### ISSUE TITLE
[Remote-SSH Bug]: 

### ISSUE THREAD

**Issue by Ena-Shepherd** [microsoft/vscode-remote-release#10000]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

Hello,
I'm trying to connect to WindowsXP through the extension.
However, choosing Windows in the ssh types forces te use of powershell, which does not exist on XP.
I didn't find a way to not use Powershell.

### Steps To Reproduce

Try to connect to a WindowsXP machine
Select Windows when the prompt asks for system type

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
> administrateur@ip's password: 
[17:10:21.256] > 
[17:10:21.349] > 'powershell' n'est pas reconnu en tant que commande interne
> ou externe, un programme ex□cutable ou un fichier de commandes.
[17:10:22.639] "install" terminal command done
[17:10:22.639] Install terminal quit with output: ou externe, un programme ex□cutable ou un fichier de commandes.
[17:10:22.640] Received install output: ou externe, un programme ex□cutable ou un fichier de commandes.
[17:10:22.641] Failed to parse remote port from server output
[17:10:22.643] Resolver error: Error: 
	at g.Create (c:\Users\yanni\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:499918)
	at t.handleInstallOutput (c:\Users\yanni\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:497240)
	at t.tryInstall (c:\Users\yanni\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:621085)
	at async c:\Users\yanni\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:580730
	at async t.withShowDetailsEvent (c:\Users\yanni\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:584036)
	at async k (c:\Users\yanni\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:577649)
	at async t.resolve (c:\Users\yanni\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:581407)
	at async c:\Users\yanni\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:848023
[17:10:22.649] ------
```

</p>
</details>

**Comment by roblourens** [comment]
Sorry, I don't think we can support Windows XP. It has been out of support for quite a while and isn't really safe to connect to the internet

**Comment by Ena-Shepherd** [comment]
Hello,
Thank you for your reply.

I know Windows XP is not secure.

I'm currently using it as a 16bits based development platform on a VM on my local network.

If you have an alternative 16 bits based system supporting VSCode, not even needing ssh, don't hesitate to tell me.

Also, WindowsXP 64 bits doesn't support 16 at my knowledge.

Have a good day.
