### ISSUE TITLE
[Remote-SSH Bug]:  main: line 58: 1719352829%N/1000000: division by 0 (error token is "N/1000000")

### ISSUE THREAD

**Issue by BloodStainedCrow** [microsoft/vscode-remote-release#10004]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

The extension manages to connect

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[00:00:25.218] Log Level: 2
[00:00:25.234] SSH Resolver called for "ssh-remote+nixosnas", attempt 1
[00:00:25.235] "remote.SSH.useLocalServer": false
[00:00:25.235] "remote.SSH.useExecServer": true
[00:00:25.235] "remote.SSH.showLoginTerminal": true
[00:00:25.235] "remote.SSH.remotePlatform": {"ggsrv.nico.icu":"linux","10.109.56.7":"linux","192.168.178.40":"linux","192.168.178.51":"linux","srv3.nico.icu":"linux","192.168.0.227":"linux","login23-1.hpc.itc.rwth-aachen.de":"linux","nixosnas":"linux"}
[00:00:25.235] "remote.SSH.path": undefined
[00:00:25.235] "remote.SSH.configFile": undefined
[00:00:25.235] "remote.SSH.useFlock": true
[00:00:25.235] "remote.SSH.lockfilesInTmp": false
[00:00:25.235] "remote.SSH.localServerDownload": auto
[00:00:25.236] "remote.SSH.remoteServerListenOnSocket": false
[00:00:25.236] "remote.SSH.showLoginTerminal": true
[00:00:25.236] "remote.SSH.defaultExtensions": []
[00:00:25.236] "remote.SSH.loglevel": 2
[00:00:25.236] "remote.SSH.enableDynamicForwarding": true
[00:00:25.236] "remote.SSH.enableRemoteCommand": false
[00:00:25.236] "remote.SSH.serverPickPortsFromRange": {}
[00:00:25.236] "remote.SSH.serverInstallPath": {}
[00:00:25.240] VS Code version: 1.90.2
[00:00:25.240] Remote-SSH version: remote-ssh@0.112.0
[00:00:25.240] win32 x64
[00:00:25.242] SSH Resolver called for host: nixosnas
[00:00:25.242] Setting up SSH remote "nixosnas"
[00:00:25.245] Using commit id "5437499feb04f7a586f677b155b039bc2b3669eb" and quality "stable" for server
[00:00:25.249] Install and start server if needed
[00:00:25.252] Checking ssh with "C:\Program Files\OpenSSH\ssh.exe -V"
[00:00:25.280] > OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2

[00:00:25.284] Running script with connection command: "C:\Program Files\OpenSSH\ssh.exe" -T -D 7601 nixosnas bash
[00:00:25.286] Terminal shell path: C:\Windows\System32\cmd.exe
[00:00:25.640] > ]0;C:\Windows\System32\cmd.exe
[00:00:25.640] Got some output, clearing connection timeout
[00:00:25.670] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[00:00:26.760] > Enter passphrase for key 'C:\Users\REDACTED/.ssh/id_rsa': 
[00:00:29.642] > 
[00:00:29.860] > 0494e21da5b5: running
[00:00:29.892] > Installing to /home/nixos/.vscode-server...
> main: line 58: 1719352829%N/1000000: division by 0 (error token is "N/1000000")
> 0494e21da5b5%%1%%
[00:00:29.907] > Downloading with curl
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed  
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 
[00:00:30.408] >   0     0    0     0    0     0    
[00:00:30.423] >   0      0 --:--:-- --:--:-- --:--:--     0
[00:00:31.405] >   0     0    0     0    0     0   
[00:00:31.421] >    0      0 --:--:--  0:00:01 --:--:--     0
[00:00:32.399] >   0     0    0     0    0     0  
[00:00:32.431] >     0      0 --:--:--  0:00:02 --:--:--     0
[00:00:33.413] >   0     0    0     0    0     0   
[00:00:33.429] >    0      0 --:--:--  0:00:03 --:--:--     0
[00:00:34.409] >   0     0    0     0    0     0   
[00:00:34.425] >    0      0 --:--:--  0:00:04 --:--:--     0
[00:00:35.413] >   0     0    0     0    0     0   
[00:00:35.430] >    0      0 --:--:--  0:00:05 --:--:--     0
[00:00:36.417] >   0     0    0     0    0     0   
[00:00:36.433] >    0      0 --:--:--  0:00:06 --:--:--     0
[00:00:36.891] >   0     0    0     0    0     0     0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
> curl: (28) Resolving timed out after 7001 milliseconds
> curl download failed
> 000
> printenv:
>     SHELL=/run/current-system/sw/bin/bash
>     __ETC_PROFILE_DONE=1
>     XDG_CONFIG_DIRS=/etc/xdg:/home/nixos/.nix-profile/etc/xdg:/nix/profile/etc/xdg:/home/nixos/.local/state/nix/profile/etc/xdg:/etc/profiles/per-user/nixos/etc/xdg:/nix/var/nix/profiles/default/etc/xdg:/run/current-system/sw/etc/xdg
>     XCURSOR_PATH=/home/nixos/.icons:/home/nixos/.local/share/icons:/home/nixos/.nix-profile/share/icons:/home/nixos/.nix-profile/share/pixmaps:/nix/profile/share/icons:/nix/profile/share/pixmaps:/home/nixos/.local/state/nix/profile/share/icons:/home/nixos/.local/state/nix/profile/share/pixm
> aps:/etc/profiles/per-user/nixos/share/icons:/etc/profiles/per-user/nixos/share/pixmaps:/nix/var/nix/profiles/default/share/icons:/nix/var/nix/profiles/default/share/pixmaps:/run/current-system/sw/share/icons:/run/current-system/sw/share/pixmaps
>     NO_AT_BRIDGE=1
>     EDITOR=nano
>     PWD=/home/nixos/.vscode-server
>     NIX_PROFILES=/run/current-system/sw /nix/var/nix/profiles/default /etc/profiles/per-user/nixos /home/nixos/.local/state/nix/profile /nix/profile /home/nixos/.nix-profile
>     LOGNAME=nixos
>     XDG_SESSION_TYPE=tty
>     NIX_PATH=nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels
>     NIXPKGS_CONFIG=/etc/nix/nixpkgs-config.nix
>     HOME=/home/nixos
>     SSH_ASKPASS=
>     LANG=en_US.UTF-8
>     VSCODE_AGENT_FOLDER=/home/nixos/.vscode-server
>     SSH_CONNECTION=192.168.0.206 7602 192.168.0.227 22
>     DIRENV_CONFIG=/etc/direnv
>     GTK_A11Y=none
>     NIX_USER_PROFILE_DIR=/nix/var/nix/profiles/per-user/nixos
>     INFOPATH=/home/nixos/.nix-profile/info:/home/nixos/.nix-profile/share/info:/nix/profile/info:/nix/profile/share/info:/home/nixos/.local/state/nix/profile/info:/home/nixos/.local/state/nix/profile/share/info:/etc/profiles/per-user/nixos/info:/etc/profiles/per-user/nixos/share/info:/nix/v
> ar/nix/profiles/default/info:/nix/var/nix/profiles/default/share/info:/run/current-system/sw/info:/run/current-system/sw/share/info
>     XDG_SESSION_CLASS=user
>     TERM=dumb
>     GTK_PATH=/home/nixos/.nix-profile/lib/gtk-2.0:/home/nixos/.nix-profile/lib/gtk-3.0:/home/nixos/.nix-profile/lib/gtk-4.0:/nix/profile/lib/gtk-2.0:/nix/profile/lib/gtk-3.0:/nix/profile/lib/gtk-4.0:/home/nixos/.local/state/nix/profile/lib/gtk-2.0:/home/nixos/.local/state/nix/profile/lib/gt
> k-3.0:/home/nixos/.local/state/nix/profile/lib/gtk-4.0:/etc/profiles/per-user/nixos/lib/gtk-2.0:/etc/profiles/per-user/nixos/lib/gtk-3.0:/etc/profiles/per-user/nixos/lib/gtk-4.0:/nix/var/nix/profiles/default/lib/gtk-2.0:/nix/var/nix/profiles/default/lib/gtk-3.0:/nix/var/nix/profiles/default
> /lib/gtk-4.0:/run/current-system/sw/lib/gtk-2.0:/run/current-system/sw/lib/gtk-3.0:/run/current-system/sw/lib/gtk-4.0
>     LESSOPEN=|/nix/store/vvgsqypyjpnkc2v4if35dxx74lmfp6ag-lesspipe-2.10/bin/lesspipe.sh %s
>     USER=nixos
>     TZDIR=/etc/zoneinfo
>     SHLVL=1
>     PAGER=less
>     QTWEBKIT_PLUGIN_PATH=/home/nixos/.nix-profile/lib/mozilla/plugins/:/nix/profile/lib/mozilla/plugins/:/home/nixos/.local/state/nix/profile/lib/mozilla/plugins/:/etc/profiles/per-user/nixos/lib/mozilla/plugins/:/nix/var/nix/profiles/default/lib/mozilla/plugins/:/run/current-system/sw/lib/
[00:00:36.900] > 
> mozilla/plugins/
>     __NIXOS_SET_ENVIRONMENT_DONE=1
>     XDG_SESSION_ID=29
>     LOCALE_ARCHIVE=/run/current-system/sw/lib/locale/locale-archive
>     LESSKEYIN_SYSTEM=/nix/store/ixsi2y9nba0lsc86nb09hg3k60j7wsx2-lessconfig
>     TERMINFO_DIRS=/home/nixos/.nix-profile/share/terminfo:/nix/profile/share/terminfo:/home/nixos/.local/state/nix/profile/share/terminfo:/etc/profiles/per-user/nixos/share/terminfo:/nix/var/nix/profiles/default/share/terminfo:/run/current-system/sw/share/terminfo
>     XDG_RUNTIME_DIR=/run/user/1000
>     SSH_CLIENT=192.168.0.206 7602 22
>     XDG_DATA_DIRS=/nix/store/8cpsc8d75ps27d6gzcdrdysipddkvpfb-desktops/share:/home/nixos/.nix-profile/share:/nix/profile/share:/home/nixos/.local/state/nix/profile/share:/etc/profiles/per-user/nixos/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share
>     LIBEXEC_PATH=/home/nixos/.nix-profile/lib/libexec:/nix/profile/lib/libexec:/home/nixos/.local/state/nix/profile/lib/libexec:/etc/profiles/per-user/nixos/lib/libexec:/nix/var/nix/profiles/default/lib/libexec:/run/current-system/sw/lib/libexec
>     PATH=/run/wrappers/bin:/home/nixos/.nix-profile/bin:/nix/profile/bin:/home/nixos/.local/state/nix/profile/bin:/etc/profiles/per-user/nixos/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
>     OLDPWD=/home/nixos
>     _=/run/current-system/sw/bin/printenv
> Trigger local server download
> 0494e21da5b5:trigger_server_download
> artifact==cli-alpine-x64==
> destFolder==/home/nixos/.vscode-server==
> destFolder2==/vscode-cli-5437499feb04f7a586f677b155b039bc2b3669eb.tar.gz==
> 0494e21da5b5:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/nixos/.vscode-server/vscode-cli-5437499feb04f7a586f677b155b039bc2b3669eb.tar.gz.done and vscode-server.tar.gz to exist
[00:00:36.900] Got request to download on client for {"artifact":"cli-alpine-x64","destPath":"/home/nixos/.vscode-server/vscode-cli-5437499feb04f7a586f677b155b039bc2b3669eb.tar.gz"}
[00:00:36.901] Downloading VS Code server locally...
[00:00:36.915] > 
> 
[00:00:37.922] Downloaded VS Code server to c:\Users\REDACTED\AppData\Local\Temp\03d8076b-6159-4903-a5d3-cae86f650052
[00:00:37.922] Renamed VS Code server to c:\Users\REDACTED\AppData\Local\Temp\vscode_server_1719352837922\vscode-cli-5437499feb04f7a586f677b155b039bc2b3669eb.tar.gz
[00:00:37.924] Checking ssh with "C:\Program Files\OpenSSH\ssh.exe -V"
[00:00:37.947] > OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2

[00:00:37.949] Expecting scp to be next to ssh at C:\Program Files\OpenSSH\scp.exe
[00:00:37.949] Testing scp with "C:\Program Files\OpenSSH\scp.exe"
[00:00:37.977] scp exited with code: 1
[00:00:37.977] Got stderr from scp: usage: scp [-346ABCOpqRrsTv] [-c cipher] [-D sftp_server_path] [-F ssh_config]
           [-i identity_file] [-J destination] [-l limit] [-o ssh_option]
           [-P port] [-S program] [-X sftp_option] source ... target
[00:00:37.977] Copying file to remote with "C:\Program Files\OpenSSH\scp.exe" "c:\Users\Tim\AppData\Local\Temp\vscode_server_1719352837922\vscode-cli-5437499feb04f7a586f677b155b039bc2b3669eb.tar.gz" "vscode-cli-5437499feb04f7a586f677b155b039bc2b3669eb.tar.gz.done" nixosnas:"/home/nixos/.vscode-server"
[00:00:37.977] Using cwd: file:///c%3A/Users/Tim/AppData/Local/Temp/vscode_server_1719352837922
[00:00:37.978] Terminal shell path: C:\Windows\System32\cmd.exe
[00:00:38.101] >     SSH_CLIENT=192.168.0.206 7602 22
>     XDG_DATA_DIRS=/nix/store/8cpsc8d75ps27d6gzcdrdysipddkvpfb-desktops/share:/home/nixos/.nix-profile/share:/nix/profile/share:/home/nixos/.local/state/nix/profile/share:/etc/profiles/per-user/nixos/share:/nix/var/nix/profiles/default/share:/run/current-syst
> em/sw/share
>     LIBEXEC_PATH=/home/nixos/.nix-profile/lib/libexec:/nix/profile/lib/libexec:/home/nixos/.local/state/nix/profile/lib/libexec:/etc/profiles/per-user/nixos/lib/libexec:/nix/var/nix/profiles/default/lib/libexec:/run/current-system/sw/lib/libexec
>     PATH=/run/wrappers/bin:/home/nixos/.nix-profile/bin:/nix/profile/bin:/home/nixos/.local/state/nix/profile/bin:/etc/profiles/per-user/nixos/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
>     OLDPWD=/home/nixos
>     _=/run/current-system/sw/bin/printenv
> Trigger local server download
> 0494e21da5b5:trigger_server_download
> artifact==cli-alpine-x64==
> destFolder==/home/nixos/.vscode-server==
> destFolder2==/vscode-cli-5437499feb04f7a586f677b155b039bc2b3669eb.tar.gz==
> 0494e21da5b5:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/nixos/.vscode-server/vscode-cli-5437499feb04f7a586f677b155b039bc2b3669eb.tar.gz.done and vscode-server.tar.gz to exist
> 
[00:00:38.133] > ]0;C:\Windows\System32\cmd.exe
[00:00:38.148] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[00:00:39.245] > Enter passphrase for key 'C:\Users\REDACTED/.ssh/id_rsa': 
[00:01:50.016] > 
[00:01:50.234] > vscode-cli-5437499feb04f7a586f677b155b039bc2b3669eb.tar.gz                                                                                                                                                                        0%    0     0.0KB/s   --:-- ETA
[00:01:50.311] > vscode-cli-5437499feb04f7a586f677b155b039bc2b3669eb.tar.gz                                                                                                                                                                      100% 8752KB 109.6MB/s   00:00    
[00:01:50.327] > 
[00:01:50.343] > vscode-cli-5437499feb04f7a586f677b155b039bc2b3669eb.tar.gz.done                                                                                                                                                                   0%    0     0.0KB/s   --:-- ETA
[00:01:50.373] > vscode-cli-5437499feb04f7a586f677b155b039bc2b3669eb.tar.gz.done                                                                                                                                                                 100%    9     0.0KB/s   00:00    
[00:01:51.636] "Copy server to host" terminal command done
[00:01:51.713] >     SSH_CLIENT=192.168.0.206 7602 22
>     XDG_DATA_DIRS=/nix/store/8cpsc8d75ps27d6gzcdrdysipddkvpfb-desktops/share:/home/nixos/.nix-profile/share:/nix/profile/share:/home/nixos/.local/state/nix/profile/share:/etc/profiles/per-user/nixos/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share
>     LIBEXEC_PATH=/home/nixos/.nix-profile/lib/libexec:/nix/profile/lib/libexec:/home/nixos/.local/state/nix/profile/lib/libexec:/etc/profiles/per-user/nixos/lib/libexec:/nix/var/nix/profiles/default/lib/libexec:/run/current-system/sw/lib/libexec
>     PATH=/run/wrappers/bin:/home/nixos/.nix-profile/bin:/nix/profile/bin:/home/nixos/.local/state/nix/profile/bin:/etc/profiles/per-user/nixos/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
>     OLDPWD=/home/nixos
>     _=/run/current-system/sw/bin/printenv
> Trigger local server download
> 0494e21da5b5:trigger_server_download
> artifact==cli-alpine-x64==
> destFolder==/home/nixos/.vscode-server==
> destFolder2==/vscode-cli-5437499feb04f7a586f677b155b039bc2b3669eb.tar.gz==
> 0494e21da5b5:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/nixos/.vscode-server/vscode-cli-5437499feb04f7a586f677b155b039bc2b3669eb.tar.gz.done and vscode-server.tar.gz to exist
> 
> 
[00:01:51.929] > Found flag and server on host
> main: line 58: 1719352911%N/1000000: division by 0 (error token is "N/1000000")
> 0494e21da5b5%%2%%
> tar --version:
> tar (busybox) 1.36.1
[00:01:51.945] > 
[00:01:52.146] > main: line 58: 1719352911%N/1000000: division by 0 (error token is "N/1000000")
> main: line 66: - : syntax error: operand expected (error token is "- ")
> code 1.90.2 (commit 5437499feb04f7a586f677b155b039bc2b3669eb)
> Starting VS Code CLI... "/home/nixos/.vscode-server/code-5437499feb04f7a586f677b155b039bc2b3669eb" command-shell --cli-data-dir "/home/nixos/.vscode-server/cli" --on-port --on-host=127.0.0.1 --parent-process-id 29160 &> "/home/nixos/.vscode-server/.cli.5437499feb04f7a586f677b155b039bc2b3669
[00:01:52.154] > 
> eb.log" < /dev/null
> printenv:
>     SHELL=/run/current-system/sw/bin/bash
>     __ETC_PROFILE_DONE=1
>     XDG_CONFIG_DIRS=/etc/xdg:/home/nixos/.nix-profile/etc/xdg:/nix/profile/etc/xdg:/home/nixos/.local/state/nix/profile/etc/xdg:/etc/profiles/per-user/nixos/etc/xdg:/nix/var/nix/profiles/default/etc/xdg:/run/current-system/sw/etc/xdg
>     XCURSOR_PATH=/home/nixos/.icons:/home/nixos/.local/share/icons:/home/nixos/.nix-profile/share/icons:/home/nixos/.nix-profile/share/pixmaps:/nix/profile/share/icons:/nix/profile/share/pixmaps:/home/nixos/.local/state/nix/profile/share/icons:/home/nixos/.local/state/nix/profile/share/pixm
> aps:/etc/profiles/per-user/nixos/share/icons:/etc/profiles/per-user/nixos/share/pixmaps:/nix/var/nix/profiles/default/share/icons:/nix/var/nix/profiles/default/share/pixmaps:/run/current-system/sw/share/icons:/run/current-system/sw/share/pixmaps
>     NO_AT_BRIDGE=1
>     EDITOR=nano
>     PWD=/home/nixos
>     NIX_PROFILES=/run/current-system/sw /nix/var/nix/profiles/default /etc/profiles/per-user/nixos /home/nixos/.local/state/nix/profile /nix/profile /home/nixos/.nix-profile
>     LOGNAME=nixos
>     XDG_SESSION_TYPE=tty
>     NIX_PATH=nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels
>     NIXPKGS_CONFIG=/etc/nix/nixpkgs-config.nix
>     HOME=/home/nixos
>     SSH_ASKPASS=
>     LANG=en_US.UTF-8
>     VSCODE_AGENT_FOLDER=/home/nixos/.vscode-server
>     SSH_CONNECTION=192.168.0.206 7602 192.168.0.227 22
>     DIRENV_CONFIG=/etc/direnv
>     GTK_A11Y=none
>     NIX_USER_PROFILE_DIR=/nix/var/nix/profiles/per-user/nixos
>     INFOPATH=/home/nixos/.nix-profile/info:/home/nixos/.nix-profile/share/info:/nix/profile/info:/nix/profile/share/info:/home/nixos/.local/state/nix/profile/info:/home/nixos/.local/state/nix/profile/share/info:/etc/profiles/per-user/nixos/info:/etc/profiles/per-user/nixos/share/info:/nix/v
> ar/nix/profiles/default/info:/nix/var/nix/profiles/default/share/info:/run/current-system/sw/info:/run/current-system/sw/share/info
>     XDG_SESSION_CLASS=user
>     TERM=dumb
>     GTK_PATH=/home/nixos/.nix-profile/lib/gtk-2.0:/home/nixos/.nix-profile/lib/gtk-3.0:/home/nixos/.nix-profile/lib/gtk-4.0:/nix/profile/lib/gtk-2.0:/nix/profile/lib/gtk-3.0:/nix/profile/lib/gtk-4.0:/home/nixos/.local/state/nix/profile/lib/gtk-2.0:/home/nixos/.local/state/nix/profile/lib/gt
> k-3.0:/home/nixos/.local/state/nix/profile/lib/gtk-4.0:/etc/profiles/per-user/nixos/lib/gtk-2.0:/etc/profiles/per-user/nixos/lib/gtk-3.0:/etc/profiles/per-user/nixos/lib/gtk-4.0:/nix/var/nix/profiles/default/lib/gtk-2.0:/nix/var/nix/profiles/default/lib/gtk-3.0:/nix/var/nix/profiles/default
> /lib/gtk-4.0:/run/current-system/sw/lib/gtk-2.0:/run/current-system/sw/lib/gtk-3.0:/run/current-system/sw/lib/gtk-4.0
>     LESSOPEN=|/nix/store/vvgsqypyjpnkc2v4if35dxx74lmfp6ag-lesspipe-2.10/bin/lesspipe.sh %s
>     USER=nixos
>     TZDIR=/etc/zoneinfo
>     SHLVL=1
>     PAGER=less
>     QTWEBKIT_PLUGIN_PATH=/home/nixos/.nix-profile/lib/mozilla/plugins/:/nix/profile/lib/mozilla/plugins/:/home/nixos/.local/state/nix/profile/lib/mozilla/plugins/:/etc/profiles/per-user/nixos/lib/mozilla/plugins/:/nix/var/nix/profiles/default/lib/mozilla/plugins/:/run/current-system/sw/lib/
> mozilla/plugins/
>     __NIXOS_SET_ENVIRONMENT_DONE=1
>     XDG_SESSION_ID=29
>     LOCALE_ARCHIVE=/run/current-system/sw/lib/locale/locale-archive
>     LESSKEYIN_SYSTEM=/nix/store/ixsi2y9nba0lsc86nb09hg3k60j7wsx2-lessconfig
>     TERMINFO_DIRS=/home/nixos/.nix-profile/share/terminfo:/nix/profile/share/terminfo:/home/nixos/.local/state/nix/profile/share/terminfo:/etc/profiles/per-user/nixos/share/terminfo:/nix/var/nix/profiles/default/share/terminfo:/run/current-system/sw/share/terminfo
>     XDG_RUNTIME_DIR=/run/user/1000
>     SSH_CLIENT=192.168.0.206 7602 22
>     XDG_DATA_DIRS=/nix/store/8cpsc8d75ps27d6gzcdrdysipddkvpfb-desktops/share:/home/nixos/.nix-profile/share:/nix/profile/share:/home/nixos/.local/state/nix/profile/share:/etc/profiles/per-user/nixos/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share
>     LIBEXEC_PATH=/home/nixos/.nix-profile/lib/libexec:/nix/profile/lib/libexec:/home/nixos/.local/state/nix/profile/lib/libexec:/etc/profiles/per-user/nixos/lib/libexec:/nix/var/nix/profiles/default/lib/libexec:/run/current-system/sw/lib/libexec
>     PATH=/run/wrappers/bin:/home/nixos/.nix-profile/bin:/nix/profile/bin:/home/nixos/.local/state/nix/profile/bin:/etc/profiles/per-user/nixos/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
>     OLDPWD=/home/nixos/.vscode-server
>     _=/run/current-system/sw/bin/printenv
> main: line 58: 1719352911%N/1000000: division by 0 (error token is "N/1000000")
[00:01:52.161] > 
> Spawned remote CLI: 29339
> ps: invalid option -- 'p'
> BusyBox v1.36.1 () multi-call binary.
> 
> Usage: ps [-o COL1,COL2=HEADER] [-T]
> 
> Show list of processes
> 
>         -o COL1,COL2=HEADER     Select columns for display
>         -T                      Show threads
> Exec server process not found
> main: line 58: 1719352911%N/1000000: division by 0 (error token is "N/1000000")
> 0494e21da5b5: start
> SSH_AUTH_SOCK====
> DISPLAY====
> listeningOn====
> osReleaseId==nixos==
> arch==x86_64==
> vscodeArch==x64==
[00:01:52.178] > 
> bitness==64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult==success==
> didLocalDownload==1==
> downloadTime====
> installTime====
> serverStartTime====
> execServerToken==a11a1aaa-a111-11a1-a111-aa1111aa111a==
> 0494e21da5b5: end
> main: line 66: - : syntax error: operand expected (error token is "- ")
[00:01:52.178] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====
listeningOn====
osReleaseId==nixos==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult==success==
didLocalDownload==1==
downloadTime====
installTime====
serverStartTime====
execServerToken==a11a1aaa-a111-11a1-a111-aa1111aa111a==

[00:01:52.179] Failed to parse remote port from server output
[00:01:52.180] Resolver error: Error: 
	at g.Create (c:\Users\REDACTED\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:499918)
	at t.handleInstallOutput (c:\Users\REDACTED\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:497240)
	at t.tryInstall (c:\Users\REDACTED\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:621085)
	at async c:\Users\REDACTED\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:580730
	at async t.withShowDetailsEvent (c:\Users\REDACTED\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:584036)
	at async k (c:\Users\REDACTED\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:577649)
	at async t.resolve (c:\Users\REDACTED\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:581407)
	at async c:\Users\REDACTED\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:848023
[00:01:52.184] ------




[00:01:52.624] Opening exec server for ssh-remote+nixosnas
[00:01:52.709] Initizing new exec server for ssh-remote+nixosnas
[00:01:52.711] Using commit id "5437499feb04f7a586f677b155b039bc2b3669eb" and quality "stable" for server
[00:01:52.713] Install and start server if needed
[00:01:52.732] Opening exec server for ssh-remote+nixosnas
[00:01:52.778] Running script with connection command: "C:\Program Files\OpenSSH\ssh.exe" -T -D 7601 nixosnas bash
[00:01:52.780] Terminal shell path: C:\Windows\System32\cmd.exe
[00:01:52.925] > DISPLAY====
> listeningOn====
> osReleaseId==nixos==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult==success==
> didLocalDownload==1==
> downloadTime====
> installTime====
> serverStartTime====
> execServerToken==a11a1aaa-a111-11a1-a111-aa1111aa111a==
> 0494e21da5b5: end
> main: line 66: - : syntax error: operand expected (error token is "- ")
> 
[00:01:52.942] > ]0;C:\Windows\System32\cmd.exe
[00:01:52.942] Got some output, clearing connection timeout
[00:01:52.958] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[00:01:54.079] > Enter passphrase for key 'C:\Users\REDACTED/.ssh/id_rsa': 

```

</p>
</details>

**Comment by BloodStainedCrow** [comment]
Downgrading from VSCode 1.90 to 1.84 fixed the issue.

**Comment by BloodStainedCrow** [comment]
*Nevermind, after a downgrade it worked for a short time, but I kept reconnecting.
And now I once again cannot connect  again with the same error

**Comment by roblourens** [comment]
Looks like this falls under https://github.com/microsoft/vscode-remote-release/issues/1747

**Comment by BloodStainedCrow** [comment]
Thank you, for pointing me in the correct direction!

You are correct. As soon as I uninstalled BusyBox on the remote machine I could connect flawlessly!
Even if it is not doable to add busybox support, is it maybe possible to improve the error message to point the user in the correct direction?

Another thing that confuses me, is that it worked with busybox installed for days and just randomly broke
