### ISSUE TITLE
[Remote-SSH Bug]: /c: /c: Is a directory error

### ISSUE THREAD

**Issue by gooneraki** [microsoft/vscode-remote-release#10012]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[14:51:29.514] Log Level: 1
[14:51:29.533] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a2243594c45464150503231227d", attempt 1
[14:51:29.533] "remote.SSH.useLocalServer": false
[14:51:29.534] "remote.SSH.useExecServer": true
[14:51:29.535] "remote.SSH.showLoginTerminal": true
[14:51:29.535] "remote.SSH.remotePlatform": {}
[14:51:29.536] "remote.SSH.path": undefined
[14:51:29.536] "remote.SSH.configFile": undefined
[14:51:29.536] "remote.SSH.useFlock": true
[14:51:29.536] "remote.SSH.lockfilesInTmp": false
[14:51:29.536] "remote.SSH.localServerDownload": auto
[14:51:29.536] "remote.SSH.remoteServerListenOnSocket": false
[14:51:29.536] "remote.SSH.showLoginTerminal": true
[14:51:29.536] "remote.SSH.defaultExtensions": []
[14:51:29.537] "remote.SSH.loglevel": 1
[14:51:29.537] "remote.SSH.enableDynamicForwarding": true
[14:51:29.537] "remote.SSH.enableRemoteCommand": false
[14:51:29.537] "remote.SSH.serverPickPortsFromRange": {}
[14:51:29.538] "remote.SSH.serverInstallPath": {}
[14:51:29.551] SSH Resolver called for host: [HOSTNAME]
[14:51:29.551] Setting up SSH remote "[HOSTNAME]"
[14:51:29.556] VS Code version: 1.90.2
[14:51:29.556] Remote-SSH version: remote-ssh@0.112.0
[14:51:29.556] win32 x64
[14:51:29.560] Using commit id "5437499feb04f7a586f677b155b039bc2b3669eb" and quality "stable" for server
[14:51:29.562] Install and start server if needed
[14:51:34.092] Checking ssh with "C:\Program Files (x86)\Common Files\Oracle\Java\java8path\ssh.exe -V"
[14:51:34.096] Got error from ssh: spawn C:\Program Files (x86)\Common Files\Oracle\Java\java8path\ssh.exe ENOENT
[14:51:34.096] Checking ssh with "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe -V"
[14:51:34.098] Got error from ssh: spawn C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[14:51:34.098] Checking ssh with "C:\windows\system32\ssh.exe -V"
[14:51:34.100] Got error from ssh: spawn C:\windows\system32\ssh.exe ENOENT
[14:51:34.100] Checking ssh with "C:\windows\ssh.exe -V"
[14:51:34.101] Got error from ssh: spawn C:\windows\ssh.exe ENOENT
[14:51:34.102] Checking ssh with "C:\windows\System32\Wbem\ssh.exe -V"
[14:51:34.103] Got error from ssh: spawn C:\windows\System32\Wbem\ssh.exe ENOENT
[14:51:34.103] Checking ssh with "C:\windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[14:51:34.105] Got error from ssh: spawn C:\windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[14:51:34.105] Checking ssh with "C:\windows\System32\OpenSSH\ssh.exe -V"
[14:51:34.168] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[14:51:34.176] Remote command length: 4920/8192 characters
[14:51:34.176] Running script with connection command: "C:\windows\System32\OpenSSH\ssh.exe" -T -D 60121 "[HOSTNAME]" powershell
[14:51:34.179] Terminal shell path: C:\windows\System32\cmd.exe
[14:51:34.644] "install" terminal received data: "[2J[m[H]0;C:\windows\System32\cmd.exe[?25h[25l[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[H[?25h"
[14:51:34.644] Got some output, clearing connection timeout
[14:51:35.229] "install" terminal received data: "[USER]@[HOSTNAME]'s password: "
[14:51:36.125] "install" terminal received data: "[25l[H[USER]@[HOSTNAME]'s password:[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[1;37H[?25h"
[14:51:40.610] "install" terminal received data: ""
[14:51:41.215] "install" terminal received data: "/c: /c: Is a directory"
[14:51:42.804] "install" terminal command done
[14:51:42.805] Install terminal quit with output: /c: /c: Is a directory
[14:51:42.805] Received install output: /c: /c: Is a directory
[14:51:42.805] Stopped parsing output early. Remaining text: /c: /c: Is a directory
[14:51:42.806] Failed to parse remote port from server output
[14:51:42.809] Resolver error: Error: 
	at g.Create (c:\Users\[user]\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:499918)
	at t.handleInstallOutput (c:\Users\[user]\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:497240)
	at t.tryInstall (c:\Users\[user]\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:621085)
	at async c:\Users\[user]\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:580730
	at async t.withShowDetailsEvent (c:\Users\[user]\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:584036)
	at async k (c:\Users\[user]\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:577649)
	at async t.resolve (c:\Users\[user]\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:581407)
	at async c:\Users\[user]\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:848023
[14:51:42.813] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"UnparsableOutput","exitCodeLabel":""},"measures":{"resolveAttempts":1,"isExecServer":0,"timing.totalResolveTime":13275,"timing.preSshTime":4647,"timing.scriptTime":8626}}
[14:51:42.815] ------
```

</p>
</details>

### Anything else?

In all terminals of my local machine ssh connection works (gitbash, cmd, powershell).
In "Remote ssh" VS code extension, I click connect to Connect to host... then select platform (Windows), then I type the password but then I get the `/c: /c: Is a directory` error

**Comment by gooneraki** [comment]
I can replicate this error in a terminal outside of vs code, when I add this line in my `config` file for ssh `RemoteCommand bash`

**Comment by roblourens** [comment]
> I can replicate this error in a terminal outside of vs code

It sounds like this is an issue with your configuration, and not with vscode. Sounds like it's failing to start bash, which might point at WSL or something else

**Comment by gooneraki** [comment]
Ok I see the ssh code ran by the extension is `"C:\windows\System32\OpenSSH\ssh.exe" -T -D 49784 "[MY SERVER]" powershell`. 
Changing to bash gives the same error. 

I tried variations in my command shell and got this results:
 `"C:\windows\System32\OpenSSH\ssh.exe" -D 49784 "[MY SERVER]"`: Works fine.
`"C:\windows\System32\OpenSSH\ssh.exe" "[MY SERVER]"`: Works fine.
`"C:\windows\System32\OpenSSH\ssh.exe" -T -D 49784 "[MY SERVER]"`: Error after password: `shell request failed on channel 2`
`"C:\windows\System32\OpenSSH\ssh.exe" -T -D 49784 "[MY SERVER]" powershell: Error after password: `/c: /c: Is a directory`.

So the question is if I can update remote ssh extension to accommodate these commands
