### ISSUE TITLE
It keeps repeatedly downloading the VS Code server.

### ISSUE THREAD

**Issue by allisShenYuXian** [microsoft/vscode-remote-release#10019]
🚨 The issue tracker is not for questions 🚨

I want to connect to BeagleBone Black running Debian 10 via SSH, but I encounter repeated downloads of the VS Code server and it keeps asking me to enter the password.

![螢幕擷取畫面 2024-07-01 201425](https://github.com/microsoft/vscode-remote-release/assets/160206966/f1013e5e-7410-4ce8-9ab9-73e03f2b0e3a)

**Comment by roblourens** [comment]
Please share the log from the Remote-SSH output channel, thanks

**Comment by allisShenYuXian** [comment]
My VS Code continuously cycles through "server download progress" and "server inflate progress," repeatedly asking me to enter my password.

![image](https://github.com/microsoft/vscode-remote-release/assets/160206966/1d202f88-191b-43da-b94b-8d95993d1983)

![image](https://github.com/microsoft/vscode-remote-release/assets/160206966/4335da9c-9494-41ea-851d-bd0555ef0f37)

**Comment by MurphLaws** [comment]
Same for me. This is my remote-ssh output:
```

[22:02:17.242] Log Level: 2
[22:02:17.244] SSH Resolver called for "ssh-remote+triplepatte.etis-lab.fr", attempt 1
[22:02:17.245] "remote.SSH.useLocalServer": true
[22:02:17.245] "remote.SSH.useExecServer": false
[22:02:17.245] "remote.SSH.path": undefined
[22:02:17.245] "remote.SSH.configFile": undefined
[22:02:17.245] "remote.SSH.useFlock": true
[22:02:17.245] "remote.SSH.lockfilesInTmp": false
[22:02:17.245] "remote.SSH.localServerDownload": auto
[22:02:17.245] "remote.SSH.remoteServerListenOnSocket": false
[22:02:17.245] "remote.SSH.showLoginTerminal": false
[22:02:17.245] "remote.SSH.defaultExtensions": []
[22:02:17.245] "remote.SSH.loglevel": 2
[22:02:17.245] "remote.SSH.enableDynamicForwarding": true
[22:02:17.245] "remote.SSH.enableRemoteCommand": false
[22:02:17.245] "remote.SSH.serverPickPortsFromRange": {}
[22:02:17.245] "remote.SSH.serverInstallPath": {}
[22:02:17.248] VS Code version: 1.90.2
[22:02:17.248] Remote-SSH version: remote-ssh@0.112.0
[22:02:17.248] darwin arm64
[22:02:17.248] SSH Resolver called for host: triplepatte.etis-lab.fr
[22:02:17.248] Setting up SSH remote "triplepatte.etis-lab.fr"
[22:02:17.250] Acquiring local install lock: /var/folders/l4/8ms98s3x57b8r7gtd_183_zr0000gn/T/vscode-remote-ssh-6a5e6c20-install.lock
[22:02:17.250] Looking for existing server data file at /Users/illico/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-6a5e6c20-5437499feb04f7a586f677b155b039bc2b3669eb-0.112.0-tr/data.json
[22:02:17.250] Using commit id "5437499feb04f7a586f677b155b039bc2b3669eb" and quality "stable" for server
[22:02:17.253] Install and start server if needed
[22:02:17.254] PATH: /opt/miniconda3/bin:/opt/miniconda3/condabin:/opt/homebrew/opt/node@20/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
[22:02:17.254] Checking ssh with "ssh -V"
[22:02:17.260] > OpenSSH_9.7p1, OpenSSL 3.3.1 4 Jun 2024

[22:02:17.261] askpass server listening on /var/folders/l4/8ms98s3x57b8r7gtd_183_zr0000gn/T/vscode-ssh-askpass-48dcc31e4b29b2242485c5e28bf24b031d3babdd.sock
[22:02:17.261] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/l4/8ms98s3x57b8r7gtd_183_zr0000gn/T/vscode-ssh-askpass-702243e7f1984c48149445e45024415c1965b420.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","64202","-o","ConnectTimeout=15","triplepatte.etis-lab.fr"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/illico/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-6a5e6c20-5437499feb04f7a586f677b155b039bc2b3669eb-0.112.0-tr/data.json"}
[22:02:17.261] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.4qfx0sdp3W/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/illico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/private/var/folders/l4/8ms98s3x57b8r7gtd_183_zr0000gn/T/AppTranslocation/CB88C4A0-3BD8-4ACF-B9A9-EAF087E5E5A3/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"","VSCODE_SSH_ASKPASS_MAIN":"/Users/illico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/l4/8ms98s3x57b8r7gtd_183_zr0000gn/T/vscode-ssh-askpass-48dcc31e4b29b2242485c5e28bf24b031d3babdd.sock"}
[22:02:17.262] Spawned 99606
[22:02:17.320] > local-server-1> Running ssh connection command: ssh -v -T -D 64202 -o ConnectTimeout=15 triplepatte.etis-lab.fr
[22:02:17.321] > local-server-1> Spawned ssh, pid=99611
[22:02:17.325] stderr> OpenSSH_9.7p1, OpenSSL 3.3.1 4 Jun 2024
[22:02:17.334] stderr> OpenSSH_9.7p1, OpenSSL 3.3.1 4 Jun 2024
[22:02:18.056] stderr> debug1: Server host key: ssh-ed25519 SHA256:x2TFXMGr6+zFBEOW5VpjJGOnKln1OIeULf3LxGA+fUY
[22:02:18.708] Got askpass request: {"request":" nicolass80@fandral.etis-lab.fr's password:"}
[22:02:18.708] Showing password prompt
[22:02:18.709] Listening for interwindow password on /var/folders/l4/8ms98s3x57b8r7gtd_183_zr0000gn/T/vscode-ssh-askpass-3937b9f930caae60516f935255269aae3206bdc2.sock
[22:02:18.709] Writing password prompt to globalState
[22:02:21.417] Got password response
[22:02:21.418] Interactor gave response: ***************
[22:02:21.418] Cleaning up other-window auth server
[22:02:21.610] stderr> Authenticated to fandral.etis-lab.fr ([193.51.45.192]:7722) using "password".
[22:02:22.316] stderr> debug1: Server host key: ssh-ed25519 SHA256:CqVxkj4dW8XFveShsuoP8mReX/it+jZdhWrwLQ9ubLw
[22:02:22.780] Got askpass request: {"request":" nicolass80@triplepatte.etis-lab.fr's password:"}
[22:02:22.781] Showing password prompt
[22:02:22.781] Listening for interwindow password on /var/folders/l4/8ms98s3x57b8r7gtd_183_zr0000gn/T/vscode-ssh-askpass-b9517efb1c7fc40599ff656c90ee2dbe4d7008e4.sock
[22:02:22.781] Writing password prompt to globalState
[22:02:25.452] Got password response
[22:02:25.453] Interactor gave response: ***************
[22:02:25.453] Cleaning up other-window auth server
[22:02:25.643] stderr> Authenticated to triplepatte.etis-lab.fr (via proxy) using "password".
[22:02:26.284] > Welcome to Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-97-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/pro
> 
>   System information as of mar. 02 juil. 2024 05:02:12 CEST
> 
>   System load:    1.10302734375      Temperature:           33.0 C
>   Usage of /home: 0.0% of 219.88GB   Processes:             357
>   Memory usage:   5%                 Users logged in:       0
>   Swap usage:     0%                 IPv4 address for eno1: 10.10.5.181
> 
>  * Strictly confined Kubernetes makes edge and IoT secure. Learn how MicroK8s
>    just raised the bar for easy, resilient and secure K8s cluster deployment.
> 
>    https://ubuntu.com/engage/secure-kubernetes-at-the-edge
[22:02:26.487] > ready: f4aa032bb566
[22:02:26.654] > Linux 5.15.0-97-generic #107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024
[22:02:26.655] Platform: linux
[22:02:26.819] > /bin/bash
[22:02:26.819] Shell: bash
[22:02:26.820] Creating bash subshell inside "bash"
[22:02:26.986] > bash version:  5.1.16(1)-release
[22:02:27.146] > bash version:  5.1.16(1)-release
> bash version:  5.1.16(1)-release
> bash version:  5.1.16(1)-release
[22:02:27.306] > f4aa032bb566: running
> Acquiring lock on /users/nicolass80/.vscode-server/bin/5437499feb04f7a586f677b155b039bc2b3669eb/vscode-remote-lock.nicolass80.5437499feb04f7a586f677b155b039bc2b3669eb
[22:02:33.369] stderr> flock: 99: No locks available
[22:02:33.530] > Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> f4aa032bb566: start
> exitCode==24==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/100697==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> f4aa032bb566: end
[22:02:33.531] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/100697==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[22:02:33.532] Server installation process already in progress - waiting and retrying
[22:02:33.533] Terminating local server
[22:02:33.548] Local server exit: 15
[22:02:34.540] askpass server listening on /var/folders/l4/8ms98s3x57b8r7gtd_183_zr0000gn/T/vscode-ssh-askpass-f7bf12496a9d70d81aaefe14c99c4e15125beec2.sock
[22:02:34.541] Spawning local server with {"serverId":2,"ipcHandlePath":"/var/folders/l4/8ms98s3x57b8r7gtd_183_zr0000gn/T/vscode-ssh-askpass-cedcd6bb62e6b583e19af9ad20ce47e0cf419f28.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","64202","-o","ConnectTimeout=15","triplepatte.etis-lab.fr"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/illico/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-6a5e6c20-5437499feb04f7a586f677b155b039bc2b3669eb-0.112.0-tr/data.json"}
[22:02:34.541] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.4qfx0sdp3W/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/illico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/private/var/folders/l4/8ms98s3x57b8r7gtd_183_zr0000gn/T/AppTranslocation/CB88C4A0-3BD8-4ACF-B9A9-EAF087E5E5A3/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"","VSCODE_SSH_ASKPASS_MAIN":"/Users/illico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/l4/8ms98s3x57b8r7gtd_183_zr0000gn/T/vscode-ssh-askpass-f7bf12496a9d70d81aaefe14c99c4e15125beec2.sock"}
[22:02:34.542] Spawned 99770
[22:02:34.612] > local-server-2> Running ssh connection command: ssh -v -T -D 64202 -o ConnectTimeout=15 triplepatte.etis-lab.fr
[22:02:34.613] > local-server-2> Spawned ssh, pid=99775
[22:02:34.632] stderr> OpenSSH_9.7p1, OpenSSL 3.3.1 4 Jun 2024
[22:02:34.641] stderr> OpenSSH_9.7p1, OpenSSL 3.3.1 4 Jun 2024
[22:02:35.345] stderr> debug1: Server host key: ssh-ed25519 SHA256:x2TFXMGr6+zFBEOW5VpjJGOnKln1OIeULf3LxGA+fUY
[22:02:36.005] Got askpass request: {"request":" nicolass80@fandral.etis-lab.fr's password:"}
[22:02:36.005] Showing password prompt
[22:02:36.005] Listening for interwindow password on /var/folders/l4/8ms98s3x57b8r7gtd_183_zr0000gn/T/vscode-ssh-askpass-9bb4b2f881756ccdb03e343217fa48f003f9926f.sock
[22:02:36.005] Writing password prompt to globalState
[22:02:49.639] stderr> Connection timed out during banner exchange
[22:02:49.639] stderr> Connection to UNKNOWN port 65535 timed out
[22:02:49.640] > local-server-2> ssh child died, shutting down
[22:02:49.646] Local server exit: 0
[22:02:49.646] Received install output: local-server-2> Running ssh connection command: ssh -v -T -D 64202 -o ConnectTimeout=15 triplepatte.etis-lab.fr
local-server-2> Spawned ssh, pid=99775
OpenSSH_9.7p1, OpenSSL 3.3.1 4 Jun 2024
OpenSSH_9.7p1, OpenSSL 3.3.1 4 Jun 2024
debug1: Server host key: ssh-ed25519 SHA256:x2TFXMGr6+zFBEOW5VpjJGOnKln1OIeULf3LxGA+fUY
Connection timed out during banner exchange
Connection to UNKNOWN port 65535 timed out
local-server-2> ssh child died, shutting down

[22:02:49.649] Resolver error: Error: The connection timed out
	at g.Offline (/Users/illico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:499969)
	at /Users/illico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:495860
	at t.handleInstallOutput (/Users/illico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:496175)
	at e (/Users/illico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:558422)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /Users/illico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:580377
	at async t.withShowDetailsEvent (/Users/illico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:584036)
	at async /Users/illico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:555127
	at async T (/Users/illico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:553178)
	at async t.resolveWithLocalServer (/Users/illico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:554667)
	at async k (/Users/illico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:577548)
	at async t.resolve (/Users/illico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:581407)
	at async /Users/illico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:848023
[22:02:49.652] ------




[22:02:49.786] Opening exec server for ssh-remote+triplepatte.etis-lab.fr
[22:02:49.803] Initizing new exec server for ssh-remote+triplepatte.etis-lab.fr
[22:02:49.804] Acquiring local install lock: /var/folders/l4/8ms98s3x57b8r7gtd_183_zr0000gn/T/vscode-remote-ssh-6a5e6c20-install.lock
[22:02:49.805] Looking for existing server data file at /Users/illico/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-6a5e6c20-5437499feb04f7a586f677b155b039bc2b3669eb-0.112.0-es/data.json
[22:02:49.805] Using commit id "5437499feb04f7a586f677b155b039bc2b3669eb" and quality "stable" for server
[22:02:49.807] Install and start server if needed
[22:02:49.813] askpass server listening on /var/folders/l4/8ms98s3x57b8r7gtd_183_zr0000gn/T/vscode-ssh-askpass-756e23589ba040801197b38122ad6dc2daa194b1.sock
[22:02:49.813] Spawning local server with {"serverId":3,"ipcHandlePath":"/var/folders/l4/8ms98s3x57b8r7gtd_183_zr0000gn/T/vscode-ssh-askpass-4fc4d868b7a88be5c34fc511fc4476ba5444f680.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","64212","-o","ConnectTimeout=15","triplepatte.etis-lab.fr"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/illico/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-6a5e6c20-5437499feb04f7a586f677b155b039bc2b3669eb-0.112.0-es/data.json"}
[22:02:49.813] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.4qfx0sdp3W/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/illico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/private/var/folders/l4/8ms98s3x57b8r7gtd_183_zr0000gn/T/AppTranslocation/CB88C4A0-3BD8-4ACF-B9A9-EAF087E5E5A3/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"","VSCODE_SSH_ASKPASS_MAIN":"/Users/illico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/l4/8ms98s3x57b8r7gtd_183_zr0000gn/T/vscode-ssh-askpass-756e23589ba040801197b38122ad6dc2daa194b1.sock"}
[22:02:49.814] Spawned 99906
[22:02:49.893] > local-server-3> Running ssh connection command: ssh -v -T -D 64212 -o ConnectTimeout=15 triplepatte.etis-lab.fr
[22:02:49.894] > local-server-3> Spawned ssh, pid=99911
[22:02:49.900] stderr> OpenSSH_9.7p1, OpenSSL 3.3.1 4 Jun 2024
[22:02:49.907] stderr> OpenSSH_9.7p1, OpenSSL 3.3.1 4 Jun 2024
[22:02:50.631] stderr> debug1: Server host key: ssh-ed25519 SHA256:x2TFXMGr6+zFBEOW5VpjJGOnKln1OIeULf3LxGA+fUY
[22:02:51.294] Got askpass request: {"request":" nicolass80@fandral.etis-lab.fr's password:"}
[22:02:51.295] Showing password prompt
[22:02:51.295] Listening for interwindow password on /var/folders/l4/8ms98s3x57b8r7gtd_183_zr0000gn/T/vscode-ssh-askpass-8927a35d583cd8230b175ab502ad7c59c28d2334.sock
[22:02:51.295] Writing password prompt to globalState
[22:02:51.296] Password dialog canceled
[22:02:51.296] Interactor signaled cancel
[22:02:51.296] Cleaning up other-window auth server
[22:03:04.908] stderr> Connection timed out during banner exchange
[22:03:04.909] stderr> Connection to UNKNOWN port 65535 timed out
[22:03:04.911] > local-server-3> ssh child died, shutting down
[22:03:04.922] Local server exit: 0
[22:03:04.923] Received install output: local-server-3> Running ssh connection command: ssh -v -T -D 64212 -o ConnectTimeout=15 triplepatte.etis-lab.fr
local-server-3> Spawned ssh, pid=99911
OpenSSH_9.7p1, OpenSSL 3.3.1 4 Jun 2024
OpenSSH_9.7p1, OpenSSL 3.3.1 4 Jun 2024
debug1: Server host key: ssh-ed25519 SHA256:x2TFXMGr6+zFBEOW5VpjJGOnKln1OIeULf3LxGA+fUY
Connection timed out during banner exchange
Connection to UNKNOWN port 65535 timed out
local-server-3> ssh child died, shutting down

[22:03:04.926] Exec server for ssh-remote+triplepatte.etis-lab.fr failed: Error: The connection timed out
[22:03:04.926] Error opening exec server for ssh-remote+triplepatte.etis-lab.fr: Error: The connection timed out
[22:03:42.425] Password dialog canceled
[22:03:42.425] Interactor signaled cancel
[22:03:42.426] Cleaning up other-window auth server
```

**Comment by roblourens** [comment]
@MurphLaws seems like a different issue

@allisShenYuXian seems like the right GLIBCXX version is missing

@deepak1556 @connor4312 the doc says `3.4.25` but the log is complaining about missing `3.4.26`, did this requirement change? The retrying also seems wrong

**Comment by connor4312** [comment]
Tracked in https://github.com/microsoft/vscode/issues/214462
