### ISSUE TITLE
[Remote-SSH Bug]: Unable To Connect To macOS Mojave Machine

### ISSUE THREAD

**Issue by CuriousTommy** [microsoft/vscode-remote-release#10035]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

Should be able to remote SSH into a macOS Mojave machine.

### Steps To Reproduce

1. Make sure you are using VSCode version 1.91.0 (Issue does not occur on version 1.90.2)
2. Have a macOS Mojave machine ready to SSH into
3. Trying to remote SSH into the macOS Mojave machine.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[13:49:37.675] Log Level: 2
[13:49:37.683] SSH Resolver called for "ssh-remote+thomasaosmojave", attempt 1
[13:49:37.683] "remote.SSH.useLocalServer": false
[13:49:37.683] "remote.SSH.useExecServer": true
[13:49:37.683] "remote.SSH.showLoginTerminal": true
[13:49:37.683] "remote.SSH.remotePlatform": {}
[13:49:37.683] "remote.SSH.path": undefined
[13:49:37.683] "remote.SSH.configFile": undefined
[13:49:37.683] "remote.SSH.useFlock": true
[13:49:37.683] "remote.SSH.lockfilesInTmp": false
[13:49:37.683] "remote.SSH.localServerDownload": auto
[13:49:37.683] "remote.SSH.remoteServerListenOnSocket": false
[13:49:37.683] "remote.SSH.showLoginTerminal": true
[13:49:37.683] "remote.SSH.defaultExtensions": []
[13:49:37.683] "remote.SSH.loglevel": 2
[13:49:37.683] "remote.SSH.enableDynamicForwarding": true
[13:49:37.684] "remote.SSH.enableRemoteCommand": false
[13:49:37.684] "remote.SSH.serverPickPortsFromRange": {}
[13:49:37.684] "remote.SSH.serverInstallPath": {}
[13:49:37.687] VS Code version: 1.91.0
[13:49:37.687] Remote-SSH version: remote-ssh@0.112.0
[13:49:37.687] darwin arm64
[13:49:37.689] SSH Resolver called for host: thomasaosmojave
[13:49:37.689] Setting up SSH remote "thomasaosmojave"
[13:49:37.691] Using commit id "ea1445cc7016315d0f5728f8e8b12a45dc0a7286" and quality "stable" for server
[13:49:37.693] Install and start server if needed
[13:49:40.610] PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/VMware Fusion.app/Contents/Public:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/thomasa/bin:/Users/thomasa/.cargo/bin
[13:49:40.610] Checking ssh with "ssh -V"
[13:49:40.615] > OpenSSH_9.6p1, LibreSSL 3.3.6

[13:49:40.617] Running script with connection command: ssh -T -D 64255 -o ConnectTimeout=15 thomasaosmojave bash
[13:49:41.059] > 7e3a98381512: running
[13:49:41.059] Got some output, clearing connection timeout
[13:49:41.079] > Installing to /Users/thomasa/.vscode-server...
> 7e3a98381512%%1%%
[13:49:41.091] > Downloading with curl
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--  
[13:49:41.096] >    0
[13:49:41.188] > 100   159  100   159    0     0   1764      0 --:--:-- --:--:-- --:--:--  1766
[13:49:42.045] >  31 6468k   31 2064k    0     0  2214k      0  0:00:02 --:--:--  0:00:02 2214k
[13:49:42.748] > 100 6468k  100 6468k    0     0  3925k      0  0:00:01  0:00:01 --:--:-- 6160k
[13:49:42.760] > Download complete
[13:49:42.767] > 7e3a98381512%%2%%
> tar --version:
> bsdtar 2.8.3 - libarchive 2.8.3
[13:49:42.904] > ERROR: /Users/thomasa/.vscode-server/code-ea1445cc7016315d0f5728f8e8b12a45dc0a7286 don't exist
> dyld: cannot load 'code-ea1445cc7016315d0f5728f8e8b12a45dc0a7286' (load command 0x80000034 is unknown)
> bash: line 272:  6267 Abort trap: 6           /Users/thomasa/.vscode-server/code-ea1445cc7016315d0f5728f8e8b12a45dc0a7286 --version
> Trigger local server download
> 7e3a98381512:trigger_server_download
> artifact==cli-darwin-x64==
> destFolder==/Users/thomasa/.vscode-server==
> destFolder2==/vscode-cli-ea1445cc7016315d0f5728f8e8b12a45dc0a7286.tar.gz==
> 7e3a98381512:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /Users/thomasa/.vscode-server/vscode-cli-ea1445cc7016315d0f5728f8e8b12a45dc0a7286.tar.gz.done and vscode-server.tar.gz to exist
>  
[13:49:42.904] Got request to download on client for {"artifact":"cli-darwin-x64","destPath":"/Users/thomasa/.vscode-server/vscode-cli-ea1445cc7016315d0f5728f8e8b12a45dc0a7286.tar.gz"}
[13:49:42.905] Downloading VS Code server locally...
[13:49:43.019] Downloaded VS Code server to /var/folders/sv/lydcks4s16ddtff5v875y3kc0000gn/T/2ced2bdb-7e06-4fbb-996a-7cd1f5b567c2
[13:49:43.019] Renamed VS Code server to /var/folders/sv/lydcks4s16ddtff5v875y3kc0000gn/T/vscode_server_1720212583019/vscode-cli-ea1445cc7016315d0f5728f8e8b12a45dc0a7286.tar.gz
[13:49:43.021] PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/VMware Fusion.app/Contents/Public:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/thomasa/bin:/Users/thomasa/.cargo/bin
[13:49:43.021] Checking ssh with "ssh -V"
[13:49:43.025] > OpenSSH_9.6p1, LibreSSL 3.3.6

[13:49:43.026] Testing scp with "scp"
[13:49:43.031] scp exited with code: 1
[13:49:43.031] Got stderr from scp: usage: scp [-346ABCOpqRrsTv] [-c cipher] [-D sftp_server_path] [-F ssh_config]
           [-i identity_file] [-J destination] [-l limit] [-o ssh_option]
           [-P port] [-S program] [-X sftp_option] source ... target
[13:49:43.031] Copying file to remote with scp -o ConnectTimeout=15 'vscode-cli-ea1445cc7016315d0f5728f8e8b12a45dc0a7286.tar.gz' 'vscode-cli-ea1445cc7016315d0f5728f8e8b12a45dc0a7286.tar.gz.done' thomasaosmojave:'/Users/thomasa/.vscode-server'
[13:49:43.031] Using cwd: file:///var/folders/sv/lydcks4s16ddtff5v875y3kc0000gn/T/vscode_server_1720212583019
[13:49:43.784] > vscode-cli-ea1445cc7016315d0f5728f8e8b12a45dc   0%    0     0.0KB/s   --:-- ETA
[13:49:44.787] > vscode-cli-ea1445cc7016315d0f5728f8e8b12a45dc  40% 2624KB   2.6MB/s   00:01 ETA
[13:49:45.528] > vscode-cli-ea1445cc7016315d0f5728f8e8b12a45dc 100% 6469KB   3.6MB/s   00:01    
[13:49:45.560] > vscode-cli-ea1445cc7016315d0f5728f8e8b12a45dc   0%    0     0.0KB/s   --:-- ETA
[13:49:45.569] > vscode-cli-ea1445cc7016315d0f5728f8e8b12a45dc 100%    9     1.0KB/s   00:00    
[13:49:45.843] "Copy server to host" terminal command done
[13:49:45.867] > Found flag and server on host
> 7e3a98381512%%2%%
> tar --version:
> bsdtar 2.8.3 - libarchive 2.8.3
[13:49:45.965] > ERROR: /Users/thomasa/.vscode-server/code-ea1445cc7016315d0f5728f8e8b12a45dc0a7286 don't exist
> Already attempted local download, failing
> 7e3a98381512: start
> exitCode==37==
> listeningOn====
> osReleaseId==Darwin==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/tmp==
> platform==macOS==
> unpackResult==missingFiles==
> didLocalDownload==1==
> downloadTime==1000==
> installTime==0==
> serverStartTime====
> execServerToken==11aaa1aa-1aaa-1111-1a1a-1aaa1aaa1a11==
> 7e3a98381512: end
> dyld: cannot load 'code-ea1445cc7016315d0f5728f8e8b12a45dc0a7286' (load command 0x80000034 is unknown)
> bash: line 272:  6286 Abort trap: 6           /Users/thomasa/.vscode-server/code-ea1445cc7016315d0f5728f8e8b12a45dc0a7286 --version
[13:49:45.965] Received install output: 
exitCode==37==
listeningOn====
osReleaseId==Darwin==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/tmp==
platform==macOS==
unpackResult==missingFiles==
didLocalDownload==1==
downloadTime==1000==
installTime==0==
serverStartTime====
execServerToken==11aaa1aa-1aaa-1111-1a1a-1aaa1aaa1a11==

[13:49:45.967] Resolver error: Error: Failed to install the VS Code Server
	at g.ServerInstallError (/Users/thomasa/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:499852)
	at d (/Users/thomasa/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:493513)
	at t.handleInstallOutput (/Users/thomasa/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:495331)
	at t.tryInstall (/Users/thomasa/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:621085)
	at async /Users/thomasa/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:580730
	at async t.withShowDetailsEvent (/Users/thomasa/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:584036)
	at async k (/Users/thomasa/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:577649)
	at async t.resolve (/Users/thomasa/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:581407)
	at async /Users/thomasa/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:848023
[13:49:45.968] ------




[13:49:46.160] Opening exec server for ssh-remote+thomasaosmojave
[13:49:46.166] Initizing new exec server for ssh-remote+thomasaosmojave
[13:49:46.166] Using commit id "ea1445cc7016315d0f5728f8e8b12a45dc0a7286" and quality "stable" for server
[13:49:46.168] Install and start server if needed
[13:49:46.198] Opening exec server for ssh-remote+thomasaosmojave
[13:49:46.210] "install" terminal command done
[13:49:46.210] Install terminal quit with output: 
[13:49:49.033] getPlatformForHost was canceled
[13:49:49.033] Exec server for ssh-remote+thomasaosmojave failed: Error: Connecting was canceled
[13:49:49.033] Existing exec server for ssh-remote+thomasaosmojave errored (Error: Connecting was canceled)
[13:49:49.034] Initizing new exec server for ssh-remote+thomasaosmojave
[13:49:49.034] Using commit id "ea1445cc7016315d0f5728f8e8b12a45dc0a7286" and quality "stable" for server
[13:49:49.035] Error opening exec server for ssh-remote+thomasaosmojave: Error: Connecting was canceled
[13:49:49.035] Install and start server if needed
```

</p>
</details>

### Anything else?

Downgrading to version 1.90.2 allows me to successfully connect to my macOS Mojave Mac Mini

**Comment by neverland-lhy** [comment]
I also find VSCode version 1.91.0 can't connect to macOS 10.15 Catalina Mac, but version 1.90.1 works just fine

**Comment by joshspicer** [comment]
From the logs it seems like perhaps version `1.91.0` of our macOS server build was corrupted or not linked properly in some way? Are folks still seeing this dylib error?  

```
[13:49:42.904] > ERROR: /Users/thomasa/.vscode-server/code-ea1445cc7016315d0f5728f8e8b12a45dc0a7286 don't exist
> dyld: cannot load 'code-ea1445cc7016315d0f5728f8e8b12a45dc0a7286' (load command 0x80000034 is unknown)
> bash: line 272:  6267 Abort trap: 6           /Users/thomasa/.vscode-server/code-ea1445cc7016315d0f5728f8e8b12a45dc0a7286 --version
```

I don't see this repro on current versions of VS Code, so it might be a point in time issue for this release. Please share with us if you see otherwise
