### ISSUE TITLE
A ssh server achieved by apache mina sshd cannot support for vscode's remote-ssh plugin

### ISSUE THREAD

**Issue by linuxvim20** [microsoft/vscode-remote-release#10119]
🚨 The issue tracker is not for questions 🚨

I'm using apache mina sshd (java spring) to achieve a sshd server A, where server A provide a port 8282 for clients. When a client connect to 8282, server A will start a ssh client and connect to a real linux machine B with sshd service. Thus server A is a bridge for client and real machine B providing sshd service.

Now I can apply "ssh -p 8282 abc@<A's IP>" connecting to B and can also use some single-used instructions like "bash a.sh" or "scp ..." or "wget ..." via this server A. However, when I set up connection configs on vscode's remote-ssh, it failed. And it shows that
> ]0;C:\Windows\System32\cmd.exe
[11:33:38.824] Got some output, clearing connection timeout
[11:33:38.835] > Password: 
[11:33:38.835] Showing password prompt
[11:33:41.378] Got password response
[11:33:41.378] "install" wrote data to terminal: "******"
[11:33:41.398] > 
[11:33:43.279] "install" terminal command done
[11:33:43.280] Install terminal quit with output: 
[11:33:43.281] Resolver error: Error: Got bad result from install script
	at g.Create (c:\Users\83130\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:499918)
	at t.tryInstall (c:\Users\83130\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:620821)
	at async c:\Users\83130\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:580730
	at async t.withShowDetailsEvent (c:\Users\83130\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:584036)
	at async k (c:\Users\83130\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:577649)
	at async t.resolve (c:\Users\83130\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:581407)
	at async c:\Users\83130\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.0\out\extension.js:2:848023
[11:33:43.284] ------

I cannot see what happened between the installation script and my server. I want to make sure if this try can work finally or it's not possible to solve.

here is my version of apache mina sshd:
<dependency>
        <groupId>org.apache.sshd</groupId>
        <artifactId>sshd-core</artifactId>
        <version>2.9.2</version>
</dependency>

**Comment by roblourens** [comment]
Please see https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting
