### ISSUE TITLE
VS Code GitHub Tunnel Broken

### ISSUE THREAD

**Issue by ZCLINGER-NEFCO** [microsoft/vscode-remote-release#10136]
- VSCode Version: Browser
- Local OS Version: Win10
- Remote OS Version:  PRETTY_NAME="Ubuntu 22.04.3 LTS"
- Remote Extension/Connection Type: Containers/WSL/Server - Server

- Logs:
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1] Require stack:
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1] - /home/tunnelUser/.vscode/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/server-main.js
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at Module._load (node:internal/modules/cjs/loader:986:27)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at Module.require (node:internal/modules/cjs/loader:1233:19)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at require (node:internal/modules/helpers:179:18)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at n (/home/tunnelUser/.vscode/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/server-main.js:3:98)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at r.load (/home/tunnelUser/.vscode/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/server-main.js:2:1637)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at h.load (/home/tunnelUser/.vscode/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/server-main.js:1:13958)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at u (/home/tunnelUser/.vscode/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/server-main.js:3:9338)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at Object.errorback (/home/tunnelUser/.vscode/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/server-main.js:3:9457)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at h.triggerErrorback (/home/tunnelUser/.vscode/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/server-main.js:1:14252)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at /home/tunnelUser/.vscode/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/server-main.js:1:14003
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at r.load (/home/tunnelUser/.vscode/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/server-main.js:2:1654)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at h.load (/home/tunnelUser/.vscode/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/server-main.js:1:13958)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at u (/home/tunnelUser/.vscode/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/server-main.js:3:9338)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at a._loadModule (/home/tunnelUser/.vscode/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/server-main.js:3:9466)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at a._resolve (/home/tunnelUser/.vscode/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/server-main.js:4:452)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at a.defineModule (/home/tunnelUser/.vscode/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/server-main.js:3:5561)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at Function.p [as define] (/home/tunnelUser/.vscode/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/server-main.js:4:1741)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at out-build/bootstrap-amd.js (/home/tunnelUser/.vscode/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/server-main.js:4:6445)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at /home/tunnelUser/.vscode/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/server-main.js:1:132
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at Object.<anonymous> (/home/tunnelUser/.vscode/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/server-main.js:4:9767)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at Module._compile (node:internal/modules/cjs/loader:1358:14)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at Module.load (node:internal/modules/cjs/loader:1208:32)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at Module._load (node:internal/modules/cjs/loader:1024:12)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     at node:internal/main/run_main_module:28:49 {
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]   code: 'MODULE_NOT_FOUND',
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]   requireStack: [
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]     '/home/tunnelUser/.vscode/cli/servers/Stable-b1c0a14de1414fcdaa400695b4db1c0799bc3124/server/out/server-main.js'
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]   ],
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]   phase: 'loading',
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]   moduleId: 'original-fs',
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1]   neededBy: [ 'fs' ]
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1] }
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1] Here are the modules that depend on it:
[2024-08-02 10:40:29] trace [rpc.0] [codeserver.1] [ 'fs' ]

Steps to Reproduce:

1. code tunnel 
2. connect to tunnel from remote machine

Does this issue occur when you try this locally?: Yes/No - N/A
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No - N/A

**Comment by aleleba** [comment]
Yes tunnel service is broken for me too

**Comment by connor4312** [comment]
You seem to have cut off the line of the actual error message, can you please share the entire log you see?

**Comment by ZCLINGER-NEFCO** [comment]
Whoops - the top of it is 

Loading "original-fs" failed
Error: Cannot find module 'original-fs'

That's the only part I lopped off

**Comment by connor4312** [comment]
Thanks, this should be fixed by updating VS Code on your _host_ machine (where the tunnel is running) to the latest 1.92 release.
