### ISSUE TITLE
Can't use serve-web from code 1.91.1 as of today

### ISSUE THREAD

**Issue by dmarcuse** [microsoft/vscode-remote-release#10130]
I've been using `code serve-web` on a remote linux system to work from a windows machine for the past few months via Edge, but today, it's been broken with no changes on my part. The browser page never loads, and the command-line output (see below) indicates that there's a missing module (`original-fs`).

The problem first began with a message that VS code was downloading the server, after which the page would no longer load in a browser. After digging through the logs and files, I believe I've traced the issue to a version mismatch between the system-wide VS code package installed via dnf (version 1.91.1) and the server release installed automatically to `.vscode/cli/serve-web` (version 1.92.0). The issue seems to be that whatever mechanism installs the server doesn't check the version against the installed system package correctly. I cannot upgrade the system package to 1.92.0 yet to test whether that resolves the issue due to software policies at my company.

I've identified two workarounds for the issue at the moment:

- I can install the `code-insiders` package instead (version 1.92.0 in the repositories I use) and use `code-insiders serve-web`. This works as expected. This seems to use different data directories from the stable releases, so I haven't bothered to experiment with this beyond just checking that I can load the editor and open/save files.
- I can manually run the 1.91.1 build of the server with `~/.vscode/cli/serve-web/f1e16e1e6214d7c44d078b1f0607b2388f29d729/bin/code-server`. The command line flags are slightly different, but otherwise, this seems to work with the same data directories as `code serve-web`, so I've been using this for my regular development tasks without issue.

- VSCode Version: 1.91.1 (`f1e16e1e6214d7c44d078b1f0607b2388f29d729`) installed as system package via `dnf`, 1.92.0 (`b1c0a14de1414fcdaa400695b4db1c0799bc3124`) downloaded automatically to `.vscode/cli/serve-web` without my input
- Local OS Version: Windows 11 Enterprise 23H2
- Remote OS Version: Red Hat Enterprise Linux 9.4
- Remote Extension/Connection Type: Web Server

Steps to Reproduce:

1. From remote host, run `code serve-web`
2. Attempt to connect to the host from a web browser with the printed connection token 
3. Observe that the page never loads in the browser, and an error appears in the `code serve-web` output

<details>
<summary>Logs</summary>

```
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Web UI available at http://127.0.0.1:8000?tkn=4c635d73-32cf-4eda-8abf-09a745b100b3
[2024-08-01 13:00:13] info Starting server b1c0a14de1414fcdaa400695b4db1c0799bc3124
[2024-08-01 13:00:13] info [b1c0a14 stderr]: Loading "original-fs" failed
[2024-08-01 13:00:13] info [b1c0a14 stderr]: Error: Cannot find module 'original-fs'
[2024-08-01 13:00:13] info [b1c0a14 stderr]: Require stack:
[2024-08-01 13:00:13] info [b1c0a14 stderr]: - /home/<redacted>/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at Module._load (node:internal/modules/cjs/loader:986:27)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at Module.require (node:internal/modules/cjs/loader:1233:19)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at require (node:internal/modules/helpers:179:18)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at n (/home/<redacted>/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:3:98)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at r.load (/home/<redacted>/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:2:1637)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at h.load (/home/<redacted>/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:1:13958)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at u (/home/<redacted>/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:3:9338)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at Object.errorback (/home/<redacted>/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:3:9457)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at h.triggerErrorback (/home/<redacted>/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:1:14252)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at /home/<redacted>/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:1:14003
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at r.load (/home/<redacted>/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:2:1654)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at h.load (/home/<redacted>/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:1:13958)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at u (/home/<redacted>/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:3:9338)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at a._loadModule (/home/<redacted>/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:3:9466)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at a._resolve (/home/<redacted>/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:4:452)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at a.defineModule (/home/<redacted>/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:3:5561)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at Function.p [as define] (/home/<redacted>/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:4:1741)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at out-build/bootstrap-amd.js (/home/<redacted>/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:4:6445)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at /home/<redacted>/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:1:132
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at Object.<anonymous> (/home/<redacted>/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js:4:9767)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at Module._compile (node:internal/modules/cjs/loader:1358:14)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at Module.load (node:internal/modules/cjs/loader:1208:32)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at Module._load (node:internal/modules/cjs/loader:1024:12)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     at node:internal/main/run_main_module:28:49 {
[2024-08-01 13:00:13] info [b1c0a14 stderr]:   code: 'MODULE_NOT_FOUND',
[2024-08-01 13:00:13] info [b1c0a14 stderr]:   requireStack: [
[2024-08-01 13:00:13] info [b1c0a14 stderr]:     '/home/<redacted>/.vscode/cli/serve-web/b1c0a14de1414fcdaa400695b4db1c0799bc3124/out/server-main.js'
[2024-08-01 13:00:13] info [b1c0a14 stderr]:   ],
[2024-08-01 13:00:13] info [b1c0a14 stderr]:   phase: 'loading',
[2024-08-01 13:00:13] info [b1c0a14 stderr]:   moduleId: 'original-fs',
[2024-08-01 13:00:13] info [b1c0a14 stderr]:   neededBy: [ 'fs' ]
[2024-08-01 13:00:13] info [b1c0a14 stderr]: }
[2024-08-01 13:00:13] info [b1c0a14 stderr]: Here are the modules that depend on it:
[2024-08-01 13:00:13] info [b1c0a14 stderr]: [ 'fs' ]
[2024-08-01 13:00:13] info [b1c0a14 stdout]: *
[2024-08-01 13:00:13] info [b1c0a14 stdout]: * Visual Studio Code Server
[2024-08-01 13:00:13] info [b1c0a14 stdout]: *
[2024-08-01 13:00:13] info [b1c0a14 stdout]: * By using the software, you agree to
[2024-08-01 13:00:13] info [b1c0a14 stdout]: * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
[2024-08-01 13:00:13] info [b1c0a14 stdout]: * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
[2024-08-01 13:00:13] info [b1c0a14 stdout]: *
[2024-08-01 13:00:13] info [b1c0a14 stdout]: Server bound to /tmp/code-4d3a9f54-db7e-42c3-8a42-94e92e0bbe60
[2024-08-01 13:00:13] info [b1c0a14 stdout]: Extension host agent listening on /tmp/code-4d3a9f54-db7e-42c3-8a42-94e92e0bbe60
[2024-08-01 13:00:13] info [b1c0a14 stdout]: 
```
</details>

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by connor4312** [comment]
Please update your host version of VS Code to 1.92 to resolve the issue, thanks!

**Comment by dmarcuse** [comment]
Hi connor - I'm not able to update VS code at the moment due to my company's policies, and the fact that it will update its own component and break itself anyways seems unintended. I can use a workaround for now, but is this really intended behavior?

**Comment by connor4312** [comment]
It's a bug, but we cannot patch older versions of VS Code, so putting in any kind of 'fix' would also require taking an update.

**Comment by dmarcuse** [comment]
Fair enough. For now I'll manually run the 1.91.1 server until I can upgrade to 1.92.0. Thank you!
