### ISSUE TITLE
Dockerfile # escape=` setting not work when using dev container.

### ISSUE THREAD

**Issue by Kicey** [microsoft/vscode-remote-release#10149]
When try to start a dev container using custom dockerfile (on a open source project: https://github.com/voiceip/oreka, you can reproduct the same error response easily), I get an error response caused by the `` ` `` is not recognized as a escape character (statement: `` # escape=` `` not work), and the temporary dockerfile is begin with `        ARG _DEV_CONTAINERS_BASE_IMAGE=placeholder` (which cause the escape statement not work).

- VSCode Version: 1.89.1 (user setup)
- Local OS Version: Windows_NT x64 10.0.19044
- Remote OS Version: 5.15.146.1-microsoft-standard-WSL2
- Remote Extension/Connection Type: Containers in WSL

- Logs:

```
[2024-08-09T07:40:13.601Z] Dockerfile-with-features:14
--------------------
  12 |     
  13 |     RUN . /etc/os-release && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 31F54F3E108EAD31 `
  14 | >>> 	&& echo "deb [trusted=yes] http://ppa.launchpad.net/mhier/libboost-latest/ubuntu $UBUNTU_CODENAME main" >> /etc/apt/sources.list
  15 |     
  16 |     RUN apt-get update && apt-get install -y build-essential libtool automake git tree rpm libboost1.70-dev`
--------------------
[2024-08-09T07:40:13.601Z] ERROR: failed to solve: dockerfile parse error on line 14: unknown instruction: &&
[2024-08-09T07:40:13.605Z] Stop (1828 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-joy/container-features/0.65.0-1723189211773/Dockerfile-with-features -t vsc-master-9ffa23c681fcf79f47ac2a43b7a64f227630eee2d75f747a023c4cc3c58d6527 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /home/joy/projects/open-source/oreka-worktree/master
[2024-08-09T07:40:13.605Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-joy/container-features/0.65.0-1723189211773/Dockerfile-with-features -t vsc-master-9ffa23c681fcf79f47ac2a43b7a64f227630eee2d75f747a023c4cc3c58d6527 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /home/joy/projects/open-source/oreka-worktree/master
[2024-08-09T07:40:13.605Z]     at mtA (/home/joy/.vscode-remote-containers/dist/dev-containers-cli-0.380.0/dist/spec-node/devContainersSpecCLI.js:466:1933)
[2024-08-09T07:40:13.606Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-08-09T07:40:13.606Z]     at async Pm (/home/joy/.vscode-remote-containers/dist/dev-containers-cli-0.380.0/dist/spec-node/devContainersSpecCLI.js:465:1856)
[2024-08-09T07:40:13.606Z]     at async NH (/home/joy/.vscode-remote-containers/dist/dev-containers-cli-0.380.0/dist/spec-node/devContainersSpecCLI.js:465:610)
[2024-08-09T07:40:13.606Z]     at async KtA (/home/joy/.vscode-remote-containers/dist/dev-containers-cli-0.380.0/dist/spec-node/devContainersSpecCLI.js:482:3771)
[2024-08-09T07:40:13.606Z]     at async eB (/home/joy/.vscode-remote-containers/dist/dev-containers-cli-0.380.0/dist/spec-node/devContainersSpecCLI.js:482:4886)
[2024-08-09T07:40:13.606Z]     at async hrA (/home/joy/.vscode-remote-containers/dist/dev-containers-cli-0.380.0/dist/spec-node/devContainersSpecCLI.js:663:200)
[2024-08-09T07:40:13.606Z]     at async lrA (/home/joy/.vscode-remote-containers/dist/dev-containers-cli-0.380.0/dist/spec-node/devContainersSpecCLI.js:662:13452)
[2024-08-09T07:40:13.610Z] Stop (2622 ms): Run in Host: /home/joy/.vscode-server/bin/dc96b837cf6bb4af9cd736aa3af08cf8279f7685/node /home/joy/.vscode-remote-containers/dist/dev-containers-cli-0.380.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-40057c38-9102-4a1a-8a65-b6ea51ce7d231723189208340 --workspace-folder /home/joy/projects/open-source/oreka-worktree/master --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\Ubuntu-24.04\home\joy\projects\open-source\oreka-worktree\master --id-label devcontainer.config_file=/home/joy/projects/open-source/oreka-worktree/master/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/joy/projects/open-source/oreka-worktree/master/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[2024-08-09T07:40:13.611Z] Exit code 1
[2024-08-09T07:40:13.615Z] Command failed: /home/joy/.vscode-server/bin/dc96b837cf6bb4af9cd736aa3af08cf8279f7685/node /home/joy/.vscode-remote-containers/dist/dev-containers-cli-0.380.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-40057c38-9102-4a1a-8a65-b6ea51ce7d231723189208340 --workspace-folder /home/joy/projects/open-source/oreka-worktree/master --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\Ubuntu-24.04\home\joy\projects\open-source\oreka-worktree\master --id-label devcontainer.config_file=/home/joy/projects/open-source/oreka-worktree/master/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/joy/projects/open-source/oreka-worktree/master/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[2024-08-09T07:40:13.615Z] Exit code 1
[2024-08-09T07:40:26.212Z] Start: Run: wsl -d Ubuntu-24.04 -e wslpath -u \\wsl.localhost\Ubuntu-24.04\home\joy\projects\open-source\oreka-worktree\master
[2024-08-09T07:40:26.498Z] Stop (286 ms): Run: wsl -d Ubuntu-24.04 -e wslpath -u \\wsl.localhost\Ubuntu-24.04\home\joy\projects\open-source\oreka-worktree\master
```

Steps to Reproduce:

1. Clone the project: https://github.com/voiceip/oreka
2. Try to open it in devcontainer by vs code

**Comment by bamurtaugh** [comment]
I wonder if the version of Docker being used + the fact dev containers are Linux-based are impacting things. Chatted with GitHub Copilot about this:

![Image](https://github.com/user-attachments/assets/e9e0b073-6e01-4b08-94a8-c423e46665fb)

@Kicey do you absolutely need "# escape=`" in this setup, or could you try using the repo + dev container without it?

**Comment by chrmarti** [comment]
Tracking as https://github.com/devcontainers/cli/issues/632.

**Comment by Kicey** [comment]
> I wonder if the version of Docker being used + the fact dev containers are Linux-based are impacting things. Chatted with GitHub Copilot about this:
> 
> ![Image](https://private-user-images.githubusercontent.com/25310137/362457352-e9e0b073-6e01-4b08-94a8-c423e46665fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNzk1MDMsIm5iZiI6MTcyNTA3OTIwMywicGF0aCI6Ii8yNTMxMDEzNy8zNjI0NTczNTItZTllMGIwNzMtNmUwMS00YjA4LTk0YTgtYzQyM2U0NjY2NWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDA0NDAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NmM0MDAyNGZkZjczYWQxYmIyYTM3OTJhMTY0N2ZiZTgzZjNkYjQ0OTE2NTNiMzFlZmUyZDMyOTgwNzQ4MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BxIJUMIb3ji_p5VUKyfWYmkdSyJQkPeMqCbtm-LWx3Y)
> 
> @Kicey do you absolutely need "# escape=`" in this setup, or could you try using the repo + dev container without it?

It's simple to work around. And the `escape` not work is caused by the dev container overwrite the dockerfile (temporarily) which put the escape config not the first line. Just report the issue, and @chrmarti 's link shows that it's caused by the dev container cli.
