### ISSUE TITLE
Connect to WSL fails when in a dev container

### ISSUE THREAD

**Issue by Brainicism** [microsoft/vscode-remote-release#10159]
Type: <b>Bug</b>

Every variation of "WSL: Connect to ..." results in the following error 

```
Command "WSL: Connect to ..." resulted in an error
Cannot read properties of undefined (reading 'env')
```

Extension version: 0.88.2
VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.90GB (13.75GB free)|
|Process Argv|--crash-reporter-id e49d4c19-2371-4f7e-8bbb-0de4fd0bb1fb|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: KMQ Dev Container|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor (16 x 0)|
|Memory (System)|15.57GB (10.66GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717

```

</details>

**Comment by aeschli** [comment]
Are theme more details in the WSL Log? Run command: `WSL: Show Logs...`

**Comment by Brainicism** [comment]
> Are theme more details in the WSL Log? Run command: `WSL: Show Logs...`

There aren't any new logs when I try to connect, but this was the current state
```
[2024-08-12 08:07:30.410] Extension version: 0.88.2
[2024-08-12 08:07:30.411] L10N bundle: undefined
[2024-08-12 08:07:30.417] authorityHierarchy: dev-container+7b22686f737450617468223a225c5c5c5c77736c2e6c6f63616c686f73745c5c5562756e74752d31382e30345c5c686f6d655c5c627269616e5c5c4b4d515f446973636f7264222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f627269616e2f4b4d515f446973636f72642f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d
[2024-08-12 08:07:30.417] Host authority leaf is not exec server enabled (dev-container+7b22686f737450617468223a225c5c5c5c77736c2e6c6f63616c686f73745c5c5562756e74752d31382e30345c5c686f6d655c5c627269616e5c5c4b4d515f446973636f7264222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f627269616e2f4b4d515f446973636f72642f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d)
```

**Comment by Brainicism** [comment]
Huh.. trying again from a new window worked. My window where I was loaded into a dev container did not work.

**Comment by aeschli** [comment]
The window was open on a dev container, and you used the  `WSL: Connect to ...` command?

**Comment by Brainicism** [comment]
> The window was open on a dev container, and you used the `WSL: Connect to ...` command?

Correct

**Comment by aeschli** [comment]
Thanks! I was able to reproduce:
```
	at Object.getEnv (c:\Users\martinae\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.88.2\dist\node\extension.js:848:31)
	at c:\Users\martinae\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.88.2\dist\node\extension.js:933:98
	at async getWSLExecServer (c:\Users\martinae\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.88.2\dist\node\extension.js:933:64)
	at async AuthorityResourceStore.get (c:\Users\martinae\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.88.2\dist\node\extension.js:13723:32)
	at async connect (c:\Users\martinae\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.88.2\dist\node\extension.js:12850:42)
	at async d.h (c:\Users\martinae\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:161:206881) remote-wsl.connect {"value":"ms-vscode-remote.remote-wsl","_lower":"ms-vscode-remote.remote-wsl"}
```
