### ISSUE TITLE
[Remote-SSH Bug]: Resolver error: Error: Server returned 404

### ISSUE THREAD

**Issue by weindler** [microsoft/vscode-remote-release#10163]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

no

### Expected Behavior

no

### Steps To Reproduce

no

### Remote-SSH Log

09:22:59.295] Log Level: 2
[09:22:59.322] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a22696f42726f6b6572456e747769636b6c756e67227d", attempt 1
[09:22:59.325] "remote.SSH.useLocalServer": false
[09:22:59.325] "remote.SSH.useExecServer": false
[09:22:59.326] "remote.SSH.showLoginTerminal": false
[09:22:59.336] "remote.SSH.remotePlatform": {}
[09:22:59.337] "remote.SSH.path": ssh
[09:22:59.337] "remote.SSH.configFile": C:\Users\josef\ssh\iobentw
[09:22:59.338] "remote.SSH.useFlock": true
[09:22:59.338] "remote.SSH.lockfilesInTmp": false
[09:22:59.338] "remote.SSH.localServerDownload": auto
[09:22:59.339] "remote.SSH.remoteServerListenOnSocket": false
[09:22:59.339] "remote.SSH.showLoginTerminal": false
[09:22:59.339] "remote.SSH.defaultExtensions": []
[09:22:59.339] "remote.SSH.loglevel": 2
[09:22:59.340] "remote.SSH.enableDynamicForwarding": true
[09:22:59.340] "remote.SSH.enableRemoteCommand": false
[09:22:59.340] "remote.SSH.serverPickPortsFromRange": {}
[09:22:59.342] "remote.SSH.serverInstallPath": {}
[09:22:59.352] VS Code version: 1.83.1
[09:22:59.352] Remote-SSH version: remote-ssh@0.106.5
[09:22:59.352] win32 ia32
[09:22:59.355] SSH Resolver called for host: ioBrokerEntwicklung
[09:22:59.356] Setting up SSH remote "ioBrokerEntwicklung"
[09:22:59.365] Using commit id "a6606b6ca720bca780c2d3c9d4cc3966ff2eca12" and quality "stable" for server
[09:22:59.373] Install and start server if needed
[09:23:03.519] Checking ssh with "ssh -V"
[09:23:03.620] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[09:23:03.632] Using SSH config file "C:\Users\josef\ssh\iobentw"
[09:23:03.633] Running script with connection command: ssh -T -D 52807 -F "C:\Users\josef\ssh\iobentw" "ioBrokerEntwicklung" bash
[09:23:03.638] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[09:23:04.600] > ]0;C:\WINDOWS\System32\cmd.exe
[09:23:04.601] Got some output, clearing connection timeout
[09:23:04.817] > josefw@192.168.157.52's password: 
[09:23:04.818] Showing password prompt
[09:23:14.636] Got password response
[09:23:14.637] "install" wrote data to terminal: "********"
[09:23:14.685] > 
[09:23:14.820] > 9ed0bffb3434: running
[09:23:14.850] > Acquiring lock on /home/josefw/.vscode-server/bin/a6606b6ca720bca780c2d3c9d4cc39
> 66ff2eca12/vscode-remote-lock.josefw.a6606b6ca720bca780c2d3c9d4cc3966ff2eca12   
[09:23:14.872] > Installing to /home/josefw/.vscode-server/bin/a6606b6ca720bca780c2d3c9d4cc3966ff
> 2eca12...
> 9ed0bffb3434%%1%%
> Downloading with wget
[09:23:15.116] > wget download failed
> https://update.code.visualstudio.com/commit:a6606b6ca720bca780c2d3c9d4cc3966ff2e
> ca12/server-linux-x64/stable: 2024-08-13 09:23:14 FEHLER 404: Not Found.        
> printenv:
>     SHELL=/bin/bash
>     PWD=/home/josefw/.vscode-server/bin/a6606b6ca720bca780c2d3c9d4cc3966ff2eca12
>     LOGNAME=josefw
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/home/josefw
>     LANG=de_DE.UTF-8
>     VSCODE_AGENT_FOLDER=/home/josefw/.vscode-server
>     SSH_CONNECTION=192.168.157.20 52813 192.168.157.52 22
>     XDG_SESSION_CLASS=user
>     USER=josefw
>     SHLVL=0
>     XDG_SESSION_ID=10
>     XDG_RUNTIME_DIR=/run/user/1000
>     SSH_CLIENT=192.168.157.20 52813 22
>     PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
>     OLDPWD=/home/josefw
>     _=/usr/bin/printenv
[09:23:15.125] > 
[09:23:15.167] > Trigger local server download
> 9ed0bffb3434:trigger_server_download
> artifact==server-linux-x64==
> destFolder==/home/josefw/.vscode-server/bin/==
> destFolder2==/a6606b6ca720bca780c2d3c9d4cc3966ff2eca12/vscode-server.tar.gz==   
> 9ed0bffb3434:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/josefw/.vscode-server/bin/a6606b6ca720bca780c2d3c9d4cc3966ff2e
> ca12/vscode-server.tar.gz.done and vscode-server.tar.gz to exist
> 
[09:23:15.169] Got request to download on client for {"artifact":"server-linux-x64","destPath":"/home/josefw/.vscode-server/bin//a6606b6ca720bca780c2d3c9d4cc3966ff2eca12/vscode-server.tar.gz"}
[09:23:15.170] Downloading VS Code server locally...
[09:23:15.283] Resolver error: Error: Server returned 404
    at d (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:676:29246)
    at E.download (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:677:1753)
[09:23:15.299] ------

[09:27:15.342] > 
> 

### Anything else?

no

**Comment by bamurtaugh** [comment]
Thanks for opening. Could you please include the steps you took so that we can try to reproduce and take a closer look?
