### ISSUE TITLE
[Remote-SSH Bug]: Pre-release (113.1) has bugs on windows

### ISSUE THREAD

**Issue by wenh06** [microsoft/vscode-remote-release#10208]
- VSCode Version: 1.93.0-insider
- Local OS Version: Windows_NT x64 10.0.22631
- Remote OS Version: Ubuntu 22.04
- Remote Extension/Connection Type: Server

I encountered "could not establish connection" issues and found something like "sh: xx: [[: not found" in the output logs. Then I opened the corresponding .sh files and found things like:

![image](https://github.com/user-attachments/assets/10d721c2-7ccb-4643-9435-a851adab9d2c)

Files that work look like 
![image](https://github.com/user-attachments/assets/6e023a57-62a7-4eb7-903c-86462b736c2c)

I found [this answer](https://stackoverflow.com/a/37528631/10779789) in StackOverflow that 

    `[[` is a bashism, ie built into Bash and not available for other shells. If you want your script to be portable, use `[`

I downgraded remote-ssh from `0.113.1` to `0.112.0`, and the `could not establish connection` issue resolved.
```[tasklist]
### Tasks
```

**Comment by joshspicer** [comment]
Would you mind sharing your entire [log](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting) file?

These are all release versions of the extension, right?  Not the pre-release?

**Comment by wenh06** [comment]
It was the pre-release version. After this bug, I switched all Remote extensions to release version.

By the way, where can I find the log file except at "View > Output > Remote-SSH"? I don't want to switch back to reproduce this error.

**Comment by joshspicer** [comment]
Gotcha.  If it was the pre-release extension this is likely already fixed.  If you do have a moment to test it out, it would be appreciated (and sharing the log if the issue still repros!)

The old, relevant log at this point is probably gone if you've been using the extension.

**Comment by albireox** [comment]
Still happening for me with the latest pre-release version. I killed node in the remote server but that didn't help.

<details closed>
<summary>Log</summary>
<code>
[13:03:12.619] Log Level: 2
[13:03:12.630] SSH Resolver called for "ssh-remote+mako", attempt 1
[13:03:12.631] "remote.SSH.useLocalServer": true
[13:03:12.631] "remote.SSH.useExecServer": false
[13:03:12.631] "remote.SSH.path": undefined
[13:03:12.631] "remote.SSH.configFile": undefined
[13:03:12.632] "remote.SSH.useFlock": true
[13:03:12.632] "remote.SSH.lockfilesInTmp": false
[13:03:12.632] "remote.SSH.localServerDownload": auto
[13:03:12.632] "remote.SSH.remoteServerListenOnSocket": false
[13:03:12.632] "remote.SSH.showLoginTerminal": false
[13:03:12.632] "remote.SSH.defaultExtensions": ["streetsidesoftware.code-spell-checker","christian-kohler.path-intellisense","psioniq.psi-header","ms-python.python","ms-python.vscode-pylance","mrmlnc.vscode-duplicate","github.vscode-pull-request-github","eamodio.gitlens","esbenp.prettier-vscode","redhat.vscode-yaml","ms-python.black-formatter","charliermarsh.ruff"]
[13:03:12.633] "remote.SSH.loglevel": 2
[13:03:12.633] "remote.SSH.enableDynamicForwarding": true
[13:03:12.633] "remote.SSH.enableRemoteCommand": false
[13:03:12.633] "remote.SSH.serverPickPortsFromRange": {}
[13:03:12.633] "remote.SSH.serverInstallPath": {}
[13:03:12.633] "remote.SSH.permitPtyAllocation": false
[13:03:12.633] "remote.SSH.preferredLocalPortRange: undefined
[13:03:12.634] "remote.SSH.useCurlAndWgetConfigurationFiles: false
[13:03:12.638] VS Code version: 1.93.0
[13:03:12.638] Remote-SSH version: remote-ssh@0.114.2024090417
[13:03:12.638] darwin x64
[13:03:12.646] SSH Resolver called for host: mako
[13:03:12.646] Setting up SSH remote "mako"
[13:03:12.650] Acquiring local install lock: /var/folders/p1/v1b0n8qj0m3ftp3rf3t_50380000gn/T/vscode-remote-ssh-eb8c666d-install.lock
[13:03:12.661] Looking for existing server data file at /Users/gallegoj/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-eb8c666d-4849ca9bdf9666755eb463db297b69e5385090e3-0.114.2024090417-tr/data.json
[13:03:12.663] No existing data file
[13:03:12.664] Using commit id "4849ca9bdf9666755eb463db297b69e5385090e3" and quality "stable" for server
[13:03:12.667] Script variables:
 {
  "InstallExitCode.24": "AlreadyInProgress",
  "InstallExitCode.25": "ServerDownloadFailed",
  "InstallExitCode.26": "NoDownloaderAvailable",
  "InstallExitCode.27": "UnsupportedArch",
  "InstallExitCode.28": "StatusCheckFailed",
  "InstallExitCode.29": "NeedInsidersArch",
  "InstallExitCode.30": "NoDownloaderAvailableForStatusCheck",
  "InstallExitCode.31": "ServerTransferFailed",
  "InstallExitCode.32": "ServerFailedToStart",
  "InstallExitCode.33": "NeedInsidersWindows",
  "InstallExitCode.34": "CreateInstallDirFailed",
  "InstallExitCode.35": "UnsupportedPlatform",
  "InstallExitCode.36": "ServerTerminatedCVE20201416",
  "InstallExitCode.37": "UnpackFailed",
  "InstallExitCode.38": "ChangeDirFailed",
  "InstallExitCode.AlreadyInProgress": "24",
  "InstallExitCode.ServerDownloadFailed": "25",
  "InstallExitCode.NoDownloaderAvailable": "26",
  "InstallExitCode.NoDownloaderAvailableForStatusCheck": "30",
  "InstallExitCode.UnsupportedArch": "27",
  "InstallExitCode.StatusCheckFailed": "28",
  "InstallExitCode.NeedInsidersArch": "29",
  "InstallExitCode.ServerTransferFailed": "31",
  "InstallExitCode.ServerFailedToStart": "32",
  "InstallExitCode.NeedInsidersWindows": "33",
  "InstallExitCode.CreateInstallDirFailed": "34",
  "InstallExitCode.UnsupportedPlatform": "35",
  "InstallExitCode.ServerTerminatedCVE20201416": "36",
  "InstallExitCode.UnpackFailed": "37",
  "InstallExitCode.ChangeDirFailed": "38",
  "InstallUnpackCode.Success": "success",
  "InstallUnpackCode.Error": "error",
  "InstallUnpackCode.MissingFiles": "missingFiles",
  "uuid": "f50f89666ff6",
  "startMarker": "f50f89666ff6: running",
  "commitId": "4849ca9bdf9666755eb463db297b69e5385090e3",
  "quality": "stable",
  "token": "1a1a1a11-a11a-1111-1111-aaaa11a1aaa1",
  "vscodeAgentFolder": "$HOME/.vscode-server",
  "allowClientDownload": "1",
  "forceClientDownload": "0",
  "cliNameInArchive": "code",
  "ignoreWgetConfigFlag": " --no-config ",
  "ignoreCurlConfigFlag": " --disable ",
  "wgetTriesSegment": "--tries=1",
  "listenArgs": "--on-host=127.0.0.1 --on-port",
  "getDownloadServerStartTrigger": "f50f89666ff6:trigger_server_download",
  "getDownloadServerEndTrigger": "f50f89666ff6:trigger_server_download_end",
  "getProgressDownloading": "f50f89666ff6%%1%%",
  "getProgressInstalling": "f50f89666ff6%%2%%"
}
[13:03:12.669] Install and start server if needed
[13:03:12.680] PATH: /Users/gallegoj/.pyenv/plugins/pyenv-virtualenv/shims:/Users/gallegoj/.pyenv/shims:/Users/gallegoj/.cargo/bin:/usr/local/bin:/Users/gallegoj/.local/bin:/Users/gallegoj/.pyenv/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin
[13:03:12.680] Checking ssh with "ssh -V"
[13:03:12.710] > OpenSSH_9.8p1, OpenSSL 3.3.2 3 Sep 2024

[13:03:12.727] askpass server listening on /var/folders/p1/v1b0n8qj0m3ftp3rf3t_50380000gn/T/vscode-ssh-askpass-65e440644d4c943acc7fd6b68548662a9be3ff66.sock
[13:03:12.728] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/p1/v1b0n8qj0m3ftp3rf3t_50380000gn/T/vscode-ssh-askpass-24108285ac81405b59761ccfc4ebabd5748f74b9.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","60059","-o","ConnectTimeout=30","mako","bash"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/gallegoj/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-eb8c666d-4849ca9bdf9666755eb463db297b69e5385090e3-0.114.2024090417-tr/data.json"}
[13:03:12.728] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.1x6ivhCPVU/Listeners","SHELL":"/usr/local/bin/fish","DISPLAY":"/private/tmp/com.apple.launchd.UT9MVBJY1g/org.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/gallegoj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.114.2024090417/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"","VSCODE_SSH_ASKPASS_MAIN":"/Users/gallegoj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.114.2024090417/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/p1/v1b0n8qj0m3ftp3rf3t_50380000gn/T/vscode-ssh-askpass-65e440644d4c943acc7fd6b68548662a9be3ff66.sock"}
[13:03:12.731] Spawned 37200
[13:03:12.920] > local-server-1> Running ssh connection command: ssh -v -T -D 60059 -o ConnectTimeout=30 mako bash
[13:03:12.927] > local-server-1> Spawned ssh, pid=37204
[13:03:12.945] stderr> OpenSSH_9.8p1, OpenSSL 3.3.2 3 Sep 2024
[13:03:13.027] stderr> debug1: Server host key: ssh-ed25519 SHA256:pQ/mK3CaCNuqDlJO3rTI1hQqA8S0N+ydX2XcEFFQrOc
[13:03:13.138] stderr> Authenticated to 10.155.88.196 ([10.155.88.196]:22) using "publickey".
[13:03:14.469] > ready: f50f89666ff6
[13:03:14.476] > Linux 6.2.0-39-generic #40-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:18:00 UTC 2023
[13:03:14.477] Platform: linux
[13:03:14.480] > /home/linuxbrew/.linuxbrew/bin/fish
[13:03:14.481] Parent Shell: fish
[13:03:14.481] Parent Shell pid: 37200
[13:03:14.487] > 560583
[13:03:14.487] Waiting for pid of spawned 'sh' subshell: '560583'...
[13:03:14.494] stderr> sh: 173: Syntax error: "(" unexpected (expecting "then")
[13:03:14.509] stderr> bash: line 252: syntax error near unexpected token `('
[13:03:14.509] stderr> bash: line 252: `echo "* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and"'
[13:03:14.513] stderr> Transferred: sent 21320, received 4520 bytes, in 1.4 seconds
[13:03:14.513] stderr> Bytes per second: sent 15545.3, received 3295.7
[13:03:14.514] > local-server-1> ssh child died, shutting down
[13:03:14.520] Local server exit: 0
[13:03:14.521] Received install output: local-server-1> Running ssh connection command: ssh -v -T -D 60059 -o ConnectTimeout=30 mako bash
local-server-1> Spawned ssh, pid=37204
OpenSSH_9.8p1, OpenSSL 3.3.2 3 Sep 2024
debug1: Server host key: ssh-ed25519 SHA256:pQ/mK3CaCNuqDlJO3rTI1hQqA8S0N+ydX2XcEFFQrOc
Authenticated to 10.155.88.196 ([10.155.88.196]:22) using "publickey".
ready: f50f89666ff6
Linux 6.2.0-39-generic #40-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:18:00 UTC 2023
/home/linuxbrew/.linuxbrew/bin/fish
560583
sh: 173: Syntax error: "(" unexpected (expecting "then")
bash: line 252: syntax error near unexpected token `('
bash: line 252: `echo "* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and"'
Transferred: sent 21320, received 4520 bytes, in 1.4 seconds
Bytes per second: sent 15545.3, received 3295.7
local-server-1> ssh child died, shutting down

[13:03:14.521] Failed to parse remote port from server output
[13:03:14.524] Resolver error: Error: 
	at v.Create (/Users/gallegoj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.114.2024090417/out/extension.js:2:501404)
	at t.handleInstallOutput (/Users/gallegoj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.114.2024090417/out/extension.js:2:498726)
	at e (/Users/gallegoj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.114.2024090417/out/extension.js:2:553139)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /Users/gallegoj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.114.2024090417/out/extension.js:2:575383
	at async t.withShowDetailsEvent (/Users/gallegoj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.114.2024090417/out/extension.js:2:579059)
	at async /Users/gallegoj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.114.2024090417/out/extension.js:2:549844
	at async T (/Users/gallegoj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.114.2024090417/out/extension.js:2:547895)
	at async t.resolveWithLocalServer (/Users/gallegoj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.114.2024090417/out/extension.js:2:549384)
	at async k (/Users/gallegoj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.114.2024090417/out/extension.js:2:572515)
	at async t.resolve (/Users/gallegoj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.114.2024090417/out/extension.js:2:576470)
	at async /Users/gallegoj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.114.2024090417/out/extension.js:2:844825
[13:03:14.530] ------
</code>
</details>

**Comment by joshspicer** [comment]
Hey there @albireox.  From your logs I think you're hitting https://github.com/microsoft/vscode-remote-release/issues/10229.  I'm about to deploy a pre-release that I suspect will fix your issue, but you can also try setting the `useExecServer` feature back to true (the default value).

**Comment by albireox** [comment]
Thanks. I'll test it when it's out.

I need `useExecServer: false` because of this long-standing issue https://github.com/microsoft/vscode/issues/168202

**Comment by joshspicer** [comment]
@albireox Thanks for sharing why you've set `useExecServer` to false.  I'm going to read that thread to catch up on the issue.

FYI a new pre-release build as landed that should help

**Comment by albireox** [comment]
Thanks @joshspicer! I installed it and it's working for me on Linux.

**Comment by joshspicer** [comment]
Closing this issue as the original bug here was seen in a pre-release extension (and should be fixed). Current discussion on a similar but unrelated issue is being tracked in https://github.com/microsoft/vscode-remote-release/issues/10229
