### ISSUE TITLE
Command 'Dev Containers: Add Dev Container Configuration Files...' resulted in an error Cannot read properties of undefined (reading 'files')

### ISSUE THREAD

**Issue by AlaricWeb** [microsoft/vscode-remote-release#10217]
Type: <b>Bug</b>

ctrl+ p
input  'Dev Containers: Add Dev Container Configuration

Extension version: 0.380.0
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 4650G with Radeon Graphics (12 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.39GB (4.64GB free)|
|Process Argv|D:\\workspace\\test --crash-reporter-id 40bf09d0-d888-4403-a81a-3cdf82d2ef1e --crash-reporter-id 40bf09d0-d888-4403-a81a-3cdf82d2ef1e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-t:31111718
wkspc-ranged-c:31125598
ei213698:31121563
aajjf12562cf:31125794

```

</details>

**Comment by chrmarti** [comment]
Please append the Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)

**Comment by AlaricWeb** [comment]
[114 ms] Dev Containers 0.380.0 in VS Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9).
[113 ms] Start: Run: wsl -l -v
[235 ms] Start: Run: wsl -d Ubuntu -e wslpath -u d:\workspace\test
[367 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/mnt/d/workspace/test' && /bin/sh
[375 ms] Start: Run in host: id -un
[435 ms] root
[436 ms] 
[436 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true)
[440 ms] Start: Run in host: echo ~
[444 ms] /root
[444 ms] 
[445 ms] Start: Run in host: test -f '/root/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/node'
[446 ms] 
[446 ms] 
[447 ms] Exit code 1
[447 ms] Start: Run in host: test -f '/root/.vscode/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/node'
[448 ms] 
[448 ms] 
[448 ms] Exit code 1
[449 ms] Start: Run in host: test -f '/root/.vscode-server/bin/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/node'
[450 ms] 
[450 ms] 
[450 ms] Start: Run in host: test -f '/root/.vscode-server/bin/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/node_modules/node-pty/package.json'
[452 ms] 
[452 ms] 
[452 ms] Start: Run in host: test -f '/root/.vscode-remote-containers/dist/vscode-remote-containers-server-0.380.0.js'
[453 ms] 
[453 ms] 
[456 ms] userEnvProbe: loginInteractiveShell (default)
[456 ms] userEnvProbe: not found in cache
[456 ms] userEnvProbe shell: /usr/bin/zsh
[748 ms] userEnvProbe PATHs:
Probe:     '/run/user/0/fnm_multishells/23831_1725450765454/bin:/root/.local/share/fnm:/usr/local/php7.4/pear/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Python312/Scripts/:/mnt/c/Python312/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/dotnet/:/mnt/c/ProgramData/ComposerSetup/bin:/mnt/c/Program Files/Go/bin:/mnt/c/ProgramData/chocolatey/bin:/Docker/host/bin:/mnt/c/Users/artist/AppData/Local/Microsoft/WindowsApps:/mnt/c/dev/mysql-5.7.23-winx64/bin:/mnt/c/Users/artist/AppData/Local/Microsoft/WinGet/Packages/oleg-shilo.win-sudo_Microsoft.Winget.Source_8wekyb3d8bbwe:/mnt/c/dev/php-7.4.0-nts-Win32-vc15-x86:/mnt/c/dev/pecl:/mnt/c/dev/composer:/mnt/c/Users/artist/AppData/Roaming/Composer/vendor/bin:/mnt/c/Program Files/Neovim/bin:/mnt/c/Users/artist/AppData/Local/Microsoft/WinGet/Links:/mnt/c/Users/artist/go/bin:/mnt/c/Users/artist/AppData/Roaming/Code/User/globalStorage/ms-vscode-remote.remote-containers/cli-bin:/mnt/c/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64:/mnt/c/Users/artist/AppData/Local/Programs/Microsoft VS Code/bin'
Container: None
[884 ms] Initializing configuration support...
[885 ms] Internal initialization of dev container support package...
[886 ms] Start: Run: wsl -l -v
[941 ms] Start: Run: wsl -d Ubuntu -e wslpath -u d:\workspace\test
[7960 ms] Entering createDevContainerConfig_v2
[44244 ms] Preparing to apply Template 'ghcr.io/devcontainers/templates/php:latest'
[44259 ms] Running Dev Containers CLI:   templates apply --workspace-folder C:\Users\artist\AppData\Local\Temp\tmp-output-dir-1725450808971 --template-id ghcr.io/devcontainers/templates/php:latest --template-args {"imageVariant":"8.2-bullseye"} --features [] --tmp-dir C:\Users\artist\AppData\Local\Temp\tmp-dir-1725450808971 --log-level debug
[44266 ms] ProxyResolver#loadSystemCertificates count
[44268 ms] ProxyResolver#loadSystemCertificates count filtered
[44269 ms] Start: Run: C:\Users\artist\AppData\Local\Programs\Microsoft VS Code\Code.exe c:\Users\artist\.vscode\extensions\ms-vscode-remote.remote-containers-0.380.0\dist\spec-node\devContainersSpecCLI.js templates apply --workspace-folder C:\Users\artist\AppData\Local\Temp\tmp-output-dir-1725450808971 --template-id ghcr.io/devcontainers/templates/php:latest --template-args {"imageVariant":"8.2-bullseye"} --features [] --tmp-dir C:\Users\artist\AppData\Local\Temp\tmp-dir-1725450808971 --log-level debug
[44491 ms] [2024-09-04T11:53:29.216Z] @devcontainers/cli 0.65.0. Node.js v20.14.0. win32 10.0.19045 x64.
[44496 ms] [2024-09-04T11:53:29.223Z] Loading 36 extra certificates from C:\Users\artist\AppData\Local\Temp\vsch\certificates-aa529ada0792190e9b438decedeb9b27b401c47e8ab1d383b92ef5be9bdaa7da.pem.
[45068 ms] [2024-09-04T11:53:29.795Z] Start: Run: docker-credential-desktop get
[45296 ms] [2024-09-04T11:53:30.023Z] Stop (228 ms): Run: docker-credential-desktop get
[47085 ms] [2024-09-04T11:53:31.812Z] Error getting blob: Error: getaddrinfo ENOTFOUND pkg-containers.githubusercontent.com
[47086 ms] Error: Failed to download package for ghcr.io/devcontainers/templates/php
[47086 ms]     at aY (c:\Users\artist\.vscode\extensions\ms-vscode-remote.remote-containers-0.380.0\dist\spec-node\devContainersSpecCLI.js:607:6731)
[47086 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[47086 ms]     at async ArA (c:\Users\artist\.vscode\extensions\ms-vscode-remote.remote-containers-0.380.0\dist\spec-node\devContainersSpecCLI.js:607:9667)
[47086 ms]     at async c:\Users\artist\.vscode\extensions\ms-vscode-remote.remote-containers-0.380.0\dist\spec-node\devContainersSpecCLI.js:607:9102

**Comment by AlaricWeb** [comment]
Why do I start he will automatically start devcontainer I some projects to use this thing

**Comment by AlaricWeb** [comment]
Why do I start vscode is automatically start devcontainer I some projects to use this thing

**Comment by AlaricWeb** [comment]
![image](https://github.com/user-attachments/assets/3f7fce6d-31b4-4f84-8dca-c1e0ff264930)

**Comment by chrmarti** [comment]
@AlaricWeb It looks like you might be connected through SSH or a tunnel to a remote machine. Could you open a new issue if you think this is a problem? Thanks.

**Comment by AlaricWeb** [comment]
Ok，thanks

**Comment by alexr00** [comment]
@chrmarti is it possible to verify this?

**Comment by chrmarti** [comment]
To verify:
- Run `Dev Containers: Add Dev Container Configuration Files...`.
- After picking a predefined template disconnect your machine from the network.
- Continue and finish the QuickPick steps in the UI.
- Verify that at the end a dialog informing about the failure is shown offering to show the log.
