### ISSUE TITLE
Cannot connect to FreeBSD

### ISSUE THREAD

**Issue by hanusek** [microsoft/vscode-remote-release#10223]
- VSCode Version: July 2024 (version 1.92)
- Local OS Version: MacOS 14.5 (23F79)
- Remote OS Version: FreeBSD 14
- Remote Extension/Connection Type: Containers/WSL/Server

- Logs:
```
[12:18:44.830] Log Level: 2
[12:18:44.833] SSH Resolver called for "ssh-remote+localhost", attempt 1
[12:18:44.833] "remote.SSH.useLocalServer": true
[12:18:44.833] "remote.SSH.useExecServer": true
[12:18:44.834] "remote.SSH.path": undefined
[12:18:44.834] "remote.SSH.configFile": undefined
[12:18:44.834] "remote.SSH.useFlock": true
[12:18:44.834] "remote.SSH.lockfilesInTmp": false
[12:18:44.834] "remote.SSH.localServerDownload": auto
[12:18:44.834] "remote.SSH.remoteServerListenOnSocket": false
[12:18:44.834] "remote.SSH.showLoginTerminal": false
[12:18:44.834] "remote.SSH.defaultExtensions": []
[12:18:44.834] "remote.SSH.loglevel": 2
[12:18:44.834] "remote.SSH.enableDynamicForwarding": true
[12:18:44.834] "remote.SSH.enableRemoteCommand": false
[12:18:44.834] "remote.SSH.serverPickPortsFromRange": {}
[12:18:44.834] "remote.SSH.serverInstallPath": {}
[12:18:44.834] "remote.SSH.permitPtyAllocation": false
[12:18:44.834] "remote.SSH.preferredLocalPortRange: undefined
[12:18:44.834] "remote.SSH.useCurlAndWgetConfigurationFiles: false
[12:18:44.838] VS Code version: 1.92.2
[12:18:44.838] Remote-SSH version: remote-ssh@0.113.1
[12:18:44.838] darwin arm64
[12:18:44.839] SSH Resolver called for host: localhost
[12:18:44.839] Setting up SSH remote "localhost"
[12:18:44.841] Acquiring local install lock: /var/folders/t9/c1qs1ttd2sgg3mqfy58n3fg80000gn/T/vscode-remote-ssh-0150773a-install.lock
[12:18:44.842] Looking for existing server data file at /Users/mhanusek/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-0150773a-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9-0.113.1-es/data.json
[12:18:44.843] Using commit id "fee1edb8d6d72a0ddff41e5f71a671c23ed924b9" and quality "stable" for server
[12:18:44.844] Install and start server if needed
[12:18:44.846] PATH: /Library/PostgreSQL/16/bin:/Users/mhanusek/.nvm/versions/node/v19.6.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/mhanusek/.cargo/bin:/Applications/iTerm.app/Contents/Resources/utilitiesexport
[12:18:44.846] Checking ssh with "ssh -V"
[12:18:44.850] > OpenSSH_9.6p1, LibreSSL 3.3.6

[12:18:44.851] askpass server listening on /var/folders/t9/c1qs1ttd2sgg3mqfy58n3fg80000gn/T/vscode-ssh-askpass-ec351a6ef7fba8c171729ee82fe09310bea6a6da.sock
[12:18:44.852] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/t9/c1qs1ttd2sgg3mqfy58n3fg80000gn/T/vscode-ssh-askpass-491914fbd3627c426dc81f461680fb8849cb070c.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","51368","-o","ConnectTimeout=15","localhost"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/mhanusek/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-0150773a-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9-0.113.1-es/data.json"}
[12:18:44.852] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.Fg9mhdguZO/Listeners","SHELL":"/bin/zsh","DISPLAY":"ssh-askpass","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/mhanusek/.vscode/extensions/ms-vscode-remote.remote-ssh-0.113.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"","VSCODE_SSH_ASKPASS_MAIN":"/Users/mhanusek/.vscode/extensions/ms-vscode-remote.remote-ssh-0.113.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/t9/c1qs1ttd2sgg3mqfy58n3fg80000gn/T/vscode-ssh-askpass-ec351a6ef7fba8c171729ee82fe09310bea6a6da.sock"}
[12:18:44.852] Spawned 9993
[12:18:44.909] > local-server-1> Running ssh connection command: ssh -v -T -D 51368 -o ConnectTimeout=15 localhost
[12:18:44.910] > local-server-1> Spawned ssh, pid=10000
[12:18:44.913] stderr> OpenSSH_9.6p1, LibreSSL 3.3.6
[12:18:45.057] stderr> debug1: Server host key: ssh-ed25519 SHA256:lRAQX627xHAv5staa24zOKpLMOu+Pxan7TuJVO8uTJY
[12:18:45.165] Got askpass request: {"request":" (root@localhost) Password for root@freebsd-vm:"}
[12:18:45.166] Listening for interwindow password on /var/folders/t9/c1qs1ttd2sgg3mqfy58n3fg80000gn/T/vscode-ssh-askpass-4f439244df054fea680de2832675b1ccec383b0e.sock
[12:18:45.166] Writing password prompt to globalState
[12:18:49.798] Interactor gave response: *********
[12:18:49.799] Cleaning up other-window auth server
[12:18:49.855] stderr> Authenticated to localhost ([127.0.0.1]:22) using "keyboard-interactive".
[12:18:49.897] > ready: 1ee0c0cff419
[12:18:49.902] > FreeBSD 14.1-RELEASE FreeBSD 14.1-RELEASE releng/14.1-n267679-10e31f0946d8 GENERIC
[12:18:49.903] Platform: linux
[12:18:49.904] > /bin/sh
[12:18:49.904] Shell: sh
[12:18:49.904] Creating bash subshell inside "sh"
[12:18:49.913] > bash version:  5.2.26(1)-release
[12:18:49.925] > 1ee0c0cff419: running
[12:18:49.957] > Unsupported platform: FreeBSD
[12:18:49.957] > 1ee0c0cff419: start
[12:18:49.958] > exitCode==35==
> listeningOn====
> osReleaseId==freebsd==
[12:18:49.958] > arch====
> vscodeArch====
[12:18:49.959] > bitness====
[12:18:49.959] > tmpDir==/tmp==
> platform====
[12:18:49.959] > unpackResult====
> didLocalDownload==0==
[12:18:49.959] > downloadTime====
[12:18:49.960] > installTime====
[12:18:49.960] > serverStartTime====
[12:18:49.960] > execServerToken==a11aa111-1aaa-11a1-a1a1-11111a1a1aaa==
[12:18:49.960] > 1ee0c0cff419: end
[12:18:49.961] Received install output: exitCode==35==
listeningOn====
osReleaseId==freebsd==arch====
vscodeArch====bitness====tmpDir==/tmp==
platform====unpackResult====
didLocalDownload==0==downloadTime====installTime====serverStartTime====execServerToken==a11aa111-1aaa-11a1-a1a1-11111a1a1aaa==
[12:18:49.962] Failed to parse remote port from server output
[12:18:49.962] Terminating local server
[12:18:49.966] Resolver error: Error: 
	at m.Create (/Users/mhanusek/.vscode/extensions/ms-vscode-remote.remote-ssh-0.113.1/out/extension.js:2:501230)
	at t.handleInstallOutput (/Users/mhanusek/.vscode/extensions/ms-vscode-remote.remote-ssh-0.113.1/out/extension.js:2:498552)
	at e (/Users/mhanusek/.vscode/extensions/ms-vscode-remote.remote-ssh-0.113.1/out/extension.js:2:560378)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /Users/mhanusek/.vscode/extensions/ms-vscode-remote.remote-ssh-0.113.1/out/extension.js:2:582435
	at async t.withShowDetailsEvent (/Users/mhanusek/.vscode/extensions/ms-vscode-remote.remote-ssh-0.113.1/out/extension.js:2:586054)
	at async /Users/mhanusek/.vscode/extensions/ms-vscode-remote.remote-ssh-0.113.1/out/extension.js:2:557083
	at async T (/Users/mhanusek/.vscode/extensions/ms-vscode-remote.remote-ssh-0.113.1/out/extension.js:2:555134)
	at async t.resolveWithLocalServer (/Users/mhanusek/.vscode/extensions/ms-vscode-remote.remote-ssh-0.113.1/out/extension.js:2:556623)
	at async k (/Users/mhanusek/.vscode/extensions/ms-vscode-remote.remote-ssh-0.113.1/out/extension.js:2:579574)
	at async t.resolve (/Users/mhanusek/.vscode/extensions/ms-vscode-remote.remote-ssh-0.113.1/out/extension.js:2:583465)
	at async /Users/mhanusek/.vscode/extensions/ms-vscode-remote.remote-ssh-0.113.1/out/extension.js:2:851126
[12:18:49.972] ------

```

Steps to Reproduce:

1. Add remote server with FreeBSD14
2. Connect

**Comment by joshspicer** [comment]
Thank you for providing feedback and sharing your logs.  This extension does not [officially support](https://code.visualstudio.com/docs/remote/linux) FreeBSD.

That said, the pre-release build of the extension has experimental support for additional OSs/distributions (removing various assumptions that are incompatible with less-common distros).  If you're able to give it a try, you'll need to install the "pre-release" extension inside of [VS Code **Insiders**](https://code.visualstudio.com/insiders/)

![image](https://github.com/user-attachments/assets/c92c3109-21cf-46d4-8c37-0d2ea442b374)


That may just work out of the box for you. If not, please share the logs with me so I can explore how we can support your use case. Thanks!
