### ISSUE TITLE
Cannot connect windows if install coreutils uname

### ISSUE THREAD

**Issue by cathaysia** [microsoft/vscode-remote-release#10240]
- VSCode Version: 1.92.2
- Local OS Version: Linux 6.10.6-200.fc40.x86_64(Fedora 40)
- Remote OS Version: Windows10 22H2
- Remote Extension/Connection Type: Containers/WSL/Server: 1.92.2

Steps to reproduce:

1. install scoop on windows
2. run `scoop install uutils-coreutils`
3. try connect windows.
4. then failed.

Solve:

remove `~/scoop/shim/uname`

**Comment by joshspicer** [comment]
Thanks, might [appending your logs here](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting) so we can take a close look.  

We use the `uname` tool is various places. It seems here that the default program is being shadowed on your $PATH. We rely on the user's PATH in a lot of instances to resolve programs.  It may not be feasible for this extension to handle these kinds of shim programs (and your workaround may be the best path forward).  Regardless, i'll take a look at the logs and see what we can improve

**Comment by cathaysia** [comment]
Here is the output:

<details>

```console
[19:29:27.613] Log Level: 2
[19:29:27.615] SSH Resolver called for "ssh-remote+192.168.122.186", attempt 1
[19:29:27.616] "remote.SSH.useLocalServer": true
[19:29:27.616] "remote.SSH.useExecServer": true
[19:29:27.616] "remote.SSH.path": undefined
[19:29:27.616] "remote.SSH.configFile": undefined
[19:29:27.617] "remote.SSH.useFlock": true
[19:29:27.617] "remote.SSH.lockfilesInTmp": false
[19:29:27.617] "remote.SSH.localServerDownload": auto
[19:29:27.617] "remote.SSH.remoteServerListenOnSocket": false
[19:29:27.617] "remote.SSH.showLoginTerminal": false
[19:29:27.617] "remote.SSH.defaultExtensions": []
[19:29:27.617] "remote.SSH.loglevel": 2
[19:29:27.617] "remote.SSH.enableDynamicForwarding": true
[19:29:27.617] "remote.SSH.enableRemoteCommand": false
[19:29:27.617] "remote.SSH.serverPickPortsFromRange": {}
[19:29:27.617] "remote.SSH.serverInstallPath": {}
[19:29:27.617] "remote.SSH.permitPtyAllocation": false
[19:29:27.617] "remote.SSH.preferredLocalPortRange: undefined
[19:29:27.617] "remote.SSH.useCurlAndWgetConfigurationFiles: false
[19:29:27.628] VS Code version: 1.93.1
[19:29:27.628] Remote-SSH version: remote-ssh@0.113.2024072315
[19:29:27.628] linux x64
[19:29:27.629] SSH Resolver called for host: 192.168.122.186
[19:29:27.629] Setting up SSH remote "192.168.122.186"
[19:29:27.632] Acquiring local install lock: /tmp/vscode-remote-ssh-246819a6-install.lock
[19:29:27.633] Looking for existing server data file at /home/tea/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-246819a6-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40-0.113.2024072315-es/data.json
[19:29:27.633] Using commit id "38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40" and quality "stable" for server
[19:29:27.637] Install and start server if needed
[19:29:27.639] PATH: /nix/store/jwhrlnqc3kwnql6gj5gmgviwwhdagjsz-glib-2.80.4-bin/bin:/home/tea/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/lib64/ccache:/home/tea/.nix-profile/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin
[19:29:27.639] Checking ssh with "ssh -V"
[19:29:27.647] > OpenSSH_9.6p1, OpenSSL 3.2.2 4 Jun 2024

[19:29:27.650] askpass server listening on /run/user/1000/vscode-ssh-askpass-5738d6c9ec1a424045b4090a3247d01ad9532635.sock
[19:29:27.650] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-af0290806f9ee611827c56c3870b2390e828a7ac.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","35027","-o","ConnectTimeout=15","192.168.122.186"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/tea/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-246819a6-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40-0.113.2024072315-es/data.json"}
[19:29:27.650] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","SHELL":"/bin/zsh","DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/nix/store/z2jcrhk514ycr40clk4f7l9ygxanh3xh-vscode-extension-ms-vscode-remote-remote-ssh-0.113.2024072315/share/vscode/extensions/ms-vscode-remote.remote-ssh/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/nix/store/vynknv3hmgdviq3rvaqwap0c4da2g5mr-vscode-1.93.1/lib/vscode/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"","VSCODE_SSH_ASKPASS_MAIN":"/nix/store/z2jcrhk514ycr40clk4f7l9ygxanh3xh-vscode-extension-ms-vscode-remote-remote-ssh-0.113.2024072315/share/vscode/extensions/ms-vscode-remote.remote-ssh/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-5738d6c9ec1a424045b4090a3247d01ad9532635.sock"}
[19:29:27.653] Spawned 150758
[19:29:27.763] > local-server-1> Running ssh connection command: ssh -v -T -D 35027 -o ConnectTimeout=15 192.168.122.186
[19:29:27.766] > local-server-1> Spawned ssh, pid=150766
[19:29:27.768] stderr> OpenSSH_9.6p1, OpenSSL 3.2.2 4 Jun 2024
[19:29:27.842] stderr> debug1: Server host key: ssh-ed25519 SHA256:IJLKENFpsHyA+MA9j8La9h+WgGCvqPgmFZjmh9hGQwA
[19:29:27.901] stderr> Authenticated to 192.168.122.186 ([192.168.122.186]:22) using "publickey".
[19:29:27.939] > Microsoft Windows [�汾 10.0.19045.2965]
> (c) Microsoft Corporation����������Ȩ����
[19:29:27.939] > 
> kvm@DESKTOP-O33L5KF C:\Users\kvm>echo 'ready: 28a945639859'
[19:29:27.941] > 'ready: 28a945639859'
> 
> kvm@DESKTOP-O33L5KF C:\Users\kvm>
[19:29:27.942] > uname -rsv
[19:29:27.957] > Windows_NT 10.0 19045
[19:29:27.960] > 
> kvm@DESKTOP-O33L5KF C:\Users\kvm>
[19:29:44.654] Terminating local server
[19:29:44.656] Resolver error: Error: Connecting with SSH timed out
	at m.Timeout (/nix/store/z2jcrhk514ycr40clk4f7l9ygxanh3xh-vscode-extension-ms-vscode-remote-remote-ssh-0.113.2024072315/share/vscode/extensions/ms-vscode-remote.remote-ssh/out/extension.js:2:501356)
	at Timeout._onTimeout (/nix/store/z2jcrhk514ycr40clk4f7l9ygxanh3xh-vscode-extension-ms-vscode-remote-remote-ssh-0.113.2024072315/share/vscode/extensions/ms-vscode-remote.remote-ssh/out/extension.js:2:567468)
	at listOnTimeout (node:internal/timers:573:17)
	at process.processTimers (node:internal/timers:514:7)
[19:29:44.658] ------
```
</details>

**Comment by joshspicer** [comment]
Thinking about this more, I don't think we can reliably handle shimmed versions of standard tools.  As you've found, removing the shim program solves your issue.  

Feel free to comment back if you think we need to special case this particular tool, but I believe the best solution here is to ask `uutils-coreutils` to not override common programs on the PATH if they do not behave as standard
