### ISSUE TITLE
SSH: Extensions installation directory does not respect `remote.SSH.serverInstallPath`

### ISSUE THREAD

**Issue by joshspicer** [microsoft/vscode-remote-release#10255]
Based on: https://github.com/microsoft/vscode-remote-release/issues/10230#issuecomment-2341356290

## Steps
1. Set `remote.SSH.serverInstallPath` to a custom path (not $HOME)
2. Note in the logs that this setting is respected when installing the VS Code server, etc
3. At the very end of the log, note that extensions are downloaded into $HOME.

Expected behavior from report: the `serverInstallPath` is honored here too.

I am not 100% sure if this is a regression or not with `0.114.0`, or if this is expected behavior.  The report from @sirK84 indicates this is new behavior.

```
[16:49:06.393] [server] [14:49:06] Started initializing default profile extensions in extensions installation folder. file:///home/<<username>>/.vscode-server/extensions
```

Edit: @sirK84 shared that in the previous month's release those logs messages were not present and things worked as-expected:

>In v0.113.1 those logs are not present:
>
>[18:18:51.875] [server] [16:18:51] Extension host agent started.
>[18:18:52.058] [server] [16:18:51] [<unknown>][7e4c6472][ExtensionHostConnection] New connection established.
>[18:18:52.058] [server] [16:18:51] [<unknown>][f7a68617][ManagementConnection] New connection established.
>[18:18:52.230] [server] [16:18:52] [<unknown>][7e4c6472][ExtensionHostConnection] <12870> Launched Extension >Host Process.
>

**Comment by joshspicer** [comment]
From what i'm gathering, a probable reason for this regression is that this last release no longer exports (the deprecated) `VSCODE_AGENT_FOLDER` env variable [*](https://github.com/microsoft/vscode-internalbacklog/issues/2604).  If this is the case, we need to pass forward this folder info to the Server (the modern way is with the `--server-data-dir`, but this server is being spawned on our behalf in `useExecServer` mode.

**Comment by Aonnghus** [comment]
Coming from microsoft/vscode#227737.
I get the same log messages:
```
[22:52:57.574] [server] [22:52:57] Extension host agent started.
[22:52:57.574] [server] [22:52:57] Started initializing default profile extensions in extensions installation folder. file:///home/<username>/.vscode-server/extensions
[22:52:57.575] [server] [22:52:57] Completed initializing default profile extensions in extensions installation folder. file:///home/<username>/.vscode-server/extensions
```
Extensions are indeed not installed in the `serverInstallPath` directory.

**Comment by juxeii** [comment]
Same here. Extensions are installed in HOME dir.

**Comment by joshspicer** [comment]
Thank you all for the report.  Pre-release `v0.115.2024091122` should resolve this issue - please let me know 

![Image](https://github.com/user-attachments/assets/e1d41fce-52be-4ee9-958d-9cc5d136feb8)

**Comment by sirK84** [comment]
@joshspicer  I confirm, on my end v0.115.2024091122 solves all issues.

Attaching log for reference:
[RemoteSSH_v0.115.2024091122.log](https://github.com/user-attachments/files/16981273/RemoteSSH_v0.115.2024091122.log)

Thanks :)

**Comment by juxeii** [comment]
I can confirm, but strangely it seems that the extension always creates a `.vscode-server` folder in HOME, which is empty.
Would be great to get rid of it.

**Comment by joshspicer** [comment]
Thank you @sirK84 and @juxeii for taking the time to validate!

@juxeii - I'm not seeing that on my end.  If possible, please share your [logs](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting) here so I can take a peek.

**Comment by juxeii** [comment]
@joshspicer I checked again, and can confirm that this extension does **not** create the `.vscode-server` folder. Sorry for confusion.

**Comment by joshspicer** [comment]
@juxeii great! Thanks for following back up

**Comment by zaccrites-intel** [comment]
A temporary workaround that worked for me, until the next release:

On your local machine, close VSCode.

On the remote machine:
```sh
cd $HOME
rm -rf .vscode-server/
mkdir /data/some/other/path/.vscode-server-symlink-target
ln -sf /data/some/other/path/.vscode-server-symlink-target .vscode-server
```

On your local machine:
1. Delete or comment out the corresponding setting in `remote.SSH.serverInstallPath` for that remote.
2. Connect to the remote within VSCode to get it to install the server in the new location.
3. Reinstall any missing extensions. I had to reinstall the Python extension for some reason.

**Comment by joshspicer** [comment]
`0.114.3` has been released and includes the relevant patches.

**Comment by amunger** [comment]
I can't seem to get a successful connection when changing the install directory. tried `"remote.SSH.serverInstallPath": {"<IP>":"/usr/local"}` and `"remote.SSH.serverInstallPath": {"<IP>:"$HOME/server"}`

logs 

```
[15:18:35.516] Install and start server if needed
[15:18:35.520] Checking ssh with "C:\Python312\Scripts\ssh.exe -V"
[15:18:35.522] Got error from ssh: spawn C:\Python312\Scripts\ssh.exe ENOENT
[15:18:35.522] Checking ssh with "C:\Python312\ssh.exe -V"
[15:18:35.523] Got error from ssh: spawn C:\Python312\ssh.exe ENOENT
[15:18:35.523] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[15:18:35.524] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[15:18:35.524] Checking ssh with "C:\Windows\ssh.exe -V"
[15:18:35.524] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[15:18:35.524] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[15:18:35.525] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[15:18:35.525] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[15:18:35.525] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[15:18:35.526] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[15:18:35.558] > OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2

[15:18:35.562] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 59970 "104.42.213.64" sh
[15:18:35.563] Generated SSH command: 'type "C:\Users\aaron\AppData\Local\Temp\vscode-linux-multi-line-command-104.42.213.64-649707188.sh" | "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 59970 "104.42.213.64" sh'
[15:18:35.563] Terminal shell path: C:\Windows\System32\cmd.exe
[15:18:35.826] > [?9001h[?1004h
[15:18:35.827] Got some output, clearing connection timeout
[15:18:52.782] > 

> 
> ]0;C:\Windows\System32\cmd.exe
> 

> 
> 
[15:18:52.798] > 
> 

[15:18:56.934] > ssh: connect to host 104.42.213.64 port 22: Connection timed out
> The process tried to write to a nonexistent pipe.
[15:18:58.254] "install" terminal command done
[15:18:58.255] Install terminal quit with output: ssh: connect to host 104.42.213.64 port 22: Connection timed out
[15:18:58.255] Received install output: ssh: connect to host 104.42.213.64 port 22: Connection timed out
[15:18:58.258] Resolver error: Error: The connection timed out
	at v.Offline (c:\Users\aaron\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.114.3\out\extension.js:2:501455)
	at c:\Users\aaron\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.114.3\out\extension.js:2:497346
	at t.handleInstallOutput (c:\Users\aaron\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.114.3\out\extension.js:2:497661)
	at t.tryInstall (c:\Users\aaron\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.114.3\out\extension.js:2:616460)
	at async c:\Users\aaron\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.114.3\out\extension.js:2:575788
	at async t.withShowDetailsEvent (c:\Users\aaron\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.114.3\out\extension.js:2:579017)
	at async k (c:\Users\aaron\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.114.3\out\extension.js:2:572574)
	at async t.resolve (c:\Users\aaron\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.114.3\out\extension.js:2:576428)
	at async c:\Users\aaron\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.114.3\out\extension.js:2:844803
[15:18:58.269] ------
```

**Comment by joshspicer** [comment]
@amunger thanks for testing. Are you able to get a successful connection without any settings?  My read of these logs are that ssh is timing out on its initial connect (before this setting would come into play).

To rule that out, does `ssh 104.42.213.64` work in a separate powershell window? (I'm assuming `104.42.213.64` is the name of the host in your SSH config file)
![Image](https://github.com/user-attachments/assets/d00f5b63-7ab2-4a3e-965f-d70c424b69d9)

**Comment by amunger** [comment]
well, now it's working just fine after booting up the remote machine again today.

```
[09:49:38.122] [server] [16:49:37] Completed initializing default profile extensions in extensions installation folder. file:///home/aamunger/server/.vscode-server-insiders/extensions
```
