### ISSUE TITLE
Issue with installing vscode/node server in alternate directory

### ISSUE THREAD

**Issue by stevendwilson1988** [microsoft/vscode-remote-release#10266]
I use VSCode on a mostly read only remote file system.  I have a read/write folder in /tmp/data, and that is where I configure the vscode/node remote server to be installed,  This stopped working in the latests remote ssh version.  Will share logs shortly.

Here is the working case using vscode 1.92.2.  The node server installs under /tmp/data
```
[21:06:00.028] [server] Starting server with command... Command { std: "/tmp/data/.vscode-server/cli/servers/Stable-fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/server/bin/code-server" "--connection-token=remotessh" "--accept-server-license-terms" "--start-server" "--enable-remote-auto-shutdown" "--socket-path=/tmp/code-ed38d1b0-b697-41b6-89e7-87a0fcb2e682", kill_on_drop: false }
[21:06:00.791] [server] *
[21:06:00.833] [server] * Visual Studio Code Server
[21:06:00.833] [server] *
[21:06:00.833] [server] * By using the software, you agree to
[21:06:00.833] [server] * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
[21:06:00.833] [server] Server bound to /tmp/code-ed38d1b0-b697-41b6-89e7-87a0fcb2e682
[21:06:00.833] [server] Extension host agent listening on /tmp/code-ed38d1b0-b697-41b6-89e7-87a0fcb2e682
[21:06:00.834] [server] parsed location: "/tmp/code-ed38d1b0-b697-41b6-89e7-87a0fcb2e682"
[21:06:00.834] [server] 
[21:06:00.834] [server] Server started
[21:06:01.783] [server] [02:06:01] 
[21:06:01.827] [server] 
[21:06:01.827] [server] 
[21:06:01.827] [server] 
[21:06:02.120] [server] [02:06:01] [Error: ENOENT: no such file or directory, mkdir '/home/root/.cache'] {
[21:06:02.161] [server]   errno: -2,
[21:06:02.162] [server]   code: 'ENOENT',
[21:06:02.162] [server]   syscall: 'mkdir',
[21:06:02.204] [server] [02:06:01] Extension host agent started.
[21:06:02.468] [server] [02:06:02] [<unknown>][ab220ceb][ExtensionHostConnection] New connection established.
[21:06:02.472] [server] [02:06:02] [<unknown>][9ddb8068][ManagementConnection] New connection established.
[21:06:03.004] [server] [02:06:02] [<unknown>][ab220ceb][ExtensionHostConnection] <19568> Launched Extension Host Process.
[21:06:05.072] Opening exec server for ssh-remote+10.0.0.13
[21:06:05.078] Verified and reusing cached exec server for ssh-remote+10.0.0.13
```

**Comment by joshspicer** [comment]
Thank you for taking the time to open an issue.  This may be fixed in the "pre-release" build of the extension.  Would you mind trying there to validate if this is a new issue or has been fixed? 

 If the issue still persists with the pre-release, please attach your entire log output so I can debug further -thanks!

**Comment by stevendwilson1988** [comment]
Hi, John.  I can do that, but can you confirm which extension?

Install the Pre-release of the "Remote Explorer" extension?

[cid:ba1dd645-af96-4188-b77e-358d017f431b]
________________________________

**Comment by joshspicer** [comment]
Thanks! The Remote - SSH extension, swapping to the pre-release channel temporarily by pressing this button:

![Image](https://github.com/user-attachments/assets/07adac4e-ff9e-4c7a-ad1d-3e98f5e291af)

**Comment by stevendwilson1988** [comment]
John, I did that, but I'm still getting an error.

Set to pre-release here
[cid:a1b67607-650d-46a0-a9ac-9540be682655]

Here are the logs in the failing case.

[13:23:47.525] Log Level: 2
[13:23:47.556] VS Code version: 1.93.1
[13:23:47.557] Remote-SSH version: ***@***.***
[13:23:47.557] win32 x64
[13:23:47.585] SSH Resolver called for "ssh-remote+10.0.0.13", attempt 1
[13:23:47.586] "remote.SSH.useLocalServer": false
[13:23:47.586] "remote.SSH.useExecServer": true
[13:23:47.586] "remote.SSH.showLoginTerminal": false
[13:23:47.587] "remote.SSH.remotePlatform": {"10.0.0.108":"linux","10.0.0.214":"linux","10.0.0.203":"linux","10.0.0.180":"linux","10.0.0.13":"linux","10.0.0.10":"linux","10.0.0.148":"linux","10.0.0.184":"linux","69.136.48.211":"linux","10.0.0.195":"linux","10.0.0.117":"linux","10.0.0.48":"linux","10.0.0.164":"linux","192.168.2.43":"linux","10.0.0.16":"linux","10.0.0.219":"linux"}
[13:23:47.587] "remote.SSH.path": undefined
[13:23:47.587] "remote.SSH.configFile": C:\Users\swilso757\.ssh\config
[13:23:47.587] "remote.SSH.useFlock": true
[13:23:47.587] "remote.SSH.lockfilesInTmp": true
[13:23:47.587] "remote.SSH.localServerDownload": auto
[13:23:47.588] "remote.SSH.remoteServerListenOnSocket": false
[13:23:47.588] "remote.SSH.showLoginTerminal": false
[13:23:47.588] "remote.SSH.defaultExtensions": []
[13:23:47.588] "remote.SSH.loglevel": 2
[13:23:47.588] "remote.SSH.enableDynamicForwarding": true
[13:23:47.588] "remote.SSH.enableRemoteCommand": false
[13:23:47.588] "remote.SSH.serverPickPortsFromRange": {}
[13:23:47.592] "remote.SSH.serverInstallPath": {"10.0.0.203":"/tmp/data/","10.0.0.180":"/tmp/data/","10.0.0.13":"/tmp/data","10.0.0.148":"/tmp/data/","10.0.0.184":"/tmp/data/","10.0.0.195":"/tmp/data","10.0.0.40":"/tmp/data/","10.0.0.117":"/tmp/data","10.0.0.48":"/tmp/data","10.0.0.164":"/tmp/data","10.0.0.219":"/tmp/data"}
[13:23:47.592] "remote.SSH.permitPtyAllocation": false
[13:23:47.592] "remote.SSH.preferredLocalPortRange: undefined
[13:23:47.592] "remote.SSH.useCurlAndWgetConfigurationFiles: false
[13:23:47.617] SSH Resolver called for host: 10.0.0.13
[13:23:47.617] Setting up SSH remote "10.0.0.13"
[13:23:47.626] Using commit id "38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40" and quality "stable" for server
[13:23:47.633] Script variables:
 {
  "InstallExitCode.24": "AlreadyInProgress",
  "InstallExitCode.25": "ServerDownloadFailed",
  "InstallExitCode.26": "NoDownloaderAvailable",
  "InstallExitCode.27": "UnsupportedArch",
  "InstallExitCode.28": "StatusCheckFailed",
  "InstallExitCode.29": "NeedInsidersArch",
  "InstallExitCode.30": "NoDownloaderAvailableForStatusCheck",
  "InstallExitCode.31": "ServerTransferFailed",
  "InstallExitCode.32": "ServerFailedToStart",
  "InstallExitCode.33": "NeedInsidersWindows",
  "InstallExitCode.34": "CreateInstallDirFailed",
  "InstallExitCode.35": "UnsupportedPlatform",
  "InstallExitCode.36": "ServerTerminatedCVE20201416",
  "InstallExitCode.37": "UnpackFailed",
  "InstallExitCode.38": "ChangeDirFailed",
  "InstallExitCode.AlreadyInProgress": "24",
  "InstallExitCode.ServerDownloadFailed": "25",
  "InstallExitCode.NoDownloaderAvailable": "26",
  "InstallExitCode.NoDownloaderAvailableForStatusCheck": "30",
  "InstallExitCode.UnsupportedArch": "27",
  "InstallExitCode.StatusCheckFailed": "28",
  "InstallExitCode.NeedInsidersArch": "29",
  "InstallExitCode.ServerTransferFailed": "31",
  "InstallExitCode.ServerFailedToStart": "32",
  "InstallExitCode.NeedInsidersWindows": "33",
  "InstallExitCode.CreateInstallDirFailed": "34",
  "InstallExitCode.UnsupportedPlatform": "35",
  "InstallExitCode.ServerTerminatedCVE20201416": "36",
  "InstallExitCode.UnpackFailed": "37",
  "InstallExitCode.ChangeDirFailed": "38",
  "InstallUnpackCode.Success": "success",
  "InstallUnpackCode.Error": "error",
  "InstallUnpackCode.MissingFiles": "missingFiles",
  "uuid": "e1c1f8d09f05",
  "startMarker": "e1c1f8d09f05: running",
  "commitId": "38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40",
  "quality": "stable",
  "token": "11a111a1-a11a-1a11-aa11-1a11111a11a1",
  "vscodeAgentFolder": "/tmp/data/.vscode-server",
  "allowClientDownload": "1",
  "forceClientDownload": "0",
  "cliNameInArchive": "code",
  "ignoreWgetConfigFlag": " --no-config ",
  "ignoreCurlConfigFlag": " --disable ",
  "wgetTriesSegment": "--tries=1",
  "listenArgs": "--on-host=127.0.0.1 --on-port",
  "getDownloadServerStartTrigger": "e1c1f8d09f05:trigger_server_download",
  "getDownloadServerEndTrigger": "e1c1f8d09f05:trigger_server_download_end",
  "getProgressDownloading": "e1c1f8d09f05%%1%%",
  "getProgressInstalling": "e1c1f8d09f05%%2%%"
}
[13:23:47.645] Install and start server if needed
[13:23:47.651] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[13:23:47.664] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[13:23:47.665] Checking ssh with "C:\Windows\ssh.exe -V"
[13:23:47.668] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[13:23:47.669] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[13:23:47.675] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[13:23:47.676] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[13:23:47.679] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[13:23:47.680] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[13:23:47.854] > OpenSSH_for_Windows_
[13:23:47.855] > 8.1p1, LibreSSL 3.0.2

[13:23:47.871] Using SSH config file "C:\Users\swilso757\.ssh\config"
[13:23:47.872] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 54270 -o RemoteCommand=none -F "C:\Users\swilso757\.ssh\config" "10.0.0.13" sh
[13:23:47.898] Generated SSH command: 'type "C:\Users\SWILSO~1\AppData\Local\Temp\vscode-linux-multi-line-command-10.0.0.13-931467501.sh" | "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 54270 -o RemoteCommand=none -F "C:\Users\swilso757\.ssh\config" "10.0.0.13" sh'
[13:23:47.900] Terminal shell path: C:\Windows\System32\cmd.exe
[13:23:48.421] > ]0;C:\Windows\System32\cmd.exe
[13:23:48.422] Got some output, clearing connection timeout
[13:23:48.582] > e1c1f8d09f05: running
[13:23:48.637] > Script executing under PID: 9211
> Installing to /tmp/data/.vscode-server...
> sh: line 121: getconf: command not found
[13:23:48.655] > e1c1f8d09f05%%1%%
[13:23:48.673] > Downloading with wget
> wget is from busybox: no
> Detected that this version of wget does not support '--no-config'. Will not igno
> re wget default configuration files.
> wget download failed
> wget: unrecognized option '--tries=1'
> BusyBox v1.31.1 (2024-03-18 05:56:18 UTC) multi-call binary.
>
> Usage: wget [-c|--continue] [--spider] [-q|--quiet] [-O|--output-document FILE]
>         [-o|--output-file FILE] [--header 'header: value'] [-Y|--proxy on/off]
>         [-P DIR] [-S|--server-response] [-U|--user-agent AGENT] [-T SEC] URL...
> printenv:
> Trigger local server download
> e1c1f8d09f05:trigger_server_download
> artifact==cli-linux-armhf==
> destFolder==/tmp/data/.vscode-server==
> destFolder2==/vscode-cli-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40.tar.gz==
> e1c1f8d09f05:trigger_server_download_end
[13:23:48.673] Got request to download on client for {"artifact":"cli-linux-armhf","destPath":"/tmp/data/.vscode-server/vscode-cli-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40.tar.gz"}
[13:23:48.673] server download URL: https://update.code.visualstudio.com/commit:38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/cli-linux-armhf/stable
[13:23:48.674] Downloading VS Code server locally...
[13:23:48.715] > Program 'wget' is not available or does not appear to support flag '--no-config'
> sh: line 92: printenv: command not found
> Waiting for client to transfer server archive...
> Waiting for /tmp/data/.vscode-server/vscode-cli-38c31bc77e0dd6ae88a4e9cc93428cc2
> 7a56ba40.tar.gz.done and vscode-server.tar.gz to exist
>
[13:23:48.784] Downloaded VS Code server to c:\Users\SWILSO~1\AppData\Local\Temp\699fab93-83cb-45b1-80e5-4cdbf45eaf33
[13:23:48.786] Renamed VS Code server to c:\Users\SWILSO~1\AppData\Local\Temp\vscode_server_1726248228784\vscode-cli-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40.tar.gz
[13:23:48.786] Preparing to scp to host 10.0.0.13
[13:23:48.794] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[13:23:48.797] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[13:23:48.798] Checking ssh with "C:\Windows\ssh.exe -V"
[13:23:48.800] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[13:23:48.800] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[13:23:48.805] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[13:23:48.805] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[13:23:48.811] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[13:23:48.812] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[13:23:48.920] > OpenSSH_for_Windows_8.1p
[13:23:48.921] > 1, LibreSSL 3.0.2

[13:23:48.926] Expecting scp to be next to ssh at C:\Windows\System32\OpenSSH\scp.exe
[13:23:48.926] Testing scp with "C:\Windows\System32\OpenSSH\scp.exe"
[13:23:49.058] scp exited with code: 1
[13:23:49.058] Got stderr from scp: usage: scp [-346BCpqrTv] [-c cipher] [-F ssh_config] [-i identity_file]
            [-J destination] [-l limit] [-o ssh_option] [-P port]
            [-S program] source ... target
[13:23:49.059] Using SSH config file "C:\Users\swilso757\.ssh\config"
[13:23:49.059] Copying file to remote with "C:\Windows\System32\OpenSSH\scp.exe" -F "C:\Users\swilso757\.ssh\config" "vscode-cli-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40.tar.gz" "vscode-cli-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40.tar.gz.done" "10.0.0.13":"/tmp/data/.vscode-server"
[13:23:49.059] Using cwd: file:///c%3A/Users/SWILSO~1/AppData/Local/Temp/vscode_server_1726248228784
[13:23:49.060] Terminal shell path: C:\Windows\System32\cmd.exe
[13:23:49.497] > ]0;C:\Windows\System32\cmd.exe
[13:23:49.769] > vscode-cli-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40.tar.gz   0%    0     0.0KB/
[13:23:50.556] > vscode-cli-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40.tar.gz 100% 7864KB   9.6MB/
[13:23:50.578] >
> vscode-cli-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40.tar.gz.done 100%    9     0
[13:23:51.666] > Found flag and server on host
[13:23:51.692] > e1c1f8d09f05%%2%%
> tar --version:
> ERROR: tar exited with a non-zero exit code: 1
> Already attempted local download, failing
> e1c1f8d09f05: start
> exitCode==37==
> listeningOn====
> osReleaseId==rdk==
> arch==armv7l==
> vscodeArch==armhf==
> bitness====
> tmpDir==/tmp==
> tar: unrecognized option '--version'
> BusyBox v1.31.1 (2024-03-18 05:56:18 UTC) multi-call binary.
>
> Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [FILE]
> ...
> tar: unrecognized option '--no-same-owner'
> BusyBox v1.31.1 (2024-03-18 05:56:18 UTC) multi-call binary.
>
> Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [FILE]
> ...
> platform==linux==
> unpackResult==error==
> didLocalDownload==1==
> downloadTime====
> installTime==16==
[13:23:51.698] >
> serverStartTime====
> execServerToken==11a111a1-a11a-1a11-aa11-1a11111a11a1==
> platformDownloadPath==cli-linux-armhf==
> e1c1f8d09f05: end
[13:23:51.854] "Copy server to host" terminal command done
[13:23:52.973] "install" terminal command done
[13:23:52.974] Install terminal quit with output: e1c1f8d09f05: end
[13:23:52.974] Received install output: e1c1f8d09f05: end
[13:23:52.974] Failed to parse remote port from server output
[13:23:52.976] Resolver error: Error:
    at v.Create (c:\Users\swilso757\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.2024091215\out\extension.js:2:501404)
    at t.handleInstallOutput (c:\Users\swilso757\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.2024091215\out\extension.js:2:498726)
    at t.tryInstall (c:\Users\swilso757\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.2024091215\out\extension.js:2:616460)
    at async c:\Users\swilso757\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.2024091215\out\extension.js:2:575788
    at async t.withShowDetailsEvent (c:\Users\swilso757\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.2024091215\out\extension.js:2:579017)
    at async k (c:\Users\swilso757\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.2024091215\out\extension.js:2:572574)
    at async t.resolve (c:\Users\swilso757\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.2024091215\out\extension.js:2:576428)
    at async c:\Users\swilso757\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.2024091215\out\extension.js:2:844812
[13:23:52.981] ------




[13:23:53.358] Opening exec server for ssh-remote+10.0.0.13
[13:23:53.383] Initizing new exec server for ssh-remote+10.0.0.13
[13:23:53.385] Using commit id "38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40" and quality "stable" for server
[13:23:53.399] Script variables:
 {
  "InstallExitCode.24": "AlreadyInProgress",
  "InstallExitCode.25": "ServerDownloadFailed",
  "InstallExitCode.26": "NoDownloaderAvailable",
  "InstallExitCode.27": "UnsupportedArch",
  "InstallExitCode.28": "StatusCheckFailed",
  "InstallExitCode.29": "NeedInsidersArch",
  "InstallExitCode.30": "NoDownloaderAvailableForStatusCheck",
  "InstallExitCode.31": "ServerTransferFailed",
  "InstallExitCode.32": "ServerFailedToStart",
  "InstallExitCode.33": "NeedInsidersWindows",
  "InstallExitCode.34": "CreateInstallDirFailed",
  "InstallExitCode.35": "UnsupportedPlatform",
  "InstallExitCode.36": "ServerTerminatedCVE20201416",
  "InstallExitCode.37": "UnpackFailed",
  "InstallExitCode.38": "ChangeDirFailed",
  "InstallExitCode.AlreadyInProgress": "24",
  "InstallExitCode.ServerDownloadFailed": "25",
  "InstallExitCode.NoDownloaderAvailable": "26",
  "InstallExitCode.NoDownloaderAvailableForStatusCheck": "30",
  "InstallExitCode.UnsupportedArch": "27",
  "InstallExitCode.StatusCheckFailed": "28",
  "InstallExitCode.NeedInsidersArch": "29",
  "InstallExitCode.ServerTransferFailed": "31",
  "InstallExitCode.ServerFailedToStart": "32",
  "InstallExitCode.NeedInsidersWindows": "33",
  "InstallExitCode.CreateInstallDirFailed": "34",
  "InstallExitCode.UnsupportedPlatform": "35",
  "InstallExitCode.ServerTerminatedCVE20201416": "36",
  "InstallExitCode.UnpackFailed": "37",
  "InstallExitCode.ChangeDirFailed": "38",
  "InstallUnpackCode.Success": "success",
  "InstallUnpackCode.Error": "error",
  "InstallUnpackCode.MissingFiles": "missingFiles",
  "uuid": "0ddc70ab3753",
  "startMarker": "0ddc70ab3753: running",
  "commitId": "38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40",
  "quality": "stable",
  "token": "1aaa1111-aa11-1111-aaa1-aa111a1a11a1",
  "vscodeAgentFolder": "/tmp/data/.vscode-server",
  "allowClientDownload": "1",
  "forceClientDownload": "0",
  "cliNameInArchive": "code",
  "ignoreWgetConfigFlag": " --no-config ",
  "ignoreCurlConfigFlag": " --disable ",
  "wgetTriesSegment": "--tries=1",
  "listenArgs": "--on-host=127.0.0.1 --on-port",
  "getDownloadServerStartTrigger": "0ddc70ab3753:trigger_server_download",
  "getDownloadServerEndTrigger": "0ddc70ab3753:trigger_server_download_end",
  "getProgressDownloading": "0ddc70ab3753%%1%%",
  "getProgressInstalling": "0ddc70ab3753%%2%%"
}
[13:23:53.401] Install and start server if needed
[13:23:53.415] Using SSH config file "C:\Users\swilso757\.ssh\config"
[13:23:53.415] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 54270 -o RemoteCommand=none -F "C:\Users\swilso757\.ssh\config" "10.0.0.13" sh
[13:23:53.419] Generated SSH command: 'type "C:\Users\SWILSO~1\AppData\Local\Temp\vscode-linux-multi-line-command-10.0.0.13-33087540.sh" | "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 54270 -o RemoteCommand=none -F "C:\Users\swilso757\.ssh\config" "10.0.0.13" sh'
[13:23:53.420] Terminal shell path: C:\Windows\System32\cmd.exe
[13:23:53.895] > ]0;C:\Windows\System32\cmd.exe
[13:23:53.895] Got some output, clearing connection timeout
[13:23:54.059] > 0ddc70ab3753: running
[13:23:54.088] > Script executing under PID: 9277
> sh: line 121: getconf: command not found
[13:23:54.115] > Installing to /tmp/data/.vscode-server...
[13:23:54.150] > 0ddc70ab3753%%1%%
> Downloading with wget
> wget is from busybox: no
> Detected that this version of wget does not support '--no-config'. Will not igno
> re wget default configuration files.
> wget download failed
> wget: unrecognized option '--tries=1'
> BusyBox v1.31.1 (2024-03-18 05:56:18 UTC) multi-call binary.
>
> Usage: wget [-c|--continue] [--spider] [-q|--quiet] [-O|--output-document FILE]
>         [-o|--output-file FILE] [--header 'header: value'] [-Y|--proxy on/off]
>         [-P DIR] [-S|--server-response] [-U|--user-agent AGENT] [-T SEC] URL...
> printenv:
> Trigger local server download
> 0ddc70ab3753:trigger_server_download
> artifact==cli-linux-armhf==
> destFolder==/tmp/data/.vscode-server==
> destFolder2==/vscode-cli-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40.tar.gz==
> 0ddc70ab3753:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /tmp/data/.vscode-server/vscode-cli-38c31bc77e0dd6ae88a4e9cc93428cc2
> 7a56ba40.tar.gz.done and vscode-server.tar.gz to exist
>
[13:23:54.151] Got request to download on client for {"artifact":"cli-linux-armhf","destPath":"/tmp/data/.vscode-server/vscode-cli-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40.tar.gz"}
[13:23:54.151] server download URL: https://update.code.visualstudio.com/commit:38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/cli-linux-armhf/stable
[13:23:54.151] Downloading VS Code server locally...
[13:23:54.167] >  Program 'wget' is not available or does not appear to support flag '--no-config
> '
> sh: line 92: printenv: command not found
[13:23:54.256] Downloaded VS Code server to c:\Users\SWILSO~1\AppData\Local\Temp\9f650a3c-9660-4bf1-ba3a-03e1e89645ee
[13:23:54.258] Renamed VS Code server to c:\Users\SWILSO~1\AppData\Local\Temp\vscode_server_1726248234256\vscode-cli-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40.tar.gz
[13:23:54.259] Preparing to scp to host 10.0.0.13
[13:23:54.264] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[13:23:54.268] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[13:23:54.269] Checking ssh with "C:\Windows\ssh.exe -V"
[13:23:54.271] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[13:23:54.271] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[13:23:54.274] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[13:23:54.274] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[13:23:54.276] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[13:23:54.276] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[13:23:54.380] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[13:23:54.386] Expecting scp to be next to ssh at C:\Windows\System32\OpenSSH\scp.exe
[13:23:54.386] Testing scp with "C:\Windows\System32\OpenSSH\scp.exe"
[13:23:54.514] scp exited with code: 1
[13:23:54.514] Got stderr from scp: usage: scp [-346BCpqrTv] [-c cipher] [-F ssh_config] [-i identity_file]
            [-J destination] [-l limit] [-o ssh_option] [-P port]
            [-S program] source ... target
[13:23:54.515] Using SSH config file "C:\Users\swilso757\.ssh\config"
[13:23:54.515] Copying file to remote with "C:\Windows\System32\OpenSSH\scp.exe" -F "C:\Users\swilso757\.ssh\config" "vscode-cli-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40.tar.gz" "vscode-cli-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40.tar.gz.done" "10.0.0.13":"/tmp/data/.vscode-server"
[13:23:54.516] Using cwd: file:///c%3A/Users/SWILSO~1/AppData/Local/Temp/vscode_server_1726248234256
[13:23:54.516] Terminal shell path: C:\Windows\System32\cmd.exe
[13:23:54.963] > ]0;C:\Windows\System32\cmd.exe
[13:23:55.240] > vscode-cli-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40.tar.gz   0%    0     0.0KB/
[13:23:56.083] > vscode-cli-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40.tar.gz 100% 7864KB   9.2MB/
[13:23:56.104] >
> vscode-cli-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40.tar.gz.done 100%    9     0
[13:23:57.153] > Found flag and server on host
[13:23:57.173] > 0ddc70ab3753%%2%%
> tar --version:
> ERROR: tar exited with a non-zero exit code: 1
> Already attempted local download, failing
> 0ddc70ab3753: start
> exitCode==37==
> listeningOn====
> osReleaseId==rdk==
> arch==armv7l==
> vscodeArch==armhf==
> bitness====
> tmpDir==/tmp==
> platform==linux==
> tar: unrecognized option '--version'
> BusyBox v1.31.1 (2024-03-18 05:56:18 UTC) multi-call binary.
>
> Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [FILE]
> ...
> tar: unrecognized option '--no-same-owner'
> BusyBox v1.31.1 (2024-03-18 05:56:18 UTC) multi-call binary.
>
> Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [FILE]
> ...
> unpackResult==error==
> didLocalDownload==1==
> downloadTime====
> installTime==16==
> serverStartTime====
> execServerToken==1aaa1111-aa11-1111-aaa1-aa111a1a11a1==
> platformDownloadPath==cli-linux-armhf==
> 0ddc70ab3753: end
[13:23:57.174] Received install output:
exitCode==37==
listeningOn====
osReleaseId==rdk==
arch==armv7l==
vscodeArch==armhf==
bitness====
tmpDir==/tmp==
platform==linux==
tar: unrecognized option '--version'
BusyBox v1.31.1 (2024-03-18 05:56:18 UTC) multi-call binary.

Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [FILE]
...
tar: unrecognized option '--no-same-owner'
BusyBox v1.31.1 (2024-03-18 05:56:18 UTC) multi-call binary.

Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [FILE]
...
unpackResult==error==
didLocalDownload==1==
downloadTime====
installTime==16==
serverStartTime====
execServerToken==1aaa1111-aa11-1111-aaa1-aa111a1a11a1==
platformDownloadPath==cli-linux-armhf==

[13:23:57.174] Exec server for ssh-remote+10.0.0.13 failed: Error: Failed to install the VS Code Server
[13:23:57.174] Error opening exec server for ssh-remote+10.0.0.13: Error: Failed to install the VS Code Server
[13:23:57.408] "Copy server to host" terminal command done
[13:23:58.450] "install" terminal command done
[13:23:58.450] Install terminal quit with output:

________________________________

**Comment by stevendwilson1988** [comment]
This is working for me today if I upgrade to the latest version of VSCode without upgrading the remote SSH Plugin....

![Screenshot 2024-09-22 073129](https://github.com/user-attachments/assets/e5dfb573-83ea-4332-be80-241ca3537afa)

**Comment by stevendwilson1988** [comment]
I think it can be closed, but I'm not on a PC.  Go ahead and close it if you can.
________________________________

**Comment by stevendwilson1988** [comment]
I’ve been using successfully since my last post.

Thanks
