### ISSUE TITLE
Connection timeout - hangs on "Waiting for pid of spawned 'sh' subshell"

### ISSUE THREAD

**Issue by carasel** [microsoft/vscode-remote-release#10278]
Trying to connect to a remote machine that doesn't have internet access. The ssh connection is working fine, but it then hangs before trying to download/scp the server

- VSCode Version: 1.93.1
- Local OS Version: Ubuntu 22.04.5
- Remote OS Version: Ubuntu 22.04.3
- Remote Extension/Connection Type: Server

- Logs:
```
[14:39:15.072] > ready: 2b4b72694728
[14:39:15.103] > Linux 6.2.0-1016-aws #16~22.04.1-Ubuntu SMP Sun Nov  5 20:08:16 UTC 2023
[14:39:15.104] Platform: linux
[14:39:15.133] > /bin/bash
[14:39:15.133] Parent Shell: bash
[14:39:15.133] Parent Shell pid: 565238
[14:39:15.166] > 152453
[14:39:15.166] Waiting for pid of spawned 'sh' subshell: '152453'...
[14:42:15.085] Terminating local server
[14:42:15.088] Resolver error: Error: Connecting with SSH timed out
	at v.Timeout (/home/me/.vscode/extensions/ms-vscode-remote.remote-ssh-0.114.3/out/extension.js:2:501530)
	at Timeout._onTimeout (/home/me/.vscode/extensions/ms-vscode-remote.remote-ssh-0.114.3/out/extension.js:2:560244)
	at listOnTimeout (node:internal/timers:573:17)
	at process.processTimers (node:internal/timers:514:7)
[14:42:15.091] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"1","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Timeout","exitCodeLabel":""},"measures":{"resolveAttempts":1,"isExecServer":0,"timing.totalResolveTime":182046,"timing.preSshTime":40}}
[14:42:15.094] ------
```

**Comment by joshspicer** [comment]
Does the remote machine have `scp` installed?  From my observation most of the time it's  provided along with the client `ssh` program

**Comment by carasel** [comment]
> Does the remote machine have `scp` installed? From my observation most of the time it's provided along with the client `ssh` program

@joshspicer yes, the remote machine does have `scp`. Another user has been able to use vscode server successfully on the same remote machine.

**Comment by joshspicer** [comment]
Thanks for confirming.  Would you be able to provide the full log (that way I can see what settings you have enabled, etc)?

**Comment by carasel** [comment]
```
[11:39:37.527] Log Level: 1
[11:39:37.536] SSH Resolver called for "ssh-remote+my-server", attempt 1
[11:39:37.536] "remote.SSH.useLocalServer": true
[11:39:37.536] "remote.SSH.useExecServer": true
[11:39:37.537] "remote.SSH.path": undefined
[11:39:37.537] "remote.SSH.configFile": undefined
[11:39:37.537] "remote.SSH.useFlock": true
[11:39:37.537] "remote.SSH.lockfilesInTmp": true
[11:39:37.537] "remote.SSH.localServerDownload": always
[11:39:37.537] "remote.SSH.remoteServerListenOnSocket": false
[11:39:37.537] "remote.SSH.showLoginTerminal": true
[11:39:37.537] "remote.SSH.defaultExtensions": []
[11:39:37.537] "remote.SSH.loglevel": 1
[11:39:37.538] "remote.SSH.maxReconnectionAttempts": 2
[11:39:37.538] "remote.SSH.enableDynamicForwarding": true
[11:39:37.538] "remote.SSH.enableRemoteCommand": true
[11:39:37.538] "remote.SSH.serverPickPortsFromRange": {}
[11:39:37.538] "remote.SSH.serverInstallPath": {}
[11:39:37.538] "remote.SSH.permitPtyAllocation": false
[11:39:37.538] "remote.SSH.preferredLocalPortRange: undefined
[11:39:37.538] "remote.SSH.useCurlAndWgetConfigurationFiles: false
[11:39:37.553] VS Code version: 1.93.1
[11:39:37.553] Remote-SSH version: remote-ssh@0.114.3
[11:39:37.553] linux x64
[11:39:37.554] SSH Resolver called for host: my-server
[11:39:37.554] Setting up SSH remote "my-server"
[11:39:37.557] Acquiring local install lock: /tmp/vscode-remote-ssh-3bf5ddfe-install.lock
[11:39:37.558] Looking for existing server data file at /home/me/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-3bf5ddfe-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40-0.114.3-es/data.json
[11:39:37.559] No existing data file
[11:39:37.559] Using commit id "38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40" and quality "stable" for server
[11:39:37.561] Script variables:
 {
  "InstallExitCode.24": "AlreadyInProgress",
  "InstallExitCode.25": "ServerDownloadFailed",
  "InstallExitCode.26": "NoDownloaderAvailable",
  "InstallExitCode.27": "UnsupportedArch",
  "InstallExitCode.28": "StatusCheckFailed",
  "InstallExitCode.29": "NeedInsidersArch",
  "InstallExitCode.30": "NoDownloaderAvailableForStatusCheck",
  "InstallExitCode.31": "ServerTransferFailed",
  "InstallExitCode.32": "ServerFailedToStart",
  "InstallExitCode.33": "NeedInsidersWindows",
  "InstallExitCode.34": "CreateInstallDirFailed",
  "InstallExitCode.35": "UnsupportedPlatform",
  "InstallExitCode.36": "ServerTerminatedCVE20201416",
  "InstallExitCode.37": "UnpackFailed",
  "InstallExitCode.38": "ChangeDirFailed",
  "InstallExitCode.AlreadyInProgress": "24",
  "InstallExitCode.ServerDownloadFailed": "25",
  "InstallExitCode.NoDownloaderAvailable": "26",
  "InstallExitCode.NoDownloaderAvailableForStatusCheck": "30",
  "InstallExitCode.UnsupportedArch": "27",
  "InstallExitCode.StatusCheckFailed": "28",
  "InstallExitCode.NeedInsidersArch": "29",
  "InstallExitCode.ServerTransferFailed": "31",
  "InstallExitCode.ServerFailedToStart": "32",
  "InstallExitCode.NeedInsidersWindows": "33",
  "InstallExitCode.CreateInstallDirFailed": "34",
  "InstallExitCode.UnsupportedPlatform": "35",
  "InstallExitCode.ServerTerminatedCVE20201416": "36",
  "InstallExitCode.UnpackFailed": "37",
  "InstallExitCode.ChangeDirFailed": "38",
  "InstallUnpackCode.Success": "success",
  "InstallUnpackCode.Error": "error",
  "InstallUnpackCode.MissingFiles": "missingFiles",
  "uuid": "aae9003cb77b",
  "startMarker": "aae9003cb77b: running",
  "commitId": "38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40",
  "quality": "stable",
  "token": "111aaa1a-1a11-1a1a-a1aa-a1aa11aa1a11",
  "vscodeAgentFolder": "$HOME/.vscode-server",
  "allowClientDownload": "1",
  "forceClientDownload": "1",
  "cliNameInArchive": "code",
  "ignoreWgetConfigFlag": " --no-config ",
  "ignoreCurlConfigFlag": " --disable ",
  "wgetTriesSegment": "--tries=1",
  "listenArgs": "--on-host=127.0.0.1 --on-port",
  "getDownloadServerStartTrigger": "aae9003cb77b:trigger_server_download",
  "getDownloadServerEndTrigger": "aae9003cb77b:trigger_server_download_end",
  "getProgressDownloading": "aae9003cb77b%%1%%",
  "getProgressInstalling": "aae9003cb77b%%2%%"
}
[11:39:37.564] Install and start server if needed
[11:39:37.567] PATH: /home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/me/.local/bin:/home/me/.pyenv/shims:/home/me/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
[11:39:37.567] Checking ssh with "ssh -V"
[11:39:37.574] > OpenSSH_8.9p1 Ubuntu-3ubuntu0.10, OpenSSL 3.0.2 15 Mar 2022

[11:39:37.577] askpass server listening on /run/user/1001/vscode-ssh-askpass-db294ed11f9edb3c85d311513b40b869bcd115ce.sock
[11:39:37.577] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1001/vscode-ssh-askpass-84cfaa2691bb2e848d1569f71650e2c8e38cd9b8.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","32927","-o","ConnectTimeout=180","my-server"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/me/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-3bf5ddfe-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40-0.114.3-es/data.json"}
[11:39:37.577] Local server env: {"SSH_AUTH_SOCK":"/run/user/1001/keyring/ssh","SHELL":"/usr/bin/zsh","DISPLAY":":1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/me/.vscode/extensions/ms-vscode-remote.remote-ssh-0.114.3/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"","VSCODE_SSH_ASKPASS_MAIN":"/home/me/.vscode/extensions/ms-vscode-remote.remote-ssh-0.114.3/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1001/vscode-ssh-askpass-db294ed11f9edb3c85d311513b40b869bcd115ce.sock"}
[11:39:37.581] Spawned 294303
[11:39:37.679] > local-server-1> Running ssh connection command: ssh -v -T -D 32927 -o ConnectTimeout=180 my-server
[11:39:37.682] > local-server-1> Spawned ssh, pid=294311
[11:39:37.685] stderr> OpenSSH_8.9p1 Ubuntu-3ubuntu0.10, OpenSSL 3.0.2 15 Mar 2022
[11:39:37.686] stderr> debug1: Reading configuration data /home/me/.ssh/config
[11:39:37.686] stderr> debug1: /home/me/.ssh/config line 18: Applying options for my-server
[11:39:37.686] stderr> debug1: Reading configuration data /etc/ssh/ssh_config
[11:39:37.686] stderr> debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
[11:39:37.686] stderr> debug1: /etc/ssh/ssh_config line 21: Applying options for *
[11:39:37.686] stderr> debug1: Connecting to 10.23.1.102 [10.23.1.102] port 22.
[11:39:37.734] stderr> debug1: fd 3 clearing O_NONBLOCK
[11:39:37.734] stderr> debug1: Connection established.
[11:39:37.734] stderr> debug1: identity file /home/me/.ssh/my-key.pem type -1
[11:39:37.734] stderr> debug1: identity file /home/me/.ssh/my-key.pem-cert type -1
[11:39:37.734] stderr> debug1: Local version string SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.10
[11:39:37.801] stderr> debug1: Remote protocol version 2.0, remote software version OpenSSH_8.9p1 Ubuntu-3ubuntu0.10
[11:39:37.801] stderr> debug1: compat_banner: match: OpenSSH_8.9p1 Ubuntu-3ubuntu0.10 pat OpenSSH* compat 0x04000000
[11:39:37.801] stderr> debug1: Authenticating to 10.23.1.102:22 as 'me'
[11:39:37.801] stderr> debug1: SSH2_MSG_KEXINIT sent
[11:39:37.845] stderr> debug1: SSH2_MSG_KEXINIT received
[11:39:37.845] stderr> debug1: kex: algorithm: curve25519-sha256
[11:39:37.845] stderr> debug1: kex: host key algorithm: rsa-sha2-512
[11:39:37.845] stderr> debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
[11:39:37.845] stderr> debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
[11:39:37.847] stderr> debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
[11:39:37.944] stderr> debug1: SSH2_MSG_KEX_ECDH_REPLY received
[11:39:37.944] stderr> debug1: Server host key: ssh-rsa SHA256:3BcpV5kbb3U1XXEDIiQgw/MVCznYe2iCkg4IUlqHYNM
[11:39:37.945] stderr> debug1: load_hostkeys: fopen /home/me/.ssh/known_hosts2: No such file or directory
[11:39:37.945] stderr> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
[11:39:37.945] stderr> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
[11:39:37.945] stderr> debug1: Host '10.23.1.102' is known and matches the RSA host key.
[11:39:37.945] stderr> debug1: Found key in /home/me/.ssh/known_hosts:14
[11:39:37.946] stderr> debug1: ssh_packet_send2_wrapped: resetting send seqnr 3
[11:39:37.946] stderr> debug1: rekey out after 134217728 blocks
[11:39:37.946] stderr> debug1: SSH2_MSG_NEWKEYS sent
[11:39:37.946] stderr> debug1: expecting SSH2_MSG_NEWKEYS
[11:39:37.946] stderr> debug1: ssh_packet_read_poll2: resetting read seqnr 3
[11:39:37.946] stderr> debug1: SSH2_MSG_NEWKEYS received
[11:39:37.946] stderr> debug1: rekey in after 134217728 blocks
[11:39:37.951] stderr> debug1: get_agent_identities: bound agent to hostkey
[11:39:37.951] stderr> debug1: get_agent_identities: agent returned 2 keys
[11:39:37.951] stderr> debug1: Will attempt key: xxx RSA SHA256:PzR/39/U/XsahhuHxgxtG+xF/WIx6/c1c1Y0BQrriqc agent
[11:39:37.951] stderr> debug1: Will attempt key: xxx ED25519 SHA256:8J6zQ0DZh9HkDqX0ModsmClrAkRzlmRjhuMlY5nnTQA agent
[11:39:37.951] stderr> debug1: Will attempt key: /home/me/.ssh/my-key.pem  explicit
[11:39:37.951] stderr> debug1: SSH2_MSG_EXT_INFO received
[11:39:37.951] stderr> debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com>
[11:39:37.951] stderr> debug1: kex_input_ext_info: publickey-hostbound@openssh.com=<0>
[11:39:38.070] stderr> debug1: SSH2_MSG_SERVICE_ACCEPT received
[11:39:38.119] stderr> debug1: Authentications that can continue: publickey
[11:39:38.119] stderr> debug1: Next authentication method: publickey
[11:39:38.119] stderr> debug1: Offering public key: xxx RSA SHA256:PzR/39/U/XsahhuHxgxtG+xF/WIx6/c1c1Y0BQrriqc agent
[11:39:38.261] stderr> debug1: Authentications that can continue: publickey
[11:39:38.261] stderr> debug1: Offering public key: xxx ED25519 SHA256:8J6zQ0DZh9HkDqX0ModsmClrAkRzlmRjhuMlY5nnTQA agent
[11:39:38.362] stderr> debug1: Authentications that can continue: publickey
[11:39:38.362] stderr> debug1: Trying private key: /home/me/.ssh/my-key.pem
[11:39:38.417] stderr> Authenticated to 10.23.1.102 ([10.23.1.102]:22) using "publickey".
[11:39:38.417] stderr> debug1: Local connections to LOCALHOST:32927 forwarded to remote address socks:0
[11:39:38.417] stderr> debug1: Local forwarding listening on ::1 port 32927.
[11:39:38.417] stderr> debug1: channel 0: new [port listener]
[11:39:38.417] stderr> debug1: Local forwarding listening on 127.0.0.1 port 32927.
[11:39:38.417] stderr> debug1: channel 1: new [port listener]
[11:39:38.417] stderr> debug1: channel 2: new [client-session]
[11:39:38.417] stderr> debug1: Requesting no-more-sessions@openssh.com
[11:39:38.417] stderr> debug1: Entering interactive session.
[11:39:38.417] stderr> debug1: pledge: filesystem
[11:39:39.399] stderr> debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
[11:39:39.399] stderr> debug1: client_input_hostkeys: searching /home/me/.ssh/known_hosts for 10.23.1.102 / (none)
[11:39:39.400] stderr> debug1: client_input_hostkeys: searching /home/me/.ssh/known_hosts2 for 10.23.1.102 / (none)
[11:39:39.400] stderr> debug1: client_input_hostkeys: hostkeys file /home/me/.ssh/known_hosts2 does not exist
[11:39:39.400] stderr> debug1: client_input_hostkeys: no new or deprecated keys from server
[11:39:39.400] stderr> debug1: Remote: /home/me/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
[11:39:39.486] stderr> debug1: Sending environment.
[11:39:39.486] stderr> debug1: channel 2: setting env LANG = "en_GB.UTF-8"
[11:39:39.533] > Welcome to Ubuntu 22.04.3 LTS (GNU/Linux 6.2.0-1016-aws x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   System information as of Wed Sep 25 10:39:38 UTC 2024
> 
>   System load:                      2.1396484375
>   Usage of /:                       70.3% of 43.43GB
>   Memory usage:                     11%
>   Swap usage:                       0%
>   Processes:                        206
>   Users logged in:                  0
>   IPv4 address for br-a9d7f71f153b: 172.18.0.1
>   IPv4 address for br-af592c932b8e: 172.19.0.1
>   IPv4 address for docker0:         172.17.0.1
>   IPv4 address for ens5:            10.23.1.102
> 
>  * Ubuntu Pro delivers the most comprehensive open source security and
>    compliance features.
> 
>    https://ubuntu.com/aws/pro
> 
> Expanded Security Maintenance for Applications is not enabled.
> 
> 85 updates can be applied immediately.
> To see these additional updates run: apt list --upgradable
> 
> 1 additional security update can be applied with ESM Apps.
> Learn more about enabling ESM Apps service at https://ubuntu.com/esm
> 
> New release '24.04.1 LTS' available.
> Run 'do-release-upgrade' to upgrade to it.
> 
> 
> *** System restart required ***
[11:39:39.576] > ready: aae9003cb77b
[11:39:39.622] > Linux 6.2.0-1016-aws #16~22.04.1-Ubuntu SMP Sun Nov  5 20:08:16 UTC 2023
[11:39:39.622] Platform: linux
[11:39:39.669] > /bin/bash
[11:39:39.670] Parent Shell: bash
[11:39:39.670] Parent Shell pid: 294303
[11:39:40.058] > 314077
> 314077
[11:39:40.058] Waiting for pid of spawned 'sh' subshell: '314077
314077'...
[11:39:40.104] > 314077
> 314077
> 314077
> 314077
> 314077
> 314077
[11:42:39.582] Terminating local server
[11:42:39.585] Resolver error: Error: Connecting with SSH timed out
	at v.Timeout (/home/me/.vscode/extensions/ms-vscode-remote.remote-ssh-0.114.3/out/extension.js:2:501530)
	at Timeout._onTimeout (/home/me/.vscode/extensions/ms-vscode-remote.remote-ssh-0.114.3/out/extension.js:2:560244)
	at listOnTimeout (node:internal/timers:573:17)
	at process.processTimers (node:internal/timers:514:7)
[11:42:39.588] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"1","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Timeout","exitCodeLabel":""},"measures":{"resolveAttempts":1,"isExecServer":0,"timing.totalResolveTime":182048,"timing.preSshTime":41}}
[11:42:39.592] ------




[11:42:39.595] Local server exit: 15
```

**Comment by joshspicer** [comment]
We fixed an issue that could have caused this kind of behavior.  IF you're still able to repro, please feel free to reopen (and please provide new logs). Thank you and apologies for the delay
