### ISSUE TITLE
mount dir 

### ISSUE THREAD

**Issue by AlaricWeb** [microsoft/vscode-remote-release#10281]
Type: <b>Bug</b>

For bug reports please include the complete log output. (In the VS Code window: `F1` > `Dev Containers: Show Container Log`.)

Extension version: 0.384.0
VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.19045
Modes: Unsupported
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 4650G with Radeon Graphics (12 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.39GB (6.66GB free)|
|Process Argv|--crash-reporter-id 820b86c7-4d37-4734-947f-4af64b2753b3|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-24.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 PRO 4650G with Radeon Graphics (8 x 0)|
|Memory (System)|7.76GB (6.53GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
ei213698:31121563
iacca2:31138163
cc771715:31140165

```

</details>

**Comment by AlaricWeb** [comment]
![image](https://github.com/user-attachments/assets/94477fb1-e3c3-4dd3-a5d1-04cea3c49f59)
 Can't it be bound like this?

**Comment by AlaricWeb** [comment]
[2024-09-17T22:38:16.248Z] Dev Containers 0.384.0 in VS Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3).
[2024-09-17T22:38:16.248Z] Start: Run: wsl -d Ubuntu-24.04 -e wslpath -u \\wsl.localhost\Ubuntu-24.04\workspace\lottery-admin
[2024-09-17T22:38:16.359Z] Stop (111 ms): Run: wsl -d Ubuntu-24.04 -e wslpath -u \\wsl.localhost\Ubuntu-24.04\workspace\lottery-admin
[2024-09-17T22:38:16.363Z] Start: Resolving Remote
[2024-09-17T22:38:16.366Z] Start: Run: wsl -d Ubuntu-24.04 -e wslpath -u \\wsl.localhost\Ubuntu-24.04\workspace\lottery-admin
[2024-09-17T22:38:16.470Z] Stop (104 ms): Run: wsl -d Ubuntu-24.04 -e wslpath -u \\wsl.localhost\Ubuntu-24.04\workspace\lottery-admin
[2024-09-17T22:38:16.475Z] Start: Run: wsl -d Ubuntu-24.04 -e /bin/sh -c cd '/workspace/lottery-admin' && /bin/sh
[2024-09-17T22:38:16.479Z] Start: Run in host: id -un
[2024-09-17T22:38:16.531Z] root
[2024-09-17T22:38:16.531Z] 
[2024-09-17T22:38:16.531Z] Stop (52 ms): Run in host: id -un
[2024-09-17T22:38:16.531Z] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true)
[2024-09-17T22:38:16.533Z] Stop (2 ms): Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true)
[2024-09-17T22:38:16.534Z] Start: Run in host: echo ~
[2024-09-17T22:38:16.535Z] /root
[2024-09-17T22:38:16.535Z] 
[2024-09-17T22:38:16.535Z] Stop (1 ms): Run in host: echo ~
[2024-09-17T22:38:16.535Z] Start: Run in host: test -f '/root/.vscode-server/cli/servers/Stable-4849ca9bdf9666755eb463db297b69e5385090e3/server/node'
[2024-09-17T22:38:16.536Z] 
[2024-09-17T22:38:16.536Z] 
[2024-09-17T22:38:16.536Z] Exit code 1
[2024-09-17T22:38:16.537Z] Stop (2 ms): Run in host: test -f '/root/.vscode-server/cli/servers/Stable-4849ca9bdf9666755eb463db297b69e5385090e3/server/node'
[2024-09-17T22:38:16.537Z] Start: Run in host: test -f '/root/.vscode/cli/servers/Stable-4849ca9bdf9666755eb463db297b69e5385090e3/server/node'
[2024-09-17T22:38:16.538Z] 
[2024-09-17T22:38:16.538Z] 
[2024-09-17T22:38:16.538Z] Exit code 1
[2024-09-17T22:38:16.538Z] Stop (1 ms): Run in host: test -f '/root/.vscode/cli/servers/Stable-4849ca9bdf9666755eb463db297b69e5385090e3/server/node'
[2024-09-17T22:38:16.538Z] Start: Run in host: test -f '/root/.vscode-server/bin/4849ca9bdf9666755eb463db297b69e5385090e3/node'
[2024-09-17T22:38:16.539Z] 
[2024-09-17T22:38:16.539Z] 
[2024-09-17T22:38:16.539Z] Stop (1 ms): Run in host: test -f '/root/.vscode-server/bin/4849ca9bdf9666755eb463db297b69e5385090e3/node'
[2024-09-17T22:38:16.540Z] Start: Run in host: test -f '/root/.vscode-server/bin/4849ca9bdf9666755eb463db297b69e5385090e3/node_modules/node-pty/package.json'
[2024-09-17T22:38:16.541Z] 
[2024-09-17T22:38:16.541Z] 
[2024-09-17T22:38:16.541Z] Stop (1 ms): Run in host: test -f '/root/.vscode-server/bin/4849ca9bdf9666755eb463db297b69e5385090e3/node_modules/node-pty/package.json'
[2024-09-17T22:38:16.541Z] Start: Run in host: test -f '/root/.vscode-remote-containers/dist/vscode-remote-containers-server-0.384.0.js'
[2024-09-17T22:38:16.542Z] 
[2024-09-17T22:38:16.542Z] 
[2024-09-17T22:38:16.542Z] Stop (1 ms): Run in host: test -f '/root/.vscode-remote-containers/dist/vscode-remote-containers-server-0.384.0.js'
[2024-09-17T22:38:16.543Z] userEnvProbe: loginInteractiveShell (default)
[2024-09-17T22:38:16.543Z] userEnvProbe: not found in cache
[2024-09-17T22:38:16.543Z] userEnvProbe shell: zsh
[2024-09-17T22:38:16.543Z] Start: Run in Host: zsh -lic echo -n bec227df-fcbe-4fb2-831b-c1f056caeff2; cat /proc/self/environ; echo -n bec227df-fcbe-4fb2-831b-c1f056caeff2
[2024-09-17T22:38:16.729Z] Stop (186 ms): Run in Host: zsh -lic echo -n bec227df-fcbe-4fb2-831b-c1f056caeff2; cat /proc/self/environ; echo -n bec227df-fcbe-4fb2-831b-c1f056caeff2
[2024-09-17T22:38:16.729Z] bec227df-fcbe-4fb2-831b-c1f056caeff2USER=root

**Comment by AlaricWeb** [comment]
1 warning found (use docker --debug to expand):
 - InvalidDefaultArgInFrom: Default value for ARG $BASE_IMAGE results in empty or invalid base image name (line 2)
[1478 ms] Stop (450 ms): Run: docker build -f /tmp/devcontainercli-root/updateUID.Dockerfile-0.69.0 -t vsc-lottery-admin-5c0be808cbf8851b6c22d0e1da90d142e90e3cd80d3c9284825c366f953e7b47-uid --platform linux/amd64 --build-arg BASE_IMAGE=mcr.microsoft.com/devcontainers/base:jammy --build-arg REMOTE_USER=vscode --build-arg NEW_UID=0 --build-arg NEW_GID=0 --build-arg IMAGE_USER=root /tmp/devcontainercli-root/empty-folder
[1478 ms] Start: Run: docker events --format {{json .}} --filter event=start
[1481 ms] Start: Starting container
[1481 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/workspace/lottery-admin,target=/workspaces/lottery-admin --mount type=volume,src=~/.oh-my-zsh/custom/plugins,dst=~/.oh-my-zsh/custom/plugins --mount type=bind,src=~/.zshrc,dst=~/.zshrc --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=\\wsl.localhost\Ubuntu-24.04\workspace\lottery-admin -l devcontainer.config_file=/workspace/lottery-admin/.devcontainer/devcontainer.json --entrypoint /bin/sh -l devcontainer.metadata=[{"id":"ghcr.io/devcontainers/features/common-utils:2"},{"id":"ghcr.io/devcontainers/features/git:1"},{"remoteUser":"vscode"},{"mounts":[{"target":"~/.oh-my-zsh/custom/plugins","source":"~/.oh-my-zsh/custom/plugins","type":"volume"},{"target":"~/.zshrc","source":"~/.zshrc","type":"bind"}],"forwardPorts":[80,5173]}] vsc-lottery-admin-5c0be808cbf8851b6c22d0e1da90d142e90e3cd80d3c9284825c366f953e7b47-uid -c echo Container started
docker: Error response from daemon: ~/.zshrc is not an absolute path.
See 'docker run --help'.
[1509 ms] Stop (28 ms): Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/workspace/lottery-admin,target=/workspaces/lottery-admin --mount type=volume,src=~/.oh-my-zsh/custom/plugins,dst=~/.oh-my-zsh/custom/plugins --mount type=bind,src=~/.zshrc,dst=~/.zshrc --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=\\wsl.localhost\Ubuntu-24.04\workspace\lottery-admin -l devcontainer.config_file=/workspace/lottery-admin/.devcontainer/devcontainer.json --entrypoint /bin/sh -l devcontainer.metadata=[{"id":"ghcr.io/devcontainers/features/common-utils:2"},{"id":"ghcr.io/devcontainers/features/git:1"},{"remoteUser":"vscode"},{"mounts":[{"target":"~/.oh-my-zsh/custom/plugins","source":"~/.oh-my-zsh/custom/plugins","type":"volume"},{"target":"~/.zshrc","source":"~/.zshrc","type":"bind"}],"forwardPorts":[80,5173]}] vsc-lottery-admin-5c0be808cbf8851b6c22d0e1da90d142e90e3cd80d3c9284825c366f953e7b47-uid -c echo Container started
[1509 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=\\wsl.localhost\Ubuntu-24.04\workspace\lottery-admin --filter label=devcontainer.config_file=/workspace/lottery-admin/.devcontainer/devcontainer.json
[1513 ms] Stop (35 ms): Run: docker events --format {{json .}} --filter event=start
[1538 ms] Stop (29 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=\\wsl.localhost\Ubuntu-24.04\workspace\lottery-admin --filter label=devcontainer.config_file=/workspace/lottery-admin/.devcontainer/devcontainer.json
[1541 ms] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/workspace/lottery-admin,target=/workspaces/lottery-admin --mount type=volume,src=~/.oh-my-zsh/custom/plugins,dst=~/.oh-my-zsh/custom/plugins --mount type=bind,src=~/.zshrc,dst=~/.zshrc --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=\\wsl.localhost\Ubuntu-24.04\workspace\lottery-admin -l devcontainer.config_file=/workspace/lottery-admin/.devcontainer/devcontainer.json --entrypoint /bin/sh -l devcontainer.metadata=[{"id":"ghcr.io/devcontainers/features/common-utils:2"},{"id":"ghcr.io/devcontainers/features/git:1"},{"remoteUser":"vscode"},{"mounts":[{"target":"~/.oh-my-zsh/custom/plugins","source":"~/.oh-my-zsh/custom/plugins","type":"volume"},{"target":"~/.zshrc","source":"~/.zshrc","type":"bind"}],"forwardPorts":[80,5173]}] vsc-lottery-admin-5c0be808cbf8851b6c22d0e1da90d142e90e3cd80d3c9284825c366f953e7b47-uid -c echo Container started
[1542 ms] trap "exit 0" 15
[1542 ms] exec "$@"
[1542 ms] while sleep 1 & wait $!; do :; done -
[1542 ms]     at wtA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.384.0/dist/spec-node/devContainersSpecCLI.js:465:1260)
[1543 ms]     at NH (/root/.vscode-remote-containers/dist/dev-containers-cli-0.384.0/dist/spec-node/devContainersSpecCLI.js:465:1002)
[1543 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1543 ms]     at async YtA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.384.0/dist/spec-node/devContainersSpecCLI.js:482:3771)
[1543 ms]     at async eB (/root/.vscode-remote-containers/dist/dev-containers-cli-0.384.0/dist/spec-node/devContainersSpecCLI.js:482:4886)
[1543 ms]     at async prA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.384.0/dist/spec-node/devContainersSpecCLI.js:663:200)
[1543 ms]     at async drA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.384.0/dist/spec-node/devContainersSpecCLI.js:662:14706)
[1550 ms] Stop (865 ms): Run in Host: /root/.vscode-server/bin/4849ca9bdf9666755eb463db297b69e5385090e3/node /root/.vscode-remote-containers/dist/dev-containers-cli-0.384.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-1299d4e8-99c8-4c97-931e-bbdb7495e1c81726612957128 --workspace-folder /workspace/lottery-admin --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\Ubuntu-24.04\workspace\lottery-admin --id-label devcontainer.config_file=/workspace/lottery-admin/.devcontainer/devcontainer.json --log-level trace --log-format json --config /workspace/lottery-admin/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --experimental-lockfile --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[1551 ms] Exit code 1
[1554 ms] Command failed: /root/.vscode-server/bin/4849ca9bdf9666755eb463db297b69e5385090e3/node /root/.vscode-remote-containers/dist/dev-containers-cli-0.384.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-1299d4e8-99c8-4c97-931e-bbdb7495e1c81726612957128 --workspace-folder /workspace/lottery-admin --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\Ubuntu-24.04\workspace\lottery-admin --id-label devcontainer.config_file=/workspace/lottery-admin/.devcontainer/devcontainer.json --log-level trace --log-format json --config /workspace/lottery-admin/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --experimental-lockfile --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[1554 ms] Exit code 1
