### ISSUE TITLE
Raspbian 8 fails to connect due to C++ missing lib, but Debian 8 x86 does not fail and is missing same lib

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#1030]
Tried with VS Code Insiders and the nightly and non-nightly SSH extensions. This is similar to #103, but may be a different problem, so logging separately.

Raspbian 8/Jessie is based on Debian 8/Jessie. Debian 8 works well with Remote - SSH. However, trying Raspbian 8, I get the dreaded #103 "Unauthorized Connection Refused" error.  After starting `server.sh` by hand on the Pi, I saw a variation of this error from #103 at startup time, but it’s `spdlog` failure about `CXXABI_1.3.9` rather than Node.js and the server actually does start which obscured it.

The error is accurate, but what is weird is that `CXXABI_1.3.9` **isn’t available on Deiban 8 either**, but everything works.  I have no explanation for that part.

Running `strings` on `libstdc++.so.6` on both Debian 8 and Raspbian 8 gives me:
```
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_1.3.8
```

The machine also meets the minimum requirements for libstdc++ and glibc. Could there be something about the `spdlog` build for ARM that is causing this like using a more recent version of gcc than the x86 version?

In either event, it would have saved me time if I could have seen this error in VS Code since the server was up and responding.  I was assuming it was something with my end or my Pi 3.

Specific error:

```
{ errorCode: 'load', 
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ],
  detail:
   Error: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CXXABI_1.3.9' not 
found (required by /home/pi/.vscode-server-insiders/bin/e1d3dd53d17fb1529a002e4d6fb066db0a0bd385/node_modules/spdlog/build/Release/spdlog.node)
       at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18) 
       at Module.load (internal/modules/cjs/loader.js:599:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
       at Function.Module._load (internal/modules/cjs/loader.js:530:3)
       at Module.require (internal/modules/cjs/loader.js:637:17)
       at Module.patchedRequire [as require] (/home/pi/.vscode-server-insiders/bin/e1d3dd53d17fb1529a002e4d6fb066db0a0bd385/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
       at require (internal/modules/cjs/helpers.js:20:18)
       at bindings (/home/pi/.vscode-server-insiders/bin/e1d3dd53d17fb1529a002e4d6fb066db0a0bd385/node_modules/bindings/bindings.js:112:48)
       at Object.<anonymous> (/home/pi/.vscode-server-insiders/bin/e1d3dd53d17fb1529a002e4d6fb066db0a0bd385/node_modules/spdlog/index.js:3:35)
       at Module._compile (internal/modules/cjs/loader.js:689:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)   
       at Module.load (internal/modules/cjs/loader.js:599:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
       at Function.Module._load (internal/modules/cjs/loader.js:530:3)
       at Module.require (internal/modules/cjs/loader.js:637:17)
       at Module.patchedRequire [as require] (/home/pi/.vscode-server-insiders/bin/e1d3dd53d17fb1529a002e4d6fb066db0a0bd385/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
       at require (internal/modules/cjs/helpers.js:20:18)
       at t.load (/home/pi/.vscode-server-insiders/bin/e1d3dd53d17fb1529a002e4d6fb066db0a0bd385/out/vs/loader.js:16:247)
       at e.load (/home/pi/.vscode-server-insiders/bin/e1d3dd53d17fb1529a002e4d6fb066db0a0bd385/out/vs/loader.js:13:587)
       at i (/home/pi/.vscode-server-insiders/bin/e1d3dd53d17fb1529a002e4d6fb066db0a0bd385/out/vs/loader.js:28:371)
       at Object.errorback (/home/pi/.vscode-server-insiders/bin/e1d3dd53d17fb1529a002e4d6fb066db0a0bd385/out/vs/loader.js:28:492)
       at e.triggerErrorback (/home/pi/.vscode-server-insiders/bin/e1d3dd53d17fb1529a002e4d6fb066db0a0bd385/out/vs/loader.js:13:952)
       at /home/pi/.vscode-server-insiders/bin/e1d3dd53d17fb1529a002e4d6fb066db0a0bd385/out/vs/loader.js:13:657
       at ReadFileContext.callback (/home/pi/.vscode-server-insiders/bin/e1d3dd53d17fb1529a002e4d6fb066db0a0bd385/out/vs/loader.js:16:617)
       at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13) }
[createInstance] extensionManagementService depends on storageService which is NOT registered.
```

Full log on client side:
```
[14:05:24.760] remote-ssh-nightly@2019.7.31140
[14:05:24.760] win32 x64
[14:05:24.761] SSH Resolver called for "ssh-remote+retropi3", attempt 1
[14:05:24.762] SSH Resolver called for host: retropi3
[14:05:24.762] Setting up SSH remote "retropi3"
[14:05:24.765] Using commit id "188180bccf1f56b3368c4eb20e877238d69925b8" and quality "insider" for server
[14:05:24.771] Testing ssh with ssh -V
[14:05:24.835] ssh exited with code: 0
[14:05:24.835] Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[14:05:24.836] Running script with connection command: ssh -o ClearAllForwardings=true retropi3 bash
[14:05:24.838] Install and start server if needed
[14:05:24.901] > 
[14:05:24.901] Got some output, clearing connection timeout
[14:05:25.400] > ]0;C:\WINDOWS\SYSTEM32\cmd.exe
[14:05:25.414] > 
> 
...
> 
[14:05:25.423] > 
> 
...
> 
[14:05:25.619] > pi@192.168.1.106's password: 
[14:05:29.078] "install" wrote data to terminal: "*********"
[14:05:29.083] > 
> 
[14:05:29.309] > Running remote connection script
> 
[14:05:29.327] > Acquiring lock on /home/pi/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20
> e877238d69925b8/vscode-remote-lock.188180bccf1f56b3368c4eb20e877238d69925b8     
> 
[14:05:29.349] > Installing to /home/pi/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877
> 238d69925b8...
> 
[14:05:29.370] > Downloading with wget
> 
[14:05:33.510] > Download complete
> 
[14:05:56.027] > XDG_SESSION_ID=c12
> SHELL=/bin/bash
> SSH_CLIENT=192.168.1.105 4518 22
> USER=pi
> VSCODE_AGENT_FOLDER=/home/pi/.vscode-server-insiders
> PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
> MAIL=/var/mail/pi
> PWD=/home/pi
> LANG=en_US.UTF-8
> HOME=/home/pi
> SHLVL=2
> LOGNAME=pi
> SSH_CONNECTION=192.168.1.105 4518 192.168.1.106 22
> XDG_RUNTIME_DIR=/run/user/1000
> _=/usr/bin/printenv
> OLDPWD=/home/pi/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d699
[14:05:56.028] > 
> 25b8
[14:05:56.031] > 
> 
[14:05:56.033] > Starting server...
[14:05:56.037] > 
> 
[14:05:56.045] > Waiting for server log...
[14:05:56.046] > 
> 
[14:05:56.568] > Waiting for server log...
[14:05:56.568] > 
> 
[14:05:57.090] > Waiting for server log...
[14:05:57.091] > 
> 
[14:05:57.613] > Waiting for server log...
[14:05:57.614] > 
> 
[14:05:58.134] > 
> 
[14:05:58.135] > *
[14:05:58.136] > 
> * Reminder: You may only use this software with Visual Studio family products,  
[14:05:58.137] > 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
[14:05:58.140] > 
> *
[14:05:58.141] > 
> 
[14:05:58.145] > 
> 
[14:05:58.188] > ecbc1782-643c-4f6d-a6f2-d98d18927ef0==44953==40535==
[14:05:58.189] Received install output: ecbc1782-643c-4f6d-a6f2-d98d18927ef0==44953==40535==
[14:05:58.189] Remote server is listening on port 44953
[14:05:58.196] > 
> 
[14:05:58.684] "install" terminal command done
[14:06:00.197] Running script with connection command: ssh -L 127.0.0.1:44765:127.0.0.1:44953 retropi3 bash
[14:06:00.199] Spawning tunnel with: type "C:\Users\clantz\AppData\Local\Temp\vscode-linux-multi-line-command-retropi3-234817033.sh" | ssh -L 127.0.0.1:44765:127.0.0.1:44953 retropi3 bash
[14:06:00.261] > 
[14:06:00.739] > ]0;C:\WINDOWS\SYSTEM32\cmd.exe
[14:06:00.758] > 
> 
...
> 
[14:06:00.767] > 
> 
...
> 
[14:06:00.982] > pi@192.168.1.106's password: 
[14:06:04.711] "SSH Tunnel" wrote data to terminal: "*********"
[14:06:04.721] > 
> 
[14:06:04.970] > Connected to SSH Host - Please do not close this terminal
> 
[14:06:04.971] Spawned SSH tunnel between local port 44765 and remote port 44953
[14:06:04.971] Waiting for ssh tunnel to be ready
[14:06:04.974] Tunneled remote port 44953 to local port 44765
[14:06:04.975] Resolved "ssh-remote+retropi3" to "127.0.0.1:44765"
[14:06:04.976] ------
```

Full log from running server.sh manually:
```


*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


{ errorCode: 'load',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ],
  detail:
   Error: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/pi/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/node_modules/spdlog/build/Release/spdlog.node)
       at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
       at Module.load (internal/modules/cjs/loader.js:599:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
       at Function.Module._load (internal/modules/cjs/loader.js:530:3)
       at Module.require (internal/modules/cjs/loader.js:637:17)
       at Module.patchedRequire [as require] (/home/pi/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
       at require (internal/modules/cjs/helpers.js:20:18)
       at bindings (/home/pi/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/node_modules/bindings/bindings.js:112:48)
       at Object.<anonymous> (/home/pi/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/node_modules/spdlog/index.js:3:35)
       at Module._compile (internal/modules/cjs/loader.js:689:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
       at Module.load (internal/modules/cjs/loader.js:599:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
       at Function.Module._load (internal/modules/cjs/loader.js:530:3)
       at Module.require (internal/modules/cjs/loader.js:637:17)
       at Module.patchedRequire [as require] (/home/pi/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
       at require (internal/modules/cjs/helpers.js:20:18)
       at t.load (/home/pi/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/out/vs/loader.js:16:247)
       at e.load (/home/pi/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/out/vs/loader.js:13:587)
       at i (/home/pi/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/out/vs/loader.js:28:371)
       at Object.errorback (/home/pi/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/out/vs/loader.js:28:492)
       at e.triggerErrorback (/home/pi/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/out/vs/loader.js:13:952)
       at /home/pi/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/out/vs/loader.js:13:657
       at ReadFileContext.callback (/home/pi/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/out/vs/loader.js:16:617)
       at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13) }
IP Address: 192.168.1.106
webview server listening on 8001
Extension host agent listening on 8000
```

**Comment by martinbradburn** [comment]
So is there no fix for Jessie Raspbian 8?

**Comment by Chuxel** [comment]
@martinbradburn Jesse doesn't have `CXXABI_1.3.9` (Stretch does). So other than manually updating libstdc++ by building it by hand, the distro doesn't have it.  The question is why ARM needs it but x86 does not.  That requires investigation to understand.

**Comment by creinarz** [comment]
Hi Chuxcel,

I am having the same problem! Did you find a solution?

Thanks,
Chris

**Comment by beduffy** [comment]
I'm having the same problem as well.

**Comment by chris400** [comment]
Debian 8 / Buster's mainstream support ended 2018, LTS will end in June. My guess: MS won't fix this issue. Resources are rare, so they might be better used elsewhere. I fully understand that.

**Comment by crab2313** [comment]
Same issue with Centos 7.5

**Comment by Chuxel** [comment]
Given Jessie is EOL, I'm closing this particuar issue.
