### ISSUE TITLE
"Reopen in Container" does not work

### ISSUE THREAD

**Issue by jangtze** [microsoft/vscode-remote-release#10302]
Hi, 

I have had troubles with the remote / dev-container extension after an update today (that I only did to get [this feature](https://github.com/microsoft/vscode/issues/20958)). Big mistake, since I am getting basically [this now](https://github.com/microsoft/vscode-remote-release/issues/9089) and I would have needed it to work for a meeting tomorrow, but it is what it is.

Unfortunately I forgot which versions I was running before and can not reproduce a working setup anymore. I am convinced that these kind of things are being tested in CD/CI so something might have fundamentally changed, which broke my workflow/setup. Please help.

### Attempts
Googling and asking ChatGPT did not yield any solution. In brevity it suggested (and I tried to my best knowledge):
- updating the extension ( `v0.384.0`)
- downgrading the extension ( `v0.380.0` and `v0.315.0`)
- delete workspace cache ( there was no `.vscode` folder in the project path but later I got info to delete `/Users/user/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers`
- check whether Docker runs smoothly (it did before and does after, docker compose up with the settings did work without any problem and even attaching to that container, however not with the workspace)
- check logs (it couldn't help me from the info below)
- `docker volume prune`
- `Remote-Containers: Rebuild Without Cache`
- reinstall the extension / vscode completely
- `"workspaceMount": "source=${localWorkspaceFolder},target=/home/jovyan/work,type=bind"`
 (apparently hallucination)
- reset the extension (which might be an hallucination too, as I couldn't find any described link or button)
- change ports

My details I described below.

### Versions
<details>
  <summary>VSCode Version:</summary>

```
Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin x64 21.6.0
```
</details>

<details>
  <summary>Docker Desktop:</summary>

```
Version 4.34.2 (167172)
Engine: 27.2.0
Compose: v2.29.2-desktop.2
```
</details>

- Local OS Version: macOS Monterey 12.6 (21G115)
- Remote OS Version: `jupyter/scipy-notebook` (plus some installed tools)
- Remote Extension/Connection Type: Containers

- Logs: see below

### Steps to Reproduce:

1. use `.devcontainer` as specified in the definition below
2. use command palette "Reopen in Container"

### Development Environment

<details>
  <summary> Folder SetUp </summary>

```
|-- .devcontainer
|      |-- devcontainer.json
|      `-- docker-compose.yml 
|-- datasets
|      `-- ...
|-- modules
|      `-- ...
`-- work
       `-- ...
```

</details>

<details>
  <summary><code>devcontainer.json</code></summary>

```json
{
	"name": "SomeName",
	"dockerComposeFile": "./docker-compose.yml",
	// "workspaceMount": "source=${localWorkspaceFolder}/work,target=/home/jovyan/work,type=bind", // wrong suggestion by ChatGPT
	"service": "my_service",
	"workspaceFolder": "/home/jovyan/work",
	"shutdownAction": "stopCompose",
	"customizations": {
		"vscode": {
			"settings": { 
				"terminal.integrated.shell.linux": "/bin/bash"
			},
			"extensions": [
				"ms-python.python",
				"ms-python.debugpy",
				"ms-python.vscode-pylance",
				"ms-toolsai.jupyter",
				"visualstudioexptteam.vscodeintellicode",
                // ... and others
			]
		}
	},
	"containerEnv": {
		"PATH": "${containerEnv:PATH}:/home/jovyan/work/path/headers"
	}
}
```
</details>

<details>
  <summary><code>docker-compose.yml</code></summary>

```yml
services:
  my_service:
    image:   my_image_derived_from_jupyter_scipy
    volumes:
      - ../work:/home/jovyan/work:cached
      - ../datasets:/home/jovyan/datasets:ro
      - ../modules/.local:/home/jovyan/.local
    ports:
      - 8890:8888 # host : container
    container_name:   my_container
    command: "start-notebook.sh \
              --ServerApp.password='' \
              --ServerApp.token='1234' \
              "
```
</details>

###  Output / Logs / Info
<details>
  <summary>Error Message</summary>
  
Small Pop-Up: "An error occurred setting up the container."

Sometimes showing this in the editor area:
```
The editor could not be opened due to an unexpected error: ENOPRO: No file system provider found for resource 'vscode-remote://dev-container%2B7b22686f737450617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655…8652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d/home/jovyan/work/path/code.py'
```
</details>

<details>
  <summary>Terminal Output</summary>

 Anonymized  

```sh
[...]

[2880 ms] Writing docker-compose.devcontainer.containerFeatures-1727029587166-957cf938-c6f1-4ae9-b557-4bbd1df392ca.yml to /Users/user/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose
[2881 ms] Start: Run: docker compose --project-name code_work_devcontainer -f /Users/user/path/code_work/.devcontainer/docker-compose.yml -f /Users/user/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1727029587166-957cf938-c6f1-4ae9-b557-4bbd1df392ca.yml up -d
invalid interpolation format for services.ess.environment.[].
You may need to escape any $ with another $.
PATH=${containerEnv:PATH}:/home/jovyan/work/project/headers
[2994 ms] Error: Command failed: docker compose --project-name code_work_devcontainer -f /Users/user/path/code_work/.devcontainer/docker-compose.yml -f /Users/user/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1727029587166-957cf938-c6f1-4ae9-b557-4bbd1df392ca.yml up -d
[2995 ms]     at ltA (/Users/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js:430:3355)
[2995 ms]     at async ctA (/Users/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js:410:3506)
[2995 ms]     at async YtA (/Users/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js:482:3944)
[2995 ms]     at async eB (/Users/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js:482:4886)
[2995 ms]     at async prA (/Users/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js:663:200)
[2995 ms]     at async drA (/Users/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js:662:14706)
[3005 ms] Exit code 1
[3008 ms] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/user/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-689bcb54-7d4b-4674-9a5a-6998bd75bda31727029581835 --workspace-folder /Users/user/path/code_work --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/user/path/code_work --id-label devcontainer.config_file=/Users/user/path/code_work/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/user/path/code_work/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[3008 ms] Exit code 1

```

</details>

<details>
 <summary>Dev Tools Console </summary>

```
ERR [LocalProcess0][resolveAuthority(dev-container,1)][7768ms] returned an error {code: 'NotAvailable', detail: true}
log.ts:439   ERR resolveAuthority(dev-container) returned an error after 7772 ms CodeExpectedError
    at _.qb (abstractExtensionService.ts:661:9)
    at async _.pb (abstractExtensionService.ts:622:19)
    at async _.Nb (nativeExtensionService.ts:363:22)
    at async _.ib (abstractExtensionService.ts:452:31)
nativeExtensionService.ts:369 Error handled: Not showing a notification for the error
log.ts:439   ERR Error received from starting extension host (kind: Remote)
log.ts:439   ERR CodeExpectedError
    at _.qb (abstractExtensionService.ts:661:9)
    at async _.pb (abstractExtensionService.ts:622:19)
    at async _.Nb (nativeExtensionService.ts:363:22)
    at async _.ib (abstractExtensionService.ts:452:31)
log.ts:439   ERR [remote-connection][attempt 1] An error occurred in initial connection! Will retry... Error:
log.ts:439   ERR CodeExpectedError
    at _.qb (abstractExtensionService.ts:661:9)
    at async _.pb (abstractExtensionService.ts:622:19)
    at async _.Nb (nativeExtensionService.ts:363:22)
    at async _.ib (abstractExtensionService.ts:452:31)
log.ts:439   ERR [remote-connection][attempt 2] An error occurred in initial connection! Will retry... Error:
log.ts:439   ERR CodeExpectedError
    at _.qb (abstractExtensionService.ts:661:9)
    at async _.pb (abstractExtensionService.ts:622:19)
    at async _.Nb (nativeExtensionService.ts:363:22)
    at async _.ib (abstractExtensionService.ts:452:31)
log.ts:439   ERR [remote-connection][attempt 3] An error occurred in initial connection! Will retry... Error:
log.ts:439   ERR CodeExpectedError
    at _.qb (abstractExtensionService.ts:661:9)
    at async _.pb (abstractExtensionService.ts:622:19)
    at async _.Nb (nativeExtensionService.ts:363:22)
    at async _.ib (abstractExtensionService.ts:452:31)
log.ts:439   ERR [remote-connection][attempt 4] An error occurred in initial connection! Will retry... Error:
log.ts:439   ERR CodeExpectedError
    at _.qb (abstractExtensionService.ts:661:9)
    at async _.pb (abstractExtensionService.ts:622:19)
    at async _.Nb (nativeExtensionService.ts:363:22)
    at async _.ib (abstractExtensionService.ts:452:31)
log.ts:439   ERR [remote-connection][attempt 5]  An error occurred in initial connection! It will be treated as a permanent error. Error:
log.ts:439   ERR CodeExpectedError
    at _.qb (abstractExtensionService.ts:661:9)
    at async _.pb (abstractExtensionService.ts:622:19)
    at async _.Nb (nativeExtensionService.ts:363:22)
    at async _.ib (abstractExtensionService.ts:452:31)
log.ts:439   ERR CodeExpectedError
    at _.qb (abstractExtensionService.ts:661:9)
    at async _.pb (abstractExtensionService.ts:622:19)
    at async _.Nb (nativeExtensionService.ts:363:22)
    at async _.ib (abstractExtensionService.ts:452:31)
log.ts:439   ERR Cannot register remote filesystem provider. Error while fetching remote environment. CodeExpectedError
5log.ts:439   ERR CodeExpectedError
    at _.qb (abstractExtensionService.ts:661:9)
    at async _.pb (abstractExtensionService.ts:622:19)
    at async _.Nb (nativeExtensionService.ts:363:22)
    at async _.ib (abstractExtensionService.ts:452:31)
log.ts:439   ERR CodeExpectedError
    at _.qb (abstractExtensionService.ts:661:9)
    at async _.pb (abstractExtensionService.ts:622:19)
    at async _.Nb (nativeExtensionService.ts:363:22)
    at async _.ib (abstractExtensionService.ts:452:31)
log.ts:429  WARN Ignoring the error while validating workspace folder vscode-remote://dev-container%2B7b22686f737450617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d/home/jovyan/work - ENOPRO: No file system provider found for resource 'vscode-remote://dev-container%2B7b22686f737450617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d/home/jovyan/work'
log.ts:439   ERR CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://dev-container%2B7b22686f737450617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d/home/jovyan/work'
    at r.j (fileService.ts:150:18)
    at async r.bb (fileService.ts:1175:20)
    at async fileService.ts:1141:24
log.ts:439   ERR CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://dev-container%2B7b22686f737450617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d/home/jovyan/work/.vscode/extensions'
    at r.j (fileService.ts:150:18)
    at async r.bb (fileService.ts:1175:20)
    at async fileService.ts:1141:24
log.ts:439   ERR An unknown error occurred. Please consult the log for more details.: CodeExpectedError
    at _.qb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3262:27376)
    at async _.pb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3262:26632)
    at async _.Nb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3264:3923)
    at async _.ib (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3262:24007)
log.ts:439   ERR ENOPRO: No file system provider found for resource 'vscode-remote://dev-container%2B7b22686f737450617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d/home/jovyan/work': CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://dev-container%2B7b22686f737450617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d/home/jovyan/work'
    at r.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:673:13815)
    at async r.s (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:673:14646)
    at async r.resolve (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:673:14436)
    at async d.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1916:52398)
log.ts:439   ERR ENOPRO: No file system provider found for resource 'vscode-remote://dev-container%2B7b22686f737450617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d/home/jovyan/work/.vscode': CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://dev-container%2B7b22686f737450617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d/home/jovyan/work/.vscode'
    at r.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:673:13815)
    at async r.exists (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:673:16100)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2137:6511
    at async Promise.all (index 0)
    at async A.v (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2137:6687)
log.ts:439   ERR CodeExpectedError
    at _.qb (abstractExtensionService.ts:661:9)
    at async _.pb (abstractExtensionService.ts:622:19)
    at async _.Nb (nativeExtensionService.ts:363:22)
    at async _.ib (abstractExtensionService.ts:452:31)
log.ts:439   ERR An unknown error occurred. Please consult the log for more details.: CodeExpectedError
    at _.qb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3262:27376)
    at async _.pb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3262:26632)
    at async _.Nb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3264:3923)
    at async _.ib (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3262:24007)
log.ts:439   ERR [Extension Host] Unhandled Error: CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://dev-container%2B7b22686f737450617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d/home/jovyan/work'
    at r.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:673:13815)
    at async r.exists (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:673:16100)
    at async Promise.all (index 0)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1864:3061
console.ts:137 [Extension Host] Unhandled Error: CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://dev-container%2B7b22686f737450617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f7a747a6d6a6e2f446f63756d656e74732f5374756469756d2f4d617468652f6d61737465725f62617972657574682f5072616b74696b756d5f4553532f636f64655f776f726b2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d/home/jovyan/work'
    at r.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:673:13815)
    at async r.exists (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:673:16100)
    at async Promise.all (index 0)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1864:3061
C @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1242
fire @ event.ts:1273
fire @ ipc.net.ts:652
K.onmessage @ localProcessExtensionHost.ts:378
console.ts:137 [Extension Host] [vscode-icons] v12.9.0 activated!
2log.ts:439   ERR An unknown error occurred. Please consult the log for more details.: CodeExpectedError
    at _.qb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3262:27376)
    at async _.pb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3262:26632)
    at async _.Nb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3264:3923)
    at async _.ib (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3262:24007)
```

**Comment by chrmarti** [comment]
Try removing the use of `${containerEnv:...}` from `"containerEnv"`:
```json
"containerEnv": {
		"PATH": "${containerEnv:PATH}:/home/jovyan/work/path/headers"
	}
```

`${containerEnv:...}` can only be used in properties that are used after the container has started, but `"containerEnv"` is needed before that.

**Comment by jangtze** [comment]
That did indeed work. It's strange that it affected it only after the update though.

How am I supposed to use `"containerEnv"` then ? And how do I add some folder to the `PATH`? Should I export it in a `postCreateCommand` ?

**Comment by jangtze** [comment]
done
