### ISSUE TITLE
 Error: Cannot find module 'original-fs'

### ISSUE THREAD

**Issue by scarf005** [microsoft/vscode-remote-release#10328]
Type: <b>Bug</b>

followed guide: https://distrobox.it/posts/integrate_vscode_distrobox/#from-flatpak

log:
```
[88489 ms] Port forwarding connection from 36194 > 37357 > 43249 in the container.
[88489 ms] Start: Run in container: /home/scarf/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/node -e 
[88729 ms] Port forwarding 36194 > 37357 > 43249 stderr: Connection established
[88736 ms] [00:23:01] [127.0.0.1][e998e385][ExtensionHostConnection] New connection established.
[88739 ms] [00:23:01] [127.0.0.1][e998e385][ExtensionHostConnection] <4032573> Launched Extension Host Process.
[88765 ms] [00:23:01] [127.0.0.1][e998e385][ExtensionHostConnection] <4032573><stderr> Loading "original-fs" failed

[88767 ms] [00:23:01] [127.0.0.1][e998e385][ExtensionHostConnection] <4032573><stderr> Error: Cannot find module 'original-fs'
Require stack:
- /var/tmp/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/out/bootstrap-fork.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at i (/var/tmp/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/out/bootstrap-fork.js:3:98)
    at r.load (/var/tmp/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/out/bootstrap-fork.js:2:1637)
    at p.load (/var/tmp/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/out/bootstrap-fork.js:1:13529)
    at c (/var/tmp/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/out/bootstrap-fork.js:3:9338)
    at Object.errorback (/var/tmp/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/out/bootstrap-fork.js:3:9457)
    at p.triggerErrorback (/var/tmp/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/out/bootstrap-fork.js:1:13823)
    at /var/tmp/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/out/bootstrap-fork.js:1:13574
    at r.load (/var/tmp/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/out/bootstrap-fork.js:2:1654)
    at p.load (/var/tmp/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/out/bootstrap-fork.js:1:13529)
    at c (/var/tmp/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/out/bootstrap-fork.js:3:9338)
    at l._loadModule (/var/tmp/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/out/bootstrap-fork.js:3:9466)
    at l._resolve (/var/tmp/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/out/bootstrap-fork.js:4:452)
    at l.defineModule (/var/tmp/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/out/bootstrap-fork.js:3:5561)
    at Function.h [as define] (/var/tmp/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/out/bootstrap-fork.js:4:1741)
    at out-build/bootstrap-amd.js (/var/tmp/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/out/bootstrap-fork.js:4:6260)
    at /var/tmp/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/out/bootstrap-fork.js:1:132
    at Object.<anonymous> (/var/tmp/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/out/bootstrap-fork.js:4:6663)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/tmp/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/out/bootstrap-fork.js'
  ],
  phase: 'loading',
  moduleId: 'original-fs',
  neededBy: [ 'fs' ]
}

[88767 ms] [00:23:01] [127.0.0.1][e998e385][ExtensionHostConnection] <4032573><stderr> Here are the modules that depend on it:
[ 'fs' ]

[92197 ms] Start: Run in container: /bin/sh -c # Watch installed extensions
[98838 ms] [00:23:11] [127.0.0.1][e998e385][ExtensionHostConnection] <4032573> Extension Host Process exited with code: 0, signal: null.
[98839 ms] Port forwarding 36194 > 37357 > 43249 stderr: Remote close
[98868 ms] Port forwarding 36194 > 37357 > 43249 terminated with code 0 and signal null.
[98869 ms] Port forwarding 36194 > 37357 > 43249: Local close
[98871 ms] Port forwarding connection from 51504 > 37357 > 43249 in the container.
[98872 ms] Start: Run in container: /home/scarf/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/node -e 
[99146 ms] Port forwarding 51504 > 37357 > 43249 stderr: Connection established
[99152 ms] [00:23:11] [127.0.0.1][e998e385][ExtensionHostConnection] Unknown reconnection token (seen before).
[99153 ms] Port forwarding 51504 > 37357 > 43249 stderr: Remote close
[99174 ms] Port forwarding 51504 > 37357 > 43249 terminated with code 0 and signal null.
[99175 ms] Port forwarding 51504 > 37357 > 43249: Local close
[120609 ms] Start: Run in container: cat '/home/scarf/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/product.json'
[120611 ms] Start: Run in container: /home/scarf/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/bin/code-server --server-data-dir /home/scarf/.vscode-server --telemetry-level off --list-extensions
[120996 ms] github.copilot
github.copilot-chat
github.vscode-pull-request-github
llvm-vs-code-extensions.vscode-clangd
[120996 ms] 
[120997 ms] Start: Run in container: /bin/sh -c # Watch installed extensions
[125087 ms] Start: Run in container: /bin/sh -c # Watch machine settings
[133384 ms] Extensions cache, remote removals: None
[181582 ms] Start: Run in container: /bin/sh -c # Watch installed extensions
[185593 ms] Start: Run in container: /bin/sh -c # Watch machine settings
[193388 ms] Extensions cache, remote removals: None
```

Extension version: 0.384.0
VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Linux x64 6.10.8-200.fc40.x86_64
Modes:
Remote OS version: Linux x64 6.10.8-200.fc40.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600G with Radeon Graphics (12 x 3787)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 2, 3|
|Memory (System)|30.68GB (5.14GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|

|Item|Value|
|---|---|
|Remote|Container registry.fedoraproject.org/fedora:latest (fedora)|
|OS|Linux x64 6.10.8-200.fc40.x86_64|
|CPUs|AMD Ryzen 5 5600G with Radeon Graphics (12 x 4204)|
|Memory (System)|30.68GB (5.14GB free)|
|VM|0%|
</details>

**Comment by joshspicer** [comment]
Thanks for opening an issue

Quickly looking at the guide you've posted, one thing you may try is to select another non-`archlinux` container to attach to ([see these docs for some other supported distros you may use](https://code.visualstudio.com/docs/remote/linux)). I'm not sure if choosing that container was incidental to your goals here or not. 

It may also be useful for other taking a look at your issue if you append your full logs (`F1` > `Dev Containers: Show Container Log`).

**Comment by chrmarti** [comment]
Also: Are you setting `ELECTRON_RUN_AS_NODE` anywhere? Looks like https://github.com/microsoft/vscode/issues/224498 with a different stacktrace.
