### ISSUE TITLE
Using Devcontainer build options doesn't work?

### ISSUE THREAD

**Issue by Wicaeed** [microsoft/vscode-remote-release#10334]
I am trying to force a specific docker buildx builder via Devcontainer options and it doesn't appear to work correctly when passed to the docker buildx command.

After finding the actual docker buildx command being executed by VCode and pulling it apart, this works:
```
docker buildx build \
  --load --build-arg BUILDKIT_INLINE_CACHE=1 \
  -f /var/folders/kf/sp552l4j16302wn0xj3t0jn80000gq/T/devcontainercli/container-features/0.69.0-1727559871354/Dockerfile-with-features \
  -t vsc-terraform-provider-databricks-2d99ecec934e1ebabf18f314baa794e1161f0dda279a5a9f765cb9d801768592 \
  --target dev_containers_target_stage --build-arg VARIANT=1.19-bullseye \
  --build-arg NODE_VERSION=none \
  --builder dev_buildx_builder \ <--- my custom Docker Desktop builder on macOS
  --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /Users/my.username/Projects/scratch/terraform-provider-databricks/.devcontainer
```

When run from VSCode Devcontainers, an error:
```
[2024-09-28T21:59:03.910Z] Start: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/kf/sp552l4j16302wn0xj3t0jn80000gq/T/devcontainercli/container-features/0.69.0-1727560743908/Dockerfile-with-features -t vsc-terraform-provider-databricks-2d99ecec934e1ebabf18f314baa794e1161f0dda279a5a9f765cb9d801768592 --target dev_containers_target_stage --build-arg VARIANT=1.19-bullseye --build-arg NODE_VERSION=none --builder dev_buildx_builder --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /Users/my.name/Projects/scratch/terraform-provider-databricks/.devcontainer
[2024-09-28T21:59:03.955Z] unknown flag: --builder dev_buildx_builder
See 'docker buildx build --help'.
[2024-09-28T21:59:03.986Z] Stop (76 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/kf/sp552l4j16302wn0xj3t0jn80000gq/T/devcontainercli/container-features/0.69.0-1727560743908/Dockerfile-with-features -t vsc-terraform-provider-databricks-2d99ecec934e1ebabf18f314baa794e1161f0dda279a5a9f765cb9d801768592 --target dev_containers_target_stage --build-arg VARIANT=1.19-bullseye --build-arg NODE_VERSION=none --builder dev_buildx_builder --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /Users/my.name/Projects/scratch/terraform-provider-databricks/.devcontainer
[2024-09-28T21:59:03.987Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/kf/sp552l4j16302wn0xj3t0jn80000gq/T/devcontainercli/container-features/0.69.0-1727560743908/Dockerfile-with-features -t vsc-terraform-provider-databricks-2d99ecec934e1ebabf18f314baa794e1161f0dda279a5a9f765cb9d801768592 --target dev_containers_target_stage --build-arg VARIANT=1.19-bullseye --build-arg NODE_VERSION=none --builder dev_buildx_builder --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /Users/my.name/Projects/scratch/terraform-provider-databricks/.devcontainer
[2024-09-28T21:59:03.987Z]     at FtA (/Users/my.name/.vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js:466:1933)
[2024-09-28T21:59:03.987Z]     at async Pm (/Users/my.name/.vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js:465:1896)
[2024-09-28T21:59:03.987Z]     at async NH (/Users/my.name/.vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js:465:610)
[2024-09-28T21:59:03.987Z]     at async YtA (/Users/my.name/.vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js:482:3771)
[2024-09-28T21:59:03.988Z]     at async eB (/Users/my.name/.vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js:482:4886)
[2024-09-28T21:59:03.988Z]     at async prA (/Users/my.name/.vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js:663:200)
[2024-09-28T21:59:03.988Z]     at async drA (/Users/my.name/.vscode/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js:662:14706)
```

- VSCode Version:
```
Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.6.0
```
- Local OS Version:
```
Ventura 13.5 (22G74)
```
- Remote OS Version:
Devcontainers (varies)
- Remote Extension/Connection Type: Containers

- Logs:
Can provide full logs as needed.

Steps to Reproduce:

1. Attempt to customize a devcontainer.json build options to force a custom docker buildx builder
2. Observe error

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
Try passing it as two arguments:
```json
		"options": [
			"--builder", "dev_buildx_builder"
		]
```
