### ISSUE TITLE
[Remote-SSH Bug]: Unable to pick or connect to host when /etc/ssh/ssh_config is not readable on Linux client, unhandled error EACCES

### ISSUE THREAD

**Issue by dblitt** [microsoft/vscode-remote-release#10341]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [x] I have tried both values of the `remote.SSH.useLocalServer` setting
(this does not apply to my case, I cannot even get this far)

### Connect Locally

It connects successfully

### Expected Behavior

Remote-SSH should simply move on to all other config files if `/etc/ssh/ssh_config` is not readable. For instance, my home directory `~/.ssh/config` is still readable.

Instead, clicking `Connect To Host...` silently fails, never giving me the option to pick from my personal `~/.ssh/config` or even to manually type in a SSH host. There are only log entries buried in the extension host output (See attached below in log section)

### Steps To Reproduce

1. Make `/etc/ssh/ssh_config` unreadable (`chmod 600 /etc/ssh/ssh_config`)
2. Click the "`Open a Remote Window`" blue button in the bottom left corner of VSCode
3. Click "`Connect to Host...        Remote-SSH`"
4. Here is the issue: nothing happens now.

### Remote-SSH and Extension Host Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[14:44:34.050] Log Level: 2
[14:44:34.064] Picking SSH host
[14:44:34.188] VS Code version: 1.93.1
[14:44:34.188] Remote-SSH version: remote-ssh@0.114.3
[14:44:34.188] linux x64
[14:46:21.331] Picking SSH host
[14:46:36.542] Picking SSH host
[14:55:45.389] Picking SSH host
```

</p>
</details>

<details>
<summary><b>Extension Host Log</b> (this is where the error is)</summary>
<p>

```
2024-10-01 14:44:34.232 [error] Error: EACCES: permission denied, open '/etc/ssh/ssh_config' opensshremotes.openEmptyWindow {"value":"ms-vscode-remote.remote-ssh","_lower":"ms-vscode-remote.remote-ssh"}
2024-10-01 14:44:34.234 [error] Error: EACCES: permission denied, open '/etc/ssh/ssh_config' remote-internal.getConfiguredHostnames {"value":"ms-vscode-remote.remote-ssh","_lower":"ms-vscode-remote.remote-ssh"}
2024-10-01 14:46:21.333 [error] Error: EACCES: permission denied, open '/etc/ssh/ssh_config' opensshremotes.openEmptyWindow {"value":"ms-vscode-remote.remote-ssh","_lower":"ms-vscode-remote.remote-ssh"}
2024-10-01 14:46:36.544 [error] Error: EACCES: permission denied, open '/etc/ssh/ssh_config' opensshremotes.openEmptyWindow {"value":"ms-vscode-remote.remote-ssh","_lower":"ms-vscode-remote.remote-ssh"}
2024-10-01 14:48:11.016 [error] Error: EACCES: permission denied, open '/etc/ssh/ssh_config' remote-internal.getConfiguredHostnames {"value":"ms-vscode-remote.remote-ssh","_lower":"ms-vscode-remote.remote-ssh"}
2024-10-01 14:55:45.392 [error] Error: EACCES: permission denied, open '/etc/ssh/ssh_config' opensshremotes.openEmptyWindow {"value":"ms-vscode-remote.remote-ssh","_lower":"ms-vscode-remote.remote-ssh"}
```

</p>
</details>

### Anything else?

I unfortunately cannot make `/etc/ssh/ssh_config` readable - this is a shared workstation I do not have root permissions on. Although I realize that this is a very strange edge case!

**Comment by joshspicer** [comment]
Thanks for opening the issue.  Good idea - i'll take a look at fixing this

**Comment by rmecboy** [comment]
I face the same problem today.
And I find a solution ,

1. Modify your vscode @ext:ms-vscode-remote.remote-ssh,ms-vscode-remote.remote-ssh-edit,ms-vscode.remote-explorer config file
      add absolute file path of your custom SSH configuration file
      ![Image](https://github.com/user-attachments/assets/65dede4c-2de3-4659-887a-6a71d573b928)

2. Write your configuration in the file，
        eg:   Host remotehost.yourcompany.com
                        User yourname
                        HostName another-host-fqdn-or-ip-goes-here
                        IdentityFile ~/.ssh/id_rsa-remote-ssh

3. 1)Click the "Open a Remote Window" blue button in the bottom left corner of VSCode
    2)Click "Connect to Host...        Remote-SSH"
4. A pop-up appears and the problem is magically solved

**Comment by joshspicer** [comment]
A change should be available in the latest 'pre-release' build of the extension.  If you'd like to test for us before the next stable release, you can switch channels on the extension page.

Let me know if you're still able to repro on the pre-release, and please provide the logs as done above.

![Image](https://github.com/user-attachments/assets/19507ed8-ed1f-4e69-b0ff-d200107435ab)

**Comment by rmecboy** [comment]
My system is Ubuntu 20.04, vscode version is the latest verision. 
I tried the latest stable version and pre-release version of the SSH plugin , but the bug occurred,nothing happens after I Click "Connect to Host...        Remote-SSH"

Remote-SSH log
```
[00:08:27.956] Log Level: 2
[00:08:28.071] VS Code version: 1.94.2
[00:08:28.072] Remote-SSH version: remote-ssh@0.115.0
[00:08:28.072] linux x64
[00:08:40.892] Picking SSH host
[00:17:01.552] Picking SSH host
[00:17:13.640] Picking SSH host
[00:17:25.984] Picking SSH host
[00:19:26.216] Picking SSH host
[00:22:15.055] Picking SSH host
```

Extension Host Log
```
2024-10-12 00:08:28.394 [info] Eager extensions activated
2024-10-12 00:08:28.428 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-10-12 00:08:28.433 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-10-12 00:08:40.896 [error] TypeError: Cannot read properties of undefined (reading 'after')
	at w (/home/heisenberg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:447791)
	at $ (/home/heisenberg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:591885)
	at async R (/home/heisenberg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:590718)
	at async t.getConfiguredSshHosts (/home/heisenberg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:593014)
	at async t.interactivelyPickSshHost (/home/heisenberg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:483022)
	at async g.openEmptyWindow (/home/heisenberg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:461829)
	at async T0.h (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32837) opensshremotes.openEmptyWindow {"value":"ms-vscode-remote.remote-ssh","_lower":"ms-vscode-remote.remote-ssh"}
```

**Comment by joshspicer** [comment]
This change is only in pre-release, could you share your logs (both remote SSH and extension host) after installing the pre-release (restart VS Code just to be sure!)
