### ISSUE TITLE
Error: Parent authority found without ExecServer on Dev Containers - v0.388.0

### ISSUE THREAD

**Issue by pamgluss-slack** [microsoft/vscode-remote-release#10347]
- VSCode Version: 1.94.0
- Local OS Version: MacOS Sonoma 14.7 (23H124)
- Remote OS Version: Debian GNU/Linux 11 (bullseye)
- Remote Extension/Connection Type: Containers

- Logs:
```
[17 ms] Dev Containers 0.388.0 in VS Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511).
[16 ms] Start: Resolving Remote
[22 ms] Error: Parent authority found without ExecServer: k8s-container+context=<CLUSTER>+podname=pgluss-slack-<REPO>-zyfx2k19-0+namespace=default+name=release+image=<REDACTED>.dkr.ecr.us-east-1.amazonaws.com/release@sha256:<REDACTED>
        at /Users/pgluss/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/extension/extension.js:406:4049
        at OU.d (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:155:32215)
        at OU.withProgress (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:155:32081)
        at Object.withProgress (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:47360)
        at fCe (/Users/pgluss/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/extension/extension.js:406:3831)
        at $Z (/Users/pgluss/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/extension/extension.js:406:3632)
```

Steps to Reproduce:

1. Open the container with the follow vscode-remote command: `code --disable-workspace-trust --folder-uri "vscode-remote://k8s-container+context=<CLUSTER>+podname=pgluss-slack-<REPO>-zyfx2k19-0+namespace=default+name=release+image=<REDACTED>.dkr.ecr.us-east-1.amazonaws.com%2Frelease%40sha256%<REDACTED>/mnt/devspace"`
2. VSCode opens but cannot connect to container. Terminal indicates the error above.

Workaround: downgrade to v0.369.0 for the dev containers extension.

It also doesn't seem to happen for every repo we use this tool with but we don't know what this error means.

**Comment by chrmarti** [comment]
`@` has become a special character. You could use an encoded variation of the authority:
```js
	const options = {
		context: '...',
		podname: '...',
		name: '...',
		image: '...',
		namespace: '...',
	};
	console.log(`k8s-container+${Buffer.from(JSON.stringify(options), 'utf8').toString('hex')}`);
```

**Comment by pamgluss-slack** [comment]
> `@` has become a special character. You could use an encoded variation of the authority:
> 
> ```js
> 	const options = {
> 		context: '...',
> 		podname: '...',
> 		name: '...',
> 		image: '...',
> 		namespace: '...',
> 	};
> 	console.log(`k8s-container+${Buffer.from(JSON.stringify(options), 'utf8').toString('hex')}`);
> ```

We are using Ruby to encode with `CGI::escape(image_url)` which already encodes `@` as `%40` but it seems during the decoding process of opening VSCode it is still getting that error.

**Comment by chrmarti** [comment]
Closing as you have found a workaround. Thanks.
