### ISSUE TITLE
Remote-ssh connect with proxy error: /bin/login_script.sh: No such file or directory

### ISSUE THREAD

**Issue by panicooo** [microsoft/vscode-remote-release#10369]
Hi, I'm using remote-ssh to connect machine 10.139.222.50 with ProxyCommand:
```
Host 10.139.222.50
    HostName 10.139.222.50
    User yujinbiao
    ProxyCommand ssh -W %h:%p yujinbiao@10.151.196.19
```

But I got the following error:

```
local-server-1> Spawned ssh, pid=90058
OpenSSH_9.4p1, LibreSSL 3.3.6
/bin/login_script.sh: No such file or directory
banner exchange: Connection to UNKNOWN port 65535: Broken pipe
local-server-1> ssh child died, shutting down
```

I see the env variable  got **SHELL":"/bin/login_script.sh"** in local server env, but the terminal I got result of SHELL is  **/bin/zsh** , so how to set the SHELL variable for remote-ssh? Waht I can do？ thansk.

besides, the default shell for terminal is zsh:

<img width="561" alt="image" src="https://github.com/user-attachments/assets/1b51ab4e-b3bc-43a8-bd74-3b8c02f433c2">

**There are  detail logs:**

[22:22:25.590] Install and start server if needed
[22:22:25.593] PATH: /usr/bin:/bin:/usr/sbin:/sbin
[22:22:25.593] Checking ssh with "ssh -V"
[22:22:25.603] > OpenSSH_9.4p1, LibreSSL 3.3.6

[22:22:25.606] askpass server listening on /var/folders/pm/cgp3wctj6ln3ddtrh2fp77f8tjjyrg/T/vscode-ssh-askpass-605e99d218c703e9db66c5ed1e657f5b143cd823.sock
[22:22:25.606] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/pm/cgp3wctj6ln3ddtrh2fp77f8tjjyrg/T/vscode-ssh-askpass-9b5f29487117e87dd03b61bcb4b0933d15f6dc49.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","55169","-o","ConnectTimeout=15","10.139.222.50"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/yujinbiao/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-ab2471e4-d78a74bcdfad14d5d3b1b782f87255d802b57511-0.115.0-es/data.json"}
[22:22:25.606] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.RA0nj9ANZy/Listeners","SHELL":"/bin/login_script.sh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/yujinbiao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"","VSCODE_SSH_ASKPASS_MAIN":"/Users/yujinbiao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/pm/cgp3wctj6ln3ddtrh2fp77f8tjjyrg/T/vscode-ssh-askpass-605e99d218c703e9db66c5ed1e657f5b143cd823.sock"}
[22:22:25.606] Spawned 90057
[22:22:25.607] Using connect timeout of 17 seconds
[22:22:25.694] > local-server-1> Running ssh connection command: ssh -v -T -D 55169 -o ConnectTimeout=15 10.139.222.50
[22:22:25.695] > local-server-1> Spawned ssh, pid=90058
[22:22:25.699] stderr> OpenSSH_9.4p1, LibreSSL 3.3.6
[22:22:25.701] stderr> /bin/login_script.sh: No such file or directory
[22:22:25.702] stderr> banner exchange: Connection to UNKNOWN port 65535: Broken pipe
[22:22:25.702] > local-server-1> ssh child died, shutting down
[22:22:25.706] Local server exit: 0
[22:22:25.707] Received install output: local-server-1> Running ssh connection command: ssh -v -T -D 55169 -o ConnectTimeout=15 10.139.222.50
local-server-1> Spawned ssh, pid=90058
OpenSSH_9.4p1, LibreSSL 3.3.6
/bin/login_script.sh: No such file or directory
banner exchange: Connection to UNKNOWN port 65535: Broken pipe
local-server-1> ssh child died, shutting down

[22:22:25.707] Failed to parse remote port from server output
[22:22:25.708] Resolver error: Error: 
	at v.Create (/Users/yujinbiao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:493431)
	at t.handleInstallOutput (/Users/yujinbiao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:490753)
	at e (/Users/yujinbiao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:545236)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /Users/yujinbiao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:567561
	at async t.withShowDetailsEvent (/Users/yujinbiao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:571256)
	at async /Users/yujinbiao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:541941
	at async T (/Users/yujinbiao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:539992)
	at async t.resolveWithLocalServer (/Users/yujinbiao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:541481)
	at async P (/Users/yujinbiao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:564693)
	at async t.resolve (/Users/yujinbiao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:568667)
	at async /Users/yujinbiao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:839059
[22:22:25.711] ------

**Comment by joshspicer** [comment]
This is the $SHELL variable that the `ssh` program would see (not what is set in VS Code).  You should find out where $SHELL is being set on your local machine and reset it to something like `/bin/zsh`. 

If you were to run the ssh command manually (`ssh -v -T -D 55169 -o ConnectTimeout=15 10.139.222.50`) you'd see the same issue
