### ISSUE TITLE
VSCode cannot detect and load installed extension information during remote connection

### ISSUE THREAD

**Issue by princewang666** [microsoft/vscode-remote-release#10443]
- VSCode Version:1.95.1
- Local OS Version:Windows_NT x64 10.0.22631
- Remote OS Version:Ubuntu 22.04.4 LTS（Runs on VMware workstation player）
- Remote Extension/Connection Type: Server

- Logs:
Window Log：
```2024-11-05 14:43:22.530 [info] Started local extension host with pid 17780.
2024-11-05 14:43:22.817 [error] Extension 'ms-vscode.cpptools' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): terminalDataWriteEvent, lmTools
product.json (WINS): terminalDataWriteEvent
2024-11-05 14:43:22.963 [info] Invoking resolveAuthority(ssh-remote)...
2024-11-05 14:43:22.963 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] obtaining proxy...
2024-11-05 14:43:22.964 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] invoking...
2024-11-05 14:43:23.973 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][1009ms] waiting...
2024-11-05 14:43:24.970 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][2006ms] waiting...
2024-11-05 14:43:25.969 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][3006ms] waiting...
2024-11-05 14:43:26.071 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][3108ms] returned Managed(1)
2024-11-05 14:43:26.072 [info] resolveAuthority(ssh-remote) returned 'Managed(1)' after 3108 ms
2024-11-05 14:43:26.072 [info] Creating a socket (renderer-Management-2e7e12fc-241e-4b7e-bf47-70a3fcf41e07)...
2024-11-05 14:43:26.072 [info] Creating a socket (renderer-ExtensionHost-7efb876c-1128-4a8c-8ba0-4efcc540813e)...
2024-11-05 14:43:26.131 [info] Creating a socket (renderer-ExtensionHost-7efb876c-1128-4a8c-8ba0-4efcc540813e) was successful after 58 ms.
2024-11-05 14:43:26.146 [info] Creating a socket (renderer-Management-2e7e12fc-241e-4b7e-bf47-70a3fcf41e07) was successful after 74 ms.
2024-11-05 14:43:27.415 [info] [perf] Render performance baseline is 21ms
2024-11-05 14:43:27.880 [error] [network] #2: https://az764295.vo.msecnd.net/extensions/chat.json - error GET Failed to fetch
2024-11-05 14:43:27.880 [warning] Failed to fetch chat participant registry Failed to fetch
2024-11-05 14:43:32.081 [error] [network] #1: https://api.github.com/copilot_internal/user - error GET Failed to fetch
2024-11-05 14:43:32.081 [error] Failed to fetch: TypeError: Failed to fetch
    at i$s (vscode-file://vscode-app/d:/Devs/VSCode/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3090:35915)
    at vscode-file://vscode-app/d:/Devs/VSCode/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3090:37096
    at prt.c (vscode-file://vscode-app/d:/Devs/VSCode/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:494:27265)
    at prt.request (vscode-file://vscode-app/d:/Devs/VSCode/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3090:37088)
    at Kat.y (vscode-file://vscode-app/d:/Devs/VSCode/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3422:1914)
    at Kat.w (vscode-file://vscode-app/d:/Devs/VSCode/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3422:1776)
    at vZ.value (vscode-file://vscode-app/d:/Devs/VSCode/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3422:1691)
2024-11-05 14:43:49.868 [error] [network] #4: https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery - error POST Canceled
2024-11-05 14:48:33.285 [error] [network] #7: https://az764295.vo.msecnd.net/extensions/chat.json - error GET Failed to fetch
2024-11-05 14:48:33.285 [warning] Failed to fetch chat participant registry Failed to fetch
2024-11-05 14:53:40.689 [error] [network] #8: https://az764295.vo.msecnd.net/extensions/chat.json - error GET Failed to fetch
2024-11-05 14:53:40.689 [warning] Failed to fetch chat participant registry Failed to fetch
2024-11-05 14:58:45.810 [error] [network] #9: https://az764295.vo.msecnd.net/extensions/chat.json - error GET Failed to fetch
2024-11-05 14:58:45.810 [warning] Failed to fetch chat participant registry Failed to fetch
2024-11-05 15:03:46.263 [error] [network] #10: https://az764295.vo.msecnd.net/extensions/chat.json - error GET Failed to fetch
2024-11-05 15:03:46.263 [warning] Failed to fetch chat participant registry Failed to fetch
2024-11-05 15:08:47.057 [error] [network] #11: https://az764295.vo.msecnd.net/extensions/chat.json - error GET Failed to fetch
2024-11-05 15:08:47.072 [warning] Failed to fetch chat participant registry Failed to fetch
2024-11-05 15:13:48.867 [error] [network] #12: https://az764295.vo.msecnd.net/extensions/chat.json - error GET Failed to fetch
2024-11-05 15:13:48.883 [warning] Failed to fetch chat participant registry Failed to fetch
2024-11-05 15:18:53.995 [error] [network] #13: https://az764295.vo.msecnd.net/extensions/chat.json - error GET Failed to fetch
2024-11-05 15:18:54.011 [warning] Failed to fetch chat participant registry Failed to fetch
```
Shared Log
```
2024-11-05 14:43:25.274 [error] [network] #1: https://az764295.vo.msecnd.net/extensions/marketplace.json - error GET net::ERR_CONNECTION_CLOSED
2024-11-05 14:48:32.303 [error] [network] #33: https://az764295.vo.msecnd.net/extensions/marketplace.json - error GET net::ERR_CONNECTION_CLOSED
2024-11-05 14:53:40.776 [error] [network] #52: https://az764295.vo.msecnd.net/extensions/marketplace.json - error GET net::ERR_CONNECTION_CLOSED
2024-11-05 14:59:39.457 [error] [network] #99: https://az764295.vo.msecnd.net/extensions/marketplace.json - error GET net::ERR_CONNECTION_CLOSED
2024-11-05 15:04:41.238 [error] [network] #109: https://az764295.vo.msecnd.net/extensions/marketplace.json - error GET net::ERR_CONNECTION_CLOSED
2024-11-05 15:09:41.441 [error] [network] #112: https://az764295.vo.msecnd.net/extensions/marketplace.json - error GET net::ERR_CONNECTION_CLOSED
2024-11-05 15:14:46.840 [error] [network] #115: https://az764295.vo.msecnd.net/extensions/marketplace.json - error GET net::ERR_CONNECTION_CLOSED
2024-11-05 15:19:47.598 [error] [network] #122: https://az764295.vo.msecnd.net/extensions/marketplace.json - error GET net::ERR_CONNECTION_CLOSED
2024-11-05 15:24:54.039 [error] [network] #134: https://az764295.vo.msecnd.net/extensions/marketplace.json - error GET net::ERR_CONNECTION_CLOSED
```

Steps to Reproduce:

1.After connecting to the server remotely using VSCode, click "Extensions" in the search bar on the left.
2.Then the progress bar on the top of "Extensions" keeps loading，and none of the installed extensions were detected
![Image](https://github.com/user-attachments/assets/1cdbfd16-48ed-480d-8cb0-b4be467a3f8a)
3.Try to download extensions to remote servers, such as Python and the Python Debugger. VSCode stuck in the downloading status for a long time, and the above error message appears in the log
![Image](https://github.com/user-attachments/assets/44e4c7d0-cf7e-4eed-b12f-9babe2c2d062)

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by joshspicer** [comment]
Could you share about about the remote machine? Is it behind a corporate firewall or proxy?

When connected to your remote machine, what happens if you try to try to connect to one of those URLs in the integrated terminal?

```bash
curl -s -w "%{http_code}\n" -o /dev/null https://az764295.vo.msecnd.net/extensions/marketplace.json

200
```

**Comment by princewang666** [comment]
My remote server has been configured with an proxy via the Ubuntu Desktop GUI before, but no matter whether I disable the proxy or enable the proxy , the terminal does not respond when I execute the above command
disable proxy
![Image](https://github.com/user-attachments/assets/798da481-97a7-493b-a5e6-024cbf3c9281)
enable proxy
![Image](https://github.com/user-attachments/assets/c20d415d-18c5-42bd-9bd0-10025f74cf34)
I enable/disable proxy via the Ubuntu desktop GUI Settings 
![Image](https://github.com/user-attachments/assets/e2ef4360-7ebb-4279-825b-6fe3ec6b1d85)

**Comment by Jackanapex** [comment]
https://az764295.vo.msecnd.net/ (seemingly a vscode extension CDN) has been deprecated per the documentation https://code.visualstudio.com/docs/setup/network . Try to update your vscode version in local to 1.97 could possibly resolve the problem.

**Comment by joshspicer** [comment]
Thanks @Jackanapex.

Yes, please let us know if this reproduces on the latest versions of VS Code and Remote - SSH.

**Comment by Ayukjhay** [comment]
Boss how can claimed tokens
