### ISSUE TITLE
[Remote-SSH Bug]: 1st connection always fails in double offline env

### ISSUE THREAD

**Issue by SecureFlag-Aedan** [microsoft/vscode-remote-release#10451]
### Is there an existing issue for this bug?

- [x] I have searched the existing issues

### Required Troubleshooting Steps

- [x] I have followed these troubleshooting steps
- [x] I have tried both values of the `remote.SSH.useLocalServer` setting [(more info here)](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting#troubleshooting-steps)

### Connect Locally

It connects successfully

### Expected Behavior

I would like to connect to a vscode server running on a EC2 instance that is fire-walled from the rest of the real world, with another ec2 instance that is also fire-walled from the rest of the world but they can both see each other.

For some reason the second connection always works but the first one does not. They only difference in the broken logs and the fixed logs is:

Broken:
```text
> Waiting for server log...
[11:18:18.942] > Waiting for server log...
[11:18:18.978] > Waiting for server log...
[11:18:19.005] > Waiting for server log...
[11:18:19.038] > Waiting for server log...
[11:18:19.070] > Waiting for server log...
[11:18:19.102] > Waiting for server log...
[11:18:19.133] > Waiting for server log...
[11:18:19.166] > Waiting for server log...
[11:18:19.199] > Waiting for server log...
[11:18:19.230] > Waiting for server log...
[11:18:19.265] > Waiting for server log...
[11:18:19.298] > Waiting for server log...
[11:18:19.329] > Waiting for server log...
[11:18:19.363] > Waiting for server log...
[11:18:19.391] > 74faf03935a2: start

[11:18:19.391] > 74faf03935a2: start
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> serverStartTime==485==
> execServerToken==aa1a1111-a1a1-1111-a111-111aa11a1111==
> platformDownloadPath==cli-alpine-x64==
> 74faf03935a2: end
[11:18:19.391] Received install output: 
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
serverStartTime==485==
execServerToken==aa1a1111-a1a1-1111-a111-111aa11a1111==
platformDownloadPath==cli-alpine-x64==
```

Fixed:
```text
[11:12:24.613] > Waiting for server log...
[11:12:24.645] > a3208703e244: start
> listeningOn==127.0.0.1:43067==
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> serverStartTime==36==
> execServerToken==11a11aa1-aa11-11a1-a1a1-a11a111a1111==
> platformDownloadPath==cli-alpine-x64==
> a3208703e244: end
[11:12:24.646] Received install output: 
listeningOn==127.0.0.1:43067==
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
serverStartTime==36==
execServerToken==11a11aa1-aa11-11a1-a1a1-a11a111a1111==
platformDownloadPath==cli-alpine-x64==
[11:12:24.647] Remote server is listening on port 43067
```

### Steps To Reproduce

1. Install in an offline environment such as docker container.
```shell
# Define VSCode Server environment variables
export VSCODE_COMMIT_HASH="65edc4939843c90c34d61f4ce11704f09d3e5cb6"
export VSCODE_CLI_PATH="$HOME_DIR/.vscode-server"
export VSCODE_SERVER_BIN_PATH="$VSCODE_CLI_PATH/bin/$VSCODE_COMMIT_HASH"
export VSCODE_CLI_SERVER_PATH="$VSCODE_CLI_PATH/cli/servers/Stable-$VSCODE_COMMIT_HASH"
export VSCODE_SERVER_BIN="$VSCODE_SERVER_BIN_PATH/bin/code-server"

# VS Code download URLs
export VSCODE_BASE_URL="https://vscode.download.prss.microsoft.com/dbazure/download/stable/$VSCODE_COMMIT_HASH"
export VSCODE_CLI_URL="$VSCODE_BASE_URL/vscode_cli_alpine_x64_cli.tar.gz"
export VSCODE_SERVER_URL="$VSCODE_BASE_URL/vscode-server-linux-x64.tar.gz"

# Create required directories with necessary permissions
mkdir -vp "$VSCODE_SERVER_BIN_PATH"
mkdir -vp "$VSCODE_CLI_PATH/extensions"
mkdir -vp "$VSCODE_CLI_PATH/extensionsCache"
mkdir -vp "$VSCODE_CLI_SERVER_PATH"

echo "Downloading and extracting VS Code CLI..."
wget -qO- "$VSCODE_CLI_URL" | tar -xz -C "$VSCODE_CLI_PATH" --transform="s|code|code-$VSCODE_COMMIT_HASH|"

echo "Downloading and extracting VS Code Server..."
wget -qO- "$VSCODE_SERVER_URL" | tar -xz -C "$VSCODE_SERVER_BIN_PATH" --strip-components=1 --no-same-owner

# Create symbolic links for the default version and CLI server
echo "Setting up symlinks..."
ln -sf "$VSCODE_SERVER_BIN_PATH" "$VSCODE_CLI_PATH/bin/default_version"
ln -sf "$VSCODE_SERVER_BIN_PATH" "$VSCODE_CLI_SERVER_PATH/server"

# Install the necessary VS Code extensions for remote SSH functionality
$VSCODE_SERVER_BIN --install-extension mads-hartmann.bash-ide-vscode
$VSCODE_SERVER_BIN --install-extension ms-python.python
$VSCODE_SERVER_BIN --install-extension ms-python.vscode-pylance
$VSCODE_SERVER_BIN --install-extension ms-python.debugpy
$VSCODE_SERVER_BIN --install-extension yocto-project.yocto-bitbake
echo "VS Code installation complete."

```

2. Attempt to connect with a device that has network access to the server but not to Microsoft to stop it from downloading the server locally.
3. Watch it fail the first time, click retry and watch it connect no problems.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[11:18:17.775] Log Level: 2
[11:18:17.782] VS Code version: 1.94.0
[11:18:17.782] Remote-SSH version: remote-ssh@0.115.0
[11:18:17.782] linux x64
[11:18:17.804] SSH Resolver called for "ssh-remote+server.secureflag", attempt 1
[11:18:17.806] "remote.SSH.useLocalServer": true
[11:18:17.806] "remote.SSH.useExecServer": true
[11:18:17.806] "remote.SSH.path": undefined
[11:18:17.806] "remote.SSH.configFile": undefined
[11:18:17.806] "remote.SSH.useFlock": true
[11:18:17.807] "remote.SSH.lockfilesInTmp": false
[11:18:17.807] "remote.SSH.localServerDownload": auto
[11:18:17.807] "remote.SSH.remoteServerListenOnSocket": false
[11:18:17.807] "remote.SSH.showLoginTerminal": false
[11:18:17.807] "remote.SSH.defaultExtensions": []
[11:18:17.807] "remote.SSH.loglevel": 2
[11:18:17.807] "remote.SSH.enableDynamicForwarding": true
[11:18:17.807] "remote.SSH.enableRemoteCommand": false
[11:18:17.808] "remote.SSH.serverPickPortsFromRange": {}
[11:18:17.808] "remote.SSH.serverInstallPath": {}
[11:18:17.808] "remote.SSH.permitPtyAllocation": false
[11:18:17.808] "remote.SSH.preferredLocalPortRange: undefined
[11:18:17.808] "remote.SSH.useCurlAndWgetConfigurationFiles: false
[11:18:17.820] SSH Resolver called for host: server.secureflag
[11:18:17.820] Setting up SSH remote "server.secureflag"
[11:18:17.828] Acquiring local install lock: /tmp/vscode-remote-ssh-d65f5417-install.lock
[11:18:17.830] Looking for existing server data file at /home/sf/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-d65f5417-d78a74bcdfad14d5d3b1b782f87255d802b57511-0.115.0-es/data.json
[11:18:17.830] No existing data file
[11:18:17.831] Using commit id "d78a74bcdfad14d5d3b1b782f87255d802b57511" and quality "stable" for server
[11:18:17.835] Script variables:
 {
  "InstallExitCode.24": "AlreadyInProgress",
  "InstallExitCode.25": "ServerDownloadFailed",
  "InstallExitCode.26": "NoDownloaderAvailable",
  "InstallExitCode.27": "UnsupportedArch",
  "InstallExitCode.28": "StatusCheckFailed",
  "InstallExitCode.29": "NeedInsidersArch",
  "InstallExitCode.30": "NoDownloaderAvailableForStatusCheck",
  "InstallExitCode.31": "ServerTransferFailed",
  "InstallExitCode.32": "ServerFailedToStart",
  "InstallExitCode.33": "NeedInsidersWindows",
  "InstallExitCode.34": "CreateInstallDirFailed",
  "InstallExitCode.35": "UnsupportedPlatform",
  "InstallExitCode.36": "ServerTerminatedCVE20201416",
  "InstallExitCode.37": "UnpackFailed",
  "InstallExitCode.38": "ChangeDirFailed",
  "InstallExitCode.AlreadyInProgress": "24",
  "InstallExitCode.ServerDownloadFailed": "25",
  "InstallExitCode.NoDownloaderAvailable": "26",
  "InstallExitCode.NoDownloaderAvailableForStatusCheck": "30",
  "InstallExitCode.UnsupportedArch": "27",
  "InstallExitCode.StatusCheckFailed": "28",
  "InstallExitCode.NeedInsidersArch": "29",
  "InstallExitCode.ServerTransferFailed": "31",
  "InstallExitCode.ServerFailedToStart": "32",
  "InstallExitCode.NeedInsidersWindows": "33",
  "InstallExitCode.CreateInstallDirFailed": "34",
  "InstallExitCode.UnsupportedPlatform": "35",
  "InstallExitCode.ServerTerminatedCVE20201416": "36",
  "InstallExitCode.UnpackFailed": "37",
  "InstallExitCode.ChangeDirFailed": "38",
  "InstallUnpackCode.Success": "success",
  "InstallUnpackCode.Error": "error",
  "InstallUnpackCode.MissingFiles": "missingFiles",
  "uuid": "74faf03935a2",
  "startMarker": "74faf03935a2: running",
  "commitId": "d78a74bcdfad14d5d3b1b782f87255d802b57511",
  "quality": "stable",
  "token": "aa1a1111-a1a1-1111-a111-111aa11a1111",
  "vscodeAgentFolder": "$HOME/.vscode-server",
  "allowClientDownload": "1",
  "forceClientDownload": "0",
  "cliNameInArchive": "code",
  "ignoreWgetConfigFlag": " --no-config ",
  "ignoreCurlConfigFlag": " --disable ",
  "wgetTriesSegment": "--tries=1",
  "listenArgs": "--on-host=127.0.0.1 --on-port",
  "getDownloadServerStartTrigger": "74faf03935a2:trigger_server_download",
  "getDownloadServerEndTrigger": "74faf03935a2:trigger_server_download_end",
  "getProgressDownloading": "74faf03935a2%%1%%",
  "getProgressInstalling": "74faf03935a2%%2%%"
}
[11:18:17.839] Install and start server if needed
[11:18:17.845] PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/sf/.sf/bin:/opt/VSCode-linux-x64/bin:/home/sf/.sf/bin:/opt/VSCode-linux-x64/bin
[11:18:17.845] Checking ssh with "ssh -V"
[11:18:17.862] > OpenSSH_9.6p1 Ubuntu-3ubuntu13.5, OpenSSL 3.0.13 30 Jan 2024

[11:18:17.867] askpass server listening on /tmp/vscode-ssh-askpass-e9a264c2c490028ef9ba14e7f6be13f1df23c122.sock
[11:18:17.868] Spawning local server with {"serverId":1,"ipcHandlePath":"/tmp/vscode-ssh-askpass-f23aac6d69a8ec2cd076e019299351a1358a9a7a.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","35721","server.secureflag"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/sf/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-d65f5417-d78a74bcdfad14d5d3b1b782f87255d802b57511-0.115.0-es/data.json"}
[11:18:17.868] Local server env: {"SSH_AUTH_SOCK":"/tmp/ssh-UkvZIgpZWOjg/agent.90","SHELL":"/bin/bash","DISPLAY":":10.0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/sf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/opt/VSCode-linux-x64/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"","VSCODE_SSH_ASKPASS_MAIN":"/home/sf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/tmp/vscode-ssh-askpass-e9a264c2c490028ef9ba14e7f6be13f1df23c122.sock"}
[11:18:17.875] Spawned 1066
[11:18:17.876] Using connect timeout of 3 seconds
[11:18:18.029] > local-server-1> Running ssh connection command: ssh -v -T -D 35721 server.secureflag
[11:18:18.038] > local-server-1> Spawned ssh, pid=1074
[11:18:18.042] stderr> OpenSSH_9.6p1 Ubuntu-3ubuntu13.5, OpenSSL 3.0.13 30 Jan 2024
[11:18:18.271] stderr> debug1: Server host key: ssh-ed25519 SHA256:ygW1MvsTzQOO2tY/zuQRwDPdgCRkjEx/HbdeBg+pwTM
[11:18:18.272] stderr> Warning: Permanently added 'server.secureflag' (ED25519) to the list of known hosts.
[11:18:18.555] stderr> Authenticated to server.secureflag ([35.159.112.171]:22) using "publickey".
[11:18:18.694] > Welcome to Ubuntu 22.04.5 LTS (GNU/Linux 6.8.0-1018-aws x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/pro
> 
>  System information as of Thu Nov  7 11:18:12 AM UTC 2024
> 
>   System load:  0.77               Processes:             175
>   Usage of /:   11.2% of 96.73GB   Users logged in:       0
>   Memory usage: 1%                 IPv4 address for ens5: 172.31.24.191
>   Swap usage:   0%
> 
> 
> Expanded Security Maintenance for Applications is not enabled.
> 
> 0 updates can be applied immediately.
> 
> 1 additional security update can be applied with ESM Apps.
> Learn more about enabling ESM Apps service at https://ubuntu.com/esm
> 
> New release '24.04.1 LTS' available.
> Run 'do-release-upgrade' to upgrade to it.
> 
[11:18:18.725] > ready: 74faf03935a2
[11:18:18.758] > Linux 6.8.0-1018-aws #19~22.04.1-Ubuntu SMP Wed Oct  9 16:48:22 UTC 2024
[11:18:18.760] Platform: linux
[11:18:18.793] > /bin/bash
[11:18:18.794] Parent Shell: bash
[11:18:18.794] Parent Shell pid: 1066
[11:18:18.817] > 1073
[11:18:18.817] Waiting for pid of spawned 'sh' subshell: '1073'...
[11:18:18.862] > 74faf03935a2: running
> Script executing under PID: 1073
[11:18:18.901] > Found existing installation at /home/sf/.vscode-server...
> Starting VS Code CLI...
> printenv:
[11:18:18.906] >     USER=sf
>     SSH_CLIENT=145.224.72.139 29285 22
>     XDG_SESSION_TYPE=tty
>     SHLVL=1
>     MOTD_SHOWN=pam
>     HOME=/home/sf
>     LC_CTYPE=C.UTF-8
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
>     LOGNAME=sf
>     _=/usr/bin/sh
>     XDG_SESSION_CLASS=user
>     XDG_SESSION_ID=4
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
>     XDG_RUNTIME_DIR=/run/user/1000
>     LANG=en_US.UTF-8
>     SHELL=/bin/bash
>     PWD=/home/sf
>     SSH_CONNECTION=145.224.72.139 29285 172.31.24.191 22
>     XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
> Spawned remote CLI: 1090
> Waiting for server log...
[11:18:18.942] > Waiting for server log...
[11:18:18.978] > Waiting for server log...
[11:18:19.005] > Waiting for server log...
[11:18:19.038] > Waiting for server log...
[11:18:19.070] > Waiting for server log...
[11:18:19.102] > Waiting for server log...
[11:18:19.133] > Waiting for server log...
[11:18:19.166] > Waiting for server log...
[11:18:19.199] > Waiting for server log...
[11:18:19.230] > Waiting for server log...
[11:18:19.265] > Waiting for server log...
[11:18:19.298] > Waiting for server log...
[11:18:19.329] > Waiting for server log...
[11:18:19.363] > Waiting for server log...
[11:18:19.391] > 74faf03935a2: start
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> serverStartTime==485==
> execServerToken==aa1a1111-a1a1-1111-a111-111aa11a1111==
> platformDownloadPath==cli-alpine-x64==
> 74faf03935a2: end
[11:18:19.391] Received install output: 
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
serverStartTime==485==
execServerToken==aa1a1111-a1a1-1111-a111-111aa11a1111==
platformDownloadPath==cli-alpine-x64==

[11:18:19.393] Failed to parse remote port from server output
[11:18:19.393] Terminating local server
[11:18:19.397] Resolver error: Error: 
	at v.Create (/home/sf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:493431)
	at t.handleInstallOutput (/home/sf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:490753)
	at e (/home/sf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:545236)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /home/sf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:567561
	at async t.withShowDetailsEvent (/home/sf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:571256)
	at async /home/sf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:541941
	at async T (/home/sf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:539992)
	at async t.resolveWithLocalServer (/home/sf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:541481)
	at async P (/home/sf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:564693)
	at async t.resolve (/home/sf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:568667)
	at async /home/sf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.115.0/out/extension.js:2:839059
[11:18:19.403] ------




[11:18:19.414] Local server exit: 15
```

</p>
</details>

**Comment by SecureFlag-Aedan** [comment]
Nope neither drives are network shares, permissions are correct and there seems to be no issue with writing to the location.

The reason for the double ec2 is one is a "server" and one is an rdp de where vscode is installed and used from anywhere along with other tools. This is unfortunately non negotiable. 

The only info in the log on the first connection is:

```shell
$ cat ~/.vscode-server/.cli.65edc4939843c90c34d61f4ce11704f09d3e5cb6.log 
Listening on 127.0.0.1:42719
```

Where as the second time around it is:
```shell
$ cat ~/.vscode-server/.cli.65edc4939843c90c34d61f4ce11704f09d3e5cb6.log 
Listening on 127.0.0.1:39591
looking for token 59d6d9e1-43f1-45a1-bde0-f9d9c3e58ae1, got Some("59d6d9e1-43f1-45a1-bde0-f9d9c3e58ae1")
[2024-11-11 06:12:14] info Checking /home/sf-remote/.vscode-server/cli/servers/Stable-65edc4939843c90c34d61f4ce11704f09d3e5cb6/log.txt and /home/sf-remote/.vscode-server/cli/servers/Stable-65edc4939843c90c34d61f4ce11704f09d3e5cb6/pid.txt for a running server...
[2024-11-11 06:12:14] info Disposed of connection to running server.
[2024-11-11 06:12:14] info Starting server...
[2024-11-11 06:12:27] info Server started
```

**Comment by SecureFlag-Aedan** [comment]
It is indeed a disk issue due to speed on start up there is a delay on reading and writing to disk, waiting for this to be fine solves the connection problem in vscode...
