### ISSUE TITLE
pylance extension does not install to devcontainer (most of the time)

### ISSUE THREAD

**Issue by omlnaut** [microsoft/vscode-remote-release#10473]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.91.1
- OS Version: Windows
- devcontainer version: v0.375.1
- docker version: v4.32.0

The python extension sometimes fails to install into a devcontainer, but not always. I tried narrowing down a specific combination of extensions that causes this, but couldn't find any. I.e. the error occurs when ms-python.python and eamodio.gitlens are the only extensions active. But then again, sometimes it just works to install both.

Steps to Reproduce:

1. Initialize a devcontainer configuration pointing to a local docker file (which derives from python:3.11-bookworm)
2. Add list of extensions to .devcontainer.json (see below)
3. "Rebuilt without cache" a couple of times. Most of the time it fails to install debugpy (and the whole python extension as a result)

List of extensions:
			"extensions": [
				"ms-python.python",
				"ms-toolsai.jupyter",
				"ms-python.black-formatter",
				"mhutchie.git-graph",
				"github.copilot",
				"github.copilot-chat",
				"felipecaputo.git-project-manager",
				"gitlab.gitlab-workflow",
				"eamodio.gitlens"
			]

When the installation fails, the log shows:
[27774 ms] rejected promise not handled within 1 second: Extract: ENOENT: no such file or directory, open '/root/.vscode-server/extensionsCache/ms-python.vscode-pylance-2024.7.1'
stack trace: Error: ENOENT: no such file or directory, open '/root/.vscode-server/extensionsCache/ms-python.vscode-pylance-2024.7.1'
    at v (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/out/vs/server/node/server.main.js:106:25808)
    at /vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/out/vs/server/node/server.main.js:106:27251
    at /vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/node_modules/yauzl/index.js:37:21
    at FSReqCallback.oncomplete (node:fs:191:23)
[27775 ms] [11:30:02] Error: ENOENT: no such file or directory, open '/root/.vscode-server/extensionsCache/ms-python.vscode-pylance-2024.7.1'
    at v (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/out/vs/server/node/server.main.js:106:25808)
    at /vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/out/vs/server/node/server.main.js:106:27251
    at /vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/node_modules/yauzl/index.js:37:21
    at FSReqCallback.oncomplete (node:fs:191:23) {
  code: 'Extract',
  name: 'Extract'
}

[32298 ms] [11:30:06] Error while installing extensions: ENOENT: no such file or directory, open '/root/.vscode-server/extensionsCache/ms-python.vscode-pylance-2024.7.1'
[32300 ms] [11:30:06] Error: ENOENT: no such file or directory, open '/root/.vscode-server/extensionsCache/ms-python.vscode-pylance-2024.7.1'
    at v (/vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/out/vs/server/node/server.main.js:106:25808)
    at /vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/out/vs/server/node/server.main.js:106:27251
    at /vscode/vscode-server/bin/linux-x64/f1e16e1e6214d7c44d078b1f0607b2388f29d729/node_modules/yauzl/index.js:37:21
    at FSReqCallback.oncomplete (node:fs:191:23) {
  code: 'Extract',
  name: 'Extract'
}

**Comment by goksgie** [comment]
```
ls -la /home/vscode/.vscode-server/extensionsCache/ | wc -l
22

ls -la /home/vscode/.vscode-server/extensionsCache/ | grep python
lrwxrwxrwx 1 vscode vscode        74 Nov 15 22:31 ms-python.python-2024.20.0-linux-x64 -> /vscode/vscode-server/extensionsCache/ms-python.python-2024.20.0-linux-x64
```

```
[122160 ms] [22:31:54] Error while installing extensions: ENOENT: no such file or directory, open '/home/vscode/.vscode-server/extensionsCache/ms-python.vscode-pylance-2024.11.2', ENOENT: no such file or directory, open '/home/vscode/.vscode-server/extensionsCache/ms-python.debugpy-2024.12.0-linux-x64', ENOENT: no such file or directory, open '/home/vscode/.vscode-server/extensionsCache/ms-vscode.cmake-tools-1.19.52'
[122161 ms] [22:31:54] Extract: ENOENT: no such file or directory, open '/home/vscode/.vscode-server/extensionsCache/ms-python.vscode-pylance-2024.11.2', ENOENT: no such file or directory, open '/home/vscode/.vscode-server/extensionsCache/ms-python.debugpy-2024.12.0-linux-x64', ENOENT: no such file or directory, open '/home/vscode/.vscode-server/extensionsCache/ms-vscode.cmake-tools-1.19.52'
    at Oc.M (file:///vscode/vscode-server/bin/linux-x64/e8653663e8840adaf45af01eab5c627a5af81807/out/server-main.js:50:15944)
    at async Oc.I (file:///vscode/vscode-server/bin/linux-x64/e8653663e8840adaf45af01eab5c627a5af81807/out/server-main.js:50:11861)
    at async Oc.installGalleryExtensions (file:///vscode/vscode-server/bin/linux-x64/e8653663e8840adaf45af01eab5c627a5af81807/out/server-main.js:50:7237)
    at async zc.g (file:///vscode/vscode-server/bin/linux-x64/e8653663e8840adaf45af01eab5c627a5af81807/out/server-main.js:64:591)
    at async zc.installExtensions (file:///vscode/vscode-server/bin/linux-x64/e8653663e8840adaf45af01eab5c627a5af81807/out/server-main.js:63:35244) {
  code: 'Extract'
}
```

**Comment by chrmarti** [comment]
We prune `/vscode/vscode-server/extensionsCache` at 50 entries, which is too little. A usage based clean up strategy would be better, but this needs more thought. I will increase this limit to 500 for now.
