### ISSUE TITLE
[Remote-SSH Bug]:

### ISSUE THREAD

**Issue by kelvinlord** [microsoft/vscode-remote-release#10489]
### Is there an existing issue for this bug?

- [x] I have searched the existing issues

### Required Troubleshooting Steps

- [x] I have followed these troubleshooting steps
- [x] I have tried both values of the `remote.SSH.useLocalServer` setting [(more info here)](https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting#troubleshooting-steps)

### Connect Locally

It doesn’t connect successfully (same error message)

### ->

I tried many times to connect to my windows system desktop using my Macbook air remotely and the same issues occurs, the connection seems successful cause I can find a@DESKTOP-GLPJ173 C:\Users\A> in terminal but it always stuck at setting up ssh host and I tried many times, the same problem occurs

### Remote-SSH Log

[01:55:43.657] Got password response
[01:55:43.657] Interactor gave response: **************
[01:55:43.658] Cleaning up other-window auth server
[01:55:43.767] stderr> Authenticated to 2.tcp.cpolar.cn ([198.18.0.94]:12368) using "password".
[01:55:43.939] > Microsoft Windows [�汾 10.0.19045.4780]
> (c) Microsoft Corporation����������Ȩ����
> 
> a@DESKTOP-GLPJ173 C:\Users\A>
[01:55:43.989] > echo 'ready: c90291ca5072'
> 'ready: c90291ca5072'
> 
> a@DESKTOP-GLPJ173 C:\Users\A>
[01:55:44.063] > uname -rsv
> 
> a@DESKTOP-GLPJ173 C:\Users\A>
[01:55:44.064] Platform: windows
[01:55:44.064] Remote command length: 8208/8192 characters
[01:55:44.149] > powershell -NoProfile
> 
> a@DESKTOP-GLPJ173 C:\Users\A>
[01:55:44.151] stderr> 'powershell' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
[01:55:44.151] stderr> ���������ļ���

**Comment by kelvinlord** [comment]
I tried ssh the same command in bash and it works I connected successfully

**Comment by kelvinlord** [comment]
Got some new clues for the error:

[15:21:54.038] > 'powershell' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
> ���������ļ���
[15:21:55.666] "install" terminal command done
[15:21:55.666] Install terminal quit with output: ���������ļ���
[15:21:55.666] Received install output: ���������ļ���
[15:21:55.667] Failed to parse remote port from server output
[15:21:55.668] Resolver error: Error: 
	at v.Create (c:\Users\29440\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.1\out\extension.js:2:493431)
	at t.handleInstallOutput (c:\Users\29440\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.1\out\extension.js:2:490753)
	at t.tryInstall (c:\Users\29440\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.1\out\extension.js:2:608797)
	at async c:\Users\29440\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.1\out\extension.js:2:568008
	at async t.withShowDetailsEvent (c:\Users\29440\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.1\out\extension.js:2:571256)
	at async P (c:\Users\29440\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.1\out\extension.js:2:564794)
	at async t.resolve (c:\Users\29440\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.1\out\extension.js:2:568667)
	at async c:\Users\29440\.vscode\extensions\ms-vscode-remote.remote-ssh-0.115.1\out\extension.js:2:839059
[15:21:55.672] ------

**Comment by joshspicer** [comment]
Could you please attach your entire SSH log demonstrating this issue?

Additionally, could you try manually ssh'ing (from your terminal) and see if the issue reproduces. The exact command should be somewhere in your log (can try searching for `ssh.exe`)
