### ISSUE TITLE
Error while starting DevContainers on Windows 11, works fine on Mac and Linux.

### ISSUE THREAD

**Issue by picarro-ajain** [microsoft/vscode-remote-release#10498]
I have a private repository with all files in LF endings. Cloning the repository on Linux/Mac and then running the devcontainers works fine. On Windows 11, it was working on Day 1, but suddenly stopped working citing failure to build DevContainers. The specific error that happens every time I build DCs is:-

```bash
[2024-11-24T00:13:04.031Z] ERROR: parsing time "2024-11-23T01:42:26Z\x0a\x0d\x0a": extra text: "\x0a\x0d\x0a"
```

### What I have tried:-

- [x] tried `dos2unix` to make sure all files on Windows repository are LF endings.
- [x] Tried reinstalling DevContainers extension
- [x] Tried reinstalling VSCode
- [x] Tried restarting WSL
- [x] Tried restarting Docker Desktop(v4.35.1)
- [x] Tried deleting AppData items - Temp, Code, and reinstalling Code, and DevContainers.

### Complete logs are as follows:
```
[2024-11-24T00:13:02.455Z] Dev Containers 0.388.0 in VS Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813).
[2024-11-24T00:13:02.455Z] Start: Resolving Remote
[2024-11-24T00:13:02.485Z] Setting up container for folder or workspace: c:\Users\ajain\Documents\repos\pcubed-backend-api
[2024-11-24T00:13:02.486Z] Context: desktop-linux
[2024-11-24T00:13:02.487Z] Start: Run: wsl -l -v
[2024-11-24T00:13:02.548Z] Stop (61 ms): Run: wsl -l -v
[2024-11-24T00:13:02.549Z] Start: Run: wsl -d docker-desktop -e /bin/sh -c echo ~
[2024-11-24T00:13:02.658Z] Stop (109 ms): Run: wsl -d docker-desktop -e /bin/sh -c echo ~
[2024-11-24T00:13:02.660Z] Start: Run: wsl -d docker-desktop -e /bin/sh -c cd '/root' && /bin/sh
[2024-11-24T00:13:02.665Z] Start: Run in host: id -un
[2024-11-24T00:13:02.720Z] root
[2024-11-24T00:13:02.720Z] 
[2024-11-24T00:13:02.720Z] Stop (55 ms): Run in host: id -un
[2024-11-24T00:13:02.720Z] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true)
[2024-11-24T00:13:02.722Z] Stop (2 ms): Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true)
[2024-11-24T00:13:02.722Z] Start: Run in host: echo ~
[2024-11-24T00:13:02.723Z] /root
[2024-11-24T00:13:02.723Z] 
[2024-11-24T00:13:02.723Z] Stop (1 ms): Run in host: echo ~
[2024-11-24T00:13:02.723Z] Start: Run in host: test -f '/root/.vscode-server/cli/servers/Stable-f1a4fb101478ce6ec82fe9627c43efbf9e98c813/server/node'
[2024-11-24T00:13:02.724Z] 
[2024-11-24T00:13:02.724Z] 
[2024-11-24T00:13:02.724Z] Exit code 1
[2024-11-24T00:13:02.724Z] Stop (1 ms): Run in host: test -f '/root/.vscode-server/cli/servers/Stable-f1a4fb101478ce6ec82fe9627c43efbf9e98c813/server/node'
[2024-11-24T00:13:02.725Z] Start: Run in host: test -f '/root/.vscode/cli/servers/Stable-f1a4fb101478ce6ec82fe9627c43efbf9e98c813/server/node'
[2024-11-24T00:13:02.725Z] 
[2024-11-24T00:13:02.725Z] 
[2024-11-24T00:13:02.725Z] Exit code 1
[2024-11-24T00:13:02.726Z] Stop (1 ms): Run in host: test -f '/root/.vscode/cli/servers/Stable-f1a4fb101478ce6ec82fe9627c43efbf9e98c813/server/node'
[2024-11-24T00:13:02.726Z] Start: Run in host: test -f '/root/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/node'
[2024-11-24T00:13:02.726Z] 
[2024-11-24T00:13:02.726Z] 
[2024-11-24T00:13:02.726Z] Exit code 1
[2024-11-24T00:13:02.726Z] Stop (0 ms): Run in host: test -f '/root/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/node'
[2024-11-24T00:13:02.727Z] Start: Run in host: test -f '/root/.vscode-remote-containers/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/node'
[2024-11-24T00:13:02.727Z] 
[2024-11-24T00:13:02.727Z] 
[2024-11-24T00:13:02.727Z] Stop (0 ms): Run in host: test -f '/root/.vscode-remote-containers/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/node'
[2024-11-24T00:13:02.727Z] Start: Run in host: test -f '/root/.vscode-remote-containers/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/node_modules/node-pty/package.json'
[2024-11-24T00:13:02.728Z] 
[2024-11-24T00:13:02.728Z] 
[2024-11-24T00:13:02.728Z] Stop (1 ms): Run in host: test -f '/root/.vscode-remote-containers/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/node_modules/node-pty/package.json'
[2024-11-24T00:13:02.728Z] Start: Run in host: test -f '/root/.vscode-remote-containers/dist/vscode-remote-containers-server-0.388.0.js'
[2024-11-24T00:13:02.729Z] 
[2024-11-24T00:13:02.729Z] 
[2024-11-24T00:13:02.729Z] Stop (1 ms): Run in host: test -f '/root/.vscode-remote-containers/dist/vscode-remote-containers-server-0.388.0.js'
[2024-11-24T00:13:02.732Z] Host server: /bin/sh: /root/.vscode-remote-containers/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/node: not found
[2024-11-24T00:13:02.732Z] userEnvProbe: loginInteractiveShell (default)
[2024-11-24T00:13:02.733Z] userEnvProbe: not found in cache
[2024-11-24T00:13:02.733Z] userEnvProbe shell: /bin/sh
[2024-11-24T00:13:02.768Z] Error reading shell environment.
[2024-11-24T00:13:02.769Z] Error: stream ended with:0 but wanted:9
	at l (c:\Users\ajain\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\extension\extension.js:27:22149)
	at c:\Users\ajain\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\extension\extension.js:27:22330
	at s (c:\Users\ajain\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\extension\extension.js:30:5371)
	at Socket.<anonymous> (c:\Users\ajain\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\extension\extension.js:30:5541)
	at Socket.emit (node:events:531:35)
	at endReadableNT (node:internal/streams/readable:1696:12)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[2024-11-24T00:13:02.769Z] Could not connect to WSL.
[2024-11-24T00:13:02.769Z] stream is closed
[2024-11-24T00:13:02.769Z] Stop (109 ms): Run: wsl -d docker-desktop -e /bin/sh -c cd '/root' && /bin/sh
[2024-11-24T00:13:02.770Z] Host server terminated (code: 127, signal: null).
[2024-11-24T00:13:02.771Z] Start: Check Docker is running
[2024-11-24T00:13:02.772Z] Start: Run: docker version
[2024-11-24T00:13:02.843Z] Client:
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:42:27 2024
 OS/Arch:           windows/amd64
 Context:           desktop-linux

[2024-11-24T00:13:02.843Z] Server: Docker Desktop 4.35.1 (173168)
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:11 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.21
  GitCommit:        472731909fa34bd7bc9c087e4c27943f9835f111
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
[2024-11-24T00:13:02.849Z] Stop (77 ms): Run: docker version
[2024-11-24T00:13:02.850Z] Stop (79 ms): Check Docker is running
[2024-11-24T00:13:02.851Z] Start: Run: docker volume ls -q
[2024-11-24T00:13:02.921Z] Stop (70 ms): Run: docker volume ls -q
[2024-11-24T00:13:02.921Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=c:\Users\ajain\Documents\repos\pcubed-backend-api --filter label=vsch.quality=stable
[2024-11-24T00:13:02.989Z] Stop (68 ms): Run: docker ps -q -a --filter label=vsch.local.folder=c:\Users\ajain\Documents\repos\pcubed-backend-api --filter label=vsch.quality=stable
[2024-11-24T00:13:02.990Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\ajain\Documents\repos\pcubed-backend-api --filter label=devcontainer.config_file=c:\Users\ajain\Documents\repos\pcubed-backend-api\.devcontainer\devcontainer.json
[2024-11-24T00:13:03.058Z] Stop (68 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\ajain\Documents\repos\pcubed-backend-api --filter label=devcontainer.config_file=c:\Users\ajain\Documents\repos\pcubed-backend-api\.devcontainer\devcontainer.json
[2024-11-24T00:13:03.058Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\ajain\Documents\repos\pcubed-backend-api
[2024-11-24T00:13:03.127Z] Stop (69 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\ajain\Documents\repos\pcubed-backend-api
[2024-11-24T00:13:03.127Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\ajain\Documents\repos\pcubed-backend-api
[2024-11-24T00:13:03.194Z] Stop (67 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\ajain\Documents\repos\pcubed-backend-api
[2024-11-24T00:13:03.195Z] Running Dev Containers CLI:   up --user-data-folder c:\Users\ajain\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-bb779e26-1ea2-4973-b8fb-dae3ce2433a81732407181560 --workspace-folder c:\Users\ajain\Documents\repos\pcubed-backend-api --workspace-mount-consistency cached --gpu-availability detect --id-label devcontainer.local_folder=c:\Users\ajain\Documents\repos\pcubed-backend-api --id-label devcontainer.config_file=c:\Users\ajain\Documents\repos\pcubed-backend-api\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\ajain\Documents\repos\pcubed-backend-api\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[2024-11-24T00:13:03.201Z] ProxyResolver#loadSystemCertificates count
[2024-11-24T00:13:03.203Z] ProxyResolver#loadSystemCertificates count filtered
[2024-11-24T00:13:03.203Z] Start: Run: C:\Users\ajain\AppData\Local\Programs\Microsoft VS Code\Code.exe c:\Users\ajain\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\ajain\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-bb779e26-1ea2-4973-b8fb-dae3ce2433a81732407181560 --workspace-folder c:\Users\ajain\Documents\repos\pcubed-backend-api --workspace-mount-consistency cached --gpu-availability detect --id-label devcontainer.local_folder=c:\Users\ajain\Documents\repos\pcubed-backend-api --id-label devcontainer.config_file=c:\Users\ajain\Documents\repos\pcubed-backend-api\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\ajain\Documents\repos\pcubed-backend-api\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[2024-11-24T00:13:03.429Z] @devcontainers/cli 0.71.0. Node.js v20.18.0. win32 10.0.26100 x64.
[2024-11-24T00:13:03.429Z] Start: Run: docker buildx version
[2024-11-24T00:13:03.565Z] Stop (136 ms): Run: docker buildx version
[2024-11-24T00:13:03.566Z] github.com/docker/buildx v0.17.1-desktop.1 1a2ee7e8d945b88fdc18f1948da491c2f540dec9
[2024-11-24T00:13:03.566Z] 
[2024-11-24T00:13:03.566Z] Start: Run: docker -v
[2024-11-24T00:13:03.624Z] Stop (58 ms): Run: docker -v
[2024-11-24T00:13:03.624Z] Start: Resolving Remote
[2024-11-24T00:13:03.630Z] Loading 35 extra certificates from C:\Users\ajain\AppData\Local\Temp\vsch\certificates-25424df9a359621a2c454f7c4066dd89d58993cd45ea6feb0d66e279f4b669c3.pem.
[2024-11-24T00:13:03.705Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\ajain\Documents\repos\pcubed-backend-api --filter label=devcontainer.config_file=c:\Users\ajain\Documents\repos\pcubed-backend-api\.devcontainer\devcontainer.json
[2024-11-24T00:13:03.769Z] Stop (64 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\ajain\Documents\repos\pcubed-backend-api --filter label=devcontainer.config_file=c:\Users\ajain\Documents\repos\pcubed-backend-api\.devcontainer\devcontainer.json
[2024-11-24T00:13:03.772Z] Start: Run: docker inspect --type image python:3.9-slim-buster
[2024-11-24T00:13:03.836Z] Stop (64 ms): Run: docker inspect --type image python:3.9-slim-buster
[2024-11-24T00:13:03.839Z] Start: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\ajain\AppData\Local\Temp\devcontainercli\container-features\0.71.0-1732407183837\Dockerfile-with-features -t vsc-pcubed-backend-api-66c23f6cdee1e230e8368f2d11866f6c2a96da580fa7b807192f63fb022776a4 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label c:\Users\ajain\Documents\repos\pcubed-backend-api
[2024-11-24T00:13:03.969Z] 
[2024-11-24T00:13:04.031Z] ERROR: parsing time "2024-11-23T01:42:26Z\x0a\x0d\x0a": extra text: "\x0a\x0d\x0
a"
[2024-11-24T00:13:04.094Z] Stop (255 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\ajain\AppData\Local\Temp\devcontainercli\container-features\0.71.0-1732407183837\Dockerfile-with-features -t vsc-pcubed-backend-api-66c23f6cdee1e230e8368f2d11866f6c2a96da580fa7b807192f63fb022776a4 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label c:\Users\ajain\Documents\repos\pcubed-backend-api
[2024-11-24T00:13:04.100Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\ajain\AppData\Local\Temp\devcontainercli\container-features\0.71.0-1732407183837\Dockerfile-with-features -t vsc-pcubed-backend-api-66c23f6cdee1e230e8368f2d11866f6c2a96da580fa7b807192f63fb022776a4 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label c:\Users\ajain\Documents\repos\pcubed-backend-api
[2024-11-24T00:13:04.100Z]     at RtA (c:\Users\ajain\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\spec-node\devContainersSpecCLI.js:466:1933)
[2024-11-24T00:13:04.101Z]     at async _m (c:\Users\ajain\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\spec-node\devContainersSpecCLI.js:465:1896)
[2024-11-24T00:13:04.101Z]     at async bH (c:\Users\ajain\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\spec-node\devContainersSpecCLI.js:465:610)
[2024-11-24T00:13:04.101Z]     at async TtA (c:\Users\ajain\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\spec-node\devContainersSpecCLI.js:482:3848)
[2024-11-24T00:13:04.101Z]     at async iB (c:\Users\ajain\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\spec-node\devContainersSpecCLI.js:482:4963)
[2024-11-24T00:13:04.101Z]     at async wrA (c:\Users\ajain\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\spec-node\devContainersSpecCLI.js:663:203)
[2024-11-24T00:13:04.101Z]     at async DrA (c:\Users\ajain\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\spec-node\devContainersSpecCLI.js:662:14830)
[2024-11-24T00:13:04.101Z]     at async c:\Users\ajain\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\spec-node\devContainersSpecCLI.js:482:1190
[2024-11-24T00:13:04.111Z] Stop (908 ms): Run: C:\Users\ajain\AppData\Local\Programs\Microsoft VS Code\Code.exe c:\Users\ajain\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\ajain\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-bb779e26-1ea2-4973-b8fb-dae3ce2433a81732407181560 --workspace-folder c:\Users\ajain\Documents\repos\pcubed-backend-api --workspace-mount-consistency cached --gpu-availability detect --id-label devcontainer.local_folder=c:\Users\ajain\Documents\repos\pcubed-backend-api --id-label devcontainer.config_file=c:\Users\ajain\Documents\repos\pcubed-backend-api\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\ajain\Documents\repos\pcubed-backend-api\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[2024-11-24T00:13:04.112Z] Exit code 1
[2024-11-24T00:13:04.115Z] Command failed: C:\Users\ajain\AppData\Local\Programs\Microsoft VS Code\Code.exe c:\Users\ajain\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\ajain\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-bb779e26-1ea2-4973-b8fb-dae3ce2433a81732407181560 --workspace-folder c:\Users\ajain\Documents\repos\pcubed-backend-api --workspace-mount-consistency cached --gpu-availability detect --id-label devcontainer.local_folder=c:\Users\ajain\Documents\repos\pcubed-backend-api --id-label devcontainer.config_file=c:\Users\ajain\Documents\repos\pcubed-backend-api\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\ajain\Documents\repos\pcubed-backend-api\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[2024-11-24T00:13:04.115Z] Exit code 1

```

**Comment by chrmarti** [comment]
Is that timestamp in the `Dockerfile-with-features` mentioned in the command before the error?

If this is an issue with one of the Docker caches, a factory reset of Docker Desktop might help.

**Comment by picarro-ajain** [comment]
@chrmarti For now,

1. I started the VS Code on WSL with Ubuntu distro, and downloaded the repositories there and launched the DevContainer from there. This worked, probably because now the repositories are downloaded on a Linux subsystem, and hence there aren't any Cross-OS issues.

2. I am keeping the Docker Desktop factory reset for later, as I'm on a company project, and any such experiments may impact the project timelines.

We can say, we have a workaround for now. Let me know, if the issue could be closed, and also suggest what would be a good label for closing it.

**Comment by chrmarti** [comment]
Sounds good. Let us know, preferably in a new issue, when you have more information we can look into. Thanks.
