### ISSUE TITLE
Saving files causes them to close

### ISSUE THREAD

**Issue by rafjohnson** [microsoft/vscode-remote-release#10519]
Type: <b>Bug</b>

Happens somewhat randomly, so I'm not able to replicate on command, but occasionally, about half the time I connect to the remote system, when I save any file, all open files will close. This happens when using ctrl+s, or File > Save. Always happens while connected to remote system. Local (on same subnet) or Remote (on different subnet) doesn't seem to matter, nor does file type (text, tek, .md, .r, .c, .h).  I have no macros or additional keyboard shortcuts mapped to ctrl+s, and this only happens when connected to the remote server. 

The only solution is to restart the remote session by closing and re-opening VSCode.

The only trigger I can seem to notice is if I have started a session, but haven't interacted with it recently, within about a half hour, it will sometimes start doing this. But I've also had it start immediately upon a connect from a fresh VSCode session. 

I was connecting via SSH Password, but I have switched to a certificate and that did not affect the behavior. 

I have found nothing in logs that indicates what's happening. 

Extension version: 0.115.1
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 6.10.10-100.fc39.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.83GB (12.03GB free)|
|Process Argv|--file-uri file:///c%3A/Users/rjohnson/Github/VTSUDataScience/VTSUDataScience.code-workspace --enable-proposed-api intersystems-community.vscode-objectscript --crash-reporter-id 1d31cad8-587b-45ad-9007-51f6bbbfe78f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.0.0.7|
|OS|Linux x64 6.10.10-100.fc39.x86_64|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700K (20 x 800)|
|Memory (System)|31.08GB (26.69GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31185842
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by joshspicer** [comment]
Thanks for taking the time to open an issue.  Could you please share your logs (`> Remote-SSH: Show Log` in the command palette) after reproducing the issue? Even if it doesn't point to the full issue, it will show your current settings, some remote environment metrics, etc...

Perhaps another extension is not functioning as expected? To rule that out, could you disable all extensions (except Remote - SSH) and see if the issue persists. Please also check other logs in the output channel (extension host, etc...), as that may point to something useful. Thanks!

**Comment by rafjohnson** [comment]
Sure! [VSCode-RemoteSSH.log](https://github.com/user-attachments/files/18068012/VSCode-RemoteSSH.log)

I think I've found another clue. I was able to make it happen by having a file open from one Github branch. I saved and commit to that branch, but didn't close the file (main.c). I then switch to a different branch, all within the same codebase, but those files don't exist on that branch. The file did not stay open when I switched branches. I see the following error in the "Window" log:

```
2024-12-09 16:13:59.370 [error] cannot open vscode-remote://ssh-remote%2B10.0.0.7/home/becky/Github/VTSUDataScience/CIS3052-DSA/Projects/Project6-Sorts/main.c. Detail: Unable to read file 'vscode-remote://ssh-remote+10.0.0.7/home/becky/Github/VTSUDataScience/CIS3052-DSA/Projects/Project6-Sorts/main.c' (Error: Unable to resolve nonexistent file 'vscode-remote://ssh-remote+10.0.0.7/home/becky/Github/VTSUDataScience/CIS3052-DSA/Projects/Project6-Sorts/main.c'): CodeExpectedError: cannot open vscode-remote://ssh-remote%2B10.0.0.7/home/becky/Github/VTSUDataScience/CIS3052-DSA/Projects/Project6-Sorts/main.c. Detail: Unable to read file 'vscode-remote://ssh-remote+10.0.0.7/home/becky/Github/VTSUDataScience/CIS3052-DSA/Projects/Project6-Sorts/main.c' (Error: Unable to resolve nonexistent file 'vscode-remote://ssh-remote+10.0.0.7/home/becky/Github/VTSUDataScience/CIS3052-DSA/Projects/Project6-Sorts/main.c')
    at OFe.$tryOpenDocument (vscode-file://vscode-app/c:/users/rjohnson/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:615:8481)
```

The "main.c" file is the file I had open from the first branch. 

This error shows up each time I save, and any files I open from the 2nd branch closes. They do save, though. 

I just tried switching back to the first branch, and I'm able to save files without them closing. I then switched back to the 2nd branch, and the main.c file opened showing that it wasn't present in the branch (title in red and struck through).  I'm also able to save files without them closing, and the error doesn't show up. 

I've attached the Window Log. I didn't see any other logs that had updates when I saved.
[VSCode-Window.log](https://github.com/user-attachments/files/18068130/VSCode-Window.log)

**Comment by rafjohnson** [comment]
The issue happened again, but this time I saw this error in the Extension Host - Remote Exporer log: 
```
2025-01-02 10:38:11.867 [error] TypeError: Cannot read properties of undefined (reading 'uri')
    at /home/becky/.vscode-server/extensions/usama8800.tab-groups-2.1.1/out/extension.js:369:27
    at Generator.next (<anonymous>)
    at /home/becky/.vscode-server/extensions/usama8800.tab-groups-2.1.1/out/extension.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/becky/.vscode-server/extensions/usama8800.tab-groups-2.1.1/out/extension.js:4:12)
    at openTab (/home/becky/.vscode-server/extensions/usama8800.tab-groups-2.1.1/out/extension.js:365:12)
    at /home/becky/.vscode-server/extensions/usama8800.tab-groups-2.1.1/out/extension.js:355:23
    at Generator.next (<anonymous>)
    at fulfilled (/home/becky/.vscode-server/extensions/usama8800.tab-groups-2.1.1/out/extension.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I disabled the tab-groups extension and it didn't close when saving. To try to replicate it, I re-enabled the tab-groups extension, reloaded the extension host, and opened the file. It stayed open after saving. I then switched branches, the original file closed (rather than showing a red strikethrough) and I saw these errors in the log, repeating multiple times: 

```
2025-01-02 10:48:04.594 [error] CodeExpectedError: cannot open vscode-remote://ssh-remote%2B10.0.0.7/home/becky/Github/VTSUDataScience/PatientLookupProject/Doc.tex. Detail: Unable to read file 'vscode-remote://ssh-remote+10.0.0.7/home/becky/Github/VTSUDataScience/PatientLookupProject/Doc.tex' (Error: Unable to resolve nonexistent file 'vscode-remote://ssh-remote+10.0.0.7/home/becky/Github/VTSUDataScience/PatientLookupProject/Doc.tex')
    at hVe.$tryOpenDocument (vscode-file://vscode-app/c:/users/rjohnson/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:748:8481)
```

I uninstalled the tab-groups extension (https://marketplace.visualstudio.com/items?itemName=usama8800.tab-groups) and will monitor to see if it happens again. I think it may have been unintended consequences of that extension.

**Comment by joshspicer** [comment]
Thank you for the detailed follow up! I think you've solved it - but if you can reproduce without extensions enabled, please feel free to re-open.
