### ISSUE TITLE
Remote explorer crashing

### ISSUE THREAD

**Issue by powerlimit** [microsoft/vscode-remote-release#10554]
After updating vscode itself, I can no longer use the vscode remote explorer. The remote explorer browser is now empty and if I click on the refresh button it shows an error:

```
The tunnel request resulted in 403 status, but the request did not reach the tunnel service. This may indicate the domain 'global.rel.tunnels.api.visualstudio.com' is blocked by a firewall.
```

Connecting to my VMs via "File->Open Recent" does work though. And once I'm back in a devcontainer on one of my VMs the devcontainer selection of the remote explorer does also work. But the Tunnels/SSH does not work.

- VSCode Version: 1.96.0 (user setup)
- Local OS Version: Windows 10 22H2
- Remote OS Version: Ubuntu 2024
- Remote Extension/Connection Type: Remote explorer - Tunnels/SSH page.

- Logs: 
```
2024-12-12 09:24:38.292 [trace] ProxyResolver#tls.connect [{"session":"[object Object]","maxRedirects":21,"maxBodyLength":null,"protocol":"https:","path":"null","method":"GET","headers":"[object Object]","agents":"[object Object]","beforeRedirect":"[Function: ct]","beforeRedirects":"[object Object]","hostname":"global.rel.tunn[39 chars]","port":443,"agent":"[object Object]","nativeProtocols":"[object Object]","pathname":"/tunnels","search":"?includePorts=[106 chars]","_defaultAgent":"[object Object]","host":"global.rel.tunn[39 chars]","lookupProxyAuthorization":"[Function: bound dz]","noDelay":true,"servername":"global.rel.tunn[39 chars]","secureEndpoint":true,"_vscodeAdditionalCaCerts":"[47 certs]","keepAlive":true,"scheduling":"lifo","timeout":5000,"_agentKey":"global.rel.tunn[64 chars]","encoding":"null","keepAliveInitialDelay":1000}]
2024-12-12 09:24:38.430 [error] AxiosError: Request failed with status code 403
    at je (c:\Users\manuels\.vscode\extensions\ms-vscode.remote-server-1.5.2\dist\node\extension.js:2:951027)
    at IncomingMessage.<anonymous> (c:\Users\manuels\.vscode\extensions\ms-vscode.remote-server-1.5.2\dist\node\extension.js:2:963117)
    at IncomingMessage.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at At.request (c:\Users\manuels\.vscode\extensions\ms-vscode.remote-server-1.5.2\dist\node\extension.js:2:971833)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at E.axiosRequest (c:\Users\manuels\.vscode\extensions\ms-vscode.remote-server-1.5.2\dist\node\extension.js:2:75388)
    at E.request (c:\Users\manuels\.vscode\extensions\ms-vscode.remote-server-1.5.2\dist\node\extension.js:2:76034)
    at E.sendRequest (c:\Users\manuels\.vscode\extensions\ms-vscode.remote-server-1.5.2\dist\node\extension.js:2:69974)
    at E.listTunnels (c:\Users\manuels\.vscode\extensions\ms-vscode.remote-server-1.5.2\dist\node\extension.js:2:64683)
    at c:\Users\manuels\.vscode\extensions\ms-vscode.remote-server-1.5.2\dist\node\extension.js:2:1201977
    at cw.h (file:///c:/Users/manuels/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:32825)
    at async Promise.all (index 0)
    at t.RemoteTreeDataProvider.refreshTunnels (c:\Users\manuels\.vscode\extensions\ms-vscode.remote-explorer-0.4.3\dist\node\extension.js:1:7783)
    at async Promise.all (index 0) remote-tunnels.internal.getTunnelsList {"value":"ms-vscode.remote-server","_lower":"ms-vscode.remote-server"}
2024-12-12 09:24:38.431 [error] AxiosError: Request failed with status code 403
    at je (c:\Users\manuels\.vscode\extensions\ms-vscode.remote-server-1.5.2\dist\node\extension.js:2:951027)
    at IncomingMessage.<anonymous> (c:\Users\manuels\.vscode\extensions\ms-vscode.remote-server-1.5.2\dist\node\extension.js:2:963117)
    at IncomingMessage.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at At.request (c:\Users\manuels\.vscode\extensions\ms-vscode.remote-server-1.5.2\dist\node\extension.js:2:971833)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at E.axiosRequest (c:\Users\manuels\.vscode\extensions\ms-vscode.remote-server-1.5.2\dist\node\extension.js:2:75388)
    at E.request (c:\Users\manuels\.vscode\extensions\ms-vscode.remote-server-1.5.2\dist\node\extension.js:2:76034)
    at E.sendRequest (c:\Users\manuels\.vscode\extensions\ms-vscode.remote-server-1.5.2\dist\node\extension.js:2:69974)
    at E.listTunnels (c:\Users\manuels\.vscode\extensions\ms-vscode.remote-server-1.5.2\dist\node\extension.js:2:64683)
    at c:\Users\manuels\.vscode\extensions\ms-vscode.remote-server-1.5.2\dist\node\extension.js:2:1201977
    at cw.h (file:///c:/Users/manuels/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:32825)
    at async Promise.all (index 0)
    at t.RemoteTreeDataProvider.refreshTunnels (c:\Users\manuels\.vscode\extensions\ms-vscode.remote-explorer-0.4.3\dist\node\extension.js:1:7783)
    at async Promise.all (index 0) remote-explorer.refresh {"value":"ms-vscode.remote-explorer","_lower":"ms-vscode.remote-explorer"}
2024-12-12 09:24:38.431 [trace] forwarded error to extension? false {"value":"ms-vscode.remote-explorer","_lower":"ms-vscode.remote-explorer"}
```

Steps to Reproduce: 

1. Unclear, updated vscode itself. Everything was working fine yesterday. Looked at version of the remote extensions but they are on 0.26 which hasn't changed for a month. So, likely something in vscode itself. But presumably some _man in the middle_ issue my IT is causing. Cannot see what exactly to ask for in my fire wall exceptions ATM.

Does this issue occur when you try this locally?: No, happening on my local machine as well as on remote.
Does this issue occur when you try this locally and all extensions are disabled?: Not applicable

**Comment by connor4312** [comment]
Fixed in the next release
