### ISSUE TITLE
Inconsistent behaviour when switching from Dev Container to WSL folder (reopen in WSL)

### ISSUE THREAD

**Issue by SimonCahill** [microsoft/vscode-remote-release#10596]
As stated in the title, there is some inconsistent behaviour when switching between dev containers and WSL in my current version of VS Code (Code is Insiders branch).

Version info:
```
Version: 1.97.0-insider (user setup)
Commit: 89f808979a5151 bd91324e65d4f7ab1 b62896983
Date: (1 wk ago)
Electron: 322.6
ElectronBuildld: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
128.37438-electron.o
OS: Windows_NTx64 10.02635

// DevContainers
Identifier   ms-vscode-remote.remote-containers
Version      0.395.0
Last Updated 2024-12-11, 21:07:09

// WSL
Identifier   ms-vscode-remote.remote-wsl
Version      0.88.5
Last Updated 2024-11-07, 15:20:37
```

When hitting <key>F1</key> and entering "Reopen in WSL", the following menu shows up:

![Image](https://github.com/user-attachments/assets/4f20aaa6-cc3b-4d30-a77b-2cf379d18082)

hitting the suggested menu item causes an error message to display:
![Image](https://github.com/user-attachments/assets/5791d839-cfd3-4e0d-a6c6-8de2ac547c3c)

while producing the following logs:

```
2024-12-27 14:07:41.071 [error] TypeError: Cannot read properties of undefined (reading 'env')
	at Object.getEnv (c:\Users\simon\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.88.5\dist\node\extension.js:2:247350)
	at c:\Users\simon\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.88.5\dist\node\extension.js:2:267631
	at async t.getWSLExecServer (c:\Users\simon\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.88.5\dist\node\extension.js:2:267610)
	at async t.AuthorityResourceStore.get (c:\Users\simon\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.88.5\dist\node\extension.js:2:210477)
	at async c:\Users\simon\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.88.5\dist\node\extension.js:2:223145
	at async fw.h (file:///c:/Users/simon/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:32825) remote-wsl.reopenInWSL {"value":"ms-vscode-remote.remote-wsl","_lower":"ms-vscode-remote.remote-wsl"}
```

If, however, I use the `Remote` menu at the bottom-left of the window, the VS Code behaves as expected and reopens the folder "locally" (in WSL).

![Image](https://github.com/user-attachments/assets/efaf3d4f-0fa7-483c-b7ac-7af9e7e9c3c4)

![Image](https://github.com/user-attachments/assets/cdfd452a-4f46-4dbb-89d3-0a9dc6aafcc5)

> Note: Although I didn't explicitely show this in screenshots, using <key>F1</key> and explicitly hitting `Dev Containers: Reopen...` works as expected. This is an issue in the WSL remote extension.

**Comment by aeschli** [comment]
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/10159

The 'Reopen Folder in WSL' command should not be visible when in a Dev Container
