### ISSUE TITLE
Cannot use Python Refactor: Sort Imports when on Remote: SSH

### ISSUE THREAD

**Issue by juliussimonelli** [microsoft/vscode-remote-release#1223]
Issue Type: <b>Bug</b>

I don't know if this is a bug or a feature that hasn't been implemented yet in the remote release, but I thought I would create a Github issue for it. When I try to use the Python Refactor: Sort Imports feature in the Python package while on a Remote: SSH session, I get the following error:

```
Traceback (most recent call last): File "/root/.vscode-server/extensions/ms-python.python-2019.8.30787/pythonFiles/sortImports.py", line 11, in <module> import isort.main File "/root/.vscode-server/extensions/ms-python.python-2019.8.30787/pythonFiles/lib/python/isort/__init__.py", line 26, in <module> from .isort import SortImports # noqa: F401 File "/root/.vscode-server/extensions/ms-python.python-2019.8.30787/pythonFiles/lib/python/isort/isort.py", line 41, in <module> from .finders import FindersManager File "/root/.vscode-server/extensions/ms-python.python-2019.8.30787/pythonFiles/lib/python/isort/finders.py", line 35, in <module> from backports.functools_lru_cache import lru_cache ImportError: No module named functools_lru_cache
```

I don't have any issues when I use it outside of a Remote: SSH session.

Extension version: 0.45.5
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 3.10.0-693.2.2.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|-psn_0_6235634|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: localhost|
|OS|Linux x64 3.10.0-693.2.2.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (4 x 2118)|
|Memory (System)|59.81GB (56.03GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Please file this issue on the python extension. It sounds like there is some dependency missing for that extension.
