### ISSUE TITLE
Support Termux on Android/aarch64

### ISSUE THREAD

**Issue by killercup** [microsoft/vscode-remote-release#1338]
I have followed #69 and was excited to test this on my OnePlus 6 phone running the latest Android 9 release and [Termux](https://wiki.termux.com/wiki/Main_Page). On my Macbook, I'm running VSCode Insiders (dcc01858d3f75696568eb751238d01b30a1e7d33) as well as the most recent release of the "Remote - SSH (Nightly)" extension (2019.8.42660).

Since Termux is not a very Linux-y Linux, I have some issues getting the remote extension to install its toolchain correctly on the phone. Here's what I tried. I hope this is helpful and I would be delighted to get this work :)

1. I click on the bottom left "remote" icon, select "connect to ssh host", and select the phone from the list (I have it as an ssh alias)
2. A new window opens that after a while shows my a modal with

   > Could not establish connection to "oneplus6local". The VS Code Server failed to start.

   I select "More actions", but then close the panel to be able to view the "output" pane.
3. "Output" -> "Remote - SSH" ends with (full log below):

   > `/data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/server.sh: 12: /data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/server.sh: /data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/node: not found`

The path `/data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/node` seemed suspicious at first but [Termux does not follow the Filesystem Hierarchy Standard](https://wiki.termux.com/wiki/Differences_from_Linux), so maybe it is fine. Checking manually, this file exists indeed:

```console
$ ls -lah /data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/node
-rwx------ 1 u0_a289 u0_a289 38M Aug 30 18:41 /data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/node*
$ file /data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/node 
/data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/node: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=ba687b0f745c43aef53e42eec1b8b55e6ec9e9fe, with debug_info, not stripped
```

But executing it fails with

```console
Failed to execute process '/data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/node'. Reason:
The file '/data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/node' does not exist or could not be executed.
```

Now *that* is suspicious.

I have installed the current node.js LTS version (`pkg i nodejs-lts` gives me v10.16.3), which I can execute:

```console
$ node
> ![] + []
'false'
```

One of the differences between the `node` executable that the Remote SSH extension downloaded and the one from Termux' repo is that is that it is using `/system/bin/linker64` instead of `/lib/ld-linux-aarch64.so.1`:

```console
$ file (which node)
/data/data/com.termux/files/usr/bin/node: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker64, stripped
```

To test a hypothesis, I copied the working version over the other one and confirmed that it (unsurprisingly) still works:

```console
$ cp /data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/node
$ /data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/node
> ![] + []
'false'
```

Seemed like a good start. Let's try to connect again.

This time I get two error notifications:

- "Could not fetch remote environment"
- "Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused.)"

The log shows a few interesting pieces of information, though (see full log below, the one with "(2)"):

```console
[11:58:32.414] > Found existing installation at /data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33...
…
[11:58:32.652] Remote server is listening on port 41455
…
[11:58:32.653] Forwarding server listening on 56285
…
[11:58:32.654] Tunneled remote port 41455 to local port 56285
…
[11:58:32.655] [Forwarding server 56285] Got connection 0
[11:58:32.770] [Forwarding server 56285] Got connection 1
[11:58:32.770] [Forwarding server 56285] Got connection 2
```

Sadly that is where the log ends, with the remote extension still not connecting. Looking at the `~/.vscode-server-insiders` directory, however, I saw there was a `.log` file! And it had this interesting snippet in it (full log below):

```console
[…] dlopen failed: library "libstdc++.so.6" not found […]
…
Unable to retrieve mac address (Error: Command failed: /sbin/ifconfig -a || /sbin/ip link
/data/data/com.termux/files/usr/bin/sh: 1: /sbin/ifconfig: Permission denied
/data/data/com.termux/files/usr/bin/sh: 1: /sbin/ip: Permission denied
)
```

Not sure about the dy lib, but since node exists for Alpine, I assume it can be statically linked, too. Fo the network tools, I can indeed not execute either of these:

```console
$ /sbin/ifconfig
fish: The file '/sbin/ifconfig' is not executable by this user
$ /sbin/ip
fish: The file '/sbin/ip' is not executable by this user
```

This is where the weird file system layout comes in again: Both tools exist and executable, but they are in `/data/data/com.termux/files/usr/bin/`.

Since I don't know where this code is executed, and this issue is long enough already, I'm gonna stop here. My next step would be to add `|| /data/data/com.termux/files/usr/bin/ip link` to the erroring line.

- - -

<details>
<summary>Full "Remote - SSH" log (1)</summary>

```console
[11:40:09.598] remote-ssh-nightly@2019.8.42660
[11:40:09.598] darwin x64
[11:40:09.599] SSH Resolver called for "ssh-remote+oneplus6local", attempt 1
[11:40:09.599] SSH Resolver called for host: oneplus6local
[11:40:09.599] Setting up SSH remote "oneplus6local"
[11:40:09.613] Using commit id "dcc01858d3f75696568eb751238d01b30a1e7d33" and quality "insider" for server
[11:40:09.621] Testing ssh with ssh -V
[11:40:09.643] ssh exited with code: 0
[11:40:09.643] Got stderr from ssh: OpenSSH_7.8p1, LibreSSL 2.6.2
[11:40:09.644] Running script with connection command: ssh -D 56203 -o ConnectTimeout=15 oneplus6local bash
[11:40:09.644] Install and start server if needed
[11:40:10.553] > Running remote connection script
> Acquiring lock on /data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/vscode-remote-lock.dcc01858d3f75696568eb751238d01b30a1e7d33
[11:40:10.553] Got some output, clearing connection timeout
[11:40:10.591] > Installing to /data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33...
[11:40:10.592] > Downloading with curl
>   % Tota
[11:40:10.593] > l    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[11:40:10.746] >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[11:40:12.030] >   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
[11:40:12.037] > 100   134  100   134    0     0     92      0  0:00:01  0:00:01 --:--:--    92
[11:40:12.819] > 
[11:40:12.820] >   0
[11:40:12.822] > 2
[11:40:12.827] > 8.0M    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
[11:40:13.830] > 
[11:40:13.831] >  44 28.0M   44 12.4M    0     0  4036k      0  0:00:07  0:00:03  0:00:04 13.4M
[11:40:14.746] > 
[11:40:14.748] >  95 28.0M   95 26.8M    0     0  6606k      0  0:00:04  0:00:04 --:--:-- 13.9M
[11:40:14.809] > 100 
[11:40:14.810] > 28.0M  100 28.0M    0     0  6792k      0  0:00:04  0:00:04 --:--:-- 14.0M
[11:40:14.825] > Download complete
[11:40:16.389] > SHELL=/data/data/com.termux/files/usr/bin/fish
> LESS=--RAW-CONTROL-CHARS
> LANGUAGE=en_US.UTF-8
> PREFIX=/data/data/com.termux/files/usr
> EDITOR=vim
> CARGO_TARGET_DIR=/data/data/com.termux/files/home/.cargo/global-target
> PWD=/data/data/com.termux/files/home
> LOGNAME=u0_a289
> EXTERNAL_STORAGE=/sdcard
> LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
> HOME=/data/data/com.termux/files/home
> LANG=en_US.UTF-8
> TMPDIR=/data/data/com.termux/files/usr/tmp
> VSCODE_AGENT_FOLDER=/data/data/com.termux/files/home/.vscode-server-insiders
> SSH_CONNECTION=192.168.0.6 56204 192.168.0.5 8022
> ANDROID_DATA=/data
> USER=u0_a289
> SHLVL=2
> ANDROID_ROOT=/system
> LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
> SSH_CLIENT=192.168.0.6 56204 8022
> LC_ALL=en_US.UTF-8
> PATH=./bin:/data/data/com.termux/files/home/.local/bin:/data/data/com.termux/files/home/.bin:/usr/local/bin:./bin:/data/data/com.termux/files/home/.local/bin:/data/data/com.termux/files/home/.bin:/usr/local/bin:/data/data/com.termux/files/usr/bin:/data/d
[11:40:16.390] > ata/com.termux/files/usr/bin/applets:/usr/local/sbin:/data/data/com.termux/files/home/.cargo/bin:./node_modules/.bin:/usr/local/sbin:/data/data/com.termux/files/home/.cargo/bin:./node_modules/.bin
> _=/data/data/com.termux/files/usr/bin/printenv
> OLDPWD=/data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33
[11:40:16.390] > Starting server...
> Waiting for server log...
[11:40:17.106] > Waiting for server log...
[11:40:17.858] > Waiting for server log...
[11:40:18.029] > Waiting for server log...
[11:40:18.813] > Waiting for server log...
[11:40:19.549] > Waiting for server log...
[11:40:19.672] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[11:40:19.711] > Server did not start successfully. Full server log >>>
[11:40:19.718] > /data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/server.sh: 12: /data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/server.sh: /data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/node: not found
[11:40:19.719] > <<< End of server log
> a1a81061-93fb-4f50-a49c-9a27fb9b389d##32##
[11:40:20.490] "install" terminal command done
[11:40:20.490] Install terminal quit with output: a1a81061-93fb-4f50-a49c-9a27fb9b389d##32##
[11:40:20.490] Received install output: a1a81061-93fb-4f50-a49c-9a27fb9b389d##32##
[11:40:20.490] The VS Code Server failed to start
[11:40:20.490] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"ExitCode"},"measures":{"resolveAttempts":1,"exitCode":32,"retries":1}}
[11:40:20.491] ------
```

</details>

<details>
<summary>Full "Remote - SSH" log (2)</summary>

```console
[11:58:31.585] remote-ssh-nightly@2019.8.42660
[11:58:31.585] darwin x64
[11:58:31.585] SSH Resolver called for "ssh-remote+oneplus6local", attempt 1
[11:58:31.586] SSH Resolver called for host: oneplus6local
[11:58:31.586] Setting up SSH remote "oneplus6local"
[11:58:31.601] Using commit id "dcc01858d3f75696568eb751238d01b30a1e7d33" and quality "insider" for server
[11:58:31.609] Testing ssh with ssh -V
[11:58:31.632] ssh exited with code: 0
[11:58:31.632] Got stderr from ssh: OpenSSH_7.8p1, LibreSSL 2.6.2
[11:58:31.632] Running script with connection command: ssh -D 56282 -o ConnectTimeout=15 oneplus6local bash
[11:58:31.632] Install and start server if needed
[11:58:32.370] > Running remote connection script
[11:58:32.370] Got some output, clearing connection timeout
[11:58:32.373] > Acquiring lock on /data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/vscode-remote-lock.dcc01858d3f75696568eb751238d01b30a1e7d33
[11:58:32.414] > Found existing installation at /data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33...
[11:58:32.449] > Found running server...
>  
[11:58:32.450] > *
> * Reminder: You may only use this software with Visual Studio family products,
[11:58:32.453] > * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[11:58:32.546] > Checking server status on port 41455 with curl
[11:58:32.650] > fbcaa8cd-417d-436b-9758-08f0c54a5e76: start
> agentPort==41455==
> webViewServerPort====
[11:58:32.652] > osReleaseId==Linux==
> arch==aarch64==
> webUiAccessToken====
> fbcaa8cd-417d-436b-9758-08f0c54a5e76: end
[11:58:32.652] Received install output: 
agentPort==41455==
webViewServerPort====
osReleaseId==Linux==
arch==aarch64==
webUiAccessToken====

[11:58:32.652] Remote server is listening on port 41455
[11:58:32.652] Parsed server configuration: {"agentPort":41455,"osReleaseId":"Linux","arch":"aarch64","webUiAccessToken":""}
[11:58:32.652] ** Note: Support for architecture "aarch64" is in preview **
[11:58:32.653] Starting forwarding server. localPort 56285 -> socksPort 56282 -> remotePort 41455
[11:58:32.653] Forwarding server listening on 56285
[11:58:32.653] Waiting for ssh tunnel to be ready
[11:58:32.654] Tunneled remote port 41455 to local port 56285
[11:58:32.654] Resolved "ssh-remote+oneplus6local" to "127.0.0.1:56285"
[11:58:32.654] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"success","osReleaseId":"Linux","arch":"aarch64"},"measures":{"resolveAttempts":1,"retries":1}}
[11:58:32.655] ------




[11:58:32.655] [Forwarding server 56285] Got connection 0
[11:58:32.770] [Forwarding server 56285] Got connection 1
[11:58:32.770] [Forwarding server 56285] Got connection 2
```

</details>

<details>
<summary>Visual Studio Code Server log file</summary>

```console
$ cat /data/data/com.termux/files/home/.vscode-server-insiders/.dcc01858d3f75696568eb751238d01b30a1e7d33.log


*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


{ Error: dlopen failed: library "libstdc++.so.6" not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module.patchedRequire [as require] (/data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:25:18)
    at bindings (/data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/node_modules/spdlog/index.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module.patchedRequire [as require] (/data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:25:18)
    at t.load (/data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/out/vs/loader.js:16:247)
    at e.load (/data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/out/vs/loader.js:13:713)
    at i (/data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/out/vs/loader.js:29:371)
    at Object.errorback (/data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/out/vs/loader.js:29:492)
    at e.triggerErrorback (/data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/out/vs/loader.js:14:62)
    at /data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/out/vs/loader.js:13:783
    at ReadFileContext.callback (/data/data/com.termux/files/home/.vscode-server-insiders/bin/dcc01858d3f75696568eb751238d01b30a1e7d33/out/vs/loader.js:16:619)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:237:13)
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ] }
IP Address: 192.168.0.5
Extension host agent listening on 41455
Unable to retrieve mac address (Error: Command failed: /sbin/ifconfig -a || /sbin/ip link
/data/data/com.termux/files/usr/bin/sh: 1: /sbin/ifconfig: Permission denied
/data/data/com.termux/files/usr/bin/sh: 1: /sbin/ip: Permission denied
)
Unauthorized client refused.
Unauthorized client refused.
Unauthorized client refused.
Unauthorized client refused.
```

</details>

**Comment by roblourens** [comment]
Thanks for the detailed issue! Yeah the stuff we ship is dynamically linked and the current requirements are documented here: https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites

**Comment by kbfifi** [comment]
@killercup For what it's worth: I pretty much discovered the same issue as you did. So that was a dead end. However my goal was to be able remotely debug with VSCode in Termux. I succeeded by using WinScp and using the import ptvsd in my target script. Use WinScp to connect via SSH and from WinScp edit the script with VSCode (Make sure set "Options->preferences->Storage->Use this directory" and "Options->preferences->Storage->Keep temp copies"
Then in VSCode set the remote debug options and add an entry like:
{
            "name": "My new remote settings",
            "type": "python",
            "request": "attach",
            "pathMappings": [
                {
                    "localRoot": "C:\\Users\\myname\\AppData\\Local\\Temp\\Scp\\data\\data\\com.termux\\files\\home\\owncloud-sync-venv",  
                    "remoteRoot": "." 
necessary for your OS and situation.
                }
            ],
            "port": 2000,                   // Set to the remote port.
            "host": "192.168.178.37",               
            "justMyCode": false
        }

Works like charm!

**Comment by gregjhogan** [comment]
I found more context as to where the issue lies here: https://github.com/microsoft/vscode-remote-release/issues/103#issuecomment-552167999

**Comment by QGB** [comment]
最近 Visual Studio Code C Languaqetas 
问题输出 调试控制台 终
 Could not establish connection to "192.168.1.6" 
  note-SSH 6 More Actions.. Close Remote Retry
 「12:29:46.635] > termux@192.168.1.6's password: 
[12:20:46.635] Showing password prompt
 [12:29:59.709] Got password response 
「12:29:59.7691 *install* wrote datatotermina1:* 家来索家家索 
「12:29:56.714] > 
「12:29:51.2861> Hello wor1d 
[12:29:51.218] > No PTY requested.
 |12:26:51.5681 "install" terminsl command done
 [12:20:51.569] Install terminal quit with output: No PTY reguested.
 [12:29:51.569] Received install output: No PTV requested. 
[12:29:51.569] Stopped parsing output early.Remaining text: No PTY requested. [12:26:51.569] Failed to parse remote port from server output 
「12:26:51.570] Resolver error: ”:
12:29:51.5741 "resolver","properties":{ 12:29:51.5741 TELEMETRY:4 eventName "outcome": "failure",reason":"Unparsableoutput","askedPw":"1","askedpassphrase":*o" "asked2fa":"9"askedHostKe gotUnrecognizedpromot":9" gFile":"1"},"measures":{"resolveAttempts*:1, "retries":1]] 
T12:29:51.575 -----

![image](https://user-images.githubusercontent.com/8005654/178131234-f0487741-f334-454c-8da1-ff07d3362621.png)

**Comment by QGB** [comment]
点x close 关闭报错弹窗
```
[12:20:43.484] remote-ssh@0.47.2
[12:20:43.484] win32 x64
[12:20:43.486] SSH Resolver called for "ssh-remote+192.168.1.6", attempt 1
[12:20:43.486] SSH Resolver called for host: 192.168.1.6
[12:20:43.486] Setting up SSH remote "192.168.1.6"
[12:20:43.535] Using commit id "6ab598523be7a800d7f3eb4d92d7ab9a66069390" and quality "stable" for server
[12:20:43.537] Testing ssh with ssh -V
[12:20:43.621] ssh exited with code: 0
[12:20:43.621] Got stderr from ssh: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[12:20:43.627] Running script with connection command: ssh -T -D 64620 192.168.1.6 bash
[12:20:43.629] Install and start server if needed
[12:20:43.631] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[12:20:43.748] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\WINDOWS\System32\cmd.exe
[12:20:43.749] Got some output, clearing connection timeout
[12:20:43.765] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[12:20:44.263] > The authenticity of host '[192.168.1.6]:2222 ([192.168.1.6]:2222)' can't be esta
> blished.
> RSA key fingerprint is SHA256:er1llgXPftjkJMxWxMWO2vnvCD/i2C0cDoIZ1YNlrIE.      
> Are you sure you want to continue connecting (yes/no)?
[12:20:44.263] Detected fingerprint confirmation message
[12:20:44.263] Showing fingerprint confirmation dialog
[12:20:46.452] Got fingerprint response: yes
[12:20:46.453] "install" wrote data to terminal: "yes"
[12:20:46.475] > y
[12:20:46.484] > Are you sure you want to continue connecting (yes/no)? yes
> Warning: Permanently added '[192.168.1.6]:2222' (RSA) to the list of known hosts
> .
> 
[12:20:46.635] > termux@192.168.1.6's password: 
[12:20:46.635] Showing password prompt
[12:20:50.709] Got password response
[12:20:50.709] "install" wrote data to terminal: "******"
[12:20:50.714] > 
> 
[12:20:51.200] > Hello world
> 
[12:20:51.218] > No PTY requested.
> 
[12:20:51.568] "install" terminal command done
[12:20:51.569] Install terminal quit with output: No PTY requested.
[12:20:51.569] Received install output: No PTY requested.
[12:20:51.569] Stopped parsing output early. Remaining text: No PTY requested.
[12:20:51.569] Failed to parse remote port from server output
[12:20:51.570] Resolver error: 
[12:20:51.574] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"UnparsableOutput","askedPw":"1","askedPassphrase":"0","asked2fa":"0","askedHostKey":"1","gotUnrecognizedPrompt":"0","remoteInConfigFile":"1"},"measures":{"resolveAttempts":1,"retries":1}}
[12:20:51.575] ------

```

**Comment by QGB** [comment]
https://alpha2phi.medium.com/remote-code-development-on-termux-using-vs-code-and-neovim-ca9fd13b7824
```
[20:11:34.933] Got password response
[20:11:34.933] "install" wrote data to terminal: "******"
[20:11:34.951] > 
> 
[20:11:36.260] > d3db0a4abf65: running
> 
[20:11:36.424] > aarch64 is only supported when running VS Code Insiders
> 
[20:11:36.433] > d3db0a4abf65##29##
> 
[20:11:36.854] "install" terminal command done
[20:11:36.855] Install terminal quit with output: d3db0a4abf65##29##
[20:11:36.855] Received install output: d3db0a4abf65##29##
[20:11:36.855] Resolver error: The remote host's architecture is only supported on VS Code Insiders
[20:11:36.861] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"ExitCode","askedPw":"1","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","gotUnrecognizedPrompt":"0","remoteInConfigFile":"1"},"measures":{"resolveAttempts":1,"exitCode":29,"retries":1}}
[20:11:36.861] ------

```

**Comment by heethjain21** [comment]
Jan 2026. This functionality is still not supported. I can successfully get into my Android via SSH, but when I try running VSCode, I get this error

<img width="2880" height="1750" alt="Image" src="https://github.com/user-attachments/assets/4651d7e9-eba9-409d-8640-61f1ef4892a2" />

**Comment by ge9** [comment]
I've found a working solution.
Basically, we have to install glibc and set the three environment variables (as we do in outdated Linux):
- VSCODE_SERVER_CUSTOM_GLIBC_LINKER
- VSCODE_SERVER_CUSTOM_GLIBC_PATH
- VSCODE_SERVER_PATCHELF_PATH

However, there are some more caveats around shebang and LD_PRELOAD.
This is my Japanese blog article. I'll publish an English version sometime.
https://turgenev.hatenablog.com/entry/2026/02/11/121330
Confirmed working in Termux (without root or proot) in F-01J (Android 8), Pixel 5 (Android 14), Pixel 6 (Android 16).
