### ISSUE TITLE
Failure to clean up saved askpass prompt

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#1472]
Keep seeing a weird reconnection case 

- With local server enabled
- Asks for passphrase (not sure if this was correct)
- Local server dies/askpass connection times out
- askpass.sh fails, probably signals cancel to ssh
- Asks for password instead
- This prompt stays in globalState forever

```
[15:01:36.537] SSH Resolver called for "ssh-remote+robfast", attempt 2, (Reconnection)
[15:01:36.539] SSH Resolver called for host: robfast
[15:01:36.539] Setting up SSH remote "robfast"
[15:01:36.546] Acquiring local install lock: /var/folders/tx/p0ycbfpj37786p760wwdg6y80000gn/T/vscode-remote-ssh-robfast-install.lock
[15:01:36.548] Looking for existing server data file at /Users/roblou/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh-nightly/vscode-ssh-host-robfast-de03947834d0bcf55093b97c292b76faa75cdebc/data.json
[15:01:36.550] Found local server running: {"agentPort":35815,"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"8f94b8fe-8cb9-458c-83e2-6b441e2f22b2","sshAuthSock":"/tmp/ssh-WH7b6qcJl1/agent.36358","pid":64405,"ipcHandlePath":"/var/folders/tx/p0ycbfpj37786p760wwdg6y80000gn/T/vscode-ssh-askpass-7b85cbb0b54191f5a996c13b8e0d448e9837acc6.sock","socksPort":64789,"startupTime":1569273438828}
[15:01:36.550] Running server is stale. Ignoring
[15:01:36.551] Using commit id "de03947834d0bcf55093b97c292b76faa75cdebc" and quality "insider" for server
[15:01:36.557] Running script with connection command: ssh -T -D 50804 -o ConnectTimeout=15 robfast bash
[15:01:36.557] Install and start server if needed
[15:01:36.560] askpass server listening on /var/folders/tx/p0ycbfpj37786p760wwdg6y80000gn/T/vscode-ssh-askpass-bb2df5cee6ecf91dfe29bd6ec7f93a0ab2a0d631.sock
[15:01:36.561] Spawning local server with {"ipcHandlePath":"/var/folders/tx/p0ycbfpj37786p760wwdg6y80000gn/T/vscode-ssh-askpass-7c33c3e369eee8ae865439bf05ee18843a81e31d.sock","sshCommand":"ssh","sshArgs":["robfast","-D","50804","bash"],"dataFilePath":"/Users/roblou/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh-nightly/vscode-ssh-host-robfast-de03947834d0bcf55093b97c292b76faa75cdebc/data.json"}
[15:01:36.561] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/roblou/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2019.9.32781/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/roblou/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2019.9.32781/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/tx/p0ycbfpj37786p760wwdg6y80000gn/T/vscode-ssh-askpass-bb2df5cee6ecf91dfe29bd6ec7f93a0ab2a0d631.sock"}
[15:01:36.566] Spawned 68468
[15:01:36.708] > local-server> Spawned 68469
[15:01:37.118] Got askpass request: {"request":"Enter passphrase for key '/Users/roblou/.ssh/azurevm':"}
[15:01:37.120] Detected passphrase message
[15:01:37.121] Listening for interwindow password on /var/folders/tx/p0ycbfpj37786p760wwdg6y80000gn/T/vscode-ssh-askpass-8ee6502e57778e440052ca125267fc7cf6bccb09.sock
[15:01:37.121] Writing password prompt to globalState
[15:01:40.732] > local-server> Timed out
[15:01:40.749] Local server exit: 0
[15:01:40.749] Install terminal quit with output: 3c8498884951: end
[16:15:55.667] stderr> Failed to get SSH credentials: Error in request: socket hang up
[16:15:55.668] stderr> ["/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer)","/Users/roblou/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2019.9.32781/out/askpass-main.js","Enter","passphrase","for","key","'/Users/roblou/.ssh/azurevm':"]
[16:15:56.145] Cleaning up other window auth server
[16:15:56.146] Handling auth request failed: Error: Canceled
	at /Users/roblou/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2019.9.32781/out/extension.js:1:10061
	at l.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:467)
	at s.cancel (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:54:100)
	at Object.cancel (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:54:665)
	at /Users/roblou/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2019.9.32781/out/extension.js:1:167765
	at l.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:50:467)
	at s.cancel (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:54:100)
	at Object.cancel (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:54:665)
	at Object.onRequest (/Users/roblou/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2019.9.32781/out/extension.js:1:76476)
	at Server.<anonymous> (/Users/roblou/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2019.9.32781/out/extension.js:1:75786)
	at Server.emit (events.js:200:13)
	at parserOnIncoming (_http_server.js:713:12)
	at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
[16:15:56.147] Got askpass request: {"request":"roblou@168.62.29.176's password:"}
[16:15:56.147] Showing password prompt
[16:15:56.148] Listening for interwindow password on /var/folders/tx/p0ycbfpj37786p760wwdg6y80000gn/T/vscode-ssh-askpass-87ab2d18d5af0faccedb1c6a11ab77cdb2ec663b.sock
[16:15:56.148] Writing password prompt to globalState
[16:25:56.130] stderr> Failed to get SSH credentials: Error in request: socket hang up
[16:25:56.130] stderr> ["/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer)","/Users/roblou/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2019.9.32781/out/askpass-main.js","roblou@168.62.29.176's","password:"]
[16:25:56.145] stderr> Connection closed by 168.62.29.176 port 22
[16:25:56.148] > local-server> ssh child died, shutting down
[16:25:56.158] Local server exit: 0
[16:25:56.158] Install terminal quit with output: Connection closed by 168.62.29.176 port 22
[16:25:56.158] Received install output: Connection closed by 168.62.29.176 port 22
[16:25:56.158] Failed to parse remote port from server output: Connection closed by 168.62.29.176 port 22
[16:25:56.159] Resolver error:
[16:25:56.159] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"UnparsableOutput"},"measures":{"resolveAttempts":2,"retries":1}}
[16:25:56.160] ------
```

**Comment by roblourens** [comment]
This is fixed
