### ISSUE TITLE
SSH randomly disconnecting

### ISSUE THREAD

**Issue by orn688** [microsoft/vscode-remote-release#1473]
The remote VS Code extension has been (seemingly) randomly disconnecting with the message "Cannot reconnect. Please reload the window." This happens roughly once every two hours, both yesterday and today (September 23-24). My internet connection is excellent and I've tried restarting my local machine (though not the remote machine) without effect. Could this be a regression in the latest release (from September 22)?

Here is the window log (I wasn't able to see any other logs after it had disconnected):
https://gist.github.com/orn688/a1d8edfb05eef4214bb3a32d0ec61262

It's been the same stack trace every time I've thought to check.

- VSCode Version: 1.38.1
- Local OS Version: macOS 10.14.6
- Remote OS Version: Debian 4.19.37
- Remote Extension/Connection Type: SSH

Steps to Reproduce (not sure if this will be reliable):

1. Work for a couple hours on a remote SSH connection

(Sorry I can't be more specific – I'll try to gather more info as it keeps happening.)

**Comment by roblourens** [comment]
Is there a Remote-SSH log in the output pane after this? (it might disappear after this happens). Are you using the nightly ssh extension or stable?

> `[2019-09-24 13:50:21.853] [renderer4] [error] Error: Connection error: Unknown reconnection token.`

Any idea @alexandrudima?

**Comment by orn688** [comment]
No, unfortunately that's the last of the output I can find (in the "Log (Window)" section). Let me know if there's any other place I should look for logs next time it happens (which will probably be within the next hour). Since it's disconnected I can no longer view the server side logs, but I could try to find them in the remote machine's file system if they're persisted somewhere.

I'm using the stable SSH extension as well as stable VS Code.

**Comment by roblourens** [comment]
You can also run "Set log level" and pick "trace" to probably get more output in the Window log

**Comment by orn688** [comment]
Here's the output with log level set to trace: https://gist.github.com/orn688/2b456f2d4dc1962a5f4ae04336df92aa

Interestingly, it's only happened in one workspace – I've used another workspace for several hours without issues. The main difference between the two is that I mostly work in Go files (using the Go extension) in the former, and Python files in the latter. I'll report back if I do experience a crash in the Python workspace.

**Comment by orn688** [comment]
I've had both workspaces open in separate windows for a few hours and the Go workspace has disconnected twice (and I wasn't even doing anything in that window either time) while the Python workspace hasn't disconnected at all. It could still be a coincidence, of course. But it's interesting that the Python workspace hasn't disconnected even when the Go one has.

**Comment by roblourens** [comment]
What extensions are you using? One explanation for that error is that an extension is crashing the remote extension host.

**Comment by alexandrudima** [comment]
It is possible that the remote extension host is crashing...

**Comment by joepow2** [comment]
I also met this issue, and I don't have any extension either.
- VSCode Version: 1.38.1
- Local OS Version: Windows 7
- Remote OS Version: Ubuntu 16.04
- Remote Extension/Connection Type: SSH

Trace log:
```[2019-10-01 18:21:06.839] [remoteagent] [info] Last EH closed, waiting before shutting down
[2019-10-01 18:21:11.868] [remoteagent] [info] ==> Received an extension host connection.
[2019-10-01 18:21:11.868] [remoteagent] [info] ==> Using UI language: en
[2019-10-01 18:21:37.596] [remoteagent] [trace] telemetry/UnhandledError {"properties":{"msg":"write EPIPE","callstack":"Error: write EPIPE\n    at WriteWrap.afterWrite [as oncomplete] (net.js:788:14)","common.machineId":"50718b9208d3cec94e9b8511be3e8ab7e5daa2a5db03b7e6f4df94a507052bb2","sessionID":"69168bc1-80e7-4cb5-8b5e-81d395be9fbe1569923162516","commitHash":"b37e54c98e1a74ba89e03073e5a3761284e3ffb0","version":"1.38.1-remote","common.platformVersion":"4.15.0","common.platform":"Linux","common.nodePlatform":"linux","common.nodeArch":"x64","common.product":"remoteAgent","timestamp":"2019-10-01T10:21:37.595Z"},"measurements":{"count":1,"common.timesincesessionstart":2135080,"common.sequence":10}}
[2019-10-01 18:21:37.596] [remoteagent] [trace] telemetry/UnhandledError {"msg":"write EPIPE","callstack":"Error: write EPIPE\n    at WriteWrap.afterWrite [as oncomplete] (net.js:788:14)","count":1}```

**Comment by orn688** [comment]
After ~one week of using mostly the Python workspace, I'm using the Go workspace again and it's consistently crashing.

I have the exact same set of extensions enabled for the two workspaces, but I'm definitely using the Go extension much more heavily for the Go workspace, so I suspect that's the issue.

Are the remote extension host logs saved somewhere that I could access them the next time a crash happens? I assume that would help with debugging this.

**Comment by roblourens** [comment]
Before it crashes you can run "Open Log File" and pick the remote EH log to see where it is. Then check that location after it crashes.

**Comment by joepow2** [comment]
Hi @roblourens, I followed your suggestion running "Open Log File => Windows".
I found something interesting, is it helpful?

File Name: renderer3.log

```[2019-10-02 10:44:42.787] [renderer3] [info] [remote-connection][ExtensionHost][02402…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2019-10-02 10:44:42.787] [renderer3] [info] [remote-connection][ExtensionHost][02402…][reconnect] waiting for 5 seconds before reconnecting...
[2019-10-02 10:44:47.794] [renderer3] [info] [remote-connection][ExtensionHost][02402…][reconnect] resolving connection...
[2019-10-02 10:44:47.794] [renderer3] [info] [remote-connection][ExtensionHost][02402…][reconnect] connecting to 127.0.0.1:53310...
[2019-10-02 10:44:47.816] [renderer3] [error] [remote-connection][ExtensionHost][02402…][reconnect][127.0.0.1:53310] received error control message when negotiating connection. Error:
[2019-10-02 10:44:47.816] [renderer3] [error] Error: Connection error: Unknown reconnection token.
    at _ (file:///D:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1678:506)
    at o.onControlMessage.l (file:///D:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1676:659)
    at d.fire (file:///D:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:107:468)
    at v.fire (file:///D:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:350:801)
    at _receiveMessage (file:///D:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:355:324)
    at _socketDisposables.push._socketReader.onMessage.e (file:///D:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:354:281)
    at d.fire (file:///D:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:107:468)
    at g.acceptChunk (file:///D:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:348:234)
    at _register._socket.onData.e (file:///D:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:347:592)
    at Socket.t (file:///D:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:357:518)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[2019-10-02 10:44:47.816] [renderer3] [error] [remote-connection][ExtensionHost][02402…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
[2019-10-02 10:44:47.816] [renderer3] [error] Error: Connection error: Unknown reconnection token.
    at _ (file:///D:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1678:506)
    at o.onControlMessage.l (file:///D:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1676:659)
    at d.fire (file:///D:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:107:468)
    at v.fire (file:///D:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:350:801)
    at _receiveMessage (file:///D:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:355:324)
    at _socketDisposables.push._socketReader.onMessage.e (file:///D:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:354:281)
    at d.fire (file:///D:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:107:468)
    at g.acceptChunk (file:///D:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:348:234)
    at _register._socket.onData.e (file:///D:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:347:592)
    at Socket.t (file:///D:/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:357:518)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[2019-10-02 10:45:03.739] [renderer3] [warning] Workbench did not finish loading in 10 seconds, that might be a problem that should be reported.
[2019-10-02 10:45:06.660] [renderer3] [error] Error: [File Watcher (chokidar)] Inotify limit reached (ENOSPC)
[2019-10-02 10:47:09.699] [renderer3] [error] read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:111:27)```

**Comment by roblourens** [comment]
No, I am looking for the "Remote Extension Host" log file

**Comment by joepow2** [comment]
The "Remote Extension Host" log file
https://gist.github.com/joepow2/4a7846371c8145ee28bd82cf79556e56

**Comment by roblourens** [comment]
Thanks, that doesn't show a crash or anything bad unfortunately.

**Comment by orn688** [comment]
Ah interesting, there wasn't anything in the remote EH host log (`~/.vscode-server/data/logs/20191002T092620/exthost2/output_logging_20191002T092645/exthost.log`) but I found `exthost2/output_logging_20191002T092645/6-gopls.log` with some interesting output:
```
[Error - 10:30:40 AM] 2019/10/02 10:30:40 no highlight: 357.000000:31.000000 is not an identifier
        URI = file:///redactedpath/main.go
```
(Weirdly, there isn't any text like that in that `main.go` file.)

This seems like a gopls issue rather than a VS Code remote problem. A quick search of the gopls and vscode-go issues didn't reveal any similar issues, so I'll file an issue with one of them (probably vscode-go to start with).

Thanks for the help!

**Comment by roblourens** [comment]
They shouldn't be crashing the EH, so please follow up with whatever you learn!

**Comment by orn688** [comment]
Will do, thanks!

**Comment by orn688** [comment]
This is actually happening even with gopls disabed. I found some logs like the following:
```
[2019-10-07 14:07:25.921] [remoteagent] [error] [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
[2019-10-07 14:07:52.535] [remoteagent] [error] [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
[2019-10-07 14:08:13.323] [remoteagent] [error] [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
[2019-10-07 14:08:45.023] [remoteagent] [error] [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
[2019-10-07 14:09:11.982] [remoteagent] [error] [File Watcher (chokidar)] failed to start after retrying for some time, giving up. Please report this as a bug report!
[2019-10-07 14:09:35.148] [remoteagent] [error] [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
[2019-10-07 14:10:26.253] [remoteagent] [error] [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
[2019-10-07 14:11:17.786] [remoteagent] [error] [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
[2019-10-07 14:11:57.241] [remoteagent] [info] New EH opened, aborting shutdown
[2019-10-07 14:12:17.144] [remoteagent] [error] [File Watcher (chokidar)] terminated unexpectedly and is restarted again...
[2019-10-07 14:13:08.572] [remoteagent] [error] [File Watcher (chokidar)] failed to start after retrying for some time, giving up. Please report this as a bug report!
```
This might be a dupe of #1257 (incidentally, I'm also a Google employee using a very similar setup to what #1257 describes).

**Comment by orn688** [comment]
Yep, pretty sure the issue was too many files in the workspace. I had several massive directories of old cached downloaded files in the workspace, and things seem to be working fine now that I've deleted those.

Not sure what the plan is for #1257, but this is definitely a dupe of that issue.

Thanks for the help!
