### ISSUE TITLE
[SSH] Windows 10 disconnects then fails to reconnect to linux remote until remote reboot

### ISSUE THREAD

**Issue by weikinhuang** [microsoft/vscode-remote-release#1486]
- VSCode Version: `1.38.1`
- Remote - SSH Version: `0.46.1`
- Local OS Version: Windows 10 19H1
- Remote OS Version: `Linux dev-78b45757dd-vbb4z 4.19.68-coreos #1 SMP Wed Sep 4 02:59:18 -00 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to remote host
2. Do work for a little while

This happens on both my windows computers, but is fine on my mac.

What happens is that I'm able to connect to the remote server via vscode once per reboot of my remote server. Once I'm connected everything is fine for ~5-10 mins. Then will disconnect. Once it disconnects I am unable to reconnect until I reboot the remote machine.

I've tried both with and without the wrapper. (using native windows ssh, and wsl ssh via wrapper below)

This setup was working fine up until the last vscode update.

ssh config:
```
Host dev
    Hostname ide.example.com
    Port 9922
    ServerAliveInterval 25
    HashKnownHosts no
```

ssh.bat
```bat
@echo off

set v_params=%*
set v_params=%v_params:\=/%
set v_params=%v_params:c:=/mnt/c%
REM set v_params=%v_params:"=\"%

If %PROCESSOR_ARCHITECTURE% == x86 (
  C:\Windows\Sysnative\wsl.exe ssh %v_params%
) Else (
  C:\Windows\System32\wsl.exe ssh %v_params%
)
```

```settings.json
  // Remote ssh
  "remote.SSH.lockfilesInTmp": true,
  // "remote.SSH.enableDynamicForwarding": true,
  "remote.SSH.enableAgentForwarding": true,
  "remote.SSH.path": "c:\\ssh.bat",
```

Here's some logs

```
[20:35:29.757] remote-ssh-nightly@2019.9.35460
[20:35:29.757] win32 x64
[20:35:29.757] SSH Resolver called for "ssh-remote+dev", attempt 1
[20:35:29.757] SSH Resolver called for host: dev
[20:35:29.757] Setting up SSH remote "dev"
[20:35:29.764] Using commit id "b37e54c98e1a74ba89e03073e5a3761284e3ffb0" and quality "stable" for server
[20:35:29.767] Testing ssh with c:\ssh.bat -V
[20:35:29.865] ssh exited with code: 0
[20:35:29.865] Got stderr from ssh: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
[20:35:29.865] Running script with connection command: "c:\ssh.bat" -T -D 51108 dev bash
[20:35:29.866] Install and start server if needed
[20:35:29.929] > ]0;C:\WINDOWS\SYSTEM32\cmd.exe
[20:35:29.929] Got some output, clearing connection timeout
[20:35:30.089] > Authenticated to ssh.node.dev.weikinhuang.com ([192.168.1.100]:9922).
[20:35:30.101] > 
[20:35:31.264] > Authenticated to ssh.node.dev.weikinhuang.com ([192.168.1.100]:9922).
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[20:35:47.395] > Authenticated to ide.example.com ([192.168.1.100]:9922).
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
```

Tailing the logs on the server
```
Last EH closed, waiting before shutting down
Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
==> Received a management connection
==> Received an extension host connection.
==> Using UI language: en
Got start params: { language: 'en',
  break: undefined,
  port: undefined,
  debugId: undefined }


EXTHOST: PROCESS EXITED
0
null
Cancelling previous shutdown timeout
Last EH closed, waiting before shutting down
Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
==> Received a management connection
==> Received an extension host connection.
==> Using UI language: en
Got start params: { language: 'en',
  break: undefined,
  port: undefined,
  debugId: undefined }








New EH opened, aborting shutdown
{ Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:788:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
Error: Unexpected SIGPIPE
    at process.on (/home/whuang/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/bootstrap.js:5:192)
    at process.emit (events.js:182:13)
Error: Unexpected SIGPIPE
    at process.on (/home/whuang/.vscode-server/bin/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/out/bootstrap.js:5:192)
    at process.emit (events.js:182:13)


```
Once that happens I can't reconnect

ps aux output
```
root        678  0.0  0.0  97196  6676 ?        Ss   20:28   0:00 sshd: remote [priv]
remote      693  0.0  0.0  97196  3392 ?        S    20:28   0:00 sshd: remote@pts/1
remote      694  0.0  0.0  28896 12504 pts/1    Ss+  20:28   0:00 -bash
root        863  0.0  0.0  97196  6624 ?        Ss   20:28   0:00 sshd: remote [priv]
remote      878  0.0  0.0  97196  3384 ?        S    20:28   0:00 sshd: remote@pts/2
remote      879  0.0  0.0  28896 12748 pts/2    Ss   20:28   0:00 -bash
remote     1274  0.0  0.0   6216   752 pts/0    S+   20:29   0:00 tail -f .b37e54c98e1a74ba89e03073e5a3761284e3ffb0.log
root       1275  0.0  0.0  97192  6436 ?        Ss   20:30   0:00 sshd: remote [priv]
remote     1290  0.0  0.0  97192  3440 ?        S    20:30   0:00 sshd: remote@notty
remote     1291  0.0  0.0  13312  3108 ?        Ss   20:30   0:00 bash
root       1964  0.0  0.0  97192  6660 ?        Ss   20:35   0:00 sshd: remote [priv]
remote     1979  0.0  0.0  97192  3392 ?        S    20:35   0:00 sshd: remote@notty
remote     1980  0.0  0.0  13312  3136 ?        Ss   20:35   0:00 bash
remote     2019  0.0  0.0  36076  3284 pts/2    R+   20:39   0:00 ps aux
```

Each one of those connections are from me quitting vscode and trying to reconnect again. The connect remains open even after fully quitting vscode.

**Comment by roblourens** [comment]
So the log is from a time when you failed to connect, right? Kind of confusing, we are trying to run a script over ssh and it never starts running the script, and I don't see what that would have to do with the remote server we start or why it would work once but not twice.

Does it work if you run the command "Kill VS Code Server on Host" and try again?

When it doesn't work, what happens if you run `echo uname | ssh.bat dev bash`

**Comment by weikinhuang** [comment]
yes, basically it'll work for a little while, and then stop working. The logs are from me trying to reconnect. Basically, it does manage to connect to the remote, but the script never runs or finishes. I couldn't get any logs from the bash script, it just hangs.

I'm still able to connect to the host via regular ssh.

**Comment by roblourens** [comment]
Does it work if you run the command "Kill VS Code Server on Host" and try again?

And so just to be clear, running a command by piping it to ssh works in this case? Like it looks like you were able to connect, it just didn't want to run our script.

**Comment by weikinhuang** [comment]
The problem seems to have gone away after I reinstalled the extension. I'll close for now and reopen if I see this again. Thanks!
