### ISSUE TITLE
Saltstack via VSCode: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1097: ordinal not in range(128) Error: unorderable types: UnicodeDecodeError() >= int()

### ISSUE THREAD

**Issue by xenadmin** [microsoft/vscode-remote-release#1572]
I use Visual Studio Code, together with the Remote SSH extension to administrate my Debian 9 SaltStack Master. Since today, the 'salt' commands on the Terminal broke. I can only reproduce this via the Terminal from VSCode. If I use PowerShell openssh, Putty, or other SSH Clients, everything works as expected. On 01.10.19 everything was still working. I have two different machines where I use VSCode, where it stopped working simultaneously. 

Example Terminal Output from VSCode:
```
root@salt:/srv# salt-key -L
[ERROR   ] 'ascii' codec can't decode byte 0xc3 in position 1097: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 210, in parse_args
    process_option_func()
  File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 2513, in process_config_dir
    super(SaltKeyOptionParser, self).process_config_dir()
  File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 548, in process_config_dir
    self.config.update(self.setup_config())
  File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 2518, in setup_config
    keys_config = config.master_config(self.get_config_file_path())
  File "/usr/lib/python3/dist-packages/salt/config/__init__.py", line 3884, in master_config
    exit_on_config_errors=exit_on_config_errors))
  File "/usr/lib/python3/dist-packages/salt/config/__init__.py", line 2295, in include_config
    opts = _read_conf_file(fn_)
  File "/usr/lib/python3/dist-packages/salt/config/__init__.py", line 2153, in _read_conf_file
    conf_opts = salt.utils.yaml.safe_load(conf_file) or {}
  File "/usr/lib/python3/dist-packages/salt/utils/yamlloader.py", line 224, in safe_load
    return yaml.load(stream, Loader=Loader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 70, in load
    loader = Loader(stream)
  File "/usr/lib/python3/dist-packages/salt/utils/yamlloader.py", line 42, in __init__
    super(SaltYamlSafeLoader, self).__init__(stream)
  File "/usr/lib/python3/dist-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/usr/lib/python3/dist-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/usr/lib/python3/dist-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/usr/lib/python3/dist-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1097: ordinal not in range(128)
Error: unorderable types: UnicodeDecodeError() >= int()
root@salt:/srv# 
```

Example Terminal Output from PowerShell openssh:
```
root@salt:~# salt-key -L
Accepted Keys:
zabprox.XYZ
zabprox.XYZ
zabprox.XYZ
zabprox.XYZ
zabprox.XYZ
zabprox.XYZ
zabprox.XYZ
zabprox.XYZ
zabprox.XYZ
zabprox.XYZ
zabprox.XYZ
zabprox.XYZ
zabprox.XYZ
zabprox.XYZ
zabprox.XYZ
zabprox.XYZ
zabprox.XYZ
zabprox.XYZ
zabprox.XYZ
zabprox.XYZ
zabprox.XYZ
zabprox.XYZ
Denied Keys:
Unaccepted Keys:
Rejected Keys:
root@salt:~#
```

Visual Studio Code:
```
Version: 1.38.1 (system setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

Did I open this issue in the correct project? Or do I have to go the the VSCode repo? I can't imagine it's a SaltStack problem, since it still works with other SSH clients. 

**UPDATE:** I can't reproduce it in Visual Studio Code Insiders
```
Version: 1.39.0-insider (user setup)
Commit: 695ee74864ef93d10f5de0861cb66af190e76211
Date: 2019-10-02T08:56:48.092Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by xenadmin** [comment]
I can't reproduce the error anymore. Will close it for now.
