### ISSUE TITLE
Errors in debug console when debugging node Win on Win

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-remote-release#1594]
Testing #1524 

debugging simple node app. did not repro in local with same app

```
C:\Users\roblou\.vscode-server-insiders\bin\695ee74864ef93d10f5de0861cb66af190e76211\node.exe --inspect-brk=46864 'C:\Users\roblou\My Documents\myWork\index.js'
Debugger listening on ws://127.0.0.1:46864/95d0a5a5-5f49-4954-8f5b-e8dcc8fccd83
For help, see: https://nodejs.org/en/docs/inspector
Error processing "breakpointLocations": Error: Breakpoint ignored because generated code not found (source map problem?).
    at Object.errP (c:\Users\roblou\.vscode-server-insiders\bin\695ee74864ef93d10f5de0861cb66af190e76211\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\utils.js:262:13)
    at adapter.sourceMapTransformer.getGeneratedPathFromAuthoredPath.then.mappedPath (c:\Users\roblou\.vscode-server-insiders\bin\695ee74864ef93d10f5de0861cb66af190e76211\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\chrome\breakpoints.js:140:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error processing "breakpointLocations": Error: Breakpoint ignored because generated code not found (source map problem?).
    at Object.errP (c:\Users\roblou\.vscode-server-insiders\bin\695ee74864ef93d10f5de0861cb66af190e76211\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\utils.js:262:13)
    at adapter.sourceMapTransformer.getGeneratedPathFromAuthoredPath.then.mappedPath (c:\Users\roblou\.vscode-server-insiders\bin\695ee74864ef93d10f5de0861cb66af190e76211\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\chrome\breakpoints.js:140:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
hello, world
```

**Comment by isidorn** [comment]
This should be fixed in latest. DUp of https://github.com/microsoft/vscode/issues/81567
