### ISSUE TITLE
Remote SSH Windows: disconnects out of random

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-remote-release#1601]
While testing https://github.com/microsoft/vscode-remote-release/issues/1524 I often noticed the reconnection dialog showing up out of nowhere. Then asking me for the password again and after I do that giving me this:

![image](https://user-images.githubusercontent.com/900690/66102421-99df5300-e5b2-11e9-890a-b9354806cc75.png)

Output:

```
[2019-10-03 07:41:59.298] [renderer3] [error] [remote-connection][Management   ][f62f5…][initial][127.0.0.1:53139] the handshake took longer than 10 seconds. Error:
[2019-10-03 07:41:59.298] [renderer3] [error] Error: handshake timeout
    at setTimeout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1678:260)
[2019-10-03 07:41:59.298] [renderer3] [error] [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
[2019-10-03 07:41:59.298] [renderer3] [error] Error: handshake timeout
    at setTimeout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1678:260)
[2019-10-03 07:41:59.397] [renderer3] [error] handshake timeout: Error: handshake timeout
    at setTimeout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1678:260)
[2019-10-03 07:41:59.397] [renderer3] [error] Could not fetch environment: Error: Could not fetch environment
    at t.isExtensionTerminal.d.getEnvironment.then.e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4071:417)
[2019-10-03 07:41:59.399] [renderer3] [error] handshake timeout: Error: handshake timeout
    at setTimeout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1678:260)
[2019-10-03 07:41:59.399] [renderer3] [error] [remote-connection][ExtensionHost][5459b…][initial][127.0.0.1:53139] the handshake took longer than 10 seconds. Error:
[2019-10-03 07:41:59.399] [renderer3] [error] Error: handshake timeout
    at setTimeout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1678:260)
[2019-10-03 07:41:59.399] [renderer3] [error] [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
[2019-10-03 07:41:59.399] [renderer3] [error] Error: handshake timeout
    at setTimeout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1678:260)
[2019-10-03 07:46:42.392] [renderer3] [info] [remote-connection][ExtensionHost][63400…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2019-10-03 07:46:42.392] [renderer3] [info] [remote-connection][ExtensionHost][63400…][reconnect] waiting for 5 seconds before reconnecting...
[2019-10-03 07:46:42.413] [renderer3] [info] [remote-connection][Management   ][e8865…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2019-10-03 07:46:42.426] [renderer3] [info] [remote-connection][Management   ][e8865…][reconnect] waiting for 5 seconds before reconnecting...
[2019-10-03 07:46:47.393] [renderer3] [info] [remote-connection][ExtensionHost][63400…][reconnect] resolving connection...
[2019-10-03 07:46:47.430] [renderer3] [info] [remote-connection][Management   ][e8865…][reconnect] resolving connection...
[2019-10-03 07:46:47.430] [renderer3] [info] [remote-connection][ExtensionHost][63400…][reconnect] A promise cancelation error occured while trying to reconnect, will try again...
[2019-10-03 07:46:47.430] [renderer3] [info] [remote-connection][ExtensionHost][63400…][reconnect] waiting for 5 seconds before reconnecting...
[2019-10-03 07:46:52.431] [renderer3] [info] [remote-connection][ExtensionHost][63400…][reconnect] resolving connection...
[2019-10-03 07:46:59.574] [renderer3] [info] [remote-connection][Management   ][e8865…][reconnect] connecting to 127.0.0.1:53243...
[2019-10-03 07:46:59.574] [renderer3] [info] [remote-connection][ExtensionHost][63400…][reconnect] connecting to 127.0.0.1:53243...
[2019-10-03 07:47:00.335] [renderer3] [error] [remote-connection][Management   ][e8865…][reconnect][127.0.0.1:53243] received error control message when negotiating connection. Error:
[2019-10-03 07:47:00.335] [renderer3] [error] Error: Connection error: Unknown reconnection token.
    at x (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1686:920)
    at o.onControlMessage.l (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1679:622)
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:116:519)
    at v.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:365:274)
    at t.PersistentProtocol._receiveMessage (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:369:677)
    at _socketDisposables.push._socketReader.onMessage.e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:368:786)
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:116:519)
    at g.acceptChunk (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:362:588)
    at _register._socket.onData.e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:361:958)
    at Socket.t (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:372:805)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[2019-10-03 07:47:00.335] [renderer3] [error] [remote-connection][Management   ][e8865…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
[2019-10-03 07:47:00.335] [renderer3] [error] Error: Connection error: Unknown reconnection token.
    at x (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1686:920)
    at o.onControlMessage.l (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1679:622)
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:116:519)
    at v.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:365:274)
    at t.PersistentProtocol._receiveMessage (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:369:677)
    at _socketDisposables.push._socketReader.onMessage.e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:368:786)
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:116:519)
    at g.acceptChunk (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:362:588)
    at _register._socket.onData.e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:361:958)
    at Socket.t (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:372:805)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[2019-10-03 07:48:39.049] [renderer3] [warning] Workbench did not finish loading in 10 seconds, that might be a problem that should be reported.
[2019-10-03 07:49:23.211] [renderer3] [warning] Workbench did not finish loading in 10 seconds, that might be a problem that should be reported.
[2019-10-03 07:49:39.002] [renderer3] [info] [remote-connection][Management   ][c33e8…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2019-10-03 07:49:39.012] [renderer3] [info] [remote-connection][Management   ][c33e8…][reconnect] waiting for 5 seconds before reconnecting...
[2019-10-03 07:49:39.013] [renderer3] [info] [remote-connection][ExtensionHost][804df…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2019-10-03 07:49:39.013] [renderer3] [info] [remote-connection][ExtensionHost][804df…][reconnect] waiting for 5 seconds before reconnecting...
[2019-10-03 07:49:44.014] [renderer3] [info] [remote-connection][Management   ][c33e8…][reconnect] resolving connection...
[2019-10-03 07:49:44.020] [renderer3] [info] [remote-connection][ExtensionHost][804df…][reconnect] resolving connection...
[2019-10-03 07:51:10.127] [renderer3] [info] [remote-connection][Management   ][c33e8…][reconnect] connecting to 127.0.0.1:53382...
[2019-10-03 07:51:10.127] [renderer3] [info] [remote-connection][ExtensionHost][804df…][reconnect] connecting to 127.0.0.1:53382...
[2019-10-03 07:51:10.871] [renderer3] [error] [remote-connection][Management   ][c33e8…][reconnect][127.0.0.1:53382] received error control message when negotiating connection. Error:
[2019-10-03 07:51:10.871] [renderer3] [error] Error: Connection error: Unknown reconnection token.
    at x (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1686:920)
    at o.onControlMessage.l (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1679:622)
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:116:519)
    at v.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:365:274)
    at t.PersistentProtocol._receiveMessage (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:369:677)
    at _socketDisposables.push._socketReader.onMessage.e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:368:786)
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:116:519)
    at g.acceptChunk (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:362:588)
    at _register._socket.onData.e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:361:958)
    at Socket.t (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:372:805)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[2019-10-03 07:51:10.871] [renderer3] [error] [remote-connection][Management   ][c33e8…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
[2019-10-03 07:51:10.871] [renderer3] [error] Error: Connection error: Unknown reconnection token.
    at x (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1686:920)
    at o.onControlMessage.l (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1679:622)
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:116:519)
    at v.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:365:274)
    at t.PersistentProtocol._receiveMessage (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:369:677)
    at _socketDisposables.push._socketReader.onMessage.e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:368:786)
    at c.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:116:519)
    at g.acceptChunk (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:362:588)
    at _register._socket.onData.e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:361:958)
    at Socket.t (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:372:805)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[2019-10-03 07:51:40.131] [renderer3] [error] [remote-connection] The time limit has been reached for a connection. Error:
[2019-10-03 07:51:40.132] [renderer3] [error] Error: Time limit reached
    at setTimeout (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1686:515)
[2019-10-03 07:51:40.132] [renderer3] [info] [remote-connection][ExtensionHost][804df…][reconnect] A network error occured while trying to reconnect, will try again...

```

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/66102479-cb581e80-e5b2-11e9-941c-5bfe224b80b7.png)

**Comment by roblourens** [comment]
It looks like the remote extension host is crashing here too @alexandrudima

**Comment by roblourens** [comment]
Oh no, this is actually due to the server auto shutdown logic, and the incomplete windows install script which doesn't call `/delay-shutdown`. Can be fixed in the extension...

**Comment by roblourens** [comment]
This isn't even that. Long story short, when I run `Start-Process` from local powershell instance, it does seem to start a detached process that survives its parent's death. But when I run it from a script invoked over ssh, it doesn't. This was hidden before because we were leaking the powershell processes.

For now I am patching this by keeping the powershell process open as long as the server that it launched is alive.

**Comment by evertiro** [comment]
Note that this doesn't seem limited to Windows. I run both Windows and Linux (two different computers, Windows 10 and Pop!_OS), and am experiencing it on both systems. Obviously, the Linux machine isn't experiencing an issue with powershell...

**Comment by roblourens** [comment]
If you aren't connecting to a windows server then you have a different problem, please open a new issue.

**Comment by evertiro** [comment]
Oops! Sorry, the description and screenshot matched my issue
