### ISSUE TITLE
Remote SSH: Support SunOS

### ISSUE THREAD

**Issue by fr43nk** [microsoft/vscode-remote-release#1875]
Hi,

are there any plans supporting operation systems like SunOS, like the one we use?

`SunOS habicht 5.10 Generic_147147-26 sun4u sparc SUNW,SPARC-Enterprise`

Best regards

**Comment by raivatshah** [comment]
I would love this feature as well!!

**Comment by dnyaneshgate** [comment]
Is there a workaround to make it work for Solaris OS?

**Comment by mccloud-jeff** [comment]
+1 for this feature please. I'm working in the financial industry, with many older SunOS machines. This VS Code feature works amazing for our Linux boxes. please implement it for SunOS!

**Comment by john-terrell** [comment]
Modern Illumos derived OSes (like SmartOS, OmniOS, etc) need support.   Illumos is a OpenSolaris derivative.    Please support!

**Comment by john-terrell** [comment]
> Modern Illumos derived OSes (like SmartOS, OmniOS, etc) need support. Illumos is a OpenSolaris derivative. Please support!

I can provide build support for these systems if need be.   I'm will to do the heavy lifting to make this happen as well.

**Comment by kovalexpro** [comment]
Working on DilOS (another illumos-based OS) - would be happy to use it as well. Now it rejects because "SunOS" is not supported.
I have bash at host (ubuntu/amd64) and guest (dilos/amd64) side. Please, suggest workaround if any.

**Comment by jussisallinen** [comment]
This would be great addition, I operate fleet of SmartOS (illumos based) hosts and would need to do remote development inside SmartOS Zones.

**Comment by jussisallinen** [comment]
Here's what happens upon connecting to illumos based SmartOS Zone:
`[11:41:06.897] Log Level: 2
[11:41:06.898] remote-ssh@0.56.0
[11:41:06.899] darwin x64
[11:41:06.900] SSH Resolver called for "ssh-remote+pupu.jus.si", attempt 1
[11:41:06.900] SSH Resolver called for host: pupu.jus.si
[11:41:06.900] Setting up SSH remote "pupu.jus.si"
[11:41:06.903] Acquiring local install lock: /var/folders/0s/nzq5b17129503hpj0vhpswj80000gp/T/vscode-remote-ssh-pupu.jus.si-install.lock
[11:41:06.916] Looking for existing server data file at /Users/jussi/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-pupu.jus.si-d2e414d9e4239a252d1ab117bd7067f125afd80a-0.56.0/data.json
[11:41:06.917] Using commit id "d2e414d9e4239a252d1ab117bd7067f125afd80a" and quality "stable" for server
[11:41:06.918] Install and start server if needed
[11:41:06.921] Checking ssh with "ssh -V"
[11:41:06.934] > OpenSSH_8.1p1, LibreSSL 2.7.3

[11:41:06.937] askpass server listening on /var/folders/0s/nzq5b17129503hpj0vhpswj80000gp/T/vscode-ssh-askpass-fda635fe9bee9427adb80f8ec85ee8b18c3f21e2.sock
[11:41:06.937] Spawning local server with {"ipcHandlePath":"/var/folders/0s/nzq5b17129503hpj0vhpswj80000gp/T/vscode-ssh-askpass-40f6cd66ce3b77077fad264a54babf70111a9985.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","50146","-o","ConnectTimeout=15","pupu.jus.si"],"dataFilePath":"/Users/jussi/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-pupu.jus.si-d2e414d9e4239a252d1ab117bd7067f125afd80a-0.56.0/data.json"}
[11:41:06.938] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/jussi/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code 2.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/jse39/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/0s/nzq5b17129503hpj0vhpswj80000gp/T/vscode-ssh-askpass-fda635fe9bee9427adb80f8ec85ee8b18c3f21e2.sock"}
[11:41:06.940] Spawned 72081
[11:41:07.030] > local-server> Spawned ssh: 72082
[11:41:07.034] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[11:41:07.279] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:OxTayF5/gbNr4f82yxY4HXSOvX2996Ot3rpsYaRj79w
[11:41:07.552] stderr> Authenticated to pupu.jus.si ([136.243.26.39]:22).
[11:41:07.697] > ready: 7e197af14519
[11:41:07.733] > SunOS 5.11 joyent_20201022T155042Z
[11:41:23.946] Terminating local server
[11:41:23.952] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/jussi/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:1:94553)
	at Timeout._onTimeout (/Users/jussi/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:1:329614)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)
[11:41:23.953] Local server exit: 15`

**Comment by JohnConnett** [comment]
This would be very useful on [OmniOS](https://omniosce.org/) and others in the [Illumos](https://www.illumos.org/) family.

**Comment by chrmarti** [comment]
The VS Code Server that is installed on the remote machine runs on Node.js and uses a few native modules that need to be compiled for that remote OS and hardware.

**Comment by jussisallinen** [comment]
> The VS Code Server that is installed on the remote machine runs on Node.js and uses a few native modules that need to be compiled for that remote OS and hardware.

Well that shouldn't be hard given that SmartOS is developed by Joyent: [https://www.joyent.com/node-js/support](url)
Do you need access to a SmartOS/illumos host for that to happen?
I can help with that in case it would speed things up.

**Comment by chrmarti** [comment]
We would set up a build machine to automate it. This is not planned at the moment. (It might not be hard, but automation and maintenance takes time.)

**Comment by robertdfrench** [comment]
@chrmarti am I correct in thinking that these remote components are not necessarily open source? (That is, we might not be able to help you much anyhow?). Thanks again!

**Comment by chrmarti** [comment]
@robertdfrench That's correct (see [FAQ](https://code.visualstudio.com/docs/remote/faq#_license-and-privacy)).

**Comment by robertdfrench** [comment]
> FAQ

doh! Gets me every time... Thanks @chrmarti !

**Comment by nwilkens** [comment]
+1 .. Was just trying to use this on a SmartOS development instance.  

I'd be happy to provide build machines to support this effort @ mnx.io if that helps in any way!

**Comment by dancrossnyc** [comment]
I, too, would really like to see this.

**Comment by Makr91** [comment]
This would be Awesome to see come to OmniOS!

**Comment by txinto** [comment]
+1 Hi, it would be fantastic to develop on SunOS machines from the desktop, without having to mount filesystems, etc.

**Comment by dancrossnyc** [comment]
Another cry for sympathy here. What would be needed to make this happen?

**Comment by dyigitpolat** [comment]
3 years, all these people asking for it and still nothing changed.

**Comment by Vistuvis** [comment]
Just putting in another request for SunOS support.

**Comment by bboysnick5** [comment]
pls add this.

**Comment by chebansviaz** [comment]
+1

**Comment by aquelemiguel** [comment]
+1

**Comment by Scripa4** [comment]
+1 Will be cool

**Comment by shabo20** [comment]
+1

**Comment by OneThousandEyes** [comment]
+1

**Comment by VitaliiVasetskyi** [comment]
+

**Comment by VitaliiVasetskyi** [comment]
+1

**Comment by Dimonv82** [comment]
+1

**Comment by AgentRelo** [comment]
+1

**Comment by natriy81** [comment]
+1

**Comment by dyigitpolat** [comment]
+1. 
If VS Code team needs a SunOS machine to test the remote connection mechanism, I can provide access to one.

**Comment by Rudolfowich** [comment]
+1

**Comment by ntubach** [comment]
+1

**Comment by sunilaecs** [comment]
+1

**Comment by abarnes-wmko** [comment]
+1

**Comment by alvdef** [comment]
+1

**Comment by Aaron-Hartwig** [comment]
+1

**Comment by kurowskitomek** [comment]
+1

**Comment by arjenroodselaar** [comment]
Adding a voice to the chorus.

**Comment by robertdfrench** [comment]
Have y'all tried running this in an LX-branded zone? It mostly works, except for debugging (that seems to be an issue with running a Linux gdb on illumos anyhow, it issues some ioctl that isn't implemented yet). I don't think Microsoft is going to fix this for us, but we might be able to craft an image to run in an LX zone that contains like, all the core illumos libraries and such. I think if we do that, figure out how to get gdb running, and tell rustc that it should always cross-compile for illumos, it might be a sufficient dev environment.

Any thoughts, or rotten tomatoes to throw?

**Comment by shanemcdo** [comment]
+1 for SunOS This would be a godsend.

**Comment by oraclejavanet** [comment]
+1 for Oracle Solaris 11.4

**Comment by oraclejavanet** [comment]
I can provide access to a number of Solaris 11.4 machines for testing. I can also provide any type of heavying lifting to getting this resolved. I can connect SSH using UltraEdit; however, I would rather work on these projects using VS Code.

**Comment by oraclejavanet** [comment]
Another desperate plea!

**Comment by Domest0s** [comment]
+1 to Solaris

**Comment by geosone** [comment]
and another one

**Comment by liv3010m** [comment]
+1, another vote

**Comment by alslater** [comment]
+1

**Comment by huang96962** [comment]
+1

**Comment by snunez1** [comment]
+1

Is this on the radar anywhere?

**Comment by equilibrium139** [comment]
+1

Would greatly appreciate this.

**Comment by lmk** [comment]
+1

**Comment by antekone** [comment]
It would be really nice to have this feature, +1

**Comment by alanhargreaves** [comment]
Another to the list, +1

**Comment by adamlouis** [comment]
+1 for Illumos, would appreciate this!

**Comment by robertdfrench** [comment]
Y'all, they are not gonna build this for us. But I think if we all sit down and burn a lot of tokens at the same time we could maybe reverse it and get something that half-ass works. DM me if you want to hack on this together some time, I'm not optimistic, but it could be fun to try.
