### ISSUE TITLE
Connection Timeout

### ISSUE THREAD

**Issue by dugu9sword** [microsoft/vscode-remote-release#1881]
- VSCode Version:1.40.1
- Local OS Version:Windows 10 1903
- Remote OS Version:Ubuntu 18.04
- Remote Extension/Connection Type: SSH
- SSH version: ssh.exe from Git for Windows

Steps to Reproduce:

1. Open a remote connection
2. Write code
3. It will randomly happen at some time :(

BTW, an SSH connection from a terminal works well, so it is not the problem of the network.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes
The output from the console:
![console](https://user-images.githubusercontent.com/6239743/69389251-baf62300-0c88-11ea-855a-04a7c5113849.png)

Win Process Manager:
![process](https://user-images.githubusercontent.com/6239743/69389254-bb8eb980-0c88-11ea-8613-014fa326b974.png)

The process managar on the remote os:
![server](https://user-images.githubusercontent.com/6239743/69389255-bb8eb980-0c88-11ea-916d-a5eacda62f4e.png)

**Comment by dugu9sword** [comment]
Log from remote server
```
[2019-11-21 17:54:52.139] [renderer1] [error] This socket has been ended by the other party: Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:407:14)
	at h.write (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:193:370)
	at f._writeNow (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:185:689)
	at Immediate.<anonymous> (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:185:627)
	at processImmediate (internal/timers.js:439:21)
[2019-11-21 17:54:53.879] [renderer1] [error] This socket has been ended by the other party: Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:407:14)
	at h.write (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:193:370)
	at f._writeNow (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:185:689)
	at Immediate.<anonymous> (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:185:627)
	at processImmediate (internal/timers.js:439:21)
[2019-11-21 17:54:55.235] [renderer1] [error] This socket has been ended by the other party: Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:407:14)
	at h.write (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:193:370)
	at f._writeNow (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:185:689)
	at Immediate.<anonymous> (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:185:627)
	at processImmediate (internal/timers.js:439:21)
[2019-11-21 17:54:56.341] [renderer1] [info] [remote-connection][ExtensionHost][9315f…][reconnect] resolving connection...
[2019-11-21 17:54:56.894] [renderer1] [info] [remote-connection][Management   ][cf7a3…][reconnect] resolving connection...
[2019-11-21 17:54:56.920] [renderer1] [info] [remote-connection][ExtensionHost][9315f…][reconnect] A promise cancelation error occured while trying to reconnect, will try again...
[2019-11-21 17:54:56.921] [renderer1] [info] [remote-connection][ExtensionHost][9315f…][reconnect] waiting for 5 seconds before reconnecting...
[2019-11-21 17:54:57.199] [renderer1] [error] This socket has been ended by the other party: Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:407:14)
	at h.write (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:193:370)
	at f._writeNow (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:185:689)
	at Immediate.<anonymous> (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:185:627)
	at processImmediate (internal/timers.js:439:21)
[2019-11-21 17:55:06.040] [renderer1] [error] This socket has been ended by the other party: Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:407:14)
	at h.write (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:193:370)
	at f._writeNow (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:185:689)
	at Immediate.<anonymous> (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:185:627)
	at processImmediate (internal/timers.js:439:21)
[2019-11-21 17:55:06.783] [renderer1] [info] [remote-connection][ExtensionHost][9315f…][reconnect] resolving connection...
[2019-11-21 17:55:07.488] [renderer1] [error] This socket has been ended by the other party: Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:407:14)
	at h.write (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:193:370)
	at f._writeNow (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:185:689)
	at Immediate.<anonymous> (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:185:627)
	at processImmediate (internal/timers.js:439:21)
[2019-11-21 17:55:08.582] [renderer1] [error] This socket has been ended by the other party: Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:407:14)
	at h.write (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:193:370)
	at f._writeNow (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:185:689)
	at Immediate.<anonymous> (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:185:627)
	at processImmediate (internal/timers.js:439:21)
[2019-11-21 17:55:09.763] [renderer1] [error] This socket has been ended by the other party: Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:407:14)
	at h.write (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:193:370)
	at f._writeNow (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:185:689)
	at Immediate.<anonymous> (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:185:627)
	at processImmediate (internal/timers.js:439:21)
[2019-11-21 17:55:10.951] [renderer1] [error] This socket has been ended by the other party: Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:407:14)
	at h.write (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:193:370)
	at f._writeNow (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:185:689)
	at Immediate.<anonymous> (/home/zhouyi/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/out/vs/server/remoteExtensionHostProcess.js:185:627)
	at processImmediate (internal/timers.js:439:21)
```

**Comment by dugu9sword** [comment]
Log from VSCODE
```
> Found existing installation at /home/zhouyi/.vscode-server/bin/8795a9889db74563d
> dd43eb0a897a2384129a619...
> Found running server...
[17:55:16.888] > 
> 
> *
[17:55:18.862] > 
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
[17:55:21.017] > 
> 
> *
> 
> Checking server status on port 43191 with wget
[17:55:21.162] > 
> 
> 
> 
[17:55:22.712] > 31e4f18fac44: start
> sshAuthSock====
> agentPort==43191==
[17:55:25.276] > 
> 
> 
> webViewServerPort====
> osReleaseId==ubuntu==
[17:55:26.834] > 
> 
> arch==x86_64==
> webUiAccessToken====
> 31e4f18fac44: end
[17:55:26.835] Received install output: 
sshAuthSock====
agentPort==43191==


webViewServerPort====
osReleaseId==ubuntu==

arch==x86_64==
webUiAccessToken====

[17:55:26.835] Remote server is listening on port 43191
[17:55:26.835] Parsed server configuration: {"agentPort":43191,"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":""}
[17:55:26.839] Starting forwarding server. localPort 12295 -> socksPort 12275 -> remotePort 43191
[17:55:26.842] Forwarding server listening on 12295
[17:55:26.842] Waiting for ssh tunnel to be ready
[17:55:26.845] Tunneled remote port 43191 to local port 12295
[17:55:26.845] Resolved "ssh-remote+172.81.237.69" to "127.0.0.1:12295"
[17:55:26.846] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"success","osReleaseId":"ubuntu","arch":"x86_64","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0"},"measures":{"resolveAttempts":28,"retries":1}}
[17:55:26.846] ------




[17:55:26.847] [Forwarding server 12295] Got connection 0
[17:55:27.066] [Forwarding server 12295] Got connection 1
[17:55:27.067] [Forwarding server 12295] Got connection 2
[17:55:28.217] > 
[17:55:28.887] > 
> 
> 
```

**Comment by roblourens** [comment]
Is that the full log? It doesn't show the reconnction happening.

**Comment by roblourens** [comment]
Also can you get the command line args of those processes using high CPU, like from `ps`?

**Comment by dugu9sword** [comment]
hi, i think it is because the network is busy.
