### ISSUE TITLE
 Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#1981]
Found the following in the ext host log. Not sure when/how I got it.

ms-vscode-remote.remote-containers 0.88.0
```
[2019-12-05 14:13:57.414] [exthost] [error] [ms-vscode-remote.remote-containers] provider FAILED
[2019-12-05 14:13:57.417] [exthost] [error] TypeError: Cannot read property 'type' of undefined
	at Module.e (/home/aeschli/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.88.0/dist/extension.js:1:56659)
	at t.ConfigLinkProvider.provideDocumentLinks (/home/aeschli/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.88.0/dist/extension.js:1:1120857)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:587:40
	at /usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:52:287
	at new Promise (<anonymous>)
	at Object.t.asPromise (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:52:259)
	at N.provideLinks (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:587:11)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:600:90
	at B._withAdapter (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:591:697)
	at B.$provideDocumentLinks (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:600:68)
	at p._doInvokeHandler (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:663:275)
	at p._invokeHandler (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:662:971)
	at p._receiveRequest (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:661:588)
	at p._receiveOneMessage (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:660:468)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:658:691
	at l.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)
	at _.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:189:274)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:820:285
	at l.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)
	at _.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:189:274)
	at t.PersistentProtocol._receiveMessage (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:193:629)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:190:824
	at l.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)
	at p.acceptChunk (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186:737)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186:89
	at Socket.t (/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:195:68)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by chrmarti** [comment]
No exact match, but the location is shortly after the third `.type` in the explorer code:
![image](https://user-images.githubusercontent.com/9205389/70267921-ba3cb100-179f-11ea-9802-368ebd2e0731.png)

**Comment by alexr00** [comment]
It's coming from something that `provideDocumentLinks` calls (not explorer). More specifically, it's likely coming from `_linksForDockerCompose`.

**Comment by alexr00** [comment]
I found a couple other errors and made a PR, but I don't see the cause of this problem.

**Comment by chrmarti** [comment]
We haven't seen this again, assuming it is fixed.
