### ISSUE TITLE
Remote Container on Remote Host

### ISSUE THREAD

**Issue by dfarley1** [microsoft/vscode-remote-release#2028]
I'm trying to follow the instructions [here](https://code.visualstudio.com/docs/remote/containers-advanced#_a-basic-remote-example) to connect to a docker container running on a remote machine (Windows PC at home --> Linux PC in the office) but I'm getting some error about `open-ssh-agent` after setting `"docker.host": "ssh://danf@<workmachine>"` and reloading the window
```
[2019-12-14 00:17:30.253] [renderer1] [error] connect ENOENT \\.\pipe\openssh-ssh-agent: Error: connect ENOENT \\.\pipe\openssh-ssh-agent
	at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
```

I don't see any of my running containers show up in the Remote Explorer list and the loading bar at the top spins forever.

I've installed both the OpenSSH client and server provided by Windows (Manage Optional Features) as well as the Docker CLI, VSCode with Remote-Containers and Docker extensions.  They should all be up to date since I started trying this yesterday.

----------

I figured if SSH isn't gonna work I might as well try TCP but that's got a problem as well.  I set remote host's `dockerd` to listen on `0.0.0.0:2375` and set `"docker.host": "<workmachine>:2375"`.  Now I can actually see the running containers in the Remote Explorer but when I try to connect to one of them I get the following error in the "Dev Containers" terminal of the new window:
```
[0 ms] Start: Resolving remote
[5 ms] Setting up container depotviolet_stage_1

[141 ms] Start: Check Docker is running
[220 ms] Start: Inspecting container
[256 ms] Start: Run in container: uname -m
[259 ms] Start: Run in container: cat /etc/passwd
[261 ms] Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
        at doWrite (_stream_writable.js:413:19)
        at writeOrBuffer (_stream_writable.js:401:5)
        at Socket.Writable.write (_stream_writable.js:301:11)
        at c:\Users\danfa\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:95871
        at c:\Users\danfa\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:96235
        at async Object.exec (c:\Users\danfa\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:96256)
        at async c:\Users\danfa\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:134613
        at async Object.t.getContainerProperties (c:\Users\danfa\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:134571)
        at async Object.t.resolve (c:\Users\danfa\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:384869)
        at async c:\Users\danfa\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:1028173
```

**Comment by chrmarti** [comment]
What do you get for `ssh-add -l`? Make sure you have the ssh-agent running, see https://code.visualstudio.com/docs/remote/troubleshooting#_setting-up-the-ssh-agent.

**Comment by aleksandrlat** [comment]
I tried both 
`"docker.host": "ssh://root@192.168.56.101"`
and
`"docker.host": "tcp://192.168.56.101:2375"`

And for both I have the same error
```
[0 ms] Start: Resolving remote
[3 ms] Setting up container swoop_node_1

[485 ms] Start: Check Docker is running
[941 ms] Start: Inspecting container
[1493 ms] Start: Run in container: uname -m
[1496 ms] Start: Run in container: cat /etc/passwd
[1498 ms] Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
        at doWrite (_stream_writable.js:413:19)
        at writeOrBuffer (_stream_writable.js:401:5)
        at Socket.Writable.write (_stream_writable.js:301:11)
        at c:\Users\Aleksandr\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:95871
        at c:\Users\Aleksandr\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:96235
        at async Object.exec (c:\Users\Aleksandr\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:96256)
        at async c:\Users\Aleksandr\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:134613
        at async Object.t.getContainerProperties (c:\Users\Aleksandr\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:134571)
        at async Object.t.resolve (c:\Users\Aleksandr\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:384869)
        at async c:\Users\Aleksandr\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:1028173
```

**Comment by chrmarti** [comment]
@aleksandrlat What is the output when you set the log level to Debug and then reload the window? (`F1` > `Developer: Set Log Level...` and `F1` > `Reload Window`)

**Comment by chrmarti** [comment]
@dfarley1 @aleksandrlat Also: Which version of Docker are you running?

**Comment by aleksandrlat** [comment]
My docker version is `Docker version 19.03.5, build 633a0ea838`

The output with log level Debug is almost the same. Just `Stop` lines appeared.
```
[0 ms] Start: Resolving remote
[2 ms] Setting up container swoop_node_1

[47 ms] Start: Check Docker is running
[56 ms] Stop (9 ms): Check Docker is running
[56 ms] Start: Inspecting container
[59 ms] Stop (3 ms): Inspecting container
[71 ms] Start: Run in container: uname -m
[73 ms] Start: Run in container: cat /etc/passwd
[74 ms] Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
        at doWrite (_stream_writable.js:413:19)
        at writeOrBuffer (_stream_writable.js:401:5)
        at Socket.Writable.write (_stream_writable.js:301:11)
        at c:\Users\Aleksandr\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:95871
        at c:\Users\Aleksandr\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:96235
        at async Object.exec (c:\Users\Aleksandr\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:96256)
        at async c:\Users\Aleksandr\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:134613
        at async Object.t.getContainerProperties (c:\Users\Aleksandr\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:134571)
        at async Object.t.resolve (c:\Users\Aleksandr\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:384869)
        at async c:\Users\Aleksandr\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:1028173
```

**Comment by brianclaridge** [comment]
@aleksandrlat -- I received this error as well. For me, it was because I had a folder in my local workspace called ./docker where I kept my Dockerfiles and other assets. As soon as I renamed the folder, the issue went away. This same workspace was fine a few weeks ago -- so I'm not sure why it was suddenly a problem.

**Comment by aleksandrlat** [comment]
Hey @brianclaridge!

Thank you for the help!

I have tried to rename my `./docker` folder to `./doctor` folder. 
Also I tried to downgrade docker to `18.09.9` version.

But none of these helped. Having the same error.

I re-created containers after renaming `./docker` folder to `./doctor`. Maybe I should do some other actions?

I also tried debian and node public images without mounting anything to them. Still no luck :(

**Comment by aleksandrlat** [comment]
Maybe it’s important that I run my containers using `docker-compose`

**Comment by chrmarti** [comment]
@aleksandrlat Could you attach a minimal reproducible case? Maybe a docker-compose.yml with a single service that demonstrates the problem.

**Comment by dfarley1** [comment]
@chrmarti I didn't have ssh-agent running, so I enabled that to run at startup and restarted VSCode.  
```
C:\Users\danfa>ssh-add -l
The agent has no identities.

C:\Users\danfa>docker --version
Docker version 19.03.5, build 633a0ea
```
I am still not able to see any containers on my remote machine (they're definitely up).  The Remote Explorer spins forever and I'm not seeing any output even with logging set to debug.

If I go to the Docker tab I see the following errors but everything is blank except for "Connect Registry..."
```
[2019-12-20 16:57:22.669] [renderer1] [error] read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
[2019-12-20 16:57:24.657] [renderer1] [error] read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
[2019-12-20 16:57:28.664] [renderer1] [error] read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
[2019-12-20 16:57:30.668] [renderer1] [error] read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
```

----------

As for TCP, I'm not getting the original error I reported anymore.  Instead it seems frozen in the "Installing Dev Container" phase. I see the the following in the Dev Containers terminal, it's been trying to run `uname -m` for about 5 minutes now.  No other logs or anything.
```
[0 ms] Start: Resolving remote
[5 ms] Setting up container depotviolet_stage_1

[84 ms] Start: Check Docker is running
[156 ms] Stop (72 ms): Check Docker is running
[157 ms] Start: Inspecting container
[202 ms] Stop (45 ms): Inspecting container
[210 ms] Start: Run in container: uname -m
```

**Comment by aleksandrlat** [comment]
@dfarley1 I think you just need to add your key to ssh-agent 
```
# Now load your key files into ssh-agent
ssh-add ~\.ssh\id_rsa
```

@chrmarti even if I just run 
```
docker run -it --name debian9 debian:9 /bin/bash
```
I cannot connect to it.

This is the only line I have in `settings.json` for docker
```
"docker.host": "tcp://192.168.56.101:2375"
```

**Comment by aleksandrlat** [comment]
@chrmarti I figured it out finally. I had to un-minify `extension.js` and debug it by adding `output.write` debug messages.

Code was creating `C:\soft\Microsoft VS Code\docker` path for docker-cli because docker-cli was not in path. Of course `C:\soft\Microsoft VS Code\docker` is invalid path. After I added `docker.exe` to my path it works fine.

It would be good to check if docker executable really exists and fail explicitly if it does not. I would contribute but looks like it is not open source, right?

I see [dockerode](https://www.npmjs.com/package/dockerode) js client is used. Can it be used instead of docker-cli?

I don't want to install full Docker Desktop only for docker-cli because of different reasons.
It is possible to build docker-cli from source code. Or get pre-built binaries.

I found couple of sources to get pre-built binaries:
- chocolatey docker-cli only package https://chocolatey.org/packages/docker-cli. Here is github repo for it https://github.com/StefanScherer/docker-cli-builder
- this issue https://github.com/docker/for-win/issues/1460 contains some useful links
- https://github.com/OneGet/MicrosoftDockerProvider
- https://github.com/rgl/docker-ce-windows-binaries-vagrant

This maybe helpful if you may want to add some info to docs how to get docker-cli only.

**Comment by chrmarti** [comment]
There is a fix for logging errors in the latest version 0.99.2 of the extension available for VS Code Insiders (https://code.visualstudio.com/insiders/). Could those still seeing issues retry with that and check if the Containers log has any additional information?
