### ISSUE TITLE
Cannot open server

### ISSUE THREAD

**Issue by axm2** [microsoft/vscode-remote-release#2032]
- VSCode Version: 1.41.0
- Local OS Version: 
- Remote OS Version: 
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. connect to remote server
2.

```
[21:55:36.712] > Starting server...       
> Waiting for server log...
> 
[21:55:37.208] > Waiting for server log...
> 
[21:55:37.713] > Waiting for server log...
> 
[21:55:38.219] > Waiting for server log...
> 
[21:55:38.723] > Waiting for server log...
> 
[21:55:39.228] > Waiting for server log...
> 
[21:55:39.733] > Waiting for server log...
> 
[21:55:40.240] > Waiting for server log...
> 
[21:55:40.739] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
[21:55:40.749] > 
> Server did not start successfully. Full server log >>>
> The factory method of "vs/platform/product/common/product" has thrown an excepti
> on
> Error: Cannot find module '/home/users/316F19/mirza_omar316/.vscode-server/bin/9
> 579eda04fdb3a9bba2750f15193e5fafe16b959/product.json'
> Require stack:
> - /home/users/316F19/mirza_omar316/.vscode-server/bin/9579eda04fdb3a9bba2750f151
> 93e5fafe16b959/out/vs/loader.js
> - /home/users/316F19/mirza_omar316/.vscode-server/bin/9579eda04fdb3a9bba2750f151
> 93e5fafe16b959/out/bootstrap-amd.js
> - /home/users/316F19/mirza_omar316/.vscode-server/bin/9579eda04fdb3a9bba2750f151
> 93e5fafe16b959/out/vs/server/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15) 
>     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
>     at Module.require (internal/modules/cjs/loader.js:681:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at Function.s [as __$__nodeRequire] (/home/users/316F19/mirza_omar316/.vscod
[21:55:40.755] > 
> e-server/bin/9579eda04fdb3a9bba2750f15193e5fafe16b959/out/vs/loader.js:32:963)  
>     at Object.<anonymous> (/home/users/316F19/mirza_omar316/.vscode-server/bin/9
> 579eda04fdb3a9bba2750f15193e5fafe16b959/out/vs/server/remoteExtensionHostAgent.j
> s:295:416)
>     at Function.t._safeInvokeFunction (/home/users/316F19/mirza_omar316/.vscode-
> server/bin/9579eda04fdb3a9bba2750f15193e5fafe16b959/out/vs/loader.js:20:548)    
>     at Function.t._invokeFactory (/home/users/316F19/mirza_omar316/.vscode-serve
> r/bin/9579eda04fdb3a9bba2750f15193e5fafe16b959/out/vs/loader.js:20:795)
>     at t.complete (/home/users/316F19/mirza_omar316/.vscode-server/bin/9579eda04
> fdb3a9bba2750f15193e5fafe16b959/out/vs/loader.js:21:10)
>     at s._onModuleComplete (/home/users/316F19/mirza_omar316/.vscode-server/bin/
[21:55:40.760] > 
> 9579eda04fdb3a9bba2750f15193e5fafe16b959/out/vs/loader.js:31:490)
>     at s._resolve (/home/users/316F19/mirza_omar316/.vscode-server/bin/9579eda04
> fdb3a9bba2750f15193e5fafe16b959/out/vs/loader.js:31:41)
>     at s.defineModule (/home/users/316F19/mirza_omar316/.vscode-server/bin/9579e
> da04fdb3a9bba2750f15193e5fafe16b959/out/vs/loader.js:25:184)
>     at r (/home/users/316F19/mirza_omar316/.vscode-server/bin/9579eda04fdb3a9bba
> 2750f15193e5fafe16b959/out/vs/loader.js:32:180)
>     at c (/home/users/316F19/mirza_omar316/.vscode-server/bin/9579eda04fdb3a9bba
> 2750f15193e5fafe16b959/out/vs/loader.js:16:956)
>     at Object.<anonymous> (/home/users/316F19/mirza_omar316/.vscode-server/bin/9
> 579eda04fdb3a9bba2750f15193e5fafe16b959/out/vs/server/remoteExtensionHostAgent.j
> s:276:763)
>     at Object.<anonymous> (/home/users/316F19/mirza_omar316/.vscode-server/bin/9
> 579eda04fdb3a9bba2750f15193e5fafe16b959/out/vs/server/remoteExtensionHostAgent.j
> s:473:442)
>     at t._createAndEvalScript (/home/users/316F19/mirza_omar316/.vscode-server/b
> in/9579eda04fdb3a9bba2750f15193e5fafe16b959/out/vs/loader.js:17:3)
>     at /home/users/316F19/mirza_omar316/.vscode-server/bin/9579eda04fdb3a9bba275
> 0f15193e5fafe16b959/out/vs/loader.js:16:639
>     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_c
> ontext.js:61:3) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/users/316F19/mirza_omar316/.vscode-server/bin/9579eda04fdb3a9bba2750f
> 15193e5fafe16b959/out/vs/loader.js',
>     '/home/users/316F19/mirza_omar316/.vscode-server/bin/9579eda04fdb3a9bba2750f
> 15193e5fafe16b959/out/bootstrap-amd.js',
[21:55:40.766] > 
>     '/home/users/316F19/mirza_omar316/.vscode-server/bin/9579eda04fdb3a9bba2750f
> 15193e5fafe16b959/out/vs/server/main.js'
>   ],
>   phase: 'factory',
>   moduleId: 'vs/platform/product/common/product'
> }
> 
[21:55:40.776] > <<< End of server log
> 2e692bb9187b##32##
[21:55:40.785] > 
> 
[21:55:41.438] "install" terminal command done
[21:55:41.438] Install terminal quit with output: 2e692bb9187b##32##
[21:55:41.438] Received install output: 2e692bb9187b##32##
[21:55:41.438] Resolver error: The VS Code Server failed to start
[21:55:41.441] ------
```

I think something may have gone wrong with the installation

**Comment by axm2** [comment]
NVM I hit a disk quota
