### ISSUE TITLE
Error when vscode attach running container

### ISSUE THREAD

**Issue by EdduSoft** [microsoft/vscode-remote-release#2058]
Im getting the next error:

```
[0 ms] Start: Resolving remote
[1 ms] Setting up container intelligent_driscoll

[6 ms] Start: Check Docker is running
[34 ms] Start: Inspecting container
[395 ms] Start: Run in container: uname -m
[667 ms] x86_64
[667 ms] 
[667 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[757 ms] NAME="Ubuntu"
VERSION="14.04.6 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.6 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
[757 ms] 
[758 ms] Start: Run in container: cat /etc/passwd
[770 ms] TypeError: Cannot read property 'reduce' of null
        at Object.t.getContainerProperties (/home/google/.vscode/extensions/ms-vscode-remote.remote-containers-0.94.0/dist/extension.js:1:135076)
        at async Object.t.resolve (/home/google/.vscode/extensions/ms-vscode-remote.remote-containers-0.94.0/dist/extension.js:1:384869)
        at async /home/google/.vscode/extensions/ms-vscode-remote.remote-containers-0.94.0/dist/extension.js:1:1028173
```

This issue was generated in the last vscode updated 1.41.0

**Comment by kapadiup** [comment]
Has the been solved yet or is there a work around.  I am running into the same issue.  Strangely it works fine on my sandbox windows wsl docker environment but I am getting this error on my dev environment which is running docker on a Linux box.

**Comment by chrmarti** [comment]
It's not fixed yet. I think it's triggered when there is no environment variable set on the container. Try setting one with `-e` of `docker run` when you start the container.
