### ISSUE TITLE
SSH value for docker.host fails with 'Current user does not have permission'

### ISSUE THREAD

**Issue by diablodale** [microsoft/vscode-remote-release#2079]
Issue Type: <b>Bug</b>

SSH docker.host, e.g. `"docker.host": "ssh://username@mylanserver"
F1, Remote-Containers: Attach to running container
Fails with permission error

This is related to the new functionality in 1.41 
https://github.com/microsoft/vscode-docs/blob/master/remote-release-notes/v1_41.md#support-for-ssh-as-docker-host

May be related to https://github.com/microsoft/vscode-remote-release/issues/937

## Setup

* local Windows 10 1909  build 18363.535
* remote Ubuntu 18.04.3 LTS
* VS Code for Windows 1.41.1 (system setup)
* Have working SSH ~/.ssh/config and key setup for seamless ssh usage in WSL.
* Have working shim bat file that if VSCode needs to run `ssh` from windows, that it is routed to WSL. This includes the setting `"remote.SSH.path": "C:\\mybatfile.bat"`
* Have working remote explorer that successfully shows containers on this remote SSH target
* Have working Remote-SSH solution to this remote docker host
* In main settings for VSCode, set `"docker.host": "ssh://username@mylanserver"`

## Repro

1. Open VSCode
2. Click green remote icon in lower left
3. Choose Remote-Containers: Attach to running container

## Result

Current user does not have permission to run 'docker'. Try adding the user to the 'docker' group.

(Documenation / Cancel)

Also notice minor typo in the button. The `t` is missing.

## Expected

Some UI that lists the containers running on that remote SSH server and ability to chose the specific container to which I want to connect

## Notes

1. From WSL I can run `ssh username@mylanserver` and it seamlessly connects and I get a prompt
2. On that prompt I can run `docker container ls` and see all the containers
3. On that prompt I can run `docker run hello-world` and I get the successful expected output

Extension version: 0.94.0
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 4.4.0-18362-Microsoft
Remote OS version: Linux x64 5.0.0-37-generic
Remote OS version: Linux x64 4.4.0-18362-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|      Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2601)|
|Memory (System)|15.89GB (6.62GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|      Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2601)|
|Memory (System)|15.89GB (6.62GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: home-nas|
|OS|Linux x64 5.0.0-37-generic|
|CPUs|Intel(R) Pentium(R) CPU G3258 @ 3.20GHz (2 x 1974)|
|Memory (System)|7.66GB (2.72GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.4.0-18362-Microsoft|
|CPUs|      Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2601)|
|Memory (System)|15.89GB (6.62GB free)|
|VM|0%|
</details>

**Comment by ferwasy** [comment]
Hi. I was experimenting the same error that you describe and I could get rid of it adding my private key to the ssh agent and adding my public key to the authorized_keys file in my ssh server.

**Comment by diablodale** [comment]
Glad that worked for you. You describe that you are using a common method of authentication for SSH.

Step 4 of my setup bullets describes how there is a working SSH authentication setup in my repo case. There are no issues with SSH authentication or authorization with other apps and tools. My auth setup continues to work unchanged for years.

I'm confident the issue is isolated to errant code or behavior in this remote extension. This new feature of the extension+ssh+docker is new and it is normal to find errant code, errant behavior, or a "lack-of-feature". This issue provides the needed scenario to explore why this new feature doesn't work so to improve it. :-)

**Comment by ferwasy** [comment]
But is the key listed in the output of "ssh-add -l" ?

**Comment by diablodale** [comment]
Yes, the key is listed. I use it and the agent uncountable times per day.

**Comment by ferwasy** [comment]
That is weird ...
What about docker? Is it installed on your machine? Can you run "docker" with your regular user without using sudo?

**Comment by ferwasy** [comment]
Maybe some of questions seem silly, but I 'm just trying to tackle the issues that I had

**Comment by diablodale** [comment]
* docker client is installed on the local machine
* docker client and docker server are installed on the remote docker host

On my local machine I can do the following:
```bash
export DOCKER_HOST="ssh://mylanserver"
docker container ls
```

and it will give me the expected ls of all the containers running on the remote host.
No sudo. No other settings or options to use. It is simple and seamless.

**Comment by diablodale** [comment]
I've isolated some issues with the Docker extension codebase. It is blindly running `ssh` with no regard to configured shell (cmd, wsl bash, etc.) or specified vscode setting of path to ssh `"remote.SSH.path"`

### Docker extension runs incorrect SSH client

These two issues immediately cause problems when `ssh` is not in the same subsystem as VSCode. For example, my `ssh` is in WSL. My VSCode is in the Windows subsystem. This extension's codebase doesn't consider this. Therefore, it blindly runs `ssh` in the Windows subsystem. This leads to Windows searching the Windows `PATH` environment variable. It is possible that the newer SSH client (optional Windows feature) is installed. This was my scenario. So this extension was running the Windows SSH client which has no configuration whatsoever that would allow it to connect to remote servers. This Windows SSH client has no ssh config file, no ssh agent, etc. And it likely will never have such.

### Docker extension should honor VSCode setting for path to SSH

This extension should allow running ssh from WSL.

I have a batch file named `ssh.BAT` that can be used for many situations like this. This BAT shim approach is widely discussed in the VSCode SSH/remote extension. This BAT file is already defined as the value of the VSCode setting `"remote.SSH.path"`. This works well for the Remote-SSH extension and I have no problems using that. This Docker extension should use that value -or- create yet another value just for this extensions use.

### Docker extension should allow running BAT files as SSH

Since that explicit SSH path is not yet supported in this extension, I added the directory of the BAT shim into the PATH. Now when I try to attach to a running container, I get the following error in the VSCode developer tools:

```
[Extension Host]%
{error: {…}, stdout: "'↵", stderr: "error during connect: Get http://docker/v1.40/vers…exec: "ssh": executable file not found in %PATH%↵"}
error:
cmd: "docker version --format '{{.Server.Version}}'"
code: 1
killed: false
signal: null
__proto__: Object
stderr: "error during connect: Get http://docker/v1.40/version: exec: "ssh": executable file not found in %PATH%↵"
stdout: "'↵"
__proto__: Object
```

This error suggests that the Docker extension does not recognize/support running a BAT file as SSH.
In contrast, I can open a VSCode terminal window (CMD is the shell) and run the following with no errors and you can see the version of docker running on _myservername_ is nicely printed as the result.:

```
ssh myservername -- docker version --format '{{.Server.Version}}'
19.03.5
```

**Comment by chrmarti** [comment]
#### On your first approach:

`"remote.SSH.path"` is not supported by Remote-Containers at the moment. We also use a NPM module (in addition to the CLI) that currently doesn't support reading from `~/.ssh/config` (and that wouldn't know how to get to the WSL side to read the config there).

#### On your second approach :

We set SSH_AUTH_SOCK to that path on Windows (if it is not set yet). Maybe that is passed through to your `docker` executable in WSL? Can you try setting SSH_AUTH_SOCK to the SSH agent's path in WSL in your shim for `docker`?

Note that the mentioned NPM module also needs to be able to connect to the Docker daemon and that module runs inside the extension unaware of your shim. It might still work, but you'd need the SSH agent set up with your key on the Windows side too (not just insider WSL).

#### Supported setup

I recommend setting up SSH on Windows (should be preinstalled) and use `ssh://...` with that.

**Comment by diablodale** [comment]
@chrmarti , my mistake. I didn't answer your question.
No that didn't work. setting such a named pipe variable for a Linux executable doesn't work.
Naturally, the root issue here is incompatibility of VSCode (windows) with the tools existing in WSL. That boat of open-source tools in Linux sailed a long time ago.
Running an SSH agent in Windows works against that vast army of tools like git, gpg, ssh, etc.

**Comment by chrmarti** [comment]
So you have everything set up in WSL and now want to use Remote-Containers with the ssh-agent running in WSL to connect to a remote Docker host. Is that correct?

Placing wrappers on the PATH got you almost there it seems. What's missing is a way for the extension to reach the ssh-agent's socket path in WSL. The code doing that is a module not under our control, so you would have to set the `SSH_AUTH_SOCK` env variable on the Windows side for VS Code to some path that forwards/redirects to the WSL one. 🤔

**Comment by diablodale** [comment]
bit of patience please, I'm testing some ideas.

**Comment by diablodale** [comment]
Thanks for your patience. I've got some thoughts + diagnostics below. I'll use the term "user" to mean a person that uses the VSCode UI to achieve some coding/dev goal.

### Coding destination is distinct from VSCode's connectivity toolset

This idea I would love to be at a whiteboard to have a discussion. So for brevity here, I'll summarize and ask you fill in the gaps or ask me for clarification. Some distinctions are grey/blurred; please don't consider them absolute for this discussion.

 A user has two locations to configure:

* Coding destination is the computing unit on which the user wants to code/edit/compile/parse/etc.
* Connectivity toolset is the set of tools (typically contained in a computing unit) with which the user wants VSCode to execute its connectivity. This might be broader than only connectivity, but for now I'll simplify it as this.

In addition, VSCode's UI is distinct from its engine. This distinction somewhat exists today with `remote.extensionKind: workspace/ui`. However, as currently implemented it has collapsed together the coding destination + connectivity toolset.

### Thought example

I can imagine scenarios. A users wants to...

| Scenario | VSCode UI | VSCode connectivity | Coding destination |
|---|---|---|---|
| 1✔ | Windows 10 local | Windows API local | Windows 10 local |
| 2✔ | Windows 10 local | Windows API local | remote Ubuntu server via SSH |
| 3✔ | Windows 10 local | Windows API local | WSL |
| 4✔ | Windows 10 local | Windows API local | remote Docker container |
| 5✔ | Debian local | Linux ELF local | remote Docker container |
| 6✔ | Mac local | Mac Darwin local | remote Ubuntu server via SSH |
| 7❌ | Windows 10 local | WSL local | remote Ubuntu server via SSH |
| 8❌ | Windows 10 local | WSL local | remote Docker container |
| 9❌ | Windows 10 local | Docker local | remote Ubuntu server via SSH |

Drilldown to scenario 7...

1. VSCode UI runs on the local Windows 10 computer
2. User with VSCode UI chooses to connect to a remote Ubuntu server with SSH
3. VSCode uses an internal interface to SSH connect to that remote Ubuntu server
4. User has previously indicated in a setting that connectivity should be managed by WSL
5. VSCode uses WSL connectivity infrastructure to setup SSH to Ubuntu server
6. WSL connectivity infrastructure runs `ssh`, starts forwarding servers, tunnels, etc.
7. On successful connect, the VSCode UI is connected through WSL over SSH to the Ubuntu remote server.

The first 6 scenarios can usually be done today with VSCode. The last 3 are not possible with today's VSCode. I have a BAT script workaround for this scenario 7 which works reliably and I use daily for probably 6 months now. It is technically possible if connectivity is distinct from other components like most extensions.

Extensions are often higher-level components which are abstracted above and away from connectivity. For example, a php-lint extension runs `php-l` and parses its stdout. It is not involved with connectivity (TCP/IP, SSH, auth keys, etc.). The same for a compiler, UI pretty maker, or vcs. These types of extensions are associated with the "coding destination" not "connectivity".

### Diagnostics

In my real-world usage, my "holder/manager of secure keys" is in WSL. I use `gpg-agent` as I have a bank of gpg and ssh keys for communications, code/commit signing, encrypting, etc. `gpg-agent` provides native compatibility with the ssh-agent socket interface and I use it as such.

I ran some experiments to see how far I could push VSCode with workarounds. Scenario 7 is already possible with a BAT file that I use.

<details>
<summary>Click for Remote - SSH debug output of BAT workaround</summary>

```bash
[13:35:50.750] remote-ssh@0.48.0
[13:35:50.750] win32 x64
[13:35:50.758] SSH Resolver called for "ssh-remote+remoteserver1", attempt 1
[13:35:50.759] SSH Resolver called for host: remoteserver1
[13:35:50.759] Setting up SSH remote "remoteserver1"
[13:35:50.843] Using commit id "26076a4de974ead31f97692a0d32f90d735645c0" and quality "stable" for server
[13:35:50.845] Testing ssh with C:\njs\ssh.BAT -V
[13:35:51.236] ssh exited with code: 0
[13:35:51.238] Got stderr from ssh: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
[13:35:51.252] Running script with connection command: "C:\njs\ssh.BAT" -T -D 59560 remoteserver1 bash
[13:35:51.257] Install and start server if needed
[13:35:51.264] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[13:35:51.471] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\WINDOWS\System32\cmd.exe
[13:35:51.472] Got some output, clearing connection timeout
[13:35:51.483] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[13:35:51.494] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[13:35:51.513] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[13:35:51.539] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[13:35:56.738] > 264a78b9851c: running
[13:35:56.748] > 
> 
[13:35:56.756] > Acquiring lock on /home/dale/.vscode-server/bin/26076a4de974ead31f97692a0d32f90d
> 735645c0/vscode-remote-lock.26076a4de974ead31f97692a0d32f90d735645c0
> 
[13:35:56.765] > Found existing installation at /home/dale/.vscode-server/bin/26076a4de974ead31f9
> 7692a0d32f90d735645c0...
> 
[13:35:56.774] > SSH_CONNECTION=192.168.2.23 59561 192.168.2.5 22
[13:35:56.783] > 
> LANG=en_US.UTF-8
> XDG_SESSION_ID=526
> USER=dale
> PWD=/home/dale
> HOME=/home/dale
> SSH_CLIENT=192.168.2.23 59561 22
> MAIL=/var/mail/dale
> SHELL=/bin/bash
> SHLVL=2
> VSCODE_AGENT_FOLDER=/home/dale/.vscode-server
> LOGNAME=dale
> XDG_RUNTIME_DIR=/run/user/1000
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/us
> r/local/games
> _=/usr/bin/printenv
> Starting server...
> Waiting for server log...
> 
[13:35:57.293] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,  
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
[13:35:57.301] > 
> 
[13:35:57.312] > 264a78b9851c: start
> sshAuthSock====
> agentPort==41091==
> webViewServerPort====
> osReleaseId==ubuntu==
> arch==x86_64==
> webUiAccessToken====
> 264a78b9851c: end
[13:35:57.312] Received install output: 
sshAuthSock====
agentPort==41091==
webViewServerPort====
osReleaseId==ubuntu==
arch==x86_64==
webUiAccessToken====

[13:35:57.313] Remote server is listening on port 41091
[13:35:57.313] Parsed server configuration: {"agentPort":41091,"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":""}
[13:35:57.318] Starting forwarding server. localPort 59564 -> socksPort 59560 -> remotePort 41091
[13:35:57.320] Forwarding server listening on 59564
[13:35:57.320] Waiting for ssh tunnel to be ready
[13:35:57.325] Tunneled remote port 41091 to local port 59564
[13:35:57.325] Resolved "ssh-remote+remoteserver1" to "127.0.0.1:59564"
[13:35:57.329] ------




[13:35:57.330] [Forwarding server 59564] Got connection 0
[13:35:57.332] > 
> 
[13:35:57.358] [Forwarding server 59564] Got connection 1
[13:35:57.359] [Forwarding server 59564] Got connection 2
[13:35:58.651] [Forwarding server 59564] Got connection 3
[13:35:58.652] [Forwarding server 59564] Got connection 4
[13:35:58.652] [Forwarding server 59564] Got connection 5
[13:35:58.653] [Forwarding server 59564] Got connection 6
[13:37:43.773] [Forwarding server 59564] Got connection 7
```
</details>

That now provides me a great solution where I can keep my keys in WSL's `gpg`, and use WSL's `ssh` to connect to and compile on my remote Ubuntu server. Naturally, a wide base of users shouldn't use a BAT workaround nor workarounds like https://code.visualstudio.com/docs/remote/troubleshooting#_using-an-ssh-tunnel-to-connect-to-a-remote-docker-host

Such a `ssh.BAT` workaround also won't work with `ms-azuretools.vscode-docker` extension. That extension uses the `docker-modem` module which itself uses `ssh2` client which itself works in Windows, WSL, cygwin, etc. by using that environment's ssh agent mechanisms. So if `docker-modem` runs in Windows APIs environment, it won't use WSL `ssh`.

This `ms-azuretools.vscode-docker` Docker extension was installed "globally". That didn't work. So I had to force that extension to run in `workspace` + open VSCode as remote into WSL. Note, I also put username, it didn't pull from sshconfig file due to https://github.com/mscdex/ssh2/issues/604

settings.json
```json
{
    "remote.extensionKind": {
        "ms-azuretools.vscode-docker": "workspace",
    },
    "remote.WSL.debug": true,
    "remote.SSH.showLoginTerminal": true,
    "docker.host": "ssh://dale@remoteserver1"
}
```

With those settings and opening VSCode into WSL, I was able to get Docker containers in the left panes, images, etc. I successfully opened a shell into a container with `pane->container->right-click->shell`. Note that there was no entry `F1 -> Remote-Containers: Attach to running container`. 
However, if I chose `container pane-> container-> attach VSCode to container`, it quietly
failed. In dev tools I saw that Remote Container extension was still operating in a Windows mindset. It was not operating in a WSL/Linux approach/environment.

```
ERR connect ENOENT \\.\pipe\openssh-ssh-agent: Error: connect ENOENT \\.\pipe\openssh-ssh-agent
	at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
```

`ms-vscode-remote.remote-containers` was also installed globally. I somehow need to have that extension run in WSL. So I added it to the settings.json for the WSL environment, e.g.

WSL settings.json
```
"remote.extensionKind": {
        "ms-azuretools.vscode-docker": "workspace",
        "ms-vscode-remote.remote-containers": "workspace",
    },
```

Now I launched VSCode into WSL. Installed the `ms-vscode-remote.remote-containers` into WSL, restarted VSCode, then `Docker container pane-> container-> right-click Attach`. I got a new VSCode Window, with bottom left reporting "opening remote" and bottom right "installing dev container". If I click for details I see:
```
Start: resolving remote
Setting up container rsync
```

and then forever nothing. If I open dev tools I again see:
```
ERR connect ENOENT \\.\pipe\openssh-ssh-agent: Error: connect ENOENT \\.\pipe\openssh-ssh-agent
	at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
```

I suspect this is because when the new VSCode window was created, it reset the "workspace" to be "Windows API" instead of WSL. Therefore, the connectivity components are again not using the WSL tools that are needed. The concepts of "Coding destination" and "Connectivity toolset" were collapsed together and jointly reset to Windows API.

**Comment by chrmarti** [comment]
Thanks for the detailed write-up. I'll take this as a feature request. Using WSL for connectivity is - as you explain - currently not supported.

**Comment by chrmarti** [comment]
Some progress is available with 0.109.0 of the extension (currently available with VS Code Insiders) where there is an experimental setting to run the Docker CLI on the WSL side:
![image](https://user-images.githubusercontent.com/9205389/78004417-5c2d6e00-733a-11ea-972f-b20cdb0f370c.png)

(The `SSH_AUTH_SOCK` is still wrong though.)

**Comment by chrmarti** [comment]
@diablodale This should work now with the WSL2 support (including `SSH_AUTH_SOCK`). If you are connecting to some other Docker host, you still have to open a Remote-WSL window first to make Remote-Containers use WSL when connecting. Does that work for you?

**Comment by diablodale** [comment]
Hi. I don't see any useful improvement in a quick test.

### Setup

```
Version: 1.50.1 (system setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
```

* My default distro is WSL2 Ubuntu 20.04. I have a 2nd distro of WSL1 Ubuntu 18.04 installed. The latter is my years long running distro and was used in the OP
* In this default WSL2 distro is installed `docker-ce/focal,now 5:19.03.13~3-0~ubuntu-focal amd64 [installed]` and `docker-ce-cli/focal,now 5:19.03.13~3-0~ubuntu-focal amd64 [installed]`
* On windows login, the following three are started in that WSL2 distro: docker service, gpg-agent, dirmngr
* Docker is setup so that I don't need to sudo

### Repro

1. I see no Remote>Containers setting in the vscode settings UI about WSL2 related to this issue. Therefore no changes to settings has been made.
2. In WSL2 `docker run -ti -d ubuntu:18.04`
3. Verify container is running with `docker container ls`
4. Click on Remote Explorer icon on left icon bar in VSCode
5. Choose "containers" in the top right pulldown 

### Result

Nothing is shown except for "Get started with containers by installing and starting Docker or by visiting the help view".

### Expected

List the Ubuntu 18.04 container currently running on the WSL2 localhost

### Repro

6. Open terminal in VSCode. Therefore it is opening into my WSL2 Ubuntu 20.04
7. `export DOCKER_HOST="ssh://local-lan-server-with-docker-containers-running"`
8. `docker container ls`
9. Verify a list of container on that remove lan server is listed
10. Edit `.profile` and `.bashrc` and put a line in there of `export DOCKER_HOST="ssh://local-lan-server-with-docker-containers-running"`. Save both.
11. Save .profile
12. Press F1 in VSCode to reload window
13. Click on left tab Remove Explorer icon
14. pulldown=containers

### Result

Nothing is shown except for "Get started with containers by installing and starting Docker or by visiting the help view".

### Expected

List the many containers currently running on the remote LAN host

### Notes

One problem I see is that VSCode/extensions continue to *not* use WSL toolsets in these scenarios.
I verified this by turning on F1 -> Developer Tools, then reloading VSCode window, clicking on the left remote tab, again pulldown=containers....and I see errors.

```
Error: EEXIST: file already exists, mkdir 'c:\Users\dale\AppData\Roaming\Code\logs\20201025T125134\exthost4\ms-vscode-remote.remote-containers'

Error: spawn C:\Program Files\Microsoft VS Code\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)

Error: EEXIST: file already exists, mkdir 'c:\Users\dale\AppData\Roaming\Code\logs\20201025T125134\exthost4\ms-vscode-remote.remote-containers'

rejected promise not handled within 1 second: Error: spawn C:\Program Files\Microsoft VS Code\docker ENOENT

stack trace: Error: spawn C:\Program Files\Microsoft VS Code\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)

ERR spawn C:\Program Files\Microsoft VS Code\docker ENOENT: Error: spawn C:\Program Files\Microsoft VS Code\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

This suggests to me that some part of VSCode/extension is trying to run a Win32 binary at `C:\Program Files\Microsoft VS Code\docker`
Naturally, this will fail. It should be running `docker` in WSL2, and it should be using paths.

**Comment by chrmarti** [comment]
Ack, that's not fully implemented yet, thanks. Related: #3534

**Comment by chrmarti** [comment]
Also related: #3764

**Comment by chrmarti** [comment]
Published partial fixes with 0.148.0 of the extension (currently requires VS Code Insiders). One limitation is that you need to open a WSL window and open any folder in that (an empty WSL window won't work due to #3638).
