### ISSUE TITLE
SSH unable to connect - error spawn UNKNOWN

### ISSUE THREAD

**Issue by andreeas26** [microsoft/vscode-remote-release#2128]
Hi! I am trying to connect to a remote VM with SSH and a private key, but I get this strange error. On a different machine the connection works.
I've tried uninstalling and installing again VSCode and its extensions, but to no good. Also, I am able to connect to the VM in git bash with `ssh user@IP -i path/to/key,` and the command `ssh -V` works in the VM. I think there is a problem with VScode or the remote extension.

- VSCode Version: 1.41.1 (user setup), Commit: 26076a4de974ead31f97692a0d32f90d735645c0
- Local OS Version: Windows_NT x64 10.0.14393
- Remote OS Version: Ubuntu 16.04.4 LTS
- Remote Extension/Connection Type: SSH

This is the output from Remote - SSH window

```
[13:46:44.190] remote-ssh@0.48.0
[13:46:44.190] win32 x64
[13:46:44.195] SSH Resolver called for "ssh-remote+IP", attempt 1
[13:46:44.195] SSH Resolver called for host: IP
[13:46:44.195] Setting up SSH remote "IP"
[13:46:44.248] Using commit id "26076a4de974ead31f97692a0d32f90d735645c0" and quality "stable" for server
[13:46:44.251] Testing ssh with ssh -V
[13:46:44.262] Finding installed ssh failed: spawn UNKNOWN
[13:46:44.262] Resolver error: spawn UNKNOWN
[13:46:44.263] ------
```

And the log (Window)

```[2020-01-06 13:46:44.470] [renderer3] [error] [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
[2020-01-06 13:46:44.470] [renderer3] [error] Error: spawn UNKNOWN
	at ChildProcess.spawn (internal/child_process.js:394:11)
	at Object.spawn (child_process.js:548:9)
	at c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:147263
	at new Promise (<anonymous>)
	at O (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:147187)
	at C (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:147138)
	at c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:149643
	at k (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:149671)
	at E (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:146955)
	at R (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:146864)
	at Object.t.generateMultiLineCommand (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:148124)
	at c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:284585
	at async k (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:283680)
	at async Object.t.resolve (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:288133)
	at async c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:127:97574
[2020-01-06 13:46:44.512] [renderer3] [error] spawn UNKNOWN: Error: spawn UNKNOWN
	at ChildProcess.spawn (internal/child_process.js:394:11)
	at Object.spawn (child_process.js:548:9)
	at c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:147263
	at new Promise (<anonymous>)
	at O (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:147187)
	at C (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:147138)
	at c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:149643
	at k (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:149671)
	at E (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:146955)
	at R (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:146864)
	at Object.t.generateMultiLineCommand (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:148124)
	at c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:284585
	at async k (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:283680)
	at async Object.t.resolve (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:288133)
	at async c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:127:97574
[2020-01-06 13:46:45.719] [renderer3] [error] spawn UNKNOWN: Error: spawn UNKNOWN
	at ChildProcess.spawn (internal/child_process.js:394:11)
	at Object.spawn (child_process.js:548:9)
	at c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:147263
	at new Promise (<anonymous>)
	at O (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:147187)
	at C (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:147138)
	at c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:149643
	at k (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:149671)
	at E (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:146955)
	at R (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:146864)
	at Object.t.generateMultiLineCommand (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:148124)
	at c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:284585
	at async k (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:283680)
	at async Object.t.resolve (c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:1:288133)
	at async c:\Users\andreea.sandu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.48.0\out\extension.js:127:97574
[2020-01-06 13:55:54.183] [renderer3] [error] Could not fetch environment: Error: Could not fetch environment
    at file:///C:/Users/andreea.sandu/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3798:126```

**Comment by andreeas26** [comment]
I solved the issue. The problem was that VSCode was getting from Path the wrong Git. Before switching to Remote SSH I was using MobaXterm for development which includes a git installation. This was the one VSCode was using in the first place. 

Maybe this will help someone else.
