### ISSUE TITLE
Docker path is being improperly resolved in Remote Container extension

### ISSUE THREAD

**Issue by MarcPow** [microsoft/vscode-remote-release#2298]
- VSCode Version: 1.41.1
- Local OS Version: 18363.592
- Remote OS Version:
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Simply open a dev container

[67 ms] Failed: Building an image from the Dockerfile (this can take a while).
[72 ms] Error: File not found: c:\Program Files\Docker\docker  ** This is not the real path **
        at new WindowsPtyAgent (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsPtyAgent.js:77:36)
        at new WindowsTerminal (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsTerminal.js:49:24)
        at Object.spawn (c:\Program Files\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\index.js:28:12)
        at c:\Users\marcpow\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:8613
        at new Promise (<anonymous>)
        at Object.I [as runCommand] (c:\Users\marcpow\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:8574)
        at async Object.R [as showProgress] (c:\Users\marcpow\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:8988)
        at async c:\Users\marcpow\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:64429
        at async Object.t.openDockerfileDevContainer (c:\Users\marcpow\.vscode\extensions\ms-vscode-remote.remote-containers-0.94.0\dist\extension.js:1:64071)

**Comment by chrmarti** [comment]
Is this still a problem with the latest release (0.101.0)? If so, please check that `docker.exe`'s folder is part of the `PATH` environment variable.

**Comment by fshamakhov** [comment]
- VSCode Version 1.42.0
- Local OS Version: 18363.628
- Remote Extension/Connection Type: Docker

I have `C:\Program Files\Docker\Docker\resources\bin;` in my `Path` environment variable and get the same error trying to `Open Folder in Container`. But it tries to find `docker` in my `${localWorkspaceFolder}`

I tried to add 
```
"remoteEnv": {
    "PATH": "C:\\Program Files\\Docker\\Docker\\resources\\bin;${localEnv:PATH}",
},
``` 
to my `devcontainer.json` but it did not help.

**Comment by AlexKClarify** [comment]
You should have a look if the docker \resources\bin is listed in the Windows **user variable** PATH and if not add it.
In my case it was only listed in the system variables PATH but apparently that has not been sufficient to run the dev container.

**Comment by chrmarti** [comment]
@MarcPow Is `c:\Program Files\Docker` on your PATH? (We try to find docker.exe based on `PATH` and somehow that came up with `c:\Program Files\Docker\docker`.)

@fshamakhov Does `docker ps` work from Powershell / Cmd? Please append the full log.

**Comment by chrmarti** [comment]
Fixing with #2358.
