### ISSUE TITLE
Sample container fails to start

### ISSUE THREAD

**Issue by michalrames** [microsoft/vscode-remote-release#2358]
Issue Type: <b>Bug</b>

I cannot connect VSCode to any remote container. Docker is running and there are no issues using docker outside of VSCODE. The simplest way to replicate:

1) Click "Open a remote Window" or launch a command window (ctrl+shift+p)
2) Click "Remote containers: try a sample..."  and choose any sample image
... new window opens. Terminal produces the following error (unfortunately I'm not sure how to debug extensions.js):
```
[0 ms] Start: Resolving remote
[5 ms] Start: Check Docker is running
[37 ms] Start: Run: docker build -f c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.101.0\scripts\volumeBootstrap.Dockerfile -t vsc-volume-bootstrap c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.101.0\scripts
[69 ms] Error: File not found: C:\Program Files\docker
        at new WindowsPtyAgent (c:\Users\micha\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsPtyAgent.js:77:36)
        at new WindowsTerminal (c:\Users\micha\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsTerminal.js:49:24)
        at Object.spawn (c:\Users\micha\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\index.js:28:12)
        at c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.101.0\dist\extension.js:1:8432
        at new Promise (<anonymous>)
        at Object.I [as runCommand] (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.101.0\dist\extension.js:1:8393)
        at async c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.101.0\dist\extension.js:1:166387
        at async Object.C [as cloneAndBuildRepository] (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.101.0\dist\extension.js:1:166253)
        at async Object.t.openDockerfileRepoDevContainer (c:\Users\micha\.vscode\extensions\ms-vscode-remote.remote-containers-0.101.0\dist\extension.js:1:177691)
```

System details:
* windows 10
* Docker desktop 2.2.1.0, with docker 19.03.5. The executable `docker.exe` is on the PATH

Extension version: 0.101.0
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:46:03.121Z)
OS version: Windows_NT ia32 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (16.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Looks like https://github.com/microsoft/vscode-remote-release/issues/2298. Not sure what could cause this. The relevant code hasn't changed in a while, we simply go through all `PATH` entries and check if there is a `docker` executable in that folder. Is `C:\Program Files` on your `PATH`?

**Comment by michalrames** [comment]
@chrmarti Yes, indeed there was `C:\Program Files` on my (system) PATH. Not sure why. Removing the entry solved the issue - appreciate your quick response. 

Is it the case that the extension finds a Docker directory (by name) under `C:\Program Files` and thinks it's the executable?

**Comment by chrmarti** [comment]
@michalrames Yes, you're right! I'll fix that.
