### ISSUE TITLE
git pull fails in remote container

### ISSUE THREAD

**Issue by hholst80** [microsoft/vscode-remote-release#2441]
- VSCode Version: 1.42.1
- Local OS Version: Ubuntu 19.10

Steps to Reproduce:

I am not sure. Working on it. Posting here for exposure.

```
➜  api-server git:(master) git pull
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module '/tmp/vscode-remote-containers-298bed45ba497798741c3bdfaaa587a0a48d7175.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Password for 'https://hholst80@github.com': 
➜  api-server git:(master) 
```

**Comment by chrmarti** [comment]
This should be updated when you reconnect. Does this also occur with VS Code Insiders (https://code.visualstudio.com/insiders/) that has a newer version of the extension?

**Comment by hholst80** [comment]
```
[0 ms] Start: Resolving remote
[4 ms] Setting up container {REMOVED}

[195 ms] Start: Check Docker is running
[276 ms] Start: Inspecting container
[328 ms] Start: Run: C:\Program Files\Docker\Docker\resources\bin\docker.exe exec -i -u ubuntu -e VSCODE_REMOTE_CONTAINERS_SESSION=bbbb5da1-484b-4db3-a16b-54b700d523b61583435446065 9b21f48d3e92b19b944949df340c8e1623a4bbd74f00cecf62a848950e5897f9 /bin/sh
[342 ms] Start: Run in container: uname -m
[929 ms] x86_64
[930 ms] 
[930 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[938 ms] NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"
VERSION_ID="19.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
[938 ms] 
[939 ms] Start: Run in container: cat /etc/passwd
[949 ms] Start: Run in container: test -d /home/ubuntu/.vscode-server-insiders
[955 ms] 
[956 ms] 
[956 ms] Exit code 1
[956 ms] Start: Run in container: test -d /home/ubuntu/.vscode-remote
[962 ms] 
[962 ms] 
[962 ms] Exit code 1
[963 ms] Start: Run in container: set -o noclobber ; mkdir -p '/home/ubuntu/.vscode-server-insiders/data/Machine' && { > '/home/ubuntu/.vscode-server-insiders/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[975 ms] 
[975 ms] 
[975 ms] Start: Run in container: test -d /home/ubuntu/.vscode-server-insiders/bin/b53d3c26f35df3da2d3f2ed472e73c8edf4f90d0
[982 ms] 
[982 ms] 
[982 ms] Exit code 1
[982 ms] Installing VS Code Server for commit b53d3c26f35df3da2d3f2ed472e73c8edf4f90d0
[982 ms] Start: Run in container: mkdir -p /home/ubuntu/.vscode-server-insiders/bin/b53d3c26f35df3da2d3f2ed472e73c8edf4f90d0_1583435448112
[990 ms] 
[991 ms] 
[992 ms] Start: Downloading VS Code Server
[4245 ms] Start: Run: C:\Program Files\Docker\Docker\resources\bin\docker.exe exec -i -u ubuntu -w /home/ubuntu/.vscode-server-insiders/bin/b53d3c26f35df3da2d3f2ed472e73c8edf4f90d0_1583435448112 9b21f48d3e92b19b944949df340c8e1623a4bbd74f00cecf62a848950e5897f9 tar --no-same-owner -xz --strip-components 1
[7509 ms] 
[7510 ms] tar: node: Wrote only 2048 of 10240 bytes
tar: Exiting with failure status due to previous errors

[7517 ms] Command failed: tar --no-same-owner -xz --strip-components 1
```

**Comment by hholst80** [comment]
Same problem. A very much unwanted feature that I at least would like to be able to opt out from.

```
[credential]
        helper = "!f() { /home/ubuntu/.vscode-server-insiders/bin/b53d3c26f35df3da2d3f2ed472e73c8edf4f90d0/node /tmp/vscode-remote-containers-e4d5d900fc80073c86e1e2491571d3bb367467c6.js $*; }; f"
```

**Comment by hholst80** [comment]
A workaround is to run a sed in your terminal conf

```
sed 's/helper = .*/helper = cache/' -i ~/.gitconfig
```

**Comment by hholst80** [comment]
Just tried this in the latest insider release. In any way the problem is sort of still there. It will allow me to push, but it has disabled my cache settings. I am not happy about that.

The ugly hack that injected itself into my gitconfig also has the bad habit of emitting my password to the console. Really bad if I should say be on a recorded teams meeting and doing a demo.

```
$ git push                                                      
Remote-Containers CLI: RPC pipe not configured. Message: {"command":"fill","stdin":"protocol=https\nhost=github.com\n"}
Username for 'https://github.com': hholst80
Password for 'https://hholst80@github.com': 
Remote-Containers CLI: RPC pipe not configured. Message: {"command":"approve","stdin":"protocol=https\nhost=github.com\nusername=hholst80\npassword=CLEARTEXT\n"}
Enumerating objects: 34, done.
Counting objects: 100% (28/28), done.
Delta compression using up to 8 threads
Compressing objects: 100% (16/16), done.
Writing objects: 100% (16/16), 1.62 KiB | 1.62 MiB/s, done.
Total 16 (delta 12), reused 0 (delta 0)
remote: Resolving deltas: 100% (12/12), completed with 9 local objects.
To https://github.com/X/Y.git
   a98d2c6..5371865  master -> master
```

**Comment by chrmarti** [comment]
We could add a user setting to disable this feature.

**Comment by hholst80** [comment]
Please allow users to disable the feature completely, much appreciated!
