### ISSUE TITLE
Downloading VS Code Server results in "Client network socket disconnected before secure TLS connection was established" error

### ISSUE THREAD

**Issue by slavdok** [microsoft/vscode-remote-release#2480]
I am following https://code.visualstudio.com/docs/remote/containers#_quick-start-try-a-dev-container

- I did `git clone https://github.com/Microsoft/vscode-remote-try-java`
- Clicked the "Open a remote window" at the bottom left
- Selected "Remote-Containers: Open Folder in Container..." and pointed to the folder I just git cloned.

It now opens a new VS Code window and starts the building/installation process.
Once it reaches the "Start: Downloading VS Code Server", it errors out

```
[2020-03-04T21:00:40.873Z] [PID 11956] [112493 ms] Installing VS Code Server for commit c47d83b293181d9be64f27ff093689e8e7aed054
[2020-03-04T21:00:40.873Z] [PID 11956] [112493 ms] Start: Run in container: mkdir -p /home/vscode/.vscode-server/bin/c47d83b293181d9be64f27ff093689e8e7aed054_1583355640873
[2020-03-04T21:00:40.876Z] [PID 11956] [112496 ms] 
[2020-03-04T21:00:40.876Z] [PID 11956] [112496 ms] 
[2020-03-04T21:00:40.877Z] [PID 11956] [112497 ms] Start: Downloading VS Code Server
[2020-03-04T21:00:41.360Z] [PID 11956] [112980 ms] Error: Client network socket disconnected before secure TLS connection was established
	at connResetException (internal/errors.js:559:14)
	at TLSSocket.onConnectEnd (_tls_wrap.js:1355:19)
	at Object.onceWrapper (events.js:288:20)
	at TLSSocket.emit (events.js:205:15)
	at endReadableNT (_stream_readable.js:1154:12)
	at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

This exact thing happens on everything I tried to do:
- Open folder in container
- Open workspace in container
- Attach to running container
- Try a sample

The Docker extension connects to Docker Desktop with DOCKER_HOST setting `tcp://localhost:2375`
It's working fine. I can see my images and containers. 
I can even see the containers that the Remote extension tries to create. They are stopped. But can be started and "Attach Shell" to.

VSCode Version: 1.42.1
Extension Remote - Containers: 0.101.1
Extension Microsoft Docker : 0.10.0
Docker Desktop: 2.2.0.3
Docker Engine: 19.03.5
Windows 10 Pro 1909

I tried disabling all Windows Firewall. Same result

**Comment by chrmarti** [comment]
Please update to the latest VS Code (1.50, soon 1.51) and Remote-Containers (0.145.1, soon 0.148.0) versions and check if this is still a problem.
