### ISSUE TITLE
shell server

### ISSUE THREAD

**Issue by sbehara** [microsoft/vscode-remote-release#2524]

**Comment by chrmarti** [comment]
@sbehara Could you try VS Code Insiders 1.44 with the latest extension 0.107.0 and check if the problem is still there?

**Comment by sbehara** [comment]
Version: 1.44.0-insider (user setup)
Commit: ef75c4bb445e5021065cf0012cfa2c66e55bfa16
Date: 2020-03-11T09:14:53.536Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

Container Build Log attached:
/files/4319818/vscode_insiders_144_RemoteContainers.log)

Dockerfile and devcontainer.json

[devcontainer.json.txt](https://github.com/microsoft/vscode-remote-release/files/4319824/devcontainer.json.txt)
[Dockerfile.txt](https://github.com/microsoft/vscode-remote-release/files/4319825/Dockerfile.txt)

**Comment by chrmarti** [comment]
I think your `"postCreateCommand"` might not terminate. If you need to run `httpd` in the background, you can set `"overrideCommand": false` in the devcontainer.json and set `CMD /usr/sbin/httpd` in the Dockerfile.

**Comment by sbehara** [comment]
The same setup works in 1.41
However, here is the new error message after adding CMD ["/usr/sbin/httpd"] in Dockerfile and adding "overrideCommand":false in devcontainer.json.

[3548 ms] Start: Run: docker inspect --type container 0baa899d6dc6
[3810 ms] Start: Inspecting container
[3810 ms] Start: Run: docker inspect --type container 0baa899d6dc6e2f094b56745b5236a3630426d4eb4ece07ec739231301c6fa20
[3954 ms] Start: Run: C:\Program Files\Docker\Docker\resources\bin\docker.exe exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=2c9e163a-9f31-47e8-8629-8bffbd5294d31584035943610 0baa899d6dc6e2f094b56745b5236a3630426d4eb4ece07ec739231301c6fa20 /bin/sh
[3959 ms] Start: Run in container: uname -m
[4094 ms] Start: Run in container: cat /etc/passwd
[4094 ms] Stdin closed!
[4097 ms] Shell server terminated (code: 1, signal: null)

Error response from daemon: Container 0baa899d6dc6e2f094b56745b5236a3630426d4eb4ece07ec739231301c6fa20 is not running

**Comment by chrmarti** [comment]
The container’s CMD seems to terminate and with it the container.

**Comment by purplezimmermann** [comment]
@sbehara @chrmarti 

Is there any progress on this issue? I run into a pretty similar failure:

```[22 ms] Start: Check Docker is running
[88 ms] Start: Run: git rev-parse --show-toplevel
[507 ms] Start: Inspecting container
[533 ms] Start: Run: C:\ProgramData\chocolatey\bin\docker.exe exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=fee18736-6a2d-4a87-ae85-8f64a7c281701585524102001 8e4a8daaa4f71fc516e18b8ebf1e2f8c04e2c92fd4d6b2ee161ff88dbc305211 /bin/sh
[544 ms] Start: Run in container: uname -m
[1458 ms] Start: Run in container: cat /etc/passwd
[1458 ms] Stdin closed!
[1462 ms] Shell server terminated (code: 0, signal: null)
```

No `CMD` and no `overrideCommand` are set

And in my case, the container is still running afterwards

```
> code --version
1.43.2
0ba0ca52957102ca3527cf479571617f0de6ed50
x64
```

**Comment by chrmarti** [comment]
@purplezimmermann It seems `/bin/sh` in the container exits (code 0) for some reason maybe after running `uname -m` or `cat /etc/passwd`. Is there anything special with your container? What version of Docker are you using and could you post a simple Dockerfile with which the problem repros?

**Comment by purplezimmermann** [comment]
@chrmarti 

```
> docker --version
Docker version 17.06.0-ce, build 02c1d87
```

```
> docker-machine --version
docker-machine.exe version 0.15.0, build b48dc28d
```

Stripped down version of my `Dockerfile` (only leaving out additional `apt` packages of build tools and dependency libraries for my C++ project):

```dockerfile
FROM ubuntu:focal

ENV DEBIAN_FRONTEND=noninteractive                                          \
    EDITOR=vim                                                              \
    LANG=en_US.UTF-8                                                        \
    PAGER="less -rF"                                                        \
    TERM=xterm                                                              \
    TZ=UTC

RUN apt-get update                                                          \
&&  apt-get install --yes --no-install-recommends                           \
        locales                                                             \
                                                                            \
&&  locale-gen $LANG                                                        \
&&  update-locale                                                           \
                                                                            \
&&  apt-get install --yes --no-install-recommends                           \
        bash                                                                \
        less                                                                \
        openssh-server                                                      \
        vim                                                                 \
                                                                            \
&&  apt-get clean                                                           \
&&  rm -rf /var/lib/apt/lists/*

RUN rm -f /etc/ssh/ssh_host_rsa_key                                         \
&&  ssh-keygen -N "" -f /etc/ssh/ssh_host_rsa_key
```

And my `devcontainer.json` (using your `workspaceMount` workaround from https://github.com/microsoft/vscode-remote-release/issues/509#issuecomment-497596751):

```js
{
    "name": "Remote Development Container",
    "dockerFile": "Dockerfile",
    "workspaceMount": "",

    "extensions": [
        "ms-vscode.cmake-tools",
        "ms-vscode.cpptools",
    ],

    "settings": {
        "terminal.integrated.shell.linux": "/bin/bash",
    }
}
```

**Comment by purplezimmermann** [comment]
@chrmarti And here is the complete **Developer Tools Console** output:

```
console.ts:137 [Extension Host] Failed to process Docker context. Falling back to default. Error: SyntaxError: Unexpected end of JSON input
t.log @ console.ts:137
console.ts:137 [Extension Host] Shell server terminated (code: 0, signal: null)
t.log @ console.ts:137
extensionService.ts:464 Error
    at e.resolveAuthority (extensionHostProcessManager.ts:272)
    at processTicksAndRejections (internal/process/task_queues.js:85)
    at async K._scanAndHandleExtensions (extensionService.ts:458)
    at async K._initialize (abstractExtensionService.ts:101)
extensionService.ts:466 Not showing a notification for the error
extensionHostProcessManager.ts:73 Error received from starting extension host
(anonymous) @ extensionHostProcessManager.ts:73
extensionHostProcessManager.ts:74 Error
    at e.resolveAuthority (extensionHostProcessManager.ts:272)
    at processTicksAndRejections (internal/process/task_queues.js:85)
    at async K._scanAndHandleExtensions (extensionService.ts:458)
    at async K._initialize (abstractExtensionService.ts:101)
(anonymous) @ extensionHostProcessManager.ts:74
log.ts:197   ERR [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
log.ts:197   ERR Error
    at e.resolveAuthority (extensionHostProcessManager.ts:272)
    at processTicksAndRejections (internal/process/task_queues.js:85)
    at async K._scanAndHandleExtensions (extensionService.ts:458)
    at async K._initialize (abstractExtensionService.ts:101)
log.ts:197   ERR Unable to read file 'vscode-remote://dev-container+633a5c55736572735c73746566616e7a5c414456415c63702d73646e2d74656c65666f6e6963612d64656d6f/workspaces/cp-sdn-telefonica-demo/.vscode/settings.json' (Error): Error: Unable to read file 'vscode-remote://dev-container+633a5c55736572735c73746566616e7a5c414456415c63702d73646e2d74656c65666f6e6963612d64656d6f/workspaces/cp-sdn-telefonica-demo/.vscode/settings.json' (Error)
    at _.doReadAsFileStream (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1667:417)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
log.ts:197   ERR Unable to read file 'vscode-remote://dev-container+633a5c55736572735c73746566616e7a5c414456415c63702d73646e2d74656c65666f6e6963612d64656d6f/workspaces/cp-sdn-telefonica-demo/.vscode/tasks.json' (Error): Error: Unable to read file 'vscode-remote://dev-container+633a5c55736572735c73746566616e7a5c414456415c63702d73646e2d74656c65666f6e6963612d64656d6f/workspaces/cp-sdn-telefonica-demo/.vscode/tasks.json' (Error)
    at _.doReadAsFileStream (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1667:417)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
log.ts:197   ERR Unable to read file 'vscode-remote://dev-container+633a5c55736572735c73746566616e7a5c414456415c63702d73646e2d74656c65666f6e6963612d64656d6f/workspaces/cp-sdn-telefonica-demo/.vscode/launch.json' (Error): Error: Unable to read file 'vscode-remote://dev-container+633a5c55736572735c73746566616e7a5c414456415c63702d73646e2d74656c65666f6e6963612d64656d6f/workspaces/cp-sdn-telefonica-demo/.vscode/launch.json' (Error)
    at _.doReadAsFileStream (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1667:417)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
log.ts:197   ERR Unable to read file 'vscode-remote://dev-container+633a5c55736572735c73746566616e7a5c414456415c63702d73646e2d74656c65666f6e6963612d64656d6f/workspaces/cp-sdn-telefonica-demo/.vscode/settings.json' (Error): Error: Unable to read file 'vscode-remote://dev-container+633a5c55736572735c73746566616e7a5c414456415c63702d73646e2d74656c65666f6e6963612d64656d6f/workspaces/cp-sdn-telefonica-demo/.vscode/settings.json' (Error)
    at _.doReadAsFileStream (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1667:417)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
log.ts:197   ERR Unable to read file 'vscode-remote://dev-container+633a5c55736572735c73746566616e7a5c414456415c63702d73646e2d74656c65666f6e6963612d64656d6f/workspaces/cp-sdn-telefonica-demo/.vscode/tasks.json' (Error): Error: Unable to read file 'vscode-remote://dev-container+633a5c55736572735c73746566616e7a5c414456415c63702d73646e2d74656c65666f6e6963612d64656d6f/workspaces/cp-sdn-telefonica-demo/.vscode/tasks.json' (Error)
    at _.doReadAsFileStream (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1667:417)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
log.ts:197   ERR Unable to read file 'vscode-remote://dev-container+633a5c55736572735c73746566616e7a5c414456415c63702d73646e2d74656c65666f6e6963612d64656d6f/workspaces/cp-sdn-telefonica-demo/.vscode/launch.json' (Error): Error: Unable to read file 'vscode-remote://dev-container+633a5c55736572735c73746566616e7a5c414456415c63702d73646e2d74656c65666f6e6963612d64656d6f/workspaces/cp-sdn-telefonica-demo/.vscode/launch.json' (Error)
    at _.doReadAsFileStream (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1667:417)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
log.ts:197   ERR An unknown error occurred. Please consult the log for more details.: Error
    at e.resolveAuthority (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3692:473)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async K._scanAndHandleExtensions (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4043:3)
    at async K._initialize (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3569:517)
log.ts:197   ERR Could not fetch environment: Error: Could not fetch environment
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3977:651
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
log.ts:197   ERR An unknown error occurred. Please consult the log for more details.: Error
    at e.resolveAuthority (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3692:473)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async K._scanAndHandleExtensions (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4043:3)
    at async K._initialize (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3569:517)
```

**Comment by chrmarti** [comment]
@purplezimmermann I wonder if we do something that doesn't work with Docker version 17.06.0-ce. Could you update to the latest release of Docker and try again?

**Comment by yvess** [comment]
I have a similar issue

```
[2020-04-09T23:55:17.456Z] [PID 43668] [6085 ms] 
[2020-04-09T23:55:17.456Z] [PID 43668] [6085 ms] Start: Run in container: cat /etc/passwd
[2020-04-09T23:55:17.474Z] [PID 43668] [6103 ms] Start: Setup shutdown monitor
/var/folders/mb/zyw_g5297_vgs9s50bl01y_m0000gn/T/vscode-remote-containers-49bce5fc0a25c58a9ee10719020c847424801925.sock dockerCompose Info /Users/yserrano/Library/Application Support/Code/logs/20200410T014458/exthost3/ms-vscode-remote.remote-containers
[2020-04-09T23:55:17.491Z] [PID 43668] [6120 ms] Start: Run in container: test -d /root/.vscode-server
[2020-04-09T23:55:17.519Z] [PID 43668] [6148 ms] 
[2020-04-09T23:55:17.519Z] [PID 43668] [6148 ms] 
[2020-04-09T23:55:17.519Z] [PID 43668] [6148 ms] Start: Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[2020-04-09T23:55:17.533Z] [PID 43668] [6162 ms] 
[2020-04-09T23:55:17.533Z] [PID 43668] [6162 ms] 
[2020-04-09T23:55:17.533Z] [PID 43668] [6162 ms] Exit code 1
[2020-04-09T23:55:17.533Z] [PID 43668] [6162 ms] 
Support for Alpine Linux is in preview.

[2020-04-09T23:55:17.533Z] [PID 43668] [6162 ms] Start: Run in container: test -d /root/.vscode-server/bin/2aae1f26c72891c399f860409176fe435a154b13
[2020-04-09T23:55:17.577Z] [PID 43668] [6206 ms] 
[2020-04-09T23:55:17.577Z] [PID 43668] [6206 ms] 
[2020-04-09T23:55:17.577Z] [PID 43668] [6206 ms] Start: Launching Remote-Containers helper.
[2020-04-09T23:55:17.579Z] [PID 43668] [6208 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-1acc213cf744e9e0e7c5e0329c119308dde9f3e3.js' >/tmp/vscode-remote-containers-1acc213cf744e9e0e7c5e0329c119308dde9f3e3.js
[2020-04-09T23:55:17.785Z] [PID 43668] [6414 ms] Shell server terminated (code: 2, signal: null)
```

When I run the two command with exit code != 0 inside the container:

```bash
$ set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; }
ash: can't create /root/.vscode-server/data/Machine/.writeMachineSettingsMarker: File exists
$ echo $?
1
```

```bash
$ cat <<'EOF-/tmp/vscode-remote-containers-1acc213cf744e9e0e7c5e0329c119308dde9f3e3.js' >/tmp/vscode-remote-containers-1acc213cf744e9e0e7c5e0329c119308
dde9f3e3.js
ash: syntax error: illegal eof marker for << redirection
$ echo $?
2
```

- docker mac 2.2.0.4
- python container: alpine linux 3.7

**Comment by Onjrew** [comment]
I'm also experiencing this error.
```
$ docker --version
Docker version 19.03.8, build afacb8b
```
```
docker-compose --version
docker-compose version 1.25.5, build 8a1c60f6
```
My `.devcontainer.json`:
```
// For format details, see https://aka.ms/vscode-remote/devcontainer.json or this file's README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.117.0/containers/python-3
{
	"name": "Python 3",
	"dockerComposeFile": "../docker-compose.yml",
	"service": "app",

	// Set *default* container specific settings.json values on container create.
	"settings": { 
		"terminal.integrated.shell.linux": "/bin/bash",
		"python.pythonPath": "/usr/local/bin/python",
		"python.linting.enabled": true,
		"python.linting.pylintEnabled": true,
		"python.formatting.autopep8Path": "/usr/local/py-utils/bin/autopep8",
		"python.formatting.blackPath": "/usr/local/py-utils/bin/black",
		"python.formatting.yapfPath": "/usr/local/py-utils/bin/yapf",
		"python.linting.banditPath": "/usr/local/py-utils/bin/bandit",
		"python.linting.flake8Path": "/usr/local/py-utils/bin/flake8",
		"python.linting.mypyPath": "/usr/local/py-utils/bin/mypy",
		"python.linting.pycodestylePath": "/usr/local/py-utils/bin/pycodestyle",
		"python.linting.pydocstylePath": "/usr/local/py-utils/bin/pydocstyle",
		"python.linting.pylintPath": "/usr/local/py-utils/bin/pylint",
		"python.testing.pytestPath": "/usr/local/py-utils/bin/pytest"
	},
}
```

My `docker-compose.yml`:
```
version: '3'
services:
    app:
        build:
            context: .
            args:
                VARIANT: 3
```

And my `Dockerfile`:
```
#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

# Update the VARIANT arg in devcontainer.json to pick a Python version: 3, 3.8, 3.7, 3.6 
# To fully customize the contents of this image, use the following Dockerfile instead:
# https://github.com/microsoft/vscode-dev-containers/tree/v0.117.0/containers/python-3/.devcontainer/base.Dockerfile
ARG VARIANT="3"
FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT}

# [Optional] If your requirements rarely change, uncomment this section to add them to the image.
#
COPY requirements.txt /tmp/pip-tmp/
RUN pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
   && rm -rf /tmp/pip-tmp
```

And when I try to build this dev container I get:
```
[1 ms] Start: Resolving remote
[2 ms] Setting up container for folder or workspace: /Users/aferguson/dev/con_test

[34 ms] Start: Check Docker is running
[34 ms] Start: Run: docker info
[537 ms] Start: Run: docker-compose version --short
[991 ms] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=con_test --filter label=com.docker.compose.service=app
[1051 ms] Start: Run: docker inspect --type container a99117b0322e
[1110 ms] Start: Removing existing container.
[1110 ms] Start: Run: docker rm -f a99117b0322e64843419f4ed70df0825970bf52cd6ce69174f3ac831064dce5b
[1178 ms] Start: Run: docker-compose -f /Users/aferguson/dev/con_test/docker-compose.yml config --services
[1627 ms] Start: Run: docker events --format {{json .}} --filter status=start
[1636 ms] Start: Run: docker-compose --project-name con_test -f /Users/aferguson/dev/con_test/docker-compose.yml up -d --build
Building app
Step 1/4 : ARG VARIANT="3"
Step 2/4 : FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT}
 ---> 7c4535bbb77d
Step 3/4 : COPY requirements.txt /tmp/pip-tmp/
 ---> Using cache
 ---> d5dd143e6fda
Step 4/4 : RUN pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt    && rm -rf /tmp/pip-tmp
 ---> Using cache
 ---> 9371ffbef4cf
Successfully built 9371ffbef4cf
Successfully tagged con_test_app:latest
Creating con_test_app_1 ... done
[6130 ms] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=con_test --filter label=com.docker.compose.service=app
[6211 ms] Start: Run: docker inspect --type container 98c0ac46ffeb
[6338 ms] Start: Inspecting container
[6338 ms] Start: Run: docker inspect --type container 98c0ac46ffeb2f91ecf6f7cab3c2060b9ec9f57e79851844702dfb11d24184a9
[6400 ms] Start: Run: docker exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=70a23013-71eb-44b9-a837-daed8b48c7bc1589313984824 98c0ac46ffeb2f91ecf6f7cab3c2060b9ec9f57e79851844702dfb11d24184a9 /bin/sh
[6409 ms] Start: Run in container: uname -m
[6472 ms] Start: Run in container: cat /etc/passwd
[6472 ms] Stdin closed!
[6474 ms] Shell server terminated (code: 1, signal: null)

Error response from daemon: Container 98c0ac46ffeb2f91ecf6f7cab3c2060b9ec9f57e79851844702dfb11d24184a9 is not running
```

**Comment by chrmarti** [comment]
@Onjrew Try adding `command: /bin/sh -c "while sleep 1000; do :; done"` to your docker-compose.yml. The container needs to stay alive on its own in a Docker Compose setup. (When using a single container we pass the sleep in as the command with `docker run`.)

**Comment by Onjrew** [comment]
@chrmarti  Thank you. This was my issue, the container was exiting before VSCode could finish attaching.

**Comment by PavelSosin-320** [comment]
@chrmarti What caused exit? Is it OK?
I would like to look at **docker events --filter container=xxxxx** output
