### ISSUE TITLE
Keeps reconnect and reload when Remote SSH with VPN

### ISSUE THREAD

**Issue by allenloong** [microsoft/vscode-remote-release#2565]
Version: 1.43.0
OS: Linux x64 4.15.0-88-generic
remote OS: Linux
Extension : Remote SSH 0.50.0

I try to connect the Compute Cluster with remote ssh through a VPN. However, after connected to the remote host, about half a minute, the vscode prompts that " attempting reconnect balbala". After reconnected, got "Failed to fetch remote environment balba". Thx.

Log:
```
[17:51:00.029] Log Level: 2
[17:51:00.031] remote-ssh@0.50.0
[17:51:00.031] linux x64
[17:51:00.032] SSH Resolver called for "ssh-remote+th", attempt 1
[17:51:00.033] SSH Resolver called for host: th
[17:51:00.033] Setting up SSH remote "th"
[17:51:00.035] Acquiring local install lock: /tmp/vscode-remote-ssh-th-install.lock
[17:51:00.040] Looking for existing server data file at /home/user/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-th-78a4c91400152c0f27ba4d363eb56d2835f9903a/data.json
[17:51:00.041] Using commit id "78a4c91400152c0f27ba4d363eb56d2835f9903a" and quality "stable" for server
[17:51:00.043] Install and start server if needed
[17:51:00.045] Checking ssh with "ssh -V"
[17:51:00.051] > OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
[17:51:00.053] askpass server listening on /run/user/1000/vscode-ssh-askpass-6c34cfc3c556bb4ea903975edc43542d21941c00.sock
[17:51:00.053] Spawning local server with {"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-0d1dc0eade5d4145b0fb8c2193c219427534141e.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","35741","-o","ConnectTimeout=15","th"],"dataFilePath":"/home/user/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-th-78a4c91400152c0f27ba4d363eb56d2835f9903a/data.json"}
[17:51:00.053] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.50.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.50.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-6c34cfc3c556bb4ea903975edc43542d21941c00.sock"}
[17:51:00.058] Spawned 18728
[17:51:00.115] > local-server> Spawned ssh: 18736
[17:51:00.116] stderr> OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
[17:51:00.282] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:vHYltynIXHzJKUSxEJeWUYYnRcIxaqRnHEu/5gr/Rho
[17:51:00.283] stderr> Warning: Permanently added '[172.16.22.11]:5566' (ECDSA) to the list of known hosts.
[17:51:00.440] stderr> No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_1000)
[17:51:00.440] stderr> 
[17:51:00.483] stderr> No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_1000)
[17:51:00.483] stderr> 
[17:51:00.662] stderr> Authenticated to 172.16.22.11 ([172.16.22.11]:5566).

[17:51:01.514] > ready: 6058815c021a
[17:51:01.552] > Linux 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016
[17:51:01.553] Platform: linux
[17:51:01.626] > 6058815c021a: running
[17:51:01.677] > Acquiring lock on /BLOCK1/user_user/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/vscode-remote-lock.user_user.78a4c91400152c0f27ba4d363eb56d2835f9903a
[17:51:01.680] > \ln /BLOCK1/user_user/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/vscode-remote-lock.user_user.78a4c91400152c0f27ba4d363eb56d2835f9903a.target /BLOCK1/user_user/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/vscode-remote-lock.user_user.78a4c91400152c0f27ba4d363eb56d2835f9903a
[17:51:01.689] > Found existing installation at /BLOCK1/user_user/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a...


> Starting server with command... /BLOCK1/user_user/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/BLOCK1/user_user/.vscode-server/.78a4c91400152c0f27ba4d363eb56d2835f9903a.log" < /dev/null
[17:51:01.774] > Waiting for server log...
[17:51:02.249] > Waiting for server log...
[17:51:02.754] > Waiting for server log...
[17:51:03.259] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
[17:51:03.270] > 6058815c021a: start
[17:51:03.271] > sshAuthSock====
> agentPort==43366==
> osReleaseId==rhel==
> arch==x86_64==
> webUiAccessToken====
> tmpDir==/run/user/5007==
> platform==linux==
> 6058815c021a: end
[17:51:03.272] Received install output: sshAuthSock====
agentPort==43366==
osReleaseId==rhel==
arch==x86_64==
webUiAccessToken====
tmpDir==/run/user/5007==
platform==linux==

[17:51:03.274] Remote server is listening on port 43366
[17:51:03.274] Parsed server configuration: {"agentPort":43366,"osReleaseId":"rhel","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/5007","platform":"linux"}
[17:51:03.276] Persisting server connection details to /home/user/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-th-78a4c91400152c0f27ba4d363eb56d2835f9903a/data.json
[17:51:03.280] Starting forwarding server. localPort 33499 -> socksPort 35741 -> remotePort 43366
[17:51:03.281] Forwarding server listening on 33499
[17:51:03.281] Waiting for ssh tunnel to be ready
[17:51:03.284] [Forwarding server 33499] Got connection 0
[17:51:03.287] Tunneled remote port 43366 to local port 33499
[17:51:03.288] Resolved "ssh-remote+th" to "127.0.0.1:33499"
[17:51:03.305] ------




[17:51:03.332] [Forwarding server 33499] Got connection 1
[17:51:03.332] [Forwarding server 33499] Got connection 2
[17:51:44.920] ------




[17:51:44.920] SSH Resolver called for "ssh-remote+th", attempt 2, (Reconnection)
[17:51:44.921] SSH Resolver called for host: th
[17:51:44.922] Setting up SSH remote "th"
[17:51:44.926] Acquiring local install lock: /tmp/vscode-remote-ssh-th-install.lock
[17:51:44.928] Looking for existing server data file at /home/user/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-th-78a4c91400152c0f27ba4d363eb56d2835f9903a/data.json
[17:51:44.930] Found local server running: {"agentPort":43366,"osReleaseId":"rhel","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/5007","platform":"linux","pid":18728,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-0d1dc0eade5d4145b0fb8c2193c219427534141e.sock","socksPort":35741,"startupTime":1584438660058}
[17:51:44.930] Running server is stale. Ignoring
[17:51:44.931] Using commit id "78a4c91400152c0f27ba4d363eb56d2835f9903a" and quality "stable" for server
[17:51:44.935] Install and start server if needed
[17:51:44.942] askpass server listening on /run/user/1000/vscode-ssh-askpass-95037eea678205b1934912ec72b3483e1a4a15e0.sock
[17:51:44.943] Spawning local server with {"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-f1ad01c767c65526ea08f583feaefaf6e9df0522.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","46277","-o","ConnectTimeout=15","th"],"dataFilePath":"/home/user/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-th-78a4c91400152c0f27ba4d363eb56d2835f9903a/data.json"}
[17:51:44.944] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.50.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.50.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-95037eea678205b1934912ec72b3483e1a4a15e0.sock"}
[17:51:44.955] Spawned 18836
[17:51:45.052] > local-server> Spawned ssh: 18844
[17:51:45.053] stderr> OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
[17:51:45.222] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:RliDnTfhjwVpeqBZuN+RZiC9ul5OTCp9iKLYdO+DcZ8
[17:51:45.222] stderr> Warning: Permanently added '[172.16.22.11]:5566' (ECDSA) to the list of known hosts.
[17:51:45.383] stderr> No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_1000)
[17:51:45.384] stderr> 
[17:51:45.386] stderr> No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_1000)
[17:51:45.386] stderr> 
[17:51:45.702] stderr> Authenticated to 172.16.22.11 ([172.16.22.11]:5566).

[17:51:46.629] > ready: 032339edcda2
[17:51:46.667] > Linux 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016
[17:51:46.668] Platform: linux
[17:51:46.740] > 032339edcda2: running
[17:51:46.789] > Acquiring lock on /BLOCK1/user_user/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/vscode-remote-lock.user_user.78a4c91400152c0f27ba4d363eb56d2835f9903a
[17:51:46.794] > \ln /BLOCK1/user_user/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/vscode-remote-lock.user_user.78a4c91400152c0f27ba4d363eb56d2835f9903a.target /BLOCK1/user_user/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/vscode-remote-lock.user_user.78a4c91400152c0f27ba4d363eb56d2835f9903a
[17:51:46.801] > Found existing installation at /BLOCK1/user_user/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a...

> Starting server with command... /BLOCK1/user_user/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/BLOCK1/user_user/.vscode-server/.78a4c91400152c0f27ba4d363eb56d2835f9903a.log" < /dev/null
[17:51:46.940] > Waiting for server log...
[17:51:47.448] > Waiting for server log...
[17:51:47.955] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[17:51:47.968] > 032339edcda2: start
[17:51:47.968] > sshAuthSock====
> agentPort==33700==
> osReleaseId==rhel==
> arch==x86_64==
> webUiAccessToken====
[17:51:47.968] > tmpDir==/tmp==
> platform==linux==
> 032339edcda2: end
[17:51:47.969] Received install output: sshAuthSock====
agentPort==33700==
osReleaseId==rhel==
arch==x86_64==
webUiAccessToken====tmpDir==/tmp==
platform==linux==

[17:51:47.969] Remote server is listening on port 33700
[17:51:47.969] Parsed server configuration: {"agentPort":33700,"osReleaseId":"rhel","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/tmp","platform":"linux"}
[17:51:47.970] Persisting server connection details to /home/user/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-th-78a4c91400152c0f27ba4d363eb56d2835f9903a/data.json
[17:51:47.970] Starting forwarding server. localPort 36317 -> socksPort 46277 -> remotePort 33700
[17:51:47.971] Forwarding server listening on 36317
[17:51:47.971] Waiting for ssh tunnel to be ready
[17:51:47.971] [Forwarding server 36317] Got connection 0
[17:51:47.972] Tunneled remote port 33700 to local port 36317
[17:51:47.972] Resolved "ssh-remote+th" to "127.0.0.1:36317"
[17:51:47.975] ------




[17:51:47.983] [Forwarding server 36317] Got connection 1
[17:51:47.983] [Forwarding server 36317] Got connection 2
[17:51:48.010] Failed to set up socket for dynamic port forward to remote port 33700: Socket closed. Is the remote port correct?
[17:51:48.020] Failed to set up socket for dynamic port forward to remote port 33700: Socket closed. Is the remote port correct?
[17:51:48.021] Failed to set up socket for dynamic port forward to remote port 33700: Socket closed. Is the remote port correct?
[17:51:49.788] > local-server> Timed out
[17:51:49.794] Local server exit: 0
[17:52:23.011] ------




[17:52:23.011] SSH Resolver called for "ssh-remote+th", attempt 3, (Reconnection)
[17:52:23.011] SSH Resolver called for host: th
[17:52:23.012] Setting up SSH remote "th"
[17:52:23.013] Acquiring local install lock: /tmp/vscode-remote-ssh-th-install.lock
[17:52:23.014] Looking for existing server data file at /home/user/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-th-78a4c91400152c0f27ba4d363eb56d2835f9903a/data.json
[17:52:23.015] Found local server running: {"agentPort":33700,"osReleaseId":"rhel","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/tmp","platform":"linux","pid":18836,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-f1ad01c767c65526ea08f583feaefaf6e9df0522.sock","socksPort":46277,"startupTime":1584438704957}
[17:52:23.015] Running server is stale. Ignoring
[17:52:23.015] Using commit id "78a4c91400152c0f27ba4d363eb56d2835f9903a" and quality "stable" for server
[17:52:23.017] Install and start server if needed
[17:52:23.020] askpass server listening on /run/user/1000/vscode-ssh-askpass-ae4d4c306f42df1aec34817dd481eab1cf79d545.sock
[17:52:23.021] Spawning local server with {"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-8b847ba261651db9faa233412b23100b42dcf1c6.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","42623","-o","ConnectTimeout=15","th"],"dataFilePath":"/home/user/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-th-78a4c91400152c0f27ba4d363eb56d2835f9903a/data.json"}
[17:52:23.021] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.50.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.50.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-ae4d4c306f42df1aec34817dd481eab1cf79d545.sock"}
[17:52:23.026] Spawned 18878
[17:52:23.088] > local-server> Spawned ssh: 18886
[17:52:23.089] stderr> OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
[17:52:23.254] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:RliDnTfhjwVpeqBZuN+RZiC9ul5OTCp9iKLYdO+DcZ8
[17:52:23.255] stderr> Warning: Permanently added '[172.16.22.11]:5566' (ECDSA) to the list of known hosts.
[17:52:23.416] stderr> No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_1000)
[17:52:23.417] stderr> 
[17:52:23.421] stderr> No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_1000)
[17:52:23.421] stderr> 
[17:52:23.592] stderr> Authenticated to 172.16.22.11 ([172.16.22.11]:5566).

[17:52:24.458] > ready: 9aefcfe38519
[17:52:24.497] > Linux 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016
[17:52:24.498] Platform: linux
[17:52:24.571] > 9aefcfe38519: running
[17:52:24.623] > Acquiring lock on /BLOCK1/user_user/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/vscode-remote-lock.user_user.78a4c91400152c0f27ba4d363eb56d2835f9903a
[17:52:24.634] > \ln /BLOCK1/user_user/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/vscode-remote-lock.user_user.78a4c91400152c0f27ba4d363eb56d2835f9903a.target /BLOCK1/user_user/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/vscode-remote-lock.user_user.78a4c91400152c0f27ba4d363eb56d2835f9903a
[17:52:24.642] > Found existing installation at /BLOCK1/user_user/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a...

> Starting server with command... /BLOCK1/user_user/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/BLOCK1/user_user/.vscode-server/.78a4c91400152c0f27ba4d363eb56d2835f9903a.log" < /dev/null
[17:52:24.764] > Waiting for server log...
[17:52:25.242] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[17:52:25.255] > 9aefcfe38519: start
> sshAuthSock====
> agentPort==41100==
> osReleaseId==rhel==
> arch==x86_64==
> webUiAccessToken====
[17:52:25.257] > tmpDir==/tmp==
> platform==linux==
> 9aefcfe38519: end
[17:52:25.257] Received install output: 
sshAuthSock====
agentPort==41100==
osReleaseId==rhel==
arch==x86_64==
webUiAccessToken====tmpDir==/tmp==
platform==linux==

[17:52:25.258] Remote server is listening on port 41100
[17:52:25.258] Parsed server configuration: {"agentPort":41100,"osReleaseId":"rhel","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/tmp","platform":"linux"}
[17:52:25.260] Persisting server connection details to /home/user/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-th-78a4c91400152c0f27ba4d363eb56d2835f9903a/data.json
[17:52:25.263] Starting forwarding server. localPort 33393 -> socksPort 42623 -> remotePort 41100
[17:52:25.264] Forwarding server listening on 33393
[17:52:25.264] Waiting for ssh tunnel to be ready
[17:52:25.266] [Forwarding server 33393] Got connection 0
[17:52:25.267] Tunneled remote port 41100 to local port 33393
[17:52:25.268] Resolved "ssh-remote+th" to "127.0.0.1:33393"
[17:52:25.274] ------




[17:52:25.286] [Forwarding server 33393] Got connection 1
[17:52:25.286] [Forwarding server 33393] Got connection 2
[17:52:25.306] Failed to set up socket for dynamic port forward to remote port 41100: Socket closed. Is the remote port correct?
[17:52:25.325] Failed to set up socket for dynamic port forward to remote port 41100: Socket closed. Is the remote port correct?
[17:52:25.326] Failed to set up socket for dynamic port forward to remote port 41100: Socket closed. Is the remote port correct?
[17:52:26.476] > local-server> Timed out
[17:52:26.481] Local server exit: 0
[17:52:57.705] ------




[17:52:57.706] SSH Resolver called for "ssh-remote+th", attempt 4, (Reconnection)
[17:52:57.707] SSH Resolver called for host: th
[17:52:57.708] Setting up SSH remote "th"
[17:52:57.711] Acquiring local install lock: /tmp/vscode-remote-ssh-th-install.lock
[17:52:57.712] Looking for existing server data file at /home/user/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-th-78a4c91400152c0f27ba4d363eb56d2835f9903a/data.json
[17:52:57.714] Found local server running: {"agentPort":41100,"osReleaseId":"rhel","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/tmp","platform":"linux","pid":18878,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-8b847ba261651db9faa233412b23100b42dcf1c6.sock","socksPort":42623,"startupTime":1584438743026}
[17:52:57.714] Running server is stale. Ignoring
[17:52:57.714] Using commit id "78a4c91400152c0f27ba4d363eb56d2835f9903a" and quality "stable" for server
[17:52:57.717] Install and start server if needed
[17:52:57.721] askpass server listening on /run/user/1000/vscode-ssh-askpass-f1e0ffc9fc3eb551fd443a7034f19c37734aa12c.sock
[17:52:57.722] Spawning local server with {"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-f64ae5dcb07c1038fadcf1ca680f637e253c5f76.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","46047","-o","ConnectTimeout=15","th"],"dataFilePath":"/home/user/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-th-78a4c91400152c0f27ba4d363eb56d2835f9903a/data.json"}
[17:52:57.722] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.50.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.50.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-f1e0ffc9fc3eb551fd443a7034f19c37734aa12c.sock"}
[17:52:57.729] Spawned 18900
[17:52:57.800] > local-server> Spawned ssh: 18908
[17:52:57.801] stderr> OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
[17:52:57.963] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:pcSgneIA4GyuP6Y6K4VYsg/SaPWy0UwHpPaC+QYgkvw
[17:52:57.964] stderr> Warning: Permanently added '[172.16.22.11]:5566' (ECDSA) to the list of known hosts.
[17:52:58.118] stderr> No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_1000)
[17:52:58.118] stderr> 
[17:52:58.121] stderr> No Kerberos credentials available (default cache: FILE:/tmp/krb5cc_1000)
[17:52:58.122] stderr> 
[17:52:58.438] stderr> Authenticated to 172.16.22.11 ([172.16.22.11]:5566).

[17:52:59.523] > ready: 9c74f34653b2
[17:52:59.561] > Linux 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016
[17:52:59.561] Platform: linux
[17:52:59.637] > 9c74f34653b2: running
[17:52:59.689] > Acquiring lock on /BLOCK1/user_user/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/vscode-remote-lock.user_user.78a4c91400152c0f27ba4d363eb56d2835f9903a
[17:52:59.694] > \ln /BLOCK1/user_user/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/vscode-remote-lock.user_user.78a4c91400152c0f27ba4d363eb56d2835f9903a.target /BLOCK1/user_user/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/vscode-remote-lock.user_user.78a4c91400152c0f27ba4d363eb56d2835f9903a
[17:52:59.704] > Found existing installation at /BLOCK1/user_user/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a...

> Starting server with command... /BLOCK1/user_user/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/BLOCK1/user_user/.vscode-server/.78a4c91400152c0f27ba4d363eb56d2835f9903a.log" < /dev/null
[17:52:59.793] > Waiting for server log...
[17:53:00.267] > Waiting for server log...
[17:53:00.771] > Waiting for server log...
[17:53:01.276] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
[17:53:01.286] > 9c74f34653b2: start
> sshAuthSock====
> agentPort==35959==
> osReleaseId==rhel==
[17:53:01.287] > arch==x86_64==
> webUiAccessToken====
> tmpDir==/run/user/5007==
> platform==linux==
> 9c74f34653b2: end
[17:53:01.288] Received install output: 
sshAuthSock====
agentPort==35959==
osReleaseId==rhel==arch==x86_64==
webUiAccessToken====
tmpDir==/run/user/5007==
platform==linux==

[17:53:01.289] Remote server is listening on port 35959
[17:53:01.289] Parsed server configuration: {"agentPort":35959,"osReleaseId":"rhel","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/5007","platform":"linux"}
[17:53:01.292] Persisting server connection details to /home/user/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-th-78a4c91400152c0f27ba4d363eb56d2835f9903a/data.json
[17:53:01.294] Starting forwarding server. localPort 44109 -> socksPort 46047 -> remotePort 35959
[17:53:01.295] Forwarding server listening on 44109
[17:53:01.296] Waiting for ssh tunnel to be ready
[17:53:01.297] [Forwarding server 44109] Got connection 0
[17:53:01.298] Tunneled remote port 35959 to local port 44109
[17:53:01.298] Resolved "ssh-remote+th" to "127.0.0.1:44109"
[17:53:01.304] ------
[17:53:01.321] [Forwarding server 44109] Got connection 1

```

**Comment by roblourens** [comment]
It looks like maybe the remote server keeps crashing? Can you check `/BLOCK1/user_user/.vscode-server/.78a4c91400152c0f27ba4d363eb56d2835f9903a.log` for any interesting output?

**Comment by allenloong** [comment]
Thanks for your quick response. I checked the log and it looks like the remote node killed the vscode-server.

```
*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


IP Address: 172.16.22.89
IP Address: 25.25.107.26
IP Address: 12.8.71.140
Extension host agent listening on 42403


[19:25:13] Extension host agent started.
[19:25:16] [127.0.0.1][6bd468ea][ManagementConnection] Unknown reconnection token.
[19:25:16] [127.0.0.1][731b1ff6][ExtensionHostConnection] Unknown reconnection token.
/BLOCK1/user.user/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/server.sh: line 12: 17453 Killed                  "$ROOT/node" ${INSPECT:-} "$ROOT/out/vs/server/main.js" "$@"
```

**Comment by roblourens** [comment]
Ok, that tells us that the remote extension host probably crashed. Do you have any remote extensions installed?

**Comment by allenloong** [comment]
emmm...no i didn't install any remote extension.

**Comment by roblourens** [comment]
It looks like your remote meets the minimum requirements, but can you check that it meets the requirements on this page? https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites

**Comment by allenloong** [comment]
I checked these and the remote machine meets the GENERAL BASE REQUIREMENTS.

**Comment by t3fi** [comment]
I've had similar issues before that made me to try insiders version and different setups of exensions, mainly for developing c++ with cmake extensions. It seemed to me first that when these extensions are taking lots of server cpu time, the ssh connection starts to timeout and ask for reconnect/reload-window. In past days it has worked decently for me, but just today it started doing it again and even on simple tasks like CTRL-S (save-current-file).

I believe I updated insiders version, maybe some extensions as well just yesterday. Now it started to jam my vpn-ssh port totally. I.e. I cannot reconnect even via terminal ssh without reconnecting the vpn (It says "Connecting reset by ... port 22) and starts to work after reconnect of vpn. 
VSCode ssh reconnection connection just prints:
```
[13:31:54.564] Failed to parse remote port from server output
[13:31:54.565] Resolver error: 
[13:31:54.567] ------
```

In server log:
```
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/xxx/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/out/bootstrap.js:5:80)
    at process.emit (events.js:200:13)
[13:26:27] [127.0.0.1][c3e24b07][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
```

**Comment by tcherne** [comment]
Fix for me was in the vscode logs you will see:
[timestamp] stderr> ln: failed to create hard link '<some file name>' File exists

Go to the box you are trying to connect to and rm '<some file name>'
Restart your vscode and you should be good.

**Comment by cperera-aud** [comment]
I also had a similar issue with the symbolic link. To get things to work again, I deleted the .vscode-server folder on my home directory on my remote machine. After that all good and the remote extension was able to setup an SSH connection.

**Comment by langweixianzi** [comment]
works for me by deleting the content inside the folder ~/.vscode-server/bin/<something long>/*
then re click the ssh >< button.

**Comment by roblourens** [comment]
Many changes over the summer. Is this still an issue?
