### ISSUE TITLE
Remote CLI fails installing extension

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#2566]
Issue Type: <b>Bug</b>

[11519 ms] Start: Run in container: cd /root/.vscode-server-insiders/bin/b7bfce30be3c30aa2c33fbe94fe82b81d4105668; export VSCODE_AGENT_FOLDER=/root/.vscode-server-insiders; /root/.vscode-server-insiders/bin/b7bfce30be3c30aa2c33fbe94fe82b81d4105668/server.sh --install-extension dbaeumer.vscode-eslint --force
[11711 ms] Installing extensions...
[11711 ms] [createInstance] extensionManagementService depends on storageService which is NOT registered.
(node:66) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
    at Object.t.getServiceMachineId (/root/.vscode-server-insiders/bin/b7bfce30be3c30aa2c33fbe94fe82b81d4105668/out/vs/server/remoteExtensionHostAgent.js:354:192)
    at U (/root/.vscode-server-insiders/bin/b7bfce30be3c30aa2c33fbe94fe82b81d4105668/out/vs/server/remoteExtensionHostAgent.js:383:915)
    at new e (/root/.vscode-server-insiders/bin/b7bfce30be3c30aa2c33fbe94fe82b81d4105668/out/vs/server/remoteExtensionHostAgent.js:375:435)
    at u._createInstance (/root/.vscode-server-insiders/bin/b7bfce30be3c30aa2c33fbe94fe82b81d4105668/out/vs/server/remoteExtensionHostAgent.js:248:201)
    at u._createServiceInstance (/root/.vscode-server-insiders/bin/b7bfce30be3c30aa2c33fbe94fe82b81d4105668/out/vs/server/remoteExtensionHostAgent.js:250:256)
    at u._createServiceInstanceWithOwner (/root/.vscode-server-insiders/bin/b7bfce30be3c30aa2c33fbe94fe82b81d4105668/out/vs/server/remoteExtensionHostAgent.js:249:768)
    at u._createAndCacheServiceInstance (/root/.vscode-server-insiders/bin/b7bfce30be3c30aa2c33fbe94fe82b81d4105668/out/vs/server/remoteExtensionHostAgent.js:249:443)
    at u._getOrCreateServiceInstance (/root/.vscode-server-insiders/bin/b7bfce30be3c30aa2c33fbe94fe82b81d4105668/out/vs/server/remoteExtensionHostAgent.js:248:709)
    at u._createInstance (/root/.vscode-server-insiders/bin/b7bfce30be3c30aa2c33fbe94fe82b81d4105668/out/vs/server/remoteExtensionHostAgent.js:247:702)
    at u.createInstance (/root/.vscode-server-insiders/bin/b7bfce30be3c30aa2c33fbe94fe82b81d4105668/out/vs/server/remoteExtensionHostAgent.js:247:538)
    at Object.t.run (/root/.vscode-server-insiders/bin/b7bfce30be3c30aa2c33fbe94fe82b81d4105668/out/vs/server/remoteExtensionHostAgent.js:475:575)
(node:66) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:66) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Cannot read property 'get' of undefined
(node:66) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
[11711 ms] Exit code 1

Extension version: 0.108.0
VS Code version: Code - Insiders 1.44.0-insider (b7bfce30be3c30aa2c33fbe94fe82b81d4105668, 2020-03-17T07:17:39.113Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.98GB (2.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|Dev Container: Node.js 12 & Mongo DB|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (2 x 2399)|
|Memory (System)|1.94GB (0.65GB free)|
|VM|0%|
</details>

**Comment by sandy081** [comment]
Fixed by 6e90a629f5d9e1f55270c47372155104cf145f8f
