### ISSUE TITLE
Remote SSH: Terminal stops responding and requires a "Reload" to work again

### ISSUE THREAD

**Issue by ob** [microsoft/vscode-remote-release#2643]
- VSCode Version:
```
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

- Local OS Version:
```
% sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E266
```

- Remote OS Version:
```
% uname -a
Linux obonilla-ld2.linkedin.biz 3.10.0-957.12.2.el7.x86_64 #1 SMP Fri Apr 19 21:09:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Remote Extension/Connection Type: SSH
Remote-SSH: 0.51.0

Steps to Reproduce:

1. Open remote connection
2. Work for a while

This happens very often to me and is somewhat reproducible, although I haven’t figured out a way to reliably reproduce it. 

Sometimes after running one of our builds in the Terminal via Remote-SSH, the terminal stops responding. I see the prompt but I can’t enter any commands.

The rest of VS Code appears to be working normally but the Terminal is unresponsive and I can’t even create a new session, If I hit the “+” button next to the shell drop-down, a new session is created but it doesn’t run a shell.

I can open new files, run commands, etc.

<details><summary>The last few lines of the “Remote-SSH” output channel</summary>
<p>
```
[09:44:12.677] [Forwarding server 62050] Got connection 1
[09:44:12.677] [Forwarding server 62050] Got connection 2
[09:44:14.383] [Forwarding server 62050] Got connection 3
[09:44:14.384] [Forwarding server 62050] Got connection 4
[09:44:17.949] "Update SSH_AUTH_SOCK" terminal command done
[09:44:23.042] [Forwarding server 62050] Got connection 5
[09:44:23.042] [Forwarding server 62050] Got connection 6
[09:44:23.043] [Forwarding server 62050] Got connection 7
[10:28:05.198] [Forwarding server 62050] Got connection 8
[10:28:37.881] [Forwarding server 62050] Got connection 9
```
</p>
</details>

<details><summary>The remote log</summary>
<p>

```
[2020-03-28 07:27:34.307] [renderer4] [error] [remote-connection][Management   ][ee570…][reconnect] An error occurred while reconnecting, but it will be treated as a permanent error because the reconnection grace time has expired! Will give up now! Error:
[2020-03-28 07:27:34.307] [renderer4] [error] Error: Could not resolve hostname
    at e.resolveAuthority (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3692:473)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async K._resolveAuthorityAgain (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4042:426)
[2020-03-28 07:27:34.409] [renderer4] [error] [remote-connection][ExtensionHost][2f4d9…][reconnect] An error occurred while reconnecting, but it will be treated as a permanent error because the reconnection grace time has expired! Will give up now! Error:
[2020-03-28 07:27:34.409] [renderer4] [error] Error: Could not resolve hostname
    at e.resolveAuthority (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3692:473)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async K._resolveAuthorityAgain (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4042:426)
[2020-03-30 09:44:28.006] [renderer4] [error] Failed to execute git
[2020-03-30 09:44:30.551] [renderer4] [error] Cannot read property 'command' of undefined: TypeError: Cannot read property 'command' of undefined
    at OpportunisticCodeLensProvider.provideCodeLenses (/home/obonilla/.vscode-server/extensions/ms-vsliveshare.vsliveshare-1.0.1847/out/prod/extension-prod.js:144488:91)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
[2020-03-30 10:21:15.293] [renderer4] [error] Cannot read property 'command' of undefined: TypeError: Cannot read property 'command' of undefined
    at OpportunisticCodeLensProvider.provideCodeLenses (/home/obonilla/.vscode-server/extensions/ms-vsliveshare.vsliveshare-1.0.1847/out/prod/extension-prod.js:144488:91)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
[2020-03-30 10:22:33.370] [renderer4] [error] Cannot read property 'command' of undefined: TypeError: Cannot read property 'command' of undefined
    at OpportunisticCodeLensProvider.provideCodeLenses (/home/obonilla/.vscode-server/extensions/ms-vsliveshare.vsliveshare-1.0.1847/out/prod/extension-prod.js:144488:91)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
[2020-03-30 10:22:46.400] [renderer4] [error] Cannot read property 'command' of undefined: TypeError: Cannot read property 'command' of undefined
    at OpportunisticCodeLensProvider.provideCodeLenses (/home/obonilla/.vscode-server/extensions/ms-vsliveshare.vsliveshare-1.0.1847/out/prod/extension-prod.js:144488:91)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
[2020-03-30 10:28:00.192] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-03-30 10:28:00.192] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] waiting for 5 seconds before reconnecting...
[2020-03-30 10:28:05.195] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] resolving connection...
[2020-03-30 10:28:05.195] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] connecting to 127.0.0.1:62050...
[2020-03-30 10:28:12.873] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] reconnected!
[2020-03-30 10:28:13.304] [renderer4] [error] write EPIPE: Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
[2020-03-30 10:28:32.879] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-03-30 10:28:32.879] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] waiting for 5 seconds before reconnecting...
[2020-03-30 10:28:37.879] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] resolving connection...
[2020-03-30 10:28:37.879] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] connecting to 127.0.0.1:62050...
[2020-03-30 10:28:42.060] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] reconnected!
[2020-03-30 10:28:42.278] [renderer4] [error] write EPIPE: Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
[2020-03-30 10:29:02.070] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-03-30 10:29:02.071] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] waiting for 5 seconds before reconnecting...
[2020-03-30 10:29:07.071] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] resolving connection...
[2020-03-30 10:29:07.071] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] connecting to 127.0.0.1:62050...
[2020-03-30 10:29:11.761] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] reconnected!
[2020-03-30 10:29:12.002] [renderer4] [error] write EPIPE: Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
[2020-03-30 10:29:31.772] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-03-30 10:29:31.772] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] waiting for 5 seconds before reconnecting...
[2020-03-30 10:29:36.772] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] resolving connection...
[2020-03-30 10:29:36.773] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] connecting to 127.0.0.1:62050...
[2020-03-30 10:29:41.834] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] reconnected!
[2020-03-30 10:29:42.065] [renderer4] [error] write EPIPE: Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
[2020-03-30 10:30:01.840] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-03-30 10:30:01.840] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] waiting for 5 seconds before reconnecting...
[2020-03-30 10:30:06.841] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] resolving connection...
[2020-03-30 10:30:06.842] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] connecting to 127.0.0.1:62050...
[2020-03-30 10:30:09.771] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] reconnected!
[2020-03-30 10:30:29.780] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-03-30 10:30:29.780] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] waiting for 5 seconds before reconnecting...
[2020-03-30 10:30:34.781] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] resolving connection...
[2020-03-30 10:30:34.781] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] connecting to 127.0.0.1:62050...
[2020-03-30 10:30:39.903] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] reconnected!
[2020-03-30 10:30:59.910] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-03-30 10:30:59.911] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] waiting for 5 seconds before reconnecting...
[2020-03-30 10:31:04.910] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] resolving connection...
[2020-03-30 10:31:04.910] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] connecting to 127.0.0.1:62050...
[2020-03-30 10:31:10.416] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] reconnected!
[2020-03-30 10:31:30.423] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-03-30 10:31:30.424] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] waiting for 5 seconds before reconnecting...
[2020-03-30 10:31:35.425] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] resolving connection...
[2020-03-30 10:31:35.425] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] connecting to 127.0.0.1:62050...
[2020-03-30 10:31:41.285] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] reconnected!
[2020-03-30 10:31:41.571] [renderer4] [error] write EPIPE: Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
[2020-03-30 10:32:01.295] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-03-30 10:32:01.295] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] waiting for 5 seconds before reconnecting...
[2020-03-30 10:32:06.296] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] resolving connection...
[2020-03-30 10:32:06.296] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] connecting to 127.0.0.1:62050...
[2020-03-30 10:32:11.975] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] reconnected!
[2020-03-30 10:32:31.984] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-03-30 10:32:31.984] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] waiting for 5 seconds before reconnecting...
[2020-03-30 10:32:36.984] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] resolving connection...
[2020-03-30 10:32:36.984] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] connecting to 127.0.0.1:62050...
[2020-03-30 10:32:43.848] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] reconnected!
[2020-03-30 10:32:44.098] [renderer4] [error] write EPIPE: Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
[2020-03-30 10:33:03.857] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-03-30 10:33:03.857] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] waiting for 5 seconds before reconnecting...
[2020-03-30 10:33:08.861] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] resolving connection...
[2020-03-30 10:33:08.861] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] connecting to 127.0.0.1:62050...
[2020-03-30 10:33:15.975] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] reconnected!
[2020-03-30 10:33:16.777] [renderer4] [error] write EPIPE: Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
[2020-03-30 10:33:35.982] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-03-30 10:33:35.982] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] waiting for 5 seconds before reconnecting...
[2020-03-30 10:33:40.982] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] resolving connection...
[2020-03-30 10:33:40.983] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] connecting to 127.0.0.1:62050...
[2020-03-30 10:33:47.541] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] reconnected!
[2020-03-30 10:34:07.548] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-03-30 10:34:07.549] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] waiting for 5 seconds before reconnecting...
[2020-03-30 10:34:12.552] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] resolving connection...
[2020-03-30 10:34:12.552] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] connecting to 127.0.0.1:62050...
[2020-03-30 10:34:20.582] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] reconnected!
[2020-03-30 10:34:21.004] [renderer4] [error] write EPIPE: Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
[2020-03-30 10:34:40.588] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-03-30 10:34:40.588] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] waiting for 5 seconds before reconnecting...
[2020-03-30 10:34:45.589] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] resolving connection...
[2020-03-30 10:34:45.589] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] connecting to 127.0.0.1:62050...
[2020-03-30 10:34:55.001] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] reconnected!
[2020-03-30 10:34:55.257] [renderer4] [error] write EPIPE: Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
[2020-03-30 10:35:15.007] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-03-30 10:35:15.007] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] waiting for 5 seconds before reconnecting...
[2020-03-30 10:35:20.009] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] resolving connection...
[2020-03-30 10:35:20.009] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] connecting to 127.0.0.1:62050...
[2020-03-30 10:35:26.816] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] reconnected!
[2020-03-30 10:35:27.181] [renderer4] [error] write EPIPE: Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
[2020-03-30 10:35:46.823] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-03-30 10:35:46.824] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] waiting for 5 seconds before reconnecting...
[2020-03-30 10:35:51.825] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] resolving connection...
[2020-03-30 10:35:51.825] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] connecting to 127.0.0.1:62050...
[2020-03-30 10:36:00.127] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] reconnected!
[2020-03-30 10:36:20.132] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-03-30 10:36:20.132] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] waiting for 5 seconds before reconnecting...
[2020-03-30 10:36:25.134] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] resolving connection...
[2020-03-30 10:36:25.134] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] connecting to 127.0.0.1:62050...
[2020-03-30 10:36:35.168] [renderer4] [error] write EPIPE: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:146:25)
    at writeGeneric (internal/stream_base_commons.js:137:3)
    at Socket._writeGeneric (net.js:698:11)
    at Socket._write (net.js:710:8)
    at doWrite (_stream_writable.js:418:12)
    at writeOrBuffer (_stream_writable.js:402:5)
    at Socket.Writable.write (_stream_writable.js:302:11)
    at Socket.ondata (_stream_readable.js:720:22)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
[2020-03-30 10:36:36.168] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] reconnected!
[2020-03-30 10:36:36.873] [renderer4] [error] write EPIPE: Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
[2020-03-30 10:36:56.176] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-03-30 10:36:56.176] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] waiting for 5 seconds before reconnecting...
[2020-03-30 10:37:01.178] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] resolving connection...
[2020-03-30 10:37:01.178] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] connecting to 127.0.0.1:62050...
[2020-03-30 10:37:13.174] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] reconnected!
[2020-03-30 10:37:14.030] [renderer4] [error] write EPIPE: Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
[2020-03-30 10:37:33.181] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-03-30 10:37:33.181] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] waiting for 5 seconds before reconnecting...
[2020-03-30 10:37:38.182] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] resolving connection...
[2020-03-30 10:37:38.182] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] connecting to 127.0.0.1:62050...
[2020-03-30 10:37:48.948] [renderer4] [info] [remote-connection][ExtensionHost][9e03f…][reconnect] reconnected!
```
</p>
</details>

And if I run “Reload Window” everything goes back to normal.

**Comment by roblourens** [comment]
Can you check if there is some process using high CPU/memory when this happens? Does the build create a lot of files that might make our file watcher busy?

This is probably related to https://github.com/microsoft/vscode-remote-release/issues/2349 although it's strange that you can continue to open files in this state.

**Comment by ob** [comment]
Do you mean in the local side or the remote side? The remote side is building so I would expect CPU load there. The build creates lots of files but they are in a directory that is excluded in `settings.json`

**Comment by roblourens** [comment]
Are they excluded by the `files.watcherExclude` setting? You could see whether that makes a difference.

**Comment by ob** [comment]
No, they are excluded in `files.exclude`. Should I also add them to `files.watcherExclude`?

**Comment by roblourens** [comment]
It's worth trying, in case the issue is due to the file watcher process going wild
