### ISSUE TITLE
Ctrl P does not find any files other than those "recently opened" in a multi-root workspace in WSL

### ISSUE THREAD

**Issue by AaronFriel** [microsoft/vscode-remote-release#2799]
- VSCode Version: 1.44.2
- OS Version: Windows 10 19608

Steps to Reproduce:

1. Open up a multi-root workspace in WSL
2. Ctrl-P to search for a file, e.g.: package.json

I know there are multiple package.json files in this workspace, but I cannot find them, or any other file, unless it was recently opened.

This occurs on the latest Insider build as well. The ctrl-p search doesn't find anything unless it is in the currently open or recently open lists that are maintained by the editor. It appears searching for unopened files by name is non-functional.

![image](https://user-images.githubusercontent.com/788800/79612445-8ceb0280-80b1-11ea-9ad7-4644430f96e3.png)

Does this issue occur when all extensions are disabled?: n/a (cannot test without WSL extension)

**Comment by bpasero** [comment]
Given it works for recently opened, I think this is rather a search issue.

**Comment by AaronFriel** [comment]
In that state I was able to ctrl-shift-f and find in files successfully, I note that because I saw some issues about search not working with remote workspaces, so it wasn't #709.

I think this is a duplicate of #2770 which I missed in my search.

**Comment by AaronFriel** [comment]
Creator of #2770 disagrees, and upon re-reading it seems there may be a different cause.

I cannot reproduce anymore, but maybe this is a useful bug report anyhow?

**Comment by roblourens** [comment]
I'll follow up in that issue, thanks

**Comment by AaronFriel** [comment]
@roblourens It looks like I'm still experiencing this issue intermittently on VS Code and VS Code Insiders (as of today, April 27th), e.g.:

![image](https://user-images.githubusercontent.com/788800/80434262-3c905380-88ae-11ea-944a-f87be5fab945.png)

There are dozens if not hundreds of "index.ts" files in this workspace and Ctrl+P is only finding the recently opened one. Likewise, any other search term only shows recently opened results. I don't know why this glitch stopped and then returned on VS Code or VS Code Insiders.

**Comment by roblourens** [comment]
Please do the following

- Run the command "Set log level" and change it to "Trace"
- Run the search again
- Show the search-related messages in the "Log (Window)" output panel

![image](https://user-images.githubusercontent.com/323878/35987940-02aae15a-0cb2-11e8-83f1-d95c5dc3881b.png)

**Comment by AaronFriel** [comment]
Going to need to redact some of this, if you don't mind


[2020-04-28 09:20:02.674] [renderer1] [trace] SearchService#search {"_reason":"openFileHandler","folderQueries":[{"folder":{"$mid":1,"external":"vscode-remote://wsl%2Bdebian/home/friel/code/[redacted]","path":"/home/friel/code/[redacted]","scheme":"vscode-remote","authority":"wsl+debian"},"folderName":"[redacted]","excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/vendor":true,"**/venv":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false},{"folder":{"$mid":1,"external":"vscode-remote://wsl%2Bdebian/home/friel/code/[redacted]","path":"/home/friel/code/[redacted]","scheme":"vscode-remote","authority":"wsl+debian"},"folderName":"[redacted]","excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/vendor":true,"**/venv":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false},{"folder":{"$mid":1,"external":"vscode-remote://wsl%2Bdebian/home/friel/code/[redacted]","path":"/home/friel/code/[redacted]","scheme":"vscode-remote","authority":"wsl+debian"},"folderName":"[redacted]","excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/vendor":true,"**/venv":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false},{"folder":{"$mid":1,"external":"vscode-remote://wsl%2Bdebian/home/friel/code/[redacted]","path":"/home/friel/code/[redacted]","scheme":"vscode-remote","authority":"wsl+debian"},"folderName":"[redacted]","excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/vendor":true,"**/venv":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false},{"folder":{"$mid":1,"external":"vscode-remote://wsl%2Bdebian/home/friel/code/[redacted]","path":"/home/friel/code/[redacted]","scheme":"vscode-remote","authority":"wsl+debian"},"folderName":"[redacted]","excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/vendor":true,"**/venv":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false},{"folder":{"$mid":1,"external":"vscode-remote://wsl%2Bdebian/home/friel/code/[redacted]","path":"/home/friel/code/[redacted]","scheme":"vscode-remote","authority":"wsl+debian"},"folderName":"[redacted]","excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/vendor":true,"**/venv":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false},{"folder":{"$mid":1,"external":"vscode-remote://wsl%2Bdebian/home/friel/code/[redacted]","path":"/home/friel/code/[redacted]","scheme":"vscode-remote","authority":"wsl+debian"},"folderName":"[redacted]","excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/vendor":true,"**/venv":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false},{"folder":{"$mid":1,"external":"vscode-remote://wsl%2Bdebian/home/friel/code/[redacted]","path":"/home/friel/code/[redacted]","scheme":"vscode-remote","authority":"wsl+debian"},"folderName":"[redacted]","excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/vendor":true,"**/venv":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false},{"folder":{"$mid":1,"external":"vscode-remote://wsl%2Bdebian/home/friel/code/[redacted]","path":"/home/friel/code/[redacted]","scheme":"vscode-remote","authority":"wsl+debian"},"folderName":"[redacted]","excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/vendor":true,"**/venv":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false},{"folder":{"$mid":1,"external":"vscode-remote://wsl%2Bdebian/home/friel/code/[redacted]","path":"/home/friel/code/[redacted]","scheme":"vscode-remote","authority":"wsl+debian"},"folderName":"[redacted]","excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/vendor":true,"**/venv":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false},{"folder":{"$mid":1,"external":"vscode-remote://wsl%2Bdebian/home/friel/code/[redacted]","path":"/home/friel/code/[redacted]","scheme":"vscode-remote","authority":"wsl+debian"},"folderName":"[redacted]","excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/vendor":true,"**/venv":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false},{"folder":{"$mid":1,"external":"vscode-remote://wsl%2Bdebian/home/friel/code/[redacted]","path":"/home/friel/code/[redacted]","scheme":"vscode-remote","authority":"wsl+debian"},"folderName":"[redacted]","excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/vendor":true,"**/venv":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false},{"folder":{"$mid":1,"external":"vscode-remote://wsl%2Bdebian/home/friel/code/[redacted]","path":"/home/friel/code/[redacted]","scheme":"vscode-remote","authority":"wsl+debian"},"folderName":"[redacted]","excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/vendor":true,"**/venv":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false},{"folder":{"$mid":1,"external":"vscode-remote://wsl%2Bdebian/home/friel/code/[redacted]","path":"/home/friel/code/[redacted]","scheme":"vscode-remote","authority":"wsl+debian"},"folderName":"[redacted]","excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/vendor":true,"**/venv":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false}],"usingSearchPaths":false,"maxResults":512,"type":1,"filePattern":"webhook.ts","sortByScore":true,"cacheKey":"id#8"}
[2020-04-28 09:20:02.903] [renderer1] [trace] SearchService#search: 229ms
[2020-04-28 09:20:02.904] [renderer1] [error] spawn /home/friel/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/node_modules/vscode-ripgrep/bin/rg ENOENT: Error: spawn /home/friel/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/node_modules/vscode-ripgrep/bin/rg ENOENT
    at Object.t.deserializeSearchError (file:///C:/Users/Aaron Friel/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4334:786)
    at file:///C:/Users/Aaron Friel/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4377:134
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async e.getFileSearchResults (file:///C:/Users/Aaron Friel/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5635:875)
    at async Promise.all (index 0)
    at async e.doFileSearch (file:///C:/Users/Aaron Friel/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5635:528)

The folder options are:

```json
            "excludePattern": {
                "**/.git": true,
                "**/.svn": true,
                "**/.hg": true,
                "**/CVS": true,
                "**/.DS_Store": true,
                "**/node_modules": true,
                "**/bower_components": true,
                "**/*.code-search": true,
                "**/vendor": true,
                "**/venv": true
            },
            "fileEncoding": "utf8",
            "disregardIgnoreFiles": false,
            "disregardGlobalIgnoreFiles": true,
            "ignoreSymlinks": false
```

**Comment by AaronFriel** [comment]
I'll add that "rg" works just fine, I use ripgrep as my default grep tool and in my WSL instance I can "rg foo" or to find matching file names I can do `rg --files | rg webhook.ts` and find the four matching files in my workspace.

**Comment by roblourens** [comment]
Does this exist at this path, and does it have executable permissions? `/home/friel/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/node_modules/vscode-ripgrep/bin/rg`

**Comment by AaronFriel** [comment]
@roblourens yes it does, 

```
$ /home/friel/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/node_modules/vscode-ripgrep/bin/rg --help | wc -l
1013
```

Could this have to do with the multi-root workspace I'm using?

**Comment by roblourens** [comment]
Oh, does one of the folders in your workspace not exist?

**Comment by AaronFriel** [comment]
👏 👏 👏 

I had a temporary scratch dir that exists on some branches and not others (workspace config isn't checked in). I removed that workspace directory and ctrl-P works. That explains the ENOENT as well.

Then perhaps the bug report should be:

"VSCode quick search does not filter out missing directories"?

**Comment by roblourens** [comment]
Ok, known issue then, https://github.com/microsoft/vscode/issues/94170 sorry for the trouble
