### ISSUE TITLE
Rename a mounted file/folder (and the respective mounts parameter in devcontainer.json) and vscode won't open or build the container any longer

### ISSUE THREAD

**Issue by tmaslach** [microsoft/vscode-remote-release#2815]
I have a devcontainer.json refrencing a dockerfile.  The devcontainer specifies a file in the /tmp folder I want to mount into the container.  If I rename this file, I get into a state where the I can't open up my project in vscode any longer, nor can I rebuild the container either.

I would imagine if I changed a mount in the mounts, it would ideally ask me if I want to rebuild the container.  
At a minimum, I'm good with manually doing a "Rebuild Container", but that doesn't work either. 

If this doesn't make much sense, I apologize.  See steps to reproduce, I'll do my best to explain there.

- VSCode Version: 1.44.2
- Local OS Version: Ubuntu 
- Remote OS Version: Ubuntu
- Remote Extension/Connection Type:  Docker

Steps to Reproduce:

1. Clone https://github.com/microsoft/vscode-remote-try-python
2. Inside the vscode-remote-try-python/.devcontainer/devcontainer.json, add the following entry:
```
"mounts": ["source=/tmp/f1.txt,target=/tmp/f1.txt,type=bind"]
```
3. Make sure you have a file that exists named /tmp/f1.txt.
4. Run vscode on this folder.  Make sure to "Open Folder in Container". Everything should start up and work fine.  
5. Close VSCode
6. Rename /tmp/f1.txt to /tmp/f2.txt.  Both the actual file and the 2 references in devcontainer.json.
7. Run vscode on the folder again. Make sure to "Open Folder in Container"
8. VS Code will pop up, but fail.    This is what I see
```[26 ms] Start: Check Docker is running
[27 ms] Start: Run: docker info
[129 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/thomas/vscode-remote-try-python --filter label=vsch.quality=stable
[184 ms] Start: Run: docker inspect --type container f65921e65cd9
[242 ms] Start: Starting container
[242 ms] Start: Run: docker start f65921e65cd9ee24a8bfd609cf19e0eaf9754650edb6419eb62b29c578f56f8a
[309 ms] Command failed: docker start f65921e65cd9ee24a8bfd609cf19e0eaf9754650edb6419eb62b29c578f56f8a
```
The first issue is that I would have expected the container to get rebuilt, given the mount value was changed.  It's not happening, though.  This is the first bug. Let's continue, however...

9. You should see an error dialog that says "An error occurred setting up the container.".  Click 'More Actions...'  In the top drop down, select "Rebuild Container".
Nothing will happen.  VSCode will just sit there.  Looking at the terminal window, I see this:
```
[72368 ms] Start: Run: docker remove -f f65921e65cd9ee24a8bfd609cf19e0eaf9754650edb6419eb62b29c578f56f8a
```
This the the second bug.  I believe the problem is there is no such command as `docker remove`? I think that should be `docker container rm`

At this point, the user needs to know how to manually remove the container on their own or rename the file back (which isn't always obvious) to get things working again.  

If there is a better workaround, please let me know.  The example I gave is a file, but it still applies to folders as well.  

Does this issue occur when you try this locally?: Yes

**Comment by Celthi** [comment]
I met the exact same errors after I switch to a new Mac to use the same devcontainer.json.
In my old Mac, the folder container .devcontainer is
dev_original
    .devcontainer/
       .devcontainer.json
    .vscode/
       .settings.json

In my new Mac
dev_new_name
    // containing the same thing as dev_original

I cannot use the `dev_new_name` to develop as what I did in the old Mac(dev_original) and met the same errors when I tried to sovled it.

**Comment by Celthi** [comment]
[11119 ms] Remote-Containers server: error during connect: Get http://docker/v1.40/containers/fa56461fba80c1f8b6ce9010e7f837d48f340f35a1b4bda395d071472e2b2804/json: command [ssh -l root -- 10.23.10.239 docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=kex_exchange_identification: read: Connection reset by peer
[11126 ms] Error: stream ended with:0 but wanted:9
        at p (/Users/xialu/.vscode/extensions/ms-vscode-remote.remote-containers-0.140.1/dist/extension.js:1:215920)
        at /Users/xialu/.vscode/extensions/ms-vscode-remote.remote-containers-0.140.1/dist/extension.js:1:216090
        at s (/Users/xialu/.vscode/extensions/ms-vscode-remote.remote-containers-0.140.1/dist/extension.js:1:231407)
        at Socket.<anonymous> (/Users/xialu/.vscode/extensions/ms-vscode-remote.remote-containers-0.140.1/dist/extension.js:1:231580)
        at Socket.emit (events.js:228:7)
        at endReadableNT (_stream_readable.js:1185:12)
        at processTicksAndRejections (internal/process/task_queues.js:81:21)
[11128 ms] Remote-Containers server terminated (code: 1, signal: null).

**Comment by chrmarti** [comment]
When you have the folder open locally, does `F1` > `Remote-Containers: Rebuild and Reopen in Container` work?
