### ISSUE TITLE
Can't run vscode server on my pi after update 

### ISSUE THREAD

**Issue by nicholmikey** [microsoft/vscode-remote-release#2840]
I just upgraded and I am now getting this error when VS code tries to start the server on my pi. Everything was OK before the upgrade. 

```
> TypeError: loader.config is not a function
>     at Object.<anonymous> (/home/pi/.vscode-server/bin/ff915844119ce9485abf
> e8aa9076ec76b5300ddd/out/bootstrap-amd.js:5:121)
>     at Module._compile (internal/modules/cjs/loader.js:774:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10
> )
>     at Module.load (internal/modules/cjs/loader.js:641:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:556:12)       
>     at Module.require (internal/modules/cjs/loader.js:681:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at Object.<anonymous> (/home/pi/.vscode-server/bin/ff915844119ce9485abf
> e8aa9076ec76b5300ddd/out/vs/server/main.js:5:373)
>     at Module._compile (internal/modules/cjs/loader.js:774:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10
> )
>     at Module.load (internal/modules/cjs/loader.js:641:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:556:12)       
>     at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)     
>     at internal/main/run_main_module.js:17:11
> <<< End of server log
```

I took a look in the loader.js file that it references and it's empty 

Here is the full log 

```
[20:01:01.883] > 
> 
[20:01:02.178] > 5b336a0f2a3b: running
> 
[20:01:02.235] > Acquiring lock on /home/pi/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-remote-lock.pi.ff915844119c
> e9485abfe8aa9076ec76b5300ddd
> 
[20:01:02.248] > \ln /home/pi/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-remote-lock.pi.ff915844119ce9485abfe8aa90
> 76ec76b5300ddd.target /home/pi/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-remote-lock.pi.ff915844
> 119ce9485abfe8aa9076ec76b5300ddd
> 
[20:01:02.260] > Found existing installation at /home/pi/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd...
> 
[20:01:02.332] > SHELL=/bin/bash
> LANGUAGE=en_US.UTF-8
> PWD=/home/pi
> LOGNAME=pi
> XDG_SESSION_TYPE=tty
> HOME=/home/pi
> LANG=en_US.UTF-8
> VSCODE_AGENT_FOLDER=/home/pi/.vscode-server        
> SSH_CONNECTION=192.168.0.111 53955 192.168.0.113 22
> XDG_SESSION_CLASS=user
> USER=pi
> SHLVL=1
> XDG_SESSION_ID=c7
> XDG_RUNTIME_DIR=/run/user/1000
> SSH_CLIENT=192.168.0.111 53955 22
> LC_ALL=en_US.UTF-8
> PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
> DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
> MAIL=/var/mail/pi
> _=/usr/bin/printenv
> Starting server with command... /home/pi/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/server.sh --host=127
> .0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/home/pi/.vscode-server/.ff915844119ce9485abfe8aa9076ec76b5300ddd.log"
>  < /dev/null
> Waiting for server log...
[20:01:02.350] > 
> 
[20:01:02.823] > Waiting for server log...
> 
[20:01:03.353] > Waiting for server log...
> 
[20:01:03.883] > Waiting for server log...
> 
[20:01:03.997] > SHLVL=1
> XDG_SESSION_ID=c7
> XDG_RUNTIME_DIR=/run/user/1000
> SSH_CLIENT=192.168.0.111 53955 22
> LC_ALL=en_US.UTF-8
> PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
> DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
> MAIL=/var/mail/pi
> _=/usr/bin/printenv
> Starting server with command... /home/pi/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/home/pi/.vscode-server/.ff915844119ce9485abfe8aa9076ec76b5300ddd.
> log" < /dev/null
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> 
> 
[20:01:04.412] > Waiting for server log...
> 
[20:01:04.947] > Waiting for server log...
> 
[20:01:05.478] > Waiting for server log...
> 
[20:01:05.984] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
[20:01:05.991] > 
> 
[20:01:06.030] > Server did not start successfully. Full server log at /home/pi/.vscode-server/.ff915844119ce9485abfe8aa9076ec76b5300ddd.log >>>
> 
[20:01:06.035] > /home/pi/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/bootstrap-amd.js:5
> "use strict";const loader=require("./vs/loader"),bootstrap=require("./bootstrap"),nlsConfig=bootstrap.setupNLS();loader.config({baseUrl:bootstrap.uriFromPath(__dirname),catchError:!0,nodeRequire:require,nodeMain:__filename,"vs/nls":nlsCon
> fig}),(process.env.ELECTRON_RUN_AS_NODE||process.versions.electron)&&loader.define("fs",["original-fs"],(function(o){return o})),nlsConfig.pseudo&&loader(["vs/nls"],(function(o){o.setPseudoTranslation(nlsConfig.pseudo)})),exports.load=fun
> ction(o,e,n){o&&(process.env.VSCODE_NODE_CACHED_DATA_DIR&&loader.config({nodeCachedData:{path:process.env.VSCODE_NODE_CACHED_DATA_DIR,seed:o}}),loader([o],e=e||function(){},n=n||function(o){console.error(o)}))};
>                                                                                                                         ^
> 
> TypeError: loader.config is not a function
>     at Object.<anonymous> (/home/pi/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/bootstrap-amd.js:5:121)
>     at Module._compile (internal/modules/cjs/loader.js:774:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
>     at Module.load (internal/modules/cjs/loader.js:641:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
>     at Module.require (internal/modules/cjs/loader.js:681:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at Object.<anonymous> (/home/pi/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/server/main.js:5:373)
>     at Module._compile (internal/modules/cjs/loader.js:774:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
>     at Module.load (internal/modules/cjs/loader.js:641:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
[20:01:06.045] > 
>     at internal/main/run_main_module.js:17:11
> <<< End of server log
> 5b336a0f2a3b##32##
[20:01:06.046] Received install output: 5b336a0f2a3b##32##
[20:01:06.046] Resolver error: The VS Code Server failed to start
[20:01:06.048] ------




[20:01:06.278] > 
> 
[20:01:06.537] "install" terminal command done
[20:01:06.538] Install terminal quit with output: 
```

Is there anything I can do?

**Comment by nicholmikey** [comment]
Never mind. I am a giant idiot. The pi was out of space, so when I tried to fix this by deleting the vscode-server folder and reinstalling it was not installing correctly.
