### ISSUE TITLE
cannot move 'vscode-server-linux-x64/node_modules' to './node_modules': Permission denied

### ISSUE THREAD

**Issue by tripolskypetr** [microsoft/vscode-remote-release#2941]
Why do I need to download something binary and proprietary for writing files via SSH to my server? There is definitely no telemetry? Ok, I understand that this is Microsoft, but now this software is simple broken. Could could you fix it?

```
[10:37:04.842] Log Level: 2
[10:37:04.843] remote-ssh@0.51.0
[10:37:04.843] darwin x64
[10:37:04.849] SSH Resolver called for "ssh-remote+10.0.0.57", attempt 1
[10:37:04.850] SSH Resolver called for host: 10.0.0.57
[10:37:04.850] Setting up SSH remote "10.0.0.57"
[10:37:04.854] Acquiring local install lock: /var/folders/fn/x3d1l7js2rl2pz95ppx557k40000gn/T/vscode-remote-ssh-10.0.0.57-install.lock
[10:37:04.866] Looking for existing server data file at /Users/tripolskypetr/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-10.0.0.57-ff915844119ce9485abfe8aa9076ec76b5300ddd-0.51.0/data.json
[10:37:04.866] Using commit id "ff915844119ce9485abfe8aa9076ec76b5300ddd" and quality "stable" for server
[10:37:04.868] Install and start server if needed
[10:37:04.876] Checking ssh with "ssh -V"
[10:37:04.917] > OpenSSH_7.9p1, LibreSSL 2.7.3
[10:37:04.920] askpass server listening on /var/folders/fn/x3d1l7js2rl2pz95ppx557k40000gn/T/vscode-ssh-askpass-3d972e1487f53cb4816ac6f1cd6f56fd973238f2.sock
[10:37:04.921] Spawning local server with {"ipcHandlePath":"/var/folders/fn/x3d1l7js2rl2pz95ppx557k40000gn/T/vscode-ssh-askpass-684e9ebcdd1fe291fc2ad46b1a460b91b7cdf9a9.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","64638","-o","ConnectTimeout=15","10.0.0.57"],"dataFilePath":"/Users/tripolskypetr/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-10.0.0.57-ff915844119ce9485abfe8aa9076ec76b5300ddd-0.51.0/data.json"}
[10:37:04.922] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/tripolskypetr/.vscode/extensions/ms-vscode-remote.remote-ssh-0.51.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/tripolskypetr/.vscode/extensions/ms-vscode-remote.remote-ssh-0.51.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/fn/x3d1l7js2rl2pz95ppx557k40000gn/T/vscode-ssh-askpass-3d972e1487f53cb4816ac6f1cd6f56fd973238f2.sock"}
[10:37:04.933] Spawned 25695
[10:37:05.090] > local-server> Spawned ssh: 25696
[10:37:05.103] stderr> OpenSSH_7.9p1, LibreSSL 2.7.3
[10:37:05.240] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:3AmYCLv9SPMXtzeziJc45S54zNdSfsgQZIHc8C4a8WU
[10:37:05.557] Got askpass request: {"request":"tripolskypetr@10.0.0.57's password:"}
[10:37:05.558] Showing password prompt
[10:37:05.561] Listening for interwindow password on /var/folders/fn/x3d1l7js2rl2pz95ppx557k40000gn/T/vscode-ssh-askpass-8bcb74fd206adf470c9ca86cf919906af922a69c.sock
[10:37:05.561] Writing password prompt to globalState
[10:37:10.172] Got password response
[10:37:10.172] Interactor gave response: **********
[10:37:10.173] Cleaning up other-window auth server
[10:37:10.230] stderr> Authenticated to 10.0.0.57 ([10.0.0.57]:22).
[10:37:11.074] > Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-17763-Microsoft x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
> 168 packages can be updated.
> 75 updates are security updates.
> 
> New release '18.04.4 LTS' available.
> Run 'do-release-upgrade' to upgrade to it.
> 
[10:37:11.106] > ready: 44a9f00a2095
[10:37:11.149] > Linux 4.4.0-17763-Microsoft #864-Microsoft Thu Nov 07 15:22:00 PST 2019
[10:37:11.149] Platform: linux
[10:37:11.236] > 44a9f00a2095: running
[10:37:11.521] > Acquiring lock on /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-remote-lock.tripolskypetr.ff915844119ce9485abfe8aa9076ec76b5300ddd
[10:37:11.539] > \ln /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-remote-lock.tripolskypetr.ff915844119ce9485abfe8aa9076ec76b5300ddd.target /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/vscode-remote-lock.tripolskypetr.ff915844119ce9485abfe8aa9076ec76b5300ddd
[10:37:11.605] > Installing to /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd...
[10:37:11.637] > 44a9f00a2095%%1%%
[10:37:11.639] > Downloading with wget
[10:37:37.577] > Download complete
> 44a9f00a2095%%2%%
[10:37:39.627] stderr> mv: cannot move 'vscode-server-linux-x64/node_modules' to './node_modules': Permission denied
[10:37:44.723] > SHELL=/bin/bash
> SSH_CLIENT=10.255.5.154 64639 22
> USER=tripolskypetr
> VSCODE_AGENT_FOLDER=/home/tripolskypetr/.vscode-server
> PATH=/home/tripolskypetr/bin:/home/tripolskypetr/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> MAIL=/var/mail/tripolskypetr
> PWD=/home/tripolskypetr
> HOME=/home/tripolskypetr
> SHLVL=2
> LOGNAME=tripolskypetr
> SSH_CONNECTION=10.255.5.154 64639 10.0.0.57 22
> XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
> _=/usr/bin/printenv
> OLDPWD=/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd
[10:37:44.725] > Starting server with command... /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown --disable-telemetry --port=0 &> "/home/tripolskypetr/.vscode-server/.ff915844119ce9485abfe8aa9076ec76b5300ddd.log" < /dev/null
[10:37:44.854] > Waiting for server log...
[10:37:45.457] > Waiting for server log...
[10:37:46.124] > Waiting for server log...
[10:37:46.641] > Waiting for server log...
[10:37:47.261] > Waiting for server log...
[10:37:47.841] > Waiting for server log...
[10:37:48.374] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[10:37:48.510] > Server did not start successfully. Full server log at /home/tripolskypetr/.vscode-server/.ff915844119ce9485abfe8aa9076ec76b5300ddd.log >>>
[10:37:48.538] > Error: Cannot find module 'minimist'
> Require stack:
> - /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/bootstrap-amd.js
> - /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/server/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
>     at Module.require (internal/modules/cjs/loader.js:681:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at t.load (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:16:119)
>     at e.load (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:13:586)
>     at i (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:29:189)
>     at Object.errorback (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:29:313)
>     at e.triggerErrorback (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:13:955)
>     at /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:13:659
>     at ReadFileContext.callback (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:16:494)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/bootstrap-amd.js',
>     '/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/server/main.js'
>   ],
>   phase: 'loading',
>   moduleId: 'minimist',
>   neededBy: [ 'vs/platform/environment/node/argv' ]
> }
> Error: Cannot find module 'applicationinsights'
> Require stack:
> - /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/bootstrap-amd.js
> - /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/server/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
>     at Module.require (internal/modules/cjs/loader.js:681:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at t.load (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:16:119)
>     at e.load (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:13:586)
>     at i (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:29:189)
>     at Object.errorback (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:29:313)
>     at e.triggerErrorback (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:13:955)
>     at /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:13:659
>     at ReadFileContext.callback (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:16:494)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/bootstrap-amd.js',
>     '/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/server/main.js'
>   ],
>   phase: 'loading',
>   moduleId: 'applicationinsights',
>   neededBy: [ 'vs/platform/telemetry/node/appInsightsAppender' ]
> }
> Error: Cannot find module 'cookie'
> Require stack:
> - /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/bootstrap-amd.js
> - /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/server/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
>     at Module.require (internal/modules/cjs/loader.js:681:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at t.load (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:16:119)
>     at e.load (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:13:586)
>     at i (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:29:189)
>     at Object.errorback (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:29:313)
>     at e.triggerErrorback (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:13:955)
>     at /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:13:659
>     at ReadFileContext.callback (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:16:494)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/bootstrap-amd.js',
>     '/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/server/main.js'
>   ],
>   phase: 'loading',
>   moduleId: 'cookie',
>   neededBy: [ 'vs/server/webClientServer' ]
> }
> Error: Cannot find module 'semver-umd'
> Require stack:
> - /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/bootstrap-amd.js
> - /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/server/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
>     at Module.require (internal/modules/cjs/loader.js:681:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at t.load (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:16:119)
>     at e.load (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:13:586)
>     at i (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:29:189)
>     at Object.errorback (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:29:313)
>     at e.triggerErrorback (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:13:955)
>     at /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:13:659
>     at ReadFileContext.callback (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:16:494)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/bootstrap-amd.js',
>     '/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/server/main.js'
>   ],
>   phase: 'loading',
>   moduleId: 'semver-umd',
>   neededBy: [
>     'vs/workbench/services/extensions/node/extensionPoints',
>     'vs/platform/extensionManagement/node/extensionManagementService',
>     'vs/code/node/cliProcessMain'
>   ]
> }
> Error: Cannot find module 'yauzl'
> Require stack:
> - /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/bootstrap-amd.js
> - /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/server/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
>     at Module.require (internal/modules/cjs/loader.js:681:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at t.load (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:16:119)
>     at e.load (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9
[10:37:48.538] > 076ec76b5300ddd/out/vs/loader.js:13:586)
>     at i (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:29:189)
>     at Object.errorback (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:29:313)
>     at e.triggerErrorback (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:13:955)
>     at /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:13:659
>     at ReadFileContext.callback (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:16:494)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/bootstrap-amd.js',
>     '/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/server/main.js'
>   ],
>   phase: 'loading',
>   moduleId: 'yauzl',
>   neededBy: [ 'vs/base/node/zip' ]
> }
> Error: Cannot find module 'yazl'
> Require stack:
> - /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/bootstrap-amd.js
> - /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/server/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
>     at Module.require (internal/modules/cjs/loader.js:681:19)
>     at require (internal/modules/cjs/helpers.js:16:16)
>     at t.load (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:16:119)
>     at e.load (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:13:586)
>     at i (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:29:189)
>     at Object.errorback (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:29:313)
>     at e.triggerErrorback (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:13:955)
>     at /home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:13:659
>     at ReadFileContext.callback (/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/loader.js:16:494)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/bootstrap-amd.js',
>     '/home/tripolskypetr/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/server/main.js'
>   ],
>   phase: 'loading',
>   moduleId: 'yazl',
>   neededBy: [ 'vs/base/node/zip' ]
> }
> <<< End of server log
> 44a9f00a2095##32##
[10:37:48.539] Received install output: 44a9f00a2095##32##
[10:37:48.540] Terminating local server
[10:37:48.545] Resolver error: The VS Code Server failed to start
[10:37:48.554] Local server exit: 15
[10:37:48.562] ------
```

**Comment by rzhao271** [comment]
Closing this issue as part of housekeeping.

@tripolskypetr feel free to reply if this issue still occurs for you on the latest version of VS Code (preferably Insiders edition).
