### ISSUE TITLE
Remote Containers: "try a sample" fails

### ISSUE THREAD

**Issue by jgbustos** [microsoft/vscode-remote-release#2980]
VSCode Version: 1.45.0 (user setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z (4 days ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
ms-vscode-remote.remote-containers v0.117.0
Docker desktop 2.3.0.2 (45183) using WSL2 engine

Steps to Reproduce:

1. Download the Windows x64 zip file from https://code.visualstudio.com/download
2. Extract the zip file contents to c:\PortableApps\VSCode
3. Create folder c:\PortableApps\VSCode\data to run c:\PortableApps\VSCode\code.exe in portable mode
4. Install v0.117.0 of Remove Containers extension
5. Click on "Remote Explorer", select "Containers" in the drop-down, "Try a sample"
6. Choose a language. Any will do, I have replicated this with PHP, Python and Java
7. An error message "An error occurred setting up the container." will appear

The contents of the terminal tab are:

```
[1 ms] Start: Resolving remote
[3 ms] Start: Check Docker is running
[3 ms] Start: Run: docker info
[420 ms] Start: Run: docker volume ls -q
[577 ms] Start: Run: docker ps -q -a --filter label=vsch.local.repository=https://github.com/Microsoft/vscode-remote-try-python --filter label=vsch.local.repository.volume=vsc-remote-sample --filter label=vsch.local.repository.folder=vscode-remote-try-python --filter label=vsch.quality=stable
[733 ms] Start: Run: docker build -f c:\PortableApps\VSCode\data\extensions\ms-vscode-remote.remote-containers-0.117.0\scripts\volumeBootstrap.Dockerfile -t vsc-volume-bootstrap c:\PortableApps\VSCode\data\extensions\ms-vscode-remote.remote-containers-0.117.0\scripts
[858 ms] Error: Unable to start terminal process: CreateProcess failed
        at new WindowsPtyAgent (c:\PortableApps\VSCode\resources\app\node_modules.asar\node-pty\lib\windowsPtyAgent.js:77:36)
        at new WindowsTerminal (c:\PortableApps\VSCode\resources\app\node_modules.asar\node-pty\lib\windowsTerminal.js:50:24)
        at Object.spawn (c:\PortableApps\VSCode\resources\app\node_modules.asar\node-pty\lib\index.js:28:12)
        at c:\PortableApps\VSCode\data\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:5211
        at async Object.t.runCommand (c:\PortableApps\VSCode\data\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:8512)
        at async c:\PortableApps\VSCode\data\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:118726
        at async Object.D [as cloneAndBuildRepository] (c:\PortableApps\VSCode\data\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:118585)
        at async Object.t.openDockerfileRepoDevContainer (c:\PortableApps\VSCode\data\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:165567)
```
EDIT: I wrongly presumed that the issue only occurrs when the user folder has space chars in it

**Comment by andy-cheetham** [comment]
I've just started getting this same error, but I don't have spaces in my user directory.

**Comment by ssmendon** [comment]
I have a similar error.

```
[46 ms] Start: Check Docker is running
[46 ms] Start: Run: docker info
[211 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=c:\Users\dfire\Documents\personal\dockerized-projects\latex --filter label=vsch.quality=stable
[278 ms] Start: Run: docker build -f c:\Users\dfire\Documents\personal\dockerized-projects\latex\.devcontainer\Dockerfile -t vsc-latex-b02ed263eefe0bdd33eb04ec6069f4b7 c:\Users\dfire\Documents\personal\dockerized-projects\latex
[358 ms] Error: Unable to start terminal process: CreateProcess failed
        at new WindowsPtyAgent (c:\Users\dfire\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsPtyAgent.js:77:36)
        at new WindowsTerminal (c:\Users\dfire\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsTerminal.js:50:24)
        at Object.spawn (c:\Users\dfire\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\index.js:28:12)
        at c:\Users\dfire\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:5211
        at async Object.t.runCommand (c:\Users\dfire\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:8512)
        at async c:\Users\dfire\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:162431
        at async Object.t.openDockerfileDevContainer (c:\Users\dfire\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:162334)
```

I think it's caused by a path that's wrong inside the application. In the first error message, it tries to open `...\node_modules.asar\node-pty\lib`, but there isn't a `lib` folder. There is a `build\Release\winpty-agent.exe` folder, though.

**Comment by BilalArxd** [comment]
I've just started with Dev Containers and got the same error. Tried reinstalling VSCode and Docker but still no luck. I have checked the directory where it tries to open **...node-pty\lib\windowsPtyAgent.js** but there is only a build folder inside the node-pty directory.

**Visual Studio Code Version:**
```
> Version: 1.45.0 (user setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z (5 days ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Logs:** 
```[0 ms] Start: Resolving remote
[4 ms] Start: Check Docker is running
[4 ms] Start: Run: docker info
[386 ms] Start: Run: docker volume ls -q
[519 ms] Start: Run: docker ps -q -a --filter label=vsch.local.repository=https://github.com/Microsoft/vscode-remote-try-dotnetcore --filter label=vsch.local.repository.volume=vsc-remote-sample --filter label=vsch.local.repository.folder=vscode-remote-try-dotnetcore --filter label=vsch.quality=stable
[661 ms] Start: Run: docker build -f c:\Users\Bilal\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\scripts\volumeBootstrap.Dockerfile -t vsc-volume-bootstrap c:\Users\Bilal\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\scripts
[871 ms] Error: Unable to start terminal process: CreateProcess failed
        at new WindowsPtyAgent (c:\Users\Bilal\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsPtyAgent.js:77:36)
        at new WindowsTerminal (c:\Users\Bilal\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsTerminal.js:50:24)
        at Object.spawn (c:\Users\Bilal\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\index.js:28:12)
        at c:\Users\Bilal\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:5211
        at async Object.t.runCommand (c:\Users\Bilal\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:8512)
        at async c:\Users\Bilal\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:118726
        at async Object.D [as cloneAndBuildRepository] (c:\Users\Bilal\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:118585)
        at async Object.t.openDockerfileRepoDevContainer (c:\Users\Bilal\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:165567)
```



**Contents of node-pty directory:**
```

PS ...\Microsoft VS Code\resources\app\node_modules.asar.unpacked\node-pty> ls

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        5/12/2020   2:01 AM                build

```

**Comment by BilalArxd** [comment]
Resolved it by doing steps recommended by @chrmarti in [2975](https://github.com/microsoft/vscode-remote-release/issues/2975#issuecomment-627456260) thread.

**Comment by jgbustos** [comment]
Agreed, renaming the file docker to docker.sh in folder C:\Program Files\Docker\Docker\resources\bin is a valid workaround. I'll mark this issue a duplicate of #2975. Thanks for the tip @BilalArxd
