### ISSUE TITLE
"Open folder in container" fails in Docker WSL 2 mode

### ISSUE THREAD

**Issue by guyuxiang** [microsoft/vscode-remote-release#2983]
- VSCode Version: 1.45.0
- Local OS Version: Windows 10 Pro, version 2004, build 19041.208
- Remote OS Version: WSL2, Ubuntu 20.04
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Set-up.
install ubuntu(20.04) as WSL 2
set Docker desktop to WSL 2 mode
2. Start vscode and open a folder in any container. It will give the following error message.

Comment:
1. Swtich docker to HyperV mode, vscode opening folder in container works fine.
2. In docker WSL 2 mode, running "docker build" in a terminal(cmd) outside vscode works fine.
3. WSL 2 Ubuntu works fine.

```
[0 ms] Start: Resolving remote
[3 ms] Setting up container for folder or workspace: c:\Users\yuxia\docker_volumes\code-server\projects

[27 ms] Start: Run: git rev-parse --show-toplevel
[115 ms] Start: Check Docker is running
[116 ms] Start: Run: docker info
[534 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=c:\Users\yuxia\docker_volumes\code-server\projects --filter label=vsch.quality=stable
[688 ms] Start: Run: docker build -f c:\Users\yuxia\docker_volumes\code-server\projects\.devcontainer\Dockerfile -t vsc-projects-26965546232624e4aa53b6bf280f0d9c c:\Users\yuxia\docker_volumes\code-server\projects\.devcontainer
[859 ms] Error: Unable to start terminal process: CreateProcess failed
        at new WindowsPtyAgent (c:\Users\yuxia\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsPtyAgent.js:77:36)
        at new WindowsTerminal (c:\Users\yuxia\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsTerminal.js:50:24)
        at Object.spawn (c:\Users\yuxia\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\index.js:28:12)
        at c:\Users\yuxia\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:5211
        at async Object.t.runCommand (c:\Users\yuxia\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:8512)
        at async c:\Users\yuxia\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:162431
        at async Object.t.openDockerfileDevContainer (c:\Users\yuxia\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:162334)
```

Does this issue occur when you try this locally?:  No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by guyuxiang** [comment]
Duplicated with #2975
