### ISSUE TITLE
Got bad result from install script

### ISSUE THREAD

**Issue by jakiechris** [microsoft/vscode-remote-release#3004]
The terminal process command 'C:\windows\System32\cmd.exe /c (type "D:\Users\LIUZHEN290\AppData\Local\Temp\vscode-.......sh" | "C...\ssh.exe" -T -D 1319 19.23.41.23 bash) & exit /b 0' failed to launch exit code {2}

win10 wants to connect to centos7

manually input 'C:\windows\System32\cmd.exe /c (type "D:\Users\LIUZHEN290\AppData\Local\Temp\vscode-.......sh" | "C...\ssh.exe" -T -D 1319 19.23.41.23 bash) & exit /b 0' to my cmd window , it works just fine .

any helps?

**Comment by gpkvt** [comment]
Same problem here, Win 10 2004 to Debian (Stretch, Buster, x64, arm)

**Comment by roblourens** [comment]
Is this still an issue?

**Comment by diepes** [comment]
I just ran into this after upgrading Win10,  connecting to virtual-box.
Putty connection from Win10 still works fine.

OUTPUT
`[08:33:23.396] Log Level: 2
[08:33:23.454] remote-ssh@0.56.0
[08:33:23.455] win32 x64
[08:33:23.456] SSH Resolver called for "ssh-remote+vbox-debian", attempt 1
[08:33:23.457] SSH Resolver called for host: vbox-debian
[08:33:23.457] Setting up SSH remote "vbox-debian"
[08:33:23.505] Using commit id "e5a624b788d92b8d34d1392e4c4d9789406efe8f" and quality "stable" for server
[08:33:23.506] Install and start server if needed
[08:33:23.510] Checking ssh with "ssh -V"
[08:33:23.729] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[08:33:23.734] Running script with connection command: ssh -T -D 52516 vbox-debian bash
[08:33:23.744] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[08:33:23.826] "install" terminal command done
[08:33:23.826] Install terminal quit with output: 
[08:33:23.833] Resolver error: Error: Got bad result from install script
	at Function.NotAvailable (c:\Users\smitp\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:517:659)
	at I (c:\Users\smitp\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:127:106870)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\smitp\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:127:104974
	at async Object.t.withShowDetailsEvent (c:\Users\smitp\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:127:110096)
	at async Object.t.resolve (c:\Users\smitp\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:127:108158)
	at async c:\Users\smitp\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:127:143767
[08:33:23.836] ------`
