### ISSUE TITLE
Open New External Terminal does not seem to work

### ISSUE THREAD

**Issue by oliverpool** [microsoft/vscode-remote-release#3058]
- VSCode Version: 1.45.1
- Local OS Version: Arch Linux
- Remote OS Version: N/A
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Open a dev container (docker)
2. Launch `Open New External Terminal` command

Expected behavior:
3. my external terminal opens (or at least some error message)

Actual behavior:
3. nothing happens (I can see `CommandService#executeCommand workbench.action.terminal.openNativeConsole` when running in `--verbose` mode)

Does this issue occur when you try this locally?: No, everything works fine when the container is disabled

**Comment by chrmarti** [comment]
Does this work when not connected to a container?

**Comment by oliverpool** [comment]
Yes, it works when not connected to the container (see the last sentence of my original post).

I just saw that "Open Containing Folder" is not available when connected to the container. Maybe the "Open New External Terminal" should be disabled as well in this situation.

---

I would actually prefer to have access to both features, when running a container locally (but this is probably quite hard to do - especially considering if the container is local or not)

**Comment by marveloo** [comment]
When I try to open an external terminal on Remote-WSL with the default keyboard shortcut `Ctrl+Shift+C`, nothing happens too. Console in Developer Tools shows this error:

```
  ERR spawn C:\WINDOWS\system32\cmd.exe ENOENT: Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```
I have no terminal related settings in settings.json.

There are no issues when in local (non-remote) environment.

VSCode Version: 1.46.1
OS: Windows_NT x64 10.0.19041

**Comment by oliverpool** [comment]
@chrmarti do you need more info?

**Comment by adamwtow** [comment]
Hacky temp fix for the meantime (if your container is on the same host and you have X forwarding setup already), install your terminal in your devcontainer.json's `postCreateCommand` and launch it as a background process in `postAttachCommand`.

**Comment by cjtim** [comment]
Install this [Shell Launcher - Vscode](https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher)

in settings.json insert this
```
"shellLauncher.shells.linux": [
        {
            "shell": "/bin/zsh",
            "args": [
                "-c",
                "powershell.exe \"wt.exe -d $(pwd)\"",
            ],
            "label": "Windows Terminal"
        },
        {
            "shell": "/bin/bash",
            "label": "bash"
        },
        {
            "shell": "/bin/zsh",
            "label": "zsh"
        },
        {
            "shell": "zsh",
            "args": [
                "-l"
            ],
            "label": "zsh login shell"
        },
        {
            "shell": "bash",
            "args": [
                "-l"
            ],
            "label": "bash login shell"
        }
    ],

```
![](https://i.ibb.co/19HH2XC/Screenshot-2020-09-28-145123.jpg)

Press **Ctrl + Shift + T** to open shell launcher
