### ISSUE TITLE
Support remote SSH development on AIX

### ISSUE THREAD

**Issue by Dshamgar** [microsoft/vscode-remote-release#3059]
Please support remote SSH development on AIX platforms (in addition to linux x86).

**Comment by panchals17** [comment]
Agree with @Dshamgar

**Comment by torinreilly** [comment]
I don't think this support would be difficult to add and would benefit a number of enterprise customers. The SSH login seems to be working fine, but hits a "timeout" after issuing a uname command (despite seeming to be properly connected). This is what the output looks like on my Mac trying to connect to an AIX host:
```
10:40:24.179] > local-server> Spawned ssh: 94201
[10:40:24.186] stderr> OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019
[10:40:25.013] stderr> debug1: Server host key: REDACTED REDACTED
[10:40:26.112] Got askpass request: {"request":"root@REDACTED's password:"}
[10:40:26.114] Showing password prompt
[10:40:26.115] Listening for interwindow password on /var/folders/kw/kp6pyf5n2cg4sq6l0jvx37w80000gn/T/vscode-ssh-askpass-87cb00cc91dab19dc0e513f75105a4c1028c75ca.sock
[10:40:26.115] Writing password prompt to globalState
[10:40:31.342] Got password response
[10:40:31.342] Interactor gave response: ******
[10:40:31.342] Cleaning up other-window auth server
[10:40:31.711] stderr> Authenticated to REDACTED ([REDACTED]:22).
[10:40:32.235] > ready: 7eb56ede7b8a
[10:40:32.312] > AIX 1 7
[10:41:33.349] Terminating local server
[10:41:33.350] Resolver error: Connecting with SSH timed out
[10:41:33.358] ------
```

**Comment by waltlillyman** [comment]
Agree w/ @Dshamgar

**Comment by ponchofiesta** [comment]
They seem to have fixed the timeout by explicitly checking supported OS:

```
[...]
[16:04:02.336] > ddca0ecb3e2b: running
> 
[16:04:02.457] > Unsupported platform: AIX
> ddca0ecb3e2b##35##
> 
[16:04:02.458] Received install output: ddca0ecb3e2b##35##
[16:04:02.458] Server installation failed with exit code 35 and output ddca0ecb3e2b##35##
[16:04:02.462] Resolver error: Error: 
	at Function.Create (c:\Users\XXX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:130564)
	at Object.t.handleInstallOutput (c:\Users\XXX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:129103)
	at I (c:\Users\XXX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:106775)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\XXX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:104774
	at async Object.t.withShowDetailsEvent (c:\Users\XXX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:109845)
	at async Object.t.resolve (c:\Users\XXX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107960)
	at async c:\Users\XXX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:141955
[16:04:02.465] ------




[16:04:02.877] "install" terminal command done
[16:04:02.877] Install terminal quit with output: 
```

I assume the problem is the different build architecture. You'll need the hardware and the OS. And you'll need Node.js and all dependencies running on that OS. And all this needs to be tested and supported for a really small user base I assume. If Remote SSH would be open source this might be a community feature.

**Comment by stuboydl** [comment]
RISC AIX 5.3 also doesn't seem to like "grep -a" nor does it have /etc/os-release (although it could be created)

[14:50:20.062] > Unsupported platform: AIX
> exitCode==35==
> osReleaseId==AIX==       
...
> grep: illegal option -- a

**Comment by Raph-xyz** [comment]
It really seems to come from a incorrect call to grep on AIX environment.
I found that the -a flag is used to read binaries, and IBM doesn't seem to have implemented a similar flag : https://www.ibm.com/docs/en/aix/7.1?topic=g-grep-command#grep__row-d3e144040

[11:14:27.657] > 3c34c1ea0eaf: running
[11:14:27.670] > grep: Not a recognized flag: a
> Usage: grep [-r] [-R] [-H] [-L] [-E|-F] [-c|-l|-q] [-insvxbhwyu] [-p[parasep]] -e pattern_list...    
>         [-f pattern_file...] [file...]
> Usage: grep [-r] [-R] [-H] [-L]  [-E|-F] [-c|-l|-q] [-insvxbhwyu] [-p[parasep]] [-e pattern_list...] 
>         -f pattern_file... [file...]
> Usage: grep [-r] [-R] [-H] [-L] [-E|-F] [-c|-l|-q] [-insvxbhwyu] [-p[parasep]] pattern_list [file...]
[11:14:27.700] > 
> grep: Not a recognized flag: a
> Usage: grep [-r] [-R] [-H] [-L] [-E|-F] [-c|-l|-q] [-insvxbhwyu] [-p[parasep]] -e pattern_list...     
>         [-f pattern_file...] [file...]
> Usage: grep [-r] [-R] [-H] [-L]  [-E|-F] [-c|-l|-q] [-insvxbhwyu] [-p[parasep]] [-e pattern_list...]  
>         -f pattern_file... [file...]
> Usage: grep [-r] [-R] [-H] [-L] [-E|-F] [-c|-l|-q] [-insvxbhwyu] [-p[parasep]] pattern_list [file...] 
[11:14:27.700] > Unsupported platform: AIX
> 3c34c1ea0eaf: start
> exitCode==35==
> listeningOn====
> osReleaseId==AIX==
> arch====
> tmpDir==/tmp==
> platform====
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 3c34c1ea0eaf: end
[11:14:27.701] Received install output: 
exitCode==35==
listeningOn====
osReleaseId==AIX==
arch====
tmpDir==/tmp==
platform====
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[11:14:27.702] Failed to parse remote port from server output
[11:14:27.702] Resolver error: Error: 
	at Function.Create (c:\Users\MrX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64659)
	at Object.t.handleInstallOutput (c:\Users\MrX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:63302)
	at Object.t.tryInstall (c:\Users\MrX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:415135)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\MrX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:294918
	at async Object.t.withShowDetailsEvent (c:\Users\MrX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:406463)
	at async Object.t.resolve (c:\Users\MrX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:295994)
	at async c:\Users\MrX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:127:110656
[11:14:27.706] ------

**Comment by Aabderahim** [comment]
Installed GNU version of grep pattern matching utilities,
Created ln -sf /opt/freeware/bin/grep_64 /usr/bin/grep,
That grep error fixed, but i still unsupported error 

[15:07:47.855] > 1e568c6d9f13: running
> 
[15:07:47.893] > Unsupported platform: AIX
> 1e568c6d9f13: start      
> exitCode==35==
> listeningOn====
> osReleaseId==AIX==       
> arch====
> tmpDir==/tmp==
> platform====
> unpackResult====
> didLocalDownload==0==    
> downloadTime====
> installTime====
> extInstallTime====       
> serverStartTime====      
> 1e568c6d9f13: end        
> 
[15:07:47.894] Received install output:       
exitCode==35==
listeningOn====
osReleaseId==AIX==       
arch====
tmpDir==/tmp==
platform====
unpackResult====
didLocalDownload==0==    
downloadTime====
installTime====
extInstallTime====       
serverStartTime====      

[15:07:47.894] Failed to parse remote port from server output
[15:07:47.895] Resolver error: Error: 
	at Function.Create (c:\Users\X215941\OneDrive - GROUP DIGITAL WORKPLACE\Documents\Tools\VSCode-win32-x64-1.63.2\data\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:430425)
	at Object.t.handleInstallOutput (c:\Users\X215941\OneDrive - GROUP DIGITAL WORKPLACE\Documents\Tools\VSCode-win32-x64-1.63.2\data\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:429068)
	at Object.t.tryInstall (c:\Users\X215941\OneDrive - GROUP DIGITAL WORKPLACE\Documents\Tools\VSCode-win32-x64-1.63.2\data\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:524212)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\X215941\OneDrive - GROUP DIGITAL WORKPLACE\Documents\Tools\VSCode-win32-x64-1.63.2\data\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:487216
	at async Object.t.withShowDetailsEvent (c:\Users\X215941\OneDrive - GROUP DIGITAL WORKPLACE\Documents\Tools\VSCode-win32-x64-1.63.2\data\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:490561)
	at async Object.t.resolve (c:\Users\X215941\OneDrive - GROUP DIGITAL WORKPLACE\Documents\Tools\VSCode-win32-x64-1.63.2\data\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:488295)
	at async c:\Users\X215941\OneDrive - GROUP DIGITAL WORKPLACE\Documents\Tools\VSCode-win32-x64-1.63.2\data\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:564197
[15:07:47.903] ------




[15:07:49.690] "install" terminal command done
[15:07:49.690] Install terminal quit with output: 

Do you know how can i modify list of OS supported ?

thanks.

**Comment by ifirxl** [comment]
Agree it .Hope will support AIX

**Comment by knmiecc** [comment]
Any chance, this may be tackled in the nearer future?

**Comment by BriRoCh** [comment]
Many companies still depend on AIX but can't use VS Code due to the lack of ssh connectivity. Therefore seeking alternative products.

**Comment by laihaotao** [comment]
I am a IBMer and really want to have AIX supported lol .... I don't want to play with vim every day :(

**Comment by massimosil** [comment]
We would also like this to be implemented. It would make many activities much faster

**Comment by bob109** [comment]
This is disappointing that AIX is still not supported. It makes up half  of our *nix environment.

**Comment by mlaskie** [comment]
Agreed, our company has a large AIX base as well.  
This approach is surely exciting for upcoming development efforts.

**Comment by jodytek** [comment]
I would also like to request this functionality. Long time AIX admin needing to integrate modern tools for development. 

Don't make me take this to the VUG...

**Comment by dbmill** [comment]
+1 to the need of AIX support.

**Comment by Riorlan** [comment]
+1

**Comment by asalih** [comment]
+1

**Comment by suchismith1993** [comment]
+1. Has any one been able to get an alternate tool to do remote development for AIX. ?

**Comment by bova** [comment]
+1

**Comment by vipfrog** [comment]
+10086

**Comment by Toufa7** [comment]
+1

**Comment by tblok** [comment]
+1 we would like to have this

**Comment by kesavanm** [comment]
Missing remote support on AIX

**Comment by sboldt1978** [comment]
+1 would also be important for development for us

**Comment by kashwy** [comment]
+1 we would like to have this

**Comment by dzozii** [comment]
Also Linux PPC64 would be nice and maybe it is easier to implement.

**Comment by WindArcher** [comment]
Missing remote support on AIX

**Comment by JulienAlleaume** [comment]
+1 yes, we would like to have this

**Comment by tonykuttai** [comment]
+1 would like to have this

**Comment by AShaw-GHIB** [comment]
+1 we definitely need this support for AIX

**Comment by TWolfis** [comment]
+1 to this feature

**Comment by ayushjainibm951-code** [comment]
+1

**Comment by Er4twXz** [comment]
Did anyone try out 

AIX Remote Development Extension
A VS Code extension for remote development on AIX machines. Provides terminal access, file browsing, and automatic server deployment over SSH.


https://github.com/tonykuttai/open-remote-aix ?

**Comment by Dshamgar** [comment]
> Did anyone try out
> 
> AIX Remote Development Extension A VS Code extension for remote development on AIX machines. Provides terminal access, file browsing, and automatic server deployment over SSH.
> 
> https://github.com/tonykuttai/open-remote-aix ?

I did try it. I thinks it's very promising, but would require some enhancements for logging in with a SecureID token. It appeared to only support userid/password logins when I tried it out a while back.

**Comment by tonykuttai** [comment]
Please try out the latest version: https://github.com/tonykuttai/open-remote-ssh Let me know if you face any issues :)

**Comment by pablohdzvizcarra** [comment]
+1 would like to have this

Please add the support fox AIX
