### ISSUE TITLE
Failed to connect to the remote extension host server

### ISSUE THREAD

**Issue by manvithn** [microsoft/vscode-remote-release#3097]
- VSCode Version:
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
- Local OS Version: macOS Catalina 10.15.4
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Tried to connect to remote
2. Receive the following errors:
```
Failed to connect to the remote extension host server (Error: Time limit reached)
Could not fetch remote environment
```

Remote - SSH logs:
```
[19:01:45.181] Log Level: 2
[19:01:45.183] remote-ssh@0.51.0
[19:01:45.183] darwin x64
[19:01:45.184] SSH Resolver called for "ssh-remote+[REMOTE]", attempt 1
[19:01:45.184] SSH Resolver called for host: [REMOTE]
[19:01:45.185] Setting up SSH remote "[REMOTE]"
[19:01:45.187] Acquiring local install lock: /var/folders/mh/h565l85n6x75fkshp50j60qwk20mrp/T/vscode-remote-ssh-[REMOTE]-install.lock
[19:01:45.198] Looking for existing server data file at /Users/[USER]/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-[REMOTE]-5763d909d5f12fe19f215cbfdd29a91c0fa9208a-0.51.0/data.json
[19:01:45.199] Using commit id "5763d909d5f12fe19f215cbfdd29a91c0fa9208a" and quality "stable" for server
[19:01:45.205] Install and start server if needed
[19:01:45.244] Checking ssh with "ssh -V"
[19:01:45.275] > OpenSSH_8.1p1, LibreSSL 2.7.3
[19:01:45.277] askpass server listening on /var/folders/mh/h565l85n6x75fkshp50j60qwk20mrp/T/vscode-ssh-askpass-8c14fb3bcd39ac42b3ab46fb041eae416d7ec0b3.sock
[19:01:45.278] Spawning local server with {"ipcHandlePath":"/var/folders/mh/h565l85n6x75fkshp50j60qwk20mrp/T/vscode-ssh-askpass-6d02f57bd672d3c3b7c8b2b1ffebc9292b669b03.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","64337","-o","ConnectTimeout=60","[REMOTE]"],"dataFilePath":"/Users/[USER]/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-[REMOTE]-5763d909d5f12fe19f215cbfdd29a91c0fa9208a-0.51.0/data.json"}
[19:01:45.278] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/[USER]/.vscode/extensions/ms-vscode-remote.remote-ssh-0.51.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/[USER]/.vscode/extensions/ms-vscode-remote.remote-ssh-0.51.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/mh/h565l85n6x75fkshp50j60qwk20mrp/T/vscode-ssh-askpass-8c14fb3bcd39ac42b3ab46fb041eae416d7ec0b3.sock"}
[19:01:45.280] Spawned 5292
[19:01:45.372] > local-server> Spawned ssh: 5293
[19:01:45.375] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[19:01:45.843] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:RZW3VzrRwpXDjUnhyYuetDJ4Gy9N8+BnD6WOO5L0nRY
[19:01:46.431] stderr> Authenticated to 172.25.151.193 ([172.25.151.193]:22).
[19:01:58.294] > ready: 883085f83ee7
[19:01:58.406] > Linux 5.3.0-7629-generic #31~1581628854~18.04~2db8a7a~dev-Ubuntu SMP Fri Feb 14 19:57:43 
[19:01:58.407] Platform: linux
[19:01:58.753] > 883085f83ee7: running
[19:01:58.792] > Acquiring lock on /home/[USER]/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/vscode-remote-lock.[USER].5763d909d5f12fe19f215cbfdd29a91c0fa9208a
[19:01:58.794] > \ln /home/[USER]/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/vscode-remote-lock.[USER].5763d909d5f12fe19f215cbfdd29a91c0fa9208a.target /home/[USER]/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/vscode-remote-lock.[USER].5763d909d5f12fe19f215cbfdd29a91c0fa9208a
[19:01:58.799] > Found existing installation at /home/[USER]/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a...
[19:01:58.838] > Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[19:01:58.852] > Checking server status on port 36443 with wget
[19:01:58.860] > 883085f83ee7: start
> sshAuthSock====
> agentPort==36443==
> osReleaseId==ubuntu==
> arch==x86_64==
> webUiAccessToken====
> tmpDir==/run/user/1001==
> platform==linux==
[19:01:58.865] > 883085f83ee7: end
[19:01:58.866] Received install output: 
sshAuthSock====
agentPort==36443==
osReleaseId==ubuntu==
arch==x86_64==
webUiAccessToken====
tmpDir==/run/user/1001==
platform==linux==
[19:01:58.866] Remote server is listening on port 36443
[19:01:58.866] Parsed server configuration: {"agentPort":36443,"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/1001","platform":"linux"}
[19:01:58.868] Persisting server connection details to /Users/[USER]/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-[REMOTE]-5763d909d5f12fe19f215cbfdd29a91c0fa9208a-0.51.0/data.json
[19:01:58.871] Starting forwarding server. localPort 64344 -> socksPort 64337 -> remotePort 36443
[19:01:58.871] Forwarding server listening on 64344
[19:01:58.871] Waiting for ssh tunnel to be ready
[19:01:58.872] [Forwarding server 64344] Got connection 0
[19:01:58.874] Tunneled remote port 36443 to local port 64344
[19:01:58.874] Resolved "ssh-remote+[REMOTE]" to "127.0.0.1:64344"
[19:01:58.883] ------




[19:01:58.932] [Forwarding server 64344] Got connection 1
[19:01:58.933] [Forwarding server 64344] Got connection 2
[19:01:58.992] Failed to set up socket for dynamic port forward to remote port 36443: Socket closed. Is the remote port correct?
[19:01:59.046] Failed to set up socket for dynamic port forward to remote port 36443: Socket closed. Is the remote port correct?
[19:01:59.046] Failed to set up socket for dynamic port forward to remote port 36443: Socket closed. Is the remote port correct?
```

Window Logs:
```
[2020-06-01 19:02:28.934] [renderer5] [error] [remote-connection] The time limit has been reached for a connection. Error:
[2020-06-01 19:02:28.934] [renderer5] [error] Error: Time limit reached
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1835:292
[2020-06-01 19:02:28.934] [renderer5] [error] [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
[2020-06-01 19:02:28.934] [renderer5] [error] Error: Time limit reached
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1835:292
[2020-06-01 19:02:29.054] [renderer5] [error] [remote-connection] The time limit has been reached for a connection. Error:
[2020-06-01 19:02:29.054] [renderer5] [error] Error: Time limit reached
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1835:292
[2020-06-01 19:02:29.054] [renderer5] [error] [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
[2020-06-01 19:02:29.055] [renderer5] [error] Error: Time limit reached
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1835:292
[2020-06-01 19:02:29.067] [renderer5] [error] Time limit reached: Error: Time limit reached
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1835:292
[2020-06-01 19:02:29.068] [renderer5] [error] Could not fetch environment: Error: Could not fetch environment
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4327:126
```

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by manvithn** [comment]
Looks like my remote server disabled port forwarding for certain accounts. Closing the issue.
