### ISSUE TITLE
Failed to connect to the remote extension host server (Error: handshake timeout)

### ISSUE THREAD

**Issue by benliddicott** [microsoft/vscode-remote-release#3102]
Appear to be other connection issues but none with this message mentioned.
Also fails in vscode-insiders, same error

- VSCode Version: 1.45.1 (user setup)
- Local OS Version: Windows_NT x64 10.0.14393
- Remote OS Version: Linux virtual-machine 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Remote Extension/Connection Type: SSH

Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.14393

**Steps to Reproduce:**

1. Attempt to connect to previously working workspace
2. Fail with error handshake timeout

Does this issue occur when you try this locally?: **No**
Does this issue occur when you try this locally and all extensions are disabled?: **No**

**Log from Remote - SSH:**
```

[12:03:41.810] Log Level: 2
[12:03:41.817] remote-ssh@0.51.0
[12:03:41.818] win32 x64
[12:03:41.820] SSH Resolver called for "ssh-remote+buildsc-ben", attempt 1
[12:03:41.820] SSH Resolver called for host: buildsc-ben
[12:03:41.820] Setting up SSH remote "buildsc-ben"
[12:03:41.874] Using commit id "5763d909d5f12fe19f215cbfdd29a91c0fa9208a" and quality "stable" for server
[12:03:41.875] Install and start server if needed
[12:03:41.879] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[12:03:41.881] Got error from ssh: spawn C:\WINDOWS\System32\OpenSSH\ssh.exe ENOENT
[12:03:41.882] The specified path C:\WINDOWS\System32\OpenSSH\ssh.exe is not a valid SSH binary
[12:03:41.882] Checking ssh with "ssh -V"
[12:03:41.940] > OpenSSH_for_Windows_7.9p1, LibreSSL 2.6.5
[12:03:41.942] Running script with connection command: ssh -T -D 57077 buildsc-ben bash
[12:03:41.944] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[12:03:42.102] > 
[12:03:42.103] Got some output, clearing connection timeout
[12:03:44.598] > 79a3d1c0295d: running
> 
[12:03:44.636] > Acquiring lock on /home/bliddicott/.vscode-server/bin/5763d909d5f12fe19f215cbfdd
> 29a91c0fa9208a/vscode-remote-lock.bliddicott.5763d909d5f12fe19f215cbfdd29a91c0fa
> 9208a
> \ln /home/bliddicott/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a
> /vscode-remote-lock.bliddicott.5763d909d5f12fe19f215cbfdd29a91c0fa9208a.target /
> home/bliddicott/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/vsco
> de-remote-lock.bliddicott.5763d909d5f12fe19f215cbfdd29a91c0fa9208a
> Found existing installation at /home/bliddicott/.vscode-server/bin/5763d909d5f12
> fe19f215cbfdd29a91c0fa9208a...
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
[12:03:44.660] > Checking server status on port 38707 with wget
> 79a3d1c0295d: start
> sshAuthSock==/tmp/ssh-vmSLNccAy7/agent.3610==
> agentPort==38707==
> osReleaseId==ubuntu==
> arch==x86_64==
> webUiAccessToken====
> tmpDir==/run/user/1001==
> 
[12:03:44.782] > platform==linux==
> 79a3d1c0295d: end
> 
[12:03:44.782] Received install output: 
sshAuthSock==/tmp/ssh-vmSLNccAy7/agent.3610==
agentPort==38707==
osReleaseId==ubuntu==
arch==x86_64==
webUiAccessToken====
tmpDir==/run/user/1001==
platform==linux==

[12:03:44.782] Remote server is listening on port 38707
[12:03:44.783] Parsed server configuration: {"agentPort":38707,"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"/tmp/ssh-vmSLNccAy7/agent.3610","tmpDir":"/run/user/1001","platform":"linux"}
[12:03:44.784] Starting forwarding server. localPort 57080 -> socksPort 57077 -> remotePort 38707
[12:03:44.786] Forwarding server listening on 57080
[12:03:44.786] Waiting for ssh tunnel to be ready
[12:03:44.788] Tunneled remote port 38707 to local port 57080
[12:03:44.788] Resolved "ssh-remote+buildsc-ben" to "127.0.0.1:57080"
[12:03:44.788] Updating $SSH_AUTH_SOCK: ln -f -s "/tmp/ssh-vmSLNccAy7/agent.3610" "/run/user/1001/vscode-ssh-auth-sock-343553890"
[12:03:44.789] Using cwd: vscode-remote://ssh-remote%2Bbuildsc-ben/
[12:03:44.789] Remote extension host environment: {"SSH_AUTH_SOCK":"/run/user/1001/vscode-ssh-auth-sock-343553890"}
[12:03:44.790] [Forwarding server 57080] Got connection 0
[12:03:44.798] ------




[12:03:44.813] [Forwarding server 57080] Got connection 1
[12:03:44.814] [Forwarding server 57080] Got connection 2
[12:06:44.677] > 


```

**Log from Log (Window):**

```
[2020-06-02 12:03:55.130] [renderer1] [error] [remote-connection][Management   ][c75b4…][initial][127.0.0.1:57080] the handshake took longer than 10 seconds. Error:
[2020-06-02 12:03:55.130] [renderer1] [error] Error: handshake timeout
    at file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1826:655
[2020-06-02 12:03:55.131] [renderer1] [error] [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
[2020-06-02 12:03:55.131] [renderer1] [error] Error: handshake timeout
    at file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1826:655
[2020-06-02 12:03:55.215] [renderer1] [error] Unable to read file 'vscode-remote://ssh-remote+buildsc-ben/home/bliddicott/workdir/sonicosv/.vscode/settings.json' (Error: handshake timeout): Error: Unable to read file 'vscode-remote://ssh-remote+buildsc-ben/home/bliddicott/workdir/sonicosv/.vscode/settings.json' (Error: handshake timeout)
    at e.doReadAsFileStream (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1666:417)
[2020-06-02 12:03:55.215] [renderer1] [error] Unable to read file 'vscode-remote://ssh-remote+buildsc-ben/home/bliddicott/workdir/sonicosv/.vscode/tasks.json' (Error: handshake timeout): Error: Unable to read file 'vscode-remote://ssh-remote+buildsc-ben/home/bliddicott/workdir/sonicosv/.vscode/tasks.json' (Error: handshake timeout)
    at e.doReadAsFileStream (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1666:417)
[2020-06-02 12:03:55.215] [renderer1] [error] Unable to read file 'vscode-remote://ssh-remote+buildsc-ben/home/bliddicott/workdir/sonicosv/.vscode/launch.json' (Error: handshake timeout): Error: Unable to read file 'vscode-remote://ssh-remote+buildsc-ben/home/bliddicott/workdir/sonicosv/.vscode/launch.json' (Error: handshake timeout)
    at e.doReadAsFileStream (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1666:417)
[2020-06-02 12:03:55.215] [renderer1] [error] Unable to read file 'vscode-remote://ssh-remote+buildsc-ben/home/bliddicott/workdir/sonicosv/.vscode/settings.json' (Error: handshake timeout): Error: Unable to read file 'vscode-remote://ssh-remote+buildsc-ben/home/bliddicott/workdir/sonicosv/.vscode/settings.json' (Error: handshake timeout)
    at e.doReadAsFileStream (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1666:417)
[2020-06-02 12:03:55.215] [renderer1] [error] Unable to read file 'vscode-remote://ssh-remote+buildsc-ben/home/bliddicott/workdir/sonicosv/.vscode/tasks.json' (Error: handshake timeout): Error: Unable to read file 'vscode-remote://ssh-remote+buildsc-ben/home/bliddicott/workdir/sonicosv/.vscode/tasks.json' (Error: handshake timeout)
    at e.doReadAsFileStream (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1666:417)
[2020-06-02 12:03:55.215] [renderer1] [error] Unable to read file 'vscode-remote://ssh-remote+buildsc-ben/home/bliddicott/workdir/sonicosv/.vscode/launch.json' (Error: handshake timeout): Error: Unable to read file 'vscode-remote://ssh-remote+buildsc-ben/home/bliddicott/workdir/sonicosv/.vscode/launch.json' (Error: handshake timeout)
    at e.doReadAsFileStream (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1666:417)
[2020-06-02 12:03:55.248] [renderer1] [error] [remote-connection][ExtensionHost][28147…][initial][127.0.0.1:57080] the handshake took longer than 10 seconds. Error:
[2020-06-02 12:03:55.248] [renderer1] [error] Error: handshake timeout
    at file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1826:655
[2020-06-02 12:03:55.249] [renderer1] [error] [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
[2020-06-02 12:03:55.249] [renderer1] [error] Error: handshake timeout
    at file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1826:655
[2020-06-02 12:03:55.265] [renderer1] [error] handshake timeout: Error: handshake timeout
    at file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1826:655
[2020-06-02 12:03:55.266] [renderer1] [error] Could not fetch environment: Error: Could not fetch environment
    at file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4327:126
```

**Things I have Tried**

Remove .vscode directory on server, reboot.
Install OS updates on server, reboot.
Install OS updates on client, reboot.
Tried to reproduce with vscode-insiders, same issue.

**Comment by benliddicott** [comment]
Server log:

```


*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


IP Address: REDACTED
Extension host agent listening on 38707


[09:38:24] Extension host agent started.
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/bliddicott/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/bootstrap.js:5:80)
    at process.emit (events.js:200:13)
Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/bliddicott/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/bootstrap.js:5:80)
    at process.emit (events.js:200:13)
Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/bliddicott/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/bootstrap.js:5:80)
    at process.emit (events.js:200:13)
Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/bliddicott/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/bootstrap.js:5:80)
    at process.emit (events.js:200:13)
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/bliddicott/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/bootstrap.js:5:80)
    at process.emit (events.js:200:13)
Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/bliddicott/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/bootstrap.js:5:80)
    at process.emit (events.js:200:13)
Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/bliddicott/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/bootstrap.js:5:80)
    at process.emit (events.js:200:13)
Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/bliddicott/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/bootstrap.js:5:80)
    at process.emit (events.js:200:13)
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/bliddicott/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/bootstrap.js:5:80)
    at process.emit (events.js:200:13)
Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/bliddicott/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/bootstrap.js:5:80)
    at process.emit (events.js:200:13)
Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/bliddicott/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/bootstrap.js:5:80)
    at process.emit (events.js:200:13)
Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/bliddicott/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/bootstrap.js:5:80)
    at process.emit (events.js:200:13)

```

**Comment by benliddicott** [comment]
Removed/reinstalled, no change.

**Trace leve logging - Additional error seen**

```
[14:25:03.905] Log Level: 1
[14:25:03.914] remote-ssh@0.51.0
[14:25:03.914] win32 x64
[14:25:03.917] SSH Resolver called for "ssh-remote+buildsc-ben", attempt 1
[14:25:03.917] SSH Resolver called for host: buildsc-ben
[14:25:03.917] Setting up SSH remote "buildsc-ben"
[14:25:03.942] Using commit id "5763d909d5f12fe19f215cbfdd29a91c0fa9208a" and quality "stable" for server
[14:25:03.943] Install and start server if needed
[14:25:06.082] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[14:25:06.084] Got error from ssh: spawn C:\WINDOWS\System32\OpenSSH\ssh.exe ENOENT
[14:25:06.084] The specified path C:\WINDOWS\System32\OpenSSH\ssh.exe is not a valid SSH binary
[14:25:06.084] Checking ssh with "ssh -V"
[14:25:06.149] > OpenSSH_for_Windows_7.9p1, LibreSSL 2.6.5
[14:25:06.152] Running script with connection command: ssh -T -D 57066 buildsc-ben bash
[14:25:06.156] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[14:25:06.294] "install" terminal received data: "[0m[0K"
[14:25:06.295] Got some output, clearing connection timeout
[14:25:08.793] "install" terminal received data: "5ad8107c9732: running[0K[?25l
Acquiring lock on /home/bliddicott/.vscode-server/bin/5763d909d5f12fe19f215cbfd[0Kd
29a91c0fa9208a/vscode-remote-lock.bliddicott.5763d909d5f12fe19f215cbfdd29a91c0f[0Ka
9208a[0K
\ln /home/bliddicott/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208[0Ka
/vscode-remote-lock.bliddicott.5763d909d5f12fe19f215cbfdd29a91c0fa9208a.target [0K/
home/bliddicott/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/vsc[0Ko
de-remote-lock.bliddicott.5763d909d5f12fe19f215cbfdd29a91c0fa9208a[0K
Installing to /home/bliddicott/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a[0K9
1c0fa9208a...[0K
5ad8107c9732%%1%%[0K
Downloading with wget[0K
[0K[?25h"
[14:25:10.982] "install" terminal received data: "Download complete[0K[?25l
5ad8107c9732%%2%%[0K
[0K[?25h"
[14:25:11.860] "install" terminal received data: "WARNING: VS Code Server is running but its logfile is missing. Don't delete the[0K[?25l
VS Code Server manually, run the command 'Uninstall VS Code Server'.[0K
SSH_CONNECTION=10.203.25.253 63848 10.202.9.180 22[0K
LANG=en_US.UTF-8[0K
SSH_AUTH_SOCK=/tmp/ssh-a0fQDsmbxO/agent.11201[0K
XDG_SESSION_ID=237[0K
USER=bliddicott[0K
PWD=/home/bliddicott[0K
HOME=/home/bliddicott[0K
SSH_CLIENT=10.203.25.253 63848 22[0K
MAIL=/var/mail/bliddicott[0K
SHELL=/bin/bash[0K
SHLVL=2[0K
VSCODE_AGENT_FOLDER=/home/bliddicott/.vscode-server[0K
LOGNAME=bliddicott[0K
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus[0K
XDG_RUNTIME_DIR=/run/user/1001[0K
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/u[0Ks
r/local/games[0K
_=/usr/bin/printenv[0K
OLDPWD=/home/bliddicott/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9[0K2
08a[0K
Starting server with command... /home/bliddicott/.vscode-server/bin/5763d909d5f[0K1
2fe19f215cbfdd29a91c0fa9208a/server.sh --host=127.0.0.1 --enable-remote-auto-sh[0Ku
tdown  --port=0 &> "/home/bliddicott/.vscode-server/.5763d909d5f12fe19f215cbfdd[0K2
9a91c0fa9208a.log" < /dev/null[0K
Waiting for server log...[0K
[0K[?25h"
[14:25:12.360] "install" terminal received data: "[?25l
*[0K
* Reminder: You may only use this software with Visual Studio family products,[0K
* as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)[0K
*[0K
[0K
Checking server status on port 43179 with wget[0K
5ad8107c9732: start[0K
sshAuthSock==/tmp/ssh-a0fQDsmbxO/agent.11201==[0K
agentPort==43179==[0K
osReleaseId==ubuntu==[0K
arch==x86_64==[0K
webUiAccessToken====[0K
[0K[?25h"
[14:25:12.506] "install" terminal received data: "tmpDir==/run/user/1001==[0K[?25l
platform==linux==[0K
5ad8107c9732: end[0K
[0K[?25h"
[14:25:12.506] Received install output: 
sshAuthSock==/tmp/ssh-a0fQDsmbxO/agent.11201==
agentPort==43179==
osReleaseId==ubuntu==
arch==x86_64==
webUiAccessToken====
tmpDir==/run/user/1001==
platform==linux==

[14:25:12.507] Remote server is listening on port 43179
[14:25:12.507] Parsed server configuration: {"agentPort":43179,"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"/tmp/ssh-a0fQDsmbxO/agent.11201","tmpDir":"/run/user/1001","platform":"linux"}
[14:25:12.509] Starting forwarding server. localPort 57081 -> socksPort 57066 -> remotePort 43179
[14:25:12.510] Forwarding server listening on 57081
[14:25:12.510] Waiting for ssh tunnel to be ready
[14:25:12.511] Tunneled remote port 43179 to local port 57081
[14:25:12.512] Resolved "ssh-remote+buildsc-ben" to "127.0.0.1:57081"
[14:25:12.512] Updating $SSH_AUTH_SOCK: ln -f -s "/tmp/ssh-a0fQDsmbxO/agent.11201" "/run/user/1001/vscode-ssh-auth-sock-289033920"
[14:25:12.512] Using cwd: vscode-remote://ssh-remote%2Bbuildsc-ben/
[14:25:12.512] Remote extension host environment: {"SSH_AUTH_SOCK":"/run/user/1001/vscode-ssh-auth-sock-289033920"}
[14:25:12.513] [Forwarding server 57081] Got connection 0
[14:25:12.522] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"success","osReleaseId":"ubuntu","arch":"x86_64","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0"},"measures":{"resolveAttempts":1,"retries":1}}
[14:25:12.524] ------




[14:25:12.558] [Forwarding server 57081] Got connection 1
[14:25:12.559] [Forwarding server 57081] Got connection 2
[14:25:16.538] **Unhandled rejection: Error: Unable to write to User Settings because remote.SSH.remotePlatform is not a registered configuration.**
    at e.reject (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5183:839)
    at e.resolveAndValidate (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5186:717)
    at e.doWriteConfiguration (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5181:70)
    at Object.factory (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5180:801)
    at u.consume (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:129:609)
    at file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:129:424
    at new Promise (<anonymous>)
    at u.queue (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:129:348)
    at e.writeConfiguration (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5180:786)
    at C.writeConfigurationValue (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5206:356)
    at file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5194:815
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[14:28:12.388] "install" terminal received data: "[2G"
[14:31:12.386] "install" terminal received data: "[3G"
[14:34:12.417] "install" terminal received data: "[4G"
[14:37:12.378] "install" terminal received data: "[5G"
```


**Console Log**

```
console.ts:137 [Extension Host] (node:25172) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log	@	console.ts:137
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Unable to write to User Settings because remote.SSH.remotePlatform is not a registered configuration.
console.ts:137 [Extension Host] stack trace: Error: Unable to write to User Settings because remote.SSH.remotePlatform is not a registered configuration.
    at e.reject (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5183:839)
    at e.resolveAndValidate (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5186:717)
    at e.doWriteConfiguration (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5181:70)
    at Object.factory (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5180:801)
    at u.consume (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:129:609)
    at file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:129:424
    at new Promise (<anonymous>)
    at u.queue (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:129:348)
    at e.writeConfiguration (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5180:786)
    at C.writeConfigurationValue (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5206:356)
    at file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5194:815
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
log.ts:197   ERR Unable to write to User Settings because remote.SSH.remotePlatform is not a registered configuration.: Error: Unable to write to User Settings because remote.SSH.remotePlatform is not a registered configuration.
    at e.reject (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5183:839)
    at e.resolveAndValidate (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5186:717)
    at e.doWriteConfiguration (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5181:70)
    at Object.factory (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5180:801)
    at u.consume (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:129:609)
    at file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:129:424
    at new Promise (<anonymous>)
    at u.queue (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:129:348)
    at e.writeConfiguration (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5180:786)
    at C.writeConfigurationValue (file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5206:356)
    at file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5194:815
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
log.ts:197   ERR [remote-connection][Management   ][04c22…][initial][127.0.0.1:57081] the handshake took longer than 10 seconds. Error:
log.ts:197   ERR Error: handshake timeout
    at remoteAgentConnection.ts:114
log.ts:197   ERR [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
log.ts:197   ERR Error: handshake timeout
    at remoteAgentConnection.ts:114
notificationsAlerts.ts:40 Failed to connect to the remote extension host server (Error: handshake timeout)
notificationsAlerts.ts:40 Could not fetch remote environment
log.ts:197   ERR handshake timeout: Error: handshake timeout
    at file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1826:655
log.ts:197   ERR Could not fetch environment: Error: Could not fetch environment
    at file:///C:/Users/bliddicott/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4327:126
log.ts:197   ERR [remote-connection][ExtensionHost][4c768…][initial][127.0.0.1:57081] the handshake took longer than 10 seconds. Error:
log.ts:197   ERR Error: handshake timeout
    at remoteAgentConnection.ts:114
log.ts:197   ERR [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
log.ts:197   ERR Error: handshake timeout
    at remoteAgentConnection.ts:114
extensionHostProcessManager.ts:73 Error received from starting extension host
(anonymous)	@	extensionHostProcessManager.ts:73
extensionHostProcessManager.ts:74 Error: handshake timeout
    at remoteAgentConnection.ts:114
﻿
​
```

**Comment by benliddicott** [comment]
Is there anything at all I can do to shed more light on this?

Any way to enable additional logging?

**Comment by benliddicott** [comment]
It occurs to me that there are some strange characters in the logs. 
Comparing to working connections, working connections do not have these characters:

[13:00:31.957] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[13:00:32.090] "SSH Tunnel" terminal received data: "[0m[0K"
[13:00:32.197] "install" terminal command done
[13:00:32.197] Install terminal quit with output: 
[13:00:34.567] "SSH Tunnel" terminal received data: "SSH_AUTH_SOCK=/tmp/ssh-BsmCz0Qy4b/agent.21444[0K[?25l
Connected to SSH Host - Please do not close this terminal[0K
[0K[?25h"


[0m = Normal character attributes
[0K = Clear line right
[?25l =  Hide Cursor (DECTCEM)
[?25h = Show Cursor (DECTCEM)
[3G  = Cursor Character Absolute [column]

**Comment by benliddicott** [comment]
Upgraded to Windows 2004, installed clean user profile, and WSL2.
Same issue, cannot connect to local WSL2 with the same error and symptoms.

Disabled antivirus/network protection solution, and it works again.

If anyone else has this issue, try disabling your antivirus/network protection solution.

**Comment by bamurtaugh** [comment]
Thanks so much for the updates here @benliddicott! Since it looks like the issue was resolved, going to close this thread. But if I'm missing something or you're still experiencing any issues, just let us know, and I'd be happy to reopen or discuss further. Thank you!
