### ISSUE TITLE
Resolver error: The remote host's architecture is not supported

### ISSUE THREAD

**Issue by amirhosseindavoody** [microsoft/vscode-remote-release#3129]
Connecting from Windows10 machine to Linux Machine (OpenSuse).
I am able to connect via PowerShell SSH.

I get the following error when using remote development extension pack in VScode 1.45

```
[09:54:15.327] Log Level: 2
[09:54:15.347] remote-ssh@0.51.0
[09:54:15.347] win32 x64
[09:54:15.352] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a22696e74656c4c696e7578227d", attempt 1
[09:54:15.352] SSH Resolver called for host: Linux
[09:54:15.352] Setting up SSH remote "Linux"
[09:54:15.401] Using commit id "5763d909d5f12fe19f215cbfdd29a91c0fa9208a" and quality "stable" for server
[09:54:15.404] Install and start server if needed
[09:54:16.912] Checking ssh with "ssh -V"
[09:54:17.155] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[09:54:17.159] Running script with connection command: ssh -T -D 49477 Linux bash
[09:54:17.165] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[09:54:17.580] > 
[09:54:17.581] Got some output, clearing connection timeout
[09:54:18.469] > *******************************************************
> Use of this device and the xxxx network are subject to
> security monitoring to protect against security
> vulnerabilities and to confirm xxxx policy compliance.
> *******************************************************
> 
[09:54:18.687] > Password:
[09:54:18.688] Showing password prompt
[09:54:25.277] Got password response
[09:54:25.278] "install" wrote data to terminal: "*************"
[09:54:25.318] > 
> 
[09:54:26.450] > 3c0e78fbd52e: running
> sed: invalid option -- 'E'
> Usage: sed [OPTION]... {script-only-if-no-other-script} [input-file]...
> 
>   -n, --quiet, --silent
>                  suppress automatic printing of pattern space
>   -e script, --expression=script
>                  add the script to the commands to be executed
>   -f script-file, --file=script-file
>                  add the contents of script-file to the commands to be executed
>   --follow-symlinks
>                  follow symlinks when processing in place
>   -i[SUFFIX], --in-place[=SUFFIX]
>                  edit files in place (makes backup if extension supplied)
>   -l N, --line-length=N
>                  specify the desired line-wrap length for the `l' command
>   --posix
>                  disable all GNU extensions.
>   -r, --regexp-extended
>                  use extended regular expressions in the script.
>   -s, --separate
>                  consider files as separate rather than as a single continuous
>                  long stream.
>   -u, --unbuffered
>                  load minimal amounts of data from the input files and flush
>                  the output buffers more often
>       --help     display this help and exit
>       --version  output version information and exit
> 
> If no -e, --expression, -f, or --file option is given, then the first
> non-option argument is taken as the sed script to interpret.  All
> remaining arguments are names of input files; if no input files are
> specified, then the standard input is read.
> 
> E-mail bug reports to: bonzini@gnu.org .
> Be sure to include the word ``sed'' somewhere in the ``Subject:'' field.
> Unsupported architecture:
> 3c0e78fbd52e##27##
> 
[09:54:26.451] Received install output: 3c0e78fbd52e##27##
[09:54:26.452] Unsupported architecture
[09:54:26.452] Resolver error: The remote host's architecture is not supported
[09:54:26.457] ------
```

**Comment by jrlanglois** [comment]
I have a similar situation, though the symptoms are larger due to working with (older) embedded devices. Boiling the errors down, it looks like this remote explorer is trying to use things that just aren't present on the target device/system.

```bash
BusyBox v1.21.1
stderr> -sh: bash: not found
stderr> -sh: function: not found
stderr> sed
stderr> : invalid option -- E
```

**Comment by cgxeiji** [comment]
Facing the same error here, it would be nice to change `-E` to `-r` to support older versions of `sed`. Is there any reason in particular why `-E` is preferred?

**Comment by jrlanglois** [comment]
The crickets on here are loud... All devices I work with are BusyBox based, and this feature would be extraordinarily useful. Context switching to other apps and whatnot to deal with this is obviously not ideal.

**Comment by yt2639** [comment]
Is this resolved tho? I'm still having the same error (sed invalid option -- E).

**Comment by roblourens** [comment]
This will be fixed in the next release of the Remote-SSH Nightly extension, about 12 hours from now.

**Comment by HectorB-2020** [comment]
Well, I have v0.63.0 and it still complains about
`> sed: invalid option -- 'E'`

**Comment by roblourens** [comment]
You will have to uninstall the stable version of the Remote-SSH extension and install the nightly version.

**Comment by yt2639** [comment]
> You will have to uninstall the stable version of the Remote-SSH extension and install the nightly version.

Hi, @roblourens 
I installed the newest nightly version, but there is still an error **Could not establish connection to "myserver".** It seems like there is a minor bracket issue in the code for connecting:

[20:40:19.953] Log Level: 2
[20:40:19.954] remote-ssh-nightly@2021.1.35460
[20:40:19.954] darwin x64
[20:40:19.955] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a224a4855227d", attempt 1
[20:40:19.956] "remote.SSH.useLocalServer": false
[20:40:19.956] "remote.SSH.showLoginTerminal": true
[20:40:19.956] "remote.SSH.remotePlatform": {"myserver":"linux"}
[20:40:19.956] "remote.SSH.sshPath": undefined
[20:40:19.956] "remote.SSH.sshConfigurationFile": undefined
[20:40:19.956] "remote.SSH.useFlock": true
[20:40:19.957] "remote.SSH.lockfilesInTmp": false
[20:40:19.957] "remote.SSH.localServerDownload": auto
[20:40:19.957] "remote.SSH.remoteServerListenOnSocket": false
[20:40:19.957] "remote.SSH.showLoginTerminal": true
[20:40:19.957] SSH Resolver called for host: myserver
[20:40:19.957] Setting up SSH remote "myserver"
[20:40:19.970] Using commit id "ea3859d4ba2f3e577a159bc91e3074c5d85c0523" and quality "stable" for server
[20:40:19.973] Install and start server if needed
[20:40:19.977] Checking ssh with "ssh -V"
[20:40:19.992] > OpenSSH_7.9p1, LibreSSL 2.7.3

[20:40:19.995] Running script with connection command: ssh -T -D 62413 -o ConnectTimeout=30 'myserver' bash
[20:40:33.584] > ba72f521024e: running
[20:40:33.584] Got some output, clearing connection timeout
[20:40:34.872] > bash: line 145: unexpected argument `(' to conditional binary operator
> bash: line 145: syntax error near `(['
> bash: line 145: `			if [[ $version =~ ([[:digit:]]+)\.([[:digit:]]+)(\.([[:digit:]]+))? ]]; then'
[20:40:35.138] "install" terminal command done
[20:40:35.138] Install terminal quit with output: bash: line 145: `			if [[ $version =~ ([[:digit:]]+)\.([[:digit:]]+)(\.([[:digit:]]+))? ]]; then'
[20:40:35.138] Received install output: bash: line 145: `			if [[ $version =~ ([[:digit:]]+)\.([[:digit:]]+)(\.([[:digit:]]+))? ]]; then'
[20:40:35.139] Stopped parsing output early. Remaining text: bash: line 145: `			if [[ $version =~ ([[:digit:]]+)\.([[:digit:]]+)(\.([[:digit:]]+))? ]]; then'
[20:40:35.139] Failed to parse remote port from server output
[20:40:35.143] Resolver error: Error: 
	at Function.Create (/Users/shane/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.35460/out/extension.js:1:64027)
	at Object.t.handleInstallOutput (/Users/shane/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.35460/out/extension.js:1:62766)
	at k (/Users/shane/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.35460/out/extension.js:1:312984)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /Users/shane/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.35460/out/extension.js:1:310870
	at async Object.t.withShowDetailsEvent (/Users/shane/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.35460/out/extension.js:1:405859)
	at async Object.t.resolve (/Users/shane/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.35460/out/extension.js:1:314523)
	at async /Users/shane/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.35460/out/extension.js:127:110333
[20:40:35.149] ------


By the way, I googled previously and found people saying that I need to set **_remote.SSH.useLocalServer: false_** so I did. Not sure if that's also the reason contributing to this error.

Many thanks!

**Comment by HectorB-2020** [comment]
Pardon, how would I take the latest nightly? I still see the official 0.63.0.

**Comment by yt2639** [comment]
> Pardon, how would I take the latest nightly? I still see the official 0.63.0.

@HectorB-2020 
You need to uninstall stable version and install nightly version instead. There is a separate extension in the extension tab called "Remote SSH (nightly)".

**Comment by roblourens** [comment]
@yt2639 I figured if you had such an old version of sed, there would probably be another incompatibility, and it does seem like you also have an old version of bash that doesn't support some syntax in that line. If you want, you could try to help me figure out exactly which syntax it doesn't like. Or which version of bash do you have?

**Comment by connor4312** [comment]
Marking verified with code review and report that this gets it passed this particular error...

**Comment by yt2639** [comment]
> @yt2639 I figured if you had such an old version of sed, there would probably be another incompatibility, and it does seem like you also have an old version of bash that doesn't support some syntax in that line. If you want, you could try to help me figure out exactly which syntax it doesn't like. Or which version of bash do you have?

Hey @roblourens, thanks for getting back to me. So the "sed --version" gives 4.2.2 and "bash --version" gives 4.2.46(2)-release (x86_64-redhat-linux-gnu). More specifically,

```
$ sed --version
sed (GNU sed) 4.2.2
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

```
$ bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

I cannot update them as I'm not a sudo user for the server and I don't think they will want to update as well. So in this case, does that mean I simply cannot use the "Remote - SSH" extension in VS Code?

Thanks!

**Comment by roblourens** [comment]
Yeah, I don't have time to figure out how to work around this, so I can't support it right now, sorry
