### ISSUE TITLE
Closing workspace does not docker-compose stop container

### ISSUE THREAD

**Issue by dmlond** [microsoft/vscode-remote-release#3137]
- VSCode Version: 1.45.1
- Local OS Version: 10.13.6 (17G13035)
- Remote OS Version: same
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. open folder configured for VSCode Remote Container development
2. Save a new workspace
3. Close and Reopen VSCode
4. Open new workspace
5. let it start the container
6. close workspace without closing VSCode
7. launch local terminal
8. cd $folder_path
9. docker-compose ps a few times and see that docker containers remain running in the background

I think I would expect closing the workspace to docker-compose stop the same way that exiting VSCode does.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: NA

**Comment by dmlond** [comment]
actually, it does not appear that VSCode Remote Container development is compatible with workspaces at all. I cannot close VSCode and reopen it, then open the workspace and then 'Reopen in Container'. It just silently ignores that request, and I cannot figure out where there is output to say why it is failing.

**Comment by chrmarti** [comment]
Could you check the log (`F1` > `Remote-Containers: Show Log`) and the dev console (`Help` > `Toggle Developer Tools`).

**Comment by dmlond** [comment]
Here is the Dev Containers log
```
[0 ms] Start: Resolving remote
[3 ms] Setting up container for folder or workspace: /Users/londo003/projects/Finance/departmental-routing

[16 ms] Start: Check Docker is running
[17 ms] Start: Run: docker info
[226 ms] Stop (209 ms): Run: docker info
[227 ms] Stop (211 ms): Check Docker is running
[228 ms] Start: Run: docker-compose version --short
[1692 ms] Stop (1464 ms): Run: docker-compose version --short
[1693 ms] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=departmental-routing --filter label=com.docker.compose.service=server
[1811 ms] Stop (118 ms): Run: docker ps -q -a --filter label=com.docker.compose.project=departmental-routing --filter label=com.docker.compose.service=server
[1812 ms] Start: Run: docker inspect --type container fd17fabcdad0
[2043 ms] Stop (231 ms): Run: docker inspect --type container fd17fabcdad0
[2045 ms] Start: Inspecting container
[2045 ms] Start: Run: docker inspect --type container fd17fabcdad022904561b5156239a4341aaf35bf6003f3cace227897abfd48fd
[2165 ms] Stop (120 ms): Run: docker inspect --type container fd17fabcdad022904561b5156239a4341aaf35bf6003f3cace227897abfd48fd
[2165 ms] Stop (120 ms): Inspecting container
[2166 ms] Start: Run: docker exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=234eb621-c0c2-4d5e-a05b-4e3125378cd11591634372839 fd17fabcdad022904561b5156239a4341aaf35bf6003f3cace227897abfd48fd /bin/sh
[2176 ms] Start: Run in container: uname -m
[2744 ms] x86_64
[2744 ms] 
[2744 ms] Stop (568 ms): Run in container: uname -m
[2745 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[2819 ms] PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[2820 ms] 
[2820 ms] Stop (75 ms): Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[2820 ms] Start: Run in container: cat /etc/passwd
[2829 ms] Stop (9 ms): Run in container: cat /etc/passwd
[2831 ms] Start: Setup shutdown monitor
[2836 ms] Forking shutdown monitor: /Users/londo003/.vscode/extensions/ms-vscode-remote.remote-containers-0.117.1/dist/shutdownMonitorProcess /var/folders/_3/sh_56h697lv46n6ky8k67d7w0000gn/T/vscode-remote-containers-0e17d2ac49d3d42f638151838e8f6282dd437f1d.sock dockerCompose Trace /Users/londo003/Library/Application Support/Code/logs/20200608T123931/exthost1/ms-vscode-remote.remote-containers
[2846 ms] Stop (15 ms): Setup shutdown monitor
[2847 ms] Start: Run in container: test -d /root/.vscode-server
[2856 ms] 
[2856 ms] 
[2856 ms] Stop (9 ms): Run in container: test -d /root/.vscode-server
[2856 ms] Start: Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[2910 ms] 
[2910 ms] 
[2910 ms] Exit code 2
[2910 ms] Stop (54 ms): Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[2911 ms] Start: Run in container: test -d /root/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a
[2943 ms] 
[2943 ms] 
[2943 ms] Stop (32 ms): Run in container: test -d /root/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a
[2943 ms] Start: Launching Remote-Containers helper.
[2944 ms] Stop (1 ms): Launching Remote-Containers helper.
[2945 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-10b84cbb0a0fdbcfb790295a29c06099b60fc9ea.js' >/tmp/vscode-remote-containers-10b84cbb0a0fdbcfb790295a29c06099b60fc9ea.js
[2955 ms] 
[2955 ms] 
[2955 ms] Stop (10 ms): Run in container: cat <<'EOF-/tmp/vscode-remote-containers-10b84cbb0a0fdbcfb790295a29c06099b60fc9ea.js' >/tmp/vscode-remote-containers-10b84cbb0a0fdbcfb790295a29c06099b60fc9ea.js
[2955 ms] Start: Run in container: # Copy .gitconfig
[2961 ms] /root/.gitconfig exists
[2961 ms] 
[2961 ms] Stop (6 ms): Run in container: # Copy .gitconfig
[2961 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-10b84cbb0a0fdbcfb790295a29c06099b60fc9ea.js' >/tmp/vscode-remote-containers-server-10b84cbb0a0fdbcfb790295a29c06099b60fc9ea.js
[2977 ms] 
[2977 ms] 
[2977 ms] Stop (16 ms): Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-10b84cbb0a0fdbcfb790295a29c06099b60fc9ea.js' >/tmp/vscode-remote-containers-server-10b84cbb0a0fdbcfb790295a29c06099b60fc9ea.js
[2977 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --global credential.helper '!f() { /root/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/node /tmp/vscode-remote-containers-10b84cbb0a0fdbcfb790295a29c06099b60fc9ea.js $*; }; f' || true
[3060 ms] 
[3060 ms] 
[3060 ms] Stop (83 ms): Run in container: command -v git >/dev/null 2>&1 && git config --global credential.helper '!f() { /root/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/node /tmp/vscode-remote-containers-10b84cbb0a0fdbcfb790295a29c06099b60fc9ea.js $*; }; f' || true
[3060 ms] Start: Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.installExtensionsMarker' ; } 2> /dev/null
[3077 ms] 
[3077 ms] 
[3077 ms] Exit code 2
[3077 ms] Stop (17 ms): Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.installExtensionsMarker' ; } 2> /dev/null
[3079 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink -f /proc/$pid/cwd ; xargs -0 < /proc/$pid/environ ; xargs -0 < /proc/$pid/cmdline ; } ; echo ; done 2>/dev/null
[3158 ms] Shutdown monitor: [0 ms] Starting monitor process...
[3176 ms] Shutdown monitor: [67 ms] Received message: [{"type":"configure","sequence":0,"options":{"cwd":"/Users/londo003/projects/Finance/departmental-routing","env":{"ELECTRON_RUN_AS_NODE":"1","TMPDIR":"/var/folders/_3/sh_56h697lv46n6ky8k67d7w0000gn/T/","__CF_USER_TEXT_ENCODING":"0x1F5:0x0:0x0","SHELL":"/bin/bash","HOME":"/Users/londo003","Apple_PubSub_Socket_Render":"/private/tmp/com.apple.launchd.anS3rhMAJ2/Render","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.f9Y50aXsfD/Listeners","PATH":"/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/londo003/.opam/system/bin:/usr/local/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Ballerina/ballerina-1.0.4/bin:/usr/local/bin:/usr/local/oracle:/usr/local/go/bin","LOGNAME":"londo003","XPC_SERVICE_NAME":"com.microsoft.VSCode.194960","USER":"londo003","XPC_FLAGS":"0x0","VSCODE_NLS_CONFIG":"{\"locale\":\"en-us\",\"availableLanguages\":{},\"_languagePackSupport\":true}","VSCODE_NODE_CACHED_DATA_DIR":"/Users/londo003/Library/Application Support/Code/CachedData/5763d909d5f12fe19f215cbfdd29a91c0fa9208a","VSCODE_LOGS":"/Users/londo003/Library/Application Support/Code/logs/20200608T123931","VSCODE_IPC_HOOK":"/Users/londo003/Library/Application Support/Code/1.45.1-main.sock","VSCODE_PID":"69609","CAML_LD_LIBRARY_PATH":"/Users/londo003/.opam/system/lib/stublibs:/usr/local/lib/ocaml/stublibs","GITLAB_SSH_KEY":"/Users/londo003/.ssh/git_deploy_key","MANPATH":":/Users/londo003/.opam/system/man","NLS_LANG":"AMERICAN_AMERICA.UTF8","OCAML_TOPLEVEL_PATH":"/Users/londo003/.opam/system/lib/toplevel","OCI_DIR":"/usr/local/oracle","OPAMUTF8MSGS":"1","ORACLE_HOME":"/usr/local/oracle","PERL5LIB":"/Users/londo003/.opam/system/lib/perl5:","PWD":"/","SHLVL":"1","SQLPATH":"/usr/local/oracle","TNS_ADMIN":"/usr/local/oracle/admin/","_":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","AMD_ENTRYPOINT":"vs/workbench/services/extensions/node/extensionHostProcess","PIPE_LOGGING":"true","VERBOSE_LOGGING":"true","VSCODE_IPC_HOOK_EXTHOST":"/var/folders/_3/sh_56h697lv46n6ky8k67d7w0000gn/T/vscode-ipc-e15ff5e3-57be-4dde-911d-4ecb83f18c8a.sock","VSCODE_HANDLES_UNCAUGHT_ERRORS":"true","VSCODE_LOG_STACK":"false","APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL":"true"},"containerId":"fd17fabcdad022904561b5156239a4341aaf35bf6003f3cace227897abfd48fd","user":"root","sessionId":"234eb621-c0c2-4d5e-a05b-4e3125378cd11591634372839","projectName":"departmental-routing","composeFiles":["/Users/londo003/projects/Finance/departmental-routing/docker-compose.yml","/Users/londo003/projects/Finance/departmental-routing/.devcontainer/docker-compose.yml"],"runServices":["server","webpacker","db"],"logLevel":1,"delay":10000}}]
[3781 ms] Stop (702 ms): Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink -f /proc/$pid/cwd ; xargs -0 < /proc/$pid/environ ; xargs -0 < /proc/$pid/cmdline ; } ; echo ; done 2>/dev/null
[3782 ms] Extension host agent is already running.
[3782 ms] Start: Run in container: cat /root/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/.devport 2>/dev/null
[3827 ms] 41217
[3827 ms] 
[3827 ms] Stop (45 ms): Run in container: cat /root/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/.devport 2>/dev/null
[3829 ms] Forwarding local port 61142 to container port 41217
[3833 ms] 

------------------------
Published Ports:
3000/tcp -> 0.0.0.0:3000
------------------------

[3835 ms] Stop (3835 ms): Resolving remote
[3870 ms] Start: Run: docker exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=234eb621-c0c2-4d5e-a05b-4e3125378cd11591634372839 fd17fabcdad022904561b5156239a4341aaf35bf6003f3cace227897abfd48fd /root/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/node -e 
[3878 ms] Start: Run: docker exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=234eb621-c0c2-4d5e-a05b-4e3125378cd11591634372839 fd17fabcdad022904561b5156239a4341aaf35bf6003f3cace227897abfd48fd /root/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/node -e 
[4697 ms] Remote-Containers server terminated (code: 126, signal: null).
[4766 ms] Stop (888 ms): Run: docker exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=234eb621-c0c2-4d5e-a05b-4e3125378cd11591634372839 fd17fabcdad022904561b5156239a4341aaf35bf6003f3cace227897abfd48fd /root/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/node -e 
[4824 ms] Stop (954 ms): Run: docker exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=234eb621-c0c2-4d5e-a05b-4e3125378cd11591634372839 fd17fabcdad022904561b5156239a4341aaf35bf6003f3cace227897abfd48fd /root/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/node -e 
[5119 ms] Stop (2953 ms): Run: docker exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=234eb621-c0c2-4d5e-a05b-4e3125378cd11591634372839 fd17fabcdad022904561b5156239a4341aaf35bf6003f3cace227897abfd48fd /bin/sh
[34291 ms] Shutdown monitor: [31181 ms] Received message: [{"type":"configure","sequence":1,"options":{"cwd":"/Users/londo003/projects/Finance/departmental-routing","env":{"ELECTRON_RUN_AS_NODE":"1","TMPDIR":"/var/folders/_3/sh_56h697lv46n6ky8k67d7w0000gn/T/","__CF_USER_TEXT_ENCODING":"0x1F5:0x0:0x0","SHELL":"/bin/bash","HOME":"/Users/londo003","Apple_PubSub_Socket_Render":"/private/tmp/com.apple.launchd.anS3rhMAJ2/Render","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.f9Y50aXsfD/Listeners","PATH":"/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/londo003/.opam/system/bin:/usr/local/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Ballerina/ballerina-1.0.4/bin:/usr/local/bin:/usr/local/oracle:/usr/local/go/bin","LOGNAME":"londo003","XPC_SERVICE_NAME":"com.microsoft.VSCode.194960","USER":"londo003","XPC_FLAGS":"0x0","VSCODE_NLS_CONFIG":"{\"locale\":\"en-us\",\"availableLanguages\":{},\"_languagePackSupport\":true}","VSCODE_NODE_CACHED_DATA_DIR":"/Users/londo003/Library/Application Support/Code/CachedData/5763d909d5f12fe19f215cbfdd29a91c0fa9208a","VSCODE_LOGS":"/Users/londo003/Library/Application Support/Code/logs/20200608T123931","VSCODE_IPC_HOOK":"/Users/londo003/Library/Application Support/Code/1.45.1-main.sock","VSCODE_PID":"69609","CAML_LD_LIBRARY_PATH":"/Users/londo003/.opam/system/lib/stublibs:/usr/local/lib/ocaml/stublibs","GITLAB_SSH_KEY":"/Users/londo003/.ssh/git_deploy_key","MANPATH":":/Users/londo003/.opam/system/man","NLS_LANG":"AMERICAN_AMERICA.UTF8","OCAML_TOPLEVEL_PATH":"/Users/londo003/.opam/system/lib/toplevel","OCI_DIR":"/usr/local/oracle","OPAMUTF8MSGS":"1","ORACLE_HOME":"/usr/local/oracle","PERL5LIB":"/Users/londo003/.opam/system/lib/perl5:","PWD":"/","SHLVL":"1","SQLPATH":"/usr/local/oracle","TNS_ADMIN":"/usr/local/oracle/admin/","_":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","AMD_ENTRYPOINT":"vs/workbench/services/extensions/node/extensionHostProcess","PIPE_LOGGING":"true","VERBOSE_LOGGING":"true","VSCODE_IPC_HOOK_EXTHOST":"/var/folders/_3/sh_56h697lv46n6ky8k67d7w0000gn/T/vscode-ipc-e15ff5e3-57be-4dde-911d-4ecb83f18c8a.sock","VSCODE_HANDLES_UNCAUGHT_ERRORS":"true","VSCODE_LOG_STACK":"false","APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL":"true"},"containerId":"fd17fabcdad022904561b5156239a4341aaf35bf6003f3cace227897abfd48fd","user":"root","sessionId":"234eb621-c0c2-4d5e-a05b-4e3125378cd11591634372839","projectName":"departmental-routing","composeFiles":["/Users/londo003/projects/Finance/departmental-routing/docker-compose.yml","/Users/londo003/projects/Finance/departmental-routing/.devcontainer/docker-compose.yml"],"runServices":["server","webpacker","db"],"logLevel":1,"delay":10000}}]
[94299 ms] Shutdown monitor: [91190 ms] Received message: []
[154307 ms] Shutdown monitor: [151198 ms] Received message: []
[214309 ms] Shutdown monitor: [211202 ms] Received message: []
[274312 ms] Shutdown monitor: [271205 ms] Received message: []
```

**Comment by dmlond** [comment]
Here is the Console output from Help: Toggle Developer Tools
```
2/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:259 [Extension Host] (node:69668) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:259
2/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:259 [Extension Host] Error: Unexpected SIGPIPE	at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap.js:5:80)	at process.emit (events.js:203:13)
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:259
2/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:259 [Extension Host] Port forwarding terminated with code 126 and signal null.
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:259
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1642   ERR [remote-connection] The time limit has been reached for a connection. Error:
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1642   ERR Error: Time limit reached
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1835
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1642   ERR [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1642   ERR Error: Time limit reached
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1835
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2876 Failed to connect to the remote extension host server (Error: Time limit reached)
onDidChangeNotification @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2876
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2876 Could not fetch remote environment
onDidChangeNotification @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2876
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1642   ERR Unable to read file 'vscode-remote://dev-container+2f55736572732f6c6f6e646f3030332f70726f6a656374732f46696e616e63652f6465706172746d656e74616c2d726f7574696e67/workspace/.vscode/settings.json' (Error: Time limit reached): Error: Unable to read file 'vscode-remote://dev-container+2f55736572732f6c6f6e646f3030332f70726f6a656374732f46696e616e63652f6465706172746d656e74616c2d726f7574696e67/workspace/.vscode/settings.json' (Error: Time limit reached)
    at e.doReadAsFileStream (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1666:417)
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1642   ERR Unable to read file 'vscode-remote://dev-container+2f55736572732f6c6f6e646f3030332f70726f6a656374732f46696e616e63652f6465706172746d656e74616c2d726f7574696e67/workspace/.vscode/tasks.json' (Error: Time limit reached): Error: Unable to read file 'vscode-remote://dev-container+2f55736572732f6c6f6e646f3030332f70726f6a656374732f46696e616e63652f6465706172746d656e74616c2d726f7574696e67/workspace/.vscode/tasks.json' (Error: Time limit reached)
    at e.doReadAsFileStream (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1666:417)
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1642   ERR Unable to read file 'vscode-remote://dev-container+2f55736572732f6c6f6e646f3030332f70726f6a656374732f46696e616e63652f6465706172746d656e74616c2d726f7574696e67/workspace/.vscode/launch.json' (Error: Time limit reached): Error: Unable to read file 'vscode-remote://dev-container+2f55736572732f6c6f6e646f3030332f70726f6a656374732f46696e616e63652f6465706172746d656e74616c2d726f7574696e67/workspace/.vscode/launch.json' (Error: Time limit reached)
    at e.doReadAsFileStream (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1666:417)
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1642   ERR Unable to read file 'vscode-remote://dev-container+2f55736572732f6c6f6e646f3030332f70726f6a656374732f46696e616e63652f6465706172746d656e74616c2d726f7574696e67/workspace/.vscode/settings.json' (Error: Time limit reached): Error: Unable to read file 'vscode-remote://dev-container+2f55736572732f6c6f6e646f3030332f70726f6a656374732f46696e616e63652f6465706172746d656e74616c2d726f7574696e67/workspace/.vscode/settings.json' (Error: Time limit reached)
    at e.doReadAsFileStream (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1666:417)
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1642   ERR Unable to read file 'vscode-remote://dev-container+2f55736572732f6c6f6e646f3030332f70726f6a656374732f46696e616e63652f6465706172746d656e74616c2d726f7574696e67/workspace/.vscode/tasks.json' (Error: Time limit reached): Error: Unable to read file 'vscode-remote://dev-container+2f55736572732f6c6f6e646f3030332f70726f6a656374732f46696e616e63652f6465706172746d656e74616c2d726f7574696e67/workspace/.vscode/tasks.json' (Error: Time limit reached)
    at e.doReadAsFileStream (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1666:417)
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1642   ERR Unable to read file 'vscode-remote://dev-container+2f55736572732f6c6f6e646f3030332f70726f6a656374732f46696e616e63652f6465706172746d656e74616c2d726f7574696e67/workspace/.vscode/launch.json' (Error: Time limit reached): Error: Unable to read file 'vscode-remote://dev-container+2f55736572732f6c6f6e646f3030332f70726f6a656374732f46696e616e63652f6465706172746d656e74616c2d726f7574696e67/workspace/.vscode/launch.json' (Error: Time limit reached)
    at e.doReadAsFileStream (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1666:417)
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1642   ERR Time limit reached: Error: Time limit reached
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1835:292
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1642   ERR Could not fetch environment: Error: Could not fetch environment
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4327:126
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1642   ERR Time limit reached: Error: Time limit reached
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1835:292
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1642   ERR [remote-connection] The time limit has been reached for a connection. Error:
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1642   ERR Error: Time limit reached
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1835
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1642   ERR [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1642   ERR Error: Time limit reached
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1835
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4034 Error received from starting extension host
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4034
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4034 Error: Time limit reached
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1835
(anonymous) @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4034
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4512 Overwriting grammar scope name to file mapping for scope source.ruby.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/ruby/syntaxes/ruby.tmLanguage.json.
New grammar file: file:///Users/londo003/.vscode/extensions/wingrunr21.vscode-ruby-0.27.0/syntaxes/ruby.cson.json
register @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4512
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1642   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
```

**Comment by dmlond** [comment]
This is after I created a workspace in the root of the application dir which is mounted to /workspace, closed, and reopoed VSCode. It seems to try to launch the remote container, but hangs.

**Comment by chrmarti** [comment]
Could you append the workspace file?

**Comment by PavelSosin-320** [comment]
@chrmarti Hm, what is restart policy of dev container? Docker engine can restart the container even if it exited with code (0). :(

**Comment by chrmarti** [comment]
@dmlond If the only thing you do is `File` > `Close Workspace`, the window reloads connected to the container without any folder open. Try `File` > `Close Remote Connection`.

**Comment by chrmarti** [comment]
@PavelSosin-320 The restart policy is controlled with the `docker-compose.yml`.
