### ISSUE TITLE
can't have multiple users to use vscode on a remote server

### ISSUE THREAD

**Issue by DH0000000001** [microsoft/vscode-remote-release#3138]
- VSCode Version: 1.45.1 
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:
1. install remote-ssh 0.51.0
2. connect to host 
    config_file
     Host hostname1
        HostName hostname1
        User user1
        Port port1
(it works fine!)
3. when others want to use the same remote server.  it fails.
    connect to host
    config_file
     Host hostname1
        HostName hostname1
        User user2
        Port port1
(ssh -p port1 user2@hostname1: Permission denied (publickey,password)
.... 
Permission denied, please try again.
"install" wrote data to terminal: "***"
the process tried to write to a nonexistent pipe.
Resolver error: The process tried to write to a nonexistent pipe)

4. As a result, in the dir user1's "$home/" there is a ".vscode-server" folder  

can't have multiple users to use vscode on a remote server.  

Any help would be greatly appreciated.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
Are you sure User2 has access to this machine? And are you saying that you get this error when actually running an ssh command in an external terminal? `(ssh -p port1 user2@hostname1: Permission denied (publickey,password)`

**Comment by DH0000000001** [comment]
i am sure user2 has access to the server. 
i can connect to the server with ssh -p port1 user1@hostname1 and ssh -p port1 user2@hostname1  in the Command Prompt.
when i run ssh -p port1 user1@hostname1 from vsCode Remote-SSH, it works, but running ssh -p port1 user2@hostname1 fails.  also i can't even connect to the remote server with ssh -p port1 user2@hostname1 in the second machine.
Strange! what am i missing.

**Comment by roblourens** [comment]
Could you share the full log from the "Remote - SSH" output channel when you try to connect with user2?

![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)

**Comment by tobiaspiechowiak** [comment]
Hmm... maybe you need to do that in VSC: 

![image](https://user-images.githubusercontent.com/11884766/97314980-857a9200-1868-11eb-9275-7011f82ce928.png)

**Comment by arenddeboer** [comment]
I think I have the same issue. Both users work with vscode-remoting configured individually. The moment I add a second user it no longer works.

The log:
```

[11:05:00.973] Log Level: 2
[11:05:00.976] remote-ssh@0.55.0
[11:05:00.976] linux x64
[11:05:00.978] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a2276707331312e6172656e646d656469612e6e6c222c2275736572223a226d617070726f7879227d", attempt 1
[11:05:00.979] SSH Resolver called for host: mapproxy@vps11.testmedia.nl
[11:05:00.979] Setting up SSH remote "vps11.testmedia.nl"
[11:05:00.983] Acquiring local install lock: /tmp/vscode-remote-ssh-mapproxy@vps11.testmedia.nl-install.lock
[11:05:00.991] Looking for existing server data file at /home/test/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-mapproxy@vps11.testmedia.nl-d2e414d9e4239a252d1ab117bd7067f125afd80a-0.55.0/data.json
[11:05:00.992] Using commit id "d2e414d9e4239a252d1ab117bd7067f125afd80a" and quality "stable" for server
[11:05:00.994] Install and start server if needed
[11:05:01.000] Checking ssh with "ssh -V"
[11:05:01.009] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020

[11:05:01.013] askpass server listening on /run/user/1000/vscode-ssh-askpass-4116bc8eaf57390d7598a37fa0d4ee49a564658e.sock
[11:05:01.014] Spawning local server with {"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-8835a611e13a18ae69375445e3986b1fd0dd8f29.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","33581","-o","ConnectTimeout=15","mapproxy@vps11.testmedia.nl"],"dataFilePath":"/home/test/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-mapproxy@vps11.testmedia.nl-d2e414d9e4239a252d1ab117bd7067f125afd80a-0.55.0/data.json"}
[11:05:01.014] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-4116bc8eaf57390d7598a37fa0d4ee49a564658e.sock"}
[11:05:01.018] Spawned 35636
[11:05:01.111] > local-server> Spawned ssh: 35644
[11:05:01.114] stderr> OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020
[11:05:01.295] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:00p9B69pbYOWQU49eLb/tokGW7RMkPTiHn4tCrFG3Lc
[11:05:01.509] stderr> mapproxy@vps11.testmedia.nl: Permission denied (publickey).
[11:05:01.511] > local-server> ssh child died, shutting down
[11:05:01.516] Local server exit: 0
[11:05:01.517] Received install output: OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:00p9B69pbYOWQU49eLb/tokGW7RMkPTiHn4tCrFG3Lc
mapproxy@vps11.testmedia.nl: Permission denied (publickey).

[11:05:01.532] Resolver error: Error: Permission denied (publickey).
	at Function.Create (/home/test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:130564)
	at /home/test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:127202
	at Object.t.handleInstallOutput (/home/test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:127485)
	at Object.t.tryInstallWithLocalServer (/home/test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:102339)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /home/test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:104310
	at async Object.t.withShowDetailsEvent (/home/test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:109845)
	at async /home/test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100912
	at async R (/home/test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:97702)
	at async Object.t.resolveWithLocalServer (/home/test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100561)
	at async Object.t.resolve (/home/test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:107840)
	at async /home/test/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:141955
[11:05:01.534] ------




```

**Comment by roblourens** [comment]
@arenddeboer the error just implies that the ssh command failed with "Permission denied". Make sure that you have everything set up correctly, if ssh works from an external terminal then it should work through the extension too.

**Comment by arenddeboer** [comment]
Thanks @roblourens 
It works 100% from the terminal without passwords for both users.
vscode remoting also works if I leave just one entry in /home/user/.ssh/config
So for now I just comment out the other user and vscode no longer complains (even though the error tells us it is the connecting server that rejects the public key as you mentioned)
