### ISSUE TITLE
Cannot Start VSCode on WSL Terminal (WSL1 Debian 10) on Windows 10

### ISSUE THREAD

**Issue by maxhamz** [microsoft/vscode-remote-release#3189]
Dear admin,

I previously tried to reinstall PostgreSQL on my WSL, but for some reason, after successfully reinstall PostgreSQL from "clean slate" and I tried to open VSCode in my WSL with Debian 10, this error log occured:
`[2020-06-15 14:55:49.444] Resolving wsl+Debian, resolveAttempt: 1
[2020-06-15 14:55:50.091] Starting VS Code Server inside WSL (Debian)
[2020-06-15 14:55:50.091] Extension version: 0.44.2, Windows build: 18363. Multi distro support: available. WSL path support: enabled
[2020-06-15 14:55:50.718] Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d Debian -e sh -c "[ -d ~/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2020-06-15 14:55:52.795] Probing result: found
[2020-06-15 14:55:52.795] Server install found in WSL
[2020-06-15 14:55:52.795] Launching C:\WINDOWS\System32\wsl.exe -d Debian sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 5763d909d5f12fe19f215cbfdd29a91c0fa9208a stable .vscode-server 0  ' in c:\Users\sandbox\.vscode\extensions\ms-vscode-remote.remote-wsl-0.44.2}
[2020-06-15 14:55:53.745] Setting up server environment: Looking for /home/sandboxadmin/.vscode-server/server-env-setup. Not found.
[2020-06-15 14:55:54.044] WSL version: 4.4.0-18362-Microsoft Debian
[2020-06-15 14:55:54.044] Starting server: /home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/server.sh  --port=0 --use-host-proxy --fileWatcherPolling=0 
[2020-06-15 14:55:59.030] 
[2020-06-15 14:55:59.030] 
[2020-06-15 14:55:59.030] *
[2020-06-15 14:55:59.030] * Visual Studio Code Server
[2020-06-15 14:55:59.030] *
[2020-06-15 14:55:59.030] * Reminder: You may only use this software with Visual Studio family products,
[2020-06-15 14:55:59.030] * as described in the license https://aka.ms/vscode-remote/license
[2020-06-15 14:55:59.030] *
[2020-06-15 14:55:59.030] 
[2020-06-15 14:55:59.030] 
[2020-06-15 14:55:59.330] (node:17) UnhandledPromiseRejectionWarning: Error: Cannot find module './diagnostic-channel/postgres.sub'
[2020-06-15 14:55:59.330] Require stack:
[2020-06-15 14:55:59.330] - /home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/node_modules/applicationinsights/out/AutoCollection/HttpDependencies.js
[2020-06-15 14:55:59.330] - /home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/node_modules/applicationinsights/out/applicationinsights.js
[2020-06-15 14:55:59.330] - /home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/bootstrap-amd.js
[2020-06-15 14:55:59.330] - /home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/main.js
[2020-06-15 14:55:59.330]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
[2020-06-15 14:55:59.330]     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
[2020-06-15 14:55:59.330]     at Module.require (internal/modules/cjs/loader.js:681:19)
[2020-06-15 14:55:59.330]     at Module.patchedRequire [as require] (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
[2020-06-15 14:55:59.330]     at require (internal/modules/cjs/helpers.js:16:16)
[2020-06-15 14:55:59.331]     at AutoCollectHttpDependencies.enable (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/node_modules/applicationinsights/out/AutoCollection/HttpDependencies.js:27:13)
[2020-06-15 14:55:59.331]     at Function.start (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/node_modules/applicationinsights/out/applicationinsights.js:73:25)
[2020-06-15 14:55:59.331]     at /home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostAgent.js:401:330
[2020-06-15 14:55:59.331]     at new e (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostAgent.js:401:452)
[2020-06-15 14:55:59.331]     at ge._createServices (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostAgent.js:484:222)
[2020-06-15 14:55:59.331]     at ge.start (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostAgent.js:483:190)
[2020-06-15 14:55:59.331]     at Object.<anonymous> (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostAgent.js:498:631)
[2020-06-15 14:55:59.331]     at Function.t._safeInvokeFunction (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:20:548)
[2020-06-15 14:55:59.331]     at Function.t._invokeFactory (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:20:795)
[2020-06-15 14:55:59.331]     at t.complete (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:21:10)
[2020-06-15 14:55:59.331]     at s._onModuleComplete (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:31:623)
[2020-06-15 14:55:59.331]     at s._onModuleComplete (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:31:863)
[2020-06-15 14:55:59.331]     at s._onModuleComplete (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:31:863)
[2020-06-15 14:55:59.331]     at s._onModuleComplete (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:31:863)
[2020-06-15 14:55:59.331]     at s._onModuleComplete (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:31:863)
[2020-06-15 14:55:59.331]     at s._onModuleComplete (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:31:863)
[2020-06-15 14:55:59.331]     at s._resolve (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:31:174)
[2020-06-15 14:55:59.331]     at s.defineModule (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:25:184)
[2020-06-15 14:55:59.331]     at o (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:29:565)
[2020-06-15 14:55:59.331]     at Object.l (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:37:482)
[2020-06-15 14:55:59.331]     at Function.t._safeInvokeFunction (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:20:548)
[2020-06-15 14:55:59.331]     at Function.t._invokeFactory (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:20:795)
[2020-06-15 14:55:59.331]     at t.complete (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:21:10)
[2020-06-15 14:55:59.331]     at s._onModuleComplete (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:31:623)
[2020-06-15 14:55:59.331]     at s._onModuleComplete (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:31:863)
[2020-06-15 14:55:59.331]     at s._resolve (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:31:174)
[2020-06-15 14:55:59.331]     at s.defineModule (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:25:184)
[2020-06-15 14:55:59.331]     at r (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:32:308)
[2020-06-15 14:55:59.331]     at c (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:16:958)
[2020-06-15 14:55:59.331]     at Object.<anonymous> (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostAgent.nls.js:4:1)
[2020-06-15 14:55:59.331]     at t._createAndEvalScript (/home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:17:3)
[2020-06-15 14:55:59.331]     at /home/sandboxadmin/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/loader.js:16:639
[2020-06-15 14:55:59.331]     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
[2020-06-15 14:55:59.331] (node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[2020-06-15 14:55:59.331] (node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2020-06-15 14:55:59.791] VS Code Server for WSL closed unexpectedly.
[2020-06-15 14:55:59.791] For help with startup problems, go to
[2020-06-15 14:55:59.791] https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips
[2020-06-15 14:56:00.160] WSL Daemon exited with code 0`

I am totally confused on what to do to fix this. Thanks again for the help.

Maxwell.

**Comment by bamurtaugh** [comment]
Hey @maxhamz, just to double-check, are you still experiencing this issue?

**Comment by maxhamz** [comment]
I am forced to reinstall debian in this case
