### ISSUE TITLE
Failed to parse remote port from server output on windows

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/vscode-remote-release#3281]
*   VSCode Version:  
    Version: 1.47.0-insider (user setup)  
    Commit: 7923112cdd20575406ec547b55a99c289dd7d7e2  
    Date: 2020-06-29T05:53:43.438Z  
    Electron: 8.3.3  
    Chrome: 80.0.3987.165  
    Node.js: 12.13.0  
    V8: 8.0.426.27-electron.0
*   Local OS Version: Windows\_NT x64 10.0.18363
*   Remote OS Version: Windows\_NT x64 10.0.18363
*   Remote Extension/Connection Type: SSH/Docker/WSL

```
[22:25:26.889] Log Level: 2
[22:25:26.938] remote-ssh-nightly@2020.6.41800
[22:25:26.939] win32 x64
[22:25:27.008] SSH Resolver called for "ssh-remote+dm-sp6", attempt 1
[22:25:27.010] SSH Resolver called for host: dm-sp6
[22:25:27.014] Setting up SSH remote "dm-sp6"
[22:25:27.119] Using commit id "7923112cdd20575406ec547b55a99c289dd7d7e2" and quality "insider" for server
[22:25:27.121] Install and start server if needed
[22:25:27.126] Checking ssh with "ssh -V"
[22:25:27.649] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[22:25:27.650] Remote command length: 7624/8192 characters
// RemoteSSHConfigurationScript omitted in this log //
[22:25:28.092] > 
> 
 
> ]0;C:\WINDOWS\System32\cmd.exe
[22:25:28.093] Got some output, clearing connection timeout
[22:25:28.103] > 
>  
[22:25:31.446] > #< CLIXML
> 
[22:25:31.457] > dc96d3e794c4: running
> 
[22:25:31.791] > Acquiring lock on C:\Users\Jack\.vscode-server-insiders\bin\7923112cdd20575406ec
> 547b55a99c289dd7d7e2\vscode-remote-lock.7923112cdd20575406ec547b55a99c289dd7d7e2
> 
[22:25:31.798] > 
> 
[22:25:31.824] > Looking for existing server in C:\Users\Jack\.vscode-server-insiders\bin\7923112
> cdd20575406ec547b55a99c289dd7d7e2
[22:25:31.852] > 
> vscode-server already installed. Skipping download...
> vscode-server with 7923112cdd20575406ec547b55a99c289dd7d7e2 is already running.
> 
[22:25:31.887] > dc96d3e794c4: start
[22:25:31.894] > 
> sshAuthSock====
> agentPort==50523==
> osReleaseId==windows==
> osVersion==10.0.18363==
> arch==x64==
> platform==windows==
> dc96d3e794c4: end
> Install script is 5660, watching sshd parent 8980
> 
[22:25:31.895] Received install output: 
sshAuthSock====
agentPort==50523==
osReleaseId==windows==
osVersion==10.0.18363==
arch==x64==
platform==windows==

[22:25:31.898] Failed to parse remote port from server output
[22:25:31.910] Resolver error: Error: 
	at Function.Create (c:\Users\Jack\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2020.6.41800\out\extension.js:1:130167)
	at Object.t.handleInstallOutput (c:\Users\Jack\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2020.6.41800\out\extension.js:1:127425)
	at I (c:\Users\Jack\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2020.6.41800\out\extension.js:127:106779)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\Jack\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2020.6.41800\out\extension.js:127:104778
	at async Object.t.withShowDetailsEvent (c:\Users\Jack\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2020.6.41800\out\extension.js:127:110011)
	at async Object.t.resolve (c:\Users\Jack\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2020.6.41800\out\extension.js:127:107964)
	at async c:\Users\Jack\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2020.6.41800\out\extension.js:127:141861
[22:25:31.922] ------
```

**Comment by Jack-Works** [comment]
No bug in remote-ssh stable

**Comment by benliddicott** [comment]
I get this intermittently connecting from England to San Francisco.

I suspect it's related to the 10 second timeout.

**Comment by grkamarnath** [comment]
Same issue i have faced in mac.

About vscode version details:
----------------------------------------------------
Version: 1.49.2
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:23:52.277Z (1 wk ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.5.0
----------------------------------------------------

about Remote:SSH extension 

![image](https://user-images.githubusercontent.com/53405745/94986426-46646400-057c-11eb-971d-c2e71ad0a968.png)

--------------------------------------------------------


Console log 


[13:01:36.823] Log Level: 2
[13:01:36.825] remote-ssh@0.55.0
[13:01:36.826] darwin x64
[13:01:36.828] SSH Resolver called for "ssh-remote+3.238.88.63", attempt 1
[13:01:36.828] SSH Resolver called for host: 3.238.88.63
[13:01:36.828] Setting up SSH remote "3.238.88.63"
[13:01:36.832] Acquiring local install lock: /var/folders/pk/3qr37g510qq47kcq09qfkfmm0000gn/T/vscode-remote-ssh-3.238.88.63-install.lock
[13:01:36.845] Looking for existing server data file at /Users/amar/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-3.238.88.63-e5e9e69aed6e1984f7499b7af85b3d05f9a6883a-0.55.0/data.json
[13:01:36.846] Using commit id "e5e9e69aed6e1984f7499b7af85b3d05f9a6883a" and quality "stable" for server
[13:01:36.848] Install and start server if needed
[13:01:36.853] Checking ssh with "ssh -V"
[13:01:36.862] > OpenSSH_8.1p1, LibreSSL 2.7.3

[13:01:36.866] askpass server listening on /var/folders/pk/3qr37g510qq47kcq09qfkfmm0000gn/T/vscode-ssh-askpass-1d760b8c406aaa76c0080f7af40831b912d82301.sock
[13:01:36.867] Spawning local server with {"ipcHandlePath":"/var/folders/pk/3qr37g510qq47kcq09qfkfmm0000gn/T/vscode-ssh-askpass-2b6c2c4d6165f3ef057c170c120f0fa7a00c40e9.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","49941","-o","ConnectTimeout=15","3.238.88.63"],"dataFilePath":"/Users/amar/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-3.238.88.63-e5e9e69aed6e1984f7499b7af85b3d05f9a6883a-0.55.0/data.json"}
[13:01:36.867] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/amar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/amar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/pk/3qr37g510qq47kcq09qfkfmm0000gn/T/vscode-ssh-askpass-1d760b8c406aaa76c0080f7af40831b912d82301.sock"}
[13:01:36.870] Spawned 2392
[13:01:36.970] > local-server> Spawned ssh: 2393
[13:01:36.974] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[13:01:38.703] stderr> debug1: Server host key: ssh-rsa SHA256:TU6s+sozm5lZ2E0CgBHqc0EKFHcmlJKoXOqbpZXSUFk
[13:01:40.708] stderr> Authenticated to 3.238.88.63 ([3.238.88.63]:64535).
[13:01:41.863] > Error: No command or PTY requested
[13:01:41.865] stderr> Transferred: sent 3444, received 1932 bytes, in 1.2 seconds
[13:01:41.865] stderr> Bytes per second: sent 2979.6, received 1671.5
[13:01:41.865] > local-server> ssh child died, shutting down
[13:01:41.869] Local server exit: 0
[13:01:41.869] Received install output: OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Server host key: ssh-rsa SHA256:TU6s+sozm5lZ2E0CgBHqc0EKFHcmlJKoXOqbpZXSUFk
Authenticated to 3.238.88.63 ([3.238.88.63]:64535).
Error: No command or PTY requested
Transferred: sent 3444, received 1932 bytes, in 1.2 seconds
Bytes per second: sent 2979.6, received 1671.5

[13:01:41.870] Stopped parsing output early. Remaining text: OpenSSH_8.1p1, LibreSSL 2.7.3debug1: Server host key: ssh-rsa SHA256:TU6s+sozm5lZ2E0CgBHqc0EKFHcmlJKoXOqbpZXSUFkAuthenticated to 3.238.88.63 ([3.238.88.63]:64535).Error: No command or PTY requestedTransferred: sent 3444, received 1932 bytes, in 1.2 secondsBytes per second: sent 2979.6, received 1671.5
[13:01:41.870] Failed to parse remote port from server output
[13:01:41.876] Resolver error: Error: 
	at Function.Create (/Users/amar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:130564)
	at Object.t.handleInstallOutput (/Users/amar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:127671)
	at Object.t.tryInstallWithLocalServer (/Users/amar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:102339)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /Users/amar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:104310
	at async Object.t.withShowDetailsEvent (/Users/amar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:109845)
	at async /Users/amar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100912
	at async R (/Users/amar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:97702)
	at async Object.t.resolveWithLocalServer (/Users/amar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100561)
	at async Object.t.resolve (/Users/amar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:107840)
	at async /Users/amar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:141955
[13:01:41.879] ------

**Comment by roblourens** [comment]
@grkamarnath your issue is different and looks like the server is messing with the ssh command sent in. @Jack-Works can you tell me whether this is still an issue for you?

**Comment by Jack-Works** [comment]
No longer having this problem
