### ISSUE TITLE
Error while ssh: Failed to parse remote port from server output

### ISSUE THREAD

**Issue by Serphin** [microsoft/vscode-remote-release#3301]
- VSCode Version: 1.46.1 (user setup)
- Local OS Version: Windows 10
- Remote OS Version: Windows 10
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

Try to connect over ssh to remote, that is what I get every time. Have no idea what is going on.

```
Acquiring lock on ~\.vscode-server\bin\cd9ea6488829f560dc949a8b2fb789f3cdc05f5d\vscode-remote-lock.cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Looking for existing server in ~\.vscode-server\bin\cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
vscode-server already installed. Skipping download...
vscode-server with cd9ea6488829f560dc949a8b2fb789f3cdc05f5d is already running.
2ea04c86463a: start
sshAuthSock====
agentPort==55273==
osReleaseId==windows==
osVersion==10.0.18362==
arch==x64==
platform==windows==
2ea04c86463a: end
Install script is 12148, watching sshd parent 1100


[12:03:47.591] Failed to parse remote port from server output
[12:03:47.600] Resolver error: Error: 
	at Function.Create (~local~\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2020.6.42660\out\extension.js:1:130167)
	at Object.t.handleInstallOutput (~local~\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2020.6.42660\out\extension.js:1:127425)
	at I (~local~\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2020.6.42660\out\extension.js:127:106779)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async ~local~\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2020.6.42660\out\extension.js:127:104778
	at async Object.t.withShowDetailsEvent (~local~\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2020.6.42660\out\extension.js:127:110011)
	at async Object.t.resolve (~local~\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2020.6.42660\out\extension.js:127:107964)
	at async ~local~\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2020.6.42660\out\extension.js:127:141861
[12:03:47.602] > 
[12:03:47.603] ------
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by Serphin** [comment]
I know about duplicates, but no one of them can help me. Or I didn't understand the issue well.

**Comment by seen76** [comment]
same issue here, connecting from macOS to win10 host. it happened after updating to latest, so it is definitely a current issue.

**Comment by existXFx** [comment]
I have same issue when connecting remote Windows host:

#### Remote Host
* Windows 10 Pro Version 1909 18363.900

#### VSCode 
Version: 1.47.0-insider
Commit: 376d9d9d785ccca128fdbb16f001446d0ad64d32
Date: 2020-07-03T10:26:01.724Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0

#### Error output
```
[10:44:53.478] Received install output: 
sshAuthSock====
agentPort==49715==
osReleaseId==windows==
osVersion==10.0.18363==
arch==x64==
platform==windows==

[10:44:53.479] Failed to parse remote port from server output
[10:44:53.483] Resolver error: Error: 
	at Function.Create (/Users/xxx/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2020.6.42660/out/extension.js:1:130167)
	at Object.t.handleInstallOutput (/Users/xxx/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2020.6.42660/out/extension.js:1:127425)
	at I (/Users/xxx/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2020.6.42660/out/extension.js:127:106779)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async /Users/xxx/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2020.6.42660/out/extension.js:127:104778
	at async Object.t.withShowDetailsEvent (/Users/xxx/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2020.6.42660/out/extension.js:127:110011)
	at async Object.t.resolve (/Users/xxx/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2020.6.42660/out/extension.js:127:107964)
	at async /Users/xxx/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2020.6.42660/out/extension.js:127:141861
[10:44:53.485] > Install script is 5524, watching sshd parent 4324
[10:44:53.487] ------
```

**Comment by Chuxel** [comment]
//cc: @roblourens

**Comment by roblourens** [comment]
Sorry, fix on the way. You should be able to switch from the "nightly" extension to the stable one as a workaround.

**Comment by roblourens** [comment]
Fixed in the latest insiders

**Comment by existXFx** [comment]
@roblourens Huge thanks.

**Comment by seen76** [comment]
Thank you. This literally happened with every other update so far for me. Is there a way to prevent it? I am happy to help to write the tests or whatever is required.

**Comment by Serphin** [comment]
@roblourens  Thank you so much!

**Comment by roblourens** [comment]
@seen76 this particular issue was a one-off mistake on my part. If you are having issues in general, please open an issue with the log.

**Comment by chenzhutian** [comment]
same bug here

**Comment by connor4312** [comment]
Was not able to verify due to https://github.com/microsoft/vscode-remote-release/issues/3481
