### ISSUE TITLE
The VS Code Server failed to start

### ISSUE THREAD

**Issue by minghao-wu** [microsoft/vscode-remote-release#3394]
- VSCode Version: 1.47.2
- Local OS Version: Windows 10
- Remote OS Version: CentOS Linux release 7.2.1511 (Core)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to remote server via vscode
2. enter my password

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

The connection worked well yesterday but failed today.

I hide my username, password and proxy in environment variable HTTP_PROXY and HTTPS_PROXY.

Here is the log:
```
[20:05:12.335] Log Level: 2
[20:05:12.339] remote-ssh@0.51.0
[20:05:12.339] win32 x64
[20:05:12.341] SSH Resolver called for "ssh-remote+10.90.91.35", attempt 1
[20:05:12.341] SSH Resolver called for host: 10.90.91.35
[20:05:12.341] Setting up SSH remote "10.90.91.35"
[20:05:12.353] Using commit id "17299e413d5590b14ab0340ea477cdd86ff13daf" and quality "stable" for server
[20:05:12.354] Install and start server if needed
[20:05:13.874] Checking ssh with "ssh -V"
[20:05:13.910] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[20:05:13.912] Running script with connection command: ssh -T -D 58874 10.90.91.35 bash
[20:05:13.914] Terminal shell path: C:\windows\System32\cmd.exe
[20:05:13.989] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\windows\System32\cmd.exe
[20:05:13.989] Got some output, clearing connection timeout
[20:05:14.002] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[20:05:14.016] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[20:05:14.024] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[20:05:14.169] > wuminghao@10.90.91.35's password: 
[20:05:14.169] Showing password prompt
[20:05:18.113] Got password response
[20:05:18.113] "install" wrote data to terminal: "************"
[20:05:18.123] > 
> 
[20:05:18.514] > b93152bf0abb: running
> 
[20:05:18.566] > Acquiring lock on /home/wuminghao/.vscode-server/bin/17299e413d5590b14ab0340ea47
> 7cdd86ff13daf/vscode-remote-lock.wuminghao.17299e413d5590b14ab0340ea477cdd86ff13
> daf
> 
[20:05:18.575] > \ln /home/wuminghao/.vscode-server/bin/17299e413d5590b14ab0340ea477cdd86ff13daf/
> vscode-remote-lock.wuminghao.17299e413d5590b14ab0340ea477cdd86ff13daf.target /ho
> me/wuminghao/.vscode-server/bin/17299e413d5590b14ab0340ea477cdd86ff13daf/vscode-
> remote-lock.wuminghao.17299e413d5590b14ab0340ea477cdd86ff13daf
> 
[20:05:18.586] > Found existing installation at /home/wuminghao/.vscode-server/bin/17299e413d5590
> b14ab0340ea477cdd86ff13daf...
> 
[20:05:18.684] > XDG_SESSION_ID=49895
> SELINUX_ROLE_REQUESTED=
> SHELL=/bin/bash
> SSH_CLIENT=10.70.74.214 58875 22
> SELINUX_USE_CURRENT_RANGE=
> USER=wuminghao
> http_proxy=http://username:password@proxy
> VSCODE_AGENT_FOLDER=/home/wuminghao/.vscode-server
> PATH=/home/wuminghao/anaconda3/bin:/usr/local/bin:/usr/bin  
> MAIL=/var/mail/wuminghao
> PWD=/home/wuminghao
> LANG=en_US.UTF-8
> SELINUX_LEVEL_REQUESTED=
> https_proxy=http://username:password@proxy
> HOME=/home/wuminghao
> SHLVL=2
> LOGNAME=wuminghao
> SSH_CONNECTION=10.70.74.214 58875 10.90.91.35 22
> LESSOPEN=||/usr/bin/lesspipe.sh %s
> XDG_RUNTIME_DIR=/run/user/1016
> _=/usr/bin/printenv
> Starting server with command... /home/wuminghao/.vscode-server/bin/17299e413d559
> 0b14ab0340ea477cdd86ff13daf/server.sh --host=127.0.0.1 --enable-remote-auto-shut
> down  --port=0 &> "/home/wuminghao/.vscode-server/.17299e413d5590b14ab0340ea477c
> dd86ff13daf.log" < /dev/null
[20:05:18.690] > 
> Waiting for server log...
[20:05:18.696] > 
> 
[20:05:19.199] > Waiting for server log...
> 
[20:05:19.705] > Waiting for server log...
> 
[20:05:20.212] > Waiting for server log...
> 
[20:05:20.718] > Waiting for server log...
> 
[20:05:21.226] > Waiting for server log...
> 
[20:05:21.733] > Waiting for server log...
> 
[20:05:22.241] > Waiting for server log...
> 
[20:05:22.742] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
[20:05:22.751] > 
> Server did not start successfully. Full server log at /home/wuminghao/.vscode-se
> rver/.17299e413d5590b14ab0340ea477cdd86ff13daf.log >>>
> 
> 
> *
> * Visual Studio Code Server
> *
> * Reminder: You may only use this software with Visual Studio family products,  
> * as described in the license https://aka.ms/vscode-remote/license
> *
> 
> 
> url.js:340
>       this.auth = decodeURIComponent(rest.slice(0, atSign));
>                   ^
> 
[20:05:22.757] > 
> URIError: URI malformed
>     at decodeURIComponent (<anonymous>)
>     at Url.parse (url.js:340:19)
>     at Object.urlParse [as parse] (url.js:150:13)
>     at Function.Util.makeRequest (/home/wuminghao/.vscode-server/bin/17299e413d5
> 590b14ab0340ea477cdd86ff13daf/node_modules/applicationinsights/out/Library/Util.
> js:266:38)
>     at Timeout.fetchAppId [as _onTimeout] (/home/wuminghao/.vscode-server/bin/17
> 299e413d5590b14ab0340ea477cdd86ff13daf/node_modules/applicationinsights/out/Libr
> ary/CorrelationIdManager.js:33:28)
>     at listOnTimeout (internal/timers.js:531:17)
>     at processTimers (internal/timers.js:475:7)
> <<< End of server log
> b93152bf0abb##32##
> 
[20:05:22.757] Received install output: b93152bf0abb##32##
[20:05:22.757] Resolver error: The VS Code Server failed to start
[20:05:22.759] ------




[20:05:23.172] "install" terminal command done
[20:05:23.172] Install terminal quit with output: 
```

**Comment by roblourens** [comment]
Sorry for the slow response. Is this still an issue? If so please share the format of the proxy variables. You don't have to share the actual value but you can replace the content with different letters so I can see the format.
