### ISSUE TITLE
Remote VSCode server crash with "Unexpected SIGPIPE"

### ISSUE THREAD

**Issue by ronen3** [microsoft/vscode-remote-release#3536]
- VSCode Version: 1.48.0
- Local OS Version: macOS 10.15.6
- Remote OS Version: Ubuntu 20.04.1 LTS
- Remote Extension/Connection Type: SSH

I got up this morning with nothing unusual. Yesterday I worked on the remote host with no problems.

Today tried to connect to the remote host, and my local VS Code was disconnected and attempted numerous reconnections which was odd, because it never happened before.

After a few searches here I uninstalled the VS Code remote server using command "Remote-SSH: Uninstall VS Code Server from Host", then tried to reconnect (which automatically installed the remote server again), but with no success.

I opened the log file `~/.vscode-server/.db40434f562994116e5b21c24015a2e40b2504e6.log` and it says:

```[14:15:30] [127.0.0.1][779c82bf][ManagementConnection] Another client has connected, will shorten the wait for reconnection 5m before disposing...
[14:15:30] [127.0.0.1][005847ad][ManagementConnection] New connection established.
[14:15:30] [127.0.0.1][de0a6908][ExtensionHostConnection] New connection established.
[14:15:30] [127.0.0.1][de0a6908][ExtensionHostConnection] <9336> Launched Extension Host Process.
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/<USER>/.vscode-server/bin/db40434f562994116e5b21c24015a2e40b2504e6/out/bootstrap.js:5:284)
    at process.emit (events.js:200:13)
Error: Unexpected SIGPIPE
    at process.<anonymous> (/home/<USER>/.vscode-server/bin/db40434f562994116e5b21c24015a2e40b2504e6/out/bootstrap.js:5:284)
    at process.emit (events.js:200:13)
[14:16:21] [127.0.0.1][005847ad][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
```

What should I do?

**Comment by ronen3** [comment]
OK, for some odd reason I'm up and running again after executing:
`pkill -f vscode-server`

Found it here in Github somewhere... can someone explain what might have been the issue and how to avoid it next time?
