### ISSUE TITLE
JavaScript language service not starting on Windows remote host

### ISSUE THREAD

**Issue by amcasey** [microsoft/vscode-remote-release#3546]
- VSCode Version: 1.49.0-insider (f694b07825a23005985b470e767a68927a83a553)
- Local OS Version: Windows_NT x64 10.0.19041
- Remote OS Version: Windows_NT x64 10.0.19041
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Open folder on Windows remote host
2. Open .js or .ts file

Expected: Quick info works on identifiers (e.g. on "console" in `console.log("hello")`)
Actual: `The TypeScript language service died 5 times right after it got started`

There's no tsserver log, which usually indicates that the node process completely failed to start (frequently, because of a bad argument).

Does this issue occur when you try this locally?: No (it also works correctly when the remote host is Linux, Mac, or WSL)
Does this issue occur when you try this locally and all extensions are disabled?: The only thing I installed was the SSH Remote extension, so I'm not sure what to disable

**Comment by amcasey** [comment]
This is in the `Log (Window)` output, but a web search suggests it's a generic error without diagnostic value:
```
[2020-08-19 14:32:30.429] [renderer1] [error] Could not create TS service. Service state:{"type":0}: Error: Could not create TS service. Service state:{"type":0}
	at T.service (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\extensions\typescript-language-features\dist\extension.js:1:229890)
	at T.executeImpl (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\extensions\typescript-language-features\dist\extension.js:1:237607)
	at T.execute (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\extensions\typescript-language-features\dist\extension.js:1:237210)
	at c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\extensions\typescript-language-features\dist\extension.js:1:181914
	at S.interuptGetErr (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\extensions\typescript-language-features\dist\extension.js:1:250902)
	at T.interruptGetErr (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\extensions\typescript-language-features\dist\extension.js:1:237692)
	at u.provideHover (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\extensions\typescript-language-features\dist\extension.js:1:181882)
	at c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:724:783
	at c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:52:345
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:52:317)
	at C.provideHover (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:724:754)
	at c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:745:572
	at K._withAdapter (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:742:499)
	at K.$provideHover (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:745:550)
	at m._doInvokeHandler (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:864:202)
	at m._invokeHandler (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:863:901)
	at m._receiveRequest (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:862:494)
	at m._receiveOneMessage (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:861:373)
	at c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:859:476
	at l.fire (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:46:475)
	at v.fire (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:257:381)
	at c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:1050:649
	at l.fire (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:46:475)
	at v.fire (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:257:381)
	at t.PersistentProtocol._receiveMessage (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:261:921)
	at c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:258:926
	at l.fire (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:46:475)
	at p.acceptChunk (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:254:851)
	at c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:254:203
	at Socket.t (c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\out\vs\server\remoteExtensionHostProcess.js:263:499)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
```

**Comment by amcasey** [comment]
Syntax classification (i.e. TextMate), from the `typescript-basics` extension, does appear to be working.

**Comment by amcasey** [comment]
Found this:
```
[Info  - 21:32:29.516] Starting TS Server 
[Info  - 21:32:29.516] Using tsserver from: c:\Users\acasey\.vscode-server-insiders\bin\f694b07825a23005985b470e767a68927a83a553\extensions\node_modules\typescript\lib\tsserver.js
[Info  - 21:32:29.521] <syntax> Log file: c:\Users\acasey\.vscode-server-insiders\data\logs\20200819T143100\exthost2\vscode.typescript-language-features\tsserver-log-KRT8Q4\tsserver.log
[Info  - 21:32:29.521] <syntax> Forking...
[Info  - 21:32:29.533] <syntax> Starting...
[Info  - 21:32:29.537] <semantic> Log file: c:\Users\acasey\.vscode-server-insiders\data\logs\20200819T143100\exthost2\vscode.typescript-language-features\tsserver-log-SAKi3z\tsserver.log
[Info  - 21:32:29.537] <semantic> Forking...
[Info  - 21:32:29.544] <semantic> Starting...
[Error  - 21:32:29.586] TSServer exited with code: 12
```

I'll see if I can figure out what exit code 12 means.

**Comment by amcasey** [comment]
If I run Insider's locally on the server (versus remoting in from the client) and set `typescript.sdk` to the path from the log fragment above, it works correctly, so I think tsserver is fine.

**Comment by amcasey** [comment]
Okay, I dug the remote command out of procmon on the server and running it on its own produces `Starting inspector on 127.0.0.1:9239 failed: address already in use`.  So I guess I just need to figure out why it's starting with `--inspect=9239`.

**Comment by amcasey** [comment]
`--inspect=9239` is added to the command line because the server has the environment variable `TSS_DEBUG` set.  I kind of want to keep that.  It feels like it shouldn't really apply to this process?  Or, failing that, there should be some way to override environment variables in the remote session?

It would also be nice if the node error message were propagated back to the client - that would have made debugging a lot easier.

**Comment by mjbvz** [comment]
Thanks for the investigation @amcasey 

The remote server uses a normal  node instances instead of running node through electron. That is why you see it using `node.exe` although I wouldn't have expected any difference in behavior between the two around ports 

I don't think there is a way to configure the environment variables specifically for in a remote instance (except in VS Code's integrated terminal). Should I just disable TSS_DEBUG in remote cases?

**Comment by amcasey** [comment]
@mjbvz That seems like a sensible option, unless someone internal needs it for debugging the server.  Any chance the extension could also log the stderr output from the node process?

**Comment by mjbvz** [comment]
This environment var only really exists for the typescript team's usage so tell me what you think is best and I can make the change :)

**Comment by amcasey** [comment]
Thanks!  I'll ping the team.

**Comment by amcasey** [comment]
There are at least two votes for "I might need that", so I'd go ahead and add `TSS_DEBUG_REMOTE` (`TSS_REMOTE_DEBUG`?).  Thanks again!

**Comment by mjbvz** [comment]
Ok. Should `TSS_DEBUG_REMOTE` be an alias of `TSS_DEBUG` but only enabled in remote cases?

**Comment by amcasey** [comment]
I'm not sure what "alias" means in this context.  I think that in local scenarios `TSS_DEBUG` should be consumed and `TSS_REMOTE_DEBUG` should be ignored and vice versa in remote scenarios.  (Yes, I switched the order - it works better with `TSS_REMOTE_DEBUG_BRK`.)

**Comment by amcasey** [comment]
Thanks, @mjbvz!
