### ISSUE TITLE
TypeError: Cannot read property when trying to save the ssh finger print

### ISSUE THREAD

**Issue by EmbeddedBacon** [microsoft/vscode-remote-release#3577]
- VSCode Version: 
- Local OS Version: Windows 10
- Remote OS Version: CentOS v7
- Remote Extension/Connection Type: SSH
- remote-ssh-0.51.0

  When attempting to connect to a development machine the using the Remote SSH extension the following messages on the console were seen

`[16:32:01.107] Showing password prompt
[16:32:14.170] Got password response
[16:32:14.172] "install" wrote data to terminal: "******"
[16:32:14.207] > 
> 
[16:32:33.626] > Connection reset by xxx.xxx.193.243 port 22
> 
[16:32:35.271] "install" terminal command done
[16:32:35.271] Install terminal quit with output: Connection reset by xxx.xxx.193.243 port 22
[16:32:35.271] Received install output: Connection reset by xxx.xxx.193.243 port 22
[16:32:35.272] Stopped parsing output early. Remaining text: Connection reset by xxx.xxx.193.243 port 22
[16:32:35.272] Failed to parse remote port from server output
[16:32:35.273] Resolver error:`

So, remove all entries to xxx.xxx.193.243 from the `known_host` file on the Windows machine since I have seen issues with the finger prints don't match due to DNS assignments.  After removing all xxx.xxx.193.243 entries restart VS Code and tried to connect to the development machine the following error is seen.

`[16:58:56.704] > The authenticity of host '__host_name__ (xxx.xxx.193.243)' can't be establis
> hed.
> ECDSA key fingerprint is SHA256:ZhbpLQ9pXvrTVOoGgfMeyzoM/qBDObJTXGS+HkOO+jc.    
> Are you sure you want to continue connecting (yes/no)?
[16:58:56.705] Detected fingerprint confirmation message
[16:58:56.706] Showing fingerprint confirmation dialog
[16:59:06.422] Unhandled rejection: `TypeError: Cannot read property `'value' of undefined
    at c:\Users\__user__\.vscode\extensions\ms-vscode-remote.remote-ssh-0.51.0\out\extension.js:1:99462
    at e.fire (c:\Users\__user__\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:497)
    at f._fireDidAccept (c:\Users\__user__\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:683:649)
    at t.ExtHostQuickOpen.$onDidAccept (c:\Users\__user__\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:681:232)
    at e._doInvokeHandler (c:\Users\__user__\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:752:683)
    at e._invokeHandler (c:\Users\__user__\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:752:375)
    at e._receiveRequest (c:\Users\__user__\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:751:14)
    at e._receiveOneMessage (c:\Users\__user__\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:749:832)
    at c:\Users\__user__\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:748:34
    at e.fire (c:\Users\__user__\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:497)
    at v.fire (c:\Users\__user__\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:206:615)
    at c:\Users\__user__\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:919:744
    at e.fire (c:\Users\__user__\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:497)
    at v.fire (c:\Users\__user__\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:206:615)
    at t.PersistentProtocol._receiveMessage (c:\Users\__user__\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:211:17)
    at c:\Users\__user__\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:208:155
    at e.fire (c:\Users\__user__\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:497)
    at p.acceptChunk (c:\Users\__user__\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:204:129)
    at c:\Users\__user__\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:203:483
    at Socket.t (c:\Users\__user__\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:212:565)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)`

**Comment by roblourens** [comment]
Sorry for the slow response. Is this still an issue?
