### ISSUE TITLE
Can't connect to host

### ISSUE THREAD

**Issue by SlyJonas** [microsoft/vscode-remote-release#3596]
- VSCode Version: 1.48.2 (user setup)
- Local OS Version: Windows 10 Pro x64 2004 19041.450 (Windows_NT x64 10.0.19041)
- Remote OS Version: Linux Ubuntu 18.04
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1. Try connecting to SSH via remote extension by Microsoft

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

[11:34:21.238] Log Level: 2
[11:34:21.252] remote-ssh@0.51.0
[11:34:21.252] win32 x64
[11:34:21.256] SSH Resolver called for "ssh-remote+root", attempt 1
[11:34:21.256] SSH Resolver called for host: root
[11:34:21.257] Setting up SSH remote "root"
[11:34:21.304] Using commit id "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" and quality "stable" for server
[11:34:21.306] Install and start server if needed
[11:34:21.314] Checking ssh with "C:\Users\user\.ssh\config -V"
[11:34:21.321] Got error from ssh: spawn C:\Users\user\.ssh\config ENOENT
[11:34:21.321] The specified path C:\Users\user\.ssh\config is not a valid SSH binary
[11:34:21.322] Checking ssh with "ssh -V"
[11:34:21.558] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
[11:34:21.562] Using SSH config file "C:\Users\user\.ssh\config"
[11:34:21.562] Running script with connection command: ssh -T -D 49732 -F "C:\Users\user\.ssh\config" root bash
[11:34:21.567] Terminal shell path: C:\Windows\System32\cmd.exe
[11:34:22.322] > user@xxx.xxx.xxx.xxx's password:]0;C:\Windows\System32\cmd.exe
[11:34:22.322] Got some output, clearing connection timeout
[11:34:22.323] Showing password prompt
[11:34:30.846] Got password response
[11:34:30.847] "install" wrote data to terminal: "**************"
[11:34:30.872] > 
[11:34:52.542] > ssh_dispatch_run_fatal: Connection to cxx.xxx.xxx.xxx port 22: Connection timed o
> ut
[11:34:52.553] > The process tried to write to a nonexistent pipe.
[11:34:52.838] "install" terminal command done
[11:34:52.839] Install terminal quit with output: The process tried to write to a nonexistent pipe.
[11:34:52.839] Received install output: The process tried to write to a nonexistent pipe.
[11:34:52.840] Resolver error: The process tried to write to a nonexistent pipe
[11:34:52.845] ------

[11:34:53.630] Unhandled rejection: TypeError: Cannot read property 'write' of null
	at IPCTransport.send (c:\Users\user\.vscode\extensions\icrawl.discord-vscode-4.0.0\dist\extension.js:2:104777)
	at IPCTransport.close (c:\Users\user\.vscode\extensions\icrawl.discord-vscode-4.0.0\dist\extension.js:2:104813)
	at RPCClient.destroy (c:\Users\user\.vscode\extensions\icrawl.discord-vscode-4.0.0\dist\extension.js:2:102127)
	at RPCClient.dispose (c:\Users\user\.vscode\extensions\icrawl.discord-vscode-4.0.0\dist\extension.js:2:89241)
	at activate (c:\Users\raycu\.vscode\extensions\icrawl.discord-vscode-4.0.0\dist\extension.js:2:84674)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)

-----------------------------------------------------------
The issue being for some reason it stopped working, yesterday worked fine.

**Comment by SlyJonas** [comment]
Ye my host went for maintenance and left me un noticed I am sorry
