### ISSUE TITLE
Unable to start sample - error: Error: TAR_BAD_ARCHIVE: Unrecognized archive format

### ISSUE THREAD

**Issue by NikiforovAll** [microsoft/vscode-remote-release#3642]
- VSCode Version: 1.48.2
- Remote OS Version: Windows_NT x64 10.0.19041
- Extension version: ms-vscode-remote.remote-containers:v0.134.1

**Context:** I'm trying to open folder located on C drive in a devcontainer.

### Error

```text
[102607 ms] Error: TAR_BAD_ARCHIVE: Unrecognized archive format
        at $.warn (c:\Users\nikiforovall\.vscode\extensions\ms-vscode-remote.remote-containers-0.134.1\dist\extension.js:1:197830)
        at $.warn (c:\Users\nikiforovall\.vscode\extensions\ms-vscode-remote.remote-containers-0.134.1\dist\extension.js:1:301454)
        at $.<anonymous> (c:\Users\nikiforovall\.vscode\extensions\ms-vscode-remote.remote-containers-0.134.1\dist\extension.js:1:165293)
        at $.emit (events.js:208:15)
        at $.[emit] (c:\Users\nikiforovall\.vscode\extensions\ms-vscode-remote.remote-containers-0.134.1\dist\extension.js:1:167753)
        at $.[maybeEnd] (c:\Users\nikiforovall\.vscode\extensions\ms-vscode-remote.remote-containers-0.134.1\dist\extension.js:1:169342)
        at $.[consumeChunk] (c:\Users\nikiforovall\.vscode\extensions\ms-vscode-remote.remote-containers-0.134.1\dist\extension.js:1:169605)
        at $.write (c:\Users\nikiforovall\.vscode\extensions\ms-vscode-remote.remote-containers-0.134.1\dist\extension.js:1:168850)
        at $.end (c:\Users\nikiforovall\.vscode\extensions\ms-vscode-remote.remote-containers-0.134.1\dist\extension.js:1:170030)
        at Socket.onend (_stream_readable.js:682:10)
        at Object.onceWrapper (events.js:291:20)
        at Socket.emit (events.js:208:15)
        at endReadableNT (_stream_readable.js:1168:12)
        at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

**Comment by Chuxel** [comment]
Moving to vscode-remote-release repo.  Could you include the full log so we can see which tar is impacted?  I suspect one of the extensions may have just downloaded incorrectly or there was a bad tar for it in the marketplace.

I've actually never seen this happen - @chrmarti ?

**Comment by NikiforovAll** [comment]
https://gist.github.com/NikiforovAll/9db6086a1176b80f852eafaef56cef0a

**Note:** It works when the container is rebuilt on a second time after I hit "Retry" button in the provided dialog.

**Comment by chrmarti** [comment]
This is the TAR we create on-the-fly in the container to copy the downloaded VSIXs to a local cache folder. The 'untar' happens on the Windows side. Not sure how that tar could fail to unpack.

There are more extensions listed than you have in the devcontainer.json, maybe the others are listed in your user settings?

Does this only happen with this container or with all? What if you install only a single extension?

**Comment by NikiforovAll** [comment]
All of these are from recent .devcontainer file and I don't other extensions that are installed globally. 

The error is reproduced if there are any extensions defined.

Issue is reproduced for `remote-containers.trySample` into ".NET Core".

**Comment by TimVosch** [comment]
I am having the same issue, I removed almost all extensions. I am developing on a windows machine through WSL 2 and Docker Desktop.
The error log, my devcontainer and Dockerfile are shown below (unfold)

I wish I could be of more help but I don't have knowledge about the internal workings, so I hope this can be of use.

Sincerely,

----

**Extensions local**
- [ms-vscode-remote.remote-containers] **Remote - Containers**
- [ms-vscode-remote.remote-ssh] **Remote - SSH**
- [ms-vscode-remote.remote-ssh-edit] **Remote - SSH: Editing Configuration Files**
- [ms-vscode-remote.remote-wsl] **Remote - WSL**
- [loilo.snazzy-light] **Snazzy Lights**

**Extensions container**
- [esbenp.prettier-vscode] **Prettier - Code formatter**

<details>
<summary>.devcontainer/devcontainer.json</summary>

```json
{
	"name": "Node.js & TypeScript",
	"build": {
		"dockerfile": "Dockerfile",
		// Update 'VARIANT' to pick a Node version: 10, 12, 14
		"args": {
			"VARIANT": "14"
		}
	},
	// Set *default* container specific settings.json values on container create.
	"settings": {
		"terminal.integrated.shell.linux": "/bin/bash"
	},
	// Add the IDs of extensions you want installed when the container is created.
	"extensions": [
		"esbenp.prettier-vscode",
	],
	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	"forwardPorts": [
		3000
	]
	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "yarn install",
	// Uncomment to connect as a non-root user. See https://aka.ms/vscode-remote/containers/non-root.
	// "remoteUser": "node"
}
```

</details>

<details>
<summary>.devcontainer/Dockerfile</summary>

```Dockerfile
# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.145.1/containers/typescript-node/.devcontainer/base.Dockerfile

# [Choice] Node.js version: 14, 12, 10
ARG VARIANT="14-buster"
FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:0-${VARIANT}

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment if you want to install an additional version of node using nvm
# ARG EXTRA_NODE_VERSION=10
# RUN su node -c "source /usr/local/share/nvm/nvm.sh && nvm install ${EXTRA_NODE_VERSION}"

# [Optional] Uncomment if you want to install more global node packages
# RUN sudo -u node npm install -g <your-package-list -here>
```

</details>

<details>
<summary>Error log</summary>

```
[5 ms] Remote-Containers 0.145.1 in VS Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a).
[14 ms] Start: Resolving remote
[16 ms] Start: Run: wsl -d Ubuntu -e wslpath -u \\wsl$\Ubuntu\home\timvosch\src\shortcut
[110 ms] Start: Run: wsl -d Ubuntu
[178 ms] Setting up container for folder or workspace: /home/timvosch/src/shortcut

[179 ms] Start: Check Docker is running
[179 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && docker 'info'
[319 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && test '-f' '/home/timvosch/src/shortcut/.devcontainer/devcontainer.json'
[389 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && cat '/home/timvosch/src/shortcut/.devcontainer/devcontainer.json'
[461 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && git 'rev-parse' '--show-toplevel'
[531 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && docker 'ps' '-q' '-a' '--filter' 'label=vsch.local.folder=\\wsl$\Ubuntu\home\timvosch\src\shortcut' '--filter' 'label=vsch.quality=stable'
[603 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && cat '/home/timvosch/src/shortcut/.devcontainer/Dockerfile'
[673 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && docker 'build' '-f' '/home/timvosch/src/shortcut/.devcontainer/Dockerfile' '-t' 'vsc-shortcut-b301921a200fd4000b8eb48121428582' '--build-arg' 'VARIANT=14' '/home/timvosch/src/shortcut/.devcontainer'
Sending build context to Docker daemon   5.12kB
Step 1/2 : ARG VARIANT="14-buster"
Step 2/2 : FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:0-${VARIA
NT}
 ---> bed1d468cebc
Successfully built bed1d468cebc
Successfully tagged vsc-shortcut-b301921a200fd4000b8eb48121428582:latest
[897 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && docker 'inspect' '--type' 'image' 'vsc-shortcut-b301921a200fd4000b8eb48121428582'
[964 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && docker '-v'
[1032 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && docker 'events' '--format' '{{json .}}' '--filter' 'status=start'
[1035 ms] Start: Starting container
[1035 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && docker 'run' '-a' 'STDOUT' '-a' 'STDERR' '--mount' 'type=bind,source=/home/timvosch/src/shortcut,target=/workspaces/shortcut' '-l' 'vsch.quality=stable' '-l' 'vsch.remote.devPort=0' '-l' 'vsch.local.folder=\\wsl$\Ubuntu\home\timvosch\src\shortcut' '--entrypoint' '/bin/sh' 'vsc-shortcut-b301921a200fd4000b8eb48121428582' '-c' 'echo Container started ; trap "exit 0" 15; while sleep 1 & wait $!; do :; done'
Container started
[1393 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && docker 'ps' '-q' '-a' '--filter' 'label=vsch.local.folder=\\wsl$\Ubuntu\home\timvosch\src\shortcut' '--filter' 'label=vsch.quality=stable'
[1460 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && docker 'inspect' '--type' 'container' '29538edfc239'
[1527 ms] Start: Inspecting container
[1527 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && docker 'inspect' '--type' 'container' '29538edfc23919e892c8c8dde6e631b1aebacc54fde31b3ee9fe0cb6283bbffa'
[1595 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && docker 'exec' '-i' '-u' 'root' '-e' 'VSCODE_REMOTE_CONTAINERS_SESSION=37c6c67f-b763-4d25-84e9-792755fbbd271603369422319' '29538edfc23919e892c8c8dde6e631b1aebacc54fde31b3ee9fe0cb6283bbffa' '/bin/sh'
[1598 ms] Start: Run in container: uname -m
[1674 ms] x86_64
[1674 ms] 
[1674 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[1676 ms] PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[1676 ms] 
[1676 ms] Start: Run in container: cat /etc/passwd
[1678 ms] Start: Updating configuration state
[1678 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && cat '/home/timvosch/src/shortcut/.devcontainer/Dockerfile'
[1749 ms] Start: Setup shutdown monitor
[1751 ms] Forking shutdown monitor: c:\Users\Tim van Osch\.vscode\extensions\ms-vscode-remote.remote-containers-0.145.1\dist\shutdownMonitorProcess \\.\pipe\vscode-remote-containers-f9651d9f1c658f65a525e4704c003b76b65208db-sock singleContainer Info c:\Users\Tim van Osch\AppData\Roaming\Code\logs\20201022T141835\exthost1\ms-vscode-remote.remote-containers 1603369422880
[1758 ms] Start: Run in container: test -d /root/.vscode-server
[1760 ms] 
[1760 ms] 
[1760 ms] Exit code 1
[1760 ms] Start: Run in container: test -d /root/.vscode-remote
[1762 ms] 
[1762 ms] 
[1762 ms] Exit code 1
[1762 ms] Start: Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[1765 ms] 
[1765 ms] 
[1765 ms] Start: Run in container: mkdir -p '/root/.vscode-server/data/Machine' && cat >'/root/.vscode-server/data/Machine/settings.json' <<'settingsJSON'
[1767 ms] 
[1767 ms] 
[1768 ms] Start: Run in container: test -d /root/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a
[1769 ms] 
[1769 ms] 
[1769 ms] Exit code 1
[1769 ms] Installing VS Code Server for commit d2e414d9e4239a252d1ab117bd7067f125afd80a
[1769 ms] Start: Run in container: mkdir -p /root/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a_1603369424649
[1771 ms] 
[1771 ms] 
[1785 ms] Start: Run in container: (dd iflag=fullblock bs=8192 count=3928 2>/dev/null; dd iflag=fullblock bs=1759 count=1 2>/dev/null) | tar --no-same-owner -xz --strip-components 1 -C /root/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a_1603369424649
[2413 ms] 
[2413 ms] 
[2413 ms] Start: Run in container: mv -n /root/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a_1603369424649 /root/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a
[2415 ms] 
[2415 ms] 
[2415 ms] Start: Launching Remote-Containers helper.
[2416 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && gpgconf '--list-dir' 'agent-extra-socket'
[2483 ms] Start: Run in container: gpgconf --list-dir agent-socket
[2485 ms] /root/.gnupg/S.gpg-agent
[2485 ms] 
[2485 ms] Start: Run in container: gpgconf --list-dir homedir
[2486 ms] /root/.gnupg
[2486 ms] 
[2486 ms] Start: Run in container: ls '/root/.gnupg/private-keys-v1.d' 2>/dev/null
[2488 ms] 
[2488 ms] 
[2488 ms] Exit code 2
[2488 ms] Start: Run in container: mkdir -p -m 700 '/root/.gnupg'
[2489 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && cat '/home/timvosch/.gitconfig'
[2492 ms] 
[2492 ms] 
[2492 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-2ea912a2fec158c9b6ac0f7dede6c55f8118de05.js' >/tmp/vscode-remote-containers-2ea912a2fec158c9b6ac0f7dede6c55f8118de05.js
[2492 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && gpgconf '--list-dir' 'homedir'
[2494 ms] 
[2494 ms] 
[2494 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-2ea912a2fec158c9b6ac0f7dede6c55f8118de05.js' >/tmp/vscode-remote-containers-server-2ea912a2fec158c9b6ac0f7dede6c55f8118de05.js
[2497 ms] 
[2497 ms] 
[2497 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && docker 'exec' '-i' '-u' 'root' '-e' 'REMOTE_CONTAINERS_SOCKETS=["/root/.gnupg/S.gpg-agent"]' '-e' 'REMOTE_CONTAINERS_IPC=/tmp/vscode-remote-containers-ipc-2ea912a2fec158c9b6ac0f7dede6c55f8118de05.sock' '29538edfc23919e892c8c8dde6e631b1aebacc54fde31b3ee9fe0cb6283bbffa' '/root/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/node' '/tmp/vscode-remote-containers-server-2ea912a2fec158c9b6ac0f7dede6c55f8118de05.js'
[2572 ms] Start: Run in container: # Test for /root/.gitconfig and git
[2575 ms] 
[2575 ms] 
[2575 ms] Start: Run in container: # Copy /home/timvosch/.gitconfig to /root/.gitconfig
[2578 ms] 
[2578 ms] 
[2578 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --global credential.helper '!f() { /root/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/node /tmp/vscode-remote-containers-2ea912a2fec158c9b6ac0f7dede6c55f8118de05.js $*; }; f' || true
[2581 ms] 
[2581 ms] 
[2581 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && cat '/home/timvosch/.ssh/known_hosts'
[2595 ms] Start: Run in container: gpgconf --list-dir homedir
[2597 ms] /root/.gnupg
[2598 ms] 
[2598 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && cat '/home/timvosch/.gnupg/pubring.kbx'
[2654 ms] Start: Run in container: # Test for /root/.ssh/known_hosts and ssh
[2656 ms] 
[2657 ms] 
[2657 ms] Start: Run in container: # Copy /home/timvosch/.ssh/known_hosts to /root/.ssh/known_hosts
[2659 ms] 
[2659 ms] 
[2659 ms] Start: Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.installExtensionsMarker' ; } 2> /dev/null
[2661 ms] 
[2661 ms] 
[2663 ms] Start: Run in container: test -d /root/.vscode-server/extensionsCache && ls /root/.vscode-server/extensionsCache || true
[2665 ms] 
[2665 ms] 
[2666 ms] Start: Run in container: cd /root/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a; export VSCODE_AGENT_FOLDER=/root/.vscode-server; /root/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/server.sh --extensions-download-dir /root/.vscode-server/extensionsCache --install-extension esbenp.prettier-vscode --force
[2673 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && cat '/home/timvosch/.gnupg/trustdb.gpg'
[2744 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && gpg-connect-agent 'updatestartuptty' '/bye'
[3492 ms] Installing extensions...
Installing extension 'esbenp.prettier-vscode' v5.7.1...
Extension 'esbenp.prettier-vscode' v5.7.1 was successfully installed.
[3492 ms] 
[3492 ms] Start: Run in container: ls /root/.vscode-server/extensionsCache || true
[3494 ms] esbenp.prettier-vscode-5.7.1
[3494 ms] 
[3494 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/timvosch/src/shortcut' && docker 'exec' '-i' '-u' 'root' '-w' '/root/.vscode-server' '29538edfc23919e892c8c8dde6e631b1aebacc54fde31b3ee9fe0cb6283bbffa' 'tar' 'c' 'extensionsCache/esbenp.prettier-vscode-5.7.1'
[3567 ms] Error: TAR_BAD_ARCHIVE: Unrecognized archive format
        at B.warn (c:\Users\Tim van Osch\.vscode\extensions\ms-vscode-remote.remote-containers-0.145.1\dist\extension.js:1:234012)
        at B.warn (c:\Users\Tim van Osch\.vscode\extensions\ms-vscode-remote.remote-containers-0.145.1\dist\extension.js:1:603809)
        at B.<anonymous> (c:\Users\Tim van Osch\.vscode\extensions\ms-vscode-remote.remote-containers-0.145.1\dist\extension.js:1:182395)
        at B.emit (events.js:228:7)
        at B.[emit] (c:\Users\Tim van Osch\.vscode\extensions\ms-vscode-remote.remote-containers-0.145.1\dist\extension.js:1:184855)
        at B.[maybeEnd] (c:\Users\Tim van Osch\.vscode\extensions\ms-vscode-remote.remote-containers-0.145.1\dist\extension.js:1:186444)
        at B.[consumeChunk] (c:\Users\Tim van Osch\.vscode\extensions\ms-vscode-remote.remote-containers-0.145.1\dist\extension.js:1:186707)
        at B.write (c:\Users\Tim van Osch\.vscode\extensions\ms-vscode-remote.remote-containers-0.145.1\dist\extension.js:1:185952)
        at B.end (c:\Users\Tim van Osch\.vscode\extensions\ms-vscode-remote.remote-containers-0.145.1\dist\extension.js:1:187132)
        at Socket.onend (_stream_readable.js:693:10)
        at Object.onceWrapper (events.js:312:28)
        at Socket.emit (events.js:228:7)
        at endReadableNT (_stream_readable.js:1185:12)
        at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

</details>

**Comment by chrmarti** [comment]
Not seen elsewhere. Closing as won't fix.
