### ISSUE TITLE
login remote window10. why  time out ?

### ISSUE THREAD

**Issue by sixhj** [microsoft/vscode-remote-release#3651]
```
[11:42:08.532] Log Level: 2
[11:42:08.533] remote-ssh@0.51.0
[11:42:08.533] darwin x64
[11:42:08.535] SSH Resolver called for "ssh-remote+192.168.156.145", attempt 1
[11:42:08.535] SSH Resolver called for host: 192.168.156.145
[11:42:08.535] Setting up SSH remote "192.168.156.145"
[11:42:08.539] Acquiring local install lock: /var/folders/ry/xq9dj2p5267dh6zkp8htsb6r0000gn/T/vscode-remote-ssh-192.168.156.145-install.lock
[11:42:08.548] Looking for existing server data file at /Users/a/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-192.168.156.145-a0479759d6e9ea56afa657e454193f72aef85bd0-0.51.0/data.json
[11:42:08.574] Using commit id "a0479759d6e9ea56afa657e454193f72aef85bd0" and quality "stable" for server
[11:42:08.582] Install and start server if needed
[11:42:08.587] Checking ssh with "ssh -V"
[11:42:08.603] > OpenSSH_7.9p1, LibreSSL 2.7.3
[11:42:08.605] askpass server listening on /var/folders/ry/xq9dj2p5267dh6zkp8htsb6r0000gn/T/vscode-ssh-askpass-4c714673cf112b77f905922052597e2121f2a9fa.sock
[11:42:08.605] Spawning local server with {"ipcHandlePath":"/var/folders/ry/xq9dj2p5267dh6zkp8htsb6r0000gn/T/vscode-ssh-askpass-4e0f57b3496626f71986c7899e24c8065777d2d1.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","50544","-o","ConnectTimeout=15","192.168.156.145"],"dataFilePath":"/Users/a/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-192.168.156.145-a0479759d6e9ea56afa657e454193f72aef85bd0-0.51.0/data.json"}
[11:42:08.606] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/a/.vscode/extensions/ms-vscode-remote.remote-ssh-0.51.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/a/.vscode/extensions/ms-vscode-remote.remote-ssh-0.51.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/ry/xq9dj2p5267dh6zkp8htsb6r0000gn/T/vscode-ssh-askpass-4c714673cf112b77f905922052597e2121f2a9fa.sock"}
[11:42:08.608] Spawned 953
[11:42:08.695] > local-server> Spawned ssh: 954
[11:42:08.706] stderr> OpenSSH_7.9p1, LibreSSL 2.7.3
[11:42:08.857] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:XeQZZwwkCAdIWWiRjvT9hDQNLDW4olNrC6es7GBYK1k
[11:42:09.031] Got askpass request: {"request":"administrator@192.168.156.145's password:"}
[11:42:09.033] Showing password prompt
[11:42:09.034] Listening for interwindow password on /var/folders/ry/xq9dj2p5267dh6zkp8htsb6r0000gn/T/vscode-ssh-askpass-e9d1da840ce18e87c6c3ad4ca973e3ec1fac9595.sock
[11:42:09.035] Writing password prompt to globalState
[11:42:12.223] Got password response
[11:42:12.224] Interactor gave response: ****
[11:42:12.224] Cleaning up other-window auth server
[11:42:12.251] stderr> Authenticated to 192.168.156.145 ([192.168.156.145]:22).
[11:42:12.361] > Microsoft Windows [�汾 10.0.18362.53]
> (c) 2019 Microsoft Corporation����������Ȩ����
> 
> administrator@SD-20200119TSGR C:\Users\Administrator>echo 'ready: 03f84727e7c9'
[11:42:12.365] > 'ready: 03f84727e7c9'
[11:42:12.367] > 
[11:42:12.368] > administrator@SD-20200119TSGR C:\Users\Administrator>
[11:42:12.374] > uname -rsv
[11:42:12.375] > administrator@SD-20200119TSGR C:\Users\Administrator>
[11:42:12.375] stderr> 'uname' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
[11:42:12.375] stderr> ���������ļ���
[11:42:29.232] Terminating local server
[11:42:29.234] Resolver error: Connecting with SSH timed out
[11:42:29.243] Local server exit: 15
[11:42:29.247] ------
```

Use mac to remotely log in to win10. Use vscode to time out, but terminal will not time out

**Comment by roblourens** [comment]
Looks like you are using an old version of the extension, please try updating.

**Comment by sixhj** [comment]
> Looks like you are using an old version of the extension, please try updating.

[17:15:46.596] > JHdpblZlcnNpb249InVua25vd24iCn0KZWNobyAiYWZkZmMyNDhmMDg2OiBzdGFydCIKZWNobyAic3NoQXV0aFNvY2s9PSRlbnY6U1NIX0FVVEhfU09DSz09IgplY2hvICJsaXN0ZW5pbmdPbj09JHBvcnQ9PSIKZWNobyAib3NSZWxlYXNlSWQ9PXdpbmRvd
[17:15:46.596] > 3M9PSIKZWNobyAib3NWZXJzaW9uPT0kd2luVmVyc2lvbj09IgplY2hvICJhcmNoPT0kYXJjaD09IgplY2hvICJwbGF0Zm9ybT09d2luZG93cz09IgplY2hvICJhZmRmYzI0OGYwODY6IGVuZCIKZWNobyAiSW5zdGFsbCBzY3JpcHQgaXMgJHBpZCwgd2F0Y2h
[17:15:46.610] > pbmcgc3NoZCBwYXJlbnQgJHNzaGRQSUQiCndoaWxlICgkVHJ1ZSkgewpleGl0SWZOZWVkZWQKc2xlZXAgMzAKfQo=')))); powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -EncodedCommand `$remoteSSHConfig
[17:15:46.610] > urationScript"
[17:15:47.051] > afdfc248f086: running
[17:15:47.052] stderr> #< CLIXML
[17:15:47.889] > Acquiring lock on C:\Users\Administrator\.vscode-server\bin\a0479759d6e9ea56afa657e454193f72aef85bd0\vscode-remote-lock.a0479759d6e9ea56afa657e454193f72aef85bd0
> Looking for existing server in C:\Users\Administrator\.vscode-server\bin\a0479759d6e9ea56afa657e454193f72aef85bd0
> vscode-server already installed. Skipping download...
> Starting server with command... & 'C:\Users\Administrator\.vscode-server\bin\a0479759d6e9ea56afa657e454193f72aef85bd0\server.cmd' --host=127.0.0.1 --enable-remote-auto-shutdown --port=0 --disable-telemetry *> 'C:\Users\Administrator\.vscode-server\.a0479759d6e9ea56afa657e454193f72aef85bd0.log'
[17:15:51.983] > Server did not start successfully. Full server log at C:\Users\Administrator\.vscode-server\.a0479759d6e9ea56afa657e454193f72aef85bd0.log >>>
> C:\Users\Administrator\.vscode-server\bin\a0479759d6e9ea56afa657e454193f72aef85bd0\server.cmd : internal/modules/cjs/lo
> ader.js:626
> ����λ�� ��:1 �ַ�: 1
> + C:\Users\Administrator\.vscode-server\bin\a0479759d6e9ea56afa657e4541 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[17:15:52.064] > 
>     + CategoryInfo          : NotSpecified: (internal/modules/cjs/loader.js:626:String) [], RemoteException
>     + FullyQualifiedErrorId : NativeCommandError
>  
>     throw err;
>     ^
> 
> Error: Cannot find module 'C:\Users\Admini
[17:15:52.064] > 
> strator\.vscode-server\bin\a0479759d6e9ea56afa657e454193f72aef85bd0\
> out\vs\server\main.js'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
>     at Function.Module._load (internal/modules/cjs/loader
> .
> js:
> 527
> :27
> )
> 
>     at Fu
> nct
[17:15:52.064] > io
[17:15:52.068] > n.M
> od
> ul
> e.
> ru
> nM
> ain (i
> nternal/mo
> dul
> es
> /cjs/load
> er
> .j
> s:
> 83
> 7:10)
> 
>     at internal
[17:15:52.068] > 
> /
> main/run_main_mod
> u
> le.js:17:11 {
[17:15:52.104] >   
> c
> ode: 'MODULE_NOT_FOUND
> '
> ,
>   requireSt
> ack: []
> }
> 
> 
> <<< End of server log
> afdfc248f086##32##
> PS C:\Users\Administrator> 
[17:15:52.105] Received install output: afdfc248f086##32##
[17:15:52.105] Terminating local server
[17:15:52.106] stderr> <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>����׼���״�ʹ��ģ�顣</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>����׼���״�ʹ��ģ�顣</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
[17:15:52.113] Resolver error: Error: The VS Code Server failed to start
	at Function.ExitCode (/Users/a/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:130495)
	at Object.t.handleInstallOutput (/Users/a/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:128732)
	at Object.t.tryInstallWithLocalServer (/Users/a/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:102339)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async /Users/a/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:104310
	at async Object.t.withShowDetailsEvent (/Users/a/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:109845)
	at async /Users/a/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100912
	at async R (/Users/a/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:97702)
	at async Object.t.resolveWithLocalServer (/Users/a/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100561)
	at async Object.t.resolve (/Users/a/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:107840)
	at async /Users/a/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:141955
[17:15:52.118] Local server exit: 15
[17:15:52.122] ------


updated, but  have err 

i don't know   what happened ?

**Comment by roblourens** [comment]
Not sure what's going on here but it looks like something went wrong with downloading/unzipping the remote server. Can you just try running the "Kill VS Code Server on Host" command to start over fresh?
