### ISSUE TITLE
Container construction fails on latest Ubuntu 20.04 with Docker installed from Snap

### ISSUE THREAD

**Issue by ahri** [microsoft/vscode-remote-release#3657]
- VSCode Version: 1.49.0 (from Snap)
- Local OS Version: Ubuntu 20.04
- Remote OS Version: n/a
- Remote Extension/Connection Type: Docker [Docker version 19.03.11, build dd360c7 (from Snap)]

Steps to Reproduce:

1. Open a folder with a Dockerfile in it
2. Upon successful build, extension crashes:

```
Successfully built 84ac7812c38b
Successfully tagged vsc-mapdone-95e6de166d4c897777b6ba0566696f4e:latest
[253 ms] Start: Run: docker inspect --type image vsc-mapdone-95e6de166d4c897777b6ba0566696f4e
[311 ms] SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)
        at s (/home/adam/.vscode/extensions/ms-vscode-remote.remote-containers-0.140.1/dist/extension.js:1:34959)
        at processTicksAndRejections (internal/process/task_queues.js:94:5)
        at async Object.t.inspectImage (/home/adam/.vscode/extensions/ms-vscode-remote.remote-containers-0.140.1/dist/extension.js:1:36089)
        at async Object.t.inspectDockerImage (/home/adam/.vscode/extensions/ms-vscode-remote.remote-containers-0.140.1/dist/extension.js:1:25346)
        at async /home/adam/.vscode/extensions/ms-vscode-remote.remote-containers-0.140.1/dist/extension.js:1:186307
        at async Object.t.openDockerfileDevContainer (/home/adam/.vscode/extensions/ms-vscode-remote.remote-containers-0.140.1/dist/extension.js:1:186177)
```

Does this issue occur when you try this locally?: n/a
Does this issue occur when you try this locally and all extensions are disabled?: Yes

I tried running the command myself to see what the output was and it looks like valid JSON:

`$ docker inspect --type image vsc-mapdone-95e6de166d4c897777b6ba0566696f4e`
```json
[
    {
        "Id": "sha256:84ac7812c38b878564e6d1f212a1336d4be31ac07314e7abbc6c1203e5dba0db",
        "RepoTags": [
            "vsc-mapdone-95e6de166d4c897777b6ba0566696f4e:latest"
        ],
        "RepoDigests": [],
        "Parent": "sha256:b143a711fc4e58c76c6f91a8c9f3c496a9451c735dc699385c43c29c88ca61de",
        "Comment": "",
        "Created": "2020-09-12T17:13:06.367955386Z",
        "Container": "d80eaee0c00937d198e698426e957418cf188a5c76e2b668130f3394fba13429",
        "ContainerConfig": {
            "Hostname": "d80eaee0c009",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "BUILD_DEPS=wget",
                "DEV_DEPS=npm entr curl",
                "MAPDONE_DEPS=libsodium-dev pkg-config",
                "CYPRESS_DEPS=libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "ENV CYPRESS_DEPS=libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:b143a711fc4e58c76c6f91a8c9f3c496a9451c735dc699385c43c29c88ca61de",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "DockerVersion": "19.03.11",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "BUILD_DEPS=wget",
                "DEV_DEPS=npm entr curl",
                "MAPDONE_DEPS=libsodium-dev pkg-config",
                "CYPRESS_DEPS=libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb"
            ],
            "Cmd": [
                "bash"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:b143a711fc4e58c76c6f91a8c9f3c496a9451c735dc699385c43c29c88ca61de",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 69219567,
        "VirtualSize": 69219567,
        "GraphDriver": {
            "Data": {
                "MergedDir": "/var/snap/docker/common/var-lib-docker/overlay2/94691693ac64c7bf189c45c0b409563290bac4623fe68f24a8f900ded7da2991/merged",
                "UpperDir": "/var/snap/docker/common/var-lib-docker/overlay2/94691693ac64c7bf189c45c0b409563290bac4623fe68f24a8f900ded7da2991/diff",
                "WorkDir": "/var/snap/docker/common/var-lib-docker/overlay2/94691693ac64c7bf189c45c0b409563290bac4623fe68f24a8f900ded7da2991/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:07cab433985205f29909739f511777a810f4a9aff486355b71308bb654cdc868"
            ]
        },
        "Metadata": {
            "LastTagTime": "2020-09-12T19:50:00.079343828+01:00"
        }
    }
]
```

**Comment by Chuxel** [comment]
Last I checked, the snap package suffers from permissions issues with bind mounts. We call out that we do not support it: https://code.visualstudio.com/docs/remote/containers#_system-requirements

**Comment by ahri** [comment]
There are no volumes in use in this case, so no bind-mounting. However I'll try the non-Snap package this evening - I don't have access to that machine right now!

Thanks for the pointer on Snap.

**Comment by chrmarti** [comment]
Could you also check the console in the dev tools (`Help` > `Toggle Developer Tools`). That should have an entry with the output that was being parsed. (Since your manual run showed proper JSON, I wonder what was different in the output.)

**Comment by ahri** [comment]
I've swapped to use the `docker.io` package rather than the Snap, and that does indeed fix the problem. I'll have to wait to test the output to get to the bottom of the Snap issue. I'll report back.

**Comment by ahri** [comment]
This is the last thing that happened on the dev console before it failed to load with Docker from Snap:

`{Extension Host]% {stdout: "", stderr: ""}`

**Comment by chrmarti** [comment]
I realize you were talking about the Docker snap (not VS Code's). Assuming that is the culprit then. Closing as upstream. Thanks.
