### ISSUE TITLE
Timeout too short for Checking SSH client on Windows 10

### ISSUE THREAD

**Issue by nextcoder** [microsoft/vscode-remote-release#3704]
Issue: SSH remote connect can't succeed.

Cause: On my computer, typing ssh on CMD will invoke Windows 10 OpenSSH client. And it takes up to like 8 seconds for it to exit and come back to the prompt. As indicated by the log, the "Checking" phase of the extension doesn't wait long enough for the ssh command to be verified.

Solution: Increase the wait time, or allow me as the user to configure it.

- VSCode Version: 1.49
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu Xenial
- Remote Extension/Connection SSH

Steps to Reproduce:

1. Open VSCode
2. Try to connect to a configured host

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

Log: 
[13:50:21.485] Setting up SSH remote "[redacted]"
[13:50:21.506] Using commit id "a0479759d6e9ea56afa657e454193f72aef85bd0" and quality "stable" for server
[13:50:21.508] Install and start server if needed
[13:50:21.512] Checking ssh with "ssh -V"
[13:50:25.582] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[13:50:28.536] ssh is not exiting, continuing
[13:50:28.537] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[13:50:35.600] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[13:50:37.542] ssh is not exiting, continuing
[13:50:37.543] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[13:50:37.545] Got error from ssh: spawn C:\Program Files\Git\usr\bin\ssh.exe ENOENT
[13:50:37.545] Checking ssh with "C:\Program Files (x86)\Git\usr\bin\ssh.exe -V"
[13:50:37.547] Got error from ssh: spawn C:\Program Files (x86)\Git\usr\bin\ssh.exe ENOENT
[13:50:37.547] Finding installed ssh failed: ssh installation not found
[13:50:37.558] Resolver error: Error: ssh installation not found
	at _ (c:\Users\wcano\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:242296)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async O (c:\Users\wcano\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:238805)
	at async C (c:\Users\wcano\.vscode\extensions\ms-vscode-remote.remot

**Comment by EmbeddedBacon** [comment]
When creating a solution for this, please add the time-out value as a configuration parameters that we can modified for our specific cases.  Thanks.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/3731
