### ISSUE TITLE
Can't connect to Remote VsCode server

### ISSUE THREAD

**Issue by paule96** [microsoft/vscode-remote-release#3714]
- VSCode Version: 1.49.1
- Local OS Version: 2004 (19041.508)
- Remote OS Version: 1909 (18363.1082)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Open Remote development Session
2. VsCode ends with `The VS Code Server failed to start`

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

Log-Output of the server:

```powershell
Get-Content .vscode-server\.58bb7b2331731bf72587010e943852e13e6fd3cf.log -Wait -Tail 10


*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*




```

> yes it is empty, sometimes it also logs the IP. But nothing more...

Log from VsCode

```bash
[07:54:22.153] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[07:54:23.782] > Load key "C:\\Users\\xxxx/.ssh/id_rsa": Operation not permitted
> ]0;C:\WINDOWS\System32\cmd.exe
[07:54:23.784] Got some output, clearing connection timeout
[07:54:23.812] > xxxx@xxxxxx@xxxxxx's password: 
[07:54:23.818] Showing password prompt
[07:54:31.696] Got password response
[07:54:31.697] "install" wrote data to terminal: "************"
[07:54:31.722] > 
[07:54:36.965] > #< CLIXML
[07:54:37.169] > 44fbc28f0687: running
[07:54:37.184] > 
[07:54:38.691] > Acquiring lock on C:\Users\xxxx\.vscode-server\bin\58bb7b2331731bf72587010e94385
> 2e13e6fd3cf\vscode-remote-lock.58bb7b2331731bf72587010e943852e13e6fd3cf
[07:54:38.725] > 
> Looking for existing server in C:\Users\xxxx\.vscode-server\bin\58bb7b2331731bf7
> 2587010e943852e13e6fd3cf
[07:54:38.747] > vscode-server already installed. Skipping download...
[07:54:38.785] > Starting server with command... & 'C:\Users\x\.vxxxscode-server\bin\58bb7b233173
> 1bf72587010e943852e13e6fd3cf\server.cmd' --host=127.0.0.1 --enable-remote-auto-s
> hutdown --port=0  *> 'C:\Users\xxx\.vscode-server\.58bb7b2331731bf72587010e9438
> 52e13e6fd3cf.log
[07:54:38.812] > '
[07:54:43.123] > Server did not start successfully. Full server log at C:\Users\xxxx\.vscode-serv
> er\.58bb7b2331731bf72587010e943852e13e6fd3cf.log >>>
[07:54:43.132] > 
[07:54:43.185] > 
> 
> *
> * Visual Studio Code Server
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license https://aka.ms/vscode-remote/license
> *
> 
[07:54:43.191] > 
> <<< End of server log
> 44fbc28f0687##32##
[07:54:43.192] Received install output: 44fbc28f0687##32##
[07:54:43.199] Resolver error: Error: The VS Code Server failed to start
	at Function.ExitCode (c:\Users\xxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:130495)
	at Object.t.handleInstallOutput (c:\Users\xxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:128732)
	at I (c:\Users\xxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:106775)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\xxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:104774
	at async Object.t.withShowDetailsEvent (c:\Users\xxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:109845)
	at async Object.t.resolve (c:\Users\xxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107960)
	at async c:\Users\xxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:141955
[07:54:43.210] ------




[07:54:43.540] > 
[07:54:43.912] > <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
> <Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCust
[07:54:44.225] > 
> omObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"
> ><AV>Module werden f�r erstmalige Verwendung vorbereitet.</AV><AI>0</AI><Nil /><
> PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S
[07:54:44.324] > 
> ="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Rec
> ord"><AV>Module werden f�r erstmalige Verwendung vorbereitet.</AV><AI>0</AI><Nil
[07:54:44.349] > 
>  /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></
> Objs>
[07:54:44.744] "install" terminal command done
[07:54:44.744] Install terminal quit with output: Objs>
```

I also only apear if I try connect to the server if it's shutdown. If I run the command `.\server.cmd --host=127.0.0.1 --enable-remote-auto-shutdown --port=0  *> 'C:\Users\xxx\.vscode-server\.58bb7b2331731bf72587010e943852e13e6fd3cf.log'` manuell it works fine.

**Comment by roblourens** [comment]
How long does it take to write the ip/port when you start it manually?
