### ISSUE TITLE
Won't download server on Windows 7

### ISSUE THREAD

**Issue by dwilliamson** [microsoft/vscode-remote-release#3716]
Issue Type: <b>Bug</b>

Yes.

Extension version: 0.55.0
VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.18362
Fetching remote diagnostics for 'SSH' failed.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3398)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (19.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed.
</details>

Release notes don't state support for Windows 7 but I really needed that so decided to try.

When using a supported OpenSSH Server on a freshly-installed Windows 7 machine with all updates, there are errors connecting:

```
[21:19:00.961] > <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><S S="Error">The term 'Get-CimInstanc
> e' is not recognized as the name of a cmdlet, function,_x000D__x000A_</S><S S="Error"> script file, or operable progr
> am. Check the spelling of the name, or if a path_x000D__x000A_</S><S S="Error"> was included, verify that the path is
>  correct and try again._x000D__x000A_</S><S S="Error">At line:17 char:28_x000D__x000A_</S><S S="Error">+ $parentPID=(
> Get-CimInstance &lt;&lt;&lt;&lt;  win32_process | ? processid -eq $currentPID_x000D__x000A_</S><S S="Error">).parentp
> rocessid_x000D__x000A_</S><S S="Error">    + CategoryInfo          : ObjectNotFound: (Get-CimInstance:String) [], Com
>  _x000D__x000A_</S><S S="Error">   mandNotFoundException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : 
> CommandNotFoundException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>
[21:19:01.382] "install" terminal command done
[21:19:01.382] Install terminal quit with output: CommandNotFoundException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>
[21:19:01.382] Received install output: CommandNotFoundException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>
[21:19:01.383] Stopped parsing output early. Remaining text: CommandNotFoundException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>
[21:19:01.383] Failed to parse remote port from server output
[21:19:01.388] Resolver error: Error: 
	at Function.Create (c:\Users\Don Williamson\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:130564)
	at Object.t.handleInstallOutput (c:\Users\Don Williamson\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:127671)
	at I (c:\Users\Don Williamson\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:106775)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\Don Williamson\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:104774
	at async Object.t.withShowDetailsEvent (c:\Users\Don Williamson\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:109845)
	at async Object.t.resolve (c:\Users\Don Williamson\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107960)
	at async c:\Users\Don Williamson\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:141955
[21:19:01.391] ------
```

**Comment by dwilliamson** [comment]
Problem was due to not having the right version of Powershell for the `Get-CimInstance` command, which I believe is only available in Powershell 3+. Try this command to get your Powershell version:

```
Get-Host | Select Version
```

Mine was 2... You can upgrade to the latest Powershell 5.1 for Windows 7 by installing WMF 5.1, here: https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/wmf/setup/install-configure?view=powershell-7
