### ISSUE TITLE
error in buffer.js with remote-ssh in qemu

### ISSUE THREAD

**Issue by swebs** [microsoft/vscode-remote-release#3720]
This issue seems to be similar or the same as the initially one in #3485.  When I try to start  a remote session I get an error in buffer.js and the session does not start. It occurs in the released versions of vscode and the remote-ssh extension, as well as with insiders and the nightly extension. Here's the output for insiders/nightly. @roblourens apologies if this is a duplicate.

```
[10:37:51.560] Log Level: 2
[10:37:51.567] remote-ssh-nightly@2020.9.32580
[10:37:51.567] win32 x64
[10:37:51.568] SSH Resolver called for "ssh-remote+127.0.0.1", attempt 1
[10:37:51.568] SSH Resolver called for host: 127.0.0.1
[10:37:51.568] Setting up SSH remote "127.0.0.1"
[10:37:51.588] Using commit id "f943318042a3b9229049aea86cea04d0ff9c8210" and quality "insider" for server
[10:37:51.589] Install and start server if needed
[10:37:52.972] Checking ssh with "ssh -V"
[10:37:53.025] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[10:37:53.031] Running script with connection command: ssh -T -D 49474 127.0.0.1 bash
[10:37:53.034] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:37:53.512] > oper@127.0.0.1's password:]0;C:\WINDOWS\System32\cmd.exe
[10:37:53.512] Got some output, clearing connection timeout
[10:37:53.512] Showing password prompt
[10:37:58.870] Got password response
[10:37:58.871] "install" wrote data to terminal: "************"
[10:37:58.885] > 
[10:38:00.671] > 3557726f3a94: running
[10:38:01.389] > Acquiring lock on /home/oper/.vscode-server-insiders/bin/f943318042a3b9229049aea
> 86cea04d0ff9c8210/vscode-remote-lock.oper.f943318042a3b9229049aea86cea04d0ff9c82
> 10
[10:38:01.485] > Found existing installation at /home/oper/.vscode-server-insiders/bin/f943318042
> a3b9229049aea86cea04d0ff9c8210...
[10:38:01.701] > SHELL=/bin/bash
> LANGUAGE=en_CA:en
> PWD=/home/oper
> LOGNAME=oper
> XDG_SESSION_TYPE=tty
> HOME=/home/oper
> LANG=en_CA.UTF-8
> VSCODE_AGENT_FOLDER=/home/oper/.vscode-server-insiders
> SSH_CONNECTION=10.0.2.2 54654 10.0.2.15 22
> XDG_SESSION_CLASS=user
> USER=oper
> SHLVL=1
> XDG_SESSION_ID=3
> XDG_RUNTIME_DIR=/run/user/1000
> SSH_CLIENT=10.0.2.2 54654 22
> PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
> DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus 
> MAIL=/var/mail/oper
> _=/usr/bin/printenv
> Starting server with command... /home/oper/.vscode-server-insiders/bin/f94331804
> 2a3b9229049aea86cea04d0ff9c8210/server.sh --host=127.0.0.1 --enable-remote-auto-
> shutdown  --port=0 &> "/home/oper/.vscode-server-insiders/.f943318042a3b9229049a
[10:38:01.707] > 
> ea86cea04d0ff9c8210.log" < /dev/null
[10:38:01.722] > 
[10:38:01.833] > Waiting for server log...
[10:38:02.452] > Waiting for server log...
[10:38:03.071] > Waiting for server log...
[10:38:03.668] > Waiting for server log...
[10:38:04.297] > Waiting for server log...
[10:38:04.911] > Waiting for server log...
[10:38:05.510] > Waiting for server log...
[10:38:06.119] > Waiting for server log...
[10:38:06.714] > Waiting for server log...
[10:38:07.308] > Waiting for server log...
[10:38:07.918] > Waiting for server log...
[10:38:08.510] > Waiting for server log...
[10:38:09.044] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
[10:38:09.058] > 
[10:38:09.188] > Server did not start successfully. Full server log at /home/oper/.vscode-server-
> insiders/.f943318042a3b9229049aea86cea04d0ff9c8210.log >>>
[10:38:09.215] > buffer.js:585
>     slice: (buf, start, end) => buf.utf8Slice(start, end),
>                                     ^
> 
> RangeError: Index out of range
>     at Object.slice (buffer.js:585:37)
>     at Buffer.toString (buffer.js:782:14)
>     at Object.readFileSync (fs.js:386:41)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:990:22)    
>     at Module.load (internal/modules/cjs/loader.js:811:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
>     at internal/main/run_main_module.js:17:11 {
>   code: 'ERR_OUT_OF_RANGE'
> }
[10:38:09.222] > <<< End of server log
> 3557726f3a94##32##
[10:38:09.222] Received install output: 3557726f3a94##32##
[10:38:09.231] Resolver error: Error: The VS Code Server failed to start
	at Function.ExitCode (c:\Users\swebs\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2020.9.32580\out\extension.js:1:130495)
	at Object.t.handleInstallOutput (c:\Users\swebs\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2020.9.32580\out\extension.js:1:128732)
	at I (c:\Users\swebs\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2020.9.32580\out\extension.js:127:106775)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\swebs\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2020.9.32580\out\extension.js:127:104774
	at async Object.t.withShowDetailsEvent (c:\Users\swebs\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2020.9.32580\out\extension.js:127:109845)
	at async Object.t.resolve (c:\Users\swebs\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2020.9.32580\out\extension.js:127:107960)
	at async c:\Users\swebs\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2020.9.32580\out\extension.js:127:141955
[10:38:09.233] > 
[10:38:09.234] ------




[10:38:09.857] "install" terminal command done
[10:38:09.858] Install terminal quit with output: 
```

**Comment by roblourens** [comment]
Sorry, I have no clue. Does it do the same if you start the server manually from an external ssh session? See the command after `Starting server with command` in the log.

Also can you check whether running `node` on that machine by itself produces the same issue? (It's in the `.vscode-server-insides/bin/hash` folder) and could you mention in https://github.com/nodejs/node/issues/34709 that you have the same issue?

**Comment by swebs** [comment]
Running the server manually has the same issue. Output is below. I ran the `node` repl directly once and it worked, but tried again  and it failed, the same way mentioned in the node issue you referenced (where I also posted).

```
oper@myhostname:~$ .vscode-server-insiders/bin/f943318042a3b9229049aea86cea04d0ff9c8210/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown --port=0
buffer.js:585
    slice: (buf, start, end) => buf.utf8Slice(start, end),
                                    ^

RangeError: Index out of range
    at Object.slice (buffer.js:585:37)
    at Buffer.toString (buffer.js:782:14)
    at Object.readFileSync (fs.js:386:41)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:990:22)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'ERR_OUT_OF_RANGE'
}
oper@myhostname:~$
```

**Comment by Dantali0n** [comment]
I am also having this exact issue, available to provide additionally information if necessary.

**Comment by roblourens** [comment]
A lot has changed, someone let me know if this is still an issue
