### ISSUE TITLE
Can't connect with ssh: Terminating local server. Resolver error: Error: Connecting with SSH timed out

### ISSUE THREAD

**Issue by 12101111** [microsoft/vscode-remote-release#3723]
- VSCode Version: 1.50.0-insider commit f943348042a3b9229049aea86cea04d0ff9c8210
- Local OS Version: Archlinux
- Remote OS Version: Ubuntu 18.04.5
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. connect to remote device
2. Resolver error: Error: Connecting with SSH timed out

Does this issue occur when you try this locally?: I just can't connect to remote device
Does this issue occur when you try this locally and all extensions are disabled?: 

log:

```
[11:23:32.216] Log Level: 2
[11:23:32.217] remote-ssh@0.55.0
[11:23:32.217] linux x64
[11:23:32.218] SSH Resolver called for "ssh-remote+agx", attempt 1
[11:23:32.219] SSH Resolver called for host: agx
[11:23:32.219] Setting up SSH remote "agx"
[11:23:32.221] Acquiring local install lock: /tmp/vscode-remote-ssh-agx-install.lock
[11:23:32.225] Looking for existing server data file at /home/han/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-agx-f943318042a3b9229049aea86cea04d0ff9c8210-0.55.0/data.json
[11:23:32.226] Using commit id "f943318042a3b9229049aea86cea04d0ff9c8210" and quality "insider" for server
[11:23:32.226] Install and start server if needed
[11:23:32.229] Checking ssh with "ssh -V"
[11:23:32.232] > OpenSSH_8.3p1, OpenSSL 1.1.1g  21 Apr 2020

[11:23:32.234] askpass server listening on /run/user/1001/vscode-ssh-askpass-c6b309c78cae2bda4fd0198d296084c924ffcc34.sock
[11:23:32.235] Spawning local server with {"ipcHandlePath":"/run/user/1001/vscode-ssh-askpass-3e93436043e31eb328c25b4b7bb859aefb522483.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","34499","-o","ConnectTimeout=15","agx"],"dataFilePath":"/home/han/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-agx-f943318042a3b9229049aea86cea04d0ff9c8210-0.55.0/data.json"}
[11:23:32.235] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/han/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/opt/visual-studio-code-insiders/code-insiders","VSCODE_SSH_ASKPASS_MAIN":"/home/han/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1001/vscode-ssh-askpass-c6b309c78cae2bda4fd0198d296084c924ffcc34.sock"}
[11:23:32.237] Spawned 346844
[11:23:32.281] > local-server> Spawned ssh: 346852
[11:23:32.282] stderr> OpenSSH_8.3p1, OpenSSL 1.1.1g  21 Apr 2020
[11:23:32.309] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:*******
[11:23:32.360] stderr> Authenticated to 192.168.50.242 ([192.168.50.242]:22).
[11:23:33.642] > Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 4.9.140-tegra aarch64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   System information as of Thu Sep 24 11:23:43 CST 2020
> 
>   System load:  1.31               Processes:              278
>   Usage of /:   78.8% of 27.44GB   Users logged in:        1
>   Memory usage: 4%                 IP address for eth0:    192.168.50.242
>   Swap usage:   0%                 IP address for docker0: 172.17.0.1
> 
> 5 个可升级软件包。
> 5 个安全更新。
> 
[11:23:49.238] Terminating local server
[11:23:49.243] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/home/han/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:130714)
	at Timeout._onTimeout (/home/han/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:325959)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)
[11:23:49.244] Local server exit: 15
[11:23:49.245] ------
```

There is no `.vscode-server` folder on remote device.

**Comment by princelySid** [comment]
I have the exact same problem. I can connect to other hosts but for this specific host, it times out.

**Comment by MDCHAMP** [comment]
I don't know if this is helpful to anyone but for my setup:

client: Gallium linux, Openssh 7.6
server: Windows 10, opensshd 8.1

I was able to resolve this same behavior by reverting to OpenSSHd server on Windows  10 from 8.1 to 7.7p1

**Comment by bamurtaugh** [comment]
Thanks for the insight @MDCHAMP. @princelySid Does the suggestion above potentially help your scenario?

**Comment by princelySid** [comment]
Nope. Can't seem to consistently replicate the problem.

**Comment by bamurtaugh** [comment]
@princelySid Got it - so are you still experiencing the problem, just not consistently/it's hard to repro? 

@12101111 Are you still experiencing trouble?

**Comment by princelySid** [comment]
@bamurtaugh It's not consistent. I've been able to connect for the last couple of day without issue

**Comment by 12101111** [comment]
Still this error:
```
[09:27:59.506] Log Level: 2
[09:27:59.507] remote-ssh@0.56.0
[09:27:59.507] linux x64
[09:27:59.509] SSH Resolver called for "ssh-remote+agx", attempt 1
[09:27:59.509] SSH Resolver called for host: agx
[09:27:59.509] Setting up SSH remote "agx"
[09:27:59.511] Acquiring local install lock: /tmp/vscode-remote-ssh-agx-install.lock
[09:27:59.517] Looking for existing server data file at /home/han/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-agx-65f805d98e798b979901b74d4c8810c05455b792-0.56.0/data.json
[09:27:59.517] Using commit id "65f805d98e798b979901b74d4c8810c05455b792" and quality "insider" for server
[09:27:59.518] Install and start server if needed
[09:27:59.520] Checking ssh with "ssh -V"
[09:27:59.532] > OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020

[09:27:59.533] askpass server listening on /run/user/1001/vscode-ssh-askpass-31592e9641e4406c306540d1dc8c87cd2ef3f177.sock
[09:27:59.534] Spawning local server with {"ipcHandlePath":"/run/user/1001/vscode-ssh-askpass-3263c94a224f763785135ff868344d25299825a7.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","38665","-o","ConnectTimeout=15","agx"],"dataFilePath":"/home/han/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-agx-65f805d98e798b979901b74d4c8810c05455b792-0.56.0/data.json"}
[09:27:59.534] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/han/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/opt/visual-studio-code-insiders/code-insiders","VSCODE_SSH_ASKPASS_MAIN":"/home/han/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1001/vscode-ssh-askpass-31592e9641e4406c306540d1dc8c87cd2ef3f177.sock"}
[09:27:59.536] Spawned 108694
[09:27:59.580] > local-server> Spawned ssh: 108702
[09:27:59.581] stderr> OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020
[09:27:59.634] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:0Jli3jZ69WCFa2OHnkfX4d+XI3k0G3VHFBKF0ye3VNk
[09:27:59.695] stderr> Authenticated to 192.168.50.242 ([192.168.50.242]:22).
[09:28:01.453] > Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 4.9.140-tegra aarch64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   System information as of Wed Nov 11 09:28:28 CST 2020
> 
>   System load:  0.1                Processes:           250
>   Usage of /:   74.6% of 27.44GB   Users logged in:     1
>   Memory usage: 2%                 IP address for eth0: 192.168.50.242
>   Swap usage:   0%
> 
> 20 个可升级软件包。
> 3 个安全更新。
> 
[09:28:16.536] Terminating local server
[09:28:16.543] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/home/han/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:1:94553)
	at Timeout._onTimeout (/home/han/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:1:329614)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)
[09:28:16.544] Local server exit: 15
[09:28:16.545] ------
```

**Comment by tomateb** [comment]
same problem here. I'm able to connect through ssh from terminal, also from scratch in vscode. But after the first connection at some point the connection drops and is unable to reconnect:
```
[11:22:09.639] > ready: b1b780c7ccb2
[11:22:10.505] Terminating local server
[11:22:10.511] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/tombraude/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:1:94553)
	at Timeout._onTimeout (/Users/tombraude/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:1:329614)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)
[11:22:10.513] Local server exit: 15
[11:22:10.515] ------
```

**Comment by TermeHansen** [comment]
I have the exact same issue, both mschines running ubuntu 18.04, fully updated with latest vscode from snap. 
As the terminal show, it authenticates fine, but still timesout for some reason...

**Comment by roblourens** [comment]
Does a command like `echo "uname" | ssh <yourhost>` in an external terminal work?

Does disabling `remote.SSH.useLocalServer` help?

**Comment by vikingsloth** [comment]
I had this problem and even though I had Windows ssh installed I went through the steps again from here: https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse

I then sshed to the host once via powershell and after that it worked in vscode

**Comment by gengjiawen** [comment]
> echo "uname" | ssh <yourhost>

Pseudo-terminal will not be allocated because stdin is not a terminal.
Linux

> Does disabling remote.SSH.useLocalServer help?

Yes, this works.

@roblourens Is this have any pitfalls ?

**Comment by ilouzl** [comment]
@roblourens, in my case I am able to ssh through terminal ,but not using the extension. It has been working great for a long time but recently I've been experiencing this timeout error much more frequently and randomly, without being able to fix it by myself.

> Does a command like `echo "uname" | ssh <yourhost>` in an external terminal work?

Doesn't work (just replying `Pseudo-terminal will not be allocated because stdin is not a terminal` and disconnects after a while. I am trying to connect to a Linux machine from MacOS if it matters...)

and

> Does disabling `remote.SSH.useLocalServer` help?

Doesn't help.

Any other suggestion?
