### ISSUE TITLE
i couldn't ssh to aws ec2 instance

### ISSUE THREAD

**Issue by pro-ghanem** [microsoft/vscode-remote-release#3740]
```
[08:47:47.192] Log Level: 2
[08:47:47.194] remote-ssh@0.55.0
[08:47:47.194] linux x64
[08:47:47.196] SSH Resolver called for "ssh-remote+54.216.8.252", attempt 1
[08:47:47.197] SSH Resolver called for host: 54.216.8.252
[08:47:47.197] Setting up SSH remote "54.216.8.252"
[08:47:47.201] Acquiring local install lock: /tmp/vscode-remote-ssh-54.216.8.252-install.lock
[08:47:47.210] Looking for existing server data file at /home/ghanem/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-54.216.8.252-e5e9e69aed6e1984f7499b7af85b3d05f9a6883a-0.55.0/data.json
[08:47:47.211] Using commit id "e5e9e69aed6e1984f7499b7af85b3d05f9a6883a" and quality "stable" for server
[08:47:47.214] Install and start server if needed
[08:47:47.220] Checking ssh with "ssh -V"
[08:47:47.232] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020

[08:47:47.236] Using SSH config file "/home/ghanem/.ssh/config"
[08:47:47.238] askpass server listening on /run/user/1000/vscode-ssh-askpass-1f28c8a2e0e0ef126c872cd273f32703ea313d24.sock
[08:47:47.238] Spawning local server with {"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-1fe8d4fd7504f7d4e342589da38b6ad559fb5a37.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","42629","-o","ConnectTimeout=15","-F","/home/ghanem/.ssh/config","54.216.8.252"],"dataFilePath":"/home/ghanem/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-54.216.8.252-e5e9e69aed6e1984f7499b7af85b3d05f9a6883a-0.55.0/data.json"}
[08:47:47.238] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/ghanem/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/ghanem/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-1f28c8a2e0e0ef126c872cd273f32703ea313d24.sock"}
[08:47:47.246] Spawned 25114
[08:47:47.379] > local-server> Spawned ssh: 25122
[08:47:47.384] stderr> OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020
[08:47:48.251] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:Q1BVdAqrylRSUdurmfrk/NfslFTxShAWnemqFSLRqHk
[08:47:48.837] stderr> Authenticated to 54.216.8.252 ([54.216.8.252]:22).
[08:47:49.896] > Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.3.0-1035-aws x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>  System information disabled due to load higher than 2.0
> 
>  * Kubernetes 1.19 is out! Get it in one command with:
> 
>      sudo snap install microk8s --channel=1.19 --classic
> 
>    https://microk8s.io/ has docs and details.
> 
>  * Canonical Livepatch is available for installation.
>    - Reduce system reboots and improve kernel security. Activate at:
>      https://ubuntu.com/livepatch
> 
> 19 packages can be updated.
> 0 updates are security updates.
> 
> 
> *** System restart required ***
[08:47:50.022] > ready: 36958b723ac9
[08:47:50.118] > Linux 5.3.0-1035-aws #37-Ubuntu SMP Sun Sep 6 01:17:09 UTC 2020
[08:47:50.119] Platform: linux
[08:47:50.453] > 36958b723ac9: running
[08:47:50.468] > Creating the server install dir failed...
> 36958b723ac9##34##
[08:47:50.469] Received install output: 36958b723ac9##34##
[08:47:50.471] Terminating local server
[08:47:50.474] stderr> mkdir: cannot create directory ‘/home/ubuntu/.vscode-server’: Not a directory
[08:47:50.488] Resolver error: Error: Failed to create the remote server's install directory
	at Function.ExitCode (/home/ghanem/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:130495)
	at Object.t.handleInstallOutput (/home/ghanem/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:128951)
	at Object.t.tryInstallWithLocalServer (/home/ghanem/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:102339)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /home/ghanem/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:104310
	at async Object.t.withShowDetailsEvent (/home/ghanem/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:109845)
	at async /home/ghanem/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100912
	at async R (/home/ghanem/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:97702)
	at async Object.t.resolveWithLocalServer (/home/ghanem/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100561)
	at async Object.t.resolve (/home/ghanem/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:107840)
	at async /home/ghanem/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:141955
[08:47:50.490] Local server exit: 15
[08:47:50.494] ------

```

**Comment by roblourens** [comment]
Did we get the home dir wrong? Does `/home/ubuntu/` exist? Do you have permissions to create that path manually?
