### ISSUE TITLE
ssh question! Help!

### ISSUE THREAD

**Issue by dylan110** [microsoft/vscode-remote-release#3758]
![image](https://user-images.githubusercontent.com/16866386/94556936-7c5dcb80-0290-11eb-9dfa-4e09c5ad31a3.png)

```
[20:14:52.742] Log Level: 2
[20:14:52.743] remote-ssh@0.55.0
[20:14:52.743] win32 x64
[20:14:52.745] SSH Resolver called for "ssh-remote+111", attempt 1
[20:14:52.745] SSH Resolver called for host: 111
[20:14:52.745] Setting up SSH remote "111"
[20:14:52.812] Using commit id "e5e9e69aed6e1984f7499b7af85b3d05f9a6883a" and quality "stable" for server
[20:14:52.814] Install and start server if needed
[20:14:53.732] Checking ssh with "ssh -V"
[20:14:53.780] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[20:14:53.784] Running script with connection command: ssh -T -D 52873 111 bash
[20:14:53.786] Terminal shell path: C:\windows\System32\cmd.exe
[20:14:53.852] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\windows\System32\cmd.exe
[20:14:53.853] Got some output, clearing connection timeout
[20:14:53.863] > '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC' 不是内部或外部命令，也不
> 是可运行的程序
> 或批处理文件。
> 
[20:14:54.163] "install" terminal command done
[20:14:54.163] Install terminal quit with output: 或批处理文件。
[20:14:54.163] Received install output: 或批处理文件。
[20:14:54.164] Stopped parsing output early. Remaining text: 或批处理文件。
[20:14:54.164] Failed to parse remote port from server output
[20:14:54.170] Resolver error: Error: 
	at Function.Create (c:\Users\hhye\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:130564)
	at Object.t.handleInstallOutput (c:\Users\hhye\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:127671)
	at I (c:\Users\hhye\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:106775)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\hhye\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:104774
	at async Object.t.withShowDetailsEvent (c:\Users\hhye\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:109845)
	at async Object.t.resolve (c:\Users\hhye\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107960)
	at async c:\Users\hhye\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:141955
[20:14:54.172] ------
```

**Comment by arocki7** [comment]
I have the same problem.

**Comment by arocki7** [comment]
It was down to my network/firewall connections. I fixed my VPN connection and it worked fine for me.

**Comment by imxxw** [comment]
Try to remove folder "~/.vscode-server" in the remote server, and open vscode to connect the remote server with remote-ssh.

**Comment by imxxw** [comment]
> ![image](https://user-images.githubusercontent.com/16866386/94556936-7c5dcb80-0290-11eb-9dfa-4e09c5ad31a3.png)
> [20:14:52.742] Log Level: 2
> [20:14:52.743] remote-ssh@0.55.0
> [20:14:52.743] win32 x64
> [20:14:52.745] SSH Resolver called for "ssh-remote+111", attempt 1
> [20:14:52.745] SSH Resolver called for host: 111
> [20:14:52.745] Setting up SSH remote "111"
> [20:14:52.812] Using commit id "e5e9e69aed6e1984f7499b7af85b3d05f9a6883a" and quality "stable" for server
> [20:14:52.814] Install and start server if needed
> [20:14:53.732] Checking ssh with "ssh -V"
> [20:14:53.780] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
> 
> [20:14:53.784] Running script with connection command: ssh -T -D 52873 111 bash
> [20:14:53.786] Terminal shell path: C:\windows\System32\cmd.exe
> [20:14:53.852] >
> 
> > �]0;C:\windows\System32\cmd.exe�
> > [20:14:53.853] Got some output, clearing connection timeout
> > [20:14:53.863] > '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC' 不是内部或外部命令，也不
> > 是可运行的程序
> > 或批处理文件。
> 
> [20:14:54.163] "install" terminal command done
> [20:14:54.163] Install terminal quit with output: 或批处理文件。
> [20:14:54.163] Received install output: 或批处理文件。
> [20:14:54.164] Stopped parsing output early. Remaining text: 或批处理文件。
> [20:14:54.164] Failed to parse remote port from server output
> [20:14:54.170] Resolver error: Error:
> at Function.Create (c:\Users\hhye.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:130564)
> at Object.t.handleInstallOutput (c:\Users\hhye.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:127671)
> at I (c:\Users\hhye.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:106775)
> at processTicksAndRejections (internal/process/task_queues.js:94:5)
> at async c:\Users\hhye.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:104774
> at async Object.t.withShowDetailsEvent (c:\Users\hhye.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:109845)
> at async Object.t.resolve (c:\Users\hhye.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107960)
> at async c:\Users\hhye.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:141955
> [20:14:54.172] ------

Remove the folder "**~/.vscode-server**" in the remote server, and open vscode to connect the remote server with remote-ssh.

**Comment by bamurtaugh** [comment]
Hey @dylan110, does it look like either of the above comments might help your situation (fixing your VPN connection or removing the vscode-server)?
