### ISSUE TITLE
ssh: Could not resolve hostname bash: Name or service not known

### ISSUE THREAD

**Issue by fabsi88** [microsoft/vscode-remote-release#3770]
- VSCode Version: 1.49.2
- Local OS Version: Windows 10 10.0.18363
- Remote OS Version: Redhat Linux 7.8
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Create a SSH remote connection with the following Config
```
Host anyserver.fqdn
  HostName anyserver.fqdn
  User asecretuser
  IdentityFile "C:\Users\bla\.ssh\id_rsa"
  MACs hmac-sha2-256
```
2. Open a connection to the remote
3. Error is appearing
I also tried IP as Host and HostName - not working.
Adding 
`
Host asecretuser@anyserver.fqdn
`
a corrupted MAC message appears - therefore I added the MACs in the config - but no success.
Another Entry in the .ssh/config is working
```
Host 10.93.119.26
  HostName 10.93.119.26
  User root
```

Log:
```
21:25:40.458] Log Level: 2
[21:25:40.473] remote-ssh@0.55.0
[21:25:40.474] win32 x64
[21:25:40.475] SSH Resolver called for "ssh-remote+anyserver.fqdn", attempt 1
[21:25:40.475] SSH Resolver called for host: anyserver.fqdn
[21:25:40.475] Setting up SSH remote "anyserver.fqdn"
[21:25:40.521] Using commit id "e5e9e69aed6e1984f7499b7af85b3d05f9a6883a" and quality "stable" for server
[21:25:40.522] Install and start server if needed
[21:25:41.915] Checking ssh with "ssh -V"
[21:25:42.021] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[21:25:42.027] Running script with connection command: ssh -T -D 64391 anyserver.fqdn bash
[21:25:42.030] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[21:25:42.331] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\WINDOWS\System32\cmd.exe
[21:25:42.331] Got some output, clearing connection timeout
[21:25:42.346] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[21:25:42.829] > ssh: Could not resolve hostname bash: Name or service not known
> 
[21:25:44.249] "install" terminal command done
[21:25:44.249] Install terminal quit with output: ssh: Could not resolve hostname bash: Name or service not known
[21:25:44.249] Received install output: ssh: Could not resolve hostname bash: Name or service not known
[21:25:44.257] Resolver error: Error: Could not resolve hostname
	at Function.Offline (c:\Users\bla\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:130625)
	at c:\Users\bla\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:126500
	at Object.t.handleInstallOutput (c:\Users\bla\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:126987)
	at I (c:\Users\bla\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:106775)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\bla\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:104774
	at async Object.t.withShowDetailsEvent (c:\Users\bla\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:109845)
	at async Object.t.resolve (c:\Users\bla\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107960)
	at async c:\Users\bla\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:141955
[21:25:44.260] ------
```

**Comment by bamurtaugh** [comment]
Just to clarify, are you able to connect to this machine using the same user and host name through another means, like SSH-ing into it through a terminal?

**Comment by fabsi88** [comment]
Sure.

Brigit Murtaugh <notifications@github.com> schrieb am Mi., 28. Okt. 2020,
22:34:

**Comment by bamurtaugh** [comment]
Just to clarify, does your comment above mean you were able to connect through a terminal? Or that you were going to investigate it?

**Comment by fabsi88** [comment]
Good morning,
yes. Correct. 
Using the ssh command on the cmd of Windows (which accesses the same ssh config) the connection works fine.

Trying to connect via vscode throws
`` 
ssh: Could not resolve hostname bash: Name or service not known
``

**Comment by roblourens** [comment]
That command is pretty simple and that needs to work, or there's nothing we can do. It sounds like it doesn't think `anyserver.fqdn` is the host and it thinks `bash` is the host. No idea why that would be but see if you can mess around with that command and get it to work.
