### ISSUE TITLE
Remote SSH constantly drops

### ISSUE THREAD

**Issue by dashesy** [microsoft/vscode-remote-release#3772]
- VSCode Version: 1.49.2
- Local OS Version: 1809
- Remote OS Version: Ubuntu 16
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to remote
2. Explore remote repositories

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

```text
[17:27:08.544] SSH Resolver called for "ssh-remote+my-linux", attempt 3, (Reconnection)
[17:27:08.544] SSH Resolver called for host: my-linux
[17:27:08.545] Setting up SSH remote "my-linux"
[17:27:08.554] Using commit id "e5e9e69aed6e1984f7499b7af85b3d05f9a6883a" and quality "stable" for server
[17:27:08.560] Install and start server if needed
[17:27:08.575] Running script with connection command: ssh -T -D 2187 my-linux bash
[17:27:08.581] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[17:27:08.844] > 
[17:27:08.844] Got some output, clearing connection timeout
```

This started to happen after updating. The previous version was fine.
What did change? was it using git-bash's ssh beforhand?

This is the type of error I get:

```text
> The process tried to write to a nonexistent pipe.
> 
[17:30:23.805] "install" terminal command done
[17:30:23.806] Install terminal quit with output: The process tried to write to a nonexistent pipe.
[17:30:23.806] Received install output: The process tried to write to a nonexistent pipe.
[17:30:23.809] Resolver error: Error: The process tried to write to a nonexistent pipe
	at Function.Offline (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:130625)
	at c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:126609
	at Object.t.handleInstallOutput (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:126987)
	at I (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:106775)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:104774
	at async Object.t.withShowDetailsEvent (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:109845)
	at async Object.t.resolve (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107960)
	at async c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:141955
[17:30:23.813] ------
```

I removed .vscode-server on the remote machine, but the issue is back. ssh manually with git-bash works fine

**Comment by Nadav-K** [comment]
same issue here.

**Comment by dashesy** [comment]
My issue was mostly networking. I rebooted my modem and now it works reliably again. Not sure exactly why.

**Comment by bamurtaugh** [comment]
Thanks for the update @dashesy - since it's working reliably again, going to close out this issue. If you (or other folks) are still facing this issue, please just let me know, and I'd be more than happy to reopen or discuss it further.
