### ISSUE TITLE
VSCode remote server can not finding glibc, libstdc++ in custom directory such as /home/username/...

### ISSUE THREAD

**Issue by xuzhaofangxzf** [microsoft/vscode-remote-release#3780]
- VSCode Version:1.4.91
- Local OS Version:MacOS 13.6
- Remote OS Version:CentOS6
- Remote Extension/Connection Type: remote SSH

here is the log

[00:18:09.961] Log Level: 2
[00:18:09.963] remote-ssh@0.55.0
[00:18:09.963] darwin x64
[00:18:09.966] SSH Resolver called for "ssh-remote+dev2.se.corp.qihoo.net", attempt 1
[00:18:09.966] SSH Resolver called for host: dev2.se.corp.qihoo.net
[00:18:09.966] Setting up SSH remote "dev2.se.corp.qihoo.net"
[00:18:09.970] Acquiring local install lock: /var/folders/xm/76jxxnqd4yngm94jxwn1dznr0000gn/T/vscode-remote-ssh-dev2.se.corp.qihoo.net-install.lock
[00:18:09.990] Looking for existing server data file at /Users/xufang/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-dev2.se.corp.qihoo.net-58bb7b2331731bf72587010e943852e13e6fd3cf-0.55.0/data.json
[00:18:09.991] Using commit id "58bb7b2331731bf72587010e943852e13e6fd3cf" and quality "stable" for server
[00:18:09.992] Install and start server if needed
[00:18:09.995] Checking ssh with "ssh -V"
[00:18:10.021] > OpenSSH_7.6p1, LibreSSL 2.6.2

[00:18:10.023] askpass server listening on /var/folders/xm/76jxxnqd4yngm94jxwn1dznr0000gn/T/vscode-ssh-askpass-d27c85a524853d6a5b0b451a987bd375dcabc38a.sock
[00:18:10.024] Spawning local server with {"ipcHandlePath":"/var/folders/xm/76jxxnqd4yngm94jxwn1dznr0000gn/T/vscode-ssh-askpass-e81dd0b36b8c25d99971cbb1e55fb9e274021a3a.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","51467","-o","ConnectTimeout=15","dev2.se.corp.qihoo.net"],"dataFilePath":"/Users/xufang/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-dev2.se.corp.qihoo.net-58bb7b2331731bf72587010e943852e13e6fd3cf-0.55.0/data.json"}
[00:18:10.024] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/xufang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Users/xufang/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/xufang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/xm/76jxxnqd4yngm94jxwn1dznr0000gn/T/vscode-ssh-askpass-d27c85a524853d6a5b0b451a987bd375dcabc38a.sock"}
[00:18:10.027] Spawned 3654
[00:18:10.135] > local-server> Spawned ssh: 3655
[00:18:10.147] stderr> OpenSSH_7.6p1, LibreSSL 2.6.2
[00:18:10.361] stderr> debug1: Server host key: ssh-rsa SHA256:yDFwTqtxfM6f+MJ1/W1LNT/bYloeYSXtRWqF/j5Lbi0
[00:18:10.635] Got askpass request: {"request":"xuzhaofang@dev2.se.corp.qihoo.net's password:"}
[00:18:10.636] Showing password prompt
[00:18:10.637] Listening for interwindow password on /var/folders/xm/76jxxnqd4yngm94jxwn1dznr0000gn/T/vscode-ssh-askpass-82ca911c1998678168eaeff18cd4f1e0538929d7.sock
[00:18:10.637] Writing password prompt to globalState
[00:18:16.979] Got password response
[00:18:16.979] Interactor gave response: **********
[00:18:16.980] Cleaning up other-window auth server
[00:18:17.033] stderr> Authenticated to dev2.se.corp.qihoo.net ([10.16.28.25]:22).
[00:18:17.133] > ready: 4b743881b5b2
[00:18:17.169] > Linux 2.6.32-220.7.1.el6.x86_64 #1 SMP Wed Mar 7 00:52:02 GMT 2012
[00:18:17.170] Platform: linux
[00:18:17.348] > 4b743881b5b2: running
[00:18:17.416] 

> > **Missing GLIBCXX >= 3.4.18!**

> Found versions 3.4.1
> 3.4.2
> 3.4.3
> 3.4.4
> 3.4.5
> 3.4.6
> 3.4.7
> 3.4.8
> 3.4.9
> 3.4.10
> 3.4.11
> 3.4.12
> 3.4.13
> 3.4.14
> 3.4.15
> 3.4.16
> 3.4.17
> 3.4.5
> 3.4.5
> 3.4.5
> 3.4.9
> 3.4.11
> 3.4.10
> 3.4.16
> 3.4.1
> 3.4.5
> 3.4.5
> 3.4.5
> 3.4.11
> 3.4.5
> 3.4.5
> 3.4.5
> 3.4.11
> 3.4.5
> 3.4.12
> 3.4.5
> 3.4.2
> 3.4.5
> 3.4.6
> 3.4.15
> 3.4.5
> 3.4.5
> 3.4.11
> 3.4.3
> 3.4.7
> 3.4.5
> 3.4.5
> 3.4.5
> 3.4.14
> 3.4.5
> 3.4.5
> 3.4.14
> 3.4.11
> 3.4.5
> 3.4.5
> 3.4.5
> 3.4.5
> 3.4.5
> 3.4.8
> 3.4.13
> 3.4.11
> 3.4.5
> 3.4.17
> 3.4.4
> 3.4.5
> 3.4.5
[00:18:17.422] > 4b743881b5b2$$1$$
[00:18:17.424] > Acquiring lock on /home/xuzhaofang/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf/vscode-remote-lock.xuzhaofang.58bb7b2331731bf72587010e943852e13e6fd3cf
[00:18:17.424] > Installing to /home/xuzhaofang/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf...
> 4b743881b5b2%%1%%
[00:18:17.434] > Downloading with wget
[00:18:18.829] > wget download failed
[00:18:18.829] > ERROR: certificate common name “*.azurewebsites.net” doesn’t match requested host name “update.code.visualstudio.com”. To connect to update.code.visualstudio.com insecurely, use ‘--no-check-certificate’.
> HOSTNAME=dev2.corp.qihoo.net
> SHELL=/bin/bash
> TERM=xterm-256color
> HISTSIZE=1000
> SSH_CLIENT=10.247.23.173 51468 22
> LD_PRELOAD=/home/xuzhaofang/libs/lib64/libstdc++.so.6
> LC_ALL=en_US.UTF-8
> USER=xuzhaofang
> LD_LIBRARY_PATH=/home/xuzhaofang/libs/bin:/home/xuzhaofang/libs/lib64:/lib:/lib64:/usr/lib:/usr/lib64:/usr/local/lib:/usr/local/lib64
> VSCODE_AGENT_FOLDER=/home/xuzhaofang/.vscode-server
> PATH=/home/xuzhaofang/libs/bin:/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/home/xuzhaofang/bin
> MAIL=/var/spool/mail/xuzhaofang
> MAVEN_HOME=/usr/share/apache-maven
> PWD=/home/xuzhaofang/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf
> LANG=en_US.UTF-8
> HISTCONTROL=ignoredups
> HOME=/home/xuzhaofang
> SHLVL=2
> M2_HOME=/usr/share/apache-maven
> LOGNAME=xuzhaofang
> CVS_RSH=ssh
> SSH_CONNECTION=10.247.23.173 51468 10.16.28.25 22
> LESSOPEN=|/usr/bin/lesspipe.sh %s
> G_BROKEN_FILENAMES=1
> _=/usr/bin/printenv
> OLDPWD=/da1/home/xuzhaofang
> Trigger client server download
> 4b743881b5b2:trigger_server_download
> platform==linux==
> vscodeArch==x64==
> destFolder==/home/xuzhaofang/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf==
> 4b743881b5b2:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/xuzhaofang/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf/vscode-scp-done.flag and vscode-server.tar.gz to exist
>  
[00:18:18.830] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/home/xuzhaofang/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf"}
[00:18:18.830] Downloading VS Code server locally...
[00:18:55.663] >     
[00:20:12.354] Downloaded VS Code server to /var/folders/xm/76jxxnqd4yngm94jxwn1dznr0000gn/T/d46a4ade-fadd-44b3-a7e6-34e0b7fa723b
[00:20:12.355] Renamed VS Code server to /var/folders/xm/76jxxnqd4yngm94jxwn1dznr0000gn/T/vscode_server_1601482812354/vscode-server.tar.gz
[00:20:12.357] Checking ssh with "ssh -V"
[00:20:12.381] > OpenSSH_7.6p1, LibreSSL 2.6.2

[00:20:12.382] Testing scp with "scp"
[00:20:12.394] scp exited with code: 1
[00:20:12.394] Got stderr from scp: usage: scp [-346BCpqrv] [-c cipher] [-F ssh_config] [-i identity_file]
           [-l limit] [-o ssh_option] [-P port] [-S program]
           [[user@]host1:]file1 ... [[user@]host2:]file2
[00:20:12.395] Copying file to remote with scp -o ConnectTimeout=15 vscode-server.tar.gz vscode-scp-done.flag dev2.se.corp.qihoo.net:/home/xuzhaofang/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf
[00:20:12.396] Using cwd: file:///var/folders/xm/76jxxnqd4yngm94jxwn1dznr0000gn/T/vscode_server_1601482812354
[00:20:12.990] > xuzhaofang@dev2.se.corp.qihoo.net's password: 
[00:20:12.990] Showing password prompt
[00:20:22.024] Got password response
[00:20:22.024] "Copy server to host" wrote data to terminal: "**********"
[00:20:22.039] > 

[00:29:14.936] > vscode-scp-done.flag                            0%    0     0.0KB/s   --:-- ETAvscode-scp-done.flag                          100%    9     0.2KB/s   00:00    
[00:29:14.939] "Copy server to host" terminal command done
[00:30:09.047] >              
[00:30:09.097] >                                 
[00:30:09.097] >                                   
[00:30:09.098] >                               
[00:30:09.121] >           Found flag and server on host
> 4b743881b5b2%%2%%
> tar --version:
> tar (GNU tar) 1.23
> Copyright (C) 2010 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
> HOSTNAME=dev2.corp.qihoo.net
> SHELL=/bin/bash
> TERM=xterm-256color
> HISTSIZE=1000
> SSH_CLIENT=10.247.23.173 51468 22
> LD_PRELOAD=/home/xuzhaofang/libs/lib64/libstdc++.so.6
> LC_ALL=en_US.UTF-8
> USER=xuzhaofang
> LD_LIBRARY_PATH=/home/xuzhaofang/libs/bin:/home/xuzhaofang/libs/lib64:/lib:/lib64:/usr/lib:/usr/lib64:/usr/local/lib:/usr/local/lib64
> VSCODE_AGENT_FOLDER=/home/xuzhaofang/.vscode-server
> PATH=/home/xuzhaofang/libs/bin:/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/home/xuzhaofang/bin
> MAIL=/var/spool/mail/xuzhaofang
> MAVEN_HOME=/usr/share/apache-maven
> PWD=/da1/home/xuzhaofang
> LANG=en_US.UTF-8
> HISTCONTROL=ignoredups
> HOME=/home/xuzhaofang
> SHLVL=2
> M2_HOME=/usr/share/apache-maven
> LOGNAME=xuzhaofang
> CVS_RSH=ssh
> SSH_CONNECTION=10.247.23.173 51468 10.16.28.25 22
> LESSOPEN=|/usr/bin/lesspipe.sh %s
> G_BROKEN_FILENAMES=1
> _=/usr/bin/printenv
> OLDPWD=/home/xuzhaofang/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf
[00:30:09.127] > Starting server with command... /home/xuzhaofang/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/home/xuzhaofang/.vscode-server/.58bb7b2331731bf72587010e943852e13e6fd3cf.log" < /dev/null
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> Server did not start successfully. Full server log at /home/xuzhaofang/.vscode-server/.58bb7b2331731bf72587010e943852e13e6fd3cf.log >>>
[00:30:09.132] > **/home/xuzhaofang/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf/node: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /home/xuzhaofang/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf/node)
> /home/xuzhaofang/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf/node: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /home/xuzhaofang/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf/node)
> /home/xuzhaofang/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf/node: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/xuzhaofang/.vscode-server/bin/58bb7b2331731bf72587010e943852e13e6fd3cf/node)**
> <<< End of server log
> 4b743881b5b2##32##
[00:30:09.133] Received install output: 4b743881b5b2##32##
[00:30:09.133] Terminating local server
[00:30:09.138] Resolver error: Error: The VS Code Server failed to start
	at Function.ExitCode (/Users/xufang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:130495)
	at Object.t.handleInstallOutput (/Users/xufang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:128732)
	at Object.t.tryInstallWithLocalServer (/Users/xufang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:102339)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /Users/xufang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:104310
	at async Object.t.withShowDetailsEvent (/Users/xufang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:109845)
	at async /Users/xufang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100912
	at async R (/Users/xufang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:97702)
	at async Object.t.resolveWithLocalServer (/Users/xufang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100561)
	at async Object.t.resolve (/Users/xufang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:107840)
	at async /Users/xufang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:141955
[00:30:09.139] Local server exit: 15
[00:30:09.141] ------

because I have not root authority，so I installed the GLIB manual in a path /home/xuzhaofang/libs/ 
I set the path and LD_LIBRARY_PATH to include my path. and then I type the command "ldd --version" get 
ldd (GNU libc) 2.17
and I use command "strings /home/xuzhaofang/libs/lib64/libstdc++.so.6 |grep GLIBC"

GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBC_2.2.5
GLIBC_2.3
GLIBC_2.3.2
GLIBCXX_FORCE_NEW
GLIBCXX_DEBUG_MESSAGE_LENGTH

Then I think it may meet the library demand.

So the question is how can I make configuration to make vscode reomote ssh extensions to get the dependency in my own path(/home/xuzhaofang/libs/lib64 not the system path(/lib64)

**Comment by xuzhaofangxzf** [comment]
@joaomoreno

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/1712
