### ISSUE TITLE
Remote SSH connecting to Aarch64: Cannot reconnect. Please, reload the window. 

### ISSUE THREAD

**Issue by ZhenyaKh** [microsoft/vscode-remote-release#3787]
- Vscode Version: 1.49.2 (user setup)
- Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
- Date: 2020-09-24T16:29:41.983Z
- Electron: 9.2.1
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Windows_NT x64 10.0.17763
- "Remote SSH" extention: v.0.55.0
- "Remote - SSH: Editing Configuration Files" extension: v.0.55.0
- No other vscode extensions installed (when the problem occurred, I removed cpptools)
- Connecting to: aarch64 -- CentOS 8.2.2004 -- 4.18.0-193.el8.aarch64
- On CentOS 8 aarch64 I tried to remove ~/.vscode-server folder, but it did not help
- Currently I solve the problem by using old 1.48.2  Vscode version.

Log (Window) -- OUTPUT:

```
[2020-10-01 13:36:12.629] [renderer1] [info] [remote-connection][ExtensionHost][7a114…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2020-10-01 13:36:12.629] [renderer1] [info] [remote-connection][ExtensionHost][7a114…][reconnect] waiting for 5 seconds before reconnecting...
[2020-10-01 13:36:17.630] [renderer1] [info] [remote-connection][ExtensionHost][7a114…][reconnect] resolving connection...
[2020-10-01 13:36:17.630] [renderer1] [info] [remote-connection][ExtensionHost][7a114…][reconnect]
connecting to 127.0.0.1:59217...
[2020-10-01 13:36:17.643] [renderer1] [error] [remote-connection][ExtensionHost][7a114…][reconnect][127.0.0.1:59217] received error control message when negotiating connection. Error:
[2020-10-01 13:36:17.644] [renderer1] [error] Error: Connection error: Unknown reconnection token.
    at D (file:///C:/Users/x/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1907:697)
    at file:///C:/Users/x/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1900:478
    at c.fire (file:///C:/Users/x/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:96:67)
    at fire (file:///C:/Users/x/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:452:97)
    at t.PersistentProtocol._receiveMessage (file:///C:/Users/x/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:457:324)
    at file:///C:/Users/x/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:456:317
    at c.fire (file:///C:/Users/x/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:96:67)
    at g.acceptChunk (file:///C:/Users/x/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:449:445)
    at file:///C:/Users/x/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:448:796
    at Socket.t (file:///C:/Users/x/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:458:885)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
[2020-10-01 13:36:17.644] [renderer1] [error] [remote-connection][ExtensionHost][7a114…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
[2020-10-01 13:36:17.644] [renderer1] [error] Error: Connection error: Unknown reconnection token.
    at D (file:///C:/Users/x/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1907:697)
    at file:///C:/Users/x/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1900:478
    at c.fire (file:///C:/Users/x/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:96:67)
    at fire (file:///C:/Users/x/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:452:97)
    at t.PersistentProtocol._receiveMessage (file:///C:/Users/x/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:457:324)
    at file:///C:/Users/x/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:456:317
    at c.fire (file:///C:/Users/x/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:96:67)
    at g.acceptChunk (file:///C:/Users/x/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:449:445)
    at file:///C:/Users/x/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:448:796
    at Socket.t (file:///C:/Users/x/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:458:885)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
[2020-10-01 13:36:21.903] [renderer1] [warning] UNRESPONSIVE extension host, 'ms-vscode-remote.remote-ssh' took 56% of 5608ms, saved PROFILE here: 'C:\Users\x\AppData\Local\Temp\exthost-x.cpuprofile' [{"id":"gc","total":25000,"percentage":0},{"id":"ms-vscode-remote.remote-ssh","total":3137000,"percentage":56},{"id":"program","total":2422000,"percentage":43},{"id":"self","total":24000,"percentage":0}]
```

DEV-TOOLS:

![dev-tools](https://user-images.githubusercontent.com/2928659/94776987-e68b8300-03ec-11eb-9f95-f60c4827bdf5.png)

**Comment by roblourens** [comment]
This implies that the remote extension host crashed. What were you doing before this happened?

**Comment by ZhenyaKh** [comment]
> This implies that the remote extension host crashed. What were you doing before this happened?

I did not do anything special really. The only thing is that the day before yesterday a new version of vscode 1.49.2 got installed. Also, when I connect to a x86-64 remote server, it looks like I have no problems.

You know, I tried to remove the directory *C:\Users\x\\.vscode*. And it looked like it worked yesterday evening: I was leaving my computer with vscode being opened, e.g., for an hour and, when returning, I could see that it continued to work and my files could be saved without that "Cannot reconnect" message. But this morning it all repeated (I left my vscode opened for the night).

**Comment by alexdima** [comment]
> I was leaving my computer with vscode being opened, e.g., for an hour and, when returning, I could see that it continued to work and my remote files could be saved without that "Cannot reconnect" message.

> (I left my vscode opened for the night)

This is consistent with what we have implemented. The vscode server will wait for you to reconnect for 3 hours. If the client-side does not reconnect within 3 hours, the server side will kill all running processes and clean up any state associated with the client.

**Comment by ZhenyaKh** [comment]
But the problem is not solved by closing and re-opening vscode. I don't think it is normal to remove all the directories with settings every time when one wants to continue to work. This is not very nice to close my issue like that.

**Comment by alexdima** [comment]
> I don't think it is normal to remove all the directories with settings every time when one wants to continue to work. Anyway.

@ZhenyaKh I am confused by your statement. You don't need to remove any directories, you just need to press "Reload window" or open a new window to the ssh machine. Why do you need to remove directories?

**Comment by ZhenyaKh** [comment]
@alexdima , the problem is that neither "Close connection", nor "Reload window" helps. Also, pressing File->Close Remote Connection does not help. And no other ways I could imagine. When I reopen vscode, everything is repeated: I again see this pop-up window "Close connection"/"Reload window" . So the only way to solve this problem currently for me is to install 1.48.2 version. The new update 1.49.3, by the way, also did not help. So the problem is that I cannot get rid of the error pop-up message and cannot continue to edit/save my files.

**Comment by alexdima** [comment]
@roblourens What additional information would be necessary to troubleshoot this? The problem is that even after pressing "Reload window" the new window does not manage to connect to the remote SSH server and @ZhenyaKh mentions that there  is a need to delete all of `$HOME/.vscode-remote` to get things working again.

**Comment by roblourens** [comment]
Still a little confused about a couple things

- Does it totally work fine in 1.48 and the problem only exists in 1.49.* or is that not what you are saying?
- Do you always see that error about the reconnection token immediately or does it work sometimes or for some period of time?

Can you share the log from the Remote-SSH output channel after an instance where you click "Reload window" and it does not connect?

For the error in the original post, it's likely that the log will simply show a successful connection, but maybe it will give us some clue.
