### ISSUE TITLE
Unable to install VS Code Server on Windows Server Core 1903

### ISSUE THREAD

**Issue by michaelin** [microsoft/vscode-remote-release#3798]
- VSCode Version: 1.49.2
- Local OS Version: Windows 10 Enterprise (17763.1.amd64fre.rs5_release.180914-1434)
- Remote OS Version: Windows Server Core 1903 Datacenter (18362.1.amd64fre.19h1_release.190318-1202)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Install `Remote Development` extension on local machine.
2. Choose `Remote SSH - Connect to Host` and choose your target host connection.
3. After authentication the VS Code Server installation begins, but fails with `Resolver error: The VS Code Server failed to start`.

Does this issue occur when you try this locally?: No. It is a remote issue by nature. Unable to test locally.
Does this issue occur when you try this locally and all extensions are disabled?: No

*A little more context:*

* Logfile attached: [e5e9e69aed6e1984f7499b7af85b3d05f9a6883a.log](https://github.com/microsoft/vscode-remote-release/files/5325806/e5e9e69aed6e1984f7499b7af85b3d05f9a6883a.log)

* `Remote SSH` versions tried: 0.55.0, 0.51.0. For both versions, I've tried clean installations where I removed the .vscode-remote folder on the remote.

* Running `Code.cmd` manually on the remote fails in the same way:
```
PS C:\Users\mcian\.vscode-server\bin\e5e9e69aed6e1984f7499b7af85b3d05f9a6883a\bin> cmd.exe /C .\code.cmd
Error: Cannot find module 'minimist'
Require stack:
- C:\Users\mcian\.vscode-server\bin\e5e9e69aed6e1984f7499b7af85b3d05f9a6883a\out\bootstrap-amd.js
- C:\Users\mcian\.vscode-server\bin\e5e9e69aed6e1984f7499b7af85b3d05f9a6883a\out\vs\server\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at t.load (C:\Users\mcian\.vscode-server\bin\e5e9e69aed6e1984f7499b7af85b3d05f9a6883a\out\vs\loader.js:16:749)
    at e.load (C:\Users\mcian\.vscode-server\bin\e5e9e69aed6e1984f7499b7af85b3d05f9a6883a\out\vs\loader.js:13:941)
    at i (C:\Users\mcian\.vscode-server\bin\e5e9e69aed6e1984f7499b7af85b3d05f9a6883a\out\vs\loader.js:29:839)
    at Object.errorback (C:\Users\mcian\.vscode-server\bin\e5e9e69aed6e1984f7499b7af85b3d05f9a6883a\out\vs\loader.js:29:963)
    at e.triggerErrorback (C:\Users\mcian\.vscode-server\bin\e5e9e69aed6e1984f7499b7af85b3d05f9a6883a\out\vs\loader.js:14:306)
    at C:\Users\mcian\.vscode-server\bin\e5e9e69aed6e1984f7499b7af85b3d05f9a6883a\out\vs\loader.js:14:10
    at ReadFileContext.callback (C:\Users\mcian\.vscode-server\bin\e5e9e69aed6e1984f7499b7af85b3d05f9a6883a\out\vs\loader.js:17:221)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:239:13) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\mcian\\.vscode-server\\bin\\e5e9e69aed6e1984f7499b7af85b3d05f9a6883a\\out\\bootstrap-amd.js',
    'C:\\Users\\mcian\\.vscode-server\\bin\\e5e9e69aed6e1984f7499b7af85b3d05f9a6883a\\out\\vs\\server\\cli.js'
  ],
  phase: 'loading',
  moduleId: 'minimist',
  neededBy: [ 'vs/platform/environment/node/argv' ]
}
PS C:\Users\mcian\.vscode-server\bin\e5e9e69aed6e1984f7499b7af85b3d05f9a6883a\bin>
```

* The `minimist` module does exist on the remote:
```
PS C:\Users\mcian\.vscode-server> gci -Recurse minimist


    Directory: C:\Users\mcian\.vscode-server\bin\e5e9e69aed6e1984f7499b7af85b3d05f9a6883a\extensions\ms-vscode.node-debug2\node_modules


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        10/5/2020   7:46 AM                minimist


PS C:\Users\mcian\.vscode-server>
```

**Comment by roblourens** [comment]
Please try deleting it and reinstalling
