### ISSUE TITLE
Unable to install VS Code Server on Debian

### ISSUE THREAD

**Issue by st3g4n0** [microsoft/vscode-remote-release#3799]
- VSCode Version: 1.49.3
- Local OS Version: Windows_NT x64 10.0.19041
- Remote OS Version: Debian GNU/Linux 8 (jessie)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. ./vagrant ssh-config 
2. put the config ssh get from vagrant into the file config of Remote Development
3. connect

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

- Config SSH File:

```Host default
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile C:/Users/vladi/.vagrant.d/boxes/vpuente-VAGRANTSLASH-AOSUC/1.23/virtualbox/vagrant_private_key
  IdentitiesOnly yes
  LogLevel FATAL```


- Log:

```[13:23:13.861] Log Level: 2
[13:23:13.870] remote-ssh@0.55.0
[13:23:13.871] win32 x64
[13:23:13.873] SSH Resolver called for "ssh-remote+default", attempt 1
[13:23:13.874] SSH Resolver called for host: default
[13:23:13.874] Setting up SSH remote "default"
[13:23:13.901] Using commit id "2af051012b66169dde0c4dfae3f5ef48f787ff69" and quality "stable" for server
[13:23:13.903] Install and start server if needed
[13:23:15.038] Checking ssh with "ssh -V"
[13:23:15.080] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[13:23:15.088] Using SSH config file "C:\Users\vladi\Desktop\SOA\ssh-config"
[13:23:15.088] Running script with connection command: ssh -T -D 51987 -F "C:\Users\vladi\Desktop\SOA\ssh-config" default bash
[13:23:15.092] Terminal shell path: C:\Windows\System32\cmd.exe
[13:23:15.287] > 
[13:23:15.287] Got some output, clearing connection timeout
[13:23:15.383] > 44653e935a56: running
> 
[13:23:15.441] > Acquiring lock on /home/vagrant/.vscode-server/bin/2af051012b66169dde0c4dfae3f5e
> f48f787ff69/vscode-remote-lock.vagrant.2af051012b66169dde0c4dfae3f5ef48f787ff69
> Installing to /home/vagrant/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f
> 787ff69...
> 44653e935a56%%1%%
> Downloading with wget
> 
[13:23:16.860] > Acquiring lock on /home/vagrant/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/vscode-remote-lock.vagrant.2af051012b6616
> 9dde0c4dfae3f5ef48f787ff69
> Installing to /home/vagrant/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69...
> 44653e935a56%%1%%
> Downloading with wget
> 
> 
[13:23:18.010] > Download complete
> 44653e935a56%%2%%
> tar --version:
> tar (GNU tar) 1.27.1
> Copyright (C) 2013 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
> 
[13:23:18.474] > tar: Skipping to next header
> 
[13:23:18.911] > tar: Exiting with failure status due to previous errors
> WARNING: tar exited with non-0 exit code
[13:23:18.939] > 
> WARNING: /home/vagrant/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/server.sh doesn't exist. Download/untar may have f
> ailed.
> 
[13:23:19.006] > SHELL=/bin/bash
> SSH_CLIENT=10.0.2.2 51990 22
> USER=vagrant
> VSCODE_AGENT_FOLDER=/home/vagrant/.vscode-server
> PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
> MAIL=/var/mail/vagrant
> PWD=/home/vagrant
> LANG=en_US.UTF-8
> HOME=/home/vagrant
> SHLVL=2
> LOGNAME=vagrant
> SSH_CONNECTION=10.0.2.2 51990 10.0.2.15 22
> _=/usr/bin/printenv
> OLDPWD=/home/vagrant/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69
> Starting server with command... /home/vagrant/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/server.sh --host=127.0.0.1
> --enable-remote-auto-shutdown  --port=0 &> "/home/vagrant/.vscode-server/.2af051012b66169dde0c4dfae3f5ef48f787ff69.log" < /dev/null
> Waiting for server log...
> 
[13:23:19.534] > Waiting for server log...
> 
[13:23:20.038] > Waiting for server log...
> 
[13:23:20.537] > Waiting for server log...
> 
[13:23:21.035] > Waiting for server log...
> 
[13:23:21.571] > Waiting for server log...
> 
[13:23:22.070] > 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Server did not start successfully. Full server log at /home/vagrant/.vscode-server/.2af051012b66169dde0c4dfae3f5ef48f787ff69.log >>>
> bash: line 386: /home/vagrant/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/server.sh: No such file or directory
> <<< End of server log
> 44653e935a56##32##
> 
[13:23:22.071] Received install output: 44653e935a56##32##
[13:23:22.076] Resolver error: Error: The VS Code Server failed to start
	at Function.ExitCode (c:\Users\vladi\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:130495)
	at Object.t.handleInstallOutput (c:\Users\vladi\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:128732)
	at I (c:\Users\vladi\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:106775)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\vladi\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:104774
	at async Object.t.withShowDetailsEvent (c:\Users\vladi\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:109845)
	at async Object.t.resolve (c:\Users\vladi\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107960)
	at async c:\Users\vladi\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:141955
[13:23:22.081] ------




[13:23:22.529] "install" terminal command done
[13:23:22.530] Install terminal quit with output: ```

**Comment by roblourens** [comment]
Please try running the command "Uninstall VS Code Server on Host" and trying again
