### ISSUE TITLE
I can connect the service machine ,but can not open some folder

### ISSUE THREAD

**Issue by hit-joseph** [microsoft/vscode-remote-release#3801]
```
[23:27:26.809] Log Level: 2
[23:27:26.813] remote-ssh@0.55.0
[23:27:26.813] win32 x64
[23:27:26.815] SSH Resolver called for "ssh-remote+grey_recall-45.255.133.221", attempt 1
[23:27:26.816] SSH Resolver called for host: grey_recall-45.255.133.221
[23:27:26.816] Setting up SSH remote "grey_recall-45.255.133.221"
[23:27:26.844] Using commit id "2af051012b66169dde0c4dfae3f5ef48f787ff69" and quality "stable" for server
[23:27:26.851] Install and start server if needed
[23:27:26.864] Checking ssh with "ssh -V"
[23:27:27.008] > OpenSSH_7.9p1, OpenSSL 1.1.1a  20 Nov 2018

[23:27:27.034] Running script with connection command: ssh -T -D 13421 grey_recall-45.255.133.221 bash
[23:27:27.038] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[23:27:27.257] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\WINDOWS\System32\cmd.exe
[23:27:27.258] Got some output, clearing connection timeout
[23:27:27.379] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[23:27:27.393] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[23:27:28.776] > 
[23:27:28.835] > 473a823fca97: running
> 
[23:27:28.875] > 
[23:27:28.907] > cat: /data/services/libs/lib32/libstdc++.so.6
[23:27:28.913] > cat: /data/services/libs/lib32/libstdc++.so.6Acquiring lock on /home/yanxin/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/vscode-remote-lock.yan
> xin.2af051012b66169dde0c4dfae3f5ef48f787ff69
> Found existing installation at /home/yanxin/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69...
[23:27:28.980] > 
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status on port 30915 with wget
> 473a823fca97: start
> : Permission denied
> 
[23:27:29.036] > 
[23:27:29.043] > sshAuthSock====      
> listeningOn==30915== 
> osReleaseId==ubuntu==
> arch==x86_64==
> webUiAccessToken====
> tmpDir==/run/user/1205==
> platform==linux==
> 473a823fca97: end
[23:27:29.043] Received install output: 
: Permission denied
sshAuthSock====      
listeningOn==30915== 
osReleaseId==ubuntu==
arch==x86_64==
webUiAccessToken====
tmpDir==/run/user/1205==
platform==linux==

[23:27:29.050] Resolver error: Error: Permission denied
	at Function.Create (c:\Users\10520\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:130564)
	at c:\Users\10520\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:127202
	at Object.t.handleInstallOutput (c:\Users\10520\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:127485)
	at I (c:\Users\10520\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:106775)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\10520\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:104774
	at async Object.t.withShowDetailsEvent (c:\Users\10520\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:109845)
	at async Object.t.resolve (c:\Users\10520\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107960)
	at async c:\Users\10520\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:141955
[23:27:29.059] ------




[23:27:29.093] > 
> 
-------------------
```

logs like this , which shows "Permission denied"

**Comment by roblourens** [comment]
Sorry I have no clue where that message is coming from or why it's injected into the middle of this echo.
