### ISSUE TITLE
Remote SSH: Times out after successfully connecting (even on bash shell) 

### ISSUE THREAD

**Issue by XintianS** [microsoft/vscode-remote-release#3810]
- VSCode Version: 1.49.3 (latest)
- Local OS Version: Ubuntu 18.04.4 LTS
- Remote OS Version: Ubuntu 18.04.4 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. SSH directly into the remote machine (**works fine**)
2. Running remote-ssh through vscode by `"remote.SSH.useLocalServer": false` keeps idling forever
3. Running remote-ssh through vscode by `"remote.SSH.useLocalServer": true` gives following error **(after successful ssh connection)** :

```
> [15:45:06.919] Log Level: 2
> [15:45:06.920] remote-ssh@0.55.0
> [15:45:06.920] linux x64
> [15:45:06.921] SSH Resolver called for "ssh-remote+192.168.6.9", attempt 1
> [15:45:06.921] SSH Resolver called for host: 192.168.6.9
> [15:45:06.921] Setting up SSH remote "192.168.6.9"
> [15:45:06.923] Acquiring local install lock: /tmp/vscode-remote-ssh-192.168.6.9-install.lock
> [15:45:06.930] Looking for existing server data file at /home/xintian/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-192.168.6.9-2af051012b66169dde0c4dfae3f5ef48f787ff69-0.55.0/data.json
> [15:45:06.930] Using commit id "2af051012b66169dde0c4dfae3f5ef48f787ff69" and quality "stable" for server
> [15:45:06.932] Install and start server if needed
> [15:45:06.933] Checking ssh with "ssh -V"
> [15:45:06.939] > OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
> 
> [15:45:06.955] askpass server listening on /run/user/1000/vscode-ssh-askpass-688703070bb2438ce830967eda6c6a463d246dd1.sock
> [15:45:06.956] Spawning local server with {"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-1c980c0faab6b7872607bbfc58d40facf3650666.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","36069","-o","ConnectTimeout=30","192.168.6.9"],"dataFilePath":"/home/xintian/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-192.168.6.9-2af051012b66169dde0c4dfae3f5ef48f787ff69-0.55.0/data.json"}
> [15:45:06.956] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/xintian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/xintian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-688703070bb2438ce830967eda6c6a463d246dd1.sock"}
> [15:45:06.959] Spawned 21106
> [15:45:07.017] > local-server> Spawned ssh: 21114
> [15:45:07.020] stderr> OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
> [15:45:07.155] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:G5jxcrCHTjqSlD+FsGBbEPbOCyoShjrDU9UNTjoByBA
> [15:45:07.287] stderr> Load key "/home/xintian/Desktop/local_server.pem": invalid format
> [15:45:07.370] Got askpass request: {"request":"aiuser@192.168.6.9's password:"}
> [15:45:07.370] Showing password prompt
> [15:45:07.371] Listening for interwindow password on /run/user/1000/vscode-ssh-askpass-acd5dbcefdbed9dbae0bbf0e359ebe8f721e8e6c.sock
> [15:45:07.371] Writing password prompt to globalState
> [15:45:10.344] Got password response
> [15:45:10.344] Interactor gave response: *************
> [15:45:10.345] Cleaning up other-window auth server
> **[15:45:10.401] stderr> Authenticated to 192.168.6.9 ([192.168.6.9]:22).**
> **[15:45:10.603] > Welcome to Ubuntu 18.04.4 LTS (GNU/Linux 5.4.0-48-generic x86_64)**
> > 
> >  * Documentation:  https://help.ubuntu.com
> >  * Management:     https://landscape.canonical.com
> >  * Support:        https://ubuntu.com/advantage
> > 

> [15:45:10.621] > ready: c568bda91b3d
> [15:45:10.649] > Linux 5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020
> [15:45:10.651] Platform: linux
> [15:45:42.351] Terminating local server
> [15:45:42.384] Resolver error: Error: Connecting with SSH timed out
> 	at Function.Timeout (/home/xintian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:130714)
> 	at Timeout._onTimeout (/home/xintian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:325959)
> 	at listOnTimeout (internal/timers.js:531:17)
> 	at processTimers (internal/timers.js:475:7)
> [15:45:42.386] Local server exit: 15
> [15:45:42.388] ------
> 
```

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by XintianS** [comment]
Update: If I use another internet connection then I can connect via remote-ssh. Through my own internet connection ssh directly into the remote machine works, do not know why via vscode remote-ssh is not working. Any help is appreciated. Thanks.

**Comment by roblourens** [comment]
It's possible that the install script is getting mangled or lost or something else. It runs one line then stops.
