### ISSUE TITLE
Server did not start successfully - server.sh: No such file or directory

### ISSUE THREAD

**Issue by rgranit** [microsoft/vscode-remote-release#3818]
Hi all, 

I saw a few previous posts describing similar issues, but it seems that in all cases the solution came after updating to the latest version of the addon, and I'm using the latest version..

These are my technical spec:
- VSCode Version: 1.49.3
- Local OS Version: MacOS 10.15.7
- Remote OS Version: Centos 8
- Remote Extension/Connection Type: SSH version 0.55.0

Steps to Reproduce:

Connecting to the remote server via the ssh gives the following issue:
`[14:19:14.552] > Starting server with command... /home/royg/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/home/royg/.vscode-server/.2af051012b66169dde0c4dfae3f5ef48f787ff69.log" < /dev/null
> Waiting for server log...
[14:19:15.123] > Waiting for server log...
[14:19:15.640] > Waiting for server log...
[14:19:16.051] > Waiting for server log...
[14:19:16.562] > Waiting for server log...
[14:19:17.067] > Waiting for server log...
[14:19:17.583] > Waiting for server log...
[14:19:18.097] > Waiting for server log...
[14:19:18.632] >  
> *
[14:19:18.633] > * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> Server did not start successfully. Full server log at /home/royg/.vscode-server/.2af051012b66169dde0c4dfae3f5ef48f787ff69.log >>>
> bash: line 387: /home/royg/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/server.sh: No such file or directory
> <<< End of server log
> 47166969ceae##32##
[14:19:18.633] Received install output: 47166969ceae##32##
[14:19:18.635] Terminating local server
[14:19:18.645] Resolver error: Error: The VS Code Server failed to start
	at Function.ExitCode (/Users/royg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:130495)
	at Object.t.handleInstallOutput (/Users/royg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:128732)
	at Object.t.tryInstallWithLocalServer (/Users/royg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:102339)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /Users/royg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:104310
	at async Object.t.withShowDetailsEvent (/Users/royg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:109845)
	at async /Users/royg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100912
	at async R (/Users/royg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:97702)
	at async Object.t.resolveWithLocalServer (/Users/royg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100561)
	at async Object.t.resolve (/Users/royg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:107840)
	at async /Users/royg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:141955
[14:19:18.648] Local server exit: 15
[14:19:18.651] ------`

Any suggestions?

Thanks! 🙏
Roy

**Comment by wayne1204** [comment]
same issue here

**Comment by rgranit** [comment]
It appear that the extension removes the 'server.sh' file prematurely

**Comment by YusufMohammedUH** [comment]
I have the same issue.

These are my technical spec:
- VSCode Version: 1.49.3
- Local OS Version: Ubuntu 20.04
- Remote OS Version: Ubuntu 16.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. connect to remote server via remote-ssh
2. disconnect and try to reconnect

`[20:46:05.825] Log Level: 2
[20:46:05.827] remote-ssh@0.55.0
[20:46:05.827] linux x64
[20:46:05.829] SSH Resolver called for "ssh-remote+login1", attempt 1
[20:46:05.830] SSH Resolver called for host: login1
[20:46:05.830] Setting up SSH remote "login1"
[20:46:05.839] Using commit id "2af051012b66169dde0c4dfae3f5ef48f787ff69" and quality "stable" for server
[20:46:05.841] Install and start server if needed
[20:46:05.844] Checking ssh with "ssh -V"
[20:46:05.854] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020

[20:46:05.856] Running script with connection command: ssh -T -D 34129 -o ConnectTimeout=15 login1 bash
[20:46:06.477] > username@remote's password: 
[20:46:06.477] Got some output, clearing connection timeout
[20:54:20.701] > 
> Connection closed by 134.100.105.240 port 22
[20:54:21.051] "install" terminal command done
[20:54:21.052] Install terminal quit with output: Connection closed by xxx.xxx.xxx.xxx port 22
[20:54:21.052] Received install output: Connection closed by xxx.xxx.xxx.xxx port 22
[20:54:21.053] Stopped parsing output early. Remaining text: Connection closed by xxx.xxx.xxx.xxx port 22
[20:54:21.053] Failed to parse remote port from server output
[20:54:21.071] Resolver error: Error: 
	at Function.Create (~/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:130564)
	at Object.t.handleInstallOutput (~/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:127671)
	at I (~/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:106775)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async ~/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:104774
	at async Object.t.withShowDetailsEvent (~/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:109845)
	at async Object.t.resolve (~/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:107960)
	at async ~.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:141955
[20:54:21.078] ------

[20:54:22.131] Unhandled rejection: TypeError: Cannot read property 'onDidEndTour' of undefined
    at Object.t.onDidEndTour (~/.vscode/extensions/vsls-contrib.gistfs-0.1.8/out/prod/extension.js:31:144864)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[20:54:22.974] Unhandled rejection: Error: API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at l (~/.vscode/extensions/vsls-contrib.gistfs-0.1.8/out/prod/extension.js:321:1209)
    at ~/.vscode/extensions/vsls-contrib.gistfs-0.1.8/out/prod/extension.js:321:2258
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at v (~/.vscode/extensions/vsls-contrib.gistfs-0.1.8/out/prod/extension.js:16:91285)
    at async Promise.all (index 2)
    at Module.<anonymous> (~/.vscode/extensions/vsls-contrib.gistfs-0.1.8/out/prod/extension.js:16:95836)
    at Object.t.refreshShowcase (~/.vscode/extensions/vsls-contrib.gistfs-0.1.8/out/prod/extension.js:16:95539)`

When locking at the remoteagent.log I get:

`[2020-10-12 20:45:03.567] [remoteagent] [info] 

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


[2020-10-12 20:45:03.567] [remoteagent] [info] Extension host agent started.
[2020-10-12 20:45:07.591] [remoteagent] [info] [127.0.0.1][8e2c320e][ManagementConnection] New connection established.
[2020-10-12 20:45:07.602] [remoteagent] [info] [127.0.0.1][f1f2d4a9][ExtensionHostConnection] New connection established.
[2020-10-12 20:45:08.818] [remoteagent] [info] [127.0.0.1][f1f2d4a9][ExtensionHostConnection] <13253> Launched Extension Host Process.
[2020-10-12 20:45:10.615] [remoteagent] [info] [127.0.0.1][8e2c320e][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[2020-10-12 20:45:13.563] [remoteagent] [error] Error: EACCES: permission denied, scandir '~/.vscode-server/data/logs'
[2020-10-12 20:45:25.575] [remoteagent] [info] [127.0.0.1][8e2c320e][ManagementConnection] Another client has connected, will shorten the wait for reconnection 5m before disposing...
[2020-10-12 20:45:25.576] [remoteagent] [info] [127.0.0.1][8e9c64f0][ManagementConnection] New connection established.
[2020-10-12 20:45:25.582] [remoteagent] [info] [127.0.0.1][ee3935e2][ExtensionHostConnection] New connection established.
[2020-10-12 20:45:25.593] [remoteagent] [info] [127.0.0.1][ee3935e2][ExtensionHostConnection] <undefined> Launched Extension Host Process.
[2020-10-12 20:45:25.593] [remoteagent] [error] [127.0.0.1][ee3935e2][ExtensionHostConnection] <undefined> Extension Host Process had an error
[2020-10-12 20:45:25.595] [remoteagent] [error] Error: spawn ~/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/node EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[2020-10-12 20:45:25.664] [remoteagent] [error] ~/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/extensions {"errno":-13,"code":"EACCES","syscall":"scandir","path":"~/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/extensions"}
[2020-10-12 20:45:25.664] [remoteagent] [error] ~/.vscode-server/extensions {"errno":-13,"code":"EACCES","syscall":"scandir","path":"~/.vscode-server/extensions"}
[2020-10-12 20:45:26.302] [remoteagent] [error] [File Watcher (node.js)] Error: EACCES: permission denied, stat '~/.vscode-server/data/Machine'
[2020-10-12 20:45:30.771] [remoteagent] [error] [127.0.0.1][ee3935e2][ExtensionHostConnection] Unknown reconnection token.
[2020-10-12 20:45:51.332] [remoteagent] [info] [127.0.0.1][8e9c64f0][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...`

I logged in to the remote server via ssh and noticed that remote-ssh starts node.js
processes, which do not terminate after the remote connection is closed.

The issue could be solved by killing all node processes started by remote-ssh and reconnecting.

**Comment by rgranit** [comment]
@YusufMohammedUH It seems like your issue is a bit different, as your log does not indicate you are missing the 'server.sh' file..

**Comment by YusufMohammedUH** [comment]
@rgranit  Sorry. That's true. Should I look for an other issue matching mine?

**Comment by wayne1204** [comment]
I have solved the issue by removing .vscode-server/ folder and manually download the vscode server file.
Below is the command.

$ wget -O vscode-server-linux-x64.tar.gz https://update.code.visualstudio.com/commit:<commit-version>/server-linux-x64/stable
$ tar zxvf vscode-server-linux-x64.tar.gz
$ cp vscode-server-linux-x64/* .vscode-server/

Hope it will help!

**Comment by rgranit** [comment]
Thanks @wayne1204 I tried your suggestion but I get the following error:
`-sh-4.2$ wget -O vscode-server-linux-x64.tar.gz https://update.code.visualstudio.com/commit:/server-linux-x64/stable/
--2020-10-13 09:52:13--  https://update.code.visualstudio.com/commit:/server-linux-x64/stable/
Resolving update.code.visualstudio.com (update.code.visualstudio.com)... 51.144.164.215
Connecting to update.code.visualstudio.com (update.code.visualstudio.com)|51.144.164.215|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-13 09:52:14 ERROR 404: Not Found.`

Any suggestions?

**Comment by imxxw** [comment]
Remove the folder "~/.vscode-server" in the remote server, and open vscode to connect the remote server with remote-ssh.

> Hi all,
> 
> I saw a few previous posts describing similar issues, but it seems that in all cases the solution came after updating to the latest version of the addon, and I'm using the latest version..
> 
> These are my technical spec:
> 
> * VSCode Version: 1.49.3
> * Local OS Version: MacOS 10.15.7
> * Remote OS Version: Centos 8
> * Remote Extension/Connection Type: SSH version 0.55.0
> 
> Steps to Reproduce:
> 
> Connecting to the remote server via the ssh gives the following issue:
> `[14:19:14.552] > Starting server with command... /home/royg/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown --port=0 &> "/home/royg/.vscode-server/.2af051012b66169dde0c4dfae3f5ef48f787ff69.log" < /dev/null
> 
> > Waiting for server log...
> > [14:19:15.123] > Waiting for server log...
> > [14:19:15.640] > Waiting for server log...
> > [14:19:16.051] > Waiting for server log...
> > [14:19:16.562] > Waiting for server log...
> > [14:19:17.067] > Waiting for server log...
> > [14:19:17.583] > Waiting for server log...
> > [14:19:18.097] > Waiting for server log...
> > [14:19:18.632] >
> > *
> > [14:19:18.633] > * Reminder: You may only use this software with Visual Studio family products,
> > 
> > * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> > 
> > 
> > Server did not start successfully. Full server log at /home/royg/.vscode-server/.2af051012b66169dde0c4dfae3f5ef48f787ff69.log >>>
> > bash: line 387: /home/royg/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/server.sh: No such file or directory
> > <<< End of server log
> > 47166969ceae##32##
> > [14:19:18.633] Received install output: 47166969ceae##32##
> > [14:19:18.635] Terminating local server
> > [14:19:18.645] Resolver error: Error: The VS Code Server failed to start
> > at Function.ExitCode (/Users/royg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:130495)
> > at Object.t.handleInstallOutput (/Users/royg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:128732)
> > at Object.t.tryInstallWithLocalServer (/Users/royg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:102339)
> > at processTicksAndRejections (internal/process/task_queues.js:94:5)
> > at async /Users/royg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:104310
> > at async Object.t.withShowDetailsEvent (/Users/royg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:109845)
> > at async /Users/royg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100912
> > at async R (/Users/royg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:97702)
> > at async Object.t.resolveWithLocalServer (/Users/royg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100561)
> > at async Object.t.resolve (/Users/royg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:107840)
> > at async /Users/royg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:141955
> > [14:19:18.648] Local server exit: 15
> > [14:19:18.651] ------`
> 
> Any suggestions?
> 
> Thanks! 🙏
> Roy

Remove the folder "~/.vscode-server" in the remote server, and open vscode to connect the remote server with remote-ssh.

**Comment by rgranit** [comment]
Thanks @imxxw I have tried that but it does not work.. I ended up installing in manually as I've mentioned above..

> Thanks @wayne1204 I tried your suggestion together with the [following guide](https://medium.com/@debugger24/installing-vscode-server-on-remote-machine-in-private-network-offline-installation-16e51847e275) and it worked!
> 
> But I still believe there is an issue with the extension, since this should work automatically

I guess this is a sensible solution to this problem, but I did not close the issue since I believe that there is some issue preventing vscode-server from bing installed automatically in certain cases

**Comment by roblourens** [comment]
Please try running the command "Uninstall VS Code Server on Host" and try again. if that doesn't work, please share teh full log

**Comment by rgranit** [comment]
@roblourens unfortunately the log file suggested by the output (`/home/royg/.vscode-server/.2af051012b66169dde0c4dfae3f5ef48f787ff69.log`) does not exist :(
