### ISSUE TITLE
ssh client oftens doens't find ssh, but after a number of attempts it works

### ISSUE THREAD

**Issue by EmbeddedBacon** [microsoft/vscode-remote-release#3833]
- VSCode Version: 1.50 (user)
- Local OS Version: Windows 10 Enterprise
- Remote OS Version: CentOS v7
- Remote Extension/Connection Type: ssh, extension version 0.55.0

Often, after closing down VSCode and launching it later result is the error of "Resolver error: Error: ssh installation not found".  The following is in the log

[15:24:38.767] Log Level: 2
[15:24:38.778] remote-ssh@0.55.0
[15:24:38.779] win32 x64
[15:24:38.812] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a224952562d5554492d3132227d", attempt 1
[15:24:38.815] SSH Resolver called for host: __remote_machine__
[15:24:38.816] Setting up SSH remote "__remote_machine__"
[15:24:38.868] Using commit id "93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3" and quality "stable" for server
[15:24:38.876] Install and start server if needed
[15:24:38.893] Checking ssh with "ssh -V"
[15:24:44.267] ssh is not exiting, continuing
[15:24:44.317] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[15:24:45.210] Got error from ssh: spawn C:\WINDOWS\System32\OpenSSH\ssh.exe ENOENT
[15:24:45.216] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[15:24:45.300] Got error from ssh: spawn C:\Program Files\Git\usr\bin\ssh.exe ENOENT
[15:24:45.311] Checking ssh with "C:\Program Files (x86)\Git\usr\bin\ssh.exe -V"
[15:24:45.356] Got error from ssh: spawn C:\Program Files (x86)\Git\usr\bin\ssh.exe ENOENT
[15:24:45.361] Finding installed ssh failed: ssh installation not found
[15:24:46.978] Resolver error: Error: ssh installation not found
	at _ (c:\Users\__user__\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:242296)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at runNextTicks (internal/process/task_queues.js:63:3)
	at processTimers (internal/timers.js:472:9)
	at async O (c:\Users\__user__\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:238805)
	at async C (c:\Users\__user__\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:238714)
	at async Object.t.generateMultiLineCommand (c:\Users\__user__\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:240084)
	at async q (c:\Users\__user__\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107417)
	at async c:\Users\__user__\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:104810
	at async Object.t.withShowDetailsEvent (c:\Users\__user__\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:109845)
	at async Object.t.resolve (c:\Users\__user__\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107960)
	at async c:\Users\__user__\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:141955

After a number of attempts it will finally work

`[15:37:18.984] Log Level: 2
[15:37:18.986] remote-ssh@0.55.0
[15:37:18.988] win32 x64
[15:37:18.994] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a224952562d5554492d3132227d", attempt 1
[15:37:18.995] SSH Resolver called for host: __remote_machine__
[15:37:18.995] Setting up SSH remote "__remote_machine__"
[15:37:19.030] Using commit id "93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3" and quality "stable" for server
[15:37:19.033] Install and start server if needed
[15:37:19.050] Checking ssh with "ssh -V"
[15:37:21.090] > OpenSSH_8.2p1, OpenSSL 1.1.1d  10 Sep 2019

[15:37:21.110] Running script with connection command: ssh -T -D 61897 __remote_machine__ bash
[15:37:21.117] Terminal shell path: C:\WINDOWS\System32\cmd.exe`

Is there a timeout associated with this test?  Can that time out be adjusted?  The only way I know to measure execution time is to use PowerShell with an output of the longest time I saw after 10 tests.

`PS C:\Users\__user__> Measure-Command {ssh -V}
OpenSSH_8.2p1, OpenSSL 1.1.1d  10 Sep 2019

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 23
Ticks             : 10238692
TotalDays         : 1.1850337962963E-05
TotalHours        : 0.000284408111111111
TotalMinutes      : 0.0170644866666667
TotalSeconds      : 1.0238692
TotalMilliseconds : 1023.8692`

A co-worker sees the following

[16:42:24.031] Log Level: 2
[16:42:24.051] remote-ssh@0.55.0
[16:42:24.052] win32 x64
[16:42:24.054] SSH Resolver called for "ssh-remote+__remote_machine__", attempt 1
[16:42:24.054] SSH Resolver called for host:__remote_machine__
[16:42:24.054] Setting up SSH remote "__remote_machine__"
[16:42:24.101] Using commit id "2af051012b66169dde0c4dfae3f5ef48f787ff69" and quality "stable" for server
[16:42:24.103] Install and start server if needed
[16:42:24.112] Checking ssh with "ssh -V"
[16:42:24.437] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
 
[16:42:24.471] Running script with connection command: ssh -T -D 64749 __remote_machine__ bash
[16:42:24.479] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[16:42:24.756] > 
> 
> �]0;C:\WINDOWS\System32\cmd.exe�
[16:42:24.757] Got some output, clearing connection timeout
[16:42:24.773] > 'ssh' is not recognized as an internal or external command,
> operable program or batch file.
> 
[16:42:24.785] > 'ssh' is not recognized as an internal or external command,
> operable program or batch file.

It is like it found OpenSSH, but then can't execute it.

**Comment by nextcoder** [comment]
This is similar to the bug report that I opened 22 days ago:

https://github.com/microsoft/vscode-remote-release/issues/3704#issue-705678555

The timeout for checking the existence of the ssh command should be adjustable.

**Comment by EmbeddedBacon** [comment]
@nextcoder, yes, this has been an issue for a number of months now.  Hopefully the team will make this a configurable item

**Comment by EmbeddedBacon** [comment]
One method to work around this is once VSCode times out is to leave the VSCode open then connect to the remote machine.  The problem with this is that I lose all history of what files were open and I need to reopen all the files I had opened.

**Comment by bamurtaugh** [comment]
Thanks for opening this @EmbeddedBacon. As the request here appears to be related to timeout, closing in favor of #3704 to avoid dupes. If I've missed anything or you have further questions/feedback, please just let me know, and I'd be happy to reopen this issue.

**Comment by EmbeddedBacon** [comment]
@bamurtaugh, no worries.  I did search for a similar ticket, but I just didn't use the correct keywords.  @nextcoder did find this one so I was able to follow his.  This issue has been ongoing for some time and truly hope it gets assigned and worked on quickly.  It is very annoying and I know a lot of my friends run into this frequently.

**Comment by EmbeddedBacon** [comment]
@bamurtaugh , did you view the second test case I referenced in this ticket?  The other issue my co-worker ran into wasn't the the time-out, but the script did find ssh, logs the message of "'ssh' is not recognized as an internal or external command" even though it was found.  So this is a different case and probably should remain open or I can create a separate ticket for that case?

**Comment by bamurtaugh** [comment]
@EmbeddedBacon Thank you for the follow-up here! I think it'd make sense to create a separate ticket just for the case your coworker is running into so that it can stand out on its own.
