### ISSUE TITLE
vs code wsl error

### ISSUE THREAD

**Issue by sparrow84001** [microsoft/vscode-remote-release#3838]
log
-----------------------------------------------
[2020-10-03 19:49:03.309] Resolving wsl+Ubuntu, resolveAttempt: 1
[2020-10-03 19:49:03.405] Starting VS Code Server inside WSL (Ubuntu)
[2020-10-03 19:49:03.405] Extension version: 0.44.5, Windows build: 19042. Multi distro support: available. WSL path support: enabled
[2020-10-03 19:49:03.616] Connecting to daemon started by other Remote-WSL window... 4.4.0-19041-Microsoft Ubuntu
[2020-10-03 19:49:03.616] WSL resolver response: 127.0.0.1:52157
[2020-10-03 19:49:03.616] To debug connection issues, open a local browser on http://127.0.0.1:52157/version

2af051012b66169dde0c4dfae3f5ef48f787ff69
error
-----------------------------------------------
Could not fetch remote environment
Failed to connect to the remote extension host server (Error: handshake timeout)
Unable to open 'l4': Unable to read file 'vscode-remote://wsl+ubuntu/home/l4' (Error: handshake timeout).

**Comment by sparrow84001** [comment]
noo

**Comment by sparrow84001** [comment]
log
----------------------------------
[2020-10-12 18:20:53.627] [renderer5] [error] write ECONNRESET: Error: write ECONNRESET
    at afterWriteDispatched (internal/stream_base_commons.js:149:25)
    at writeGeneric (internal/stream_base_commons.js:140:3)
    at Socket._writeGeneric (net.js:776:11)
    at Socket._write (net.js:788:8)
    at doWrite (_stream_writable.js:435:12)
    at writeOrBuffer (_stream_writable.js:419:5)
    at Socket.Writable.write (_stream_writable.js:309:11)
    at u.write (file:///C:/Users/Sparrow/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:461:824)
    at p._writeNow (file:///C:/Users/Sparrow/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:453:321)
    at Immediate._onImmediate (file:///C:/Users/Sparrow/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:453:259)
    at processImmediate (internal/timers.js:439:21)
[2020-10-12 18:21:03.608] [renderer5] [error] [remote-connection][Management   ][421ce…][initial][127.0.0.1:54747] the handshake took longer than 10 seconds. Error:
[2020-10-12 18:21:03.608] [renderer5] [error] Error: handshake timeout
    at file:///C:/Users/Sparrow/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1901:589
[2020-10-12 18:21:03.609] [renderer5] [error] [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
[2020-10-12 18:21:03.609] [renderer5] [error] Error: handshake timeout
    at file:///C:/Users/Sparrow/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1901:589
[2020-10-12 18:21:03.683] [renderer5] [error] handshake timeout: Error: handshake timeout
    at file:///C:/Users/Sparrow/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1901:589
[2020-10-12 18:21:05.855] [renderer5] [error] Could not fetch remote environment: Error: Could not fetch remote environment
    at d.start (file:///C:/Users/Sparrow/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5251:291)
    at async k.createProcess (file:///C:/Users/Sparrow/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5271:76)
[2020-10-12 18:21:07.578] [renderer5] [error] handshake timeout: Error: handshake timeout
    at file:///C:/Users/Sparrow/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1901:589
[2020-10-12 18:21:08.608] [renderer5] [error] handshake timeout: Error: handshake timeout
    at file:///C:/Users/Sparrow/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1901:589
[2020-10-12 18:21:13.662] [renderer5] [error] handshake timeout: Error: handshake timeout
    at file:///C:/Users/Sparrow/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1901:589
[2020-10-12 18:21:37.447] [renderer5] [error] handshake timeout: Error: handshake timeout
    at file:///C:/Users/Sparrow/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1901:589
[2020-10-12 18:21:39.790] [renderer5] [error] handshake timeout: Error: handshake timeout
    at file:///C:/Users/Sparrow/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1901:589
[2020-10-12 18:21:47.284] [renderer5] [error] handshake timeout: Error: handshake timeout
    at file:///C:/Users/Sparrow/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1901:589
[2020-10-12 18:21:57.056] [renderer5] [error] handshake timeout: Error: handshake timeout
    at file:///C:/Users/Sparrow/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1901:589

**Comment by aeschli** [comment]
Is this still a problem? Please speak up.
