### ISSUE TITLE
Could not establish connection to "(my sever)": The VS Code Server failed to start."

### ISSUE THREAD

**Issue by jdrecoulle0001** [microsoft/vscode-remote-release#3846]
- VSCode Version: 1.50.0
- Local OS Version: Windows 10 Home 2004 Build: 19041.508
- Remote OS Version: Ubuntu 20.04.1 LTS Release: 20.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Command Palette
2. Remote-SSH: Connect to Host...
3. Enter password

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

When I try to connect to my Linux server using Remote-SSH extension, after entering my password, VS Code alerts me of failure with message: "Could not establish connection to "elnux1.cs.umass.edu": The VS Code Server failed to start." Remote-SSH worked fine before, but all of sudden this issue happened while I was writing a program. I can still ssh into the server fine through Windows PowerShell.

Here is the log, below. Let me know if I need to provide any further information. Thank you!

```
[10:41:26.968] Log Level: 2
[10:41:26.971] remote-ssh@0.55.0
[10:41:26.971] win32 x64
[10:41:26.972] SSH Resolver called for "ssh-remote+elnux1.cs.umass.edu", attempt 1
[10:41:26.972] SSH Resolver called for host: elnux1.cs.umass.edu
[10:41:26.972] Setting up SSH remote "elnux1.cs.umass.edu"
[10:41:26.981] Using commit id "93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3" and quality "stable" for server
[10:41:26.982] Install and start server if needed
[10:41:26.983] Checking ssh with "ssh -V"
[10:41:27.004] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[10:41:27.006] Running script with connection command: ssh -T -D 60764 elnux1.cs.umass.edu bash
[10:41:27.007] Terminal shell path: C:\Windows\System32\cmd.exe
[10:41:27.209] > Password:]0;C:\Windows\System32\cmd.exe
[10:41:27.209] Got some output, clearing connection timeout
[10:41:27.209] Showing password prompt
[10:41:31.123] Got password response
[10:41:31.123] "install" wrote data to terminal: "************"
[10:41:31.134] > 
[10:41:31.866] > e8b4217ccdf8: running
[10:41:31.924] > Acquiring lock on /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf
> 16c5a4b10e4d5f89737d9c2c25488a3/vscode-remote-lock.jrecoulle.93c2f0fbf16c5a4b10e
> 4d5f89737d9c2c25488a3
[10:41:31.933] > Found existing installation at /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/
> bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3...
[10:41:31.987] > SHELL=/bin/bash
> KRB5CCNAME=KEYRING:persistent:35904
> PWD=/nfs/elsrv4/users2/grad/jrecoulle
> LOGNAME=jrecoulle
> XDG_SESSION_TYPE=tty
> MOTD_SHOWN=pam
> HOME=/nfs/elsrv4/users2/grad/jrecoulle
> LANG=C.UTF-8
> VSCODE_AGENT_FOLDER=/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server
> SSH_CONNECTION=73.238.133.148 60766 128.119.243.147 22
> XDG_SESSION_CLASS=user
> USER=jrecoulle
> WWW_HOME=http://edlab-www.cs.umass.edu/
> SHLVL=1
> XDG_SESSION_ID=43544
> XDG_RUNTIME_DIR=/run/user/35904
> SSH_CLIENT=73.238.133.148 60766 22
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin/:/us
> r/games:/usr/local/games:/usr/ucb:/usr/bin/X11:/usr/bin:/bin:/usr/sbin:/usr/loca
> l/bin:/exp/rcf/share/bin
> DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/35904/bus
> MAIL=/var/spool/mail/jrecoulle
> _=/usr/bin/printenv
> Starting server with command... /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server
> /bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/server.sh --host=127.0.0.1 --enabl
> e-remote-auto-shutdown  --port=0 &> "/nfs/elsrv4/users2/grad/jrecoulle/.vscode-s
> erver/.93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3.log" < /dev/null
[10:41:32.010] > 
> Waiting for server log...
[10:41:32.027] > 
[10:41:32.520] > Waiting for server log...
[10:41:33.026] > Waiting for server log...
[10:41:33.533] > Waiting for server log...
[10:41:34.041] > Waiting for server log...
[10:41:34.546] > Waiting for server log...
[10:41:35.052] > Waiting for server log...
[10:41:35.571] > Waiting for server log...
[10:41:36.062] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,  
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
[10:41:36.071] > 
> Server did not start successfully. Full server log at /nfs/elsrv4/users2/grad/jr
> ecoulle/.vscode-server/.93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3.log >>>        
> Error: Cannot find module 'minimist'
> Require stack:
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/bootstrap-amd.js
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/vs/server/main.js
[10:41:36.077] > 
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17) 
>     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
>     at Module.require (internal/modules/cjs/loader.js:848:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at t.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:17:960)
>     at e.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:13:941)
>     at o (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b1
> 0e4d5f89737d9c2c25488a3/out/vs/loader.js:31:189)
>     at Object.errorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93
> c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:31:313)
>     at e.triggerErrorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/
> 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:14:306)
>     at /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4
> d5f89737d9c2c25488a3/out/vs/loader.js:14:10
>     at ReadFileContext.callback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-serve
> r/bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:18:342)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:239:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/bootstrap-amd.js',
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/vs/server/main.js'
>   ],
>   phase: 'loading',
>   moduleId: 'minimist',
>   neededBy: [ 'vs/platform/environment/node/argv' ]
[10:41:36.083] > 
> }
> Error: Cannot find module 'semver-umd'
> Require stack:
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/bootstrap-amd.js
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/vs/server/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17) 
>     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
>     at Module.require (internal/modules/cjs/loader.js:848:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at t.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:17:960)
>     at e.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:13:941)
>     at o (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b1
> 0e4d5f89737d9c2c25488a3/out/vs/loader.js:31:189)
>     at Object.errorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93
> c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:31:313)
>     at e.triggerErrorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/
> 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:14:306)
>     at /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4
> d5f89737d9c2c25488a3/out/vs/loader.js:14:10
>     at ReadFileContext.callback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-serve
> r/bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:18:342)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:239:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/bootstrap-amd.js',
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/vs/server/main.js'
>   ],
>   phase: 'loading',
>   moduleId: 'semver-umd',
>   neededBy: [
>     'vs/platform/extensionManagement/node/extensionDownloader',
>     'vs/workbench/services/extensions/node/extensionPoints',
>     'vs/platform/extensionManagement/node/extensionsScanner',
>     'vs/platform/extensionManagement/node/extensionManagementService'
>   ]
> }
> Error: Cannot find module 'applicationinsights'
> Require stack:
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/bootstrap-amd.js
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/vs/server/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17) 
>     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
>     at Module.require (internal/modules/cjs/loader.js:848:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at t.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:17:960)
>     at e.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:13:941)
>     at o (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b1
[10:41:36.088] > 
> 0e4d5f89737d9c2c25488a3/out/vs/loader.js:31:189)
>     at Object.errorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93
> c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:31:313)
>     at e.triggerErrorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/
> 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:14:306)
>     at /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4
> d5f89737d9c2c25488a3/out/vs/loader.js:14:10
>     at ReadFileContext.callback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-serve
> r/bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:18:342)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:239:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/bootstrap-amd.js',
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/vs/server/main.js'
>   ],
>   phase: 'loading',
>   moduleId: 'applicationinsights',
>   neededBy: [ 'vs/platform/telemetry/node/appInsightsAppender' ]
> }
> Error: Cannot find module 'cookie'
> Require stack:
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/bootstrap-amd.js
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/vs/server/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17) 
>     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
>     at Module.require (internal/modules/cjs/loader.js:848:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at t.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:17:960)
>     at e.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:13:941)
>     at o (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b1
> 0e4d5f89737d9c2c25488a3/out/vs/loader.js:31:189)
>     at Object.errorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93
> c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:31:313)
>     at e.triggerErrorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/
> 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:14:306)
>     at /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4
> d5f89737d9c2c25488a3/out/vs/loader.js:14:10
>     at ReadFileContext.callback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-serve
> r/bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:18:342)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:239:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/bootstrap-amd.js',
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/vs/server/main.js'
>   ],
>   phase: 'loading',
>   moduleId: 'cookie',
>   neededBy: [ 'vs/server/webClientServer' ]
> }
> Error: Cannot find module 'yauzl'
> Require stack:
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/bootstrap-amd.js
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/vs/server/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17) 
[10:41:36.093] > 
>     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
>     at Module.require (internal/modules/cjs/loader.js:848:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at t.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:17:960)
>     at e.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:13:941)
>     at o (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b1
> 0e4d5f89737d9c2c25488a3/out/vs/loader.js:31:189)
>     at Object.errorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93
> c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:31:313)
>     at e.triggerErrorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/
> 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:14:306)
>     at /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4
> d5f89737d9c2c25488a3/out/vs/loader.js:14:10
>     at ReadFileContext.callback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-serve
> r/bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:18:342)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:239:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/bootstrap-amd.js',
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/vs/server/main.js'
>   ],
>   phase: 'loading',
>   moduleId: 'yauzl',
>   neededBy: [ 'vs/base/node/zip' ]
> }
> Error: Cannot find module 'yazl'
> Require stack:
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/bootstrap-amd.js
> - /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89
> 737d9c2c25488a3/out/vs/server/main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17) 
>     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
>     at Module.require (internal/modules/cjs/loader.js:848:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at t.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:17:960)
>     at e.load (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c
> 5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:13:941)
>     at o (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b1
> 0e4d5f89737d9c2c25488a3/out/vs/loader.js:31:189)
>     at Object.errorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93
> c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:31:313)
>     at e.triggerErrorback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/
> 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:14:306)
>     at /nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4
> d5f89737d9c2c25488a3/out/vs/loader.js:14:10
>     at ReadFileContext.callback (/nfs/elsrv4/users2/grad/jrecoulle/.vscode-serve
[10:41:36.099] > 
> r/bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/out/vs/loader.js:18:342)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:239:13) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/bootstrap-amd.js',
>     '/nfs/elsrv4/users2/grad/jrecoulle/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5
> f89737d9c2c25488a3/out/vs/server/main.js'
>   ],
>   phase: 'loading',
>   moduleId: 'yazl',
>   neededBy: [ 'vs/base/node/zip' ]
> }
> <<< End of server log
> e8b4217ccdf8##32##
[10:41:36.099] Received install output: e8b4217ccdf8##32##
[10:41:36.103] Resolver error: Error: The VS Code Server failed to start
	at Function.ExitCode (c:\Users\jaker\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:130495)
	at Object.t.handleInstallOutput (c:\Users\jaker\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:128732)
	at I (c:\Users\jaker\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:106775)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\jaker\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:104774
	at async Object.t.withShowDetailsEvent (c:\Users\jaker\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:109845)
	at async Object.t.resolve (c:\Users\jaker\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107960)
	at async c:\Users\jaker\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:141955
[10:41:36.104] ------




[10:41:36.456] "install" terminal command done
[10:41:36.456] Install terminal quit with output: 
```

**Comment by vpascuzz** [comment]
Also cannot connect to remote with VS Code 1.50.0 (commit 93c2f0fbf), Remote - SSH v0.55.0:
```
[13:56:22.382] Log Level: 2
[13:56:22.383] remote-ssh@0.55.0
[13:56:22.383] linux x64
[13:56:22.384] SSH Resolver called for "ssh-remote+mymachine", attempt 1
[13:56:22.385] SSH Resolver called for host: mymachine
[13:56:22.385] Setting up SSH remote "mymachine"
[13:56:22.387] Acquiring local install lock: /tmp/vscode-remote-ssh-mymachine-install.lock
[13:56:22.396] Looking for existing server data file at /home/myname/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-mymachine-93c2f0fbf16c7d9c2c25488a3-0.55.0/data.json
[13:56:22.396] Using commit id "93c2f0fbf16c5a4bd9c2c25488a3" and quality "stable" for server
[13:56:22.397] Install and start server if needed
[13:56:22.401] Checking ssh with "ssh -V"
[13:56:22.409] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020

[13:56:22.414] askpass server listening on /run/user/1000/vscode-ssh-askpass-9d006291ce388d9ad0ec6b94690ca998c5.sock
[13:56:22.414] Spawning local server with {"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-4c065e893bc933571fd27.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","33359","-o","ConnectTimeout=15","mymachine"],"dataFilePath":"/home/myname/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-mymachine-93c2f0fbf16c5a737d9c2c25488a3-0.55.0/data.json"}
[13:56:22.414] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/myname/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/myname/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-9d006291ce388d9ad090ca998c5.sock"}
[13:56:22.419] Spawned 30570
[13:56:22.504] > local-server> Spawned ssh: 30578
[13:56:22.506] stderr> OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020
[13:56:22.568] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:/xxx
[13:56:22.663] stderr> Authenticated to mymachine.lbl.gov ([xxx.xxx.xxx.xxx]:xx).
[13:56:22.940] stderr> Warning: No xauth data; using fake authentication data for X11 forwarding.
[13:56:23.106] > ready: 9bfe957749c7
[13:56:23.111] > Linux 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020
[13:56:23.111] Platform: linux
[13:56:23.137] > 9bfe957749c7: running
[13:56:23.199] > Acquiring lock on /home/myname/.vscode-server/bin/93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3/vscode-remote-lock.myname.93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
[13:56:23.200] > Installation already in progress...
> 9bfe957749c7##24##
[13:56:23.201] Received install output: 9bfe957749c7##24##
[13:56:23.202] Server installation process already in progress - waiting and retrying
[13:56:23.202] Terminating local server
[13:56:23.209] Local server exit: 15
[13:57:20.002] Resolver error: Error: 
	at Function.Create (/home/myname/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:130564)
	at /home/myname/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:105225
	at async Object.t.withShowDetailsEvent (/home/myname/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:109845)
	at async /home/myname/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100912
	at async R (/home/myname/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:97702)
	at async Object.t.resolveWithLocalServer (/home/myname/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100561)
	at async Object.t.resolve (/home/myname/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:107840)
	at async /home/myname/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:141955
[13:57:20.005] ------
```
Deleted `.vscode-server` on remote machine and tried reinstall -- still broken. Seems correlated with recent code drop.

**Comment by function2-llx** [comment]
> EDIT: Not a problem with VS Code or Remote - SSH. Sorry for the noise.

Could you please share your solution? I meet the same issue.

**Comment by vpascuzz** [comment]
@function2-llx I tested the same code and Remote - SSH versions as above and managed to successfully connect to several different machines. The log above is from another machine that appears to be in a bad state.

So, no 'solution' yet. When the problematic server is rebooted, I will try to remote-ssh into it (likely not until Friday when the sysadmin gets to the lab). Keep you posted.

**Comment by jdrecoulle0001** [comment]
> > EDIT: Not a problem with VS Code or Remote - SSH. Sorry for the noise.
> 
> Could you please share your solution? I meet the same issue.

I was able to get mine working again by running the command “Remote-SSH: Kill VS Code Server on Host”, then reconnecting to the server.

**Comment by vpascuzz** [comment]
> @function2-llx I tested the same code and Remote - SSH versions as above and managed to successfully connect to several different machines. The log above is from another machine that appears to be in a bad state.
> 
> So, no 'solution' yet. When the problematic server is rebooted, I will try to remote-ssh into it (likely not until Friday when the sysadmin gets to the lab). Keep you posted.

FYI: It was a problem with the machine, not code.

**Comment by function2-llx** [comment]
@vpascuzz Thanks! I'm able to work again with Remote-SSH again, in my case it was a problem of network, some process occupied too much bandwith of the server these days.

**Comment by bamurtaugh** [comment]
Thanks for the discussion here! Since it looks like the issues were resolved, going to close the thread, but please let me know if you have any other questions or feedback.
