### ISSUE TITLE
Visual Studio Code - Remote Containers spawns hundreds of processes when container is run with --pid=host and sharing docker socket

### ISSUE THREAD

**Issue by awesomebytes** [microsoft/vscode-remote-release#3850]
Hello. I found an issue that happens in a very specific situation (unfortunately part of my team's workflow). When attaching VSCode via Remote Containers to a second container that has set `-t --pid=host  -v /var/run/docker.sock:/var/run/docker.sock` VSCode starts spawning hundred of `docker exec -i -u` processes filling up the RAM very quickly.

I've created a video showing the issue happening (note that my flags there are slightly different, as I wrote this issue I dropped `--privileged --net=host` which are not necessary to reproduce this issue) so it's easier to understand: https://youtu.be/MKCA5XW026c

- VSCode Version: 1.50.0 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3 x64 (happened also in 1.49.2)
- Local OS Version: Ubuntu 18.04
- Remote OS Version: Ubuntu 18.04 / doesn't seem to matter
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Open shell 1 and run `docker run --rm -it -v /var/run/docker:/var/run/docker --name docker_socket_shared python:3 bash`
2. Open shell 2 and run `docker run --rm -it --pid=host -v /var/run/docker:/var/run/docker --name docker_socket_shared_2 python:3 bash`
3. Open Visual Studio Code and use the Remote Explorer extension, using the dropdown of Containers, and click on the `python:3 (/docker_socket_shared)` _Attach to Container_ icon. This one will work fine.
4. From any of the Visual Studio Code windows, use again the Remote Explorer extension, with the dropdown of Containers, and click the `python:3 (/docker_socket_shared_2)` _Attach to Container_ icon. This time the remote extension will get stuck running hundreds of processes and eating all RAM.

Thank you very much for any help you can provide.

Edit: as I posted this, I saw in the video a suspicious command in the second 0:35: (attaching screenshot)
![Screenshot from 2020-10-14 19-49-44](https://user-images.githubusercontent.com/1721716/95966101-77834500-0e56-11eb-86ef-24cd96365570.png)

Edit2: I found out that the first docker container does not need to have `--pid=host` enabled to reproduce this bug. I've updated the issue with that information.

**Comment by PavelSosin-320** [comment]
What I see in the Docker Documentation:
**--pid option** in docker run says to which namespace the Process started inside the container belongs: Host or another container

**--pid-limit** restricts the number of Processes.  
In other words, if --pid is set to Host all processes started inside the container will be visible as the Host processes and if **pid-limit** is not set or set to -1 the container may create as many Host processes as it needs.
These are docker run options because the same image can be run on the different hosts and Host's limitations can vary. Even on the same kind of Host, the process limit is the kernel parameter (sysctl!) which can't be "imported" into VSCode.
Docker's documentation provides the  [guidelyne](https://docs.docker.com/engine/reference/run/) but how to optimize these values should be discussed in another community.
Another consideration is how much used by the Docker/Container init process is reliable and cleans the Container's sub-processes. In the big and complex containers, it should be carefully monitored (**Docker top & Docker stats**) and tuned.
VSCode is too basic Container's runner to manage the Docker's host resources directly.
Development tools can produce many processes to utilize the Docker daemon host's resources in the best way.

**Comment by awesomebytes** [comment]
Hey @PavelSosin-320, I'm reporting a bug that creates infinite processes (or at least, I let it run until it ate all my RAM... a few times, for science). Which only happens on this specific condition I reported. Otherwise VSCode behaves very nicely!
I'm not trying to control how many processes it runs.

**Comment by PavelSosin-320** [comment]
Docker is all about resource management and sharing between containers. Please, monitor your containers and take necessary steps to restrict resource consumption every time when you see something abnormal like infinite resource consumption growth. If certain resource consumption can't be restricted by Docker run command options (reflecting Host OS cgroups), please open an issue on Docker implementation.
I didn't find how to protect Daemon running Dev Container from Out-Of-Resource situation, maybe, because this plugin was Docker-Desktop oriented with very limited resource management support.
But, it is another issue ???
Happy codding.

**Comment by awesomebytes** [comment]
@PavelSosin-320 again, what you say is off-topic from the problem I'm reporting regarding Visual Studio Code (it's not a problem of Docker, it's a problem of this plugin for VSCode).

**Comment by PavelSosin-320** [comment]
@awesomebytes 
Please, clarify what do you mean when writing --pid=host and "Container spawns hundreds of processes"? What do you expect? pid=host  is Docker run command option that defines how Docker container creates processes. In which namespace and limit on the number of processes. It is absolutely invariant for all kinds of Docker containers and is applied to Dev container too.
There is no way to configure or restrict this process from outside the Docker. The container is not a VM and has no own mechanism for process creation.
Every time when process inside the container creates a subprocess using Kernel call a new process is created in the Host OS.
The "size" of Host OS should be big enough" to fulfill all requirements of all containers running on the Docker engine.
VSCode can't help you but only pass the chosen parameters to the Docker run command. 
sysctl command from inside the container can't work too because Host's Kernel is read-only from the container point of view.
When **specific container**  creates too many processes it causes big troubles - the number of processes should be restricted using pid-limit, -pid optins. -**-pid means PID namespace.**
VSCode is not a Docker orchestration engine to provide a resource management mechanism to the container.

**Comment by awesomebytes** [comment]
@PavelSosin-320 Just run the commands in my initial post on `Steps to Reproduce:`... Or watch the video... You are really complicating the issue way more than it is.

If you substitute step 4 to connect to a container that's **not** doing `--pid=host -v /var/run/docker.sock:/var/run/docker.sock` Visual Studio Code will work perfectly fine attaching to it. You can attach to as many containers as you want without seeing this behavior that I'm reporting here without those two specific flags set **AND** attaching to a second container.

I reiterate: This is not a problem from Docker, this a problem from Visual Studio Code - Remote Containers.

I reiterate again: This issue is not reporting some Docker orchestration problem, it's reporting some infinite loop that spawns processes in Visual Studio Code - Remote Container under a specific set of conditions.

@chrmarti Could you hide this conversation? I don't think it's adding anything to the issue. Additionally, thanks for assigning yourself the bug.

**Comment by awesomebytes** [comment]
Hello @chrmarti, I just tested the last version of VSCode (1.51.1 e5a624b788d92b8d34d1392e4c4d9789406efe8f x64) and this problem persists. Would it be possible to open this issue again?

Thank you!

**Comment by chrmarti** [comment]
This fix will only be in 0.150.0 of the Remote-Containers extension.

**Comment by awesomebytes** [comment]
Ok thanks. I see it needs VSCode ^1.52.0 so I guess I'll need to wait.

**Comment by chrmarti** [comment]
@awesomebytes Remote-Containers 0.150.0 is out, you can use it today with VS Code Insiders (https://code.visualstudio.com/insiders/) which can be installed alongside VS Code's stable release.

**Comment by awesomebytes** [comment]
Hello @chrmarti, thanks a lot for the pointer to VS Code Insiders. I've just tried this same bug in that version (code-insiders 1.52.0-insider a36c68b9ec3d6a0aca9799d7a10be741a6658a51 x64, remote-containers v0.150.0) and the bug has changed its behaviour, but it is still not working.

See attached screenshots:

![Screenshot from 2020-11-20 13-58-55](https://user-images.githubusercontent.com/1721716/99752651-cea4c580-2b38-11eb-9a56-7208702a5214.png)

![Screenshot from 2020-11-20 13-59-11](https://user-images.githubusercontent.com/1721716/99752658-d2d0e300-2b38-11eb-987e-b62415385bc6.png)


And for commodity, copy-paste of that log:
```
[3 ms] Remote-Containers 0.150.0 in VS Code 1.52.0-insider (a36c68b9ec3d6a0aca9799d7a10be741a6658a51).
[13 ms] Start: Resolving remote
[15 ms] Setting up container /docker_socket_shared_2

[15 ms] Start: Run: docker inspect --type container /docker_socket_shared_2
[71 ms] Start: Check Docker is running
[71 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[134 ms] Server API version: 1.40
[134 ms] Start: Inspecting container
[134 ms] Start: Run: docker inspect --type container 9c38cdacecc81dfc99c9e7d399b084ab85bbf353f47e63660b8a0653a7329b5d
[176 ms] Start: Run: docker exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=22c3bc21-34b0-41eb-9fce-af13e259f3b21605841124681 9c38cdacecc81dfc99c9e7d399b084ab85bbf353f47e63660b8a0653a7329b5d /bin/sh
[179 ms] Start: Run in container: uname -m
[297 ms] x86_64
[297 ms] 
[297 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[299 ms] PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[300 ms] 
[300 ms] Start: Run in container: cat /etc/passwd
[302 ms] Start: Run in container: test -d /root/.vscode-server-insiders
[303 ms] 
[303 ms] 
[303 ms] Exit code 1
[303 ms] Start: Run in container: test -d /root/.vscode-remote
[303 ms] 
[303 ms] 
[303 ms] Exit code 1
[304 ms] Start: Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server-insiders/data/Machine' && { > '/root/.vscode-server-insiders/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[306 ms] 
[306 ms] 
[306 ms] Start: Run in container: cat /root/.vscode-server-insiders/data/Machine/settings.json
[307 ms] 
[307 ms] cat: /root/.vscode-server-insiders/data/Machine/settings.json: No such file or directory
[307 ms] Exit code 1
[307 ms] Start: Run in container: test -d /root/.vscode-server-insiders/bin/a36c68b9ec3d6a0aca9799d7a10be741a6658a51
[308 ms] 
[308 ms] 
[308 ms] Exit code 1
[308 ms] Installing VS Code Server for commit a36c68b9ec3d6a0aca9799d7a10be741a6658a51
[308 ms] Start: Run in container: mkdir -p /root/.vscode-server-insiders/bin/a36c68b9ec3d6a0aca9799d7a10be741a6658a51_1605841125530
[310 ms] 
[310 ms] 
[336 ms] Start: Run in container: (dd iflag=fullblock bs=8192 count=3717 2>/dev/null; dd iflag=fullblock bs=2258 count=1 2>/dev/null) | tar --no-same-owner -xz --strip-components 1 -C /root/.vscode-server-insiders/bin/a36c68b9ec3d6a0aca9799d7a10be741a6658a51_1605841125530
[1135 ms] 
[1135 ms] 
[1135 ms] Start: Run in container: mv -n /root/.vscode-server-insiders/bin/a36c68b9ec3d6a0aca9799d7a10be741a6658a51_1605841125530 /root/.vscode-server-insiders/bin/a36c68b9ec3d6a0aca9799d7a10be741a6658a51
[1137 ms] 
[1137 ms] 
[1137 ms] Start: Launching Remote-Containers helper.
[1137 ms] Start: Run: gpgconf --list-dir agent-extra-socket
[1142 ms] Start: Run in container: gpgconf --list-dir agent-socket
[1143 ms] /root/.gnupg/S.gpg-agent
[1143 ms] 
[1143 ms] Start: Run in container: gpgconf --list-dir homedir
[1144 ms] /root/.gnupg
[1144 ms] 
[1144 ms] Start: Run in container: ls '/root/.gnupg/private-keys-v1.d' 2>/dev/null
[1145 ms] 
[1145 ms] 
[1145 ms] Exit code 2
[1145 ms] Start: Run in container: mkdir -p -m 700 '/root/.gnupg'
[1147 ms] 
[1147 ms] 
[1147 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-693a42f45f1dac3830b14ff30aa28867458aeb0f.js' >/tmp/vscode-remote-containers-693a42f45f1dac3830b14ff30aa28867458aeb0f.js
[1147 ms] Start: Run: gpgconf --list-dir homedir
[1150 ms] 
[1150 ms] 
[1150 ms] Start: Run in container: # Test for /root/.ssh/known_hosts and ssh
[1152 ms] 
[1152 ms] 
[1152 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-693a42f45f1dac3830b14ff30aa28867458aeb0f.js' >/tmp/vscode-remote-containers-server-693a42f45f1dac3830b14ff30aa28867458aeb0f.js
[1153 ms] 
[1153 ms] 
[1153 ms] Start: Run in container: gpgconf --list-dir homedir
[1153 ms] Start: Run: docker exec -i -u root -e REMOTE_CONTAINERS_SOCKETS=["/tmp/vscode-ssh-auth-693a42f45f1dac3830b14ff30aa28867458aeb0f.sock","/root/.gnupg/S.gpg-agent"] -e REMOTE_CONTAINERS_IPC=/tmp/vscode-remote-containers-ipc-693a42f45f1dac3830b14ff30aa28867458aeb0f.sock 9c38cdacecc81dfc99c9e7d399b084ab85bbf353f47e63660b8a0653a7329b5d /root/.vscode-server-insiders/bin/a36c68b9ec3d6a0aca9799d7a10be741a6658a51/node /tmp/vscode-remote-containers-server-693a42f45f1dac3830b14ff30aa28867458aeb0f.js
[1158 ms] /root/.gnupg
[1158 ms] 
[1159 ms] Start: Run in container: # Copy /home/skipper/.ssh/known_hosts to /root/.ssh/known_hosts
[1161 ms] 
[1161 ms] 
[1161 ms] Start: Run in container: # Test for /root/.gnupg/pubring.kbx and gpg
[1163 ms] 
[1163 ms] 
[1163 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --system credential.helper '!f() { /root/.vscode-server-insiders/bin/a36c68b9ec3d6a0aca9799d7a10be741a6658a51/node /tmp/vscode-remote-containers-693a42f45f1dac3830b14ff30aa28867458aeb0f.js $*; }; f' || true
[1164 ms] 
[1165 ms] 
[1165 ms] Start: Run in container: # Copy /home/skipper/.gnupg/pubring.kbx to /root/.gnupg/pubring.kbx
[1167 ms] 
[1167 ms] 
[1167 ms] Start: Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server-insiders/data/Machine' && { > '/root/.vscode-server-insiders/data/Machine/.installExtensionsMarker' ; } 2> /dev/null
[1168 ms] 
[1168 ms] 
[1168 ms] Start: Run in container: # Test for /root/.gnupg/trustdb.gpg and gpg
[1170 ms] 
[1170 ms] 
[1170 ms] Start: Run in container: # Copy /home/skipper/.gnupg/trustdb.gpg to /root/.gnupg/trustdb.gpg
[1172 ms] 
[1172 ms] 
[1172 ms] Start: Run in container: # Test for /root/.gitconfig and git
[1172 ms] Start: Run: gpg-connect-agent updatestartuptty /bye
[1177 ms] 
[1177 ms] 
[1177 ms] Start: Run in container: # Copy /home/skipper/.gitconfig to /root/.gitconfig
[1180 ms] 
[1180 ms] 
[1180 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --global credential.helper '!f() { /root/.vscode-server-insiders/bin/a36c68b9ec3d6a0aca9799d7a10be741a6658a51/node /tmp/vscode-remote-containers-693a42f45f1dac3830b14ff30aa28867458aeb0f.js $*; }; f' || true
[1182 ms] 
[1183 ms] 
[1183 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd ; readlink /proc/$pid/ns/mnt ; cat /proc/$pid/stat | tr "
[3607 ms] TypeError: Cannot read property '1' of null
        at /home/skipper/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.150.0/dist/extension.js:1:613089
        at Array.map (<anonymous>)
        at Object.t.findProcesses (/home/skipper/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.150.0/dist/extension.js:1:613009)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:94:5)
        at async V (/home/skipper/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.150.0/dist/extension.js:1:639497)
        at async Object.t.injectIntoContainer (/home/skipper/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.150.0/dist/extension.js:1:636870)
        at async Object.t.resolve (/home/skipper/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.150.0/dist/extension.js:1:778625)
        at async /home/skipper/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.150.0/dist/extension.js:1:686810
```

**Comment by chrmarti** [comment]
Marking as verified based on https://github.com/microsoft/vscode-remote-release/issues/4054#issuecomment-739717314.
