### ISSUE TITLE
 "Failed to parse remote port from server output" when more than one vscode clients try to access the same remote server

### ISSUE THREAD

**Issue by imxxw** [microsoft/vscode-remote-release#3861]
- VSCode Version: 1.50.1
- Local OS Version: Windows 10 home
- Remote OS Version: Ubuntu 18.04.4 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

I have 2 PCs (pc1 and pc2). Both of them have vscode installed，and they use the same account to access the remote server 111.  They are working well until now.

1. The vscode is updated to v1.50.1 on pc1, and then the it can't access the server 111.

2. I try it on pc2, the vscode can access the server 111. But after the vscode is updated to v1.50.1, it can't access the server 111 either.

the log is below:
```
[10:58:10.251] Received install output: d5db649fd3c2##24##
[10:58:10.251] Server installation process already in progress - waiting and retrying
[10:58:10.545] "install" terminal command done
[10:58:10.546] Install terminal quit with output:
[10:58:11.268] Using SSH config file "C:\Users\XXW\.ssh\config"
[10:58:11.269] Running script with connection command: ssh -T -D 56593 -F "C:\Users\XXW\.ssh\config" 111 bash
[10:58:11.272] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:58:13.396] "install" terminal received data: "[2J[m[Hd5db649fd3c2: running
]0;C:\WINDOWS\System32\cmd.exe[?25h"
[10:58:13.397] Got some output, clearing connection timeout
[10:58:13.711] "install" terminal command done
[10:58:13.712] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exe
[10:58:13.712] Received install output: ]0;C:\WINDOWS\System32\cmd.exe
[10:58:13.713] Stopped parsing output early. Remaining text: ]0;C:\WINDOWS\System32\cmd.exe
[10:58:13.713] Failed to parse remote port from server output
[10:58:13.721] Resolver error: Error:
    at Function.Create (c:\Users\XXW\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:130564)
    at Object.t.handleInstallOutput (c:\Users\XXW\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:127671)
    at I (c:\Users\XXW\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:106775)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async c:\Users\XXW\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:104774
    at async Object.t.withShowDetailsEvent (c:\Users\XXW\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:109845)
    at async Object.t.resolve (c:\Users\XXW\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107960)
    at async c:\Users\XXW\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:141955
[10:58:13.725] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"UnparsableOutput","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","gotUnrecognizedPrompt":"0","remoteInConfigFile":"1"},"measures":{"resolveAttempts":1,"retries":4}}
[10:58:13.728] ------
```

3. I can access the server 111 normally using SSH in other terminals (such as cmd, MobaXterm).

4. I delete all the log files(there are many log files) in the folder ".vscode-server" on server 111. Then I tried to access server 111 via vscode on pc1, and it can work again. Then I tried the same on pc2, but it can't work anymore.

5. I delete the log file(only 1 log file now) in the folder ".vscode-server" on server 111. Then I tried to access server 111 via vscode on pc2, and it can work again. Then I tried the same on pc1, but it can't work anymore. It means that only one vscode client can access the same remote vscode-server.

Maybe the problem is the log file access, hope you to fixed. 
Thank you!

**Comment by roblourens** [comment]
Please try running "Kill vs code server on host", then try again, and share the full server log
