### ISSUE TITLE
Could not establish connection to "IP address".

### ISSUE THREAD

**Issue by OmarSinoussy** [microsoft/vscode-remote-release#3868]
- Local VSCode Version: 1.50.1
- Remote VSCode Version: 1.50.0
- Local OS Version: macOS Catalina 10.15.7 (19H2)
- Remote OS Version:  Microsoft Windows 10 Pro 10.0.18363 N/A Build 18363 
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
I've been trying to SSH into my windows machine from my Mac using VS Code for a while now but it hasn't been working. I should note that I'm able to SSH into the machine with no issues from the terminal. The following are the logs from the SSH attempt through VS Code: 

```
[00:56:35.195] Log Level: 2
[00:56:35.196] remote-ssh@0.55.0
[00:56:35.196] darwin x64
[00:56:35.197] SSH Resolver called for "ssh-remote+192.168.100.18", attempt 1
[00:56:35.198] SSH Resolver called for host: 192.168.100.18
[00:56:35.198] Setting up SSH remote "192.168.100.18"
[00:56:35.200] Acquiring local install lock: /var/folders/nb/bn09s2nj1hn5pkn5pll1w86m0000gn/T/vscode-remote-ssh-192.168.100.18-install.lock
[00:56:35.213] Looking for existing server data file at /Users/omarabdulla/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-192.168.100.18-d2e414d9e4239a252d1ab117bd7067f125afd80a-0.55.0/data.json
[00:56:35.214] Using commit id "d2e414d9e4239a252d1ab117bd7067f125afd80a" and quality "stable" for server
[00:56:35.216] Install and start server if needed
[00:56:35.220] Checking ssh with "ssh -V"
[00:56:35.227] > OpenSSH_8.1p1, LibreSSL 2.7.3

[00:56:35.231] askpass server listening on /var/folders/nb/bn09s2nj1hn5pkn5pll1w86m0000gn/T/vscode-ssh-askpass-b907855ece80a810ae37ad05695992f35cf8a0a9.sock
[00:56:35.231] Spawning local server with {"ipcHandlePath":"/var/folders/nb/bn09s2nj1hn5pkn5pll1w86m0000gn/T/vscode-ssh-askpass-c02785eb6ef2999d416c8ff554b61ea9b2875981.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","60166","-o","ConnectTimeout=15","192.168.100.18"],"dataFilePath":"/Users/omarabdulla/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-192.168.100.18-d2e414d9e4239a252d1ab117bd7067f125afd80a-0.55.0/data.json"}
[00:56:35.231] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/omarabdulla/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/omarabdulla/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/nb/bn09s2nj1hn5pkn5pll1w86m0000gn/T/vscode-ssh-askpass-b907855ece80a810ae37ad05695992f35cf8a0a9.sock"}
[00:56:35.233] Spawned 3897
[00:56:35.315] > local-server> Spawned ssh: 3898
[00:56:35.317] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[00:56:48.860] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:wMdcUagijETBxPq3JCiWe6icfAO9/VSRb1fS0O9+1ww
[00:56:49.051] Got askpass request: {"request":"OmarA@192.168.100.18's password:"}
[00:56:49.052] Showing password prompt
[00:56:49.053] Listening for interwindow password on /var/folders/nb/bn09s2nj1hn5pkn5pll1w86m0000gn/T/vscode-ssh-askpass-9a594f76ad5ab81072c71b5e245ecfb2d75dd8eb.sock
[00:56:49.053] Writing password prompt to globalState
[00:56:55.316] Got password response
[00:56:55.317] Interactor gave response: ********
[00:56:55.317] Cleaning up other-window auth server
[00:56:55.411] stderr> Authenticated to 192.168.100.18 ([192.168.100.18]:22).
[00:57:04.614] stderr> shell request failed on channel 2
[00:57:04.616] > local-server> ssh child died, shutting down
[00:57:04.620] Local server exit: 0
[00:57:04.620] Received install output: OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:wMdcUagijETBxPq3JCiWe6icfAO9/VSRb1fS0O9+1ww
Authenticated to 192.168.100.18 ([192.168.100.18]:22).
shell request failed on channel 2

[00:57:04.621] Stopped parsing output early. Remaining text: OpenSSH_8.1p1, LibreSSL 2.7.3debug1: Server host key: ecdsa-sha2-nistp256 SHA256:wMdcUagijETBxPq3JCiWe6icfAO9/VSRb1fS0O9+1wwAuthenticated to 192.168.100.18 ([192.168.100.18]:22).shell request failed on channel 2
[00:57:04.621] Failed to parse remote port from server output
[00:57:04.626] Resolver error: Error: 
	at Function.Create (/Users/omarabdulla/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:130564)
	at Object.t.handleInstallOutput (/Users/omarabdulla/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:127671)
	at Object.t.tryInstallWithLocalServer (/Users/omarabdulla/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:102339)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /Users/omarabdulla/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:104310
	at async Object.t.withShowDetailsEvent (/Users/omarabdulla/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:109845)
	at async /Users/omarabdulla/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100912
	at async R (/Users/omarabdulla/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:97702)
	at async Object.t.resolveWithLocalServer (/Users/omarabdulla/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100561)
	at async Object.t.resolve (/Users/omarabdulla/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:107840)
	at async /Users/omarabdulla/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:141955
[00:57:04.629] ------
```

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
You could try setting `"remote.SSH.useLocalServer": false` to see if that helps

**Comment by ifuijx** [comment]
> 
> 
> You could try setting `"remote.SSH.useLocalServer": false` to see if that helps

Still could not establish connection.

**Comment by roblourens** [comment]
Then can you share the log?

**Comment by ifuijx** [comment]
> 
> 
> Then can you share the log?

```
[09:23:56.546] Log Level: 2
[09:23:56.548] remote-ssh@0.55.0
[09:23:56.548] win32 x64
[09:23:56.550] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a223230322e3131342e39362e313830222c2275736572223a227a7977616e6734227d", attempt 1
[09:23:56.550] SSH Resolver called for host: <username>@<IP address>
[09:23:56.550] Setting up SSH remote "<IP address>"
[09:23:56.567] Using commit id "d2e414d9e4239a252d1ab117bd7067f125afd80a" and quality "stable" for server
[09:23:56.568] Install and start server if needed
[09:23:59.280] Checking ssh with "ssh -V"
[09:23:59.321] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[09:23:59.326] Running script with connection command: ssh -T -D 65245 <username>@<IP address> bash
[09:23:59.329] Terminal shell path: C:\Windows\System32\cmd.exe
[09:23:59.574] > <username>@<IP address>'s password:]0;C:\Windows\System32\cmd.exe
[09:23:59.574] Got some output, clearing connection timeout
[09:23:59.575] Showing password prompt
[09:24:02.125] Got password response
[09:24:02.126] "install" wrote data to terminal: "*****"
[09:24:02.139] > 
[09:24:04.081] > bda9891eb801: running
[09:24:04.135] > Acquiring lock on /home/<username>/.vscode-server/bin/d2e414d9e4239a252d1ab117bd706
> 7f125afd80a/vscode-remote-lock.<username>.d2e414d9e4239a252d1ab117bd7067f125afd80a 
[09:24:04.158] > flock: 99: Installation already in progress...
> bda9891eb801##24##
> Function not implemented
> flock: 99: Function not implemented
> flock: 99: Function not implemented
[09:24:04.158] Received install output: bda9891eb801##24##
[09:24:04.158] Server installation process already in progress - waiting and retrying
[09:24:04.466] "install" terminal command done
[09:24:04.467] Install terminal quit with output: 
[09:24:06.667] Running script with connection command: ssh -T -D 65245 <username>@<IP address> bash
[09:24:06.669] Terminal shell path: C:\Windows\System32\cmd.exe
[09:24:06.989] > <username>@<IP address>'s password:]0;C:\Windows\System32\cmd.exe
[09:24:06.990] Got some output, clearing connection timeout
[09:24:06.990] Showing password prompt
[09:24:09.948] Got password response
[09:24:09.948] "install" wrote data to terminal: "*****"
[09:24:09.959] > 
[09:24:11.671] > bda9891eb801: running
[09:24:11.720] > Acquiring lock on /home/<username>/.vscode-server/bin/d2e414d9e4239a252d1ab117bd706
> 7f125afd80a/vscode-remote-lock.<username>.d2e414d9e4239a252d1ab117bd7067f125afd80a 
[09:24:11.730] > flock: 99: Installation already in progress...
> bda9891eb801##24##
> Function not implemented
> flock: 99: Function not implemented
> flock: 99: Function not implemented
[09:24:11.731] Received install output: bda9891eb801##24##
[09:24:11.731] Server installation process already in progress - waiting and retrying
[09:24:12.034] "install" terminal command done
[09:24:12.035] Install terminal quit with output: 
[09:24:13.948] Running script with connection command: ssh -T -D 65245 <username>@<IP address> bash
[09:24:13.951] Terminal shell path: C:\Windows\System32\cmd.exe
[09:24:14.172] > <username>@<IP address>'s password:]0;C:\Windows\System32\cmd.exe
[09:24:14.172] Got some output, clearing connection timeout
[09:24:14.173] Showing password prompt
[09:24:17.460] Got password response
[09:24:17.460] "install" wrote data to terminal: "*****"
[09:24:17.470] > 
[09:24:18.916] > bda9891eb801: running
[09:24:18.966] > Acquiring lock on /home/<username>/.vscode-server/bin/d2e414d9e4239a252d1ab117bd706
> 7f125afd80a/vscode-remote-lock.<username>.d2e414d9e4239a252d1ab117bd7067f125afd80a 
[09:24:18.984] > flock: 99: Installation already in progress...
> bda9891eb801##24##
> Function not implemented
> flock: 99: Function not implemented
> flock: 99: Function not implemented
[09:24:18.984] Received install output: bda9891eb801##24##
[09:24:18.984] Server installation process already in progress - waiting and retrying
[09:24:19.287] "install" terminal command done
[09:24:19.287] Install terminal quit with output: 
[09:24:21.277] getPlatformForHost was canceled
[09:24:21.285] Resolver error: Error: Connecting was canceled
```

**Comment by roblourens** [comment]
Were you trying to connect to WSL? Because I think that's what's happening here.

When you disabled useLocalServer it should have prompted you for the remote platform to configure `remote.SSH.remotePlatform`. Sounds like it's working for you one way or another now though.
