### ISSUE TITLE
Unable to ssh to Siteground server via Remote - SSH extension in VS Code

### ISSUE THREAD

**Issue by JonathanRhein** [microsoft/vscode-remote-release#3884]
- VSCode Version: 1.50.1
- Local OS Version:  macOS 10.14.6
- Remote OS Version: Fedora 31
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Install extension Remote - SSH inside VS Code
2. Open connection to Siteground host via **Remote - SSH**

This produces the the following **error**:

```
[14:44:51.437] Log Level: 2
[14:44:51.438] remote-ssh@0.55.0
[14:44:51.438] darwin x64
[14:44:51.440] SSH Resolver called for "ssh-remote+gfxc2609.siteground.eu", attempt 1
[14:44:51.440] SSH Resolver called for host: gfxc2609.siteground.eu
[14:44:51.440] Setting up SSH remote "gfxc2609.siteground.eu"
[14:44:51.443] Acquiring local install lock: /var/folders/t1/cvst3l8s7b7gn6m45c_vvv9r0000gn/T/vscode-remote-ssh-gfxc2609.siteground.eu-install.lock
[14:44:51.451] Looking for existing server data file at /Users/user/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-gfxc2609.siteground.eu-d2e414d9e4239a252d1ab117bd7067f125afd80a-0.55.0/data.json
[14:44:51.452] Using commit id "d2e414d9e4239a252d1ab117bd7067f125afd80a" and quality "stable" for server
[14:44:51.453] Install and start server if needed
[14:44:51.457] Checking ssh with "ssh -V"
[14:44:51.486] > OpenSSH_7.9p1, LibreSSL 2.7.3

[14:44:51.489] askpass server listening on /var/folders/t1/cvst3l8s7b7gn6m45c_vvv9r0000gn/T/vscode-ssh-askpass-c516da6bda0f83f73ae592bff61fbd3fcce00450.sock
[14:44:51.489] Spawning local server with {"ipcHandlePath":"/var/folders/t1/cvst3l8s7b7gn6m45c_vvv9r0000gn/T/vscode-ssh-askpass-276ab7f95712d96006044237799b8032d102ae14.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","54720","-o","ConnectTimeout=15","gfxc2609.siteground.eu"],"dataFilePath":"/Users/user/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-gfxc2609.siteground.eu-d2e414d9e4239a252d1ab117bd7067f125afd80a-0.55.0/data.json"}
[14:44:51.489] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/t1/cvst3l8s7b7gn6m45c_vvv9r0000gn/T/vscode-ssh-askpass-c516da6bda0f83f73ae592bff61fbd3fcce00450.sock"}
[14:44:51.492] Spawned 93844
[14:44:51.566] > local-server> Spawned ssh: 93845
[14:44:51.574] stderr> OpenSSH_7.9p1, LibreSSL 2.7.3
[14:44:51.875] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:BKF80GuGpLHJFV93UhECN6XLToCjLspMQkvhpgBw0oo
[14:44:52.269] stderr> Authenticated to gfxc2609.siteground.eu ([35.207.67.104]:16295).
[14:44:52.435] > ready: 5b8e61cddb7e
[14:44:52.468] > Linux 3.12.18-clouder0 #1 SMP Tue Oct 9 18:14:47 EEST 2018
[14:44:52.468] Platform: linux
[14:44:52.626] > 5b8e61cddb7e: running
[14:44:52.641] > Acquiring lock on /home/u781-etsbeocxv2pw/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/vscode-remote-lock.u781-etsbeocxv2pw.d2e414d9e4239a252d1ab117bd7067f125afd80a
[14:44:52.642] > Found existing installation at /home/u781-etsbeocxv2pw/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a...
[14:44:52.643] stderr> main: line 404: ps: command not found
[14:44:52.645] > SHELL=/bin/bash
> LESS=-MRFSXx4
> LESSCHARSET=utf-8
> HISTCONTROL=ignoredups
> HOSTNAME=gfxc2609.siteground.eu
> HISTSIZE=1000000
> HISTTIMEFORMAT=%F %T %z 
> PWD=/home/customer
> LOGNAME=u781-etsbeocxv2pw
> LS_OPTIONS=--color=auto -F -a -b -T 0
> HOME=/home/u781-etsbeocxv2pw
> VSCODE_AGENT_FOLDER=/home/u781-etsbeocxv2pw/.vscode-server
> SSH_CONNECTION=84.181.243.119 54722 35.207.67.104 16295
> LESSOPEN=||/usr/bin/lesspipe.sh %s
> USER=u781-etsbeocxv2pw
> SHLVL=2
> CVS_RSH=ssh
> SSH_CLIENT=84.181.243.119 54722 16295
> PGHOST=/tmp
> LC_ALL=C.utf8
> PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin:/home/u781-etsbeocxv2pw/bin
> HISTFILESIZE=10000000
> MAIL=/var/spool/mail/u781-etsbeocxv2pw
> _=/bin/printenv
[14:44:52.645] > Starting server with command... /home/u781-etsbeocxv2pw/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0 &> "/home/u781-etsbeocxv2pw/.vscode-server/.d2e414d9e4239a252d1ab117bd7067f125afd80a.log" < /dev/null
[14:44:52.648] > Waiting for server log...
[14:44:53.156] > Waiting for server log...
[14:44:53.655] > Waiting for server log...
[14:44:54.159] > Waiting for server log...
[14:44:54.662] > Waiting for server log...
[14:44:55.166] > Waiting for server log...
[14:44:55.668] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
[14:44:55.673] > Server did not start successfully. Full server log at /home/u781-etsbeocxv2pw/.vscode-server/.d2e414d9e4239a252d1ab117bd7067f125afd80a.log >>>
[14:44:55.673] > node: ../deps/uv/src/unix/core.c:556: uv__close_nocheckstdio: Assertion `fd > -1' failed.
> /home/u781-etsbeocxv2pw/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/server.sh: line 12: 46139 Aborted                 "$ROOT/node" ${INSPECT:-} "$ROOT/out/vs/server/main.js" "$@"
[14:44:55.675] > <<< End of server log
> 5b8e61cddb7e##32##
[14:44:55.675] Received install output: 5b8e61cddb7e##32##
[14:44:55.675] Terminating local server
[14:44:55.679] Resolver error: Error: The VS Code Server failed to start
	at Function.ExitCode (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:130495)
	at Object.t.handleInstallOutput (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:128732)
	at Object.t.tryInstallWithLocalServer (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:102339)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:104310
	at async Object.t.withShowDetailsEvent (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:109845)
	at async /Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100912
	at async R (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:97702)
	at async Object.t.resolveWithLocalServer (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:100561)
	at async Object.t.resolve (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:107840)
	at async /Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:127:141955
[14:44:55.680] Local server exit: 15
[14:44:55.682] ------
```

**Note**: From my local terminal I am perfectly able to log on to the Siteground server via SSH.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No, because I am using Remote - SSH to establish the connection to the Siteground server. So, I cannot disable all extensions.

**Comment by roblourens** [comment]
Seems that node cannot run on siteground servers. have also gotten this report https://github.com/microsoft/vscode-remote-release/issues/3018

https://www.siteground.com/kb/node-js-available/
