### ISSUE TITLE
pwntools stuck with insider remote-ssh terminal

### ISSUE THREAD

**Issue by onionyst** [microsoft/vscode-remote-release#389]
- VSCode Version: 1.35.0-insider
- OS Version: macOS Mojave 10.14.5

Steps to Reproduce:

1. Connect to Ubuntu 18.04.2 LTS with Remote-SSH extension. 
2. Open SSH terminal of VSCode Insider (automatically ssh-ed to Ubuntu). 
3. Create file `main.py` with following code. 

~~~python
import pwn
~~~

4. Create a virtualenv `py2pwn` with virtualenvwrapper v4.8.4 and switch to that venv. 
5. Run command `pip2.7 install pwntools` to install [pwntools](https://github.com/Gallopsled/pwntools) v3.12.2. 
6. Run command `python2.7 main.py` in terminal. 
5. The process is stuck until a Ctrl+C, and shows following information. 

~~~shell
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import pwn
  File "/home/xxx/.virtualenvs/py2pwn/lib/python2.7/site-packages/pwn/__init__.py", line 6, in <module>
    pwnlib.args.initialize()
  File "/home/xxx/.virtualenvs/py2pwn/lib/python2.7/site-packages/pwnlib/args.py", line 208, in initialize
    term.init()
  File "/home/xxx/.virtualenvs/py2pwn/lib/python2.7/site-packages/pwnlib/term/__init__.py", line 74, in init
    term.init()
  File "/home/xxx/.virtualenvs/py2pwn/lib/python2.7/site-packages/pwnlib/term/term.py", line 109, in init
    c = os.read(fd.fileno(), 1)
KeyboardInterrupt
~~~

Does this issue occur when all extensions are disabled?: Yes

This issue does not happen when directly using an SSH in iTerm2. It does not happen when using the terminal SSH in a VSCode v1.34.0 official release either. 

I suppose this is caused by something related to the utilization of standard input and output of terminal from pwntools, which is not supported by VSCode.

**Comment by egamma** [comment]
//fyi @qubitron

**Comment by qubitron** [comment]
I don't see a direct connection to the Python extension for this issue, it seems like it is a generic terminal issue with remote. 

@onionyst can you confirm that this issue occurs if the Python is not installed in the remote SSH environment?

**Comment by onionyst** [comment]
In fact, I only see this issue when I'm using [pwntools](https://github.com/Gallopsled/pwntools). I believe this is not a remote issue but a terminal one. 

I tried it locally (with [pwntools docker](https://hub.docker.com/r/pwntools/pwntools) since I'm on a Macintosh) yesterday, and it occurred again. Run the command `docker run -it --rm -v $(pwd):/work pwntools/pwntools python2.7 /work/exp.py` and it simply sticks. After a Ctrl-C I get merely the same

~~~shell
Traceback (most recent call last):
  File "/work/exp.py", line 8, in <module>
    import pwn
  File "/usr/local/lib/python2.7/dist-packages/pwn/__init__.py", line 6, in <module>
    pwnlib.args.initialize()
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/args.py", line 208, in initialize
    term.init()
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/term/__init__.py", line 74, in init
    term.init()
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/term/term.py", line 109, in init
    c = os.read(fd.fileno(), 1)
KeyboardInterrupt
~~~

However, this does not happen with VSCode 1.34.0 (blue icon). It's the 1.35.0-insider (green icon) version.

**Comment by Tyriar** [comment]
Could you try this again using today's build? I could have been fallout from https://github.com/xtermjs/xterm.js/issues/2107

**Comment by onionyst** [comment]
It works now. Much appreciated. =^-^=
