### ISSUE TITLE
WSL2 folder Reopen in Container do nothing

### ISSUE THREAD

**Issue by LuckyRu** [microsoft/vscode-remote-release#3923]
- VSCode Version: 1.50.1
- Local OS Version: Windows 10.0.19041
- Remote OS Version: Fedora remix for WSL
- Remote Extension/Connection Type: Docker/WSL
- Remote-Containers: v0.145.1
- Remote-WSL: v0.50.1

Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

- Open WSL2 (in my case Fedora remix for WSL)
- cd to ~/
- mkdir tst
- cd tst
- code .
- F1
- Add Development Container Configuration Files...
- Pick anything
- Click Reopen in Container

Remote Conteiners: Show Log
```
[4 ms] Remote-Containers 0.145.1 in VS Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a).
[22 ms] Start: Run: wsl -d fedoraremix
[288 ms] Stop (266 ms): Run: wsl -d fedoraremix
[289 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && wslpath '-w' '/home/lucky/tst'
[353 ms] Stop (64 ms): Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && wslpath '-w' '/home/lucky/tst'
[4648 ms] Start: Run: wsl -d fedoraremix
[4880 ms] Stop (232 ms): Run: wsl -d fedoraremix
[4881 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && docker 'version' '--format' '{{.Server.Version}}'
[4948 ms] Stop (67 ms): Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && docker 'version' '--format' '{{.Server.Version}}'
[4949 ms] 19.03.13
[4950 ms] Start: Run: wsl -d fedoraremix
[5184 ms] Stop (234 ms): Run: wsl -d fedoraremix
[5184 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && wslpath '-w' '/home/lucky/tst'
[5249 ms] Stop (65 ms): Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && wslpath '-w' '/home/lucky/tst'
[5250 ms] Start: Run: wsl -d fedoraremix -e wslpath -u \\wsl$\fedoraremix\home\lucky\tst
[5315 ms] Stop (65 ms): Run: wsl -d fedoraremix -e wslpath -u \\wsl$\fedoraremix\home\lucky\tst
[5315 ms] Start: Run: wsl -d fedoraremix
[5552 ms] Stop (237 ms): Run: wsl -d fedoraremix
[5552 ms] Start: Run: wsl -d fedoraremix
[5788 ms] Stop (236 ms): Run: wsl -d fedoraremix
[5788 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && docker 'version' '--format' '{{.Server.Version}}'
[5858 ms] Stop (70 ms): Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && docker 'version' '--format' '{{.Server.Version}}'
[5858 ms] 19.03.13
[5922 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && test '-f' '/home/lucky/tst/.devcontainer/devcontainer.json'
[5987 ms] Stop (65 ms): Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && test '-f' '/home/lucky/tst/.devcontainer/devcontainer.json'
[5988 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && cat '/home/lucky/tst/.devcontainer/devcontainer.json'
[6054 ms] Stop (66 ms): Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && cat '/home/lucky/tst/.devcontainer/devcontainer.json'
[6055 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && git 'rev-parse' '--show-toplevel'
[6120 ms] Stop (65 ms): Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && git 'rev-parse' '--show-toplevel'
[6121 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && cat '/home/lucky/tst/.devcontainer/Dockerfile'
[6186 ms] Stop (65 ms): Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && cat '/home/lucky/tst/.devcontainer/Dockerfile'
[8468 ms] Start: Run: wsl -d fedoraremix
[8706 ms] Stop (238 ms): Run: wsl -d fedoraremix
[8707 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && docker 'version' '--format' '{{.Server.Version}}'
[8775 ms] Stop (68 ms): Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && docker 'version' '--format' '{{.Server.Version}}'
[8775 ms] 19.03.13
[8776 ms] Start: Run: wsl -d fedoraremix -e wslpath -u \\wsl$\fedoraremix\home\lucky\tst
[8844 ms] Stop (68 ms): Run: wsl -d fedoraremix -e wslpath -u \\wsl$\fedoraremix\home\lucky\tst
[8844 ms] Start: Run: wsl -d fedoraremix
[9088 ms] Stop (244 ms): Run: wsl -d fedoraremix
[9089 ms] Start: Run: wsl -d fedoraremix
[9330 ms] Stop (241 ms): Run: wsl -d fedoraremix
[9331 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && docker 'version' '--format' '{{.Server.Version}}'
[9396 ms] Stop (65 ms): Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && docker 'version' '--format' '{{.Server.Version}}'
[9396 ms] 19.03.13
[9460 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && test '-f' '/home/lucky/tst/.devcontainer/devcontainer.json'
[9524 ms] Stop (64 ms): Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && test '-f' '/home/lucky/tst/.devcontainer/devcontainer.json'
[9524 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && cat '/home/lucky/tst/.devcontainer/devcontainer.json'
[9588 ms] Stop (64 ms): Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && cat '/home/lucky/tst/.devcontainer/devcontainer.json'
[9588 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && git 'rev-parse' '--show-toplevel'
[9651 ms] Stop (63 ms): Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && git 'rev-parse' '--show-toplevel'
[9652 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && cat '/home/lucky/tst/.devcontainer/Dockerfile'
[9715 ms] Stop (63 ms): Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && cat '/home/lucky/tst/.devcontainer/Dockerfile'
```

Dev Console
```
console.ts:137 [Extension Host] Error: ENOENT: no such file or directory, open 'c:\Users\Leshc\AppData\Roaming\Code\logs\20201030T151331\exthost7\ms-vscode-remote.remote-containers\remoteContainers-2020-10-30T10:13:34.315Z.log'
[Extension Host] Error: EEXIST: file already exists, mkdir 'c:\Users\Leshc\AppData\Roaming\Code\logs\20201030T151331\exthost7\ms-vscode-remote.remote-containers'
ERR Cannot read property 'endsWith' of undefined: TypeError: Cannot read property 'endsWith' of undefined
	at c:\Users\Leshc\.vscode\extensions\ms-vscode-remote.remote-containers-0.145.1\dist\extension.js:1:56800
	at Object.t.tildify (c:\Users\Leshc\.vscode\extensions\ms-vscode-remote.remote-containers-0.145.1\dist\extension.js:1:56854)
	at N (c:\Users\Leshc\.vscode\extensions\ms-vscode-remote.remote-containers-0.145.1\dist\extension.js:1:574472)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async B (c:\Users\Leshc\.vscode\extensions\ms-vscode-remote.remote-containers-0.145.1\dist\extension.js:1:560238)
```

**Last vscode setup without issues is:**
Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Remote WSL: v0.44.5
Remote Containers: v0.128.0

**Comment by chrmarti** [comment]
Could you check if this is fixed with the latest version 0.148.0 of the extension? You currently need VS Code Insiders to get that version (or the upcoming VS Code 1.51).

**Comment by LuckyRu** [comment]
Same behaviour.

Version: 1.51.0-insider (user setup)
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-04T18:31:15.290Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Remote-WSL: v0.51.1
Remote-Containers: v0.148.0

Remote Conteiners: Show Log
```
[10 ms] Remote-Containers 0.148.0 in VS Code 1.51.0-insider (fcac248b077b55bae4ba5bab613fd6e9156c2f0c).
[20 ms] Start: Run: wsl -d fedoraremix
[240 ms] Start: Run: wsl -d fedoraremix
[441 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && wslpath '-w' '/home/lucky/tst'
[574 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && test '-f' '\\wsl$\fedoraremix\home\lucky\tst/.devcontainer/devcontainer.json'
[643 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && test '-f' '\\wsl$\fedoraremix\home\lucky\tst/.devcontainer.json'
[7960 ms] Start: Run: wsl -d fedoraremix
[8158 ms] Start: Run: wsl -d fedoraremix
[8363 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && docker 'version' '--format' '{{.Server.Version}}'
[8456 ms] 19.03.13
[8458 ms] Start: Run: wsl -d fedoraremix
[8656 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && wslpath '-w' '/home/lucky/tst'
[8723 ms] Start: Run: wsl -d fedoraremix -e wslpath -u \\wsl$\fedoraremix\home\lucky\tst
[8794 ms] Start: Run: wsl -d fedoraremix
[9062 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && test '-f' '/home/lucky/tst/.devcontainer/devcontainer.json'
[9128 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && cat '/home/lucky/tst/.devcontainer/devcontainer.json'
[9195 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && git 'rev-parse' '--show-cdup'
[9262 ms] Start: Run: wsl -d fedoraremix -e /bin/sh -c cd '/home/lucky/tst' && cat '/home/lucky/tst/.devcontainer/Dockerfile'
```

Dev Console
```
ERR Cannot read property 'endsWith' of undefined: TypeError: Cannot read property 'endsWith' of undefined
	at c:\Users\Leshc\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.148.0\dist\extension.js:1:54879
	at Object.t.tildify (c:\Users\Leshc\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.148.0\dist\extension.js:1:54933)
	at N (c:\Users\Leshc\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.148.0\dist\extension.js:1:577684)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async B (c:\Users\Leshc\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.148.0\dist\extension.js:1:562349)
```

**Comment by chrmarti** [comment]
It looks like HOME is not set in WSL. What do you get for running this from PowerShell:
```
wsl -e /bin/bash -lc 'echo $HOME'
```

**Comment by LuckyRu** [comment]
```
wsl -d fedoraremix -e /bin/bash -lc 'echo $HOME'
/home/lucky
```

**Comment by LuckyRu** [comment]
Everything was fine on Remote-Containers v0.128.0. After VSCode update got this behavior. Downgrade fixing problem.

**Comment by chrmarti** [comment]
Could you try Remote-Containers 0.149.0 (currently requires VS Code Insiders)? I have fixed the issue with HOME not being set with that version.

**Comment by LuckyRu** [comment]
Yes, after update everything working like a charm! Thank you!
