### ISSUE TITLE
docker-compose remote-container fails to build or connect

### ISSUE THREAD

**Issue by djedlajn** [microsoft/vscode-remote-release#3931]
- VSCode Version: 1.50.1
- Local OS Version: OSX 10.15.6 (19G2021)
- Remote OS Version: Arch - Linux playground 5.9.1-arch1-1
- Remote Extension/Connection Type: SSH/Docker

tl;dr - docker-compose version of the remote container example found [here](https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host) does not appear to work.

Regular Dockerfile in conjunction with `devcontainer.json` works just fine. But docker-compose example fails.

From what I could tell ssh tunnel needed for remote docker.sock does not even get started.

Steps to Reproduce:

1. Try to open a remote folder in the container. `Via Rebuild and Reopen in Container` command

#### ssh-config
```
Host hetzner
  HostName addr.example
  User kadza
  Port 22
```

#### settings.json
```
"docker.host": "ssh://kadza@hetzner"
```

#### devcontainer.json

```
{
  "name": "Transfusion",
  "dockerComposeFile": "docker-compose.yml",
  "service": "transfusion",
  "workspaceFolder": "/workspace",
  "extensions": ["ms-azuretools.vscode-docker"],
  "workspaceMount": "source=/home/kadza/transfusion,target=/workspace,type=bind,consistency=cached"
}
```

#### container log

```
[2020-11-01T13:15:01.623Z] [PID 28792] [5 ms] Remote-Containers 0.145.1 in VS Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a).
[2020-11-01T13:15:01.692Z] [PID 28792] [74 ms] Start: Resolving remote
[2020-11-01T13:15:01.695Z] [PID 28792] [77 ms] Setting up container for folder or workspace: /Users/uroskaric/trans

[2020-11-01T13:15:02.149Z] [PID 28792] [531 ms] Start: Check Docker is running
[2020-11-01T13:15:02.151Z] [PID 28792] [532 ms] Start: Run: docker info
[2020-11-01T13:15:03.937Z] [PID 28792] [2319 ms] Start: Run: docker-compose version --short
[2020-11-01T13:15:05.243Z] [PID 28792] [3625 ms] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=trans_devcontainer --filter label=com.docker.compose.service=transfusion
[2020-11-01T13:15:05.953Z] [PID 28792] [4335 ms] Start: Run: docker-compose -f /Users/uroskaric/trans/.devcontainer/docker-compose.yml config --services
[2020-11-01T13:15:08.066Z] [PID 28792] [6448 ms] transfusion
[2020-11-01T13:15:08.067Z] [PID 28792] [6449 ms] 
[2020-11-01T13:15:08.069Z] [PID 28792] [6451 ms] Start: Run: docker events --format {{json .}} --filter status=start
[2020-11-01T13:15:08.083Z] [PID 28792] [6465 ms] Start: Run: docker-compose --project-name trans_devcontainer -f /Users/uroskaric/trans/.devcontainer/docker-compose.yml up -d --build
[2020-11-01T13:15:10.208Z] [PID 28792] Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
[2020-11-01T13:15:10.212Z] [PID 28792]   File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 125, in perform_command
  File "compose/cli/command.py", line 65, in project_from_options
  File "compose/cli/command.py", line 149, in get_project
[2020-11-01T13:15:10.269Z] [PID 28792]   File "compose/cli/command.py", line 120, in get_client
[2020-11-01T13:15:10.270Z] [PID 28792]   File "compose/cli/docker_client.py", line 127, in docker_client
[2020-11-01T13:15:10.270Z] [PID 28792]   File "site-packages/docker/api/client.py", line 166, in __init__
[2020-11-01T13:15:10.270Z] [PID 28792]   File "site-packages/docker/transport/sshconn.py", line 84, in __init__
[2020-11-01T13:15:10.271Z] [PID 28792]   File "site-packages/docker/transport/sshconn.py", line 94, in _connect
[2020-11-01T13:15:10.271Z] [PID 28792]   File "site-packages/paramiko/client.py", line 340, in connect
[2020-11-01T13:15:10.271Z] [PID 28792]   File "site-packages/paramiko/client.py", line 204, in _families_and_addresses
[2020-11-01T13:15:10.272Z] [PID 28792]   File "socket.py", line 748, in getaddrinfo
[2020-11-01T13:15:10.273Z] [PID 28792] socket.gaierror: [Errno 8] nodename nor servname provided, or not known
[2020-11-01T13:15:10.274Z] [PID 28792] [28908] 
[2020-11-01T13:15:10.275Z] [PID 28792] Failed to execute script docker-compose
[2020-11-01T13:15:10.620Z] [PID 28792] [9002 ms] Command failed: docker-compose --project-name trans_devcontainer -f /Users/uroskaric/trans/.devcontainer/docker-compose.yml up -d --build

```

**Comment by chrmarti** [comment]
Does it fail looking up the hostname you have configured in your SSH Config?

**Comment by djedlajn** [comment]
> Does it fail looking up the hostname you have configured in your SSH Config?

I would assume it does but don't see much in the logs that it does. What is strange is that it does work with plain Dockerfile correctly connects to SSH and goes trough to docker host of remote machine.

**Comment by chrmarti** [comment]
Can you run the command manually? (Setting the DOCKER_HOST environment variable to `ssh://kadza@hetzner`.)

**Comment by chrmarti** [comment]
Also try upgrading Docker Desktop, this looks like an issue in `docker-compose`.
