### ISSUE TITLE
Can't connect to remote host 

### ISSUE THREAD

**Issue by aigerimmaden96** [microsoft/vscode-remote-release#3934]
Can't connect to remote host from my Visual Studio Code

Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Output:
```
[13:30:52.668] Log Level: 2
[13:30:52.674] remote-ssh@0.55.0
[13:30:52.674] win32 x64
[13:30:52.676] SSH Resolver called for "ssh-remote+bastion.fuchicorp.com", attempt 1
[13:30:52.676] SSH Resolver called for host: bastion.fuchicorp.com
[13:30:52.676] Setting up SSH remote "bastion.fuchicorp.com"
[13:30:52.708] Using commit id "d2e414d9e4239a252d1ab117bd7067f125afd80a" and quality "stable" for server
[13:30:52.710] Install and start server if needed
[13:30:54.527] Checking ssh with "ssh -V"
[13:30:54.578] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[13:30:54.585] Running script with connection command: ssh -T -D 65521 bastion.fuchicorp.com bash
[13:30:54.588] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[13:30:56.108] > cfb7bf7658be: running
> ]0;C:\WINDOWS\System32\cmd.exe
[13:30:56.109] Got some output, clearing connection timeout
[13:30:56.113] > Acquiring lock on /home/aigerimmaden96/.vscode-server/bin/d2e414d9e4239a252d1ab1
> 17bd7067f125afd80a/vscode-remote-lock.aigerimmaden96.d2e414d9e4239a252d1ab117bd7
> 067f125afd80a
[13:30:56.134] > Installation already in progress...
> cfb7bf7658be##24##
[13:30:56.135] Received install output: cfb7bf7658be##24##
[13:30:56.135] Server installation process already in progress - waiting and retrying
[13:30:56.426] "install" terminal command done
[13:30:56.427] Install terminal quit with output: 
[13:30:58.982] Running script with connection command: ssh -T -D 65521 bastion.fuchicorp.com bash
[13:30:58.987] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[13:31:00.368] > cfb7bf7658be: running
> ]0;C:\WINDOWS\System32\cmd.exe
[13:31:00.368] Got some output, clearing connection timeout
[13:31:00.391] > Acquiring lock on /home/aigerimmaden96/.vscode-server/bin/d2e414d9e4239a252d1ab1
> 17bd7067f125afd80a/vscode-remote-lock.aigerimmaden96.d2e414d9e4239a252d1ab117bd7
> 067f125afd80a
[13:31:00.411] > Installation already in progress...
> cfb7bf7658be##24##
[13:31:00.411] Received install output: cfb7bf7658be##24##
[13:31:00.412] Server installation process already in progress - waiting and retrying
[13:31:00.718] "install" terminal command done
[13:31:00.719] Install terminal quit with output: 
[13:31:44.807] Running script with connection command: ssh -T -D 65521 bastion.fuchicorp.com bash
[13:31:44.809] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[13:31:46.178] > cfb7bf7658be: running
> ]0;C:\WINDOWS\System32\cmd.exe
[13:31:46.178] Got some output, clearing connection timeout
[13:31:46.217] > Acquiring lock on /home/aigerimmaden96/.vscode-server/bin/d2e414d9e4239a252d1ab1
> 17bd7067f125afd80a/vscode-remote-lock.aigerimmaden96.d2e414d9e4239a252d1ab117bd7
> 067f125afd80a
> Installation already in progress...
> cfb7bf7658be##24##
[13:31:46.217] Received install output: cfb7bf7658be##24##
[13:31:46.217] Server installation process already in progress - waiting and retrying
[13:31:46.528] "install" terminal command done
[13:31:46.528] Install terminal quit with output: 
[13:32:11.630] getPlatformForHost was canceled
[13:32:11.640] Resolver error: Error: Connecting was canceled
	at Function.Canceled (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:130798)
	at c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:104686
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.t.withShowDetailsEvent (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:109845)
	at async Object.t.resolve (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107960)
	at async c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:141955
[13:32:11.645] ------
```

Also tried to set terminal to Git bash which I use, nothing has changed

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by alkasm** [comment]
I am also unable to remote onto the ARM and X86 machines that I normally remote onto from macOS. I was using vscode earlier today with no problems, I don't think I updated vscode in-between either. It just continually pops up with attempting to reconnect. Here's output from the Remote - SSH extension while it's trying to reconnect to the arm machine:

```

[20:38:37.043] SSH Resolver called for "ssh-remote+arm", attempt 4, (Reconnection)
[20:38:37.043] SSH Resolver called for host: arm
[20:38:37.044] Setting up SSH remote "arm"
[20:38:37.045] Acquiring local install lock: /var/folders/1v/dvnfrhkx43x5lgg1810_2nmr0000gn/T/vscode-remote-ssh-arm-install.lock
[20:38:37.045] Looking for existing server data file at /Users/<host-username>/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-arm-d2e414d9e4239a252d1ab117bd7067f125afd80a-0.54.0/data.json
[20:38:37.046] Using commit id "d2e414d9e4239a252d1ab117bd7067f125afd80a" and quality "stable" for server
[20:38:37.047] Install and start server if needed
[20:38:37.050] askpass server listening on /var/folders/1v/dvnfrhkx43x5lgg1810_2nmr0000gn/T/vscode-ssh-askpass-e10f6cb87fad6274068bc91ec6ff682b45b00cab.sock
[20:38:37.050] Spawning local server with {"ipcHandlePath":"/var/folders/1v/dvnfrhkx43x5lgg1810_2nmr0000gn/T/vscode-ssh-askpass-52b1039b0df322bf8333438e3eaef72f70453405.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","51381","-o","ConnectTimeout=15","arm"],"dataFilePath":"/Users/<host-username>/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-arm-d2e414d9e4239a252d1ab117bd7067f125afd80a-0.54.0/data.json"}
[20:38:37.051] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/<host-username>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.54.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/<host-username>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.54.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/1v/dvnfrhkx43x5lgg1810_2nmr0000gn/T/vscode-ssh-askpass-e10f6cb87fad6274068bc91ec6ff682b45b00cab.sock"}
[20:38:37.055] Spawned 24111
[20:38:37.157] > local-server> Spawned ssh: 24112
[20:38:37.165] stderr> OpenSSH_7.9p1, LibreSSL 2.7.3
[20:38:37.326] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:ko49sKyFYiutq3xieI4y8hHntVbgw3q8hebLxPiuoto
[20:38:37.493] stderr> Authenticated to <remote-host> ([<remote-host>]:22).
[20:38:38.110] > Welcome to Ubuntu 18.04.4 LTS (GNU/Linux 5.3.0-1034-aws aarch64)

... <output from my machine>

[20:38:38.140] > ready: d4db72babc45
[20:38:38.171] > Linux 5.3.0-1034-aws #36-Ubuntu SMP Tue Aug 18 09:02:25 UTC 2020
[20:38:38.171] Platform: linux
[20:38:38.236] > d4db72babc45: running
[20:38:38.249] > Acquiring lock on /home/<remote-username>/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/vscode-remote-lock.<remote-username>.d2e414d9e4239a252d1ab117bd7067f125afd80a
[20:38:38.251] > Found existing installation at /home/<remote-username>/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a...
[20:38:38.310] > Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> Checking server status on port 43059 with wget
> d4db72babc45: start
> sshAuthSock====
> listeningOn==43059==
> osReleaseId==ubuntu==
> arch==aarch64==
> webUiAccessToken====
> tmpDir==/run/user/1007==
> platform==linux==
> d4db72babc45: end
[20:38:38.311] Received install output: 
sshAuthSock====
listeningOn==43059==
osReleaseId==ubuntu==
arch==aarch64==
webUiAccessToken====
tmpDir==/run/user/1007==
platform==linux==

[20:38:38.311] Remote server is listening on 43059
[20:38:38.311] Parsed server configuration: {"remoteListeningOn":{"port":43059},"osReleaseId":"ubuntu","arch":"aarch64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/1007","platform":"linux"}
[20:38:38.312] ** Note: Support for architecture "aarch64" is in preview **
[20:38:38.313] Persisting server connection details to /Users/<host-username>/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-arm-d2e414d9e4239a252d1ab117bd7067f125afd80a-0.54.0/data.json
[20:38:38.313] Starting forwarding server. localPort 51383 -> socksPort 51381 -> remotePort 43059
[20:38:38.314] Forwarding server listening on 51383
[20:38:38.314] Waiting for ssh tunnel to be ready
[20:38:38.314] [Forwarding server 51383] Got connection 0
[20:38:38.315] Tunneled 43059 to local port 51383
[20:38:38.315] Resolved "ssh-remote+arm" to "127.0.0.1:51383"
[20:38:38.318] ------




[20:38:38.330] [Forwarding server 51383] Got connection 1
[20:38:38.667] > local-server> ssh child died, shutting down
[20:38:38.672] Local server exit: 0
```

**Comment by alkasm** [comment]
I am also unable to remote onto the ARM and X86 machines that I normally remote onto from macOS. I was using vscode earlier today with no problems, I don't think I updated vscode in-between either. It just continually pops up with attempting to reconnect. 

<details>

<summary>Remote - SSH extension output while it's trying to reconnect to the arm machine</summary>

```
[20:38:37.043] SSH Resolver called for "ssh-remote+arm", attempt 4, (Reconnection)
[20:38:37.043] SSH Resolver called for host: arm
[20:38:37.044] Setting up SSH remote "arm"
[20:38:37.045] Acquiring local install lock: /var/folders/1v/dvnfrhkx43x5lgg1810_2nmr0000gn/T/vscode-remote-ssh-arm-install.lock
[20:38:37.045] Looking for existing server data file at /Users/<host-username>/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-arm-d2e414d9e4239a252d1ab117bd7067f125afd80a-0.54.0/data.json
[20:38:37.046] Using commit id "d2e414d9e4239a252d1ab117bd7067f125afd80a" and quality "stable" for server
[20:38:37.047] Install and start server if needed
[20:38:37.050] askpass server listening on /var/folders/1v/dvnfrhkx43x5lgg1810_2nmr0000gn/T/vscode-ssh-askpass-e10f6cb87fad6274068bc91ec6ff682b45b00cab.sock
[20:38:37.050] Spawning local server with {"ipcHandlePath":"/var/folders/1v/dvnfrhkx43x5lgg1810_2nmr0000gn/T/vscode-ssh-askpass-52b1039b0df322bf8333438e3eaef72f70453405.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","51381","-o","ConnectTimeout=15","arm"],"dataFilePath":"/Users/<host-username>/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-arm-d2e414d9e4239a252d1ab117bd7067f125afd80a-0.54.0/data.json"}
[20:38:37.051] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/<host-username>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.54.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/<host-username>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.54.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/1v/dvnfrhkx43x5lgg1810_2nmr0000gn/T/vscode-ssh-askpass-e10f6cb87fad6274068bc91ec6ff682b45b00cab.sock"}
[20:38:37.055] Spawned 24111
[20:38:37.157] > local-server> Spawned ssh: 24112
[20:38:37.165] stderr> OpenSSH_7.9p1, LibreSSL 2.7.3
[20:38:37.326] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:<some-sha>
[20:38:37.493] stderr> Authenticated to <remote-host> ([<remote-host>]:22).
[20:38:38.110] > Welcome to Ubuntu 18.04.4 LTS (GNU/Linux 5.3.0-1034-aws aarch64)

... <output from my machine>

[20:38:38.140] > ready: d4db72babc45
[20:38:38.171] > Linux 5.3.0-1034-aws #36-Ubuntu SMP Tue Aug 18 09:02:25 UTC 2020
[20:38:38.171] Platform: linux
[20:38:38.236] > d4db72babc45: running
[20:38:38.249] > Acquiring lock on /home/<remote-username>/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/vscode-remote-lock.<remote-username>.d2e414d9e4239a252d1ab117bd7067f125afd80a
[20:38:38.251] > Found existing installation at /home/<remote-username>/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a...
[20:38:38.310] > Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> Checking server status on port 43059 with wget
> d4db72babc45: start
> sshAuthSock====
> listeningOn==43059==
> osReleaseId==ubuntu==
> arch==aarch64==
> webUiAccessToken====
> tmpDir==/run/user/1007==
> platform==linux==
> d4db72babc45: end
[20:38:38.311] Received install output: 
sshAuthSock====
listeningOn==43059==
osReleaseId==ubuntu==
arch==aarch64==
webUiAccessToken====
tmpDir==/run/user/1007==
platform==linux==

[20:38:38.311] Remote server is listening on 43059
[20:38:38.311] Parsed server configuration: {"remoteListeningOn":{"port":43059},"osReleaseId":"ubuntu","arch":"aarch64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/1007","platform":"linux"}
[20:38:38.312] ** Note: Support for architecture "aarch64" is in preview **
[20:38:38.313] Persisting server connection details to /Users/<host-username>/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-arm-d2e414d9e4239a252d1ab117bd7067f125afd80a-0.54.0/data.json
[20:38:38.313] Starting forwarding server. localPort 51383 -> socksPort 51381 -> remotePort 43059
[20:38:38.314] Forwarding server listening on 51383
[20:38:38.314] Waiting for ssh tunnel to be ready
[20:38:38.314] [Forwarding server 51383] Got connection 0
[20:38:38.315] Tunneled 43059 to local port 51383
[20:38:38.315] Resolved "ssh-remote+arm" to "127.0.0.1:51383"
[20:38:38.318] ------




[20:38:38.330] [Forwarding server 51383] Got connection 1
[20:38:38.667] > local-server> ssh child died, shutting down
[20:38:38.672] Local server exit: 0
```
</details>

**Comment by Y0Q** [comment]
I am facing the same issue , deleting the .vscode-server on the remote machine allowed me to connect again. This might be a temporary mitigation for now.

**Comment by aigerimmaden96** [comment]
@Y0Q Thanks a lot it solved the issue
