### ISSUE TITLE
Prompt for Smartcard PIN code not showing

### ISSUE THREAD

**Issue by tecandrew** [microsoft/vscode-remote-release#3952]
I'm able to log into systems using Yubikey PIV, but VS Code doesn't prompt to enter pin using its password entry form. I have to switch to the Integrated Terminal to enter the PIN by clicking the blue _"(details)"_ link on the lower right pop-up. 

![image](https://user-images.githubusercontent.com/21319730/98161295-67033f00-1ed7-11eb-96bc-8ba657af4b4b.png)

## System Specs
Operating System: Windows 10
VS Code Version: 1.50.1
VS Code SSH Version: v0.55.0
OpenSSH Version: OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2
PKCS11 Version: libykcs11 , Version: yubico-piv-tool 2.1.1

## Log
```
[11:42:46.078] > #########################################################################
> WARNING:  Unauthorized access to this system is forbidden and will be
> prosecuted by law. By accessing this system, you agree that your actions
> may be monitored if unauthorized usage is suspected.
> #########################################################################
> Enter PIN for 'YubiKey PIV #9118035':
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[11:42:48.077] > 
[11:42:48.407] > 54d065b99cac: running
[11:42:48.482] > Acquiring lock on /home/andrest/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/vscode-remote-lock.andrest.d2e414d9e4239a252d1ab117bd7067f125afd80a
[11:42:48.512] > Found existing installation at /home/andrest/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a...
[11:42:48.532] > Found running server...
> 
> *
[11:42:48.539] > * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
[11:42:48.574] > Checking server status on port 36147 with wget 
> 54d065b99cac: start
> sshAuthSock==/tmp/ssh-mukE4xX5S7/agent.121492==
> listeningOn==36147==
> osReleaseId==ubuntu==
> arch==x86_64==
> webUiAccessToken====
> tmpDir==/run/user/1000==
> platform==linux==
> 54d065b99cac: end
[11:42:48.574] Received install output: 
sshAuthSock==/tmp/ssh-mukE4xX5S7/agent.121492==
listeningOn==36147==
osReleaseId==ubuntu==
arch==x86_64==
webUiAccessToken====
tmpDir==/run/user/1000==
platform==linux==

[11:42:48.575] Remote server is listening on 36147
[11:42:48.575] Parsed server configuration: {"remoteListeningOn":{"port":36147},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"/tmp/ssh-mukE4xX5S7/agent.121492","tmpDir":"/run/user/1000","platform":"linux"}
[11:42:48.576] Starting forwarding server. localPort 49190 -> socksPort 49158 -> remotePort 36147
[11:42:48.577] Forwarding server listening on 49190
[11:42:48.577] Waiting for ssh tunnel to be ready
[11:42:48.578] Tunneled 36147 to local port 49190
[11:42:48.578] Resolved "ssh-remote+trabus" to "127.0.0.1:49190"
[11:42:48.579] Updating $SSH_AUTH_SOCK: ln -f -s "/tmp/ssh-mukE4xX5S7/agent.121492" "/run/user/1000/vscode-ssh-auth-sock-442822169"
[11:42:48.580] Using cwd: vscode-remote://ssh-remote%2Btrabus/
[11:42:48.580] Remote extension host environment: {"SSH_AUTH_SOCK":"/run/user/1000/vscode-ssh-auth-sock-442822169"}
[11:42:48.580] [Forwarding server 49190] Got connection 0
[11:42:48.582] > 
[11:42:48.591] ------




[11:42:48.645] [Forwarding server 49190] Got connection 1
[11:42:48.646] [Forwarding server 49190] Got connection 2
[11:42:49.151] [Forwarding server 49190] Got connection 3
[11:42:50.392] "Update SSH_AUTH_SOCK" terminal command done
```

**Comment by roblourens** [comment]
Does it work if you set `"remote.SSH.useLocalServer": true` in settings.json?

**Comment by tecandrew** [comment]
Unfortunately, it doesn't. I can't even login to the system with that setting enabled.

Here's the log dump from the "details" link:

```
[13:04:58.776] Log Level: 2
[13:04:58.787] remote-ssh@0.55.0
[13:04:58.787] win32 x64
[13:04:58.789] SSH Resolver called for "ssh-remote+trabus", attempt 1
[13:04:58.789] SSH Resolver called for host: trabus
[13:04:58.789] Setting up SSH remote "trabus"
[13:04:58.793] Acquiring local install lock: C:\Users\ANDREW~1\AppData\Local\Temp\vscode-remote-ssh-trabus-install.lock
[13:04:58.815] Looking for existing server data file at c:\Users\Andrew Tec\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-ssh\vscode-ssh-host-trabus-fcac248b077b55bae4ba5bab613fd6e9156c2f0c-0.55.0\data.json
[13:04:58.815] Using commit id "fcac248b077b55bae4ba5bab613fd6e9156c2f0c" and quality "stable" for server
[13:04:58.816] Install and start server if needed
[13:04:58.818] Checking ssh with "ssh -V"
[13:04:58.866] > OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2

[13:04:58.869] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[13:04:58.870] Got error from ssh: spawn C:\WINDOWS\System32\OpenSSH\ssh.exe ENOENT
[13:04:58.871] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[13:04:58.930] > OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020

[13:04:58.936] Using SSH config file "C:\Users\Andrew Tec\.ssh\config"
[13:04:58.937] askpass server listening on \\.\pipe\vscode-ssh-askpass-0339538c5262fe0893838497ceefb5c80dc2d89b-sock
[13:04:58.937] Spawning local server with {"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-cae56e942bafbe2ba8290e73c44fc8ea08fe24ca-sock","sshCommand":"C:\\Program Files\\Git\\usr\\bin\\ssh.exe","sshArgs":["-v","-T","-D","57651","-F","C:\\Users\\Andrew Tec\\.ssh\\config","trabus"],"dataFilePath":"c:\\Users\\Andrew Tec\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-vscode-remote.remote-ssh\\vscode-ssh-host-trabus-fcac248b077b55bae4ba5bab613fd6e9156c2f0c-0.55.0\\data.json"}
[13:04:58.937] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"c:\\Users\\Andrew Tec\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.55.0\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"C:\\Program Files\\Microsoft VS Code\\Code.exe","VSCODE_SSH_ASKPASS_MAIN":"c:\\Users\\Andrew Tec\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.55.0\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-0339538c5262fe0893838497ceefb5c80dc2d89b-sock"}
[13:04:58.950] Spawned 24056
[13:04:59.047] > local-server> Spawned ssh: 50132
[13:04:59.096] stderr> OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020
[13:05:01.458] stderr> Exception: STATUS_ACCESS_VIOLATION at rip=0010044DA33
[13:05:01.459] stderr> rax=00007FF9BA4B1000 rbx=00000000FFFFB278 rcx=0000000000000000
[13:05:01.459] stderr> rdx=00000008000A25E0 rsi=00000000FFFFB280 rdi=0000000000000000
[13:05:01.459] stderr> r8 =000000000000000E r9 =000000080009200D r10=0000000000000000
[13:05:01.459] stderr> r11=000000010043EE63 r12=0000000800093F20 r13=00000008000A25E0
[13:05:01.459] stderr> r14=00007FF9BA490000 r15=0000000000000000
[13:05:01.459] stderr> rbp=00007FF9BA4916A0 rsp=00000000FFFFB050
[13:05:01.459] stderr> program=C:\Program Files\Git\usr\bin\ssh.exe, pid 1011, thread main
[13:05:01.460] stderr> cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
[13:05:01.460] stderr> Stack trace:
[13:05:01.460] stderr> Frame        Function    Args
[13:05:01.460] stderr> 7FF9BA4916A0  0010044DA33 (00800092650, 00000000016, 00800093E90, 001004AD840)
[13:05:01.460] stderr> 001004AD820  0010046B64D (0018023D800, 00000000007, 00000000000, 000FFFFCCE0)
[13:05:01.460] stderr> 000FFFFCCE0  0018004AF0A (00000000000, 00000000000, 00000000000, 00000000000)
[13:05:01.461] stderr> 000FFFFFFF0  00180048846 (00000000000, 00000000000, 00000000000, 00000000000)
[13:05:01.461] stderr> 000FFFFFFF0  001800488F4 (00000000000, 00000000000, 00000000000, 00000000000)
[13:05:01.461] stderr> End of stack trace
[13:05:01.462] > local-server> ssh child died, shutting down
[13:05:01.467] Server delay-shutdown request failed: connect ENOENT \\.\pipe\vscode-ssh-askpass-cae56e942bafbe2ba8290e73c44fc8ea08fe24ca-sock
[13:05:01.470] Local server exit: 0
[13:05:01.470] Received install output: OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020
Exception: STATUS_ACCESS_VIOLATION at rip=0010044DA33
rax=00007FF9BA4B1000 rbx=00000000FFFFB278 rcx=0000000000000000
rdx=00000008000A25E0 rsi=00000000FFFFB280 rdi=0000000000000000
r8 =000000000000000E r9 =000000080009200D r10=0000000000000000
r11=000000010043EE63 r12=0000000800093F20 r13=00000008000A25E0
r14=00007FF9BA490000 r15=0000000000000000
rbp=00007FF9BA4916A0 rsp=00000000FFFFB050
program=C:\Program Files\Git\usr\bin\ssh.exe, pid 1011, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
7FF9BA4916A0  0010044DA33 (00800092650, 00000000016, 00800093E90, 001004AD840)
001004AD820  0010046B64D (0018023D800, 00000000007, 00000000000, 000FFFFCCE0)
000FFFFCCE0  0018004AF0A (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180048846 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  001800488F4 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace

[13:05:01.471] Stopped parsing output early. Remaining text: OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020Exception: STATUS_ACCESS_VIOLATION at rip=0010044DA33rax=00007FF9BA4B1000 rbx=00000000FFFFB278 rcx=0000000000000000rdx=00000008000A25E0 rsi=00000000FFFFB280 rdi=0000000000000000r8 =000000000000000E r9 =000000080009200D r10=0000000000000000r11=000000010043EE63 r12=0000000800093F20 r13=00000008000A25E0r14=00007FF9BA490000 r15=0000000000000000rbp=00007FF9BA4916A0 rsp=00000000FFFFB050program=C:\Program Files\Git\usr\bin\ssh.exe, pid 1011, thread maincs=0033 ds=002B es=002B fs=0053 gs=002B ss=002BStack trace:Frame        Function    Args7FF9BA4916A0  0010044DA33 (00800092650, 00000000016, 00800093E90, 001004AD840)001004AD820  0010046B64D (0018023D800, 00000000007, 00000000000, 000FFFFCCE0)000FFFFCCE0  0018004AF0A (00000000000, 00000000000, 00000000000, 00000000000)000FFFFFFF0  00180048846 (00000000000, 00000000000, 00000000000, 00000000000)000FFFFFFF0  001800488F4 (00000000000, 00000000000, 00000000000, 00000000000)End of stack trace
[13:05:01.471] Failed to parse remote port from server output
[13:05:01.476] Resolver error: Error: 
	at Function.Create (c:\Users\Andrew Tec\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:130564)
	at Object.t.handleInstallOutput (c:\Users\Andrew Tec\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:127671)
	at Object.t.tryInstallWithLocalServer (c:\Users\Andrew Tec\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:102339)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\Andrew Tec\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:104310
	at async Object.t.withShowDetailsEvent (c:\Users\Andrew Tec\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:109845)
	at async c:\Users\Andrew Tec\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:100912
	at async R (c:\Users\Andrew Tec\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:97702)
	at async Object.t.resolveWithLocalServer (c:\Users\Andrew Tec\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:100561)
	at async Object.t.resolve (c:\Users\Andrew Tec\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107840)
	at async c:\Users\Andrew Tec\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:141955
[13:05:01.478] ------




[13:05:03.882] ssh is not exiting, continuing
```

**Comment by roblourens** [comment]
You can try setting `"remote.SSH.path": "C:\\WINDOWS\\System32\\OpenSSH\\ssh.exe"`, but it may not work. I try to use Git ssh when available to work around some issues that you may see in this mode.

**Comment by roblourens** [comment]
You can also get rid of all these settings and use `"remote.SSH.showLoginTerminal": true`

**Comment by tecandrew** [comment]
Yes, this solved the issue. I pointed `remote.SSH.path` to the custom install of ssh. I didn't realize I had this option.
