### ISSUE TITLE
VSCode cannot ssh to server, failed to connect

### ISSUE THREAD

**Issue by wj01011** [microsoft/vscode-remote-release#3955]
[01:05:21.203] Failed to parse remote port from server output
[01:05:21.209] Resolver error: Error: 
	at Function.Create (c:\Users\wendy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:130564)
	at Object.t.handleInstallOutput (c:\Users\wendy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:127671)
	at I (c:\Users\wendy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:106775)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\wendy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:104774
	at async Object.t.withShowDetailsEvent (c:\Users\wendy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:109845)
	at async Object.t.resolve (c:\Users\wendy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107960)
	at async c:\Users\wendy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:141955
[01:05:21.212] ------

I was able to ssh to my server using the terminal but it doesn't work remote-ssh: Connect to Host drop down window. It was working last week, not sure what happened. Please help, thanks.

**Comment by roblourens** [comment]
Please share the full log. You could also try running the command "Kill VS Code Server on Host" to see if that gets it to work.

**Comment by wj01011** [comment]
Where do I do this "kill VS Code Server on Host" ? sorry I'm not very technical
________________________________

**Comment by wj01011** [comment]
I reinstalled third time, delete all the old vscode file, now it seems to work. I think I might accidently modified the .json file by mistake, somehow it caused the error. It's working now, thanks.
________________________________
