### ISSUE TITLE
[SSH] Downgrading to 0.49 solved the connection issue 0.55.0

### ISSUE THREAD

**Issue by wyq977** [microsoft/vscode-remote-release#3958]
- VSCode Version: 1.50.1
- Local OS Version: Darwin x64 19.6.0
- Remote OS Version: 
- Remote Extension/Connection Type: SSH/Docker/WSL

```
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z (3 wks ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

Saw kind of similar issue in 2545 so I tried downgrade version, everything is fine except the folder name of remote SSH is not showing properly

![Screen Shot 2020-11-05 at 3 45 10 PM](https://user-images.githubusercontent.com/27303600/98255741-07ac3a00-1f7e-11eb-823b-00185064acd1.png)

Steps to Reproduce:

1. connect to ssh server from school
2. downgrading to 0.49 version, solved this issue with just folder name displayed incorrectly.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

Out put from Remote SSH 0.55.0
```
[15:34:01.919] Log Level: 2
[15:34:01.921] remote-ssh@0.55.0
[15:34:01.921] darwin x64
[15:34:01.923] SSH Resolver called for "ssh-remote+SSH_SERVER_ADDRESS", attempt 1
[15:34:01.923] SSH Resolver called for host: SSH_SERVER_ADDRESS
[15:34:01.923] Setting up SSH remote "SSH_SERVER_ADDRESS"
[15:34:01.926] Acquiring local install lock: /var/folders/_7/8gxnq4s54w9d3gypg7j4wffm0000gn/T/vscode-remote-ssh-SSH_SERVER_ADDRESS-install.lock
[15:34:01.940] Looking for existing server data file at /Users/BLURRED/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-SSH_SERVER_ADDRESS-d2e414d9e4239a252d1ab117bd7067f125afd80a-0.55.0/data.json
[15:34:01.941] Using commit id "d2e414d9e4239a252d1ab117bd7067f125afd80a" and quality "stable" for server
[15:34:01.943] Install and start server if needed
[15:34:01.948] Checking ssh with "ssh -V"
[15:34:01.956] > OpenSSH_8.1p1, LibreSSL 2.7.3

[15:34:01.976] askpass server listening on /var/folders/_7/8gxnq4s54w9d3gypg7j4wffm0000gn/T/vscode-ssh-askpass-bbeb77a0df3841142873f2af6b7630ffd0d32b9e.sock
[15:34:01.976] Spawning local server with {"ipcHandlePath":"/var/folders/_7/8gxnq4s54w9d3gypg7j4wffm0000gn/T/vscode-ssh-askpass-72596e0701daa6f1b85abf5c982149b59126dff7.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","57718","-o","ConnectTimeout=15","SSH_SERVER_ADDRESS"],"dataFilePath":"/Users/wyq-pc/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-SSH_SERVER_ADDRESS-d2e414d9e4239a252d1ab117bd7067f125afd80a-0.55.0/data.json"}
[15:34:01.976] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/BLURRED/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/wyq-pc/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/_7/8gxnq4s54w9d3gypg7j4wffm0000gn/T/vscode-ssh-askpass-bbeb77a0df3841142873f2af6b7630ffd0d32b9e.sock"}
[15:34:01.979] Spawned 73107
[15:34:02.065] > local-server> Spawned ssh: 73108
[15:34:02.068] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[15:34:02.447] stderr> Authenticated to SSH_SERVER_ADDRESS ([IP_ADDRESS]:22).
[15:34:02.961] > 
[15:34:03.463] > 
[15:34:03.464] stderr> -bash: line 1: ho: command not found
[15:34:18.985] Terminating local server
[15:34:18.989] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/BLURRED/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:130714)
	at Timeout._onTimeout (/Users/BLURRED/.vscode/extensions/ms-vscode-remote.remote-ssh-0.55.0/out/extension.js:1:325959)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)
[15:34:18.991] Local server exit: 15
[15:34:18.992] ------
```

Out put from Remote SSH 0.49.0
```
[15:39:13.944] Log Level: 3
[15:39:13.946] remote-ssh@0.49.0
[15:39:13.946] darwin x64
[15:39:13.947] SSH Resolver called for "ssh-remote+SSH_SERVER_ADDRESS", attempt 1
[15:39:13.947] SSH Resolver called for host: SSH_SERVER_ADDRESS
[15:39:13.947] Setting up SSH remote "SSH_SERVER_ADDRESS"
[15:39:13.959] Using commit id "d2e414d9e4239a252d1ab117bd7067f125afd80a" and quality "stable" for server
[15:39:13.960] Install and start server if needed
[15:39:13.963] Checking ssh with "ssh -V"
[15:39:13.972] > OpenSSH_8.1p1, LibreSSL 2.7.3
[15:39:13.973] Running script with connection command: ssh -T -D 57800 -o ConnectTimeout=15 SSH_SERVER_ADDRESS bash
[15:39:14.761] > d0981907275e: running
[15:39:14.761] Got some output, clearing connection timeout
[15:39:14.783] > Acquiring lock on /cluster/home/BLURRED/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/vscode-remote-lock.BLURRED.d2e414d9e4239a252d1ab117bd7067f125afd80a
[15:39:14.813] > Found existing installation at /cluster/home/BLURRED/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a...
[15:39:14.831] > MANPATH=/cluster/apps/modules/share/man:/cluster/apps/lsf/10.1/man::
> XDG_SESSION_ID=40982
> CONSUL_HTTP_ADDR=unix:///var/run/consul/http.sock
> SHELL=/bin/bash
> SSH_CLIENT=10.5.219.158 57802 22
> LSF_SERVERDIR=/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/etc
> QTDIR=/usr/lib64/qt-3.3
> QTINC=/usr/lib64/qt-3.3/include
> LSF_LIBDIR=/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib
> QT_GRAPHICSSYSTEM_CHECKED=1
> USER=BLURRED
> LD_LIBRARY_PATH=/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib:
> TMOUT=86400
> VSCODE_AGENT_FOLDER=/cluster/home/BLURRED/.vscode-server
> PATH=/cluster/home/BLURRED/bin:/usr/lib64/qt-3.3/bin:/cluster/apps/modules/bin:/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/bin:/usr/local/bin:/usr/bin:/cluster/apps/local
> MAIL=/var/mail/BLURRED
> LIBGL_ALWAYS_INDIRECT=1
> PWD=/cluster/home/BLURRED
> _LMFILES_=/cluster/apps/modules/modulefiles/modules
> LANG=en_US.UTF-8
> MODULEPATH=/cluster/apps/modules/modulefiles
> LOADEDMODULES=modules
> LSF_BINDIR=/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/bin
> HOME=/cluster/home/BLURRED
> SHLVL=2
> LOGNAME=BLURRED
> QTLIB=/usr/lib64/qt-3.3/lib
> SSH_CONNECTION=DELETED 22
> MODULESHOME=/cluster/apps/modules
> LESSOPEN=||/usr/bin/lesspipe.sh %s
> XDG_RUNTIME_DIR=/run/user/217245
> LSF_ENVDIR=/cluster/apps/lsf/conf
> SCRATCH=/cluster/scratch/BLURRED
> BASH_FUNC_module()=() {  eval `/cluster/apps/modules/bin/modulecmd bash $*`
> }
> _=/usr/bin/printenv
> Starting server...
> Waiting for server log...
[15:39:15.341] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[15:39:15.354] > d0981907275e: start
> sshAuthSock====
> agentPort==33667==
> osReleaseId==centos==
> arch==x86_64==
> webUiAccessToken====
> tmpDir==/run/user/217245==
> d0981907275e: end
[15:39:15.354] Received install output: 
sshAuthSock====
agentPort==33667==
osReleaseId==centos==
arch==x86_64==
webUiAccessToken====
tmpDir==/run/user/217245==

[15:39:15.355] Remote server is listening on port 33667
[15:39:15.355] Parsed server configuration: {"agentPort":33667,"osReleaseId":"centos","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/217245"}
[15:39:15.356] Starting forwarding server. localPort 57803 -> socksPort 57800 -> remotePort 33667
[15:39:15.356] Forwarding server listening on 57803
[15:39:15.356] Waiting for ssh tunnel to be ready
[15:39:15.357] [Forwarding server 57803] Got connection 0
[15:39:15.358] Tunneled remote port 33667 to local port 57803
[15:39:15.359] Resolved "ssh-remote+SSH_SERVER_ADDRESS" to "DELETED:57803"
[15:39:15.371] ------




[15:39:15.389] [Forwarding server 57803] Got connection 1
[15:39:15.389] [Forwarding server 57803] Got connection 2
[15:39:15.864] [Forwarding server 57803] Got connection 3
```

**Comment by roblourens** [comment]
Does setting `"remote.SSH.useLocalServer": false` help?

**Comment by wyq977** [comment]
Seems to connect to the server. Might I ask what the problem is? Thx a lot! 👍 


```
[11:27:02.650] Log Level: 2
[11:27:02.652] remote-ssh@0.55.0
[11:27:02.653] darwin x64
[11:27:02.654] SSH Resolver called for "ssh-remote+SSH_SERVER_ADDRESS", attempt 1
[11:27:02.655] SSH Resolver called for host: SSH_SERVER_ADDRESS
[11:27:02.655] Setting up SSH remote "SSH_SERVER_ADDRESS"
[11:27:02.667] Using commit id "fcac248b077b55bae4ba5bab613fd6e9156c2f0c" and quality "stable" for server
[11:27:02.672] Install and start server if needed
[11:27:05.303] Checking ssh with "ssh -V"
[11:27:05.311] > OpenSSH_8.1p1, LibreSSL 2.7.3

[11:27:05.314] Running script with connection command: ssh -T -D 50248 -o ConnectTimeout=15 SSH_SERVER_ADDRESS bash
[11:27:06.171] > 9a79948b83cf: running
[11:27:06.171] Got some output, clearing connection timeout
[11:27:06.200] > Acquiring lock on /cluster/home/MY_USERNAME/.vscode-server/bin/fcac248b077b55bae4ba5bab613fd6e9156c2f0c/vscode-remote-lock.MY_USERNAME.fcac248b077b55bae4ba5bab613fd6e9156c2f0c
[11:27:06.227] > Installing to /cluster/home/MY_USERNAME/.vscode-server/bin/fcac248b077b55bae4ba5bab613fd6e9156c2f0c...
> 9a79948b83cf%%1%%
[11:27:06.232] > Downloading with wget
[11:27:06.893] > Download complete
> 9a79948b83cf%%2%%
> tar --version:
> tar (GNU tar) 1.26
> Copyright (C) 2011 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[11:27:09.453] > MANPATH=/cluster/apps/modules/share/man:/cluster/apps/lsf/10.1/man::
> XDG_SESSION_ID=45628
> CONSUL_HTTP_ADDR=unix:///var/run/consul/http.sock
> SHELL=/bin/bash
> SSH_CLIENT=10.5.219.251 50250 22
> LSF_SERVERDIR=/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/etc
> QTDIR=/usr/lib64/qt-3.3
> QTINC=/usr/lib64/qt-3.3/include
> LSF_LIBDIR=/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib
> QT_GRAPHICSSYSTEM_CHECKED=1
> USER=MY_USERNAME
> LD_LIBRARY_PATH=/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib:
> TMOUT=86400
> VSCODE_AGENT_FOLDER=/cluster/home/MY_USERNAME/.vscode-server
> PATH=/cluster/home/MY_USERNAME/bin:/usr/lib64/qt-3.3/bin:/cluster/apps/modules/bin:/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/bin:/usr/local/bin:/usr/bin:/cluster/apps/local
> MAIL=/var/mail/MY_USERNAME
> LIBGL_ALWAYS_INDIRECT=1
> PWD=/cluster/home/MY_USERNAME
> _LMFILES_=/cluster/apps/modules/modulefiles/modules
> LANG=en_US.UTF-8
> MODULEPATH=/cluster/apps/modules/modulefiles
> LOADEDMODULES=modules
> LSF_BINDIR=/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/bin
> HOME=/cluster/home/MY_USERNAME
> SHLVL=2
> LOGNAME=MY_USERNAME
> QTLIB=/usr/lib64/qt-3.3/lib
> SSH_CONNECTION=10.5.219.251 50250 129.132.93.72 22
> MODULESHOME=/cluster/apps/modules
> LESSOPEN=||/usr/bin/lesspipe.sh %s
> XDG_RUNTIME_DIR=/run/user/217245
> LSF_ENVDIR=/cluster/apps/lsf/conf
> SCRATCH=/cluster/scratch/MY_USERNAME
> BASH_FUNC_module()=() {  eval `/cluster/apps/modules/bin/modulecmd bash $*`
> }
> _=/usr/bin/printenv
> OLDPWD=/cluster/home/MY_USERNAME/.vscode-server/bin/fcac248b077b55bae4ba5bab613fd6e9156c2f0c
> Starting server with command... /cluster/home/MY_USERNAME/.vscode-server/bin/fcac248b077b55bae4ba5bab613fd6e9156c2f0c/server.sh --host=DELETED --enable-remote-auto-shutdown  --port=0 &> "/cluster/home/MY_USERNAME/.vscode-server/.fcac248b077b55bae4ba5bab613fd6e9156c2f0c.log" < /dev/null
> cat: /cluster/home/MY_USERNAME/.vscode-server/.fcac248b077b55bae4ba5bab613fd6e9156c2f0c.log: No such file or directory
> Waiting for server log...
[11:27:09.962] > Waiting for server log...
[11:27:10.466] > Waiting for server log...
[11:27:10.968] > Waiting for server log...
[11:27:11.473] > Waiting for server log...
[11:27:11.977] > Waiting for server log...
[11:27:12.480] > Waiting for server log...
[11:27:12.985] > Waiting for server log...
[11:27:13.485] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[11:27:13.494] > 9a79948b83cf: start
> sshAuthSock====
> listeningOn==44427==
> osReleaseId==centos==
> arch==x86_64==
> webUiAccessToken====
> tmpDir==/run/user/217245==
> platform==linux==
> 9a79948b83cf: end
[11:27:13.494] Received install output: 
sshAuthSock====
listeningOn==44427==
osReleaseId==centos==
arch==x86_64==
webUiAccessToken====
tmpDir==/run/user/217245==
platform==linux==

[11:27:13.495] Remote server is listening on 44427
[11:27:13.495] Parsed server configuration: {"remoteListeningOn":{"port":44427},"osReleaseId":"centos","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/217245","platform":"linux"}
[11:27:13.496] Starting forwarding server. localPort 50253 -> socksPort 50248 -> remotePort 44427
[11:27:13.496] Forwarding server listening on 50253
[11:27:13.497] Waiting for ssh tunnel to be ready
[11:27:13.498] [Forwarding server 50253] Got connection 0
[11:27:13.499] Tunneled 44427 to local port 50253
[11:27:13.500] Resolved "ssh-remote+SSH_SERVER_ADDRESS" to "DELETED:50253"
[11:27:13.510] ------




[11:27:13.529] [Forwarding server 50253] Got connection 1
[11:27:13.529] [Forwarding server 50253] Got connection 2
```

**Comment by wyq977** [comment]
@roblourens Do u need more info from my end?

I saw the troubleshooting here: https://code.visualstudio.com/docs/remote/troubleshooting#_troubleshooting-hanging-or-failing-connections

BTW, if i have sth in my `~/.bash_rc` to wait for input upone logining onto my server, would the remote-shh hangs?

**Comment by roblourens** [comment]
> BTW, if i have sth in my ~/.bash_rc to wait for input upone logining onto my server, would the remote-shh hangs?

This sounds kind of relevant, can you tell me more about this?

**Comment by wyq977** [comment]
This is the bash_profile I have to load up the modules I needed

```bash
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH

read -p "Load python/3.6.1 NOW? [Y/y] " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "Loading python/3.6.1                                                     "
    echo 
    module load new gcc/4.8.2 python/3.6.1
fi

sleep .5

read -p "Load LBIBCell NOW? [Y/y] " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "Loading new, boost/1.57.0 vtk/6.1.0 gcc/4.9.2 qt/5.5.0 netcdf open_mpi   "
    module load new
    module load boost/1.57.0
    module load vtk/6.1.0
    module load gcc/4.9.2
    module load qt/5.5.0
    module load netcdf
    module load open_mpi
fi
```

**Comment by wyq977** [comment]
In the latest release, deleting the above bash_profile let me connet to the remote shh server without

```json
     "remote.SSH.showLoginTerminal": true,
     "remote.SSH.useLocalServer": false,
```
<details>
  <summary>Log without bash_profile</summary>

```
[10:20:20.957] Log Level: 2
[10:20:20.960] remote-ssh@0.56.0
[10:20:20.960] darwin x64
[10:20:20.961] SSH Resolver called for "ssh-remote+SSH_SERVER_ADDRESS", attempt 1
[10:20:20.962] SSH Resolver called for host: SSH_SERVER_ADDRESS
[10:20:20.962] Setting up SSH remote "SSH_SERVER_ADDRESS"
[10:20:20.964] Acquiring local install lock: /var/folders/_7/8gxnq4s54w9d3gypg7j4wffm0000gn/T/vscode-remote-ssh-SSH_SERVER_ADDRESS-install.lock
[10:20:20.975] Looking for existing server data file at /Users/BLURRED/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-SSH_SERVER_ADDRESS-fcac248b077b55bae4ba5bab613fd6e9156c2f0c-0.56.0/data.json
[10:20:20.979] Using commit id "fcac248b077b55bae4ba5bab613fd6e9156c2f0c" and quality "stable" for server
[10:20:20.982] Install and start server if needed
[10:20:20.987] Checking ssh with "ssh -V"
[10:20:21.006] > OpenSSH_8.1p1, LibreSSL 2.7.3

[10:20:21.024] askpass server listening on /var/folders/_7/8gxnq4s54w9d3gypg7j4wffm0000gn/T/vscode-ssh-askpass-705306e9b9a33d047605fc979d0558322d4a1eaa.sock
[10:20:21.024] Spawning local server with {"ipcHandlePath":"/var/folders/_7/8gxnq4s54w9d3gypg7j4wffm0000gn/T/vscode-ssh-askpass-2cb86e0a08e18e3f5a54c4acef7c49703da4f93f.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","60170","-o","ConnectTimeout=15","SSH_SERVER_ADDRESS"],"dataFilePath":"/Users/BLURRED/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-SSH_SERVER_ADDRESS-fcac248b077b55bae4ba5bab613fd6e9156c2f0c-0.56.0/data.json"}
[10:20:21.024] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/BLURRED/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/BLURRED/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/_7/8gxnq4s54w9d3gypg7j4wffm0000gn/T/vscode-ssh-askpass-705306e9b9a33d047605fc979d0558322d4a1eaa.sock"}
[10:20:21.030] Spawned 75836
[10:20:21.133] > local-server> Spawned ssh: 75837
[10:20:21.138] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[10:20:21.437] stderr> Authenticated to SSH_SERVER_ADDRESS ([129.132.93.72]:22).
[10:20:21.670] > ready: ec7402fec3e9
[10:20:21.679] > Linux 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020
[10:20:21.679] Platform: linux
[10:20:21.704] > ec7402fec3e9: running
[10:20:21.729] > Acquiring lock on /cluster/home/MY_USERNAME/.vscode-server/bin/fcac248b077b55bae4ba5bab613fd6e9156c2f0c/vscode-remote-lock.MY_USERNAME.fcac248b077b55bae4ba5bab613fd6e9156c2f0c
[10:20:21.754] > Found existing installation at /cluster/home/MY_USERNAME/.vscode-server/bin/fcac248b077b55bae4ba5bab613fd6e9156c2f0c...
> Checking /cluster/home/MY_USERNAME/.vscode-server/.fcac248b077b55bae4ba5bab613fd6e9156c2f0c.log and /cluster/home/MY_USERNAME/.vscode-server/.fcac248b077b55bae4ba5bab613fd6e9156c2f0c.pid for a running server
[10:20:21.873] > Starting server with command... /cluster/home/MY_USERNAME/.vscode-server/bin/fcac248b077b55bae4ba5bab613fd6e9156c2f0c/server.sh --host=DELETED --enable-remote-auto-shutdown  --port=0 &> "/cluster/home/MY_USERNAME/.vscode-server/.fcac248b077b55bae4ba5bab613fd6e9156c2f0c.log" < /dev/null
> printenv:
[10:20:21.875] >     MANPATH=/cluster/apps/modules/share/man:/cluster/apps/lsf/10.1/man::
>     XDG_SESSION_ID=44580
>     CONSUL_HTTP_ADDR=unix:///var/run/consul/http.sock
>     HOSTNAME=eu-login-19
>     SHELL=/bin/bash
>     HISTSIZE=1000
>     SSH_CLIENT=10.5.220.228 60172 22
>     LSF_SERVERDIR=/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/etc
>     QTDIR=/usr/lib64/qt-3.3
>     QTINC=/usr/lib64/qt-3.3/include
>     LSF_LIBDIR=/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib
>     QT_GRAPHICSSYSTEM_CHECKED=1
>     USER=MY_USERNAME
>     LD_LIBRARY_PATH=/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/lib:
>     TMOUT=86400
>     VSCODE_AGENT_FOLDER=/cluster/home/MY_USERNAME/.vscode-server
>     PATH=/cluster/home/MY_USERNAME/bin:/usr/lib64/qt-3.3/bin:/cluster/apps/modules/bin:/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/cluster/apps/local:/cluster/home/MY_USERNAME/.local/bin:/cluster/home/MY_USERNAME/bin
>     MAIL=/var/spool/mail/MY_USERNAME
>     LIBGL_ALWAYS_INDIRECT=1
>     PWD=/cluster/home/MY_USERNAME
>     _LMFILES_=/cluster/apps/modules/modulefiles/modules
>     LANG=en_US.UTF-8
>     MODULEPATH=/cluster/apps/modules/modulefiles
>     LOADEDMODULES=modules
>     LSF_BINDIR=/cluster/apps/lsf/10.1/linux2.6-glibc2.3-x86_64/bin
>     HISTCONTROL=ignoredups
>     HOME=/cluster/home/MY_USERNAME
>     SHLVL=2
>     LOGNAME=MY_USERNAME
>     QTLIB=/usr/lib64/qt-3.3/lib
>     SSH_CONNECTION=10.5.220.228 60172 129.132.93.72 22
>     MODULESHOME=/cluster/apps/modules
>     LESSOPEN=||/usr/bin/lesspipe.sh %s
>     XDG_RUNTIME_DIR=/run/user/217245
>     LSF_ENVDIR=/cluster/apps/lsf/conf
>     SCRATCH=/cluster/scratch/MY_USERNAME
>     BASH_FUNC_module()=() {  eval `/cluster/apps/modules/bin/modulecmd bash $*`
>     }
>     _=/usr/bin/printenv
[10:20:21.876] > Spawned remote server: 16376
[10:20:21.880] > Waiting for server log...
[10:20:22.385] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[10:20:22.391] > ec7402fec3e9: start
> sshAuthSock====
> listeningOn==46063==
[10:20:22.392] > osReleaseId==centos==
> arch==x86_64==
> webUiAccessToken====
> tmpDir==/run/user/217245==
> platform==linux==
> ec7402fec3e9: end
[10:20:22.392] Received install output: 
sshAuthSock====
listeningOn==46063==osReleaseId==centos==
arch==x86_64==
webUiAccessToken====
tmpDir==/run/user/217245==
platform==linux==

[10:20:22.393] Remote server is listening on 46063
[10:20:22.393] Parsed server configuration: {"remoteListeningOn":{"port":46063},"osReleaseId":"centos","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/217245","platform":"linux"}
[10:20:22.394] Persisting server connection details to /Users/BLURRED/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-SSH_SERVER_ADDRESS-fcac248b077b55bae4ba5bab613fd6e9156c2f0c-0.56.0/data.json
[10:20:22.396] Starting forwarding server. localPort 60175 -> socksPort 60170 -> remotePort 46063
[10:20:22.396] Forwarding server listening on 60175
[10:20:22.396] Waiting for ssh tunnel to be ready
[10:20:22.401] [Forwarding server 60175] Got connection 0
[10:20:22.402] Tunneled 46063 to local port 60175
[10:20:22.403] Resolved "ssh-remote+SSH_SERVER_ADDRESS" to "DELETED:60175"
[10:20:22.451] ------




[10:20:22.505] [Forwarding server 60175] Got connection 1
[10:20:22.505] [Forwarding server 60175] Got connection 2
[10:20:28.002] [Forwarding server 60175] Got connection 3
```
</details>

But with those bash_profile, I ended up with similar errors I described before

<details>
  <summary>Log with bash_profile</summary>

```
[10:24:47.648] Log Level: 2
[10:24:47.649] remote-ssh@0.56.0
[10:24:47.649] darwin x64
[10:24:47.650] SSH Resolver called for "ssh-remote+SHH_ADDRESS", attempt 1
[10:24:47.651] SSH Resolver called for host: SHH_ADDRESS
[10:24:47.651] Setting up SSH remote "SHH_ADDRESS"
[10:24:47.653] Acquiring local install lock: /var/folders/_7/8gxnq4s54w9d3gypg7j4wffm0000gn/T/vscode-remote-ssh-SHH_ADDRESS-install.lock
[10:24:47.663] Looking for existing server data file at /Users/BLUR/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-SHH_ADDRESS-fcac248b077b55bae4ba5bab613fd6e9156c2f0c-0.56.0/data.json
[10:24:47.664] Using commit id "fcac248b077b55bae4ba5bab613fd6e9156c2f0c" and quality "stable" for server
[10:24:47.665] Install and start server if needed
[10:24:47.668] Checking ssh with "ssh -V"
[10:24:47.676] > OpenSSH_8.1p1, LibreSSL 2.7.3

[10:24:47.680] askpass server listening on /var/folders/_7/8gxnq4s54w9d3gypg7j4wffm0000gn/T/vscode-ssh-askpass-9e1ce8dfacdf799334b4d5c390b6000f54bd0dbf.sock
[10:24:47.680] Spawning local server with {"ipcHandlePath":"/var/folders/_7/8gxnq4s54w9d3gypg7j4wffm0000gn/T/vscode-ssh-askpass-1961bf6334c46d8ad0cfeb284ff751e2bc588ab4.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","60240","-o","ConnectTimeout=15","SHH_ADDRESS"],"dataFilePath":"/Users/BLUR/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-SHH_ADDRESS-fcac248b077b55bae4ba5bab613fd6e9156c2f0c-0.56.0/data.json"}
[10:24:47.680] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/BLUR/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/BLUR/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/_7/8gxnq4s54w9d3gypg7j4wffm0000gn/T/vscode-ssh-askpass-9e1ce8dfacdf799334b4d5c390b6000f54bd0dbf.sock"}
[10:24:47.683] Spawned 75934
[10:24:47.767] > local-server> Spawned ssh: 75935
[10:24:47.771] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[10:24:48.074] stderr> Authenticated to SHH_ADDRESS ([BLUR]:22).
[10:24:48.597] > 
[10:24:49.099] > 
[10:24:49.101] stderr> -bash: line 1: ho: command not found
```
</details>

**Comment by roblourens** [comment]
`sleep .5` I'm sure this kind of thing is the problem. I think we start sending input while the sleep is happening, and it just gets lost.
