### ISSUE TITLE
Bad owner or permissions on C:\\Users\\del/.ssh/config

### ISSUE THREAD

**Issue by chrisyxue** [microsoft/vscode-remote-release#3967]
The error is printed as :

""
Resolver error: Error: 
	at Function.Create (c:\Users\del\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:130564)
	at Object.t.handleInstallOutput (c:\Users\del\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:1:127671)
	at I (c:\Users\del\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:106775)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\del\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:104774
	at async Object.t.withShowDetailsEvent (c:\Users\del\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:109845)
	at async Object.t.resolve (c:\Users\del\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:107960)
	at async c:\Users\del\.vscode\extensions\ms-vscode-remote.remote-ssh-0.55.0\out\extension.js:127:141955
""

Could you please tell me how to solve it?

**Comment by solinad21** [comment]
me too have this problem

**Comment by roblourens** [comment]
Sounds like you need https://code.visualstudio.com/docs/remote/troubleshooting#_local-ssh-file-and-folder-permissions
