### ISSUE TITLE
Provide a CLI option that can open a URL in a browser page 

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#3992]
Currently node CLI apps that use the `opn` to open a browser do not work when run in a remote context.

To support this, the code CLI available in a remote context should provide a CLI option/command (e.g. `code-open`) that opens a URL in the local browser from the locally running VS Code .

The `opn` module which uses the `xdg-open` utility supports a `BROWSER` environment variable. `BROWSER` is a similar environment variable like `EDITOR`, it contains the path to the web browser. Now, when a remote context defines this environment variable BROWSER with the code command, then the `opn` module also works in the remote context. 

Test case:

1. npx create-react-app my-app
2. cd my-app
3. npm start

This should open the webpage for the react app in a browser.

**Comment by egamma** [comment]
@aeschli tested in Codespaces.

The environment variable is set:
```
echo $BROWSER
/home/codespace/.vscode-remote/bin/caf01baa45b9816e2e1d8a2de22b40cf89459c03/bin/code-insiders --openExternal
```

Running the sample in a Codespace
```
npx create-react-app my-app
cd my-app
npm start
```

Results in the following error:
```
Starting the development server...

events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/codespace/.vscode-remote/bin/caf01baa45b9816e2e1d8a2de22b40cf89459c03/bin/code-insiders --openExternal ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /home/codespace/.vscode-remote/bin/caf01baa45b9816e2e1d8a2de22b40cf89459c03/bin/code-insiders --openExternal',
  path: '/home/codespace/.vscode-remote/bin/caf01baa45b9816e2e1d8a2de22b40cf89459c03/bin/code-insiders --openExternal',
  spawnargs: [ 'http://localhost:3000' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
