### ISSUE TITLE
remote connection fails with Broken pipe, and shuts down remote ssh server

### ISSUE THREAD

**Issue by mitchwoodside** [microsoft/vscode-remote-release#4004]
I have looked over the issues here to see if this has been solved but I can't find reference to it here or elsewhere.

- VSCode Version: 1.52.0-insider
- Local OS Version: Linux x64 5.4.74-1-MANJARO
- Remote OS Version: Windows 10 Pro 19041.630
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1. Open remote window
2. Enter user@ip for hostname
3. Choose "Windows" server

Does this issue occur when you try this locally?: No, N/A
Does this issue occur when you try this locally and all extensions are disabled?: No, N/A

It's worth noting that I can connect over ssh just fine via the terminal.

```
[11:57:36.083] Log Level: 1
[11:57:36.085] remote-ssh@0.56.0
[11:57:36.085] linux x64
[11:57:36.087] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a2231302e38382e3131312e38222c2275736572223a226d776f6f6473696465227d", attempt 1
[11:57:36.088] SSH Resolver called for host: mitch@10.88.111.1
[11:57:36.088] Setting up SSH remote "10.88.111.8"
[11:57:36.102] Using commit id "65f805d98e798b979901b74d4c8810c05455b792" and quality "insider" for server
[11:57:36.103] Install and start server if needed
[11:57:37.868] Checking ssh with "ssh -V"
[11:57:37.880] > OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020

[11:57:37.882] Remote command length: 7905/8192 characters
[11:57:37.884] Running script with connection command: ssh -T -D 39809 -o ConnectTimeout=3600 mitch@10.88.111.1 powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -Command "powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -EncodedCommand \$([Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('CmVjaG8gIjVlMzQ4ZTMzNTIxMDogcnVubmluZyIKJFByb2dyZXNzUHJlZmVyZW5jZT0nU2lsZW50bHlDb250aW51ZScKJGNvbW1pdElkPSc2NWY4MDVkOThlNzk4Yjk3OTkwMWI3NGQ0Yzg4MTBjMDU0NTViNzkyJwokcD0kZW52OlBST0NFU1NPUl9BUkNISVRFQ1RVUkUKJGFyY2g9aWYgKCgkcCAtZXEgJ0FNRDY0JykgLW9yICgkcCAtZXEgJ0lBNjQnKSkgeyAneDY0JyB9IGVsc2UgeyAnaWEzMicgfQokc2VydmVyUm9vdD0oSm9pbi1QYXRoIChSZXNvbHZlLVBhdGggfikgJy52c2NvZGUtc2VydmVyLWluc2lkZXJzJykKJGVudjpWU0NPREVfQUdFTlRfRk9MREVSPSRzZXJ2ZXJSb290CiRsb2c9IiRzZXJ2ZXJSb290XC4kY29tbWl0SWQubG9nIgokc0Rpcj0iJHNlcnZlclJvb3RcYmluXCRjb21taXRJZCIKJHF1YWxpdHk9J2luc2lkZXInCiR0ZWxlbWV0cnk9IiIKJGV4dHM9IiIKZnVuY3Rpb24gZGV0YWlscyB7CmVjaG8gImxpc3RlbmluZ09uPT0kcG9ydD09IgplY2hvICJvc1JlbGVhc2VJZD09d2luZG93cz09IgplY2hvICJvc1ZlcnNpb249PSR3aW5WZXJzaW9uPT0iCmVjaG8gImFyY2g9PSRhcmNoPT0iCmVjaG8gInBsYXRmb3JtPT13aW5kb3dzPT0iCn0KZnVuY3Rpb24gcSgkY29kZSkgewplY2hvICI1ZTM0OGUzMzUyMTA6IHN0YXJ0IgplY2hvICJleGl0Q29kZT09JGNvZGU9PSIKZGV0YWlscwplY2hvICI1ZTM0OGUzMzUyMTA6IGVuZCIKfQpmdW5jdGlvbiBnZXRTc2hkUGFyZW50UGlkIHsKJGN1cnJlbnRQSUQ9JFBJRAp3aGlsZSAoJFRydWUpIHsKJHBhcmVudFBJRD0oR2V0LUNpbUluc3RhbmNlIHdpbjMyX3Byb2Nlc3MgfCA/IHByb2Nlc3NpZCAtZXEgJGN1cnJlbnRQSUQpLnBhcmVudHByb2Nlc3NpZAppZiAoISRwYXJlbnRQSUQpIHsKZWNobyAibm8gc3NoZCBwYXJlbnQgcHJvYyIKZXhpdCAwCn0KaWYgKChncHMgLUlkICRwYXJlbnRQSUQpLk5hbWUgLWVxICdzc2hkJykgewpyZXR1cm4gJHBhcmVudFBJRAp9CiRjdXJyZW50UElEPSRwYXJlbnRQSUQKfQp9CmZ1bmN0aW9uIGV4aXRJZk5lZWRlZCB7CmlmICgkbGF1bmNoZWRTZXJ2ZXJQaWQpIHsKaWYgKCEoZ3BzIC1JZCAkbGF1bmNoZWRTZXJ2ZXJQaWQpKSB7CmVjaG8gIlRoZSBsYXVuY2hlZCBzZXJ2ZXIgZGllZCwgZXhpdGluZyIKZXhpdCAwCn0KfSBlbHNlIHsKaWYgKCEoZ3BzIC1JZCAkc3NoZFBJRCkpIHsKZWNobyAiVGhlIHNzaGQgcGFyZW50IGRpZWQsIGV4aXRpbmciCmV4aXQgMAp9Cn0KfQpmdW5jdGlvbiBEb3dubG9hZFNlcnZlciB7CmVjaG8gIkRvd25sb2FkaW5nIFZTIENvZGUgU2VydmVyIgplY2hvICc1ZTM0OGUzMzUyMTAlJTElJScKJHdlYlBhcnQ9IiIKJGFyY2hQYXJ0PWlmICgkYXJjaCAtZXEgJ3g2NCcpIHsgIi0kYXJjaCIgfSBlbHNlIHsgIiIgfQokc2VydmVyTmFtZT0ic2VydmVyLXdpbjMyJGFyY2hQYXJ0IiArICR3ZWJQYXJ0CiRzcGxhdD1AewpVcmk9Imh0dHBzOi8vdXBkYXRlLmNvZGUudmlzdWFsc3R1ZGlvLmNvbS9jb21taXQ6JGNvbW1pdElkLyRzZXJ2ZXJOYW1lLyRxdWFsaXR5IgpUaW1lb3V0U2VjPTIwCk91dEZpbGU9InZzY29kZS1zZXJ2ZXIuemlwIgpVc2VCYXNpY1BhcnNpbmc9JFRydWUKfQpbTmV0LlNlcnZpY2VQb2ludE1hbmFnZXJdOjpTZWN1cml0eVByb3RvY29sID0gW05ldC5TZXJ2aWNlUG9pbnRNYW5hZ2VyXTo6U2VjdXJpdHlQcm90b2NvbCAtYm9yIFtOZXQuU2VjdXJpdHlQcm90b2NvbFR5cGVdOjpUbHMxMgpJbnZva2UtUmVzdE1ldGhvZCBAc3BsYXQKfQpmdW5jdGlvbiBJbnN0YWxsU2VydmVyIHsKJHJhbmRvbURpck5hbWU9W1N5c3RlbS5JTy5QYXRoXTo6R2V0UmFuZG9tRmlsZU5hbWUoKQokdG1wRGVzdD0iJGVudjpURU1QXCRyYW5kb21EaXJOYW1lIgplY2hvICJFeHBhbmRpbmcgc2VydmVyIGludG8gJHRtcERlc3QiCmVjaG8gJzVlMzQ4ZTMzNTIxMCUlMiUlJwpFeHBhbmQtQXJjaGl2ZSAidnNjb2RlLXNlcnZlci56aXAiIC1EZXN0aW5hdGlvblBhdGggIiR0bXBEZXN0IgptdiAiJHRtcERlc3RcdnNjb2RlLSpcKiIgLURlc3RpbmF0aW9uIC4KfQpmdW5jdGlvbiBEb0NsaWVudERvd25sb2FkIHsKZWNobyAiVHJpZ2dlciBjbGllbnQgc2VydmVyIGRvd25sb2FkIgplY2hvIDVlMzQ4ZTMzNTIxMDp0cmlnZ2VyX3NlcnZlcl9kb3dubG9hZAplY2hvIHBsYXRmb3JtPT13aW5kb3dzPT0KZWNobyB2c2NvZGVBcmNoPT0kYXJjaD09CmVjaG8gZGVzdEZvbGRlcj09JHNEaXI9PQplY2hvIDVlMzQ4ZTMzNTIxMDp0cmlnZ2VyX3NlcnZlcl9kb3dubG9hZF9lbmQKZWNobyAiV2FpdGluZyBmb3IgY2xpZW50IHRvIHRyYW5zZmVyIHNlcnZlciBhcmNoaXZlLi4uIgplY2hvICJXYWl0aW5nIGZvciAkc0Rpclx2c2NvZGUtc2NwLWRvbmUuZmxhZyBhbmQgdnNjb2RlLXNlcnZlci56aXAgdG8gZXhpc3QiCndoaWxlKCRUcnVlKSB7CmlmKFRlc3QtUGF0aCAiJHNEaXJcdnNjb2RlLXNjcC1kb25lLmZsYWciKSB7CmlmKCEoVGVzdC1QYXRoICIkc0Rpclx2c2NvZGUtc2VydmVyLnppcCIpKSB7CmVjaG8gIkZvdW5kIGZsYWcgYnV0IG5vdCBzZXJ2ZXIgdGFyIC0gc2VydmVyIHRyYW5zZmVyIGZhaWxlZCIKcSAzMQp9CmVjaG8gIkZvdW5kIGZsYWcgYW5kIHNlcnZlciBvbiBob3N0IgpkZWwgJHNEaXJcdnNjb2RlLXNjcC1kb25lLmZsYWcKYnJlYWsKfSBlbHNlIHsKU3RhcnQtU2xlZXAgLVNlY29uZHMgMwpleGl0SWZOZWVkZWQKfQp9Cn0KJHNzaGRQSUQ9Z2V0U3NoZFBhcmVudFBpZAppZighKFRlc3QtUGF0aCAkc0RpcikpIHsKdHJ5IHsKJG51bGw9bmkgLUl0ZW1UeXBlIERpcmVjdG9yeSAkc0RpciAtRm9yY2UgLUVycm9yQWN0aW9uIFNpbGVudGx5Q29udGludWUKfSBjYXRjaCB7CmVjaG8gIkNvdWxkIG5vdCBjcmVhdGUgc2VydmVyIGRpcmVjdG9yeS4gLSAkKCRfLlRvU3RyaW5nKCkpIgpyZXR1cm4KfQppZighKFRlc3QtUGF0aCAkc0RpcikpIHsKZWNobyAiQ291bGQgbm90IGNyZWF0ZSBzZXJ2ZXIgZGlyZWN0b3J5LiIKcmV0dXJuCn0KfQpjZCAkc0RpcgokbG9ja0ZpbGVQYXRoPShKb2luLVBhdGggIiRzRGlyIiAidnNjb2RlLXJlbW90ZS1sb2NrLiRjb21taXRJZCIpCnRyeSB7CiRudWxsPW5pICRsb2NrRmlsZVBhdGggLUl0ZW1UeXBlIEZpbGUgLUVycm9yQWN0aW9uIFNpbGVudGx5Q29udGludWUKfSBjYXRjaCB7CmVjaG8gIkNvdWxkIG5vdCBjcmVhdGUgc2VydmVyIGxvY2sgZmlsZS4gLSAkKCRfLlRvU3RyaW5nKCkpIgpyZXR1cm4KfQp0cnkgewplY2hvICJBY3F1aXJpbmcgbG9jayBvbiAkbG9ja0ZpbGVQYXRoIgokZmlsZT1bU3lzdGVtLmlvLkZpbGVdOjpPcGVuKCRsb2NrRmlsZVBhdGgsICdPcGVuJywgJ1JlYWQnLCAnTm9uZScpCn0gY2F0Y2ggewplY2hvICJJbnN0YWxsYXRpb24gYWxyZWFkeSBpbiBwcm9ncmVzcy4uLiAtICQoJF8uVG9TdHJpbmcoKSkiCnEgMjQKfQp0cnkgewplY2hvICJMb29raW5nIGZvciBleGlzdGluZyBzZXJ2ZXIgaW4gJHNEaXIiCmlmKFRlc3QtUGF0aCAiJHNEaXJcc2VydmVyLmNtZCIpIHsKZWNobyAidnNjb2RlLXNlcnZlciBhbHJlYWR5IGluc3RhbGxlZC4gU2tpcHBpbmcgZG93bmxvYWQuLi4iCn0gZWxzZSB7CnRyeSB7CkRvd25sb2FkU2VydmVyCn0gY2F0Y2ggewplY2hvICJGYWlsZWQgdG8gZG93bmxvYWQgJiBleHRyYWN0IHZzY29kZS1zZXJ2ZXIuIC0gJCgkXy5Ub1N0cmluZygpKSIKRG9DbGllbnREb3dubG9hZAp9Ckluc3RhbGxTZXJ2ZXIKaWYoIShUZXN0LVBhdGggIiRzRGlyXHNlcnZlci5jbWQiKSkgewplY2hvICJGYWlsZWQgdG8gZG93bmxvYWQgJiBleHRyYWN0IHZzY29kZS1zZXJ2ZXIuIgpxIDI1Cn0KfQppZiAoJGV4dHMgLW5lICIiKSB7CmVjaG8gIkluc3RhbGxpbmcgZXh0ZW5zaW9ucy4uLiIKJiAiJHNEaXJcc2VydmVyLmNtZCIgJHRlbGVtZXRyeSAgIyA/Pwp9CmlmKCEoR2V0LVByb2Nlc3Mgbm9kZSAtRXJyb3JBY3Rpb24gU2lsZW50bHlDb250aW51ZSB8IFdoZXJlLU9iamVjdCBQYXRoIC1tYXRjaCAkY29tbWl0SWQpKSB7CmlmKFRlc3QtUGF0aCAkbG9nKSB7CmRlbCAkbG9nCn0KJGVzY2FwZWRTZXJ2ZXJEaXI9JHNEaXIgLXJlcGxhY2UgJyAnLCAnYCAnCiRhcmdzPSItLWhvc3Q9MTI3LjAuMC4xIC0tZW5hYmxlLXJlbW90ZS1hdXRvLXNodXRkb3duIC0tcG9ydD0wICR0ZWxlbWV0cnkgKj4gJyRsb2cnIgokc3BsYXQ9QHsKRmlsZVBhdGggPSAicG93ZXJzaGVsbC5leGUiCldpbmRvd1N0eWxlID0gImhpZGRlbiIKQXJndW1lbnRMaXN0ID0gQCgKIi1FeGVjdXRpb25Qb2xpY3kiLCAiVW5yZXN0cmljdGVkIiwgIi1Ob0xvZ28iLCAiLU5vUHJvZmlsZSIsICItTm9uSW50ZXJhY3RpdmUiLCAiLWMiLCAiJGVzY2FwZWRTZXJ2ZXJEaXJcc2VydmVyLmNtZCAkYXJncyIKKQpQYXNzVGhydSA9ICRUcnVlCn0KZWNobyAiU3RhcnRpbmcgc2VydmVyIHdpdGggY29tbWFuZC4uLiAmICckc0RpclxzZXJ2ZXIuY21kJyAkYXJncyIKJGxhdW5jaGVkU2VydmVyUGlkPShTdGFydC1Qcm9jZXNzIEBzcGxhdCkuSUQKfSBlbHNlIHsKZWNobyAidnNjb2RlLXNlcnZlciB3aXRoICRjb21taXRJZCBpcyBhbHJlYWR5IHJ1bm5pbmcuIgp9CiRsaXN0ZW5pbmdQPUB7ClBhdGggPSAkbG9nClBhdHRlcm4gPSAiRXh0ZW5zaW9uIGhvc3QgYWdlbnQgbGlzdGVuaW5nIG9uIChcZCspIgp9CiRmYWlsZWRQPUB7ClBhdGggPSAkbG9nClBhdHRlcm4gPSAiISEhISBTZXJ2ZXIgdGVybWluYXRlZCBkdWUgdG8gcHJlc2VuY2Ugb2YgQ1ZFLTIwMjAtMTQxNiAhISEhIgp9CiR0aW1lb3V0RGF0ZT0oR2V0LURhdGUpLkFkZFNlY29uZHMoNCkKd2hpbGUgKChHZXQtRGF0ZSkgLWx0ICR0aW1lb3V0RGF0ZSkgewppZihUZXN0LVBhdGggJGxvZykgewokbGlzdGVuaW5nPShzbHMgQGxpc3RlbmluZ1ApLk1hdGNoZXMuR3JvdXBzCmlmKCRsaXN0ZW5pbmcpIHsKJHBvcnQ9JGxpc3RlbmluZ1sxXS5WYWx1ZQpicmVhawp9CiRmYWlsZWQ9KHNscyBAZmFpbGVkUCkuTWF0Y2hlcy5Hcm91cHMKaWYoJGZhaWxlZCkgewplY2hvICJTZXJ2ZXIgZGlkIG5vdCBzdGFydCBzdWNjZXNzZnVsbHkuIEZ1bGwgc2VydmVyIGxvZyBhdCAkbG9nID4+PiIKY2F0ICRsb2cKZWNobyAiPDw8IEVuZCBvZiBzZXJ2ZXIgbG9nIgpxIDM2Cn0KfQpzbGVlcCAtTWlsbGlzZWNvbmRzIDUwMAp9CmlmICghJHBvcnQpIHsKZWNobyAiU2VydmVyIGRpZCBub3Qgc3RhcnQgc3VjY2Vzc2Z1bGx5LiBGdWxsIHNlcnZlciBsb2cgYXQgJGxvZyA+Pj4iCmNhdCAkbG9nCmVjaG8gIjw8PCBFbmQgb2Ygc2VydmVyIGxvZyIKcSAzMgp9Cn0gY2F0Y2ggewplY2hvICJ2c2NvZGUtc2VydmVyIGZhaWxlZCB0byBzdGFydC4gLSAkKCRfLlRvU3RyaW5nKCkpIgp9IGZpbmFsbHkgewokZmlsZS5DbG9zZSgpCn0KdHJ5IHsKJHdpblZlcnNpb249KEdldC1DaW1JbnN0YW5jZSBXaW4zMl9PcGVyYXRpbmdTeXN0ZW0pLlZlcnNpb24KfSBjYXRjaCB7CmVjaG8gIkZhaWxlZCB0byBmaW5kIFdpbmRvd3MgdmVyc2lvbiAtICQoJF8uVG9TdHJpbmcoKSkiCiR3aW5WZXJzaW9uPSJ1bmtub3duIgp9CmVjaG8gIjVlMzQ4ZTMzNTIxMDogc3RhcnQiCmVjaG8gInNzaEF1dGhTb2NrPT0kZW52OlNTSF9BVVRIX1NPQ0s9PSIKZGV0YWlscwplY2hvICI1ZTM0OGUzMzUyMTA6IGVuZCIKZWNobyAiSW5zdGFsbCBzY3JpcHQgaXMgJHBpZCwgd2F0Y2hpbmcgc3NoZCBwYXJlbnQgJHNzaGRQSUQiCndoaWxlICgkVHJ1ZSkgewpleGl0SWZOZWVkZWQKc2xlZXAgMzAKfQo=')))))"  # RemoteSSHConfigurationScript
[11:58:44.692] "install" terminal received data: "#< CLIXML

5e348e335210: running
"
[11:58:44.693] Got some output, clearing connection timeout
[11:58:45.822] "install" terminal received data: "client_loop: send disconnect: Broken pipe
"
[11:58:46.098] "install" terminal command done
[11:58:46.098] Install terminal quit with output: client_loop: send disconnect: Broken pipe
[11:58:46.098] Received install output: client_loop: send disconnect: Broken pipe
[11:58:46.099] Stopped parsing output early. Remaining text: client_loop: send disconnect: Broken pipe
[11:58:46.099] Failed to parse remote port from server output
[11:58:46.112] Resolver error: Error: 
	at Function.Create (/home/mitch/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:1:94424)
	at Object.t.handleInstallOutput (/home/mitch/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:1:91173)
	at I (/home/mitch/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:106975)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /home/mitch/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:104974
	at async Object.t.withShowDetailsEvent (/home/mitch/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:110096)
	at async Object.t.resolve (/home/mitch/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:108158)
	at async /home/mitch/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:143767
[11:58:46.118] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"UnparsableOutput","exitCodeLabel":"","osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"0","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0"},"measures":{"resolveAttempts":1,"retries":1}}
[11:58:46.119] ------
```

After the failed connection, the sshd service on the Windows remote has to be restarted.

This is as much an ask for help as it is a bug report. Let me know if I should take this elsewhere. Thanks.

**Comment by tomateb** [comment]
same here, any fix on the issue?

**Comment by diepes** [comment]
I get something very similar (found this report with search)
Windows10 with vbox debian,   vscode Remote: ssh to vbox instance (Used to work before Win10 update)

```
[11:36:39.905] Install terminal quit with output: 
[11:36:39.918] Resolver error: Error: Got bad result from install script
	at Function.NotAvailable (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:517:659)
	at I (c:\Users\<user>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:127:106870)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\<user>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:127:104974
	at async Object.t.withShowDetailsEvent (c:\Users\<user>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:127:110096)
	at async Object.t.resolve (c:\Users\<user>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:127:108158)
	at async c:\Users\<user>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:127:143767
[11:36:39.925] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"Unknown","exitCodeLabel":"","osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0"},"measures":{"resolveAttempts":1}}
[11:36:39.926] ------
```

**Comment by roblourens** [comment]
> After the failed connection, the sshd service on the Windows remote has to be restarted.

Why? Can you tell me more?

Are there any processes using lots of CPU after this happens?

**Comment by mitchwoodside** [comment]
I'm having trouble gathering more info. Should I ask to reopen this issue when ready, or create a new one?

**Comment by roblourens** [comment]
You can leave a comment on this issue when you have more info. If it's after 30 days it will be locked, then you can create a new issue.
