### ISSUE TITLE
Could not fetch Remote environment / failed to connect to the remote extension host server

### ISSUE THREAD

**Issue by cpsLock** [microsoft/vscode-remote-release#4025]
As soon as I updated to WSL2 i get the following error in vscode after typing `code .` :

Could not fetch remote environment
Failed to connect to the remote extension host server (Error: connect ECONNREFUSED ::1:43841)

This is the WSL-Log:

```
[2020-11-17 12:32:12.127] Resolving wsl+Debian, resolveAttempt: 1
[2020-11-17 12:32:12.157] Starting VS Code Server inside WSL (Debian)
[2020-11-17 12:32:12.157] Extension version: 0.51.3, Windows build: 19042. Multi distro support: available. WSL path support: enabled
[2020-11-17 12:32:12.211] Using shell environment from invoking shell: /tmp/vscode-distro-env.ZZRjji
[2020-11-17 12:32:12.290] Probing if server is already installed: C:\Windows\System32\wsl.exe -d Debian -e sh -c "[ -d ~/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
[2020-11-17 12:32:12.354] Probing result: found
[2020-11-17 12:32:12.354] Server install found in WSL
[2020-11-17 12:32:12.354] Launching C:\Windows\System32\wsl.exe -d Debian sh -c 'env && VSCODE_WSL_DEBUG_INFO=true "$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" e5a624b788d92b8d34d1392e4c4d9789406efe8f stable .vscode-server 0  ' in c:\Users\mirai\.vscode\extensions\ms-vscode-remote.remote-wsl-0.51.3, env: {
[2020-11-17 12:32:12.354]   "ALLUSERSPROFILE": "C:\\ProgramData",
[2020-11-17 12:32:12.354]   "AMDRMPATH": "C:\\Program Files\\AMD\\RyzenMaster\\",
[2020-11-17 12:32:12.354]   "AMD_ENTRYPOINT": "vs/workbench/services/extensions/node/extensionHostProcess",
[2020-11-17 12:32:12.354]   "APPDATA": "C:\\Users\\mirai\\AppData\\Roaming",
[2020-11-17 12:32:12.354]   "APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL": "true",
[2020-11-17 12:32:12.354]   "ChocolateyInstall": "C:\\ProgramData\\chocolatey",
[2020-11-17 12:32:12.354]   "ChocolateyLastPathUpdate": "132500716045490432",
[2020-11-17 12:32:12.354]   "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\crashpad_4432_EWNPSCFNMSXBNEOE",
[2020-11-17 12:32:12.354]   "CommonProgramFiles": "C:\\Program Files\\Common Files",
[2020-11-17 12:32:12.354]   "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
[2020-11-17 12:32:12.354]   "CommonProgramW6432": "C:\\Program Files\\Common Files",
[2020-11-17 12:32:12.354]   "COMPUTERNAME": "WINDOWS",
[2020-11-17 12:32:12.354]   "ComSpec": "C:\\Windows\\system32\\cmd.exe",
[2020-11-17 12:32:12.354]   "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
[2020-11-17 12:32:12.354]   "ELECTRON_NO_ATTACH_CONSOLE": "1",
[2020-11-17 12:32:12.354]   "ELECTRON_RUN_AS_NODE": "1",
[2020-11-17 12:32:12.355]   "HOMEDRIVE": "C:",
[2020-11-17 12:32:12.355]   "HOMEPATH": "\\Users\\mirai",
[2020-11-17 12:32:12.355]   "LOCALAPPDATA": "C:\\Users\\mirai\\AppData\\Local",
[2020-11-17 12:32:12.355]   "LOGONSERVER": "\\\\WINDOWS",
[2020-11-17 12:32:12.355]   "MP_FORCE_USE_SANDBOX": "1",
[2020-11-17 12:32:12.355]   "NUMBER_OF_PROCESSORS": "12",
[2020-11-17 12:32:12.355]   "OneDrive": "C:\\Users\\mirai\\OneDrive",
[2020-11-17 12:32:12.355]   "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
[2020-11-17 12:32:12.355]   "OS": "Windows_NT",
[2020-11-17 12:32:12.355]   "Path": "C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\Git\\cmd;C:\\ProgramData\\chocolatey\\bin;C:\\Users\\mirai\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\mirai\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\mirai\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\bin",
[2020-11-17 12:32:12.355]   "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC",
[2020-11-17 12:32:12.355]   "PIPE_LOGGING": "true",
[2020-11-17 12:32:12.355]   "PROCESSOR_ARCHITECTURE": "AMD64",
[2020-11-17 12:32:12.355]   "PROCESSOR_IDENTIFIER": "AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD",
[2020-11-17 12:32:12.355]   "PROCESSOR_LEVEL": "23",
[2020-11-17 12:32:12.355]   "PROCESSOR_REVISION": "7100",
[2020-11-17 12:32:12.355]   "ProgramData": "C:\\ProgramData",
[2020-11-17 12:32:12.355]   "ProgramFiles": "C:\\Program Files",
[2020-11-17 12:32:12.355]   "ProgramFiles(x86)": "C:\\Program Files (x86)",
[2020-11-17 12:32:12.355]   "ProgramW6432": "C:\\Program Files",
[2020-11-17 12:32:12.355]   "PSModulePath": "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
[2020-11-17 12:32:12.355]   "PUBLIC": "C:\\Users\\Public",
[2020-11-17 12:32:12.355]   "SystemDrive": "C:",
[2020-11-17 12:32:12.355]   "SystemRoot": "C:\\Windows",
[2020-11-17 12:32:12.355]   "TEMP": "C:\\Temp",
[2020-11-17 12:32:12.355]   "TMP": "C:\\Temp",
[2020-11-17 12:32:12.355]   "USERDOMAIN": "WINDOWS",
[2020-11-17 12:32:12.355]   "USERDOMAIN_ROAMINGPROFILE": "WINDOWS",
[2020-11-17 12:32:12.355]   "USERNAME": "mirai",
[2020-11-17 12:32:12.355]   "USERPROFILE": "C:\\Users\\mirai",
[2020-11-17 12:32:12.355]   "VERBOSE_LOGGING": "true",
[2020-11-17 12:32:12.355]   "VSCODE_CLI": "1",
[2020-11-17 12:32:12.355]   "VSCODE_CLI_REMOTE_ENV": "/tmp/vscode-distro-env.ZZRjji",
[2020-11-17 12:32:12.355]   "VSCODE_CWD": "C:\\Users\\mirai\\AppData\\Local\\Programs\\Microsoft VS Code",
[2020-11-17 12:32:12.355]   "VSCODE_FILE_WATCHER_POLLING": "0",
[2020-11-17 12:32:12.355]   "VSCODE_HANDLES_UNCAUGHT_ERRORS": "true",
[2020-11-17 12:32:12.355]   "VSCODE_IPC_HOOK": "\\\\.\\pipe\\d01b6094d1d253937ef6819acd993942-1.51.1-main-sock",
[2020-11-17 12:32:12.355]   "VSCODE_IPC_HOOK_EXTHOST": "\\\\.\\pipe\\vscode-ipc-6639f6f0-2528-4193-affe-69f0bd639fcb-sock",
[2020-11-17 12:32:12.355]   "VSCODE_LOGS": "C:\\Users\\mirai\\AppData\\Roaming\\Code\\logs\\20201117T133211",
[2020-11-17 12:32:12.355]   "VSCODE_LOG_STACK": "false",
[2020-11-17 12:32:12.355]   "VSCODE_NLS_CONFIG": "{\"locale\":\"en-gb\",\"availableLanguages\":{},\"_languagePackSupport\":true}",
[2020-11-17 12:32:12.355]   "VSCODE_NODE_CACHED_DATA_DIR": "C:\\Users\\mirai\\AppData\\Roaming\\Code\\CachedData\\e5a624b788d92b8d34d1392e4c4d9789406efe8f",
[2020-11-17 12:32:12.355]   "VSCODE_PID": "4432",
[2020-11-17 12:32:12.355]   "VSCODE_WSL_AGENT_DEBUG_PORT": "",
[2020-11-17 12:32:12.355]   "VSCODE_WSL_APP_ROOT": "c:\\Users\\mirai\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app",
[2020-11-17 12:32:12.355]   "VSCODE_WSL_DEBUG_INFO": "true",
[2020-11-17 12:32:12.355]   "VSCODE_WSL_DEFAULT_DISTRO": "Debian",
[2020-11-17 12:32:12.355]   "VSCODE_WSL_DISTRO": "Debian",
[2020-11-17 12:32:12.355]   "VSCODE_WSL_ENABLE_TELEMETRY": "true",
[2020-11-17 12:32:12.355]   "VSCODE_WSL_EXT_HOST_PID": "6984",
[2020-11-17 12:32:12.355]   "VSCODE_WSL_EXT_LOCATION": "c:\\Users\\mirai\\.vscode\\extensions\\ms-vscode-remote.remote-wsl-0.51.3",
[2020-11-17 12:32:12.355]   "VSCODE_WSL_PIPE_NAME": "\\\\.\\pipe\\vscode-wsl-3fd6e1fc1afad0fec7bfae371c6a6643424ffab5-sock",
[2020-11-17 12:32:12.355]   "windir": "C:\\Windows",
[2020-11-17 12:32:12.355]   "WSLENV": "VSCODE_WSL_EXT_LOCATION/up:VSCODE_CLI_REMOTE_ENV/w:ELECTRON_RUN_AS_NODE/w:WT_SESSION::WT_PROFILE_ID",
[2020-11-17 12:32:12.355]   "WT_PROFILE_ID": "{58ad8b0c-3ef8-5f4d-bc6f-13e4c00f2530}",
[2020-11-17 12:32:12.355]   "WT_SESSION": "63e7a203-8241-4a22-bdda-2acdceb43690"
[2020-11-17 12:32:12.355] }}
[2020-11-17 12:32:12.602] USER=kuma
[2020-11-17 12:32:12.602] VSCODE_WSL_EXT_LOCATION=/mnt/c/Users/mirai/.vscode/extensions/ms-vscode-remote.remote-wsl-0.51.3
[2020-11-17 12:32:12.602] PF_COL3=6
[2020-11-17 12:32:12.602] WT_PROFILE_ID={58ad8b0c-3ef8-5f4d-bc6f-13e4c00f2530}
[2020-11-17 12:32:12.602] SHLVL=0
[2020-11-17 12:32:12.602] XDG_CACHE_HOME=/home/kuma/.config/cache
[2020-11-17 12:32:12.602] HOME=/home/kuma
[2020-11-17 12:32:12.602] OLDPWD=/mnt/c/Users/mirai/.vscode/extensions/ms-vscode-remote.remote-wsl-0.51.3
[2020-11-17 12:32:12.602] VISUAL=nvim
[2020-11-17 12:32:12.602] WSL_DISTRO_NAME=Debian
[2020-11-17 12:32:12.602] LOGNAME=kuma
[2020-11-17 12:32:12.603] WSL_INTEROP=/run/WSL/575_interop
[2020-11-17 12:32:12.603] NAME=Windows
[2020-11-17 12:32:12.603] _=/bin/sh
[2020-11-17 12:32:12.603] TERM=xterm-256color
[2020-11-17 12:32:12.603] PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files/Git/cmd:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Users/mirai/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/mirai/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/mirai/AppData/Local/Programs/Microsoft VS Code Insiders/bin
[2020-11-17 12:32:12.603] WT_SESSION=63e7a203-8241-4a22-bdda-2acdceb43690
[2020-11-17 12:32:12.603] LANG=en_US.UTF-8
[2020-11-17 12:32:12.603] HISTSIZE=10000
[2020-11-17 12:32:12.603] XDG_CONFIG_HOME=/home/kuma/.config
[2020-11-17 12:32:12.603] XDG_DATA_HOME=/home/kuma/.config/local/share
[2020-11-17 12:32:12.603] SHELL=/usr/bin/zsh
[2020-11-17 12:32:12.603] SAVEHIST=10000
[2020-11-17 12:32:12.603] PWD=/mnt/c/Users/mirai/.vscode/extensions/ms-vscode-remote.remote-wsl-0.51.3
[2020-11-17 12:32:12.603] ZDOTDIR=/home/kuma/.config/zsh
[2020-11-17 12:32:12.603] HISTFILE=/home/kuma/.config/zsh/.zhistory
[2020-11-17 12:32:12.603] HOSTTYPE=x86_64
[2020-11-17 12:32:12.603] WSLENV=VSCODE_WSL_EXT_LOCATION/up:VSCODE_CLI_REMOTE_ENV/w:ELECTRON_RUN_AS_NODE/w:WT_SESSION::WT_PROFILE_ID
[2020-11-17 12:32:12.603] EDITOR=nvim
[2020-11-17 12:32:12.603] Setting up server environment: Looking for /home/kuma/.vscode-server/server-env-setup. Not found.
[2020-11-17 12:32:12.603] WSL version: 4.19.128-microsoft-standard Debian
[2020-11-17 12:32:12.603] WSL2-shell-PID: 578
[2020-11-17 12:32:12.603] Starting server: /home/kuma/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/server.sh  --port=0 --use-host-proxy --enable-remote-auto-shutdown 
[2020-11-17 12:32:12.603] 
[2020-11-17 12:32:12.603] 
[2020-11-17 12:32:12.603] *
[2020-11-17 12:32:12.603] * Visual Studio Code Server
[2020-11-17 12:32:12.603] *
[2020-11-17 12:32:12.603] * Reminder: You may only use this software with Visual Studio family products,
[2020-11-17 12:32:12.603] * as described in the license https://aka.ms/vscode-remote/license
[2020-11-17 12:32:12.603] *
[2020-11-17 12:32:12.603] 
[2020-11-17 12:32:12.603] 
[2020-11-17 12:32:12.603] Extension host agent listening on 43841
[2020-11-17 12:32:12.603] 
[2020-11-17 12:32:12.603] 
[2020-11-17 12:32:12.603] [13:32:11] Extension host agent started.
[2020-11-17 12:32:12.604] + [ ! -d /home/kuma/.vscode-server ]
[2020-11-17 12:32:12.604] + CODE_PROFILE=/home/kuma/.vscode-server/server-env-setup
[2020-11-17 12:32:12.604] + printf Setting up server environment: Looking for %s.  /home/kuma/.vscode-server/server-env-setup
[2020-11-17 12:32:12.604] + [ -f /home/kuma/.vscode-server/server-env-setup ]
[2020-11-17 12:32:12.604] + echo Not found.
[2020-11-17 12:32:12.604] + VSCODE_REMOTE_BIN=/home/kuma/.vscode-server/bin
[2020-11-17 12:32:12.604] + uname -r
[2020-11-17 12:32:12.604] + WSL_VERSION=4.19.128-microsoft-standard
[2020-11-17 12:32:12.604] + echo WSL version: 4.19.128-microsoft-standard Debian
[2020-11-17 12:32:12.604] + dirname /mnt/c/Users/mirai/.vscode/extensions/ms-vscode-remote.remote-wsl-0.51.3/scripts/wslServer.sh
[2020-11-17 12:32:12.604] + /mnt/c/Users/mirai/.vscode/extensions/ms-vscode-remote.remote-wsl-0.51.3/scripts/wslDownload.sh e5a624b788d92b8d34d1392e4c4d9789406efe8f stable /home/kuma/.vscode-server/bin
[2020-11-17 12:32:12.604] + [ ! -d /home/kuma/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f ]
[2020-11-17 12:32:12.604] + RC=0
[2020-11-17 12:32:12.604] + [ 0 -ne 0 ]
[2020-11-17 12:32:12.604] + SERVER_ARGS=
[2020-11-17 12:32:12.604] + echo WSL2-shell-PID: 578
[2020-11-17 12:32:12.604] + SERVER_ARGS=--enable-remote-auto-shutdown
[2020-11-17 12:32:12.604] + echo Starting server: /home/kuma/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/server.sh  --port=0 --use-host-proxy --enable-remote-auto-shutdown 
[2020-11-17 12:32:12.604] + [ -f /etc/alpine-release ]
[2020-11-17 12:32:12.604] + uname -m
[2020-11-17 12:32:12.604] + [ x86_64 = aarch64 ]
[2020-11-17 12:32:12.604] + export VSCODE_AGENT_FOLDER=/home/kuma/.vscode-server
[2020-11-17 12:32:12.604] + /home/kuma/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/server.sh  --port=0 --use-host-proxy --enable-remote-auto-shutdown
[2020-11-17 12:32:12.604] Unable to retrieve mac address (unexpected format)
[2020-11-17 12:32:12.604] WSL resolver response: ::1:43841
[2020-11-17 12:32:12.604] To debug connection issues, open a local browser on http://[::1]:43841/version
[2020-11-17 12:32:12.604] Extension host environment: {
[2020-11-17 12:32:12.604]   "STARSHIP_SHELL": "zsh",
[2020-11-17 12:32:12.604]   "PF_COL3": "6",
[2020-11-17 12:32:12.604]   "WT_PROFILE_ID": "{58ad8b0c-3ef8-5f4d-bc6f-13e4c00f2530}",
[2020-11-17 12:32:12.604]   "SHLVL": "1",
[2020-11-17 12:32:12.604]   "XDG_CACHE_HOME": "/home/kuma/.config/cache",
[2020-11-17 12:32:12.604]   "HOME": "/home/kuma",
[2020-11-17 12:32:12.604]   "VISUAL": "nvim",
[2020-11-17 12:32:12.604]   "WSL_DISTRO_NAME": "Debian",
[2020-11-17 12:32:12.604]   "LOGNAME": "kuma",
[2020-11-17 12:32:12.604]   "WSL_INTEROP": "/run/WSL/460_interop",
[2020-11-17 12:32:12.604]   "NAME": "Code",
[2020-11-17 12:32:12.604]   "_": "/mnt/c/Users/mirai/AppData/Local/Programs/Microsoft VS Code/bin/code",
[2020-11-17 12:32:12.604]   "TERM": "xterm-256color",
[2020-11-17 12:32:12.604]   "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files/Git/cmd:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Users/mirai/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/mirai/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/mirai/AppData/Local/Programs/Microsoft VS Code Insiders/bin",
[2020-11-17 12:32:12.604]   "WT_SESSION": "63e7a203-8241-4a22-bdda-2acdceb43690",
[2020-11-17 12:32:12.604]   "LANG": "en_US.UTF-8",
[2020-11-17 12:32:12.604]   "HISTSIZE": "10000",
[2020-11-17 12:32:12.604]   "XDG_CONFIG_HOME": "/home/kuma/.config",
[2020-11-17 12:32:12.604]   "XDG_DATA_HOME": "/home/kuma/.config/local/share",
[2020-11-17 12:32:12.604]   "SAVEHIST": "10000",
[2020-11-17 12:32:12.604]   "ZDOTDIR": "/home/kuma/.config/zsh",
[2020-11-17 12:32:12.604]   "KEYTIMEOUT": "1",
[2020-11-17 12:32:12.604]   "STARSHIP_SESSION_KEY": "2936713912327924",
[2020-11-17 12:32:12.604]   "HISTFILE": "/home/kuma/.cache/zsh/history",
[2020-11-17 12:32:12.604]   "HOSTTYPE": "x86_64",
[2020-11-17 12:32:12.604]   "WSLENV": "ELECTRON_RUN_AS_NODE/w:WT_SESSION::WT_PROFILE_ID",
[2020-11-17 12:32:12.604]   "EDITOR": "nvim"
[2020-11-17 12:32:12.604] }
```

I already tried using the Insider version of vscode like mentioned in posts regarding the same issue in 2019 which did not work for me.

**Comment by MirzaSikander** [comment]
I am also getting the same error.  Using WSL2 and version 1.51.1 for vscode.

```
[2020-12-04 15:36:31.020] [renderer11] [error] [remote-connection][Management   ][c958c…][initial][::1:36295] socketFactory.connect() failed. Error:
[2020-12-04 15:36:31.020] [renderer11] [error] Error: connect ECONNREFUSED ::1:36295
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)
[2020-12-04 15:36:31.021] [renderer11] [error] [remote-connection][ExtensionHost][1493b…][initial][::1:36295] socketFactory.connect() failed. Error:
[2020-12-04 15:36:31.021] [renderer11] [error] Error: connect ECONNREFUSED ::1:36295
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)
```
