### ISSUE TITLE
Unsupported architecture: i686

### ISSUE THREAD

**Issue by NonoKing** [microsoft/vscode-remote-release#4026]
🚨 The issue tracker is not for questions 🚨
I could use Windows SSH to connect to the server which is Linux.
But I cannot use Remote-SSH in VS Code to connect.

The log is as following:

[20:29:42.439] Log Level: 2
[20:29:42.443] remote-ssh@0.56.0
[20:29:42.443] win32 x64
[20:29:42.445] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a225465616d536572766572227d", attempt 1
[20:29:42.445] SSH Resolver called for host: TeamServer
[20:29:42.446] Setting up SSH remote "TeamServer"
[20:29:42.463] Using commit id "e5a624b788d92b8d34d1392e4c4d9789406efe8f" and quality "stable" for server
[20:29:42.465] Install and start server if needed
[20:29:43.712] Checking ssh with "ssh -V"
[20:29:43.738] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[20:29:43.742] Running script with connection command: ssh -T -D 51939 TeamServer bash
[20:29:43.746] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[20:29:43.802] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\WINDOWS\System32\cmd.exe
[20:29:43.803] Got some output, clearing connection timeout
[20:29:43.811] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[20:29:44.119] > qingbihao@172.16.10.53's password: 
[20:29:44.120] Showing password prompt
[20:29:46.790] Got password response
[20:29:46.790] "install" wrote data to terminal: "******"
[20:29:46.805] > 
> 
[20:29:47.198] > 6a80d912224f: running
> 
[20:29:47.233] > Unsupported architecture: i686
> 6a80d912224f: start
> exitCode==27==
> sshAuthSock====
> listeningOn====
> osReleaseId==Linux==
> arch==i686==
> webUiAccessToken====
> tmpDir==/tmp==
> platform==linux==
> 6a80d912224f: end
> 
[20:29:47.233] Received install output: 
exitCode==27==
sshAuthSock====
listeningOn====
osReleaseId==Linux==
arch==i686==
webUiAccessToken====
tmpDir==/tmp==
platform==linux==

[20:29:47.234] Unsupported architecture
[20:29:47.239] Resolver error: Error: The remote host's architecture is not supported
	at Function.ServerInstallError (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:1:94355)
	at c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:1:92085
	at Object.t.handleInstallOutput (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:1:93073)
	at I (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:127:106975)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:127:104974
	at async Object.t.withShowDetailsEvent (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:127:110096)
	at async Object.t.resolve (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:127:108158)
	at async c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.56.0\out\extension.js:127:143767
[20:29:47.242] ------

[20:29:47.671] "install" terminal command done
[20:29:47.671] Install terminal quit with output:

**Comment by roblourens** [comment]
We aren't able to support this architecture on linux
