### ISSUE TITLE
Cannot connect to University HPC

### ISSUE THREAD

**Issue by DDDOH** [microsoft/vscode-remote-release#4027]
When I tried to connect to the HPC in my school with "ssh zyzheng@hpc.brc.berkeley.edu", I was asked to type in the password for three times, and then the error message as below popped up. Is it because the HPC refuse the using of port forwarding as discussed in https://github.com/microsoft/vscode-remote-release/issues/92, or any other reason that I can fix on my side?

```
[20:38:40.991] Log Level: 2
[20:38:40.999] remote-ssh-nightly@2020.11.18240
[20:38:40.999] darwin x64
[20:38:41.001] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a226870632e6272632e6265726b656c65792e656475222c2275736572223a22737368207a797a68656e67227d", attempt 1
[20:38:41.001] SSH Resolver called for host: ssh zyzheng@hpc.brc.berkeley.edu
[20:38:41.002] Setting up SSH remote "hpc.brc.berkeley.edu"
[20:38:41.028] Acquiring local install lock: /var/folders/0r/65qs6jfj4y12960sqy9x42580000gq/T/vscode-remote-ssh-ssh zyzheng@hpc.brc.berkeley.edu-install.lock
[20:38:41.120] Looking for existing server data file at /Users/shuffle_new/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh-nightly/vscode-ssh-host-ssh zyzheng@hpc.brc.berkeley.edu-e5a624b788d92b8d34d1392e4c4d9789406efe8f-2020.11.18240/data.json
[20:38:41.121] Using commit id "e5a624b788d92b8d34d1392e4c4d9789406efe8f" and quality "stable" for server
[20:38:41.123] Install and start server if needed
[20:38:41.134] Checking ssh with "ssh -V"
[20:38:41.155] > OpenSSH_8.1p1, LibreSSL 2.7.3

[20:38:41.161] askpass server listening on /var/folders/0r/65qs6jfj4y12960sqy9x42580000gq/T/vscode-ssh-askpass-8cb855736e41fe3b0acdcfbaf4c2de0d775f59e4.sock
[20:38:41.162] Spawning local server with {"ipcHandlePath":"/var/folders/0r/65qs6jfj4y12960sqy9x42580000gq/T/vscode-ssh-askpass-9c9bce7b7207d94584f91efec940a4ea18322c62.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","62875","-o","ConnectTimeout=15","ssh zyzheng@hpc.brc.berkeley.edu"],"dataFilePath":"/Users/shuffle_new/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh-nightly/vscode-ssh-host-ssh zyzheng@hpc.brc.berkeley.edu-e5a624b788d92b8d34d1392e4c4d9789406efe8f-2020.11.18240/data.json"}
[20:38:41.162] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/shuffle_new/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.18240/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/shuffle_new/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.18240/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/0r/65qs6jfj4y12960sqy9x42580000gq/T/vscode-ssh-askpass-8cb855736e41fe3b0acdcfbaf4c2de0d775f59e4.sock"}
[20:38:41.169] Spawned 41543
[20:38:41.485] > local-server> Spawned ssh: 41544
[20:38:41.494] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[20:38:43.451] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:hUvl7RrOoo0MRUAg/xfKx9a4Laj3qvcM3WnMvgpS0Y4
[20:38:45.225] Got askpass request: {"request":"Password:"}
[20:38:45.226] Showing password prompt
[20:38:45.229] Listening for interwindow password on /var/folders/0r/65qs6jfj4y12960sqy9x42580000gq/T/vscode-ssh-askpass-45131171df8c2fd76b391c9ac990e8e8fe3d3a43.sock
[20:38:45.230] Writing password prompt to globalState
[20:39:00.588] Got password response
[20:39:00.588] Interactor gave response: ******
[20:39:00.589] Cleaning up other-window auth server
[20:39:01.604] Got askpass request: {"request":"Password:"}
[20:39:01.605] Showing password prompt
[20:39:01.605] Listening for interwindow password on /var/folders/0r/65qs6jfj4y12960sqy9x42580000gq/T/vscode-ssh-askpass-aaca31c3976e4eb3213f116c56bca3e130cf202e.sock
[20:39:01.605] Writing password prompt to globalState
[20:39:08.653] Got password response
[20:39:08.653] Interactor gave response: ************
[20:39:08.653] Cleaning up other-window auth server
[20:39:09.709] Got askpass request: {"request":"Password:"}
[20:39:09.709] Showing password prompt
[20:39:09.710] Listening for interwindow password on /var/folders/0r/65qs6jfj4y12960sqy9x42580000gq/T/vscode-ssh-askpass-675ef0d6018f4f906f36f7d4a5f326a627fb1e7d.sock
[20:39:09.710] Writing password prompt to globalState
[20:39:14.643] Got password response
[20:39:14.644] Interactor gave response: ************
[20:39:14.644] Cleaning up other-window auth server
[20:39:15.030] stderr> ssh zyzheng@hpc.brc.berkeley.edu: Permission denied (gssapi-keyex,gssapi-with-mic,keyboard-interactive).
[20:39:15.031] > local-server> ssh child died, shutting down
[20:39:15.036] Local server exit: 0
[20:39:15.036] Received install output: OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:hUvl7RrOoo0MRUAg/xfKx9a4Laj3qvcM3WnMvgpS0Y4
ssh zyzheng@hpc.brc.berkeley.edu: Permission denied (gssapi-keyex,gssapi-with-mic,keyboard-interactive).

[20:39:15.043] Resolver error: Error: Permission denied (gssapi-keyex,gssapi-with-mic,keyboard-interactive).
	at Function.Create (/Users/shuffle_new/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.18240/out/extension.js:1:95022)
	at /Users/shuffle_new/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.18240/out/extension.js:1:91264
	at Object.t.handleInstallOutput (/Users/shuffle_new/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.18240/out/extension.js:1:91547)
	at Object.t.tryInstallWithLocalServer (/Users/shuffle_new/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.18240/out/extension.js:127:102412)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /Users/shuffle_new/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.18240/out/extension.js:127:104532
	at async Object.t.withShowDetailsEvent (/Users/shuffle_new/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.18240/out/extension.js:127:110110)
	at async /Users/shuffle_new/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.18240/out/extension.js:127:100985
	at async S (/Users/shuffle_new/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.18240/out/extension.js:127:97777)
	at async Object.t.resolveWithLocalServer (/Users/shuffle_new/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.18240/out/extension.js:127:100634)
	at async Object.t.resolve (/Users/shuffle_new/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.18240/out/extension.js:127:108056)
	at async /Users/shuffle_new/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.18240/out/extension.js:127:144369
[20:39:15.060] ------
```

**Comment by roblourens** [comment]
Please try without including `ssh `, this is probably the issue
