### ISSUE TITLE
Cannot read property '1' of null

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#4054]
Hello @chrmarti, thanks a lot for the pointer to VS Code Insiders. I've just tried this same bug in that version (code-insiders 1.52.0-insider a36c68b9ec3d6a0aca9799d7a10be741a6658a51 x64, remote-containers v0.150.0) and the bug has changed its behaviour, but it is still not working.

See attached screenshots:

![Screenshot from 2020-11-20 13-58-55](https://user-images.githubusercontent.com/1721716/99752651-cea4c580-2b38-11eb-9a56-7208702a5214.png)

![Screenshot from 2020-11-20 13-59-11](https://user-images.githubusercontent.com/1721716/99752658-d2d0e300-2b38-11eb-987e-b62415385bc6.png)

And for commodity, copy-paste of that log:
```
[3 ms] Remote-Containers 0.150.0 in VS Code 1.52.0-insider (a36c68b9ec3d6a0aca9799d7a10be741a6658a51).
[13 ms] Start: Resolving remote
[15 ms] Setting up container /docker_socket_shared_2

[15 ms] Start: Run: docker inspect --type container /docker_socket_shared_2
[71 ms] Start: Check Docker is running
[71 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[134 ms] Server API version: 1.40
[134 ms] Start: Inspecting container
[134 ms] Start: Run: docker inspect --type container 9c38cdacecc81dfc99c9e7d399b084ab85bbf353f47e63660b8a0653a7329b5d
[176 ms] Start: Run: docker exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=22c3bc21-34b0-41eb-9fce-af13e259f3b21605841124681 9c38cdacecc81dfc99c9e7d399b084ab85bbf353f47e63660b8a0653a7329b5d /bin/sh
[179 ms] Start: Run in container: uname -m
[297 ms] x86_64
[297 ms] 
[297 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[299 ms] PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[300 ms] 
[300 ms] Start: Run in container: cat /etc/passwd
[302 ms] Start: Run in container: test -d /root/.vscode-server-insiders
[303 ms] 
[303 ms] 
[303 ms] Exit code 1
[303 ms] Start: Run in container: test -d /root/.vscode-remote
[303 ms] 
[303 ms] 
[303 ms] Exit code 1
[304 ms] Start: Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server-insiders/data/Machine' && { > '/root/.vscode-server-insiders/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[306 ms] 
[306 ms] 
[306 ms] Start: Run in container: cat /root/.vscode-server-insiders/data/Machine/settings.json
[307 ms] 
[307 ms] cat: /root/.vscode-server-insiders/data/Machine/settings.json: No such file or directory
[307 ms] Exit code 1
[307 ms] Start: Run in container: test -d /root/.vscode-server-insiders/bin/a36c68b9ec3d6a0aca9799d7a10be741a6658a51
[308 ms] 
[308 ms] 
[308 ms] Exit code 1
[308 ms] Installing VS Code Server for commit a36c68b9ec3d6a0aca9799d7a10be741a6658a51
[308 ms] Start: Run in container: mkdir -p /root/.vscode-server-insiders/bin/a36c68b9ec3d6a0aca9799d7a10be741a6658a51_1605841125530
[310 ms] 
[310 ms] 
[336 ms] Start: Run in container: (dd iflag=fullblock bs=8192 count=3717 2>/dev/null; dd iflag=fullblock bs=2258 count=1 2>/dev/null) | tar --no-same-owner -xz --strip-components 1 -C /root/.vscode-server-insiders/bin/a36c68b9ec3d6a0aca9799d7a10be741a6658a51_1605841125530
[1135 ms] 
[1135 ms] 
[1135 ms] Start: Run in container: mv -n /root/.vscode-server-insiders/bin/a36c68b9ec3d6a0aca9799d7a10be741a6658a51_1605841125530 /root/.vscode-server-insiders/bin/a36c68b9ec3d6a0aca9799d7a10be741a6658a51
[1137 ms] 
[1137 ms] 
[1137 ms] Start: Launching Remote-Containers helper.
[1137 ms] Start: Run: gpgconf --list-dir agent-extra-socket
[1142 ms] Start: Run in container: gpgconf --list-dir agent-socket
[1143 ms] /root/.gnupg/S.gpg-agent
[1143 ms] 
[1143 ms] Start: Run in container: gpgconf --list-dir homedir
[1144 ms] /root/.gnupg
[1144 ms] 
[1144 ms] Start: Run in container: ls '/root/.gnupg/private-keys-v1.d' 2>/dev/null
[1145 ms] 
[1145 ms] 
[1145 ms] Exit code 2
[1145 ms] Start: Run in container: mkdir -p -m 700 '/root/.gnupg'
[1147 ms] 
[1147 ms] 
[1147 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-693a42f45f1dac3830b14ff30aa28867458aeb0f.js' >/tmp/vscode-remote-containers-693a42f45f1dac3830b14ff30aa28867458aeb0f.js
[1147 ms] Start: Run: gpgconf --list-dir homedir
[1150 ms] 
[1150 ms] 
[1150 ms] Start: Run in container: # Test for /root/.ssh/known_hosts and ssh
[1152 ms] 
[1152 ms] 
[1152 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-693a42f45f1dac3830b14ff30aa28867458aeb0f.js' >/tmp/vscode-remote-containers-server-693a42f45f1dac3830b14ff30aa28867458aeb0f.js
[1153 ms] 
[1153 ms] 
[1153 ms] Start: Run in container: gpgconf --list-dir homedir
[1153 ms] Start: Run: docker exec -i -u root -e REMOTE_CONTAINERS_SOCKETS=["/tmp/vscode-ssh-auth-693a42f45f1dac3830b14ff30aa28867458aeb0f.sock","/root/.gnupg/S.gpg-agent"] -e REMOTE_CONTAINERS_IPC=/tmp/vscode-remote-containers-ipc-693a42f45f1dac3830b14ff30aa28867458aeb0f.sock 9c38cdacecc81dfc99c9e7d399b084ab85bbf353f47e63660b8a0653a7329b5d /root/.vscode-server-insiders/bin/a36c68b9ec3d6a0aca9799d7a10be741a6658a51/node /tmp/vscode-remote-containers-server-693a42f45f1dac3830b14ff30aa28867458aeb0f.js
[1158 ms] /root/.gnupg
[1158 ms] 
[1159 ms] Start: Run in container: # Copy /home/skipper/.ssh/known_hosts to /root/.ssh/known_hosts
[1161 ms] 
[1161 ms] 
[1161 ms] Start: Run in container: # Test for /root/.gnupg/pubring.kbx and gpg
[1163 ms] 
[1163 ms] 
[1163 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --system credential.helper '!f() { /root/.vscode-server-insiders/bin/a36c68b9ec3d6a0aca9799d7a10be741a6658a51/node /tmp/vscode-remote-containers-693a42f45f1dac3830b14ff30aa28867458aeb0f.js $*; }; f' || true
[1164 ms] 
[1165 ms] 
[1165 ms] Start: Run in container: # Copy /home/skipper/.gnupg/pubring.kbx to /root/.gnupg/pubring.kbx
[1167 ms] 
[1167 ms] 
[1167 ms] Start: Run in container: set -o noclobber ; mkdir -p '/root/.vscode-server-insiders/data/Machine' && { > '/root/.vscode-server-insiders/data/Machine/.installExtensionsMarker' ; } 2> /dev/null
[1168 ms] 
[1168 ms] 
[1168 ms] Start: Run in container: # Test for /root/.gnupg/trustdb.gpg and gpg
[1170 ms] 
[1170 ms] 
[1170 ms] Start: Run in container: # Copy /home/skipper/.gnupg/trustdb.gpg to /root/.gnupg/trustdb.gpg
[1172 ms] 
[1172 ms] 
[1172 ms] Start: Run in container: # Test for /root/.gitconfig and git
[1172 ms] Start: Run: gpg-connect-agent updatestartuptty /bye
[1177 ms] 
[1177 ms] 
[1177 ms] Start: Run in container: # Copy /home/skipper/.gitconfig to /root/.gitconfig
[1180 ms] 
[1180 ms] 
[1180 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --global credential.helper '!f() { /root/.vscode-server-insiders/bin/a36c68b9ec3d6a0aca9799d7a10be741a6658a51/node /tmp/vscode-remote-containers-693a42f45f1dac3830b14ff30aa28867458aeb0f.js $*; }; f' || true
[1182 ms] 
[1183 ms] 
[1183 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd ; readlink /proc/$pid/ns/mnt ; cat /proc/$pid/stat | tr "
[3607 ms] TypeError: Cannot read property '1' of null
        at /home/skipper/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.150.0/dist/extension.js:1:613089
        at Array.map (<anonymous>)
        at Object.t.findProcesses (/home/skipper/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.150.0/dist/extension.js:1:613009)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:94:5)
        at async V (/home/skipper/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.150.0/dist/extension.js:1:639497)
        at async Object.t.injectIntoContainer (/home/skipper/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.150.0/dist/extension.js:1:636870)
        at async Object.t.resolve (/home/skipper/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.150.0/dist/extension.js:1:778625)
        at async /home/skipper/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.150.0/dist/extension.js:1:686810
```

_Originally posted by @awesomebytes in https://github.com/microsoft/vscode-remote-release/issues/3850#issuecomment-730814588_

**Comment by chrmarti** [comment]
It looks like one of the `/proc/*/stat` files doesn't have the expected format. In the container with which you see this, could you run `cat /proc/*/stat` and post the result here? (You could use `Attach Shell` from the container's context menu in the Docker extension's viewlet.)

**Comment by awesomebytes** [comment]
Hello @chrmarti I just tried again code-insiders (1.52.0-insider), now with Remote - Containers with version 0.152.**1** and it works correctly! Thanks a lot for following through!
