### ISSUE TITLE
Attaching to Remote Container on Cloud Ubuntu Linux Target Returns Error

### ISSUE THREAD

**Issue by kzawad1** [microsoft/vscode-remote-release#4070]
The error is the following:

```
[69632 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --global credential.helper '!f() { /home/decs/.vscode-server-insiders/bin/6026ab576dc6a4fbb8e255241a364816f42464c5/node /tmp/vscode-remote-containers-89ef916a7e750415d74d27b7e1f459e9632169a2.js $*; }; f' || true
[69759 ms] 
[69759 ms] 
[69760 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd ; readlink /proc/$pid/ns/mnt ; cat /proc/$pid/stat | tr "
[69888 ms] Start: Run in container: /home/decs/.vscode-server-insiders/bin/6026ab576dc6a4fbb8e255241a364816f42464c5/server.sh --disable-user-env-probe --port 0 --extensions-download-dir /home/decs/.vscode-server-insiders/extensionsCache
[70027 ms] Error: stream ended with:125 but wanted:1128865906
        at p (/home/kzawada/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.150.0/dist/extension.js:1:510820)
        at /home/kzawada/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.150.0/dist/extension.js:1:510990
        at s (/home/kzawada/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.150.0/dist/extension.js:1:540286)
        at Socket.<anonymous> (/home/kzawada/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.150.0/dist/extension.js:1:540459)
        at Socket.emit (events.js:228:7)
        at endReadableNT (_stream_readable.js:1185:12)
        at processTicksAndRejections (internal/process/task_queues.js:81:21)
[70031 ms] Remote-Containers server terminated (code: 126, signal: null).
```
![Screenshot from 2020-11-23 17-12-29](https://user-images.githubusercontent.com/13036629/100026398-55170c80-2db0-11eb-9404-ab569b2a68a9.png)
![Screenshot from 2020-11-23 17-12-38](https://user-images.githubusercontent.com/13036629/100026412-59432a00-2db0-11eb-81cf-0a39e14a3469.png)

- VSCode Version: 1.52.0-insider
- Local OS Version: Ubuntu 20.04.1 LTS x86-64
- Remote OS Version: 18.04.4 LTS x86-64
- Remote Extension/Connection Type: SSH/Docker/WSL

Steps to Reproduce:

1. Create a Ubuntu 20.04 cloud compute instance
2. Setup Docker Daemon on the Ubuntu 20.04 cloud compute instance.
3. Configure Docker Daemon on Ubuntu 20.04 cloud compute instance
4. Setup Visual Studio Code to connect to this instance.
5. Open container C/C++ project.
6. From View->Command Palette, select "Remote-Containers: Attach to Running Container".
7. Select the running container on the target once displayed.
8. Wait until the process of connecting starts running and eventually displays error above.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
Previously https://github.com/microsoft/vscode-remote-release/issues/3855.

**Comment by chrmarti** [comment]
Not seen elsewhere. Might have been fixed with more recent versions of dependencies. Closing as wont-fix. Thanks.
