### ISSUE TITLE
randomly disconnects from remote server

### ISSUE THREAD

**Issue by CyanBook** [microsoft/vscode-remote-release#4081]
Issue Type: <b>Bug</b>

vscode Remote-SSH extensionrandomly disconnects from my server.
It may vary from a couple of minutes to a couple of hours. Sometimes it doesn't at all. I already tried to reload and reinstall VSCode Server, but nothing happened. Please help me

Extension version: 0.56.0
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 5.4.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (8.68GB free)|
|Process Argv|--crash-reporter-id d4f79334-6cde-4f34-9a3e-b71cdb9bff7d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Hetzner|
|OS|Linux x64 5.4.0-52-generic|
|CPUs|AMD EPYC Processor (with IBPB) (4 x 2495)|
|Memory (System)|7.59GB (0.20GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Here are some things that can cause disconnections
- Extensions or other processes using lots of CPU or memory
- Very large workspaces that cause VS Code's filewatcher process to use lots of memory
- Anything that disrupts the network connection between the local and remote machines

**Comment by CyanBook** [comment]
The RAM and CPU shouldn't be a problem since the load is low and the server has 16GB of ram.
I can ensure my connection is stable.

I noticed that when 2 windows are open, only 1 has this problem. Maybe one day the first, the second day the second window.

I can't work because of this problem. I will give you any info you want. Please help me because this is really slowing my productivity and considerably increasing my frustration. I am not the only one!

![image](https://user-images.githubusercontent.com/29289434/100867853-0b5ab000-349b-11eb-85f6-1fd1eeec7193.png)
![image](https://user-images.githubusercontent.com/29289434/100867876-18779f00-349b-11eb-8975-2076df8d10ec.png)

**Comment by roblourens** [comment]
Do you have any remote extensions installed? Can you try disabling them?

Also try increasing the log level with the command "Set Log Level" > Trace

**Comment by CyanBook** [comment]
![image](https://user-images.githubusercontent.com/29289434/101414161-deb4f700-38e5-11eb-91c9-1fda3279795c.png)
This problem kept representing even with every extension disabled
Log on TRACE: [-1607381514940.log](https://github.com/microsoft/vscode-remote-release/files/5655685/-1607381514940.log)

**Comment by andreujuanc** [comment]
I'm remoting to a devcontainer in wsl2. 
When I compile any medium sized project it disconnects. 
It also happens when I open multiple projects (even without compiling)
Everything is up to date.

Can we tweak the timeout value? if any.

**Comment by roblourens** [comment]
I don't know if you can get anything from this log @alexdima

**Comment by alexdima** [comment]
Here are the relevant log entries:
```
bootstrap-window.js:235 [uncaught exception]: Error: read ECONNRESET
r @ bootstrap-window.js:9
bootstrap-window.js:238 Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:200)
r @ bootstrap-window.js:9
events.js:200 Uncaught Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:200)
log.ts:185  INFO [remote-connection][ExtensionHost][ba0fa…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:185  INFO [remote-connection][ExtensionHost][ba0fa…][reconnect] waiting for 5 seconds before reconnecting...
bootstrap-window.js:235 [uncaught exception]: Error: read ECONNRESET
r @ bootstrap-window.js:9
bootstrap-window.js:238 Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:200)
r @ bootstrap-window.js:9
events.js:200 Uncaught Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:200)
log.ts:185  INFO [remote-connection][Management   ][15cb4…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:185  INFO [remote-connection][Management   ][15cb4…][reconnect] waiting for 5 seconds before reconnecting...
abstractExtensionService.ts:467 Extension host terminated unexpectedly. Code:  1  Signal:  null
_onExtensionHostCrashed @ abstractExtensionService.ts:438
log.ts:197   ERR Extension host terminated unexpectedly. The following extensions were running: ms-vscode-remote.remote-ssh, vscode.microsoft-authentication, vscode.python, softwaredotcom.music-time, softwaredotcom.swdc-vscode, ms-toolsai.jupyter, vscode.debug-auto-launch, vscode.emmet, vscode.git, vscode.merge-conflict, vscode.search-result, donjayamanne.githistory, vscode.github-authentication, vscode.github, ms-vscode.js-debug, ms-python.python, vscode.debug-server-ready, ms-python.vscode-pylance
notificationsAlerts.ts:40 Extension host terminated unexpectedly.
onDidChangeNotification @ breadcrumbsModel.ts:39
localProcessExtensionHost.ts:257 Extension Host
localProcessExtensionHost.ts:258 events.js:200
      throw er; // Unhandled 'error' event
      ^

[Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:200:27)
Emitted 'error' event on Socket instance at:
	at emitErrorNT (internal/streams/destroy.js:92:8)
	at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)] {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
log.ts:173 TRACE Layout#layout, height: 768, width: 603
log.ts:173 TRACE [File Watcher (node.js)] [CHANGED] c:\Users\loren\AppData\Roaming\Code\User\globalStorage
log.ts:173 TRACE [File Watcher (node.js)] [CHANGED] c:\Users\loren\AppData\Roaming\Code\User\globalStorage
log.ts:185  INFO [remote-connection][ExtensionHost][ba0fa…][reconnect] resolving connection...
log.ts:185  INFO [remote-connection][Management   ][15cb4…][reconnect] resolving connection...
log.ts:185  INFO [remote-connection][ExtensionHost][ba0fa…][reconnect] A promise cancelation error occurred while trying to reconnect, will try again...
log.ts:173 TRACE Canceled: Canceled
    at Object.t.canceled (file:///C:/Users/loren/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:49:918)
    at a._clearResolvedAuthority (file:///C:/Users/loren/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1956:198)
    at F._resolveAuthorityAgain (file:///C:/Users/loren/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5415:764)
    at file:///C:/Users/loren/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5416:992
    at c.fire (file:///C:/Users/loren/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:99:67)
    at Object.getAddress (file:///C:/Users/loren/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:5352:338)
    at v (file:///C:/Users/loren/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1944:623)
    at E._runReconnectingLoop (file:///C:/Users/loren/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1948:450)
    at async E._beginReconnecting (file:///C:/Users/loren/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1947:616)
log.ts:185  INFO [remote-connection][ExtensionHost][ba0fa…][reconnect] waiting for 5 seconds before reconnecting...
```

The root cause is:
```
abstractExtensionService.ts:467 Extension host terminated unexpectedly. Code:  1  Signal:  null
_onExtensionHostCrashed @ abstractExtensionService.ts:438
log.ts:197   ERR Extension host terminated unexpectedly. The following extensions were running: ms-vscode-remote.remote-ssh, vscode.microsoft-authentication, vscode.python, softwaredotcom.music-time, softwaredotcom.swdc-vscode, ms-toolsai.jupyter, vscode.debug-auto-launch, vscode.emmet, vscode.git, vscode.merge-conflict, vscode.search-result, donjayamanne.githistory, vscode.github-authentication, vscode.github, ms-vscode.js-debug, ms-python.python, vscode.debug-server-ready, ms-python.vscode-pylance
```

This is a bit difficult to digest, but it means that the local extension host (the one where `ms-vscode-remote.remote-ssh` executes) has crashed. The list of running extensions contains both local and remote running extensions and does not list to each one where they were executing. This leads to what I guess is automatic closing of the SSH tunnels since `ms-vscode-remote.remote-ssh` is no longer executing.

Having seen lists of crashing extensions for a while, please try to disable/uninstall `softwaredotcom.music-time` and `softwaredotcom.swdc-vscode`. From our telemetry, users that have these extensions installed can see anywhere between 4x to 6 x times more crashes than users without them.
