### ISSUE TITLE
Can not start vscode-server on windows 10 pro host from macos client

### ISSUE THREAD

**Issue by r4t31** [microsoft/vscode-remote-release#4089]
Can not start vscode-server on windows 10 pro host from macos client

[12:07:02.575] SSH Resolver called for host: ratel@antosha.local
[12:07:02.575] Setting up SSH remote "antosha.local"
[12:07:02.578] Acquiring local install lock: /var/folders/wg/8ndjkz1n1wqdr1870xn033mc0000gn/T/vscode-remote-ssh-ratel@antosha.local-install.lock
[12:07:02.589] Looking for existing server data file at /Users/ratel/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-ratel@antosha.local-e5a624b788d92b8d34d1392e4c4d9789406efe8f-0.56.0/data.json
[12:07:02.591] Using commit id "e5a624b788d92b8d34d1392e4c4d9789406efe8f" and quality "stable" for server
[12:07:02.592] Install and start server if needed
[12:07:02.597] Checking ssh with "ssh -V"
[12:07:02.614] > OpenSSH_7.8p1, LibreSSL 2.6.2

[12:07:02.645] askpass server listening on /var/folders/wg/8ndjkz1n1wqdr1870xn033mc0000gn/T/vscode-ssh-askpass-c1d8c8138452367b521f46b257b31f40760e6012.sock
[12:07:02.646] Spawning local server with {"ipcHandlePath":"/var/folders/wg/8ndjkz1n1wqdr1870xn033mc0000gn/T/vscode-ssh-askpass-2b6d20b3321a166b7638597832dcdbae6adebc71.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","49877","-o","ConnectTimeout=15","ratel@antosha.local"],"dataFilePath":"/Users/ratel/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-ratel@antosha.local-e5a624b788d92b8d34d1392e4c4d9789406efe8f-0.56.0/data.json"}
[12:07:02.646] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/ratel/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/ratel/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/wg/8ndjkz1n1wqdr1870xn033mc0000gn/T/vscode-ssh-askpass-c1d8c8138452367b521f46b257b31f40760e6012.sock"}
[12:07:02.649] Spawned 95069
[12:07:02.758] > local-server> Spawned ssh: 95070
[12:07:02.771] stderr> OpenSSH_7.8p1, LibreSSL 2.6.2
[12:07:03.058] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:GrblhNyreSxcobEDM3D3IWm5k6o3C9R0GeJGLXKdC68
[12:07:03.272] Got askpass request: {"request":"ratel@antosha.local's password:"}
[12:07:03.273] Showing password prompt
[12:07:03.275] Listening for interwindow password on /var/folders/wg/8ndjkz1n1wqdr1870xn033mc0000gn/T/vscode-ssh-askpass-38074f4bfe18312694fcbb40f5914ce621b085bc.sock
[12:07:03.275] Writing password prompt to globalState
[12:07:06.807] Got password response
[12:07:06.807] Interactor gave response: *********
[12:07:06.807] Cleaning up other-window auth server
[12:07:06.847] stderr> Authenticated to antosha.local ([fe80::59c7:a432:365:ebe6%en0]:22).
[12:07:06.867] stderr> shell request failed on channel 2
[12:07:06.869] > local-server> ssh child died, shutting down
[12:07:06.875] Local server exit: 0
[12:07:06.875] Received install output: OpenSSH_7.8p1, LibreSSL 2.6.2
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:GrblhNyreSxcobEDM3D3IWm5k6o3C9R0GeJGLXKdC68
Authenticated to antosha.local ([fe80::59c7:a432:365:ebe6%en0]:22).
shell request failed on channel 2

[12:07:06.876] Stopped parsing output early. Remaining text: OpenSSH_7.8p1, LibreSSL 2.6.2debug1: Server host key: ecdsa-sha2-nistp256 SHA256:Grblh Authenticated to antosha.local ([fe80::59c7:a432:365:ebe6%en0]:22).shell request failed on channel 2
[12:07:06.876] Failed to parse remote port from server output
[12:07:06.882] Resolver error: Error: 
	at Function.Create (/Users/ratel/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:1:94424)
	at Object.t.handleInstallOutput (/Users/ratel/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:1:91173)
	at Object.t.tryInstallWithLocalServer (/Users/ratel/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:102430)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /Users/ratel/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:104510
	at async Object.t.withShowDetailsEvent (/Users/ratel/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:110096)
	at async /Users/ratel/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:101003
	at async R (/Users/ratel/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:97793)
	at async Object.t.resolveWithLocalServer (/Users/ratel/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:100652)
	at async Object.t.resolve (/Users/ratel/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:108038)
	at async /Users/ratel/.vscode/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:143767
[12:07:06.893] ------

**Comment by r4t31** [comment]
Solve with reboot windows host after installing of OpenSSH.Server

**Comment by r4t31** [comment]
Solve with reboot windows host after installing of OpenSSH.Server
