### ISSUE TITLE
Connection timed out during banner exchange

### ISSUE THREAD

**Issue by sierhlj** [microsoft/vscode-remote-release#4091]
I have encountered ssh connectivity issues tonight. 
My ssh connection is achieved by implementing a proxy jump.  Though I can ssh via shell, I had difficulty connecting to the remote server in the remote development mode.  The error prompt is **Connection timed out during banner exchange**. 

**Here is the log.** 

```
[22:26:44.098] Log Level: 2
[22:26:44.100] remote-ssh@0.56.0
[22:26:44.100] darwin x64
[22:26:44.101] SSH Resolver called for "ssh-remote+chcpu.xxx.hk", attempt 1
[22:26:44.101] SSH Resolver called for host: chcpu.xxx.hk"
[22:26:44.102] Setting up SSH remote "chcpu.xxx.hk"
[22:26:44.105] Acquiring local install lock: /var/folders/g8/ly5k7twn565332w3l4hy63h80000gn/T/vscode-remote-ssh-chcpu.xxx.hk"-install.lock
[22:26:44.114] Looking for existing server data file at /Users/lj/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-chcpu.xxx.hk"-0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d-0.56.0/data.json
[22:26:44.116] Using commit id "0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d" and quality "insider" for server
[22:26:44.118] Install and start server if needed
[22:26:44.122] Checking ssh with "ssh -V"
[22:26:44.130] > OpenSSH_8.1p1, LibreSSL 2.7.3

[22:26:44.134] askpass server listening on /var/folders/g8/ly5k7twn565332w3l4hy63h80000gn/T/vscode-ssh-askpass-c58b283284b4d24040dcb84528a4eda643e75c36.sock
[22:26:44.135] Spawning local server with {"ipcHandlePath":"/var/folders/g8/ly5k7twn565332w3l4hy63h80000gn/T/vscode-ssh-askpass-2a0f6c306a417d5cea6abf3e336d8ed7f0f3e483.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","49701","-o","ConnectTimeout=15","chcpu10.cse.ust.hk"],"dataFilePath":"/Users/lj/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-chcpu.xxx.hk"-0a80aacc7be1ab03ec0f94b8ac1a84949a83f35d-0.56.0/data.json"}
[22:26:44.135] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/lj/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/lj/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/g8/ly5k7twn565332w3l4hy63h80000gn/T/vscode-ssh-askpass-c58b283284b4d24040dcb84528a4eda643e75c36.sock"}
[22:26:44.137] Spawned 3616
[22:26:44.239] > local-server> Spawned ssh: 3617
[22:26:44.243] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[22:26:44.256] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[22:26:59.250] stderr> Connection timed out during banner exchange
[22:26:59.254] > local-server> ssh child died, shutting down
[22:26:59.262] Local server exit: 0
[22:26:59.263] Received install output: OpenSSH_8.1p1, LibreSSL 2.7.3
OpenSSH_8.1p1, LibreSSL 2.7.3
Connection timed out during banner exchange

[22:26:59.270] Resolver error: Error: The connection timed out
	at Function.Offline (/Users/lj/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:1:94478)
	at /Users/lj/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:1:90174
	at Object.t.handleInstallOutput (/Users/lj/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:1:90449)
	at Object.t.tryInstallWithLocalServer (/Users/lj/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:102430)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async /Users/lj/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:104510
	at async Object.t.withShowDetailsEvent (/Users/lj/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:110096)
	at async /Users/lj/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:101003
	at async R (/Users/lj/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:97793)
	at async Object.t.resolveWithLocalServer (/Users/lj/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:100652)
	at async Object.t.resolve (/Users/lj/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:108038)
	at async /Users/lj/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.56.0/out/extension.js:127:143767
[22:26:59.274] ------

```

**Here is my local config**  (this config is working while ssh via shells
Host chcpu.xxxt.hk
    HostName chcpu.xxxt.hk
    User linjie
    LocalForward 4xx77 localhost:4xx77
    ProxyJump ras
    
Host ras
    User lhuaxxxxx
    HostName xxxxxxx

**Comment by roblourens** [comment]
This error is from ssh, I don't know what it implies exactly. Does a command like `echo uname | ssh <yourhost>` work in an external terminal?

Does disabling `remote.SSH.useLocalServer` help?
