### ISSUE TITLE
SSH connection with useLocalServer enabled fails when hostname has special characters

### ISSUE THREAD

**Issue by AndyBehr** [microsoft/vscode-remote-release#4138]
- VSCode Version: 1.51.1
- Local OS Version: macos 11.0.1
- Remote OS Version: n/a
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Setup up remote host with keybased auth
2. when connection it gets stuck on "Starting to look for password prompt from another window"

But my key does not have a password.
If I change the login to password based it works fine.

```
[18:40:39.450] Log Level: 2
[18:40:39.451] remote-ssh@0.56.0
[18:40:39.452] darwin x64
[18:40:39.453] SSH Resolver called for "ssh-remote+private/berryzero", attempt 1
[18:40:39.454] SSH Resolver called for host: private/berryzero
[18:40:39.454] Setting up SSH remote "private/berryzero"
[18:40:39.457] Acquiring local install lock: /var/folders/nf/tyjf2xxn4jb2sqhryq3dxnkc0000gn/T/vscode-remote-ssh-private/berryzero-install.lock
[18:40:40.960] Starting to look for password prompt from another window
```

**Comment by roblourens** [comment]
I think this is due to the `/` in your hostname. Please try without

**Comment by MACscr** [comment]
Hmm, is there no solution for this? I have to use formats like username@domain.com, so ssh would be: 

```ssh foo@domain.com@domain.com``` or ```ssh foo#domain.com@domain.com``` are both acceptable formats.

This is simply how the hosting/user environments are setup in order to allow multiple domains on the server with multiple users with no naming conflicts.

**Comment by roblourens** [comment]
Not sure this is the same issue, can you explain yours a little more?

**Comment by akosyakov** [comment]
I have similar issue for following SSH command: `ssh -F /tmp/gitpod_ssh_config amaranth-rabbit-vfz9eqz1`
```
[14:15:04.915] SSH Resolver called for host: ssh -F /tmp/gitpod_ssh_config amaranth-rabbit-vfz9eqz1
[14:15:04.915] Setting up SSH remote "ssh -F /tmp/gitpod_ssh_config amaranth-rabbit-vfz9eqz1"
[14:15:04.918] Acquiring local install lock: /var/folders/4c/y9gk896j7236wypqzgp0d20h0000gn/T/vscode-remote-ssh-ssh -F /tmp/gitpod_ssh_config amaranth-rabbit-vfz9eqz1-install.lock
[14:15:06.422] Starting to look for password prompt from another window
[14:17:05.783] Resolver error: Error: Timed out while waiting for the local startup lock
	at Function.Create (/Users/akosyakov/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:64641)
	at /Users/akosyakov/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:381482
	at n (/Users/akosyakov/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:127:152731)
	at /Users/akosyakov/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:127:152984
	at FSReqCallback.oncomplete (fs.js:160:23)
```

If I configure though to use `/tmp/gitpod_ssh_config` in settings then it works.

@roblourens Is it related or different bug?

**Comment by KaysData** [comment]
I had the same problem, This helped.

**Comment by roblourens** [comment]
Fixed in https://github.com/microsoft/vscode-remote-ssh/commit/63709525f00da24d488dab5eb7343d668c541d13
