### ISSUE TITLE
Mac mini M1 Can not connect remote cent os server using VScode exploration 

### ISSUE THREAD

**Issue by Chenghao-Wu** [microsoft/vscode-remote-release#4139]
- VSCode Version:
Version: 1.52.0-exploration
Commit: 25a4ee40993f43df9229edc552bd3018c086569d
Date: 2020-12-03T22:37:53.684Z (19 hrs ago)
Electron: 11.0.3
Chrome: 87.0.4280.67
Node.js: 12.18.3
V8: 8.7.220.25-electron.0
OS: Darwin arm64 20.1.0

- Local OS Version:
Model Name:	Mac mini
Model Identifier:	Macmini9,1
Chip:	Apple M1
OS: big sur 11.0.1

- Remote OS Version:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Remote Extension/Connection Type: SSH

Log:

```
TRACE [storage state.vscdb] open(/Users/bruce/Library/Application Support/Code - Exploration/User/workspaceStorage/1607106133276/state.vscdb, retryOnBusy: true)
log.ts:173 TRACE [storage state.vscdb] Trace (event): PRAGMA user_version = 1;
log.ts:173 TRACE [storage state.vscdb] Trace (event): CREATE TABLE IF NOT EXISTS ItemTable (key TEXT UNIQUE ON CONFLICT REPLACE, value BLOB)
log.ts:173 TRACE lifecycle: starting up (startup kind: 1)
log.ts:173 TRACE lifecycle: phase changed (value: 2)
log.ts:173 TRACE Skipping initializing user data in desktop
log.ts:173 TRACE Layout#layout, height: 1055, width: 1865
log.ts:173 TRACE workbench configuration {"_":[],"logsPath":"/Users/bruce/Library/Application Support/Code - Exploration/logs/20201204T184143","remote":"ssh-remote+sniffa","appRoot":"/Applications/Visual Studio Code - Exploration.app/Contents/Resources/app","machineId":"ac782dc8dbee7a641f623f4c7f94fa469e03b978610db7c7ab2a410cf42d3b5c","nodeCachedDataDir":"/Users/bruce/Library/Application Support/Code - Exploration/CachedData/25a4ee40993f43df9229edc552bd3018c086569d","mainPid":27647,"execPath":"/Applications/Visual Studio Code - Exploration.app/Contents/MacOS/Electron","userEnv":{"VSCODE_IPC_HOOK":"/Users/bruce/Library/Application Support/Code - Exploration/1.52.0-exploration-main.sock","VSCODE_NLS_CONFIG":"{\"locale\":\"en-gb\",\"availableLanguages\":{},\"_languagePackSupport\":true}"},"remoteAuthority":"ssh-remote+sniffa","backupPath":"/Users/bruce/Library/Application Support/Code - Exploration/Backups/1607106133276","windowId":4,"sessionId":"window:4","logLevel":0,"colorScheme":{"dark":true,"highContrast":false},"autoDetectHighContrast":true,"maximized":true,"perfEntries":["main:started",1607103703170,"main:appReady",1607103703347,"nlsGeneration:start",1607103703348,"nlsGeneration:end",1607103703348,"willLoadMainBundle",1607103703368,"didLoadMainBundle",1607103703398,"main:loadWindow",1607103703545,"main:loadWindow",1607103983437,"main:loadWindow",1607103999284,"main:loadWindow",1607104732477,"main:loadWindow",1607105631992,"main:loadWindow",1607105663268,"main:loadWindow",1607105681561,"main:loadWindow",1607105686855,"main:loadWindow",1607105941776,"main:loadWindow",1607106132825],"partsSplashPath":"/Users/bruce/Library/Application Support/Code - Exploration/rapid_render.json","os":{"release":"20.1.0"}}
log.ts:173 TRACE lifecycle: phase changed (value: 3)
log.ts:173 TRACE Created Spdlogger
log.ts:173 TRACE [storage state.vscdb] updateItems(): insert(Map(12) {__$__isNewStorageMarker => true, __$__targetStorageMarker => {"workbench.panel.markers":1,"workbench.panel.output":1,"terminal":1,"workbench.explorer.views.state":1,"workbench.scm.views.state":1,"workbench.view.search.state":1,"output.activechannel":0,"workbench.centerededitorlayout.active":0,"debug.selectedroot":1,"workbench.view.debug.state":1}, workbench.panel.markers => {"workbench.panel.markers.view":{"collapsed":false,"isHidden":true}}, workbench.panel.output => {"workbench.panel.output":{"collapsed":false,"isHidden":true}}, terminal => {"terminal":{"collapsed":false,"isHidden":true}}, workbench.explorer.views.state => {"outline":{"collapsed":true,"isHidden":true},"timeline":{"collapsed":true,"isHidden":true},"workbench.explorer.openEditorsView":{"collapsed":true,"isHidden":true},"workbench.explorer.emptyView":{"collapsed":false,"isHidden":true}}, workbench.scm.views.state => {"workbench.scm.repositories":{"collapsed":false,"isHidden":true},"workbench.scm":{"collapsed":false,"isHidden":false}}, workbench.view.search.state => {"workbench.view.search":{"collapsed":false,"isHidden":true}}, output.activechannel => tasks, workbench.centerededitorlayout.active => false, debug.selectedroot => vscode-userdata:/Users/bruce/Library/Application%20Support/Code%20-%20Exploration/User/settings.json, workbench.view.debug.state => {"workbench.debug.welcome":{"collapsed":false,"isHidden":true},"workbench.debug.variablesView":{"collapsed":false,"isHidden":true},"workbench.debug.watchExpressionsView":{"collapsed":false,"isHidden":true},"workbench.debug.callStackView":{"collapsed":false,"isHidden":true},"workbench.debug.loadedScriptsView":{"collapsed":true,"isHidden":true},"workbench.debug.breakPointsView":{"collapsed":false,"isHidden":true}}}), delete(Set(0) {})
log.ts:173 TRACE [storage state.vscdb] Trace (event): BEGIN TRANSACTION
log.ts:173 TRACE [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('__$__isNewStorageMarker','true'),('__$__targetStorageMarker','{"workbench.panel.markers":1,"workbench.panel.output":1,"terminal":1,"workbench.explorer.views.state":1,"workbench.scm.views.state":1,"workbench.view.search.state":1,"output.activechannel":0,"workbench.centerededitorlayout.active":0,"debug.selectedroot":1,"workbench.view.debug.state":1}'),('workbench.panel.markers','{"workbench.panel.markers.view":{"collapsed":false,"isHidden":true}}'),('workbench.panel.output','{"workbench.panel.output":{"collapsed":false,"isHidden":true}}'),('terminal','{"terminal":{"collapsed":false,"isHidden":true}}'),('workbench.explorer.views.state','{"outline":{"collapsed":true,"isHidden":true},"timeline":{"collapsed":true,"isHidden":true},"workbench.explorer.openEditorsView":{"collapsed":true,"isHidden":true},"workbench.explorer.emptyView":{"collapsed":false,"isHidden":true}}'),('workbench.scm.views.state','{"workbench.scm.repositories":{"collapsed":false,"isHidden":true},"workbench.scm":{"collapsed":false,"isHidden":false}}'),('workbench.view.search.state','{"workbench.view.search":{"collapsed":false,"isHidden":true}}'),('output.activechannel','tasks'),('workbench.centerededitorlayout.active','false'),('debug.selectedroot','vscode-userdata:/Users/bruce/Library/Application%20Support/Code%20-%20Exploration/User/settings.json'),('workbench.view.debug.state','{"workbench.debug.welcome":{"collapsed":false,"isHidden":true},"workbench.debug.variablesView":{"collapsed":false,"isHidden":true},"workbench.debug.watchExpressionsView":{"collapsed":false,"isHidden":true},"workbench.debug.callStackView":{"collapsed":false,"isHidden":true},"workbench.debug.loadedScriptsView":{"collapsed":true,"isHidden":true},"workbench.debug.breakPointsView":{"collapsed":false,"isHidden":true}}')
log.ts:173 TRACE [storage state.vscdb] Trace (event): END TRANSACTION
log.ts:173 TRACE [File Watcher (node.js)] [CHANGED] /Users/bruce/Library/Application Support/Code - Exploration/logs/20201204T184143/output_4_20201204T192213/tasks.log
log.ts:173 TRACE [File Watcher (node.js)] [CHANGED] /Users/bruce/Library/Application Support/Code - Exploration/logs/20201204T184143/output_4_20201204T192213/extensions.log
log.ts:173 TRACE MainThreadTreeViews#$registerTreeViewDataProvider sshHosts Object
log.ts:173 TRACE CommandService#executeCommand setContext
log.ts:173 TRACE [File Watcher (node.js)] >> normalized [CHANGED] /Users/bruce/Library/Application Support/Code - Exploration/logs/20201204T184143/output_4_20201204T192213/tasks.log
log.ts:173 TRACE [File Watcher (node.js)] >> normalized [CHANGED] /Users/bruce/Library/Application Support/Code - Exploration/logs/20201204T184143/output_4_20201204T192213/extensions.log
log.ts:173 TRACE KeybindingService#dispatch W undefined
log.ts:173 TRACE KeybindingService#dispatch 6 undefined
log.ts:173 TRACE KeybindingService#dispatch 3 undefined
log.ts:173 TRACE KeybindingService#dispatch 6 undefined
log.ts:173 TRACE KeybindingService#dispatch 1 undefined
log.ts:173 TRACE KeybindingService#dispatch 3 undefined
log.ts:173 TRACE KeybindingService#dispatch 2 undefined
log.ts:173 TRACE lifecycle: phase changed (value: 4)
log.ts:173 TRACE RequestService#request https://vscodeexperiments.azureedge.net/experiments/vscode-experiments.json
log.ts:173 TRACE KeybindingService#dispatch 1 undefined
log.ts:173 TRACE [storage state.vscdb] updateItems(): insert(Map(2) {__$__targetStorageMarker => {"workbench.panel.markers":1,"workbench.panel.output":1,"terminal":1,"workbench.explorer.views.state":1,"workbench.scm.views.state":1,"workbench.view.search.state":1,"output.activechannel":0,"workbench.centerededitorlayout.active":0,"debug.selectedroot":1,"workbench.view.debug.state":1,"workbench.view.remote.state":1}, workbench.view.remote.state => {"~remote.forwardedPorts":{"collapsed":false,"isHidden":false}}}), delete(Set(0) {})
log.ts:173 TRACE [storage state.vscdb] Trace (event): BEGIN TRANSACTION
log.ts:173 TRACE [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('__$__targetStorageMarker','{"workbench.panel.markers":1,"workbench.panel.output":1,"terminal":1,"workbench.explorer.views.state":1,"workbench.scm.views.state":1,"workbench.view.search.state":1,"output.activechannel":0,"workbench.centerededitorlayout.active":0,"debug.selectedroot":1,"workbench.view.debug.state":1,"workbench.view.remote.state":1}'),('workbench.view.remote.state','{"~remote.forwardedPorts":{"collapsed":false,"isHidden":false}}')
log.ts:173 TRACE [storage state.vscdb] Trace (event): END TRANSACTION
log.ts:173 TRACE KeybindingService#dispatch 8 undefined
log.ts:173 TRACE CommandService#executeCommand setContext
console.ts:137 [Extension Host] (node:28024) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (at writeOut (internal/process/warning.js:32:3))
t.log @ console.ts:137
log.ts:173 TRACE terminalInstance#ctor (id: 1) Object
log.ts:173 TRACE [remote-connection][Management   ][67806…][initial][127.0.0.1:50027] 1/6. invoking socketFactory.connect().
log.ts:173 TRACE [remote-connection][ExtensionHost][5eca9…][initial][127.0.0.1:50027] 1/6. invoking socketFactory.connect().
log.ts:173 TRACE [remote-connection][Management   ][67806…][initial][127.0.0.1:50027] 2/6. socketFactory.connect() was successful.
log.ts:173 TRACE [remote-connection][Management   ][67806…][initial][127.0.0.1:50027] 3/6. sending AuthRequest control message.
log.ts:173 TRACE [remote-connection][ExtensionHost][5eca9…][initial][127.0.0.1:50027] 2/6. socketFactory.connect() was successful.
log.ts:173 TRACE [remote-connection][ExtensionHost][5eca9…][initial][127.0.0.1:50027] 3/6. sending AuthRequest control message.
log.ts:173 TRACE [remote-connection][Management   ][67806…][initial][127.0.0.1:50027] 4/6. received SignRequest control message.
log.ts:173 TRACE [remote-connection][ExtensionHost][5eca9…][initial][127.0.0.1:50027] 4/6. received SignRequest control message.
log.ts:173 TRACE [remote-connection][Management   ][67806…][initial][127.0.0.1:50027] 5/6. sending ConnectionTypeRequest control message.
log.ts:173 TRACE [remote-connection][ExtensionHost][5eca9…][initial][127.0.0.1:50027] 5/6. sending ConnectionTypeRequest control message.
log.ts:197   ERR [remote-connection][Management   ][67806…][initial][127.0.0.1:50027] received error control message when negotiating connection. Error:
log.ts:197   ERR Error: Connection error: Unauthorized client refused.
    at D (remoteAgentConnection.ts:560)
    at remoteAgentConnection.ts:193
    at c.fire (event.ts:587)
    at fire (ipc.net.ts:468)
    at t.PersistentProtocol._receiveMessage (ipc.net.ts:821)
    at ipc.net.ts:660
    at c.fire (event.ts:587)
    at g.acceptChunk (ipc.net.ts:241)
    at ipc.net.ts:202
    at Socket.t (ipc.net.ts:31)
    at Socket.emit (events.js:315)
    at addChunk (_stream_readable.js:295)
    at readableAddChunk (_stream_readable.js:271)
    at Socket.Readable.push (_stream_readable.js:212)
    at TCP.onStreamRead (internal/stream_base_commons.js:186)
log.ts:197   ERR [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
log.ts:197   ERR Error: Connection error: Unauthorized client refused.
    at D (remoteAgentConnection.ts:560)
    at remoteAgentConnection.ts:193
    at c.fire (event.ts:587)
    at fire (ipc.net.ts:468)
    at t.PersistentProtocol._receiveMessage (ipc.net.ts:821)
    at ipc.net.ts:660
    at c.fire (event.ts:587)
    at g.acceptChunk (ipc.net.ts:241)
    at ipc.net.ts:202
    at Socket.t (ipc.net.ts:31)
    at Socket.emit (events.js:315)
    at addChunk (_stream_readable.js:295)
    at readableAddChunk (_stream_readable.js:271)
    at Socket.Readable.push (_stream_readable.js:212)
    at TCP.onStreamRead (internal/stream_base_commons.js:186)
notificationsAlerts.ts:40 Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused.)
onDidChangeNotification @ notificationsAlerts.ts:40
notificationsAlerts.ts:40 Could not fetch remote environment
onDidChangeNotification @ notificationsAlerts.ts:40
log.ts:197   ERR Connection error: Unauthorized client refused.: Error: Connection error: Unauthorized client refused.
    at D (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1997:697)
    at file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1990:507
    at c.fire (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:99:696)
    at fire (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:448:356)
    at t.PersistentProtocol._receiveMessage (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:453:580)
    at file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:450:519
    at c.fire (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:99:696)
    at g.acceptChunk (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:445:789)
    at file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:445:141
    at Socket.t (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:455:389)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
2log.ts:173 TRACE onWillActivateByEvent:  onFileSystem:vscode-userdata
log.ts:173 TRACE Settings Sync: Initializing accounts
log.ts:173 TRACE Settings Sync: Getting accounts for microsoft
log.ts:173 TRACE onWillActivateByEvent:  onAuthenticationRequest:microsoft
log.ts:173 TRACE onWillActivateByEvent:  onFileSystem:file
log.ts:173 TRACE onWillActivateByEvent:  onFileSystem:vscode-userdata
13log.ts:173 TRACE onWillActivateByEvent:  onFileSystem:file
6log.ts:173 TRACE onWillActivateByEvent:  onFileSystem:vscode-userdata
log.ts:173 TRACE onWillActivateByEvent:  onCommand:setContext
2log.ts:173 TRACE onWillActivateByEvent:  onFileSystem:file
log.ts:173 TRACE onWillActivateByEvent:  onCommand:setContext
log.ts:197   ERR [remote-connection][ExtensionHost][5eca9…][initial][127.0.0.1:50027] received error control message when negotiating connection. Error:
log.ts:197   ERR Error: Connection error: Unauthorized client refused.
    at D (remoteAgentConnection.ts:560)
    at remoteAgentConnection.ts:193
    at c.fire (event.ts:587)
    at fire (ipc.net.ts:468)
    at t.PersistentProtocol._receiveMessage (ipc.net.ts:821)
    at ipc.net.ts:660
    at c.fire (event.ts:587)
    at g.acceptChunk (ipc.net.ts:241)
    at ipc.net.ts:202
    at Socket.t (ipc.net.ts:31)
    at Socket.emit (events.js:315)
    at addChunk (_stream_readable.js:295)
    at readableAddChunk (_stream_readable.js:271)
    at Socket.Readable.push (_stream_readable.js:212)
    at TCP.onStreamRead (internal/stream_base_commons.js:186)
log.ts:197   ERR [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
log.ts:197   ERR Error: Connection error: Unauthorized client refused.
    at D (remoteAgentConnection.ts:560)
    at remoteAgentConnection.ts:193
    at c.fire (event.ts:587)
    at fire (ipc.net.ts:468)
    at t.PersistentProtocol._receiveMessage (ipc.net.ts:821)
    at ipc.net.ts:660
    at c.fire (event.ts:587)
    at g.acceptChunk (ipc.net.ts:241)
    at ipc.net.ts:202
    at Socket.t (ipc.net.ts:31)
    at Socket.emit (events.js:315)
    at addChunk (_stream_readable.js:295)
    at readableAddChunk (_stream_readable.js:271)
    at Socket.Readable.push (_stream_readable.js:212)
    at TCP.onStreamRead (internal/stream_base_commons.js:186)
extensionHostManager.ts:73 Error received from starting extension host
(anonymous) @ extensionHostManager.ts:73
extensionHostManager.ts:74 Error: Connection error: Unauthorized client refused.
    at D (remoteAgentConnection.ts:560)
    at remoteAgentConnection.ts:193
    at c.fire (event.ts:587)
    at fire (ipc.net.ts:468)
    at t.PersistentProtocol._receiveMessage (ipc.net.ts:821)
    at ipc.net.ts:660
    at c.fire (event.ts:587)
    at g.acceptChunk (ipc.net.ts:241)
    at ipc.net.ts:202
    at Socket.t (ipc.net.ts:31)
    at Socket.emit (events.js:315)
    at addChunk (_stream_readable.js:295)
    at readableAddChunk (_stream_readable.js:271)
    at Socket.Readable.push (_stream_readable.js:212)
    at TCP.onStreamRead (internal/stream_base_commons.js:186)
(anonymous) @ extensionHostManager.ts:74
log.ts:197   ERR Could not fetch remote environment: Error: Could not fetch remote environment
    at S.start (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5302:482)
    at async k.createProcess (file:///Applications/Visual Studio Code - Exploration.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5329:650)
log.ts:173 TRACE MainThreadTreeViews#$refresh sshHosts undefined
log.ts:173 TRACE Settings Sync: Updated accounts for microsoft
log.ts:173 TRACE Settings Sync: Getting accounts for github
log.ts:173 TRACE onWillActivateByEvent:  onAuthenticationRequest:github
log.ts:173 TRACE Settings Sync: Updated accounts for github
log.ts:173 TRACE Settings Sync: Account status changed from uninitialized to unavailable
log.ts:173 TRACE Settings Sync: Accounts are initialized
log.ts:173 TRACE [storage state.vscdb] updateItems(): insert(Map(3) {workbench.view.remote.state => {"~remote.forwardedPorts":{"collapsed":false,"isHidden":false},"sshHosts":{"collapsed":false,"isHidden":true}}, __$__targetStorageMarker => {"workbench.panel.markers":1,"workbench.panel.output":1,"terminal":1,"workbench.explorer.views.state":1,"workbench.scm.views.state":1,"workbench.view.search.state":1,"output.activechannel":0,"workbench.centerededitorlayout.active":0,"debug.selectedroot":1,"workbench.view.debug.state":1,"workbench.view.remote.state":1,"workbench.panel.placeholderPanels":1}, workbench.panel.placeholderPanels => [{"id":"workbench.panel.markers","name":"Problems"},{"id":"workbench.panel.output","name":"Output"},{"id":"workbench.panel.repl","name":"Debug Console"},{"id":"terminal","name":"Terminal"},{"id":"refactorPreview","name":"Refactor Preview"}]}), delete(Set(0) {})
log.ts:173 TRACE [storage state.vscdb] Trace (event): BEGIN TRANSACTION
log.ts:173 TRACE [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('workbench.view.remote.state','{"~remote.forwardedPorts":{"collapsed":false,"isHidden":false},"sshHosts":{"collapsed":false,"isHidden":true}}'),('__$__targetStorageMarker','{"workbench.panel.markers":1,"workbench.panel.output":1,"terminal":1,"workbench.explorer.views.state":1,"workbench.scm.views.state":1,"workbench.view.search.state":1,"output.activechannel":0,"workbench.centerededitorlayout.active":0,"debug.selectedroot":1,"workbench.view.debug.state":1,"workbench.view.remote.state":1,"workbench.panel.placeholderPanels":1}'),('workbench.panel.placeholderPanels','[{"id":"workbench.panel.markers","name":"Problems"},{"id":"workbench.panel.output","name":"Output"},{"id":"workbench.panel.repl","name":"Debug Console"},{"id":"terminal","name":"Terminal"},{"id":"refactorPreview","name":"Refactor Preview"}]')
log.ts:173 TRACE [storage state.vscdb] Trace (event): END TRANSACTION
log.ts:173 TRACE MainThreadTreeViews#$refresh sshHosts undefined
log.ts:173 TRACE CommandService#executeCommand workbench.action.toggleDevTools
```

**Comment by roblourens** [comment]
Could there be an issue with the vsda native module on mac arm? @deepak1556 @alexdima

**Comment by deepak1556** [comment]
Just tested the vsda test suite with the vsda module shipped in arm64 exploration build and every result is correct. Will test with a ssh server on my device.

**Comment by deepak1556** [comment]
Was able to connect fine to ubuntu 18 server, testing with centos 7 server

![Screen Shot 2020-12-04 at 12 19 26 PM](https://user-images.githubusercontent.com/964386/101211045-602d3080-362b-11eb-932c-6528d7bbc132.png)

**Comment by deepak1556** [comment]
Connecting to centos 7 failed on both mac arm64 and x64 with exploration, while succeeded with insiders version. This alludes that problem is still with built native modules.

But the log message doesn't say what is failing,

```
[12:32:36.669] Log Level: 2
[12:32:36.673] remote-ssh@0.58.0
[12:32:36.673] darwin x64
[12:32:36.674] SSH Resolver called for "ssh-remote+192.34.56.10", attempt 1
[12:32:36.675] "remote.SSH.useLocalServer": true
[12:32:36.675] "remote.SSH.sshPath": undefined
[12:32:36.675] "remote.SSH.sshConfigurationFile": undefined
[12:32:36.676] "remote.SSH.useFlock": true
[12:32:36.676] "remote.SSH.lockfilesInTmp": false
[12:32:36.676] "remote.SSH.localServerDownload": auto
[12:32:36.676] "remote.SSH.remoteServerListenOnSocket": false
[12:32:36.677] "remote.SSH.showLoginTerminal": false
[12:32:36.677] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[12:32:36.677] SSH Resolver called for host: 192.34.56.10
[12:32:36.677] Setting up SSH remote "192.34.56.10"
[12:32:36.680] Acquiring local install lock: /var/folders/tr/67t1nysj0l73x554k1x2lpgw0000gn/T/vscode-remote-ssh-192.34.56.10-install.lock
[12:32:36.694] Looking for existing server data file at /Users/demohan/Library/Application Support/Code - Exploration/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-192.34.56.10-25a4ee40993f43df9229edc552bd3018c086569d-0.58.0/data.json
[12:32:36.695] Using commit id "25a4ee40993f43df9229edc552bd3018c086569d" and quality "exploration" for server
[12:32:36.699] Install and start server if needed
[12:32:36.704] Checking ssh with "ssh -V"
[12:32:36.712] > OpenSSH_8.1p1, LibreSSL 2.7.3

[12:32:36.717] askpass server listening on /var/folders/tr/67t1nysj0l73x554k1x2lpgw0000gn/T/vscode-ssh-askpass-64fd631c744b7069fffea065738cbf1bd1d5af34.sock
[12:32:36.717] Spawning local server with {"ipcHandlePath":"/var/folders/tr/67t1nysj0l73x554k1x2lpgw0000gn/T/vscode-ssh-askpass-4f1d93caf3fe22e12909a783c153c97a045c8c68.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","50999","-o","ConnectTimeout=15","192.34.56.10"],"dataFilePath":"/Users/demohan/Library/Application Support/Code - Exploration/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-192.34.56.10-25a4ee40993f43df9229edc552bd3018c086569d-0.58.0/data.json"}
[12:32:36.717] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/demohan/.vscode-exploration/extensions/ms-vscode-remote.remote-ssh-0.58.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code - Exploration.app/Contents/Frameworks/Code - Exploration Helper (Renderer).app/Contents/MacOS/Code - Exploration Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/demohan/.vscode-exploration/extensions/ms-vscode-remote.remote-ssh-0.58.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/tr/67t1nysj0l73x554k1x2lpgw0000gn/T/vscode-ssh-askpass-64fd631c744b7069fffea065738cbf1bd1d5af34.sock"}
[12:32:36.720] Spawned 55254
[12:32:36.857] > local-server> Spawned ssh: 55255
[12:32:36.859] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[12:32:37.310] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:p54s+PyGcTyh9ZqiDWUmdR91dELCf6O0wqxiP5ffX08
[12:32:37.873] Got askpass request: {"request":"root@192.34.56.10's password:"}
[12:32:37.873] Showing password prompt
[12:32:37.874] Listening for interwindow password on /var/folders/tr/67t1nysj0l73x554k1x2lpgw0000gn/T/vscode-ssh-askpass-c1a65cf71d27e59f4c9669a1a780f25f9b271e6a.sock
[12:32:37.874] Writing password prompt to globalState
[12:32:43.830] Got password response
[12:32:43.830] Interactor gave response: *************
[12:32:43.831] Cleaning up other-window auth server
[12:32:43.957] stderr> Authenticated to 192.34.56.10 ([192.34.56.10]:22).
[12:32:44.303] > Last failed login: Fri Dec  4 20:27:48 UTC 2020 from 160.155.113.22 on ssh:notty
> There was 1 failed login attempt since the last successful login.
[12:32:44.382] > ready: e00a48fadb53
[12:32:44.460] > Linux 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020
[12:32:44.460] Platform: linux
[12:32:44.562] > e00a48fadb53: running
[12:32:44.595] > Acquiring lock on /root/.vscode-server-exploration/bin/25a4ee40993f43df9229edc552bd3018c086569d/vscode-remote-lock.root.25a4ee40993f43df9229edc552bd3018c086569d
[12:32:44.599] > Found existing installation at /root/.vscode-server-exploration/bin/25a4ee40993f43df9229edc552bd3018c086569d...
> Checking /root/.vscode-server-exploration/.25a4ee40993f43df9229edc552bd3018c086569d.log and /root/.vscode-server-exploration/.25a4ee40993f43df9229edc552bd3018c086569d.pid for a running server
[12:32:44.600] > Looking for server with pid: 8930
[12:32:44.645] > Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[12:32:44.645] > Checking server status on port 38775 with curl
[12:32:44.651] > e00a48fadb53: start
> sshAuthSock====
> webUiAccessToken====
> listeningOn==38775==
> osReleaseId==centos==
> arch==x86_64==
> tmpDir==/run/user/0==
[12:32:44.672] > platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> e00a48fadb53: end
[12:32:44.672] Received install output: 
sshAuthSock====
webUiAccessToken====
listeningOn==38775==
osReleaseId==centos==
arch==x86_64==
tmpDir==/run/user/0==platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[12:32:44.673] Remote server is listening on 38775
[12:32:44.674] Parsed server configuration: {"remoteListeningOn":{"port":38775},"osReleaseId":"centos","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/0","platform":"linux"}
[12:32:44.675] Persisting server connection details to /Users/demohan/Library/Application Support/Code - Exploration/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-192.34.56.10-25a4ee40993f43df9229edc552bd3018c086569d-0.58.0/data.json
[12:32:44.677] Starting forwarding server. localPort 51003 -> socksPort 50999 -> remotePort 38775
[12:32:44.677] Forwarding server listening on 51003
[12:32:44.678] Waiting for ssh tunnel to be ready
[12:32:44.678] [Forwarding server 51003] Got connection 0
[12:32:44.679] Tunneled 38775 to local port 51003
[12:32:44.680] Resolved "ssh-remote+192.34.56.10" to "127.0.0.1:51003"
[12:32:44.692] ------




[12:32:44.787] [Forwarding server 51003] Got connection 1
[12:32:44.787] [Forwarding server 51003] Got connection 2
```

**Comment by deepak1556** [comment]
@roblourens how do I further investigate which module is causing the trouble ?

**Comment by deepak1556** [comment]
Looks like CentOS 7 can support a maximum of `GLIBCXX_3.4.19` while the new builds require `GLIBCXX_3.4.21` for some modules. I was able to go back to gcc-5 on ubuntu-18.04 build machine, going down to `gcc-4.9` might not be possible. Another option is to build our server bits on ubuntu-16.04 while desktop bits on ubuntu-18.04

**Comment by Chenghao-Wu** [comment]
Thanks a lot for all your testing. I am now using the stable version and I can use the remote extension to connect any server I have. But it is a bit slow since it is x86 based.

Hope it could be solved on the exploration version soon!

**Comment by roblourens** [comment]
@deepak are you saying that CentOS 7 has newer glibc available but it can't be used for some reason?

**Comment by markrosoftuk** [comment]
Can confirm my CentOS 7 only goes up to GLIBCXX_3.4.19

Should be possible to build and install a newer GCC from source for CentOS 7. I'm going to give that a try.

**Comment by deepak1556** [comment]
> are you saying that CentOS 7 has newer glibc available but it can't be used for some reason?

no the opposite, default glibc support is old.

I have a working solution using gcc-4.8 with ubuntu-18.04 build image and that should keep these distros supported. But moving forward when can no longer build with gcc-4.8 (which will happen when we jump to node14), we should deprecate support.

**Comment by Chenghao-Wu** [comment]
Hi guys, Thank you a lot. I updated the exploration version and the remote works now!
Thanks a lot!

**Comment by markrosoftuk** [comment]
Thank you very much, working nicely for me now too. Great to be able to work with the speed of the exploration version on this m1 mac.

**Comment by deepak1556** [comment]
Thanks for confirming!
