### ISSUE TITLE
Method invocation failed because [System.String] does not contain a method named 'AddSeconds'. 

### ISSUE THREAD

**Issue by williamlagos** [microsoft/vscode-remote-release#4166]
- VSCode Version: 1.51.1
- Local OS Version: Ubuntu 20.04.1 LTS
- Remote OS Version: Windows Server 2016 Standard Version 1607 (OS Build 14393.3025)
- Remote Extension/Connection Type: SSH Nightly (using OpenSSH-Win64), already tested with stable channel

Steps to Reproduce:

1. Set settings: remote.SSH.localServerDownload: false, remote.SSH.useLocalServer: false, and "remote.SSH.remotePlatform": { "<hostname>": "windows" }
2. Add SSH configuration for connecting the host (user and hostname) on ~/.ssh/config on Ubuntu host (This Windows Server 2016 is forwarded by a SSH tunnel to 127.0.0.1:2222 to my machine)
3. Then try to connect, the vscode-server installs itself, but generates this error:

[10:24:03.396] Log Level: 2
[10:24:03.398] remote-ssh-nightly@2020.11.38340
[10:24:03.398] linux x64
[10:24:03.400] SSH Resolver called for "ssh-remote+forward-cas", attempt 1
[10:24:03.400] "remote.SSH.useLocalServer": false
[10:24:03.400] "remote.SSH.showLoginTerminal": false
[10:24:03.400] "remote.SSH.remotePlatform": {"xpad-tunnel":"linux"}
[10:24:03.401] "remote.SSH.sshPath": undefined
[10:24:03.401] "remote.SSH.sshConfigurationFile": undefined
[10:24:03.401] "remote.SSH.useFlock": true
[10:24:03.401] "remote.SSH.lockfilesInTmp": false
[10:24:03.401] "remote.SSH.localServerDownload": off
[10:24:03.401] "remote.SSH.remoteServerListenOnSocket": false
[10:24:03.401] "remote.SSH.showLoginTerminal": false
[10:24:03.401] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[10:24:03.402] SSH Resolver called for host: forward-cas
[10:24:03.402] Setting up SSH remote "forward-cas"
[10:24:03.408] Using commit id "e5a624b788d92b8d34d1392e4c4d9789406efe8f" and quality "stable" for server
[10:24:03.411] Install and start server if needed
[10:24:05.023] Checking ssh with "ssh -V"
[10:24:05.037] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020

[10:24:05.039] Remote command length: 7465/8192 characters
[10:24:05.041] Running script with connection command: ssh -T -D 34281 -o ConnectTimeout=15 forward-cas powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -Command "powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -EncodedCommand \$([Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('---omit base64 coding for better reading---')))))"  # RemoteSSHConfigurationScript
[10:24:06.718] > c4cd5140f60d: running
[10:24:06.718] Got some output, clearing connection timeout
[10:24:07.250] > Acquiring lock on C:\Users\Administrator\.vscode-server\bin\e5a624b788d92b8d34d1392e4c4d9789406efe8f\vscode-remote-lock.e5a624b788d92b8d34d1392e4c4d9789406efe8f
[10:24:07.259] > Looking for existing server in C:\Users\Administrator\.vscode-server\bin\e5a624b788d92b8d34d1392e4c4d9789406efe8f
[10:24:07.266] > Found installed server
[10:24:07.283] > Starting server: & 'C:\Users\Administrator\.vscode-server\bin\e5a624b788d92b8d34d1392e4c4d9789406efe8f\server.cmd' --start-server --host=127.0.0.1 --enable-remote-auto-shutdown --port=0   *> 'C:\Users\Administrator\.vscode-server\.e5a624b788d92b8d34d1392e4c4d9789406efe8f.log'
[10:24:07.353] > Server failed to start. - Method invocation failed because [System.String] does not contain a method named 'AddSeconds'.
[10:24:07.439] > c4cd5140f60d: start
[10:24:07.449] > sshAuthSock====
[10:24:07.468] > listeningOn====
> osReleaseId==windows==
> osVersion==10.0.14393==
> arch==x64==
> platform==windows==
> unpackResult====
> didLocalDownload==False==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==34==
> c4cd5140f60d: end
> Install script is 7508, watching sshd parent 6484
[10:24:07.469] Received install output: 
sshAuthSock====
listeningOn====
osReleaseId==windows==
osVersion==10.0.14393==
arch==x64==
platform==windows==
unpackResult====
didLocalDownload==False==
downloadTime====
installTime====
extInstallTime====
serverStartTime==34==

[10:24:07.471] Failed to parse remote port from server output
[10:24:07.504] Resolver error: Error: 
	at Function.Create (/home/william/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.38340/out/extension.js:1:95502)
	at Object.t.handleInstallOutput (/home/william/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.38340/out/extension.js:1:92151)
	at I (/home/william/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.38340/out/extension.js:127:107038)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /home/william/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.38340/out/extension.js:127:104953
	at async Object.t.withShowDetailsEvent (/home/william/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.38340/out/extension.js:127:110290)
	at async Object.t.resolve (/home/william/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.38340/out/extension.js:127:108354)
	at async /home/william/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.38340/out/extension.js:127:129588
[10:24:07.516] ------

But when I try to run manually the vscode-server, or check the logs on Windows Server, it runs succesfully:

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*

IP Address: 192.168.122.250
Extension host agent listening on 55152

[10:24:07] Extension host agent started.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/4140#issuecomment-742981004
