### ISSUE TITLE
Remote connection to windows machine with "Method invocation failed because [System.String]" issue

### ISSUE THREAD

**Issue by Yuejiang-li** [microsoft/vscode-remote-release#4167]
When I use vscode on a windows computer to connect the other windows machine, it does not work. But I can use PowerShell to ping the server windows machine. Besides, It works when I try other windows server machine. I am wondering how to solve this problem.

Here is the detailed information
*client computer* and *server computer*
```
vscode=1.51.1
windows=windows10-1909
```

*Log*
```
[16:38:10.014] Log Level: 2
[16:38:10.021] remote-ssh@0.61.0
[16:38:10.022] win32 x64
[16:38:10.023] SSH Resolver called for "ssh-remote+166.111.74.161", attempt 1
[16:38:10.023] "remote.SSH.useLocalServer": false
[16:38:10.024] "remote.SSH.showLoginTerminal": true
[16:38:10.024] "remote.SSH.remotePlatform": {"ThuServer1":"linux","thusrv2":"linux","thusrv1":"linux","thusrv3":"linux","166.111.74.161":"windows","166.111.74.166":"windows"}
[16:38:10.024] "remote.SSH.sshPath": undefined
[16:38:10.024] "remote.SSH.sshConfigurationFile": C:\Users\yueji\.ssh\config
[16:38:10.024] "remote.SSH.useFlock": true
[16:38:10.024] "remote.SSH.lockfilesInTmp": false
[16:38:10.025] "remote.SSH.localServerDownload": auto
[16:38:10.025] "remote.SSH.remoteServerListenOnSocket": false
[16:38:10.025] "remote.SSH.showLoginTerminal": true
[16:38:10.025] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[16:38:10.025] SSH Resolver called for host: 166.111.74.161
[16:38:10.025] Setting up SSH remote "166.111.74.161"
[16:38:10.048] Using commit id "e5a624b788d92b8d34d1392e4c4d9789406efe8f" and quality "stable" for server
[16:38:10.052] Install and start server if needed
[16:38:10.055] Checking ssh with "ssh -V"
[16:38:10.115] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[16:38:10.119] Remote command length: 7252/8192 characters
[16:38:10.121] Using SSH config file "C:\Users\yueji\.ssh\config"
[16:38:10.122] Running script with connection command: ssh -T -D 63807 -F "C:\Users\yueji\.ssh\config" "166.111.74.161" powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -Command "powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -EncodedCommand $([Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('CiR1dWlkPSIyNjNkZTljNjk1NWYiCiIke3V1aWR9OiBydW5uaW5nIgokUHJvZ3Jlc3NQcmVmZXJlbmNlPSdTaWxlbnRseUNvbnRpbnVlJwokbj0nZTVhNjI0Yjc4OGQ5MmI4ZDM0ZDEzOTJlNGM0ZDk3ODk0MDZlZmU4ZicKJHA9JGVudjpQUk9DRVNTT1JfQVJDSElURUNUVVJFCiRhcmNoPWlmICgoJHAgLWVxICdBTUQ2NCcpIC1vciAoJHAgLWVxICdJQTY0JykpIHsgJ3g2NCcgfSBlbHNlIHsgJ2lhMzInIH0KJG89KEpvaW4tUGF0aCAoUmVzb2x2ZS1QYXRoIH4pICcudnNjb2RlLXNlcnZlcicpCiRlbnY6VlNDT0RFX0FHRU5UX0ZPTERFUj0kbwokbG9nPSIkb1wuJG4ubG9nIgokc0Rpcj0iJG9cYmluXCRuIgokcD0nc3RhYmxlJwokcT0iIgokZXh0cz0iIgokZz0kVHJ1ZQokaD0kRmFsc2UKJGdsb2JhbDpyID0gJEZhbHNlCiRnbG9iYWw6cyA9ICcnCiRnbG9iYWw6aiA9ICcnCiRnbG9iYWw6ayA9ICcnCiRnbG9iYWw6bCA9ICcnCiRnbG9iYWw6bSA9ICcnCmZ1bmN0aW9uIGRldGFpbHMgewoibGlzdGVuaW5nT249PSRwb3J0PT0iCiJvc1JlbGVhc2VJZD09d2luZG93cz09Igoib3NWZXJzaW9uPT0kYWg9PSIKImFyY2g9PSRhcmNoPT0iCiJwbGF0Zm9ybT09d2luZG93cz09Igoicz09JHM9PSIKImRpZExvY2FsRG93bmxvYWQ9PSRyPT0iCiJkb3dubG9hZFRpbWU9PSRqPT0iCiJpbnN0YWxsVGltZT09JGs9PSIKImV4dEluc3RhbGxUaW1lPT0kbD09Igoic2VydmVyU3RhcnRUaW1lPT0kbT09Igp9CmZ1bmN0aW9uIGkgewpyZXR1cm4gW3N5c3RlbS5kaWFnbm9zdGljcy5zdG9wd2F0Y2hdOjpTdGFydE5ldygpOwp9CmZ1bmN0aW9uIHEoJGNvZGUpIHsKIiR7dXVpZH06IHN0YXJ0IgoiZXhpdENvZGU9PSRjb2RlPT0iCmRldGFpbHMKIiR7dXVpZH06IGVuZCIKfQpmdW5jdGlvbiBhIHsKJHQ9JFBJRAp3aGlsZSAoJFRydWUpIHsKJHU9KGdjaW0gd2luMzJfcHJvY2VzcyB8ID8gcHJvY2Vzc2lkIC1lcSAkdCkucGFyZW50cHJvY2Vzc2lkCmlmICghJHUpIHsKIm5vIHNzaGQgcGFyZW50IHByb2MiCmV4aXQgMAp9CmlmICgoZ3BzIC1JZCAkdSkuTmFtZSAtZXEgJ3NzaGQnKSB7CnJldHVybiAkdQp9CiR0PSR1Cn0KfQpmdW5jdGlvbiBiIHsKaWYgKCR2KSB7CmlmICghKGdwcyAtSWQgJHYpKSB7CiJzZXJ2ZXIgZGllZCwgZXhpdCIKZXhpdCAwCn0KfSBlbHNlIHsKaWYgKCEoZ3BzIC1JZCAkc3NoZFBJRCkpIHsKInNzaGQgcGFyZW50IGRpZWQsIGV4aXQiCmV4aXQgMAp9Cn0KfQpmdW5jdGlvbiBjIHsKJHM9aQoiRG93bmxvYWRpbmcgc2VydmVyIgoiJHt1dWlkfSUlMSUlIgokdz0iIgokeD1pZiAoJGFyY2ggLWVxICd4NjQnKSB7ICItJGFyY2giIH0gZWxzZSB7ICIiIH0KJHk9InNlcnZlci13aW4zMiR4IiArICR3CiRzcGxhdD1AewpVcmk9Imh0dHBzOi8vdXBkYXRlLmNvZGUudmlzdWFsc3R1ZGlvLmNvbS9jb21taXQ6JG4vJHkvJHAiClRpbWVvdXRTZWM9MjAKT3V0RmlsZT0idnNjb2RlLXNlcnZlci56aXAiClVzZUJhc2ljUGFyc2luZz0kVHJ1ZQp9CltOZXQuU2VydmljZVBvaW50TWFuYWdlcl06OlNlY3VyaXR5UHJvdG9jb2wgPSAnVGxzMTInCmlybSBAc3BsYXQKJHMuU3RvcCgpCiRnbG9iYWw6aiA9ICRzLkVsYXBzZWRNaWxsaXNlY29uZHMKfQpmdW5jdGlvbiBkIHsKJGdsb2JhbDpzPSdzdWNjZXNzJwokcz1pCnRyeSB7CiR6PVtTeXN0ZW0uSU8uUGF0aF06OkdldFJhbmRvbUZpbGVOYW1lKCkKJGFhPSIkZW52OlRFTVBcJHoiCiJFeHBhbmRpbmcgc2VydmVyIGludG8gJGFhIgoiJHt1dWlkfSUlMiUlIgpFeHBhbmQtQXJjaGl2ZSAidnNjb2RlLXNlcnZlci56aXAiIC1EZXN0aW5hdGlvblBhdGggIiRhYSIKbXYgIiRhYVx2c2NvZGUtKlwqIiAtRGVzdGluYXRpb24gLgokcy5TdG9wKCkKJGdsb2JhbDprID0gJHMuRWxhcHNlZE1pbGxpc2Vjb25kcwp9IGNhdGNoIHsKJGdsb2JhbDpzPSdlcnJvcicKIkZhaWxlZCB0byB1bnppcCBzZXJ2ZXIuIC0gJCgkXy5Ub1N0cmluZygpKSIKZiAzNwpkCn0KaWYoIShUZXN0LVBhdGggIiRzRGlyXHNlcnZlci5jbWQiKSkgewokZ2xvYmFsOnM9J21pc3NpbmdGaWxlcycKIkRvd25sb2FkZWQgc2VydmVyIGlzIGluY29tcGxldGUuIgpmIDM3CmQKfQp9CmZ1bmN0aW9uIFN0YXJ0U2VydmVyIHsKJHM9aQppZihUZXN0LVBhdGggJGxvZykgewpkZWwgJGxvZwp9CiRhYj0kc0RpciAtcmVwbGFjZSAnICcsICdgICcKJGFyZ3M9Ii0taG9zdD0xMjcuMC4wLjEgLS1lbmFibGUtcmVtb3RlLWF1dG8tc2h1dGRvd24gLS1wb3J0PTAgJHEgKj4gJyRsb2cnIgokc3BsYXQ9QHsKRmlsZVBhdGggPSAicG93ZXJzaGVsbC5leGUiCldpbmRvd1N0eWxlID0gImhpZGRlbiIKQXJndW1lbnRMaXN0ID0gQCgKIi1FeGVjdXRpb25Qb2xpY3kiLCAiVW5yZXN0cmljdGVkIiwgIi1Ob0xvZ28iLCAiLU5vUHJvZmlsZSIsICItTm9uSW50ZXJhY3RpdmUiLCAiLWMiLCAiJGFiXHNlcnZlci5jbWQgJGFyZ3MiCikKUGFzc1RocnUgPSAkVHJ1ZQp9CiJTdGFydGluZyBzZXJ2ZXI6ICYgJyRzRGlyXHNlcnZlci5jbWQnICRhcmdzIgokdj0oc3RhcnQgQHNwbGF0KS5JRAokcy5TdG9wKCkKJGdsb2JhbDptID0gJHMuRWxhcHNlZE1pbGxpc2Vjb25kcwp9CmZ1bmN0aW9uIGUgewokZ2xvYmFsOnI9JFRydWUKIlRyaWdnZXIgbG9jYWwgc2VydmVyIGRvd25sb2FkIgoiJHt1dWlkfTp0cmlnZ2VyX3NlcnZlcl9kb3dubG9hZCIKInBsYXRmb3JtPT13aW5kb3dzPT0iCiJ2c2NvZGVBcmNoPT0kYXJjaD09IgoiZGVzdEZvbGRlcj09JHNEaXI9PSIKIiR7dXVpZH06dHJpZ2dlcl9zZXJ2ZXJfZG93bmxvYWRfZW5kIgoiV2FpdGluZyBmb3IgY2xpZW50IHRvIHRyYW5zZmVyIHNlcnZlciBhcmNoaXZlLi4uIgoiV2FpdGluZyBmb3IgJHNEaXJcdnNjb2RlLXNjcC1kb25lLmZsYWcgYW5kIHZzY29kZS1zZXJ2ZXIuemlwIHRvIGV4aXN0Igp3aGlsZSgkVHJ1ZSkgewppZihUZXN0LVBhdGggIiRzRGlyXHZzY29kZS1zY3AtZG9uZS5mbGFnIikgewppZighKFRlc3QtUGF0aCAiJHNEaXJcdnNjb2RlLXNlcnZlci56aXAiKSkgewoiVHJhbnNmZXIgZmFpbGVkIgpxIDMxCn0KIlRyYW5zZmVyIGNvbXBsZXRlIgpkZWwgJHNEaXJcdnNjb2RlLXNjcC1kb25lLmZsYWcKYnJlYWsKfSBlbHNlIHsKU3RhcnQtU2xlZXAgLVNlY29uZHMgMwpiCn0KfQp9CmZ1bmN0aW9uIGYoJGNvZGUpIHsKaWYgKCRyKSB7CiJBbHJlYWR5IGF0dGVtcHRlZCBsb2NhbCBkb3dubG9hZCwgZmFpbGluZyIKcSAkY29kZQp9IGVsc2VpZigkZykgewplCn0gZWxzZSB7CnEgJGNvZGUKfQp9CiRzc2hkUElEPWEKaWYoIShUZXN0LVBhdGggJHNEaXIpKSB7CiRtPSJDb3VsZCBub3QgY3JlYXRlIHNlcnZlciBkaXJlY3RvcnkiCnRyeSB7CiRudWxsPW5pIC1pdCBkICRzRGlyIC1mIC1lYSBzaQp9IGNhdGNoIHsKIiRtLiAtICQoJF8uVG9TdHJpbmcoKSkiCnJldHVybgp9CmlmKCEoVGVzdC1QYXRoICRzRGlyKSkgewoiJG0iCnJldHVybgp9Cn0KY2QgJHNEaXIKJGFjPShKb2luLVBhdGggIiRzRGlyIiAidnNjb2RlLXJlbW90ZS1sb2NrLiRuIikKdHJ5IHsKJG51bGw9bmkgJGFjIC1pdCBmIC1lYSBzaQp9IGNhdGNoIHsKIkNvdWxkIG5vdCBjcmVhdGUgc2VydmVyIGxvY2sgZmlsZS4gLSAkKCRfLlRvU3RyaW5nKCkpIgpyZXR1cm4KfQp0cnkgewoiQWNxdWlyaW5nIGxvY2sgb24gJGFjIgokZmlsZT1bU3lzdGVtLmlvLkZpbGVdOjpPcGVuKCRhYywgJ09wZW4nLCAnUmVhZCcsICdOb25lJykKfSBjYXRjaCB7CiJJbnN0YWxsIGFscmVhZHkgaW4gcHJvZ3Jlc3MuLi4gLSAkKCRfLlRvU3RyaW5nKCkpIgpxIDI0Cn0KdHJ5IHsKIkxvb2tpbmcgZm9yIGV4aXN0aW5nIHNlcnZlciBpbiAkc0RpciIKaWYoVGVzdC1QYXRoICIkc0RpclxzZXJ2ZXIuY21kIikgewoiRm91bmQgaW5zdGFsbGVkIHNlcnZlciIKfSBlbHNlIHsKaWYgKCRoKSB7CmUKfSBlbHNlIHsKdHJ5IHsgYyB9IGNhdGNoIHsKIkRvd25sb2FkIGZhaWxlZC4gLSAkKCRfLlRvU3RyaW5nKCkpIgpmIDI1Cn0KfQpkCn0KaWYgKCRleHRzIC1uZSAiIikgewokcz1pCiYgIiRzRGlyXHNlcnZlci5jbWQiICRxICRleHRzCiRzLlN0b3AoKQokZ2xvYmFsOmwgPSAkcy5FbGFwc2VkTWlsbGlzZWNvbmRzCn0KaWYoIShHZXQtUHJvY2VzcyBub2RlIC1FcnJvckFjdGlvbiBTaWxlbnRseUNvbnRpbnVlIHwgV2hlcmUtT2JqZWN0IFBhdGggLW1hdGNoICRuKSkgewpTdGFydFNlcnZlcgp9IGVsc2UgewoiU2VydmVyIHdpdGggJG4gaXMgYWxyZWFkeSBydW5uaW5nLiIKfQokYWY9QHsKUGF0aCA9ICRsb2cKUGF0dGVybiA9ICJFeHRlbnNpb24gaG9zdCBhZ2VudCBsaXN0ZW5pbmcgb24gKFxkKykiCn0KJGFlPUB7ClBhdGggPSAkbG9nClBhdHRlcm4gPSAiISEhISBTZXJ2ZXIgdGVybWluYXRlZCBkdWUgdG8gcHJlc2VuY2Ugb2YgQ1ZFLTIwMjAtMTQxNiAhISEhIgp9CiRhZD0oRGF0ZSkuQWRkU2Vjb25kcyg0KQp3aGlsZSAoKERhdGUpIC1sdCAkYWQpIHsKaWYoVGVzdC1QYXRoICRsb2cpIHsKJGFnPShzbHMgQGFmKS5NYXRjaGVzLkdyb3VwcwppZigkYWcpIHsKJHBvcnQ9JGFnWzFdLlZhbHVlCmJyZWFrCn0KJGZhaWxlZD0oc2xzIEBhZSkuTWF0Y2hlcy5Hcm91cHMKaWYoJGZhaWxlZCkgewoiU2VydmVyIGRpZCBub3Qgc3RhcnQgc3VjY2Vzc2Z1bGx5LiBGdWxsIHNlcnZlciBsb2cgYXQgJGxvZyA+Pj4iCmNhdCAkbG9nCiI8PDwgRW5kIG9mIHNlcnZlciBsb2ciCnEgMzYKfQp9CnNsZWVwIC1NaWxsaXNlY29uZHMgMjAwCn0KaWYgKCEkcG9ydCkgewoiU2VydmVyIGRpZCBub3Qgc3RhcnQgc3VjY2Vzc2Z1bGx5LiBGdWxsIHNlcnZlciBsb2cgYXQgJGxvZyA+Pj4iCmNhdCAkbG9nCiI8PDwgRW5kIG9mIHNlcnZlciBsb2ciCnEgMzIKfQp9IGNhdGNoIHsKIlNlcnZlciBmYWlsZWQgdG8gc3RhcnQuIC0gJCgkXy5Ub1N0cmluZygpKSIKfSBmaW5hbGx5IHsKJGZpbGUuQ2xvc2UoKQp9CnRyeSB7CiRhaD0oZ2NpbSBXaW4zMl9PcGVyYXRpbmdTeXN0ZW0pLlZlcnNpb24KfSBjYXRjaCB7CiJGYWlsZWQgdG8gZmluZCBXaW5kb3dzIHZlcnNpb24gLSAkKCRfLlRvU3RyaW5nKCkpIgokYWg9InVua25vd24iCn0KIiR7dXVpZH06IHN0YXJ0Igoic3NoQXV0aFNvY2s9PSRlbnY6U1NIX0FVVEhfU09DSz09IgpkZXRhaWxzCiIke3V1aWR9OiBlbmQiCiJJbnN0YWxsIHNjcmlwdCBpcyAkcGlkLCB3YXRjaGluZyBzc2hkIHBhcmVudCAkc3NoZFBJRCIKd2hpbGUgKCRUcnVlKSB7CmIKc2xlZXAgMzAKfQo=')))))"  # RemoteSSHConfigurationScript
[16:38:10.122] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[16:38:10.285] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\WINDOWS\System32\cmd.exe
[16:38:10.285] Got some output, clearing connection timeout
[16:38:10.308] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[16:38:10.323] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[16:38:10.356] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[16:38:10.367] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[16:38:10.681] > xzzz@166.111.74.161's password: 
[16:38:15.153] > 
> 
[16:38:15.489] > 263de9c6955f: running
[16:38:15.515] > 
> 
[16:38:15.736] > Acquiring lock on C:\Users\xzzz\.vscode-server\bin\e5a624b788d92b8d34d1392e4c4d9789406efe8f\vscode-remote-
> lock.e5a624b788d92b8d34d1392e4c4d9789406efe8f
[16:38:15.831] > 
> Looking for existing server in C:\Users\xzzz\.vscode-server\bin\e5a624b788d92b8d34d1392e4c4d9789406efe8f  
> Found installed server
> Starting server: & 'C:\Users\xzzz\.vscode-server\bin\e5a624b788d92b8d34d1392e4c4d9789406efe8f\server.cmd' 
> --host=127.0.0.1 --enable-remote-auto-shutdown --port=0  *> 'C:\Users\xzzz\.vscode-server\.e5a624b788d92b8
> d34d1392e4c4d9789406efe8f.log'
> 
[16:38:15.854] > Server failed to start. - Method invocation failed because [System.String] does not contain a method named
>  'AddSeconds'.
[16:38:16.068] > 
> 263de9c6955f: start      
> sshAuthSock====
> listeningOn====
> osReleaseId==windows==   
> osVersion==10.0.18363==  
> arch==x64==
> platform==windows==      
> s====
> didLocalDownload==False==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==28==
> 263de9c6955f: end
[16:38:16.068] Received install output:       
sshAuthSock====
listeningOn====
osReleaseId==windows==   
osVersion==10.0.18363==  
arch==x64==
platform==windows==      
s====
didLocalDownload==False==
downloadTime====
installTime====
extInstallTime====
serverStartTime==28==

[16:38:16.070] Failed to parse remote port from server output
[16:38:16.089] Resolver error: Error: 
	at Function.Create (c:\Users\yueji\.vscode\extensions\ms-vscode-remote.remote-ssh-0.61.0\out\extension.js:1:82322)
	at Object.t.handleInstallOutput (c:\Users\yueji\.vscode\extensions\ms-vscode-remote.remote-ssh-0.61.0\out\extension.js:1:78935)
	at I (c:\Users\yueji\.vscode\extensions\ms-vscode-remote.remote-ssh-0.61.0\out\extension.js:127:107056)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\yueji\.vscode\extensions\ms-vscode-remote.remote-ssh-0.61.0\out\extension.js:127:104971
	at async Object.t.withShowDetailsEvent (c:\Users\yueji\.vscode\extensions\ms-vscode-remote.remote-ssh-0.61.0\out\extension.js:127:110308)
	at async Object.t.resolve (c:\Users\yueji\.vscode\extensions\ms-vscode-remote.remote-ssh-0.61.0\out\extension.js:127:108372)
	at async c:\Users\yueji\.vscode\extensions\ms-vscode-remote.remote-ssh-0.61.0\out\extension.js:127:129627
[16:38:16.094] ------




[16:38:16.151] > 
> Install script is 14664, watching sshd parent 13488
> 

```

**Comment by Shahmeerm** [comment]
I'm experiencing exactly the same issue. Unable to connect to my Windows Machine.

```
[18:22:58.276] Failed to parse remote port from server output
[18:22:58.280] Resolver error: Error: 
	at Function.Create (/Users/mahers/.vscode/extensions/ms-vscode-remote.remote-ssh-0.61.0/out/extension.js:1:82322)
	at Object.t.handleInstallOutput (/Users/mahers/.vscode/extensions/ms-vscode-remote.remote-ssh-0.61.0/out/extension.js:1:78935)
	at I (/Users/mahers/.vscode/extensions/ms-vscode-remote.remote-ssh-0.61.0/out/extension.js:127:107056)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /Users/mahers/.vscode/extensions/ms-vscode-remote.remote-ssh-0.61.0/out/extension.js:127:104971
	at async Object.t.withShowDetailsEvent (/Users/mahers/.vscode/extensions/ms-vscode-remote.remote-ssh-0.61.0/out/extension.js:127:110308)
	at async Object.t.resolve (/Users/mahers/.vscode/extensions/ms-vscode-remote.remote-ssh-0.61.0/out/extension.js:127:108372)
	at async /Users/mahers/.vscode/extensions/ms-vscode-remote.remote-ssh-0.61.0/out/extension.js:127:129627
[18:22:58.283] ------
```

**Comment by ashirsch** [comment]
Check out #4140 - I had same issue, turned out I had a different date.exe on my PATH (one that came packaged with cygwin) that gets confused with the Date cmdlet. For now renaming the bad date.exe (or removing it from PATH) fixed my issue.

**Comment by youyuanwu** [comment]
> Check out #4140 - I had same issue, turned out I had a different date.exe on my PATH (one that came packaged with cygwin) that gets confused with the Date cmdlet. For now renaming the bad date.exe (or removing it from PATH) fixed my issue.

I installed MinGit which has date.exe in path. removing it fixed the issue. It used to work fine without this fix. Maybe the new release has dependency on "date.exe" from powershell.

**Comment by Yuejiang-li** [comment]
Thanks a lot @ashirsch @youyuanwu . The problem is solved. The issue is also because of `date`, but my `date` is hiden in Anaconda's path...

I directly remove it. as @youyuanwu suggested, and not sure if this operation will affect the future usage to the Anaconda. Is there better solution so that the `date.exe` in my Anaconda path can be preserved?

*BTW, the Issue's name is changed so that it can be easily to find for those with the similar problem.*

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/4140
