### ISSUE TITLE
Remote SSH Nightly seems to had been broken several days ago

### ISSUE THREAD

**Issue by sergei3000** [microsoft/vscode-remote-release#4177]
- VSCode Version: 1.51.1
- Local OS Version: Ubuntu 18.04.3 LTS
- Remote OS Version: Red Hat Enterprise Linux Server 7.4 (Maipo)
- Remote Extension/Connection Type: SSH (Nightly)

Steps to Reproduce:

1. Use Remote - SSH (Nightly) extension.
2. Try to connect to a remote server via the button in Remote Explorer menu.

Does this issue occur when you try this locally?: NA
Does this issue occur when you try this locally and all extensions are disabled?: NA

-----

So what's going on is I'm trying to connect to remote servers with `SSH - Remote Nightl`y (I'm using `Nightly` because of #3365). This used to work but started failing some days ago. The interesting part is that if after trying to install remote `.vscode-server` with the `Nightly` version (which fails) I switch to the stable version of `SSH - Remote`, everything starts working and I can connect to the remote server again. I'm guessing Nightly succeeds in delivering installation files to my remote server but fails to install them.
This behavior was reproduced by me on other remote servers. It was also confirmed by one of my colleagues who's working with the same remote servers but from a Windows local host.
I really hope this will be noticed and the next stable version won't come out broken.

The log from `Remote - SSH (Nightly)` Output:
```
[13:11:19.137] Log Level: 2
[13:11:19.138] remote-ssh-nightly@2020.11.38340
[13:11:19.138] linux x64
[13:11:19.140] SSH Resolver called for "ssh-remote+appnode02", attempt 1
[13:11:19.141] "remote.SSH.useLocalServer": true
[13:11:19.141] "remote.SSH.sshPath": undefined
[13:11:19.141] "remote.SSH.sshConfigurationFile": undefined
[13:11:19.141] "remote.SSH.useFlock": true
[13:11:19.142] "remote.SSH.lockfilesInTmp": false
[13:11:19.142] "remote.SSH.localServerDownload": auto
[13:11:19.142] "remote.SSH.remoteServerListenOnSocket": false
[13:11:19.142] "remote.SSH.showLoginTerminal": false
[13:11:19.142] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[13:11:19.143] SSH Resolver called for host: appnode02
[13:11:19.149] Setting up SSH remote "appnode02"
[13:11:19.153] Acquiring local install lock: /tmp/vscode-remote-ssh-appnode02-install.lock
[13:11:19.157] Looking for existing server data file at /home/X5/serzakharov/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh-nightly/vscode-ssh-host-appnode02-e5a624b788d92b8d34d1392e4c4d9789406efe8f-2020.11.38340/data.json
[13:11:19.158] Using commit id "e5a624b788d92b8d34d1392e4c4d9789406efe8f" and quality "stable" for server
[13:11:19.161] Install and start server if needed
[13:11:19.163] Checking ssh with "ssh -V"
[13:11:19.203] > OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017

[13:11:19.214] askpass server listening on /run/user/10005/vscode-ssh-askpass-7107c00d190fc12a7bacaf3b75c56bada0c8f125.sock
[13:11:19.214] Spawning local server with {"ipcHandlePath":"/run/user/10005/vscode-ssh-askpass-4ded692db1cd77d245e8e722ab1ef907f49c3e03.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","41561","-o","ConnectTimeout=15","appnode02"],"dataFilePath":"/home/X5/serzakharov/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh-nightly/vscode-ssh-host-appnode02-e5a624b788d92b8d34d1392e4c4d9789406efe8f-2020.11.38340/data.json"}
[13:11:19.214] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/X5/serzakharov/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.38340/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/X5/serzakharov/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.38340/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/10005/vscode-ssh-askpass-7107c00d190fc12a7bacaf3b75c56bada0c8f125.sock"}
[13:11:19.232] Spawned 20991
[13:11:19.443] > local-server> Spawned ssh: 20999
[13:11:19.446] stderr> OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
[13:11:19.523] stderr> debug1: Server host key: ssh-rsa <host-key-was-here>
[13:11:19.614] stderr> Authenticated to <server-url-was-here> ([192.168.235.13]:22).
[13:11:20.160] > ready: df01b4744327
[13:11:20.169] > Linux 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017
[13:11:20.171] Platform: linux
[13:11:20.189] > df01b4744327: running
[13:11:20.283] > Acquiring lock on /home/local/X5/serzakharov/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/vscode-remote-lock.serzakharov.e5a624b788d92b8d34d1392e4c4d9789406efe8f
[13:11:20.296] > Installing to /home/local/X5/serzakharov/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f...
[13:11:20.301] > df01b4744327%%1%%
[13:11:20.375] > Downloading with wget
[13:11:22.664] > Download complete
[13:11:22.675] > df01b4744327%%2%%
> tar --version:
[13:11:22.741] > tar (GNU tar) 1.26
> Copyright (C) 2011 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[13:11:23.901] > Checking /home/local/X5/serzakharov/.vscode-server/.e5a624b788d92b8d34d1392e4c4d9789406efe8f.log and /home/local/X5/serzakharov/.vscode-server/.e5a624b788d92b8d34d1392e4c4d9789406efe8f.pid for a running server
[13:11:24.104] > Starting server with command... /home/local/X5/serzakharov/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/server.sh --start-server --host=127.0.0.1 --enable-remote-auto-shutdown --disable-telemetry --port=0 --install-extension ms-python.python --install-extension redhat.vscode-yaml --install-extension eamodio.gitlens --install-extension ms-python.vscode-pylance &> "/home/local/X5/serzakharov/.vscode-server/.e5a624b788d92b8d34d1392e4c4d9789406efe8f.log" < /dev/null
> printenv:
[13:11:24.117] >     LC_PAPER=ru_RU.UTF-8
>     MANPATH=:/opt/puppetlabs/puppet/share/man
>     LC_ADDRESS=ru_RU.UTF-8
>     XDG_SESSION_ID=157071
>     LC_MONETARY=ru_RU.UTF-8
>     HOSTNAME=mn-hdap02
>     SHELL=/bin/bash
>     HISTSIZE=100000
>     SSH_CLIENT=192.168.217.9 58084 22
>     CONDA_SHLVL=1
>     CONDA_PROMPT_MODIFIER=(base) 
>     LC_NUMERIC=ru_RU.UTF-8
>     QTDIR=/usr/lib64/qt-3.3
>     QTINC=/usr/lib64/qt-3.3/include
>     QT_GRAPHICSSYSTEM_CHECKED=1
>     USER=serzakharov
>     HISTFILESIZE=100000
>     LC_TELEPHONE=ru_RU.UTF-8
>     CONDA_EXE=/home/local/X5/serzakharov/miniconda3/bin/conda
>     VSCODE_AGENT_FOLDER=/home/local/X5/serzakharov/.vscode-server
>     _CE_CONDA=
>     PATH=/home/local/X5/serzakharov/miniconda3/bin:/home/local/X5/serzakharov/miniconda3/condabin:/home/local/X5/serzakharov/anaconda3/bin:/home/local/X5/serzakharov/anaconda3/bin:/home/local/X5/serzakharov/anaconda3/bin:/home/local/X5/serzakharov/.linuxbrew/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/home/local/X5/serzakharov/.local/bin:/home/local/X5/serzakharov/bin:/home/local/X5/serzakharov/.linuxbrew/bin
>     MAIL=/var/spool/mail/serzakharov
>     LC_IDENTIFICATION=ru_RU.UTF-8
>     CONDA_PREFIX=/home/local/X5/serzakharov/miniconda3
>     PWD=/home/local/X5/serzakharov
>     LANG=en_US.UTF-8
>     HADOOP_CONF_DIR=/etc/hadoop/conf
>     MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
>     LC_MEASUREMENT=ru_RU.UTF-8
>     LOADEDMODULES=
>     KRB5CCNAME=FILE:/tmp/krb5cc_2019866183
>     HISTCONTROL=ignoredups
>     _CE_M=
>     HOME=/home/local/X5/serzakharov
>     SHLVL=2
>     LOGNAME=serzakharov
>     CONDA_PYTHON_EXE=/home/local/X5/serzakharov/miniconda3/bin/python
>     QTLIB=/usr/lib64/qt-3.3/lib
>     SSH_CONNECTION=192.168.217.9 58084 192.168.235.13 22
>     MODULESHOME=/usr/share/Modules
>     LESSOPEN=||/usr/bin/lesspipe.sh %s
>     CONDA_DEFAULT_ENV=base
>     XDG_RUNTIME_DIR=/run/user/2019866183
>     LC_TIME=ru_RU.UTF-8
>     HISTTIMEFORMAT=%d.%m.%Y %H:%M:%S: 
>     LC_NAME=ru_RU.UTF-8
>     BASH_FUNC_module()=() {  eval `/usr/bin/modulecmd bash $*`
>     }
>     _=/usr/bin/printenv
>     OLDPWD=/home/local/X5/serzakharov/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f
[13:11:24.123] > Spawned remote server: 163316
[13:11:24.127] > Waiting for server log...
[13:11:24.340] > Waiting for server log...
[13:11:24.541] > Waiting for server log...
[13:11:24.750] > Waiting for server log...
[13:11:24.957] > Waiting for server log...
[13:11:25.169] > Waiting for server log...
[13:11:25.373] > Waiting for server log...
[13:11:25.584] > Waiting for server log...
[13:11:25.789] > Waiting for server log...
[13:11:26.004] > Waiting for server log...
[13:11:26.202] > Waiting for server log...
[13:11:26.411] > Waiting for server log...
[13:11:26.618] > Waiting for server log...
[13:11:26.825] > Waiting for server log...
[13:11:27.032] > Waiting for server log...
[13:11:27.237] > Waiting for server log...
[13:11:27.446] > Waiting for server log...
[13:11:27.659] > Waiting for server log...
[13:11:27.860] > Waiting for server log...
[13:11:28.069] > Waiting for server log...
[13:11:28.272] > Waiting for server log...
[13:11:28.480] > Waiting for server log...
[13:11:28.694] > Waiting for server log...
[13:11:28.894] > Waiting for server log...
[13:11:29.102] > Waiting for server log...
[13:11:29.308] > Waiting for server log...
[13:11:29.517] > Waiting for server log...
[13:11:29.725] > Waiting for server log...
[13:11:29.931] > Waiting for server log...
[13:11:30.136] > Waiting for server log...
[13:11:30.344] > Waiting for server log...
[13:11:30.552] > Waiting for server log...
[13:11:30.762] > Waiting for server log...
[13:11:30.969] > Waiting for server log...
[13:11:31.175] > Waiting for server log...
[13:11:31.382] > Waiting for server log...
[13:11:31.593] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[13:11:31.602] > Server did not start successfully. Full server log at /home/local/X5/serzakharov/.vscode-server/.e5a624b788d92b8d34d1392e4c4d9789406efe8f.log >>>
[13:11:31.602] > Ignoring option start-server: not supported for server.
> Installing extensions...
[13:11:31.603] > <<< End of server log
> df01b4744327: start
> exitCode==32==
> listeningOn====
> osReleaseId==rhel==
> arch==x86_64==
> tmpDir==/run/user/2019866183==
> platform==linux==
> unpackResult==success==
> didLocalDownload==0==
> downloadTime==2369==
> installTime==1204==
> extInstallTime====
> serverStartTime==7468==
> df01b4744327: end
[13:11:31.603] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==rhel==
arch==x86_64==
tmpDir==/run/user/2019866183==
platform==linux==
unpackResult==success==
didLocalDownload==0==
downloadTime==2369==
installTime==1204==
extInstallTime====
serverStartTime==7468==

[13:11:31.604] Terminating local server
[13:11:31.621] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (/home/X5/serzakharov/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.38340/out/extension.js:1:95433)
	at /home/X5/serzakharov/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.38340/out/extension.js:1:93549
	at Object.t.handleInstallOutput (/home/X5/serzakharov/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.38340/out/extension.js:1:94151)
	at Object.t.tryInstallWithLocalServer (/home/X5/serzakharov/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.38340/out/extension.js:127:102434)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /home/X5/serzakharov/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.38340/out/extension.js:127:104481
	at async Object.t.withShowDetailsEvent (/home/X5/serzakharov/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.38340/out/extension.js:127:110290)
	at async /home/X5/serzakharov/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.38340/out/extension.js:127:100987
	at async S (/home/X5/serzakharov/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.38340/out/extension.js:127:97777)
	at async Object.t.resolveWithLocalServer (/home/X5/serzakharov/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.38340/out/extension.js:127:100636)
	at async Object.t.resolve (/home/X5/serzakharov/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.38340/out/extension.js:127:108232)
	at async /home/X5/serzakharov/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2020.11.38340/out/extension.js:127:129588
[13:11:31.624] Local server exit: 15
[13:11:31.626] -----

**Comment by roblourens** [comment]
Sorry about that, should be fixed when you upgrade to vscode 1.52, which was just released, can you check?

**Comment by sergei3000** [comment]
@roblourens 
Upgrading to new version of VS Code itself is not easy on my host, but it seems that even without such an upgrade the newest version of the stable `SSH - Remote` extension works fine for me. Checked by removing the `.remote-server` folder from the remote server and connecting there from scratch.
So I guess problem solved. Thanks!

**Comment by sergei3000** [comment]
Just managed to install 1.52, everything is working fine.
