### ISSUE TITLE
regression: remote via SSH failing after update vscode/extension update to 1.52.0 and 0.62.0

### ISSUE THREAD

**Issue by diablodale** [microsoft/vscode-remote-release#4182]
Remote SSH regression in VSCode 1.52.0 and RemoteSSH 0.62.0. Remote SSH projects fail to connect with error...

```
Failed to set up socket for dynamic port forward to remote port 35755: connect ECONNREFUSED 127.0.0.1:61011. Is the remote port correct?
```

I am experiencing it with remote SSH. I see others reporting the same problem with remote WSL. https://github.com/microsoft/vscode-remote-release/issues/4179

No known changes except I did update today to VSCode 1.52.0 and it updated RemoteSSH to 0.62.0.

**I verified...the same projects *work* on a machine using 1.51.1 and RemoteSSH 0.61.0.**
I believe this indicates a regression.

I checked...Insiders Version: 1.53.0-insider (user setup) with Commit: 76436a4d43566cd313629799e2ec51b4d00caa64
also fails. It doesn't give the above error. Instead the SSH session fails and SSH logout displays the following and nothing after...
```
...
installTime==585==
extInstallTime====
serverStartTime==68==
7cecb1cc3b0b: end
```

### Setup

Version: 1.52.0 (system setup)
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:45:11.850Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Remote is:

Ubuntu 18.04.5 LTS
openssh-server/bionic-security,bionic-updates,now 1:7.6p1-4ubuntu0.3 amd64

### Steps to Reproduce:

1. Have multiple remote SSH project/folders for a year
2. Open any of them

### Result

The remote coding session fails. Looking in the ssh log pane, the errors seen are:

```
Failed to set up socket for dynamic port forward to remote port 35755: connect ECONNREFUSED 127.0.0.1:61011. Is the remote port correct?
```

### Expected

No errors and successful RemoteSSH session.

### Q&A

Does this issue occur when you try this locally? N/A...because the issue is Remote SSH.
Does this issue occur when you try this locally and all extensions are disabled? N/A...the issue is Remote SSH.

### Log output

SSH log pane output

```
[04:09:28.517] Log Level: 2
[04:09:28.524] remote-ssh@0.62.0
[04:09:28.524] win32 x64
[04:09:28.526] SSH Resolver called for "ssh-remote+redacted", attempt 1
[04:09:28.526] "remote.SSH.useLocalServer": false
[04:09:28.527] "remote.SSH.showLoginTerminal": false
[04:09:28.527] "remote.SSH.remotePlatform": {"redacted":"linux"}
[04:09:28.527] "remote.SSH.sshPath": C:\njs\ssh.BAT
[04:09:28.528] "remote.SSH.sshConfigurationFile": undefined
[04:09:28.528] "remote.SSH.useFlock": true
[04:09:28.528] "remote.SSH.lockfilesInTmp": false
[04:09:28.528] "remote.SSH.localServerDownload": auto
[04:09:28.529] "remote.SSH.remoteServerListenOnSocket": false
[04:09:28.529] "remote.SSH.showLoginTerminal": false
[04:09:28.529] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[04:09:28.529] SSH Resolver called for host: redacted
[04:09:28.530] Setting up SSH remote "redacted"
[04:09:28.554] Using commit id "940b5f4bb5fa47866a54529ed759d95d09ee80be" and quality "stable" for server
[04:09:28.560] Install and start server if needed
[04:09:28.565] Checking ssh with "C:\njs\ssh.BAT -V"
[04:09:28.663] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020

[04:09:28.733] Running script with connection command: "C:\njs\ssh.BAT" -T -D 61011 "redacted" bash
[04:09:28.736] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[04:09:28.909] > ]0;C:\WINDOWS\System32\cmd.exe
[04:09:28.910] Got some output, clearing connection timeout
[04:09:29.903] > 6696afa568ae: running
[04:09:29.929] > Acquiring lock on /home/dale/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d
> 09ee80be/vscode-remote-lock.dale.940b5f4bb5fa47866a54529ed759d95d09ee80be       
[04:09:29.946] > Found existing installation at /home/dale/.vscode-server/bin/940b5f4bb5fa47866a5
> 4529ed759d95d09ee80be...
> Checking /home/dale/.vscode-server/.940b5f4bb5fa47866a54529ed759d95d09ee80be.log
>  and /home/dale/.vscode-server/.940b5f4bb5fa47866a54529ed759d95d09ee80be.pid for
>  a running server
> Looking for server with pid: 5696
[04:09:29.958] > Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status on port 35755 with wget
> 6696afa568ae: start
> sshAuthSock====
> webUiAccessToken====
> listeningOn==35755==
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
[04:09:29.965] > 
> extInstallTime====
> serverStartTime====
> 6696afa568ae: end
[04:09:29.965] Received install output: 
sshAuthSock====
webUiAccessToken====
listeningOn==35755==
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[04:09:29.966] Remote server is listening on 35755
[04:09:29.966] Parsed server configuration: {"remoteListeningOn":{"port":35755},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/1000","platform":"linux"}
[04:09:29.968] Starting forwarding server. localPort 61014 -> socksPort 61011 -> remotePort 35755
[04:09:29.970] Forwarding server listening on 61014
[04:09:29.970] Waiting for ssh tunnel to be ready
[04:09:29.972] Tunneled 35755 to local port 61014
[04:09:29.972] Resolved "ssh-remote+redacted" to "127.0.0.1:61014"
[04:09:29.974] [Forwarding server 61014] Got connection 0
[04:09:29.981] ------




[04:09:30.007] [Forwarding server 61014] Got connection 1
[04:09:30.009] [Forwarding server 61014] Got connection 2
[04:09:32.022] Failed to set up socket for dynamic port forward to remote port 35755: connect ECONNREFUSED 127.0.0.1:61011. Is the remote port correct?
[04:09:32.054] Failed to set up socket for dynamic port forward to remote port 35755: connect ECONNREFUSED 127.0.0.1:61011. Is the remote port correct?
[04:09:32.054] Failed to set up socket for dynamic port forward to remote port 35755: connect ECONNREFUSED 127.0.0.1:61011. Is the remote port correct?
```

Dev Tools Console
```
abstractExtensionService.ts:840 Extension 'ms-toolsai.jupyter cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
updateEnableProposedApi @ abstractExtensionService.ts:829
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/940b5f4bb5fa47866a54529ed759d95d09ee80be/node_modules/windows-process-tree/lib/index.js.map: Unknown error
```

**Comment by roblourens** [comment]
>No known changes except I did update today to VSCode 1.52.0 and it updated RemoteSSH to 0.62.0.
>
>I verified...the same projects work on a machine using 1.51.1 and RemoteSSH 0.61.0.

Can you try with VS Code 1.52 and Remote-SSH 0.61? You can right click the extension and say "Install another version"

No idea what would have changed. Works for me on windows.

Also could you try setting `"remote.SSH.enableDynamicForwarding": false` to eliminate one variable?

**Comment by diablodale** [comment]
In each these failed tests, I setup VSCode as instructed, exited VSCode, started VSCode, and selected to open an SSH project that is otherwise successful with VSCode 1.51.1 and RemoteSSH 0.61.0. And I tried twice -- each failed in the same way.

### VSCode 1.52 with downgrade to Remote SSH 0.61

```
[15:58:30.362] Log Level: 2
[15:58:30.371] remote-ssh@0.61.0
[15:58:30.371] win32 x64
[15:58:30.375] SSH Resolver called for "ssh-remote+redacted", attempt 1
[15:58:30.376] "remote.SSH.useLocalServer": false
[15:58:30.377] "remote.SSH.showLoginTerminal": false
[15:58:30.377] "remote.SSH.remotePlatform": {"redacted":"linux"}
[15:58:30.378] "remote.SSH.sshPath": C:\njs\ssh.BAT
[15:58:30.378] "remote.SSH.sshConfigurationFile": undefined
[15:58:30.379] "remote.SSH.useFlock": true
[15:58:30.379] "remote.SSH.lockfilesInTmp": false
[15:58:30.380] "remote.SSH.localServerDownload": auto
[15:58:30.380] "remote.SSH.remoteServerListenOnSocket": false
[15:58:30.381] "remote.SSH.showLoginTerminal": false
[15:58:30.381] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[15:58:30.382] SSH Resolver called for host: redacted
[15:58:30.382] Setting up SSH remote "redacted"
[15:58:30.414] Using commit id "940b5f4bb5fa47866a54529ed759d95d09ee80be" and quality "stable" for server
[15:58:30.419] Install and start server if needed
[15:58:30.427] Checking ssh with "C:\njs\ssh.BAT -V"
[15:58:30.527] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020

[15:58:30.600] Running script with connection command: "C:\njs\ssh.BAT" -T -D 60312 "redacted" bash
[15:58:30.605] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:58:30.791] > ]0;C:\WINDOWS\System32\cmd.exe
[15:58:30.792] Got some output, clearing connection timeout
[15:58:39.203] > ee77d985b3be: running
[15:58:39.223] > Acquiring lock on /home/dale/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d
> 09ee80be/vscode-remote-lock.dale.940b5f4bb5fa47866a54529ed759d95d09ee80be       
[15:58:39.235] > Installing to /home/dale/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee
> 80be...
> ee77d985b3be%%1%%
[15:58:39.251] > Downloading with wget
[15:58:44.528] > Download complete
[15:58:44.545] > ee77d985b3be%%2%%
> tar --version:
> tar (GNU tar) 1.29
> Copyright (C) 2015 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[15:58:45.120] > Checking /home/dale/.vscode-server/.940b5f4bb5fa47866a54529ed759d95d09ee80be.log
>  and /home/dale/.vscode-server/.940b5f4bb5fa47866a54529ed759d95d09ee80be.pid for
>  a running server
[15:58:45.141] > Starting server with command... /home/dale/.vscode-server/bin/940b5f4bb5fa47866a
> 54529ed759d95d09ee80be/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown 
>  --port=0 &> "/home/dale/.vscode-server/.940b5f4bb5fa47866a54529ed759d95d09ee80b
> e.log" < /dev/null
> printenv:
>     SSH_CONNECTION=192.168.2.12 53438 192.168.2.5 22
>     LANG=en_US.UTF-8
>     XDG_SESSION_ID=770
>     USER=dale
[15:58:45.146] > 
>     PWD=/home/dale
>     HOME=/home/dale
>     SSH_CLIENT=192.168.2.12 53438 22
>     MAIL=/var/mail/dale
>     SHELL=/bin/bash
>     SHLVL=2
>     VSCODE_AGENT_FOLDER=/home/dale/.vscode-server
>     LOGNAME=dale
>     XDG_RUNTIME_DIR=/run/user/1000
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
> :/usr/local/games:/snap/bin
>     _=/usr/bin/printenv
[15:58:45.152] > 
>     OLDPWD=/home/dale/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80b
> e
> Spawned remote server: 20330
> Waiting for server log...
[15:58:45.167] > 
[15:58:45.356] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,  
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
[15:58:45.363] > ee77d985b3be: start
> sshAuthSock====
> webUiAccessToken====
> listeningOn==45393==
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult==success==
> didLocalDownload==0==
> downloadTime==5308==
> installTime==577==
> extInstallTime====
> serverStartTime==209==
> ee77d985b3be: end
[15:58:45.363] Received install output: 
sshAuthSock====
webUiAccessToken====
listeningOn==45393==
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult==success==
didLocalDownload==0==
downloadTime==5308==
installTime==577==
extInstallTime====
serverStartTime==209==

[15:58:45.365] Remote server is listening on 45393
[15:58:45.365] Parsed server configuration: {"remoteListeningOn":{"port":45393},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/run/user/1000","platform":"linux","downloadTime":5308,"installTime":577,"serverStartTime":209}
[15:58:45.367] Starting forwarding server. localPort 60316 -> socksPort 60312 -> remotePort 45393
[15:58:45.368] Forwarding server listening on 60316
[15:58:45.369] Waiting for ssh tunnel to be ready
[15:58:45.371] [Forwarding server 60316] Got connection 0
[15:58:45.373] Tunneled 45393 to local port 60316
[15:58:45.374] Resolved "ssh-remote+redacted" to "127.0.0.1:60316"
[15:58:45.376] > 
[15:58:45.388] ------




[15:58:45.423] [Forwarding server 60316] Got connection 1
[15:58:45.424] [Forwarding server 60316] Got connection 2
[15:58:47.188] Unhandled rejection: Error: spawn \mnt\nasdata1\dale\opsworkspace\home\git ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)
[15:58:47.204] Unhandled rejection: Error: spawn \mnt\nasdata1\dale\opsworkspace\home\git ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

### VSCode 1.52 with downgrade to Remote SSH 0.61 and remote.SSH.enableDynamicForwarding=false

```
[16:06:42.335] Log Level: 2
[16:06:42.341] remote-ssh@0.61.0
[16:06:42.342] win32 x64
[16:06:42.344] SSH Resolver called for "ssh-remote+redacted", attempt 1
[16:06:42.344] "remote.SSH.useLocalServer": false
[16:06:42.345] "remote.SSH.showLoginTerminal": false
[16:06:42.345] "remote.SSH.remotePlatform": {"redacted":"linux"}
[16:06:42.345] "remote.SSH.sshPath": C:\njs\ssh.BAT
[16:06:42.345] "remote.SSH.sshConfigurationFile": undefined
[16:06:42.346] "remote.SSH.useFlock": true
[16:06:42.346] "remote.SSH.lockfilesInTmp": false
[16:06:42.346] "remote.SSH.localServerDownload": auto
[16:06:42.346] "remote.SSH.remoteServerListenOnSocket": false
[16:06:42.347] "remote.SSH.showLoginTerminal": false
[16:06:42.347] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[16:06:42.347] SSH Resolver called for host: redacted
[16:06:42.347] Setting up SSH remote "redacted"
[16:06:42.389] Using commit id "940b5f4bb5fa47866a54529ed759d95d09ee80be" and quality "stable" for server
[16:06:42.395] Install and start server if needed
[16:06:42.400] Checking ssh with "C:\njs\ssh.BAT -V"
[16:06:42.484] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020

[16:06:42.544] Running script with connection command: "C:\njs\ssh.BAT" -T -o ClearAllForwardings=true "redacted" bash
[16:06:42.548] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[16:06:42.693] > ]0;C:\WINDOWS\System32\cmd.exe
[16:06:42.693] Got some output, clearing connection timeout
[16:06:43.590] > 67fb029b0d0a: running
[16:06:43.620] > Acquiring lock on /home/dale/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d
> 09ee80be/vscode-remote-lock.dale.940b5f4bb5fa47866a54529ed759d95d09ee80be       
[16:06:43.634] > Found existing installation at /home/dale/.vscode-server/bin/940b5f4bb5fa47866a5
> 4529ed759d95d09ee80be...
> Checking /home/dale/.vscode-server/.940b5f4bb5fa47866a54529ed759d95d09ee80be.log
>  and /home/dale/.vscode-server/.940b5f4bb5fa47866a54529ed759d95d09ee80be.pid for
>  a running server
> Looking for server with pid: 20330
[16:06:43.650] > Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status on port 45393 with wget
> 67fb029b0d0a: start
> webUiAccessToken====
> listeningOn==45393==
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
[16:06:43.660] > 
> serverStartTime====
> 67fb029b0d0a: end
[16:06:43.660] Received install output: 
webUiAccessToken====
listeningOn==45393==
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[16:06:43.663] Remote server is listening on 45393
[16:06:43.663] Parsed server configuration: {"remoteListeningOn":{"port":45393},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","tmpDir":"/run/user/1000","platform":"linux"}
[16:06:43.673] Running script with connection command: "C:\njs\ssh.BAT" -T -L 127.0.0.1:60398:127.0.0.1:45393 redacted bash
[16:06:43.674] Spawning tunnel with: type "C:\Users\dale\AppData\Local\Temp\vscode-linux-multi-line-command-redacted-930173294.sh" | "C:\njs\ssh.BAT" -T -L 127.0.0.1:60398:127.0.0.1:45393 redacted bash
[16:06:43.675] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[16:06:43.760] > ]0;C:\WINDOWS\System32\cmd.exe
[16:06:43.958] "install" terminal command done
[16:06:43.959] Install terminal quit with output: 
[16:06:44.721] > SSH_AUTH_SOCK=
> Connected to SSH Host - Please do not close this terminal
[16:06:44.722] Spawned SSH tunnel between local port 60398 and remote target 45393
[16:06:44.722] Waiting for ssh tunnel to be ready
[16:06:45.235] Tunneled 45393 to local port 60398
[16:06:45.235] Resolved "ssh-remote+redacted" to "127.0.0.1:60398"
[16:06:45.243] ------




[16:06:46.694] Unhandled rejection: Error: spawn \mnt\nasdata1\dale\opsworkspace\home\git ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)
[16:06:46.705] Unhandled rejection: Error: spawn \mnt\nasdata1\dale\opsworkspace\home\git ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by roblourens** [comment]
So both of those failed? That's interesting because the first one for 1.52/0.61 does not show the `[Forwarding server 60316] Got connection 1` message that I thought was the real error.

So did you get some error from vscode here, and what was the error? Same as in the original case/

**Comment by svisnaw** [comment]
I had a similar issue after the 1.52/0.62 update, but it only affected my busybox target.

Downgrading Remote-SSH to 0.61 didn't work, I had to go back to 0.56

`[10:34:51.397] Log Level: 2
[10:34:51.408] remote-ssh@0.62.0
[10:34:51.408] win32 x64
[10:34:51.409] SSH Resolver called for "ssh-remote+10.0.6.66", attempt 1
[10:34:51.409] "remote.SSH.useLocalServer": false
[10:34:51.410] "remote.SSH.showLoginTerminal": false
[10:34:51.410] "remote.SSH.remotePlatform": {}
[10:34:51.410] "remote.SSH.sshPath": C:\\Program Files\\Git\\usr\\bin\\ssh.exe
[10:34:51.410] "remote.SSH.sshConfigurationFile": C:\\users\\svisnaw\\.ssh\\config
[10:34:51.410] "remote.SSH.useFlock": true
[10:34:51.411] "remote.SSH.lockfilesInTmp": false
[10:34:51.411] "remote.SSH.localServerDownload": auto
[10:34:51.411] "remote.SSH.remoteServerListenOnSocket": false
[10:34:51.411] "remote.SSH.showLoginTerminal": false
[10:34:51.411] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[10:34:51.411] SSH Resolver called for host: 10.0.6.66
[10:34:51.411] Setting up SSH remote "10.0.6.66"
[10:34:51.436] Using commit id "940b5f4bb5fa47866a54529ed759d95d09ee80be" and quality "stable" for server
[10:34:51.439] Install and start server if needed
[10:34:51.444] Checking ssh with "C:\\Program Files\\Git\\usr\\bin\\ssh.exe -V"
[10:34:51.538] > OpenSSH_8.3p1, OpenSSL 1.1.1g  21 Apr 2020

[10:34:51.544] Using SSH config file "C:\\users\\svisnaw\\.ssh\\config"
[10:34:51.544] Running script with connection command: "C:\\Program Files\\Git\\usr\\bin\\ssh.exe" -T -D 3710 -F "C:\\users\\svisnaw\\.ssh\\config" "10.0.6.66" bash
[10:34:51.547] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:34:51.687] > 
[10:34:51.687] Got some output, clearing connection timeout
[10:34:52.370] > 37a78c692918: running
> 
[10:34:52.464] > Acquiring lock on /home/root/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d
> 09ee80be/vscode-remote-lock.root.940b5f4bb5fa47866a54529ed759d95d09ee80be
> 
[10:34:52.489] > Installing to /home/root/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee
> 80be...
> 
[10:34:52.550] > 37a78c692918%%1%%
> Downloading with curl
> main: line 52: 1608050092%N/1000000: division by 0 (error token is "N/1000000")
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[10:34:52.989] > 100   133  100   133    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[10:34:53.023] > 100   133  100   133    0     0    311      0 --:--:-- --:--:-- --:--:--   311
> 
[10:34:53.557] >  14 26.7M   14 3903k    0     0  3
[10:34:53.581] > 911k      0  0:00:07 --:--:--  0:00:07 3911k
[10:34:54.551] >  56 26.7M   56 15.2M    0     0  7803k      0  0:00:07 --:--:--  0:00:07 3911k
[10:34:54.586] >  56 26.7M   56 15.2M    0     0  7803k      0  0:00:03  0:00:01  0:00:02 11.4M
[10:34:55.557] >  98 26.7M   98 26.3M    0     0  7803k      0  0:00:03  0:00:01  0:00:02 11.4M
[10:34:55.584] > 100 26.7M  100 26.7M    0     0  9041k      0  0:00:03  0:00:03 --:--:-- 11.2M
> 
[10:34:55.648] > Download complete
> 
[10:34:55.679] > 37a78c692918%%2%%
> tar --version:
> main: line 52: 1608050095%N/1000000: division by 0 (error token is "N/1000000")
> main: line 60: - : syntax error: operand expected (error token is "- ")
> main: line 52: 1608050095%N/1000000: division by 0 (error token is "N/1000000")
> tar: unrecognized option '--version'
> BusyBox v1.29.3 (2020-09-27 06:24:11 UTC) multi-call binary.
> 
> Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [FILE]
> ...
> 
[10:35:03.680] > main: line 52: 1608050103%N/1000000: division by 0 (error token is "N/1000000")
> 
[10:35:03.716] > ERROR: tar exited with non-0 exit code: 0
> Trigger local server download
> 37a78c692918:trigger_server_download
> platform==linux==
> vscodeArch==armhf==
> destFolder==/home/root/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80
> be==
> 37a78c692918:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/root/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80
> be/vscode-scp-done.flag and vscode-server.tar.gz to exist
>  main: line 60: - : syntax error: operand expected (error token is "- ")
> 
[10:35:03.717] Got request to download on client for {"platform":"linux","arch":"armhf","destFolder":"/home/root/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be"}
[10:35:03.717] Downloading VS Code server locally...
[10:35:04.120] Downloaded VS Code server to c:\Users\svisnaw\AppData\Local\Temp\beeb1ded-09d2-4e41-8ca2-3b321d04d82d
[10:35:04.122] Renamed VS Code server to c:\Users\svisnaw\AppData\Local\Temp\vscode_server_1608050104120\vscode-server.tar.gz
[10:35:04.125] Checking ssh with "C:\\Program Files\\Git\\usr\\bin\\ssh.exe -V"
[10:35:04.190] > OpenSSH_8.3p1, OpenSSL 1.1.1g  21 Apr 2020

[10:35:04.203] Expecting scp to be next to ssh at C:\Program Files\Git\usr\bin\scp.exe
[10:35:04.203] Testing scp with "C:\Program Files\Git\usr\bin\scp.exe"
[10:35:04.279] scp exited with code: 1
[10:35:04.279] Got stderr from scp: usage: scp [-346BCpqrTv] [-c cipher] [-F ssh_config] [-i identity_file]
            [-J destination] [-l limit] [-o ssh_option] [-P port]
            [-S program] source ... target
[10:35:04.280] Using SSH config file "C:\\users\\svisnaw\\.ssh\\config"
[10:35:04.280] Copying file to remote with "C:\Program Files\Git\usr\bin\scp.exe" -F "C:\\users\\svisnaw\\.ssh\\config" "vscode-server.tar.gz" "vscode-scp-done.flag" "10.0.6.66":"/home/root/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be"
[10:35:04.280] Using cwd: file:///c%3A/Users/svisnaw/AppData/Local/Temp/vscode_server_1608050104120
[10:35:04.281] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:35:04.387] > 
[10:35:05.073] > vscode-server.tar.gz                            0%    0     0.0KB/s   --:-- ETA
[10:35:06.068] > vscode-server.tar.gz                           21% 5888KB   5.7MB/s   00:03 ETA
[10:35:06.678] > 
[10:35:07.072] > vscode-server.tar.gz                           42%   11MB   5.7MB/s   00:02 ETA
[10:35:08.070] > vscode-server.tar.gz                           63%   17MB   5.7MB/s   00:01 ETA
[10:35:09.072] > vscode-server.tar.gz                           82%   22MB   5.6MB/s   00:00 ETA
[10:35:09.715] > 
[10:35:10.067] > vscode-server.tar.gz                          100%   27MB   5.4MB/s   00:04
> vscode-scp-done.flag                          100%    9     3.9KB/s   00:00
> 
[10:35:10.349] "Copy server to host" terminal command done
[10:35:12.713] >   Found flag and server on host
> 
[10:35:12.739] > 37a78c692918%%2%%
> tar --version:
> main: line 52: 1608050112%N/1000000: division by 0 (error token is "N/1000000")
> 
[10:35:12.812] > tar: unrecognized option '--version'
> BusyBox v1.29.3 (2020-09-27 06:24:11 UTC) multi-call binary.
> 
> Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [FILE]
> ...
> 
[10:35:20.524] > main: line 52: 1608050120%N/1000000: division by 0 (error token is "N/1000000")
> 
[10:35:20.558] > ERROR: tar exited with non-0 exit code: 0
> Already attempted local download, failing
> 37a78c692918: start
> exitCode==37==
> listeningOn====
> osReleaseId==tdx-x11==
> arch==armv7l==
> tmpDir==/tmp==
> platform==linux==
> unpackResult==error==
> didLocalDownload==1==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 37a78c692918: end
> main: line 60: - : syntax error: operand expected (error token is "- ")
> 
[10:35:20.559] Received install output: 
exitCode==37==
listeningOn====
osReleaseId==tdx-x11==
arch==armv7l==
tmpDir==/tmp==
platform==linux==
unpackResult==error==
didLocalDownload==1==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[10:35:20.565] Resolver error: Error: Failed to install the VS Code Server
	at Function.ServerInstallError (c:\Users\svisnaw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:64207)
	at c:\Users\svisnaw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:62881
	at Object.t.handleInstallOutput (c:\Users\svisnaw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:63061)
	at I (c:\Users\svisnaw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:311112)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\svisnaw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:309029
	at async Object.t.withShowDetailsEvent (c:\Users\svisnaw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:403706)
	at async Object.t.resolve (c:\Users\svisnaw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:312426)
	at async c:\Users\svisnaw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:127:110280
[10:35:20.570] ------




[10:35:20.863] "install" terminal command done
[10:35:20.863] Install terminal quit with output: 
`

**Comment by diablodale** [comment]
@roblourens the errors are listed in the last lines of the console output I pasted for both fail cases.
I saw no popup windows.

**Comment by roblourens** [comment]
@svisnaw please open a new issue

@diablodale not the same forwarding server errors though. I'm not concerned about whatever is going on with git. 

You didn't see any error popup from vscode though? I would expect to see it complain that it can't connect to the remote. Are there any errors in the devtools console (Help > Toggle Developer tools)

**Comment by diablodale** [comment]
Hi. Yesterday's patched vscode 1.52.1 is successful and does not reproduce the failures above. It and Remote-SSH 0.62.0 work on multiple computers and connect to multiple remote SSH projects.

I have collected all the 1.52.1 logs that now show success. I can add them here if you specifically request.
I can generate/gather previous 1.52.0 logs if you specifically request.
Or, we can close this as fixed... likely related to https://github.com/microsoft/vscode/issues/112571

**Comment by itaysk** [comment]
I'm with 1.52.1 and I'm still facing this issue

**Comment by roblourens** [comment]
Glad it works but I don't think that linked issue would be related. Not sure what happened here. @itaysk please open a new issue with details and logs and I can take a look.

**Comment by roblourens** [comment]
Really the only thing I can think of is that the 1.52.0 didn't get installed properly. You could try listing all the files in the installed folder, like `ls -lR` in `~/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be`. But the Remote-SSH log shows that the server was able to start and load its files, even if there was some problem later starting the remote extension host process, so it seems unlikely to me. I really don't know
