### ISSUE TITLE
Timeout for SSH connetion even though SSH connects successfully

### ISSUE THREAD

**Issue by torkelrogstad** [microsoft/vscode-remote-release#4206]
- VSCode Version: 1.52.0
- OS Version: macOS 11.0.1

Does this issue occur when all extensions are disabled?: Yes - I've tried disabling all extensions except the "Remote - SSH" extension

I can't connect to a SSH server due to a timeout issue, even though it appears the SSH connection itself is successfull.

1. Remote-SSH: Connect to host...
2. Choose correct host in the dropdown (which is a host I'm able to SSH into normally)
3. Connection times out, even though I get the Ubuntu greeting banner: 
```
[22:18:12.069] Log Level: 1
[22:18:12.072] remote-ssh@0.62.0
[22:18:12.072] darwin x64
[22:18:12.073] SSH Resolver called for "ssh-remote+torkel-desktop", attempt 1
[22:18:12.074] "remote.SSH.useLocalServer": true
[22:18:12.074] "remote.SSH.sshPath": undefined
[22:18:12.074] "remote.SSH.sshConfigurationFile": undefined
[22:18:12.075] "remote.SSH.useFlock": true
[22:18:12.075] "remote.SSH.lockfilesInTmp": false
[22:18:12.075] "remote.SSH.localServerDownload": auto
[22:18:12.075] "remote.SSH.remoteServerListenOnSocket": false
[22:18:12.075] "remote.SSH.showLoginTerminal": true
[22:18:12.076] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[22:18:12.076] SSH Resolver called for host: torkel-desktop
[22:18:12.076] Setting up SSH remote "torkel-desktop"
[22:18:12.080] Acquiring local install lock: /var/folders/7_/6snf5h451hv62fr1flgrpcfc0000gn/T/vscode-remote-ssh-torkel-desktop-install.lock
[22:18:12.092] Looking for existing server data file at /Users/torkel/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-torkel-desktop-940b5f4bb5fa47866a54529ed759d95d09ee80be-0.62.0/data.json
[22:18:12.093] Using commit id "940b5f4bb5fa47866a54529ed759d95d09ee80be" and quality "stable" for server
[22:18:12.099] Install and start server if needed
[22:18:12.104] Checking ssh with "ssh -V"
[22:18:12.158] > OpenSSH_8.1p1, LibreSSL 2.7.3

[22:18:12.180] askpass server listening on /var/folders/7_/6snf5h451hv62fr1flgrpcfc0000gn/T/vscode-ssh-askpass-9eab0d584695ad801f7d4b945054477e43492017.sock
[22:18:12.181] Spawning local server with {"ipcHandlePath":"/var/folders/7_/6snf5h451hv62fr1flgrpcfc0000gn/T/vscode-ssh-askpass-34a724569dcdf2562cdbf77006c2c33c3273957a.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","52018","-o","ConnectTimeout=60","torkel-desktop"],"dataFilePath":"/Users/torkel/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-torkel-desktop-940b5f4bb5fa47866a54529ed759d95d09ee80be-0.62.0/data.json"}
[22:18:12.181] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/torkel/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/torkel/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/7_/6snf5h451hv62fr1flgrpcfc0000gn/T/vscode-ssh-askpass-9eab0d584695ad801f7d4b945054477e43492017.sock"}
[22:18:12.185] Spawned 33459
[22:18:12.392] > local-server> Spawned ssh: 33460
[22:18:12.396] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[22:18:12.396] stderr> debug1: Reading configuration data /Users/torkel/.ssh/config
--- some logs omitted, don't want to leak info about my SSH keys
[22:18:12.893] stderr> debug1: Sending environment.
[22:18:12.894] stderr> debug1: Sending env LC_ALL = en_US.utf8
[22:18:12.897] > Welcome to Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-53-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
> 21 updates can be installed immediately.
> 8 of these updates are security updates.
> To see these additional updates run: apt list --upgradable
> 
> *** System restart required ***
[22:19:14.190] Terminating local server
[22:19:14.197] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/torkel/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:64405)
	at Timeout._onTimeout (/Users/torkel/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:277390)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)
[22:19:14.199] Local server exit: 15
[22:19:14.201] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"Timeout","exitCodeLabel":"","osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"1"},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":62119,"timing.preSshTime":108}}
```

**Comment by torkelrogstad** [comment]
That worked! However, I was not able to open up the terminal. I got an error message because it tried to access my _local_ home folder on the _remote_. Is this expected behavior?

**Comment by roblourens** [comment]
Hm, do you have any terminal settings set?

**Comment by balupton** [comment]
I swapped from password based ssh login on macos, to using my https://github.com/kryptco/kr public key in authorized keys. It authenticates correctly, but as I guess, it doesn't run that script.

Settings  `"remote.SSH.useLocalServer": false` worked around it successfully.

Is this a bug on vscode or krypton?

**Comment by lamnd09** [comment]
Had the same problem. The simple solution is that I uninstalled the current version (newest) of VScode and re-install older version (1.5.0). It works.

**Comment by roblourens** [comment]
Didn't hear back from @torkelrogstad, closing

@balupton I wouldn't expect that tool to break this, but I'm not sure how it works. Please open a new issue if you want me to investigate more.

**Comment by ismail** [comment]
I got the same problem - VSCode 1.55.0 on openSUSE Tumbleweed, remote Ubuntu 21.04. 
"remote.SSH.useLocalServer": false works but I don't understand the problem, does useLocalServer enables connection multiplexing?

If you need any debug info let me know.

**Comment by madiha95** [comment]
I'm still facing the same prblm the work around didnt resolve it , is there other suggestions !?

**Comment by axeII** [comment]
Using latest version: Version: 1.55.1 and disabling `remote.SSH.useLocalServer` worked for me I am able to connect. Also don't forget to choose os when connecting. I forgot to choose os when I was connecting for the first time and also had timeout error.

**Comment by jxramos** [comment]
I'm in this pickle right now,

VS Code Version: 1.55.1
MacOS 10.15.7 (19H524)

trying to remote to an Ubuntu 14.x machine. Times out 100% of the time. Tried increasing timeout, and disabling useLocalServer to no avail. I'm going to set the Remote.SSH: Log Level to trace and see if anything can be spotted.

```
[20:55:33.072] Spawned 68212
[20:55:33.196] > local-server> Spawned ssh: 68216
[20:55:33.201] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[20:55:33.201] stderr> debug1: Reading configuration data /Users/USERX/.ssh/config
[20:55:33.201] stderr> debug1: /Users/USERX/.ssh/config line 6: Applying options for XXX.XXX.XXX.XXX
[20:55:33.201] stderr> debug1: Reading configuration data /etc/ssh/ssh_config
[20:55:33.201] stderr> debug1: /etc/ssh/ssh_config line 47: Applying options for *
[20:55:34.020] stderr> debug1: Connecting to XXX.XXX.XXX.XXX [XXX.XXX.XXX.XXX] port 22.
[20:55:34.068] stderr> debug1: fd 3 clearing O_NONBLOCK
[20:55:34.068] stderr> debug1: Connection established.
[20:55:34.068] stderr> debug1: identity file /Users/USERX/.ssh/id_rsa type 0
[20:55:34.068] stderr> debug1: identity file /Users/USERX/.ssh/id_rsa-cert type -1
[20:55:34.068] stderr> debug1: identity file /Users/USERX/.ssh/id_dsa type -1
[20:55:34.068] stderr> debug1: identity file /Users/USERX/.ssh/id_dsa-cert type -1
[20:55:34.069] stderr> debug1: identity file /Users/USERX/.ssh/id_ecdsa type -1
[20:55:34.069] stderr> debug1: identity file /Users/USERX/.ssh/id_ecdsa-cert type -1
[20:55:34.069] stderr> debug1: identity file /Users/USERX/.ssh/id_ed25519 type -1
[20:55:34.069] stderr> debug1: identity file /Users/USERX/.ssh/id_ed25519-cert type -1
[20:55:34.070] stderr> debug1: identity file /Users/USERX/.ssh/id_xmss type -1
[20:55:34.070] stderr> debug1: identity file /Users/USERX/.ssh/id_xmss-cert type -1
[20:55:34.070] stderr> debug1: Local version string SSH-2.0-OpenSSH_8.1
[20:55:34.070] stderr> debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.13
[20:55:34.070] stderr> debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.13 pat OpenSSH_6.6.1* compat 0x04000002
[20:55:34.070] stderr> debug1: Authenticating to XXX.XXX.XXX.XXX:22 as 'USERX'
[20:55:34.070] stderr> debug1: SSH2_MSG_KEXINIT sent
[20:55:34.096] stderr> debug1: SSH2_MSG_KEXINIT received
[20:55:34.096] stderr> debug1: kex: algorithm: curve25519-sha256@libssh.org
[20:55:34.097] stderr> debug1: kex: host key algorithm: ecdsa-sha2-nistp256
[20:55:34.097] stderr> debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
[20:55:34.097] stderr> debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
[20:55:34.098] stderr> debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
[20:55:50.073] Terminating local server
[20:55:50.077] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/USERX/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:64454)
	at Timeout._onTimeout (/Users/USERX/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:263987)
	at listOnTimeout (internal/timers.js:549:17)
	at processTimers (internal/timers.js:492:7)
[20:55:50.079] Local server exit: 15
[20:55:50.080] TELEMETRY: 
{
    "eventName": "resolver",
    "properties": {
        "osReleaseId": "",
        "arch": "",
        "askedPw": "0",
        "askedPassphrase": "0",
        "asked2fa": "0",
        "askedHostKey": "0",
        "remoteInConfigFile": "1",
        "gotUnrecognizedPrompt": "0",
        "dynamicForwarding": "1",
        "localServer": "1",
        "didLocalDownload": "0",
        "installUnpackCode": "0",
        "outcome": "failure",
        "reason": "Timeout",
        "exitCodeLabel": ""
    },
    "measures": {
        "resolveAttempts": 1,
        "retries": 1,
        "timing.totalResolveTime": 17037,
        "timing.preSshTime": 31
    }
}
```

**Comment by ismail** [comment]
> I'm in this pickle right now,
 Can you actually ssh to this machine? It seems to me it's a cipher problem not a vscode one.

**Comment by jxramos** [comment]
Yah I think you're right. Trying to ssh from terminal just hung. I just upgraded vscode today, something may have gotten off in that process. I restarted my macbook and was able to remote session once again.

**Comment by madiha95** [comment]
I had to uninstall vscode and reinstall it again to correct the problem because I had the right version and also rightly updated all the parameter mentionned before.

**Comment by cpbotha** [comment]
I had the same issue on macOS Big Sur 11.2.3 with VSCode 1.55.2: I would see the remote Linux server MOTD (welcome message) in the logs, but then the connection would timeout.

After I correctly configured `remote.SSH.remotePlatform` to indicate that that hostname mapped to Linux, I could connect without issues.

I did *not* modify `remote.SSH.useLocalServer`, leaving it at its default `true` value.
