### ISSUE TITLE
Remote - SSH fails to connect to busybox target after VScode 1.52.0 / Remote SSH 0.62.0 update

### ISSUE THREAD

**Issue by svisnaw** [microsoft/vscode-remote-release#4207]
I was no longer able to connect to my OpenEmbedded / BusyBox target after updating. My Debian 9 targets were still able to connect successfully. 

I tried using older versions of Remote - SSH with VScode 1.52.0, with no success. I downgraded VScode to 1.51.1. Using Remote - SSH 0.62 and 0.61 produced the same issue. Using 0.56 connecting to my target worked again.

```
[10:34:51.397] Log Level: 2
[10:34:51.408] remote-ssh@0.62.0
[10:34:51.408] win32 x64
[10:34:51.409] SSH Resolver called for "ssh-remote+10.0.6.66", attempt 1
[10:34:51.409] "remote.SSH.useLocalServer": false
[10:34:51.410] "remote.SSH.showLoginTerminal": false
[10:34:51.410] "remote.SSH.remotePlatform": {}
[10:34:51.410] "remote.SSH.sshPath": C:\\Program Files\\Git\\usr\\bin\\ssh.exe
[10:34:51.410] "remote.SSH.sshConfigurationFile": C:\\users\\svisnaw\\.ssh\\config
[10:34:51.410] "remote.SSH.useFlock": true
[10:34:51.411] "remote.SSH.lockfilesInTmp": false
[10:34:51.411] "remote.SSH.localServerDownload": auto
[10:34:51.411] "remote.SSH.remoteServerListenOnSocket": false
[10:34:51.411] "remote.SSH.showLoginTerminal": false
[10:34:51.411] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[10:34:51.411] SSH Resolver called for host: 10.0.6.66
[10:34:51.411] Setting up SSH remote "10.0.6.66"
[10:34:51.436] Using commit id "940b5f4bb5fa47866a54529ed759d95d09ee80be" and quality "stable" for server
[10:34:51.439] Install and start server if needed
[10:34:51.444] Checking ssh with "C:\\Program Files\\Git\\usr\\bin\\ssh.exe -V"
[10:34:51.538] > OpenSSH_8.3p1, OpenSSL 1.1.1g  21 Apr 2020

[10:34:51.544] Using SSH config file "C:\\users\\svisnaw\\.ssh\\config"
[10:34:51.544] Running script with connection command: "C:\\Program Files\\Git\\usr\\bin\\ssh.exe" -T -D 3710 -F "C:\\users\\svisnaw\\.ssh\\config" "10.0.6.66" bash
[10:34:51.547] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:34:51.687] > 
[10:34:51.687] Got some output, clearing connection timeout
[10:34:52.370] > 37a78c692918: running
> 
[10:34:52.464] > Acquiring lock on /home/root/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d
> 09ee80be/vscode-remote-lock.root.940b5f4bb5fa47866a54529ed759d95d09ee80be
> 
[10:34:52.489] > Installing to /home/root/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee
> 80be...
> 
[10:34:52.550] > 37a78c692918%%1%%
> Downloading with curl
> main: line 52: 1608050092%N/1000000: division by 0 (error token is "N/1000000")
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[10:34:52.989] > 100   133  100   133    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[10:34:53.023] > 100   133  100   133    0     0    311      0 --:--:-- --:--:-- --:--:--   311
> 
[10:34:53.557] >  14 26.7M   14 3903k    0     0  3
[10:34:53.581] > 911k      0  0:00:07 --:--:--  0:00:07 3911k
[10:34:54.551] >  56 26.7M   56 15.2M    0     0  7803k      0  0:00:07 --:--:--  0:00:07 3911k
[10:34:54.586] >  56 26.7M   56 15.2M    0     0  7803k      0  0:00:03  0:00:01  0:00:02 11.4M
[10:34:55.557] >  98 26.7M   98 26.3M    0     0  7803k      0  0:00:03  0:00:01  0:00:02 11.4M
[10:34:55.584] > 100 26.7M  100 26.7M    0     0  9041k      0  0:00:03  0:00:03 --:--:-- 11.2M
> 
[10:34:55.648] > Download complete
> 
[10:34:55.679] > 37a78c692918%%2%%
> tar --version:
> main: line 52: 1608050095%N/1000000: division by 0 (error token is "N/1000000")
> main: line 60: - : syntax error: operand expected (error token is "- ")
> main: line 52: 1608050095%N/1000000: division by 0 (error token is "N/1000000")
> tar: unrecognized option '--version'
> BusyBox v1.29.3 (2020-09-27 06:24:11 UTC) multi-call binary.
> 
> Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [FILE]
> ...
> 
[10:35:03.680] > main: line 52: 1608050103%N/1000000: division by 0 (error token is "N/1000000")
> 
[10:35:03.716] > ERROR: tar exited with non-0 exit code: 0
> Trigger local server download
> 37a78c692918:trigger_server_download
> platform==linux==
> vscodeArch==armhf==
> destFolder==/home/root/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80
> be==
> 37a78c692918:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/root/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80
> be/vscode-scp-done.flag and vscode-server.tar.gz to exist
>  main: line 60: - : syntax error: operand expected (error token is "- ")
> 
[10:35:03.717] Got request to download on client for {"platform":"linux","arch":"armhf","destFolder":"/home/root/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be"}
[10:35:03.717] Downloading VS Code server locally...
[10:35:04.120] Downloaded VS Code server to c:\Users\svisnaw\AppData\Local\Temp\beeb1ded-09d2-4e41-8ca2-3b321d04d82d
[10:35:04.122] Renamed VS Code server to c:\Users\svisnaw\AppData\Local\Temp\vscode_server_1608050104120\vscode-server.tar.gz
[10:35:04.125] Checking ssh with "C:\\Program Files\\Git\\usr\\bin\\ssh.exe -V"
[10:35:04.190] > OpenSSH_8.3p1, OpenSSL 1.1.1g  21 Apr 2020

[10:35:04.203] Expecting scp to be next to ssh at C:\Program Files\Git\usr\bin\scp.exe
[10:35:04.203] Testing scp with "C:\Program Files\Git\usr\bin\scp.exe"
[10:35:04.279] scp exited with code: 1
[10:35:04.279] Got stderr from scp: usage: scp [-346BCpqrTv] [-c cipher] [-F ssh_config] [-i identity_file]
            [-J destination] [-l limit] [-o ssh_option] [-P port]
            [-S program] source ... target
[10:35:04.280] Using SSH config file "C:\\users\\svisnaw\\.ssh\\config"
[10:35:04.280] Copying file to remote with "C:\Program Files\Git\usr\bin\scp.exe" -F "C:\\users\\svisnaw\\.ssh\\config" "vscode-server.tar.gz" "vscode-scp-done.flag" "10.0.6.66":"/home/root/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be"
[10:35:04.280] Using cwd: file:///c%3A/Users/svisnaw/AppData/Local/Temp/vscode_server_1608050104120
[10:35:04.281] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:35:04.387] > 
[10:35:05.073] > vscode-server.tar.gz                            0%    0     0.0KB/s   --:-- ETA
[10:35:06.068] > vscode-server.tar.gz                           21% 5888KB   5.7MB/s   00:03 ETA
[10:35:06.678] > 
[10:35:07.072] > vscode-server.tar.gz                           42%   11MB   5.7MB/s   00:02 ETA
[10:35:08.070] > vscode-server.tar.gz                           63%   17MB   5.7MB/s   00:01 ETA
[10:35:09.072] > vscode-server.tar.gz                           82%   22MB   5.6MB/s   00:00 ETA
[10:35:09.715] > 
[10:35:10.067] > vscode-server.tar.gz                          100%   27MB   5.4MB/s   00:04
> vscode-scp-done.flag                          100%    9     3.9KB/s   00:00
> 
[10:35:10.349] "Copy server to host" terminal command done
[10:35:12.713] >   Found flag and server on host
> 
[10:35:12.739] > 37a78c692918%%2%%
> tar --version:
> main: line 52: 1608050112%N/1000000: division by 0 (error token is "N/1000000")
> 
[10:35:12.812] > tar: unrecognized option '--version'
> BusyBox v1.29.3 (2020-09-27 06:24:11 UTC) multi-call binary.
> 
> Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [FILE]
> ...
> 
[10:35:20.524] > main: line 52: 1608050120%N/1000000: division by 0 (error token is "N/1000000")
> 
[10:35:20.558] > ERROR: tar exited with non-0 exit code: 0
> Already attempted local download, failing
> 37a78c692918: start
> exitCode==37==
> listeningOn====
> osReleaseId==tdx-x11==
> arch==armv7l==
> tmpDir==/tmp==
> platform==linux==
> unpackResult==error==
> didLocalDownload==1==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 37a78c692918: end
> main: line 60: - : syntax error: operand expected (error token is "- ")
> 
[10:35:20.559] Received install output: 
exitCode==37==
listeningOn====
osReleaseId==tdx-x11==
arch==armv7l==
tmpDir==/tmp==
platform==linux==
unpackResult==error==
didLocalDownload==1==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[10:35:20.565] Resolver error: Error: Failed to install the VS Code Server
	at Function.ServerInstallError (c:\Users\svisnaw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:64207)
	at c:\Users\svisnaw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:62881
	at Object.t.handleInstallOutput (c:\Users\svisnaw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:63061)
	at I (c:\Users\svisnaw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:311112)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\svisnaw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:309029
	at async Object.t.withShowDetailsEvent (c:\Users\svisnaw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:403706)
	at async Object.t.resolve (c:\Users\svisnaw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:312426)
	at async c:\Users\svisnaw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:127:110280
[10:35:20.570] ------




[10:35:20.863] "install" terminal command done
[10:35:20.863] Install terminal quit with output: 
```

_Originally posted by @svisnaw in https://github.com/microsoft/vscode-remote-release/issues/4182#issuecomment-745463791_

**Comment by roblourens** [comment]
Two issues here: `main: line 52: 1608050095%N/1000000: division by 0 (error token is "N/1000000")` I added some timing code that uses `date` in a way that busybox's version doesn't like. But I think those errors could be ignored

Second, `tar: unrecognized option '--version'`, but this isn't new, it hasn't changed in a very long time. And on busybox for me, I get `tar (busybox) 1.30.0`. But we ignore that too.

Then, `ERROR: tar exited with non-0 exit code: 0` for the actual untar, which hasn't changed. Maybe the `Usage:` is from the actual tar -xf call? Does it want `tar x -f` instead?

Could you share the log from 0.56 when it does work?

**Comment by roblourens** [comment]
I guess since the `date` stuff is resulting in a syntax error, it could confuse how other lines are interpreted, but it seems to be continuing on fine...

**Comment by svisnaw** [comment]
The busybox version running on my target (1.29.3) looks to be the release before yours, the date command from the shell fails just like the script:
`# echo $(($(date +%s%N)/1000000))`
`-sh: 1608238320%N/1000000: division by 0 (error token is "N/1000000")`

tar -xf does sucessfully extract an archive.

I had removed the .vscode-server and .vscode directories from my home directory while I was troubleshooting. I did see that it had extracted the files from the archive after it reported failure. I notice when I look in the .vscode-server directory while running 0.56 now that the vscode-server.tar.gz has been removed, while it was still present along with the extracted files when it was failing.

```
[11:50:30.932] Log Level: 2
[11:50:30.940] remote-ssh@0.56.0
[11:50:30.940] win32 x64
[11:50:30.941] SSH Resolver called for "ssh-remote+10.0.6.66", attempt 1
[11:50:30.942] SSH Resolver called for host: 10.0.6.66
[11:50:30.942] Setting up SSH remote "10.0.6.66"
[11:50:30.986] Using commit id "e5a624b788d92b8d34d1392e4c4d9789406efe8f" and quality "stable" for server
[11:50:30.987] Install and start server if needed
[11:50:30.991] Checking ssh with "C:\\Program Files\\Git\\usr\\bin\\ssh.exe -V"
[11:50:31.061] > OpenSSH_8.3p1, OpenSSL 1.1.1g  21 Apr 2020

[11:50:31.065] Using SSH config file "C:\\users\\svisnaw\\.ssh\\config"
[11:50:31.066] Running script with connection command: "C:\\Program Files\\Git\\usr\\bin\\ssh.exe" -T -D 18910 -F "C:\\users\\svisnaw\\.ssh\\config" 10.0.6.66 bash
[11:50:31.068] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[11:50:31.202] > 
[11:50:31.202] Got some output, clearing connection timeout
[11:50:31.885] > c0ab2ace1d08: running
> 
[11:50:32.016] > Acquiring lock on /home/root/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789
> 406efe8f/vscode-remote-lock.root.e5a624b788d92b8d34d1392e4c4d9789406efe8f
> 
[11:50:32.041] > Installing to /home/root/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406e
> fe8f...
> c0ab2ace1d08%%1%%
> 
[11:50:32.076] > Downloading with curl
>   % Total    % Received % Xferd  Average Speed
[11:50:32.138] >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[11:50:32.515] > 100   133  100   133    0     0    308      0 --:--:-- --:--:-- --:--:--   308
> 
[11:50:32.602] >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[11:50:33.576] >  28 26.2M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[11:50:33.603] >  28 26.2M   28 7567k    0     0  5113k      0  0:00:05  0:00:01  0:00:04 7818k
[11:50:34.578] >  71 26.2M   71 18.8M    0     0  5113k      0  0:00:05  0:00:01  0:00:04 7818k
[11:50:34.604] >  71 26.2M   71 18.8M    0     0  7780k      0  0:00:03  0:00:02  0:00:01 9804k
[11:50:35.202] > 100 26.2M  100 26.2M    0     0  7780k      0  0:00:03  0:00:02  0:00:01 9804k
[11:50:35.265] > 100 26.2M  100 26.2M    0     0  8588k      0  0:00:03  0:00:03 --:--:-- 10.0M
> 
[11:50:35.891] > Download complete
> c0ab2ace1d08%%2%%
> tar --version:
> 
[11:50:35.951] > tar: unrecognized option '--version'
> BusyBox v1.29.3 (2020-09-27 06:24:11 UTC) multi-call binary.
> 
> Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [FILE]
> ...
> 
[11:50:43.076] > Checking /home/root/.vscode-server/.e5a624b788d92b8d34d1392e4c4d9789406efe8f.log
>  and /home/root/.vscode-server/.e5a624b788d92b8d34d1392e4c4d9789406efe8f.pid for
>  a running server
[11:50:43.103] > 
> 
> 
> 
[11:50:43.951] > Starting server with command... /home/root/.vscode-server/bin/e5a624b788d92b8d34
> d1392e4c4d9789406efe8f/server.sh --host=127.0.0.1 --enable-remote-auto-shutdown
>  --port=0 &> "/home/root/.vscode-server/.e5a624b788d92b8d34d1392e4c4d9789406efe8
> f.log" < /dev/null
> printenv:
> 
[11:50:43.978] > Spawned remote server: 3834
> Waiting for server log...
> main: line 46: printenv: command not found
> 
[11:50:44.511] > Waiting for server log...
> 
[11:50:45.043] > Waiting for server log...
> 
[11:50:45.570] > Waiting for server log...
> 
[11:50:46.105] > Waiting for server log...
> 
[11:50:46.641] > 
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> 
[11:50:46.703] > c0ab2ace1d08: start
> 
[11:50:46.766] > sshAuthSock====
> listeningOn==41857==
> osReleaseId==tdx-x11==
> arch==armv7l==
> webUiAccessToken====
> tmpDir==/tmp==
> platform==linux==
> c0ab2ace1d08: end
> 
[11:50:46.766] Received install output: 
sshAuthSock====
listeningOn==41857==
osReleaseId==tdx-x11==
arch==armv7l==
webUiAccessToken====
tmpDir==/tmp==
platform==linux==

[11:50:46.767] Remote server is listening on 41857
[11:50:46.767] Parsed server configuration: {"remoteListeningOn":{"port":41857},"osReleaseId":"tdx-x11","arch":"armv7l","webUiAccessToken":"","sshAuthSock":"","tmpDir":"/tmp","platform":"linux"}
[11:50:46.778] Starting forwarding server. localPort 18952 -> socksPort 18910 -> remotePort 41857
[11:50:46.801] Forwarding server listening on 18952
[11:50:46.801] Waiting for ssh tunnel to be ready
[11:50:46.803] Tunneled 41857 to local port 18952
[11:50:46.803] Resolved "ssh-remote+10.0.6.66" to "127.0.0.1:18952"
[11:50:46.804] [Forwarding server 18952] Got connection 0
[11:50:46.819] ------




[11:50:46.834] [Forwarding server 18952] Got connection 1
[11:50:46.835] [Forwarding server 18952] Got connection 2
[11:50:53.544] [Forwarding server 18952] Got connection 3
[11:53:46.731] > 
[11:56:46.732] > 
[11:59:46.735] > 
```

**Comment by roblourens** [comment]
Ok, I'm guessing that the date issue is messing up the tar call later, so I'll figure out what i need to do to handle that.

**Comment by stefandeml** [comment]
any update on this one? - running into the same issue...

`=
[21:10:50.083] stderr> main: line 55: 1612210250%N/1000000: division by 0 (error token is "N/1000000")
[21:10:50.083] > d313792a1c11%%2%%
> tar --version:
[21:10:50.084] > tar (busybox) 1.30.1
[21:10:51.047] stderr> main: line 55: 1612210251%N/1000000: division by 0 (error token is "N/1000000")
[21:10:51.047] stderr> main: line 63: - : syntax error: operand expected (error token is "- ")
[21:10:51.047] > ERROR: tar exited with non-0 exit code: 0`

**Comment by stefandeml** [comment]
fixed the issue on my end now by manually extracting the tar on the server and putting it at the right path s.th. the extension finds the binary already installed

**Comment by 3raymon** [comment]
Just as a side note, if someone is facing the same issue with working on a buildroot built busybox image.
I could fix
- the first error: `tar: unrecognized option '--version'` by adding `BR2_PACKAGE_TAR=y` to the defconfig / .config file. This overrides the busybox internal *tar* version by the official one
- the second error: `stderr> main: line 55: 1612210250%N/1000000: division by 0 (error token is "N/1000000")` by adding `BR2_PACKAGE_COREUTILS=y` to the defconfig / .config file. This overrides the busybox internal coreutils, containing amongst other packages, the full *date* package  

So it turned out the busybox internal *tar* and *date* packages where just too slim to execute / fulfill the required options  
btw I was working with BusyBox v1.29.3

**Comment by 3raymon** [comment]
> I have the same problem using Vscode 1.65.2 and a SSH arm64 target using busybox. The strange thing is that is does NOT happen always (I mean: sometime it works).
> 
> The previous posts are not very clear. @3raymon Did your change with the tar/date utility result in a stable behavior?

To be honest, I've not used it for a while now but as far as I could remember it worked afterwards without any problems... would definitely add a comment here if there's news👍

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/1747
