### ISSUE TITLE
Dev Containers on Mac silicon

### ISSUE THREAD

**Issue by mz-zmsoft** [microsoft/vscode-remote-release#4224]
I can not execute any docker command like `Remote-Containers: Reopen in container`

VSCode reports immediately the message **Docker returned an error. Make sure the Docker daemon is running.**

Dev Containers Log
```
[388 ms] Remote-Containers 0.154.1 in VS Code 1.53.0-insider (4a875e23d20b64504a818834f3fa4c40adb8d480).
[595 ms] Start: Run: git rev-parse --abbrev-ref --symbolic-full-name @{u}
[43841 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[43912 ms] spawn docker ENOENT
```

Output when executing docker version manually.
```
docker version --format {{.Server.APIVersion}}
1.41
```

Output in developer tools (hope this helps)
```
console.ts:137 [Extension Host] Error: spawn docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21) (at c (/Users/admin/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.154.1/dist/extension.js:1:697060))
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: spawn docker ENOENT (at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1100:774)
console.ts:137 [Extension Host] stack trace: Error: spawn docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21) (at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1100:853)
log.ts:197   ERR spawn docker ENOENT: Error: spawn docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)

```

**Comment by chrmarti** [comment]
@mz-zmsoft It looks like `docker` is not on the PATH when run from within VS Code. Try setting the absolute path to it in the user settings:
![image](https://user-images.githubusercontent.com/9205389/102894625-affd5b80-4463-11eb-8746-038de67ee71d.png)

**Comment by mz-zmsoft** [comment]
thank you for fast feedback, @chrmarti. Remote Container starts as expected, now.

Got some compile issues. Think it's a docker problem now.

![Bildschirmfoto 2020-12-22 um 16 04 38](https://user-images.githubusercontent.com/55440373/102903001-05d80080-4470-11eb-81ff-454e781b1763.png)

**Comment by chrmarti** [comment]
Thanks @mz-zmsoft. The extension should be independent of the platform. I will therefore close this issue, but please open new issues for any problems you encounter.
