### ISSUE TITLE
Remote-SSH does not work if user's shell is set to fish

### ISSUE THREAD

**Issue by kunickiaj** [microsoft/vscode-remote-release#4234]
- VSCode Version: 1.52.1
- Local OS Version: macOS 11.1
- Remote OS Version: Ubuntu 20.10 (aarch64)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. On the remote host set the user's shell to something other than bash like fish. `chsh -s /usr/bin/fish`
2. Try to open a connection from VS Code

We're logged in to the remote via ssh successfully, however VS Code detects a failure. A similar issue is reproducible if the user's shell is set to dash as well.

Sample log:
```
[10:27:38.563] Log Level: 2
[10:27:38.565] remote-ssh@0.62.0
[10:27:38.565] darwin x64
[10:27:38.567] SSH Resolver called for "ssh-remote+pi4", attempt 1
[10:27:38.567] "remote.SSH.useLocalServer": true
[10:27:38.568] "remote.SSH.sshPath": undefined
[10:27:38.568] "remote.SSH.sshConfigurationFile": undefined
[10:27:38.568] "remote.SSH.useFlock": true
[10:27:38.569] "remote.SSH.lockfilesInTmp": false
[10:27:38.569] "remote.SSH.localServerDownload": auto
[10:27:38.569] "remote.SSH.remoteServerListenOnSocket": false
[10:27:38.569] "remote.SSH.showLoginTerminal": false
[10:27:38.569] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[10:27:38.570] SSH Resolver called for host: pi4
[10:27:38.570] Setting up SSH remote "pi4"
[10:27:38.574] Acquiring local install lock: /var/folders/5q/q71qf2dn50bf9rnkdnqw6_nh0000gn/T/vscode-remote-ssh-pi4-install.lock
[10:27:38.588] Looking for existing server data file at /Users/<user>/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-pi4-ea3859d4ba2f3e577a159bc91e3074c5d85c0523-0.62.0/data.json
[10:27:38.589] Using commit id "ea3859d4ba2f3e577a159bc91e3074c5d85c0523" and quality "stable" for server
[10:27:38.594] Install and start server if needed
[10:27:38.601] Checking ssh with "ssh -V"
[10:27:38.611] > OpenSSH_8.1p1, LibreSSL 2.7.3

[10:27:38.618] askpass server listening on /var/folders/5q/q71qf2dn50bf9rnkdnqw6_nh0000gn/T/vscode-ssh-askpass-657b58bb0906d7fc595b6ea280affe24eca04514.sock
[10:27:38.619] Spawning local server with {"ipcHandlePath":"/var/folders/5q/q71qf2dn50bf9rnkdnqw6_nh0000gn/T/vscode-ssh-askpass-6c4f7a93a003a8da0e689ec5d7854c655b9fff78.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","59885","-o","ConnectTimeout=15","pi4"],"dataFilePath":"/Users/<user>/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-pi4-ea3859d4ba2f3e577a159bc91e3074c5d85c0523-0.62.0/data.json"}
[10:27:38.619] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/<user>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/<user>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/5q/q71qf2dn50bf9rnkdnqw6_nh0000gn/T/vscode-ssh-askpass-657b58bb0906d7fc595b6ea280affe24eca04514.sock"}
[10:27:38.622] Spawned 60131
[10:27:38.760] > local-server> Spawned ssh: 60132
[10:27:38.769] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[10:27:38.829] stderr> debug1: Server host key: ecdsa-sha2-nistp256 <redacted>
[10:27:38.921] stderr> Authenticated to pi4 ([192.168.xxx.yyy]:22).
[10:27:39.342] > Welcome to Ubuntu 20.10 (GNU/Linux 5.8.0-1010-raspi aarch64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>  System information disabled due to load higher than 4.0
> 
>  * Introducing self-healing high availability clusters in MicroK8s.
>    Simple, hardened, Kubernetes for production, from RaspberryPi to DC.
> 
>      https://microk8s.io/high-availability
> 
> 0 updates can be installed immediately.
> 0 of these updates are security updates.
> 
[10:27:55.624] Terminating local server
[10:27:55.632] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/<user>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:64405)
	at Timeout._onTimeout (/Users/<user>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:277390)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)
[10:27:55.634] Local server exit: 15
[10:27:55.640] ------
```

**Comment by kunickiaj** [comment]
This may be more related to `fish` shell as it seems that `ssh bash` does not work when `fish` is the default shell (however `ssh bash -c ls` does work).

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/2509
