### ISSUE TITLE
TypeError: Cannot create property 'configFilePath' on string

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode-remote-release#4250]
Only happens to one container. Tried removing ~/.vscode-server inside container but not working.
```
[2 ms] Remote-Containers 0.154.1 in VS Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523).
[15 ms] Start: Resolving Remote
[15 ms] Setting up container /simcent3

[16 ms] Start: Run: docker inspect --type container /simcent3
[51 ms] TypeError: Cannot create property 'configFilePath' on string '/home/sgao/Documents/'
        at S (/home/sgao/.vscode/extensions/ms-vscode-remote.remote-containers-0.154.1/dist/extension.js:1:780418)
        at async Object.t.findAttachConfigDocument (/home/sgao/.vscode/extensions/ms-vscode-remote.remote-containers-0.154.1/dist/extension.js:1:782656)
        at async /home/sgao/.vscode/extensions/ms-vscode-remote.remote-containers-0.154.1/dist/extension.js:1:687853

```

**Comment by xgdgsc** [comment]
Seems caused by a corrupt file inside `/home/sgao/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/imageConfigs` , it somehow became:
```
"/home/sgao/Documents/"/home/sgao/Documents/simulation/smodel"e"
```
Removing that and reconnect works.

**Comment by xgdgsc** [comment]
But now clicking "install in Container" on extension page has no effect.

**Comment by xgdgsc** [comment]
When I use another machine to open this container on this machine, installation of extension works.

**Comment by xgdgsc** [comment]
After that . Installation of extension from the machine works.

**Comment by chrmarti** [comment]
The corrupt config file is tracked with https://github.com/microsoft/vscode-remote-release/issues/4208.

Installing an extension should work independently of the above issue. This might be another bug. Is there anything in the console (`Help` > `Toggle Developer Tools`)?
