### ISSUE TITLE
Remote connection issue when remote shell is Fish and remote.SSH.useLocalServer is on

### ISSUE THREAD

**Issue by hgezim** [microsoft/vscode-remote-release#4270]
- VSCode Version: Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
- Local OS Version: 10.15.7 (19H114)
- Remote OS Version: No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. SSH to your remote server and install fish:
```
sudo apt-add-repository ppa:fish-shell/release-3
sudo apt-get update
sudo apt-get install fish
```
2. Add `/usr/bin/fish` (fish instructions say `/usr/local/bin/fish` so use whichever exists) to `/etc/shells`
3. `sudo chsh -s /usr/bin/fish <your user name>` or /usr/local/bin/fish if that's where your fish landed
4. Setup a remote connection with VS Code to that user for that user
5. Set `remote.SSH.useLocalServer` to `true` in your User VS Code settings
6. Attempt to connect to that remove server

## Results:
I get this error:

```
[10:26:55.024] Log Level: 1
[10:26:55.027] remote-ssh@0.62.0
[10:26:55.027] darwin x64
[10:26:55.029] SSH Resolver called for "ssh-remote+<my connection name>", attempt 1
[10:26:55.029] "remote.SSH.useLocalServer": true
[10:26:55.030] "remote.SSH.sshPath": undefined
[10:26:55.030] "remote.SSH.sshConfigurationFile": undefined
[10:26:55.030] "remote.SSH.useFlock": true
[10:26:55.031] "remote.SSH.lockfilesInTmp": false
[10:26:55.031] "remote.SSH.localServerDownload": auto
[10:26:55.031] "remote.SSH.remoteServerListenOnSocket": false
[10:26:55.031] "remote.SSH.showLoginTerminal": false
[10:26:55.032] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[10:26:55.032] SSH Resolver called for host: <my connection name>
[10:26:55.033] Setting up SSH remote "<my connection name>"
[10:26:55.038] Acquiring local install lock: /var/folders/6n/<random name>/T/vscode-remote-ssh-<my connection name>-install.lock
[10:26:55.052] Looking for existing server data file at /Users/<my local home>/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-<my connection name>-ea3859d4ba2f3e577a159bc91e3074c5d85c0523-0.62.0/data.json
[10:26:55.054] Using commit id "ea3859d4ba2f3e577a159bc91e3074c5d85c0523" and quality "stable" for server
[10:26:55.060] Install and start server if needed
[10:26:55.069] Checking ssh with "ssh -V"
[10:26:55.080] > OpenSSH_8.1p1, LibreSSL 2.7.3

[10:26:55.087] askpass server listening on /var/folders/6n/<random name>/T/vscode-ssh-askpass-f60555895d91c261054c8cf80d3c6e1d8d5f9a3c.sock
[10:26:55.087] Spawning local server with {"ipcHandlePath":"/var/folders/6n/<random name>/T/vscode-ssh-askpass-4cc90f02ec2979df1c45db571d306e8aa8c0814a.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","53727","-o","ConnectTimeout=30","<my connection name>"],"dataFilePath":"/Users/<my local home>/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-<my connection name>-ea3859d4ba2f3e577a159bc91e3074c5d85c0523-0.62.0/data.json"}
[10:26:55.087] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/<my local home>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/<my local home>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/6n/<random name>/T/vscode-ssh-askpass-f60555895d91c261054c8cf80d3c6e1d8d5f9a3c.sock"}
[10:26:55.095] Spawned 54225
[10:26:55.232] > local-server> Spawned ssh: 54226
[10:26:55.235] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[10:26:55.235] stderr> debug1: Reading configuration data /Users/<my local home>/.ssh/config
[10:26:55.235] stderr> debug1: /Users/<my local home>/.ssh/config line 1: Applying options for *
[10:26:55.236] stderr> debug1: /Users/<my local home>/.ssh/config line 6: Applying options for <my connection name>
[10:26:55.236] stderr> debug1: Reading configuration data /etc/ssh/ssh_config
[10:26:55.236] stderr> debug1: /etc/ssh/ssh_config line 47: Applying options for *
[10:26:55.236] stderr> debug1: auto-mux: Trying existing master
[10:26:55.237] stderr> debug1: Requesting forwarding of dynamic forward LOCALHOST:53727 -> *
[10:27:27.097] Terminating local server
[10:27:27.107] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/<my local home>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:64405)
	at Timeout._onTimeout (/Users/<my local home>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:277390)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)
[10:27:27.110] Local server exit: 15
[10:27:27.114] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"Timeout","exitCodeLabel":"","osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"1"},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":32071,"timing.preSshTime":58}}
[10:27:27.116] ------
```

## Expected results

I expected the connection to be established. I increased `remote.SSH.connectTimeout` from 30 to 120 and nothing changes.

Setting `remote.SSH.useLocalServer` to `false` fixes the connection issue.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/2509
