### ISSUE TITLE
'Failed to parse remote port from server output' Error

### ISSUE THREAD

**Issue by nick-h-123** [microsoft/vscode-remote-release#4276]
- VSCode Version: 1.52.1
- Local OS Version: Windows 10.0.19042
- Remote Extension/Connection Type: SSH

I'm trying to connect to remote SSH. After selecting the remote platform, I'm getting this error.

[22:05:27.998] Terminal shell path: C:\Windows\System32\cmd.exe
[22:05:49.254] > ssh: connect to host kepler.physics.hmc.edu port 22: Connection timed out
> ]0;C:\Windows\System32\cmd.exe
[22:05:49.255] Got some output, clearing connection timeout
[22:05:49.801] "install" terminal command done
[22:05:49.801] Install terminal quit with output: ]0;C:\Windows\System32\cmd.exe
[22:05:49.801] Received install output: ]0;C:\Windows\System32\cmd.exe
[22:05:49.802] Stopped parsing output early. Remaining text: ]0;C:\Windows\System32\cmd.exe
[22:05:49.802] Failed to parse remote port from server output
[22:05:49.807] Resolver error: Error: 
	at Function.Create (c:\Users\HMCUser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:64276)
	at Object.t.handleInstallOutput (c:\Users\HMCUser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:61061)
	at I (c:\Users\HMCUser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:311112)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\HMCUser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:309029
	at async Object.t.withShowDetailsEvent (c:\Users\HMCUser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:403706)
	at async Object.t.resolve (c:\Users\HMCUser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:312426)
	at async c:\Users\HMCUser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:127:110280
[22:05:49.815] ------

**Comment by Silverazz** [comment]
I have exactly the same problem...

**Comment by AlexZhou1995** [comment]
me  too

**Comment by Meralis40** [comment]
I have the same problem with 0.63.0. Using 0.62.0 works for me

**Comment by bndgyawali** [comment]
I am having this problem in macOS Big Sur 11.2.1. It was working fine when I was in Mojave and stopped working as soon as I upgrade my OS.

**Comment by roblourens** [comment]
`ssh: connect to host kepler.physics.hmc.edu port 22: Connection timed out` This simply says that ssh couldn't connect to your host. Does it work in an external terminal?

Also people having this issue, please share the full log. Can't do much without a log.

**Comment by bndgyawali** [comment]
Here's the full log. 
```
[11:08:06.721] Log Level: 2
[11:08:06.723] remote-ssh@0.64.0
[11:08:06.723] darwin x64
[11:08:06.724] SSH Resolver called for "ssh-remote+XXXXXSERVER.org", attempt 1
[11:08:06.725] "remote.SSH.useLocalServer": true
[11:08:06.725] "remote.SSH.sshPath": undefined
[11:08:06.725] "remote.SSH.sshConfigurationFile": undefined
[11:08:06.725] "remote.SSH.useFlock": true
[11:08:06.725] "remote.SSH.lockfilesInTmp": false
[11:08:06.725] "remote.SSH.localServerDownload": auto
[11:08:06.725] "remote.SSH.remoteServerListenOnSocket": false
[11:08:06.726] "remote.SSH.showLoginTerminal": false
[11:08:06.726] "remote.SSH.defaultExtensions": []
[11:08:06.726] SSH Resolver called for host: XXXXXSERVER.org
[11:08:06.726] Setting up SSH remote "XXXXXSERVER.org"
[11:08:06.729] Acquiring local install lock: /var/folders/t4/7dt_7qp17hnbfrnsybq4wmwm0000gq/T/vscode-remote-ssh-XXXXXSERVER.org-install.lock
[11:08:06.742] Looking for existing server data file at /Users/bgyawali/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-XXXXXSERVER.org-622cb03f7e070a9670c94bae1a45d78d7181fbd4-0.64.0/data.json
[11:08:06.742] Using commit id "622cb03f7e070a9670c94bae1a45d78d7181fbd4" and quality "stable" for server
[11:08:06.746] Install and start server if needed
[11:08:06.749] Checking ssh with "ssh -V"
[11:08:06.763] > OpenSSH_8.1p1, LibreSSL 2.7.3

[11:08:06.767] askpass server listening on /var/folders/t4/7dt_7qp17hnbfrnsybq4wmwm0000gq/T/vscode-ssh-askpass-34d4ac98022e4cb2a69cdeed76ed298044cff22b.sock
[11:08:06.768] Spawning local server with {"ipcHandlePath":"/var/folders/t4/7dt_7qp17hnbfrnsybq4wmwm0000gq/T/vscode-ssh-askpass-f88123285c6a37f6afd6b77a73d7db367d532542.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","55695","-o","ConnectTimeout=15","XXXXXSERVER.org"],"dataFilePath":"/Users/bgyawali/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-XXXXXSERVER.org-622cb03f7e070a9670c94bae1a45d78d7181fbd4-0.64.0/data.json"}
[11:08:06.768] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/bgyawali/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/bgyawali/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/t4/7dt_7qp17hnbfrnsybq4wmwm0000gq/T/vscode-ssh-askpass-34d4ac98022e4cb2a69cdeed76ed298044cff22b.sock"}
[11:08:06.771] Spawned 71654
[11:08:06.911] > local-server> Spawned ssh: 71656
[11:08:06.915] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[11:08:07.397] stderr> ssh: connect to host XXXXXSERVER.org port 22: Bad file descriptor
[11:08:07.398] > local-server> ssh child died, shutting down
[11:08:07.402] Local server exit: 0
[11:08:07.402] Received install output: OpenSSH_8.1p1, LibreSSL 2.7.3
ssh: connect to host XXXXXSERVER.org port 22: Bad file descriptor

[11:08:07.402] Stopped parsing output early. Remaining text: OpenSSH_8.1p1, LibreSSL 2.7.3ssh: connect to host XXXXXSERVER.org port 22: Bad file descriptor
[11:08:07.403] Failed to parse remote port from server output
[11:08:07.408] Resolver error: Error: 
    at Function.Create (/Users/bgyawali/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:64126)
    at Object.t.handleInstallOutput (/Users/bgyawali/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:62865)
    at Object.t.tryInstallWithLocalServer (/Users/bgyawali/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:405581)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/bgyawali/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:310867
    at async Object.t.withShowDetailsEvent (/Users/bgyawali/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:406337)
    at async /Users/bgyawali/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:404105
    at async S (/Users/bgyawali/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:400873)
    at async Object.t.resolveWithLocalServer (/Users/bgyawali/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:403732)
    at async Object.t.resolve (/Users/bgyawali/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:314879)
    at async /Users/bgyawali/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:127:110431
[11:08:07.411] ------




[11:08:07.768] Unhandled rejection: Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[11:08:07.776] Unhandled rejection: Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[11:38:07.793] Unhandled rejection: Error: getaddrinfo ENOTFOUND default.exp-tas.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
[12:47:10.543] Unhandled rejection: Error: getaddrinfo ENOTFOUND default.exp-tas.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
[13:36:47.452] Unhandled rejection: Error: getaddrinfo ENOTFOUND default.exp-tas.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
[14:06:47.433] Unhandled rejection: Error: getaddrinfo ENOTFOUND default.exp-tas.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
```

**Comment by roblourens** [comment]
ssh is producing a different error for you: `ssh: connect to host XXXXXSERVER.org port 22: Bad file descriptor` no clue where that's coming from.

Same question for you: Does it work in an external terminal?

**Comment by bndgyawali** [comment]
I started getting this error because i had upgraded from Mojave to BigSur. It did work in external terminal. However, now I reinstalled vscode, it has started working.
