### ISSUE TITLE
Can not ssh remote machine using a jump server

### ISSUE THREAD

**Issue by serend1p1ty** [microsoft/vscode-remote-release#4283]
Hello everyone, great plugin! But I met a tough issue.

I want to connect to the target server `target.server.com` using a jump server `jump.server.com` like this:

```
Local machine --> jump.server.com --> target.server.com
```

Purely terminal ops without VSCode:

1. ssh jump server, input password, and 6 digits MFA auth.
```
➜  ssh username@jump.server.com
jump.server.com's password: 
Please enter 6 digits.
[MFA auth]: 123456
```
2. Pop up an interface for me to make a choice. Then I press `1`
![image](https://user-images.githubusercontent.com/39628662/104113776-e11ccd80-5337-11eb-9d76-b8b885aca80f.png)
3. Pop up an interface again. Then I press `1`
![image](https://user-images.githubusercontent.com/39628662/104114022-a36d7400-533a-11eb-955a-4f25e081a24d.png)
4. Then I connect to the target server successfully.

To implement this process, I write an ssh configuration refer to [remote-ssh-tips-and-tricks](https://code.visualstudio.com/blogs/2019/10/03/remote-ssh-tips-and-tricks)

```
# Jump box with public IP address
Host jump-box
    HostName jump.server.com
    User username

# Target machine with private IP address
Host target-box
    HostName target.server.com
    User username
    ProxyCommand ssh -q -W %h:%p jump-box
```

and some configs in `settings.json`

```
"remote.SSH.showLoginTerminal": true,
"remote.SSH.useLocalServer": false,
``` 

Then I tried to ssh target server. Firstly, VSCode terminal pop up an interface for me to input password and MFA auth.

![image](https://user-images.githubusercontent.com/39628662/104113987-31952a80-533a-11eb-8e16-05f359b208c8.png)

Then the connection is crush.

```
[11:44:15.107] Log Level: 2
[11:44:15.111] remote-ssh@0.62.0
[11:44:15.112] darwin x64
[11:44:15.114] SSH Resolver called for "ssh-remote+target-box", attempt 1
[11:44:15.115] "remote.SSH.useLocalServer": false
[11:44:15.115] "remote.SSH.showLoginTerminal": true
[11:44:15.115] "remote.SSH.sshPath": undefined
[11:44:15.115] "remote.SSH.sshConfigurationFile": undefined
[11:44:15.116] "remote.SSH.useFlock": true
[11:44:15.116] "remote.SSH.lockfilesInTmp": false
[11:44:15.116] "remote.SSH.localServerDownload": auto
[11:44:15.116] "remote.SSH.remoteServerListenOnSocket": false
[11:44:15.116] "remote.SSH.showLoginTerminal": true
[11:44:15.116] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[11:44:15.117] SSH Resolver called for host: target-box
[11:44:15.117] Setting up SSH remote "target-box"
[11:44:15.142] Using commit id "ea3859d4ba2f3e577a159bc91e3074c5d85c0523" and quality "stable" for server
[11:44:15.171] Install and start server if needed
[11:44:17.446] Checking ssh with "ssh -V"
[11:44:17.463] > OpenSSH_8.1p1, LibreSSL 2.7.3

[11:44:17.468] Running script with connection command: ssh -T -D 50162 -o ConnectTimeout=15 'target-box' bash
[11:44:17.971] > username@jump.server.com's password: 
[11:44:17.971] Got some output, clearing connection timeout
[11:44:22.119] > 
[11:44:22.369] > [MFA auth]: 
[11:44:22.986] > 1
[11:44:23.067] > 2
[11:44:23.187] > 3
[11:44:23.818] > 4
[11:44:24.407] > 5
[11:44:24.854] > 6
[11:44:25.055] > 
[11:44:25.540] > kex_exchange_identification: Connection closed by remote host
[11:44:25.946] "install" terminal command done
[11:44:25.948] Install terminal quit with output: kex_exchange_identification: Connection closed by remote host
[11:44:25.948] Received install output: kex_exchange_identification: Connection closed by remote host
[11:44:25.949] Stopped parsing output early. Remaining text: kex_exchange_identification: Connection closed by remote host
[11:44:25.949] Failed to parse remote port from server output
[11:44:25.954] Resolver error: Error: 
	at Function.Create (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:64276)
	at Object.t.handleInstallOutput (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:61061)
	at I (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:311112)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:309029
	at async Object.t.withShowDetailsEvent (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:403706)
	at async Object.t.resolve (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:312426)
	at async /Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:127:110280
[11:44:25.961] ------
```

- VSCode Version: Latest
- Local OS Version: MacOS
- Remote OS Version: Ubuntu 16.04
- Remote Extension/Connection Type: SSH

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by serend1p1ty** [comment]
This question has nothing to do with this plugin.

Change another jump server works for me.
