### ISSUE TITLE
Failed to pars remote port from sever output

### ISSUE THREAD

**Issue by adicoingitgub** [microsoft/vscode-remote-release#4284]
Hello,
This bug was opened already (#3301) but no solution that works for me was offered.
Trying to start SSH connection and get the following error:

![image](https://user-images.githubusercontent.com/73114585/104116117-6e532880-531e-11eb-9865-cea9200a615f.png)

[09:21:51.621] Log Level: 2
[09:21:51.627] remote-ssh@0.61.0
[09:21:51.627] win32 x64
[09:21:51.628] SSH Resolver called for "ssh-remote+[stromboli.tau.ac.il]", attempt 1
[09:21:51.628] "remote.SSH.useLocalServer": false
[09:21:51.628] "remote.SSH.showLoginTerminal": true
[09:21:51.628] "remote.SSH.remotePlatform": {}
[09:21:51.628] "remote.SSH.sshPath": undefined
[09:21:51.628] "remote.SSH.sshConfigurationFile": C:\Users\YanivA01\.ssh\config
[09:21:51.629] "remote.SSH.useFlock": true
[09:21:51.629] "remote.SSH.lockfilesInTmp": false
[09:21:51.629] "remote.SSH.localServerDownload": auto
[09:21:51.629] "remote.SSH.remoteServerListenOnSocket": true
[09:21:51.629] "remote.SSH.showLoginTerminal": true
[09:21:51.629] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[09:21:51.629] SSH Resolver called for host: [stromboli.tau.ac.il]
[09:21:51.629] Setting up SSH remote "[stromboli.tau.ac.il]"
[09:21:51.653] Using commit id "d2e414d9e4239a252d1ab117bd7067f125afd80a" and quality "stable" for server
[09:21:51.656] Install and start server if needed
[09:21:52.459] Checking ssh with "ssh -V"
[09:21:52.507] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[09:21:52.511] Using SSH config file "C:\Users\YanivA01\.ssh\config"
[09:21:52.512] Running script with connection command: ssh -T -D 65502 -F "C:\Users\YanivA01\.ssh\config" "[stromboli.tau.ac.il]" bash
[09:21:52.516] Terminal shell path: C:\Windows\System32\cmd.exe
[09:21:52.631] > ssh: Could not resolve hostname [stromboli.tau.ac.il]: No such host is known.
> ]0;C:\Windows\System32\cmd.exe
[09:21:52.632] Got some output, clearing connection timeout
[09:21:52.642] > The process tried to write to a nonexistent pipe.
[09:21:52.963] "install" terminal command done
[09:21:52.963] Install terminal quit with output: ]0;C:\Windows\System32\cmd.exeThe process tried to write to a nonexistent pipe.
[09:21:52.963] Received install output: ]0;C:\Windows\System32\cmd.exeThe process tried to write to a nonexistent pipe.
[09:21:52.968] Resolver error: Error: The process tried to write to a nonexistent pipe
	at Function.Offline (c:\Users\YanivA01\.vscode\extensions\ms-vscode-remote.remote-ssh-0.61.0\out\extension.js:1:82376)
	at c:\Users\YanivA01\.vscode\extensions\ms-vscode-remote.remote-ssh-0.61.0\out\extension.js:1:77835
	at Object.t.handleInstallOutput (c:\Users\YanivA01\.vscode\extensions\ms-vscode-remote.remote-ssh-0.61.0\out\extension.js:1:78213)
	at I (c:\Users\YanivA01\.vscode\extensions\ms-vscode-remote.remote-ssh-0.61.0\out\extension.js:127:107056)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\YanivA01\.vscode\extensions\ms-vscode-remote.remote-ssh-0.61.0\out\extension.js:127:104971
	at async Object.t.withShowDetailsEvent (c:\Users\YanivA01\.vscode\extensions\ms-vscode-remote.remote-ssh-0.61.0\out\extension.js:127:110308)
	at async Object.t.resolve (c:\Users\YanivA01\.vscode\extensions\ms-vscode-remote.remote-ssh-0.61.0\out\extension.js:127:108372)
	at async c:\Users\YanivA01\.vscode\extensions\ms-vscode-remote.remote-ssh-0.61.0\out\extension.js:127:129627
[09:21:52.971] ------

![image](https://user-images.githubusercontent.com/73114585/104116910-79f61d80-5325-11eb-9403-7cdb4c9501a3.png)

Also, the connection works if typing adirivkac@stromboli.tau.ac.il at the terminal....
Any ideas?
Thank you so much!

**Comment by roblourens** [comment]
Somehow you end up with your host in brackets `ssh: Could not resolve hostname [stromboli.tau.ac.il]: No such host is known` please check your ssh config

**Comment by faustvault** [comment]
Possible workaround,

I had a similar issue, I was unable to do a `ProxyJump` to a container on a remote machine (failed connections from windows 10 machine, the ssh-config in question, with minor changes for Windows was previously tested config on Linux & Mac machines, worked perfectly) 

My console output is pretty much the same as stated in #4284 by @adicoingitgub so I would dig into the ssh config

So, I found this [answer on serverfault](https://serverfault.com/a/956614) by @johnymachine (thanks much ♥) with a reference to this [bug on Win32-OpenSSH (issue 1185)](https://github.com/PowerShell/Win32-OpenSSH/issues/1185) 

Excerpt:
> ... the fix is to use a full path. So this is the correct line in the .ssh/config:
> `ProxyCommand  C:\Windows\System32\OpenSSH\ssh.exe jumphost netcat -w 120 %h %p`
> For further development see this issue: https://github.com/microsoft/vscode-remote-release/issues/18

So I changed `ProxyJump myownjumphost` to `ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -W %h:%p myownjumphost`, worked perfectly. Hope it helps a bit.
