### ISSUE TITLE
Large number of reconnect failures

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#4287]
Issue Type: <b>Bug</b>

I see a large number of reconnect issues with Remote-SSH. This seems to happen while I'm using the machine or when it is idle. Most of them are transparent to me, but I also see permanent disconnect way  more often than in the past. I run on an Apple M1 Mac. Not sure that makes a difference. It also correlates with us enabling compression,

[Log-window-reconnection.log](https://github.com/microsoft/vscode-remote-release/files/5799616/Log-window-reconnection.log)

Extension version: 2021.1.8132
VS Code version: Code - Insiders 1.53.0-insider (3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e, 2021-01-11T05:14:18.990Z)
OS version: Darwin arm64 20.2.0
Remote OS version: Linux x64 5.4.0-1031-azure
Fetching remote diagnostics for 'SSH: az-devbox' failed: Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv|--crash-reporter-id ef10dfea-3602-4c74-ba1a-109ce7da7825|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.4.0-1031-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (8.72GB free)|
|VM|0%|

Fetching remote diagnostics for 'SSH: az-devbox' failed: Canceled
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30208929
wsl2prompt:30219162
vstry244:30230484
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenu:30219168
pythonvsded773:30223139
pythonvspyt875:30241730
core-portspanel:30233467

```

</details>

**Comment by alexdima** [comment]
Looking at the logs, here is what I think happened:
* around 7:23, both management and extension host connections got disconnected
* around 7:26, the management connection managed to reconnect
* the extension host connection never managed to reconnect; the 30s time limit is always reached, indicating that the socket did not finish opening and the handshake did not complete within 30s.
* around 7:58, the management connection gets disconnected again
* around 7:59 the management connection managed to reconnect.
* around 9:40, the management connection gets disconnected again
* around 9:41, the management connection managed to reconnect
* after trying for 3h, at 10:23, the extension host connection gives up and a permanent connection error occurs.

The same pattern repeats starting at 16:42, with the management connection managing to reconnect, but then after 3h the server kills the corresponding remote ext host process at 18:49 (perhaps the disconnection was detected 1h later on the client side).

This indicates to me a problem specific to the extension host reconnection part, since the management connection manages to reconnect. I cannot say exactly what is going on, it is possible that there is a bug in the socket transfer logic (from the server process to the extension host process) or it is also possible that the extension host process becomes unhealthy/unresponsive.

@kieferrm As always, more information would be very helpful, like what extensions were running remotely and what is the server perspective on the matter. The server logs can be found in `$HOME/.vscode-server-insider`. Also, what version of vscode were you using?

**Comment by roblourens** [comment]
I haven't been using remote much lately since I've been in the codespaces repos, but I opened a remote window this morning and got a permanent disconnection while my macbook was asleep for a bit, with logs that look similar.

Unfortunately I tried to get the server log by connecting with vscode which obviously overwrote the previous server log so I have to wait for it to happen again. This is today's insiders. No unusual extensions

![image](https://user-images.githubusercontent.com/323878/104353726-1acb1100-54bd-11eb-89f4-e96f0abf8213.png)

**Comment by kieferrm** [comment]
Attached are all the logs from today. Since I update VS Code Insiders to the latest version this morning I had one local and one remote window open. The remote window is **not** disconnected right now and it is working as expected. Indeed, I collected and edited the attached logs in that window,  i.e. extensions work, I edit, etc.

However, the logs show the same pattern as yesterday. Constant reconnect failures.
[connection-issues.zip](https://github.com/microsoft/vscode-remote-release/files/5804044/connection-issues.zip)

**Comment by roblourens** [comment]
Happened again, here is the server log from `~/.vscode-server-insiders/.6dc779565e1e4a26104002fde340b68c157c3bc5.log` 

[serverlog.log](https://github.com/microsoft/vscode-remote-release/files/5805657/serverlog.log)

It shows this pattern on every reconnection

```
[13:09:35] [127.0.0.1][3a8dae4e][ManagementConnection] The client has reconnected.
[13:10:01] [127.0.0.1][1c706505][ExtensionHostConnection] The client has reconnected.
Error [ERR_SOCKET_CLOSED]: Socket is closed
    at Socket._writeGeneric (net.js:776:8)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at f.write (/home/roblou/.vscode-server-insiders/bin/6dc779565e1e4a26104002fde340b68c157c3bc5/out/vs/server/remoteExtensionHostAgent.js:105:98900)
    at v._write (/home/roblou/.vscode-server-insiders/bin/6dc779565e1e4a26104002fde340b68c157c3bc5/out/vs/server/remoteExtensionHostAgent.js:105:102571)
    at /home/roblou/.vscode-server-insiders/bin/6dc779565e1e4a26104002fde340b68c157c3bc5/out/vs/server/remoteExtensionHostAgent.js:105:101818
    at afterWrite (_stream_writable.js:490:5)
    at onwrite (_stream_writable.js:470:7)
    at DeflateRaw.afterTransform (_stream_transform.js:98:3)
    at Zlib.processCallback (zlib.js:578:8) {
  code: 'ERR_SOCKET_CLOSED'
```

which makes it looks like something is wrong with the extension host connection. It looks like it was reconnecting all afternoon but only disconnected when my macbook was asleep.

**Comment by alexdima** [comment]
I can reproduce directly, even without the SSH resolver.
