### ISSUE TITLE
Extension not activated as expected in newly created Codespaces

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-remote-release#4288]
I was using GitHub Codespaces. I created new codespaces with a [repo](https://github.com/Eskibear/maven-quickstart-project) of a simple Maven project. 
**Sometimes** Java extension is not activated as expected. I suspect if there's something was wrong during extension installation. And if I reload the window, everything works fine then. 

### Some Context Information
[Java Extension Pack](https://github.com/microsoft/vscode-java-pack) will be installed into the codespace when I open it for the first time. The structure of this extension pack is as below:
```
- Java Extension Pack
| -- Language Support for Java (redhat.java) 
| -- Debugger for Java (vscode-java-debug)
| -- Java Test Runner (vscode-java-test): depending on `redhat.java` and `vscode-java-debug`
| -- Maven for Java 
| -- Project Manager for Java
| -- IntelliCode
```

Language Support for Java (redhat.java) will be activated on opening .java files.

### Error Logs
I have some logs for the session on 2021/1/11. `redhat.java` was installed but not activated (I've checked Developer: Running Extensions) when I open a .java file. (it should be activated) [codespaces-error-log-java-extension-not-activated.zip](https://github.com/microsoft/vscode-remote-release/files/5800457/codespaces-error-log-java-extension-not-activated.zip)

From the logs, I find some clues, please take a look see if that's useful:

In **Log(Remote Extension)**: I see an error and its callstack
```
[2021-01-11 09:12:22.387] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/codespace/.vscode-remote/extensions/redhat.java-0.73.0/dist/extension
[2021-01-11 09:12:22.387] [exthost] [error] Activating extension redhat.java failed due to an error:
[2021-01-11 09:12:22.393] [exthost] [error] Error: Cannot find module '/home/codespace/.vscode-remote/extensions/redhat.java-0.73.0/dist/extension'
Require stack:
- /home/codespace/.vscode-remote/bin/3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e/out/vs/loader.js
- /home/codespace/.vscode-remote/bin/3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e/out/bootstrap-amd.js
- /home/codespace/.vscode-remote/bin/3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e/out/bootstrap-fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.o._load (/home/codespace/.vscode-remote/bin/3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e/out/vs/server/remoteExtensionHostProcess.js:104:26480)
    at Function.p._load (/home/codespace/.vscode-remote/bin/3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e/out/vs/server/remoteExtensionHostProcess.js:104:23247)
    at Function.L._load (/home/codespace/.vscode-remote/bin/3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e/out/vs/server/remoteExtensionHostProcess.js:94:61486)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Function.t [as __$__nodeRequire] (/home/codespace/.vscode-remote/bin/3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e/out/vs/loader.js:4:101)
    at f._loadCommonJSModule (/home/codespace/.vscode-remote/bin/3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e/out/vs/server/remoteExtensionHostProcess.js:104:24639)
    at f._doActivateExtension (/home/codespace/.vscode-remote/bin/3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e/out/vs/server/remoteExtensionHostProcess.js:90:11524)
    at f._activateExtension (/home/codespace/.vscode-remote/bin/3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e/out/vs/server/remoteExtensionHostProcess.js:90:10583)
    at Object.actualActivateExtension (/home/codespace/.vscode-remote/bin/3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e/out/vs/server/remoteExtensionHostProcess.js:90:8251)
    at m._activateExtension (/home/codespace/.vscode-remote/bin/3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e/out/vs/server/remoteExtensionHostProcess.js:86:63109)
    at /home/codespace/.vscode-remote/bin/3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e/out/vs/server/remoteExtensionHostProcess.js:86:62791
    at Array.map (<anonymous>)
    at m._activateExtensions (/home/codespace/.vscode-remote/bin/3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e/out/vs/server/remoteExtensionHostProcess.js:86:62779)
    at m.activateById (/home/codespace/.vscode-remote/bin/3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e/out/vs/server/remoteExtensionHostProcess.js:86:60645)
    at f._activateById (/home/codespace/.vscode-remote/bin/3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e/out/vs/server/remoteExtensionHostProcess.js:90:9208)
    at f.$activate (/home/codespace/.vscode-remote/bin/3ceb3a100ed0ad5f3238b5022d9d64353a1cc31e/out/vs/server/remoteExtensionHostProcess.js:90:18669)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

In **Log(Remote Server)**: it was tring installing `redhat.java` for multiple times...and I don't know if that's related.
```log
[2021-01-11 09:12:19.795] [remoteagent] [info] Rename failed. Deleting from extracted location /home/codespace/.vscode-remote/extensions/.visualstudioexptteam.vscodeintellicode-1.2.10
<--!! HERE is an error ---> 
[2021-01-11 09:12:19.795] [remoteagent] [error] Failed to install extension: visualstudioexptteam.vscodeintellicode ENOTEMPTY: directory not empty, rename '/home/codespace/.vscode-remote/extensions/.visualstudioexptteam.vscodeintellicode-1.2.10' -> '/home/codespace/.vscode-remote/extensions/visualstudioexptteam.vscodeintellicode-1.2.10'
<--!! HERE is 1st time installing redhat.java --->
[2021-01-11 09:12:20.738] [remoteagent] [info] Installing extension: redhat.java
[2021-01-11 09:12:20.756] [remoteagent] [info] Downloaded extension: redhat.java undefined
[2021-01-11 09:12:21.721] [remoteagent] [info] Extracted extension to /home/codespace/.vscode-remote/extensions/.redhat.java-0.73.0: redhat.java
[2021-01-11 09:12:21.721] [remoteagent] [info] Renamed to /home/codespace/.vscode-remote/extensions/redhat.java-0.73.0
[2021-01-11 09:12:21.722] [remoteagent] [info] Installation completed. redhat.java
[2021-01-11 09:12:21.740] [remoteagent] [info] Extensions installed successfully: redhat.java
<--!! HERE it tried install redhat.java for a 2nd time??? --->
[2021-01-11 09:12:22.156] [remoteagent] [info] Installing extension: redhat.java
[2021-01-11 09:12:22.165] [remoteagent] [info] Downloaded extension: redhat.java undefined
[2021-01-11 09:12:22.716] [remoteagent] [info] Installing extension: vscjava.vscode-java-debug
[2021-01-11 09:12:22.739] [remoteagent] [info] Downloaded extension: vscjava.vscode-java-debug undefined
```

- VSCode Version: 1.53.0-insiders I guess (which is used by Codespaces from "About" dialog)
- Remote Extension/Connection Type: GitHub Codespaces

**Comment by Eskibear** [comment]
BTW, sometimes we see below error:

![image](https://user-images.githubusercontent.com/2351748/104285301-63e78900-54ee-11eb-96f7-32ccf9c8c7ae.png)

> | -- Debugger for Java (vscode-java-debug)
| -- Java Test Runner (vscode-java-test): depending on `redhat.java` and `vscode-java-debug`

As you see the dependencies above, it's strange because when Java Extension Pack is installed, all the above extensions should be installed. All I can think of is, VS Code attempted to activate Test Runner before installation of Debugger was completed? e.g. The sequence was:
```
install "test runner" and "debugger"
finish installation of "test runner"
[error] try activate "test runner", but no "debugger" found.
---------below not happened yet------------
finish installation of "debug"
```
Is that possible?

Although the error will probably be gone after you reload the window, it does harm the user experience for the first time.

**Comment by roblourens** [comment]
Any idea what happened @sandy081 or do we send this to the codespaces team?

**Comment by sandy081** [comment]
Forwarding to @alexdima as he knows much about extension activation and runtime/

**Comment by alexdima** [comment]
The root cause here is that `redhat.java` could not be activated because its disk installation appears to be corrupt. It is missing its "main" file on disk, `redhat.java-0.73.0/dist/extension.js`. Other extensions that depend on this extension will also fail to activate, this is expected. I agree that it is weird to get a prompt for the second error and not get a prompt for the initial root cause error.

@sandy081 The remote server log shows that there were multiple attempts to install the redhat.java extension and that there was also another error while installing the `vscodeintellicode` extension. This to me indicates that perhaps there are two distinct processes or pieces of code that try to install the same extensions at the same location. So I believe this is an installation problem.

**Comment by sandy081** [comment]
Sorry @alexdima for forwarding. I see there are errors while installing.

@Eskibear Is it possible to reproduce this?

**Comment by Eskibear** [comment]
I cannot stably reproduce it. The issue occurs occasionally and disappears after reloading. 
Let me know what information/logs you need for your hypotheses, so I might be able to share more detailed information next time when it occurs.

**Comment by sandy081** [comment]
When it happens next time, please provide the complete remote server log.

**Comment by yaojinyang** [comment]
In my last test on Jan/25, I hit the same issue. How can I find the complete remote server log? I will try to do an test and reproduce.
