### ISSUE TITLE
Error while loading extensions. Cannot connect to Extensions Marketplace at this time.

### ISSUE THREAD

**Issue by jonaslimhx** [microsoft/vscode-remote-release#4302]
SSH-installed. Error while loading extensions. Connecting SSH timed out.
We cannot connect to the Extensions Marketplace at this time, please try again later.

Using putty or Windows power shell, I can able to connect to the fslhdppclient01 linux server. 
Already installed the open ssh client. Unsure why this problem is happening. Please advise. 

[13:45:28.178] Log Level: 2
[13:45:28.189] remote-ssh@0.62.0
[13:45:28.189] win32 x64
[13:45:28.190] SSH Resolver called for "ssh-remote+fslhdppclient01", attempt 1
[13:45:28.191] "remote.SSH.useLocalServer": false
[13:45:28.191] "remote.SSH.showLoginTerminal": false
[13:45:28.191] "remote.SSH.remotePlatform": {}
[13:45:28.191] "remote.SSH.sshPath": undefined
[13:45:28.191] "remote.SSH.sshConfigurationFile": undefined
[13:45:28.191] "remote.SSH.useFlock": true
[13:45:28.191] "remote.SSH.lockfilesInTmp": false
[13:45:28.191] "remote.SSH.localServerDownload": auto
[13:45:28.192] "remote.SSH.remoteServerListenOnSocket": false
[13:45:28.192] "remote.SSH.showLoginTerminal": false
[13:45:28.192] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[13:45:28.192] SSH Resolver called for host: fslhdppclient01
[13:45:28.192] Setting up SSH remote "fslhdppclient01"
[13:45:28.210] Using commit id "ea3859d4ba2f3e577a159bc91e3074c5d85c0523" and quality "stable" for server
[13:45:28.213] Install and start server if needed
[13:45:29.225] Checking ssh with "ssh -V"
[13:45:29.429] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[13:45:29.447] Running script with connection command: ssh -T -D 58540 fslhdppclient01 bash
[13:45:29.452] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[13:46:01.462] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (c:\Users\jonaslimhx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:64405)
	at Timeout._onTimeout (c:\Users\jonaslimhx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:309982)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)
[13:46:01.471] ------

**Comment by npurson** [comment]
@jonaslimhx are you using jump server? I met same issue when using jump server and setting ssh configs like ```ProxyCommand ssh.exe -W %h:%p JumpServer```, and solved it by replacing with ```ProxyJump JumpServer```.

**Comment by jonaslimhx** [comment]
Thanks. Resolved it. I used the same computer to create a separate user profile and the ssh connection had no issue. 
Some settings on my user profile was causing this issue.
