### ISSUE TITLE
The VS Code Server failed to start - node: not found, albeit the binary exists?

### ISSUE THREAD

**Issue by omares** [microsoft/vscode-remote-release#4306]
I am unable to connect via SSH to a dockerized openssh-server. The `server.sh` exists with the error  `/config/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/server.sh: line 12: /config/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/node: not found`. When checking the directory a file with binary contents is present with execution rights. Trying to run the node binary fails with an error saying "No such file or directory.."

Any tip or ideas on how to fix the issue? Thanks!

```
openssh-server:~# ls -lah /config/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/node
-rwxr-xr-x 1 root root 38M Dec 16 16:56 /config/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/node

openssh-server:~# /config/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/node
-bash: /config/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/node: No such file or directory
```

- VSCode Version: `Version: 1.52.1, Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523`
- Local OS Version: `macOS Big Sur, Version 11.1 (20C69)`
- Remote OS Version: `Linux version 5.4.79-v7l+ (dom@buildbot) (gcc version 8.4.0 (Ubuntu/Linaro 8.4.0-3ubuntu1)) #1373 SMP Mon Nov 23 13:27:40 GMT 2020` via https://github.com/linuxserver/docker-openssh-server
- Remote Extension/Connection Type: `SSH`

Steps to Reproduce:

1. Select the appropriate SSH-Target, let the setup do its work an, and watch it fail

Full log output of the setup process

```
[23:00:12.576] Log Level: 2
[23:00:12.578] remote-ssh@0.62.0
[23:00:12.578] darwin x64
[23:00:12.579] SSH Resolver called for "ssh-remote+openssh-server", attempt 1
[23:00:12.580] "remote.SSH.useLocalServer": true
[23:00:12.580] "remote.SSH.sshPath": undefined
[23:00:12.580] "remote.SSH.sshConfigurationFile": undefined
[23:00:12.580] "remote.SSH.useFlock": true
[23:00:12.581] "remote.SSH.lockfilesInTmp": false
[23:00:12.581] "remote.SSH.localServerDownload": auto
[23:00:12.581] "remote.SSH.remoteServerListenOnSocket": false
[23:00:12.581] "remote.SSH.showLoginTerminal": true
[23:00:12.581] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[23:00:12.581] SSH Resolver called for host: openssh-server
[23:00:12.582] Setting up SSH remote "openssh-server"
[23:00:12.585] Acquiring local install lock: /var/folders/n6/gb7vy6_j1c10bg3fv00b72nh0000gn/T/vscode-remote-ssh-openssh-server-install.lock
[23:00:12.596] Looking for existing server data file at /Users/otamares/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-openssh-server-ea3859d4ba2f3e577a159bc91e3074c5d85c0523-0.62.0/data.json
[23:00:12.598] Using commit id "ea3859d4ba2f3e577a159bc91e3074c5d85c0523" and quality "stable" for server
[23:00:12.602] Install and start server if needed
[23:00:12.608] Checking ssh with "ssh -V"
[23:00:12.615] > OpenSSH_8.1p1, LibreSSL 2.7.3

[23:00:12.620] askpass server listening on /var/folders/n6/gb7vy6_j1c10bg3fv00b72nh0000gn/T/vscode-ssh-askpass-18d9f7f5f9f0e9d4a66389bf7825839c48d4e92a.sock
[23:00:12.620] Spawning local server with {"ipcHandlePath":"/var/folders/n6/gb7vy6_j1c10bg3fv00b72nh0000gn/T/vscode-ssh-askpass-d533980d5283870a19bcde490bc3727aebfdf9db.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","63427","-o","ConnectTimeout=15","openssh-server"],"dataFilePath":"/Users/otamares/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-openssh-server-ea3859d4ba2f3e577a159bc91e3074c5d85c0523-0.62.0/data.json"}
[23:00:12.620] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/otamares/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/otamares/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/n6/gb7vy6_j1c10bg3fv00b72nh0000gn/T/vscode-ssh-askpass-18d9f7f5f9f0e9d4a66389bf7825839c48d4e92a.sock"}
[23:00:12.623] Spawned 77855
[23:00:12.728] > local-server> Spawned ssh: 77856
[23:00:12.731] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[23:00:12.790] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:3eKTBZOe/qSwwi9cg51p5rViokRPTHH5C9V1nEKxY74
[23:00:12.853] stderr> Authenticated to 192.168.20.93 ([192.168.20.93]:2222).
[23:00:12.864] > ready: 5a9e6048fd9d
[23:00:12.870] > Linux 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020
[23:00:12.870] Platform: linux
[23:00:12.927] > 5a9e6048fd9d: running
[23:00:12.959] stderr> Illegal option -p
[23:00:12.967] stderr> musl libc (armhf)
[23:00:12.967] stderr> Version 1.1.24
[23:00:12.967] stderr> Dynamic Program Loader
[23:00:12.967] stderr> Usage: /lib/ld-musl-armhf.so.1 [options] [--] pathname
[23:00:12.968] > Missing GLIBC >= 2.17!
> Found version 
> 5a9e6048fd9d$$1$$
[23:00:12.972] > Acquiring lock on /config/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/vscode-remote-lock.otamares.ea3859d4ba2f3e577a159bc91e3074c5d85c0523
[23:00:12.980] > Installing to /config/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523...
[23:00:12.987] > 5a9e6048fd9d%%1%%
[23:00:13.005] > Downloading with curl
[23:00:13.014] stderr>   
[23:00:13.015] stderr> % 
[23:00:13.016] stderr> To
[23:00:13.017] stderr> tal    
[23:00:13.018] stderr> % R
[23:00:13.021] stderr> eceived % Xferd  Av
[23:00:13.021] stderr> erage S
[23:00:13.022] stderr> pe
[23:00:13.023] stderr> ed   Time  
[23:00:13.024] stderr>   Time     Time  Current
[23:00:13.024] stderr>                                  Dload  Upload   Total   Spent    Left  Speed
[23:00:13.024] stderr>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[23:00:13.158] stderr> 100   133  100   133    0     0    936      0 --:--:-- --:--:-- --:--:--   936
[23:00:13.972] stderr>  20 26.7M   20 5584k    0     0  5834k      0  0:00:04 --:--:--  0:00:04 5834k
[23:00:15.051] stderr>  58 26.7M   58 15.6M    0     0  8289k      0  0:00:03  0:00:01  0:00:02 10.4M
[23:00:15.950] stderr>  95 26.7M   95 25.5M    0     0  8921k      0  0:00:03  0:00:02  0:00:01 10.1M
[23:00:16.072] stderr> 100 26.7M  100 26.7M    0     0  8973k      0  0:00:03  0:00:03 --:--:-- 10.1M
[23:00:16.078] > Download complete
[23:00:16.091] > 5a9e6048fd9d%%2%%
> tar --version:
[23:00:16.092] > tar (busybox) 1.31.1
[23:00:18.925] > Checking /config/.vscode-server/.ea3859d4ba2f3e577a159bc91e3074c5d85c0523.log and /config/.vscode-server/.ea3859d4ba2f3e577a159bc91e3074c5d85c0523.pid for a running server
[23:00:18.940] > Starting server with command... /config/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/server.sh --start-server --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0  &> "/config/.vscode-server/.ea3859d4ba2f3e577a159bc91e3074c5d85c0523.log" < /dev/null
> printenv:
[23:00:18.942] >     SHELL=/bin/bash
>     SSH_AUTH_SOCK=/tmp/ssh-vT6tE3xR9B/agent.3565
>     PWD=/config
>     LOGNAME=otamares
>     TZ=Europe/Berlin
>     HOME=/config
>     VSCODE_AGENT_FOLDER=/config/.vscode-server
>     SSH_CONNECTION=10.0.0.2 63428 10.0.0.29 2222
>     USER=otamares
>     SHLVL=1
>     SSH_CLIENT=10.0.0.2 63428 2222
>     PATH=/bin:/usr/bin:/sbin:/usr/sbin
>     MAIL=/var/mail/otamares
>     OLDPWD=/config/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523
>     _=/bin/printenv
[23:00:18.950] > Spawned remote server: 3633
[23:00:18.958] > Waiting for server log...
[23:00:18.999] > Waiting for server log...
[23:00:19.038] > Waiting for server log...
[23:00:19.078] > Waiting for server log...
[23:00:19.119] > Waiting for server log...
[23:00:19.158] > Waiting for server log...
[23:00:19.197] > Waiting for server log...
[23:00:19.238] > Waiting for server log...
[23:00:19.280] > Waiting for server log...
[23:00:19.323] > Waiting for server log...
[23:00:19.367] > Waiting for server log...
[23:00:19.414] > Waiting for server log...
[23:00:19.460] > Waiting for server log...
[23:00:19.505] > Waiting for server log...
[23:00:19.554] > Waiting for server log...
[23:00:19.603] > Waiting for server log...
[23:00:19.650] > Waiting for server log...
[23:00:19.694] > Waiting for server log...
[23:00:19.741] > Waiting for server log...
[23:00:19.785] > Waiting for server log...
[23:00:19.832] > Waiting for server log...
[23:00:19.881] > Waiting for server log...
[23:00:19.926] > Waiting for server log...
[23:00:19.974] > Waiting for server log...
[23:00:20.021] > Waiting for server log...
[23:00:20.066] > Waiting for server log...
[23:00:20.114] > Waiting for server log...
[23:00:20.161] > Waiting for server log...
[23:00:20.208] > Waiting for server log...
[23:00:20.255] > Waiting for server log...
[23:00:20.302] > Waiting for server log...
[23:00:20.349] > Waiting for server log...
[23:00:20.396] > Waiting for server log...
[23:00:20.445] > Waiting for server log...
[23:00:20.491] > Waiting for server log...
[23:00:20.538] > Waiting for server log...
[23:00:20.585] > Waiting for server log...
[23:00:20.633] > Waiting for server log...
[23:00:20.680] > Waiting for server log...
[23:00:20.725] > Waiting for server log...
[23:00:20.772] > Waiting for server log...
[23:00:20.818] > Waiting for server log...
[23:00:20.865] > Waiting for server log...
[23:00:20.913] > Waiting for server log...
[23:00:20.958] > Waiting for server log...
[23:00:21.005] > Waiting for server log...
[23:00:21.052] > Waiting for server log...
[23:00:21.098] > Waiting for server log...
[23:00:21.144] > Waiting for server log...
[23:00:21.191] > Waiting for server log...
[23:00:21.238] > Waiting for server log...
[23:00:21.285] > Waiting for server log...
[23:00:21.333] > Waiting for server log...
[23:00:21.380] > Waiting for server log...
[23:00:21.425] > Waiting for server log...
[23:00:21.472] > Waiting for server log...
[23:00:21.519] > Waiting for server log...
[23:00:21.564] > Waiting for server log...
[23:00:21.610] > Waiting for server log...
[23:00:21.657] > Waiting for server log...
[23:00:21.704] > Waiting for server log...
[23:00:21.749] > Waiting for server log...
[23:00:21.795] > Waiting for server log...
[23:00:21.841] > Waiting for server log...
[23:00:21.889] > Waiting for server log...
[23:00:21.934] > Waiting for server log...
[23:00:21.981] > Waiting for server log...
[23:00:22.028] > Waiting for server log...
[23:00:22.075] > Waiting for server log...
[23:00:22.120] > Waiting for server log...
[23:00:22.166] > Waiting for server log...
[23:00:22.211] > Waiting for server log...
[23:00:22.258] > Waiting for server log...
[23:00:22.305] > Waiting for server log...
[23:00:22.352] > Waiting for server log...
[23:00:22.399] > Waiting for server log...
[23:00:22.444] > Waiting for server log...
[23:00:22.490] > Waiting for server log...
[23:00:22.535] > Waiting for server log...
[23:00:22.583] > Waiting for server log...
[23:00:22.631] > Waiting for server log...
[23:00:22.676] > Waiting for server log...
[23:00:22.721] > Waiting for server log...
[23:00:22.767] > Waiting for server log...
[23:00:22.815] > Waiting for server log...
[23:00:22.863] > Waiting for server log...
[23:00:22.911] > Waiting for server log...
[23:00:22.959] > Waiting for server log...
[23:00:23.005] > Waiting for server log...
[23:00:23.052] > Waiting for server log...
[23:00:23.099] > Waiting for server log...
[23:00:23.145] > Waiting for server log...
[23:00:23.191] > Waiting for server log...
[23:00:23.239] > Waiting for server log...
[23:00:23.285] > Waiting for server log...
[23:00:23.331] > Waiting for server log...
[23:00:23.378] > Waiting for server log...
[23:00:23.425] > Waiting for server log...
[23:00:23.472] > Waiting for server log...
[23:00:23.519] > Waiting for server log...
[23:00:23.564] > Waiting for server log...
[23:00:23.611] > Waiting for server log...
[23:00:23.658] > Waiting for server log...
[23:00:23.704] > Waiting for server log...
[23:00:23.751] > Waiting for server log...
[23:00:23.799] > Waiting for server log...
[23:00:23.845] > Waiting for server log...
[23:00:23.892] > Waiting for server log...
[23:00:23.939] > Waiting for server log...
[23:00:23.985] > Waiting for server log...
[23:00:24.032] > Waiting for server log...
[23:00:24.079] > Waiting for server log...
[23:00:24.124] > Waiting for server log...
[23:00:24.171] > Waiting for server log...
[23:00:24.217] > Waiting for server log...
[23:00:24.265] > Waiting for server log...
[23:00:24.310] > Waiting for server log...
[23:00:24.355] > Waiting for server log...
[23:00:24.403] > Waiting for server log...
[23:00:24.449] > Waiting for server log...
[23:00:24.496] > Waiting for server log...
[23:00:24.543] > Waiting for server log...
[23:00:24.589] > Waiting for server log...
[23:00:24.634] > Waiting for server log...
[23:00:24.680] > Waiting for server log...
[23:00:24.725] > Waiting for server log...
[23:00:24.772] > Waiting for server log...
[23:00:24.819] > Waiting for server log...
[23:00:24.865] > Waiting for server log...
[23:00:24.912] > Waiting for server log...
[23:00:24.959] > Waiting for server log...
[23:00:25.005] > Waiting for server log...
[23:00:25.052] > Waiting for server log...
[23:00:25.099] > Waiting for server log...
[23:00:25.145] > Waiting for server log...
[23:00:25.191] > Waiting for server log...
[23:00:25.236] > Waiting for server log...
[23:00:25.280] > Waiting for server log...
[23:00:25.325] > Waiting for server log...
[23:00:25.372] > Waiting for server log...
[23:00:25.419] > Waiting for server log...
[23:00:25.464] > Waiting for server log...
[23:00:25.512] > Waiting for server log...
[23:00:25.559] > Waiting for server log...
[23:00:25.626] > Waiting for server log...
[23:00:25.668] > Waiting for server log...
[23:00:25.713] > Waiting for server log...
[23:00:25.760] > Waiting for server log...
[23:00:25.806] > Waiting for server log...
[23:00:25.853] > Waiting for server log...
[23:00:25.898] > Waiting for server log...
[23:00:25.945] > Waiting for server log...
[23:00:25.991] > Waiting for server log...
[23:00:26.036] > Waiting for server log...
[23:00:26.082] > Waiting for server log...
[23:00:26.129] > Waiting for server log...
[23:00:26.175] > Waiting for server log...
[23:00:26.222] > Waiting for server log...
[23:00:26.268] > Waiting for server log...
[23:00:26.315] > Waiting for server log...
[23:00:26.362] > Waiting for server log...
[23:00:26.409] > Waiting for server log...
[23:00:26.455] > Waiting for server log...
[23:00:26.501] > Waiting for server log...
[23:00:26.546] > Waiting for server log...
[23:00:26.593] > Waiting for server log...
[23:00:26.641] > Waiting for server log...
[23:00:26.686] > Waiting for server log...
[23:00:26.734] > Waiting for server log...
[23:00:26.780] > Waiting for server log...
[23:00:26.829] > Waiting for server log...
[23:00:26.875] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
[23:00:26.875] > * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[23:00:26.897] > Server did not start successfully. Full server log at /config/.vscode-server/.ea3859d4ba2f3e577a159bc91e3074c5d85c0523.log >>>
[23:00:26.902] > /config/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/server.sh: line 12: /config/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/node: not found
[23:00:26.903] > <<< End of server log
> 5a9e6048fd9d: start
> exitCode==32==
[23:00:26.903] > listeningOn====
> osReleaseId==Linux==
> arch==armv7l==
> tmpDir==/tmp==
> platform==linux==
> unpackResult==success==
[23:00:26.904] > didLocalDownload==0==
> downloadTime==3097==
> installTime==2808==
> extInstallTime====
> serverStartTime==7924==
> 5a9e6048fd9d: end
[23:00:26.904] Received install output: 
exitCode==32==listeningOn====
osReleaseId==Linux==
arch==armv7l==
tmpDir==/tmp==
platform==linux==
unpackResult==success==didLocalDownload==0==
downloadTime==3097==
installTime==2808==
extInstallTime====
serverStartTime==7924==

[23:00:26.905] Terminating local server
[23:00:26.913] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (/Users/otamares/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:64207)
	at /Users/otamares/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:62459
	at Object.t.handleInstallOutput (/Users/otamares/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:63061)
	at Object.t.tryInstallWithLocalServer (/Users/otamares/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:402931)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /Users/otamares/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:308557
	at async Object.t.withShowDetailsEvent (/Users/otamares/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:403706)
	at async /Users/otamares/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:401486
	at async S (/Users/otamares/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:398276)
	at async Object.t.resolveWithLocalServer (/Users/otamares/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:401135)
	at async Object.t.resolve (/Users/otamares/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:312304)
	at async /Users/otamares/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:127:110280
[23:00:26.914] Local server exit: 15
[23:00:26.918] ------

```

Does this issue occur when you try this locally?: NA
Does this issue occur when you try this locally and all extensions are disabled?: NA

**Comment by roblourens** [comment]
> `> Missing GLIBC >= 2.17!`

It sounds like node doesn't like your libc. The right version is either missing or can't be found. Anything on this page useful? https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites

**Comment by omares** [comment]
The openssh-server image is based on Alpine 3.12. In case I understand the prerequisites, the container should have the packages `musl, libgcc, libstdc++` and `musl >= 1.1.18` installed. 
libgcc and libstdc++ have not been available, so I installed the packages manually, to see if it would fix the issue. Unfortunately still no luck, anything that I am missing?

```
root@openssh-server:/# apk info libgcc
libgcc-9.3.0-r2 description:
GNU C compiler runtime libraries

libgcc-9.3.0-r2 webpage:
https://gcc.gnu.org

libgcc-9.3.0-r2 installed size:
45056
```
```
root@openssh-server:/# apk info libstdc++
libstdc++-9.3.0-r2 description:
GNU C++ standard runtime library

libstdc++-9.3.0-r2 webpage:
https://gcc.gnu.org

libstdc++-9.3.0-r2 installed size:
1167360
```
```
root@openssh-server:/# apk info musl
musl-1.1.24-r10 description:
the musl c library (libc) implementation

musl-1.1.24-r10 webpage:
https://musl.libc.org/

musl-1.1.24-r10 installed size:
499712
```

**Comment by roblourens** [comment]
Indeed, sorry
