### ISSUE TITLE
 The VS Code Server failed to start

### ISSUE THREAD

**Issue by mrevow** [microsoft/vscode-remote-release#4307]
- VSCode Version: 1.52.1
- Local OS Version: Windows_NT_x64 10.0.19042
- Remote OS Version: Ubuntu 18.04.5
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connect to remote host using ssh from command pallete
2. Select the remote host
3. Errors out with log below

Does this issue occur when you try this locally?: No
Does this issue occur with all remotes: No only occurs with one remote

## Log Output

```
[08:47:41.235] Log Level: 1
[08:47:41.244] remote-ssh@0.62.0
[08:47:41.244] win32 x64
[08:47:41.246] SSH Resolver called for "ssh-remote+mrevowgp1.westus2.cloudapp.azure.com", attempt 1
[08:47:41.246] "remote.SSH.useLocalServer": false
[08:47:41.247] "remote.SSH.showLoginTerminal": false
[08:47:41.247] "remote.SSH.remotePlatform": {"mrevowcpu2.centralus.cloudapp.azure.com":"linux"}
[08:47:41.247] "remote.SSH.sshPath": undefined
[08:47:41.247] "remote.SSH.sshConfigurationFile": undefined
[08:47:41.247] "remote.SSH.useFlock": true
[08:47:41.248] "remote.SSH.lockfilesInTmp": false
[08:47:41.248] "remote.SSH.localServerDownload": auto
[08:47:41.248] "remote.SSH.remoteServerListenOnSocket": false
[08:47:41.248] "remote.SSH.showLoginTerminal": false
[08:47:41.248] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[08:47:41.248] SSH Resolver called for host: mrevowgp1.westus2.cloudapp.azure.com
[08:47:41.249] Setting up SSH remote "mrevowgp1.westus2.cloudapp.azure.com"
[08:47:41.279] Using commit id "ea3859d4ba2f3e577a159bc91e3074c5d85c0523" and quality "stable" for server
[08:47:41.285] Install and start server if needed
[08:47:45.967] Checking ssh with "ssh -V"
[08:47:46.028] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[08:47:46.034] Running script with connection command: ssh -T -D 57263 "mrevowgp1.westus2.cloudapp.azure.com" bash
[08:47:46.037] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[08:47:47.021] "install" terminal received data: "[2J[m[H93ea2fea3716: running
]0;C:\WINDOWS\System32\cmd.exe[?25h"
[08:47:47.022] Got some output, clearing connection timeout
[08:47:47.061] "install" terminal received data: "Acquiring lock on /home/mrevow/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074
c5d85c0523/vscode-remote-lock.mrevow.ea3859d4ba2f3e577a159bc91e3074c5d85c0523   
Found existing installation at /home/mrevow/.vscode-server/bin/ea3859d4ba2f3e577
a159bc91e3074c5d85c0523...[K
Checking /home/mrevow/.vscode-server/.ea3859d4ba2f3e577a159bc91e3074c5d85c0523.l
og and /home/mrevow/.vscode-server/.ea3859d4ba2f3e577a159bc91e3074c5d85c0523.pid
 for a running server[K
Looking for server with pid: 4605[K"
[08:47:47.076] "install" terminal received data: "Found running server...[K
[K
*[K
* Reminder: You may only use this software with Visual Studio family products,  
* as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
*[K
[K
Server did not start successfully. Full server log at /home/mrevow/.vscode-serve
r/.ea3859d4ba2f3e577a159bc91e3074c5d85c0523.log >>>[K
<<< End of server log[K
93ea2fea3716: start[K
exitCode==32==[K
listeningOn====[K
osReleaseId==ubuntu==[K
arch==x86_64==[K
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
93ea2fea3716: end"
[08:47:47.076] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[08:47:47.084] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (c:\Users\mrevow\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:64207)
	at c:\Users\mrevow\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:62459
	at Object.t.handleInstallOutput (c:\Users\mrevow\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:63061)
	at I (c:\Users\mrevow\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:311112)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\mrevow\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:309029
	at async Object.t.withShowDetailsEvent (c:\Users\mrevow\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:403706)
	at async Object.t.resolve (c:\Users\mrevow\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:312426)
	at async c:\Users\mrevow\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:127:110280
[08:47:47.087] TELEMETRY: {"eventName":"resolver","properties":{"outcome":"failure","reason":"ExitCode","exitCodeLabel":"ServerFailedToStart","osReleaseId":"ubuntu","arch":"x86_64","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0"},"measures":{"resolveAttempts":1,"exitCode":32,"retries":1,"timing.totalResolveTime":5832,"timing.preSshTime":4790,"timing.establishSshTime":986,"timing.scriptTime":1040}}
[08:47:47.089] ------

[08:47:47.799] "install" terminal command done
[08:47:47.799] Install terminal quit with output: 

```

## Other Information
1. I am able to remote ssh to the server manually using `ssh -i ~/.ssh/key.pem user@host.azure.com`
2. Visual code is able to connect to other hosts. I only get this error with this host
3. Connecting to this host was working fine for many months.  Coincidently when the server ran out of boot disk space I started getting this error. I have since cleaned up the boot disk and there is now ample free space
4.  My ssh config looks like
...  Other hosts
Host host.azure.com
  HostName host.azure.com
  IdentityFile c:/Users/user/.ssh/key.pem
  User user

**Comment by HanyuuLu** [comment]
I've got the similar problem when i attempt to connect to my raspberry pi 4b (with arm64 Raspbian), i found such log info in my vscode client
``` bash
[14:28:28.496] > Server did not start successfully. Full server log at /home/pi/.vscode-server/.e
> ea3859d4ba2f3e577a159bc91e3074c5d85c0523.log >>>
> /home/pi/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/server.sh: 
>  12: /home/pi/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/server.
> .sh: /home/pi/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/node: n
> not found
[14:28:28.502] > 
> <<< End of server log
> 01e1a283bd90: start
> exitCode==32==
> listeningOn====
> osReleaseId==raspbian==
> arch==aarch64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==7891==
> 01e1a283bd90: end
[14:28:28.502] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==raspbian==
arch==aarch64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==7891==

[14:28:28.508] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (c:\Users\Hanyuu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:64207)
	at c:\Users\Hanyuu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:62459
	at Object.t.handleInstallOutput (c:\Users\Hanyuu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:63061)
	at I (c:\Users\Hanyuu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:311112)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async c:\Users\Hanyuu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:309029
	at async Object.t.withShowDetailsEvent (c:\Users\Hanyuu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:403706)
	at async Object.t.resolve (c:\Users\Hanyuu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:1:312426)
	at async c:\Users\Hanyuu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.62.0\out\extension.js:127:110280
[14:28:28.510] > 
[14:28:28.515] ------
```
and this in my raspberry pi 4b's .vscode-remote logfile
``` bash
cat /home/pi/.vscode-server/.ea3859d4ba2f3e577a159bc91e3074c5d85c0523.log
/home/pi/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/server.sh: 12: /home/pi/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/server.sh: /home/pi/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/node: not found
```

**Comment by roblourens** [comment]
Please try running the command "Kill VS Code Server on Host", it might be that the server was installed in a bad state when it ran out of disk space.

**Comment by mrevow** [comment]
Thanks @roblourens That worked!

Just in case others need to try the same here is the detail 

1. ctrl-shift-p  and choose:
2. `Remote-SSH: kill VS Code Server on Host...`
3. Chose the host name
4. Selected the platform type (linux)

No feedback was received, but the next time I remote logged in it worked
