### ISSUE TITLE
Npm fails after 'Rebuild Container'

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#4308]
1) Clone `https://github.com/microsoft/vscode-remote-try-node` into a container volume
2) `npm install` works fine
3) Run `Rebuild Container`
4) `npm install` get the following error:

```
node@1493723f89c2:/workspaces/vscode-remote-try-node$ npm install
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/home/node/.vscode-server-insiders/data/User/workspaceStorage/fbaf90b076ac78e0d27774a5306a7fcd/ms-vscode.js-debug/bootloader.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1277:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:439:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:71:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
```

**Comment by chrmarti** [comment]
Related: https://github.com/microsoft/vscode-js-debug/issues/374#issuecomment-675020979

**Comment by egamma** [comment]
After following the steps given in the comment both `npm` and `node` work again.

**Comment by chrmarti** [comment]
@connor4312 Is this still the old issue or is this a new case?

**Comment by connor4312** [comment]
This is interesting. @Tyriar we should discard the terminal environment variables when rebuilding a container, treat it as a new workspace.

**Comment by chrmarti** [comment]
@connor4312 A rebuild also reloads the window, are the variables preserved across reloads?

**Comment by connor4312** [comment]
Yes, intentionally

**Comment by Tyriar** [comment]
@chrmarti are there any hooks that I can use to clear the environment variable collections? It is just a regular window reload from the perspective of VS Code?

**Comment by chrmarti** [comment]
@Tyriar The reload is not aware of the rebuild, only the extension nows about that. There are no hooks I'm aware of. What is the environment variable that causes this?

**Comment by Tyriar** [comment]
@chrmarti the JS debug extension registers an environment variable to enable auto attach, this is cached per workspace by design so that reloading the window will not wait for extensions to launch to create a terminal.

@connor4312 the only way forward I'm seeing for this is for the js debug extension to track this and clear/reset the environment when it reloads and finds the bootloader doesn't exist there, which would cause the warning in the top right like it's a new workspace.

**Comment by connor4312** [comment]
This is not possible without us activating on `*` to check this, with is not good.

I think clearing environment variables on reload would be desirable not just for js-debug. For example `VSCODE_GIT_IPC_HANDLE` points to a temporary file, which would no longer be valid on reload. Maybe a missing git handle can be handled gracefully, but a missing bootloader cannot.

**Comment by chrmarti** [comment]
@connor4312 Why is the bootloader in the user data and not in the install folder?

**Comment by connor4312** [comment]
It copied there so that the location doesn't change when the extension version/vscode updates

**Comment by joaomoreno** [comment]
@Tyriar I think that's the only one open. Even if we resolve `vscodeInstall`, it doesn't solve the problem that, for remote, terminal environments are _sticky_.

**Comment by Tyriar** [comment]
@joaomoreno it's sticky, so you could say `${vscodeInstall}` to point to the extension directory, which would get resolved to the correct path _whenever a new version is installed_? That solves the problem we're talking about doesn't it?

**Comment by joaomoreno** [comment]
Oh I see. Literally `${vscodeInstall}` would be resolved after the fact by us? Yeah that could work. We should probably come up with something more obscure and less likely to collide with a real-world scenario, eg `@@VSCODE_INSTALL_PATH@@`. Idk

**Comment by Tyriar** [comment]
`${}` is how the variable resolution feature works https://code.visualstudio.com/docs/editor/variables-reference

**Comment by joaomoreno** [comment]
Yeah, but not in env variables. It's in tasks or launch configs. Env variables usually are passed around shells and at some point we will hit a situation in which some tool will resolve it before we do.

**Comment by Tyriar** [comment]
I'd still stay we still stick with ${} though as it's used [in a lot of places](https://code.visualstudio.com/docs/editor/variables-reference#_is-variable-substitution-supported-in-user-and-workspace-settings), instead of trying to invent something new and different. $ is common in paths too (mostly where it's used elsewhere) which is why the {} works well to avoid problems.

**Comment by joaomoreno** [comment]
OK I must be misunderstanding something. I was under the assumpion the idea was that extensions would have env variables with the *literal* value `${vscodeInstallPath}`. Ie `export VSCODE_INSTALL_PATH='${vscodeInstallPath}'`. But still I don't see how that could help in a situation that the workbench reloads and the terminal env is preserved. How and where would that literal value be resolved?

**Comment by Tyriar** [comment]
@joaomoreno examples:

```ts
collection.append('PATH', '${vscodeInstallPath}/extensions/git/bin');
collection.replace('USED_BY_GIT', '${vscodeInstallPath}/extensions/git/bin/auth.sh');
collection.replace('NODE_OPTIONS', 'require("${vscodeInstallPath}/ms-vscode.js-debug/bootloader.js")')
```

The path would get resolved when the collection gets merged into the actual environment, the shell wouldn't see any `${}`.

**Comment by joaomoreno** [comment]
Oh I see what you mean, at the terminal API level, I like it. And it definitely fixes it for most cases! But this still doesn't address the remote case, in which terminals are persisted. I hit this all the time with WSL.

**Comment by Tyriar** [comment]
@joaomoreno was just talking about this WRT codespaces, I'll probably do https://github.com/microsoft/vscode/issues/100193 in Feb which will fix that case.

**Comment by Tyriar** [comment]
Created https://github.com/microsoft/vscode/issues/115053 to track vscode-side work. This would need to be actioned in the extensions after the variable resolution is supported.

**Comment by connor4312** [comment]
This looks good (for non-nightly builds which is the vast majority of users) but I'm not sure how to get the install path from the extension host. Is it currently exposed in any way?

**Comment by Tyriar** [comment]
@connor4312 I guess extension dir path is what js-debug needs?

**Comment by connor4312** [comment]
Yea

**Comment by Tyriar** [comment]
@connor4312 @joaomoreno variables are now resolved in the env var values and `${execInstallFolder}` should point to VS Code's install folder, so you can point directly to you bootloader scripts without needing to install them.
