### ISSUE TITLE
Remote connection fails after initial connection if the git path has a space in it

### ISSUE THREAD

**Issue by Meberem** [microsoft/vscode-remote-release#4310]
- VSCode Version:1.52.1
- Local OS Version: Windows 10 2004
- Remote OS Version: Windows 10 20H2
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Have a git path with a space in it and connect

```
[2021-01-15 20:01:00.081] [renderer1] [error] Error: [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat 'C:\Code\*redacted*\.vscode'
[2021-01-15 20:01:03.475] [renderer1] [error] spawn C:\Program Files\Git\cmd\git.exe ENOENT: Error: spawn C:\Program Files\Git\cmd\git.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)
[2021-01-15 20:01:14.562] [renderer1] [info] [remote-connection][ExtensionHost][d752b…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-01-15 20:01:14.562] [renderer1] [info] [remote-connection][ExtensionHost][d752b…][reconnect] waiting for 5 seconds before reconnecting...
[2021-01-15 20:01:14.563] [renderer1] [info] [remote-connection][Management   ][e8665…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-01-15 20:01:14.586] [renderer1] [info] [remote-connection][Management   ][e8665…][reconnect] waiting for 5 seconds before reconnecting...
[2021-01-15 20:01:19.566] [renderer1] [info] [remote-connection][ExtensionHost][d752b…][reconnect] resolving connection...
[2021-01-15 20:01:19.584] [renderer1] [info] [remote-connection][Management   ][e8665…][reconnect] resolving connection...
[2021-01-15 20:01:19.590] [renderer1] [info] [remote-connection][ExtensionHost][d752b…][reconnect] A promise cancelation error occurred while trying to reconnect, will try again...
[2021-01-15 20:01:19.590] [renderer1] [info] [remote-connection][ExtensionHost][d752b…][reconnect] waiting for 5 seconds before reconnecting...
[2021-01-15 20:01:22.074] [renderer1] [info] [remote-connection][Management   ][e8665…][reconnect] connecting to 127.0.0.1:50161...
[2021-01-15 20:01:22.124] [renderer1] [error] [remote-connection][Management   ][e8665…][reconnect][127.0.0.1:50161] received error control message when negotiating connection. Error:
[2021-01-15 20:01:22.127] [renderer1] [error] Error: Connection error: Unknown reconnection token.
```

**Comment by roblourens** [comment]
I doubt the git path thing is related to the connection failure, unless you've tried it both ways on the same machine?

**Comment by Meberem** [comment]
I initially did not have 2 way SSH between the machines as one, I initially tried with password authentication but this seemed to cause the same issue. Now both machines can Remote-SSH without a password and the issue appears to be resolved. I still get the error message about git, not sure why.

Below is my successful connection from my Laptop to my Desktop
```
[10:01:22.727] Log Level: 2
[10:01:22.740] remote-ssh@0.62.0
[10:01:22.740] win32 x64
[10:01:22.742] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a224d6174746865772d5043222c2275736572223a224d617474227d", attempt 1
[10:01:22.743] "remote.SSH.useLocalServer": false
[10:01:22.743] "remote.SSH.showLoginTerminal": false
[10:01:22.744] "remote.SSH.remotePlatform": {"Matts-PC":"windows"}
[10:01:22.744] "remote.SSH.sshPath": undefined
[10:01:22.745] "remote.SSH.sshConfigurationFile": undefined
[10:01:22.745] "remote.SSH.useFlock": true
[10:01:22.746] "remote.SSH.lockfilesInTmp": false
[10:01:22.748] "remote.SSH.localServerDownload": auto
[10:01:22.749] "remote.SSH.remoteServerListenOnSocket": false
[10:01:22.749] "remote.SSH.showLoginTerminal": false
[10:01:22.750] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[10:01:22.750] SSH Resolver called for host: Matt@Matts-PC
[10:01:22.751] Setting up SSH remote "Matts-PC"
[10:01:22.805] Using commit id "ea3859d4ba2f3e577a159bc91e3074c5d85c0523" and quality "stable" for server
[10:01:22.822] Install and start server if needed
[10:01:22.999] Checking ssh with "ssh -V"
[10:01:23.119] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[10:01:23.127] Remote command length: 7504/8192 characters
[10:01:23.130] Running script with connection command: ssh -T -D 55523 "Matt@Matts-PC" powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -Command "powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -EncodedCommand $([Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('CiR1dWlkPSJjOTI4MTg4OGU4YzciCiIke3V1aWR9OiBydW5uaW5nIgokUHJvZ3Jlc3NQcmVmZXJlbmNlPSdTaWxlbnRseUNvbnRpbnVlJwokbl89J2VhMzg1OWQ0YmEyZjNlNTc3YTE1OWJjOTFlMzA3NGM1ZDg1YzA1MjMnCiRwPSRlbnY6UFJPQ0VTU09SX0FSQ0hJVEVDVFVSRQokYXJjaD1pZiAoKCRwIC1lcSAnQU1ENjQnKSAtb3IgKCRwIC1lcSAnSUE2NCcpKSB7ICd4NjQnIH0gZWxzZSB7ICdpYTMyJyB9CiRvXz0oSm9pbi1QYXRoIChSZXNvbHZlLVBhdGggfikgJy52c2NvZGUtc2VydmVyJykKJGVudjpWU0NPREVfQUdFTlRfRk9MREVSPSRvXwokbG9nPSIkb19cLiRuXy5sb2ciCiRzRGlyPSIkb19cYmluXCRuXyIKJHBfPSdzdGFibGUnCiRxXz0iIgokZXh0cz0iIgokZ189JFRydWUKJGhfPSRGYWxzZQokZ2xvYmFsOnJfID0gJEZhbHNlCiRnbG9iYWw6c18gPSAnJwokZ2xvYmFsOmpfID0gJycKJGdsb2JhbDprXyA9ICcnCiRnbG9iYWw6bF8gPSAnJwokZ2xvYmFsOm1fID0gJycKZnVuY3Rpb24gZGV0YWlscyB7CiJsaXN0ZW5pbmdPbj09JHBvcnQ9PSIKIm9zUmVsZWFzZUlkPT13aW5kb3dzPT0iCiJvc1ZlcnNpb249PSRhaF89PSIKImFyY2g9PSRhcmNoPT0iCiJwbGF0Zm9ybT09d2luZG93cz09IgoidW5wYWNrUmVzdWx0PT0kc189PSIKImRpZExvY2FsRG93bmxvYWQ9PSRyXz09IgoiZG93bmxvYWRUaW1lPT0kal89PSIKImluc3RhbGxUaW1lPT0ka189PSIKImV4dEluc3RhbGxUaW1lPT0kbF89PSIKInNlcnZlclN0YXJ0VGltZT09JG1fPT0iCn0KZnVuY3Rpb24gaV8gewpyZXR1cm4gW3N5c3RlbS5kaWFnbm9zdGljcy5zdG9wd2F0Y2hdOjpTdGFydE5ldygpOwp9CmZ1bmN0aW9uIHEoJGNvZGUpIHsKIiR7dXVpZH06IHN0YXJ0IgoiZXhpdENvZGU9PSRjb2RlPT0iCmRldGFpbHMKIiR7dXVpZH06IGVuZCIKfQpmdW5jdGlvbiBhXyB7CiR0Xz0kUElECndoaWxlICgkVHJ1ZSkgewokdV89KGdjaW0gd2luMzJfcHJvY2VzcyB8ID8gcHJvY2Vzc2lkIC1lcSAkdF8pLnBhcmVudHByb2Nlc3NpZAppZiAoISR1Xykgewoibm8gc3NoZCBwYXJlbnQgcHJvYyIKZXhpdCAwCn0KaWYgKChncHMgLUlkICR1XykuTmFtZSAtZXEgJ3NzaGQnKSB7CnJldHVybiAkdV8KfQokdF89JHVfCn0KfQpmdW5jdGlvbiBiXyB7CmlmICgkdl8pIHsKaWYgKCEoZ3BzIC1JZCAkdl8pKSB7CiJzZXJ2ZXIgZGllZCwgZXhpdCIKZXhpdCAwCn0KfSBlbHNlIHsKaWYgKCEoZ3BzIC1JZCAkc3NoZFBJRCkpIHsKInNzaGQgcGFyZW50IGRpZWQsIGV4aXQiCmV4aXQgMAp9Cn0KfQpmdW5jdGlvbiBjXyB7CiRzPWlfCiJEb3dubG9hZGluZyBzZXJ2ZXIiCiIke3V1aWR9JSUxJSUiCiR3Xz0iIgokeF89aWYgKCRhcmNoIC1lcSAneDY0JykgeyAiLSRhcmNoIiB9IGVsc2UgeyAiIiB9CiR5Xz0ic2VydmVyLXdpbjMyJHhfIiArICR3Xwokc3BsYXQ9QHsKVXJpPSJodHRwczovL3VwZGF0ZS5jb2RlLnZpc3VhbHN0dWRpby5jb20vY29tbWl0OiRuXy8keV8vJHBfIgpUaW1lb3V0U2VjPTIwCk91dEZpbGU9InZzY29kZS1zZXJ2ZXIuemlwIgpVc2VCYXNpY1BhcnNpbmc9JFRydWUKfQpbTmV0LlNlcnZpY2VQb2ludE1hbmFnZXJdOjpTZWN1cml0eVByb3RvY29sID0gJ1RsczEyJwppcm0gQHNwbGF0CiRzLlN0b3AoKQokZ2xvYmFsOmpfID0gJHMuRWxhcHNlZE1pbGxpc2Vjb25kcwp9CmZ1bmN0aW9uIGRfIHsKJGdsb2JhbDpzXz0nc3VjY2VzcycKJHM9aV8KdHJ5IHsKJHpfPVtTeXN0ZW0uSU8uUGF0aF06OkdldFJhbmRvbUZpbGVOYW1lKCkKJGFhXz0iJGVudjpURU1QXCR6XyIKIkV4cGFuZGluZyBzZXJ2ZXIgaW50byAkYWFfIgoiJHt1dWlkfSUlMiUlIgpFeHBhbmQtQXJjaGl2ZSAidnNjb2RlLXNlcnZlci56aXAiIC1EZXN0aW5hdGlvblBhdGggIiRhYV8iCm12ICIkYWFfXHZzY29kZS0qXCoiIC1EZXN0aW5hdGlvbiAuCiRzLlN0b3AoKQokZ2xvYmFsOmtfID0gJHMuRWxhcHNlZE1pbGxpc2Vjb25kcwp9IGNhdGNoIHsKJGdsb2JhbDpzXz0nZXJyb3InCiJGYWlsZWQgdG8gdW56aXAgc2VydmVyLiAtICQoJF8uVG9TdHJpbmcoKSkiCmZfIDM3CmRfCn0KaWYoIShUZXN0LVBhdGggIiRzRGlyXHNlcnZlci5jbWQiKSkgewokZ2xvYmFsOnNfPSdtaXNzaW5nRmlsZXMnCiJEb3dubG9hZGVkIHNlcnZlciBpcyBpbmNvbXBsZXRlLiIKZl8gMzcKZF8KfQp9CmZ1bmN0aW9uIFN0YXJ0U2VydmVyIHsKJHM9aV8KaWYoVGVzdC1QYXRoICRsb2cpIHsKZGVsICRsb2cKfQokYWJfPSRzRGlyIC1yZXBsYWNlICcgJywgJ2AgJwokYXJncz0iLS1zdGFydC1zZXJ2ZXIgLS1ob3N0PTEyNy4wLjAuMSAtLWVuYWJsZS1yZW1vdGUtYXV0by1zaHV0ZG93biAtLXBvcnQ9MCAkcV8gJGV4dHMgKj4gJyRsb2cnIgokc3BsYXQ9QHsKRmlsZVBhdGggPSAicG93ZXJzaGVsbC5leGUiCldpbmRvd1N0eWxlID0gImhpZGRlbiIKQXJndW1lbnRMaXN0ID0gQCgKIi1FeGVjdXRpb25Qb2xpY3kiLCAiVW5yZXN0cmljdGVkIiwgIi1Ob0xvZ28iLCAiLU5vUHJvZmlsZSIsICItTm9uSW50ZXJhY3RpdmUiLCAiLWMiLCAiJGFiX1xzZXJ2ZXIuY21kICRhcmdzIgopClBhc3NUaHJ1ID0gJFRydWUKfQoiU3RhcnRpbmcgc2VydmVyOiAmICckc0RpclxzZXJ2ZXIuY21kJyAkYXJncyIKJHZfPShzdGFydCBAc3BsYXQpLklECiRzLlN0b3AoKQokZ2xvYmFsOm1fID0gJHMuRWxhcHNlZE1pbGxpc2Vjb25kcwp9CmZ1bmN0aW9uIGVfIHsKJGdsb2JhbDpyXz0kVHJ1ZQoiVHJpZ2dlciBsb2NhbCBzZXJ2ZXIgZG93bmxvYWQiCiIke3V1aWR9OnRyaWdnZXJfc2VydmVyX2Rvd25sb2FkIgoicGxhdGZvcm09PXdpbmRvd3M9PSIKInZzY29kZUFyY2g9PSRhcmNoPT0iCiJkZXN0Rm9sZGVyPT0kc0Rpcj09IgoiJHt1dWlkfTp0cmlnZ2VyX3NlcnZlcl9kb3dubG9hZF9lbmQiCiJXYWl0aW5nIGZvciBjbGllbnQgdG8gdHJhbnNmZXIgc2VydmVyIGFyY2hpdmUuLi4iCiJXYWl0aW5nIGZvciAkc0Rpclx2c2NvZGUtc2NwLWRvbmUuZmxhZyBhbmQgdnNjb2RlLXNlcnZlci56aXAgdG8gZXhpc3QiCndoaWxlKCRUcnVlKSB7CmlmKFRlc3QtUGF0aCAiJHNEaXJcdnNjb2RlLXNjcC1kb25lLmZsYWciKSB7CmlmKCEoVGVzdC1QYXRoICIkc0Rpclx2c2NvZGUtc2VydmVyLnppcCIpKSB7CiJUcmFuc2ZlciBmYWlsZWQiCnEgMzEKfQoiVHJhbnNmZXIgY29tcGxldGUiCmRlbCAkc0Rpclx2c2NvZGUtc2NwLWRvbmUuZmxhZwpicmVhawp9IGVsc2UgewpTdGFydC1TbGVlcCAtU2Vjb25kcyAzCmJfCn0KfQp9CmZ1bmN0aW9uIGZfKCRjb2RlKSB7CmlmICgkcl8pIHsKIkFscmVhZHkgYXR0ZW1wdGVkIGxvY2FsIGRvd25sb2FkLCBmYWlsaW5nIgpxICRjb2RlCn0gZWxzZWlmKCRnXykgewplXwp9IGVsc2UgewpxICRjb2RlCn0KfQpmdW5jdGlvbiBJbnN0YWxsRXh0ZW5zaW9ucyB7CmlmICgkZXh0cyAtbmUgIiIpIHsKJHM9aV8KJiAiJHNEaXJcc2VydmVyLmNtZCIgJHFfIAokcy5TdG9wKCkKJGdsb2JhbDpsXyA9ICRzLkVsYXBzZWRNaWxsaXNlY29uZHMKfQp9CiRzc2hkUElEPWFfCmlmKCEoVGVzdC1QYXRoICRzRGlyKSkgewokbT0iQ291bGQgbm90IGNyZWF0ZSBzZXJ2ZXIgZGlyZWN0b3J5Igp0cnkgewokbnVsbD1uaSAtaXQgZCAkc0RpciAtZiAtZWEgc2kKfSBjYXRjaCB7CiIkbS4gLSAkKCRfLlRvU3RyaW5nKCkpIgpyZXR1cm4KfQppZighKFRlc3QtUGF0aCAkc0RpcikpIHsKIiRtIgpyZXR1cm4KfQp9CmNkICRzRGlyCiRhY189KEpvaW4tUGF0aCAiJHNEaXIiICJ2c2NvZGUtcmVtb3RlLWxvY2suJG5fIikKdHJ5IHsKJG51bGw9bmkgJGFjXyAtaXQgZiAtZWEgc2kKfSBjYXRjaCB7CiJDb3VsZCBub3QgY3JlYXRlIHNlcnZlciBsb2NrIGZpbGUuIC0gJCgkXy5Ub1N0cmluZygpKSIKcmV0dXJuCn0KdHJ5IHsKIkFjcXVpcmluZyBsb2NrIG9uICRhY18iCiRmaWxlPVtTeXN0ZW0uaW8uRmlsZV06Ok9wZW4oJGFjXywgJ09wZW4nLCAnUmVhZCcsICdOb25lJykKfSBjYXRjaCB7CiJJbnN0YWxsIGFscmVhZHkgaW4gcHJvZ3Jlc3MuLi4gLSAkKCRfLlRvU3RyaW5nKCkpIgpxIDI0Cn0KdHJ5IHsKIkxvb2tpbmcgZm9yIGV4aXN0aW5nIHNlcnZlciBpbiAkc0RpciIKaWYoVGVzdC1QYXRoICIkc0RpclxzZXJ2ZXIuY21kIikgewoiRm91bmQgaW5zdGFsbGVkIHNlcnZlciIKfSBlbHNlIHsKaWYgKCRoXykgewplXwp9IGVsc2Ugewp0cnkgeyBjXyB9IGNhdGNoIHsKIkRvd25sb2FkIGZhaWxlZC4gLSAkKCRfLlRvU3RyaW5nKCkpIgpmXyAyNQp9Cn0KZF8KfQppZighKEdldC1Qcm9jZXNzIG5vZGUgLUVycm9yQWN0aW9uIFNpbGVudGx5Q29udGludWUgfCBXaGVyZS1PYmplY3QgUGF0aCAtbWF0Y2ggJG5fKSkgewpTdGFydFNlcnZlcgp9IGVsc2UgewoiU2VydmVyIHdpdGggJG5fIGlzIGFscmVhZHkgcnVubmluZy4iCkluc3RhbGxFeHRlbnNpb25zCn0KJGFmXz1AewpQYXRoID0gJGxvZwpQYXR0ZXJuID0gIkV4dGVuc2lvbiBob3N0IGFnZW50IGxpc3RlbmluZyBvbiAoXGQrKSIKfQokYWVfPUB7ClBhdGggPSAkbG9nClBhdHRlcm4gPSAiISEhISBTZXJ2ZXIgdGVybWluYXRlZCBkdWUgdG8gcHJlc2VuY2Ugb2YgQ1ZFLTIwMjAtMTQxNiAhISEhIgp9CiRhZF89KEdldC1EYXRlKS5BZGRTZWNvbmRzKDQpCndoaWxlICgoR2V0LURhdGUpIC1sdCAkYWRfKSB7CmlmKFRlc3QtUGF0aCAkbG9nKSB7CiRhZ189KHNscyBAYWZfKS5NYXRjaGVzLkdyb3VwcwppZigkYWdfKSB7CiRwb3J0PSRhZ19bMV0uVmFsdWUKYnJlYWsKfQokZmFpbGVkPShzbHMgQGFlXykuTWF0Y2hlcy5Hcm91cHMKaWYoJGZhaWxlZCkgewoiU2VydmVyIGRpZCBub3Qgc3RhcnQgc3VjY2Vzc2Z1bGx5LiBGdWxsIHNlcnZlciBsb2cgYXQgJGxvZyA+Pj4iCmNhdCAkbG9nCiI8PDwgRW5kIG9mIHNlcnZlciBsb2ciCnEgMzYKfQp9CnNsZWVwIC1NaWxsaXNlY29uZHMgMzAKfQppZiAoISRwb3J0KSB7CiJTZXJ2ZXIgZGlkIG5vdCBzdGFydCBzdWNjZXNzZnVsbHkuIEZ1bGwgc2VydmVyIGxvZyBhdCAkbG9nID4+PiIKY2F0ICRsb2cKIjw8PCBFbmQgb2Ygc2VydmVyIGxvZyIKcSAzMgp9Cn0gY2F0Y2ggewoiU2VydmVyIGZhaWxlZCB0byBzdGFydC4gLSAkKCRfLlRvU3RyaW5nKCkpIgp9IGZpbmFsbHkgewokZmlsZS5DbG9zZSgpCn0KdHJ5IHsKJGFoXz0oZ2NpbSBXaW4zMl9PcGVyYXRpbmdTeXN0ZW0pLlZlcnNpb24KfSBjYXRjaCB7CiJGYWlsZWQgdG8gZmluZCBXaW5kb3dzIHZlcnNpb24gLSAkKCRfLlRvU3RyaW5nKCkpIgokYWhfPSJ1bmtub3duIgp9CiIke3V1aWR9OiBzdGFydCIKInNzaEF1dGhTb2NrPT0kZW52OlNTSF9BVVRIX1NPQ0s9PSIKZGV0YWlscwoiJHt1dWlkfTogZW5kIgoiSW5zdGFsbCBzY3JpcHQgaXMgJHBpZCwgd2F0Y2hpbmcgc3NoZCBwYXJlbnQgJHNzaGRQSUQiCndoaWxlICgkVHJ1ZSkgewpiXwpzbGVlcCAzMAp9Cg==')))))"  # RemoteSSHConfigurationScript
[10:01:23.137] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:01:24.027] > warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
> ]0;C:\WINDOWS\System32\cmd.exe
[10:01:24.029] Got some output, clearing connection timeout
[10:01:24.264] > c9281888e8c7: running
[10:01:24.279] > 
[10:01:24.731] > Acquiring lock on C:\Users\matth\.vscode-server\bin\ea3859d4ba2f3e577a159bc91e30
> 74c5d85c0523\vscode-remote-lock.ea3859d4ba2f3e577a159bc91e3074c5d85c0523        
[10:01:24.765] > 
> Looking for existing server in C:\Users\matth\.vscode-server\bin\ea3859d4ba2f3e5
> 77a159bc91e3074c5d85c0523
> Found installed server
> Starting server: & 'C:\Users\matth\.vscode-server\bin\ea3859d4ba2f3e577a159bc91e
> 3074c5d85c0523\server.cmd' --start-server --host=127.0.0.1 --enable-remote-auto-
> shutdown --port=0   *> 'C:\Users\matth\.vscode-server\.ea3859d4ba2f3e577a159bc91
> e3074c5d85c0523.log'
[10:01:25.161] > c9281888e8c7: start
[10:01:25.256] > 
> sshAuthSock====
> listeningOn==54102==     
> osReleaseId==windows==   
> osVersion==10.0.19042==  
> arch==x64==
> platform==windows==      
> unpackResult====
> didLocalDownload==False==
> downloadTime====
> installTime====
> extInstallTime====       
> serverStartTime==29==    
> c9281888e8c7: end
[10:01:25.257] Received install output: 
sshAuthSock====
listeningOn==54102==     
osReleaseId==windows==   
osVersion==10.0.19042==  
arch==x64==
platform==windows==      
unpackResult====
didLocalDownload==False==
downloadTime====
installTime====
extInstallTime====       
serverStartTime==29==    

[10:01:25.260] Remote server is listening on 54102
[10:01:25.261] Parsed server configuration: {"remoteListeningOn":{"port":54102},"osReleaseId":"windows","arch":"x64","sshAuthSock":"","platform":"windows","serverStartTime":29}
[10:01:25.269] Starting forwarding server. localPort 55548 -> socksPort 55523 -> remotePort 54102
[10:01:25.273] Forwarding server listening on 55548
[10:01:25.275] Waiting for ssh tunnel to be ready
[10:01:25.279] [Forwarding server 55548] Got connection 0
[10:01:25.285] Tunneled 54102 to local port 55548
[10:01:25.286] Resolved "ssh-remote+7b22686f73744e616d65223a224d6174746865772d5043222c2275736572223a224d617474227d" to "127.0.0.1:55548"
[10:01:25.305] ------




[10:01:25.389] > 
> Install script is 28236, watching sshd parent 10356
[10:01:25.661] > 
[10:01:25.697] [Forwarding server 55548] Got connection 1
[10:01:25.699] [Forwarding server 55548] Got connection 2
[10:01:27.828] [Forwarding server 55548] Got connection 3
[10:01:31.967] Unhandled rejection: Error: spawn C:\Program Files\Git\cmd\git.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)
[10:01:31.997] Unhandled rejection: Error: spawn C:\Program Files\Git\cmd\git.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)

```
