### ISSUE TITLE
Error: Failed to parse remote port from server output

### ISSUE THREAD

**Issue by AlexZhou1995** [microsoft/vscode-remote-release#4314]
- VSCode Version: 1.52.1
- Local OS Version: MacOS
- Remote OS Version: Linux
- Remote Extension/Connection Type: SSH

```
[15:35:00.844] Log Level: 2
[15:35:00.846] remote-ssh@0.62.0
[15:35:00.846] darwin x64
[15:35:00.847] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a224a756d704d616368696e65227d", attempt 1
[15:35:00.847] "remote.SSH.useLocalServer": true
[15:35:00.847] "remote.SSH.sshPath": undefined
[15:35:00.847] "remote.SSH.sshConfigurationFile": /Users/zhouwj/.vscode/extension_conf/remote_ssh/config
[15:35:00.847] "remote.SSH.useFlock": true
[15:35:00.847] "remote.SSH.lockfilesInTmp": false
[15:35:00.848] "remote.SSH.localServerDownload": auto
[15:35:00.848] "remote.SSH.remoteServerListenOnSocket": false
[15:35:00.848] "remote.SSH.showLoginTerminal": false
[15:35:00.848] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[15:35:00.848] SSH Resolver called for host: JumpMachine
[15:35:00.848] Setting up SSH remote "JumpMachine"
[15:35:00.851] Acquiring local install lock: /var/folders/13/1qt9fjrs42b69ypwhcpmh6vr0000gp/T/vscode-remote-ssh-JumpMachine-install.lock
[15:35:00.861] Looking for existing server data file at /Users/zhouwj/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-JumpMachine-ea3859d4ba2f3e577a159bc91e3074c5d85c0523-0.62.0/data.json
[15:35:00.862] Using commit id "ea3859d4ba2f3e577a159bc91e3074c5d85c0523" and quality "stable" for server
[15:35:00.864] Install and start server if needed
[15:35:00.868] Checking ssh with "ssh -V"
[15:35:00.909] > OpenSSH_7.9p1, LibreSSL 2.7.3

[15:35:00.911] Using SSH config file "/Users/zhouwj/.vscode/extension_conf/remote_ssh/config"
[15:35:00.911] askpass server listening on /var/folders/13/1qt9fjrs42b69ypwhcpmh6vr0000gp/T/vscode-ssh-askpass-a83126c82af28dc16bff4f99184d7d8079c479f1.sock
[15:35:00.912] Spawning local server with {"ipcHandlePath":"/var/folders/13/1qt9fjrs42b69ypwhcpmh6vr0000gp/T/vscode-ssh-askpass-143628b2f8fd1a56c4ac3c25a293234cf320c03c.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","60405","-o","ConnectTimeout=15","-F","/Users/zhouwj/.vscode/extension_conf/remote_ssh/config","JumpMachine"],"dataFilePath":"/Users/zhouwj/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-JumpMachine-ea3859d4ba2f3e577a159bc91e3074c5d85c0523-0.62.0/data.json"}
[15:35:00.912] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/zhouwj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/zhouwj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/13/1qt9fjrs42b69ypwhcpmh6vr0000gp/T/vscode-ssh-askpass-a83126c82af28dc16bff4f99184d7d8079c479f1.sock"}
[15:35:00.915] Spawned 40463
[15:35:00.999] > local-server> Spawned ssh: 40464
[15:35:01.037] stderr> OpenSSH_7.9p1, LibreSSL 2.7.3
[15:35:01.097] stderr> debug1: Server host key: ssh-rsa SHA256:p3vZYcYGrB1x/TkvQTDMoWZKZbYwHWup9F32k8uHtbQ
[15:35:01.277] Got askpass request: {"request":"\u001b[1;32mTry the fastest login: https://sa.alibaba-inc.com/ops/terminal.html \u001b[0m please enter your password (DomainPassword + 6 characters Token):"}
[15:35:01.279] Listening for interwindow password on /var/folders/13/1qt9fjrs42b69ypwhcpmh6vr0000gp/T/vscode-ssh-askpass-db936a523fa605b2ffa1dba207ed56f15602e393.sock
[15:35:01.279] Writing password prompt to globalState
[15:35:13.862] Interactor gave response: ***************
[15:35:13.863] Cleaning up other-window auth server
[15:35:13.978] stderr> Authenticated to login1.cm10.alibaba.org ([100.67.24.44]:22).
[15:35:13.991] stderr> Transferred: sent 2448, received 1624 bytes, in 0.0 seconds
[15:35:13.991] stderr> Bytes per second: sent 212555.4, received 141008.9
[15:35:13.992] > local-server> ssh child died, shutting down
[15:35:13.999] Local server exit: 0
[15:35:13.999] Received install output: OpenSSH_7.9p1, LibreSSL 2.7.3
debug1: Server host key: ssh-rsa SHA256:p3vZYcYGrB1x/TkvQTDMoWZKZbYwHWup9F32k8uHtbQ
Authenticated to login1.cm10.alibaba.org ([100.67.24.44]:22).
Transferred: sent 2448, received 1624 bytes, in 0.0 seconds
Bytes per second: sent 212555.4, received 141008.9

[15:35:14.000] Stopped parsing output early. Remaining text: OpenSSH_7.9p1, LibreSSL 2.7.3debug1: Server host key: ssh-rsa SHA256:p3vZYcYGrB1x/TkvQTDMoWZKZbYwHWup9F32k8uHtbQAuthenticated to login1.cm10.alibaba.org ([100.67.24.44]:22).Transferred: sent 2448, received 1624 bytes, in 0.0 secondsBytes per second: sent 212555.4, received 141008.9
[15:35:14.000] Failed to parse remote port from server output
[15:35:14.005] Resolver error: Error: 
	at Function.Create (/Users/zhouwj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:64276)
	at Object.t.handleInstallOutput (/Users/zhouwj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:61061)
	at Object.t.tryInstallWithLocalServer (/Users/zhouwj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:402931)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /Users/zhouwj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:308557
	at async Object.t.withShowDetailsEvent (/Users/zhouwj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:403706)
	at async /Users/zhouwj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:401486
	at async S (/Users/zhouwj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:398276)
	at async Object.t.resolveWithLocalServer (/Users/zhouwj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:401135)
	at async Object.t.resolve (/Users/zhouwj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:1:312304)
	at async /Users/zhouwj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.62.0/out/extension.js:127:110280
[15:35:14.009] ------

```

**Comment by roblourens** [comment]
What is your default remote shell?

Does setting `"remote.SSH.useLocalServer": false` help?
