### ISSUE TITLE
Failed to parse remote port from server output: While SSh 

### ISSUE THREAD

**Issue by yahyanik** [microsoft/vscode-remote-release#4330]
I am ssh-ing from a MacOS to an Ubuntu 16.04. The error log is as folows:
```
  `ready: 12cc40d08a4d`
  `Linux 4.4.0-1119-aws #133-Ubuntu SMP Tue Dec 1 19:04:22 UTC 2020`
  `Downloading with wget`
  `wget download failed`
  `wget: missing URL Usage: wget [OPTION]... [URL]... Try `wget --help' for more options.`
  `bash: line 12: printenv_indent: command not found`
  `bash: line 14: do_client_download_or_fail: command not found`
  `bash: line 43: syntax error near unexpected token `}'`
  `bash: line 43: `}'`
  `-sh: 4: function: not found`
  `-sh: 67: [[: not found`
  `12cc40d08a4d: running`
  `-sh: 88: [[: not found`
  `-sh: 147: Syntax error: "(" unexpected (expecting "then")`
  `Transferred: sent 17492, received 7796 bytes, in 0.4 seconds`
  `Bytes per second: sent 39011.2, received 17386.9`
  
  `[14:46:51.766] Stopped parsing output early. Remaining text: = * Documentation:  https://help.ubuntu.com * Management:     https://landscape.canonical.com * Support:        https://ubuntu.com/advantage  Get cloud support with Ubuntu Advantage Cloud Guest:    http://www.ubuntu.com/business/services/cloud64 packages can be updated.0 updates are security updates.New release '18.04.5 LTS' available.Run 'do-release-upgrade' to upgrade to it.ready: 12cc40d08a4dLinux 4.4.0-1119-aws #133-Ubuntu SMP Tue Dec 1 19:04:22 UTC 2020Downloading with wgetwget download failedwget: missing URL Usage: wget [OPTION]... [URL]... Try `wget --help' for more options.bash: line 12: printenv_indent: command not foundbash: line 14: do_client_download_or_fail: command not foundbash: line 43: syntax error near unexpected token `}'bash: line 43: `}'-sh: 4: function: not found-sh: 67: [[: not found12cc40d08a4d: running-sh: 88: [[: not found-sh: 147: Syntax error: "(" unexpected (expecting "then")Transferred: sent 17492, received 7796 bytes, in 0.4 secondsBytes per second: sent 39011.2, received 17386.9`
  `[14:46:51.766] Failed to parse remote port from server output`
  `[14:46:51.775] Resolver error: Error: `
	`  at Function.Create (/Users/seyednikouei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.58.0/out/extension.js:1:82258)`
	 ` at Object.t.handleInstallOutput (/Users/seyednikouei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.58.0/out/extension.js:1:79079)`
	 ` at Object.t.tryInstallWithLocalServer (/Users/seyednikouei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.58.0/out/extension.js:1:401911)`
	 ` at processTicksAndRejections (internal/process/task_queues.js:94:5)`
	  at async /Users/seyednikouei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.58.0/out/extension.js:1:307537
	  at async Object.t.withShowDetailsEvent (/Users/seyednikouei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.58.0/out/extension.js:1:402686)`
	  `at async /Users/seyednikouei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.58.0/out/extension.js:1:400466
	  `at async S (/Users/seyednikouei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.58.0/out/extension.js:1:397256)`
	  `at async Object.t.resolveWithLocalServer (/Users/seyednikouei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.58.0/out/extension.js:1:400115)`
	  `at async Object.t.resolve (/Users/seyednikouei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.58.0/out/extension.js:1:311284)`
	  `at async /Users/seyednikouei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.58.0/out/extension.js:127:110259
  [14:46:51.778] ------`
```

- VSCode Version: 1.52.1
- Local OS Version: MacOS 10.15.7
- Remote OS Version: Ubuntu 16.04
- Remote Extension/Connection Type: SSH/Docker/WSL: SHH

Steps to Reproduce:

1. download the VSCode app and install the Remote - SSH (version 0.62.0).
2. Use config file for SSH

**Comment by roblourens** [comment]
Please share the log from the Remote-SSH output channel

**Comment by yahyanik** [comment]
Hey, thanks for the response. The log from the Remote-SSH output channel is what I already included.

**Comment by roblourens** [comment]
It looks like either a partial log or output from the install terminal. But in any case, it looks like the install script is getting mangled or truncated. You could try setting `"remote.SSH.useLocalServer": false` to see if that makes a difference. Is there anything unusual about your setup that could cause something like `echo "echo hello" | ssh <yourhost> bash` to not work?
