### ISSUE TITLE
Failed to start vscode server 

### ISSUE THREAD

**Issue by artemtr** [microsoft/vscode-remote-release#4347]
- VSCode Version: insides
- Local OS Version: Debian GNU/Linux 10 (buster)
- Remote Extension/Connection Type: vscode-server/SSH

Steps to Reproduce:

1. Conent to host

Try to conect to host by ssh using remote-SSH ( Nightly ) extensions

**Here some log output**

[07:20:54.244] Log Level: 1
[07:20:54.251] remote-ssh-nightly@2021.1.26820
[07:20:54.252] linux x64
[07:20:54.255] SSH Resolver called for "ssh-remote+negocian.ftp.tools", attempt 1
[07:20:54.255] "remote.SSH.useLocalServer": false
[07:20:54.256] "remote.SSH.showLoginTerminal": false
[07:20:54.256] "remote.SSH.remotePlatform": {}
[07:20:54.257] "remote.SSH.sshPath": undefined
[07:20:54.257] "remote.SSH.sshConfigurationFile": undefined
[07:20:54.257] "remote.SSH.useFlock": true
[07:20:54.258] "remote.SSH.lockfilesInTmp": false
[07:20:54.258] "remote.SSH.localServerDownload": auto
[07:20:54.259] "remote.SSH.remoteServerListenOnSocket": true
[07:20:54.259] "remote.SSH.showLoginTerminal": false
[07:20:54.260] SSH Resolver called for host: negocian.ftp.tools
[07:20:54.260] Setting up SSH remote "negocian.ftp.tools"
[07:20:54.279] Using commit id "ed72c64b87ede96fb51bc16870f9d2ecbf4fcc57" and quality "insider" for server
[07:20:54.287] Install and start server if needed
[07:20:58.225] getPlatformForHost was canceled
[07:20:58.269] Resolver error: Error: Connecting was canceled
	at Function.Canceled (/home/artem/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.26820/out/extension.js:1:64226)
	at /home/artem/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.26820/out/extension.js:1:310713
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Object.t.withShowDetailsEvent (/home/artem/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.26820/out/extension.js:1:405790)
	at async Object.t.resolve (/home/artem/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.26820/out/extension.js:1:314454)
	at async /home/artem/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.1.26820/out/extension.js:127:110333
[07:20:58.284] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Canceled","exitCodeLabel":""},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":3972}}
[07:20:58.299] ------

![Screenshot from 2021-01-23 07-06-43](https://user-images.githubusercontent.com/16256887/105579360-b9703100-5d4b-11eb-80fa-50efde99cf9d.png)
![Screenshot from 2021-01-23 07-21-25](https://user-images.githubusercontent.com/16256887/105579361-baa15e00-5d4b-11eb-8916-8f744ef0111b.png)

**Comment by roblourens** [comment]
`getPlatformForHost was canceled` You should have gotten a prompt to select a host, did you press escape there? Also I think the pasted log is different than the one in the screenshot, could you share whatever full log you see next time you try?
