### ISSUE TITLE
When multiple instances of VSCode are open and one is reloaded, others lose connection 

### ISSUE THREAD

**Issue by BladeMF** [microsoft/vscode-remote-release#4353]
- VSCode Version:
1.52.1
- Local OS Version:
19042.746
- Remote OS Version:
Ubuntu 18
- Remote Extension/Connection Type: SSH/Docker/WSL
WSL 2

Steps to Reproduce:

1. Open two instances of VSCode with projects within the same WSL 2 instance
2. Reload the window of one of the instances

This doesn't not happen 100% of the time, but if you reload 10 times, it will most surely happen. You get this window first:
![image](https://user-images.githubusercontent.com/12109622/105676587-689b3c80-5ef3-11eb-8bd4-76a87d239daa.png)
and then inevitably this:
![image](https://user-images.githubusercontent.com/12109622/105676621-751f9500-5ef3-11eb-8ad5-a03f660f0bf8.png)

Not sure if by design, but it is kind of annoying when developing extensions as you need to reload multiple times.

Does this issue occur when you try this locally?: **No**
Does this issue occur when you try this locally and all extensions are disabled?: **No**

**Comment by bamurtaugh** [comment]
Thanks for writing this up @BladeMF. If you encounter this again, could you please provide any logs you see?

Set the appropriate logging level through Command Palette -> `Developer: Set Log Level...` -> `Trace`, and then retrieve logs once this occurs:
- F1 > Open View > Log (Window)
- F1 > Open View > Log (Remote Server)

**Comment by BladeMF** [comment]
Hi @bamurtaugh, thanks for responding. After the update yesterday I can't seem to reproduce it (the previous update did it as well). When now I try this, the Window log is empty and the Remote server log shows this for every reload:
```
[2021-02-11 08:30:41.184] [remoteagent] [info] [::ffff:172.22.16.1][eae244c0][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2021-02-11 08:30:42.223] [remoteagent] [info] [::ffff:172.22.16.1][90e1566b][ExtensionHostConnection] <20150> Extension Host Process exited with code: 0, signal: null.
[2021-02-11 08:30:42.581] [remoteagent] [info] [::ffff:172.22.16.1][94e9d426][ManagementConnection] New connection established.
[2021-02-11 08:30:42.598] [remoteagent] [info] [::ffff:172.22.16.1][7742eaba][ExtensionHostConnection] New connection established.
[2021-02-11 08:30:42.604] [remoteagent] [info] [::ffff:172.22.16.1][7742eaba][ExtensionHostConnection] <20353> Launched Extension Host Process.
```
Before the last update the reproduction was pretty easy as it did it on the 3rd reload at the latest, but now I tried at least 20 times with no success.

We should probably close this.

**Comment by bamurtaugh** [comment]
Thanks for the update @BladeMF! If you encounter this again, please just let us know, and we'd be happy to discuss further.

**Comment by BladeMF** [comment]
I am sorry to reopen this, but it seems I have found it again. The logs are as follows:
### Window
```
[2021-02-27 09:41:05.814] [renderer1] [info] [remote-connection][Management   ][08506…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-02-27 09:41:05.817] [renderer1] [info] [remote-connection][Management   ][08506…][reconnect] resolving connection...
[2021-02-27 09:41:05.824] [renderer1] [info] [remote-connection][ExtensionHost][2c3e4…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-02-27 09:41:05.824] [renderer1] [info] [remote-connection][ExtensionHost][2c3e4…][reconnect] resolving connection...
[2021-02-27 09:41:06.811] [renderer1] [info] [remote-connection][Management   ][08506…][reconnect] connecting to 172.22.122.213:44091...
[2021-02-27 09:41:06.811] [renderer1] [info] [remote-connection][ExtensionHost][2c3e4…][reconnect] connecting to 172.22.122.213:44091...
[2021-02-27 09:41:06.879] [renderer1] [error] [remote-connection][ExtensionHost][2c3e4…][reconnect][172.22.122.213:44091] received error control message when negotiating connection. Error:
[2021-02-27 09:41:06.879] [renderer1] [error] Error: Connection error: Unknown reconnection token
    at P (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:118683)
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:109747
    at u.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at a.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:16129)
    at i._receiveMessage (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:21434)
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:20477
    at u.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at c.acceptChunk (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13494)
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:12842
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:106179
    at u.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at FileReader._fileReader.onload (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:104796)
[2021-02-27 09:41:06.880] [renderer1] [error] [remote-connection][ExtensionHost][2c3e4…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
[2021-02-27 09:41:06.880] [renderer1] [error] Error: Connection error: Unknown reconnection token
    at P (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:118683)
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:109747
    at u.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at a.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:16129)
    at i._receiveMessage (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:21434)
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:20477
    at u.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at c.acceptChunk (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13494)
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:12842
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:106179
    at u.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at FileReader._fileReader.onload (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:104796)
[2021-02-27 09:41:16.449] [renderer1] [error] Unable to read file 'vscode-remote://wsl+ct2/root/phpactor/completion/lib/Bridge/TolerantParser/ReferenceFinder/NameSearcherCompletor.php' (Canceled: Canceled): Error: Unable to read file 'vscode-remote://wsl+ct2/root/phpactor/completion/lib/Bridge/TolerantParser/ReferenceFinder/NameSearcherCompletor.php' (Canceled: Canceled)
    at a.doReadAsFileStream (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:618:28471)
    at async E.doRead (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2105:31018)
    at async E.readStream (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2105:30671)
    at async Or.loadFromFile (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2099:48650)
[2021-02-27 09:41:17.744] [renderer1] [error] Unable to read file 'vscode-remote://wsl+ct2/root/phpactor/completion/lib/Bridge/TolerantParser/ReferenceFinder/NameSearcherCompletor.php' (Canceled: Canceled): Error: Unable to read file 'vscode-remote://wsl+ct2/root/phpactor/completion/lib/Bridge/TolerantParser/ReferenceFinder/NameSearcherCompletor.php' (Canceled: Canceled)
    at a.doReadAsFileStream (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:618:28471)
    at async E.doRead (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2105:31018)
    at async E.readStream (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2105:30671)
    at async Or.loadFromFile (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2099:48650)
[2021-02-27 09:45:54.819] [renderer1] [info] [remote-connection][Management   ][1c9bf…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-02-27 09:45:54.822] [renderer1] [info] [remote-connection][Management   ][1c9bf…][reconnect] resolving connection...
[2021-02-27 09:45:54.836] [renderer1] [info] [remote-connection][ExtensionHost][40fa6…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-02-27 09:45:54.837] [renderer1] [info] [remote-connection][ExtensionHost][40fa6…][reconnect] resolving connection...
[2021-02-27 09:45:54.848] [renderer1] [info] [remote-connection][Management   ][1c9bf…][reconnect] connecting to 172.22.122.213:44091...
[2021-02-27 09:45:54.852] [renderer1] [info] [remote-connection][ExtensionHost][40fa6…][reconnect] connecting to 172.22.122.213:44091...
[2021-02-27 09:46:01.000] [renderer1] [error] [remote-connection][Management   ][1c9bf…][reconnect][172.22.122.213:44091] socketFactory.connect() failed. Error:
[2021-02-27 09:46:01.001] [renderer1] [error] Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:105451)
[2021-02-27 09:46:01.001] [renderer1] [info] [remote-connection][Management   ][1c9bf…][reconnect] A temporarily not available error occurred while trying to reconnect, will try again...
[2021-02-27 09:46:01.001] [renderer1] [info] [remote-connection][Management   ][1c9bf…][reconnect] waiting for 5 seconds before reconnecting...
[2021-02-27 09:46:03.046] [renderer1] [error] [remote-connection][ExtensionHost][40fa6…][reconnect][172.22.122.213:44091] socketFactory.connect() failed. Error:
[2021-02-27 09:46:03.047] [renderer1] [error] Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:105451)
[2021-02-27 09:46:03.047] [renderer1] [info] [remote-connection][ExtensionHost][40fa6…][reconnect] A temporarily not available error occurred while trying to reconnect, will try again...
[2021-02-27 09:46:03.047] [renderer1] [info] [remote-connection][ExtensionHost][40fa6…][reconnect] waiting for 5 seconds before reconnecting...
[2021-02-27 09:46:06.004] [renderer1] [info] [remote-connection][Management   ][1c9bf…][reconnect] resolving connection...
[2021-02-27 09:46:06.342] [renderer1] [info] [remote-connection][Management   ][1c9bf…][reconnect] connecting to 172.22.122.213:46753...
[2021-02-27 09:46:06.397] [renderer1] [error] [remote-connection][Management   ][1c9bf…][reconnect][172.22.122.213:46753] received error control message when negotiating connection. Error:
[2021-02-27 09:46:06.397] [renderer1] [error] Error: Connection error: Unknown reconnection token
    at P (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:118683)
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:109747
    at u.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at a.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:16129)
    at i._receiveMessage (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:21434)
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:20477
    at u.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at c.acceptChunk (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13494)
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:12842
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:106179
    at u.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at FileReader._fileReader.onload (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:104796)
[2021-02-27 09:46:06.397] [renderer1] [error] [remote-connection][Management   ][1c9bf…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
[2021-02-27 09:46:06.397] [renderer1] [error] Error: Connection error: Unknown reconnection token
    at P (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:118683)
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:109747
    at u.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at a.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:16129)
    at i._receiveMessage (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:21434)
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:20477
    at u.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at c.acceptChunk (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13494)
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:12842
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:106179
    at u.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at FileReader._fileReader.onload (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:104796)
[2021-02-27 09:46:06.404] [renderer1] [error] Error: Unable to read file 'vscode-remote://wsl+ct2/root/.vscode-server/extensions/mblode.twig-language-0.9.2/src/snippets/snippets.json' (Canceled: Canceled)
    at a.doReadAsFileStream (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:618:28471)
    at async a.readFile (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:618:27576)
    at async k.readExtensionResource (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1386:4136)
    at async Promise.all (index 15)
    at async E.getSnippets (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1808:4771)
    at async g.provideCompletionItems (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:960:41128)
    at async file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:665:14467 vscode-remote://wsl%2Bct2/root/.vscode-server/extensions/mblode.twig-language-0.9.2/src/snippets/snippets.json
[2021-02-27 09:46:06.416] [renderer1] [error] Unable to read file 'vscode-remote://wsl+ct2/root/phpactor/indexer-extension/lib/Adapter/ReferenceFinder/IndexedNameSearcher.php' (Canceled: Canceled): Error: Unable to read file 'vscode-remote://wsl+ct2/root/phpactor/indexer-extension/lib/Adapter/ReferenceFinder/IndexedNameSearcher.php' (Canceled: Canceled)
    at a.doReadAsFileStream (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:618:28471)
    at async E.doRead (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2105:31018)
    at async E.readStream (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2105:30671)
    at async Or.loadFromFile (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2099:48650)
[2021-02-27 09:49:59.420] [renderer1] [info] [remote-connection][Management   ][24623…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-02-27 09:49:59.423] [renderer1] [info] [remote-connection][Management   ][24623…][reconnect] resolving connection...
[2021-02-27 09:49:59.429] [renderer1] [info] [remote-connection][Management   ][24623…][reconnect] connecting to 172.22.122.213:46753...
[2021-02-27 09:49:59.431] [renderer1] [info] [remote-connection][ExtensionHost][f33e2…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-02-27 09:49:59.431] [renderer1] [info] [remote-connection][ExtensionHost][f33e2…][reconnect] resolving connection...
[2021-02-27 09:49:59.431] [renderer1] [info] [remote-connection][ExtensionHost][f33e2…][reconnect] connecting to 172.22.122.213:46753...
[2021-02-27 09:50:01.481] [renderer1] [error] [remote-connection][Management   ][24623…][reconnect][172.22.122.213:46753] socketFactory.connect() failed. Error:
[2021-02-27 09:50:01.481] [renderer1] [error] Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:105451)
[2021-02-27 09:50:01.481] [renderer1] [info] [remote-connection][Management   ][24623…][reconnect] A temporarily not available error occurred while trying to reconnect, will try again...
[2021-02-27 09:50:01.482] [renderer1] [info] [remote-connection][Management   ][24623…][reconnect] waiting for 5 seconds before reconnecting...
[2021-02-27 09:50:03.527] [renderer1] [error] [remote-connection][ExtensionHost][f33e2…][reconnect][172.22.122.213:46753] socketFactory.connect() failed. Error:
[2021-02-27 09:50:03.527] [renderer1] [error] Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:105451)
[2021-02-27 09:50:03.527] [renderer1] [info] [remote-connection][ExtensionHost][f33e2…][reconnect] A temporarily not available error occurred while trying to reconnect, will try again...
[2021-02-27 09:50:03.527] [renderer1] [info] [remote-connection][ExtensionHost][f33e2…][reconnect] waiting for 5 seconds before reconnecting...
[2021-02-27 09:50:06.487] [renderer1] [info] [remote-connection][Management   ][24623…][reconnect] resolving connection...
[2021-02-27 09:50:06.880] [renderer1] [info] [remote-connection][Management   ][24623…][reconnect] connecting to 172.22.122.213:37381...
[2021-02-27 09:50:06.941] [renderer1] [error] [remote-connection][Management   ][24623…][reconnect][172.22.122.213:37381] received error control message when negotiating connection. Error:
[2021-02-27 09:50:06.941] [renderer1] [error] Error: Connection error: Unknown reconnection token
    at P (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:118683)
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:109747
    at u.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at a.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:16129)
    at i._receiveMessage (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:21434)
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:20477
    at u.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at c.acceptChunk (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13494)
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:12842
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:106179
    at u.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at FileReader._fileReader.onload (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:104796)
[2021-02-27 09:50:06.941] [renderer1] [error] [remote-connection][Management   ][24623…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
[2021-02-27 09:50:06.941] [renderer1] [error] Error: Connection error: Unknown reconnection token
    at P (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:118683)
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:109747
    at u.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at a.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:16129)
    at i._receiveMessage (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:21434)
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:20477
    at u.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at c.acceptChunk (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:13494)
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:12842
    at file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:106179
    at u.fire (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:55:1836)
    at FileReader._fileReader.onload (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:623:104796)
[2021-02-27 09:50:06.954] [renderer1] [error] Unable to read file 'vscode-remote://wsl+ct2/root/phpactor/indexer-extension/lib/Adapter/ReferenceFinder/IndexedNameSearcher.php' (Canceled: Canceled): Error: Unable to read file 'vscode-remote://wsl+ct2/root/phpactor/indexer-extension/lib/Adapter/ReferenceFinder/IndexedNameSearcher.php' (Canceled: Canceled)
    at a.doReadAsFileStream (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:618:28471)
    at async E.doRead (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2105:31018)
    at async E.readStream (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2105:30671)
    at async Or.loadFromFile (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2099:48650)
[2021-02-27 09:50:08.527] [renderer1] [error] [remote-connection][ExtensionHost][f33e2…][reconnect] permanent failure occurred while running the reconnecting loop.
[2021-02-27 09:52:54.249] [renderer1] [error] Unable to read file 'vscode-remote://wsl+ct2/root/phpactor/indexer-extension/lib/Adapter/ReferenceFinder/IndexedNameSearcher.php' (Canceled: Canceled): Error: Unable to read file 'vscode-remote://wsl+ct2/root/phpactor/indexer-extension/lib/Adapter/ReferenceFinder/IndexedNameSearcher.php' (Canceled: Canceled)
    at a.doReadAsFileStream (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:618:28471)
    at async E.doRead (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2105:31018)
    at async E.readStream (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2105:30671)
    at async Or.loadFromFile (file:///C:/Users/VladislavKosev/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2099:48650)
```
### Remote server (after reconnect)
```
[2021-02-27 09:50:01.846] [remoteagent] [info] 

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


[2021-02-27 09:50:01.846] [remoteagent] [info] Extension host agent started.
[2021-02-27 09:50:02.015] [remoteagent] [info] [::ffff:172.22.112.1][68564c89][ManagementConnection] New connection established.
[2021-02-27 09:50:02.051] [remoteagent] [info] [::ffff:172.22.112.1][843cec90][ExtensionHostConnection] New connection established.
[2021-02-27 09:50:03.309] [remoteagent] [info] [::ffff:172.22.112.1][843cec90][ExtensionHostConnection] <21186> Launched Extension Host Process.
[2021-02-27 09:50:06.939] [remoteagent] [error] [::ffff:172.22.112.1][24623d81][ManagementConnection] Unknown reconnection token.
[2021-02-27 09:53:43.942] [remoteagent] [info] [::ffff:172.22.112.1][8c8098a7][ManagementConnection] New connection established.
[2021-02-27 09:53:43.942] [remoteagent] [info] [::ffff:172.22.112.1][6186ef88][ExtensionHostConnection] New connection established.
[2021-02-27 09:53:43.947] [remoteagent] [info] [::ffff:172.22.112.1][6186ef88][ExtensionHostConnection] <21308> Launched Extension Host Process.
```

**Comment by BladeMF** [comment]
It would appear that it would depend on the projects being opened or something else which I can't figure out. Can it be the state of WSL? Whether I've been hybernated before or not?

Can you reopen this or should I open another one?

**Comment by bamurtaugh** [comment]
Thanks for the update @BladeMF. Does it sound like https://github.com/microsoft/vscode-remote-release/issues/3454 could be your issue?

**Comment by BladeMF** [comment]
@bamurtaugh , It's not impossible, although we do need to prove it somehow. Any ideas? I do hibernate a lot, but I never leave VS Code open during hibernation. I have my problem during plugin development and it is pretty annoying. :-(

**Comment by BladeMF** [comment]
UPDATE: @bamurtaugh, I just did a restart and the problem does not occur. This would mean that something happens after hibernation (I suppose) which makes reconnection unstable.
