### ISSUE TITLE
following the steps did not work

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-remote-release#4368]
Testing #4362

![recording (8)](https://user-images.githubusercontent.com/29464607/105874277-40721300-5fb1-11eb-9da7-d0abb80a561f.gif)

**Comment by meganrogge** [comment]
Note that when I try to open a folder (as the instructions suggest), the remote connection fails immediately.

**Comment by meganrogge** [comment]
here's the output

```
[08:36:06.622] > root@localhost's password: 
[08:36:06.622] Showing password prompt
[08:36:15.093] Got password response
[08:36:15.094] "install" wrote data to terminal: "****"
[08:36:15.094] > root@localhost's password:
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[08:36:15.095] Showing password prompt
[08:36:18.165] Got password response
[08:36:18.165] "install" wrote data to terminal: "****"
[08:36:18.166] > 
> 
[08:36:18.167] > Permission denied, please try again.
> root@localhost's password:
[08:36:18.167] Showing password prompt
[08:36:18.648] "install" terminal command done
[08:36:18.649] Install terminal quit with output: root@localhost's password:
[08:36:18.649] Received install output: root@localhost's password:
[08:36:18.650] Stopped parsing output early. Remaining text: root@localhost's password:
[08:36:18.650] Failed to parse remote port from server output
[08:36:18.654] Resolver error: Error: 
	at Function.Create (c:\Users\merogge\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:64027)
	at Object.t.handleInstallOutput (c:\Users\merogge\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:62766)
	at k (c:\Users\merogge\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:312915)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\merogge\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:310801
	at async Object.t.withShowDetailsEvent (c:\Users\merogge\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:405790)
	at async Object.t.resolve (c:\Users\merogge\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:314454)
	at async c:\Users\merogge\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:127:110333
[08:36:18.660] ------




[08:36:34.660] Password dialog canceled
[08:36:34.660] "install" terminal command canceled
[08:36:34.661] > 
> 
[08:36:34.661] > bash: command substitution: line 1: syntax error near unexpected token `[Text.Encoding]::Unicode.GetBytes'
> bash: command substitution: line 1: `[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes([Text.Encoding]::UTF8.GetString([Con
> vert]::FromBase64String('CiR1dWlkPSJiNGU5YjgxNTk1MDYiCiIke3V1aWR9OiBydW5uaW5nIgokUHJvZ3Jlc3NQcmVmZXJlbmNlPSdTaWxlbnRseUNvbnRpbnVlJwok
> bl89JzFhOWRkNzU4NTMwNzgyZWU0YmIwOWExNWJkYzQ4NGYzZGNiOWI1YTMnCiRwPSRlbnY6UFJPQ0VTU09SX0FSQ0hJVEVDVFVSRQokYXJjaD1pZiAoKCRwIC1lcSAnQU1EN
> jQnKSAtb3IgKCRwIC1lcSAnSUE2NCcpKSB7ICd4NjQnIH0gZWxzZSB7ICdpYTMyJyB9CiRvXz0oSm9pbi1QYXRoIChSZXNvbHZlLVBhdGggfikgJy52c2NvZGUtc2VydmVyLW
> luc2lkZXJzJykKJGVudjpWU0NPREVfQUdFTlRfRk9MREVSPSRvXwokbG9nPSIkb19cLiRuXy5sb2ciCiRhaV89IiRvX1wuJG5fLnRva2VuIgokc0Rpcj0iJG9fXGJpblwkbl8
> iCiRwXz0naW5zaWRlcicKJHFfPSIiCiRleHRzPSIiCiRnXz0kVHJ1ZQokaF89JEZhbHNlCiRnbG9iYWw6cl8gPSAkRmFsc2UKJGdsb2JhbDpzXyA9ICcnCiRnbG9iYWw6al8g
> PSAnJwokZ2xvYmFsOmtfID0gJycKJGdsb2JhbDpsXyA9ICcnCiRnbG9iYWw6bV8gPSAnJwokZ2xvYmFsOmFqXyA9ICcnCmZ1bmN0aW9uIGRldGFpbHMgewoibGlzdGVuaW5nT
> 249PSRwb3J0PT0iCiJvc1JlbGVhc2VJZD09d2luZG93cz09Igoib3NWZXJzaW9uPT0kYWhfPT0iCiJhcmNoPT0kYXJjaD09IgoicGxhdGZvcm09PXdpbmRvd3M9PSIKInVucG
> Fja1Jlc3VsdD09JHNfPT0iCiJkaWRMb2NhbERvd25sb2FkPT0kcl89PSIKImRvd25sb2FkVGltZT09JGpfPT0iCiJpbnN0YWxsVGltZT09JGtfPT0iCiJleHRJbnN0YWxsVGl
> tZT09JGxfPT0iCiJzZXJ2ZXJTdGFydFRpbWU9PSRtXz09Igp9CmZ1bmN0aW9uIGlfIHsKcmV0dXJuIFtzeXN0ZW0uZGlhZ25vc3RpY3Muc3RvcHdhdGNoXTo6U3RhcnROZXco
> KTsKfQpmdW5jdGlvbiBxKCRjb2RlKSB7CiIke3V1aWR9OiBzdGFydCIKImV4aXRDb2RlPT0kY29kZT09IgpkZXRhaWxzCiIke3V1aWR9OiBlbmQiCn0KZnVuY3Rpb24gYV8ge
> wokdF89JFBJRAp3aGlsZSAoJFRydWUpIHsKJHVfPShnY2ltIHdpbjMyX3Byb2Nlc3MgfCA/IHByb2Nlc3NpZCAtZXEgJHRfKS5wYXJlbnRwcm9jZXNzaWQKaWYgKCEkdV8pIH
> sKIm5vIHNzaGQgcGFyZW50IHByb2MiCmV4aXQgMAp9CmlmICgoZ3BzIC1JZCAkdV8pLk5hbWUgLWVxICdzc2hkJykgewpyZXR1cm4gJHVfCn0KJHRfPSR1Xwp9Cn0KZnVuY3R
> pb24gYl8gewppZiAoJHZfKSB7CmlmICghKGdwcyAtSWQgJHZfKSkgewoic2VydmVyIGRpZWQsIGV4aXQiCmV4aXQgMAp9Cn0gZWxzZSB7CmlmICghKGdwcyAtSWQgJHNzaGRQ
> SUQpKSB7CiJzc2hkIHBhcmVudCBkaWVkLCBleGl0IgpleGl0IDAKfQp9Cn0KZnVuY3Rpb24gY18gewokcz1pXwoiRG93bmxvYWRpbmcgc2VydmVyIgoiJHt1dWlkfSUlMSUlI
> gokd189IiIKJHhfPWlmICgkYXJjaCAtZXEgJ3g2NCcpIHsgIi0kYXJjaCIgfSBlbHNlIHsgIiIgfQokeV89InNlcnZlci13aW4zMiR4XyIgKyAkd18KJHNwbGF0PUB7ClVyaT
> 0iaHR0cHM6Ly91cGRhdGUuY29kZS52aXN1YWxzdHVkaW8uY29tL2NvbW1pdDokbl8vJHlfLyRwXyIKVGltZW91dFNlYz0yMApPdXRGaWxlPSJ2c2NvZGUtc2VydmVyLnppcCI
> KVXNlQmFzaWNQYXJzaW5nPSRUcnVlCn0KW05ldC5TZXJ2aWNlUG9pbnRNYW5hZ2VyXTo6U2VjdXJpdHlQcm90b2NvbCA9ICdUbHMxMicKaXJtIEBzcGxhdAokcy5TdG9wKCkK
> JGdsb2JhbDpqXyA9ICRzLkVsYXBzZWRNaWxsaXNlY29uZHMKfQpmdW5jdGlvbiBkXyB7CiRnbG9iYWw6c189J3N1Y2Nlc3MnCiRzPWlfCnRyeSB7CiR6Xz1bU3lzdGVtLklPL
> lBhdGhdOjpHZXRSYW5kb21GaWxlTmFtZSgpCiRhYV89IiRlbnY6VEVNUFwkel8iCiJFeHBhbmRpbmcgc2VydmVyIGludG8gJGFhXyIKIiR7dXVpZH0lJTIlJSIKRXhwYW5kLU
> FyY2hpdmUgInZzY29kZS1zZXJ2ZXIuemlwIiAtRGVzdGluYXRpb25QYXRoICIkYWFfIgptdiAiJGFhX1x2c2NvZGUtKlwqIiAtRGVzdGluYXRpb24gLgokcy5TdG9wKCkKJGd
> sb2JhbDprXyA9ICRzLkVsYXBzZWRNaWxsaXNlY29uZHMKfSBjYXRjaCB7CiRnbG9iYWw6c189J2Vycm9yJwoiRmFpbGVkIHRvIHVuemlwIHNlcnZlci4gLSAkKCRfLlRvU3Ry
[08:36:34.662] > 
> aW5nKCkpIgpmXyAzNwpkXwp9CmlmKCEoVGVzdC1QYXRoICIkc0RpclxzZXJ2ZXIuY21kIikpIHsKJGdsb2JhbDpzXz0nbWlzc2luZ0ZpbGVzJwoiRG93bmxvYWRlZCBzZXJ2Z
> XIgaXMgaW5jb21wbGV0ZS4iCmZfIDM3CmRfCn0KfQpmdW5jdGlvbiBha18gewokZ2xvYmFsOmFqXyA9ICJjOGQ2YjZkYS1hNWUyLTQwMjYtYjZlOC05MTQ0NzU2Y2QxZTIiCm
> 5pIC1pdCBmICRhaV8gLUZvcmNlCmljYWNscyAkYWlfIC9yZXNldCAvUQppY2FjbHMgJGFpXyAvc2V0b3duZXIgIiRlbnY6VVNFUk5BTUUiIC9RCmljYWNscyAkYWlfIC9ncmF
> udCAiJCgkZW52OlVTRVJOQU1FKTooUixXKSIgL1EKaWNhY2xzICRhaV8gL2luaGVyaXRhbmNlOnIgL1EKW1N5c3RlbS5JTy5GaWxlXTo6V3JpdGVBbGxMaW5lcygkYWlfLCAk
> Z2xvYmFsOmFqXykKfQpmdW5jdGlvbiBTdGFydFNlcnZlciB7CiRzPWlfCmlmKFRlc3QtUGF0aCAkbG9nKSB7CmRlbCAkbG9nCn0KJGFiXz0kc0RpciAtcmVwbGFjZSAnICcsI
> CdgICcKYWtfCiRhcmdzPSItLXN0YXJ0LXNlcnZlciAtLWhvc3Q9MTI3LjAuMC4xIC0tZW5hYmxlLXJlbW90ZS1hdXRvLXNodXRkb3duIC0tcG9ydD0wIC0tY29ubmVjdGlvbi
> 1zZWNyZXQgJGFpXyAkcV8gJGV4dHMgKj4gJyRsb2cnIgokc3BsYXQ9QHsKRmlsZVBhdGggPSAicG93ZXJzaGVsbC5leGUiCldpbmRvd1N0eWxlID0gImhpZGRlbiIKQXJndW1
> lbnRMaXN0ID0gQCgKIi1FeGVjdXRpb25Qb2xpY3kiLCAiVW5yZXN0cmljdGVkIiwgIi1Ob0xvZ28iLCAiLU5vUHJvZmlsZSIsICItTm9uSW50ZXJhY3RpdmUiLCAiLWMiLCAi
> JGFiX1xzZXJ2ZXIuY21kICRhcmdzIgopClBhc3NUaHJ1ID0gJFRydWUKfQoiU3RhcnRpbmcgc2VydmVyOiAmICckc0RpclxzZXJ2ZXIuY21kJyAkYXJncyIKJGdsb2JhbDp2X
> yA9IChzdGFydCBAc3BsYXQpLklECiRzLlN0b3AoKQokZ2xvYmFsOm1fID0gJHMuRWxhcHNlZE1pbGxpc2Vjb25kcwp9CmZ1bmN0aW9uIGVfIHsKJGdsb2JhbDpyXz0kVHJ1ZQ
> oiVHJpZ2dlciBsb2NhbCBzZXJ2ZXIgZG93bmxvYWQiCiIke3V1aWR9OnRyaWdnZXJfc2VydmVyX2Rvd25sb2FkIgoicGxhdGZvcm09PXdpbmRvd3M9PSIKInZzY29kZUFyY2g
> 9PSRhcmNoPT0iCiJkZXN0Rm9sZGVyPT0kc0Rpcj09IgoiJHt1dWlkfTp0cmlnZ2VyX3NlcnZlcl9kb3dubG9hZF9lbmQiCiJXYWl0aW5nIGZvciBjbGllbnQgdG8gdHJhbnNm
> ZXIgc2VydmVyIGFyY2hpdmUuLi4iCiJXYWl0aW5nIGZvciAkc0Rpclx2c2NvZGUtc2NwLWRvbmUuZmxhZyBhbmQgdnNjb2RlLXNlcnZlci56aXAgdG8gZXhpc3QiCndoaWxlK
> CRUcnVlKSB7CmlmKFRlc3QtUGF0aCAiJHNEaXJcdnNjb2RlLXNjcC1kb25lLmZsYWciKSB7CmlmKCEoVGVzdC1QYXRoICIkc0Rpclx2c2NvZGUtc2VydmVyLnppcCIpKSB7Ci
> JUcmFuc2ZlciBmYWlsZWQiCnEgMzEKfQoiVHJhbnNmZXIgY29tcGxldGUiCmRlbCAkc0Rpclx2c2NvZGUtc2NwLWRvbmUuZmxhZwpicmVhawp9IGVsc2UgewpTdGFydC1TbGV
> lcCAtU2Vjb25kcyAzCmJfCn0KfQp9CmZ1bmN0aW9uIGZfKCRjb2RlKSB7CmlmICgkcl8pIHsKIkFscmVhZHkgYXR0ZW1wdGVkIGxvY2FsIGRvd25sb2FkLCBmYWlsaW5nIgpx
[08:36:34.663] > 
> ICRjb2RlCn0gZWxzZWlmKCRnXykgewplXwp9IGVsc2UgewpxICRjb2RlCn0KfQpmdW5jdGlvbiBJbnN0YWxsRXh0ZW5zaW9ucyB7CmlmICgkZXh0cyAtbmUgIiIpIHsKJHM9a
> V8KJiAiJHNEaXJcc2VydmVyLmNtZCIgJHFfIAokcy5TdG9wKCkKJGdsb2JhbDpsXyA9ICRzLkVsYXBzZWRNaWxsaXNlY29uZHMKfQp9CiRzc2hkUElEPWFfCmlmKCEoVGVzdC
[08:36:34.664] > 
> 1QYXRoICRzRGlyKSkgewokbT0iQ291bGQgbm90IGNyZWF0ZSBzZXJ2ZXIgZGlyZWN0b3J5Igp0cnkgewokbnVsbD1uaSAtaXQgZCAkc0RpciAtZiAtZWEgc2kKfSBjYXRjaCB
> 7CiIkbS4gLSAkKCRfLlRvU3RyaW5nKCkpIgpyZXR1cm4KfQppZighKFRlc3QtUGF0aCAkc0RpcikpIHsKIiRtIgpyZXR1cm4KfQp9CmNkICRzRGlyCiRhY189KEpvaW4tUGF0
> aCAiJHNEaXIiICJ2c2NvZGUtcmVtb3RlLWxvY2suJG5fIikKdHJ5IHsKJG51bGw9bmkgJGFjXyAtaXQgZiAtZWEgc2kKfSBjYXRjaCB7CiJDb3VsZCBub3QgY3JlYXRlIHNlc
> nZlciBsb2NrIGZpbGUuIC0gJCgkXy5Ub1N0cmluZygpKSIKcmV0dXJuCn0KdHJ5IHsKIkFjcXVpcmluZyBsb2NrIG9uICRhY18iCiRmaWxlPVtTeXN0ZW0uaW8uRmlsZV06Ok
[08:36:34.665] > 
> 9wZW4oJGFjXywgJ09wZW4nLCAnUmVhZCcsICdOb25lJykKfSBjYXRjaCB7CiJJbnN0YWxsIGFscmVhZHkgaW4gcHJvZ3Jlc3MuLi4gLSAkKCRfLlRvU3RyaW5nKCkpIgpxIDI
> 0Cn0KdHJ5IHsKIkxvb2tpbmcgZm9yIGV4aXN0aW5nIHNlcnZlciBpbiAkc0RpciIKaWYoVGVzdC1QYXRoICIkc0RpclxzZXJ2ZXIuY21kIikgewoiRm91bmQgaW5zdGFsbGVk
> IHNlcnZlciIKfSBlbHNlIHsKaWYgKCRoXykgewplXwp9IGVsc2Ugewp0cnkgeyBjXyB9IGNhdGNoIHsKIkRvd25sb2FkIGZhaWxlZC4gLSAkKCRfLlRvU3RyaW5nKCkpIgpmX
> yAyNQp9Cn0KZF8KfQppZighKEdldC1Qcm9jZXNzIG5vZGUgLUVycm9yQWN0aW9uIFNpbGVudGx5Q29udGludWUgfCBXaGVyZS1PYmplY3QgUGF0aCAtbWF0Y2ggJG5fKSkgew
> pTdGFydFNlcnZlcgp9IGVsc2UgewoiU2VydmVyIHdpdGggJG5fIGlzIGFscmVhZHkgcnVubmluZy4iCkluc3RhbGxFeHRlbnNpb25zCmlmIChUZXN0LVBhdGggJGFpXykgewo
[08:36:34.666] > 
> kZ2xvYmFsOmFqXyA9ICQoY2F0ICRhaV8pCn0KfQokYWZfPUB7ClBhdGggPSAkbG9nClBhdHRlcm4gPSAiRXh0ZW5zaW9uIGhvc3QgYWdlbnQgbGlzdGVuaW5nIG9uIChcZCsp
> Igp9CiRhZV89QHsKUGF0aCA9ICRsb2cKUGF0dGVybiA9ICIhISEhIFNlcnZlciB0ZXJtaW5hdGVkIGR1ZSB0byBwcmVzZW5jZSBvZiBDVkUtMjAyMC0xNDE2ICEhISEiCn0KJ
> GFkXz0oR2V0LURhdGUpLkFkZFNlY29uZHMoNCkKd2hpbGUgKChHZXQtRGF0ZSkgLWx0ICRhZF8pIHsKaWYoVGVzdC1QYXRoICRsb2cpIHsKJGFnXz0oc2xzIEBhZl8pLk1hdG
> NoZXMuR3JvdXBzCmlmKCRhZ18pIHsKJHBvcnQ9JGFnX1sxXS5WYWx1ZQpicmVhawp9CiRmYWlsZWQ9KHNscyBAYWVfKS5NYXRjaGVzLkdyb3VwcwppZigkZmFpbGVkKSB7CiJ
> TZXJ2ZXIgZGlkIG5vdCBzdGFydCBzdWNjZXNzZnVsbHkuIEZ1bGwgc2VydmVyIGxvZyBhdCAkbG9nID4+PiIKY2F0ICRsb2cKIjw8PCBFbmQgb2Ygc2VydmVyIGxvZyIKcSAz
> Ngp9Cn0Kc2xlZXAgLU1pbGxpc2Vjb25kcyAzMAp9CmlmICghJHBvcnQpIHsKIlNlcnZlciBkaWQgbm90IHN0YXJ0IHN1Y2Nlc3NmdWxseS4gRnVsbCBzZXJ2ZXIgbG9nIGF0I
[08:36:34.667] > 
> CRsb2cgPj4+IgpjYXQgJGxvZwoiPDw8IEVuZCBvZiBzZXJ2ZXIgbG9nIgpxIDMyCn0KfSBjYXRjaCB7CiJTZXJ2ZXIgZmFpbGVkIHRvIHN0YXJ0LiAtICQoJF8uVG9TdHJpbm
> coKSkiCn0gZmluYWxseSB7CiRmaWxlLkNsb3NlKCkKfQp0cnkgewokYWhfPShnY2ltIFdpbjMyX09wZXJhdGluZ1N5c3RlbSkuVmVyc2lvbgp9IGNhdGNoIHsKIkZhaWxlZCB
> 0byBmaW5kIFdpbmRvd3MgdmVyc2lvbiAtICQoJF8uVG9TdHJpbmcoKSkiCiRhaF89InVua25vd24iCn0KIiR7dXVpZH06IHN0YXJ0Igoic3NoQXV0aFNvY2s9PSRlbnY6U1NI
> X0FVVEhfU09DSz09IgpkZXRhaWxzCiJjb25uZWN0aW9uVG9rZW49PSRnbG9iYWw6YWpfPT0iCiIke3V1aWR9OiBlbmQiCiJJbnN0YWxsIHNjcmlwdCBpcyAkcGlkLCB3YXRja
> GluZyBzc2hkIHBhcmVudCAkc3NoZFBJRCIKd2hpbGUgKCRUcnVlKSB7CmJfCnNsZWVwIDMwCn0K')))))'
```
>

**Comment by meganrogge** [comment]
since then, have also tried with powershell. that resulted in this:

```
[08:43:51.687] "install" terminal command done
[08:43:51.688] Install terminal quit with output: 0K')))))'
[08:43:51.689] Received install output: 0K')))))'
[08:43:51.690] Stopped parsing output early. Remaining text: 0K')))))'
[08:43:51.690] Failed to parse remote port from server output
[08:43:51.700] Resolver error: Error: 
	at Function.Create (c:\Users\merogge\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:64027)
	at Object.t.handleInstallOutput (c:\Users\merogge\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:62766)
	at k (c:\Users\merogge\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:312915)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\merogge\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:310801
	at async Object.t.withShowDetailsEvent (c:\Users\merogge\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:405790)
	at async Object.t.resolve (c:\Users\merogge\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:314454)
	at async c:\Users\merogge\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:127:110333
[08:43:51.711] ------
```

**Comment by roblourens** [comment]
It looks like you are connecting to a linux remote, but you picked Windows, the error shows bash failing to run a powershell command. You can set `"remote.SSH.useLocalServer": true` in json so you don't have to pick the host OS manually
