### ISSUE TITLE
every possible error on remote SSH vscode and insider

### ISSUE THREAD

**Issue by m1613** [microsoft/vscode-remote-release#4376]
hiii, 
kinda tired of facing error since 48 hrs, needed to develop on a server, searched everywhere, used vscode and insider too, 

used ftp extensions,
used remote SSH extensions,

first, got connected but suddenly website went down - error 503- server busy try again- in ssh terminal- failed to allocate memory /checked server-used max resources/,
      , The process tried to write to a nonexistent pipe,
      , got timeout error too
      , terminal related errors couple of times,

Got success for a minute-yet after some minutes in coding- tried to save- no response and error again.
frustrating to setup- when to code? 

my last attempt vscode remote ssh log: 

`[00:28:05.221] Log Level: 2
[00:28:05.225] remote-ssh@0.63.0
[00:28:05.225] win32 x64
[00:28:05.227] SSH Resolver called for "ssh-remote+XXX:XXX:XXX.0", attempt 1
[00:28:05.229] "remote.SSH.useLocalServer": false
[00:28:05.230] "remote.SSH.showLoginTerminal": false
[00:28:05.231] "remote.SSH.remotePlatform": {"XXX:XXX:XXX.0":"linux"}
[00:28:05.231] "remote.SSH.sshPath": undefined
[00:28:05.232] "remote.SSH.sshConfigurationFile": undefined
[00:28:05.232] "remote.SSH.useFlock": true
[00:28:05.233] "remote.SSH.lockfilesInTmp": false
[00:28:05.233] "remote.SSH.localServerDownload": auto
[00:28:05.234] "remote.SSH.remoteServerListenOnSocket": false
[00:28:05.234] "remote.SSH.showLoginTerminal": false
[00:28:05.235] SSH Resolver called for host: XXX:XXX:XXX.0
[00:28:05.235] Setting up SSH remote "XXX:XXX:XXX.0"
[00:28:05.267] Using commit id "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" and quality "insider" for server
[00:28:05.276] Install and start server if needed
[00:28:05.287] Checking ssh with "ssh -V"
[00:28:05.428] > OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2

[00:28:05.441] Running script with connection command: ssh -T -D 54127 "XXX:XXX:XXX:XXX" bash
[00:28:05.455] Terminal shell path: C:\Windows\System32\cmd.exe
[00:28:05.624] > 
[00:28:05.624] Got some output, clearing connection timeout
[00:28:32.367] > ssh_dispatch_run_fatal: Connection to XXX:XXX:XXX:0 port 65002: Connection timed out
> 
[00:28:32.522] > The process tried to write to a nonexistent pipe.
> 
[00:28:32.818] "install" terminal command done
[00:28:32.820] Install terminal quit with output: The process tried to write to a nonexistent pipe.
[00:28:32.820] Received install output: The process tried to write to a nonexistent pipe.
[00:28:32.832] Resolver error: Error: The process tried to write to a nonexistent pipe
	at Function.Offline (c:\Users\Administrator\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:64081)
	at c:\Users\Administrator\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:61667
	at Object.t.handleInstallOutput (c:\Users\Administrator\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:62045)
	at k (c:\Users\Administrator\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:312915)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\Administrator\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:310801
	at async Object.t.withShowDetailsEvent (c:\Users\Administrator\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:405790)
	at async Object.t.resolve (c:\Users\Administrator\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:314454)
	at async c:\Users\Administrator\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:127:110333
[00:28:32.856] ------
`

Plz- its the last attempt log- previously i setup a better configuration - true and falses.

Need some immediate suggestion from fellow coders- 
I need remote access to linux server- it only allows me tmp folder access to write, and public folder, and wont even give me root access(but offers SSH and FTP), is there a way any tools and method available i can use to get what remote SSH is supposed to give----any alternatives?

tried vscode in kali- there is also error- _apt doesnot have sudo permission to write in vscode or in a directory related to gpg key or something while installing vscode.deb

sick and tired, 

any leads, thanks in advance.

**Comment by roblourens** [comment]
`ssh_dispatch_run_fatal: Connection to XXX:XXX:XXX:0 port 65002: Connection timed out`

I think this just implies that ssh wasn't able to connect to the host. If you can run a command like `echo uname | ssh yourhost` and get a response, then Remote-SSH should work.

> I need remote access to linux server- it only allows me tmp folder access to write, and public folder, and wont even give me root access(but offers SSH and FTP

Sorry, don't totally understand what you are asking
