### ISSUE TITLE
Failed to parse remote port from server output

### ISSUE THREAD

**Issue by arttet** [microsoft/vscode-remote-release#4420]
I cannot connect to virtual machines using `vscode-remote`.
However, I am able to connect to those virtual machines using `ssh`, `MobaXterm`.

I have received the following error:
```sh
Failed to parse remote port from server output
Resolver error: Error: 
	at Function.Create (%USER%\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:64027)
	at Object.t.handleInstallOutput (%USER%\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:62766)
	at k (%USER%\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:312915)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async %USER%\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:310801
	at async Object.t.withShowDetailsEvent (%USER%\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:405790)
	at async Object.t.resolve (%USER%\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:314454)
	at async %USER%\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:127:110333
```

- VSCode Version: 1.52.1
- Local OS Version: Windows 10
- Remote OS Version: Windows Server 2012 R2, Windows 10 
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Add data to %USER%\.ssh\config
```sh
Host vm
  HostName 10.10.1.1
  User user
  Port 3322
  ForwardAgent yes
  IdentityFile ~/.ssh/id_rsa
```
2. Connect to `vm`

Does this issue occur when you try this locally?: Yes

**Comment by roblourens** [comment]
Please share the full log from the Remote-SSH output channel

**Comment by arttet** [comment]
@roblourens, I hope it will help you.

```sh
[15:42:29.184] Log Level: 2
[15:42:29.184] remote-ssh@0.63.0
[15:42:29.185] win32 x64
[15:42:29.186] SSH Resolver called for "ssh-remote+ciwin-12-64-117", attempt 1
[15:42:29.186] "remote.SSH.useLocalServer": false
[15:42:29.186] "remote.SSH.showLoginTerminal": false
[15:42:29.187] "remote.SSH.remotePlatform": {"ciwin-12-64-116":"windows","ciwin-12-64-117":"windows"}
[15:42:29.187] "remote.SSH.sshPath": undefined
[15:42:29.187] "remote.SSH.sshConfigurationFile": undefined
[15:42:29.187] "remote.SSH.useFlock": true
[15:42:29.187] "remote.SSH.lockfilesInTmp": false
[15:42:29.187] "remote.SSH.localServerDownload": auto
[15:42:29.187] "remote.SSH.remoteServerListenOnSocket": false
[15:42:29.187] "remote.SSH.showLoginTerminal": false
[15:42:29.188] SSH Resolver called for host: ciwin-12-64-117
[15:42:29.188] Setting up SSH remote "ciwin-12-64-117"
[15:42:29.191] Using commit id "8490d3dde47c57ba65ec40dd192d014fd2113496" and quality "stable" for server
[15:42:29.193] Install and start server if needed
[15:42:29.223] Checking ssh with "ssh -V"
[15:42:29.584] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[15:42:29.633] Remote command length: 8116/8192 characters
[15:42:29.634] Running script with connection command: ssh -T -D 49223 "ciwin-12-64-117" powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -Command "powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -EncodedCommand $([Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('CiR1dWlkPSJjNzhkZDVhMDYxY2UiCiIke3V1aWR9OiBydW5uaW5nIgokUHJvZ3Jlc3NQcmVmZXJlbmNlPSdTaWxlbnRseUNvbnRpbnVlJwokbl89Jzg0OTBkM2RkZTQ3YzU3YmE2NWVjNDBkZDE5MmQwMTRmZDIxMTM0OTYnCiRwPSRlbnY6UFJPQ0VTU09SX0FSQ0hJVEVDVFVSRQokYXJjaD1pZiAoKCRwIC1lcSAnQU1ENjQnKSAtb3IgKCRwIC1lcSAnSUE2NCcpKSB7ICd4NjQnIH0gZWxzZSB7ICdpYTMyJyB9CiRvXz0oSm9pbi1QYXRoIChSZXNvbHZlLVBhdGggfikgJy52c2NvZGUtc2VydmVyJykKJGVudjpWU0NPREVfQUdFTlRfRk9MREVSPSRvXwokbG9nPSIkb19cLiRuXy5sb2ciCiRhaV89IiRvX1wuJG5fLnRva2VuIgokc0Rpcj0iJG9fXGJpblwkbl8iCiRwXz0nc3RhYmxlJwokcV89Ii0tZGlzYWJsZS10ZWxlbWV0cnkiCiRleHRzPSIiCiRnXz0kVHJ1ZQokaF89JEZhbHNlCiRnbG9iYWw6cl8gPSAkRmFsc2UKJGdsb2JhbDpzXyA9ICcnCiRnbG9iYWw6al8gPSAnJwokZ2xvYmFsOmtfID0gJycKJGdsb2JhbDpsXyA9ICcnCiRnbG9iYWw6bV8gPSAnJwokZ2xvYmFsOmFqXyA9ICcnCmZ1bmN0aW9uIGRldGFpbHMgewoibGlzdGVuaW5nT249PSRwb3J0PT0iCiJvc1JlbGVhc2VJZD09d2luZG93cz09Igoib3NWZXJzaW9uPT0kYWhfPT0iCiJhcmNoPT0kYXJjaD09IgoicGxhdGZvcm09PXdpbmRvd3M9PSIKInVucGFja1Jlc3VsdD09JHNfPT0iCiJkaWRMb2NhbERvd25sb2FkPT0kcl89PSIKImRvd25sb2FkVGltZT09JGpfPT0iCiJpbnN0YWxsVGltZT09JGtfPT0iCiJleHRJbnN0YWxsVGltZT09JGxfPT0iCiJzZXJ2ZXJTdGFydFRpbWU9PSRtXz09Igp9CmZ1bmN0aW9uIGlfIHsKcmV0dXJuIFtzeXN0ZW0uZGlhZ25vc3RpY3Muc3RvcHdhdGNoXTo6U3RhcnROZXcoKTsKfQpmdW5jdGlvbiBxKCRjb2RlKSB7CiIke3V1aWR9OiBzdGFydCIKImV4aXRDb2RlPT0kY29kZT09IgpkZXRhaWxzCiIke3V1aWR9OiBlbmQiCn0KZnVuY3Rpb24gYV8gewokdF89JFBJRAp3aGlsZSAoJFRydWUpIHsKJHVfPShnY2ltIHdpbjMyX3Byb2Nlc3MgfCA/IHByb2Nlc3NpZCAtZXEgJHRfKS5wYXJlbnRwcm9jZXNzaWQKaWYgKCEkdV8pIHsKIm5vIHNzaGQgcGFyZW50IHByb2MiCmV4aXQgMAp9CmlmICgoZ3BzIC1JZCAkdV8pLk5hbWUgLWVxICdzc2hkJykgewpyZXR1cm4gJHVfCn0KJHRfPSR1Xwp9Cn0KZnVuY3Rpb24gYl8gewppZiAoJHZfKSB7CmlmICghKGdwcyAtSWQgJHZfKSkgewoic2VydmVyIGRpZWQsIGV4aXQiCmV4aXQgMAp9Cn0gZWxzZSB7CmlmICghKGdwcyAtSWQgJHNzaGRQSUQpKSB7CiJzc2hkIHBhcmVudCBkaWVkLCBleGl0IgpleGl0IDAKfQp9Cn0KZnVuY3Rpb24gY18gewokcz1pXwoiRG93bmxvYWRpbmcgc2VydmVyIgoiJHt1dWlkfSUlMSUlIgokd189IiIKJHhfPWlmICgkYXJjaCAtZXEgJ3g2NCcpIHsgIi0kYXJjaCIgfSBlbHNlIHsgIiIgfQokeV89InNlcnZlci13aW4zMiR4XyIgKyAkd18KJHNwbGF0PUB7ClVyaT0iaHR0cHM6Ly91cGRhdGUuY29kZS52aXN1YWxzdHVkaW8uY29tL2NvbW1pdDokbl8vJHlfLyRwXyIKVGltZW91dFNlYz0yMApPdXRGaWxlPSJ2c2NvZGUtc2VydmVyLnppcCIKVXNlQmFzaWNQYXJzaW5nPSRUcnVlCn0KW05ldC5TZXJ2aWNlUG9pbnRNYW5hZ2VyXTo6U2VjdXJpdHlQcm90b2NvbCA9ICdUbHMxMicKaXJtIEBzcGxhdAokcy5TdG9wKCkKJGdsb2JhbDpqXyA9ICRzLkVsYXBzZWRNaWxsaXNlY29uZHMKfQpmdW5jdGlvbiBkXyB7CiRnbG9iYWw6c189J3N1Y2Nlc3MnCiRzPWlfCnRyeSB7CiR6Xz1bU3lzdGVtLklPLlBhdGhdOjpHZXRSYW5kb21GaWxlTmFtZSgpCiRhYV89IiRlbnY6VEVNUFwkel8iCiJFeHBhbmRpbmcgc2VydmVyIGludG8gJGFhXyIKIiR7dXVpZH0lJTIlJSIKRXhwYW5kLUFyY2hpdmUgInZzY29kZS1zZXJ2ZXIuemlwIiAtRGVzdGluYXRpb25QYXRoICIkYWFfIgptdiAiJGFhX1x2c2NvZGUtKlwqIiAtRGVzdGluYXRpb24gLgokcy5TdG9wKCkKJGdsb2JhbDprXyA9ICRzLkVsYXBzZWRNaWxsaXNlY29uZHMKfSBjYXRjaCB7CiRnbG9iYWw6c189J2Vycm9yJwoiRmFpbGVkIHRvIHVuemlwIHNlcnZlci4gLSAkKCRfLlRvU3RyaW5nKCkpIgpmXyAzNwpkXwp9CmlmKCEoVGVzdC1QYXRoICIkc0RpclxzZXJ2ZXIuY21kIikpIHsKJGdsb2JhbDpzXz0nbWlzc2luZ0ZpbGVzJwoiRG93bmxvYWRlZCBzZXJ2ZXIgaXMgaW5jb21wbGV0ZS4iCmZfIDM3CmRfCn0KfQpmdW5jdGlvbiBha18gewokZ2xvYmFsOmFqXyA9ICJiMmUzZThiYi02MDY1LTRiMTgtODRkNS1mODBmN2E2MjRkZGQiCm5pIC1pdCBmICRhaV8gLUZvcmNlCmljYWNscyAkYWlfIC9yZXNldCAvUQppY2FjbHMgJGFpXyAvc2V0b3duZXIgIiRlbnY6VVNFUk5BTUUiIC9RCmljYWNscyAkYWlfIC9ncmFudCAiJCgkZW52OlVTRVJOQU1FKTooUixXKSIgL1EKaWNhY2xzICRhaV8gL2luaGVyaXRhbmNlOnIgL1EKW1N5c3RlbS5JTy5GaWxlXTo6V3JpdGVBbGxMaW5lcygkYWlfLCAkZ2xvYmFsOmFqXykKfQpmdW5jdGlvbiBTdGFydFNlcnZlciB7CiRzPWlfCmlmKFRlc3QtUGF0aCAkbG9nKSB7CmRlbCAkbG9nCn0KJGFiXz0kc0RpciAtcmVwbGFjZSAnICcsICdgICcKYWtfCiRhcmdzPSItLXN0YXJ0LXNlcnZlciAtLWhvc3Q9MTI3LjAuMC4xIC0tZW5hYmxlLXJlbW90ZS1hdXRvLXNodXRkb3duIC0tcG9ydD0wIC0tY29ubmVjdGlvbi1zZWNyZXQgJGFpXyAkcV8gJGV4dHMgKj4gJyRsb2cnIgokc3BsYXQ9QHsKRmlsZVBhdGggPSAicG93ZXJzaGVsbC5leGUiCldpbmRvd1N0eWxlID0gImhpZGRlbiIKQXJndW1lbnRMaXN0ID0gQCgKIi1FeGVjdXRpb25Qb2xpY3kiLCAiVW5yZXN0cmljdGVkIiwgIi1Ob0xvZ28iLCAiLU5vUHJvZmlsZSIsICItTm9uSW50ZXJhY3RpdmUiLCAiLWMiLCAiJGFiX1xzZXJ2ZXIuY21kICRhcmdzIgopClBhc3NUaHJ1ID0gJFRydWUKfQoiU3RhcnRpbmcgc2VydmVyOiAmICckc0RpclxzZXJ2ZXIuY21kJyAkYXJncyIKJGdsb2JhbDp2XyA9IChzdGFydCBAc3BsYXQpLklECiRzLlN0b3AoKQokZ2xvYmFsOm1fID0gJHMuRWxhcHNlZE1pbGxpc2Vjb25kcwp9CmZ1bmN0aW9uIGVfIHsKJGdsb2JhbDpyXz0kVHJ1ZQoiVHJpZ2dlciBsb2NhbCBzZXJ2ZXIgZG93bmxvYWQiCiIke3V1aWR9OnRyaWdnZXJfc2VydmVyX2Rvd25sb2FkIgoicGxhdGZvcm09PXdpbmRvd3M9PSIKInZzY29kZUFyY2g9PSRhcmNoPT0iCiJkZXN0Rm9sZGVyPT0kc0Rpcj09IgoiJHt1dWlkfTp0cmlnZ2VyX3NlcnZlcl9kb3dubG9hZF9lbmQiCiJXYWl0aW5nIGZvciBjbGllbnQgdG8gdHJhbnNmZXIgc2VydmVyIGFyY2hpdmUuLi4iCiJXYWl0aW5nIGZvciAkc0Rpclx2c2NvZGUtc2NwLWRvbmUuZmxhZyBhbmQgdnNjb2RlLXNlcnZlci56aXAgdG8gZXhpc3QiCndoaWxlKCRUcnVlKSB7CmlmKFRlc3QtUGF0aCAiJHNEaXJcdnNjb2RlLXNjcC1kb25lLmZsYWciKSB7CmlmKCEoVGVzdC1QYXRoICIkc0Rpclx2c2NvZGUtc2VydmVyLnppcCIpKSB7CiJUcmFuc2ZlciBmYWlsZWQiCnEgMzEKfQoiVHJhbnNmZXIgY29tcGxldGUiCmRlbCAkc0Rpclx2c2NvZGUtc2NwLWRvbmUuZmxhZwpicmVhawp9IGVsc2UgewpTdGFydC1TbGVlcCAtU2Vjb25kcyAzCmJfCn0KfQp9CmZ1bmN0aW9uIGZfKCRjb2RlKSB7CmlmICgkcl8pIHsKIkFscmVhZHkgYXR0ZW1wdGVkIGxvY2FsIGRvd25sb2FkLCBmYWlsaW5nIgpxICRjb2RlCn0gZWxzZWlmKCRnXykgewplXwp9IGVsc2UgewpxICRjb2RlCn0KfQpmdW5jdGlvbiBJbnN0YWxsRXh0ZW5zaW9ucyB7CmlmICgkZXh0cyAtbmUgIiIpIHsKJHM9aV8KJiAiJHNEaXJcc2VydmVyLmNtZCIgJHFfIAokcy5TdG9wKCkKJGdsb2JhbDpsXyA9ICRzLkVsYXBzZWRNaWxsaXNlY29uZHMKfQp9CiRzc2hkUElEPWFfCmlmKCEoVGVzdC1QYXRoICRzRGlyKSkgewokbT0iQ291bGQgbm90IGNyZWF0ZSBzZXJ2ZXIgZGlyZWN0b3J5Igp0cnkgewokbnVsbD1uaSAtaXQgZCAkc0RpciAtZiAtZWEgc2kKfSBjYXRjaCB7CiIkbS4gLSAkKCRfLlRvU3RyaW5nKCkpIgpyZXR1cm4KfQppZighKFRlc3QtUGF0aCAkc0RpcikpIHsKIiRtIgpyZXR1cm4KfQp9CmNkICRzRGlyCiRhY189KEpvaW4tUGF0aCAiJHNEaXIiICJ2c2NvZGUtcmVtb3RlLWxvY2suJG5fIikKdHJ5IHsKJG51bGw9bmkgJGFjXyAtaXQgZiAtZWEgc2kKfSBjYXRjaCB7CiJDb3VsZCBub3QgY3JlYXRlIHNlcnZlciBsb2NrIGZpbGUuIC0gJCgkXy5Ub1N0cmluZygpKSIKcmV0dXJuCn0KdHJ5IHsKIkFjcXVpcmluZyBsb2NrIG9uICRhY18iCiRmaWxlPVtTeXN0ZW0uaW8uRmlsZV06Ok9wZW4oJGFjXywgJ09wZW4nLCAnUmVhZCcsICdOb25lJykKfSBjYXRjaCB7CiJJbnN0YWxsIGFscmVhZHkgaW4gcHJvZ3Jlc3MuLi4gLSAkKCRfLlRvU3RyaW5nKCkpIgpxIDI0Cn0KdHJ5IHsKIkxvb2tpbmcgZm9yIGV4aXN0aW5nIHNlcnZlciBpbiAkc0RpciIKaWYoVGVzdC1QYXRoICIkc0RpclxzZXJ2ZXIuY21kIikgewoiRm91bmQgaW5zdGFsbGVkIHNlcnZlciIKfSBlbHNlIHsKaWYgKCRoXykgewplXwp9IGVsc2Ugewp0cnkgeyBjXyB9IGNhdGNoIHsKIkRvd25sb2FkIGZhaWxlZC4gLSAkKCRfLlRvU3RyaW5nKCkpIgpmXyAyNQp9Cn0KZF8KfQppZighKEdldC1Qcm9jZXNzIG5vZGUgLUVycm9yQWN0aW9uIFNpbGVudGx5Q29udGludWUgfCBXaGVyZS1PYmplY3QgUGF0aCAtbWF0Y2ggJG5fKSkgewpTdGFydFNlcnZlcgp9IGVsc2UgewoiU2VydmVyIHdpdGggJG5fIGlzIGFscmVhZHkgcnVubmluZy4iCkluc3RhbGxFeHRlbnNpb25zCmlmIChUZXN0LVBhdGggJGFpXykgewokZ2xvYmFsOmFqXyA9ICQoY2F0ICRhaV8pCn0KfQokYWZfPUB7ClBhdGggPSAkbG9nClBhdHRlcm4gPSAiRXh0ZW5zaW9uIGhvc3QgYWdlbnQgbGlzdGVuaW5nIG9uIChcZCspIgp9CiRhZV89QHsKUGF0aCA9ICRsb2cKUGF0dGVybiA9ICIhISEhIFNlcnZlciB0ZXJtaW5hdGVkIGR1ZSB0byBwcmVzZW5jZSBvZiBDVkUtMjAyMC0xNDE2ICEhISEiCn0KJGFkXz0oR2V0LURhdGUpLkFkZFNlY29uZHMoNCkKd2hpbGUgKChHZXQtRGF0ZSkgLWx0ICRhZF8pIHsKaWYoVGVzdC1QYXRoICRsb2cpIHsKJGFnXz0oc2xzIEBhZl8pLk1hdGNoZXMuR3JvdXBzCmlmKCRhZ18pIHsKJHBvcnQ9JGFnX1sxXS5WYWx1ZQpicmVhawp9CiRmYWlsZWQ9KHNscyBAYWVfKS5NYXRjaGVzLkdyb3VwcwppZigkZmFpbGVkKSB7CiJTZXJ2ZXIgZGlkIG5vdCBzdGFydCBzdWNjZXNzZnVsbHkuIEZ1bGwgc2VydmVyIGxvZyBhdCAkbG9nID4+PiIKY2F0ICRsb2cKIjw8PCBFbmQgb2Ygc2VydmVyIGxvZyIKcSAzNgp9Cn0Kc2xlZXAgLU1pbGxpc2Vjb25kcyAzMAp9CmlmICghJHBvcnQpIHsKIlNlcnZlciBkaWQgbm90IHN0YXJ0IHN1Y2Nlc3NmdWxseS4gRnVsbCBzZXJ2ZXIgbG9nIGF0ICRsb2cgPj4+IgpjYXQgJGxvZwoiPDw8IEVuZCBvZiBzZXJ2ZXIgbG9nIgpxIDMyCn0KfSBjYXRjaCB7CiJTZXJ2ZXIgZmFpbGVkIHRvIHN0YXJ0LiAtICQoJF8uVG9TdHJpbmcoKSkiCn0gZmluYWxseSB7CiRmaWxlLkNsb3NlKCkKfQp0cnkgewokYWhfPShnY2ltIFdpbjMyX09wZXJhdGluZ1N5c3RlbSkuVmVyc2lvbgp9IGNhdGNoIHsKIkZhaWxlZCB0byBmaW5kIFdpbmRvd3MgdmVyc2lvbiAtICQoJF8uVG9TdHJpbmcoKSkiCiRhaF89InVua25vd24iCn0KIiR7dXVpZH06IHN0YXJ0Igoic3NoQXV0aFNvY2s9PSRlbnY6U1NIX0FVVEhfU09DSz09IgpkZXRhaWxzCiJjb25uZWN0aW9uVG9rZW49PSRnbG9iYWw6YWpfPT0iCiIke3V1aWR9OiBlbmQiCiJJbnN0YWxsIHNjcmlwdCBpcyAkcGlkLCB3YXRjaGluZyBzc2hkIHBhcmVudCAkc3NoZFBJRCIKd2hpbGUgKCRUcnVlKSB7CmJfCnNsZWVwIDMwCn0K')))))"  # RemoteSSHConfigurationScript
[15:42:29.635] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:42:30.826] > The command line is too long.
> ]0;C:\WINDOWS\System32\cmd.exe
[15:42:30.826] Got some output, clearing connection timeout
[15:42:31.267] "install" terminal command done
[15:42:31.267] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exe
[15:42:31.268] Received install output: ]0;C:\WINDOWS\System32\cmd.exe
[15:42:31.268] Stopped parsing output early. Remaining text: ]0;C:\WINDOWS\System32\cmd.exe
[15:42:31.268] Failed to parse remote port from server output
[15:42:31.271] Resolver error: Error: 
	at Function.Create (c:\Users\arttet\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:64027)
	at Object.t.handleInstallOutput (c:\Users\arttet\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:62766)
	at k (c:\Users\arttet\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:312915)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\arttet\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:310801
	at async Object.t.withShowDetailsEvent (c:\Users\arttet\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:405790)
	at async Object.t.resolve (c:\Users\arttet\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:314454)
	at async c:\Users\arttet\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:127:110333
[15:42:31.273] ------
```

**Comment by roblourens** [comment]
This is fixed in the Nightly version of the SSH extension. Will have a new stable release soon.
