### ISSUE TITLE
Cannot connect ssh on remote linux host

### ISSUE THREAD

**Issue by angelitoTalens** [microsoft/vscode-remote-release#4423]
Issue Type: <b>Bug</b>

trying to connect to remote ssh linux that works before but suddenly not working

Failed to parse remote port from server output
[21:16:28.243] Resolver error: Error: 
	at Function.Create (c:\Users\atalens\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:64027)
	at Object.t.handleInstallOutput (c:\Users\atalens\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:62766)
	at k (c:\Users\atalens\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:312915)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\atalens\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:310801
	at async Object.t.withShowDetailsEvent (c:\Users\atalens\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:405790)
	at async Object.t.resolve (c:\Users\atalens\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:314454)
	at async c:\Users\atalens\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:127:110333

Extension version: 0.63.0
VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (8.26GB free)|
|Process Argv|--crash-reporter-id 8fbb27ad-7bf2-4c7f-8902-b3834e90e7b1|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Please share the full log from the Remote-SSH output channel

**Comment by angelitoTalens** [comment]
> Please share the full log from the Remote-SSH output channel

[09:35:09.804] Log Level: 2
[09:35:09.805] remote-ssh@0.63.0
[09:35:09.805] win32 x64
[09:35:09.805] SSH Resolver called for "ssh-remote+sydlnxv004", attempt 1
[09:35:09.806] "remote.SSH.useLocalServer": false
[09:35:09.806] "remote.SSH.showLoginTerminal": false
[09:35:09.806] "remote.SSH.remotePlatform": {"sydlnxv004":"linux"}
[09:35:09.806] "remote.SSH.sshPath": C:\Program Files\Git\usr\bin\ssh.exe
[09:35:09.806] "remote.SSH.sshConfigurationFile": undefined
[09:35:09.806] "remote.SSH.useFlock": true
[09:35:09.806] "remote.SSH.lockfilesInTmp": false
[09:35:09.806] "remote.SSH.localServerDownload": auto
[09:35:09.806] "remote.SSH.remoteServerListenOnSocket": false
[09:35:09.807] "remote.SSH.showLoginTerminal": false
[09:35:09.807] SSH Resolver called for host: sydlnxv004
[09:35:09.807] Setting up SSH remote "sydlnxv004"
[09:35:09.810] Using commit id "8490d3dde47c57ba65ec40dd192d014fd2113496" and quality "stable" for server
[09:35:09.815] Install and start server if needed
[09:35:09.819] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[09:35:10.037] > OpenSSH_8.4p1, OpenSSL 1.1.1i  8 Dec 2020

[09:35:10.043] Running script with connection command: "C:\Program Files\Git\usr\bin\ssh.exe" -T -D 50764 sydlnxv004 bash
[09:35:10.045] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[09:35:10.139] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\WINDOWS\System32\cmd.exe
[09:35:10.139] Got some output, clearing connection timeout
[09:35:10.152] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[09:35:10.165] > Access is denied.
> 
[09:35:10.194] > Access is denied.
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[09:35:10.203] > Access is denied.
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[09:35:14.923] "install" terminal command done
[09:35:14.923] Install terminal quit with output: Access is denied.
[09:35:14.923] Received install output: Access is denied.
[09:35:14.923] Stopped parsing output early. Remaining text: Access is denied.
[09:35:14.924] Failed to parse remote port from server output
[09:35:14.929] Resolver error: Error: 
	at Function.Create (c:\Users\atalens\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:64027)
	at Object.t.handleInstallOutput (c:\Users\atalens\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:62766)
	at k (c:\Users\atalens\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:312915)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\atalens\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:310801
	at async Object.t.withShowDetailsEvent (c:\Users\atalens\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:405790)
	at async Object.t.resolve (c:\Users\atalens\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:1:314454)
	at async c:\Users\atalens\.vscode\extensions\ms-vscode-remote.remote-ssh-0.63.0\out\extension.js:127:110333
[09:35:14.931] ------


I have ssh keys setup and works fine with git bash

**Comment by angelitoTalens** [comment]
I read through similar issues before:

https://github.com/microsoft/vscode-remote-release/issues/3011

It seems my issue is the same with missing TEMP. It is working fine now

**Comment by roblourens** [comment]
Thanks for following up. Do you know why TEMP was missing? Starting to sound like a common issue

**Comment by angelitoTalens** [comment]
Not exactly sure why. But perhaps it would be better that the vscode/remote plugin installer checks if the TEMP exist. reinstalling should fix it if the functionality depends on it
