### ISSUE TITLE
SSH: Server failed to start. - Exception calling "WriteAllLines"

### ISSUE THREAD

**Issue by ayush-j** [microsoft/vscode-remote-release#4476]
After updating to 0.64, I'm getting the following error. This used to work before the SSH issues started 2 weeks ago.

```
[05:36:28.197] Log Level: 2
[05:36:28.208] remote-ssh@0.64.0
[05:36:28.208] win32 x64
[05:36:28.210] SSH Resolver called for "ssh-remote+<sshhost>", attempt 1
[05:36:28.211] "remote.SSH.useLocalServer": false
[05:36:28.211] "remote.SSH.showLoginTerminal": false
[05:36:28.212] "remote.SSH.remotePlatform": {"xyz":"windows","abc":"windows"}
[05:36:28.212] "remote.SSH.sshPath": undefined
[05:36:28.212] "remote.SSH.sshConfigurationFile": undefined
[05:36:28.212] "remote.SSH.useFlock": true
[05:36:28.212] "remote.SSH.lockfilesInTmp": false
[05:36:28.212] "remote.SSH.localServerDownload": auto
[05:36:28.212] "remote.SSH.remoteServerListenOnSocket": false
[05:36:28.212] "remote.SSH.showLoginTerminal": false
[05:36:28.213] "remote.SSH.defaultExtensions": []
[05:36:28.213] SSH Resolver called for host: <sshhost>
[05:36:28.213] Setting up SSH remote "<sshhost>"
[05:36:28.231] Using commit id "6ac8f9adfd3698e82bf901f11bbb5940f6bc3c197" and quality "insider" for server
[05:36:28.236] Install and start server if needed
[05:36:29.325] Checking ssh with "ssh -V"
[05:36:29.391] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[05:36:29.397] Remote command length: 5944/8192 characters
[05:36:29.397] Running script with connection command: ssh -T -D 56461 "<sshhost>" powershell
[05:36:29.401] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[05:36:31.463] > Windows PowerShell
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Try the new cross-platform PowerShell https://aka.ms/pscore6]0;C:\WINDOWS\System32\cmd.exePS C:\Users\ayjindal>
> PS C:\Users\ayjindal> $uuid="a56e5bfa027"
> PS C:\Users\ayjindal> "${uuid}: running"
> a56e5bfa027: running
> PS C:\Users\ayjindal> "a56e5bfa027: pauseLog"
> a56e5bfa027: pauseLog
[05:36:31.464] Got some output, clearing connection timeout
[05:36:31.847] > a56e5bfa027: resumeLog
[05:36:31.855] > 
> PS C:\Users\ayjindal> main
[05:36:31.862] > 
[05:36:32.435] > Acquiring lock on C:\Users\ayjindal\.vscode-server-insiders\bin\6ac8f9adfd3698e82
> bf901f11bbb5940f6bc3c197\vscode-remote-lock.6ac8f9adfd3698e82bf901f11bbb5940f6bc3
> c197
> Looking for existing server in C:\Users\ayjindal\.vscode-server-insiders\bin\6ac
> 9a3ecb3698e82bf901f11bbb5940f6bc3c197
[05:36:32.443] > 
> Downloading server
> a56e5bfa027%%1%%
[05:36:32.460] > 
[05:36:39.155] > Expanding server into C:\Users\ayjindal\AppData\Local\Temp\ycselzlj.1x3
> a56e5bfa027%%2%%
[05:36:39.168] > 
[05:37:03.487] > 
> 
>     Directory: C:\Users\ayjindal\.vscode-server-insiders
> 
> 
> Mode                 LastWriteTime         Length Name
> 
> ----                 -------------         ------ ----
[05:37:03.493] > 
> 
> -a----         2/13/2021   5:37 AM              0 .6ac8f9adfd3698e82bf901f11bbb59
> 40f6bc3c197.token
[05:37:03.511] > 
[05:37:03.530] > Successfully processed 1 files; Failed processing 0 files
[05:37:03.557] > Successfully processed 1 files; Failed processing 0 files
[05:37:03.612] > Successfully processed 1 files; Failed processing 0 files
[05:37:03.623] > Successfully processed 1 files; Failed processing 0 files
[05:37:03.637] > 
[05:37:03.643] > Server failed to start. - Exception calling "WriteAllLines" with "2" argument(s)
> : "Access to the path 'C:\Users\ayjindal\.vscode-server-insiders\.6ac8f9adfd3698e
> 82bf901f11bbb5940f6bc3c197.token' is denied."
[05:37:03.652] > 
[05:37:03.916] > a56e5bfa027: start
> sshAuthSock====
> listeningOn====
> osReleaseId==windows==
> osVersion==10.0.19042==
> arch==x64==
[05:37:03.922] > 
> platform==windows==
> unpackResult==success==
> didLocalDownload==False==
> downloadTime==6696==
[05:37:03.929] > 
> installTime==24242==
> extInstallTime====
> serverStartTime====
> connectionToken==aa111111-aa1a-111a-aa11-111111aa1111==
> a56e5bfa027: end
> 17380, watching 15468
[05:37:03.930] Received install output: 
sshAuthSock====
listeningOn====
osReleaseId==windows==
osVersion==10.0.19042==
arch==x64==
platform==windows==
unpackResult==success==
didLocalDownload==False==
downloadTime==6696==
installTime==24242==
extInstallTime====
serverStartTime====
connectionToken==aa111111-aa1a-111a-aa11-111111aa1111==

[05:37:03.930] Failed to parse remote port from server output
[05:37:03.933] Resolver error: Error: 
	at Function.Create (c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:64126)
	at Object.t.handleInstallOutput (c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:62865)
	at k (c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:313462)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:311339
	at async Object.t.withShowDetailsEvent (c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:406337)
	at async Object.t.resolve (c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:315001)
	at async c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:127:110431
[05:37:03.939] ------
```

_Originally posted by @ayush-j in https://github.com/microsoft/vscode-remote-release/issues/4354#issuecomment-778522307_

**Comment by ayush-j** [comment]
@roblourens 

> Could you open a new issue for that? Also are you sure you are connecting as the same user as SSH? Are you an administrator on the machine? If so, what do you get if you click through to see ownership details?

I'm not sure if I'm connecting with the same user as SSH. My sshd and ssh-agent processes on remote are running under SYSTEM user. But yes, I'm an admin on both remote and laptop (although I don't run vscode as admin).

I'm unable to see ownership details even after requesting as admin.
![image](https://user-images.githubusercontent.com/4624541/108037225-49f61480-705f-11eb-9db6-17e7083f621a.png)

But I tried using a cmdline tool to check permissions and here are the permissions for the token file and a log file (which is okay).

![image](https://user-images.githubusercontent.com/4624541/108037792-15368d00-7060-11eb-85df-a71ba974e998.png)

**Comment by ayush-j** [comment]
I have another machine where it does work and the permissions from that system:

![image](https://user-images.githubusercontent.com/4624541/108038806-495e7d80-7061-11eb-9ce3-091567d00a1e.png)

**Comment by roblourens** [comment]
Could you try this?

- ssh to your windows remote
- `echo $env:USERNAME` The result should be your username

**Comment by ayush-j** [comment]
Yes, it is.

![image](https://user-images.githubusercontent.com/4624541/108212367-c9fda680-7153-11eb-9c97-2537ae23b2c9.png)

**Comment by roblourens** [comment]
I have no clue. If you want to keep debugging, you could try running this:

```
$contents = "test text"
$h = Resolve-Path ~
$file = "$h\\test.txt"
ni -it f $file -Force
icacls $file /reset /Q
icacls $file /setowner "$env:USERNAME" /Q
icacls $file /grant "$($env:USERNAME):(R,W)" /Q
icacls $file /inheritance:r /Q
[System.IO.File]::WriteAllLines($file, $global:contents)
```

**Comment by ayush-j** [comment]
I ran those on my primary remote machine (with added to print permissions at each step):

```
> $contents = "test text"
> $file = "$h\\test.txt"

> icacls $file /reset /Q
> icacls $file
C:\Users\ayjindal\\test.txt NT AUTHORITY\SYSTEM:(I)(F)
                            BUILTIN\Administrators:(I)(F)
                            FAREAST\ayjindal:(I)(F)

Successfully processed 1 files; Failed processing 0 files

> icacls $file /setowner "$env:USERNAME" /Q
Successfully processed 1 files; Failed processing 0 files
> icacls $file
C:\Users\ayjindal\\test.txt NT AUTHORITY\SYSTEM:(I)(F)
                            BUILTIN\Administrators:(I)(F)
                            FAREAST\ayjindal:(I)(F)

Successfully processed 1 files; Failed processing 0 files

> icacls $file /grant "$($env:USERNAME):(R,W)" /Q
Successfully processed 1 files; Failed processing 0 files
> icacls $file
C:\Users\ayjindal\\test.txt AYJINDAL\:(R,W)
                            NT AUTHORITY\SYSTEM:(I)(F)
                            BUILTIN\Administrators:(I)(F)
                            FAREAST\ayjindal:(I)(F)

Successfully processed 1 files; Failed processing 0 files

> icacls $file /inheritance:r /Q
Successfully processed 1 files; Failed processing 0 files
> icacls $file
C:\Users\ayjindal\\test.txt: Access is denied.
Successfully processed 0 files; Failed processing 1 files

> [System.IO.File]::WriteAllLines($file, $global:contents)
Exception calling "WriteAllLines" with "2" argument(s): "Access to the path 'C:\Users\ayjindal\test.txt' is denied."
At line:1 char:1
+ [System.IO.File]::WriteAllLines($file, $global:contents)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : UnauthorizedAccessException

>
```

And then on my secondary machine where it works:
```
> $contents = "test text"
> $file = "$h\\test.txt"

> icacls $file /reset /Q
Successfully processed 1 files; Failed processing 0 files
C:\Users\ayjindal\\test.txt NT AUTHORITY\SYSTEM:(I)(F)
                            BUILTIN\Administrators:(I)(F)
                            FAREAST\ayjindal:(I)(F)

Successfully processed 1 files; Failed processing 0 files

> icacls $file /setowner "$env:USERNAME" /Q
Successfully processed 1 files; Failed processing 0 files
> icacls $file
C:\Users\ayjindal\\test.txt NT AUTHORITY\SYSTEM:(I)(F)
                            BUILTIN\Administrators:(I)(F)
                            FAREAST\ayjindal:(I)(F)

Successfully processed 1 files; Failed processing 0 files

> icacls $file /grant "$($env:USERNAME):(R,W)" /Q
Successfully processed 1 files; Failed processing 0 files
> icacls $file
C:\Users\ayjindal\\test.txt FAREAST\ayjindal:(R,W)
                            NT AUTHORITY\SYSTEM:(I)(F)
                            BUILTIN\Administrators:(I)(F)
                            FAREAST\ayjindal:(I)(F)

Successfully processed 1 files; Failed processing 0 files

> icacls $file /inheritance:r /Q
Successfully processed 1 files; Failed processing 0 files
> icacls $file
C:\Users\ayjindal\\test.txt FAREAST\ayjindal:(R,W)

Successfully processed 1 files; Failed processing 0 files

> [System.IO.File]::WriteAllLines($file, $global:contents)
>
```


I can see that on the main machine (where it's failing), running `icacls $file /grant "$($env:USERNAME):(R,W)" /Q` grants the RW permissions to a user `AYJINDAL\` **NOT** `FAREAST\ayjindal` and then it all goes downhill from there.

Both machines have "ayjindal" as `$env:USERNAME` but it doesn't seem to be considering my domain name on the failing machine -- do you know why that would be?

**Comment by roblourens** [comment]
Is it possible that the machine name in the broken case is `AYJINDAL`? If not that, then maybe for some reason it thinks there is a domain with that name.

If you replace `$($env:USERNAME)` with `FAREAST\ayjindal`, does it work?

**Comment by ayush-j** [comment]
The machine is indeed named `AYJINDAL`. If I replace `$($env:USERNAME)` with `FAREAST\ayjindal` then yes, it does work.

I did try using `FAREAST\ayjindal` in my ssh config but that does not change anything. And I haven't changed my config or machine name since it stopped working.

What else could I do to fix this?

**Comment by roblourens** [comment]
Nothing - I think that I will have to change my code to always use a fully-qualified user name. Thanks for the help testing! I wouldn't have figured it out on my own.

**Comment by roblourens** [comment]
Will be fixed in the next build of the **Nightly** Remote-SSH extension tomorrow, please try it then.

**Comment by ayush-j** [comment]
I just installed the nightly Remote SSH extension and I'm getting this:

```

**Comment by roblourens** [comment]
Apologies. The fix will be in the next nightly build

**Comment by ayush-j** [comment]
IT FINALLY WORKS 🎉

Thanks for the help and fix!
