### ISSUE TITLE
Spammy error about running docker locally

### ISSUE THREAD

**Issue by ThiefMaster** [microsoft/vscode-remote-release#4497]
Issue Type: <b>Bug</b>

I'm getting very noisy output in the "Remote - SSH" output panel which looks like the extension is trying to run docker locally, even though I neither use docker (I'm connected to an ssh remote) nor can I see any reason why remote-ssh would run something locally in the first place...

```
[10:24:13.873] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:13.873] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:15.880] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:15.885] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:15.885] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:17.889] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:17.896] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:17.896] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:19.899] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:19.905] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:19.905] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:21.902] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:21.907] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:21.908] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:23.904] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:23.909] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:23.910] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:25.918] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:25.923] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:25.924] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:27.925] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:27.931] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:27.931] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:29.931] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:29.938] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:29.938] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:31.930] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:31.936] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:31.936] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:33.935] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:33.941] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:33.941] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:35.941] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:35.948] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:35.948] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:37.956] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:37.963] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:37.963] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:39.966] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:39.973] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:39.973] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:41.967] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:41.973] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:41.973] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:43.976] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:43.983] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:43.983] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:45.990] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:45.996] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:45.996] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:47.998] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:48.005] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:48.005] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:50.007] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:50.012] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:50.012] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:52.009] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:52.014] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:52.014] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:54.012] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:54.018] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:54.018] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:56.024] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:56.030] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:56.030] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[10:24:58.033] Unhandled rejection: Error: spawn C:\Program Files\Microsoft VS Code Insiders\docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Extension version: 0.64.0
VS Code version: Code - Insiders 1.54.0-insider (192c817fd350bcbf3caecae22a45ec39bae78516, 2021-02-19T05:14:28.632Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-gentoo
Remote OS version: Linux x64 5.4.72-gentoo
Remote OS version: Linux x64 5.4.97-gentoo

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (16.35GB free)|
|Process Argv|--crash-reporter-id c6195c38-5aa8-4897-b60d-c88b99231d15|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: eluvian|
|OS|Linux x64 5.4.72-gentoo|
|CPUs|AMD Ryzen 5 3600X 6-Core Processor (12 x 4110)|
|Memory (System)|31.35GB (6.25GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: eluvian|
|OS|Linux x64 5.4.72-gentoo|
|CPUs|AMD Ryzen 5 3600X 6-Core Processor (12 x 4110)|
|Memory (System)|31.35GB (6.25GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: claptrap|
|OS|Linux x64 5.4.97-gentoo|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 3100)|
|Memory (System)|15.51GB (0.44GB free)|
|VM|0%|
</details>

**Comment by Tyriar** [comment]
@chrmarti I'm seeing this in devtools when Remote - Containers is installed which is making it hard to view logs while developing extensions:

![image](https://user-images.githubusercontent.com/2193314/108606096-ecb6d780-736c-11eb-81fb-ddee993ce22d.png)

**Comment by kevinykuo** [comment]
Hitting this also
```
[00:20:01.211] Unhandled rejection: Error: spawn docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[00:20:03.206] Unhandled rejection: Error: spawn docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[00:20:03.207] Unhandled rejection: Error: spawn docker ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
