### ISSUE TITLE
Resolver error: Error: The VS Code Server failed to start

### ISSUE THREAD

**Issue by brylucyk** [microsoft/vscode-remote-release#4500]
- VSCode Version: 1.53.2
- Local OS Version: Windows 10 Home 1909
- Remote OS Version: Linux
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Attempt to connect to remote server (was working yesterday)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

> Server did not start successfully. Full server log at /home/lucykbr/.vscode-serv
> er/.622cb03f7e070a9670c94bae1a45d78d7181fbd4.log >>>
> /home/lucykbr/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/server
> .sh: line 12: /home/lucykbr/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7
> 181fbd4/node: No such file or directory
> <<< End of server log
> 22a625208f5c: start
> exitCode==32==
> listeningOn====
> osReleaseId==nixos==
> arch==x86_64==
> tmpDir==/run/user/145270==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==7757==
> 22a625208f5c: end
> 
> [09:09:25.981] Received install output: 
> exitCode==32==
> listeningOn====
> osReleaseId==nixos==
> arch==x86_64==
> tmpDir==/run/user/145270==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==7757==
> 
> [09:09:25.990] Resolver error: Error: The VS Code Server failed to start
> 	at Function.ServerInstallError (c:\Users\blucy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:64057)
> 	at c (c:\Users\blucy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:58602)
> 	at Object.t.handleInstallOutput (c:\Users\blucy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:62898)
> 	at k (c:\Users\blucy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:313462)
> 	at processTicksAndRejections (internal/process/task_queues.js:97:5)
> 	at async c:\Users\blucy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:311339
> 	at async Object.t.withShowDetailsEvent (c:\Users\blucy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:406337)
> 	at async Object.t.resolve (c:\Users\blucy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:315001)
> 	at async c:\Users\blucy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:127:110431
> [09:09:25.998] ------
>

**Comment by brylucyk** [comment]
Ok, this was fixed by the sysadmin (Linux configuration issue). :)
