### ISSUE TITLE
Can't connect to remote if default shell is not /bin/bash 

### ISSUE THREAD

**Issue by derived-coder** [microsoft/vscode-remote-release#4518]
- VSCode Version:1.53.2
- Local OS Version: Ubuntu 18.04
- Remote OS Version: unknown
- Remote Extension/Connection Type: SSH
Steps to Reproduce:
Connect to a shell with only (bin/sh) available
Remark: there is no `bin/bash` executable available

1.
2.
```
[17:53:59.611] Log Level: 2
[17:53:59.614] remote-ssh@0.64.0
[17:53:59.614] linux x64
[17:53:59.615] SSH Resolver called for "ssh-remote+my-remote", attempt 1
[17:53:59.615] "remote.SSH.useLocalServer": true
[17:53:59.616] "remote.SSH.sshPath": undefined
[17:53:59.616] "remote.SSH.sshConfigurationFile": undefined
[17:53:59.616] "remote.SSH.useFlock": true
[17:53:59.616] "remote.SSH.lockfilesInTmp": false
[17:53:59.616] "remote.SSH.localServerDownload": auto
[17:53:59.616] "remote.SSH.remoteServerListenOnSocket": false
[17:53:59.616] "remote.SSH.showLoginTerminal": false
[17:53:59.617] "remote.SSH.defaultExtensions": []
[17:53:59.617] SSH Resolver called for host: my-remote
[17:53:59.617] Setting up SSH remote "my-remote"
[17:53:59.620] Acquiring local install lock: /tmp/vscode-remote-ssh-my-remote-install.lock
[17:53:59.628] Looking for existing server data file at /lhome/user/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-my-remote-622cb03f7e070a9670c94bae1a45d78d7181fbd4-0.64.0/data.json
[17:53:59.629] Using commit id "622cb03f7e070a9670c94bae1a45d78d7181fbd4" and quality "stable" for server
[17:53:59.634] Install and start server if needed
[17:53:59.637] Checking ssh with "ssh -V"
[17:53:59.644] > OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017

[17:53:59.649] askpass server listening on /run/user/76080/vscode-ssh-askpass-acc73cdc83279626bced6cbae6a6f61699816a71.sock
[17:53:59.649] Spawning local server with {"ipcHandlePath":"/run/user/76080/vscode-ssh-askpass-7890bbeec56170e40cab7a6744063f851e15f1ae.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","35065","-o","ConnectTimeout=15","my-remote"],"dataFilePath":"/lhome/user/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-my-remote-622cb03f7e070a9670c94bae1a45d78d7181fbd4-0.64.0/data.json"}
[17:53:59.649] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/lhome/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/lhome/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/76080/vscode-ssh-askpass-acc73cdc83279626bced6cbae6a6f61699816a71.sock"}
[17:53:59.653] Spawned 9354
[17:53:59.739] > local-server> Spawned ssh: 9364
[17:53:59.740] stderr> OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
[17:54:00.518] stderr> Server not found in Kerberos database
[17:54:00.519] stderr> 
[17:54:00.656] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:pKCq9Oq29laxV+zQ6BrfzXetBf1zvRSXo0bjlLEbRUk
[17:54:00.831] stderr> Authenticated to 127.0.0.1 ([127.0.0.1]:8206).
[17:54:01.126] > ready: f7b4d1687e2c
[17:54:01.234] > Linux 4.14.206-perf #1 SMP PREEMPT Fri Feb 19 11:52:44 UTC 2021
[17:54:01.235] Platform: linux
[17:54:01.329] stderr> -sh: bash: not found
[17:54:01.329] stderr> -sh: syntax error: unexpected "(" (expecting "then")
[17:54:01.330] stderr> Transferred: sent 17008, received 2568 bytes, in 0.5 seconds
[17:54:01.330] stderr> Bytes per second: sent 34111.0, received 5150.3
[17:54:01.330] > local-server> ssh child died, shutting down
[17:54:01.333] Local server exit: 0
[17:54:01.333] Received install output: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
Server not found in Kerberos database

debug1: Server host key: ecdsa-sha2-nistp256 SHA256:pKCq9Oq29laxV+zQ6BrfzXetBf1zvRSXo0bjlLEbRUk
Authenticated to 127.0.0.1 ([127.0.0.1]:8206).
ready: f7b4d1687e2c
Linux 4.14.206-perf #1 SMP PREEMPT Fri Feb 19 11:52:44 UTC 2021
-sh: bash: not found
-sh: syntax error: unexpected "(" (expecting "then")
Transferred: sent 17008, received 2568 bytes, in 0.5 seconds
Bytes per second: sent 34111.0, received 5150.3

[17:54:01.341] Resolver error: Error: bash not found
	at Function.Create (/lhome/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:64126)
	at /lhome/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:62441
	at Object.t.handleInstallOutput (/lhome/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:62642)
	at Object.t.tryInstallWithLocalServer (/lhome/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:405581)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async /lhome/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:310867
	at async Object.t.withShowDetailsEvent (/lhome/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:406337)
	at async /lhome/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:404105
	at async S (/lhome/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:400873)
	at async Object.t.resolveWithLocalServer (/lhome/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:403732)
	at async Object.t.resolve (/lhome/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:314879)
	at async /lhome/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:127:110431
[17:54:01.345] ------
```

**Comment by bamurtaugh** [comment]
This seems tied to https://github.com/microsoft/vscode-remote-release/issues/2509; does setting `"remote.SSH.useLocalServer": false` help?
