### ISSUE TITLE
SSH Disconnects and doesn't let me log in again

### ISSUE THREAD

**Issue by Shashank-Ojha** [microsoft/vscode-remote-release#4529]
Steps to Reproduce:

SSH into some remote machine.
Put your computer to sleep so it disconnects from SSH
Return to VsCode
Previously I used to get a dialog box on the top that asked me to re-enter my password and that was it. All my files remained open and I could continue my work. Now the dialog box doesn't show anymore and it won't let me reconnect. I just have to close VsCode and restart everything.

**Comment by bamurtaugh** [comment]
Hey @Shashank-Ojha, thanks for reporting. Do you think https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_53.md#less-disruptive-disconnects could be affecting your experience?

**Comment by Shashank-Ojha** [comment]
Hey @bamurtaugh, thanks for the quick response. 

To answer your question, I don't think so. In that green panel, I actually end up seeing something like "Disconnected from remote ssh" and when I click on it, a menu shows up giving me the standard options (Connect Current Window to Host, Connect to Host, etc). I try clicking "Connect to Host" hoping that it will ask me to enter my password and reconnect, but nothing ever pops up, so I end up restarting VsCode.

I never observe the "Reconnect to vscode-remote" message like in the link you attached.

**Comment by nick-baliesnyi** [comment]
Same issue here – can't restore the disrupted connection without completely closing it.

For me though, the `Close Remote Connection` option in the menu works, so I don't have to completely restart VS Code, but I still have to reconnect and reopen all tabs manually.

**Comment by bamurtaugh** [comment]
Thanks for the additional info!

Would you be able to provide the logs from the Output > "Remote - SSH" panel when this happens?

**Comment by nick-baliesnyi** [comment]
Sure @bamurtaugh, here you go:

<details>
<summary>Logs when disconnected</summary>
```
[08:34:30.410] Stopped parsing output early. Remaining text: OpenSSH_8.1p1, LibreSSL 2.7.3ssh: connect to host localhost port 8888: Connection refused
[08:34:30.411] Failed to parse remote port from server output
[08:34:30.415] Resolver error: Error: 
	at Function.Create (/Users/macbook/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:64126)
	at Object.t.handleInstallOutput (/Users/macbook/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:62865)
	at Object.t.tryInstallWithLocalServer (/Users/macbook/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:405581)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async /Users/macbook/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:310867
	at async Object.t.withShowDetailsEvent (/Users/macbook/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:406337)
	at async /Users/macbook/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:404105
	at async S (/Users/macbook/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:400873)
	at async Object.t.resolveWithLocalServer (/Users/macbook/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:403732)
	at async Object.t.resolve (/Users/macbook/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:314879)
	at async /Users/macbook/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:127:110431
[08:34:30.419] ------
```
</details>

Some more details that I hope will help you.

1. What is shown in the logs when I press the buttons?

Nothing. The only thing that happens is I get "Activating Extensions..." loading spinner in the bottom, and when it's gone, nothing happens either.

2. What connection am I using? 

My connection is carried over through a local SSH proxy that I first create via:

```bash
ssh -N -L localhost:<port>:localhost:<port> <end-host>
```

I then connect to the end-host through this localhost proxy using the following config:

```raw
Host <friendly-end-host-name>
    HostName localhost
    User root
    Port <port>
```

To get disconnected, I stopped the local proxy, and then my SSH connection dropped immediately and I copied the logs above.

3. Does the issue happen only on this type of connection?

It occurs even for ordinary direct SSH connections, but in those cases, the extension _does try to reconnect automatically_ and I can get back to the host without restarting. To get disconnected there, I simply turn off my Internet access.

Hope this helps. Will be happy to provide more info/logs.

**Comment by Shashank-Ojha** [comment]
This is the most recent error I see in the logs. I removed server host key credentials for safety reasons. 
```
[18:07:13.896] Stopped parsing output early. Remaining text: OpenSSH_8.1p1, LibreSSL 2.7.3debug1: Server host key:[Info deleted]
[18:07:13.897] Failed to parse remote port from server output
[18:07:14.061] Resolver error: Error: 
	at Function.Create (/Users/sojha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:64126)
	at Object.t.handleInstallOutput (/Users/sojha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:62865)
	at Object.t.tryInstallWithLocalServer (/Users/sojha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:405581)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async /Users/sojha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:310867
	at async Object.t.withShowDetailsEvent (/Users/sojha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:406337)
	at async /Users/sojha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:404105
	at async S (/Users/sojha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:400873)
	at async Object.t.resolveWithLocalServer (/Users/sojha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:403732)
	at async Object.t.resolve (/Users/sojha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:314879)
	at async /Users/sojha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:127:110431
```

I also see these errors a little further up in output screen
```
[18:07:13.880] Handling auth request failed: Error: Canceled
	at /Users/sojha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:85753
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
	at T.cancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:5880)
	at P.cancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:6421)
	at /Users/sojha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:405069
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
	at T.cancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:5880)
	at P.cancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:6421)
	at ServerResponse.<anonymous> (/Users/sojha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:306025)
	at ServerResponse.emit (events.js:315:20)
	at Socket.socketOnTimeout (_http_server.js:511:33)
	at Socket.emit (events.js:315:20)
	at Socket._onTimeout (net.js:482:8)
	at listOnTimeout (internal/timers.js:549:17)
	at processTimers (internal/timers.js:492:7)
[18:07:13.887] Unhandled rejection: Error: Handling auth request failed: Error: Canceled
	at /Users/sojha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:85753
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
	at T.cancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:5880)
	at P.cancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:6421)
	at /Users/sojha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:405069
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
	at T.cancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:5880)
	at P.cancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:6421)
	at ServerResponse.<anonymous> (/Users/sojha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:306025)
	at ServerResponse.emit (events.js:315:20)
	at Socket.socketOnTimeout (_http_server.js:511:33)
	at Socket.emit (events.js:315:20)
	at Socket._onTimeout (net.js:482:8)
	at listOnTimeout (internal/timers.js:549:17)
	at processTimers (internal/timers.js:492:7)
	at IncomingMessage.<anonymous> (/Users/sojha/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:306300)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Hope that helps.
