### ISSUE TITLE
Failed to parse remote port from server output

### ISSUE THREAD

**Issue by jq-87** [microsoft/vscode-remote-release#4552]
```
Version: 1.54.0-insider (Universal)
Commit: c47da720f351455681978a48edc4d9a0d095ea0e
Date: 2021-02-24T12:22:35.736Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```
AND
```
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```
- Local OS Version: OSX 10.15.7
- Remote OS Version: Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1035-aws x86_64)
- Remote Extension/Connection Type: SSH

# Steps to Reproduce:

1. Run Remote-SSH: Connect to Host...

Does this issue occur when you try this locally?: Yes

Does this issue occur when you try this locally and all extensions are disabled?: Yes
```
Remote - SSH extension version: 
v0.64.0

Tried with these Node versions:
v14.16.0
v12.21.0
v10.24.0
```

# Error in Output panel
```

Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1035-aws x86_64)

...

*** System restart required ***
ready: c63c32e9af08
Linux 5.4.0-1035-aws #37~18.04.1-Ubuntu SMP Wed Jan 6 22:31:04 UTC 2021
bash: line 1: syntax error near unexpected token `;'
bash: line 1: `; then'
-sh: 4: function: not found
c63c32e9af08: running
-sh: 69: [[: not found
-sh: 90: [[: not found
-sh: 149: Syntax error: "(" unexpected (expecting "then")
Transferred: sent 17836, received 4328 bytes, in 0.5 seconds
Bytes per second: sent 35580.6, received 8633.8

[11:51:52.247] Stopped parsing output early.
[11:51:52.247] Failed to parse remote port from server output
[11:51:52.253] Resolver error: Error: 
	at Function.Create (/Users/quiroz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:64126)
	at Object.t.handleInstallOutput (/Users/quiroz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:62865)
	at Object.t.tryInstallWithLocalServer (/Users/quiroz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:405581)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async /Users/quiroz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:310867
	at async Object.t.withShowDetailsEvent (/Users/quiroz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:406337)
	at async /Users/quiroz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:404105
	at async S (/Users/quiroz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:400873)
	at async Object.t.resolveWithLocalServer (/Users/quiroz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:403732)
	at async Object.t.resolve (/Users/quiroz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:314879)
	at async /Users/quiroz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:127:110431
[11:51:52.258] ------
```

**Comment by jq-87** [comment]
I want to confirm that I can successfully ssh via my command line

**Comment by jq-87** [comment]
I am no longer having this issue on Version: 1.54.2
