### ISSUE TITLE
Cannot connect to VM via Azure Bastion Host

### ISSUE THREAD

**Issue by MotoRZR** [microsoft/vscode-remote-release#4553]
Maybe this is how it's intended to be but I cannot connect to a machine via an Azure Bastion Host service.  I know the Azure Bastion service normally allows you to directly remote into the Linux VM by of choice via the bastion host if you're going through the Azure Portal as the bastion host only seems to accept SSL/HTML connections.  A browser based connection is not as convenient as if you could connect via VS Code remote.  I attempted an SSH using the following SSH config but it fails:

```
Host bastion-host
  HostName xx.xxx.xxx.x

Host target-machine
  HostName x.x.x.x
  Port 22
  User me
  IdentityFile C:/Users/me/.ssh/id_rsa
  ProxyJump bastion-host
```

With this error message:

```
[17:08:27.968] Log Level: 2
[17:08:27.972] remote-ssh@0.64.0
[17:08:27.972] win32 x64
[17:08:27.973] SSH Resolver called for "ssh-remote+target-machine", attempt 1
[17:08:27.973] "remote.SSH.useLocalServer": false
[17:08:27.973] "remote.SSH.showLoginTerminal": false
[17:08:27.974] "remote.SSH.remotePlatform": {"target-box":"linux","jump-box":"linux"}
[17:08:27.974] "remote.SSH.sshPath": undefined
[17:08:27.974] "remote.SSH.sshConfigurationFile": undefined
[17:08:27.974] "remote.SSH.useFlock": true
[17:08:27.974] "remote.SSH.lockfilesInTmp": false
[17:08:27.974] "remote.SSH.localServerDownload": auto
[17:08:27.974] "remote.SSH.remoteServerListenOnSocket": true
[17:08:27.974] "remote.SSH.showLoginTerminal": false
[17:08:27.974] "remote.SSH.defaultExtensions": []
[17:08:27.975] SSH Resolver called for host: target-machine
[17:08:27.975] Setting up SSH remote "target-machine"
[17:08:27.987] Using commit id "22cb03f7e070a9670c94bae1a45d78d781fbd4" and quality "stable" for server
[17:08:27.990] Install and start server if needed
[17:08:29.378] Checking ssh with "ssh -V"
[17:08:29.405] > OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2

[17:08:29.408] Running script with connection command: ssh -T -D 60410 "target-machine" bash
[17:08:29.414] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[17:08:29.485] > ]0;C:\WINDOWS\System32\cmd.exe
[17:08:29.485] Got some output, clearing connection timeout
[17:08:50.542] > ssh: connect to host bastion-host port 22: Connection timed out
[17:08:50.558] > kex_exchange_identification: Connection closed by remote host
> The process tried to write to a nonexistent pipe.
> 
[17:08:50.847] "install" terminal command done
[17:08:50.847] Install terminal quit with output: The process tried to write to a nonexistent pipe.
[17:08:50.847] Received install output: The process tried to write to a nonexistent pipe.
[17:08:50.850] Resolver error: Error: The process tried to write to a nonexistent pipe
	at Function.Offline (c:\Users\mr\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:64180)
	at c:\Users\me\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:61766
	at Object.t.handleInstallOutput (c:\Users\me\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:62144)
	at k (c:\Users\me\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:313462)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\me\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:311339
	at async Object.t.withShowDetailsEvent (c:\Users\me\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:406337)
	at async Object.t.resolve (c:\Users\me\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:315001)
	at async c:\Users\me\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:127:110431
[17:08:50.853] ------

```

Is there any SSH configuration that would allow access to a VM via the Azure Bastion Service with VS Code Remote?

**Comment by roblourens** [comment]
Ah I see that it does say that. Not clear whether normal SSH is still supported. Sorry I can't be more helpful
