### ISSUE TITLE
Windows Host Multi user environment failure

### ISSUE THREAD

**Issue by LukeMauldin** [microsoft/vscode-remote-release#4556]
- VSCode Version: 1.53.2
- Local OS Version: Windows 10 2004
- Remote OS Version: Windows Server 2019
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
1.  Setup Windows server 2019 remote environment to support SSH logins
2.  Have user A connect to Windows server 2019 remote environment via VSCode remote - this succeeds
3.  Have user B connect to Windows server 2019 remote environment via VSCode remote - this fails

The steps above work as expected with both user A and user B being able to connect when the remote OS version is a Linux system.

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?:N/A

Failure log file:
```
[13:47:20.384] Log Level: 2
[13:47:20.395] remote-ssh@0.64.0
[13:47:20.395] win32 x64
[13:47:20.396] SSH Resolver called for "ssh-remote+dev3", attempt 1
[13:47:20.396] "remote.SSH.useLocalServer": false
[13:47:20.397] "remote.SSH.showLoginTerminal": false
[13:47:20.397] "remote.SSH.remotePlatform": {"dev3":"windows"}
[13:47:20.397] "remote.SSH.sshPath": undefined
[13:47:20.397] "remote.SSH.sshConfigurationFile": undefined
[13:47:20.397] "remote.SSH.useFlock": true
[13:47:20.397] "remote.SSH.lockfilesInTmp": false
[13:47:20.398] "remote.SSH.localServerDownload": auto
[13:47:20.398] "remote.SSH.remoteServerListenOnSocket": false
[13:47:20.398] "remote.SSH.showLoginTerminal": false
[13:47:20.398] "remote.SSH.defaultExtensions": []
[13:47:20.398] SSH Resolver called for host: dev3
[13:47:20.398] Setting up SSH remote "dev3"
[13:47:20.421] Using commit id "622cb03f7e070a9670c94bae1a45d78d7181fbd4" and quality "stable" for server
[13:47:20.425] Install and start server if needed
[13:47:20.433] Checking ssh with "ssh -V"
[13:47:20.514] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[13:47:20.520] Remote command length: 5934/8192 characters
[13:47:20.520] Running script with connection command: ssh -T -D 55407 dev3 powershell
[13:47:20.524] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[13:47:23.501] > Windows PowerShell
> Copyright (C) Microsoft Corporation. All rights reserved.]0;C:\WINDOWS\System32\cmd.exePS C:\Users\USERA>
> PS C:\Users\USERA> $uuid="d151ccc13824"
> PS C:\Users\USERA> "${uuid}: running"
> d151ccc13824: running
> PS C:\Users\USERA> "d151ccc13824: pauseLog"
> d151ccc13824: pauseLog
[13:47:23.501] Got some output, clearing connection timeout
[13:47:24.159] > 
[13:47:27.986] > Server did not start successfully. Full server log at C:\Users\USERA\.vsco
> de-server\.622cb03f7e070a9670c94bae1a45d78d7181fbd4.log >>>
[13:47:28.002] > 
[13:47:28.103] > cat : Cannot find path 'C:\Users\USERA\.vscode-server\.622cb03f7e070a9670c
> 94bae1a45d78d7181fbd4.log' because it
> does not exist.
> At line:71 char:1
> + cat $log
> + ~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (C:\Users\mauldi...78d7181fbd4.log
> :String) [Get-Content], ItemNotFoundEx
> <<< End of server log
> d151ccc13824: start
> exitCode==32==
>    ception
>     + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetCont
> entCommand
> 
> listeningOn====
> osReleaseId==windows==
> osVersion====
> arch==x64==
> platform==windows==
> unpackResult====
> didLocalDownload==False==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> d151ccc13824: end
[13:47:28.103] Received install output: 
exitCode==32==
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetCont
entCommand

listeningOn====
osReleaseId==windows==
osVersion====
arch==x64==
platform==windows==
unpackResult====
didLocalDownload==False==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[13:47:28.108] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (c:\Users\USERA\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:64057)
	at c (c:\Users\USERA\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:58602)
	at Object.t.handleInstallOutput (c:\Users\USERA\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:62898)
	at k (c:\Users\USERA\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:313462)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\USERA\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:311339
	at async Object.t.withShowDetailsEvent (c:\Users\USERA\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:406337)
	at async Object.t.resolve (c:\Users\USERA\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:315001)
	at async c:\Users\USERA\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:127:110431
[13:47:28.112] ------




[13:47:28.237] > 
> d151ccc13824: start
[13:47:28.283] > 
> sshAuthSock====
[13:47:28.295] > 
> listeningOn====
[13:47:28.357] > osReleaseId==windows==
> osVersion==10.0.17763==
[13:47:28.357] > 
> arch==x64==
> platform==windows==
[13:47:28.363] > 
> unpackResult====
> didLocalDownload==False==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> connectionToken====
> d151ccc13824: end
[13:47:28.371] > 
> 6116, watching 9328
```

Success log file:
```
[13:54:16.504] Log Level: 2
[13:54:16.513] remote-ssh@0.64.0
[13:54:16.513] win32 x64
[13:54:16.514] SSH Resolver called for "ssh-remote+dev3", attempt 1
[13:54:16.514] "remote.SSH.useLocalServer": false
[13:54:16.514] "remote.SSH.showLoginTerminal": false
[13:54:16.515] "remote.SSH.remotePlatform": {"dev3":"windows"}
[13:54:16.515] "remote.SSH.sshPath": undefined
[13:54:16.515] "remote.SSH.sshConfigurationFile": undefined
[13:54:16.515] "remote.SSH.useFlock": true
[13:54:16.515] "remote.SSH.lockfilesInTmp": false
[13:54:16.515] "remote.SSH.localServerDownload": auto
[13:54:16.515] "remote.SSH.remoteServerListenOnSocket": false
[13:54:16.515] "remote.SSH.showLoginTerminal": false
[13:54:16.515] "remote.SSH.defaultExtensions": []
[13:54:16.516] SSH Resolver called for host: dev3
[13:54:16.516] Setting up SSH remote "dev3"
[13:54:16.534] Using commit id "622cb03f7e070a9670c94bae1a45d78d7181fbd4" and quality "stable" for server
[13:54:16.538] Install and start server if needed
[13:54:16.541] Checking ssh with "ssh -V"
[13:54:16.621] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[13:54:16.627] Remote command length: 5934/8192 characters
[13:54:16.627] Running script with connection command: ssh -T -D 61298 dev3 powershell
[13:54:16.632] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[13:54:19.714] > Windows PowerShell
> Copyright (C) Microsoft Corporation. All rights reserved.]0;C:\WINDOWS\System32\cmd.exe
[13:54:19.715] Got some output, clearing connection timeout
[13:54:19.719] > PS C:\Users\USERA.sa>
> PS C:\Users\USERA.sa> $uuid="1484fdb17b81"
> PS C:\Users\USERA.sa> "${uuid}: running"
> 1484fdb17b81: running
> PS C:\Users\USERA.sa> "1484fdb17b81: pauseLog"
> 1484fdb17b81: pauseLog
[13:54:20.005] > 
[13:54:20.159] > Acquiring lock on C:\Users\USERA.sa\.vscode-server\bin\622cb03f7e070a9670c94b
> ae1a45d78d7181fbd4\vscode-remote-lock.622cb03f7e070a9670c94bae1a45d78d7181fbd4  
> Looking for existing server in C:\Users\USERA.sa\.vscode-server\bin\622cb03f7
> e070a9670c94bae1a45d78d7181fbd4
[13:54:20.169] > 
> Found installed server
[13:54:20.178] > 
[13:54:20.204] > 
> 
>     Directory: C:\Users\USERA.sa\.vscode-server
> 
> 
> Mode                LastWriteTime         Length Name
> 
> ----                -------------         ------ ----
> 
> -a----        2/24/2021   1:54 PM              0 .622cb03f7e070a9670c94bae1a45d7
> 8d7181fbd4.token
[13:54:20.223] > 
[13:54:20.238] > Successfully processed 1 files; Failed processing 0 files
[13:54:20.249] > Successfully processed 1 files; Failed processing 0 files
[13:54:20.254] > 
[13:54:20.263] > Successfully processed 1 files; Failed processing 0 files
[13:54:20.270] > 
> Successfully processed 1 files; Failed processing 0 files
> Starting server: & 'C:\Users\USERA.sa\.vscode-server\bin\622cb03f7e070a9670c9
> 4bae1a45d78d7181fbd4\server.cmd' --start-server --host=127.0.0.1 --enable-remote
[13:54:20.276] > 
> -auto-shutdown --port=0 --connection-secret C:\Users\USERA.sa\.vscode-server\
> .622cb03f7e070a9670c94bae1a45d78d7181fbd4.token   *> 'C:\Users\USERA.sa\.vsco
> de-server\.622cb03f7e070a9670c94bae1a45d78d7181fbd4.log'
[13:54:20.286] > 
[13:54:21.756] > 1484fdb17b81: start
> sshAuthSock====
> listeningOn==50992==
> osReleaseId==windows==
> osVersion==10.0.17763==
> arch==x64==
> platform==windows==
[13:54:21.765] > 
> unpackResult====
> didLocalDownload==False==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==124==
> connectionToken==a1a1a1a1-a1a1-1aa1-a1a1-aa111a111a11==
> 1484fdb17b81: end
> 14112, watching 4952
[13:54:21.766] Received install output: 
sshAuthSock====
listeningOn==50992==
osReleaseId==windows==
osVersion==10.0.17763==
arch==x64==
platform==windows==
unpackResult====
didLocalDownload==False==
downloadTime====
installTime====
extInstallTime====
serverStartTime==124==
connectionToken==a1a1a1a1-a1a1-1aa1-a1a1-aa111a111a11==

[13:54:21.767] Remote server is listening on 50992
[13:54:21.767] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":50992},"osReleaseId":"windows","arch":"x64","sshAuthSock":"","platform":"windows","connectionToken":"a1a1a1a1-a1a1-1aa1-a1a1-aa111a111a11"},"serverStartTime":124,"installUnpackCode":""}
[13:54:21.770] Starting forwarding server. localPort 61307 -> socksPort 61298 -> remotePort 50992
[13:54:21.772] Forwarding server listening on 61307
[13:54:21.772] Waiting for ssh tunnel to be ready
[13:54:21.774] [Forwarding server 61307] Got connection 0
[13:54:21.776] Tunneled 50992 to local port 61307
[13:54:21.777] Resolved "ssh-remote+dev3" to "127.0.0.1:61307"
[13:54:21.778] > 
[13:54:21.789] ------




[13:54:21.797] [Forwarding server 61307] Got connection 1
[13:54:22.060] [Forwarding server 61307] Got connection 2
[13:54:23.886] [Forwarding server 61307] Got connection 3
[13:54:23.887] [Forwarding server 61307] Got connection 4
[13:54:23.888] [Forwarding server 61307] Got connection 5

```

**Comment by bamurtaugh** [comment]
Hey @LukeMauldin, just to clarify - did user A connect in one window/instance of VS Code, then user B opens a new instance of VS Code on the same machine while user A is still connected? Or how does this connection flow look (i.e. are they connecting from separate local machines)?

**Comment by LukeMauldin** [comment]
User A and User B are are separate machines. User A connects first and this is successful. While User A is still connected, User B attempts to connect and User B is unable to connect as shown in the logs. This scenario works as expected when the destination system is Linux but fails when the destination system is Windows Server 2019.
The client machines in both cases are Windows 10.

**Comment by bamurtaugh** [comment]
It sounds like this issue may have come up again in https://github.com/microsoft/vscode-remote-release/issues/4940. Perhaps you could see if the workaround mentioned in the issue to try a different version of the extension/server works?

**Comment by LukeMauldin** [comment]
Yes, using different versions of VSCode with different server ids us a temporary work-around for this issue. However, most of our developers work from a standard template with a controlled version of VSCode installed and so this work-around is less than ideal for us. This workaround is also not required when the destination server is Linux.

**Comment by bamurtaugh** [comment]
Makes sense, thanks for trying it out. Verifying the workaround does technically work helps verify these two issues seem to have the same root cause. 👍

**Comment by connor4312** [comment]
Verified on Windows 10 desktop, assuming that's valid
