### ISSUE TITLE
Wrong architecture of server is installed on remote system

### ISSUE THREAD

**Issue by nlsweet** [microsoft/vscode-remote-release#4558]
- VSCode Version: 1.53.2
- Local OS Version: Ubuntu 20.04.2
- Remote OS Version: Ubuntu 18.04.5
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Try to connect to remote system with remote extension
2. Wait for failure...

```
[17:55:36.048] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (/home/nlsweet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:64057)
	at c (/home/nlsweet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:58602)
	at Object.t.handleInstallOutput (/home/nlsweet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:62898)
	at Object.t.tryInstallWithLocalServer (/home/nlsweet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:405581)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async /home/nlsweet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:310867
	at async Object.t.withShowDetailsEvent (/home/nlsweet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:406337)
	at async /home/nlsweet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:404105
	at async S (/home/nlsweet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:400873)
	at async Object.t.resolveWithLocalServer (/home/nlsweet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:403732)
	at async Object.t.resolve (/home/nlsweet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:1:314879)
	at async /home/nlsweet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.64.0/out/extension.js:127:110431
```

Pertinent info:
The remote target is an embedded board with an ARMv8 procesor, but running 32 bit.  So the output of uname is misleading:
```
user@host:~$ uname -m
aarch64
user@host:~$ getconf LONG_BIT
32
```

I tried installing a 32 bit version of node on the remote system and editing the server.sh script.  I had to reinstall the 'spdlog' module, since it also wasn't 32 bit.  But that only got me so far.  At that point, the extension quietly failed to connect and the remote server log complained about "Unauthorized client refused."

**Comment by roblourens** [comment]
Can you share the output of `uname -a`?

Is there a typical standard way to get the correct arch? Have not seen `getconf LONG_BIT` yet. This sort of thing has come up before but I don't know how to fix it in general.

**Comment by nlsweet** [comment]
Yeah, that `getconf LONG_BIT` trick was new to me as well.  In the past, I have always relied on uname being definitive, but it looks like ARM may introduce some ambiguities.  Here's the output you asked for:
```
$ uname -a
Linux hostname 4.14.0-xilinx-v2018.2 #1 SMP Thu Nov 1 13:05:48 MDT 2018 aarch64 aarch64 aarch64 GNU/Linux
```

And also, in case you're curious:
```
$ file $(which uname)
/bin/uname: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=c6082875291b6a0e9ab0effea7c7c3824fa4066c, stripped
```

And there's also:
```
$ sudo lshw -class system
hostname
    description: Computer
    product: ZynqMP ZCU102 Rev1.0
    **width: 32 bits**
    capabilities: smp
```

I suspect that this is one of those corner cases that shows up only rarely.  Is there a way to possibly work around the issue?   LIke possibly downloading the server tarball manually and installing it on the remote system?

**Comment by roblourens** [comment]
Hm, running `file` on some userspace binary could be a useful trick. We can continue this in https://github.com/microsoft/vscode-remote-release/issues/2947.
