### ISSUE TITLE
Python Extension WSL Error

### ISSUE THREAD

**Issue by siweiwang24** [microsoft/vscode-remote-release#4563]
I have WSL 2, VS Code, and Remote-WSL installed. I previously had Python and Pylance extensions working in remote-wsl. However, I did a clean install of VS Code and now I'm able to install both extensions locally, but unable to get them working in WSL.

When I attempt to install either, I get the message:
```Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.53.2'.```

**Comment by sandy081** [comment]
Can you please enable log level to trace using `F1 > Set Log Level` and retry installing and share us following logs

- F1 > Open View > Log (Window)
- F1 > Open View > Log (Remote Server)

**Comment by siweiwang24** [comment]
@sandy081 Here's (what I think are) the relevant logs.

*WIndow*
```text
[2021-02-26 12:18:14.152] [renderer1] [trace] Download 'ms-python.python' extension locally and install
[2021-02-26 12:18:14.160] [renderer1] [debug] Webview(extensionEditor): will post message on 'focus'
[2021-02-26 12:18:14.160] [renderer1] [debug] Webview(extensionEditor): did post message on 'focus'
[2021-02-26 12:18:14.215] [renderer1] [trace] RequestService#request https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2021.2.582707922/1613774555212/Microsoft.VisualStudio.Code.Manifest
[2021-02-26 12:18:14.220] [renderer1] [trace] RequestService#request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
[2021-02-26 12:18:14.275] [renderer1] [trace] RequestService#request https://ms-toolsai.gallerycdn.vsassets.io/extensions/ms-toolsai/jupyter/2021.3.593162453/1614099708627/Microsoft.VisualStudio.Code.Manifest
[2021-02-26 12:18:14.280] [renderer1] [trace] ExtensionGalleryService#download ms-toolsai.jupyter
[2021-02-26 12:18:14.281] [renderer1] [trace] RequestService#request https://ms-toolsai.gallery.vsassets.io/_apis/public/gallery/publisher/ms-toolsai/extension/jupyter/2021.3.593162453/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage?redirect=true&update=true
```

*Remote Server*
```text
[2021-02-26 12:19:17.308] [remoteagent] [trace] Started scanning user extensions
[2021-02-26 12:19:17.311] [remoteagent] [trace] {"errno":-2,"code":"ENOENT","syscall":"open","path":"/home/siweiw/.vscode-server/extensions/ms-python.python-2021.2.582707922/package.json"}
[2021-02-26 12:19:17.334] [remoteagent] [trace] Scanned user extensions: 12
[2021-02-26 12:19:17.561] [remoteagent] [trace] ExtensionManagementService#install vscode-local:/c%3A/Users/siwei/AppData/Local/Temp/a24931b8-603a-4e4a-9624-9e211934298f
```

**Comment by sandy081** [comment]
Thanks for the logs

Just wondering have not you seen any other log statements after this line in remote server log

```
[2021-02-26 12:19:17.561] [remoteagent] [trace] ExtensionManagementService#install vscode-local:/c%3A/Users/siwei/AppData/Local/Temp/a24931b8-603a-4e4a-9624-9e211934298f
```

This shall stream the downloaded VSIX from desktop to WSL and install in WSL

**Comment by remss** [comment]
I'm running in the same issue trying to install pylance extension once attached to a remote docker container.

```
Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.53.2'.
```

Here the logs

```
[2021-03-02 15:42:34.437] [remoteagent] [trace] Scanned system extensions: 31
[2021-03-02 15:42:47.517] [remoteagent] [trace] Started scanning user extensions
[2021-03-02 15:42:47.529] [remoteagent] [trace] Scanned user extensions: 4
[2021-03-02 15:42:48.026] [remoteagent] [trace] ExtensionManagementService#install vscode-local:/c%3A/Users/joe/AppData/Local/Temp/8c7a580a-387f-4ce7-a56a-211dfb5bb8a6
[2021-03-02 15:42:48.029] [remoteagent] [trace] ExtensionManagementService#install vscode-local:/c%3A/Users/joe/AppData/Local/Temp/0bd76862-6ac7-4d74-97b5-07bf7df5aaa2
[2021-03-02 15:42:50.922] [remoteagent] [trace] Started scanning user extensions
[2021-03-02 15:42:50.932] [remoteagent] [trace] Scanned user extensions: 4
[2021-03-02 15:42:50.933] [remoteagent] [trace] Deleting existing extension from disk ms-python.python /home/joe/.vscode-server/extensions/ms-python.python-2021.2.582707922
[2021-03-02 15:42:51.033] [remoteagent] [info] Deleted from disk ms-python.python /home/joe/.vscode-server/extensions/ms-python.python-2021.2.582707922
[2021-03-02 15:42:51.033] [remoteagent] [info] Installing the extension: ms-python.python
[2021-03-02 15:42:51.034] [remoteagent] [trace] RequestService#request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
[2021-03-02 15:42:51.196] [remoteagent] [trace] Started extracting the extension from /tmp/08729fa9-6cce-4151-9566-19aaf1d39ca3 to /home/joe/.vscode-server/extensions/.ms-python.python-2021.2.582707922
[2021-03-02 15:42:52.515] [remoteagent] [info] Extracted extension to /home/joe/.vscode-server/extensions/.ms-python.python-2021.2.582707922: ms-python.python
[2021-03-02 15:42:52.515] [remoteagent] [info] Renamed to /home/joe/.vscode-server/extensions/ms-python.python-2021.2.582707922
[2021-03-02 15:42:52.517] [remoteagent] [info] Installation completed. ms-python.python
[2021-03-02 15:42:52.535] [remoteagent] [trace] Started scanning system extensions
[2021-03-02 15:42:52.535] [remoteagent] [trace] Started scanning user extensions
[2021-03-02 15:42:52.551] [remoteagent] [trace] Scanned user extensions: 4
[2021-03-02 15:42:52.561] [remoteagent] [trace] {"errno":-2,"code":"ENOENT","syscall":"open","path":"/home/joe/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/extensions/node_modules/package.json"}
[2021-03-02 15:42:52.565] [remoteagent] [trace] Scanned system extensions: 31
[2021-03-02 15:42:52.567] [remoteagent] [info] Successfully installed the extension: ms-python.python
```

**Comment by sandy081** [comment]
@remss I do not think this is the same issue, the error says that the jupyter extension is not compatible with the container - I would recommend to please file a separate issue so that this specific issue can be discussed without getting this issue distracted

**Comment by siweiwang24** [comment]
@sandy081 I did not see any logs after that line. However, I attempted it again today. After an update to Remote-WSL, I'm now able to install Python and Pylance in WSL, so the issue seems to be patched.

**Comment by pford221** [comment]
This is still an issue for me. 

VSCode version: 1.54.1
ms-python version: 2021.2.625...

Log (Window)
```
[2021-03-07 16:15:30.935] [renderer1] [error] Error while installing 'ms-python.python' extension in the remote server. read ECONNRESET
[2021-03-07 16:15:30.935] [renderer1] [info] Trying to download 'ms-python.python' extension locally and install
[2021-03-07 16:15:43.105] [renderer1] [error] ["Error: Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.1'.","    at /mnt/N0225086/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostAgent.js:108:97446","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]
[2021-03-07 16:15:43.123] [renderer1] [error] ["downloading: read ECONNRESET","    at Ee.downloadInstallableExtension (/mnt/N0225086/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostAgent.js:108:103265)","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]
[2021-03-07 16:15:43.161] [renderer1] [error] read ECONNRESET: downloading: read ECONNRESET
    at Ee.downloadInstallableExtension (/mnt/N0225086/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostAgent.js:108:103265)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Log (Remote Server)
```
[2021-03-07 19:15:32.151] [remoteagent] [info] Installing extension: ms-python.python
[2021-03-07 19:15:32.209] [remoteagent] [error] Failed to install extension: ms-python.python read ECONNRESET
```

**Comment by sandy081** [comment]
@pford221 Your issue seems related to this - #117986

**Comment by pford221** [comment]
@sandy081 - Apologies but is that a valid issue #? I can't find it.

**Comment by sandy081** [comment]
Sorry wrong link it is https://github.com/microsoft/vscode/issues/117986

**Comment by siweiwang24** [comment]
I'm encountering a similar issue when trying to install the PyLance extension in VS Code, though the Python extension now works fine.  I get the error `Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.3'.` Here are the logs. This has been an issue for around a now.

```text
[2021-03-21 23:03:23.855] [remoteagent] [trace] Started scanning user extensions
[2021-03-21 23:03:23.873] [remoteagent] [trace] Scanned user extensions: 13
[2021-03-21 23:03:24.179] [remoteagent] [trace] ExtensionManagementService#install vscode-local:/c%3A/Users/siwei/AppData/Local/Temp/caba5097-4bdd-44e5-bb34-f8198d19d868
[2021-03-21 23:03:24.213] [remoteagent] [trace] ExtensionManagementService#install vscode-local:/c%3A/Users/siwei/AppData/Local/Temp/31a76882-1754-4c3b-af44-0d003114e932
[2021-03-21 23:03:25.812] [remoteagent] [trace] Started scanning user extensions
[2021-03-21 23:03:25.839] [remoteagent] [trace] Scanned user extensions: 13
[2021-03-21 23:03:25.840] [remoteagent] [trace] Deleting existing extension from disk ms-python.python /home/siweiw/.vscode-server/extensions/ms-python.python-2021.3.658691958
[2021-03-21 23:03:26.028] [remoteagent] [info] Deleted from disk ms-python.python /home/siweiw/.vscode-server/extensions/ms-python.python-2021.3.658691958
[2021-03-21 23:03:26.028] [remoteagent] [info] Installing the extension: ms-python.python
[2021-03-21 23:03:26.028] [remoteagent] [trace] RequestService#request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
[2021-03-21 23:03:26.203] [remoteagent] [trace] Started extracting the extension from /tmp/7c0df3ff-6d48-49dd-b0cd-af91ac78fa81 to /home/siweiw/.vscode-server/extensions/.ms-python.python-2021.3.658691958
[2021-03-21 23:03:28.093] [remoteagent] [info] Extracted extension to /home/siweiw/.vscode-server/extensions/.ms-python.python-2021.3.658691958: ms-python.python
[2021-03-21 23:03:28.093] [remoteagent] [info] Renamed to /home/siweiw/.vscode-server/extensions/ms-python.python-2021.3.658691958
[2021-03-21 23:03:28.095] [remoteagent] [info] Installation completed. ms-python.python
[2021-03-21 23:03:28.108] [remoteagent] [trace] Started scanning system extensions
[2021-03-21 23:03:28.108] [remoteagent] [trace] Started scanning user extensions
[2021-03-21 23:03:28.143] [remoteagent] [trace] {"errno":-2,"code":"ENOENT","syscall":"open","path":"/home/siweiw/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/extensions/node_modules/package.json"}
[2021-03-21 23:03:28.157] [remoteagent] [trace] Scanned user extensions: 13
[2021-03-21 23:03:28.158] [remoteagent] [trace] Scanned system extensions: 31
[2021-03-21 23:03:28.160] [remoteagent] [info] Successfully installed the extension: ms-python.python

```

**Comment by sandy081** [comment]
/duplicate

This is being actively discussed and investigated here - https://github.com/microsoft/vscode/issues/119073
