### ISSUE TITLE
ENOTCON log spam

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#4581]
My Log (Window) in a remote-ssh window is full of this:

```
[2021-03-01 15:21:04.389] [renderer1] [error] read ENOTCONN: Error: read ENOTCONN
    at tryReadStart (net.js:573:20)
    at Socket._read (net.js:584:5)
    at Socket.Readable.read (_stream_readable.js:467:10)
    at Socket.read (net.js:624:39)
    at new Socket (net.js:376:12)
    at Object.Socket (net.js:267:41)
    at createSocket (internal/child_process.js:314:14)
    at ChildProcess.spawn (internal/child_process.js:437:23)
    at Object.spawn (child_process.js:557:9)
    at /Users/roblou/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.162.0/dist/extension/extension.js:77:1087
    at W (/Users/roblou/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.162.0/dist/extension/extension.js:76:499)
    at V0 (/Users/roblou/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.162.0/dist/extension/extension.js:82:1393)
    at OP (/Users/roblou/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.162.0/dist/extension/extension.js:167:9406)
    at mr (/Users/roblou/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.162.0/dist/extension/extension.js:167:9356)
    at $q (/Users/roblou/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.162.0/dist/extension/extension.js:233:42643)
    at /Users/roblou/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.162.0/dist/extension/extension.js:233:31717
```

**Comment by chrmarti** [comment]
I wonder if anything has changed here. I also see 3 of them from the Git extension (/cc @eamodio):
```
ERR read ENOTCONN: Error: read ENOTCONN
    at tryReadStart (net.js:573:20)
    at Socket._read (net.js:584:5)
    at Socket.read (_stream_readable.js:467:10)
    at Socket.read (net.js:624:39)
    at new Socket (net.js:376:12)
    at Object.Socket (net.js:267:41)
    at createSocket (internal/child_process.js:314:14)
    at ChildProcess.spawn (internal/child_process.js:437:23)
    at Object.spawn (child_process.js:557:9)
    at Object.spawn (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git/dist/main.js:1:89263)
    at Object._exec (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git/dist/main.js:1:88431)
    at Object.exec (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git/dist/main.js:1:88272)
    at Object.getRepositoryRoot (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git/dist/main.js:1:87521)
    at g.openRepository (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git/dist/main.js:10:406906)
    at n (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git/dist/main.js:1:24277)
```

My fix (apart from polling less frequently) is to also handle 'error' on those stdio streams of the child_process on which I listen for 'data'. ENOTCONN I then ignore, others I rethrow. (https://github.com/microsoft/vscode-remote-containers/commit/758148a66263affdf64fb3ba643ed99e39ae703c)
