### ISSUE TITLE
CentOS 6.8 based container is not supported (GLIBCXX 3.4.18 is required)

### ISSUE THREAD

**Issue by jarni-ua** [microsoft/vscode-remote-release#459]
Hi,

My development environment is CentOS 6.8 based with devtoolset-3 installed and I can't use it with VSCode Remote. The following error occurs:
...
Run: docker build -f ...
...
Successfully built 3ba35cf5c334
Successfully tagged vsc-dmp-b5e7a69cf61e46ccfac3f05e76a8dee9:latest
Run: docker run -a STDOUT -a STDERR ... -l vsch.remote.devPort=9753 vsc-dmp-b5e7a69cf61e46ccfac3f05e76a8dee9 /bin/sh -c echo Container started ;  while sleep 1; do :; done
Container started
Run: docker exec 2dc1d9a974f433551fd511769d3d9921413c954107488e4c35b0986e627d1f01 /bin/sh -c (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
Run: docker exec 2dc1d9a974f433551fd511769d3d9921413c954107488e4c35b0986e627d1f01 test -d /root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9
Installing VS Code Server for commit 16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9
Run: docker exec 2dc1d9a974f433551fd511769d3d9921413c954107488e4c35b0986e627d1f01 mkdir -p /root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9_1558962043341
Run: docker cp /var/folders/d1/0_j5pqw13wjb_3xl8pwkp__r0000gn/T/vsch/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/vscode-server-linux-x64.tar.gz 2dc1d9a974f433551fd511769d3d9921413c954107488e4c35b0986e627d1f01:/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9_1558962043341
Run: docker exec -w /root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9_1558962043341 2dc1d9a974f433551fd511769d3d9921413c954107488e4c35b0986e627d1f01 tar -xf vscode-server-linux-x64.tar.gz --strip-components 1
Run: docker exec -w /root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9_1558962043341 2dc1d9a974f433551fd511769d3d9921413c954107488e4c35b0986e627d1f01 rm vscode-server-linux-x64.tar.gz
Run: docker exec 2dc1d9a974f433551fd511769d3d9921413c954107488e4c35b0986e627d1f01 mv -n /root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9_1558962043341 /root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9
Run: docker exec 2dc1d9a974f433551fd511769d3d9921413c954107488e4c35b0986e627d1f01 test -d /root/.vscode-remote/extensions
Run: docker exec 2dc1d9a974f433551fd511769d3d9921413c954107488e4c35b0986e627d1f01 /bin/sh -c set -o noclobber ; mkdir -p '/root/.vscode-remote/data/Machine' && { > '/root/.vscode-remote/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
Run: docker exec 2dc1d9a974f433551fd511769d3d9921413c954107488e4c35b0986e627d1f01 /bin/sh -c set -o noclobber ; mkdir -p '/root/.vscode-remote/data/Machine' && { > '/root/.vscode-remote/data/Machine/.postCreateCommandMarker' ; } 2> /dev/null
Run: docker exec 2dc1d9a974f433551fd511769d3d9921413c954107488e4c35b0986e627d1f01 test -f /root/.vscode-remote/.postCreateCommandMarker
Run: docker exec -w /root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9 -u 0 2dc1d9a974f433551fd511769d3d9921413c954107488e4c35b0986e627d1f01 /bin/sh -c command -v git >/dev/null 2>&1 && git config --system credential.helper '!f() { command -v code-insiders >/dev/null 2>&1 && code-insiders --gitCredential $*; }; f' || true
Run: docker exec -w /root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9 2dc1d9a974f433551fd511769d3d9921413c954107488e4c35b0986e627d1f01 /usr/bin/scl enable devtoolset-3 PATH="/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/bin:$PATH" /root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/server.sh  --port 9753
Remote configuration data at /root/.vscode-remote
...
**Error: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/node_modules/spdlog/build/Release/spdlog.node)**
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:731:18)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at Module.patchedRequire [as require] (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/node_modules/spdlog/index.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at Module.patchedRequire [as require] (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Function.i [as __$__nodeRequire] (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:31:542)
    at /root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/agent/remoteExtensionHostAgent.js:220:255
    at Generator.next (<anonymous>)
    at /root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/agent/remoteExtensionHostAgent.js:16:388
    at new Promise (<anonymous>)
    at r (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/agent/remoteExtensionHostAgent.js:16:165)
    at o (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/agent/remoteExtensionHostAgent.js:220:208)
    at Object.t.createBufferSpdLogService (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/agent/remoteExtensionHostAgent.js:220:738)
    at K.<anonymous> (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/agent/remoteExtensionHostAgent.js:371:497)
    at Generator.next (<anonymous>)
    at /root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/agent/remoteExtensionHostAgent.js:16:388
    at new Promise (<anonymous>)
    at r (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/agent/remoteExtensionHostAgent.js:16:165)
    at K._createServices (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/agent/remoteExtensionHostAgent.js:371:288)
    at Function.create (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/agent/remoteExtensionHostAgent.js:371:218)
    at O.<anonymous> (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/agent/remoteExtensionHostAgent.js:375:506)
    at Generator.next (<anonymous>)
    at /root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/agent/remoteExtensionHostAgent.js:16:388
    at new Promise (<anonymous>)
    at r (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/agent/remoteExtensionHostAgent.js:16:165)
    at O.start (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/agent/remoteExtensionHostAgent.js:375:425)
    at Object.<anonymous> (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/agent/remoteExtensionHostAgent.js:383:992)
    at Function.t._safeInvokeFunction (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:20:173)
    at Function.t._invokeFactory (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:20:420)
    at t.complete (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:20:657)
    at s._onModuleComplete (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:30:796)
    at s._onModuleComplete (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:31:41)
    at s._onModuleComplete (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:31:41)
    at s._onModuleComplete (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:31:41)
    at s._onModuleComplete (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:31:41)
    at s._onModuleComplete (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:31:41)
    at s._resolve (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:30:356)
    at s.defineModule (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:24:768)
    at r (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:28:919)
    at Object.l (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:36:405)
    at Function.t._safeInvokeFunction (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:20:173)
    at Function.t._invokeFactory (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:20:420)
    at t.complete (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:20:657)
    at s._onModuleComplete (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:30:796)
    at s._onModuleComplete (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:31:41)
    at s._resolve (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:30:356)
    at s.defineModule (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:24:768)
    at r (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:31:950)
    at f (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:17:524)
    at Object.<anonymous> (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/agent/remoteExtensionHostAgent.nls.js:4:1)
    at t._loadAndEvalScript (/root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:17:568)
    at /root/.vscode-remote/bin/16de3c28db1d2c6fbe2227d1ffe91c5e7e683bc9/out/vs/loader.js:17:285
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)
...
CentOS 6.8 supports at most GLIBCXX 3.4.13:
 $ strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_FORCE_NEW
GLIBCXX_DEBUG_MESSAGE_LENGTH

Is there a hard requirement to use GLIBCXX 3.4.18? Can it be downgraded to 3.4.13?

**Comment by Chuxel** [comment]
@jarni-ua This is related to #103. Currently these are hard requirements, but you should be able to use a Dockerfile to run the [commands described here](https://github.com/Microsoft/vscode-remote-release/issues/103#issuecomment-497118857).

For example:

```Dockerfile
FROM centos:6

RUN yum -y install wget

# Update glibc
RUN wget -q http://copr-be.cloud.fedoraproject.org/results/mosquito/myrepo-el6/epel-6-x86_64/glibc-2.17-55.fc20/glibc-2.17-55.el6.x86_64.rpm \
    && wget -q http://copr-be.cloud.fedoraproject.org/results/mosquito/myrepo-el6/epel-6-x86_64/glibc-2.17-55.fc20/glibc-common-2.17-55.el6.x86_64.rpm \
    && wget -q http://copr-be.cloud.fedoraproject.org/results/mosquito/myrepo-el6/epel-6-x86_64/glibc-2.17-55.fc20/glibc-devel-2.17-55.el6.x86_64.rpm \
    && wget -q http://copr-be.cloud.fedoraproject.org/results/mosquito/myrepo-el6/epel-6-x86_64/glibc-2.17-55.fc20/glibc-headers-2.17-55.el6.x86_64.rpm \
    && wget -q https://copr-be.cloud.fedoraproject.org/results/mosquito/myrepo-el6/epel-6-x86_64/glibc-2.17-55.fc20/glibc-utils-2.17-55.el6.x86_64.rpm \
    && wget -q https://copr-be.cloud.fedoraproject.org/results/mosquito/myrepo-el6/epel-6-x86_64/glibc-2.17-55.fc20/glibc-static-2.17-55.el6.x86_64.rpm \
    && rpm -Uh --force --nodeps \
        glibc-2.17-55.el6.x86_64.rpm \
        glibc-common-2.17-55.el6.x86_64.rpm \
        glibc-devel-2.17-55.el6.x86_64.rpm \
        glibc-headers-2.17-55.el6.x86_64.rpm \
        glibc-static-2.17-55.el6.x86_64.rpm \
        glibc-utils-2.17-55.el6.x86_64.rpm \
    && rm *.rpm

# Update libstdc++
RUN  wget -q https://copr-be.cloud.fedoraproject.org/results/mosquito/myrepo-el6/epel-6-x86_64/gcc-4.8.2-16.3.fc20/libstdc++-4.8.2-16.3.el6.x86_64.rpm \
    && wget -q https://copr-be.cloud.fedoraproject.org/results/mosquito/myrepo-el6/epel-6-x86_64/gcc-4.8.2-16.3.fc20/libstdc++-devel-4.8.2-16.3.el6.x86_64.rpm \
    && wget -q https://copr-be.cloud.fedoraproject.org/results/mosquito/myrepo-el6/epel-6-x86_64/gcc-4.8.2-16.3.fc20/libstdc++-static-4.8.2-16.3.el6.x86_64.rpm \
    && rpm -Uh \
        libstdc++-4.8.2-16.3.el6.x86_64.rpm \
        libstdc++-devel-4.8.2-16.3.el6.x86_64.rpm \
        libstdc++-static-4.8.2-16.3.el6.x86_64.rpm \
    && rm *.rpm

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash
```

**Comment by jarni-ua** [comment]
@Chuxel Thank you very much for provided Dockerfile. I'll try that out for development image.

I'll close this ticket because the core reason is the same as in #103, thank you for pointing to that.
