### ISSUE TITLE
Fortmat remote source file takes too long

### ISSUE THREAD

**Issue by milesxu** [microsoft/vscode-remote-release#4594]
- VSCode Version: 1.53.2
- Local OS Version: 5.11.1-1-MANJARO #1 SMP PREEMPT Tue Feb 23 14:26:47 UTC 2021 x86_64 GNU/Linux
- Remote OS Version: 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. There is a formatter for CPP files, either clang-format or cpptools. 
2. Format a cpp source file on the remote machine takes too long to finish. 

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

Local: Remote development only
Server: C/C++ only

If I use cpptools for formatting, and selected "format on save", then the formatting will last too long after save:
![image](https://user-images.githubusercontent.com/2003731/109922893-06ef9e80-7cf9-11eb-93ee-151409f8dca3.png)

If I use clang-format on remote, I will get the error below:
![109903041-3d67f200-7cd6-11eb-8e1d-a9089fe95502](https://user-images.githubusercontent.com/2003731/109923477-d0665380-7cf9-11eb-9871-683e1246759f.png)

**I haven't found any error when I editing local files. Formating on same files locally will finish immediately.**

Remote SSH output:

```
[15:23:03.517] [Forwarding server 29861] Got connection 1
[15:23:03.532] [Forwarding server 29861] Got connection 2
[15:23:06.873] "Update SSH_AUTH_SOCK" terminal command done
[15:23:08.465] Unhandled rejection: Error: spawn git ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[15:23:08.477] Unhandled rejection: Error: spawn git ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
[15:23:27.777] TELEMETRY: {"eventName":"extraInfo","properties":{"remoteCloud":""},"measures":{}}
```
Log (Remote Server) output:
```
[2021-03-04 15:23:03.564] [remoteagent] [info] Last EH closed, waiting before shutting down
[2021-03-04 15:23:03.566] [remoteagent] [error] [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/home/nfs/admin0/milesxu/src/caffe-0.17.3/.vscode'
[2021-03-04 15:23:03.757] [remoteagent] [info] [127.0.0.1][b476966d][ExtensionHostConnection] New connection established.
[2021-03-04 15:23:03.853] [remoteagent] [info] [127.0.0.1][b476966d][ExtensionHostConnection] <77654> Launched Extension Host Process.
[2021-03-04 15:28:03.565] [remoteagent] [info] New EH opened, aborting shutdown
```
Log(Remote Extension Host) output:
```
[2021-03-04 15:25:38.760] [exthost] [error] [ms-vscode.cpptools] provider FAILED
[2021-03-04 15:25:38.760] [exthost] [error] undefined
```

**Comment by roblourens** [comment]
Please file this issue on the repo for the extension that you are using
