### ISSUE TITLE
Segmentation fault in server

### ISSUE THREAD

**Issue by dniku** [microsoft/vscode-remote-release#4596]
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z (3 wks ago)
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

- Local OS Version: macOS Catalina 10.15.6
- Remote OS Version: custom Docker image based on Ubuntu Bionic
- Remote Extension/Connection Type: SSH

Not sure about the exact steps to reproduce, as the problem seems to manifest only with our company's proprietary Docker image.

The VSCode Server process crashes with a segfault, leaving the following in `~/.vscode-server/.622cb03f7e070a9670c94bae1a45d78d7181fbd4.log`:

```


*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*

Extension host agent listening on 35653

[19:28:57] Extension host agent started.


#
# Fatal error in , line 0
# Check failed: page_allocator->DiscardSystemPages( reinterpret_cast<void*>(memory_area.begin()), memory_area.size()).
#
#
#
#FailureMessage Object: 0x7fff3ad8b970


#
# Fatal error in , line 0
# Check failed: page_allocator->DiscardSystemPages( reinterpret_cast<void*>(memory_area.begin()), memory_area.size()).
#
#
#
#FailureMessage Object: 0x7fd2b72a1070


#
# Fatal error in , line 0
# Check failed: page_allocator->DiscardSystemPages( reinterpret_cast<void*>(memory_area.begin()), memory_area.size()).
#
#
#
#FailureMessage Object: 0x7fd2b5a9e070


#
# Fatal error in , line 0
# Check failed: page_allocator->DiscardSystemPages( reinterpret_cast<void*>(memory_area.begin()), memory_area.size()).
#
#
#
#FailureMessage Object: 0x7fd2b629f070
 1: 0xa760a1  [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 1: 0xa760a1  [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 1: 0xa760a1  [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 1: 0xa760a1  [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 2: 0x19f5a75 V8_Fatal(char const*, ...) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 3: 0xd9ebcf  [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 2: 0x19f5a75 V8_Fatal(char const*, ...) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 3: 0xd9ebcf  [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 2: 0x19f5a75 V8_Fatal(char const*, ...) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 3: 0xd9ebcf  [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 4: 0xdb111b v8::internal::Sweeper::RawSweep(v8::internal::Page*, v8::internal::Sweeper::FreeListRebuildingMode, v8::internal::FreeSpaceTreatmentMode, v8::internal::Sweeper::FreeSpaceMayContainInvalidatedSlots) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 5: 0xdb5cba v8::internal::Sweeper::ParallelSweepSpace(v8::internal::AllocationSpace, int, int, v8::internal::Sweeper::FreeSpaceMayContainInvalidatedSlots) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 6: 0xda978a v8::internal::PagedSpace::RawSlowRefillLinearAllocationArea(int, v8::internal::AllocationOrigin) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 2: 0x19f5a75 V8_Fatal(char const*, ...) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 3: 0xd9ebcf  [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 4: 0xdb111b v8::internal::Sweeper::RawSweep(v8::internal::Page*, v8::internal::Sweeper::FreeListRebuildingMode, v8::internal::FreeSpaceTreatmentMode, v8::internal::Sweeper::FreeSpaceMayContainInvalidatedSlots) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 7: 0xd07e20 v8::internal::PagedSpace::AllocateRaw(int, v8::internal::AllocationAlignment, v8::internal::AllocationOrigin) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 8: 0xd600fb v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 9: 0xd677b0 void v8::internal::LiveObjectVisitor::VisitBlackObjectsNoFail<v8::internal::EvacuateNewSpaceVisitor, v8::internal::MajorNonAtomicMarkingState>(v8::internal::MemoryChunk*, v8::internal::MajorNonAtomicMarkingState*, v8::internal::EvacuateNewSpaceVisitor*, v8::internal::LiveObjectVisitor::IterationMode) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
10: 0xd76bb8 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 4: 0xdb111b v8::internal::Sweeper::RawSweep(v8::internal::Page*, v8::internal::Sweeper::FreeListRebuildingMode, v8::internal::FreeSpaceTreatmentMode, v8::internal::Sweeper::FreeSpaceMayContainInvalidatedSlots) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 4: 0xdb111b v8::internal::Sweeper::RawSweep(v8::internal::Page*, v8::internal::Sweeper::FreeListRebuildingMode, v8::internal::FreeSpaceTreatmentMode, v8::internal::Sweeper::FreeSpaceMayContainInvalidatedSlots) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 5: 0xdb5cba v8::internal::Sweeper::ParallelSweepSpace(v8::internal::AllocationSpace, int, int, v8::internal::Sweeper::FreeSpaceMayContainInvalidatedSlots) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 6: 0xda978a v8::internal::PagedSpace::RawSlowRefillLinearAllocationArea(int, v8::internal::AllocationOrigin) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 7: 0xd07e20 v8::internal::PagedSpace::AllocateRaw(int, v8::internal::AllocationAlignment, v8::internal::AllocationOrigin) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 8: 0xd600fb v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
11: 0xd595fe v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 5: 0xdb5cba v8::internal::Sweeper::ParallelSweepSpace(v8::internal::AllocationSpace, int, int, v8::internal::Sweeper::FreeSpaceMayContainInvalidatedSlots) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 5: 0xdb5cba v8::internal::Sweeper::ParallelSweepSpace(v8::internal::AllocationSpace, int, int, v8::internal::Sweeper::FreeSpaceMayContainInvalidatedSlots) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
 9: 0xd677b0 void v8::internal::LiveObjectVisitor::VisitBlackObjectsNoFail<v8::internal::EvacuateNewSpaceVisitor, v8::internal::MajorNonAtomicMarkingState>(v8::internal::MemoryChunk*, v8::internal::MajorNonAtomicMarkingState*, v8::internal::EvacuateNewSpaceVisitor*, v8::internal::LiveObjectVisitor::IterationMode) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
12: 0xd59a07 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
13: 0xd4eba5 v8::internal::ItemParallelJob::Task::RunInternal() [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
14: 0xc83c33 v8::internal::CancelableTask::Run() [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
15: 0xa75ef9  [/home/user/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/node]
16: 0x7fd2b7e9c6db  [/lib/x86_64-linux-gnu/libpthread.so.0]
17: 0x7fd2b7bc571f clone [/lib/x86_64-linux-gnu/libc.so.6]
Illegal instruction (core dumped)
```

Does this issue occur when you try this locally?: n/a
Does this issue occur when you try this locally and all extensions are disabled?: n/a

**Comment by roblourens** [comment]
Does the remote meet the prerqs here? https://code.visualstudio.com/docs/remote/linux

**Comment by dniku** [comment]
This particular issue _might_ be caused by `LD_PRELOAD` containing some custom libraries that cause Node to go crazy. Is there a way to tell VSCode to launch a remote SSH server with some environment variables either unset or customized? I haven't managed to find any documentation on that.

**Comment by dniku** [comment]
Seems that it does:
```
$ apt list libc6 libstdc++6 python-minimal ca-certificates tar openssh-server bash wget
Listing... Done
bash/unstable,now 4.4.18-2ubuntu1.2+sdcbionic1 amd64 [installed]
ca-certificates/bionic-updates,bionic-security,now 20210119~18.04.1 all [installed,automatic]
libc6/bionic-updates,now 2.27-3ubuntu1.4 amd64 [installed]
libstdc++6/bionic-updates,bionic-security,now 8.4.0-1ubuntu1~18.04 amd64 [installed]
openssh-server/bionic-updates,bionic-security,now 1:7.6p1-4ubuntu0.3 amd64 [installed]
python-minimal/bionic,now 2.7.15~rc1-1 amd64 [installed]
tar/bionic-updates,bionic-security,now 1.29b-2ubuntu0.2 amd64 [installed]
wget/bionic-updates,bionic-security,now 1.19.4-1ubuntu2.2 amd64 [installed]
```

Kernel version is 4.19.131-34.

A few clarifications:

1. This Docker container is running on a remote machine. Inside, it has an sshd server, which I connect to using the Remote SSH extension. The connection is set up via a jumping host (the remote machine itself, outside of the container) and is configured in `~/.ssh/config`.
2. The image has a custom `LD_PRELOAD` value. If I add `unset LD_PRELOAD` in `server.sh`, I get a different error log:
```


*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*

Extension host agent listening on 35481

[11:49:34] Extension host agent started.
[11:49:35] [127.0.0.1][2d7a3342][ExtensionHostConnection] New connection established.
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
[11:49:35] [127.0.0.1][ce91a6a6][ManagementConnection] New connection established.
[11:49:35] [127.0.0.1][2d7a3342][ExtensionHostConnection] <55412> Launched Extension Host Process.
EXTHOST-STDERR::::::::

#
# Fatal error in , line 0
# Check failed: page_allocator->DiscardSystemPages( reinterpret_cast<void*>(memory_area.begin()), memory_area.size()).
#
#
#
#FailureMessage Object: 0x7ffd94129770

EXTHOST-STDERR::::::::

#
# Fatal error in , line 0
# Check failed: page_allocator->DiscardSystemPages( reinterpret_cast<void*>(memory_area.begin()), memory_area.size()).
#
#
#
#FailureMessage Object: 0x7f58837fd100


#
# Fatal error in , line 0
# Check failed: page_allocator->DiscardSystemPages( reinterpret_cast<void*>(memory_area.begin()), memory_area.size()).
#
#
#
#FailureMessage Object: 0x7f58827fb100

EXTHOST-STDERR:::::::: 1: 0xa760a1  [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR::::::::

#
# Fatal error in , line 0
# Check failed: page_allocator->DiscardSystemPages( reinterpret_cast<void*>(memory_area.begin()), memory_area.size()).
#
#
#
#FailureMessage Object: 0x7f5883ffe100

EXTHOST-STDERR::::::::

#
# Fatal error in , line 0
# Check failed: page_allocator->DiscardSystemPages( reinterpret_cast<void*>(memory_area.begin()), memory_area.size()).
#
#
#
#FailureMessage Object: 0x7f5882ffc100

EXTHOST-STDERR:::::::: 2: 0x19f5a75 V8_Fatal(char const*, ...) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 1: 0xa760a1  [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 2: 0x19f5a75 V8_Fatal(char const*, ...) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 3: 0xd9ebcf  [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 3: 0xd9ebcf  [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 4: 0xdb2510 v8::internal::Sweeper::RawSweep(v8::internal::Page*, v8::internal::Sweeper::FreeListRebuildingMode, v8::internal::FreeSpaceTreatmentMode, v8::internal::Sweeper::FreeSpaceMayContainInvalidatedSlots) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 5: 0xdb5cba v8::internal::Sweeper::ParallelSweepSpace(v8::internal::AllocationSpace, int, int, v8::internal::Sweeper::FreeSpaceMayContainInvalidatedSlots) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 1: 0xa760a1  [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 2: 0x19f5a75 V8_Fatal(char const*, ...) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 1: 0xa760a1  [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 2: 0x19f5a75 V8_Fatal(char const*, ...) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 6: 0xda978a v8::internal::PagedSpace::RawSlowRefillLinearAllocationArea(int, v8::internal::AllocationOrigin) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 7: 0xd6724a bool v8::internal::LiveObjectVisitor::VisitBlackObjects<v8::internal::EvacuateOldSpaceVisitor, v8::internal::MajorNonAtomicMarkingState>(v8::internal::MemoryChunk*, v8::internal::MajorNonAtomicMarkingState*, v8::internal::EvacuateOldSpaceVisitor*, v8::internal::LiveObjectVisitor::IterationMode, v8::internal::HeapObject*) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 8: 0xd76dab v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 9: 0xd595fe v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 3: 0xd9ebcf  [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 4: 0xdb111b v8::internal::Sweeper::RawSweep(v8::internal::Page*, v8::internal::Sweeper::FreeListRebuildingMode, v8::internal::FreeSpaceTreatmentMode, v8::internal::Sweeper::FreeSpaceMayContainInvalidatedSlots) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 5: 0xdb5cba v8::internal::Sweeper::ParallelSweepSpace(v8::internal::AllocationSpace, int, int, v8::internal::Sweeper::FreeSpaceMayContainInvalidatedSlots) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 6: 0xda978a v8::internal::PagedSpace::RawSlowRefillLinearAllocationArea(int, v8::internal::AllocationOrigin) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 7: 0xd6724a bool v8::internal::LiveObjectVisitor::VisitBlackObjects<v8::internal::EvacuateOldSpaceVisitor, v8::internal::MajorNonAtomicMarkingState>(v8::internal::MemoryChunk*, v8::internal::MajorNonAtomicMarkingState*, v8::internal::EvacuateOldSpaceVisitor*, v8::internal::LiveObjectVisitor::IterationMode, v8::internal::HeapObject*) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 4: 0xdb111b v8::internal::Sweeper::RawSweep(v8::internal::Page*, v8::internal::Sweeper::FreeListRebuildingMode, v8::internal::FreeSpaceTreatmentMode, v8::internal::Sweeper::FreeSpaceMayContainInvalidatedSlots) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 5: 0xdb5cba v8::internal::Sweeper::ParallelSweepSpace(v8::internal::AllocationSpace, int, int, v8::internal::Sweeper::FreeSpaceMayContainInvalidatedSlots) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 6: 0xda978a v8::internal::PagedSpace::RawSlowRefillLinearAllocationArea(int, v8::internal::AllocationOrigin) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR::::::::10: 0xd598c4 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 8: 0xd76dab v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 9: 0xd595fe v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR::::::::10: 0xd59a07 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 7: 0xd6724a bool v8::internal::LiveObjectVisitor::VisitBlackObjects<v8::internal::EvacuateOldSpaceVisitor, v8::internal::MajorNonAtomicMarkingState>(v8::internal::MemoryChunk*, v8::internal::MajorNonAtomicMarkingState*, v8::internal::EvacuateOldSpaceVisitor*, v8::internal::LiveObjectVisitor::IterationMode, v8::internal::HeapObject*) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR::::::::11: 0xd4eba5 v8::internal::ItemParallelJob::Task::RunInternal() [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR::::::::12: 0xd4efb4 v8::internal::ItemParallelJob::Run() [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR::::::::13: 0xd68c67 void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, v8::internal::ItemParallelJob*, v8::internal::MigrationObserver*, long) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR::::::::11: 0xd4eba5 v8::internal::ItemParallelJob::Task::RunInternal() [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 8: 0xd76dab v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 3: 0xd9ebcf  [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 4: 0xdb111b v8::internal::Sweeper::RawSweep(v8::internal::Page*, v8::internal::Sweeper::FreeListRebuildingMode, v8::internal::FreeSpaceTreatmentMode, v8::internal::Sweeper::FreeSpaceMayContainInvalidatedSlots) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR::::::::14: 0xd79194 v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR::::::::12: 0xc83c33 v8::internal::CancelableTask::Run() [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 9: 0xd595fe v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 1: 0xa760a1  [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 5: 0xdb5cba v8::internal::Sweeper::ParallelSweepSpace(v8::internal::AllocationSpace, int, int, v8::internal::Sweeper::FreeSpaceMayContainInvalidatedSlots) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR::::::::15: 0xd79daa  [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR::::::::13: 0xa75ef9  [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR::::::::10: 0xd59a07 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR::::::::11: 0xd4eba5 v8::internal::ItemParallelJob::Task::RunInternal() [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 6: 0xda978a v8::internal::PagedSpace::RawSlowRefillLinearAllocationArea(int, v8::internal::AllocationOrigin) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 7: 0xd6724a bool v8::internal::LiveObjectVisitor::VisitBlackObjects<v8::internal::EvacuateOldSpaceVisitor, v8::internal::MajorNonAtomicMarkingState>(v8::internal::MemoryChunk*, v8::internal::MajorNonAtomicMarkingState*, v8::internal::EvacuateOldSpaceVisitor*, v8::internal::LiveObjectVisitor::IterationMode, v8::internal::HeapObject*) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 8: 0xd76dab v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR:::::::: 9: 0xd595fe v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR::::::::12: 0xc83c33 v8::internal::CancelableTask::Run() [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR::::::::16: 0xd7f027 v8::internal::MarkCompactCollector::CollectGarbage() [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]
14: 0x7f5888d2e6db  [/lib/x86_64-linux-gnu/libpthread.so.0]

EXTHOST-STDERR::::::::17: 0xd3d559 v8::internal::Heap::MarkCompact() [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR::::::::18: 0xd3e273 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR::::::::13: 0xa75ef9  [/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/node]

EXTHOST-STDERR::::::::14: 0x7f5888d2e6db  [/lib/x86_64-linux-gnu/libpthread.so.0]
15: 0x7f5888a5771f clone [/lib/x86_64-linux-gnu/libc.so.6]

[11:49:52] [127.0.0.1][2d7a3342][ExtensionHostConnection] <55412> Extension Host Process had an error
[11:49:52] Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:679:16)
    at u.shortenReconnectionGraceTimeIfNecessary (/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostAgent.js:108:125820)
    at /home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostAgent.js:120:2699
    at I.fire (/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostAgent.js:57:1836)
    at m.fire (/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostAgent.js:71:15486)
    at t._receiveMessage (/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostAgent.js:71:20791)
    at /home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostAgent.js:71:17630
    at I.fire (/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostAgent.js:57:1836)
    at u.acceptChunk (/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostAgent.js:71:12851)
    at /home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostAgent.js:71:12199
    at I.fire (/home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostAgent.js:57:1836)
    at /home/user/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostAgent.js:108:119040
    at afterWrite (_stream_writable.js:490:5)
    at onwrite (_stream_writable.js:470:7)
    at InflateRaw.afterTransform (_stream_transform.js:98:3)
    at Zlib.processCallback (zlib.js:578:8) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
Last EH closed, waiting before shutting down
[11:49:52] Last EH closed, waiting before shutting down
[11:49:52] [127.0.0.1][2d7a3342][ExtensionHostConnection] Unknown reconnection token.
[11:49:52] [127.0.0.1][ce91a6a6][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[11:49:52] [127.0.0.1][2d7a3342][ExtensionHostConnection] <55412> Extension Host Process exited with code: null, signal: SIGILL.
```

**Comment by dniku** [comment]
Sorry, this is not a VSCode problem. I get the same error when I just type `node` in the terminal and wait for ≈10 seconds.
