### ISSUE TITLE
Finding installed ssh failed: spawn ENOTDIR

### ISSUE THREAD

**Issue by nzardosh** [microsoft/vscode-remote-release#4615]
Issue Type: <b>Bug</b>

Hello,

I developed a problem a few days ago (potentially after a instability in my internet connection but I'm unsure) where I cant connect to any remote servers using VS anymore, and I cant seem to find a solution. Any help would be very much appreictaed, thank you. This is the error I get when using remote-ssh from the command palette to connect to a host:

[23:45:22.136] Log Level: 2
[23:45:22.138] remote-ssh@0.65.1
[23:45:22.138] darwin x64
[23:45:22.139] SSH Resolver called for "ssh-remote+pc115", attempt 1
[23:45:22.139] "remote.SSH.useLocalServer": true
[23:45:22.139] "remote.SSH.sshPath": undefined
[23:45:22.139] "remote.SSH.sshConfigurationFile": undefined
[23:45:22.139] "remote.SSH.useFlock": true
[23:45:22.140] "remote.SSH.lockfilesInTmp": false
[23:45:22.140] "remote.SSH.localServerDownload": auto
[23:45:22.140] "remote.SSH.remoteServerListenOnSocket": false
[23:45:22.140] "remote.SSH.showLoginTerminal": false
[23:45:22.140] "remote.SSH.defaultExtensions": []
[23:45:22.140] SSH Resolver called for host: pc115
[23:45:22.140] Setting up SSH remote "pc115"
[23:45:22.143] Acquiring local install lock: /var/folders/4z/dlcqf9bd2pbdc09rg7wnsn3m0000gn/T/vscode-remote-ssh-pc115-install.lock
[23:45:22.149] Looking for existing server data file at /Users/nima/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-pc115-f30a9b73e8ffc278e71575118b6bf568f04587c8-0.65.1/data.json
[23:45:22.149] Using commit id "f30a9b73e8ffc278e71575118b6bf568f04587c8" and quality "stable" for server
[23:45:22.152] Install and start server if needed
[23:45:22.155] Checking ssh with "ssh -V"
[23:45:22.156] Finding installed ssh failed: spawn ENOTDIR
[23:45:22.159] Resolver error: Error: spawn ENOTDIR
	at ChildProcess.spawn (internal/child_process.js:407:11)
	at Object.spawn (child_process.js:557:9)
	at /Users/nima/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:141985
	at new Promise (<anonymous>)
	at k (/Users/nima/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:141906)
	at I (/Users/nima/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:141857)
	at /Users/nima/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:145959
	at _ (/Users/nima/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:146024)
	at C (/Users/nima/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:141636)
	at Object.t.getSshCommandPath (/Users/nima/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:144744)
	at Function.create (/Users/nima/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:262426)
	at async Object.t.tryInstallWithLocalServer (/Users/nima/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:387852)
	at async /Users/nima/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:293749
	at async Object.t.withShowDetailsEvent (/Users/nima/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:407055)
	at async /Users/nima/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:387177
	at async N (/Users/nima/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:383945)
	at async Object.t.resolveWithLocalServer (/Users/nima/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:386804)
	at async Object.t.resolve (/Users/nima/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:297790)
	at async /Users/nima/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:127:110485
[23:45:22.161] ------

I can successfully connect to this (pc115) and other hosts using ssh on the terminal as normal. However there is one specific host which I can no longer connect to on the terminal but I dont know if this is related or not (i was connected to this host when my internet instability occured). This is the error I get when i try to connect to it on the terminal and I'll put it here in case it happens to be related :
channel 0: open failed: connect failed: No route to host
stdio forwarding failed
ssh_exchange_identification: Connection closed by remote host)

Extension version: 0.65.1
VS Code version: Code 1.54.1 (Universal) (f30a9b73e8ffc278e71575118b6bf568f04587c8, 2021-03-04T22:42:18.719Z)
OS version: Darwin x64 18.6.0
Fetching remote diagnostics for 'SSH' failed: spawn ENOTDIR

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.55GB free)|
|Process Argv|--crash-reporter-id 5cb94dd7-2149-4b54-a528-55dfa14e8d05|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: spawn ENOTDIR
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvsdeb440:30248342
pythonvsded773:30248341
vstes627:30244334
pythonvspyt875:30259475
dockersubset:30265998
pythontbcf:30265426
vspre833cf:30267465

```

</details>

**Comment by gremito** [comment]
It's the same symptom as this error, I'm in great trouble.

**Comment by roblourens** [comment]
Can you check whether setting `"remote.SSH.useLocalServer": false` makes any difference?

**Comment by roblourens** [comment]
Merging into https://github.com/microsoft/vscode-remote-release/issues/4630
