### ISSUE TITLE
Clone in Volume: Dev container not found

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#4625]
I also get this error when opening certain try-* samples via the Try a Sample command in Remote-Containers. I got it when I tried opening the Python sample for the first time, and now I just got it when trying to open the Go sample:

![image](https://user-images.githubusercontent.com/25310137/110161313-08c16c80-7da2-11eb-9801-a29305078e98.png)

```
[16 ms] Remote-Containers 0.163.0 in VS Code 1.54.1 (f30a9b73e8ffc278e71575118b6bf568f04587c8).
[406 ms] Start: Resolving Remote
[410 ms] Start: Check Docker is running
[410 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[803 ms] Server API version: 1.41
[804 ms] Start: Run: docker volume ls -q
[1346 ms] Start: Run: docker ps -q -a --filter label=vsch.local.repository=https://github.com/Microsoft/vscode-remote-try-go --filter label=vsch.local.repository.volume=vsc-remote-sample --filter label=vsch.local.repository.folder=vscode-remote-try-go
[1821 ms] Start: Run: docker inspect --type container 93ab877cb144
[2362 ms] Start: Starting container
[2362 ms] Start: Run: docker start 93ab877cb144fbfeb08936a64f46fff346b3e7e8ecdc4f7ee1256e12a823bf0a
[3355 ms] Start: Run: docker ps -q -a --filter label=vsch.local.repository=https://github.com/Microsoft/vscode-remote-try-go --filter label=vsch.local.repository.volume=vsc-remote-sample --filter label=vsch.local.repository.folder=vscode-remote-try-go --filter label=vsch.quality=stable
[3869 ms] Dev container not found.
[3876 ms] Error: Dev container not found.
        at bf (c:\Users\brmurtau\.vscode\extensions\ms-vscode-remote.remote-containers-0.163.0\dist\extension\extension.js:186:13667)
        at Tg (c:\Users\brmurtau\.vscode\extensions\ms-vscode-remote.remote-containers-0.163.0\dist\extension\extension.js:186:11279)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async pg (c:\Users\brmurtau\.vscode\extensions\ms-vscode-remote.remote-containers-0.163.0\dist\extension\extension.js:186:7020)
```

Unlike the Python container, however, I was able to get the most recent version of the Go container (i.e. it has the Codespaces readme updates). I selected "More Actions..." to view the log output that I've pasted above, then rebuilt the container, and then it connected successfully:

![image](https://user-images.githubusercontent.com/25310137/110161515-50e08f00-7da2-11eb-9703-57604e6b17b7.png)

_Originally posted by @bamurtaugh in https://github.com/microsoft/vscode-remote-release/issues/4606#issuecomment-791618358_

**Comment by chrmarti** [comment]
@bamurtaugh Do you remember if you turned this into a Docker Compose dev container and the switched back? (The only way I currently see this happening.)

**Comment by chrmarti** [comment]
Pushing the fix for that, this is a regression from the January milestone.

**Comment by bamurtaugh** [comment]
Thank you for looking into this and already pushing the fix! For completion's sake/in case it helps, I don't believe I turned this into a Docker Compose dev container and then switched back. I've just opened the Go repo via the Try a Sample command several times and tried running, debugging, and other miscellaneous code/changes.

**Comment by chrmarti** [comment]
Thanks, the fix is definitely good as it addresses a regression, but there might be more to the issue then. Keeping this closed for now, let me know if you see it again.
