### ISSUE TITLE
I can't connect to remote host through Remote-SSH extension

### ISSUE THREAD

**Issue by pashikk2008** [microsoft/vscode-remote-release#4631]
I can't connect to remote host through Remote-SSH extension.

- VSCode Version:
Версия: 1.54.1 (user setup)
Фиксация: f30a9b73e8ffc278e71575118b6bf568f04587c8
Дата: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
ОС: Windows_NT x64 10.0.18363

- Remote OS Version:
Ubuntu Server Edition

- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Install VSCode 1.54.1
2. Install Remote-SSH 0.65.1

While logging I get several prompts for a password then I get this output in console:

```
[08:33:48.026] Log Level: 2
[08:33:48.029] remote-ssh@0.65.1
[08:33:48.029] win32 x64
[08:33:48.030] SSH Resolver called for "ssh-remote+zontonline.beget.tech", attempt 1
[08:33:48.031] "remote.SSH.useLocalServer": false
[08:33:48.031] "remote.SSH.showLoginTerminal": false
[08:33:48.031] "remote.SSH.remotePlatform": {"tvp.altaseo":"linux"}
[08:33:48.031] "remote.SSH.sshPath": undefined
[08:33:48.031] "remote.SSH.sshConfigurationFile": undefined
[08:33:48.031] "remote.SSH.useFlock": true
[08:33:48.031] "remote.SSH.lockfilesInTmp": false
[08:33:48.032] "remote.SSH.localServerDownload": auto
[08:33:48.032] "remote.SSH.remoteServerListenOnSocket": false
[08:33:48.032] "remote.SSH.showLoginTerminal": false
[08:33:48.032] "remote.SSH.defaultExtensions": []
[08:33:48.032] SSH Resolver called for host: zontonline.beget.tech
[08:33:48.032] Setting up SSH remote "zontonline.beget.tech"
[08:33:48.057] Using commit id "f30a9b73e8ffc278e71575118b6bf568f04587c8" and quality "stable" for server
[08:33:48.060] Install and start server if needed
[08:33:49.279] Checking ssh with "ssh -V"
[08:33:49.303] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[08:33:49.307] Running script with connection command: ssh -T -D 21323 "zontonline.beget.tech" bash
[08:33:49.308] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[08:33:49.348] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\WINDOWS\System32\cmd.exe
[08:33:49.348] Got some output, clearing connection timeout
[08:33:49.357] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[08:33:49.543] > Welcome to LTD BeGet SSH Server 'bruma'
> 
[08:33:49.550] > zontonline_vsc@zontonline.beget.tech's password: 
[08:33:49.551] Showing password prompt
[08:33:51.133] Got password response
[08:33:51.134] "install" wrote data to terminal: "********"
[08:33:51.146] > 
> 
[08:33:53.940] > Permission denied, please try again.
> 
[08:33:53.948] > zontonline_vsc@zontonline.beget.tech's password: 
[08:33:53.948] Showing password prompt
[08:33:56.205] Got password response
[08:33:56.205] "install" wrote data to terminal: "********"
[08:33:56.217] > 
> 
[08:33:58.504] > Permission denied, please try again.
> 
[08:33:58.512] > zontonline_vsc@zontonline.beget.tech's password: 
[08:33:58.513] Showing password prompt
[08:33:59.477] Got password response
[08:33:59.477] "install" wrote data to terminal: "********"
[08:33:59.489] > 
> 
[08:34:00.853] > zontonline_vsc@zontonline.beget.tech: Permission denied (publickey,password).
> 
[08:34:00.862] > Попытка записи в несуществующий канал.
> 
[08:34:01.134] "install" terminal command done
[08:34:01.134] Install terminal quit with output: Попытка записи в несуществующий канал.
[08:34:01.134] Received install output: Попытка записи в несуществующий канал.
[08:34:01.134] Stopped parsing output early. Remaining text: Попытка записи в несуществующий канал.
[08:34:01.134] Failed to parse remote port from server output
[08:34:01.137] Resolver error: Error: 
	at Function.Create (c:\Users\1\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:64328)
	at Object.t.handleInstallOutput (c:\Users\1\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:63022)
	at q (c:\Users\1\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:296373)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\1\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:294221
	at async Object.t.withShowDetailsEvent (c:\Users\1\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:407055)
	at async Object.t.resolve (c:\Users\1\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:297912)
	at async c:\Users\1\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:127:110485
[08:34:01.139] ------
```

**Comment by roblourens** [comment]
`Permission denied (publickey,password)`

Please check that your password is correct

**Comment by pashikk2008** [comment]
> `Permission denied (publickey,password)`
> 
> Please check that your password is correct

Password is 100% correct. I can connect with these login&password through Putty normally.

**Comment by roblourens** [comment]
I don't understand... that goes on the host? Why does it help?
