### ISSUE TITLE
wget download failed for vscode-server-linux-x64.tar.gz

### ISSUE THREAD

**Issue by eugenelet** [microsoft/vscode-remote-release#4648]
- VSCode Version: 1.54.0
- Local OS Version: Windows 10.0.18363
- Remote OS Version: Linux (Ubuntu 20.04)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Connecting to remove server using remote SSH on VS Code
2. log returns:
`[12:21:16.400] > wget download failed
> failed: Connection timed out. failed: Connection timed out. failed: Connection t
> imed out. failed: Connection timed out. failed: Connection timed out. failed: Co
> nnection timed out. failed: Connection timed out. failed: Connection timed out. 
> failed: Connection timed out. failed: Connection timed out. failed: Connection t
> imed out. failed: Connection timed out. failed: Connection timed out. failed: Co
> nnection timed out. failed: Connection timed out.`

Then I check to see which file it's trying to download and it returns:

` wget https://vscode.cdn.azure.cn/stable/42e27fe5cdc58539dad9867970326a297eb8cacf/vscode-server-linux-x64.tar.gz`

I tried to manual download it on my server and it will be stuck at:

`Resolving vscode.cdn.azure.cn (vscode.cdn.azure.cn)... 112.90.58.219, 112.65.212.110, 112.65.212.105, ...
Connecting to vscode.cdn.azure.cn (vscode.cdn.azure.cn)|112.90.58.219|:443...`

Is the download server down right now? I has been working flawlessly before.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by penut85420** [comment]
Same issue, everything worked fine yesterday :(

**Comment by jjasoncool** [comment]
same issue, too.
Now I can't connect to server via ssh-remote.

**Comment by nicehorse06** [comment]
Same issue, can not connect WSL.

![](https://i.imgur.com/rHvMRW5.png)

**Comment by joewutaiwan** [comment]
Same issue maybe?

After upgrade this morning, every thing went to tragedy.

- VSCode Version: 1.54.1
- Local OS Version: Windows 10.0.18362
- Remote OS Version: Linux (Ubuntu 18.04.2 LTS)
- Remote Extension/Connection Type: SSH

```
Acquiring lock on /run/user/0/vscode-remote-lock.root.f30a9b73e8ffc278e71575118b6bf568f04587c8
Installing to /root/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8...
5451ceeb01f7%%1%%
Downloading with wget..

[16:18:54.758] > wget download failed
> failed: Connection timed out. failed: Connection timed out. failed: Connection timed out. No data received.
> printenv:
>     SSH_CONNECTION=10.17.56.14 60823 10.17.210.22 22
>     LANG=en_US.UTF-8
>     XDG_SESSION_ID=1724
>     USER=root
>     PWD=/root/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8
>     HOME=/root
>     SSH_CLIENT=10.17.56.14 60823 22
>     MAIL=/var/mail/root
>     SHELL=/bin/bash
>     SHLVL=2
>     VSCODE_AGENT_FOLDER=/root/.vscode-server
>     LOGNAME=root
>     XDG_RUNTIME_DIR=/run/user/0
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
>     _=/usr/bin/printenv
>     OLDPWD=/root
> Trigger local server download
> 5451ceeb01f7:trigger_server_download
> platform==linux==
> vscodeArch==x64==
> destFolder==/root/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8==
> 5451ceeb01f7:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /root/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/vscode-scp-done.flag and vscode-server.tar.gz to exist
[16:18:54.761] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/root/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8"}
[16:18:54.761] Downloading VS Code server locally...
[16:18:54.767] > 
> 
[16:19:25.205] Resolver error: Error: Running the contributed command: '_workbench.downloadResource' failed.
	at S._executeContributedCommand (c:\Users\joewu\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:103934)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\joewu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.58.0\out\extension.js:1:136553
	at async Object.t.downloadAndCopyToHost (c:\Users\joewu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.58.0\out\extension.js:1:136468)
	at async c:\Users\joewu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.58.0\out\extension.js:1:309647
	at async I (c:\Users\joewu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.58.0\out\extension.js:1:309865)
	at async c:\Users\joewu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.58.0\out\extension.js:1:308009
	at async Object.t.withShowDetailsEvent (c:\Users\joewu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.58.0\out\extension.js:1:402686)
	at async Object.t.resolve (c:\Users\joewu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.58.0\out\extension.js:1:311406)
	at async c:\Users\joewu\.vscode\extensions\ms-vscode-remote.remote-ssh-0.58.0\out\extension.js:127:110259
[16:19:25.211] ------
```

**Comment by eugenelet** [comment]
I'm seeing a pattern, is this bug only for Taiwan users?

**Comment by jay16213** [comment]
same issue here

VSCode Version: 1.54.1
Local OS Version: Windows 10.0.18363
Remote OS Version: Linux (Ubuntu 18.04.5 LTS)
Remote Extension/Connection Type: SSH

```
00423dfe6f8f: running
Acquiring lock on /home/jay/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/vscode-remote-lock.jay.f30a9b73e8ffc278e71575118b6bf568f04587c8
Installing to /home/jay/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8...
00423dfe6f8f%%1%%
Downloading with wget
wget download failed
failed: Connection timed out. failed: Connection timed out. failed: Connection timed out. failed: Connection timed out. failed: Connection timed out. failed: Connection timed out. failed: Connection timed out. failed: Connection timed out. failed: Connection timed out. failed: Connection timed out. failed: Connection timed out. failed: Connection timed out. failed: Connection timed out. failed: Connection timed out. failed: Connection timed out.
printenv:
    LC_MEASUREMENT=lzh_TW
    SSH_CONNECTION=192.168.56.2 5001 192.168.56.136 22
    LC_PAPER=lzh_TW
    LC_MONETARY=lzh_TW
    LANG=en_US.UTF-8
    OLDPWD=/home/jay
    LC_NAME=lzh_TW
    XDG_SESSION_ID=51
    USER=jay
    PWD=/home/jay/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8
    HOME=/home/jay
    SSH_CLIENT=192.168.56.2 5001 22
    LC_ADDRESS=lzh_TW
    LC_NUMERIC=lzh_TW
    MAIL=/var/mail/jay
    SHELL=/bin/zsh
    SHLVL=1
    LC_TELEPHONE=lzh_TW
    VSCODE_AGENT_FOLDER=/home/jay/.vscode-server
    LOGNAME=jay
    DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
    XDG_RUNTIME_DIR=/run/user/1000
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    LC_IDENTIFICATION=lzh_TW
    LC_TIME=lzh_TW
    _=/usr/bin/printenv
Trigger local server download
00423dfe6f8f:trigger_server_download
platform==linux==
vscodeArch==x64==
destFolder==/home/jay/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8==
00423dfe6f8f:trigger_server_download_end
Waiting for client to transfer server archive...
Waiting for /home/jay/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/vscode-scp-done.flag and vscode-server.tar.gz to exist
```

**Comment by joewutaiwan** [comment]
Even hard to downgrade vs code 

https://update.code.visualstudio.com/1.53.2/win32-x64/stable

The endpoint is in azure china, maybe have connections.

https://vscode.cdn.azure.cn/stable/622cb03f7e070a9670c94bae1a45d78d7181fbd4/VSCodeSetup-x64-1.53.2.exe

**Comment by ZeroRie** [comment]
Temporary plan: use China VPN

**Comment by extrovert7986** [comment]
following
https://stackoverflow.com/questions/56671520/how-can-i-install-vscode-server-in-linux-offline
update the vscode-server by hand will work
replace curl url by **https://az764295.vo.msecnd.net/stable/${commit}/vscode-server-linux-x64.tar.gz**

**Comment by nicehorse06** [comment]
Thank @extrovert7986, it words to me  💯

**Comment by roblourens** [comment]
Looking into this

**Comment by lolikung** [comment]
Same problem in Taiwan user 😢 
```text
$ wget https://update.code.visualstudio.com/commit:f30a9b73e8ffc278e71575118b6bf568f04587c8/server-linux-x64/stable
Connecting to update.code.visualstudio.com (51.144.164.215:443)
Connecting to vscode.cdn.azure.cn (119.6.229.138:443)
wget: can't connect to remote host (119.6.229.138): Connection refused
```

**Comment by joaomoreno** [comment]
We just deployed a new update which redirects Taiwan users to the main Azure instance. Can you confirm whether this is working now for you? Thanks.
