### ISSUE TITLE
Connection timeout (SSH)

### ISSUE THREAD

**Issue by pczarn** [microsoft/vscode-remote-release#4664]
- VSCode Version: 1.54.1 & 1.54.2
- Local OS Version: Linux (Arch)
- Remote OS Version: Linux (CentOS)
- Remote Extension/Connection Type: **SSH**

Steps to Reproduce:

1. Connect to remote host

I do not know what changed between working state and broken state, from one day to the next, but I believe nothing changed.

Does this issue occur when you try this locally?: Unknown
Does this issue occur when you try this locally and all extensions are disabled?: **Yes**

```
[09:37:51.954] Log Level: 2
[09:37:51.956] remote-ssh@0.65.1
[09:37:51.957] linux x64
[09:37:51.958] SSH Resolver called for "ssh-remote+example.com", attempt 1
[09:37:51.958] "remote.SSH.useLocalServer": true
[09:37:51.958] "remote.SSH.sshPath": undefined
[09:37:51.958] "remote.SSH.sshConfigurationFile": undefined
[09:37:51.959] "remote.SSH.useFlock": true
[09:37:51.959] "remote.SSH.lockfilesInTmp": false
[09:37:51.959] "remote.SSH.localServerDownload": auto
[09:37:51.959] "remote.SSH.remoteServerListenOnSocket": false
[09:37:51.959] "remote.SSH.showLoginTerminal": false
[09:37:51.959] "remote.SSH.defaultExtensions": []
[09:37:51.960] SSH Resolver called for host: example.com
[09:37:51.960] Setting up SSH remote "example.com"
[09:37:51.963] Acquiring local install lock: /tmp/vscode-remote-ssh-example.com-install.lock
[09:37:51.969] Looking for existing server data file at /home/piotr/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-example.com-fd6f3bce6709b121a895d042d343d71f317d74e7-0.65.1/data.json
[09:37:51.970] Using commit id "fd6f3bce6709b121a895d042d343d71f317d74e7" and quality "stable" for server
[09:37:51.973] Install and start server if needed
[09:37:51.976] Checking ssh with "ssh -V"
[09:37:51.985] > OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020

[09:37:51.989] askpass server listening on /run/user/1000/vscode-ssh-askpass-74e8d6746e554fc96c42dd42bbe506678d3d585b.sock
[09:37:51.990] Spawning local server with {"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-a4f74cdeae2b21c8c9ac5390301ba701da4eb59b.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","37787","-o","ConnectTimeout=45","example.com"],"dataFilePath":"/home/piotr/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-example.com-fd6f3bce6709b121a895d042d343d71f317d74e7-0.65.1/data.json"}
[09:37:51.990] Local server env: {"DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/piotr/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/opt/visual-studio-code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/piotr/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-74e8d6746e554fc96c42dd42bbe506678d3d585b.sock"}
[09:37:51.996] Spawned 19138
[09:37:52.120] > local-server> Spawned ssh: 19147
[09:37:52.124] stderr> OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020
[09:37:56.760] stderr> debug1: Server host key: ecdsa-sha2-nistp256 ...
[09:38:39.001] Terminating local server
[09:38:39.032] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/home/piotr/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:64454)
	at Timeout._onTimeout (/home/piotr/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:263987)
	at listOnTimeout (internal/timers.js:549:17)
	at processTimers (internal/timers.js:492:7)
[09:38:39.035] Local server exit: 15
[09:38:39.040] ------
```

**Comment by pczarn** [comment]
I did the same connection with another mobile internet provider. It works. I believe you should be notified of a flaky connection, because I was confused as hell as to what was happening. The connection was decent for web browsing too, so nothing seemed off.

**Comment by roblourens** [comment]
Not much to say about this, we start `ssh` and it isn't able to open a connection. Does it work from an external terminal?

**Comment by marcuskober** [comment]
I have the same problem. 

- VSCode Version: 1.54.3
- Local OS Version: Mac
- Remote OS Version: Linux (Ubuntu)
- Remote Extension/Connection Type: SSH

`[09:21:53.487] Log Level: 2
[09:21:53.489] remote-ssh@0.65.1
[09:21:53.489] darwin x64
[09:21:53.490] SSH Resolver called for "ssh-remote+193.53.250.208", attempt 1
[09:21:53.490] "remote.SSH.useLocalServer": true
[09:21:53.490] "remote.SSH.sshPath": undefined
[09:21:53.490] "remote.SSH.sshConfigurationFile": undefined
[09:21:53.490] "remote.SSH.useFlock": true
[09:21:53.491] "remote.SSH.lockfilesInTmp": true
[09:21:53.491] "remote.SSH.localServerDownload": auto
[09:21:53.491] "remote.SSH.remoteServerListenOnSocket": false
[09:21:53.491] "remote.SSH.showLoginTerminal": false
[09:21:53.491] "remote.SSH.defaultExtensions": []
[09:21:53.491] SSH Resolver called for host: 193.53.250.208
[09:21:53.491] Setting up SSH remote "193.53.250.208"
[09:21:53.493] Acquiring local install lock: /var/folders/tt/t7q7m2rx7yx3j_tkzr7jvx0m0000gn/T/vscode-remote-ssh-193.53.250.208-install.lock
[09:21:53.501] Looking for existing server data file at /Users/marcuskober/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-193.53.250.208-2b9aebd5354a3629c3aba0a5f5df49f43d6689f8-0.65.1/data.json
[09:21:53.502] Using commit id "2b9aebd5354a3629c3aba0a5f5df49f43d6689f8" and quality "stable" for server
[09:21:53.504] Install and start server if needed
[09:21:53.506] Checking ssh with "ssh -V"
[09:21:53.511] > OpenSSH_8.1p1, LibreSSL 2.7.3

[09:21:53.514] askpass server listening on /var/folders/tt/t7q7m2rx7yx3j_tkzr7jvx0m0000gn/T/vscode-ssh-askpass-52909ab9da8dc02458cca60d68122610b46b7002.sock
[09:21:53.515] Spawning local server with {"ipcHandlePath":"/var/folders/tt/t7q7m2rx7yx3j_tkzr7jvx0m0000gn/T/vscode-ssh-askpass-0624e7003f2b1eef889a7d0c8ee7bfac44b6fc12.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","59946","-o","ConnectTimeout=20","193.53.250.208"],"dataFilePath":"/Users/marcuskober/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-193.53.250.208-2b9aebd5354a3629c3aba0a5f5df49f43d6689f8-0.65.1/data.json"}
[09:21:53.515] Local server env: {"DISPLAY":"/private/tmp/com.apple.launchd.cW1f8x1eWO/org.macosforge.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/marcuskober/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/marcuskober/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/tt/t7q7m2rx7yx3j_tkzr7jvx0m0000gn/T/vscode-ssh-askpass-52909ab9da8dc02458cca60d68122610b46b7002.sock"}
[09:21:53.516] Spawned 61102
[09:21:53.620] > local-server> Spawned ssh: 61108
[09:21:53.624] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[09:21:53.718] stderr> debug1: Server host key: [REMOVED]
[09:21:53.926] Got askpass request: {"request":"[REMOVED]'s password:"}
[09:21:53.927] Showing password prompt
[09:21:53.927] Listening for interwindow password on /var/folders/tt/t7q7m2rx7yx3j_tkzr7jvx0m0000gn/T/vscode-ssh-askpass-12d3a96f95db209f302602651f0a83e5ded609a0.sock
[09:21:53.927] Writing password prompt to globalState
[09:21:59.560] Got password response
[09:21:59.560] Interactor gave response: ************
[09:21:59.560] Cleaning up other-window auth server
[09:21:59.634] stderr> Authenticated to [REMOVED].
[09:21:59.706] > ready: 027d190d2697
[09:21:59.740] stderr> -bash: Zeile 2: uname: command not found.
[09:22:21.567] Terminating local server
[09:22:21.571] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/marcuskober/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:64454)
	at Timeout._onTimeout (/Users/marcuskober/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:263987)
	at listOnTimeout (internal/timers.js:549:17)
	at processTimers (internal/timers.js:492:7)
[09:22:21.573] Local server exit: 15
[09:22:21.575] ------`

From an external terminal everything works normal.

I have two assumptions why it isn't working:

- the root folder of the ssh account is write protected
- the command uname is not found

Is this the problem? If yes, what could I do to connect?

**Comment by roblourens** [comment]
> uname: command not found.

Not the same issue. Please open your own issue
