### ISSUE TITLE
could not install python and pylance extension in remote machine

### ISSUE THREAD

**Issue by ROGERDJQ** [microsoft/vscode-remote-release#4676]
- VSCode Version:1.54.3
- Local OS Version:  window10
- Remote OS Version: ubuntu 16.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
0. A totally new local machine with windows 10; and remote ubuntu which winstall these extensions before; 
1. Install vscode in local windows machine and use ssh extension to get access to remote ubuntu;
2. try to install python and pylance extension;
3. get error "Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.3'."

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

<Some information>
I notice that this issue has been proposed here(https://github.com/microsoft/vscode/issues/117986). Yet after I get a totally new machine and install the newest vscode, the bug remains, which makes me very disappointed.

**Comment by ROGERDJQ** [comment]
Since my local machine is a brand new one, I doubt that the issue happens in the remote machine. Yet I do not know how to fix it.

**Comment by ROGERDJQ** [comment]
[renderer1] [error] Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.3'.: Error: Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.3'.
    at /remote-home/jqdai/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/out/vs/server/remoteExtensionHostAgent.js:108:97447
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by ROGERDJQ** [comment]
I have closed this issue as it should be a  vscode issue.
