### ISSUE TITLE
Could not establish a connection to "alias" get bad result from install script

### ISSUE THREAD

**Issue by reaCodes** [microsoft/vscode-remote-release#4701]
- VSCode Version:1.54.3
- Local OS Version:windows 10.19042
- Remote OS Version:ubuntu 16.04
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/13817254/111785093-20970580-88f7-11eb-9cc2-5b1a4b45ca9e.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by roblourens** [comment]
`ssh` is starting and immediately exiting. Can you use ssh from an external terminal?

**Comment by reaCodes** [comment]
@roblourens Yes, I can use ssh from an external terminal
![image](https://user-images.githubusercontent.com/13817254/111854756-ee6bbf00-895b-11eb-8bef-c26d0c4e83b9.png)

**Comment by roblourens** [comment]
Looks like you're using git ssh there. VS Code is using whatever ssh you have on your path, possibly windows openSSH. Does using that in an external terminal work? If not you can set the setting `remote.SSH.path` to your git ssh install.

**Comment by reaCodes** [comment]
In Powershell, It's the same thing

![image](https://user-images.githubusercontent.com/13817254/111928701-58689d80-8aef-11eb-8efb-d75e14fd8f90.png)

**Comment by roblourens** [comment]
In the vscode example you are using some host called "alias"?

What if you run something like

`echo uname | ssh alias`

**Comment by reaCodes** [comment]
> In the vscode example you are using some host called "alias"?
> 
> What if you run something like
> 
> `echo uname | ssh -T alias bash`
> 
> Also, in vscode try setting
> 
> `"remote.SSH.useLocalServer": true`
> 
> just to see if there's a difference

I execute `echo uname | ssh -T alias bash` in git bash:

![image](https://user-images.githubusercontent.com/13817254/112427079-fbc9e480-8d73-11eb-9d98-50e0f8db462f.png)

But I don't know why I do this. Please tell me the mean of this command.

Then,
In vscode's setting, I can't find `"remote.SSH.useLocalServer": true`

**Comment by reaCodes** [comment]
I uninstall vscode and cleanup residual file,  then reinstall vscode, its remote development feature still does not work.

**Comment by roblourens** [comment]
Can you try setting `"remote.SSH.useLocalServer": true` in your settings.json file? (the UI will show it enabled by default on windows, needs to be set in JSON)

**Comment by reaCodes** [comment]
> Can you try setting `"remote.SSH.useLocalServer": true` in your settings.json file? (the UI will show it enabled by default on windows, needs to be set in JSON)

I've tried, and it's still not working. Is there a faster way for us to communicate further?

**Comment by roblourens** [comment]
Can you share the log from running with that option?

**Comment by reaCodes** [comment]
[16:10:59.968] Log Level: 2
[16:10:59.968] remote-ssh@0.65.1
[16:10:59.968] win32 x64
[16:10:59.968] SSH Resolver called for "ssh-remote+tencent", attempt 1
[16:10:59.968] "remote.SSH.useLocalServer": true
[16:10:59.968] "remote.SSH.sshPath": undefined
[16:10:59.968] "remote.SSH.sshConfigurationFile": undefined
[16:10:59.968] "remote.SSH.useFlock": true
[16:10:59.968] "remote.SSH.lockfilesInTmp": false
[16:10:59.968] "remote.SSH.localServerDownload": auto
[16:10:59.968] "remote.SSH.remoteServerListenOnSocket": false
[16:10:59.968] "remote.SSH.showLoginTerminal": true
[16:10:59.968] "remote.SSH.defaultExtensions": []
[16:10:59.968] SSH Resolver called for host: tencent
[16:10:59.968] Setting up SSH remote "tencent"
[16:10:59.987] Acquiring local install lock: C:\Users\ZHONGJ~1\AppData\Local\Temp\vscode-remote-ssh-tencent-install.lock
[16:11:00.044] Looking for existing server data file at c:\Users\zhongjingwei\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-ssh\vscode-ssh-host-tencent-2b9aebd5354a3629c3aba0a5f5df49f43d6689f8-0.65.1\data.json
[16:11:00.044] Using commit id "2b9aebd5354a3629c3aba0a5f5df49f43d6689f8" and quality "stable" for server
[16:11:00.044] Install and start server if needed
[16:11:00.079] Checking ssh with "ssh -V"
[16:11:00.127] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[16:11:00.127] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[16:11:00.169] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[16:11:00.169] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[16:11:00.211] > OpenSSH_8.5p1, OpenSSL 1.1.1j  16 Feb 2021

[16:11:00.211] Using SSH config file "C:\Users\zhongjingwei\.ssh\config"
[16:11:00.211] askpass server listening on \\.\pipe\vscode-ssh-askpass-5d8a173dd29334985a4d8147a7c84bef2a48abe1-sock
[16:11:00.211] Spawning local server with {"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-1ad24ae013d149448c34dd9c89e14e218b922c1f-sock","sshCommand":"C:\\Program Files\\Git\\usr\\bin\\ssh.exe","sshArgs":["-v","-T","-D","49530","-F","C:\\Users\\zhongjingwei\\.ssh\\config","tencent"],"dataFilePath":"c:\\Users\\zhongjingwei\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-vscode-remote.remote-ssh\\vscode-ssh-host-tencent-2b9aebd5354a3629c3aba0a5f5df49f43d6689f8-0.65.1\\data.json"}
[16:11:00.211] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"c:\\Users\\zhongjingwei\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.65.1\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"C:\\Program Files\\Microsoft VS Code\\Code.exe","VSCODE_SSH_ASKPASS_MAIN":"c:\\Users\\zhongjingwei\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.65.1\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-5d8a173dd29334985a4d8147a7c84bef2a48abe1-sock"}
[16:11:00.252] Spawned 7812
[16:11:00.371] > local-server> Spawned ssh: 7864
[16:11:00.395] stderr> OpenSSH_8.5p1, OpenSSL 1.1.1j  16 Feb 2021
[16:11:00.487] stderr> debug1: Server host key: ssh-ed25519 SHA256:HbyEvEcKQ28odmAdRQT9sGHbc3xCS39kBHEASSKThA8
[16:11:00.523] stderr> Host key verification failed.
[16:11:00.526] > local-server> ssh child died, shutting down
[16:11:00.533] Local server exit: 0
[16:11:00.534] Received install output: OpenSSH_8.5p1, OpenSSL 1.1.1j  16 Feb 2021
debug1: Server host key: ssh-ed25519 SHA256:HbyEvEcKQ28odmAdRQT9sGHbc3xCS39kBHEASSKThA8
Host key verification failed.

[16:11:00.534] Stopped parsing output early. Remaining text: OpenSSH_8.5p1, OpenSSL 1.1.1j  16 Feb 2021debug1: Server host key: ssh-ed25519 SHA256:HbyEvEcKQ28odmAdRQT9sGHbc3xCS39kBHEASSKThA8Host key verification failed.
[16:11:00.534] Failed to parse remote port from server output
[16:11:00.537] Resolver error: Error: 
	at Function.Create (c:\Users\zhongjingwei\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:64328)
	at Object.t.handleInstallOutput (c:\Users\zhongjingwei\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:63022)
	at Object.t.tryInstallWithLocalServer (c:\Users\zhongjingwei\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:388682)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\zhongjingwei\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:293749
	at async Object.t.withShowDetailsEvent (c:\Users\zhongjingwei\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:407055)
	at async c:\Users\zhongjingwei\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:387177
	at async N (c:\Users\zhongjingwei\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:383945)
	at async Object.t.resolveWithLocalServer (c:\Users\zhongjingwei\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:386804)
	at async Object.t.resolve (c:\Users\zhongjingwei\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:297790)
	at async c:\Users\zhongjingwei\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:127:110485
[16:11:00.537] ------

**Comment by reaCodes** [comment]
I tried to replace system SSH with git SSH, but it still couldn't work

**Comment by roblourens** [comment]
> Host key verification failed.

Not sure what you changed but now it doesn't like the host's key. Deleting your `~/.ssh/known_hosts` file might fix that.

**Comment by alvis** [comment]
I know it's not helpful. But I have the same issue. :/
