### ISSUE TITLE
division by 0 (error token is "N/1000000") on Yocto

### ISSUE THREAD

**Issue by przemoch1** [microsoft/vscode-remote-release#4706]
Hello, 

I'm trying to configure a remote connection between my PC and Raspberry Pi that works on Yocto custom OS. I'm facing an issue while installing VS Code server. Here is output:

```
[11:47:39.010] Log Level: 2
[11:47:39.081] remote-ssh@0.65.1
[11:47:39.081] linux x64
[11:47:39.095] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a223139322e3136382e312e313431222c2275736572223a22726f6f74227d", attempt 1
[11:47:39.104] "remote.SSH.useLocalServer": true
[11:47:39.105] "remote.SSH.sshPath": undefined
[11:47:39.106] "remote.SSH.sshConfigurationFile": undefined
[11:47:39.107] "remote.SSH.useFlock": true
[11:47:39.107] "remote.SSH.lockfilesInTmp": false
[11:47:39.108] "remote.SSH.localServerDownload": auto
[11:47:39.108] "remote.SSH.remoteServerListenOnSocket": false
[11:47:39.109] "remote.SSH.showLoginTerminal": false
[11:47:39.109] "remote.SSH.defaultExtensions": []
[11:47:39.110] SSH Resolver called for host: root@192.168.1.141
[11:47:39.110] Setting up SSH remote "192.168.1.141"
[11:47:39.116] Acquiring local install lock: /tmp/vscode-remote-ssh-root@192.168.1.141-install.lock
[11:47:39.152] Looking for existing server data file at /home/przemoch/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-root@192.168.1.141-f30a9b73e8ffc278e71575118b6bf568f04587c8-0.65.1/data.json
[11:47:39.156] Using commit id "f30a9b73e8ffc278e71575118b6bf568f04587c8" and quality "stable" for server
[11:47:39.228] Install and start server if needed
[11:47:39.267] Checking ssh with "ssh -V"
[11:47:39.371] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020

[11:47:39.387] askpass server listening on /run/user/1000/vscode-ssh-askpass-9b194aa3bbbce3250969edbbb5f6e25d4061e306.sock
[11:47:39.387] Spawning local server with {"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-ee8df2b361457d5daf541375aeb0f6a7d1cb43a7.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","37169","-o","ConnectTimeout=15","root@192.168.1.141"],"dataFilePath":"/home/przemoch/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-root@192.168.1.141-f30a9b73e8ffc278e71575118b6bf568f04587c8-0.65.1/data.json"}
[11:47:39.388] Local server env: {"DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/przemoch/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/przemoch/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-9b194aa3bbbce3250969edbbb5f6e25d4061e306.sock"}
[11:47:39.457] Spawned 51676
[11:47:39.969] Server delay-shutdown request failed: connect ENOENT /run/user/1000/vscode-ssh-askpass-ee8df2b361457d5daf541375aeb0f6a7d1cb43a7.sock
[11:47:40.116] > local-server> Spawned ssh: 51685
[11:47:40.130] stderr> OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020
[11:47:40.328] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:Z0U7njEjR4niNRu4hvqvGyUe17uPhJ/DZYZXjTtxAFI
[11:47:40.577] stderr> Authenticated to 192.168.1.141 ([192.168.1.141]:22).
[11:47:40.644] > ready: 50053bf69844
[11:47:40.653] > Linux 5.4.72-v7 #1 SMP Mon Oct 19 11:12:20 UTC 2020
[11:47:40.654] Platform: linux
[11:47:40.756] > 50053bf69844: running
[11:47:41.378] stderr> main: line 176: ldd: command not found
[11:47:41.379] stderr> main: line 55: 1616237261%N/1000000: division by 0 (error token is "N/1000000")
[11:47:41.379] > Missing GLIBC >= 2.17!
> Found version 
> 50053bf69844$$1$$
> Acquiring lock on /root/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/vscode-remote-lock.root.f30a9b73e8ffc278e71575118b6bf568f04587c8
> Installing to /root/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8...
> 50053bf69844%%1%%
[11:47:41.388] > printenv:
[11:47:41.398] stderr> main: line 78: printenv: command not found
[11:47:41.399] > Neither wget nor curl is installed
> Trigger local server download
> 50053bf69844:trigger_server_download
> platform==linux==
> vscodeArch==armhf==
> destFolder==/root/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8==
> 50053bf69844:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /root/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/vscode-scp-done.flag and vscode-server.tar.gz to exist
>  
[11:47:41.400] Got request to download on client for {"platform":"linux","arch":"armhf","destFolder":"/root/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8"}
[11:47:41.400] Downloading VS Code server locally...
[11:47:46.091] Downloaded VS Code server to /tmp/19b753f7-5e73-4302-ac43-8383f4db8f52
[11:47:46.092] Renamed VS Code server to /tmp/vscode_server_1616237266091/vscode-server.tar.gz
[11:47:46.096] Checking ssh with "ssh -V"
[11:47:46.113] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020

[11:47:46.115] Testing scp with "scp"
[11:47:46.137] scp exited with code: 1
[11:47:46.138] Got stderr from scp: usage: scp [-346BCpqrTv] [-c cipher] [-F ssh_config] [-i identity_file]
            [-J destination] [-l limit] [-o ssh_option] [-P port]
            [-S program] source ... target
[11:47:46.140] Copying file to remote with scp -o ConnectTimeout=15 'vscode-server.tar.gz' 'vscode-scp-done.flag' 'root@192.168.1.141':'/root/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8'
[11:47:46.142] Using cwd: file:///tmp/vscode_server_1616237266091
[11:47:46.743] > vscode-server.tar.gz                            0%    0     0.0KB/s   --:-- ETA
[11:47:47.752] > vscode-server.tar.gz                           22% 6320KB   6.0MB/s   00:03 ETA
[11:47:48.763] > vscode-server.tar.gz                           33% 9504KB   5.7MB/s   00:03 ETA
[11:47:49.888] > vscode-server.tar.gz                           51%   14MB   5.6MB/s   00:02 ETA
[11:47:50.859] > vscode-server.tar.gz                           73%   20MB   5.7MB/s   00:01 ETA
[11:47:51.780] > vscode-server.tar.gz                           86%   24MB   5.5MB/s   00:00 ETA
[11:47:52.465] > vscode-server.tar.gz                          100%   28MB   4.8MB/s   00:05    
> vscode-scp-done.flag                            0%    0     0.0KB/s   --:-- ETAvscode-scp-done.flag                          100%    9     3.9KB/s   00:00    
[11:47:52.718] "Copy server to host" terminal command done
[11:47:53.421] > Found flag and server on host
[11:47:53.436] stderr> main: line 55: 1616237273%N/1000000: division by 0 (error token is "N/1000000")
[11:47:53.439] > 50053bf69844%%2%%
> tar --version:
[11:47:53.443] stderr> tar: unrecognized option '--version'
[11:47:53.445] stderr> BusyBox v1.31.1 ()
[11:47:53.445] stderr>  multi-call binary.
[11:47:53.446] stderr> 
[11:47:53.446] stderr> Usage: tar 
[11:47:53.447] stderr> c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [FILE]...
[11:47:53.447] stderr> 
[11:48:00.221] stderr> main: line 55: 1616237280%N/1000000: division by 0 (error token is "N/1000000")
[11:48:00.221] stderr> main: line 63: - : syntax error: operand expected (error token is "- ")
[11:48:00.221] > ERROR: tar exited with non-0 exit code: 0
> Already attempted local download, failing
> 50053bf69844: start
> exitCode==37==
> listeningOn====
> osReleaseId==poky==
> arch==armv7l==
> tmpDir==/tmp==
[11:48:00.281] > platform==linux==
> unpackResult==error==
> didLocalDownload==1==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 50053bf69844: end
[11:48:00.282] Received install output: 
exitCode==37==
listeningOn====
osReleaseId==poky==
arch==armv7l==
tmpDir==/tmp==platform==linux==
unpackResult==error==
didLocalDownload==1==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[11:48:00.283] Terminating local server
[11:48:00.320] Resolver error: Error: Failed to install the VS Code Server
	at Function.ServerInstallError (/home/przemoch/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:64262)
	at c (/home/przemoch/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:59161)
	at Object.t.handleInstallOutput (/home/przemoch/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:63055)
	at Object.t.tryInstallWithLocalServer (/home/przemoch/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:388682)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async /home/przemoch/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:293749
	at async Object.t.withShowDetailsEvent (/home/przemoch/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:407055)
	at async /home/przemoch/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:387177
	at async N (/home/przemoch/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:383945)
	at async Object.t.resolveWithLocalServer (/home/przemoch/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:386804)
	at async Object.t.resolve (/home/przemoch/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:297790)
	at async /home/przemoch/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:127:110485
[11:48:00.332] Local server exit: 15
[11:48:00.357] ------
```

Do you have any advice, how to resolve it?

**Comment by bamurtaugh** [comment]
This looks like https://github.com/microsoft/vscode-remote-release/issues/3054. The log mentions, `Neither wget nor curl is installed`. Can you try `sudo apt-get install curl`?

**Comment by przemoch1** [comment]
I have both curl and wget. 
```
% curl --version
curl 7.69.1 (aarch64-poky-linux-gnu) libcurl/7.69.1 GnuTLS/3.6.14 zlib/1.2.11 libidn2/2.3.0
```
```
wget --version
wget: unrecognized option '--version'
BusyBox v1.31.1 () multi-call binary.
```
Don't know why `--version` does not work here :smile:

**Comment by bamurtaugh** [comment]
> Don't know why --version does not work here

Based on some quick investigation, looks like https://github.com/haskell/cabal/issues/6126 or https://github.com/nvm-sh/nvm/issues/2135 could be the type of issue. Specifically, there's a "pseudo wget provided by busybox"

I'm not sure if something like this could help? https://github.com/haskell/cabal/issues/6126#issuecomment-649520157 https://github.com/nvm-sh/nvm/issues/2135#issuecomment-565735120
