### ISSUE TITLE
Unable to connect to remote - Bad file descriptor

### ISSUE THREAD

**Issue by chitranshu** [microsoft/vscode-remote-release#4726]
- VSCode Version: 1.54.3
- Local OS Version: MacOS Big Sur **Version: 11.2.3**
- Remote OS Version:  Ubuntu 18.04.5
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Go to Remote Explorer
2. Right click on a remote server 
3. Connect to Host 

**Logs:**
```
[13:36:04.360] Log Level: 2
[13:36:04.362] remote-ssh@0.65.1
[13:36:04.363] darwin x64
[13:36:04.363] SSH Resolver called for "ssh-remote+chitranshu-devbox", attempt 1
[13:36:04.364] "remote.SSH.useLocalServer": true
[13:36:04.364] "remote.SSH.sshPath": undefined
[13:36:04.364] "remote.SSH.sshConfigurationFile": undefined
[13:36:04.364] "remote.SSH.useFlock": true
[13:36:04.364] "remote.SSH.lockfilesInTmp": false
[13:36:04.365] "remote.SSH.localServerDownload": auto
[13:36:04.365] "remote.SSH.remoteServerListenOnSocket": false
[13:36:04.365] "remote.SSH.showLoginTerminal": true
[13:36:04.365] "remote.SSH.defaultExtensions": []
[13:36:04.365] SSH Resolver called for host: chitranshu-devbox
[13:36:04.365] Setting up SSH remote "chitranshu-devbox"
[13:36:04.368] Acquiring local install lock: /var/folders/g2/g_vrmvgx7rg3l_kbvw5vxvw80000h5/T/vscode-remote-ssh-chitranshu-devbox-install.lock
[13:36:04.377] Looking for existing server data file at /Users/casthana/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-chitranshu-devbox-2b9aebd5354a3629c3aba0a5f5df49f43d6689f8-0.65.1/data.json
[13:36:04.378] Using commit id "2b9aebd5354a3629c3aba0a5f5df49f43d6689f8" and quality "stable" for server
[13:36:04.381] Install and start server if needed
[13:36:04.386] Checking ssh with "ssh -V"
[13:36:04.399] > OpenSSH_8.1p1, LibreSSL 2.7.3

[13:36:04.407] askpass server listening on /var/folders/g2/g_vrmvgx7rg3l_kbvw5vxvw80000h5/T/vscode-ssh-askpass-2f18bd9947bd8355c8817c0892362bd2f99c3770.sock
[13:36:04.410] Spawning local server with {"ipcHandlePath":"/var/folders/g2/g_vrmvgx7rg3l_kbvw5vxvw80000h5/T/vscode-ssh-askpass-9d5d08d866b6d49e313d4b8884a7fe78bb8ffa2f.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","53096","-o","ConnectTimeout=15","chitranshu-devbox"],"dataFilePath":"/Users/casthana/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-chitranshu-devbox-2b9aebd5354a3629c3aba0a5f5df49f43d6689f8-0.65.1/data.json"}
[13:36:04.410] Local server env: {"DISPLAY":"/private/tmp/com.apple.launchd.sYf9bhb5sT/org.macports:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/casthana/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/casthana/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/g2/g_vrmvgx7rg3l_kbvw5vxvw80000h5/T/vscode-ssh-askpass-2f18bd9947bd8355c8817c0892362bd2f99c3770.sock"}
[13:36:04.413] Spawned 28869
[13:36:04.665] > local-server> Spawned ssh: 28873
[13:36:04.669] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[13:36:05.236] stderr> ssh: connect to host 10.45.120.42 port 22: Bad file descriptor
[13:36:05.238] > local-server> ssh child died, shutting down
[13:36:05.244] Local server exit: 0
[13:36:05.244] Received install output: OpenSSH_8.1p1, LibreSSL 2.7.3
ssh: connect to host 10.45.120.42 port 22: Bad file descriptor

[13:36:05.245] Stopped parsing output early. Remaining text: OpenSSH_8.1p1, LibreSSL 2.7.3ssh: connect to host 10.45.120.42 port 22: Bad file descriptor
[13:36:05.245] Failed to parse remote port from server output
[13:36:05.250] Resolver error: Error: 
	at Function.Create (/Users/casthana/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:64328)
	at Object.t.handleInstallOutput (/Users/casthana/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:63022)
	at Object.t.tryInstallWithLocalServer (/Users/casthana/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:388682)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async /Users/casthana/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:293749
	at async Object.t.withShowDetailsEvent (/Users/casthana/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:407055)
	at async /Users/casthana/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:387177
	at async N (/Users/casthana/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:383945)
	at async Object.t.resolveWithLocalServer (/Users/casthana/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:386804)
	at async Object.t.resolve (/Users/casthana/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:297790)
	at async /Users/casthana/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:127:110485
[13:36:05.255] ------
```

<img width="262" alt="Screenshot 2021-03-23 at 1 53 27 PM" src="https://user-images.githubusercontent.com/4478575/112115442-34848500-8bdf-11eb-82a5-5b60e8326e6e.png">

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

> **Note:** I am able to connect to my remote machine through my terminal. I used zsh as well as bash to connect to remote and both were success.

**Comment by chitranshu** [comment]
Logs of connecting to same machine through terminal

```
casthana@C02TK1MTHF1R ~ % ssh -v chitranshu-devbox
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/casthana/.ssh/config
debug1: /Users/casthana/.ssh/config line 11: Applying options for chitranshu-devbox
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 47: Applying options for *
debug1: Connecting to 10.45.120.42 [10.45.120.42] port 22.
debug1: Connection established.
debug1: identity file /Users/casthana/.ssh/id_rsa type 0
debug1: identity file /Users/casthana/.ssh/id_rsa-cert type -1
debug1: identity file /Users/casthana/.ssh/id_dsa type -1
debug1: identity file /Users/casthana/.ssh/id_dsa-cert type -1
debug1: identity file /Users/casthana/.ssh/id_ecdsa type -1
debug1: identity file /Users/casthana/.ssh/id_ecdsa-cert type -1
debug1: identity file /Users/casthana/.ssh/id_ed25519 type -1
debug1: identity file /Users/casthana/.ssh/id_ed25519-cert type -1
debug1: identity file /Users/casthana/.ssh/id_xmss type -1
debug1: identity file /Users/casthana/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
debug1: match: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3 pat OpenSSH_7.0*,OpenSSH_7.1*,OpenSSH_7.2*,OpenSSH_7.3*,OpenSSH_7.4*,OpenSSH_7.5*,OpenSSH_7.6*,OpenSSH_7.7* compat 0x04000002
debug1: Authenticating to 10.45.120.42:22 as 'appsadm'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:4cpLjOCBBQdPuwT6Bi5qrg3wbIHEEmsKE2rMCg/P9rg
debug1: Host '10.45.120.42' is known and matches the ECDSA host key.
debug1: Found key in /Users/casthana/.ssh/known_hosts:32
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /Users/casthana/.ssh/id_rsa RSA SHA256:q5WGwV3jaDe11ozEbEir25S1zMJhgJm7svaRyGXShN0
debug1: Will attempt key: /Users/casthana/.ssh/id_dsa 
debug1: Will attempt key: /Users/casthana/.ssh/id_ecdsa 
debug1: Will attempt key: /Users/casthana/.ssh/id_ed25519 
debug1: Will attempt key: /Users/casthana/.ssh/id_xmss 
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering public key: /Users/casthana/.ssh/id_rsa RSA SHA256:q5WGwV3jaDe11ozEbEir25S1zMJhgJm7svaRyGXShN0
debug1: Authentications that can continue: publickey,password
debug1: Trying private key: /Users/casthana/.ssh/id_dsa
debug1: Trying private key: /Users/casthana/.ssh/id_ecdsa
debug1: Trying private key: /Users/casthana/.ssh/id_ed25519
debug1: Trying private key: /Users/casthana/.ssh/id_xmss
debug1: Next authentication method: password
appsadm@10.45.120.42's password: 
debug1: Authentication succeeded (password).
Authenticated to 10.45.120.42 ([10.45.120.42]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Sending environment.
debug1: Sending env LANG = en_GB.UTF-8
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-134-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Tue Mar 23 02:30:39 MDT 2021

  System load:                    0.0
  Usage of /:                     11.8% of 73.22GB
  Memory usage:                   11%
  Swap usage:                     2%
  Processes:                      175
  Users logged in:                1
  IP address for ens160:          10.45.120.42
  IP address for docker0:         172.17.0.1
  IP address for br-1451c33ba899: 192.168.80.1
  IP address for br-0ecec7c8a775: 192.168.144.1


 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

81 packages can be updated.
53 of these updates are security updates.
To see these additional updates run: apt list --upgradable

New release '20.04.2 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


Last login: Tue Mar 23 02:27:21 2021 from 10.248.208.122
appsadm@CLDDVDEVCE0481:~$ ssh -V
OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
```

**Comment by prantaaho** [comment]
I encountered  the same issue. After some trial and error I came to conclusion that Big Sur version of the ssh (OpenSSH_8.1p1, LibreSSL 2.7.3) has some issues with ConnectTimeout. Plain ssh fails when ConnectTimeout != 0:
```
❯ ssh -o ConnectTimeout=10 10.171.8.126
ssh: connect to host 10.171.8.126 port 22: Bad file descriptor
```
while ``ssh 10.171.8.126`` or ``ssh -o ConnectTimeout=0 10.171.8.126`` work just fine. Unfortunately it is not possible to specify ConnectTimeout to zero in the extension settings. 

I ended up to workaround with custom ssh-command ``"remote.SSH.path": "/Users/me/bin/ssh" `` which sets connection timeout option to 0 before calling real ssh. My simple bash-script to do that:
```bash
#!/usr/bin/env bash
for arg do
  shift
  [ "$arg" = "ConnectTimeout=15" ] && arg="ConnectTimeout=0"
  set -- "$@" "$arg"
done

exec /usr/bin/ssh $@
```

**Comment by chitranshu** [comment]
Thanks @prantaaho this workaround worked.. 

But we do need a permanent solution for this problem.

**Comment by prantaaho** [comment]
Another workaround is to use Homebrew version of Openssh. It would be nice to be able to set the timeout to 0 in extension settings, that would be the easiest solution to avoid this issue with BigSur default ssh.

**Comment by varunyn** [comment]
@prantaaho I updated ConnectTimeout to 0 in config file, and it worked fine. Thanks

```
Host *
  ConnectTimeout 0
```
