### ISSUE TITLE
`"remote.SSH.useLocalServer": true` overrides SSH_ASKPASS

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode-remote-release#4747]
Some of my testing implies that using `"remote.SSH.useLocalServer": true` overrides/overwrites/disables/ignores my global SSH_ASKPASS mechanism on Windows 10. It works fine without the local server,. I have tested a bunch of clients, including Win32-OpenSSH (OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2), Git for Windows `ssh.exe` (OpenSSH_8.5p1, OpenSSL 1.1.1j  16 Feb 2021), and Cygwin's `ssh.exe`s (OpenSSH_8.5p1, OpenSSL 1.1.1f  31 Mar 2020).

I don't have a major issue with that, but should documentation be coming in the future (compare #4492), this might also be considered.

**Comment by roblourens** [comment]
Yes, we do that so we can forward the auth prompt to the vscode window. Can you tell me more about your scenario? What are you setting SSH_ASKPASS to?

**Comment by bersbersbers** [comment]
I'm setting SSH_ASKPASS to a non-interactive batch file using oathtool and others - the key is "non-interactive", so that aspect is lost when the extension overrides the setting.

I can easily live without the local server. But if this issue shall be solved, a setting to not override SSH_ASKPASS could be helpful. (Not sure if SSH_ASKPASS_REQUIRE could be interpreted - I have set it to "force", could that be seen as an indication that the prompt is non-interactive (not in general, probably).

**Comment by tanhakabir** [comment]
@bersbersbers and @Samega7Cattac there will be an experimental setting in tomorrow's pre-release (version `v0.81.2022052415`) of the extension called `remote.SSH.externalSSH_ASKPASS` which will allow you to use your own SSH_ASKPASS value. Could you let me know how this works for you?

**Comment by bersbersbers** [comment]
@tanhakabir that seems to be working for me, thanks a lot :)

**Comment by Samega7Cattac** [comment]
Still doesn't work for me @tanmayeekamath 
```
[14:59:15.115] Log Level: 1
[14:59:15.126] remote-ssh@0.81.2022052415
[14:59:15.126] linux x64
[14:59:15.164] SSH Resolver called for "ssh-remote+ninetails", attempt 1
[14:59:15.172] "remote.SSH.useLocalServer": true
[14:59:15.172] "remote.SSH.path": undefined
[14:59:15.173] "remote.SSH.configFile": /home/samega7cattac/.ssh/config
[14:59:15.174] "remote.SSH.useFlock": true
[14:59:15.174] "remote.SSH.lockfilesInTmp": false
[14:59:15.174] "remote.SSH.localServerDownload": auto
[14:59:15.175] "remote.SSH.remoteServerListenOnSocket": false
[14:59:15.176] "remote.SSH.showLoginTerminal": true
[14:59:15.177] "remote.SSH.defaultExtensions": []
[14:59:15.177] "remote.SSH.loglevel": 1
[14:59:15.178] "remote.SSH.enableDynamicForwarding": true
[14:59:15.178] "remote.SSH.enableRemoteCommand": true
[14:59:15.178] "remote.SSH.serverPickPortsFromRange": {}
[14:59:15.179] "remote.SSH.serverInstallPath": {}
[14:59:15.220] SSH Resolver called for host: ninetails
[14:59:15.220] Setting up SSH remote "ninetails"
[14:59:15.228] Acquiring local install lock: /tmp/vscode-remote-ssh-ca530be0-install.lock
[14:59:15.240] Looking for existing server data file at /home/samega7cattac/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-ca530be0-c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5-0.81.2022052415/data.json
[14:59:15.242] Using commit id "c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5" and quality "stable" for server
[14:59:15.251] Install and start server if needed
[14:59:15.264] PATH: /opt/devkitpro/tools/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
[14:59:15.265] Checking ssh with "ssh -V"
[14:59:15.281] > OpenSSH_9.0p1, OpenSSL 1.1.1o  3 May 2022

[14:59:15.289] Using SSH config file "/home/samega7cattac/.ssh/config"
[14:59:15.291] askpass server listening on /run/user/1000/vscode-ssh-askpass-713357fa5f4e33554517777284ceddbe27ddf4fa.sock
[14:59:15.291] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-574f06354a7c22cd72d7f5cc619b2c5e91c97740.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","32929","-o","ConnectTimeout=15","-F","/home/samega7cattac/.ssh/config","ninetails","bash"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/samega7cattac/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-ca530be0-c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5-0.81.2022052415/data.json"}
[14:59:15.291] Local server env: {"SHELL":"/bin/bash","DISPLAY":":1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/samega7cattac/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022052415/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/opt/visual-studio-code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/samega7cattac/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022052415/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-713357fa5f4e33554517777284ceddbe27ddf4fa.sock"}
[14:59:15.303] Spawned 2546
[14:59:15.550] > local-server-1> Spawned ssh, pid=2555
[14:59:15.558] stderr> OpenSSH_9.0p1, OpenSSL 1.1.1o  3 May 2022
[14:59:15.558] stderr> debug1: Reading configuration data /home/samega7cattac/.ssh/config
[14:59:15.558] stderr> debug1: /home/samega7cattac/.ssh/config line 21: Applying options for ninetails
[14:59:15.558] stderr> debug1: Connecting to 192.168.1.119 [192.168.1.119] port 4269.
[14:59:15.649] stderr> debug1: fd 3 clearing O_NONBLOCK
[14:59:15.649] stderr> debug1: Connection established.
[14:59:15.650] stderr> debug1: identity file /home/samega7cattac/.ssh/id_rsa type -1
[14:59:15.650] stderr> debug1: identity file /home/samega7cattac/.ssh/id_rsa-cert type -1
[14:59:15.650] stderr> debug1: identity file /home/samega7cattac/.ssh/id_ecdsa type -1
[14:59:15.650] stderr> debug1: identity file /home/samega7cattac/.ssh/id_ecdsa-cert type -1
[14:59:15.650] stderr> debug1: identity file /home/samega7cattac/.ssh/id_ecdsa_sk type -1
[14:59:15.651] stderr> debug1: identity file /home/samega7cattac/.ssh/id_ecdsa_sk-cert type -1
[14:59:15.651] stderr> debug1: identity file /home/samega7cattac/.ssh/id_ed25519 type -1
[14:59:15.651] stderr> debug1: identity file /home/samega7cattac/.ssh/id_ed25519-cert type -1
[14:59:15.651] stderr> debug1: identity file /home/samega7cattac/.ssh/id_ed25519_sk type -1
[14:59:15.652] stderr> debug1: identity file /home/samega7cattac/.ssh/id_ed25519_sk-cert type -1
[14:59:15.652] stderr> debug1: identity file /home/samega7cattac/.ssh/id_xmss type -1
[14:59:15.652] stderr> debug1: identity file /home/samega7cattac/.ssh/id_xmss-cert type -1
[14:59:15.652] stderr> debug1: identity file /home/samega7cattac/.ssh/id_dsa type -1
[14:59:15.652] stderr> debug1: identity file /home/samega7cattac/.ssh/id_dsa-cert type -1
[14:59:15.652] stderr> debug1: Local version string SSH-2.0-OpenSSH_9.0
[14:59:15.669] stderr> debug1: Remote protocol version 2.0, remote software version OpenSSH_8.8
[14:59:15.669] stderr> debug1: compat_banner: match: OpenSSH_8.8 pat OpenSSH* compat 0x04000000
[14:59:15.669] stderr> debug1: Authenticating to 192.168.1.119:4269 as 'ninetails'
[14:59:15.670] stderr> debug1: load_hostkeys: fopen /home/samega7cattac/.ssh/known_hosts2: No such file or directory
[14:59:15.670] stderr> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
[14:59:15.670] stderr> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
[14:59:15.670] stderr> debug1: SSH2_MSG_KEXINIT sent
[14:59:15.679] stderr> debug1: SSH2_MSG_KEXINIT received
[14:59:15.680] stderr> debug1: kex: algorithm: curve25519-sha256
[14:59:15.680] stderr> debug1: kex: host key algorithm: ssh-ed25519
[14:59:15.680] stderr> debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
[14:59:15.680] stderr> debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
[14:59:15.680] stderr> debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
[14:59:15.729] stderr> debug1: SSH2_MSG_KEX_ECDH_REPLY received
[14:59:15.729] stderr> debug1: Server host key: ssh-ed25519 SHA256:qjEtvlq08ADAHm/JfXYts+flupfvp2rKYYPYAwHZMNg
[14:59:15.730] stderr> debug1: load_hostkeys: fopen /home/samega7cattac/.ssh/known_hosts2: No such file or directory
[14:59:15.730] stderr> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
[14:59:15.730] stderr> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
[14:59:15.730] stderr> debug1: Host '[192.168.1.119]:4269' is known and matches the ED25519 host key.
[14:59:15.730] stderr> debug1: Found key in /home/samega7cattac/.ssh/known_hosts:9
[14:59:15.751] stderr> debug1: rekey out after 134217728 blocks
[14:59:15.751] stderr> debug1: SSH2_MSG_NEWKEYS sent
[14:59:15.751] stderr> debug1: expecting SSH2_MSG_NEWKEYS
[14:59:15.751] stderr> debug1: SSH2_MSG_NEWKEYS received
[14:59:15.752] stderr> debug1: rekey in after 134217728 blocks
[14:59:15.752] stderr> debug1: Will attempt key: /home/samega7cattac/.ssh/id_rsa 
[14:59:15.752] stderr> debug1: Will attempt key: /home/samega7cattac/.ssh/id_ecdsa 
[14:59:15.752] stderr> debug1: Will attempt key: /home/samega7cattac/.ssh/id_ecdsa_sk 
[14:59:15.752] stderr> debug1: Will attempt key: /home/samega7cattac/.ssh/id_ed25519 
[14:59:15.753] stderr> debug1: Will attempt key: /home/samega7cattac/.ssh/id_ed25519_sk 
[14:59:15.753] stderr> debug1: Will attempt key: /home/samega7cattac/.ssh/id_xmss 
[14:59:15.754] stderr> debug1: Will attempt key: /home/samega7cattac/.ssh/id_dsa 
[14:59:15.754] stderr> debug1: SSH2_MSG_EXT_INFO received
[14:59:15.754] stderr> debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com>
[14:59:15.757] stderr> debug1: SSH2_MSG_SERVICE_ACCEPT received
[14:59:15.786] stderr> debug1: Authentications that can continue: publickey
[14:59:15.786] stderr> debug1: Next authentication method: publickey
[14:59:15.786] stderr> debug1: Trying private key: /home/samega7cattac/.ssh/id_rsa
[14:59:15.786] stderr> debug1: Trying private key: /home/samega7cattac/.ssh/id_ecdsa
[14:59:15.787] stderr> debug1: Trying private key: /home/samega7cattac/.ssh/id_ecdsa_sk
[14:59:15.787] stderr> debug1: Trying private key: /home/samega7cattac/.ssh/id_ed25519
[14:59:15.792] stderr> debug1: Trying private key: /home/samega7cattac/.ssh/id_ed25519_sk
[14:59:15.792] stderr> debug1: Trying private key: /home/samega7cattac/.ssh/id_xmss
[14:59:15.792] stderr> debug1: Trying private key: /home/samega7cattac/.ssh/id_dsa
[14:59:15.793] stderr> debug1: No more authentication methods to try.
[14:59:15.798] stderr> ninetails@192.168.1.119: Permission denied (publickey).
[14:59:15.800] > local-server-1> ssh child died, shutting down
[14:59:15.801] Local server exit: 0
[14:59:15.802] Received install output: local-server-1> Spawned ssh, pid=2555
OpenSSH_9.0p1, OpenSSL 1.1.1o  3 May 2022
debug1: Server host key: ssh-ed25519 SHA256:qjEtvlq08ADAHm/JfXYts+flupfvp2rKYYPYAwHZMNg

ninetails@192.168.1.119: Permission denied (publickey).
local-server-1> ssh child died, shutting down

[14:59:15.809] Stopped parsing output early. Remaining text: =ninetails@192.168.1.119: Permission denied (publickey).local-server-1> ssh child died, shutting down
[14:59:15.830] Resolver error: Error: Permission denied (publickey).
	at Function.Create (/home/samega7cattac/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022052415/out/extension.js:1:585219)
	at /home/samega7cattac/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022052415/out/extension.js:1:583276
	at Object.t.handleInstallOutput (/home/samega7cattac/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022052415/out/extension.js:1:583793)
	at Object.e [as tryInstallWithLocalServer] (/home/samega7cattac/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022052415/out/extension.js:1:624370)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/samega7cattac/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022052415/out/extension.js:1:643503
	at async Object.t.withShowDetailsEvent (/home/samega7cattac/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022052415/out/extension.js:1:647221)
	at async /home/samega7cattac/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022052415/out/extension.js:1:622842
	at async T (/home/samega7cattac/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022052415/out/extension.js:1:619348)
	at async Object.t.resolveWithLocalServer (/home/samega7cattac/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022052415/out/extension.js:1:622457)
	at async Object.t.resolve (/home/samega7cattac/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022052415/out/extension.js:1:644831)
	at async /home/samega7cattac/.vscode/extensions/ms-vscode-remote.remote-ssh-0.81.2022052415/out/extension.js:1:727004
[14:59:15.843] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"1","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"PermissionDenied","exitCodeLabel":""},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":665,"timing.preSshTime":127}}
[14:59:15.851] ------
```

I have set `Remote.SSH: External SSH_ASKPASS` to `true`
Set `Remote.SSH: Use Local Server` to `true`
and the output of my SSH_ASKPASS env var
```
$ echo $SSH_ASKPASS
/run/user/1000/gnupg/S.gpg-agent.ssh
```
I have now `SSH_ASKPASS` and `SSH_AUTH_SOCK` set to the same value (idk if it's correct) in my `.bashrc`
```
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
export SSH_ASKPASS=$(gpgconf --list-dirs agent-ssh-socket)
```

**Comment by Samega7Cattac** [comment]
Ok so if I run `code` from my terminal it works, but if I run from the Application Menu it doesn't.
I think I have my env var set correctly, it's in my .bashrc to export like in the end of the previous post

**Comment by bersbersbers** [comment]
> Ok so if I run `code` from my terminal it works, but if I run from the Application Menu it doesn't.
> I think I have my env var set correctly, it's in my .bashrc to export like in the end of the previous post

I am not an expert on this, but I would not have expected that `.bashrc` is parsed when you don't open a `bash` shell - and when you open Code via the application menu, I don't see why it should open a shell at all. So maybe that is why it's not working in that case. 

When I say it is working for me, that is on Windows with environment variables defined like in https://superuser.com/a/989665/253137

On OSX, for example, some googling suggest you need to use `/etc/launchd.conf` to make sure environment variables are available to application started by the GUI.

**Comment by tanhakabir** [comment]
Hm @Samega7Cattac for a sanity check, if you SSH through another application your YubiKey auth works as expected?

**Comment by Samega7Cattac** [comment]
ok I had the configuration wrong, its working now
