### ISSUE TITLE
Stuck in Password loop [SSH remote]

### ISSUE THREAD

**Issue by jeiros** [microsoft/vscode-remote-release#4764]
- VSCode Version: 1.54.3
- Local OS Version: Windows 10 Home
- Remote OS Version: Red Hat Enterprise Linux Server release 7.5 (Maipo)
- Remote Extension/Connection Type: S

Hello,

I get stuck in a password-asking (first the key password, then the user's password in the remote machine) loop when trying to establish connection to a Linux Host (myvm), using a jump server.

Here are the logs:

```
[15:18:06.652] Log Level: 1
[15:18:06.654] remote-ssh@0.65.1
[15:18:06.654] win32 x64
[15:18:06.655] SSH Resolver called for "ssh-remote+myvm", attempt 1
[15:18:06.655] "remote.SSH.useLocalServer": false
[15:18:06.655] "remote.SSH.showLoginTerminal": false
[15:18:06.655] "remote.SSH.remotePlatform": {"myvm":"linux"}
[15:18:06.655] "remote.SSH.sshPath": undefined
[15:18:06.656] "remote.SSH.sshConfigurationFile": undefined
[15:18:06.656] "remote.SSH.useFlock": false
[15:18:06.656] "remote.SSH.lockfilesInTmp": false
[15:18:06.656] "remote.SSH.localServerDownload": auto
[15:18:06.656] "remote.SSH.remoteServerListenOnSocket": false
[15:18:06.656] "remote.SSH.showLoginTerminal": false
[15:18:06.656] "remote.SSH.defaultExtensions": []
[15:18:06.656] SSH Resolver called for host: myvm
[15:18:06.656] Setting up SSH remote "myvm"
[15:18:06.666] Using commit id "2b9aebd5354a3629c3aba0a5f5df49f43d6689f8" and quality "stable" for server
[15:18:06.669] Install and start server if needed
[15:18:06.672] Checking ssh with "ssh -V"
[15:18:06.694] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[15:18:06.698] Running script with connection command: ssh -T -D 54887 myvm bash
[15:18:06.699] Terminal shell path: C:\Windows\System32\cmd.exe
[15:18:08.081] "install" terminal received data: "[2J[m[HEnter passphrase for key 'C:\Users\Juan/.ssh/id_rsa':[1C]0;C:\Windows\System32\cmd.exe[?25h"
[15:18:08.082] Got some output, clearing connection timeout
[15:18:08.082] Detected passphrase message
[15:18:11.470] Got passphrase response
[15:18:11.471] "install" wrote data to terminal: "************"
[15:18:11.488] "install" terminal received data: ""
[15:18:11.647] "install" terminal received data: "jeiroszamora@jzamora-l's password: "
[15:18:11.647] Showing password prompt
[15:18:14.591] Got password response
[15:18:14.591] "install" wrote data to terminal: "************"
[15:18:14.602] "install" terminal received data: ""
[15:18:15.712] "install" terminal received data: "a2bfc1ca736d: running"
[15:18:15.799] "install" terminal received data: "Acquiring lock on /home/jeiroszamora/.vscode-server/bin/2b9aebd5354a3629c3aba0a5
f5df49f43d6689f8/vscode-remote-lock.jeiroszamora.2b9aebd5354a3629c3aba0a5f5df49f
43d6689f8[K
\ln /home/jeiroszamora/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689
f8/vscode-remote-lock.jeiroszamora.2b9aebd5354a3629c3aba0a5f5df49f43d6689f8.targ
et /home/jeiroszamora/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f
8/vscode-remote-lock.jeiroszamora.2b9aebd5354a3629c3aba0a5f5df49f43d6689f8      "
[15:18:15.943] "install" terminal received data: "ln: failed to create hard link ‘/home/jeiroszamora/.vscode-server/bin/2b9aebd535
4a3629c3aba0a5f5df49f43d6689f8/vscode-remote-lock.jeiroszamora.2b9aebd5354a3629c
3aba0a5f5df49f43d6689f8’: File exists[K"
[15:18:16.028] "install" terminal received data: "Installation already in progress...[K
If you continue to see this message, you can try toggling the remote.SSH.useFloc
k setting[K
a2bfc1ca736d: start[K
exitCode==24==[K
listeningOn====[K
osReleaseId==rhel==[K
arch==x86_64==[K
tmpDir==/run/user/2981==[K
platform==linux==[K
unpackResult====[K
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
a2bfc1ca736d: end"
[15:18:16.028] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==rhel==
arch==x86_64==
tmpDir==/run/user/2981==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[15:18:16.029] Server installation process already in progress - waiting and retrying
[15:18:16.317] "install" terminal command done
[15:18:16.317] User entered passphrase
[15:18:16.319] Passphrase was entered and ssh config entry was found - adding SSH key to agent
[15:18:16.319] Executing add-ssh-key:
powershell -ExecutionPolicy Bypass C:\Users\Juan\AppData\Local\Temp\vscode_add_ssh_key_to_agent.ps1
[15:18:16.320] Terminal shell path: C:\Windows\System32\cmd.exe
[15:18:16.320] "add-ssh-key" wrote data to terminal: "powershell -ExecutionPolicy Bypass C:\Users\Juan\AppData\Local\Temp\vscode_add_ssh_key_to_agent.ps1"
[15:18:16.348] "add-ssh-key" terminal received data: "[2J[m[HMicrosoft Windows [Version 10.0.19042.867]]0;C:\Windows\System32\cmd.exe[?25h"
[15:18:16.360] "add-ssh-key" terminal received data: "
(c) 2020 Microsoft Corporation. All rights reserved.[K
[K
C:\Users\Juan>(powershell -ExecutionPolicy Bypass C:\Users\Juan\AppData\Local\Te
mp\vscode_add_ssh_key_to_agent.ps1[K"
[15:18:16.378] "add-ssh-key" terminal received data: ") & exit /b 0
]0;C:\Windows\System32\cmd.exe - powershell  -ExecutionPolicy Bypass C:\Users\Juan\AppData\Local\Temp\vscode_add_ssh_key_to_agent.ps1"
[15:18:16.548] "add-ssh-key" terminal received data: "PS: adding key to ssh-agent"
[15:18:16.570] "add-ssh-key" terminal received data: "
ssh-add[41X
C:\Users\Juan\.ssh\id_rsa[23X
Enter passphrase for C:\Users\Juan\.ssh\id_rsa: "
[15:18:16.570] Detected passphrase message
[15:18:16.570] Got passphrase response
[15:18:16.570] "add-ssh-key" wrote data to terminal: "************"
[15:18:16.585] "add-ssh-key" terminal received data: ""
[15:18:16.700] "add-ssh-key" terminal received data: "Identity added: C:\Users\Juan\.ssh\id_rsa (Juan Eiros Zamora jeiroszamora@abinit
io.com)[K"
[15:18:16.721] "add-ssh-key" terminal received data: "]0;C:\Windows\System32\cmd.exe"
[15:18:17.007] "add-ssh-key" terminal command done
[15:18:17.007] Install terminal quit with output: 
[15:18:17.032] Running script with connection command: ssh -T -D 54887 myvm bash
[15:18:17.034] Terminal shell path: C:\Windows\System32\cmd.exe
[15:18:18.370] "install" terminal received data: "[2J[m[HEnter passphrase for key 'C:\Users\Juan/.ssh/id_rsa':[1C]0;C:\Windows\System32\cmd.exe[?25h"
[15:18:18.370] Got some output, clearing connection timeout
[15:18:18.370] Detected passphrase message
[15:18:21.681] Got passphrase response
[15:18:21.681] "install" wrote data to terminal: "************"
[15:18:21.692] "install" terminal received data: ""
[15:18:21.852] "install" terminal received data: "jeiroszamora@jzamora-l's password: "
[15:18:21.852] Showing password prompt
[15:18:24.720] Got password response
[15:18:24.720] "install" wrote data to terminal: "************"
[15:18:24.729] "install" terminal received data: ""
[15:18:26.206] "install" terminal received data: "a2bfc1ca736d: running"
[15:18:26.277] "install" terminal received data: "Acquiring lock on /home/jeiroszamora/.vscode-server/bin/2b9aebd5354a3629c3aba0a5
f5df49f43d6689f8/vscode-remote-lock.jeiroszamora.2b9aebd5354a3629c3aba0a5f5df49f
43d6689f8[K
\ln /home/jeiroszamora/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689
f8/vscode-remote-lock.jeiroszamora.2b9aebd5354a3629c3aba0a5f5df49f43d6689f8.targ
et /home/jeiroszamora/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f
8/vscode-remote-lock.jeiroszamora.2b9aebd5354a3629c3aba0a5f5df49f43d6689f8      
Installation already in progress...[K
If you continue to see this message, you can try toggling the remote.SSH.useFloc
k setting[K
a2bfc1ca736d: start[K
exitCode==24==[K
listeningOn====[K
osReleaseId==rhel==[K
arch==x86_64==[K
tmpDir==/run/user/2981==[K
platform==linux==[K
unpackResult====[K
didLocalDownload==0==[K
downloadTime====[K
installTime====[K
extInstallTime====
serverStartTime====
a2bfc1ca736d: end
ln: failed to create hard link ‘/home/jeiroszamora/.vscode-server/bin/2b9aebd535
4a3629c3aba0a5f5df49f43d6689f8/vscode-remote-lock.jeiroszamora.2b9aebd5354a3629c
3aba0a5f5df49f43d6689f8’: File exists"
[15:18:26.277] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==rhel==
arch==x86_64==
tmpDir==/run/user/2981==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[15:18:26.278] Server installation process already in progress - waiting and retrying
[15:18:26.301] "install" terminal received data: ""
[15:18:26.586] "install" terminal command done
[15:18:26.586] User entered passphrase
[15:18:26.588] Passphrase was entered and ssh config entry was found - adding SSH key to agent
[15:18:26.589] Executing add-ssh-key:
powershell -ExecutionPolicy Bypass C:\Users\Juan\AppData\Local\Temp\vscode_add_ssh_key_to_agent.ps1
[15:18:26.589] Terminal shell path: C:\Windows\System32\cmd.exe
[15:18:26.589] "add-ssh-key" wrote data to terminal: "powershell -ExecutionPolicy Bypass C:\Users\Juan\AppData\Local\Temp\vscode_add_ssh_key_to_agent.ps1"
[15:18:26.617] "add-ssh-key" terminal received data: "[2J[m[HMicrosoft Windows [Version 10.0.19042.867]]0;C:\Windows\System32\cmd.exe[?25h"
[15:18:26.631] "add-ssh-key" terminal received data: "
(c) 2020 Microsoft Corporation. All rights reserved.[K
[K
C:\Users\Juan>(powershell -ExecutionPolicy Bypass C:\Users\Juan\AppData\Local\Te
mp\vscode_add_ssh_key_to_agent.ps1[K"
[15:18:26.647] "add-ssh-key" terminal received data: ") & exit /b 0
]0;C:\Windows\System32\cmd.exe - powershell  -ExecutionPolicy Bypass C:\Users\Juan\AppData\Local\Temp\vscode_add_ssh_key_to_agent.ps1"
[15:18:26.815] "add-ssh-key" terminal received data: "PS: adding key to ssh-agent"
[15:18:26.825] "add-ssh-key" terminal received data: "
ssh-add[41X
C:\Users\Juan\.ssh\id_rsa[23X
Enter passphrase for C:\Users\Juan\.ssh\id_rsa: "
[15:18:26.825] Detected passphrase message
[15:18:26.826] Got passphrase response
[15:18:26.826] "add-ssh-key" wrote data to terminal: "************"
[15:18:26.840] "add-ssh-key" terminal received data: ""
[15:18:26.955] "add-ssh-key" terminal received data: "Identity added: C:\Users\Juan\.ssh\id_rsa (Juan Eiros Zamora jeiroszamora@abinit
io.com)[K"
[15:18:26.977] "add-ssh-key" terminal received data: "]0;C:\Windows\System32\cmd.exe"
[15:18:27.261] "add-ssh-key" terminal command done
[15:18:27.261] Install terminal quit with output: 
[15:18:27.287] Running script with connection command: ssh -T -D 54887 myvm bash
[15:18:27.288] Terminal shell path: C:\Windows\System32\cmd.exe
[15:18:28.667] "install" terminal received data: "[2J[m[HEnter passphrase for key 'C:\Users\Juan/.ssh/id_rsa':[1C]0;C:\Windows\System32\cmd.exe[?25h"
[15:18:28.667] Got some output, clearing connection timeout
[15:18:28.668] Detected passphrase message
[15:18:29.075] Passphrase dialog canceled
[15:18:29.075] "install" terminal command canceled
[15:18:29.078] Resolver error: Error: Connecting was canceled
	at Function.Canceled (c:\Users\Juan\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:64524)
	at c:\Users\Juan\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:295746
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
[15:18:29.080] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"1","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Canceled","exitCodeLabel":""},"measures":{"resolveAttempts":1,"retries":3,"timing.totalResolveTime":22422,"timing.preSshTime":20634,"timing.establishSshTime":-1082,"timing.scriptTime":1788}}
[15:18:29.081] -----
```
(The "Error: Connecting was canceled" is me pressing Ctrl+C when being asked for a password again).

My ~/.ssh/config file:
```
Host abijump
	User jeiroszamora
	HostName ssh4.acme.com
	KexAlgorithms +diffie-hellman-group1-sha1

Host myvm
	User jeiroszamora
	HostName jzamora-l
	IdentityFile ~/.ssh/id_rsa
	ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -q -W %h:%p abijump
```

When I run the same SSH command from my Windows Command Prompt, this is what I see:

```
C:\Users\Juan>ssh -T -D 54887 myvm bash
Enter passphrase for key 'C:\Users\Juan/.ssh/id_rsa':
jeiroszamora@jzamora-l's password:
```

Can someone help me out? Is there any other information I can give to help resolve this issue?

**Comment by qrqiuren** [comment]
I also have the same problem.

**Comment by qrqiuren** [comment]
After each loop there's an error message like below. I'm not sure if it is the problem.

```
[17:53:56.019] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (c:\Users\qrqiuren\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.8100\out\extension.js:1:64575)
	at c (c:\Users\qrqiuren\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.8100\out\extension.js:1:58900)
	at Object.t.handleInstallOutput (c:\Users\qrqiuren\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.8100\out\extension.js:1:63317)
	at Object.t.tryInstall (c:\Users\qrqiuren\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.8100\out\extension.js:1:414004)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\qrqiuren\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.8100\out\extension.js:1:294518
	at async Object.t.withShowDetailsEvent (c:\Users\qrqiuren\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.8100\out\extension.js:1:405349)
	at async Object.t.resolve (c:\Users\qrqiuren\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.8100\out\extension.js:1:295639)
	at async c:\Users\qrqiuren\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.8100\out\extension.js:127:110540
[17:53:56.025] ------
```

**Comment by tanhakabir** [comment]
Hey! You could look for some help here: https://github.com/microsoft/vscode-remote-release/issues/4613

You could try restarting the server by running `Kill VS Code Server on Host`
