### ISSUE TITLE
The VS Code Server failed to start

### ISSUE THREAD

**Issue by zhangxinlong633** [microsoft/vscode-remote-release#4780]
[13:22:49.712] Terminating local server
[13:22:49.718] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (/Users/zhangxinlong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:64262)
	at c (/Users/zhangxinlong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:58739)
	at Object.t.handleInstallOutput (/Users/zhangxinlong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:63055)
	at Object.t.tryInstallWithLocalServer (/Users/zhangxinlong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:388682)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async /Users/zhangxinlong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:293749
	at async Object.t.withShowDetailsEvent (/Users/zhangxinlong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:407055)
	at async /Users/zhangxinlong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:387177
	at async N (/Users/zhangxinlong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:383945)
	at async Object.t.resolveWithLocalServer (/Users/zhangxinlong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:386804)
	at async Object.t.resolve (/Users/zhangxinlong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:297790)
	at async /Users/zhangxinlong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:127:110485
[13:22:49.721] Local server exit: 15
[13:22:49.726] ------

**Comment by nickWardDesigns** [comment]
I'm also having the same issue.

**Comment by zhangxinlong633** [comment]
vs code server in Linux, and I reinstall the OS. It works.!!!

**Comment by bamurtaugh** [comment]
@zhangxinlong633 To clarify - is Remote-SSH now working? 

@nickWardDesigns are you still experiencing this issue?

**Comment by nickWardDesigns** [comment]
@bamurtaugh Yeah I'm still having issues. I was able to get it working about a month ago using a solution mentioned [on Reddit](https://www.reddit.com/r/vscode/comments/i1sme4/has_anyone_been_able_to_connect_via_ssh_to_shared/), though it suddenly stopped working for me.

**Comment by bamurtaugh** [comment]
@nickWardDesigns Can you include the [logs](https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues)?

**Comment by nickWardDesigns** [comment]
Sorry been quite busy lately. Not sure how much of the log you need (I'm new to reporting issues :P) but here you go:

[13:31:22.390] Terminating local server
[13:31:22.394] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (/Users/nickward/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.3/out/extension.js:1:64575)
	at c (/Users/nickward/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.3/out/extension.js:1:58900)
	at Object.t.handleInstallOutput (/Users/nickward/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.3/out/extension.js:1:63317)
	at Object.e [as tryInstallWithLocalServer] (/Users/nickward/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.3/out/extension.js:1:386419)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async /Users/nickward/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.3/out/extension.js:1:294035
	at async Object.t.withShowDetailsEvent (/Users/nickward/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.3/out/extension.js:1:405329)
	at async /Users/nickward/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.3/out/extension.js:1:384890
	at async E (/Users/nickward/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.3/out/extension.js:1:381658)
	at async Object.t.resolveWithLocalServer (/Users/nickward/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.3/out/extension.js:1:384517)
	at async Object.t.resolve (/Users/nickward/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.3/out/extension.js:1:295505)
	at async /Users/nickward/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.3/out/extension.js:127:110540
[13:31:22.395] Local server exit: 15
[13:31:22.397] ------

**Comment by nickWardDesigns** [comment]
No, this would be the full log. I included a file due to formatting issues when pasting it here.

[logs.txt](https://github.com/microsoft/vscode-remote-release/files/6345033/logs.txt)

**Comment by bamurtaugh** [comment]
cc @roblourens Seems related to https://github.com/microsoft/vscode-remote-release/issues/3201? Based on the linked Reddit post and `Check failed: reservation_.SetPermissions` from @nickWardDesigns's logs.

**Comment by roblourens** [comment]
Are you on Dreamhost @nickWardDesigns?

**Comment by nickWardDesigns** [comment]
Yes, Dreamhost shared hosting.

**Comment by roblourens** [comment]
That original `setfattr` command that was claimed to fix it doesn't make sense to me because it's fixing node inside `NVM_DIR` which is not the node we invoke.

What if you try it with `find ~/.vscode-server -type f -iname "node" -o -iname "npm" -o -iname "npx"` instead?

**Comment by nickWardDesigns** [comment]
Yup, that worked! Thank you so much!

**Comment by roblourens** [comment]
Great!
