### ISSUE TITLE
SSH to Ubuntu fails, creds are ok

### ISSUE THREAD

**Issue by mash8336** [microsoft/vscode-remote-release#4786]
- VSCode Version: 1.54.3
- Local OS Version: Win10 20H2 19042.867
- Remote OS Version: Ubuntu 18.04.5 LTS / Ubuntu 20.04.2 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Creds (key pair) tested in command window ok
2. Has never connected, PC recently refreshed

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: Don't know

Not sure what to make of the log:
1. remote.SSH.sshConfigurationFile is defined hence can ssh from command window "ssh IP_Address"
2. remote.SSH.remotePlatform is blank but I told a popup it was "Linux"

[06:12:28.004] Log Level: 2
[06:12:28.011] remote-ssh@0.65.1
[06:12:28.011] win32 x64
[06:12:28.013] SSH Resolver called for "ssh-remote+192.168.222.98", attempt 1
[06:12:28.014] "remote.SSH.useLocalServer": false
[06:12:28.014] "remote.SSH.showLoginTerminal": false
[06:12:28.015] "remote.SSH.remotePlatform": {}
[06:12:28.015] "remote.SSH.sshPath": undefined
[06:12:28.015] "remote.SSH.sshConfigurationFile": undefined
[06:12:28.015] "remote.SSH.useFlock": true
[06:12:28.016] "remote.SSH.lockfilesInTmp": false
[06:12:28.016] "remote.SSH.localServerDownload": auto
[06:12:28.016] "remote.SSH.remoteServerListenOnSocket": false
[06:12:28.016] "remote.SSH.showLoginTerminal": false
[06:12:28.017] "remote.SSH.defaultExtensions": []
[06:12:28.017] SSH Resolver called for host: 192.168.222.98
[06:12:28.017] Setting up SSH remote "192.168.222.98"
[06:12:28.039] Using commit id "2b9aebd5354a3629c3aba0a5f5df49f43d6689f8" and quality "stable" for server
[06:12:28.045] Install and start server if needed
[06:12:57.258] getPlatformForHost was canceled
[06:12:57.264] Resolver error: Error: Connecting was canceled
	at Function.Canceled (c:\Users\Mark\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:64524)
	at c:\Users\Mark\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:294133
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Object.t.withShowDetailsEvent (c:\Users\Mark\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:407055)
	at async Object.t.resolve (c:\Users\Mark\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:297912)
	at async c:\Users\Mark\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:127:110485
[06:12:57.269] ------

**Comment by mash8336** [comment]
Just started working, no idea why, reboot maybe

**Comment by roblourens** [comment]
> getPlatformForHost was canceled

It thinks that you pressed escape or clicked out of that popup. Glad it's working now, let me know if it stops working
