### ISSUE TITLE
New bug for whitespace in windows hostname

### ISSUE THREAD

**Issue by sjtututu** [microsoft/vscode-remote-release#4815]
- VSCode Version: 1.55
- Local OS Version: win10 2004
- Remote OS Version: win10 20H2
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Disable other extensions
2.Remote connect to windows hosts

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**The error as follow:** 
(node:10668) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\Tu'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at ce (C:\Users\Tu Xinglong\.vscode-server\bin\c185983a683d14c396952dd432459097bc7f757f\out\vs\server\remoteExtensi
onHostAgent.js:120:7355)
    at Le (C:\Users\Tu Xinglong\.vscode-server\bin\c185983a683d14c396952dd432459097bc7f757f\out\vs\server\remoteExtensi
onHostAgent.js:132:109)
    at Object.n [as createServer] (C:\Users\Tu Xinglong\.vscode-server\bin\c185983a683d14c396952dd432459097bc7f757f\out
\vs\server\remoteExtensionHostAgent.js:148:1378)
    at C:\Users\Tu Xinglong\.vscode-server\bin\c185983a683d14c396952dd432459097bc7f757f\out\vs\server\main.js:1:782
(node:10668) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing in
side of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To term
inate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://no
dejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

**I'm sure it's caused by whitespace in windows hostname, becasue I can connect to my remote windows host by the manual command **: _& 'C:\Users\Tu Xinglong\.vscode-server\bin\c185983a683d14c396952dd432459097bc7f757f\server.cmd' --start-server --host=127.0.0.1 --enable-remote-auto-shutdown --port=0 --connection-secret 'C:\Users\Tu Xinglong\.vscode-server\.c185983a683d14c396952dd432459097bc7f757f.token' *> 'C:\Users\Tu Xinglong\.vscode-server\.c185983a683d14c396952dd432459097bc7f757f.log_'

**Comment by sjtututu** [comment]
problem solved!
