### ISSUE TITLE
SSH stuck on wget before failling

### ISSUE THREAD

**Issue by koetjeengdjalanan** [microsoft/vscode-remote-release#4823]
- VSCode Version:1.55.0
- Local OS Version: 20H2 (19042.867)
- Remote OS Version: 5.11.11-200.fc33.x86_64
- Remote Extension/Connection Type: SSH

This is the output of the debug console:
```
[09:03:12.835] Log Level: 2
[09:03:12.839] remote-ssh@0.65.1
[09:03:12.839] win32 x64
[09:03:12.842] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a224a6f6b6f5f7365727665722d4b525f4f6666696365227d", attempt 1
[09:03:12.842] "remote.SSH.useLocalServer": false
[09:03:12.842] "remote.SSH.showLoginTerminal": false
[09:03:12.842] "remote.SSH.remotePlatform": {"Joko_Server":"linux","192.168.0.246":"linux","Joko_Server-Telkom":"linux","Joko_server-KR_Office":"linux","101.255.120.81":"linux","Linode_Server":"linux","KR_Office-Remote":"linux"}
[09:03:12.843] "remote.SSH.sshPath": undefined
[09:03:12.843] "remote.SSH.sshConfigurationFile": undefined
[09:03:12.843] "remote.SSH.useFlock": true
[09:03:12.843] "remote.SSH.lockfilesInTmp": false
[09:03:12.843] "remote.SSH.localServerDownload": auto
[09:03:12.843] "remote.SSH.remoteServerListenOnSocket": false
[09:03:12.844] "remote.SSH.showLoginTerminal": false
[09:03:12.844] "remote.SSH.defaultExtensions": []
[09:03:12.844] SSH Resolver called for host: Joko_server-KR_Office
[09:03:12.844] Setting up SSH remote "Joko_server-KR_Office"
[09:03:12.869] Using commit id "c185983a683d14c396952dd432459097bc7f757f" and quality "stable" for server
[09:03:12.873] Install and start server if needed
[09:03:12.879] Checking ssh with "ssh -V"
[09:03:12.940] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[09:03:12.944] Running script with connection command: ssh -T -D 23088 "Joko_server-KR_Office" bash
[09:03:12.948] Terminal shell path: C:\Windows\System32\cmd.exe
[09:03:13.255] > user@192.168.0.246's password:]0;C:\Windows\System32\cmd.exe
[09:03:13.255] Got some output, clearing connection timeout
[09:03:13.256] Showing password prompt
[09:03:17.689] Got password response
[09:03:17.690] "install" wrote data to terminal: "**********"
[09:03:17.754] > 
[09:03:18.300] > b378c80ae944: running
[09:03:18.332] > Acquiring lock on /home/user/.vscode-server/bin/c185983a683d14c396952
> dd432459097bc7f757f/vscode-remote-lock.user.c185983a683d14c396952dd43
> 2459097bc7f757f
[09:03:18.397] > Installing to /home/user/.vscode-server/bin/c185983a683d14c396952dd43
> 2459097bc7f757f...
> b378c80ae944%%1%%
> Downloading with wget
[09:03:25.160] > user@192.168.0.246's password:
> b378c80ae944: running
> Acquiring lock on /home/user/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/vscode-remote-lock.user.c185983a683d14c396952dd432459097bc7f757f
> Installing to /home/user/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f...
> b378c80ae944%%1%%
> Downloading with wget
> 
> 
> 
> 
> 
> 
[09:18:34.942] > wget download failedprintenv:
>     SHELL=/bin/bash
>     PWD=/home/user/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f
>     LOGNAME=user
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/home/user
>     LANG=en_US.UTF-8
>     VSCODE_AGENT_FOLDER=/home/user/.vscode-server
[09:18:34.943] > 
>     SSH_CONNECTION=192.168.0.34 23090 192.168.0.246 22
>     XDG_SESSION_CLASS=user
>     SELINUX_ROLE_REQUESTED=
>     LESSOPEN=||/usr/bin/lesspipe.sh %s
>     USER=user
>     SELINUX_USE_CURRENT_RANGE=
>     SHLVL=0
>     XDG_SESSION_ID=14
>     XDG_RUNTIME_DIR=/run/user/1000
>     SSH_CLIENT=192.168.0.34 23090 22
>     PATH=/home/user/.local/bin:/home/user/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
>     SELINUX_LEVEL_REQUESTED=
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
>     OLDPWD=/home/user
>     _=/usr/bin/printenv
> Trigger local server download
> b378c80ae944:trigger_server_download
> platform==linux==
> vscodeArch==x64==
> destFolder==/home/user/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f==
> b378c80ae944:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/user/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f/vscode-scp-done.flag and vscode-server.tar.gz to exist
[09:18:34.944] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/home/user/.vscode-server/bin/c185983a683d14c396952dd432459097bc7f757f"}
[09:18:34.945] Downloading VS Code server locally...
[09:18:34.971] > 
> 
[09:20:39.965] Resolver error: Error: Running the contributed command: '_workbench.downloadResource' failed.
	at S._executeContributedCommand (c:\Users\IT Technician\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:106930)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\IT Technician\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:139049
	at async Object.t.downloadAndCopyToHost (c:\Users\IT Technician\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:138964)
	at async c:\Users\IT Technician\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:295868
	at async q (c:\Users\IT Technician\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:296086)
	at async c:\Users\IT Technician\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:294221
	at async Object.t.withShowDetailsEvent (c:\Users\IT Technician\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:407055)
	at async Object.t.resolve (c:\Users\IT Technician\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:297912)
	at async c:\Users\IT Technician\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:127:110485
[09:20:39.972] ------

```

And, yes I've delete .vscode directory several time on the server side. Re-Installing? yes I've done that too
please help because i really love using vscode.

**Comment by roblourens** [comment]
Another user reported this and it went away. Could you share the log that is asked for in this issue? https://github.com/microsoft/vscode-remote-release/issues/4743#issuecomment-805588249
