### ISSUE TITLE
Disconnect button not terminating the debugger session

### ISSUE THREAD

**Issue by aleks-j** [microsoft/vscode-remote-release#4834]
- VSCode Version: 1.55.0
- Local OS Version: Ubuntu 20.10
- Remote OS Version: Debian buster slim (from python:3.8-slim-buster docker image)
- Remote Extension/Connection Type: Docker

Steps to Reproduce:

1. Run a container (I have done so with docker-compose and a Django app running in it)
2. Start the debugger so that it attaches to the said container
2. After the debugger starts, press the disconnect button to stop the debugger
3. Upon the debugger stopping, press the disconnect button again to terminate the debugger. Here nothing happens and the following is logged:
```[2021-04-06 11:27:49.269] [renderer1] [error] cannot find session: Error: cannot find session
	at S.getSession (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:35886)
	at S.$acceptDebugSessionTerminated (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:32859)
	at u._doInvokeHandler (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12794)
	at u._invokeHandler (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12478)
	at u._receiveRequest (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:11145)
	at u._receiveOneMessage (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:9931)
	at /snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:8032
	at _.fire (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at E.fire (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15496)
	at /snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:30083
	at _.fire (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at E.fire (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15496)
	at t._receiveMessage (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:20754)
	at /snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17640
	at _.fire (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at acceptChunk (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12861)
	at /snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12209
	at Socket.w (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:13173)
	at Socket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at Socket.Readable.push (_stream_readable.js:212:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)

```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by aleks-j** [comment]
Thanks, will take a deeper look into it
