### ISSUE TITLE
The VS Code Server failed to start

### ISSUE THREAD

**Issue by kieran199** [microsoft/vscode-remote-release#4850]
Hi there

The server seemed to install OK but it won't start, with the below error.

I have tried to kill server on host & retry it, but it doesn't work unfortunately.

Can you advise me

`[07:30:37.949] Terminating local server
[07:30:37.953] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (/Users/keenek1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:64262)
	at c (/Users/keenek1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:58739)
	at Object.t.handleInstallOutput (/Users/keenek1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:63055)
	at Object.t.tryInstallWithLocalServer (/Users/keenek1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:388682)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async /Users/keenek1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:293749
	at async Object.t.withShowDetailsEvent (/Users/keenek1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:407055)
	at async /Users/keenek1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:387177
	at async N (/Users/keenek1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:383945)
	at async Object.t.resolveWithLocalServer (/Users/keenek1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:386804)
	at async Object.t.resolve (/Users/keenek1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:297790)
	at async /Users/keenek1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:127:110485
[07:30:37.955] Local server exit: 15
[07:30:37.958] ------`

**Comment by tkelkermans** [comment]
Same issue. I removed the .vscode-server folder on the server side, and it is working now.

**Comment by kieran199** [comment]
Thanks a lot for your reply - I tried removing the folder using  rm -r .vscode-server but unfortunately, the problem persists. It does the wget downloads again successfully, but then just 'waiting for server logs' before it fails!

**Comment by bamurtaugh** [comment]
It seems like a few issues have been opened recently with `Terminating local server... Resolver error: Error: The VS Code Server failed to start at Function.ServerInstallError` in the logs; https://github.com/microsoft/vscode-remote-release/issues/4780, https://github.com/microsoft/vscode-remote-release/issues/4847, https://github.com/microsoft/vscode-remote-release/issues/4764#issuecomment-815585049. 

cc @roblourens In case there's something related among these.

**Comment by roblourens** [comment]
Please include the full log

**Comment by walterzhaoJR** [comment]
@bamurtaugh 
```
[10:28:17.342] Log Level: 2
[10:28:17.344] remote-ssh@0.65.8
[10:28:17.344] darwin x64
[10:28:17.345] SSH Resolver called for "ssh-remote+9.30.17.168", attempt 1
[10:28:17.345] "remote.SSH.useLocalServer": true
[10:28:17.345] "remote.SSH.path": undefined
[10:28:17.346] "remote.SSH.configFile": undefined
[10:28:17.346] "remote.SSH.useFlock": true
[10:28:17.346] "remote.SSH.lockfilesInTmp": false
[10:28:17.346] "remote.SSH.localServerDownload": auto
[10:28:17.346] "remote.SSH.remoteServerListenOnSocket": false
[10:28:17.347] "remote.SSH.showLoginTerminal": false
[10:28:17.347] "remote.SSH.defaultExtensions": []
[10:28:17.347] "remote.SSH.loglevel": 2
[10:28:17.347] SSH Resolver called for host: 9.30.17.168
[10:28:17.347] Setting up SSH remote "9.30.17.168"
[10:28:17.352] Acquiring local install lock: /var/folders/ks/v0082gtn2nvc0cc4skj54gth0000gn/T/vscode-remote-ssh-8d7573ee-install.lock
[10:28:17.364] Looking for existing server data file at /Users/walterzhao/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-8d7573ee-83bd43bc519d15e50c4272c6cf5c1479df196a4d-0.65.8/data.json
[10:28:17.365] Using commit id "83bd43bc519d15e50c4272c6cf5c1479df196a4d" and quality "stable" for server
[10:28:17.367] Install and start server if needed
[10:28:17.369] PATH: /Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
[10:28:17.369] Checking ssh with "ssh -V"
[10:28:17.373] > OpenSSH_8.1p1, LibreSSL 2.7.3

[10:28:17.375] askpass server listening on /var/folders/ks/v0082gtn2nvc0cc4skj54gth0000gn/T/vscode-ssh-askpass-a5c171df74a6e4998692fb28a419fe51591ab72f.sock
[10:28:17.376] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/ks/v0082gtn2nvc0cc4skj54gth0000gn/T/vscode-ssh-askpass-9e73b14566a0e1a46b1c672616f72120982bfc5f.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","50079","-o","ConnectTimeout=15","9.30.17.168"],"dataFilePath":"/Users/walterzhao/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-8d7573ee-83bd43bc519d15e50c4272c6cf5c1479df196a4d-0.65.8/data.json"}
[10:28:17.376] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/walterzhao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/walterzhao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/ks/v0082gtn2nvc0cc4skj54gth0000gn/T/vscode-ssh-askpass-a5c171df74a6e4998692fb28a419fe51591ab72f.sock"}
[10:28:17.377] Spawned 3466
[10:28:17.497] > local-server-1> Spawned ssh, pid=3471
[10:28:17.500] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[10:28:17.538] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:UZJx2kiGJKekMD5/rHmKJiYRynmqczJ1lfiG3EKIKTA
[10:28:17.575] stderr> Authenticated to 9.30.17.168 ([9.30.17.168]:36000).
[10:28:17.592] > Warning: your password will expire in 0 days
[10:28:17.658] > ready: 4a5440c32fef
[10:28:17.669] > Linux 5.4.119-1-tlinux4-0004 #1 SMP Fri May 28 10:26:46 CST 2021
[10:28:17.683] Platform: linux
[10:28:17.702] > 4a5440c32fef: running
[10:28:17.732] > Acquiring lock on /data1/home/walterzhao/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/vscode-remote-lock.walterzhao.83bd43bc519d15e50c4272c6cf5c1479df196a4d
[10:28:17.735] > Installing to /data1/home/walterzhao/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d...
[10:28:17.739] > 4a5440c32fef%%1%%
[10:28:17.741] > Downloading with wget
[10:28:17.752] > wget download failed
[10:28:17.752] > 
> printenv:
[10:28:17.754] >     XDG_SESSION_ID=277402
>     HOSTNAME=TENCENT64.site
>     SHELL=/bin/bash
>     HISTSIZE=3000
>     SSH_CLIENT=10.89.19.57 50081 36000
>     TMPDIR=/data1/tmpdir
>     LC_ALL=zh_CN.UTF-8
>     NO_PROXY=localhost,127.0.0.1,.oa.com
>     USER=walterzhao
>     http_proxy=http://web-proxy.tencent.com:8080
>     VSCODE_AGENT_FOLDER=/data1/home/walterzhao/.vscode-server
>     PATH=/data1/home/walterzhao/bin/lcov-1.13/bin:/sbin:/bin:/usr/sbin:/usr/bin:/data1/home/walterzhao/.local/bin:/data1/home/walterzhao/bin:/bin
>     MAIL=/var/spool/mail/walterzhao
>     PWD=/data1/home/walterzhao/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d
>     TST_HACK_BASH_SESSION_ID=27974753844537
>     LANG=zh_CN.UTF-8
>     MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
>     LOADEDMODULES=
>     https_proxy=http://web-proxy.tencent.com:8080
>     HTTPS_PROXY=http://web-proxy.tencent.com:8080
>     HISTCONTROL=ignoredups
>     HOME=/data1/home/walterzhao
>     SHLVL=2
>     no_proxy=git.woa.com,9.30.17.168,9.30.17.130,9.30.17.135,127.0.0.1,tlinux-mirror.tencent-cloud.com,tlinux-mirrorlist.tencent-cloud.com,localhost,mirrors-tlinux.tencentyun.com,.oa.com,.local
>     HTTP_PROXY=http://web-proxy.tencent.com:8080
>     LOGNAME=walterzhao
>     CVS_RSH=ssh
>     SSH_CONNECTION=10.89.19.57 50081 9.30.17.168 36000
>     MODULESHOME=/usr/share/Modules
>     LESSOPEN=||/usr/bin/lesspipe.sh %s
>     GOPATH=/data1/home/walterzhao/go
>     XDG_RUNTIME_DIR=/run/user/1003
>     BASH_FUNC_module()=() {  eval `/usr/bin/modulecmd bash $*`
>     }
>     _=/bin/printenv
>     OLDPWD=/data1/home/walterzhao
[10:28:17.754] > Trigger local server download
> 4a5440c32fef:trigger_server_download
> platform==linux==
> vscodeArch==x64==
[10:28:17.754] > destFolder==/data1/home/walterzhao/.vscode-server/bin/==
> destFolder2==83bd43bc519d15e50c4272c6cf5c1479df196a4d==
> 4a5440c32fef:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /data1/home/walterzhao/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/vscode-scp-done.flag and vscode-server.tar.gz to exist
[10:28:17.754] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/data1/home/walterzhao/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d"}
[10:28:17.754] Downloading VS Code server locally...
[10:28:19.181] Terminating local server
[10:28:19.183] Resolver error: Error: Running the contributed command: '_workbench.downloadResource' failed.
	at _executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:111039)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/walterzhao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:427617
	at async Object.t.downloadAndCopyToHost (/Users/walterzhao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:427532)
	at async /Users/walterzhao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:434898
	at async Object.e [as tryInstallWithLocalServer] (/Users/walterzhao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:434982)
	at async /Users/walterzhao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:452665
	at async Object.t.withShowDetailsEvent (/Users/walterzhao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:456460)
	at async /Users/walterzhao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:433816
	at async C (/Users/walterzhao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:430392)
	at async Object.t.resolveWithLocalServer (/Users/walterzhao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:433431)
	at async Object.t.resolve (/Users/walterzhao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:454065)
	at async /Users/walterzhao/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:526942
[10:28:19.185] Local server exit: 15
[10:28:19.187] ------





```

**Comment by roblourens** [comment]
@walterzhaoJR please open your own issue if needed

> _workbench.downloadResource

Probably a network issue, something involving a proxy?
