### ISSUE TITLE
SSH Keeps saying "attempting to reconnect"

### ISSUE THREAD

**Issue by deepak6422** [microsoft/vscode-remote-release#4867]
This same issue has been reported here but I couldn't find any solution to resolve this.
Link to issue: https://github.com/microsoft/vscode-remote-release/issues/246

**Comment by bamurtaugh** [comment]
@deepak6422 Can you please include the relevant logs ([info here](https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues))?

**Comment by deepak6422** [comment]
Attaching below the complete logs.
`[2021-04-15 11:16:03.250] [renderer3] [info] [remote-connection][Management   ][cd22f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-04-15 11:16:03.259] [renderer3] [info] [remote-connection][Management   ][cd22f…][reconnect] waiting for 5 seconds before reconnecting...
[2021-04-15 11:16:08.260] [renderer3] [info] [remote-connection][Management   ][cd22f…][reconnect] resolving connection...
[2021-04-15 11:16:12.654] [renderer3] [info] [remote-connection][ExtensionHost][697ce…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-04-15 11:16:12.654] [renderer3] [info] [remote-connection][ExtensionHost][697ce…][reconnect] waiting for 5 seconds before reconnecting...
[2021-04-15 11:16:17.654] [renderer3] [info] [remote-connection][ExtensionHost][697ce…][reconnect] resolving connection...
[2021-04-15 11:16:43.809] [renderer3] [info] [remote-connection][Management   ][cd22f…][reconnect] connecting to 127.0.0.1:46399...
[2021-04-15 11:16:43.809] [renderer3] [info] [remote-connection][ExtensionHost][697ce…][reconnect] connecting to 127.0.0.1:46399...
[2021-04-15 11:16:45.186] [renderer3] [info] [remote-connection][Management   ][cd22f…][reconnect] reconnected!
[2021-04-15 11:16:49.799] [renderer3] [info] [remote-connection][ExtensionHost][697ce…][reconnect] reconnected!
[2021-04-15 11:17:05.191] [renderer3] [info] [remote-connection][Management   ][cd22f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-04-15 11:17:05.198] [renderer3] [info] [remote-connection][Management   ][cd22f…][reconnect] waiting for 5 seconds before reconnecting...
[2021-04-15 11:17:10.199] [renderer3] [info] [remote-connection][Management   ][cd22f…][reconnect] resolving connection...
[2021-04-15 11:17:13.805] [renderer3] [info] [remote-connection][ExtensionHost][697ce…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-04-15 11:17:13.805] [renderer3] [info] [remote-connection][ExtensionHost][697ce…][reconnect] waiting for 5 seconds before reconnecting...
[2021-04-15 11:17:18.805] [renderer3] [info] [remote-connection][ExtensionHost][697ce…][reconnect] resolving connection...
[2021-04-15 11:17:25.342] [renderer3] [info] [remote-connection][Management   ][cd22f…][reconnect] connecting to 127.0.0.1:35305...
[2021-04-15 11:17:25.343] [renderer3] [info] [remote-connection][ExtensionHost][697ce…][reconnect] connecting to 127.0.0.1:35305...
[2021-04-15 11:17:26.784] [renderer3] [info] [remote-connection][Management   ][cd22f…][reconnect] reconnected!
[2021-04-15 11:17:44.209] [renderer3] [info] [remote-connection][ExtensionHost][697ce…][reconnect] reconnected!
[2021-04-15 11:17:46.789] [renderer3] [info] [remote-connection][Management   ][cd22f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-04-15 11:17:46.799] [renderer3] [info] [remote-connection][Management   ][cd22f…][reconnect] waiting for 5 seconds before reconnecting...
[2021-04-15 11:17:51.799] [renderer3] [info] [remote-connection][Management   ][cd22f…][reconnect] resolving connection...
[2021-04-15 11:17:55.737] [renderer3] [info] [remote-connection][ExtensionHost][697ce…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-04-15 11:17:55.737] [renderer3] [info] [remote-connection][ExtensionHost][697ce…][reconnect] waiting for 5 seconds before reconnecting...
[2021-04-15 11:18:00.737] [renderer3] [info] [remote-connection][ExtensionHost][697ce…][reconnect] resolving connection...
[2021-04-15 11:18:10.348] [renderer3] [info] [remote-connection][Management   ][cd22f…][reconnect] connecting to 127.0.0.1:45865...
[2021-04-15 11:18:10.348] [renderer3] [info] [remote-connection][ExtensionHost][697ce…][reconnect] connecting to 127.0.0.1:45865...
[2021-04-15 11:18:11.754] [renderer3] [info] [remote-connection][Management   ][cd22f…][reconnect] reconnected!
[2021-04-15 11:18:21.987] [renderer3] [info] [remote-connection][ExtensionHost][697ce…][reconnect] reconnected!
[2021-04-15 11:18:31.759] [renderer3] [info] [remote-connection][Management   ][cd22f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-04-15 11:18:31.765] [renderer3] [info] [remote-connection][Management   ][cd22f…][reconnect] waiting for 5 seconds before reconnecting...
[2021-04-15 11:18:36.765] [renderer3] [info] [remote-connection][Management   ][cd22f…][reconnect] resolving connection...
[2021-04-15 11:18:41.325] [renderer3] [info] [remote-connection][ExtensionHost][697ce…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-04-15 11:18:41.325] [renderer3] [info] [remote-connection][ExtensionHost][697ce…][reconnect] waiting for 5 seconds before reconnecting...
[2021-04-15 11:18:46.086] [renderer3] [error] [remote-connection][Management   ][cd22f…][reconnect] An unknown error occurred while trying to reconnect, since this is an unknown case, it will be treated as a permanent error! Will give up now! Error:
[2021-04-15 11:18:46.086] [renderer3] [error] Error: Too many authentication failures
    at e.resolveAuthority (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:4564:488)
    at async W._resolveAuthorityAgain (file:///usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:5292:119)
[2021-04-15 11:18:46.325] [renderer3] [error] [remote-connection][ExtensionHost][697ce…][reconnect] permanent failure occurred while running the reconnecting loop.
`

**Comment by deepak6422** [comment]
I am able to connect through external terminal without any issue. 
Adding below the remote SSH logs too.
![Screenshot from 2021-04-15 11-30-50](https://user-images.githubusercontent.com/77039531/114821416-268ce300-9dde-11eb-9879-cd983fca0bbb.png)

**Comment by roblourens** [comment]
Could you include the logs as text, and the full log, not just the last few lines
