### ISSUE TITLE
Can not connect to SSH from vscode

### ISSUE THREAD

**Issue by Aleix20** [microsoft/vscode-remote-release#4872]
Hi,
I'm getting this error every time that I try to use SSH on vscode after install all necessary packets.

My console output:
```
[12:36:45.879] Log Level: 2
[12:36:45.884] remote-ssh@0.65.1
[12:36:45.884] win32 x64
[12:36:45.885] SSH Resolver called for "ssh-remote+10.49.0.95", attempt 1
[12:36:45.886] "remote.SSH.useLocalServer": false
[12:36:45.886] "remote.SSH.showLoginTerminal": false
[12:36:45.886] "remote.SSH.remotePlatform": {}
[12:36:45.886] "remote.SSH.sshPath": undefined
[12:36:45.886] "remote.SSH.sshConfigurationFile": undefined
[12:36:45.887] "remote.SSH.useFlock": true
[12:36:45.887] "remote.SSH.lockfilesInTmp": false
[12:36:45.887] "remote.SSH.localServerDownload": auto
[12:36:45.887] "remote.SSH.remoteServerListenOnSocket": false
[12:36:45.887] "remote.SSH.showLoginTerminal": false
[12:36:45.887] "remote.SSH.defaultExtensions": []
[12:36:45.887] SSH Resolver called for host: 10.49.0.95
[12:36:45.887] Setting up SSH remote "10.49.0.95"
[12:36:45.903] Using commit id "08a217c4d27a02a5bcde898fd7981bda5b49391b" and quality "stable" for server
[12:36:45.907] Install and start server if needed
[12:36:51.736] Checking ssh with "ssh -V"
[12:36:51.757] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[12:36:51.760] Running script with connection command: ssh -T -D 61575 "10.49.0.95" bash
[12:36:51.762] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[12:36:51.830] > Bad owner or permissions on C:\\Users\\Aleix/.ssh/config
> ]0;C:\WINDOWS\System32\cmd.exe
[12:36:51.830] Got some output, clearing connection timeout
[12:36:51.836] > El proceso ha intentado escribir en una canalización que no existe.
[12:36:52.109] "install" terminal command done
[12:36:52.109] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exeEl proceso ha intentado escribir en una canalización que no existe.
[12:36:52.109] Received install output: ]0;C:\WINDOWS\System32\cmd.exeEl proceso ha intentado escribir en una canalización que no existe.
[12:36:52.109] Stopped parsing output early. Remaining text: ]0;C:\WINDOWS\System32\cmd.exeEl proceso ha intentado escribir en una canalización que no existe.
[12:36:52.109] Failed to parse remote port from server output
[12:36:52.113] Resolver error: Error: 
	at Function.Create (c:\Users\Aleix\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:64328)
	at Object.t.handleInstallOutput (c:\Users\Aleix\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:63022)
	at q (c:\Users\Aleix\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:296373)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\Aleix\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:294221
	at async Object.t.withShowDetailsEvent (c:\Users\Aleix\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:407055)
	at async Object.t.resolve (c:\Users\Aleix\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:297912)
	at async c:\Users\Aleix\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:127:110485
```

I was looking some similar errors, but any solution worked in my case....Any ideas?

**Comment by Aleix20** [comment]
Solved
