### ISSUE TITLE
Can't connect to remote host if private key doesn't have file extension

### ISSUE THREAD

**Issue by Dealerpriest** [microsoft/vscode-remote-release#4878]
I can't connect to a host if the private key doesn't have a file extension (example: "keyname").
Keeping the exact same configuration except changing the file name to something like "keyname.key" (and of course updating the ssh config for "IdentityFile") makes the connection succeed.

**"about" output in VS Code:**
Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042 (WIN 10)

- Remote OS Version: Ubuntu 20.04 (LTS) x64
- Remote Extension/Connection Type: SSH
- Remote SSH Extension version: v0.65.1

Steps to Reproduce:

1. Try to connect to a host using a private key **without** file extension -> fails
2. Try to connect to the same host using the same private key but **with** a file extension -> success

### When failing:
```
[10:33:33.567] Log Level: 2
[10:33:33.574] remote-ssh@0.65.1
[10:33:33.574] win32 x64
[10:33:33.576] SSH Resolver called for "ssh-remote+XXXXXXXX", attempt 1
[10:33:33.577] "remote.SSH.useLocalServer": false
[10:33:33.577] "remote.SSH.showLoginTerminal": false
[10:33:33.578] "remote.SSH.remotePlatform": {XXXXXXXXXXXX}
[10:33:33.578] "remote.SSH.sshPath": undefined
[10:33:33.578] "remote.SSH.sshConfigurationFile": undefined
[10:33:33.578] "remote.SSH.useFlock": true
[10:33:33.578] "remote.SSH.lockfilesInTmp": false
[10:33:33.578] "remote.SSH.localServerDownload": auto
[10:33:33.579] "remote.SSH.remoteServerListenOnSocket": false
[10:33:33.579] "remote.SSH.showLoginTerminal": false
[10:33:33.579] "remote.SSH.defaultExtensions": []
[10:33:33.579] SSH Resolver called for host: XXXXXXXXXXXX
[10:33:33.579] Setting up SSH remote "XXXXXXXXXX"
[10:33:33.604] Using commit id "3c4e3df9e89829dce27b7b5c24508306b151f30d" and quality "stable" for server
[10:33:33.609] Install and start server if needed
[10:33:36.483] Checking ssh with "ssh -V"
[10:33:36.522] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[10:33:36.529] Running script with connection command: ssh -T -D 50397 "XXXXXXXXXX" bash
[10:33:36.533] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:33:36.900] > warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
> ]0;C:\WINDOWS\System32\cmd.exe
[10:33:36.900] Got some output, clearing connection timeout
[10:33:36.936] > root@XXX.XXX.XXX.XXX: Permission denied (publickey).
[10:33:36.954] > The process tried to write to a nonexistent pipe.
[10:33:37.257] "install" terminal command done
[10:33:37.258] Install terminal quit with output: The process tried to write to a nonexistent pipe.
[10:33:37.258] Received install output: The process tried to write to a nonexistent pipe.
[10:33:37.264] Resolver error: Error: The process tried to write to a nonexistent pipe
	at Function.Offline (c:\Users\XXXXX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:64379)
	at c:\Users\XXXXX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:61923
	at Object.t.handleInstallOutput (c:\Users\XXXXX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:62301)
	at q (c:\Users\XXXXX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:296373)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\XXXXX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:294221
	at async Object.t.withShowDetailsEvent (c:\Users\XXXXX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:407055)
	at async Object.t.resolve (c:\Users\XXXXX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:1:297912)
	at async c:\Users\XXXXX\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.1\out\extension.js:127:110485
[10:33:37.271] ------




[10:35:05.054] ConfigFileWatcher: start watching file:///c%3A/Users/XXXXX/.ssh/config
[10:35:05.054] ConfigFileWatcher: adding save listener
[10:35:05.054] ConfigFileWatcher: adding close listener
[10:35:53.296] ConfigFileWatcher: saving vscode-userdata:/c%3A/Users/XXXXX/AppData/Roaming/Code/User/settings.json
[10:35:53.298] ConfigFileWatcher: closing vscode-userdata:/c%3A/Users/XXXXX/AppData/Roaming/Code/User/settings.json
[10:50:23.952] ConfigFileWatcher: start watching file:///c%3A/Users/XXXXX/.ssh/config
[10:50:37.949] ConfigFileWatcher: saving file:///c%3A/Users/XXXXX/.ssh/config
[10:50:37.949] ConfigFileWatcher: firing change event for file:///c%3A/Users/XXXXX/.ssh/config
```

### When successful
```
[10:58:07.435] Log Level: 2
[10:58:07.441] remote-ssh@0.65.1
[10:58:07.441] win32 x64
[10:58:07.443] SSH Resolver called for "ssh-remote+XXXXX", attempt 1
[10:58:07.443] "remote.SSH.useLocalServer": false
[10:58:07.444] "remote.SSH.showLoginTerminal": false
[10:58:07.444] "remote.SSH.remotePlatform": {XXXXX}
[10:58:07.444] "remote.SSH.sshPath": undefined
[10:58:07.444] "remote.SSH.sshConfigurationFile": undefined
[10:58:07.445] "remote.SSH.useFlock": true
[10:58:07.445] "remote.SSH.lockfilesInTmp": false
[10:58:07.445] "remote.SSH.localServerDownload": auto
[10:58:07.445] "remote.SSH.remoteServerListenOnSocket": false
[10:58:07.445] "remote.SSH.showLoginTerminal": false
[10:58:07.445] "remote.SSH.defaultExtensions": []
[10:58:07.446] SSH Resolver called for host: XXXXXXXX
[10:58:07.446] Setting up SSH remote "XXXXXXXX"
[10:58:07.470] Using commit id "3c4e3df9e89829dce27b7b5c24508306b151f30d" and quality "stable" for server
[10:58:07.474] Install and start server if needed
[10:58:07.483] Checking ssh with "ssh -V"
[10:58:07.534] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[10:58:07.541] Running script with connection command: ssh -T -D 50642 "XXXXXXXX" bash
[10:58:07.546] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:58:08.642] > 40142d819dc0: running
> ]0;C:\WINDOWS\System32\cmd.exe
[10:58:08.643] Got some output, clearing connection timeout
[10:58:08.681] > Acquiring lock on /root/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f
> 30d/vscode-remote-lock.root.3c4e3df9e89829dce27b7b5c24508306b151f30d
[10:58:08.709] > Found existing installation at /root/.vscode-server/bin/3c4e3df9e89829dce27b7b5c
> 24508306b151f30d...
> Checking /root/.vscode-server/.3c4e3df9e89829dce27b7b5c24508306b151f30d.log and 
> /root/.vscode-server/.3c4e3df9e89829dce27b7b5c24508306b151f30d.pid for a running
>  server
> Looking for server with pid: 1410
[10:58:08.722] > Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
[10:58:08.737] > Checking server status on port 36845 with wget
[10:58:08.747] > 40142d819dc0: start
> SSH_AUTH_SOCK==/tmp/ssh-YEQJS0MUX1/agent.1535==
> DISPLAY====
> webUiAccessToken====
> listeningOn==36845==
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/0==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> connectionToken==1111a1a1-1111-1aa1-1aa1-a11aa11111a1==
> 40142d819dc0: end
[10:58:08.748] Received install output: 
SSH_AUTH_SOCK==/tmp/ssh-YEQJS0MUX1/agent.1535==
DISPLAY====
webUiAccessToken====
listeningOn==36845==
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/0==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==1111a1a1-1111-1aa1-1aa1-a11aa11111a1==

[10:58:08.749] Remote server is listening on 36845
[10:58:08.749] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":36845},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"/tmp/ssh-YEQJS0MUX1/agent.1535","display":"","tmpDir":"/run/user/0","platform":"linux","connectionToken":"1111a1a1-1111-1aa1-1aa1-a11aa11111a1"},"installUnpackCode":""}
[10:58:08.752] Starting forwarding server. localPort 50645 -> socksPort 50642 -> remotePort 36845
[10:58:08.753] Forwarding server listening on 50645
[10:58:08.753] Waiting for ssh tunnel to be ready
[10:58:08.754] [Forwarding server 50645] Got connection 0
[10:58:08.756] Tunneled 36845 to local port 50645
[10:58:08.756] Resolved "ssh-remote+XXXXXXXX" to "127.0.0.1:50645"
[10:58:08.756] Updating $SSH_AUTH_SOCK: ln -f -s "/tmp/ssh-YEQJS0MUX1/agent.1535" "/run/user/0/vscode-ssh-auth-sock-293277554"
[10:58:08.757] Using cwd: vscode-remote://ssh-remote%2BXXXXXXXX/
[10:58:08.757] Remote extension host environment: {"SSH_AUTH_SOCK":"/run/user/0/vscode-ssh-auth-sock-293277554"}
[10:58:08.768] ------




[10:58:08.804] [Forwarding server 50645] Got connection 1
[10:58:08.879] [Forwarding server 50645] Got connection 2
[10:58:10.433] "Update SSH_AUTH_SOCK" terminal command done
```

**Comment by roblourens** [comment]
> root@XXX.XXX.XXX.XXX: Permission denied (publickey).

VS Code is not searching for your keys, it's all ssh. Does this work with ssh in an external terminal?

**Comment by Dealerpriest** [comment]
Yes. Works fine to ssh into the remote server using any of my usual terminals such as powershell or bash with git.

**Comment by roblourens** [comment]
My guess is that it's not actually using your ssh config file and the problem comes from changing the key from a default key path to something else, is that possible?

If you set `"remote.SSH.logLevel": "trace"` ssh will include some logs about where the config was loaded from which might help you troubleshoot.

**Comment by Dealerpriest** [comment]
I have now verified that this only happens for me on digitalocean (of the two hosting services I've tried). It's very peculiar.
Reproducable problem for me:
- Be on windows.
- Set up a droplet on digital ocean. Add the key (without extension) and relevant config to your ssh-config. Try to connect. Doesn't work.
- Rename the key to have a three-letter file extension. Update the ssh-config to reflect this. Try to connect. Works.

**Comment by Dealerpriest** [comment]
Here's the log output after setting log level to trace:
```
[10:43:21.345] Log Level: 1
[10:43:21.351] remote-ssh@0.65.4
[10:43:21.351] win32 x64
[10:43:21.352] SSH Resolver called for "ssh-remote+XXXXXXXXX", attempt 1
[10:43:21.353] "remote.SSH.useLocalServer": false
[10:43:21.353] "remote.SSH.showLoginTerminal": false
[10:43:21.354] "remote.SSH.remotePlatform": {XXXXXXXXXXXXXXXXXXXXXX}
[10:43:21.354] "remote.SSH.path": undefined
[10:43:21.354] "remote.SSH.configFile": undefined
[10:43:21.354] "remote.SSH.useFlock": true
[10:43:21.354] "remote.SSH.lockfilesInTmp": false
[10:43:21.354] "remote.SSH.localServerDownload": auto
[10:43:21.355] "remote.SSH.remoteServerListenOnSocket": false
[10:43:21.355] "remote.SSH.showLoginTerminal": false
[10:43:21.355] "remote.SSH.defaultExtensions": []
[10:43:21.355] "remote.SSH.loglevel": 1
[10:43:21.355] SSH Resolver called for host: XXXXXXXXXXXXXXXX
[10:43:21.355] Setting up SSH remote "XXXXXXXXXXXXXXXXX"
[10:43:21.374] Using commit id "3c4e3df9e89829dce27b7b5c24508306b151f30d" and quality "stable" for server
[10:43:21.378] Install and start server if needed
[10:43:21.388] Checking ssh with "ssh -V"
[10:43:21.438] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[10:43:21.445] Running script with connection command: ssh -T -D 53839 "XXXXXXXXXXXXXXXX" bash
[10:43:21.448] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:43:21.864] "install" terminal received data: "[2J[m[Hwarning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
]0;C:\WINDOWS\System32\cmd.exe[?25h"
[10:43:21.864] Got some output, clearing connection timeout
[10:43:21.896] "install" terminal received data: "root@XXX.XXX.XXX.XXX: Permission denied (publickey)."
[10:43:21.911] "install" terminal received data: "The process tried to write to a nonexistent pipe."
[10:43:22.217] "install" terminal command done
[10:43:22.217] Install terminal quit with output: The process tried to write to a nonexistent pipe.
[10:43:22.217] Received install output: The process tried to write to a nonexistent pipe.
[10:43:22.218] Stopped parsing output early. Remaining text: The process tried to write to a nonexistent pipe.
[10:43:22.222] Resolver error: Error: The process tried to write to a nonexistent pipe
	at Function.Offline (c:\Users\gunhaxxor\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:64692)
	at c:\Users\gunhaxxor\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:62242
	at Object.t.handleInstallOutput (c:\Users\gunhaxxor\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:62620)
	at Object.t.tryInstall (c:\Users\gunhaxxor\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:413984)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\gunhaxxor\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:294518
	at async Object.t.withShowDetailsEvent (c:\Users\gunhaxxor\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:405329)
	at async Object.t.resolve (c:\Users\gunhaxxor\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:295639)
	at async c:\Users\gunhaxxor\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:127:110530
[10:43:22.226] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"OfflineError","exitCodeLabel":""},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":866,"timing.preSshTime":96,"timing.scriptTime":769}}
[10:43:22.229] ------
```

**Comment by roblourens** [comment]
Sorry, it only sets the verbose flag on SSH when you have `"remote.SSH.useLocalServer": true`. You could try that too.
