### ISSUE TITLE
Remote ssh: extensions fail to load, no language support

### ISSUE THREAD

**Issue by avivey** [microsoft/vscode-remote-release#4890]
Issue Type: <b>Bug</b>

When connecting to remote SSH session:
- All files identified as "plain text"; "Select Language" shows only `log`, `plaintext`, `scminput`.
- Extensions View just spins forever when trying to show "installed" extensions. 
- Searching marketplace from extensions view works.
- Everything appears to work normally in local mode.

Everything was fine for a day or two after upgrading to 1.55.2, then started breaking today.

I've tried `rm -rf ~/.vscode-server` and restarting vscode - no change.
Also tried `Extension Bisect`, it only restarted once and gave up.

Extension version: 0.65.3
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19043
Remote OS version: Linux x64 5.4.0-71-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz (8 x 3702)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.94GB (12.58GB free)|
|Process Argv|--crash-reporter-id 8812d33d-851c-481f-b969-13626b21b235|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: localhost|
|OS|Linux x64 5.4.0-71-generic|
|CPUs|Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz (1 x 3702)|
|Memory (System)|7.68GB (5.15GB free)|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30283811
openwslfolder:30282073
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953
pythondataviewer:30285071
vscus158:30286553

```
</details>

Logs:
"Log (Extension Host)"
```
[2021-04-15 20:12:30.756] [exthost] [info] extension host started
[2021-04-15 20:12:30.776] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-ssh {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-ssh","_lower":"ms-vscode-remote.remote-ssh"},"activationEvent":"onResolveRemoteAuthority:ssh-remote"}
[2021-04-15 20:12:30.776] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Aviv/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.3/out/extension
```
"Log (Window)"
```
[2021-04-15 19:51:40.021] [renderer1] [warning] Settings pattern "keyboard.*" doesn't match any settings
[2021-04-15 19:51:42.469] [renderer1] [error] Invalid regular expression: /*/: Nothing to repeat: SyntaxError: Invalid regular expression: /*/: Nothing to repeat
    at RegExp (<anonymous>)
    at v.readSetting (file:///C:/Users/Aviv/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1902:18434)
    at v.updateAttributes (file:///C:/Users/Aviv/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1902:17043)
    at new v (file:///C:/Users/Aviv/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1902:16979)
    at new C (file:///C:/Users/Aviv/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1902:20198)
    at new E (file:///C:/Users/Aviv/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1902:28877)
    at w._createInstance (file:///C:/Users/Aviv/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:624:15342)
    at file:///C:/Users/Aviv/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:624:17522
    at B._executor (file:///C:/Users/Aviv/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:18723)
    at file:///C:/Users/Aviv/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:18816
[2021-04-15 19:51:48.678] [renderer1] [warning] Settings pattern "keyboard.*" doesn't match any settings
[2021-04-15 20:12:13.563] [renderer1] [warning] extension BISECT active [["aaron-bond.better-comments",true],["coenraads.bracket-pair-colorizer-2",true],["editorconfig.editorconfig",true],["ms-vscode-remote.remote-ssh",true],["ms-vscode-remote.remote-ssh-edit",true],["oderwat.indent-rainbow",true],["philhindle.errorlens",true],["usernamehw.errorlens",true],["zhengxiaoyao0716.intelligence-change-case",true]]
```

**Comment by roblourens** [comment]
Please share the logs from Remote-SSH and "Log (Remote extension host)"

**Comment by avivey** [comment]
I don't see that one...
I have:
![image](https://user-images.githubusercontent.com/1530242/114925610-ff62ff80-9e37-11eb-8193-fa3413781757.png)

<details>
<summary>Remote - SSH</summary>

```
[22:07:02.112] Log Level: 2
[22:07:02.119] remote-ssh@0.65.3
[22:07:02.120] win32 x64
[22:07:02.121] SSH Resolver called for "ssh-remote+localhost", attempt 1
[22:07:02.122] "remote.SSH.useLocalServer": false
[22:07:02.122] "remote.SSH.showLoginTerminal": false
[22:07:02.122] "remote.SSH.remotePlatform": {"localhost":"linux"}
[22:07:02.123] "remote.SSH.path": undefined
[22:07:02.123] "remote.SSH.sshConfigurationFile": undefined
[22:07:02.123] "remote.SSH.useFlock": true
[22:07:02.124] "remote.SSH.lockfilesInTmp": false
[22:07:02.124] "remote.SSH.localServerDownload": auto
[22:07:02.124] "remote.SSH.remoteServerListenOnSocket": false
[22:07:02.125] "remote.SSH.showLoginTerminal": false
[22:07:02.125] "remote.SSH.defaultExtensions": []
[22:07:02.125] "remote.SSH.loglevel": 2
[22:07:02.126] SSH Resolver called for host: localhost
[22:07:02.126] Setting up SSH remote "localhost"
[22:07:02.186] Using commit id "3c4e3df9e89829dce27b7b5c24508306b151f30d" and quality "stable" for server
[22:07:02.193] Install and start server if needed
[22:07:02.200] Checking ssh with "ssh -V"
[22:07:02.235] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[22:07:02.240] Running script with connection command: ssh -T -D 61664 localhost bash
[22:07:02.243] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[22:07:05.873] > 27ad7e2a3e45: running
> ]0;C:\WINDOWS\System32\cmd.exe
[22:07:05.874] Got some output, clearing connection timeout
[22:07:05.938] > Acquiring lock on /home/avivey/.vscode-server/bin/3c4e3df9e89829dce27b7b5c245083
> 06b151f30d/vscode-remote-lock.avivey.3c4e3df9e89829dce27b7b5c24508306b151f30d   
[22:07:05.955] > Found existing installation at /home/avivey/.vscode-server/bin/3c4e3df9e89829dce
> 27b7b5c24508306b151f30d...
> Checking /home/avivey/.vscode-server/.3c4e3df9e89829dce27b7b5c24508306b151f30d.l
> og and /home/avivey/.vscode-server/.3c4e3df9e89829dce27b7b5c24508306b151f30d.pid
>  for a running server
[22:07:05.964] > Looking for server with pid: 25195
[22:07:05.987] > Starting server with command... /home/avivey/.vscode-server/bin/3c4e3df9e89829dc
> e27b7b5c24508306b151f30d/server.sh --start-server --host=127.0.0.1 --enable-remo
> te-auto-shutdown  --port=0  &> "/home/avivey/.vscode-server/.3c4e3df9e89829dce27
> b7b5c24508306b151f30d.log" < /dev/null
> printenv:
>     SHELL=/bin/bash        
>     LC_ADDRESS=en_US.UTF-8 
>     LC_NAME=en_US.UTF-8    
>     LC_MONETARY=en_US.UTF-8
>     PWD=/home/avivey       
>     LOGNAME=avivey
>     XDG_SESSION_TYPE=tty   
>     MOTD_SHOWN=pam
>     HOME=/home/avivey      
>     LANG=en_US.UTF-8       
>     LC_PAPER=en_US.UTF-8
>     VSCODE_AGENT_FOLDER=/home/avivey/.vscode-server
>     SSH_CONNECTION=10.0.2.2 61682 10.0.2.15 22
>     XDG_SESSION_CLASS=user
>     LC_IDENTIFICATION=en_US.UTF-8
>     USER=avivey
[22:07:05.989] > 
>     SHLVL=0
>     LC_TELEPHONE=en_US.UTF-8
>     LC_MEASUREMENT=en_US.UTF-8
>     XDG_SESSION_ID=94
>     XDG_RUNTIME_DIR=/run/user/1000
>     SSH_CLIENT=10.0.2.2 61682 22
>     LC_TIME=en_US.UTF-8
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
> :/usr/local/games:/snap/bin
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
>     LC_NUMERIC=en_US.UTF-8
>     _=/usr/bin/printenv
> Spawned remote server: 26417
[22:07:06.000] > 
> Waiting for server log...
[22:07:06.009] > 
[22:07:06.055] > Waiting for server log...
[22:07:06.117] > Waiting for server log...
[22:07:06.176] > Waiting for server log...
[22:07:06.291] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,  
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
> 27ad7e2a3e45: start
> SSH_AUTH_SOCK====
> DISPLAY====
> webUiAccessToken====
> listeningOn==33489==
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==255==
> connectionToken==a1a1aaa1-111a-11aa-aa1a-1aa11a11aaaa==
> 27ad7e2a3e45: end
[22:07:06.291] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==33489==
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==255==
connectionToken==a1a1aaa1-111a-11aa-aa1a-1aa11a11aaaa==

[22:07:06.291] Remote server is listening on 33489
[22:07:06.292] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":33489},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/1000","platform":"linux","connectionToken":"a1a1aaa1-111a-11aa-aa1a-1aa11a11aaaa"},"serverStartTime":255,"installUnpackCode":""}
[22:07:06.293] Starting forwarding server. localPort 61683 -> socksPort 61664 -> remotePort 33489
[22:07:06.294] Forwarding server listening on 61683
[22:07:06.294] Waiting for ssh tunnel to be ready
[22:07:06.295] [Forwarding server 61683] Got connection 0
[22:07:06.297] Tunneled 33489 to local port 61683
[22:07:06.297] Resolved "ssh-remote+localhost" to "127.0.0.1:61683"
[22:07:06.311] ------




[22:07:06.332] [Forwarding server 61683] Got connection 1
[22:07:06.751] [Forwarding server 61683] Got connection 2
```
</details>

"Extensions" (empty)

<details>
<summary>Log (Remote Server)</summary>

```
[2021-04-15 12:07:06.792] [remoteagent] [info] 

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


[2021-04-15 12:07:06.793] [remoteagent] [info] Extension host agent started.
[2021-04-15 12:07:07.240] [remoteagent] [info] [127.0.0.1][4471b046][ExtensionHostConnection] New connection established.
[2021-04-15 12:07:07.243] [remoteagent] [info] [127.0.0.1][cff2f7a9][ManagementConnection] New connection established.
[2021-04-15 12:07:08.029] [remoteagent] [info] [127.0.0.1][4471b046][ExtensionHostConnection] <26514> Launched Extension Host Process.
```
</details>

<details><summary>Log (Shared)</summary>

```
[2021-04-15 22:07:42.385] [sharedprocess] [info] Starting to clean up unused language packs.
```
</details>

<details><summary>Log (Main)</summary>

```
[2021-04-15 22:07:00.396] [main] [info] update#setState idle
[2021-04-15 22:07:30.397] [main] [info] update#setState checking for updates
[2021-04-15 22:07:30.473] [main] [info] update#setState idle
```
</details>

and "Log (Extension Host)" and "Log (Window)" (above).

I'm also seeing that the "Opening Remote..." is spinning: 
![image](https://user-images.githubusercontent.com/1530242/114925563-ef4b2000-9e37-11eb-9f77-e0a3972c8501.png)

**Comment by avivey** [comment]
But I do have `~/.vscode-server/.3c4e3df9e89829dce27b7b5c24508306b151f30d.log` file:
```


*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*

Extension host agent listening on 33489

[12:07:06] Extension host agent started.
[12:07:07] [127.0.0.1][4471b046][ExtensionHostConnection] New connection established.
[12:07:07] [127.0.0.1][cff2f7a9][ManagementConnection] New connection established.
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
[IPC Library: Pty Host]  INFO Listing 0 persistent terminals, 0 total terminals
[12:07:08] [127.0.0.1][4471b046][ExtensionHostConnection] <26514> Launched Extension Host Process.
```

**Comment by roblourens** [comment]
I'm not sure whether this error is the root issue, but it is suspicious: `Invalid regular expression: /*/: Nothing to repeat: SyntaxError: Invalid regular expression: /*/: Nothing to repeat`. This is coming from RemoteExplorerService, can you check it out @alexr00?

**Comment by alexr00** [comment]
@roblourens I found where the error is coming from. It's a bad user setting (`remote.portsAttributes`). I've added a try-catch around the offending code since it's always possible that we get a bad regex in the setting.

**Comment by alexr00** [comment]
@avivey I don't think that the bad setting could cause all the behavior that you're seeing, but just to be sure, can you remove any `remote.portsAttributes` settings that you have and try again?

**Comment by alexr00** [comment]
Oh wow. Actually, this does cause all that bad behavior. Fixed with https://github.com/microsoft/vscode/commit/5ef190e98a460c4ab33086a805c25645eef99804

**Comment by alexr00** [comment]
To verify, add this setting then try to connect to a remote. If the remote indicator keeps spinning forever then you have reproed the bug.
```json
  "remote.portsAttributes": {
    "*": {
      "onAutoForward": "ignore"
    }
  },
```

**Comment by avivey** [comment]
Hi, yes!

I've added this to my config (and forgot about it :/):
```
   "remote.portsAttributes": {
        "*": {
            "onAutoForward": "notify"
        }
    },
}```

Removing it and re-starting makes the issue go away.

Thanks for the investigation!
