### ISSUE TITLE
I want to have the possibility to open the terminal ssh in REMOTE EXPLORER.

### ISSUE THREAD

**Issue by AlexandroGonSan** [microsoft/vscode-remote-release#4908]
Issue Type: <b>Feature request.</b>

![i.imgur.com/fd8ZMsc](https://i.imgur.com/fd8ZMsc.gif)

* Similar issues verificados!
* Similar issues checked!
![i.imgur.com/OF6lxxD](https://i.imgur.com/OF6lxxD.png)

TO MSCODE: Eu quero ter a possibilidade de abrir o terminal ssh in REMOTE EXPLORER. https://i.imgur.com/mirov2V.png

Extension version: 2021.4.26820
VS Code version: Code - Insiders 1.56.0-insider (ce791d27dc9889a392f4d29abefe9c53eb0b5129, 2021-04-16T11:25:09.908Z)
OS version: Linux x64 4.19.0-12-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Pentium(R) Dual-Core CPU       T4300  @ 2.10GHz (2 x 2057)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|1.91GB (0.07GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 916cefe7-d422-4e5e-b1b2-3cd8fe832aad|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|lightdm-xsession|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|lightdm-xsession|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
vstes627:30244334
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
wslfolderdoc:30278405
vspre833:30267464
pythonptprofiler:30281269
vsdfh931:30280409
vscnewfiletextcf:30288478
vshan820cf:30276953
pythondataviewer:30285072
vscus158cf:30286554
vscgsv2:30286872

```

</details>

**Comment by bamurtaugh** [comment]
Hi @AlexandroGonSan - I want to make sure I understand the issue here. Are you looking for a button/option to create a new terminal instance for different SSH targets from the Remote Explorer? Is there a reason why the integrated terminal isn't sufficient?

**Comment by AlexandroGonSan** [comment]
Eu preciso abrir no terminal integrado um shell para a minha conexão remota em um clique?

Do I need to open in the integrated terminal a shell for my remote connection in one click?

**Comment by bamurtaugh** [comment]
The integrated terminal will provide a terminal for your current Remote-SSH connection automatically. Are you looking for something beyond this?

**Comment by AlexandroGonSan** [comment]
Eu cliquei em Connect to Host in New Window e ocorreu esse erro.

I clicked Connect to Host in New Window and this error occurred.

![simplescreenrecorder-2021-04-21 (2)](https://user-images.githubusercontent.com/38570195/115575012-271af300-a290-11eb-80e0-0d3f3213e146.gif)

 - RECORDING ERROR
```
[10:53:21.186] Log Level: 2
[10:53:21.209] remote-ssh-nightly@2021.4.28260
[10:53:21.209] linux x64
[10:53:21.222] SSH Resolver called for "ssh-remote+35.202.212.200", attempt 1
[10:53:21.250] "remote.SSH.useLocalServer": true
[10:53:21.251] "remote.SSH.path": undefined
[10:53:21.252] "remote.SSH.configFile": undefined
[10:53:21.252] "remote.SSH.useFlock": true
[10:53:21.253] "remote.SSH.lockfilesInTmp": false
[10:53:21.258] "remote.SSH.localServerDownload": auto
[10:53:21.259] "remote.SSH.remoteServerListenOnSocket": false
[10:53:21.259] "remote.SSH.showLoginTerminal": false
[10:53:21.259] "remote.SSH.defaultExtensions": []
[10:53:21.260] "remote.SSH.loglevel": 2
[10:53:21.261] SSH Resolver called for host: 35.202.212.200
[10:53:21.262] Setting up SSH remote "35.202.212.200"
[10:53:21.284] Acquiring local install lock: /tmp/vscode-remote-ssh-35.202.212.200-install.lock
[10:53:21.369] Looking for existing server data file at /home/alexandrogonsan/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh-nightly/vscode-ssh-host-35.202.212.200-ce791d27dc9889a392f4d29abefe9c53eb0b5129-2021.4.28260/data.json
[10:53:21.373] Using commit id "ce791d27dc9889a392f4d29abefe9c53eb0b5129" and quality "insider" for server
[10:53:21.384] Install and start server if needed
[10:53:21.440] PATH: /home/alexandrogonsan/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/go/bin
[10:53:21.442] Checking ssh with "ssh -V"
[10:53:21.751] > OpenSSH_7.9p1 Debian-10+deb10u2, OpenSSL 1.1.1d  10 Sep 2019

[10:53:21.767] askpass server listening on /run/user/1000/vscode-ssh-askpass-c2a2f7d765750a6f61a4322c1c17d8e37e425088.sock
[10:53:21.773] Spawning local server with {"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-67117eb25d0f5786da87b4f6f2fd850614a3701a.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","36483","-o","ConnectTimeout=15","35.202.212.200"],"dataFilePath":"/home/alexandrogonsan/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh-nightly/vscode-ssh-host-35.202.212.200-ce791d27dc9889a392f4d29abefe9c53eb0b5129-2021.4.28260/data.json"}
[10:53:21.773] Local server env: {"DISPLAY":":0.0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code-insiders/code-insiders","VSCODE_SSH_ASKPASS_MAIN":"/home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-c2a2f7d765750a6f61a4322c1c17d8e37e425088.sock"}
[10:53:21.789] Spawned 19787
[10:53:22.296] Server delay-shutdown request failed: connect ENOENT /run/user/1000/vscode-ssh-askpass-67117eb25d0f5786da87b4f6f2fd850614a3701a.sock
[10:53:23.444] > local-server> Spawned ssh: 19795
[10:53:23.495] stderr> OpenSSH_7.9p1 Debian-10+deb10u2, OpenSSL 1.1.1d  10 Sep 2019
[10:53:24.651] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:DiWIofSi86wypeBSu8/np/hHO+i+Z8IW1gxTROjSQXY
[10:53:25.806] stderr> Authenticated to 35.202.212.200 ([35.202.212.200]:22).
[10:53:26.494] > Linux google 4.19.0-13-cloud-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64
> 
> The programs included with the Debian GNU/Linux system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
> permitted by applicable law.
[10:53:26.709] > ready: d84218c80b00
[10:53:26.939] > Linux 4.19.0-13-cloud-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28)
[10:53:26.940] Platform: linux
[10:53:27.385] > d84218c80b00: running
[10:53:27.388] > Creating the server install dir failed...
> d84218c80b00: start
> exitCode==34==
> listeningOn====
> osReleaseId====
> arch====
> tmpDir==/run/user/1000==
> platform====
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> d84218c80b00: end
[10:53:27.389] Received install output: 
exitCode==34==
listeningOn====
osReleaseId====
arch====
tmpDir==/run/user/1000==
platform====
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[10:53:27.394] Failed to parse remote port from server output
[10:53:27.397] Terminating local server
[10:53:27.426] Resolver error: Error: 
	at Function.Create (/home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/extension.js:1:64641)
	at Object.t.handleInstallOutput (/home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/extension.js:1:63284)
	at Object.e [as tryInstallWithLocalServer] (/home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/extension.js:1:386419)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async /home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/extension.js:1:294035
	at async Object.t.withShowDetailsEvent (/home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/extension.js:1:405329)
	at async /home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/extension.js:1:384890
	at async E (/home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/extension.js:1:381658)
	at async Object.t.resolveWithLocalServer (/home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/extension.js:1:384517)
	at async Object.t.resolve (/home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/extension.js:1:295505)
	at async /home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/extension.js:127:110530
[10:53:27.457] ------




[10:53:27.475] Local server exit: 15

```

 - FIRST ERROR
```
[10:41:06.744] Log Level: 2
[10:41:06.771] remote-ssh-nightly@2021.4.28260
[10:41:06.772] linux x64
[10:41:06.781] SSH Resolver called for "ssh-remote+35.202.212.200", attempt 1
[10:41:06.785] "remote.SSH.useLocalServer": true
[10:41:06.787] "remote.SSH.path": undefined
[10:41:06.787] "remote.SSH.configFile": undefined
[10:41:06.788] "remote.SSH.useFlock": true
[10:41:06.788] "remote.SSH.lockfilesInTmp": false
[10:41:06.789] "remote.SSH.localServerDownload": auto
[10:41:06.790] "remote.SSH.remoteServerListenOnSocket": false
[10:41:06.791] "remote.SSH.showLoginTerminal": false
[10:41:06.793] "remote.SSH.defaultExtensions": []
[10:41:06.793] "remote.SSH.loglevel": 2
[10:41:06.796] SSH Resolver called for host: 35.202.212.200
[10:41:06.797] Setting up SSH remote "35.202.212.200"
[10:41:06.875] Acquiring local install lock: /tmp/vscode-remote-ssh-35.202.212.200-install.lock
[10:41:06.908] Looking for existing server data file at /home/alexandrogonsan/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh-nightly/vscode-ssh-host-35.202.212.200-ce791d27dc9889a392f4d29abefe9c53eb0b5129-2021.4.28260/data.json
[10:41:06.963] Using commit id "ce791d27dc9889a392f4d29abefe9c53eb0b5129" and quality "insider" for server
[10:41:06.983] Install and start server if needed
[10:41:07.003] PATH: /home/alexandrogonsan/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/go/bin
[10:41:07.004] Checking ssh with "ssh -V"
[10:41:07.265] > OpenSSH_7.9p1 Debian-10+deb10u2, OpenSSL 1.1.1d  10 Sep 2019

[10:41:07.284] askpass server listening on /run/user/1000/vscode-ssh-askpass-06318bc441efa702721e6c48c04a05cc46d6338a.sock
[10:41:07.285] Spawning local server with {"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-bee422e8699174ffa4c850bb629180e677f7fe67.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","35553","-o","ConnectTimeout=15","35.202.212.200"],"dataFilePath":"/home/alexandrogonsan/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh-nightly/vscode-ssh-host-35.202.212.200-ce791d27dc9889a392f4d29abefe9c53eb0b5129-2021.4.28260/data.json"}
[10:41:07.286] Local server env: {"DISPLAY":":0.0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code-insiders/code-insiders","VSCODE_SSH_ASKPASS_MAIN":"/home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-06318bc441efa702721e6c48c04a05cc46d6338a.sock"}
[10:41:07.301] Spawned 19219
[10:41:08.647] Server delay-shutdown request failed: connect ENOENT /run/user/1000/vscode-ssh-askpass-bee422e8699174ffa4c850bb629180e677f7fe67.sock
[10:41:09.822] > local-server> Spawned ssh: 19227
[10:41:09.869] stderr> OpenSSH_7.9p1 Debian-10+deb10u2, OpenSSL 1.1.1d  10 Sep 2019
[10:41:11.016] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:DiWIofSi86wypeBSu8/np/hHO+i+Z8IW1gxTROjSQXY
[10:41:12.174] stderr> Authenticated to 35.202.212.200 ([35.202.212.200]:22).
[10:41:13.135] > Linux google 4.19.0-13-cloud-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64
> 
> The programs included with the Debian GNU/Linux system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
> permitted by applicable law.
[10:41:13.350] > ready: ed148a108138
[10:41:13.569] > Linux 4.19.0-13-cloud-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28)
[10:41:13.578] Platform: linux
[10:41:14.027] > ed148a108138: running
[10:41:14.063] stderr> mkdir: cannot create directory ‘/home/alexandrogonsan/.vscode-server-insiders/bin/ce791d27dc9889a392f4d29abefe9c53eb0b5129’: No space left on device
[10:41:14.064] > Creating the server install dir failed...
> ed148a108138: start
> exitCode==34==
> listeningOn====
> osReleaseId====
> arch====
> tmpDir==/run/user/1000==
> platform====
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> ed148a108138: end
[10:41:14.065] Received install output: 
exitCode==34==
listeningOn====
osReleaseId====
arch====
tmpDir==/run/user/1000==
platform====
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[10:41:14.077] Failed to parse remote port from server output
[10:41:14.085] Terminating local server
[10:41:14.139] Resolver error: Error: 
	at Function.Create (/home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/extension.js:1:64641)
	at Object.t.handleInstallOutput (/home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/extension.js:1:63284)
	at Object.e [as tryInstallWithLocalServer] (/home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/extension.js:1:386419)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async /home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/extension.js:1:294035
	at async Object.t.withShowDetailsEvent (/home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/extension.js:1:405329)
	at async /home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/extension.js:1:384890
	at async E (/home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/extension.js:1:381658)
	at async Object.t.resolveWithLocalServer (/home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/extension.js:1:384517)
	at async Object.t.resolve (/home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/extension.js:1:295505)
	at async /home/alexandrogonsan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.28260/out/extension.js:127:110530
[10:41:14.187] ------




[10:41:14.195] Local server exit: 15
```

**Comment by bamurtaugh** [comment]
@AlexandroGonSan I interpreted your first post to be a request for a new feature - did I misunderstand, and this thread has been a bug report? Or is this latest comment a new bug you're experiencing? If it's the latter (a new bug unrelated to the initial feature request), can you please open a new issue with the bug so that we can focus the discussion in this thread to the feature request?

**Comment by AlexandroGonSan** [comment]
[pt-br][Original]

Sim, foi um novo bug que eu encontrei. Abrir um novo issue, muito obrigado!

[en][Bing Translate]

Yes, it was a new bug I found. Open a new issue, thank you very much!

**Comment by bamurtaugh** [comment]
Thank you! Also, if you have any insight into my [question above](https://github.com/microsoft/vscode-remote-release/issues/4908#issuecomment-823467858), that'd be great.

**Comment by AlexandroGonSan** [comment]
[pt-br][Original]

Seria interessante eu poder abrir um terminal no terminal integrado para um ssh target sem abrir uma nova ou substituir a janela atual para a conexão.

[en][Bing Translate]

It would be interesting for me to be able to open a terminal in the integrated terminal for a ssh target without opening a new one or replacing the current window for the connection.

**Comment by bamurtaugh** [comment]
cc @roblourens if this sounds in/out of scope. 

This request sounds along the lines of https://github.com/microsoft/vscode-remote-release/issues/585 and https://github.com/microsoft/vscode/issues/101200, except within the integrated terminal and not looking to open a new VS Code instance.

**Comment by roblourens** [comment]
I interpret this as either one of those issues, or you want a way to open a terminal connected to your remote with ssh without opening a full ssh window. We have https://github.com/microsoft/vscode-remote-release/issues/4700 for that request, you can also just use the `ssh` command in the terminal yourself.
