### ISSUE TITLE
SSH fails to connect: Connecting was canceled

### ISSUE THREAD

**Issue by jjlin** [microsoft/vscode-remote-release#4909]
(This is mostly a duplicate of #2788, but I couldn't add anything there since that issue is currently locked except to existing collaborators.)

- VS Code Version: 1.55.2
- Remote Extension/Connection Type: SSH
- Logs:
```
[17:15:32.870] Log Level: 2
[17:15:32.875] remote-ssh@0.65.4
[17:15:32.875] win32 x64
[17:15:32.876] SSH Resolver called for "ssh-remote+my-host", attempt 1
[17:15:32.876] "remote.SSH.useLocalServer": false
[17:15:32.876] "remote.SSH.showLoginTerminal": false
[17:15:32.876] "remote.SSH.remotePlatform": {}
[17:15:32.876] "remote.SSH.path": undefined
[17:15:32.876] "remote.SSH.configFile": undefined
[17:15:32.877] "remote.SSH.useFlock": true
[17:15:32.877] "remote.SSH.lockfilesInTmp": false
[17:15:32.877] "remote.SSH.localServerDownload": auto
[17:15:32.877] "remote.SSH.remoteServerListenOnSocket": false
[17:15:32.877] "remote.SSH.showLoginTerminal": false
[17:15:32.877] "remote.SSH.defaultExtensions": []
[17:15:32.877] "remote.SSH.loglevel": 2
[17:15:32.877] SSH Resolver called for host: my-host
[17:15:32.877] Setting up SSH remote "my-host"
[17:15:32.893] Using commit id "3c4e3df9e89829dce27b7b5c24508306b151f30d" and quality "stable" for server
[17:15:32.896] Install and start server if needed
[17:15:47.797] getPlatformForHost was canceled
[17:15:47.801] Resolver error: Error: Connecting was canceled
	at Function.Canceled (c:\Users\my-user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:64837)
	at c:\Users\my-user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:294430
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Object.t.withShowDetailsEvent (c:\Users\my-user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:405329)
	at async Object.t.resolve (c:\Users\my-user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:295639)
	at async c:\Users\my-user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:127:110530
[17:15:47.808] ------
```

I was on 1.39.0 (hadn't used VS Code on this particular machine in a while), and it started up and loaded my remote workspace. Then I immediately upgraded to the current version (1.55.2). After restarting, the remote workspace didn't come back up.

I deleted the contents of `~/.vscode-server` on the remote, but that didn't help. Fiddling around until I found a way to set the remote platform fixed things, and the output then shows
```
"remote.SSH.remotePlatform": {"my-host":"linux"}
```

Not sure why my existing settings weren't carried over across the upgrade, but one clear issue here is the logs aren't very helpful for figuring out that a missing remote platform is the problem. If that configuration is necessary, then VS Code should just say explicitly that it can't connect without a platform being set for the remote host.

**Comment by roblourens** [comment]
It showed a prompt for you to select the remote host platform, it looks like you didn't respond to the prompt or canceled it.

**Comment by jjlin** [comment]
Yeah, it looks like it does, but I didn't notice it since it was working just before the upgrade and I wasn't expecting to have to do that. In hindsight, I guess this is what `getPlatformForHost was canceled` is supposed to convey, but this still reads much more like a log message for developers than a message intended for end users.

Given the confusion in #2788, it seems there are others who don't find this process intuitive either. I would still suggest a clear diagnostic of the issue, e.g. the log should say something like `You must select a platform for the remote host 'my-host'` and/or there should be a notification toast to the same effect.

**Comment by roblourens** [comment]
Yeah, the log is basically for me :)

Thanks for pointing out that other issue. I will continue this there.
