### ISSUE TITLE
bootstrap-node.js

### ISSUE THREAD

**Issue by martinowren** [microsoft/vscode-remote-release#4930]
- VS Code Version: 1.53.2 (user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:
I do not know if it is a reproducible error as I cannot record doing anything special. 

Does this issue occur when all extensions are disabled?: Yes

Nothing updated etc, and this happened this morning. I have tried to upgrade and update ubuntu without any luck
```
/home/martinow/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/out/bootstrap-node.js:1

SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/martinow/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/out/vs/server/cli.js:1:229)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
```

**Comment by tanhakabir** [comment]
Hey @martinowren! Did @aeschli's suggestion fix your issue?

**Comment by martinowren** [comment]
Unfortunately I cannot recall 😅

**Comment by tanhakabir** [comment]
No worries! I'll close this issue for now but feel free to let me know on this issue or a new one if you this is still a problem for you!
