### ISSUE TITLE
The remote host's architecture is not supported.

### ISSUE THREAD

**Issue by p1yang** [microsoft/vscode-remote-release#4972]
Mac vscode link kali 2021 ssh

[09:58:26.850] Unsupported architecture
[09:58:26.850] Terminating local server
[09:58:26.858] Resolver error: Error: The remote host's architecture is not supported
	at Function.ServerInstallError (/Users/pipi/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.36900/out/extension.js:1:64593)
	at c (/Users/pipi/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.36900/out/extension.js:1:58358)
	at Object.t.handleInstallOutput (/Users/pipi/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.36900/out/extension.js:1:63335)
	at Object.e [as tryInstallWithLocalServer] (/Users/pipi/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.36900/out/extension.js:1:386437)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async /Users/pipi/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.36900/out/extension.js:1:294053
	at async Object.t.withShowDetailsEvent (/Users/pipi/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.36900/out/extension.js:1:405347)
	at async /Users/pipi/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.36900/out/extension.js:1:384908
	at async E (/Users/pipi/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.36900/out/extension.js:1:381676)
	at async Object.t.resolveWithLocalServer (/Users/pipi/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.36900/out/extension.js:1:384535)
	at async Object.t.resolve (/Users/pipi/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.36900/out/extension.js:1:295523)
	at async /Users/pipi/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.4.36900/out/extension.js:127:110530
[09:58:26.862] Local server exit: 15

**Comment by p1yang** [comment]
<img width="689" alt="image" src="https://user-images.githubusercontent.com/82321176/116335957-4ecb0780-a80a-11eb-947b-69aff4921e2a.png">

**Comment by bamurtaugh** [comment]
Does your Remote SSH host meet the following requirements: https://code.visualstudio.com/docs/remote/ssh#_system-requirements?
