### ISSUE TITLE
cannot connect to remote server, while ssh from local cmd works well.

### ISSUE THREAD

**Issue by hexi519** [microsoft/vscode-remote-release#4983]
One part of my config file is：
![image](https://user-images.githubusercontent.com/32733547/116561796-360b4080-a935-11eb-851c-7929ac990e1c.png)
But when I tried to connect this server, log is :
```bash
[21:44:17.276] Log Level: 2
[21:44:17.284] remote-ssh-nightly@2021.4.39780
[21:44:17.284] win32 x64
[21:44:17.285] SSH Resolver called for "ssh-remote+g1v6(hesy)", attempt 1
[21:44:17.285] "remote.SSH.useLocalServer": false
[21:44:17.286] "remote.SSH.showLoginTerminal": false
[21:44:17.286] "remote.SSH.remotePlatform": {"g14v6(hesy)":"linux","g1v6(hesy)":"linux","g5v6(hesy)":"linux","g8v6(hesy)":"linux","hesycloud(g14-hesy)":"linux","g2v6(hesy)":"linux","g2v6(guifei)":"linux","hesycloud(g14)(hesy)":"linux","g2v4(hesy)":"linux","hesycloud(g2)(hesy)":"linux","hesycloud(g2)(guifei)":"linux","g2v4(guifei)":"linux","g1v4(hesy)":"linux"}
[21:44:17.286] "remote.SSH.path": undefined
[21:44:17.286] "remote.SSH.configFile": C:\Users\hesy\.ssh\config_vscode_hesy_v6
[21:44:17.287] "remote.SSH.useFlock": true
[21:44:17.287] "remote.SSH.lockfilesInTmp": false
[21:44:17.287] "remote.SSH.localServerDownload": auto
[21:44:17.287] "remote.SSH.remoteServerListenOnSocket": false
[21:44:17.287] "remote.SSH.showLoginTerminal": false
[21:44:17.288] "remote.SSH.defaultExtensions": []
[21:44:17.288] "remote.SSH.loglevel": 2
[21:44:17.288] SSH Resolver called for host: hesycloud(g14)(hesy)
[21:44:17.289] Setting up SSH remote "hesycloud(g14)(hesy)"
[21:44:17.326] Using commit id "3c4e3df9e89829dce27b7b5c24508306b151f30d" and quality "stable" for server
[21:44:17.333] Install and start server if needed
[21:44:17.415] Checking ssh with "ssh -V"
[21:44:17.463] > OpenSSH_8.2p1, OpenSSL 1.1.1d  10 Sep 2019

[21:44:17.479] Using SSH config file "C:\Users\hesy\.ssh\config_vscode_hesy_v6"
[21:44:17.480] Running script with connection command: ssh -T -D 39532 -F "C:\Users\hesy\.ssh\config_vscode_hesy_v6" "g1v6(hesy)" bash
[21:44:17.485] Terminal shell path: C:\Windows\System32\cmd.exe
[21:44:17.634] > 
[21:44:17.635] Got some output, clearing connection timeout
[21:44:17.660] > 拒绝访问。
> 
[21:44:21.782] "install" terminal command done
[21:44:21.783] Install terminal quit with output: 拒绝访问。
[21:44:21.784] Received install output: 拒绝访问。
[21:44:21.785] Failed to parse remote port from server output
[21:44:21.790] Resolver error: Error: 
	at Function.Create (c:\Users\hesy\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.39780\out\extension.js:1:64659)
	at Object.t.handleInstallOutput (c:\Users\hesy\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.39780\out\extension.js:1:63302)
	at Object.t.tryInstall (c:\Users\hesy\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.39780\out\extension.js:1:414002)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\hesy\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.39780\out\extension.js:1:294536
	at async Object.t.withShowDetailsEvent (c:\Users\hesy\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.39780\out\extension.js:1:405347)
	at async Object.t.resolve (c:\Users\hesy\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.39780\out\extension.js:1:295657)
	at async c:\Users\hesy\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.39780\out\extension.js:127:110530
[21:44:21.804] ------
```

However, I can ssh to this remote server through the local cmd：
![image](https://user-images.githubusercontent.com/32733547/116562155-82568080-a935-11eb-8cdb-7b1e1ced1405.png)

I don't think that any error exists in my config file, because I have successfully connected to the remote server via Remote Development for a long time, but I failed suddenly today.

I have tried the latest Remote SSH extension and changed to  Remote SSH (Nightly) according to one issue, but still failed.

**Comment by hexi519** [comment]
So sorry for the mistake paste of the log file. The correct log file is：
```shell
[21:44:17.276] Log Level: 2
[21:44:17.284] remote-ssh-nightly@2021.4.39780
[21:44:17.284] win32 x64
[21:44:17.285] SSH Resolver called for "ssh-remote+g1v6(hesy)", attempt 1
[21:44:17.285] "remote.SSH.useLocalServer": false
[21:44:17.286] "remote.SSH.showLoginTerminal": false
[21:44:17.286] "remote.SSH.remotePlatform": {"g14v6(hesy)":"linux","g1v6(hesy)":"linux","g5v6(hesy)":"linux","g8v6(hesy)":"linux","hesycloud(g14-hesy)":"linux","g2v6(hesy)":"linux","g2v6(guifei)":"linux","hesycloud(g14)(hesy)":"linux","g2v4(hesy)":"linux","hesycloud(g2)(hesy)":"linux","hesycloud(g2)(guifei)":"linux","g2v4(guifei)":"linux","g1v4(hesy)":"linux"}
[21:44:17.286] "remote.SSH.path": undefined
[21:44:17.286] "remote.SSH.configFile": C:\Users\hesy\.ssh\config_vscode_hesy_v6
[21:44:17.287] "remote.SSH.useFlock": true
[21:44:17.287] "remote.SSH.lockfilesInTmp": false
[21:44:17.287] "remote.SSH.localServerDownload": auto
[21:44:17.287] "remote.SSH.remoteServerListenOnSocket": false
[21:44:17.287] "remote.SSH.showLoginTerminal": false
[21:44:17.288] "remote.SSH.defaultExtensions": []
[21:44:17.288] "remote.SSH.loglevel": 2
[21:44:17.288] SSH Resolver called for host: g1v6(hesy)
[21:44:17.289] Setting up SSH remote "g1v6(hesy)"
[21:44:17.326] Using commit id "3c4e3df9e89829dce27b7b5c24508306b151f30d" and quality "stable" for server
[21:44:17.333] Install and start server if needed
[21:44:17.415] Checking ssh with "ssh -V"
[21:44:17.463] > OpenSSH_8.2p1, OpenSSL 1.1.1d  10 Sep 2019

[21:44:17.479] Using SSH config file "C:\Users\hesy\.ssh\config_vscode_hesy_v6"
[21:44:17.480] Running script with connection command: ssh -T -D 39532 -F "C:\Users\hesy\.ssh\config_vscode_hesy_v6" "g1v6(hesy)" bash
[21:44:17.485] Terminal shell path: C:\Windows\System32\cmd.exe
[21:44:17.634] > 
[21:44:17.635] Got some output, clearing connection timeout
[21:44:17.660] > 拒绝访问。
> 
[21:44:21.782] "install" terminal command done
[21:44:21.783] Install terminal quit with output: 拒绝访问。
[21:44:21.784] Received install output: 拒绝访问。
[21:44:21.785] Failed to parse remote port from server output
[21:44:21.790] Resolver error: Error: 
	at Function.Create (c:\Users\hesy\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.39780\out\extension.js:1:64659)
	at Object.t.handleInstallOutput (c:\Users\hesy\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.39780\out\extension.js:1:63302)
	at Object.t.tryInstall (c:\Users\hesy\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.39780\out\extension.js:1:414002)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\hesy\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.39780\out\extension.js:1:294536
	at async Object.t.withShowDetailsEvent (c:\Users\hesy\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.39780\out\extension.js:1:405347)
	at async Object.t.resolve (c:\Users\hesy\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.39780\out\extension.js:1:295657)
	at async c:\Users\hesy\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.4.39780\out\extension.js:127:110530
[21:44:21.804] ------
```

**Comment by roblourens** [comment]
Is it any different if you don't have the `()` in your server host name?

**Comment by jjcarstens** [comment]
@roblourens If it helps, I have this same issue from MacOS host to ubuntu remote. I've tried using the hostname `bender.local` and its static IP of `10.0.1.35`, but with the same error ¬

<details>
<summary>Remote SSH output</summary>

```
[10:38:08.928] Log Level: 2
[10:38:08.929] remote-ssh@0.65.1
[10:38:08.929] darwin x64
[10:38:08.930] SSH Resolver called for "ssh-remote+10.0.1.35", attempt 1
[10:38:08.930] "remote.SSH.useLocalServer": true
[10:38:08.931] "remote.SSH.sshPath": undefined
[10:38:08.931] "remote.SSH.sshConfigurationFile": undefined
[10:38:08.931] "remote.SSH.useFlock": true
[10:38:08.931] "remote.SSH.lockfilesInTmp": false
[10:38:08.931] "remote.SSH.localServerDownload": auto
[10:38:08.931] "remote.SSH.remoteServerListenOnSocket": false
[10:38:08.932] "remote.SSH.showLoginTerminal": false
[10:38:08.932] "remote.SSH.defaultExtensions": []
[10:38:08.932] SSH Resolver called for host: 10.0.1.35
[10:38:08.932] Setting up SSH remote "10.0.1.35"
[10:38:08.934] Acquiring local install lock: /var/folders/ys/0kz680t51hd6j0cvc76bv0vm0000gr/T/vscode-remote-ssh-10.0.1.35-install.lock
[10:38:08.937] Looking for existing server data file at /Users/jonjon/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-10.0.1.35-cfa2e218100323074ac1948c885448fdf4de2a7f-0.65.1/data.json
[10:38:08.938] Using commit id "cfa2e218100323074ac1948c885448fdf4de2a7f" and quality "stable" for server
[10:38:08.940] Install and start server if needed
[10:38:08.943] Checking ssh with "ssh -V"
[10:38:08.948] > OpenSSH_8.1p1, LibreSSL 2.7.3

[10:38:08.951] askpass server listening on /var/folders/ys/0kz680t51hd6j0cvc76bv0vm0000gr/T/vscode-ssh-askpass-58b25201cc874129153eaeba538b277f75980854.sock
[10:38:08.951] Spawning local server with {"ipcHandlePath":"/var/folders/ys/0kz680t51hd6j0cvc76bv0vm0000gr/T/vscode-ssh-askpass-3eb6a8074c410af911c4dfd648aa95deb3777ea8.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","54622","-o","ConnectTimeout=15","10.0.1.35"],"dataFilePath":"/Users/jonjon/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-10.0.1.35-cfa2e218100323074ac1948c885448fdf4de2a7f-0.65.1/data.json"}
[10:38:08.951] Local server env: {"DISPLAY":"/private/tmp/com.apple.launchd.pAquLbaefr/org.macosforge.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/jonjon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/jonjon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/ys/0kz680t51hd6j0cvc76bv0vm0000gr/T/vscode-ssh-askpass-58b25201cc874129153eaeba538b277f75980854.sock"}
[10:38:08.952] Spawned 29644
[10:38:09.045] > local-server> Spawned ssh: 29653
[10:38:09.047] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[10:38:09.078] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:mFEC/tQBZT2xYPS3WJwF6ns0PHYgm/yzE0ZdJ/XUb8Q
[10:38:09.078] stderr> Warning: Permanently added '10.0.1.35' (ECDSA) to the list of known hosts.
[10:38:09.158] stderr> Authenticated to 10.0.1.35 ([10.0.1.35]:22).
[10:38:09.260] > Welcome to Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-72-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
> 36 updates can be installed immediately.
> 0 of these updates are security updates.
> To see these additional updates run: apt list --upgradable
[10:38:09.262] > ready: 38250154d4bf
[10:38:09.266] > Linux 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021
[10:38:09.266] Platform: linux
[10:38:09.278] > 38250154d4bf: running
[10:38:09.294] > Acquiring lock on /home/jonjon/.vscode-server/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/vscode-remote-lock.jonjon.cfa2e218100323074ac1948c885448fdf4de2a7f
[10:38:09.297] > Installing to /home/jonjon/.vscode-server/bin/cfa2e218100323074ac1948c885448fdf4de2a7f...
[10:38:09.298] > 38250154d4bf%%1%%
[10:38:09.299] > Downloading with wget
[10:38:09.467] stderr> events.js:292
[10:38:09.467] stderr>       throw er; // Unhandled 'error' event
[10:38:09.467] stderr>       ^
[10:38:09.467] stderr> 
[10:38:09.467] stderr> Error [ERR_STREAM_WRITE_AFTER_END]: write after end
[10:38:09.467] stderr>     at writeAfterEnd (_http_outgoing.js:668:15)
[10:38:09.467] stderr>     at ServerResponse.end (_http_outgoing.js:789:7)
[10:38:09.467] stderr>     at Object.onRequest (/Users/jonjon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/localServer.js:1:2599)
[10:38:09.468] stderr>     at Server.<anonymous> (/Users/jonjon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/localServer.js:1:1914)
[10:38:09.468] stderr>     at Server.emit (events.js:315:20)
[10:38:09.468] stderr>     at parserOnIncoming (_http_server.js:874:12)
[10:38:09.468] stderr>     at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
[10:38:09.468] stderr> Emitted 'error' event on ServerResponse instance at:
[10:38:09.468] stderr>     at writeAfterEndNT (_http_outgoing.js:727:7)
[10:38:09.468] stderr>     at processTicksAndRejections (internal/process/task_queues.js:81:21) {
[10:38:09.468] stderr>   code: 'ERR_STREAM_WRITE_AFTER_END'
[10:38:09.468] stderr> }
[10:38:09.470] Local server exit: 1
[10:38:09.470] Received install output: OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:mFEC/tQBZT2xYPS3WJwF6ns0PHYgm/yzE0ZdJ/XUb8Q
Warning: Permanently added '10.0.1.35' (ECDSA) to the list of known hosts.
Authenticated to 10.0.1.35 ([10.0.1.35]:22).
Welcome to Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-72-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

36 updates can be installed immediately.
0 of these updates are security updates.
To see these additional updates run: apt list --upgradable

ready: 38250154d4bf
Linux 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021
38250154d4bf: running
Acquiring lock on /home/jonjon/.vscode-server/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/vscode-remote-lock.jonjon.cfa2e218100323074ac1948c885448fdf4de2a7f
Installing to /home/jonjon/.vscode-server/bin/cfa2e218100323074ac1948c885448fdf4de2a7f...
38250154d4bf%%1%%
Downloading with wget
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_http_outgoing.js:668:15)
    at ServerResponse.end (_http_outgoing.js:789:7)
    at Object.onRequest (/Users/jonjon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/localServer.js:1:2599)
    at Server.<anonymous> (/Users/jonjon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/localServer.js:1:1914)
    at Server.emit (events.js:315:20)
    at parserOnIncoming (_http_server.js:874:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
Emitted 'error' event on ServerResponse instance at:
    at writeAfterEndNT (_http_outgoing.js:727:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}

[10:38:09.471] Stopped parsing output early. Remaining text: OpenSSH_8.1p1, LibreSSL 2.7.3debug1: Server host key: ecdsa-sha2-nistp256 SHA256:mFEC/tQBZT2xYPS3WJwF6ns0PHYgm/yzE0ZdJ/XUb8QWarning: Permanently added '10.0.1.35' (ECDSA) to the list of known hosts.Authenticated to 10.0.1.35 ([10.0.1.35]:22).Welcome to Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-72-generic x86_64) * Documentation:  https://help.ubuntu.com * Management:     https://landscape.canonical.com * Support:        https://ubuntu.com/advantage36 updates can be installed immediately.0 of these updates are security updates.To see these additional updates run: apt list --upgradableready: 38250154d4bfLinux 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 202138250154d4bf: runningAcquiring lock on /home/jonjon/.vscode-server/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/vscode-remote-lock.jonjon.cfa2e218100323074ac1948c885448fdf4de2a7fInstalling to /home/jonjon/.vscode-server/bin/cfa2e218100323074ac1948c885448fdf4de2a7f...38250154d4bf%%1%%Downloading with wgetevents.js:292      throw er; // Unhandled 'error' event      ^Error [ERR_STREAM_WRITE_AFTER_END]: write after end    at writeAfterEnd (_http_outgoing.js:668:15)    at ServerResponse.end (_http_outgoing.js:789:7)    at Object.onRequest (/Users/jonjon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/localServer.js:1:2599)    at Server.<anonymous> (/Users/jonjon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/localServer.js:1:1914)    at Server.emit (events.js:315:20)    at parserOnIncoming (_http_server.js:874:12)    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)Emitted 'error' event on ServerResponse instance at:    at writeAfterEndNT (_http_outgoing.js:727:7)    at processTicksAndRejections (internal/process/task_queues.js:81:21) {  code: 'ERR_STREAM_WRITE_AFTER_END'}
[10:38:09.471] Failed to parse remote port from server output
[10:38:09.476] Resolver error: Error: 
	at Function.Create (/Users/jonjon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:64328)
	at Object.t.handleInstallOutput (/Users/jonjon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:63022)
	at Object.t.tryInstallWithLocalServer (/Users/jonjon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:388682)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/jonjon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:293749
	at async Object.t.withShowDetailsEvent (/Users/jonjon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:407055)
	at async /Users/jonjon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:387177
	at async N (/Users/jonjon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:383945)
	at async Object.t.resolveWithLocalServer (/Users/jonjon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:386804)
	at async Object.t.resolve (/Users/jonjon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:1:297790)
	at async /Users/jonjon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.1/out/extension.js:127:110485
[10:38:09.479] ------
```
</details>

**Comment by jjcarstens** [comment]
Actually, FWIW, I thought I was on the latest extension version, but just updated to 0.65.4 and its fixed 🙌

**Comment by hexi519** [comment]
> Actually, FWIW, I thought I was on the latest extension version, but just updated to 0.65.4 and its fixed 🙌

It looks like a good solution, but I reinstalled my Windows 2 days ago, so I cannot try your solution... 
However, I remember that I tried to reinstall VS Code and then reinstall the plugin ( yet without check whether the plugin version is the latest ), and still failed...

**Comment by roblourens** [comment]
Let me know if you have any more issues
