### ISSUE TITLE
Remote-ssh and CyberArk PSM

### ISSUE THREAD

**Issue by secfalcon** [microsoft/vscode-remote-release#4989]
- VSCode Version: 1.55.2
- Local OS Version: Windows 10
- Remote OS Version: Red Hat 7
- Remote Extension/Connection Type: SSH

**Steps to Reproduce:**
1. Simple SSH Connection through PSM for SSH Proxy Server of CyberArk

<br>
I am having issues using VSCode Remote through CyberArk proxy same as documented in prior unresolved issues #2736 and #4129

We authenticate to our Linux servers through CyberArk proxy servers successfully with the below SSH command. 

`ssh myUserName@vaultUserName%domain@targetServer@CyberArkPSM`

The CyberArkPSM will validate "_myUserName_" credentials then checkout the password for "_vaultUserName_" from safe "domain" and create an SSH session to "_targetServer_". We never know or provide the password for "_vaultUserName_". (Full details available at https://docs.cyberark.com/Product-Doc/OnlineHelp/PrivCloud/Latest/en/Content/Privilege%20Cloud/privCloud-connect-using-SSH.htm#Connect)

When attempting to use this string in VSCode to connect to a new server, we authenticate to the CyberArkPSM successfully, but immediately error out with the below error as documented in the other unresolved issues:

`bash: line 187: unexpected EOF while looking for matching "'`
`bash: line 188: syntax error: unexpected end of file`

What it looks like is the install process starts after it detects the successful connection to the CyberArkPSM proxy server thinking the connection is successful (as it was) and ready to go, but we are not yet on our target server. The install is not waiting until CyberArkPSM establishes a session with the actual server we are trying to connect to (_targetServer_).

It appears the connection to CyberArkPSM allows up to 4096 bytes to stdin before the connection from CyberArkPSM to the actual target server is complete. Once connected to the target server, those 4096 bytes are sent, but its already a truncated payload. Since the install payload is truncated at 4096 bytes, we see the EOF error in the bash execution. After the connection is complete, payloads larger than 4096 bytes pass through to the target server in full.

Is ~4096 bytes into the install script ~187 lines in as mentioned in the unexpected EOF error returned?
Is it possible add a configurable delay before the install attempts to execute after connecting to a host?

**Comment by secfalcon** [comment]
If the truncation is related to length of install script being sent before connection between CyberArk PSM and target server, issue #4487 exploring other ways to transfer the install script on Window may help here as well, depending on how the solution can be used on Linux as well.

**Comment by roblourens** [comment]
Interesting, thanks for this detail.

> After the connection is complete, payloads larger than 4096 bytes pass through to the target server in full.

Is there any way to know automatically when the connection is complete? 

Also, can you tell me whether this is any different when using `"remote.SSH.useLocalServer": true`? Note that you have to set this in your json file on windows to take effect.

**Comment by secfalcon** [comment]
> Also, can you tell me whether this is any different when using "remote.SSH.useLocalServer": true? Note that you have to set this in your json file on windows to take effect.

Still fails (looks to be earlier on) with remote.SSH.useLocalServer set to true.

>[23:08:59.839] Got askpass request: {"request":""}
[23:08:59.840] Listening for interwindow password on \\.\pipe\vscode-ssh-askpass-7c92479e42d1005087a26c6d03f94be9e8153268-sock
[23:08:59.840] Writing password prompt to globalState
[23:09:08.765] Interactor gave response: ********
[23:09:08.765] Cleaning up other-window auth server
[23:09:08.822] stderr> Authenticated to [hostname] ([IP]:22).
[23:09:08.892] > Last failed login: Thu May  6 22:53:58 EDT 2021 from [otherIP] on ssh:notty
[23:09:11.602] stderr> Transferred: sent 1852, received 2552 bytes, in 2.8 seconds
[23:09:11.603] stderr> Bytes per second: sent 667.0, received 919.1
[23:09:11.605] stderr> This is a corporate computer facility. Access must be specifically
[23:09:11.605] stderr> authorized by [entity] for business purposes
[23:09:11.612] > local-server> ssh child died, shutting down
[23:09:11.627] Local server exit: 0
[23:09:11.628] Received install output: OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:[hostkey]
Authenticated to [hostname] ([IP]:22).
Transferred: sent 1852, received 2552 bytes, in 2.8 seconds
Bytes per second: sent 667.0, received 919.1
This is a corporate computer facility. Access must be specifically
authorized by [entity] for business purposes
[23:09:11.629] Failed to parse remote port from server output
[23:09:11.630] Resolver error: Error: 
	at Function.Create (c:\Users\[username]\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:64641)
	at Object.t.handleInstallOutput (c:\Users\[username]\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:63284)
	at Object.e [as tryInstallWithLocalServer] (c:\Users\[username]\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:386419)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\[username]\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:294035
	at async Object.t.withShowDetailsEvent (c:\Users\[username]\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:405329)
	at async c:\Users\[username]\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:384890
	at async E (c:\Users\[username]\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:381658)
	at async Object.t.resolveWithLocalServer (c:\Users\[username]\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:384517)
	at async Object.t.resolve (c:\Users\[username]\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:295505)
	at async c:\Users\[username]\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:127:110530
[23:09:11.637] ------


> Is there any way to know automatically when the connection is complete?

Not that I can see. Was wondering if there was some delay parameter already configured to allow testing if we waited a certain amount of time to allow the second connection to be established prior to sending the script contents. At least to start there to confirm we are down the correct path.

What I see (outside of VSCode using just SSH) is if I try to put more than the 4096 bytes into stdin before CyberArk establishes the second connection the payload is truncated. If I wait to send the payload until CyberArk establishes the connection to our actual target server, the full payload makes it to the target server.

**Comment by roblourens** [comment]
Can you share your test code?

I am confused because in the first case (useLocalServer=off), we can't delay, because we only run a command like `echo "long command" | ssh yourhost`

In the second case (useLocalServer=on), we spawn an ssh process then write to stdin, so this is the case where we would delay. But I don't see any output or error about the script so I can't even tell whether it ran or what. I don't know if that 'Transferred' line is about the script or something else

```
[23:09:08.822] stderr> Authenticated to [hostname] ([IP]:22).
[23:09:08.892] > Last failed login: Thu May 6 22:53:58 EDT 2021 from [otherIP] on ssh:notty
[23:09:11.602] stderr> Transferred: sent 1852, received 2552 bytes, in 2.8 seconds
[23:09:11.603] stderr> Bytes per second: sent 667.0, received 919.1
[23:09:11.605] stderr> This is a corporate computer facility. Access must be specifically
[23:09:11.605] stderr> authorized by [entity] for business purposes
[23:09:11.612] > local-server> ssh child died, shutting down
```
