### ISSUE TITLE
Git credential manager conflict with Dev Container

### ISSUE THREAD

**Issue by Byrth** [microsoft/vscode-remote-release#5002]
- VSCode Version:
Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
- Local OS Version: Windows 10 Enterprise
- Name of Dev Container Definition with Issue: Custom / local

Steps to Reproduce:

1. Open Dev container
2. Check /etc/gitconfig and ~/.gitconfig
3. Observe that the `[credential]` section has reappeared
4. Wait ~an hour
5. Attempt to use git. It spins for a long time and throws an error about not being able to connect.

Narrative:
Every time I open my dev container, VS Code re-writes a `[credential]` section with helper defined as the result of a javascript script executed by node. This is a problem for me because the script only seems to work for an hour or so before it starts timing out (very slowly). Every time I log in, I have to remember to delete it again, which is an annoyance (even moreso when I forget to do it). So there are kind of two problems here:
* The credential manager integration doesn't seem to work with my setup (not sure who owns this)
* The container boot process involves writing these two files again even though I have intentionally removed the lines already (I'm 80% sure that's this project). Why is this ever rewritten?

**Comment by chrmarti** [comment]
You can disable this in the user settings:
![image](https://user-images.githubusercontent.com/9205389/117253532-96bfdf00-ae47-11eb-9cee-adbad685bb21.png)

**Comment by Byrth** [comment]
Excellent. Thank you!

I am willing to help debug if you're interested in attempting to discover why it fails after a certain amount of time. Otherwise, feel free to close it.

**Comment by chrmarti** [comment]
It would be great to have the logs (`F1` > `Remote-Containers: Show Container Log` and `Help` > `Toggle Developer Tools` > `Console`) from around the time it stops working. Thanks!

**Comment by Byrth** [comment]
Dev Containers log:
~~~
[25389 ms] [13:32:17] [::ffff:127.0.0.1][47877f25][ExtensionHostConnection] New connection established.
[25400 ms] [13:32:17] [::ffff:127.0.0.1][47877f25][ExtensionHostConnection] <205> Launched Extension Host Process.
[31643 ms] Port forwarding 53074 > 45103 > 45103 stderr: Remote close
[31782 ms] Port forwarding 53074 > 45103 > 45103 terminated with code 0 and signal null.
[151794 ms] Port forwarding 53074 > 45103 > 45103: Local close with error
[429647 ms] Remote-Containers server: command [ssh -l me -p 22 -- 10.32.9.73 docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=Connection reset by 10.32.9.73 port 22
[429716 ms] Remote-Containers server terminated (code: 1, signal: null).
~~~

Developer console:
~~~
log.ts:296   ERR read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (internal/stream_base_commons.js:209:20)

# This repeats four times:
console.ts:137 [Extension Host] Error: unexpected end of parent stream
	at ir.destroy (c:\Users\me\.vscode\extensions\ms-vscode-remote.remote-containers-0.177.0\dist\extension\extension.js:7:60958)
	at ir.write (c:\Users\me\.vscode\extensions\ms-vscode-remote.remote-containers-0.177.0\dist\extension\extension.js:7:61837)
	at c:\Users\me\.vscode\extensions\ms-vscode-remote.remote-containers-0.177.0\dist\extension\extension.js:7:64899
	at c:\Users\me\.vscode\extensions\ms-vscode-remote.remote-containers-0.177.0\dist\extension\extension.js:7:50629
	at c:\Users\me\.vscode\extensions\ms-vscode-remote.remote-containers-0.177.0\dist\extension\extension.js:7:69170
	at Object.cb (c:\Users\me\.vscode\extensions\ms-vscode-remote.remote-containers-0.177.0\dist\extension\extension.js:7:59451)
	at u (c:\Users\me\.vscode\extensions\ms-vscode-remote.remote-containers-0.177.0\dist\extension\extension.js:7:57684)
	at c:\Users\me\.vscode\extensions\ms-vscode-remote.remote-containers-0.177.0\dist\extension\extension.js:7:57831
	at s (c:\Users\me\.vscode\extensions\ms-vscode-remote.remote-containers-0.177.0\dist\extension\extension.js:12:5707)
	at Socket.<anonymous> (c:\Users\me\.vscode\extensions\ms-vscode-remote.remote-containers-0.177.0\dist\extension\extension.js:12:5877)
	at Socket.emit (events.js:327:22)
	at endReadableNT (internal/streams/readable.js:1327:12)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)
~~~

**Comment by chrmarti** [comment]
We might just have to reestablish the connection at that point. That will also make us more resilient towards other network issues. Thanks!

**Comment by posita** [comment]
> You can disable this in the user settings: ![image](https://user-images.githubusercontent.com/9205389/117253532-96bfdf00-ae47-11eb-9cee-adbad685bb21.png)

How does one set this in `devcontainer.json`?

**Comment by janis-veinbergs** [comment]
> You can disable this in the user settings: ![image](https://user-images.githubusercontent.com/9205389/117253532-96bfdf00-ae47-11eb-9cee-adbad685bb21.png)

@chrmarti  Is this setting gone? VSCode 1.67.2 and I don't see such setting.

**Comment by chrmarti** [comment]
@janis-veinbergs The setting is still there, make sure you are not connected to a remote when you look for it in "User" settings.

@posita You can add it to `"customizations" > "vscode" > "settings"` in the devcontainer.json. (Although I would recommend setting it in your user settings if you don't want any dev container to get your `~./gitconfig`.)

**Comment by chrmarti** [comment]
Closing. Currently investigating if reconnection works, that should take care of when `ssh` disconnects.
