### ISSUE TITLE
jailkit: ssh-failed flock

### ISSUE THREAD

**Issue by matteocostantini** [microsoft/vscode-remote-release#5004]
i'm using a chroot jailkit user. i want use this user with remote ssh. ssh-add failed!

- VSCode Version: 1.55.2
- Local OS Version:  Windows 10 20h2
- Remote OS Version: ubuntu 20.04
- Remote Extension/Connection Type: SSH
- Logs:
C:\Users\ad05>(powershell -ExecutionPolicy Bypass C:\Users\ad05\AppData\Local\Te
> mp\vscode_add_ssh_key_to_agent.ps1) & exit /b 0
> ]0;C:\Windows\System32\cmd.exe - powershell  -ExecutionPolicy Bypass C:\Users\ad05\AppData\Local\Temp\vscode_add_ssh_key_to_agent.ps1
[16:11:22.808] > PS: adding key to ssh-agent
[16:11:22.818] > 
> ssh-add
> C:\Users\ad05\.ssh\id_rsa
[16:11:22.833] > Error connecting to agent: No such file or directory
> 2077fbc5cf74##5##
[16:11:22.833] ssh-add failed
[16:11:22.833] Consider setting up the ssh agent: https://aka.ms/vscode-remote/troubleshooting#_setting-up-the-ssh-agent
[16:11:22.848] > ]0;C:\Windows\System32\cmd.exe
[16:11:22.848] ssh-add failed
[16:11:22.848] Consider setting up the ssh agent: https://aka.ms/vscode-remote/troubleshooting#_setting-up-the-ssh-agent
[16:11:23.157] "add-ssh-key" terminal command done
[16:11:23.157] Install terminal quit with output: main: line 223: flock: command not found
[16:11:28.462] getPlatformForHost was canceled
[16:11:28.465] Resolver error: Error: Connecting was canceled
	at Function.Canceled (c:\Users\ad05\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:64837)
	at c:\Users\ad05\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:294430
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Object.t.withShowDetailsEvent (c:\Users\ad05\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:405329)
	at async Object.t.resolve (c:\Users\ad05\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:295639)
	at async c:\Users\ad05\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:127:110530
[16:11:28.470] ------

**Comment by matteocostantini** [comment]
jk_cp -k -j /jail/path  /usr/bin/flock is the solution!
