### ISSUE TITLE
cannot SSH key-based authentication to Ubuntu host

### ISSUE THREAD

**Issue by giangdo11** [microsoft/vscode-remote-release#5005]
Issue Type: <b>Bug</b>

I generated a SSH key pair by cmd "ssh-keygen -t rsa -b 4096".

After that I copy public-key to ubuntu host by cmd:
$USER_AT_HOST="dotruong@10.129.1.207"
$PUBKEYPATH="$HOME\.ssh\id_rsa.pub"
$pubKey=(Get-Content "$PUBKEYPATH" | Out-String); ssh "$USER_AT_HOST" "mkdir -p ~/.ssh && chmod 700 ~/.ssh && echo '${pubKey}' >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys"

and I config ssh file as below:
Host 10.129.1.207
  HostName 10.129.1.207
  User dotruong
  PreferredAuthentications publickey
  IdentityFile ~/.ssh/id_rsa

But I got the error when ssh :
[11:05:40.160] Checking ssh with "ssh -V"
[11:05:40.205] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[11:05:40.211] Using SSH config file "C:\Users\dtruonggiang\.ssh\config"
[11:05:40.212] Running script with connection command: ssh -T -D 61460 -F "C:\Users\dtruonggiang\.ssh\config" "10.129.1.207" bash
[11:05:40.215] Terminal shell path: C:\Windows\System32\cmd.exe
[11:05:41.396] > dotruong@10.129.1.207: Permission denied (publickey,password).
> ]0;C:\Windows\System32\cmd.exe
[11:05:41.397] Got some output, clearing connection timeout
[11:05:41.404] > The process tried to write to a nonexistent pipe.
[11:05:41.762] "install" terminal command done
[11:05:41.762] Install terminal quit with output: ]0;C:\Windows\System32\cmd.exeThe process tried to write to a nonexistent pipe.
[11:05:41.763] Received install output: ]0;C:\Windows\System32\cmd.exeThe process tried to write to a nonexistent pipe.
[11:05:41.763] Resolver error: Error: The process tried to write to a nonexistent pipe
	at Function.Offline (c:\Users\dtruonggiang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:64692)
	at c:\Users\dtruonggiang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:62242
	at Object.t.handleInstallOutput (c:\Users\dtruonggiang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:62620)
	at Object.t.tryInstall (c:\Users\dtruonggiang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:413984)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\dtruonggiang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:294518
	at async Object.t.withShowDetailsEvent (c:\Users\dtruonggiang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:405329)
	at async Object.t.resolve (c:\Users\dtruonggiang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:295639)
	at async c:\Users\dtruonggiang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:127:110530
[11:05:41.767] ------

Could you please help check this issue? Thank you

Extension version: 0.65.4
VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (2.00GB free)|
|Process Argv|--crash-reporter-id c1e08ce2-7f4a-40f0-b0f7-8b2353996ce4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvsnew554cf:30291488
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30294352

```

</details>

**Comment by bamurtaugh** [comment]
Does it sound like this could be https://github.com/microsoft/vscode-remote-release/issues/3661?
