### ISSUE TITLE
Trying to connect to a container that already has a connection gets stuck

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#502]
Testing https://github.com/microsoft/vscode-remote-release/issues/495

Repro steps
1. Using Java 8 test container + stable. Reopen folder in container.
2. After folder is open, do the same with insiders.
3. In stable, Attach to running container. Select the container that insiders is connected to.
4. I'm not sure what should happen here, but there should be some kind of message saying what went wrong. Instead, it got stuck "Installing Dev Container (details): Copying VS Code server to container.

**Comment by chrmarti** [comment]
Might be #500. What's in the Dev Container terminal?

**Comment by alexr00** [comment]
```
*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


IP Address: 172.17.0.3
Error occurred in server
{ Error: listen EADDRINUSE :::9753
    at Server.setupListenHandle [as _listen2] (net.js:1330:14)
    at listenInCluster (net.js:1378:12)
    at Server.listen (net.js:1466:7)
    at O._start (/root/.vscode-server/bin/c69c1719bb2dc24c33e2e5348b2a93fb1c3a2ea6/out/vs/agent/remoteExtensionHostAgent.js:377:933)
    at O.<anonymous> (/root/.vscode-server/bin/c69c1719bb2dc24c33e2e5348b2a93fb1c3a2ea6/out/vs/agent/remoteExtensionHostAgent.js:375:568)
    at Generator.next (<anonymous>)
    at o (/root/.vscode-server/bin/c69c1719bb2dc24c33e2e5348b2a93fb1c3a2ea6/out/vs/agent/remoteExtensionHostAgent.js:16:221)
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 9753 }
