### ISSUE TITLE
Extension 'ms-vscode-remote.remote-ssh-explorer cannot use PROPOSED API 

### ISSUE THREAD

**Issue by CalebEverett** [microsoft/vscode-remote-release#5044]
Issue Type: <b>Bug</b>

Just start the insiders edition and you get an error that says extension failed to activate and to run Developer: Toggle Developer Tools.

electron/js2c/renderer_init.js:61 The vm module of Node.js is deprecated in the renderer process and will be removed.
t._load @ electron/js2c/renderer_init.js:61
workbench.desktop.main.js:627   ERR Cannot have two contributions with the same id editor.contrib.acceptChangesButton: Error: Cannot have two contributions with the same id editor.contrib.acceptChangesButton
    at new ln (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:652:76088)
    at g._createInstance (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1374)
    at g.createInstance (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:793)
    at i.createEditorControl (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2252:27035)
    at i.createEditor (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2252:26646)
    at i.create (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1440:57779)
    at l.doCreateEditorPane (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1808:9752)
    at l.doShowEditorPane (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1808:9327)
    at l.openEditor (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1808:9081)
    at file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2462:15947
    at mi.doShowEditor (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2462:16126)
    at mi.restoreEditors (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2462:9086)
    at new mi (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2462:4164)
    at g._createInstance (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1374)
    at g.createInstance (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:793)
    at Function.createFromSerialized (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2462:4465)
    at ai.doCreateGroupView (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2481:7761)
    at Object.fromJSON (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2481:14771)
    at c._deserializeNode (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:142:59361)
    at file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:142:59204
    at Array.map (<anonymous>)
    at c._deserializeNode (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:142:59185)
    at c._deserialize (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:142:59090)
    at Function.deserialize (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:142:59024)
    at Function.deserialize (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:142:67922)
    at ai.doCreateGridControlWithState (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2481:14700)
    at ai.doCreateGridControlWithPreviousState (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2481:14283)
    at ai.doCreateGridControl (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2481:13860)
    at ai.createContentArea (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2481:11939)
    at ai.create (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:735:140270)
    at file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2519:63731
    at Array.forEach (<anonymous>)
    at M.renderWorkbench (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2519:63638)
    at file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2519:60823
    at g.invokeFunction (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:319)
    at M.startup (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2519:60454)
    at E.open (file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2649:30050)
    at async file:///C:/Users/Caleb/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/bootstrap-window.js:1:2841
workbench.desktop.main.js:2720 Extension 'ms-vscode-remote.remote-ssh-explorer cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
updateEnableProposedApi @ workbench.desktop.main.js:2720
workbench.desktop.main.js:62 [Extension Host] (node:9272) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code - Insiders --trace-deprecation ...` to show where the warning was created) (at writeOut (internal/process/warning.js:43:3))
S @ workbench.desktop.main.js:62
workbench.desktop.main.js:1965 No search provider registered for scheme: vscode-remote, waiting
(anonymous) @ workbench.desktop.main.js:1965
workbench.desktop.main.js:735 Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information.
onDidChangeNotification @ workbench.desktop.main.js:735
workbench.desktop.main.js:62 [Extension Host] extension activation failed TypeError: s.notebook.onDidChangeNotebookCellExecutionState is not a function
	at new d (/home/caleb/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:90:450992)
	at Object.t.resolveInstance (/home/caleb/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:263462)
	at /home/caleb/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:262667
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/caleb/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:263232)
	at /home/caleb/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:262667
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/caleb/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:263232)
	at /home/caleb/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:262667
	at /home/caleb/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:261615
	at Array.map (<anonymous>)
	at /home/caleb/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:261587
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/caleb/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:263232)
	at /home/caleb/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:262667
	at Object.t.resolve (/home/caleb/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:262930)
	at /home/caleb/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:254027
	at e._get (/home/caleb/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:253793)
	at e.get (/home/caleb/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:252505)
	at a.get (/home/caleb/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:90:505543)
	at /home/caleb/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:246130
	at async /home/caleb/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:37:829501
	at async t.activate (/home/caleb/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:37:829188)
	at async Promise.all (index 0)
S @ workbench.desktop.main.js:62
workbench.desktop.main.js:62 [Extension Host] (node:16490) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `node --trace-deprecation ...` to show where the warning was created)
S @ workbench.desktop.main.js:62
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/54d33cf14cf6c0e86880b5b74a5a3628de42bce9/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout

Extension version: 0.21.0
VS Code version: Code - Insiders 1.57.0-insider (54d33cf14cf6c0e86880b5b74a5a3628de42bce9, 2021-05-10T05:15:52.500Z)
OS version: Windows_NT x64 10.0.19043
Remote OS version: Linux x64 4.19.84-microsoft-standard
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (15.97GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/caleb/.cookiecutters/cookiecutter-finm --remote=wsl+Ubuntu --crash-reporter-id f7543aed-88e3-49ba-bc08-aa9439d824e1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|24.85GB (20.31GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|24.85GB (20.31GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833cf:30267465
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30296409
vscgsv2:30286872
vscorehovct:30295782
3f5j7703:30294757

```

</details>

**Comment by bamurtaugh** [comment]
Did you start getting this after a new VS Code or Remote-SSH update? If you uninstall Remote-SSH and reinstall the latest (v0.65.6) do you still experience this?

**Comment by CalebEverett** [comment]
@bamurtaugh I should have closed - I forget exactly when it this went away, but for sure with the set up below and v0.65.6 for Remote-SSH doesn't have this error:

Version: 1.57.0-insider (user setup)
Commit: 541a5d4fa70ab3095f23b28b88914e1f6a8f65c4
Date: 2021-05-28T09:50:57.063Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
