### ISSUE TITLE
Multiroot workspaces on Windows with forward slashes are treated as relative paths

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-remote-release#5045]
- VS Code Version: 1.56.1 & 1.56.2 
- OS Version: Windows

Steps to Reproduce:

1. clone https://github.com/Microsoft/vscode-smoketest-express
2. create a code-workspace somewhere else with this in it:

```json
{
	"folders": [
		{
			"path": "C:/Users/Tyler/Code/Microsoft/vscode-smoketest-express/public"
		},
		{
			"path": "C:/Users/Tyler/Code/Microsoft/vscode-smoketest-express/routes"
		},
		{
			"path": "C:/Users/Tyler/Code/Microsoft/vscode-smoketest-express/views"
		}
	]
}
```

> Note you need to update the paths to point to what you just cloned

3. Open the code workspace on Windows using the Test Resolver or SSH (the client and target should both be Windows)
4. It fails to load trying to find: `/C:/Users/Tyler/Code/Microsoft/vscode-smoketest-express/views/C:/Users/Tyler/Code/Microsoft/vscode-smoketest-express/views`

This is because it thinks `C:/Users/Tyler/Code/Microsoft/vscode-smoketest-express/views` is a relative path because we used forward slashes.

**Workarounds:**
* Add a forward slash to the beginning: `/C:/Users/Tyler/Code/Microsoft/vscode-smoketest-express/views`
* Replace forward slashes with back slashes

The smoke tests found this issue!

**Comment by TylerLeonhardt** [comment]
cc @rzhao271 @roblourens

**Comment by bpasero** [comment]
Martin please bounce back if this is a wrong assignment but I think you did the remote support and handling for multi root workspaces iirc.

**Comment by bpasero** [comment]
Some related commits in this area, this to originate from [`toWorkspaceFolders`](https://github.com/microsoft/vscode/blob/51ed283cc5bfcce3d331b5e028d0a2be3d8fafaf/src/vs/platform/workspaces/common/workspaces.ts#L317-L317)

https://github.com/microsoft/vscode/commit/a33643223033bf1bf841af01045f067b42cfefe6
https://github.com/microsoft/vscode/commit/f4939dff89d9e20fcd82492b8c6b89c82b571487

**Comment by TylerLeonhardt** [comment]
Here's what the smoke test failure looks like...


```
1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Multiroot
           shows results from all folders:
     Error: Timeout: get elements '.quick-input-widget .quick-input-list .monaco-list-row .label-name' after 20 seconds.     
      at poll (C:\Users\raymondzhao\work\vscode-distro\test\automation\out\code.js:173:19)
      at async Code.waitForElements (C:\Users\raymondzhao\work\vscode-distro\test\automation\out\code.js:250:16)
      at async QuickInput.waitForQuickInputElements (C:\Users\raymondzhao\work\vscode-distro\test\automation\out\quickinput.js:24:9)
      at async Context.<anonymous> (out\areas\multiroot\multiroot.test.js:39:13)
```

_Visually_ you see 3 folders in a workspace with the indicator that they could not be opened. And if you right click and `Copy path` you see that the path is like:

```
/C:/Users/Tyler/Code/Microsoft/vscode-smoketest-express/views/C:/Users/Tyler/Code/Microsoft/vscode-smoketest-express/views
```
