### ISSUE TITLE
SignatureDoesNotMatch: Signature expired (While connecting to AWS)

### ISSUE THREAD

**Issue by Lorioux** [microsoft/vscode-remote-release#5048]
Issue Type: <b>Bug</b>

[ERROR]: Error getting AccountId: [SignatureDoesNotMatch: Signature expired: 20210512T052235Z is now earlier than 20210512T140004Z (20210512T141504Z - 15 min.)
	at constructor.p (/home/***/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.25.0/dist/extension.js:44:9005)
	at constructor.callListeners (/home/***/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.25.0/dist/extension.js:45:22254)
	at constructor.emit (/home/***/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.25.0/dist/extension.js:45:21963)
	at constructor.emitEvent (/home/***/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.25.0/dist/extension.js:45:7927)
	at constructor.e (/home/***/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.25.0/dist/extension.js:45:3513)
	at R.runTo (/home/***/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.25.0/dist/extension.js:57:1736)
	at /home/***/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.25.0/dist/extension.js:57:1948
	at constructor.<anonymous> (/home/***/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.25.0/dist/extension.js:45:3724)
	at constructor.<anonymous> (/home/***/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.25.0/dist/extension.js:45:7982)
	at constructor.callListeners (/home/***/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.25.0/dist/extension.js:45:22358)
	at constructor.emit (/home/***/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.25.0/dist/extension.js:45:21963)
	at constructor.emitEvent (/home/***/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.25.0/dist/extension.js:45:7927)
	at constructor.e (/home/***/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.25.0/dist/extension.js:45:3513)
	at R.runTo (/home/***/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.25.0/dist/extension.js:57:1736)
	at /home/***/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.25.0/dist/extension.js:57:1948
	at constructor.<anonymous> (/home/***/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.25.0/dist/extension.js:45:3724)
	at constructor.<anonymous> (/home/***/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.25.0/dist/extension.js:45:7982)
	at constructor.callListeners (/home/***/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.25.0/dist/extension.js:45:22358)
	at e (/home/***/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.25.0/dist/extension.js:45:22139)
	at IncomingMessage.<anonymous> (/home/***/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.25.0/dist/extension.js:40:6016259)
	at IncomingMessage.emit (events.js:327:22)
	at IncomingMessage.EventEmitter.emit (domain.js:467:12)
	at endReadableNT (internal/streams/readable.js:1327:12)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)] {
  code: 'SignatureDoesNotMatch',
  time: 2021-05-12T05:22:35.512Z,
  requestId: '************************',
  statusCode: 403,
  retryable: true

Extension version: 0.56.2
VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (5.93GB free)|
|Process Argv|--crash-reporter-id 3b762e12-5e01-4d4f-8a6a-37d0bd19c0de|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|Memory (System)|12.24GB (11.14GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt943cf:30300583
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30294353
bridgeflight:30299254

```

</details>

**Comment by bamurtaugh** [comment]
Some investigation seems to suggest this may be because your local system time is out of sync; have you tried any solutions as described here: https://stackoverflow.com/questions/18295185/amazon-dynamodb-invalidsignatureexception?

**Comment by Lorioux** [comment]
Solved with `sudo ntpdate ntp.ubuntu.com` .
