### ISSUE TITLE
Suddenly can't connect to remote server through VSCode remote; SSH from terminal works

### ISSUE THREAD

**Issue by GeoffNN** [microsoft/vscode-remote-release#5056]
```
[15:47:42.017] Log Level: 2
[15:47:42.019] remote-ssh@0.65.4
[15:47:42.019] linux x64
[15:47:42.020] SSH Resolver called for "ssh-remote+hostname", attempt 1
[15:47:42.020] "remote.SSH.useLocalServer": true
[15:47:42.021] "remote.SSH.path": undefined
[15:47:42.021] "remote.SSH.configFile": undefined
[15:47:42.021] "remote.SSH.useFlock": false
[15:47:42.021] "remote.SSH.lockfilesInTmp": false
[15:47:42.021] "remote.SSH.localServerDownload": auto
[15:47:42.021] "remote.SSH.remoteServerListenOnSocket": false
[15:47:42.021] "remote.SSH.showLoginTerminal": false
[15:47:42.022] "remote.SSH.defaultExtensions": []
[15:47:42.022] "remote.SSH.loglevel": 2
[15:47:42.022] "remote.SSH.maxReconnectionAttempts": 5
[15:47:42.022] SSH Resolver called for host: hostname
[15:47:42.022] Setting up SSH remote "hostname"
[15:47:42.024] Acquiring local install lock: /tmp/vscode-remote-ssh-hostname-install.lock
[15:47:42.040] Looking for existing server data file at /home/username/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-hostname-e713fe9b05fc24facbec8f34fb1017133858842b-0.65.4/data.json
[15:47:42.041] Using commit id "e713fe9b05fc24facbec8f34fb1017133858842b" and quality "stable" for server
[15:47:42.043] Install and start server if needed
[15:47:42.047] PATH: /home/user/anaconda3/bin:/home/user/anaconda3/condabin:/home/user/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[15:47:42.047] Checking ssh with "ssh -V"
[15:47:42.053] > OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017

[15:47:42.075] askpass server listening on /run/user/1000/vscode-ssh-askpass-be2a4e7aa540012ec3dcb85da02b0a0d8a09f7a5.sock
[15:47:42.075] Spawning local server with {"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-7a110ac4763e1cfa0471ca9caae625dc579a6607.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","34803","-o","ConnectTimeout=45","hostname"],"dataFilePath":"/home/user/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-hostname-e713fe9b05fc24facbec8f34fb1017133858842b-0.65.4/data.json"}
[15:47:42.075] Local server env: {"DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-be2a4e7aa540012ec3dcb85da02b0a0d8a09f7a5.sock"}
[15:47:42.079] Spawned 5106
[15:47:42.163] > local-server> Spawned ssh: 5114
[15:47:42.164] stderr> OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
[15:47:42.172] stderr> ssh: connect to host hostname port 22: Connection refused
[15:47:42.173] > local-server> ssh child died, shutting down
[15:47:42.176] Local server exit: 0
[15:47:42.176] Received install output: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
ssh: connect to host hostname port 22: Connection refused

[15:47:42.177] Failed to parse remote port from server output
[15:47:42.178] Resolver error: Error: 
	at Function.Create (/home/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:64641)
	at Object.t.handleInstallOutput (/home/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:63284)
	at Object.e [as tryInstallWithLocalServer] (/home/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:386419)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:294035
	at async Object.t.withShowDetailsEvent (/home/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:405329)
	at async /home/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:384890
	at async E (/home/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:381658)
	at async Object.t.resolveWithLocalServer (/home/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:384517)
	at async Object.t.resolve (/home/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:295505)
	at async /home/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:127:110530
[15:47:42.183] ------
```

**Comment by GeoffNN** [comment]
A second attempt gave me these encouraging logs, but I still can't connect.

```
[16:00:01.487] Log Level: 2
[16:00:01.489] remote-ssh@0.65.4
[16:00:01.489] linux x64
[16:00:01.490] SSH Resolver called for "ssh-remote+hostname", attempt 1
[16:00:01.490] "remote.SSH.useLocalServer": true
[16:00:01.490] "remote.SSH.path": undefined
[16:00:01.491] "remote.SSH.configFile": undefined
[16:00:01.491] "remote.SSH.useFlock": false
[16:00:01.491] "remote.SSH.lockfilesInTmp": false
[16:00:01.491] "remote.SSH.localServerDownload": auto
[16:00:01.491] "remote.SSH.remoteServerListenOnSocket": false
[16:00:01.491] "remote.SSH.showLoginTerminal": false
[16:00:01.491] "remote.SSH.defaultExtensions": []
[16:00:01.491] "remote.SSH.loglevel": 2
[16:00:01.492] "remote.SSH.maxReconnectionAttempts": 5
[16:00:01.492] SSH Resolver called for host: hostname
[16:00:01.492] Setting up SSH remote "hostname"
[16:00:01.494] Acquiring local install lock: /tmp/vscode-remote-ssh-hostname-install.lock
[16:00:01.510] Looking for existing server data file at /home/geoff/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-hostname-e713fe9b05fc24facbec8f34fb1017133858842b-0.65.4/data.json
[16:00:01.511] Using commit id "e713fe9b05fc24facbec8f34fb1017133858842b" and quality "stable" for server
[16:00:01.513] Install and start server if needed
[16:00:01.516] PATH: /home/geoff/anaconda3/bin:/home/geoff/anaconda3/condabin:/home/geoff/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[16:00:01.516] Checking ssh with "ssh -V"
[16:00:01.523] > OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017

[16:00:01.541] askpass server listening on /run/user/1000/vscode-ssh-askpass-a4a2d5b8162383e302cad8bf19b7158b9457ae56.sock
[16:00:01.541] Spawning local server with {"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-021482d1b5b654dc6b787b3fde67eb86a099729a.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","42647","-o","ConnectTimeout=45","hostname"],"dataFilePath":"/home/geoff/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-hostname-e713fe9b05fc24facbec8f34fb1017133858842b-0.65.4/data.json"}
[16:00:01.541] Local server env: {"DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/geoff/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/geoff/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-a4a2d5b8162383e302cad8bf19b7158b9457ae56.sock"}
[16:00:01.545] Spawned 6322
[16:00:01.630] > local-server> Spawned ssh: 6330
[16:00:01.631] stderr> OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
[16:00:01.727] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:cPX6iKKAAPzylaG/vfrrpGqESD8SYwNlQuNeL0iPD6A
[16:00:01.917] Got askpass request: {"request":"username@hostname's password:"}
[16:00:01.917] Showing password prompt
[16:00:01.918] Listening for interwindow password on /run/user/1000/vscode-ssh-askpass-105380980818dabecaefd224a8095285354b32dc.sock
[16:00:01.918] Writing password prompt to globalState
[16:00:09.337] Got password response
[16:00:09.338] Interactor gave response: *************
[16:00:09.339] Cleaning up other-window auth server
[16:00:09.413] stderr> Authenticated to hostname ([128.32.37.243]:22).
[16:00:10.547] > Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-112-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>  System information disabled due to load higher than 48.0
> 
>  * Pure upstream Kubernetes 1.21, smallest, simplest cluster ops!
> 
>      https://microk8s.io/
> 
>  * Canonical Livepatch is available for installation.
>    - Reduce system reboots and improve kernel security. Activate at:
>      https://ubuntu.com/livepatch
> 
> 65 packages can be updated.
> 44 of these updates are security updates.
> To see these additional updates run: apt list --upgradable
> 
> New release '20.04.2 LTS' available.
> Run 'do-release-upgrade' to upgrade to it.
> 
> 
> *** System restart required ***
[16:00:10.594] > ready: 58500782842b
[16:00:10.611] > Linux 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020
[16:00:10.612] Platform: linux
[16:00:10.656] > 58500782842b: running
[16:00:10.838] > Acquiring lock on /home/username/.vscode-server/bin/e713fe9b05fc24facbec8f34fb1017133858842b/vscode-remote-lock.username.e713fe9b05fc24facbec8f34fb1017133858842b
[16:00:10.839] > \ln /home/username/.vscode-server/bin/e713fe9b05fc24facbec8f34fb1017133858842b/vscode-remote-lock.username.e713fe9b05fc24facbec8f34fb1017133858842b.target /home/username/.vscode-server/bin/e713fe9b05fc24facbec8f34fb1017133858842b/vscode-remote-lock.username.e713fe9b05fc24facbec8f34fb1017133858842b
> Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> 58500782842b: start
> exitCode==24==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/15399==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 58500782842b: end
[16:00:10.840] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/15399==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[16:00:10.841] Server installation process already in progress - waiting and retrying
[16:00:10.842] Terminating local server
[16:00:10.852] Local server exit: 15
[16:00:11.859] askpass server listening on /run/user/1000/vscode-ssh-askpass-2a8299da82676648b355c2781515321278a2599d.sock
[16:00:11.860] Spawning local server with {"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-eb5b3cd456343fa1379085b33de0724d80b2ab82.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","42647","-o","ConnectTimeout=45","hostname"],"dataFilePath":"/home/geoff/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-hostname-e713fe9b05fc24facbec8f34fb1017133858842b-0.65.4/data.json"}
[16:00:11.860] Local server env: {"DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/geoff/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/geoff/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-2a8299da82676648b355c2781515321278a2599d.sock"}
[16:00:11.868] Spawned 6351
[16:00:11.971] > local-server> Spawned ssh: 6359
[16:00:11.973] stderr> OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
[16:00:12.122] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:cPX6iKKAAPzylaG/vfrrpGqESD8SYwNlQuNeL0iPD6A
[16:00:12.400] Got askpass request: {"request":"username@hostname's password:"}
[16:00:12.400] Showing password prompt
[16:00:12.401] Listening for interwindow password on /run/user/1000/vscode-ssh-askpass-ced033be132e566ccfe3d0442b7cae5ff34aee23.sock
[16:00:12.401] Writing password prompt to globalState
[16:00:27.616] Got password response
[16:00:27.617] Interactor gave response: *************
[16:00:27.617] Cleaning up other-window auth server
[16:00:27.688] stderr> Authenticated to hostname ([128.32.37.243]:22).
[16:00:28.614] > Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-112-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>  System information disabled due to load higher than 48.0
> 
>  * Pure upstream Kubernetes 1.21, smallest, simplest cluster ops!
> 
>      https://microk8s.io/
> 
>  * Canonical Livepatch is available for installation.
>    - Reduce system reboots and improve kernel security. Activate at:
>      https://ubuntu.com/livepatch
> 
> 65 packages can be updated.
> 44 of these updates are security updates.
> To see these additional updates run: apt list --upgradable
> 
> New release '20.04.2 LTS' available.
> Run 'do-release-upgrade' to upgrade to it.
> 
> 
> *** System restart required ***
[16:00:28.637] > ready: 58500782842b
[16:00:28.650] > Linux 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020
[16:00:28.651] Platform: linux
[16:00:28.706] > 58500782842b: running
[16:00:28.836] > Acquiring lock on /home/username/.vscode-server/bin/e713fe9b05fc24facbec8f34fb1017133858842b/vscode-remote-lock.username.e713fe9b05fc24facbec8f34fb1017133858842b
[16:00:28.847] > \ln /home/username/.vscode-server/bin/e713fe9b05fc24facbec8f34fb1017133858842b/vscode-remote-lock.username.e713fe9b05fc24facbec8f34fb1017133858842b.target /home/username/.vscode-server/bin/e713fe9b05fc24facbec8f34fb1017133858842b/vscode-remote-lock.username.e713fe9b05fc24facbec8f34fb1017133858842b
[16:00:28.854] stderr> ln: failed to create hard link '/home/username/.vscode-server/bin/e713fe9b05fc24facbec8f34fb1017133858842b/vscode-remote-lock.username.e713fe9b05fc24facbec8f34fb1017133858842b': File exists
[16:00:28.855] stderr> 
[16:00:28.856] > Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> 58500782842b: start
> exitCode==24==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/15399==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 58500782842b: end
[16:00:28.856] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/15399==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[16:00:28.856] Server installation process already in progress - waiting and retrying
[16:00:28.857] Terminating local server
[16:00:28.866] Local server exit: 15
[16:00:29.874] askpass server listening on /run/user/1000/vscode-ssh-askpass-292db18559757f077c2322ad9fb9dbb9f393a22a.sock
[16:00:29.874] Spawning local server with {"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-97545072b108b242cb7353ac7400cae3a0823698.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","42647","-o","ConnectTimeout=45","hostname"],"dataFilePath":"/home/geoff/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-hostname-e713fe9b05fc24facbec8f34fb1017133858842b-0.65.4/data.json"}
[16:00:29.875] Local server env: {"DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/geoff/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/geoff/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-292db18559757f077c2322ad9fb9dbb9f393a22a.sock"}
[16:00:29.884] Spawned 6377
[16:00:29.987] > local-server> Spawned ssh: 6385
[16:00:29.989] stderr> OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
[16:00:30.082] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:cPX6iKKAAPzylaG/vfrrpGqESD8SYwNlQuNeL0iPD6A
[16:00:30.274] Got askpass request: {"request":"username@hostname's password:"}
[16:00:30.274] Showing password prompt
[16:00:30.275] Listening for interwindow password on /run/user/1000/vscode-ssh-askpass-33975613b82efa15a37a382fd89de0b41a3816a3.sock
[16:00:30.275] Writing password prompt to globalState
```
