### ISSUE TITLE
Unable to establish connection using VS Code 1.65.2 and Remote - SSH v0.65.4

### ISSUE THREAD

**Issue by jethas-bennettjones** [microsoft/vscode-remote-release#5076]
- VSCode Version: 1.65.2
- Local OS Version: Windows 10 17763.1879
- Remote OS Version: Windows 10 19042.985
- Remote Extension/Connection Type: SSH
- Logs:
```
[13:10:28.774] Log Level: 2
[13:10:28.813] remote-ssh@0.65.4
[13:10:28.813] win32 x64
[13:10:28.814] SSH Resolver called for "ssh-remote+dev-cvd-sj01.dev.bjlocal", attempt 1
[13:10:28.815] "remote.SSH.useLocalServer": false
[13:10:28.815] "remote.SSH.showLoginTerminal": false
[13:10:28.816] "remote.SSH.remotePlatform": {"ubuntu":"linux","dev-cvd-sj01.dev.bjlocal":"windows"}
[13:10:28.816] "remote.SSH.path": undefined
[13:10:28.816] "remote.SSH.configFile": undefined
[13:10:28.816] "remote.SSH.useFlock": true
[13:10:28.817] "remote.SSH.lockfilesInTmp": false
[13:10:28.817] "remote.SSH.localServerDownload": auto
[13:10:28.817] "remote.SSH.remoteServerListenOnSocket": false
[13:10:28.817] "remote.SSH.showLoginTerminal": false
[13:10:28.818] "remote.SSH.defaultExtensions": []
[13:10:28.818] "remote.SSH.loglevel": 2
[13:10:28.818] SSH Resolver called for host: dev-cvd-sj01.dev.bjlocal
[13:10:28.819] Setting up SSH remote "dev-cvd-sj01.dev.bjlocal"
[13:10:28.914] Using commit id "054a9295330880ed74ceaedda236253b4f39a335" and quality "stable" for server
[13:10:28.919] Install and start server if needed
[13:10:28.924] Checking ssh with "ssh -V"
[13:10:29.455] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[13:10:29.465] Remote command length: 5988/8192 characters
[13:10:29.465] Running script with connection command: ssh -T -D 54193 "dev-cvd-sj01.dev.bjlocal" powershell
[13:10:29.606] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[13:10:31.101] > 
[13:10:31.101] Got some output, clearing connection timeout
[13:10:40.319] > Windows PowerShell
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Try the new cross-platform PowerShell https://aka.ms/pscore6Loading personal and
>  system profiles took 886ms.
> 
> 
> PS C:\Users\DEVSJ>
> PS C:\Users\DEVSJ> $uuid="35fb10212ebc"
> PS C:\Users\DEVSJ> "${uuid}: running"
> 35fb10212ebc: running
> PS C:\Users\DEVSJ> "35fb10212ebc: pauseLog"
> 35fb10212ebc: pauseLog
[13:10:41.350] > Acquiring lock on C:\Users\DEVSJ\.vscode-server\bin\054a9295330880ed74ceaedda236
> 253b4f39a335\vscode-remote-lock.054a9295330880ed74ceaedda236253b4f39a335
> Looking for existing server in C:\Users\DEVSJ\.vscode-server\bin\054a9295330880e
> d74ceaedda236253b4f39a335
> Found installed server
> 
[13:10:41.436] > 
> 
>     Directory: C:\Users\DEVSJ\.vscode-server
> 
> 
> Mode                 LastWriteTime         Length Name
> 
> ----                 -------------         ------ ----
> 
> -a----        19/05/2021     13:10              0 .054a9295330880ed74ceaedda2362
> 53b4f39a335.token
> 
[13:10:41.507] > Successfully processed 1 files; Failed processing 0 files
> 
[13:10:41.533] > Successfully processed 1 files; Failed processing 0 files
> 
[13:10:41.568] > Successfully processed 1 files; Failed processing 0 files
> Successfully processed 1 files; Failed processing 0 files
> Starting server: & 'C:\Users\DEVSJ\.vscode-server\bin\054a9295330880ed74ceaedda2
> 36253b4f39a335\server.cmd' --start-server --host=127.0.0.1 --enable-remote-auto-
> shutdown --port=0 --connection-secret 'C:\Users\DEVSJ\.vscode-server\.054a929533
> 0880ed74ceaedda236253b4f39a335.token'   *> 'C:\Users\DEVSJ\.vscode-server\.054a9
> 295330880ed74ceaedda236253b4f39a335.log'
> 
[13:10:45.675] > Server did not start successfully. Full server log at C:\Users\DEVSJ\.vscode-ser
> ver\.054a9295330880ed74ceaedda236253b4f39a335.log >>>
> C:\Users\DEVSJ\.vscode-server\bin\054a9295330880ed74ceaedda236253b4f39a335\serve
> r.cmd :
> internal/modules/cjs/loader.js:883
> At line:1 char:1
> + C:\Users\DEVSJ\.vscode-server\bin\054a9295330880ed74ceaedda236253b4f3 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (internal/modules/cjs/loader.js:883:
> String)
>    [], RemoteException
>     + FullyQualifiedErrorId : NativeCommandError
> 
>   throw err;
>   ^
> 
> Error: Cannot find module 'minimist'
> Require stack:
> - C:\Users\DEVSJ\.vscode-server\bin\054a9295330880ed74ceaedda236253b4f39a335\out
> \vs\serve
> r\main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at start (C:\Users\DEVSJ\.vscode-server\bin\054a9295330880ed74ceaedda236253b
> 4f39a335\
> out\vs\server\main.js:1:287)
>     at Object.<anonymous> (C:\Users\DEVSJ\.vscode-server\bin\054a9295330880ed74c
> eaedda236
> 253b4f39a335\out\vs\server\main.js:12:707)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     'C:\\Users\\DEVSJ\\.vscode-server\\bin\\054a9295330880ed74ceaedda236253b4f39
> a335\\out
> \\vs\\server\\main.js'
>   ]
> }
> <<< End of server log
> 35fb10212ebc: start
> exitCode==32==
> listeningOn====
> osReleaseId==windows==
> osVersion====
> arch==x64==
> platform==windows==
> unpackResult====
> didLocalDownload==False==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==278==
> 35fb10212ebc: end
[13:10:45.676] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==windows==
osVersion====
arch==x64==
platform==windows==
unpackResult====
didLocalDownload==False==
downloadTime====
installTime====
extInstallTime====
serverStartTime==278==

[13:10:45.677] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (c:\Users\jethas\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:64575)
	at c (c:\Users\jethas\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:58900)
	at Object.t.handleInstallOutput (c:\Users\jethas\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:63317)
	at Object.t.tryInstall (c:\Users\jethas\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:413984)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\jethas\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:294518
	at async Object.t.withShowDetailsEvent (c:\Users\jethas\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:405329)
	at async Object.t.resolve (c:\Users\jethas\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:1:295639)
	at async c:\Users\jethas\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.4\out\extension.js:127:110530
[13:10:45.684] ------




[13:10:46.099] > 
> 35fb10212ebc: start
> SSH_AUTH_SOCK====
> listeningOn====
> osReleaseId==windows==
> osVersion==10.0.19042==
> arch==x64==
> platform==windows==
> unpackResult====
> didLocalDownload==False==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==278==
> connectionToken==1111a1a1-1111-11aa-1aaa-111a111a1a11==
> 35fb10212ebc: end
> 1640, watching 3424
> gps : Cannot find a process with the process identifier 6000.
> At line:3 char:7
> + if (!(gps -Id $v_)) {
> server died, exit
> +       ~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (6000:Int32) [Get-Process], Proces
> sCommandException
>     + FullyQualifiedErrorId : NoProcessFoundForGivenId,Microsoft.PowerShell.Comm
> ands.GetProcessCom
>    mand
> 
> 
[13:10:46.438] "install" terminal command done
[13:10:46.439] Install terminal quit with output:    mand
```

Steps to Reproduce:

1. Install VS Code 1.55.2 and the latest Remote - SSH extension
2. Successfully connect to a Windows remote machine using a public key
3. Update to VS Code 1.56.2
4. Retry the connection and note that it fails to complete.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by jethas-bennettjones** [comment]
I downgraded VS to 1.55.2 and I was able to successfully connect once again.

**Comment by foorschtbar** [comment]
Same problem here. I cant connect to a Rasbian system since update to 1.56. Downgrade to 1.55 and it works again. Error message `The VS Code Server failed to start`

**Comment by jethas-bennettjones** [comment]
VSCode auto-updated to 1.65.2 today and this issue re-appeared. Has a fix for this been planned out yet?

**Comment by ayush-j** [comment]
It has started working again for me in

```yaml
Version: 1.57.0-insider (user setup)
Commit: bf84ee619e0b67443d0307c04348fa575bc3c363
Date: 2021-06-07T12:46:22.208Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by jethas-bennettjones** [comment]
Funny, the expected release date for 1.57 is today or tomorrow. Fingers crossed it gets released this week!

**Comment by foorschtbar** [comment]
Still the same problem with:

Version: 1.57.0 (user setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z (2 days ago)
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

Please reopen!

**Comment by jethas-bennettjones** [comment]
My issue was resolved, but I'll reopen the ticket.
What version of the extension are you using?

**Comment by foorschtbar** [comment]
Thank u for reopening. I found the issue. I switched my Rasbian to aarch64. After switch the kernal back to 32bit, it works. Thats fine for me at the moment.

**Comment by bamurtaugh** [comment]
Thanks for the discussion here! It seems like the issue has been resolved for you both? If you're still experiencing this in the latest versions of VS Code + Remote - SSH, please just let me know, and I'm happy to reopen.
