### ISSUE TITLE
Unable to debug on a remote host "/usr/bin/bash: No such file or directory"

### ISSUE THREAD

**Issue by SamPovilus** [microsoft/vscode-remote-release#5098]
- VSCode Version:  1.57.0-insiders 2021-05-25 286b643
- Local OS Version: Windows 10 and Debian testing 
- Remote OS Version: Debian testing and Ubuntu 20.04
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. Install Remote - SSH extension
2. Install C/C++ extension
3. Connect to a Linux host
4. create a trivial c++ program
5. attempt to debug the program
6. get a message that pops up in the terminal "/usr/bin/bash: No such file or directory"  very quickly and then the terminal dissappears.
7. The debug session appears to be running, but not connected to vscode (the debug shows up in the Call Stack window)
Note this happens in both windows and linux and /usr/bin/bash does exsist on both remote os's

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bamurtaugh** [comment]
Thanks for reporting @SamPovilus. Does everything else work normally (i.e. editing files, saving)? Can you check the Log (Window) output channel for errors? Can you check whether the "Remote Extension Host" entry is missing from the output channel too?

Trying to see if this could be similar to https://github.com/microsoft/vscode-remote-release/issues/4439.

**Comment by SamPovilus** [comment]
I'm not a GUI guy so I might provide the wrong info. Debugging is the only thing I've noticed not working.  I don't think it's related to #4439, it only shows up in Insiders ( 1.57.0-insiders) I tried it on 1.56.0 (not insiders) and debugging worked fine.

 here is the "Remote Extension Host" log
`[2021-05-26 11:24:33.906] [exthost] [info] extension host started
[2021-05-26 11:24:34.283] [exthost] [info] ExtensionService#_doActivateExtension cschlosser.doxdocgen {"startup":false,"extensionId":{"value":"cschlosser.doxdocgen","_lower":"cschlosser.doxdocgen"},"activationEvent":"onLanguage:cpp"}
[2021-05-26 11:24:34.284] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/spovilus/.vscode-server-insiders/extensions/cschlosser.doxdocgen-1.3.1/out/extension
[2021-05-26 11:24:34.391] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.cpptools {"startup":false,"extensionId":{"value":"ms-vscode.cpptools","_lower":"ms-vscode.cpptools"},"activationEvent":"onLanguage:cpp"}
[2021-05-26 11:24:34.391] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/spovilus/.vscode-server-insiders/extensions/ms-vscode.cpptools-1.3.1/dist/main
[2021-05-26 11:24:34.508] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-05-26 11:24:34.509] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/spovilus/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/extensions/debug-auto-launch/dist/extension
[2021-05-26 11:24:34.513] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-05-26 11:24:34.513] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/spovilus/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/extensions/git/dist/main
[2021-05-26 11:24:34.575] [exthost] [info] ExtensionService#_doActivateExtension GitHub.vscode-pull-request-github {"startup":true,"extensionId":{"value":"GitHub.vscode-pull-request-github","_lower":"github.vscode-pull-request-github"},"activationEvent":"*"}
[2021-05-26 11:24:34.575] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/spovilus/.vscode-server-insiders/extensions/github.vscode-pull-request-github-0.26.0/dist/extension
[2021-05-26 11:24:34.681] [exthost] [info] ExtensionService#_doActivateExtension mhutchie.git-graph {"startup":true,"extensionId":{"value":"mhutchie.git-graph","_lower":"mhutchie.git-graph"},"activationEvent":"*"}
[2021-05-26 11:24:34.681] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/spovilus/.vscode-server-insiders/extensions/mhutchie.git-graph-1.30.0/out/extension.js
[2021-05-26 11:24:34.705] [exthost] [info] ExtensionService#_doActivateExtension ms-vsliveshare.vsliveshare {"startup":true,"extensionId":{"value":"ms-vsliveshare.vsliveshare-audio","_lower":"ms-vsliveshare.vsliveshare-audio"},"activationEvent":"*"}
[2021-05-26 11:24:34.706] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/spovilus/.vscode-server-insiders/extensions/ms-vsliveshare.vsliveshare-1.0.4272/out/prod/extension-prod
[2021-05-26 11:24:40.922] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2021-05-26 11:24:40.922] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/spovilus/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/extensions/ms-vscode.js-debug/src/extension.js
[2021-05-26 11:24:41.147] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":false,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-05-26 11:24:41.147] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/spovilus/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/extensions/github/dist/extension.js
[2021-05-26 11:24:44.379] [exthost] [info] ExtensionService#_doActivateExtension ms-vsliveshare.vsliveshare-audio {"startup":true,"extensionId":{"value":"ms-vsliveshare.vsliveshare-audio","_lower":"ms-vsliveshare.vsliveshare-audio"},"activationEvent":"*"}
[2021-05-26 11:24:44.379] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/spovilus/.vscode-server-insiders/extensions/ms-vsliveshare.vsliveshare-audio-0.1.91/out/extension
[2021-05-26 11:24:45.236] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":false,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"onStartupFinished"}
[2021-05-26 11:24:45.236] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/spovilus/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/extensions/emmet/dist/node/emmetNodeMain
[2021-05-26 11:24:45.251] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
[2021-05-26 11:24:45.251] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/spovilus/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/extensions/merge-conflict/dist/mergeConflictMain
[2021-05-26 11:24:45.255] [exthost] [info] ExtensionService#_doActivateExtension vscode.testing-editor-contributions {"startup":false,"extensionId":{"value":"vscode.testing-editor-contributions","_lower":"vscode.testing-editor-contributions"},"activationEvent":"onStartupFinished"}
[2021-05-26 11:24:45.255] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/spovilus/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/extensions/testing-editor-contributions/dist/extension.js
[2021-05-26 11:24:45.356] [exthost] [info] eager extensions activated
[2021-05-26 11:24:58.173] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-server-ready {"startup":false,"extensionId":{"value":"vscode.debug-server-ready","_lower":"vscode.debug-server-ready"},"activationEvent":"onDebugResolve"}
[2021-05-26 11:24:58.174] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/spovilus/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/extensions/debug-server-ready/dist/extension
[2021-05-26 11:24:58.243] [exthost] [info] ExtensionService#_doActivateExtension vscode.grunt {"startup":false,"extensionId":{"value":"vscode.grunt","_lower":"vscode.grunt"},"activationEvent":"onCommand:workbench.action.tasks.runTask"}
[2021-05-26 11:24:58.243] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/spovilus/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/extensions/grunt/dist/main
[2021-05-26 11:24:58.250] [exthost] [info] ExtensionService#_doActivateExtension vscode.gulp {"startup":false,"extensionId":{"value":"vscode.gulp","_lower":"vscode.gulp"},"activationEvent":"onCommand:workbench.action.tasks.runTask"}
[2021-05-26 11:24:58.250] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/spovilus/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/extensions/gulp/dist/main
[2021-05-26 11:24:58.257] [exthost] [info] ExtensionService#_doActivateExtension vscode.jake {"startup":false,"extensionId":{"value":"vscode.jake","_lower":"vscode.jake"},"activationEvent":"onCommand:workbench.action.tasks.runTask"}
[2021-05-26 11:24:58.257] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/spovilus/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/extensions/jake/dist/main
[2021-05-26 11:24:58.263] [exthost] [info] ExtensionService#_doActivateExtension vscode.npm {"startup":false,"extensionId":{"value":"vscode.npm","_lower":"vscode.npm"},"activationEvent":"onCommand:workbench.action.tasks.runTask"}
[2021-05-26 11:24:58.263] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/spovilus/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/extensions/npm/dist/npmMain
[2021-05-26 11:24:58.324] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"extensionId":{"value":"vscode.typescript-language-features","_lower":"vscode.typescript-language-features"},"activationEvent":"onCommand:workbench.action.tasks.runTask"}
[2021-05-26 11:24:58.324] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/spovilus/.vscode-server-insiders/bin/286b643ecd231f66f3f2e67e1456f3c601838b46/extensions/typescript-language-features/dist/extension
[2021-05-26 11:24:58.359] [exthost] [info] ExtensionService#_doActivateExtension ms-azuretools.vscode-docker {"startup":false,"extensionId":{"value":"ms-azuretools.vscode-docker","_lower":"ms-azuretools.vscode-docker"},"activationEvent":"onCommand:workbench.action.tasks.runTask"}
[2021-05-26 11:24:58.359] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/spovilus/.vscode-server-insiders/extensions/ms-azuretools.vscode-docker-1.13.0/main
`

And this is the only error I see in any other logs (in the developer tools console)
`
 ERR Cannot have two contributions with the same id editor.contrib.acceptChangesButton: Error: Cannot have two contributions with the same id editor.contrib.acceptChangesButton
    at new cn (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:658:76373)
    at h._createInstance (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1374)
    at h.createInstance (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:793)
    at ta.createEditorControl (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2369:27086)
    at ta.createEditor (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2369:26697)
    at ta.create (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1457:57923)
    at u.doCreateEditorPane (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2369:134541)
    at u.doShowEditorPane (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2369:134116)
    at u.openEditor (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2369:133665)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2579:16066
    at bi.doShowEditor (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2579:16247)
    at bi.openEditor (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2579:15840)
    at F.openEditor (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2415:152404)
    at async Object.run (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2749:12900)
notificationsAlerts.ts:40 The terminal process "bash ''" failed to launch (exit code: 127).
onDidChangeNotification @ notificationsAlerts.ts:40
`

**Comment by SamPovilus** [comment]
Bug does appears to be resolved in today's version, (a18ea9c9)
