### ISSUE TITLE
Can't start container with `forwardPorts` on latest VSCode Insiders

### ISSUE THREAD

**Issue by tomferon** [microsoft/vscode-remote-release#5102]
Version: 1.57.0-insider (user setup)
Commit: a18ea9c9ec25c59e599ba3c2eb668315546dd269
Date: 2021-05-26T05:14:06.346Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
Remote Extension/Connection Type: Docker
Docker desktop: 3.3.3 (64133)

Steps to Reproduce:

1. Create a project with a port in `forwardPorts` in `.devcontainer/devcontainer.json`.
2. Open it in a container.

It started to happen after upgrading to the latest insider version. 

**Workaround**: Removing `forwardPorts`.

Error in the logs:

```
[5998 ms] Start: Run in container: echo 41363 >/home/vscode/.vscode-server-insiders/data/Machine/.devport
[6002 ms] 
[6003 ms] 
[6003 ms] Port forwarding for container port 41363 starts listening on local port.
[6006 ms] Port forwarding local port 41363 to container port 41363
[6065 ms] TypeError: Cannot read property 'port' of null
    at m.waitForReady (file:///C:/Users/[user]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2844:1471)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async P.forward (file:///C:/Users/[user]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1989:26348)
    at async S.$openTunnel (file:///C:/Users/[user]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1989:35965)
```

Full log:

```
[472 ms] Remote-Containers 0.179.0 in VS Code 1.57.0-insider (a18ea9c9ec25c59e599ba3c2eb668315546dd269).
[471 ms] Start: Resolving Remote
[474 ms] Start: Run: wsl -d Ubuntu -e wslpath -u \\wsl$\Ubuntu\home\[user]\[project]
[629 ms] Start: Run: wsl -d Ubuntu
[800 ms] Setting up container for folder or workspace: /home/[user]/[project]
[803 ms] Start: Check Docker is running
[804 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/[user]/[project]' && DISPLAY='1' ELECTRON_RUN_AS_NODE='1' SSH_ASKPASS='c:\Users\[user]\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.179.0\scripts\ssh-askpass.bat' VSCODE_SSH_ASKPASS_NODE='C:\Users\[user]\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe' VSCODE_SSH_ASKPASS_MAIN='c:\Users\[user]\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.179.0\dist\common\sshAskpass.js' VSCODE_SSH_ASKPASS_HANDLE='\\.\pipe\ssh-askpass-fa9377fdd24596a19155aef660cb3dd55d3f8023-sock' DOCKER_CONTEXT='default' VSCODE_SSH_ASKPASS_COUNTER='1' docker 'version' '--format' '{{.Server.APIVersion}}'
[1071 ms] Server API version: 1.41
[1572 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/[user]/[project]' && git 'rev-parse' '--show-cdup'
[1783 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/[user]/[project]' && DISPLAY='1' ELECTRON_RUN_AS_NODE='1' SSH_ASKPASS='c:\Users\[user]\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.179.0\scripts\ssh-askpass.bat' VSCODE_SSH_ASKPASS_NODE='C:\Users\[user]\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe' VSCODE_SSH_ASKPASS_MAIN='c:\Users\[user]\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.179.0\dist\common\sshAskpass.js' VSCODE_SSH_ASKPASS_HANDLE='\\.\pipe\ssh-askpass-fa9377fdd24596a19155aef660cb3dd55d3f8023-sock' DOCKER_CONTEXT='default' VSCODE_SSH_ASKPASS_COUNTER='2' docker 'ps' '-q' '-a' '--filter' 'label=vsch.local.folder=\\wsl$\Ubuntu\home\[user]\[project]' '--filter' 'label=vsch.quality=insider'
[2144 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/[user]/[project]' && DISPLAY='1' ELECTRON_RUN_AS_NODE='1' SSH_ASKPASS='c:\Users\[user]\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.179.0\scripts\ssh-askpass.bat' VSCODE_SSH_ASKPASS_NODE='C:\Users\[user]\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe' VSCODE_SSH_ASKPASS_MAIN='c:\Users\[user]\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.179.0\dist\common\sshAskpass.js' VSCODE_SSH_ASKPASS_HANDLE='\\.\pipe\ssh-askpass-fa9377fdd24596a19155aef660cb3dd55d3f8023-sock' DOCKER_CONTEXT='default' VSCODE_SSH_ASKPASS_COUNTER='3' docker 'inspect' '--type' 'container' 'c83bd186fc82'
[2480 ms] Start: Starting container
[2480 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/[user]/[project]' && DISPLAY='1' ELECTRON_RUN_AS_NODE='1' SSH_ASKPASS='c:\Users\[user]\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.179.0\scripts\ssh-askpass.bat' VSCODE_SSH_ASKPASS_NODE='C:\Users\[user]\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe' VSCODE_SSH_ASKPASS_MAIN='c:\Users\[user]\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.179.0\dist\common\sshAskpass.js' VSCODE_SSH_ASKPASS_HANDLE='\\.\pipe\ssh-askpass-fa9377fdd24596a19155aef660cb3dd55d3f8023-sock' DOCKER_CONTEXT='default' VSCODE_SSH_ASKPASS_COUNTER='4' docker 'start' 'c83bd186fc82a4d977aa453719d5a6befeb7ba8503f99c049678170b4aa25d16'
[3069 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/[user]/[project]' && DISPLAY='1' ELECTRON_RUN_AS_NODE='1' SSH_ASKPASS='c:\Users\[user]\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.179.0\scripts\ssh-askpass.bat' VSCODE_SSH_ASKPASS_NODE='C:\Users\[user]\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe' VSCODE_SSH_ASKPASS_MAIN='c:\Users\[user]\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.179.0\dist\common\sshAskpass.js' VSCODE_SSH_ASKPASS_HANDLE='\\.\pipe\ssh-askpass-fa9377fdd24596a19155aef660cb3dd55d3f8023-sock' DOCKER_CONTEXT='default' VSCODE_SSH_ASKPASS_COUNTER='5' docker 'ps' '-q' '-a' '--filter' 'label=vsch.local.folder=\\wsl$\Ubuntu\home\[user]\[project]' '--filter' 'label=vsch.quality=insider'
[3417 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/[user]/[project]' && DISPLAY='1' ELECTRON_RUN_AS_NODE='1' SSH_ASKPASS='c:\Users\[user]\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.179.0\scripts\ssh-askpass.bat' VSCODE_SSH_ASKPASS_NODE='C:\Users\[user]\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe' VSCODE_SSH_ASKPASS_MAIN='c:\Users\[user]\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.179.0\dist\common\sshAskpass.js' VSCODE_SSH_ASKPASS_HANDLE='\\.\pipe\ssh-askpass-fa9377fdd24596a19155aef660cb3dd55d3f8023-sock' DOCKER_CONTEXT='default' VSCODE_SSH_ASKPASS_COUNTER='6' docker 'inspect' '--type' 'container' 'c83bd186fc82'
[3746 ms] Start: Inspecting container
[3747 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/[user]/[project]' && DISPLAY='1' ELECTRON_RUN_AS_NODE='1' SSH_ASKPASS='c:\Users\[user]\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.179.0\scripts\ssh-askpass.bat' VSCODE_SSH_ASKPASS_NODE='C:\Users\[user]\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe' VSCODE_SSH_ASKPASS_MAIN='c:\Users\[user]\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.179.0\dist\common\sshAskpass.js' VSCODE_SSH_ASKPASS_HANDLE='\\.\pipe\ssh-askpass-fa9377fdd24596a19155aef660cb3dd55d3f8023-sock' DOCKER_CONTEXT='default' VSCODE_SSH_ASKPASS_COUNTER='7' docker 'inspect' '--type' 'container' 'c83bd186fc82a4d977aa453719d5a6befeb7ba8503f99c049678170b4aa25d16'
[4084 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/[user]/[project]' && DISPLAY='1' ELECTRON_RUN_AS_NODE='1' SSH_ASKPASS='c:\Users\[user]\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.179.0\scripts\ssh-askpass.bat' VSCODE_SSH_ASKPASS_NODE='C:\Users\[user]\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe' VSCODE_SSH_ASKPASS_MAIN='c:\Users\[user]\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.179.0\dist\common\sshAskpass.js' VSCODE_SSH_ASKPASS_HANDLE='\\.\pipe\ssh-askpass-fa9377fdd24596a19155aef660cb3dd55d3f8023-sock' DOCKER_CONTEXT='default' VSCODE_SSH_ASKPASS_COUNTER='8' docker 'exec' '-i' '-u' 'vscode' '-e' 'VSCODE_REMOTE_CONTAINERS_SESSION=d479d169-ef3e-4f01-92cc-66115264c5921622099752419' 'c83bd186fc82a4d977aa453719d5a6befeb7ba8503f99c049678170b4aa25d16' '/bin/sh'
[4097 ms] Start: Run in container: uname -m
[4549 ms] x86_64
[4551 ms] 
[4552 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[4556 ms] PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[4557 ms] 
[4561 ms] Start: Run in container: cat /etc/passwd
[4568 ms] Start: Setup shutdown monitor
[4569 ms] Forking shutdown monitor: c:\Users\[user]\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.179.0\dist\shutdown\shutdownMonitorProcess \\.\pipe\vscode-remote-containers-4688d6ad1c143bb38cc345b2ad2554d16de7d027-sock singleContainer Debug c:\Users\[user]\AppData\Roaming\Code - Insiders\logs\20210527T085109\exthost1\ms-vscode-remote.remote-containers 1622099753724
[4591 ms] Start: Run in container: test -d /home/vscode/.vscode-server-insiders
[4605 ms] 
[4605 ms] 
[4607 ms] Start: Run in container: set -o noclobber ; mkdir -p '/home/vscode/.vscode-server-insiders/data/Machine' && { > '/home/vscode/.vscode-server-insiders/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[4615 ms] 
[4616 ms] 
[4616 ms] Exit code 2
[4617 ms] Start: Run in container: cat /home/vscode/.vscode-server-insiders/data/Machine/settings.json
[4621 ms] {
        "terminal.integrated.shell.linux": "/bin/bash",
        "haskell.formattingProvider": "brittany"
}
[4622 ms] 
[4623 ms] Start: Run in container: test -d /home/vscode/.vscode-server-insiders/bin/a18ea9c9ec25c59e599ba3c2eb668315546dd269
[4627 ms] 
[4627 ms] 
[4628 ms] Start: Run in container: test -d /vscode/vscode-server-insiders/bin/x64/a18ea9c9ec25c59e599ba3c2eb668315546dd269-insider
[4632 ms] 
[4632 ms] 
[4633 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/[user]/[project]' && DISPLAY='1' ELECTRON_RUN_AS_NODE='1' SSH_ASKPASS='c:\Users\[user]\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.179.0\scripts\ssh-askpass.bat' VSCODE_SSH_ASKPASS_NODE='C:\Users\[user]\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe' VSCODE_SSH_ASKPASS_MAIN='c:\Users\[user]\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.179.0\dist\common\sshAskpass.js' VSCODE_SSH_ASKPASS_HANDLE='\\.\pipe\ssh-askpass-fa9377fdd24596a19155aef660cb3dd55d3f8023-sock' DOCKER_CONTEXT='default' VSCODE_SSH_ASKPASS_COUNTER='9' docker 'exec' '-i' '-u' 'root' 'c83bd186fc82a4d977aa453719d5a6befeb7ba8503f99c049678170b4aa25d16' '/bin/sh'
[4634 ms] Start: Launching Remote-Containers helper.
[4635 ms] SSH_AUTH_SOCK not set on host.
[4635 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/[user]/[project]' && gpgconf '--list-dir' 'agent-extra-socket'
[4647 ms] Start: Run in container: touch '/vscode/vscode-server-insiders/bin/x64/a18ea9c9ec25c59e599ba3c2eb668315546dd269-insider'
[4940 ms] /home/[user]/.gnupg/S.gpg-agent.extra
[4940 ms] 
[4941 ms] Start: Run in container: gpgconf --list-dir agent-socket
[4948 ms] /home/vscode/.gnupg/S.gpg-agent
[4948 ms] 
[4949 ms] Start: Run in container: gpgconf --list-dir homedir
[4954 ms] /home/vscode/.gnupg
[4955 ms] 
[4956 ms] Start: Run in container: ls '/home/vscode/.gnupg/private-keys-v1.d' 2>/dev/null
[4962 ms] 
[4963 ms] 
[4963 ms] Exit code 2
[4964 ms] Start: Run in container: mkdir -p -m 700 '/home/vscode/.gnupg'
[4967 ms] userEnvProbe: loginShell
[4971 ms] 
[4971 ms] 
[4972 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/[user]/[project]' && gpgconf '--list-dir' 'homedir'
[4986 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-88d92111acfb55debcdb926b80a7479ec6020d18.js' >/tmp/vscode-remote-containers-88d92111acfb55debcdb926b80a7479ec6020d18.js
[5002 ms] 
[5002 ms] 
[5003 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-88d92111acfb55debcdb926b80a7479ec6020d18.js' >/tmp/vscode-remote-containers-server-88d92111acfb55debcdb926b80a7479ec6020d18.js
[5013 ms] 
[5013 ms] 
[5014 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/[user]/[project]' && DISPLAY='1' ELECTRON_RUN_AS_NODE='1' SSH_ASKPASS='c:\Users\[user]\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.179.0\scripts\ssh-askpass.bat' VSCODE_SSH_ASKPASS_NODE='C:\Users\[user]\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe' VSCODE_SSH_ASKPASS_MAIN='c:\Users\[user]\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.179.0\dist\common\sshAskpass.js' VSCODE_SSH_ASKPASS_HANDLE='\\.\pipe\ssh-askpass-fa9377fdd24596a19155aef660cb3dd55d3f8023-sock' DOCKER_CONTEXT='default' VSCODE_SSH_ASKPASS_COUNTER='10' docker 'exec' '-i' '-u' 'vscode' '-e' 'REMOTE_CONTAINERS_SOCKETS=["/home/vscode/.gnupg/S.gpg-agent"]' '-e' 'REMOTE_CONTAINERS_IPC=/tmp/vscode-remote-containers-ipc-88d92111acfb55debcdb926b80a7479ec6020d18.sock' 'c83bd186fc82a4d977aa453719d5a6befeb7ba8503f99c049678170b4aa25d16' '/home/vscode/.vscode-server-insiders/bin/a18ea9c9ec25c59e599ba3c2eb668315546dd269/node' '/tmp/vscode-remote-containers-server-88d92111acfb55debcdb926b80a7479ec6020d18.js'
[5310 ms] Start: Run in container: # Test for /home/vscode/.ssh/known_hosts and ssh
[5313 ms] /home/[user]/.gnupg
[5314 ms] 
[5316 ms] /home/vscode/.ssh/known_hosts exists
[5316 ms] 
[5317 ms] Exit code 1
[5317 ms] Start: Run in container: gpgconf --list-dir homedir
[5323 ms] /home/vscode/.gnupg
[5324 ms] 
[5365 ms] 
[5366 ms] 
[5367 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --system credential.helper '!f() { /home/vscode/.vscode-server-insiders/bin/a18ea9c9ec25c59e599ba3c2eb668315546dd269/node /tmp/vscode-remote-containers-88d92111acfb55debcdb926b80a7479ec6020d18.js $*; }; f' || true
[5381 ms] 
[5382 ms] 
[5383 ms] Start: Preparing Extensions
[5384 ms] Start: Run in container: set -o noclobber ; mkdir -p '/home/vscode/.vscode-server-insiders/data/Machine' && { > '/home/vscode/.vscode-server-insiders/data/Machine/.installExtensionsMarker' ; } 2> /dev/null
[5391 ms] 
[5392 ms] 
[5393 ms] Exit code 2
[5404 ms] Extensions cache, install extensions: None
[5405 ms] Start: Run in container: test -d /home/vscode/.vscode-server-insiders/extensionsCache && ls /home/vscode/.vscode-server-insiders/extensionsCache || true
[5413 ms] bbenoist.nix-1.0.1
dhall.dhall-lang-0.0.4
dhall.vscode-dhall-lsp-server-0.0.4
eamodio.gitlens-11.4.1
github.vscode-pull-request-github-0.26.0
haskell.haskell-1.4.0
janjoerke.align-by-regex-1.0.4
justusadam.language-haskell-3.4.0
tabnine.tabnine-vscode-3.4.4
[5413 ms] 
[5414 ms] Start: Run in container: test -d /vscode/vscode-server-insiders/extensionsCache && ls /vscode/vscode-server-insiders/extensionsCache || true
[5421 ms] asciidoctor.asciidoctor-vscode-2.8.9
bbenoist.nix-1.0.1
dhall.dhall-lang-0.0.4
dhall.vscode-dhall-lsp-server-0.0.4
eamodio.gitlens-11.4.1
github.vscode-pull-request-github-0.26.0
haskell.haskell-1.4.0
janjoerke.align-by-regex-1.0.4
justusadam.language-haskell-3.4.0
tabnine.tabnine-vscode-3.4.4
[5422 ms] 
[5423 ms] Extensions cache, link in container: None
[5425 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd ; readlink /proc/$pid/ns/mnt ; cat /proc/$pid/stat | tr "
[5516 ms] Start: Starting VS Code Server
[5517 ms] Start: Run in container: /home/vscode/.vscode-server-insiders/bin/a18ea9c9ec25c59e599ba3c2eb668315546dd269/server.sh --log debug --force-disable-user-env --use-host-proxy --port 0 --extensions-download-dir /home/vscode/.vscode-server-insiders/extensionsCache --start-server
[5855 ms] Start: Run: wsl -d Ubuntu -e /bin/sh -c cd '/home/[user]/[project]' && gpg-connect-agent 'updatestartuptty' '/bye'
[5996 ms] 

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*

Extension host agent listening on 41363

[5998 ms] Start: Run in container: echo 41363 >/home/vscode/.vscode-server-insiders/data/Machine/.devport
[6002 ms] 
[6003 ms] 
[6003 ms] Port forwarding for container port 41363 starts listening on local port.
[6006 ms] Port forwarding local port 41363 to container port 41363
[6065 ms] TypeError: Cannot read property 'port' of null
    at m.waitForReady (file:///C:/Users/[user]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2844:1471)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async P.forward (file:///C:/Users/[user]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1989:26348)
    at async S.$openTunnel (file:///C:/Users/[user]/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1989:35965)
[6349 ms] userEnvProbe merged PATHs:
Probe:     [truncated]
Container: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Merged:    [truncated]
[6424 ms] [07:16:00] Extension host agent started.
```

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode/commit/2508b33f0d34487178b9b475f2a1452f05374bbc
