### ISSUE TITLE
Unable to remote-ssh - "The VS Code Server failed to start" 

### ISSUE THREAD

**Issue by ayush-j** [microsoft/vscode-remote-release#5150]
Version: 1.57.0-insider (user setup)
Commit: fe1eafc80c07608de52a2f9c99fee103dea77f5e
Date: 2021-06-04T12:21:40.077Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

Getting this error when I try to connect to my SSH server:
`Could not establish connection to "<ssh host>": The VS Code Server failed to start.`

Log:
```
[00:21:08.188] Log Level: 2
[00:21:08.197] remote-ssh-nightly@2021.5.29700
[00:21:08.197] win32 x64
[00:21:08.270] SSH Resolver called for "ssh-remote+<ssh host>", attempt 1
[00:21:08.270] "remote.SSH.useLocalServer": false
[00:21:08.270] "remote.SSH.showLoginTerminal": false
[00:21:08.271] "remote.SSH.remotePlatform": {}
[00:21:08.271] "remote.SSH.path": undefined
[00:21:08.271] "remote.SSH.configFile": undefined
[00:21:08.271] "remote.SSH.useFlock": true
[00:21:08.271] "remote.SSH.lockfilesInTmp": false
[00:21:08.271] "remote.SSH.localServerDownload": auto
[00:21:08.271] "remote.SSH.remoteServerListenOnSocket": false
[00:21:08.271] "remote.SSH.showLoginTerminal": false
[00:21:08.272] "remote.SSH.defaultExtensions": []
[00:21:08.272] "remote.SSH.loglevel": 2
[00:21:08.272] SSH Resolver called for host: <ssh host>
[00:21:08.272] Setting up SSH remote "<ssh host>"
[00:21:08.279] Using commit id "fe1eafc80c07608de52a2f9c99fee103dea77f5e" and quality "insider" for server
[00:21:08.283] Install and start server if needed
[00:21:08.286] Checking ssh with "ssh -V"
[00:21:08.340] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[00:21:08.345] Remote command length: 6003/8192 characters
[00:21:08.345] Running script with connection command: ssh -T -D 50545 "<ssh host>" powershell
[00:21:08.348] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[00:21:08.690] > ]0;C:\WINDOWS\System32\cmd.exe
[00:21:08.691] Got some output, clearing connection timeout
[00:21:10.734] > Windows PowerShell
> Copyright (C) Microsoft Corporation. All rights reserved.   
> 
> Try the new cross-platform PowerShell https://aka.ms/pscore6PS C:\Users\ayjindal>
> PS C:\Users\ayjindal> $uuid="13bdeafabc48"
> PS C:\Users\ayjindal> "${uuid}: running"
> 13bdeafabc48: running
> PS C:\Users\ayjindal> "13bdeafabc48: pauseLog"
> 13bdeafabc48: pauseLog
[00:21:11.066] > 
[00:21:11.606] > Acquiring lock on C:\Users\ayjindal\.vscode-server-insiders\bin\fe1eafc80c07608d
> e52a2f9c99fee103dea77f5e\vscode-remote-lock.fe1eafc80c07608de52a2f9c99fee103dea7
> 7f5e
> Looking for existing server in C:\Users\ayjindal\.vscode-server-insiders\bin\fe1
> eafc80c07608de52a2f9c99fee103dea77f5e
[00:21:11.613] > 
> Found installed server
[00:21:11.627] > 
[00:21:11.669] > 
> 
>     Directory: C:\Users\ayjindal\.vscode-server-insiders
> 
> 
> Mode                 LastWriteTime         Length Name
> 
> ----                 -------------         ------ ----
> 
> -a----          6/7/2021  12:21 AM              0 .fe1eafc80c07608de52a2f9c99fee
> 103dea77f5e.token
[00:21:11.688] > 
[00:21:11.695] > Successfully processed 1 files; Failed processing 0 files
[00:21:11.702] > 
[00:21:11.715] > Successfully processed 1 files; Failed processing 0 files
[00:21:11.742] > Successfully processed 1 files; Failed processing 0 files
[00:21:11.754] > Successfully processed 1 files; Failed processing 0 files
> Starting server: & 'C:\Users\ayjindal\.vscode-server-insiders\bin\fe1eafc80c0760
> 8de52a2f9c99fee103dea77f5e\server.cmd' --start-server --host=127.0.0.1 --enable-
> remote-auto-shutdown --port=0 --connection-secret 'C:\Users\ayjindal\.vscode-ser
[00:21:11.761] > 
> ver-insiders\.fe1eafc80c07608de52a2f9c99fee103dea77f5e.token'   *> 'C:\Users\ayj
> indal\.vscode-server-insiders\.fe1eafc80c07608de52a2f9c99fee103dea77f5e.log'    
[00:21:15.845] > Server did not start successfully. Full server log at C:\Users\ayjindal\.vscode-
> server-insiders\.fe1eafc80c07608de52a2f9c99fee103dea77f5e.log >>>
[00:21:15.851] > 
> C:\Users\ayjindal\.vscode-server-insiders\bin\fe1eafc80c07608de52a2f9c99fee103de
> a77f5e\server.cmd :
> internal/modules/cjs/loader.js:883
> At line:1 char:1
> + C:\Users\ayjindal\.vscode-server-insiders\bin\fe1eafc80c07608de52a2f9 ...     
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (internal/modules/cjs/loader.js:883:
> String) [], RemoteException
>     + FullyQualifiedErrorId : NativeCommandError
> 
>   throw err;
>   ^
> 
> Error: Cannot find module 'minimist'
> Require stack:
> - C:\Users\ayjindal\.vscode-server-insiders\bin\fe1eafc80c07608de52a2f9c99fee103
> dea77f5e\out\vs\server\main.js
[00:21:15.857] > 
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15) 
>     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at start
> (C:\Users\ayjindal\.vscode-server-insiders\bin\fe1eafc80c07608de52a2f9c99fee103d
> ea77f5e\out\vs\server\main.js:1:287)
>     at Object.<anonymous>
> (C:\Users\ayjindal\.vscode-server-insiders\bin\fe1eafc80c07608de52a2f9c99fee103d
> ea77f5e\out\vs\server\main.js:12:707)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)   
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
> 
> 'C:\\Users\\ayjindal\\.vscode-server-insiders\\bin\\fe1eafc80c07608de52a2f9c99fe
> e103dea77f5e\\out\\vs\\server\\main.js'
>   ]
> }
> <<< End of server log
> 13bdeafabc48: start
[00:21:15.868] > 
> exitCode==32==
> listeningOn====
> osReleaseId==windows==
> osVersion====
> arch==x64==
> platform==windows==
> unpackResult====
> didLocalDownload==False==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==200==
> 13bdeafabc48: end
[00:21:15.868] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==windows==
osVersion====
arch==x64==
platform==windows==
unpackResult====
didLocalDownload==False==
downloadTime====
installTime====
extInstallTime====
serverStartTime==200==

[00:21:15.869] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:1:64593)
	at c (c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:1:58918)
	at Object.t.handleInstallOutput (c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:1:63335)
	at Object.t.tryInstall (c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:1:415135)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:1:294918
	at async Object.t.withShowDetailsEvent (c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:1:406463)
	at async Object.t.resolve (c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:1:295994)
	at async c:\Users\ayjindal\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:127:110656
[00:21:15.874] ------




[00:21:16.263] > 
[00:21:16.269] > 13bdeafabc48: start
> SSH_AUTH_SOCK====
> listeningOn====
> osReleaseId==windows==
> osVersion==10.0.19043==
> arch==x64==
> platform==windows==
> unpackResult====
> didLocalDownload==False==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==200==
> connectionToken==aa111111-11a1-1a11-1aaa-a1a111a1aaa1==
> 13bdeafabc48: end
> 18228, watching 16488
> gps : Cannot find a process with the process identifier 3752.
> At line:3 char:7
> + if (!(gps -Id $v_)) {
> +       ~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (3752:Int32) [Get-Process], Proces
> sCommandException
>     + FullyQualifiedErrorId : NoProcessFoundForGivenId,Microsoft.PowerShell.Comm
> ands.GetProcessCommand
> 
> server died, exit
[00:21:17.528] "install" terminal command done
[00:21:17.529] Install terminal quit with output: server died, exit

```

**Comment by bamurtaugh** [comment]
Potentially related to https://github.com/microsoft/vscode-remote-release/issues/5076
