### ISSUE TITLE
VS Code Remote SSH keeps asking for password

### ISSUE THREAD

**Issue by jsamarth** [microsoft/vscode-remote-release#5164]
When I try to connect to my remote host, I keep getting asked to enter my password again, despite entering it correctly. I have looked at other issues and managed to fix this by deleting the .vscode_server and then retrying, but this problem has happened multiple times with me, roughly thrice in the past month. There needs to be a permanent fix to this. Some issues related to this: [2728](https://github.com/microsoft/vscode-remote-release/issues/2728) [2518](https://github.com/microsoft/vscode-remote-release/issues/2518)

- VSCode Version: 1.56.2 
- Local OS Version: Mac OS Big Sur 11.2.3
- Remote OS Version: Linux 4.1.12-124.46.4.1.el7uek.x86_64
- Remote Extension/Connection Type: SSH
- Logs: 
```
[16:06:39.494] Spawned 77923
[16:06:39.614] > local-server> Spawned ssh: 77926
[16:06:39.617] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[16:06:39.978] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:z8p0qPIVIgHIogdb7HqdIh3FL/1Z+j9/StflLhYHE0g
[16:06:40.382] Got askpass request: {"request":"samajain@slc16ljq's password:"}
[16:06:40.382] Showing password prompt
[16:06:40.383] Listening for interwindow password on /var/folders/1q/c9rzy7791v3bgd64673ldrl00000gn/T/vscode-ssh-askpass-de3c6a1761a385578b212c79bf12bc5e1730e05e.sock
[16:06:40.383] Writing password prompt to globalState
[16:06:42.154] Password dialog canceled
[16:06:42.154] Interactor signaled cancel
[16:06:42.155] Cleaning up other-window auth server
[16:06:42.262] stderr> Permission denied, please try again.
[16:06:42.382] Got askpass request: {"request":"samajain@slc16ljq's password:"}
[16:06:42.479] stderr> Permission denied, please try again.
[16:06:42.595] Got askpass request: {"request":"samajain@slc16ljq's password:"}
[16:06:42.712] stderr> samajain@slc16ljq: Permission denied (publickey,password).
[16:06:42.717] > local-server> ssh child died, shutting down
[16:06:42.718] Local server exit: 0
[16:06:42.718] Received install output: OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:z8p0qPIVIgHIogdb7HqdIh3FL/1Z+j9/StflLhYHE0g
Permission denied, please try again.
Permission denied, please try again.
samajain@slc16ljq: Permission denied (publickey,password).

[16:06:42.719] Resolver error: Error: Permission denied (publickey,password).
	at Function.Create (/Users/samajain/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:64641)
	at /Users/samajain/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:62835
	at Object.t.handleInstallOutput (/Users/samajain/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:63220)
	at Object.e [as tryInstallWithLocalServer] (/Users/samajain/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:386419)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/samajain/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:294035
	at async Object.t.withShowDetailsEvent (/Users/samajain/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:405329)
	at async /Users/samajain/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:384890
	at async E (/Users/samajain/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:381658)
	at async Object.t.resolveWithLocalServer (/Users/samajain/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:384517)
	at async Object.t.resolve (/Users/samajain/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:295505)
	at async /Users/samajain/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:127:110530
[16:06:42.724] ------

```

**Comment by ff4c00** [comment]
Yes, I also encountered this problem after the update this morning.
I can make sure the password is correct, but I always prompt for the password

**Comment by roblourens** [comment]
This is just ssh telling us that your password is wrong. Make sure the user and everything else with your ssh config is correct.
