### ISSUE TITLE
Failed to install vscode-server in remote arm device

### ISSUE THREAD

**Issue by KawaiiZapic** [microsoft/vscode-remote-release#5175]
Issue Type: <b>Bug</b>

1. Connect to a arm device by SSH
2. Failed to start vscode-server: `/root/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/server.sh: /root/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/node: not found `

System: Ubuntu 18.04 on by Linux Deploy,Android 10 with Linux Kernel 3.18, armv8l

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042
Fetching remote diagnostics for 'SSH' failed: The VS Code Server failed to start

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3475S CPU @ 2.90GHz (4 x 2893)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.96GB (3.25GB free)|
|Process Argv|--crash-reporter-id 5105ae50-dff5-4d16-abfd-fc7ad836bc7e|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: The VS Code Server failed to start
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
vscod805cf:30301675
binariesv517cf:30312826

```

</details>

**Comment by roblourens** [comment]
Most likely your remote linux distro does not meet the requirements here https://code.visualstudio.com/docs/remote/linux

**Comment by KawaiiZapic** [comment]
> Most likely your remote linux distro does not meet the requirements here https://code.visualstudio.com/docs/remote/linux

It working well before(at April,2021).    
In the docs it says Ubuntu need >= 16.04, and need these packages:  
>Requires kernel >= 3.10, glibc >= 2.17, libstdc++ >= 3.4.18. Debian < 8 (Jessie) and Ubuntu < 14.04 do not meet this requirement.   

So I check the requirements in the list:    
*"已安装" == "Installed"*   
```
root@localhost:~# uname -a
Linux localhost 3.18.140-Triton☄Atmosphere💨 #1 SMP PREEMPT Thu Jul 2 11:36:33 MSK 2020 armv8l armv8l armv8l GNU/Linux
root@localhost:~# apt list --installed glibc libstdc++6 libc6 python-minimal ca-certificates tar openssh-server bash wget
正在列表... 完成
bash/bionic,now 4.4.18-2ubuntu1 arm64 [已安装]
ca-certificates/bionic,now 20180409 all [已安装]
libc6/bionic,now 2.27-3ubuntu1 arm64 [已安装]
libstdc++6/bionic,now 8-20180414-1ubuntu2 arm64 [已安装]
openssh-server/bionic,now 1:7.6p1-4 arm64 [已安装]
python-minimal/bionic,now 2.7.15~rc1-1 arm64 [已安装，自动]
tar/bionic,now 1.29b-2 arm64 [已安装]
wget/bionic,now 1.19.4-1ubuntu2 arm64 [已安装]
```    
  
I also try to disable all extensions except remote extensions,language pack and theme, but change nothing.  
  
I try to replace node providing by vscode with node(v14.16.1) install by apt,now it ouput something more detailed:  
  
<details>
<summary>Output</summary>
  
```    
root@localhost:~/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c# mv node node_backup
root@localhost:~/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c# ln /usr/bin/node /root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/
root@localhost:~/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c# node -v
v14.16.1
root@localhost:~/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c# ./server.sh


*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*

Extension host agent listening on 8000

[08:48:23] Extension host agent started.
Error: /root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/node_modules/spdlog/build/Release/spdlog.node: wrong ELF class: ELFCLASS32
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/node_modules/spdlog/index.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/loader.js:5:101)
    at r.load (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/loader.js:4:1722)
    at r.load (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/loader.js:3:10249)
    at l (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/loader.js:5:10314)
    at Object.errorback (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/loader.js:5:10435)
    at r.triggerErrorback (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/loader.js:3:10613)
    at /root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/loader.js:3:10319
    at r.load (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/loader.js:4:1739)
    at r.load (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/loader.js:3:10249)
    at l (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/loader.js:5:10314)
    at r._loadModule (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/loader.js:5:10444)
    at r._resolve (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/loader.js:6:452)
    at r.defineModule (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/loader.js:5:6145)
    at r._relativeRequire (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/loader.js:5:6831)
    at n (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/loader.js:5:9420)
    at d (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostAgent.js:81:23283)
    at new Promise (<anonymous>)
    at p (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostAgent.js:81:23263)
    at _createSpdLogLogger (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostAgent.js:81:24243)
    at new _ (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostAgent.js:81:24059)
    at /root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostAgent.js:155:126
    at new H (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostAgent.js:124:1608)
    at Object.pe [as createServer] (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostAgent.js:139:341)
    at Object.t [as createServer] (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/remoteExtensionHostAgent.js:155:1315)
    at /root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/main.js:1:782
    at async Server.<anonymous> (/root/.vscode-server/bin/b4c1bd0a9b03c749ea011b06c6d2676c8091a70c/out/vs/server/main.js:12:99) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}
[08:48:33] [Error: ENOENT: no such file or directory, scandir '/root/.vscode-remote/data/logs'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/root/.vscode-remote/data/logs'
}  
```
</details>

**Comment by KawaiiZapic** [comment]
I asked my friend to take a test in another arm device but they could not reproduce this problem, maybe there is something wrong in my environment, I'll have a check and retry.

**Comment by bamurtaugh** [comment]
Hey @KawaiiZapic, did you have a chance to try this out again?

**Comment by KawaiiZapic** [comment]
> Hey @KawaiiZapic, did you have a chance to try this out again?

Problem still...   
I try to re-install my env, but change nothing.

**Comment by KawaiiZapic** [comment]
> > Hey @KawaiiZapic, did you have a chance to try this out again?
> 
> Problem still...
> I try to re-install my env, but change nothing.
> Maybe there is some problems in my device, because none of my firends facing this problem.
> One of them has a try on a Raspberry Pie without any error.

I try on a Android 10 with Linux Kernel 4.4.238, Ubuntu 20.04 running in termux v0.111 with proot, and working fine.

**Comment by roblourens** [comment]
Do you have a 32 bit userspace on a 64 bit kernel? This is another issue I've heard of on some of these devices

**Comment by KawaiiZapic** [comment]
> Do you have a 32 bit userspace on a 64 bit kernel? This is another issue I've heard of on some of these devices

I don't know how to check this.  
I'm using the Ubuntu arm64 in linux deploy, and the system is able to run arm64 program.

**Comment by roblourens** [comment]
What do you get for `file /usr/ls`?
