### ISSUE TITLE
Terminal stuck on "Starting ..." for Vagrant Linux VM in Mac

### ISSUE THREAD

**Issue by jfcervera** [microsoft/vscode-remote-release#518]
- VSCode Version: 1.35.0-insider 
- Local OS Version: MacOS Mojave 10.14.5
- Remote OS Version: CentOS 7 3.10.0-957.12.2.el7.x86_64 
- Remote Extension/Connection Type: SSH

Hi, I tried to create a Linux development environment in a Vagrant VM in my Mac. The remote server connection works fine and I can access the remote file system and open files without issues, I can also install extensions.

The issue is that when I try to open a Terminal within VSCode it says "2: Starting ..." on the Terminal dropdown and never opens or gives any errors.

I am using:
Vagrant: 2.2.4
VirtualBox: 5.2.30
Vagrant Box: centos/7 (virtualbox, 1902.01)

Any ideas on what the problem could be? The documentation says that a new terminal will be opened in the remote server.

Thanks

**Comment by Tyriar** [comment]
@jfcervera once connected could you turn on trace logging (F1, "log level", select trace), try open a terminal (ctrl+shift+`) then open the remote extension host logs (cmd+shift+u, on dropdown select remote extension host) and let me know what it says. It will print your terminal environment, feel free to replace that with {} if it's sensitive.

**Comment by jfcervera** [comment]
@Tyriar I did that but nothing is coming in the logs when I open a terminal, see below:

![image](https://user-images.githubusercontent.com/11924772/58689619-6f208c00-837f-11e9-8a45-904e2df7a2d4.png)

This is how it looks, I tried to open several but nothing shows:
![image](https://user-images.githubusercontent.com/11924772/58689560-44cece80-837f-11e9-9c1b-85977fcb215e.png)

In case that it is of any help, this is the ssh-config (which I generated with vagrant ssh-config)

Host dev-vm
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile xxxxxxxxxxxxxx
  IdentitiesOnly yes
  LogLevel FATAL


Thanks

**Comment by Tyriar** [comment]
Hmm, I'm not sure what's happening here right now. I'll keep an eye out for other issues where the terminal is stuck at "Starting...", thanks.

**Comment by jfcervera** [comment]
@Tyriar I have tried again a couple of times and this time I have looked in all the Logs and I see a block similar to the following each time I try a terminal in the "Log (Window)" one:

[2019-06-05 16:01:39.211] [renderer1] [trace] IPty#resize 235 27
[2019-06-05 16:01:39.259] [renderer1] [trace] [storage state.vscdb] updateItems(): insert(Map(1) {workbench.panelpart.activepanelid => workbench.panel.terminal}), delete(Set(0) {})
[2019-06-05 16:01:39.260] [renderer1] [trace] [storage state.vscdb] Trace (event): BEGIN TRANSACTION
[2019-06-05 16:01:39.260] [renderer1] [trace] [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('workbench.panelpart.activepanelid','workbench.panel.terminal')
[2019-06-05 16:01:39.261] [renderer1] [trace] [storage state.vscdb] Trace (event): END TRANSACTION
[2019-06-05 16:01:41.609] [renderer1] [trace] terminalInstance#ctor (id: 5) {}
[2019-06-05 16:01:41.638] [renderer1] [error] Cannot read property 'toString' of null: TypeError: Cannot read property 'toString' of null
	at E.getWorkspaceFolder (/home/vagrant/.vscode-server-insiders/bin/553cfb2c2205db5f15f3ee8395bbd5cf066d357d/out/vs/agent/remoteExtensionHostProcess.js:658:517)
	at S.getWorkspaceFolder (/home/vagrant/.vscode-server-insiders/bin/553cfb2c2205db5f15f3ee8395bbd5cf066d357d/out/vs/agent/remoteExtensionHostProcess.js:661:55)
	at _.<anonymous> (/home/vagrant/.vscode-server-insiders/bin/553cfb2c2205db5f15f3ee8395bbd5cf066d357d/out/vs/agent/remoteExtensionHostProcess.js:625:475)
	at Generator.next (<anonymous>)
	at s (/home/vagrant/.vscode-server-insiders/bin/553cfb2c2205db5f15f3ee8395bbd5cf066d357d/out/vs/agent/remoteExtensionHostProcess.js:13:221)
	at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-06-05 16:01:43.105] [renderer1] [trace] CommandService#executeCommand setContext
[2019-06-05 16:01:43.145] [renderer1] [trace] [storage state.vscdb] updateItems(): insert(Map(1) {workbench.panelpart.activepanelid => workbench.panel.output}), delete(Set(0) {})
[2019-06-05 16:01:43.170] [renderer1] [trace] [storage state.vscdb] Trace (event): BEGIN TRANSACTION
[2019-06-05 16:01:43.209] [renderer1] [trace] [storage state.vscdb] Trace (event): INSERT INTO ItemTable VALUES ('workbench.panelpart.activepanelid','workbench.panel.output')
[2019-06-05 16:01:43.210] [renderer1] [trace] [storage state.vscdb] Trace (event): END TRANSACTION

The file referred to actually exists, it's a minimised js file. 

Not sure whether the above error is related, but I get a new one every time I try to open a new terminal, no other logs seem to change.

There is also the following error at the start of the Log (Window) when I restart VSCode:

[2019-06-05 16:08:54.872] [renderer1] [error] ioctl(2) failed, EBADF: Error: ioctl(2) failed, EBADF
    at UnixTerminal.resize (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/node-pty/lib/unixTerminal.js:227:13)
    at g.resize (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2700:892)
    at C.setDimensions (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3865:843)
    at _processManager._processManager.ptyProcessReady.then (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3711:384)


Hope that helps.

**Comment by Tyriar** [comment]
Thanks this says everything:

> ioctl(2) failed, EBADF: Error: ioctl(2) failed, EBADF

Looks like this issue has the same root cause as https://github.com/microsoft/vscode/issues/71966, but the crashes only happen on Windows.
