### ISSUE TITLE
Getting the error in Vscode remote connection(SSH) 

### ISSUE THREAD

**Issue by ninjasujan** [microsoft/vscode-remote-release#5194]
🚨 The issue tracker is not for questions 🚨
-sh: 28: ‘export: not found
-sh: 29: ‘export: not found
ready: dc86f0b3af2e
Linux 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019
bash: line 1: _exitcode: command not found
bash: line 2: syntax error near unexpected token `elif'
bash: line 2: `	elif [[ $ALLOW_CLIENT_DOWNLOAD == "1" ]]; then'
-sh: 4: function: not found
-sh: 69: [[: not found
-sh: 90: [[: not found
-sh: 155: Syntax error: "(" unexpected (expecting "then")
Transferred: sent 18452, received 4576 bytes, in 2.8 seconds
Bytes per second: sent 6694.6, received 1660.2
dc86f0b3af2e: running
local-server-1> ssh child died, shutting down

[11:29:47.446] Failed to parse remote port from server output
[11:29:47.451] Resolver error: Error: 
	at Function.Create (/home/sujan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:64659)
	at Object.t.handleInstallOutput (/home/sujan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:63302)
	at Object.e [as tryInstallWithLocalServer] (/home/sujan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:387573)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/sujan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:294473
	at async Object.t.withShowDetailsEvent (/home/sujan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:406463)
	at async /home/sujan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:386112
	at async E (/home/sujan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:382710)
	at async Object.t.resolveWithLocalServer (/home/sujan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:385728)
	at async Object.t.resolve (/home/sujan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:295870)
	at async /home/sujan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:127:110656
[11:29:47.464] ------

**Comment by shahman28** [comment]
10:20:52.762] Log Level: 2
[10:20:52.764] remote-ssh@0.65.7
[10:20:52.764] linux x64
[10:20:52.765] SSH Resolver called for "ssh-remote+34.86.58.241", attempt 1
[10:20:52.766] "remote.SSH.useLocalServer": true
[10:20:52.766] "remote.SSH.path": undefined
[10:20:52.766] "remote.SSH.configFile": undefined
[10:20:52.766] "remote.SSH.useFlock": true
[10:20:52.766] "remote.SSH.lockfilesInTmp": false
[10:20:52.766] "remote.SSH.localServerDownload": auto
[10:20:52.767] "remote.SSH.remoteServerListenOnSocket": false
[10:20:52.767] "remote.SSH.showLoginTerminal": false
[10:20:52.767] "remote.SSH.defaultExtensions": []
[10:20:52.767] "remote.SSH.loglevel": 2
[10:20:52.767] SSH Resolver called for host: 34.86.58.241
[10:20:52.767] Setting up SSH remote "34.86.58.241"
[10:20:52.770] Acquiring local install lock: /tmp/vscode-remote-ssh-34.86.58.241-install.lock
[10:20:52.786] Looking for existing server data file at /home/shahman28/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-34.86.58.241-507ce72a4466fbb27b715c3722558bb15afa9f48-0.65.7/data.json
[10:20:52.786] Using commit id "507ce72a4466fbb27b715c3722558bb15afa9f48" and quality "stable" for server
[10:20:52.790] Install and start server if needed
[10:20:52.793] PATH: /home/shahman28/anaconda/bin:/home/shahman28/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[10:20:52.793] Checking ssh with "ssh -V"
[10:20:52.807] > OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
 
[10:20:52.809] askpass server listening on /run/user/1000/vscode-ssh-askpass-46df146ae1045c2ad92b635356f6854e875aa2a3.sock
[10:20:52.809] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-6a918fc3d90efabff69a782b6b28766643c0272c.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","34527","-o","ConnectTimeout=15","34.86.58.241"],"dataFilePath":"/home/shahman28/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-34.86.58.241-507ce72a4466fbb27b715c3722558bb15afa9f48-0.65.7/data.json"}
[10:20:52.810] Local server env: {"DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/shahman28/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/snap/code/67/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/shahman28/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-46df146ae1045c2ad92b635356f6854e875aa2a3.sock"}
[10:20:52.812] Spawned 2483
[10:20:52.876] > local-server-1> Spawned ssh, pid=2491
[10:20:52.877] stderr> OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
[10:20:53.091] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:jka3H2NLqTYeqIgt10ogymE0tXlqkBfaMUwXHYcyOX8
[10:20:53.324] stderr> Authenticated to 34.86.58.241 ([34.86.58.241]:22).
[10:20:53.537] > Welcome to Ubuntu 16.04.7 LTS (GNU/Linux 4.15.0-1098-gcp x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   Get cloud support with Ubuntu Advantage Cloud Guest:
>     http://www.ubuntu.com/business/services/cloud
> 
> UA Infra: Extended Security Maintenance (ESM) is not enabled.
> 
> 3 updates can be applied immediately.
> To see these additional updates run: apt list --upgradable
> 
> 32 additional security updates can be applied with UA Infra: ESM
> Learn more about enabling UA Infra: ESM service at https://ubuntu.com/esm
> 
> New release '18.04.5 LTS' available.
> Run 'do-release-upgrade' to upgrade to it.
> 
[10:20:53.567] > ready: 0ca208eb1e87
[10:20:53.604] > Linux 4.15.0-1098-gcp #111~16.04.1-Ubuntu SMP Tue Apr 13 19:05:08 UTC 2021
[10:20:53.604] Platform: linux
[10:20:53.676] stderr> bash: line 1: _exitcode: command not found
[10:20:53.676] stderr> bash: line 2: syntax error near unexpected token `elif'
[10:20:53.676] stderr> bash: line 2: `	elif [[ $ALLOW_CLIENT_DOWNLOAD == "1" ]]; then'
[10:20:53.677] > 0ca208eb1e87: running
[10:20:53.677] stderr> -sh: 4: function: not found
[10:20:53.679] stderr> -sh: 69: [[: not found
[10:20:53.680] stderr> -sh: 90: [[: not found
[10:20:53.681] stderr> -sh: 155: Syntax error: "(" unexpected (expecting "then")
[10:20:53.682] stderr> Transferred: sent 17916, received 4172 bytes, in 0.4 seconds
[10:20:53.682] stderr> Bytes per second: sent 50094.2, received 11665.2
[10:20:53.682] > local-server-1> ssh child died, shutting down
[10:20:53.684] Local server exit: 0
[10:20:53.685] Received install output: local-server-1> Spawned ssh, pid=2491
OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:jka3H2NLqTYeqIgt10ogymE0tXlqkBfaMUwXHYcyOX8
Authenticated to 34.86.58.241 ([34.86.58.241]:22).
Welcome to Ubuntu 16.04.7 LTS (GNU/Linux 4.15.0-1098-gcp x86_64)
 
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
 
  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud
 
UA Infra: Extended Security Maintenance (ESM) is not enabled.
 
3 updates can be applied immediately.
To see these additional updates run: apt list --upgradable
 
32 additional security updates can be applied with UA Infra: ESM
Learn more about enabling UA Infra: ESM service at https://ubuntu.com/esm
 
New release '18.04.5 LTS' available.
Run 'do-release-upgrade' to upgrade to it.
 
 
ready: 0ca208eb1e87
Linux 4.15.0-1098-gcp #111~16.04.1-Ubuntu SMP Tue Apr 13 19:05:08 UTC 2021
bash: line 1: _exitcode: command not found
bash: line 2: syntax error near unexpected token `elif'
bash: line 2: `	elif [[ $ALLOW_CLIENT_DOWNLOAD == "1" ]]; then'
0ca208eb1e87: running
-sh: 4: function: not found
-sh: 69: [[: not found
-sh: 90: [[: not found
-sh: 155: Syntax error: "(" unexpected (expecting "then")
Transferred: sent 17916, received 4172 bytes, in 0.4 seconds
Bytes per second: sent 50094.2, received 11665.2
local-server-1> ssh child died, shutting down
 
[10:20:53.685] Failed to parse remote port from server output
[10:20:53.686] Resolver error: Error: 
	at Function.Create (/home/shahman28/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:64659)
	at Object.t.handleInstallOutput (/home/shahman28/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:63302)
	at Object.e [as tryInstallWithLocalServer] (/home/shahman28/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:387573)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/shahman28/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:294473
	at async Object.t.withShowDetailsEvent (/home/shahman28/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:406463)
	at async /home/shahman28/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:386112
	at async E (/home/shahman28/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:382710)
	at async Object.t.resolveWithLocalServer (/home/shahman28/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:385728)
	at async Object.t.resolve (/home/shahman28/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:295870)
	at async /home/shahman28/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:127:110656
[10:20:53.689] ------
