### ISSUE TITLE
connect from mac to win10 error

### ISSUE THREAD

**Issue by trobr** [microsoft/vscode-remote-release#5195]
- VSCode Version: 1.56
- Local OS Version: mac os big sur 11.1
- Remote OS Version: win10 10.0.19041.1023
- Remote Extension/Connection Type: ssh
- Logs:
```
[14:03:49.985] > Windows PowerShell
> ��Ȩ���� (C) Microsoft Corporation����������Ȩ����
> 
> �����µĿ�ƽ̨ PowerShell https://aka.ms/pscore6
[14:03:50.084] > PS C:\Users\admin> 
[14:03:50.255] > e
[14:03:50.255] > cho 'ready: c6f71d0cb9b6'
[14:03:50.262] > ready: c6f71d0cb9b6
[14:03:50.263] > 
[14:03:50.267] > PS C:\Users\admin> 
[14:03:50.314] > uname -rsv
[14:03:50.407] stderr> uname : �޷�����uname����ʶ��Ϊ cmdlet���������ű��ļ�������г�������ơ��������Ƶ�ƴд���������·������ȷ��·����
[14:03:50.407] stderr> ȷ��Ȼ������һ�Ρ�
[14:03:50.407] stderr> ����λ�� ��:1 �ַ�: 1
[14:03:50.407] stderr> + uname -rsv
[14:03:50.407] stderr> + ~~~~~
[14:03:50.407] stderr>     + CategoryInfo          : ObjectNotFound: (uname:String) [], CommandNotFoundException
[14:03:50.407] stderr>     + FullyQualifiedErrorId : CommandNotFoundException
[14:03:50.407] stderr>  
[14:03:50.414] > PS C:\Users\admin> 
[14:04:06.216] Terminating local server
[14:04:06.218] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/w/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:64767)
	at Timeout._onTimeout (/Users/w/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.4/out/extension.js:1:264318)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[14:04:06.225] ------




[14:04:06.226] Local server exit: 15

```
Steps to Reproduce:

1.  remote ssh to linux server
2. remote ssh to windows 

The error message show that `uname` not find. I try to set `remote.SSH.remotePlatform` but got same error.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by trobr** [comment]
set `"remote.SSH.useLocalServer": false` resolved
