### ISSUE TITLE
Failing to connect to remote server because main.js module cannot be found

### ISSUE THREAD

**Issue by montallban** [microsoft/vscode-remote-release#5212]
- VSCode Version: 1.57.0
- Local OS Version: Windows 10 19041.1052
- Remote OS Version: Ubuntu 20.04.2 LTS
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. connect to remote terminal (using a ssh config file). This has worked for months up until 1 hour ago.

This used to connect, but now is unable to connect to the server. the following error is thrown:
`> Server did not start successfully. Full server log at /home/michaelm/.vscode-ser
> ver/.b4c1bd0a9b03c749ea011b06c6d2676c8091a70c.log >>>
> internal/modules/cjs/loader.js:883
>   throw err;
>   ^
> 
> Error: Cannot find module '/home/michaelm/.vscode-server/bin/b4c1bd0a9b03c749ea0
> 11b06c6d2676c8091a70c/out/vs/server/main.js'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15) 
>     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js
> :72:12)
>     at internal/main/run_main_module.js:17:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
[14:17:16.164] > 
> <<< End of server log
> 7b49c0835084: start
> exitCode==32==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/1004==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==7998==
> 7b49c0835084: end
[14:17:16.164] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/1004==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==7998==

[14:17:16.165] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64593)
	at c (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:58918)
	at Object.t.handleInstallOutput (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:63335)
	at Object.t.tryInstall (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:415135)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:294918
	at async Object.t.withShowDetailsEvent (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:406463)
	at async Object.t.resolve (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:295994)
	at async c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:127:110656
[14:17:16.167] ------`

**Comment by roblourens** [comment]
Does that file/folder exist? What if you run "Kill VS Code Server on Host", and try connecting again?

**Comment by tanhakabir** [comment]
Closing this issue due to inactivity!
