### ISSUE TITLE
After resuming Windows from hibernation, reloading window is required and some extensions are then broken until manually reloading it again

### ISSUE THREAD

**Issue by CherryDT** [microsoft/vscode-remote-release#5215]
Issue Type: <b>Bug</b>

For the last 2-3 weeks I had the issue that whenever I resume my Windows from hibernation while a WSL project was open in VSCode, I get a "cannot reconnect" popup in VSCode, prompting me to reload the window. When I do so, things work again but some extensions don't work, such as my linters - not even appearing in the dropdown of the "output" window. I didn't find anything standing out in the output window otherwise, looks like some things just aren't happening, somehow. When I then use Command Palette -> Reload Window manually and reload the window a second time this way, everything works again (until next hibernation). I'm using legacy WSL.

Extension version: 0.58.1
VS Code version: Code - Insiders 1.58.0-insider (012b14606f75ec4fed90d7ab4154f63dffab9503, 2021-06-11T05:14:11.473Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 4.4.0-19041-Microsoft

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (4.02GB free)|
|Process Argv|--crash-reporter-id c6356cfd-7a7a-4cee-93f1-a6019521c8bb|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Legacy|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|Memory (System)|15.86GB (4.04GB free)|
|VM|0%|
</details>

**Comment by CherryDT** [comment]
I noticed now something I didn't see before, in the output for `Log (Remote Extension Host)` - not sure if it's related:

```
[2021-06-20 14:29:12.621] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2021-06-20 14:29:12.622] [exthost] [error] Error: DisposableStore is missing...
    at F._convertCompletionItem (/home/david/.vscode-server-insiders/bin/012b14606f75ec4fed90d7ab4154f63dffab9503/out/vs/server/remoteExtensionHostProcess.js:84:172591)
    at F.resolveCompletionItem (/home/david/.vscode-server-insiders/bin/012b14606f75ec4fed90d7ab4154f63dffab9503/out/vs/server/remoteExtensionHostProcess.js:84:172329)
[2021-06-20 14:31:48.400] [exthost] [info] ExtensionService#_doActivateExtension Rubymaniac.vscode-paste-and-indent {"startup":false,"extensionId":{"value":"Rubymaniac.vscode-paste-and-indent","_lower":"rubymaniac.vscode-paste-and-indent"},"activationEvent":"onCommand:pasteAndIndent.action"}
[2021-06-20 14:31:48.401] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/david/.vscode-server-insiders/extensions/rubymaniac.vscode-paste-and-indent-0.0.8/out/src/extension
[2021-06-20 14:35:00.016] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2021-06-20 14:35:00.030] [exthost] [error] Error: name must not be falsy
    at Function.validate (/home/david/.vscode-server-insiders/bin/012b14606f75ec4fed90d7ab4154f63dffab9503/out/vs/server/remoteExtensionHostProcess.js:77:27724)
    at new n (/home/david/.vscode-server-insiders/bin/012b14606f75ec4fed90d7ab4154f63dffab9503/out/vs/server/remoteExtensionHostProcess.js:77:27673)
    at new n (/home/david/.vscode-server-insiders/bin/012b14606f75ec4fed90d7ab4154f63dffab9503/out/vs/server/remoteExtensionHostProcess.js:77:14472)
    at Function.convertSymbol (/home/david/.vscode-server-insiders/bin/012b14606f75ec4fed90d7ab4154f63dffab9503/extensions/typescript-language-features/dist/extension.js:1:173076)
    at Function.convertNavTree (/home/david/.vscode-server-insiders/bin/012b14606f75ec4fed90d7ab4154f63dffab9503/extensions/typescript-language-features/dist/extension.js:1:172687)
    at Function.convertNavTree (/home/david/.vscode-server-insiders/bin/012b14606f75ec4fed90d7ab4154f63dffab9503/extensions/typescript-language-features/dist/extension.js:1:172796)
    at a.provideDocumentSymbols (/home/david/.vscode-server-insiders/bin/012b14606f75ec4fed90d7ab4154f63dffab9503/extensions/typescript-language-features/dist/extension.js:1:172423)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2021-06-20 14:35:36.618] [exthost] [info] ExtensionService#_doActivateExtension vscode.html-language-features {"startup":false,"extensionId":{"value":"vscode.html-language-features","_lower":"vscode.html-language-features"},"activationEvent":"onLanguage:html"}
[2021-06-20 14:35:36.619] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/david/.vscode-server-insiders/bin/012b14606f75ec4fed90d7ab4154f63dffab9503/extensions/html-language-features/client/dist/node/htmlClientMain
[2021-06-20 14:57:57.660] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2021-06-20 14:57:57.661] [exthost] [error] Error: DisposableStore is missing...
    at F._convertCompletionItem (/home/david/.vscode-server-insiders/bin/012b14606f75ec4fed90d7ab4154f63dffab9503/out/vs/server/remoteExtensionHostProcess.js:84:172591)
    at F.resolveCompletionItem (/home/david/.vscode-server-insiders/bin/012b14606f75ec4fed90d7ab4154f63dffab9503/out/vs/server/remoteExtensionHostProcess.js:84:172329)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
