### ISSUE TITLE
Code Insiders - Resolver error: Error: Running the contributed command: '_workbench.downloadResource'

### ISSUE THREAD

**Issue by firegate22** [microsoft/vscode-remote-release#5222]
- VSCode Version: 1.58
- Local OS Version: Windows 10 21H1
- Remote OS Version: CentOS 7
- Remote Extension/Connection Type: SSH
- Logs:
```
[09:02:59.703] Log Level: 2
[09:02:59.714] remote-ssh@0.65.7
[09:02:59.715] win32 x64
[09:02:59.754] SSH Resolver called for "ssh-remote+<<ssh url>>", attempt 1
[09:02:59.755] "remote.SSH.useLocalServer": false
[09:02:59.755] "remote.SSH.showLoginTerminal": false
[09:02:59.756] "remote.SSH.remotePlatform": {"<<ssh url>>":"linux"}
[09:02:59.756] "remote.SSH.path": undefined
[09:02:59.756] "remote.SSH.configFile": undefined
[09:02:59.756] "remote.SSH.useFlock": true
[09:02:59.756] "remote.SSH.lockfilesInTmp": false
[09:02:59.756] "remote.SSH.localServerDownload": always
[09:02:59.757] "remote.SSH.remoteServerListenOnSocket": false
[09:02:59.757] "remote.SSH.showLoginTerminal": false
[09:02:59.757] "remote.SSH.defaultExtensions": []
[09:02:59.757] "remote.SSH.loglevel": 2
[09:02:59.757] SSH Resolver called for host: <<ssh url>>
[09:02:59.757] Setting up SSH remote "<<ssh url>>"
[09:02:59.764] Using commit id "a81fff00c9dab105800118fcf8b044cd84620419" and quality "insider" for server
[09:02:59.768] Install and start server if needed
[09:02:59.772] Checking ssh with "ssh -V"
[09:02:59.906] > OpenSSH_for_Windows_8.1p1, 
[09:02:59.906] > LibreSSL 3.0.2

[09:02:59.912] Running script with connection command: ssh -T -D 49222 "<<ssh url>>" bash
[09:02:59.915] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[09:03:00.350] > ]0;C:\WINDOWS\System32\cmd.exe
[09:03:00.350] Got some output, clearing connection timeout
[09:03:01.233] > 80575b888811: running
[09:03:01.266] > Acquiring lock on /home/<<my username>>/.vscode-server-insiders/bin/a81fff00c9dab105
> 800118fcf8b044cd84620419/vscode-remote-lock.<<my username>>.a81fff00c9dab105800118fc
> f8b044cd84620419
[09:03:01.280] > Installing to /home/<<my username>>/.vscode-server-insiders/bin/a81fff00c9dab1058001
> 18fcf8b044cd84620419...
> Trigger local server download
> 80575b888811:trigger_server_download
> platform==linux==
> vscodeArch==x64==
> destFolder==/home/<<my username>>/.vscode-server-insiders/bin/a81fff00c9dab105800118
> fcf8b044cd84620419==
> 80575b888811:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/<<my username>>/.vscode-server-insiders/bin/a81fff00c9dab105800118
> fcf8b044cd84620419/vscode-scp-done.flag and vscode-server.tar.gz to exist       
> 
[09:03:01.281] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/home/<<my username>>/.vscode-server-insiders/bin/a81fff00c9dab105800118fcf8b044cd84620419"}
[09:03:01.281] Downloading VS Code server locally...
[09:03:01.486] Resolver error: Error: Running the contributed command: '_workbench.downloadResource' failed.
	at I._executeContributedCommand (c:\Users\<<my username>>\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:108993)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\<<my username>>\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:139384
	at async Object.t.downloadAndCopyToHost (c:\Users\<<my username>>\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:139299)
	at async c:\Users\<<my username>>\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:414617
	at async Object.t.tryInstall (c:\Users\<<my username>>\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:414829)
	at async c:\Users\<<my username>>\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:294918
	at async Object.t.withShowDetailsEvent (c:\Users\<<my username>>\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:406463)
	at async Object.t.resolve (c:\Users\<<my username>>\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:295994)
	at async c:\Users\<<my username>>\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:127:110656
[09:03:01.489] ------
```

Steps to Reproduce:

1. Open SSH connection in Code 1.58 (insiders build)
2. Connection can't be established

I tried deleting workspaceStorage local (Windows), deleting/stopping server on remote host via VS Code / manually deleting folder. The same connection works with VS Code 1.57.1 (stable vs code).

Remote SSH 65.7

Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by firegate22** [comment]
Sorry, can't delete - now after opening I found #4743 - sorry.
