### ISSUE TITLE
Could not establish connection to "ip address": The process tried to write to a nonexistent pipe

### ISSUE THREAD

**Issue by quyleanh** [microsoft/vscode-remote-release#5234]
Does this issue occur when all extensions are disabled?: 
N/A. Need Remote extension to connect to remote host.

- VS Code Version: 1.57.1 (user setup)
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Remote ssh to a known host in VSCode
2. The error dialog is displayed

**Comment by bamurtaugh** [comment]
Can you please provide more information? i.e. the SSH output log, local and remote OS, version of Remote-SSH you are using. Additional info about logs and reporting issues here: https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues.

**Comment by quyleanh** [comment]
Thank you for your response.

Here is the SSH output log

```
[11:28:44.193] Log Level: 2
[11:28:44.194] remote-ssh@0.65.7
[11:28:44.195] win32 x64
[11:28:44.195] SSH Resolver called for "ssh-remote+ip.address", attempt 1
[11:28:44.196] "remote.SSH.useLocalServer": false
[11:28:44.196] "remote.SSH.showLoginTerminal": false
[11:28:44.196] "remote.SSH.remotePlatform": {"ip.address":"linux"}
[11:28:44.196] "remote.SSH.path": undefined
[11:28:44.196] "remote.SSH.configFile": undefined
[11:28:44.196] "remote.SSH.useFlock": true
[11:28:44.196] "remote.SSH.lockfilesInTmp": false
[11:28:44.197] "remote.SSH.localServerDownload": auto
[11:28:44.197] "remote.SSH.remoteServerListenOnSocket": false
[11:28:44.197] "remote.SSH.showLoginTerminal": false
[11:28:44.197] "remote.SSH.defaultExtensions": []
[11:28:44.197] "remote.SSH.loglevel": 2
[11:28:44.197] SSH Resolver called for host: ip.address
[11:28:44.197] Setting up SSH remote "ip.address"
[11:28:45.536] Using commit id "507ce72a4466fbb27b715c3722558bb15afa9f48" and quality "stable" for server
[11:28:45.540] Install and start server if needed
[11:28:45.545] Checking ssh with "ssh -V"
[11:28:45.672] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[11:28:45.677] Running script with connection command: ssh -T -D 61957 "ip.address" bash
[11:28:45.684] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[11:28:46.027] > Bad owner or permissions on C:\\Users\\quyleanh/.ssh/config
> ]0;C:\WINDOWS\System32\cmd.exe
[11:28:46.027] Got some output, clearing connection timeout
[11:28:46.040] > The process tried to write to a nonexistent pipe.
[11:28:47.298] "install" terminal command done
[11:28:47.298] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exeThe process tried to write to a nonexistent pipe.
[11:28:47.299] Received install output: ]0;C:\WINDOWS\System32\cmd.exeThe process tried to write to a nonexistent pipe.
[11:28:47.304] Resolver error: Error: The process tried to write to a nonexistent pipe
	at Function.Offline (c:\Users\quyleanh\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64710)
	at c:\Users\quyleanh\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:62260
	at Object.t.handleInstallOutput (c:\Users\quyleanh\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:62638)
	at Object.t.tryInstall (c:\Users\quyleanh\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:415135)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\quyleanh\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:294918
	at async Object.t.withShowDetailsEvent (c:\Users\quyleanh\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:406463)
	at async Object.t.resolve (c:\Users\quyleanh\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:295994)
	at async c:\Users\quyleanh\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:127:110656
[11:28:47.306] ------
```

My VSCode version info
```
Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
```

My Remote - SSH version 
```v0.65.7```

My remote server version info
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"
```

**Comment by bamurtaugh** [comment]
Based on `Bad owner or permissions on C:\\Users\\quyleanh/.ssh/config`

I think you need https://code.visualstudio.com/docs/remote/troubleshooting#_local-ssh-file-and-folder-permissions

**Comment by quyleanh** [comment]
I think it's not related to permission. I check the log first and there is no problem with permission.
```
drwxrwxrwx     - quyleanh 18 Jun 18:40  .ssh
```
I also deleted the .vscode folder on my server but it didn't work.

Check with other computer and it works fine. I think it's my PC's problem. I will close this issue since it isn't a bug from VSCode.
Thank you for your kind support.
