### ISSUE TITLE
SSH Failed to connect to EC2 with latest release (0.65.7) 

### ISSUE THREAD

**Issue by zachcoleman** [microsoft/vscode-remote-release#5239]
- VSCode Version: 1.57
- Local OS Version: MacOS 11.4
- Remote OS Version: ubuntu-bionic-18.04-amd64-server-20210224 
- Remote Extension/Connection Type: SSH
- Logs: I replaced my public DNS and pem file name w/ placeholders
```
[10:01:01.591] Log Level: 2
[10:01:01.593] remote-ssh@0.65.7
[10:01:01.593] darwin x64
[10:01:01.595] SSH Resolver called for "ssh-remote+<my ec2>.compute-1.amazonaws.com", attempt 1
[10:01:01.595] "remote.SSH.useLocalServer": true
[10:01:01.596] "remote.SSH.path": undefined
[10:01:01.596] "remote.SSH.configFile": undefined
[10:01:01.596] "remote.SSH.useFlock": true
[10:01:01.596] "remote.SSH.lockfilesInTmp": false
[10:01:01.596] "remote.SSH.localServerDownload": auto
[10:01:01.596] "remote.SSH.remoteServerListenOnSocket": false
[10:01:01.596] "remote.SSH.showLoginTerminal": false
[10:01:01.597] "remote.SSH.defaultExtensions": []
[10:01:01.597] "remote.SSH.loglevel": 2
[10:01:01.597] SSH Resolver called for host: <my ec2>.compute-1.amazonaws.com
[10:01:01.597] Setting up SSH remote "<my ec2>.compute-1.amazonaws.com"
[10:01:01.600] Acquiring local install lock: /var/folders/b_/wk6p_y5x5sg4f25gyw7w3t0r0000gp/T/vscode-remote-ssh-<my ec2>.compute-1.amazonaws.com-install.lock
[10:01:01.613] Looking for existing server data file at /Users/zachcoleman/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-<my ec2>.compute-1.amazonaws.com-507ce72a4466fbb27b715c3722558bb15afa9f48-0.65.7/data.json
[10:01:01.613] Using commit id "507ce72a4466fbb27b715c3722558bb15afa9f48" and quality "stable" for server
[10:01:01.617] Install and start server if needed
[10:01:01.620] PATH: /Users/zachcoleman/.pyenv/shims:/Users/zachcoleman/.pyenv/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin
[10:01:01.620] Checking ssh with "ssh -V"
[10:01:01.626] > OpenSSH_8.1p1, LibreSSL 2.7.3

[10:01:01.628] askpass server listening on /var/folders/b_/wk6p_y5x5sg4f25gyw7w3t0r0000gp/T/vscode-ssh-askpass-490cbefb6c8cb9f3f6389539e9ce37034e39918f.sock
[10:01:01.629] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/b_/wk6p_y5x5sg4f25gyw7w3t0r0000gp/T/vscode-ssh-askpass-afdccec731ddee6395a785807ef68fe3d682c0ac.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","56411","-o","ConnectTimeout=15","<my ec2>.compute-1.amazonaws.com"],"dataFilePath":"/Users/zachcoleman/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-<my ec2>.compute-1.amazonaws.com-507ce72a4466fbb27b715c3722558bb15afa9f48-0.65.7/data.json"}
[10:01:01.629] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/zachcoleman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/zachcoleman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/b_/wk6p_y5x5sg4f25gyw7w3t0r0000gp/T/vscode-ssh-askpass-490cbefb6c8cb9f3f6389539e9ce37034e39918f.sock"}
[10:01:01.630] Spawned 30608
[10:01:01.730] > local-server-1> Spawned ssh, pid=30614
[10:01:01.733] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[10:01:02.021] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:5zpKLhxCadJZOkpROp+46lhffO85rz5bGJ9IvI3Urrg
[10:01:02.179] stderr> no such identity: Users/zachcoleman/<my pem file>.pem: No such file or directory
[10:01:02.179] stderr> ubuntu@<my ec2>.compute-1.amazonaws.com: Permission denied (publickey).
[10:01:02.179] > local-server-1> ssh child died, shutting down
[10:01:02.183] Local server exit: 0
[10:01:02.183] Received install output: local-server-1> Spawned ssh, pid=30614
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:5zpKLhxCadJZOkpROp+46lhffO85rz5bGJ9IvI3Urrg
no such identity: Users/zachcoleman/<my pem file>.pem: No such file or directory
ubuntu@<my ec2>.compute-1.amazonaws.com: Permission denied (publickey).
local-server-1> ssh child died, shutting down

[10:01:02.184] Resolver error: Error: Permission denied (publickey).
	at Function.Create (/Users/zachcoleman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:64659)
	at /Users/zachcoleman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:62853
	at Object.t.handleInstallOutput (/Users/zachcoleman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:63238)
	at Object.e [as tryInstallWithLocalServer] (/Users/zachcoleman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:387573)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/zachcoleman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:294473
	at async Object.t.withShowDetailsEvent (/Users/zachcoleman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:406463)
	at async /Users/zachcoleman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:386112
	at async E (/Users/zachcoleman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:382710)
	at async Object.t.resolveWithLocalServer (/Users/zachcoleman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:385728)
	at async Object.t.resolve (/Users/zachcoleman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:295870)
	at async /Users/zachcoleman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:127:110656
[10:01:02.188] ------
```

Steps to Reproduce:

1. Launch EC2
2. Edit .ssh/config file with respective host like:
```
Host <my ec2>.compute-1.amazonaws.com
  HostName <my ec2>.compute-1.amazonaws.com
  User ubuntu
  IdentityFile <global path to .pem>
```
3: Try to connect using plugin

Does this issue occur when you try this locally?: This is vscode/plugin specific. Connection via ssh OS Terminal client can be established.
Does this issue occur when you try this locally and all extensions are disabled?: This is vscode/plugin specific. Connection via OS Terminal ssh client can be established.

**Comment by bamurtaugh** [comment]
Thanks for reporting. Just to clarify based on the issue name - was the connection working in a previous version of Remote - SSH and/or VS Code, but now you're experiencing this issue?

**Comment by bamurtaugh** [comment]
Also in case your .pem file has any spaces: https://github.com/microsoft/vscode-remote-release/issues/4999.

**Comment by zachcoleman** [comment]
Thank you for responding!

> Thanks for reporting. Just to clarify based on the issue name - was the connection working in a previous version of Remote - SSH and/or VS Code, but now you're experiencing this issue?

Yes, downgrading to 0.65.6 works for me.


> Also in case your .pem file has any spaces: #4999.

No, the path to my .pem file does not have any spaces.
