### ISSUE TITLE
Failed to parse remote port from server output

### ISSUE THREAD

**Issue by Hello-GBY** [microsoft/vscode-remote-release#5252]
![企业微信截图_20210625104438](https://user-images.githubusercontent.com/65537456/123361872-5e649380-d5a2-11eb-8e29-88966bee3247.png)

**Comment by roblourens** [comment]
Please share the whole log. Looks like there is some other error above it

**Comment by Hello-GBY** [comment]
![image](https://user-images.githubusercontent.com/65537456/123729267-45702100-d8c7-11eb-9f11-81a9d4e90343.png)

**Comment by roblourens** [comment]
I really need the whole log, ideally as pasted text instead of a screenshot

**Comment by Hello-GBY** [comment]
[11:52:51.943] Log Level: 2
[11:52:51.948] remote-ssh@0.65.7
[11:52:51.948] win32 x64
[11:52:51.950] SSH Resolver called for "ssh-remote+10.100.41.18", attempt 1
[11:52:51.951] "remote.SSH.useLocalServer": false
[11:52:51.951] "remote.SSH.showLoginTerminal": false
[11:52:51.951] "remote.SSH.remotePlatform": {"47.94.248.189":"linux"}
[11:52:51.951] "remote.SSH.path": undefined
[11:52:51.951] "remote.SSH.configFile": undefined
[11:52:51.952] "remote.SSH.useFlock": true
[11:52:51.952] "remote.SSH.lockfilesInTmp": false
[11:52:51.952] "remote.SSH.localServerDownload": always
[11:52:51.952] "remote.SSH.remoteServerListenOnSocket": false
[11:52:51.952] "remote.SSH.showLoginTerminal": false
[11:52:51.953] "remote.SSH.defaultExtensions": []
[11:52:51.953] "remote.SSH.loglevel": 2
[11:52:51.953] SSH Resolver called for host: 10.100.41.18
[11:52:51.953] Setting up SSH remote "10.100.41.18"
[11:52:51.975] Using commit id "507ce72a4466fbb27b715c3722558bb15afa9f48" and quality "stable" for server
[11:52:51.979] Install and start server if needed
[11:52:53.286] Checking ssh with "ssh -V"
[11:52:53.315] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.3.3

[11:52:53.320] Remote command length: 5992/8192 characters
[11:52:53.320] Running script with connection command: ssh -T -D 61738 "10.100.41.18" powershell
[11:52:53.324] Terminal shell path: C:\Windows\System32\cmd.exe
[11:52:53.509] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\Windows\System32\cmd.exe
[11:52:53.510] Got some output, clearing connection timeout
[11:52:53.515] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[11:52:53.600] > 
>                             ****USAGE WARNING****
> 
> This is a private computer system. This computer system, including all
> related equipment, networks, and network devices (specifically including       
> Internet access) are provided only for authorized use. This computer system    
> may be monitored for all lawful purposes, including to ensure that its use     
> is authorized, for management of the system, to facilitate protection against  
> unauthorized access, and to verify security procedures, survivability, and     
> operational security. Monitoring includes active attacks by authorized entities
> to test or verify the security of this system. During monitoring, information  
> may be examined, recorded, copied and used for authorized purposes. All        
> information, including personal information, placed or sent over this system   
> may be monitored.
> 
> Use of this computer system, authorized or unauthorized, constitutes consent   
> to monitoring of this system. Unauthorized use may subject you to criminal     
> prosecution. Evidence of unauthorized use collected during monitoring may be   
> used for administrative, criminal, or other adverse action. Use of this system 
> constitutes consent to monitoring for these purposes.
[11:52:53.649] > administrator@10.100.41.18's password: 
[11:52:53.649] Showing password prompt
[11:52:55.013] Got password response
[11:52:55.014] "install" wrote data to terminal: "*"
[11:52:55.025] > 
> 
[11:52:55.230] > Windows PowerShell
> ��Ȩ���� (C) Microsoft Corporation����������Ȩ����
> 
> �����µĿ�ƽ̨ PowerShell https://aka.ms/pscore6
> 
> 
[11:52:55.368] > PS C:\Program Files\OpenSSH\home\Administrator> 
[11:52:55.471] > 
> PS C:\Program Files\OpenSSH\home\Administrator> $uuid="34e68b48f01e"
[11:52:55.479] > 
> 
[11:52:55.490] > PS C:\Program Files\OpenSSH\home\Administrator> "${uuid}: running"
> 34e68b48f01e: running
[11:52:55.496] > 
> PS C:\Program Files\OpenSSH\home\Administrator> "34e68b48f01e: pauseLog
[11:52:56.028] > 34e68b48f01e: resumeLog
> PS C:\Program Files\OpenSSH\home\Administrator> main
[11:52:56.038] > 
> 
[11:52:56.621] > gps : �Ҳ������̱�ʶ��Ϊ 64940 �Ľ��̡�
> ����λ�� ��:9 �ַ�: 6
> + if ((gps -Id $u_).Name -eq 'sshd') {
> +      ~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (64940:Int32) [Get-Process], Proce
[11:52:56.626] > 
> ssCommandException
>     + FullyQualifiedErrorId : NoProcessFoundForGivenId,Microsoft.PowerShell.Comm
> ands.GetProcessCommand
> 
> 
[11:52:56.684] > no sshd parent proc
> 
[11:52:57.976] "install" terminal command done
[11:52:57.976] Install terminal quit with output: no sshd parent proc
[11:52:57.976] Received install output: no sshd parent proc
[11:52:57.977] Failed to parse remote port from server output
[11:52:57.978] Resolver error: Error: 
	at Function.Create (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64597)
	at Object.t.handleInstallOutput (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:63240)
	at Object.t.tryInstall (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:415073)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:294856
	at async Object.t.withShowDetailsEvent (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:406401)
	at async Object.t.resolve (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:295932)
	at async c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:127:110656
[11:52:57.982] ------

**Comment by Hello-GBY** [comment]
That's all the info, thank you

**Comment by Hello-GBY** [comment]
I really need your help

**Comment by roblourens** [comment]
Sorry, this is strange, I don't know what's going on. 

> [11:52:56.621] > gps : �Ҳ������̱�ʶ��Ϊ 64940 �Ľ��̡�
> ����λ�� ��:9 �ַ�: 6
> + if ((gps -Id $u_).Name -eq 'sshd') {

We made one call which told us that `64940` is the pid of the parent process, but get-process tells us that process doesn't exist. I don't know how that's possible

**Comment by roblourens** [comment]
I wonder whether there is a permissions issue here. It seems like you are an administrator, is that right? Do you have limited permissions on this remote machine that would keep you from using the get-process tool?
