### ISSUE TITLE
Failed to parse remote port from server output

### ISSUE THREAD

**Issue by VaiSuliafu** [microsoft/vscode-remote-release#5263]
When trying to remote ssh to server I regularly connect to, I get the following....

[16:41:38.033] Log Level: 2
[16:41:38.039] remote-ssh-nightly@2021.5.29700
[16:41:38.039] win32 x64
[16:41:38.040] SSH Resolver called for "ssh-remote+newton.sci.utah.edu", attempt 1
[16:41:38.040] "remote.SSH.useLocalServer": false
[16:41:38.040] "remote.SSH.showLoginTerminal": false
[16:41:38.040] "remote.SSH.remotePlatform": {}
[16:41:38.040] "remote.SSH.path": undefined
[16:41:38.040] "remote.SSH.configFile": undefined
[16:41:38.041] "remote.SSH.useFlock": true
[16:41:38.041] "remote.SSH.lockfilesInTmp": false
[16:41:38.041] "remote.SSH.localServerDownload": auto
[16:41:38.041] "remote.SSH.remoteServerListenOnSocket": false
[16:41:38.041] "remote.SSH.showLoginTerminal": false
[16:41:38.041] "remote.SSH.defaultExtensions": []
[16:41:38.041] "remote.SSH.loglevel": 2
[16:41:38.042] SSH Resolver called for host: newton.sci.utah.edu
[16:41:38.042] Setting up SSH remote "newton.sci.utah.edu"
[16:41:38.069] Using commit id "507ce72a4466fbb27b715c3722558bb15afa9f48" and quality "stable" for server
[16:41:38.073] Install and start server if needed
[16:41:38.912] Checking ssh with "ssh -V"
[16:41:38.953] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[16:41:38.958] Running script with connection command: ssh -T -D 57082 "newton.sci.utah.edu" bash
[16:41:38.960] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[16:41:39.197] > ]0;C:\WINDOWS\System32\cmd.exe
[16:41:39.197] Got some output, clearing connection timeout
[16:41:39.344] > vais@newton.sci.utah.edu's password: 
[16:41:39.345] Showing password prompt
[16:41:42.522] Got password response
[16:41:42.523] "install" wrote data to terminal: "***********"
[16:41:42.555] > 
[16:41:43.395] > 5884649b088e: running
[16:41:43.417] > mkdir: cannot create directory ‘/home/vais/.vscode-server/bin/507ce72a4466fbb27b
> 715c3722558bb15afa9f48’: Permission denied
> Creating the server install dir failed...
> 5884649b088e: start
> exitCode==34==
> listeningOn====
> osReleaseId====
> arch====
> tmpDir==/run/user/1001==
> platform====
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 5884649b088e: end
[16:41:43.417] Received install output: 
exitCode==34==
listeningOn====
osReleaseId====
arch====
tmpDir==/run/user/1001==
platform====
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[16:41:43.418] Failed to parse remote port from server output
[16:41:43.418] Resolver error: Error: 
	at Function.Create (c:\Users\vaisu\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:1:64659)
	at Object.t.handleInstallOutput (c:\Users\vaisu\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:1:63302)
	at Object.t.tryInstall (c:\Users\vaisu\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:1:415135)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\vaisu\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:1:294918
	at async Object.t.withShowDetailsEvent (c:\Users\vaisu\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:1:406463)
	at async Object.t.resolve (c:\Users\vaisu\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:1:295994)
	at async c:\Users\vaisu\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:127:110656
[16:41:43.421] ------

[16:41:44.700] "install" terminal command done
[16:41:44.701] Install terminal quit with output:

**Comment by bamurtaugh** [comment]
Seems somewhat similar to https://github.com/microsoft/vscode-remote-release/issues/2095. 

Does `/home/vais/.vscode-server` exist already? Also, do you expect to have permission to create a directory?

**Comment by bamurtaugh** [comment]
Please let us know if you're still experiencing this, and if so, if you can provide info into the questions above. Thanks!
