### ISSUE TITLE
Attach to running docker container by name in CLI and document CLI options

### ISSUE THREAD

**Issue by JPustkuchen** [microsoft/vscode-remote-release#5278]
Hi and thank you all very much for your hard work on vscode and vscode-remote! It's simply brilliant.

### Context
We're using tools like https://github.com/drud/ddev or https://lando.dev/ to build and run smart development docker containers.
We're using VSCode Remote to attach to these running containers using the wonderful UI via F1 + Remote-Containers: Attach to Running Container ...
There we select the container we'd like to attach to and run it.

### Problem
This works, but for developers like you and us the process isn't really perfect. It's clicky here, clicky there for a task where you'd expect to write a shell script and GO :)

I've read many similar issues, most are about how to start devcontainers / k8 or ssh remote connections.
Anyway it seems such CLI parameters aren't yet officially documented?

For our use-case (attaching to a running docker container by name from CLI / shell script) I couldn't find a viable solution. That's why I've written this feature request to document the CLI options and provide a clever way to start vscode attached to a running container by container name / id.

### Proposed solution
1. Document the CLI parameters officially with examples how to start vscode from CLI in remote (devcontainer, attached to running container, k8, ssh, ...?)
2. Allow to attach to a running container from CLI by container name (or document how to do that if that should be possible already)

Once again, thank you very much for your hard work on this wonderful project!

**Comment by chrmarti** [comment]
There is now a `devcontainer` CLI, we could add an `attach` command to that: https://code.visualstudio.com/docs/remote/devcontainer-cli

**Comment by joshsedl** [comment]
Hey @chrmarti,
can't wait for this feature to be implemented! It would really help automatically setting up our programming environment using ddev with VSCode. 👍 
Just wanted to sneak in and ask what the current status of this feature is?

**Comment by chrmarti** [comment]
Hi @joshsedl, still on the backlog. To follow what we are currently up to I recommend checking the current iteration plan. Usually the only pinned issue at the top of https://github.com/microsoft/vscode-remote-release/issues.

**Comment by joshsedl** [comment]
Ok, thanks for the tip!

**Comment by joshsedl** [comment]
Since we are tracking this issue here now, I just wanted to quote my proposal from https://github.com/microsoft/vscode-remote-release/issues/5944, to attach VSCode to a container with additional setting and extension flags!
>If there could be an easier readable command to attach to a container, instead of using the hex value of the container, + some additional flags which define the location of a settings/extensions.json, to use would be perfect!
For example:
code-attach-to-container --name my-container-name --extension-path /my/path/to/extensions.json --settings-path /my/path/to/settings.json

**Comment by g-kartik** [comment]
Hello @chrmarti, this is a very useful feature.
I am using git hooks to automatically build and run docker containers on branch checkout and merge. If there is a CLI command to attach to a running container then I could use it in the git hooks script to launch the vs code remote dev environment, which would be awesome. Can't wait this feature to be built.

**Comment by chrmarti** [comment]
@g-kartik You could try using this: `code --folder-uri vscode-remote://attached-container+$(printf "$CONTAINER_NAME_OR_ID" | xxd -p)/home`

**Comment by g-kartik** [comment]
Thank you @chrmarti . It worked. Could not be more happy!

**Comment by joshsedl** [comment]
For some reason, `printf "$CONTAINER_NAME_OR_ID" | xxd -p` lead to two different outcomes depending on the distro:
- Under Windows + WSL2 (with Ubuntu installed) using zsh, it works as expected and prints out the hexvalue of the container name
- Under OpenSUSE Leap using bash, the hex value got split

So instead I am using a differen (probably overcomplicated) command:
 `code --folder-uri vscode-remote://attached-container+$(printf "$CONTAINER_NAME_OR_ID" | od -A n -t x1 | sed 's/ *//g' | tr -d '\n')/home` (sed, will delete the spaces and tr the new lines)

**Comment by tyler36** [comment]
@joshsedl 

I had the issue with my [ddev-vscode-devcontainer addon](https://github.com/tyler36/ddev-vscode-devcontainer) to open containers in VScode.  It came down to how the terminal would "wrap" longer names into columns.

Using [xxd](https://ss64.com/bash/xxd.html), I change the default from 16 to 64 which resolved my issue.

```
 ${CODE_EXECUTABLE} --folder-uri "vscode-remote://attached-container+$(printf '%s' $CODE_CONTAINER | xxd -p -c 64)${CODE_PATH}"
```

**Comment by joshsedl** [comment]
Thanks, @tyler36! Yea, I probably skipped on "xxd" too fast, Never the less I'll rather use `code --folder-uri vscode-remote://attached-container+$(printf "$CONTAINER_NAME_OR_ID" | od -A n -t x1 | sed 's/ *//g' | tr -d '\n')/home` now, as "od", "sed" AND "tr" all follow the POSIX standard, making sure, the command works on a wide variety of UNIX derivatives (xxd doesn't).
It's probably not a big deal and both are fine, but since it works, it works!

**Comment by tyler36** [comment]
Thanks @joshsedl . I use WSL ubuntu and it was the solution I stumbled across and worked. Before my post, I checked that my WSL OpenSUS had `xxd` (it did) but it's good to now know that it doesn't work on some UNIX derivatives.

**Comment by tuunit** [comment]
I combined the new devcontainer cli with the approach presented here:
`CONTAINER_NAME_OR_ID=$(devcontainer up --workspace-folder . | jq -r .containerId) /usr/bin/code --folder-uri vscode-remote://attached-container+$(printf "$CONTAINER_NAME_OR_ID" | od -A n -t x1 | sed 's/ *//g' | tr -d '\n')/workspace`

**Comment by joshsedl** [comment]
@tuunit, thanks for sharing! 

You say, that you start a devcontainer through "devcontainer up" and attach vscode to it. Do you know if the devcontainer cli  can also take a devcontainer.json and create an attached container to an existing container? I saw "devcontainer up --mount", but I am unsure if that does what this issue is originally about.

**Comment by tuunit** [comment]
> creat an attached container to an existing container?

How would you attach a container to a container 🤔 Or do I misunderstand what you try to accomplish?

**Comment by tuunit** [comment]
Ah okay, if you read the last sentence of my original comment. It will answer your question:
> It either starts a new devcontainer from the definition file in your current working directory or will attach to an already existing devcontainer.

Meaning if a devcontainer defined by your `devcontainer.json` is already running, it will automatically attach to it. This statement is valid for the first solution using `devcontainers/cli` and the custom python function.

**Comment by joshsedl** [comment]
Thanks a lot @tuunit! That sounds great! 🎉
I thought that part was script specific! So thanks for the clear up!

**Comment by joshsedl** [comment]
Ok, https://github.com/microsoft/vscode-remote-release/issues/5278#issuecomment-1785723387, doesn't solve this issue's problem yet. `devcontainers/cli` will always create its own devcontainer, no matter what. 
As @tuunit already said in his comment:
>Meaning if a devcontainer defined by your devcontainer.json is already running, it will automatically attach to it

The talk is of a **dev**container, not a "normal" container to attach to. Meaning if I want to attach VSCode to my dev environment's web server container, I can not do that with the `devcontainers/cli`, even if I define the same image and name of my webserver docker container, `devcontainers/cli`, will always create its own container.

Although this could still be a future feature of https://github.com/devcontainers/cli. It might make sense to move this feature request there?

**Comment by lakuapik** [comment]
Hi @chrmarti @joshsedl the above command works, just curious, is it possible to open in existing workspace that already running devcontainer? instead of opening in new window?

**Comment by mauro-lanza** [comment]
Hi I'm following up on this issue, @tuunit 's response worked fine for me while i was using docker desktop, but the moment i moved away to colima or rancher i have the issue of it not connecting correctly to the image. I get the following message and logs:

<img width="263" height="284" alt="Image" src="https://github.com/user-attachments/assets/bb44e7fd-8dd0-43a5-b1e3-dc52f30c0185" />

```log
[14 ms] Dev Containers 0.422.0 in VS Code 1.102.0 (cb0c47c0cfaad0757385834bd89d410c78a856c0).
[14 ms] Start: Resolving Remote
[15 ms] Setting up container: 1254d7c0915a
[19 ms] Start: Run: docker inspect --type container 1254d7c0915a
[36 ms] Stop (17 ms): Run: docker inspect --type container 1254d7c0915a
```


When i manually click on the Attach to running container i see the following logs:
```log
[17252 ms] Getting Docker parameters for own remote.
[17254 ms] Error: 
        at tt (/Users/mauro.lanza/.vscode/extensions/ms-vscode-remote.remote-containers-0.422.0/dist/extension/extension.js:328:1176)
        at Zr (/Users/mauro.lanza/.vscode/extensions/ms-vscode-remote.remote-containers-0.422.0/dist/extension/extension.js:384:1106)
        at h (/Users/mauro.lanza/.vscode/extensions/ms-vscode-remote.remote-containers-0.422.0/dist/extension/extension.js:410:14613)
        at async Ab.h (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:41564)
[17332 ms] Start: Run: docker version --format {{json .}}
[17349 ms] {"Client":{"Version":"28.1.1-rd","ApiVersion":"1.47","DefaultAPIVersion":"1.49","GitCommit":"4d7f01e","GoVersion":"go1.23.8","Os":"darwin","Arch":"arm64","BuildTime":"Fri Apr 18 18:11:24 2025","Context":"colima"},"Server":{"Platform":{"Name":"Docker Engine - Community"},"Components":[{"Name":"Engine","Version":"27.4.0","Details":{"ApiVersion":"1.47","Arch":"arm64","BuildTime":"Sat Dec  7 10:39:01 2024","Experimental":"false","GitCommit":"92a8393","GoVersion":"go1.22.10","KernelVersion":"6.8.0-50-generic","MinAPIVersion":"1.24","Os":"linux"}},{"Name":"containerd","Version":"1.7.24","Details":{"GitCommit":"88bf19b2105c8b17560993bee28a01ddc2f97182"}},{"Name":"runc","Version":"1.2.2","Details":{"GitCommit":"v1.2.2-0-g7cb3632"}},{"Name":"docker-init","Version":"0.19.0","Details":{"GitCommit":"de40ad0"}}],"Version":"27.4.0","ApiVersion":"1.47","MinAPIVersion":"1.24","GitCommit":"92a8393","GoVersion":"go1.22.10","Os":"linux","Arch":"arm64","KernelVersion":"6.8.0-50-generic","BuildTime":"2024-12-07T10:39:01.000000000+00:00"}}
[17350 ms] Stop (18 ms): Run: docker version --format {{json .}}
[17352 ms] Start: Run: docker ps -q
[17364 ms] Stop (12 ms): Run: docker ps -q
[17365 ms] Start: Run: docker inspect --type container 1254d7c0915a
[17376 ms] Stop (11 ms): Run: docker inspect --type container 1254d7c0915a
```

And once selected (the same container i tried connecting before with the command) it works correctly with the logs:
```
[14 ms] Dev Containers 0.422.0 in VS Code 1.102.0 (cb0c47c0cfaad0757385834bd89d410c78a856c0).
[14 ms] Start: Resolving Remote
[15 ms] Setting up container: /container_name
[15 ms] Context: colima
[18 ms] Start: Run: docker inspect --type container /container_name
[37 ms] Stop (19 ms): Run: docker inspect --type container /container_name
[39 ms] Start: Check Docker is running
[39 ms] Start: Run: docker version
[50 ms] Client: Docker Engine - Community
 Version:           28.3.2
 API version:       1.47 (downgraded from 1.51)
 Go version:        go1.24.5
 Git commit:        578ccf607d
 Built:             Wed Jul  9 12:04:02 2025
 OS/Arch:
[50 ms]            darwin/arm64
 Context:           colima

Server: Docker Engine - Community
 Engine:
  Version:          27.4.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.10
  Git commit:       92a8393
  Built:            Sat Dec  7 10:39:01 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.24
  GitCommit:        88bf19b2105c8b17560993bee28a01ddc2f97182
 runc:
  Version:          1.2.2
  GitCommit:        v1.2.2-0-g7cb3632
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
[51 ms] Stop (12 ms): Run: docker version
[51 ms] Stop (12 ms): Check Docker is running
[51 ms] Running Dev Containers CLI:   set-up --container-id ......
```

I can see that there is a difference on the logs regarding the `Contex: colima` but have no idea where to look or what to try. 


I'll also add the basic version of the script im using:

```bash
#!/bin/bash

readonly CONTAINER_NAME="container_name"
readonly WORKSPACE_DIR="workspace"
readonly DOCKER_COMPOSE_FILE="docker/docker-compose.yml"

cleanup() {
  # some stuff
  docker-compose -f "$DOCKER_COMPOSE_FILE" down
}

trap cleanup EXIT

docker-compose -f "$DOCKER_COMPOSE_FILE" up -d

# CONTAINER_ID=$(docker ps -q --filter "name=$CONTAINER_NAME")
# HEX_ID=$(printf "$CONTAINER_ID" | od -A n -t x1 | sed 's/ *//g' | tr -d '\n')
HEX_NAME=$(printf "/$CONTAINER_NAME" | od -A n -t x1 | sed 's/ *//g' | tr -d '\n')
# code --folder-uri "vscode-remote://attached-container+${HEX_ID}/workspace"
code --folder-uri "vscode-remote://attached-container+${HEX_NAME}/workspace"

fswatch -r "$WORKSPACE_DIR" | while read -r full_path; do
  if [ -e "$full_path" ]; then
    # other stuff
  fi
done
```

**Comment by mauro-lanza** [comment]
> I can see that there is a difference on the logs regarding the Contex: colima but have no idea where to look or what to try.

~After running a colima delete and start with virtiofs its now working, tried again with the default sshfs and both work. So if you as me came through this thread and ended up having an issue, give it a try. Restarting the colima vm a few time may also work for you.~

Found the magic command, when creating this link everything works, if i remove the link it breaks again:
`sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock`

**Comment by tuunit** [comment]
> > I can see that there is a difference on the logs regarding the Contex: colima but have no idea where to look or what to try.
> 
> ~After running a colima delete and start with virtiofs its now working, tried again with the default sshfs and both work. So if you as me came through this thread and ended up having an issue, give it a try. Restarting the colima vm a few time may also work for you.~
> 
> Found the magic command, when creating this link everything works, if i remove the link it breaks again: `sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock`

Yes that is because VSCode expects the docker socket to be present in the default location. I haven't used devcontainers or vscode in a while and don't know if this behaviour can be configured to use a different socket location

**Comment by andrei-e-random** [comment]
@mauro-lanza 

> > I can see that there is a difference on the logs regarding the Contex: colima but have no idea where to look or what to try.
> 
> ~After running a colima delete and start with virtiofs its now working, tried again with the default sshfs and both work. So if you as me came through this thread and ended up having an issue, give it a try. Restarting the colima vm a few time may also work for you.~
> 
> Found the magic command, when creating this link everything works, if i remove the link it breaks again: `sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock`

That only works if your colima profile is `default`. This, on the other hand, might work on a larger subset of possible docker contexts.

```bash
DOCKER_HOST=$(docker context inspect $(docker context show) --format '{{ .Endpoints.docker.Host }}') \
code --disable-workspace-trust \
--file-uri "vscode-remote://attached-container+${HEX_CONTAINER_NAME}${CODE_WORKSPACE_PATH_IN_CONTAINER}"
```

To me, it looks like a bug in `vscode-remote`, it seems they are not considering the current docker context and go to `default`. Too bad it ain't open.

Do not leave `DOCKER_HOST` set (do not use `export` or make sure to `unset` it afterwards. Mixing up `DOCKER_HOST` _and_ docker contexts may lead to unpredictable behavior. Once started, `code` correctly picks up the context, their issue seems to apply only on folder/file uri handling.
