### ISSUE TITLE
Another SSH reconnecting issue

### ISSUE THREAD

**Issue by DanPhonovation** [microsoft/vscode-remote-release#5279]
Hi, having a really frustrating issue that seems limited to one host. Its crept out of nowhere.

Using SSH keys to connect to my remote host. After about 5-10 minutes, the connection drops. Even wireshark'ing the traffic - no attempt is even made. I can close and reopen VSCode and it will reconnect fine. I can start connections from other apps while VSCode is in a reconnecting state. But without a relaunch VSCode won't connect again.

I get nothing useful in remoteagent.log on the remote end.

On the local end, as I flip through the dropdown of logs, the only relevant bit seems this;

`[2021-07-01 20:14:43.692] [renderer1] [info] [remote-connection][ExtensionHost][05e29…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-07-01 20:14:43.692] [renderer1] [info] [remote-connection][ExtensionHost][05e29…][reconnect] resolving connection...
[2021-07-01 20:14:43.693] [renderer1] [info] [remote-connection][ExtensionHost][05e29…][reconnect] connecting to 127.0.0.1:13126...
[2021-07-01 20:14:50.462] [renderer1] [info] [remote-connection][Management   ][495b3…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2021-07-01 20:14:50.464] [renderer1] [info] [remote-connection][Management   ][495b3…][reconnect] resolving connection...
[2021-07-01 20:15:13.696] [renderer1] [error] [remote-connection][ExtensionHost][05e29…][reconnect][127.0.0.1:13126] socketFactory.connect() failed or timed out. Error:
[2021-07-01 20:15:13.696] [renderer1] [error] Error: Time limit reached
    at s._createTimeoutError (file:///C:/Users/myuser/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:634:141248)
    at s._timeout (file:///C:/Users/myuser/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:634:141194)
    at file:///C:/Users/myuser/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:634:140936
    at n.fire (file:///C:/Users/myuser/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at R.cancel (file:///C:/Users/myuser/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:15419)
    at k.cancel (file:///C:/Users/myuser/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:15960)
    at file:///C:/Users/myuser/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:634:140406
[2021-07-01 20:15:13.696] [renderer1] [info] [remote-connection][ExtensionHost][05e29…][reconnect] A network error occurred while trying to reconnect, will try again...
[2021-07-01 20:15:13.696] [renderer1] [info] [remote-connection][ExtensionHost][05e29…][reconnect] waiting for 5 seconds before reconnecting...
[2021-07-01 20:15:18.228] [renderer1] [warning] UNRESPONSIVE extension host, 'ms-vscode-remote.remote-ssh' took 88% of 5045.768ms, saved PROFILE here: 'file:///c%3A/Users/myuser/AppData/Local/Temp/exthost-49ab04.cpuprofile' [{"id":"gc","total":579059,"percentage":11},{"id":"ms-vscode-remote.remote-ssh","total":4415192,"percentage":88},{"id":"program","total":45373,"percentage":1},{"id":"self","total":5932,"percentage":0}]
[2021-07-01 20:15:18.705] [renderer1] [info] [remote-connection][ExtensionHost][05e29…][reconnect] resolving connection...
[2021-07-01 20:16:05.710] [renderer1] [warning] UNRESPONSIVE extension host, 'ms-vscode-remote.remote-ssh' took 71% of 5052.141ms, saved PROFILE here: 'file:///c%3A/Users/myuser/AppData/Local/Temp/exthost-7b735d.cpuprofile' [{"id":"gc","total":1406576,"percentage":28},{"id":"ms-vscode-remote.remote-ssh","total":3587218,"percentage":71},{"id":"program","total":51759,"percentage":1},{"id":"self","total":6387,"percentage":0}]`

Things I've tried:

* blowing out .vscode-server on remote end
* removing all custom mappings on my local machine
* rebooting the remote end (CentOS 7) as well as my local end (Win 10, latest and up to date)
* Ensuring no remote extensions are installed
* Mostly everything from here: https://github.com/microsoft/vscode-remote-release/issues/246#issuecomment-511782776

This is a HUGE workspace (ansible/terraform). I did get a warning about not being able to watch due to the sysctl thing. Which I changed to the maximum. The warning hasn't appeared since. Don't know if this is relevant.

I'm extremely frustrated, as its interrupting a workflow on an important project. 

What else can I look at?

 I assume this 13126 port is the local port for the ExtensionHost node.js based app that is doing work on behalf of vscode-remote. So it's crashing?

Thanks for any help in advance

**Comment by DanPhonovation** [comment]
Definitely not workspace related. I opened a second VSCode to a separate folder workspace on the same box. And they lost connection at the same time. I can launch a 3rd window and reconnect or drop into a 3rd workspace, no problem. But the original windows never reconnect.

**Comment by DanPhonovation** [comment]
Tried on 3 new machines that have never seen VSCode. Same effect.

Remote end is fully up to date. I did notice in VSphere the NICs were of the VMXNET type. Not E1000. 

I also noticed a bash process go haywire every time VSCode locks up. I've killed it a few times.

It's been 30 mins and I haven't been disconnected.

Holding my breath.

**Comment by DanPhonovation** [comment]
I figured it out!

I have 10 NICs on this VM.

When I changed to E1000, I only left the first one connected. Continued  with my workflow.

Said workflow demanded I turn 2 other adapters back on. When I did, a short time later my VSCode disconnected. I went to go disconnect them and it instantly returned.

Routing table looks fine. Other processes are able to reach this host over the same link and ip. There are no overlaps. Simple /24s. 

This combined with the extremely excited bash process spawned by vscode during these times - lead me to believe the vscode-server doesn't like something about multi-homing?


```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         gateway         0.0.0.0         UG    103    0        0 ens192
ansible. 0.0.0.0         255.255.255.255 UH    100    0        0 ens194
10.1.76.0       0.0.0.0         255.255.255.0   U     107    0        0 ens256
10.1.78.0       0.0.0.0         255.255.255.0   U     101    0        0 ens161
10.1.200.0      0.0.0.0         255.255.255.0   U     104    0        0 ens193
10.1.204.0      0.0.0.0         255.255.255.0   U     106    0        0 ens225
10.1.70.0      0.0.0.0         255.255.255.0   U     105    0        0 ens224
10.1.71.0      0.0.0.0         255.255.255.0   U     103    0        0 ens192
10.1.50.0      0.0.0.0         255.255.255.0   U     108    0        0 ens257
10.1.51.0      0.0.0.0         255.255.255.0   U     102    0        0 ens162

```

**Comment by DanPhonovation** [comment]
This is still ongoing unfortunately. Above did not end up helping.

**Comment by roblourens** [comment]
> Said workflow demanded I turn 2 other adapters back on. When I did, a short time later my VSCode disconnected.

I have no clue why that would impact us. I don't know anything about the types of NICs that you describe. But the problem you're describing is generally due to extensions hogging the extension host process and making the client think it stopped responding. We are tracking issues like that in https://github.com/microsoft/vscode/issues/135021

Do you have any remote extensions installed? Does it help to disable them? Do you see processes using high cpu and what is the full command line of that process?
