### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by kale1d0code** [microsoft/vscode-remote-release#5289]
Issue Type: <b>Bug</b>

clone https://github.com/microsoft/vscode-remote-try-php
attempt to open project in a dev-container

Extension version: 0.183.0
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.11.0-22-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3099)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 3, 2|
|Memory (System)|11.61GB (1.85GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 18d2850e-57ce-49b0-80e1-78bffcc8d3ef|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by kale1d0code** [comment]
`
SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)
        at Cf (/home/<user_folder>/.vscode/extensions/ms-vscode-remote.remote-containers-0.183.0/dist/extension/extension.js:214:1206)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at async fc (/home/<user_folder>/.vscode/extensions/ms-vscode-remote.remote-containers-0.183.0/dist/extension/extension.js:214:944)
        at async fI (/home/<user_folder>/.vscode/extensions/ms-vscode-remote.remote-containers-0.183.0/dist/extension/extension.js:250:1129)
        at async Hz (/home/<user_folder>/.vscode/extensions/ms-vscode-remote.remote-containers-0.183.0/dist/extension/extension.js:236:10239)
        at async UD (/home/<user_folder>/.vscode/extensions/ms-vscode-remote.remote-containers-0.183.0/dist/extension/extension.js:236:6872)
        at async wz (/home/<user_folder>/.vscode/extensions/ms-vscode-remote.remote-containers-0.183.0/dist/extension/extension.js:217:9939)
`

**Comment by kale1d0code** [comment]
it seems I missed out a bit of the documentation.
I use using the snap version of docker.

now I have switched over this is working properly
