### ISSUE TITLE
Install terminal quit with output: server died, exit

### ISSUE THREAD

**Issue by zplorer52** [microsoft/vscode-remote-release#5306]
- VSCode Version:
Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 6.1.7601

- Local OS Version: Windows_NT x64 6.1.7601
- Remote OS Version: Windows_NT x64 6.1.7601 (Local/Remote are same Windows7 prof)
- Remote Extension/Connection Type: SSH (OpenSSH_for_Windows_8.6p1, LibreSSL 3.3.3)
- PowerShell Version: 
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14409  1005

- Logs:
[09:56:34.826] Log Level: 2
[09:56:34.832] remote-ssh-nightly@2021.5.29700
[09:56:34.832] win32 x64
[09:56:34.833] SSH Resolver called for "ssh-remote+10.29.164.219", attempt 1
[09:56:34.833] "remote.SSH.useLocalServer": false
[09:56:34.833] "remote.SSH.showLoginTerminal": false
[09:56:34.833] "remote.SSH.remotePlatform": {"10.29.34.171":"linux","10.29.164.219":"windows"}
[09:56:34.834] "remote.SSH.path": D:\Downloaded\OpenSSH-Win64\ssh.exe
[09:56:34.834] "remote.SSH.configFile": undefined
[09:56:34.834] "remote.SSH.useFlock": true
[09:56:34.834] "remote.SSH.lockfilesInTmp": false
[09:56:34.834] "remote.SSH.localServerDownload": auto
[09:56:34.834] "remote.SSH.remoteServerListenOnSocket": false
[09:56:34.834] "remote.SSH.showLoginTerminal": false
[09:56:34.834] "remote.SSH.defaultExtensions": []
[09:56:34.835] "remote.SSH.loglevel": 2
[09:56:34.835] SSH Resolver called for host: 10.29.164.219
[09:56:34.835] Setting up SSH remote "10.29.164.219"
[09:56:34.855] Using commit id "507ce72a4466fbb27b715c3722558bb15afa9f48" and quality "stable" for server
[09:56:34.858] Install and start server if needed
[09:56:34.863] Checking ssh with "D:\Downloaded\OpenSSH-Win64\ssh.exe -V"
[09:56:34.955] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.3.3

[09:56:34.960] Remote command length: 5993/8192 characters
[09:56:34.960] Running script with connection command: "D:\Downloaded\OpenSSH-Win64\ssh.exe" -T -D 60640 "10.29.164.219" powershell
[09:56:34.962] Terminal shell path: C:\Windows\System32\cmd.exe
[09:56:35.705] > 
[09:56:35.706] Got some output, clearing connection timeout
[09:56:37.001] > MySTN52@10.29.164.219's password:
[09:56:37.001] Showing password prompt
[09:56:39.746] Got password response
[09:56:39.747] "install" wrote data to terminal: "**"
[09:56:39.785] > 
> 
[09:56:40.708] > Windows PowerShell
> Copyright (C) 2016 Microsoft Corporation. All rights reserved.
> 
> PS C:\Users\MySTN52>
> PS C:\Users\MySTN52> $uuid="577b563e9b44"
> PS C:\Users\MySTN52> "${uuid}: running"
> 577b563e9b44: running
> PS C:\Users\MySTN52> "577b563e9b44: pauseLog"
> 577b563e9b44: pauseLog
[09:56:41.250] > Acquiring lock on C:\Users\MySTN52\.vscode-server\bin\507ce72a4466fbb27b715c3722
> 558bb15afa9f48\vscode-remote-lock.507ce72a4466fbb27b715c3722558bb15afa9f48
> 
[09:56:41.276] > Looking for existing server in C:\Users\MySTN52\.vscode-server\bin\507ce72a4466f
> bb27b715c3722558bb15afa9f48
> Downloading server
> 577b563e9b44%%1%%
> 
[09:57:04.943] > Expanding server into C:\Users\MySTN52\AppData\Local\Temp\3222k34a.ikf
> 577b563e9b44%%2%%
> 
[09:57:12.789] > 
> 
>     Directory: C:\Users\MySTN52\.vscode-server
> 
> 
> Mode                LastWriteTime         Length Name
> ----                -------------         ------ ----
> -a----       09/07/2021   9:57 AM              0 .507ce72a4466fbb27b715c3722558
>                                                  bb15afa9f48.token
> 
[09:57:12.823] > Successfully processed 1 files; Failed processing 0 files
> 
[09:57:12.858] > Successfully processed 1 files; Failed processing 0 files
> Successfully processed 1 files; Failed processing 0 files
> 
[09:57:12.883] > Successfully processed 1 files; Failed processing 0 files
> Starting server: & 'C:\Users\MySTN52\.vscode-server\bin\507ce72a4466fbb27b715c37
> 22558bb15afa9f48\server.cmd' --start-server --host=127.0.0.1 --enable-remote-aut
> o-shutdown --port=0 --connection-secret 'C:\Users\MySTN52\.vscode-server\.507ce7
> 2a4466fbb27b715c3722558bb15afa9f48.token'   *> 'C:\Users\MySTN52\.vscode-server\
> .507ce72a4466fbb27b715c3722558bb15afa9f48.log'
> 
[09:57:16.924] > Server did not start successfully. Full server log at C:\Users\MySTN52\.vscode-s
> erver\.507ce72a4466fbb27b715c3722558bb15afa9f48.log >>>
> C:\Users\MySTN52\.vscode-server\bin\507ce72a4466fbb27b715c3722558bb15afa9f48\se
> rver.cmd : Node.js is only supported on Windows 8.1, Windows Server 2012 R2,
> or higher.
> At line:1 char:1
> + C:\Users\MySTN52\.vscode-server\bin\507ce72a4466fbb27b715c3722558bb15 ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (Node.js is only... R2, or higher.
>    :String) [], RemoteException
>     + FullyQualifiedErrorId : NativeCommandError
> 
> S
> e
> t
> t
> i
> n
> g
> 
> t
> h
> e
> 
> N
[09:57:16.979] > 
> O
> D
> E
> _
> S
> K
> I
> P
> _
> P
> L
> A
> T
> F
> O
> R
> M
> _
> C
> H
> E
> C
> K
> 
> e
> n
> v
> i
> r
> o
> n
> m
> e
> n
> t
> 
> v
> a
> r
> i
> a
> b
> l
> e
> 
> t
> o
> 
> 1
> 
> s
> k
> i
> p
> s
> 
> t
> h
> i
> s
> 
> 
> c
> h
> e
> c
> k
> ,
> 
> b
> u
> t
> 
> N
> o
> d
> e
> .
> j
> s
> 
> m
> i
> g
> h
> t
> 
> n
> o
> t
> 
> e
> x
> e
> c
> u
> t
> e
> 
> c
> o
> r
> r
> e
> c
> t
> l
> y
> .
> 
> A
> n
> y
> 
> i
> s
> s
> ues encountered on
> unsupported platforms will not be fixed.
> <<< End of server log
> 577b563e9b44: start
> exitCode==32==
> listeningOn====
> osReleaseId==windows==
> osVersion====
> arch==x64==
> platform==windows==
> unpackResult==success==
> didLocalDownload==False==
> downloadTime==23672==
> installTime==7779==
> extInstallTime====
> serverStartTime==169==
> 577b563e9b44: end
> 
[09:57:16.980] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==windows==
osVersion====
arch==x64==
platform==windows==
unpackResult==success==
didLocalDownload==False==
downloadTime==23672==
installTime==7779==
extInstallTime====
serverStartTime==169==

[09:57:16.981] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (c:\Users\MySTN52\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:1:64593)
	at c (c:\Users\MySTN52\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:1:58918)
	at Object.t.handleInstallOutput (c:\Users\MySTN52\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:1:63335)
	at Object.t.tryInstall (c:\Users\MySTN52\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:1:415135)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\MySTN52\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:1:294918
	at async Object.t.withShowDetailsEvent (c:\Users\MySTN52\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:1:406463)
	at async Object.t.resolve (c:\Users\MySTN52\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:1:295994)
	at async c:\Users\MySTN52\.vscode\extensions\ms-vscode-remote.remote-ssh-nightly-2021.5.29700\out\extension.js:127:110656
[09:57:16.987] ------

[09:57:17.414] > 577b563e9b44: start
> SSH_AUTH_SOCK====
> listeningOn====
> osReleaseId==windows==
> osVersion==6.1.7601==
> arch==x64==
> platform==windows==
> unpackResult==success==
> didLocalDownload==False==
> downloadTime==23672==
> installTime==7779==
> extInstallTime====
> serverStartTime==169==
> connectionToken==1a11a1a1-1a1a-111a-1a11-1111111111a1==
> 577b563e9b44: end
> 5508, watching 8600
> gps : Cannot find a process with the process identifier 7700.
> At line:3 char:7
> + if (!(gps -Id $v_)) {
> +       ~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (7700:Int32) [Get-Process], Proc
>    essCommandException
>     + FullyQualifiedErrorId : NoProcessFoundForGivenId,Microsoft.PowerShell.Co
>    mmands.GetProcessCommand
> 
> server died, exit
> 
[09:57:17.692] "install" terminal command done
[09:57:17.694] Install terminal quit with output: server died, exit
Steps to Reproduce:

1. With PS v2 stuck at "Install" wrote data to terminal:"**"
2. After updating [PS V5](https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/wmf/setup/install-configure?view=powershell-7.1#download-and-install-the-wmf-51-package)

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by bamurtaugh** [comment]
Thanks for reporting @zplorer52. Are you able to repro this regularly? And could you clarify "Both Local and Remote. The above logs are generated while testing locally" - do you see this terminal message in local VS Code as well, not using any remote extensions?

**Comment by zplorer52** [comment]
Hi, thanks for reply.
Local means, Local ssh server connection with vscode remote extension.

Remote means, connecting remote ssh server with vscode remote extension.

Both results same, are windows7 pro. Problem is due to nodejs initiated by
vscode which is v14 and not support on windows7 os.

**Comment by deepak1556** [comment]
Yeah Electron plans to support it till chrome marks it EOL which is currently set for January, 2022.
