### ISSUE TITLE
Error: No command or PTY requested

### ISSUE THREAD

**Issue by eps1lon** [microsoft/vscode-remote-release#5336]
Issue Type: <b>Bug</b>

Connecting to a CircleCI job available via VSCode remote ssh fails. Connecting just via `ssh -p 64535 3.81.73.197` works fine.

CI job: https://app.circleci.com/pipelines/github/mui-org/material-ui/49257/workflows/37e99ed7-106c-484f-a80a-c3d396ec484d/jobs/274850

ssh config:
```
Host 3.81.73.197
  HostName 3.81.73.197
  Port 64535
  User eps1lon
  IdentityFile ~/.ssh/id_rsa
```

log:

```
[10:38:17.023] Log Level: 2
[10:38:17.025] remote-ssh@0.65.7
[10:38:17.025] linux x64
[10:38:17.025] SSH Resolver called for "ssh-remote+3.81.73.197", attempt 1
[10:38:17.026] "remote.SSH.useLocalServer": true
[10:38:17.026] "remote.SSH.path": undefined
[10:38:17.026] "remote.SSH.configFile": undefined
[10:38:17.026] "remote.SSH.useFlock": true
[10:38:17.026] "remote.SSH.lockfilesInTmp": false
[10:38:17.027] "remote.SSH.localServerDownload": auto
[10:38:17.027] "remote.SSH.remoteServerListenOnSocket": false
[10:38:17.027] "remote.SSH.showLoginTerminal": false
[10:38:17.027] "remote.SSH.defaultExtensions": []
[10:38:17.027] "remote.SSH.loglevel": 2
[10:38:17.027] SSH Resolver called for host: 3.81.73.197
[10:38:17.027] Setting up SSH remote "3.81.73.197"
[10:38:17.030] Acquiring local install lock: /tmp/vscode-remote-ssh-3.81.73.197-install.lock
[10:38:17.044] Looking for existing server data file at /home/eps1lon/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-3.81.73.197-507ce72a4466fbb27b715c3722558bb15afa9f48-0.65.7/data.json
[10:38:17.045] Using commit id "507ce72a4466fbb27b715c3722558bb15afa9f48" and quality "stable" for server
[10:38:17.047] Install and start server if needed
[10:38:17.059] PATH: /home/eps1lon/.flossbank/bin:/home/eps1lon/.yarn/bin:/home/eps1lon/.flossbank/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[10:38:17.059] Checking ssh with "ssh -V"
[10:38:17.065] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020

[10:38:17.068] askpass server listening on /run/user/1000/vscode-ssh-askpass-d157a704630fb4ed35c281e466bf55f7c9b25d67.sock
[10:38:17.068] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-f5cac52264992abf4fcbe71c122775a7a579671f.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","42667","-o","ConnectTimeout=15","3.81.73.197"],"dataFilePath":"/home/eps1lon/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-3.81.73.197-507ce72a4466fbb27b715c3722558bb15afa9f48-0.65.7/data.json"}
[10:38:17.068] Local server env: {"DISPLAY":":1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/eps1lon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/eps1lon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-d157a704630fb4ed35c281e466bf55f7c9b25d67.sock"}
[10:38:17.071] Spawned 502868
[10:38:17.138] > local-server-1> Spawned ssh, pid=502876
[10:38:17.138] stderr> OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020
[10:38:17.568] stderr> debug1: Server host key: ssh-rsa SHA256:OTMuDGJZamCS1hAcNLNjUbKASng6ut8KuTKAhTNOW8I
[10:38:18.171] stderr> Authenticated to 3.81.73.197 ([3.81.73.197]:64535).
[10:38:18.381] stderr> Transferred: sent 4124, received 1932 bytes, in 0.2 seconds
[10:38:18.381] stderr> Bytes per second: sent 19948.8, received 9345.5
[10:38:18.382] > Error: No command or PTY requested
> local-server-1> ssh child died, shutting down
[10:38:18.391] Local server exit: 0
[10:38:18.393] Received install output: local-server-1> Spawned ssh, pid=502876
OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020
debug1: Server host key: ssh-rsa SHA256:OTMuDGJZamCS1hAcNLNjUbKASng6ut8KuTKAhTNOW8I
Authenticated to 3.81.73.197 ([3.81.73.197]:64535).
Transferred: sent 4124, received 1932 bytes, in 0.2 seconds
Bytes per second: sent 19948.8, received 9345.5
Error: No command or PTY requested
local-server-1> ssh child died, shutting down

[10:38:18.395] Failed to parse remote port from server output
[10:38:18.399] Resolver error: Error: 
	at Function.Create (/home/eps1lon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:64659)
	at Object.t.handleInstallOutput (/home/eps1lon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:63302)
	at Object.e [as tryInstallWithLocalServer] (/home/eps1lon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:387573)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/eps1lon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:294473
	at async Object.t.withShowDetailsEvent (/home/eps1lon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:406463)
	at async /home/eps1lon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:386112
	at async E (/home/eps1lon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:382710)
	at async Object.t.resolveWithLocalServer (/home/eps1lon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:385728)
	at async Object.t.resolve (/home/eps1lon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:295870)
	at async /home/eps1lon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:127:110656
[10:38:18.426] ------
```

Extension version: 0.65.7
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.4.0-77-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 3900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|15.57GB (1.38GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 5f6e1c4c-dc37-41aa-be95-976a93109367|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
bridge0708:30335490

```

</details>

**Comment by dronl** [comment]
I got the same issue, can we provide a parameter to remove -T?

**Comment by roblourens** [comment]
Can you get the same failure if you run something like `echo "echo hello" | ssh -T yourhost`?

**Comment by eps1lon** [comment]
> Can you get the same failure if you run something like `echo "echo hello" | ssh -T yourhost`?

```sh
~ $ echo "echo hello" | ssh -p 64535 52.91.208.102
Pseudo-terminal will not be allocated because stdin is not a terminal.
Error: No command or PTY requested
```

I don't know what this means but it sounds like there's an issue on my side/CircleCIs side that should be adressed first?

**Comment by roblourens** [comment]
I think so - I have an incomplete understanding of exactly how that flag behaves in every situation, but I think it is correct here and should work. I don't want to do something like add a setting to disable it unless I know that there is a good reason for it.
