### ISSUE TITLE
Error starting vscode server under Windows 10

### ISSUE THREAD

**Issue by lucasmgcic** [microsoft/vscode-remote-release#5338]
I tried to use vs code from a Linux client to a server running under Windows 10 with OpenSSH server installed as suggested in Documentation. I am able to connect via ssh to the server machine, but i did not manage to use vs code remote. Reading the log (posted here), it seems to be an issue in starting the vscode server in Windows, maybe caused for some node incompatibilty. Any tips ?

If futher information is needed, let me know.

Best Regards

--------------------

[12:42:52.143] Log Level: 2
[12:42:52.144] remote-ssh@0.61.0
[12:42:52.144] linux x64
[12:42:52.145] SSH Resolver called for "ssh-remote+192.168.3.15", attempt 1
[12:42:52.146] "remote.SSH.useLocalServer": true
[12:42:52.146] "remote.SSH.sshPath": undefined
[12:42:52.146] "remote.SSH.sshConfigurationFile": undefined
[12:42:52.146] "remote.SSH.useFlock": true
[12:42:52.147] "remote.SSH.lockfilesInTmp": false
[12:42:52.147] "remote.SSH.localServerDownload": auto
[12:42:52.152] "remote.SSH.remoteServerListenOnSocket": false
[12:42:52.152] "remote.SSH.showLoginTerminal": false
[12:42:52.152] "remote.SSH.maxReconnectionAttempts": 9007199254740991
[12:42:52.152] SSH Resolver called for host: 192.168.3.15
[12:42:52.152] Setting up SSH remote "192.168.3.15"
[12:42:52.155] Acquiring local install lock: /tmp/vscode-remote-ssh-192.168.3.15-install.lock
[12:42:52.176] Looking for existing server data file at /home/local_user/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-192.168.3.15-cd9ea6488829f560dc949a8b2fb789f3cdc05f5d-0.61.0/data.json
[12:42:52.177] Using commit id "cd9ea6488829f560dc949a8b2fb789f3cdc05f5d" and quality "stable" for server
[12:42:52.179] Install and start server if needed
[12:42:52.190] Checking ssh with "ssh -V"
[12:42:52.196] > OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017

[12:42:52.199] askpass server listening on /run/user/1001/vscode-ssh-askpass-18abbf9ad4f8e35e685c6fe673fcf7e562805d76.sock
[12:42:52.199] Spawning local server with {"ipcHandlePath":"/run/user/1001/vscode-ssh-askpass-5e439f8dcd41dcacad6556b1cfc25b22e17bdff9.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","46451","-o","ConnectTimeout=15","192.168.3.15"],"dataFilePath":"/home/local_user/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-192.168.3.15-cd9ea6488829f560dc949a8b2fb789f3cdc05f5d-0.61.0/data.json"}
[12:42:52.199] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/local_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.61.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/local_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.61.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1001/vscode-ssh-askpass-18abbf9ad4f8e35e685c6fe673fcf7e562805d76.sock"}
[12:42:52.203] Spawned 8874
[12:42:52.277] > local-server> Spawned ssh: 8884
[12:42:52.279] stderr> OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
[12:42:52.597] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:nPLRpVc1Ugv25Zh2f2qf8WPEvoYsETl+oZg14Dujv1s
[12:42:52.855] Got askpass request: {"request":"user@192.168.3.15's password:"}
[12:42:52.855] Showing password prompt
[12:42:52.856] Listening for interwindow password on /run/user/1001/vscode-ssh-askpass-603d023865e02a865e5ade89744d14ac4ac66f0f.sock
[12:42:52.856] Writing password prompt to globalState
[12:42:56.795] Got password response
[12:42:56.796] Interactor gave response: *************
[12:42:56.797] Cleaning up other-window auth server
[12:42:56.881] stderr> Authenticated to 192.168.3.15 ([192.168.3.15]:22).
[12:42:57.108] > Microsoft Windows [vers�o 10.0.18363.1556]
[12:42:57.164] > 
> (c) 2019 Microsoft Corporation. Todos os direitos reservados.
[12:42:57.164] > domain\user@server_machine d:\Users\user>echo 'ready: b67455340ffa'
> 'ready: b67455340ffa'
> 
> domain\user@server_machine d:\Users\user>
[12:42:57.229] > uname -rsv
[12:42:57.463] > MSYS_NT-10.0-18363 3.0.7-338.x86_64 2019-07-11 10:58 UTC
[12:42:57.464] Platform: windows
[12:42:57.465] Remote command length: 6912/8192 characters
[12:42:57.473] > 
> domain\user@server_machine d:\Users\user>
[12:42:57.489] > powershell -NoProfile
[12:42:57.731] > Windows PowerShell
> Copyright (C) Microsoft Corporation. Todos os direitos reservados.
> 
> Experimente a nova plataforma cruzada PowerShell https://aka.ms/pscore6
[12:42:57.741] > 
[12:42:57.890] > PS D:\Users\user> 
[12:42:58.130] > p
[12:42:58.131] > owershell -ExecutionPolicy Unre
[12:42:58.133] > stricted -NoLogo -NoProfile -NonInteractive -Command "`$remoteSSHConfigurationScript=[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('CiR1dWlkPSJiNjc0NTUzNDBmZmEiCiIke
[12:42:58.134] > 3V1aWR9OiBydW5uaW5nIgokUHJvZ3Jlc3NQcmVmZXJlbmNlPSdTaWxlbnRseUNvbnRpbnVlJwokbj0nY2Q5ZWE2NDg4ODI5ZjU2MGRjOTQ5YThiMmZiNzg5ZjNjZGMwNWY1ZCcKJHA9JGVudjpQUk9DRVNTT1JfQVJDSElURUNUVVJFCiRhcmNoPWlmICgoJHAgLWVxICdBTUQ2NCcpIC1vciAoJHAgLWVxICdJQTY0JykpIHsgJ3g2NCcgfSBlbHNlIHsgJ2lhMzInIH0KJG89KEpvaW4tUGF0aCAoUmVzb2x2ZS1QY
[12:42:58.135] > XRoIH4pICcudnNjb2RlLXNlcnZlcicpCiRlbnY6VlNDT0RFX0FHRU5UX0ZPTERFUj0kbwokbG9nPSIkb1wuJG4ubG9nIgokc0Rpcj0iJG9cYmluXCRuIgokcD0nc3RhYmxlJwokcT0iIgokZXh0cz0iIgokZz0kVHJ1ZQokaD0kRmFsc2UKJGdsb2JhbDpyID0gJEZhbHNlCiRnbG9iYWw6cyA9ICcnCiRnbG9iYWw6aiA9ICcnCiRnbG9iYWw6ayA9ICcnCiRnbG9i
[12:42:58.136] > YWw6bCA9ICcnCiRnbG9iYWw6bSA9ICcnCmZ1bmN0aW9uIG
[12:42:58.143] > RldGFpbHMgewoibGlzdGVuaW5nT249PSRwb3J0PT0iCiJvc1JlbGVhc2VJZD09d2luZG93cz09Ig
[12:42:58.144] > oib3NWZXJzaW9uPT0kYWg9PSIKImFyY2g9PSRhcmNoPT0iCiJwbGF0Zm9ybT09d2luZG93cz09Igoicz09JHM9PSIKImRpZExvY2FsRG93bmxvYWQ9PSRyPT0iCiJkb3dubG9hZFRpbWU9PSRqPT0iCiJpbnN0YWxsVGltZT09JGs9PSIKImV4dEluc3RhbGxUaW1lPT0kbD09Igoic2VydmVyU3RhcnRUaW1lPT0kbT09Igp9CmZ1bmN0aW9uIGkgewpyZXR1cm4gW3N5c3RlbS5kaWFnbm9zdGljcy5zdG9wd2F0Y2hdOjpTdGF
[12:42:58.145] > ydE5ldygpOwp9CmZ1bmN0aW9uIHEoJGNvZGUpIHsKIiR7dXVpZH06IHN0YXJ0IgoiZXhpdENvZGU9PSRjb2RlPT0iCmRldGFpbHMKIiR7dXVpZH06IGVuZCIKfQpmdW5jdGlvbiBhIHsKJHQ9JFBJRAp3aGlsZSAoJFRydWUpIHsKJHU9KGdjaW0gd2luMzJfcHJvY2VzcyB8ID8gcHJvY2Vzc2lkIC1lcSAkdCkucGFyZW50cHJvY2Vzc2lkCmlmICghJHUpIHsKIm5
[12:42:58.147] > vIHNzaGQgcGFyZW50IHByb2MiCmV4aXQgMAp9CmlmICgoZ3BzIC1JZCAkdSkuTmFtZSAtZXEgJ3NzaGQnKSB7CnJldHVybiAkdQp9CiR0PSR1Cn0KfQpmdW5jdGlvbiBiIHsKaWYgKCR2KSB7CmlmICghKGdwcyAtSWQgJHYpKSB7CiJzZXJ2ZXIgZGllZCwgZXhpdCIKZXhpdC
[12:42:58.147] > AwCn0KfSBlbHNlIHsKaWYgKCEoZ3BzIC1JZCAkc3NoZFBJRCkpIHsKInNzaGQgcGFyZW50IGRpZWQsIGV4aXQi
[12:42:58.157] > CmV4aXQgMAp9Cn0KfQpmdW5jdGlvbiBjIHsKJHM9aQoiRG93bmxvYWRpbmcgc2VydmVy
[12:42:58.158] > IgoiJHt1dWlkfSUlMSUlIgokdz0iIgokeD1pZiAoJGFyY2ggLWVxICd4NjQnKSB7ICItJGFyY2giIH0gZWxzZSB7ICIiIH0KJHk9InNlcnZlci13aW4zMiR4IiArICR3CiRzcGxhdD1AewpVcmk9Imh0dHBzOi8vdXBkYXRlLmNvZGUudmlzdWFsc3R1ZGlvLmNvbS9jb21taXQ6JG4vJHkvJHAiClRpbWVvdXRTZWM9MjAKT3V0RmlsZT0idnNjb2RlLXNlcnZlci56aXAiClVzZUJhc2ljUGFyc2luZz0kVHJ1ZQp9CltOZXQuU2V
[12:42:58.159] > ydmljZVBvaW50TWFuYWdlcl06OlNlY3VyaXR5UHJvdG9jb2wgPSAnVGxzMTInCmlybSBAc3BsYXQKJHMuU3RvcCgpCiRnbG9iYWw6aiA9ICRzLkVsYXBzZWRNaWxsaXNlY29uZHMKfQpmdW5jdGlvbiBkIHsKJGdsb2JhbDpzPSdzdWNjZXNzJwokcz1pCnRyeSB7CiR6PVtTeXN0ZW0uSU8uUGF0aF06OkdldFJhbmRvb
[12:42:58.160] > UZpbGVOYW1lKCkKJGFhPSIkZW52OlRFTVBcJHoiCiJFeHBhbmRpbmcgc2VydmVyIGludG8gJGFhIgoiJHt1dWlkfSUlMiUlIgpFeHBhbmQtQXJjaGl2ZSAidnNjb2RlLXNlcnZlci56aXAiIC1EZXN0aW5hdGlvblBhdGggIiRhYSIKbXYgIiRhYVx2c2NvZGUtKlwqIiAtRGVzdGluYXRpb24gLgokcy5TdG9wKCkKJGdsb2JhbDprID0gJHMuRWxhcHNlZE1pbGxpc2Vjb25kcwp9IGN
[12:42:58.161] > hdGNoIHsKJGdsb2JhbDpzPSdlcnJvcicKIkZhaWxlZCB0byB1bnppcCBzZXJ2ZXIuIC0gJCgkXy5Ub1N0cmluZygpKSIKZiAzNwpkCn0KaWYoIShUZXN0LVBhdGggIiRzRGlyXHNlcnZlci5jbWQiKSkgewokZ2xvYmFsOnM9J21pc3NpbmdGaWxlcycKIkRvd25sb2FkZW
[12:42:58.169] > Qgc2VydmVyIGlzIGluY29tcGxldGUuIgpmIDM3CmQKfQp9CmZ1bmN0aW9uIFN0YX
[12:42:58.170] > J0U2VydmVyIHsKJHM9aQppZihUZXN0LVBhdGggJGxvZykgewpkZWwgJGxvZwp9CiRhYj0kc0RpciAtcmVwbGFjZSAnICcsICdgICcKJGFyZ3M9Ii0taG9zdD0xMjcuMC4wLjEgLS1lbmFibGUtcmVtb3RlLWF1dG8tc2h1dGRvd24gLS1wb3J0PTAgJHEgKj4gJyRsb2cnIgokc3BsYXQ9QHsKRmlsZVBhdGggPSAicG93ZXJzaGVsbC5leGUiCldpbmRvd1N0eWxlID0gImhpZGRlbiIKQXJndW1lbnRMa
[12:42:58.171] > XN0ID0gQCgKIi1FeGVjdXRpb25Qb2xpY3kiLCAiVW5yZXN0cmljdGVkIiwgIi1Ob0xvZ28iLCAiLU5vUHJvZmlsZSIsICItTm9uSW50ZXJhY3RpdmUiLCAiLWMiLCAiJGFiXHNlcnZlci5jbWQgJGFyZ3MiCikKUGFzc1RocnUgPSAkVHJ1ZQp9CiJTdGFydGluZyBzZXJ2ZXI6ICYgJyRzRGlyXHNlcnZlci5jbWQnICRhcmdzIgokdj0oc3RhcnQgQHNwbG
[12:42:58.172] > F0KS5JRAokcy5TdG9wKCkKJGdsb2JhbDptID0gJHMuRWxhcHNlZE1pbGxpc2Vjb25kcwp9CmZ1bmN0aW9uIGUgewokZ2xvYmFsOnI9JFRydWUKIlRyaWdnZXIgbG9jYWwgc2VydmVyIGRvd25sb2FkIgoiJHt1dWlkfTp0cmlnZ2VyX3NlcnZlcl9kb3dubG9hZCIKInBsYXRmb3JtPT13aW5kb3dzPT
[12:42:58.173] > 0iCiJ2c2NvZGVBcmNoPT0kYXJjaD09IgoiZGVzdEZvbGRlcj09JHNEaXI9PSIKIiR7dXVpZH06dHJpZ2dlcl9zZXJ2ZXJfZG93bmxvYWRfZW5kIgoiV2FpdGluZyBmb3IgY2xpZW50IHRvIHRyYW5zZmVyIHNlcnZlciBhcmNoaXZlLi4uIgoiV2FpdGluZyBmb3IgJHNEaXJcdnNjb2RlLXNjcC1kb25lLmZsYWcgYW5kIHZzY29kZS1zZXJ2ZXIuemlw
[12:42:58.174] > IHRvIGV4aXN0Igp3aGlsZSgkVHJ1ZSkgewppZihUZXN0LVBhdGggIiRzRGlyXHZzY29kZS1zY3AtZG9uZS5mbGFnIikgewppZighKFRlc3QtUGF0aCAiJHNEaXJcdnNjb2RlLXNlcnZlci56aXAiKSkgewoi
[12:42:58.180] > VHJhbnNmZXIgZmFpbGVkIgpxIDMxCn0KIlRyYW5zZmVyIGNvbXBsZXRlIgpkZWwgJHNEaXJcdnNjb2RlLXNjcC1
[12:42:58.181] > kb25lLmZsYWcKYnJlYWsKfSBlbHNlIHsKU3RhcnQtU2xlZXAgLVNlY29uZHMgMwpiCn0KfQp9CmZ1bmN0aW9uIGYoJGNvZGUpIHsKaWYgKCRyKSB7CiJBbHJlYWR5IGF0dGVtcHRlZCBsb2NhbCBkb3dubG9hZCwgZmFpbGluZyIKcSAkY29kZQp9IGVsc2VpZigkZykgewplCn0gZWxzZSB7CnEgJGNvZGUKfQp9CiRzc2hkUElEPWEKaWYoIShUZXN0LVBhdGggJH
[12:42:58.182] > NEaXIpKSB7CiRtPSJDb3VsZC
[12:42:58.186] > Bub3QgY3JlYXRlIHN
[12:42:58.187] > lcnZlciBkaXJlY3RvcnkiCnRyeSB7CiRudWxsPW5pIC1pdCBkICRzRGlyIC1mIC1lYSBzaQp9IGNhdGNoIHsKIiRtLiAtICQoJF8uVG9TdHJpbmcoKSkiCnJldHVybgp9CmlmKCEoVGVzdC1QYXRoICRzRGlyKSkgewoiJG0iCnJldHVybgp9Cn0KY2QgJHNEaXIKJGFjPShKb2luLVBhdGggIiRzRGlyIiAidnNjb2RlLXJlbW90ZS1sb2NrLiRuI
[12:42:58.187] > ikKdHJ5IHsKJG51bGw9bmkgJGFjIC1pdCBmIC1lYSBzaQp9IGNhdGNoIHsKIkNvdWxkIG5vdCBjcmVhdGUgc2VydmVyIGxvY2sgZmlsZS4gLSAkKCRfLlRvU3RyaW5nKCkpIgpyZXR1cm4KfQp0cnkgewoiQWNxdWlyaW5nIGxvY2sgb24gJGFjIgo
[12:42:58.187] > kZmlsZT1bU3lzdGVtLmlvLkZpbGVdOjpPcGVuKCRhYywgJ09wZW4nLCAnUmVhZCcsICdOb25lJykKfSBjYXRjaCB7CiJJbnN0YWxsIGFscmVhZHkgaW4gcHJvZ3Jlc3MuLi4gLSAkKCRfLlRvU3RyaW5nKCkpIgpxIDI0
[12:42:58.188] > Cn0KdHJ5IHsKIkxvb2tpbmcgZm9yIGV4aXN0aW5nIHNlcnZlciBpbiAkc0RpciIKaWYoVGVzdC1QYXRoICIkc0RpclxzZXJ2ZXIuY21kIikgewoiRm91bmQgaW5zdGFsbGVkIHNlcnZlciIKfSBlbHNlIHsKaWYgKCRoKSB7CmUKfSBlbHNlIHsKdHJ5IH
[12:42:58.188] > sgYyB9IGNhdGNoIHsKIkRvd25sb2FkIGZhaWxlZC4gLSAkKCRfLlRvU3RyaW5nKCkpIgpmIDI1Cn0KfQpkCn0KaWYgKCRleHRzIC1uZSAiIikgewokcz1pCiYgIiRzRGlyXHNlcnZlci5jbWQiICRxICRleHRzCiRzLlN0b3AoKQokZ2xvYmFsOmw
[12:42:58.189] > gPSAkcy5FbGFwc2VkTWlsbGlzZWNvbmRzCn0KaWYoIShHZXQtUHJvY2VzcyBub2RlIC1FcnJvckFjdGlvbiBTaWxlbnRseUNvbnRpbnVlIHwgV2hlcmUtT2JqZ
[12:42:58.192] > WN0IFBhdGggLW1hdGNoICRu
[12:42:58.192] > KSkgewpTdGFydFNlcnZlcgp9IGVsc2UgewoiU2VydmVyIHdpdGggJG4gaXMgYWxyZWFkeSBydW5uaW5nLiIKfQokYWY9QHsKUGF0aCA9ICRsb2cKUGF0dGVybiA9ICJFeHRlbnNpb24gaG9zdCBhZ2VudCBsaXN0ZW5pbmcgb24gKFxkKykiCn0KJGFlPUB7ClBhdGggPSAkbG9nClBhdHRlcm4gPSAiISEhISBTZXJ2ZXIgdGVybWlu
[12:42:58.192] > YXRlZCBkdWUgdG8gcHJlc2VuY2Ugb2YgQ1ZFLTIwMjAtMTQxNiAhISEhIgp9CiRhZD0oRGF0ZSkuQWRkU2Vjb25kcyg0KQp3aGl
[12:42:58.196] > sZSAoKERhdGUpIC1sdCAk
[12:42:58.197] > YWQpIHsKaWYoVGVzdC1QYXRoICRsb2cpIHsKJGFnPShzbHMgQGFmKS5NYXRjaGVzLkdyb3VwcwppZigkYWcpIHsKJHBvcnQ9JGFnWzFdLlZhbHVlCmJyZWFrCn0KJGZhaWxlZD0oc2xzIEBhZSkuTWF0Y2hlcy5Hcm91cHMKaWYoJGZhaWxlZCkgewoiU2VydmVyIGRpZCBub3Qgc3RhcnQgc3VjY2Vzc2Z1bGx5LiBGdWxsIHNlcnZlciBsb2cgYXQgJGxvZyA+Pj4iCmNhdCAkbG9nCiI8PDwgRW5kIG9mIHNlcnZlciBsb2ciCnEgMzYKfQp9CnNsZWVwIC1NaWxsaXNlY29uZHMgMjAwCn0KaWYgKCEkcG9ydCkgewoiU2VydmVyIGRpZCBub3Qgc3RhcnQgc3VjY2Vzc2Z1bGx5LiBGdWxsIHNlcnZlciBsb2cgYXQgJGxvZyA+Pj4iCmNhdCAkbG9nCiI8PDwgRW5kIG9mIHNlcnZlciBsb2ciCnEgMzIKfQp9IGNhdGNoIHsKIlNlcn
[12:42:58.197] > ZlciBmYWlsZWQgdG8gc3RhcnQuIC0gJCgkXy5Ub1N0cmluZygpKSIKfSBmaW5hbGx5IHsKJGZpbGUuQ2xvc2UoKQp9CnRyeSB7CiRhaD0oZ2NpbSBXaW4zMl9PcGVyYXRpbmdTeXN0ZW0pLlZlcnNpb24KfSBjYXRjaCB7CiJGYWlsZWQgdG8gZmluZCBXaW5kb3dzIHZlcnNpb24gLSAkKCRfLlRvU3RyaW5nKCkpIgokYWg9InVua25vd24iCn0KIiR7dXVpZH06IHN0YXJ0Igoic3NoQXV0aFNvY2s9PSRlbnY6U1NIX0FVVEhfU09DSz09IgpkZXRhaWxzCiIke3V1aWR9OiBlbmQiCiJJbnN0YWxsIHNjcmlwdCBpcyAkcGlkLCB3YXRjaGluZyBzc2hkIHBhcmVudCAkc3NoZFBJRCIKd2hpbGUgKCRUcnVlKSB7CmIKc2xlZXAgMzAKfQo=')))); powershell -ExecutionPolicy Unrestricted -NoLogo -NoProfile -NonInteractive -EncodedCommand `$remoteSSHConfigurationScript"
[12:42:58.906] > b67455340ffa: running
[12:42:58.917] > 
[12:42:59.724] > Acquiring lock on D:\Users\user\.vscode-server\bin\cd9ea6488829f560dc949a8b2fb789f3cdc05f5d\vscode-remote-lock.cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
[12:42:59.735] > 
[12:42:59.736] > Looking for existing server in D:\Users\user\.vscode-server\bin\cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
> Downloading server
> b67455340ffa%%1%%
[12:43:17.804] > Expanding server into d:\Users\user\AppData\Local\Temp\005zaems.oog
[12:43:17.815] > 
> b67455340ffa%%2%%
[12:43:17.817] > 
[12:43:35.881] > Starting server: & 'D:\Users\user\.vscode-server\bin\cd9ea6488829f560dc949a8b2fb789f3cdc05f5d\server.cmd' --host=127.0.0.1 --enable-remote-auto-shutdown --port=0  *> 'D:\Users\user\.vscode-server\.cd9ea6488829f560dc949a8b2fb789f3cdc05f5d.log'
[12:43:36.900] > Server failed to start. - Falha na invoca��o do m�todo porque [System.String] n�o cont�m um m�todo denominado 'AddSeconds'.
[12:43:36.902] > b67455340ffa: start
> sshAuthSock====
> listeningOn====
> osReleaseId==windows==
> osVersion==10.0.18363==
> arch==x64==
> platform==windows==
> s==success==
> didLocalDownload==False==
> downloadTime==18104==
[12:43:36.923] > installTime==18034==
> extInstallTime====
> serverStartTime==279==
> b67455340ffa: end
> Install script is 13064, watching sshd parent 5984
[12:43:36.924] Received install output: 
sshAuthSock====
listeningOn====
osReleaseId==windows==
osVersion==10.0.18363==
arch==x64==
platform==windows==
s==success==
didLocalDownload==False==
downloadTime==18104==installTime==18034==
extInstallTime====
serverStartTime==279==

[12:43:36.926] Failed to parse remote port from server output
[12:43:36.927] Terminating local server
[12:43:36.943] Resolver error: Error: 
	at Function.Create (/home/local_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.61.0/out/extension.js:1:82322)
	at Object.t.handleInstallOutput (/home/local_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.61.0/out/extension.js:1:78935)
	at Object.t.tryInstallWithLocalServer (/home/local_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.61.0/out/extension.js:127:102434)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async /home/local_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.61.0/out/extension.js:127:104499
	at async Object.t.withShowDetailsEvent (/home/local_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.61.0/out/extension.js:127:110308)
	at async /home/local_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.61.0/out/extension.js:127:100987
	at async S (/home/local_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.61.0/out/extension.js:127:97777)
	at async Object.t.resolveWithLocalServer (/home/local_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.61.0/out/extension.js:127:100636)
	at async Object.t.resolve (/home/local_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.61.0/out/extension.js:127:108250)
	at async /home/local_user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.61.0/out/extension.js:127:129627
[12:43:36.947] Local server exit: 15
[12:43:36.951] ------

**Comment by lucasmgcic** [comment]
Sorry, it is a duplicate of issue https://github.com/microsoft/vscode-remote-release/issues/4140. So, I'll close the issue. After updating my VSCode, I was able to use vs code on Windows 10 remote.
