### ISSUE TITLE
Unable to open new session with remote (SSH) connection

### ISSUE THREAD

**Issue by seokbeomKim** [microsoft/vscode-remote-release#5346]
- VSCode Version: 1.58.2
- Local OS Version: Windows 10 Pro 20H2
- Remote OS Version: Fedora
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. Remote SSH: Connect to Host ->
2. Select target host & fail to connect

In the console output there are few information about this problem:
```
[11:10:29.782] Log Level: 2
[11:10:29.795] remote-ssh@0.65.7
[11:10:29.795] win32 x64
[11:10:29.796] SSH Resolver called for "ssh-remote+dev_server", attempt 1
[11:10:29.797] "remote.SSH.useLocalServer": false
[11:10:29.797] "remote.SSH.showLoginTerminal": false
[11:10:29.797] "remote.SSH.remotePlatform": {"dev_server":"linux"}
[11:10:29.798] "remote.SSH.path": undefined
[11:10:29.798] "remote.SSH.configFile": undefined
[11:10:29.798] "remote.SSH.useFlock": true
[11:10:29.798] "remote.SSH.lockfilesInTmp": true
[11:10:29.798] "remote.SSH.localServerDownload": auto
[11:10:29.798] "remote.SSH.remoteServerListenOnSocket": false
[11:10:29.798] "remote.SSH.showLoginTerminal": false
[11:10:29.799] "remote.SSH.defaultExtensions": []
[11:10:29.799] "remote.SSH.loglevel": 2
[11:10:29.799] SSH Resolver called for host: dev_server
[11:10:29.799] Setting up SSH remote "dev_server"
[11:10:29.851] Using commit id "c3f126316369cd610563c75b1b1725e0679adfb3" and quality "stable" for server
[11:10:29.858] Install and start server if needed
[11:10:29.866] Checking ssh with "ssh -V"
[11:10:30.017] > OpenSSH_for_Windows_8.
[11:10:30.017] > 1p1, LibreSSL 3.0.2

[11:10:30.023] Running script with connection command: ssh -T -D 51523 "dev_server" bash
[11:10:30.026] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[11:10:30.409] "install" terminal command done
[11:10:30.409] Install terminal quit with output: 
[11:10:30.410] Resolver error: Error: Got bad result from install script
	at Function.Create (c:\Users\B190253\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64659)
	at Object.t.tryInstall (c:\Users\B190253\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:414900)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\B190253\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:294918
	at async Object.t.withShowDetailsEvent (c:\Users\B190253\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:406463)
	at async Object.t.resolve (c:\Users\B190253\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:295994)
	at async c:\Users\B190253\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:127:110656
[11:10:30.414] ------
```

But in developer tools, more information about pr.resolveAuthority is logged like below: 
```
workbench.desktop.main.js:62 [Extension Host] (node:24532) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code --trace-deprecation ...` to show where the warning was created)
m @ workbench.desktop.main.js:62
workbench.desktop.main.js:745 The terminal process failed to launch: A native exception occurred during launch (Cannot create process, error code: 5).
onDidChangeNotification @ workbench.desktop.main.js:745
workbench.desktop.main.js:2850 Error: Got bad result from install script
    at pr.resolveAuthority (workbench.desktop.main.js:1736)
    at processTicksAndRejections (internal/process/task_queues.js:93)
    at async Za._scanAndHandleExtensions (workbench.desktop.main.js:2850)
    at async Za._initialize (workbench.desktop.main.js:2844)
workbench.desktop.main.js:2850 Error handled: Not showing a notification for the error
workbench.desktop.main.js:1736 Error received from starting extension host (kind: 2)
(anonymous) @ workbench.desktop.main.js:1736
workbench.desktop.main.js:1736 Error: Got bad result from install script
    at pr.resolveAuthority (workbench.desktop.main.js:1736)
    at processTicksAndRejections (internal/process/task_queues.js:93)
    at async Za._scanAndHandleExtensions (workbench.desktop.main.js:2850)
    at async Za._initialize (workbench.desktop.main.js:2844)
(anonymous) @ workbench.desktop.main.js:1736
workbench.desktop.main.js:627   ERR [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
2workbench.desktop.main.js:627   ERR Error: Got bad result from install script
    at pr.resolveAuthority (workbench.desktop.main.js:1736)
    at processTicksAndRejections (internal/process/task_queues.js:93)
    at async Za._scanAndHandleExtensions (workbench.desktop.main.js:2850)
    at async Za._initialize (workbench.desktop.main.js:2844)
workbench.desktop.main.js:2844 [budparr.language-hugo-vscode]: Unknown language in `contributes.language-hugo-vscode.language`. Provided value: toml
_logMessageInConsole @ workbench.desktop.main.js:2844
workbench.desktop.main.js:627   ERR Got bad result from install script: Error: Got bad result from install script
    at pr.resolveAuthority (vscode-file://vscode-app/c:/Users/B190253/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1736:8048)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Za._scanAndHandleExtensions (vscode-file://vscode-app/c:/Users/B190253/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2850:6930)
    at async Za._initialize (vscode-file://vscode-app/c:/Users/B190253/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2844:133909)
workbench.desktop.main.js:627   ERR Error: Got bad result from install script
    at pr.resolveAuthority (workbench.desktop.main.js:1736)
    at processTicksAndRejections (internal/process/task_queues.js:93)
    at async Za._scanAndHandleExtensions (workbench.desktop.main.js:2850)
    at async Za._initialize (workbench.desktop.main.js:2844)
```

I've checked that remote server has no problem since other devices can access to the target host except for few devices.. I can't find the reason of this issue, so I report the problem with logs above.

**Comment by bamurtaugh** [comment]
Does the command **Remote-SSH: Kill VS Code Server on Host** help at all? Do any of the other [troubleshooting steps ](https://code.visualstudio.com/docs/remote/troubleshooting#_troubleshooting-hanging-or-failing-connections)seem helpful?

**Comment by seokbeomKim** [comment]
1. Unfortunately, killing VS code server on host does not work. 
```
workbench.desktop.main.js:62 [Extension Host] (node:8448) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code --trace-deprecation ...` to show where the warning was created)
m @ workbench.desktop.main.js:62
workbench.desktop.main.js:745 The terminal process failed to launch: A native exception occurred during launch (Cannot create process, error code: 5).
onDidChangeNotification @ workbench.desktop.main.js:745
```

2. I tried all of them, but nothing was helpful. Accessing to the remote host is okay from other tools, like tramp of emacs, putty, ssh tools, except for vscode's remote plugin. Is there any methods to get 'more details' about the plugin? "Bad results" is too ambiguous to know what is going on.

**Comment by bamurtaugh** [comment]
cc @roblourens I saw some related issues for "Resolver error: Error: Got bad result from install script" but not a clear next step from them https://github.com/microsoft/vscode-remote-release/issues/3004 https://github.com/microsoft/vscode-remote-release/issues/5049 https://github.com/microsoft/vscode-remote-release/issues/4004

**Comment by roblourens** [comment]
Does setting `"remote.SSH.useLocalServer": true` work as a workaround?

**Comment by seokbeomKim** [comment]
> 
> 
> The log is weird, it's like the terminal is failing to launch or something. Does setting `"remote.SSH.useLocalServer": true` work as a workaround?

No, it doesn't work, either. 

```
[13:44:21.862] Running script with connection command: ssh -T -D 55533 "dev_server" bash
[13:44:21.865] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[13:44:22.589] "install" terminal command done
[13:44:22.590] Install terminal quit with output: 
[13:44:22.590] Resolver error: Error: Got bad result from install script
	at Function.Create (c:\Users\B190253\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64659)
	at Object.t.tryInstall (c:\Users\B190253\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:414900)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\B190253\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:294918
	at async Object.t.withShowDetailsEvent (c:\Users\B190253\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:406463)
	at async Object.t.resolve (c:\Users\B190253\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:295994)
	at async c:\Users\B190253\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:127:110656
[13:44:22.594] ------
```

**Comment by roblourens** [comment]
Have you installed powershell from the microsoft store?

https://github.com/microsoft/vscode/issues/115581

Possible that there is some other issue with limited permissions on your machine?

**Comment by seokbeomKim** [comment]
> 
> 
> Have you installed powershell from the microsoft store?
> 
> [microsoft/vscode#115581](https://github.com/microsoft/vscode/issues/115581)
> 
> Possible that there is some other issue with limited permissions on your machine?

No, I haven't installed ps from the store.
Still, I don't understand why the terminal is failing to launch but I'm suspicious that antivirus in working environment is preventing process creation. 
I will check whether the antivirus affects on this issue.

**Comment by seokbeomKim** [comment]
I've checked that antivirus is not related. 

After update the vscode, the ssh remote is working in one of devices (which was not working previously).
![image](https://user-images.githubusercontent.com/3895316/128655678-ee940827-a3be-4cf7-b803-b6fc1b85366d.png)

```
03334c15feab: running
Acquiring lock on /run/user/1000006450/vscode-remote-lock.B190253.379476f0e13988d90fab105c5c19e7abc8b1dea8
Installing to /home/B190253/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8...
03334c15feab%%1%%
Downloading with wget
Download complete
03334c15feab%%2%%
tar --version:
tar (GNU tar) 1.26
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
Checking /home/B190253/.vscode-server/.379476f0e13988d90fab105c5c19e7abc8b1dea8.log and /home/B190253/.vscode-server/.379476f0e13988d90fab105c5c19e7abc8b1dea8.pid for a running server
Looking for server with pid: 13538
Starting server with command... /home/B190253/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/server.sh --start-server --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0  &> "/home/B190253/.vscode-server/.379476f0e13988d90fab105c5c19e7abc8b1dea8.log" < /dev/null
printenv:
    XDG_SESSION_ID=9522
    OSH=/home/B190253/.oh-my-bash
    GTAGSCONF=/home/B190253/.gtags.conf
    SHELL=/bin/bash
    SSH_CLIENT=192.168.3.249 55115 22
    USER=B190253
    VSCODE_AGENT_FOLDER=/home/B190253/.vscode-server
    PATH=/home/B190253/opt/bin:/home/B190253/bin:/usr/local/bin:/usr/bin
    MAIL=/var/mail/B190253
    PWD=/home/B190253
    HOME=/home/B190253
    SHLVL=2
    LOGNAME=B190253
    SSH_CONNECTION=192.168.3.249 55115 192.168.33.101 22
    XDG_RUNTIME_DIR=/run/user/1000006450
    _=/usr/bin/printenv
    OLDPWD=/home/B190253/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8
Spawned remote server: 13776
Waiting for server log...
Waiting for server log...
 
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
*

03334c15feab: start
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==56914==
osReleaseId==fedora==
arch==x86_64==
tmpDir==/run/user/1000006450==
platform==linux==
unpackResult==success==
didLocalDownload==0==
downloadTime==10019==
installTime==1189==
extInstallTime====
serverStartTime==78==
connectionToken==4a29a7d4-e90f-4e33-96ef-bb6ac99ed6e0==
03334c15feab: end

```

But another device that worked before is not working now with same error after update vscode.
There is no difference except for O/S version.
![image](https://user-images.githubusercontent.com/3895316/128655795-64def08a-a88f-4f66-ba3c-d26a520b0ee1.png)

**Comment by seokbeomKim** [comment]
I've just updated the O/S from 19042 to 19043, it is not working again..
![image](https://user-images.githubusercontent.com/3895316/128660285-752f8db1-acb0-4758-a09a-ba612b095ebc.png)

**Comment by roblourens** [comment]
Do you have any terminal settings set? You might be able to work around it by setting something like

`"terminal.integrated.shell.windows": "C:\WINDOWS\System32\cmd.exe",`

**Comment by seokbeomKim** [comment]
> 
> 
> Do you have any terminal settings set? You might be able to work around it by setting something like
> 
> `"terminal.integrated.shell.windows": "C:\WINDOWS\System32\cmd.exe",`

It doesn't work even I set the configuration about terminal..

**Comment by roblourens** [comment]
@Tyriar any idea?

**Comment by seokbeomKim** [comment]
I will close the issue since this issue was related to company's groupware program.
I've noticed that opening a remote session got failed when the program is running even it is not antivirus though.

**Comment by Tyriar** [comment]
@seokbeomKim thanks for the clarification. I looked up error code 5 and it is indeed access denied so that makes sense.
