### ISSUE TITLE
Remote SSH can not connect remote host, when upgrade vsc from 1.57.1 to 1.58.2.

### ISSUE THREAD

**Issue by KylixC** [microsoft/vscode-remote-release#5360]
- VSCode Version:1.58.2
- Local OS Version:Windows 10 20H2
- Remote OS Version:Linux kernel 5.10.0, centos 8 update kernel, other host(openEuler release 21.03) same error
- Remote Extension/Connection Type: SSH
- Logs:
[11:00:07.141] Log Level: 1
[11:00:07.146] remote-ssh@0.65.7
[11:00:07.147] win32 x64
[11:00:07.172] SSH Resolver called for "ssh-remote+192.168.1.100", attempt 1
[11:00:07.172] "remote.SSH.useLocalServer": false
[11:00:07.173] "remote.SSH.showLoginTerminal": false
[11:00:07.173] "remote.SSH.remotePlatform": {"10.8.105.27":"linux","192.168.1.100":"linux","10.8.245.40":"linux"}
[11:00:07.174] "remote.SSH.path": undefined
[11:00:07.174] "remote.SSH.configFile": undefined
[11:00:07.174] "remote.SSH.useFlock": false
[11:00:07.174] "remote.SSH.lockfilesInTmp": true
[11:00:07.174] "remote.SSH.localServerDownload": auto
[11:00:07.174] "remote.SSH.remoteServerListenOnSocket": false
[11:00:07.174] "remote.SSH.showLoginTerminal": false
[11:00:07.175] "remote.SSH.defaultExtensions": []
[11:00:07.175] "remote.SSH.loglevel": 1
[11:00:07.175] "remote.SSH.maxReconnectionAttempts": 3
[11:00:07.175] SSH Resolver called for host: 192.168.1.100
[11:00:07.175] Setting up SSH remote "192.168.1.100"
[11:00:07.182] Using commit id "c3f126316369cd610563c75b1b1725e0679adfb3" and quality "stable" for server
[11:00:07.185] Install and start server if needed
[11:00:07.189] Checking ssh with "ssh -V"
[11:00:07.238] > OpenSSH_for_Windows_8.1p1, 
[11:00:07.238] > LibreSSL 3.0.2

[11:00:07.242] Running script with connection command: ssh -T -D 61608 "192.168.1.100" bash
[11:00:07.244] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[11:00:07.579] "install" terminal received data: "[2J[m[H]0;C:\WINDOWS\System32\cmd.exe[?25h"
[11:00:07.579] Got some output, clearing connection timeout
[11:00:07.809] "install" terminal received data: "c7d95fa42f56: running"
[11:00:07.846] "install" terminal received data: "Acquiring lock on /run/user/0/vscode-remote-lock.root.c3f126316369cd610563c75b1b
1725e0679adfb3[K
\ln /run/user/0/vscode-remote-lock.root.c3f126316369cd610563c75b1b1725e0679adfb3
.target /run/user/0/vscode-remote-lock.root.c3f126316369cd610563c75b1b1725e0679a
dfb3[K
Installing to /root/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3.
..[K
c7d95fa42f56%%1%%[K"
[11:00:07.877] "install" terminal received data: "Downloading with wget"
[11:00:15.104] "install" terminal received data: "wget download failed[9X
failed: Connection timed out.
printenv:[20X
    SHELL=/bin/bash[54X
    PWD=/root/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3
    LOGNAME=root[57X
    XDG_SESSION_TYPE=tty[49X
    MOTD_SHOWN=pam[55X
    HOME=/root[59X
    LANG=en_US.UTF-8[53X
    VSCODE_AGENT_FOLDER=/root/.vscode-server[29X
    SSH_CONNECTION=192.168.1.1 61610 192.168.1.100 22[16X
    XDG_SESSION_CLASS=user[47X
    SELINUX_ROLE_REQUESTED=[46X
    USER=root[60X
    SELINUX_USE_CURRENT_RANGE=[43X
    SHLVL=0[62X
    XDG_SESSION_ID=124[51X
    XDG_RUNTIME_DIR=/run/user/0[42X
    SSH_CLIENT=192.168.1.1 61610 22[36X
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
    SELINUX_LEVEL_REQUESTED=
    DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/0/bus
    OLDPWD=/root
    _=/usr/bin/printenv
Trigger local server download
c7d95fa42f56:trigger_server_download
platform==linux==
vscodeArch==x64==
destFolder==/root/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3== 
c7d95fa42f56:trigger_server_download_end
Waiting for client to transfer server archive...
Waiting for /root/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/vs
code-scp-done.flag and vscode-server.tar.gz to exist"
[11:00:15.104] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/root/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3"}
[11:00:15.105] Downloading VS Code server locally...
[11:00:15.125] "install" terminal received data: "
[1C"
[11:00:16.973] Resolver error: Error: Running the contributed command: '_workbench.downloadResource' failed.
	at S._executeContributedCommand (d:\Program\VSC\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:120745)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\diabo3\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:139384
	at async Object.t.downloadAndCopyToHost (c:\Users\diabo3\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:139299)
	at async c:\Users\diabo3\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:414617
	at async Object.t.tryInstall (c:\Users\diabo3\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:414829)
	at async c:\Users\diabo3\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:294918
	at async Object.t.withShowDetailsEvent (c:\Users\diabo3\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:406463)
	at async Object.t.resolve (c:\Users\diabo3\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:295994)
	at async c:\Users\diabo3\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:127:110656
[11:00:16.976] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Unknown","exitCodeLabel":""},"measures":{"resolveAttempts":1,"timing.totalResolveTime":9800,"timing.preSshTime":71,"timing.establishSshTime":566,"timing.scriptTime":9728}}
[11:00:16.978] ------

Steps to Reproduce:

1.upgrade vsc from 1.57.1 to 1.58.2;
2.vsc can auto restart,so find this error; 
3.when uninstall vsc 1.58.2, install 1.57.1, it is ok.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by bamurtaugh** [comment]
Only the version of VS Code changed for this error to occur? What version of Remote-SSH do you use? And has this been repro-ing regularly?

**Comment by phil-harmoniq** [comment]
I am also experiencing this issue. VS Code version 1.58.2, extension version v0.65.7. I don't know what version it started to happen but this happens with every new setup. Existing installs still connect without issues.

At a quick glance of my logs, I notice there seems to be an issue with the scp path. First a commit id is given:

`[13:30:51.351] Using commit id "c3f126316369cd610563c75b1b1725e0679adfb3" and quality "stable" for server`

and then scp is called with the wrong path:

`[13:30:55.806] Got request to download on client for {"platform":"linux","arch":"arm64","destFolder":"/home/ubuntu/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679aadfb3"}`

Notice there is an extra `a` at the end. Here is the full log:

```
[13:30:51.329] Log Level: 2
[13:30:51.331] remote-ssh@0.65.7
[13:30:51.331] win32 x64
[13:30:51.332] SSH Resolver called for "ssh-remote+orion", attempt 1
[13:30:51.332] "remote.SSH.useLocalServer": false
[13:30:51.332] "remote.SSH.showLoginTerminal": false
[13:30:51.333] "remote.SSH.remotePlatform": {"192.168.1.20":"linux","RaspberryPi":"linux"}
[13:30:51.333] "remote.SSH.path": undefined
[13:30:51.333] "remote.SSH.configFile": undefined
[13:30:51.333] "remote.SSH.useFlock": true
[13:30:51.333] "remote.SSH.lockfilesInTmp": false
[13:30:51.333] "remote.SSH.localServerDownload": auto
[13:30:51.333] "remote.SSH.remoteServerListenOnSocket": false
[13:30:51.333] "remote.SSH.showLoginTerminal": false
[13:30:51.333] "remote.SSH.defaultExtensions": []
[13:30:51.333] "remote.SSH.loglevel": 2
[13:30:51.334] SSH Resolver called for host: orion
[13:30:51.334] Setting up SSH remote "orion"
[13:30:51.351] Using commit id "c3f126316369cd610563c75b1b1725e0679adfb3" and quality "stable" for server
[13:30:51.354] Install and start server if needed
[13:30:53.055] Checking ssh with "ssh -V"
[13:30:53.083] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[13:30:53.086] Running script with connection command: ssh -T -D 50844 orion bash
[13:30:53.088] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[13:30:53.320] > ]0;C:\WINDOWS\System32\cmd.exe
[13:30:53.320] Got some output, clearing connection timeout
[13:30:55.651] > 170fd369bd27: running
[13:30:55.735] > Acquiring lock on /home/ubuntu/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/vscode-remote-lock.ubuntu.c3f126316369cd610563c75b1b1725e0679adfb3
[13:30:55.768] > Installing to /home/ubuntu/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3...
[13:30:55.780] > 170fd369bd27%%1%%
[13:30:55.796] > Downloading with wget
[13:30:55.805] > wget download failed
> wget: unable to resolve host address ‘update.code.visualstudio.com’
> printenv:
>     SHELL=/bin/bash
>     PWD=/home/ubuntu/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3
>     LOGNAME=ubuntu
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/home/ubuntu
>     LANG=C.UTF-8
>     VSCODE_AGENT_FOLDER=/home/ubuntu/.vscode-server
>     SSH_CONNECTION=192.168.1.4 50846 192.168.1.20 22
>     XDG_SESSION_CLASS=user
>     USER=ubuntu
>     SHLVL=0
>     XDG_SESSION_ID=7
>     XDG_RUNTIME_DIR=/run/user/1000
>     SSH_CLIENT=192.168.1.4 50846 22
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
>     OLDPWD=/home/ubuntu
>     _=/usr/bin/printenv
> Trigger local server download
> 170fd369bd27:trigger_server_download
> platform==linux==
> vscodeArch==arm64==
> destFolder==/home/ubuntu/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679a
> adfb3==
> 170fd369bd27:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/ubuntu/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679a
> adfb3/vscode-scp-done.flag and vscode-server.tar.gz to exist
[13:30:55.806] Got request to download on client for {"platform":"linux","arch":"arm64","destFolder":"/home/ubuntu/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679aadfb3"}
[13:30:55.806] Downloading VS Code server locally...
[13:30:55.811] > 
> 
[13:30:58.566] Downloaded VS Code server to c:\Users\Phil\AppData\Local\Temp\fb38490d-5753-4d92-b606-f7bbf0250796
[13:30:58.579] Renamed VS Code server to c:\Users\Phil\AppData\Local\Temp\vscode_server_1627839058567\vscode-server.tar.gz
[13:30:58.583] Checking ssh with "ssh -V"
[13:30:58.615] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[13:30:58.617] Testing scp with "scp"
[13:30:58.647] scp exited with code: 1
[13:30:58.647] Got stderr from scp: usage: scp [-346BCpqrTv] [-c cipher] [-F ssh_config] [-i identity_file]
            [-J destination] [-l limit] [-o ssh_option] [-P port]
            [-S program] source ... target
[13:30:58.647] Copying file to remote with scp "vscode-server.tar.gz" "vscode-scp-done.flag" orion:"/home/ubuntu/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679aadfb3"
[13:30:58.647] Using cwd: file:///c%3A/Users/Phil/AppData/Local/Temp/vscode_server_1627839058567
[13:30:58.647] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[13:30:58.827] > ]0;C:\WINDOWS\System32\cmd.exe
[13:31:00.355] > scp: /home/ubuntu/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679aadfb3: No such file or directory
[13:31:01.639] "Copy server to host" terminal command done
```

**Comment by KylixC** [comment]
Thanks for your attention.
>>Only the version of VS Code changed for this error to occur?
Yes, when upgrade vsc from 1.57.1 to 1.58.2, this error reappears.

>>What version of Remote-SSH do you use?
Version is 0.65.7.

>>And has this been repro-ing regularly?
Yes. If upgrade to 1.58.2, can not work. 
so uninstall vsc 1.58.2, reinstall vsc 1.57.1 it's ok.

**Comment by bamurtaugh** [comment]
cc @roblourens Based on `Running the contributed command: '_workbench.downloadResource' failed`, does this sound like https://github.com/microsoft/vscode-remote-release/issues/4743 / https://github.com/microsoft/vscode/issues/128492?

**Comment by roblourens** [comment]
Could you start VS Code with --log-net-log=netlog.json, retry to connect to the SSH remote and then post the created netlog.json here?

**Comment by KylixC** [comment]
Today, I try again, upgrade vsc from 1.57.1 to 1.60.2, can work.
Yes, it's ok, now.

Thanks!

**Comment by KylixC** [comment]
If you find same error's, please upgrade vsc to 1.60.2.
