### ISSUE TITLE
CLI Installation throws an Error

### ISSUE THREAD

**Issue by jcralbino** [microsoft/vscode-remote-release#5366]
- VSCode Version: 1.58.2
- Local OS Version:  Win Server 2016 , v1607 , OS BUlid 14393.4402
- Remote OS Version:
- Remote Extension/Connection Type: SSH/Docker/WSL
- Logs:
```
PS E:\SW\VisualStudioCode\VSExtension> code --install-extension .\ms-vscode-remote.remote-ssh-0.56.0.vsix
Installing extensions...
(node:15228) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
Extension 'ms-vscode-remote.remote-ssh-0.56.0.vsix' was successfully installed.
(node:15228) UnhandledPromiseRejectionWarning: Canceled: Canceled
    at Object.O [as canceled] (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:5:1157)
    at T.cancel (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:9:62864)
    at T.dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:9:63004)
    at k.dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:9:63266)
    at W (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3428)
    at d.clear (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3888)
    at dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3867)
    at dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:4402)
    at dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:11:7229)
    at W (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3428)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3634
    at Object.dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3706)
    at Object.W [as dispose] (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3567)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:14:41195
    at Map.forEach (<anonymous>)
    at Ne.dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:14:41182)
    at W (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3428)
    at d.clear (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3888)
    at dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3867)
    at a.dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:4402)
    at Object.g [as main] (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:17:51594)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async k (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:12:13756)
(node:15228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandl
ed promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
PS E:\SW\VisualStudioCode\VSExtension>  code --v
1.58.2

PS E:\SW\VisualStudioCode\VSExtension> code --install-extension .\ms-vscode-remote.remote-ssh-0.65.7.vsix
Installing extensions...
(node:19384) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
Extension 'ms-vscode-remote.remote-ssh-0.65.7.vsix' was successfully installed.
(node:19384) UnhandledPromiseRejectionWarning: Canceled: Canceled
    at Object.O [as canceled] (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:5:1157)
    at T.cancel (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:9:62864)
    at T.dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:9:63004)
    at k.dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:9:63266)
    at W (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3428)
    at d.clear (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3888)
    at dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3867)
    at dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:4402)
    at dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:11:7229)
    at W (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3428)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3634
    at Object.dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3706)
    at Object.W [as dispose] (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3567)
    at C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:14:41195
    at Map.forEach (<anonymous>)
    at Ne.dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:14:41182)
    at W (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3428)
    at d.clear (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3888)
    at dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:3867)
    at a.dispose (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:6:4402)
    at Object.g [as main] (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:17:51594)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async k (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cli.js:12:13756)
(node:19384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandl
ed promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
PS E:\SW\VisualStudioCode\VSExtension>

```
Steps to Reproduce:

1. Install the VSCode
2. Install an extension via CLI

Does this issue occur when you try this locally?: Yes

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/128854
