### ISSUE TITLE
Remote SSH - The VS Code Server failed to start

### ISSUE THREAD

**Issue by goshdarnharris** [microsoft/vscode-remote-release#5371]
- VSCode Version: 1.58.2, 1.59.0-insider
- Local OS Version: windows 10 19042.1110
- Remote OS Version: arch linux, virtualbox
- Remote Extension/Connection Type: SSH
- Logs:
```[18:31:42.032] Log Level: 2
[18:31:42.034] remote-ssh@0.65.7
[18:31:42.035] win32 x64
[18:31:42.072] SSH Resolver called for "ssh-remote+192.168.56.101", attempt 1
[18:31:42.073] "remote.SSH.useLocalServer": false
[18:31:42.073] "remote.SSH.showLoginTerminal": false
[18:31:42.073] "remote.SSH.remotePlatform": {"192.168.56.101":"linux"}
[18:31:42.073] "remote.SSH.path": undefined
[18:31:42.073] "remote.SSH.configFile": undefined
[18:31:42.073] "remote.SSH.useFlock": true
[18:31:42.074] "remote.SSH.lockfilesInTmp": false
[18:31:42.074] "remote.SSH.localServerDownload": auto
[18:31:42.074] "remote.SSH.remoteServerListenOnSocket": false
[18:31:42.074] "remote.SSH.showLoginTerminal": false
[18:31:42.074] "remote.SSH.defaultExtensions": []
[18:31:42.074] "remote.SSH.loglevel": 2
[18:31:42.075] SSH Resolver called for host: 192.168.56.101
[18:31:42.075] Setting up SSH remote "192.168.56.101"
[18:31:42.080] Using commit id "c3f126316369cd610563c75b1b1725e0679adfb3" and quality "stable" for server
[18:31:42.083] Install and start server if needed
[18:31:42.086] Checking ssh with "ssh -V"
[18:31:42.147] > OpenSSH_for_W
[18:31:42.147] > indows_8.1p1, LibreSSL 3.0.2

[18:31:42.151] Running script with connection command: ssh -T -D 50184 "192.168.56.101" bash
[18:31:42.153] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[18:31:42.432] > ]0;C:\WINDOWS\System32\cmd.exe
[18:31:42.432] Got some output, clearing connection timeout
[18:31:42.469] > gharris@192.168.56.101's password: 
[18:31:42.470] Showing password prompt
[18:31:44.076] Got password response
[18:31:44.077] "install" wrote data to terminal: "*********"
[18:31:44.096] > 
[18:31:44.176] > 6b643fc90c45: running
[18:31:44.235] > Acquiring lock on /home/gharris/.vscode-server/bin/c3f126316369cd610563c75b1b172
> 5e0679adfb3/vscode-remote-lock.gharris.c3f126316369cd610563c75b1b1725e0679adfb3 
[18:31:44.251] > Found existing installation at /home/gharris/.vscode-server/bin/c3f126316369cd61
> 0563c75b1b1725e0679adfb3...
> Checking /home/gharris/.vscode-server/.c3f126316369cd610563c75b1b1725e0679adfb3.
> log and /home/gharris/.vscode-server/.c3f126316369cd610563c75b1b1725e0679adfb3.p
> id for a running server
> Looking for server with pid: 296057
[18:31:44.261] > Starting server with command... /home/gharris/.vscode-server/bin/c3f126316369cd6
> 10563c75b1b1725e0679adfb3/server.sh --start-server --host=127.0.0.1 --enable-rem
> ote-auto-shutdown  --port=0  &> "/home/gharris/.vscode-server/.c3f126316369cd610
> 563c75b1b1725e0679adfb3.log" < /dev/null
> printenv:
>     SHELL=/bin/bash
>     PWD=/home/gharris
>     LOGNAME=gharris
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/home/gharris
>     VSCODE_AGENT_FOLDER=/home/gharris/.vscode-server   
>     SSH_CONNECTION=192.168.56.1 50186 192.168.56.101 22
>     XDG_SESSION_CLASS=user
>     USER=gharris
>     SHLVL=0
>     XDG_SESSION_ID=3
>     XDG_RUNTIME_DIR=/run/user/1000
>     SSH_CLIENT=192.168.56.1 50186 22
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/bin       
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
>     MAIL=/var/spool/mail/gharris
>     _=/usr/bin/printenv
> Spawned remote server: 1677
[18:31:44.269] > 
> Waiting for server log...
[18:31:44.303] > Waiting for server log...
[18:31:44.338] > Waiting for server log...
[18:31:44.371] > Waiting for server log...
[18:31:44.406] > Waiting for server log...
[18:31:44.438] > Waiting for server log...
[18:31:44.471] > Waiting for server log...
[18:31:44.505] > Waiting for server log...
[18:31:44.539] > Waiting for server log...
[18:31:44.574] > Waiting for server log...
[18:31:44.608] > Waiting for server log...
[18:31:44.643] > Waiting for server log...
[18:31:44.678] > Waiting for server log...
[18:31:44.711] > Waiting for server log...
[18:31:44.749] > Waiting for server log...
[18:31:44.783] > Waiting for server log...
[18:31:44.818] > Waiting for server log...
[18:31:44.854] > Waiting for server log...
[18:31:44.888] > Waiting for server log...
[18:31:44.925] > Waiting for server log...
[18:31:44.954] > Waiting for server log...
[18:31:44.989] > Waiting for server log...
[18:31:45.023] > Waiting for server log...
[18:31:45.058] > Waiting for server log...
[18:31:45.094] > Waiting for server log...
[18:31:45.127] > Waiting for server log...
[18:31:45.160] > Waiting for server log...
[18:31:45.195] > Waiting for server log...
[18:31:45.228] > Waiting for server log...
[18:31:45.759] > Waiting for server log...
[18:31:45.792] > Waiting for server log...
[18:31:45.827] > Waiting for server log...
[18:31:45.860] > Waiting for server log...
[18:31:45.894] > Waiting for server log...
[18:31:45.936] > Waiting for server log...
[18:31:45.961] > Waiting for server log...
[18:31:45.995] > Waiting for server log...
[18:31:46.028] > Waiting for server log...
[18:31:46.066] > Waiting for server log...
[18:31:46.101] > Waiting for server log...
[18:31:46.133] > Waiting for server log...
[18:31:46.166] > Waiting for server log...
[18:31:46.205] > Waiting for server log...
[18:31:46.234] > Waiting for server log...
[18:31:46.267] > Waiting for server log...
[18:31:46.301] > Waiting for server log...
[18:31:46.334] > Waiting for server log...
[18:31:46.370] > Waiting for server log...
[18:31:46.402] > Waiting for server log...
[18:31:46.440] > Waiting for server log...
[18:31:46.471] > Waiting for server log...
[18:31:46.503] > Waiting for server log...
[18:31:46.540] > Waiting for server log...
[18:31:46.574] > Waiting for server log...
[18:31:46.607] > Waiting for server log...
[18:31:46.644] > Waiting for server log...
[18:31:46.680] > Waiting for server log...
[18:31:46.718] > Waiting for server log...
[18:31:46.744] > Waiting for server log...
[18:31:46.789] > Waiting for server log...
[18:31:46.817] > Waiting for server log...
[18:31:46.845] > Waiting for server log...
[18:31:46.882] > Waiting for server log...
[18:31:46.915] > Waiting for server log...
[18:31:46.951] > Waiting for server log...
[18:31:46.986] > Waiting for server log...
[18:31:47.019] > Waiting for server log...
[18:31:47.053] > Waiting for server log...
[18:31:47.085] > Waiting for server log...
[18:31:47.121] > Waiting for server log...
[18:31:47.154] > Waiting for server log...
[18:31:47.188] > Waiting for server log...
[18:31:47.221] > Waiting for server log...
[18:31:47.255] > Waiting for server log...
[18:31:47.288] > Waiting for server log...
[18:31:47.323] > Waiting for server log...
[18:31:47.356] > Waiting for server log...
[18:31:47.389] > Waiting for server log...
[18:31:47.423] > Waiting for server log...
[18:31:47.457] > Waiting for server log...
[18:31:47.492] > Waiting for server log...
[18:31:47.527] > Waiting for server log...
[18:31:47.562] > Waiting for server log...
[18:31:47.596] > Waiting for server log...
[18:31:47.632] > Waiting for server log...
[18:31:47.666] > Waiting for server log...
[18:31:47.701] > Waiting for server log...
[18:31:47.732] > Waiting for server log...
[18:31:47.767] > Waiting for server log...
[18:31:47.801] > Waiting for server log...
[18:31:47.835] > Waiting for server log...
[18:31:47.870] > Waiting for server log...
[18:31:47.902] > Waiting for server log...
[18:31:47.963] > Waiting for server log...
[18:31:47.972] > Waiting for server log...
[18:31:48.004] > Waiting for server log...
[18:31:48.037] > Waiting for server log...
[18:31:48.071] > Waiting for server log...
[18:31:48.105] > Waiting for server log...
[18:31:48.140] > Waiting for server log...
[18:31:48.173] > Waiting for server log...
[18:31:48.209] > Waiting for server log...
[18:31:48.242] > Waiting for server log...
[18:31:48.275] > Waiting for server log...
[18:31:48.310] > Waiting for server log...
[18:31:48.344] > Waiting for server log...
[18:31:48.377] > Waiting for server log...
[18:31:48.412] > Waiting for server log...
[18:31:48.444] > Waiting for server log...
[18:31:48.478] > Waiting for server log...
[18:31:48.511] > Waiting for server log...
[18:31:48.544] > Waiting for server log...
[18:31:48.578] > Waiting for server log...
[18:31:48.612] > Waiting for server log...
[18:31:48.646] > Waiting for server log...
[18:31:48.682] > Waiting for server log...
[18:31:48.715] > Waiting for server log...
[18:31:48.750] > Waiting for server log...
[18:31:48.785] > Waiting for server log...
[18:31:48.819] > Waiting for server log...
[18:31:48.854] > Waiting for server log...
[18:31:48.886] > Waiting for server log...
[18:31:49.094] > Waiting for server log...
[18:31:49.113] > Waiting for server log...
[18:31:49.151] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[18:31:49.161] > 
[18:31:49.168] > Waiting for server log...
[18:31:49.203] > Waiting for server log...
[18:31:49.237] > Waiting for server log...
[18:31:49.270] > Waiting for server log...
[18:31:49.304] > Waiting for server log...
[18:31:49.340] > Waiting for server log...
[18:31:49.373] > Waiting for server log...
[18:31:49.406] > Waiting for server log...
[18:31:49.443] > Waiting for server log...
[18:31:49.473] > Waiting for server log...
[18:31:49.508] > Waiting for server log...
[18:31:49.542] > Waiting for server log...
[18:31:49.576] > Waiting for server log...
[18:31:49.609] > Waiting for server log...
[18:31:49.644] > Waiting for server log...
[18:31:49.677] > Waiting for server log...
[18:31:49.711] > Waiting for server log...
[18:31:49.748] > Waiting for server log...
[18:31:49.782] > Waiting for server log...
[18:31:49.817] > Waiting for server log...
[18:31:49.851] > Waiting for server log...
[18:31:49.886] > Waiting for server log...
[18:31:49.919] > Waiting for server log...
[18:31:49.959] > Waiting for server log...
[18:31:49.994] > Waiting for server log...
[18:31:50.028] > Waiting for server log...
[18:31:50.060] > Waiting for server log...
[18:31:50.092] > Waiting for server log...
[18:31:50.127] > Waiting for server log...
[18:31:50.162] > Waiting for server log...
[18:31:50.197] > Waiting for server log...
[18:31:50.233] > Waiting for server log...
[18:31:50.291] > Waiting for server log...
[18:31:50.308] > Waiting for server log...
[18:31:50.335] > Waiting for server log...
[18:31:50.369] > Waiting for server log...
[18:31:50.403] > Waiting for server log...
[18:31:50.442] > Waiting for server log...
[18:31:50.471] > Waiting for server log...
[18:31:50.505] > Waiting for server log...
[18:31:50.540] > Waiting for server log...
[18:31:50.574] > Waiting for server log...
[18:31:50.608] > Waiting for server log...
[18:31:50.642] > Waiting for server log...
[18:31:50.674] > Waiting for server log...
[18:31:50.708] > Waiting for server log...
[18:31:50.743] > Waiting for server log...
[18:31:50.776] > Waiting for server log...
[18:31:50.810] > Waiting for server log...
[18:31:50.843] > Waiting for server log...
[18:31:50.878] > Waiting for server log...
[18:31:50.911] > Waiting for server log...
[18:31:50.942] > Waiting for server log...
[18:31:50.977] > Waiting for server log...
[18:31:51.009] > Waiting for server log...
[18:31:51.044] > Waiting for server log...
[18:31:51.078] > Waiting for server log...
[18:31:51.111] > Waiting for server log...
[18:31:51.144] > Waiting for server log...
[18:31:51.178] > Waiting for server log...
[18:31:51.212] > Waiting for server log...
[18:31:51.249] > Waiting for server log...
[18:31:51.282] > Waiting for server log...
[18:31:51.316] > Waiting for server log...
[18:31:51.350] > Waiting for server log...
[18:31:51.403] > Waiting for server log...
[18:31:51.422] > Waiting for server log...
[18:31:51.952] > Waiting for server log...
[18:31:51.986] > Waiting for server log...
[18:31:52.023] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,  
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
> Server did not start successfully. Full server log at /home/gharris/.vscode-serv
> er/.c3f126316369cd610563c75b1b1725e0679adfb3.log >>>
> <<< End of server log
> 6b643fc90c45: start
> exitCode==32==
> listeningOn====
> osReleaseId==arch==
> arch==x86_64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==7756==
> 6b643fc90c45: end
[18:31:52.023] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==arch==
arch==x86_64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==7756==

[18:31:52.024] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (c:\Users\gharris\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64593)
	at c (c:\Users\gharris\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:58918)
	at Object.t.handleInstallOutput (c:\Users\gharris\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:63335)
	at Object.t.tryInstall (c:\Users\gharris\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:415135)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\gharris\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:294918
	at async Object.t.withShowDetailsEvent (c:\Users\gharris\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:406463)
	at async Object.t.resolve (c:\Users\gharris\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:295994)
	at async c:\Users\gharris\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:127:110656
[18:31:52.031] ------




[18:31:52.506] > 
[18:31:53.326] "install" terminal command done
[18:31:53.326] Install terminal quit with output:
```

Steps to Reproduce:
1. Attempt to open a remote workspace or connect to a remote host.

This appeared on previously functioning remote workspaces after updating to 1.58.2. I have also tested with insiders and a nightly build of this extension. I am able to ssh into the remote via powershell. I can see a few other issues having to do with this update and connecting with remote SSH, but I think what I'm seeing is a bit different in that it appears to be getting through installation before failing.

**Comment by astrowonk** [comment]
I am having this same problem. However, my previously working remote ssh target (an azure vm) setup continues to work, trying to set up remote vs code on a new vm is failing. I get the same eternal scanning for server log issue.

This has been open for 19 days without any response? This breaks using remote completely.
