### ISSUE TITLE
Remote SSH not working after the recent update. 

### ISSUE THREAD

**Issue by VIGNESHinZONE** [microsoft/vscode-remote-release#5381]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.58.2
- OS Version: Ubuntu 20.04
- Server: AWS EC2 instance

```
[23:13:13.855] askpass server listening on /run/user/1000/vscode-ssh-askpass-c4640e9241142c793b7dd57fd94c16f79294a09c.sock
[23:13:13.856] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-df5bf7a31613b1814e0c34e73d82922880aaacb4.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","45689","-o","ConnectTimeout=15","ec2-3-113-14-118.ap-northeast-1.compute.amazonaws.com"],"dataFilePath":"/home/vignesh/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-ec2-3-113-14-118.ap-northeast-1.compute.amazonaws.com-c3f126316369cd610563c75b1b1725e0679adfb3-0.65.7/data.json"}
[23:13:13.856] Local server env: {"DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/vignesh/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/vignesh/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-c4640e9241142c793b7dd57fd94c16f79294a09c.sock"}
[23:13:13.862] Spawned 27273
[23:13:13.977] > local-server-1> Spawned ssh, pid=27282
[23:13:13.980] stderr> OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020
[23:13:30.865] Terminating local server
[23:13:30.875] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/home/vignesh/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:64785)
	at Timeout._onTimeout (/home/vignesh/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:264709)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[23:13:30.887] Local server exit: 15
[23:13:30.903] ------

```

This error has started only since today. I'm able to connect via ssh on my command line but not on VS code.
I had installed the latest updates yesterday and I have also reinstalled VS code twice to verify.

Thanks in Advance

**Comment by VIGNESHinZONE** [comment]
Thanks for the immediate reply, 
I wasnt sure about the output of the `echo "echo hello" | ssh -i "~/Downloads/internship-otsuka.pem" -v -o ConnectTimeout=15 -T -D 45689 ubuntu@ec2-54-249-221-217.ap-northeast-1.compute.amazonaws.com` , but i think its working because it manages to log into `Deep Learning AMI (Ubuntu 18.04) Version 45.0`.

```
(base) vignesh@vignesh-Inspiron-7560:~$ echo "echo hello" | ssh -i "~/Downloads/internship-otsuka.pem" -v -o ConnectTimeout=15 -T -D 45689 ubuntu@ec2-54-249-221-217.ap-northeast-1.compute.amazonaws.com
OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /home/vignesh/.ssh/config
debug1: /home/vignesh/.ssh/config line 1: Applying options for ec2-54-249-221-217.ap-northeast-1.compute.amazonaws.com
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to ec2-54-249-221-217.ap-northeast-1.compute.amazonaws.com [54.249.221.217] port 22.
debug1: fd 3 clearing O_NONBLOCK
debug1: Connection established.
debug1: identity file /home/vignesh/Downloads/internship-otsuka.pem type -1
debug1: identity file /home/vignesh/Downloads/internship-otsuka.pem-cert type -1
debug1: identity file /home/vignesh/Downloads/internship-otsuka.pem type -1
debug1: identity file /home/vignesh/Downloads/internship-otsuka.pem-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.2
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
debug1: match: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3 pat OpenSSH_7.0*,OpenSSH_7.1*,OpenSSH_7.2*,OpenSSH_7.3*,OpenSSH_7.4*,OpenSSH_7.5*,OpenSSH_7.6*,OpenSSH_7.7* compat 0x04000002
debug1: Authenticating to ec2-54-249-221-217.ap-northeast-1.compute.amazonaws.com:22 as 'ubuntu'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:efJu94lGo5fJMCGVmimGqYCzRrM+Uvt86lEUcUP2oNc
debug1: Host 'ec2-54-249-221-217.ap-northeast-1.compute.amazonaws.com' is known and matches the ECDSA host key.
debug1: Found key in /home/vignesh/.ssh/known_hosts:3
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /home/vignesh/Downloads/internship-otsuka.pem  explicit
debug1: Will attempt key: /home/vignesh/Downloads/internship-otsuka.pem  explicit
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /home/vignesh/Downloads/internship-otsuka.pem
debug1: Authentication succeeded (publickey).
Authenticated to ec2-54-249-221-217.ap-northeast-1.compute.amazonaws.com ([54.249.221.217]:22).
debug1: Local connections to LOCALHOST:45689 forwarded to remote address socks:0
debug1: Local forwarding listening on ::1 port 45689.
debug1: channel 0: new [port listener]
debug1: Local forwarding listening on 127.0.0.1 port 45689.
debug1: channel 1: new [port listener]
debug1: channel 2: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Sending environment.
debug1: Sending env LANG = en_GB.UTF-8
=============================================================================
       __|  __|_  )
       _|  (     /   Deep Learning AMI (Ubuntu 18.04) Version 45.0
      ___|\___|___|
=============================================================================

Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1054-aws x86_64v)

Please use one of the following commands to start the required environment with the framework of your choice:
for AWS MX 1.7 (+Keras2) with Python3 (CUDA 10.1 and Intel MKL-DNN) _______________________________ source activate mxnet_p36
for AWS MX 1.8 (+Keras2) with Python3 (CUDA + and Intel MKL-DNN) ___________________________ source activate mxnet_latest_p37
for AWS MX(+AWS Neuron) with Python3 ___________________________________________________ source activate aws_neuron_mxnet_p36
for AWS MX(+Amazon Elastic Inference) with Python3 _______________________________________ source activate amazonei_mxnet_p36
for TensorFlow(+Keras2) with Python3 (CUDA + and Intel MKL-DNN) _____________________________ source activate tensorflow_p37
for Tensorflow(+AWS Neuron) with Python3 _________________________________________ source activate aws_neuron_tensorflow_p36
for TensorFlow 2(+Keras2) with Python3 (CUDA 10.1 and Intel MKL-DNN) _______________________ source activate tensorflow2_p36
for TensorFlow 2.3 with Python3.7 (CUDA + and Intel MKL-DNN) ________________________ source activate tensorflow2_latest_p37
for PyTorch 1.4 with Python3 (CUDA 10.1 and Intel MKL) _________________________________________ source activate pytorch_p36
for PyTorch 1.7.1 with Python3.7 (CUDA 11.1 and Intel MKL) ________________________________ source activate pytorch_latest_p37
for PyTorch (+AWS Neuron) with Python3 ______________________________________________ source activate aws_neuron_pytorch_p36
for base Python3 (CUDA 10.0) _______________________________________________________________________ source activate python3

To automatically activate base conda environment upon login, run: 'conda config --set auto_activate_base true'
Official Conda User Guide: https://docs.conda.io/projects/conda/en/latest/user-guide/
AWS Deep Learning AMI Homepage: https://aws.amazon.com/machine-learning/amis/
Developer Guide and Release Notes: https://docs.aws.amazon.com/dlami/latest/devguide/what-is-dlami.html
Support: https://forums.aws.amazon.com/forum.jspa?forumID=263
For a fully managed experience, check out Amazon SageMaker at https://aws.amazon.com/sagemaker
When using INF1 type instances, please update regularly using the instructions at: https://github.com/aws/aws-neuron-sdk/tree/master/release-notes
=============================================================================

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Tue Jul 27 08:55:54 UTC 2021


 * Super-optimized for small spaces - read how we shrank the memory
   footprint of MicroK8s to make it the smallest full K8s around.

   https://ubuntu.com/blog/microk8s-memory-optimisation

21 updates can be applied immediately.
To see these additional updates run: apt list --upgradable

New release '20.04.2 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


debug1: client_input_channel_req: channel 2 rtype exit-status reply 0
hello
debug1: channel 2: free: client-session, nchannels 3
debug1: channel 0: free: port listener, nchannels 2
debug1: channel 1: free: port listener, nchannels 1
debug1: fd 0 clearing O_NONBLOCK
Transferred: sent 2572, received 5548 bytes, in 1.5 seconds
Bytes per second: sent 1703.9, received 3675.3
debug1: Exit status 0
```

Im able to access the ssh from the command line but not through the ssh extension.
![Screenshot from 2021-07-27 14-20-15](https://user-images.githubusercontent.com/45672459/127133779-c1cce013-fbbd-4242-8dfd-f0441b082d97.jpg)

**Comment by VIGNESHinZONE** [comment]
Thanks, @roblourens, I got a solution and I will close the issue.

Problem: I recently got a new internet connection and it was taking longer to connect via ssh. VS Code has a timeout limit of 15 seconds and hence the above message. When I changed my internet connection, SSH started working.

Solution: https://stackoverflow.com/a/62423178/16338209
