### ISSUE TITLE
-D is used instead of user in Remote-SSH connection

### ISSUE THREAD

**Issue by Nathan-LG** [microsoft/vscode-remote-release#5393]
- VSCode Version: 1.58.2
- Local OS Version: Version 10.0.19043 Build 19043
- Remote OS Version: Debian GNU/Linux 8.5 (jessie)
- Remote Extension/Connection Type: SSH
- Logs:

(_USERNAME_ is my username, and _SERVER_ is the server address)

> [14:01:06.467] Log Level: 2
> [14:01:06.469] remote-ssh@0.65.7
> [14:01:06.469] win32 x64
> [14:01:06.470] SSH Resolver called for "ssh-remote+_USERNAME_@_SERVER_", attempt 1
> [14:01:06.471] "remote.SSH.useLocalServer": false
> [14:01:06.471] "remote.SSH.showLoginTerminal": false
> [14:01:06.471] "remote.SSH.remotePlatform": {"_SERVER_":"linux"}
> [14:01:06.471] "remote.SSH.path": undefined
> [14:01:06.471] "remote.SSH.configFile": undefined
> [14:01:06.471] "remote.SSH.useFlock": true
> [14:01:06.471] "remote.SSH.lockfilesInTmp": false
> [14:01:06.472] "remote.SSH.localServerDownload": auto
> [14:01:06.472] "remote.SSH.remoteServerListenOnSocket": false
> [14:01:06.472] "remote.SSH.showLoginTerminal": false
> [14:01:06.472] "remote.SSH.defaultExtensions": []
> [14:01:06.472] "remote.SSH.loglevel": 2
> [14:01:06.472] SSH Resolver called for host: _USERNAME_@_SERVER_
> [14:01:06.472] Setting up SSH remote "_SERVER_"
> [14:01:06.490] Using commit id "c3f126316369cd610563c75b1b1725e0679adfb3" and quality "stable" for server
> [14:01:06.493] Install and start server if needed
> [14:01:06.512] Checking ssh with "ssh -V"
> [14:01:06.550] > OpenSSH_for_Windows_8.1p1, 
> [14:01:06.550] > LibreSSL 3.0.2
> 
> [14:01:06.553] Running script with connection command: ssh -T -D 63303 "_USERNAME_@_SERVER_" bash
> [14:01:06.555] Terminal shell path: C:\Windows\System32\cmd.exe
> [14:01:06.760] > ]0;C:\Windows\System32\cmd.exe
> [14:01:06.760] Got some output, clearing connection timeout
> [14:01:06.773] > C:\Users\_USERNAME_>echo off 
> [14:01:06.939] > m
> [14:01:06.962] > esg: ttyname failed: Inappropriate ioctl for device
> [14:01:07.057] > -D@192.168.201.51's password: 
> [14:01:07.057] Showing password prompt
> [14:01:08.573] "install" terminal command done
> [14:01:08.573] Install terminal quit with output: **-D@192.168.201.51**'s password: 
> [14:01:08.574] Received install output: **-D@192.168.201.51**'s password: 
> [14:01:08.574] Failed to parse remote port from server output
> [14:01:08.574] Resolver error: Error: 
> 	at Function.Create (c:\Users\_USERNAME_\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64659)
> 	at Object.t.handleInstallOutput (c:\Users\_USERNAME_\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:63302)
> 	at Object.t.tryInstall (c:\Users\_USERNAME_\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:415135)
> 	at processTicksAndRejections (internal/process/task_queues.js:93:5)
> 	at async c:\Users\_USERNAME_\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:294918
> 	at async Object.t.withShowDetailsEvent (c:\Users\_USERNAME_\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:406463)
> 	at async Object.t.resolve (c:\Users\_USERNAME_\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:295994)
> 	at async c:\Users\_USERNAME_\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:127:110656
> [14:01:08.577] ------
> 
> 
> 
> 
> [14:01:11.001] Password dialog canceled
> [14:01:11.001] "install" terminal command canceled
> [14:01:11.001] > -D@192.168.201.51's password: A
> > ccess denied
> [14:01:11.002] Showing password prompt

As you can see in the logs, it tries to connect with "Install terminal quit with output: **-D@192.168.201.51**'s password: " instead of using _USERNAME_@192.168.201.51.

My config file :

> Host _USERNAME_@_SERVER_
>   HostName _SERVER_
>   User _USERNAME_
>   IdentityFile "C:\Users\_USERNAME_\.ssh\id_rsa"

Also for an unknown reason, VSCode keeps asking me for a password when I try to connect while I've provided it with an SSH key.

Steps to Reproduce:

1. Add Host
2. Try to connect to Host

**Comment by Nathan-LG** [comment]
When disabling Conpty, the logs are a bit better, you can see that VSCode got an "Access denied" (which is quite logical, since it is still using -D@192.168.201.51).

> [14:18:44.406] Log Level: 2
> [14:18:44.408] remote-ssh@0.65.7
> [14:18:44.408] win32 x64
> [14:18:44.410] SSH Resolver called for "ssh-remote+n.legranvallet@rd.axode", attempt 1
> [14:18:44.410] "remote.SSH.useLocalServer": false
> [14:18:44.410] "remote.SSH.showLoginTerminal": false
> [14:18:44.410] "remote.SSH.remotePlatform": {"rd.axode":"linux"}
> [14:18:44.411] "remote.SSH.path": undefined
> [14:18:44.411] "remote.SSH.configFile": undefined
> [14:18:44.411] "remote.SSH.useFlock": true
> [14:18:44.411] "remote.SSH.lockfilesInTmp": false
> [14:18:44.411] "remote.SSH.localServerDownload": auto
> [14:18:44.411] "remote.SSH.remoteServerListenOnSocket": false
> [14:18:44.411] "remote.SSH.showLoginTerminal": false
> [14:18:44.411] "remote.SSH.defaultExtensions": []
> [14:18:44.411] "remote.SSH.loglevel": 2
> [14:18:44.411] SSH Resolver called for host: n.legranvallet@rd.axode
> [14:18:44.412] Setting up SSH remote "rd.axode"
> [14:18:44.429] Using commit id "c3f126316369cd610563c75b1b1725e0679adfb3" and quality "stable" for server
> [14:18:44.432] Install and start server if needed
> [14:18:44.451] Checking ssh with "ssh -V"
> [14:18:44.486] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
> 
> [14:18:44.489] Running script with connection command: ssh -T -D 64876 "n.legranvallet@rd.axode" bash
> [14:18:44.491] Terminal shell path: C:\Windows\System32\cmd.exe
> [14:18:44.773] > 
> > C:\Users\n.legranvallet>echo off
> > 
> [14:18:44.774] Got some output, clearing connection timeout
> [14:18:44.938] > mesg: ttyname failed: Inappropriate ioctl for device
> > 
> [14:18:45.063] > -D@192.168.201.51's password:
> > Access denied
> > 
> [14:18:45.063] Showing password prompt
> [14:18:45.659] "install" terminal command done
> [14:18:45.660] Install terminal quit with output: Access denied
> [14:18:45.660] Received install output: Access denied
> [14:18:45.660] Failed to parse remote port from server output
> [14:18:45.661] Resolver error: Error: 
> 	at Function.Create (c:\Users\n.legranvallet\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64659)
> 	at Object.t.handleInstallOutput (c:\Users\n.legranvallet\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:63302)
> 	at Object.t.tryInstall (c:\Users\n.legranvallet\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:415135)
> 	at processTicksAndRejections (internal/process/task_queues.js:93:5)
> 	at async c:\Users\n.legranvallet\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:294918
> 	at async Object.t.withShowDetailsEvent (c:\Users\n.legranvallet\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:406463)
> 	at async Object.t.resolve (c:\Users\n.legranvallet\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:295994)
> 	at async c:\Users\n.legranvallet\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:127:110656
> [14:18:45.664] ------
> 
> 
> 
> 
> [14:18:46.848] Password dialog canceled
> [14:18:46.849] "install" terminal command canceled
> [14:18:46.850] > mesg: ttyname failed: Inappropriate ioctl for device

**Comment by Nathan-LG** [comment]
So... it turns out that you cannot have a file named ssh.bat or ssh.exe in your home directory, otherwise VSCode will execute it instead of the classic OpenSSH program.
