### ISSUE TITLE
Open container fails with "Docker version 17.12.0 or later is required"

### ISSUE THREAD

**Issue by taiya** [microsoft/vscode-remote-release#5396]
1) install Remote - Containers extension 
2) CMD+P: open folder in container
3) vscode complains (see snapshot)
4) going through with "install" (despite the fact I already have Docker)
5) vscode installs Version 3.5.2 (3.5.2.18)
6) back to (2)
7) rinse and repeat..

TL;DR: even allowing vscode to install the "desired" version of docker is not successful

![Screen Shot 2021-07-28 at 4 11 37 PM](https://user-images.githubusercontent.com/4480573/127408052-8a46fc52-4c61-4d1e-8863-87bd841b607b.png)
Issue Type: <b>Bug</b>

Extension version: 0.187.1
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:09:06.581Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

**Comment by tanhakabir** [comment]
+ 1 I have Docker version 20.10.7, build f0df350 installed but I also get this error

**Comment by taiya** [comment]
By the way, found this (closed?!) related bug:
https://github.com/microsoft/vscode-remote-release/issues/5074

Was able to move forward by following these instructions (but restarted OS vs. sshd):
https://github.com/microsoft/vscode-remote-release/issues/5074#issuecomment-864342093

Still odd the previous bug was marked as closed as this is still an evident problem :)

**Comment by junekhan** [comment]
I'm having the same issue, downgrading doesn't help.

**Comment by tonylea** [comment]
I'm having the same issue too. 

- Big Sur 11.4
- Remote containers extension v0.187.1
- Docker version 20.10.7, build f0df350

**Comment by ikappas** [comment]
I'm having the same issue too.

- Windows 10
- Remote Containers extension v0.187.1
- Docker version 20.10.7

**Comment by mitochon** [comment]
I had this issue earlier this week but it seems to be resolved after updating to latest VSCode release:

VSCode:
Version: 1.59.0 (Universal)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:14:40.191Z (1 day ago)
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 19.6.0

remote containers:
v0.191.0

**Comment by taiya** [comment]
Confirm on 1.59.0 I am not seeing the problem.

**Comment by pedeveaux** [comment]
I have this same issue on 1.59.0. 

Version: 1.59.0
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:14:40.191Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 18.7.0

I was able to build containers just a few days ago and now I cannot.

**Comment by pedeveaux** [comment]
Downgrading vs code to 1.58.2 and re-installing the remote containers extension resolved the issue for me.

**Comment by ikappas** [comment]
I am still experiencing this issue on 1.59.0 running on Windows 10:

Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by ikappas** [comment]
Downgrading does not help. Please reopen the issue

**Comment by chrmarti** [comment]
When you see this, could you click Cancel and then check the dev container log (`F1` > `Remote-Containers: Show Container Log`) and the dev console (`Help` > `Toggle Developer Tools`) and post these here?

**Comment by ikappas** [comment]
The javascript console output is:
```
workbench.desktop.main.js:62 [Extension Host] Error: spawn /usr/local/bin/docker ENOENT	at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)	at onErrorNT (internal/child_process.js:465:16)	at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by Andrew-Tuen** [comment]
I have the same issue on MacOS BigSur 11.5.2. And I fixed it buy trying to completely uninstall the docker on laptop and re-install it.

**Comment by chrmarti** [comment]
@ikappas Do you have the Docker Path in the user settings set to that path? Is the executable still at that location?

**Comment by ikappas** [comment]
@chrmarti Thank you for identifying the issue!! For some reason I had "remote.containers.dockerPath": "/usr/local/bin/docker" in my vscode configuration which seems to be the culprit. As soon as I removed the setting the devcontainer lauched properly.

**Comment by ikappas** [comment]
@chrmarti Please note that I dual boot between macOS and Windows and I have settings synchronization enabled. Could this be related to a macOS setting being synced to Windows?

**Comment by chrmarti** [comment]
@sandy081 How can I turn off settings sync for an application setting by default (in the package.json)?

**Comment by sandy081** [comment]
Currently extensions cannot flag a setting to be ignored for sync by default.

**Comment by chrmarti** [comment]
This also occurs on mac OS starting from the dock when the shell startup scripts take longer than 10 seconds which I have seen happen (without adding `sleep 10` for testing) right after rebooting. We hit the timeout here: https://github.com/microsoft/vscode/blob/1bb144d69c2b2419a04c1539c4c24f6895d7e23b/src/vs/platform/environment/node/shellEnv.ts#L63

The `Log (Main)` output channel shows:
```
[2021-08-25 11:34:24.807] [main] [error] [resolve shell env] Could not resolve shell environment within 10 seconds. Proceeding without shell environment...
```
