### ISSUE TITLE
Remote-SSH login issue into linux host

### ISSUE THREAD

**Issue by satishkrish-cloud** [microsoft/vscode-remote-release#5399]
It loops back again and again to login prompt

[08:44:50.084] SSH Resolver called for "ssh-remote+ecs-win-auto.xxxxx.com", attempt 1
[08:44:50.084] "remote.SSH.useLocalServer": false
[08:44:50.084] "remote.SSH.showLoginTerminal": true
[08:44:50.084] "remote.SSH.remotePlatform": {}
[08:44:50.084] "remote.SSH.path": undefined
[08:44:50.084] "remote.SSH.configFile": undefined
[08:44:50.084] "remote.SSH.useFlock": true
[08:44:50.084] "remote.SSH.lockfilesInTmp": false
[08:44:50.084] "remote.SSH.localServerDownload": auto
[08:44:50.084] "remote.SSH.remoteServerListenOnSocket": true
[08:44:50.085] "remote.SSH.showLoginTerminal": true
[08:44:50.085] "remote.SSH.defaultExtensions": []
[08:44:50.085] "remote.SSH.loglevel": 2
[08:44:50.085] SSH Resolver called for host: ecs-win-auto.xxxxxx.com
[08:44:50.085] Setting up SSH remote "ecs-win-auto.xxxxxxx.com"
[08:44:50.096] Using commit id "c3f126316369cd610563c75b1b1725e0679adfb3" and quality "stable" for server
[08:44:50.098] Install and start server if needed
[08:44:51.908] PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public
[08:44:51.909] Checking ssh with "ssh -V"
[08:44:51.914] > OpenSSH_8.1p1, LibreSSL 2.7.3

[08:44:51.916] Running script with connection command: ssh -T -D 50536 -o ConnectTimeout=15 'ecs-win-auto.xxxxxx.com' bash
[08:44:54.361] > 
>                                  WARNING!!!
>                     READ THIS BEFORE ATTEMPTING TO LOGON
>  
>       xxxx
> 
> 
> 
>         ===========================================================
>          
> 
[08:44:54.361] Got some output, clearing connection timeout
[08:44:54.641] > This is your AD password:
[08:45:19.273] > 
[08:45:20.108] > two-factor login for sbellike
> 
> Enter a passcode or select one of the following options:
> 
>  
> 
> Passcode or option (1-1): 
[08:45:21.417] > 
[08:45:38.585] > e5afd0331c16: running
[08:45:40.017] > Acquiring lock on /users/sbellike/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/vscode-remote-lock.sbellike.c3f126316369cd610563c75b1b1725e0679adfb3
> Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> e5afd0331c16: start
> exitCode==24==
> listeningOn====
> osReleaseId==rhel==
> arch==x86_64==
> tmpDir==/run/user/1759475==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> e5afd0331c16: end
[08:45:40.017] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==rhel==
arch==x86_64==
tmpDir==/run/user/1759475==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[08:45:40.018] Server installation process already in progress - waiting and retrying
[08:45:40.312] "install" terminal command done
[08:45:40.312] Install terminal quit with output: 
[08:45:44.143] getPlatformForHost was canceled
[08:45:44.144] Resolver error: Error: Connecting was canceled
    at Function.Canceled (/Users/sbellike/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:64855)
    at /Users/sbellike/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:294830
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.t.withShowDetailsEvent (/Users/sbellike/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:406463)
    at async Object.t.resolve (/Users/sbellike/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:295994)
    at async /Users/sbellike/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:127:110656
[08:45:44.147] ------

[08:45:57.213] ConfigFileWatcher: start watching file:///Users/sbellike/.ssh/config
[08:45:57.214] ConfigFileWatcher: adding save listener
[08:45:57.214] ConfigFileWatcher: adding close listener

**Comment by bamurtaugh** [comment]
Thanks for reporting @satishkrish-cloud. If you're still experiencing / able to consistently repro, could you please share some additional info: version of VS Code and Remote-SSH, and local and remote OS.
