### ISSUE TITLE
Connection refused using SSH keys on v0.65.7 but working on v0.49

### ISSUE THREAD

**Issue by vitormhenrique** [microsoft/vscode-remote-release#5439]
I'm switched from using passwords to use ssh keys to authenticate to my servers, if it is a brand new server i can use the remote extension to connect to it no problems.

But even after add the `IdentityFile` to my ssh config I still get an connection error to the old servers that I have.

I can log and connect to those servers just fine using  `ssh -i  ~/.ssh/id_rsa vitormhenrique@10.2.40.253` so i know that the keys are setup correctly.

```
  Host TR_STAGINGg[SR]
    HostName 10.2.40.200
    User vitormhenrique
    IdentityFile /Users/vitormhenrique/.ssh/id_rsa
```

I downgraded the extension version to **v0.49** and it worked fine, so I guess it is something with the newer versions.

- VSCode Version: 1.59.0
- Remote extension version: v0.65.7
- Local OS Version: MAC OS 11.5.1 (20G80)
- Remote Extension/Connection Type: SSH/Docker/WSL
- Logs:

```
> Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
> applicable law.
[17:06:56.179] > ready: bbf3d516c6ea
[17:06:56.229] > Linux 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021
[17:06:56.229] Platform: linux
[17:06:56.279] stderr> bash: line 1: _exitcode: command not found
[17:06:56.279] stderr> bash: line 2: syntax error near unexpected token `elif'
[17:06:56.279] stderr> bash: line 2: `	elif [[ $ALLOW_CLIENT_DOWNLOAD == "1" ]]; then'
[17:06:56.279] stderr> -sh: 4: function: not found
[17:06:56.279] stderr> -sh: 69: [[: not found
[17:06:56.279] stderr> -sh: 90: [[: not found
[17:06:56.279] stderr> -sh: 155: Syntax error: "(" unexpected (expecting "then")
[17:06:56.280] > bbf3d516c6ea: running
[17:06:56.280] stderr> Transferred: sent 8204, received 3956 bytes, in 1.3 seconds
[17:06:56.280] stderr> Bytes per second: sent 6319.5, received 3047.3
[17:06:56.281] > local-server-1> ssh child died, shutting down
[17:06:56.284] Local server exit: 0
[17:06:56.285] Received install output: local-server-1> Spawned ssh, pid=31166
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:6tQoyDfHZLiCvlUv/3qKuT2onnrDCAlN4rW+4Err3ts
Authenticated to 10.2.40.253 ([10.2.40.253]:22).
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-80-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Tue 10 Aug 2021 10:06:55 PM UTC

  System load:  0.0                 Processes:             248
  Usage of /:   66.1% of 124.50GB   Users logged in:       0
  Memory usage: 10%                 IPv4 address for eth0: 10.2.40.253
  Swap usage:   0%


160 updates can be installed immediately.
1 of these updates is a security update.
To see these additional updates run: apt list --upgradable



The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.


The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

ready: bbf3d516c6ea
Linux 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021
bash: line 1: _exitcode: command not found
bash: line 2: syntax error near unexpected token `elif'
bash: line 2: `	elif [[ $ALLOW_CLIENT_DOWNLOAD == "1" ]]; then'
-sh: 4: function: not found
-sh: 69: [[: not found
-sh: 90: [[: not found
-sh: 155: Syntax error: "(" unexpected (expecting "then")
bbf3d516c6ea: running
Transferred: sent 8204, received 3956 bytes, in 1.3 seconds
Bytes per second: sent 6319.5, received 3047.3
local-server-1> ssh child died, shutting down

[17:06:56.286] Failed to parse remote port from server output
[17:06:56.287] Resolver error: Error: 
	at Function.Create (/Users/vitormhenrique/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:64659)
	at Object.t.handleInstallOutput (/Users/vitormhenrique/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:63302)
	at Object.e [as tryInstallWithLocalServer] (/Users/vitormhenrique/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:387573)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/vitormhenrique/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:294473
	at async Object.t.withShowDetailsEvent (/Users/vitormhenrique/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:406463)
	at async /Users/vitormhenrique/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:386112
	at async E (/Users/vitormhenrique/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:382710)
	at async Object.t.resolveWithLocalServer (/Users/vitormhenrique/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:385728)
	at async Object.t.resolve (/Users/vitormhenrique/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:295870)
	at async /Users/vitormhenrique/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:127:110656
```

**Comment by liricky** [comment]
Have you fix this error yet? I meet the same error, and fail to solve it in the latest remote extension version. But it do works well in v0.49 extension version.
By the way, my friend use the latest extension version and vscode version, but the Local OS Version is MAC OS 10.14 instead. So I suppose the error is caused by the compatibility between the extension version and the Local OS Version.
- vscode version: 1.59.1
- Remote extension version: v0.65.7
- Local OS Version: MAC OS 11.5.1

**Comment by timharris777** [comment]
I'm having the same issue. 

The following **succeeds**:
- Local OS Version: MAC OS 11.4
- vscode version: 1.59.1
- Remote extension version: v0.65.7
- Remote OS: Amazon Linux 2

The following **succeeds**:
- Local OS Version: MAC OS 11.4
- vscode version: 1.59.1
- Remote extension version: v0.49
- Remote OS: Ubuntu 20.04

The following **fails**:
- Local OS Version: MAC OS 11.4
- vscode version: 1.59.1
- Remote extension version: v0.65.7
- Remote OS: Ubuntu 20.04

```
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:SWTarlASFO8OPUhaQKX7W+LE/rNxZ5EAdDJlwoVlH4M
Authenticated to github-actions-runner (via proxy) using "publickey".
ready: b7e961001277
Linux 5.8.0-1041-aws #43~20.04.1-Ubuntu SMP Thu Jul 15 11:07:29 UTC 2021
bash: line 1: _exitcode: command not found
b7e961001277: running
bash: line 2: syntax error near unexpected token `elif'
bash: line 2: `	elif [[ $ALLOW_CLIENT_DOWNLOAD == "1" ]]; then'
-sh: 4: function: not found
-sh: 69: [[: not found
-sh: 90: [[: not found
-sh: 155: Syntax error: "(" unexpected (expecting "then")
Transferred: sent 18748, received 3756 bytes, in 0.7 seconds
Bytes per second: sent 28232.2, received 5656.1
local-server-1> ssh child died, shutting down

[22:50:09.105] Failed to parse remote port from server output
[22:50:09.106] Resolver error: Error: 
	at Function.Create (/Users/tim.harris/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:64659)
	at Object.t.handleInstallOutput (/Users/tim.harris/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:63302)
	at Object.e [as tryInstallWithLocalServer] (/Users/tim.harris/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:387573)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/tim.harris/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:294473
	at async Object.t.withShowDetailsEvent (/Users/tim.harris/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:406463)
	at async /Users/tim.harris/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:386112
	at async E (/Users/tim.harris/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:382710)
	at async Object.t.resolveWithLocalServer (/Users/tim.harris/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:385728)
	at async Object.t.resolve (/Users/tim.harris/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:295870)
	at async /Users/tim.harris/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:127:110656
[22:50:09.110] ------
```

**Comment by timharris777** [comment]
So... on another note. Updating my users default shell from /bin/sh to /bin/bash on the remote machine fixed the issue. Seems that whatever script vscode is running on the remote machine to setup everything up requires at least `bash` and will error out if the shell is `sh`

**Comment by liricky** [comment]
@timharris777 I have rechecked my default shell on the remote machine (a docker container of Ubuntu 20.04). My origin shell is zsh and the question occurs. Then I changed my shell to bash, but it didn't work as well. Have you changed any other setting of your remote machine? Although I am not sure if your solution works well for other users, I suppose that using bash may still meet the same problem. By the way, I appreciate your help very much. And I hope this question can be solved in the next release version. XD

**Comment by roblourens** [comment]
I expected the install script to be sh-compatible - need to review that

**Comment by roblourens** [comment]
Working in 0.49 implies that setting `"remote.SSH.useLocalServer": false` might fix it

**Comment by vitormhenrique** [comment]
@roblourens have you tried using a brand new server that you never vm (Ubuntu 20.04 LTS on my case)

Setting up only key authentication and it just works for you?  

on my remote server i have zsh installed and running as the default terminal.

**Comment by vitormhenrique** [comment]
Just tested with and without the `remote.SSH.useLocalServer`
Fails on both, the error above with the `remote.SSH.useLocalServer` marked and the following error with the setting unchecked:

```
[15:43:36.680] Log Level: 2
[15:43:36.681] remote-ssh@0.70.0
[15:43:36.682] darwin x64
[15:43:36.683] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a2253525f53544147494e475b53525d5f5353485f4b4559227d", attempt 1
[15:43:36.684] "remote.SSH.useLocalServer": false
[15:43:36.684] "remote.SSH.showLoginTerminal": false
[15:43:36.684] "remote.SSH.remotePlatform": {}
[15:43:36.684] "remote.SSH.path": undefined
[15:43:36.684] "remote.SSH.configFile": undefined
[15:43:36.685] "remote.SSH.useFlock": true
[15:43:36.685] "remote.SSH.lockfilesInTmp": false
[15:43:36.685] "remote.SSH.localServerDownload": auto
[15:43:36.685] "remote.SSH.remoteServerListenOnSocket": false
[15:43:36.685] "remote.SSH.showLoginTerminal": false
[15:43:36.685] "remote.SSH.defaultExtensions": []
[15:43:36.685] "remote.SSH.loglevel": 2
[15:43:36.686] "remote.SSH.serverPickPortsFromRange": {}
[15:43:36.686] "remote.SSH.enableDynamicForwarding": true
[15:43:36.686] "remote.SSH.serverInstallPath": {}
[15:43:36.686] SSH Resolver called for host: SR_STAGING[SR]_SSH_KEY
[15:43:36.686] Setting up SSH remote "SR_STAGING[SR]_SSH_KEY"
[15:43:36.695] Using commit id "7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e" and quality "stable" for server
[15:43:36.698] Install and start server if needed
[15:43:38.275] PATH: /Users/vitormhenrique/opt/anaconda3/bin:/Users/vitormhenrique/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/usr/local/sbin
[15:43:38.275] Checking ssh with "ssh -V"
[15:43:38.280] > OpenSSH_8.6p1, LibreSSL 2.8.3

[15:43:38.282] Running script with connection command: ssh -T -D 61434 -o ConnectTimeout=15 'SR_STAGING[SR]_SSH_KEY' bash
[15:43:40.067] > 8803aa19cf4e: running
> Creating the server install dir failed...
> 8803aa19cf4e: start
> exitCode==34==
> listeningOn====
> osReleaseId====
> arch====
> tmpDir==/run/user/1002==
> platform====
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 8803aa19cf4e: end
> mkdir: cannot create directory ‘/home/vitormhenrique/.vscode-server’: Permission denied
[15:43:40.068] Got some output, clearing connection timeout
[15:43:40.068] Received install output: 
exitCode==34==
listeningOn====
osReleaseId====
arch====
tmpDir==/run/user/1002==
platform====
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[15:43:40.069] Failed to parse remote port from server output
[15:43:40.070] Resolver error: Error: 
	at Function.Create (/Users/vitormhenrique/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:430425)
	at Object.t.handleInstallOutput (/Users/vitormhenrique/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:429068)
	at Object.t.tryInstall (/Users/vitormhenrique/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:524212)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/vitormhenrique/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:487216
	at async Object.t.withShowDetailsEvent (/Users/vitormhenrique/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:490561)
	at async Object.t.resolve (/Users/vitormhenrique/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:488295)
	at async /Users/vitormhenrique/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:564197
[15:43:40.073] ------
```

**Comment by vitormhenrique** [comment]
Quick update, I discovered that my home directory had the incorrect ownership, by fixing that with the `remote.SSH.useLocalServer` disabled I could connect to the server!

But if the `remote.SSH.useLocalServer` is checked I still get the error when setting up a new server....

**Comment by roblourens** [comment]
You still get `cannot create directory ‘/home/vitormhenrique/.vscode-server’: Permission denied`?

**Comment by vitormhenrique** [comment]
Sorry for the delay, the permission denied was being caused by stupidity apparently!
I created the user using a remote agent, and it set the incorrect owner for the user.

So in summary, if I check the `remote.SSH.useLocalServer` I still get the same error as before.

**Comment by MartinPELCAT** [comment]
Faced the same probleme and i tried to use all the seetings and it didn't work.

I solved it by connecting to ssh manually and then delete the `.vscode-server` folder at /root/.vscode-server

Just a good old ```rm -rf .vscode-server/```

Not sure if it's the best solution but it worked

**Comment by xu4k** [comment]
> Faced the same probleme and i tried to use all the seetings and it didn't work.
> 
> I solved it by connecting to ssh manually and then delete the `.vscode-server` folder at `/root/.vscode-server`
> 
> Just a good old `rm -rf .vscode-server/`
> 
> Not sure if it's the best solution but it worked

Hi @MartinPELCAT,

When connecting, VSCode is creating `.vscode-server` automatically right?
I somehow face the same permission problem where `.vscode-server` is created by `root`. 
And I don't have root permission on the server. 

But does root permissions change anything for connecting remotely via VSCode?

**Comment by santhoshcameo** [comment]
I have the same issue on latest build as well, tried all the possible combinations

```
Version: 1.73.1 (Universal)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T02:08:38.961Z (1 wk ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.1.0
Sandboxed: No
```

Another thread on this [https://github.com/microsoft/vscode-remote-release/issues/7441]


Any updates please?

**Comment by roblourens** [comment]
Lots has changed, and there are some different possible issues behind getting the bash syntax error that are open (firewall that interrupts the script, a different shell running on the remote and not passing along the full script to bash, ...). Can follow up if anyone is still having an issue
