### ISSUE TITLE
An error occurred while loading the image

### ISSUE THREAD

**Issue by MichaelSuen-thePointer** [microsoft/vscode-remote-release#5441]
- VSCode Version: 1.59.0(user setup_
- Local OS Version: Win 10.0.19042.1110
- Remote OS Version: Debian10 (kernel 4.19.37)
- Remote Extension/Connection Type: SSH
- Logs:
```
ENOPRO: No file system provider found for resource 'xn--vscode-remote://ssh-remote%2B-zg83brz7ra/home/sunmingqi/u5_server/tools/analyzer_output/ai103_pass_time_hist.png?version%3D1628656615694'
    at ci.withProvider (vscode-file://vscode-app/c:/Users/sunmingqi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:637:11313)
    at async ci.withReadProvider (vscode-file://vscode-app/c:/Users/sunmingqi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:637:11436)
    at async ci.readFileStream (vscode-file://vscode-app/c:/Users/sunmingqi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:637:16301)
    at async w (vscode-file://vscode-app/c:/Users/sunmingqi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1220:19544)
    at async i.loadResource (vscode-file://vscode-app/c:/Users/sunmingqi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1510:16286)
ai103_pass_time_hist.png:1 GET https://xn--vscode-remote+ssh-remote+-zg83brz7ra.vscode-resource.vscode-webview.net/home/sunmingqi/u5_server/tools/analyzer_output/ai103_pass_time_hist.png?version%3D1628656615694 404
Image (async)
(anonymous) @ main.js:313
(anonymous) @ main.js:340
```
![image](https://user-images.githubusercontent.com/12868093/128970510-6b45de81-9c9e-4965-9d61-afb0e5beed24.png)

![image](https://user-images.githubusercontent.com/12868093/128970492-51d30c1c-a5fa-4544-b26f-66d8cbac1f08.png)

Steps to Reproduce:

1. open the remote session
2. open an image

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

It seems that something wrong with the "remote file providing url", in this case `https://xn--vscode-remote+ssh-remote+-zg83brz7ra.vscode-resource.vscode-webview.net/home/sunmingqi/u5_server/tools/analyzer_output/ai103_pass_time_hist.png?version%3D1628656615694` returned 404 error, but appearently this file exists

And by the way the similar issue appears when I was commiting files in SVN extension, the css file of the page failed to load, and the error message was also "404 error"

**Comment by MichaelSuen-thePointer** [comment]
Ok, after changing Host section to ascii-words only, this issue disappears, but I still think this is a bug, I will rename this issue anyway.
