### ISSUE TITLE
Server did not start successfully

### ISSUE THREAD

**Issue by phil-harmoniq** [microsoft/vscode-remote-release#5459]
- VSCode Version: 1.59.0
- Local OS Version: Windows 11 Pro 22000.132
- Remote OS Version: Raspbian 10 (buster) aarch64
- Remote Extension/Connection Type: SSH/Docker/WSL
- Logs:

```[12:01:00.893] Log Level: 2
[12:01:00.896] remote-ssh@0.65.7
[12:01:00.896] win32 x64
[12:01:00.897] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a227270692d31222c2275736572223a226465766f7073227d", attempt 1
[12:01:00.898] "remote.SSH.useLocalServer": false
[12:01:00.898] "remote.SSH.showLoginTerminal": false
[12:01:00.898] "remote.SSH.remotePlatform": {"192.168.1.20":"linux","RaspberryPi":"linux","orion":"linux","192.168.1.17":"linux","10.1.1.190":"linux","Pi":"linux","orion.lan":"linux"}
[12:01:00.898] "remote.SSH.path": undefined
[12:01:00.898] "remote.SSH.configFile": undefined
[12:01:00.898] "remote.SSH.useFlock": true
[12:01:00.899] "remote.SSH.lockfilesInTmp": false
[12:01:00.899] "remote.SSH.localServerDownload": auto
[12:01:00.899] "remote.SSH.remoteServerListenOnSocket": false
[12:01:00.899] "remote.SSH.showLoginTerminal": false
[12:01:00.899] "remote.SSH.defaultExtensions": []
[12:01:00.899] "remote.SSH.loglevel": 2
[12:01:00.899] SSH Resolver called for host: devops@rpi-1
[12:01:00.899] Setting up SSH remote "rpi-1"
[12:01:00.915] Using commit id "379476f0e13988d90fab105c5c19e7abc8b1dea8" and quality "stable" for server
[12:01:00.918] Install and start server if needed
[12:01:02.212] Checking ssh with "ssh -V"
[12:01:02.240] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[12:01:02.243] Running script with connection command: ssh -T -D 62215 "devops@rpi-1" bash
[12:01:02.245] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[12:01:02.425] > ]0;C:\WINDOWS\System32\cmd.exe
[12:01:02.425] Got some output, clearing connection timeout
[12:01:02.639] > 0e0382531bc1: running
[12:01:02.717] > Acquiring lock on /home/devops/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/vscode-remote-lock.devops.379476f0e13988d90fab105c5c19e7abc8b1dea8
[12:01:02.737] > Installing to /home/devops/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8...
[12:01:02.760] > 0e0382531bc1%%1%%
> Downloading with wget
[12:01:06.028] > Download complete
[12:01:06.048] > 0e0382531bc1%%2%%
> tar --version:
> tar (GNU tar) 1.30
> Copyright (C) 2017 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.Written by John Gilmore and Jay Fenlason.
> 
[12:01:11.562] > Checking /home/devops/.vscode-server/.379476f0e13988d90fab105c5c19e7abc8b1dea8.log and /home/devops/.vscode-server/.379476f0e13988d90fab105c5c19e7abc8b1dea8.pid for a running server
[12:01:11.607] > Starting server with command... /home/devops/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/server.sh --start-server --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0  &> "/home/devops/.vscode-server/.379476f0e13988d90fab105c5c19e7abc8b1dea8.log" < /dev/null
> printenv:
>     SHELL=/bin/bash
>     PWD=/home/devops
>     LOGNAME=devops
>     XDG_SESSION_TYPE=tty
>     HOME=/home/devops
>     LANG=en_GB.UTF-8
[12:01:11.611] > 
>     VSCODE_AGENT_FOLDER=/home/devops/.vscode-server
>     SSH_CONNECTION=10.0.229.105 62217 10.0.181.149 22
>     XDG_SESSION_CLASS=user
>     USER=devops
>     SHLVL=0
>     XDG_SESSION_ID=33
>     XDG_RUNTIME_DIR=/run/user/1001
>     SSH_CLIENT=10.0.229.105 62217 22
>     PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
>     MAIL=/var/mail/devops
>     OLDPWD=/home/devops/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1d
> dea8
>     _=/usr/bin/printenv
[12:01:11.620] > 
> rm: cannot remove '/home/devops/.vscode-server/.379476f0e13988d90fab105c5c19e7ab
> bc8b1dea8.token': No such file or directory
[12:01:11.630] > Spawned remote server: 8123
[12:01:11.637] > 
> Waiting for server log...
[12:01:11.653] > 
[12:01:11.684] > Waiting for server log...
[12:01:11.728] > Waiting for server log...
[12:01:11.770] > Waiting for server log...
[12:01:11.812] > Waiting for server log...
[12:01:11.859] > Waiting for server log...
[12:01:11.899] > Waiting for server log...
[12:01:11.943] > Waiting for server log...
[12:01:11.986] > Waiting for server log...
[12:01:12.034] > Waiting for server log...
[12:01:12.080] > Waiting for server log...
[12:01:12.132] > Waiting for server log...
[12:01:12.185] > Waiting for server log...
[12:01:12.233] > Waiting for server log...
[12:01:12.283] > Waiting for server log...
[12:01:12.334] > Waiting for server log...
[12:01:12.385] > Waiting for server log...
[12:01:12.432] > Waiting for server log...
[12:01:12.476] > Waiting for server log...
[12:01:12.516] > Waiting for server log...
[12:01:12.561] > Waiting for server log...
[12:01:12.603] > Waiting for server log...
[12:01:12.645] > Waiting for server log...
[12:01:12.689] > Waiting for server log...
[12:01:12.730] > Waiting for server log...
[12:01:12.778] > Waiting for server log...
[12:01:12.820] > Waiting for server log...
[12:01:12.864] > Waiting for server log...
[12:01:12.907] > Waiting for server log...
[12:01:12.950] > Waiting for server log...
[12:01:12.995] > Waiting for server log...
[12:01:13.037] > Waiting for server log...
[12:01:13.080] > Waiting for server log...
[12:01:13.122] > Waiting for server log...
[12:01:13.166] > Waiting for server log...
[12:01:13.207] > Waiting for server log...
[12:01:13.248] > Waiting for server log...
[12:01:13.292] > Waiting for server log...
[12:01:13.336] > Waiting for server log...
[12:01:13.380] > Waiting for server log...
[12:01:13.421] > Waiting for server log...
[12:01:13.465] > Waiting for server log...
[12:01:13.508] > Waiting for server log...
[12:01:13.550] > Waiting for server log...
[12:01:13.593] > Waiting for server log...
[12:01:13.636] > Waiting for server log...
[12:01:13.679] > Waiting for server log...
[12:01:13.722] > Waiting for server log...
[12:01:13.765] > Waiting for server log...
[12:01:13.808] > Waiting for server log...
[12:01:13.851] > Waiting for server log...
[12:01:13.893] > Waiting for server log...
[12:01:13.935] > Waiting for server log...
[12:01:13.979] > Waiting for server log...
[12:01:14.022] > Waiting for server log...
[12:01:14.066] > Waiting for server log...
[12:01:14.109] > Waiting for server log...
[12:01:14.151] > Waiting for server log...
[12:01:14.194] > Waiting for server log...
[12:01:14.234] > Waiting for server log...
[12:01:14.279] > Waiting for server log...
[12:01:14.322] > Waiting for server log...
[12:01:14.366] > Waiting for server log...
[12:01:14.413] > Waiting for server log...
[12:01:14.457] > Waiting for server log...
[12:01:14.500] > Waiting for server log...
[12:01:14.544] > Waiting for server log...
[12:01:14.584] > Waiting for server log...
[12:01:14.629] > Waiting for server log...
[12:01:14.671] > Waiting for server log...
[12:01:14.714] > Waiting for server log...
[12:01:14.756] > Waiting for server log...
[12:01:14.800] > Waiting for server log...
[12:01:14.842] > Waiting for server log...
[12:01:14.882] > Waiting for server log...
[12:01:14.926] > Waiting for server log...
[12:01:14.970] > Waiting for server log...
[12:01:15.011] > Waiting for server log...
[12:01:15.055] > Waiting for server log...
[12:01:15.100] > Waiting for server log...
[12:01:15.142] > Waiting for server log...
[12:01:15.185] > Waiting for server log...
[12:01:15.226] > Waiting for server log...
[12:01:15.268] > Waiting for server log...
[12:01:15.314] > Waiting for server log...
[12:01:15.358] > Waiting for server log...
[12:01:15.401] > Waiting for server log...
[12:01:15.444] > Waiting for server log...
[12:01:15.487] > Waiting for server log...
[12:01:15.532] > Waiting for server log...
[12:01:15.571] > Waiting for server log...
[12:01:15.615] > Waiting for server log...
[12:01:15.659] > Waiting for server log...
[12:01:15.702] > Waiting for server log...
[12:01:15.745] > Waiting for server log...
[12:01:15.786] > Waiting for server log...
[12:01:15.829] > Waiting for server log...
[12:01:15.872] > Waiting for server log...
[12:01:15.914] > Waiting for server log...
[12:01:15.957] > Waiting for server log...
[12:01:16.000] > Waiting for server log...
[12:01:16.043] > Waiting for server log...
[12:01:16.085] > Waiting for server log...
[12:01:16.128] > Waiting for server log...
[12:01:16.172] > Waiting for server log...
[12:01:16.213] > Waiting for server log...
[12:01:16.256] > Waiting for server log...
[12:01:16.303] > Waiting for server log...
[12:01:16.347] > Waiting for server log...
[12:01:16.388] > Waiting for server log...
[12:01:16.433] > Waiting for server log...
[12:01:16.481] > Waiting for server log...
[12:01:16.526] > Waiting for server log...
[12:01:16.567] > Waiting for server log...
[12:01:16.610] > Waiting for server log...
[12:01:16.653] > Waiting for server log...
[12:01:16.696] > Waiting for server log...
[12:01:16.739] > Waiting for server log...
[12:01:16.782] > Waiting for server log...
[12:01:16.824] > Waiting for server log...
[12:01:16.868] > Waiting for server log...
[12:01:16.912] > Waiting for server log...
[12:01:16.955] > Waiting for server log...
[12:01:16.998] > Waiting for server log...
[12:01:17.041] > Waiting for server log...
[12:01:17.083] > Waiting for server log...
[12:01:17.126] > Waiting for server log...
[12:01:17.171] > Waiting for server log...
[12:01:17.216] > Waiting for server log...
[12:01:17.261] > Waiting for server log...
[12:01:17.307] > Waiting for server log...
[12:01:17.350] > Waiting for server log...
[12:01:17.393] > Waiting for server log...
[12:01:17.450] > Waiting for server log...
[12:01:17.501] > Waiting for server log...
[12:01:17.544] > Waiting for server log...
[12:01:17.588] > Waiting for server log...
[12:01:17.630] > Waiting for server log...
[12:01:17.675] > Waiting for server log...
[12:01:17.718] > Waiting for server log...
[12:01:17.761] > Waiting for server log...
[12:01:17.803] > Waiting for server log...
[12:01:17.846] > Waiting for server log...
[12:01:17.886] > Waiting for server log...
[12:01:17.929] > Waiting for server log...
[12:01:17.974] > Waiting for server log...
[12:01:18.017] > Waiting for server log...
[12:01:18.059] > Waiting for server log...
[12:01:18.103] > Waiting for server log...
[12:01:18.153] > Waiting for server log...
[12:01:18.199] > Waiting for server log...
[12:01:18.243] > Waiting for server log...
[12:01:18.287] > Waiting for server log...
[12:01:18.332] > Waiting for server log...
[12:01:18.375] > Waiting for server log...
[12:01:18.418] > Waiting for server log...
[12:01:18.470] > Waiting for server log...
[12:01:18.515] > Waiting for server log...
[12:01:18.557] > Waiting for server log...
[12:01:18.599] > Waiting for server log...
[12:01:18.642] > Waiting for server log...
[12:01:18.685] > Waiting for server log...
[12:01:18.727] > Waiting for server log...
[12:01:18.771] > Waiting for server log...
[12:01:18.816] > Waiting for server log...
[12:01:18.855] > Waiting for server log...
[12:01:18.897] > Waiting for server log...
[12:01:18.941] > Waiting for server log...
[12:01:18.986] > Waiting for server log...
[12:01:19.025] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
[12:01:19.045] > 
> Server did not start successfully. Full server log at /home/devops/.vscode-serve
> er/.379476f0e13988d90fab105c5c19e7abc8b1dea8.log >>>
> /home/devops/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/server.
> .sh: 12: /home/devops/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8
> 8/server.sh: /home/devops/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1
> 1dea8/node: not found
> <<< End of server log
[12:01:19.051] > 
> 0e0382531bc1: start
> exitCode==32==
> listeningOn====
> osReleaseId==raspbian==
> arch==aarch64==
> tmpDir==/run/user/1001==
> platform==linux==
> unpackResult==success==
> didLocalDownload==0==
> downloadTime==3285==
> installTime==5467==
> extInstallTime====
> serverStartTime==7408==
> 0e0382531bc1: end
[12:01:19.051] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==raspbian==
arch==aarch64==
tmpDir==/run/user/1001==
platform==linux==
unpackResult==success==
didLocalDownload==0==
downloadTime==3285==
installTime==5467==
extInstallTime====
serverStartTime==7408==

[12:01:19.051] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (c:\Users\Phil\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64593)
	at c (c:\Users\Phil\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:58918)
	at Object.t.handleInstallOutput (c:\Users\Phil\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:63335)
	at Object.t.tryInstall (c:\Users\Phil\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:415135)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\Phil\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:294918
	at async Object.t.withShowDetailsEvent (c:\Users\Phil\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:406463)
	at async Object.t.resolve (c:\Users\Phil\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:295994)
	at async c:\Users\Phil\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:127:110656
[12:01:19.055] ------




[12:01:19.295] > 
[12:01:20.349] "install" terminal command done
[12:01:20.350] Install terminal quit with output:
```
Steps to Reproduce:

1. Connect to Raspberry Pi 4 from a VS Code
2. Server startup fails

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

This appears to be the [same issue as this one](https://github.com/microsoft/vscode-remote-release/issues/2145), but that issue was closed without a solution. I'm not sure why this is failing. I tried the steps suggested in the previous thread and was not successful:

```
[ devops@rpi-1 ~ ]$ .vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/server.sh
.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/server.sh: 12: .vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/server.sh: .vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/node: not found
[ devops@rpi-1 ~ ]$ .vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/node
-bash: .vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/node: No such file or directory
[ devops@rpi-1 ~ ]$ ls -lhaF .vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/
total 70M
drwxr-xr-x  6 devops devops 4.0K Aug 14 17:01 ./
drwxr-xr-x  3 devops devops 4.0K Aug 14 17:01 ../
drwxr-xr-x  3 devops devops 4.0K Aug  5 00:13 bin/
drwxr-xr-x 34 devops devops 4.0K Aug  5 00:13 extensions/
-rw-r--r--  1 devops devops  14K Aug  5 00:12 LICENSE
-rwxr-xr-x  1 devops devops  70M Aug  5 00:13 node*
drwxr-xr-x 75 devops devops 4.0K Aug  5 00:13 node_modules/
drwxr-xr-x  3 devops devops 4.0K Aug  5 00:13 out/
-rw-r--r--  1 devops devops 1.1K Aug  5 00:12 package.json
-rw-r--r--  1 devops devops  34K Aug  5 00:12 product.json
-rwxr-xr-x  1 devops devops  222 Aug  5 00:12 server.sh*
```

**Comment by bamurtaugh** [comment]
Hey @phil-harmoniq, thanks for reporting. Are you still experiencing this issue? Is it consistent? Did it appear after any updates/changes (i.e. new VS Code or Remote-SSH version)?

**Comment by phil-harmoniq** [comment]
@bamurtaugh This seems to be due to running the aarch64 kernel of Raspbian which doesn't fully support some 64-bit binaries. I switched to running Ubuntu arm64 and the remote server ran as expected. I found this related issue which helped me figure out what was happening: https://github.com/dotnet/core/issues/4694

**Comment by Vincysuper07** [comment]
Hello. I am also experiencing this issue. This started happening when I changed the Raspbian kernel from `armv7l` (32-bit) to the `aarch64` (64-bit) one.
