### ISSUE TITLE
VS Code Server failed to start 

### ISSUE THREAD

**Issue by clobraico22** [microsoft/vscode-remote-release#5461]
I'm currently attempting to access the ubuntu server on my odroid-c4. I have no issue doing so from the command line, though I'm unable to do so using the remote connection extension on vs-code.

**What I've already tried**
-  `rm ~/.vscode  -rf `on the remote server
- ` Remote-SSH: kill VS Code Server on Host... `command in VSCode. 

**Here is the log output from when I attempt to access SSH:**
[10:58:07.144] > Server did not start successfully. Full server log at /home/aretex/.vscode-server/.379476f0e13988d90fab105c5c19e7abc8b1dea8.log >>>
[10:58:07.150] > /home/aretex/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/server.sh: 12: /home/aretex/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/server.sh: /home/aretex/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/node: not found
> <<< End of server log
> 14343786a1bd: start
> exitCode==32==
> listeningOn====
> osReleaseId==ubuntu==
> arch==aarch64==
> tmpDir==/tmp==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==7477==
> 14343786a1bd: end
[10:58:07.151] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==ubuntu==
arch==aarch64==
tmpDir==/tmp==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==7477==

[10:58:07.154] Terminating local server
[10:58:07.158] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (/home/clobraico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:64593)
	at c (/home/clobraico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:58918)
	at Object.t.handleInstallOutput (/home/clobraico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:63335)
	at Object.e [as tryInstallWithLocalServer] (/home/clobraico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:387573)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/clobraico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:294473
	at async Object.t.withShowDetailsEvent (/home/clobraico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:406463)
	at async /home/clobraico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:386112
	at async E (/home/clobraico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:382710)
	at async Object.t.resolveWithLocalServer (/home/clobraico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:385728)
	at async Object.t.resolve (/home/clobraico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:295870)
	at async /home/clobraico/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:127:110656
[10:58:07.181] ------

[10:58:07.183] Local server exit: 15

**Comment by bamurtaugh** [comment]
Does your odroid-c4 meet these requirements: https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites?

**Comment by bamurtaugh** [comment]
If you're still experiencing and/or able to provide the info above, please let us know. Thank you!
