### ISSUE TITLE
Could not establish connection to SERVER: Connecting with SSH timed out.

### ISSUE THREAD

**Issue by yihan0512** [microsoft/vscode-remote-release#5464]
- VSCode Version: 1.60.0-insider
- Local OS Version: MacOS Big Sur 11.4
- Remote OS Version: Ubuntu 20
- Remote Extension/Connection Type: SSH
- Logs:
```
[17:58:57.768]` Log Level: 2
[17:58:57.770] remote-ssh-nightly@2021.8.18181
[17:58:57.770] darwin x64
[17:58:57.771] SSH Resolver called for "ssh-remote+lab4n6yi", attempt 1
[17:58:57.771] "remote.SSH.useLocalServer": true
[17:58:57.772] "remote.SSH.path": undefined
[17:58:57.772] "remote.SSH.configFile": undefined
[17:58:57.772] "remote.SSH.useFlock": true
[17:58:57.772] "remote.SSH.lockfilesInTmp": false
[17:58:57.773] "remote.SSH.localServerDownload": auto
[17:58:57.773] "remote.SSH.remoteServerListenOnSocket": false
[17:58:57.773] "remote.SSH.showLoginTerminal": false
[17:58:57.773] "remote.SSH.defaultExtensions": []
[17:58:57.774] "remote.SSH.loglevel": 2
[17:58:57.774] SSH Resolver called for host: lab4n6yi
[17:58:57.777] Setting up SSH remote "lab4n6yi"
[17:58:57.780] Acquiring local install lock: /var/folders/5q/9jy5ycbs4zq4cb7mbpr2ctpr0000gn/T/vscode-remote-ssh-fc67fd9a-install.lock
[17:58:57.792] Looking for existing server data file at /Users/yihan/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh-nightly/vscode-ssh-host-fc67fd9a-9dd4f31a21d63deea5e1fc322cfc802413b31d95-2021.8.18181/data.json
[17:58:57.792] Using commit id "9dd4f31a21d63deea5e1fc322cfc802413b31d95" and quality "insider" for server
[17:58:57.795] Install and start server if needed
[17:58:57.797] PATH: /Users/yihan/anaconda3/bin:/Users/yihan/anaconda3/condabin:/Users/yihan/.poetry/bin:/Users/yihan/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin
[17:58:57.798] Checking ssh with "ssh -V"
[17:58:57.803] > OpenSSH_8.1p1, LibreSSL 2.7.3

[17:58:57.806] askpass server listening on /var/folders/5q/9jy5ycbs4zq4cb7mbpr2ctpr0000gn/T/vscode-ssh-askpass-009312fe9906068ff5da8bb2f954cb59ae039e7e.sock
[17:58:57.806] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/5q/9jy5ycbs4zq4cb7mbpr2ctpr0000gn/T/vscode-ssh-askpass-6117a4f37bbcb2ca46348b2563bbfc188eaf8799.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","61747","-o","ConnectTimeout=15","lab4n6yi"],"dataFilePath":"/Users/yihan/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh-nightly/vscode-ssh-host-fc67fd9a-9dd4f31a21d63deea5e1fc322cfc802413b31d95-2021.8.18181/data.json"}
[17:58:57.806] Local server env: {"DISPLAY":"/private/tmp/com.apple.launchd.MGSW3IG6VK/org.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/yihan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.8.18181/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/yihan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.8.18181/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/5q/9jy5ycbs4zq4cb7mbpr2ctpr0000gn/T/vscode-ssh-askpass-009312fe9906068ff5da8bb2f954cb59ae039e7e.sock"}
[17:58:57.807] Spawned 29163
[17:58:57.937] > local-server-1> Spawned ssh, pid=29172
[17:58:57.939] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[17:58:58.019] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:v6UVdNlzCiwMjvRWIxt+6iBon7sX2rWrX9xsQ69KF+o
[17:58:58.123] stderr> Authenticated to test535.engr.rutgers.edu ([172.16.60.140]:22).
[17:58:58.222] stderr> Warning: No xauth data; using fake authentication data for X11 forwarding.
[17:58:58.232] > Welcome to Ubuntu 20.04.2 LTS (GNU/Linux 5.8.0-63-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
> 102 updates can be applied immediately.
> 23 of these updates are standard security updates.
> To see these additional updates run: apt list --upgradable
> 
> 
> 5 updates could not be installed automatically. For more details,
> see /var/log/unattended-upgrades/unattended-upgrades.log
> Your Hardware Enablement Stack (HWE) is supported until April 2025.
> *** System restart required ***
[17:59:14.809] Terminating local server
[17:59:14.811] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/yihan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.8.18181/out/extension.js:1:397137)
	at Timeout._onTimeout (/Users/yihan/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-nightly-2021.8.18181/out/extension.js:1:441287)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[17:59:14.816] ------




[17:59:14.817] Local server exit: 15
```

1. Attempts to connect to all three of my servers failed, both with password or rsa keys
2. There is no problem connecting via ssh in terminal
3.  looking at the logs it seems like the remote machine is already successfully authenticated, but still connection cannot be established.

Steps to Reproduce:

1. it does not really take any step to reproduce, just try connect to a host

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by akshat-crypto** [comment]
Try removing the binary file in /root/.vscode-server/bin/345xxxxxxxxx file in your remote VM,  In my case it started downloading the files again and worked properly

**Comment by yihan0512** [comment]
> Try removing the binary file in /root/.vscode-server/bin/345xxxxxxxxx file in your remote VM and then do ssh, In my case it started downloading the files again and worked properly

Thank you @akshat-crypto, however the solution does not work for me. I don't have ./root/.vscode-server/ on my remote machine. I do have .vscode-server in the home dir, I followed some solutions from StackOverFlow to delete the whole folder and connect again, however, this did not solve the problem either and .vscode-server/ was not even re-installed when I connect.

**Comment by roblourens** [comment]
We sent a script for your remote to execute, and it seems that it never starting executing.

Does running a command like `echo "echo hello" | ssh yourhost bash` work?
