### ISSUE TITLE
Cannot reconnect. Please reload the window

### ISSUE THREAD

**Issue by wonjeongchoi** [microsoft/vscode-remote-release#5476]
🚨 The issue tracker is not for questions 🚨

If you have a question about VS Code, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code and about
VS Code Remote on https://stackoverflow.com/questions/tagged/vscode-remote.

Hi, I have issue on remote-ssh to my remote gpu server(ubuntu 18.04) after I did format on my computer(window 10).

Full logs are below.

"""
[23:16:20.441] [Forwarding server 53292] Got connection 1
[23:16:20.458] [Forwarding server 53292] Got connection 2
[23:26:07.017] > client_loop: send disconnect: Connection reset
[23:26:08.287] "install" terminal command done
[23:26:08.287] Install terminal quit with output:    client_loop: send disconnect: Connection reset
[23:26:23.675] ------

[23:26:23.675] SSH Resolver called for "ssh-remote+comstogpu6.kaist.ac.kr", attempt 2, (Reconnection)
[23:26:23.675] SSH Resolver called for host: comstogpu6.kaist.ac.kr
[23:26:23.676] Setting up SSH remote "comstogpu6.kaist.ac.kr"
[23:26:23.678] Using commit id "379476f0e13988d90fab105c5c19e7abc8b1dea8" and quality "stable" for server
[23:26:23.681] Install and start server if needed
[23:26:23.686] Using SSH config file "C:\\Users\\user\\.ssh\\config"
[23:26:23.687] Running script with connection command: ssh -T -D 49169 -F "C:\\Users\\user\\.ssh\\config" "comstogpu6.kaist.ac.kr" bash
[23:26:23.688] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[23:26:23.910] > ]0;C:\WINDOWS\System32\cmd.exe
[23:26:23.910] Got some output, clearing connection timeout
[23:26:24.778] > @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[23:26:24.802] > @    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
> Someone could be eavesdropping on you right now (man-in-the-middle attack)!     
> It is also possible that a host key has just been changed.
> The fingerprint for the RSA key sent by the remote host is
> SHA256:iDaqi84d...
> Please contact your system administrator.
> Add correct host key in C:\\Users\\user/.ssh/known_hosts to get rid of this mess
> age.
> Offending ECDSA key in C:\\Users\\user/.ssh/known_hosts:3
> RSA host key for comstogpu6.kaist.ac.kr has changed and you have requested stric
> t checking.
> Host key verification failed.
> The process tried to write to a nonexistent pipe.
> 
[23:26:26.063] "install" terminal command done
[23:26:26.064] Install terminal quit with output: The process tried to write to a nonexistent pipe.
[23:26:26.064] Received install output: The process tried to write to a nonexistent pipe.
[23:26:26.064] Failed to parse remote port from server output
[23:26:26.065] Resolver error: Error: 
	at Function.Create (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64659)
	at Object.t.handleInstallOutput (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:63302)
	at Object.t.tryInstall (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:415135)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:294918
	at async Object.t.withShowDetailsEvent (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:406463)
	at async Object.t.resolve (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:295994)
	at async c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:127:110656
[23:26:26.067] ------
"""

I have already tried several solutions for this type of issue.
I have tried..
  1) edit my local C:\Users\user\.ssh\known_hosts file to remove "Offending ECDSA key" => not working
  2) manually set config path => not working

Is there anyone who can help?

**Comment by bamurtaugh** [comment]
I think this may be the same as https://github.com/microsoft/vscode-remote-release/issues/5456?
