### ISSUE TITLE
why not install extension by SCP on the offline server?

### ISSUE THREAD

**Issue by WXZhao7** [microsoft/vscode-remote-release#5478]
- VSCode Version: 1.59.0
- Local OS Version: Ubuntu 20.04 focal
- Remote OS Version: Ubuntu 20.04 focal
- Remote Extension/Connection Type: SSH
- Logs:
- 
<details>
<summary>Remote Server Log</summary>
[2021-08-17 21:51:39.240] [remoteagent] [info] 

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*

[2021-08-17 21:51:39.240] [remoteagent] [info] Extension host agent started.
[2021-08-17 21:51:39.411] [remoteagent] [info] Deleted from disk ms-python.vscode-pylance /home/wxz/.vscode-server/extensions/ms-python.vscode-pylance-2021.7.7
[2021-08-17 21:51:39.843] [remoteagent] [info] [<unknown>][f422785d][ManagementConnection] New connection established.
[2021-08-17 21:51:39.864] [remoteagent] [info] [<unknown>][0b29847a][ExtensionHostConnection] New connection established.
[2021-08-17 21:51:39.877] [remoteagent] [info] [<unknown>][0b29847a][ExtensionHostConnection] <130628> Launched Extension Host Process.
[2021-08-17 21:58:21.545] [remoteagent] [info] Installing extension: ms-azuretools.vscode-docker
[2021-08-17 21:58:23.088] [remoteagent] [info] Installing extension: ms-azuretools.vscode-docker
[2021-08-17 21:58:38.443] [remoteagent] [info] Installing extension: ms-python.vscode-pylance
[2021-08-17 21:58:38.548] [remoteagent] [info] Installing extension: ms-python.python
[2021-08-17 21:58:38.665] [remoteagent] [info] Installing extension: ms-python.python
[2021-08-17 21:58:38.754] [remoteagent] [info] Installing extension: ms-python.vscode-pylance
[2021-08-17 21:58:39.031] [remoteagent] [info] Installing extension: ms-python.python
[2021-08-17 21:58:39.131] [remoteagent] [info] Installing extension: ms-python.vscode-pylance
[2021-08-17 21:58:39.354] [remoteagent] [info] Installing extension: ms-python.vscode-pylance
[2021-08-17 21:58:39.474] [remoteagent] [info] Installing extension: ms-python.python
[2021-08-17 21:58:41.528] [remoteagent] [info] Installing extension: ms-toolsai.jupyter
[2021-08-17 21:58:41.638] [remoteagent] [info] Installing extension: ms-toolsai.jupyter
[2021-08-17 21:58:42.705] [remoteagent] [info] Installing extension: ms-toolsai.jupyter
[2021-08-17 21:58:43.521] [remoteagent] [info] Installing extension: ms-toolsai.jupyter
[2021-08-17 22:00:32.781] [remoteagent] [error] Error while preparing to install dependencies and extension packs of the extension: ms-azuretools.vscode-docker
[2021-08-17 22:00:32.787] [remoteagent] [error] Error: connect ETIMEDOUT 13.107.42.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2021-08-17 22:00:32.788] [remoteagent] [error] Failed to install extension: ms-azuretools.vscode-docker connect ETIMEDOUT 13.107.42.18:443
[2021-08-17 22:00:32.790] [remoteagent] [error] Error while preparing to install dependencies and extension packs of the extension: ms-azuretools.vscode-docker
[2021-08-17 22:00:32.790] [remoteagent] [error] Error: connect ETIMEDOUT 13.107.42.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2021-08-17 22:00:32.790] [remoteagent] [error] Failed to install extension: ms-azuretools.vscode-docker connect ETIMEDOUT 13.107.42.18:443
[2021-08-17 22:00:51.239] [remoteagent] [info] Deleted from disk ms-toolsai.jupyter /home/wxz/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1195043623
[2021-08-17 22:00:51.240] [remoteagent] [info] Deleted from disk ms-toolsai.jupyter /home/wxz/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1195043623
[2021-08-17 22:00:53.262] [remoteagent] [info] Deleted from disk ms-toolsai.jupyter /home/wxz/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1195043623
[2021-08-17 22:00:53.262] [remoteagent] [info] Deleted from disk ms-toolsai.jupyter /home/wxz/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1195043623
[2021-08-17 22:00:54.674] [remoteagent] [info] Extracted extension to /home/wxz/.vscode-server/extensions/.ffd4746e-a339-4830-8820-328eedd33059: ms-toolsai.jupyter
[2021-08-17 22:00:54.677] [remoteagent] [info] Extracted extension to /home/wxz/.vscode-server/extensions/.1088f66a-6b94-4e19-b430-f484c4fbd270: ms-toolsai.jupyter
[2021-08-17 22:00:54.778] [remoteagent] [info] Renamed to /home/wxz/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1195043623
[2021-08-17 22:00:54.785] [remoteagent] [info] Extracting completed. ms-toolsai.jupyter
[2021-08-17 22:00:54.824] [remoteagent] [info] Extension installed successfully: ms-toolsai.jupyter
[2021-08-17 22:00:54.848] [remoteagent] [info] Rename failed because extension was installed by another source. So ignoring renaming. ms-toolsai.jupyter
[2021-08-17 22:00:54.853] [remoteagent] [info] Extracting completed. ms-toolsai.jupyter
[2021-08-17 22:00:54.873] [remoteagent] [info] Extension installed successfully: ms-toolsai.jupyter
[2021-08-17 22:00:56.855] [remoteagent] [info] Extracted extension to /home/wxz/.vscode-server/extensions/.4fda524b-30dc-4fb0-bda5-eb6c63ba1811: ms-toolsai.jupyter
[2021-08-17 22:00:56.866] [remoteagent] [info] Extracted extension to /home/wxz/.vscode-server/extensions/.6ce00bf7-f4c8-4dbd-98fe-63dcc298fc3e: ms-toolsai.jupyter
[2021-08-17 22:00:56.989] [remoteagent] [info] Rename failed because extension was installed by another source. So ignoring renaming. ms-toolsai.jupyter
[2021-08-17 22:00:56.991] [remoteagent] [info] Rename failed because extension was installed by another source. So ignoring renaming. ms-toolsai.jupyter
[2021-08-17 22:00:56.994] [remoteagent] [info] Extracting completed. ms-toolsai.jupyter
[2021-08-17 22:00:56.996] [remoteagent] [info] Extracting completed. ms-toolsai.jupyter
[2021-08-17 22:00:57.002] [remoteagent] [error] Error while installing the extension: ms-toolsai.jupyter
[2021-08-17 22:00:57.003] [remoteagent] [error] Error: Extension invalid: package.json is not a JSON file.
    at /home/wxz/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/out/vs/server/remoteExtensionHostAgent.js:116:85024
    at new Promise (<anonymous>)
    at y.parseManifest (/home/wxz/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/out/vs/server/remoteExtensionHostAgent.js:116:84919)
    at y.storeMetadata (/home/wxz/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/out/vs/server/remoteExtensionHostAgent.js:116:78790)
    at async y.saveMetadataForLocalExtension (/home/wxz/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/out/vs/server/remoteExtensionHostAgent.js:116:78451)
    at async Q.extract (/home/wxz/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/out/vs/server/remoteExtensionHostAgent.js:116:90245)
[2021-08-17 22:00:57.003] [remoteagent] [error] Failed to install extension: ms-toolsai.jupyter Extension invalid: package.json is not a JSON file.
[2021-08-17 22:00:57.057] [remoteagent] [info] Extension installed successfully: ms-toolsai.jupyter
[2021-08-17 22:00:59.042] [remoteagent] [info] Extracted extension to /home/wxz/.vscode-server/extensions/.c15a4ec7-c9fd-4b98-82cb-a83a22400c5d: ms-python.vscode-pylance
[2021-08-17 22:00:59.048] [remoteagent] [info] Extracted extension to /home/wxz/.vscode-server/extensions/.4d08432c-ffb6-4a5d-89c2-4a3a06b2d820: ms-python.vscode-pylance
[2021-08-17 22:00:59.058] [remoteagent] [info] Extracted extension to /home/wxz/.vscode-server/extensions/.48e46ada-84ac-4a3a-bbef-c40d3f7fa26b: ms-python.vscode-pylance
[2021-08-17 22:00:59.067] [remoteagent] [info] Extracted extension to /home/wxz/.vscode-server/extensions/.cb943eb7-c0d2-4f6e-8b37-22872de325da: ms-python.vscode-pylance
[2021-08-17 22:00:59.129] [remoteagent] [info] Renamed to /home/wxz/.vscode-server/extensions/ms-python.vscode-pylance-2021.8.1
[2021-08-17 22:00:59.138] [remoteagent] [info] Extracting completed. ms-python.vscode-pylance
[2021-08-17 22:00:59.184] [remoteagent] [info] Extension installed successfully: ms-python.vscode-pylance
[2021-08-17 22:00:59.353] [remoteagent] [info] Rename failed because extension was installed by another source. So ignoring renaming. ms-python.vscode-pylance
[2021-08-17 22:00:59.353] [remoteagent] [info] Rename failed because extension was installed by another source. So ignoring renaming. ms-python.vscode-pylance
[2021-08-17 22:00:59.354] [remoteagent] [info] Rename failed because extension was installed by another source. So ignoring renaming. ms-python.vscode-pylance
[2021-08-17 22:00:59.356] [remoteagent] [info] Extracting completed. ms-python.vscode-pylance
[2021-08-17 22:00:59.356] [remoteagent] [info] Extracting completed. ms-python.vscode-pylance
[2021-08-17 22:00:59.357] [remoteagent] [info] Extracting completed. ms-python.vscode-pylance
[2021-08-17 22:00:59.414] [remoteagent] [info] Extension installed successfully: ms-python.vscode-pylance
[2021-08-17 22:00:59.436] [remoteagent] [info] Extension installed successfully: ms-python.vscode-pylance
[2021-08-17 22:00:59.441] [remoteagent] [info] Extension installed successfully: ms-python.vscode-pylance
[2021-08-17 22:01:00.080] [remoteagent] [info] Extracted extension to /home/wxz/.vscode-server/extensions/.2f46ed86-18bd-4fc6-9290-ccab9a635532: ms-python.python
[2021-08-17 22:01:00.080] [remoteagent] [info] Extracted extension to /home/wxz/.vscode-server/extensions/.9082ba68-eda7-49b7-81d7-b2329efb8f92: ms-python.python
[2021-08-17 22:01:00.105] [remoteagent] [info] Extracted extension to /home/wxz/.vscode-server/extensions/.e8633d9c-527d-465f-92d9-3856e8121d36: ms-python.python
[2021-08-17 22:01:00.109] [remoteagent] [info] Extracted extension to /home/wxz/.vscode-server/extensions/.37144bc4-b665-4f42-a19d-05323eae119b: ms-python.python
[2021-08-17 22:01:00.136] [remoteagent] [info] Renamed to /home/wxz/.vscode-server/extensions/ms-python.python-2021.8.1105858891
[2021-08-17 22:01:00.146] [remoteagent] [info] Extracting completed. ms-python.python
[2021-08-17 22:01:00.162] [remoteagent] [info] Extension installed successfully: ms-python.python
[2021-08-17 22:01:00.333] [remoteagent] [info] Rename failed because extension was installed by another source. So ignoring renaming. ms-python.python
[2021-08-17 22:01:00.334] [remoteagent] [info] Rename failed because extension was installed by another source. So ignoring renaming. ms-python.python
[2021-08-17 22:01:00.336] [remoteagent] [info] Extracting completed. ms-python.python
[2021-08-17 22:01:00.338] [remoteagent] [info] Extracting completed. ms-python.python
[2021-08-17 22:01:00.340] [remoteagent] [error] Error while installing the extension: ms-python.python
[2021-08-17 22:01:00.341] [remoteagent] [error] Error: Extension invalid: package.json is not a JSON file.
    at /home/wxz/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/out/vs/server/remoteExtensionHostAgent.js:116:85024
    at new Promise (<anonymous>)
    at y.parseManifest (/home/wxz/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/out/vs/server/remoteExtensionHostAgent.js:116:84919)
    at y.storeMetadata (/home/wxz/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/out/vs/server/remoteExtensionHostAgent.js:116:78790)
    at async y.saveMetadataForLocalExtension (/home/wxz/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/out/vs/server/remoteExtensionHostAgent.js:116:78451)
    at async Q.extract (/home/wxz/.vscode-server/bin/379476f0e13988d90fab105c5c19e7abc8b1dea8/out/vs/server/remoteExtensionHostAgent.js:116:90245)
[2021-08-17 22:01:00.341] [remoteagent] [error] Failed to install extension: ms-python.python Extension invalid: package.json is not a JSON file.
[2021-08-17 22:01:00.342] [remoteagent] [info] Rename failed because extension was installed by another source. So ignoring renaming. ms-python.python
[2021-08-17 22:01:00.380] [remoteagent] [info] Extracting completed. ms-python.python
[2021-08-17 22:01:00.402] [remoteagent] [info] Extension installed successfully: ms-python.python
[2021-08-17 22:01:00.409] [remoteagent] [info] Extension installed successfully: ms-python.python
[2021-08-17 22:01:07.753] [remoteagent] [info] Installing extension: ms-python.vscode-pylance
[2021-08-17 22:01:08.123] [remoteagent] [info] Installing extension: ms-python.vscode-pylance
[2021-08-17 22:01:42.225] [remoteagent] [info] [<unknown>][f422785d][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2021-08-17 22:01:43.291] [remoteagent] [info] [<unknown>][0b29847a][ExtensionHostConnection] <130628> Extension Host Process exited with code: 0, signal: null.
[2021-08-17 22:01:43.292] [remoteagent] [info] Last EH closed, waiting before shutting down
[2021-08-17 22:01:46.230] [remoteagent] [info] Got delay-shutdown request while in shutdown timeout, delaying
[2021-08-17 22:01:46.230] [remoteagent] [info] Cancelling previous shutdown timeout
[2021-08-17 22:01:46.947] [remoteagent] [info] [<unknown>][bf97f86d][ManagementConnection] New connection established.
[2021-08-17 22:01:46.981] [remoteagent] [info] [<unknown>][05f57164][ExtensionHostConnection] New connection established.
[2021-08-17 22:01:47.017] [remoteagent] [info] [<unknown>][05f57164][ExtensionHostConnection] <132013> Launched Extension Host Process.
[2021-08-17 22:03:18.840] [remoteagent] [info] Deleted from disk ms-python.vscode-pylance /home/wxz/.vscode-server/extensions/ms-python.vscode-pylance-2021.8.1
[2021-08-17 22:03:18.841] [remoteagent] [info] Deleted from disk ms-python.vscode-pylance /home/wxz/.vscode-server/extensions/ms-python.vscode-pylance-2021.8.1
[2021-08-17 22:03:21.499] [remoteagent] [info] Extracted extension to /home/wxz/.vscode-server/extensions/.a4086dfc-2372-429e-9f62-fbb3e46f150d: ms-python.vscode-pylance
[2021-08-17 22:03:21.502] [remoteagent] [info] Extracted extension to /home/wxz/.vscode-server/extensions/.25c7e4c2-c917-4189-898a-0bd97936f3b3: ms-python.vscode-pylance
[2021-08-17 22:03:21.541] [remoteagent] [info] Renamed to /home/wxz/.vscode-server/extensions/ms-python.vscode-pylance-2021.8.1
[2021-08-17 22:03:21.546] [remoteagent] [info] Extracting completed. ms-python.vscode-pylance
[2021-08-17 22:03:21.621] [remoteagent] [info] Extension installed successfully: ms-python.vscode-pylance
[2021-08-17 22:03:21.673] [remoteagent] [info] Rename failed because extension was installed by another source. So ignoring renaming. ms-python.vscode-pylance
[2021-08-17 22:03:21.674] [remoteagent] [info] Extracting completed. ms-python.vscode-pylance
[2021-08-17 22:03:21.700] [remoteagent] [info] Extension installed successfully: ms-python.vscode-pylance
[2021-08-17 22:06:46.231] [remoteagent] [info] New EH opened, aborting shutdown
[2021-08-17 22:08:24.707] [remoteagent] [info] Installing extension: ms-azuretools.vscode-docker
[2021-08-17 22:08:25.156] [remoteagent] [info] Installing extension: ms-azuretools.vscode-docker
[2021-08-17 22:10:34.889] [remoteagent] [error] Error while preparing to install dependencies and extension packs of the extension: ms-azuretools.vscode-docker
[2021-08-17 22:10:34.894] [remoteagent] [error] Error: connect ETIMEDOUT 13.107.42.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2021-08-17 22:10:34.896] [remoteagent] [error] Failed to install extension: ms-azuretools.vscode-docker connect ETIMEDOUT 13.107.42.18:443
[2021-08-17 22:10:34.897] [remoteagent] [error] Error while preparing to install dependencies and extension packs of the extension: ms-azuretools.vscode-docker
[2021-08-17 22:10:34.898] [remoteagent] [error] Error: connect ETIMEDOUT 13.107.42.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2021-08-17 22:10:34.898] [remoteagent] [error] Failed to install extension: ms-azuretools.vscode-docker connect ETIMEDOUT 13.107.42.18:443
[2021-08-18 10:08:27.929] [remoteagent] [info] Installing extension: ms-azuretools.vscode-docker
[2021-08-18 10:08:31.125] [remoteagent] [info] Installing extension: ms-toolsai.jupyter
[2021-08-18 10:10:37.452] [remoteagent] [error] Error while preparing to install dependencies and extension packs of the extension: ms-azuretools.vscode-docker
[2021-08-18 10:10:37.457] [remoteagent] [error] Error: connect ETIMEDOUT 13.107.42.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2021-08-18 10:10:37.458] [remoteagent] [error] Failed to install extension: ms-azuretools.vscode-docker connect ETIMEDOUT 13.107.42.18:443
[2021-08-18 10:10:42.962] [remoteagent] [info] Extracted extension to /home/wxz/.vscode-server/extensions/.e31b36bb-f244-4fea-a86a-fbf63cd4da3d: ms-toolsai.jupyter
[2021-08-18 10:10:42.998] [remoteagent] [info] Renamed to /home/wxz/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1236758218
[2021-08-18 10:10:43.003] [remoteagent] [info] Extracting completed. ms-toolsai.jupyter
[2021-08-18 10:10:43.008] [remoteagent] [info] Extension installed successfully: ms-toolsai.jupyter
[2021-08-18 10:17:18.795] [remoteagent] [info] Installing extension: ms-azuretools.vscode-docker
[2021-08-18 10:19:29.928] [remoteagent] [error] Error while preparing to install dependencies and extension packs of the extension: ms-azuretools.vscode-docker
[2021-08-18 10:19:29.934] [remoteagent] [error] Error: connect ETIMEDOUT 13.107.42.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2021-08-18 10:19:29.935] [remoteagent] [error] Failed to install extension: ms-azuretools.vscode-docker connect ETIMEDOUT 13.107.42.18:443
[2021-08-18 22:08:30.673] [remoteagent] [info] Installing extension: ms-azuretools.vscode-docker
[2021-08-18 22:10:40.009] [remoteagent] [error] Error while preparing to install dependencies and extension packs of the extension: ms-azuretools.vscode-docker
[2021-08-18 22:10:40.014] [remoteagent] [error] Error: connect ETIMEDOUT 13.107.42.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2021-08-18 22:10:40.016] [remoteagent] [error] Failed to install extension: ms-azuretools.vscode-docker connect ETIMEDOUT 13.107.42.18:443
[2021-08-19 10:08:31.697] [remoteagent] [info] Installing extension: ms-azuretools.vscode-docker
[2021-08-19 10:10:42.569] [remoteagent] [error] Error while preparing to install dependencies and extension packs of the extension: ms-azuretools.vscode-docker
[2021-08-19 10:10:42.574] [remoteagent] [error] Error: connect ETIMEDOUT 13.107.42.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2021-08-19 10:10:42.576] [remoteagent] [error] Failed to install extension: ms-azuretools.vscode-docker connect ETIMEDOUT 13.107.42.18:443
[2021-08-19 19:14:01.349] [remoteagent] [info] [<unknown>][bf97f86d][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2021-08-19 19:14:02.440] [remoteagent] [info] [<unknown>][05f57164][ExtensionHostConnection] <132013> Extension Host Process exited with code: 0, signal: null.
[2021-08-19 19:14:02.440] [remoteagent] [info] Last EH closed, waiting before shutting down
[2021-08-19 19:14:12.432] [remoteagent] [info] Got delay-shutdown request while in shutdown timeout, delaying
[2021-08-19 19:14:12.432] [remoteagent] [info] Cancelling previous shutdown timeout
[2021-08-19 19:14:13.122] [remoteagent] [info] [<unknown>][fe3485a3][ManagementConnection] New connection established.
[2021-08-19 19:14:13.189] [remoteagent] [info] [<unknown>][183efb31][ExtensionHostConnection] New connection established.
[2021-08-19 19:14:13.212] [remoteagent] [info] [<unknown>][183efb31][ExtensionHostConnection] <591887> Launched Extension Host Process.
[2021-08-19 19:19:12.435] [remoteagent] [info] New EH opened, aborting shutdown
[2021-08-19 19:20:53.035] [remoteagent] [info] Installing extension: exodiusstudios.comment-anchors
[2021-08-19 19:20:53.339] [remoteagent] [info] Installing extension: ms-azuretools.vscode-docker
[2021-08-19 19:20:55.045] [remoteagent] [info] Installing extension: ms-azuretools.vscode-docker
[2021-08-19 19:23:03.305] [remoteagent] [error] Error while preparing to install dependencies and extension packs of the extension: ms-azuretools.vscode-docker
[2021-08-19 19:23:03.310] [remoteagent] [error] Error: connect ETIMEDOUT 13.107.42.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2021-08-19 19:23:03.312] [remoteagent] [error] Failed to install extension: ms-azuretools.vscode-docker connect ETIMEDOUT 13.107.42.18:443
[2021-08-19 19:23:03.401] [remoteagent] [info] Extracted extension to /home/wxz/.vscode-server/extensions/.6dbee787-978b-407e-90c9-af90fc3403ba: exodiusstudios.comment-anchors
[2021-08-19 19:23:03.407] [remoteagent] [info] Renamed to /home/wxz/.vscode-server/extensions/exodiusstudios.comment-anchors-1.9.6
[2021-08-19 19:23:03.408] [remoteagent] [info] Extracting completed. exodiusstudios.comment-anchors
[2021-08-19 19:23:03.410] [remoteagent] [info] Extension installed successfully: exodiusstudios.comment-anchors
[2021-08-19 19:23:05.351] [remoteagent] [error] Error while preparing to install dependencies and extension packs of the extension: ms-azuretools.vscode-docker
[2021-08-19 19:23:05.352] [remoteagent] [error] Error: connect ETIMEDOUT 13.107.42.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2021-08-19 19:23:05.352] [remoteagent] [error] Failed to install extension: ms-azuretools.vscode-docker connect ETIMEDOUT 13.107.42.18:443
[2021-08-19 19:33:03.738] [remoteagent] [info] Installing extension: ms-azuretools.vscode-docker
[2021-08-19 19:33:57.076] [remoteagent] [info] Installing extension: donjayamanne.githistory
[2021-08-19 19:35:14.441] [remoteagent] [error] Error while preparing to install dependencies and extension packs of the extension: ms-azuretools.vscode-docker
[2021-08-19 19:35:14.446] [remoteagent] [error] Error: connect ETIMEDOUT 13.107.42.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2021-08-19 19:35:14.447] [remoteagent] [error] Failed to install extension: ms-azuretools.vscode-docker connect ETIMEDOUT 13.107.42.18:443
[2021-08-19 19:36:07.767] [remoteagent] [info] Extracted extension to /home/wxz/.vscode-server/extensions/.72131fc1-9b41-476c-9820-c1fda2cbc462: donjayamanne.githistory
[2021-08-19 19:36:07.774] [remoteagent] [info] Renamed to /home/wxz/.vscode-server/extensions/donjayamanne.githistory-0.6.18
[2021-08-19 19:36:07.775] [remoteagent] [info] Extracting completed. donjayamanne.githistory
[2021-08-19 19:36:07.778] [remoteagent] [info] Extension installed successfully: donjayamanne.githistory
[2021-08-19 19:41:49.958] [remoteagent] [info] Installing extension: ms-azuretools.vscode-docker
[2021-08-19 19:44:00.780] [remoteagent] [error] Error while preparing to install dependencies and extension packs of the extension: ms-azuretools.vscode-docker
[2021-08-19 19:44:00.784] [remoteagent] [error] Error: connect ETIMEDOUT 13.107.42.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2021-08-19 19:44:00.785] [remoteagent] [error] Failed to install extension: ms-azuretools.vscode-docker connect ETIMEDOUT 13.107.42.18:443
</details>

Steps to Reproduce:
I can't update the extensions on the offline server quickly. I think Remote-SSH can upload the VSIX file or cached extension file just by SCP.  
Now I must: Download the VSIX files one by one > uploading by SCP > install VSIX file
My opinion: click update/install > select offline method > done automatically
1. update extension or install new extension on the remote sever 
2. waiting……
3. sometimes nothing happened

![image](https://user-images.githubusercontent.com/56864878/130061621-b6204781-c3fd-4e36-96e7-b498640c9098.png)

![image](https://user-images.githubusercontent.com/56864878/130063959-6a8467b9-ebb4-45e7-81f5-96ef2f58bf0f.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by bamurtaugh** [comment]
I think this may be tied to https://github.com/microsoft/vscode-remote-release/issues/1242.

**Comment by sandy081** [comment]
You can set the setting `remote.downloadExtensionsLocally` to `true` for extensions to be downloaded locally and install in remote server.
