### ISSUE TITLE
Installation of some extensions in WSL fails with "self signed certificate in certificate chain"

### ISSUE THREAD

**Issue by J0F3** [microsoft/vscode-remote-release#5482]
- VSCode Version: 1.59.1
- Local OS Version: Windows 10 21H1 (19043.1165)
- Remote OS Version: Ubuntu 20.04.2
- Remote Extension/Connection Type: WSL
- Logs:

Window:
[2021-08-20 10:33:25.514] [renderer1] [error] Error while installing 'ms-azuretools.vscode-docker' extension in the remote server. self signed certificate in certificate chain
[2021-08-20 10:33:25.515] [renderer1] [info] Trying to download 'ms-azuretools.vscode-docker' extension locally and install
[2021-08-20 10:33:25.551] [renderer1] [trace] RequestService#request https://ms-azuretools.gallerycdn.vsassets.io/extensions/ms-azuretools/vscode-docker/1.16.0/1629119875998/Microsoft.VisualStudio.Code.Manifest
[2021-08-20 10:33:25.777] [renderer1] [trace] RequestService#request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
[2021-08-20 10:33:25.779] [renderer1] [trace] RequestService#request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
[2021-08-20 10:33:25.946] [renderer1] [trace] ExtensionGalleryService#download ms-azuretools.vscode-docker
[2021-08-20 10:33:25.946] [renderer1] [trace] RequestService#request https://ms-azuretools.gallery.vsassets.io/_apis/public/gallery/publisher/ms-azuretools/extension/vscode-docker/1.16.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage?redirect=true&install=true
[2021-08-20 10:33:26.725] [renderer1] [error] ["Error: self signed certificate in certificate chain","    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)","    at TLSSocket.emit (events.js:315:20)","    at TLSSocket._finishInit (_tls_wrap.js:932:8)","    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)"]

Remote Server:
[2021-08-20 10:30:56.707] [remoteagent] [error] Failed to install extension: ms-azuretools.vscode-docker self signed certificate in certificate chain
[2021-08-20 10:31:10.888] [remoteagent] [trace] Started scanning user extensions
[2021-08-20 10:31:10.903] [remoteagent] [trace] Scanned user extensions: 19
[2021-08-20 10:31:11.254] [remoteagent] [trace] ExtensionManagementService#install vscode-local:/c%3A/Users/<redacted>/AppData/Local/Temp/be26a1bc-9fc5-41c6-ba41-dc2a933b9349
[2021-08-20 10:31:11.342] [remoteagent] [info] Installing extension: ms-azuretools.vscode-docker
[2021-08-20 10:31:11.342] [remoteagent] [trace] Started scanning system extensions
[2021-08-20 10:31:11.342] [remoteagent] [trace] Started scanning user extensions
[2021-08-20 10:31:11.371] [remoteagent] [trace] Scanned user extensions: 19
[2021-08-20 10:31:11.380] [remoteagent] [trace] Scanned system extensions: 31
[2021-08-20 10:31:11.380] [remoteagent] [trace] RequestService#request https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
[2021-08-20 10:31:11.380] [remoteagent] [trace] resolveShellEnv(): running (macOS/Linux)
[2021-08-20 10:31:11.436] [remoteagent] [error] Error while preparing to install dependencies and extension packs of the extension: ms-azuretools.vscode-docker
[2021-08-20 10:31:11.436] [remoteagent] [error] Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
[2021-08-20 10:31:11.436] [remoteagent] [error] Failed to install extension: ms-azuretools.vscode-docker self signed certificate in certificate chain

Steps to Reproduce:

1. Open a WSL Window
2. Install Docker extension in WSL

Does this issue occur when you try this locally?: No (only remote, in WSL.)
Does this issue occur when you try this locally and all extensions are disabled?: No

**Note that I am behind a corporate firewall which does inspect all SSL traffic!** 
So the firewall does basically a man-in-the middle and so all hosts have a certificate from an internal CA instead of the certificat of the actual host it self. However the internal CA is trusted in the WSL and the `NODE_EXTRA_CA_CERTS` environment variable is set. But it seems like the variable has no impact for VS Code during the extension installation (which is a problem). 

Interesting is also that the problem does not exist for all extensions. For Example the "docker" extension has this problem and the "Markdown All in One" extensions has not. 

For me it looks like the problem only exists when the extension has some dependencies. Because the self-singed cert error happens at: "Error while preparing to install dependencies and extension packs of the extension: ms-azuretools.vscode-docker".
When I install the "Markdown All in One" I can not see this line in the logs. The extension does also not show any dependencies in the UI where the docker extension does. So I think this is the difference:
![image](https://user-images.githubusercontent.com/12759579/130207088-ff4fc2b1-2cb7-4c6d-8b44-a730f0fb900f.png)
![image](https://user-images.githubusercontent.com/12759579/130207261-3394af39-3ec4-4462-ac90-b53c967d349b.png)

When looking at the log (above) it seems also that the extension itself is actually downloaded in Windows (not in the WSL) :
2021-08-20 10:33:25.514] [renderer1] [error] Error while installing 'ms-azuretools.vscode-docker' extension in the remote server. self signed certificate in certificate chain
[2021-08-20 10:33:25.515] [renderer1] [info] Trying to download 'ms-azuretools.vscode-docker' extension locally and install

But the dependencies will then get installed in WSL again which does not work. Probably because the `NODE_EXTRA_CA_CERTS` variable is no honored by the VS Code remote server and therefore the certs form the internal CA are not trusted.

So how can we get the VS code server to trust the certs of the internal CA? 
Why does the `NODE_EXTRA_CA_CERTS`  env variable seems do not have any effect on the VS code server?

**Comment by chrmarti** [comment]
@sandy081 Could dependencies also be downloaded locally? (Has this changed?)

**Comment by sandy081** [comment]
If `remote.downloadExtensionsLocally` setting is set then extension (including dependencies) is downloaded locally and installed on remote otherwise download happens on remote. But there was a bug in last milestone that offline installation (installing through VSIXs) is broken and I fixed it recently - https://github.com/microsoft/vscode/issues/130962

@J0F3 Do you have above setting set to true? If so, can you please try with our latest insiders and see if it is fixed.

**Comment by J0F3** [comment]
@sandy081 I had tried it with `remote.downloadExtensionsLocally` set to `false`  and `true` but I made not really any difference.

But I just test it now with VS Code Insiders and there it seems to be fixed. (with `remote.downloadExtensionsLocally` set to `true`)

It looks like the step where in the stable version the error happens is now skipped and so the installation finishes successfully:
![image](https://user-images.githubusercontent.com/12759579/130508048-8fea5669-60c7-48e4-a16e-9fb601493d78.png)


When installing manually form an VSIX file there is still an error about the self-singed cert in the log but is seems not anymore blocking the installation. So seems also to be fine:
![image](https://user-images.githubusercontent.com/12759579/130508171-c2b967c6-31ce-4581-a42d-8a5f7e974c32.png)


Just let me know if you need more information or if I should test something else.

Thx!
