### ISSUE TITLE
Can't connect to remote machine via ssh

### ISSUE THREAD

**Issue by rkube** [microsoft/vscode-remote-release#5484]
Hi,
vscode won't connect to a certain remote host via ssh, here is the log:
```
[12:32:26.222] Log Level: 2
[12:32:26.225] remote-ssh@0.65.7
[12:32:26.225] darwin x64
[12:32:26.226] SSH Resolver called for "ssh-remote+portal", attempt 1
[12:32:26.226] "remote.SSH.useLocalServer": true
[12:32:26.226] "remote.SSH.path": undefined
[12:32:26.226] "remote.SSH.configFile": undefined
[12:32:26.226] "remote.SSH.useFlock": true
[12:32:26.227] "remote.SSH.lockfilesInTmp": false
[12:32:26.227] "remote.SSH.localServerDownload": auto
[12:32:26.227] "remote.SSH.remoteServerListenOnSocket": false
[12:32:26.227] "remote.SSH.showLoginTerminal": true
[12:32:26.227] "remote.SSH.defaultExtensions": []
[12:32:26.227] "remote.SSH.loglevel": 2
[12:32:26.227] SSH Resolver called for host: portal
[12:32:26.227] Setting up SSH remote "portal"
[12:32:26.230] Acquiring local install lock: /var/folders/2p/kw9s71xx0fl6c0_t44p9lb580000gn/T/vscode-remote-ssh-portal-install.lock
[12:32:26.244] Looking for existing server data file at /Users/ralph/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-portal-3866c3553be8b268c8a7f8c0482c0c0177aa8bfa-0.65.7/data.json
[12:32:26.245] Found local server running: {"remoteListeningOn":{"port":42369},"osReleaseId":"centos","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/41903","platform":"linux","connectionToken":"11a11111-111a-11a1-1aa1-11aa11aa1a11","pid":47217,"ipcHandlePath":"/var/folders/2p/kw9s71xx0fl6c0_t44p9lb580000gn/T/vscode-ssh-askpass-df8ade24bfaf1b0cd8a58500a1c30744f8f05414.sock","socksPort":53890,"startupTime":1629476830957}
[12:32:26.253] Found running server - short-circuiting install
[12:32:26.254] Starting forwarding server. localPort 53991 -> socksPort 53890 -> remotePort 42369
[12:32:26.255] Forwarding server listening on 53991
[12:32:26.255] Waiting for ssh tunnel to be ready
[12:32:26.257] [Forwarding server 53991] Got connection 0
[12:32:26.258] Tunneled 42369 to local port 53991
[12:32:26.258] Resolved "ssh-remote+portal" to "127.0.0.1:53991"
[12:32:26.263] ------




[12:32:26.276] Failed to set up socket for dynamic port forward to remote port 42369: Socket closed. Is the remote port correct?
[12:32:26.382] [Forwarding server 53991] Got connection 1
[12:32:26.402] Failed to set up socket for dynamic port forward to remote port 42369: Socket closed. Is the remote port correct?
[12:41:17.398] Picking SSH host
[12:41:18.605] Selected cori
```

  Logging into that host using a separate ssh session is fine. I can also log in just fine to a different remote ssh host.
How can I approach debugging this issue?

**Comment by roblourens** [comment]
We think we have a connection but the remote host is closing it, it's not clear why. You could try running the command "Kill VS Code Server on Host" to start over fresh. You could also try disabling the setting `useLocalServer` as a workaround

**Comment by rkube** [comment]
I deleted the `.vscode-server` directory on the host and disabled `useLocalServer`. When connecting again the message `Waiting for serevr log` repeats a lot and I get this error in a logfile on the host:
```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'minimist'
Require stack:
- /u/rkube/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/out/vs/server/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at start (/u/rkube/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/out/vs/server/main.js:1:287)
    at Object.<anonymous> (/u/rkube/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/out/vs/server/main.js:12:707)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/u/rkube/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/out/vs/server/main.js'
  ]
}```

**Comment by roblourens** [comment]
> Error: Cannot find module 'minimist'

That's pretty interesting. It kind of sounds like the installation is incomplete or corrupted. 

> The host I'm connecting to is locked down

Is there some antivirus or corporate policy that might be messing with the installation?

**Comment by ABMorley** [comment]
I get this with Windows 10 (not in the WSL subsystem) as the remote host (I see you're using MacOS, or at least Darwin). What I find fixes it is deleting both `~/.vscode-server` _and_ the contents of the temporary directory (which on Windows is `~/AppData/Local/Temp`)

I don't know if that's your problem or not. And I haven't worked out what causes it.
