### ISSUE TITLE
Error while installing 'ms-python.python' extension in the remote server. self signed certificate in certificate chain

### ISSUE THREAD

**Issue by focusmatters** [microsoft/vscode-remote-release#5487]
- VSCode Version: 1.59.1
- Local OS Version: win10
- Remote OS Version: centos
- Remote Extension/Connection Type: SSH
- Logs: [error] Error while installing 'ms-python.python' extension in the remote server. self signed certificate in certificate chain
[2021-08-22 01:03:11.629] [renderer3] [info] Trying to download 'ms-python.python' extension locally and install
[2021-08-22 01:03:49.611] [renderer3] [error] ["Error: self signed certificate in certificate chain","    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)","    at TLSSocket.emit (events.js:315:20)","    at TLSSocket._finishInit (_tls_wrap.js:932:8)","    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)"]
[2021-08-22 01:03:49.803] [renderer3] [error] ["Error: self signed certificate in certificate chain","    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)","    at TLSSocket.emit (events.js:315:20)","    at TLSSocket._finishInit (_tls_wrap.js:932:8)","    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)"]

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
Looks like https://github.com/microsoft/vscode-remote-release/issues/5482. /fyi @sandy081
