### ISSUE TITLE
macOS 12 Update causes Operation timed out with SSH with same exact settings

### ISSUE THREAD

**Issue by CarlosAMendoza** [microsoft/vscode-remote-release#5498]
- VSCode Version: 1.59.1
- Local OS Version: macOS 12.0 Beta
- Remote OS Version: Ubuntu 18
- Remote Extension/Connection Type: SSH
- Logs:
[19:10:36.932] SSH Resolver called for "ssh-remote+myServerDomain", attempt 1
[19:10:36.933] "remote.SSH.useLocalServer": false
[19:10:36.933] "remote.SSH.showLoginTerminal": false
[19:10:36.934] "remote.SSH.remotePlatform": {"myServerDomain":"linux"}
[19:10:36.934] "remote.SSH.path": undefined
[19:10:36.934] "remote.SSH.configFile": undefined
[19:10:36.935] "remote.SSH.useFlock": true
[19:10:36.935] "remote.SSH.lockfilesInTmp": false
[19:10:36.935] "remote.SSH.localServerDownload": auto
[19:10:36.936] "remote.SSH.remoteServerListenOnSocket": false
[19:10:36.936] "remote.SSH.showLoginTerminal": false
[19:10:36.936] "remote.SSH.defaultExtensions": []
[19:10:36.936] "remote.SSH.loglevel": 2
[19:10:36.937] SSH Resolver called for host: myServerDomain
[19:10:36.937] Setting up SSH remote "myServerDomain"
[19:10:36.951] Using commit id "3866c3553be8b268c8a7f8c0482c0c0177aa8bfa" and quality "stable" for server
[19:10:36.954] Install and start server if needed
[19:10:36.959] PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/usr/local/mysql/bin
[19:10:36.960] Checking ssh with "ssh -V"
[19:10:36.967] > OpenSSH_8.6p1, LibreSSL 2.7.3

[19:10:36.969] Running script with connection command: ssh -T -D 56108 -o ConnectTimeout=15 'myServerDomain' bash
[19:10:52.400] > ssh: connect to host myServerDomain port 22: Operation timed out
[19:10:52.400] Got some output, clearing connection timeout
[19:10:52.643] "install" terminal command done
[19:10:52.644] Install terminal quit with output: ssh: connect to host myServerDomain port 22: Operation timed out
[19:10:52.644] Received install output: ssh: connect to host myServerDomain port 22: Operation timed out
[19:10:52.645] Resolver error: Error: The operation timed out
	at Function.Offline (/Users/carlos/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.8.18181/out/extension.js:1:397062)
	at /Users/carlos/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.8.18181/out/extension.js:1:394793
	at Object.t.handleInstallOutput (/Users/carlos/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.8.18181/out/extension.js:1:394990)
	at Object.t.tryInstall (/Users/carlos/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.8.18181/out/extension.js:1:489191)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/carlos/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.8.18181/out/extension.js:1:452987
	at async Object.t.withShowDetailsEvent (/Users/carlos/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.8.18181/out/extension.js:1:456337)
	at async Object.t.resolve (/Users/carlos/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.8.18181/out/extension.js:1:454066)
	at async /Users/carlos/.vscode/extensions/ms-vscode-remote.remote-ssh-nightly-2021.8.18181/out/extension.js:1:526846
[19:10:52.649] ------

Steps to Reproduce:

1. SSH into configuration
2. wait
3. times out

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

I have the same exact version of vscode working on windows, I can ssh from the terminal perfectly fine, and before I update to macOS 12 on this computer with these settings were working perfectly fine. I need to have the beta version of macOS and I need to remote into the server so changing OS is not an option.

**Comment by CarlosAMendoza** [comment]
Seems this issue was related to some permission errors on the server. It only occurred on this version of macOS but it was not due to the extension.
