### ISSUE TITLE
SSH: ETIMEDOUT when installing ms-python extension 

### ISSUE THREAD

**Issue by CyrilOtheninGirard** [microsoft/vscode-remote-release#5510]
- VSCode Version: 1.59.1
- Local OS Version: Windows 10 version 1909 (OS Build 18363.1679) 
- Remote OS Version: Ubuntu 18.04.5 LTS for x86_64
- Remote Extension/Connection Type: SSH

**Steps to Reproduce**:
1. Place remote computer behind a firewall that blocks direct connections to the Internet
2. Click on Microsoft Python extension, then on "Install in SSH: xxxx"

```
[2021-08-25 20:18:37.863] [remoteagent] [info] [10.0.2.15][b3d60106][ManagementConnection] New connection established.
[2021-08-25 20:18:37.879] [remoteagent] [info] [10.0.2.15][b877e47c][ExtensionHostConnection] New connection established.
[2021-08-25 20:18:37.900] [remoteagent] [info] [10.0.2.15][b877e47c][ExtensionHostConnection] <2022> Launched Extension Host Process.
[2021-08-25 20:19:11.094] [remoteagent] [info] Installing extension: ms-python.python
[2021-08-25 20:19:11.986] [remoteagent] [info] Installing extension: ms-python.vscode-pylance
[2021-08-25 20:19:12.122] [remoteagent] [info] Installing extension: ms-toolsai.jupyter
[2021-08-25 20:21:20.538] [remoteagent] [error] Error while preparing to install dependencies and extension packs of the extension: ms-python.python
[2021-08-25 20:21:20.540] [remoteagent] [error] Error: connect ETIMEDOUT 13.107.42.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2021-08-25 20:21:20.541] [remoteagent] [error] Failed to install extension: ms-python.python connect ETIMEDOUT 13.107.42.18:443
[2021-08-25 20:21:22.586] [remoteagent] [error] Error while preparing to install dependencies and extension packs of the extension: ms-python.vscode-pylance
[2021-08-25 20:21:22.586] [remoteagent] [error] Error: connect ETIMEDOUT 13.107.42.18:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2021-08-25 20:21:22.586] [remoteagent] [error] Failed to install extension: ms-python.vscode-pylance connect ETIMEDOUT 13.107.42.18:443
[2021-08-25 20:21:22.636] [remoteagent] [info] Deleted from disk ms-toolsai.jupyter /home/idemia/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1236758218
[2021-08-25 20:21:24.348] [remoteagent] [info] Extracted extension to /home/idemia/.vscode-server/extensions/.d98c2a0b-46ad-422a-926c-620e6112b60f: ms-toolsai.jupyter
[2021-08-25 20:21:24.365] [remoteagent] [info] Renamed to /home/idemia/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1236758218
[2021-08-25 20:21:24.370] [remoteagent] [info] Extracting completed. ms-toolsai.jupyter
[2021-08-25 20:21:24.376] [remoteagent] [info] Extension installed successfully: ms-toolsai.jupyter
```
### Note 1:
I have the same issue when I try to install the python extension by running the **Remote: Install local Extensions in: SSH: remote-machine** command. 
Even if I check **ms-python.python** + **ms-python.vscode-pylance** + **ms-toolsai.jupyter**.

I assumed that this command was falling back on the **remote.downloadExtensionsLocally** (which I checked anyway), which:
1. FIRST downloads the extensions on the local machine 
2. THEN copy them to the remote using SCP 
3. BEFORE installing them.

**Am I wrong ?**
 
### Note 2:
I do not have that issue when remotely installing other extensions, like **clangd** :
```
[2021-08-25 20:49:21.895] [remoteagent] [info] Installing extension: llvm-vs-code-extensions.vscode-clangd
[2021-08-25 20:51:33.382] [remoteagent] [info] Extracted extension to /home/idemia/.vscode-server/extensions/.bd055d86-9ce2-409d-80dd-24580bed13f4: llvm-vs-code-extensions.vscode-clangd
[2021-08-25 20:51:33.400] [remoteagent] [info] Renamed to /home/idemia/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.13
[2021-08-25 20:51:33.402] [remoteagent] [info] Extracting completed. llvm-vs-code-extensions.vscode-clangd
[2021-08-25 20:51:33.408] [remoteagent] [info] Extension installed successfully: llvm-vs-code-extensions.vscode-clangd
```
**BUT** I always have a delay of more than 180s between the 1st and 2nd log lines, whatever the size of the extension may be. **Why ?**

Does this issue occur when you try this locally?: No

**Comment by bamurtaugh** [comment]
@CyrilOtheninGirard And you install the non-Python extensions, like clangd, using the same process you tried with Python?

@AkshayRoyal you're having the same issue where all extensions besides Python are installing properly when behind a firewall/in a situation where your remote doesn't have direct Internet access?
