### ISSUE TITLE
Remote-SSH: plus '+' symbol not supported for ssh config Host specification

### ISSUE THREAD

**Issue by Fedma123** [microsoft/vscode-remote-release#5525]
# Summary
Connecting via Remote-SSH to a host that includes a plus '+' symbol  in the `Host` specification of the ssh config file causes the extension to fail.

Example ssh config causing the issue:
```
Host +myhost
    Hostname myhostname
    User root
``` 
To work around the issue remove the '+' symbol.

# Information
- Version: 1.59.1
- Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
- Date: 2021-08-19T11:54:37.513Z
- Electron: 13.1.7
- Chrome: 91.0.4472.124
- Node.js: 14.16.0
- V8: 9.1.269.36-electron.0
- OS: Linux x64 5.10.60-1-MANJARO
- Remote OS: Linux 5.10.17-v7l+ armv7l GNU/Linux

<details>
<summary>Log</summary>

```
[18:29:26.212] Log Level: 2
[18:29:26.215] remote-ssh@0.65.7
[18:29:26.215] linux x64
[18:29:26.216] SSH Resolver called for "ssh-remote++raspberry", attempt 1
[18:29:26.217] "remote.SSH.useLocalServer": true
[18:29:26.217] "remote.SSH.path": undefined
[18:29:26.217] "remote.SSH.configFile": undefined
[18:29:26.217] "remote.SSH.useFlock": true
[18:29:26.218] "remote.SSH.lockfilesInTmp": false
[18:29:26.218] "remote.SSH.localServerDownload": auto
[18:29:26.218] "remote.SSH.remoteServerListenOnSocket": false
[18:29:26.218] "remote.SSH.showLoginTerminal": false
[18:29:26.218] "remote.SSH.defaultExtensions": []
[18:29:26.219] "remote.SSH.loglevel": 2
[18:29:26.219] SSH Resolver called for host: 
[18:29:26.219] Setting up SSH remote ""
[18:29:26.223] Acquiring local install lock: /tmp/vscode-remote-ssh--install.lock
[18:29:26.245] Looking for existing server data file at /home/<redacted>/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host--3866c3553be8b268c8a7f8c0482c0c0177aa8bfa-0.65.7/data.json
[18:29:26.246] Using commit id "3866c3553be8b268c8a7f8c0482c0c0177aa8bfa" and quality "stable" for server
[18:29:26.251] Install and start server if needed
[18:29:26.261] PATH: /home/<redacted>/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin
[18:29:26.261] Checking ssh with "ssh -V"
[18:29:26.290] > OpenSSH_8.7p1, OpenSSL 1.1.1l  24 Aug 2021

[18:29:26.296] askpass server listening on /run/user/1000/vscode-ssh-askpass-cbf49ada0544803645a625af100bf1b7c5915597.sock
[18:29:26.296] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-ac6a6f268bcad8a7e9ab32d1b2177f693f62a0eb.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","41063","-o","ConnectTimeout=15"],"dataFilePath":"/home/<redacted>/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host--3866c3553be8b268c8a7f8c0482c0c0177aa8bfa-0.65.7/data.json"}
[18:29:26.296] Local server env: {"DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/opt/visual-studio-code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-cbf49ada0544803645a625af100bf1b7c5915597.sock"}
[18:29:26.302] Spawned 20557
[18:29:26.434] > local-server-1> Spawned ssh, pid=20565
[18:29:26.437] stderr> usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface]
[18:29:26.437] stderr>            [-b bind_address] [-c cipher_spec] [-D [bind_address:]port]
[18:29:26.437] stderr>            [-E log_file] [-e escape_char] [-F configfile] [-I pkcs11]
[18:29:26.437] stderr>            [-i identity_file] [-J [user@]host[:port]] [-L address]
[18:29:26.437] stderr>            [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
[18:29:26.437] stderr>            [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
[18:29:26.437] stderr>            [-w local_tun[:remote_tun]] destination [command]
[18:29:26.438] > local-server-1> ssh child died, shutting down
[18:29:26.443] Local server exit: 0
[18:29:26.444] Received install output: local-server-1> Spawned ssh, pid=20565
usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-B bind_interface]
           [-b bind_address] [-c cipher_spec] [-D [bind_address:]port]
           [-E log_file] [-e escape_char] [-F configfile] [-I pkcs11]
           [-i identity_file] [-J [user@]host[:port]] [-L address]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-Q query_option] [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] destination [command]
local-server-1> ssh child died, shutting down

[18:29:26.445] Failed to parse remote port from server output
[18:29:26.446] Resolver error: Error: 
	at Function.Create (/home/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:64659)
	at Object.t.handleInstallOutput (/home/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:63302)
	at Object.e [as tryInstallWithLocalServer] (/home/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:387573)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:294473
	at async Object.t.withShowDetailsEvent (/home/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:406463)
	at async /home/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:386112
	at async E (/home/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:382710)
	at async Object.t.resolveWithLocalServer (/home/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:385728)
	at async Object.t.resolve (/home/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:295870)
	at async /home/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:127:110656
[18:29:26.454] ------
```
</details>

**Comment by bamurtaugh** [comment]
@roblourens Is this expected?

If yes, is there a list of characters users should avoid in Host/hostnames/usernames that we could document (and perhaps link to if the extension fails to connect)?
