### ISSUE TITLE
Connection Timed out while I can connect with PowerShell

### ISSUE THREAD

**Issue by Aviortheking** [microsoft/vscode-remote-release#5555]
- VSCode Version: 1.61.0-insider
- Local OS Version: Windows 11 21H2 22000.176
- Remote OS Version: Raspbian 10
- Remote Extension/Connection Type: SSH
- Logs:

```
[16:32:25.596] Log Level: 2
[16:32:25.597] remote-ssh@0.65.7
[16:32:25.597] win32 x64
[16:32:25.598] SSH Resolver called for "ssh-remote+pi", attempt 1
[16:32:25.599] "remote.SSH.useLocalServer": false
[16:32:25.599] "remote.SSH.showLoginTerminal": false
[16:32:25.600] "remote.SSH.remotePlatform": {"xxx":"linux","xxx":"linux","xxx":"linux"}
[16:32:25.600] "remote.SSH.path": undefined
[16:32:25.600] "remote.SSH.configFile": undefined
[16:32:25.600] "remote.SSH.useFlock": true
[16:32:25.601] "remote.SSH.lockfilesInTmp": false
[16:32:25.601] "remote.SSH.localServerDownload": auto
[16:32:25.601] "remote.SSH.remoteServerListenOnSocket": false
[16:32:25.602] "remote.SSH.showLoginTerminal": false
[16:32:25.602] "remote.SSH.defaultExtensions": []
[16:32:25.602] "remote.SSH.loglevel": 2
[16:32:25.603] SSH Resolver called for host: pi
[16:32:25.603] Setting up SSH remote "pi"
[16:32:25.609] Using commit id "bb9491d9f2c65510226dcc920a6efbf6501d5943" and quality "insider" for server
[16:32:25.614] Install and start server if needed
[16:32:26.839] Checking ssh with "ssh -V"
[16:32:27.943] > Ope
[16:32:27.944] > nSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[16:32:27.948] Running script with connection command: ssh -T -D 58722 pi bash
[16:32:27.950] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[16:33:29.965] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (c:\Users\micro\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64785)
	at Timeout._onTimeout (c:\Users\micro\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:413911)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[16:33:29.974] ------
```

Config

```
Host pi
        HostName 192.168.1.xx
        IdentityFile ~/.ssh/key
        User username
        Port 2201
```

Steps to Reproduce:

1. IDK

NOTE: I tried running the command `ssh -T -D 58722 pi bash` on the Windows Terminal's PowerShell and I was able to connect to the remote and run commands like normally

I also tried to:
- set `remote.SSH.useLocalServer` to `False`
- set `remote.SSH.connectTimeout` to `60`
- set `terminal.integrated.windowsEnableConpty` to `false`

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by MrPaulAR** [comment]
Having the same issues with all my SSH servers.  I have full connectivity from powershell by the hostname configured in the ssh config file.

Below is one of the sample failures.

```
[10:23:18.937] Setting up SSH remote "ubuntu-docker"
[10:23:18.943] Using commit id "bb9491d9f2c65510226dcc920a6efbf6501d5943" and quality "insider" for server
[10:23:18.947] Install and start server if needed
[10:23:18.958] Checking ssh with "ssh -V"
[10:23:19.162] > OpenSSH_for_Windows_8.1p1, LibreSSL 3
[10:23:19.162] > .0.2

[10:23:19.168] Running script with connection command: ssh -T -D 64995 "ubuntu-docker" bash
[10:23:19.169] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:23:36.177] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (c:\Users\who\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64785)
	at Timeout._onTimeout (c:\Users\who\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:413911)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[10:23:36.180] ------
```

**Comment by Dradows** [comment]
So do I.

`
[00:09:54.105] Running script with connection command: ssh -T -D 2327 "123.XX.XX.XX" bash
[00:09:54.107] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[00:10:11.107] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (c:\Users\Dradows\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64785)
	at Timeout._onTimeout (c:\Users\Dradows\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:413911)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
`

**Comment by plwalsh** [comment]
Same problem and error message here. Can't connect to any servers.

Does anyone know a way to roll back to the previous Insiders release?

**Comment by plwalsh** [comment]
Thanks for the tip. Unfortunately, though, I don't have any other PC with a prior install directory. Like one person said in that linked issue, a rollback function for times like these would be so incredibly useful.

**Comment by foxli180** [comment]
> Same problem and error message here. Can't connect to any servers.
> 
> Does anyone know a way to roll back to the previous Insiders release?
https://az764295.vo.msecnd.net/insider/a3fce6207d9364afcfccaa55efc82ff8a392fdd5/VSCode-win32-x64-1.61.0-insider.zip 
https://az764295.vo.msecnd.net/insider/a3fce6207d9364afcfccaa55efc82ff8a392fdd5/VSCodeSetup-x64-1.61.0-insider.exe
change a3fce6207d9364afcfccaa55efc82ff8a392fdd5 to the commit same as your server in linux host which should in ~/.vscode-server-insiders/bin

**Comment by Firsh** [comment]
Me too, uninstalling rn. Gonna go back to Stable.

**Comment by gordon0001** [comment]
Same here on all linux and windows servers after I updated to 1.61-insiders today. I'm on Win11 22449.1000.
Connection on cmd and Powershell works fine.

**Comment by FrastSerg** [comment]
Have checked remote connections:
Linux -> Linux: OK
Linux -> Mac:  OK
Windows -> Linux: OK
Windows ->Mac:   OK

Failed all connections to Windows:
Linux -> Windows
Windows -> Windows

with the same error
`[13:21:55.416] Log Level: 2
[13:21:55.418] remote-ssh@0.65.7
[13:21:55.418] linux x64
[13:21:55.419] SSH Resolver called for "ssh-remote+serg-cmd", attempt 1
[13:21:55.419] "remote.SSH.useLocalServer": true
[13:21:55.420] "remote.SSH.path": undefined
[13:21:55.420] "remote.SSH.configFile": undefined
[13:21:55.420] "remote.SSH.useFlock": true
[13:21:55.420] "remote.SSH.lockfilesInTmp": true
[13:21:55.420] "remote.SSH.localServerDownload": auto
[13:21:55.421] "remote.SSH.remoteServerListenOnSocket": false
[13:21:55.421] "remote.SSH.showLoginTerminal": false
[13:21:55.421] "remote.SSH.defaultExtensions": []
[13:21:55.421] "remote.SSH.loglevel": 2
[13:21:55.421] SSH Resolver called for host: serg-cmd
[13:21:55.421] Setting up SSH remote "serg-cmd"
[13:21:55.424] Acquiring local install lock: /tmp/vscode-remote-ssh-serg-cmd-install.lock
[13:21:55.444] Looking for existing server data file at /home/serg/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-serg-cmd-e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff-0.65.7/data.json
[13:21:55.444] Using commit id "e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff" and quality "stable" for server
[13:21:55.448] Install and start server if needed
[13:21:55.454] PATH: /home/serg/.local/bin:/home/serg/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[13:21:55.454] Checking ssh with "ssh -V"
[13:21:55.466] > OpenSSH_7.6p1 Ubuntu-4ubuntu0.5, OpenSSL 1.0.2n  7 Dec 2017

[13:21:55.473] askpass server listening on /run/user/1000/vscode-ssh-askpass-7bb72959fac6749436c24ae1c11296f559bc41a1.sock
[13:21:55.473] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-30474679dc112ab1f9401562c9376c201ae24e93.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","38177","serg-cmd"],"dataFilePath":"/home/serg/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-serg-cmd-e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff-0.65.7/data.json"}
[13:21:55.473] Local server env: {"DISPLAY":":1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/serg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_MAIN":"/home/serg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-7bb72959fac6749436c24ae1c11296f559bc41a1.sock"}
[13:21:55.479] Spawned 12455
[13:21:55.600] > local-server-1> Spawned ssh, pid=12463
[13:21:55.605] stderr> OpenSSH_7.6p1 Ubuntu-4ubuntu0.5, OpenSSL 1.0.2n  7 Dec 2017
[13:21:56.000] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:Zb708FWFQ8sEpgX/gWCq0K/eGhvVq7QAZ/LGLgqV3BU
[13:21:58.126] stderr> Authenticated to serg-cmd.dev.corp ([192.168.2.80]:2222).
[13:21:58.797] > Microsoft Windows [Version 10.0.19043.985]
> (c) Microsoft Corporation. All rights reserved.
[13:21:58.797] > 
> dev\sergey.u@SERG-CMD C:\Users\sergey.u>
[13:21:58.803] > echo 'ready: 41686be46a8e'
[13:21:58.803] > 'ready: 41686be46a8e'
> 
> dev\sergey.u@SERG-CMD C:\Users\sergey.u>
[13:21:58.838] > uname -rsv
[13:21:58.870] > CYGWIN_NT-10.0 3.2.0(0.340/5/3) 2021-03-29 08:42
[13:21:58.882] > 
[13:21:58.883] > dev\sergey.u@SERG-CMD C:\Users\sergey.u>
[13:22:12.480] Terminating local server
[13:22:12.482] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/home/serg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:64785)
	at Timeout._onTimeout (/home/serg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:264709)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[13:22:12.500] ------




[13:22:12.502] Local server exit: 15
`
![Screenshot from 2021-09-10 13-49-15](https://user-images.githubusercontent.com/36641539/132844203-be511d8f-cd0c-4ba0-ba1d-819fa5d408cf.png)
![Untitled](https://user-images.githubusercontent.com/36641539/132844750-db5530db-c691-44c4-901f-432fcaa30539.png)

Remote-SSH extension pack v0.65.7 on all clients

**Comment by FrastSerg** [comment]
> .................................................
> [13:21:58.126] stderr> Authenticated to serg-cmd.dev.corp ([192.168.2.80]:2222).
> [13:21:58.797] > Microsoft Windows [Version 10.0.19043.985]
> 
> (c) Microsoft Corporation. All rights reserved.
> [13:21:58.797] >
> dev\sergey.u@SERG-CMD C:\Users\sergey.u>
> [13:21:58.803] > echo 'ready: 41686be46a8e'
> [13:21:58.803] > 'ready: 41686be46a8e'
> dev\sergey.u@SERG-CMD C:\Users\sergey.u>
**> [13:21:58.838] > uname -rsv
> [13:21:58.870] > CYGWIN_NT-10.0 3.2.0(0.340/5/3) 2021-03-29 08:42**
> [13:21:58.882] >
> [13:21:58.883] > dev\sergey.u@SERG-CMD C:\Users\sergey.u>
> [13:22:12.480] Terminating local server
> [13:22:12.482] Resolver error: Error: Connecting with SSH timed out
> .................................................


Probably it was bad idea to use 'uname' command to detect os :(
 'uname.exe' has been renamed to 'uname.ex_' temporary and all stay working fine.

Config parameters:
`"remote.SSH.remotePlatform": {
    "serg-cmd": "windows"
  }
`
This parameter does not in any way affect the ability of VSCode to detect or override type of the remote OS.

**Comment by Fydon** [comment]
@FrastSerg The error being experience by the original poster and others like me is specifically to do with vscode-insider and is affecting Linux remote hosts (possibly all remote hosts as it doesn't reach the remote host). If you are experiencing an issue with the stable build of vscode, it may be worth opening a separate issue as it may have a different cause, like uname that you mention.

**Comment by MrPaulAR** [comment]
The 1.61.0 insiders has fixed this issue for me.  Tried on multiple Ubuntu, CentOS, & Fedora SSH remotes.

**Comment by lustremedia** [comment]
> 
> 
> The 1.61.0 insiders has fixed this issue for me. Tried on multiple Ubuntu, CentOS, & Fedora SSH remotes.

1.61.0 does not fix the issue, see https://github.com/microsoft/vscode-remote-release/issues/5559

**Comment by lustremedia** [comment]
Ok Insiders 1.61.0 on a later commit hash fixes the issue. No version increase. This hash fixed it for me:
![grafik](https://user-images.githubusercontent.com/1240374/133037029-2ac8d824-d2cb-4f4e-b987-a237a6e8dfcc.png)

**Comment by bamurtaugh** [comment]
Thanks all for reporting. Believe this was fixed with https://github.com/microsoft/vscode/issues/132519, so closing, but please let me know if there are any persisting issues.
