### ISSUE TITLE
SSH remote connection times out on vscode insiders 1.61.0

### ISSUE THREAD

**Issue by lustremedia** [microsoft/vscode-remote-release#5559]
- VSCode Version: 1.61 Insider
- Local OS Version: Windows_NT x64 
- Remote OS Version: Debian Linux
- Remote Extension/Connection Type: SSH/Docker/WSL

Version: 1.61.0-insider
Commit: 34861b8c8aa76b517f203743ad5b5d72ef5fcd81
Date: 2021-09-08T05:17:18.073Z

Steps to Reproduce:

1. Issue is very similar to this ticket here, but none of the suggested solutions work: https://github.com/microsoft/vscode-remote-release/issues/4206
2. I can ssh into my client without problem
3. Since ever I updated Insiders to the latest version, this stopped working

- Logs:
```
[15:00:57.071] Log Level: 1
[15:00:57.080] remote-ssh@0.65.7
[15:00:57.080] win32 x64
[15:00:57.081] SSH Resolver called for "ssh-remote+node_vue", attempt 1
[15:00:57.081] "remote.SSH.useLocalServer": false
[15:00:57.081] "remote.SSH.showLoginTerminal": false
[15:00:57.081] "remote.SSH.remotePlatform": {"name1":"linux","name2":"linux","name3":"linux","name4":"linux","name5":"linux"}
[15:00:57.081] "remote.SSH.path": undefined
[15:00:57.082] "remote.SSH.configFile": C:\Users\mengerto\.ssh\config
[15:00:57.082] "remote.SSH.useFlock": false
[15:00:57.082] "remote.SSH.lockfilesInTmp": false
[15:00:57.082] "remote.SSH.localServerDownload": auto
[15:00:57.082] "remote.SSH.remoteServerListenOnSocket": false
[15:00:57.082] "remote.SSH.showLoginTerminal": false
[15:00:57.082] "remote.SSH.defaultExtensions": []
[15:00:57.082] "remote.SSH.loglevel": 1
[15:00:57.083] SSH Resolver called for host: node_vue
[15:00:57.083] Setting up SSH remote "node_vue"
[15:00:57.105] Using commit id "34861b8c8aa76b517f203743ad5b5d72ef5fcd81" and quality "insider" for server
[15:00:57.109] Install and start server if needed
[15:00:57.116] Checking ssh with "ssh -V"
[15:00:57.189] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[15:00:57.194] Using SSH config file "C:\Users\user\.ssh\config"
[15:00:57.195] Running script with connection command: ssh -T -D 1025 -F "C:\Users\user\.ssh\config" "node_vue" bash
[15:00:57.198] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:01:59.199] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (c:\Users\user\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64785)
	at Timeout._onTimeout (c:\Users\user\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:413911)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[15:01:59.202] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Timeout","exitCodeLabel":""},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":62119,"timing.preSshTime":117,"timing.scriptTime":62002}}
[15:01:59.204] ------
```

**Comment by lustremedia** [comment]
Ok this is a duplicate of this issue: https://github.com/microsoft/vscode-remote-release/issues/5555 seems like a bug in the latest Insiders!

**Comment by lustremedia** [comment]
A later 1.61.0 commit hash fixes the issue for me!
![grafik](https://user-images.githubusercontent.com/1240374/133037345-11c82d0f-56ad-4e02-ac00-9d86d5368235.png)
