### ISSUE TITLE
Unrelated .ssh/config sections are improperly rewritten when adding a host

### ISSUE THREAD

**Issue by timothyb89** [microsoft/vscode-remote-release#5562]
- VSCode Version: 1.60.0
  ```
  Version: 1.60.0 (user setup)
  Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
  Date: 2021-09-01T10:41:52.311Z
  Electron: 13.1.8
  Chrome: 91.0.4472.164
  Node.js: 14.16.0
  V8: 9.1.269.39-electron.0
  OS: Windows_NT x64 10.0.19042
  ```
- Local OS Version: Windows 10 Pro 20H2 (also occurs on macOS)
- Remote OS Version: n/a
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. Start with an empty `~/.ssh/config` and no configured remote SSH targets
2. Add an unrelated directive to `~/.ssh/config` like the following:
   ```
   Host foo
       ProxyCommand "C:\foo bar\baz.exe" "arg" "arg" "arg"
   ```
3. In VS Code, from "SSH Targets" in the Remote Explorer sidebar, click the "+" to add a new host
4. At the prompt, enter any valid SSH command (does not need to be related to the above config directive), e.g. `ssh foo@example.com`
5. Select `~/.ssh/config` from the list and press enter to update the file
6. Check `~/.ssh/config` and notice the contents have been rewritten:
   ```
   Host foo
       ProxyCommand "C:\foo bar\baz.exe "arg" "arg" "arg""

   Host example.com
       HostName example.com
       User foo
   ```

   The `ProxyCommand` has now been improperly quoted: the first argument had its ending quote removed, additional arguments remain quoted, but the entire line has been quoted (resulting in invalid nested quotes). All `ProxyCommand` lines in the file will be rewritten regardless of whether or not they are related to the host we added (or any Remote - SSH host, for that matter).
7. If the `ProxyCommand` applies to the host we just added, the Remote - SSH connection will fail:
   ![image](https://user-images.githubusercontent.com/3459954/132768606-b60e4d25-c5d2-4be3-a89d-ebd367f1110a.png)

   For context, due to the improper quoting, it's attempting to run the entire quoted string as a command with no args, rather than a command + arguments as expected.

   <details><summary>Logs</summary>
   
   ```
   [16:03:23.626] Log Level: 2
   [16:03:23.629] remote-ssh@0.65.7
   [16:03:23.630] win32 x64
   [16:03:23.650] SSH Resolver called for "ssh-remote+node000.foo.example.com", attempt 1
   [16:03:23.651] "remote.SSH.useLocalServer": false
   [16:03:23.651] "remote.SSH.showLoginTerminal": false
   [16:03:23.651] "remote.SSH.remotePlatform": {"node000.foo.example.com":"macOS"}
   [16:03:23.652] "remote.SSH.path": undefined
   [16:03:23.652] "remote.SSH.configFile": undefined
   [16:03:23.652] "remote.SSH.useFlock": true
   [16:03:23.652] "remote.SSH.lockfilesInTmp": false
   [16:03:23.653] "remote.SSH.localServerDownload": auto
   [16:03:23.653] "remote.SSH.remoteServerListenOnSocket": false
   [16:03:23.653] "remote.SSH.showLoginTerminal": false
   [16:03:23.653] "remote.SSH.defaultExtensions": []
   [16:03:23.654] "remote.SSH.loglevel": 2
   [16:03:23.654] SSH Resolver called for host: node000.foo.example.com
   [16:03:23.654] Setting up SSH remote "node000.foo.example.com"
   [16:03:23.679] Using commit id "e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff" and quality "stable" for server
   [16:03:23.684] Install and start server if needed
   [16:03:23.692] Checking ssh with "ssh -V"
   [16:03:23.737] > OpenSSH_for_Windows_8
   [16:03:23.737] > .1p1, LibreSSL 3.0.2
   
   [16:03:23.742] Running script with connection command: ssh -T -D 52281 "node000.foo.example.com" bash
   [16:03:23.744] Terminal shell path: C:\WINDOWS\System32\cmd.exe
   [16:03:24.022] > ]0;C:\WINDOWS\System32\cmd.exe
   [16:03:24.023] Got some output, clearing connection timeout
   [16:03:24.035] > CreateProcessW failed error:2
   > posix_spawnp: No such file or directory
   [16:03:24.067] > The process tried to write to a nonexistent pipe.
   [16:03:25.322] "install" terminal command done
   [16:03:25.323] Install terminal quit with output: The process tried to write to a nonexistent pipe.
   [16:03:25.323] Received install output: The process tried to write to a nonexistent pipe.
   [16:03:25.324] Resolver error: Error: The process tried to write to a nonexistent pipe
   	at Function.Offline (c:\Users\Tim\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:64710)
   	at c:\Users\Tim\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:62260
   	at Object.t.handleInstallOutput (c:\Users\Tim\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:62638)
   	at Object.t.tryInstall (c:\Users\Tim\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:415135)
   	at processTicksAndRejections (internal/process/task_queues.js:93:5)
   	at async c:\Users\Tim\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:294918
   	at async Object.t.withShowDetailsEvent (c:\Users\Tim\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:406463)
   	at async Object.t.resolve (c:\Users\Tim\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:1:295994)
   	at async c:\Users\Tim\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.7\out\extension.js:127:110656
   [16:03:25.330] ------
   ```
   
   </details>
   
I also tried moving my `ProxyCommand` directives to an included file, unfortunately due to #5449 the extension  just copies the included text back into the file and then corrupts the lines anyway (though, the included file itself is left untouched).

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes (all disabled except for Remote - SSH and Remote - SSH: Editing Configuration Files)

**Comment by roblourens** [comment]
If you feel like looking at this @tanhakabir, it would be a bug in the ssh config parsing library we use https://github.com/cyjake/ssh-config

**Comment by weinand** [comment]
After installing the "Nightly" version of the SSH extension, the problem is indeed fixed.

I noticed that now unnecessary quotes are removed, e.g. the following "unrelated section" 
```
Host foo
    ProxyCommand "C:\foo bar\baz.exe" "arg" "foo bar" "arg"
```
becomes:
```
Host foo
    ProxyCommand "C:\foo bar\baz.exe" arg "foo bar" arg
```

**Comment by tanhakabir** [comment]
@weinand that's expected. We don't adhere to keep the config exactly the same but we want to ensure we write it back into the config file with the same expected result when trying to connect to those entries
