### ISSUE TITLE
Cannot etablish connection to <Your Server>

### ISSUE THREAD

**Issue by Meng-Zhaoru** [microsoft/vscode-remote-release#5579]
[11:06:26.974] Log Level: 2
[11:06:26.975] remote-ssh@0.65.7
[11:06:26.975] darwin arm64
[11:06:26.975] SSH Resolver called for "ssh-remote+csl-kh1250-08.cselabs.umn.edu", attempt 1
[11:06:26.975] "remote.SSH.useLocalServer": false
[11:06:26.976] "remote.SSH.showLoginTerminal": true
[11:06:26.976] "remote.SSH.remotePlatform": {}
[11:06:26.976] "remote.SSH.path": undefined
[11:06:26.976] "remote.SSH.configFile": undefined
[11:06:26.976] "remote.SSH.useFlock": true
[11:06:26.976] "remote.SSH.lockfilesInTmp": false
[11:06:26.976] "remote.SSH.localServerDownload": auto
[11:06:26.976] "remote.SSH.remoteServerListenOnSocket": false
[11:06:26.976] "remote.SSH.showLoginTerminal": true
[11:06:26.976] "remote.SSH.defaultExtensions": []
[11:06:26.976] "remote.SSH.loglevel": 2
[11:06:26.976] SSH Resolver called for host: csl-kh1250-08.cselabs.umn.edu
[11:06:26.976] Setting up SSH remote "csl-kh1250-08.cselabs.umn.edu"
[11:06:26.985] Using commit id "e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff" and quality "stable" for server
[11:06:26.987] Install and start server if needed
[11:06:32.546] PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[11:06:32.546] Checking ssh with "ssh -V"
[11:06:32.553] > OpenSSH_8.1p1, LibreSSL 2.7.3

[11:06:32.555] Running script with connection command: ssh -T -D 55121 -o ConnectTimeout=15 'csl-kh1250-08.cselabs.umn.edu' bash
[11:06:32.742] > /Users/zhaorumeng/.ssh/config line 7: garbage at end of line; "csel-kh1250-12.cselabs.umn.edu".
[11:06:32.742] Got some output, clearing connection timeout
[11:06:33.001] "install" terminal command done
[11:06:33.005] Install terminal quit with output: /Users/zhaorumeng/.ssh/config line 7: garbage at end of line; "csel-kh1250-12.cselabs.umn.edu".
[11:06:33.005] Received install output: /Users/zhaorumeng/.ssh/config line 7: garbage at end of line; "csel-kh1250-12.cselabs.umn.edu".
[11:06:33.006] Failed to parse remote port from server output
[11:06:33.006] Resolver error: Error: 
	at Function.Create (/Users/zhaorumeng/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:64659)
	at Object.t.handleInstallOutput (/Users/zhaorumeng/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:63302)
	at Object.t.tryInstall (/Users/zhaorumeng/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:415135)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/zhaorumeng/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:294918
	at async Object.t.withShowDetailsEvent (/Users/zhaorumeng/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:406463)
	at async Object.t.resolve (/Users/zhaorumeng/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:1:295994)
	at async /Users/zhaorumeng/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.7/out/extension.js:127:110656
[11:06:33.009] ------

I tried to kill the VS Code server on Host, but it didn't work either. Does anybody have the same problem?

**Comment by Luther-Sparks** [comment]
I have the same problem :(
I could use remote-ssh normally until I re-installed my server system.
In my case, I managed to get into the server system successfully but somehow remote-ssh just won't work.However, I can still use ssh to connect to the server :(
Anybody help

**Comment by PwndDepot** [comment]
I had this issue last week. Stopped working after last week’s Insiders update. The update today seemed to fix it.

**Comment by bamurtaugh** [comment]
Thanks for filing @Meng-Zhaoru. Could you please share additional details: version of VS Code and Remote-SSH, local and remote OS?

@Luther-Sparks could you please share your full logs and the info I mention above too?

@PwndDepot thanks for the info - there was a separate connection issue last week that was resolved that may have been the issue.
