### ISSUE TITLE
root connecting normally, user not connecting 

### ISSUE THREAD

**Issue by antonio24073** [microsoft/vscode-remote-release#5621]
- VSCode Version: 1.60.1
- Local OS Version: Ubuntu 20.04.3 LTS
- Remote OS Version: Debian 10 buster
- Remote Extension/Connection Type: SSH
- Logs:
[12:45:16.905] Failed to parse remote port from server output
[12:45:16.906] Terminating local server
[12:45:16.908] Resolver error: Error: 
	at Function.Create (/home/antonio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:397041)
	at Object.t.handleInstallOutput (/home/antonio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:395684)
	at Object.e [as tryInstallWithLocalServer] (/home/antonio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:435292)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/antonio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:452665
	at async Object.t.withShowDetailsEvent (/home/antonio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:456460)
	at async /home/antonio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:433816
	at async C (/home/antonio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:430392)
	at async Object.t.resolveWithLocalServer (/home/antonio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:433431)
	at async Object.t.resolve (/home/antonio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:454065)
	at async /home/antonio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:526942
[12:45:16.922] ------

Steps to Reproduce:
1. install normally desktop and server
2. it works
2. reinstall server SO
3. in the desktop: ssh-keygen -t rsa
4. in the server: cat id_rsa.pub > .ssh/authorized_keys2
5. access with root normally without password with vscode remote (OK)
6. access with user SSH with password by command line (OK)
7. try to access with user SSH with vscode remote (not working)
8. this happens in 2 servers

I tried to delete /root/.vscode-server
- same problem: root connecting normally, user not connecting 

I tried uninstall vscode remote desktop and do:
cd ~/.vscode/extensions
rm -Rf ms-vscode-remote.remote*
- same problem: root connecting normally, user not connecting

**Comment by antonio24073** [comment]
the problem was simple: the 2 servers had root permissions to the home folder. I created by myself from root before add the user but this message isn't clear: "Failed to parse remote port from server output". It turns a simple problem in a big problem.
Thank you

**Comment by tanhakabir** [comment]
Sorry about the slow response! It sounds like you've figured out how to fix it for yourself? Sorry about the message, we generally take error messages provided to us by either your local machine or your remote machine and relay those back to you.
