### ISSUE TITLE
Error when trying to connect to a Vagrant machine (osX, Vagrant, VirtualBox, running NixOS)

### ISSUE THREAD

**Issue by maelp** [microsoft/vscode-remote-release#5627]
- VSCode Version: 1.60.2
- Local OS Version: osX 11.6
- Remote OS Version: NixOS 21.05
- Remote Extension/Connection Type: SSH in a VirtualBox
- Logs:

```
[09:54:36.570] Log Level: 2
[09:54:36.572] remote-ssh@0.65.8
[09:54:36.572] darwin x64
[09:54:36.573] SSH Resolver called for "ssh-remote+nixbox", attempt 1
[09:54:36.574] "remote.SSH.useLocalServer": true
[09:54:36.575] "remote.SSH.path": undefined
[09:54:36.575] "remote.SSH.configFile": undefined
[09:54:36.575] "remote.SSH.useFlock": true
[09:54:36.576] "remote.SSH.lockfilesInTmp": false
[09:54:36.576] "remote.SSH.localServerDownload": auto
[09:54:36.576] "remote.SSH.remoteServerListenOnSocket": false
[09:54:36.576] "remote.SSH.showLoginTerminal": false
[09:54:36.577] "remote.SSH.defaultExtensions": []
[09:54:36.577] "remote.SSH.loglevel": 2
[09:54:36.577] SSH Resolver called for host: nixbox
[09:54:36.580] Setting up SSH remote "nixbox"
[09:54:36.583] Acquiring local install lock: /var/folders/6d/tgjjs7m13yngmk287mk9cv9h0000gp/T/vscode-remote-ssh-4f8010d9-install.lock
[09:54:36.615] Looking for existing server data file at /Users/primet/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-4f8010d9-7f6ab5485bbc008386c4386d08766667e155244e-0.65.8/data.json
[09:54:36.616] Using commit id "7f6ab5485bbc008386c4386d08766667e155244e" and quality "stable" for server
[09:54:36.618] Install and start server if needed
[09:54:36.623] PATH: [redacted]
[09:54:36.623] Checking ssh with "ssh -V"
[09:54:36.644] > OpenSSH_8.1p1, LibreSSL 2.7.3

[09:54:36.648] askpass server listening on /var/folders/6d/tgjjs7m13yngmk287mk9cv9h0000gp/T/vscode-ssh-askpass-808c1a9b0554145c32ce90582ac23749038cbd52.sock
[09:54:36.648] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/6d/tgjjs7m13yngmk287mk9cv9h0000gp/T/vscode-ssh-askpass-deaea4136026e18cb102a4b8727076b528a128c0.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","49611","-o","ConnectTimeout=15","nixbox"],"dataFilePath":"/Users/primet/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-4f8010d9-7f6ab5485bbc008386c4386d08766667e155244e-0.65.8/data.json"}
[09:54:36.648] Local server env: {"DISPLAY":"/private/tmp/com.apple.launchd.ZnhgSAgoOf/org.macosforge.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/primet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/primet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/6d/tgjjs7m13yngmk287mk9cv9h0000gp/T/vscode-ssh-askpass-808c1a9b0554145c32ce90582ac23749038cbd52.sock"}
[09:54:36.649] Spawned 87444
[09:54:36.774] > local-server-1> Spawned ssh, pid=87461
[09:54:36.778] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[09:54:36.799] stderr> debug1: Server host key: ssh-ed25519 SHA256:kLhnngXQN0OgFWgsw0NHJyP2acfPsu9rJeFjVZqBdNM
[09:54:36.799] stderr> Warning: Permanently added '[127.0.0.1]:2222' (ED25519) to the list of known hosts.
[09:54:36.834] stderr> Authenticated to 127.0.0.1 ([127.0.0.1]:2222).
[09:54:36.862] > ready: f0981e7440b0
[09:54:36.865] > Linux 5.10.66 #1-NixOS SMP Thu Sep 16 10:51:23 UTC 2021
[09:54:36.865] Platform: linux
[09:54:36.881] > f0981e7440b0: running
[09:54:36.896] > Warning: Can't find libstdc++.so or ldconfig, can't verify libstdc++ version
[09:54:36.904] > Acquiring lock on /home/vagrant/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/vscode-remote-lock.vagrant.7f6ab5485bbc008386c4386d08766667e155244e
[09:54:36.912] > Found existing installation at /home/vagrant/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e...
[09:54:36.912] > Checking /home/vagrant/.vscode-server/.7f6ab5485bbc008386c4386d08766667e155244e.log and /home/vagrant/.vscode-server/.7f6ab5485bbc008386c4386d08766667e155244e.pid for a running server
[09:54:36.915] > Looking for server with pid: 15913
[09:54:36.934] > Starting server with command... /home/vagrant/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/server.sh --start-server --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0  &> "/home/vagrant/.vscode-server/.7f6ab5485bbc008386c4386d08766667e155244e.log" < /dev/null
[09:54:36.935] > printenv:
[09:54:36.943] >     SSH_CONNECTION=10.0.2.2 49612 10.0.2.15 22
>     LANG=en_US.UTF-8
>     EDITOR=nano
>     MOZ_PLUGIN_PATH=/home/vagrant/.nix-profile/lib/mozilla/plugins:/etc/profiles/per-user/vagrant/lib/mozilla/plugins:/nix/var/nix/profiles/default/lib/mozilla/plugins:/run/current-system/sw/lib/mozilla/plugins
>     KDEDIRS=/home/vagrant/.nix-profile:/etc/profiles/per-user/vagrant:/nix/var/nix/profiles/default:/run/current-system/sw
>     NO_AT_BRIDGE=1
>     QTWEBKIT_PLUGIN_PATH=/home/vagrant/.nix-profile/lib/mozilla/plugins/:/etc/profiles/per-user/vagrant/lib/mozilla/plugins/:/nix/var/nix/profiles/default/lib/mozilla/plugins/:/run/current-system/sw/lib/mozilla/plugins/
>     XDG_SESSION_ID=21
>     USER=vagrant
>     PAGER=less -R
>     TZDIR=/etc/zoneinfo
>     LIBEXEC_PATH=/home/vagrant/.nix-profile/lib/libexec:/etc/profiles/per-user/vagrant/lib/libexec:/nix/var/nix/profiles/default/lib/libexec:/run/current-system/sw/lib/libexec
>     NIX_PROFILES=/run/current-system/sw /nix/var/nix/profiles/default /etc/profiles/per-user/vagrant /home/vagrant/.nix-profile
>     NIX_PATH=nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels
>     PWD=/home/vagrant
>     SSH_ASKPASS=
>     HOME=/home/vagrant
>     SSH_CLIENT=10.0.2.2 49612 22
>     XDG_SESSION_TYPE=tty
>     GTK_PATH=/home/vagrant/.nix-profile/lib/gtk-2.0:/home/vagrant/.nix-profile/lib/gtk-3.0:/etc/profiles/per-user/vagrant/lib/gtk-2.0:/etc/profiles/per-user/vagrant/lib/gtk-3.0:/nix/var/nix/profiles/default/lib/gtk-2.0:/nix/var/nix/profiles/default/lib/gtk-3.0:/run/current-system/sw/lib/gtk-2.0:/run/current-system/sw/lib/gtk-3.0
>     XDG_DATA_DIRS=/nix/store/al8l354rvnrp0kczr9iv0a22imjki8lv-desktops/share:/home/vagrant/.nix-profile/share:/etc/profiles/per-user/vagrant/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share
>     TERMINFO_DIRS=/home/vagrant/.nix-profile/share/terminfo:/etc/profiles/per-user/vagrant/share/terminfo:/nix/var/nix/profiles/default/share/terminfo:/run/current-system/sw/share/terminfo
>     __NIXOS_SET_ENVIRONMENT_DONE=1
>     QT_PLUGIN_PATH=/home/vagrant/.nix-profile/lib/qt4/plugins:/home/vagrant/.nix-profile/lib/kde4/plugins:/etc/profiles/per-user/vagrant/lib/qt4/plugins:/etc/profiles/per-user/vagrant/lib/kde4/plugins:/nix/var/nix/profiles/default/lib/qt4/plugins:/nix/var/nix/profiles/default/lib/kde4/plugins:/run/current-system/sw/lib/qt4/plugins:/run/current-system/sw/lib/kde4/plugins
>     NIX_USER_PROFILE_DIR=/nix/var/nix/profiles/per-user/vagrant
>     SHELL=/run/current-system/sw/bin/bash
>     TERM=dumb
>     XDG_SESSION_CLASS=user
>     SHLVL=2
>     LOCALE_ARCHIVE=/run/current-system/sw/lib/locale/locale-archive
>     VSCODE_AGENT_FOLDER=/home/vagrant/.vscode-server
>     LOGNAME=vagrant
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
>     NIXPKGS_CONFIG=/etc/nix/nixpkgs-config.nix
>     XDG_RUNTIME_DIR=/run/user/1000
>     XDG_CONFIG_DIRS=/etc/xdg:/home/vagrant/.nix-profile/etc/xdg:/etc/profiles/per-user/vagrant/etc/xdg:/nix/var/nix/profiles/default/etc/xdg:/run/current-system/sw/etc/xdg
>     PATH=/run/wrappers/bin:/home/vagrant/.nix-profile/bin:/etc/profiles/per-user/vagrant/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
>     INFOPATH=/home/vagrant/.nix-profile/info:/home/vagrant/.nix-profile/share/info:/etc/profiles/per-user/vagrant/info:/etc/profiles/per-user/vagrant/share/info:/nix/var/nix/profiles/default/info:/nix/var/nix/profiles/default/share/info:/run/current-system/sw/info:/run/current-system/sw/share/info
>     XCURSOR_PATH=/home/vagrant/.icons:/home/vagrant/.local/share/icons:/home/vagrant/.nix-profile/share/icons:/home/vagrant/.nix-profile/share/pixmaps:/etc/profiles/per-user/vagrant/share/icons:/etc/profiles/per-user/vagrant/share/pixmaps:/nix/var/nix/profiles/default/share/icons:/nix/var/nix/profiles/default/share/pixmaps:/run/current-system/sw/share/icons:/run/current-system/sw/share/pixmaps
>     __ETC_PROFILE_DONE=1
>     _=/run/current-system/sw/bin/printenv
[09:54:36.950] > Spawned remote server: 16927
[09:54:36.971] > Waiting for server log...
[09:54:37.024] > Waiting for server log...
[...]
[09:54:43.999] > Waiting for server log...
[09:54:44.035] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
[09:54:44.035] > * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[09:54:44.062] > Server did not start successfully. Full server log at /home/vagrant/.vscode-server/.7f6ab5485bbc008386c4386d08766667e155244e.log >>>
[09:54:44.064] > /home/vagrant/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/server.sh: line 12: /home/vagrant/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/node: No such file or directory
[09:54:44.064] > <<< End of server log
> f0981e7440b0: start
> exitCode==32==
[09:54:44.065] > listeningOn====
> osReleaseId==nixos==
> arch==x86_64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==7090==
> f0981e7440b0: end
[09:54:44.065] Received install output: 
exitCode==32==listeningOn====
osReleaseId==nixos==
arch==x86_64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==7090==

[09:54:44.065] Terminating local server
[09:54:44.069] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (/Users/primet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:396975)
	at u (/Users/primet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:391298)
	at Object.t.handleInstallOutput (/Users/primet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:395717)
	at Object.e [as tryInstallWithLocalServer] (/Users/primet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:435292)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/primet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:452665
	at async Object.t.withShowDetailsEvent (/Users/primet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:456460)
	at async /Users/primet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:433816
	at async C (/Users/primet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:430392)
	at async Object.t.resolveWithLocalServer (/Users/primet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:433431)
	at async Object.t.resolve (/Users/primet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:454065)
	at async /Users/primet/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:526942
[09:54:44.071] Local server exit: 15
[09:54:44.079] ------
```

Steps to Reproduce:

1. create VirtualBox / Vagrant / NixOS machine
2. add it to my SSH config
3. use Remote SSH extension to log in
4. it tries to install the software and fail

I then log in my machine, go in the `~/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e`, and if I try to run the local `node` binary it fails (perhaps it is a binary for a different OS?).

If I remove this binary and install node system-wide on my VirtualBox instance (`nix-env -iA nixos.nodejs`) then run `./server.sh` it works, and VSCode can then connect locally

So I assume it is either because VSCode is downloading the package for the wrong architecture (how to change this?) or because there is a bug in the package?

**Comment by maelp** [comment]
Here is the mentioned log

```
$ cat ~/.vscode-server/bin/.7f6ab5485bbc008386c4386d08766667e155244e.log
/home/vagrant/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/server.sh: line 12: /home/vagrant/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/node: No such file or directory
```

there is the file:

```
$ ls -lah /home/vagrant/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/node
-rwxr-xr-x 1 vagrant vagrant 71M Sep 22 12:02 /home/vagrant/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/node
```

here is the header (ELF file)

```
$ head -c 64 node | xxd
00000000: 7f45 4c46 0201 0103 0000 0000 0000 0000  .ELF............
00000010: 0200 3e00 0100 0000 a394 9600 0000 0000  ..>.............
00000020: 4000 0000 0000 0000 8030 6704 0000 0000  @........0g.....
00000030: 0000 0000 4000 3800 0a00 4000 2700 2600  ....@.8...@.'.&.
```

but it does not seem to be runnable on NixOS (not sure why the error is "No such file or directory"):

```
$ ./node
-bash: ./node: No such file or directory
```

**Comment by maelp** [comment]
And when looking at the file

```
$ file node
node: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=c30982e8224bcd8b307b63f48132d7dd96e1a12b, with debug_info, not stripped
```

**Comment by maelp** [comment]
It might perhaps be related to this bug?
https://discourse.nixos.org/t/no-such-file-of-directory-when-trying-to-execute-binary-file/6150/2

**Comment by maelp** [comment]
As a reference, this works

```bash
# log in the VirtualBox
vagrant ssh

# go in the vscode-server extension path
cd ~/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e

# follow https://nixos.wiki/wiki/Packaging/Binaries
nix-shell -p binutils stdenv wget dpkg nix-index stdenv.cc
patchelf --print-interpreter node
# this outputs /lib64/ld-linux-x86-64.so.2
patchelf \
 --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" \
 node
# retrieve other libraries
patchelf --print-needed node
# [many libraries]
ldd node | grep "not found"
# libstdc++.so.6 => not found

nix repl '<nixpkgs>'
nix-repl> with pkgs; lib.makeLibraryPath [ stdenv.cc.cc.lib ]
# "/nix/store/50msfhkz5wbyk8i78pjv3y9lxdrp7dlm-gcc-10.3.0-lib/lib"

patchelf --set-interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" --set-rpath /nix/store/50msfhkz5wbyk8i78pjv3y9lxdrp7dlm-gcc-10.3.0-lib/lib node

./node
# it works
```

so I guess I'd need a way to run this script after the vscode-server has been downloaded and installed, and before it tries to run the `server.sh` script, is that possible?

**Comment by maelp** [comment]
(I'm not sure where to find the code of the extension in order to check whether it is possible to change the script)

**Comment by maelp** [comment]
Here is an article reviewing the issue, so I can close it
[https://nixos.wiki/wiki/Vscode#Remote_SSH](https://nixos.wiki/wiki/Vscode#Remote_SSH)

**Comment by maelp** [comment]
Seems a duplicate of https://github.com/microsoft/vscode-remote-release/issues/648
