### ISSUE TITLE
Resolver error: Error: The process tried to write to a nonexistent pipe

### ISSUE THREAD

**Issue by arekgotfryd** [microsoft/vscode-remote-release#5640]
- VSCode Version:
```
1.60.2
7f6ab5485bbc008386c4386d08766667e155244e
x64
```
- Local OS Version:
```
Edition: Windows 10 Enterprise
Version: 20H2
OS Build: 19042.1237
```
- Remote OS Version:
```
Edition: Windows 10 Pro
Version: 21H1
OS Build: 19043.1237
```
- Remote Extension/Connection Type: 
```
SSH
```
- Logs:
```
[22:15:28.230] Log Level: 1
[22:15:28.239] remote-ssh@0.65.8
[22:15:28.239] win32 x64
[22:15:28.241] SSH Resolver called for "ssh-remote+uk-w10-li-ssa01.syncdi1.us.syncsort.com", attempt 1
[22:15:28.242] "remote.SSH.useLocalServer": false
[22:15:28.242] "remote.SSH.showLoginTerminal": false
[22:15:28.243] "remote.SSH.remotePlatform": {"remotehostname":"windows"}
[22:15:28.243] "remote.SSH.path": C:\Program Files\Git\usr\bin\ssh.exe
[22:15:28.243] "remote.SSH.configFile": C:\Users\User\.ssh\config
[22:15:28.243] "remote.SSH.useFlock": true
[22:15:28.243] "remote.SSH.lockfilesInTmp": false
[22:15:28.244] "remote.SSH.localServerDownload": auto
[22:15:28.244] "remote.SSH.remoteServerListenOnSocket": false
[22:15:28.244] "remote.SSH.showLoginTerminal": false
[22:15:28.244] "remote.SSH.defaultExtensions": []
[22:15:28.244] "remote.SSH.loglevel": 1
[22:15:28.245] SSH Resolver called for host: uk-host.com
[22:15:28.245] Setting up SSH remote "uk-host.com"
[22:15:28.272] Using commit id "7f6ab5485bbc008386c4386d08766667e155244e" and quality "stable" for server
[22:15:28.277] Install and start server if needed
[22:15:31.210] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[22:15:31.350] > OpenSSH_8.7p1, OpenSSL 1.1.1k  25 Mar 2021

[22:15:31.355] Using SSH config file "C:\Users\User\.ssh\config"
[22:15:31.355] Remote command length: 6017/8192 characters
[22:15:31.355] Running script with connection command: "C:\Program Files\Git\usr\bin\ssh.exe" -T -D 5450 -F "C:\Users\User\.ssh\config" "uk-host.com" powershell
[22:15:31.359] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[22:15:34.058] "install" terminal received data: "[2J[m[H]0;C:\WINDOWS\System32\cmd.exe[?25h"
[22:15:34.060] Got some output, clearing connection timeout
[22:15:34.070] "install" terminal received data: "COMPANYINC+Name.Surname@uk-host.com's password
:[K[1C"
[22:15:36.806] "install" terminal received data: "[25l[HSYNCSORTINC+Name.Surname@uk-host.com's password:[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[1;83H[?25h"
[22:15:36.807] Showing password prompt
[22:15:46.574] Got password response
[22:15:46.574] "install" wrote data to terminal: "*************"
[22:15:46.597] "install" terminal received data: ""
[22:15:46.666] "install" terminal received data: "Permission denied, please try again."
[22:15:46.685] "install" terminal received data: "COMPANYINC+Name.Surname@uk-host.com's password: "
[22:15:46.686] Showing password prompt
[22:15:48.293] Got password response
[22:15:48.293] "install" wrote data to terminal: "*******************"
[22:15:48.313] "install" terminal received data: ""
[22:15:48.385] "install" terminal received data: "Permission denied, please try again."
[22:15:48.404] "install" terminal received data: "COMPANYINC+Name.Surname@uk-host.com's password: "
[22:15:48.405] Showing password prompt
[22:15:49.456] Got password response
[22:15:49.456] "install" wrote data to terminal: "*******************"
[22:15:49.479] "install" terminal received data: ""
[22:15:49.558] "install" terminal received data: "COMPANYINC+Name.Surname@uk-host.com: Permission denied (publickey,password,keyboard-interactive)."
[22:15:49.565] "install" terminal received data: "The process tried to write to a nonexistent pipe."
[22:15:50.924] "install" terminal command done
[22:15:50.925] Install terminal quit with output: The process tried to write to a nonexistent pipe.
[22:15:50.925] Received install output: The process tried to write to a nonexistent pipe.
[22:15:50.926] Stopped parsing output early. Remaining text: The process tried to write to a nonexistent pipe.
[22:15:50.928] Resolver error: Error: The process tried to write to a nonexistent pipe
	at Function.Offline (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:397092)
	at c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:394642
	at Object.t.handleInstallOutput (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:395020)
	at Object.t.tryInstall (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:489314)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:453110
	at async Object.t.withShowDetailsEvent (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:456460)
	at async Object.t.resolve (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:454189)
	at async c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:526942
[22:15:50.932] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"1","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"0","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"OfflineError","exitCodeLabel":""},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":22687,"timing.preSshTime":3118,"timing.scriptTime":19567}}
[22:15:50.934] ------
```
Steps to Reproduce:

1. Open Vs Code 
2. Connect to existing remote

Does this issue occur when you try this locally?: Yes?
Does this issue occur when you try this locally and all extensions are disabled?: Yes?

I just want to add that I was able to successfully connect with ssh client (outside of vscode) from local to remote.

**Comment by vanderhoff** [comment]
I have opened the same bug report but with more log output as requested. #5740

**Comment by tanhakabir** [comment]
I'll close this issue as it's linked from the new one you've already created!
