### ISSUE TITLE
Extensions are not installed when configured in devcontainer.json

### ISSUE THREAD

**Issue by Kiolali** [microsoft/vscode-remote-release#5665]
- VSCode Version: 1.60.2  (Remote - Containers v0.194.3)
- Local OS Version: Window 10
- Remote OS Version: mcr.microsoft.com/vscode/devcontainers/cpp:0-debian-11
- Remote Extension/Connection Type: Docker
- Logs:  exhost.log:
```
[2021-10-01 15:56:23.320] [exthost] [info] extension host started
[2021-10-01 15:56:23.324] [exthost] [info] Skipping acquiring lock for c:\Users\xxx\AppData\Roaming\Code\User\workspaceStorage\6fc84cd211c7d63d932d0555e6b4e391.
[2021-10-01 15:56:23.436] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2021-10-01 15:56:23.436] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/xxx/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/microsoft-authentication/dist/extension.js
[2021-10-01 15:56:23.462] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-10-01 15:56:23.462] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/xxx/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/debug-auto-launch/dist/extension
[2021-10-01 15:56:23.470] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-10-01 15:56:23.470] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/xxx/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/git/dist/main
[2021-10-01 15:56:23.510] [exthost] [info] ExtensionService#_doActivateExtension ms-vsliveshare.vsliveshare {"startup":true,"extensionId":{"value":"ms-vsliveshare.vsliveshare","_lower":"ms-vsliveshare.vsliveshare"},"activationEvent":"*"}
[2021-10-01 15:56:23.510] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/xxx/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.4836/out/prod/extension-prod
[2021-10-01 15:56:23.704] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers {"startup":true,"extensionId":{"value":"ms-vscode-remote.remote-containers","_lower":"ms-vscode-remote.remote-containers"},"activationEvent":"workspaceContains:.devcontainer/devcontainer.json"}
[2021-10-01 15:56:23.705] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/xxx/.vscode/extensions/ms-vscode-remote.remote-containers-0.194.3/dist/extension/extension
[2021-10-01 15:56:24.368] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2021-10-01 15:56:24.369] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/xxx/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/extension.js
[2021-10-01 15:56:24.622] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":false,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-10-01 15:56:24.623] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/xxx/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/github/dist/extension.js
[2021-10-01 15:56:24.957] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":false,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"onAuthenticationRequest:github"}
[2021-10-01 15:56:24.957] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/xxx/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/github-authentication/dist/extension.js
[2021-10-01 15:56:33.430] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":false,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"onStartupFinished"}
[2021-10-01 15:56:33.431] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/xxx/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/emmet/dist/node/emmetNodeMain
[2021-10-01 15:56:33.465] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
[2021-10-01 15:56:33.465] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/xxx/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2021-10-01 15:56:33.478] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl-recommender {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-wsl-recommender","_lower":"ms-vscode-remote.remote-wsl-recommender"},"activationEvent":"onStartupFinished"}
[2021-10-01 15:56:33.478] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/xxx/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode-remote.remote-wsl-recommender/dist/extension.js
[2021-10-01 15:58:21.700] [exthost] [info] extension host terminating: renderer closed the socket
[2021-10-01 15:58:21.724] [exthost] [error] Activating extension ms-vsliveshare.vsliveshare failed due to an error:
[2021-10-01 15:58:21.724] [exthost] [error] Canceled: Canceled
	at Object.n [as canceled] (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:5:1157)
	at c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:8805
	at Array.forEach (<anonymous>)
	at i.dispose (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:8753)
	at E.terminate (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:682)
	at a (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:113:32208)
	at Socket.<anonymous> (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:113:29858)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
[2021-10-01 15:58:21.725] [exthost] [info] eager extensions activated
[2021-10-01 15:58:22.732] [exthost] [info] exiting with code 0


```

Same behaviour as described here [#5620](https://github.com/microsoft/vscode-remote-release/issues/5620#issue-1003948683) but in my case there are no certificate errors in the log.

When I try to open a remote container it looks like it works except for activating all the extensions defined in devcontainer.json. It happens for me and some of my students using Windows 10 when connected to eduroam Wifi. The problem only appears for some Windows 10 Laptops, not every Windows 10 Laptop is affected. We didn't notice those problems with Ubuntu Laptops.

In my Wifi at home, with the same laptop which was connected to eduroam before, after rebuilding the container it works as expected: all the extensions defined in devcontainer.sjon are installed.
So it maybe has something to do with eduroam (enterprise wifi?).

Any ideas what we could do?

**Comment by sandy081** [comment]
Can you please share the remote server logs?

**Comment by Kiolali** [comment]
yes. logs are attached
[logs.zip](https://github.com/microsoft/vscode-remote-release/files/7296163/logs.zip)

**Comment by Kiolali** [comment]
I got it now. Using the terminal i figured out the location of the logs. Unfortunately, there is only one folder with logs from today (although it's the folder/devcontainer which did not work in eduroam wifi)

**Comment by sandy081** [comment]
Please provide the remote server logs if you are able to reproduce it again.
