### ISSUE TITLE
Dev Container CLI fails when reading machine ID from user settings

### ISSUE THREAD

**Issue by Chuxel** [microsoft/vscode-remote-release#5675]
Version: 1.61.0-insider (user setup)
Commit: 71ca6e8e74591ae5c577d52a2aa1bd0c3df5ac32
Date: 2021-10-05T01:25:37.698Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Extension version 0.201.0

This may be Windows only or not - have not tried other OS's

1. Run the Install Dev Container CLI command
2. Go to the terminal and try to build

It will with the following: 

```
E:\temp>devcontainer-insiders build .
Failed to load user settings
Error: Failed to determine user settings path
    at doe (c:\Users\clantz\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.201.0\dev-containers-user-cli\dist\node\devContainersUserCLI.js:279:13608)
    at Ab (c:\Users\clantz\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.201.0\dev-containers-user-cli\dist\node\devContainersUserCLI.js:279:6862)
    at Object.handler (c:\Users\clantz\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.201.0\dev-containers-user-cli\dist\node\devContainersUserCLI.js:279:6590)
    at c:\Users\clantz\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.201.0\dev-containers-user-cli\dist\node\devContainersUserCLI.js:30:27067
    at Ho (c:\Users\clantz\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.201.0\dev-containers-user-cli\dist\node\devContainersUserCLI.js:30:23033)
    at l0.applyMiddlewareAndGetResult (c:\Users\clantz\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.201.0\dev-containers-user-cli\dist\node\devContainersUserCLI.js:30:27050)
    at l0.runCommand (c:\Users\clantz\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.201.0\dev-containers-user-cli\dist\node\devContainersUserCLI.js:30:25330)
    at U0.[runYargsParserAndExecuteCommands] (c:\Users\clantz\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.201.0\dev-containers-user-cli\dist\node\devContainersUserCLI.js:87:6499)
    at U0.parse (c:\Users\clantz\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.201.0\dev-containers-user-cli\dist\node\devContainersUserCLI.js:85:13590)
    at U0.get [as argv] (c:\Users\clantz\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.201.0\dev-containers-user-cli\dist\node\devContainersUserCLI.js:85:2132)
Failed to read VS Code machine id from vscode-machine-id
```

**Comment by chrmarti** [comment]
@Chuxel Could you check if this also occurs with a folder on `C:`?

**Comment by Chuxel** [comment]
@chrmarti 
```
c:\Users\clantz\AppData\Roaming\Code - Insiders\User\globalStorage\ms-vscode-remote.remote-containers\cli-bin\devcontainer-insiders.cmd
```

**Comment by Chuxel** [comment]
Oh! One other thing I just noticed - this is failing in `CMD.exe`, not PowerShell.

**Comment by Syntactical01** [comment]
So this error is still a thing from CMD prompt. Any fixes? I use PowerShell but I user "Make for Windows" which appears to use command prompt under the hood so I was curious if there is a fix I can apply to get it to work.

**Comment by Syntactical01** [comment]
Okay so I think I found the bug for windows.

So first off, `devcontainer build` failed with the same error as the user above stated.

First I did a `where devcontainer` because I wanted to see where the command was it was running and I got something like:
```
c:\Users\foobar\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\cli-bin\devcontainer.cmd
```
I will reference this full path as `FULL_PATH` from here on out to save typing.

For the fun of it I tried running:
```
FULL_PATH build
```
and that worked..... **UGH** now why did that work?!

So looking in the file that FULL_PATH represents, I turned the echo on and re-ran the commands above to do a diff check...

The differences I noted are:

- `devcontainer build` gave me: `SET DEVCONTAINER_CLI_PATH=devcontainer
- `FULL_PATH build` gave me : `SET DEVCONTAINER_CLI_PATH=FULL_PATH`

So I did a little research on the following command that was in the `.cmd` file:
```
SET DEVCONTAINER_CLI_PATH=%0
```
Reading this: https://stackoverflow.com/a/35686107/8150685
I changed the above command to:
```
SET DEVCONTAINER_CLI_PATH=%~f0
```
And like magic it started working.

I don't think there is a public repository I can PR this? @chrmarti

**Comment by chrmarti** [comment]
@Syntactical01 That's the fix I released. Which version of Remote-Containers are you using?

**Comment by Syntactical01** [comment]
![image](https://user-images.githubusercontent.com/46199814/141789770-d0cb1672-2c8f-4eb2-9f0a-d7b1b275dce9.png)
