### ISSUE TITLE
Unable to connect to any remote server

### ISSUE THREAD

**Issue by Alexbh911** [microsoft/vscode-remote-release#5700]
Issue Type: <b>Bug</b>

College computer with CMD & PowerShell Locked. But running ssh user@serverAddress works in run menu (Win+R) works to get SSH terminal.
Errors Are:
"Could not establish connection to "serverAddress": Got bad result from install script", 
"The terminal process failed to launch: A native exception occurred during launch (Cannot create process, error code: 1260).", 
"Resolver error: Error: Got bad result from install script
	at Function.Create (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:397041)
	at Object.t.tryInstall (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:489077)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:453110
	at async Object.t.withShowDetailsEvent (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:456460)
	at async Object.t.resolve (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:454189)
	at async c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:526942"

Extension version: 0.65.8
VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (10.65GB free)|
|Process Argv|--crash-reporter-id 9c4d2acc-a5fb-4fad-ba3b-6a22d1a0affb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30378365
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30371810
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30364666
pythonvspyt187:30373474
pydsgsc2:30361791
vsqsis200:30374795
vsaa593cf:30376535
vssld246:30379911

```

</details>

**Comment by tanhakabir** [comment]
Thanks for submitting! Would you be able to post the entire Remote-SSH log?

**Comment by liqunfu** [comment]
I have a similar issue with the same Error message and call stack #5722 [#5722 ](url)

**Comment by roblourens** [comment]
The ssh command exited, but it isn't clear why. Does running a command like `echo "echo hello" | ssh yourhost bash` work?

Alternately, do you get a different result if you set `"remote.SSH.useLocalServer": true` in your settings json

**Comment by Alexbh911** [comment]
I got a new error after adding the server key when connecting with the ssh command 

[15:57:55.556] Log Level: 2
[15:57:55.561] remote-ssh@0.65.8
[15:57:55.561] win32 x64
[15:57:55.562] SSH Resolver called for "ssh-remote+'ServerAddress'", attempt 1
[15:57:55.562] "remote.SSH.useLocalServer": true
[15:57:55.563] "remote.SSH.path": undefined
[15:57:55.563] "remote.SSH.configFile": undefined
[15:57:55.563] "remote.SSH.useFlock": true
[15:57:55.563] "remote.SSH.lockfilesInTmp": false
[15:57:55.563] "remote.SSH.localServerDownload": auto
[15:57:55.563] "remote.SSH.remoteServerListenOnSocket": false
[15:57:55.563] "remote.SSH.showLoginTerminal": true
[15:57:55.563] "remote.SSH.defaultExtensions": []
[15:57:55.563] "remote.SSH.loglevel": 2
[15:57:55.564] SSH Resolver called for host: 'ServerAddress'
[15:57:55.564] Setting up SSH remote "'ServerAddress'"
[15:57:55.567] Acquiring local install lock: C:\Users\DestopUserName\AppData\Local\Temp\vscode-remote-ssh-97790c8d-install.lock
[15:57:55.591] Looking for existing server data file at c:\Users\DestopUserName\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-ssh\vscode-ssh-host-97790c8d-83bd43bc519d15e50c4272c6cf5c1479df196a4d-0.65.8\data.json
[15:57:55.592] Using commit id "83bd43bc519d15e50c4272c6cf5c1479df196a4d" and quality "stable" for server
[15:57:55.595] Install and start server if needed
[15:57:55.599] Checking ssh with "ssh -V"
[15:57:55.644] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[15:57:55.646] Checking ssh with "C:\windows\System32\OpenSSH\ssh.exe -V"
[15:57:55.686] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[15:57:55.688] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[15:57:55.689] Got error from ssh: spawn C:\Program Files\Git\usr\bin\ssh.exe ENOENT
[15:57:55.689] Checking ssh with "C:\Program Files (x86)\Git\usr\bin\ssh.exe -V"
[15:57:55.690] Got error from ssh: spawn C:\Program Files (x86)\Git\usr\bin\ssh.exe ENOENT
[15:57:55.690] Checking ssh with "ssh -V"
[15:57:55.730] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[15:57:55.735] Using SSH config file "C:\Users\DestopUserName\.ssh\config"
[15:57:55.735] askpass server listening on \\.\pipe\vscode-ssh-askpass-320cc54e3ed6f1092f3b5df2d8d013b0265fa030-sock
[15:57:55.736] Spawning local server with {"serverId":1,"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-68d4af049bfe83739c9ef1110fab68efc56c3358-sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","51833","-F","C:\\Users\\DestopUserName\\.ssh\\config","'ServerAddress'"],"dataFilePath":"c:\\Users\\DestopUserName\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-vscode-remote.remote-ssh\\vscode-ssh-host-97790c8d-83bd43bc519d15e50c4272c6cf5c1479df196a4d-0.65.8\\data.json"}
[15:57:55.736] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"c:\\Users\\DestopUserName\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.65.8\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"C:\\Program Files\\Microsoft VS Code\\Code.exe","VSCODE_SSH_ASKPASS_MAIN":"c:\\Users\\DestopUserName\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.65.8\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-320cc54e3ed6f1092f3b5df2d8d013b0265fa030-sock"}
[15:57:55.744] Spawned 14140
[15:57:55.822] > local-server-1> Spawned ssh, pid=7400
[15:57:55.858] stderr> OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
[15:57:55.896] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:J68pC1Ql6V4LcmRr3E078iCmA65k0KBVcH1K8TrlMPE
[15:57:55.958] stderr> CreateProcessW failed error:1260
[15:57:55.958] stderr> ssh_askpass: posix_spawnp: Unknown error
[15:57:55.966] stderr> Permission denied, please try again.
[15:57:55.970] stderr> CreateProcessW failed error:1260
[15:57:55.970] stderr> ssh_askpass: posix_spawnp: Unknown error
[15:57:55.979] stderr> Permission denied, please try again.
[15:57:55.982] stderr> CreateProcessW failed error:1260
[15:57:55.982] stderr> ssh_askpass: posix_spawnp: Unknown error
[15:57:55.991] stderr> RemoteUserName@'ServerAddress': Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
[15:57:55.993] > local-server-1> ssh child died, shutting down
[15:57:56.000] Local server exit: 0
[15:57:56.000] Received install output: local-server-1> Spawned ssh, pid=7400
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:J68pC1Ql6V4LcmRr3E078iCmA65k0KBVcH1K8TrlMPE
CreateProcessW failed error:1260
ssh_askpass: posix_spawnp: Unknown error
Permission denied, please try again.
CreateProcessW failed error:1260
ssh_askpass: posix_spawnp: Unknown error
Permission denied, please try again.
CreateProcessW failed error:1260
ssh_askpass: posix_spawnp: Unknown error
RemoteUserName@'ServerAddress': Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
local-server-1> ssh child died, shutting down

[15:57:56.002] Resolver error: Error: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
	at Function.Create (c:\Users\DestopUserName\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:397041)
	at c:\Users\DestopUserName\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:395235
	at Object.t.handleInstallOutput (c:\Users\DestopUserName\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:395620)
	at Object.e [as tryInstallWithLocalServer] (c:\Users\DestopUserName\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:435292)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\DestopUserName\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:452665
	at async Object.t.withShowDetailsEvent (c:\Users\DestopUserName\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:456460)
	at async c:\Users\DestopUserName\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:433816
	at async C (c:\Users\DestopUserName\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:430392)
	at async Object.t.resolveWithLocalServer (c:\Users\DestopUserName\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:433431)
	at async Object.t.resolve (c:\Users\DestopUserName\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:454065)
	at async c:\Users\DestopUserName\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:526942
[15:57:56.004] ------

**Comment by roblourens** [comment]
Ah, I'm sure that this is due to the permission restrictions on your system. If you can't open a terminal, this isn't going to work, sorry. The other logs just show that ssh is failing to spawn a process. Talk to your sysadmin and see if they can help.
