### ISSUE TITLE
AWS SSM process tried to write to nonexistent pipe

### ISSUE THREAD

**Issue by vanderhoff** [microsoft/vscode-remote-release#5740]
using vscode ssh connection an error is returned, **process tried to write to nonexistent pipe**
Running the same command from powershell or cmd the pipe works as expected

- VSCode Version:
             Version: 1.61.0 (user setup)
             Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
             Date: 2021-10-07T18:13:09.652Z
             Electron: 13.5.1
            Chrome: 91.0.4472.164
            Node.js: 14.16.0
            V8: 9.1.269.39-electron.0
             OS: Windows_NT x64 10.0.19043
- Local OS Version: Windows 10 Pro 21H1
- Remote OS Version: Amazon Linux 2
- Remote Extension/Connection Type: SSH/Docker/WSL   ec2 via SSM tunnel
- Logs:

Steps to Reproduce:

1. add entry to .ssh cfg file 
        Host i-* mi-*
	      User ec2-user
	      ProxyCommand C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe "aws --region us-east-1 ssm start-session --target %h --document-name AWS-StartSSHSession --parameters portNumber=%p"
	      IdentityFile "C:\Users\myuser\.ssh\my.pem"

         Host i-09b749f52649f1234
              HostName i-09b749f52649f1234

2. validate with manual test using powershell
         PS C:\dev> ssh i-09b749f52649f1234
            Last login: Mon Oct 18 20:26:20 2021 from localhost
 
                  __|  __|_  )
                  _|  (     /   Amazon Linux 2 AMI
                  ___|\___|___|

             https://aws.amazon.com/amazon-linux-2/

3. call from vscode 
            connect current window to host 
            i-09b749f52649f1234
    ! > asks for OS type > select Linux

```    
[22:04:54.806] Log Level: 2
[22:04:54.809] remote-ssh@0.65.8
[22:04:54.809] win32 x64
[22:04:54.809] SSH Resolver called for "ssh-remote+i-09b749f52649f1234", attempt 1
[22:04:54.810] "remote.SSH.useLocalServer": false
[22:04:54.810] "remote.SSH.showLoginTerminal": false
[22:04:54.810] "remote.SSH.remotePlatform": { ... }
[22:04:54.810] "remote.SSH.path": undefined
[22:04:54.811] "remote.SSH.configFile": C:\Users\myuser\.ssh\config
[22:04:54.811] "remote.SSH.useFlock": true
[22:04:54.811] "remote.SSH.lockfilesInTmp": false
[22:04:54.811] "remote.SSH.localServerDownload": auto
[22:04:54.811] "remote.SSH.remoteServerListenOnSocket": false
[22:04:54.811] "remote.SSH.showLoginTerminal": false
[22:04:54.811] "remote.SSH.defaultExtensions": []
[22:04:54.812] "remote.SSH.loglevel": 2
[22:04:54.812] SSH Resolver called for host: i-09b749f52649f1234
[22:04:54.812] Setting up SSH remote "i-09b749f52649f1234"
[22:04:54.833] Using commit id "ee8c7def80afc00dd6e593ef12f37756d8f504ea" and quality "stable" for server
[22:04:54.839] Install and start server if needed
[22:04:56.245] Checking ssh with "ssh -V"
[22:04:56.291] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[22:04:56.300] Using SSH config file "C:\Users\myuser\.ssh\config"
[22:04:56.301] Running script with connection command: ssh -T -D 62483 -F "C:\Users\myuser\.ssh\config" "i-09b749f52649f1234" bash
[22:04:56.306] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[22:04:56.527] > ]0;C:\WINDOWS\System32\cmd.exe
[22:04:56.527] Got some output, clearing connection timeout
[22:04:56.921] > kex_exchange_identification: Connection closed by remote host
[22:04:56.928] > The process tried to write to a nonexistent pipe.
[22:04:58.199] "install" terminal command done
[22:04:58.200] Install terminal quit with output: The process tried to write to a nonexistent pipe.
[22:04:58.200] Received install output: The process tried to write to a nonexistent pipe.
[22:04:58.200] Resolver error: Error: The process tried to write to a nonexistent pipe
	at Function.Offline (c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:397092)
	at c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:394642
	at Object.t.handleInstallOutput (c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:395020)
	at Object.t.tryInstall (c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:489314)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:453110
	at async Object.t.withShowDetailsEvent (c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:456460)
	at async Object.t.resolve (c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:454189)
	at async c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:526942
[22:04:58.205] ------
```    

4. running cmd direct in cmd / powershell
                      ssh -T -D 62483 -F "C:\Users\myuser\.ssh\config" "i-09b749f52649f1234" bash
                !> cmd line does not echo out any details or time out, manual ctrl-c needed, then output as follows

```
Command '['session-manager-plugin', '{"SessionId": "awsssm-00baa7a353371e...", "TokenValue": "...TOKEN...", "StreamUrl": "wss://ssmmessages.us-east-1.amazonaws.com/v1/data-channel/awsssm-00baa7a35337.....?role=publish_subscribe", "ResponseMetadata": {"RequestId": "fe72e8ba-1204-4db7-a3a1-ed1622d12345", "HTTPStatusCode": 200, "HTTPHeaders": {"server": "Server", "date": "Mon, 18 Oct 2021 21:10:15 GMT", "content-type": "application/x-amz-json-1.1", "content-length": "684", "connection": "keep-alive", "x-amzn-requestid": "fe72e8ba-1204-4db7-a3a1-ed1622d12345"}, "RetryAttempts": 0}}', 'us-east-1', 'StartSession', '', '{"Target": "i-09b749f52649f1234", "DocumentName": "AWS-StartSSHSession", "Parameters": {"portNumber": ["22"]}}', 'https://ssm.us-east-1.amazonaws.com']' returned non-zero exit status 3221225786.
```

**Comment by vanderhoff** [comment]
Hi @roblourens thanks for the prompt follow up

new steps
1) upgrade to OpenSSH_for_Windows_8.6p1
https://github.com/PowerShell/Win32-OpenSSH/releases/tag/V8.6.0.0p1-Beta

2) confirm setting `"remote.SSH.useLocalServer": true`

3) run with echo 
`echo "echo hello" | ssh -T -D 62483 -F "C:\Users\myuser.ssh\config" "i-09b749f52649f1234" bash`
3.1) on powershell returns only "hello"
3.2) on cmd returns `bash: line 1: echo hello: command not found`

4) update ssh config 
`Host i-* mi-*
      User ec2-user
      ProxyCommand C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe "aws --region us-east-1 ssm start-session --target %h --document-name AWS-StartSSHSession --parameters portNumber=%p"
      IdentityFile "C:\Users\myuser.ssh\my.pem"`

4.1) validate with manual test using powershell
  `PS C:\dev> ssh i-09b749f52649f1234` connects to ec2 as expected

4.2) vscode 
    Remote-SSH: Connect Current Window to Host...     > i-09b749f52649f1234
         new log line 
         `[10:28:13.674] > kex_exchange_identification: Connection closed by remote host
                                  > Connection closed by UNKNOWN port 65535
                                  > The process tried to write to a nonexistent pipe.`
    full log
    `[10:28:11.547] Log Level: 2
[10:28:11.551] remote-ssh@0.65.8
[10:28:11.551] win32 x64
[10:28:11.552] SSH Resolver called for "ssh-remote+i-09b749f52649f1234", attempt 1
[10:28:11.553] "remote.SSH.useLocalServer": false
[10:28:11.553] "remote.SSH.showLoginTerminal": false
[10:28:11.553] "remote.SSH.remotePlatform": { ... }
[10:28:11.554] "remote.SSH.path": undefined
[10:28:11.554] "remote.SSH.configFile": C:\Users\myuser\.ssh\config
[10:28:11.554] "remote.SSH.useFlock": true
[10:28:11.554] "remote.SSH.lockfilesInTmp": false
[10:28:11.555] "remote.SSH.localServerDownload": auto
[10:28:11.555] "remote.SSH.remoteServerListenOnSocket": false
[10:28:11.555] "remote.SSH.showLoginTerminal": false
[10:28:11.555] "remote.SSH.defaultExtensions": []
[10:28:11.555] "remote.SSH.loglevel": 2
[10:28:11.556] SSH Resolver called for host: i-09b749f52649f1234
[10:28:11.556] Setting up SSH remote "i-09b749f52649f1234"
[10:28:11.576] Using commit id "ee8c7def80afc00dd6e593ef12f37756d8f504ea" and quality "stable" for server
[10:28:11.581] Install and start server if needed
[10:28:12.913] Checking ssh with "ssh -V"
[10:28:12.949] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.0.2

[10:28:12.958] Using SSH config file "C:\Users\myuser\.ssh\config"
[10:28:12.958] Running script with connection command: ssh -T -D 58158 -F "C:\Users\myuser\.ssh\config" "i-09b749f52649f1234" bash
[10:28:12.961] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:28:13.179] > ]0;C:\WINDOWS\System32\cmd.exe
[10:28:13.180] Got some output, clearing connection timeout
[10:28:13.674] > kex_exchange_identification: Connection closed by remote host
> Connection closed by UNKNOWN port 65535
> The process tried to write to a nonexistent pipe.
[10:28:14.930] "install" terminal command done
[10:28:14.930] Install terminal quit with output: The process tried to write to a nonexistent pipe.
[10:28:14.930] Received install output: The process tried to write to a nonexistent pipe.
[10:28:14.931] Resolver error: Error: The process tried to write to a nonexistent pipe
	at Function.Offline (c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:397092)
	at c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:394642
	at Object.t.handleInstallOutput (c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:395020)
	at Object.t.tryInstall (c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:489314)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:453110
	at async Object.t.withShowDetailsEvent (c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:456460)
	at async Object.t.resolve (c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:454189)
	at async c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:526942
[10:28:14.934] ------`

**Comment by vanderhoff** [comment]
for those that don't mind a tactical solution. 
After a LOT of searching I did not find this spelt out anywhere, so posting here in case it is of value to others using win10.

in powershell start a proxy session
`aws --region <region> ssm start-session --target i-09b749f52649f1234 --document-name AWS-StartPortForwardingSession --parameters '{\"portNumber\":[\"22\"], \"localPortNumber\":[\"62300\"]}'`
_note the extra required slash in the json \"_

then in the hosts file
`Host i-09b749f52649f1234
	HostName 127.0.0.1
	User ec2-user
    port 62300
	IdentityFile "C:\mydir\myfile.pem"`

it may take a while to install vscode, so monitor via 
output> Remote SSH

I have not tried debugging etc but at least this gets you onto the instance via ssm

hope this helps until we can get a built in solution via vscode

**Comment by roblourens** [comment]
> why does vscode change the internal command to

We need to set some extra options, and the config file is because you have set the config file in your settings. I assume that path is correct.

> on cmd returns bash: line 1: echo hello: command not found

Sorry, yes on cmd that command would be `echo echo hello | ssh ...` (no quotes). It worked on powershell, seems like everything should be working...

I am seeing the same error show up in some other questions where ProxyCommand is involved https://github.com/microsoft/vscode-remote-release/issues/4283#issuecomment-758435245 https://github.com/microsoft/vscode-remote-release/issues/3562#issuecomment-679343261

but they don't have real solution.

I would think that you don't need to
