### ISSUE TITLE
cannot use ssh after disable cmd.exe

### ISSUE THREAD

**Issue by fatevase** [microsoft/vscode-remote-release#5744]
### issues :
change the vscode default terminal does not change the path of the extension.

when I forbid cmd.exe and i changed the default terminal of vscode(using powershell), then running the `Remote-SSH`, it still using cmd.exe terminal. i cant change terminal shell path for ssh esxtension independently.

- VSCode Version:1.61.1
- Local OS Version:window11
- Remote OS Version:ubuntu16.04
- Remote Extension/Connection Type: SSH
- Logs:
```
[22:00:09.700] Using commit id "c13f1abb110fc756f9b3a6f16670df9cd9d4cf63" and quality "stable" for server
[22:00:09.702] Install and start server if needed
[22:00:09.705] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[22:00:09.756] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[22:00:09.761] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 3906 "server_in" bash
[22:00:09.763] **Terminal shell path: C:\WINDOWS\System32\cmd.exe**
[22:00:11.351] "install" terminal command done
[22:00:11.352] Install terminal quit with output: 
[22:00:11.353] Resolver error: Error: Got bad result from install script
	at Function.Create (c:\Users\vase\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:397041)
	at Object.t.tryInstall (c:\Users\vase\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:489077)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\vase\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:453110
	at async Object.t.withShowDetailsEvent (c:\Users\vase\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:456460)
	at async Object.t.resolve (c:\Users\vase\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:454189)
	at async c:\Users\vase\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:526942
[22:00:11.361] ------
```
```
“C:\WINDOWS\System32\cmd.exe /c (type 
"C:\Users\vase\AppData\Local\Temp\vscode-linux-multi-line-command-server_in-
542988820.sh" | "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 3906 "server_in" 
bash) & exit /b 0” terminated with exit code: 1.
```

Steps to Reproduce:
1.setting `\HKEY_CURRENT_USER\Software\Microsoft\Command Processor` `AutoRun` : `if exit` in regedit
2. setting remote.SSH:Path : `C:\Windows\System32\OpenSSH\ssh.exe`
3. open ssh and still get error.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by fatevase** [comment]
> > when I forbid cmd.exe
> 
> Why? Is that a common thing to do? I would expect that would interfere with many applications

it not common thing to do...
I found this issues when the system suddenly failed to call the cmd.exe terminal
I just found out that this extension will not follow the custom terminal of vscode.

**Comment by roblourens** [comment]
Ok, I don't think that we can reasonably work around that, sorry.
