### ISSUE TITLE
Failed to parse remote port from server output

### ISSUE THREAD

**Issue by tnhlng** [microsoft/vscode-remote-release#5749]
when I try to connect remote machine,I got  error below:

```
[20:15:54.150] ssh exited with code: 2
[20:15:54.150] The specified path E:\Git\bin\sh.exe is not a valid SSH binary
[20:15:54.150] Checking ssh with "ssh -V"
[20:15:54.195] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[20:15:54.198] Running script with connection command: ssh -T -D 12686 -o RemoteCommand=none remoteserver bash
[20:15:54.200] Terminal shell path: C:\Windows\System32\cmd.exe
[20:15:54.499] > ]0;C:\Windows\System32\cmd.exe
[20:15:54.499] Got some output, clearing connection timeout
[20:15:54.513] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[20:15:54.576] > Enter passphrase for key 'C:\Users\Administrator\.ssh\Identity_20210727\Identify': 
[20:16:03.949] > 
[20:16:03.965] > Enter passphrase for key 'C:\Users\Administrator\.ssh\Identity_20210727\Identify': 
[20:16:20.072] > 
**[20:16:20.287] > Please select your docker version
> 1) ubuntu12.04        
> 2) ubuntu16.04        
> 3) ubuntu20.04        
> 4) ubuntu_dcache:     
> #? 1) ubuntu12.04     
> 2) ubuntu16.04        
> you selected version: 
> invaild option**        
> you selected version: 
> invaild option        
> you selected version: 
> invaild option        
> you selected version: 
> invaild option        
> 3) ubuntu20.04
> 4) ubuntu_dcache:
> #? #? 1) ubuntu12.04

……………………

> invaild option
> you selected version:
> invaild option
> you selected version:
> invaild option
> #? #? #? #? #? #? 1) ubuntu12.04
> 2) ubuntu16.04
> 3) ubuntu20.04
> 4) ubuntu_dcache:
> #? #? 1) ubuntu12.04
> 2) ubuntu16.04
> 3) ubuntu20.04
> 4) ubuntu_dcache:
> #? #?
[20:16:22.211] "install" terminal command done
[20:16:22.212] Install terminal quit with output: #? #?
[20:16:22.212] Received install output: #? #?
[20:16:22.213] Failed to parse remote port from server output
[20:16:22.213] Resolver error: Error: 
	at Function.Create (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:397041)
	at Object.t.handleInstallOutput (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:395684)
	at Object.t.tryInstall (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:489314)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:453110
	at async Object.t.withShowDetailsEvent (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:456460)
	at async Object.t.resolve (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:454189)
	at async c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:526942
[20:16:22.217] ------
```

**the background is that I need input a number to choose the enviroment version to login in remote machine . but it seems that vscode-remote ignored these massage, so I can't give effective response, Is there any solution to this situation？**

My configuration is as follows 。

Host remoteserver
	HostName xxx.xx.214.24
	User abc
    IdentityFile "C:\Users\Administrator\.ssh\Identity_20210727\Identify"
    RequestTTY force
    Port 32200
    ForwardX11 yes

**Comment by tnhlng** [comment]
> Hey thanks for the detailed question! Could you try using the Login terminal to connect? Set the setting `remote.SSH.showLoginTerminal` to true and it should pop up a terminal for you to put in your answers to.
> 
> The setting looks like this in the Settings View: ![image](https://user-images.githubusercontent.com/12758612/138374082-1fc50a5d-8bcc-4285-af3e-0cab8c629692.png)

yes，actually I connect  my remote machine through xshell7 most of time ,it works well.  but I want to login in remote machine through vscode-remote so that i can write and compile code as local。

I do found some similar issue like "Support Duo 2fa prompt #2170" and set configure as below :
```
"remote.SSH.useLocalServer": false,
"remote.SSH.showLoginTerminal": true,
```
but it never pop out any terminal but Error prompt box after i enter passphrase for key.
