### ISSUE TITLE
can't connect to remote host after update 1.61.2

### ISSUE THREAD

**Issue by telnet01** [microsoft/vscode-remote-release#5753]
Hello!

With a last version 1.62 VS Code I can't login on remote after install it on target 
```
[22:20:58.965] Log Level: 2
[22:20:58.965] remote-ssh@0.65.8
[22:20:58.966] darwin arm64
[22:20:58.966] SSH Resolver called for "ssh-remote+192.168.1.244", attempt 1
[22:20:58.966] "remote.SSH.useLocalServer": true
[22:20:58.967] "remote.SSH.path": undefined
[22:20:58.967] "remote.SSH.configFile": undefined
[22:20:58.967] "remote.SSH.useFlock": true
[22:20:58.967] "remote.SSH.lockfilesInTmp": false
[22:20:58.967] "remote.SSH.localServerDownload": auto
[22:20:58.967] "remote.SSH.remoteServerListenOnSocket": false
[22:20:58.967] "remote.SSH.showLoginTerminal": false
[22:20:58.967] "remote.SSH.defaultExtensions": []
[22:20:58.967] "remote.SSH.loglevel": 2
[22:20:58.967] SSH Resolver called for host: 192.168.1.244
[22:20:58.967] Setting up SSH remote "192.168.1.244"
[22:20:58.969] Acquiring local install lock: /var/folders/sb/_qhbymls261cg64wpgqpz0fw0000gn/T/vscode-remote-ssh-68f7dbed-install.lock
[22:20:58.977] Looking for existing server data file at /Users/andrey/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-68f7dbed-6cba118ac49a1b88332f312a8f67186f7f3c1643-0.65.8/data.json
[22:20:58.978] Using commit id "6cba118ac49a1b88332f312a8f67186f7f3c1643" and quality "stable" for server
[22:20:58.980] Install and start server if needed
[22:20:58.982] PATH: /opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/gcc_arm/gcc-arm-none-eabi-4_7-2013q3/bin/
[22:20:58.982] Checking ssh with "ssh -V"
[22:20:58.987] > OpenSSH_8.1p1, LibreSSL 2.7.3

[22:20:58.989] askpass server listening on /var/folders/sb/_qhbymls261cg64wpgqpz0fw0000gn/T/vscode-ssh-askpass-e8164a095c1e7a2ad3d333ce6d3a3c6adaecbd48.sock
[22:20:58.989] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/sb/_qhbymls261cg64wpgqpz0fw0000gn/T/vscode-ssh-askpass-d66cda2c8dd6a0272d86c6724fe6975cd45f47cf.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","54369","-o","ConnectTimeout=15","192.168.1.244"],"dataFilePath":"/Users/andrey/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-68f7dbed-6cba118ac49a1b88332f312a8f67186f7f3c1643-0.65.8/data.json"}
[22:20:58.989] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/andrey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/private/var/folders/sb/_qhbymls261cg64wpgqpz0fw0000gn/T/AppTranslocation/13540D62-C560-4992-8217-B445F03DCA1F/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/andrey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/sb/_qhbymls261cg64wpgqpz0fw0000gn/T/vscode-ssh-askpass-e8164a095c1e7a2ad3d333ce6d3a3c6adaecbd48.sock"}
[22:20:58.990] Spawned 91362
[22:20:59.075] > local-server-1> Spawned ssh, pid=91369
[22:20:59.076] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[22:20:59.374] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:uxfZHkfHfnF/76wTbLJevR99oTuF3dyEA+TMWut9E1k
[22:20:59.488] Got askpass request: {"request":"Password:"}
[22:20:59.488] Showing password prompt
[22:20:59.488] Listening for interwindow password on /var/folders/sb/_qhbymls261cg64wpgqpz0fw0000gn/T/vscode-ssh-askpass-5932ea25f39290901984148fd5f0e912d03ff538.sock
[22:20:59.489] Writing password prompt to globalState
[22:21:07.435] Got password response
[22:21:07.435] Interactor gave response: ***********
[22:21:07.435] Cleaning up other-window auth server
[22:21:07.922] stderr> Authenticated to 192.168.1.244 ([192.168.1.244]:22).
[22:21:08.014] > ready: c154366d7385
[22:21:08.038] > Linux 4.1.13-g8dc6617 #3 PREEMPT Fri Jun 11 15:10:07 +07 2021
[22:21:08.038] Platform: linux
[22:21:08.073] stderr> bash: line 1: o: command not found
[22:21:08.076] > downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
[22:21:08.077] stderr> bash: line 6: syntax error near unexpected token `}'
[22:21:08.077] stderr> bash: line 6: `}'
[22:21:08.078] > c154366d7385: running
[22:21:08.078] stderr> -sh: function: not found
[22:21:08.092] stderr> -sh: syntax error: unexpected "(" (expecting "then")
[22:21:08.093] stderr> Transferred: sent 17032, received 2264 bytes, in 0.2 seconds
[22:21:08.094] stderr> Bytes per second: sent 100594.2, received 13371.6
[22:21:08.094] > local-server-1> ssh child died, shutting down
[22:21:08.098] Local server exit: 0
[22:21:08.098] Received install output: local-server-1> Spawned ssh, pid=91369
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:uxfZHkfHfnF/76wTbLJevR99oTuF3dyEA+TMWut9E1k
Authenticated to 192.168.1.244 ([192.168.1.244]:22).
ready: c154366d7385
Linux 4.1.13-g8dc6617 #3 PREEMPT Fri Jun 11 15:10:07 +07 2021
bash: line 1: o: command not found
downloadTime====
installTime====
extInstallTime====
serverStartTime====
bash: line 6: syntax error near unexpected token `}'
bash: line 6: `}'
c154366d7385: running
-sh: function: not found
-sh: syntax error: unexpected "(" (expecting "then")
Transferred: sent 17032, received 2264 bytes, in 0.2 seconds
Bytes per second: sent 100594.2, received 13371.6
local-server-1> ssh child died, shutting down

[22:21:08.098] Failed to parse remote port from server output
[22:21:08.099] Resolver error: Error: 
	at Function.Create (/Users/andrey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:397041)
	at Object.t.handleInstallOutput (/Users/andrey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:395684)
	at Object.e [as tryInstallWithLocalServer] (/Users/andrey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:435292)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/andrey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:452665
	at async Object.t.withShowDetailsEvent (/Users/andrey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:456460)
	at async /Users/andrey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:433816
	at async C (/Users/andrey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:430392)
	at async Object.t.resolveWithLocalServer (/Users/andrey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:433431)
	at async Object.t.resolve (/Users/andrey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:454065)
	at async /Users/andrey/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:526942
[22:21:08.101] ------
```

**Comment by tanhakabir** [comment]
Closing issue due to inactivity

**Comment by kennylbj** [comment]
Same issue to me, 6cba118ac49a1b88332f312a8f67186f7f3c1643 version still doesn't work.  @telnet01 have you resolved this issue?

**Comment by tanhakabir** [comment]
@kennylbj have you tried deleting .vscode-server folder in your remote and trying to connect from the extension again?

And would you also be able to share your logs?

**Comment by telnet01** [comment]
> Same issue to me, 6cba118ac49a1b88332f312a8f67186f7f3c1643 version still doesn't work. @telnet01 have you resolved this issue?

Hello,yes, i installed bash 5.0 and  the problem is gone, but a new problem has appeared[https://github.com/microsoft/vscode/issues/136209#issuecomment-956005309](url)

**Comment by kennylbj** [comment]
@tanhakabir I have removed the .vscode-server folder but still didn't work. here is the log
[12:50:53.480] Log Level: 2
[12:50:53.482] remote-ssh@0.66.0
[12:50:53.482] darwin x64
[12:50:53.491] SSH Resolver called for "ssh-remote+[IP]", attempt 1
[12:50:53.491] "remote.SSH.useLocalServer": true
[12:50:53.492] "remote.SSH.path": undefined
[12:50:53.492] "remote.SSH.configFile": undefined
[12:50:53.492] "remote.SSH.useFlock": true
[12:50:53.493] "remote.SSH.lockfilesInTmp": false
[12:50:53.493] "remote.SSH.localServerDownload": off
[12:50:53.493] "remote.SSH.remoteServerListenOnSocket": false
[12:50:53.493] "remote.SSH.showLoginTerminal": false
[12:50:53.494] "remote.SSH.defaultExtensions": []
[12:50:53.494] "remote.SSH.loglevel": 2
[12:50:53.494] SSH Resolver called for host: [ip]
[12:50:53.494] Setting up SSH remote "[ip]"
[12:50:53.497] Acquiring local install lock: /var/folders/sy/kqyy8q9d2n76rlvflkxznxmc0000gn/T/vscode-remote-ssh-67cb8c6e-install.lock
[12:50:53.503] Looking for existing server data file at /Users/fishdicks/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-67cb8c6e-6cba118ac49a1b88332f312a8f67186f7f3c1643-0.66.0/data.json
[12:50:53.503] Using commit id "6cba118ac49a1b88332f312a8f67186f7f3c1643" and quality "stable" for server
[12:50:53.505] Install and start server if needed
[12:50:53.507] PATH: /usr/local/opt/python/libexec/bin:/usr/local/sbin:/Users/fishdicks/.nvm/versions/node/v10.19.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Apple/usr/bin:/Users/fishdicks/Desktop/workspace/mobile/flutter/flutter/bin
[12:50:53.507] Checking ssh with "ssh -V"
[12:50:53.512] > OpenSSH_8.1p1, LibreSSL 2.7.3

[12:50:53.515] askpass server listening on /var/folders/sy/kqyy8q9d2n76rlvflkxznxmc0000gn/T/vscode-ssh-askpass-a0fd5d76a0f7904d60d54534c62430a95c2aa3af.sock
[12:50:53.515] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/sy/kqyy8q9d2n76rlvflkxznxmc0000gn/T/vscode-ssh-askpass-dc32954239df8be82c4fbf7621748a6401c52272.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","52899","-o","ConnectTimeout=15","[ip]"],"dataFilePath":"/Users/fishdicks/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-67cb8c6e-6cba118ac49a1b88332f312a8f67186f7f3c1643-0.66.0/data.json"}
[12:50:53.516] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/fishdicks/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/fishdicks/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/sy/kqyy8q9d2n76rlvflkxznxmc0000gn/T/vscode-ssh-askpass-a0fd5d76a0f7904d60d54534c62430a95c2aa3af.sock"}
[12:50:53.517] Spawned 5425
[12:50:53.614] > local-server-1> Spawned ssh, pid=5430
[12:50:53.616] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[12:50:56.261] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:oPd8QavRg9SFqxrMH4GDrh5taiXJf3rhX/MRitar1bc
[12:50:58.521] Got askpass request: {"request":"muser727@[ip]'s password:"}
[12:50:58.522] Showing password prompt
[12:50:58.523] Listening for interwindow password on /var/folders/sy/kqyy8q9d2n76rlvflkxznxmc0000gn/T/vscode-ssh-askpass-ece4b6ef73b9708298b459636bb0547f16d3eb85.sock
[12:50:58.523] Writing password prompt to globalState
[12:51:05.871] Got password response
[12:51:05.871] Interactor gave response: **************
[12:51:05.872] Cleaning up other-window auth server
[12:51:06.489] stderr> Authenticated to [ip] ([ip]:22).
[12:51:08.452] > Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-1058-aws x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   System information as of Wed Nov  3 04:51:06 UTC 2021
> 
>   System load:  0.02               Processes:           127
>   Usage of /:   79.5% of 19.32GB   Users logged in:     1
>   Memory usage: 9%                 IP address for ens5: 172.31.41.37
>   Swap usage:   0%
> 
>  * Ubuntu Pro delivers the most comprehensive open source security and
>    compliance features.
> 
>    https://ubuntu.com/aws/pro
> 
>  * Canonical Livepatch is available for installation.
>    - Reduce system reboots and improve kernel security. Activate at:
>      https://ubuntu.com/livepatch
> 
> 72 packages can be updated.
> 1 update is a security update.
> 
> New release '20.04.3 LTS' available.
> Run 'do-release-upgrade' to upgrade to it.
> 
[12:51:10.977] > ready: 543eed16c8fb
[12:51:11.769] > Linux 5.4.0-1058-aws #61~18.04.3-Ubuntu SMP Fri Oct 1 14:04:01 UTC 2021
[12:51:11.770] Platform: linux
[12:51:11.959] > 543eed16c8fb: running
[12:51:21.316] > Acquiring lock on /home/muser727/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/vscode-remote-lock.muser727.6cba118ac49a1b88332f312a8f67186f7f3c1643
> Installing to /home/muser727/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643...
> 543eed16c8fb%%1%%
> Downloading with wget
[12:51:21.564] > Download complete
> 543eed16c8fb%%2%%
> tar --version:
> tar (GNU tar) 1.29
> Copyright (C) 2015 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
> Checking /home/muser727/.vscode-server/.6cba118ac49a1b88332f312a8f67186f7f3c1643.log and /home/muser727/.vscode-server/.6cba118ac49a1b88332f312a8f67186f7f3c1643.pid for a running server
> Starting server with command... /home/muser727/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/server.sh --start-server --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0  &> "/home/muser727/.vscode-server/.6cba118ac49a1b88332f312a8f67186f7f3c1643.log" < /dev/null
> printenv:
>     LC_ALL=en_US.UTF-8
>     SSH_CONNECTION=117.136.75.224 55790 172.31.41.37 22
>     LANG=C.UTF-8
>     SSH_AUTH_SOCK=/tmp/ssh-hElhULwtDq/agent.1815
>     S_COLORS=auto
>     XDG_SESSION_ID=3
>     USER=muser727
>     PWD=/home/muser727
>     HOME=/home/muser727
>     LC_CTYPE=
>     SSH_CLIENT=117.136.75.224 55790 22
>     XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
>     MAIL=/var/mail/muser727
>     SHELL=/bin/bash
>     SHLVL=2
>     VSCODE_AGENT_FOLDER=/home/muser727/.vscode-server
>     LOGNAME=muser727
>     XDG_RUNTIME_DIR=/run/user/1001
>     PATH=/home/muser727/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
>     _=/usr/bin/printenv
>     OLDPWD=/home/muser727/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643
> Spawned remote server: 1888
> Waiting for server log...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[12:51:21.565] stderr> rm: cannot remove '/home/muser727/.vscode-server/.6cba118ac49a1b88332f312a8f67186f7f3c1643.token': No such file or directory
[12:51:23.580] > 543eed16c8fb: start
> SSH_AUTH_SOCK==/tmp/ssh-hElhULwtDq/agent.1815==
> DISPLAY====
> webUiAccessToken====
> listeningOn==35857==
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/1001==
> platform==linux==
> unpackResult==success==
> didLocalDownload==0==
> downloadTime==661==
> installTime==1456==
> extInstallTime====
> serverStartTime==56==
> connectionToken==aa1a1111-1a11-1111-aaa1-a1a111a11111==
> 543eed16c8fb: end
[12:51:23.580] Received install output: 
SSH_AUTH_SOCK==/tmp/ssh-hElhULwtDq/agent.1815==
DISPLAY====
webUiAccessToken====
listeningOn==35857==
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/1001==
platform==linux==
unpackResult==success==
didLocalDownload==0==
downloadTime==661==
installTime==1456==
extInstallTime====
serverStartTime==56==
connectionToken==aa1a1111-1a11-1111-aaa1-a1a111a11111==

[12:51:23.581] Remote server is listening on 35857
[12:51:23.581] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":35857},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"/tmp/ssh-hElhULwtDq/agent.1815","display":"","tmpDir":"/run/user/1001","platform":"linux","connectionToken":"aa1a1111-1a11-1111-aaa1-a1a111a11111"},"downloadTime":661,"installTime":1456,"serverStartTime":56,"installUnpackCode":"success"}
[12:51:23.582] Persisting server connection details to /Users/fishdicks/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-67cb8c6e-6cba118ac49a1b88332f312a8f67186f7f3c1643-0.66.0/data.json
[12:51:23.584] Starting forwarding server. localPort 52915 -> socksPort 52899 -> remotePort 35857
[12:51:23.584] Forwarding server listening on 52915
[12:51:23.584] Waiting for ssh tunnel to be ready
[12:51:23.585] Tunneled 35857 to local port 52915
[12:51:23.585] Resolved "ssh-remote+[ip]" to "127.0.0.1:52915"
[12:51:23.586] Updating $SSH_AUTH_SOCK: ln -f -s "/tmp/ssh-hElhULwtDq/agent.1815" "/run/user/1001/vscode-ssh-auth-sock-125095799"
[12:51:23.586] Using cwd: vscode-remote://ssh-remote%2B[ip]/
[12:51:23.587] Remote extension host environment: {"SSH_AUTH_SOCK":"/run/user/1001/vscode-ssh-auth-sock-125095799"}
[12:51:23.589] [Forwarding server 52915] Got connection 0
[12:51:23.593] ------




[12:51:23.616] [Forwarding server 52915] Got connection 1
[12:51:28.837] [Forwarding server 52915] Got connection 2
[12:51:51.305] [Forwarding server 52915] Got connection 3
[12:51:53.366] ------




[12:51:53.366] SSH Resolver called for "ssh-remote+[ip]", attempt 2, (Reconnection)
[12:51:53.366] SSH Resolver called for host: [ip]
[12:51:53.367] Setting up SSH remote "[ip]"
[12:51:53.368] Acquiring local install lock: /var/folders/sy/kqyy8q9d2n76rlvflkxznxmc0000gn/T/vscode-remote-ssh-67cb8c6e-install.lock
[12:51:53.369] Looking for existing server data file at /Users/fishdicks/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-67cb8c6e-6cba118ac49a1b88332f312a8f67186f7f3c1643-0.66.0/data.json
[12:51:53.370] Found local server running: {"remoteListeningOn":{"port":35857},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"/tmp/ssh-hElhULwtDq/agent.1815","display":"","tmpDir":"/run/user/1001","platform":"linux","connectionToken":"aa1a1111-1a11-1111-aaa1-a1a111a11111","pid":5425,"ipcHandlePath":"/var/folders/sy/kqyy8q9d2n76rlvflkxznxmc0000gn/T/vscode-ssh-askpass-dc32954239df8be82c4fbf7621748a6401c52272.sock","socksPort":52899,"startupTime":1635915053517}
[12:51:53.370] Running server is stale. Ignoring
[12:51:53.370] Using commit id "6cba118ac49a1b88332f312a8f67186f7f3c1643" and quality "stable" for server
[12:51:53.374] Install and start server if needed
[12:51:53.377] askpass server listening on /var/folders/sy/kqyy8q9d2n76rlvflkxznxmc0000gn/T/vscode-ssh-askpass-13448f0958293ce7e8d9821700540ef87b811b9a.sock
[12:51:53.378] Spawning local server with {"serverId":2,"ipcHandlePath":"/var/folders/sy/kqyy8q9d2n76rlvflkxznxmc0000gn/T/vscode-ssh-askpass-7a44beb4e15be3da69725526a57b44c1ee0eabc7.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","52931","-o","ConnectTimeout=15","[ip]"],"dataFilePath":"/Users/fishdicks/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-67cb8c6e-6cba118ac49a1b88332f312a8f67186f7f3c1643-0.66.0/data.json"}
[12:51:53.378] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/fishdicks/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/fishdicks/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/sy/kqyy8q9d2n76rlvflkxznxmc0000gn/T/vscode-ssh-askpass-13448f0958293ce7e8d9821700540ef87b811b9a.sock"}
[12:51:53.379] Spawned 5448
[12:51:53.507] > local-server-2> Spawned ssh, pid=5453
[12:51:53.510] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[12:51:53.955] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:oPd8QavRg9SFqxrMH4GDrh5taiXJf3rhX/MRitar1bc
[12:51:55.790] Got askpass request: {"request":"muser727@[ip]'s password:"}
[12:51:55.790] Showing password prompt
[12:51:55.791] Listening for interwindow password on /var/folders/sy/kqyy8q9d2n76rlvflkxznxmc0000gn/T/vscode-ssh-askpass-f8fc649cf21cc151cc69eacf247b349ed2a3c538.sock
[12:51:55.791] Writing password prompt to globalState
[12:51:57.090] > local-server-1> Timed out
[12:51:57.090] Failed to set up socket for dynamic port forward to remote port 35857: Socket closed. Is the remote port correct?
[12:51:57.094] Local server exit: 0




It keeps letting me enter credential but does not work.

**Comment by kennylbj** [comment]
> i installed bash 5.0 and the problem is gone
@telnet01 thank you for the sharing. what is bash 5.0 and how do you install it? the link you provided is unavailable.

**Comment by telnet01** [comment]
> > i installed bash 5.0 and the problem is gone
> 
> @telnet01 thank you for the sharing. what is bash 5.0 and how do you install it? the link you provided is unavailable.

Link edited, i installed bash from source on remote machine where VS code server resides

**Comment by kennylbj** [comment]
Looks like it is my connection issue, resolved by using a "jump box" server.
