### ISSUE TITLE
Can't use shortcut to connect to host: "TypeError: Cannot read property 'hostName' of undefined"

### ISSUE THREAD

**Issue by a-gn** [microsoft/vscode-remote-release#5760]
- VSCode Version: 1.61.2
- Local OS Version: Darwin arm64 20.6.0
- Remote OS Version: Irrelevant (I haven't chosen a host to connect to)
- Remote Extension/Connection Type: SSH
- Logs:

```
[2021-10-25 09:26:17.604] [exthost] [error] TypeError: Cannot read property 'hostName' of undefined
	at c.openHostReuseWindow (/Users/arno/.vscode/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:377571)
	at l._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:111652)
	at l.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:112090)
	at i._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13802)
	at i._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13486)
	at i._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:12148)
	at i._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:10826)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:8922
	at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15990)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:30514
	at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15990)
	at u._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:21260)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:18138
	at a.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at w.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:13351)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:12699
	at Socket.v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:13465)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) opensshremotesexplorer.emptyWindowInCurrentWindow
```

Steps to Reproduce:

1. Start in a local VSCode window, not connected to any remote host.
2. In "Keyboard Shortcuts", add a shortcut for "Connect to Host in Current Window" (say Cmd + K, H).
3. Press that shortcut.

Expected result: the host menu shows up, so I can choose a host to connect to.

Actual result: a warning popup shows, saying: "Running the contributed command: 'opensshremotesexplorer.emptyWindowInCurrentWindow' failed.".

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by tanhakabir** [comment]
Hm I'm struggling to reproduce this. Would you be able to try on VS Code Insiders and see if you still see this issue?

**Comment by AG-LC** [comment]
I just tried again and it works now, on VSCode 1.62.0 as well as Insiders. Thanks for looking into it :)

**Comment by a-gn** [comment]
I just tried again and it works now, on VSCode 1.62.0 as well as Insiders. Thanks for looking into it :)
