### ISSUE TITLE
hangs after authenticated

### ISSUE THREAD

**Issue by balupton** [microsoft/vscode-remote-release#5773]
VSCode Version:

```
Version: 1.61.2 (Universal)
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T15:49:28.381Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
```

and

```
Version: 1.62.0-insider (Universal)
Commit: 45fdad3a10d437fb0a45cc008eecca7c35021fb2
Date: 2021-10-25T05:13:17.888Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
```

- Local OS Version: macOS 12.0.1 (21A559)
- Remote OS Version: Ubuntu Server 21.04 on a Raspberry Pi 4
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Try to connect to the raspberry pi ubuntu server host I've connected to dozens of times before
2. After upgrading the connecting machine to MacOS Monteray, I am no longer able to connect to it via vscode — via the macOS terminal I have no problem connecting

Log files of the failed vscode connection is as follows:

```
[09:31:54.172] Log Level: 2
[09:31:54.175] remote-ssh@0.65.8
[09:31:54.175] darwin x64
[09:31:54.176] SSH Resolver called for "ssh-remote+192.168.5.80", attempt 1
[09:31:54.177] "remote.SSH.useLocalServer": true
[09:31:54.180] "remote.SSH.path": undefined
[09:31:54.180] "remote.SSH.configFile": undefined
[09:31:54.180] "remote.SSH.useFlock": true
[09:31:54.181] "remote.SSH.lockfilesInTmp": false
[09:31:54.181] "remote.SSH.localServerDownload": auto
[09:31:54.181] "remote.SSH.remoteServerListenOnSocket": false
[09:31:54.181] "remote.SSH.showLoginTerminal": false
[09:31:54.182] "remote.SSH.defaultExtensions": ["skyapps.fish-vscode","wayou.vscode-todo-highlight","editorconfig.editorconfig","github.copilot","github.vscode-pull-request-github","eamodio.gitlens","esbenp.prettier-vscode","foxundermoon.shell-format","timonwong.shellcheck"]
[09:31:54.182] "remote.SSH.loglevel": 2
[09:31:54.183] SSH Resolver called for host: 192.168.5.80
[09:31:54.183] Setting up SSH remote "192.168.5.80"
[09:31:54.186] Acquiring local install lock: /var/folders/wm/8g56ry4s47z_hbt0tgv0m5gr0000gn/T/vscode-remote-ssh-9d7ebd39-install.lock
[09:31:54.198] Looking for existing server data file at /Users/balupton/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-9d7ebd39-45fdad3a10d437fb0a45cc008eecca7c35021fb2-0.65.8/data.json
[09:31:54.198] Using commit id "45fdad3a10d437fb0a45cc008eecca7c35021fb2" and quality "insider" for server
[09:31:54.201] Install and start server if needed
[09:31:54.205] PATH: /Users/balupton/bin:/Users/balupton/.dorothy/user/commands.local:/Users/balupton/.dorothy/user/commands:/Users/balupton/.dorothy/commands:/Users/balupton/.local/bin:/usr/local/Cellar/go/1.17.2/bin:/Users/balupton/.cargo/bin:/usr/local/opt/openssl/bin:/Users/balupton/Library/Python/3.9/bin:/Users/balupton/Library/Python/2.7/bin:/usr/local/opt/python/libexec/bin:/usr/local/Cellar/node/17.0.1/bin:/usr/local/Cellar/ruby/3.0.2_1/lib/ruby/gems/3.0.0/bin:/usr/local/lib/ruby/gems/3.0.0/bin:/Users/balupton/.gem/ruby/3.0.0/bin:/usr/local/opt/ruby/bin:/usr/local/opt/gettext/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/opt/sqlite/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[09:31:54.205] Checking ssh with "ssh -V"
[09:31:54.224] > OpenSSH_8.8p1, OpenSSL 1.1.1l  24 Aug 2021

[09:31:54.229] askpass server listening on /var/folders/wm/8g56ry4s47z_hbt0tgv0m5gr0000gn/T/vscode-ssh-askpass-46c2ad092217b196f82d2d363a0daac5de964f7f.sock
[09:31:54.229] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/wm/8g56ry4s47z_hbt0tgv0m5gr0000gn/T/vscode-ssh-askpass-44f69f1c40663a4d8800ffd41e7e1b718ab4f820.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","51021","-o","ConnectTimeout=90","192.168.5.80","bash"],"dataFilePath":"/Users/balupton/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-9d7ebd39-45fdad3a10d437fb0a45cc008eecca7c35021fb2-0.65.8/data.json"}
[09:31:54.230] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/balupton/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/balupton/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/wm/8g56ry4s47z_hbt0tgv0m5gr0000gn/T/vscode-ssh-askpass-46c2ad092217b196f82d2d363a0daac5de964f7f.sock"}
[09:31:54.232] Spawned 30380
[09:31:54.381] > local-server-1> Spawned ssh, pid=30405
[09:31:54.390] stderr> OpenSSH_8.8p1, OpenSSL 1.1.1l  24 Aug 2021
[09:31:54.460] stderr> debug1: Server host key: ssh-ed25519 SHA256:redacted
[09:31:54.511] stderr> Authenticated to 192.168.5.80 ([192.168.5.80]:22) using "publickey".
[09:33:26.231] Terminating local server
[09:33:26.233] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/balupton/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:397167)
	at Timeout._onTimeout (/Users/balupton/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/extension.js:1:441410)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[09:33:26.239] Local server exit: 15
[09:33:26.244] ------
```

<img width="352" alt="CleanShot 2021-10-26 at 09 33 45@2x" src="https://user-images.githubusercontent.com/61148/138793619-49418f30-0ab0-4200-ac62-d9829cb6cae4.png">

Works just fine to another raspberry pi ubuntu server:

```
[09:28:20.812] Log Level: 2
[09:28:20.814] remote-ssh@0.65.8
[09:28:20.814] darwin x64
[09:28:20.815] SSH Resolver called for "ssh-remote+192.168.5.40", attempt 1
[09:28:20.816] "remote.SSH.useLocalServer": true
[09:28:20.819] "remote.SSH.path": undefined
[09:28:20.820] "remote.SSH.configFile": undefined
[09:28:20.820] "remote.SSH.useFlock": true
[09:28:20.820] "remote.SSH.lockfilesInTmp": false
[09:28:20.820] "remote.SSH.localServerDownload": auto
[09:28:20.821] "remote.SSH.remoteServerListenOnSocket": false
[09:28:20.821] "remote.SSH.showLoginTerminal": false
[09:28:20.821] "remote.SSH.defaultExtensions": ["skyapps.fish-vscode","wayou.vscode-todo-highlight","editorconfig.editorconfig","github.copilot","github.vscode-pull-request-github","eamodio.gitlens","esbenp.prettier-vscode","foxundermoon.shell-format","timonwong.shellcheck"]
[09:28:20.822] "remote.SSH.loglevel": 2
[09:28:20.822] SSH Resolver called for host: 192.168.5.40
[09:28:20.822] Setting up SSH remote "192.168.5.40"
[09:28:20.825] Acquiring local install lock: /var/folders/wm/8g56ry4s47z_hbt0tgv0m5gr0000gn/T/vscode-remote-ssh-a59cdee5-install.lock
[09:28:20.838] Looking for existing server data file at /Users/balupton/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-a59cdee5-45fdad3a10d437fb0a45cc008eecca7c35021fb2-0.65.8/data.json
[09:28:20.839] Using commit id "45fdad3a10d437fb0a45cc008eecca7c35021fb2" and quality "insider" for server
[09:28:20.841] Install and start server if needed
[09:28:20.845] PATH: /Users/balupton/bin:/Users/balupton/.dorothy/user/commands.local:/Users/balupton/.dorothy/user/commands:/Users/balupton/.dorothy/commands:/Users/balupton/.local/bin:/usr/local/Cellar/go/1.17.2/bin:/Users/balupton/.cargo/bin:/usr/local/opt/openssl/bin:/Users/balupton/Library/Python/3.9/bin:/Users/balupton/Library/Python/2.7/bin:/usr/local/opt/python/libexec/bin:/usr/local/Cellar/node/17.0.1/bin:/usr/local/Cellar/ruby/3.0.2_1/lib/ruby/gems/3.0.0/bin:/usr/local/lib/ruby/gems/3.0.0/bin:/Users/balupton/.gem/ruby/3.0.0/bin:/usr/local/opt/ruby/bin:/usr/local/opt/gettext/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/opt/sqlite/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[09:28:20.845] Checking ssh with "ssh -V"
[09:28:20.859] > OpenSSH_8.8p1, OpenSSL 1.1.1l  24 Aug 2021

[09:28:20.863] askpass server listening on /var/folders/wm/8g56ry4s47z_hbt0tgv0m5gr0000gn/T/vscode-ssh-askpass-acac26073b7b4c303247c0529de78816642f5060.sock
[09:28:20.864] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/wm/8g56ry4s47z_hbt0tgv0m5gr0000gn/T/vscode-ssh-askpass-4e1f79b8817e5ed7740ec49bdb32bf08d9622e49.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","50916","-o","ConnectTimeout=90","192.168.5.40","bash"],"dataFilePath":"/Users/balupton/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-a59cdee5-45fdad3a10d437fb0a45cc008eecca7c35021fb2-0.65.8/data.json"}
[09:28:20.864] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/balupton/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer)","VSCODE_SSH_ASKPASS_MAIN":"/Users/balupton/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.65.8/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/wm/8g56ry4s47z_hbt0tgv0m5gr0000gn/T/vscode-ssh-askpass-acac26073b7b4c303247c0529de78816642f5060.sock"}
[09:28:20.865] Spawned 29314
[09:28:20.992] > local-server-1> Spawned ssh, pid=29336
[09:28:20.999] stderr> OpenSSH_8.8p1, OpenSSL 1.1.1l  24 Aug 2021
[09:28:21.073] stderr> debug1: Server host key: ssh-ed25519 SHA256: redacted
[09:28:21.121] stderr> Authenticated to 192.168.5.40 ([192.168.5.40]:22) using "publickey".
[09:28:25.820] > ready: ce205a707264
[09:28:25.831] > Linux 5.11.0-1021-raspi #22-Ubuntu SMP PREEMPT Wed Oct 6 17:30:38 UTC 2021
[09:28:25.832] Platform: linux
[09:28:25.910] > ce205a707264: running
[09:28:26.004] > Acquiring lock on /home/ubuntu/.vscode-server-insiders/bin/45fdad3a10d437fb0a45cc008eecca7c35021fb2/vscode-remote-lock.ubuntu.45fdad3a10d437fb0a45cc008eecca7c35021fb2
[09:28:26.027] > Found existing installation at /home/ubuntu/.vscode-server-insiders/bin/45fdad3a10d437fb0a45cc008eecca7c35021fb2...
> Checking /home/ubuntu/.vscode-server-insiders/.45fdad3a10d437fb0a45cc008eecca7c35021fb2.log and /home/ubuntu/.vscode-server-insiders/.45fdad3a10d437fb0a45cc008eecca7c35021fb2.pid for a running server
[09:28:26.034] > Looking for server with pid: 30607
[09:28:26.093] > Found running server...
> Installing extensions...
[09:28:26.912] > Installing extensions...
[09:28:26.921] > Extension 'skyapps.fish-vscode' v0.2.1 is already installed. Use '--force' option to update to latest version or provide '@<version>' to install a specific version, for example: 'skyapps.fish-vscode@1.2.3'.
> Extension 'wayou.vscode-todo-highlight' v1.0.4 is already installed. Use '--force' option to update to latest version or provide '@<version>' to install a specific version, for example: 'wayou.vscode-todo-highlight@1.2.3'.
[09:28:26.922] > Extension 'editorconfig.editorconfig' v0.16.4 is already installed. Use '--force' option to update to latest version or provide '@<version>' to install a specific version, for example: 'editorconfig.editorconfig@1.2.3'.
> Extension 'github.copilot' v1.6.3450 is already installed. Use '--force' option to update to latest version or provide '@<version>' to install a specific version, for example: 'github.copilot@1.2.3'.
> Extension 'github.vscode-pull-request-github' v0.31.1 is already installed. Use '--force' option to update to latest version or provide '@<version>' to install a specific version, for example: 'github.vscode-pull-request-github@1.2.3'.
> Extension 'eamodio.gitlens' v11.6.1 is already installed. Use '--force' option to update to latest version or provide '@<version>' to install a specific version, for example: 'eamodio.gitlens@1.2.3'.
> Extension 'esbenp.prettier-vscode' v9.0.0 is already installed. Use '--force' option to update to latest version or provide '@<version>' to install a specific version, for example: 'esbenp.prettier-vscode@1.2.3'.
[09:28:26.922] > Extension 'foxundermoon.shell-format' v7.1.1 is already installed. Use '--force' option to update to latest version or provide '@<version>' to install a specific version, for example: 'foxundermoon.shell-format@1.2.3'.
> Extension 'timonwong.shellcheck' v0.18.1 is already installed. Use '--force' option to update to latest version or provide '@<version>' to install a specific version, for example: 'timonwong.shellcheck@1.2.3'.
[09:28:26.967] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[09:28:27.009] > Checking server status on port 43515 with wget
[09:28:27.028] > ce205a707264: start
> SSH_AUTH_SOCK==/tmp/ssh-3NG2lEJy1rgF/agent.32294==
> DISPLAY====
> webUiAccessToken====
> listeningOn==43515==
> osReleaseId==ubuntu==
[09:28:27.029] > arch==aarch64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime==854==
> serverStartTime====
> connectionToken== redacted ==
> ce205a707264: end
[09:28:27.030] Received install output: 
SSH_AUTH_SOCK==/tmp/ssh-3NG2lEJy1rgF/agent.32294==
DISPLAY====
webUiAccessToken====
listeningOn==43515==
osReleaseId==ubuntu==arch==aarch64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime==854==
serverStartTime====
connectionToken==redacted==

[09:28:27.030] Remote server is listening on 43515
[09:28:27.031] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":43515},"osReleaseId":"ubuntu","arch":"aarch64","webUiAccessToken":"","sshAuthSock":"/tmp/ssh-3NG2lEJy1rgF/agent.32294","display":"","tmpDir":"/run/user/1000","platform":"linux","connectionToken":"11aa11aa-1a1a-11aa-a111-1aa1a1a1aaaa"},"extInstallTime":854,"installUnpackCode":""}
[09:28:27.031] ** Note: Support for architecture "aarch64" is in preview **
[09:28:27.032] Persisting server connection details to /Users/balupton/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-a59cdee5-45fdad3a10d437fb0a45cc008eecca7c35021fb2-0.65.8/data.json
[09:28:27.040] Starting forwarding server. localPort 50923 -> socksPort 50916 -> remotePort 43515
[09:28:27.040] Forwarding server listening on 50923
[09:28:27.040] Waiting for ssh tunnel to be ready
[09:28:27.042] Tunneled 43515 to local port 50923
[09:28:27.042] Resolved "ssh-remote+192.168.5.40" to "127.0.0.1:50923"
[09:28:27.043] Updating $SSH_AUTH_SOCK: ln -f -s "/tmp/ssh-3NG2lEJy1rgF/agent.32294" "/run/user/1000/vscode-ssh-auth-sock-935617472"
[09:28:27.043] Using cwd: vscode-remote://ssh-remote%2B192.168.5.40/
[09:28:27.044] Remote extension host environment: {"SSH_AUTH_SOCK":"/run/user/1000/vscode-ssh-auth-sock-935617472"}
[09:28:27.045] [Forwarding server 50923] Got connection 0
[09:28:27.055] ------
```

**Comment by balupton** [comment]
@roblourens turns out my dotfiles executed a command that would also read from `stdin`, which would mangle the stdin that was passed to ssh. I had to update my dotfiles to prevent reading from stdin upon initialisation.
