### ISSUE TITLE
Failed to connect to the remote extension host server (Error: The process tried to write to a nonexistent pipe)

### ISSUE THREAD

**Issue by Bc137** [microsoft/vscode-remote-release#5802]
Issue Type: <b>Bug</b>

Have latest vscode installed with remote ssh extension

Open explorer and try to connect to linux host via remote ssh in my case I have tried ubuntu 20.04 or raspbian .
ssh user@host 
whether using the config file or ad hoc commands or passwordd auth or ssh keys I get this samer erro 

Failed to connect to the remote extension host server (Error: The process tried to write to a nonexistent pipe)

[04:08:01.829] Log Level: 2
[04:08:01.837] remote-ssh@0.65.8
[04:08:01.837] win32 x64
[04:08:01.838] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a223139322e3136382e312e313036222c2275736572223a22737368207069227d", attempt 1
[04:08:01.839] "remote.SSH.useLocalServer": false
[04:08:01.839] "remote.SSH.showLoginTerminal": false
[04:08:01.840] "remote.SSH.remotePlatform": {}
[04:08:01.840] "remote.SSH.path": undefined
[04:08:01.840] "remote.SSH.configFile": undefined
[04:08:01.840] "remote.SSH.useFlock": true
[04:08:01.841] "remote.SSH.lockfilesInTmp": false
[04:08:01.841] "remote.SSH.localServerDownload": auto
[04:08:01.841] "remote.SSH.remoteServerListenOnSocket": false
[04:08:01.841] "remote.SSH.showLoginTerminal": false
[04:08:01.841] "remote.SSH.defaultExtensions": []
[04:08:01.842] "remote.SSH.loglevel": 2
[04:08:01.842] SSH Resolver called for host: ssh pi@192.168.1.106
[04:08:01.842] Setting up SSH remote "redacted"
[04:08:01.881] Using commit id "6cba118ac49a1b88332f312a8f67186f7f3c1643" and quality "stable" for server
[04:08:01.886] Install and start server if needed
[04:08:03.623] Checking ssh with "ssh -V"
[04:08:03.681] > OpenSSH_for_Windows
[04:08:03.681] > _8.1p1, LibreSSL 3.0.2

[04:08:03.687] Running script with connection command: ssh -T -D 56236 "ssh pi@redacted" bash
[04:08:03.690] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[04:08:03.942] > ]0;C:\WINDOWS\System32\cmd.exe
[04:08:03.942] Got some output, clearing connection timeout
[04:08:04.232] > The authenticity of host 'redacted (redacted)' can't be established.
> ECDSA key fingerprint is SHA256:I/7CGZ156bcyRiZqbnIRt6DhO8zEi6WQs29ZnF8Yyx0.  
> Are you sure you want to continue connecting (yes/no/[fingerprint])?
[04:08:04.233] Detected fingerprint confirmation message
[04:08:04.233] Showing fingerprint confirmation dialog
[04:08:07.870] Got fingerprint response: yes
[04:08:07.870] "install" wrote data to terminal: "yes"
[04:08:07.887] > y
[04:08:07.897] > Are you sure you want to continue connecting (yes/no/[fingerprint])? yes      
> Warning: Permanently added 'redacted' (ECDSA) to the list of known hosts.
[04:08:07.911] > ssh pi@redacted password: 
[04:08:07.912] Showing password prompt
[04:08:10.280] Got password response
[04:08:10.281] "install" wrote data to terminal: ""
[04:08:10.295] > 
[04:08:10.312] > Permission denied, please try again.
> ssh pi@redacted password:    
[04:08:10.312] Showing password prompt
[04:08:14.078] Got password response
[04:08:14.078] "install" wrote data to terminal: "**********"
[04:08:14.096] > 
[04:08:16.992] > Permission denied, please try again.
[04:08:17.001] > ssh pi@redacted password: 
[04:08:17.001] Showing password prompt
[04:08:21.225] Got password response
[04:08:21.225] "install" wrote data to terminal: "**********"
[04:08:21.242] > 
[04:08:24.138] > ssh pi@redacted: Permission denied (publickey,password).
[04:08:24.153] > The process tried to write to a nonexistent pipe.
[04:08:25.472] "install" terminal command done
[04:08:25.473] Install terminal quit with output: The process tried to write to a nonexistent pipe.
[04:08:25.473] Received install output: The process tried to write to a nonexistent pipe.
[04:08:25.474] Resolver error: Error: The process tried to write to a nonexistent pipe
	at Function.Offline (c:\Users\redacted\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:397092)
	at c:\Users\redacted\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:394642
	at Object.t.handleInstallOutput (c:\Users\redacted\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:395020)
	at Object.t.tryInstall (c:\Users\redacted\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:489314)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\redacted\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:453110
	at async Object.t.withShowDetailsEvent (c:\Users\Brayd\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:456460)
	at async Object.t.resolve (c:\Users\Brayd\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:454189)
	at async c:\Users\Brayd\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:526942
[04:08:25.481] ------

Extension version: 0.65.8
VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Fetching remote diagnostics for 'SSH' failed: The process tried to write to a nonexistent pipe

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (10.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH' failed: The process tried to write to a nonexistent pipe
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by tanhakabir** [comment]
Hey! It looks like the actual error is `ssh pi@redacted: Permission denied (publickey,password).` Are you able to connect to your remote in PowerShell or whatever you default shell is? `ssh pi@redacted`

**Comment by tothedistance** [comment]
```
[14:30:33.584] Log Level: 2
[14:30:33.585] remote-ssh@0.65.8
[14:30:33.585] win32 x64
[14:30:33.586] SSH Resolver called for "ssh-remote+ai1", attempt 1
[14:30:33.586] "remote.SSH.useLocalServer": false
[14:30:33.586] "remote.SSH.showLoginTerminal": false
[14:30:33.586] "remote.SSH.remotePlatform": {"ai1":"linux"}
[14:30:33.586] "remote.SSH.path": undefined
[14:30:33.586] "remote.SSH.configFile": C:/Users/admin/.ssh/config
[14:30:33.587] "remote.SSH.useFlock": true
[14:30:33.587] "remote.SSH.lockfilesInTmp": false
[14:30:33.587] "remote.SSH.localServerDownload": auto
[14:30:33.587] "remote.SSH.remoteServerListenOnSocket": false
[14:30:33.587] "remote.SSH.showLoginTerminal": false
[14:30:33.587] "remote.SSH.defaultExtensions": []
[14:30:33.587] "remote.SSH.loglevel": 2
[14:30:33.587] SSH Resolver called for host: ai1
[14:30:33.587] Setting up SSH remote "ai1"
[14:30:33.599] Using commit id "6cba118ac49a1b88332f312a8f67186f7f3c1643" and quality "stable" for server
[14:30:33.601] Install and start server if needed
[14:30:33.617] Checking ssh with "ssh -V"
[14:30:33.653] > OpenSSH_5.4p1, OpenSSL 1.0.0 29 Mar 2010

[14:30:33.656] Using SSH config file "C:/Users/admin/.ssh/config"
[14:30:33.656] Running script with connection command: ssh -T -D 63360 -F "C:/Users/admin/.ssh/config" ai1 bash
[14:30:33.657] Terminal shell path: C:\Windows\System32\cmd.exe
[14:30:33.957] > Permission denied (publickey).]0;C:\Windows\System32\cmd.exe
[14:30:33.957] Got some output, clearing connection timeout
[14:30:33.970] > 
> The process tried to write to a nonexistent pipe.
[14:30:35.243] "install" terminal command done
[14:30:35.244] Install terminal quit with output: The process tried to write to a nonexistent pipe.
[14:30:35.244] Received install output: The process tried to write to a nonexistent pipe.
[14:30:35.244] Resolver error: Error: The process tried to write to a nonexistent pipe
	at Function.Offline (c:\Users\admin\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:397092)
	at c:\Users\admin\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:394642
	at Object.t.handleInstallOutput (c:\Users\admin\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:395020)
	at Object.t.tryInstall (c:\Users\admin\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:489314)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\admin\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:453110
	at async Object.t.withShowDetailsEvent (c:\Users\admin\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:456460)
	at async Object.t.resolve (c:\Users\admin\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:454189)
	at async c:\Users\admin\.vscode\extensions\ms-vscode-remote.remote-ssh-0.65.8\out\extension.js:1:526942
[14:30:35.247] ------
```
I am able to ssh in with powershell, powershell 7, cmd, windows terminal conda profile(ps7), windows terminal wsl. 
I am not able to ssh in with powershell7 in integrated terminal.
`ssh.exe": Could not resolve hostname ai1: no address associated with name`

**Comment by tothedistance** [comment]
all of a sudden, i can ssh in with the extension version revert to 0.65.8, i guess the revert need some time to take effect.

**Comment by Bclrk2021** [comment]
@tothedistance  thank you I do not know how I didn't notice the resolve error I chose I.P instead of the hostname and it worked. Need to figure out why my DNS was not working correctly

**Comment by Bclrk2021** [comment]
> Hey! It looks like the actual error is `ssh pi@redacted: Permission denied (publickey,password).` Are you able to connect to your remote in PowerShell or whatever you default shell is? `ssh pi@redacted`

I fatfingered my credential a few times but @tothedistance  pointed out my DNS was not resolving.

**Comment by tothedistance** [comment]
I upgraded to 0.66.0. and still works now. have no idea why. maybe I didn't close my computer for too long and I did a reboot this afternoon. sorry to bother you.

**Comment by tanhakabir** [comment]
No worries @tothedistance! Happy both you got it working in the end!

@Bclrk2021 I'll close this issue for now since it seems like a DNS issue but let me know if you end up connecting through PowerShell but not VS Code
