### ISSUE TITLE
Buildkit does not work with `docker-compose`.

### ISSUE THREAD

**Issue by mrmachine** [microsoft/vscode-remote-release#5804]
- VSCode Version: Version: 1.61.2 (Universal)
- Local OS Version: macOS 11.6
- Remote OS Version: `alpine` image
- Remote Extension/Connection Type: Docker
- Logs:

```
[130 ms] Remote-Containers 0.202.5 in VS Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643).
[130 ms] Start: Resolving Remote
[131 ms] Setting up container for folder or workspace: /Users/tailee/foo
[137 ms] Start: Check Docker is running
[137 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[257 ms] Server API version: 1.41
[261 ms] Start: Run: docker-compose version --short
[574 ms] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=foo --filter label=com.docker.compose.service=foo
[707 ms] Start: Run: docker-compose -f /Users/tailee/foo/docker-compose.yml config
[1034 ms] services:
  foo:
    build:
      context: /Users/tailee/foo
version: '2.4'

[1034 ms] 
[1036 ms] Start: Run: docker events --format {{json .}} --filter event=start
[1037 ms] Start: Run: docker-compose --project-name foo -f /Users/tailee/foo/docker-compose.yml build
Building foo
WARN[0000] No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load 
[+] Building 3.6s (6/6) FINISHED                                                                                                                            
 => [internal] load build definition from Dockerfile                                                                                                   0.0s
 => => transferring dockerfile: 100B                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                                                                       3.5s
 => [auth] library/alpine:pull token for registry-1.docker.io                                                                                          0.0s
 => [stage-0 1/2] FROM docker.io/library/alpine@sha256:e1c082e3d3c45cccac829840a25941e679c25d438cc8412c2fa221cf1a824e6a                                0.0s
 => => resolve docker.io/library/alpine@sha256:e1c082e3d3c45cccac829840a25941e679c25d438cc8412c2fa221cf1a824e6a                                        0.0s
 => CACHED [stage-0 2/2] RUN --mount="type=cache,target=/root/.cache" true                                                                             0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 368, in build
  File "compose/project.py", line 519, in build
  File "compose/project.py", line 501, in build_service
  File "compose/service.py", line 1111, in build
  File "compose/service.py", line 1950, in build
IndexError: list index out of range
[52758] Failed to execute script docker-compose
[5876 ms] Command failed: docker-compose --project-name foo -f /Users/tailee/foo/docker-compose.yml build
```

Steps to Reproduce:

`.devcontainer.json`:

```
{
	"dockerComposeFile": [
		"docker-compose.yml"
	],
	"service": "foo",
	"workspaceFolder": "/root"
}
```

`Dockerfile`:

```
FROM alpine

RUN --mount="type=cache,target=/root/.cache" true
```

`docker-compose.yml`:

```
version: '2.4'

services:
  foo:
    build: .
```

Does this issue occur when you try this locally?:

**Yes** with `docker-compose`:

```shell
$ docker-compose build
Building foo
WARN[0000] No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load 
[+] Building 1.2s (5/5) FINISHED                                                                                                                                                                          
 => [internal] load build definition from Dockerfile                                                                                                                                                 0.0s
 => => transferring dockerfile: 100B                                                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                                                    0.0s
 => => transferring context: 2B                                                                                                                                                                      0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                                                                                                                     1.1s
 => [stage-0 1/2] FROM docker.io/library/alpine@sha256:e1c082e3d3c45cccac829840a25941e679c25d438cc8412c2fa221cf1a824e6a                                                                              0.0s
 => => resolve docker.io/library/alpine@sha256:e1c082e3d3c45cccac829840a25941e679c25d438cc8412c2fa221cf1a824e6a                                                                                      0.0s
 => CACHED [stage-0 2/2] RUN --mount="type=cache,target=/root/.cache" true                                                                                                                           0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 368, in build
  File "compose/project.py", line 519, in build
  File "compose/project.py", line 501, in build_service
  File "compose/service.py", line 1111, in build
  File "compose/service.py", line 1950, in build
IndexError: list index out of range
[52852] Failed to execute script docker-compose
```

**No** with `docker compose`:

```shell
$ docker compose build
[+] Building 4.4s (7/7) FINISHED                                                                                                                                                                          
 => [internal] load build definition from Dockerfile                                                                                                                                                 0.0s
 => => transferring dockerfile: 100B                                                                                                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                                                    0.0s
 => => transferring context: 2B                                                                                                                                                                      0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                                                                                                                     3.7s
 => [auth] library/alpine:pull token for registry-1.docker.io                                                                                                                                        0.0s
 => [stage-0 1/2] FROM docker.io/library/alpine@sha256:e1c082e3d3c45cccac829840a25941e679c25d438cc8412c2fa221cf1a824e6a                                                                              0.0s
 => => resolve docker.io/library/alpine@sha256:e1c082e3d3c45cccac829840a25941e679c25d438cc8412c2fa221cf1a824e6a                                                                                      0.0s
 => => sha256:e1c082e3d3c45cccac829840a25941e679c25d438cc8412c2fa221cf1a824e6a 1.64kB / 1.64kB                                                                                                       0.0s
 => => sha256:b06a5cf61b2956088722c4f1b9a6f71dfe95f0b1fe285d44195452b8a1627de7 528B / 528B                                                                                                           0.0s
 => => sha256:bb3de5531c18f185667b0be0e400ab24aa40f4440093de82baf4072e14af3b84 1.49kB / 1.49kB                                                                                                       0.0s
 => [stage-0 2/2] RUN --mount="type=cache,target=/root/.cache" true                                                                                                                                  0.5s
 => exporting to image                                                                                                                                                                               0.0s
 => => exporting layers                                                                                                                                                                              0.0s
 => => writing image sha256:3970e1a02dab9330472785471de4486e25f7c806e8dcb0ff6ee212c5b12d6604                                                                                                         0.0s
 => => naming to docker.io/library/foo_foo                                                                                                                                                           0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
```

I found this relevant compose issue: https://github.com/docker/compose/issues/8590

So, this might not strictly be an issue with vscode-remote. But, can we have an option to switch to `docker compose` instead of `docker-compose`?

**Comment by chrmarti** [comment]
Not sure how you installed Docker, but the latest Docker Desktop versions support forwarding `docker-compose` to `docker compose`. Have you tried that? (Also see https://docs.docker.com/compose/cli-command/#installing-compose-v2 for details.)

**Comment by chrmarti** [comment]
Worth mentioning: The extension automatically uses `docker compose` when there is no `docker-compose` executable on the PATH.

**Comment by mrmachine** [comment]
Thanks. I didn't know about the Docker Desktop preference. That does seem to allow me to build via `docker-compose` with buildkit. However, that preference (or removing `docker-compose` from `PATH`) are nuclear/global options. It would be nice if we could specify `docker-compose` (v1) or `docker compose` (v2) via `devcontainer.json`.

**Comment by chrmarti** [comment]
Just for my understanding: What are the differences between the two that would make you use v1 over v2? (My assumption so far was that v2 is largely backwards compatible with v1.)

**Comment by mrmachine** [comment]
I don't have any concrete experience with Compose v2, except for that mentioned in this issue.

Last I read about it, Compose v2 was still not GA, not the default, no "standard" way to install on Linux, and only supported "most" of the v1 features and flags.

Re-reading the compatibility docs page now, there does not appear to be any significant omissions listed. But as seen here, and based on past experience with the compose file format v2/v3 compatibility, I have doubts that it will be a perfectly safe drop in replacement for everyone. 

Docker's own documentation and implementation suggests that an easy way to revert to v1 is important during this transition.

**Comment by chrmarti** [comment]
I expect Compose v2 to work the same with the various Compose file versions as Compose v1. The CLI versions and the file versions are distinct. If Compose v2 causes issues, I suggest to revert your installation to Compose v1, Remote-Containers will just use the installed version.
