### ISSUE TITLE
remote-SSH stuck at Acquiring lock on a file

### ISSUE THREAD

**Issue by woodwm** [microsoft/vscode-remote-release#5822]
- VSCode Version: 1.61.2
- Local OS Version: Windows 10 20H2
- Remote OS Version: Ubuntu 20.4
- Remote Extension/Connection Type: SSH
- Logs:

```
[15:01:48.845] Log Level: 2
[15:01:48.846] remote-ssh@0.66.0
[15:01:48.846] win32 x64
[15:01:48.848] SSH Resolver called for "ssh-remote+force", attempt 1
[15:01:48.849] "remote.SSH.useLocalServer": false
[15:01:48.849] "remote.SSH.showLoginTerminal": false
[15:01:48.850] "remote.SSH.remotePlatform": {--------}          %% deleted
[15:01:48.850] "remote.SSH.path": undefined
[15:01:48.850] "remote.SSH.configFile": undefined
[15:01:48.850] "remote.SSH.useFlock": true
[15:01:48.851] "remote.SSH.lockfilesInTmp": false
[15:01:48.851] "remote.SSH.localServerDownload": auto
[15:01:48.851] "remote.SSH.remoteServerListenOnSocket": false
[15:01:48.851] "remote.SSH.showLoginTerminal": false
[15:01:48.852] "remote.SSH.defaultExtensions": []
[15:01:48.852] "remote.SSH.loglevel": 2
[15:01:48.852] SSH Resolver called for host: force
[15:01:48.852] Setting up SSH remote "force"
[15:01:48.860] Using commit id "6cba118ac49a1b88332f312a8f67186f7f3c1643" and quality "stable" for server
[15:01:48.868] Install and start server if needed
[15:01:48.877] Checking ssh with "ssh -V"
[15:01:49.098] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[15:01:49.111] Running script with connection command: ssh -T -D 55467 force bash
[15:01:49.115] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:01:49.574] > ]0;C:\WINDOWS\System32\cmd.exe
[15:01:49.574] Got some output, clearing connection timeout
[15:01:50.014] > c52d179ebb37: running
[15:01:50.191] > Acquiring lock on ----------/unix/.vscode-server/bin/6cba118ac49a1b88332f312a8
> f67186f7f3c1643/vscode-remote-lock.zhaow6.6cba118ac49a1b88332f312a8f67186f7f3c16
> 43
[15:03:47.356] > c52d179ebb37: running
> Acquiring lock on ---------/unix/.vscode-server/bin/6cba118ac49a1b88332f312a8f67186f7f3c1643/vscode-remote-lock.zhaow6.6cba118
> ac49a1b88332f312a8f67186f7f3c1643
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[15:03:54.585] "install" terminal command done
[15:03:54.586] Install terminal quit with output: ac49a1b88332f312a8f67186f7f3c1643
[15:03:54.587] Received install output: ac49a1b88332f312a8f67186f7f3c1643
[15:03:54.589] Failed to parse remote port from server output
[15:03:54.592] Resolver error: Error: 
	at Function.Create (c:\Users\--------\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:429193)
	at Object.t.handleInstallOutput (c:\Users\--------\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:427836)
	at Object.t.tryInstall (c:\Users\--------\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:521609)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\--------\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:485262
	at async Object.t.withShowDetailsEvent (c:\Users\--------\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:488612)
	at async Object.t.resolve (c:\Users\--------\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:486341)
	at async c:\Users\--------\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:559963
[15:03:54.601] ------
```

The file that it tries to lock is an empty file. I tried deleting it, but this does not work.

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by tanhakabir** [comment]
Hey! Hm would you be able to delete `.vscode-server` on your remote and try connecting again through the extension?

**Comment by woodwm** [comment]
Hi, I tried deleting the folder `.vscode-server`,  and the problem is the same. I have no problem to connect to the server using the same ssh configuration.

**Comment by tanhakabir** [comment]
> I have no problem to connect to the server using the same ssh configuration.

Do you mean you've tried connecting with powershell or another shell?

@roblourens have you seen issues in the past with acquiring locks in the remote?

**Comment by woodwm** [comment]
Yes, both powershell and git bash works.

**Comment by roblourens** [comment]
We use the `flock` command to get a lock, and it seems like that hung/didn't return. Is there any reason that would work differently on your system?

Can you work around it by disabling the `"remote.SSH.useFlock"` setting?

**Comment by woodwm** [comment]
Hi, after disable `remote.SSH.useFlock`, remote-ssh seems cannot connect to the server. It keeps trying and after trying more than 20 times, it fails.

**Comment by roblourens** [comment]
Seems that something is going on with your system. If you want to investigate, I can share the commands that we run with flock in the install script.

**Comment by hwangdeyu** [comment]
> Hi, after disable `remote.SSH.useFlock`, remote-ssh seems cannot connect to the server. It keeps trying and after trying more than 20 times, it fails.

Hi @woodwm , how do you fix this issue. I meet the same problem.
