### ISSUE TITLE
Remote SSH: The VS Code Server failed to start

### ISSUE THREAD

**Issue by matzuu** [microsoft/vscode-remote-release#5832]
- VSCode Version: 1.62.0 
- Local OS Version: Windows 10 , 10.0.19042
- Remote OS Version: Linux Ubuntu 20.04.2 LTS
- Remote Extension/Connection Type: SSH
- Logs:
`
[15:36:40.271] Log Level: 2
[15:36:40.277] remote-ssh@0.66.0
[15:36:40.277] win32 x64
[15:36:40.278] SSH Resolver called for "ssh-remote+143.205.173.100", attempt 1
[15:36:40.279] "remote.SSH.useLocalServer": false
[15:36:40.280] "remote.SSH.showLoginTerminal": false
[15:36:40.280] "remote.SSH.remotePlatform": {"gpu2.itec.aau.at":"linux","gpu3.itec.aau.at":"linux","articonf1.itec.aau.at":"linux","gpu1.itec.aau.at":"linux"}
[15:36:40.280] "remote.SSH.path": undefined
[15:36:40.280] "remote.SSH.configFile": undefined
[15:36:40.281] "remote.SSH.useFlock": true
[15:36:40.281] "remote.SSH.lockfilesInTmp": false
[15:36:40.281] "remote.SSH.localServerDownload": auto
[15:36:40.282] "remote.SSH.remoteServerListenOnSocket": false
[15:36:40.282] "remote.SSH.showLoginTerminal": false
[15:36:40.282] "remote.SSH.defaultExtensions": []
[15:36:40.285] "remote.SSH.loglevel": 2
[15:36:40.286] SSH Resolver called for host: 143.205.173.100
[15:36:40.286] Setting up SSH remote "143.205.173.100"
[15:36:40.309] Using commit id "b3318bc0524af3d74034b8bb8a64df0ccf35549a" and quality "stable" for server
[15:36:40.313] Install and start server if needed
[15:36:44.742] Checking ssh with "ssh -V"
[15:36:44.780] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.
[15:36:44.781] > 0.2

[15:36:44.785] Running script with connection command: ssh -T -D 50075 "143.205.173.100" bash
[15:36:44.788] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:36:45.054] > ]0;C:\WINDOWS\System32\cmd.exe
[15:36:45.054] Got some output, clearing connection timeout
[15:36:52.356] > 7b850ab73200: running
[15:36:53.166] > Acquiring lock on /home/ubuntu/.vscode-server/bin/b3318bc0524af3d74034b8bb8a64df
> 0ccf35549a/vscode-remote-lock.ubuntu.b3318bc0524af3d74034b8bb8a64df0ccf35549a   
[15:36:53.297] > Found existing installation at /home/ubuntu/.vscode-server/bin/b3318bc0524af3d74
> 034b8bb8a64df0ccf35549a...
[15:36:53.314] > Checking /home/ubuntu/.vscode-server/.b3318bc0524af3d74034b8bb8a64df0ccf35549a.l
> og and /home/ubuntu/.vscode-server/.b3318bc0524af3d74034b8bb8a64df0ccf35549a.pid
>  for a running server
[15:36:53.332] > Looking for server with pid: 62032
[15:36:53.693] > Starting server with command... /home/ubuntu/.vscode-server/bin/b3318bc0524af3d7
> 4034b8bb8a64df0ccf35549a/server.sh --start-server --host=127.0.0.1 --enable-remo
> te-auto-shutdown  --port=0  &> "/home/ubuntu/.vscode-server/.b3318bc0524af3d7403
> 4b8bb8a64df0ccf35549a.log" < /dev/null
> printenv:
[15:36:53.768] >     SHELL=/bin/bash
>     PWD=/home/ubuntu
>     LOGNAME=ubuntu
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/home/ubuntu
>     LANG=C.UTF-8
>     VSCODE_AGENT_FOLDER=/home/ubuntu/.vscode-server
>     SSH_CONNECTION=143.205.122.203 50077 172.20.2.75 22
>     XDG_SESSION_CLASS=user
>     USER=ubuntu
>     SHLVL=0
>     XDG_SESSION_ID=336
>     XDG_RUNTIME_DIR=/run/user/1000
>     SSH_CLIENT=143.205.122.203 50077 22
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
> :/usr/local/games:/snap/bin
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
>     _=/usr/bin/printenv
[15:36:53.912] > Spawned remote server: 62357
[15:36:54.141] > Waiting for server log...
[15:36:54.483] > Waiting for server log...
[15:36:54.819] > Waiting for server log...
[15:36:55.156] > Waiting for server log...
[15:36:55.463] > Waiting for server log...
[15:36:55.720] > Waiting for server log...
[15:36:55.972] > Waiting for server log...
[15:36:56.225] > Waiting for server log...
[15:36:56.480] > Waiting for server log...
[15:36:56.776] > Waiting for server log...
[15:36:57.021] > Waiting for server log...
[15:36:57.268] > Waiting for server log...
[15:36:57.524] > Waiting for server log...
[15:36:57.775] > Waiting for server log...
[15:36:58.030] > Waiting for server log...
[15:36:58.284] > Waiting for server log...
[15:36:58.538] > Waiting for server log...
[15:36:58.788] > Waiting for server log...
[15:36:59.039] > Waiting for server log...
[15:36:59.292] > Waiting for server log...
[15:36:59.549] > Waiting for server log...
[15:37:00.261] > Waiting for server log...
[15:37:00.500] > Waiting for server log...
[15:37:00.773] > Waiting for server log...
[15:37:01.028] > Waiting for server log...
[15:37:01.285] > Waiting for server log...
[15:37:01.532] > Waiting for server log...
[15:37:01.665] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,  
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
[15:37:01.670] > 
> *
> 
[15:37:02.037] > Server did not start successfully. Full server log at /home/ubuntu/.vscode-serve
> r/.b3318bc0524af3d74034b8bb8a64df0ccf35549a.log >>>
[15:37:02.070] > buffer.js:608
>     slice: (buf, start, end) => buf.utf8Slice(start, end),
>                                     ^
> 
> RangeError: Index out of range
>     at Object.slice (buffer.js:608:37)
>     at Buffer.toString (buffer.js:805:14)
>     at Object.readFileSync (fs.js:421:41)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1090:18)   
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js
> :72:12)
>     at internal/main/run_main_module.js:17:47 {
>   code: 'ERR_OUT_OF_RANGE'
> }
> <<< End of server log
> 7b850ab73200: start
> exitCode==32==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/1000==
> platform==linux==
[15:37:02.072] > unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==7849==
> 7b850ab73200: end
[15:37:02.072] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==7849==

[15:37:02.075] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (c:\Users\Bogdan\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:429127)
	at u (c:\Users\Bogdan\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:423450)
	at Object.t.handleInstallOutput (c:\Users\Bogdan\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:427869)
	at Object.t.tryInstall (c:\Users\Bogdan\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:521609)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\Bogdan\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:485262
	at async Object.t.withShowDetailsEvent (c:\Users\Bogdan\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:488612)
	at async Object.t.resolve (c:\Users\Bogdan\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:486341)
	at async c:\Users\Bogdan\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:559963
[15:37:02.085] ------

[15:37:02.714] > 
[15:37:03.456] "install" terminal command done
[15:37:03.457] Install terminal quit with output: 

`

Steps to Reproduce:

1. Attempt to SSH connect to remote host using Remote Explorer

I am able to connect to the remote host using only the VS Code terminal, as well as using _putty_. However when using Remote Explorer it just returns that error.

 I have tried to connect to the same remote host from 2 different computers. 

I have also tried to Kill Remote Host, and also tried deleting the _.vscode-server_ folder on the remote host, but it didn't work.  
I have also used _apt-get update_ . 

I saw that the _Remote Server failed to start_ issue is relatively common, and I've checked other previous posts, but they couldn't solve it.

Thank you in advance for your time.

**Comment by tanhakabir** [comment]
Hey! Thank you for the issue. This looks like the same issue as https://github.com/microsoft/vscode-remote-release/issues/3720 where there's an issue with buffer js from node that we use in the extension. 

I can ping the issue owner to see if they had any progress on the issue.

**Comment by matzuu** [comment]
Hi, I checked the issue [#3720](https://github.com/microsoft/vscode-remote-release/issues/3720) , as well as [#34709](https://github.com/nodejs/node/issues/34709). I've tried installing nodejs and kvm-qemu, but they didn't solve the issue. I get the exact same error.

Maybe is important to note that in my case the vs-code server is hosted on an Openstack VM.

**Comment by tanhakabir** [comment]
Hm sorry I'm not sure of a good solution at the moment. I would follow the issue I have linked for any updates.
