### ISSUE TITLE
Remote-SSH through a localhost tunnel - server did not start successfully, could not find node

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [microsoft/vscode-remote-release#5868]
- VSCode Version: 1.62.1
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu based embedded system on armv7l
- Remote Extension/Connection Type: SSH
- Logs: (see below)

Steps to Reproduce:

I suspect `node` is not supported on my architecture, but I need to ask in case I'm missing something...

I have to access my embedded system via a gateweay:

```
PC <> Gateway <> Embedded Linux Target
```

To access the Linux target from my PC, I create a `localhost` tunnel.  This way, I use `ssh -p 8080 localhost` and this will establish a session on the Linux target.  When I'm on the Linux target, it uses the Gateway as a `http_proxy`, so I can download from the internet.

This is all rosy.

Now, I'd love to be able to run the vscode-server with Remote-SSH on the Linux Target.  When I direct vscode to open a Remote-SSH session, it gets as far as untarring the downloaded bundle but fails to start the vscode-server.

```
:> cat /home/root/.vscode-server/.f4af3cbf5a99787542e2a30fe1fd37cd644cc31f.log 
/home/root/.vscode-server/bin/f4af3cbf5a99787542e2a30fe1fd37cd644cc31f/server.sh: line 12: /home/root/.vscode-server/bin/f4af3cbf5a99787542e2a30fe1fd37cd644cc31f/node: No such file or directory

:> ls -lh /home/root/.vscode-server/bin/f4af3cbf5a99787542e2a30fe1fd37cd644cc31f/node
-rwxr-xr-x 1 root root 65M Nov  5 09:17 /home/root/.vscode-server/bin/f4af3cbf5a99787542e2a30fe1fd37cd644cc31f/node

:> # When I try to run node from the command line...

:> /home/root/.vscode-server/bin/f4af3cbf5a99787542e2a30fe1fd37cd644cc31f/node
-sh: /home/root/.vscode-server/bin/f4af3cbf5a99787542e2a30fe1fd37cd644cc31f/node: No such file or directory
```

Does this mean `node` is not supported on my architecture?

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

## Log (Remote-SSH)
```
[15:09:08.855] Log Level: 2
[15:09:08.865] remote-ssh@0.66.1
[15:09:08.866] win32 x64
[15:09:08.866] SSH Resolver called for "ssh-remote+tun-shtest-008-pdhc", attempt 1
[15:09:08.867] "remote.SSH.useLocalServer": false
[15:09:08.867] "remote.SSH.showLoginTerminal": false
[15:09:08.867] "remote.SSH.remotePlatform": {"5":"linux","7":"linux","8":"linux","abc3":"linux","abc10":"linux","abc3.corp.net":"linux","abc10.corp.net":"linux","crossfield.ccorp.net":"linux","abc30":"linux","fossett":"linux","shtest-011-rmc":"linux","crossfield":"linux","abc30.corp.net":"linux","shtest-008-rmc":"linux"}
[15:09:08.867] "remote.SSH.path": undefined
[15:09:08.868] "remote.SSH.configFile": C:\cygwin64\home\muggerid\.ssh\config
[15:09:08.868] "remote.SSH.useFlock": true
[15:09:08.868] "remote.SSH.lockfilesInTmp": false
[15:09:08.868] "remote.SSH.localServerDownload": auto
[15:09:08.868] "remote.SSH.remoteServerListenOnSocket": false
[15:09:08.868] "remote.SSH.showLoginTerminal": false
[15:09:08.869] "remote.SSH.defaultExtensions": []
[15:09:08.869] "remote.SSH.loglevel": 2
[15:09:08.869] SSH Resolver called for host: tun-shtest-008-pdhc
[15:09:08.870] Setting up SSH remote "tun-shtest-008-pdhc"
[15:09:08.911] Using commit id "f4af3cbf5a99787542e2a30fe1fd37cd644cc31f" and quality "stable" for server
[15:09:08.914] Install and start server if needed
[15:09:10.990] Checking ssh with "ssh -V"
[15:09:16.827] > OpenSSH_8.4p1, OpenSSL 1.1.1f  31 Mar 2020

[15:09:16.868] Using SSH config file "C:\cygwin64\home\muggerid\.ssh\config"
[15:09:16.869] Running script with connection command: ssh -T -D 55693 -F "C:\cygwin64\home\muggerid\.ssh\config" "tun-shtest-008-pdhc" bash
[15:09:16.874] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:09:33.890] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (c:\Users\muggerid\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:429319)
	at Timeout._onTimeout (c:\Users\muggerid\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:520464)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[15:09:33.915] ------




[15:09:34.841] > edf89aca057b: running
> ]0;C:\WINDOWS\System32\cmd.exeWarning: Can't find libstdc++.so or ldconfig, can't verify libstdc++ version
> Acquiring lock on /home/root/.vscode-server/bin/f4af3cbf5a99787542e2a30fe1fd37cd
> 644cc31f/vscode-remote-lock.root.f4af3cbf5a99787542e2a30fe1fd37cd644cc31f       
> Found existing installation at /home/root/.vscode-server/bin/f4af3cbf5a99787542e
> 2a30fe1fd37cd644cc31f...
> Checking /home/root/.vscode-server/.f4af3cbf5a99787542e2a30fe1fd37cd644cc31f.log
>  and /home/root/.vscode-server/.f4af3cbf5a99787542e2a30fe1fd37cd644cc31f.pid for
>  a running server
> Looking for server with pid: 4434
[15:09:34.842] Got some output, clearing connection timeout
[15:09:34.844] > Starting server with command... /home/root/.vscode-server/bin/f4af3cbf5a99787542
> e2a30fe1fd37cd644cc31f/server.sh --start-server --host=127.0.0.1 --enable-remote
> -auto-shutdown  --port=0  &> "/home/root/.vscode-server/.f4af3cbf5a99787542e2a30
> fe1fd37cd644cc31f.log" < /dev/null
> printenv:
>     SHELL=/bin/sh
>     PWD=/home/root
>     LOGNAME=root
>     HOME=/home/root
>     VSCODE_AGENT_FOLDER=/home/root/.vscode-server    
>     SSH_CONNECTION=172.30.50.1 38202 172.30.50.100 22
>     USER=root
>     SHLVL=0
>     SSH_CLIENT=172.30.50.1 38202 22
>     PATH=/usr/bin:/bin:/usr/sbin:/sbin
>     _=/bin/printenv
> Spawned remote server: 6544
> Waiting for server log...
> Waiting for server log...
[15:09:34.967] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:34.967] > 
[15:09:35.280] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:35.327] > 
[15:09:35.686] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:35.993] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:36.342] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:36.362] > 
[15:09:36.689] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:36.705] > 
[15:09:37.051] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:37.073] > 
[15:09:37.395] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:37.733] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:37.745] > 
[15:09:38.071] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:38.095] > 
[15:09:38.403] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:38.414] > 
[15:09:38.738] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:38.748] > 
[15:09:39.086] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:39.096] > 
[15:09:39.355] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:39.381] > 
[15:09:39.685] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:39.708] > 
[15:09:39.993] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:40.013] > 
[15:09:40.332] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:40.337] > 
> Waiting for server log...
[15:09:40.632] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:40.652] > 
[15:09:40.950] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:40.975] > 
[15:09:41.306] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:41.319] > 
[15:09:41.634] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:41.642] > 
[15:09:41.968] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[15:09:41.973] > 
[15:09:42.064] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,  
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
> Server did not start successfully. Full server log at /home/root/.vscode-server/
> .f4af3cbf5a99787542e2a30fe1fd37cd644cc31f.log >>>
> /home/root/.vscode-server/bin/f4af3cbf5a99787542e2a30fe1fd37cd644cc31f/server.sh
> : line 12: /home/root/.vscode-server/bin/f4af3cbf5a99787542e2a30fe1fd37cd644cc31
> f/node: No such file or directory
> <<< End of server log
> edf89aca057b: start
[15:09:42.071] > 
> exitCode==32==
> listeningOn====
> osReleaseId==abc-openbmc-phosphor==
> arch==armv7l==
> tmpDir==/tmp==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==7613==
[15:09:42.268] > edf89aca057b: end
[15:09:43.679] "install" terminal command done
[15:09:43.680] Install terminal quit with output:
```

**Comment by tanhakabir** [comment]
Hey! Sorry for the slow response! Hmm yes this does indicate to me that the remote doesn't support `node`

But you can verify with `node -v` to see if you have any version of `node` installed and working in your remote.

**Comment by LiveFreeAndRoam** [comment]
I need a little more time here. I think I should be able to cross-compile a version of node for this architecture.  Assuming I can do that, how do I get remote-ssh to use the installed version, rather than the one it downloads as part of the `vscode-server.tar.gz`?

**Comment by tanhakabir** [comment]
My understanding is that we can't support that at the moment. But @roblourens can you verify?

**Comment by roblourens** [comment]
> `> �]0;C:\WINDOWS\System32\cmd.exe�Warning: Can't find libstdc++.so or ldconfig, can't verify libstdc++ version`

Something is not right. We don't support a cross-compiled node, we have other native dependencies that you will be missing, and we only support the official builds

**Comment by LiveFreeAndRoam** [comment]
Thanks. That saves me heading further down this path... for now 😉.
