### ISSUE TITLE
Cannot update remote extensions

### ISSUE THREAD

**Issue by tapr00t** [microsoft/vscode-remote-release#5874]
When I try to update the remote extensions, many times it fails.  My remote.SSH.localServerDownload is set to auto, but I've had similar failures with it set to true.  It appears to fallback to the local extension download, then gives an error that the downloaded file is not found locally.  However, if I check the file it complains does not exist, I DO see it on my disk.

- VSCode Version: 1.62.2
- Local OS Version: Windows 10
- Remote OS Version: RHEL 7.2
- Remote Extension/Connection Type: SSH
- Logs:
```
[2021-11-12 11:28:21.699] [renderer1] [error] Error while installing 'donjayamanne.githistory' extension in the remote server. connect ETIMEDOUT 13.107.6.175:443
[2021-11-12 11:28:21.700] [renderer1] [info] Downloading the 'donjayamanne.githistory' extension locally and install
[2021-11-12 11:28:21.845] [renderer1] [info] Downloaded extension: donjayamanne.githistory /c:/Users/leidemdg/AppData/Local/Temp/b0d19cdd-9b2d-4adb-a8f8-2ba08cb184e0
[2021-11-12 11:28:23.427] [renderer1] [error] ["Error: Unable to resolve nonexistent file 'c:\\Users\\leidemdg\\AppData\\Local\\Temp\\b0d19cdd-9b2d-4adb-a8f8-2ba08cb184e0'","    at yi.resolve (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:602:22914)","    at async yi.doMoveCopy (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:602:31002)","    at async yi.copy (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:602:30449)","    at async T.download (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:613:1365)"]
[2021-11-12 11:28:23.459] [renderer1] [error] ["Error: Unable to resolve nonexistent file 'c:\\Users\\leidemdg\\AppData\\Local\\Temp\\b0d19cdd-9b2d-4adb-a8f8-2ba08cb184e0'","    at yi.resolve (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:602:22914)","    at async yi.doMoveCopy (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:602:31002)","    at async yi.copy (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:602:30449)","    at async T.download (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:613:1365)"]
[2021-11-12 11:28:23.564] [renderer1] [error] Unable to resolve nonexistent file 'c:\Users\leidemdg\AppData\Local\Temp\b0d19cdd-9b2d-4adb-a8f8-2ba08cb184e0': Error: Unable to resolve nonexistent file 'c:\Users\leidemdg\AppData\Local\Temp\b0d19cdd-9b2d-4adb-a8f8-2ba08cb184e0'
    at yi.resolve (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:602:22914)
    at async yi.doMoveCopy (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:602:31002)
    at async yi.copy (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:602:30449)
    at async T.download (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:613:1365)
```

Steps to Reproduce:

1. Update an extension

**Comment by tanhakabir** [comment]
Hm and which version of Remote-SSH are you using?

I'm struggling to reproduce this on my Windows 10 machine with VS Code version 1.62.2 and Remote-SSH 0.66.1

**Comment by tapr00t** [comment]
Remote-SSH version:  v0.66.1
But I've had this problem for months

**Comment by tapr00t** [comment]
I messed around with this a bit more, and restarted my VSCode on both my home and work PCs, then I could update (via local transfer) the remote extensions from both successfully.  I'm not sure why that fixed it...

**Comment by tanhakabir** [comment]
Huh strange. I'm not sure. Does everyone else at your organization still see this issue?

**Comment by tapr00t** [comment]
Yes, off and on.  Maybe its something to do with leaving VSCode open for a long time, or having multiple machines connecting to the same remote server.  From my error log, it seems something causes the local VSCode to not "see" the file in the Temp folder.

**Comment by roblourens** [comment]
Please let me know if this is still an issue
