### ISSUE TITLE
"Could not establish connection to "SERVER"

### ISSUE THREAD

**Issue by b-garbacz** [microsoft/vscode-remote-release#5878]
Hey i have problem with Could not establish connection to "SERVER". 
I was looking for solutions of this problem on stack and another pages, I tried everything and i am done also I tried to Install another version... My server works well when I  created connetion in CMD

log below:
`[02:34:03.242] Log Level: 2
[02:34:03.247] remote-ssh@0.66.1
[02:34:03.248] win32 x64
[02:34:03.249] SSH Resolver called for "ssh-remote+SERVER", attempt 1
[02:34:03.250] "remote.SSH.useLocalServer": false
[02:34:03.250] "remote.SSH.showLoginTerminal": false
[02:34:03.250] "remote.SSH.remotePlatform": {}
[02:34:03.250] "remote.SSH.path": undefined
[02:34:03.251] "remote.SSH.configFile": undefined
[02:34:03.252] "remote.SSH.useFlock": true
[02:34:03.252] "remote.SSH.lockfilesInTmp": false
[02:34:03.252] "remote.SSH.localServerDownload": auto
[02:34:03.253] "remote.SSH.remoteServerListenOnSocket": false
[02:34:03.253] "remote.SSH.showLoginTerminal": false
[02:34:03.253] "remote.SSH.defaultExtensions": []
[02:34:03.253] "remote.SSH.loglevel": 2
[02:34:03.254] SSH Resolver called for host: SERVER
[02:34:03.254] Setting up SSH remote "SERVER"
[02:34:03.278] Using commit id "3a6960b964327f0e3882ce18fcebd07ed191b316" and quality "stable" for server
[02:34:03.283] Install and start server if needed
[02:34:07.578] Checking ssh with "ssh -V"
[02:34:07.612] > OpenSSH_for_Windows_8.1p1, LibreSS
[02:34:07.612] > L 3.0.2

[02:34:07.617] Running script with connection command: ssh -T -D 58844 "SERVER" bash
[02:34:07.620] Terminal shell path: C:\Windows\System32\cmd.exe
[02:34:07.890] > ]0;C:\Windows\System32\cmd.exe
[02:34:07.891] Got some output, clearing connection timeout
[02:34:08.194] > superuser@SERVER's password: 
[02:34:08.196] Showing password prompt
[02:34:19.285] Got password response
[02:34:19.285] "install" wrote data to terminal: "********"
[02:34:19.303] > 
[02:34:20.011] > f5b9b688a6c0: running
[02:34:20.030] > mkdir: cannot create directory ‘/home/superuser/.vscode-server/bin/3a6960b964327
> f0e3882ce18fcebd07ed191b316’: Read-only file system
> Creating the server install dir failed...
> f5b9b688a6c0: start
> exitCode==34==
> listeningOn====
> osReleaseId====
> arch====
> tmpDir==/run/user/1000==
> platform====
[02:34:20.050] > unpackResult====     
> didLocalDownload==0==
> downloadTime====     
> installTime====      
> extInstallTime====   
> serverStartTime====  
> f5b9b688a6c0: end    
[02:34:20.051] Received install output: 
exitCode==34==
listeningOn====
osReleaseId====
arch====
tmpDir==/run/user/1000==
platform====
unpackResult====     
didLocalDownload==0==
downloadTime====     
installTime====      
extInstallTime====   
serverStartTime====  

[02:34:20.052] Failed to parse remote port from server output
[02:34:20.052] Resolver error: Error: 
	at Function.Create (c:\Users\barti\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:429193)
	at Object.t.handleInstallOutput (c:\Users\barti\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:427836)
	at Object.t.tryInstall (c:\Users\barti\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:521703)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\barti\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:485356
	at async Object.t.withShowDetailsEvent (c:\Users\barti\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:488706)
	at async Object.t.resolve (c:\Users\barti\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:486435)
	at async c:\Users\barti\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:560057
[02:34:20.059] ------

[02:34:21.354] "install" terminal command done
[02:34:21.356] Install terminal quit with output: 
`

**Comment by b-garbacz** [comment]
also i tried to use
rm -rf ~/.vscode-server but this dir still exsist

**Comment by b-garbacz** [comment]
I found solution for this error. For some reason the filesystem did the re-mount read-only then you have to reboot your machine
