### ISSUE TITLE
Remote connection to local vagrant VM sometimes dies until reboot

### ISSUE THREAD

**Issue by MarkKahn** [microsoft/vscode-remote-release#5883]
- VSCode Version: 1.62.2
- Local OS Version: OSX 11.5.2
- Remote OS Version: Ubuntu 20.04 via Vagrant/Parallels
- Remote Extension/Connection Type: SSH
- Logs:

```sh
[14:06:24.323] Log Level: 2
[14:06:24.326] remote-ssh@0.66.1
[14:06:24.326] darwin x64
[14:06:24.328] SSH Resolver called for "ssh-remote+voice-vagrant", attempt 1
[14:06:24.328] "remote.SSH.useLocalServer": true
[14:06:24.329] "remote.SSH.path": undefined
[14:06:24.333] "remote.SSH.configFile": undefined
[14:06:24.333] "remote.SSH.useFlock": true
[14:06:24.334] "remote.SSH.lockfilesInTmp": true
[14:06:24.334] "remote.SSH.localServerDownload": auto
[14:06:24.334] "remote.SSH.remoteServerListenOnSocket": false
[14:06:24.335] "remote.SSH.showLoginTerminal": false
[14:06:24.335] "remote.SSH.defaultExtensions": []
[14:06:24.336] "remote.SSH.loglevel": 2
[14:06:24.336] SSH Resolver called for host: voice-vagrant
[14:06:24.336] Setting up SSH remote "voice-vagrant"
[14:06:24.341] Acquiring local install lock: /var/folders/b3/pjb8p5tn0gz83zb5fcgk5c4w0000gn/T/vscode-remote-ssh-32086b95-install.lock
[14:06:24.356] Looking for existing server data file at /Users/mark/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-32086b95-3a6960b964327f0e3882ce18fcebd07ed191b316-0.66.1/data.json
[14:06:24.358] Using commit id "3a6960b964327f0e3882ce18fcebd07ed191b316" and quality "stable" for server
[14:06:24.361] Install and start server if needed
[14:06:24.364] PATH: /Users/mark/bin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
[14:06:24.364] Checking ssh with "ssh -V"
[14:06:24.371] > OpenSSH_8.1p1, LibreSSL 2.7.3

[14:06:24.374] askpass server listening on /var/folders/b3/pjb8p5tn0gz83zb5fcgk5c4w0000gn/T/vscode-ssh-askpass-c1567003c6dda56fc7cbae215f55656d94126de0.sock
[14:06:24.374] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/b3/pjb8p5tn0gz83zb5fcgk5c4w0000gn/T/vscode-ssh-askpass-92efe44cbe9a2a42f6bb806539773bcae536719e.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","59795","-o","RemoteCommand=none","voice-vagrant"],"dataFilePath":"/Users/mark/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-32086b95-3a6960b964327f0e3882ce18fcebd07ed191b316-0.66.1/data.json"}
[14:06:24.375] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/mark/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/mark/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/b3/pjb8p5tn0gz83zb5fcgk5c4w0000gn/T/vscode-ssh-askpass-c1567003c6dda56fc7cbae215f55656d94126de0.sock"}
[14:06:24.376] Spawned 77542
[14:06:24.519] > local-server-1> Spawned ssh, pid=77548
[14:06:24.522] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[14:06:24.537] stderr> ssh: connect to host 10.211.55.4 port 22: Bad file descriptor
[14:06:24.539] > local-server-1> ssh child died, shutting down
[14:06:24.543] Local server exit: 0
[14:06:24.543] Received install output: local-server-1> Spawned ssh, pid=77548
OpenSSH_8.1p1, LibreSSL 2.7.3
ssh: connect to host 10.211.55.4 port 22: Bad file descriptor
local-server-1> ssh child died, shutting down

[14:06:24.544] Failed to parse remote port from server output
[14:06:24.545] Resolver error: Error: 
	at Function.Create (/Users/mark/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:429193)
	at Object.t.handleInstallOutput (/Users/mark/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:427836)
	at Object.e [as tryInstallWithLocalServer] (/Users/mark/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:467444)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/mark/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:484911
	at async Object.t.withShowDetailsEvent (/Users/mark/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:488706)
	at async /Users/mark/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:465968
	at async I (/Users/mark/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:462544)
	at async Object.t.resolveWithLocalServer (/Users/mark/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:465583)
	at async Object.t.resolve (/Users/mark/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:486311)
	at async /Users/mark/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:560057
[14:06:24.548] ------
```

Steps to Reproduce:

Unknown.  Happens occasionally on my laptop, *possibly* has to do with sleeping, but it usually works so that's just a random guess.  It's happened 3 times now and VSCode is unable to connect to the local running vagrant VM until I reboot the host OS.  Rebooting the VM has no effect.  Both `vagrant ssh` and `ssh voice-vagrant` work just fine.

Happy to provide any additional logs, but not sure where they are.

**Comment by MarkKahn** [comment]
Turns out this happens whenever my laptop doesn't have internet access.  This time it's because I didn't sign in to the local network at a coffee shop.

This is entirely unexpected because a) It's connecting to a *local* VM and b) vscode-server is already installed on the VM

**Comment by roblourens** [comment]
`Bad file descriptor` this error is coming from ssh, not sure what it means. It has come up in a couple issues here before but there isn't really a pattern. The command we run is essentially something like `echo "echo hello" | ssh -v -T -D 59795 -o RemoteCommand=none voice-vagrant`, does that work for you?

**Comment by MarkKahn** [comment]
I actually figured it out (at least for my case).  I have a program called TripMode installed, that is a network filter for when I'm tethering data on my phone.  For whatever strange reason VSCode needed access in TripMode even though if my wifi was completely turned off and I wasn't connected to anything.

Given this, there *might* be some network filtering going on in your other cases.  Just reproduced, and yes that command works when VSCode isn't.
