### ISSUE TITLE
Remote - SSH doesn't ask for keyphrase of private key?

### ISSUE THREAD

**Issue by MikeK184** [microsoft/vscode-remote-release#5931]
- VSCode Version: 1.62.3 (user setup)
- Local OS Version: WSL-Version 1 - Ubuntu-18.04 
- Remote OS Version: Ubuntu 16.04.7 LTS
- Remote Extension/Connection Type: SSH/WSL(?)
- Logs:
```
[12:42:38.382] Log Level: 2
[12:42:38.441] remote-ssh@0.66.1
[12:42:38.442] win32 x64
[12:42:38.448] SSH Resolver called for "ssh-remote+pkstest-ops-manager.m086", attempt 1
[12:42:38.449] "remote.SSH.useLocalServer": false
[12:42:38.450] "remote.SSH.showLoginTerminal": true
[12:42:38.450] "remote.SSH.remotePlatform": {}
[12:42:38.450] "remote.SSH.path": undefined
[12:42:38.450] "remote.SSH.configFile": C:\Users\rsmi077\.ssh\config
[12:42:38.450] "remote.SSH.useFlock": true
[12:42:38.451] "remote.SSH.lockfilesInTmp": false
[12:42:38.451] "remote.SSH.localServerDownload": auto
[12:42:38.451] "remote.SSH.remoteServerListenOnSocket": false
[12:42:38.451] "remote.SSH.showLoginTerminal": true
[12:42:38.451] "remote.SSH.defaultExtensions": []
[12:42:38.451] "remote.SSH.loglevel": 2
[12:42:38.452] SSH Resolver called for host: pkstest-ops-manager.m086
[12:42:38.452] Setting up SSH remote "pkstest-ops-manager.m086"
[12:42:38.502] Using commit id "ccbaa2d27e38e5afa3e5c21c1c7bef4657064247" and quality "stable" for server
[12:42:38.506] Install and start server if needed
[12:42:42.163] Checking ssh with "ssh -V"
[12:42:42.287] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[12:42:42.292] Using SSH config file "C:\Users\rsmi077\.ssh\config"
[12:42:42.292] Running script with connection command: ssh -T -D 54350 -F "C:\Users\rsmi077\.ssh\config" "pkstest-ops-manager.m086" bash
[12:42:42.295] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[12:42:42.711] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ]0;C:\WINDOWS\System32\cmd.exe
[12:42:42.712] Got some output, clearing connection timeout
[12:42:42.719] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[12:42:42.731] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[12:42:43.126] > Corrupted MAC on input.
> 
[12:42:43.133] > ssh_dispatch_run_fatal: Connection to 10.2.210.4 port 22: message authentication code incorrect
> Ein Prozess hat versucht, zu einer nicht bestehenden Pipe zu schreiben.
> 
[12:42:45.130] "install" terminal command done
[12:42:45.131] Install terminal quit with output: Ein Prozess hat versucht, zu einer nicht bestehenden Pipe zu schreiben.
[12:42:45.131] Received install output: Ein Prozess hat versucht, zu einer nicht bestehenden Pipe zu schreiben.
[12:42:45.133] Failed to parse remote port from server output
[12:42:45.134] Resolver error: Error: 
	at Function.Create (c:\Users\rsmi077\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:429193)
	at Object.t.handleInstallOutput (c:\Users\rsmi077\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:427836)
	at Object.t.tryInstall (c:\Users\rsmi077\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:521703)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\rsmi077\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:485356
	at async Object.t.withShowDetailsEvent (c:\Users\rsmi077\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:488706)
	at async Object.t.resolve (c:\Users\rsmi077\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:486435)
	at async c:\Users\rsmi077\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:560057
[12:42:45.148] ------
```
**Steps to Reproduce:**

1.  Added remote host
![image](https://user-images.githubusercontent.com/56921065/142855150-5f481abe-b507-4a98-8f9e-b4b0be0b7434.png)
2. My config looks like this (C:\Users\rsmi077\.ssh\config):
```
Host pkstest-ops-manager.m086
  HostName pkstest-ops-manager.m086
  User ubuntu
  IdentityFile id_rsa_opstest
```
3. VSCode doesn't recognize OS (I'm choosing Linux):
![image](https://user-images.githubusercontent.com/56921065/142855749-3b969c75-c2c8-4d15-b486-5c3def7d7f71.png)
4. Check error logs above

**Note:**
I've added the given private key in the same directory as the config. I've also activated the ``Remote.SSH: Show Login Terminal
` but I never get to type in my passphrase, as i get the error that the connection couldn't be established

**Comment by tanhakabir** [comment]
Just to verify are you able to run `echo "hello" | ssh -D 54350 -F "C:\Users\rsmi077\.ssh\config" "pkstest-ops-manager.m086"` in your cli?

**Comment by MikeK184** [comment]
Hi there @tanhakabir 

I've run that given command in Powershell & Git Bash as it didn't work in WSL, but I've got 2 different responses:

Powershell:
```
PS C:\Users\rsmi077> echo "hello" | ssh -D 54350 -F "C:\Users\rsmi077\.ssh\config" "pkstest-ops-manager.m086"
Pseudo-terminal will not be allocated because stdin is not a terminal.
Corrupted MAC on input.
ssh_dispatch_run_fatal: Connection to 10.2.210.4 port 22: message authentication code incorrect
```

Git Bash:
```
rsmi077@a8600473 MINGW64 ~
$ echo "hello" | ssh -D 54350 -F "C:\Users\rsmi077\.ssh\config" "pkstest-ops-manager.m086"
Pseudo-terminal will not be allocated because stdin is not a terminal.
############## TKGI TEST##############
no such identity: id_rsa_opstest: No such file or directory
ubuntu@pkstest-ops-manager.m086: Permission denied (publickey).
```

WSL:
```
rsmi077 @ a8600473 ~/Documentation (master)
└ $ > echo "hello" | ssh -D 54350 -F "C:\Users\rsmi077\.ssh\config" "pkstest-ops-manager.m086"
Can't open user config file C:\\Users\\rsmi077\\.ssh\\config: No such file or directory
```

However, the response from Git Bash kinda makes the impression that the config couldn't find the given private key? As I haven't provided the full path in the config file. But regardless its somewhat confusing due to the different error messages.

**Comment by tanhakabir** [comment]
@MikeK184 researching `no such identity: id_rsa_opstest: No such file or directory` I see this https://stackoverflow.com/questions/58352466/git-no-such-identity-id-rsa-no-such-file-or-directory where maybe you've misconfigured your private key?
