### ISSUE TITLE
Remote - SSH can’t establish in vscode when upgraded,It's ok before

### ISSUE THREAD

**Issue by didiaibiancheng** [microsoft/vscode-remote-release#5951]
- VSCode Version: 1.62.3 (user setup)
- Local OS Version: Microsoft Windows [ver 10.0.19042.1348]
- Remote OS Version: CentOS Linux release 7.2
- Remote Extension/Connection Type: SSH

**Logs:**
[11:45:56.860] Log Level: 2
[11:45:56.863] remote-ssh@0.66.1
[11:45:56.863] win32 x64
[11:45:56.864] SSH Resolver called for "ssh-remote+dev-cloud-cvm", attempt 1
[11:45:56.865] "remote.SSH.useLocalServer": false
[11:45:56.865] "remote.SSH.showLoginTerminal": false
[11:45:56.865] "remote.SSH.remotePlatform": {}
[11:45:56.865] "remote.SSH.path": undefined
[11:45:56.866] "remote.SSH.configFile": undefined
[11:45:56.866] "remote.SSH.useFlock": true
[11:45:56.866] "remote.SSH.lockfilesInTmp": false
[11:45:56.866] "remote.SSH.localServerDownload": auto
[11:45:56.867] "remote.SSH.remoteServerListenOnSocket": false
[11:45:56.867] "remote.SSH.showLoginTerminal": false
[11:45:56.867] "remote.SSH.defaultExtensions": []
[11:45:56.867] "remote.SSH.loglevel": 2
[11:45:56.868] SSH Resolver called for host: dev-cloud-cvm
[11:45:56.868] Setting up SSH remote "dev-cloud-cvm"
[11:45:56.893] Using commit id "ccbaa2d27e38e5afa3e5c21c1c7bef4657064247" and quality "stable" for server
[11:45:56.896] Install and start server if needed
[11:45:58.167] Checking ssh with "ssh -V"
[11:45:58.287] > OpenSSH_for_Windows_8.1p1, 
[11:45:58.287] > LibreSSL 3.0.2
[11:45:58.293] Running script with connection command: ssh -T -D 2894 "dev-cloud-cvm" bash
[11:45:58.296] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[11:45:58.587] > 拒绝访问。
]0;C:\WINDOWS\System32\cmd.exe
[11:45:58.587] Got some output, clearing connection timeout
[11:45:58.869] > root@9.134.233.1's password: 
[11:45:58.870] Showing password prompt
[11:46:03.508] Got password response
[11:46:03.508] "install" wrote data to terminal: "**********"
[11:46:03.521] > 
[11:46:04.908] "install" terminal command done
[11:46:04.909] Install terminal quit with output: 
[11:46:04.909] Resolver error: Error: Got bad result from install script
	at Function.Create (c:\Users\85228\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:429193)
	at Object.t.tryInstall (c:\Users\85228\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:521466)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\85228\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:485356
	at async Object.t.withShowDetailsEvent (c:\Users\85228\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:488706)
	at async Object.t.resolve (c:\Users\85228\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:486435)
	at async c:\Users\85228\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:560057

**But when ran ssh in cmd,it's ok,no error occured：**
C:\Users\85228> ssh -D 54350 -F "C:\Users\85228\.ssh\config" "dev-cloud-cvm"
root@9.134.233.1's password:
Last login: Sat Nov 27 11:41:49 2021 from 10.99.17.133
bash-4.2#

**myconfig：**
Host dev-cloud-cvm
    User root
    HostName 9.134.233.1
    Port 19000
    IdentityFile C:\Users\85228\.ssh\id_rsa

**Comment by tanhakabir** [comment]
Just to clarify as well you had no issues connecting in vscode version `1.62.2`?

**Comment by risharde** [comment]
I am beyond frustrated with this, I am having the same issue! IdentityFile not being detected and you can see that it isn't
here (Windows 10 x64) - Latest VSCode and Latest remote ssh plugin update: 

[00:15:41.171] Running script with connection command: ssh -T -D 51802 -p 1122 "user@domain" bash

I replaced my real user and domain.

This makes VSCODE unusable and needs to be fixed ASAP!

**Comment by tanhakabir** [comment]
@risharde to verify this command works in cmd/powershell? `ssh -T -D 51802 -p 1122 "user@domain"`

What does your config entry look like?

We don't do anything special with the IdentityFile listed in your config entry. We just call OpenSSH with your config.
