### ISSUE TITLE
Test: Use the pre-built alpine image for the recovery container

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#5964]
Refs: #5897

- [x] anyOS @sbatten
- [x] anyOS @alexr00

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-remote-release/issues/new?body=Testing+%235964%0A%0A&assignees=chrmarti)

---

- Use `Remote-Containers: Clone Repository in Container Volume...` to create a dev container.
- Add an error to the Dockerfile (e.g., `RUN fail` at the end).
- Run `Remote-Containers: Rebuild Container`.
- When the build fails you are offered to open in a recovery container.
- Check that the recovery container has `git` installed.
- Fix the Dockerfile and `Reopen in Container`.
- Verify the dev container is correctly opened.

**Comment by alexr00** [comment]
I got the following errors when the recovery container opened:
![image](https://user-images.githubusercontent.com/38270282/144060064-71bb5a4f-3dd7-4e41-b3d1-4cb2d14dd055.png)

```
 WARN Ignoring the error while validating workspace folder vscode-remote://dev-container%2B7b227265706f7369746f727950617468223a2268747470733a2f2f6769746875622e636f6d2f616c65787230302f73696d706c652d7365727665722e6769742f747265652f6d6173746572222c22766f6c756d654e616d65223a2273696d706c652d7365727665722d6d61737465722d3765383864363963613263316664663938613335393133386164306130366530222c22666f6c646572223a2273696d706c652d736572766572222c22696e7370656374566f6c756d65223a747275657d/workspaces/simple-server - Unable to resolve nonexistent file 'vscode-remote://dev-container+7b227265706f7369746f727950617468223a2268747470733a2f2f6769746875622e636f6d2f616c65787230302f73696d706c652d7365727665722e6769742f747265652f6d6173746572222c22766f6c756d654e616d65223a2273696d706c652d7365727665722d6d61737465722d3765383864363963613263316664663938613335393133386164306130366530222c22666f6c646572223a2273696d706c652d736572766572222c22696e7370656374566f6c756d65223a747275657d/workspaces/simple-server'
log.ts:313   ERR Error: Unable to read file 'vscode-remote:/workspaces/simple-server/.devcontainer/Dockerfile' (Error: Unable to resolve nonexistent file 'vscode-remote:/workspaces/simple-server/.devcontainer/Dockerfile')
    at n.handleSetInputError (textFileEditor.ts:186)
    at n.handleSetInputError (textFileEditor.ts:82)
    at n.setInput (textFileEditor.ts:164)
    at async i.doSetInput (editorPanes.ts:284)
    at async i.doOpenEditor (editorPanes.ts:151)
    at async i.openEditor (editorPanes.ts:119)
    at async editorGroupView.ts:1062
    at async editorCommands.ts:505
notificationsAlerts.ts:42 Unable to open 'Dockerfile': Unable to read file 'vscode-remote:/workspaces/simple-server/.devcontainer/Dockerfile' (Error: Unable to resolve nonexistent file 'vscode-remote:/workspaces/simple-server/.devcontainer/Dockerfile').
onDidChangeNotification @ notificationsAlerts.ts:42
log.ts:313   ERR Unable to resolve nonexistent file 'vscode-remote://dev-container+7b227265706f7369746f727950617468223a2268747470733a2f2f6769746875622e636f6d2f616c65787230302f73696d706c652d7365727665722e6769742f747265652f6d6173746572222c22766f6c756d654e616d65223a2273696d706c652d7365727665722d6d61737465722d3765383864363963613263316664663938613335393133386164306130366530222c22666f6c646572223a2273696d706c652d736572766572222c22696e7370656374566f6c756d65223a747275657d/workspaces/simple-server': Error: Unable to resolve nonexistent file 'vscode-remote://dev-container+7b227265706f7369746f727950617468223a2268747470733a2f2f6769746875622e636f6d2f616c65787230302f73696d706c652d7365727665722e6769742f747265652f6d6173746572222c22766f6c756d654e616d65223a2273696d706c652d7365727665722d6d61737465722d3765383864363963613263316664663938613335393133386164306130366530222c22666f6c646572223a2273696d706c652d736572766572222c22696e7370656374566f6c756d65223a747275657d/workspaces/simple-server'
    at Ei.resolve (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:577:29972)
    at async m.findWorkspaces (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1548:6419)
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: ENOENT: no such file or directory, scandir '/workspaces/simple-server'
I @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: ENOENT: no such file or directory, scandir '/workspaces/simple-server'
I @ console.ts:137
log.ts:313   ERR ENOENT: no such file or directory, scandir '/workspaces/simple-server': Error: ENOENT: no such file or directory, scandir '/workspaces/simple-server'
```

**Comment by alexr00** [comment]
The second time worked, but there is no "Reopen Folder in Container". Is there another way to get back into the container?

**Comment by chrmarti** [comment]
It is just `Reopen in Container` (no `Folder`). There is also a notification for that. (Removed `Folder` from the test instructions above.)

**Comment by sbatten** [comment]
👍🏻 on macos
