### ISSUE TITLE
Does Not Work On Windows + WSL + OpenSSH + Ubuntu

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-remote-release#5969]
Testing #5962

![image](https://user-images.githubusercontent.com/2931520/144046167-19353b6c-1f9b-4385-bcfb-78fbe3c2e708.png)

In the integrated terminal when connected to remote ssh, before "open in container":
```
docker --version
Docker version 20.10.10, build b485636
```

```
[4204 ms] Remote-Containers 0.207.0 in VS Code 1.63.0-insider (b9cf83f70bb6b4697b544a97c7056dfd28fccc5f).
[4203 ms] Start: Run: ssh localhost2 /bin/sh -c /bin/sh
[4214 ms] Start: Run in host: id -un
[8909 ms] hediet
[8909 ms]
[8910 ms] Start: Run in host: cat /etc/passwd
[8913 ms] Start: Run in host: echo ~
[8915 ms] /home/hediet
[8915 ms]
[8916 ms] Start: Run in host: test -x '/home/hediet/.vscode-remote-containers/bin/b9cf83f70bb6b4697b544a97c7056dfd28fccc5f/node'
[8917 ms]
[8918 ms]
[8918 ms] Exit code 1
[8918 ms] Start: Run in host: test -x '/home/hediet/.vscode-server-insiders/bin/b9cf83f70bb6b4697b544a97c7056dfd28fccc5f/node'
[8920 ms]
[8920 ms]
[8920 ms] Start: Run in host: test -f '/home/hediet/.vscode-server-insiders/bin/b9cf83f70bb6b4697b544a97c7056dfd28fccc5f/node_modules/node-pty/package.json'
[8922 ms]
[8922 ms]
[8922 ms] Start: Run in host: test -f '/home/hediet/.vscode-remote-containers/dist/vscode-remote-containers-server-0.207.0.js'
[8923 ms]
[8923 ms]
[8925 ms] userEnvProbe: loginInteractiveShell (default)
[8925 ms] userEnvProbe shell: /bin/bash
[8963 ms] Host server: (node:1711) UnhandledPromiseRejectionWarning: Error: spawn /bin/bash ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
[8964 ms] Host server: (node:1711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1711) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[8966 ms] Error: spawn /bin/bash ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[8967 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[8968 ms] Host server: (node:1711) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
[9010 ms] Host server: (node:1711) UnhandledPromiseRejectionWarning: Error: spawn docker ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:1711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[9013 ms] Host server: (node:1711) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
[9014 ms] spawn docker ENOENT
[9017 ms] CLI host's PATH: undefined
[36234 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[36237 ms] Host server: (node:1711) UnhandledPromiseRejectionWarning: Error: spawn docker ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[36238 ms] Host server: (node:1711) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[36239 ms] spawn docker ENOENT
[36240 ms] CLI host's PATH: undefined
[36241 ms] Host server: (node:1711) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
```

**Comment by chrmarti** [comment]
`spawn /bin/bash ENOENT` indicates that the working directory does not exist (since /bin/bash does exist). What do you get for running `ssh localhost2 /bin/sh -c pwd`?

**Comment by hediet** [comment]
`/home/hediet`, it is empty but exists.

**Comment by hediet** [comment]
Thanks, it works now!
