### ISSUE TITLE
After one successful connection, all subsequent attempts time out

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-release#5972]
- VSCode Version: 1.63.0-insider (user setup) Commit: 827f76521d33a61c19e92160649a0a6af8bad132
- Local OS Version: Windows 11
- Remote OS Version: Linux (ubuntu 20.04)
- Remote Extension/Connection Type: SSH
- Logs:
<details>

```
[15:00:41.356] Log Level: 2
[15:00:41.362] remote-ssh@0.66.1
[15:00:41.362] win32 x64
[15:00:41.363] SSH Resolver called for "ssh-remote+<redacted>", attempt 1
[15:00:41.363] "remote.SSH.useLocalServer": false
[15:00:41.363] "remote.SSH.showLoginTerminal": false
[15:00:41.363] "remote.SSH.remotePlatform": {"<redacted>":"linux"}
[15:00:41.364] "remote.SSH.path": undefined
[15:00:41.364] "remote.SSH.configFile": undefined
[15:00:41.364] "remote.SSH.useFlock": true
[15:00:41.364] "remote.SSH.lockfilesInTmp": false
[15:00:41.364] "remote.SSH.localServerDownload": auto
[15:00:41.364] "remote.SSH.remoteServerListenOnSocket": false
[15:00:41.364] "remote.SSH.showLoginTerminal": false
[15:00:41.364] "remote.SSH.defaultExtensions": []
[15:00:41.364] "remote.SSH.loglevel": 2
[15:00:41.365] SSH Resolver called for host: <redacted>
[15:00:41.365] Setting up SSH remote "<redacted>"
[15:00:41.382] Using commit id "827f76521d33a61c19e92160649a0a6af8bad132" and quality "insider" for server
[15:00:41.385] Install and start server if needed
[15:00:41.389] Checking ssh with "ssh -V"
[15:00:41.428] > OpenSSH_for_Windows_8.1p1, LibreSSL
[15:00:41.428] >  3.0.2

[15:00:41.432] Running script with connection command: ssh -T -D 63939 "<redacted>" bash
[15:00:41.435] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:00:41.720] > ]0;C:\WINDOWS\System32\cmd.exe
[15:00:41.720] Got some output, clearing connection timeout
[15:01:02.766] > ssh: connect to host <redacted> port 22: Connection timed out
[15:01:02.770] > The process tried to write to a nonexistent pipe.
[15:01:04.042] "install" terminal command done
[15:01:04.042] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exessh: connect to host <redacted> port 22: Connection timed out
[15:01:04.043] Received install output: ]0;C:\WINDOWS\System32\cmd.exessh: connect to host <redacted> port 22: Connection timed out
[15:01:04.045] Resolver error: Error: The connection timed out
	at Function.Offline (c:\Users\huer\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:429244)
	at c:\Users\huer\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:426897
	at Object.t.handleInstallOutput (c:\Users\huer\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:427172)
	at Object.t.tryInstall (c:\Users\huer\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:521703)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\huer\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:485356
	at async Object.t.withShowDetailsEvent (c:\Users\huer\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:488706)
	at async Object.t.resolve (c:\Users\huer\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:486435)
	at async c:\Users\huer\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.66.1\out\extension.js:1:560057
[15:01:04.052] ------
```

</details>

Steps to Reproduce:

1. Create a clean Linux VM from portal.azure.com
2. Connect to it with Remote-SSH
3. Connection succeeds once
4. Close connection
5. Try connecting again 
6. 🐛 connection times out
![image](https://user-images.githubusercontent.com/30305945/144142106-d7b8599e-adb3-4619-9a3c-b9986dcbfc6d.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by tanhakabir** [comment]
Would you be able to also grab the logs you see in the Remote-SSH output channel when it's timing out like that?

**Comment by tanhakabir** [comment]
Nvm didn't notice the dropdown

**Comment by joyceerhl** [comment]
I realized it's the default security group inbound port rules--long time no Azure VM 🥲
