### ISSUE TITLE
SSH stops working

### ISSUE THREAD

**Issue by an0** [microsoft/vscode-remote-release#5982]
Issue Type: <b>Bug</b>

I've been using SSH Targets for a long time. Today it stops working. The same ssh command works in terminal (either inside or outsite Code).

SSH connection logs:
```
[10:31:25.423] Log Level: 2
[10:31:25.425] remote-ssh@0.66.1
[10:31:25.425] darwin x64
[10:31:25.436] SSH Resolver called for "ssh-remote+ghost", attempt 1
[10:31:25.437] "remote.SSH.useLocalServer": true
[10:31:25.437] "remote.SSH.path": undefined
[10:31:25.437] "remote.SSH.configFile": undefined
[10:31:25.437] "remote.SSH.useFlock": true
[10:31:25.437] "remote.SSH.lockfilesInTmp": false
[10:31:25.437] "remote.SSH.localServerDownload": auto
[10:31:25.437] "remote.SSH.remoteServerListenOnSocket": false
[10:31:25.438] "remote.SSH.showLoginTerminal": false
[10:31:25.438] "remote.SSH.defaultExtensions": []
[10:31:25.438] "remote.SSH.loglevel": 2
[10:31:25.438] SSH Resolver called for host: ghost
[10:31:25.438] Setting up SSH remote "ghost"
[10:31:25.440] Acquiring local install lock: /var/folders/rj/wcyvtff13q1brw51zsrjz3_c0000gn/T/vscode-remote-ssh-784003d0-install.lock
[10:31:25.443] Looking for existing server data file at /Users/an0/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-784003d0-ccbaa2d27e38e5afa3e5c21c1c7bef4657064247-0.66.1/data.json
[10:31:25.443] Using commit id "ccbaa2d27e38e5afa3e5c21c1c7bef4657064247" and quality "stable" for server
[10:31:25.445] Install and start server if needed
[10:31:25.447] PATH: xxx
[10:31:25.447] Checking ssh with "ssh -V"
[10:31:25.498] > OpenSSH_8.1p1, LibreSSL 2.7.3

[10:31:25.500] askpass server listening on /var/folders/rj/wcyvtff13q1brw51zsrjz3_c0000gn/T/vscode-ssh-askpass-c091d2257461e110711f08fd8913719f461411b2.sock
[10:31:25.501] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/rj/wcyvtff13q1brw51zsrjz3_c0000gn/T/vscode-ssh-askpass-9fb42432d44d003d41fdf4af19fa135915d72bf4.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","50692","-o","ConnectTimeout=15","ghost"],"dataFilePath":"/Users/an0/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-784003d0-ccbaa2d27e38e5afa3e5c21c1c7bef4657064247-0.66.1/data.json"}
[10:31:25.501] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/an0/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/an0/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/rj/wcyvtff13q1brw51zsrjz3_c0000gn/T/vscode-ssh-askpass-c091d2257461e110711f08fd8913719f461411b2.sock"}
[10:31:25.502] Spawned 26242
[10:31:25.592] > local-server-1> Spawned ssh, pid=26246
[10:31:25.595] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[10:31:26.650] stderr> debug1: Server host key: ssh-rsa SHA256:UIMViA/T0i5idtAoEfke5ZBxaNqgk37BaccpktQuiSI
[10:31:28.036] stderr> Authenticated to 139.162.68.86 ([139.162.68.86]:22).
[10:31:28.798] > Linux ghost 5.13.4-x86_64-linode146 #1 SMP Wed Jul 21 14:45:45 EDT 2021 x86_64
> 
> The programs included with the Debian GNU/Linux system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
> permitted by applicable law.
> You have no mail.
[10:31:28.801] > Must be connected to a terminal.
[10:31:29.156] > ready: 97697ab36d03
[10:31:29.463] > Linux 5.13.4-x86_64-linode146 #1 SMP Wed Jul 21 14:45:45 EDT 2021
[10:31:29.463] Platform: linux
[10:31:29.738] > 97697ab36d03: running
[10:31:29.777] > Acquiring lock on /home/an0/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/vscode-remote-lock.an0.ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
[10:31:29.779] > Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> 97697ab36d03: start
> exitCode==24==
> listeningOn====
> osReleaseId==debian==
> arch==x86_64==
> tmpDir==/run/user/1000==
[10:31:29.987] > platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 97697ab36d03: end
[10:31:29.988] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==debian==
arch==x86_64==
tmpDir==/run/user/1000==platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[10:31:29.988] Server installation process already in progress - waiting and retrying
[10:31:29.988] Terminating local server
[10:31:29.993] Local server exit: 15
```

Extension version: 0.66.1
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-3275M CPU @ 2.50GHz (56 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 2|
|Memory (System)|96.00GB (67.68GB free)|
|Process Argv|--crash-reporter-id 02189bf2-aabc-4063-b3b8-912e2f2477f3|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593cf:30376535
pythonvs932cf:30405812
vscop804:30404766
vs360cf:30404996
vsrem710:30405998

```

</details>

**Comment by tanhakabir** [comment]
Hmm could you try the command `Remote-SSH: Kill Local Server on Host...`?

**Comment by an0** [comment]
> Hmm could you try the command `Remote-SSH: Kill Local Server on Host...`?

Tried, no effect. I even tried restarting local computer.

**Comment by tanhakabir** [comment]
Could you try connecting with the setting `remote.ssh.useLocalServer` set to `false`?

**Comment by an0** [comment]
> Could you try connecting with the setting `remote.ssh.useLocalServer` set to `false`?

Tried, still cannot connect.

**Comment by tanhakabir** [comment]
Could you send me the logs for it as well?

**Comment by an0** [comment]
With `remote.ssh.useLocalServer` unchecked, it now keeps prompting this and I cannot grab the full logs.
<img width="1136" alt="Screen Shot 2021-12-01 at 8 44 50 PM" src="https://user-images.githubusercontent.com/100976/144359290-df8e96e1-35e6-4ec0-a8b6-d02f3e0afa00.png">

**Comment by tanhakabir** [comment]
Interesting, like it's stuck in a loop of asking for remote platform? 

Could you hit `escape` and you should see a model dialog pop up with actions. Hit `More Actions` and then open up the output channel to see what the logs are?

Were you seeing this infinite loop yesterday when you said it didn't work?

**Comment by an0** [comment]
> Interesting, like it's stuck in a loop of asking for remote platform?
> 
> Could you hit `escape` and you should see a model dialog pop up with actions. Hit `More Actions` and then open up the output channel to see what the logs are?

This trick works. Here is the log:
```
[12:46:25.832] Log Level: 2
[12:46:25.836] remote-ssh@0.66.1
[12:46:25.836] darwin x64
[12:46:25.839] SSH Resolver called for "ssh-remote+ghost", attempt 1
[12:46:25.841] "remote.SSH.useLocalServer": false
[12:46:25.842] "remote.SSH.showLoginTerminal": false
[12:46:25.843] "remote.SSH.remotePlatform": {}
[12:46:25.848] "remote.SSH.path": undefined
[12:46:25.848] "remote.SSH.configFile": undefined
[12:46:25.849] "remote.SSH.useFlock": true
[12:46:25.849] "remote.SSH.lockfilesInTmp": false
[12:46:25.850] "remote.SSH.localServerDownload": auto
[12:46:25.850] "remote.SSH.remoteServerListenOnSocket": false
[12:46:25.851] "remote.SSH.showLoginTerminal": false
[12:46:25.851] "remote.SSH.defaultExtensions": []
[12:46:25.852] "remote.SSH.loglevel": 2
[12:46:25.852] SSH Resolver called for host: ghost
[12:46:25.853] Setting up SSH remote "ghost"
[12:46:25.876] Using commit id "ccbaa2d27e38e5afa3e5c21c1c7bef4657064247" and quality "stable" for server
[12:46:25.880] Install and start server if needed
[12:46:26.855] getPlatformForHost was canceled
[12:46:26.856] Resolver error: Error: Connecting was canceled
	at Function.Canceled (/Users/an0/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:429389)
	at /Users/an0/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:485268
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Object.t.withShowDetailsEvent (/Users/an0/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:488706)
	at async Object.t.resolve (/Users/an0/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:486435)
	at async /Users/an0/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:560057
[12:46:26.864] ------
```
 
> Were you seeing this infinite loop yesterday when you said it didn't work?
When `remote.ssh.useLocalServer` is on? Yes, it is an infinite loop.

**Comment by tanhakabir** [comment]
> Were you seeing this infinite loop yesterday when you said it didn't work?

Yesterday when you said that when `remote.ssh.useLocalServer` is `false` it didn't work. Did you also see it get stuck on selecting the platform?

Sorry so far I haven't figured out the issue yet from the remote logs.

Just incase would you also be able to use the command `Toggle Dev Tools` to see if there's any interesting logs in the console when you fail to connect?

**Comment by an0** [comment]
> > Were you seeing this infinite loop yesterday when you said it didn't work?
> 
> Yesterday when you said that when `remote.ssh.useLocalServer` is `false` it didn't work. Did you also see it get stuck on selecting the platform?

Yes

> Sorry so far I haven't figured out the issue yet from the remote logs.
> 
> Just incase would you also be able to use the command `Toggle Dev Tools` to see if there's any interesting logs in the console when you fail to connect?

<img width="555" alt="Screen Shot 2021-12-02 at 5 43 05 PM" src="https://user-images.githubusercontent.com/100976/144530412-8219ac46-62a2-42e0-9737-0e3cc23ef8af.png">

**Comment by tanhakabir** [comment]
Sorry for the delay! I just noticed this log in your original log: `If you continue to see this message, you can try toggling the remote.SSH.useFlock setting`

It seems like it's struggling to acquire the lock. There's many reasons for why this can happen. 

Could you try first to run `Kill VS Code Server on Host` with your remote. If that doesn't work could you try manually deleting  `/home/an0/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/vscode-remote-lock.an0.ccbaa2d27e38e5afa3e5c21c1c7bef4657064247` and then trying to connect again?

**Comment by an0** [comment]
I tried `Kill VS Code Server on Host`. It works! Thank you so much!
