### ISSUE TITLE
VS Code Server not starting up

### ISSUE THREAD

**Issue by MWH-Rookie** [microsoft/vscode-remote-release#5986]
Hi everyone

I am not an experienced coder (still learning).

Now I wanted to run vs code on my laptop and connect to my NAS on which I have a chroot (got it with a little help of a friend). But I have a problem to get the server starting.

```
[11:06:19.768] Log Level: 2
[11:06:19.770] remote-ssh@0.66.1
[11:06:19.770] linux x64
[11:06:19.772] SSH Resolver called for "ssh-remote+192.168.1.135", attempt 1
[11:06:19.773] "remote.SSH.useLocalServer": true
[11:06:19.774] "remote.SSH.path": undefined
[11:06:19.774] "remote.SSH.configFile": undefined
[11:06:19.774] "remote.SSH.useFlock": true
[11:06:19.774] "remote.SSH.lockfilesInTmp": false
[11:06:19.774] "remote.SSH.localServerDownload": auto
[11:06:19.774] "remote.SSH.remoteServerListenOnSocket": false
[11:06:19.775] "remote.SSH.showLoginTerminal": false
[11:06:19.775] "remote.SSH.defaultExtensions": []
[11:06:19.775] "remote.SSH.loglevel": 2
[11:06:19.775] SSH Resolver called for host: 192.168.1.135
[11:06:19.776] Setting up SSH remote "192.168.1.135"
[11:06:19.780] Acquiring local install lock: /tmp/vscode-remote-ssh-90052d39-install.lock
[11:06:19.795] Looking for existing server data file at /home/martin/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-90052d39-ccbaa2d27e38e5afa3e5c21c1c7bef4657064247-0.66.1/data.json
[11:06:19.796] Using commit id "ccbaa2d27e38e5afa3e5c21c1c7bef4657064247" and quality "stable" for server
[11:06:19.800] Install and start server if needed
[11:06:19.805] PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[11:06:19.806] Checking ssh with "ssh -V"
[11:06:19.816] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.3, OpenSSL 1.1.1f  31 Mar 2020

[11:06:19.822] askpass server listening on /run/user/1000/vscode-ssh-askpass-5ab416f848a93087e5f13e13106e2291e95e7276.sock
[11:06:19.823] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-f0c8591baf4f515ec24cc23b2579f0d675160986.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","41983","-o","ConnectTimeout=15","192.168.1.135"],"dataFilePath":"/home/martin/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-90052d39-ccbaa2d27e38e5afa3e5c21c1c7bef4657064247-0.66.1/data.json"}
[11:06:19.823] Local server env: {"DISPLAY":":1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-5ab416f848a93087e5f13e13106e2291e95e7276.sock"}
[11:06:19.829] Spawned 239712
[11:06:19.949] > local-server-1> Spawned ssh, pid=239720
[11:06:19.951] stderr> OpenSSH_8.2p1 Ubuntu-4ubuntu0.3, OpenSSL 1.1.1f  31 Mar 2020
[11:06:20.084] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:9msnW/aY5s88LQlLH6wjm/y68J7Nb0LU7IDZr7LG7UA
[11:06:20.221] Got askpass request: {"request":"root@192.168.1.135's password:"}
[11:06:20.223] Showing password prompt
[11:06:20.225] Listening for interwindow password on /run/user/1000/vscode-ssh-askpass-1045b98f7c7560a30c5fb62ffaed64292e17e093.sock
[11:06:20.225] Writing password prompt to globalState
[11:06:22.950] Got password response
[11:06:22.950] Interactor gave response: ********
[11:06:22.951] Cleaning up other-window auth server
[11:06:23.186] stderr> Authenticated to 192.168.1.135 ([192.168.1.135]:66666).
[11:06:23.218] > Linux DiskStation213 3.2.40 #25556 Thu Mar 4 17:56:47 CST 2021 armv7l
> 
> The programs included with the Debian GNU/Linux system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
> permitted by applicable law.
[11:06:23.236] stderr> mesg: 
[11:06:23.236] stderr> ttyname failed
[11:06:23.236] stderr> : Invalid argument
[11:06:23.237] > ready: 7f4ccc6a8a58
[11:06:23.246] > Linux 3.2.40 #25556 Thu Mar 4 17:56:47 CST 2021
[11:06:23.247] Platform: linux
[11:06:23.317] > 7f4ccc6a8a58: running
[11:06:23.494] > Acquiring lock on /root/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/vscode-remote-lock.root.ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
> Found existing installation at /root/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247...
> Checking /root/.vscode-server/.ccbaa2d27e38e5afa3e5c21c1c7bef4657064247.log and /root/.vscode-server/.ccbaa2d27e38e5afa3e5c21c1c7bef4657064247.pid for a running server
[11:06:23.496] > Looking for server with pid: 20461
[11:06:23.699] > Starting server with command... /root/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/server.sh --start-server --host=127.0.0.1 --enable-remote-auto-shutdown  --port=0  &> "/root/.vscode-server/.ccbaa2d27e38e5afa3e5c21c1c7bef4657064247.log" < /dev/null
> printenv:
>     LS_COLORS=
>     LC_MEASUREMENT=de_DE.UTF-8
>     SSH_CONNECTION=192.168.1.116 48674 192.168.1.135 66666
>     LC_PAPER=de_DE.UTF-8
>     LC_MONETARY=de_DE.UTF-8
>     LANG=en_US.UTF-8
>     TZ=Europe/Berlin
>     MAYAN_ALLOWED_HOSTS=['*']
>     OLDPWD=/root
>     MAYAN_CELERY_RESULT_BACKEND=redis://:mayanredispassword@127.0.0.1:6379/1
>     MAYAN_CELERY_BROKER_URL=redis://:mayanredispassword@127.0.0.1:6379/0
>     LC_NAME=de_DE.UTF-8
>     USER=root
>     PWD=/home/basicfolder
>     HOME=/root
>     SSH_CLIENT=192.168.1.116 48674 66666
>     LC_ADDRESS=de_DE.UTF-8
>     LC_NUMERIC=de_DE.UTF-8
>     MAYAN_MEDIA_ROOT=/home/basicfolder/mayan-media/
>     MAIL=/var/mail/root
>     SHELL=/bin/bash
>     SHLVL=2
>     PYTHONPATH=/home/basicfolder/mayan-media/mayan_settings
>     LC_TELEPHONE=de_DE.UTF-8
>     VSCODE_AGENT_FOLDER=/root/.vscode-server
>     QT_QPA_PLATFORM=offscreen
>     LOGNAME=root
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
>     LC_IDENTIFICATION=de_DE.UTF-8
>     LC_TIME=de_DE.UTF-8
>     _=/usr/bin/printenv
> Spawned remote server: 21297
> Waiting for server log...
[11:06:23.749] > Waiting for server log...
[11:06:23.801] > Waiting for server log...
[11:06:23.858] > Waiting for server log...
[11:06:23.915] > Waiting for server log...
[11:06:23.973] > Waiting for server log...
[11:06:24.034] > Waiting for server log...
[11:06:24.096] > Waiting for server log...
[11:06:24.148] > Waiting for server log...
[11:06:24.210] > Waiting for server log...
[11:06:24.263] > Waiting for server log...
[11:06:24.322] > Waiting for server log...
[11:06:24.380] > Waiting for server log...
[11:06:24.444] > Waiting for server log...
[11:06:24.497] > Waiting for server log...
[11:06:24.554] > Waiting for server log...
[11:06:24.616] > Waiting for server log...
[11:06:24.670] > Waiting for server log...
[11:06:24.728] > Waiting for server log...
[11:06:24.787] > Waiting for server log...
[11:06:24.852] > Waiting for server log...
[11:06:24.905] > Waiting for server log...
[11:06:24.962] > Waiting for server log...
[11:06:25.020] > Waiting for server log...
[11:06:25.082] > Waiting for server log...
[11:06:25.140] > Waiting for server log...
[11:06:25.195] > Waiting for server log...
[11:06:25.259] > Waiting for server log...
[11:06:25.316] > Waiting for server log...
[11:06:25.370] > Waiting for server log...
[11:06:25.429] > Waiting for server log...
[11:06:25.487] > Waiting for server log...
[11:06:25.551] > Waiting for server log...
[11:06:25.605] > Waiting for server log...
[11:06:25.671] > Waiting for server log...
[11:06:25.720] > Waiting for server log...
[11:06:25.789] > Waiting for server log...
[11:06:25.854] > Waiting for server log...
[11:06:25.912] > Waiting for server log...
[11:06:25.976] > Waiting for server log...
[11:06:26.063] > Waiting for server log...
[11:06:26.094] > Waiting for server log...
[11:06:26.147] > Waiting for server log...
[11:06:26.207] > Waiting for server log...
[11:06:26.266] > Waiting for server log...
[11:06:26.325] > Waiting for server log...
[11:06:26.566] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[11:06:26.713] > Waiting for server log...
> Waiting for server log...
[11:06:26.964] > Waiting for server log...
> Waiting for server log...
[11:06:27.181] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[11:06:27.637] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[11:06:27.640] > Waiting for server log...
> Waiting for server log...
[11:06:27.668] > Waiting for server log...
[11:06:27.721] > Waiting for server log...
[11:06:27.779] > Waiting for server log...
[11:06:27.840] > Waiting for server log...
[11:06:27.899] > Waiting for server log...
[11:06:27.956] > Waiting for server log...
[11:06:28.030] > Waiting for server log...
[11:06:28.078] > Waiting for server log...
[11:06:28.131] > Waiting for server log...
[11:06:28.193] > Waiting for server log...
[11:06:28.249] > Waiting for server log...
[11:06:28.309] > Waiting for server log...
[11:06:28.367] > Waiting for server log...
[11:06:28.436] > Waiting for server log...
[11:06:28.489] > Waiting for server log...
[11:06:28.544] > Waiting for server log...
[11:06:28.604] > Waiting for server log...
[11:06:28.668] > Waiting for server log...
[11:06:28.718] > Waiting for server log...
[11:06:28.776] > Waiting for server log...
[11:06:28.845] > Waiting for server log...
[11:06:28.896] > Waiting for server log...
[11:06:28.952] > Waiting for server log...
[11:06:29.008] > Waiting for server log...
[11:06:29.067] > Waiting for server log...
[11:06:29.126] > Waiting for server log...
[11:06:29.189] > Waiting for server log...
[11:06:29.253] > Waiting for server log...
[11:06:29.303] > Waiting for server log...
[11:06:29.364] > Waiting for server log...
[11:06:29.420] > Waiting for server log...
[11:06:29.481] > Waiting for server log...
[11:06:29.539] > Waiting for server log...
[11:06:29.601] > Waiting for server log...
[11:06:29.661] > Waiting for server log...
[11:06:29.713] > Waiting for server log...
[11:06:29.771] > Waiting for server log...
[11:06:29.841] > Waiting for server log...
[11:06:29.897] > Waiting for server log...
[11:06:29.954] > Waiting for server log...
[11:06:30.012] > Waiting for server log...
[11:06:30.075] > Waiting for server log...
[11:06:30.130] > Waiting for server log...
[11:06:30.192] > Waiting for server log...
[11:06:30.254] > Waiting for server log...
[11:06:30.308] > Waiting for server log...
[11:06:30.366] > Waiting for server log...
[11:06:30.427] > Waiting for server log...
[11:06:30.520] > Waiting for server log...
[11:06:30.543] > Waiting for server log...
[11:06:30.603] > Waiting for server log...
[11:06:30.674] > Waiting for server log...
[11:06:30.721] > Waiting for server log...
[11:06:30.774] > Waiting for server log...
[11:06:30.832] > Waiting for server log...
[11:06:30.894] > Waiting for server log...
[11:06:30.948] > Waiting for server log...
[11:06:31.000] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[11:06:31.047] > Server did not start successfully. Full server log at /root/.vscode-server/.ccbaa2d27e38e5afa3e5c21c1c7bef4657064247.log >>>
> /root/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/server.sh: 12: /root/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/server.sh: /root/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/node: not found
[11:06:31.050] > <<< End of server log
> 7f4ccc6a8a58: start
> exitCode==32==
> listeningOn====
> osReleaseId==debian==
> arch==armv7l==
> tmpDir==/tmp==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==7373==
> 7f4ccc6a8a58: end
[11:06:31.051] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==debian==
arch==armv7l==
tmpDir==/tmp==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==7373==

[11:06:31.053] Terminating local server
[11:06:31.055] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (/home/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:429127)
	at u (/home/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:423450)
	at Object.t.handleInstallOutput (/home/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:427869)
	at Object.e [as tryInstallWithLocalServer] (/home/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:467444)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:484911
	at async Object.t.withShowDetailsEvent (/home/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:488706)
	at async /home/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:465968
	at async I (/home/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:462544)
	at async Object.t.resolveWithLocalServer (/home/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:465583)
	at async Object.t.resolve (/home/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:486311)
	at async /home/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:560057
[11:06:31.065] ------




[11:06:31.066] Local server exit: 15
```

I hope that I am right here to ask how I can solve this. The system is a Debian.

Best regards
Martin

**Comment by tanhakabir** [comment]
Hey! Thanks for submitting an issue.

Hm I'm seeing `> /root/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/server.sh: 12: /root/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/server.sh: /root/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/node: not found` in your logs which indicates to me that some dependency is missing from your remote system.

Would you be able to verify that your remote machine meets these criteria? https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites

**Comment by MWH-Rookie** [comment]
Hi @tanhakabir 
Thanks for your reply. I am not that experienced but I will try to give you all required information. A friend of mine showed me that relevant information is in /proc/cpuinfo:

`cat /proc/cpuinfo 
Processor	: Marvell PJ4Bv7 Processor rev 1 (v7l)
BogoMIPS	: 1196.85
Features	: swp half thumb fastmult vfp edsp vfpv3 vfpv3d16 tls 
CPU implementer	: 0x56
CPU architecture: 7
CPU variant	: 0x1
CPU part	: 0x581
CPU revision	: 1

Hardware	: Marvell Armada-370
Revision	: 0000
Serial		: 0000000000000000`

So, this could be relevant: "You may encounter issues with certain extensions with native dependencies with ARMv7l (AArch32) / ARMv8l (AArch64) glibc-based hosts, containers, or WSL and 64-bit x86 musl-based Alpine Linux."

But I am not sure, what the next sentence means for me: "For ARMv7l/ARMv8l, extensions may only include x86_64 versions of native modules or runtimes in the extension." What do I have to do?

**Comment by tanhakabir** [comment]
"You may encounter issues with certain extensions with native dependencies with ARMv7l (AArch32) / ARMv8l (AArch64) glibc-based hosts, containers, or WSL and 64-bit x86 musl-based Alpine Linux." 

This is referring to extensions running in the remote context. If you have `ARMv7l (AArch32) / ARMv8l (AArch64) glibc-based hosts, containers, or WSL and 64-bit x86 musl-based Alpine Linux` machines then some extensions after you connect to your remote machine might not work as expected.

Unfortunately verify from this...

```
cat /proc/cpuinfo
Processor : Marvell PJ4Bv7 Processor rev 1 (v7l)
BogoMIPS : 1196.85
Features : swp half thumb fastmult vfp edsp vfpv3 vfpv3d16 tls
CPU implementer : 0x56
CPU architecture: 7
CPU variant : 0x1
CPU part : 0x581
CPU revision : 1

Hardware : Marvell Armada-370
Revision : 0000
Serial : 0000000000000000
```

...if your remote machine meets the requirements. Would you be able to work with your friend to verify from the website to see if all your requirements are met?

**Comment by MWH-Rookie** [comment]
Dear @tanhakabir 
I will try my best and check the rest.
uname -r provides me with 3.2.40, so the kernel should be fine.
ldd --version gives me 2.24, so glibc should also be fine (<--- thank for the how to, I did not know how to check that)
**But strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX gives me: strings: '/usr/lib64/libstdc++.so.6': No such file**
python2.7 is installed according to dpkg -l
I have installed tar now.

bash, wget and curl are already installed

Distro specific:
libc6 is already the newest version
libstdc++6 is already the newest version
python-minimal is already the newest version
ca-certifcates is already the newest version.

Can you help me with the problem with the missing lib (see above)?

**Comment by tanhakabir** [comment]
Hmm are you part of a school or organization?

If you are, you probably need the help from your system admin or IT department to get `/usr/lib64/libstdc++.so.6` set up on your remote machines.

If not you can install `/usr/lib64/libstdc++.so.6` from here: https://pkgs.org/download/libstdc++.so.6(GLIBCXX_3.4.18) but this requires admin privileges which you won't have if your remote machines are managed by your school or work.

**Comment by MWH-Rookie** [comment]
No, it's just on my private NAS.

**Comment by MWH-Rookie** [comment]
But my friend told me that I cannot install 64 bit libs on another architecture.

**Comment by MWH-Rookie** [comment]
Just this minute he told me to check strings /usr/lib/*/libstdc++.so.6 | grep GLIBCXX, because this is different for debian now.

Here are the results:
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_DEBUG_MESSAGE_LENGTH

So, I guess the requirements are met, but the lib is in the wrong place, right?

**Comment by tanhakabir** [comment]
Hmm possibly. Sorry I'm not familiar with Marvell processors. You could try to see if you move the lib what happens?

**Comment by MWH-Rookie** [comment]
According to my friend the problem is that the interpreter /lib/ld-linux-armhf.so.3 is not available on my system and also cannot be installed due to incompatability between my debian and this version of vs code.

**Comment by tanhakabir** [comment]
I see, I'm sorry I don't think there's anything I can do to fix this for you. Thanks for looking into this so deeply, I appreciate it!
