### ISSUE TITLE
How to configure vscode remote ssh to use wallix bastion connection?

### ISSUE THREAD

**Issue by raulbethencourt** [microsoft/vscode-remote-release#6022]
Hi everybody,

At my company we start to work with wallix to make a connection to servers. I use vscode remote ssh to connect to servers and work directly, but I'm trying to configure the new server that passes through wallix, and it's not working.

This is the new command to connect to my server:

`ssh -l user@lamp:SSH:user ecrmut-wallix-number.host.net`

And here my config vscode:

```
Host vh33
  HostName lamp:SSH:user ecrmut-wallix-number.host.net
  User user
  ForwardAgent yes
  ControlMaster auto
```

Thanks in advance for ideas

**Comment by tanhakabir** [comment]
Hey! Could I also see your logs from the Remote-SSH output channel?

**Comment by raulbethencourt** [comment]
HI this is the logs
```
[09:31:44.525] Log Level: 2
[09:31:44.527] remote-ssh@0.66.1
[09:31:44.529] linux x64
[09:31:44.531] SSH Resolver called for "ssh-remote+vh33", attempt 1
[09:31:44.531] "remote.SSH.useLocalServer": false
[09:31:44.532] "remote.SSH.showLoginTerminal": false
[09:31:44.532] "remote.SSH.remotePlatform": {"213.182.42.136":"linux","vh31":"linux","vh23":"linux"}
[09:31:44.533] "remote.SSH.path": undefined
[09:31:44.533] "remote.SSH.configFile": /home/raul/.ssh/config
[09:31:44.533] "remote.SSH.useFlock": true
[09:31:44.533] "remote.SSH.lockfilesInTmp": false
[09:31:44.534] "remote.SSH.localServerDownload": auto
[09:31:44.534] "remote.SSH.remoteServerListenOnSocket": false
[09:31:44.534] "remote.SSH.showLoginTerminal": false
[09:31:44.535] "remote.SSH.defaultExtensions": []
[09:31:44.535] "remote.SSH.loglevel": 2
[09:31:44.535] SSH Resolver called for host: vh33
[09:31:44.535] Setting up SSH remote "vh33"
[09:31:44.549] Using commit id "ccbaa2d27e38e5afa3e5c21c1c7bef4657064247" and quality "stable" for server
[09:31:44.551] Install and start server if needed
[09:31:46.776] PATH: /home/raul/.nvm/versions/node/v14.17.2/bin:/home/raul/.yarn/bin:/home/raul/.config/yarn/global/node_modules/.bin:/home/raul/.local/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/raul/.cargo/bin:/home/raul/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[09:31:46.776] Checking ssh with "ssh -V"
[09:31:46.798] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020

[09:31:46.804] Using SSH config file "/home/raul/.ssh/config"
[09:31:46.805] Running script with connection command: ssh -T -D 39929 -o ConnectTimeout=15 -F '/home/raul/.ssh/config' vh33 bash
[09:31:46.976] > ssh: Could not resolve hostname bns-lamp-13:SSH:raul-bns: Name or service not known
[09:31:46.976] Got some output, clearing connection timeout
[09:31:47.227] "install" terminal command done
[09:31:47.227] Install terminal quit with output: ssh: Could not resolve hostname bns-lamp-13:SSH:raul-bns: Name or service not known
[09:31:47.228] Received install output: ssh: Could not resolve hostname bns-lamp-13:SSH:raul-bns: Name or service not known
[09:31:47.230] Resolver error: Error: Could not resolve hostname
	at Function.Offline (/home/raul/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:429244)
	at /home/raul/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:426685
	at Object.t.handleInstallOutput (/home/raul/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:427172)
	at Object.t.tryInstall (/home/raul/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:521703)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/raul/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:485356
	at async Object.t.withShowDetailsEvent (/home/raul/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:488706)
	at async Object.t.resolve (/home/raul/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:486435)
	at async /home/raul/.vscode/extensions/ms-vscode-remote.remote-ssh-0.66.1/out/extension.js:1:560057
[09:31:47.239] ------
```

**Comment by tanhakabir** [comment]
And to verify are you able to run `ssh -o ConnectTimeout=15 -F '/home/raul/.ssh/config' vh33 bash` on your terminal?

**Comment by raulbethencourt** [comment]
It doesn't works :
```
[raul@] ~/sites/tests 🐘 v7.3.33
➜ ssh -o ConnectTimeout=15 -F '/home/raul/.ssh/config' vh33 bash
ssh: Could not resolve hostname bns-lamp:SSH:bns: Name or service not known
[raul@] ~/sites/tests 🐘 v7.3.33
➜ 
```

**Comment by raulbethencourt** [comment]
Sorry I've edited the logs coz I've puted wrong ones. Now they are right.

**Comment by tanhakabir** [comment]
What does your config file look like? Especially with the error `garbage at end of line; "ecrmut-wallix-number.host.net".`

**Comment by raulbethencourt** [comment]
config file :
```
Host vh33
  HostName lamp:SSH:user ecrmut-wallix-number.host.net
  User user
  ForwardAgent yes
  ControlMaster auto
```

**Comment by tanhakabir** [comment]
Hm there's something wrong with your config but I can't tell what exactly the issue is. The Remote-SSH extension uses the same ssh binary that your terminal uses to connect to the remote. 

Could you investigate why you get `garbage at end of line;` error? Once that is resolved it should work in VS Code as well.

**Comment by raulbethencourt** [comment]
I found possible solution...
write config like this : 
```
Host vh33
  HostName "lamp:SSH:user ecrmut-wallix-number.host.net"
  User user
  ForwardAgent yes
  ControlMaster auto
```
The problem is the space in the ip. Il check tomorrow

**Comment by raulbethencourt** [comment]
Hi i found the solution, this is my config now :
```
Host vh33
	HostName "ecrmut-wallix-number.host.net"
	User "user@lamp:SSH:user"
```
Thanks a lot for your help 👍🏽

**Comment by tanhakabir** [comment]
No worries!
