### ISSUE TITLE
Docker command not found on remote host

### ISSUE THREAD

**Issue by jbencook** [microsoft/vscode-remote-release#6026]
Starting in version v0.207.0, I get `The 'docker' command was not found. Make sure Docker is installed.` every time I run `Remote-Containers: Rebuild and Reopen in Container` when my Docker host is a remote machine. Installing v0.206.0 or earlier solves it.

- VSCode Version: 1.63.0 (Universal)
- Local OS Version: macOS Monterey 12.0.1
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: Here's my `devcontainer.json`. I also have `docker.host` set to a remote machine:

```
{
  "name": "retinanet",
  "build": {
    "dockerfile": "../Dockerfile"
  },
  "settings": {
    "python.pythonPath": "/usr/local/bin/python",
    "python.languageServer": "Pylance",
    "python.linting.enabled": true,
    "python.formatting.blackPath": "/usr/local/bin/black",
    "python.formatting.provider": "black",
    "editor.formatOnSave": true
  },
  "extensions": [
    "ms-python.python",
    "ms-python.vscode-pylance"
  ],
	"mounts": [
		"source=/home/jbencook/.ssh,target=/root/.ssh,type=bind,consistency=cached",
		"source=/home/jbencook/.aws,target=/root/.aws,type=bind,consistency=cached",
		"source=/home/jbencook/.gitconfig,target=/root/.gitconfig,type=bind,consistency=cached",
		"source=/data,target=/data,type=bind,consistency=cached",
		"source=projectname-bashhistory,target=/commandhistory,type=volume"
	],
  "workspaceMount": "source=/home/jbencook/code/retinanet,target=/code,type=bind",
  "workspaceFolder": "/code",
  "runArgs": [
    "--gpus=all"
  ],
  "forwardPorts": [
    8888
  ]
}
```

Steps to Reproduce:

1. Install Remote - Containers extension v0.207.0 or newer
2. Run `Remote-Containers: Rebuild and Reopen in Container` with a remote docker host

Everything works fine when my local machine is the Docker host. And I confirmed that I get the problem when the remote host is both an Ubuntu workstation and an Amazon Linux instance.

**Comment by Chuxel** [comment]
@jbencook Can you also post the complete logs you see (if you're getting more than this one error)?

**Comment by bakaleks** [comment]
I am experiencing exactly the same issue after upgrade to vscode 1.63 and Remote-Containers 0.209.3. Here is what error message looks like:

<img width="937" alt="Screenshot 2021-12-10 at 10 38 36" src="https://user-images.githubusercontent.com/1871986/145554724-29a0b764-8748-4fad-ba1d-a454ebe4fe5a.png">

**Comment by jbencook** [comment]
> Just to be clear, you still see this with v0.209.3 that was released today, correct?

Yes, I just confirmed it's happening with everything v0.207.0 and newer including v0.209.3 and v0.209.4.

Here are all the logs I can copy from my terminal when it happens:

```
 on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1317702) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1498 ms] Host server: (node:1317702) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
[1499 ms] Error: spawn /bin/bash ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[1500 ms] Setting up container for folder or workspace: /Users/jbencook/code/nsg-dataset-management
[1500 ms] Host: ssh://jbencook@192.168.4.42
[1506 ms] Start: Check Docker is running
[1506 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[1511 ms] Host server: (node:1317702) UnhandledPromiseRejectionWarning: Error: spawn docker ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[1511 ms] Host server: (node:1317702) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[1513 ms] spawn docker ENOENT
[1517 ms] Docker returned an error code ENOENT, message: spawn docker ENOENT
[1518 ms] Host server: (node:1317702) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
```

The current workaround for me is to install v0.206.0, which makes everything work as expected.

**Comment by chrmarti** [comment]
Could you retry with trace logging for Remote-Containers enabled and post the entire log? (The terminal has a Select All command in its context menu. Or you can look at past logs using `F1` > `Remote-Containers Developer: Show All Logs...`.)
<img width="356" alt="image" src="https://user-images.githubusercontent.com/9205389/145615128-a42aa3ca-bf2e-4d0a-a8e4-e516391b56b4.png">

**Comment by jbencook** [comment]
It's truncating a bunch of the logs. I can't figure out a way to copy all of them, but here's what I see when I switch the log level to trace:

```
s with a non-zero exit code.
[305 ms] Stop (61 ms): Run in Host: /bin/bash -lic '/home/jbencook/.vscode-remote-containers/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/node' -p '"2e9b8076468cd243a758a7449ae4a7aa" + JSON.stringify(process.env) + "2e9b8076468cd243a758a7449ae4a7aa"'
[305 ms] Error: spawn /bin/bash ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[305 ms] Host server: (node:1442585) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
[307 ms] Setting up container for folder or workspace: /Users/jbencook/code/nsg-dataset-management
[307 ms] Host: ssh://jbencook@192.168.4.42
[312 ms] Start: Check Docker is running
[312 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[315 ms] Host server: (node:1442585) UnhandledPromiseRejectionWarning: Error: spawn docker ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:1442585) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[316 ms] Stop (4 ms): Run in Host: docker version --format {{.Server.APIVersion}}
[316 ms] spawn docker ENOENT
[317 ms] Stop (5 ms): Check Docker is running
[319 ms] Docker returned an error code ENOENT, message: spawn docker ENOENT
[320 ms] Host server: (node:1442585) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
```

**Comment by chrmarti** [comment]
Should be fixed in Remote-Containers 0.209.5. Let me know if you still see this issue there. Thanks.

FYI: Instead of having your devcontainer.json locally, you can now also have it on your SSH server. To try that use the Remote-SSH extension to connect to the SSH server, open your workspace folder on the SSH server and then use the `Reopen in Container` command (`F1` > `Remote-Containers: Reopen in Container`) to connect to the dev container. (Assuming you have your devcontainer.json in the workspace folder on the SSH server, otherwise you first need to copy it there.)

**Comment by jbencook** [comment]
I'll give that a try -- thank you!

**Comment by meskill** [comment]
@chrmarti The issue still happens for me on version 0.209.5. But only when using custom docker command with settings `remote.containers.dockerPath` as leaving it empty makes everything work

<details>
<summary>My trace logs</summary>
[78 ms] Remote-Containers 0.209.5 in VS Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e).
[78 ms] Start: Run: wsl -d alpine -e wslpath -u \\wsl$\alpine\home\meskill\Projects\test\rust
[162 ms] Stop (84 ms): Run: wsl -d alpine -e wslpath -u \\wsl$\alpine\home\meskill\Projects\test\rust
[332 ms] Start: Resolving Remote
[336 ms] Start: Run: wsl -d alpine -e wslpath -u \\wsl$\alpine\home\meskill\Projects\test\rust
[418 ms] Stop (82 ms): Run: wsl -d alpine -e wslpath -u \\wsl$\alpine\home\meskill\Projects\test\rust
[419 ms] Start: Run: wsl -d alpine -e /bin/sh -c cd '/home/meskill/Projects/test/rust' && /bin/sh
[423 ms] Start: Run in host: id -un
[460 ms] meskill
[461 ms] 
[461 ms] Stop (38 ms): Run in host: id -un
[461 ms] Start: Run in host: cat /etc/passwd
[463 ms] Stop (2 ms): Run in host: cat /etc/passwd
[463 ms] Start: Run in host: echo ~
[464 ms] /home/meskill
[464 ms] 
[464 ms] Stop (1 ms): Run in host: echo ~
[465 ms] Start: Run in host: test -x '/home/meskill/.vscode-remote-containers/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/node'
[465 ms] 
[466 ms] 
[466 ms] Stop (1 ms): Run in host: test -x '/home/meskill/.vscode-remote-containers/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/node'
[466 ms] Start: Run in host: test -f '/home/meskill/.vscode-remote-containers/dist/vscode-remote-containers-server-0.209.5.js'
[467 ms] 
[467 ms] 
[467 ms] Stop (1 ms): Run in host: test -f '/home/meskill/.vscode-remote-containers/dist/vscode-remote-containers-server-0.209.5.js'
[469 ms] userEnvProbe: loginInteractiveShell (default)
[469 ms] userEnvProbe shell: /usr/bin/fish
[470 ms] Start: Run in Host: /usr/bin/fish -lic '/home/meskill/.vscode-remote-containers/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/node' -p '"1e040e07dbb41a0925b1f4f86c02604b" + JSON.stringify(process.env) + "1e040e07dbb41a0925b1f4f86c02604b"'
[587 ms] Stop (117 ms): Run in Host: /usr/bin/fish -lic '/home/meskill/.vscode-remote-containers/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/node' -p '"1e040e07dbb41a0925b1f4f86c02604b" + JSON.stringify(process.env) + "1e040e07dbb41a0925b1f4f86c02604b"'
[587 ms] 1e040e07dbb41a0925b1f4f86c02604b{"PWD":"/home/meskill/Projects/test/rust","SHLVL":"3","WSLENV":"","WSL_DISTRO_NAME":"alpine","SHELL":"/bin/sh","HOME":"/home/meskill","TERM":"xterm-256color","WSL_HOST_IP":"192.168.144.1","WSL_IP":"192.168.157.237","SELF_IP":"192.168.157.237","NAME":"Tower","REMOTE_CONTAINERS_IPC":"","HOSTTYPE":"x86_64","WSL_INTEROP":"/run/WSL/11638_interop","LOGNAME":"meskill","USER":"meskill","PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Users/meski/AppData/Local/Vivaldi/Application:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/system32/wbem:/mnt/c/windows/system32/windowspowershell/v1.0/:/mnt/c/windows/system32/openssh/:/mnt/c/programdata/chocolatey/bin:/mnt/c/program files/microsoft vs code/bin:/mnt/c/program files/nvidia corporation/nvidia ngx:/mnt/c/program files/microsoft vs code/bin:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/system32/wbem:/mnt/c/windows/system32/windowspowershell/v1.0/:/mnt/c/windows/system32/openssh/:/mnt/c/program files/dotnet/:/mnt/c/program files/microsoft vs code/bin:/mnt/c/program files/nvidia corporation/nvidia nvdlisr:/mnt/c/program files/microsoft vs code/bin:/mnt/c/program files (x86)/git:/mnt/c/program files (x86)/windows kits/10/windows performance toolkit/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Users/meski/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/meski/AppData/Roaming/Code/User/globalStorage/ms-vscode-remote.remote-containers/cli-bin","HOST_IP":"192.168.144.1","REMOTE_CONTAINERS_SOCKETS":"[]","LANG":"en_US.UTF-8","OLDPWD":"/mnt/c/Program Files/Microsoft VS Code"}1e040e07dbb41a0925b1f4f86c02604b
[587 ms] 
[588 ms] userEnvProbe parsed: {
  "PWD": "/home/meskill/Projects/test/rust",
  "SHLVL": "3",
  "WSLENV": "",
  "WSL_DISTRO_NAME": "alpine",
  "SHELL": "/bin/sh",
  "HOME": "/home/meskill",
  "TERM": "xterm-256color",
  "WSL_HOST_IP": "192.168.144.1",
  "WSL_IP": "192.168.157.237",
  "SELF_IP": "192.168.157.237",
  "NAME": "Tower",
  "REMOTE_CONTAINERS_IPC": "",
  "HOSTTYPE": "x86_64",
  "WSL_INTEROP": "/run/WSL/11638_interop",
  "LOGNAME": "meskill",
  "USER": "meskill",
  "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Users/meski/AppData/Local/Vivaldi/Application:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/system32/wbem:/mnt/c/windows/system32/windowspowershell/v1.0/:/mnt/c/windows/system32/openssh/:/mnt/c/programdata/chocolatey/bin:/mnt/c/program files/microsoft vs code/bin:/mnt/c/program files/nvidia corporation/nvidia ngx:/mnt/c/program files/microsoft vs code/bin:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/system32/wbem:/mnt/c/windows/system32/windowspowershell/v1.0/:/mnt/c/windows/system32/openssh/:/mnt/c/program files/dotnet/:/mnt/c/program files/microsoft vs code/bin:/mnt/c/program files/nvidia corporation/nvidia nvdlisr:/mnt/c/program files/microsoft vs code/bin:/mnt/c/program files (x86)/git:/mnt/c/program files (x86)/windows kits/10/windows performance toolkit/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Users/meski/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/meski/AppData/Roaming/Code/User/globalStorage/ms-vscode-remote.remote-containers/cli-bin",
  "HOST_IP": "192.168.144.1",
  "REMOTE_CONTAINERS_SOCKETS": "[]",
  "LANG": "en_US.UTF-8",
  "OLDPWD": "/mnt/c/Program Files/Microsoft VS Code"
}
[588 ms] userEnvProbe PATHs:
Probe:     '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Users/meski/AppData/Local/Vivaldi/Application:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/system32/wbem:/mnt/c/windows/system32/windowspowershell/v1.0/:/mnt/c/windows/system32/openssh/:/mnt/c/programdata/chocolatey/bin:/mnt/c/program files/microsoft vs code/bin:/mnt/c/program files/nvidia corporation/nvidia ngx:/mnt/c/program files/microsoft vs code/bin:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/system32/wbem:/mnt/c/windows/system32/windowspowershell/v1.0/:/mnt/c/windows/system32/openssh/:/mnt/c/program files/dotnet/:/mnt/c/program files/microsoft vs code/bin:/mnt/c/program files/nvidia corporation/nvidia nvdlisr:/mnt/c/program files/microsoft vs code/bin:/mnt/c/program files (x86)/git:/mnt/c/program files (x86)/windows kits/10/windows performance toolkit/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Users/meski/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/meski/AppData/Roaming/Code/User/globalStorage/ms-vscode-remote.remote-containers/cli-bin'
Container: None
[589 ms] Setting up container for folder or workspace: /home/meskill/Projects/test/rust
[590 ms] Start: Check Docker is running
[591 ms] Start: Run in Host: fish -c 'docker $argv' version --format {{.Server.APIVersion}}
[628 ms] Host server: (node:11645) UnhandledPromiseRejectionWarning: Error: spawn fish -c 'docker $argv' ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11645) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[628 ms] Host server: (node:11645) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[628 ms] Stop (37 ms): Run in Host: fish -c 'docker $argv' version --format {{.Server.APIVersion}}
[630 ms] spawn fish -c 'docker $argv' ENOENT
[630 ms] Stop (40 ms): Check Docker is running
[633 ms] Docker returned an error code ENOENT, message: spawn fish -c 'docker $argv' ENOENT
[634 ms] Host server: (node:11645) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
</details>

**Comment by chrmarti** [comment]
@meskill I wasn't aware that adding options to the Docker path used to work with WSL. I have opened https://github.com/microsoft/vscode-remote-release/issues/6042 to track. Let's continue the discussion there. Thanks.

**Comment by bakaleks** [comment]
I'm still getting docker error on 0.209.5 and I don't have remote.containers.dockerPath set anywhere

```
[2021-12-13T09:53:54.191Z] Remote-Containers 0.209.5 in VS Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e).
[2021-12-13T09:53:54.191Z] Start: Run: ssh bakaleks@dev-server-01 /bin/sh -c /bin/sh
[2021-12-13T09:53:54.194Z] Start: Run in host: id -un
[2021-12-13T09:53:54.571Z] bakaleks
[2021-12-13T09:53:54.571Z] 
[2021-12-13T09:53:54.572Z] Stop (378 ms): Run in host: id -un
[2021-12-13T09:53:54.572Z] Start: Run in host: cat /etc/passwd
[2021-12-13T09:53:54.582Z] Stop (10 ms): Run in host: cat /etc/passwd
[2021-12-13T09:53:54.583Z] Start: Run in host: echo ~
[2021-12-13T09:53:54.589Z] /home/bakaleks
[2021-12-13T09:53:54.589Z] 
[2021-12-13T09:53:54.589Z] Stop (6 ms): Run in host: echo ~
[2021-12-13T09:53:54.589Z] Start: Run in host: test -x '/home/bakaleks/.vscode-remote-containers/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/node'
[2021-12-13T09:53:54.596Z] 
[2021-12-13T09:53:54.596Z] 
[2021-12-13T09:53:54.596Z] Stop (7 ms): Run in host: test -x '/home/bakaleks/.vscode-remote-containers/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/node'
[2021-12-13T09:53:54.596Z] Start: Run in host: test -f '/home/bakaleks/.vscode-remote-containers/dist/vscode-remote-containers-server-0.209.5.js'
[2021-12-13T09:53:54.603Z] 
[2021-12-13T09:53:54.603Z] 
[2021-12-13T09:53:54.603Z] Stop (7 ms): Run in host: test -f '/home/bakaleks/.vscode-remote-containers/dist/vscode-remote-containers-server-0.209.5.js'
[2021-12-13T09:53:54.610Z] userEnvProbe: loginInteractiveShell (default)
[2021-12-13T09:53:54.610Z] userEnvProbe shell: /bin/bash
[2021-12-13T09:53:55.385Z] Host server: (node:8875) UnhandledPromiseRejectionWarning: Error: spawn /bin/bash ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8875) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8875) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2021-12-13T09:53:55.394Z] Error: spawn /bin/bash ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2021-12-13T09:53:55.395Z] Host server: (node:8875) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
[2021-12-13T09:53:55.428Z] Host server: (node:8875) UnhandledPromiseRejectionWarning: Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:8875) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[2021-12-13T09:53:55.435Z] Host server: (node:8875) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
[2021-12-13T09:53:55.444Z] Host server: (node:8875) UnhandledPromiseRejectionWarning: Error: spawn test ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2021-12-13T09:53:55.444Z] Host server: (node:8875) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[2021-12-13T09:53:55.450Z] Host server: (node:8875) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
```

**Comment by terroirman** [comment]
@bakaleks , I had the same behavior. Re-opening the folder locally and doing "rebuild and reopen in container" worked for me.
