### ISSUE TITLE
"Open folder in container" fails

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#6029]
I have similar problem on 1.63. When I choose "Open folder in container" and select local folder with devcontainer config, it fails with this error:
![image](https://user-images.githubusercontent.com/9105882/145529722-87615135-c982-42bf-8a0f-45126ec785a2.png)

The same config works on 1.62.3. I'm on Kubuntu 20.04.

_Originally posted by @maciek16180 in https://github.com/microsoft/vscode-remote-release/issues/6023#issuecomment-990661391_

**Comment by chrmarti** [comment]
This might be a different problem than #6023. Tracking here.

**Comment by daMichaelB** [comment]
same here. I added `log_level = trace` in the settings.

Here are the logs (hope it is helpful):

```
[823 ms] Stop (89 ms): Run in Host: /bin/bash -lic '/home/ec2-user/.vscode-remote-containers/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/node' -p '"89b28e98cccec2c7ef0e50d2caee6e39" + JSON.stringify(process.env) + "89b28e98cccec2c7ef0e50d2caee6e39"'
[824 ms] Error: spawn /bin/bash ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[824 ms] Host server: (node:7666) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
[847 ms] Setting up container for folder or workspace: /Users/XXXXXX/...../XXXXXX/
[848 ms] Host: ssh://user@10.x.x.x
[849 ms] Start: Check Docker is running
[850 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[876 ms] Host server: (node:7666) UnhandledPromiseRejectionWarning: Error: spawn docker ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:7666) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[901 ms] Stop (51 ms): Run in Host: docker version --format {{.Server.APIVersion}}
[904 ms] spawn docker ENOENT
[904 ms] Stop (55 ms): Check Docker is running
[909 ms] Docker returned an error code ENOENT, message: spawn docker ENOENT
[910 ms] Host server: (node:7666) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
```

**Comment by chrmarti** [comment]
@daMichaelB Does the EC2 VM have `/bin/bash`?

**Comment by cawhitworth** [comment]
I'm seeing almost the exact same thing, running VS Code on Windows 11, connecting to an Ubuntu 20.04 host running Docker. It started happening maybe an hour ago, after I restarted VS Code and it updated to 1.63. It was working immediately prior (this is my primary dev environment):

```
[739 ms] userEnvProbe: loginInteractiveShell (default)
[739 ms] userEnvProbe shell: /bin/bash
[785 ms] Host server: (node:353381) UnhandledPromiseRejectionWarning: Error: spawn /bin/bash ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:353381) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:353381) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[790 ms] Error: spawn /bin/bash ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[790 ms] Host server: (node:353381) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
[797 ms] Setting up container for folder or workspace: c:\Users\chwhitwo\source\Workspaces\EVK workspace
[797 ms] Host: ssh://chris@192.168.1.171
[798 ms] Start: Check Docker is running
[798 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[804 ms] Host server: (node:353381) UnhandledPromiseRejectionWarning: Error: spawn docker ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:353381) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[810 ms] Host server: (node:353381) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
[813 ms] spawn docker ENOENT
[817 ms] Docker returned an error code ENOENT, message: spawn docker ENOENT
```

**Comment by cawhitworth** [comment]
I'm seeing almost the exact same thing, running VS Code on Windows 11, connecting to an Ubuntu 20.04 host running Docker. It started happening maybe an hour ago, after I restarted VS Code and it updated to 1.63. It was working immediately prior (this is my primary dev environment):

```
[739 ms] userEnvProbe: loginInteractiveShell (default)
[739 ms] userEnvProbe shell: /bin/bash
[785 ms] Host server: (node:353381) UnhandledPromiseRejectionWarning: Error: spawn /bin/bash ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:353381) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:353381) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[790 ms] Error: spawn /bin/bash ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[790 ms] Host server: (node:353381) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
[797 ms] Setting up container for folder or workspace: c:\workspace
[797 ms] Host: ssh://user@x.x.x.x
[798 ms] Start: Check Docker is running
[798 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[804 ms] Host server: (node:353381) UnhandledPromiseRejectionWarning: Error: spawn docker ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:353381) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[810 ms] Host server: (node:353381) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
[813 ms] spawn docker ENOENT
[817 ms] Docker returned an error code ENOENT, message: spawn docker ENOENT
```

**Comment by chrmarti** [comment]
Does everyone seeing this have the `"docker.host"` setting or the `DOCKER_HOST` env variable set to a `ssh://...` URI and uses a local folder with a devcontainer.json? (This looks like https://github.com/microsoft/vscode-remote-release/issues/6026.)

**Comment by chrmarti** [comment]
Should be fixed in Remote-Containers 0.209.5. Let me know if you still see this issue there. Thanks.

FYI: Instead of having your devcontainer.json locally, you can now also have it on your SSH server. To try that use the Remote-SSH extension to connect to the SSH server, open your workspace folder on the SSH server and then use the `Reopen in Container` command (`F1` > `Remote-Containers: Reopen in Container`) to connect to the dev container. (Assuming you have your devcontainer.json in the workspace folder on the SSH server, otherwise you first need to copy it there.)

**Comment by maciek16180** [comment]
It works for me now, thanks!

**Comment by daMichaelB** [comment]
Hey @chrmarti . With `0.209.5` it works like a charm! THANK YOU a lot from my side for the quick fix.

**Comment by cawhitworth** [comment]
Working again here - thanks for the fast turnaround on the fix
