### ISSUE TITLE
Remote Connection to Raspberry Zero not working from M1 Mac (but fine from Windows)

### ISSUE THREAD

**Issue by matthiasg** [microsoft/vscode-remote-release#6035]
I was able to connect to my raspberry zero W from VSCode running on Win11 (SurfaceBook 2) fine. Now on my MBP M1 Pro Max it is **no longer** possible.

This seems related to https://github.com/microsoft/vscode-remote-release/issues/669 but it makes no sense to say it doesn't work, as it works fine from my surface book 2 against the exact same raspberry :)

**Env**

```
Version: 1.63.0 (Universal)
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-07T05:15:48.091Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.1.0
```

**Log**

```
[09:05:37.927] Log Level: 2
[09:05:37.928] remote-ssh@0.68.0
[09:05:37.928] darwin arm64
[09:05:37.929] SSH Resolver called for "ssh-remote+raspberry-frame", attempt 1
[09:05:37.929] "remote.SSH.useLocalServer": true
[09:05:37.929] "remote.SSH.path": undefined
[09:05:37.929] "remote.SSH.configFile": undefined
[09:05:37.929] "remote.SSH.useFlock": true
[09:05:37.929] "remote.SSH.lockfilesInTmp": false
[09:05:37.929] "remote.SSH.localServerDownload": auto
[09:05:37.929] "remote.SSH.remoteServerListenOnSocket": false
[09:05:37.929] "remote.SSH.showLoginTerminal": false
[09:05:37.930] "remote.SSH.defaultExtensions": []
[09:05:37.930] "remote.SSH.loglevel": 2
[09:05:37.930] "remote.SSH.serverPickPortsFromRange": {}
[09:05:37.930] "remote.SSH.enableDynamicForwarding": true
[09:05:37.930] "remote.SSH.serverInstallPath": {}
[09:05:37.930] SSH Resolver called for host: raspberry-frame
[09:05:37.930] Setting up SSH remote "raspberry-frame"
[09:05:37.932] Acquiring local install lock: /var/folders/yz/vqr9r5hj55jb08qx9sncx0h00000gn/T/vscode-remote-ssh-966b6181-install.lock
[09:05:37.936] Looking for existing server data file at /Users/mgt/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-966b6181-7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e-0.68.0/data.json
[09:05:37.937] Using commit id "7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e" and quality "stable" for server
[09:05:37.939] Install and start server if needed
[09:05:37.942] PATH: /Users/mgt/.nvm/versions/node/v16.13.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/mgt/Development/tools
[09:05:37.942] Checking ssh with "ssh -V"
[09:05:37.945] > OpenSSH_8.6p1, LibreSSL 2.8.3

[09:05:37.947] askpass server listening on /var/folders/yz/vqr9r5hj55jb08qx9sncx0h00000gn/T/vscode-ssh-askpass-d9a2b94df547a2c144b7759f39cf970c0d30d90b.sock
[09:05:37.947] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/yz/vqr9r5hj55jb08qx9sncx0h00000gn/T/vscode-ssh-askpass-0903776dd16b1439a72016862c1e786f53e8b3bc.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","55840","-o","ConnectTimeout=15","raspberry-frame"],"dataFilePath":"/Users/mgt/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-966b6181-7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e-0.68.0/data.json"}
[09:05:37.947] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/mgt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.68.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/mgt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.68.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/yz/vqr9r5hj55jb08qx9sncx0h00000gn/T/vscode-ssh-askpass-d9a2b94df547a2c144b7759f39cf970c0d30d90b.sock"}
[09:05:37.948] Spawned 30067
[09:05:38.008] > local-server-1> Spawned ssh, pid=30072
[09:05:38.010] stderr> OpenSSH_8.6p1, LibreSSL 2.8.3
[09:05:38.538] stderr> debug1: Server host key: ssh-ed25519 SHA256:2YAkq3Xce7i3F+YZI/3oIF5OVHY+s5tJcPgfH7Y/t1w
[09:05:38.678] stderr> Authenticated to 192.168.86.65 ([192.168.86.65]:22).
[09:05:39.231] > Linux raspberrypi 5.10.63+ #1459 Wed Oct 6 16:40:27 BST 2021 armv6l
> 
> The programs included with the Debian GNU/Linux system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
> permitted by applicable law.
[09:05:39.356] > 
[09:05:39.386] > SSH is enabled and the default password for the 'pi' user has not been changed.
[09:05:39.405] > This is a security risk - please login as the 'pi' user and type 'passwd' to set a new password.
[09:05:39.531] > ready: 33119de805d7
[09:05:39.551] > Linux 5.10.63+ #1459 Wed Oct 6 16:40:27 BST 2021
[09:05:39.552] Platform: linux
[09:05:39.781] > 33119de805d7: running
[09:05:40.146] > Unsupported architecture: armv6l
> 33119de805d7: start
> exitCode==27==
> listeningOn====
> osReleaseId==raspbian==
> arch==armv6l==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 33119de805d7: end
[09:05:40.147] Received install output: 
exitCode==27==
listeningOn====
osReleaseId==raspbian==
arch==armv6l==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[09:05:40.147] Unsupported architecture
[09:05:40.147] Terminating local server
[09:05:40.148] Resolver error: Error: The remote host's architecture is not supported
	at Function.ServerInstallError (/Users/mgt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.68.0/out/extension.js:1:430359)
	at u (/Users/mgt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.68.0/out/extension.js:1:424122)
	at Object.t.handleInstallOutput (/Users/mgt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.68.0/out/extension.js:1:429101)
	at Object.e [as tryInstallWithLocalServer] (/Users/mgt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.68.0/out/extension.js:1:469079)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/mgt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.68.0/out/extension.js:1:486771
	at async Object.t.withShowDetailsEvent (/Users/mgt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.68.0/out/extension.js:1:490561)
	at async /Users/mgt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.68.0/out/extension.js:1:467603
	at async E (/Users/mgt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.68.0/out/extension.js:1:464111)
	at async Object.t.resolveWithLocalServer (/Users/mgt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.68.0/out/extension.js:1:467218)
	at async Object.t.resolve (/Users/mgt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.68.0/out/extension.js:1:488171)
	at async /Users/mgt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.68.0/out/extension.js:1:564197
[09:05:40.151] ------




[09:05:40.151] Local server exit: 15
```

**Comment by tanhakabir** [comment]
Hm sorry for the slow response! That's definitely odd that different client machines would treat remotes differently. @roblourens do you have an idea why this could be the case?

**Comment by roblourens** [comment]
We don't support armv6: https://github.com/microsoft/vscode-remote-release/issues/669. Sure you are connecting to the same remote from windows?
