### ISSUE TITLE
[bug] remote ssh "TypeError [ERR_INVALID_OPT_VALUE]: The value "4294967295" is invalid for option "family""

### ISSUE THREAD

**Issue by baslr** [microsoft/vscode-remote-release#604]
- VSCode Version: Version 1.36.0-insider
- Local OS Version: OS X 10.12
- Remote OS Version: Debian 9 x86_64
- Remote Extension/Connection Type: SSH

When I try to connect to the remote machine I get this:

```
remote-ssh@0.42.0
SSH Resolver called for "ssh-remote+user"
SSH Resolver called for host: user
Setting up SSH remote "user"
Using commit id "c089daa858f34631f5f827ff8a0313bf1e2ded6d" and quality "insider" for server
Install and start server if needed
> Found existing installation at /home/user/.vscode-server-insiders/bin/c089daa858f34631f5f827ff8a0313bf1e2ded6d...
> Printing the current remote environment...
> SSH_CONNECTION=wan-ipv4addr 38810 10.0.2.15 22
> LANG=en_US.UTF-8
> XDG_SESSION_ID=32
> USER=user
> PWD=/home/user
> HOME=/home/user
> SSH_CLIENT=wan-ipv4addr 38810 22
> MAIL=/var/mail/user
> SHELL=/bin/bash
> SHLVL=2
> LANGUAGE=en_US:en
> VSCODE_AGENT_FOLDER=/home/user/.vscode-server-insiders
> LOGNAME=user
> XDG_RUNTIME_DIR=/run/user/1000
> PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
> _=/usr/bin/printenv
> Starting server...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> Server did not start successfully. Full server log:
> Remote configuration data at /home/user/.vscode-server-insiders
> 
> 
> *
> * Visual Studio Code Server
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license https://aka.ms/vscode-remote/license
> *
> 
> 
> dns.js:111
>     throw new ERR_INVALID_OPT_VALUE('family', family);
>     ^
> 
> TypeError [ERR_INVALID_OPT_VALUE]: The value "4294967295" is invalid for option "family"
>     at lookup (dns.js:111:11)
>     at net.js:1055:5
>     at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
>     at lookupAndConnect (net.js:1054:3)
>     at TLSSocket.Socket.connect (net.js:987:5)
>     at Object.exports.connect (_tls_wrap.js:1153:12)
>     at Agent.createConnection (https.js:119:22)
>     at Agent.createSocket (_http_agent.js:226:26)
>     at 
> Agent.addRequest (_http_agent.js:184:10)
>     at new ClientRequest (_http_client.js:239:16)
>     at Object.request (https.js:272:10)
>     at Function.Util.makeRequest (/home/user/.vscode-server-insiders/bin/c089daa858f34631f5f827ff8a0313bf1e2ded6d/node_modules/applicationinsights/out/Library/Util.js:288:26)
>     at Timeout.fetchAppId [as _onTimeout] (/home/user/.vscode-server-insiders/bin/c089daa858f34631f5f827ff8a0313bf1e2ded6d/node_modules/applicationinsights/out/Library/CorrelationIdManager.js:33:28)
>     at ontimeout (timers.js:427:11)
>     at tryOnTimeout (timers.js:289:5)
>     at listOnTimeout (timers.js:252:5)
>     at Timer.processTimers (timers.js:212:10)
> a1441c50-6f5c-4665-9117-aeb55679df3d====
"install" terminal command done
Received install output: a1441c50-6f5c-4665-9117-aeb55679df3d====
Failed to parse remote port from server output: a1441c50-6f5c-4665-9117-aeb55679df3d====
```

```
iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             10.0.2.15            tcp dpt:ssh
DROP       all  --  10.0.2.2             anywhere            
DROP       all  --  hostnet/24       anywhere            

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```

```
nslookup microsoft.com
Server:		10.0.2.3
Address:	10.0.2.3#53

Non-authoritative answer:
Name:	microsoft.com
Address: 40.112.72.205
Name:	microsoft.com
Address: 40.76.4.15
Name:	microsoft.com
Address: 104.215.148.63
Name:	microsoft.com
Address: 40.113.200.201
Name:	microsoft.com
Address: 13.77.161.179
```
the remote ssh target is a ipv4 only debian 9 virtual machine run with qemu.

**Comment by baslr** [comment]
v10.2.1 dns.js at line 111:
```
  if (family !== 0 && family !== 4 && family !== 6)
throw new ERR_INVALID_OPT_VALUE('family', family);
```

**Comment by baslr** [comment]
4294967295 is `0xff'ff'ff'ff`

**Comment by baslr** [comment]
nodejs/node/issues/19348

**Comment by baslr** [comment]
node version 10.2.1
```
> a = {f:undefined}
{ f: undefined }
> x = a.f >>> 0
4294967295
```

node version > 10.15
```
> a = {f:undefined}
{ f: undefined }
> x = a.f >>> 0
0
```
Its a node version problem.

**Comment by baslr** [comment]
I would suggest to upgrade to v10.16.0

**Comment by roblourens** [comment]
What is the plan for upgrading node versions @aeschli?

**Comment by aeschli** [comment]
We want to use a Node version that matches (as close as possible) the one that we get in the Electron version of the VSCode client.

For 1.36 we updated to Electron 4.2.3 using Node 10.11.

Updated version: microsoft/vscode@51e5a1985d2ac72f333a58381bbe36fdd8396d67

Verified that this fixes the example at https://github.com/microsoft/vscode-remote-release/issues/604#issuecomment-500162696

**Comment by baslr** [comment]
@roblourens @aeschli as I found out, the problem is ether

* tcg code
* compile bug in qemu
* v8 code
* compile bug in v8
* compiler code
* compile bug in compiler

because

In tcg environments `-cpu qemu64` and no -enable-kvm

```
$ node
> a = undefined 
undefined
> a >>> 0
4294967295
```
on the host:
```
$ node
> a = undefined
undefined
> a >>> 0
0
```

node on native hardware
```
node
Welcome to Node.js v12.4.0.
Type ".help" for more information.
> let buffer
undefined
> buffer |= 0
0
```
vm with tcg:
```
$ ./out/Release/node --version
v12.4.0
./out/Release/node -e "let buffer; buffer |= 0; console.log(buffer);"
-1
```
see also
https://bugs.launchpad.net/qemu/+bug/1832281
