### ISSUE TITLE
Support custom options for Docker CLI

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#6042]
@chrmarti The issue still happens for me on version 0.209.5. But only when using custom docker command with settings `remote.containers.dockerPath` as leaving it empty makes everything work

<details>
<summary>My trace logs</summary>
<pre>
  [78 ms] Remote-Containers 0.209.5 in VS Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e).
  [78 ms] Start: Run: wsl -d alpine -e wslpath -u \\wsl$\alpine\home\meskill\Projects\test\rust
  [162 ms] Stop (84 ms): Run: wsl -d alpine -e wslpath -u \\wsl$\alpine\home\meskill\Projects\test\rust
  [332 ms] Start: Resolving Remote
  [336 ms] Start: Run: wsl -d alpine -e wslpath -u \\wsl$\alpine\home\meskill\Projects\test\rust
  [418 ms] Stop (82 ms): Run: wsl -d alpine -e wslpath -u \\wsl$\alpine\home\meskill\Projects\test\rust
  [419 ms] Start: Run: wsl -d alpine -e /bin/sh -c cd '/home/meskill/Projects/test/rust' && /bin/sh
  [423 ms] Start: Run in host: id -un
  [460 ms] meskill
  [461 ms] 
  [461 ms] Stop (38 ms): Run in host: id -un
  [461 ms] Start: Run in host: cat /etc/passwd
  [463 ms] Stop (2 ms): Run in host: cat /etc/passwd
  [463 ms] Start: Run in host: echo ~
  [464 ms] /home/meskill
  [464 ms] 
  [464 ms] Stop (1 ms): Run in host: echo ~
  [465 ms] Start: Run in host: test -x '/home/meskill/.vscode-remote-containers/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/node'
  [465 ms] 
  [466 ms] 
  [466 ms] Stop (1 ms): Run in host: test -x '/home/meskill/.vscode-remote-containers/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/node'
  [466 ms] Start: Run in host: test -f '/home/meskill/.vscode-remote-containers/dist/vscode-remote-containers-server-0.209.5.js'
  [467 ms] 
  [467 ms] 
  [467 ms] Stop (1 ms): Run in host: test -f '/home/meskill/.vscode-remote-containers/dist/vscode-remote-containers-server-0.209.5.js'
  [469 ms] userEnvProbe: loginInteractiveShell (default)
  [469 ms] userEnvProbe shell: /usr/bin/fish
  [470 ms] Start: Run in Host: /usr/bin/fish -lic '/home/meskill/.vscode-remote-containers/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/node' -p '"1e040e07dbb41a0925b1f4f86c02604b" + JSON.stringify(process.env) + "1e040e07dbb41a0925b1f4f86c02604b"'
  [587 ms] Stop (117 ms): Run in Host: /usr/bin/fish -lic '/home/meskill/.vscode-remote-containers/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/node' -p '"1e040e07dbb41a0925b1f4f86c02604b" + JSON.stringify(process.env) + "1e040e07dbb41a0925b1f4f86c02604b"'
  [587 ms] 1e040e07dbb41a0925b1f4f86c02604b{"PWD":"/home/meskill/Projects/test/rust","SHLVL":"3","WSLENV":"","WSL_DISTRO_NAME":"alpine","SHELL":"/bin/sh","HOME":"/home/meskill","TERM":"xterm-256color","WSL_HOST_IP":"192.168.144.1","WSL_IP":"192.168.157.237","SELF_IP":"192.168.157.237","NAME":"Tower","REMOTE_CONTAINERS_IPC":"","HOSTTYPE":"x86_64","WSL_INTEROP":"/run/WSL/11638_interop","LOGNAME":"meskill","USER":"meskill","PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Users/meski/AppData/Local/Vivaldi/Application:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/system32/wbem:/mnt/c/windows/system32/windowspowershell/v1.0/:/mnt/c/windows/system32/openssh/:/mnt/c/programdata/chocolatey/bin:/mnt/c/program files/microsoft vs code/bin:/mnt/c/program files/nvidia corporation/nvidia ngx:/mnt/c/program files/microsoft vs code/bin:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/system32/wbem:/mnt/c/windows/system32/windowspowershell/v1.0/:/mnt/c/windows/system32/openssh/:/mnt/c/program files/dotnet/:/mnt/c/program files/microsoft vs code/bin:/mnt/c/program files/nvidia corporation/nvidia nvdlisr:/mnt/c/program files/microsoft vs code/bin:/mnt/c/program files (x86)/git:/mnt/c/program files (x86)/windows kits/10/windows performance toolkit/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Users/meski/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/meski/AppData/Roaming/Code/User/globalStorage/ms-vscode-remote.remote-containers/cli-bin","HOST_IP":"192.168.144.1","REMOTE_CONTAINERS_SOCKETS":"[]","LANG":"en_US.UTF-8","OLDPWD":"/mnt/c/Program Files/Microsoft VS Code"}1e040e07dbb41a0925b1f4f86c02604b
  [587 ms] 
  [588 ms] userEnvProbe parsed: {
    "PWD": "/home/meskill/Projects/test/rust",
    "SHLVL": "3",
    "WSLENV": "",
    "WSL_DISTRO_NAME": "alpine",
    "SHELL": "/bin/sh",
    "HOME": "/home/meskill",
    "TERM": "xterm-256color",
    "WSL_HOST_IP": "192.168.144.1",
    "WSL_IP": "192.168.157.237",
    "SELF_IP": "192.168.157.237",
    "NAME": "Tower",
    "REMOTE_CONTAINERS_IPC": "",
    "HOSTTYPE": "x86_64",
    "WSL_INTEROP": "/run/WSL/11638_interop",
    "LOGNAME": "meskill",
    "USER": "meskill",
    "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Users/meski/AppData/Local/Vivaldi/Application:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/system32/wbem:/mnt/c/windows/system32/windowspowershell/v1.0/:/mnt/c/windows/system32/openssh/:/mnt/c/programdata/chocolatey/bin:/mnt/c/program files/microsoft vs code/bin:/mnt/c/program files/nvidia corporation/nvidia ngx:/mnt/c/program files/microsoft vs code/bin:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/system32/wbem:/mnt/c/windows/system32/windowspowershell/v1.0/:/mnt/c/windows/system32/openssh/:/mnt/c/program files/dotnet/:/mnt/c/program files/microsoft vs code/bin:/mnt/c/program files/nvidia corporation/nvidia nvdlisr:/mnt/c/program files/microsoft vs code/bin:/mnt/c/program files (x86)/git:/mnt/c/program files (x86)/windows kits/10/windows performance toolkit/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Users/meski/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/meski/AppData/Roaming/Code/User/globalStorage/ms-vscode-remote.remote-containers/cli-bin",
    "HOST_IP": "192.168.144.1",
    "REMOTE_CONTAINERS_SOCKETS": "[]",
    "LANG": "en_US.UTF-8",
    "OLDPWD": "/mnt/c/Program Files/Microsoft VS Code"
  }
  [588 ms] userEnvProbe PATHs:
  Probe:     '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Users/meski/AppData/Local/Vivaldi/Application:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/system32/wbem:/mnt/c/windows/system32/windowspowershell/v1.0/:/mnt/c/windows/system32/openssh/:/mnt/c/programdata/chocolatey/bin:/mnt/c/program files/microsoft vs code/bin:/mnt/c/program files/nvidia corporation/nvidia ngx:/mnt/c/program files/microsoft vs code/bin:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/system32/wbem:/mnt/c/windows/system32/windowspowershell/v1.0/:/mnt/c/windows/system32/openssh/:/mnt/c/program files/dotnet/:/mnt/c/program files/microsoft vs code/bin:/mnt/c/program files/nvidia corporation/nvidia nvdlisr:/mnt/c/program files/microsoft vs code/bin:/mnt/c/program files (x86)/git:/mnt/c/program files (x86)/windows kits/10/windows performance toolkit/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Users/meski/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/meski/AppData/Roaming/Code/User/globalStorage/ms-vscode-remote.remote-containers/cli-bin'
  Container: None
  [589 ms] Setting up container for folder or workspace: /home/meskill/Projects/test/rust
  [590 ms] Start: Check Docker is running
  [591 ms] Start: Run in Host: fish -c 'docker $argv' version --format {{.Server.APIVersion}}
  [628 ms] Host server: (node:11645) UnhandledPromiseRejectionWarning: Error: spawn fish -c 'docker $argv' ENOENT
      at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
      at onErrorNT (internal/child_process.js:465:16)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
  (Use `node --trace-warnings ...` to show where the warning was created)
  (node:11645) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
  [628 ms] Host server: (node:11645) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  [628 ms] Stop (37 ms): Run in Host: fish -c 'docker $argv' version --format {{.Server.APIVersion}}
  [630 ms] spawn fish -c 'docker $argv' ENOENT
  [630 ms] Stop (40 ms): Check Docker is running
  [633 ms] Docker returned an error code ENOENT, message: spawn fish -c 'docker $argv' ENOENT
  [634 ms] Host server: (node:11645) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
  </pre>
</details>

_Originally posted by @meskill in https://github.com/microsoft/vscode-remote-release/issues/6026#issuecomment-991464663_

**Comment by chrmarti** [comment]
What kind of options are you passing with `$argv`?

**Comment by meskill** [comment]
@chrmarti I expect `$argv` will have arguments passed to docker

I'm using that custom command to pass call to the fish shell itself in order to make some initial setup for docker. 

Before it worked as expected and inside wsl2 this command is working similar to call of docker itself:
![image](https://user-images.githubusercontent.com/8974488/145796318-a0445540-8d83-48d2-b2df-53090dfdc758.png)

**Comment by chrmarti** [comment]
`$argv` was then passed with every call to `docker`. I'm wondering what specific arguments you passed that make sense with all `docker` commands we use. Could you explain?

**Comment by meskill** [comment]
It is basically just a redirect command to the fist itself.

And inside fish I have next function

```fish
function checkOrStartDocker
    pgrep dockerd &>/dev/null

    if test $status -ne 0
        sudo dockerd &>/dev/null &
        echo "Starting docker service..."
        sleep 3s
    end
end

function docker -w docker
    checkOrStartDocker

    command docker $argv
end
```

So no additional arguments, just wrapping docker command to run docker daemon in case it is not running

**Comment by meskill** [comment]
I'm not quite got the question.

It just worked before, as I understand Remote-Containers has been using sh inside wsl and as sh does not have functionality I need, I've just put instead of `docker` command other command which acts exactly as docker itself and caller shouldn't know that details as it is just a some command. But something has changed with the latest releases, and it acts differently.

If I use just `docker` it will work but only in case if `dockerd` is already running on wsl, but on previous versions I could do it automatically and start `dockerd` as soon as someone called `docker` command.

**Comment by chrmarti** [comment]
Ok, I think that might not work now because we no longer use `/bin/sh` to spawn the Docker CLI. We are now using a separate process in WSL that spawns the Docker CLI. You could change the Docker Path setting to `mydocker` and add a `mydocker` script that does the check for dockerd.

**Comment by meskill** [comment]
Thanks for the explanation I'll try to do as you've suggested.

The issue might be close I believe.

**Comment by chrmarti** [comment]
Great, thanks!
