### ISSUE TITLE
Command 'Remote-Containers: Reopen in Container' resulted in an error (Cannot read property 'endsWith' of undefined)

### ISSUE THREAD

**Issue by tanzle-aames** [microsoft/vscode-remote-release#6046]
- VSCode Version: 1.63.0
- Local OS Version: Ubuntu 20.04.3 LTS
- Remote OS Version: nvidia/cudagl:11.4.0-devel-ubuntu20.04
- Remote Extension/Connection Type: Docker
- Logs:

[115 ms] Remote-Containers 0.209.5 in VS Code 1.64.0-insider (065b450db9f555f177161748e8f2911ebb5677f9).
[115 ms] Start: Resolving Remote
[126 ms] Setting up container for folder or workspace: /home/myuser/myproject
[129 ms] Start: Check Docker is running
[130 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[181 ms] Server API version: 1.41
[196 ms] TypeError: Cannot read property 'endsWith' of undefined
 at K5 (/home/myuser/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.209.5/dist/extension/extension.js:416:13731)
 at Array.map (<anonymous>)
 at _h (/home/myuser/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.209.5/dist/extension/extension.js:416:13126)
 at qN (/home/myuser/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.209.5/dist/extension/extension.js:416:13079)
 at processTicksAndRejections (internal/process/task_queues.js:93:5)
 at async wC (/home/myuser/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.209.5/dist/extension/extension.js:416:12830)
 at async oi (/home/myuser/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.209.5/dist/extension/extension.js:416:12755)
 at async W5 (/home/myuser/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.209.5/dist/extension/extension.js:416:10471)

Steps to Reproduce:

1. This morning, automatic updates installed VS Code 1.63.0
2. Upon reopening in container, I get a popup error that says "Command 'Remote-Containers: Reopen in Container' resulted in an error (Cannot read property 'endsWith' of undefined)"
3. This project had been working with the same remote container for several months across several VS Code versions.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by tanzle-aames** [comment]
The same project and Docker container setup works fine with 1.64.0-insider build of VS Code.

**Comment by tanzle-aames** [comment]
After rolling back the "Remote - Containers" extension back to v0.205.2, I am able to resume working with this project without the error.

**Comment by chrmarti** [comment]
@tanzle-aames Could you post your project's `.git/config` file and the output of `git remote -v`? (If there is any non-public information involved it would help if you could remove it in a way that preserves the structure of the text. E.g., replace all characters with `x` and replace all numbers with `5`.)

**Comment by tanzle-aames** [comment]
The project is private source for the company I work for. Redacting would remove most of the text.

**Comment by chrmarti** [comment]
I can add a check to avoid the error.
