### ISSUE TITLE
Resolver fails on Windows if COMSPEC set to Take Command (tcc.exe)

### ISSUE THREAD

**Issue by jaltman** [microsoft/vscode-remote-release#6085]
Issue Type: <b>Bug</b>

Install Take Command from https://jpsoft.com/products/tcc-cmd-prompt.html

Execute TCC Command Prompt

At TCC command line, start "code"

Attempt to connect to a Linux server via SSH

The connection will fail with an error indicating that the Resolver was unable to determine the server port.

Remote-SSH attempts to execute a command of the form

  C:\windows\System32\cmd.exe /c (type "C:\Users\<user>\AppData\Local\Temp\vscode-linux-multi-line-command-<hostname>-401872090.sh" | ssh -T -D 54284 "<hostname>" bash) & exit /b 0

which fails with 

  bash: -c: line 1: syntax error near unexpected token `)'
  bash: -c: line 1: `bash)'

when COMSPEC is set to 

  C:\Program Files\JPSoft\TCMD28\TCC.EXE

instead of 

  C:\windows\system32\cmd.exe

I suggest overriding COMSPEC to before creating the shell.

Extension version: 0.70.0
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.15.7-200.fc35.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.63GB (41.38GB free)|
|Process Argv|--crash-reporter-id 69973ee4-a22c-4619-96f2-84008a605944|
|Screen Reader|no|
|VM|44%|

|Item|Value|
|---|---|
|Remote|SSH: fc35|
|OS|Linux x64 5.15.7-200.fc35.x86_64|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (3 x 2803)|
|Memory (System)|1.89GB (0.07GB free)|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30416614
py55gd98:30411514
vscexrecpromp3t3:30407764

```

</details>

**Comment by tanhakabir** [comment]
Would you please be able to send me the full logs from the Remote-SSH channel in the Output tab?

**Comment by jaltman** [comment]
`[13:37:17.458] Log Level: 2
[13:37:17.462] remote-ssh@0.70.0
[13:37:17.462] win32 x64
[13:37:17.473] SSH Resolver called for "ssh-remote+fc35.stags-leap.bayside.sara-jeff.nyc", attempt 1
[13:37:17.474] "remote.SSH.useLocalServer": false
[13:37:17.474] "remote.SSH.showLoginTerminal": false
[13:37:17.474] "remote.SSH.remotePlatform": {"fedora.bayside.sara-jeff.nyc":"linux","lamplighter.auristor.com":"linux","fc35.stags-leap.bayside.sara-jeff.nyc":"linux"}
[13:37:17.474] "remote.SSH.path": undefined
[13:37:17.474] "remote.SSH.configFile": undefined
[13:37:17.474] "remote.SSH.useFlock": true
[13:37:17.474] "remote.SSH.lockfilesInTmp": false
[13:37:17.475] "remote.SSH.localServerDownload": auto
[13:37:17.475] "remote.SSH.remoteServerListenOnSocket": false
[13:37:17.475] "remote.SSH.showLoginTerminal": false
[13:37:17.475] "remote.SSH.defaultExtensions": []
[13:37:17.475] "remote.SSH.loglevel": 2
[13:37:17.475] "remote.SSH.serverPickPortsFromRange": {}
[13:37:17.475] "remote.SSH.enableDynamicForwarding": true
[13:37:17.475] "remote.SSH.serverInstallPath": {}
[13:37:17.476] SSH Resolver called for host: fc35.stags-leap.bayside.sara-jeff.nyc
[13:37:17.476] Setting up SSH remote "fc35.stags-leap.bayside.sara-jeff.nyc"
[13:37:17.482] Using commit id "899d46d82c4c95423fb7e10e68eba52050e30ba3" and quality "stable" for server
[13:37:17.485] Install and start server if needed
[13:37:17.503] Checking ssh with "ssh -V"
[13:37:17.531] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[13:37:17.534] Running script with connection command: ssh -T -D 49831 "fc35.stags-leap.bayside.sara-jeff.nyc" bash
[13:37:17.537] Terminal shell path: C:\windows\System32\cmd.exe
[13:37:17.832] > ]0;C:\windows\System32\cmd.exe
[13:37:17.833] Got some output, clearing connection timeout
[13:37:18.311] > TCC: Unknown command "/c" type "C:\Users\jaltm\AppData\Local\Temp\vscode-linux-m
> ulti-line-command-fc35.stags-leap.bayside.sara-jeff.nyc-583810091.sh" ""        
[13:37:19.577] "install" terminal command done
[13:37:19.577] Install terminal quit with output: ulti-line-command-fc35.stags-leap.bayside.sara-jeff.nyc-583810091.sh" ""        
[13:37:19.577] Received install output: ulti-line-command-fc35.stags-leap.bayside.sara-jeff.nyc-583810091.sh" ""        
[13:37:19.578] Failed to parse remote port from server output
[13:37:19.579] Resolver error: Error: 
	at Function.Create (c:\Users\jaltm\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:430425)
	at Object.t.handleInstallOutput (c:\Users\jaltm\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:429068)
	at Object.t.tryInstall (c:\Users\jaltm\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:524212)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\jaltm\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:487216
	at async Object.t.withShowDetailsEvent (c:\Users\jaltm\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:490561)
	at async Object.t.resolve (c:\Users\jaltm\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:488295)
	at async c:\Users\jaltm\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:564197
[13:37:19.583] ------
`

**Comment by jaltman** [comment]
The problem still exists with VSCode 1.66.2.

**Comment by eleanorjboyd** [comment]
Hello, I'm Eleanor the new remote-SSH maintainer! A few questions as I review this issue: Can you confirm if this issue still exists on the most recent version of VS Code? Can you try running this connection command from a local terminal and let me know the output: `ssh -T -D 49831 "fc35.stags-leap.bayside.sara-jeff.nyc" bash`? Your local machine has TCC but your remote one has which shell type? 

Thanks!
