### ISSUE TITLE
Remote-SSH not working: "Could not establish connection to [host]"

### ISSUE THREAD

**Issue by nikijain17** [microsoft/vscode-remote-release#6088]
Remote-SSH stopped working. After I enter my password, it says "Could not establish connection to [host]"
I am able to connect to other computers. The issue is specific to this one.
I am using VSCode 1.63.2

Here are some of the things I have tried:
- Deleted the host info from the config file and re-setup remote SSH
- Ran command "Remote-SSH: Kill VS Code Server on Host"
- Ran command "Remote-SSH: Uninstall VS Code Server from Host"
- Deleted .vscode-server and all traces of vscode on the remote computer
- Uninstalled and reinstalled the Remote-SSH extension
- Uninstalled and reinstalled VSCode

Here is the log:
`[15:17:37.708] Showing password prompt
[15:17:40.718] Got password response
[15:17:40.719] "install" wrote data to terminal: "********"
[15:17:40.735] > 
[15:17:41.005] > 'powershell' is not recognized as an internal or external command,
> operable program or batch file.
[15:17:42.403] "install" terminal command done
[15:17:42.403] Install terminal quit with output: operable program or batch file.
[15:17:42.403] Received install output: operable program or batch file.
[15:17:42.404] Failed to parse remote port from server output
[15:17:42.405] Resolver error: Error: 
    at Function.Create (c:\Users\nikitaj\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:430425)
    at Object.t.handleInstallOutput (c:\Users\nikitaj\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:429068)
    at Object.t.tryInstall (c:\Users\nikitaj\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:524212)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async c:\Users\nikitaj\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:487216
    at async Object.t.withShowDetailsEvent (c:\Users\nikitaj\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:490561)
    at async Object.t.resolve (c:\Users\nikitaj\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:488295)
    at async c:\Users\nikitaj\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:564197
[15:17:42.407] ------`

**Comment by tanhakabir** [comment]
> `'powershell' is not recognized as an internal or external command,`

This indicates to me that we're struggling to resolve PowerShell on your remote machine. PowerShell has been on Windows since Windows XP. What version of remote are you running? Did you possibly delete PowerShell or change the path to PowerShell?

**Comment by nikijain17** [comment]
Sorry I didn't see this sooner, I never got a notification. That was the issue, thank you so much!
