### ISSUE TITLE
Error: certificate signature failure

### ISSUE THREAD

**Issue by rana94302** [microsoft/vscode-remote-release#6097]
- VSCode Version:1.63.2
- Local OS Version: Ubuntu 18.04
- Remote OS Version:
- Remote Extension/Connection Type: SSH/Docker/WSL
- Logs:
[2021-12-22T17:59:54.131Z] Stop (103 ms): Run in container: uname -m
[2021-12-22T17:59:54.131Z] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[2021-12-22T17:59:54.133Z] NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
[2021-12-22T17:59:54.134Z] 
[2021-12-22T17:59:54.134Z] Stop (3 ms): Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[2021-12-22T17:59:54.134Z] Start: Run in container: cat /etc/passwd
[2021-12-22T17:59:54.136Z] Stop (2 ms): Run in container: cat /etc/passwd
[2021-12-22T17:59:54.136Z] Start: Updating configuration state
[2021-12-22T17:59:54.144Z] Stop (8 ms): Updating configuration state
[2021-12-22T17:59:54.144Z] Start: Setup shutdown monitor
[2021-12-22T17:59:54.145Z] Forking shutdown monitor: /home/hvqy9t2/.vscode/extensions/ms-vscode-remote.remote-containers-0.209.6/dist/shutdown/shutdownMonitorProcess /run/user/1000/vscode-remote-containers-373cb294a0a82d3425425a8b727561208d3a6cc6.sock dockerCompose Debug /home/hvqy9t2/.config/Code/logs/20211222T114228/exthost1/ms-vscode-remote.remote-containers 1640195990539
[2021-12-22T17:59:54.150Z] Stop (6 ms): Setup shutdown monitor
[2021-12-22T17:59:54.150Z] Start: Run in container: test -d /home/vscode/.vscode-server
[2021-12-22T17:59:54.152Z] 
[2021-12-22T17:59:54.152Z] 
[2021-12-22T17:59:54.152Z] Exit code 1
[2021-12-22T17:59:54.153Z] Stop (3 ms): Run in container: test -d /home/vscode/.vscode-server
[2021-12-22T17:59:54.153Z] Start: Run in container: test -d /home/vscode/.vscode-remote
[2021-12-22T17:59:54.155Z] 
[2021-12-22T17:59:54.155Z] 
[2021-12-22T17:59:54.155Z] Exit code 1
[2021-12-22T17:59:54.155Z] Stop (2 ms): Run in container: test -d /home/vscode/.vscode-remote
[2021-12-22T17:59:54.155Z] Start: Run in container: test -f /var/vscode-server/.patchEtcEnvironmentMarker
[2021-12-22T17:59:54.156Z] 
[2021-12-22T17:59:54.156Z] 
[2021-12-22T17:59:54.156Z] Exit code 1
[2021-12-22T17:59:54.156Z] Stop (1 ms): Run in container: test -f /var/vscode-server/.patchEtcEnvironmentMarker
[2021-12-22T17:59:54.156Z] Start: Run in container: /bin/sh
[2021-12-22T17:59:54.160Z] Start: Run in container: test ! -f '/var/vscode-server/.patchEtcEnvironmentMarker' && set -o noclobber && mkdir -p '/var/vscode-server' && { > '/var/vscode-server/.patchEtcEnvironmentMarker' ; } 2> /dev/null
[2021-12-22T17:59:54.269Z] 
[2021-12-22T17:59:54.269Z] 
[2021-12-22T17:59:54.269Z] Stop (109 ms): Run in container: test ! -f '/var/vscode-server/.patchEtcEnvironmentMarker' && set -o noclobber && mkdir -p '/var/vscode-server' && { > '/var/vscode-server/.patchEtcEnvironmentMarker' ; } 2> /dev/null
[2021-12-22T17:59:54.269Z] Start: Run in container: cat >> /etc/environment <<'etcEnvrionmentEOF'
[2021-12-22T17:59:54.281Z] 
[2021-12-22T17:59:54.282Z] 
[2021-12-22T17:59:54.282Z] Stop (13 ms): Run in container: cat >> /etc/environment <<'etcEnvrionmentEOF'
[2021-12-22T17:59:54.282Z] Start: Run in container: test -f /var/vscode-server/.patchEtcProfileMarker
[2021-12-22T17:59:54.283Z] 
[2021-12-22T17:59:54.284Z] 
[2021-12-22T17:59:54.284Z] Exit code 1
[2021-12-22T17:59:54.284Z] Stop (2 ms): Run in container: test -f /var/vscode-server/.patchEtcProfileMarker
[2021-12-22T17:59:54.284Z] Start: Run in container: test ! -f '/var/vscode-server/.patchEtcProfileMarker' && set -o noclobber && mkdir -p '/var/vscode-server' && { > '/var/vscode-server/.patchEtcProfileMarker' ; } 2> /dev/null
[2021-12-22T17:59:54.287Z] 
[2021-12-22T17:59:54.287Z] 
[2021-12-22T17:59:54.287Z] Stop (3 ms): Run in container: test ! -f '/var/vscode-server/.patchEtcProfileMarker' && set -o noclobber && mkdir -p '/var/vscode-server' && { > '/var/vscode-server/.patchEtcProfileMarker' ; } 2> /dev/null
[2021-12-22T17:59:54.287Z] Start: Run in container: sed -i -E 's/((^|\s)PATH=)([^\$]*)$/\1${PATH:-\3}/g' /etc/profile || true
[2021-12-22T17:59:54.290Z] 
[2021-12-22T17:59:54.290Z] 
[2021-12-22T17:59:54.290Z] Stop (3 ms): Run in container: sed -i -E 's/((^|\s)PATH=)([^\$]*)$/\1${PATH:-\3}/g' /etc/profile || true
[2021-12-22T17:59:54.290Z] Start: Run in container: test ! -f '/home/vscode/.vscode-server/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/home/vscode/.vscode-server/data/Machine' && { > '/home/vscode/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[2021-12-22T17:59:54.294Z] 
[2021-12-22T17:59:54.294Z] 
[2021-12-22T17:59:54.294Z] Stop (4 ms): Run in container: test ! -f '/home/vscode/.vscode-server/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/home/vscode/.vscode-server/data/Machine' && { > '/home/vscode/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[2021-12-22T17:59:54.294Z] Start: Run in container: mkdir -p '/home/vscode/.vscode-server/data/Machine' && cat >'/home/vscode/.vscode-server/data/Machine/settings.json' <<'settingsJSON'
[2021-12-22T17:59:54.298Z] 
[2021-12-22T17:59:54.299Z] 
[2021-12-22T17:59:54.299Z] Stop (5 ms): Run in container: mkdir -p '/home/vscode/.vscode-server/data/Machine' && cat >'/home/vscode/.vscode-server/data/Machine/settings.json' <<'settingsJSON'
[2021-12-22T17:59:54.299Z] Start: Run in container: test -d /home/vscode/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3
[2021-12-22T17:59:54.300Z] 
[2021-12-22T17:59:54.300Z] 
[2021-12-22T17:59:54.300Z] Exit code 1
[2021-12-22T17:59:54.300Z] Stop (1 ms): Run in container: test -d /home/vscode/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3
[2021-12-22T17:59:54.300Z] Installing VS Code Server for commit 899d46d82c4c95423fb7e10e68eba52050e30ba3
[2021-12-22T17:59:54.301Z] Start: Downloading VS Code Server
[2021-12-22T17:59:54.301Z] 899d46d82c4c95423fb7e10e68eba52050e30ba3 linux-x64 stable 
[2021-12-22T18:00:16.339Z] Stop (22038 ms): Downloading VS Code Server
[2021-12-22T18:00:16.346Z] Error: connect ECONNREFUSED 165.225.120.44:10364
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Steps to Reproduce:

1. Click on reopen in container
2. getting below error:
[3200 ms] Exit code 1
[3200 ms] Installing VS Code Server for commit 899d46d82c4c95423fb7e10e68eba52050e30ba3
[3201 ms] Start: Downloading VS Code Server
[3201 ms] 899d46d82c4c95423fb7e10e68eba52050e30ba3 linux-x64 stable 
[8423 ms] Error: certificate signature failure
 at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
 at TLSSocket.emit (events.js:315:20)
 at TLSSocket._finishInit (_tls_wrap.js:932:8)
 at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by chrmarti** [comment]
Are you behind a network proxy?
