### ISSUE TITLE
Failed to parse remote port from server output Linux -> Win 11

### ISSUE THREAD

**Issue by nickblock** [microsoft/vscode-remote-release#6101]
Sorry i know there are a lot of these but i cannot find solution.

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:39:46.686Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.14.18-100.fc33.x86_64

Remote Machine: win 11, OpenSSH

Remoting into win 11. Used to work with win 10. I am using pubkey auth, which works in terminal.

I have tried removing .vscode and .vscode-server from the windows machine, and restarted, I am usre there are no other agents running. This is my output, the suspicous part says "child died" for no reason, i don't see this when accessing via terminal. I removed domain name and ip from output, but they look correct, unique port.

[10:49:04.063] Log Level: 2
[10:49:04.064] remote-ssh@0.70.0
[10:49:04.065] linux x64
[10:49:04.066] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a224379626572706f77657257696e227d", attempt 1
[10:49:04.066] "remote.SSH.useLocalServer": true
[10:49:04.066] "remote.SSH.path": undefined
[10:49:04.066] "remote.SSH.configFile": undefined
[10:49:04.067] "remote.SSH.useFlock": true
[10:49:04.067] "remote.SSH.lockfilesInTmp": false
[10:49:04.067] "remote.SSH.localServerDownload": auto
[10:49:04.067] "remote.SSH.remoteServerListenOnSocket": false
[10:49:04.067] "remote.SSH.showLoginTerminal": true
[10:49:04.068] "remote.SSH.defaultExtensions": []
[10:49:04.068] "remote.SSH.loglevel": 2
[10:49:04.068] "remote.SSH.serverPickPortsFromRange": {}
[10:49:04.068] "remote.SSH.enableDynamicForwarding": true
[10:49:04.069] "remote.SSH.serverInstallPath": {}
[10:49:04.069] SSH Resolver called for host: CyberpowerWin
[10:49:04.069] Setting up SSH remote "CyberpowerWin"
[10:49:04.073] Acquiring local install lock: /tmp/vscode-remote-ssh-46a3bcc3-install.lock
[10:49:04.081] Looking for existing server data file at /home/nick/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-46a3bcc3-899d46d82c4c95423fb7e10e68eba52050e30ba3-0.70.0/data.json
[10:49:04.082] Using commit id "899d46d82c4c95423fb7e10e68eba52050e30ba3" and quality "stable" for server
[10:49:04.087] Install and start server if needed
[10:49:04.094] PATH: /home/nick/.nvm/versions/node/v10.18.1/bin:/usr/lib64/ccache:/home/nick/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/var/lib/snapd/snap/bin:/home/nick/.local/bin:/home/nick/Android/Sdk/platform-tools/:/home/nick/NVPACK/android-sdk-linux/tools:/home/nick/NVPACK/android-sdk-linux/platform-tools:/home/nick/NVPACK/android-sdk-linux/build-tools:/home/nick/NVPACK/android-sdk-linux/extras/android/support:/home/nick/NVPACK/android-ndk-r14b:/home/nick/NVPACK/apache-ant-1.8.2/bin:/home/nick/NVPACK/gradle-2.9/bin
[10:49:04.095] Checking ssh with "ssh -V"
[10:49:04.104] > OpenSSH_8.4p1, OpenSSL 1.1.1l  FIPS 24 Aug 2021

[10:49:04.109] askpass server listening on /run/user/1000/vscode-ssh-askpass-95ee1dfb86dae4605ab7e1156adfc954a4e88824.sock
[10:49:04.109] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-2629ef2022a4a68902eec478b0cc170d3c5c4f1b.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","39271","-o","ConnectTimeout=15","CyberpowerWin"],"dataFilePath":"/home/nick/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-46a3bcc3-899d46d82c4c95423fb7e10e68eba52050e30ba3-0.70.0/data.json"}
[10:49:04.110] Local server env: {"DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/nick/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/nick/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-95ee1dfb86dae4605ab7e1156adfc954a4e88824.sock"}
[10:49:04.115] Spawned 9705
[10:49:04.217] > local-server-1> Spawned ssh, pid=9713
[10:49:04.219] stderr> OpenSSH_8.4p1, OpenSSL 1.1.1l  FIPS 24 Aug 2021
[10:49:04.386] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:HwTP1eN4AGLEORh8YsOedTkGbjygm5L4E0FFNob1Jzc
[10:49:04.481] stderr> Authenticated to servername.co.uk ([XXX.XXX.XXX.XXX]:2349).
[10:49:05.442] stderr> client_loop: send disconnect: Broken pipe
[10:49:05.446] > local-server-1> ssh child died, shutting down
[10:49:05.458] Local server exit: 0
[10:49:05.460] Received install output: local-server-1> Spawned ssh, pid=9713
OpenSSH_8.4p1, OpenSSL 1.1.1l  FIPS 24 Aug 2021
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:HwTP1eN4AGLEORh8YsOedTkGbjygm5L4E0FFNob1Jzc
Authenticated to servername.co.uk ([XXX.XXX.XXX.XXX]:2349).
client_loop: send disconnect: Broken pipe
local-server-1> ssh child died, shutting down

[10:49:05.463] Failed to parse remote port from server output
[10:49:05.467] Resolver error: Error: 
	at Function.Create (/home/nick/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:430425)
	at Object.t.handleInstallOutput (/home/nick/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:429068)
	at Object.e [as tryInstallWithLocalServer] (/home/nick/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:469079)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/nick/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:486771
	at async Object.t.withShowDetailsEvent (/home/nick/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:490561)
	at async /home/nick/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:467603
	at async E (/home/nick/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:464111)
	at async Object.t.resolveWithLocalServer (/home/nick/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:467218)
	at async Object.t.resolve (/home/nick/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:488171)
	at async /home/nick/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:564197
[10:49:05.480] ------

any help, debugging advice much appreciated.

**Comment by nickblock** [comment]
seemed to get it working with useLocalServer: false just once, and it now works without that setting.
