### ISSUE TITLE
Resolver error: Error: The VS Code Server failed to start

### ISSUE THREAD

**Issue by PythonOrC** [microsoft/vscode-remote-release#6107]
- VSCode Version: 1.63.2
- Local OS Version: Window 11 Pro 21H2 build 22000.376
- Remote OS Version: ubuntu 20.04.3 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. connect to remote host via ssh 
2. select the remote host
3. enter password
4. error appears after waiting a bit

I've tried the Remote-SSH Kill method but it didn't work for me. 
The command I initially used to add the remote host to vscode is `ssh ubuntu@192.168.101.8`
Log:
```
[10:50:09.204] Log Level: 2
[10:50:09.207] remote-ssh@0.70.0
[10:50:09.207] win32 x64
[10:50:09.208] SSH Resolver called for "ssh-remote+192.168.101.8", attempt 1
[10:50:09.208] "remote.SSH.useLocalServer": false
[10:50:09.208] "remote.SSH.showLoginTerminal": false
[10:50:09.209] "remote.SSH.remotePlatform": {"168.62.5.10":"linux","104.40.54.28":"linux","40.114.38.158":"linux","168.61.46.124":"linux","104.41.136.218":"linux","192.168.101.8":"linux","20.119.56.104":"linux"}
[10:50:09.209] "remote.SSH.path": undefined
[10:50:09.209] "remote.SSH.configFile": undefined
[10:50:09.209] "remote.SSH.useFlock": true
[10:50:09.209] "remote.SSH.lockfilesInTmp": false
[10:50:09.209] "remote.SSH.localServerDownload": auto
[10:50:09.210] "remote.SSH.remoteServerListenOnSocket": false
[10:50:09.210] "remote.SSH.showLoginTerminal": false
[10:50:09.210] "remote.SSH.defaultExtensions": []
[10:50:09.210] "remote.SSH.loglevel": 2
[10:50:09.210] "remote.SSH.serverPickPortsFromRange": {}
[10:50:09.210] "remote.SSH.enableDynamicForwarding": true
[10:50:09.210] "remote.SSH.serverInstallPath": {}
[10:50:09.211] SSH Resolver called for host: 192.168.101.8
[10:50:09.211] Setting up SSH remote "192.168.101.8"
[10:50:09.226] Using commit id "899d46d82c4c95423fb7e10e68eba52050e30ba3" and quality "stable" for server
[10:50:09.229] Install and start server if needed
[10:50:09.232] Checking ssh with "ssh -V"
[10:50:09.352] > OpenSSH_for_Windows_8.1p1, 
[10:50:09.353] > LibreSSL 3.0.2

[10:50:09.356] Running script with connection command: ssh -T -D 16627 "192.168.101.8" bash
[10:50:09.359] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:50:09.563] > ]0;C:\WINDOWS\System32\cmd.exe
[10:50:09.563] Got some output, clearing connection timeout
[10:50:09.638] > ubuntu@192.168.101.8's password: 
[10:50:09.639] Showing password prompt
[10:50:13.402] Got password response
[10:50:13.402] "install" wrote data to terminal: "********"
[10:50:13.416] > 
[10:50:14.805] > e2feb1ce51ff: running
[10:50:14.905] > Acquiring lock on /home/ubuntu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/vscode-remote-lock.ubuntu.899d46d82c4c95423fb7e10e68eba52050e30ba3
[10:50:14.941] > Installing to /home/ubuntu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3...
[10:50:14.954] > e2feb1ce51ff%%1%%
[10:50:14.969] > Downloading with wget
[10:50:18.375] > Download complete
[10:50:18.406] > e2feb1ce51ff%%2%%
> tar --version:
> tar (GNU tar) 1.30
> Copyright (C) 2017 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.Written by John Gilmore and Jay Fenlason.
> 
[10:50:37.896] > Checking /home/ubuntu/.vscode-server/.899d46d82c4c95423fb7e10e68eba52050e30ba3.log and /home/ubuntu/.vscode-server/.899d46d82c4c95423fb7e10e68eba52050e30ba3.pid for a running server
[10:50:37.923] > Looking for server with pid: 6875
[10:50:37.944] > Starting server with command... /home/ubuntu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/server.sh --start-server --host=127.0.0.1 --enable-remote-auto-shutdown --port=0    &> "/home/ubuntu/.vscode-server/.899d46d82c4c95423fb7e10e68eba52050e30ba3.log" < /dev/null
> printenv:
>     SHELL=/bin/bash
>     PWD=/home/ubuntu
>     LOGNAME=ubuntu
[10:50:37.946] > 
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/home/ubuntu
>     LANG=C.UTF-8
>     VSCODE_AGENT_FOLDER=/home/ubuntu/.vscode-server
>     SSH_CONNECTION=192.168.101.49 16629 192.168.101.8 22
>     XDG_SESSION_CLASS=user
>     USER=ubuntu
>     SHLVL=0
>     XDG_SESSION_ID=13
>     XDG_RUNTIME_DIR=/run/user/1000
>     SSH_CLIENT=192.168.101.49 16629 22
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
> s:/usr/local/games:/snap/bin
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
>     OLDPWD=/home/ubuntu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30
> 0ba3
>     _=/usr/bin/printenv
[10:50:37.953] > 
[10:50:37.971] > Spawned remote server: 7965
[10:50:37.983] > Waiting for server log...
[10:50:38.034] > Waiting for server log...
[10:50:38.083] > Waiting for server log...
[10:50:38.137] > Waiting for server log...
[10:50:38.187] > Waiting for server log...
[10:50:38.237] > Waiting for server log...
[10:50:38.288] > Waiting for server log...
[10:50:38.339] > Waiting for server log...
[10:50:38.389] > Waiting for server log...
[10:50:38.441] > Waiting for server log...
[10:50:38.490] > Waiting for server log...
[10:50:38.540] > Waiting for server log...
[10:50:38.593] > Waiting for server log...
[10:50:38.643] > Waiting for server log...
[10:50:38.695] > Waiting for server log...
[10:50:38.763] > Waiting for server log...
[10:50:38.797] > Waiting for server log...
[10:50:38.847] > Waiting for server log...
[10:50:38.902] > Waiting for server log...
[10:50:38.953] > Waiting for server log...
[10:50:39.002] > Waiting for server log...
[10:50:39.054] > Waiting for server log...
[10:50:39.107] > Waiting for server log...
[10:50:39.159] > Waiting for server log...
[10:50:39.210] > Waiting for server log...
[10:50:39.260] > Waiting for server log...
[10:50:39.310] > Waiting for server log...
[10:50:39.363] > Waiting for server log...
[10:50:39.411] > Waiting for server log...
[10:50:39.461] > Waiting for server log...
[10:50:39.512] > Waiting for server log...
[10:50:39.563] > Waiting for server log...
[10:50:39.613] > Waiting for server log...
[10:50:39.660] > Waiting for server log...
[10:50:39.713] > Waiting for server log...
[10:50:39.762] > Waiting for server log...
[10:50:39.811] > Waiting for server log...
[10:50:39.865] > Waiting for server log...
[10:50:39.911] > Waiting for server log...
[10:50:39.965] > Waiting for server log...
[10:50:40.015] > Waiting for server log...
[10:50:40.065] > Waiting for server log...
[10:50:40.114] > Waiting for server log...
[10:50:40.170] > Waiting for server log...
[10:50:40.221] > Waiting for server log...
[10:50:40.272] > Waiting for server log...
[10:50:40.324] > Waiting for server log...
[10:50:40.380] > Waiting for server log...
[10:50:40.424] > Waiting for server log...
[10:50:40.475] > Waiting for server log...
[10:50:40.525] > Waiting for server log...
[10:50:40.576] > Waiting for server log...
[10:50:40.629] > Waiting for server log...
[10:50:40.678] > Waiting for server log...
[10:50:40.729] > Waiting for server log...
[10:50:40.779] > Waiting for server log...
[10:50:40.831] > Waiting for server log...
[10:50:40.882] > Waiting for server log...
[10:50:40.933] > Waiting for server log...
[10:50:40.983] > Waiting for server log...
[10:50:41.034] > Waiting for server log...
[10:50:41.084] > Waiting for server log...
[10:50:41.134] > Waiting for server log...
[10:50:41.185] > Waiting for server log...
[10:50:41.236] > Waiting for server log...
[10:50:41.286] > Waiting for server log...
[10:50:41.337] > Waiting for server log...
[10:50:41.388] > Waiting for server log...
[10:50:41.440] > Waiting for server log...
[10:50:41.490] > Waiting for server log...
[10:50:41.540] > Waiting for server log...
[10:50:41.591] > Waiting for server log...
[10:50:41.645] > Waiting for server log...
[10:50:41.696] > Waiting for server log...
[10:50:41.747] > Waiting for server log...
[10:50:41.798] > Waiting for server log...
[10:50:41.850] > Waiting for server log...
[10:50:41.902] > Waiting for server log...
[10:50:41.950] > Waiting for server log...
[10:50:42.004] > Waiting for server log...
[10:50:42.053] > Waiting for server log...
[10:50:42.102] > Waiting for server log...
[10:50:42.156] > Waiting for server log...
[10:50:42.204] > Waiting for server log...
[10:50:42.257] > Waiting for server log...
[10:50:42.310] > Waiting for server log...
[10:50:42.361] > Waiting for server log...
[10:50:42.411] > Waiting for server log...
[10:50:42.461] > Waiting for server log...
[10:50:42.512] > Waiting for server log...
[10:50:42.563] > Waiting for server log...
[10:50:42.617] > Waiting for server log...
[10:50:42.669] > Waiting for server log...
[10:50:42.721] > Waiting for server log...
[10:50:42.771] > Waiting for server log...
[10:50:42.822] > Waiting for server log...
[10:50:42.872] > Waiting for server log...
[10:50:42.923] > Waiting for server log...
[10:50:42.976] > Waiting for server log...
[10:50:43.028] > Waiting for server log...
[10:50:43.077] > Waiting for server log...
[10:50:43.127] > Waiting for server log...
[10:50:43.179] > Waiting for server log...
[10:50:43.230] > Waiting for server log...
[10:50:43.280] > Waiting for server log...
[10:50:43.331] > Waiting for server log...
[10:50:43.382] > Waiting for server log...
[10:50:43.432] > Waiting for server log...
[10:50:43.484] > Waiting for server log...
[10:50:43.549] > Waiting for server log...
[10:50:43.585] > Waiting for server log...
[10:50:43.636] > Waiting for server log...
[10:50:43.688] > Waiting for server log...
[10:50:43.741] > Waiting for server log...
[10:50:43.793] > Waiting for server log...
[10:50:43.843] > Waiting for server log...
[10:50:43.897] > Waiting for server log...
[10:50:43.949] > Waiting for server log...
[10:50:44.000] > Waiting for server log...
[10:50:44.053] > Waiting for server log...
[10:50:44.104] > Waiting for server log...
[10:50:44.155] > Waiting for server log...
[10:50:44.207] > Waiting for server log...
[10:50:44.257] > Waiting for server log...
[10:50:44.308] > Waiting for server log...
[10:50:44.362] > Waiting for server log...
[10:50:44.415] > Waiting for server log...
[10:50:44.464] > Waiting for server log...
[10:50:44.515] > Waiting for server log...
[10:50:44.565] > Waiting for server log...
[10:50:44.615] > Waiting for server log...
[10:50:44.666] > Waiting for server log...
[10:50:44.717] > Waiting for server log...
[10:50:44.767] > Waiting for server log...
[10:50:44.819] > Waiting for server log...
[10:50:44.869] > Waiting for server log...
[10:50:44.921] > Waiting for server log...
[10:50:44.971] > Waiting for server log...
[10:50:45.023] > Waiting for server log...
[10:50:45.073] > Waiting for server log...
[10:50:45.123] > Waiting for server log...
[10:50:45.178] > Waiting for server log...
[10:50:45.228] > Waiting for server log...
[10:50:45.282] > Waiting for server log...
[10:50:45.332] > Waiting for server log...
[10:50:45.383] > Waiting for server log...
[10:50:45.435] > Waiting for server log...
[10:50:45.487] > Waiting for server log...
[10:50:45.537] > Waiting for server log...
[10:50:45.587] > Waiting for server log...
[10:50:45.639] > Waiting for server log...
[10:50:45.690] > Waiting for server log...
[10:50:45.742] > Waiting for server log...
[10:50:45.792] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,  
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
[10:50:45.815] > 
> Server did not start successfully. Full server log at /home/ubuntu/.vscode-serve
> er/.899d46d82c4c95423fb7e10e68eba52050e30ba3.log >>>
[10:50:45.823] > 
> /home/ubuntu/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/node: e
> error while loading shared libraries: libatomic.so.1: cannot open shared object f
> file: No such file or directory
> <<< End of server log
> e2feb1ce51ff: start
> exitCode==32==
> listeningOn====
> osReleaseId==ubuntu==
> arch==armv7l==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult==success==
> didLocalDownload==0==
> downloadTime==3435==
> installTime==16321==
> extInstallTime====
> serverStartTime==7835==
> e2feb1ce51ff: end
[10:50:45.823] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==ubuntu==
arch==armv7l==
tmpDir==/run/user/1000==
platform==linux==
unpackResult==success==
didLocalDownload==0==
downloadTime==3435==
installTime==16321==
extInstallTime====
serverStartTime==7835==

[10:50:45.824] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (c:\Users\Ethan\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:430359)
	at u (c:\Users\Ethan\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:424682)
	at Object.t.handleInstallOutput (c:\Users\Ethan\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:429101)
	at Object.t.tryInstall (c:\Users\Ethan\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:524212)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\Ethan\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:487216
	at async Object.t.withShowDetailsEvent (c:\Users\Ethan\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:490561)
	at async Object.t.resolve (c:\Users\Ethan\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:488295)
	at async c:\Users\Ethan\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:564197
[10:50:45.827] ------




[10:50:46.326] > 
[10:50:47.120] "install" terminal command done
[10:50:47.120] Install terminal quit with output: 
```
(the log ended without output)

**Comment by waltoncade** [comment]
I am having this exact same issue when trying to access remote linux machines from a windows 10 host.

**Comment by tanhakabir** [comment]
Hm do your remotes meet these prerequisites? https://code.visualstudio.com/docs/remote/linux#_remote-host-container-wsl-linux-prerequisites

`...node: not found` in your logs indicates to me that some dependency is missing from your remote system.
