### ISSUE TITLE
Throw error when RemoteCommand crashes SSH remote connection process on terminating commands

### ISSUE THREAD

**Issue by markusdd** [microsoft/vscode-remote-release#6108]
This relates to ticket #4474 

- VSCode Version: 1.63.2
- SSH Remote extension latest preview (v0.71.2021121615 Pre-Release)
- Local OS Version: Fedora 35
- Remote OS Version: CentOS 7.9
- Remote Extension/Connection Type: SSH
- Logs:

```
[13:32:05.942] Log Level: 2
[13:32:05.944] remote-ssh@0.71.2021121615
[13:32:05.944] linux x64
[13:32:05.957] SSH Resolver called for "ssh-remote+slpcomp4-icd-capri", attempt 1
[13:32:05.957] "remote.SSH.useLocalServer": true
[13:32:05.958] "remote.SSH.path": undefined
[13:32:05.958] "remote.SSH.configFile": undefined
[13:32:05.958] "remote.SSH.useFlock": true
[13:32:05.958] "remote.SSH.lockfilesInTmp": false
[13:32:05.958] "remote.SSH.localServerDownload": auto
[13:32:05.958] "remote.SSH.remoteServerListenOnSocket": false
[13:32:05.959] "remote.SSH.showLoginTerminal": false
[13:32:05.959] "remote.SSH.defaultExtensions": []
[13:32:05.959] "remote.SSH.loglevel": 2
[13:32:05.959] "remote.SSH.enableDynamicForwarding": true
[13:32:05.959] "remote.SSH.enableRemoteCommand": true
[13:32:05.959] "remote.SSH.serverPickPortsFromRange": {}
[13:32:05.959] "remote.SSH.serverInstallPath": {}
[13:32:05.961] SSH Resolver called for host: slpcomp4-icd-capri
[13:32:05.961] Setting up SSH remote "slpcomp4-icd-capri"
[13:32:05.963] Acquiring local install lock: /tmp/vscode-remote-ssh-b9ba25da-install.lock
[13:32:05.977] Looking for existing server data file at /home/mkrause/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-b9ba25da-899d46d82c4c95423fb7e10e68eba52050e30ba3-0.71.2021121615/data.json
[13:32:05.977] Using commit id "899d46d82c4c95423fb7e10e68eba52050e30ba3" and quality "stable" for server
[13:32:05.980] Install and start server if needed
[13:32:05.982] PATH: /usr/lib64/qt-3.3/bin:/opt/opensource/environment-modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/opt/scripts:/opt/scripts:/opt/puppetlabs/bin:/home/mkrause/bin:/home/mkrause/.local/bin:/home/mkrause/bin:/opt/scripts:/opt/scripts:/home/mkrause/bin:/home/mkrause/.local/bin:/home/mkrause/bin
[13:32:05.982] Checking ssh with "ssh -V"
[13:32:05.990] > OpenSSH_8.7p1, OpenSSL 1.1.1l  FIPS 24 Aug 2021

[13:32:05.994] askpass server listening on /run/user/853001119/vscode-ssh-askpass-aabc434c7ae80ea2149310765f47514951415497.sock
[13:32:05.994] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/853001119/vscode-ssh-askpass-86b20c5a1db66fae7359c710b592af6c5e574976.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","45167","-o","ConnectTimeout=15","slpcomp4-icd-capri"],"dataFilePath":"/home/mkrause/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-b9ba25da-899d46d82c4c95423fb7e10e68eba52050e30ba3-0.71.2021121615/data.json"}
[13:32:05.994] Local server env: {"DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/mkrause/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/mkrause/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/853001119/vscode-ssh-askpass-aabc434c7ae80ea2149310765f47514951415497.sock"}
[13:32:05.998] Spawned 182409
[13:32:06.102] > local-server-1> Spawned ssh, pid=182417
[13:32:06.104] stderr> OpenSSH_8.7p1, OpenSSL 1.1.1l  FIPS 24 Aug 2021
[13:32:06.377] stderr> debug1: Server host key: ssh-ed25519 SHA256:fT4hQQk4IgtxcydSEKBdOUlmvxwMITC69oCg+YXS/cI
[13:32:06.806] stderr> Ticket expired
[13:32:06.806] stderr> 
[13:32:06.806] stderr> 
[13:32:07.056] stderr> Authenticated to slpcomp4 (via proxy) using "publickey".
[13:32:08.113] stderr> Transferred: sent 3104, received 2816 bytes, in 1.1 seconds
[13:32:08.113] stderr> Bytes per second: sent 2938.9, received 2666.2
[13:32:08.113] > HELLLOOOOOOO
> local-server-1> ssh child died, shutting down
[13:32:08.118] Local server exit: 0
[13:32:08.118] Received install output: local-server-1> Spawned ssh, pid=182417
OpenSSH_8.7p1, OpenSSL 1.1.1l  FIPS 24 Aug 2021
debug1: Server host key: ssh-ed25519 SHA256:fT4hQQk4IgtxcydSEKBdOUlmvxwMITC69oCg+YXS/cI
Ticket expired


Authenticated to slpcomp4 (via proxy) using "publickey".
Transferred: sent 3104, received 2816 bytes, in 1.1 seconds
Bytes per second: sent 2938.9, received 2666.2
HELLLOOOOOOO
local-server-1> ssh child died, shutting down

[13:32:08.119] Failed to parse remote port from server output
[13:32:08.119] Resolver error: Error: 
	at Function.Create (/home/mkrause/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:431103)
	at Object.t.handleInstallOutput (/home/mkrause/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:429755)
	at Object.e [as tryInstallWithLocalServer] (/home/mkrause/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:469838)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/mkrause/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:487415
	at async Object.t.withShowDetailsEvent (/home/mkrause/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:491162)
	at async /home/mkrause/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:468281
	at async E (/home/mkrause/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:464789)
	at async Object.t.resolveWithLocalServer (/home/mkrause/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:467896)
	at async Object.t.resolve (/home/mkrause/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:488772)
	at async /home/mkrause/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:565038
[13:32:08.123] ------
```

Steps to Reproduce:
1. configure a remote location like this and try to connect
![image](https://user-images.githubusercontent.com/25175069/147567205-9c6e3a3b-8110-4492-84ef-dd2aed878711.png)

2. above issue occurs. The RemoteCommand is honored and executed, but the connection process crashes for an unknown reason.

It does not matter which remotecommand I use, it always crashes the server.

**Comment by tanhakabir** [comment]
Just to be sure this only happens if you have a RemoteCommand. Are you able to connect normally if you have no RemoteCommand but `enableRemoteCommand` and `useLocalServer` set to true?

**Comment by tanhakabir** [comment]
Thanks for filing an issue on this experimental setting! It helps me a ton to sort out any potential concerns before making enabled RemoteCommands a default setting

**Comment by memco** [comment]
I am having the same issue and I was able to test having remote.ssh.enableRemoteCommand set to true but not having a remote command configured for the connection works but when I add a remoteCommand to the connection config then the VSCode ssh connection fails.

**Comment by tanhakabir** [comment]
@memco could I see your logs as well? Also this information:

```
- VSCode Version:
- Local OS Version:
- Remote OS Version:
```

**Comment by memco** [comment]
VSCode version: 1.63.2
Local OS: Mac OS 10.15.7
Remote OS  CentOS 7.5.1804

```
09:40:40.949] Log Level: 2
[09:40:40.951] remote-ssh@0.71.2021121615
[09:40:40.951] darwin x64
[09:40:40.952] SSH Resolver called for "ssh-remote+remoteserver", attempt 1
[09:40:40.952] "remote.SSH.useLocalServer": true
[09:40:40.953] "remote.SSH.path": undefined
[09:40:40.953] "remote.SSH.configFile": undefined
[09:40:40.953] "remote.SSH.useFlock": true
[09:40:40.953] "remote.SSH.lockfilesInTmp": false
[09:40:40.953] "remote.SSH.localServerDownload": auto
[09:40:40.953] "remote.SSH.remoteServerListenOnSocket": false
[09:40:40.954] "remote.SSH.showLoginTerminal": false
[09:40:40.954] "remote.SSH.defaultExtensions": []
[09:40:40.954] "remote.SSH.loglevel": 2
[09:40:40.954] "remote.SSH.enableDynamicForwarding": true
[09:40:40.954] "remote.SSH.enableRemoteCommand": true
[09:40:40.954] "remote.SSH.serverPickPortsFromRange": {}
[09:40:40.955] "remote.SSH.serverInstallPath": {}
[09:40:40.956] SSH Resolver called for host: remoteserver
[09:40:40.956] Setting up SSH remote "remoteserver"
[09:40:40.958] Acquiring local install lock: /var/folders/y2/4100qtpd5bxd66vmqbrz9s_m0000gn/T/vscode-remote-ssh-371a34ed-install.lock
[09:40:40.959] Looking for existing server data file at /Users/user/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-371a34ed-899d46d82c4c95423fb7e10e68eba52050e30ba3-0.71.2021121615/data.json
[09:40:40.960] Using commit id "899d46d82c4c95423fb7e10e68eba52050e30ba3" and quality "stable" for server
[09:40:40.962] Install and start server if needed
[09:40:40.975] PATH: /Users/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
[09:40:40.975] Checking ssh with "ssh -V"
[09:40:40.986] > OpenSSH_8.1p1, LibreSSL 2.7.3

[09:40:41.005] askpass server listening on /var/folders/y2/4100qtpd5bxd66vmqbrz9s_m0000gn/T/vscode-ssh-askpass-b411a6758483f0aabe1d256a6b2d08386d178554.sock
[09:40:41.007] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/y2/4100qtpd5bxd66vmqbrz9s_m0000gn/T/vscode-ssh-askpass-a0a0b984b546e31c93d76cad79e521f3495858ad.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","53732","remoteserver"],"dataFilePath":"/Users/user/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-371a34ed-899d46d82c4c95423fb7e10e68eba52050e30ba3-0.71.2021121615/data.json"}
[09:40:41.007] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/y2/4100qtpd5bxd66vmqbrz9s_m0000gn/T/vscode-ssh-askpass-b411a6758483f0aabe1d256a6b2d08386d178554.sock"}
[09:40:41.008] Spawned 94028
[09:40:41.101] > local-server-1> Spawned ssh, pid=94032
[09:40:41.106] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[09:40:41.311] stderr> Password:
[09:40:44.243] stderr> su: Authentication failure
[09:40:44.292] > local-server-1> ssh child died, shutting down
[09:40:44.298] Local server exit: 0
[09:40:44.298] Received install output: local-server-1> Spawned ssh, pid=94032
OpenSSH_8.1p1, LibreSSL 2.7.3
Password:
su: Authentication failure
local-server-1> ssh child died, shutting down

[09:40:44.299] Failed to parse remote port from server output
[09:40:44.301] Resolver error: Error:
	at Function.Create (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:431103)
	at Object.t.handleInstallOutput (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:429755)
	at Object.e [as tryInstallWithLocalServer] (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:469838)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:487415
	at async Object.t.withShowDetailsEvent (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:491162)
	at async /Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:468281
	at async E (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:464789)
	at async Object.t.resolveWithLocalServer (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:467896)
	at async Object.t.resolve (/Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:488772)
	at async /Users/user/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:565038
[09:40:44.308] ------
```

**Comment by markusdd** [comment]
I can confirm like @memco .

An actual RemoteCommand needs to be specified, the other setting do not make a difference.

**Comment by tanhakabir** [comment]
Hm both of you have a CentOS remote. 

Are you both able to run `echo "echo hello" | ssh yourhost` with the host that has a RemoteCommand set?

**Comment by markusdd** [comment]
I'm not at work but let me spin up a centOS7 VM and try, WIll get back to you in a minute.

**Comment by memco** [comment]
No, I am unable to authenticate before the connection closes using your command.

**Comment by markusdd** [comment]
Ok that is SUPER weird.

I have now set this up on my private Windows PC connecting to an up to date CentOS7 VM.

This is what happens:

```
[21:46:44.627] Log Level: 2
[21:46:44.631] remote-ssh@0.71.2021121615
[21:46:44.631] win32 x64
[21:46:44.642] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a2243656e744f53372d564d227d", attempt 1
[21:46:44.642] "remote.SSH.useLocalServer": false
[21:46:44.643] "remote.SSH.showLoginTerminal": false
[21:46:44.643] "remote.SSH.remotePlatform": {"CentOS7-VM":"linux"}
[21:46:44.643] "remote.SSH.path": C:\Program Files\Git\usr\bin\ssh.exe
[21:46:44.643] "remote.SSH.configFile": undefined
[21:46:44.643] "remote.SSH.useFlock": true
[21:46:44.643] "remote.SSH.lockfilesInTmp": false
[21:46:44.643] "remote.SSH.localServerDownload": auto
[21:46:44.644] "remote.SSH.remoteServerListenOnSocket": false
[21:46:44.644] "remote.SSH.showLoginTerminal": false
[21:46:44.644] "remote.SSH.defaultExtensions": []
[21:46:44.644] "remote.SSH.loglevel": 2
[21:46:44.644] "remote.SSH.enableDynamicForwarding": true
[21:46:44.644] "remote.SSH.enableRemoteCommand": true
[21:46:44.644] "remote.SSH.serverPickPortsFromRange": {}
[21:46:44.644] "remote.SSH.serverInstallPath": {}
[21:46:44.645] SSH Resolver called for host: CentOS7-VM
[21:46:44.645] Setting up SSH remote "CentOS7-VM"
[21:46:44.649] Using commit id "899d46d82c4c95423fb7e10e68eba52050e30ba3" and quality "stable" for server
[21:46:44.652] Install and start server if needed
[21:46:44.666] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[21:46:44.687] > OpenSSH_8.1p1, OpenSSL 1.1.1d  10 Sep 2019

[21:46:44.689] Running script with connection command: "C:\Program Files\Git\usr\bin\ssh.exe" -T -D 58198 -o RemoteCommand=none "CentOS7-VM" bash
[21:46:44.691] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[21:46:45.203] > ]0;C:\WINDOWS\System32\cmd.exe
[21:46:45.204] Got some output, clearing connection timeout
[21:46:45.215] > d2f46f85fe22: running
[21:46:45.247] > Acquiring lock on /home/mkrause/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/vscode-remote-lock.mkrause.899d46d82c4c95423fb7e10e68eba52050e30ba3
> Found existing installation at /home/mkrause/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3...
> Checking /home/mkrause/.vscode-server/.899d46d82c4c95423fb7e10e68eba52050e30ba3.log and /home/mkrause/.vscode-server/.899d46d82c4c95423fb7e10e68eba52050e30ba3.pid for a running server
> Looking for server with pid: 29094
[21:46:45.266] > Starting server with command... /home/mkrause/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/server.sh --start-server --host=127.0.0.1 --enable-remote-auto-shutdown --port=0    &> "/home/mkrause/.vscode-server/.899d46d82c4c95423fb7e10e68eba52050e30ba3.log" < /dev/null
> printenv:
>     XDG_SESSION_ID=14
>     SELINUX_ROLE_REQUESTED=
>     SHELL=/bin/bash
>     SSH_CLIENT=192.168.1.228 58200 22
>     SELINUX_USE_CURRENT_RANGE=
>     USER=mkrause
>     VSCODE_AGENT_FOLDER=/home/mkrause/.vscode-server
>     PATH=/usr/local/bin:/usr/bin
>     MAIL=/var/mail/mkrause
>     PWD=/home/mkrause
>     LANG=en_US.UTF-8
>     SELINUX_LEVEL_REQUESTED=
>     HOME=/home/mkrause
>     SHLVL=2
>     LOGNAME=mkrause
>     SSH_CONNECTION=192.168.1.228 58200 192.168.1.126 22
>     LESSOPEN=||/usr/bin/lesspipe.sh %s
>     XDG_RUNTIME_DIR=/run/user/1000
>     _=/usr/bin/printenv
> Spawned remote server: 29271
> Waiting for server log...
[21:46:45.278] > 
[21:46:45.290] > Waiting for server log...
[21:46:45.318] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,  
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
[21:46:45.328] > 
> d2f46f85fe22: start
> SSH_AUTH_SOCK====
> DISPLAY====
> webUiAccessToken====
> listeningOn==41142==
> osReleaseId==centos==
> arch==x86_64==
> tmpDir==/run/user/1000==
> platform==linux==
[21:46:45.336] > 
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
[21:46:45.344] > 
> extInstallTime====
> serverStartTime==70==
> connectionToken==1111aa11-1111-111a-a1a1-1a1a11a111a1==
> d2f46f85fe22: end
[21:46:45.344] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==41142==
osReleaseId==centos==
arch==x86_64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==70==
connectionToken==1111aa11-1111-111a-a1a1-1a1a11a111a1==

[21:46:45.345] Remote server is listening on 41142
[21:46:45.345] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":41142},"osReleaseId":"centos","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/1000","platform":"linux","connectionToken":"1111aa11-1111-111a-a1a1-1a1a11a111a1"},"serverStartTime":70,"installUnpackCode":""}
[21:46:45.347] Starting forwarding server. localPort 58201 -> socksPort 58198 -> remotePort 41142
[21:46:45.347] Forwarding server listening on 58201
[21:46:45.348] Waiting for ssh tunnel to be ready
[21:46:45.348] [Forwarding server 58201] Got connection 0
[21:46:45.349] Tunneled 41142 to local port 58201
[21:46:45.349] Resolved "ssh-remote+7b22686f73744e616d65223a2243656e744f53372d564d227d" to "127.0.0.1:58201"
[21:46:45.353] ------




[21:46:45.353] > 
[21:46:45.361] [Forwarding server 58201] Got connection 1
[21:46:45.449] [Forwarding server 58201] Got connection 2
```

The connection succeeds, but there is no RemoteCommand being executed.
This line "running script for connection" where it clearly say ssh RemoteCommand=none does not even appear in my original log.

So now it is running, but the remote command is ignored.

Version of extension and VS Code are the same.
There is no difference if I use the Windows OpenSSH oder the one bundled in git bash mingw.

ssh config is like this:
![grafik](https://user-images.githubusercontent.com/25175069/148837747-2e4d183b-2df6-4707-9a9b-868e7c18300f.png)

**Comment by markusdd** [comment]
I think I know why....it clearly says 'uselocalserver' false at the top although it is absolutely turned on in the settings...

![grafik](https://user-images.githubusercontent.com/25175069/148839439-dc8bcd2c-dd15-46b0-bb7e-2a5572981f5b.png)

**Comment by markusdd** [comment]
Ok so I replicated this setup again using a vs code form linux and it seems under Windows it just plain ignores the 'use local server' setting which renders the RemoteCommand option useless.

Good news is: Under the local linux VS code it crashes like in my original post where ssh just exits.

So the Windows thing seems to be yet another issue.

**Comment by markusdd** [comment]
ok I have foudn something out

if I use 

`ssh -t -X slpcomp4 bash -l`

as remote command the session establishes.
That means the bug is most likely as simple as that the remote command gets executed and then ssh session exits.

What shoudl happen instead: the command gets executed and the shell with correct environment persist.

**Comment by markusdd** [comment]
ok, so after trying a lot more stuff I think this issue boil down to one simple thing:

The RemoteCommand needs to spawn a shell at the end of it.
Any command that executes and just exits will close the ssh connection process.

Now it is the question if this is actually a bug or intended behavior that needs to be documented.

Other than that, if I e.g. just use `bash` as RemoteCommand it is working fine.

**Comment by memco** [comment]
My use case for RemoteCommand is to be able to log in as one user and then exit and debug a a different user. I’ll play around with the command some more to see if I’m missing something but in my example I was using `su <user>` to try to accomplish that. Is there some other way I can do that with temoteCommand? As it is I need to pass ForceTTY to get the remoteCommand to work as part of my normal workflow so I expect the my issue has something to do with my specific workflow. As for the remote extension: I guess the question I have is should the extension have some way to fall back to non remoteCommand, report the current error or provide a different error message if the remoteCommand is the source e of the failure?

**Comment by markusdd** [comment]
I think the very simple fact here is that the extension just exactly does what ssh itself does. (because it uses it directly)

If you do `ssh mynode echo HELLO` it will ssh to the node, print HELLO and exit.

What we see here with RemoteCommand is exactly that behavior. So if you need code to spawn in a shell as a different user, you might need to do something like: `ssh -t user@node bash`.

Whatever you enter as remote command, the whole vs code server infrastructure will run under that environment. So it is not the case that the connection is opened, the server spawns and then the remote command is being executed. 
The connection is established, the remote command is being run and THEN under this process tree, the whole infrastructure of VS code remote is spawning its processes.

**Comment by tanhakabir** [comment]
Wow thank you so much @markusdd for doing such an indepth look! I really appreciate it and your patience!

Regarding:

> I think I know why....it clearly says 'uselocalserver' false at the top although it is absolutely turned on in the settings...

Sorry this is due to this bug: https://github.com/microsoft/vscode-remote-release/issues/6147 with a thorough explanation here: https://github.com/microsoft/vscode-remote-release/issues/6147#issuecomment-1009599907


> The RemoteCommand needs to spawn a shell at the end of it.
Any command that executes and just exits will close the ssh connection process.

> Now it is the question if this is actually a bug or intended behavior that needs to be documented.

You're totally right. I'm seeing the same behavior but if I use a non terminating command like `su` then RemoteCommand works as expected.

@roblourens what do you think would be an ideal experience here? It seems like for a subset of commands the current experience makes sense but for any terminating commands it will crash. It's hard to determine if the command is terminating or not programmatically; if we could we could spawn a separate shell for that command.

**Comment by markusdd** [comment]
I think from an ssh perspective the behavior makes sense.
In the context of an editor it somehow doesn't.

I think this issue has to be seen in the context of my newly created tickets #6185  #6186 and #6187 .
 
The main use case for RemoteCommand will be executing and sourcing some kind of environment scripts to make sure the editor runs with the proper tools etc. 
This is mainly what I am doing currently and it already causes problems in other contexts (e.g. so second server can be spawned when one is already running, so you can only have one env per remote machine), see the tickets linked above.

The second use case is hopping to another node in special IT setups, I think this would work fine already now with the knowledge we have gathered here.

So as suggested in #6187 the whole question is if RemoteCommand and environment setup/additional commands to be executed should really be the same thing.

**Comment by tanhakabir** [comment]
After testing out how RemoteCommand works in just terminal with ssh I believe this is expected behavior. Currently, if you set RemoteCommand to `echo hello` for a remote and then connect with your shell, I see this:
```
(base) tanha@r6415 ~ % ssh second 
root@147.182.250.143's password: 
hello
(base) tanha@r6415 ~ % 
```

For this config:
```
Host second
  HostName 147.182.250.143
  User root
  RemoteCommand echo hello
```

Where the terminating RemoteCommand is executed and immediately the ssh connection is closed. This kind of RemoteCommand might be helpful for any non-interactive SSH session where you want to just execute some command and the remote and exit but the Remote-SSH extension is intended to be used in interactive SSH sessions only.

So I believe the current way RemoteCommand works with Remote-SSH is expected as it matches what happens when you ssh in your shell and only works for interactive SSH sessions.

**Comment by markusdd** [comment]
yes that is the same conclusion I came to above.
The only thing is: it does not make much sense in the context of the function inside the editor currently.

But I would not work around this tbh but document the way it is currently and give a proper example.

**Comment by tanhakabir** [comment]
> it does not make much sense in the context of the function inside the editor currently

Could you clarify what this means?

**Comment by markusdd** [comment]
Basically what I am saying is: In order to get the proper remote env we are currently piggybacking on SSH to provide most of the functionality, which is fine.

But that particular property of RemoteCommand is of course not necessarily what you would expect as an end user when configuring this extension inside vs code.
To understand why it behaves like it does you need to understand how SSH treats RemoteCommands, which many people probably do not.

So this is not really a functional problem, but more of an UX issue. What happens is correct in the light of SSH, but unintuitive, which is the whole reason why the ticket exists and we all got confused at first :D


There is in my view only 3 ways to go about it:

1) leave it like it is and explain it properly 
2) recommend RemoteCommand really only for hopping to other nodes and provide other means to provide a shell env and source scripts remotely before the code server launches in the correct environment
3) detect inside the extension when the remote command exits and provide a shell after that instead of also exiting

**Comment by tanhakabir** [comment]
Good call on it being unintuitive. I think it'd be best to leave enabling RemoteCommand as a setting to turn on and add a notification if we see there was a RemoteCommand and a crash explaining the RemoteCommand behavior.

**Comment by markusdd** [comment]
that is also a viable option to make the experience better.

I think it leaves the full flexibility of the Remote Command option but catching the exit and explaining it would help a lot I think.

**Comment by markusdd** [comment]
Will adding the notification pop-up be tracked elsewhere? Or why is this closed?

**Comment by tanhakabir** [comment]
It was closed because we just merged in the PR to add this. Sorry it's not as clear since the Remote SSH extension is a private repo but this will be on Monday's pre-release!

It'll be a log in the SSH logs with a tip for why the crash could have occured.

**Comment by markusdd** [comment]
ah of course that makes sense I got confused because it closed without PR haha
