### ISSUE TITLE
Remote SSH: Failed to connect to the remote extension host server (Error: WebSocket close with status code 1006)

### ISSUE THREAD

**Issue by BnAmN** [microsoft/vscode-remote-release#6131]
![vscode_remote_ssh_websocket_error_1006-1](https://user-images.githubusercontent.com/11967700/148267879-82f13801-0050-4356-bd31-5cbc11607667.png)

## System information
* VSCode Version: `1.63.2` / `1.64.0-insider`
* Local OS Version: `Microsoft Windows 10 Version 21H1 (Build 19043.1415)`
* Remote OS Version: `Debian GNU/Linux 11 (bullseye)` / `Linux 5.10.0-10-amd64`
* Remote Extension/Connection Type: `SSH`
* Remote SSH Extension Version: `0.70.0` / `nightly-2021.12.12420`

## Steps to Reproduce
1. Open remote SSH connection to host
2. Authenticate
3. *In case of first connect:*  
   Wait for `vscode-server` to install
4. Error message appears:  
   `Failed to connect to the remote extension host server (Error: WebSocket close with status code 1006)`  

## Additional information
* The problem suddenly started after changing the IP address of the SSH host.
  * SSH from PowerShell is working without any problems.
  * Hostname resolution is working without any problems.
* Connecting with VSCode from a different machine to the same SSH host ist working correctly.
* I already reinstalled VSCode and deleted the following folders before reinstall:
  * `C:\Program Files\Microsoft VS Code`
  * `%APPDATA%/code`
* I already tried with only `Remote SSH` extension installed.
* I already tried different/older `Remote SSH` extension versions including the `nightly` version.
* I already tried different/older VSCode versions.
* I already tried reinstalling the VSCode server by deleting the `.vscode-server` folder on the SSH host.
* I tried connecting to the URI provided in '**Open in browser**':
  * My machine:  
     ![vscode_remote_ssh_websocket_error_1006-2](https://user-images.githubusercontent.com/11967700/148267884-0ba9368e-9e67-4d03-bf7b-5d12e7a33d97.png)
  * SSH host:  
     ![vscode_remote_ssh_websocket_error_1006-3](https://user-images.githubusercontent.com/11967700/148267885-5947b816-f45a-484b-a8e3-4e7b84c181f9.png)

Since everything was working and still is working from a different machine, I currently don't think the problem comes from the SSH host / the VSCode server.

So something must be wrong with my VSCode installation or machine but I'm currently getting out of ideas...

## Probably realated issues
*The fixes suggested in the following issues didn't help and seem to concern `Remote WSL` more than `Remote SSH`.*
* #6062  
  Concerns `Remote WSL`
* #5352  
  Concerns `Remote WSL`

### Remote SSH
```
[17:21:04.873] Log Level: 2
[17:21:04.879] remote-ssh-nightly@2021.12.12420
[17:21:04.879] win32 x64
[17:21:04.880] SSH Resolver called for "ssh-remote+docs.home.arpa", attempt 1
[17:21:04.881] "remote.SSH.useLocalServer": false
[17:21:04.881] "remote.SSH.showLoginTerminal": false
[17:21:04.881] "remote.SSH.remotePlatform": {"docs.home.arpa":"linux","V-Server":"linux"}
[17:21:04.881] "remote.SSH.path": undefined
[17:21:04.882] "remote.SSH.configFile": undefined
[17:21:04.882] "remote.SSH.useFlock": true
[17:21:04.882] "remote.SSH.lockfilesInTmp": false
[17:21:04.882] "remote.SSH.localServerDownload": auto
[17:21:04.882] "remote.SSH.remoteServerListenOnSocket": false
[17:21:04.882] "remote.SSH.showLoginTerminal": false
[17:21:04.883] "remote.SSH.defaultExtensions": []
[17:21:04.883] "remote.SSH.loglevel": 2
[17:21:04.883] "remote.SSH.serverPickPortsFromRange": {}
[17:21:04.883] "remote.SSH.enableDynamicForwarding": true
[17:21:04.883] "remote.SSH.serverInstallPath": {}
[17:21:04.884] SSH Resolver called for host: docs.home.arpa
[17:21:04.884] Setting up SSH remote "docs.home.arpa"
[17:21:04.907] Using commit id "899d46d82c4c95423fb7e10e68eba52050e30ba3" and quality "stable" for server
[17:21:04.913] Install and start server if needed
[17:21:04.917] Checking ssh with "ssh -V"
[17:21:04.978] > OpenSSH_for_Windows_8.
[17:21:04.978] > 1p1, LibreSSL 3.0.2

[17:21:04.985] Running script with connection command: ssh -T -D 60615 "docs.home.arpa" bash
[17:21:04.987] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[17:21:05.272] > ]0;C:\WINDOWS\System32\cmd.exe
[17:21:05.273] Got some output, clearing connection timeout
[17:21:05.411] > bnamn@docs.home.arpa's password: 
[17:21:05.413] Showing password prompt
[17:21:08.396] Got password response
[17:21:08.397] "install" wrote data to terminal: "******"
[17:21:08.431] > 
[17:21:08.581] > f690c3d8209f: running
[17:21:08.630] > Acquiring lock on /home/bnamn/.vscode-server/bin/899d46d82c4c95423fb7e10e68e
> ba52050e30ba3/vscode-remote-lock.bnamn.899d46d82c4c95423fb7e10e68eba52050e30
> ba3
> Found existing installation at /home/bnamn/.vscode-server/bin/899d46d82c4c95
> 423fb7e10e68eba52050e30ba3...
> Checking /home/bnamn/.vscode-server/.899d46d82c4c95423fb7e10e68eba52050e30ba
> 3.log and /home/bnamn/.vscode-server/.899d46d82c4c95423fb7e10e68eba52050e30b
> a3.pid for a running server
> Looking for server with pid: 3074
> Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
[17:21:08.638] > Checking server status on port 35697 with wget
> f690c3d8209f: start
> SSH_AUTH_SOCK====
> DISPLAY====
> webUiAccessToken====
> listeningOn==35697==
> osReleaseId==debian==
> arch==x86_64==
> tmpDir==/run/user/1001==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
[17:21:08.640] > 
> extInstallTime====
> serverStartTime====
> connectionToken==a11a1a11-aa1a-1a11-aa11-11a1aa111aaa==
> f690c3d8209f: end
[17:21:08.640] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==35697==
osReleaseId==debian==
arch==x86_64==
tmpDir==/run/user/1001==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==a11a1a11-aa1a-1a11-aa11-11a1aa111aaa==

[17:21:08.641] Remote server is listening on 35697
[17:21:08.641] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":35697},"osReleaseId":"debian","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/1001","platform":"linux","connectionToken":"a11a1a11-aa1a-1a11-aa11-11a1aa111aaa"},"installUnpackCode":""}
[17:21:08.647] Starting forwarding server. localPort 60621 -> socksPort 60615 -> remotePort 35697
[17:21:08.649] Forwarding server listening on 60621
[17:21:08.649] Waiting for ssh tunnel to be ready
[17:21:08.654] Tunneled 35697 to local port 60621
[17:21:08.655] Resolved "ssh-remote+docs.home.arpa" to "127.0.0.1:60621"
[17:21:08.664] ------
```

### Log (Main)
```
[2022-01-05 17:21:03.037] [main] [info] Extension host with pid 3020 exited with code: 0, signal: null.
[2022-01-05 17:21:04.127] [main] [info] Starting extension host with pid 14048 (fork() took 13 ms).
```

### Log (Window)
```
[2022-01-05 17:21:04.082] [renderer4] [info] Invoking resolveAuthority(ssh-remote)
[2022-01-05 17:21:04.697] [renderer4] [error] [Extension Host] (node:14048) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
[2022-01-05 17:21:08.685] [renderer4] [info] resolveAuthority(ssh-remote) returned '127.0.0.1:60621' after 4603 ms
[2022-01-05 17:21:08.827] [renderer4] [error] [remote-connection][Management   ][f1f26…][initial][127.0.0.1:60621] socketFactory.connect() failed or timed out. Error:
[2022-01-05 17:21:08.828] [renderer4] [error] Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:583:36456)
[2022-01-05 17:21:08.829] [renderer4] [error] [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
[2022-01-05 17:21:08.829] [renderer4] [error] Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:583:36456)
[2022-01-05 17:21:08.830] [renderer4] [error] Cannot register remote filesystem provider. Error while fetching remote environment. WebSocket close with status code 1006
[2022-01-05 17:21:08.833] [renderer4] [error] Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:583:36456)
[2022-01-05 17:21:08.914] [renderer4] [error] Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:583:36456)
[2022-01-05 17:21:09.251] [renderer4] [error] [remote-connection][ExtensionHost][c3db1…][initial][127.0.0.1:60621] socketFactory.connect() failed or timed out. Error:
[2022-01-05 17:21:09.252] [renderer4] [error] Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:583:36456)
[2022-01-05 17:21:09.253] [renderer4] [error] [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
[2022-01-05 17:21:09.254] [renderer4] [error] Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:583:36456)
[2022-01-05 17:21:09.255] [renderer4] [error] Error received from starting extension host (kind: Remote)
[2022-01-05 17:21:09.256] [renderer4] [error] Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:583:36456)
[2022-01-05 17:21:09.258] [renderer4] [error] WebSocket close with status code 1006: Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:583:36456)
[2022-01-05 17:21:10.680] [renderer4] [error] WebSocket close with status code 1006: Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:583:36456)
[2022-01-05 17:21:12.808] [renderer4] [error] WebSocket close with status code 1006: Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:583:36456)
```

**Comment by tanhakabir** [comment]
Hm have you run `Kill VS Code Server on Host...` to make sure everything was cleaned up?

**Comment by BnAmN** [comment]
Yes I did.

I just repeated the following steps again:
* On my machine:
  * Opened new local VSCode window
  * Executed `Kill VS Code Server on Host...` for my SSH host
     * `[10:13:50.906] "Uninstall VS Code Server" wrote data to terminal: "******"`
     * `[10:13:52.440] "Uninstall VS Code Server" terminal command done`
  * Rebooted my machine
* On my SSH host:
  * `rm -rf /home/bnamn/.vscode-server`
  * `rm -rf /home/bnamn/.cache/code-server`
  * `rm -rf /home/bnamn/.config/code-server`
  * Double checked for remnants:
    * `sudo find / -name "*code-server*"`
    * `sudo find / -name "*vscode*"`
  * Rebooted the Host

I tried to connect again: Sadly the error still occurs...

I still don't fully understand what's the actual problem. Should the Extension Host WebSocket server be running on my machine or the remote SSH host? Is there any other log I could look into to get find the root causing the error `1006`? I guess it must be some sort of low-level network or permission error?

**Comment by BnAmN** [comment]
Sorry for delay too.

No sadly the logs stops after that and I wasn't able to find another log containing more information about the error yet.

**Comment by tanhakabir** [comment]
Sorry again for the super late reply! Hm based on these logs I don't see any error so it's hard for me to figure out what's going on here. Could you see if  there are any errors in Dev Tools? You can use the command `Toggle Developer Tools` and see if there's anything interesting in console

**Comment by BnAmN** [comment]
The developer tools console showed the same errors as the "Window" log.

But I just updated to VSCode 1.64.2 and now it's working again.  
I'm still curious what caused the problem...

**Comment by tanhakabir** [comment]
Hm I'm not sure :/ Unfortunately without any specific error logging it's hard to tell what could have been the issue. But I'm glad this was resolved for you!

**Comment by metya** [comment]
I have vscode 1.65.2

And I have exactly the same problem.

**Comment by tanhakabir** [comment]
@metya could you please create a new issue with your Remote SSH logs?

**Comment by metya** [comment]
seems if forwarding ports and TCP ports in host sshd_config is allowed, everything works.

**Comment by tanhakabir** [comment]
Port forwarding is required to use the Remote SSH extension

**Comment by metya** [comment]
But port forwarding was turned on in the remote extension settings. But it has to be turned on in sshd_config on the host too, just turning on in settings doesn't work.

**Comment by tanhakabir** [comment]
Yes the remote host needs to have port forwarding allowed in their sshd_config. The extension settings have to do with port forwarding locally on your machine. This issue has more details: https://github.com/microsoft/vscode-remote-release/issues/92

**Comment by metya** [comment]
I see! 
Thanks for the informaton.
