### ISSUE TITLE
Error when useLocalServer: True. Unable to access server level 2

### ISSUE THREAD

**Issue by jesusdpa1** [microsoft/vscode-remote-release#6159]
- VSCode Version: 1.63.2
- Local OS Version: Windows 11
- Remote OS Version: Linux
- Remote Extension/Connection Type: SSH
- Logs: 

Error when activating Local server. Show login in terminal stops working in both log1 and log2. Unable to access Log2

SSH config file

```bash
Host log1
   HostName ########
   User $USERNAME
   KeepAlive yes

Host log2
   HostName ######
   ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -W %h:%p log1
   User $USERNAME
   KeepAlive yes
```

```bash 
[10:48:08.141] Log Level: 2
[10:48:08.143] remote-ssh@0.70.0
[10:48:08.143] win32 x64
[10:48:08.144] SSH Resolver called for "ssh-remote+compute", attempt 1
[10:48:08.145] "remote.SSH.useLocalServer": true
[10:48:08.145] "remote.SSH.path": undefined
[10:48:08.145] "remote.SSH.configFile": undefined
[10:48:08.145] "remote.SSH.useFlock": true
[10:48:08.145] "remote.SSH.lockfilesInTmp": false
[10:48:08.146] "remote.SSH.localServerDownload": auto
[10:48:08.146] "remote.SSH.remoteServerListenOnSocket": false
[10:48:08.146] "remote.SSH.showLoginTerminal": true
[10:48:08.146] "remote.SSH.defaultExtensions": []
[10:48:08.146] "remote.SSH.loglevel": 2
[10:48:08.146] "remote.SSH.serverPickPortsFromRange": {}
[10:48:08.146] "remote.SSH.enableDynamicForwarding": true
[10:48:08.147] "remote.SSH.serverInstallPath": {}
[10:48:08.148] SSH Resolver called for host: compute
[10:48:08.148] Setting up SSH remote "compute"
[10:48:08.152] Acquiring local install lock: C:\Users\jesus\AppData\Local\Temp\vscode-remote-ssh-4463ef7a-install.lock
[10:48:08.166] Looking for existing server data file at c:\Users\jesus\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-ssh\vscode-ssh-host-4463ef7a-899d46d82c4c95423fb7e10e68eba52050e30ba3-0.70.0\data.json
[10:48:08.167] Using commit id "899d46d82c4c95423fb7e10e68eba52050e30ba3" and quality "stable" for server
[10:48:08.170] Install and start server if needed
[10:48:08.174] Checking ssh with "ssh -V"
[10:48:08.212] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[10:48:08.216] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[10:48:08.251] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[10:48:08.255] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[10:48:08.298] > OpenSSH_8.8p1, OpenSSL 1.1.1l  24 Aug 2021

[10:48:08.315] Using SSH config file "C:\Users\jesus\.ssh\config"
[10:48:08.316] askpass server listening on \\.\pipe\vscode-ssh-askpass-ef07ac277c4e7f1d48228e9b9932aa7016ce8bda-sock
[10:48:08.316] Spawning local server with {"serverId":1,"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-d9edbb24b2f3668813d76710ab8e3bd82d1cc06f-sock","sshCommand":"C:\\Program Files\\Git\\usr\\bin\\ssh.exe","sshArgs":["-v","-T","-D","56272","-F","C:\\Users\\jesus\\.ssh\\config","compute","bash"],"dataFilePath":"c:\\Users\\jesus\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-vscode-remote.remote-ssh\\vscode-ssh-host-4463ef7a-899d46d82c4c95423fb7e10e68eba52050e30ba3-0.70.0\\data.json"}
[10:48:08.316] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"c:\\Users\\jesus\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.70.0\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"C:\\Users\\jesus\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"c:\\Users\\jesus\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.70.0\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-ef07ac277c4e7f1d48228e9b9932aa7016ce8bda-sock"}
[10:48:08.327] Spawned 19908
[10:48:08.419] > local-server-1> Spawned ssh, pid=19140
[10:48:08.457] stderr> OpenSSH_8.8p1, OpenSSL 1.1.1l  24 Aug 2021
[10:48:08.528] stderr> /bin/sh: line 0: exec: C:WindowsSystem32OpenSSHssh.exe: not found
[10:48:08.528] stderr> kex_exchange_identification: Connection closed by remote host
[10:48:08.528] stderr> Connection closed by UNKNOWN port 65535
[10:48:08.561] > local-server-1> ssh child died, shutting down
[10:48:08.570] Local server exit: 0
[10:48:08.570] Received install output: local-server-1> Spawned ssh, pid=19140
OpenSSH_8.8p1, OpenSSL 1.1.1l  24 Aug 2021
/bin/sh: line 0: exec: C:WindowsSystem32OpenSSHssh.exe: not found
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
local-server-1> ssh child died, shutting down

[10:48:08.570] Failed to parse remote port from server output
[10:48:08.572] Resolver error: Error: 
	at Function.Create (c:\Users\jesus\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:430425)
	at Object.t.handleInstallOutput (c:\Users\jesus\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:429068)
	at Object.e [as tryInstallWithLocalServer] (c:\Users\jesus\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:469079)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\jesus\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:486771
	at async Object.t.withShowDetailsEvent (c:\Users\jesus\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:490561)
	at async c:\Users\jesus\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:467603
	at async E (c:\Users\jesus\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:464111)
	at async Object.t.resolveWithLocalServer (c:\Users\jesus\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:467218)
	at async Object.t.resolve (c:\Users\jesus\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:488171)
	at async c:\Users\jesus\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:564197
[10:48:08.576] ------
```

Steps to Reproduce:

1. access settings json, 
2. set "remote.SSH.useLocalServer": true, 
3. connect to remote server

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by bamurtaugh** [comment]
Thanks for filing. To verify, when `"remote.SSH.useLocalServer": false`, you're able to connect?

Does running `Kill Local Connection Server For Host...` and then connecting help?
