### ISSUE TITLE
TypeError: Cannot read property 'spawn' of undefined

### ISSUE THREAD

**Issue by gdw2** [microsoft/vscode-remote-release#6161]
I get the following error when I attempt to develop within a remote (over SSH) container.  I'm willing to bet the problem is related to my use of NixOS as the remote host, but the logs and lack of source make it difficult to debug. 

- VSCode Version:
- Local OS Version: Mac OS 12.0.1
- Remote OS Version: NixOS 20.09.4404.a13824fe5e3 (Nightingale)
- Remote Extension/Connection Type: SSH + Docker
- Logs:

```
[2022-01-12T21:09:20.731Z] Remote-Containers 0.209.6 in VS Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3).
[2022-01-12T21:09:20.731Z] Start: Resolving Remote
[2022-01-12T21:09:20.740Z] Start: Run: ssh sopair /bin/sh -c /bin/sh
[2022-01-12T21:09:20.742Z] Start: Run in host: id -un
[2022-01-12T21:09:22.554Z] gwarner
[2022-01-12T21:09:22.555Z] 
[2022-01-12T21:09:22.555Z] Stop (1813 ms): Run in host: id -un
[2022-01-12T21:09:22.555Z] Start: Run in host: cat /etc/passwd
[2022-01-12T21:09:22.654Z] Stop (99 ms): Run in host: cat /etc/passwd
[2022-01-12T21:09:22.655Z] Start: Run in host: echo ~
[2022-01-12T21:09:22.755Z] /home/gwarner
[2022-01-12T21:09:22.755Z] 
[2022-01-12T21:09:22.755Z] Stop (100 ms): Run in host: echo ~
[2022-01-12T21:09:22.756Z] Start: Run in host: test -x '/home/gwarner/.vscode-remote-containers/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/node'
[2022-01-12T21:09:22.854Z] 
[2022-01-12T21:09:22.855Z] 
[2022-01-12T21:09:22.855Z] Stop (99 ms): Run in host: test -x '/home/gwarner/.vscode-remote-containers/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/node'
[2022-01-12T21:09:22.855Z] Start: Run in host: test -f '/home/gwarner/.vscode-remote-containers/dist/vscode-remote-containers-server-0.209.6.js'
[2022-01-12T21:09:22.954Z] 
[2022-01-12T21:09:22.955Z] 
[2022-01-12T21:09:22.955Z] Stop (100 ms): Run in host: test -f '/home/gwarner/.vscode-remote-containers/dist/vscode-remote-containers-server-0.209.6.js'
[2022-01-12T21:09:23.055Z] userEnvProbe: loginInteractiveShell (default)
[2022-01-12T21:09:23.056Z] userEnvProbe shell: /bin/sh
[2022-01-12T21:09:23.282Z] userEnvProbe PATHs:
Probe:     '/home/gwarner/bin:/home/gwarner/.local/bin:/home/gwarner/.npm-packages/bin:/home/gwarner/e/.npm-packages/bin:/run/wrappers/bin:/home/gwarner/.nix-profile/bin:/etc/profiles/per-user/gwarner/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/home/jmartin/repos/SimulationService2/'
Container: None
[2022-01-12T21:09:23.365Z] Setting up container for folder or workspace: /home/gwarner/code/bep/modules/om/bep-om
[2022-01-12T21:09:23.365Z] Host: ssh://sopair
[2022-01-12T21:09:23.367Z] Start: Check Docker is running
[2022-01-12T21:09:23.367Z] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[2022-01-12T21:09:23.555Z] Stop (188 ms): Run in Host: docker version --format {{.Server.APIVersion}}
[2022-01-12T21:09:23.555Z] Server API version: 1.40
[2022-01-12T21:09:23.556Z] Stop (189 ms): Check Docker is running
[2022-01-12T21:09:24.156Z] Start: Run in Host: git rev-parse --show-cdup
[2022-01-12T21:09:24.354Z] Stop (198 ms): Run in Host: git rev-parse --show-cdup
[2022-01-12T21:09:24.355Z] Start: Run in Host: docker ps -q -a --filter label=vsch.local.folder=/home/gwarner/code/bep/modules/om/bep-om --filter label=vsch.quality=stable
[2022-01-12T21:09:25.006Z] Stop (651 ms): Run in Host: docker ps -q -a --filter label=vsch.local.folder=/home/gwarner/code/bep/modules/om/bep-om --filter label=vsch.quality=stable
[2022-01-12T21:09:25.008Z] Start: Run in Host: docker build -f /home/gwarner/code/bep/modules/om/bep-om/.devcontainer/Dockerfile -t vsc-bep-om-9fe99ef5358a7bb504189a5b852c8496 --build-arg VARIANT=3.14 /home/gwarner/code/bep/modules/om/bep-om/.devcontainer
[2022-01-12T21:09:25.110Z] TypeError: Cannot read property 'spawn' of undefined
    at Object.ptyExec (/home/gwarner/.vscode-remote-containers/dist/vscode-remote-containers-server-0.209.6.js:10:7426)
    at Object.i (/home/gwarner/.vscode-remote-containers/dist/vscode-remote-containers-server-0.209.6.js:10:3232)
    at Object.<anonymous> (/home/gwarner/.vscode-remote-containers/dist/vscode-remote-containers-server-0.209.6.js:10:3308)
    at Object.request (/home/gwarner/.vscode-remote-containers/dist/vscode-remote-containers-server-0.209.6.js:10:338)
    at y._onrequest (/home/gwarner/.vscode-remote-containers/dist/vscode-remote-containers-server-0.209.6.js:5:14010)
    at y.write (/home/gwarner/.vscode-remote-containers/dist/vscode-remote-containers-server-0.209.6.js:5:13590)
    at /home/gwarner/.vscode-remote-containers/dist/vscode-remote-containers-server-0.209.6.js:5:16506
    at /home/gwarner/.vscode-remote-containers/dist/vscode-remote-containers-server-0.209.6.js:5:2447
    at /home/gwarner/.vscode-remote-containers/dist/vscode-remote-containers-server-0.209.6.js:5:20780
    at Object.cb (/home/gwarner/.vscode-remote-containers/dist/vscode-remote-containers-server-0.209.6.js:5:11326)
```

Steps to Reproduce:

1. Follow the steps here: https://code.visualstudio.com/docs/remote/containers#_open-a-folder-on-a-remote-ssh-host-in-a-container
2. When selecting container, select Alpine or NodeJS 16.  (I'm sure any container image will fail.)

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by chrmarti** [comment]
Is there a `/home/gwarner/.vscode-remote-containers/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/node_modules/node-pty` folder on the SSH server and what is in there? (It looks like that module didn't load.)

**Comment by gdw2** [comment]
negative.  There is a `/home/gwarner/.vscode-remote-containers/dist/...` dir, but not a `/home/gwarner/.vscode-remote-containers/bin` dir.

**Comment by chrmarti** [comment]
The log suggest that there is a `/home/gwarner/.vscode-remote-containers/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/node` executable, is that not there?

**Comment by gdw2** [comment]
That's right.

**Comment by chrmarti** [comment]
@gdw2 Just to make sure I understand: Is the executable there?

**Comment by gdw2** [comment]
No, it's not there.

**Comment by chrmarti** [comment]
Is there an antivirus running on that machine that might quarantine the executable? The log indicates that the executable was there.
