### ISSUE TITLE
Impossible to close window if ssh disconnects suddenly

### ISSUE THREAD

**Issue by yagueto** [microsoft/vscode-remote-release#6175]
- VSCode Version: 1.63.2
- Local OS Version: Arch 5.16.0
- Remote OS Version: Ubuntu 21.10
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. Open a remote connection
2. Cut internet connection on the remote machine
3. Modify an opened file 
3. A popup appears trying to reconnect to the remote (failing repeatedly, as desired)
4. If you then try to close the editor, it turns out to be impossible, as it tries constantly to save the file. 

Does this issue occur when you try this locally?: -
Does this issue occur when you try this locally and all extensions are disabled?: -

**Comment by bamurtaugh** [comment]
Are you able to access `Close Remote Connection` from this state?

**Comment by bamurtaugh** [comment]
Thanks for the info. Are you able to retrieve any Remote-SSH output logs, or does that pop up/conflict with the same saving notification?

**Comment by yagueto** [comment]
The ssh logs look like this: it just keeps on trying to reconnect

```
[19:17:44.626] SSH Resolver called for "ssh-remote+192.168.1.104", attempt 5, (Reconnection)
[19:17:44.627] SSH Resolver called for host: 192.168.1.104
[19:17:44.627] Setting up SSH remote "192.168.1.104"
[19:17:44.632] Acquiring local install lock: /tmp/vscode-remote-ssh-1bfdbad8-install.lock
[19:17:44.633] Looking for existing server data file at /home/USERNAME/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-1bfdbad8-899d46d82c4c95423fb7e10e68eba52050e30ba3-0.70.0/data.json
[19:17:44.634] Using commit id "899d46d82c4c95423fb7e10e68eba52050e30ba3" and quality "stable" for server
[19:17:44.641] Install and start server if needed
[19:17:44.678] askpass server listening on /run/user/1000/vscode-ssh-askpass-b79e597b400e5989662ffcff1988bf978c2b16be.sock
[19:17:44.678] Spawning local server with {"serverId":5,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-b1b168dfb8a01f0c8bdd884587939574580b9716.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","35911","-o","ConnectTimeout=15","192.168.1.104"],"dataFilePath":"/home/USERNAME/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-1bfdbad8-899d46d82c4c95423fb7e10e68eba52050e30ba3-0.70.0/data.json"}
[19:17:44.679] Local server env: {"DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/opt/visual-studio-code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-b79e597b400e5989662ffcff1988bf978c2b16be.sock"}
[19:17:44.694] Spawned 15520
[19:17:45.019] > local-server-5> Spawned ssh, pid=15528
[19:17:45.023] stderr> OpenSSH_8.8p1, OpenSSL 1.1.1m  14 Dec 2021
[19:17:48.074] stderr> ssh: connect to host 192.168.1.104 port 2222: No route to host
[19:17:48.077] > local-server-5> ssh child died, shutting down
[19:17:48.085] Local server exit: 0
[19:17:48.086] Received install output: local-server-5> Spawned ssh, pid=15528
OpenSSH_8.8p1, OpenSSL 1.1.1m  14 Dec 2021
ssh: connect to host 192.168.1.104 port 2222: No route to host
local-server-5> ssh child died, shutting down

[19:17:48.088] Resolver error: Error: No route to host
	at Function.Offline (/home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:430476)
	at /home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:428281
	at Object.t.handleInstallOutput (/home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:428404)
	at Object.e [as tryInstallWithLocalServer] (/home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:469079)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:486771
	at async Object.t.withShowDetailsEvent (/home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:490561)
	at async /home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:467603
	at async E (/home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:464111)
	at async Object.t.resolveWithLocalServer (/home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:467218)
	at async Object.t.resolve (/home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:488171)
	at async /home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:564197
[19:17:48.093] ------




[19:17:58.176] ------




[19:17:58.176] SSH Resolver called for "ssh-remote+192.168.1.104", attempt 6, (Reconnection)
[19:17:58.177] SSH Resolver called for host: 192.168.1.104
[19:17:58.177] Setting up SSH remote "192.168.1.104"
[19:17:58.181] Acquiring local install lock: /tmp/vscode-remote-ssh-1bfdbad8-install.lock
[19:17:58.183] Looking for existing server data file at /home/USERNAME/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-1bfdbad8-899d46d82c4c95423fb7e10e68eba52050e30ba3-0.70.0/data.json
[19:17:58.184] Using commit id "899d46d82c4c95423fb7e10e68eba52050e30ba3" and quality "stable" for server
[19:17:58.191] Install and start server if needed
[19:17:58.205] askpass server listening on /run/user/1000/vscode-ssh-askpass-b876700193e790a0b059393c83e3dc8bff5b037e.sock
[19:17:58.206] Spawning local server with {"serverId":6,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-5f68f4d0282d624d1f5b5626bc611fad88003d58.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","42809","-o","ConnectTimeout=15","192.168.1.104"],"dataFilePath":"/home/USERNAME/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-1bfdbad8-899d46d82c4c95423fb7e10e68eba52050e30ba3-0.70.0/data.json"}
[19:17:58.207] Local server env: {"DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/opt/visual-studio-code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-b876700193e790a0b059393c83e3dc8bff5b037e.sock"}
[19:17:58.218] Spawned 15529
[19:17:58.562] > local-server-6> Spawned ssh, pid=15537
[19:17:58.570] stderr> OpenSSH_8.8p1, OpenSSL 1.1.1m  14 Dec 2021
[19:18:01.603] stderr> ssh: connect to host 192.168.1.104 port 2222: No route to host
[19:18:01.608] > local-server-6> ssh child died, shutting down
[19:18:01.615] Local server exit: 0
[19:18:01.616] Received install output: local-server-6> Spawned ssh, pid=15537
OpenSSH_8.8p1, OpenSSL 1.1.1m  14 Dec 2021
ssh: connect to host 192.168.1.104 port 2222: No route to host
local-server-6> ssh child died, shutting down

[19:18:01.619] Resolver error: Error: No route to host
	at Function.Offline (/home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:430476)
	at /home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:428281
	at Object.t.handleInstallOutput (/home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:428404)
	at Object.e [as tryInstallWithLocalServer] (/home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:469079)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:486771
	at async Object.t.withShowDetailsEvent (/home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:490561)
	at async /home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:467603
	at async E (/home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:464111)
	at async Object.t.resolveWithLocalServer (/home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:467218)
	at async Object.t.resolve (/home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:488171)
	at async /home/USERNAME/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:564197
[19:18:01.634] ------
```.


The saving and the reconnecting notifications popup one over the other, and if I close them they will only popup again some seconds  after

**Comment by bamurtaugh** [comment]
cc @tanhakabir

**Comment by tanhakabir** [comment]
Hm when I tried to repro this case on my side by being connected and then turning off my wifi and then eventually turning it back on. I didn't get exactly the same error but instead I got stuck in this case:
![image](https://user-images.githubusercontent.com/12758612/151856029-4acd245c-570c-40cb-8e7c-8039ffaac05c.png)

Where I also couldn't click on anything in the VS Code window and when I tried to close the window I see: 
![image](https://user-images.githubusercontent.com/12758612/151856101-ce2ca111-c060-4283-b6a3-8a51f7a39efe.png)

**Comment by tanhakabir** [comment]
@bpasero have you seen this error recently or are familiar with what could be the issue?

**Comment by bpasero** [comment]
No I am not, sorry. This indicates that there is a handler registering to the `ILifecycleService#onWillShutdown` event taking longer than 800ms (the delay we pick before showing progress dialog). We print the identifier of the handler in dev tools console, so maybe check there.

The workbench is non-functional at this event stage, so we block any access to the UI by showing a modal overlay.

**Comment by yagueto** [comment]
The issue is still not solved, what info is it needed?

**Comment by tanhakabir** [comment]
Sorry @yagueto I still need to investigate this issue

**Comment by bpasero** [comment]
I pushed a change to give the user control to force shutdown when this happens, see https://github.com/microsoft/vscode/issues/134180#issuecomment-1049629149

It is quite possible that this is as such a duplicate of https://github.com/microsoft/vscode/issues/134180

**Comment by bpasero** [comment]
I feel this issue should close in favour of the linked ones and the resolution.
