### ISSUE TITLE
Prompt for system password

### ISSUE THREAD

**Issue by pauline-wang-techlabs** [microsoft/vscode-remote-release#6230]
Hi - I would like the password prompt to appear each time when I SSH to my linux. However the password prompt does not always show up and when it does not show up, it leads to a connection timeout.  How can I set up so the password prompt appear each time when I try to SSH to my Linux?

**Comment by tanhakabir** [comment]
Hello! What is the OS of your local machine? And do you have `remote.SSH.useLocalServer` set to true?

Generally with out `useLocalServer` we prompt for your password when the ssh binary on your machine prompts us for one. If you have Remote SSH logs from when the connection times out I could investigate why you aren't being prompted

**Comment by pauline-wang-techlabs** [comment]
Yes `remote.SSH.useLocalServer` is set to True and my OS Is macOS Monterey 12.1.

I uncheck the box on Remote.SSH:Use Local Server on Settings but the password prompt still did not come up.

**Comment by tanhakabir** [comment]
Could I see your Remote SSH logs? Here's some details for where to look: https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues

**Comment by pauline-wang-techlabs** [comment]
Yes - Here you go `[10:22:37.162] Log Level: 2
[10:22:37.164] remote-ssh@0.70.0
[10:22:37.164] darwin x64
[10:22:37.172] SSH Resolver called for "ssh-remote+192.168.86.84", attempt 1
[10:22:37.173] "remote.SSH.useLocalServer": false
[10:22:37.173] "remote.SSH.showLoginTerminal": false
[10:22:37.173] "remote.SSH.remotePlatform": {}
[10:22:37.173] "remote.SSH.path": undefined
[10:22:37.173] "remote.SSH.configFile": undefined
[10:22:37.174] "remote.SSH.useFlock": true
[10:22:37.174] "remote.SSH.lockfilesInTmp": false
[10:22:37.174] "remote.SSH.localServerDownload": auto
[10:22:37.174] "remote.SSH.remoteServerListenOnSocket": false
[10:22:37.174] "remote.SSH.showLoginTerminal": false
[10:22:37.174] "remote.SSH.defaultExtensions": []
[10:22:37.174] "remote.SSH.loglevel": 2
[10:22:37.174] "remote.SSH.serverPickPortsFromRange": {}
[10:22:37.175] "remote.SSH.enableDynamicForwarding": true
[10:22:37.175] "remote.SSH.serverInstallPath": {}
[10:22:37.176] SSH Resolver called for host: 192.168.86.84
[10:22:37.176] Setting up SSH remote "192.168.86.84"
[10:22:37.180] Using commit id "899d46d82c4c95423fb7e10e68eba52050e30ba3" and quality "stable" for server
[10:22:37.183] Install and start server if needed
[10:22:42.587] PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[10:22:42.587] Checking ssh with "ssh -V"
[10:22:42.593] > OpenSSH_8.6p1, LibreSSL 2.8.3

[10:22:42.595] Running script with connection command: ssh -T -D 50684 -o ConnectTimeout=15 '192.168.86.84' bash
[10:22:58.019] > ssh: connect to host 192.168.86.84 port 22: Operation timed out
[10:22:58.019] Got some output, clearing connection timeout
[10:22:58.265] "install" terminal command done
[10:22:58.265] Install terminal quit with output: ssh: connect to host 192.168.86.84 port 22: Operation timed out
[10:22:58.266] Received install output: ssh: connect to host 192.168.86.84 port 22: Operation timed out
[10:22:58.266] Resolver error: Error: The operation timed out
	at Function.Offline (/Users/paulinewang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:430476)
	at /Users/paulinewang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:428207
	at Object.t.handleInstallOutput (/Users/paulinewang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:428404)
	at Object.t.tryInstall (/Users/paulinewang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:524212)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/paulinewang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:487216
	at async Object.t.withShowDetailsEvent (/Users/paulinewang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:490561)
	at async Object.t.resolve (/Users/paulinewang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:488295)
	at async /Users/paulinewang/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:564197
[10:22:58.271] ------`

**Comment by tanhakabir** [comment]
It looks like ssh is having difficulty resolving your remote: `Install terminal quit with output: ssh: connect to host 192.168.86.84 port 22: Operation timed out`

This comes from the ssh binary on your machine so it's most likely an issue with your remote keeping port 22 open. I'm sorry it's hard for me to debug exactly this would be the issue but I'd recommend checking the configurations of your remote to make sure it's set up well to receive SSH connections.

**Comment by pauline-wang-techlabs** [comment]
Got it - no worries. Thanks for the help.
