### ISSUE TITLE
VS Code Server for WSL failed to start. No messages received for 90s

### ISSUE THREAD

**Issue by dlambert-eworking** [microsoft/vscode-remote-release#6231]
Hello,
I'm using WSL2 but since I changed my PC I got this error "VS Code Server for WSL failed to start.".
Have you a
 idea to solve this?
Thank you in advance.

- VSCode Version: 1.63.2
- Local OS Version: W10 Version 1909 (18363.1977) 
- Remote OS Version: Ubuntu 20.04.2 LTS
- Remote Extension/Connection Type: WSL
- Action : "New WSL Windows"
- Logs: with debug mode (no error above)

[2022-01-25 17:43:22.159] [18:43:22] Started scanning user extensions
[2022-01-25 17:43:22.159] [18:43:22] Scanned user extensions: 0
[2022-01-25 17:43:22.162] [18:43:21] Error occurred in server
[2022-01-25 17:43:22.162] [18:43:21] Error: listen EADDRNOTAVAIL: address not available 127.0.0.1
[2022-01-25 17:43:22.162]     at Server.setupListenHandle [as _listen2] (net.js:1301:21)
[2022-01-25 17:43:22.162]     at listenInCluster (net.js:1366:12)
[2022-01-25 17:43:22.162]     at doListen (net.js:1503:7)
[2022-01-25 17:43:22.162]     at processTicksAndRejections (internal/process/task_queues.js:81:21) {
[2022-01-25 17:43:22.162]   code: 'EADDRNOTAVAIL',
[2022-01-25 17:43:22.162]   errno: -99,
[2022-01-25 17:43:22.162]   syscall: 'listen',
[2022-01-25 17:43:22.162]   address: '127.0.0.1'
[2022-01-25 17:43:22.162] }
[2022-01-25 17:44:52.607] VS Code Server for WSL failed to start. No messages received for 90s
[2022-01-25 17:44:52.607] For help with startup problems, go to
[2022-01-25 17:44:52.607] https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips
[2022-01-25 17:44:52.614] C:\windows\System32\wsl.exe -d Ubuntu2004 -e kill 1002
[2022-01-25 17:44:52.956] WSL Daemon exited with code 0

**Comment by dlambert-eworking** [comment]
Hello,
Here is the log host agent starting time :

What is that mean ?
[08:03:31] getUnixShellEnvironment#stderr bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

Thank you for your help


[2022-01-26 07:03:31.241] [08:03:30] Extension host agent started.
[08:03:30] Started scanning user extensions
[08:03:30] resolveShellEnv(): running (macOS/Linux)
[08:03:30] getUnixShellEnvironment#runAsNode undefined
[08:03:30] getUnixShellEnvironment#noAttach undefined
[08:03:30] getUnixShellEnvironment#env {
  USER: 'nzkc9106',
  VSCODE_WSL_EXT_LOCATION: '/mnt/c/Users/nzkc9106/.vscode/extensions/ms-vscode-remote.remote-wsl-0.63.13',
  SHLVL: '0',
  WT_PROFILE_ID: '{2c4de342-38b7-51cf-b940-2309a097f518}',
  HOME: '/home/nzkc9106',
  WSL_DISTRO_NAME: 'Ubuntu',
  LOGNAME: 'nzkc9106',
  VSCODE_WSL_DEBUG_INFO: 'true',
  NAME: 'WX-OR6245151',
  WSL_INTEROP: '/run/WSL/1092_interop',
  _: '/usr/bin/sh',
  TERM: 'xterm-256color',
  PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/System32/Wbem:/mnt/c/windows/System32/WindowsPowerShell/v1.0/:/mnt/c/windows/System32/OpenSSH/:/mnt/c/Program Files/SafeNet/Authentication/SAC/x64:/mnt/c/Program Files/SafeNet/Authentication/SAC/x32:/mnt/c/Program Files (x86)/Sennheiser/SoftphoneSDK/:/mnt/c/Program Files/PuTTY/:/mnt/c/Users/nzkc9106/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/nzkc9106/AppData/Local/Programs/Microsoft VS Code/bin',
  VSCODE_AGENT_FOLDER: '/home/nzkc9106/.vscode-server',
  WT_SESSION: '8f2dce69-3e3e-4cfa-ad06-1d6edba350e9',
  LANG: 'C.UTF-8',
  SHELL: '/bin/bash',
  PWD: '/mnt/c/Users/nzkc9106/AppData/Local/Programs/Microsoft VS Code',
  HOSTTYPE: 'x86_64',
  WSLENV: 'VSCODE_WSL_EXT_LOCATION/up:VSCODE_CLI_REMOTE_ENV/w:ELECTRON_RUN_AS_NODE/w:WT_SESSION::WT_PROFILE_ID',
  VSCODE_INJECT_NODE_MODULE_LOOKUP_PATH: '/home/nzkc9106/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/remote/node_modules',
  VSCODE_CWD: '/mnt/c/Users/nzkc9106/AppData/Local/Programs/Microsoft VS Code',
  ELECTRON_RUN_AS_NODE: '1',
  ELECTRON_NO_ATTACH_CONSOLE: '1'
}
[08:03:30] ExtensionManagementService.refreshReportedCache
[08:03:30] RequestService#request https://az764295.vo.msecnd.net/extensions/marketplace.json
[08:03:30] resolveShellEnv(): running (macOS/Linux)
[08:03:30] getUnixShellEnvironment#shell /bin/bash
[08:03:30] getUnixShellEnvironment#spawn ["-ilc"] '/home/nzkc9106/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/node'  -p '"94d00a236cbd" + JSON.stringify(process.env) + "94d00a236cbd"'
[08:03:31] getUnixShellEnvironment#raw 94d00a236cbd{"SHELL":"/bin/bash","WSL_DISTRO_NAME":"Ubuntu","WT_SESSION":"8f2dce69-3e3e-4cfa-ad06-1d6edba350e9","VSCODE_INJECT_NODE_MODULE_LOOKUP_PATH":"/home/nzkc9106/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/remote/node_modules","ELECTRON_RUN_AS_NODE":"1","NAME":"WX-OR6245151","PWD":"/mnt/c/Users/nzkc9106/AppData/Local/Programs/Microsoft VS Code","LOGNAME":"nzkc9106","HOME":"/home/nzkc9106","LANG":"C.UTF-8","WSL_INTEROP":"/run/WSL/1092_interop","VSCODE_AGENT_FOLDER":"/home/nzkc9106/.vscode-server","TERM":"xterm-256color","USER":"nzkc9106","SHLVL":"0","VSCODE_WSL_DEBUG_INFO":"true","VSCODE_CWD":"/mnt/c/Users/nzkc9106/AppData/Local/Programs/Microsoft VS Code","WSLENV":"VSCODE_WSL_EXT_LOCATION/up:VSCODE_CLI_REMOTE_ENV/w:ELECTRON_RUN_AS_NODE/w:WT_SESSION::WT_PROFILE_ID","VSCODE_WSL_EXT_LOCATION":"/mnt/c/Users/nzkc9106/.vscode/extensions/ms-vscode-remote.remote-wsl-0.63.13","ELECTRON_NO_ATTACH_CONSOLE":"1","XDG_DATA_DIRS":"/usr/local/share:/usr/share:/var/lib/snapd/desktop","PATH":"/home/nzkc9106/.tfenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/System32/Wbem:/mnt/c/windows/System32/WindowsPowerShell/v1.0/:/mnt/c/windows/System32/OpenSSH/:/mnt/c/Program Files/SafeNet/Authentication/SAC/x64:/mnt/c/Program Files/SafeNet/Authentication/SAC/x32:/mnt/c/Program Files (x86)/Sennheiser/SoftphoneSDK/:/mnt/c/Program Files/PuTTY/:/mnt/c/Users/nzkc9106/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/nzkc9106/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin","HOSTTYPE":"x86_64","WT_PROFILE_ID":"{2c4de342-38b7-51cf-b940-2309a097f518}","_":"/home/nzkc9106/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/node"}94d00a236cbd

[08:03:31] getUnixShellEnvironment#stderr bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell

[08:03:31] getUnixShellEnvironment#result {
  SHELL: '/bin/bash',
  WSL_DISTRO_NAME: 'Ubuntu',
  WT_SESSION: '8f2dce69-3e3e-4cfa-ad06-1d6edba350e9',
  VSCODE_INJECT_NODE_MODULE_LOOKUP_PATH: '/home/nzkc9106/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/remote/node_modules',
  NAME: 'WX-OR6245151',
  PWD: '/mnt/c/Users/nzkc9106/AppData/Local/Programs/Microsoft VS Code',
  LOGNAME: 'nzkc9106',
  HOME: '/home/nzkc9106',
  LANG: 'C.UTF-8',
  WSL_INTEROP: '/run/WSL/1092_interop',
  VSCODE_AGENT_FOLDER: '/home/nzkc9106/.vscode-server',
  TERM: 'xterm-256color',
  USER: 'nzkc9106',
  SHLVL: '0',
  VSCODE_WSL_DEBUG_INFO: 'true',
  VSCODE_CWD: '/mnt/c/Users/nzkc9106/AppData/Local/Programs/Microsoft VS Code',
  WSLENV: 'VSCODE_WSL_EXT_LOCATION/up:VSCODE_CLI_REMOTE_ENV/w:ELECTRON_RUN_AS_NODE/w:WT_SESSION::WT_PROFILE_ID',
  VSCODE_WSL_EXT_LOCATION: '/mnt/c/Users/nzkc9106/.vscode/extensions/ms-vscode-remote.remote-wsl-0.63.13',
  XDG_DATA_DIRS: '/usr/local/share:/usr/share:/var/lib/snapd/desktop',
  PATH: '/home/nzkc9106/.tfenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/System32/Wbem:/mnt/c/windows/System32/WindowsPowerShell/v1.0/:/mnt/c/windows/System32/OpenSSH/:/mnt/c/Program Files/SafeNet/Authentication/SAC/x64:/mnt/c/Program Files/SafeNet/Authentication/SAC/x32:/mnt/c/Program Files (x86)/Sennheiser/SoftphoneSDK/:/mnt/c/Program Files/PuTTY/:/mnt/c/Users/nzkc9106/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/nzkc9106/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin',
  HOSTTYPE: 'x86_64',
  WT_PROFILE_ID: '{2c4de342-38b7-51cf-b940-2309a097f518}',
  _: '/home/nzkc9106/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/node'
}
[08:03:31] Scanned user extensions: 9

[2022-01-26 07:03:31.257] [08:03:30] Error occurred in server
[08:03:30] Error: listen EADDRNOTAVAIL: address not available 127.0.0.1
    at Server.setupListenHandle [as _listen2] (net.js:1301:21)
    at listenInCluster (net.js:1366:12)
    at doListen (net.js:1503:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'EADDRNOTAVAIL',
  errno: -99,
  syscall: 'listen',
  address: '127.0.0.1'
}

[2022-01-26 07:03:31.541] [08:03:31] ExtensionManagementService.refreshControlCache {
  malicious: [
    { id: 'visualstuiocode.emmet' },
    { id: 'joaomoreno.banana' },
    { id: 'JacobeanResearchandDevelopmentLLC.vscode-scxml-preview' },
    { id: 'joaquin6.package-watch' },
    { id: 'KazuoCode.gthubsum' },
    { id: 'MaxGotovkin.tslens' }
  ],
  unsupportedPreReleaseExtensions: {
    'github.vscode-pull-request-github-insiders': {
      id: 'github.vscode-pull-request-github',
      displayName: 'GitHub Pull Requests and Issues'
    },
    'ms-vscode-remote.remote-ssh-nightly': { id: 'ms-vscode-remote.remote-ssh', displayName: 'Remote - SSH' },
    'ms-vscode-remote.remote-ssh-edit-nightly': {
      id: 'ms-vscode-remote.remote-ssh-edit',
      displayName: 'Remote - SSH: Editing Configuration Files'
    }
  }
}
[08:03:31] Started scanning user extensions
[08:03:31] Scanned user extensions: 9

[2022-01-26 07:05:02.035] Exiting
[2022-01-26 07:05:02.036] C:\windows\System32\wsl.exe -d Ubuntu -e kill 1095

**Comment by bamurtaugh** [comment]
Thanks for opening! It'd be great to get some more info on your setup:

- What WSL distro are you using?
- Can you provide any repro / setup steps? i.e. how you're starting VS Code and initiating a Remote-WSL connection (are you starting in a WSL terminal, using Remote-WSL command to open a new WSL window directly within VS Code, etc)
