### ISSUE TITLE
Cant conect

### ISSUE THREAD

**Issue by kaiserdj** [microsoft/vscode-remote-release#6275]
Issue Type: <b>Bug</b>

I am trying to connect to an ssh from vscode but it gives me an error only when I try it from vscode:
The command that I use in the terminal to enter and if it works for me:
`ssh hKVoAD7PhvquJZevsw8ZPRVaJlLhHuKW0Kr@shell.hiveos.farm -p 22`

In the vscode I have edited the .ssh/config with the following:
```
Host HiveOs_RIG
     HostName shell.hiveos.farm
     User hKVoAD7PhvquJZevsw8ZPRVaJlLhHuKW0Kr
     port 22

```

Someone could help me?

Extension version: 0.70.0
VS Code version: Code - Insiders 1.64.0-insider (5554b12acf27056905806867f251c859323ff7e9, 2022-02-02T17:16:15.360Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.32GB free)|
|Process Argv|--crash-reporter-id 09b89622-3fe3-4d21-91bb-cc9931a83c26|
|Screen Reader|no|
|VM|29%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstartedc:30421358
vscop940:30404999
vsclayoutctrc:30405799
pythonvsnew555:30426298
vscscmwlcmc:30428972
azactmsal:30432848

```

</details>

**Comment by tanhakabir** [comment]
Could you please share with us the Remote SSH logs? You can find instructions here: https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues

**Comment by kaiserdj** [comment]
Log: 
```
[10:46:10.672] Log Level: 2
[10:46:10.674] remote-ssh@0.70.0
[10:46:10.674] win32 x64
[10:46:10.675] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a22486976654f735f524947227d", attempt 1
[10:46:10.676] "remote.SSH.useLocalServer": false
[10:46:10.676] "remote.SSH.showLoginTerminal": false
[10:46:10.677] "remote.SSH.remotePlatform": {}
[10:46:10.677] "remote.SSH.path": undefined
[10:46:10.677] "remote.SSH.configFile": undefined
[10:46:10.677] "remote.SSH.useFlock": true
[10:46:10.677] "remote.SSH.lockfilesInTmp": false
[10:46:10.677] "remote.SSH.localServerDownload": auto
[10:46:10.677] "remote.SSH.remoteServerListenOnSocket": false
[10:46:10.678] "remote.SSH.showLoginTerminal": false
[10:46:10.678] "remote.SSH.defaultExtensions": []
[10:46:10.678] "remote.SSH.loglevel": 2
[10:46:10.678] "remote.SSH.serverPickPortsFromRange": {}
[10:46:10.678] "remote.SSH.enableDynamicForwarding": true
[10:46:10.678] "remote.SSH.serverInstallPath": {}
[10:46:10.679] SSH Resolver called for host: HiveOs_RIG
[10:46:10.679] Setting up SSH remote "HiveOs_RIG"
[10:46:10.711] Using commit id "5554b12acf27056905806867f251c859323ff7e9" and quality "insider" for server
[10:46:10.716] Install and start server if needed
[10:46:12.216] Checking ssh with "ssh -V"
[10:46:12.261] > OpenSSH_for_Windo
[10:46:12.262] > ws_8.1p1, LibreSSL 3.0.2

[10:46:12.267] Running script with connection command: ssh -T -D 56018 "HiveOs_RIG" bash
[10:46:12.270] Terminal shell path: C:\Windows\System32\cmd.exe
[10:46:12.530] > ]0;C:\Windows\System32\cmd.exe
[10:46:12.530] Got some output, clearing connection timeout
[10:46:13.146] > exec request failed on channel 2
[10:46:14.426] "install" terminal command done
[10:46:14.426] Install terminal quit with output: ]0;C:\Windows\System32\cmd.exeexec request failed on channel 2
[10:46:14.427] Received install output: ]0;C:\Windows\System32\cmd.exeexec request failed on channel 2
[10:46:14.428] Failed to parse remote port from server output
[10:46:14.429] Resolver error: Error: 
	at Function.Create (c:\Users\gonfe\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:430425)
	at Object.t.handleInstallOutput (c:\Users\gonfe\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:429068)
	at Object.t.tryInstall (c:\Users\gonfe\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:524212)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\gonfe\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:487216
	at async Object.t.withShowDetailsEvent (c:\Users\gonfe\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:490561)
	at async Object.t.resolve (c:\Users\gonfe\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:488295)
	at async c:\Users\gonfe\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:564197
[10:46:14.435] ------
```

**Comment by tanhakabir** [comment]
Are you able to run `ssh -T -D 56018 "HiveOs_RIG"` on your terminal?

**Comment by kaiserdj** [comment]
It does connect, but it has problems using the -t "Disable pseudo-terminal allocation" parameter.

**Comment by tanhakabir** [comment]
What are the errors you see using `-T`?

We need `-T` to successfully connect.

**Comment by kaiserdj** [comment]
with that option I can not write:

https://user-images.githubusercontent.com/5487950/152603582-0c6222f0-e3dd-43d0-9437-c6d10c42980b.mp4

**Comment by tanhakabir** [comment]
I'm not exactly sure why you're seeing what you are seeing with the `-T` flag. But unfortunately we need that flag to work to be able to connect.

We had some issues in the past about the `-T` flag: https://github.com/microsoft/vscode-remote-release/issues/5683 and https://github.com/microsoft/vscode-remote-release/issues/6078

I'll mark this as a feature request for now.

@roblourens seeing a couple issues about `-T` flags now. What are your thoughts?

**Comment by moonlightsh** [comment]
@tanhakabir  seems I got the same issue with the same log output.  I found remote-ssh can't connect the server until I reboot my computer or abort all running VScode and restart it as Administrator.

**Comment by roblourens** [comment]
@tanhakabir I wonder whether the `-T` flag is behind what we see with the fish shell. We could add an experimental setting to disable that flag. But need to understand its behavior some more.

**Comment by tanhakabir** [comment]
@roblourens I'm not sure ensuring that no pseudo terminals are used allows for fish to connect successfully

**Comment by paperdave** [comment]
`-T` doesnt seem to work when my shell is set to fish. it works when i set it bash. this is very annoying.

**Comment by roblourens** [comment]
Merging into https://github.com/microsoft/vscode-remote-release/issues/6078
