### ISSUE TITLE
Remote-SSH: Cannot connect from mac to windows 10

### ISSUE THREAD

**Issue by pmcl77** [microsoft/vscode-remote-release#6278]
Hi,

I cannot connect with Remote-SSH to my Windows 10 Pro server which is running OpenSSH on WSL2. I have no issues connection on the cli and in other programs, but with VScode it just does not work. (NB: Same thing for Remote-Containers)

- VSCode Version:
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:38:17.605Z (1 mo ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0

- Local OS Version:
MacOS Big Sur 11.6 20G165
Macbook Air (M1, 2020)

- Remote OS Version:
Windows 10 Pro 
1909
18363.1256

- Remote Extension/Connection Type: 
Remote-SSH v0.70.0

- Logs:
Note: SSH remote "pd" is configured in my .ssh/config and works on the CLI, authentication with keys.

[22:44:41.564] Log Level: 2
[22:44:41.564] remote-ssh@0.70.0
[22:44:41.564] darwin arm64
[22:44:41.565] SSH Resolver called for "ssh-remote+pd", attempt 1
[22:44:41.565] "remote.SSH.useLocalServer": true
[22:44:41.565] "remote.SSH.path": undefined
[22:44:41.565] "remote.SSH.configFile": undefined
[22:44:41.565] "remote.SSH.useFlock": true
[22:44:41.565] "remote.SSH.lockfilesInTmp": false
[22:44:41.566] "remote.SSH.localServerDownload": auto
[22:44:41.566] "remote.SSH.remoteServerListenOnSocket": false
[22:44:41.566] "remote.SSH.showLoginTerminal": false
[22:44:41.566] "remote.SSH.defaultExtensions": []
[22:44:41.566] "remote.SSH.loglevel": 2
[22:44:41.566] "remote.SSH.serverPickPortsFromRange": {}
[22:44:41.566] "remote.SSH.enableDynamicForwarding": true
[22:44:41.566] "remote.SSH.serverInstallPath": {}
[22:44:41.567] SSH Resolver called for host: pd
[22:44:41.567] Setting up SSH remote "pd"
[22:44:41.568] Acquiring local install lock: /var/folders/8z/t4y4yxt533d0ptjygf336pbw0000gn/T/vscode-remote-ssh-4d4e53d1-install.lock
[22:44:41.574] Looking for existing server data file at /Users/phil/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-4d4e53d1-899d46d82c4c95423fb7e10e68eba52050e30ba3-0.70.0/data.json
[22:44:41.574] Using commit id "899d46d82c4c95423fb7e10e68eba52050e30ba3" and quality "stable" for server
[22:44:41.576] Install and start server if needed
[22:44:41.579] PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/phil/bin/docker
[22:44:41.579] Checking ssh with "ssh -V"
[22:44:41.582] > OpenSSH_8.1p1, LibreSSL 2.7.3

[22:44:41.584] askpass server listening on /var/folders/8z/t4y4yxt533d0ptjygf336pbw0000gn/T/vscode-ssh-askpass-cb929383035941e1be167a3e51f4656b0431414a.sock
[22:44:41.584] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/8z/t4y4yxt533d0ptjygf336pbw0000gn/T/vscode-ssh-askpass-1c3a21d52bd066a15f23fda64e8e9a6ce5740650.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","62768","-o","ConnectTimeout=15","pd"],"dataFilePath":"/Users/phil/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-4d4e53d1-899d46d82c4c95423fb7e10e68eba52050e30ba3-0.70.0/data.json"}
[22:44:41.584] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/phil/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/phil/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/8z/t4y4yxt533d0ptjygf336pbw0000gn/T/vscode-ssh-askpass-cb929383035941e1be167a3e51f4656b0431414a.sock"}
[22:44:41.584] Spawned 10644
[22:44:41.644] > local-server-1> Spawned ssh, pid=10648
[22:44:41.646] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[22:44:41.791] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:e//eYzqK8c+abcde...
[22:44:42.177] stderr> Authenticated to 192.168.0.11 ([192.168.0.11]:22).
[22:44:42.216] > Microsoft Windows [Version 10.0.18363.1256]
> (c) 2019 Microsoft Corporation. Alle Rechte vorbehalten.
> 
> phili@PHIL-DESKTOP C:\Users\phili>echo 'ready: 22f63d14b337'
> 'ready: 22f63d14b337'
> 
> phili@PHIL-DESKTOP C:\Users\phili>
[22:44:42.222] > uname -rsv
> 
> phili@PHIL-DESKTOP C:\Users\phili>
[22:44:42.223] stderr> Der Befehl "uname" ist entweder falsch geschrieben oder
[22:44:42.223] stderr> konnte nicht gefunden werden.
[22:44:58.587] Terminating local server
[22:44:58.589] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/phil/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:430551)
	at Timeout._onTimeout (/Users/phil/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:475197)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[22:44:58.591] Local server exit: 15
[22:44:58.594] ------

Thanks for help!

**Comment by tanhakabir** [comment]
Thanks for submitting the issue! The issue was with how were were programmatically parsing the error and was expecting the error to be in English localization. I'll have a fix for this out in tomorrow's pre-release of the extension!

**Comment by pmcl77** [comment]
thank you @tanhakabir ! Will I be able to download the pre-release on github?

**Comment by tanhakabir** [comment]
You'll see the option to switch to the Pre-Release version of the extension on the extension page:
![image](https://user-images.githubusercontent.com/12758612/152610583-76ab3486-42e8-4e34-9363-193c935820e1.png)

**Comment by pmcl77** [comment]
Thanks @tanhakabir, I switched to v0.73.2022020215 and reloaded, still the same, can't connect to remote SSH/Containers unfortunately...

**Comment by tanhakabir** [comment]
Sorry the fix probably wasn't out yet then. Try updating to `v0.73.2022020715`

**Comment by pmcl77** [comment]
@tanhakabir it works with that version! 🙂
