### ISSUE TITLE
Cannot connect from windows 10 to ubuntu server 

### ISSUE THREAD

**Issue by Cby19961020** [microsoft/vscode-remote-release#6283]
- VSCode Version: 1.64
- Local OS Version: Windows 10 21H2
- Remote OS Version: Linux
- Remote Extension/Connection Type: SSH/Docker/WSL SSH
- Logs:
gzip: skipping: <stdin>: corrupted -- incomplete deflate data
> gzip: abort: internal threads error
> tar: Unexpected EOF in archive
> tar: Unexpected EOF in archive
> tar: Error is not recoverable: exiting now
[09:57:15.624] > 
> ERROR: tar exited with non-0 exit code: 0
> Already attempted local download, failing
> 1187c5c17cd3: start
> exitCode==37==
> listeningOn====
> osReleaseId==centos==
> arch==x86_64==
> tmpDir==/run/user/22236==
> platform==linux==
> unpackResult==error==
> didLocalDownload==1==
> downloadTime====
> installTime==52==
> extInstallTime====
> serverStartTime====
> 1187c5c17cd3: end
[09:57:15.625] Received install output: 
exitCode==37==
listeningOn====
osReleaseId==centos==
arch==x86_64==
tmpDir==/run/user/22236==
platform==linux==
unpackResult==error==
didLocalDownload==1==
downloadTime====
installTime==52==
extInstallTime====
serverStartTime====

[09:57:15.626] Resolver error: Error: Failed to install the VS Code ServerResolver

Does this issue occur when you try this locally?: Yes, when working on my other desktop ssh went through
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by tanhakabir** [comment]
Would you be able to share the entire log with us?

**Comment by Cby19961020** [comment]
[15:01:58.574] Showing password prompt
[15:02:05.445] Got password response
[15:02:05.445] "install" wrote data to terminal: "************"
[15:02:05.445] > 
[15:02:05.445] > 9d29f6ccf9cd: running
[15:02:05.446] > Acquiring lock on /folk/bchang/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9/vscode-remote-lock.bchang.5554b12acf27056905806867f251c859323ff7e9
[15:02:05.446] > Installing to /folk/bchang/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9...
[15:02:05.446] > 9d29f6ccf9cd%%1%%    
> Downloading with wget
[15:02:05.446] > wget download failed
[15:02:05.446] > 2022-02-04 15:01:29 URL:https://az764295.vo.msecnd.net/stable/5554b12acf27056905806867f251c859323ff7e9/vscode-server-linux-x64.tar.gz [54607867/54607867] -> "vscode-server.tar.gz" [1]
> printenv:
[15:02:05.446] >     XDG_SESSION_ID=235021
>     SHELL=/bin/bash
>     SSH_CLIENT=128.224.72.223 54376 22
>     USER=bchang
>     VSCODE_AGENT_FOLDER=/folk/bchang/.vscode-server
>     PATH=/usr/local/bin:/usr/bin
>     MAIL=/var/mail/bchang
>     PWD=/folk/bchang/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9
>     HOME=/folk/bchang
>     SHLVL=2
>     LOGNAME=bchang
>     SSH_CONNECTION=128.224.72.223 54376 128.224.145.95 22
>     XDG_RUNTIME_DIR=/run/user/22236
>     _=/usr/bin/printenv
>     OLDPWD=/folk/bchang
> Trigger local server download
> 9d29f6ccf9cd:trigger_server_download
> platform==linux==
> vscodeArch==x64==
> destFolder==/folk/bchang/.vscode-server/bin/==
> destFolder2==5554b12acf27056905806867f251c859323ff7e9==
> 9d29f6ccf9cd:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /folk/bchang/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9/vscode-scp-done.flag and vscode-server.tar.gz to exist
> 
[15:02:05.447] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/folk/bchang/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9"}
[15:02:05.447] Downloading VS Code server locally...
[15:02:12.156] Downloaded VS Code server to c:\Users\bchang\AppData\Local\Temp\769a0e6d-a98f-4cae-82bd-b4a55397a82d
[15:02:12.157] Renamed VS Code server to c:\Users\bchang\AppData\Local\Temp\vscode_server_1644004932156\vscode-server.tar.gz
[15:02:12.159] Checking ssh with "ssh -V"
[15:02:12.202] > OpenSSH_for_Wind
[15:02:12.202] > ows_8.1p1, LibreSSL 3.0.2

[15:02:12.205] Testing scp with "scp"
[15:02:12.252] scp exited with code: 1
[15:02:12.252] Got stderr from scp: usage: scp [-346BCpqrTv] [-c cipher] [-F ssh_config] [-i identity_file]
            [-J destination] [-l limit] [-o ssh_option] [-P port]
            [-S program] source ... target
[15:02:12.252] Copying file to remote with scp "vscode-server.tar.gz" "vscode-scp-done.flag" "yow-cgts1-lx.wrs.com":"/folk/bchang/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9"
[15:02:12.252] Using cwd: file:///c%3A/Users/bchang/AppData/Local/Temp/vscode_server_1644004932156
[15:02:12.252] Terminal shell path: C:\windows\System32\cmd.exe
[15:02:12.486] > ]0;C:\windows\System32\cmd.exe
[15:02:13.069] > bchang@yow-cgts1-lx.wrs.com's password: 
[15:02:13.069] Showing password prompt
[15:02:19.115] Got password response
[15:02:19.115] "Copy server to host" wrote data to terminal: "************"
[15:02:19.154] > 
[15:02:19.330] > vscode-server.tar.gz                            0%    0     0.0KB/s   --:-- ETA
[15:02:20.379] > vscode-server.tar.gz                            4% 2416KB   2.3MB/s   00:22 ETA
[15:02:21.460] > vscode-server.tar.gz                            6% 3312KB   2.1MB/s   00:23 ETA
[15:02:22.458] > vscode-server.tar.gz                            8% 4464KB   2.0MB/s   00:23 ETA
[15:02:23.455] > vscode-server.tar.gz                           10% 5616KB   1.9MB/s   00:24 ETA
[15:02:24.459] > vscode-server.tar.gz                           12% 6768KB   1.8MB/s   00:24 ETA
[15:02:25.454] > vscode-server.tar.gz                           14% 7920KB   1.8MB/s   00:25 ETA
[15:02:26.455] > vscode-server.tar.gz                           17% 9072KB   1.7MB/s   00:25 ETA
[15:02:27.543] > vscode-server.tar.gz                           18% 9840KB   1.6MB/s   00:26 ETA
[15:02:28.461] > vscode-server.tar.gz                           20%   10MB   1.5MB/s   00:27 ETA
[15:02:29.496] > vscode-server.tar.gz                           22%   12MB   1.5MB/s   00:27 ETA
[15:02:30.541] > vscode-server.tar.gz                           24%   13MB   1.5MB/s   00:27 ETA
[15:02:31.464] > vscode-server.tar.gz                           26%   14MB   1.4MB/s   00:27 ETA
[15:02:31.662] > bchang@yow-cgts1-lx.wrs.com's password:
> 9d29f6ccf9cd: running
> Acquiring lock on /folk/bchang/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9/vscode-remote-lock.bchang.5554b12acf27056905806867f251c859323ff7e9
> Installing to /folk/bchang/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9...
> 9d29f6ccf9cd%%1%%
> Downloading with wget
> wget download failed
> 2022-02-04 15:01:29 URL:https://az764295.vo.msecnd.net/stable/5554b12acf27056905806867f251c859323ff7e9/vscode-server-linux-x64.tar.gz [54607867/54607867] -> "vscode-server.tar.gz" [1]
> printenv:
>     XDG_SESSION_ID=235021
>     SHELL=/bin/bash
>     SSH_CLIENT=128.224.72.223 54376 22
>     USER=bchang
>     VSCODE_AGENT_FOLDER=/folk/bchang/.vscode-server
>     PATH=/usr/local/bin:/usr/bin
>     MAIL=/var/mail/bchang
>     PWD=/folk/bchang/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9
>     HOME=/folk/bchang
>     SHLVL=2
>     LOGNAME=bchang
>     SSH_CONNECTION=128.224.72.223 54376 128.224.145.95 22
>     XDG_RUNTIME_DIR=/run/user/22236
>     _=/usr/bin/printenv
>     OLDPWD=/folk/bchang
> Trigger local server download
> 9d29f6ccf9cd:trigger_server_download
> platform==linux==
> vscodeArch==x64==
> destFolder==/folk/bchang/.vscode-server/bin/==
> destFolder2==5554b12acf27056905806867f251c859323ff7e9==
> 9d29f6ccf9cd:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /folk/bchang/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9/vscode-scp-done.flag and vscode-server.tar.gz to exist
> 
> 
> 
> 
> 
> 
[15:02:32.499] > vscode-server.tar.gz                           28%   15MB   1.4MB/s   00:26 ETA
[15:02:33.539] > vscode-server.tar.gz                           30%   16MB   1.4MB/s   00:26 ETA
[15:02:34.472] > vscode-server.tar.gz                           32%   17MB   1.3MB/s   00:26 ETA
[15:02:35.651] > vscode-server.tar.gz                           33%   18MB   1.2MB/s   00:27 ETA
[15:02:36.573] > vscode-server.tar.gz                           35%   18MB   1.2MB/s   00:27 ETA
[15:02:37.579] > vscode-server.tar.gz                           37%   20MB   1.2MB/s   00:26 ETA
[15:02:38.606] > vscode-server.tar.gz                           39%   21MB   1.2MB/s   00:26 ETA
[15:02:39.522] > vscode-server.tar.gz                           41%   22MB   1.2MB/s   00:25 ETA
[15:02:40.675] > vscode-server.tar.gz                           44%   23MB   1.2MB/s   00:24 ETA
[15:02:41.617] > vscode-server.tar.gz                           46%   24MB   1.2MB/s   00:24 ETA
[15:02:42.556] > vscode-server.tar.gz                           47%   25MB   1.2MB/s   00:23 ETA
[15:02:43.765] > vscode-server.tar.gz                           49%   26MB   1.1MB/s   00:23 ETA
[15:02:44.676] > vscode-server.tar.gz                           51%   27MB   1.1MB/s   00:23 ETA
[15:02:45.586] > vscode-server.tar.gz                           53%   28MB   1.1MB/s   00:22 ETA
[15:02:46.599] > vscode-server.tar.gz                           55%   29MB   1.1MB/s   00:21 ETA
[15:02:47.659] > vscode-server.tar.gz                           57%   30MB   1.1MB/s   00:20 ETA
[15:02:48.620] > vscode-server.tar.gz                           59%   31MB   1.1MB/s   00:19 ETA
[15:02:49.653] > vscode-server.tar.gz                           61%   32MB   1.1MB/s   00:18 ETA
[15:02:50.661] > vscode-server.tar.gz                           63%   33MB   1.1MB/s   00:17 ETA
[15:02:51.671] > vscode-server.tar.gz                           65%   34MB   1.1MB/s   00:17 ETA
[15:02:52.633] > vscode-server.tar.gz                           66%   34MB   1.0MB/s   00:17 ETA
[15:02:53.661] > vscode-server.tar.gz                           68%   36MB   1.0MB/s   00:16 ETA
[15:02:54.645] > vscode-server.tar.gz                           70%   37MB   1.0MB/s   00:14 ETA
[15:02:55.757] > vscode-server.tar.gz                           72%   38MB   1.0MB/s   00:13 ETA
[15:02:56.759] > vscode-server.tar.gz                           75%   39MB   1.1MB/s   00:12 ETA
[15:02:57.839] > vscode-server.tar.gz                           77%   40MB   1.1MB/s   00:11 ETA
[15:02:58.831] > vscode-server.tar.gz                           78%   41MB   1.0MB/s   00:11 ETA
[15:02:59.732] > vscode-server.tar.gz                           80%   42MB   1.0MB/s   00:10 ETA
[15:03:00.732] > vscode-server.tar.gz                           82%   43MB   1.0MB/s   00:08 ETA
[15:03:02.298] > vscode-server.tar.gz                           84%   44MB   1.0MB/s   00:07 ETA
[15:03:02.868] > vscode-server.tar.gz                           86%   45MB   1.0MB/s   00:06 ETA
[15:03:03.784] > vscode-server.tar.gz                           88%   46MB   1.0MB/s   00:05 ETA
[15:03:04.798] > vscode-server.tar.gz                           90%   47MB   1.0MB/s   00:04 ETA
[15:03:05.820] > vscode-server.tar.gz                           93%   48MB   1.1MB/s   00:03 ETA
[15:03:07.285] > vscode-server.tar.gz                           94%   49MB   1.0MB/s   00:03 ETA
[15:03:07.841] > vscode-server.tar.gz                           95%   50MB   1.0MB/s   00:02 ETA
[15:03:08.960] > vscode-server.tar.gz                           96%   50MB 969.7KB/s   00:01 ETA
[15:03:09.849] > vscode-server.tar.gz                           98%   51MB 988.1KB/s   00:00 ETA
[15:03:13.471] > vscode-server.tar.gz                           98%   51MB 988.1KB/s   00:00 ETAs
> cp: /folk/bchang/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9/vsc
> ode-server.tar.gz: Disk quota exceeded
[15:03:13.484] > vscode-server.tar.gz                          100%   52MB 985.0KB/s   00:54    
[15:03:13.622] > vscode-scp-done.flag                            0%    0     0.0KB/s   --:-- ETA
[15:03:13.649] > vscode-scp-done.flag                          100%    9     0.3KB/s   00:00    
[15:03:13.664] > 
[15:03:14.963] "Copy server to host" terminal command done
[15:03:15.403] > Found flag and server on host
[15:03:15.486] > 9d29f6ccf9cd%%2%%
> tar --version:   
> tar (GNU tar) 1.26
> Copyright (C) 2011 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[15:03:15.514] > 
[15:03:16.212] > gzip: skipping: <stdin>: corrupted -- invalid deflate data (invalid literal/length code)
> gzip: abort: internal threads error
> tar: Unexpected EOF in archive
> tar: Unexpected EOF in archive
[15:03:16.221] > 
> tar: Error is not recoverable: exiting now
[15:03:16.799] > ERROR: tar exited with non-0 exit code: 0
> Already attempted local download, failing
> 9d29f6ccf9cd: start
> exitCode==37==
> listeningOn====
> osReleaseId==centos==
> arch==x86_64==
> tmpDir==/run/user/22236==
> platform==linux==
> unpackResult==error==
> didLocalDownload==1==
> downloadTime====
> installTime==1333==
> extInstallTime====
> serverStartTime====
> 9d29f6ccf9cd: end
[15:03:16.800] Received install output: 
exitCode==37==
listeningOn====
osReleaseId==centos==
arch==x86_64==
tmpDir==/run/user/22236==
platform==linux==
unpackResult==error==
didLocalDownload==1==
downloadTime====
installTime==1333==
extInstallTime====
serverStartTime====

[15:03:16.801] Resolver error: Error: Failed to install the VS Code Server
	at Function.ServerInstallError (c:\Users\bchang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:430359)
	at u (c:\Users\bchang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:425104)
	at Object.t.handleInstallOutput (c:\Users\bchang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:429101)
	at Object.t.tryInstall (c:\Users\bchang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:524212)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\bchang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:487216
	at async Object.t.withShowDetailsEvent (c:\Users\bchang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:490561)
	at async Object.t.resolve (c:\Users\bchang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:488295)
	at async c:\Users\bchang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:564197
[15:03:16.807] ------




[15:03:17.432] > 
[15:03:18.094] "install" terminal command done
[15:03:18.094] Install terminal quit with output:

**Comment by tanhakabir** [comment]
I'm seeing this error in your logs: `cp: /folk/bchang/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9/vsc
ode-server.tar.gz: Disk quota exceeded`

It looks like you're running into memory issues or other filesystem issues downloading the server zip. 

Are you able to troubleshoot why you're seeing this error?

**Comment by Cby19961020** [comment]
Apologies on a closer investigation this is an issue from the server side. Sorry about the trouble.
