### ISSUE TITLE
Could not establish connection to "RaspberryPi": Cannot find module 'minimist'

### ISSUE THREAD

**Issue by Unstable0** [microsoft/vscode-remote-release#6306]
- VSCode Version: Latest version on MacOS Apple Silicon VSCode Insiders
(Version: 1.65.0-insider
Commit: 0283cec6ec2c2d5ec39006a1048b8dc3ea8bc955
Date: 2022-02-08T05:26:07.941Z (6 hrs ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.4.0)

- Local OS Version: MacOs Monterey beta 12.3
- Remote OS Version: Ubuntu Server LTS (20.04)
- Remote Extension/Connection Type: SSH
- Logs:
[18:52:42.779] Log Level: 2
[18:52:42.779] remote-ssh@0.73.2022020715
[18:52:42.779] darwin arm64
[18:52:42.781] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a225261737062657272795069227d", attempt 1
[18:52:42.781] "remote.SSH.useLocalServer": true
[18:52:42.782] "remote.SSH.path": undefined
[18:52:42.782] "remote.SSH.configFile": undefined
[18:52:42.783] "remote.SSH.useFlock": true
[18:52:42.783] "remote.SSH.lockfilesInTmp": false
[18:52:42.783] "remote.SSH.localServerDownload": auto
[18:52:42.783] "remote.SSH.remoteServerListenOnSocket": false
[18:52:42.783] "remote.SSH.showLoginTerminal": false
[18:52:42.783] "remote.SSH.defaultExtensions": []
[18:52:42.783] "remote.SSH.loglevel": 2
[18:52:42.783] "remote.SSH.enableDynamicForwarding": true
[18:52:42.783] "remote.SSH.enableRemoteCommand": false
[18:52:42.784] "remote.SSH.serverPickPortsFromRange": {}
[18:52:42.784] "remote.SSH.serverInstallPath": {}
[18:52:42.789] SSH Resolver called for host: RaspberryPi
[18:52:42.789] Setting up SSH remote "RaspberryPi"
[18:52:42.791] Acquiring local install lock: /var/folders/_3/8q4yycds05z2_7bk96p5dgy40000gn/T/vscode-remote-ssh-b93131de-install.lock
[18:52:42.792] Looking for existing server data file at /Users/jirayuadisakdechakul/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-b93131de-0283cec6ec2c2d5ec39006a1048b8dc3ea8bc955-0.73.2022020715/data.json
[18:52:42.793] Using commit id "0283cec6ec2c2d5ec39006a1048b8dc3ea8bc955" and quality "insider" for server
[18:52:42.796] Install and start server if needed
[18:52:42.801] PATH: /Library/Frameworks/Python.framework/Versions/3.10/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
[18:52:42.801] Checking ssh with "ssh -V"
[18:52:42.806] > OpenSSH_8.6p1, LibreSSL 3.3.5

[18:52:42.809] askpass server listening on /var/folders/_3/8q4yycds05z2_7bk96p5dgy40000gn/T/vscode-ssh-askpass-103193a0000cc9fcc0d426a670a30b18cedca59c.sock
[18:52:42.809] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/_3/8q4yycds05z2_7bk96p5dgy40000gn/T/vscode-ssh-askpass-8346da0b7b2077490c4a83693a4159646759b16e.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","55473","-o","ConnectTimeout=15","RaspberryPi"],"serverDataFolderName":".vscode-server-insiders","dataFilePath":"/Users/jirayuadisakdechakul/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-b93131de-0283cec6ec2c2d5ec39006a1048b8dc3ea8bc955-0.73.2022020715/data.json"}
[18:52:42.809] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/jirayuadisakdechakul/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.73.2022020715/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/jirayuadisakdechakul/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.73.2022020715/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/_3/8q4yycds05z2_7bk96p5dgy40000gn/T/vscode-ssh-askpass-103193a0000cc9fcc0d426a670a30b18cedca59c.sock"}
[18:52:42.810] Spawned 8602
[18:52:42.882] > local-server-1> Spawned ssh, pid=8608
[18:52:42.889] stderr> OpenSSH_8.6p1, LibreSSL 3.3.5
[18:52:43.074] stderr> debug1: Server host key: ssh-ed25519 SHA256:rSLojCGX1i/3YdCpG/qtP75TxFe/oatpT+FGaa0Faqs
[18:52:43.173] Got askpass request: {"request":"root@home.biggybig.xyz's password:"}
[18:52:43.173] Showing password prompt
[18:52:43.174] Listening for interwindow password on /var/folders/_3/8q4yycds05z2_7bk96p5dgy40000gn/T/vscode-ssh-askpass-5e5fd8ae29f35dafa9122d748fc95b47756ef632.sock
[18:52:43.174] Writing password prompt to globalState
[18:52:56.090] Got password response
[18:52:56.091] Interactor gave response: ************
[18:52:56.092] Cleaning up other-window auth server
[18:52:58.331] stderr> Permission denied, please try again.
[18:52:58.424] Got askpass request: {"request":"root@home.biggybig.xyz's password:"}
[18:52:58.424] Showing password prompt
[18:52:58.425] Listening for interwindow password on /var/folders/_3/8q4yycds05z2_7bk96p5dgy40000gn/T/vscode-ssh-askpass-fc2844e95d91969a8c064d08e137f3c77591a174.sock
[18:52:58.425] Writing password prompt to globalState
[18:53:02.748] Got password response
[18:53:02.748] Interactor gave response: *************
[18:53:02.748] Cleaning up other-window auth server
[18:53:02.909] stderr> Authenticated to home.biggybig.xyz ([171.5.27.138]:22).
[18:53:05.012] > Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-1050-raspi aarch64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   System information as of Tue Feb  8 11:53:03 UTC 2022
> 
>   System load:  0.02              Temperature:            37.5 C
>   Usage of /:   5.2% of 58.27GB   Processes:              136
>   Memory usage: 3%                Users logged in:        0
>   Swap usage:   0%                IPv4 address for wlan0: 192.168.1.123
> 
>  * Super-optimized for small spaces - read how we shrank the memory
>    footprint of MicroK8s to make it the smallest full K8s around.
> 
>    https://ubuntu.com/blog/microk8s-memory-optimisation
> 
> 0 updates can be applied immediately.
> 
[18:53:05.041] > ready: 38b0275eba82
[18:53:05.050] > Linux 5.4.0-1050-raspi #56-Ubuntu SMP PREEMPT Thu Jan 13 13:09:35 UTC 2022
[18:53:05.050] Platform: linux
[18:53:05.126] > 38b0275eba82: running
[18:53:05.189] > Acquiring lock on /root/.vscode-server-insiders/bin/0283cec6ec2c2d5ec39006a1048b8dc3ea8bc955/vscode-remote-lock.root.0283cec6ec2c2d5ec39006a1048b8dc3ea8bc955
[18:53:05.200] > Found existing installation at /root/.vscode-server-insiders/bin/0283cec6ec2c2d5ec39006a1048b8dc3ea8bc955...
> Checking /root/.vscode-server-insiders/.0283cec6ec2c2d5ec39006a1048b8dc3ea8bc955.log and /root/.vscode-server-insiders/.0283cec6ec2c2d5ec39006a1048b8dc3ea8bc955.pid for a running server
[18:53:05.205] > Looking for server with pid: 9077
[18:53:05.242] > Starting server with command... /root/.vscode-server-insiders/bin/0283cec6ec2c2d5ec39006a1048b8dc3ea8bc955/bin/code-server-insiders --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0    &> "/root/.vscode-server-insiders/.0283cec6ec2c2d5ec39006a1048b8dc3ea8bc955.log" < /dev/null
> printenv:
[18:53:05.247] >     SHELL=/bin/bash
>     PWD=/root
>     LOGNAME=root
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/root
>     LANG=C.UTF-8
>     VSCODE_AGENT_FOLDER=/root/.vscode-server-insiders
>     SSH_CONNECTION=171.5.27.138 55474 192.168.1.123 22
>     XDG_SESSION_CLASS=user
>     USER=root
>     SHLVL=1
>     XDG_SESSION_ID=19
>     XDG_RUNTIME_DIR=/run/user/0
>     SSH_CLIENT=171.5.27.138 55474 22
>     XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/0/bus
>     _=/usr/bin/printenv
[18:53:05.266] > Spawned remote server: 10229
[18:53:05.278] > Waiting for server log...
[18:53:05.323] > Waiting for server log...
[18:53:05.369] > Waiting for server log...
[18:53:05.415] > Waiting for server log...
[18:53:05.462] > Waiting for server log...
[18:53:05.509] > Waiting for server log...
[18:53:05.555] > Waiting for server log...
[18:53:05.603] > Waiting for server log...
[18:53:05.650] > Waiting for server log...
[18:53:05.699] > Waiting for server log...
[18:53:05.744] > Waiting for server log...
[18:53:05.792] > Waiting for server log...
[18:53:05.849] > Waiting for server log...
[18:53:05.886] > Waiting for server log...
[18:53:05.932] > Waiting for server log...
[18:53:05.979] > Waiting for server log...
[18:53:06.027] > Waiting for server log...
[18:53:06.074] > Waiting for server log...
[18:53:06.121] > Waiting for server log...
[18:53:06.168] > Waiting for server log...
[18:53:06.215] > Waiting for server log...
[18:53:06.263] > Waiting for server log...
[18:53:06.310] > Waiting for server log...
[18:53:06.356] > Waiting for server log...
[18:53:06.403] > Waiting for server log...
[18:53:06.450] > Waiting for server log...
[18:53:06.500] > Waiting for server log...
[18:53:06.546] > Waiting for server log...
[18:53:06.595] > Waiting for server log...
[18:53:06.642] > Waiting for server log...
[18:53:06.689] > Waiting for server log...
[18:53:06.736] > Waiting for server log...
[18:53:06.783] > Waiting for server log...
[18:53:06.829] > Waiting for server log...
[18:53:06.876] > Waiting for server log...
[18:53:06.923] > Waiting for server log...
[18:53:06.970] > Waiting for server log...
[18:53:07.017] > Waiting for server log...
[18:53:07.067] > Waiting for server log...
[18:53:07.112] > Waiting for server log...
[18:53:07.160] > Waiting for server log...
[18:53:07.210] > Waiting for server log...
[18:53:07.257] > Waiting for server log...
[18:53:07.304] > Waiting for server log...
[18:53:07.350] > Waiting for server log...
[18:53:07.398] > Waiting for server log...
[18:53:07.445] > Waiting for server log...
[18:53:07.492] > Waiting for server log...
[18:53:07.539] > Waiting for server log...
[18:53:07.587] > Waiting for server log...
[18:53:07.632] > Waiting for server log...
[18:53:07.680] > Waiting for server log...
[18:53:07.729] > Waiting for server log...
[18:53:07.777] > Waiting for server log...
[18:53:07.824] > Waiting for server log...
[18:53:07.871] > Waiting for server log...
[18:53:07.918] > Waiting for server log...
[18:53:07.964] > Waiting for server log...
[18:53:08.012] > Waiting for server log...
[18:53:08.059] > Waiting for server log...
[18:53:08.106] > Waiting for server log...
[18:53:08.153] > Waiting for server log...
[18:53:08.200] > Waiting for server log...
[18:53:08.246] > Waiting for server log...
[18:53:08.294] > Waiting for server log...
[18:53:08.340] > Waiting for server log...
[18:53:08.387] > Waiting for server log...
[18:53:08.434] > Waiting for server log...
[18:53:08.481] > Waiting for server log...
[18:53:08.529] > Waiting for server log...
[18:53:08.577] > Waiting for server log...
[18:53:08.624] > Waiting for server log...
[18:53:08.672] > Waiting for server log...
[18:53:08.718] > Waiting for server log...
[18:53:08.766] > Waiting for server log...
[18:53:08.812] > Waiting for server log...
[18:53:08.859] > Waiting for server log...
[18:53:08.905] > Waiting for server log...
[18:53:08.953] > Waiting for server log...
[18:53:09.000] > Waiting for server log...
[18:53:09.047] > Waiting for server log...
[18:53:09.093] > Waiting for server log...
[18:53:09.140] > Waiting for server log...
[18:53:09.187] > Waiting for server log...
[18:53:09.235] > Waiting for server log...
[18:53:09.281] > Waiting for server log...
[18:53:09.327] > Waiting for server log...
[18:53:09.376] > Waiting for server log...
[18:53:09.422] > Waiting for server log...
[18:53:09.468] > Waiting for server log...
[18:53:09.516] > Waiting for server log...
[18:53:09.563] > Waiting for server log...
[18:53:09.610] > Waiting for server log...
[18:53:09.658] > Waiting for server log...
[18:53:09.704] > Waiting for server log...
[18:53:09.751] > Waiting for server log...
[18:53:09.798] > Waiting for server log...
[18:53:09.845] > Waiting for server log...
[18:53:09.891] > Waiting for server log...
[18:53:09.938] > Waiting for server log...
[18:53:09.985] > Waiting for server log...
[18:53:10.033] > Waiting for server log...
[18:53:10.080] > Waiting for server log...
[18:53:10.128] > Waiting for server log...
[18:53:10.172] > Waiting for server log...
[18:53:10.223] > Waiting for server log...
[18:53:10.271] > Waiting for server log...
[18:53:10.318] > Waiting for server log...
[18:53:10.363] > Waiting for server log...
[18:53:10.410] > Waiting for server log...
[18:53:10.458] > Waiting for server log...
[18:53:10.505] > Waiting for server log...
[18:53:10.552] > Waiting for server log...
[18:53:10.600] > Waiting for server log...
[18:53:10.647] > Waiting for server log...
[18:53:10.695] > Waiting for server log...
[18:53:10.742] > Waiting for server log...
[18:53:10.788] > Waiting for server log...
[18:53:10.834] > Waiting for server log...
[18:53:10.880] > Waiting for server log...
[18:53:10.929] > Waiting for server log...
[18:53:10.978] > Waiting for server log...
[18:53:11.024] > Waiting for server log...
[18:53:11.071] > Waiting for server log...
[18:53:11.118] > Waiting for server log...
[18:53:11.166] > Waiting for server log...
[18:53:11.213] > Waiting for server log...
[18:53:11.261] > Waiting for server log...
[18:53:11.308] > Waiting for server log...
[18:53:11.354] > Waiting for server log...
[18:53:11.402] > Waiting for server log...
[18:53:11.451] > Waiting for server log...
[18:53:11.497] > Waiting for server log...
[18:53:11.545] > Waiting for server log...
[18:53:11.593] > Waiting for server log...
[18:53:11.642] > Waiting for server log...
[18:53:11.688] > Waiting for server log...
[18:53:11.737] > Waiting for server log...
[18:53:11.784] > Waiting for server log...
[18:53:11.832] > Waiting for server log...
[18:53:11.878] > Waiting for server log...
[18:53:11.926] > Waiting for server log...
[18:53:11.973] > Waiting for server log...
[18:53:12.023] > Waiting for server log...
[18:53:12.071] > Waiting for server log...
[18:53:12.119] > Waiting for server log...
[18:53:12.165] > Waiting for server log...
[18:53:12.211] > Waiting for server log...
[18:53:12.258] > Waiting for server log...
[18:53:12.305] > Waiting for server log...
[18:53:12.352] > Waiting for server log...
[18:53:12.399] > Waiting for server log...
[18:53:12.446] > Waiting for server log...
[18:53:12.493] > Waiting for server log...
[18:53:12.541] > Waiting for server log...
[18:53:12.588] > Waiting for server log...
[18:53:12.636] > Waiting for server log...
[18:53:12.682] > Waiting for server log...
[18:53:12.729] > Waiting for server log...
[18:53:12.776] > Waiting for server log...
[18:53:12.823] > Waiting for server log...
[18:53:12.869] > Waiting for server log...
[18:53:12.917] > Waiting for server log...
[18:53:12.964] > Waiting for server log...
[18:53:13.012] > Waiting for server log...
[18:53:13.058] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[18:53:13.077] > Server did not start successfully. Full server log at /root/.vscode-server-insiders/.0283cec6ec2c2d5ec39006a1048b8dc3ea8bc955.log >>>
[18:53:13.083] > (node:10239) UnhandledPromiseRejectionWarning: Error: Cannot find module 'minimist'
> Require stack:
> - /root/.vscode-server-insiders/bin/0283cec6ec2c2d5ec39006a1048b8dc3ea8bc955/out/server-main.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at start (/root/.vscode-server-insiders/bin/0283cec6ec2c2d5ec39006a1048b8dc3ea8bc955/out/server-main.js:1:292)
>     at Object.<anonymous> (/root/.vscode-server-insiders/bin/0283cec6ec2c2d5ec39006a1048b8dc3ea8bc955/out/server-main.js:11:28)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:10239) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:10239) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> <<< End of server log
> 38b0275eba82: start
> exitCode==32==
> listeningOn====
> osReleaseId==ubuntu==
> arch==aarch64==
> tmpDir==/run/user/0==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==7802==
> 38b0275eba82: end
[18:53:13.083] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==ubuntu==
arch==aarch64==
tmpDir==/run/user/0==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==7802==

[18:53:13.084] Cannot find module 'minimist'

[18:53:13.085] Terminating local server
[18:53:13.087] Resolver error: Error: Cannot find module 'minimist'

	at Function.ServerInstallError (/Users/jirayuadisakdechakul/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.73.2022020715/out/extension.js:1:585851)
	at d (/Users/jirayuadisakdechakul/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.73.2022020715/out/extension.js:1:578326)
	at Object.t.handleInstallOutput (/Users/jirayuadisakdechakul/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.73.2022020715/out/extension.js:1:582959)
	at Object.e [as tryInstallWithLocalServer] (/Users/jirayuadisakdechakul/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.73.2022020715/out/extension.js:1:624837)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/jirayuadisakdechakul/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.73.2022020715/out/extension.js:1:642927
	at async Object.t.withShowDetailsEvent (/Users/jirayuadisakdechakul/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.73.2022020715/out/extension.js:1:646674)
	at async /Users/jirayuadisakdechakul/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.73.2022020715/out/extension.js:1:623309
	at async b (/Users/jirayuadisakdechakul/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.73.2022020715/out/extension.js:1:619815)
	at async Object.t.resolveWithLocalServer (/Users/jirayuadisakdechakul/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.73.2022020715/out/extension.js:1:622924)
	at async Object.t.resolve (/Users/jirayuadisakdechakul/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.73.2022020715/out/extension.js:1:644284)
	at async /Users/jirayuadisakdechakul/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.73.2022020715/out/extension.js:1:721424
[18:53:13.093] ------

[18:53:13.094] Local server exit: 15

Steps to Reproduce:

1. Connect to a server
2. the error shows

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by Unstable0** [comment]
I tried killing vscode on the host, rebooting the host, erasing every data (reinstall os), uninstalling vscode completely on my mac still wont work. Please help because without vs code I can't work on my projects :(

**Comment by fpoeea** [comment]
+1

**Comment by roblourens** [comment]
Stable vscode should work. Tracking this in https://github.com/microsoft/vscode/issues/142318
