### ISSUE TITLE
SSH from VScode doesn't work but from terminal SSH works fine.

### ISSUE THREAD

**Issue by kochargs** [microsoft/vscode-remote-release#6316]
I was able to SSH remote windows 10 machine but all of a sudden, I am not able to do it anymore.
I can confirm nothing has changed, no update has been done

Source machine is windows 11 and target machine is windows 10
This setup has been working for me for a long time but now all of a sudden, it stopped.
When I SSH to windows 10 ( target ) from pwsh on windows 11 ( source machine )... That SSH connections works absolutely fine but VScode fails everytime.

Here is the trace that i get...

[12:20:57.993] Log Level: 2
[12:20:57.994] remote-ssh@0.73.2022020915
[12:20:57.994] win32 x64
[12:20:57.998] SSH Resolver called for "ssh-remote+192.168.29.92", attempt 1
[12:20:57.999] "remote.SSH.useLocalServer": false
[12:20:57.999] "remote.SSH.showLoginTerminal": false
[12:20:57.999] "remote.SSH.remotePlatform": {"35.238.31.171":"linux","Debian":"linux","gcp":"linux","debian":"linux","192.168.29.92":"windows"}
[12:20:57.999] "remote.SSH.path": C:\Windows\System32\OpenSSH\ssh.exe
[12:20:57.999] "remote.SSH.configFile": undefined
[12:20:58.000] "remote.SSH.useFlock": true
[12:20:58.000] "remote.SSH.lockfilesInTmp": true
[12:20:58.000] "remote.SSH.localServerDownload": always
[12:20:58.000] "remote.SSH.remoteServerListenOnSocket": false
[12:20:58.000] "remote.SSH.showLoginTerminal": false
[12:20:58.000] "remote.SSH.defaultExtensions": []
[12:20:58.000] "remote.SSH.loglevel": 2
[12:20:58.001] "remote.SSH.enableDynamicForwarding": true
[12:20:58.001] "remote.SSH.enableRemoteCommand": true
[12:20:58.001] "remote.SSH.serverPickPortsFromRange": {}
[12:20:58.001] "remote.SSH.serverInstallPath": {}
[12:20:58.026] SSH Resolver called for host: 192.168.29.92
[12:20:58.026] Setting up SSH remote "192.168.29.92"
[12:20:58.031] Using commit id "d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03" and quality "stable" for server
[12:20:58.034] Install and start server if needed
[12:20:58.036] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[12:20:58.061] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[12:20:58.063] Remote command length: 6157/8192 characters
[12:20:58.064] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 49786 "192.168.29.92" powershell
[12:20:58.066] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[12:20:58.277] > ]0;C:\WINDOWS\System32\cmd.exe
[12:20:58.277] Got some output, clearing connection timeout
[12:21:01.044] > 80874133@cwwpvt@192.168.29.92's password: 
[12:21:01.044] Showing password prompt
[12:21:09.602] Got password response
[12:21:09.603] "install" wrote data to terminal: "***********"
[12:21:09.621] > 
[12:21:14.169] > Windows PowerShell
> Copyright (C) Microsoft Corporation. All rights reserved.Try the new cross-platform PowerShell https://aka.ms/pscore6
[12:21:14.188] > 
[12:21:14.349] > PS C:\Users\80874133> 
[12:21:14.532] > 
[12:21:14.550] > PS C:\Users\80874133> $uuid="386f53220e86"
[12:21:14.565] > PS C:\Users\80874133> "${uuid}: running"
> 386f53220e86: running
> PS C:\Users\80874133> "386f53220e86: pauseLog
[12:21:15.504] > PS C:\Users\80874133> main
[12:21:15.514] > 
[12:21:21.747] > gcim : Access denied 
> At line:4 char:6
> + $u_=(gcim win32_process | ? processid -eq $t_).parentprocessid
> +      ~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : PermissionDenied: (root\cimv2:win32_process:String
> g) [Get-CimInstance], CimException
>     + FullyQualifiedErrorId : HRESULT 0x80041003,Microsoft.Management.Infrastruc
> cture.CimCmdlets.GetCimInstanceCommand
> 
> no sshd parent proc
[12:21:21.755] > 
[12:21:23.054] "install" terminal command done
[12:21:23.055] Install terminal quit with output: no sshd parent proc
[12:21:23.055] Received install output: no sshd parent proc
[12:21:23.056] Failed to parse remote port from server output
[12:21:23.056] Resolver error: Error: 
	at Function.Create (c:\Users\kocha\.vscode\extensions\ms-vscode-remote.remote-ssh-0.73.2022020915\out\extension.js:1:585917)
	at Object.t.handleInstallOutput (c:\Users\kocha\.vscode\extensions\ms-vscode-remote.remote-ssh-0.73.2022020915\out\extension.js:1:584569)
	at Object.t.tryInstall (c:\Users\kocha\.vscode\extensions\ms-vscode-remote.remote-ssh-0.73.2022020915\out\extension.js:1:680433)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\kocha\.vscode\extensions\ms-vscode-remote.remote-ssh-0.73.2022020915\out\extension.js:1:643292
	at async Object.t.withShowDetailsEvent (c:\Users\kocha\.vscode\extensions\ms-vscode-remote.remote-ssh-0.73.2022020915\out\extension.js:1:646637)
	at async Object.t.resolve (c:\Users\kocha\.vscode\extensions\ms-vscode-remote.remote-ssh-0.73.2022020915\out\extension.js:1:644371)
	at async c:\Users\kocha\.vscode\extensions\ms-vscode-remote.remote-ssh-0.73.2022020915\out\extension.js:1:721387
[12:21:23.060] ------

I looks duplicate of #2648 but that, unfortunately, hasn't helped me much.... I am out of options and it is important for this to work for me.

Thank you.

**Comment by kochargs** [comment]
idk what was wrong... i had to reboot both client machine and the target machine.... it is now working atleast....
