### ISSUE TITLE
Could not establish connection to a host on Virtual Studio Code

### ISSUE THREAD

**Issue by supernayj** [microsoft/vscode-remote-release#6330]
This is the output when I try to connect to a host using Windows platform. Can someone please help me with this?

[21:17:05.414] Log Level: 2
[21:17:05.416] remote-ssh@0.70.0
[21:17:05.416] win32 x64
[21:17:05.417] SSH Resolver called for "ssh-remote+192.168.1.7", attempt 1
[21:17:05.417] "remote.SSH.useLocalServer": false
[21:17:05.418] "remote.SSH.showLoginTerminal": false
[21:17:05.418] "remote.SSH.remotePlatform": {}
[21:17:05.418] "remote.SSH.path": undefined
[21:17:05.418] "remote.SSH.configFile": undefined
[21:17:05.418] "remote.SSH.useFlock": true
[21:17:05.418] "remote.SSH.lockfilesInTmp": false
[21:17:05.418] "remote.SSH.localServerDownload": auto
[21:17:05.418] "remote.SSH.remoteServerListenOnSocket": false
[21:17:05.418] "remote.SSH.showLoginTerminal": false
[21:17:05.419] "remote.SSH.defaultExtensions": []
[21:17:05.419] "remote.SSH.loglevel": 2
[21:17:05.419] "remote.SSH.serverPickPortsFromRange": {}
[21:17:05.419] "remote.SSH.enableDynamicForwarding": true
[21:17:05.419] "remote.SSH.serverInstallPath": {}
[21:17:05.420] SSH Resolver called for host: 192.168.1.7
[21:17:05.420] Setting up SSH remote "192.168.1.7"
[21:17:05.437] Using commit id "f80445acd5a3dadef24aa209168452a3d97cc326" and quality "stable" for server
[21:17:05.442] Install and start server if needed
[21:17:07.537] Checking ssh with "ssh -V"
[21:17:07.644] > OpenSSH_for_Windows_8.1p1, L
[21:17:07.645] > ibreSSL 3.0.2

[21:17:07.649] Remote command length: 6110/8192 characters
[21:17:07.649] Running script with connection command: ssh -T -D 55822 "192.168.1.7" powershell
[21:17:07.652] Terminal shell path: C:\Windows\System32\cmd.exe
[21:17:07.936] > ]0;C:\Windows\System32\cmd.exe
[21:17:07.936] Got some output, clearing connection timeout
[21:17:10.013] > ssh: connect to host 192.168.1.7 port 22: Connection refused
[21:17:10.041] > The process tried to write to a nonexistent pipe.
[21:17:11.284] "install" terminal command done
[21:17:11.285] Install terminal quit with output: ]0;C:\Windows\System32\cmd.exessh: connect to host 192.168.1.7 port 22: Connection refused
[21:17:11.285] Received install output: ]0;C:\Windows\System32\cmd.exessh: connect to host 192.168.1.7 port 22: Connection refused
[21:17:11.286] Failed to parse remote port from server output
[21:17:11.286] Resolver error: Error: 
	at Function.Create (c:\Users\PC\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:430425)
	at Object.t.handleInstallOutput (c:\Users\PC\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:429068)
	at Object.t.tryInstall (c:\Users\PC\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:524212)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\PC\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:487216
	at async Object.t.withShowDetailsEvent (c:\Users\PC\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:490561)
	at async Object.t.resolve (c:\Users\PC\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:488295)
	at async c:\Users\PC\.vscode\extensions\ms-vscode-remote.remote-ssh-0.70.0\out\extension.js:1:564197
[21:17:11.292] ------

**Comment by etdr** [comment]
Can you connect to this host using ssh yourself, like in PowerShell?

**Comment by roblourens** [comment]
This is just an error directly from ssh

> `ssh: connect to host 192.168.1.7 port 22: Connection refused`

So like @etdr said, please make sure that you have the connection details correct

**Comment by supernayj** [comment]
The first thing I did was downloading the Remote SSH and the Remote SSH Editing Configuration. Then, I run a command "ssh root@192.168.1.7" And whenever I chose Windows as the platform to connect to the host, I get that "Could not establish connection to "192.168.1.5"

Please help me solve this.

**Comment by supernayj** [comment]
> This is just an error directly from ssh
> 
> > `ssh: connect to host 192.168.1.7 port 22: Connection refused`
> 
> So like @etdr said, please make sure that you have the connection details correct

**Comment by roblourens** [comment]
Can you connect to that address with ssh through a terminal?
