### ISSUE TITLE
Cannot connect to Ubuntu 16.04 with SSH

### ISSUE THREAD

**Issue by jnooree** [microsoft/vscode-remote-release#6333]
- VSCode Version: `1.64.2`
- Local OS Version: macOS `11.6.3`
- Remote OS Version: Linux Ubuntu 16.04.7 LTS
- Remote Extension/Connection Type: SSH
- Logs:
```[11:23:19.106] stderr> debug1: mux_client_request_session: master session id: 19
[11:23:19.285] > ready: e0ef979a9b22
[11:23:19.296] > Linux 4.4.0-218-generic #251-Ubuntu SMP Thu Dec 2 09:48:54 UTC 2021
[11:23:19.296] Platform: linux
[11:23:19.312] > Already attempted local download, failing
[11:23:19.312] stderr> bash: line 2: fail_with_exitcode: command not found
[11:23:19.312] stderr> bash: line 3: syntax error near unexpected token `elif'
[11:23:19.312] stderr> bash: line 3: `	elif [[ $ALLOW_CLIENT_DOWNLOAD == "1" ]]; then'
[11:23:19.316] > e0ef979a9b22: running
[11:23:19.333] stderr> cat: '/usr/libx32/libstdc++.so.6'$'\n''/usr/lib/x86_64-linux-gnu/libstdc++.so.6'$'\n''/usr/lib/i386-linux-gnu/libstdc++.so.6'$'\n''/usr/lib32/libstdc++.so.6': No such file or directory
[11:23:19.335] > Missing GLIBCXX >= 3.4.18!
> Found versions 
[11:23:19.342] stderr> mainScriptWrapper:183: bad math expression: operand expected at `*100 +  '
[11:23:19.344] > local-server-1> ssh child died, shutting down
[11:23:19.346] Local server exit: 0
[11:23:19.346] Received install output: local-server-1> Spawned ssh, pid=65058
OpenSSH_8.8p1, OpenSSL 1.1.1m  14 Dec 2021
ready: e0ef979a9b22
Linux 4.4.0-218-generic #251-Ubuntu SMP Thu Dec 2 09:48:54 UTC 2021
Already attempted local download, failing
bash: line 2: fail_with_exitcode: command not found
bash: line 3: syntax error near unexpected token `elif'
bash: line 3: `	elif [[ $ALLOW_CLIENT_DOWNLOAD == "1" ]]; then'
e0ef979a9b22: running
cat: '/usr/libx32/libstdc++.so.6'$'\n''/usr/lib/x86_64-linux-gnu/libstdc++.so.6'$'\n''/usr/lib/i386-linux-gnu/libstdc++.so.6'$'\n''/usr/lib32/libstdc++.so.6': No such file or directory
Missing GLIBCXX >= 3.4.18!
Found versions 
mainScriptWrapper:183: bad math expression: operand expected at `*100 +  '
local-server-1> ssh child died, shutting down

[11:23:19.346] Stopped parsing output early. Remaining text: local-server-1> Spawned ssh, pid=65058OpenSSH_8.8p1, OpenSSL 1.1.1m  14 Dec 2021ready: e0ef979a9b22Linux 4.4.0-218-generic #251-Ubuntu SMP Thu Dec 2 09:48:54 UTC 2021Already attempted local download, failingbash: line 2: fail_with_exitcode: command not foundbash: line 3: syntax error near unexpected token `elif'bash: line 3: `	elif [[ $ALLOW_CLIENT_DOWNLOAD == "1" ]]; then'e0ef979a9b22: runningcat: '/usr/libx32/libstdc++.so.6'$'\n''/usr/lib/x86_64-linux-gnu/libstdc++.so.6'$'\n''/usr/lib/i386-linux-gnu/libstdc++.so.6'$'\n''/usr/lib32/libstdc++.so.6': No such file or directoryMissing GLIBCXX >= 3.4.18!Found versions mainScriptWrapper:183: bad math expression: operand expected at `*100 +  'local-server-1> ssh child died, shutting down
[11:23:19.347] Failed to parse remote port from server output
[11:23:19.348] Resolver error: Error: 
	at Function.Create (/Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:430425)
	at Object.t.handleInstallOutput (/Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:429068)
	at Object.e [as tryInstallWithLocalServer] (/Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:469079)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:486771
	at async Object.t.withShowDetailsEvent (/Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:490561)
	at async /Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:467603
	at async E (/Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:464111)
	at async Object.t.resolveWithLocalServer (/Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:467218)
	at async Object.t.resolve (/Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:488171)
	at async /Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:564197
[11:23:19.350] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"1","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"UnparsableOutput","exitCodeLabel":""},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":455,"timing.preSshTime":36,"timing.establishSshTime":387}}
[11:23:19.351] ------
```

Steps to Reproduce:

1. Try to connect to Ubuntu 16.04 remote.
2. Failure.

**NOTE**: Available to connect to Ubuntu 20.04 remotes.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by jnooree** [comment]
Thank you very much! This does works as a temporary measure.

**Comment by curoky** [comment]
Thank you very much! It took me a long time to troubleshooting. 👍🏻

**Comment by tanhakabir** [comment]
@jnooree could you also paste the missing first half of your log as well?

**Comment by tanhakabir** [comment]
What is the default shell of your remote? Could you try using `bash` instead? Seems similar to https://github.com/microsoft/vscode-remote-release/issues/4090

**Comment by jnooree** [comment]
My (almost) full log. Removed some lines containing sensitive information.
Default shell is zsh (changed with chsh, so seems unrelated to #4090?)

```
[09:40:20.108] Log Level: 1
[09:40:20.109] remote-ssh@0.74.0
[09:40:20.109] darwin x64
[09:40:20.117] SSH Resolver called for "ssh-remote+galaxy2", attempt 1
[09:40:20.117] "remote.SSH.useLocalServer": true
[09:40:20.118] "remote.SSH.path": /usr/local/bin/ssh
[09:40:20.118] "remote.SSH.configFile": /Users/jnooree/.ssh/config
[09:40:20.118] "remote.SSH.useFlock": true
[09:40:20.119] "remote.SSH.lockfilesInTmp": true
[09:40:20.119] "remote.SSH.localServerDownload": off
[09:40:20.119] "remote.SSH.remoteServerListenOnSocket": false
[09:40:20.119] "remote.SSH.showLoginTerminal": true
[09:40:20.119] "remote.SSH.defaultExtensions": []
[09:40:20.120] "remote.SSH.loglevel": 1
[09:40:20.120] "remote.SSH.enableDynamicForwarding": true
[09:40:20.120] "remote.SSH.enableRemoteCommand": false
[09:40:20.120] "remote.SSH.serverPickPortsFromRange": {}
[09:40:20.121] "remote.SSH.serverInstallPath": {}
[09:40:20.133] SSH Resolver called for host: galaxy2
[09:40:20.133] Setting up SSH remote "galaxy2"
[09:40:20.136] Acquiring local install lock: /var/folders/mx/mbvmjqw15bz564h8lhq2f7ww0000gn/T/vscode-remote-ssh-09479819-install.lock
[09:40:20.138] Looking for existing server data file at /Users/jnooree/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-09479819-f80445acd5a3dadef24aa209168452a3d97cc326-0.74.0/data.json
[09:40:20.138] Using commit id "f80445acd5a3dadef24aa209168452a3d97cc326" and quality "stable" for server
[09:40:20.142] Install and start server if needed
[09:40:20.152] Checking ssh with "/usr/local/bin/ssh -V"
[09:40:20.160] > OpenSSH_8.8p1, OpenSSL 1.1.1m  14 Dec 2021

[09:40:20.164] Using SSH config file "/Users/jnooree/.ssh/config"
[09:40:20.165] askpass server listening on /var/folders/mx/mbvmjqw15bz564h8lhq2f7ww0000gn/T/vscode-ssh-askpass-7cb93d47174d1ae191ed7ebbe5c2d81e681c7b86.sock
[09:40:20.165] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/mx/mbvmjqw15bz564h8lhq2f7ww0000gn/T/vscode-ssh-askpass-78ee0ea7cce3283b8603d51075809c35b51316b3.sock","sshCommand":"/usr/local/bin/ssh","sshArgs":["-v","-T","-D","63272","-o","ConnectTimeout=15","-F","/Users/jnooree/.ssh/config","galaxy2"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/jnooree/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-09479819-f80445acd5a3dadef24aa209168452a3d97cc326-0.74.0/data.json"}
[09:40:20.165] Local server env: {"DISPLAY":"/private/tmp/com.apple.launchd.F4o850SLID/org.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/mx/mbvmjqw15bz564h8lhq2f7ww0000gn/T/vscode-ssh-askpass-7cb93d47174d1ae191ed7ebbe5c2d81e681c7b86.sock"}
[09:40:20.166] Spawned 80732
> Welcome to Ubuntu 16.04.7 LTS (GNU/Linux 4.4.0-218-generic x86_64)
[09:40:20.878] > ready: c1d828b24473
[09:40:20.883] > Linux 4.4.0-218-generic #251-Ubuntu SMP Thu Dec 2 09:48:54 UTC 2021
[09:40:20.883] Platform: linux
[09:40:20.901] stderr> bash: line 1: syntax error near unexpected token `done'
[09:40:20.901] stderr> bash: line 1: `done'
[09:40:20.903] stderr> zsh: parse error near `}'
[09:40:20.904] > Installing to ...
[09:40:20.906] > c1d828b24473%%1%%
[09:40:20.907] stderr> do_host_download:1: command not found: millis
[09:40:21.028] > Downloading with wget
[09:40:21.460] > wget download failed
> https://update.code.visualstudio.com/commit:/server-darwin/stable:
> 2022-02-17 09:40:21 ERROR 404: Not Found.
> c1d828b24473%%2%%
> tar --version:
[09:40:21.461] stderr> do_host_download:21: command not found: printenv_indent
[09:40:21.461] stderr> do_client_download_or_fail:8: command not found: fail_with_exitcode
[09:40:21.461] stderr> do_install:1: command not found: millis
[09:40:21.642] > tar (GNU tar) 1.34
> Copyright (C) 2021 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[09:40:21.644] stderr> tar: This does not look like a tar archive
[09:40:21.672] stderr> 
[09:40:21.672] stderr> gzip: stdin: unexpected end of file
[09:40:21.672] stderr> tar: Child returned status 1
[09:40:21.672] stderr> tar: Error is not recoverable: exiting now
[09:40:21.673] > ERROR: tar exited with non-0 exit code: 0
[09:40:21.673] stderr> do_install:8: command not found: elapsed
[09:40:21.674] stderr> do_client_download_or_fail:8: command not found: fail_with_exitcode
[09:40:21.676] > c1d828b24473%%2%%
> tar --version:

...similar lines repeated multiple times...

do_client_download_or_fail:14: maximum nested function level reached; increase FUNCNEST?
local-server-1> ssh child died, shutting down

[09:40:25.812] Stopped parsing output early. Remaining text: (same text)
[09:40:25.816] Failed to parse remote port from server output
[09:40:25.820] Resolver error: Error: 
	at Function.Create (/Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:585917)
	at Object.t.handleInstallOutput (/Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:584569)
	at Object.e [as tryInstallWithLocalServer] (/Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:624925)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:643015
	at async Object.t.withShowDetailsEvent (/Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:646762)
	at async /Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:623397
	at async b (/Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:619903)
	at async Object.t.resolveWithLocalServer (/Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:623012)
	at async Object.t.resolve (/Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:644372)
	at async /Users/jnooree/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:721503
[09:40:25.824] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"1","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"UnparsableOutput","exitCodeLabel":""},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":5703,"timing.preSshTime":48}}
[09:40:25.826] ------
```

**Comment by curoky** [comment]
I had the same problem, downgraded remote-ssh to previous version 0.70.0 and the problem was solved. And I found that the 0.74.0 version does not have the problem on all machines, it just reproduces in the ubuntu 21.04/22.04 container.

**Comment by jnooree** [comment]
Maybe not? I had no problem connecting Ubuntu 20.04 host. My default shell is also zsh there.

**Comment by tanhakabir** [comment]
There will be a fix for this out in tomorrow's pre-release after 8am PST. Let me know if this fixes it for you.

**Comment by tanhakabir** [comment]
Could you try version `v0.75.2022021815` from the pre-release and let me know if it makes a difference for you?
