### ISSUE TITLE
SSH connection lost after pasting certain UTF-8 text into a Markdown file

### ISSUE THREAD

**Issue by tigerinus** [microsoft/vscode-remote-release#6349]
- VSCode Version:

```
Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

- Local OS Version: `Windows 10`
- Remote OS Version: `RHEL 8`
- Remote Extension/Connection Type: SSH
- Logs: (pasted at the end)

Steps to Reproduce:

1. Connected to SSH Remote via VSCode, with all extensions disabled.
2. Open a new file, select file language to be `Markdown`
3. Paste following text

```
http://localhost:8081

操
```

NOTE: If paste with text without Chinese charactor, it doesn't crash.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No
Does this issue occur when you try this remotely and all extensions are disabled?: Yes

Log:

```
[2022-02-15 22:39:09.250] [exthost] [error] TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
	at c.provideDocumentLinks (c:\Users\xiaoh\.vscode\extensions\vsls-contrib.gistfs-0.3.0\dist\extension.js:51:187466)
	at ee.provideLinks (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:111117)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:128870
	at Ee._withAdapter (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:116602)
	at Ee.$provideDocumentLinks (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:128847)
	at i._doInvokeHandler (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13801)
	at i._invokeHandler (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13485)
	at i._receiveRequest (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:12096)
	at i._receiveOneMessage (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:10825)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:8934
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at s.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:34390
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at s.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
	at a._receiveMessage (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:23583)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:21117
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at _.acceptChunk (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:15833)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:14963
	at Socket.A (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:13838)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
[2022-02-15 22:39:09.485] [exthost] [error] [vsls-contrib.gistfs] provider FAILED
[2022-02-15 22:39:09.485] [exthost] [error] TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
	at c.provideDocumentLinks (c:\Users\xiaoh\.vscode\extensions\vsls-contrib.gistfs-0.3.0\dist\extension.js:51:187466)
	at ee.provideLinks (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:111117)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:128870
	at Ee._withAdapter (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:116602)
	at Ee.$provideDocumentLinks (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:128847)
	at i._doInvokeHandler (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13801)
	at i._invokeHandler (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13485)
	at i._receiveRequest (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:12096)
	at i._receiveOneMessage (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:10825)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:8934
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at s.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:34390
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at s.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
	at a._receiveMessage (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:23583)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:21117
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at _.acceptChunk (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:15833)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:14963
	at Socket.A (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:13838)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
[2022-02-15 22:39:09.485] [exthost] [error] [vsls-contrib.gistfs] provider FAILED
[2022-02-15 22:39:09.485] [exthost] [error] TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
	at c.provideDocumentLinks (c:\Users\xiaoh\.vscode\extensions\vsls-contrib.gistfs-0.3.0\dist\extension.js:51:187466)
	at ee.provideLinks (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:111117)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:128870
	at Ee._withAdapter (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:116602)
	at Ee.$provideDocumentLinks (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:128847)
	at i._doInvokeHandler (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13801)
	at i._invokeHandler (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13485)
	at i._receiveRequest (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:12096)
	at i._receiveOneMessage (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:10825)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:8934
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at s.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:34390
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at s.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
	at a._receiveMessage (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:23583)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:21117
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at _.acceptChunk (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:15833)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:14963
	at Socket.A (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:13838)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
[2022-02-15 22:39:09.485] [exthost] [error] [vsls-contrib.gistfs] provider FAILED
[2022-02-15 22:39:09.485] [exthost] [error] TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
	at c.provideDocumentLinks (c:\Users\xiaoh\.vscode\extensions\vsls-contrib.gistfs-0.3.0\dist\extension.js:51:187466)
	at ee.provideLinks (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:111117)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:128870
	at Ee._withAdapter (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:116602)
	at Ee.$provideDocumentLinks (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:128847)
	at i._doInvokeHandler (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13801)
	at i._invokeHandler (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13485)
	at i._receiveRequest (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:12096)
	at i._receiveOneMessage (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:10825)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:8934
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at s.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:34390
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at s.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
	at a._receiveMessage (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:23583)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:21117
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at _.acceptChunk (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:15833)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:14963
	at Socket.A (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:13838)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
[2022-02-15 22:39:09.485] [exthost] [error] [vsls-contrib.gistfs] provider FAILED
[2022-02-15 22:39:09.485] [exthost] [error] TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
	at c.provideDocumentLinks (c:\Users\xiaoh\.vscode\extensions\vsls-contrib.gistfs-0.3.0\dist\extension.js:51:187466)
	at ee.provideLinks (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:111117)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:128870
	at Ee._withAdapter (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:116602)
	at Ee.$provideDocumentLinks (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:128847)
	at i._doInvokeHandler (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13801)
	at i._invokeHandler (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13485)
	at i._receiveRequest (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:12096)
	at i._receiveOneMessage (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:10825)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:8934
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at s.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:34390
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at s.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
	at a._receiveMessage (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:23583)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:21117
	at l.fire (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
	at _.acceptChunk (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:15833)
	at c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:14963
	at Socket.A (c:\Users\xiaoh\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:13838)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
[2022-02-15 22:39:34.924] [exthost] [info] extension host terminating: renderer closed the socket
[2022-02-15 22:39:34.926] [exthost] [info] Extension host with pid 13744 exiting with code 0
```

**Comment by roblourens** [comment]
Seems like a couple things going on - first it seems like remote extensions are not actually disabled? @sandy081 

Secondly, the extension is probably getting stuck in a loop and blocking communication with the extension host process. Thanks for opening an issue on the extension.

I can't reproduce either issue

**Comment by tigerinus** [comment]
Thanks for looking into this. 

I am also aware that even I let VSCode reload with all extension disabled, one of the extension still got loaded. 

For the actual issue that causes message congestion which eventually broke the connection, I've filed a bug at https://marketplace.visualstudio.com/items?itemName=vsls-contrib.gistfs

Other than the above issue filed elsewhere, I think it's fair to say there are still two issues at vscode: 

1. Why does it still load certain extension when it's told to reload with all extensions disabled?
2. Why does SSH connection get lost when a 3rd party extension plays naughty (other than high CPU/memory/network usage)?

**Comment by sandy081** [comment]
> first it seems like remote extensions are not actually disabled?

Resolver extensions are excluded - @aeschli knows more as he added this.

**Comment by alexdima** [comment]
> 1. Why does it still load certain extension when it's told to reload with all extensions disabled?

I cannot reproduce this. If I use the command `F1 > Developer: Reload With Extensions Disabled` while in a SSH remote window, then the window reloads and the user installed extensions are disabled for me.

> 2. Why does SSH connection get lost when a 3rd party extension plays naughty (other than high CPU/memory/network usage)?

When the extension host process crashes, the connection/socket we have to it closes. We are currently behaving the same way in this case as if internet connection is lost. But I agree, in cases like this, we could use the separate management connection/socket to let the renderer know that the connection is healthy, but the extension host process has crashed.
