### ISSUE TITLE
Regression bug for macOS12 connect to Ubuntu Server

### ISSUE THREAD

**Issue by hijkzzz** [microsoft/vscode-remote-release#6356]
Reproduce Steps:
Remote - SSH v0.74.0
macOS 12
Ubuntu 18.04 Server with openssh-server
Centous 7 server with openssh-server

Then I can't connect to the Ubuntu Server with VSCode for  macOS 12
However I can connect to the CentOS7 Server 
Meanwhile I can use VSCode for Windows 11 to connect the Ubuntu Server

I solve this problem on macOS12 by downgrade the remote-ssh tools to v0.70.0.
This is a serious bug

the failed logs are (0.74 + macOS):

```
[19:14:10.432] Log Level: 2
[19:14:10.433] remote-ssh@0.74.0
[19:14:10.433] darwin x64
[19:14:10.435] SSH Resolver called for "ssh-remote+computelab-304-7022", attempt 1
[19:14:10.436] "remote.SSH.useLocalServer": true
[19:14:10.436] "remote.SSH.path": undefined
[19:14:10.436] "remote.SSH.configFile": undefined
[19:14:10.436] "remote.SSH.useFlock": true
[19:14:10.436] "remote.SSH.lockfilesInTmp": false
[19:14:10.436] "remote.SSH.localServerDownload": auto
[19:14:10.437] "remote.SSH.remoteServerListenOnSocket": false
[19:14:10.437] "remote.SSH.showLoginTerminal": false
[19:14:10.437] "remote.SSH.defaultExtensions": []
[19:14:10.437] "remote.SSH.loglevel": 2
[19:14:10.437] "remote.SSH.enableDynamicForwarding": true
[19:14:10.437] "remote.SSH.enableRemoteCommand": false
[19:14:10.437] "remote.SSH.serverPickPortsFromRange": {}
[19:14:10.438] "remote.SSH.serverInstallPath": {}
[19:14:10.446] SSH Resolver called for host: computelab-304-7022
[19:14:10.446] Setting up SSH remote "computelab-304-7022"
[19:14:10.449] Acquiring local install lock: /var/folders/x5/cqkp4ww55h32p6gv60bflrd00000gn/T/vscode-remote-ssh-3e6a398b-install.lock
[19:14:10.450] Looking for existing server data file at /Users/hujian/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-3e6a398b-f80445acd5a3dadef24aa209168452a3d97cc326-0.74.0/data.json
[19:14:10.450] Using commit id "f80445acd5a3dadef24aa209168452a3d97cc326" and quality "stable" for server
[19:14:10.453] Install and start server if needed
[19:14:10.456] PATH: /Users/hujian/.nvm/versions/node/v14.17.5/bin:/Users/hujian/opt/anaconda3/bin:/Users/hujian/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
[19:14:10.456] Checking ssh with "ssh -V"
[19:14:10.463] > OpenSSH_8.6p1, LibreSSL 2.8.3

[19:14:10.466] askpass server listening on /var/folders/x5/cqkp4ww55h32p6gv60bflrd00000gn/T/vscode-ssh-askpass-49003feec32eaf0af7497c5e030d9ea571d62acb.sock
[19:14:10.467] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/x5/cqkp4ww55h32p6gv60bflrd00000gn/T/vscode-ssh-askpass-5fa8bd94c4de5b8a2c5a87b9bd0ba0997e273233.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","60233","-o","ConnectTimeout=15","computelab-304-7022"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/hujian/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-3e6a398b-f80445acd5a3dadef24aa209168452a3d97cc326-0.74.0/data.json"}
[19:14:10.467] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/x5/cqkp4ww55h32p6gv60bflrd00000gn/T/vscode-ssh-askpass-49003feec32eaf0af7497c5e030d9ea571d62acb.sock"}
[19:14:10.468] Spawned 80097
[19:14:10.584] > local-server-1> Spawned ssh, pid=80105
[19:14:10.586] stderr> OpenSSH_8.6p1, LibreSSL 2.8.3
[19:14:11.368] stderr> debug1: Server host key: ssh-ed25519 SHA256:Wu3omFjAtUl6H3JR7/XL1yAdPtl2mO7cyuulzc/cK78
[19:14:11.369] stderr> Warning: Permanently added '[computelab-304]:7022' (ED25519) to the list of known hosts.
[19:14:12.360] stderr> Authenticated to computelab-304 ([10.32.208.144]:7022).
[19:14:12.937] > Welcome to Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-97-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> This system has been minimized by removing packages and content that are
> not required on a system that users do not log into.
> 
> To restore this content, you can run the 'unminimize' command.
> 
> The programs included with the Ubuntu system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
> applicable law.
> 
> 
> The programs included with the Ubuntu system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
> applicable law.
[19:14:13.207] > ready: 453c595095a7
[19:14:13.405] > Linux 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022
[19:14:13.406] Platform: linux
[19:14:13.597] stderr> bash: line 1: syntax error near unexpected token `done'
[19:14:13.597] stderr> bash: line 1: `done'
[19:14:13.597] stderr> -sh: 4: function: not found
[19:14:13.597] > 453c595095a7: running
[19:14:13.599] stderr> -sh: 74: [[: not found
[19:14:13.602] stderr> -sh: 95: [[: not found
[19:14:13.604] stderr> -sh: 160: Syntax error: "(" unexpected (expecting "then")
[19:14:13.606] stderr> Transferred: sent 18324, received 3976 bytes, in 1.2 seconds
[19:14:13.606] stderr> Bytes per second: sent 14718.5, received 3193.7
[19:14:13.607] > local-server-1> ssh child died, shutting down
[19:14:13.610] Local server exit: 0
[19:14:13.610] Received install output: local-server-1> Spawned ssh, pid=80105
OpenSSH_8.6p1, LibreSSL 2.8.3
debug1: Server host key: ssh-ed25519 SHA256:Wu3omFjAtUl6H3JR7/XL1yAdPtl2mO7cyuulzc/cK78
Warning: Permanently added '[computelab-304]:7022' (ED25519) to the list of known hosts.
Authenticated to computelab-304 ([10.32.208.144]:7022).
Welcome to Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-97-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
This system has been minimized by removing packages and content that are
not required on a system that users do not log into.

To restore this content, you can run the 'unminimize' command.

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.


The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

ready: 453c595095a7
Linux 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022
bash: line 1: syntax error near unexpected token `done'
bash: line 1: `done'
-sh: 4: function: not found
453c595095a7: running
-sh: 74: [[: not found
-sh: 95: [[: not found
-sh: 160: Syntax error: "(" unexpected (expecting "then")
Transferred: sent 18324, received 3976 bytes, in 1.2 seconds
Bytes per second: sent 14718.5, received 3193.7
local-server-1> ssh child died, shutting down

[19:14:13.611] Failed to parse remote port from server output
[19:14:13.611] Resolver error: Error: 
	at Function.Create (/Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:585917)
	at Object.t.handleInstallOutput (/Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:584569)
	at Object.e [as tryInstallWithLocalServer] (/Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:624925)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:643015
	at async Object.t.withShowDetailsEvent (/Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:646762)
	at async /Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:623397
	at async b (/Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:619903)
	at async Object.t.resolveWithLocalServer (/Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:623012)
	at async Object.t.resolve (/Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:644372)
	at async /Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:721503
[19:14:13.615] ------
```

The success logs are (v0.70 + macOS): 

```
[19:14:45.564] Log Level: 2
[19:14:45.566] remote-ssh@0.70.0
[19:14:45.566] darwin x64
[19:14:45.567] SSH Resolver called for "ssh-remote+computelab-304-7022", attempt 1
[19:14:45.567] "remote.SSH.useLocalServer": true
[19:14:45.567] "remote.SSH.path": undefined
[19:14:45.567] "remote.SSH.configFile": undefined
[19:14:45.567] "remote.SSH.useFlock": true
[19:14:45.568] "remote.SSH.lockfilesInTmp": false
[19:14:45.568] "remote.SSH.localServerDownload": auto
[19:14:45.568] "remote.SSH.remoteServerListenOnSocket": false
[19:14:45.568] "remote.SSH.showLoginTerminal": false
[19:14:45.568] "remote.SSH.defaultExtensions": []
[19:14:45.568] "remote.SSH.loglevel": 2
[19:14:45.568] "remote.SSH.serverPickPortsFromRange": {}
[19:14:45.569] "remote.SSH.enableDynamicForwarding": true
[19:14:45.569] "remote.SSH.serverInstallPath": {}
[19:14:45.570] SSH Resolver called for host: computelab-304-7022
[19:14:45.570] Setting up SSH remote "computelab-304-7022"
[19:14:45.572] Acquiring local install lock: /var/folders/x5/cqkp4ww55h32p6gv60bflrd00000gn/T/vscode-remote-ssh-3e6a398b-install.lock
[19:14:45.580] Looking for existing server data file at /Users/hujian/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-3e6a398b-f80445acd5a3dadef24aa209168452a3d97cc326-0.70.0/data.json
[19:14:45.580] Using commit id "f80445acd5a3dadef24aa209168452a3d97cc326" and quality "stable" for server
[19:14:45.583] Install and start server if needed
[19:14:45.586] PATH: /Users/hujian/.nvm/versions/node/v14.17.5/bin:/Users/hujian/opt/anaconda3/bin:/Users/hujian/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
[19:14:45.587] Checking ssh with "ssh -V"
[19:14:45.592] > OpenSSH_8.6p1, LibreSSL 2.8.3

[19:14:45.597] askpass server listening on /var/folders/x5/cqkp4ww55h32p6gv60bflrd00000gn/T/vscode-ssh-askpass-9a5514686c09957525e9dd55d3d1b83d42394a16.sock
[19:14:45.598] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/x5/cqkp4ww55h32p6gv60bflrd00000gn/T/vscode-ssh-askpass-2f55b1bdaca65f68f07327e1329aab0d8dbdb15c.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","60271","-o","ConnectTimeout=15","computelab-304-7022","bash"],"dataFilePath":"/Users/hujian/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-3e6a398b-f80445acd5a3dadef24aa209168452a3d97cc326-0.70.0/data.json"}
[19:14:45.598] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/hujian/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/x5/cqkp4ww55h32p6gv60bflrd00000gn/T/vscode-ssh-askpass-9a5514686c09957525e9dd55d3d1b83d42394a16.sock"}
[19:14:45.599] Spawned 82531
[19:14:45.709] > local-server-1> Spawned ssh, pid=82544
[19:14:45.711] stderr> OpenSSH_8.6p1, LibreSSL 2.8.3
[19:14:46.888] stderr> debug1: Server host key: ssh-ed25519 SHA256:Wu3omFjAtUl6H3JR7/XL1yAdPtl2mO7cyuulzc/cK78
[19:14:46.889] stderr> Warning: Permanently added '[computelab-304]:7022' (ED25519) to the list of known hosts.
[19:14:47.844] stderr> Authenticated to computelab-304 ([10.32.208.144]:7022).
[19:14:49.033] > ready: af0794499f6a
[19:14:49.355] > Linux 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022
[19:14:49.355] Platform: linux
[19:14:49.894] > af0794499f6a: running
[19:14:49.895] > Acquiring lock on /home/jianh/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/vscode-remote-lock.jianh.f80445acd5a3dadef24aa209168452a3d97cc326
> Found old VS Code install 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, attempting to clean up
[19:14:49.896] > Deleting old install from /home/jianh/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
> Deleting old log file from /home/jianh/.vscode-server/.7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e.log
> Found old VS Code install 5554b12acf27056905806867f251c859323ff7e9, attempting to clean up
> Deleting old install from /home/jianh/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9
[19:14:49.896] stderr> rm: cannot remove '/home/jianh/.vscode-server/bin/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e': Directory not empty
[19:14:49.896] stderr> rm: cannot remove '/home/jianh/.vscode-server/.7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e.log': No such file or directory
[19:14:49.896] stderr> rm: cannot remove '/home/jianh/.vscode-server/bin/5554b12acf27056905806867f251c859323ff7e9': Directory not empty
[19:14:50.086] > Deleting old log file from /home/jianh/.vscode-server/.5554b12acf27056905806867f251c859323ff7e9.log
> Found existing installation at /home/jianh/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326...
> Checking /home/jianh/.vscode-server/.f80445acd5a3dadef24aa209168452a3d97cc326.log and /home/jianh/.vscode-server/.f80445acd5a3dadef24aa209168452a3d97cc326.pid for a running server
> Looking for server with pid: 888
> Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> Checking server status on port 43571 with wget
> af0794499f6a: start
> SSH_AUTH_SOCK====
> DISPLAY====
> webUiAccessToken====
> listeningOn==43571==
[19:14:50.087] > osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/tmp==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> connectionToken==11a1a11a-1111-11a1-1a1a-1a1aaaa11a11==
> af0794499f6a: end
[19:14:50.087] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==43571==osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/tmp==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==11a1a11a-1111-11a1-1a1a-1a1aaaa11a11==

[19:14:50.087] Remote server is listening on 43571
[19:14:50.088] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":43571},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/tmp","platform":"linux","connectionToken":"11a1a11a-1111-11a1-1a1a-1a1aaaa11a11"},"installUnpackCode":""}
[19:14:50.088] stderr> rm: cannot remove '/home/jianh/.vscode-server/.5554b12acf27056905806867f251c859323ff7e9.log': No such file or directory
[19:14:50.089] Persisting server connection details to /Users/hujian/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-3e6a398b-f80445acd5a3dadef24aa209168452a3d97cc326-0.70.0/data.json
[19:14:50.092] Starting forwarding server. localPort 60275 -> socksPort 60271 -> remotePort 43571
[19:14:50.092] Forwarding server listening on 60275
[19:14:50.092] Waiting for ssh tunnel to be ready
[19:14:50.093] Tunneled 43571 to local port 60275
[19:14:50.093] Resolved "ssh-remote+computelab-304-7022" to "127.0.0.1:60275"
[19:14:50.095] [Forwarding server 60275] Got connection 0
[19:14:50.102] ------




[19:14:50.160] [Forwarding server 60275] Got connection 1
[19:14:50.545] [Forwarding server 60275] Got connection 2
[19:14:54.360] [Forwarding server 60275] Got connection 3
[19:14:54.360] [Forwarding server 60275] Got connection 4

```

**Comment by tanhakabir** [comment]
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/6341

There will be a fix out tomorrow in the pre-release version. Please let me know if it ends up working for you!

**Comment by tanhakabir** [comment]
Actually I think this is actually an issue with how we're starting the connection. Tomorrow's fix may still fix it for you

**Comment by tanhakabir** [comment]
What does your `remote.SSH.remotePlatform` look like in settings.json
