### ISSUE TITLE
MacOS unable to connect to windows 10, but SSH connections successfully.

### ISSUE THREAD

**Issue by daief** [microsoft/vscode-remote-release#6359]
- VSCode Version: 1.64.2
- Local OS Version: macOS Catalina 10.15.7
- Remote OS Version: Windows 10 
- Remote Extension/Connection Type: SSH
- Logs:

Fail to connect host.

```bash
[19:29:35.010] Log Level: 2
[19:29:35.011] remote-ssh@0.75.2022021715
[19:29:35.012] darwin x64
[19:29:35.014] SSH Resolver called for "ssh-remote+win.qunhequnhe.com", attempt 1
[19:29:35.015] "remote.SSH.useLocalServer": false
[19:29:35.015] "remote.SSH.showLoginTerminal": false
[19:29:35.016] "remote.SSH.remotePlatform": {"win.qunhequnhe.com":"windows"}
[19:29:35.016] "remote.SSH.path": undefined
[19:29:35.016] "remote.SSH.configFile": undefined
[19:29:35.016] "remote.SSH.useFlock": true
[19:29:35.016] "remote.SSH.lockfilesInTmp": false
[19:29:35.017] "remote.SSH.localServerDownload": auto
[19:29:35.017] "remote.SSH.remoteServerListenOnSocket": false
[19:29:35.017] "remote.SSH.showLoginTerminal": false
[19:29:35.017] "remote.SSH.defaultExtensions": []
[19:29:35.017] "remote.SSH.loglevel": 2
[19:29:35.018] "remote.SSH.enableDynamicForwarding": true
[19:29:35.018] "remote.SSH.enableRemoteCommand": false
[19:29:35.018] "remote.SSH.serverPickPortsFromRange": {}
[19:29:35.018] "remote.SSH.serverInstallPath": {}
[19:29:35.031] SSH Resolver called for host: win.qunhequnhe.com
[19:29:35.032] Setting up SSH remote "win.qunhequnhe.com"
[19:29:35.036] Using commit id "f80445acd5a3dadef24aa209168452a3d97cc326" and quality "stable" for server
[19:29:35.040] Install and start server if needed
[19:29:35.041] PATH: /Users/daief/.deno/bin:/Users/daief/.nvm/versions/node/v12.22.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/daief/.cargo/bin:/Users/daief/Library/Android/sdk/tools:/Users/daief/Library/Android/sdk/platform-tools
[19:29:35.041] Checking ssh with "ssh -V"
[19:29:35.048] > OpenSSH_8.1p1, LibreSSL 2.7.3

[19:29:35.051] Remote command length: 6179/8192 characters
[19:29:35.051] Running script with connection command: ssh -T -D 62821 -o ConnectTimeout=15 'win.qunhequnhe.com' powershell
[19:29:52.053] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/daief/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022021715/out/extension.js:1:586253)
	at Timeout._onTimeout (/Users/daief/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022021715/out/extension.js:1:679491)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[19:29:52.059] ------

```

But I execute `Remote-SSH: Uninstall VS Code Server from Host...` successfully.

```bash
[19:30:20.832] Picking SSH host
[19:30:22.385] Selected win.qunhequnhe.com
[19:30:22.390] Remote command length: 192/8192 characters
[19:30:22.390] Running script with connection command: ssh -T -o ClearAllForwardings=true -o ConnectTimeout=15 'win.qunhequnhe.com' powershell
[19:30:22.950] > Windows PowerShell
> ��Ȩ���� (C) Microsoft Corporation����������Ȩ����
> 
> �����µĿ�ƽ̨ PowerShell https://aka.ms/pscore6
> 
[19:30:23.371] > 
# ......
[19:30:23.926] "Uninstall VS Code Server" terminal command done
```

And I can SSH the host in my terminal.

```bash
❯ ssh -T -D 62831 -o ConnectTimeout=15 'win.qunhequnhe.com' powershell
Windows PowerShell
��Ȩ���� (C) Microsoft Corporation����������Ȩ��

�����µĿ�ƽ̨ PowerShell https://aka.ms/pscore6


daief in DESKTOP-B6GVNH9 in ~
? uname -a
uname -a
MINGW64_NT-10.0-19042 DESKTOP-B6GVNH9 3.1.6-340.x86_64 2020-07-09 14:33 UTC x86_64 Msys
```

My VS Code config. It is no effect to set `remote.SSH.useLocalServer` true neither false. 

```json
{
  "remote.SSH.remotePlatform": {
    "win.qunhequnhe.com": "windows"
  },
  "remote.SSH.useLocalServer": false
}
```

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No(Remote SSH is a extension)

**Comment by tanhakabir** [comment]
What is the shell setup on your remote? When you ssh'd in through your terminal how did you get MINGW set up?

**Comment by daief** [comment]
> What is the shell setup on your remote? When you ssh'd in through your terminal how did you get MINGW set up?

@tanhakabir 

1. There are both powershell and git bash on my remote. I make git bash as my default SSH shell. But run ssh command with `powershell` options that may force using powershell.
    - ![image](https://user-images.githubusercontent.com/19222089/154789136-a049c9f8-781e-4628-ad86-d380d988e6ad.png)
2. I do't konw what MINGW is. I am sorry.

And there is one more thing. About three or four days ago, Remote SSH worked fine for about two months. It broke down all of a sudden, before that my windows and mac had not even restarted.

**Comment by tanhakabir** [comment]
I'm seeing in your logs you had:
```
❯ ssh -T -D 62831 -o ConnectTimeout=15 'win.qunhequnhe.com' powershell
Windows PowerShell
��Ȩ���� (C) Microsoft Corporation����������Ȩ��

�����µĿ�ƽ̨ PowerShell https://aka.ms/pscore6


daief in DESKTOP-B6GVNH9 in ~
? uname -a
uname -a
MINGW64_NT-10.0-19042 DESKTOP-B6GVNH9 3.1.6-340.x86_64 2020-07-09 14:33 UTC x86_64 Msys
```

Where you became connected to a MINGW shell. Do you know how that happen? Did that happen automatically?

Would you also be able to try the latest pre-release of the Remote SSH extension to see if you're also facing a problem there?

**Comment by daief** [comment]
1. I copied the command(`ssh -T -D 62831 -o ConnectTimeout=15 'win.qunhequnhe.com' powershell`) from the Remote SSH logs. I execute it manually to prove my Mac can connect to remote by the SSH. And the result looks good as the logs.
2. Today I tried the prerelease version(v0.75.2022021903) but the problem remains.

<details>
  <summary>The logs when `remote.SSH.useLocalServer` is true:</summary>

```bash
[15:28:46.175] Log Level: 2
[15:28:46.176] remote-ssh@0.75.2022021903
[15:28:46.176] darwin x64
[15:28:46.195] SSH Resolver called for "ssh-remote+win.qunhequnhe.com", attempt 1
[15:28:46.195] "remote.SSH.useLocalServer": true
[15:28:46.196] "remote.SSH.path": undefined
[15:28:46.196] "remote.SSH.configFile": undefined
[15:28:46.196] "remote.SSH.useFlock": true
[15:28:46.197] "remote.SSH.lockfilesInTmp": false
[15:28:46.197] "remote.SSH.localServerDownload": always
[15:28:46.197] "remote.SSH.remoteServerListenOnSocket": false
[15:28:46.198] "remote.SSH.showLoginTerminal": false
[15:28:46.198] "remote.SSH.defaultExtensions": []
[15:28:46.198] "remote.SSH.loglevel": 2
[15:28:46.198] "remote.SSH.enableDynamicForwarding": true
[15:28:46.199] "remote.SSH.enableRemoteCommand": false
[15:28:46.199] "remote.SSH.serverPickPortsFromRange": {}
[15:28:46.199] "remote.SSH.serverInstallPath": {}
[15:28:46.202] SSH Resolver called for host: win.qunhequnhe.com
[15:28:46.202] Setting up SSH remote "win.qunhequnhe.com"
[15:28:46.206] Acquiring local install lock: /var/folders/0z/376xt06j77j26_8r4bdffhkh0000gn/T/vscode-remote-ssh-c0fe08dc-install.lock
[15:28:46.209] Looking for existing server data file at /Users/daief/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-c0fe08dc-f80445acd5a3dadef24aa209168452a3d97cc326-0.75.2022021903/data.json
[15:28:46.210] Using commit id "f80445acd5a3dadef24aa209168452a3d97cc326" and quality "stable" for server
[15:28:46.214] Install and start server if needed
[15:28:46.232] PATH: /Users/daief/.deno/bin:/Users/daief/.nvm/versions/node/v12.22.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/daief/.cargo/bin:/Users/daief/Library/Android/sdk/tools:/Users/daief/Library/Android/sdk/platform-tools
[15:28:46.232] Checking ssh with "ssh -V"
[15:28:46.239] > OpenSSH_8.1p1, LibreSSL 2.7.3

[15:28:46.243] askpass server listening on /var/folders/0z/376xt06j77j26_8r4bdffhkh0000gn/T/vscode-ssh-askpass-74d31bd1f88bd845d3579aba5524897f6d1941f8.sock
[15:28:46.243] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/0z/376xt06j77j26_8r4bdffhkh0000gn/T/vscode-ssh-askpass-58bb62206c2dbeafdb7f0ef147163dc71f79a922.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","61786","-o","ConnectTimeout=30","win.qunhequnhe.com","powershell"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/daief/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-c0fe08dc-f80445acd5a3dadef24aa209168452a3d97cc326-0.75.2022021903/data.json"}
[15:28:46.243] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/daief/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022021903/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/daief/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022021903/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/0z/376xt06j77j26_8r4bdffhkh0000gn/T/vscode-ssh-askpass-74d31bd1f88bd845d3579aba5524897f6d1941f8.sock"}
[15:28:46.244] Spawned 59273
[15:28:46.356] > local-server-1> Spawned ssh, pid=59277
[15:28:46.361] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[15:28:46.551] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:u9fz+KRpwc8nl4dHa8JgqQGPDstYgHidLV2xI+qzGAY
[15:28:46.867] stderr> Authenticated to win.qunhequnhe.com ([10.10.121.252]:22).
[15:28:47.167] > Windows PowerShell
> ��Ȩ���� (C) Microsoft Corporation����������Ȩ����
>
> �����µĿ�ƽ̨ PowerShell https://aka.ms/pscore6
[15:28:47.178] >
[15:28:47.596] >
> daief in [1;2;32mDESKTOP-B6GVNH9 in ~
> ?
[15:28:47.645] > echo 'ready: dfc46274510f'
[15:28:47.656] > ready: dfc46274510f
[15:28:47.687] >
> daief in [1;2;32mDESKTOP-B6GVNH9 in ~
> ?
[15:28:47.698] > uname -rsv
[15:28:47.712] > MINGW64_NT-10.0-19042 3.1.6-340.x86_64 2020-07-09 14:33 UTC
[15:28:47.759] >
> daief in [1;2;32mDESKTOP-B6GVNH9 in ~
> ?
[15:29:18.247] Terminating local server
[15:29:18.249] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/daief/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022021903/out/extension.js:1:586167)
	at Timeout._onTimeout (/Users/daief/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022021903/out/extension.js:1:631082)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[15:29:18.255] ------




[15:29:18.256] Local server exit: 15
```

</details>

<details>
  <summary>The logs when `remote.SSH.useLocalServer` is false:</summary>

```bash
[15:32:11.320] Log Level: 2
[15:32:11.321] remote-ssh@0.75.2022021903
[15:32:11.321] darwin x64
[15:32:11.338] SSH Resolver called for "ssh-remote+win.qunhequnhe.com", attempt 1
[15:32:11.339] "remote.SSH.useLocalServer": false
[15:32:11.340] "remote.SSH.showLoginTerminal": false
[15:32:11.340] "remote.SSH.remotePlatform": {"win.qunhequnhe.com":"windows"}
[15:32:11.340] "remote.SSH.path": undefined
[15:32:11.341] "remote.SSH.configFile": undefined
[15:32:11.341] "remote.SSH.useFlock": true
[15:32:11.341] "remote.SSH.lockfilesInTmp": false
[15:32:11.342] "remote.SSH.localServerDownload": always
[15:32:11.342] "remote.SSH.remoteServerListenOnSocket": false
[15:32:11.342] "remote.SSH.showLoginTerminal": false
[15:32:11.342] "remote.SSH.defaultExtensions": []
[15:32:11.343] "remote.SSH.loglevel": 2
[15:32:11.343] "remote.SSH.enableDynamicForwarding": true
[15:32:11.343] "remote.SSH.enableRemoteCommand": false
[15:32:11.344] "remote.SSH.serverPickPortsFromRange": {}
[15:32:11.344] "remote.SSH.serverInstallPath": {}
[15:32:11.347] SSH Resolver called for host: win.qunhequnhe.com
[15:32:11.348] Setting up SSH remote "win.qunhequnhe.com"
[15:32:11.352] Using commit id "f80445acd5a3dadef24aa209168452a3d97cc326" and quality "stable" for server
[15:32:11.357] Install and start server if needed
[15:32:11.361] PATH: /Users/daief/.deno/bin:/Users/daief/.nvm/versions/node/v12.22.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/daief/.cargo/bin:/Users/daief/Library/Android/sdk/tools:/Users/daief/Library/Android/sdk/platform-tools
[15:32:11.361] Checking ssh with "ssh -V"
[15:32:11.370] > OpenSSH_8.1p1, LibreSSL 2.7.3

[15:32:11.372] Remote command length: 6178/8192 characters
[15:32:11.372] Running script with connection command: ssh -T -D 63867 -o ConnectTimeout=30 'win.qunhequnhe.com' powershell
[15:32:43.379] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/daief/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022021903/out/extension.js:1:586167)
	at Timeout._onTimeout (/Users/daief/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022021903/out/extension.js:1:680497)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[15:32:43.385] ------
```

</details>

**Comment by daief** [comment]
@tanhakabir 
Thanks for your reply. I remove the defalutShell  `HKEY_LOCAL_MACHINE\SOFTWARE\OpenSSH\DefaultShell`, then I can connect remote with `useLocalServer: true`.

My problems is resolved and I will close this. Thank you very much!

But there maybe another problem. When set `useLocalServer: false`, it is still timeout to connect. The logs is same as above. Neither of `"ssh-remote+win.qunhequnhe.com": "windows"` nor `"win.qunhequnhe.com": "windows"` can connect.

The "MINGW" is the result of `uname -rsv` in Git-Bash, maybe it is just a name alias.

![image](https://user-images.githubusercontent.com/19222089/155253150-291ddee9-30e6-4f4c-9b00-6b40fc8b9857.png)

**Comment by tanhakabir** [comment]
I suspect it's an issue with this: "The "MINGW" is the result of uname -rsv in Git-Bash, maybe it is just a name alias."

Overall `useLocalServer` being true is better than false so I think this is fine!
