### ISSUE TITLE
Can't connect with ssh: Terminating local server. Resolver error: Error: Connecting with SSH timed out

### ISSUE THREAD

**Issue by kuvaldini** [microsoft/vscode-remote-release#6360]
Same issue as  #3723, but discussion was stopped and issue closed.

OS: Arch Linux
VSCode version: 1.63.2 899d46d82c4c95423fb7e10e68eba52050e30ba3 x64 (latest at the moment)

Regular connection works fine. Piped command also works. 
```
 echo uname | ssh -T valo-vbox 
Welcome to Ubuntu 16.04.7 LTS (GNU/Linux 4.15.0-142-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

UA Infra: Extended Security Maintenance (ESM) is not enabled.

5 updates can be applied immediately.
To see these additional updates run: apt list --upgradable

147 additional security updates can be applied with UA Infra: ESM
Learn more about enabling UA Infra: ESM service for Ubuntu 16.04 at
https://ubuntu.com/16-04

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

Linux
```

Extention log:
```
[14:23:29.304] Log Level: 2
[14:23:29.306] remote-ssh@0.70.0
[14:23:29.306] linux x64
[14:23:29.307] SSH Resolver called for "ssh-remote+valo-vbox", attempt 1
[14:23:29.308] "remote.SSH.useLocalServer": true
[14:23:29.308] "remote.SSH.path": undefined
[14:23:29.308] "remote.SSH.configFile": undefined
[14:23:29.308] "remote.SSH.useFlock": true
[14:23:29.308] "remote.SSH.lockfilesInTmp": false
[14:23:29.308] "remote.SSH.localServerDownload": auto
[14:23:29.308] "remote.SSH.remoteServerListenOnSocket": false
[14:23:29.308] "remote.SSH.showLoginTerminal": false
[14:23:29.309] "remote.SSH.defaultExtensions": []
[14:23:29.309] "remote.SSH.loglevel": 2
[14:23:29.309] "remote.SSH.serverPickPortsFromRange": {}
[14:23:29.309] "remote.SSH.enableDynamicForwarding": true
[14:23:29.309] "remote.SSH.serverInstallPath": {}
[14:23:29.310] SSH Resolver called for host: valo-vbox
[14:23:29.310] Setting up SSH remote "valo-vbox"
[14:23:29.312] Acquiring local install lock: /tmp/vscode-remote-ssh-b029d2ab-install.lock
[14:23:29.320] Looking for existing server data file at /home/kyb/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-b029d2ab-899d46d82c4c95423fb7e10e68eba52050e30ba3-0.70.0/data.json
[14:23:29.322] Using commit id "899d46d82c4c95423fb7e10e68eba52050e30ba3" and quality "stable" for server
[14:23:29.326] Install and start server if needed
[14:23:29.330] PATH: /home/kyb/.yarn/bin:/home/kyb/devel/kuvaldini.pro/vendor/bundle/ruby/3.0.0/bin:/home/kyb/.local/share/gem/ruby/3.0.0/bin:/usr/local/bin:/usr/bin:/var/lib/snapd/snap/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
[14:23:29.330] Checking ssh with "ssh -V"
[14:23:29.338] > OpenSSH_8.8p1, OpenSSL 1.1.1m  14 Dec 2021

[14:23:29.341] askpass server listening on /run/user/1000/vscode-ssh-askpass-0f8d7c7b8115e224912392acec57202ef2888ae5.sock
[14:23:29.341] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-6d5723f70bb19d6adc27b51bb8ecd94d9602781b.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","44045","-o","ConnectTimeout=15","valo-vbox"],"dataFilePath":"/home/kyb/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-b029d2ab-899d46d82c4c95423fb7e10e68eba52050e30ba3-0.70.0/data.json"}
[14:23:29.341] Local server env: {"DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/kyb/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/home/kyb/Downloads/VSCode-linux-x64/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/kyb/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-0f8d7c7b8115e224912392acec57202ef2888ae5.sock"}
[14:23:29.344] Spawned 799487
[14:23:29.442] > local-server-1> Spawned ssh, pid=799495
[14:23:29.444] stderr> OpenSSH_8.8p1, OpenSSL 1.1.1m  14 Dec 2021
[14:23:29.462] stderr> debug1: Server host key: ssh-ed25519 SHA256:PJ6n6tGuF2OZJzYUcw+SgyPNOgeacTPNz+nbvAiGCwI
[14:23:29.480] stderr> Authenticated to localhost ([127.0.0.1]:3022) using "publickey".
[14:23:29.563] > Welcome to Ubuntu 16.04.7 LTS (GNU/Linux 4.15.0-142-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
> UA Infra: Extended Security Maintenance (ESM) is not enabled.
> 
> 5 updates can be applied immediately.
> To see these additional updates run: apt list --upgradable
> 
> 147 additional security updates can be applied with UA Infra: ESM
> Learn more about enabling UA Infra: ESM service for Ubuntu 16.04 at
> https://ubuntu.com/16-04
> 
> Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
> applicable law.
[14:23:46.346] Terminating local server
[14:23:46.348] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/home/kyb/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:430551)
	at Timeout._onTimeout (/home/kyb/.vscode/extensions/ms-vscode-remote.remote-ssh-0.70.0/out/extension.js:1:475197)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[14:23:46.354] ------




[14:23:46.355] Local server exit: 15
```

Is that fixable?

**Comment by kuvaldini** [comment]
I disabled "Use local server" and it seems become working.

**Comment by roblourens** [comment]
Thanks, btw what is your default shell on the remote? It may be another issue we've seen

**Comment by kuvaldini** [comment]
Default shell on the remote was /bin/sh (i.e. dash). Since issue was solved I stopped any investigations on it.
