### ISSUE TITLE
Mac: Remote SSH doesn't work (terminal SSH is okay)

### ISSUE THREAD

**Issue by AliengirlLiv** [microsoft/vscode-remote-release#6365]
- VSCode Version: Version: 1.64.2 (Universal), Commit: f80445acd5a3dadef24aa209168452a3d97cc326
- Local OS Version: macOS Big Sur 11.6.1
- Remote OS Version: Ubuntu 18.04.5
- Remote Extension/Connection Type: SSH
- Logs: see below

Steps to Reproduce:

I installed the Remote-SSH extension, then tried to connect to a remote server by selecting a machine from the "ssh targets" panel. This nearly immediately gives me the following error:

> Could not establish connection to "pabrtxs1.ist.berkeley.edu": Permission denied (publickey).

I can ssh into the same machine through the VSCode terminal with no problems.

Other things I've tried unsuccessfully:
* Turning the setting "Remote.SSH: Use Local Server" on and off
* Deleting the .vscode_server folder on the server
* Copying settings from a different (Linux) machine, from which I can connect successfully

Trying to connect remotely gives the following terminal logs:

> [13:55:06.234] Log Level: 2
[13:55:06.235] remote-ssh@0.74.0
[13:55:06.235] darwin x64
[13:55:06.238] SSH Resolver called for "ssh-remote+pabrtxs1.ist.berkeley.edu", attempt 1
[13:55:06.239] "remote.SSH.useLocalServer": true
[13:55:06.239] "remote.SSH.path": undefined
[13:55:06.239] "remote.SSH.configFile": undefined
[13:55:06.239] "remote.SSH.useFlock": true
[13:55:06.239] "remote.SSH.lockfilesInTmp": false
[13:55:06.240] "remote.SSH.localServerDownload": auto
[13:55:06.240] "remote.SSH.remoteServerListenOnSocket": false
[13:55:06.240] "remote.SSH.showLoginTerminal": false
[13:55:06.240] "remote.SSH.defaultExtensions": []
[13:55:06.240] "remote.SSH.loglevel": 2
[13:55:06.240] "remote.SSH.enableDynamicForwarding": true
[13:55:06.240] "remote.SSH.enableRemoteCommand": false
[13:55:06.240] "remote.SSH.serverPickPortsFromRange": {}
[13:55:06.241] "remote.SSH.serverInstallPath": {}
[13:55:06.250] SSH Resolver called for host: pabrtxs1.ist.berkeley.edu
[13:55:06.250] Setting up SSH remote "pabrtxs1.ist.berkeley.edu"
[13:55:06.253] Acquiring local install lock: /var/folders/35/rjhqzmd92_gf85nmn_xs9l0c0000gn/T/vscode-remote-ssh-f57c76bd-install.lock
[13:55:06.255] Looking for existing server data file at /Users/oliviawatkins/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f57c76bd-f80445acd5a3dadef24aa209168452a3d97cc326-0.74.0/data.json
[13:55:06.256] Using commit id "f80445acd5a3dadef24aa209168452a3d97cc326" and quality "stable" for server
[13:55:06.259] Install and start server if needed
[13:55:06.264] PATH: /Users/oliviawatkins/miniconda3/bin:/Users/oliviawatkins/miniconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/opt/llvm/bin:/miniconda3/bin:/opt/local/bin:/opt/local/sbin:/Users/oliviawatkins/sumo_binaries/bin:/usr/local/opt/llvm/bin:/miniconda3/bin/python3.7:/Users/oliviawatkins/torch/install/bin:/Applications/SWI-Prolog.app/Contents/MacOS:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/opt/llvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/oliviawatkins/Library/Android/sdk/emulator:/Users/oliviawatkins/Library/Android/sdk/tools:/Users/oliviawatkins/Library/Android/sdk/tools/bin:/Users/oliviawatkins/Library/Android/sdk/platform-tools
[13:55:06.264] Checking ssh with "ssh -V"
[13:55:06.270] > OpenSSH_8.1p1, LibreSSL 2.7.3

>[13:55:06.273] askpass server listening on /var/folders/35/rjhqzmd92_gf85nmn_xs9l0c0000gn/T/vscode-ssh-askpass-b0d842445a13d3ff080c949ea647ba2818285738.sock
[13:55:06.273] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/35/rjhqzmd92_gf85nmn_xs9l0c0000gn/T/vscode-ssh-askpass-e66f840c9dc58fc4c79faf2d129cdb3d489b6bb3.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","53433","-o","ConnectTimeout=30","pabrtxs1.ist.berkeley.edu"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/oliviawatkins/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-f57c76bd-f80445acd5a3dadef24aa209168452a3d97cc326-0.74.0/data.json"}
[13:55:06.273] Local server env: {"DISPLAY":"/private/tmp/com.apple.launchd.yLKO31U3mW/org.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/oliviawatkins/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/oliviawatkins/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/35/rjhqzmd92_gf85nmn_xs9l0c0000gn/T/vscode-ssh-askpass-b0d842445a13d3ff080c949ea647ba2818285738.sock"}
[13:55:06.274] Spawned 9094
[13:55:06.385] > local-server-1> Spawned ssh, pid=9110
[13:55:06.386] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[13:55:06.438] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:L3rNpxsuVMKHod72xs/QkWltERUCnYi0b34JpF+j65A
[13:55:06.514] stderr> oliviawatkins@pabrtxs1.ist.berkeley.edu: Permission denied (publickey).
[13:55:06.515] > local-server-1> ssh child died, shutting down
[13:55:06.519] Local server exit: 0
[13:55:06.520] Received install output: local-server-1> Spawned ssh, pid=9110
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:L3rNpxsuVMKHod72xs/QkWltERUCnYi0b34JpF+j65A
oliviawatkins@pabrtxs1.ist.berkeley.edu: Permission denied (publickey).
local-server-1> ssh child died, shutting down

>[13:55:06.521] Resolver error: Error: Permission denied (publickey).
	at Function.Create (/Users/oliviawatkins/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:585917)
	at /Users/oliviawatkins/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:583968
	at Object.t.handleInstallOutput (/Users/oliviawatkins/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:584491)
	at Object.e [as tryInstallWithLocalServer] (/Users/oliviawatkins/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:624925)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/oliviawatkins/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:643015
	at async Object.t.withShowDetailsEvent (/Users/oliviawatkins/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:646762)
	at async /Users/oliviawatkins/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:623397
	at async b (/Users/oliviawatkins/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:619903)
	at async Object.t.resolveWithLocalServer (/Users/oliviawatkins/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:623012)
	at async Object.t.resolve (/Users/oliviawatkins/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:644372)
	at async /Users/oliviawatkins/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:721503
[13:55:06.526] ------

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by firegate22** [comment]
agree
mac 12.2.1 (21D62)

Version: 1.65.0-insider (Universal)
Commit: 29f707c1f0dc0df76a98390eacbca440507866c0
Date: 2022-02-22T05:14:17.705Z (2 hrs ago)

remote ssh v0.75.2022022115

remote centos 7

**Comment by tanhakabir** [comment]
@AliengirlLiv were you ever able to connect to this remote with your current machine?

Based on your logs it seems that your credentials aren't set properly on your machine:
```
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:L3rNpxsuVMKHod72xs/QkWltERUCnYi0b34JpF+j65A
[oliviawatkins@pabrtxs1.ist.berkeley.edu](mailto:oliviawatkins@pabrtxs1.ist.berkeley.edu): Permission denied (publickey).
```

Are you able to connect to this remote on your current machine in the terminal? The above error comes from the SSH binary on your machine.

**Comment by tanhakabir** [comment]
@firegate22 could you please submit a separate issue for what you're seeing with logs?

**Comment by AliengirlLiv** [comment]
@tanhakabir Yes, I can connect to this remote from my current machine using ssh. The issue only arises when I try to connect using the Remote SSH extension.

**Comment by JRHeaton** [comment]
I'm having a similar issue. On Mac only, the Remote - SSH extension can no longer connect to my raspberry pi which I have been doing for months -- I see the "welcome" terminal message in the output for the extension(so it's authenticating), but then {timeout} seconds later it times out. Setting "use local server" to false works around this, but that feels wrong. As the OP has reported, I am able to SSH into the host fine from terminal as well, both using password and key-based authentication.

**Comment by JRHeaton** [comment]
Please let me know what additional information is needed that I can provide as I would like to facilitate making this as easy and expedient for the devs to fix as possible and am willing to take time to provide such information or do tests.

**Comment by tanhakabir** [comment]
Hm @JRHeaton could you please port your Remote SSH logs of the failure as well?

Also could you try using the pre-release version of the extension

**Comment by tanhakabir** [comment]
Hm @AliengirlLiv I'm not sure here because the error with authentication is coming from SSH on your machine not VS Code. How do you connect to your remote outside of VS Code?

**Comment by firegate22** [comment]
> @firegate22 could you please submit a separate issue for what you're seeing with logs?

Sorry, I was sure that I had exactly the same issue / error in the logs. Is there any way to get historical logs?  
Aside from that, right now, with Remote SSH v0.75.2022022115 and VS Code Build Date: 2022-02-22T05:14:17.705Z (1 day ago), it's working again. In the meantime I did downgrades (VS Code and Extension to get it "fixed" for me).

**Comment by tanhakabir** [comment]
@firegate22 sorry there isn't a way to get historical logs. That's okay! I'll see if @JRHeaton has any logs to share

**Comment by kschaab** [comment]
I think I have the same issue as @firegate22 , filed #6380

**Comment by JRHeaton** [comment]
Can confirm that for me as well, updating to the pre-release version has resolved the issue. I am using this method instead of reverting to 0.70.0 unless I see any further issues. If you still need any logs from me please tag me and I will be glad to upload whatever you request.
