### ISSUE TITLE
SSH connect encounter "System restart required", maybe related to fish shell?

### ISSUE THREAD

**Issue by Benature** [microsoft/vscode-remote-release#6374]
- VSCode Version: 1.64.2
- Local OS Version: macOS Monterey 12.1
- Remote OS Version: Ubuntu 18.04.6 LTS
- Remote Extension/Connection Type: SSH

```log
[11:24:38.895] > Welcome to Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-050400-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   System information as of Wed Feb 23 03:24:38 UTC 2022
> 
>  * Super-optimized for small spaces - read how we shrank the memory
>    footprint of MicroK8s to make it the smallest full K8s around.
> 
>    https://ubuntu.com/blog/microk8s-memory-optimisation
> 
> 37 updates can be applied immediately.
> To see these additional updates run: apt list --upgradable
> 
> New release '20.04.3 LTS' available.
> Run 'do-release-upgrade' to upgrade to it.
> 
> 
> *** System restart required ***
[11:24:39.095] stderr> set: Unknown option “--path”
[11:24:39.096] stderr> /usr/share/fish/vendor_conf.d/snapd.fish (line 11): 
[11:24:39.096] stderr> set --path --export XDG_DATA_DIRS $XDG_DATA_DIRS
[11:24:39.096] stderr> ^
[11:24:39.096] stderr> from sourcing file /usr/share/fish/vendor_conf.d/snapd.fish
[11:24:39.096] stderr> 	called on line 250 of file /usr/share/fish/config.fish
[11:24:39.096] stderr> 
[11:24:39.096] stderr> from sourcing file /usr/share/fish/config.fish
[11:24:39.097] stderr> 	called during startup
[11:24:39.097] stderr> 
[11:24:39.097] stderr> 
[11:24:39.097] stderr>        setset - display and change shell variables.
[11:24:39.097] stderr>         -
[11:24:39.097] stderr> 
[11:24:39.097] stderr>    Synopsis   Synopsis   Synopsis   Synopsis
[11:24:39.097] stderr>        set [SCOPE_OPTIONS]       set       set       set
[11:24:39.098] stderr>        set [OPTIONS] VARIABLE_NAME VALUES...       set       set       set
[11:24:39.098] stderr>        set [OPTIONS] VARIABLE_NAME[INDICES]... VALUES...       set       set       set
[11:24:39.098] stderr>        set ( -q | --query ) [SCOPE_OPTIONS] VARIABLE_NAMES...       set       set       set
[11:24:39.098] stderr>        set ( -e | --erase ) [SCOPE_OPTIONS] VARIABLE_NAME       set       set       set
[11:24:39.098] stderr>        set ( -e | --erase ) [SCOPE_OPTIONS] VARIABLE_NAME[INDICES]...       set       set       set
[11:24:39.098] stderr>        set ( -S | --show ) [SCOPE_OPTIONS] [VARIABLE_NAME]...       set       set       set
[11:24:39.098] stderr> 
[11:24:39.098] stderr> set: Type “help set” for related documentation
[11:24:39.099] stderr> 
[11:24:54.778] Terminating local server
[11:24:54.779] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/benature/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:586043)
	at Timeout._onTimeout (/Users/benature/.vscode/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:630810)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)
[11:24:54.783] ------




[11:24:54.783] Local server exit: 15
```

At first the default shell of the remote is fish, I start remote ssh and "*** System restart required ***" occur. The error shows that it is related to fish, so I change the default shell to bash, then it successfully connected. 

Is there something imcompatible with the fish shell?

**Comment by tanhakabir** [comment]
We have this longstanding issue with fish shells: https://github.com/microsoft/vscode-remote-release/issues/2509

I recommend the workaround: Use the pre-release version of the extension and make sure you have `remote.SSH.useLocalServer` set to true and your remote listed in the `remote.SSH.remotePlatform` setting like so:
```
 "remote.SSH.remotePlatform": {

        <hostname1>: "linux",
        <hostname2>: "linux"
    },
```

Next week matching with the VS Code release time, the fix I have to enable this work around will be published to stable.
