### ISSUE TITLE
Remote server installation failed, incorrectly stating "$HOME/.vscode-server-insiders/bin/<hash>/node don't exist"

### ISSUE THREAD

**Issue by gaohuazuo** [microsoft/vscode-remote-release#6381]
- VSCode Version: 1.64.0-insider
- Local OS Version: ubuntu 16.04
- Remote OS Version: ubuntu 20.04
- Remote Extension/Connection Type: SSH
- Logs:

```
[14:27:19.737] Log Level: 2
[14:27:19.738] remote-ssh@0.74.0
[14:27:19.739] linux x64
[14:27:19.752] SSH Resolver called for "ssh-remote+d.hh-b", attempt 1
[14:27:19.753] "remote.SSH.useLocalServer": true
[14:27:19.753] "remote.SSH.path": undefined
[14:27:19.753] "remote.SSH.configFile": undefined
[14:27:19.753] "remote.SSH.useFlock": true
[14:27:19.753] "remote.SSH.lockfilesInTmp": false
[14:27:19.754] "remote.SSH.localServerDownload": auto
[14:27:19.754] "remote.SSH.remoteServerListenOnSocket": false
[14:27:19.754] "remote.SSH.showLoginTerminal": false
[14:27:19.754] "remote.SSH.defaultExtensions": []
[14:27:19.755] "remote.SSH.loglevel": 2
[14:27:19.755] "remote.SSH.enableDynamicForwarding": true
[14:27:19.755] "remote.SSH.enableRemoteCommand": false
[14:27:19.755] "remote.SSH.serverPickPortsFromRange": {}
[14:27:19.755] "remote.SSH.serverInstallPath": {}
[14:27:19.760] SSH Resolver called for host: d.hh-b
[14:27:19.761] Setting up SSH remote "d.hh-b"
[14:27:19.764] Acquiring local install lock: /tmp/vscode-remote-ssh-70a91c8c-install.lock
[14:27:19.767] Looking for existing server data file at /home/gaohuazuo/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-70a91c8c-7b9e5c32a053669d4e72f998e4fa217090c32f59-0.74.0/data.json
[14:27:19.767] Using commit id "7b9e5c32a053669d4e72f998e4fa217090c32f59" and quality "insider" for server
[14:27:19.774] Install and start server if needed
[14:27:19.779] PATH: /home/gaohuazuo/bin:/home/gaohuazuo/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[14:27:19.779] Checking ssh with "ssh -V"
[14:27:19.812] > OpenSSH_7.4p1, OpenSSL 1.0.2g  1 Mar 2016

[14:27:19.823] askpass server listening on /run/user/1000/vscode-ssh-askpass-b801e372c5e561c791fd9cf973feb309b008078f.sock
[14:27:19.825] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-d331978587afcba1e362f52498c8a10d8214cb1a.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","39817","-o","ConnectTimeout=60","d.hh-b"],"serverDataFolderName":".vscode-server-insiders","dataFilePath":"/home/gaohuazuo/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-70a91c8c-7b9e5c32a053669d4e72f998e4fa217090c32f59-0.74.0/data.json"}
[14:27:19.826] Local server env: {"DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/gaohuazuo/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code-insiders/code-insiders","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/gaohuazuo/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-b801e372c5e561c791fd9cf973feb309b008078f.sock"}
[14:27:19.840] Spawned 20501
[14:27:20.055] > local-server-1> Spawned ssh, pid=20513
[14:27:20.069] stderr> OpenSSH_7.4p1, OpenSSL 1.0.2g  1 Mar 2016
[14:27:20.351] stderr> debug1: Server host key: ssh-rsa SHA256:xxx
[14:27:20.701] stderr> Authenticated to xxx ([x.x.x.x]:22).
[14:27:20.908] > Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 4.15.0-55.60 x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> Failed to connect to https://changelogs.ubuntu.com/meta-release-lts. Check your Internet connection or proxy settings
> 
> ready: e58b587e1c70
[14:27:20.971] > Linux 4.15.0-55.60 #4 SMP Mon Mar 30 12:42:28 HKT 2020
[14:27:20.972] Platform: linux
[14:27:21.099] > e58b587e1c70: running
[14:27:21.119] > Acquiring lock on /home/gaohuazuo/.vscode-server-insiders/bin/7b9e5c32a053669d4e72f998e4fa217090c32f59/vscode-remote-lock.gaohuazuo.7b9e5c32a053669d4e72f998e4fa217090c32f59
[14:27:21.124] > Installing to /home/gaohuazuo/.vscode-server-insiders/bin/7b9e5c32a053669d4e72f998e4fa217090c32f59...
> e58b587e1c70%%1%%
> Downloading with wget
[14:27:29.636] > wget download failed
> failed: Connection timed out.
> printenv:
>     SHELL=/bin/bash
>     PWD=/home/gaohuazuo/.vscode-server-insiders/bin/7b9e5c32a053669d4e72f998e4fa217090c32f59
>     LOGNAME=gaohuazuo
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/home/gaohuazuo
>     LANG=en_US.UTF-8
>     VSCODE_AGENT_FOLDER=/home/gaohuazuo/.vscode-server-insiders
>     SSH_CONNECTION=x.x.x.x 41536 x.x.x.x 22
>     XDG_SESSION_CLASS=user
>     USER=gaohuazuo
>     SHLVL=1
>     XDG_SESSION_ID=c102760
>     XDG_RUNTIME_DIR=/run/user/10649
>     SSH_CLIENT=x.x.x.x x.x.x.x 22
>     LC_ALL=en_US.UTF-8
>     PATH=/home/gaohuazuo/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
>     MAIL=/var/mail/gaohuazuo
>     OLDPWD=/home/gaohuazuo
>     _=/usr/bin/printenv
> Trigger local server download
> e58b587e1c70:trigger_server_download
> platform==linux==
> vscodeArch==x64==
> destFolder==/home/gaohuazuo/.vscode-server-insiders/bin/==
> destFolder2==7b9e5c32a053669d4e72f998e4fa217090c32f59==
> e58b587e1c70:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/gaohuazuo/.vscode-server-insiders/bin/7b9e5c32a053669d4e72f998e4fa217090c32f59/vscode-scp-done.flag and vscode-server.tar.gz to exist
>  
[14:27:29.637] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/home/gaohuazuo/.vscode-server-insiders/bin/7b9e5c32a053669d4e72f998e4fa217090c32f59"}
[14:27:29.639] Downloading VS Code server locally...
[14:27:32.635] >  
[14:27:35.638] >  
[14:27:38.638] >  
[14:27:41.562] Downloaded VS Code server to /tmp/29f74c03-f8aa-444f-a82b-499da206c37b
[14:27:41.565] Renamed VS Code server to /tmp/vscode_server_1645684061563/vscode-server.tar.gz
[14:27:41.572] PATH: /home/gaohuazuo/bin:/home/gaohuazuo/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[14:27:41.572] Checking ssh with "ssh -V"
[14:27:41.586] > OpenSSH_7.4p1, OpenSSL 1.0.2g  1 Mar 2016

[14:27:41.589] Testing scp with "scp"
[14:27:41.601] scp exited with code: 1
[14:27:41.602] Got stderr from scp: usage: scp [-12346BCpqrv] [-c cipher] [-F ssh_config] [-i identity_file]
           [-l limit] [-o ssh_option] [-P port] [-S program]
           [[user@]host1:]file1 ... [[user@]host2:]file2
[14:27:41.604] Copying file to remote with scp -o ConnectTimeout=60 'vscode-server.tar.gz' 'vscode-scp-done.flag' 'd.hh-b':'/home/gaohuazuo/.vscode-server-insiders/bin/7b9e5c32a053669d4e72f998e4fa217090c32f59'
[14:27:41.605] Using cwd: file:///tmp/vscode_server_1645684061563
[14:27:41.641] >  
[14:27:42.707] > vscode-server.tar.gz                            0%    0     0.0KB/s   --:-- ETA
[14:27:43.709] > vscode-server.tar.gz                            4% 2336KB   2.3MB/s   00:21 ETA
[14:27:44.640] >  
[14:27:44.711] > vscode-server.tar.gz                            5% 2624KB   2.1MB/s   00:23 ETA
[14:27:45.713] > vscode-server.tar.gz                            5% 2912KB   1.9MB/s   00:25 ETA
[14:27:46.712] > vscode-server.tar.gz                            5% 3104KB   1.7MB/s   00:27 ETA
[14:27:47.644] >  
[14:27:47.712] > vscode-server.tar.gz                            6% 3200KB   1.6MB/s   00:30 ETA
[14:27:48.717] > vscode-server.tar.gz                            6% 3392KB   1.4MB/s   00:33 ETA
[14:27:49.748] > vscode-server.tar.gz                            6% 3648KB   1.3MB/s   00:36 ETA
[14:27:50.644] >  
[14:27:50.714] > vscode-server.tar.gz                            7% 4000KB   1.2MB/s   00:38 ETA
[14:27:51.720] > vscode-server.tar.gz                            8% 4288KB   1.1MB/s   00:41 ETA
[14:27:52.716] > vscode-server.tar.gz                            8% 4576KB   1.0MB/s   00:44 ETA
[14:27:53.647] >  
[14:27:53.724] > vscode-server.tar.gz                            9% 4832KB 980.6KB/s   00:48 ETA
[14:27:54.716] > vscode-server.tar.gz                            9% 5120KB 911.3KB/s   00:51 ETA
[14:27:55.717] > vscode-server.tar.gz                           10% 5312KB 839.4KB/s   00:55 ETA
[14:27:56.650] >  
[14:27:56.716] > vscode-server.tar.gz                           10% 5600KB 784.2KB/s   00:59 ETA
[14:27:57.718] > vscode-server.tar.gz                           11% 5952KB 741.0KB/s   01:02 ETA
[14:27:58.721] > vscode-server.tar.gz                           12% 6336KB 705.3KB/s   01:05 ETA
[14:27:59.648] >  
[14:27:59.717] > vscode-server.tar.gz                           13% 6816KB 682.8KB/s   01:06 ETA
[14:28:00.717] > vscode-server.tar.gz                           14% 7360KB 668.9KB/s   01:07 ETA
[14:28:01.715] > vscode-server.tar.gz                           15% 8000KB 666.0KB/s   01:06 ETA
[14:28:02.656] >  
[14:28:02.719] > vscode-server.tar.gz                           16% 8576KB 657.0KB/s   01:06 ETA
[14:28:03.732] > vscode-server.tar.gz                           17% 8928KB 626.5KB/s   01:09 ETA
[14:28:04.718] > vscode-server.tar.gz                           17% 9152KB 586.2KB/s   01:13 ETA
[14:28:05.653] >  
[14:28:05.722] > vscode-server.tar.gz                           18% 9472KB 559.6KB/s   01:16 ETA
[14:28:06.721] > vscode-server.tar.gz                           18% 9856KB 542.0KB/s   01:18 ETA
[14:28:07.719] > vscode-server.tar.gz                           19%   10MB 526.2KB/s   01:19 ETA
[14:28:08.654] >  
[14:28:08.737] > vscode-server.tar.gz                           20%   10MB 521.6KB/s   01:19 ETA
[14:28:09.721] > vscode-server.tar.gz                           21%   11MB 511.0KB/s   01:20 ETA
[14:28:10.722] > vscode-server.tar.gz                           21%   11MB 485.5KB/s   01:24 ETA
[14:28:11.654] >  
[14:28:11.719] > vscode-server.tar.gz                           22%   11MB 459.3KB/s   01:28 ETA
[14:28:12.723] > vscode-server.tar.gz                           22%   12MB 439.0KB/s   01:32 ETA
[14:28:13.726] > vscode-server.tar.gz                           23%   12MB 417.5KB/s   01:36 ETA
[14:28:14.656] >  
[14:28:14.722] > vscode-server.tar.gz                           23%   12MB 407.7KB/s   01:37 ETA
[14:28:15.721] > vscode-server.tar.gz                           24%   12MB 402.2KB/s   01:38 ETA
[14:28:16.721] > vscode-server.tar.gz                           24%   13MB 390.7KB/s   01:40 ETA
[14:28:17.658] >  
[14:28:17.721] > vscode-server.tar.gz                           25%   13MB 374.1KB/s   01:44 ETA
[14:28:18.727] > vscode-server.tar.gz                           25%   13MB 362.3KB/s   01:46 ETA
[14:28:19.721] > vscode-server.tar.gz                           26%   14MB 364.4KB/s   01:45 ETA
[14:28:20.660] >  
[14:28:20.721] > vscode-server.tar.gz                           27%   14MB 366.4KB/s   01:43 ETA
[14:28:21.721] > vscode-server.tar.gz                           28%   15MB 384.1KB/s   01:37 ETA
[14:28:22.729] > vscode-server.tar.gz                           29%   15MB 400.1KB/s   01:32 ETA
[14:28:23.662] >  
[14:28:23.734] > vscode-server.tar.gz                           30%   15MB 401.7KB/s   01:30 ETA
[14:28:24.724] > vscode-server.tar.gz                           30%   16MB 380.7KB/s   01:35 ETA
[14:28:25.722] > vscode-server.tar.gz                           31%   16MB 365.0KB/s   01:38 ETA
[14:28:26.665] >  
[14:28:26.723] > vscode-server.tar.gz                           31%   16MB 354.1KB/s   01:41 ETA
[14:28:27.727] > vscode-server.tar.gz                           32%   17MB 363.5KB/s   01:37 ETA
[14:28:28.730] > vscode-server.tar.gz                           33%   17MB 365.6KB/s   01:35 ETA
[14:28:29.665] >  
[14:28:29.727] > vscode-server.tar.gz                           33%   17MB 357.8KB/s   01:36 ETA
[14:28:30.724] > vscode-server.tar.gz                           34%   18MB 357.2KB/s   01:36 ETA
[14:28:31.724] > vscode-server.tar.gz                           34%   18MB 353.5KB/s   01:36 ETA
[14:28:32.665] >  
[14:28:32.721] > vscode-server.tar.gz                           35%   18MB 340.5KB/s   01:39 ETA
[14:28:33.732] > vscode-server.tar.gz                           35%   18MB 328.9KB/s   01:42 ETA
[14:28:34.722] > vscode-server.tar.gz                           36%   19MB 334.4KB/s   01:39 ETA
[14:28:35.667] >  
[14:28:35.776] > vscode-server.tar.gz                           37%   19MB 352.1KB/s   01:32 ETA
[14:28:36.730] > vscode-server.tar.gz                           38%   20MB 358.4KB/s   01:29 ETA
[14:28:37.732] > vscode-server.tar.gz                           39%   20MB 367.3KB/s   01:26 ETA
[14:28:38.669] >  
[14:28:38.734] > vscode-server.tar.gz                           39%   20MB 365.8KB/s   01:25 ETA
[14:28:39.732] > vscode-server.tar.gz                           40%   21MB 358.0KB/s   01:27 ETA
[14:28:40.736] > vscode-server.tar.gz                           40%   21MB 347.8KB/s   01:28 ETA
[14:28:41.670] >  
[14:28:41.728] > vscode-server.tar.gz                           41%   21MB 354.6KB/s   01:25 ETA
[14:28:42.729] > vscode-server.tar.gz                           42%   22MB 354.3KB/s   01:25 ETA
[14:28:43.751] > vscode-server.tar.gz                           43%   22MB 360.5KB/s   01:22 ETA
[14:28:44.672] >  
[14:28:44.841] > vscode-server.tar.gz                           44%   23MB 372.4KB/s   01:18 ETA
[14:28:45.730] > vscode-server.tar.gz                           44%   23MB 376.8KB/s   01:16 ETA
[14:28:46.729] > vscode-server.tar.gz                           45%   23MB 374.3KB/s   01:16 ETA
[14:28:47.675] >  
[14:28:47.733] > vscode-server.tar.gz                           46%   24MB 368.9KB/s   01:16 ETA
[14:28:48.733] > vscode-server.tar.gz                           46%   24MB 360.7KB/s   01:17 ETA
[14:28:49.732] > vscode-server.tar.gz                           47%   24MB 359.9KB/s   01:16 ETA
[14:28:50.675] >  
[14:28:50.730] > vscode-server.tar.gz                           48%   25MB 368.7KB/s   01:13 ETA
[14:28:51.731] > vscode-server.tar.gz                           48%   25MB 367.0KB/s   01:12 ETA
[14:28:52.731] > vscode-server.tar.gz                           49%   25MB 362.3KB/s   01:12 ETA
[14:28:53.677] >  
[14:28:53.746] > vscode-server.tar.gz                           50%   26MB 351.7KB/s   01:14 ETA
[14:28:54.736] > vscode-server.tar.gz                           50%   26MB 348.5KB/s   01:14 ETA
[14:28:55.733] > vscode-server.tar.gz                           51%   26MB 352.0KB/s   01:12 ETA
[14:28:56.679] >  
[14:28:56.733] > vscode-server.tar.gz                           52%   27MB 352.0KB/s   01:11 ETA
[14:28:57.735] > vscode-server.tar.gz                           52%   27MB 348.8KB/s   01:10 ETA
[14:28:58.735] > vscode-server.tar.gz                           53%   27MB 349.1KB/s   01:09 ETA
[14:28:59.681] >  
[14:28:59.733] > vscode-server.tar.gz                           53%   28MB 349.4KB/s   01:08 ETA
[14:29:00.738] > vscode-server.tar.gz                           54%   28MB 343.2KB/s   01:09 ETA
[14:29:01.733] > vscode-server.tar.gz                           55%   28MB 337.7KB/s   01:09 ETA
[14:29:02.683] >  
[14:29:02.735] > vscode-server.tar.gz                           55%   28MB 335.9KB/s   01:08 ETA
[14:29:03.739] > vscode-server.tar.gz                           56%   29MB 324.7KB/s   01:10 ETA
[14:29:04.734] > vscode-server.tar.gz                           56%   29MB 321.1KB/s   01:10 ETA
[14:29:05.689] >  
[14:29:05.734] > vscode-server.tar.gz                           57%   29MB 311.4KB/s   01:12 ETA
[14:29:06.737] > vscode-server.tar.gz                           57%   29MB 305.8KB/s   01:12 ETA
[14:29:07.734] > vscode-server.tar.gz                           58%   30MB 300.8KB/s   01:12 ETA
[14:29:08.685] >  
[14:29:08.740] > vscode-server.tar.gz                           58%   30MB 293.1KB/s   01:13 ETA
[14:29:09.738] > vscode-server.tar.gz                           58%   30MB 279.8KB/s   01:16 ETA
[14:29:10.735] > vscode-server.tar.gz                           59%   30MB 283.8KB/s   01:14 ETA
[14:29:11.687] >  
[14:29:11.738] > vscode-server.tar.gz                           60%   31MB 287.4KB/s   01:12 ETA
[14:29:12.740] > vscode-server.tar.gz                           60%   31MB 293.9KB/s   01:09 ETA
[14:29:13.735] > vscode-server.tar.gz                           61%   31MB 306.1KB/s   01:05 ETA
[14:29:14.691] >  
[14:29:14.738] > vscode-server.tar.gz                           62%   32MB 304.3KB/s   01:05 ETA
[14:29:15.737] > vscode-server.tar.gz                           62%   32MB 296.2KB/s   01:06 ETA
[14:29:16.735] > vscode-server.tar.gz                           63%   32MB 308.2KB/s   01:02 ETA
[14:29:17.690] >  
[14:29:17.737] > vscode-server.tar.gz                           63%   33MB 303.0KB/s   01:02 ETA
[14:29:18.738] > vscode-server.tar.gz                           64%   33MB 301.5KB/s   01:01 ETA
[14:29:19.738] > vscode-server.tar.gz                           65%   33MB 306.5KB/s   00:59 ETA
[14:29:20.691] >  
[14:29:20.736] > vscode-server.tar.gz                           65%   34MB 307.9KB/s   00:58 ETA
[14:29:21.739] > vscode-server.tar.gz                           66%   34MB 309.1KB/s   00:57 ETA
[14:29:22.741] > vscode-server.tar.gz                           66%   34MB 313.3KB/s   00:55 ETA
[14:29:23.693] >  
[14:29:23.744] > vscode-server.tar.gz                           67%   35MB 326.7KB/s   00:51 ETA
[14:29:24.740] > vscode-server.tar.gz                           68%   35MB 332.4KB/s   00:49 ETA
[14:29:25.741] > vscode-server.tar.gz                           69%   35MB 344.0KB/s   00:46 ETA
[14:29:26.694] >  
[14:29:26.743] > vscode-server.tar.gz                           69%   36MB 335.2KB/s   00:47 ETA
[14:29:27.748] > vscode-server.tar.gz                           70%   36MB 327.3KB/s   00:47 ETA
[14:29:28.743] > vscode-server.tar.gz                           71%   36MB 336.1KB/s   00:44 ETA
[14:29:29.697] >  
[14:29:29.745] > vscode-server.tar.gz                           71%   37MB 344.1KB/s   00:42 ETA
[14:29:30.742] > vscode-server.tar.gz                           72%   37MB 344.9KB/s   00:41 ETA
[14:29:31.744] > vscode-server.tar.gz                           73%   38MB 361.6KB/s   00:38 ETA
[14:29:32.699] >  
[14:29:32.745] > vscode-server.tar.gz                           74%   38MB 357.4KB/s   00:37 ETA
[14:29:33.744] > vscode-server.tar.gz                           74%   38MB 347.2KB/s   00:38 ETA
[14:29:34.747] > vscode-server.tar.gz                           75%   38MB 347.7KB/s   00:37 ETA
[14:29:35.700] >  
[14:29:35.745] > vscode-server.tar.gz                           75%   39MB 338.5KB/s   00:37 ETA
[14:29:36.753] > vscode-server.tar.gz                           76%   39MB 327.0KB/s   00:37 ETA
[14:29:37.747] > vscode-server.tar.gz                           76%   39MB 329.5KB/s   00:36 ETA
[14:29:38.702] >  
[14:29:38.748] > vscode-server.tar.gz                           77%   40MB 334.9KB/s   00:34 ETA
[14:29:39.749] > vscode-server.tar.gz                           78%   40MB 330.2KB/s   00:34 ETA
[14:29:40.750] > vscode-server.tar.gz                           78%   40MB 326.0KB/s   00:34 ETA
[14:29:41.703] >  
[14:29:41.749] > vscode-server.tar.gz                           79%   41MB 328.6KB/s   00:32 ETA
[14:29:42.749] > vscode-server.tar.gz                           80%   41MB 334.1KB/s   00:30 ETA
[14:29:43.749] > vscode-server.tar.gz                           80%   41MB 339.1KB/s   00:29 ETA
[14:29:44.712] >  
[14:29:44.754] > vscode-server.tar.gz                           81%   42MB 343.6KB/s   00:27 ETA
[14:29:45.753] > vscode-server.tar.gz                           82%   42MB 344.4KB/s   00:26 ETA
[14:29:46.755] > vscode-server.tar.gz                           82%   42MB 332.3KB/s   00:27 ETA
[14:29:47.705] >  
[14:29:47.751] > vscode-server.tar.gz                           83%   42MB 321.5KB/s   00:27 ETA
[14:29:48.752] > vscode-server.tar.gz                           83%   43MB 324.5KB/s   00:25 ETA
[14:29:49.751] > vscode-server.tar.gz                           84%   43MB 336.9KB/s   00:23 ETA
[14:29:50.707] >  
[14:29:50.752] > vscode-server.tar.gz                           85%   44MB 335.2KB/s   00:22 ETA
[14:29:51.751] > vscode-server.tar.gz                           86%   44MB 343.3KB/s   00:21 ETA
[14:29:52.750] > vscode-server.tar.gz                           87%   45MB 363.3KB/s   00:18 ETA
[14:29:53.711] >  
[14:29:53.761] > vscode-server.tar.gz                           87%   45MB 365.4KB/s   00:17 ETA
[14:29:54.754] > vscode-server.tar.gz                           88%   45MB 357.6KB/s   00:16 ETA
[14:29:55.751] > vscode-server.tar.gz                           88%   45MB 344.3KB/s   00:16 ETA
[14:29:56.711] >  
[14:29:56.753] > vscode-server.tar.gz                           89%   46MB 338.6KB/s   00:16 ETA
[14:29:57.752] > vscode-server.tar.gz                           89%   46MB 330.4KB/s   00:15 ETA
[14:29:58.773] > vscode-server.tar.gz                           90%   46MB 329.3KB/s   00:15 ETA
[14:29:59.714] >  
[14:29:59.754] > vscode-server.tar.gz                           91%   47MB 334.8KB/s   00:13 ETA
[14:30:00.759] > vscode-server.tar.gz                           91%   47MB 336.5KB/s   00:12 ETA
[14:30:01.755] > vscode-server.tar.gz                           92%   47MB 331.6KB/s   00:11 ETA
[14:30:02.713] >  
[14:30:02.753] > vscode-server.tar.gz                           92%   47MB 317.6KB/s   00:11 ETA
[14:30:03.756] > vscode-server.tar.gz                           93%   48MB 311.5KB/s   00:11 ETA
[14:30:04.757] > vscode-server.tar.gz                           93%   48MB 312.3KB/s   00:10 ETA
[14:30:05.716] >  
[14:30:05.754] > vscode-server.tar.gz                           94%   48MB 306.7KB/s   00:09 ETA
[14:30:06.756] > vscode-server.tar.gz                           94%   48MB 301.6KB/s   00:08 ETA
[14:30:07.757] > vscode-server.tar.gz                           95%   49MB 293.8KB/s   00:08 ETA
[14:30:08.719] >  
[14:30:08.759] > vscode-server.tar.gz                           95%   49MB 286.9KB/s   00:07 ETA
[14:30:09.758] > vscode-server.tar.gz                           96%   49MB 283.7KB/s   00:06 ETA
[14:30:10.759] > vscode-server.tar.gz                           97%   50MB 293.8KB/s   00:05 ETA
[14:30:11.718] >  
[14:30:11.760] > vscode-server.tar.gz                           97%   50MB 306.0KB/s   00:03 ETA
[14:30:12.758] > vscode-server.tar.gz                           98%   50MB 329.8KB/s   00:01 ETA
[14:30:13.761] > vscode-server.tar.gz                           99%   51MB 338.4KB/s   00:00 ETA
[14:30:14.719] >  
[14:30:14.760] > vscode-server.tar.gz                          100%   51MB 343.8KB/s   02:32    
[14:30:15.759] > vscode-server.tar.gz                          100%   51MB 341.6KB/s   02:33    
[14:30:16.760] > vscode-server.tar.gz                          100%   51MB 339.3KB/s   02:34    
[14:30:17.721] >  
[14:30:17.760] > vscode-server.tar.gz                          100%   51MB 337.2KB/s   02:35    
[14:30:18.772] > vscode-server.tar.gz                          100%   51MB 335.0KB/s   02:36    
[14:30:19.761] > vscode-server.tar.gz                          100%   51MB 332.9KB/s   02:37    
[14:30:20.723] >  
[14:30:20.763] > vscode-server.tar.gz                          100%   51MB 330.8KB/s   02:38    
[14:30:21.761] > vscode-server.tar.gz                          100%   51MB 328.7KB/s   02:39    
[14:30:22.196] > 
> vscode-scp-done.flag                            0%    0     0.0KB/s   --:-- ETA
[14:30:22.263] > vscode-scp-done.flag                          100%    9     0.1KB/s   00:00    
[14:30:23.575] "Copy server to host" terminal command done
[14:30:23.725] > Found flag and server on host
[14:30:23.727] > e58b587e1c70%%2%%
> tar --version:
[14:30:23.728] > tar (GNU tar) 1.30
> Copyright (C) 2017 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[14:30:24.871] > ERROR: /home/gaohuazuo/.vscode-server-insiders/bin/7b9e5c32a053669d4e72f998e4fa217090c32f59/node or /home/gaohuazuo/.vscode-server-insiders/bin/7b9e5c32a053669d4e72f998e4fa217090c32f59/bin/undefined don't exist
> Already attempted local download, failing
> e58b587e1c70: start
> exitCode==37==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/10649==
> platform==linux==
> unpackResult==missingFiles==
> didLocalDownload==1==
> downloadTime====
> installTime==1141==
> extInstallTime====
> serverStartTime====
> e58b587e1c70: end
[14:30:24.873] Received install output: 
exitCode==37==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/10649==
platform==linux==
unpackResult==missingFiles==
didLocalDownload==1==
downloadTime====
installTime==1141==
extInstallTime====
serverStartTime====

[14:30:24.874] Terminating local server
[14:30:24.877] Resolver error: Error: Failed to install the VS Code Server
	at Function.ServerInstallError (/home/gaohuazuo/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:585851)
	at p (/home/gaohuazuo/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:580122)
	at Object.t.handleInstallOutput (/home/gaohuazuo/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:582985)
	at Object.e [as tryInstallWithLocalServer] (/home/gaohuazuo/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:624925)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/gaohuazuo/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:643015
	at async Object.t.withShowDetailsEvent (/home/gaohuazuo/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:646762)
	at async /home/gaohuazuo/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:623397
	at async b (/home/gaohuazuo/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:619903)
	at async Object.t.resolveWithLocalServer (/home/gaohuazuo/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:623012)
	at async Object.t.resolve (/home/gaohuazuo/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:644372)
	at async /home/gaohuazuo/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.74.0/out/extension.js:1:721503
[14:30:24.887] ------




[14:30:24.895] Local server exit: 15
```

Steps to Reproduce:

1. `rm -rf ~/.vscode-server-insiders` on server
2. `>Developer: Reload Window`
3. `ls -l /home/gaohuazuo/.vscode-server-insiders/bin/7b9e5c32a053669d4e72f998e4fa217090c32f59/node` on server to verify that the file does exist
  `-rwxr-xr-x 1 gaohuazuo gaohuazuo 71M Dec 22 13:16 /home/gaohuazuo/.vscode-server-insiders/bin/7b9e5c32a053669d4e72f998e4fa217090c32f59/node`

Versions tried:
0.75.2022022115 bad
0.74.0 bad
0.72.0 bad
0.70.0 good

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A

**Comment by tanhakabir** [comment]
Would you mind updating VS Code to see if you see have an issue? `1.64.0-insider` is an old version of VS Code

**Comment by gaohuazuo** [comment]
1.65.0-insider with 0.74.0 works fine.
