### ISSUE TITLE
The VS Code Server failed to start - node: not found

### ISSUE THREAD

**Issue by qbaj** [microsoft/vscode-remote-release#6388]
- VSCode Version: 1.64.2
- Local OS Version: Win10 Pro 64bit
- Remote OS Version: RPi4 with Raspbian GNU/Linux 11 (bullseye) aarch64
- Remote Extension/Connection Type: SSH
- Logs:
VSCode:
```
[22:59:52.128] Log Level: 2
[22:59:52.129] remote-ssh@0.74.0
[22:59:52.129] win32 x64
[22:59:52.137] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a2251506932227d", attempt 1
[22:59:52.137] "remote.SSH.useLocalServer": false
[22:59:52.137] "remote.SSH.showLoginTerminal": false
[22:59:52.137] "remote.SSH.remotePlatform": {}
[22:59:52.138] "remote.SSH.path": undefined
[22:59:52.138] "remote.SSH.configFile": undefined
[22:59:52.138] "remote.SSH.useFlock": true
[22:59:52.138] "remote.SSH.lockfilesInTmp": false
[22:59:52.138] "remote.SSH.localServerDownload": auto
[22:59:52.138] "remote.SSH.remoteServerListenOnSocket": false
[22:59:52.138] "remote.SSH.showLoginTerminal": false
[22:59:52.139] "remote.SSH.defaultExtensions": []
[22:59:52.139] "remote.SSH.loglevel": 2
[22:59:52.139] "remote.SSH.enableDynamicForwarding": true
[22:59:52.139] "remote.SSH.enableRemoteCommand": false
[22:59:52.139] "remote.SSH.serverPickPortsFromRange": {}
[22:59:52.139] "remote.SSH.serverInstallPath": {}
[22:59:52.157] SSH Resolver called for host: QPi2
[22:59:52.157] Setting up SSH remote "QPi2"
[22:59:52.162] Using commit id "f80445acd5a3dadef24aa209168452a3d97cc326" and quality "stable" for server
[22:59:52.165] Install and start server if needed
[22:59:53.263] Checking ssh with "ssh -V"
[22:59:53.301] > OpenSSH_for_Windows_8.1p1, LibreSSL
[22:59:53.301] >  3.0.2

[22:59:53.307] Running script with connection command: ssh -T -D 55420 "QPi2" bash
[22:59:53.309] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[22:59:53.543] > ]0;C:\WINDOWS\System32\cmd.exe
[22:59:53.544] Got some output, clearing connection timeout
[22:59:53.746] > pi@qpi2's password: 
[22:59:53.747] Showing password prompt
[23:00:01.303] Got password response
[23:00:01.303] "install" wrote data to terminal: "*********"
[23:00:01.321] > 
[23:00:02.373] > 79e5fa0b0858: running
[23:00:02.435] > Acquiring lock on /home/pi/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d9
> 7cc326/vscode-remote-lock.pi.f80445acd5a3dadef24aa209168452a3d97cc326
[23:00:02.451] > Installing to /home/pi/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc3
> 26...
[23:00:02.466] > 79e5fa0b0858%%1%%    
> Downloading with wget
[23:00:06.730] > Download complete
[23:00:06.741] > 79e5fa0b0858%%2%%
> tar --version:
> tar (GNU tar) 1.34
> Copyright (C) 2021 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[23:00:09.209] > Checking /home/pi/.vscode-server/.f80445acd5a3dadef24aa209168452a3d97cc326.log a
> nd /home/pi/.vscode-server/.f80445acd5a3dadef24aa209168452a3d97cc326.pid for a r
> unning server
[23:00:09.254] > Starting server with command... /home/pi/.vscode-server/bin/f80445acd5a3dadef24a
> a209168452a3d97cc326/bin/code-server --start-server --host=127.0.0.1 --accept-se
> rver-license-terms --enable-remote-auto-shutdown --port=0    &> "/home/pi/.vscod
> e-server/.f80445acd5a3dadef24aa209168452a3d97cc326.log" < /dev/null
> printenv:
>     SHELL=/bin/bash     
>     PWD=/home/pi        
>     LOGNAME=pi
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/home/pi
>     LANG=en_GB.UTF-8
>     VSCODE_AGENT_FOLDER=/home/pi/.vscode-server
>     SSH_CONNECTION=192.168.1.24 55422 192.168.1.4 22
>     XDG_SESSION_CLASS=user
>     USER=pi
>     SHLVL=0
[23:00:09.258] > 
>     XDG_SESSION_ID=6
>     XDG_RUNTIME_DIR=/run/user/1000
>     SSH_CLIENT=192.168.1.24 55422 22
>     PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
>     OLDPWD=/home/pi/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326 
>     _=/usr/bin/printenv
> rm: cannot remove '/home/pi/.vscode-server/.f80445acd5a3dadef24aa209168452a3d97c
> c326.token'Spawned remote server: 3382
> : No such file or directory
> Waiting for server log...
[23:00:09.274] > 
[23:00:09.299] > Waiting for server log...
[23:00:09.345] > Waiting for server log...
[23:00:09.379] > Waiting for server log...
[23:00:09.412] > Waiting for server log...
[23:00:09.447] > Waiting for server log...
[23:00:09.483] > Waiting for server log...
[23:00:09.521] > Waiting for server log...
[23:00:09.559] > Waiting for server log...
[23:00:09.598] > Waiting for server log...
[23:00:09.634] > Waiting for server log...
[23:00:09.671] > Waiting for server log...
[23:00:09.708] > Waiting for server log...
[23:00:09.746] > Waiting for server log...
[23:00:09.784] > Waiting for server log...
[23:00:09.822] > Waiting for server log...
[23:00:09.859] > Waiting for server log...
[23:00:09.896] > Waiting for server log...
[23:00:09.934] > Waiting for server log...
[23:00:09.974] > Waiting for server log...
[23:00:10.010] > Waiting for server log...
[23:00:10.046] > Waiting for server log...
[23:00:10.085] > Waiting for server log...
[23:00:10.124] > Waiting for server log...
[23:00:10.161] > Waiting for server log...
[23:00:10.198] > Waiting for server log...
[23:00:10.236] > Waiting for server log...
[23:00:10.274] > Waiting for server log...
[23:00:10.313] > Waiting for server log...
[23:00:10.352] > Waiting for server log...
[23:00:10.399] > Waiting for server log...
[23:00:10.428] > Waiting for server log...
[23:00:10.465] > Waiting for server log...
[23:00:10.505] > Waiting for server log...
[23:00:10.542] > Waiting for server log...
[23:00:10.582] > Waiting for server log...
[23:00:10.619] > Waiting for server log...
[23:00:10.657] > Waiting for server log...
[23:00:10.694] > Waiting for server log...
[23:00:10.733] > Waiting for server log...
[23:00:10.769] > Waiting for server log...
[23:00:10.807] > Waiting for server log...
[23:00:10.845] > Waiting for server log...
[23:00:10.882] > Waiting for server log...
[23:00:10.921] > Waiting for server log...
[23:00:10.959] > Waiting for server log...
[23:00:10.997] > Waiting for server log...
[23:00:11.034] > Waiting for server log...
[23:00:11.072] > Waiting for server log...
[23:00:11.111] > Waiting for server log...
[23:00:11.150] > Waiting for server log...
[23:00:11.185] > Waiting for server log...
[23:00:11.225] > Waiting for server log...
[23:00:11.262] > Waiting for server log...
[23:00:11.299] > Waiting for server log...
[23:00:11.338] > Waiting for server log...
[23:00:11.375] > Waiting for server log...
[23:00:11.413] > Waiting for server log...
[23:00:11.454] > Waiting for server log...
[23:00:11.489] > Waiting for server log...
[23:00:11.528] > Waiting for server log...
[23:00:11.567] > Waiting for server log...
[23:00:11.604] > Waiting for server log...
[23:00:11.641] > Waiting for server log...
[23:00:11.679] > Waiting for server log...
[23:00:11.716] > Waiting for server log...
[23:00:11.754] > Waiting for server log...
[23:00:11.792] > Waiting for server log...
[23:00:11.831] > Waiting for server log...
[23:00:11.869] > Waiting for server log...
[23:00:11.905] > Waiting for server log...
[23:00:11.941] > Waiting for server log...
[23:00:11.980] > Waiting for server log...
[23:00:12.018] > Waiting for server log...
[23:00:12.070] > Waiting for server log...
[23:00:12.092] > Waiting for server log...
[23:00:12.129] > Waiting for server log...
[23:00:12.167] > Waiting for server log...
[23:00:12.204] > Waiting for server log...
[23:00:12.242] > Waiting for server log...
[23:00:12.280] > Waiting for server log...
[23:00:12.317] > Waiting for server log...
[23:00:12.355] > Waiting for server log...
[23:00:12.401] > Waiting for server log...
[23:00:12.430] > Waiting for server log...
[23:00:12.469] > Waiting for server log...
[23:00:12.504] > Waiting for server log...
[23:00:12.543] > Waiting for server log...
[23:00:12.581] > Waiting for server log...
[23:00:12.619] > Waiting for server log...
[23:00:12.656] > Waiting for server log...
[23:00:12.695] > Waiting for server log...
[23:00:12.731] > Waiting for server log...
[23:00:12.769] > Waiting for server log...
[23:00:12.807] > Waiting for server log...
[23:00:12.845] > Waiting for server log...
[23:00:12.883] > Waiting for server log...
[23:00:12.920] > Waiting for server log...
[23:00:12.957] > Waiting for server log...
[23:00:12.997] > Waiting for server log...
[23:00:13.032] > Waiting for server log...
[23:00:13.070] > Waiting for server log...
[23:00:13.107] > Waiting for server log...
[23:00:13.144] > Waiting for server log...
[23:00:13.184] > Waiting for server log...
[23:00:13.220] > Waiting for server log...
[23:00:13.258] > Waiting for server log...
[23:00:13.296] > Waiting for server log...
[23:00:13.335] > Waiting for server log...
[23:00:13.372] > Waiting for server log...
[23:00:13.408] > Waiting for server log...
[23:00:13.448] > Waiting for server log...
[23:00:13.483] > Waiting for server log...
[23:00:13.521] > Waiting for server log...
[23:00:13.561] > Waiting for server log...
[23:00:13.597] > Waiting for server log...
[23:00:13.634] > Waiting for server log...
[23:00:13.673] > Waiting for server log...
[23:00:13.708] > Waiting for server log...
[23:00:13.747] > Waiting for server log...
[23:00:13.784] > Waiting for server log...
[23:00:13.821] > Waiting for server log...
[23:00:13.858] > Waiting for server log...
[23:00:13.897] > Waiting for server log...
[23:00:13.934] > Waiting for server log...
[23:00:13.972] > Waiting for server log...
[23:00:14.011] > Waiting for server log...
[23:00:14.054] > Waiting for server log...
[23:00:14.097] > Waiting for server log...
[23:00:14.140] > Waiting for server log...
[23:00:14.183] > Waiting for server log...
[23:00:14.225] > Waiting for server log...
[23:00:14.268] > Waiting for server log...
[23:00:14.312] > Waiting for server log...
[23:00:14.354] > Waiting for server log...
[23:00:14.403] > Waiting for server log...
[23:00:14.441] > Waiting for server log...
[23:00:14.485] > Waiting for server log...
[23:00:14.528] > Waiting for server log...
[23:00:14.568] > Waiting for server log...
[23:00:14.610] > Waiting for server log...
[23:00:14.655] > Waiting for server log...
[23:00:14.698] > Waiting for server log...
[23:00:14.740] > Waiting for server log...
[23:00:14.781] > Waiting for server log...
[23:00:14.825] > Waiting for server log...
[23:00:14.866] > Waiting for server log...
[23:00:14.909] > Waiting for server log...
[23:00:14.954] > Waiting for server log...
[23:00:14.997] > Waiting for server log...
[23:00:15.039] > Waiting for server log...
[23:00:15.080] > Waiting for server log...
[23:00:15.124] > Waiting for server log...
[23:00:15.167] > Waiting for server log...
[23:00:15.211] > Waiting for server log...
[23:00:15.255] > Waiting for server log...
[23:00:15.300] > Waiting for server log...
[23:00:15.342] > Waiting for server log...
[23:00:15.383] > Waiting for server log...
[23:00:15.427] > Waiting for server log...
[23:00:15.470] > Waiting for server log...
[23:00:15.512] > Waiting for server log...
[23:00:15.556] > Waiting for server log...
[23:00:15.599] > Waiting for server log...
[23:00:15.643] > Waiting for server log...
[23:00:15.685] > Waiting for server log...
[23:00:15.727] > Waiting for server log...
[23:00:15.771] > Waiting for server log...
[23:00:15.815] > Waiting for server log...
[23:00:15.858] > Waiting for server log...
[23:00:15.901] > Waiting for server log...
[23:00:15.944] > Waiting for server log...
[23:00:15.987] > Waiting for server log...
[23:00:16.030] > Waiting for server log...
[23:00:16.073] > Waiting for server log...
[23:00:16.115] > Waiting for server log...
[23:00:16.161] > Waiting for server log...
[23:00:16.203] > Waiting for server log...
[23:00:16.248] > Waiting for server log...
[23:00:16.289] > Waiting for server log...
[23:00:16.330] > Waiting for server log...
[23:00:16.373] > Waiting for server log...
[23:00:16.418] > Waiting for server log...
[23:00:16.459] > Waiting for server log...
[23:00:16.503] > Waiting for server log...
[23:00:16.545] > Waiting for server log...
[23:00:16.588] > Waiting for server log...
[23:00:16.630] > Waiting for server log...
[23:00:16.674] > Waiting for server log...
[23:00:16.717] > Waiting for server log...
[23:00:16.760] > Waiting for server log...
[23:00:16.805] > Waiting for server log...
[23:00:16.845] > Waiting for server log...
[23:00:16.887] > Waiting for server log...
[23:00:16.931] > Waiting for server log...
[23:00:16.974] > Waiting for server log...
[23:00:17.017] > Waiting for server log...
[23:00:17.058] > Waiting for server log...
[23:00:17.102] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
[23:00:17.119] > 
> Server did not start successfully. Full server log at /home/pi/.vscode-server/.f
> 80445acd5a3dadef24aa209168452a3d97cc326.log >>>
> /home/pi/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/bin/code-se
> rver: 12: /home/pi/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/n
> ode: not found
> <<< End of server log
> 79e5fa0b0858: start
> exitCode==32==
> listeningOn====
> osReleaseId==raspbian==
> arch==aarch64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult==success==
[23:00:17.124] > 
> didLocalDownload==0==
> downloadTime==4266==
> installTime==2451==
> extInstallTime====
> serverStartTime==7854==
> 79e5fa0b0858: end
[23:00:17.124] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==raspbian==
arch==aarch64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult==success==
didLocalDownload==0==
downloadTime==4266==
installTime==2451==
extInstallTime====
serverStartTime==7854==

[23:00:17.125] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (c:\Users\qbaj\.vscode\extensions\ms-vscode-remote.remote-ssh-0.74.0\out\extension.js:1:585851)
	at p (c:\Users\qbaj\.vscode\extensions\ms-vscode-remote.remote-ssh-0.74.0\out\extension.js:1:579700)
	at Object.t.handleInstallOutput (c:\Users\qbaj\.vscode\extensions\ms-vscode-remote.remote-ssh-0.74.0\out\extension.js:1:582985)
	at Object.t.tryInstall (c:\Users\qbaj\.vscode\extensions\ms-vscode-remote.remote-ssh-0.74.0\out\extension.js:1:680558)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\qbaj\.vscode\extensions\ms-vscode-remote.remote-ssh-0.74.0\out\extension.js:1:643417
	at async Object.t.withShowDetailsEvent (c:\Users\qbaj\.vscode\extensions\ms-vscode-remote.remote-ssh-0.74.0\out\extension.js:1:646762)
	at async Object.t.resolve (c:\Users\qbaj\.vscode\extensions\ms-vscode-remote.remote-ssh-0.74.0\out\extension.js:1:644496)
	at async c:\Users\qbaj\.vscode\extensions\ms-vscode-remote.remote-ssh-0.74.0\out\extension.js:1:721503
[23:00:17.128] ------




[23:00:17.536] > 
[23:00:18.426] "install" terminal command done
[23:00:18.427] Install terminal quit with output: 
```
RPi4:
```
/home/pi/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/bin/code-server: 12: /home/pi/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/node: not found
```

**Comment by tanhakabir** [comment]
@aeschli is there a reason why `code-server` might not be found in the download?

**Comment by qbaj** [comment]
- On RPi4 there is .vscode-server with files:
'''

pi@QPi2:~/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326 $ ls -ltotal 70804
drwxr-xr-x   4 pi pi     4096 Feb  9 22:02 bin
drwxr-xr-x  33 pi pi     4096 Feb  9 22:02 extensions
-rw-r--r--   1 pi pi    13380 Feb  9 22:00 LICENSE
-rwxr-xr-x   1 pi pi 72420328 Feb  9 22:02 node
drwxr-xr-x 119 pi pi     4096 Feb  9 22:02 node_modules
drwxr-xr-x   3 pi pi     4096 Feb  9 22:02 out
-rw-r--r--   1 pi pi       62 Feb  9 22:00 package.json
-rw-r--r--   1 pi pi    35791 Feb  9 22:02 product.json
-rwxr-xr-x   1 pi pi      240 Feb  9 21:59 server.sh
'''

**Comment by aeschli** [comment]
No idea why node can not be executed here.
I verified it's the `vscode-server-linux-arm64` bits which should match the platform.
@joaomoreno  Any idea?

**Comment by qbaj** [comment]
Wrong cross compilation?
From file:
```
pi@QPi2:~/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326 $ file node
node: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=72a8038142f9a08302dd214af5024652a26afbe0, with debug_info, not stripped
```

On RPi4 with Raspbian GNU/Linux 11 (bullseye) aarch64:
```
pi@QPi2:~/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326 $ ls /lib/ld*
/lib/ld-linux-armhf.so.3  /lib/ld-linux.so.3
```

**Comment by qbaj** [comment]
My Raspbian has aarch64 (64 bit kernel), but i think 32 bit user space probably.
After changing in /boot/config.txt
> arm_64bit = 0
```
pi@QPi2:~ $ uname -a
Linux QPi2 5.10.92-v7l+ #1514 SMP Mon Jan 17 17:38:03 GMT 2022 armv7l GNU/Linux
```
And it works! SUCCESS!

**Comment by tanhakabir** [comment]
Oh yes it looked like you had `server.sh` and not `code-server`.  We packaged our scripts with a different name in most recent versions so it was probably conflicting with an old version of the server.

Closing this issue now since it seems to be fixed

**Comment by aeschli** [comment]
@tanhakabir Looks to me like this was a platform mismatch as `node` also couldn't started (see [comment](https://github.com/microsoft/vscode-remote-release/issues/6388#issuecomment-1050633588)). Maybe that's something the Remote-SSH extension could have discovered and warned about?
