### ISSUE TITLE
"Try a development container sample" doesn't work on remote server (through ssh)

### ISSUE THREAD

**Issue by Cyber1000** [microsoft/vscode-remote-release#6389]
- VSCode Version: 1.64.0
- Local OS Version: Windows 10 
- Remote OS Version: Rasberry OS 64bit arm (dietpi)
- Remote Extension/Connection Type: SSH (on the Rasberry/arm side I'm using docker)

Does this issue occur when you try this locally?: No

Steps to Reproduce:
- ssh from Win x86 to Linux arm (architecture may not be relevant)
- Open "try a development container sample ..." with dotnet-core doesn't start a container, instead this happens (see the logs below)
- Creating a folder + "add dev container configuration files"  (dotnetcore) + starting this container works on remote trough ssh, but (as said) "Try a development container sample" just fails, at least for me.

Any idea?

Thanks!

---
logs:

> [92 ms] Remote-Containers 0.217.4 in VS Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326).
[91 ms] Start: Resolving Remote
[99 ms] Start: Run: C:\Program Files\OpenSSH-Win64\ssh.exe docker-dev-server /bin/sh -c /bin/sh
[117 ms] Start: Run in host: id -un
[499 ms] dietpi
[501 ms] 
[505 ms] Start: Run in host: cat /etc/passwd
[519 ms] Start: Run in host: echo ~
[537 ms] /home/dietpi
[540 ms] 
[547 ms] Start: Run in host: test -x '/home/dietpi/.vscode-remote-containers/bin/f80445acd5a3dadef24aa209168452a3d97cc326/node'
[555 ms] 
[556 ms] 
[558 ms] Exit code 1
[561 ms] Start: Run in host: test -x '/home/dietpi/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/node'
[568 ms] 
[568 ms] 
[570 ms] Start: Run in host: test -f '/home/dietpi/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/node_modules/node-pty/package.json'
[583 ms] 
[583 ms] 
[584 ms] Start: Run in host: test -f '/home/dietpi/.vscode-remote-containers/dist/vscode-remote-containers-server-0.217.4.js'
[588 ms] 
[589 ms] 
[597 ms] userEnvProbe: loginInteractiveShell (default)
[598 ms] userEnvProbe shell: /bin/bash
[800 ms] Host server: (node:2434) UnhandledPromiseRejectionWarning: Error: spawn /bin/bash ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2434) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2434) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[817 ms] Error: spawn /bin/bash ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[819 ms] Host server: (node:2434) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
[848 ms] Host server: (node:2434) UnhandledPromiseRejectionWarning: Error: spawn cat ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[852 ms] Host server: (node:2434) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[860 ms] Host server: (node:2434) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
[879 ms] Error: Could not read file: /etc/passwd
        at Object.readFile (c:\Users\Harald\.vscode\extensions\ms-vscode-remote.remote-containers-0.217.4\dist\extension\extension.js:243:19454)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at async Object.homedir (c:\Users\Harald\.vscode\extensions\ms-vscode-remote.remote-containers-0.217.4\dist\extension\extension.js:243:18904)
        at async yL (c:\Users\Harald\.vscode\extensions\ms-vscode-remote.remote-containers-0.217.4\dist\extension\extension.js:453:684)
        at async Uc (c:\Users\Harald\.vscode\extensions\ms-vscode-remote.remote-containers-0.217.4\dist\extension\extension.js:453:20898)
        at async c:\Users\Harald\.vscode\extensions\ms-vscode-remote.remote-containers-0.217.4\dist\extension\extension.js:457:6371
[879 ms] Exit code ENOENT

In vscode insiders (1.65.0) I'm getting similar (same location of error, but little bit different):

> [122 ms] Remote-Containers 0.223.0 in VS Code 1.65.0-insider (3112460dc48ce7e557ea9feeaae04b912164b48b).
[122 ms] Start: Resolving Remote
[132 ms] Start: Run: ssh docker-dev-server /bin/sh
[188 ms] Start: Run in host: id -un
[805 ms] dietpi
[806 ms] 
[808 ms] Start: Run in host: cat /etc/passwd
[822 ms] Start: Run in host: echo ~
[832 ms] /home/dietpi
[834 ms] 
[836 ms] Start: Run in host: test -x '/home/dietpi/.vscode-remote-containers/bin/3112460dc48ce7e557ea9feeaae04b912164b48b/node'
[846 ms] 
[847 ms] 
[848 ms] Exit code 1
[850 ms] Start: Run in host: test -x '/home/dietpi/.vscode-server-insiders/bin/3112460dc48ce7e557ea9feeaae04b912164b48b/node'
[858 ms] 
[861 ms] 
[863 ms] Start: Run in host: test -f '/home/dietpi/.vscode-server-insiders/bin/3112460dc48ce7e557ea9feeaae04b912164b48b/node_modules/node-pty/package.json'
[871 ms] 
[872 ms] 
[873 ms] Start: Run in host: test -f '/home/dietpi/.vscode-remote-containers/dist/vscode-remote-containers-server-0.223.0.js'
[884 ms] 
[884 ms] 
[895 ms] userEnvProbe: loginInteractiveShell (default)
[897 ms] userEnvProbe shell: /bin/bash
[1061 ms] Host server: node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^
Error: spawn /bin/bash ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /bin/bash',
  path: '/bin/bash',
  spawnargs: [
    '-lic',
    `'/home/dietpi/.vscode-server-insiders/bin/3112460dc48ce7e557ea9feeaae04b912164b48b/node' -p '"b3690f8fc13ab01ae04c1d8b65031ed9" + JSON.stringify(process.env) + "b3690f8fc13ab01ae04c1d8b65031ed9"'`
  ]
}
[1065 ms] Host server: /bin/sh: 9: ����false����false: not found
[1066 ms] Host server: /bin/sh: 10: +{name:[stdin],args:[0],type:sink}: not found
/bin/sh: 11: .{name:[stdout],args:[0],type:source}: not found
[2912 ms] Start: Run in Host: /bin/sh 
[10908 ms] userEnvProbe is taking longer than 10 seconds. Avoid waiting for user input in your shell's startup scripts. Continuing.

**Comment by peter11244** [comment]
I'm also having this issue. Please update if a workaround is found.
Running Remote Containers on a local windows machine into docker running on a VM using the DOCKER_HOST env var.

**Comment by chrmarti** [comment]
@Cyber1000 The error suggests that `/bin/bash` cannot be found on your SSH server. Did you connect to the SSH server using Remote-SSH first and then run the "Try Sample" command?

**Comment by Cyber1000** [comment]
Yes, remote-ssh first and then "try sample". Retried now with version 1.65.2 (and vscode insider 1.66), same problem.
If I remote-ssh and open up a terminal I can execute/find /bin/bash and /bin/sh. 
I can't read from the log that /bin/bash is missing, can you point me to that location?
Is there something I may execute manually to track that down?
> test -f '/home/dietpi/.vscode-remote-containers/dist/vscode-remote-containers-server-0.217.4.js'

Says the file is there, but I can't see what gets really executed (and fails) afterwards, at least nothing I can read off that log.

--- 

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/1142765/160257611-9357c149-ab1c-4481-8062-647ce34b031b.png">

**Comment by chrmarti** [comment]
`Error: spawn /bin/bash ENOENT` suggests it can't find Bash, but it could also indicate that the working directory does not exist.

Could you retry with trace logging for Remote-Containers enabled in the user settings and post that log here?
<img width="375" alt="image" src="https://user-images.githubusercontent.com/9205389/160564768-a832f7e0-3504-41e5-93a4-a974bd58eb6c.png">
