### ISSUE TITLE
Missing GLIBC >= 2.17! > Found version for Alpine Linux v3.15 OS

### ISSUE THREAD

**Issue by andodeki** [microsoft/vscode-remote-release#6397]
[17:25:27.379] Log Level: 2
[17:25:27.381] remote-ssh@0.75.2022021815
[17:25:27.381] linux x64
[17:25:27.386] SSH Resolver called for "ssh-remote+godev", attempt 1
[17:25:27.387] "remote.SSH.useLocalServer": true
[17:25:27.387] "remote.SSH.path": undefined
[17:25:27.387] "remote.SSH.configFile": undefined
[17:25:27.388] "remote.SSH.useFlock": true
[17:25:27.388] "remote.SSH.lockfilesInTmp": false
[17:25:27.388] "remote.SSH.localServerDownload": auto
[17:25:27.388] "remote.SSH.remoteServerListenOnSocket": false
[17:25:27.389] "remote.SSH.showLoginTerminal": false
[17:25:27.389] "remote.SSH.defaultExtensions": []
[17:25:27.389] "remote.SSH.loglevel": 2
[17:25:27.389] "remote.SSH.enableDynamicForwarding": true
[17:25:27.389] "remote.SSH.enableRemoteCommand": false
[17:25:27.390] "remote.SSH.serverPickPortsFromRange": {}
[17:25:27.390] "remote.SSH.serverInstallPath": {}
[17:25:27.405] SSH Resolver called for host: godev
[17:25:27.405] Setting up SSH remote "godev"
[17:25:27.409] Acquiring local install lock: /tmp/vscode-remote-ssh-80186c9a-install.lock
[17:25:27.412] Looking for existing server data file at /home/aok-1/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-80186c9a-f80445acd5a3dadef24aa209168452a3d97cc326-0.75.2022021815/data.json
[17:25:27.413] Using commit id "f80445acd5a3dadef24aa209168452a3d97cc326" and quality "stable" for server
[17:25:27.419] Install and start server if needed
[17:25:27.426] PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[17:25:27.427] Checking ssh with "ssh -V"
[17:25:27.453] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020

[17:25:27.460] askpass server listening on /run/user/1000/snap.code/vscode-ssh-askpass-6d85b101042bb94f4c4a319fc4f1b991db7cc117.sock
[17:25:27.460] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/snap.code/vscode-ssh-askpass-7c41211645af5707d93b2109de25fdf48d694da8.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","44089","-o","ConnectTimeout=15","godev"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/aok-1/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-80186c9a-f80445acd5a3dadef24aa209168452a3d97cc326-0.75.2022021815/data.json"}
[17:25:27.460] Local server env: {"DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/aok-1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022021815/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/snap/code/88/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/aok-1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022021815/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/snap.code/vscode-ssh-askpass-6d85b101042bb94f4c4a319fc4f1b991db7cc117.sock"}
[17:25:27.467] Spawned 143763
[17:25:27.598] > local-server-1> Spawned ssh, pid=143771
[17:25:27.599] stderr> OpenSSH_8.2p1 Ubuntu-4ubuntu0.1, OpenSSL 1.1.1f  31 Mar 2020
[17:25:27.625] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:wgbZdzxt7kyNJEYMUjpqnbWx97SGazcBkxhRhuW2Eyw
[17:25:27.778] Got askpass request: {"request":"godev@10.38.195.138's password:"}
[17:25:27.779] Showing password prompt
[17:25:27.781] Listening for interwindow password on /run/user/1000/snap.code/vscode-ssh-askpass-1629c5a4d649477ea59a9cde3ad840cc06aa7a77.sock
[17:25:27.781] Writing password prompt to globalState
[17:25:31.495] Got password response
[17:25:31.496] Interactor gave response: ********
[17:25:31.497] Cleaning up other-window auth server
[17:25:31.528] stderr> Authenticated to 10.38.195.138 ([10.38.195.138]:22).
[17:25:31.540] > ready: da7e05f15385
[17:25:31.542] > Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020
[17:25:31.542] Platform: linux
[17:25:31.543] > /bin/zsh
[17:25:31.543] Shell: zsh
[17:25:31.543] Creating bash subshell inside "zsh"
[17:25:31.546] > bash version:  5.1.16(1)-release
[17:25:31.568] > da7e05f15385: running
[17:25:31.577] stderr> Illegal option -p
[17:25:31.580] stderr> musl libc (x86_64)
[17:25:31.580] stderr> Version 1.2.2
[17:25:31.580] stderr> Dynamic Program Loader
[17:25:31.580] stderr> Usage: /lib/ld-musl-x86_64.so.1 [options] [--] pathname
[17:25:31.581] > Missing GLIBC >= 2.17!
> Found version 
> da7e05f15385$$1$$
[17:25:31.583] > Acquiring lock on /home/godev/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/vscode-remote-lock.godev.f80445acd5a3dadef24aa209168452a3d97cc326
[17:25:31.590] > Found existing installation at /home/godev/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326...
> Checking /home/godev/.vscode-server/.f80445acd5a3dadef24aa209168452a3d97cc326.log and /home/godev/.vscode-server/.f80445acd5a3dadef24aa209168452a3d97cc326.pid for a running server
[17:25:31.592] > Looking for server with pid: 2063
[17:25:31.602] > Starting server with command... /home/godev/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all   &> "/home/godev/.vscode-server/.f80445acd5a3dadef24aa209168452a3d97cc326.log" < /dev/null
> printenv:
[17:25:31.603] >     SHELL=/bin/zsh
>     CHARSET=UTF-8
>     PWD=/home/godev
>     LOGNAME=godev
>     HOME=/home/godev
>     LANG=C.UTF-8
>     VSCODE_AGENT_FOLDER=/home/godev/.vscode-server
>     SSH_CONNECTION=10.38.195.1 53428 10.38.195.138 22
>     USER=godev
>     SHLVL=1
>     PAGER=less
>     SSH_CLIENT=10.38.195.1 53428 22
>     LC_COLLATE=C
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
>     MAIL=/var/mail/godev
>     OLDPWD=/home/godev
>     _=/bin/printenv
[17:25:31.609] > Removing old logfile at /home/godev/.vscode-server/.f80445acd5a3dadef24aa209168452a3d97cc326.log
[17:25:31.611] > Spawned remote server: 6141
[17:25:31.615] > Waiting for server log...
[17:25:31.653] > Waiting for server log...
[17:25:31.690] > Waiting for server log...
[17:25:31.724] > Waiting for server log...
[17:25:31.758] > Waiting for server log...
[17:25:31.794] > Waiting for server log...
[17:25:31.828] > Waiting for server log...
[17:25:31.864] > Waiting for server log...
[17:25:31.900] > Waiting for server log...
[17:25:31.939] > Waiting for server log...
[17:25:31.976] > Waiting for server log...
[17:25:32.013] > Waiting for server log...
[17:25:32.050] > Waiting for server log...
[17:25:32.087] > Waiting for server log...
[17:25:32.126] > Waiting for server log...
[17:25:32.163] > Waiting for server log...
[17:25:32.202] > Waiting for server log...
[17:25:32.240] > Waiting for server log...
[17:25:32.279] > Waiting for server log...
[17:25:32.316] > Waiting for server log...
[17:25:32.355] > Waiting for server log...
[17:25:32.394] > Waiting for server log...
[17:25:32.430] > Waiting for server log...
[17:25:32.467] > Waiting for server log...
[17:25:32.506] > Waiting for server log...
[17:25:32.544] > Waiting for server log...
[17:25:32.583] > Waiting for server log...
[17:25:32.621] > Waiting for server log...
[17:25:32.660] > Waiting for server log...
[17:25:32.698] > Waiting for server log...
[17:25:32.736] > Waiting for server log...
[17:25:32.775] > Waiting for server log...
[17:25:32.813] > Waiting for server log...
[17:25:32.849] > Waiting for server log...
[17:25:32.887] > Waiting for server log...
[17:25:32.927] > Waiting for server log...
[17:25:32.966] > Waiting for server log...
[17:25:33.003] > Waiting for server log...
[17:25:33.043] > Waiting for server log...
[17:25:33.082] > Waiting for server log...
[17:25:33.118] > Waiting for server log...
[17:25:33.156] > Waiting for server log...
[17:25:33.194] > Waiting for server log...
[17:25:33.231] > Waiting for server log...
[17:25:33.268] > Waiting for server log...
[17:25:33.307] > Waiting for server log...
[17:25:33.344] > Waiting for server log...
[17:25:33.381] > Waiting for server log...
[17:25:33.416] > Waiting for server log...
[17:25:33.454] > Waiting for server log...
[17:25:33.493] > Waiting for server log...
[17:25:33.530] > Waiting for server log...
[17:25:33.567] > Waiting for server log...
[17:25:33.603] > Waiting for server log...
[17:25:33.643] > Waiting for server log...
[17:25:33.680] > Waiting for server log...
[17:25:33.717] > Waiting for server log...
[17:25:33.754] > Waiting for server log...
[17:25:33.794] > Waiting for server log...
[17:25:33.831] > Waiting for server log...
[17:25:33.869] > Waiting for server log...
[17:25:33.907] > Waiting for server log...
[17:25:33.945] > Waiting for server log...
[17:25:33.982] > Waiting for server log...
[17:25:34.019] > Waiting for server log...
[17:25:34.057] > Waiting for server log...
[17:25:34.097] > Waiting for server log...
[17:25:34.134] > Waiting for server log...
[17:25:34.171] > Waiting for server log...
[17:25:34.210] > Waiting for server log...
[17:25:34.248] > Waiting for server log...
[17:25:34.286] > Waiting for server log...
[17:25:34.323] > Waiting for server log...
[17:25:34.361] > Waiting for server log...
[17:25:34.398] > Waiting for server log...
[17:25:34.434] > Waiting for server log...
[17:25:34.472] > Waiting for server log...
[17:25:34.511] > Waiting for server log...
[17:25:34.547] > Waiting for server log...
[17:25:34.584] > Waiting for server log...
[17:25:34.622] > Waiting for server log...
[17:25:34.662] > Waiting for server log...
[17:25:34.699] > Waiting for server log...
[17:25:34.736] > Waiting for server log...
[17:25:34.774] > Waiting for server log...
[17:25:34.812] > Waiting for server log...
[17:25:34.850] > Waiting for server log...
[17:25:34.886] > Waiting for server log...
[17:25:34.923] > Waiting for server log...
[17:25:34.963] > Waiting for server log...
[17:25:35.000] > Waiting for server log...
[17:25:35.035] > Waiting for server log...
[17:25:35.071] > Waiting for server log...
[17:25:35.110] > Waiting for server log...
[17:25:35.148] > Waiting for server log...
[17:25:35.186] > Waiting for server log...
[17:25:35.223] > Waiting for server log...
[17:25:35.262] > Waiting for server log...
[17:25:35.301] > Waiting for server log...
[17:25:35.339] > Waiting for server log...
[17:25:35.378] > Waiting for server log...
[17:25:35.417] > Waiting for server log...
[17:25:35.453] > Waiting for server log...
[17:25:35.491] > Waiting for server log...
[17:25:35.530] > Waiting for server log...
[17:25:35.568] > Waiting for server log...
[17:25:35.605] > Waiting for server log...
[17:25:35.652] > Waiting for server log...
[17:25:35.690] > Waiting for server log...
[17:25:35.727] > Waiting for server log...
[17:25:35.765] > Waiting for server log...
[17:25:35.800] > Waiting for server log...
[17:25:35.837] > Waiting for server log...
[17:25:35.875] > Waiting for server log...
[17:25:35.913] > Waiting for server log...
[17:25:35.951] > Waiting for server log...
[17:25:35.987] > Waiting for server log...
[17:25:36.025] > Waiting for server log...
[17:25:36.062] > Waiting for server log...
[17:25:36.100] > Waiting for server log...
[17:25:36.139] > Waiting for server log...
[17:25:36.178] > Waiting for server log...
[17:25:36.215] > Waiting for server log...
[17:25:36.254] > Waiting for server log...
[17:25:36.292] > Waiting for server log...
[17:25:36.329] > Waiting for server log...
[17:25:36.367] > Waiting for server log...
[17:25:36.406] > Waiting for server log...
[17:25:36.443] > Waiting for server log...
[17:25:36.481] > Waiting for server log...
[17:25:36.518] > Waiting for server log...
[17:25:36.556] > Waiting for server log...
[17:25:36.596] > Waiting for server log...
[17:25:36.634] > Waiting for server log...
[17:25:36.673] > Waiting for server log...
[17:25:36.710] > Waiting for server log...
[17:25:36.748] > Waiting for server log...
[17:25:36.785] > Waiting for server log...
[17:25:36.824] > Waiting for server log...
[17:25:36.860] > Waiting for server log...
[17:25:36.897] > Waiting for server log...
[17:25:36.933] > Waiting for server log...
[17:25:36.972] > Waiting for server log...
[17:25:37.011] > Waiting for server log...
[17:25:37.047] > Waiting for server log...
[17:25:37.086] > Waiting for server log...
[17:25:37.124] > Waiting for server log...
[17:25:37.160] > Waiting for server log...
[17:25:37.199] > Waiting for server log...
[17:25:37.236] > Waiting for server log...
[17:25:37.277] > Waiting for server log...
[17:25:37.314] > Waiting for server log...
[17:25:37.351] > Waiting for server log...
[17:25:37.389] > Waiting for server log...
[17:25:37.425] > Waiting for server log...
[17:25:37.462] > Waiting for server log...
[17:25:37.500] > Waiting for server log...
[17:25:37.540] > Waiting for server log...
[17:25:37.578] > Waiting for server log...
[17:25:37.614] > Waiting for server log...
[17:25:37.651] > Waiting for server log...
[17:25:37.689] > Waiting for server log...
[17:25:37.728] > Waiting for server log...
[17:25:37.763] > Waiting for server log...
[17:25:37.800] > Waiting for server log...
[17:25:37.838] > Waiting for server log...
[17:25:37.874] > Waiting for server log...
[17:25:37.909] > Waiting for server log...
[17:25:37.944] > Waiting for server log...
[17:25:37.980] > Waiting for server log...
[17:25:38.014] > Waiting for server log...
[17:25:38.048] > Waiting for server log...
[17:25:38.082] > Waiting for server log...
[17:25:38.116] > Waiting for server log...
[17:25:38.151] > Waiting for server log...
[17:25:38.187] > Waiting for server log...
[17:25:38.220] > Waiting for server log...
[17:25:38.258] > Waiting for server log...
[17:25:38.291] > Waiting for server log...
[17:25:38.329] > Waiting for server log...
[17:25:38.366] > Waiting for server log...
[17:25:38.401] > Waiting for server log...
[17:25:38.437] > Waiting for server log...
[17:25:38.474] > Waiting for server log...
[17:25:38.514] > Waiting for server log...
[17:25:38.551] > Waiting for server log...
[17:25:38.589] > Waiting for server log...
[17:25:38.629] > Waiting for server log...
[17:25:38.669] > Waiting for server log...
[17:25:38.704] > Waiting for server log...
[17:25:38.743] > Waiting for server log...
[17:25:38.780] > Waiting for server log...
[17:25:38.817] > Waiting for server log...
[17:25:38.854] > Waiting for server log...
[17:25:38.889] > Waiting for server log...
[17:25:38.930] > Waiting for server log...
[17:25:38.967] > Waiting for server log...
[17:25:39.003] > Waiting for server log...
[17:25:39.039] >  
> *
[17:25:39.041] > * Reminder: You may only use this software with Visual Studio family products,
[17:25:39.042] > * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[17:25:39.049] > Server did not start successfully. Full server log at /home/godev/.vscode-server/.f80445acd5a3dadef24aa209168452a3d97cc326.log >>>
[17:25:39.050] > Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /home/godev/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/node)
> Error relocating /home/godev/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/node: gnu_get_libc_version: symbol not found
> Error relocating /home/godev/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/node: __register_atfork: symbol not found
> Error relocating /home/godev/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/node: __strdup: symbol not found
> Error relocating /home/godev/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/node: setcontext: symbol not found
> Error relocating /home/godev/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/node: makecontext: symbol not found
> Error relocating /home/godev/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/node: backtrace: symbol not found
> Error relocating /home/godev/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/node: getcontext: symbol not found
> Error relocating /home/godev/.vscode-server/bin/f80445acd5a3dadef24aa209168452a3d97cc326/node: __libc_stack_end: symbol not found
[17:25:39.051] > <<< End of server log
> da7e05f15385: start
> exitCode==32==
> listeningOn====
> osReleaseId==alpine==
> arch==x86_64==
> tmpDir==/tmp==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==0==
> da7e05f15385: end
[17:25:39.051] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==alpine==
arch==x86_64==
tmpDir==/tmp==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==0==

[17:25:39.052] Terminating local server
[17:25:39.055] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (/home/aok-1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022021815/out/extension.js:1:586061)
	at p (/home/aok-1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022021815/out/extension.js:1:579910)
	at Object.t.handleInstallOutput (/home/aok-1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022021815/out/extension.js:1:583195)
	at Object.e [as tryInstallWithLocalServer] (/home/aok-1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022021815/out/extension.js:1:625119)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/aok-1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022021815/out/extension.js:1:643937
	at async Object.t.withShowDetailsEvent (/home/aok-1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022021815/out/extension.js:1:647684)
	at async /home/aok-1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022021815/out/extension.js:1:623591
	at async b (/home/aok-1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022021815/out/extension.js:1:620097)
	at async Object.t.resolveWithLocalServer (/home/aok-1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022021815/out/extension.js:1:623206)
	at async Object.t.resolve (/home/aok-1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022021815/out/extension.js:1:645294)
	at async /home/aok-1/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022021815/out/extension.js:1:722515
[17:25:39.069] ------

[17:25:39.071] Local server exit: 15

**Comment by tanhakabir** [comment]
Would you be able to try this vsix and tell me if it works for you? You can download here: https://1drv.ms/u/s!Art4fdsu4NidiWbnEvN5FN5twrrC?e=5yCqMx

And install with the ellipses in the Extensions tab from the activity bar
