### ISSUE TITLE
Server setup spawning too many processes

### ISSUE THREAD

**Issue by GibsDev** [microsoft/vscode-remote-release#6403]
- VSCode Version: 1.64.2
- Local OS Version: Ubuntu 20.04.4
- Remote OS Version: Fedora 31
- Remote Extension/Connection Type: SSH
- Logs:
```
[08:36:09.118] stderr> /etc/profile.d/colorgrep.sh: fork: retry: Resource temporarily unavailable
[08:36:10.118] stderr> /etc/profile.d/colorgrep.sh: fork: retry: Resource temporarily unavailable
[08:36:12.119] stderr> /etc/profile.d/colorgrep.sh: fork: retry: Resource temporarily unavailable
[08:36:16.119] stderr> /etc/profile.d/colorgrep.sh: fork: retry: Resource temporarily unavailable
[08:36:24.119] stderr> /etc/profile.d/colorgrep.sh: fork: Resource temporarily unavailable
[08:36:24.120] stderr> Transferred: sent 3096, received 2488 bytes, in 15.2 seconds
[08:36:24.120] stderr> Bytes per second: sent 204.3, received 164.2
[08:36:24.121] > local-server-1> ssh child died, shutting down
[08:36:24.123] Local server exit: 0
[08:36:24.124] Received install output: local-server-1> Spawned ssh, pid=31281
OpenSSH_8.2p1 Ubuntu-4ubuntu0.4, OpenSSL 1.1.1f  31 Mar 2020
debug1: Server host key: ssh-ed25519 SHA256:***/***
Authenticated to *** ([*******]:*****).
/etc/profile.d/colorgrep.sh: fork: retry: Resource temporarily unavailable
/etc/profile.d/colorgrep.sh: fork: retry: Resource temporarily unavailable
/etc/profile.d/colorgrep.sh: fork: retry: Resource temporarily unavailable
/etc/profile.d/colorgrep.sh: fork: retry: Resource temporarily unavailable
/etc/profile.d/colorgrep.sh: fork: Resource temporarily unavailable
Transferred: sent 3096, received 2488 bytes, in 15.2 seconds
Bytes per second: sent 204.3, received 164.2
local-server-1> ssh child died, shutting down

[08:36:24.125] Failed to parse remote port from server output
[08:36:24.125] Resolver error: Error: 
	at Function.Create (/home/***/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022022515/out/extension.js:1:586041)
	at Object.t.handleInstallOutput (/home/***/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022022515/out/extension.js:1:584693)
	at Object.e [as tryInstallWithLocalServer] (/home/***/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022022515/out/extension.js:1:625033)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/***/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022022515/out/extension.js:1:644084
	at async Object.t.withShowDetailsEvent (/home/***/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022022515/out/extension.js:1:647831)
	at async /home/***/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022022515/out/extension.js:1:623505
	at async b (/home/***/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022022515/out/extension.js:1:620011)
	at async Object.t.resolveWithLocalServer (/home/***/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022022515/out/extension.js:1:623120)
	at async Object.t.resolve (/home/***/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022022515/out/extension.js:1:645441)
	at async /home/***/.vscode/extensions/ms-vscode-remote.remote-ssh-0.75.2022022515/out/extension.js:1:722881
[08:36:24.130] ------
```

Steps to Reproduce:

The server seems to have a fairly low process limit and is blocking forks at the OS level:

```
$ ulimit -u
80
```

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by tanhakabir** [comment]
Could you please also post the first half of your logs too?

**Comment by GibsDev** [comment]
I'm afraid I don't have them anymore. This happened on a production server and it caused some issues for me. I don't think I'm willing to reproduce it atm. I think the best way to replicate this would be to have an ssh environment where the ulimit -u is set to a low value. In this case it failed with 80, but there could have been other processes taking up some of that limit. Maybe something as small as 20? Is there a reason the server would need to spawn so many processes in order to function?

**Comment by GibsDev** [comment]
I was trying to run this on a website hosting server which I did not have administrative access to. I had to contact support to terminate the processes. I did not wait more than 8 hours to do this, so I cannot be sure.

**Comment by maciejmatczak** [comment]
Hey, I am having the same problems as @GibsDev.

@tanhakabir, I use same server daily. On a next day (definitely over 8 hours), I try to open same folders and I am informed about:
![image](https://user-images.githubusercontent.com/1786383/171578884-8117992f-5d12-4bd0-8a77-4affd458ba3f.png)

Initially I was surprised - the repos were small. Later on I realized, that this message is shown when the limit is depleted in the OS level.

Usually it's one process with almost 8k (I have std 8k limit), today it was to processes with almost 4k each.

**Comment by tanhakabir** [comment]
> This really looks like a leak, somehow. Or some plugin doing not what it's supposed to... It started to happen week or two ago, while I didn't change nothing in my workflow.

It could be this as well. There haven't really been any updates in the SSH extension in the last month. You could try seeing how well you're able to connect without running any extensions.

> end itself after 8h

Yep this is the expected time

**Comment by maciejmatczak** [comment]
I reconnected at morning - no VS Code server processes, good!

I opened a new session - 331 files in repository, but I run clean build process, let say. Files removed, files recreated.

With help of https://github.com/fatso83/dotfiles/blob/master/utils/scripts/inotify-consumers :

```text
8042         1     20226 mmatczak    /xx/yy/zz/.vscode-server/bin/c3511e6c6
```

In on of the logs, I found:

`remoteagent.log`:

```text
8:[2022-06-03 08:48:10.172] [remoteagent] [error] [File Watcher (parcel)] Inotify limit reached (ENOSPC) (path: /aa/bb/Python-3.8.0/lib/python3.8)
```

Python extension, then?

**Comment by maciejmatczak** [comment]
FYI, Python workaround being worked on, it seems: https://github.com/microsoft/vscode-python/issues/19233
... with a root cause being on VS Code's: https://github.com/microsoft/vscode/issues/151009

**Comment by tanhakabir** [comment]
@maciejmatczak thanks for investigating this for me! Yeah it looks like the issues with the Python extension and file watching are being tracked and are newer issues so hopefully they will be resolved soon. Let me know if you see issues any other issues with the SSH extension in the meantime!
