### ISSUE TITLE
VScode remote ssh might corrupt with a proxy tool gost

### ISSUE THREAD

**Issue by LetterLiGo** [microsoft/vscode-remote-release#6422]
- VSCode Version: 1.5.9
- Local OS Version: Win10
- Remote OS Version: Ubuntu18.04
- Remote Extension/Connection Type: SSH
- Logs:
[10:06:55.522] Log Level: 2
[10:06:55.524] remote-ssh@0.66.0
[10:06:55.524] win32 x64
[10:06:55.551] SSH Resolver called for "ssh-remote+a_2", attempt 1
[10:06:55.552] "remote.SSH.useLocalServer": false
[10:06:55.552] "remote.SSH.showLoginTerminal": false
[10:06:55.552] "remote.SSH.remotePlatform": {"a_2":"linux"}
[10:06:55.552] "remote.SSH.path": undefined
[10:06:55.552] "remote.SSH.configFile": undefined
[10:06:55.552] "remote.SSH.useFlock": true
[10:06:55.553] "remote.SSH.lockfilesInTmp": false
[10:06:55.553] "remote.SSH.localServerDownload": auto
[10:06:55.553] "remote.SSH.remoteServerListenOnSocket": false
[10:06:55.553] "remote.SSH.showLoginTerminal": false
[10:06:55.553] "remote.SSH.defaultExtensions": []
[10:06:55.553] "remote.SSH.loglevel": 2
[10:06:55.553] SSH Resolver called for host: a_2
[10:06:55.553] Setting up SSH remote "a_2"
[10:06:55.588] Using commit id "3866c3553be8b268c8a7f8c0482c0c0177aa8bfa" and quality "stable" for server
[10:06:55.592] Install and start server if needed
[10:06:55.594] Checking ssh with "ssh -V"
[10:06:55.656] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[10:06:55.660] Running script with connection command: ssh -T -D 8416 "a_2" bash
[10:06:55.662] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:06:55.892] > ]0;C:\WINDOWS\System32\cmd.exe
[10:06:55.892] Got some output, clearing connection timeout
[10:06:56.505] > 9e5801beacdf: running
[10:06:56.583] > Acquiring lock on /home/admin/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0
> 177aa8bfa/vscode-remote-lock.admin.3866c3553be8b268c8a7f8c0482c0c0177aa8bfa     
> Found existing installation at /home/admin/.vscode-server/bin/3866c3553be8b268c8
> a7f8c0482c0c0177aa8bfa...
> Checking /home/admin/.vscode-server/.3866c3553be8b268c8a7f8c0482c0c0177aa8bfa.lo
> g and /home/admin/.vscode-server/.3866c3553be8b268c8a7f8c0482c0c0177aa8bfa.pid f
> or a running server
> Looking for server with pid: 33733
[10:06:56.640] > Found running server...
[10:06:56.657] > 
> *
> * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status on port 33517 with wget
[10:07:56.968] > client_loop: send disconnect: Connection reset
[10:07:58.270] "install" terminal command done
[10:07:58.270] Install terminal quit with output: client_loop: send disconnect: Connection reset
[10:07:58.270] Received install output: client_loop: send disconnect: Connection reset
[10:07:58.271] Failed to parse remote port from server output
[10:07:58.271] Resolver error: Error: 
	at Function.Create (c:\Users\zxc\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:429193)
	at Object.t.handleInstallOutput (c:\Users\zxc\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:427836)
	at Object.t.tryInstall (c:\Users\zxc\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:521609)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\zxc\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:485262
	at async Object.t.withShowDetailsEvent (c:\Users\zxc\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:488612)
	at async Object.t.resolve (c:\Users\zxc\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:486341)
	at async c:\Users\zxc\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:559963
[10:07:58.275] ------

Steps to Reproduce:

1. I'm using [gost, a proxy tool](https://github.com/ginuerzh/gost) on server A to connect with the other server B. But it makes the connection attempts to server A fail.
```Shell
gost -L socks5://:1080?dns=1.1.1.1:53/tcp -L redirect://:12345 -F=socks5://<username>:<password>@<ServerB IP>:1080
```
2. If I turned the upper gost process down, the connection to server A would succeed.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by LetterLiGo** [comment]
I'm trying to connect server A with my PC.
- gost client process is runing on server A, which makes the VScode remote ssh connection from my PC to server A fail.
- gost server process is running on server B.
- If I turned the gost process on server A down, my attempts to connect PC to server A would succeed.

I'm wondering if it's related to some occupied socket channels? And how could I solve this issue? 

Thanks a lot for your precious time!

**Comment by bamurtaugh** [comment]
From [docs](https://code.visualstudio.com/docs/remote/ssh#_remote-ssh-limitations), does `HTTP_PROXY` or `HTTPS_PROXY` help?
