### ISSUE TITLE
Remote SSH Extension Resolver Error

### ISSUE THREAD

**Issue by Probmkr** [microsoft/vscode-remote-release#6431]
Here is an error when I tried to connect to my remove using Remote SSH Extension.

- VSCode Version:1.65.1
- Local OS Version:Ubuntu Server 20.04 LTS
- Remote OS Version:Ubuntu Server 20.04 LTS
- Remote Extension/Connection Type: SSH
- Logs:
```
[18:00:26.634] Log Level: 2
[18:00:26.635] remote-ssh@0.77.2022030315
[18:00:26.635] linux x64
[18:00:26.638] SSH Resolver called for "ssh-remote+probmkr.com", attempt 1
[18:00:26.638] "remote.SSH.useLocalServer": false
[18:00:26.641] "remote.SSH.showLoginTerminal": false
[18:00:26.641] "remote.SSH.remotePlatform": {}
[18:00:26.641] "remote.SSH.path": undefined
[18:00:26.641] "remote.SSH.configFile": ~/.ssh/config
[18:00:26.642] "remote.SSH.useFlock": true
[18:00:26.642] "remote.SSH.lockfilesInTmp": false
[18:00:26.642] "remote.SSH.localServerDownload": auto
[18:00:26.642] "remote.SSH.remoteServerListenOnSocket": false
[18:00:26.642] "remote.SSH.showLoginTerminal": false
[18:00:26.642] "remote.SSH.defaultExtensions": []
[18:00:26.642] "remote.SSH.loglevel": 2
[18:00:26.643] "remote.SSH.enableDynamicForwarding": true
[18:00:26.643] "remote.SSH.enableRemoteCommand": false
[18:00:26.643] "remote.SSH.serverPickPortsFromRange": {}
[18:00:26.643] "remote.SSH.serverInstallPath": {}
[18:00:26.662] SSH Resolver called for host: probmkr.com
[18:00:26.663] Setting up SSH remote "probmkr.com"
[18:00:26.670] Using commit id "8908a9ca0f221f36507231afb39d2d8d1e182702" and quality "stable" for server
[18:00:26.677] Install and start server if needed
[18:01:17.658] PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/thanatos/.local/bin:/home/thanatos/.dotnet/:/home/thanatos/.local/bin
[18:01:17.658] Checking ssh with "ssh -V"
[18:01:17.664] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.4, OpenSSL 1.1.1f  31 Mar 2020

[18:01:17.665] Using SSH config file "/home/thanatos/.ssh/config"
[18:01:17.666] Running script with connection command: ssh -T -D 36083 -o ConnectTimeout=15 -F '/home/thanatos/.ssh/config' 'probmkr.com' bash
[18:01:18.409] > 220621a712b3: running
[18:01:18.409] Got some output, clearing connection timeout
[18:01:18.440] > Acquiring lock on /home/thanatos/.vscode-server/bin/8908a9ca0f221f36507231afb39d2d8d1e182702/vscode-remote-lock.thanatos.8908a9ca0f221f36507231afb39d2d8d1e182702
> Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> 220621a712b3: start
> exitCode==24==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 220621a712b3: end
[18:01:18.440] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[18:01:18.441] Server installation process already in progress - waiting and retrying
[18:01:18.692] "install" terminal command done
[18:01:18.693] Install terminal quit with output: 

...

[18:02:08.928] Using SSH config file "/home/thanatos/.ssh/config"
[18:02:08.929] Running script with connection command: ssh -T -D 36083 -o ConnectTimeout=15 -F '/home/thanatos/.ssh/config' 'probmkr.com' bash
[18:02:09.662] > 220621a712b3: running
[18:02:09.662] Got some output, clearing connection timeout
[18:02:09.695] > Acquiring lock on /home/thanatos/.vscode-server/bin/8908a9ca0f221f36507231afb39d2d8d1e182702/vscode-remote-lock.thanatos.8908a9ca0f221f36507231afb39d2d8d1e182702
> Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> 220621a712b3: start
> exitCode==24==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 220621a712b3: end
[18:02:09.696] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[18:02:09.696] Server installation process already in progress - waiting and retrying
[18:02:09.945] "install" terminal command done
[18:02:09.945] Install terminal quit with output: 
[18:02:10.697] Resolver error: Error: 
	at Function.Create (/home/thanatos/.vscode/extensions/ms-vscode-remote.remote-ssh-0.77.2022030315/out/extension.js:1:586041)
	at /home/thanatos/.vscode/extensions/ms-vscode-remote.remote-ssh-0.77.2022030315/out/extension.js:1:644940
	at async Object.t.withShowDetailsEvent (/home/thanatos/.vscode/extensions/ms-vscode-remote.remote-ssh-0.77.2022030315/out/extension.js:1:647831)
	at async Object.t.resolve (/home/thanatos/.vscode/extensions/ms-vscode-remote.remote-ssh-0.77.2022030315/out/extension.js:1:645565)
	at async /home/thanatos/.vscode/extensions/ms-vscode-remote.remote-ssh-0.77.2022030315/out/extension.js:1:722881
[18:02:10.708] ------
```

Steps to Reproduce:

1. <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> to open the command palet.
2. Select "Remote-SSH: Connect to Host..."
3. Select Host.
4. Then it throws an error

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by Probmkr** [comment]
Addition:
If I use VSCode 1.63.2, It will work without error.

**Comment by Probmkr** [comment]
> Try deleting the lockfile at `/home/thanatos/.vscode-server/bin/8908a9ca0f221f36507231afb39d2d8d1e182702/vscode-remote-lock.thanatos.8908a9ca0f221f36507231afb39d2d8d1e182702`. if it persists, you can toggle the setting mentioned in the log

Sorry for being late for reply.
After I saw this reply, I removed the file and retried to connect again. But it threw another error.
It says
```
[18:28:00.081] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (/home/thanatos/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:431037)
	at d (/home/thanatos/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:425272)
	at Object.t.handleInstallOutput (/home/thanatos/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:428349)
	at Object.t.tryInstall (/home/thanatos/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:524958)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/thanatos/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:487817
	at async Object.t.withShowDetailsEvent (/home/thanatos/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:491162)
	at async Object.t.resolve (/home/thanatos/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:488896)
	at async /home/thanatos/.vscode/extensions/ms-vscode-remote.remote-ssh-0.71.2021121615/out/extension.js:1:565038
[18:28:00.084] ------




[18:28:00.630] "install" terminal command done
[18:28:00.688] Install terminal quit with output: 
```

How should I fix this?
