### ISSUE TITLE
Syntax Error operand expected, division by zero error

### ISSUE THREAD

**Issue by adminy** [microsoft/vscode-remote-release#6441]
- VSCode Version: Version: 1.66.0-insider
    Commit: 45b4204501ac1f50b6231af3c996d35f86359ecd
    Date: 2022-03-08T05:15:42.723Z (4 days ago)
- Local OS Version: Darwin arm64 21.3.0 (monterey 12.2)
- Remote OS Version: piCore 14.0
- Remote Extension/Connection Type: SSH
- Logs: 
```log
[11:00:04.738] > ready: 6aab5c459d6c
[11:00:04.752] > Linux 5.15.21-piCore-v7l #1 SMP Wed Feb 9 10:24:05 UTC 2022
[11:00:04.752] Platform: linux
[11:00:04.756] > /usr/local/bin/bash
[11:00:04.756] Shell: bash
[11:00:04.756] Creating bash subshell inside "bash"
[11:00:04.768] > bash version:  5.0.11(1)-release
[11:00:04.843] > 6aab5c459d6c: running
[11:00:05.405] > Missing GLIBC >= 2.17!
> Found version ldd (GNU libc)
> 6aab5c459d6c$$1$$
> Acquiring lock on /home/tc/.vscode-server-insiders/bin/45b4204501ac1f50b6231af3c996d35f86359ecd/vscode-remote-lock.tc.45b4204501ac1f50b6231af3c996d35f86359ecd
> Installing to /home/tc/.vscode-server-insiders/bin/45b4204501ac1f50b6231af3c996d35f86359ecd...
[11:00:05.407] stderr> ls: /lib/libc-*.so: No such file or directory
[11:00:05.420] stderr> main: line 61: 1647082806%N/1000000: division by 0 (error token is "N/1000000")
[11:00:05.421] > 6aab5c459d6c%%1%%
[11:00:05.471] > Downloading with curl
[11:00:05.503] stderr>   % T
[11:00:05.504] stderr> o
[11:00:05.505] stderr> tal    % Received %
[11:00:05.506] stderr>  X
[11:00:05.508] stderr> ferd  Ave
[11:00:05.508] stderr> rage Speed   Time    Tim
[11:00:05.509] stderr> e
[11:00:05.510] stderr>  
[11:00:05.512] stderr>     Time 
[11:00:05.513] stderr>  Current
[11:00:05.513] stderr>                                  Dload  Upload   Total   Spent    Left  Speed
[11:00:05.513] stderr>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[11:00:05.916] stderr>  
[11:00:05.916] stderr>  0     0    0     0    0     0      0      0 -
[11:00:05.919] stderr> -:--:-- --:--:-- --:--:--     0
[11:00:06.531] stderr> 100   134
[11:00:06.534] stderr>   100   134    0     0    133      0  0:00:01  0:00:01 --:--:--   133
[11:00:06.940] stderr>   0 39.9M
[11:00:06.944] stderr>     0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
[11:00:07.861] stderr>  29 39.9M
[11:00:07.865] stderr>    29 11.7M    0     0  5141k      0  0:00:07  0:00:02  0:00:05 12.7M
[11:00:08.886] stderr>  69 39.9M
[11:00:08.892] stderr>    69 27.7M    0     0  8508k      0  0:00:04  0:00:03  0:00:01 1
[11:00:08.894] stderr> 4.4M
[11:00:09.706] stderr> 100 39.9M  100 39.9M    0     0  9995k   
[11:00:09.709] > Download complete
> 6aab5c459d6c%%2%%
> tar --version:
> tar (busybox) 1.33.2
[11:00:09.710] stderr>    0  0:00:04  0:00:04 --:--:-- 14.9M
[11:00:09.710] stderr> main: line 61: 1647082810%N/1000000: division by 0 (error token is "N/1000000")
[11:00:09.710] stderr> main: line 69: - : syntax error: operand expected (error token is "- ")
[11:00:09.711] stderr> main: line 61: 1647082810%N/1000000: division by 0 (error token is "N/1000000")
[11:00:13.699] stderr> main: line 61: 1647082814%N/1000000: division by 0 (error token is "N/1000000")
[11:00:13.699] stderr> main: line 69: - : syntax error: operand expected (error token is "- ")
[11:00:13.707] > Checking /home/tc/.vscode-server-insiders/.45b4204501ac1f50b6231af3c996d35f86359ecd.log and /home/tc/.vscode-server-insiders/.45b4204501ac1f50b6231af3c996d35f86359ecd.pid for a running server
[11:00:13.754] > Starting server with command... /home/tc/.vscode-server-insiders/bin/45b4204501ac1f50b6231af3c996d35f86359ecd/bin/code-server-insiders --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level off   &> "/home/tc/.vscode-server-insiders/.45b4204501ac1f50b6231af3c996d35f86359ecd.log" < /dev/null
> printenv:
[11:00:13.764] >     SHELL=/usr/local/bin/bash
>     SSH_AUTH_SOCK=/tmp/ssh-Esky2cetGL/agent.3074
>     PWD=/home/tc
>     LOGNAME=tc
>     HOME=/home/tc
>     VSCODE_AGENT_FOLDER=/home/tc/.vscode-server-insiders
>     SSH_CONNECTION=192.168.8.154 56537 192.168.8.187 22
>     USER=tc
>     SHLVL=1
>     SSH_CLIENT=192.168.8.154 56537 22
>     PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
>     MAIL=/var/mail/tc
>     OLDPWD=/home/tc/.vscode-server-insiders/bin/45b4204501ac1f50b6231af3c996d35f86359ecd
>     _=/bin/printenv
[11:00:13.777] stderr> main: line 61: 1647082814%N/1000000: division by 0 (error token is "N/1000000")
[11:00:13.785] stderr> rm: can't remove '/home/tc/.vscode-server-insiders/.45b4204501ac1f50b6231af3c996d35f86359ecd.token': No such file or directory
[11:00:13.797] > Spawned remote server: 3144
[11:00:13.820] > Waiting for server log...
...
[11:00:21.187] > Waiting for server log...
[11:00:21.252] stderr> main: line 61: 1647082822%N/1000000: division by 0 (error token is "N/1000000")
[11:00:21.257] >  
> *
[11:00:21.257] stderr> main: line 69: - : syntax error: operand expected (error token is "- ")
[11:00:21.258] > * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[11:00:21.292] > Server did not start successfully. Full server log at /home/tc/.vscode-server-insiders/.45b4204501ac1f50b6231af3c996d35f86359ecd.log >>>
[11:00:21.298] > /home/tc/.vscode-server-insiders/bin/45b4204501ac1f50b6231af3c996d35f86359ecd/node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
> <<< End of server log
> 6aab5c459d6c: start
[11:00:21.299] > exitCode==32==
> listeningOn====
> osReleaseId==piCore==
[11:00:21.300] > arch==armv7l==
> tmpDir==/tmp==
> platform==linux==
> unpackResult==success==
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 6aab5c459d6c: end
[11:00:21.301] Received install output: exitCode==32==
listeningOn====
osReleaseId==piCore==arch==armv7l==
tmpDir==/tmp==
platform==linux==
unpackResult==success==
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[11:00:21.302] Terminating local server
[11:00:21.306] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (/Users/adminy/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:585975)
	at p (/Users/adminy/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:579824)
	at Object.t.handleInstallOutput (/Users/adminy/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:583109)
	at Object.e [as tryInstallWithLocalServer] (/Users/adminy/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:625033)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/adminy/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:644070
	at async Object.t.withShowDetailsEvent (/Users/adminy/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:647817)
	at async /Users/adminy/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:623505
	at async b (/Users/adminy/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:620011)
	at async Object.t.resolveWithLocalServer (/Users/adminy/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:623120)
	at async Object.t.resolve (/Users/adminy/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:645427)
	at async /Users/adminy/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:722867
[11:00:21.307] Local server exit: 15
[11:00:21.309] ------
```
Steps to Reproduce:

1. install piCore on a pi
2.  tce-load -wi bash
3. change Default shell in /etc/passwd file.
4. open vscode ssh

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by roblourens** [comment]
Can you try switching to the pre-release version of the extension, and see whether it's any different?
