### ISSUE TITLE
Remote vscode-server fails to start - python/node commands not found 

### ISSUE THREAD

**Issue by doc** [microsoft/vscode-remote-release#6442]
Connecting to a remote vscode instance via ssh fails as the remote vscode server fails to start as per snippet from log below:

[11:11:47.241] Terminating local server
[11:11:47.241] Resolver error: Error: The VS Code Server failed to start 

VSCode Version:
Version: 1.66.0-insider
Commit: 6b7453421201c888b81eae5c04ec822a6423608f
Date: 2022-03-11T05:28:10.803Z
Electron: 17.1.1
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0

Local OS: Darwin arm64 21.3.0
Remote OS : Darwin arm64 21.3.0
Remote Extension/Connection Type: SSH
Logs:
```
[11:11:39.618] Log Level: 2
[11:11:39.620] remote-ssh@0.77.2022031115
[11:11:39.620] darwin arm64
[11:11:39.625] SSH Resolver called for "ssh-remote+100.85.10.128", attempt 1
[11:11:39.625] "remote.SSH.useLocalServer": true
[11:11:39.625] "remote.SSH.path": undefined
[11:11:39.625] "remote.SSH.configFile": undefined
[11:11:39.628] "remote.SSH.useFlock": true
[11:11:39.628] "remote.SSH.lockfilesInTmp": false
[11:11:39.628] "remote.SSH.localServerDownload": auto
[11:11:39.628] "remote.SSH.remoteServerListenOnSocket": false
[11:11:39.628] "remote.SSH.showLoginTerminal": true
[11:11:39.628] "remote.SSH.defaultExtensions": []
[11:11:39.629] "remote.SSH.loglevel": 2
[11:11:39.629] "remote.SSH.enableDynamicForwarding": true
[11:11:39.629] "remote.SSH.enableRemoteCommand": false
[11:11:39.629] "remote.SSH.serverPickPortsFromRange": {}
[11:11:39.629] "remote.SSH.serverInstallPath": {}
[11:11:39.638] SSH Resolver called for host: 100.85.10.128
[11:11:39.638] Setting up SSH remote "100.85.10.128"
[11:11:39.640] Acquiring local install lock: /var/folders/2b/f1t6ly0x2273t0h7gygxmrv00000gn/T/vscode-remote-ssh-84b9043b-install.lock
[11:11:39.641] Looking for existing server data file at /Users/mark/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-84b9043b-6b7453421201c888b81eae5c04ec822a6423608f-0.77.2022031115/data.json
[11:11:39.641] Using commit id "6b7453421201c888b81eae5c04ec822a6423608f" and quality "insider" for server
[11:11:39.644] Install and start server if needed
[11:11:39.646] PATH: /Users/mark/.yarn/bin:/Users/mark/.config/yarn/global/node_modules/.bin:/usr/local/Caskroom/miniconda/base/bin:/Users/mark/Downloads/google-cloud-sdk/bin:/Users/mark/.rbenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/mark/.cargo/bin:/usr/local/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/mark/.cargo/bin:/Users/mark/.rvm/bin:/usr/local/bin/
[11:11:39.646] Checking ssh with "ssh -V"
[11:11:39.651] > OpenSSH_8.6p1, LibreSSL 2.8.3

[11:11:39.652] askpass server listening on /var/folders/2b/f1t6ly0x2273t0h7gygxmrv00000gn/T/vscode-ssh-askpass-236d34e9e0b223adb86e430dc8794bcff2f6d313.sock
[11:11:39.652] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/2b/f1t6ly0x2273t0h7gygxmrv00000gn/T/vscode-ssh-askpass-197c7d5d66a3df9c40ce1c519c6588d488f7df90.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","57273","-o","ConnectTimeout=15","100.85.10.128"],"serverDataFolderName":".vscode-server-insiders","dataFilePath":"/Users/mark/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-84b9043b-6b7453421201c888b81eae5c04ec822a6423608f-0.77.2022031115/data.json"}
[11:11:39.652] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.rwjQ02iYTB/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/mark/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/mark/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/2b/f1t6ly0x2273t0h7gygxmrv00000gn/T/vscode-ssh-askpass-236d34e9e0b223adb86e430dc8794bcff2f6d313.sock"}
[11:11:39.653] Spawned 55564
[11:11:39.721] > local-server-1> Spawned ssh, pid=55575
[11:11:39.723] stderr> OpenSSH_8.6p1, LibreSSL 2.8.3
[11:11:39.810] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:C7Pufz0BM/5ccvFidHlTRpKsv8EzUnHy3CXSoOm8Fg4
[11:11:39.906] stderr> Authenticated to 100.85.10.128 ([100.85.10.128]:22).
[11:11:40.058] > ready: 4b8a57678b22
[11:11:40.064] > Darwin 21.4.0 Darwin Kernel Version 21.4.0: Tue Jan 18 13:02:08 PST 2022; root:xnu-8020.100.406.0.1~18/RELEASE_ARM64_T8101
[11:11:40.064] Platform: macOS
[11:11:40.068] > /bin/zsh
[11:11:40.068] Shell: zsh
[11:11:40.068] Creating bash subshell inside "zsh"
[11:11:40.073] > bash version:  3.2.57(1)-release
[11:11:40.085] > 4b8a57678b22: running
[11:11:40.095] > Acquiring lock on /Users/mark/.vscode-server-insiders/bin/6b7453421201c888b81eae5c04ec822a6423608f/vscode-remote-lock.mark.6b7453421201c888b81eae5c04ec822a6423608f
[11:11:40.097] > \ln /Users/mark/.vscode-server-insiders/bin/6b7453421201c888b81eae5c04ec822a6423608f/vscode-remote-lock.mark.6b7453421201c888b81eae5c04ec822a6423608f.target /Users/mark/.vscode-server-insiders/bin/6b7453421201c888b81eae5c04ec822a6423608f/vscode-remote-lock.mark.6b7453421201c888b81eae5c04ec822a6423608f
[11:11:40.102] > Found existing installation at /Users/mark/.vscode-server-insiders/bin/6b7453421201c888b81eae5c04ec822a6423608f...
> Checking /Users/mark/.vscode-server-insiders/.6b7453421201c888b81eae5c04ec822a6423608f.log and /Users/mark/.vscode-server-insiders/.6b7453421201c888b81eae5c04ec822a6423608f.pid for a running server
[11:11:40.103] > Looking for server with pid: 76009
[11:11:40.145] > Starting server with command... /Users/mark/.vscode-server-insiders/bin/6b7453421201c888b81eae5c04ec822a6423608f/bin/code-server-insiders --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all   &> "/Users/mark/.vscode-server-insiders/.6b7453421201c888b81eae5c04ec822a6423608f.log" < /dev/null
> printenv:
[11:11:40.147] >     MANPATH=/opt/homebrew/share/man::
>     rvm_bin_path=/Users/mark/.rvm/bin
>     GEM_HOME=/Users/mark/.rvm/gems/ruby-3.0.0
>     SHELL=/bin/zsh
>     IRBRC=/Users/mark/.rvm/rubies/ruby-3.0.0/.irbrc
>     HOMEBREW_REPOSITORY=/opt/homebrew
>     TMPDIR=/var/folders/w0/4t3jbtj96gg2pw2q1tx1d6kr0000gn/T/
>     SSH_CLIENT=100.87.40.64 57275 22
>     MY_RUBY_HOME=/Users/mark/.rvm/rubies/ruby-3.0.0
>     USER=mark
>     rvm_path=/Users/mark/.rvm
>     VSCODE_AGENT_FOLDER=/Users/mark/.vscode-server-insiders
>     rvm_prefix=/Users/mark
>     PATH=/Users/mark/.rvm/gems/ruby-3.0.0/bin:/Users/mark/.rvm/gems/ruby-3.0.0@global/bin:/Users/mark/.rvm/rubies/ruby-3.0.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/mark/.cargo/bin:/Users/mark/.rvm/bin
>     PWD=/Users/mark
>     rvm_version=1.29.12 (latest)
>     SHLVL=2
>     HOME=/Users/mark
>     HOMEBREW_PREFIX=/opt/homebrew
>     LOGNAME=mark
>     GEM_PATH=/Users/mark/.rvm/gems/ruby-3.0.0:/Users/mark/.rvm/gems/ruby-3.0.0@global
>     SSH_CONNECTION=100.87.40.64 57275 100.85.10.128 22
>     INFOPATH=/opt/homebrew/share/info:
>     HOMEBREW_CELLAR=/opt/homebrew/Cellar
>     RUBY_VERSION=ruby-3.0.0
>     _=/usr/bin/printenv
[11:11:40.152] > Removing old logfile at /Users/mark/.vscode-server-insiders/.6b7453421201c888b81eae5c04ec822a6423608f.log
[11:11:40.153] > Spawned remote server: 80179
[11:11:40.157] > Waiting for server log...
[11:11:40.200] > Waiting for server log...
[11:11:40.243] > Waiting for server log...
[11:11:40.290] > Waiting for server log...
[11:11:40.337] > Waiting for server log...
[11:11:40.378] > Waiting for server log...
[11:11:40.426] > Waiting for server log...
[11:11:40.474] > Waiting for server log...
[11:11:40.528] > Waiting for server log...
[11:11:40.568] > Waiting for server log...
[11:11:40.620] > Waiting for server log...
[11:11:40.673] > Waiting for server log...
[11:11:40.718] > Waiting for server log...
[11:11:40.773] > Waiting for server log...
[11:11:40.823] > Waiting for server log...
[11:11:40.873] > Waiting for server log...
[11:11:40.921] > Waiting for server log...
[11:11:40.972] > Waiting for server log...
[11:11:41.027] > Waiting for server log...
[11:11:41.076] > Waiting for server log...
[11:11:41.120] > Waiting for server log...
[11:11:41.174] > Waiting for server log...
[11:11:41.230] > Waiting for server log...
[11:11:41.282] > Waiting for server log...
[11:11:41.337] > Waiting for server log...
[11:11:41.392] > Waiting for server log...
[11:11:41.450] > Waiting for server log...
[11:11:41.503] > Waiting for server log...
[11:11:41.556] > Waiting for server log...
[11:11:41.606] > Waiting for server log...
[11:11:41.660] > Waiting for server log...
[11:11:41.714] > Waiting for server log...
[11:11:41.774] > Waiting for server log...
[11:11:41.812] > Waiting for server log...
[11:11:41.868] > Waiting for server log...
[11:11:41.914] > Waiting for server log...
[11:11:41.966] > Waiting for server log...
[11:11:42.021] > Waiting for server log...
[11:11:42.073] > Waiting for server log...
[11:11:42.119] > Waiting for server log...
[11:11:42.178] > Waiting for server log...
[11:11:42.226] > Waiting for server log...
[11:11:42.270] > Waiting for server log...
[11:11:42.317] > Waiting for server log...
[11:11:42.368] > Waiting for server log...
[11:11:42.417] > Waiting for server log...
[11:11:42.465] > Waiting for server log...
[11:11:42.520] > Waiting for server log...
[11:11:42.573] > Waiting for server log...
[11:11:42.623] > Waiting for server log...
[11:11:42.671] > Waiting for server log...
[11:11:42.722] > Waiting for server log...
[11:11:42.772] > Waiting for server log...
[11:11:42.826] > Waiting for server log...
[11:11:42.873] > Waiting for server log...
[11:11:42.923] > Waiting for server log...
[11:11:42.972] > Waiting for server log...
[11:11:43.022] > Waiting for server log...
[11:11:43.072] > Waiting for server log...
[11:11:43.114] > Waiting for server log...
[11:11:43.166] > Waiting for server log...
[11:11:43.207] > Waiting for server log...
[11:11:43.263] > Waiting for server log...
[11:11:43.318] > Waiting for server log...
[11:11:43.366] > Waiting for server log...
[11:11:43.408] > Waiting for server log...
[11:11:43.454] > Waiting for server log...
[11:11:43.500] > Waiting for server log...
[11:11:43.555] > Waiting for server log...
[11:11:43.599] > Waiting for server log...
[11:11:43.652] > Waiting for server log...
[11:11:43.707] > Waiting for server log...
[11:11:43.762] > Waiting for server log...
[11:11:43.813] > Waiting for server log...
[11:11:43.868] > Waiting for server log...
[11:11:43.921] > Waiting for server log...
[11:11:43.975] > Waiting for server log...
[11:11:44.025] > Waiting for server log...
[11:11:44.074] > Waiting for server log...
[11:11:44.120] > Waiting for server log...
[11:11:44.169] > Waiting for server log...
[11:11:44.207] > Waiting for server log...
[11:11:44.255] > Waiting for server log...
[11:11:44.303] > Waiting for server log...
[11:11:44.350] > Waiting for server log...
[11:11:44.397] > Waiting for server log...
[11:11:44.449] > Waiting for server log...
[11:11:44.499] > Waiting for server log...
[11:11:44.553] > Waiting for server log...
[11:11:44.606] > Waiting for server log...
[11:11:44.656] > Waiting for server log...
[11:11:44.711] > Waiting for server log...
[11:11:44.762] > Waiting for server log...
[11:11:44.814] > Waiting for server log...
[11:11:44.868] > Waiting for server log...
[11:11:44.919] > Waiting for server log...
[11:11:44.971] > Waiting for server log...
[11:11:45.024] > Waiting for server log...
[11:11:45.073] > Waiting for server log...
[11:11:45.122] > Waiting for server log...
[11:11:45.175] > Waiting for server log...
[11:11:45.222] > Waiting for server log...
[11:11:45.296] > Waiting for server log...
[11:11:45.341] > Waiting for server log...
[11:11:45.399] > Waiting for server log...
[11:11:45.439] > Waiting for server log...
[11:11:45.492] > Waiting for server log...
[11:11:45.543] > Waiting for server log...
[11:11:45.594] > Waiting for server log...
[11:11:45.647] > Waiting for server log...
[11:11:45.700] > Waiting for server log...
[11:11:45.752] > Waiting for server log...
[11:11:45.803] > Waiting for server log...
[11:11:45.850] > Waiting for server log...
[11:11:45.903] > Waiting for server log...
[11:11:45.955] > Waiting for server log...
[11:11:46.008] > Waiting for server log...
[11:11:46.062] > Waiting for server log...
[11:11:46.119] > Waiting for server log...
[11:11:46.174] > Waiting for server log...
[11:11:46.225] > Waiting for server log...
[11:11:46.277] > Waiting for server log...
[11:11:46.329] > Waiting for server log...
[11:11:46.386] > Waiting for server log...
[11:11:46.439] > Waiting for server log...
[11:11:46.489] > Waiting for server log...
[11:11:46.540] > Waiting for server log...
[11:11:46.597] > Waiting for server log...
[11:11:46.642] > Waiting for server log...
[11:11:46.692] > Waiting for server log...
[11:11:46.747] > Waiting for server log...
[11:11:46.800] > Waiting for server log...
[11:11:46.853] > Waiting for server log...
[11:11:46.905] > Waiting for server log...
[11:11:46.957] > Waiting for server log...
[11:11:47.007] > Waiting for server log...
[11:11:47.061] > Waiting for server log...
[11:11:47.115] > Waiting for server log...
[11:11:47.173] > Waiting for server log...
[11:11:47.230] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[11:11:47.237] > Server did not start successfully. Full server log at /Users/mark/.vscode-server-insiders/.6b7453421201c888b81eae5c04ec822a6423608f.log >>>
[11:11:47.240] > /Users/mark/.vscode-server-insiders/bin/6b7453421201c888b81eae5c04ec822a6423608f/bin/code-server-insiders: line 10: python: command not found
> usage: dirname string [...]
> usage: dirname string [...]
> /Users/mark/.vscode-server-insiders/bin/6b7453421201c888b81eae5c04ec822a6423608f/bin/code-server-insiders: line 13: /node: No such file or directory
> <<< End of server log
[11:11:47.240] > 4b8a57678b22: start
> exitCode==32==
> listeningOn====
> osReleaseId==Darwin==
> arch==arm64==
> tmpDir==/tmp==
> platform==macOS==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==8000==
> 4b8a57678b22: end
[11:11:47.241] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==Darwin==
arch==arm64==
tmpDir==/tmp==
platform==macOS==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==8000==

[11:11:47.241] Terminating local server
[11:11:47.241] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (/Users/mark/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:585975)
	at p (/Users/mark/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:579824)
	at Object.t.handleInstallOutput (/Users/mark/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:583109)
	at Object.e [as tryInstallWithLocalServer] (/Users/mark/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:625033)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/mark/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:644070
	at async Object.t.withShowDetailsEvent (/Users/mark/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:647817)
	at async /Users/mark/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:623505
	at async b (/Users/mark/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:620011)
	at async Object.t.resolveWithLocalServer (/Users/mark/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:623120)
	at async Object.t.resolve (/Users/mark/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:645427)
	at async /Users/mark/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.77.2022031115/out/extension.js:1:722867
[11:11:47.244] ------




[11:11:47.244] Local server exit: 15
```

Steps to Reproduce:

1. Click connect this window to remote host
2. Select host from previously configured list3. 
3. Connection fails after a few seconds of waiting for the remote host to start.

Does this issue occur when you try this locally?: No, 
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by noahcolvin** [comment]
Same. I don't know if it's just a coincidence but it started right after I updated the remote to macOS 12.3. SSH still works from Windows, just not the server.

I tried running `Kill VS Code Server on Host` (that succeeded) and deleting the `.vscode-server` with no luck.

**Comment by rightparen** [comment]
Apparently macOS 12.3 removed the `python` command now that Python 2.7 is deprecated.  The `code-server` shell script depends on being able to find "python" in the path for what looks like a portable mechanism for resolving symlinks.

There is probably a better workaround, but a somewhat awkward one that worked for me is:
* On the remote machine, make sure you have Python 3 installed (e.g. via MacPorts or HomeBrew.  Xcode command-line utilities might also install this).
* When loading fails, choose "More Actions.."
* Look for a line in the Output log that contains "code-server: line 10: python: command not found".
* On the remote machine, edit the `code-server` file indicated on that line.
* Change the "python" reference to the full path of a Python 3 binary on your remote.
* Reload the remote.

This might not repro for people who installed Python 2.7 via HomeBrew because HomeBrew modifies standard system paths, but I don't have a HomeBrew machine to confirm.  I suspect it will be an issue for most of us MacPorts users.

**Comment by packeteer** [comment]
also experiencing the same issue, and the work around posted above has worked

**Comment by trodemaster** [comment]
Looks like there is a way to pass custom server environment variables like $PATH for wsl. Having this file be parsed on macOS would allow adding an existing python install to $PATH. I set up one of these files but it made no difference. 

https://code.visualstudio.com/docs/remote/wsl#_advanced-environment-setup-script

**Comment by espresso3389** [comment]
python executable seems only used to implement `realpath` function. I think there are better alternatives to the current implementation that do not require python executable anyway.
