### ISSUE TITLE
VSCode Remote-SSH times out when behind a VPN

### ISSUE THREAD

**Issue by jasonhp** [microsoft/vscode-remote-release#6444]
I can ssh to remote machine, and VSCode can connect to it too. Remote VSCode server is running, but then somehow it shows `local-server-1> Timed out` in log output and shows password prompt again. It works perfectly when not behind a VPN. The VPN is used for connecting to a machine in my office while I'm working from home. I don't know if it's VSCode remote ssh needs something that my VPN app does not support.

- VSCode Version: 1.65.2
- Local OS Version: macOS 12.2
- Remote OS Version: CentOS Linux release 7.9.2009
- Remote Extension/Connection Type: SSH
- Logs: 
```
[12:26:46.716] Log Level: 2
[12:26:46.717] remote-ssh@0.76.1
[12:26:46.718] darwin x64
[12:26:46.731] SSH Resolver called for "ssh-remote+vm", attempt 1
[12:26:46.732] "remote.SSH.useLocalServer": true
[12:26:46.732] "remote.SSH.path": undefined
[12:26:46.732] "remote.SSH.configFile": undefined
[12:26:46.732] "remote.SSH.useFlock": true
[12:26:46.735] "remote.SSH.lockfilesInTmp": false
[12:26:46.735] "remote.SSH.localServerDownload": auto
[12:26:46.735] "remote.SSH.remoteServerListenOnSocket": false
[12:26:46.735] "remote.SSH.showLoginTerminal": true
[12:26:46.735] "remote.SSH.defaultExtensions": []
[12:26:46.735] "remote.SSH.loglevel": 2
[12:26:46.736] "remote.SSH.enableDynamicForwarding": true
[12:26:46.736] "remote.SSH.enableRemoteCommand": false
[12:26:46.736] "remote.SSH.serverPickPortsFromRange": {}
[12:26:46.736] "remote.SSH.serverInstallPath": {}
[12:26:46.742] SSH Resolver called for host: vm
[12:26:46.743] Setting up SSH remote "vm"
[12:26:46.747] Acquiring local install lock: /var/folders/w6/5h6wf4dj087_xtgns4gxssgm0000gn/T/vscode-remote-ssh-4049c22c-install.lock
[12:26:46.749] Looking for existing server data file at /Users/jason/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-4049c22c-c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1-0.76.1/data.json
[12:26:46.750] Using commit id "c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1" and quality "stable" for server
[12:26:46.755] Install and start server if needed
[12:26:46.778] PATH: /Users/jason/.yarn/bin:/Users/jason/.config/yarn/global/node_modules/.bin:/usr/local/opt/gettext/bin:/Users/jason/.deno/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/GPAC.app/Contents/MacOS:/usr/local/go/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/jason/Documents/flutter/bin:/Users/jason/Library/Android/sdk/platform-tools:/Users/jason/go/bin:/Users/jason/Library/Android/sdk/ndk/21.3.6528147
[12:26:46.778] Checking ssh with "ssh -V"
[12:26:46.786] > OpenSSH_8.6p1, LibreSSL 2.8.3

[12:26:46.788] askpass server listening on /var/folders/w6/5h6wf4dj087_xtgns4gxssgm0000gn/T/vscode-ssh-askpass-5aedde97b87363fbb2b55473df7ac63b5bd58f01.sock
[12:26:46.789] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/w6/5h6wf4dj087_xtgns4gxssgm0000gn/T/vscode-ssh-askpass-078a647c477698f2cd3fb8cc8f19db525dfb199b.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","61700","-o","ConnectTimeout=15","vm"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/jason/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-4049c22c-c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1-0.76.1/data.json"}
[12:26:46.789] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.xgstrfQcSZ/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/jason/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/jason/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/w6/5h6wf4dj087_xtgns4gxssgm0000gn/T/vscode-ssh-askpass-5aedde97b87363fbb2b55473df7ac63b5bd58f01.sock"}
[12:26:46.790] Spawned 1246
[12:26:46.908] > local-server-1> Spawned ssh, pid=1252
[12:26:46.911] stderr> OpenSSH_8.6p1, LibreSSL 2.8.3
[12:26:47.465] stderr> debug1: Server host key: ssh-ed25519 SHA256:e+yxwMvkyw9nTYcwGs7Q4cHa9du9p8Kkqo1hgldxss4
[12:26:47.676] Got askpass request: {"request":"root@192.168.75.252's password:"}
[12:26:47.676] Showing password prompt
[12:26:47.677] Listening for interwindow password on /var/folders/w6/5h6wf4dj087_xtgns4gxssgm0000gn/T/vscode-ssh-askpass-6d9f826c1185b620c9f52366af263b5af841cca4.sock
[12:26:47.677] Writing password prompt to globalState
[12:26:56.767] Got password response
[12:26:56.767] Interactor gave response: *******
[12:26:56.768] Cleaning up other-window auth server
[12:26:56.827] stderr> Authenticated to 192.168.75.252 ([192.168.75.252]:22).
[12:26:56.859] > Last failed login: Mon Mar 14 11:54:47 CST 2022 from 10.10.10.183 on ssh:notty
> There were 6 failed login attempts since the last successful login.
[12:26:56.877] > ready: 92be48f1968c
[12:26:56.885] > Linux 3.10.0-1160.2.2.el7.x86_64 #1 SMP Tue Oct 20 16:53:08 UTC 2020
[12:26:56.885] Platform: linux
[12:26:56.893] > /bin/bash
[12:26:56.894] Shell: bash
[12:26:56.934] > 92be48f1968c: running
[12:26:56.971] > Acquiring lock on /root/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/vscode-remote-lock.root.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
[12:26:56.978] > Found existing installation at /root/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1...
[12:26:56.978] > Checking /root/.vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.log and /root/.vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.pid for a running server
[12:26:56.979] > Looking for server with pid: 9738
[12:26:57.006] > Found running server...
[12:26:57.008] >  
> *
[12:26:57.009] > * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
[12:26:57.022] > Checking server status on port 45825 with wget
[12:26:57.030] > 92be48f1968c: start
> SSH_AUTH_SOCK====
> DISPLAY====
[12:26:57.031] > webUiAccessToken====
> listeningOn==45825==
> osReleaseId==centos==
> arch==x86_64==
> tmpDir==/run/user/0==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
[12:26:57.032] > extInstallTime====
> serverStartTime====
> connectionToken==1111111a-a1aa-1111-a1a1-11a111a1111a==
> 92be48f1968c: end
[12:26:57.032] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====webUiAccessToken====
listeningOn==45825==
osReleaseId==centos==
arch==x86_64==
tmpDir==/run/user/0==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====extInstallTime====
serverStartTime====
connectionToken==1111111a-a1aa-1111-a1a1-11a111a1111a==

[12:26:57.032] Remote server is listening on 45825
[12:26:57.033] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":45825},"osReleaseId":"centos","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/0","platform":"linux","connectionToken":"1111111a-a1aa-1111-a1a1-11a111a1111a"},"installUnpackCode":""}
[12:26:57.034] Persisting server connection details to /Users/jason/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-4049c22c-c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1-0.76.1/data.json
[12:26:57.060] Starting forwarding server. localPort 61707 -> socksPort 61700 -> remotePort 45825
[12:26:57.061] Forwarding server listening on 61707
[12:26:57.061] Waiting for ssh tunnel to be ready
[12:26:57.062] [Forwarding server 61707] Got connection 0
[12:26:57.063] Tunneled 45825 to local port 61707
[12:26:57.063] Resolved "ssh-remote+vm" to "127.0.0.1:61707"
[12:26:57.071] ------




[12:26:57.104] [Forwarding server 61707] Got connection 1
[12:26:57.137] [Forwarding server 61707] Got connection 2
[12:27:17.671] ------




[12:27:17.671] SSH Resolver called for "ssh-remote+vm", attempt 2, (Reconnection)
[12:27:17.672] SSH Resolver called for host: vm
[12:27:17.672] Setting up SSH remote "vm"
[12:27:17.673] Acquiring local install lock: /var/folders/w6/5h6wf4dj087_xtgns4gxssgm0000gn/T/vscode-remote-ssh-4049c22c-install.lock
[12:27:17.673] Looking for existing server data file at /Users/jason/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-4049c22c-c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1-0.76.1/data.json
[12:27:17.674] Found local server running: {"remoteListeningOn":{"port":45825},"osReleaseId":"centos","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/0","platform":"linux","connectionToken":"1111111a-a1aa-1111-a1a1-11a111a1111a","pid":1246,"ipcHandlePath":"/var/folders/w6/5h6wf4dj087_xtgns4gxssgm0000gn/T/vscode-ssh-askpass-078a647c477698f2cd3fb8cc8f19db525dfb199b.sock","socksPort":61700,"startupTime":1647232006790}
[12:27:17.674] Running server is stale. Ignoring
[12:27:17.674] Using commit id "c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1" and quality "stable" for server
[12:27:17.677] Install and start server if needed
[12:27:17.679] askpass server listening on /var/folders/w6/5h6wf4dj087_xtgns4gxssgm0000gn/T/vscode-ssh-askpass-df2f616861ab6561838fb01e5e8c7955a3f90827.sock
[12:27:17.680] Spawning local server with {"serverId":2,"ipcHandlePath":"/var/folders/w6/5h6wf4dj087_xtgns4gxssgm0000gn/T/vscode-ssh-askpass-2348af4b739fe2039932e65b09933ec0005c4d0d.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","61721","-o","ConnectTimeout=15","vm"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/jason/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-4049c22c-c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1-0.76.1/data.json"}
[12:27:17.680] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.xgstrfQcSZ/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/jason/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/jason/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/w6/5h6wf4dj087_xtgns4gxssgm0000gn/T/vscode-ssh-askpass-df2f616861ab6561838fb01e5e8c7955a3f90827.sock"}
[12:27:17.680] Spawned 1265
[12:27:17.798] > local-server-2> Spawned ssh, pid=1271
[12:27:17.801] stderr> OpenSSH_8.6p1, LibreSSL 2.8.3
[12:27:18.354] stderr> debug1: Server host key: ssh-ed25519 SHA256:e+yxwMvkyw9nTYcwGs7Q4cHa9du9p8Kkqo1hgldxss4
[12:27:18.543] Got askpass request: {"request":"root@192.168.75.252's password:"}
[12:27:18.543] Showing password prompt
[12:27:18.544] Listening for interwindow password on /var/folders/w6/5h6wf4dj087_xtgns4gxssgm0000gn/T/vscode-ssh-askpass-f4bfe972ca479aabb8f92c34ffb475fbfd8af883.sock
[12:27:18.544] Writing password prompt to globalState
[12:27:22.297] > local-server-1> Timed out
[12:27:22.300] Local server exit: 0

```

Steps to Reproduce:

1. Start some VPN app 
2. Use VSCode remote-ssh to connect to a remote machine, enter the ssh password
3. Wait for `> local-server-1> Timed out` appears in Remote-SSH log output. Then it shows password prompt again.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by Nick-OpusVL** [comment]
I have a Fedora host connecting to an Ubuntu host, and can provide you with the developer tools console output you originally asked for the OP.  I suspect this is the same issue.

I also want to add that in order to get an ordinary SSH shell on the machine to which I am connecting I had to add the following to the top of my `~/.ssh/config`:
```
KexAlgorithms ecdh-sha2-nistp521
  # ^ Bugfix for OpenVPN
  # ^ https://superuser.com/a/1462220
```

However that change was to stop a connection issue - but this is clearly connecting to the server (because I see the local motd) and failing later on in the process.

My logs from the output tab are:
```
[10:47:10.853] Log Level: 2
[10:47:10.855] remote-ssh@0.78.0
[10:47:10.855] linux x64
[10:47:10.869] SSH Resolver called for "ssh-remote+dev-03.[redacted]", attempt 1
[10:47:10.870] "remote.SSH.useLocalServer": true
[10:47:10.870] "remote.SSH.path": undefined
[10:47:10.870] "remote.SSH.configFile": undefined
[10:47:10.871] "remote.SSH.useFlock": true
[10:47:10.871] "remote.SSH.lockfilesInTmp": false
[10:47:10.871] "remote.SSH.localServerDownload": auto
[10:47:10.871] "remote.SSH.remoteServerListenOnSocket": false
[10:47:10.871] "remote.SSH.showLoginTerminal": false
[10:47:10.871] "remote.SSH.defaultExtensions": []
[10:47:10.871] "remote.SSH.loglevel": 2
[10:47:10.872] "remote.SSH.enableDynamicForwarding": true
[10:47:10.872] "remote.SSH.enableRemoteCommand": false
[10:47:10.872] "remote.SSH.serverPickPortsFromRange": {}
[10:47:10.872] "remote.SSH.serverInstallPath": {}
[10:47:10.895] SSH Resolver called for host: dev-03.rug-01.[redacted]
[10:47:10.895] Setting up SSH remote "dev-03.rug-01.[redacted]"
[10:47:10.902] Acquiring local install lock: /tmp/vscode-remote-ssh-b9292460-install.lock
[10:47:10.912] Looking for existing server data file at /home/nick-[redacted]/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-b9292460-e18005f0f1b33c29e81d732535d8c0e47cafb0b5-0.78.0/data.json
[10:47:10.913] Using commit id "e18005f0f1b33c29e81d732535d8c0e47cafb0b5" and quality "stable" for server
[10:47:10.916] Install and start server if needed
[10:47:10.920] PATH: /home/nick-[redacted]/.local/bin:/home/nick-[redacted]/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
[10:47:10.921] Checking ssh with "ssh -V"
[10:47:10.949] > OpenSSH_8.7p1, OpenSSL 1.1.1n  FIPS 15 Mar 2022

[10:47:10.953] askpass server listening on /run/user/1001/vscode-ssh-askpass-90673b1d8fc870b06e917f18db2c473a3d35d13b.sock
[10:47:10.953] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1001/vscode-ssh-askpass-c78a2487146f41ff89fe08827706893f0e0970a7.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","36983","-o","ConnectTimeout=60","dev-03.rug-01.[redacted]"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/nick-[redacted]/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-b9292460-e18005f0f1b33c29e81d732535d8c0e47cafb0b5-0.78.0/data.json"}
[10:47:10.953] Local server env: {"SSH_AUTH_SOCK":"/run/user/1001/keyring/ssh","SHELL":"/bin/bash","DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/nick-[redacted]/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/nick-[redacted]/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1001/vscode-ssh-askpass-90673b1d8fc870b06e917f18db2c473a3d35d13b.sock"}
[10:47:10.959] Spawned 22937
[10:47:11.109] > local-server-1> Spawned ssh, pid=22945
[10:47:11.115] stderr> OpenSSH_8.7p1, OpenSSL 1.1.1n  FIPS 15 Mar 2022
[10:47:11.538] stderr> debug1: Server host key: ssh-ed25519 SHA256:iFQeAPSS83ilvvlBEjHZjs+oaQcanoJuhHeoDAoOfxk
[10:47:11.540] stderr> Host key fingerprint is SHA256:iFQeAPSS83ilvvlBEjHZjs+oaQcanoJuhHeoDAoOfxk
[10:47:11.541] stderr> +--[ED25519 256]--+
[10:47:11.541] stderr> | .o.++o          |
[10:47:11.541] stderr> |   o.=..         |
[10:47:11.541] stderr> |  + +oo          |
[10:47:11.541] stderr> |   *.=..         |
[10:47:11.542] stderr> |. ..*+o S        |
[10:47:11.542] stderr> |*.+oEoo          |
[10:47:11.542] stderr> |@*.=.o.          |
[10:47:11.542] stderr> |**= +o .         |
[10:47:11.543] stderr> |+o oo..          |
[10:47:11.543] stderr> +----[SHA256]-----+
[10:47:11.980] stderr> Authenticated to dev-03.rug-01.[redacted] ([<redacted>]:22) using "publickey".
[10:47:12.708] > Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-81-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   System information as of Tue Apr 12 10:47:12 BST 2022
> 
>   System load:                    0.04
>   Usage of /:                     92.7% of 466.77GB
>   Memory usage:                   62%
>   Swap usage:                     100%
>   Processes:                      578
>   Users logged in:                1
>   IP address for enp2s0:          <redacted>
[redacted]
> 
>   => / is using 92.7% of 466.77GB
>   => /mnt/ubuhome is using 86.9% of 541.25GB
> 
[redacted]
> 
> New release '20.04.4 LTS' available.
> Run 'do-release-upgrade' to upgrade to it.
> 
> Your Hardware Enablement Stack (HWE) is supported until April 2023.
> You have new mail.
[10:47:12.814] > ready: 1d23d5fffcdc
[10:47:12.947] > Linux 5.4.0-81-generic #91~18.04.1-Ubuntu SMP Fri Jul 23 13:36:29 UTC 2021
[10:47:12.948] Platform: linux
[10:47:13.077] > /bin/bash
[10:47:13.078] Shell: bash
[10:47:13.078] Creating bash subshell inside "bash"
[10:47:13.206] > bash version:  4.4.20(1)-release
[10:47:13.254] > bash version:  4.4.20(1)-release
[10:47:13.301] > bash version:  4.4.20(1)-release
[10:48:12.961] Terminating local server
[10:48:12.969] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/home/nick-[redacted]/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:586167)
	at Timeout._onTimeout (/home/nick-[redacted]/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:631243)
	at listOnTimeout (node:internal/timers:557:17)
	at processTimers (node:internal/timers:500:7)
[10:48:13.013] ------




[10:48:13.017] Local server exit: 15
[11:12:10.249] ConfigFileWatcher: start watching file:///home/nick-[redacted]/.ssh/config
[11:12:10.250] ConfigFileWatcher: adding save listener
[11:12:10.251] ConfigFileWatcher: adding close listener
```

The console log:

```
workbench.desktop.main.js:sourcemap:610  INFO Ignoring configured affinity for 'pub.name' because the extension is unknown or cannot execute.
workbench.desktop.main.js:sourcemap:610  INFO Invoking resolveAuthority(ssh-remote)
workbench.desktop.main.js:sourcemap:3100 The customer named _initialize has been holding on to the lock for 30s. This might be a problem.
(anonymous) @ workbench.desktop.main.js:sourcemap:3100
workbench.desktop.main.js:sourcemap:610   ERR resolveAuthority(ssh-remote) returned an error after 62167 ms Error: Connecting with SSH timed out
    at Fl._resolveAuthority (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3103:7152)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Fl._scanAndHandleExtensions (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3103:9159)
    at async Fl._initialize (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3100:22392)
workbench.desktop.main.js:sourcemap:610   ERR Error received from starting extension host (kind: Remote)
workbench.desktop.main.js:sourcemap:610   ERR Error: Connecting with SSH timed out
    at Fl._resolveAuthority (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3103:7152)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Fl._scanAndHandleExtensions (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3103:9159)
    at async Fl._initialize (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3100:22392)
workbench.desktop.main.js:sourcemap:610   ERR [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
3workbench.desktop.main.js:sourcemap:610   ERR Error: Connecting with SSH timed out
    at Fl._resolveAuthority (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3103:7152)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Fl._scanAndHandleExtensions (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3103:9159)
    at async Fl._initialize (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3100:22392)
workbench.desktop.main.js:sourcemap:610   ERR Cannot register remote filesystem provider. Error while fetching remote environment. Connecting with SSH timed out
workbench.desktop.main.js:sourcemap:796 Failed to connect to the remote extension host server (Error: Connecting with SSH timed out)
onDidChangeNotification @ workbench.desktop.main.js:sourcemap:796
workbench.desktop.main.js:sourcemap:610   ERR Error: Connecting with SSH timed out
    at Fl._resolveAuthority (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3103:7152)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Fl._scanAndHandleExtensions (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3103:9159)
    at async Fl._initialize (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3100:22392)
workbench.desktop.main.js:sourcemap:610  WARN Ignoring the error while validating workspace folder vscode-remote://ssh-remote%2Bdev-03.rug-01.opusvl.net/home/nick.booker/cu/bca-upgrade - No file system provider found for resource 'vscode-remote://ssh-remote%2Bdev-03.rug-01.opusvl.net/home/nick.booker/cu/bca-upgrade'
workbench.desktop.main.js:sourcemap:610   ERR ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdev-03.rug-01.opusvl.net/home/nick.booker/cu/bca-upgrade'
    at p.withProvider (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:27776)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async p.doWatch (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:41538)
    at async vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:41404
workbench.desktop.main.js:sourcemap:610   ERR No file system provider found for resource 'vscode-remote://ssh-remote%2Bdev-03.rug-01.opusvl.net/home/nick.booker/cu/bca-upgrade/.git/config': ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdev-03.rug-01.opusvl.net/home/nick.booker/cu/bca-upgrade/.git/config'
    at p.withProvider (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:27776)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async p.exists (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:30371)
    at async Promise.all (index 0)
workbench.desktop.main.js:sourcemap:610  INFO Ignoring configured affinity for 'pub.name' because the extension is unknown or cannot execute.
workbench.desktop.main.js:sourcemap:610   ERR No file system provider found for resource 'vscode-remote://ssh-remote%2Bdev-03.rug-01.opusvl.net/home/nick.booker/cu/bca-upgrade/pom.xml': ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdev-03.rug-01.opusvl.net/home/nick.booker/cu/bca-upgrade/pom.xml'
    at p.withProvider (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:27776)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async p.exists (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:30371)
    at async Promise.all (index 0)
workbench.desktop.main.js:sourcemap:610   ERR Connecting with SSH timed out: Error: Connecting with SSH timed out
    at Fl._resolveAuthority (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3103:7152)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Fl._scanAndHandleExtensions (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3103:9159)
    at async Fl._initialize (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3100:22392)
workbench.desktop.main.js:sourcemap:610   ERR No file system provider found for resource 'vscode-remote://ssh-remote%2Bdev-03.rug-01.opusvl.net/home/nick.booker/cu/bca-upgrade': ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdev-03.rug-01.opusvl.net/home/nick.booker/cu/bca-upgrade'
    at p.withProvider (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:27776)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async p.doResolveFile (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:28858)
    at async p.resolve (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:28581)
    at async i.findWorkspaces (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1947:6441)
workbench.desktop.main.js:sourcemap:610   ERR No file system provider found for resource 'vscode-remote://ssh-remote%2Bdev-03.rug-01.opusvl.net/home/nick.booker/cu/bca-upgrade/.vscode': ENOPRO: No file system provider found for resource 'vscode-remote://ssh-remote%2Bdev-03.rug-01.opusvl.net/home/nick.booker/cu/bca-upgrade/.vscode'
    at p.withProvider (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:27776)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async p.exists (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:30371)
    at async vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2194:6374
    at async Promise.all (index 0)
    at async y._initWorkspaceFolderSnippets (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:2194:6539)
workbench.desktop.main.js:sourcemap:610   ERR Connecting with SSH timed out: Error: Connecting with SSH timed out
    at Fl._resolveAuthority (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3103:7152)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Fl._scanAndHandleExtensions (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3103:9159)
    at async Fl._initialize (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3100:22392)
workbench.desktop.main.js:sourcemap:610   ERR Error: Connecting with SSH timed out
    at Fl._resolveAuthority (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3103:7152)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Fl._scanAndHandleExtensions (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3103:9159)
    at async Fl._initialize (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3100:22392)
2workbench.desktop.main.js:sourcemap:610   ERR Connecting with SSH timed out: Error: Connecting with SSH timed out
    at Fl._resolveAuthority (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3103:7152)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Fl._scanAndHandleExtensions (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3103:9159)
    at async Fl._initialize (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:3100:22392)
```
