### ISSUE TITLE
Remote-ssh始终提示 拒绝访问，无法连接到远程服务器

### ISSUE THREAD

**Issue by Quellaer** [microsoft/vscode-remote-release#6451]
```
[11:34:32.746] Log Level: 2
[11:34:32.749] remote-ssh@0.76.1
[11:34:32.750] win32 x64
[11:34:32.765] SSH Resolver called for "ssh-remote+10.1.0.119", attempt 1
[11:34:32.766] "remote.SSH.useLocalServer": false
[11:34:32.767] "remote.SSH.showLoginTerminal": true
[11:34:32.768] "remote.SSH.remotePlatform": {}
[11:34:32.768] "remote.SSH.path": F:\\Git\\usr\\bin\\ssh.exe
[11:34:32.768] "remote.SSH.configFile": C:\\Users\\lenovo\\.ssh\\config
[11:34:32.769] "remote.SSH.useFlock": true
[11:34:32.769] "remote.SSH.lockfilesInTmp": false
[11:34:32.770] "remote.SSH.localServerDownload": auto
[11:34:32.777] "remote.SSH.remoteServerListenOnSocket": false
[11:34:32.777] "remote.SSH.showLoginTerminal": true
[11:34:32.777] "remote.SSH.defaultExtensions": []
[11:34:32.778] "remote.SSH.loglevel": 2
[11:34:32.778] "remote.SSH.enableDynamicForwarding": true
[11:34:32.779] "remote.SSH.enableRemoteCommand": false
[11:34:32.779] "remote.SSH.serverPickPortsFromRange": {}
[11:34:32.780] "remote.SSH.serverInstallPath": {}
[11:34:32.924] SSH Resolver called for host: 10.1.0.119
[11:34:32.925] Setting up SSH remote "10.1.0.119"
[11:34:32.938] Using commit id "c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1" and quality "stable" for server
[11:34:32.957] Install and start server if needed
[11:34:58.592] Checking ssh with "F:\\Git\\usr\\bin\\ssh.exe -V"
[11:34:59.201] > OpenSSH_8.8p1, OpenSSL 1.1.1l  24 Aug 2021
[11:34:59.203] > 

[11:34:59.257] Using SSH config file "C:\\Users\\lenovo\\.ssh\\config"
[11:34:59.261] Running script with connection command: "F:\\Git\\usr\\bin\\ssh.exe" -T -D 54714 -F "C:\\Users\\lenovo\\.ssh\\config" "10.1.0.119" bash
[11:34:59.293] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[11:35:02.067] > 拒绝访问。
> ]0;C:\WINDOWS\System32\cmd.exe
[11:35:02.069] Got some output, clearing connection timeout
[11:35:02.075] > 拒绝访问。
> 
> 
> 
> 
> 
> 
> 
[11:35:03.049] > xxy@10.1.0.119's password: 
[11:35:07.278] > 
[11:35:09.419] "install" terminal command done
[11:35:09.423] Install terminal quit with output: xxy@10.1.0.119's password: 
[11:35:09.424] Received install output: xxy@10.1.0.119's password: 
[11:35:09.432] Failed to parse remote port from server output
[11:35:09.438] Resolver error: Error: 
	at Function.Create (c:\Users\lenovo\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:586041)
	at Object.t.handleInstallOutput (c:\Users\lenovo\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:584693)
	at Object.t.tryInstall (c:\Users\lenovo\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:681846)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\lenovo\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:644486
	at async Object.t.withShowDetailsEvent (c:\Users\lenovo\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:647831)
	at async Object.t.resolve (c:\Users\lenovo\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:645565)
	at async c:\Users\lenovo\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:722872
[11:35:09.494] ------
```

**Comment by roblourens** [comment]
拒绝访问 - access denied? Are you sure you entered your password correctly?

**Comment by Quellaer** [comment]
> 拒绝访问 - 访问被拒绝？您确定您输入的密码正确吗？
> 
> 你能提供更多细节吗？

Finally, I solved this problem by opening Vscode as an administrator. Thank you for your reply.

**Comment by Quellaer** [comment]
> 拒绝访问 - access denied? Are you sure you entered your password correctly?
> 
> Can you give more details?

Finally, I solved this problem by opening Vscode as an administrator. Thank you for your reply.
