### ISSUE TITLE
dotfiles repo not loading

### ISSUE THREAD

**Issue by avadhanij6si** [microsoft/vscode-remote-release#6484]
Issue Type: <b>Bug</b>

I have a dotfiles repo created and set up as described in the docs page, but I can't get the Codespace to load it reliably.

Sometimes it does, and sometimes it doesn't

VS Code version: Code 1.65.2 (Universal) (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1072-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 5d2a33bd-2e3c-47a3-8243-daa6083775fe|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces|
|OS|Linux x64 5.4.0-1072-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz (4 x 2693)|
|Memory (System)|7.77GB (0.26GB free)|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
codespaces|Git|1.5.7
gitlens|eam|12.0.5
codespaces|Git|1.5.7
vscode-pull-request-github|Git|0.38.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30450902
vscscmwlcmc:30438804
vscgsvid1:30447480
vscaat:30438848
pynewfile477:30450038

```

</details>

**Comment by chrmarti** [comment]
@avadhanij6si Could you append the `/workspaces/.codespaces/.persistedshare/EnvironmentLog.txt` from your Codespace?

**Comment by avadhanij6si** [comment]
Fresh Codespace logs - 

```
[2022-03-23T07:04:28.269Z] @microsoft/vscode-dev-containers-cli 0.60.0.
[2022-03-23T07:04:28.269Z] Start: Resolving Remote
[2022-03-23T07:04:28.276Z] Start: Run: docker ps -q -a --filter label=Type=codespaces
[2022-03-23T07:04:28.342Z] Stop (66 ms): Run: docker ps -q -a --filter label=Type=codespaces
[2022-03-23T07:04:28.343Z] Start: Run: docker inspect --type container 00aa4abbe1c7
[2022-03-23T07:04:28.381Z] Stop (38 ms): Run: docker inspect --type container 00aa4abbe1c7
[2022-03-23T07:04:28.383Z] Start: Inspecting container
[2022-03-23T07:04:28.383Z] Start: Run: docker inspect --type container 00aa4abbe1c7ac7c9b86daaa6a380a4fa154add7cdbe0afc5bee99d294ebd5aa
[2022-03-23T07:04:28.422Z] Stop (39 ms): Run: docker inspect --type container 00aa4abbe1c7ac7c9b86daaa6a380a4fa154add7cdbe0afc5bee99d294ebd5aa
[2022-03-23T07:04:28.423Z] Stop (40 ms): Inspecting container
[2022-03-23T07:04:28.424Z] Start: Run in container: /bin/sh
[2022-03-23T07:04:28.429Z] Start: Run in container: uname -m
[2022-03-23T07:04:28.525Z] x86_64
[2022-03-23T07:04:28.525Z] 
[2022-03-23T07:04:28.525Z] Stop (96 ms): Run in container: uname -m
[2022-03-23T07:04:28.525Z] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[2022-03-23T07:04:28.529Z] NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
[2022-03-23T07:04:28.530Z] 
[2022-03-23T07:04:28.530Z] Stop (5 ms): Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[2022-03-23T07:04:28.530Z] Start: Run in container: cat /etc/passwd
[2022-03-23T07:04:28.538Z] Stop (8 ms): Run in container: cat /etc/passwd
[2022-03-23T07:04:28.539Z] Start: Run in container: test -d /home/codespace/.vscode-remote
[2022-03-23T07:04:28.540Z] 
[2022-03-23T07:04:28.540Z] 
[2022-03-23T07:04:28.540Z] Stop (1 ms): Run in container: test -d /home/codespace/.vscode-remote
[2022-03-23T07:04:28.540Z] Start: Run in container: test -f '/var/vscode-remote/.patchEtcEnvironmentMarker'
[2022-03-23T07:04:28.542Z] 
[2022-03-23T07:04:28.542Z] 
[2022-03-23T07:04:28.542Z] Stop (2 ms): Run in container: test -f '/var/vscode-remote/.patchEtcEnvironmentMarker'
[2022-03-23T07:04:28.542Z] Start: Run in container: test -f '/var/vscode-remote/.patchEtcProfileMarker'
[2022-03-23T07:04:28.543Z] 
[2022-03-23T07:04:28.543Z] 
[2022-03-23T07:04:28.543Z] Stop (1 ms): Run in container: test -f '/var/vscode-remote/.patchEtcProfileMarker'
[2022-03-23T07:04:28.543Z] Start: Run in container: test ! -f '/home/codespace/.vscode-remote/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/home/codespace/.vscode-remote/data/Machine' && { > '/home/codespace/.vscode-remote/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[2022-03-23T07:04:28.544Z] 
[2022-03-23T07:04:28.544Z] 
[2022-03-23T07:04:28.545Z] Exit code 1
[2022-03-23T07:04:28.545Z] Stop (2 ms): Run in container: test ! -f '/home/codespace/.vscode-remote/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/home/codespace/.vscode-remote/data/Machine' && { > '/home/codespace/.vscode-remote/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[2022-03-23T07:04:28.545Z] Start: Run in container: cat /home/codespace/.vscode-remote/data/Machine/settings.json
[2022-03-23T07:04:28.549Z] {
        "go.toolsManagement.checkForUpdates": "local",
        "go.useLanguageServer": true,
        "go.gopath": "/go",
        "go.goroot": "/usr/local/go",
        "python.defaultInterpreterPath": "/opt/python/3.7/bin/python",
        "python.linting.enabled": true,
        "python.linting.pylintEnabled": true,
        "python.formatting.autopep8Path": "/usr/local/py-utils/bin/autopep8",
        "python.formatting.blackPath": "/usr/local/py-utils/bin/black",
        "python.formatting.yapfPath": "/usr/local/py-utils/bin/yapf",
        "python.linting.banditPath": "/usr/local/py-utils/bin/bandit",
        "python.linting.flake8Path": "/usr/local/py-utils/bin/flake8",
        "python.linting.mypyPath": "/usr/local/py-utils/bin/mypy",
        "python.linting.pycodestylePath": "/usr/local/py-utils/bin/pycodestyle",
        "python.linting.pydocstylePath": "/usr/local/py-utils/bin/pydocstyle",
        "python.linting.pylintPath": "/usr/local/py-utils/bin/pylint",
        "lldb.executable": "/usr/bin/lldb",
        "files.watcherExclude": {
                "**/target/**": true
        }
}
[2022-03-23T07:04:28.550Z] 
[2022-03-23T07:04:28.550Z] Stop (5 ms): Run in container: cat /home/codespace/.vscode-remote/data/Machine/settings.json
[2022-03-23T07:04:28.550Z] Start: Run in container: ls /home/codespace/.vscode-remote/bin/*/node | head -n 1
[2022-03-23T07:04:28.552Z] 
[2022-03-23T07:04:28.552Z] ls: cannot access '/home/codespace/.vscode-remote/bin/*/node': No such file or directory
[2022-03-23T07:04:28.552Z] Stop (2 ms): Run in container: ls /home/codespace/.vscode-remote/bin/*/node | head -n 1
[2022-03-23T07:04:28.553Z] userEnvProbe: none (default)
[2022-03-23T07:04:28.553Z] Start: Run in container: mkdir -p '/home/codespace/.vscode-remote/data/Machine' && CONTENT="$(cat '/home/codespace/.vscode-remote/data/Machine/.onCreateCommandMarker' 2>/dev/null || echo ENOENT)" && [ "${CONTENT:-2022-03-23T07:04:25.399047885Z}" != '2022-03-23T07:04:25.399047885Z' ] && echo '2022-03-23T07:04:25.399047885Z' > '/home/codespace/.vscode-remote/data/Machine/.onCreateCommandMarker'
[2022-03-23T07:04:28.556Z] 
[2022-03-23T07:04:28.556Z] 
[2022-03-23T07:04:28.556Z] Stop (3 ms): Run in container: mkdir -p '/home/codespace/.vscode-remote/data/Machine' && CONTENT="$(cat '/home/codespace/.vscode-remote/data/Machine/.onCreateCommandMarker' 2>/dev/null || echo ENOENT)" && [ "${CONTENT:-2022-03-23T07:04:25.399047885Z}" != '2022-03-23T07:04:25.399047885Z' ] && echo '2022-03-23T07:04:25.399047885Z' > '/home/codespace/.vscode-remote/data/Machine/.onCreateCommandMarker'
[2022-03-23T07:04:28.557Z] Start: Run in container: mkdir -p '/home/codespace/.vscode-remote/data/Machine' && CONTENT="$(cat '/home/codespace/.vscode-remote/data/Machine/.updateContentCommandMarker' 2>/dev/null || echo ENOENT)" && [ "${CONTENT:-2022-03-23T07:04:25.399047885Z}" != '2022-03-23T07:04:25.399047885Z' ] && echo '2022-03-23T07:04:25.399047885Z' > '/home/codespace/.vscode-remote/data/Machine/.updateContentCommandMarker'
[2022-03-23T07:04:28.560Z] 
[2022-03-23T07:04:28.560Z] 
[2022-03-23T07:04:28.560Z] Stop (3 ms): Run in container: mkdir -p '/home/codespace/.vscode-remote/data/Machine' && CONTENT="$(cat '/home/codespace/.vscode-remote/data/Machine/.updateContentCommandMarker' 2>/dev/null || echo ENOENT)" && [ "${CONTENT:-2022-03-23T07:04:25.399047885Z}" != '2022-03-23T07:04:25.399047885Z' ] && echo '2022-03-23T07:04:25.399047885Z' > '/home/codespace/.vscode-remote/data/Machine/.updateContentCommandMarker'
[2022-03-23T07:04:28.561Z] Start: Run in container: mkdir -p '/home/codespace/.vscode-remote/data/Machine' && CONTENT="$(cat '/home/codespace/.vscode-remote/data/Machine/.postCreateCommandMarker' 2>/dev/null || echo ENOENT)" && [ "${CONTENT:-2022-03-23T07:04:25.399047885Z}" != '2022-03-23T07:04:25.399047885Z' ] && echo '2022-03-23T07:04:25.399047885Z' > '/home/codespace/.vscode-remote/data/Machine/.postCreateCommandMarker'
[2022-03-23T07:04:28.561Z] Stop (292 ms): Resolving Remote
[2022-03-23T07:04:28.566Z] 
[2022-03-23T07:04:28.566Z] 
[2022-03-23T07:04:28.566Z] Stop (5 ms): Run in container: mkdir -p '/home/codespace/.vscode-remote/data/Machine' && CONTENT="$(cat '/home/codespace/.vscode-remote/data/Machine/.postCreateCommandMarker' 2>/dev/null || echo ENOENT)" && [ "${CONTENT:-2022-03-23T07:04:25.399047885Z}" != '2022-03-23T07:04:25.399047885Z' ] && echo '2022-03-23T07:04:25.399047885Z' > '/home/codespace/.vscode-remote/data/Machine/.postCreateCommandMarker'
[2022-03-23T07:04:28.567Z] Running the postCreateCommand from devcontainer.json...

[2022-03-23T07:04:28.568Z] Start: Run in container:
[2022-03-23T07:04:28.873Z] unset OPENVPN_CONFIG
[2022-03-23T07:04:28.925Z] unset OPENVPN_CONFIG
.devcontainer/post-creation-config.sh: line 34: /usr/bin/code: No such file or directory
[2022-03-23T07:04:28.930Z] Stop (362 ms): Run in container:
[2022-03-23T07:04:28.931Z] postCreateCommand failed with exit code 127. Skipping any further user-provided commands.
[2022-03-23T07:04:28.934Z] Error: Command failed: /bin/sh -c bash .devcontainer/post-creation-config.sh
    at p9 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:227:137)
    at async c9 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:220:2754)
    at async /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node/devContainersCLI.js:203:7625
```

Logs after stopping and starting container:
```
[2022-03-23T07:18:43.232Z] @microsoft/vscode-dev-containers-cli 0.60.0.
[2022-03-23T07:18:43.232Z] Start: Resolving Remote
[2022-03-23T07:18:43.238Z] Start: Run: docker ps -q -a --filter label=Type=codespaces
[2022-03-23T07:18:43.277Z] Stop (39 ms): Run: docker ps -q -a --filter label=Type=codespaces
[2022-03-23T07:18:43.278Z] Start: Run: docker inspect --type container 00aa4abbe1c7
[2022-03-23T07:18:43.316Z] Stop (38 ms): Run: docker inspect --type container 00aa4abbe1c7
[2022-03-23T07:18:43.317Z] Start: Inspecting container
[2022-03-23T07:18:43.317Z] Start: Run: docker inspect --type container 00aa4abbe1c7ac7c9b86daaa6a380a4fa154add7cdbe0afc5bee99d294ebd5aa
[2022-03-23T07:18:43.359Z] Stop (42 ms): Run: docker inspect --type container 00aa4abbe1c7ac7c9b86daaa6a380a4fa154add7cdbe0afc5bee99d294ebd5aa
[2022-03-23T07:18:43.360Z] Stop (43 ms): Inspecting container
[2022-03-23T07:18:43.361Z] Start: Run in container: /bin/sh
[2022-03-23T07:18:43.365Z] Start: Run in container: uname -m
[2022-03-23T07:18:43.440Z] x86_64
[2022-03-23T07:18:43.441Z] 
[2022-03-23T07:18:43.441Z] Stop (76 ms): Run in container: uname -m
[2022-03-23T07:18:43.441Z] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[2022-03-23T07:18:43.442Z] NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
[2022-03-23T07:18:43.443Z] 
[2022-03-23T07:18:43.443Z] Stop (2 ms): Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[2022-03-23T07:18:43.443Z] Start: Run in container: cat /etc/passwd
[2022-03-23T07:18:43.444Z] Stop (1 ms): Run in container: cat /etc/passwd
[2022-03-23T07:18:43.445Z] Start: Run in container: test -d /home/codespace/.vscode-remote
[2022-03-23T07:18:43.446Z] 
[2022-03-23T07:18:43.446Z] 
[2022-03-23T07:18:43.446Z] Stop (1 ms): Run in container: test -d /home/codespace/.vscode-remote
[2022-03-23T07:18:43.446Z] Start: Run in container: test -f '/var/vscode-remote/.patchEtcEnvironmentMarker'
[2022-03-23T07:18:43.447Z] 
[2022-03-23T07:18:43.447Z] 
[2022-03-23T07:18:43.447Z] Stop (1 ms): Run in container: test -f '/var/vscode-remote/.patchEtcEnvironmentMarker'
[2022-03-23T07:18:43.447Z] Start: Run in container: test -f '/var/vscode-remote/.patchEtcProfileMarker'
[2022-03-23T07:18:43.448Z] 
[2022-03-23T07:18:43.448Z] 
[2022-03-23T07:18:43.448Z] Stop (1 ms): Run in container: test -f '/var/vscode-remote/.patchEtcProfileMarker'
[2022-03-23T07:18:43.448Z] Start: Run in container: test ! -f '/home/codespace/.vscode-remote/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/home/codespace/.vscode-remote/data/Machine' && { > '/home/codespace/.vscode-remote/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[2022-03-23T07:18:43.449Z] 
[2022-03-23T07:18:43.449Z] 
[2022-03-23T07:18:43.449Z] Exit code 1
[2022-03-23T07:18:43.449Z] Stop (1 ms): Run in container: test ! -f '/home/codespace/.vscode-remote/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/home/codespace/.vscode-remote/data/Machine' && { > '/home/codespace/.vscode-remote/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[2022-03-23T07:18:43.449Z] Start: Run in container: cat /home/codespace/.vscode-remote/data/Machine/settings.json
[2022-03-23T07:18:43.450Z] {
        "go.toolsManagement.checkForUpdates": "local",
        "go.useLanguageServer": true,
        "go.gopath": "/go",
        "go.goroot": "/usr/local/go",
        "python.defaultInterpreterPath": "/opt/python/3.7/bin/python",
        "python.linting.enabled": true,
        "python.linting.pylintEnabled": true,
        "python.formatting.autopep8Path": "/usr/local/py-utils/bin/autopep8",
        "python.formatting.blackPath": "/usr/local/py-utils/bin/black",
        "python.formatting.yapfPath": "/usr/local/py-utils/bin/yapf",
        "python.linting.banditPath": "/usr/local/py-utils/bin/bandit",
        "python.linting.flake8Path": "/usr/local/py-utils/bin/flake8",
        "python.linting.mypyPath": "/usr/local/py-utils/bin/mypy",
        "python.linting.pycodestylePath": "/usr/local/py-utils/bin/pycodestyle",
        "python.linting.pydocstylePath": "/usr/local/py-utils/bin/pydocstyle",
        "python.linting.pylintPath": "/usr/local/py-utils/bin/pylint",
        "lldb.executable": "/usr/bin/lldb",
        "files.watcherExclude": {
                "**/target/**": true
        }
}
[2022-03-23T07:18:43.450Z] 
[2022-03-23T07:18:43.450Z] Stop (1 ms): Run in container: cat /home/codespace/.vscode-remote/data/Machine/settings.json
[2022-03-23T07:18:43.451Z] Start: Run in container: ls /home/codespace/.vscode-remote/bin/*/node | head -n 1
[2022-03-23T07:18:43.566Z] /home/codespace/.vscode-remote/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/node
[2022-03-23T07:18:43.567Z] 
[2022-03-23T07:18:43.567Z] Stop (116 ms): Run in container: ls /home/codespace/.vscode-remote/bin/*/node | head -n 1
[2022-03-23T07:18:43.567Z] userEnvProbe: none (default)
[2022-03-23T07:18:43.567Z] Start: Run in container: mkdir -p '/home/codespace/.vscode-remote/data/Machine' && CONTENT="$(cat '/home/codespace/.vscode-remote/data/Machine/.onCreateCommandMarker' 2>/dev/null || echo ENOENT)" && [ "${CONTENT:-2022-03-23T07:04:25.399047885Z}" != '2022-03-23T07:04:25.399047885Z' ] && echo '2022-03-23T07:04:25.399047885Z' > '/home/codespace/.vscode-remote/data/Machine/.onCreateCommandMarker'
[2022-03-23T07:18:43.610Z] 
[2022-03-23T07:18:43.611Z] 
[2022-03-23T07:18:43.611Z] Exit code 1
[2022-03-23T07:18:43.611Z] Stop (44 ms): Run in container: mkdir -p '/home/codespace/.vscode-remote/data/Machine' && CONTENT="$(cat '/home/codespace/.vscode-remote/data/Machine/.onCreateCommandMarker' 2>/dev/null || echo ENOENT)" && [ "${CONTENT:-2022-03-23T07:04:25.399047885Z}" != '2022-03-23T07:04:25.399047885Z' ] && echo '2022-03-23T07:04:25.399047885Z' > '/home/codespace/.vscode-remote/data/Machine/.onCreateCommandMarker'
[2022-03-23T07:18:43.611Z] Start: Run in container: mkdir -p '/home/codespace/.vscode-remote/data/Machine' && CONTENT="$(cat '/home/codespace/.vscode-remote/data/Machine/.updateContentCommandMarker' 2>/dev/null || echo ENOENT)" && [ "${CONTENT:-2022-03-23T07:04:25.399047885Z}" != '2022-03-23T07:04:25.399047885Z' ] && echo '2022-03-23T07:04:25.399047885Z' > '/home/codespace/.vscode-remote/data/Machine/.updateContentCommandMarker'
[2022-03-23T07:18:43.625Z] 
[2022-03-23T07:18:43.625Z] 
[2022-03-23T07:18:43.625Z] Exit code 1
[2022-03-23T07:18:43.625Z] Stop (14 ms): Run in container: mkdir -p '/home/codespace/.vscode-remote/data/Machine' && CONTENT="$(cat '/home/codespace/.vscode-remote/data/Machine/.updateContentCommandMarker' 2>/dev/null || echo ENOENT)" && [ "${CONTENT:-2022-03-23T07:04:25.399047885Z}" != '2022-03-23T07:04:25.399047885Z' ] && echo '2022-03-23T07:04:25.399047885Z' > '/home/codespace/.vscode-remote/data/Machine/.updateContentCommandMarker'
[2022-03-23T07:18:43.625Z] Start: Run in container: mkdir -p '/home/codespace/.vscode-remote/data/Machine' && CONTENT="$(cat '/home/codespace/.vscode-remote/data/Machine/.postCreateCommandMarker' 2>/dev/null || echo ENOENT)" && [ "${CONTENT:-2022-03-23T07:04:25.399047885Z}" != '2022-03-23T07:04:25.399047885Z' ] && echo '2022-03-23T07:04:25.399047885Z' > '/home/codespace/.vscode-remote/data/Machine/.postCreateCommandMarker'
[2022-03-23T07:18:43.625Z] Stop (393 ms): Resolving Remote
[2022-03-23T07:18:43.643Z] 
[2022-03-23T07:18:43.643Z] 
[2022-03-23T07:18:43.643Z] Exit code 1
[2022-03-23T07:18:43.643Z] Stop (18 ms): Run in container: mkdir -p '/home/codespace/.vscode-remote/data/Machine' && CONTENT="$(cat '/home/codespace/.vscode-remote/data/Machine/.postCreateCommandMarker' 2>/dev/null || echo ENOENT)" && [ "${CONTENT:-2022-03-23T07:04:25.399047885Z}" != '2022-03-23T07:04:25.399047885Z' ] && echo '2022-03-23T07:04:25.399047885Z' > '/home/codespace/.vscode-remote/data/Machine/.postCreateCommandMarker'
[2022-03-23T07:18:43.644Z] Start: Run in container: # Clone & install dotfiles
[2022-03-23T07:18:44.144Z] Cloning into '/workspaces/.codespaces/.persistedshare/dotfiles'...
[2022-03-23T07:18:48.446Z] Executing script /workspaces/.codespaces/.persistedshare/dotfiles/install.sh
[2022-03-23T07:18:48.491Z] 
[2022-03-23T07:18:48.491Z] 
[2022-03-23T07:18:48.491Z] Stop (4847 ms): Run in container: # Clone & install dotfiles
[2022-03-23T07:18:48.492Z] Start: Run in container: mkdir -p '/home/codespace/.vscode-remote/data/Machine' && CONTENT="$(cat '/home/codespace/.vscode-remote/data/Machine/.postStartCommandMarker' 2>/dev/null || echo ENOENT)" && [ "${CONTENT:-2022-03-23T07:18:41.7922147Z}" != '2022-03-23T07:18:41.7922147Z' ] && echo '2022-03-23T07:18:41.7922147Z' > '/home/codespace/.vscode-remote/data/Machine/.postStartCommandMarker'
[2022-03-23T07:18:48.495Z] 
[2022-03-23T07:18:48.495Z] 
[2022-03-23T07:18:48.495Z] Stop (3 ms): Run in container: mkdir -p '/home/codespace/.vscode-remote/data/Machine' && CONTENT="$(cat '/home/codespace/.vscode-remote/data/Machine/.postStartCommandMarker' 2>/dev/null || echo ENOENT)" && [ "${CONTENT:-2022-03-23T07:18:41.7922147Z}" != '2022-03-23T07:18:41.7922147Z' ] && echo '2022-03-23T07:18:41.7922147Z' > '/home/codespace/.vscode-remote/data/Machine/.postStartCommandMarker'
```

**Comment by avadhanij6si** [comment]
The dotfiles repo gets connected after the stop-start, and everything works as it should. The issue shows up on a fresh Codespace for what ever reason.

**Comment by avadhanij6si** [comment]
Never mind, I can see the issue in the logs. I just didn't know where to look for the logs. Thanks for pointing out the location.
