### ISSUE TITLE
Not able to connect to container

### ISSUE THREAD

**Issue by KnightKrusty** [microsoft/vscode-remote-release#6495]
Building of container works without any issue but throws an error when vscode tries to connect to container..
Not able to understand the logs 

```
Start: Run in Container: /home/node/.vscode-server-oss/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/bin/code-server-oss --log debug --force-disable-user-env --server-data-dir /home/node/.vscode-server-oss --use-host-proxy --disable-telemetry --accept-server-license-terms --host 127.0.0.1 --port 0 --connection-token-file /home/node/.vscode-server-oss/data/Machine/.connection-token-c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1 --extensions-download-dir /home/node/.vscode-server-oss/extensionsCache --start-server --disable-websocket-compression
[2022-03-24T13:15:11.530Z] Container server: (node:112) UnhandledPromiseRejectionWarning: Error: spawn /home/node/.vscode-server-oss/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/bin/code-server-oss ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
[2022-03-24T13:15:11.530Z] Container server: (node:112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2022-03-24T13:15:11.531Z] Stop (52 ms): Run in Container: /home/node/.vscode-server-oss/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/bin/code-server-oss --log debug --force-disable-user-env --server-data-dir /home/node/.vscode-server-oss --use-host-proxy --disable-telemetry --accept-server-license-terms --host 127.0.0.1 --port 0 --connection-token-file /home/node/.vscode-server-oss/data/Machine/.connection-token-c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1 --extensions-download-dir /home/node/.vscode-server-oss/extensionsCache --start-server --disable-websocket-compression
[2022-03-24T13:15:11.533Z] Error: spawn /home/node/.vscode-server-oss/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/bin/code-server-oss ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2022-03-24T13:15:11.533Z] Exit code ENOENT
[2022-03-24T13:15:11.535Z] userEnvProbe PATHs:
Probe:     '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
Container: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
[2022-03-24T13:15:11.535Z] Container server: (node:112) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
```.

**Comment by KnightKrusty** [comment]
To add more information related to container im trying to enter is from microsoft repo itself
https://github.com/Microsoft/vscode-remote-try-node

**Comment by chrmarti** [comment]
Are you running VS Code from source?

**Comment by KnightKrusty** [comment]
> Are you running VS Code from source?

I dont understand what you are asking but it seems to me that you are asking if i am building it from source it self, well manjaro (arch) doesnt have a official vscode build so I use Code-OSS, which doesnt support remote container at all, so I downloaded VScodium app image to try if remote container works or not and it does start building process but throws an error when trying to enter the container..

**Comment by chrmarti** [comment]
You need an official VS Code build to run the remote extensions. Unfortunately we don't have that for Arch Linux at the moment. There is an issue tracking this in the main repository (don't have the link right now).
