### ISSUE TITLE
Remote Development extension for VS code 2022 64x

### ISSUE THREAD

**Issue by Ndimis** [microsoft/vscode-remote-release#6504]
- VSCode Version: 17.1.2
- Local OS Version: Windows 11 Home edition Version 21H2
- Remote OS Version: Ubuntu 20
- Remote Extension/Connection Type: SSH/Docker/WSL
- Logs:
2022-03-25 10:14:30 AM - Microsoft VSIX Installer
2022-03-25 10:14:30 AM - -------------------------------------------
2022-03-25 10:14:30 AM - vsixinstaller.exe version:
2022-03-25 10:14:30 AM - 17.1.1035-preview2
2022-03-25 10:14:30 AM - -------------------------------------------
2022-03-25 10:14:30 AM - Command line parameters:
2022-03-25 10:14:30 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,D:\Software\ms-vscode-remote.vscode-remote-extensionpack-0.21.0.vsix
2022-03-25 10:14:30 AM - -------------------------------------------
2022-03-25 10:14:30 AM - Microsoft VSIX Installer
2022-03-25 10:14:30 AM - -------------------------------------------
2022-03-25 10:14:31 AM - Initializing Install...
2022-03-25 10:14:31 AM - Extension Details...
2022-03-25 10:14:31 AM - 	Identifier         : vscode-remote-extensionpack
2022-03-25 10:14:31 AM - 	Name               : Remote Development
2022-03-25 10:14:31 AM - 	Author             : ms-vscode-remote
2022-03-25 10:14:31 AM - 	Version            : 0.21.0
2022-03-25 10:14:31 AM - 	Description        : An extension pack that lets you open any folder in a container, on a remote machine, or in WSL and take advantage of VS Code's full feature set.
2022-03-25 10:14:31 AM - 	Locale             : en-US
2022-03-25 10:14:31 AM - 	MoreInfoURL        : 
2022-03-25 10:14:31 AM - 	InstalledByMSI     : False
2022-03-25 10:14:31 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
2022-03-25 10:14:31 AM - 
2022-03-25 10:14:31 AM - 	SignatureState     : Unsigned
2022-03-25 10:14:31 AM - 	Supported Products : 
2022-03-25 10:14:31 AM - 		Microsoft.VisualStudio.Code
2022-03-25 10:14:31 AM - 			Version : 
2022-03-25 10:14:31 AM - 			ProductArchitecture : x86
2022-03-25 10:14:31 AM - 
2022-03-25 10:14:31 AM - 	References         : 
2022-03-25 10:14:31 AM - Signature Details...
2022-03-25 10:14:31 AM - 	Extension is not signed.
2022-03-25 10:14:31 AM - 
2022-03-25 10:14:31 AM - Searching for applicable products...
2022-03-25 10:14:31 AM - Found installed product - Global Location
2022-03-25 10:14:31 AM - Found installed product - Visual Studio Community 2022
2022-03-25 10:14:31 AM - VSIXInstaller.NoApplicableSKUsException: One or more extensions are for Visual Studio Code. Try installing them in Visual Studio Code.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

Steps to Reproduce:

1. Download Remote Development extension
2. Try to install with VSIX

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by tanhakabir** [comment]
Thanks @byamagata! Yes this looks like a Visual Studio issue and should be filed with the instructions you've linked: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022

**Comment by Ndimis** [comment]
Thaanks Guys I will move it to there!
