### ISSUE TITLE
Remote fails to connect after update

### ISSUE THREAD

**Issue by eugeneia** [microsoft/vscode-remote-release#6510]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0

- OS Version:
OS: Windows_NT x64 10.0.19043
Steps to Reproduce:

1. Start vscode
2. Open remote

Output:
```
[12:28:51.243] Log Level: 2
[12:28:51.244] remote-ssh@0.64.0
[12:28:51.245] win32 x64
[12:28:51.257] SSH Resolver called for "ssh-remote+...", attempt 1
[12:28:51.257] "remote.SSH.useLocalServer": false
[12:28:51.258] "remote.SSH.showLoginTerminal": false
[12:28:51.258] "remote.SSH.remotePlatform": {...}
[12:28:51.258] "remote.SSH.sshPath": undefined
[12:28:51.258] "remote.SSH.sshConfigurationFile": undefined
[12:28:51.258] "remote.SSH.useFlock": true
[12:28:51.258] "remote.SSH.lockfilesInTmp": false
[12:28:51.259] "remote.SSH.localServerDownload": auto
[12:28:51.259] "remote.SSH.remoteServerListenOnSocket": false
[12:28:51.259] "remote.SSH.showLoginTerminal": false
[12:28:51.259] "remote.SSH.defaultExtensions": []
[12:28:51.259] SSH Resolver called for host: ...
[12:28:51.259] Setting up SSH remote "..."
[12:28:51.265] Using commit id "c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1" and quality "stable" for server
[12:28:51.268] Install and start server if needed
[12:28:51.272] Checking ssh with "ssh -V"
[12:28:51.309] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
[12:28:51.309] > 

[12:28:51.314] Running script with connection command: ssh -T -D ... bash
[12:28:51.316] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[12:28:52.547] > ]0;C:\WINDOWS\System32\cmd.exe
[12:28:52.547] Got some output, clearing connection timeout
[12:28:52.927] > Enter passphrase for key 'C:\Users\max/.ssh/id_ed25519': 
[12:28:52.927] Detected passphrase message
[12:29:01.912] Got passphrase response
[12:29:01.913] "install" wrote data to terminal: "************"
[12:29:01.927] > 
[12:29:02.330] > c0917f7fc0f6: running
[12:29:02.351] > Acquiring lock on /home/max/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b
> 15e77d1/vscode-remote-lock.max.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
[12:29:02.366] > Found existing installation at /home/max/.vscode-server/bin/c722ca6c7eed3d7987c0
> d5c3df5c45f6b15e77d1...
> Checking /home/max/.vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.log 
> and /home/max/.vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.pid for a
>  running server
> Looking for server with pid: 397295
[12:29:02.374] > Starting server with command... /home/max/.vscode-server/bin/c722ca6c7eed3d7987c
> 0d5c3df5c45f6b15e77d1/server.sh --start-server --host=127.0.0.1 --enable-remote-
> auto-shutdown --disable-telemetry --port=0  &> "/home/max/.vscode-server/.c722ca
> 6c7eed3d7987c0d5c3df5c45f6b15e77d1.log" < /dev/null
> printenv:
>     SHELL=/usr/bin/bash
>     LANGUAGE=en_US:en
>     PWD=/home/max
>     LOGNAME=max
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/home/max
>     LANG=en_US.UTF-8
>     VSCODE_AGENT_FOLDER=/home/max/.vscode-server
>     SSH_CONNECTION=...
>     XDG_SESSION_CLASS=user
>     USER=max
>     SHLVL=0
>     XDG_SESSION_ID=370
>     XDG_RUNTIME_DIR=/run/user/1007
>     SSH_CLIENT=...
>     PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
>     _=/usr/bin/printenv
[12:29:02.382] > 
[12:29:02.486] > Spawned remote server: 398738
> Waiting for server log...
[12:29:02.510] > 
[12:29:02.521] > Waiting for server log...
[12:29:02.556] > Waiting for server log...
[12:29:02.587] > Waiting for server log...
[12:29:02.597] > 
[12:29:02.620] > Waiting for server log...
[12:29:02.653] > Waiting for server log...
[12:29:02.687] > Waiting for server log...
[12:29:02.693] > 
[12:29:02.718] > Waiting for server log...
[12:29:02.752] > Waiting for server log...
[12:29:02.787] > Waiting for server log...
[12:29:02.819] > Waiting for server log...
[12:29:02.852] > Waiting for server log...
[12:29:02.885] > Waiting for server log...
[12:29:02.920] > Waiting for server log...
[12:29:02.925] > 
[12:29:02.953] > Waiting for server log...
[12:29:02.985] > Waiting for server log...
[12:29:02.994] > 
[12:29:03.019] > Waiting for server log...
[12:29:03.054] > Waiting for server log...
[12:29:03.085] > Waiting for server log...
[12:29:03.094] > 
[12:29:03.119] > Waiting for server log...
[12:29:03.153] > Waiting for server log...
[12:29:03.186] > Waiting for server log...
[12:29:03.219] > Waiting for server log...
[12:29:03.253] > Waiting for server log...
[12:29:03.261] > 
[12:29:03.285] > Waiting for server log...
[12:29:03.319] > Waiting for server log...
[12:29:03.353] > Waiting for server log...
[12:29:03.363] > 
[12:29:03.386] > Waiting for server log...
[12:29:03.419] > Waiting for server log...
[12:29:03.453] > Waiting for server log...
[12:29:03.478] > 
[12:29:03.487] > Waiting for server log...
[12:29:03.492] > 
[12:29:03.520] > Waiting for server log...
[12:29:03.553] > Waiting for server log...
[12:29:03.563] > 
[12:29:03.586] > Waiting for server log...
[12:29:03.621] > Waiting for server log...
[12:29:03.653] > Waiting for server log...
[12:29:03.686] > Waiting for server log...
[12:29:03.720] > Waiting for server log...
[12:29:03.728] > 
[12:29:03.753] > Waiting for server log...
[12:29:03.788] > Waiting for server log...
[12:29:03.819] > Waiting for server log...
[12:29:03.829] > 
[12:29:03.853] > Waiting for server log...
[12:29:03.887] > Waiting for server log...
[12:29:03.919] > Waiting for server log...
[12:29:03.952] > Waiting for server log...
[12:29:03.960] > 
[12:29:03.987] > Waiting for server log...
[12:29:04.021] > Waiting for server log...
[12:29:04.053] > Waiting for server log...
[12:29:04.087] > Waiting for server log...
[12:29:04.093] > 
[12:29:04.119] > Waiting for server log...
[12:29:04.154] > Waiting for server log...
[12:29:04.160] > 
[12:29:04.187] > Waiting for server log...
[12:29:04.221] > Waiting for server log...
[12:29:04.244] > 
[12:29:04.252] > Waiting for server log...
[12:29:04.260] > 
[12:29:04.287] > Waiting for server log...
[12:29:04.319] > Waiting for server log...
[12:29:04.328] > 
[12:29:04.353] > Waiting for server log...
[12:29:04.386] > Waiting for server log...
[12:29:04.419] > Waiting for server log...
[12:29:04.426] > 
[12:29:04.454] > Waiting for server log...
[12:29:04.487] > Waiting for server log...
[12:29:04.512] > 
[12:29:04.519] > Waiting for server log...
[12:29:04.528] > 
[12:29:04.554] > Waiting for server log...
[12:29:04.588] > Waiting for server log...
[12:29:04.598] > 
[12:29:04.620] > Waiting for server log...
[12:29:04.653] > Waiting for server log...
[12:29:04.686] > Waiting for server log...
[12:29:04.712] > 
[12:29:04.720] > Waiting for server log...
[12:29:04.726] > 
[12:29:04.754] > Waiting for server log...
[12:29:04.788] > Waiting for server log...
[12:29:04.797] > 
[12:29:04.821] > Waiting for server log...
[12:29:04.855] > Waiting for server log...
[12:29:04.888] > Waiting for server log...
[12:29:04.898] > 
[12:29:04.921] > Waiting for server log...
[12:29:04.954] > Waiting for server log...
[12:29:04.988] > Waiting for server log...
[12:29:04.996] > 
[12:29:05.023] > Waiting for server log...
[12:29:05.055] > Waiting for server log...
[12:29:05.089] > Waiting for server log...
[12:29:05.121] > Waiting for server log...
[12:29:05.129] > 
[12:29:05.156] > Waiting for server log...
[12:29:05.188] > Waiting for server log...
[12:29:05.196] > 
[12:29:05.221] > Waiting for server log...
[12:29:05.254] > Waiting for server log...
[12:29:05.263] > 
[12:29:05.289] > Waiting for server log...
[12:29:05.322] > Waiting for server log...
[12:29:05.356] > Waiting for server log...
[12:29:05.388] > Waiting for server log...
[12:29:05.395] > 
[12:29:05.422] > Waiting for server log...
[12:29:05.456] > Waiting for server log...
[12:29:05.488] > Waiting for server log...
[12:29:05.521] > Waiting for server log...
[12:29:05.529] > 
[12:29:05.556] > Waiting for server log...
[12:29:05.588] > Waiting for server log...
[12:29:05.613] > 
[12:29:05.622] > Waiting for server log...
[12:29:05.628] > 
[12:29:05.654] > Waiting for server log...
[12:29:05.688] > Waiting for server log...
[12:29:05.721] > Waiting for server log...
[12:29:05.755] > Waiting for server log...
[12:29:05.761] > 
[12:29:05.789] > Waiting for server log...
[12:29:05.821] > Waiting for server log...
[12:29:05.830] > 
[12:29:05.854] > Waiting for server log...
[12:29:05.888] > Waiting for server log...
[12:29:05.921] > Waiting for server log...
[12:29:05.953] > Waiting for server log...
[12:29:05.961] > 
[12:29:05.989] > Waiting for server log...
[12:29:06.021] > Waiting for server log...
[12:29:06.030] > 
[12:29:06.055] > Waiting for server log...
[12:29:06.089] > Waiting for server log...
[12:29:06.120] > Waiting for server log...
[12:29:06.129] > 
[12:29:06.155] > Waiting for server log...
[12:29:06.189] > Waiting for server log...
[12:29:06.222] > Waiting for server log...
[12:29:06.256] > Waiting for server log...
[12:29:06.289] > Waiting for server log...
[12:29:06.296] > 
[12:29:06.323] > Waiting for server log...
[12:29:06.356] > Waiting for server log...
[12:29:06.389] > Waiting for server log...
[12:29:06.422] > Waiting for server log...
[12:29:06.446] > 
[12:29:06.453] > Waiting for server log...
[12:29:06.461] > 
[12:29:06.489] > Waiting for server log...
[12:29:06.521] > Waiting for server log...
[12:29:06.529] > 
[12:29:06.554] > Waiting for server log...
[12:29:06.588] > Waiting for server log...
[12:29:06.619] > Waiting for server log...
[12:29:06.653] > Waiting for server log...
[12:29:06.687] > Waiting for server log...
[12:29:06.720] > Waiting for server log...
[12:29:06.729] > 
[12:29:06.771] > Waiting for server log...
[12:29:06.787] > Waiting for server log...
[12:29:06.821] > Waiting for server log...
[12:29:06.831] > 
[12:29:06.854] > Waiting for server log...
[12:29:06.888] > Waiting for server log...
[12:29:06.922] > Waiting for server log...
[12:29:06.929] > 
[12:29:06.956] > Waiting for server log...
[12:29:06.989] > Waiting for server log...
[12:29:07.013] > 
[12:29:07.021] > Waiting for server log...
[12:29:07.029] > 
[12:29:07.055] > Waiting for server log...
[12:29:07.088] > Waiting for server log...
[12:29:07.123] > Waiting for server log...
[12:29:07.156] > Waiting for server log...
[12:29:07.189] > Waiting for server log...
[12:29:07.221] > Waiting for server log...
[12:29:07.229] > 
[12:29:07.256] > Waiting for server log...
[12:29:07.288] > Waiting for server log...
[12:29:07.297] > 
[12:29:07.322] > Waiting for server log...
[12:29:07.356] > Waiting for server log...
[12:29:07.388] > Waiting for server log...
[12:29:07.396] > 
[12:29:07.421] > Waiting for server log...
[12:29:07.454] > Waiting for server log...
[12:29:07.488] > Waiting for server log...
[12:29:07.522] > Waiting for server log...
[12:29:07.554] > Waiting for server log...
[12:29:07.563] > 
[12:29:07.590] > Waiting for server log...
[12:29:07.621] > Waiting for server log...
[12:29:07.630] > 
[12:29:07.657] > Waiting for server log...
[12:29:07.689] > Waiting for server log...
[12:29:07.697] > 
[12:29:07.722] > Waiting for server log...
[12:29:07.756] > Waiting for server log...
[12:29:07.788] > Waiting for server log...
[12:29:07.796] > 
[12:29:07.822] > Waiting for server log...
[12:29:07.856] > Waiting for server log...
[12:29:07.888] > Waiting for server log...
[12:29:07.896] > 
[12:29:07.921] > Waiting for server log...
[12:29:07.954] > Waiting for server log...
[12:29:07.987] > Waiting for server log...
[12:29:07.995] > 
[12:29:08.022] > Waiting for server log...
[12:29:08.054] > Waiting for server log...
[12:29:08.062] > 
[12:29:08.090] > Waiting for server log...
[12:29:08.122] > Waiting for server log...
[12:29:08.147] > 
[12:29:08.156] > Waiting for server log...
[12:29:08.162] > 
[12:29:08.189] > Waiting for server log...
[12:29:08.221] > Waiting for server log...
[12:29:08.255] > Waiting for server log...
[12:29:08.290] > Waiting for server log...
[12:29:08.322] > Waiting for server log...
[12:29:08.355] > Waiting for server log...
[12:29:08.363] > 
[12:29:08.389] > Waiting for server log...
[12:29:08.423] > Waiting for server log...
[12:29:08.455] > Waiting for server log...
[12:29:08.462] > 
[12:29:08.489] > Waiting for server log...
[12:29:08.524] > Waiting for server log...
[12:29:08.533] > 
[12:29:08.556] > Waiting for server log...
[12:29:08.590] > Waiting for server log...
[12:29:08.623] > Waiting for server log...
[12:29:08.656] > Waiting for server log...
[12:29:08.688] > Waiting for server log...
[12:29:08.696] > 
[12:29:08.724] > Waiting for server log...
[12:29:08.757] > Waiting for server log...
[12:29:08.767] > 
[12:29:08.788] > Waiting for server log...
[12:29:08.823] > Waiting for server log...
[12:29:08.857] > Waiting for server log...
[12:29:08.866] > 
[12:29:08.888] > Waiting for server log...
[12:29:08.923] > Waiting for server log...
[12:29:08.955] > Waiting for server log...
[12:29:08.962] > 
[12:29:08.990] > Waiting for server log...
[12:29:09.022] > Waiting for server log...
[12:29:09.031] > 
[12:29:09.055] > Waiting for server log...
[12:29:09.091] > Waiting for server log...
[12:29:09.124] > Waiting for server log...
[12:29:09.133] > 
[12:29:09.156] > Waiting for server log...
[12:29:09.191] > Waiting for server log...
[12:29:09.223] > Waiting for server log...
[12:29:09.256] > Waiting for server log...
[12:29:09.264] > 
[12:29:09.289] > Waiting for server log...
[12:29:09.324] > Waiting for server log...
[12:29:09.334] > 
[12:29:09.356] > Waiting for server log...
[12:29:09.391] > Waiting for server log...
[12:29:09.399] > 
[12:29:09.422] > Waiting for server log...
[12:29:09.458] > Waiting for server log...
[12:29:09.491] > Waiting for server log...
[12:29:09.522] > Waiting for server log...
[12:29:09.530] > 
[12:29:09.558] > Waiting for server log...
[12:29:09.591] > Waiting for server log...
[12:29:09.600] > 
[12:29:09.623] > Waiting for server log...
[12:29:09.657] > Waiting for server log...
[12:29:09.691] > Waiting for server log...
[12:29:09.724] > Waiting for server log...
[12:29:09.731] > 
[12:29:09.758] > Waiting for server log...
[12:29:09.791] > Waiting for server log...
[12:29:09.822] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,  
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
> Server did not start successfully. Full server log at /home/max/.vscode-server/.
> c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.log >>>
> server.sh is being replaced by 'bin/code-server'. Please migrate to the new comm
[12:29:09.830] > 
> and and adopt the following new default behaviors:
> * connection token is mandatory unless --without-connection-token is used       
> * host defaults to `localhost`
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-lice
> nse) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacyst
> atement).
> *
> To accept the license terms, start the server with --accept-server-license-terms
> <<< End of server log
> c0917f7fc0f6: start
> exitCode==32==
> listeningOn====
> osReleaseId==debian==
> arch==x86_64==
> tmpDir==/run/user/1007==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==7449==
> c0917f7fc0f6: end
[12:29:09.830] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==debian==
arch==x86_64==
tmpDir==/run/user/1007==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==7449==

[12:29:09.836] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (c:\Users\max\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:64057)
	at c (c:\Users\max\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:58602)
	at Object.t.handleInstallOutput (c:\Users\max\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:62898)
	at k (c:\Users\max\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:313462)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\max\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:311339
	at async Object.t.withShowDetailsEvent (c:\Users\max\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:406337)
	at async Object.t.resolve (c:\Users\max\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:1:315001)
	at async c:\Users\max\.vscode\extensions\ms-vscode-remote.remote-ssh-0.64.0\out\extension.js:127:110431
[12:29:09.840] ------




[12:29:10.237] > 
[12:29:11.109] "install" terminal command done
[12:29:11.109] User entered passphrase
[12:29:11.111] Passphrase was entered and ssh config entry was found - adding SSH key to agent
[12:29:11.112] Executing add-ssh-key:
powershell -ExecutionPolicy Bypass C:\Users\max\AppData\Local\Temp\vscode_add_ssh_key_to_agent.ps1
[12:29:11.113] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[12:29:11.113] "add-ssh-key" wrote data to terminal: "powershell -ExecutionPolicy Bypass C:\Users\max\AppData\Local\Temp\vscode_add_ssh_key_to_agent.ps1"
[12:29:11.481] > Microsoft Windows [Version 10.0.19043.1526]]0;C:\WINDOWS\System32\cmd.exe
[12:29:11.490] > 
> (c) Microsoft Corporation. All rights reserved.
> 
> C:\Users\max>(powershell -ExecutionPolicy Bypass C:\Users\max\AppData\Local\Temp
> \vscode_add_ssh_key_to_agent.ps1) & exit /b 0
> ]0;C:\WINDOWS\System32\cmd.exe - powershell  -ExecutionPolicy Bypass C:\Users\max\AppData\Local\Temp\vscode_add_ssh_key_to_agent.ps1
[12:29:11.700] > PS: adding key to ssh-agent
[12:29:11.728] > 
> ssh-add
> 
> Error connecting to agent: No such file or directory
> f0b07fef2120##5##
[12:29:11.728] ssh-add failed
[12:29:11.728] Consider setting up the ssh agent: https://aka.ms/vscode-remote/troubleshooting#_setting-up-the-ssh-agent
[12:29:11.742] > ]0;C:\WINDOWS\System32\cmd.exe
[12:29:11.742] ssh-add failed
[12:29:11.742] Consider setting up the ssh agent: https://aka.ms/vscode-remote/troubleshooting#_setting-up-the-ssh-agent
[12:29:13.016] "add-ssh-key" terminal command done
[12:29:13.016] Install terminal quit with output:
```

**Comment by roblourens** [comment]
That's an old version of the extension which isn't compatible with the latest vscode, please update the extension

**Comment by eugeneia** [comment]
Which extension? Or, how do yoi/I tell?

**Comment by roblourens** [comment]
The Remote-SSH extension
