### ISSUE TITLE
No longer able to remote SSH to Mac M1 on macOS Monterey.

### ISSUE THREAD

**Issue by codeclinic** [microsoft/vscode-remote-release#6518]
- VSCode Version: 1.65.2
- Local OS Version: Win 10
- Remote OS Version: MacOS Monterey
- Remote Extension/Connection Type: SSH
- Logs:
```
[20:32:59.157] Log Level: 2
[20:32:59.158] remote-ssh@0.76.1
[20:32:59.159] win32 x64
[20:32:59.160] SSH Resolver called for "ssh-remote+10.147.17.36", attempt 1
[20:32:59.161] "remote.SSH.useLocalServer": false
[20:32:59.161] "remote.SSH.showLoginTerminal": false
[20:32:59.162] "remote.SSH.remotePlatform": {"10.147.17.36":"macOS","MacServer-Zerotier":"macOS","MacServer-Local":"macOS"}
[20:32:59.162] "remote.SSH.path": undefined
[20:32:59.162] "remote.SSH.configFile": undefined
[20:32:59.162] "remote.SSH.useFlock": true
[20:32:59.162] "remote.SSH.lockfilesInTmp": false
[20:32:59.162] "remote.SSH.localServerDownload": auto
[20:32:59.163] "remote.SSH.remoteServerListenOnSocket": false
[20:32:59.163] "remote.SSH.showLoginTerminal": false
[20:32:59.163] "remote.SSH.defaultExtensions": []
[20:32:59.163] "remote.SSH.loglevel": 2
[20:32:59.163] "remote.SSH.enableDynamicForwarding": true
[20:32:59.163] "remote.SSH.enableRemoteCommand": false
[20:32:59.164] "remote.SSH.serverPickPortsFromRange": {}
[20:32:59.164] "remote.SSH.serverInstallPath": {}
[20:32:59.167] SSH Resolver called for host: 10.147.17.36
[20:32:59.168] Setting up SSH remote "10.147.17.36"
[20:32:59.174] Using commit id "c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1" and quality "stable" for server
[20:32:59.179] Install and start server if needed
[20:32:59.182] Checking ssh with "ssh -V"
[20:32:59.248] > O
[20:32:59.249] > penSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[20:32:59.254] Running script with connection command: ssh -T -D 62354 "10.147.17.36" bash
[20:32:59.256] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[20:32:59.626] > ]0;C:\WINDOWS\System32\cmd.exe
[20:32:59.627] Got some output, clearing connection timeout
[20:33:00.258] > Password:
[20:33:00.259] Showing password prompt
[20:33:10.228] Got password response
[20:33:10.228] "install" wrote data to terminal: "**************"
[20:33:10.254] > 
[20:33:10.839] > 29aee9103fcc: running
[20:33:10.875] > Acquiring lock on /Users/phill/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45
> f6b15e77d1/vscode-remote-lock.phill.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1    
[20:33:10.899] > \ln /Users/phill/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/vsc
> ode-remote-lock.phill.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.target /Users/phi
> ll/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/vscode-remote-loc
> k.phill.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
> Found existing installation at /Users/phill/.vscode-server/bin/c722ca6c7eed3d798
> 7c0d5c3df5c45f6b15e77d1...
> Checking /Users/phill/.vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.l
> og and /Users/phill/.vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.pid
>  for a running server
> Looking for server with pid: 12237
[20:33:10.928] > Starting server with command... /Users/phill/.vscode-server/bin/c722ca6c7eed3d79
> 87c0d5c3df5c45f6b15e77d1/bin/code-server --start-server --host=127.0.0.1 --accep
> t-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level 
> off   &> "/Users/phill/.vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.
> log" < /dev/null
> printenv:
>     SHELL=/bin/zsh
>     TMPDIR=/var/folders/rp/7bdz9lgj1bgbp1w95l3p12xc0000gp/T/
>     SSH_CLIENT=10.147.17.71 62357 22
>     USER=phill
>     VSCODE_AGENT_FOLDER=/Users/phill/.vscode-server
>     PATH=/usr/bin:/bin:/usr/sbin:/sbin
>     PWD=/Users/phill
>     SHLVL=1
>     HOME=/Users/phill
>     LOGNAME=phill
>     SSH_CONNECTION=10.147.17.71 62357 10.147.17.36 22
>     _=/usr/bin/printenv
> Removing old logfile at /Users/phill/.vscode-server/.c722ca6c7eed3d7987c0d5c3df5
[20:33:10.930] > 
> c45f6b15e77d1.log
> Spawned remote server: 13210
> Waiting for server log...
[20:33:10.939] > 
[20:33:10.974] > Waiting for server log...
[20:33:11.012] > Waiting for server log...
[20:33:11.066] > Waiting for server log...
[20:33:11.116] > Waiting for server log...
[20:33:11.161] > Waiting for server log...
[20:33:11.209] > Waiting for server log...
[20:33:11.267] > Waiting for server log...
[20:33:11.314] > Waiting for server log...
[20:33:11.370] > Waiting for server log...
[20:33:11.412] > Waiting for server log...
[20:33:11.465] > Waiting for server log...
[20:33:11.515] > Waiting for server log...
[20:33:11.571] > Waiting for server log...
[20:33:11.626] > Waiting for server log...
[20:33:11.675] > Waiting for server log...
[20:33:11.726] > Waiting for server log...
[20:33:11.775] > Waiting for server log...
[20:33:11.829] > Waiting for server log...
[20:33:11.881] > Waiting for server log...
[20:33:11.928] > Waiting for server log...
[20:33:11.977] > Waiting for server log...
[20:33:12.043] > Waiting for server log...
[20:33:12.078] > Waiting for server log...
[20:33:12.128] > Waiting for server log...
[20:33:12.178] > Waiting for server log...
[20:33:12.232] > Waiting for server log...
[20:33:12.279] > Waiting for server log...
[20:33:12.328] > Waiting for server log...
[20:33:12.382] > Waiting for server log...
[20:33:12.436] > Waiting for server log...
[20:33:12.478] > Waiting for server log...
[20:33:12.532] > Waiting for server log...
[20:33:12.584] > Waiting for server log...
[20:33:12.641] > Waiting for server log...
[20:33:12.688] > Waiting for server log...
[20:33:12.728] > Waiting for server log...
[20:33:12.778] > Waiting for server log...
[20:33:12.832] > Waiting for server log...
[20:33:12.878] > Waiting for server log...
[20:33:12.928] > Waiting for server log...
[20:33:12.983] > Waiting for server log...
[20:33:13.025] > Waiting for server log...
[20:33:13.078] > Waiting for server log...
[20:33:13.125] > Waiting for server log...
[20:33:13.178] > Waiting for server log...
[20:33:13.231] > Waiting for server log...
[20:33:13.279] > Waiting for server log...
[20:33:13.328] > Waiting for server log...
[20:33:13.375] > Waiting for server log...
[20:33:13.428] > Waiting for server log...
[20:33:13.486] > Waiting for server log...
[20:33:13.530] > Waiting for server log...
[20:33:13.588] > Waiting for server log...
[20:33:13.633] > Waiting for server log...
[20:33:13.691] > Waiting for server log...
[20:33:13.742] > Waiting for server log...
[20:33:13.827] > Waiting for server log...
[20:33:13.847] > Waiting for server log...
[20:33:13.907] > Waiting for server log...
[20:33:13.944] > Waiting for server log...
[20:33:13.989] > Waiting for server log...
[20:33:14.043] > Waiting for server log...
[20:33:14.094] > Waiting for server log...
[20:33:14.146] > Waiting for server log...
[20:33:14.195] > Waiting for server log...
[20:33:14.273] > Waiting for server log...
[20:33:14.296] > Waiting for server log...
[20:33:14.348] > Waiting for server log...
[20:33:14.399] > Waiting for server log...
[20:33:14.488] > Waiting for server log...
> Waiting for server log...
[20:33:14.497] > 
[20:33:14.545] > Waiting for server log...
[20:33:14.598] > Waiting for server log...
[20:33:14.644] > Waiting for server log...
[20:33:14.699] > Waiting for server log...
[20:33:14.751] > Waiting for server log...
[20:33:14.798] > Waiting for server log...
[20:33:14.847] > Waiting for server log...
[20:33:14.895] > Waiting for server log...
[20:33:14.943] > Waiting for server log...
[20:33:14.986] > Waiting for server log...
[20:33:15.038] > Waiting for server log...
[20:33:15.087] > Waiting for server log...
[20:33:15.139] > Waiting for server log...
[20:33:15.193] > Waiting for server log...
[20:33:15.241] > Waiting for server log...
[20:33:15.292] > Waiting for server log...
[20:33:15.353] > Waiting for server log...
[20:33:15.397] > Waiting for server log...
[20:33:15.448] > Waiting for server log...
[20:33:15.506] > Waiting for server log...
[20:33:15.547] > Waiting for server log...
[20:33:15.701] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[20:33:15.705] > 
[20:33:15.743] > Waiting for server log...
[20:33:15.793] > Waiting for server log...
[20:33:15.841] > Waiting for server log...
[20:33:15.895] > Waiting for server log...
[20:33:15.949] > Waiting for server log...
[20:33:15.995] > Waiting for server log...
[20:33:16.041] > Waiting for server log...
[20:33:16.095] > Waiting for server log...
[20:33:16.142] > Waiting for server log...
[20:33:16.195] > Waiting for server log...
[20:33:16.245] > Waiting for server log...
[20:33:16.297] > Waiting for server log...
[20:33:16.347] > Waiting for server log...
[20:33:16.400] > Waiting for server log...
[20:33:16.441] > Waiting for server log...
[20:33:16.507] > Waiting for server log...
[20:33:16.552] > Waiting for server log...
[20:33:16.599] > Waiting for server log...
[20:33:16.645] > Waiting for server log...
[20:33:16.702] > Waiting for server log...
[20:33:16.749] > Waiting for server log...
[20:33:16.806] > Waiting for server log...
[20:33:16.846] > Waiting for server log...
[20:33:16.898] > Waiting for server log...
[20:33:16.960] > Waiting for server log...
[20:33:16.995] > Waiting for server log...
[20:33:17.047] > Waiting for server log...
[20:33:17.098] > Waiting for server log...
[20:33:17.253] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[20:33:17.293] > Waiting for server log...
[20:33:17.348] > Waiting for server log...
[20:33:17.397] > Waiting for server log...
[20:33:17.445] > Waiting for server log...
[20:33:17.499] > Waiting for server log...
[20:33:17.549] > Waiting for server log...
[20:33:17.595] > Waiting for server log...
[20:33:17.648] > Waiting for server log...
[20:33:17.694] > Waiting for server log...
[20:33:17.747] > Waiting for server log...
[20:33:17.794] > Waiting for server log...
[20:33:17.844] > Waiting for server log...
[20:33:17.895] > Waiting for server log...
[20:33:17.942] > Waiting for server log...
[20:33:17.999] > Waiting for server log...
[20:33:18.048] > Waiting for server log...
[20:33:18.099] > Waiting for server log...
[20:33:18.142] > Waiting for server log...
[20:33:18.198] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
[20:33:18.206] > 
> *
> 
[20:33:18.216] > Server did not start successfully. Full server log at /Users/phill/.vscode-serve
> r/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.log >>>
> /Users/phill/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/bin/cod
> e-server: line 10: python: command not found
> usage: dirname string [...]
> usage: dirname string [...]
> /Users/phill/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/bin/cod
> e-server: line 13: /node: No such file or directory
> <<< End of server log
> 29aee9103fcc: start
> exitCode==32==
> listeningOn====
> osReleaseId==Darwin==
> arch==arm64==
[20:33:18.228] > 
> tmpDir==/tmp==
> platform==macOS==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==8000==
> 29aee9103fcc: end
[20:33:18.229] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==Darwin==
arch==arm64==
tmpDir==/tmp==
platform==macOS==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==8000==

[20:33:18.235] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (c:\Users\phill\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:585975)
	at p (c:\Users\phill\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:579824)
	at Object.t.handleInstallOutput (c:\Users\phill\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:583109)
	at Object.t.tryInstall (c:\Users\phill\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:681846)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\phill\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:644486
	at async Object.t.withShowDetailsEvent (c:\Users\phill\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:647831)
	at async Object.t.resolve (c:\Users\phill\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:645565)
	at async c:\Users\phill\.vscode\extensions\ms-vscode-remote.remote-ssh-0.76.1\out\extension.js:1:722872
[20:33:18.240] ------




[20:33:19.526] "install" terminal command done
[20:33:19.527] Install terminal quit with output: 
```

Steps to Reproduce:

1. Update macOS to Monterey
2. Try to connect to Mac Mini M1 macOS vscode from win10 vscode

Does this issue occur when you try this locally?: Yes

I've been remotely working on a project from my win10 machine to a mac mini m1 device. This has worked fine for approximately 12 months. Yesterday I update the mac to the latest macOS (monterey) and now I am unable to connect to he remote ma via ssh. I've uninstalled and re-installed vscode on both my local win 10 machine and on the mac itself without any improvement.

**Comment by tanhakabir** [comment]
Could you try using VS Code Insiders and the pre-release version of the extension?

**Comment by linh1987** [comment]
I have the same issue and can confirm that using VS Code Insiders (not VS Code Stable) and pre-release version of remote SSH works for me.

**Comment by codeclinic** [comment]
@tanhakabir Yes! That works perfectly and seems to actually establish a connection much quicker than it did previously. Thanks.

**Comment by tanhakabir** [comment]
This version of Insiders and the pre-release of the extension will be out later this week onto stable in the 1.66 update!
