### ISSUE TITLE
Hi there  The server can't start, with the below error.  I have tried to kill server on host & retry it, but it still doesn't work.  Has someone solved the problem?

### ISSUE THREAD

**Issue by dengwanxia1991** [microsoft/vscode-remote-release#6520]
[09:32:27.420] Log Level: 2
[09:32:27.424] remote-ssh@0.66.0
[09:32:27.424] win32 x64
[09:32:27.425] SSH Resolver called for "ssh-remote+111.8.63.186", attempt 1
[09:32:27.425] "remote.SSH.useLocalServer": false
[09:32:27.426] "remote.SSH.showLoginTerminal": false
[09:32:27.426] "remote.SSH.remotePlatform": {"ali":"linux","amax":"linux","micro":"linux","218.77.58.46":"linux","111.8.63.186":"linux"}
[09:32:27.426] "remote.SSH.path": undefined
[09:32:27.426] "remote.SSH.configFile": undefined
[09:32:27.426] "remote.SSH.useFlock": true
[09:32:27.427] "remote.SSH.lockfilesInTmp": false
[09:32:27.427] "remote.SSH.localServerDownload": auto
[09:32:27.427] "remote.SSH.remoteServerListenOnSocket": false
[09:32:27.427] "remote.SSH.showLoginTerminal": false
[09:32:27.427] "remote.SSH.defaultExtensions": []
[09:32:27.428] "remote.SSH.loglevel": 2
[09:32:27.428] SSH Resolver called for host: 111.8.63.186
[09:32:27.428] Setting up SSH remote "111.8.63.186"
[09:32:27.493] Using commit id "c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1" and quality "stable" for server
[09:32:27.497] Install and start server if needed
[09:32:27.539] Checking ssh with "ssh -V"
[09:32:27.611] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[09:32:27.618] Running script with connection command: ssh -T -D 64191 "111.8.63.186" bash
[09:32:27.621] Terminal shell path: C:\windows\System32\cmd.exe
[09:32:27.928] > ]0;C:\windows\System32\cmd.exe
[09:32:27.929] Got some output, clearing connection timeout
[09:32:29.624] > 96a32c36e604: running
[09:32:29.672] > Acquiring lock on /root/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3df5c45f6b15e7
> 7d1/vscode-remote-lock.root.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
[09:32:29.691] > Found existing installation at /root/.vscode-server/bin/c722ca6c7eed3d7987c0d5c3
> df5c45f6b15e77d1...
> Checking /root/.vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.log and 
> /root/.vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.pid for a running
>  server
> Looking for server with pid: 14872
[09:32:29.750] > Starting server with command... /root/.vscode-server/bin/c722ca6c7eed3d7987c0d5c
> 3df5c45f6b15e77d1/server.sh --start-server --host=127.0.0.1 --enable-remote-auto
> -shutdown  --port=0  &> "/root/.vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b
> 15e77d1.log" < /dev/null
> printenv:
>     SSH_CONNECTION=116.162.134.13 24887 192.168.251.66 22
>     LANG=C.UTF-8
>     XDG_SESSION_ID=229672
>     USER=root
>     PWD=/root
>     HOME=/root
>     SSH_CLIENT=116.162.134.13 24887 22
>     MAIL=/var/mail/root
>     SHELL=/bin/bash
>     SHLVL=2
>     VSCODE_AGENT_FOLDER=/root/.vscode-server
>     LOGNAME=root
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/0/bus
>     XDG_RUNTIME_DIR=/run/user/0
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
> :/usr/local/games
>     _=/usr/bin/printenv
> Spawned remote server: 16587
[09:32:29.758] > 
> Waiting for server log...
[09:32:29.770] > 
[09:32:29.793] > Waiting for server log...
[09:32:29.838] > Waiting for server log...
[09:32:29.868] > Waiting for server log...
[09:32:29.904] > Waiting for server log...
[09:32:29.939] > Waiting for server log...
[09:32:29.975] > Waiting for server log...
[09:32:30.010] > Waiting for server log...
[09:32:30.047] > Waiting for server log...
[09:32:30.084] > Waiting for server log...
[09:32:30.119] > Waiting for server log...
[09:32:30.155] > Waiting for server log...
[09:32:30.191] > Waiting for server log...
[09:32:30.229] > Waiting for server log...
[09:32:30.265] > Waiting for server log...
[09:32:30.302] > Waiting for server log...
[09:32:30.336] > Waiting for server log...
[09:32:30.374] > Waiting for server log...
[09:32:30.407] > Waiting for server log...
[09:32:30.445] > Waiting for server log...
[09:32:30.492] > Waiting for server log...
[09:32:30.519] > Waiting for server log...
[09:32:30.570] > 
> Waiting for server log...
[09:32:30.577] > 
[09:32:30.594] > Waiting for server log...
[09:32:30.634] > Waiting for server log...
[09:32:30.676] > Waiting for server log...
[09:32:30.718] > Waiting for server log...
[09:32:30.740] > Waiting for server log...
[09:32:30.777] > Waiting for server log...
[09:32:31.169] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[09:32:31.192] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[09:32:31.201] > 
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[09:32:31.219] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[09:32:31.221] > 
[09:32:31.247] > Waiting for server log...
[09:32:31.286] > Waiting for server log...
[09:32:31.319] > Waiting for server log...
[09:32:31.356] > Waiting for server log...
[09:32:31.394] > Waiting for server log...
[09:32:31.436] > Waiting for server log...
[09:32:31.487] > Waiting for server log...
[09:32:31.513] > Waiting for server log...
[09:32:31.544] > Waiting for server log...
[09:32:31.577] > Waiting for server log...
[09:32:31.627] > Waiting for server log...
[09:32:31.648] > Waiting for server log...
[09:32:31.687] > Waiting for server log...
[09:32:31.720] > Waiting for server log...
[09:32:31.762] > Waiting for server log...
[09:32:31.801] > Waiting for server log...
[09:32:31.955] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[09:32:32.013] > Waiting for server log...
[09:32:32.083] > Waiting for server log...
[09:32:32.261] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[09:32:32.329] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[09:32:32.377] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[09:32:32.378] > Waiting for server log...
[09:32:32.414] > Waiting for server log...
[09:32:32.448] > Waiting for server log...
[09:32:32.485] > Waiting for server log...
[09:32:32.518] > Waiting for server log...
[09:32:32.566] > Waiting for server log...
[09:32:32.606] > Waiting for server log...
[09:32:32.615] > 
[09:32:32.634] > Waiting for server log...
[09:32:32.686] > Waiting for server log...
[09:32:32.715] > Waiting for server log...
[09:32:32.738] > Waiting for server log...
[09:32:32.772] > Waiting for server log...
[09:32:32.813] > Waiting for server log...
[09:32:32.847] > Waiting for server log...
[09:32:32.885] > Waiting for server log...
[09:32:32.919] > Waiting for server log...
[09:32:32.954] > Waiting for server log...
[09:32:32.997] > Waiting for server log...
[09:32:33.144] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[09:32:33.160] > 
[09:32:33.170] > Waiting for server log...
[09:32:33.178] > 
[09:32:33.211] > Waiting for server log...
[09:32:33.246] > Waiting for server log...
[09:32:33.283] > Waiting for server log...
[09:32:33.316] > Waiting for server log...
[09:32:33.351] > Waiting for server log...
[09:32:33.395] > Waiting for server log...
[09:32:33.430] > Waiting for server log...
[09:32:33.460] > Waiting for server log...
[09:32:33.502] > Waiting for server log...
[09:32:33.535] > Waiting for server log...
[09:32:33.571] > Waiting for server log...
[09:32:33.620] > Waiting for server log...
[09:32:33.646] > Waiting for server log...
[09:32:33.694] > Waiting for server log...
[09:32:33.717] > Waiting for server log...
[09:32:33.730] > 
[09:32:33.752] > Waiting for server log...
[09:32:33.794] > Waiting for server log...
[09:32:33.828] > Waiting for server log...
[09:32:33.863] > Waiting for server log...
[09:32:33.902] > Waiting for server log...
[09:32:33.945] > Waiting for server log...
[09:32:33.969] > Waiting for server log...
[09:32:33.979] > 
[09:32:34.016] > Waiting for server log...
[09:32:34.049] > Waiting for server log...
[09:32:34.099] > Waiting for server log...
[09:32:34.119] > Waiting for server log...
[09:32:34.167] > Waiting for server log...
[09:32:34.199] > Waiting for server log...
[09:32:34.230] > Waiting for server log...
[09:32:34.263] > Waiting for server log...
[09:32:34.301] > Waiting for server log...
[09:32:34.335] > Waiting for server log...
[09:32:34.370] > Waiting for server log...
[09:32:34.412] > Waiting for server log...
[09:32:34.447] > Waiting for server log...
[09:32:34.485] > Waiting for server log...
[09:32:34.516] > Waiting for server log...
[09:32:34.553] > Waiting for server log...
[09:32:34.594] > Waiting for server log...
[09:32:34.629] > Waiting for server log...
[09:32:34.663] > Waiting for server log...
[09:32:34.701] > Waiting for server log...
[09:32:34.736] > Waiting for server log...
[09:32:34.769] > Waiting for server log...
[09:32:34.812] > Waiting for server log...
[09:32:34.846] > Waiting for server log...
[09:32:34.882] > Waiting for server log...
[09:32:34.916] > Waiting for server log...
[09:32:34.967] > Waiting for server log...
[09:32:34.994] > Waiting for server log...
[09:32:34.998] > 
[09:32:35.026] > Waiting for server log...
[09:32:35.062] > Waiting for server log...
[09:32:35.101] > Waiting for server log...
[09:32:35.135] > Waiting for server log...
[09:32:35.169] > Waiting for server log...
[09:32:35.211] > Waiting for server log...
[09:32:35.246] > Waiting for server log...
[09:32:35.278] > Waiting for server log...
[09:32:35.316] > Waiting for server log...
[09:32:35.352] > Waiting for server log...
[09:32:35.394] > Waiting for server log...
[09:32:35.430] > Waiting for server log...
[09:32:35.464] > Waiting for server log...
[09:32:35.508] > Waiting for server log...
[09:32:35.537] > Waiting for server log...
[09:32:35.579] > Waiting for server log...
[09:32:35.618] > Waiting for server log...
[09:32:35.652] > Waiting for server log...
[09:32:35.693] > Waiting for server log...
[09:32:35.736] > Waiting for server log...
[09:32:35.754] > Waiting for server log...
[09:32:35.795] > Waiting for server log...
[09:32:35.829] > Waiting for server log...
[09:32:35.861] > Waiting for server log...
[09:32:35.899] > Waiting for server log...
[09:32:35.934] > Waiting for server log...
[09:32:35.970] > Waiting for server log...
[09:32:36.003] > Waiting for server log...
[09:32:36.043] > Waiting for server log...
[09:32:36.082] > Waiting for server log...
[09:32:36.116] > Waiting for server log...
[09:32:36.150] > Waiting for server log...
[09:32:36.186] > Waiting for server log...
[09:32:36.227] > Waiting for server log...
[09:32:36.262] > Waiting for server log...
[09:32:36.295] > Waiting for server log...
[09:32:36.344] > Waiting for server log...
[09:32:36.368] > Waiting for server log...
[09:32:36.383] > 
[09:32:36.412] > Waiting for server log...
[09:32:36.444] > Waiting for server log...
[09:32:36.477] > Waiting for server log...
[09:32:36.515] > Waiting for server log...
[09:32:36.550] > Waiting for server log...
[09:32:36.586] > Waiting for server log...
[09:32:36.642] > Waiting for server log...
[09:32:36.661] > Waiting for server log...
[09:32:36.702] > Waiting for server log...
[09:32:36.736] > Waiting for server log...
[09:32:36.770] > Waiting for server log...
[09:32:36.809] > Waiting for server log...
[09:32:36.844] > Waiting for server log...
[09:32:36.887] > Waiting for server log...
[09:32:36.918] > Waiting for server log...
[09:32:36.952] > Waiting for server log...
[09:32:36.987] > Waiting for server log...
[09:32:37.030] > Waiting for server log...
[09:32:37.061] > Waiting for server log...
[09:32:37.105] > Waiting for server log...
[09:32:37.144] > Waiting for server log...
[09:32:37.183] > Waiting for server log...
[09:32:37.204] > Waiting for server log...
[09:32:37.222] > 
[09:32:37.246] > Waiting for server log...
[09:32:37.295] > Waiting for server log...
[09:32:37.319] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Server did not start successfully. Full server log at /root/.vscode-server/.c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1.log >>>   
[09:32:37.352] > 
> server.sh is being replaced by 'bin/code-server'. Please migrate to the new command and adopt the following new default behavio
> rs:
> * connection token is mandatory unless --without-connection-token is used
> * host defaults to `localhost`
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
> To accept the license terms, start the server with --accept-server-license-terms
> <<< End of server log
> 96a32c36e604: start
> exitCode==32==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/0==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==7568==
> 96a32c36e604: end
[09:32:37.353] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/0==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==7568==

[09:32:37.355] Resolver error: Error: The VS Code Server failed to start
	at Function.ServerInstallError (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:429127)
	at u (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:423450)
	at Object.t.handleInstallOutput (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:427869)
	at Object.t.tryInstall (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:521609)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:485262
	at async Object.t.withShowDetailsEvent (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:488612)
	at async Object.t.resolve (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:486341)
	at async c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-ssh-0.66.0\out\extension.js:1:559963
[09:32:37.362] ------

[09:32:38.722] "install" terminal command done
[09:32:38.723] Install terminal quit with output:

**Comment by dengwanxia1991** [comment]
The network proxy server has a problem. When I closed the proxy, the problem has been solved.
