### ISSUE TITLE
Unable to connect to Windows remote with Remote SSH

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-remote-release#6521]
I tested this by SSHing into localhost. This is my usual setup for sanity testing the Windows bits during endgame.

1. Setup SSH on your Windows machine
2. Install the Remote SSH extension (pre-release or stable, both repro the issue)
3. Use VS Code Remote SSH to connect to 127.0.0.1.
The following error occurs:

```
[14:01:54.282] Got password response
[14:01:54.282] Interactor gave response: 
[14:01:54.283] Cleaning up other-window auth server
[14:01:54.833] stderr> Authenticated to 127.0.0.1 ([127.0.0.1]:22).
[14:01:56.077] stderr> client_loop: send disconnect: Connection reset by peer
[14:01:56.084] > local-server-1> ssh child died, shutting down
[14:01:56.101] Local server exit: 0
[14:01:56.102] Received install output: local-server-1> Spawned ssh, pid=24372
OpenSSH_8.4p1, OpenSSL 1.1.1j  16 Feb 2021
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:keza9iKXJMKG2cYH31QVztttLd8nf8g7ARQ67ParHPQ
Authenticated to 127.0.0.1 ([127.0.0.1]:22).
client_loop: send disconnect: Connection reset by peer
local-server-1> ssh child died, shutting down

[14:01:56.103] Failed to parse remote port from server output
[14:01:56.104] Resolver error: Error: 
	at Function.Create (c:\Users\alros\.vscode\extensions\ms-vscode-remote.remote-ssh-0.77.2022032915\out\extension.js:1:586041)
	at Object.t.handleInstallOutput (c:\Users\alros\.vscode\extensions\ms-vscode-remote.remote-ssh-0.77.2022032915\out\extension.js:1:584693)
	at Object.e [as tryInstallWithLocalServer] (c:\Users\alros\.vscode\extensions\ms-vscode-remote.remote-ssh-0.77.2022032915\out\extension.js:1:625125)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\alros\.vscode\extensions\ms-vscode-remote.remote-ssh-0.77.2022032915\out\extension.js:1:644162
	at async Object.t.withShowDetailsEvent (c:\Users\alros\.vscode\extensions\ms-vscode-remote.remote-ssh-0.77.2022032915\out\extension.js:1:647909)
	at async c:\Users\alros\.vscode\extensions\ms-vscode-remote.remote-ssh-0.77.2022032915\out\extension.js:1:623597
	at async b (c:\Users\alros\.vscode\extensions\ms-vscode-remote.remote-ssh-0.77.2022032915\out\extension.js:1:620103)
	at async Object.t.resolveWithLocalServer (c:\Users\alros\.vscode\extensions\ms-vscode-remote.remote-ssh-0.77.2022032915\out\extension.js:1:623212)
	at async Object.t.resolve (c:\Users\alros\.vscode\extensions\ms-vscode-remote.remote-ssh-0.77.2022032915\out\extension.js:1:645519)
	at async c:\Users\alros\.vscode\extensions\ms-vscode-remote.remote-ssh-0.77.2022032915\out\extension.js:1:722959
[14:01:56.109] ------
```

**Comment by alexr00** [comment]
Something seems to have broken in my setup as I also can't connect with several older versions of VS Code too. I can still use powershell to ssh into 127.0.0.1. System info:

OS: Windows_NT x64 10.0.22581

**Comment by alexr00** [comment]
I'm still hitting this.

**Comment by dbaeumer** [comment]
@alexr00 I had this yesterday as well and the reason was the Windows for some reason stopped my `sshd` service. Could this be true for you as well?

**Comment by alexr00** [comment]
I don't think so. I had just manually started it, and I confirmed that I could still ssh to the machine without VS Code.

**Comment by roblourens** [comment]
`client_loop: send disconnect: Connection reset by peer` this is an error from ssh, that's all the log says.

Can you share the rest of the log? So using ssh through a terminal works? Does something like `echo "echo hello" | ssh localhost` work?

**Comment by alexr00** [comment]
Whole log
```
[16:10:58.306] Log Level: 2
[16:10:58.309] remote-ssh@0.79.2022040715
[16:10:58.309] win32 x64
[16:10:58.394] SSH Resolver called for "ssh-remote+127.0.0.1", attempt 1
[16:10:58.395] "remote.SSH.useLocalServer": true
[16:10:58.395] "remote.SSH.path": undefined
[16:10:58.395] "remote.SSH.configFile": undefined
[16:10:58.396] "remote.SSH.useFlock": true
[16:10:58.396] "remote.SSH.lockfilesInTmp": false
[16:10:58.396] "remote.SSH.localServerDownload": auto
[16:10:58.396] "remote.SSH.remoteServerListenOnSocket": false
[16:10:58.396] "remote.SSH.showLoginTerminal": false
[16:10:58.396] "remote.SSH.defaultExtensions": []
[16:10:58.397] "remote.SSH.loglevel": 2
[16:10:58.397] "remote.SSH.enableDynamicForwarding": true
[16:10:58.397] "remote.SSH.enableRemoteCommand": false
[16:10:58.397] "remote.SSH.serverPickPortsFromRange": {}
[16:10:58.397] "remote.SSH.serverInstallPath": {}
[16:10:58.463] SSH Resolver called for host: 127.0.0.1
[16:10:58.464] Setting up SSH remote "127.0.0.1"
[16:10:58.468] Acquiring local install lock: C:\Users\alros\AppData\Local\Temp\vscode-remote-ssh-08a3d11e-install.lock
[16:10:58.494] Looking for existing server data file at c:\Users\alros\AppData\Roaming\Code - Insiders\User\globalStorage\ms-vscode-remote.remote-ssh\vscode-ssh-host-08a3d11e-6ea335e334b90a9aca753d558dec1d14741eff1e-0.79.2022040715\data.json
[16:10:58.495] Using commit id "6ea335e334b90a9aca753d558dec1d14741eff1e" and quality "insider" for server
[16:10:58.501] Install and start server if needed
[16:10:58.505] Checking ssh with "ssh -V"
[16:10:59.618] > OpenSSH_for_Windows_8.6p1, 
[16:10:59.618] > LibreSSL 3.3.3

[16:10:59.679] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[16:10:59.777] > OpenSSH_for_Windows_8.6p1,
[16:10:59.777] >  LibreSSL 3.3.3

[16:10:59.838] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[16:11:00.225] > OpenSSH_8.4p1, OpenSSL 1.1.1j  16 Feb 2021

[16:11:00.290] Using SSH config file "C:\Users\alros\.ssh\config"
[16:11:00.291] askpass server listening on \\.\pipe\vscode-ssh-askpass-e8d2cc7d7874ecf2aefb62977c5223ebe08c31d5-sock
[16:11:00.291] Spawning local server with {"serverId":1,"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-762c43b012a8c8b8e26da43bbad6957094f21d2f-sock","sshCommand":"C:\\Program Files\\Git\\usr\\bin\\ssh.exe","sshArgs":["-v","-T","-D","50339","-F","C:\\Users\\alros\\.ssh\\config","127.0.0.1"],"serverDataFolderName":".vscode-server-insiders","dataFilePath":"c:\\Users\\alros\\AppData\\Roaming\\Code - Insiders\\User\\globalStorage\\ms-vscode-remote.remote-ssh\\vscode-ssh-host-08a3d11e-6ea335e334b90a9aca753d558dec1d14741eff1e-0.79.2022040715\\data.json"}
[16:11:00.291] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"c:\\Users\\alros\\.vscode-insiders\\extensions\\ms-vscode-remote.remote-ssh-0.79.2022040715\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"C:\\Program Files\\Microsoft VS Code Insiders\\Code - Insiders.exe","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"c:\\Users\\alros\\.vscode-insiders\\extensions\\ms-vscode-remote.remote-ssh-0.79.2022040715\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-e8d2cc7d7874ecf2aefb62977c5223ebe08c31d5-sock"}
[16:11:00.302] Spawned 30556
[16:11:00.452] > local-server-1> Spawned ssh, pid=5392
[16:11:00.513] stderr> OpenSSH_8.4p1, OpenSSL 1.1.1j  16 Feb 2021
[16:11:00.654] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:keza9iKXJMKG2cYH31QVztttLd8nf8g7ARQ67ParHPQ
[16:11:01.889] Got askpass request: {"request":"alros@127.0.0.1's password: "}
[16:11:01.890] Showing password prompt
[16:11:01.891] Listening for interwindow password on \\.\pipe\vscode-ssh-askpass-9935787fb03c3b2dc1848a145c4ff90c73d5e55b-sock
[16:11:01.891] Writing password prompt to globalState
[16:11:06.921] Got password response
[16:11:06.921] Interactor gave response: **************
[16:11:06.921] Cleaning up other-window auth server
[16:11:07.635] stderr> Authenticated to 127.0.0.1 ([127.0.0.1]:22).
[16:11:10.183] stderr> client_loop: send disconnect: Connection reset by peer
[16:11:10.244] > local-server-1> ssh child died, shutting down
[16:11:10.368] Local server exit: 0
[16:11:10.369] Received install output: local-server-1> Spawned ssh, pid=5392
OpenSSH_8.4p1, OpenSSL 1.1.1j  16 Feb 2021
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:keza9iKXJMKG2cYH31QVztttLd8nf8g7ARQ67ParHPQ
Authenticated to 127.0.0.1 ([127.0.0.1]:22).
client_loop: send disconnect: Connection reset by peer
local-server-1> ssh child died, shutting down

[16:11:10.370] Failed to parse remote port from server output
[16:11:10.374] Resolver error: Error: 
	at Function.Create (c:\Users\alros\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.79.2022040715\out\extension.js:1:585789)
	at Object.t.handleInstallOutput (c:\Users\alros\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.79.2022040715\out\extension.js:1:584441)
	at Object.e [as tryInstallWithLocalServer] (c:\Users\alros\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.79.2022040715\out\extension.js:1:624908)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\alros\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.79.2022040715\out\extension.js:1:643945
	at async Object.t.withShowDetailsEvent (c:\Users\alros\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.79.2022040715\out\extension.js:1:647692)
	at async c:\Users\alros\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.79.2022040715\out\extension.js:1:623380
	at async b (c:\Users\alros\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.79.2022040715\out\extension.js:1:619886)
	at async Object.t.resolveWithLocalServer (c:\Users\alros\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.79.2022040715\out\extension.js:1:622995)
	at async Object.t.resolve (c:\Users\alros\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.79.2022040715\out\extension.js:1:645302)
	at async c:\Users\alros\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.79.2022040715\out\extension.js:1:722235
[16:11:10.380] ------
```

Yes, I'm able to ssh through a terminal. Doesn't seem like the echo test works though:
```
PS C:\Users\alros> echo "echo hello" | ssh 127.0.0.1
Pseudo-terminal will not be allocated because stdin is not a terminal.
alros@127.0.0.1's password:
client_loop: send disconnect: Connection reset
PS C:\Users\alros> ssh 127.0.0.1
alros@127.0.0.1's password:
Microsoft Windows [Version 10.0.22581.200]
(c) Microsoft Corporation. All rights reserved.

redmond\alros@ALROS-1 C:\Users\alros>
```

**Comment by roblourens** [comment]
Did you configure `"remote.SSH.useLocalServer": true`? Can you set `"remote.SSH.useLocalServer": false`?

**Comment by alexr00** [comment]
I did have `"remote.SSH.useLocalServer": true`. Not sure when or why I added it, but setting it to `false` allows me to connect again 🎉

**Comment by roblourens** [comment]
You are hitting a bug with some versions of the windows ssh server :/
