### ISSUE TITLE
Unable to connect to remote wallix server (Failed to parse remote port from server output) still

### ISSUE THREAD

**Issue by raul-bns** [microsoft/vscode-remote-release#6522]
- VSCode Version: 1.65.2
- Remote - SSH Version: v0.76.1
- Local OS Version: Ubuntu 20.04 LTS
- Remote OS Version: Debian GNU/Linux 10 (buster)
- Remote Extension/Connection Type: SSH
- Command ssh : `ssh -l foo@bns-lamp-23:SSH:foo ecrmut-wallix-14.fool.net -oForwardAgent=yes`
- config:
```
Host vh35
  ForwardAgent yes 
  HostName ecrmut-wallix-14.foo.net 
  User foo@bns-lamp-23:SSH:foo
```
- Logs:
```
[15:17:31.547] Log Level: 2
[15:17:31.548] remote-ssh@0.76.1
[15:17:31.548] linux x64
[15:17:31.557] SSH Resolver called for "ssh-remote+vh35", attempt 1
[15:17:31.559] "remote.SSH.useLocalServer": true
[15:17:31.560] "remote.SSH.path": undefined
[15:17:31.560] "remote.SSH.configFile": /home/foo/.ssh/config
[15:17:31.560] "remote.SSH.useFlock": true
[15:17:31.560] "remote.SSH.lockfilesInTmp": false
[15:17:31.561] "remote.SSH.localServerDownload": auto
[15:17:31.561] "remote.SSH.remoteServerListenOnSocket": false
[15:17:31.561] "remote.SSH.showLoginTerminal": false
[15:17:31.561] "remote.SSH.defaultExtensions": []
[15:17:31.561] "remote.SSH.loglevel": 2
[15:17:31.561] "remote.SSH.enableDynamicForwarding": true
[15:17:31.561] "remote.SSH.enableRemoteCommand": true
[15:17:31.562] "remote.SSH.serverPickPortsFromRange": {}
[15:17:31.562] "remote.SSH.serverInstallPath": {}
[15:17:31.573] SSH Resolver called for host: vh35
[15:17:31.573] Setting up SSH remote "vh35"
[15:17:31.576] Acquiring local install lock: /tmp/vscode-remote-ssh-76ef72af-install.lock
[15:17:31.579] Looking for existing server data file at /home/raul/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-76ef72af-c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1-0.76.1/data.json
[15:17:31.580] Using commit id "c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1" and quality "stable" for server
[15:17:31.584] Install and start server if needed
[15:17:31.592] PATH: /home/raul/.nvm/versions/node/v14.17.2/bin:/home/raul/.yarn/bin:/home/foo/.config/yarn/global/node_modules/.bin:/home/foo/.local/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/foo/.cargo/bin:/home/foo/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[15:17:31.592] Checking ssh with "ssh -V"
[15:17:31.597] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020

[15:17:31.600] Using SSH config file "/home/foo/.ssh/config"
[15:17:31.601] askpass server listening on /run/user/1000/vscode-ssh-askpass-82412c9f183e4d14d2ea3a0f8445ef58199158d7.sock
[15:17:31.601] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-997e907348c675cb2412f61b48f4dcf7739277c7.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","45641","-o","ConnectTimeout=15","-F","/home/foo/.ssh/config","vh35"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/foo/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-76ef72af-c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1-0.76.1/data.json"}
[15:17:31.601] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","SHELL":"/usr/bin/zsh","DISPLAY":":1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/foo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/home/foo/apps/VSCode-linux-x64-20220314/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/foo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-82412c9f183e4d14d2ea3a0f8445ef58199158d7.sock"}
[15:17:31.603] Spawned 10659
[15:17:31.673] > local-server-1> Spawned ssh, pid=10667
[15:17:31.675] stderr> OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020
[15:17:32.021] stderr> debug1: Server host key: ssh-ed25519 SHA256:9Y4Do6TZ3JbKKJ3eSIm0i2KGtZ94DuG83mTjBmxvmxY
[15:17:32.245] stderr> Authenticated to ecrmut-wallix-14.foo.net ([213.218]:22).
[15:17:32.486] > AVERTISSEMENT : L’accès à ce système est restreint et réservé aux seuls utilisateurs dûment autorisés. Toute tentative d’accès sans autorisation ou de maintien frauduleux dans ce système fera l’objet de poursuites judiciaires.
> Tout utilisateur dûment autorisé à accéder au système est d’ores et déjà informé et reconnaît que ses actions sont susceptibles d’être enregistrées, conservées et auditées.
> 
> 
> Account successfully checked out
> 
> Connexion à foo@BNS-LAMP-12:SSH...
> 
> Echec de la connexion à la cible secondaire
[15:17:32.709] > 
> Vous êtes informé(e) et reconnaissez que vos actions sont susceptibles d’être enregistrées, conservées et auditées conformément à la politique de sécurité de votre organisation.
> Veuillez vous rapprocher de votre administrateur WALLIX Bastion pour plus d’informations.
[15:17:32.722] stderr> Transferred: sent 5668, received 3780 bytes, in 0.5 seconds
[15:17:32.722] stderr> Bytes per second: sent 11930.3, received 7956.3
[15:17:32.723] > local-server-1> ssh child died, shutting down
[15:17:32.730] Local server exit: 0
[15:17:32.732] Received install output: local-server-1> Spawned ssh, pid=10667
OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020
debug1: Server host key: ssh-ed25519 SHA256:9Y4Do6TZ3JbKTjBmxvmxY
Authenticated to ecrmut-wallix-15.foo.net ([213.218.144.3]:22).
AVERTISSEMENT : L’accès à ce système est restreint et réservé aux seuls utilisateurs dûment autorisés. Toute tentative d’accès sans autorisation ou de maintien frauduleux dans ce système fera l’objet de poursuites judiciaires.
Tout utilisateur dûment autorisé à accéder au système est d’ores et déjà informé et reconnaît que ses actions sont susceptibles d’être enregistrées, conservées et auditées.


Account successfully checked out

Connexion à foo@BNS-LAMP-13:SSH...

Echec de la connexion à la cible secondaire

Vous êtes informé(e) et reconnaissez que vos actions sont susceptibles d’être enregistrées, conservées et auditées conformément à la politique de sécurité de votre organisation.
Veuillez vous rapprocher de votre administrateur WALLIX Bastion pour plus d’informations.

Transferred: sent 5668, received 3780 bytes, in 0.5 seconds
Bytes per second: sent 11930.3, received 7956.3
local-server-1> ssh child died, shutting down

[15:17:32.735] Failed to parse remote port from server output
[15:17:32.738] Resolver error: Error: 
	at Function.Create (/home/foo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:586041)
	at Object.t.handleInstallOutput (/home/foo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:584693)
	at Object.e [as tryInstallWithLocalServer] (/home/foo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:625033)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/foo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:644084
	at async Object.t.withShowDetailsEvent (/home/foo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:647831)
	at async /home/foo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:623505
	at async b (/home/foo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:620011)
	at async Object.t.resolveWithLocalServer (/home/foo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:623120)
	at async Object.t.resolve (/home/foo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:645441)
	at async /home/raul/.vscode/extensions/ms-vscode-remote.remote-ssh-0.76.1/out/extension.js:1:722872
[15:17:32.748] -----
```

Hi everybody I've seen that this is a problem that appearse in different issues, so I've tried differents solutions Like:
- I've already tried to check, and in the remote server the shell is bash, so i have bin/bash. 
- I've put "remote.SSH.useLocalServer": false,
- I've try the prerelease version
- I'cant delete .vscode-server from the remote server coz it's first time i've tried to connect

Thanks in advance for help

**Comment by tanhakabir** [comment]
Are you trying to connect to your remote machine through a proxy or a jump server?

**Comment by raul-bns** [comment]
`[11:58:28.324] Log Level: 2
[11:58:28.325] remote-ssh@0.84.0
[11:58:28.325] linux x64
[11:58:28.326] SSH Resolver called for "ssh-remote+vh34", attempt 1
[11:58:28.327] "remote.SSH.useLocalServer": false
[11:58:28.328] "remote.SSH.showLoginTerminal": false
[11:58:28.328] "remote.SSH.remotePlatform": {"vh23":"linux"}
[11:58:28.328] "remote.SSH.path": undefined
[11:58:28.329] "remote.SSH.configFile": /home/user/.ssh/config
[11:58:28.329] "remote.SSH.useFlock": true
[11:58:28.330] "remote.SSH.lockfilesInTmp": false
[11:58:28.330] "remote.SSH.localServerDownload": auto
[11:58:28.330] "remote.SSH.remoteServerListenOnSocket": false
[11:58:28.330] "remote.SSH.showLoginTerminal": false
[11:58:28.331] "remote.SSH.defaultExtensions": []
[11:58:28.331] "remote.SSH.loglevel": 2
[11:58:28.331] "remote.SSH.enableDynamicForwarding": true
[11:58:28.332] "remote.SSH.enableRemoteCommand": true
[11:58:28.332] "remote.SSH.serverPickPortsFromRange": {}
[11:58:28.332] "remote.SSH.serverInstallPath": {}
[11:58:28.340] SSH Resolver called for host: vh34
[11:58:28.340] Setting up SSH remote "vh34"
[11:58:28.344] Using commit id "3b889b090b5ad5793f524b5d1d39fda662b96a2a" and quality "stable" for server
[11:58:28.348] Install and start server if needed
[11:58:30.002] PATH: /home/user/.nvm/versions/node/v14.17.2/bin:/home/user/.yarn/bin:/home/raul/.config/yarn/global/node_modules/.bin:/home/user/.local/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/user/.cargo/bin:/home/raul/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[11:58:30.003] Checking ssh with "ssh -V"
[11:58:30.009] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020

[11:58:30.012] Using SSH config file "/home/user/.ssh/config"
[11:58:30.012] Running script with connection command: ssh -T -D 32963 -o ConnectTimeout=15 -F '/home/raul/.ssh/config' vh34 bash
[11:58:31.456] > 
> Echec de la connexion à la cible secondaire
[11:58:31.457] Got some output, clearing connection timeout
[11:58:32.029] "install" terminal command done
[11:58:32.030] Install terminal quit with output: Echec de la connexion à la cible secondaire
[11:58:32.031] Received install output: Echec de la connexion à la cible secondaire
[11:58:32.032] Failed to parse remote port from server output
[11:58:32.037] Resolver error: Error: 
	at Function.Create (/home/raul/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585222)
	at Object.t.handleInstallOutput (/home/raul/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:583874)
	at Object.t.tryInstall (/home/raul/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:681023)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/raul/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643908
	at async Object.t.withShowDetailsEvent (/home/raul/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
	at async Object.t.resolve (/home/raul/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644958)
	at async /home/raul/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[11:58:32.043] -----`

Hi tanhakabir still not working. I'm not able to connect

**Comment by raul-bns** [comment]
Yes we pass trouthg a bastion to connect to wallix

**Comment by roblourens** [comment]
From the log, it looks like the install script that we pipe into ssh is not arriving. That will have to work, otherwise you might be interested in https://marketplace.visualstudio.com/items?itemName=ms-vscode.remote-server

**Comment by raul-bns** [comment]
Hey that works perfectly. Thanls a lot 😄
