### ISSUE TITLE
Error: Missing node-pty

### ISSUE THREAD

**Issue by SrTobi** [microsoft/vscode-remote-release#6525]
Steps to Reproduce:

1. Install Remote-Containers 0.231.0
2. Open any devcontainer

If I install the version `0.224.3` it works flawlessly.

But with `0.231.0` I'm getting the following error:
```
[52 ms] Remote-Containers 0.231.0 in VS Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1).
[52 ms] Start: Resolving Remote
[57 ms] Setting up container for folder or workspace: <path-to-project>
[59 ms] Start: Check Docker is running
[59 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[79 ms] Server API version: 1.41
[80 ms] Start: Run: docker volume create vscode
[97 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=<path-to-project> --filter label=vsch.quality=stable
[111 ms] Start: Run: docker inspect --type container 6e06ffb78810
[126 ms] Start: Run: /nix/store/x85h99avi761h81a9vpfv79qbx9rg22m-vscode-1.65.2/lib/vscode/code <home>/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.0/dist/spec-node/devContainersSpecCLI.js up --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder <path-to-project> --workspace-mount-consistency cached --id-label vsch.local.folder=<path-to-project> --id-label vsch.quality=stable --log-level debug --config <path-to-project>/.devcontainer/devcontainer.json --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[210 ms] Error: Missing node-pty
[211 ms]     at ph (<home>/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.0/dist/spec-node/devContainersSpecCLI.js:79:1410)
[211 ms]     at async Za (<home>/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.0/dist/spec-node/devContainersSpecCLI.js:78:13320)
[211 ms]     at async Sa (<home>/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.0/dist/spec-node/devContainersSpecCLI.js:223:4175)
[211 ms]     at async Jw (<home>/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.0/dist/spec-node/devContainersSpecCLI.js:223:3153)
[211 ms]     at async TR (<home>/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.0/dist/spec-node/devContainersSpecCLI.js:223:13880)
[211 ms]     at async FR (<home>/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.0/dist/spec-node/devContainersSpecCLI.js:223:13605)
[213 ms] Exit code 1
[215 ms] Command failed: /nix/store/x85h99avi761h81a9vpfv79qbx9rg22m-vscode-1.65.2/lib/vscode/code <home>/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.0/dist/spec-node/devContainersSpecCLI.js up --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder <path-to-project> --workspace-mount-consistency cached --id-label vsch.local.folder=<path-to-project> --id-label vsch.quality=stable --log-level debug --config <path-to-project>/.devcontainer/devcontainer.json --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[215 ms] Exit code 1
```

**Comment by nickperrott** [comment]
Thanks to @SrTobi for reporting this, you have saved me a whole heap of time.  I have now rolled back to 0.224.3 and am breathing again.

**Comment by scalavision** [comment]
I also stumbled into this.

**Comment by chrmarti** [comment]
Fixed in Remote-Containers 0.231.1 and 0.232.1-pre-release.

**Comment by chrismamo1** [comment]
Just today I started having this exact issue with version 0.231.3, reverting to 0.224.3 solved it for me as well.

**Comment by chrmarti** [comment]
@chrismamo1 Could you open a new issue with the full log from when this failed?
