### ISSUE TITLE
Can't modify path enviroment variable with containers extension version 0.231

### ISSUE THREAD

**Issue by aelray** [microsoft/vscode-remote-release#6534]
- VSCode Version: 1.66.0
- Local OS Version: Windows 10 -> SSH Ubuntu 21.10
- Remote OS Version: Ubuntu 21.10 (podman container)
- Remote Extension/Connection Type: SSH/Docker
- Logs:

```
[2022-03-31T12:23:19.223Z] Start: Run: podman inspect --type container 5e068df8b5ec49f37fa9ff1c93754ba11bf06824aca1247c96bcce4d22ae18c7
[2022-03-31T12:23:19.467Z] Stop (1465 ms): Run: podman run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/***/Firmware/devcontainerTest,target=/workspaces/devcontainerTest -l vsch.local.folder=/home/***/Firmware/devcontainerTest -l vsch.quality=stable -e PATH=${containerEnv:PATH}:/home/vscode/.local/bin -u vscode --userns=keep-id --cap-add=SYS_PTRACE --entrypoint /bin/sh vsc-devcontainertest-228e317c854828d41db65924cd3ff5dd-uid -c echo Container started
[2022-03-31T12:23:19.468Z] Start: Run: podman ps -q -a --filter label=vsch.local.folder=/home/***/Firmware/devcontainerTest --filter label=vsch.quality=stable
[2022-03-31T12:23:19.487Z] Stop (1490 ms): Run: podman events --format json --filter event=start
[2022-03-31T12:23:19.526Z] Stop (303 ms): Run: podman inspect --type container 5e068df8b5ec49f37fa9ff1c93754ba11bf06824aca1247c96bcce4d22ae18c7
[2022-03-31T12:23:19.635Z] Stop (167 ms): Run: podman ps -q -a --filter label=vsch.local.folder=/home/***/Firmware/devcontainerTest --filter label=vsch.quality=stable
[2022-03-31T12:23:19.635Z] Start: Run: podman inspect --type container 5e068df8b5ec
[2022-03-31T12:23:19.791Z] Stop (156 ms): Run: podman inspect --type container 5e068df8b5ec
[2022-03-31T12:23:19.851Z] Error: An error occurred setting up the container.
[2022-03-31T12:23:19.852Z]     at ER (/home/***/.vscode-remote-containers/dist/dev-containers-cli-0.231.0/dist/spec-node/devContainersSpecCLI.js:218:986)
[2022-03-31T12:23:19.852Z]     at qw (/home/***/.vscode-remote-containers/dist/dev-containers-cli-0.231.0/dist/spec-node/devContainersSpecCLI.js:218:924)
[2022-03-31T12:23:19.852Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-03-31T12:23:19.852Z]     at async RR (/home/***/.vscode-remote-containers/dist/dev-containers-cli-0.231.0/dist/spec-node/devContainersSpecCLI.js:223:2024)
[2022-03-31T12:23:19.852Z]     at async Jw (/home/***/.vscode-remote-containers/dist/dev-containers-cli-0.231.0/dist/spec-node/devContainersSpecCLI.js:223:3221)
[2022-03-31T12:23:19.852Z]     at async TR (/home/***/.vscode-remote-containers/dist/dev-containers-cli-0.231.0/dist/spec-node/devContainersSpecCLI.js:223:13880)
[2022-03-31T12:23:19.853Z]     at async FR (/home/***/.vscode-remote-containers/dist/dev-containers-cli-0.231.0/dist/spec-node/devContainersSpecCLI.js:223:13605)
[2022-03-31T12:23:19.859Z] Stop (5199 ms): Run in Host: /home/***/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/node /home/***/.vscode-remote-containers/dist/dev-containers-cli-0.231.0/dist/spec-node/devContainersSpecCLI.js up --docker-path podman --docker-compose-path podman-compose --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /home/***/Firmware/devcontainerTest --workspace-mount-consistency cached --id-label vsch.local.folder=/home/***/Firmware/devcontainerTest --id-label vsch.quality=stable --log-level debug --config /home/***/Firmware/devcontainerTest/.devcontainer/devcontainer.json --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-03-31T12:23:19.859Z] Exit code 1
[2022-03-31T12:23:19.861Z] Command failed: /home/***/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/node /home/***/.vscode-remote-containers/dist/dev-containers-cli-0.231.0/dist/spec-node/devContainersSpecCLI.js up --docker-path podman --docker-compose-path podman-compose --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /home/***/Firmware/devcontainerTest --workspace-mount-consistency cached --id-label vsch.local.folder=/home/***/Firmware/devcontainerTest --id-label vsch.quality=stable --log-level debug --config /home/***/Firmware/devcontainerTest/.devcontainer/devcontainer.json --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-03-31T12:23:19.861Z] Exit code 1
```

Steps to Reproduce:

1. use Ubuntu sample devcontainer config
2. modify path with
```
    "containerEnv": {
        "PATH" : "${containerEnv:PATH}:/home/vscode/.local/bin"
    }
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by aelray** [comment]
found out that replacing

```
    "containerEnv": {
        "PATH" : "${containerEnv:PATH}:/home/vscode/.local/bin"
    }
```
with
```
    "remoteEnv": {
        "PATH" : "${containerEnv:PATH}:/home/vscode/.local/bin"
    }
```
solves the issue. Weird, that this only popped-up with the update.
