### ISSUE TITLE
Unable to clone repos into container volumes

### ISSUE THREAD

**Issue by chriscasola** [microsoft/vscode-remote-release#6545]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Command Palette -> Clone Repo in Container Volume
1. Paste "https://github.com/evanw/esbuild.git"
1. Select "Go" Project
1. Select "1.17-bullseye"
1. Don't install node
1. No extra features
1. Container server will fail to start.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

<details>
<summary>Container Log</summary>

```bash
[2022-04-01T15:24:12.576Z] Remote-Containers 0.232.2 in VS Code 1.67.0-insider (8b7086afdbfd42bf6e7b8c0bb586530bf7cf1396).
[2022-04-01T15:24:12.576Z] Start: Resolving Remote
[2022-04-01T15:24:12.581Z] Start: Check Docker is running
[2022-04-01T15:24:12.581Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2022-04-01T15:24:12.744Z] Stop (163 ms): Run: docker version --format {{.Server.APIVersion}}
[2022-04-01T15:24:12.745Z] Server API version: 1.41
[2022-04-01T15:24:12.745Z] Stop (164 ms): Check Docker is running
[2022-04-01T15:24:12.745Z] Start: Run: docker volume ls -q
[2022-04-01T15:24:12.768Z] Stop (23 ms): Run: docker volume ls -q
[2022-04-01T15:24:12.768Z] Start: Run: docker volume create --label vsch.local.repository=https://github.com/evanw/esbuild.git --label vsch.local.repository.unique=true esbuild-03d0ab4bfde9ce2889d62efa148a3485
[2022-04-01T15:24:12.797Z] Stop (29 ms): Run: docker volume create --label vsch.local.repository=https://github.com/evanw/esbuild.git --label vsch.local.repository.unique=true esbuild-03d0ab4bfde9ce2889d62efa148a3485
[2022-04-01T15:24:12.798Z] Start: Run: docker build -f /var/folders/7m/kwm3sc350q3c5w3cq0xkm2_hykbkhg/T/vsch/bootstrap-image/0.232.2/bootstrap.Dockerfile -t vsc-volume-bootstrap /var/folders/7m/kwm3sc350q3c5w3cq0xkm2_hykbkhg/T/vsch/bootstrap-image/0.232.2
[2022-04-01T15:24:13.880Z] [+] Building 0.0s (0/1)                                                         
[2022-04-01T15:24:14.031Z] [+] Building 0.1s (1/1)                                                         
 => [internal] load build definition from bootstrap.Dockerfile             0.0s
[2022-04-01T15:24:14.032Z]  => => transferring dockerfile: 54B                                        0.0s
[2022-04-01T15:24:14.182Z] [+] Building 0.3s (2/2)                                                         
 => [internal] load build definition from bootstrap.Dockerfile             0.0s
[2022-04-01T15:24:14.183Z]  => => transferring dockerfile: 54B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
[2022-04-01T15:24:14.332Z] [+] Building 0.4s (2/3)                                                         
 => [internal] load build definition from bootstrap.Dockerfile             0.0s
 => => transferring dockerfile: 54B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/b  0.1s
[2022-04-01T15:24:14.482Z] [+] Building 0.6s (2/3)                                                         
 => [internal] load build definition from bootstrap.Dockerfile             0.0s
 => => transferring dockerfile: 54B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/b  0.2s
[2022-04-01T15:24:14.634Z] [+] Building 0.7s (2/3)                                                         
[2022-04-01T15:24:14.635Z]  => [internal] load build definition from bootstrap.Dockerfile             0.0s
 => => transferring dockerfile: 54B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/b  0.4s
[2022-04-01T15:24:14.734Z] [+] Building 0.8s (3/3)                                                         
 => [internal] load build definition from bootstrap.Dockerfile             0.0s
 => => transferring dockerfile: 54B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
[2022-04-01T15:24:14.735Z]  => => transferring context: 2B                                            0.0s
 => [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/b  0.5s
[2022-04-01T15:24:14.809Z] [+] Building 0.9s (9/9) FINISHED                                                
 => [internal] load build definition from bootstrap.Dockerfile             0.0s
 => => transferring dockerfile: 54B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/b  0.5s
 => [1/4] FROM mcr.microsoft.com/vscode/devcontainers/base:0-alpine-3.14@  0.0s
 => [internal] load build context                                          0.0s
 => => transferring context: 5.90kB                                        0.0s
 => CACHED [2/4] RUN apk add --no-cache  nodejs  npm  make  g++  docker-c  0.0s
 => CACHED [3/4] RUN cd && npm i node-pty                                  0.0s
 =>
[2022-04-01T15:24:14.809Z]  CACHED [4/4] COPY .vscode-remote-containers /root/.vscode-remote-cont  0.0s
 => exporting to image                                                     0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:c176e6f51732f3c24d43ab41913f6a05b4c9545053d89  0.0s
 => => naming to docker.io/library/vsc-volume-bootstrap                    0.0s
[2022-04-01T15:24:14.810Z] Stop (2012 ms): Run: docker build -f /var/folders/7m/kwm3sc350q3c5w3cq0xkm2_hykbkhg/T/vsch/bootstrap-image/0.232.2/bootstrap.Dockerfile -t vsc-volume-bootstrap /var/folders/7m/kwm3sc350q3c5w3cq0xkm2_hykbkhg/T/vsch/bootstrap-image/0.232.2
[2022-04-01T15:24:14.811Z] Cloning Github repository: evanw/esbuild into /workspaces/esbuild

[2022-04-01T15:24:14.811Z] Start: Run: docker run -d --mount type=volume,src=esbuild-03d0ab4bfde9ce2889d62efa148a3485,dst=/workspaces -v /var/run/docker.sock:/var/run/docker.sock vsc-volume-bootstrap sleep infinity
[2022-04-01T15:24:17.107Z] Stop (2296 ms): Run: docker run -d --mount type=volume,src=esbuild-03d0ab4bfde9ce2889d62efa148a3485,dst=/workspaces -v /var/run/docker.sock:/var/run/docker.sock vsc-volume-bootstrap sleep infinity
[2022-04-01T15:24:17.108Z] Start: Run in container: /bin/sh
[2022-04-01T15:24:17.110Z] Start: Launching Remote-Containers helper.
[2022-04-01T15:24:17.110Z] ssh-agent: SSH_AUTH_SOCK in container (/tmp/vscode-ssh-auth-601df4992881eb249221c89a42bc8680a67d4353.sock) forwarded to local host (/private/tmp/com.apple.launchd.pGpdjuSwNT/Listeners).
[2022-04-01T15:24:17.111Z] Start: Run: gpgconf --list-dir agent-extra-socket
[2022-04-01T15:24:17.111Z] Stop (0 ms): Run: gpgconf --list-dir agent-extra-socket
[2022-04-01T15:24:17.112Z] Start: Run in container: /bin/sh
[2022-04-01T15:24:17.112Z] Stop (2 ms): Launching Remote-Containers helper.
[2022-04-01T15:24:17.112Z] Stop (1 ms): Run: gpgconf --list-dir agent-extra-socket
[2022-04-01T15:24:17.113Z] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-601df4992881eb249221c89a42bc8680a67d4353.js' >/tmp/vscode-remote-containers-601df4992881eb249221c89a42bc8680a67d4353.js
[2022-04-01T15:24:18.350Z] 
[2022-04-01T15:24:18.350Z] 
[2022-04-01T15:24:18.350Z] Stop (1237 ms): Run in container: cat <<'EOF-/tmp/vscode-remote-containers-601df4992881eb249221c89a42bc8680a67d4353.js' >/tmp/vscode-remote-containers-601df4992881eb249221c89a42bc8680a67d4353.js
[2022-04-01T15:24:18.350Z] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-601df4992881eb249221c89a42bc8680a67d4353.js' >/tmp/vscode-remote-containers-server-601df4992881eb249221c89a42bc8680a67d4353.js_1648826658350
[2022-04-01T15:24:18.384Z] 
[2022-04-01T15:24:18.385Z] 
[2022-04-01T15:24:18.385Z] Stop (35 ms): Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-601df4992881eb249221c89a42bc8680a67d4353.js' >/tmp/vscode-remote-containers-server-601df4992881eb249221c89a42bc8680a67d4353.js_1648826658350
[2022-04-01T15:24:18.389Z] Start: Run in container: # Test for /root/.gitconfig and git
[2022-04-01T15:24:18.409Z] 
[2022-04-01T15:24:18.410Z] 
[2022-04-01T15:24:18.410Z] Stop (21 ms): Run in container: # Test for /root/.gitconfig and git
[2022-04-01T15:24:18.411Z] Start: Run in container: # Copy /Users/ccasola/.gitconfig to /root/.gitconfig
[2022-04-01T15:24:18.443Z] 
[2022-04-01T15:24:18.444Z] 
[2022-04-01T15:24:18.444Z] Stop (33 ms): Run in container: # Copy /Users/ccasola/.gitconfig to /root/.gitconfig
[2022-04-01T15:24:18.445Z] Start: Run in container: command -v git >/dev/null 2>&1 && git config --global --replace-all credential.helper '!f() { node /tmp/vscode-remote-containers-601df4992881eb249221c89a42bc8680a67d4353.js $*; }; f' || true
[2022-04-01T15:24:18.472Z] 
[2022-04-01T15:24:18.473Z] 
[2022-04-01T15:24:18.473Z] Stop (28 ms): Run in container: command -v git >/dev/null 2>&1 && git config --global --replace-all credential.helper '!f() { node /tmp/vscode-remote-containers-601df4992881eb249221c89a42bc8680a67d4353.js $*; }; f' || true
[2022-04-01T15:24:18.474Z] Start: Run in container: # Test for /root/.ssh/known_hosts and ssh
[2022-04-01T15:24:18.489Z] 
[2022-04-01T15:24:18.489Z] 
[2022-04-01T15:24:18.489Z] Stop (15 ms): Run in container: # Test for /root/.ssh/known_hosts and ssh
[2022-04-01T15:24:18.489Z] Start: Run in container: # Copy /Users/ccasola/.ssh/known_hosts to /root/.ssh/known_hosts
[2022-04-01T15:24:18.519Z] 
[2022-04-01T15:24:18.519Z] 
[2022-04-01T15:24:18.520Z] Stop (31 ms): Run in container: # Copy /Users/ccasola/.ssh/known_hosts to /root/.ssh/known_hosts
[2022-04-01T15:24:19.418Z] Start: Run in container: git clone --depth 1 https://github.com/evanw/esbuild.git .
[2022-04-01T15:24:20.095Z] Cloning into '.'...
[2022-04-01T15:24:20.665Z] remote: Enumerating objects: 330, done.
remote: Counting objects:   0% (1/330)

...truncated git fetch status

[2022-04-01T15:24:21.673Z] Resolving deltas: 100% (58/58), done.
[2022-04-01T15:24:22.108Z] Stop (2690 ms): Run in container: git clone --depth 1 https://github.com/evanw/esbuild.git .
[2022-04-01T15:24:22.163Z] Start: Run in container: cat /workspaces/esbuild/.devcontainer/devcontainer.json 2>/dev/null
[2022-04-01T15:24:22.180Z] Stop (17 ms): Run in container: cat /workspaces/esbuild/.devcontainer/devcontainer.json 2>/dev/null
[2022-04-01T15:24:22.180Z] Start: Run in container: cat /workspaces/esbuild/.devcontainer.json 2>/dev/null
[2022-04-01T15:24:22.195Z] Stop (15 ms): Run in container: cat /workspaces/esbuild/.devcontainer.json 2>/dev/null
[2022-04-01T15:24:22.196Z] Repository evanw/esbuild has no development container files.

[2022-04-01T15:24:38.925Z] Start: Run in container: cat /workspaces/esbuild/.devcontainer/devcontainer.json 2>/dev/null
[2022-04-01T15:24:38.946Z] Stop (21 ms): Run in container: cat /workspaces/esbuild/.devcontainer/devcontainer.json 2>/dev/null
[2022-04-01T15:24:39.546Z] Start: Run in container: docker volume ls -q
[2022-04-01T15:24:40.565Z] Stop (1019 ms): Run in container: docker volume ls -q
[2022-04-01T15:24:41.796Z] Start: Run in container: docker ps -q -a --filter label=vsch.local.repository=https://github.com/evanw/esbuild.git --filter label=vsch.local.repository.volume=esbuild-03d0ab4bfde9ce2889d62efa148a3485 --filter label=vsch.local.repository.folder=esbuild --filter label=vsch.quality=insider
[2022-04-01T15:24:42.940Z] Stop (1144 ms): Run in container: docker ps -q -a --filter label=vsch.local.repository=https://github.com/evanw/esbuild.git --filter label=vsch.local.repository.volume=esbuild-03d0ab4bfde9ce2889d62efa148a3485 --filter label=vsch.local.repository.folder=esbuild --filter label=vsch.quality=insider
[2022-04-01T15:24:44.207Z] Start: Run in container: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.232.2/dist/spec-node/devContainersSpecCLI.js up --container-data-folder .vscode-server-insiders/data/Machine --container-system-data-folder /var/vscode-server-insiders --workspace-folder /workspaces/esbuild --workspace-mount-consistency cached --id-label vsch.local.repository=https://github.com/evanw/esbuild.git --id-label vsch.local.repository.volume=esbuild-03d0ab4bfde9ce2889d62efa148a3485 --id-label vsch.local.repository.folder=esbuild --id-label vsch.quality=insider --log-level debug --config /workspaces/esbuild/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-75b6b37a-dbdf-45ef-8315-cff1f031846d.json --mount type=volume,source=esbuild-03d0ab4bfde9ce2889d62efa148a3485,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root true
[2022-04-01T15:24:22.109Z] Start: Run in container: git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
[2022-04-01T15:24:22.929Z] Stop (820 ms): Run in container: git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
[2022-04-01T15:24:22.929Z] Start: Run in container: git fetch --unshallow --tags
[2022-04-01T15:24:24.599Z] remote: Enumerating objects: 32950, done.
[2022-04-01T15:24:24.606Z] remote: Counting objects:   0% (1/32950)

...truncated git fetch status

[2022-04-01T15:24:46.131Z]  * [new tag]           v0.9.5      -> v0.9.5
 * [new tag]           v0.9.6      -> v0.9.6
 * [new tag]           v0.9.7      -> v0.9.7
[2022-04-01T15:24:46.172Z] Stop (23243 ms): Run in container: git fetch --unshallow --tags
[2022-04-01T15:24:46.083Z] remote-containers 0.232.2.
[2022-04-01T15:24:46.082Z] Start: Resolving Remote
[2022-04-01T15:24:46.129Z] Start: Run: git rev-parse --show-cdup
[2022-04-01T15:24:46.184Z] Stop (55 ms): Run: git rev-parse --show-cdup
[2022-04-01T15:24:46.199Z] Start: Run: docker ps -q -a --filter label=vsch.local.repository=https://github.com/evanw/esbuild.git --filter label=vsch.local.repository.volume=esbuild-03d0ab4bfde9ce2889d62efa148a3485 --filter label=vsch.local.repository.folder=esbuild --filter label=vsch.quality=insider
[2022-04-01T15:24:46.588Z] Stop (389 ms): Run: docker ps -q -a --filter label=vsch.local.repository=https://github.com/evanw/esbuild.git --filter label=vsch.local.repository.volume=esbuild-03d0ab4bfde9ce2889d62efa148a3485 --filter label=vsch.local.repository.folder=esbuild --filter label=vsch.quality=insider
[2022-04-01T15:24:46.975Z] Error: Command failed: docker ps -q -a --filter label=vsch.local.repository=https://github.com/evanw/esbuild.git --filter label=vsch.local.repository.volume=esbuild-03d0ab4bfde9ce2889d62efa148a3485 --filter label=vsch.local.repository.folder=esbuild --filter label=vsch.quality=insider
[2022-04-01T15:24:46.976Z]     at ER (/root/.vscode-remote-containers/dist/dev-containers-cli-0.232.2/dist/spec-node/devContainersSpecCLI.js:218:986)
[2022-04-01T15:24:46.977Z]     at qw (/root/.vscode-remote-containers/dist/dev-containers-cli-0.232.2/dist/spec-node/devContainersSpecCLI.js:218:924)
[2022-04-01T15:24:46.977Z]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[2022-04-01T15:24:46.977Z]     at async RR (/root/.vscode-remote-containers/dist/dev-containers-cli-0.232.2/dist/spec-node/devContainersSpecCLI.js:223:2024)
[2022-04-01T15:24:46.977Z]     at async Jw (/root/.vscode-remote-containers/dist/dev-containers-cli-0.232.2/dist/spec-node/devContainersSpecCLI.js:223:3221)
[2022-04-01T15:24:46.978Z]     at async TR (/root/.vscode-remote-containers/dist/dev-containers-cli-0.232.2/dist/spec-node/devContainersSpecCLI.js:223:13880)
[2022-04-01T15:24:46.978Z]     at async FR (/root/.vscode-remote-containers/dist/dev-containers-cli-0.232.2/dist/spec-node/devContainersSpecCLI.js:223:13605)
[2022-04-01T15:24:47.005Z] Stop (2798 ms): Run in container: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.232.2/dist/spec-node/devContainersSpecCLI.js up --container-data-folder .vscode-server-insiders/data/Machine --container-system-data-folder /var/vscode-server-insiders --workspace-folder /workspaces/esbuild --workspace-mount-consistency cached --id-label vsch.local.repository=https://github.com/evanw/esbuild.git --id-label vsch.local.repository.volume=esbuild-03d0ab4bfde9ce2889d62efa148a3485 --id-label vsch.local.repository.folder=esbuild --id-label vsch.quality=insider --log-level debug --config /workspaces/esbuild/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-75b6b37a-dbdf-45ef-8315-cff1f031846d.json --mount type=volume,source=esbuild-03d0ab4bfde9ce2889d62efa148a3485,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root true
[2022-04-01T15:24:47.006Z] Exit code 1
[2022-04-01T15:24:47.007Z] Start: Run: docker rm -f a26c995601c681fdeb75d94e86550d18c8bb4f1210e4af7ce8e7c7d06a5344ca
[2022-04-01T15:24:47.026Z] Command failed: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.232.2/dist/spec-node/devContainersSpecCLI.js up --container-data-folder .vscode-server-insiders/data/Machine --container-system-data-folder /var/vscode-server-insiders --workspace-folder /workspaces/esbuild --workspace-mount-consistency cached --id-label vsch.local.repository=https://github.com/evanw/esbuild.git --id-label vsch.local.repository.volume=esbuild-03d0ab4bfde9ce2889d62efa148a3485 --id-label vsch.local.repository.folder=esbuild --id-label vsch.quality=insider --log-level debug --config /workspaces/esbuild/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-75b6b37a-dbdf-45ef-8315-cff1f031846d.json --mount type=volume,source=esbuild-03d0ab4bfde9ce2889d62efa148a3485,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root true
[2022-04-01T15:24:47.026Z] Exit code 1
[2022-04-01T15:24:47.223Z] Stop (30115 ms): Run in container: /bin/sh
[2022-04-01T15:24:47.269Z] Stop (30157 ms): Run in container: /bin/sh
[2022-04-01T15:24:47.269Z] Container server terminated (code: 137, signal: null).
[2022-04-01T15:24:48.161Z] Stop (1154 ms): Run: docker rm -f a26c995601c681fdeb75d94e86550d18c8bb4f1210e4af7ce8e7c7d06a5344ca

```

</details>

VS Code version: Code 1.65.2 (Universal) (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: Yes
Connection to 'Dev Container' could not be established 

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (11.83GB free)|
|Process Argv|--crash-reporter-id d508ed84-02f4-4171-a8cb-db3ed5a696f5|
|Screen Reader|no|
|VM|0%|

Connection to 'Dev Container' could not be established 
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
pythonvsnew555:30457759
vscscmwlcmt:30438805
vscgsvid2:30447481
pynewfile477:30463512

```

</details>

**Comment by chrmarti** [comment]
Fixed in v0.231.3 and v0.232.3-pre-release as #6541.
