### ISSUE TITLE
remote development in container has stopped working

### ISSUE THREAD

**Issue by skoushan** [microsoft/vscode-remote-release#6547]

**Comment by befer** [comment]
I am using Remote-Containers 0.231.2 and VS Code 1.66, Client on Windows, remote Linux Ubuntu Focal and can confirm the issue. Remote containers are losing connection and are unable to reconnect. Need to stop the container on the remote host with 'docker stop ...' before I can reconnect. And I also confirm that this is a new issue occurring after the last update.

A few more details. 
Usually when working on a project, I follow the sequence:
- open the project folder using Remote-Explorer SSH Targets
- vscode is detecting that I have a .devcontainer folder inside of my project and is asking me, if I want to reopen it in a container.
- I do that and up until here everything works fine.
- BUT: I usually have a workspace file and open it then. And exactly at this point the trouble starts. After opening the workspace, the vscode client loses the connection after a few minutes and is unable to reconnect.

**Comment by thomas-qualia** [comment]
I'm having this problem recently also. I'm using remote ssh extension into a linux VM (not remote-ing into a container). I notice it happening after I close my mac for a bit and come back to it. I just kill VS Code and open it again to fix it.

<details>
  <summary>About VS Code</summary>

  ```
Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:04.419Z (4 days ago)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 21.4.0
  ```
</details>

<details>
  <summary>Remote SSH logs</summary>

  ```
[13:00:00.698] Log Level: 2
[13:00:00.699] remote-ssh@0.78.0
[13:00:00.700] darwin x64
[13:00:00.713] SSH Resolver called for "ssh-remote+<redacted>", attempt 1
[13:00:00.713] "remote.SSH.useLocalServer": true
[13:00:00.713] "remote.SSH.path": undefined
[13:00:00.713] "remote.SSH.configFile": /Users/<redacted>/ssh-config
[13:00:00.714] "remote.SSH.useFlock": true
[13:00:00.714] "remote.SSH.lockfilesInTmp": false
[13:00:00.714] "remote.SSH.localServerDownload": auto
[13:00:00.714] "remote.SSH.remoteServerListenOnSocket": false
[13:00:00.714] "remote.SSH.showLoginTerminal": false
[13:00:00.714] "remote.SSH.defaultExtensions": []
[13:00:00.714] "remote.SSH.loglevel": 2
[13:00:00.714] "remote.SSH.enableDynamicForwarding": true
[13:00:00.714] "remote.SSH.enableRemoteCommand": false
[13:00:00.714] "remote.SSH.serverPickPortsFromRange": {}
[13:00:00.715] "remote.SSH.serverInstallPath": {}

... everything here working just fine
    i do some work
    put away mac for a couple hours
    and try to pick back up...

[17:12:07.984] ------




[17:12:07.985] SSH Resolver called for "ssh-remote+<redacted>", attempt 2, (Reconnection)
[17:12:07.987] SSH Resolver called for host: <redacted>
[17:12:07.988] Setting up SSH remote "<redacted>"
[17:12:07.992] Acquiring local install lock: /var/folders/gv/q6tpt5m50ps5m0lkzh2s0hjc0000gn/T/vscode-remote-ssh-79e23cc2-install.lock
[17:12:07.993] Looking for existing server data file at /Users/<redacted>/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-79e23cc2-e18005f0f1b33c29e81d732535d8c0e47cafb0b5-0.78.0/data.json
[17:12:08.030] Found local server running: {"remoteListeningOn":{"port":38019},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"/tmp/ssh-mNKsJZOHL9/agent.13937","display":"","tmpDir":"/run/user/1000","platform":"linux","connectionToken":"111a1a11-11aa-1111-a111-a111111a1111","pid":5348,"ipcHandlePath":"/var/folders/gv/q6tpt5m50ps5m0lkzh2s0hjc0000gn/T/vscode-ssh-askpass-5e656d1e5cbfc3912e677b80b6180225bba863d0.sock","socksPort":49261,"startupTime":1648983600764}
[17:12:08.030] Running server is stale. Ignoring
[17:12:08.030] Using commit id "e18005f0f1b33c29e81d732535d8c0e47cafb0b5" and quality "stable" for server
[17:12:08.036] Install and start server if needed
[17:12:08.044] Using SSH config file "/Users/<redacted>/ssh-config"
[17:12:08.046] askpass server listening on /var/folders/gv/q6tpt5m50ps5m0lkzh2s0hjc0000gn/T/vscode-ssh-askpass-ef7d0899702313ee163470442c1d825f3b7a83ec.sock
[17:12:08.047] Spawning local server with {"serverId":2,"ipcHandlePath":"/var/folders/gv/q6tpt5m50ps5m0lkzh2s0hjc0000gn/T/vscode-ssh-askpass-73ffaa37cbd520805cf871505768640dbd20315a.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","62536","-o","ConnectTimeout=15","-F","/Users/<redacted>/ssh-config","<redacted>"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/<redacted>/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-79e23cc2-e18005f0f1b33c29e81d732535d8c0e47cafb0b5-0.78.0/data.json"}
[17:12:08.047] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.mu7yOF2HVM/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/gv/q6tpt5m50ps5m0lkzh2s0hjc0000gn/T/vscode-ssh-askpass-ef7d0899702313ee163470442c1d825f3b7a83ec.sock"}
[17:12:08.049] Spawned 9813
[17:12:08.185] > local-server-2> Spawned ssh, pid=9815
[17:12:08.198] stderr> OpenSSH_8.6p1, LibreSSL 3.3.5
[17:12:11.775] > local-server-1> Timed out
[17:12:11.781] Local server exit: 0
[17:12:23.189] stderr> Connection timed out during banner exchange
[17:12:23.189] stderr> Connection to 127.0.0.1 port 2222 timed out
[17:12:23.190] > local-server-2> ssh child died, shutting down
[17:12:23.194] Local server exit: 0
[17:12:23.195] Received install output: local-server-2> Spawned ssh, pid=9815
OpenSSH_8.6p1, LibreSSL 3.3.5
Connection timed out during banner exchange
Connection to 127.0.0.1 port 2222 timed out
local-server-2> ssh child died, shutting down

[17:12:23.196] Resolver error: Error: The connection timed out
	at Function.Offline (/Users/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:586092)
	at /Users/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:583600
	at Object.t.handleInstallOutput (/Users/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:583875)
	at Object.e [as tryInstallWithLocalServer] (/Users/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:625125)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:644162
	at async Object.t.withShowDetailsEvent (/Users/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:647909)
	at async /Users/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:623597
	at async b (/Users/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:620103)
	at async Object.t.resolveWithLocalServer (/Users/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:623212)
	at async Object.t.resolve (/Users/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:645519)
	at async /Users/<redacted>/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:722950
[17:12:23.198] ------
  ```
</details>

**Comment by chrmarti** [comment]
Fixed in v0.231.3 and v0.232.3-pre-release for Remote-Containers.

@thomas-qualia I assume this is the same issue with Remote-SSH. We will continue tracking the underlying issue in #6543.
