### ISSUE TITLE
Wrong fish shell usage when starting container

### ISSUE THREAD

**Issue by meskill** [microsoft/vscode-remote-release#6562]
- VSCode Version: 1.66.0
- Local OS Version: Win 10 Home + WSL 2
- Remote OS Version: alpine 3.14.3
- Remote Extension/Connection Type: Docker
- Remote Extension Version: 0.232.3

Error `fish: Command substitutions not allowed`

<details>
<summary>Logs</summary>
<pre>
[2022-04-05T08:24:47.980Z] Remote-Containers 0.232.3 in VS Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5).
[2022-04-05T08:24:47.980Z] Start: Run: wsl -d alpine -e wslpath -u \\wsl$\alpine\home\meskill\Projects\test\js-ts
[2022-04-05T08:24:48.120Z] Stop (140 ms): Run: wsl -d alpine -e wslpath -u \\wsl$\alpine\home\meskill\Projects\test\js-ts
[2022-04-05T08:24:48.149Z] Start: Resolving Remote
[2022-04-05T08:24:48.154Z] Start: Run: wsl -d alpine -e wslpath -u \\wsl$\alpine\home\meskill\Projects\test\js-ts
[2022-04-05T08:24:48.294Z] Stop (140 ms): Run: wsl -d alpine -e wslpath -u \\wsl$\alpine\home\meskill\Projects\test\js-ts
[2022-04-05T08:24:48.296Z] Start: Run: wsl -d alpine -e /bin/sh -c cd '/home/meskill/Projects/test/js-ts' && /bin/sh
[2022-04-05T08:24:48.299Z] Start: Run in host: id -un
[2022-04-05T08:24:48.331Z] meskill
[2022-04-05T08:24:48.331Z] 
[2022-04-05T08:24:48.331Z] Stop (32 ms): Run in host: id -un
[2022-04-05T08:24:48.331Z] Start: Run in host: cat /etc/passwd
[2022-04-05T08:24:48.332Z] Stop (1 ms): Run in host: cat /etc/passwd
[2022-04-05T08:24:48.333Z] Start: Run in host: echo ~
[2022-04-05T08:24:48.334Z] /home/meskill
[2022-04-05T08:24:48.334Z] 
[2022-04-05T08:24:48.334Z] Stop (1 ms): Run in host: echo ~
[2022-04-05T08:24:48.334Z] Start: Run in host: test -x '/home/meskill/.vscode-remote-containers/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/node'
[2022-04-05T08:24:48.335Z] 
[2022-04-05T08:24:48.335Z] 
[2022-04-05T08:24:48.335Z] Stop (1 ms): Run in host: test -x '/home/meskill/.vscode-remote-containers/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/node'
[2022-04-05T08:24:48.336Z] Start: Run in host: test -f '/home/meskill/.vscode-remote-containers/dist/vscode-remote-containers-server-0.232.3.js'
[2022-04-05T08:24:48.336Z] 
[2022-04-05T08:24:48.337Z] 
[2022-04-05T08:24:48.337Z] Stop (1 ms): Run in host: test -f '/home/meskill/.vscode-remote-containers/dist/vscode-remote-containers-server-0.232.3.js'
[2022-04-05T08:24:48.339Z] userEnvProbe: loginInteractiveShell (default)
[2022-04-05T08:24:48.339Z] userEnvProbe shell: /usr/bin/fish
[2022-04-05T08:24:48.340Z] Start: Run in Host: /usr/bin/fish -lic echo -n e2fc304ae48e4bb93774b3bb518425db; (cat /proc/self/environ || (printenv | tr '\n' '\0')); echo -n e2fc304ae48e4bb93774b3bb518425db
[2022-04-05T08:24:48.408Z] Stop (68 ms): Run in Host: /usr/bin/fish -lic echo -n e2fc304ae48e4bb93774b3bb518425db; (cat /proc/self/environ || (printenv | tr '\n' '\0')); echo -n e2fc304ae48e4bb93774b3bb518425db
[2022-04-05T08:24:48.409Z] e2fc304ae48e4bb93774b3bb518425dbe2fc304ae48e4bb93774b3bb518425db
[2022-04-05T08:24:48.409Z] fish: Command substitutions not allowed
echo -n e2fc304ae48e4bb93774b3bb518425db; (cat /proc/self/environ || (printenv | tr '\n' '\0')); echo -n e2fc304ae48e4bb93774b3bb518425db
                                          ^

[2022-04-05T08:24:48.409Z] userEnvProbe parsed: {}
[2022-04-05T08:24:48.409Z] userEnvProbe PATHs:
Probe:     None
Container: None
[2022-04-05T08:24:48.411Z] Setting up container for folder or workspace: /home/meskill/Projects/test/js-ts
[2022-04-05T08:24:48.452Z] Start: Check Docker is running
[2022-04-05T08:24:48.453Z] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[2022-04-05T08:24:48.484Z] Stop (31 ms): Run in Host: docker version --format {{.Server.APIVersion}}
[2022-04-05T08:24:48.484Z] Server API version: 1.41
[2022-04-05T08:24:48.484Z] Stop (32 ms): Check Docker is running
[2022-04-05T08:24:48.485Z] Start: Run in Host: docker volume ls -q
[2022-04-05T08:24:48.507Z] Stop (22 ms): Run in Host: docker volume ls -q
[2022-04-05T08:24:48.531Z] Start: Run in Host: tar --no-same-owner -x -f -
[2022-04-05T08:24:48.548Z] Stop (17 ms): Run in Host: tar --no-same-owner -x -f -
[2022-04-05T08:24:48.551Z] Start: Run in Host: tar --no-same-owner -x -f -
[2022-04-05T08:24:48.556Z] Stop (5 ms): Run in Host: tar --no-same-owner -x -f -
[2022-04-05T08:24:48.559Z] Start: Run in Host: /home/meskill/.vscode-remote-containers/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/node /home/meskill/.vscode-remote-containers/dist/dev-containers-cli-0.232.3/dist/spec-node/devContainersSpecCLI.js up --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /home/meskill/Projects/test/js-ts --workspace-mount-consistency cached --id-label vsch.local.folder=\\wsl$\alpine\home\meskill\Projects\test\js-ts --id-label vsch.quality=stable --log-level trace --config /home/meskill/Projects/test/js-ts/.devcontainer/devcontainer.json --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-04-05T08:24:48.675Z] remote-containers 0.232.3.
[2022-04-05T08:24:48.675Z] Start: Resolving Remote
[2022-04-05T08:24:48.680Z] Start: Run: git rev-parse --show-cdup
[2022-04-05T08:24:48.685Z] Stop (5 ms): Run: git rev-parse --show-cdup
[2022-04-05T08:24:48.687Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=\\wsl$\alpine\home\meskill\Projects\test\js-ts --filter label=vsch.quality=stable
[2022-04-05T08:24:48.709Z] Stop (22 ms): Run: docker ps -q -a --filter label=vsch.local.folder=\\wsl$\alpine\home\meskill\Projects\test\js-ts --filter label=vsch.quality=stable
[2022-04-05T08:24:48.710Z] Start: Run: docker inspect --type image dev:node
[2022-04-05T08:24:48.734Z] Stop (24 ms): Run: docker inspect --type image dev:node
[2022-04-05T08:24:48.737Z] Start: Run: docker build -f /tmp/vsch/updateUID.Dockerfile-0.232.3 -t vsc-js-ts-2eb56091367ea46d0d6cd32e19143fbf-uid --build-arg BASE_IMAGE=dev:node --build-arg REMOTE_USER=node --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=node /tmp/vsch
[2022-04-05T08:24:48.865Z] Sending build context to Docker daemon  557.1kB

[2022-04-05T08:24:48.885Z] Sending build context to Docker daemon  664.6kB

[2022-04-05T08:24:48.908Z] Step 1/10 : ARG BASE_IMAGE
Step 2/10 : FROM $BASE_IMAGE
[2022-04-05T08:24:48.908Z]  ---> d92becff4a5d
Step 3/10 : USER root
[2022-04-05T08:24:48.908Z]  ---> Using cache
 ---> cde3d18eebb1
Step 4/10 : ARG REMOTE_USER
[2022-04-05T08:24:48.909Z]  ---> Using cache
 ---> cb4506a339ce
Step 5/10 : ARG NEW_UID
[2022-04-05T08:24:48.909Z]  ---> Using cache
 ---> b04cfc51fcc2
Step 6/10 : ARG NEW_GID
[2022-04-05T08:24:48.909Z]  ---> Using cache
 ---> 977ce093e3ee
[2022-04-05T08:24:48.909Z] Step 7/10 : SHELL ["/bin/sh", "-c"]
 ---> Using cache
 ---> 14e3c8eb433c
Step 8/10 : RUN eval $(sed -n "s/${REMOTE_USER}:[^:]*:\([^:]*\):\([^:]*\):[^:]*:\([^:]*\).*/OLD_UID=\1;OLD_GID=\2;HOME_FOLDER=\3/p" /etc/passwd); 	eval $(sed -n "s/\([^:]*\):[^:]*:${NEW_UID}:.*/EXISTING_USER=\1/p" /etc/passwd); 	eval $(sed -n "s/\([^:]*\):[^:]*:${NEW_GID}:.*/EXISTING_GROUP=\1/p" /etc/group); 	if [ -z "$OLD_UID" ]; then 		echo "Remote user not found in /etc/passwd ($REMOTE_USER)."; 	elif [ "$OLD_UID" = "$NEW_UID" -a "$OLD_GID" = "$NEW_GID" ]; then 		echo "UIDs and GIDs are the same ($NEW_UID:$NEW_GID)."; 	elif [ "$OLD_UID" != "$NEW_UID" -a -n "$EXISTING_USER" ]; then 		echo "User with UID exists ($EXISTING_USER=$NEW_UID)."; 	elif [ "$OLD_GID" != "$NEW_GID" -a -n "$EXISTING_GROUP" ]; then 		echo "Group with GID exists ($EXISTING_GROUP=$NEW_GID)."; 	else 		echo "Updating UID:GID from $OLD_UID:$OLD_GID to $NEW_UID:$NEW_GID."; 		sed -i -e "s/\(${REMOTE_USER}:[^:]*:\)[^:]*:[^:]*/\1${NEW_UID}:${NEW_GID}/" /etc/passwd; 		if [ "$OLD_GID" != "$NEW_GID" ]; then 			sed -i -e "s/\([^:]*:[^:]*:\)${OLD_GID}:/\1${NEW_GID}:/" /etc/group; 		fi; 		chown -R $NEW_UID:$NEW_GID $HOME_FOLDER; 	fi;
 ---> Using cache
 ---> 5cf1d3d624cd
[2022-04-05T08:24:48.910Z] Step 9/10 : ARG IMAGE_USER
[2022-04-05T08:24:48.910Z]  ---> Using cache
 ---> daf2ae5f8e6f
Step 10/10 : USER $IMAGE_USER
[2022-04-05T08:24:48.910Z]  ---> Using cache
 ---> 26eab73d8665
[2022-04-05T08:24:48.936Z] Successfully built 26eab73d8665
[2022-04-05T08:24:49.511Z] Successfully tagged vsc-js-ts-2eb56091367ea46d0d6cd32e19143fbf-uid:latest
[2022-04-05T08:24:49.513Z] Stop (776 ms): Run: docker build -f /tmp/vsch/updateUID.Dockerfile-0.232.3 -t vsc-js-ts-2eb56091367ea46d0d6cd32e19143fbf-uid --build-arg BASE_IMAGE=dev:node --build-arg REMOTE_USER=node --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=node /tmp/vsch
[2022-04-05T08:24:49.514Z] Start: Run: docker -v
[2022-04-05T08:24:49.537Z] Stop (23 ms): Run: docker -v
[2022-04-05T08:24:49.537Z] Start: Run: docker events --format {{json .}} --filter event=start
[2022-04-05T08:24:49.540Z] Start: Starting container
[2022-04-05T08:24:49.540Z] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/meskill/Projects/test/js-ts,target=/workspaces/js-ts --mount type=bind,src=/.ssh,dst=/home/node/.ssh --mount type=bind,src=/.wallaby,dst=/home/node/.wallaby --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=\\wsl$\alpine\home\meskill\Projects\test\js-ts -l vsch.quality=stable --entrypoint /bin/sh vsc-js-ts-2eb56091367ea46d0d6cd32e19143fbf-uid -c echo Container started
[2022-04-05T08:24:49.562Z] docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /.ssh.
See 'docker run --help'.
[2022-04-05T08:24:49.563Z] Stop (23 ms): Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/meskill/Projects/test/js-ts,target=/workspaces/js-ts --mount type=bind,src=/.ssh,dst=/home/node/.ssh --mount type=bind,src=/.wallaby,dst=/home/node/.wallaby --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=\\wsl$\alpine\home\meskill\Projects\test\js-ts -l vsch.quality=stable --entrypoint /bin/sh vsc-js-ts-2eb56091367ea46d0d6cd32e19143fbf-uid -c echo Container started
[2022-04-05T08:24:49.564Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=\\wsl$\alpine\home\meskill\Projects\test\js-ts --filter label=vsch.quality=stable
[2022-04-05T08:24:49.566Z] Stop (29 ms): Run: docker events --format {{json .}} --filter event=start
[2022-04-05T08:24:49.586Z] Stop (22 ms): Run: docker ps -q -a --filter label=vsch.local.folder=\\wsl$\alpine\home\meskill\Projects\test\js-ts --filter label=vsch.quality=stable
[2022-04-05T08:24:49.587Z] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/meskill/Projects/test/js-ts,target=/workspaces/js-ts --mount type=bind,src=/.ssh,dst=/home/node/.ssh --mount type=bind,src=/.wallaby,dst=/home/node/.wallaby --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=\\wsl$\alpine\home\meskill\Projects\test\js-ts -l vsch.quality=stable --entrypoint /bin/sh vsc-js-ts-2eb56091367ea46d0d6cd32e19143fbf-uid -c echo Container started
[2022-04-05T08:24:49.587Z] trap "exit 0" 15
[2022-04-05T08:24:49.587Z] exec "$@"
[2022-04-05T08:24:49.587Z] while sleep 1 & wait $!; do :; done -
[2022-04-05T08:24:49.587Z]     at ER (/home/meskill/.vscode-remote-containers/dist/dev-containers-cli-0.232.3/dist/spec-node/devContainersSpecCLI.js:218:986)
[2022-04-05T08:24:49.587Z]     at qw (/home/meskill/.vscode-remote-containers/dist/dev-containers-cli-0.232.3/dist/spec-node/devContainersSpecCLI.js:218:924)
[2022-04-05T08:24:49.587Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-04-05T08:24:49.587Z]     at async RR (/home/meskill/.vscode-remote-containers/dist/dev-containers-cli-0.232.3/dist/spec-node/devContainersSpecCLI.js:223:2024)
[2022-04-05T08:24:49.587Z]     at async Jw (/home/meskill/.vscode-remote-containers/dist/dev-containers-cli-0.232.3/dist/spec-node/devContainersSpecCLI.js:223:3221)
[2022-04-05T08:24:49.588Z]     at async TR (/home/meskill/.vscode-remote-containers/dist/dev-containers-cli-0.232.3/dist/spec-node/devContainersSpecCLI.js:223:13925)
[2022-04-05T08:24:49.588Z]     at async FR (/home/meskill/.vscode-remote-containers/dist/dev-containers-cli-0.232.3/dist/spec-node/devContainersSpecCLI.js:223:13650)
[2022-04-05T08:24:49.590Z] Stop (1031 ms): Run in Host: /home/meskill/.vscode-remote-containers/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/node /home/meskill/.vscode-remote-containers/dist/dev-containers-cli-0.232.3/dist/spec-node/devContainersSpecCLI.js up --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /home/meskill/Projects/test/js-ts --workspace-mount-consistency cached --id-label vsch.local.folder=\\wsl$\alpine\home\meskill\Projects\test\js-ts --id-label vsch.quality=stable --log-level trace --config /home/meskill/Projects/test/js-ts/.devcontainer/devcontainer.json --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-04-05T08:24:49.590Z] Exit code 1
[2022-04-05T08:24:49.593Z] Command failed: /home/meskill/.vscode-remote-containers/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/node /home/meskill/.vscode-remote-containers/dist/dev-containers-cli-0.232.3/dist/spec-node/devContainersSpecCLI.js up --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /home/meskill/Projects/test/js-ts --workspace-mount-consistency cached --id-label vsch.local.folder=\\wsl$\alpine\home\meskill\Projects\test\js-ts --id-label vsch.quality=stable --log-level trace --config /home/meskill/Projects/test/js-ts/.devcontainer/devcontainer.json --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-04-05T08:24:49.593Z] Exit code 1
[2022-04-05T08:24:54.810Z] Start: Run: wsl -d alpine -e wslpath -u \\wsl$\alpine\home\meskill\Projects\test\js-ts
[2022-04-05T08:24:55.006Z] Stop (196 ms): Run: wsl -d alpine -e wslpath -u \\wsl$\alpine\home\meskill\Projects\test\js-ts

</pre>
</details>

Steps to Reproduce:

1. Specify devcontainer.json with some usage of `localEnv` substitution
2. Execute `Rebuild and Reopen in Container` to start build

Probably, there should not be any brackets arround theres commands for fish
`echo -n e2fc304ae48e4bb93774b3bb518425db; (cat /proc/self/environ || (printenv | tr '\n' '\0')); echo -n e2fc304ae48e4bb93774b3bb518425db` -> `echo -n e2fc304ae48e4bb93774b3bb518425db; cat /proc/self/environ || printenv | tr '\n' '\0'; echo -n e2fc304ae48e4bb93774b3bb518425db`

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by linhmtran168** [comment]
@chrmarti Continue from #6555. It's likely the same problem. I attached the logs file with trace level logging below:
* remote-container 0.231.1 when it's still working: [remoteContainers-2022-04-06T02-37-09.070Z.log](https://github.com/microsoft/vscode-remote-release/files/8423146/remoteContainers-2022-04-06T02-37-09.070Z.log)
* remote-container 0.231.2 when the problem happens: [remoteContainers-2022-04-06T02-29-54.789Z.log](https://github.com/microsoft/vscode-remote-release/files/8423160/remoteContainers-2022-04-06T02-29-54.789Z.log)

**Comment by chrmarti** [comment]
Fixed in v0.231.4 and v0.232.4-pre-release.
