### ISSUE TITLE
Generated docker-compose file is invalid because "volumes contains an invalid type, it should be a string"

### ISSUE THREAD

**Issue by kyrofa** [microsoft/vscode-remote-release#6568]
- VSCode Version: 1.66.0
- Local OS Version: Ubuntu 18.04 (Bionic)
- Remote OS Version: Ubuntu 20.04 (Focal)
- Remote Extension/Connection Type: docker-compose
- Logs:

```
[2022-04-05T22:11:09.071Z] Start: Run: docker -v
[2022-04-05T22:11:09.098Z] Stop (27 ms): Run: docker -v
[2022-04-05T22:11:09.098Z] Start: Run: docker events --format {{json .}} --filter event=start
[2022-04-05T22:11:09.101Z] Start: Run: docker-compose --project-name projectname -f /home/kyrofa/src/project/docker-compose.yml -f /home/kyrofa/src/project/docker-compose.override.yml -f /home/kyrofa/src/project/.devcontainer/docker-compose.yml build dev
[2022-04-05T22:11:09.320Z] WARNING: The BUILD_TAG variable is not set. Defaulting to a blank string.
[2022-04-05T22:11:09.328Z] dev uses an image, skipping
[2022-04-05T22:11:09.348Z] Stop (247 ms): Run: docker-compose --project-name projectname -f /home/kyrofa/src/project/docker-compose.yml -f /home/kyrofa/src/project/docker-compose.override.yml -f /home/kyrofa/src/project/.devcontainer/docker-compose.yml build dev
[2022-04-05T22:11:09.348Z] PersistedPath=/tmp, ContainerHasLabels=false
[2022-04-05T22:11:09.348Z] Generating composeOverrideFile...
[2022-04-05T22:11:09.351Z] Writing docker-compose.devcontainer.containerFeatures-1649196669351.yml to /tmp/docker-compose
[2022-04-05T22:11:09.352Z] Start: Run: docker-compose --project-name projectname -f /home/kyrofa/src/project/docker-compose.yml -f /home/kyrofa/src/project/docker-compose.override.yml -f /home/kyrofa/src/project/.devcontainer/docker-compose.yml -f /tmp/docker-compose/docker-compose.devcontainer.containerFeatures-1649196669351.yml up -d dev
[2022-04-05T22:11:09.571Z] WARNING: The BUILD_TAG variable is not set. Defaulting to a blank string.
[2022-04-05T22:11:09.578Z] ERROR: The Compose file '/tmp/docker-compose/docker-compose.devcontainer.containerFeatures-1649196669351.yml' is invalid because:
services.dev.volumes contains an invalid type, it should be a string
[2022-04-05T22:11:09.598Z] Stop (246 ms): Run: docker-compose --project-name projectname -f /home/kyrofa/src/project/docker-compose.yml -f /home/kyrofa/src/project/docker-compose.override.yml -f /home/kyrofa/src/project/.devcontainer/docker-compose.yml -f /tmp/docker-compose/docker-compose.devcontainer.containerFeatures-1649196669351.yml up -d dev
[2022-04-05T22:11:09.599Z] Error: Command failed: docker-compose --project-name projectname -f /home/kyrofa/src/project/docker-compose.yml -f /home/kyrofa/src/project/docker-compose.override.yml -f /home/kyrofa/src/project/.devcontainer/docker-compose.yml -f /tmp/docker-compose/docker-compose.devcontainer.containerFeatures-1649196669351.yml up -d dev
[2022-04-05T22:11:09.599Z]     at dR (/home/kyrofa/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.3/dist/spec-node/devContainersSpecCLI.js:182:619)
[2022-04-05T22:11:09.599Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-04-05T22:11:09.599Z]     at async hR (/home/kyrofa/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.3/dist/spec-node/devContainersSpecCLI.js:178:2075)
[2022-04-05T22:11:09.599Z]     at async RR (/home/kyrofa/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.3/dist/spec-node/devContainersSpecCLI.js:223:2195)
[2022-04-05T22:11:09.600Z]     at async Jw (/home/kyrofa/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.3/dist/spec-node/devContainersSpecCLI.js:223:3221)
[2022-04-05T22:11:09.600Z]     at async TR (/home/kyrofa/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.3/dist/spec-node/devContainersSpecCLI.js:223:13925)
[2022-04-05T22:11:09.600Z]     at async FR (/home/kyrofa/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.3/dist/spec-node/devContainersSpecCLI.js:223:13650)
[2022-04-05T22:11:09.604Z] Stop (1190 ms): Run: /snap/code/92/usr/share/code/code /home/kyrofa/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.3/dist/spec-node/devContainersSpecCLI.js up --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /home/kyrofa/src/project --workspace-mount-consistency cached --id-label vsch.local.folder=/home/kyrofa/src/project --id-label vsch.quality=stable --log-level debug --config /home/kyrofa/src/project/.devcontainer/devcontainer.json --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-04-05T22:11:09.604Z] Exit code 1
[2022-04-05T22:11:09.606Z] Command failed: /snap/code/92/usr/share/code/code /home/kyrofa/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.3/dist/spec-node/devContainersSpecCLI.js up --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /home/kyrofa/src/project --workspace-mount-consistency cached --id-label vsch.local.folder=/home/kyrofa/src/project --id-label vsch.quality=stable --log-level debug --config /home/kyrofa/src/project/.devcontainer/devcontainer.json --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-04-05T22:11:09.606Z] Exit code 1
```

Steps to Reproduce:

1. Open a project with a dev container configuration file
2. Click the "reopen in container" button that pops up

This has been my workflow for a year or so, but it's not working today with that ^ error, for _all_ my projects. Here is the generated compose file:

```
version: '2'

services:
  'dev':
    entrypoint: ["/bin/sh", "-c", "echo Container started\n
trap \"exit 0\" 15\n
\n
exec \"$$@\"\n
while sleep 1 & wait $$!; do :; done", "-", "bin/wrap_dev_container"]
    labels:
      - vsch.local.folder=/home/kyrofa/src/project
      - vsch.quality=stable
    volumes:
      - type: volume
        source: vscode
        target: /vscode
volumes:
  vscode:
    external: true
```

Note that all my compose files are using version '2', but that ^ looks like v3.2 syntax, no?

**Comment by ilaripih** [comment]
Had the same issue. Worked around it by changing the version in my docker-compose file to '3.2'. But looks definitely like a bug in the vscode extension as it's generating v3.2+ syntax but not changing the version in the Compose file.

**Comment by chrmarti** [comment]
I think the override file is required to have the same version as the base config. We might have use the older syntax in this case.

**Comment by kyrofa** [comment]
Ah, that makes this a smidge more difficult then, eh? But that is of course a perfectly acceptable solution as well.

**Comment by chrmarti** [comment]
The older syntax seems to work fine with the newer versions. We used to use that and only recently switched, reverting that.
