### ISSUE TITLE
Python/Jupyter pre-release extension installation fails on Remote SSH

### ISSUE THREAD

**Issue by firegate22** [microsoft/vscode-remote-release#6575]
- VSCode Version: 
Version: 1.67.0-insider (Universal)
Commit: f050b17dacedba13962244b13c70084a473d08f7
Date: 2022-04-06T05:15:27.397Z (8 hrs ago)
- Local OS Version: macOs 12.3.1 / arm
- Remote OS Version: Centos 7
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. Start SSH Session
2. Get the popup, hey Python and Jupyter extensions have pre-release versions 
3.  Error (but the extensions shows the pre-release state), but afaik that's not the case 

Can't install pre-release version of 'ms-toolsai.jupyter' extension because it is not compatible with the current version of Visual Studio Code - Insiders (version 1.67.0-insider).

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?:No

logs: 
[2022-04-06 15:51:45.599] [renderer1] [info] Downloading the 'ms-toolsai.jupyter' extension locally and install
[2022-04-06 15:51:45.626] [renderer1] [error] Can't install pre-release version of 'ms-toolsai.jupyter' extension because it is not compatible with the current version of Visual Studio Code - Insiders (version 1.67.0-insider).: IncompatiblePreRelease: Can't install pre-release version of 'ms-toolsai.jupyter' extension because it is not compatible with the current version of Visual Studio Code - Insiders (version 1.67.0-insider).
    at l.checkAndGetCompatible (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3132:5311)
    at async l.downloadAndInstall (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3132:4068)
    at async l.installFromGallery (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3132:3238)
    at async Promise.all (index 0)
    at async Object.j [as settled] (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:71:22545)
    at async Ms.installFromGallery (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3126:22894)

**Comment by tanhakabir** [comment]
Would you mind sharing your Remote SSH logs as well? https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues

And if you have any gifs or videos of what you're seeing?

**Comment by firegate22** [comment]
![image](https://user-images.githubusercontent.com/37472736/162134420-8bf146ed-50d6-4ac8-8be9-21dfbc1af69a.png)
![image](https://user-images.githubusercontent.com/37472736/162134498-f60942f2-9443-49f5-ad0b-67f69eb08dca.png)

And this - but it's just a "refresh" problem, once I switch between extensions it shows the old and unfortunately correct version again:
![image](https://user-images.githubusercontent.com/37472736/162134575-5f3f8669-c8d3-4bc9-8347-b45812147591.png)

And logs...
`[08:28:55.346] Log Level: 2
[08:28:55.347] remote-ssh@0.79.2022040616
[08:28:55.347] darwin arm64
[08:28:55.357] SSH Resolver called for "ssh-remote+SSH_HOST", attempt 1
[08:28:55.357] "remote.SSH.useLocalServer": true
[08:28:55.358] "remote.SSH.path": undefined
[08:28:55.359] "remote.SSH.configFile": undefined
[08:28:55.359] "remote.SSH.useFlock": true
[08:28:55.359] "remote.SSH.lockfilesInTmp": true
[08:28:55.359] "remote.SSH.localServerDownload": always
[08:28:55.359] "remote.SSH.remoteServerListenOnSocket": false
[08:28:55.359] "remote.SSH.showLoginTerminal": false
[08:28:55.359] "remote.SSH.defaultExtensions": []
[08:28:55.359] "remote.SSH.loglevel": 2
[08:28:55.359] "remote.SSH.enableDynamicForwarding": true
[08:28:55.359] "remote.SSH.enableRemoteCommand": false
[08:28:55.360] "remote.SSH.serverPickPortsFromRange": {}
[08:28:55.360] "remote.SSH.serverInstallPath": {}
[08:28:55.364] SSH Resolver called for host: SSH_HOST
[08:28:55.364] Setting up SSH remote "SSH_HOST"
[08:28:55.366] Acquiring local install lock: /var/folders/lt/znpb3_c14gl0qvwjyqbjwy2rgbypsc/T/vscode-remote-ssh-edf44c9a-install.lock
[08:28:55.370] Looking for existing server data file at /Users/USER/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-edf44c9a-f050b17dacedba13962244b13c70084a473d08f7-0.79.2022040616/data.json
[08:28:55.372] Using commit id "f050b17dacedba13962244b13c70084a473d08f7" and quality "insider" for server
[08:28:55.374] Install and start server if needed
[08:28:55.376] PATH: /opt/homebrew/opt/openjdk/bin:/Applications/Oracle/instantclient_19_8::/Users/USER/.pyenv/plugins/pyenv-virtualenv/shims:/Users/USER/.pyenv/plugins/pyenv-virtualenv/shims:/Users/USER/.pyenv/shims:/Users/USER/.pyenv/bin:/opt/homebrew/opt/openssl@1.1/bin:/Users/USER/.nvm/versions/node/v17.4.0/bin:opt/homebrew/share/emacs/site-lisp/cmake:/Users/USER/.jenv/shims:/Users/USER/.jenv/bin:/opt/homebrew/Caskroom/miniforge/base/bin:/opt/homebrew/Caskroom/miniforge/base/condabin:/Users/USER/bin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/hadoop/bin:/opt/homebrew/Cellar/maven/3.8.1/bin
[08:28:55.376] Checking ssh with "ssh -V"
[08:28:55.389] > OpenSSH_8.6p1, LibreSSL 3.3.5

[08:28:55.391] askpass server listening on /var/folders/lt/znpb3_c14gl0qvwjyqbjwy2rgbypsc/T/vscode-ssh-askpass-8f5feb1801474839ddcbdbae0f8b066a229b78b0.sock
[08:28:55.392] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/lt/znpb3_c14gl0qvwjyqbjwy2rgbypsc/T/vscode-ssh-askpass-3db96e84b375c37d373823f7c73341dd6d7d267a.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","54546","-o","ConnectTimeout=15","SSH_HOST","bash"],"serverDataFolderName":".vscode-server-insiders","dataFilePath":"/Users/USER/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-edf44c9a-f050b17dacedba13962244b13c70084a473d08f7-0.79.2022040616/data.json"}
[08:28:55.392] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.hRtpZI662n/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/USER/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.79.2022040616/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/USER/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.79.2022040616/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/lt/znpb3_c14gl0qvwjyqbjwy2rgbypsc/T/vscode-ssh-askpass-8f5feb1801474839ddcbdbae0f8b066a229b78b0.sock"}
[08:28:55.392] Spawned 1886
[08:28:55.481] > local-server-1> Spawned ssh, pid=1909
[08:28:55.483] stderr> OpenSSH_8.6p1, LibreSSL 3.3.5
[08:28:55.696] stderr> debug1: Server host key: ####
[08:28:55.960] stderr> Authenticated to SSH_HOST ([SECRET_IP2]:22).
[08:28:56.836] > ready: 700034d43890
[08:28:56.867] > Linux 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022
[08:28:56.870] Platform: linux
[08:28:56.907] > /bin/bash
[08:28:56.907] Shell: bash
[08:28:56.907] Creating bash subshell inside "bash"
[08:28:56.939] > bash version:  4.2.46(2)-release
[08:28:57.011] > 700034d43890: running
[08:28:57.042] > Acquiring lock on /run/user/1871260745/vscode-remote-lock.USER.f050b17dacedba13962244b13c70084a473d08f7
[08:28:57.045] > Found existing installation at /home/USER/.vscode-server-insiders/bin/f050b17dacedba13962244b13c70084a473d08f7...
> Checking /home/USER/.vscode-server-insiders/.f050b17dacedba13962244b13c70084a473d08f7.log and /home/USER/.vscode-server-insiders/.f050b17dacedba13962244b13c70084a473d08f7.pid for a running server
[08:28:57.051] > Looking for server with pid: 28923
[08:28:57.152] > Starting server with command... /home/USER/.vscode-server-insiders/bin/f050b17dacedba13962244b13c70084a473d08f7/bin/code-server-insiders --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level off   &> "/home/USER/.vscode-server-insiders/.f050b17dacedba13962244b13c70084a473d08f7.log" < /dev/null
> printenv:
[08:28:57.153] >     XDG_SESSION_ID=18135

[08:28:57.161] > Removing old logfile at /home/USER/.vscode-server-insiders/.f050b17dacedba13962244b13c70084a473d08f7.log
[08:28:57.166] > Spawned remote server: 4770
[08:28:57.179] > Waiting for server log...
[08:28:57.201] > Waiting for server log...
[08:28:57.252] >  
> *
[08:28:57.256] > * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
[08:28:57.256] > *
>  
[08:28:57.259] > 700034d43890: start
[08:28:57.259] > SSH_AUTH_SOCK====
> DISPLAY====
> webUiAccessToken====
> listeningOn==37004==
> osReleaseId==centos==
> arch==x86_64==
[08:28:57.262] > tmpDir==/run/user/1871260745==
> platform==linux==
> unpackResult====
[08:28:57.279] > didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==83==
> connectionToken==1a1a1a11-11aa-11aa-a1a1-a1aaa11aa1a1==
> 700034d43890: end
[08:28:57.279] Received install output: SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==37004==
osReleaseId==centos==
arch==x86_64==tmpDir==/run/user/1871260745==
platform==linux==
unpackResult====didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==83==
connectionToken==1a1a1a11-11aa-11aa-a1a1-a1aaa11aa1a1==

[08:28:57.280] Remote server is listening on 37004
[08:28:57.280] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":37004},"osReleaseId":"centos","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/1871260745","platform":"linux","connectionToken":"1a1a1a11-11aa-11aa-a1a1-a1aaa11aa1a1"},"serverStartTime":83,"installUnpackCode":""}
[08:28:57.281] Persisting server connection details to /Users/USER/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-edf44c9a-f050b17dacedba13962244b13c70084a473d08f7-0.79.2022040616/data.json
[08:28:57.285] Starting forwarding server. localPort 54549 -> socksPort 54546 -> remotePort 37004
[08:28:57.285] Forwarding server listening on 54549
[08:28:57.285] Waiting for ssh tunnel to be ready
[08:28:57.286] Tunneled 37004 to local port 54549
[08:28:57.286] Resolved "ssh-remote+SSH_HOST" to "127.0.0.1:54549"
[08:28:57.287] [Forwarding server 54549] Got connection 0
[08:28:57.294] ------




[08:28:57.310] [Forwarding server 54549] Got connection 1
[08:28:57.435] [Forwarding server 54549] Got connection 2
[08:28:59.490] [Forwarding server 54549] Got connection 3
[08:28:59.491] [Forwarding server 54549] Got connection 4
[08:28:59.491] [Forwarding server 54549] Got connection 5
[08:28:59.491] [Forwarding server 54549] Got connection 6
`

**Comment by tanhakabir** [comment]
Your SSH connection looks successful. I'll transfer this issue to the Python extension team to see if they have ideas why this state is happening
