### ISSUE TITLE
Error: Server[1] disconnected unexpectedly when typing anything in the Python debug console while debugging

### ISSUE THREAD

**Issue by Alexander-Wilms** [microsoft/vscode-remote-release#6577]
Issue Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Expected: I can use the debug console to run python commands
Actual: The debugger crashes as soon as I type anything into the debug console

## Steps to reproduce:

1. Set breakpoint
2. Debug Python File
3.  Execution stops at breakpoint
4. Type anything into the debug console

Help > Toggle Developer Tools > Console shows the following

```
  ERR Server[1] disconnected unexpectedly: Error: Server[1] disconnected unexpectedly
    at s.handleErrorResponse (vscode-file://vscode-app/c:/Users/Username/AppData/Local/Programs/Microsoft%…20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1024:44858)
    at vscode-file://vscode-app/c:/Users/Username/AppData/Local/Programs/Microsoft%…20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1024:44287
    at async Object.provideCompletionItems (vscode-file://vscode-app/c:/Users/Username/AppData/Local/Programs/Microsoft%…%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2241:5237)
    at async vscode-file://vscode-app/c:/Users/Username/AppData/Local/Programs/Microsoft%…%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:690:15785
    at async Promise.all (index 0)
    at async m (vscode-file://vscode-app/c:/Users/Username/AppData/Local/Programs/Microsoft%…%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:690:15657)
    at async Promise.all (index 0)
```

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.1
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: false
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "autopep8"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: false
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: true
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2022.4.0
VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.67GB free)|
|Process Argv|C:\\Users\\WilmsFA\\Tools\\Eigene\\silworx_sst_import\\silworx_sst_import.py --crash-reporter-id 1d44524e-2551-4c95-b981-53e1119f2c52|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by tanhakabir** [comment]
@karthiknadig which remote extension is this relevant to?

**Comment by Alexander-Wilms** [comment]
I was trying to debug a local Python script using Python 3.10.1 (I tried 3.10.4 as well) installed in `C:\Users\Username\AppData\Local\Programs\Python\Python310`. I've disabled all other extensions but Python v2022.4.0.
I set a breakpoint and clicked Run > Start debugging. Once the breakpoint was reached, the debugger stopped the execution and listed the variables as well as the call stack. I clicked on the debug console tab, entered one to ten letters and the debugging session ended. When I entered the letters before the breakpoint had been reached, nothing happened.
