### ISSUE TITLE
Remote attach to container in kubernetes stops working after opening a folder

### ISSUE THREAD

**Issue by pete-vivacity** [microsoft/vscode-remote-release#6582]
- VSCode Version: 1.66.0
- Local OS Version: Linux 5.13.0
- Remote OS Version: Linux 5.10.68
- Remote Extension/Connection Type: Docker
- Logs:

```
INFO Ignoring configured affinity for 'pub.name' because the extension is unknown or cannot execute.
workbench.desktop.main.js:sourcemap:610  INFO Invoking resolveAuthority(k8s-container)
workbench.desktop.main.js:sourcemap:610  INFO resolveAuthority(k8s-container) returned '127.0.0.1:39793' after 14662 ms
workbench.desktop.main.js:sourcemap:610   ERR [remote-connection][Management   ][24dda…][initial][127.0.0.1:39793] received error control message when negotiating connection. Error:
workbench.desktop.main.js:sourcemap:610   ERR Error: Connection error: Unauthorized client refused: auth mismatch
    at V (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:55705)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:43257
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at u.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:19607)
    at g._receiveMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:24238)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:21722
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at s.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:16438)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:15568
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:40443
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at FileReader._fileReader.onload (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:38374)
workbench.desktop.main.js:sourcemap:610   ERR [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
3workbench.desktop.main.js:sourcemap:610   ERR Error: Connection error: Unauthorized client refused: auth mismatch
    at V (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:55705)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:43257
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at u.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:19607)
    at g._receiveMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:24238)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:21722
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at s.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:16438)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:15568
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:40443
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at FileReader._fileReader.onload (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:38374)
workbench.desktop.main.js:sourcemap:610   ERR Cannot register remote filesystem provider. Error while fetching remote environment. Connection error: Unauthorized client refused: auth mismatch
workbench.desktop.main.js:sourcemap:796 Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused: auth mismatch)
onDidChangeNotification @ workbench.desktop.main.js:sourcemap:796
workbench.desktop.main.js:sourcemap:610   ERR Error: Connection error: Unauthorized client refused: auth mismatch
    at V (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:55705)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:43257
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at u.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:19607)
    at g._receiveMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:24238)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:21722
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at s.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:16438)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:15568
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:40443
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at FileReader._fileReader.onload (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:38374)
workbench.desktop.main.js:sourcemap:796 Could not fetch remote environment
onDidChangeNotification @ workbench.desktop.main.js:sourcemap:796
workbench.desktop.main.js:sourcemap:610  WARN Ignoring the error while validating workspace folder vscode-remote://k8s-container%2Bcontext%3D<<CLUSTER>>%2Bpodname%3D<<POD>>%2Bnamespace%3Dinstation%2Bname%3D<<CONTAINER>>%2Bimage%3Deu.gcr.io%252f<<REPO>> - No file system provider found for resource 'vscode-remote://k8s-container%2Bcontext%3D<<CLUSTER>>%2Bpodname%3D<<POD>>%2Bnamespace%3Dinstation%2Bname%3D<<CONTAINER>>%2Bimage%3Deu.gcr.io%252f<<REPO>>'
workbench.desktop.main.js:sourcemap:610   ERR ENOPRO: No file system provider found for resource 'vscode-remote://k8s-container%2Bcontext%3D<<CLUSTER>>%2Bpodname%3D<<POD>>%2Bnamespace%3Dinstation%2Bname%3D<<CONTAINER>>%2Bimage%3Deu.gcr.io%252f<<REPO>>'
    at p.withProvider (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:27776)
    at async p.doWatch (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:41538)
    at async vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:41404
workbench.desktop.main.js:sourcemap:610   ERR No file system provider found for resource 'vscode-remote://k8s-container%2Bcontext%3D<<CLUSTER>>%2Bpodname%3D<<POD>>%2Bnamespace%3Dinstation%2Bname%3D<<CONTAINER>>%2Bimage%3Deu.gcr.io%252f<<REPO>>/.git/config': ENOPRO: No file system provider found for resource 'vscode-remote://k8s-container%2Bcontext%3D<<CLUSTER>>%2Bpodname%3D<<POD>>%2Bnamespace%3Dinstation%2Bname%3D<<CONTAINER>>%2Bimage%3Deu.gcr.io%252f<<REPO>>/.git/config'
    at p.withProvider (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:27776)
    at async p.exists (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:30371)
    at async Promise.all (index 0)
workbench.desktop.main.js:sourcemap:610  INFO Ignoring configured affinity for 'pub.name' because the extension is unknown or cannot execute.
workbench.desktop.main.js:sourcemap:610   ERR No file system provider found for resource 'vscode-remote://k8s-container%2Bcontext%3D<<CLUSTER>>%2Bpodname%3D<<POD>>%2Bnamespace%3Dinstation%2Bname%3D<<CONTAINER>>%2Bimage%3Deu.gcr.io%252f<<REPO>>/pom.xml': ENOPRO: No file system provider found for resource 'vscode-remote://k8s-container%2Bcontext%3D<<CLUSTER>>%2Bpodname%3D<<POD>>%2Bnamespace%3Dinstation%2Bname%3D<<CONTAINER>>%2Bimage%3Deu.gcr.io%252f<<REPO>>/pom.xml'
    at p.withProvider (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:27776)
    at async p.exists (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:30371)
    at async Promise.all (index 0)
workbench.desktop.main.js:sourcemap:610   ERR Connection error: Unauthorized client refused: auth mismatch: Error: Connection error: Unauthorized client refused: auth mismatch
    at V (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:55705)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:43257
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at u.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:19607)
    at g._receiveMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:24238)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:21722
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at s.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:16438)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:15568
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:40443
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at FileReader._fileReader.onload (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:38374)
workbench.desktop.main.js:sourcemap:610   ERR No file system provider found for resource 'vscode-remote://k8s-container%2Bcontext%3D<<CLUSTER>>%2Bpodname%3D<<POD>>%2Bnamespace%3Dinstation%2Bname%3D<<CONTAINER>>%2Bimage%3Deu.gcr.io%252f<<REPO>>': ENOPRO: No file system provider found for resource 'vscode-remote://k8s-container%2Bcontext%3D<<CLUSTER>>%2Bpodname%3D<<POD>>%2Bnamespace%3Dinstation%2Bname%3D<<CONTAINER>>%2Bimage%3Deu.gcr.io%252f<<REPO>>'
    at p.withProvider (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:27776)
    at async p.doResolveFile (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:28858)
    at async p.resolve (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:28581)
    at async i.findWorkspaces (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1947:6441)
workbench.desktop.main.js:sourcemap:610   ERR Connection error: Unauthorized client refused: auth mismatch: Error: Connection error: Unauthorized client refused: auth mismatch
    at V (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:55705)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:43257
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at u.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:19607)
    at g._receiveMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:24238)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:21722
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at s.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:16438)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:15568
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:40443
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at FileReader._fileReader.onload (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:38374)
workbench.desktop.main.js:sourcemap:610   ERR Error: Connection error: Unauthorized client refused: auth mismatch
    at V (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:55705)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:43257
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at u.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:19607)
    at g._receiveMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:24238)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:21722
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at s.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:16438)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:15568
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:40443
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at FileReader._fileReader.onload (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:38374)
workbench.desktop.main.js:sourcemap:610   ERR [remote-connection][ExtensionHost][d5ef3…][initial][127.0.0.1:39793] received error control message when negotiating connection. Error:
workbench.desktop.main.js:sourcemap:610   ERR Error: Connection error: Unauthorized client refused: auth mismatch
    at V (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:55705)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:43257
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at u.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:19607)
    at g._receiveMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:24238)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:21722
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at s.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:16438)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:15568
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:40443
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at FileReader._fileReader.onload (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:38374)
workbench.desktop.main.js:sourcemap:610   ERR [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
workbench.desktop.main.js:sourcemap:610   ERR Error: Connection error: Unauthorized client refused: auth mismatch
    at V (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:55705)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:43257
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at u.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:19607)
    at g._receiveMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:24238)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:21722
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at s.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:16438)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:15568
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:40443
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at FileReader._fileReader.onload (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:38374)
workbench.desktop.main.js:sourcemap:610   ERR Error received from starting extension host (kind: Remote)
workbench.desktop.main.js:sourcemap:610   ERR Error: Connection error: Unauthorized client refused: auth mismatch
    at V (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:55705)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:43257
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at u.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:19607)
    at g._receiveMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:24238)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:21722
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at s.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:16438)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:15568
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:40443
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at FileReader._fileReader.onload (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:38374)
workbench.desktop.main.js:sourcemap:610   ERR Connection error: Unauthorized client refused: auth mismatch: Error: Connection error: Unauthorized client refused: auth mismatch
    at V (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:55705)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:43257
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at u.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:19607)
    at g._receiveMessage (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:24238)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:21722
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at s.acceptChunk (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:16438)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:83:15568
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:40443
    at S.invoke (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.fire (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1856)
    at FileReader._fileReader.onload (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:38374)

```
Steps to Reproduce:

1. Connect to a container in a kubernetes cluster and wait for new window for the remote connection
2. Observe that everything appears to be working fine, vscode-server gets installed, processes appear on the remote host, ports get forwarded etc.
3. Click "Open folder" and navigate the dropdown with the correct folders from the remote host, choose a folder.
4. Get error notifications and the above log in the console, observe that nothing works.

**Comment by pete-vivacity** [comment]
This might be a duplicate of https://github.com/microsoft/vscode-remote-release/issues/6578

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-remote-release/issues/6578. Thanks.
