### ISSUE TITLE
Remote Container Stuck

### ISSUE THREAD

**Issue by vishalovercome** [microsoft/vscode-remote-release#6601]
I upgraded vscode as well as extensions and now my devcontainer is "stuck". By stuck I mean that while the postStart command works and extensions get installed, there's nothing I can do after that - can't type in a file, vscode is constanly trying to "activate extensions". I'm not sure how to debug this so I'll share whatever logs I was able to find:

`2022-04-11 21:18:50.464] [exthost] [error] [ms-vscode-remote.remote-containers] provider FAILED
[2022-04-11 21:18:50.468] [exthost] [error] Error: Unsupported scheme: vscode-remote://dev-container%2B7b22686f737450617468223a222f686f6d652f7562756e74752f73696e676c652d646174612d706970656c696e65222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22686f7374223a227373683a2f2f72656d6f74652d646f636b65722d646576227d7d/workspaces/PROJECT/Dockerfile
	at aO.readDocument (/Users/vishal/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.5/dist/extension/extension.js:363:242)
	at i_ (/Users/vishal/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.5/dist/extension/extension.js:384:32631)
	at s_ (/Users/vishal/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.5/dist/extension/extension.js:384:35266)
	at Vce (/Users/vishal/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.5/dist/extension/extension.js:384:39200)
	at Object.provideCompletionItems (/Users/vishal/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.5/dist/extension/extension.js:384:38108)
	at X.provideCompletionItems (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:108946)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:132923
	at Q._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:123100)
	at Q.$provideCompletionItems (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:132899)
	at i._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:13826)
	at i._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:13510)
	at i._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:12119)
	at i._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:10841)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:8947
	at u.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19034)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:34275
	at u.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19034)
	at o._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:23615)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:21149
	at u.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
	at v.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:15865)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:14995
	at Socket.P (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:13797)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)`

- VSCode Version: 1.66
- Local OS Version: MacOS Monterey
- Remote OS Version: Ubuntu 20.04 (container)
- Remote Extension/Connection Type: Docker
- Logs:

Does this issue occur when you try this locally and all extensions are disabled?: The command to disable all extensions doesn't seem to work. Perhaps because VSCode is stuck

![Screenshot 2022-04-11 at 9 28 00 PM](https://user-images.githubusercontent.com/50405519/162785167-87ab6490-1971-424f-9584-cb1e0ea0adec.png)
![Screenshot 2022-04-11 at 9 41 38 PM](https://user-images.githubusercontent.com/50405519/162785175-7de11886-2114-4bd6-a192-dae6c5d62e13.png)

**Comment by vishalovercome** [comment]
I've tried this out with version 0.231.5 and 0.232.5 of remote containers extension

**Comment by chrmarti** [comment]
Could you append the dev container log too? (`F1` > `Remote-Containers: Show Container Log`)

**Comment by vishalovercome** [comment]
Because the container is in this "stuck" state, "show container log" doesn't do anything.

**Comment by chrmarti** [comment]
Could you retry with the latest insiders build (that has a fix for reconnection)? https://code.visualstudio.com/insiders/
Are you connecting through an SSH server?

**Comment by vishalovercome** [comment]
Thanks for your reply. I will try but can you explain what has been going on with this extension's code? It was more or less flawless last year but has stopped working all of a sudden? First cloning stopped working and reopening the container started working. Now the latter has stopped working. I have created #6664 for tracking that issue. I'm reluctant to try as this extension has disrupted my workflow very severely this year at least 4 times

**Comment by chrmarti** [comment]
Sorry to hear that. We have refactored the code to support connecting through an SSH server and also for some upcoming changes. These refactorings might have introduced bugs that we have been fixing since. Let us know when you see additional issues come up, if possible with the version number of Remote-Containers that introduced it. Thanks!

**Comment by vishalovercome** [comment]
I'm using v0.233 of the extension

**Comment by vishalovercome** [comment]
It turns out that there's a node process that consumes a lot of CPU for about 15 minutes after which the IDE becomes usable. I tried to figure out what that process was and this is the output of ps command (74355 is the PID of the node command) 

root       74355     241 99 16:09 ?        00:00:47 /vscode/vscode-server/bin/linux-x64/dfd34e8260c270da74b5c2d86d61aee4b6d56977/node /vscode/vscode-server/bin/linux-x64/dfd34e8260c270da74b5c2d86d61aee4b6d56977/out/bootstrap-fork --type=extensionHost --transformURIs --useHostProxy=false
root       74470   74355  0 16:09 ?        00:00:00 /vscode/vscode-server/bin/linux-x64/dfd34e8260c270da74b5c2d86d61aee4b6d56977/node /root/.vscode-server/extensions/mtxr.sqltools-0.23.0/dist/languageserver.js --node-ipc --clientProcessId=74355
root       74477   74355  1 16:09 ?        00:00:00 /vscode/vscode-server/bin/linux-x64/dfd34e8260c270da74b5c2d86d61aee4b6d56977/node /root/.vscode-server/extensions/redhat.vscode-yaml-1.7.0/dist/languageserver.js --node-ipc --clientProcessId=74355
root       74664   74355 41 16:09 ?        00:00:14 /opt/java/openjdk/bin/java -Xss4m -Xms100m -Dmetals.client=vscode -XX:+UnlockExperimentalVMOptions -XX:MaxRAM=3584m -XX:MaxInlineLevel=20 -XX:NativeMemoryTracking=detail -Xmx1G -classpath A_WHOLE_BUNCH_OF_JAVA_DEPENDENCIES  scala.meta.metals.Main
root       74695   74355  0 16:09 ?        00:00:00 /vscode/vscode-server/bin/linux-x64/dfd34e8260c270da74b5c2d86d61aee4b6d56977/node /vscode/vscode-server/bin/linux-x64/dfd34e8260c270da74b5c2d86d61aee4b6d56977/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=74355

Looks like this node process is managing some Java/Scala extensions. However these haven't changed. Is there a way to determine whether these extensions have all of a sudden become too slow to load or whether newer VSCode has some issue?

Even if node cpu / slowdown issue is due to these extensions, can you explain why VSCode itself has become completely unresponsive? Other extensions or at least text editing ought to work.

**Comment by chrmarti** [comment]
Could you try profiling the extensions: https://github.com/microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions ?

**Comment by vishalovercome** [comment]
I ran bisect and it was inconclusive. I believe this problem happens the first time I reload. This happens once every day I get disconnected from VPN. Once it enters this "stuck" state, no commands can run for 10-15 minutes. After this, any number of reloads work fine. Thus there's no real way to monitor what's going on besides some terminal commands

**Comment by chrmarti** [comment]
Reconnection works for me using VS Code 1.67 (that has a reconnection fix, make sure to update if haven't) and the latest Remote-Containers. Which extensions do you have installed and does this occur also with all extensions disabled (`F1` > `Developer: Reload with Extensions Disabled`)?
