### ISSUE TITLE
Cloning repository in a volume doesn't work

### ISSUE THREAD

**Issue by vishalovercome** [microsoft/vscode-remote-release#6602]
Cloning repository in a volume doesn't work anymore for me. I'm not sure how to debug this, so I'll just paste the logs.

- VSCode Version: 1.66
- Local OS Version: MacOS Monterey
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: Docker
- Logs:

```
[13 ms] Remote-Containers 0.231.5 in VS Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898).
[13 ms] Start: Resolving Remote
[17 ms] Start: Run: ssh -F /Users/vishal/.ssh/config ubuntu@remote-docker-dev /bin/sh
[27 ms] Start: Run in host: id -un
[2187 ms] ubuntu
[2187 ms] 
[2188 ms] Start: Run in host: cat /etc/passwd
[2350 ms] Start: Run in host: echo ~
[2453 ms] /home/ubuntu
[2453 ms] 
[2454 ms] Start: Run in host: test -x '/home/ubuntu/.vscode-remote-containers/bin/8dfae7a5cd50421d10cd99cb873990460525a898/node'
[2562 ms] 
[2562 ms] 
[2563 ms] Start: Run in host: test -f '/home/ubuntu/.vscode-remote-containers/dist/vscode-remote-containers-server-0.231.5.js'
[2668 ms] 
[2670 ms] 
[2778 ms] userEnvProbe: loginInteractiveShell (default)
[2778 ms] userEnvProbe shell: /bin/bash
[2894 ms] Host server: Error: spawn /bin/bash ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[3001 ms] Error: spawn /bin/bash ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[3002 ms] Host server: (node:43163) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(Use `node --trace-warnings ...` to show where the warning was created)
[3214 ms] Host server: Error: spawn cat ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[3326 ms] Error: Could not read file: /etc/passwd
        at Object.readFile (/Users/vishal/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.5/dist/extension/extension.js:210:6072)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async Object.homedir (/Users/vishal/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.5/dist/extension/extension.js:210:5522)
        at async cL (/Users/vishal/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.5/dist/extension/extension.js:382:6397)
        at async jc (/Users/vishal/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.5/dist/extension/extension.js:384:22950)
        at async /Users/vishal/.vscode/extensions/ms-vscode-remote.remote-containers-0.231.5/dist/extension/extension.js:388:6825
[3326 ms] Exit code ENOENT
[3327 ms] Host server: (node:43163) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
```

Steps to Reproduce:

1. Simply clone any repository to a container volume. Not sure whether devcontainer.json is incorrectly setup

**Comment by vishalovercome** [comment]
I've tried this out with version 0.231.5 and 0.232.5 of remote containers extension

**Comment by chrmarti** [comment]
Could you check what you get for `process.cwd()` in the developer console? (`Help` > `Toggle Developer Tools`) (I see a bug in the code, but I'm not sure if that is the cause for the issue you see.)

**Comment by dannytech** [comment]
Having what I believe is the exact same issue (has been like this for at least a month or two) with Remote - Containers v0.231.6. `docker.host` is configured to be `ssh://daniel@example.com@devserver.com` (logging into a domain account, changed the domain names for privacy), and I use an SSH key to log in. I believe I may have seen mentions of issues with usernames or paths containing invalid characters in the past, but I don't remember exactly and this worked for me for the longest time. Except from the `trace` log is below.

```
[2022-04-17T07:00:20.659Z] 
[2022-04-17T07:00:20.659Z] Stop (100 ms): Run in host: cat <<'EOF-/home/daniel@example.com/.vscode-remote-containers/dist/vscode-remote-containers-server-0.231.6.js' >/home/daniel@example.com/.vscode-remote-containers/dist/vscode-remote-containers-server-0.231.6.js_1650178820559
[2022-04-17T07:00:20.761Z] userEnvProbe: loginInteractiveShell (default)
[2022-04-17T07:00:20.762Z] userEnvProbe shell: /bin/sh
[2022-04-17T07:00:20.763Z] Start: Run in Host: /bin/sh -lic echo -n 80f8b891b3ee7d7f71289d3bd9a9cb69; cat /proc/self/environ; echo -n 80f8b891b3ee7d7f71289d3bd9a9cb69
[2022-04-17T07:00:20.869Z] Host server: Error: spawn /bin/sh ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-04-17T07:00:20.970Z] Host server: (node:3541126) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(Use `node --trace-warnings ...` to show where the warning was created)
[2022-04-17T07:00:20.972Z] Stop (209 ms): Run in Host: /bin/sh -lic echo -n 80f8b891b3ee7d7f71289d3bd9a9cb69; cat /proc/self/environ; echo -n 80f8b891b3ee7d7f71289d3bd9a9cb69
[2022-04-17T07:00:20.972Z] Error: spawn /bin/sh ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-04-17T07:00:21.165Z] Host server: Error: spawn cat ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[2022-04-17T07:00:21.272Z] Error: Could not read file: /etc/passwd
	at Object.readFile (c:\Users\Daniel Hellstern\.vscode\extensions\ms-vscode-remote.remote-containers-0.231.6\dist\extension\extension.js:210:6072)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Object.homedir (c:\Users\Daniel Hellstern\.vscode\extensions\ms-vscode-remote.remote-containers-0.231.6\dist\extension\extension.js:210:5522)
	at async cL (c:\Users\Daniel Hellstern\.vscode\extensions\ms-vscode-remote.remote-containers-0.231.6\dist\extension\extension.js:382:6397)
	at async jc (c:\Users\Daniel Hellstern\.vscode\extensions\ms-vscode-remote.remote-containers-0.231.6\dist\extension\extension.js:384:22950)
	at async c:\Users\Daniel Hellstern\.vscode\extensions\ms-vscode-remote.remote-containers-0.231.6\dist\extension\extension.js:388:6825
[2022-04-17T07:00:21.273Z] Exit code ENOENT
[2022-04-17T07:00:21.274Z] Host server: (node:3541126) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
```

For me, the output from `process.cwd()` is `'C:\\Users\\Daniel Hellstern\\AppData\\Local\\Programs\\Microsoft VS Code'`

**Comment by chrmarti** [comment]
Please give Remote-Containers 0.233.1 pre-release a try and let me know if that fixes it. Thanks!

**Comment by vishalovercome** [comment]
Can you explain the problem in more details. It seems all of a sudden:

1. Cloning stopped working
2. Re-opening in a container stopped working due to path detection logic failure
3. node managing extensions take close to 10 minutes to load extensions.

These seems like very different kinds of bugs. I lead a team of engineers and having so many different kinds of bugs totally disrupts our development. On atleast 4 occasions, one or more of my teammates upgraded their IDE/extensions only to get completely blocked as we don't have any alternate way of managing developer environments that's in sync with our CI process. Can you provide some timelines by when we can expect this extension to be stable?

**Comment by dannytech** [comment]
The pre-release version seems to fix the specific issue I was having when it tried to read `/etc/passwd`, but now it's stopping and waiting for input for the following, which I can't actually type in the answer for.

```
The authenticity of host 'github.com (192.30.255.112)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? 
```

**Comment by chrmarti** [comment]
@vishalovercome 

> Can you explain the problem in more details. It seems all of a sudden:
> 
> 1. Cloning stopped working

This was this issue.

> 2. Re-opening in a container stopped working due to path detection logic failure

This is #6679.

> 3. node managing extensions take close to 10 minutes to load extensions.

Not sure we captured that in an issue yet. If this is still a problem, could you open an issue for us to investigate?

> These seems like very different kinds of bugs. I lead a team of engineers and having so many different kinds of bugs totally disrupts our development. On atleast 4 occasions, one or more of my teammates upgraded their IDE/extensions only to get completely blocked as we don't have any alternate way of managing developer environments that's in sync with our CI process. Can you provide some timelines by when we can expect this extension to be stable?

We are working hard to keep it stable. There have been larger refactorings over the past few months that temporarily introduced regressions. When you encounter these please file an issue noting with which version it broke, so we can prioritize it and narrow down the problem more quickly. Note that you can install older versions of the extension from the Extensions viewlet in VS Code to avoid issues with a new version (make sure to first file the bug report). Thanks.

**Comment by chrmarti** [comment]
> The pre-release version seems to fix the specific issue I was having when it tried to read `/etc/passwd`, but now it's stopping and waiting for input for the following, which I can't actually type in the answer for.
> 
> ```
> The authenticity of host 'github.com (192.30.255.112)' can't be established.
> ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
> This key is not known by any other names
> Are you sure you want to continue connecting (yes/no/[fingerprint])? 
> ```

This is tracked as https://github.com/microsoft/vscode-remote-release/issues/4531.
