### ISSUE TITLE
Unable to download VS Code server locally: Server returned 404

### ISSUE THREAD

**Issue by Viknet** [microsoft/vscode-remote-release#6607]
- VSCode Version: 1.66.1 (Universal)
- Local OS Version: Darwin arm64 21.3.0 (macOS 12.2.1)
- Remote OS Version: Ubuntu 20.04.3 LTS
- Remote Extension/Connection Type: SSH
- Logs: 
```
...
[17:53:41.897] > Installing to /home/viknet/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898...
[17:53:41.898] > Trigger local server download
> 6d3fc40b027f:trigger_server_download
> platform==linux==
[17:53:41.898] > vscodeArch==x64==
> destFolder==/home/viknet/.vscode-server/bin/==
> destFolder2==8dfae7a5cd50421d10cd99cb873990460525a898==
> 6d3fc40b027f:trigger_server_download_end
> Waiting for client to transfer server archive...
[17:53:41.900] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/home/viknet/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898"}
[17:53:41.901] Downloading VS Code server locally...
[17:53:41.903] > Waiting for /home/viknet/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/vscode-scp-done.flag and vscode-server.tar.gz to exist
>  
[17:53:42.048] Terminating local server
[17:53:42.049] Resolver error: Error: Server returned 404
    at w (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:618:6598)
    at k.download (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:619:1585)
[17:53:42.051] Local server exit: 15
[17:53:42.052] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"1","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Unknown","exitCodeLabel":""},"measures":{"resolveAttempts":1,"timing.totalResolveTime":1545,"timing.preSshTime":26,"timing.establishSshTime":1341}}
[17:53:42.054] ------
```

[logs.zip](https://github.com/microsoft/vscode-remote-release/files/8474053/logs.zip)

Steps to Reproduce:

1. Set option "remote.SSH.localServerDownload": "always"
2. Try to connect to new remote server.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

---------

I did some debugging and found out that method `DownloadService.download` has a line converting vscode.Uri into string:
```js
/*resource:
{
    "$mid": 1,
    "path": "/commit:8dfae7a5cd50421d10cd99cb873990460525a898/server-linux-x64/stable",
    "scheme": "https",
    "authority": "update.code.visualstudio.com"
}
*/
const options = { type: 'GET', url: resource.toString() };
/*options:
{
    "type": "GET",
    "url": "https://update.code.visualstudio.com/commit%3A8dfae7a5cd50421d10cd99cb873990460525a898/server-linux-x64/stable"
}
*/
```
Notice that colon mark `:` transformed into `%3A`. This URL is responding 404.
If I reverse `%3A` back to `:` after that line, extension is downloading server and everything working as expected.

**Comment by tanhakabir** [comment]
Hm I'm not reproducing on my end. How did you debug this?

**Comment by Viknet** [comment]
> How did you debug this?

I just had opened Developer Tools in VS Code and clicked on error's traceback from Console tab.
<details>
<summary>screenshot</summary>
<img width="2032" alt="Screen Shot 2022-04-13 at 15 00 09" src="https://user-images.githubusercontent.com/418420/163175679-13c75828-a484-44d6-9a72-3da49baeb828.png">
</details>

But I think the real issue was yesterday on the server `update.code.visualstudio.com` and it was fixed:
<details>
<summary>Yesterday</summary>
<p>

````
❯❯❯ wget https://update.code.visualstudio.com/commit%3A8dfae7a5cd50421d10cd99cb873990460525a898/server-linux-x64/stable
--2022-04-12 17:36:09--  https://update.code.visualstudio.com/commit%3A8dfae7a5cd50421d10cd99cb873990460525a898/server-linux-x64/stable
Resolving update.code.visualstudio.com (update.code.visualstudio.com)... 51.144.164.215
Connecting to update.code.visualstudio.com (update.code.visualstudio.com)|51.144.164.215|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-04-12 17:36:09 ERROR 404: Not Found.

❯❯❯ wget https://update.code.visualstudio.com/commit:8dfae7a5cd50421d10cd99cb873990460525a898/server-linux-x64/stable
--2022-04-12 17:36:32--  https://update.code.visualstudio.com/commit:8dfae7a5cd50421d10cd99cb873990460525a898/server-linux-x64/stable
Resolving update.code.visualstudio.com (update.code.visualstudio.com)... 51.144.164.215
Connecting to update.code.visualstudio.com (update.code.visualstudio.com)|51.144.164.215|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://az764295.vo.msecnd.net/stable/8dfae7a5cd50421d10cd99cb873990460525a898/vscode-server-linux-x64.tar.gz [following]
--2022-04-12 17:36:32--  https://az764295.vo.msecnd.net/stable/8dfae7a5cd50421d10cd99cb873990460525a898/vscode-server-linux-x64.tar.gz
Resolving az764295.vo.msecnd.net (az764295.vo.msecnd.net)... 152.199.19.160
Connecting to az764295.vo.msecnd.net (az764295.vo.msecnd.net)|152.199.19.160|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 55092219 (53M) [application/gzip]
Saving to: ‘stable’
...
````
</p>
</details>


<details><summary>Today</summary>
<p>

````
❯❯❯ wget https://update.code.visualstudio.com/commit%3A8dfae7a5cd50421d10cd99cb873990460525a898/server-linux-x64/stable                                                                                 ✘ 130 
--2022-04-13 15:02:25--  https://update.code.visualstudio.com/commit%3A8dfae7a5cd50421d10cd99cb873990460525a898/server-linux-x64/stable
Resolving update.code.visualstudio.com (update.code.visualstudio.com)... 51.144.164.215
Connecting to update.code.visualstudio.com (update.code.visualstudio.com)|51.144.164.215|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://az764295.vo.msecnd.net/stable/8dfae7a5cd50421d10cd99cb873990460525a898/vscode-server-linux-x64.tar.gz [following]
--2022-04-13 15:02:26--  https://az764295.vo.msecnd.net/stable/8dfae7a5cd50421d10cd99cb873990460525a898/vscode-server-linux-x64.tar.gz
Resolving az764295.vo.msecnd.net (az764295.vo.msecnd.net)... 152.199.19.160
Connecting to az764295.vo.msecnd.net (az764295.vo.msecnd.net)|152.199.19.160|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 55092219 (53M) [application/gzip]
Saving to: ‘stable'
...
````
</p>
</details>
