### ISSUE TITLE
VSCode Remote with SSH PORT Forwarding - ERROR 1006 :: channel : open failed: connect failed: open failed

### ISSUE THREAD

**Issue by arunc1985** [microsoft/vscode-remote-release#6612]
### Aim : I want to connect to remote VM using Vscode and run builds. But the remote VM has to be reached via a Proxy.
Basically aim is to do double-ssh, connect to remote VM using VSCode remote SSH.

### Highlight:

 Say I have ServerA, I want to connect to ServerB. The PORT of ServerB to connect to is unknown before-hand, the end-goal is to load contents of ServerB into VSCode Editor. Where I should make configurations such that the VSCode remote ssh plugin can do SSH accordingly and route the connections.
### 

> 
> ```
> I can use below configs in my VSCode ssh config file if the PORT & IP are known before-hand
> 
> Host serverA
> HostName serverA_ip
> PreferredAuthentications publickey
> IdentityFile your_key
> User you
> 
> Host serverB
> Hostname serverB_ip
> IdentityFile your_key
> ProxyJump serverA
> User you
> ```

But in my case the PORT & IP and allocated dynamically, is it possible to do double SSH to connect to remote systems using VSCode Remote SSH plugin?

### > User -> Proxy VM (Does SSH Forwarding) -> Remote VM (to run builds)
   Note: User reaches proxy VM and the proxy VM will re-direct to remote VM. User can't reach remote VM directly

VSCode Version: 1.66.1
Local OS Version: Windows10
Remote OS Version: U20
Remote Extension/Connection Type: SSH
Logs:

**Steps to Reproduce:**

> 
> 1. Take VM1, VM2
> 2. In sshd_config of VM1, add a rule to SSH forward to VM2
> 3. In VS Code editor ~/.ssh/config file, configure to route to VM1
> 4. Run Connection in VSCode, using RemoteSSH plugin
> 5. You can see it will land in VM2, but then it would stop and get stuck there with above error: Waiting for **### /home/arunch3x/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/vscode-scp-done.flag and vscode-server.tar.gz to exist**
> 6. To resolve step-5 I tried step-7 below
> 7. In remote VM2, r**m -rf /home/${USER}/.vscode-server/ and when I try to place the files in /home/${USER}/.vscode-server/bin/${commit_id}/vscode-scp-done.flag and /home/${USER}/.vscode-server/bin/${commit_id}/vscode-server.tar.gz, vscode server would show error as below and quit session.**
> 

**Refer sample config for Step-2 above;**
### **

> Match user arunch3x
> 
>  AllowStreamLocalForwarding yes
>  AllowAgentForwarding yes
>  AllowTcpForwarding yes
>  GatewayPorts yes
>  X11Forwarding yes
>  PasswordAuthentication yes
>  AllowTCPForwarding yes
>  PasswordAuthentication yes
>  AllowTCPForwarding yes
>  ForceCommand ssh -vvv -o 'StrictHostKeyChecking=no' arunch3x@10.74.*.* -p 32170

**

**Error after executing Step-7 above**

> **### connected to SSH Host - Please do not close this terminal
> channel 2: open failed: connect failed: open failed
> channel 3: open failed: connect failed: open failed
> channel 2: open failed: connect failed: open failed**
>

**Comment by arunc1985** [comment]
![image](https://user-images.githubusercontent.com/33749998/163169441-81f34756-6b02-4548-94c5-15b206a952ea.png)

**Comment by tanhakabir** [comment]
Could you share your Remote SSH logs as well? https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues

**Comment by arunc1985** [comment]
[20220414T101430.zip](https://github.com/microsoft/vscode-remote-release/files/8486400/20220414T101430.zip)
[20220413T214437.zip](https://github.com/microsoft/vscode-remote-release/files/8486401/20220413T214437.zip)
@tanhakabir Please find attached

**Comment by arunc1985** [comment]
@tanhakabir  Please refer to flow
![vscodeflow drawio](https://user-images.githubusercontent.com/33749998/163320071-3d47b8a3-1e4f-4cde-931b-30ffbfe1298e.png)

**Comment by arunc1985** [comment]
@tanhakabir As i can see this message , VSCode remote SSH plugin **is not able to complete this SCP file transfer** and do vs-code-server install in the remote target machine.

**### Waiting for /home/arunch3x/.vscode-server/bin/8dfae7a5cd50421d10cd99cb873990460525a898/vscode-scp-done.flag and vscode-server.tar.gz to exist**

It hangs there.
So I must add any other setting in my linux VMs or VSCode settings? I hope you got the real picture?

Note: Just in case If I configure RemoteSSH plugin !/.ssh/config file to reach remote target VM directly, then it works smooth. I guess its not able to finish file transfer(Scp) stage and do install vscode server when passed via intermediate server with automatic routing enabled to reach target remote VM.

**Comment by arunc1985** [comment]
@tanhakabir  Also to add on, VSCode is able to reach remote target server via the intermediate server, as you see in the image below, it has also created lock file, but beyond that step it hangs, its not able to download/scp and install vscode server.
![image](https://user-images.githubusercontent.com/33749998/163329607-c8f35330-54e8-41b2-b54e-8f0d83a138a9.png)

**Comment by arunc1985** [comment]
One more log file showing it hangs;
[1-Remote - SSH.log](https://github.com/microsoft/vscode-remote-release/files/8486915/1-Remote.-.SSH.log)

**Comment by arunc1985** [comment]
[20220414T163622.zip](https://github.com/microsoft/vscode-remote-release/files/8488666/20220414T163622.zip)

**Comment by arunc1985** [comment]
@tanhakabir Please refer error images and additional logs,

![image](https://user-images.githubusercontent.com/33749998/163428621-3f1908e6-07dc-4501-bd8f-32fb07983a2d.png)

**Comment by arunc1985** [comment]
[20220414T163622.zip](https://github.com/microsoft/vscode-remote-release/files/8490640/20220414T163622.zip)

**Comment by arunc1985** [comment]
@tanhakabir I am not using any browser for code-server, only using VSCode remote ssh plugin to connect to remote machines.

**Comment by arunc1985** [comment]
[main.log](https://github.com/microsoft/vscode-remote-release/files/8495881/main.log)
[output_8_20220415T175328.zip](https://github.com/microsoft/vscode-remote-release/files/8495883/output_8_20220415T175328.zip)

**Comment by arunc1985** [comment]
###
[2022-04-16 12:40:20.471] [renderer2] [info] Invoking resolveAuthority(ssh-remote)
[2022-04-16 12:40:20.841] [renderer2] [info] Ignoring configured affinity for 'pub.name' because the extension is unknown or cannot execute.
[2022-04-16 12:40:28.890] [renderer2] [info] resolveAuthority(ssh-remote) returned '127.0.0.1:51469' after 8419 ms
[2022-04-16 12:40:29.074] [renderer2] [error] [remote-connection][Management   ][e0932…][initial][127.0.0.1:51469] socketFactory.connect() failed or timed out. Error:
[2022-04-16 12:40:29.074] [renderer2] [error] Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Users/arunch3x/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:39255)
[2022-04-16 12:40:29.076] [renderer2] [error] [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
[2022-04-16 12:40:29.077] [renderer2] [error] Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Users/arunch3x/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:39255)
[2022-04-16 12:40:29.077] [renderer2] [error] Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Users/arunch3x/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:39255)
[2022-04-16 12:40:29.078] [renderer2] [error] Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Users/arunch3x/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:39255)
[2022-04-16 12:40:29.080] [renderer2] [error] Cannot register remote filesystem provider. Error while fetching remote environment. WebSocket close with status code 1006
[2022-04-16 12:40:29.130] [renderer2] [error] Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Users/arunch3x/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:39255)
[2022-04-16 12:40:29.137] [renderer2] [info] Ignoring configured affinity for 'pub.name' because the extension is unknown or cannot execute.
[2022-04-16 12:40:29.541] [renderer2] [error] WebSocket close with status code 1006: Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Users/arunch3x/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:39255)
[2022-04-16 12:40:29.567] [renderer2] [error] [remote-connection][ExtensionHost][a6b89…][initial][127.0.0.1:51469] socketFactory.connect() failed or timed out. Error:
[2022-04-16 12:40:29.568] [renderer2] [error] Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Users/arunch3x/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:39255)
[2022-04-16 12:40:29.568] [renderer2] [error] [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
[2022-04-16 12:40:29.569] [renderer2] [error] Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Users/arunch3x/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:39255)
[2022-04-16 12:40:29.570] [renderer2] [error] Error received from starting extension host (kind: Remote)
[2022-04-16 12:40:29.570] [renderer2] [error] Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Users/arunch3x/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:39255)
[2022-04-16 12:40:30.031] [renderer2] [error] Error: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Users/arunch3x/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:616:39255)
 
###

**Comment by arunc1985** [comment]
[20220416T125207.zip](https://github.com/microsoft/vscode-remote-release/files/8499472/20220416T125207.zip)

**Comment by arunc1985** [comment]
I tested both passed & failed scenarios - logs attached.
As said above it passes when remote VM is reached directly;
 **VSCodeRemoteSSH -> RemoteVM => Passed**

As said above it fails when remote VM is reached in-directly via an intermediate server;
 **VSCodeRemoteSSH -> IntermediateServer -> RemoteVM => Failed**
[vscodeRemoteSSHFailedlog.log](https://github.com/microsoft/vscode-remote-release/files/8499873/vscodeRemoteSSHFailedlog.log)
[vscodeRemoteSSHPassedlog.log](https://github.com/microsoft/vscode-remote-release/files/8499874/vscodeRemoteSSHPassedlog.log)

**Comment by arunc1985** [comment]
@tanhakabir  I did more debug and came to know that SSH tunnel is established with remote VM, but later disconnected.
Refer failed logs please.
[1-Remote-SSH-Failed.log](https://github.com/microsoft/vscode-remote-release/files/8505690/1-Remote-SSH-Failed.log)

VSCodeRemoteSSH -> IntermediateServer -> RemoteVM => Failed

**Comment by arunc1985** [comment]
@roblourens

**Comment by arunc1985** [comment]
![image](https://user-images.githubusercontent.com/33749998/163940097-a88feede-e616-4ad8-89b6-768576a100b2.png)

**Comment by tanhakabir** [comment]
Hello! Sorry for taking a bit to get to your issue but thank you for all of the thorough details and notes!

> The PORT of ServerB to connect to is unknown before-hand, the end-goal is to load contents of ServerB into VSCode Editor. Where I should make configurations such that the VSCode remote ssh plugin can do SSH accordingly and route the connections.

So the Remote SSH extension in vscode just reuses your OpenSSH binary on your machine. Essentially what we do is `echo <installation script> | ssh <your host>`. We don't have any configurations or are involved in getting to the final destination. If you're able to have `echo "mkdir foo" | ssh <Server A>` work where eventually a folder `foo` should exist in Server B. Can you confirm this works for you?

**Comment by arunc1985** [comment]
@tanhakabir  Yes I did above ;
echo "mkdir foo" | ssh -o 'StrictHostKeyChecking=no' arunch3x@serverA -p PORTA
It has created a directory in the remote serverB:portB

Note: As I mentioned before serverA -p PORTA is static, its intermediate server. But serverB:portB is dynamic that can be reached only via serverA.

Let me know for more inputs please.

Thanks for your kind support, I am fine with delay :)

**Comment by arunc1985** [comment]
@tanhakabir  Please see above screenshot and logs. The vscode server is available in target machine, even the node-js server is starting fine. But once it started, the tunnel gets disconnected.

**Comment by arunc1985** [comment]
@tanhakabir  @roblourens  Please let us know ASAP if VS Code can support double-SSH as per above scenario, else can we say that its' a limitation?

**Comment by arunc1985** [comment]
Is it possible to use VSCode to do remote SSH where the **destination IP & PORT are dynamic.** 
I have a requirement to connect to remote **serverB via serverA**. When I login to **serverA**, I am redirected to **serverB** based on **sshd_configs on serverA** for each user. when I do ssh via cmd line it goes fine to serverB. But VSCode is not able to do that. VSCode is not able to do multiple connection and load contents of ServerB in the code editor. So you can let us know if its a limitation. I can show you demo, this is a major BUG from VS.

**Comment by tanhakabir** [comment]
Sorry about missing these! Hm from your logs it looks like we connected to your remote, installed and started the server successfully. but then opening a tunnel failed. I'm seeing in your settings you have `remote.SSH.remoteServerListenOnSocket` enabled. Does turning this off make a difference for you?

**Comment by arunc1985** [comment]
@tanhakabir  no it doesn't make any difference. If you wish to reproduce this issue. it's very easy. Please follow these steps;
1. Take 2 VMs (VM_1, VM_2) - Ubuntu 20.04
2. Lets say your username is tanhakabir, you wish to connect to VM_2 through VM_1
3. In the /etc/sshd/sshd_config file of VM_1 add a rule to direct your user to VM_2
4. Match user tanhakabir
	AllowStreamLocalForwarding yes
	AllowAgentForwarding yes
	AllowTcpForwarding yes
	GatewayPorts yes
	X11Forwarding yes
	PasswordAuthentication yes
	AllowTCPForwarding yes
	PasswordAuthentication yes
	AllowTCPForwarding yes
	ForceCommand ssh -vvv -o 'StrictHostKeyChecking=no' tanhakabir@<< VM_2 IP ADDRESS >> 
5. try to do a manual ssh with your username **ssh -vvv -o 'StrictHostKeyChecking=no' tanhakabir@<< VM_ IP ADDRESS >>** to VM_1 and see if you land in VM_2 because of SSH Forwarding
6. Point 5 must work since it's linux specific
7. Now open your VS-CODE Editor and add the below settings in ~/.ssh/config
8. Host tanhakabir
  HostName <<VM_1_IP>>
  StrictHostKeyChecking no
  MACs hmac-sha2-512
  User tanhakabir
  Port <<PORT_VM_1>> # PORT is optional

9. Raise a new connection and see if you can land in VM_2_IP as per configuration is /etc/sshd/sshd_config file of VM1.
10. IF point-9 works, we win :)

**Comment by omaidb** [comment]
解决办法:
调整ssh客户端配置~/.ssh/config —必须
参考: https://blog.tizen.moe/entry/2019/10/12/000000
```bash
# 将日志级别设置为: QUIET
LogLevel QUIET
```
![image](https://user-images.githubusercontent.com/18365223/185280130-f31f713e-5bdf-4880-a461-0af4ffdece6b.png)


https://blog.csdn.net/omaidb/article/details/120027990?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22120027990%22%2C%22source%22%3A%22omaidb%22%7D

**Comment by roblourens** [comment]
Seems like there is an issue with the port/socket forwarding to this host, that will have to work. If it doesn't, you might be interested in https://marketplace.visualstudio.com/items?itemName=ms-vscode.remote-server
