### ISSUE TITLE
Unable to open file outside of workspace root

### ISSUE THREAD

**Issue by juxeii** [microsoft/vscode-remote-release#6678]
I am currently developing an extension and stumbled upon a path problem.
Let's say that  remote ssh is connected to `workspace `path `/home/juxeii/projects/myextension`.
Opening a file from here or below folders works without an issue.
But let's say that we have a file exisiting above current `workspasce `in `/home/juxeii/`.
Trying to open a file from here fails with
`cannot open vscode-remote://wsl%2Bubuntu/home/juxeii/gtestLog_testfoo2. Detail: Unable to read file 'vscode-remote://wsl+ubuntu/home/juxeii/gtestLog_testfoo2' (Error: Unable to resolve nonexistent file 'vscode-remote://wsl+ubuntu/home/juxeii/gtestLog_testfoo2')`

Does this mean that all folders not below `workspace `fail to resolve?
Here is a simple line of code with which this can be tested:
`vscode.workspace.openTextDocument(testfileuri).then(_ => logInfo('file found'), (err: Error) => logInfo('no file found ${err.message}))`

Try to use this with a `testfileuri `under the `workspace `and then try to use it with files outside.
What can I do to tell vsc that all paths should remain remote and nowhere else?

**Comment by juxeii** [comment]
Update: actually, I can open a file outside of workspace with this command. The issue is within the problem matcher of an output window:
```
[5/10/2022, 11:44:52] INFO: Log file for testfoo2.cpp: file:///home/juxeii/projects/gtest-cmake-example/build/gtestLog_testfoo2
[5/10/2022, 11:44:52] INFO: Test file file:///home/juxeii/gtestLog_testfoo
```
The first file can be opened, since the file is under workspace root `file:///home/juxeii/projects/gtest-cmake-example`.
The second file cannot be opened since path `file:///home/juxeii` is not under workspace root.
But the second file can be opened programmatically with
const testfileuri = vscode.Uri.file(path.join('/home/juxeii', 'gtestLog_testfoo'));

**Comment by juxeii** [comment]
On the output window `Log (Window)` there is
```
[2022-05-10 13:04:52.599] [renderer3] [error] Error: Unable to read file '\\vscode-app\c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\workbench.desktop.main.js:2701:95592' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat '\\vscode-app\c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\workbench.desktop.main.js:2701:95592')
    at p.doReadFileStream (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:594:24262)
    at async f.doRead (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2737:42343)
    at async f.readStream (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2737:42018)
    at async ir.resolveFromFile (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2726:66754)
    at async u.doResolve (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2737:36878)
    at async Ta.doResolveAsText (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2147:89626)
    at async g.setInput (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2701:94393)
    at async doSetInput (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2699:6429)
    at async doOpenEditor (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2699:4791)
    at async d.openEditor (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2699:3783)
    at async vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2906:16950
    at async C.doOpenCodeEditor (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1360:31342)
    at async m.open (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:594:51701)
    at async open (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:594:53162)
```

**Comment by aeschli** [comment]
Maybe the easiest is if you provide sample code, e.g. a repository that has a sample extension.
