### ISSUE TITLE
SSH fails "An SSH installation couldn't be found"

### ISSUE THREAD

**Issue by Sti2nd** [microsoft/vscode-remote-release#6682]
Seems like SSH in VS Code stopped working, worked last week. SSH works in terminal.

- VSCode Version: 1.66.2
- Local OS Version: Windows_NT x64 10.0.19042
- Remote OS Version: CentOS 7, kernel: Linux 3.10.0-957.1.3.el7.x86_64
- Remote Extension/Connection Type: SSH
- Remote - SSH version: v0.78.0
- Logs:

<details>

[10:41:26.265] Log Level: 2
[10:41:26.265] remote-ssh@0.78.0
[10:41:26.266] win32 x64
[10:41:26.272] SSH Resolver called for "ssh-remote+build", attempt 1
[10:41:26.273] "remote.SSH.useLocalServer": false
[10:41:26.273] "remote.SSH.showLoginTerminal": false
[10:41:26.273] "remote.SSH.remotePlatform": {"build":"linux"}
[10:41:26.273] "remote.SSH.path": undefined
[10:41:26.273] "remote.SSH.configFile": undefined
[10:41:26.274] "remote.SSH.useFlock": true
[10:41:26.274] "remote.SSH.lockfilesInTmp": false
[10:41:26.274] "remote.SSH.localServerDownload": auto
[10:41:26.274] "remote.SSH.remoteServerListenOnSocket": false
[10:41:26.274] "remote.SSH.showLoginTerminal": false
[10:41:26.274] "remote.SSH.defaultExtensions": []
[10:41:26.274] "remote.SSH.loglevel": 2
[10:41:26.274] "remote.SSH.enableDynamicForwarding": true
[10:41:26.274] "remote.SSH.enableRemoteCommand": false
[10:41:26.275] "remote.SSH.serverPickPortsFromRange": {}
[10:41:26.275] "remote.SSH.serverInstallPath": {}
[10:41:26.292] SSH Resolver called for host: build
[10:41:26.292] Setting up SSH remote "build"
[10:41:26.312] Using commit id "dfd34e8260c270da74b5c2d86d61aee4b6d56977" and quality "stable" for server
[10:41:26.316] Install and start server if needed
[10:41:26.320] Checking ssh with "ssh -V"
[10:41:26.324] Got error from ssh: spawn ssh ENOENT
[10:41:26.324] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[10:41:26.326] Got error from ssh: spawn C:\WINDOWS\System32\OpenSSH\ssh.exe ENOENT
[10:41:26.326] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[10:41:26.328] Got error from ssh: spawn C:\Program Files\Git\usr\bin\ssh.exe ENOENT
[10:41:26.328] Checking ssh with "C:\Program Files (x86)\Git\usr\bin\ssh.exe -V"
[10:41:26.330] Got error from ssh: spawn C:\Program Files (x86)\Git\usr\bin\ssh.exe ENOENT
[10:41:26.330] Finding installed ssh failed: ssh installation not found
[10:41:26.331] Resolver error: Error: ssh installation not found
	at c:\Users\USERNAME\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:655260
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async C (c:\Users\USERNAME\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:650907)
	at async I (c:\Users\USERNAME\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:650816)
	at async Object.t.generateMultiLineCommand (c:\Users\USERNAME\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:652496)
	at async Object.t.generateSshCommand (c:\Users\USERNAME\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:682137)
	at async c:\Users\USERNAME\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:644613
	at async Object.t.withShowDetailsEvent (c:\Users\USERNAME\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:647909)
	at async Object.t.resolve (c:\Users\USERNAME\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:645643)
	at async c:\Users\USERNAME\.vscode\extensions\ms-vscode-remote.remote-ssh-0.78.0\out\extension.js:1:722950
[10:41:26.334] ------

</details>

Steps to Reproduce:

1. Try to connect to any remote address with VS Code.

Does this issue occur when you try this locally?: Not applicable?
Does this issue occur when you try this locally and all extensions are disabled?: Should I disable all other extensions except `Remote - SSH`?

**Comment by tanhakabir** [comment]
Did anything change in your system set up? It looks like we can't find SSH on your machine. What happens when you run `ssh -V` in powershell?

In terms of the extension no updates have been made recently so I'm dubious it's an issue with the extension

**Comment by Sti2nd** [comment]
@tanhakabir

```shell
$ ssh -V
OpenSSH_8.5p1, OpenSSL 1.1.1k  25 Mar 2021
```

I don't think I have done anything on my system, not even updated Git Bash.

**Comment by tanhakabir** [comment]
And what's the location of your ssh.exe in your machine?

**Comment by Sti2nd** [comment]
Surprisingly I get this when running in Git Bash

```shell
$ which ssh
/usr/bin/ssh
```

The only clue I have found is that this is the SSH from Git for Windows. https://stackoverflow.com/questions/63068572/does-the-git-client-for-windows-10-install-an-ssh-client-automatically

**Comment by Sti2nd** [comment]
SSH is not in PATH (environment variables) outside of Git Bash.

I found out that my SSH installation is in `C:\Users\USERNAME\AppData\Local\Programs\Git\usr\bin\ssh.exe`! There is no folder at `C:\Program Files\Git` in my system.

I don't remember how I installed it. Found this SO post that mention program can get installed at AppData location if the user doesn't have admin rights https://stackoverflow.com/questions/32297340/why-was-git-installed-in-appdata-instead-of-program-files

**Comment by Sti2nd** [comment]
@tanhakabir 
Would it be wise to add `C:\Users\USERNAME\AppData\Local\Programs\Git\usr\bin\ssh.exe` to the list of SSH paths? I can create a PR if that is wanted

**Comment by tanhakabir** [comment]
Hm with a brief search `C:\Users\USERNAME\AppData\Local\Programs\Git\usr\bin\ssh.exe` doesn't seem like a common location to look for the SSH binary since this one seems to be attached to the GitHub Desktop application. I don't think we'd want to necessarily use this binary since it was intended for another program

**Comment by Sti2nd** [comment]
Alright!
Weird that I don't have GitHub desktop installed, but maybe it is possible to uninstall it and keep the SSH installation.

**Comment by tanhakabir** [comment]
Hm strange, I'll keep this adding location in mind though if I see some other issue end up in the same spot
