### ISSUE TITLE
Connect failed to remote after changing default shell to nushell

### ISSUE THREAD

**Issue by gipsyh** [microsoft/vscode-remote-release#6689]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
1.66.2
dfd34e8260c270da74b5c2d86d61aee4b6d56977
arm64
- OS Version:
local: macos-aarch64
remote: ubuntu22.04-aarch64

Steps to Reproduce:

1. change to nushell: chsh root
2. vscode remote connect failed

**Comment by roblourens** [comment]
Can you share the log from the Remote-SSH output channel?

**Comment by gipsyh** [comment]
```
[09:54:44.439] > Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
> Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
> Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
> Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
[09:54:44.443] > Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
> Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
> Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
[09:54:44.446] > Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
> Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
> Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
> Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
[09:54:44.450] > Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
> Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
> Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
[09:54:44.454] > Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
> Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
> Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
> Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
[09:54:44.457] > Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
> Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
> Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
[09:54:44.461] > Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
> Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
[09:54:44.467] Terminating local server
[09:54:44.468] > Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
> Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
> Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
> Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
> Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
> Error: Os { code: 6, kind: Uncategorized, message: "No such device or address" }
[09:54:44.472] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/gipsyh/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:586167)
	at Timeout._onTimeout (/Users/gipsyh/.vscode/extensions/ms-vscode-remote.remote-ssh-0.78.0/out/extension.js:1:631243)
	at listOnTimeout (node:internal/timers:557:17)
	at processTimers (node:internal/timers:500:7)
[09:54:44.473] Local server exit: 15
[09:54:44.475] ------
```

**Comment by tanhakabir** [comment]
Could you share your full Remote SSH logs?

**Comment by theoparis** [comment]
I'm having this exact same problem 😕 
Same os error in the logs.

**Comment by tanhakabir** [comment]
Could you share your full Remote SSH logs?
