### ISSUE TITLE
Error response from daemon: invalid mount config for type "bind"

### ISSUE THREAD

**Issue by mayong43111** [microsoft/vscode-remote-release#6696]
- VSCode Version: 1.67.0
- Local OS Version:  Windows 11 21H2
- Remote OS Version: docker desktop 4.7.1(77678)
- Remote Extension/Connection  Docker 
- Logs:

```
[2022-05-07T07:33:58.087Z] Stop (1092 ms): Run: docker build -t vsc-vscode-d102640e7348348ded1d18321a2f3125-features --build-arg BASE_IMAGE=vsc-vscode-d102640e7348348ded1d18321a2f3125 --build-arg IMAGE_USER=root C:\Users\yongma\AppData\Local\Temp\vsch\container-features\0.234.0-1651908836698
[2022-05-07T07:33:58.089Z] Start: Run: docker events --format {{json .}} --filter event=start
[2022-05-07T07:33:58.120Z] Start: Starting container
[2022-05-07T07:33:58.121Z] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=e:\repos\Lab\vscode,target=/workspaces/vscode,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=e:\repos\Lab\vscode -l vsch.quality=stable --entrypoint /bin/sh vsc-vscode-d102640e7348348ded1d18321a2f3125-features -c echo Container started
[2022-05-07T07:33:58.289Z] 
[2022-05-07T07:33:58.381Z] docker: Error response from daemon: invalid mount config for type "bind": bind s
ource path does not exist: /run/desktop/mnt/host/e/repos/Lab/vscode.
See 'docker run --help'.
[2022-05-07T07:33:58.473Z] Stop (352 ms): Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=e:\repos\Lab\vscode,target=/workspaces/vscode,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=e:\repos\Lab\vscode -l vsch.quality=stable --entrypoint /bin/sh vsc-vscode-d102640e7348348ded1d18321a2f3125-features -c echo Container started
[2022-05-07T07:33:58.474Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=e:\repos\Lab\vscode --filter label=vsch.quality=stable
[2022-05-07T07:33:58.479Z] Stop (390 ms): Run: docker events --format {{json .}} --filter event=start
[2022-05-07T07:33:58.681Z] Stop (207 ms): Run: docker ps -q -a --filter label=vsch.local.folder=e:\repos\Lab\vscode --filter label=vsch.quality=stable
[2022-05-07T07:33:58.681Z] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=e:\repos\Lab\vscode,target=/workspaces/vscode,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=e:\repos\Lab\vscode -l vsch.quality=stable --entrypoint /bin/sh vsc-vscode-d102640e7348348ded1d18321a2f3125-features -c echo Container started
[2022-05-07T07:33:58.682Z] trap "exit 0" 15
[2022-05-07T07:33:58.682Z] exec "$@"
[2022-05-07T07:33:58.682Z] while sleep 1 & wait $!; do :; done -
[2022-05-07T07:33:58.682Z]     at IR (c:\Users\yongma\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\spec-node\devContainersSpecCLI.js:221:995)
[2022-05-07T07:33:58.683Z]     at zy (c:\Users\yongma\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\spec-node\devContainersSpecCLI.js:221:933)
[2022-05-07T07:33:58.683Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-05-07T07:33:58.683Z]     at async $R (c:\Users\yongma\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\spec-node\devContainersSpecCLI.js:226:2007)
[2022-05-07T07:33:58.683Z]     at async Zy (c:\Users\yongma\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\spec-node\devContainersSpecCLI.js:226:3112)
[2022-05-07T07:33:58.683Z]     at async BR (c:\Users\yongma\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\spec-node\devContainersSpecCLI.js:226:12448)
[2022-05-07T07:33:58.683Z]     at async qR (c:\Users\yongma\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\spec-node\devContainersSpecCLI.js:226:12204)
[2022-05-07T07:33:58.693Z] Stop (4928 ms): Run: C:\Program Files\Microsoft VS Code\Code.exe c:\Users\yongma\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\yongma\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder e:\repos\Lab\vscode --workspace-mount-consistency cached --id-label vsch.local.folder=e:\repos\Lab\vscode --id-label vsch.quality=stable --log-level debug --log-format json --config e:\repos\Lab\vscode\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-05-07T07:33:58.693Z] Exit code 1
[2022-05-07T07:33:58.696Z] Command failed: C:\Program Files\Microsoft VS Code\Code.exe c:\Users\yongma\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\yongma\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder e:\repos\Lab\vscode --workspace-mount-consistency cached --id-label vsch.local.folder=e:\repos\Lab\vscode --id-label vsch.quality=stable --log-level debug --log-format json --config e:\repos\Lab\vscode\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-05-07T07:33:58.696Z] Exit code 1
```
Steps to Reproduce:

1. add dev config file
2. nodejs 16 + typescript
3. reopen

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by mayong43111** [comment]
```
[2022-05-07T07:33:53.023Z] Remote-Containers 0.234.0 in VS Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47).
[2022-05-07T07:33:53.023Z] Start: Resolving Remote
[2022-05-07T07:33:53.074Z] Setting up container for folder or workspace: e:\repos\Lab\vscode
[2022-05-07T07:33:53.081Z] Start: Check Docker is running
[2022-05-07T07:33:53.081Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2022-05-07T07:33:53.312Z] Stop (231 ms): Run: docker version --format {{.Server.APIVersion}}
[2022-05-07T07:33:53.313Z] Server API version: 1.41
[2022-05-07T07:33:53.313Z] Stop (232 ms): Check Docker is running
[2022-05-07T07:33:53.313Z] Start: Run: docker volume ls -q
[2022-05-07T07:33:53.509Z] Stop (196 ms): Run: docker volume ls -q
[2022-05-07T07:33:53.579Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=e:\repos\Lab\vscode --filter label=vsch.quality=stable
[2022-05-07T07:33:53.764Z] Stop (185 ms): Run: docker ps -q -a --filter label=vsch.local.folder=e:\repos\Lab\vscode --filter label=vsch.quality=stable
[2022-05-07T07:33:53.765Z] Start: Run: C:\Program Files\Microsoft VS Code\Code.exe c:\Users\yongma\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\yongma\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder e:\repos\Lab\vscode --workspace-mount-consistency cached --id-label vsch.local.folder=e:\repos\Lab\vscode --id-label vsch.quality=stable --log-level debug --log-format json --config e:\repos\Lab\vscode\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-05-07T07:33:53.942Z] remote-containers 0.234.0.
[2022-05-07T07:33:53.942Z] Start: Resolving Remote
[2022-05-07T07:33:53.946Z] Start: Run: git rev-parse --show-cdup
[2022-05-07T07:33:54.034Z] Stop (88 ms): Run: git rev-parse --show-cdup
[2022-05-07T07:33:54.036Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=e:\repos\Lab\vscode --filter label=vsch.quality=stable
[2022-05-07T07:33:54.253Z] Stop (217 ms): Run: docker ps -q -a --filter label=vsch.local.folder=e:\repos\Lab\vscode --filter label=vsch.quality=stable
[2022-05-07T07:33:54.255Z] Start: Run: docker build -f e:\repos\Lab\vscode\.devcontainer\Dockerfile -t vsc-vscode-d102640e7348348ded1d18321a2f3125 --build-arg VARIANT=16-bullseye e:\repos\Lab\vscode\.devcontainer
[2022-05-07T07:33:54.421Z] 
[2022-05-07T07:33:54.682Z] 
[+] Building 0.0s (0/1)
[2022-05-07T07:33:54.838Z] 
[+] Building 0.2s (2/3)
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 32B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/t  0.1s
[2022-05-07T07:33:54.995Z] 
[+] Building 0.3s (2/3)
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 32B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/t  0.2s
[2022-05-07T07:33:55.148Z] 
[+] Building 0.5s (2/3)
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 32B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/t  0.4s
[2022-05-07T07:33:55.241Z] 
[+] Building 0.6s (5/5) FINISHED
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 32B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/t  0.4s
 => CACHED [1/1] FROM mcr.microsoft.com/vscode/devcontainers/typescript-n  0.0s
 => exporting to image                                                     0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:6f80ad49fca6f3760ff6d51853b10413e8129adf67cac  0.0s
 => => naming to docker.io/library/vsc-vscode-d102640e7348348ded1d18321a2  0.0s
[2022-05-07T07:33:56.635Z] 
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and l
earn how to fix them
[2022-05-07T07:33:56.697Z] Stop (2442 ms): Run: docker build -f e:\repos\Lab\vscode\.devcontainer\Dockerfile -t vsc-vscode-d102640e7348348ded1d18321a2f3125 --build-arg VARIANT=16-bullseye e:\repos\Lab\vscode\.devcontainer
[2022-05-07T07:33:56.707Z] Preparing to parse declared features and fetch remote features.
[2022-05-07T07:33:56.707Z] Detected local feature set. Continuing...
[2022-05-07T07:33:56.707Z] Start: Run: docker inspect --type image vsc-vscode-d102640e7348348ded1d18321a2f3125
[2022-05-07T07:33:56.904Z] Stop (197 ms): Run: docker inspect --type image vsc-vscode-d102640e7348348ded1d18321a2f3125
[2022-05-07T07:33:56.907Z] local container features stored at: c:\Users\yongma\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\node_modules\vscode-dev-containers\container-features
[2022-05-07T07:33:56.908Z] Start: Run: tar --no-same-owner -x -f -
[2022-05-07T07:33:56.991Z] Stop (83 ms): Run: tar --no-same-owner -x -f -
[2022-05-07T07:33:56.995Z] Start: Run: docker build -t vsc-vscode-d102640e7348348ded1d18321a2f3125-features --build-arg BASE_IMAGE=vsc-vscode-d102640e7348348ded1d18321a2f3125 --build-arg IMAGE_USER=root C:\Users\yongma\AppData\Local\Temp\vsch\container-features\0.234.0-1651908836698
[2022-05-07T07:33:57.166Z] 
[2022-05-07T07:33:57.427Z] 
[+] Building 0.0s (0/1)
[2022-05-07T07:33:57.519Z] 
[+] Building 0.1s (2/3)
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 295B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/vsc-vscode-d102640e734  0.0s
[2022-05-07T07:33:57.642Z] 
[+] Building 0.2s (5/7)
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 295B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/vsc-vscode-d102640e734  0.0s
 => [internal] load build context                                          0.1s
 => => transferring context: 268.91kB                                      0.1s
 => [1/3] FROM docker.io/library/vsc-vscode-d102640e7348348ded1d18321a2f3  0.0s
[2022-05-07T07:33:57.704Z] 
[+] Building 0.3s (8/8) FINISHED
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 295B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/vsc-vscode-d102640e734  0.0s
 => [internal] load build context                                          0.1s
 => => transferring context: 268.91kB                                      0.1s
 => [1/3] FROM docker.io/library/vsc-vscode-d102640e7348348ded1d18321a2f3  0.0s
 => CACHED [2/3] COPY . /tmp/build-features/                               0.0s
 => CACHED [3/3] RUN cd /tmp/build-features/local-cache && chmod +x ./ins  0.0s
 => exporting to image                                                     0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:501e44b8872783425e07dcc29d3cc5b38c713e40bda16  0.0s
 => => naming to docker.io/library/vsc-vscode-d102640e7348348ded1d18321a2  0.0s
[2022-05-07T07:33:57.995Z] 
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and l
earn how to fix them
[2022-05-07T07:33:58.087Z] Stop (1092 ms): Run: docker build -t vsc-vscode-d102640e7348348ded1d18321a2f3125-features --build-arg BASE_IMAGE=vsc-vscode-d102640e7348348ded1d18321a2f3125 --build-arg IMAGE_USER=root C:\Users\yongma\AppData\Local\Temp\vsch\container-features\0.234.0-1651908836698
[2022-05-07T07:33:58.089Z] Start: Run: docker events --format {{json .}} --filter event=start
[2022-05-07T07:33:58.120Z] Start: Starting container
[2022-05-07T07:33:58.121Z] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=e:\repos\Lab\vscode,target=/workspaces/vscode,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=e:\repos\Lab\vscode -l vsch.quality=stable --entrypoint /bin/sh vsc-vscode-d102640e7348348ded1d18321a2f3125-features -c echo Container started
[2022-05-07T07:33:58.289Z] 
[2022-05-07T07:33:58.381Z] docker: Error response from daemon: invalid mount config for type "bind": bind s
ource path does not exist: /run/desktop/mnt/host/e/repos/Lab/vscode.
See 'docker run --help'.
[2022-05-07T07:33:58.473Z] Stop (352 ms): Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=e:\repos\Lab\vscode,target=/workspaces/vscode,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=e:\repos\Lab\vscode -l vsch.quality=stable --entrypoint /bin/sh vsc-vscode-d102640e7348348ded1d18321a2f3125-features -c echo Container started
[2022-05-07T07:33:58.474Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=e:\repos\Lab\vscode --filter label=vsch.quality=stable
[2022-05-07T07:33:58.479Z] Stop (390 ms): Run: docker events --format {{json .}} --filter event=start
[2022-05-07T07:33:58.681Z] Stop (207 ms): Run: docker ps -q -a --filter label=vsch.local.folder=e:\repos\Lab\vscode --filter label=vsch.quality=stable
[2022-05-07T07:33:58.681Z] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=e:\repos\Lab\vscode,target=/workspaces/vscode,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=e:\repos\Lab\vscode -l vsch.quality=stable --entrypoint /bin/sh vsc-vscode-d102640e7348348ded1d18321a2f3125-features -c echo Container started
[2022-05-07T07:33:58.682Z] trap "exit 0" 15
[2022-05-07T07:33:58.682Z] exec "$@"
[2022-05-07T07:33:58.682Z] while sleep 1 & wait $!; do :; done -
[2022-05-07T07:33:58.682Z]     at IR (c:\Users\yongma\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\spec-node\devContainersSpecCLI.js:221:995)
[2022-05-07T07:33:58.683Z]     at zy (c:\Users\yongma\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\spec-node\devContainersSpecCLI.js:221:933)
[2022-05-07T07:33:58.683Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-05-07T07:33:58.683Z]     at async $R (c:\Users\yongma\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\spec-node\devContainersSpecCLI.js:226:2007)
[2022-05-07T07:33:58.683Z]     at async Zy (c:\Users\yongma\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\spec-node\devContainersSpecCLI.js:226:3112)
[2022-05-07T07:33:58.683Z]     at async BR (c:\Users\yongma\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\spec-node\devContainersSpecCLI.js:226:12448)
[2022-05-07T07:33:58.683Z]     at async qR (c:\Users\yongma\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\spec-node\devContainersSpecCLI.js:226:12204)
[2022-05-07T07:33:58.693Z] Stop (4928 ms): Run: C:\Program Files\Microsoft VS Code\Code.exe c:\Users\yongma\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\yongma\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder e:\repos\Lab\vscode --workspace-mount-consistency cached --id-label vsch.local.folder=e:\repos\Lab\vscode --id-label vsch.quality=stable --log-level debug --log-format json --config e:\repos\Lab\vscode\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-05-07T07:33:58.693Z] Exit code 1
[2022-05-07T07:33:58.696Z] Command failed: C:\Program Files\Microsoft VS Code\Code.exe c:\Users\yongma\.vscode\extensions\ms-vscode-remote.remote-containers-0.234.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\yongma\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder e:\repos\Lab\vscode --workspace-mount-consistency cached --id-label vsch.local.folder=e:\repos\Lab\vscode --id-label vsch.quality=stable --log-level debug --log-format json --config e:\repos\Lab\vscode\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-05-07T07:33:58.696Z] Exit code 1
```

**Comment by matgnt** [comment]
Same issue here. Appeared 'overnight'.
Using the Python container with vscode 1.67.0

**Comment by matgnt** [comment]
Things I tried so far:

snap revert code (got 1.66.2): NO
Delete '.devcontainer': NO
Uninstall docker.io and install docker-ce from docker: NO
Switch ms-vscode-remote to 'pre-release' version: NO
Delete '.vscode' directory: NO

Curious to find out what the issue is. And as always it happens when you need it most ;-)

**Comment by matgnt** [comment]
Ok, got it working on my end again:
From the error log I copied the docker command and tried to start in the command line. From there I could see a better error message from docker directly and in my case it was complaining about a network that I configured the dev-container to connect to. I did rebuilds before, and deleted and created new devcontainers, but somehow it survived.

Now I just did a 'docker rm XXX' on the container from the error log and next time I started the remote container, it rebuilt it and everything worked.

For others, the issue MIGHT have been, that I did a 'docker prune' to remove unused docker resources maybe 2 days ago. Not sure, but maybe the extension saved some references and of course didn't know about my 'prune' command.

**Comment by chrmarti** [comment]
@mayong43111 Are you using Docker Desktop or some other Docker package? There seems to be an issue with mounting a local Windows folder. Maybe try restarting Docker (or your machine) to see if that fixes it.

@matgnt The network issue sounds different. Could you open a new issue when you see this again? Thanks!

**Comment by matgnt** [comment]
@chrmarti yes, you're right, I cam across this one here because my error was in the same `devContainersSpecCLI.js`, but proabably the root cause is different. Will open a separate issue should I see it again.
