### ISSUE TITLE
Remote Contanier: Can't Attach 32bit ubuntu contanier

### ISSUE THREAD

**Issue by iofu728** [Microsoft/vscode-remote-release#67]
### Env
- VSCode Version: Version 1.34.0-insider (1.34.0-insider)
- Local OS Version: macOS Mojave 10.14.5 Beta (18F118d)
- Remote OS Version: Ubuntu 16.04.1 LTS i386
- Remote Extension/Connection Type: Docker

### Steps to Reproduce:
1. Run an ubuntu32 docker container.
```bash
docker pull iofu728/zsh.sh.ubuntu32
run -it -d --name zsh_ubuntu32 iofu728/zsh.sh.ubuntu32
```
2. Remote Container: Attach to Running Container
3. It will show `/root/.vscode-remote/bin/XXXX/server.sh: 12: /root/.vscode-remote/bin/XXXX/server.sh: /root/.vscode-remote/bin/XXXX/node: not found`
![image](https://cdn.nlark.com/yuque/0/2019/png/104214/1556886437602-07b33d19-a5e2-4cf9-a5e6-037787a211c9.png)
4. And I exec containter to install a node, and change `/root/.vscode-remote/bin/XXXX/server.sh: 12`, `node` -> local node;
5. It also a new error;
```bash
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at t._loadAndEvalScript (/root/.vscode-remote/bin/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9/out/vs/loader.js:17:414)
    at /root/.vscode-remote/bin/473af338e1bd9ad4d9853933da1cd9d5d9e07dc9/out/vs/loader.js:17:285
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```
![image](https://cdn.nlark.com/yuque/0/2019/png/104214/1556886437639-7b57edfc-2795-40d7-9809-df03b64f15de.png)
### What is expected?
The after reading document, I only find a place where an emphasis on not support 32bit OS. But it talks about Remote SSH, not for Remote Container. I expected I can user vscode-remote to enter ubuntu32 docker container.

### What is actually happening?
when I enter ubuntu32 docker container by using vscode-remote, It takes some error.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
We don't support Linux 32 bit at the moment. Note that Node.js has dropped support for Linux 32 bit and there are only unofficial builds: https://github.com/nodejs/unofficial-builds

**Comment by iofu728** [comment]
Get it! Thx.

Maybe this statement can add to the document.

And I test the unofficial builds node, It also blocks in build.

Looking forward to your future work.

**Comment by ppanhoto78** [comment]
Just curiosity from a passer-by. If the server is implemented in js (as it requires node), why would you care whether the remote is 32bit or 64bit? Wouldn't it be necessary just that the remote host has nodejs installed in a compatible version?

**Comment by chrmarti** [comment]
@ppanhoto78 We want to bundle the node executable in the correct version ourselves and the server also includes a few native node modules that need to be compiled against the target architecture.

**Comment by darkvertex** [comment]
I work with raspberry pi hardware and it's a shame to not be able to use this due to this incompatibility.

> unreachable or not Linux x86_64. (Linux armv7l)

:disappointed:

**Comment by chrmarti** [comment]
@darkvertex This issue is about x86, there is now experimental support for ARM 32bit: https://github.com/microsoft/vscode-remote-release/issues/13#issuecomment-500880693

**Comment by CelestialGuru** [comment]
Can confirm you can connect to a 32 bit **remote** machine:
![image](https://user-images.githubusercontent.com/45701317/101690639-cc90a100-3a2a-11eb-9a8b-d344b0d48814.png)
![image](https://user-images.githubusercontent.com/45701317/101690703-ddd9ad80-3a2a-11eb-81e7-e3cdf2b33b96.png)

But I still wish you could connect to a 32 bit docker container:
`docker run --rm -it i386/debian:buster`

**Comment by daniporr** [comment]
Now it does not even work on 32-bit systems that can run 64-bit executables: #8615

**Comment by aol-nnov** [comment]
Now [they are dropping](https://code.visualstudio.com/docs/remote/faq#_can-i-run-vs-code-server-on-32bit-arm-linux-hosts)  32-bit ARM Linux hosts.

Why on the earth... 

Microsoft, please stop and think twice! We need remote ssh extension to work on 32-bit ARM Linux hosts! There are plenty of them yet!
