### ISSUE TITLE
2 step auth problem

### ISSUE THREAD

**Issue by fdq09eca** [microsoft/vscode-remote-release#6724]
I need to access to a host that requires 2 step auth. the extension successfully prompts me an input window after the password. 

More specifically, when it asks for password it logs the following:

```
[10:05:03.264] Showing password prompt
[10:05:03.265] Listening for interwindow password on /var/folders/t6/qy2rcbdx0g9_fv98q1g48v_h0000gn/T/vscode-ssh-askpass-334cff6873288c350c977803afe96d3fcf097396.sock
```

when it ask for 2 step auth, it logs the following

```
[10:05:10.794] Got askpass request: {"request":"Duo two-factor login for t65115cl Enter a passcode or select one of the following options: 1. Duo Push to +XX XXXX XX2934 Passcode or option (1-1):"}
[10:05:10.798] Listening for interwindow password on /var/folders/t6/qy2rcbdx0g9_fv98q1g48v_h0000gn/T/vscode-ssh-askpass-fa28a85c1ea9c5e2feb7ae025a0c305a79b78358.sock
```

However, when it is setting up the vscode-server on the remote machine, it asks for password for another time, which prompt the input window as the 1st time, 
```
[10:05:30.900] > Password: 
[10:05:30.901] Showing password prompt
[10:05:33.121] >  
[10:05:36.102] >  
[10:05:39.100] >  
[10:05:42.128] >  
[10:05:45.104] >  
[10:05:48.169] >  
[10:05:51.138] >  
[10:05:54.016] Got password response
```

but when it did not show the 2nd window

```
> Enter a passcode or select one of the following options:
> 
>  1. Duo Push to +XX XXXX XX2934
> 
> Passcode or option (1-1): 
```

and the process stuck at here.. i cannot input the passcode or option response. Full log available below

```
[10:05:01.951] Log Level: 2
[10:05:01.958] remote-ssh@0.80.0
[10:05:01.958] darwin x64
[10:05:01.969] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a22637366332e697473657276696365732e6d616e636865737465722e61632e756b222c2275736572223a22743635313135636c227d", attempt 1
[10:05:01.971] "remote.SSH.useLocalServer": true
[10:05:01.979] "remote.SSH.path": undefined
[10:05:01.979] "remote.SSH.configFile": undefined
[10:05:01.979] "remote.SSH.useFlock": true
[10:05:01.979] "remote.SSH.lockfilesInTmp": false
[10:05:01.981] "remote.SSH.localServerDownload": auto
[10:05:01.981] "remote.SSH.remoteServerListenOnSocket": false
[10:05:01.981] "remote.SSH.showLoginTerminal": false
[10:05:01.981] "remote.SSH.defaultExtensions": []
[10:05:01.981] "remote.SSH.loglevel": 2
[10:05:01.981] "remote.SSH.enableDynamicForwarding": true
[10:05:01.981] "remote.SSH.enableRemoteCommand": false
[10:05:01.981] "remote.SSH.serverPickPortsFromRange": {}
[10:05:01.981] "remote.SSH.serverInstallPath": {}
[10:05:02.015] SSH Resolver called for host: t65115cl@csf3.itservices.manchester.ac.uk
[10:05:02.016] Setting up SSH remote "csf3.itservices.manchester.ac.uk"
[10:05:02.025] Acquiring local install lock: /var/folders/t6/qy2rcbdx0g9_fv98q1g48v_h0000gn/T/vscode-remote-ssh-08e0d384-install.lock
[10:05:02.029] Looking for existing server data file at /Users/chrislam/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-08e0d384-dfd34e8260c270da74b5c2d86d61aee4b6d56977-0.80.0/data.json
[10:05:02.029] Using commit id "dfd34e8260c270da74b5c2d86d61aee4b6d56977" and quality "stable" for server
[10:05:02.120] Install and start server if needed
[10:05:02.145] PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
[10:05:02.145] Checking ssh with "ssh -V"
[10:05:02.164] > OpenSSH_8.1p1, LibreSSL 2.7.3

[10:05:02.168] askpass server listening on /var/folders/t6/qy2rcbdx0g9_fv98q1g48v_h0000gn/T/vscode-ssh-askpass-3f79ceb5a0cc048795972b53ca6b55d6664de7df.sock
[10:05:02.168] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/t6/qy2rcbdx0g9_fv98q1g48v_h0000gn/T/vscode-ssh-askpass-67a4c13825e01c5048a9becab8566e9984abbeb4.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","61165","-o","ConnectTimeout=15","t65115cl@csf3.itservices.manchester.ac.uk"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/chrislam/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-08e0d384-dfd34e8260c270da74b5c2d86d61aee4b6d56977-0.80.0/data.json"}
[10:05:02.168] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.1QmDl4gLm7/Listeners","SHELL":"/bin/zsh","DISPLAY":"/private/tmp/com.apple.launchd.yGEmSNJ9I2/org.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/chrislam/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/MacOS/Electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/chrislam/.vscode/extensions/ms-vscode-remote.remote-ssh-0.80.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/t6/qy2rcbdx0g9_fv98q1g48v_h0000gn/T/vscode-ssh-askpass-3f79ceb5a0cc048795972b53ca6b55d6664de7df.sock"}
[10:05:02.172] Spawned 9537
[10:05:02.506] > local-server-1> Spawned ssh, pid=9541
[10:05:02.507] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[10:05:02.597] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:jfZ4u8QHYQS6KuesW3upEoF931zA/AsT7UHqHQhW97Y
[10:05:03.263] Got askpass request: {"request":"Password:"}
[10:05:03.264] Showing password prompt
[10:05:03.265] Listening for interwindow password on /var/folders/t6/qy2rcbdx0g9_fv98q1g48v_h0000gn/T/vscode-ssh-askpass-334cff6873288c350c977803afe96d3fcf097396.sock
[10:05:03.265] Writing password prompt to globalState
[10:05:09.965] Got password response
[10:05:09.967] Interactor gave response: ***********
[10:05:09.968] Cleaning up other-window auth server
[10:05:10.794] Got askpass request: {"request":"Duo two-factor login for t65115cl Enter a passcode or select one of the following options: 1. Duo Push to +XX XXXX XX2934 Passcode or option (1-1):"}
[10:05:10.798] Listening for interwindow password on /var/folders/t6/qy2rcbdx0g9_fv98q1g48v_h0000gn/T/vscode-ssh-askpass-fa28a85c1ea9c5e2feb7ae025a0c305a79b78358.sock
[10:05:10.798] Writing password prompt to globalState
[10:05:13.486] Interactor gave response: *
[10:05:13.486] Cleaning up other-window auth server
[10:05:19.001] stderr> Authenticated to csf3.itservices.manchester.ac.uk ([10.99.203.52]:22).
[10:05:19.027] > Success. Logging you in...
[10:05:19.574] > ready: 797bccf343d9
[10:05:19.587] > Linux 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020
[10:05:19.588] Platform: linux
[10:05:19.594] > /bin/bash
[10:05:19.595] Shell: bash
[10:05:19.595] Creating bash subshell inside "bash"
[10:05:19.605] > bash version:  4.2.46(2)-release
[10:05:19.637] > 797bccf343d9: running
[10:05:19.688] > Acquiring lock on /mnt/iusers01/support/t65115cl/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/vscode-remote-lock.t65115cl.dfd34e8260c270da74b5c2d86d61aee4b6d56977
[10:05:19.698] > Installing to /mnt/iusers01/support/t65115cl/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977...
[10:05:19.714] > 797bccf343d9%%1%%
[10:05:19.723] > Downloading with wget
[10:05:27.184] > wget download failed
> 
> printenv:
>     MANPATH=/opt/site/sge/man:/usr/share/man:/usr/local/share/man
>     XDG_SESSION_ID=1348185
>     HOSTNAME=hlogin2.pri.csf3.alces.network
>     SHELL=/bin/bash
>     HISTSIZE=1000
>     SSH_CLIENT=10.206.7.53 61167 22
>     NCARG_FONTCAPS=/usr/lib64/ncarg/fontcaps
>     SGE_ARCH=lx-amd64
>     SGE_CELL=default
>     QT_GRAPHICSSYSTEM_CHECKED=1
>     USER=t65115cl
>     NCARG_GRAPHCAPS=/usr/lib64/ncarg/graphcaps
>     VSCODE_AGENT_FOLDER=/mnt/iusers01/support/t65115cl/.vscode-server
>     PATH=/opt/site/sge/bin:/opt/site/sge/bin/lx-amd64:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/mnt/iusers01/support/t65115cl/.local/bin:/mnt/iusers01/support/t65115cl/bin
>     MAIL=/var/spool/mail/t65115cl
>     PWD=/mnt/iusers01/support/t65115cl/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977
>     _LMFILES_=/opt/clusterware/etc/modules/null
>     NCARG_ROOT=/usr
>     SGE_EXECD_PORT=6445
>     LANG=en_GB.UTF-8
>     MODULEPATH=/opt/gridware/local/el7/etc/modules:/opt/clusterware/etc/modules:/opt/apps/modules
>     NCARG_DATABASE=/usr/lib64/ncarg/database
>     SGE_QMASTER_PORT=6444
>     LOADEDMODULES=null
>     SGE_ROOT=/opt/site/sge
>     SKIP_USERS=root alces
>     HISTCONTROL=ignoredups
>     NCARG_LIB=/usr/lib64/ncarg
>     HOME=/mnt/iusers01/support/t65115cl
>     SHLVL=2
>     NCARG_NCARG=/usr/share/ncarg
>     cw_MODULES_VERBOSE=1
>     cw_SHELL=bash
>     LOGNAME=t65115cl
>     SSH_CONNECTION=10.206.7.53 61167 10.99.203.52 22
>     cw_DIST=el7
>     XDG_DATA_DIRS=/mnt/iusers01/support/t65115cl/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
>     LESSOPEN=||/usr/bin/lesspipe.sh %s
>     LOWEST_UID=500
>     XDG_RUNTIME_DIR=/run/user/646542
>     SGE_CLUSTER_NAME=csf3
>     BASH_FUNC__cw_root()=() {  _cw_ROOT=${_cw_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")"/../.. && pwd)};
>      echo "${_cw_ROOT}"
>     }
>     BASH_FUNC_module()=() {  if [ "$1" == "search" -a -n "$2" ]; then
>      alces module avail 2>&1 | grep -i -e $2 | sort -u | sed -e 's@/[^/]*+[^/]*$@@' | awk '{print} END {exit NR}';
>      if [ $? -eq 0 ]; then
>      echo "No modulefiles found with '$2' in their name.";
>      if [ -z "$APPSBIOINF" ]; then
>      echo "Try 'module load apps/bioinf' then repeat the search.";
>      fi;
>      else
>      if [ -z "$APPSBIOINF" ]; then
>      echo "More apps/versions may also be available by first doing: 'module load apps/bioinf'";
>      fi;
>      echo "If module names are repeated, show detailed version info using:";
>      echo "module --long search $2";
>      fi;
>      return;
>      fi;
>      if [ \( "$1" == "-l" -o "$1" == "--long" -o "$1" == "-v" -o "$1" == "--verbose" \) -a "$2" == "search" -a -n "$3" ]; then
>      alces module avail 2>&1 | grep -i -e $3 | sort -u;
>      return;
>      fi;
>      alces module "$@"
>     }
>     BASH_FUNC_alces()=() {  local errlvl _cw_ROOT;
>      if [[ -t 1 && "$TERM" != linux ]]; then
>      export cw_COLOUR=1;
>      else
>      export cw_COLOUR=0;
>      fi;
>      _cw_ROOT="$(_cw_root)";
>      [[ -s "${_cw_ROOT}"/bin/alces ]] && case $1 in 
>      mo*)
>      if [[ ! $(ps -o 'command=' -p "$$" 2>/dev/null) =~ ^- ]]; then
>      if [[ ! ":$cw_FLAGS:" =~ :verbose-modules: ]]; then
>      export cw_MODULES_VERBOSE=0;
>      fi;
>      fi;
>      case $2 in 
>      al* | h* | -h | --help)
>      if [[ ":$cw_FLAGS:" =~ :nopager: ]]; then
>      "${_cw_ROOT}"/bin/alces "$@" 0>&1 2>&1;
>      else
>      "${_cw_ROOT}"/bin/alces "$@" 0>&1 2>&1 | less -FRX;
>      fi
>      ;;
>      *)
>      if [[ ":$cw_FLAGS:" =~ :nopager: ]]; then
>      eval $("${_cw_ROOT}"/bin/alces "$@") 2>&1;
>      else
>      if [ -n "$POSIXLY_CORRECT" ]; then
>      eval $("${_cw_ROOT}"/bin/alces "$@") 2>&1;
>      else
>      if [ "$2" == "load" -o "$2" == "add" ]; then
>      eval $("${_cw_ROOT}"/bin/alces "$@") 2>&1;
>      else
>      local p;
>      p="${_cw_ROOT}";
>      eval $(${p}/bin/alces "$@" 2> >(less -FRX >&2)) 2>&1;
>      fi;
>      fi;
>      fi
>      ;;
>      esac
>      ;;
>      gr*)
>      case $2 in 
>      dep*)
>      case $3 in 
>      en* | d* | p* | ini* | ins*)
>      eval $("${_cw_ROOT}"/bin/alces "$@") 2>&1
>      ;;
>      *)
>      "${_cw_ROOT}"/bin/alces "$@"
>      ;;
>      esac
>      ;;
>      *)
>      "${_cw_ROOT}"/bin/alces "$@"
>      ;;
>      esac
>      ;;
>      *)
>      "${_cw_ROOT}"/bin/alces "$@"
>      ;;
>      esac;
>      errlvl=$?;
>      unset cw_COLOUR;
>      return $errlvl
>     }
>     _=/usr/bin/printenv
>     OLDPWD=/mnt/iusers01/support/t65115cl
> Trigger local server download
> 797bccf343d9:trigger_server_download
> platform==linux==
> vscodeArch==x64==
> destFolder==/mnt/iusers01/support/t65115cl/.vscode-server/bin/==
> destFolder2==dfd34e8260c270da74b5c2d86d61aee4b6d56977==
> 797bccf343d9:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /mnt/iusers01/support/t65115cl/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/vscode-scp-done.flag and vscode-server.tar.gz to exist
>  
[10:05:27.194] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/mnt/iusers01/support/t65115cl/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977"}
[10:05:27.195] Downloading VS Code server locally...
[10:05:30.147] >  
[10:05:30.305] Downloaded VS Code server to /var/folders/t6/qy2rcbdx0g9_fv98q1g48v_h0000gn/T/c0b3df44-d0db-4a28-96d5-468892826a12
[10:05:30.308] Renamed VS Code server to /var/folders/t6/qy2rcbdx0g9_fv98q1g48v_h0000gn/T/vscode_server_1652778330306/vscode-server.tar.gz
[10:05:30.315] PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
[10:05:30.315] Checking ssh with "ssh -V"
[10:05:30.328] > OpenSSH_8.1p1, LibreSSL 2.7.3

[10:05:30.330] Testing scp with "scp"
[10:05:30.344] scp exited with code: 1
[10:05:30.344] Got stderr from scp: usage: scp [-346BCpqrTv] [-c cipher] [-F ssh_config] [-i identity_file]
            [-J destination] [-l limit] [-o ssh_option] [-P port]
            [-S program] source ... target
[10:05:30.346] Copying file to remote with scp -o ConnectTimeout=15 'vscode-server.tar.gz' 'vscode-scp-done.flag' 't65115cl@csf3.itservices.manchester.ac.uk':'/mnt/iusers01/support/t65115cl/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977'
[10:05:30.348] Using cwd: file:///var/folders/t6/qy2rcbdx0g9_fv98q1g48v_h0000gn/T/vscode_server_1652778330306
[10:05:30.900] > Password: 
[10:05:30.901] Showing password prompt
[10:05:33.121] >  
[10:05:36.102] >  
[10:05:39.100] >  
[10:05:42.128] >  
[10:05:45.104] >  
[10:05:48.169] >  
[10:05:51.138] >  
[10:05:54.016] Got password response
[10:05:54.017] "Copy server to host" wrote data to terminal: "***********"
[10:05:54.095] > 
[10:05:54.110] >  
[10:05:54.530] > Duo two-factor login for t65115cl
> 
> Enter a passcode or select one of the following options:
> 
>  1. Duo Push to +XX XXXX XX2934
> 
> Passcode or option (1-1): 
[10:05:57.179] >  
[10:06:00.115] >  
[10:06:03.171] >  
```

**Comment by bamurtaugh** [comment]
cc @tanhakabir it seems like 2 factor auth should work, as issues like https://github.com/microsoft/vscode-remote-release/issues/4427 aren't blocked purely because of the 2 step process?

**Comment by bamurtaugh** [comment]
Or actually based on https://github.com/microsoft/vscode-remote-release/issues/2010#issuecomment-570335176, perhaps this isn't expected to work?

**Comment by goldman7911** [comment]
Hi all,

cant write my two factor after pasting password

```
[19:07:17.361] Log Level: 2
[19:07:17.362] remote-ssh@0.80.0
[19:07:17.362] win32 x64
[19:07:17.364] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a224250495f44495245544f5f434f465245227d", attempt 1
[19:07:17.365] "remote.SSH.useLocalServer": false
[19:07:17.365] "remote.SSH.showLoginTerminal": true
[19:07:17.365] "remote.SSH.remotePlatform": {}
[19:07:17.365] "remote.SSH.path": undefined
[19:07:17.365] "remote.SSH.configFile": C:\Users\janki\.ssh\config
[19:07:17.365] "remote.SSH.useFlock": true
[19:07:17.365] "remote.SSH.lockfilesInTmp": false
[19:07:17.365] "remote.SSH.localServerDownload": auto
[19:07:17.366] "remote.SSH.remoteServerListenOnSocket": false
[19:07:17.366] "remote.SSH.showLoginTerminal": true
[19:07:17.366] "remote.SSH.defaultExtensions": []
[19:07:17.366] "remote.SSH.loglevel": 2
[19:07:17.366] "remote.SSH.maxReconnectionAttempts": 0
[19:07:17.366] "remote.SSH.enableDynamicForwarding": true
[19:07:17.366] "remote.SSH.enableRemoteCommand": false
[19:07:17.366] "remote.SSH.serverPickPortsFromRange": {}
[19:07:17.366] "remote.SSH.serverInstallPath": {}
[19:07:17.376] SSH Resolver called for host: BPI_DIRETO_COFRE
[19:07:17.376] Setting up SSH remote "BPI_DIRETO_COFRE"
[19:07:17.388] Using commit id "c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5" and quality "stable" for server
[19:07:17.390] Install and start server if needed
[19:07:18.452] Checking ssh with "ssh -V"
[19:07:18.473] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.
[19:07:18.473] > 0.2

[19:07:18.475] Using SSH config file "C:\Users\janki\.ssh\config"
[19:07:18.475] Running script with connection command: ssh -T -D 57689 -F "C:\Users\janki\.ssh\config" "BPI_DIRETO_COFRE" bash
[19:07:18.477] Terminal shell path: C:\Windows\System32\cmd.exe
[19:07:18.684] > ]0;C:\Windows\System32\cmd.exe
[19:07:18.684] Got some output, clearing connection timeout
[19:07:18.704] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[19:07:18.982] > 80762426[bpadmin@10.124.68.199]@10.124.65.198's password: 
[19:07:21.870] > 
[19:07:24.448] > Warning: Password input may be echoed.
> Two-Factor Token: 
[19:07:24.465] > Warning: Password input may be echoed.
> Two-Factor Token: 
[19:07:31.158] "install" terminal command done
[19:07:31.159] Install terminal quit with output: Two-Factor Token: 
[19:07:31.159] Received install output: Two-Factor Token: 
[19:07:31.159] Failed to parse remote port from server output
[19:07:31.160] Resolver error: Error: 
	at Function.Create (c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:585789)
	at Object.t.handleInstallOutput (c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:584441)
	at Object.t.tryInstall (c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:681707)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:644347
	at async Object.t.withShowDetailsEvent (c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:647692)
	at async Object.t.resolve (c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:645426)
	at async c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:722509
[19:07:31.163] ------

```

**Comment by tanhakabir** [comment]
@goldman7911 could you try after you add to your settings `"remote.SSH.useLocalServer": true`?

**Comment by goldman7911** [comment]
> @goldman7911 could you try after you add to your settings `"remote.SSH.useLocalServer": true`?

I tried before. But follow as requested. 

I can't even type the 2FA.

Warning: Password input may be echoed.
Two-Factor Token: 

```
[17:15:23.645] Log Level: 2
[17:15:23.646] remote-ssh@0.80.0
[17:15:23.646] win32 x64
[17:15:23.649] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a224250495f44495245544f5f434f465245227d", attempt 1
[17:15:23.649] "remote.SSH.useLocalServer": true
[17:15:23.649] "remote.SSH.path": undefined
[17:15:23.650] "remote.SSH.configFile": C:\Users\janki\.ssh\config
[17:15:23.650] "remote.SSH.useFlock": true
[17:15:23.650] "remote.SSH.lockfilesInTmp": false
[17:15:23.650] "remote.SSH.localServerDownload": auto
[17:15:23.650] "remote.SSH.remoteServerListenOnSocket": false
[17:15:23.650] "remote.SSH.showLoginTerminal": true
[17:15:23.650] "remote.SSH.defaultExtensions": []
[17:15:23.650] "remote.SSH.loglevel": 2
[17:15:23.650] "remote.SSH.maxReconnectionAttempts": 0
[17:15:23.650] "remote.SSH.enableDynamicForwarding": true
[17:15:23.650] "remote.SSH.enableRemoteCommand": false
[17:15:23.651] "remote.SSH.serverPickPortsFromRange": {}
[17:15:23.651] "remote.SSH.serverInstallPath": {}
[17:15:23.659] SSH Resolver called for host: BPI_DIRETO_COFRE
[17:15:23.659] Setting up SSH remote "BPI_DIRETO_COFRE"
[17:15:23.661] Acquiring local install lock: C:\Users\janki\AppData\Local\Temp\vscode-remote-ssh-8e35ffc2-install.lock
[17:15:23.663] Looking for existing server data file at c:\Users\janki\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-ssh\vscode-ssh-host-8e35ffc2-c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5-0.80.0\data.json
[17:15:23.664] Using commit id "c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5" and quality "stable" for server
[17:15:23.666] Install and start server if needed
[17:15:23.676] Checking ssh with "ssh -V"
[17:15:23.699] > OpenSSH_for_Windows_8.1p1, 
[17:15:23.699] > LibreSSL 3.0.2

[17:15:23.701] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[17:15:23.722] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[17:15:23.724] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[17:15:23.755] > OpenSSH_9.0p1, OpenSSL 1.1.1o  3 May 2022

[17:15:23.758] Using SSH config file "C:\Users\janki\.ssh\config"
[17:15:23.758] askpass server listening on \\.\pipe\vscode-ssh-askpass-a915d9e8ac8e163561618d0f42b7851a65cdad12-sock
[17:15:23.758] Spawning local server with {"serverId":1,"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-67eb91725ca6253f4830fad1689b1747f3192897-sock","sshCommand":"C:\\Program Files\\Git\\usr\\bin\\ssh.exe","sshArgs":["-v","-T","-D","57092","-F","C:\\Users\\janki\\.ssh\\config","BPI_DIRETO_COFRE"],"serverDataFolderName":".vscode-server","dataFilePath":"c:\\Users\\janki\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-vscode-remote.remote-ssh\\vscode-ssh-host-8e35ffc2-c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5-0.80.0\\data.json"}
[17:15:23.758] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"c:\\Users\\janki\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.80.0\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"C:\\Users\\janki\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"c:\\Users\\janki\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.80.0\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-a915d9e8ac8e163561618d0f42b7851a65cdad12-sock"}
[17:15:23.763] Spawned 18324
[17:15:23.827] > local-server-1> Spawned ssh, pid=21708
[17:15:23.872] stderr> OpenSSH_9.0p1, OpenSSL 1.1.1o  3 May 2022
[17:15:24.014] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:Pa35EC14wefnET2N6/FYkJNqSZAYcZuNr4acZ/6+Svg
[17:15:24.242] Got askpass request: {"request":"80762426[bpadmin@10.124.68.199]@10.124.65.198's password: "}
[17:15:24.243] Showing password prompt
[17:15:24.243] Listening for interwindow password on \\.\pipe\vscode-ssh-askpass-db4ddc2c40f1b72813e96720ea69211654152a36-sock
[17:15:24.243] Writing password prompt to globalState
[17:15:30.590] Got password response
[17:15:30.590] Interactor gave response: ***************
[17:15:30.590] Cleaning up other-window auth server
[17:15:35.841] stderr> Authenticated to 10.124.65.198 ([10.124.65.198]:22) using "password".
[17:15:35.922] stderr> Learned new hostkey: ED25519 SHA256:Q1B+xAA7IZS8hDkECVAVj25D9jECoLgry20zbXbAGDk
[17:15:35.931] stderr> Adding new key for 10.124.65.198 to /c/Users/janki/.ssh/known_hosts: ssh-ed25519 SHA256:Q1B+xAA7IZS8hDkECVAVj25D9jECoLgry20zbXbAGDk
[17:15:35.935] > 
> The programs included with the Debian GNU/Linux system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
> permitted by applicable law.
[17:15:37.036] stderr> Warning: Password input may be echoed.
[17:15:37.036] stderr> Two-Factor Token: 
[17:15:42.452] stderr> Transferred: sent 2416, received 2644 bytes, in 6.6 seconds
[17:15:42.452] stderr> Bytes per second: sent 365.5, received 400.0
[17:15:42.454] > local-server-1> ssh child died, shutting down
[17:15:42.458] Local server exit: 0
[17:15:42.459] Received install output: local-server-1> Spawned ssh, pid=21708
OpenSSH_9.0p1, OpenSSL 1.1.1o  3 May 2022
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:Pa35EC14wefnET2N6/FYkJNqSZAYcZuNr4acZ/6+Svg
Authenticated to 10.124.65.198 ([10.124.65.198]:22) using "password".
Learned new hostkey: ED25519 SHA256:Q1B+xAA7IZS8hDkECVAVj25D9jECoLgry20zbXbAGDk
Adding new key for 10.124.65.198 to /c/Users/janki/.ssh/known_hosts: ssh-ed25519 SHA256:Q1B+xAA7IZS8hDkECVAVj25D9jECoLgry20zbXbAGDk

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Warning: Password input may be echoed.
Two-Factor Token: 
Transferred: sent 2416, received 2644 bytes, in 6.6 seconds
Bytes per second: sent 365.5, received 400.0
local-server-1> ssh child died, shutting down

[17:15:42.459] Failed to parse remote port from server output
[17:15:42.460] Resolver error: Error: 
	at Function.Create (c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:585789)
	at Object.t.handleInstallOutput (c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:584441)
	at Object.e [as tryInstallWithLocalServer] (c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:624908)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:643945
	at async Object.t.withShowDetailsEvent (c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:647692)
	at async c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:623380
	at async b (c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:619886)
	at async Object.t.resolveWithLocalServer (c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:622995)
	at async Object.t.resolve (c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:645302)
	at async c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:722509
[17:15:42.463] ------
```
