### ISSUE TITLE
not connecting to linux machine

### ISSUE THREAD

**Issue by Dileep8247** [microsoft/vscode-remote-release#6725]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by weikinhuang** [comment]
Also started seeing this today from my windows 10 machine. ssh'ing from the wsl terminal works fine.

The bat script is the one in the GH issues about using WSL's ssh to connect. Everything was working fine yesterday. This also continues to work on my mac
 
```
[17:11:37.436] Log Level: 2
[17:11:37.436] remote-ssh@0.80.0
[17:11:37.437] win32 x64
[17:11:37.437] SSH Resolver called for "ssh-remote+dev", attempt 1
[17:11:37.437] "remote.SSH.useLocalServer": true
[17:11:37.438] "remote.SSH.path": d:\whuang\Documents\Projects\github.com\weikinhuang\dotfiles\utils\wsl\native-wrappers\ssh.bat
[17:11:37.438] "remote.SSH.configFile": undefined
[17:11:37.438] "remote.SSH.useFlock": true
[17:11:37.438] "remote.SSH.lockfilesInTmp": true
[17:11:37.438] "remote.SSH.localServerDownload": off
[17:11:37.438] "remote.SSH.remoteServerListenOnSocket": false
[17:11:37.438] "remote.SSH.showLoginTerminal": false
[17:11:37.438] "remote.SSH.defaultExtensions": []
[17:11:37.438] "remote.SSH.loglevel": 2
[17:11:37.438] "remote.SSH.enableDynamicForwarding": true
[17:11:37.438] "remote.SSH.enableRemoteCommand": false
[17:11:37.439] "remote.SSH.serverPickPortsFromRange": {}
[17:11:37.439] "remote.SSH.serverInstallPath": {}
[17:11:37.442] SSH Resolver called for host: dev
[17:11:37.442] Setting up SSH remote "dev"
[17:11:37.444] Acquiring local install lock: C:\Users\whuang\AppData\Local\Temp\vscode-remote-ssh-d55997bc-install.lock
[17:11:37.445] Looking for existing server data file at c:\Users\whuang\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-ssh\vscode-ssh-host-d55997bc-da15b6fd3ef856477bf6f4fb29ba1b7af717770d-0.80.0\data.json
[17:11:37.446] Using commit id "da15b6fd3ef856477bf6f4fb29ba1b7af717770d" and quality "stable" for server
[17:11:37.448] Install and start server if needed
[17:11:37.453] Checking ssh with "d:\whuang\Documents\Projects\github.com\weikinhuang\dotfiles\utils\wsl\native-wrappers\ssh.bat -V"
[17:11:38.139] > your 131072x1 screen size is bogus. expect trouble

[17:11:38.362] > OpenSSH_8.2p1 Ubuntu-4ubuntu0.5, OpenSSL 1.1.1f  31 Mar 2020

[17:11:38.369] Using SSH config file "C:\Users\whuang\.ssh\config"
[17:11:38.370] askpass server listening on \\.\pipe\vscode-ssh-askpass-b2cddeaa3d9e0a426c4d905644cd010641ee0c24-sock
[17:11:38.370] Spawning local server with {"serverId":1,"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-f01e1caee85a93f3009dbadef7f8b14981e253f3-sock","sshCommand":"d:\\whuang\\Documents\\Projects\\github.com\\weikinhuang\\dotfiles\\utils\\wsl\\native-wrappers\\ssh.bat","sshArgs":["-v","-T","-D","64479","-F","C:\\Users\\whuang\\.ssh\\config","dev","bash"],"serverDataFolderName":".vscode-server","dataFilePath":"c:\\Users\\whuang\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-vscode-remote.remote-ssh\\vscode-ssh-host-d55997bc-da15b6fd3ef856477bf6f4fb29ba1b7af717770d-0.80.0\\data.json"}
[17:11:38.370] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"c:\\Users\\whuang\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.80.0\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"C:\\Users\\whuang\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"c:\\Users\\whuang\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.80.0\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-b2cddeaa3d9e0a426c4d905644cd010641ee0c24-sock"}
[17:11:38.376] Spawned 20544
[17:11:38.432] > local-server-1> Spawned ssh, pid=22968
[17:11:39.135] stderr> your 131072x1 screen size is bogus. expect trouble
[17:11:39.363] stderr> OpenSSH_8.2p1 Ubuntu-4ubuntu0.5, OpenSSL 1.1.1f  31 Mar 2020
[17:11:39.443] stderr> debug1: Server host key: ecdsa-sha2-nistp521 SHA256:...
[17:11:39.475] stderr> Authenticated to dev ([10.10.1.50]:22).
[17:12:40.382] Terminating local server
[17:12:40.384] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (c:\Users\whuang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:585915)
	at Timeout._onTimeout (c:\Users\whuang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:631026)
	at listOnTimeout (node:internal/timers:557:17)
	at processTimers (node:internal/timers:500:7)
[17:12:40.390] ------




[17:12:40.390] Local server exit: null
```

**Comment by tanhakabir** [comment]
@weikinhuang could you try running `Kill VS Code Server on Host...` and then try connecting again?

**Comment by weikinhuang** [comment]
I have tried that @tanhakabir.

These are the things I've tried:
- kill vscode on host
- restart desktop
- restart vm
- installed the preview extension (then reverted to the release version)

It seems like vscode is able to properly ssh into the machine, but then vscode disconnects immediately:

```
$ sudo tail -f /var/log/auth.log
May 17 22:12:04 dev sshd[387854]: Accepted publickey for whuang from 10.10.40.9 port 52416 ssh2: RSA SHA256:...
May 17 22:12:04 dev sshd[387854]: pam_unix(sshd:session): session opened for user whuang by (uid=0)
May 17 22:12:04 dev systemd-logind[781]: New session 96 of user whuang.
May 17 22:13:03 dev sshd[387880]: Received disconnect from 10.73.7.99 port 52416:11: disconnected by user
May 17 22:13:03 dev sshd[387880]: Disconnected from user whuang 10.10.40.9 port 52416
May 17 22:13:03 dev sshd[387854]: pam_unix(sshd:session): session closed for user whuang
May 17 22:13:04 dev systemd-logind[781]: Session 96 logged out. Waiting for processes to exit.
May 17 22:13:04 dev systemd-logind[781]: Removed session 96
```

**Comment by tanhakabir** [comment]
Hm what if you don't use local server mode with `useLocalServer: false`. In your first logs it looks like the local server process gets killed unexpectedly

**Comment by weikinhuang** [comment]
just tried it, same problem

**Comment by weikinhuang** [comment]
I figured out my issue. In my bashrc I was executing powershell commands. By default powershell will eat stdin, so what I did was change it to `</dev/null` on my ps commands and that fixed the issue.
