### ISSUE TITLE
Cannot connect to remote server | "Cannot find module minimist"

### ISSUE THREAD

**Issue by Mashyuf** [microsoft/vscode-remote-release#6768]
- VSCode Version: Version: 1.67.2 
- Local OS Version: Windows_NT x64 10.0.19044
- Remote OS Version: CentOS Linux 7 (Core)
- Remote Extension/Connection Type: SSH
- Logs:
``` 
[22:44:10.638] > Server did not start successfully. Full server log at /home/linux/ieng6/cs15lsp2
> 2/cs15lsp22agc/.vscode-server/.c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5.log >>> 
[22:44:10.665] > node:internal/modules/cjs/loader:933
>   const err = new Error(message);
>               ^
> 
> Error: Cannot find module 'minimist'
> Require stack:
> - /home/linux/ieng6/cs15lsp22/cs15lsp22agc/.vscode-server/bin/c3511e6c69bb39013c
> 4a4b7b9566ec1ca73fc4d5/out/server-main.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15
> )
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at start (/home/linux/ieng6/cs15lsp22/cs15lsp22agc/.vscode-server/bin/c3511e
> 6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/server-main.js:1:292)
>     at Object.<anonymous> (/home/linux/ieng6/cs15lsp22/cs15lsp22agc/.vscode-serv
> er/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/server-main.js:12:28)       
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) 
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {        
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/linux/ieng6/cs15lsp22/cs15lsp22agc/.vscode-server/bin/c3511e6c69bb390
> 13c4a4b7b9566ec1ca73fc4d5/out/server-main.js'
>   ]
> }
[22:44:10.670] > 
> <<< End of server log
> 40c1b728ea6a: start
> exitCode==32==
> listeningOn====
> osReleaseId==centos==
> arch==x86_64==
> tmpDir==/run/user/12286==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==8025==
> 40c1b728ea6a: end
[22:44:10.671] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==centos==
arch==x86_64==
tmpDir==/run/user/12286==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==8025==

[22:44:10.671] Cannot find module 'minimist'

[22:44:10.672] Resolver error: Error: Cannot find module 'minimist'

	at Function.ServerInstallError (c:\Users\Matt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:585723)
	at d (c:\Users\Matt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:578198)
	at Object.t.handleInstallOutput (c:\Users\Matt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:582831)
	at Object.t.tryInstall (c:\Users\Matt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:681707)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\Matt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:644347
	at async Object.t.withShowDetailsEvent (c:\Users\Matt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:647692)
	at async Object.t.resolve (c:\Users\Matt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:645426)
	at async c:\Users\Matt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:722509
```

Steps to Reproduce:

1. Connecting to SSH target using the remote explorer on VSCode

## Extra
----
After failure to connect to the server, when I tried to uninstall this extension, the same error message will pop up. But when I close the remote window and tried to install it again, it will work. 
I'm extremely new to the whole remote server thing and this extension, so it very well could just be some simple mistake from my side.

**Comment by bamurtaugh** [comment]
Thanks for the suggestion @WheelerCC! @Mashyuf please let us know if the suggestion above helps.

**Comment by Mashyuf** [comment]
It worked! Thank you so much!

**Comment by bamurtaugh** [comment]
Great to hear, thanks so much for confirming!
