### ISSUE TITLE
VSCode fails to connect: cannot find module minimist (v2)

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [microsoft/vscode-remote-release#6772]
Related (but log is different): https://github.com/microsoft/vscode-remote-release/issues/6340

- VSCode Version: 1.67.2
- Local OS Version: Windows
- Remote OS Version: 
> $ uname -a
> Linux magic 5.3.18-150200.24.112-preempt #1 SMP PREEMPT Wed Apr 6 12:31:53 UTC 2022 (faf9825) x86_64 x86_64 x86_64 GNU/Linux
- Remote Extension/Connection Type: SSH
- Logs: (See below)

Steps to Reproduce:

Not easily reproduced. I see it from time to time. This is typically what causes the problem:

1. On remote server, manually killed all my VSCode processes
2. On my local PC, close all VSCode instances
3. Attempt to open connection to remote-server (by right-clicking toolbar icon, select workspace from `Recent folders`)
4. VSC displays "Initializing server" (or similar message)
5. Connection fails indicating: `cannot not find module 'minimist'`

Recovering from this situation is not easy. After many attempts, it eventually recovers, but it might take 30+ minutes of trying different things.  Here is what I do:

1. On my local PC, run the command "Kill VSCode Server on Host..." and wait for the pop-up message
2. On remote server, check and kill all remaining vscode processes
3. Close all VSCode instances on my PC and re-open them
4. Try closing and restarting things in different orders
5. Eventually, something works and the server starts.
6. **Start a local VSC instance, open a local TERMINAL, ssh to the server. In another VSC instance connect to remote server (it worked after I did this, though it may have been a coincidence or a combination of things I tried previously).**

Since I can eventually get the server to start, it's a mystery why it cannot find module `minimist` in the prior attempts. Is this a clue as to the cause?

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Haven't tried that yet.

### Remote - SSH Output
```
[07:58:13.091] Log Level: 2
[07:58:13.094] remote-ssh@0.80.0
[07:58:13.094] win32 x64
[07:58:13.136] SSH Resolver called for "ssh-remote+magic", attempt 1
[07:58:13.136] "remote.SSH.useLocalServer": false
[07:58:13.137] "remote.SSH.showLoginTerminal": false
[07:58:13.137] "remote.SSH.remotePlatform": {"5":"linux","6":"linux","7":"linux","8":"linux","9":"linux","10":"linux","11":"linux","12":"linux","13":"linux","14":"linux","s33":"linux","ilby":"linux","cross":"linux","fos":"linux","z10":"linux","magic":"linux","z3":"linux"}
[07:58:13.137] "remote.SSH.path": undefined
[07:58:13.137] "remote.SSH.configFile": undefined
[07:58:13.137] "remote.SSH.useFlock": true
[07:58:13.137] "remote.SSH.lockfilesInTmp": false
[07:58:13.138] "remote.SSH.localServerDownload": auto
[07:58:13.138] "remote.SSH.remoteServerListenOnSocket": false
[07:58:13.138] "remote.SSH.showLoginTerminal": false
[07:58:13.138] "remote.SSH.defaultExtensions": []
[07:58:13.138] "remote.SSH.loglevel": 2
[07:58:13.138] "remote.SSH.enableDynamicForwarding": true
[07:58:13.138] "remote.SSH.enableRemoteCommand": false
[07:58:13.138] "remote.SSH.serverPickPortsFromRange": {}
[07:58:13.140] "remote.SSH.serverInstallPath": {"5":"/store","6":"/store","7":"/store","8":"/store","9":"/store","10":"/store","11":"/store","12":"/store","13":"/store","14":"/store","s1":"/store","s2":"/store","s3":"/store","s4":"/store","s5":"/store","s6":"/store","s7":"/store","s8":"/store","s9":"/store","s10":"/store","s11":"/store","s12":"/store","s13":"/store","s14":"/store","s15":"/store","s16":"/store","s17":"/store","s18":"/store","s19":"/store","s20":"/store","s21":"/store","s22":"/store","s23":"/store","s24":"/store","s25":"/store","s26":"/store","s27":"/store","s28":"/store","s29":"/store","s30":"/store","s31":"/store","s32":"/store","s33":"/store","s34":"/store","s35":"/store","s36":"/store","s37":"/store","s38":"/store","s39":"/store","s40":"/store","s41":"/store","s42":"/store","s43":"/store","s44":"/store","s45":"/store","s46":"/store","s47":"/store","s48":"/store","s49":"/store"}
[07:58:13.158] SSH Resolver called for host: magic
[07:58:13.158] Setting up SSH remote "magic"
[07:58:13.167] Using commit id "c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5" and quality "stable" for server
[07:58:13.175] Install and start server if needed
[07:58:13.188] Checking ssh with "ssh -V"
[07:58:13.272] > OpenSSH_9.0p1, OpenSSL 1.1.1o  3 May 2022

[07:58:13.289] Running script with connection command: ssh -T -D 54035 magic bash
[07:58:13.293] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[07:58:19.056] > eb663fe337e6: running
> ]0;C:\WINDOWS\System32\cmd.exe
[07:58:19.056] Got some output, clearing connection timeout
[07:58:19.068] > Acquiring lock on /home/username/.vscode-server/bin/c3511e6c69bb39013c4a4b7b95
> 66ec1ca73fc4d5/vscode-remote-lock.username.c3511e6c69bb39013c4a4b7b9566ec1ca73
> fc4d5
[07:58:19.141] > Found existing installation at /home/username/.vscode-server/bin/c3511e6c69bb3
> 9013c4a4b7b9566ec1ca73fc4d5...
> Checking /home/username/.vscode-server/.c3511e6c69bb39013c4a4b7b9566ec1ca73fc4
> d5.log and /home/username/.vscode-server/.c3511e6c69bb39013c4a4b7b9566ec1ca73f
> c4d5.pid for a running server
[07:58:19.154] > Looking for server with pid: 71086
[07:58:19.167] > Starting server with command... /home/username/.vscode-server/bin/c3511e6c69bb
> 39013c4a4b7b9566ec1ca73fc4d5/bin/code-server --start-server --host=127.0.0.1 --a
> ccept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-le
> vel all   &> "/home/username/.vscode-server/.c3511e6c69bb39013c4a4b7b9566ec1ca
> 73fc4d5.log" < /dev/null
> printenv:
>     GLASSFISH_BIN=/home/username/distros/glassfish4/bin
>     HOSTTYPE=x86_64
>     DEFDEVDIR=h3/h3-mfw
>     SSH_CONNECTION=16.99.178.28 54039 10.234.84.130 22
>     LESSCLOSE=lessclose.sh %s %s
>     XKEYSYMDB=/usr/X11R6/lib/X11/XKeysymDB
>     LANG=en_US.UTF-8
>     WINDOWMANAGER=/usr/bin/gnome
>     LESS=-M -I -R
>     JAVA_ROOT=/usr/lib64/jvm/jre-1.8.0-ibm
>     HOSTNAME=magic
>     PYENV_ROOT=/home/username/.pyenv
>     GWROOT=/work/username/s.gw
>     CSHEDIT=emacs
>     AUDIODRIVER=pulseaudio
>     GPG_TTY=not a tty
>     LESS_ADVANCED_PREPROCESSOR=no
>     COLORTERM=1
>     PYENV_VIRTUALENV_INIT=1
>     GWBMC=/work/username/s.gw/uv400/bmc
>     JAVA_HOME=/home/username/distros/jdk1.8.0_102
>     ALSA_CONFIG_PATH=/etc/alsa-pulse.conf
>     MACHTYPE=x86_64-suse-linux
>     DEVROOT=/work/username
>     QEMU_AUDIO_DRV=pa
>     MINICOM=-c on
[07:58:19.177] > 
>     CLONEDIR=s.clone
>     GWCMC=/work/username/s.gw/uv2/cmc
>     QT_SYSTEM_DIR=/usr/share/desktop-data
>     OSTYPE=linux
>     GLASSFISH_BASE=/home/username/distros/glassfish4
>     XDG_SESSION_ID=1869
>     USER=username
>     PAGER=less
>     MODULE_VERSION=3.2.10
>     MORE=-sl
>     PWD=/home/username
>     HOME=/home/username
>     HOST=magic
>     SSH_CLIENT=16.99.178.28 54039 22
>     PYENV_VERSION=3.8.5
>     CLONERMC=/work/username/s.clone/uv2/cmc
>     XNLSPATH=/usr/share/X11/nls
>     CLONEBMC=/work/username/s.clone/uv400/bmc
>     https_proxy=http://proxy:8080
>     XDG_DATA_DIRS=/home/username/.local/share/flatpak/exports/share:/var/lib/f
> latpak/exports/share:/usr/local/share:/usr/share
>     http_proxy=http://proxy:8080
>     LIBGL_DEBUG=quiet
>     PROFILEREAD=true
>     GWRMC=/work/username/s.gw/uv2/cmc
>     LOADEDMODULES=
>     no_proxy=localhost, 127.0.0.1
>     OPENGROK_CONFIGURATION=/home/username/opengrok/etc/opengrok-env.sh        
>     NO_PROXY=localhost, 127.0.0.1
>     FROM_HEADER=
>     MAIL=/var/spool/mail/username
>     SOCKS_PROXY=
>     CLONECMC=/work/username/s.clone/uv2/cmc
[07:58:19.178] > 
>     LESSKEY=/etc/lesskey.bin
>     SHELL=/bin/bash
>     JAVA=/home/username/distros/jdk1.8.0_102/bin/java
>     socks_proxy=
>     XCURSOR_THEME=DMZ
>     GWDIR=s.gw
>     PYTHONSTARTUP=/etc/pythonstart
>     SHLVL=2
>     PYENV_SHELL=bash
>     G_FILENAME_ENCODING=@locale,UTF-8,ISO-8859-15,CP1252
>     MANPATH=/usr/local/man:/usr/share/man
>     SOCKS5_SERVER=
>     VSCODE_AGENT_FOLDER=/home/username/.vscode-server
>     gopher_proxy=
>     MODULEPATH=/usr/share/modules:/usr/share/Modules/$MODULE_VERSION/modulefiles
> :/usr/share/modules/modulefiles
>     SHOST=magic
>     LOGNAME=username
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/135011636/bus
>     XDG_RUNTIME_DIR=/run/user/135011636
>     MODULE_VERSION_STACK=3.2.10
>     JRE_HOME=/usr/lib64/jvm/jre
>     XDG_CONFIG_DIRS=/etc/xdg
>     PATH=/home/username/.pyenv/plugins/pyenv-virtualenv/shims:/home/username
> /.pyenv/shims:/home/username/.pyenv/bin:/home/username/.local/bin:/home/mugg
> eridge/bin:/usr/local/bin:/usr/bin:/bin:/users/mfwdev/bin:/opt/udock/bin        
>     JAVA_BINDIR=/usr/lib64/jvm/jre-1.8.0-ibm/bin
>     SDL_AUDIODRIVER=pulse
>     CLONEROOT=/work/username/s.clone
>     MODULESHOME=/usr/share/Modules/3.2.10
>     G_BROKEN_FILENAMES=1
>     HISTSIZE=1000
>     ftp_proxy=http://proxy:8080
>     CPU=x86_64
>     CVS_RSH=ssh
>     LESSOPEN=lessopen.sh %s
>     BASH_FUNC_module%%=() {  eval `/usr/share/Modules/$MODULE_VERSION/bin/module
> cmd bash $*`
>     }
>     BASH_FUNC_cpuhog%%=() {  ps -eo pcpu,pid,user,args | sort -k 1 -gr | head -2
> 1
>     }
>     _=/usr/bin/printenv
> Removing old logfile at /home/username/.vscode-server/.c3511e6c69bb39013c4a4b7
> b9566ec1ca73fc4d5.log
> Spawned remote server: 72800
[07:58:19.201] > 
[07:58:19.334] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[07:58:19.342] > Waiting for server log...
[07:58:19.375] > Waiting for server log...
[07:58:19.415] > Waiting for server log...
[07:58:19.459] > Waiting for server log...
[07:58:19.473] > Waiting for server log...
[07:58:19.484] > 
[07:58:19.504] > Waiting for server log...
[07:58:19.548] > Waiting for server log...
[07:58:19.580] > Waiting for server log...
[07:58:19.605] > Waiting for server log...
[07:58:19.618] > 
[07:58:19.636] > Waiting for server log...
[07:58:19.699] > Waiting for server log...
> Waiting for server log...
[07:58:19.711] > 
[07:58:19.764] > Waiting for server log...
[07:58:19.779] > Waiting for server log...
[07:58:19.785] > 
[07:58:19.802] > Waiting for server log...
[07:58:19.832] > Waiting for server log...
[07:58:19.875] > Waiting for server log...
[07:58:19.897] > Waiting for server log...
[07:58:19.932] > Waiting for server log...
[07:58:19.969] > Waiting for server log...
[07:58:19.997] > Waiting for server log...
[07:58:20.006] > 
[07:58:20.030] > Waiting for server log...
[07:58:20.061] > Waiting for server log...
[07:58:20.092] > Waiting for server log...
[07:58:20.124] > Waiting for server log...
[07:58:20.159] > Waiting for server log...
[07:58:20.193] > Waiting for server log...
[07:58:20.225] > Waiting for server log...
[07:58:20.256] > Waiting for server log...
[07:58:20.288] > Waiting for server log...
[07:58:20.323] > Waiting for server log...
[07:58:20.352] > Waiting for server log...
[07:58:20.410] > Waiting for server log...
[07:58:20.420] > Waiting for server log...
[07:58:20.426] > 
[07:58:20.455] > Waiting for server log...
[07:58:20.488] > Waiting for server log...
[07:58:20.520] > Waiting for server log...
[07:58:20.550] > Waiting for server log...
[07:58:20.585] > Waiting for server log...
[07:58:20.615] > Waiting for server log...
[07:58:20.648] > Waiting for server log...
[07:58:20.680] > Waiting for server log...
[07:58:20.714] > Waiting for server log...
[07:58:20.719] > 
[07:58:20.746] > Waiting for server log...
[07:58:20.778] > Waiting for server log...
[07:58:20.812] > Waiting for server log...
[07:58:20.843] > Waiting for server log...
[07:58:20.875] > Waiting for server log...
[07:58:20.910] > Waiting for server log...
[07:58:20.943] > Waiting for server log...
[07:58:20.972] > Waiting for server log...
[07:58:21.008] > Waiting for server log...
[07:58:21.043] > Waiting for server log...
[07:58:21.071] > Waiting for server log...
[07:58:21.079] > 
[07:58:21.106] > Waiting for server log...
[07:58:21.137] > Waiting for server log...
[07:58:21.169] > Waiting for server log...
[07:58:21.201] > Waiting for server log...
[07:58:21.236] > Waiting for server log...
[07:58:21.267] > Waiting for server log...
[07:58:21.300] > Waiting for server log...
[07:58:21.335] > Waiting for server log...
[07:58:21.364] > Waiting for server log...
[07:58:21.399] > Waiting for server log...
[07:58:21.432] > Waiting for server log...
[07:58:21.463] > Waiting for server log...
[07:58:21.495] > Waiting for server log...
[07:58:21.529] > Waiting for server log...
[07:58:21.575] > Waiting for server log...
[07:58:21.632] > Waiting for server log...
> Waiting for server log...
[07:58:21.731] > Waiting for server log...
> Waiting for server log...
[07:58:21.738] > Waiting for server log...
[07:58:21.798] > Waiting for server log...
[07:58:21.805] > Waiting for server log...
[07:58:21.861] > Waiting for server log...
> Waiting for server log...
[07:58:21.871] > 
[07:58:21.907] > Waiting for server log...
[07:58:21.949] > Waiting for server log...
[07:58:21.956] > Waiting for server log...
[07:58:22.006] > Waiting for server log...
[07:58:22.049] > Waiting for server log...
[07:58:22.055] > Waiting for server log...
[07:58:22.084] > Waiting for server log...
[07:58:22.163] > Waiting for server log...
> Waiting for server log...
[07:58:22.190] > 
> Waiting for server log...
[07:58:22.196] > 
[07:58:22.224] > Waiting for server log...
[07:58:22.264] > Waiting for server log...
[07:58:22.301] > Waiting for server log...
[07:58:22.333] > Waiting for server log...
[07:58:22.388] > Waiting for server log...
[07:58:22.400] > Waiting for server log...
[07:58:22.431] > Waiting for server log...
[07:58:22.462] > Waiting for server log...
[07:58:22.498] > Waiting for server log...
[07:58:22.509] > Waiting for server log...
[07:58:22.556] > Waiting for server log...
[07:58:22.576] > Waiting for server log...
[07:58:22.633] > Waiting for server log...
[07:58:22.672] > Waiting for server log...
> Waiting for server log...
[07:58:22.679] > 
[07:58:22.711] > Waiting for server log...
[07:58:22.751] > Waiting for server log...
[07:58:22.806] > Waiting for server log...
> Waiting for server log...
[07:58:22.812] > 
[07:58:22.859] > Waiting for server log...
[07:58:22.866] > Waiting for server log...
[07:58:22.901] > Waiting for server log...
[07:58:22.935] > Waiting for server log...
[07:58:22.968] > Waiting for server log...
[07:58:23.001] > Waiting for server log...
[07:58:23.032] > Waiting for server log...
[07:58:23.063] > Waiting for server log...
[07:58:23.096] > Waiting for server log...
[07:58:23.129] > Waiting for server log...
[07:58:23.159] > Waiting for server log...
[07:58:23.194] > Waiting for server log...
[07:58:23.247] > Waiting for server log...
[07:58:23.262] > Waiting for server log...
[07:58:23.291] > Waiting for server log...
[07:58:23.326] > Waiting for server log...
[07:58:23.370] > Waiting for server log...
[07:58:23.396] > Waiting for server log...
[07:58:23.423] > Waiting for server log...
[07:58:23.454] > Waiting for server log...
[07:58:23.497] > Waiting for server log...
[07:58:23.526] > Waiting for server log...
[07:58:23.559] > Waiting for server log...
[07:58:23.590] > Waiting for server log...
[07:58:23.618] > Waiting for server log...
[07:58:23.653] > Waiting for server log...
[07:58:23.684] > Waiting for server log...
[07:58:23.717] > Waiting for server log...
[07:58:23.749] > Waiting for server log...
[07:58:23.792] > Waiting for server log...
[07:58:23.824] > Waiting for server log...
[07:58:23.852] > Waiting for server log...
[07:58:23.882] > Waiting for server log...
[07:58:23.911] > Waiting for server log...
[07:58:23.945] > Waiting for server log...
[07:58:23.978] > Waiting for server log...
[07:58:24.009] > Waiting for server log...
[07:58:24.047] > Waiting for server log...
[07:58:24.096] > Waiting for server log...
[07:58:24.109] > Waiting for server log...
[07:58:24.142] > Waiting for server log...
[07:58:24.172] > Waiting for server log...
[07:58:24.208] > Waiting for server log...
[07:58:24.239] > Waiting for server log...
[07:58:24.271] > Waiting for server log...
[07:58:24.303] > Waiting for server log...
[07:58:24.337] > Waiting for server log...
[07:58:24.370] > Waiting for server log...
[07:58:24.404] > Waiting for server log...
[07:58:24.437] > Waiting for server log...
[07:58:24.468] > Waiting for server log...
[07:58:24.499] > Waiting for server log...
[07:58:24.535] > Waiting for server log...
[07:58:24.566] > Waiting for server log...
[07:58:24.597] > Waiting for server log...
[07:58:24.632] > Waiting for server log...
[07:58:24.663] > Waiting for server log...
[07:58:24.670] > 
[07:58:24.695] > Waiting for server log...
[07:58:24.730] > Waiting for server log...
[07:58:24.760] > Waiting for server log...
[07:58:24.794] > Waiting for server log...
[07:58:24.828] > Waiting for server log...
[07:58:24.858] > Waiting for server log...
[07:58:24.894] > Waiting for server log...
[07:58:24.926] > Waiting for server log...
[07:58:24.957] > Waiting for server log...
[07:58:24.990] > Waiting for server log...
[07:58:25.022] > Waiting for server log...
[07:58:25.031] > 
[07:58:25.056] > Waiting for server log...
[07:58:25.087] > Waiting for server log...
[07:58:25.122] > Waiting for server log...
[07:58:25.153] > Waiting for server log...
[07:58:25.187] > Waiting for server log...
[07:58:25.220] > Waiting for server log...
[07:58:25.250] > Waiting for server log...
[07:58:25.284] > Waiting for server log...
[07:58:25.318] > Waiting for server log...
[07:58:25.348] > Waiting for server log...
[07:58:25.383] > Waiting for server log...
[07:58:25.415] > Waiting for server log...
[07:58:25.448] > Waiting for server log...
[07:58:25.480] > Waiting for server log...
[07:58:25.514] > Waiting for server log...
[07:58:25.547] > Waiting for server log...
[07:58:25.578] > Waiting for server log...
[07:58:25.585] > 
[07:58:25.611] > Waiting for server log...
[07:58:25.645] > Waiting for server log...
[07:58:25.678] > Waiting for server log...
[07:58:25.710] > Waiting for server log...
[07:58:25.743] > Waiting for server log...
[07:58:25.776] > Waiting for server log...
[07:58:25.808] > Waiting for server log...
[07:58:25.839] > Waiting for server log...
[07:58:25.872] > Waiting for server log...
[07:58:25.906] > Waiting for server log...
[07:58:25.940] > Waiting for server log...
[07:58:25.947] > 
[07:58:25.972] > Waiting for server log...
[07:58:26.004] > Waiting for server log...
[07:58:26.037] > Waiting for server log...
[07:58:26.071] > Waiting for server log...
[07:58:26.102] > Waiting for server log...
[07:58:26.135] > Waiting for server log...
[07:58:26.168] > Waiting for server log...
[07:58:26.201] > Waiting for server log...
[07:58:26.233] > Waiting for server log...
[07:58:26.265] > Waiting for server log...
[07:58:26.299] > Waiting for server log...
[07:58:26.304] > 
[07:58:26.332] > Waiting for server log...
[07:58:26.363] > Waiting for server log...
[07:58:26.395] > Waiting for server log...
[07:58:26.429] > Waiting for server log...
[07:58:26.462] > Waiting for server log...
[07:58:26.495] > Waiting for server log...
[07:58:26.529] > Waiting for server log...
[07:58:26.561] > Waiting for server log...
[07:58:26.593] > Waiting for server log...
[07:58:26.626] > Waiting for server log...
[07:58:26.657] > Waiting for server log...
[07:58:26.692] > Waiting for server log...
[07:58:26.725] > Waiting for server log...
[07:58:26.757] > Waiting for server log...
[07:58:26.791] > Waiting for server log...
[07:58:26.823] > Waiting for server log...
[07:58:26.854] > Waiting for server log...
[07:58:26.886] > Waiting for server log...
[07:58:26.920] > Waiting for server log...
[07:58:26.954] > Waiting for server log...
[07:58:26.990] > Waiting for server log...
[07:58:27.018] > Waiting for server log...
[07:58:27.050] > Waiting for server log...
[07:58:27.081] > Waiting for server log...
[07:58:27.117] >  
> *
> * Reminder: You may only use this software with Visual Studio family products,  
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057) 
> *
> 
> Server did not start successfully. Full server log at /home/username/.vscode-s
[07:58:27.121] > 
> erver/.c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5.log >>>
> node:internal/modules/cjs/loader:933
>   const err = new Error(message);
>               ^
> 
> Error: Cannot find module 'minimist'
> Require stack:
> - /home/username/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/o
> ut/server-main.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15
> )
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at start (/home/username/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec
> 1ca73fc4d5/out/server-main.js:1:292)
>     at Object.<anonymous> (/home/username/.vscode-server/bin/c3511e6c69bb39013
> c4a4b7b9566ec1ca73fc4d5/out/server-main.js:12:28)
>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) 
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {        
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/username/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d
> 5/out/server-main.js'
>   ]
> }
> <<< End of server log
> eb663fe337e6: start
> exitCode==32==
> listeningOn====
> osReleaseId==sles==
> arch==x86_64==
> tmpDir==/run/user/135011636==
> platform==linux==
> unpackResult====
[07:58:27.135] > 
[07:58:27.179] > didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==7951==
> eb663fe337e6: end
[07:58:27.180] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==sles==
arch==x86_64==
tmpDir==/run/user/135011636==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==7951==

[07:58:27.180] Cannot find module 'minimist'

[07:58:27.181] Resolver error: Error: Cannot find module 'minimist'

	at Function.ServerInstallError (c:\Users\muggerid\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:585723)
	at d (c:\Users\muggerid\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:578198)
	at Object.t.handleInstallOutput (c:\Users\muggerid\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:582831)
	at Object.t.tryInstall (c:\Users\muggerid\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:681707)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\muggerid\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:644347
	at async Object.t.withShowDetailsEvent (c:\Users\muggerid\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:647692)
	at async Object.t.resolve (c:\Users\muggerid\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:645426)
	at async c:\Users\muggerid\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:722509
[07:58:27.204] ------




[07:58:27.880] > 
[07:58:28.494] "install" terminal command done
[07:58:28.494] Install terminal quit with output: 

```

**Comment by chrmarti** [comment]
@aeschil FYI, not sure if this might be an issue with the server.

**Comment by bamurtaugh** [comment]
Commenting to tag @aeschli 😄

**Comment by aeschli** [comment]
Maybe a corrupt server install? Please delete `/home/username/.vscode-server/bin` on the remote machine, close all windows and try again.

**Comment by LiveFreeAndRoam** [comment]
If there were corruption, surely it would remain broken? As describes above, I can eventually get it working again.

It's working now, so I don't see any value in reinstalling everything from scratch.

Please advise with more detail if need be.

**Comment by aeschli** [comment]
This is quite a mystery to me. `require('minimist')` is the first statement in out mail file (`.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/server-main.js`) and it should be found in `server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/node_modules/minimist` which you say is there.

The `NODE_PATH` env variable could impact how node miudles are found, that but your log doesn't show that variable being present.

**Comment by LiveFreeAndRoam** [comment]
This is a useful tip. If/When I see this again,I'll post details of the minimist file and NODE_PATH variable.  If there is anything else that I should collect, please let me know.

I'll try to reproduce it by killing the server when I next have some spare time.  For now, the server has been running continuously since I posted this issue.

**Comment by Cassieyy** [comment]
> 

it works for me!!!

**Comment by itnet7** [comment]
> Maybe a corrupt server install? Please delete `/home/username/.vscode-server/bin` on the remote machine, close all windows and try again.

In my particular case, my home was on an NFS space. I had tried to clean up some things and went to and redo the remote-server, when actually trying to remove it I was stopped by things being in use. I possibly had VScode opened somewhere and didn't realize it. It probably got rid of the non-in-use files which basically in my case seemed like corruption. I looked at it again today, and followed your recommendation to remove the contents of bin, and this time they removed without any in use warnings. Now attempting to use the remote ssh works without complaint. Thank you!

**Comment by Cassieyy** [comment]
您的邮件已收到哦我会及时处理哒~

**Comment by LiveFreeAndRoam** [comment]
Interesting. Mine home was also served by NFS. I haven't seen this error in a long time.  Maybe our NFS server has improved.

**Comment by Akshay1-6180** [comment]
this works for me sometimes , In the server delete “~/.vscode-server/“ folder and reconnect via vscode

**Comment by aeschli** [comment]
Is this still a problem? Is anyone seeing the `Cannot find module 'minimist'` error message?

**Comment by LiveFreeAndRoam** [comment]
It hasn't hit me in a very long time.

**Comment by aeschli** [comment]
Thanks! I'm closing the issue for now.
