### ISSUE TITLE
`-u=$(id -u):$(id -g)` in `"runArgs"` let the container fail

### ISSUE THREAD

**Issue by alkatar21** [microsoft/vscode-remote-release#6783]
Normally I use a `tensorflow/tensorflow` image with `docker run -v $(pwd):/workspace -u=$(id -u):$(id -g) -it --rm <image> bash`.
`-u=$(id -u):$(id -g)` is recommended by the image to run with the correct uid/gid.
Now I want to use the container to develop with VSCode as well, however the `-u` option in the `runArgs` seems to fail.

As I understood it, there would be a [workaround](https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user#_creating-a-nonroot-user) by creating an extra user, but this should not be necessary, since I have the correct uid with the other command.

- VSCode Version: 1.67.2
- Local OS Version: Ubuntu 20.04.4
- Remote OS Version: Ubuntu 20.04.4
- Remote Extension/Connection Type: Containers
<details>
<summary>Logs</summary>

```
...
[3462 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/<path> --filter label=vsch.quality=stable
[3486 ms] Start: Run: docker build -f /home/<path>/env/Dockerfile -t <image> --build-arg VARIANT=-gpu-jupyter --build-arg PIPENV_ARGS=--dev /home/<path>/env
Sending build context to Docker daemon  114.2kB
Step 1/6 : ARG VARIANT=-gpu
Step 2/6 : FROM tensorflow/tensorflow:2.7.3${VARIANT}
 ---> 61d14d026cff
...
Step 6/6 : ...
 ---> Using cache
 ---> 686d05b40cd0
Successfully built 686d05b40cd0
Successfully tagged <image>:latest
[3583 ms] Start: Run: docker inspect --type image <image>
[3630 ms] Start: Run: docker build -f /tmp/vsch/updateUID.Dockerfile-0.234.0 -t <image>-uid --build-arg BASE_IMAGE=<image> --build-arg REMOTE_USER=$(id -u):$(id -g) --build-arg NEW_UID=1003 --build-arg NEW_GID=1003 --build-arg IMAGE_USER=root /tmp/vsch
Sending build context to Docker daemon   12.8kB
Step 1/10 : ARG BASE_IMAGE
Step 2/10 : FROM $BASE_IMAGE
 ---> 686d05b40cd0
Step 3/10 : USER root
 ---> Using cache
 ---> dc06d1138c3f
Step 4/10 : ARG REMOTE_USER
 ---> Using cache
 ---> 98be1c41bb80
Step 5/10 : ARG NEW_UID
 ---> Using cache
 ---> 7ab411e18302
Step 6/10 : ARG NEW_GID
 ---> Using cache
 ---> aec3108af395
Step 7/10 : SHELL ["/bin/sh", "-c"]
 ---> Using cache
 ---> 20a66795487f
Step 8/10 : RUN eval $(sed -n "s/${REMOTE_USER}:[^:]*:\([^:]*\):\([^:]*\):[^:]*:\([^:]*\).*/OLD_UID=\1;OLD_GID=\2;HOME_FOLDER=\3/p" /etc/passwd);       eval $(sed -n "s/\([^:]*\):[^:]*:${NEW_UID}:.*/EXISTING_USER=\1/p" /etc/passwd);   eval $(sed -n "s/\([^:]*\):[^:]*:${NEW_GID}:.*/EXISTING_GROUP=\1/p" /etc/group);        if [ -z "$OLD_UID" ]; then              echo "Remote user not found in /etc/passwd ($REMOTE_USER).";    elif [ "$OLD_UID" = "$NEW_UID" -a "$OLD_GID" = "$NEW_GID" ]; then          echo "UIDs and GIDs are the same ($NEW_UID:$NEW_GID).";         elif [ "$OLD_UID" != "$NEW_UID" -a -n "$EXISTING_USER" ]; then          echo "User with UID exists ($EXISTING_USER=$NEW_UID).";    elif [ "$OLD_GID" != "$NEW_GID" -a -n "$EXISTING_GROUP" ]; then                 echo "Group with GID exists ($EXISTING_GROUP=$NEW_GID).";       else            echo "Updating UID:GID from $OLD_UID:$OLD_GID to $NEW_UID:$NEW_GID.";              sed -i -e "s/\(${REMOTE_USER}:[^:]*:\)[^:]*:[^:]*/\1${NEW_UID}:${NEW_GID}/" /etc/passwd;                if [ "$OLD_GID" != "$NEW_GID" ]; then                   sed -i -e "s/\([^:]*:[^:]*:\)${OLD_GID}:/\1${NEW_GID}:/" /etc/group;               fi;             chown -R $NEW_UID:$NEW_GID $HOME_FOLDER;        fi;
 ---> Running in b4267391cf4d
Remote user not found in /etc/passwd ($(id -u):$(id -g)).
Removing intermediate container b4267391cf4d
 ---> 618c3bd23246
Step 9/10 : ARG IMAGE_USER
 ---> Running in a2393b4fe5e0
Removing intermediate container a2393b4fe5e0
 ---> 4c0e0f67dc0a
Step 10/10 : USER $IMAGE_USER
 ---> Running in 1b2be6d99416
Removing intermediate container 1b2be6d99416
 ---> abade1b3d1ee
Successfully built abade1b3d1ee
Successfully tagged <image>-uid:latest
[9081 ms] Start: Run: docker -v
[9103 ms] Start: Run: docker events --format {{json .}} --filter event=start
[9105 ms] Start: Starting container
[9105 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/<path>,target=/workspaces/<path> --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=/home/<path> -l vsch.quality=stable -u=$(id -u):$(id -g) --entrypoint /bin/sh <image>-uid -c echo Container started
docker: Error response from daemon: unable to find user $(id -u): no matching entries in passwd file.
[10541 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/<path> --filter label=vsch.quality=stable
[10565 ms] Start: Run: docker inspect --type container 4d3a36f2fae1
[10559 ms] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/<path>,target=/workspaces/<path> --mount type=volume,src=vscode,dst=/vscode -l vsch.local.folder=/home/<path> -l vsch.quality=stable -u=$(id -u):$(id -g) --entrypoint /bin/sh <image>-uid -c echo Container started
[10559 ms] trap "exit 0" 15
[10560 ms] exec "$@"
[10560 ms] while sleep 1 & wait $!; do :; done -
[10560 ms]     at IR (/home/<user>/.vscode-remote-containers/dist/dev-containers-cli-0.234.0/dist/spec-node/devContainersSpecCLI.js:221:995)
[10560 ms]     at zy (/home/<user>/.vscode-remote-containers/dist/dev-containers-cli-0.234.0/dist/spec-node/devContainersSpecCLI.js:221:933)
[10561 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[10561 ms]     at async $R (/home/<user>/.vscode-remote-containers/dist/dev-containers-cli-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:2007)
[10561 ms]     at async Zy (/home/<user>/.vscode-remote-containers/dist/dev-containers-cli-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:3112)
[10561 ms]     at async BR (/home/<user>/.vscode-remote-containers/dist/dev-containers-cli-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:12448)
[10561 ms]     at async qR (/home/<user>/.vscode-remote-containers/dist/dev-containers-cli-0.234.0/dist/spec-node/devContainersSpecCLI.js:226:12204)
[10581 ms] Exit code 1
[10582 ms] Command failed: /home/<user>/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/node /home/<user>/.vscode-remote-containers/dist/dev-containers-cli-0.234.0/dist/spec-node/devContainersSpecCLI.js up --container-data-folder .vscode-server/data/Machine --container-system-data-folder /var/vscode-server --workspace-folder /home/<path> --workspace-mount-consistency cached --id-label vsch.local.folder=/home/<path> --id-label vsch.quality=stable --log-level debug --log-format json --config /home/<path>/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[10582 ms] Exit code 1
```
</details>

Steps to Reproduce:

1. Use this devcontainer.json with a `tensorflow/tensorflow` image
```jsonc
{
    "name": "${localWorkspaceFolderBasename}",
    "build": {
        "dockerfile": "../env/Dockerfile",
        "context": "../env",
    },
    "runArgs": [
        "-u=$(id -u):$(id -g)"
    ],
}
```
2. Open any folder in the container

Maybe I'm missing something and there is another way to reach the target and , but "remoteUser" and "containerUser" don't seem to help and the current way seems to be buggy with VSCode.
I am not quite clear why the `-uid` container is created.

I have now classified it as a bug, since it is a `runArg` that does not work. Maybe it could also be classified as a question, if I just chose the wrong way to solve this or as a feature request, if this behavior is currently just intentionally not possible/a known limitation?

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
Command substitution is tracked as https://github.com/microsoft/vscode-remote-release/issues/1050. Thanks.
