### ISSUE TITLE
`Rebuild Container` fails for broken multi root Workspace Container

### ISSUE THREAD

**Issue by alkatar21** [microsoft/vscode-remote-release#6790]
- VSCode Version: 1.67.2
- Local OS Version: Ubuntu 20.04.4
- Remote OS Version: Ubuntu 20.04.4
- Remote Extension/Connection Type: Containers
- Remote - Containers v0.234.0

In #387 and #1258 it was added that you can open workspaces directly in containers. If the creation of the container is successful, `Rebuild Container` works and the container gets rebuilt. If the build is unsuccessful and you then try `Rebuild Container` in that window, nothing happens except that it tries to activate extensions. With normal containers, however, this works without problems.

Steps to Reproduce:

1. Use any multi root workspace with a docker file that fails during build
2. `Remote-Containers: Open Workspace in Container`
3. Cancel the popup
4. `Remote-Containers: Rebuild Container`

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
The command's handler is never called. @alexdima Is this expected after the resolver failed?

From the window log:
```
[2022-06-08 08:53:42.324] [renderer11] [error] resolveAuthority(dev-container) returned an error after 27758 ms {"logTelemetry":false,"_code":"NotAvailable","_detail":true,"isHandled":true}
[2022-06-08 08:53:42.325] [renderer11] [error] Error received from starting extension host (kind: Remote)
[2022-06-08 08:53:42.325] [renderer11] [error] Error
    at k._resolveAuthority (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3181:7312)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async k._scanAndHandleExtensions (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3181:9299)
    at async k._initialize (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3179:22814)
[2022-06-08 08:53:42.325] [renderer11] [error] [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
[2022-06-08 08:53:42.325] [renderer11] [error] Error
    at k._resolveAuthority (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3181:7312)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async k._scanAndHandleExtensions (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3181:9299)
    at async k._initialize (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3179:22814)
[2022-06-08 08:53:42.326] [renderer11] [error] Error
    at k._resolveAuthority (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3181:7312)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async k._scanAndHandleExtensions (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3181:9299)
    at async k._initialize (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3179:22814)
```

**Comment by chrmarti** [comment]
I can also confirm that the command is called when not using a multi-root workspace, but a single folder.

**Comment by chrmarti** [comment]
This appears to be specific to multi-root workspaces.

**Comment by alexdima** [comment]
@chrmarti Do you have an example of a Dockerfile that fails during build? I would like to try to reproduce and debug this.

**Comment by alkatar21** [comment]
@alexdima Everything that let the container fail. I just tested it by changing the base image to one that does not exist:

```
FROM tensorflow/tensorflow:3.10.0
```
