### ISSUE TITLE
2FA not working

### ISSUE THREAD

**Issue by goldman7911** [microsoft/vscode-remote-release#6791]
- VSCode Version: 1.67.2
- Local OS Version: Windows 11 Pro 21H2 22000.675
- Remote OS Version: 
- Remote Extension/Connection Type: SSH/Containers/WSL: SSH

Steps to Reproduce:

Remote linux behind password vault system that requires two factor auth isn't possible to type it after request.

```
Warning: Password input may be echoed.
Two-Factor Token: 
```

- Logs:

"remote.SSH.showLoginTerminal": true only
https://github.com/microsoft/vscode-remote-release/issues/6724#issuecomment-1142686928

"remote.SSH.showLoginTerminal": true &&
"remote.SSH.useLocalServer": true
https://github.com/microsoft/vscode-remote-release/issues/6724#issuecomment-1147878524

ssh config

```
Host SERVER
	HostName 10.124.65.198
	User allowedUser[OSuser@10.124.68.199]
	ServerAliveInterval 10
```

I have tried to bypass using ControMaster but it still requires token.

ControlMaster auto
ControlPath C:\Users\janki\.ssh\%r@%h:%p

**Comment by tanhakabir** [comment]
Thanks for filing another issue! Taking a look now

**Comment by tanhakabir** [comment]
Hm I'm not completely convinced this will resolve it for you but what happens when you have `"remote.SSH.showLoginTerminal": false` and `"remote.SSH.useLocalServer": true`?

**Comment by goldman7911** [comment]
Thanks for your help @tanhakabir 



```
[08:53:47.456] Log Level: 2
[08:53:47.456] remote-ssh@0.80.0
[08:53:47.457] win32 x64
[08:53:47.460] SSH Resolver called for "ssh-remote+10.124.65.198", attempt 1
[08:53:47.460] "remote.SSH.useLocalServer": true
[08:53:47.460] "remote.SSH.path": undefined
[08:53:47.460] "remote.SSH.configFile": C:\Users\janki\.ssh\config
[08:53:47.460] "remote.SSH.useFlock": true
[08:53:47.460] "remote.SSH.lockfilesInTmp": false
[08:53:47.461] "remote.SSH.localServerDownload": auto
[08:53:47.461] "remote.SSH.remoteServerListenOnSocket": false
[08:53:47.461] "remote.SSH.showLoginTerminal": false
[08:53:47.461] "remote.SSH.defaultExtensions": []
[08:53:47.461] "remote.SSH.loglevel": 2
[08:53:47.461] "remote.SSH.maxReconnectionAttempts": 0
[08:53:47.461] "remote.SSH.enableDynamicForwarding": true
[08:53:47.461] "remote.SSH.enableRemoteCommand": false
[08:53:47.461] "remote.SSH.serverPickPortsFromRange": {}
[08:53:47.461] "remote.SSH.serverInstallPath": {}
[08:53:47.471] SSH Resolver called for host: 10.124.65.198
[08:53:47.471] Setting up SSH remote "10.124.65.198"
[08:53:47.473] Acquiring local install lock: C:\Users\janki\AppData\Local\Temp\vscode-remote-ssh-d31d6ab6-install.lock
[08:53:47.484] Looking for existing server data file at c:\Users\janki\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-ssh\vscode-ssh-host-d31d6ab6-4af164ea3a06f701fe3e89a2bcbb421d2026b68f-0.80.0\data.json
[08:53:47.484] Using commit id "4af164ea3a06f701fe3e89a2bcbb421d2026b68f" and quality "stable" for server
[08:53:47.486] Install and start server if needed
[08:53:47.490] Checking ssh with "ssh -V"
[08:53:47.511] > OpenSSH_for_Windows_8.1p1, 
[08:53:47.511] > LibreSSL 3.0.2

[08:53:47.513] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[08:53:47.533] > OpenSSH_for_Windows_8.1p1, 
[08:53:47.533] > LibreSSL 3.0.2

[08:53:47.534] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[08:53:47.781] > OpenSSH_9.0p1, OpenSSL 1.1.1o  3 May 2022

[08:53:47.784] Using SSH config file "C:\Users\janki\.ssh\config"
[08:53:47.785] askpass server listening on \\.\pipe\vscode-ssh-askpass-4fc9e02b3c1a4341631e145b51ddee7856e3cc8c-sock
[08:53:47.785] Spawning local server with {"serverId":1,"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-ffbcc7aaa1241717b1cd5373a08afac15ffb3e17-sock","sshCommand":"C:\\Program Files\\Git\\usr\\bin\\ssh.exe","sshArgs":["-v","-T","-D","51278","-F","C:\\Users\\janki\\.ssh\\config","10.124.65.198"],"serverDataFolderName":".vscode-server","dataFilePath":"c:\\Users\\janki\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-vscode-remote.remote-ssh\\vscode-ssh-host-d31d6ab6-4af164ea3a06f701fe3e89a2bcbb421d2026b68f-0.80.0\\data.json"}
[08:53:47.785] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"c:\\Users\\janki\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.80.0\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"C:\\Users\\janki\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"c:\\Users\\janki\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.80.0\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-4fc9e02b3c1a4341631e145b51ddee7856e3cc8c-sock"}
[08:53:47.790] Spawned 14880
[08:53:47.865] > local-server-1> Spawned ssh, pid=12588
[08:53:47.916] stderr> OpenSSH_9.0p1, OpenSSL 1.1.1o  3 May 2022
[08:53:48.072] stderr> debug1: Server host key: ssh-ed25519 SHA256:Q1B+xAA7IZS8hDkECVAVj25D9jECoLgry20zbXbAGDk
[08:53:48.323] Got askpass request: {"request":"80762426[bpadmin@10.124.68.199]@10.124.65.198's password: "}
[08:53:48.324] Showing password prompt
[08:53:48.324] Listening for interwindow password on \\.\pipe\vscode-ssh-askpass-59f6ef0bf7bcc71ae5bc0d55332e1de3459b2fce-sock
[08:53:48.324] Writing password prompt to globalState
[08:53:50.651] Got password response
[08:53:50.651] Interactor gave response: *************
[08:53:50.651] Cleaning up other-window auth server
[08:53:55.908] stderr> Permission denied, please try again.
[08:53:56.001] Got askpass request: {"request":"80762426[bpadmin@10.124.68.199]@10.124.65.198's password: "}
[08:53:56.001] Showing password prompt
[08:53:56.002] Listening for interwindow password on \\.\pipe\vscode-ssh-askpass-28375414637e4e79f8dc146dd8890a4346abcac6-sock
[08:53:56.002] Writing password prompt to globalState
[08:54:04.475] Got password response
[08:54:04.475] Interactor gave response: ***************
[08:54:04.475] Cleaning up other-window auth server
[08:54:07.132] stderr> Authenticated to 10.124.65.198 ([10.124.65.198]:22) using "password".
[08:54:07.227] > 
> The programs included with the Debian GNU/Linux system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
> permitted by applicable law.
[08:54:08.280] stderr> Warning: Password input may be echoed.
[08:54:08.280] stderr> Two-Factor Token: 
[08:54:13.693] stderr> Transferred: sent 2492, received 2520 bytes, in 6.6 seconds
[08:54:13.694] stderr> Bytes per second: sent 380.3, received 384.6
[08:54:13.696] > local-server-1> ssh child died, shutting down
[08:54:13.700] Local server exit: 0
[08:54:13.700] Received install output: local-server-1> Spawned ssh, pid=12588
OpenSSH_9.0p1, OpenSSL 1.1.1o  3 May 2022
debug1: Server host key: ssh-ed25519 SHA256:Q1B+xAA7IZS8hDkECVAVj25D9jECoLgry20zbXbAGDk
Permission denied, please try again.
Authenticated to 10.124.65.198 ([10.124.65.198]:22) using "password".

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Warning: Password input may be echoed.
Two-Factor Token: 
Transferred: sent 2492, received 2520 bytes, in 6.6 seconds
Bytes per second: sent 380.3, received 384.6
local-server-1> ssh child died, shutting down

[08:54:13.702] Resolver error: Error: Permission denied, please try again.
	at Function.Create (c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:585789)
	at c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:583840
	at Object.t.handleInstallOutput (c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:584363)
	at Object.e [as tryInstallWithLocalServer] (c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:624908)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:643945
	at async Object.t.withShowDetailsEvent (c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:647692)
	at async c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:623380
	at async b (c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:619886)
	at async Object.t.resolveWithLocalServer (c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:622995)
	at async Object.t.resolve (c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:645302)
	at async c:\Users\janki\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:722509
[08:54:13.705] ------

```

**Comment by tanhakabir** [comment]
Sorry about the slow reply! I missed this in my notifications. 

Could you also try with `"remote.SSH.showLoginTerminal": false` and `"remote.SSH.useLocalServer": false`?

**Comment by tanhakabir** [comment]
Closing due to inactivity
