### ISSUE TITLE
Failed to parse remote port from server output

### ISSUE THREAD

**Issue by caipang** [microsoft/vscode-remote-release#6792]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.2
- OS Version:dbian 10 x

Steps to Reproduce:

1.when I was try ssh to self-made linux system,Remote ssh  has been occured wrong message in the below.

           [17:57:50.368] Failed to parse remote port from server output
          [17:57:50.369] Resolver error: Error: 
	          at Function.Create (c:\Users\bing\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:585789)
	          at Object.t.handleInstallOutput (c:\Users\bing\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:584441)
	          at Object.t.tryInstall (c:\Users\bing\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:681707)
	          at processTicksAndRejections (node:internal/process/task_queues:96:5)
	          at async c:\Users\bing\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:644347
	          at async Object.t.withShowDetailsEvent (c:\Users\bing\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:647692)
	          at async Object.t.resolve (c:\Users\bing\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:645426)
	          at async c:\Users\bing\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:722509
 
If you recovary me ,I will appreciate

**Comment by caipang** [comment]
[14:17:12.893] > f5921413f9b2: running
[14:17:12.908] > Unsupported platform: 4.20.1
> f5921413f9b2: start
> exitCode==35==
> listeningOn====
> osReleaseId==debian==
> arch====
> tmpDir==/run/user/0==
> platform====
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> f5921413f9b2: end
[14:17:12.908] Received install output: 
exitCode==35==
listeningOn====
osReleaseId==debian==
arch====
tmpDir==/run/user/0==
platform====
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[14:17:12.909] Failed to parse remote port from server output
[14:17:12.910] Resolver error: Error: 
	at Function.Create (c:\Users\bing\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:585789)
	at Object.t.handleInstallOutput (c:\Users\bing\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:584441)
	at Object.t.tryInstall (c:\Users\bing\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:681707)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\bing\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:644347
	at async Object.t.withShowDetailsEvent (c:\Users\bing\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:647692)
	at async Object.t.resolve (c:\Users\bing\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:645426)
	at async c:\Users\bing\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:722509
[14:17:12.915] ------


That is all.
