### ISSUE TITLE
Remote Container fails to open in VS Code

### ISSUE THREAD

**Issue by machikoyasuda** [microsoft/vscode-remote-release#6796]
Hi - I use VS Code Remote-Containers everyday, but have been unable to successfully use it for the last two days. This is the repository I am trying to open: https://github.com/cal-itp/benefits and the instructions I am following: https://docs.calitp.org/benefits/getting-started/ and https://docs.calitp.org/benefits/development/. I am able to successfully open the repository locally, but not with Remote Containers. I've tried it with the latest VS Code Insiders as well. Any help would be appreciated! Thank you.

---

- **VSCode Version:** 1.67.2 (Universal) 

```Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:20:57.384Z (2 wks ago)
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.5.0
```

- **Local OS Version:** macOS Monterey 12.4 on Apple M1 Pro
- **Remote OS Version:** 
- **Remote Extension/Connection Type:** SSH/**Containers**/WSL - `v0.234.0`
- **Docker Version**: 4.9.0 
- **Compose File**: https://github.com/cal-itp/benefits/blob/dev/.devcontainer/compose.yml
- **Logs**: Logs with the latest https://code.visualstudio.com/insiders/

```bash
[2022-06-07T21:47:46.470Z] Remote-Containers 0.238.0 in VS Code 1.68.0-insider (b7faf235467dd56e4a62e52e7f1cacf875b67261).
[2022-06-07T21:47:46.470Z] Start: Resolving Remote
[2022-06-07T21:47:46.476Z] Setting up container for folder or workspace: /Users/machikoyasuda/cal-itp/benefits
[2022-06-07T21:47:46.477Z] Start: Check Docker is running
[2022-06-07T21:47:46.477Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2022-06-07T21:47:46.554Z] Stop (77 ms): Run: docker version --format {{.Server.APIVersion}}
[2022-06-07T21:47:46.554Z] Server API version: 1.41
[2022-06-07T21:47:46.554Z] Stop (77 ms): Check Docker is running
[2022-06-07T21:47:46.554Z] Start: Run: docker volume ls -q
[2022-06-07T21:47:46.614Z] Stop (60 ms): Run: docker volume ls -q
[2022-06-07T21:47:46.622Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/machikoyasuda/cal-itp/benefits --filter label=vsch.quality=insider
[2022-06-07T21:47:46.678Z] Stop (56 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/Users/machikoyasuda/cal-itp/benefits --filter label=vsch.quality=insider
[2022-06-07T21:47:46.679Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/machikoyasuda/cal-itp/benefits
[2022-06-07T21:47:46.751Z] Stop (72 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/machikoyasuda/cal-itp/benefits
[2022-06-07T21:47:46.752Z] Start: Run: /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper /Users/machikoyasuda/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.238.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/machikoyasuda/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/machikoyasuda/cal-itp/benefits --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/machikoyasuda/cal-itp/benefits --log-level debug --log-format json --config /Users/machikoyasuda/cal-itp/benefits/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-06-07T21:47:46.844Z] remote-containers 0.238.0.
[2022-06-07T21:47:46.844Z] Start: Run: docker buildx version
[2022-06-07T21:47:46.954Z] Stop (110 ms): Run: docker buildx version
[2022-06-07T21:47:46.955Z] Start: Resolving Remote
[2022-06-07T21:47:46.956Z] Start: Run: docker-compose version --short
[2022-06-07T21:47:47.212Z] Stop (256 ms): Run: docker-compose version --short
[2022-06-07T21:47:47.212Z] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=benefits_devcontainer --filter label=com.docker.compose.service=dev
[2022-06-07T21:47:47.286Z] Stop (74 ms): Run: docker ps -q -a --filter label=com.docker.compose.project=benefits_devcontainer --filter label=com.docker.compose.service=dev
[2022-06-07T21:47:47.286Z] Start: Run: docker-compose -f /Users/machikoyasuda/cal-itp/benefits/.devcontainer/compose.yml config
[2022-06-07T21:47:47.581Z] Stop (295 ms): Run: docker-compose -f /Users/machikoyasuda/cal-itp/benefits/.devcontainer/compose.yml config
[2022-06-07T21:47:47.582Z] Error: Command failed: docker-compose -f /Users/machikoyasuda/cal-itp/benefits/.devcontainer/compose.yml config
[2022-06-07T21:47:47.582Z]     at Ta (/Users/machikoyasuda/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.238.0/dist/spec-node/devContainersSpecCLI.js:230:813)
[2022-06-07T21:47:47.582Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-06-07T21:47:47.582Z]     at async _R (/Users/machikoyasuda/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.238.0/dist/spec-node/devContainersSpecCLI.js:204:1250)
[2022-06-07T21:47:47.582Z]     at async OR (/Users/machikoyasuda/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.238.0/dist/spec-node/devContainersSpecCLI.js:188:2240)
[2022-06-07T21:47:47.582Z]     at async zR (/Users/machikoyasuda/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.238.0/dist/spec-node/devContainersSpecCLI.js:245:2177)
[2022-06-07T21:47:47.582Z]     at async ib (/Users/machikoyasuda/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.238.0/dist/spec-node/devContainersSpecCLI.js:245:3110)
[2022-06-07T21:47:47.582Z]     at async JR (/Users/machikoyasuda/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.238.0/dist/spec-node/devContainersSpecCLI.js:245:13046)
[2022-06-07T21:47:47.582Z]     at async KR (/Users/machikoyasuda/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.238.0/dist/spec-node/devContainersSpecCLI.js:245:12802)
[2022-06-07T21:47:47.583Z] Stop (831 ms): Run: /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper /Users/machikoyasuda/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.238.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/machikoyasuda/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/machikoyasuda/cal-itp/benefits --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/machikoyasuda/cal-itp/benefits --log-level debug --log-format json --config /Users/machikoyasuda/cal-itp/benefits/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-06-07T21:47:47.583Z] Exit code 1
[2022-06-07T21:47:47.585Z] Command failed: /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper /Users/machikoyasuda/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.238.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/machikoyasuda/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/machikoyasuda/cal-itp/benefits --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/machikoyasuda/cal-itp/benefits --log-level debug --log-format json --config /Users/machikoyasuda/cal-itp/benefits/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-06-07T21:47:47.585Z] Exit code 1
```
---

Steps to Reproduce:

1. `git clone https://github.com/cal-itp/benefits` (https://github.com/cal-itp/benefits)
2. `cd benefits/.devcontainer`
3. `touch .env`
4. Open `benefits` in VS Code
5. Open app with `Remote Containers: Rebuild and Reopen in Remote Container`
6. Container fails to open

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3673236/172489212-95c31b2b-f3c5-48f2-a1e5-be54024038c3.png">

Does this issue occur when you try this locally?: **No**
Does this issue occur when you try this locally and all extensions are disabled?: **No**

**Comment by machikoyasuda** [comment]
Update: Removing the top-level `name:` field in the `compose.yml` file fixed my issue.

https://github.com/cal-itp/benefits/blob/dev/.devcontainer/compose.yml#L1

**Comment by machikoyasuda** [comment]
Update: Checking `User Docker Compose v2` in Docker.app fixed the issue as well (without having to remove the top-level `name:` field)

<img width="589" alt="image" src="https://user-images.githubusercontent.com/3673236/172504521-d2974170-387b-49f8-b859-d8236399ac64.png">
