### ISSUE TITLE
ServerThe editor could not be opened due to an unexpected error: No file system provider found for source vscode-remote://ssh-remote

### ISSUE THREAD

**Issue by daniel-alvarado-intel** [microsoft/vscode-remote-release#6808]
- VSCode Version:
- Local OS Version:
- Remote OS Version:
- Remote Extension/Connection Type: SSH/
- Logs:
- [22:28:50.475] Log Level: 2
[22:28:50.479] remote-ssh@0.80.0
[22:28:50.480] win32 x64
[22:28:50.621] SSH Resolver called for "ssh-remote+simcloud", attempt 1
[22:28:50.636] "remote.SSH.useLocalServer": false
[22:28:50.637] "remote.SSH.showLoginTerminal": false
[22:28:50.638] "remote.SSH.remotePlatform": {"simcloud":"linux"}
[22:28:50.638] "remote.SSH.path": undefined
[22:28:50.638] "remote.SSH.configFile": undefined
[22:28:50.639] "remote.SSH.useFlock": true
[22:28:50.639] "remote.SSH.lockfilesInTmp": false
[22:28:50.639] "remote.SSH.localServerDownload": auto
[22:28:50.639] "remote.SSH.remoteServerListenOnSocket": false
[22:28:50.639] "remote.SSH.showLoginTerminal": false
[22:28:50.639] "remote.SSH.defaultExtensions": []
[22:28:50.639] "remote.SSH.loglevel": 2
[22:28:50.640] "remote.SSH.enableDynamicForwarding": true
[22:28:50.640] "remote.SSH.enableRemoteCommand": false
[22:28:50.640] "remote.SSH.serverPickPortsFromRange": {}
[22:28:50.640] "remote.SSH.serverInstallPath": {}
[22:28:50.690] SSH Resolver called for host: simcloud
[22:28:50.690] Setting up SSH remote "simcloud"
[22:28:50.721] Using commit id "4af164ea3a06f701fe3e89a2bcbb421d2026b68f" and quality "stable" for server
[22:28:50.763] Install and start server if needed
[22:28:50.791] Checking ssh with "ssh -V"
[22:28:50.982] > OpenSSH_for_Win
[22:28:50.983] > dows_8.1p1, LibreSSL 3.0.2

[22:28:50.991] Running script with connection command: ssh -T -D 59831 simcloud bash
[22:28:50.995] Terminal shell path: C:\windows\System32\cmd.exe
[22:28:52.376] > ]0;C:\windows\System32\cmd.exe
[22:28:52.382] Got some output, clearing connection timeout
[22:28:52.432] > ssh: Could not resolve hostname csccl38029.zsc2.intel.com: No such host is known
> .
> The process tried to write to a nonexistent pipe.
[22:28:53.550] "install" terminal command done
[22:28:53.552] Install terminal quit with output: .
[22:28:53.552] Received install output: .
[22:28:53.560] Failed to parse remote port from server output
[22:28:53.561] Resolver error: Error: 
	at Function.Create (c:\Users\dalvara2\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:585789)
	at Object.t.handleInstallOutput (c:\Users\dalvara2\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:584441)
	at Object.t.tryInstall (c:\Users\dalvara2\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:681707)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\dalvara2\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:644347
	at async Object.t.withShowDetailsEvent (c:\Users\dalvara2\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:647692)
	at async Object.t.resolve (c:\Users\dalvara2\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:645426)
	at async c:\Users\dalvara2\.vscode\extensions\ms-vscode-remote.remote-ssh-0.80.0\out\extension.js:1:722509
[22:28:53.593] ------

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by tanhakabir** [comment]
Are you able to run `echo "echo hello" | ssh -T -D 59831 simcloud bash`?

**Comment by daniel-alvarado-intel** [comment]
Yes, that works on my cmd line. I'm on windows

**Comment by tanhakabir** [comment]
> Yes, that works on my cmd line. I'm on windows

What about powershell?

**Comment by tanhakabir** [comment]
Hm what version of VS Code are you on?

**Comment by gaddman** [comment]
Two other errors, perhaps related:

1. Attempting to uninstall the Remote-SSH extension (v0.82.0) fails with the message _Cannot resolve authority_.
2. Attempting to open the SSH configuration file fails with the message _Command 'Remote-SSH: Open SSH Configuration File...' resulted in an error (command 'opensshremotes.openConfigFile' not found)_

**Comment by insalt-glitch** [comment]
I experienced a similar error when opening a file that I do not have the permission to read. Did you check the permission on the remote, in particular of the files from `~/.vscode-server`?

**Comment by godhack97** [comment]
loging in remote ssh server and write commands.
rm -rf .vscode-remote-containers/
rm -rf .vscode-server/

**Comment by tanhakabir** [comment]
This seems like it was potentially issues with a corrupt state or bad file permissions. Closing for now but let me know if you see this issue again!
