### ISSUE TITLE
Dockerfile-with-features comment on same line as ARG causes "ARG requires exactly one argument definition "

### ISSUE THREAD

**Issue by pF-luis** [microsoft/vscode-remote-release#6819]
- VSCode Version: 1.68.0
- Local OS Version: WSL2 Ubuntu 22.04 LTS on Windows 10 Pro(Build 19044.1706)
- Remote OS Version: php dev container(https://github.com/microsoft/vscode-dev-containers/tree/v0.238.0/containers/php/.devcontainer) should be debian bullseye
- Remote Extension/Connection Type: Containers
- OCI Runtime: **podman**
- Logs:
```
[93 ms] Remote-Containers 0.238.2 in VS Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f).
[92 ms] Start: Run: wsl -d Ubuntu-20.04 -e wslpath -u \\wsl$\Ubuntu-20.04\home\user\projects\aProject
[326 ms] Start: Resolving Remote
[451 ms] Start: Run: wsl -d Ubuntu-20.04 -e wslpath -u \\wsl$\Ubuntu-20.04\home\user\projects\aProject
[681 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/user/projects/aProject' && /bin/sh
[699 ms] Start: Run in host: id -un
[796 ms] user
[797 ms] 
[797 ms] Start: Run in host: cat /etc/passwd
[800 ms] Start: Run in host: echo ~
[801 ms] /home/user
[801 ms] 
[802 ms] Start: Run in host: test -x '/home/user/.vscode-remote-containers/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/node'
[803 ms] 
[804 ms] 
[804 ms] Exit code 1
[805 ms] Start: Run in host: test -x '/home/user/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/node'
[806 ms] 
[806 ms] 
[807 ms] Start: Run in host: test -f '/home/user/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/node_modules/node-pty/package.json'
[808 ms] 
[808 ms] 
[808 ms] Start: Run in host: test -f '/home/user/.vscode-remote-containers/dist/vscode-remote-containers-server-0.238.2.js'
[809 ms] 
[809 ms] 
[814 ms] userEnvProbe: loginInteractiveShell (default)
[815 ms] userEnvProbe shell: /bin/bash
[1287 ms] userEnvProbe PATHs:
Probe:     '***'
Container: None
[1289 ms] Setting up container for folder or workspace: /home/user/projects/aProject
[1292 ms] Start: Check Docker is running
[1292 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[1674 ms] Server API version: 3.4.4
[1676 ms] Start: Run in Host: docker volume ls -q
[2073 ms] Start: Run in Host: docker ps -q -a --filter label=vsch.local.folder=\\wsl$\Ubuntu-20.04\home\user\projects\aProject --filter label=vsch.quality=stable
[2538 ms] Start: Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=\\wsl$\Ubuntu-20.04\home\user\projects\aProject
[2906 ms] Start: Run in Host: /home/user/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/node /home/user/.vscode-remote-containers/dist/dev-containers-cli-0.238.2/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /home/user/projects/aProject --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl$\Ubuntu-20.04\home\user\projects\aProject --log-level debug --log-format json --config /home/user/projects/aProject/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[3102 ms] remote-containers 0.238.2.
[3102 ms] Start: Run: docker buildx version
[3137 ms] Start: Resolving Remote
[3142 ms] Start: Run: git rev-parse --show-cdup
[3147 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=\\wsl$\Ubuntu-20.04\home\user\projects\aProject
[3432 ms] Preparing to parse declared features and fetch remote features.
[3432 ms] Detected local feature set. Continuing...
[3435 ms] local container features stored at: /home/user/.vscode-remote-containers/dist/dev-containers-cli-0.238.2/dist/node_modules/vscode-dev-containers/container-features
[3438 ms] Start: Run: tar --no-same-owner -x -f -
[3480 ms] Start: Run: docker build -t dev_container_feature_content_temp -f /tmp/vsch/container-features/0.238.2-1655108583660/Dockerfile.buildContent /tmp/vsch/container-features/0.238.2-1655108583660
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
STEP 1/2: FROM scratch
STEP 2/2: COPY . /tmp/build-features/
--> Using cache 2e090abf2772a70b985f4b40a07a898710cfd0f5eef7217a373dbc3c28bb1134
COMMIT dev_container_feature_content_temp
--> 2e090abf277
Successfully tagged localhost/dev_container_feature_content_temp:latest
2e090abf2772a70b985f4b40a07a898710cfd0f5eef7217a373dbc3c28bb1134
[4250 ms] Start: Run: docker build -f /tmp/vsch/container-features/0.238.2-1655108583660/Dockerfile-with-features -t vsc-aProject-b7ad2a2a6e76e75f9d0ddce4e4529b45 --build-arg VARIANT=8.1 --build-arg NODE_VERSION=lts/* --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=vscode --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /home/user/projects/aProject/.devcontainer
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Error: error reading multiple stages: ARG requires exactly one argument definition
[4478 ms] Error: Command failed: docker build -f /tmp/vsch/container-features/0.238.2-1655108583660/Dockerfile-with-features -t vsc-aProject-b7ad2a2a6e76e75f9d0ddce4e4529b45 --build-arg VARIANT=8.1 --build-arg NODE_VERSION=lts/* --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=vscode --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /home/user/projects/aProject/.devcontainer
[4479 ms]     at jR (/home/user/.vscode-remote-containers/dist/dev-containers-cli-0.238.2/dist/spec-node/devContainersSpecCLI.js:240:1143)
[4479 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[4479 ms]     at async Uu (/home/user/.vscode-remote-containers/dist/dev-containers-cli-0.238.2/dist/spec-node/devContainersSpecCLI.js:239:2142)
[4479 ms]     at async Jy (/home/user/.vscode-remote-containers/dist/dev-containers-cli-0.238.2/dist/spec-node/devContainersSpecCLI.js:239:1168)
[4479 ms]     at async zR (/home/user/.vscode-remote-containers/dist/dev-containers-cli-0.238.2/dist/spec-node/devContainersSpecCLI.js:245:2006)
[4479 ms]     at async nb (/home/user/.vscode-remote-containers/dist/dev-containers-cli-0.238.2/dist/spec-node/devContainersSpecCLI.js:245:3110)
[4479 ms]     at async JR (/home/user/.vscode-remote-containers/dist/dev-containers-cli-0.238.2/dist/spec-node/devContainersSpecCLI.js:245:13046)
[4479 ms]     at async KR (/home/user/.vscode-remote-containers/dist/dev-containers-cli-0.238.2/dist/spec-node/devContainersSpecCLI.js:245:12802)
[4483 ms] Exit code 1
[4489 ms] Command failed: /home/user/.vscode-server/bin/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/node /home/user/.vscode-remote-containers/dist/dev-containers-cli-0.238.2/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /home/user/projects/aProject --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl$\Ubuntu-20.04\home\user\projects\aProject --log-level debug --log-format json --config /home/user/projects/aProject/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[4489 ms] Exit code 1

```

Steps to Reproduce:

1. Use "Reopen in Container"
2. Choose a container definition, in my case it was the "PHP" one
3. let it open the new window and try to build the container until it files

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

The problem seems to be that (I assume) this extension adds a comment after/on the same line as ARG=... statement within the `Dockerfile-with-features` Dockerfile.  
Whenever I try to reopen my project within a container, a new folder in `/tmp/vsch/container-features` is created with the naming convention of `0.238.2-*....`  
Within these folders there is a Docker-with-features Dockerfile which is used to build a container, as it can be seen in the logs above.  
 These files always start with
```
ARG _DEV_CONTAINERS_BASE_IMAGE=placeholder # will be overridden by build args passed to CLI
```
Now when I remove the comment or place it into the next line, I can build it with the command displayed within the logs, without modifying the file I get the same error. Problem is vscode, or presumably this extension will create a new folder with a new Docker-with-features file in it as soon as I try to rerun the whole process from vscode.
  
It also seemed that this happened from one day to another, where a Project was still running fine from yesterday within a container and the next day when I tried to reopen another project within a container, this happenend.

Any hints are appreciated, thanks.

**Comment by chrmarti** [comment]
What do you get for running `docker buildx version `? Maybe this is using newer syntax.

**Comment by chrmarti** [comment]
Also: You can use `F1` > `Extensions: Install Specific Version of Extension...` to install Remote-Containers 0.234.0 (the previous stable release) as a workaround.

**Comment by pF-luis** [comment]
Thanks for the fast reply, I'll try it tomorrow, much obliged.

**Comment by pF-luis** [comment]
Alright, just tried it out.
Now the command `docker buildx version` does not seem to work with podman, instead maybe this helps:
```
$ buildah --version
buildah version 1.23.1 (image-spec 1.0.1, runtime-spec 1.0.2-dev)
$ podman --version
podman version 3.4.4
```

Downgrading to 0.234.0 made it run again, the Dockerfile within `/tmp/vsch/container-features` does not seem to have any comments in it.

Might be that podman is really lacking this while docker probably supports/allows for comments in the same line after an `ARG`. And also ubuntu being quite behind on the podman releases, could be that newer podman releases already allow for this.

**Comment by pF-luis** [comment]
I've tested this with build from source podman 4.1 and it seems to work just fine now with a comment on the same line as an `ARG` / with the newest release of remote containers. So this seems to just be a compatibility issue with older podman releases.

**Comment by pF-luis** [comment]
So for anyone encountering this issue, either:
* Downgrade the vscode extension to 0.234.0
* build a newer podman from source and use that
* use these prebuild binaries from this podman fork https://github.com/liebig/podman (these were compiled on ubuntu 22.04)

**Comment by chrmarti** [comment]
Remote-Containers 0.240.0 pre-release no longer uses the comment. (You can switch Remote-Containers to pre-release versions from the Extensions viewlet.)
