### ISSUE TITLE
REMOTE-SSH:connect to Host...Failure

### ISSUE THREAD

**Issue by markBosley** [microsoft/vscode-remote-release#6823]
I've been using Remote-SSH extension successfully with a few Raspberry Pi 4's. After a hiatus I have discovered I cannot connect to two of my machines. I've tried ip addresses and hostnames. neither works now. I've rebooted the Raspberry Pi's and My windows 11 machine to no avail.

- VSCode Version: 1.68.0 (user setup)
- Local OS Version: Windows_11
- Remote OS Version: NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1.Remote-SSH:Connect to Host...
2. Select Host from config.. Either older proven to work device or a new host with  newest OS Bullseye

Failed to Load message bundle dialog appears and once exiting dialog the following log is dumped

[16:33:39.817] Running script with connection command: ssh -T -D 61116 "RASPBERRYPI.byIP" bash
[16:33:39.820] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[16:33:40.411] > The authenticity of host '192.168.1.34 (192.168.1.34)' can't be established.
> ED25519 key fingerprint is SHA256:e49VCc2+o4UnmcOkR1W/GptMrkVxZphxrhmS/Fs8Bws.
> This key is not known by any other names
> Are you sure you want to continue connecting (yes/no/[fingerprint])?]0;C:\WINDOWS\System32\cmd.exe
[16:33:40.411] Got some output, clearing connection timeout
[16:33:40.412] Detected fingerprint confirmation message
[16:33:40.412] Showing fingerprint confirmation dialog
[16:33:45.082] Fingerprint dialog canceled
[16:33:45.083] "install" terminal command canceled
[16:33:45.084] Resolver error: Error: Failed to load message bundle. See console for details.
	at Function.Canceled (c:\Users\bosle\.vscode\extensions\ms-vscode-remote.remote-ssh-0.82.0\out\extension.js:1:585415)
	at c:\Users\bosle\.vscode\extensions\ms-vscode-remote.remote-ssh-0.82.0\out\extension.js:1:680272
	at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by tanhakabir** [comment]
Sorry about `Failed to Load message bundle dialog`. It's a bug from: https://github.com/microsoft/vscode-remote-release/issues/6822

Could you try this again so we can get a clear error message?
