### ISSUE TITLE
"Failed to parse remote port from server output"

### ISSUE THREAD

**Issue by abhi3700** [microsoft/vscode-remote-release#6854]
- VSCode Version: 1.68.1
- Local OS Version: macOS v12.4
- Remote OS Version: Ubuntu 20.04 VM instance on Lima
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. I create a dockered Linux VM using `lima`. [Source](https://github.com/abhi3700/my_coding_toolkit/blob/master/vm_all.md#use-vscode-editor)
2. But, I face this issue when opening folders on VSCode using `remote-ssh` extension. Following is the error:

```
[15:02:48.225] Log Level: 2
[15:02:48.226] remote-ssh@0.82.1
[15:02:48.226] darwin arm64
[15:02:48.228] SSH Resolver called for "ssh-remote+lima-docker", attempt 1
[15:02:48.231] "remote.SSH.useLocalServer": true
[15:02:48.231] "remote.SSH.path": ssh://127.0.0.1:53170
[15:02:48.231] "remote.SSH.configFile": /Users/abhi3700/.lima/_config/user
[15:02:48.231] "remote.SSH.useFlock": true
[15:02:48.232] "remote.SSH.lockfilesInTmp": false
[15:02:48.232] "remote.SSH.localServerDownload": auto
[15:02:48.232] "remote.SSH.remoteServerListenOnSocket": false
[15:02:48.232] "remote.SSH.showLoginTerminal": false
[15:02:48.232] "remote.SSH.defaultExtensions": []
[15:02:48.232] "remote.SSH.loglevel": 2
[15:02:48.233] "remote.SSH.enableDynamicForwarding": true
[15:02:48.233] "remote.SSH.enableRemoteCommand": true
[15:02:48.233] "remote.SSH.serverPickPortsFromRange": {}
[15:02:48.233] "remote.SSH.serverInstallPath": {}
[15:02:48.241] SSH Resolver called for host: lima-docker
[15:02:48.241] Setting up SSH remote "lima-docker"
[15:02:48.242] Acquiring local install lock: /var/folders/cw/dc7mkcsd6yx76lscv6w1hpcw0000gn/T/vscode-remote-ssh-5360525f-install.lock
[15:02:48.248] Looking for existing server data file at /Users/abhi3700/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-5360525f-30d9c6cd9483b2cc586687151bcbcd635f373630-0.82.1/data.json
[15:02:48.249] Using commit id "30d9c6cd9483b2cc586687151bcbcd635f373630" and quality "stable" for server
[15:02:48.251] Install and start server if needed
[15:02:48.253] Checking ssh with "ssh://127.0.0.1:53170 -V"
[15:02:48.253] Got error from ssh: spawn ssh://127.0.0.1:53170 ENOENT
[15:02:48.253] The specified path ssh://127.0.0.1:53170 is not a valid SSH binary
[15:02:48.254] PATH: /Users/abhi3700/.rvm/gems/ruby-2.7.5/bin:/Users/abhi3700/.rvm/gems/ruby-2.7.5@global/bin:/Users/abhi3700/.rvm/rubies/ruby-2.7.5/bin:/Users/abhi3700/.rbenv/bin:/Users/abhi3700/.yarn/bin:/Users/abhi3700/.config/yarn/global/node_modules/.bin:/Users/abhi3700/opt/anaconda3/bin:/Users/abhi3700/opt/anaconda3/condabin:/Users/abhi3700/.nvm/versions/node/v16.14.2/bin:/opt/homebrew/bin:/usr/local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/abhi3700/.local/share/solana/install/active_release/bin:/Users/abhi3700/Library/Python/3.8/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/abhi3700/.cargo/bin:/Users/abhi3700/.rvm/bin
[15:02:48.254] Checking ssh with "ssh -V"
[15:02:48.257] > OpenSSH_8.6p1, LibreSSL 3.3.6

[15:02:48.258] Using SSH config file "/Users/abhi3700/.lima/_config/user"
[15:02:48.259] askpass server listening on /var/folders/cw/dc7mkcsd6yx76lscv6w1hpcw0000gn/T/vscode-ssh-askpass-9439d0f7af833d2dbe8d0be9d2a24c4150573735.sock
[15:02:48.259] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/cw/dc7mkcsd6yx76lscv6w1hpcw0000gn/T/vscode-ssh-askpass-3c8ddc563dfe72859a20da15936d466ea17ceff4.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","53753","-o","ConnectTimeout=60","-F","/Users/abhi3700/.lima/_config/user","lima-docker"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/abhi3700/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-5360525f-30d9c6cd9483b2cc586687151bcbcd635f373630-0.82.1/data.json"}
[15:02:48.259] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.waaWLP6bys/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/abhi3700/.vscode/extensions/ms-vscode-remote.remote-ssh-0.82.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/abhi3700/.vscode/extensions/ms-vscode-remote.remote-ssh-0.82.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/cw/dc7mkcsd6yx76lscv6w1hpcw0000gn/T/vscode-ssh-askpass-9439d0f7af833d2dbe8d0be9d2a24c4150573735.sock"}
[15:02:48.259] Spawned 14306
[15:02:48.321] > local-server-1> Spawned ssh, pid=14325
[15:02:48.334] stderr> OpenSSH_8.6p1, LibreSSL 3.3.6
[15:02:48.335] stderr> /Users/abhi3700/.lima/_config/user: line 1: Bad configuration option: -----begin
[15:02:48.335] stderr> /Users/abhi3700/.lima/_config/user: line 2: Bad configuration option: b3blbnnzac1rzxktdjeaaaaabg5vbmuaaaaebm9uzqaaaaaaaaabaaaamwaaaatzc2gtzw
[15:02:48.336] stderr> /Users/abhi3700/.lima/_config/user: line 3: Bad configuration option: qyntuxoqaaacaus4nynav/ze5nb8l3tcg3c//cblje7se8ygq1i8xnxqaaajgh3jzeb948
[15:02:48.336] stderr> /Users/abhi3700/.lima/_config/user: line 4: Bad configuration option: xaaaaatzc2gtzwqyntuxoqaaacaus4nynav/ze5nb8l3tcg3c//cblje7se8ygq1i8xnxq
[15:02:48.336] stderr> /Users/abhi3700/.lima/_config/user: line 5: Bad configuration option: aaaeccg5tnpt/jgwodaye+ckcsnjdqft34y2zrzkhvj2retxrlg1icbx/n7k0hwve1wbcl
[15:02:48.336] stderr> /Users/abhi3700/.lima/_config/user: line 6: Bad configuration option: /8igul7tj7xgzdujxeffaaaafwfiagkznzawqde5mi4xnjgums4xmw
[15:02:48.336] stderr> /Users/abhi3700/.lima/_config/user: line 7: Bad configuration option: -----end
[15:02:48.336] stderr> /Users/abhi3700/.lima/_config/user: terminating, 7 bad configuration options
[15:02:48.337] > local-server-1> ssh child died, shutting down
[15:02:48.337] Local server exit: 0
[15:02:48.338] Received install output: local-server-1> Spawned ssh, pid=14325
OpenSSH_8.6p1, LibreSSL 3.3.6
/Users/abhi3700/.lima/_config/user: line 1: Bad configuration option: -----begin
/Users/abhi3700/.lima/_config/user: line 2: Bad configuration option: b3blbnnzac1rzxktdjeaaaaabg5vbmuaaaaebm9uzqaaaaaaaaabaaaamwaaaatzc2gtzw
/Users/abhi3700/.lima/_config/user: line 3: Bad configuration option: qyntuxoqaaacaus4nynav/ze5nb8l3tcg3c//cblje7se8ygq1i8xnxqaaajgh3jzeb948
/Users/abhi3700/.lima/_config/user: line 4: Bad configuration option: xaaaaatzc2gtzwqyntuxoqaaacaus4nynav/ze5nb8l3tcg3c//cblje7se8ygq1i8xnxq
/Users/abhi3700/.lima/_config/user: line 5: Bad configuration option: aaaeccg5tnpt/jgwodaye+ckcsnjdqft34y2zrzkhvj2retxrlg1icbx/n7k0hwve1wbcl
/Users/abhi3700/.lima/_config/user: line 6: Bad configuration option: /8igul7tj7xgzdujxeffaaaafwfiagkznzawqde5mi4xnjgums4xmw
/Users/abhi3700/.lima/_config/user: line 7: Bad configuration option: -----end
/Users/abhi3700/.lima/_config/user: terminating, 7 bad configuration options
local-server-1> ssh child died, shutting down

[15:02:48.338] Failed to parse remote port from server output
[15:02:48.339] Resolver error: Error: 
	at Function.Create (/Users/abhi3700/.vscode/extensions/ms-vscode-remote.remote-ssh-0.82.1/out/extension.js:1:585219)
	at Object.t.handleInstallOutput (/Users/abhi3700/.vscode/extensions/ms-vscode-remote.remote-ssh-0.82.1/out/extension.js:1:583871)
	at Object.e [as tryInstallWithLocalServer] (/Users/abhi3700/.vscode/extensions/ms-vscode-remote.remote-ssh-0.82.1/out/extension.js:1:624370)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/abhi3700/.vscode/extensions/ms-vscode-remote.remote-ssh-0.82.1/out/extension.js:1:643503
	at async Object.t.withShowDetailsEvent (/Users/abhi3700/.vscode/extensions/ms-vscode-remote.remote-ssh-0.82.1/out/extension.js:1:647221)
	at async /Users/abhi3700/.vscode/extensions/ms-vscode-remote.remote-ssh-0.82.1/out/extension.js:1:622842
	at async T (/Users/abhi3700/.vscode/extensions/ms-vscode-remote.remote-ssh-0.82.1/out/extension.js:1:619348)
	at async Object.t.resolveWithLocalServer (/Users/abhi3700/.vscode/extensions/ms-vscode-remote.remote-ssh-0.82.1/out/extension.js:1:622457)
	at async Object.t.resolve (/Users/abhi3700/.vscode/extensions/ms-vscode-remote.remote-ssh-0.82.1/out/extension.js:1:644831)
	at async /Users/abhi3700/.vscode/extensions/ms-vscode-remote.remote-ssh-0.82.1/out/extension.js:1:727005
[15:02:48.341] ------
```

**Comment by tanhakabir** [comment]
These errors look suspicious:
```
/Users/abhi3700/.lima/_config/user: line 1: Bad configuration option: -----begin
/Users/abhi3700/.lima/_config/user: line 2: Bad configuration option: b3blbnnzac1rzxktdjeaaaaabg5vbmuaaaaebm9uzqaaaaaaaaabaaaamwaaaatzc2gtzw
/Users/abhi3700/.lima/_config/user: line 3: Bad configuration option: qyntuxoqaaacaus4nynav/ze5nb8l3tcg3c//cblje7se8ygq1i8xnxqaaajgh3jzeb948
/Users/abhi3700/.lima/_config/user: line 4: Bad configuration option: xaaaaatzc2gtzwqyntuxoqaaacaus4nynav/ze5nb8l3tcg3c//cblje7se8ygq1i8xnxq
/Users/abhi3700/.lima/_config/user: line 5: Bad configuration option: aaaeccg5tnpt/jgwodaye+ckcsnjdqft34y2zrzkhvj2retxrlg1icbx/n7k0hwve1wbcl
/Users/abhi3700/.lima/_config/user: line 6: Bad configuration option: /8igul7tj7xgzdujxeffaaaafwfiagkznzawqde5mi4xnjgums4xmw
/Users/abhi3700/.lima/_config/user: line 7: Bad configuration option: -----end
/Users/abhi3700/.lima/_config/user: terminating, 7 bad configuration options
```

Are you able to successfully connect through terminal?

Could you try https://stackoverflow.com/questions/69003741/bad-configuration-option-identityfile
