### ISSUE TITLE
Many platforms don't seem to be supported

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-remote-release#6880]
Testing #6866

Running `docker buildx inspect`:
```
Name:   mybuilder
Driver: docker-container

Nodes:
Name:      mybuilder0
Endpoint:  npipe:////./pipe/docker_engine
Status:    running
Platforms: linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/amd64/v4, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
```

Trying a platform like `linux/riscv64`:
```
[19 ms] @devcontainers/cli 0.7.0.
[662 ms] Start: Run: docker buildx build --platform linux/riscv64 --push --build-arg BUILDKIT_INLINE_CACHE=1 -f c:\Users\raymondzhao\work\endgame\docker-workspace\.devcontainer\Dockerfile -t raymondzhaomsft/test-multi-platform-2 --build-arg VARIANT=16 c:\Users\raymondzhao\work\endgame\docker-workspace\.devcontainer

[+] Building 0.3s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 851B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => ERROR [internal] load metadata for mcr.microsoft.com/vscode/devcontai  0.3s
------
 > [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/javascrip
t-node:0-16:
------
Dockerfile:3
--------------------
   1 |     # [Choice] Node.js version (use -bullseye variants on local arm64/App
le Silicon): 18, 16, 14, 18-bullseye, 16-bullseye, 14-bullseye, 18-buster, 16-bu
ster, 14-buster
   2 |     ARG VARIANT=16-bullseye
   3 | >>> FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIA
NT}
   4 |
   5 |     # [Optional] Uncomment this section to install additional OS packages
.
--------------------
error: failed to solve: mcr.microsoft.com/vscode/devcontainers/javascript-node:0
-16: no match for platform in manifest sha256:80e1e4adeca7dff74c8b4d36a923e2ef0b
1b0867b6c060b805036ebf847b64ea: not found
Error: Command failed: docker buildx build --platform linux/riscv64 --push --build-arg BUILDKIT_INLINE_CACHE=1 -f c:\Users\raymondzhao\work\endgame\docker-workspace\.devcontainer\Dockerfile -t raymondzhaomsft/test-multi-platform-2 --build-arg VARIANT=16 c:\Users\raymondzhao\work\endgame\docker-workspace\.devcontainer
    at buildAndExtendImage (C:\Users\raymondzhao\AppData\Roaming\nvm\v16.9.1\node_modules\@devcontainers\cli\dist\spec-node\singleContainer.js:215:15)
    at async buildNamedImageAndExtend (C:\Users\raymondzhao\AppData\Roaming\nvm\v16.9.1\node_modules\@devcontainers\cli\dist\spec-node\singleContainer.js:100:16)
    at async doBuild (C:\Users\raymondzhao\AppData\Roaming\nvm\v16.9.1\node_modules\@devcontainers\cli\dist\spec-node\devContainersSpecCLI.js:291:42)
    at async build (C:\Users\raymondzhao\AppData\Roaming\nvm\v16.9.1\node_modules\@devcontainers\cli\dist\spec-node\devContainersSpecCLI.js:230:20)
{"outcome":"error","message":"Command failed: docker buildx build --platform linux/riscv64 --push --build-arg BUILDKIT_INLINE_CACHE=1 -f c:\\Users\\raymondzhao\\work\\endgame\\docker-workspace\\.devcontainer\\Dockerfile -t raymondzhaomsft/test-multi-platform-2 --build-arg VARIANT=16 c:\\Users\\raymondzhao\\work\\endgame\\docker-workspace\\.devcontainer","description":"An error occurred building the image."}
```

The Dockerfile:
```
ARG VARIANT=16-bullseye
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIANT}
```

devcontainers.json
```jsonc
// For format details, see https://aka.ms/devcontainer.json. For config options, see the README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.241.1/containers/javascript-node
{
	"name": "Node.js",
	"build": {
		"dockerfile": "Dockerfile",
		// Update 'VARIANT' to pick a Node version: 18, 16, 14.
		// Append -bullseye or -buster to pin to an OS version.
		// Use -bullseye variants on local arm64/Apple Silicon.
		"args": { "VARIANT": "16" }
	},

	// Configure tool-specific properties.
	"customizations": {
		// Configure properties specific to VS Code.
		"vscode": {
			// Add the IDs of extensions you want installed when the container is created.
			"extensions": [
				"dbaeumer.vscode-eslint"
			]
		}
	},

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "yarn install",

	// Comment out to connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
	"remoteUser": "node"
}
```

**Comment by chrmarti** [comment]
`docker manifest inspect mcr.microsoft.com/vscode/devcontainers/javascript-node:0-16` shows that the base image you are using is only available for amd64 and arm64.

E.g., `docker manifest inspect ubuntu:latest` shows: amd64, arm, arm64, ppc64le, riscv64 and s390x.

This was missing from the test instructions. Closing as expected, thanks.
