### ISSUE TITLE
VSCode doesn't allow to attach running container, throws `uv_os_get_passwd returned ENOENT ` (On newest extension only)

### ISSUE THREAD

**Issue by thebestnom** [microsoft/vscode-remote-release#6928]
- VSCode Version: 1.69.0 (Extension version 0.241.3 and up)
- Local OS Version: Ubuntu 20.04
- Remote OS Version: dokcer centos (docker 20.10.12)
- Remote Extension/Connection Type: Containers
- Logs: 
```
[2022-07-11 13:46:12.600] [exthost] [error] SystemError: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
	at new SystemError (node:internal/errors:233:5)
	at new NodeError (node:internal/errors:336:7)
	at Object.userInfo (node:os:347:11)
	at Eo (/.../.vscode/extensions/ms-vscode-remote.remote-containers-0.242.0/dist/extension/extension.js:394:5490)
	at yt (/.../.vscode/extensions/ms-vscode-remote.remote-containers-0.242.0/dist/extension/extension.js:396:10846)
	at d (/.../.vscode/extensions/ms-vscode-remote.remote-containers-0.242.0/dist/extension/extension.js:463:6044)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async o._executeContributedCommand (/snap/code/100/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:62863) remote-containers.attachToRunningContainerFromViewlet {"value":"ms-vscode-remote.remote-containers","_lower":"ms-vscode-remote.remote-containers"}
```

Steps to Reproduce:

1. try to attach (before vscode is attached to container)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

(I have LDAP user but trying nodejs directly does allow me to use os.userInfo but calling it in vscode developer options throws the same error)

Reverting extension to 0.238.3 fixed the problem

**Comment by thebestnom** [comment]
Duplicate of https://github.com/microsoft/vscode-remote-release/issues/6913

**Comment by thebestnom** [comment]
Is actually duplicate
