### ISSUE TITLE
Username in ssh config not respected

### ISSUE THREAD

**Issue by stefan-muc** [microsoft/vscode-remote-release#6939]
* Version of VS Code: Version: 1.69.1 (system setup), Commit: b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, Date: 2022-07-12T08:21:24.514Z
* What type of remote connection you were using: SSH, Auth via `SSH_AUTH_SOCK` environment variable
* Your operating system: Windows 10 Version 21H2 (OS Build 19044.1706), Domain joined
* The remote operating system you are connecting to: Debian GNU/Linux 11.3 (bullseye); publickey auth only
* List of extensions that you have installed: ms-vscode-remote.remote-containers v0.241.3
* Reproducible steps (1... 2... 3...) that cause the issue
1. Add a new server via `[+ Add new]` and type in `ssh myUsername@server` and complete
2. Click `[Connect to Host in New Window]`
3. In new window select `[Linux]` as platform of the new remote 
* What you expected to see, versus what you actually saw
  * What I actually saw
Extension modifies my `.ssh/config` and adds the new host:
```
Host server
  HostName server
  User myUsername
```

It then tries to connect to the server, but this fails:
```
[hh:mm:06.793] Log Level: 2
[hh:mm:06.795] remote-ssh@0.84.0
[hh:mm:06.795] win32 x64
[hh:mm:06.797] SSH Resolver called for "ssh-remote+server", attempt 1
[hh:mm:06.798] "remote.SSH.useLocalServer": false
[hh:mm:06.798] "remote.SSH.showLoginTerminal": false
[hh:mm:06.799] "remote.SSH.remotePlatform": {"server":"linux"}
[hh:mm:06.799] "remote.SSH.path": undefined
[hh:mm:06.799] "remote.SSH.configFile": undefined
[hh:mm:06.799] "remote.SSH.useFlock": true
[hh:mm:06.800] "remote.SSH.lockfilesInTmp": false
[hh:mm:06.800] "remote.SSH.localServerDownload": auto
[hh:mm:06.800] "remote.SSH.remoteServerListenOnSocket": false
[hh:mm:06.801] "remote.SSH.showLoginTerminal": false
[hh:mm:06.801] "remote.SSH.defaultExtensions": []
[hh:mm:06.801] "remote.SSH.loglevel": 2
[hh:mm:06.801] "remote.SSH.enableDynamicForwarding": true
[hh:mm:06.801] "remote.SSH.enableRemoteCommand": false
[hh:mm:06.802] "remote.SSH.serverPickPortsFromRange": {}
[hh:mm:06.802] "remote.SSH.serverInstallPath": {}
[hh:mm:06.809] SSH Resolver called for host: server
[hh:mm:06.809] Setting up SSH remote "server"
[hh:mm:06.815] Using commit id "b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a" and quality "stable" for server
[hh:mm:06.820] Install and start server if needed
[hh:mm:06.822] Checking ssh with "ssh -V"
[hh:mm:06.829] Got error from ssh: spawn ssh ENOENT
[hh:mm:06.829] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[hh:mm:06.832] Got error from ssh: spawn C:\WINDOWS\System32\OpenSSH\ssh.exe ENOENT
[hh:mm:06.832] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[hh:mm:06.996] > OpenSSH_8.8p1, OpenSSL 1.1.1m  14 Dec 2021

[hh:mm:07.025] Running script with connection command: "C:\Program Files\Git\usr\bin\ssh.exe" -T -D 6781 server bash
[hh:mm:07.028] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[hh:mm:07.958] > WINUSER@server: Permission denied (publickey).
> ]0;C:\WINDOWS\System32\cmd.exe
[hh:mm:07.959] Got some output, clearing connection timeout
[hh:mm:07.974] > The process tried to write to a nonexistent pipe.
[hh:mm:09.267] "install" terminal command done
[hh:mm:09.268] Install terminal quit with output: WINUSER@server: Permission denied (publickey).
[hh:mm:09.268] Received install output: WINUSER@server: Permission denied (publickey).
[hh:mm:09.269] Resolver error: Error: Permission denied (publickey).
	at Function.Create (c:\Users\WINUSER\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:585222)
	at c:\Users\WINUSER\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:583279
	at Object.t.handleInstallOutput (c:\Users\WINUSER\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:583796)
	at Object.t.tryInstall (c:\Users\WINUSER\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:681023)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\WINUSER\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:643908
	at async Object.t.withShowDetailsEvent (c:\Users\WINUSER\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:647224)
	at async Object.t.resolve (c:\Users\WINUSER\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:644958)
	at async c:\Users\WINUSER\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:727082
[hh:mm:09.271] ------
```

Problem here: It doesn't use username `myUsername` I specified, thus authentication fails. It instead tries to use my (uppercased) Windows username `WINUSER`.

I was able to verify this by changing the `myUsername` username: The log didn't change, it always uses my `WINUSER` name.

  * What I expected to see

Successful connection to the remote server

* Images, animations, or a link to a video showing the issue occurring
See log above

* A code snippet that demonstrates the issue or a link to a code repository the developers can easily pull down to recreate the issue locally
See `.ssh/config` above. Make sure hostname is set to a resolvable hostname in your net.

* Errors from the Dev Tools Console (open from the menu: Help > Toggle Developer Tools)
```
log.ts:313   ERR Permission denied (publickey).: ErrorNoTelemetry: Permission denied (publickey).
    at k._resolveAuthority (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3173:7252)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async k._scanAndHandleExtensions (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3173:9239)
    at async k._initialize (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3171:23663)
log.ts:313   ERR ErrorNoTelemetry: Permission denied (publickey).
    at k._resolveAuthority (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3173:7252)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async k._scanAndHandleExtensions (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3173:9239)
    at async k._initialize (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3171:23663)
```

* Workaround
Instead of using a syntactically correct configuration, modify `.ssh/config` to include the username in the hostname:
```
Host myUsername@server
  HostName myUsername@server
```

Now connecting works properly:
```
[hh:mm:06.423] Log Level: 2
[hh:mm:06.425] remote-ssh@0.84.0
[hh:mm:06.425] win32 x64
[hh:mm:06.427] SSH Resolver called for "ssh-remote+myUsername@server", attempt 1
[hh:mm:06.428] "remote.SSH.useLocalServer": false
[hh:mm:06.428] "remote.SSH.showLoginTerminal": false
[hh:mm:06.429] "remote.SSH.remotePlatform": {"server":"linux"}
[hh:mm:06.429] "remote.SSH.path": undefined
[hh:mm:06.429] "remote.SSH.configFile": undefined
[hh:mm:06.429] "remote.SSH.useFlock": true
[hh:mm:06.429] "remote.SSH.lockfilesInTmp": false
[hh:mm:06.430] "remote.SSH.localServerDownload": auto
[hh:mm:06.430] "remote.SSH.remoteServerListenOnSocket": false
[hh:mm:06.430] "remote.SSH.showLoginTerminal": false
[hh:mm:06.430] "remote.SSH.defaultExtensions": []
[hh:mm:06.430] "remote.SSH.loglevel": 2
[hh:mm:06.431] "remote.SSH.enableDynamicForwarding": true
[hh:mm:06.431] "remote.SSH.enableRemoteCommand": false
[hh:mm:06.431] "remote.SSH.serverPickPortsFromRange": {}
[hh:mm:06.431] "remote.SSH.serverInstallPath": {}
[hh:mm:06.440] SSH Resolver called for host: myUsername@server
[hh:mm:06.440] Setting up SSH remote "server"
[hh:mm:06.447] Using commit id "b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a" and quality "stable" for server
[hh:mm:06.451] Install and start server if needed
[hh:mm:06.455] Checking ssh with "ssh -V"
[hh:mm:06.462] Got error from ssh: spawn ssh ENOENT
[hh:mm:06.462] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[hh:mm:06.465] Got error from ssh: spawn C:\WINDOWS\System32\OpenSSH\ssh.exe ENOENT
[hh:mm:06.465] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[hh:mm:06.650] > OpenSSH_8.8p1, OpenSSL 1.1.1m  14 Dec 2021

[hh:mm:06.659] Running script with connection command: "C:\Program Files\Git\usr\bin\ssh.exe" -T -D 8439 "myUsername@server" bash
[hh:mm:06.662] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[hh:mm:07.597] > 64d133355a12: running
> ]0;C:\WINDOWS\System32\cmd.exe
[hh:mm:07.597] Got some output, clearing connection timeout
[hh:mm:07.623] > Acquiring lock on /home/myUsername/.vscode-server/bin/b06ae3b2d2dbfe28bca3134cc6be65935
> cdfea6a/vscode-remote-lock.myUsername.b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
[hh:mm:07.640] > Found existing installation at /home/myUsername/.vscode-server/bin/b06ae3b2d2dbfe28bca3
> 134cc6be65935cdfea6a...
> Checking /home/myUsername/.vscode-server/.b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a.log 
> and /home/myUsername/.vscode-server/.b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a.pid for a
>  running server
> Looking for server with pid: 3997574
[hh:mm:07.654] > Found running server...
> 
> *
> * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status on port 45337 with wget
> 64d133355a12: start  
> SSH_AUTH_SOCK====    
> DISPLAY====
> webUiAccessToken==== 
> listeningOn==45337== 
> osReleaseId==debian==
> arch==x86_64==       
> tmpDir==/tmp==       
> platform==linux==    
> unpackResult====     
> didLocalDownload==0==
> downloadTime====     
> installTime====      
> extInstallTime====
[hh:mm:07.657] > 
> serverStartTime====
> connectionToken==[... redacted ...]
> 64d133355a12: end
[hh:mm:07.657] Received install output:   
SSH_AUTH_SOCK====    
DISPLAY====
webUiAccessToken==== 
[... redacted ...]

[hh:mm:07.658] Remote server is listening on 45337
[hh:mm:07.658] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":45337},"osReleaseId":"debian","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/tmp","platform":"linux","connectionToken":"[... redacted ...]"},"installUnpackCode":""}
[hh:mm:07.662] Starting forwarding server. localPort 8446 -> socksPort 8439 -> remotePort 45337
[hh:mm:07.663] Forwarding server listening on 8446
[hh:mm:07.663] Waiting for ssh tunnel to be ready
[hh:mm:07.664] Tunneled 45337 to local port 8446
[hh:mm:07.664] Resolved "ssh-remote+myUsername@server" to "127.0.0.1:8446"
[hh:mm:07.666] [Forwarding server 8446] Got connection 0
[hh:mm:07.670] > 
[hh:mm:07.674] ------




[hh:mm:07.933] [Forwarding server 8446] Got connection 1
[hh:mm:07.952] [Forwarding server 8446] Got connection 2
```

**Comment by tanhakabir** [comment]
When you use the ssh_config that looks like this:
```
Host server
  HostName server
  User myUsername
```

And you try to connect to that remote machine in powershell, what happens?

**Comment by stefan-muc** [comment]
> And you try to connect to that remote machine in powershell, what happens?

I'm happy to try, but can you please tell me the exact command line I should use?

**Comment by tanhakabir** [comment]
`ssh -T -D 6781 server`

**Comment by stefan-muc** [comment]
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\> ssh -T -D 6781 server
ssh : The term 'ssh' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ssh -T -D 6781 server
+ ~~~
    + CategoryInfo          : ObjectNotFound: (ssh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by tanhakabir** [comment]
Is your SSH saved in `C:\Program Files\Git\usr\bin\ssh.exe`?

Then try `"C:\Program Files\Git\usr\bin\ssh.exe" -T -D 6781 server`

**Comment by stefan-muc** [comment]
Sorry for the delay - had some other stuff to do. Please reopen this issue.

Yes, as you can see from the log in my first post, SSH is used from there.

Running your command line in PowerShell doesn't work:
```
PS C:\> "C:\Program Files\Git\usr\bin\ssh.exe" -T -D 6781 server
At line:1 char:40
+ "C:\Program Files\Git\usr\bin\ssh.exe" -T -D 6781 server
+                                        ~~
Unexpected token '-T' in expression or statement.
At line:1 char:43
+ "C:\Program Files\Git\usr\bin\ssh.exe" -T -D 6781 server
+                                           ~~
Unexpected token '-D' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
```

I guess you wanted me to try this:
```
PS C:\> & 'C:\Program Files\Git\usr\bin\ssh.exe' -T -D 6781 server
WINUSER@server: Permission denied (publickey).
```

But that's also exact the same command and result as already written in the log in my first post.

Only running it with the correct command line including the username will make a connection:
```
PS C:\> & 'C:\Program Files\Git\usr\bin\ssh.exe' -T -D 6781 myUsername@server
whoami
myUsername
exit
```

**Comment by tanhakabir** [comment]
The extension strictly respects what's in your ssh config file. Could you fix your ssh config file such that `& 'C:\Program Files\Git\usr\bin\ssh.exe' -T -D 6781 server` works in powershell for you?

**Comment by stefan-muc** [comment]
That's the problem - changing the username in config file doesn't change anything in connection.

I did some more tests on another (some private) computer having the same OpenSSH version (through same Git version) installed, and changing the username in `.ssh/config` indeed changes the username used for connecting.

So I will have to do some more tests on the computer I reported the problem on, and will come back to you. Hopefully on Monday Thanks for your patience!

**Comment by stefan-muc** [comment]
So I finally digged down towards the problem: The computer from initial post stores its user data and thus `.ssh/config` on a separate disk `U:`

I don't know how to configure this in Windows, but it results in environment variable `HOMEDRIVE` being set to `U:` and variable `HOMEPATH` set to `\` (and variable `HOMESHARE` set to a network path).
This results in environment variable `HOME` in `MINGW64` being set to `/u/`. Thus `ssh.exe` reads its config from `/u/.ssh/config`

If I edit `U:\.ssh\config` accordingly, the correct username is used, and connection succeeds.

Thus I request VSCode Extension to respect `HOMEDRIVE` and `HOMEPATH` environment variables for:
* reading configuration (displaying SSH TARGETS)
* saving configuration (adding a new target, modifying existing targets)

Workaround until this bug is fixed:
Set `Remote.SSH: Config File` setting to the correct path

**Comment by tanhakabir** [comment]
Ah I see. Sorry about that and thanks for doing this investigation! I'll mark this as a bug for now but I'm glad you have a workaround

**Comment by roblourens** [comment]
This flow could be improved, but for now when `.ssh/config` is in a non-standard location, the setting will have to be set. We can revisit this for git ssh when looking at wsl ssh as well.
