### ISSUE TITLE
Mac VSCode to Windows SSH not working

### ISSUE THREAD

**Issue by derekgreer** [microsoft/vscode-remote-release#6954]
I can ssh to a Windows box from my OSX terminal, but attempting to do so through the VSCode extension fails.  I can't make out from the below output what's wrong.

```
[11:18:50.181] Log Level: 2
[11:18:50.182] remote-ssh@0.84.0
[11:18:50.182] darwin x64
[11:18:50.186] SSH Resolver called for "ssh-remote+mx", attempt 1
[11:18:50.187] "remote.SSH.useLocalServer": true
[11:18:50.187] "remote.SSH.path": undefined
[11:18:50.187] "remote.SSH.configFile": undefined
[11:18:50.190] "remote.SSH.useFlock": true
[11:18:50.190] "remote.SSH.lockfilesInTmp": false
[11:18:50.190] "remote.SSH.localServerDownload": auto
[11:18:50.191] "remote.SSH.remoteServerListenOnSocket": false
[11:18:50.191] "remote.SSH.showLoginTerminal": false
[11:18:50.191] "remote.SSH.defaultExtensions": []
[11:18:50.191] "remote.SSH.loglevel": 2
[11:18:50.192] "remote.SSH.enableDynamicForwarding": true
[11:18:50.192] "remote.SSH.enableRemoteCommand": false
[11:18:50.192] "remote.SSH.serverPickPortsFromRange": {}
[11:18:50.192] "remote.SSH.serverInstallPath": {}
[11:18:50.204] SSH Resolver called for host: mx
[11:18:50.204] Setting up SSH remote "mx"
[11:18:50.206] Acquiring local install lock: /var/folders/mg/zxjb186s43jf90ck7mnfcs5h0000gn/T/vscode-remote-ssh-4b2dfd00-install.lock
[11:18:50.208] Looking for existing server data file at /Users/derekgreer/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-4b2dfd00-30d9c6cd9483b2cc586687151bcbcd635f373630-0.84.0/data.json
[11:18:50.208] Using commit id "30d9c6cd9483b2cc586687151bcbcd635f373630" and quality "stable" for server
[11:18:50.211] Install and start server if needed
[11:18:50.213] PATH: /Users/derekgreer/.nvm/versions/node/v17.3.0/bin:./:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:~/bin:~/development/flutter/bin:/Users/derekgreer/development/flutter/bin:/Users/derekgreer/bin
[11:18:50.213] Checking ssh with "ssh -V"
[11:18:50.217] > OpenSSH_8.6p1, LibreSSL 2.8.3

[11:18:50.219] askpass server listening on /var/folders/mg/zxjb186s43jf90ck7mnfcs5h0000gn/T/vscode-ssh-askpass-bb66bd5fe274cd61731fb05075189ca1eeb278d9.sock
[11:18:50.220] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/mg/zxjb186s43jf90ck7mnfcs5h0000gn/T/vscode-ssh-askpass-861226b20ebeeab9e51f1a2790aa1730c2c5d2cd.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","58176","-o","ConnectTimeout=15","mx"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/derekgreer/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-4b2dfd00-30d9c6cd9483b2cc586687151bcbcd635f373630-0.84.0/data.json"}
[11:18:50.220] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.pSQpVvJuIm/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/derekgreer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/derekgreer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/mg/zxjb186s43jf90ck7mnfcs5h0000gn/T/vscode-ssh-askpass-bb66bd5fe274cd61731fb05075189ca1eeb278d9.sock"}
[11:18:50.221] Spawned 47637
[11:18:50.348] > local-server-1> Spawned ssh, pid=47642
[11:18:50.350] stderr> OpenSSH_8.6p1, LibreSSL 2.8.3
[11:19:07.222] Terminating local server
[11:19:07.223] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/derekgreer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585348)
	at Timeout._onTimeout (/Users/derekgreer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:630527)
	at listOnTimeout (node:internal/timers:557:17)
	at processTimers (node:internal/timers:500:7)
[11:19:07.228] ------




[11:19:07.229] Local server exit: 15
```

SSH works fine from the command line:

```
Last login: Fri Jul  1 09:39:53 on ttys001
√ ~  % !ssh
ssh dgreer@dgreer-pc
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.10.102.1-microsoft-standard-WSL2 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Fri Jul 15 11:23:07 CDT 2022

  System load:  0.0                Processes:             19
  Usage of /:   1.3% of 250.98GB   Users logged in:       0
  Memory usage: 3%                 IPv4 address for eth0: 172.27.119.161
  Swap usage:   0%


0 updates can be installed immediately.
0 of these updates are security updates.


The list of available updates is more than a week old.
To check for new updates run: sudo apt update

Last login: Fri Jul 15 11:16:52 2022 from 172.27.112.1
dgreer@dgreer-pc:/projects$
```

**Comment by Luo-Kaiyi** [comment]
**I changed default shell of ubuntu server from fish to bash, then my vs-code worked.**

Outputs of my problem is :
```
[11:00:44.899] SSH Resolver called for host: Server17
[11:00:44.899] Setting up SSH remote "Server17"
[11:00:44.900] Acquiring local install lock: /tmp/vscode-remote-ssh-8002cc4a-install.lock
[11:00:44.901] Looking for existing server data file at /home/PJLAB/luokaiyi/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-8002cc4a-e4503b30fc78200f846c62cf8091b76ff5547662-0.84.0/data.json
[11:00:44.901] Using commit id "e4503b30fc78200f846c62cf8091b76ff5547662" and quality "stable" for server
[11:00:44.902] Install and start server if needed
[11:00:44.904] askpass server listening on /run/user/409473566/vscode-ssh-askpass-8ea945d2598a08a6ca51d1301dfb3e940f4d552d.sock
[11:00:44.904] Spawning local server with {"serverId":5,"ipcHandlePath":"/run/user/409473566/vscode-ssh-askpass-2877587f1e663a7ace6fc96c981f71a4494d46cf.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","39771","-o","ConnectTimeout=15","Server17"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/PJLAB/luokaiyi/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-8002cc4a-e4503b30fc78200f846c62cf8091b76ff5547662-0.84.0/data.json"}
[11:00:44.904] Local server env: {"SSH_AUTH_SOCK":"/run/user/409473566/keyring/ssh","SHELL":"/bin/bash","DISPLAY":":1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/PJLAB/luokaiyi/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/PJLAB/luokaiyi/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/409473566/vscode-ssh-askpass-8ea945d2598a08a6ca51d1301dfb3e940f4d552d.sock"}
[11:00:44.906] Spawned 12703
[11:00:44.906] Spawned 12703
[11:00:44.964] > local-server-5> Spawned ssh, pid=12711
[11:00:44.965] stderr> OpenSSH_8.9p1 Ubuntu-3, OpenSSL 3.0.2 15 Mar 2022
[11:00:44.998] stderr> debug1: Server host key: ssh-ed25519 SHA256:E999jSLLzpMWiW50EqXPIm45SStw51wjrnS308CgNek
[11:00:45.048] stderr> Authenticated to 192.168.1.17 ([192.168.1.17]:11000) using "publickey".
[11:00:45.120] > Welcome to Ubuntu 20.04.5 LTS (GNU/Linux 5.15.0-46-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
[11:01:01.907] Terminating local server
[11:01:01.909] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/home/PJLAB/luokaiyi/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585348)
	at Timeout._onTimeout (/home/PJLAB/luokaiyi/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:630527)
	at listOnTimeout (node:internal/timers:557:17)
	at processTimers (node:internal/timers:500:7)
[11:01:01.912] ------
```

**Comment by eleanorjboyd** [comment]
Hello! My name is Eleanor and I am the new maintainer for the Remote-SSH extension. Are you still experiencing this issue? Thanks
