### ISSUE TITLE
Remote-SSH: cannot install extensions, ExtensionHostConnection crash with Unexpected SIGPIPE ?

### ISSUE THREAD

**Issue by aallrd** [microsoft/vscode-remote-release#6964]
Hello,

I am unable to install any extensions on the _vscode-server_ running on my Linux remote SSH host (RHEL 7).
After browsing the marketplace and clicking on "_Install_" for any extension, it seems to load forever without doing anything.

**VSCode:**
Version: 1.69.1 (user setup)
Commit: b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
Date: 2022-07-12T08:21:24.514Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

**Remote-SSH:**
```
[15:11:35.749] Log Level: 2
[15:11:35.751] remote-ssh@0.84.0
[15:11:35.751] win32 x64
[15:11:35.771] SSH Resolver called for "ssh-remote+sleepy-brass-echidna", attempt 1
[15:11:35.772] "remote.SSH.useLocalServer": false
[15:11:35.772] "remote.SSH.showLoginTerminal": false
[15:11:35.772] "remote.SSH.remotePlatform": {"muggy-crimson-moorhen":"linux","sleepy-brass-echidna":"linux"}
[15:11:35.772] "remote.SSH.path": C:\Windows\System32\OpenSSH\ssh.exe
[15:11:35.773] "remote.SSH.configFile": undefined
[15:11:35.773] "remote.SSH.useFlock": true
[15:11:35.773] "remote.SSH.lockfilesInTmp": false
[15:11:35.773] "remote.SSH.localServerDownload": always
[15:11:35.773] "remote.SSH.remoteServerListenOnSocket": false
[15:11:35.774] "remote.SSH.showLoginTerminal": false
[15:11:35.774] "remote.SSH.defaultExtensions": ["ms-vscode.cpptools","mjcrouch.perforce","llvm-vs-code-extensions.vscode-clangd"]
[15:11:35.774] "remote.SSH.loglevel": 2
[15:11:35.774] "remote.SSH.enableDynamicForwarding": true
[15:11:35.774] "remote.SSH.enableRemoteCommand": false
[15:11:35.775] "remote.SSH.serverPickPortsFromRange": {}
[15:11:35.775] "remote.SSH.serverInstallPath": {}
[15:11:35.801] SSH Resolver called for host: sleepy-brass-echidna
[15:11:35.801] Setting up SSH remote "sleepy-brass-echidna"
[15:11:35.828] Using commit id "b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a" and quality "stable" for server
[15:11:35.833] Install and start server if needed
[15:11:35.837] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[15:11:35.906] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[15:11:35.910] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 62375 "sleepy-brass-echidna" bash
[15:11:35.913] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:11:36.166] > ]0;C:\WINDOWS\System32\cmd.exe
[15:11:36.166] Got some output, clearing connection timeout
[15:11:36.352] > 2d132a13b50b: running
[15:11:36.377] > Acquiring lock on /root/.vscode-server/bin/b06ae3b2d2dbfe28bca3134cc6be65935cdfe
> a6a/vscode-remote-lock.root.b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
[15:11:36.394] > Found existing installation at /root/.vscode-server/bin/b06ae3b2d2dbfe28bca3134c
> c6be65935cdfea6a...
> Checking /root/.vscode-server/.b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a.log and 
> /root/.vscode-server/.b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a.pid for a running
>  server
> Looking for server with pid: 352034
> Found running server...
> Installing extensions...
[15:11:36.609] > Installing extensions...
[15:11:36.728] > Extension 'llvm-vs-code-extensions.vscode-clangd' v0.1.21 is already installed. 
> Use '--force' option to update to latest version or provide '@<version>' to inst
> all a specific version, for example: 'llvm-vs-code-extensions.vscode-clangd@1.2.
> 3'.
[15:11:37.293] > read ECONNRESET
[15:11:37.323] >  
> *
[15:11:37.329] > * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
> Checking server status on port 38493 with wget
> 2d132a13b50b: start
> SSH_AUTH_SOCK====
> DISPLAY====
> webUiAccessToken====
> listeningOn==38493==
> osReleaseId==rhel==
> arch==x86_64==
> tmpDir==/tmp==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime==924==
> serverStartTime====
> connectionToken==a1111111-a11a-1a11-1111-1a1111aa1a1a==
> 2d132a13b50b: end
[15:11:37.329] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==38493==
osReleaseId==rhel==
arch==x86_64==
tmpDir==/tmp==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime==924==
serverStartTime====
connectionToken==a1111111-a11a-1a11-1111-1a1111aa1a1a==

[15:11:37.329] Remote server is listening on 38493
[15:11:37.329] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":38493},"osReleaseId":"rhel","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/tmp","platform":"linux","connectionToken":"a1111111-a11a-1a11-1111-1a1111aa1a1a"},"extInstallTime":924,"installUnpackCode":""}
[15:11:37.332] Starting forwarding server. localPort 62379 -> socksPort 62375 -> remotePort 38493
[15:11:37.332] Forwarding server listening on 62379
[15:11:37.332] Waiting for ssh tunnel to be ready
[15:11:37.333] Tunneled 38493 to local port 62379
[15:11:37.333] Resolved "ssh-remote+sleepy-brass-echidna" to "127.0.0.1:62379"
[15:11:37.334] [Forwarding server 62379] Got connection 0
[15:11:37.341] ------
[15:11:37.423] [Forwarding server 62379] Got connection 1
[15:11:37.440] [Forwarding server 62379] Got connection 2
[15:11:38.645] [Forwarding server 62379] Got connection 3
```

**Tab "Log (remote server)":**
```
[2022-07-18 14:36:34.543] [remoteagent] [info] Extension host agent started.
[2022-07-18 14:36:34.766] [remoteagent] [info] [127.0.0.1][aa3f04ec][ManagementConnection] New connection established.
[2022-07-18 14:36:34.768] [remoteagent] [info] [127.0.0.1][1add3ea9][ExtensionHostConnection] New connection established.
[2022-07-18 14:36:35.088] [remoteagent] [info] [127.0.0.1][1add3ea9][ExtensionHostConnection] <351151> Launched Extension Host Process.
[2022-07-18 14:36:35.159] [remoteagent] [error] Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)
[2022-07-18 14:36:40.395] [remoteagent] [info] [127.0.0.1][1add3ea9][ExtensionHostConnection] <351151> Extension Host Process exited with code: 0, signal: null.
[2022-07-18 14:36:40.396] [remoteagent] [info] Last EH closed, waiting before shutting down
[2022-07-18 14:36:43.656] [remoteagent] [info] Got delay-shutdown request while in shutdown timeout, delaying
[2022-07-18 14:36:43.656] [remoteagent] [info] Cancelling previous shutdown timeout
[2022-07-18 14:36:43.760] [remoteagent] [info] [127.0.0.1][92fbedeb][ManagementConnection] New connection established.
[2022-07-18 14:36:43.760] [remoteagent] [info] [127.0.0.1][137f363f][ExtensionHostConnection] New connection established.
[2022-07-18 14:36:43.766] [remoteagent] [info] [127.0.0.1][137f363f][ExtensionHostConnection] <351410> Launched Extension Host Process.
[2022-07-18 14:36:43.866] [remoteagent] [info] [127.0.0.1][aa3f04ec][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[2022-07-18 14:36:43.877] [remoteagent] [error] Error: Unexpected SIGPIPE
    at process.<anonymous> (/root/.vscode-server/bin/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/out/vs/server/node/server.main.js:145:7933)
    at process.emit (node:events:390:28)
[2022-07-18 14:36:45.343] [remoteagent] [info] [127.0.0.1][137f363f][ExtensionHostConnection] <351410> Extension Host Process exited with code: 0, signal: null.
[2022-07-18 14:36:45.343] [remoteagent] [info] Cancelling previous shutdown timeout
[2022-07-18 14:36:45.343] [remoteagent] [info] Last EH closed, waiting before shutting down
[2022-07-18 14:36:48.311] [remoteagent] [info] Got delay-shutdown request while in shutdown timeout, delaying
[2022-07-18 14:36:48.311] [remoteagent] [info] Cancelling previous shutdown timeout
[2022-07-18 14:36:48.370] [remoteagent] [info] [127.0.0.1][aa3f04ec][ManagementConnection] Another client has connected, will shorten the wait for reconnection 5m before disposing...
[2022-07-18 14:36:48.370] [remoteagent] [info] [127.0.0.1][9f333f9f][ManagementConnection] New connection established.
[2022-07-18 14:36:48.394] [remoteagent] [info] [127.0.0.1][0f80fb2f][ExtensionHostConnection] New connection established.
[2022-07-18 14:36:48.401] [remoteagent] [info] [127.0.0.1][0f80fb2f][ExtensionHostConnection] <351648> Launched Extension Host Process.
[2022-07-18 14:36:49.260] [remoteagent] [info] [127.0.0.1][92fbedeb][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[2022-07-18 14:36:49.261] [remoteagent] [error] Error: Unexpected SIGPIPE
    at process.<anonymous> (/root/.vscode-server/bin/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/out/vs/server/node/server.main.js:145:7933)
    at process.emit (node:events:390:28)
[2022-07-18 14:36:49.526] [remoteagent] [info] [127.0.0.1][0f80fb2f][ExtensionHostConnection] <351648> Extension Host Process exited with code: 0, signal: null.
[2022-07-18 14:36:49.526] [remoteagent] [info] Cancelling previous shutdown timeout
[2022-07-18 14:36:49.527] [remoteagent] [info] Last EH closed, waiting before shutting down
[2022-07-18 14:36:52.644] [remoteagent] [info] Got delay-shutdown request while in shutdown timeout, delaying
[2022-07-18 14:36:52.644] [remoteagent] [info] Cancelling previous shutdown timeout
[2022-07-18 14:36:52.702] [remoteagent] [info] [127.0.0.1][92fbedeb][ManagementConnection] Another client has connected, will shorten the wait for reconnection 5m before disposing...
[2022-07-18 14:36:52.702] [remoteagent] [info] [127.0.0.1][93180522][ManagementConnection] New connection established.
[2022-07-18 14:36:52.749] [remoteagent] [info] [127.0.0.1][4d9c9e8d][ExtensionHostConnection] New connection established.
[2022-07-18 14:36:52.760] [remoteagent] [info] [127.0.0.1][4d9c9e8d][ExtensionHostConnection] <351894> Launched Extension Host Process.
[2022-07-18 14:36:53.723] [remoteagent] [info] [127.0.0.1][9f333f9f][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
[2022-07-18 14:36:53.724] [remoteagent] [error] Error: Unexpected SIGPIPE
    at process.<anonymous> (/root/.vscode-server/bin/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/out/vs/server/node/server.main.js:145:7933)
    at process.emit (node:events:390:28)
```

I also found that the same issue was opened 2 years ago it seems: https://github.com/microsoft/vscode-remote-release/issues/3536
I applied the same workaround by running the following command in a terminal opened from VScode: `pkill -f vscode-server`
After running this command, I get a pop up windows "_Cannot reconnect. Please reload the window._" and I am able to install extensions in the reloaded session:
```
[2022-07-18 15:17:08.115] [remoteagent] [info] Installing extension: mjcrouch.perforce
[2022-07-18 15:17:08.115] [remoteagent] [info] Installing the extension without checking dependencies and pack mjcrouch.perforce
[2022-07-18 15:17:08.196] [remoteagent] [info] Removed the extension from uninstalled list: mjcrouch.perforce
[2022-07-18 15:17:08.200] [remoteagent] [info] Deleted from disk mjcrouch.perforce /root/.vscode-server/extensions/mjcrouch.perforce-4.15.2
[2022-07-18 15:17:08.331] [remoteagent] [info] Extracted extension to /root/.vscode-server/extensions/.c20a8487-aea6-43cb-ad75-116cee0eaf2e: mjcrouch.perforce
[2022-07-18 15:17:08.338] [remoteagent] [info] Renamed to /root/.vscode-server/extensions/mjcrouch.perforce-4.15.2
[2022-07-18 15:17:08.340] [remoteagent] [info] Extracting completed. mjcrouch.perforce
[2022-07-18 15:17:08.340] [remoteagent] [info] Extension installed successfully: mjcrouch.perforce
```

Can you please let me know if you need more logs to understand the issue?

**Comment by tanhakabir** [comment]
@sandy081 any ideas for why SIGPIPE errors would occur?

**Comment by alexdima** [comment]
It looks like the running server entered some kind of bad state where it couldn't install extensions anymore. 

@sandy081 Do we always fetch extensions from the marketplace directly from the server or do we often use the client side to upload them? From the log, it looks like the management connection socket gets closed and if extensions are being uploaded then a socket close might break that. Normally, we would reconnect, but the server shows that it sees a new client meaning the user did a window reload. Do we have some logging in this area? It would be good to know if uploading a super large extension could cause something like this, maybe we can log when we are about to begin what the size of the extension is.

I don't think the `SIGPIPE` errors are necessarily the root cause, it looks like they come a few ms after a client disconnection. It is possible that we have some flaw where we try to write to a closed socket, but this is not the root cause of not being able to install extensions, it is a symptom of the management connection socket getting closed.

@aallrd Have you encountered this ever since? Was the machine you were connecting to maybe using a proxy to connect to the internet?

**Comment by alexdima** [comment]
@sandy081 Is it possible that we fall back to client-side uploading if downloading on the server fails?

@aallrd Are you using `remote.downloadExtensionsLocally`?

**Comment by sandy081** [comment]
>  Is it possible that we fall back to client-side uploading if downloading on the server fails?

Yes, if there are specific errors (Download, Internal) on the server, we try to install it from client
