### ISSUE TITLE
Corrupt docker image is built.

### ISSUE THREAD

**Issue by brad-jones** [microsoft/vscode-remote-release#6966]
Running VsCode on Windows 10 with WSL & Docker Desktop.

- **Windows Version:** 21H2 19044.1766
- **VsCode Version:** 1.69.2
- **Docker Desktop Version:** 4.10.1 (82475)

As of today, I can no longer open my devcontainer.

```
[3154 ms] Start: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /home/brad.jones/Projects/Personal/toolbox/.devcontainer/Dockerfile -t vsc-toolbox-0724732ea3bf27a2399f75460fa1c89c /home/brad.jones/Projects/Personal/toolbox/.devcontainer

...

[24405 ms] Start: Run: docker inspect --type image vsc-toolbox-0724732ea3bf27a2399f75460fa1c89c
[24557 ms] Error: Command failed: docker inspect --type image vsc-toolbox-0724732ea3bf27a2399f75460fa1c89c
[24557 ms]     at HR (/home/brad.jones/.vscode-remote-containers/dist/dev-containers-cli-0.241.3/dist/spec-node/devContainersSpecCLI.js:239:2183)
[24558 ms]     at tb (/home/brad.jones/.vscode-remote-containers/dist/dev-containers-cli-0.241.3/dist/spec-node/devContainersSpecCLI.js:239:2121)
[24558 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[24558 ms]     at async QR (/home/brad.jones/.vscode-remote-containers/dist/dev-containers-cli-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:2006)
[24558 ms]     at async cb (/home/brad.jones/.vscode-remote-containers/dist/dev-containers-cli-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:3110)
[24558 ms]     at async i_ (/home/brad.jones/.vscode-remote-containers/dist/dev-containers-cli-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:13194)
[24558 ms]     at async n_ (/home/brad.jones/.vscode-remote-containers/dist/dev-containers-cli-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:12950)
[24561 ms] Exit code 1
[24565 ms] Command failed: /home/brad.jones/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/node /home/brad.jones/.vscode-remote-containers/dist/dev-containers-cli-0.241.3/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /home/brad.jones/Projects/Personal/toolbox --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl$\Fedora33\home\brad.jones\Projects\Personal\toolbox --log-level debug --log-format json --config /home/brad.jones/Projects/Personal/toolbox/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true --terminal-columns 145 --terminal-rows 12
[24565 ms] Exit code 1
```

Running the inspect command manually.

```
$ docker inspect --type image vsc-toolbox-0724732ea3bf27a2399f75460fa1c89c
[]
Error response from daemon: readlink /var/lib/docker/overlay2: invalid argument
```

If I rebuild the image like this.

```
docker build -f /home/brad.jones/Projects/Personal/toolbox/.devcontainer/Dockerfile -t vsc-toolbox-0724732ea3bf27a2399f75460fa1c89c /home/brad.jones/Projects/Personal/toolbox/.devcontainer
```

`docker inspect` returns properly formatted JSON as expected.

**Comment by brad-jones** [comment]
Can confirm this issue happens with an off the shelf devcontainer, instead of my custom one.

```
[107 ms] Remote-Containers 0.241.3 in VS Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a).
[107 ms] Start: Run: wsl -d Fedora33 -e wslpath -u \\wsl$\Fedora33\home\brad.jones\Projects\Personal\toolbox
[328 ms] Start: Resolving Remote
[352 ms] Start: Run: wsl -d Fedora33 -e wslpath -u \\wsl$\Fedora33\home\brad.jones\Projects\Personal\toolbox
[587 ms] Start: Run: wsl -d Fedora33 -e /bin/sh -c cd '/home/brad.jones/Projects/Personal/toolbox' && /bin/sh
[597 ms] Start: Run in host: id -un
[699 ms] brad.jones
[699 ms] 
[700 ms] Start: Run in host: cat /etc/passwd
[704 ms] Start: Run in host: echo ~
[705 ms] /home/brad.jones
[705 ms] 
[706 ms] Start: Run in host: test -x '/home/brad.jones/.vscode-remote-containers/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/node'
[709 ms] 
[709 ms] 
[709 ms] Exit code 1
[710 ms] Start: Run in host: test -x '/home/brad.jones/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/node'
[712 ms] 
[712 ms] 
[712 ms] Start: Run in host: test -f '/home/brad.jones/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/node_modules/node-pty/package.json'
[714 ms] 
[715 ms] 
[715 ms] Start: Run in host: test -f '/home/brad.jones/.vscode-remote-containers/dist/vscode-remote-containers-server-0.241.3.js'
[716 ms] 
[716 ms] 
[719 ms] userEnvProbe: loginInteractiveShell (default)
[720 ms] userEnvProbe shell: /bin/bash
[2702 ms] userEnvProbe PATHs:
Probe:     '/home/brad.jones/.asdf/installs/dotnet-core/6.0.302:/home/brad.jones/.asdf/shims:/home/brad.jones/.asdf/bin:/mnt/c/Users/brad.jones/.scoop/apps/vscode/current/data/user-data/User/globalStorage/ms-vscode-remote.remote-containers/cli-bin:/mnt/c/Users/brad.jones/.scoop/apps/vscode/current/bin:/mnt/c/Program Files/Google/Chrome/Application:/mnt/c/Program Files/Mozilla Firefox:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32:/home/brad.jones/.dprint/bin:/home/brad.jones/.local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin'
Container: None
[2705 ms] Setting up container for folder or workspace: /home/brad.jones/Projects/Personal/toolbox
[2707 ms] Start: Check Docker is running
[2708 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[2860 ms] Server API version: 1.41
[2861 ms] Start: Run in Host: docker volume ls -q
[3047 ms] Start: Run in Host: docker ps -q -a --filter label=vsch.local.folder=\\wsl$\Fedora33\home\brad.jones\Projects\Personal\toolbox --filter label=vsch.quality=stable
[3158 ms] Start: Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=\\wsl$\Fedora33\home\brad.jones\Projects\Personal\toolbox
[3282 ms] Start: Run in Host: /home/brad.jones/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/node /home/brad.jones/.vscode-remote-containers/dist/dev-containers-cli-0.241.3/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /home/brad.jones/Projects/Personal/toolbox --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl$\Fedora33\home\brad.jones\Projects\Personal\toolbox --log-level debug --log-format json --config /home/brad.jones/Projects/Personal/toolbox/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true --terminal-columns 199 --terminal-rows 12
[3405 ms] remote-containers 0.241.3.
[3405 ms] Start: Run: docker buildx version
[3594 ms] Start: Resolving Remote
[3597 ms] Start: Run: git rev-parse --show-cdup
[3617 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=\\wsl$\Fedora33\home\brad.jones\Projects\Personal\toolbox
[3737 ms] Start: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /home/brad.jones/Projects/Personal/toolbox/.devcontainer/Dockerfile -t vsc-toolbox-0724732ea3bf27a2399f75460fa1c89c --build-arg VARIANT=1-bullseye --build-arg NODE_VERSION=lts/* /home/brad.jones/Projects/Personal/toolbox/.devcontainer
[+] Building 48.9s (9/9) FINISHED                                                                                                                                                                      
 => [internal] booting buildkit                                                                                                                                                                   3.1s
 => => starting container buildx_buildkit_benchmark-builder0                                                                                                                                      3.1s
 => [internal] load build definition from Dockerfile                                                                                                                                              0.0s
 => => transferring dockerfile: 1.18kB                                                                                                                                                            0.0s
 => [internal] load .dockerignore                                                                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                                                                   0.0s
 => [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/go:0-1-bullseye                                                                                                           0.5s
 => CACHED [1/2] FROM mcr.microsoft.com/vscode/devcontainers/go:0-1-bullseye@sha256:32c5123110d1e8a6ce1e4ca6d62c33ba944e7112ba0d22fa5fcdbebd84bed4fa                                              0.0s
 => => resolve mcr.microsoft.com/vscode/devcontainers/go:0-1-bullseye@sha256:32c5123110d1e8a6ce1e4ca6d62c33ba944e7112ba0d22fa5fcdbebd84bed4fa                                                     0.0s
 => [2/2] RUN if [ "lts/*" != "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install lts/* 2>&1"; fi                                                            13.0s
 => preparing layers for inline cache                                                                                                                                                            15.4s
 => exporting to oci image format                                                                                                                                                                16.7s
 => => exporting layers                                                                                                                                                                           0.0s
 => => exporting manifest sha256:d86cb3214f6e407e277a0629b58655cc5d39dbe539e1853cca63a5bbfd5e1adf                                                                                                 0.0s
 => => exporting config sha256:09dae01fec32d7f99a446d07f01a226b6e08f253baae01035fb00df432cf527c                                                                                                   0.0s
 => => sending tarball                                                                                                                                                                           16.6s
 => importing to docker                                                                                                                                                                           0.6s
[52884 ms] Start: Run: docker inspect --type image vsc-toolbox-0724732ea3bf27a2399f75460fa1c89c
[53014 ms] Error: Command failed: docker inspect --type image vsc-toolbox-0724732ea3bf27a2399f75460fa1c89c
[53014 ms]     at HR (/home/brad.jones/.vscode-remote-containers/dist/dev-containers-cli-0.241.3/dist/spec-node/devContainersSpecCLI.js:239:2183)
[53015 ms]     at tb (/home/brad.jones/.vscode-remote-containers/dist/dev-containers-cli-0.241.3/dist/spec-node/devContainersSpecCLI.js:239:2121)
[53015 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[53015 ms]     at async QR (/home/brad.jones/.vscode-remote-containers/dist/dev-containers-cli-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:2006)
[53015 ms]     at async cb (/home/brad.jones/.vscode-remote-containers/dist/dev-containers-cli-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:3110)
[53015 ms]     at async i_ (/home/brad.jones/.vscode-remote-containers/dist/dev-containers-cli-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:13194)
[53015 ms]     at async n_ (/home/brad.jones/.vscode-remote-containers/dist/dev-containers-cli-0.241.3/dist/spec-node/devContainersSpecCLI.js:245:12950)
[53024 ms] Exit code 1
[53030 ms] Command failed: /home/brad.jones/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/node /home/brad.jones/.vscode-remote-containers/dist/dev-containers-cli-0.241.3/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /home/brad.jones/Projects/Personal/toolbox --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl$\Fedora33\home\brad.jones\Projects\Personal\toolbox --log-level debug --log-format json --config /home/brad.jones/Projects/Personal/toolbox/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true --terminal-columns 199 --terminal-rows 12
[53030 ms] Exit code 1
```

**Comment by brad-jones** [comment]
Never mind me, not entirely sure what I did to resolve my issue but I have a working devcontainer again.
I think it might have been a case of recycling the `buildx_buildkit_benchmark-builder0` container.
If this happens again or turns out to be intermittent, I'll re-open this ticket.
