### ISSUE TITLE
vscode-server will exit automatically when last connection closed

### ISSUE THREAD

**Issue by mat-wang** [microsoft/vscode-remote-release#6968]
- VSCode Version: VS Code Server 20220708.2
- Local OS Version: Windows 10/11
- Remote OS Version: Linux version 5.10.0-16-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.127-1 (2022-06-30)
- Remote Extension/Connection Type: Server
- Logs:
```bash
$ user@debian-server: cat /home/user1/.vscode-server/data/logs/20220720T094703/remoteagent.log
  [2022-07-20 09:47:03.236] [remoteagent] [info] Extension host agent started.
  [2022-07-20 09:48:19.587] [remoteagent] [info] [*.*.*.*][3896a47c][ManagementConnection] New connection established.
  [2022-07-20 09:48:21.882] [remoteagent] [info] [*.*.*.*][3b86c516][ExtensionHostConnection] New connection established.
  [2022-07-20 09:48:21.887] [remoteagent] [info] [*.*.*.*][3b86c516][ExtensionHostConnection] <1503> Launched Extension Host Process.
  [2022-07-20 09:49:07.713] [remoteagent] [info] [*.*.*.*][3b86c516][ExtensionHostConnection] The client has reconnected.
  [2022-07-20 10:02:01.760] [remoteagent] [info] [*.*.*.*][3896a47c][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
  [2022-07-20 10:02:01.793] [remoteagent] [info] [*.*.*.*][3b86c516][ExtensionHostConnection] <1503> Extension Host Process exited with code: 0, signal: null.
  [2022-07-20 10:02:01.794] [remoteagent] [info] Last EH closed, waiting before shutting down
  [2022-07-20 10:02:09.503] [remoteagent] [info] [*.*.*.*][64882670][ManagementConnection] New connection established.
  [2022-07-20 10:02:09.558] [remoteagent] [info] [*.*.*.*][408f2dbc][ExtensionHostConnection] New connection established.
  [2022-07-20 10:02:09.574] [remoteagent] [info] [*.*.*.*][408f2dbc][ExtensionHostConnection] <1662> Launched Extension Host Process.
  [2022-07-20 10:07:01.798] [remoteagent] [info] New EH opened, aborting shutdown
  [2022-07-20 10:08:10.165] [remoteagent] [info] [*.*.*.*][64882670][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
  [2022-07-20 10:08:10.196] [remoteagent] [info] [*.*.*.*][408f2dbc][ExtensionHostConnection] <1662> Extension Host Process exited with code: 0, signal: null.
  [2022-07-20 10:08:10.196] [remoteagent] [info] Last EH closed, waiting before shutting down
  [2022-07-20 10:13:10.199] [remoteagent] [info] Last EH closed, shutting down
```
```bash
$ user@debian-server: cat /home/user1/.vscode-server/data/logs/20220720T094703/exthost1/exthost.log
  [2022-07-20 09:48:57.653] [exthost] [info] Extension host with pid 1503 started
  [2022-07-20 09:49:04.520] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
  [2022-07-20 09:49:04.553] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: true, activationEvent: '*'
  [2022-07-20 09:49:04.555] [exthost] [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
  [2022-07-20 09:49:04.558] [exthost] [info] ExtensionService#_doActivateExtension vscode.ipynb, startup: true, activationEvent: '*'
  [2022-07-20 09:49:04.568] [exthost] [info] ExtensionService#_doActivateExtension mtxr.sqltools, startup: true, activationEvent: '*'
  [2022-07-20 09:49:06.535] [exthost] [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
  [2022-07-20 09:49:06.584] [exthost] [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
  [2022-07-20 09:49:08.481] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onStartupFinished'
  [2022-07-20 09:49:08.493] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
  [2022-07-20 09:49:08.496] [exthost] [info] ExtensionService#_doActivateExtension aaron-bond.better-comments, startup: false, activationEvent: 'onStartupFinished'
  [2022-07-20 09:49:08.500] [exthost] [info] ExtensionService#_doActivateExtension dsznajder.es7-react-js-snippets, startup: false, activationEvent: 'onStartupFinished'
  [2022-07-20 09:49:08.880] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens, startup: false, activationEvent: 'onStartupFinished'
  [2022-07-20 09:49:08.986] [exthost] [info] ExtensionService#_doActivateExtension Gruntfuggly.todo-tree, startup: false, activationEvent: 'onStartupFinished'
  [2022-07-20 09:49:09.010] [exthost] [info] ExtensionService#_doActivateExtension PKief.material-icon-theme, startup: false, activationEvent: 'onStartupFinished'
  [2022-07-20 09:49:09.033] [exthost] [info] ExtensionService#_doActivateExtension zhuangtongfa.material-theme, startup: false, activationEvent: 'onStartupFinished'
  [2022-07-20 09:49:09.042] [exthost] [info] Eager extensions activated
  [2022-07-20 09:49:28.134] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
  [2022-07-20 09:49:37.612] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:jsonc'
  [2022-07-20 09:49:37.619] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
  [2022-07-20 09:49:37.721] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
  [2022-07-20 10:02:01.755] [exthost] [info] Extension host terminating: received terminate message from renderer
  [2022-07-20 10:02:01.777] [exthost] [error] An error occurred when deactivating the subscriptions for extension 'Gruntfuggly.todo-tree':
  [2022-07-20 10:02:01.778] [exthost] [error] Error: Encountered errors while disposing of store. Errors: [TypeError: c.dispose is not a function, TypeError: c.dispose is not a function]
          at w (/home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:10:12412)
          at b._deactivate (/home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:97:13312)
          at /home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:97:10645
          at Array.map (<anonymous>)
          at b._deactivateAll (/home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:97:10632)
          at b.terminate (/home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:97:11014)
          at b.terminate (/home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:101:620)
          at m (/home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:111:36671)
          at /home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:111:34616
          at b.invoke (/home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
          at v.deliver (/home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
          at p.fire (/home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
          at a.fire (/home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:69:18976)
          at r._receiveMessage (/home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:69:23563)
          at /home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:69:22583
          at b.invoke (/home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
          at v.deliver (/home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
          at p.fire (/home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
          at p.acceptChunk (/home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:69:15807)
          at /home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:69:14937
          at b.invoke (/home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
          at v.deliver (/home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
          at p.fire (/home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
          at f._processReadQueue (/home/user1/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:111:21245)
  [2022-07-20 10:02:01.787] [exthost] [info] Extension host with pid 1503 exiting with code 0
```

```bash
$ user@debian-server: cat /home/user1/.vscode-server/data/logs/20220720T094703/exthost2/exthost.log
  [2022-07-20 10:02:16.834] [exthost] [info] Extension host with pid 1662 started
  [2022-07-20 10:02:17.429] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
  [2022-07-20 10:02:17.466] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: true, activationEvent: '*'
  [2022-07-20 10:02:17.469] [exthost] [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
  [2022-07-20 10:02:17.471] [exthost] [info] ExtensionService#_doActivateExtension vscode.ipynb, startup: true, activationEvent: '*'
  [2022-07-20 10:02:17.481] [exthost] [info] ExtensionService#_doActivateExtension mtxr.sqltools, startup: true, activationEvent: '*'
  [2022-07-20 10:02:17.787] [exthost] [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
  [2022-07-20 10:02:17.881] [exthost] [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
  [2022-07-20 10:02:18.237] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onStartupFinished'
  [2022-07-20 10:02:18.250] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
  [2022-07-20 10:02:18.253] [exthost] [info] ExtensionService#_doActivateExtension aaron-bond.better-comments, startup: false, activationEvent: 'onStartupFinished'
  [2022-07-20 10:02:18.257] [exthost] [info] ExtensionService#_doActivateExtension dsznajder.es7-react-js-snippets, startup: false, activationEvent: 'onStartupFinished'
  [2022-07-20 10:02:18.671] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens, startup: false, activationEvent: 'onStartupFinished'
  [2022-07-20 10:02:18.769] [exthost] [info] ExtensionService#_doActivateExtension Gruntfuggly.todo-tree, startup: false, activationEvent: 'onStartupFinished'
  [2022-07-20 10:02:18.793] [exthost] [info] ExtensionService#_doActivateExtension PKief.material-icon-theme, startup: false, activationEvent: 'onStartupFinished'
  [2022-07-20 10:02:18.808] [exthost] [info] ExtensionService#_doActivateExtension zhuangtongfa.material-theme, startup: false, activationEvent: 'onStartupFinished'
  [2022-07-20 10:02:18.817] [exthost] [info] Eager extensions activated
  [2022-07-20 10:02:19.847] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
  [2022-07-20 10:02:56.901] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:jsonc'
  [2022-07-20 10:02:56.906] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
  [2022-07-20 10:02:56.960] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
  [2022-07-20 10:07:48.254] [exthost] [info] ExtensionService#_doActivateExtension vscjava.vscode-maven, startup: false, activationEvent: 'onView:mavenProjects'
  [2022-07-20 10:08:10.158] [exthost] [info] Extension host terminating: received terminate message from renderer
  [2022-07-20 10:08:10.178] [exthost] [error] An error occurred when deactivating the subscriptions for extension 'Gruntfuggly.todo-tree':
  [2022-07-20 10:08:10.179] [exthost] [error] Error: Encountered errors while disposing of store. Errors: [TypeError: c.dispose is not a function, TypeError: c.dispose is not a function]
          at w (/home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:10:12412)
          at b._deactivate (/home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:97:13312)
          at /home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:97:10645
          at Array.map (<anonymous>)
          at b._deactivateAll (/home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:97:10632)
          at b.terminate (/home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:97:11014)
          at b.terminate (/home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:101:620)
          at m (/home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:111:36671)
          at /home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:111:34616
          at b.invoke (/home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
          at v.deliver (/home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
          at p.fire (/home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
          at a.fire (/home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:69:18976)
          at r._receiveMessage (/home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:69:23563)
          at /home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:69:21097
          at b.invoke (/home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
          at v.deliver (/home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
          at p.fire (/home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
          at p.acceptChunk (/home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:69:15807)
          at /home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:69:14937
          at b.invoke (/home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
          at v.deliver (/home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
          at p.fire (/home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
          at f._processReadQueue (/home/matthew/.vscode-cli/server-stable-web/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:111:21245)
  [2022-07-20 10:08:10.190] [exthost] [info] Extension host with pid 1662 exiting with code 0
```

Steps to Reproduce:

1. screen -S vscode-server
2. dbus-run-session -- sh -c "(echo 'somecredstorepass' | gnome-keyring-daemon --unlock) && code-server serve-local --host 0.0.0.0"
3. Ctrl+A D
4. visit the vscode on web
5. close the browser
6. wait about 1 - 2 minutes

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by tanhakabir** [comment]
What happens if you reopen that link in the browser?

**Comment by Jeffery-Song** [comment]
A workaround is to write a systemd service script for vscode-server.

**Comment by mat-wang** [comment]
> What happens if you reopen that link in the browser?

There is an ERR_CONNECTION_REFUSED error showed.

**Comment by mat-wang** [comment]
> > What happens if you reopen that link in the browser?
> 
> 
> 
> There is an ERR_CONNECTION_REFUSED error showed.

Also, as the running process with $ ps aux | grep 'code-server', there's no code-server process running.

**Comment by mat-wang** [comment]
> A workaround is to write a systemd service script for vscode-server.

Yes, and currently I am running code-server as a systemd controlled service with writing a startup bash script and wiring a template service file

**Comment by aeschli** [comment]
I pushed a fix so that the server no longer shuts down
