### ISSUE TITLE
remote.SSH.serverInstallPath setting is ignored in remote Linux

### ISSUE THREAD

**Issue by kuatwal** [microsoft/vscode-remote-release#6981]
When test an issue and before it is mark as fixed, you MUST test on remote Linux and remote MAC OS and remote Windows.

Testing only on remote Windows and marking issue fixed is ridiculous.

**Comment by kuatwal** [comment]
[11:17:08.426] "remote.SSH.serverInstallPath": {"work":"/scratch1/<user>"}
[11:17:08.438] SSH Resolver called for host: 10.129.251.23
[11:17:08.438] Setting up SSH remote "10.129.251.23"
[11:17:08.444] Using commit id "b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a" and quality "stable" for server
[11:17:08.447] Install and start server if needed
[11:17:08.450] Checking ssh with "ssh -V"
[11:17:08.480] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[11:17:08.484] Running script with connection command: ssh -T -D 59480 "10.129.251.23" bash
[11:17:08.487] Terminal shell path: C:\Windows\System32\cmd.exe
[11:17:08.701] > ]0;C:\Windows\System32\cmd.exe
[11:17:08.702] Got some output, clearing connection timeout
[11:17:08.966] > <user>@10.129.251.23's password: 
[11:17:08.967] Showing password prompt
[11:17:16.778] Got password response
[11:17:16.779] "install" wrote data to terminal: "********"
[11:17:16.806] > 
[11:17:16.896] > Could not chdir to home directory /home/<user>:
> c219e0de1aae: running
[11:17:16.938] > Creating the server install dir failed...
> c219e0de1aae: start
> exitCode==34==
> listeningOn====
> osReleaseId====
> arch====
> tmpDir==/tmp==
> platform====
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> c219e0de1aae: end
> mkdir: cannot create directory '/home/<user>':

**Comment by bamurtaugh** [comment]
Hi @kuatwal, it sounds like this issue stems from another. Could you please link the other issue here too? Thanks!

**Comment by kuatwal** [comment]
https://github.com/microsoft/vscode-remote-release/issues/940

**Comment by bamurtaugh** [comment]
Looks like this ultimately was part of https://github.com/microsoft/vscode-remote-release/issues/472, cc @tanhakabir

**Comment by tanhakabir** [comment]
`serverInstallPath` expects an absolute path. I believe that might be the root cause of your issue. Additionally could you share your full logs including the first half?

**Comment by kuatwal** [comment]
I am using an absolute path of /scratch/katwal

What I see is that you are checking for error codes from your chdir /scratch/katwal command.
chdir is NOT an Linux command.  Your need to use cd /scratch/katwal

As I said, testing only on Windows is insufficient.

This is preventing me from installing on a second server, as the install path is not respected by ~/.vscode and ~/.vscode-server


[11:59:10.080] Log Level: 2
[11:59:10.081] [remote-ssh@0.84.0](mailto:remote-ssh@0.84.0)
[11:59:10.081] win32 x64
[11:59:10.087] SSH Resolver called for "ssh-remote+10.129.251.23", attempt 1
[11:59:10.088] "remote.SSH.useLocalServer": false
[11:59:10.088] "remote.SSH.showLoginTerminal": false
[11:59:10.088] "remote.SSH.remotePlatform": {"scapen-ol7-4.us.oracle.com":"linux","10.129.251.23":"linux"}
[11:59:10.088] "remote.SSH.path": undefined
[11:59:10.088] "remote.SSH.configFile": undefined
[11:59:10.088] "remote.SSH.useFlock": true
[11:59:10.088] "remote.SSH.lockfilesInTmp": false
[11:59:10.088] "remote.SSH.localServerDownload": auto
[11:59:10.088] "remote.SSH.remoteServerListenOnSocket": false
[11:59:10.088] "remote.SSH.showLoginTerminal": false
[11:59:10.088] "remote.SSH.defaultExtensions": []
[11:59:10.088] "remote.SSH.loglevel": 2
[11:59:10.088] "remote.SSH.enableDynamicForwarding": true
[11:59:10.089] "remote.SSH.enableRemoteCommand": false
[11:59:10.089] "remote.SSH.serverPickPortsFromRange": {}
[11:59:10.089] "remote.SSH.serverInstallPath": {"work":"/scratch1/katwal"}
[11:59:10.102] SSH Resolver called for host: 10.129.251.23
[11:59:10.102] Setting up SSH remote "10.129.251.23"
[11:59:10.107] Using commit id "3b889b090b5ad5793f524b5d1d39fda662b96a2a" and quality "stable" for server
[11:59:10.110] Install and start server if needed
[11:59:10.113] Checking ssh with "ssh -V"
[11:59:10.151] > OpenSSH_for_Wind
[11:59:10.151] > ows_8.1p1, LibreSSL 3.0.2

[11:59:10.156] Running script with connection command: ssh -T -D 60461 "10.129.251.23" bash
[11:59:10.159] Terminal shell path: C:\Windows\System32\cmd.exe
[11:59:10.387] > ]0;C:\Windows\System32\cmd.exe
[11:59:10.387] Got some output, clearing connection timeout
[11:59:10.708] > [katwal@10.129.251.23's](mailto:katwal@10.129.251.23's) password: 
[11:59:10.709] Showing password prompt
[11:59:23.752] Got password response
[11:59:23.752] "install" wrote data to terminal: "********"
[11:59:23.770] > 
[11:59:23.921] > Could not chdir to home directory /home/katwal: Too many levels of symbolic link
> s
[11:59:23.933] > bash: /home/katwal/.bashrc: Too many levels of symbolic links
[11:59:23.948] > 3275b863e7c7: running
[11:59:23.965] > mkdir: cannot create directory '/home/katwal': Too many levels of symbolic links
> Creating the server install dir failed...
> 3275b863e7c7: start
> exitCode==34==
> listeningOn====
> osReleaseId====
> arch====
> tmpDir==/tmp==
> platform====
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 3275b863e7c7: end
[11:59:23.966] Received install output: 
exitCode==34==
listeningOn====
osReleaseId====
arch====
tmpDir==/tmp==
platform====
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[11:59:23.966] Failed to parse remote port from server output
[11:59:23.966] Resolver error: Error: 
              at Function.Create (c:\Users\katwal\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:585222)
              at Object.t.handleInstallOutput (c:\Users\katwal\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:583874)
              at Object.t.tryInstall (c:\Users\katwal\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:681023)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
              at async c:\Users\katwal\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:643908
              at async Object.t.withShowDetailsEvent (c:\Users\katwal\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:647224)
              at async Object.t.resolve (c:\Users\katwal\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:644958)
              at async c:\Users\katwal\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:727082
[11:59:23.972] ------




[11:59:25.235] "install" terminal command done
[11:59:25.235] Install terminal quit with output:

**Comment by kuatwal** [comment]
Also, when /home/katwal does exist, it complete ignores the install path setting, and tries to install in /home/katwal

So there are two bugs:
1. Ignoring the Install path when the default install path exists.

2. Running a Windows command on linux:  chdir when the install path does not exist.

[12:38:50.623] "remote.SSH.serverInstallPath": {"work":"/scratch1/katwal"}
[12:38:50.635] SSH Resolver called for host: 10.129.251.23
[12:38:50.635] Setting up SSH remote "10.129.251.23"
[12:38:50.640] Using commit id "3b889b090b5ad5793f524b5d1d39fda662b96a2a" and quality "stable" for server
[12:38:50.642] Install and start server if needed
[12:38:50.646] Checking ssh with "ssh -V"
[12:38:50.675] > OpenSSH_for_Windows
[12:38:50.676] > _8.1p1, LibreSSL 3.0.2

[12:38:50.681] Running script with connection command: ssh -T -D 60838 "10.129.251.23" bash
[12:38:50.683] Terminal shell path: C:\Windows\System32\cmd.exe
[12:38:50.891] > ]0;C:\Windows\System32\cmd.exe
[12:38:50.891] Got some output, clearing connection timeout
[12:38:51.161] > [katwal@10.129.251.23's](mailto:katwal@10.129.251.23's) password: 
[12:38:51.162] Showing password prompt
[12:38:58.582] Got password response
[12:38:58.582] "install" wrote data to terminal: "********"
[12:38:58.616] > 
[12:38:58.741] > 242e3b2fa5f3: running
[12:38:58.764] > mkdir: cannot create directory '/home/katwal/.vscode-server': File exists
> Creating the server install dir failed...

**Comment by tanhakabir** [comment]
Could you add the machine you're trying to connect to to the `remote.SSH.remotePlatform` setting?

**Comment by roblourens** [comment]
> [11:59:23.921] > Could not chdir to home directory /home/katwal: Too many levels of symbolic links
> [11:59:23.933] > bash: /home/katwal/.bashrc: Too many levels of symbolic links

These errors came before we run any code- I think they are coming from your own bashrc or other configuration. Not really clear 

> [11:59:10.089] "remote.SSH.serverInstallPath": {"work":"/scratch1/katwal"}

This is configured for a hostname "work" while you are connecting to an IP address, so this setting isn't be applied to this host.
