### ISSUE TITLE
Cannot clone repo in container volume

### ISSUE THREAD

**Issue by andrea8moro** [microsoft/vscode-remote-release#6982]
I was trying the "clone repo in container volume" feature with the example repo https://github.com/Microsoft/vscode-remote-try-node and I got the following error. it seems that the file is not in the bootstrap image but it is present in the node-spec dir of the remote container extension. what can I try?

[2022-07-21T18:18:32.003Z] Start: Run in container: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.241.3/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /workspaces/vscode-remote-try-node --workspace-mount-consistency cached --id-label vsch.local.repository=https://github.com/Microsoft/vscode-remote-try-node --id-label vsch.local.repository.volume=vscode-remote-try-node-6789fd329eb29bc56aab44eb27506206 --id-label vsch.local.repository.folder=vscode-remote-try-node --log-level debug --log-format json --config /workspaces/vscode-remote-try-node/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-fd3c3daf-33f7-4835-8cfc-c6b5d9c98252.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode-remote-try-node-6789fd329eb29bc56aab44eb27506206,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root true --terminal-columns 224 --terminal-rows 20
[2022-07-21T18:18:32.491Z] internal/modules/cjs/loader.js:905
[2022-07-21T18:18:32.492Z]   throw err;
[2022-07-21T18:18:32.492Z]   ^
[2022-07-21T18:18:32.492Z] Error: Cannot find module '/root/.vscode-remote-containers/dist/dev-containers-cli-0.241.3/dist/spec-node/devContainersSpecCLI.js'
[2022-07-21T18:18:32.492Z]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
[2022-07-21T18:18:32.492Z]     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
[2022-07-21T18:18:32.492Z]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
[2022-07-21T18:18:32.492Z]     at internal/main/run_main_module.js:17:47 {
[2022-07-21T18:18:32.492Z]   code: 'MODULE_NOT_FOUND',
[2022-07-21T18:18:32.492Z]   requireStack: []
[2022-07-21T18:18:32.493Z] }
[2022-07-21T18:18:32.533Z] Stop (530 ms): Run in container: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.241.3/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /workspaces/vscode-remote-try-node --workspace-mount-consistency cached --id-label vsch.local.repository=https://github.com/Microsoft/vscode-remote-try-node --id-label vsch.local.repository.volume=vscode-remote-try-node-6789fd329eb29bc56aab44eb27506206 --id-label vsch.local.repository.folder=vscode-remote-try-node --log-level debug --log-format json --config /workspaces/vscode-remote-try-node/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-fd3c3daf-33f7-4835-8cfc-c6b5d9c98252.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode-remote-try-node-6789fd329eb29bc56aab44eb27506206,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root true --terminal-columns 224 --terminal-rows 20
[2022-07-21T18:18:32.533Z] Exit code 1
[2022-07-21T18:18:32.534Z] Start: Run: docker rm -f 40f7e7fbf66c62a020ec7c143e0d3458d2b4a1cff265e530baa7bb64e4d4632a
[2022-07-21T18:18:32.541Z] Command failed: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.241.3/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /workspaces/vscode-remote-try-node --workspace-mount-consistency cached --id-label vsch.local.repository=https://github.com/Microsoft/vscode-remote-try-node --id-label vsch.local.repository.volume=vscode-remote-try-node-6789fd329eb29bc56aab44eb27506206 --id-label vsch.local.repository.folder=vscode-remote-try-node --log-level debug --log-format json --config /workspaces/vscode-remote-try-node/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-fd3c3daf-33f7-4835-8cfc-c6b5d9c98252.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode-remote-try-node-6789fd329eb29bc56aab44eb27506206,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root true --terminal-columns 224 --terminal-rows 20
[2022-07-21T18:18:32.541Z] Exit code 1
[2022-07-21T18:18:33.011Z] Stop (7707 ms): Run in container: /bin/sh
[2022-07-21T18:18:33.026Z] Stop (7510 ms): Run in container: /bin/sh
[2022-07-21T18:18:33.027Z] Container server terminated (code: 137, signal: null).
[2022-07-21T18:18:33.444Z] Stop (910 ms): Run: docker rm -f 40f7e7fbf66c62a020ec7c143e0d3458d2b4a1cff265e530baa7bb64e4d4632a
[2022-07-21T18:18:37.145Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2022-07-21T18:18:37.529Z] Stop (384 ms): Run: docker version --format {{.Server.APIVersion}}
[2022-07-21T18:18:37.529Z] 1.41

**Comment by andrea8moro** [comment]
upgrading to 243 did the trick.
