### ISSUE TITLE
Remote SSH is not working suddenlyOn MAC

### ISSUE THREAD

**Issue by krishnakesanasetti** [microsoft/vscode-remote-release#6996]
I am unable to use VSCode remote ssh on MAC suddenly it worked previously and below are the logs. It's complaining about an timeout issue.

`[08:46:42.288] Log Level: 2
[08:46:42.289] remote-ssh@0.84.0
[08:46:42.289] darwin x64
[08:46:42.293] SSH Resolver called for "ssh-remote+cte-workstation.xx.xx.com", attempt 1
[08:46:42.294] "remote.SSH.useLocalServer": true
[08:46:42.294] "remote.SSH.path": undefined
[08:46:42.294] "remote.SSH.configFile": undefined
[08:46:42.295] "remote.SSH.useFlock": true
[08:46:42.295] "remote.SSH.lockfilesInTmp": false
[08:46:42.295] "remote.SSH.localServerDownload": auto
[08:46:42.295] "remote.SSH.remoteServerListenOnSocket": false
[08:46:42.296] "remote.SSH.showLoginTerminal": true
[08:46:42.296] "remote.SSH.defaultExtensions": []
[08:46:42.296] "remote.SSH.loglevel": 2
[08:46:42.296] "remote.SSH.enableDynamicForwarding": true
[08:46:42.296] "remote.SSH.enableRemoteCommand": false
[08:46:42.297] "remote.SSH.serverPickPortsFromRange": {}
[08:46:42.297] "remote.SSH.serverInstallPath": {}
[08:46:42.311] SSH Resolver called for host: cte-workstation.xx.xx.com
[08:46:42.311] Setting up SSH remote "cte-workstation.xx.xx.com"
[08:46:42.314] Acquiring local install lock: /var/folders/r5/zjnbr5sn2q311kx0p7d_jb040000gn/T/vscode-remote-ssh-d7e0e825-install.lock
[08:46:42.315] Looking for existing server data file at /Users/krishnakesanasetti/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-d7e0e825-3b889b090b5ad5793f524b5d1d39fda662b96a2a-0.84.0/data.json
[08:46:42.315] Using commit id "3b889b090b5ad5793f524b5d1d39fda662b96a2a" and quality "stable" for server
[08:46:42.318] Install and start server if needed
[08:46:42.320] PATH: /Users/krishnakesanasetti/Documents/google-cloud-sdk/bin:/Users/krishnakesanasetti/Documents/terraform:/opt/chef-workstation/bin:/Users/krishnakesanasetti/.chef/gem/ruby/3.0.0/bin:/opt/chef-workstation/embedded/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/chef-workstation/gitbin
[08:46:42.320] Checking ssh with "ssh -V"
[08:46:42.330] > OpenSSH_8.1p1, LibreSSL 2.7.3

[08:46:42.332] askpass server listening on /var/folders/r5/zjnbr5sn2q311kx0p7d_jb040000gn/T/vscode-ssh-askpass-350034d823048d0b99d835d180a429a2aadfd3b0.sock
[08:46:42.332] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/r5/zjnbr5sn2q311kx0p7d_jb040000gn/T/vscode-ssh-askpass-3ed9148614eb0f2e91f89e492452c1b6a66214dd.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","56345","-o","ConnectTimeout=15","cte-workstation.xx.xx.com"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/krishnakesanasetti/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-d7e0e825-3b889b090b5ad5793f524b5d1d39fda662b96a2a-0.84.0/data.json"}
[08:46:42.333] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.st9Kjsu2bK/Listeners","SHELL":"/bin/bash","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/krishnakesanasetti/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/krishnakesanasetti/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/r5/zjnbr5sn2q311kx0p7d_jb040000gn/T/vscode-ssh-askpass-350034d823048d0b99d835d180a429a2aadfd3b0.sock"}
[08:46:42.333] Spawned 7325
[08:46:42.447] > local-server-1> Spawned ssh, pid=7332
[08:46:42.450] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[08:46:42.627] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:90DYLFpbgzAWmHqujNMnOqqO+gonUO81qZrRdc1qu1Y
[08:46:42.952] Got askpass request: {"request":"kkesanasetti@cte-workstation.xx.xx.com's password:"}
[08:46:42.952] Showing password prompt
[08:46:42.953] Listening for interwindow password on /var/folders/r5/zjnbr5sn2q311kx0p7d_jb040000gn/T/vscode-ssh-askpass-d33bdc677bd7c00bf04ff1899edb0f28526d27e6.sock
[08:46:42.953] Writing password prompt to globalState
[08:46:47.856] Got password response
[08:46:47.856] Interactor gave response: *************
[08:46:47.857] Cleaning up other-window auth server
[08:46:47.928] stderr> Authenticated to cte-workstation.xx.xx.com ([172.x.x.x]:22).
[08:46:48.914] > ready: 261fa26f7455
[08:46:49.011] > Linux 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022
[08:46:49.011] Platform: linux
[08:46:49.112] > /bin/bash
[08:46:49.112] Shell: bash
[08:46:49.112] Creating bash subshell inside "bash"
[08:46:49.241] > bash version:  4.2.46(2)-release
[08:46:49.360] > bash version:  4.2.46(2)-release
> bash version:  4.2.46(2)-release
[08:47:04.859] Terminating local server
[08:47:04.861] Resolver error: Error: Connecting with SSH timed out
  at Function.Timeout (/Users/krishnakesanasetti/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585348)
  at Timeout._onTimeout (/Users/krishnakesanasetti/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:630527)
  at listOnTimeout (node:internal/timers:557:17)
  at processTimers (node:internal/timers:500:7)
[08:47:04.866] ------

[08:47:04.867] Local server exit: 15
`

**Comment by krishnakesanasetti** [comment]
Above one with different user and different error

**Comment by bacterio** [comment]
Hi, I'm having the same problem. I can connect through the command line but VS Code is timing out when trying to connect.

[00:10:45.681] Log Level: 2
[00:10:45.681] remote-ssh@0.84.0
[00:10:45.681] darwin arm64
[00:10:45.683] SSH Resolver called for "ssh-remote+dev", attempt 1
[00:10:45.683] "remote.SSH.useLocalServer": true
[00:10:45.684] "remote.SSH.path": undefined
[00:10:45.684] "remote.SSH.configFile": undefined
[00:10:45.684] "remote.SSH.useFlock": true
[00:10:45.684] "remote.SSH.lockfilesInTmp": false
[00:10:45.684] "remote.SSH.localServerDownload": auto
[00:10:45.684] "remote.SSH.remoteServerListenOnSocket": false
[00:10:45.684] "remote.SSH.showLoginTerminal": false
[00:10:45.684] "remote.SSH.defaultExtensions": []
[00:10:45.684] "remote.SSH.loglevel": 2
[00:10:45.684] "remote.SSH.enableDynamicForwarding": true
[00:10:45.684] "remote.SSH.enableRemoteCommand": false
[00:10:45.684] "remote.SSH.serverPickPortsFromRange": {}
[00:10:45.684] "remote.SSH.serverInstallPath": {}
[00:10:45.690] SSH Resolver called for host: dev
[00:10:45.690] Setting up SSH remote "dev"
[00:10:45.692] Acquiring local install lock: /var/folders/_q/pc1rlcqd1kb9njdx62f1q7t80000gn/T/vscode-remote-ssh-d55997bc-install.lock
[00:10:45.693] Looking for existing server data file at /Users/sergio/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-d55997bc-3b889b090b5ad5793f524b5d1d39fda662b96a2a-0.84.0/data.json
[00:10:45.694] Using commit id "3b889b090b5ad5793f524b5d1d39fda662b96a2a" and quality "stable" for server
[00:10:45.696] Install and start server if needed
[00:10:45.697] PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[00:10:45.697] Checking ssh with "ssh -V"
[00:10:45.700] > OpenSSH_8.6p1, LibreSSL 3.3.6

[00:10:45.701] askpass server listening on /var/folders/_q/pc1rlcqd1kb9njdx62f1q7t80000gn/T/vscode-ssh-askpass-267c3ffd5f853a0102e1a80e4bff22da9056a307.sock
[00:10:45.702] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/_q/pc1rlcqd1kb9njdx62f1q7t80000gn/T/vscode-ssh-askpass-46338d790e95f7aa8117bb5337a2422201449618.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","49679","-o","ConnectTimeout=15","dev"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/sergio/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-d55997bc-3b889b090b5ad5793f524b5d1d39fda662b96a2a-0.84.0/data.json"}
[00:10:45.702] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.x8iiIqm1UD/Listeners","SHELL":"/opt/homebrew/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/sergio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/sergio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/_q/pc1rlcqd1kb9njdx62f1q7t80000gn/T/vscode-ssh-askpass-267c3ffd5f853a0102e1a80e4bff22da9056a307.sock"}
[00:10:45.702] Spawned 2184
[00:10:45.765] > local-server-1> Spawned ssh, pid=2188
[00:10:45.766] stderr> OpenSSH_8.6p1, LibreSSL 3.3.6
[00:11:00.769] stderr> ssh: connect to host dev.myserver.com port 52891: Operation timed out
[00:11:00.769] > local-server-1> ssh child died, shutting down
[00:11:00.771] Local server exit: 0
[00:11:00.772] Received install output: local-server-1> Spawned ssh, pid=2188
OpenSSH_8.6p1, LibreSSL 3.3.6
ssh: connect to host dev.myserver.com port 22: Operation timed out
local-server-1> ssh child died, shutting down

[00:11:00.773] Resolver error: Error: Se agotó el tiempo de espera de la operación
	at Function.Offline (/Users/sergio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585273)
	at /Users/sergio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:582910
	at Object.t.handleInstallOutput (/Users/sergio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:583062)
	at Object.e [as tryInstallWithLocalServer] (/Users/sergio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:624373)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/sergio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643506
	at async Object.t.withShowDetailsEvent (/Users/sergio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
	at async /Users/sergio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622845
	at async T (/Users/sergio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:619351)
	at async Object.t.resolveWithLocalServer (/Users/sergio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622460)
	at async Object.t.resolve (/Users/sergio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644834)
	at async /Users/sergio/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[00:11:00.776] ------

**Comment by roblourens** [comment]
It looks like our install script is not running. If you run a command like `echo "echo hello" | ssh yourhost` does that work?

**Comment by roblourens** [comment]
Can reopen if there is an issue here
