### ISSUE TITLE
cannot ssh to windows 10

### ISSUE THREAD

**Issue by chiajen870907** [microsoft/vscode-remote-release#7017]
- VSCode Version: 1.69.2
- Local OS Version: MacOS 13.0
- Remote OS Version: Windows 10 Education
- Remote Extension/Connection Type: SSH

Logs:
```
[13:31:48.129] Log Level: 2
[13:31:48.129] remote-ssh@0.84.0
[13:31:48.129] darwin arm64
[13:31:48.131] SSH Resolver called for "ssh-remote+122.117.53.182", attempt 1
[13:31:48.131] "remote.SSH.useLocalServer": true
[13:31:48.132] "remote.SSH.path": undefined
[13:31:48.132] "remote.SSH.configFile": undefined
[13:31:48.132] "remote.SSH.useFlock": true
[13:31:48.132] "remote.SSH.lockfilesInTmp": false
[13:31:48.132] "remote.SSH.localServerDownload": auto
[13:31:48.132] "remote.SSH.remoteServerListenOnSocket": false
[13:31:48.132] "remote.SSH.showLoginTerminal": true
[13:31:48.132] "remote.SSH.defaultExtensions": []
[13:31:48.132] "remote.SSH.loglevel": 2
[13:31:48.132] "remote.SSH.enableDynamicForwarding": true
[13:31:48.132] "remote.SSH.enableRemoteCommand": false
[13:31:48.132] "remote.SSH.serverPickPortsFromRange": {}
[13:31:48.132] "remote.SSH.serverInstallPath": {}
[13:31:48.140] SSH Resolver called for host: 122.117.53.182
[13:31:48.140] Setting up SSH remote "122.117.53.182"
[13:31:48.141] Acquiring local install lock: /var/folders/xv/vc9s1dz927lb3jwshf88szk00000gn/T/vscode-remote-ssh-5267bbee-install.lock
[13:31:48.143] Looking for existing server data file at /Users/hsiehcj/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-5267bbee-3b889b090b5ad5793f524b5d1d39fda662b96a2a-0.84.0/data.json
[13:31:48.143] Using commit id "3b889b090b5ad5793f524b5d1d39fda662b96a2a" and quality "stable" for server
[13:31:48.146] Install and start server if needed
[13:31:48.148] PATH: /Users/hsiehcj/.pyenv/shims:/Users/hsiehcj/.nvm/versions/node/v16.15.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/hsiehcj/.yarn/bin
[13:31:48.148] Checking ssh with "ssh -V"
[13:31:48.153] > OpenSSH_8.6p1, LibreSSL 3.3.6

[13:31:48.155] askpass server listening on /var/folders/xv/vc9s1dz927lb3jwshf88szk00000gn/T/vscode-ssh-askpass-def053f113174fc2b1b18f1c7f31556711bf3ca0.sock
[13:31:48.155] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/xv/vc9s1dz927lb3jwshf88szk00000gn/T/vscode-ssh-askpass-62043622836488925747c3cc3246df0538a6b3bd.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","62319","-o","ConnectTimeout=60","122.117.53.182"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/hsiehcj/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-5267bbee-3b889b090b5ad5793f524b5d1d39fda662b96a2a-0.84.0/data.json"}
[13:31:48.155] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.vAsN32KtPn/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/hsiehcj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/hsiehcj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/xv/vc9s1dz927lb3jwshf88szk00000gn/T/vscode-ssh-askpass-def053f113174fc2b1b18f1c7f31556711bf3ca0.sock"}
[13:31:48.156] Spawned 67515
[13:31:48.234] > local-server-1> Spawned ssh, pid=67522
[13:31:48.236] stderr> OpenSSH_8.6p1, LibreSSL 3.3.6
[13:31:48.355] stderr> debug1: Server host key: ssh-ed25519 SHA256:Tqr6RqXKasuHCsHD+cqY5wk02t6zjA55zSXj43ANA40
[13:31:48.706] Got askpass request: {"request":"HsiehCJ@122.117.53.182's password:"}
[13:31:48.706] Showing password prompt
[13:31:48.707] Listening for interwindow password on /var/folders/xv/vc9s1dz927lb3jwshf88szk00000gn/T/vscode-ssh-askpass-ef654fa0d3cb659b59f6480d6fc12babfec7fb5e.sock
[13:31:48.707] Writing password prompt to globalState
[13:31:52.861] Got password response
[13:31:52.862] Interactor gave response: ******
[13:31:52.862] Cleaning up other-window auth serve
[13:31:52.920] stderr> Authenticated to 122.117.53.182 ([122.117.53.182]:22).
[13:31:53.099] > PowerShell 7.2.5
> Copyright (c) Microsoft Corporation.
> 
> https://aka.ms/powershell
> Type 'help' to get help.
[13:31:53.450] > PS C:\Users\HsiehCJ> 
[13:31:53.535] > echo 'ready: b44271666a88'
[13:31:53.585] > ready: b44271666a88
[13:31:53.594] > PS C:\Users\HsiehCJ> uname -rsv
[13:32:54.866] Terminating local server
[13:32:54.869] Resolver error: Error: Connecting with SSH timed out
	at Function.Timeout (/Users/hsiehcj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585348)
	at Timeout._onTimeout (/Users/hsiehcj/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:630527)
	at listOnTimeout (node:internal/timers:557:17)
	at processTimers (node:internal/timers:500:7)
[13:32:54.882] ------

[13:32:54.884] Local server exit: 15

```

**Comment by mat-wang** [comment]
Did you set up the firewall of your Windows 10?
