### ISSUE TITLE
Remote Server preview: Error: command 'remote-server.checkForUpdates' already exists

### ISSUE THREAD

**Issue by cruscio** [microsoft/vscode-remote-release#7036]
- VSCode Version: 1.70.0
- Local OS Version: macOS Monterey 12.5 (MacBook Air M1 2020)
- Remote OS Version: Windows 10 Pro 10.0.18363 N/A Build 18363
- Remote Extension/Connection Type: Remote Server v0.1.2022080309
- Logs: Apologies, I cannot share the raw logs. Here is a relevant, if incomplete, subset:

```
  ERR Error: command 'remote-server.checkForUpdates' already exists
	at a.registerCommand (vscode-file://vscode…Process.js:85:62257)
	at Object.registerCommand (vscode-file://vscode…rocess.js:106:31111)
	at Te.resolve (vscode-file://vscode…xtension.js:1:96823)
	at async w.$resolveAuthority (vscode-file://vscode…Process.js:97:21445)
log.ts:313   ERR Cannot register remote filesystem provider. Error while fetching remote environment. command 'remote-server.checkForUpdates' already exists
notificationsAlerts.ts:42 Failed to connect to the remote extension host server (Error: command 'remote-server.checkForUpdates' already exists)
log.ts:313   ERR Error: command 'remote-server.checkForUpdates' already exists
	at a.registerCommand (vscode-file://vscode…Process.js:85:62257)
	at Object.registerCommand (vscode-file://vscode…rocess.js:106:31111)
	at Te.resolve (vscode-file://vscode…xtension.js:1:96823)
	at async w.$resolveAuthority (vscode-file://vscode…Process.js:97:21445)
notificationsAlerts.ts:42 Could not fetch remote environment
onDidChangeNotification	@	notificationsAlerts.ts:42
log.ts:313   ERR command 'remote-server.checkForUpdates' already exists: Error: command 'remote-server.checkForUpdates' already exists
	at a.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:62257)
	at Object.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:31111)
	at Te.resolve (/Users/cruscio/.vscode/extensions/ms-vscode.remote-server-0.1.2022080309/dist/node/extension.js:1:96823)
	at async w.$resolveAuthority (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:21445)
log.ts:313   ERR Error: command 'remote-server.checkForUpdates' already exists
	at a.registerCommand (vscode-file://vscode…Process.js:85:62257)
	at Object.registerCommand (vscode-file://vscode…rocess.js:106:31111)
	at Te.resolve (vscode-file://vscode…xtension.js:1:96823)
	at async w.$resolveAuthority (vscode-file://vscode…Process.js:97:21445)
```

Steps to Reproduce:

1. Start a code-server instance on one machine. 
2. Verify the instance works by accessing the Web URI
3. In VSCode on another machine, `Connect to Remote...` & select the running instance from `step 1`
4. After a few minutes, there will be multiple stacked progress notifications in the lower right for `Connecting to {{instance name}}`

Does this issue occur when you try this locally?: Untested
Does this issue occur when you try this locally and all extensions are disabled?: Untested

**Comment by tanhakabir** [comment]
I'm not reproing this. Are you still seeing these errors?

**Comment by connor4312** [comment]
I think this probably happened when we renamed our extension. If you still see this, I recommend checking your installed extensions and removing any old deprecated extensions. Please let us know if you still hit this..
