### ISSUE TITLE
MacOS connection failed.

### ISSUE THREAD

**Issue by GiganticRay** [microsoft/vscode-remote-release#7086]
🚨 The issue tracker is not for questions 🚨

If you have a question about VS Code, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code and about
VS Code Remote on https://stackoverflow.com/questions/tagged/vscode-remote.

I switched my working pc to macbook. Like before I download the vscode and try to log in my remote server, but error occured: 

[19:31:15.726] Acquiring local install lock: /var/folders/6r/2fwlrfcd5f5fggmrj99xmx740000gn/T/vscode-remote-ssh-b82b5ad0-install.lock
[19:31:15.726] Looking for existing server data file at /Users/lei/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-b82b5ad0-da76f93349a72022ca4670c1b84860304616aaa2-0.84.0/data.json
[19:31:15.727] Using commit id "da76f93349a72022ca4670c1b84860304616aaa2" and quality "stable" for server
[19:31:15.728] Install and start server if needed
[19:31:15.730] askpass server listening on /var/folders/6r/2fwlrfcd5f5fggmrj99xmx740000gn/T/vscode-ssh-askpass-bb1a462ae7119893badffba59e9c6ff7d7dc9ed5.sock
[19:31:15.730] Spawning local server with {"serverId":5,"ipcHandlePath":"/var/folders/6r/2fwlrfcd5f5fggmrj99xmx740000gn/T/vscode-ssh-askpass-e77dc65c39d3dbb7b4437bb6760781e1e919d5d5.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","55535","-o","ConnectTimeout=15","xxxx"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/lei/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-b82b5ad0-da76f93349a72022ca4670c1b84860304616aaa2-0.84.0/data.json"}
[19:31:15.730] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.uARsoN5SfE/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/lei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/private/var/folders/6r/2fwlrfcd5f5fggmrj99xmx740000gn/T/AppTranslocation/D9314D6A-092C-4A42-9F82-C99A181AF34C/d/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/lei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/6r/2fwlrfcd5f5fggmrj99xmx740000gn/T/vscode-ssh-askpass-bb1a462ae7119893badffba59e9c6ff7d7dc9ed5.sock"}
[19:31:15.731] Spawned 38654
[19:31:15.803] > local-server-5> Spawned ssh, pid=38656
[19:31:15.804] stderr> OpenSSH_8.6p1, LibreSSL 3.3.6
[19:31:30.807] stderr> ssh: connect to host 30.xx.xx.xx port 22: Operation timed out
[19:31:30.809] > local-server-5> ssh child died, shutting down
[19:31:30.816] Local server exit: 0
[19:31:30.817] Received install output: local-server-5> Spawned ssh, pid=38656
OpenSSH_8.6p1, LibreSSL 3.3.6
ssh: connect to host 30.xx.xx.xx port 22: Operation timed out
local-server-5> ssh child died, shutting down

[19:31:30.818] Resolver error: Error: The operation timed out
	at Function.Offline (/Users/lei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585273)
	at /Users/lei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:582910
	at Object.t.handleInstallOutput (/Users/lei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:583062)
	at Object.e [as tryInstallWithLocalServer] (/Users/lei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:624373)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/lei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643506
	at async Object.t.withShowDetailsEvent (/Users/lei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
	at async /Users/lei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622845
	at async T (/Users/lei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:619351)
	at async Object.t.resolveWithLocalServer (/Users/lei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622460)
	at async Object.t.resolve (/Users/lei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644834)
	at async /Users/lei/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082

Then later I get back to my old pc(windows), and I can connect my server (in windows), But macbook is not ok, can anyone give me some suggestions? thanks!

**Comment by tanhakabir** [comment]
> ssh: connect to host 30.xx.xx.xx port 22: Operation timed out

Looks like an SSH issue. What happens if you try to connect to the same remote through terminal?
