### ISSUE TITLE
docker start yields exit code 1 (Mac M1)

### ISSUE THREAD

**Issue by cgebbe** [microsoft/vscode-remote-release#7114]
# Steps to reproduce

- Remote-Containers: Add Development Container Configuration Files
- Select alpine and latest (or anything else)
- Reopen in container

# Actual result

VSCode opens a new window and crashes with the following log:

```
[2022-08-24T07:42:38.912Z] Remote-Containers 0.245.2 in VS Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662).
[2022-08-24T07:42:38.912Z] Start: Resolving Remote
[2022-08-24T07:42:38.924Z] Setting up container for folder or workspace: /Users/kxkl558/git/definiens/reusable_apps/digipath-sdk
[2022-08-24T07:42:38.940Z] Start: Check Docker is running
[2022-08-24T07:42:38.941Z] Start: Run: /usr/local/bin/docker version --format {{.Server.APIVersion}}
[2022-08-24T07:42:39.013Z] Stop (72 ms): Run: /usr/local/bin/docker version --format {{.Server.APIVersion}}
[2022-08-24T07:42:39.013Z] Server API version: 1.41
[2022-08-24T07:42:39.013Z] Stop (73 ms): Check Docker is running
[2022-08-24T07:42:39.014Z] Start: Run: /usr/local/bin/docker volume ls -q
[2022-08-24T07:42:39.065Z] Stop (51 ms): Run: /usr/local/bin/docker volume ls -q
[2022-08-24T07:42:39.073Z] Start: Run: /usr/local/bin/docker ps -q -a --filter label=vsch.local.folder=/Users/kxkl558/git/definiens/reusable_apps/digipath-sdk --filter label=vsch.quality=stable
[2022-08-24T07:42:39.122Z] Stop (49 ms): Run: /usr/local/bin/docker ps -q -a --filter label=vsch.local.folder=/Users/kxkl558/git/definiens/reusable_apps/digipath-sdk --filter label=vsch.quality=stable
[2022-08-24T07:42:39.122Z] Start: Run: /usr/local/bin/docker ps -q -a --filter label=devcontainer.local_folder=/Users/kxkl558/git/definiens/reusable_apps/digipath-sdk
[2022-08-24T07:42:39.172Z] Stop (50 ms): Run: /usr/local/bin/docker ps -q -a --filter label=devcontainer.local_folder=/Users/kxkl558/git/definiens/reusable_apps/digipath-sdk
[2022-08-24T07:42:39.172Z] Start: Run: /usr/local/bin/docker inspect --type container 21e6c2522308
[2022-08-24T07:42:39.225Z] Stop (53 ms): Run: /usr/local/bin/docker inspect --type container 21e6c2522308
[2022-08-24T07:42:39.226Z] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/kxkl558/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/kxkl558/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --docker-path /usr/local/bin/docker --workspace-folder /Users/kxkl558/git/definiens/reusable_apps/digipath-sdk --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/kxkl558/git/definiens/reusable_apps/digipath-sdk --log-level debug --log-format json --config /Users/kxkl558/git/definiens/reusable_apps/digipath-sdk/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-08-24T07:42:39.322Z] remote-containers 0.245.2.
[2022-08-24T07:42:39.322Z] Start: Run: /usr/local/bin/docker buildx version
[2022-08-24T07:42:39.522Z] Stop (200 ms): Run: /usr/local/bin/docker buildx version
[2022-08-24T07:42:39.522Z] Start: Resolving Remote
[2022-08-24T07:42:39.524Z] Start: Run: git rev-parse --show-cdup
[2022-08-24T07:42:39.530Z] Stop (6 ms): Run: git rev-parse --show-cdup
[2022-08-24T07:42:39.531Z] Start: Run: /usr/local/bin/docker ps -q -a --filter label=devcontainer.local_folder=/Users/kxkl558/git/definiens/reusable_apps/digipath-sdk
[2022-08-24T07:42:39.589Z] Stop (58 ms): Run: /usr/local/bin/docker ps -q -a --filter label=devcontainer.local_folder=/Users/kxkl558/git/definiens/reusable_apps/digipath-sdk
[2022-08-24T07:42:39.589Z] Start: Run: /usr/local/bin/docker inspect --type container 21e6c2522308
[2022-08-24T07:42:39.646Z] Stop (57 ms): Run: /usr/local/bin/docker inspect --type container 21e6c2522308
[2022-08-24T07:42:39.647Z] Start: Starting container
[2022-08-24T07:42:39.647Z] Start: Run: /usr/local/bin/docker start 21e6c2522308cfe3d289410e717928c25cbe7938ff6aacfe9c2a35d33c1ec5bf
[2022-08-24T07:42:39.789Z] Stop (142 ms): Run: /usr/local/bin/docker start 21e6c2522308cfe3d289410e717928c25cbe7938ff6aacfe9c2a35d33c1ec5bf
[2022-08-24T07:42:39.790Z] Error: Command failed: /usr/local/bin/docker start 21e6c2522308cfe3d289410e717928c25cbe7938ff6aacfe9c2a35d33c1ec5bf
[2022-08-24T07:42:39.791Z]     at MS (/Users/kxkl558/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:255:2186)
[2022-08-24T07:42:39.791Z]     at Zw (/Users/kxkl558/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:255:2124)
[2022-08-24T07:42:39.791Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-08-24T07:42:39.791Z]     at async KS (/Users/kxkl558/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:261:2006)
[2022-08-24T07:42:39.791Z]     at async co (/Users/kxkl558/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:261:3110)
[2022-08-24T07:42:39.791Z]     at async LP (/Users/kxkl558/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:360:9352)
[2022-08-24T07:42:39.791Z]     at async DP (/Users/kxkl558/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:360:9108)
[2022-08-24T07:42:39.792Z] Stop (566 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/kxkl558/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/kxkl558/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --docker-path /usr/local/bin/docker --workspace-folder /Users/kxkl558/git/definiens/reusable_apps/digipath-sdk --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/kxkl558/git/definiens/reusable_apps/digipath-sdk --log-level debug --log-format json --config /Users/kxkl558/git/definiens/reusable_apps/digipath-sdk/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-08-24T07:42:39.792Z] Exit code 1
[2022-08-24T07:42:39.794Z] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/kxkl558/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/kxkl558/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --docker-path /usr/local/bin/docker --workspace-folder /Users/kxkl558/git/definiens/reusable_apps/digipath-sdk --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/kxkl558/git/definiens/reusable_apps/digipath-sdk --log-level debug --log-format json --config /Users/kxkl558/git/definiens/reusable_apps/digipath-sdk/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-08-24T07:42:39.794Z] Exit code 1
```

# System infos

## VSCode

```
Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:38:59.695Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.3.0
```

## Docker

installed via https://docs.docker.com/desktop/install/mac-install/

```
Docker version 20.10.17, build 100c701
```

# Notes during debugging

- attaching to an existing container works
- debian image also does not work
- an empty directory works
- the same repository cloned to a slightly different location works
- simply renaming the original directory works?

Hmm... is it possible that somehow an old docker build is wrongly cached? I also get the popup message "reconnect attempt without old result"

**Comment by chrmarti** [comment]
Does `F1` > `Remote-Containers: Rebuild and Reopen in Container` make it work? (This deletes the existing container and creates a new one.)

**Comment by abhishek0010** [comment]
I am having a similar issue on my Intel Mac and @chrmarti , your suggested step doesn't solve the issue.

**Comment by chrmarti** [comment]
Can you start the container from the terminal using `docker start <container id>`? Please append your devcontainer.json and Dockerfile (if you have one).

**Comment by cgebbe** [comment]
@chrmarti : Sorry, I don't have access to the laptop anymore, feel free to close this thread from my side.

**Comment by abhishek0010** [comment]
@chrmarti Sorry for the confusion, I was trying to bind my local directory to a remote docker host. 
Then I realised that the local directory is required to be mounted using nfs or its equivalent, for the remote host to pickup my local volume location. (Correct me if I am wrong here)
I thought that the remote bind mounting was handled by VS Code extension itself, which was incorrect.

**Comment by resried** [comment]
Hi
I had the same problem on windows, the error was always thrown inside the bootload-volume-container.
Somehow the .vscode-remote-containers in my AppData was not complete and thus the js File was never to be found.

In the end I deleted 
C:\Users\**<<USER>>**\AppData\Local\Temp\vsch\bootstrap-image\0.245.2
This solved the problem for me.
