### ISSUE TITLE
SSH cannot establish connection to remote server

### ISSUE THREAD

**Issue by haojie1588** [microsoft/vscode-remote-release#7139]
I'm using password to authenticate to my remote server, and I suddenly could not to connect to remote server without doing anything.
I have tried to remove ./vscode-server in remote server, but When re-downloading the .vscode-server and opening the file it doesn't work again.
- VSCode Version: 1.70
- Local OS Version: Windows 10 
- Remote OS Version: CentOS 8.4
- Remote Extension: SSH v0.84.0
- Logs:
```bash
[09:44:59.558] Log Level: 2
[09:44:59.564] remote-ssh@0.85.2022071315
[09:44:59.564] win32 x64
[09:44:59.583] SSH Resolver called for "ssh-remote+192.168.41.15", attempt 1
[09:44:59.583] "remote.SSH.useLocalServer": false
[09:44:59.583] "remote.SSH.showLoginTerminal": false
[09:44:59.583] "remote.SSH.remotePlatform": {"192.168.41.10":"linux","192.168.41.15":"linux","10.102.32.140":"linux","192.168.41.16":"linux"}
[09:44:59.584] "remote.SSH.path": C:\Windows\System32\OpenSSH\ssh.exe
[09:44:59.584] "remote.SSH.configFile": undefined
[09:44:59.584] "remote.SSH.useFlock": true
[09:44:59.584] "remote.SSH.lockfilesInTmp": false
[09:44:59.584] "remote.SSH.localServerDownload": auto
[09:44:59.584] "remote.SSH.remoteServerListenOnSocket": false
[09:44:59.584] "remote.SSH.showLoginTerminal": false
[09:44:59.584] "remote.SSH.defaultExtensions": []
[09:44:59.584] "remote.SSH.loglevel": 2
[09:44:59.584] "remote.SSH.enableDynamicForwarding": true
[09:44:59.585] "remote.SSH.enableRemoteCommand": false
[09:44:59.585] "remote.SSH.serverPickPortsFromRange": {}
[09:44:59.585] "remote.SSH.serverInstallPath": {}
[09:44:59.588] SSH Resolver called for host: 192.168.41.15
[09:44:59.588] Setting up SSH remote "192.168.41.15"
[09:44:59.596] Using commit id "e4503b30fc78200f846c62cf8091b76ff5547662" and quality "stable" for server
[09:44:59.599] Install and start server if needed
[09:44:59.601] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[09:44:59.640] > OpenSSH_for_Windows_8.1p1, Libre
[09:44:59.640] > SSL 3.0.2

[09:44:59.644] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 56057 "192.168.41.15" bash
[09:44:59.647] Terminal shell path: C:\Windows\System32\cmd.exe
[09:45:01.344] > haojie@192.168.41.15's password:
[09:45:01.344] Got some output, clearing connection timeout
[09:45:01.345] Showing password prompt
[09:45:04.234] Got password response
[09:45:04.234] "install" wrote data to terminal: "******"
[09:45:04.267] > 
> 
[09:45:04.422] > Unable to use a TTY - input is not a terminal or the right kind of file
> 
[09:45:04.840] "install" terminal command done
[09:45:04.840] Install terminal quit with output: Unable to use a TTY - input is not a terminal or the right kind of file
[09:45:04.840] Received install output: Unable to use a TTY - input is not a terminal or the right kind of file
[09:45:04.841] Failed to parse remote port from server output
[09:45:04.842] Resolver error: Error: 
	at Function.Create (c:\Users\haojie\.vscode\extensions\ms-vscode-remote.remote-ssh-0.85.2022071315\out\extension.js:1:588535)
	at Object.t.handleInstallOutput (c:\Users\haojie\.vscode\extensions\ms-vscode-remote.remote-ssh-0.85.2022071315\out\extension.js:1:587187)
	at Object.t.tryInstall (c:\Users\haojie\.vscode\extensions\ms-vscode-remote.remote-ssh-0.85.2022071315\out\extension.js:1:684336)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\haojie\.vscode\extensions\ms-vscode-remote.remote-ssh-0.85.2022071315\out\extension.js:1:647221
	at async Object.t.withShowDetailsEvent (c:\Users\haojie\.vscode\extensions\ms-vscode-remote.remote-ssh-0.85.2022071315\out\extension.js:1:650537)
	at async Object.t.resolve (c:\Users\haojie\.vscode\extensions\ms-vscode-remote.remote-ssh-0.85.2022071315\out\extension.js:1:648271)
	at async c:\Users\haojie\.vscode\extensions\ms-vscode-remote.remote-ssh-0.85.2022071315\out\extension.js:1:730993

[09:45:04.877] SSH Resolver called for "ssh-remote+192.168.41.15", attempt 2, (Reconnection)
[09:45:04.878] SSH Resolver called for host: 192.168.41.15
[09:45:04.878] Setting up SSH remote "192.168.41.15"
[09:45:04.883] Using commit id "e4503b30fc78200f846c62cf8091b76ff5547662" and quality "stable" for server
[09:45:04.885] Install and start server if needed
[09:45:04.888] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 56059 "192.168.41.15" bash
[09:45:04.890] Terminal shell path: C:\Windows\System32\cmd.exe
[09:45:05.176] > 
[09:45:05.177] Got some output, clearing connection timeout
[09:45:05.254] > haojie@192.168.41.15's password:
[09:45:05.254] Showing password prompt
[09:53:52.553] Password dialog canceled
[09:53:52.553] "install" terminal command canceled
[09:53:52.555] Resolver error: Error: Connecting was canceled
	at Function.Canceled (c:\Users\haojie\.vscode\extensions\ms-vscode-remote.remote-ssh-0.85.2022071315\out\extension.js:1:588731)
	at c:\Users\haojie\.vscode\extensions\ms-vscode-remote.remote-ssh-0.85.2022071315\out\extension.js:1:683650
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
[09:53:52.559] ------
```

**Comment by svetabeta** [comment]
same here, same error output. 
Worked like a charm before, then after VSC 1.70.2 update started to timeout and stopped connecting. 
Locally: macOS Monterey
Remote: Windows 10, official OpenSSH 
Tried killing remote vsc server, removing it manually, increasing timeout, disabling Use Local Server, changing port ....

**Comment by tanhakabir** [comment]
@svetabeta I'm not sure about what you're seeing. Could you share your logs as well?

@haojie1588 It looks like from your logs you cancelled connecting?
```
Password dialog canceled
[09:53:52.553] "install" terminal command canceled
```

**Comment by svetabeta** [comment]
Sure, sorry, [tanhakabir](https://github.com/tanhakabir)

Here:
[23:10:54.807] Log Level: 1
[23:10:54.808] remote-ssh@0.84.0
[23:10:54.808] darwin x64
[23:10:54.824] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a2231302e3139332e36332e3133222c2275736572223a227373696c696e61227d", attempt 1
[23:10:54.824] "remote.SSH.useLocalServer": false
[23:10:54.825] "remote.SSH.showLoginTerminal": false
[23:10:54.825] "remote.SSH.remotePlatform": {"seaVM":"windows"}
[23:10:54.825] "remote.SSH.path": undefined
[23:10:54.825] "remote.SSH.configFile": /Users/sveta/.ssh/config
[23:10:54.825] "remote.SSH.useFlock": true
[23:10:54.825] "remote.SSH.lockfilesInTmp": false
[23:10:54.825] "remote.SSH.localServerDownload": auto
[23:10:54.826] "remote.SSH.remoteServerListenOnSocket": false
[23:10:54.826] "remote.SSH.showLoginTerminal": false
[23:10:54.826] "remote.SSH.defaultExtensions": []
[23:10:54.826] "remote.SSH.loglevel": 1
[23:10:54.826] "remote.SSH.enableDynamicForwarding": true
[23:10:54.826] "remote.SSH.enableRemoteCommand": false
[23:10:54.826] "remote.SSH.serverPickPortsFromRange": {}
[23:10:54.826] "remote.SSH.serverInstallPath": {}
[23:10:54.829] SSH Resolver called for host: sveta@10.193.63.13
[23:10:54.829] Setting up SSH remote "10.193.63.13"
[23:10:54.832] Using commit id "e4503b30fc78200f846c62cf8091b76ff5547662" and quality "stable" for server
[23:10:54.835] Install and start server if needed

and then prompting for platform and pwd again and here we go again:

[23:15:09.114] PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin
[23:15:09.115] Checking ssh with "ssh -V"
[23:15:09.137] > OpenSSH_8.6p1, LibreSSL 3.3.6

[23:15:09.139] Using SSH config file "/Users/sveta/.ssh/config"
[23:15:09.139] Remote command length: 6167/8192 characters
[23:15:09.139] Running script with connection command: ssh -T -D 59765 -o ConnectTimeout=160 -F '/Users/sveta/.ssh/config' 'sveta@10.193.63.13' powershell
[23:15:11.469] "install" terminal received data: "
sveta@10.193.63.13's password: "
[23:15:11.470] Got some output, clearing connection timeout
[23:15:11.470] Showing password prompt
[23:15:18.799] Got password response
[23:15:18.799] "install" wrote data to terminal: "***********"
[23:15:18.815] "install" terminal received data: ""
[23:15:19.842] "install" terminal received data: "Windows PowerShell 

Copyright (C) Microsoft Corporation. All rights reserved.


"
[23:15:23.083] "install" terminal received data: "PS C:\Users\sveta> "
[23:15:23.336] "install" terminal command done
[23:15:23.337] Install terminal quit with output: PS C:\Users\sveta> 
[23:15:23.337] Received install output: PS C:\Users\ssilina> 
[23:15:23.337] Stopped parsing output early. Remaining text: PS C:\Users\sveta>
[23:15:23.337] Failed to parse remote port from server output
[23:15:23.338] Resolver error: Error: 
	at Function.Create (/Users/sveta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585222)
	at Object.t.handleInstallOutput (/Users/sveta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:583874)
	at Object.t.tryInstall (/Users/sveta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:681023)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/sveta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643908
	at async Object.t.withShowDetailsEvent (/Users/sveta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
	at async Object.t.resolve (/Users/sveta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644958)
	at async /Users/sveta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[23:15:23.340] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"1","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"0","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"UnparsableOutput","exitCodeLabel":""},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":268514,"timing.preSshTime":254316,"timing.scriptTime":14197}}
[23:15:23.344] ------


[23:15:23.354] ------


[23:15:23.354] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a2231302e3139332e36332e3133222c2275736572223a227373696c696e61227d", attempt 2, (Reconnection)
[23:15:23.355] SSH Resolver called for host: sveta@10.193.63.13
[23:15:23.355] Setting up SSH remote "10.193.63.13"
[23:15:23.356] Using commit id "e4503b30fc78200f846c62cf8091b76ff5547662" and quality "stable" for server
[23:15:23.360] Install and start server if needed
[23:15:36.319] getPlatformForHost was canceled
[23:15:36.320] Resolver error: Error: Connecting was canceled
	at Function.Canceled (/Users/sveta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585418)
	at /Users/sveta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643820
	at async Object.t.withShowDetailsEvent (/Users/sveta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
	at async Object.t.resolve (/Users/sveta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644958)
	at async /Users/sveta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[23:15:36.321] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"0","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Canceled","exitCodeLabel":""},"measures":{"resolveAttempts":2,"retries":1,"timing.totalResolveTime":12966}}
[23:15:36.321] ------


[23:15:36.333] ------

===== 
About " Connecting was canceled" - if I don't cancel, it just keep going and going prompting for password and throwing errors
while I can connect to the remote machine OK both from the bash terminal and Remote Desktop app.
Thanks lots, I very much appreciate your input. Really frustrating to code directly in VM :)

**Comment by roblourens** [comment]
Seems that our install script isn't running- `"remote.SSH.useLocalServer": true` might fix it for you, you can also test whether your remote will accept a piped script, like `echo "echo hello" | ssh -T yourhost`, does that work?
