### ISSUE TITLE
Repeated disconnects after upgrading to latest VSCode 

### ISSUE THREAD

**Issue by vishalovercome** [microsoft/vscode-remote-release#7153]
- VSCode Version: 1.71
- Local OS Version: Latest MacOS 
- Remote OS Version: Ubuntu 20.04/22.04
- Remote Extension/Connection Type: SSH/Containers
- Logs:

`[191590 ms] Start: Host: Reconnecting exec server
[191591 ms] Start: Run: ssh -F /Users/USER/.ssh/config remote-docker-dev /bin/sh
[191595 ms] Container server did not launch or terminated: unexpected end of parent stream
[191596 ms] Host server terminated (code: null, signal: SIGKILL).
[221811 ms] Host server: ssh: connect to host 10.66.54.124 port 22: Operation timed out
[221812 ms] Host server terminated (code: 255, signal: null).
[221813 ms] Error: Host server terminated (code: 255, signal: null).
    at /Users/USER/.vscode/extensions/ms-vscode-remote.remote-containers-0.252.0/dist/extension/extension.js:221:1086
    at jZ (/Users/USER/.vscode/extensions/ms-vscode-remote.remote-containers-0.252.0/dist/extension/extension.js:221:1024)
    at Object.reconnect (/Users/USER/.vscode/extensions/ms-vscode-remote.remote-containers-0.252.0/dist/extension/extension.js:220:471)
    at Object.e.cliHost.reconnect (/Users/USER/.vscode/extensions/ms-vscode-remote.remote-containers-0.252.0/dist/extension/extension.js:300:8493)
    at Object.resolve (/Users/USER/.vscode/extensions/ms-vscode-remote.remote-containers-0.252.0/dist/extension/extension.js:399:9163)
    at b.$resolveAuthority (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:21621)
[232681 ms] Start: Reconnection attempt 4
[232682 ms] Start: Host: Reconnecting exec server
[232682 ms] Start: Run: ssh -F /Users/USER/.ssh/config remote-docker-dev /bin/sh
[255954 ms] Start: Container: Reconnecting exec server
[255957 ms] Start: Run in Host: docker inspect --type container 55b82fbf95a19e63a734db61cfc5adfce992a5213a2151f006cf77c48a2ef68c
[255957 ms] Start: Run in Host: docker exec -i -u root 55b82fbf95a19e63a734db61cfc5adfce992a5213a2151f006cf77c48a2ef68c /bin/sh
[256275 ms] Host server: client_loop: send disconnect: Broken pipe
[256280 ms] Container server did not launch or terminated: stream ended with:9 but wanted:15349
[256287 ms] Error: stream ended with:9 but wanted:15349
    at l (/Users/USER/.vscode/extensions/ms-vscode-remote.remote-containers-0.252.0/dist/extension/extension.js:11:15852)
    at /Users/USER/.vscode/extensions/ms-vscode-remote.remote-containers-0.252.0/dist/extension/extension.js:11:16033
    at s (/Users/USER/.vscode/extensions/ms-vscode-remote.remote-containers-0.252.0/dist/extension/extension.js:16:5302)
    at Socket.<anonymous> (/Users/USER/.vscode/extensions/ms-vscode-remote.remote-containers-0.252.0/dist/extension/extension.js:16:5472)
    at Socket.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[256289 ms] Host server terminated (code: 255, signal: null).`

I also see this happen but I'm not sure if they're related:

`userEnvProbe is taking longer than 10 seconds. Avoid waiting for user input in your shell's startup scripts. Continuing.`

Steps to Reproduce:

1. Upgrade vscode to 1.71
2. Upgrade remote container extension to 0.252

Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by vishalovercome** [comment]
`  ERR No file system provider found for resource 'vscode-remote://dev-container%2B7b22686f737450617468223a222f686f6d652f7562756e74752f646174612d6f70732d31222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22686f7374223a227373683a2f2f646174612d6f70732d646576227d7d/workspaces/data-ops-1/.vscode': ENOPRO: No file system provider found for resource 'vscode-remote://dev-container%2B7b22686f737450617468223a222f686f6d652f7562756e74752f646174612d6f70732d31222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22686f7374223a227373683a2f2f646174612d6f70732d646576227d7d/workspaces/data-ops-1/.vscode'
    at h.withProvider (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:603:14023)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async h.exists (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:603:16618)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2312:7642
    at async Promise.all (index 0)
    at async T._initWorkspaceFolderSnippets (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2312:7807)
workbench.desktop.main.js:sourcemap:603   ERR Error: Reconnect attempt without old result.
	at Object.resolve (vscode-file://vscode-app/Users/USER/.vscode/extensions/ms-vscode-remote.remote-containers-0.252.0/dist/extension/extension.js:399:9004)
	at b.$resolveAuthority (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:21630)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
workbench.desktop.main.js:sourcemap:603   ERR Reconnect attempt without old result.: Error: Reconnect attempt without old result.
	at Object.resolve (/Users/USER/.vscode/extensions/ms-vscode-remote.remote-containers-0.252.0/dist/extension/extension.js:399:9004)
	at b.$resolveAuthority (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:21630)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by eitsupi** [comment]
Maybe related to #6936, #6961

**Comment by chrmarti** [comment]
`ERR No file system provider found for resource 'vscode-remote://dev-container` might indicate an issue with your VS Code installation. Could you try reinstalling? @aeschli Any idea when this would occur?

**Comment by vishalovercome** [comment]
I merely upgraded vscode and the extension. I don't understand why that should cause this to happen. Any how, I've created at least 4 issues by now about upgrades breaking our workflow. This extension has become a buggy mess in the last 6-9 months and is simply too unstable to be useful.

**Comment by pamelafox** [comment]
I am experiencing something similar when trying to start a devcontainer for https://github.com/pamelafox/picologging
It worked fine for a week, but stopped working a few days ago. 
It may be related to Docker changes I made outside of VS Code, so I'm going to reinstall Docker today as well. My VS Code is up to date, I think I'm on v0.251.0 of the extension.

Here's the error that appears in the editor window:

<img width="574" alt="Screen Shot 2022-10-01 at 11 22 49 AM" src="https://user-images.githubusercontent.com/297042/193423010-97dbe09a-37bc-4bbc-90cb-4640b1b602d6.png">

And here are the logs:

```
[76960 ms] Start: Run: docker events --format {{json .}} --filter event=start
[76962 ms] Start: Starting container
[76962 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/Users/pamelafox/picologging,target=/workspaces/picologging,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=/Users/pamelafox/picologging --entrypoint /bin/sh vsc-picologging-e6e3b4aeb16b912798c8a51326ac1692 -c echo Container started
Container started
[77468 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/pamelafox/picologging
[77525 ms] Start: Run: docker inspect --type container e14a2d13a487
[77577 ms] Start: Inspecting container
[77577 ms] Start: Run: docker inspect --type container e14a2d13a4873eb127a9ad1a732cbbfd697598e333d40546a9754a95f217e50b
[77629 ms] Start: Run in container: /bin/sh
[77632 ms] Start: Run in container: uname -m
[77687 ms] Shell server terminated (code: 126, signal: null)
[77687 ms] GetResourcePath: BaseFS of container e14a2d13a4873eb127a9ad1a732cbbfd697598e333d40546a9754a95f217e50b is unexpectedly nil
[77687 ms] Start: Run in container: cat /etc/passwd
[77687 ms] Stdin closed!
[77687 ms] Error: An error occurred setting up the container.
[77687 ms]     at SF (/Users/pamelafox/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js:257:2186)
[77688 ms]     at pb (/Users/pamelafox/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js:257:2124)
[77688 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[77688 ms]     at async DF (/Users/pamelafox/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js:263:2006)
[77688 ms]     at async to (/Users/pamelafox/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js:263:3110)
[77688 ms]     at async Ak (/Users/pamelafox/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js:383:8108)
[77688 ms]     at async Ok (/Users/pamelafox/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js:383:7864)
[77690 ms] Exit code 1
[77692 ms] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/pamelafox/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/pamelafox/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/pamelafox/picologging --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/pamelafox/picologging --log-level debug --log-format json --config /Users/pamelafox/picologging/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[77692 ms] Exit code 1
```

**Comment by pamelafox** [comment]
Update: Resetting Docker to factory defaults did resolve my issue. Perhaps the extension is not compatible with the Docker extensions (I had a few checked) or maybe there was something else amiss.

**Comment by chrmarti** [comment]
"GetResourcePath: BaseFS of container e14a2d13a4873eb127a9ad1a732cbbfd697598e333d40546a9754a95f217e50b is unexpectedly nil" indicates this is https://github.com/microsoft/vscode-remote-release/issues/7214. Continuing there.
