### ISSUE TITLE
remote-containers: EntryNotADirectory (FileSystemError) in git worktree

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode-remote-release#7185]
remote-containers: v0.251.0

vscode:
Version: 1.71.0 (user setup)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:36:10.600Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

Steps to Reproduce:

1. make a git worktree in `/home/user/project` (pointing to a clone elsewhere). 
2. NOTE: `/home/user/project/.git` is NOT a directory since it's a worktree.
3. wait... (i'm not even actively using the remote-container extension)

```
[2022-09-13 13:26:24.702] [renderer1] [error] [Extension Host] EntryNotADirectory (FileSystemError): Error: ENOTDIR: not a directory, stat '/home/user/project/.git/config'
	at Qt._handleError (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:29835)
	at Object.stat (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:28102)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Object.isFile (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-containers-0.251.0\dist\extension\extension.js:399:31774)
	at async r_ (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-containers-0.251.0\dist\extension\extension.js:206:312)
	at async SL (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-containers-0.251.0\dist\extension\extension.js:
```

**Comment by chrmarti** [comment]
Need to check for `EntryNotADirectory` when calling the extension API's `fs.stat`.

**Comment by chrmarti** [comment]
Fixed a while ago. (Error code changed to 'FileNotADirectory'.)
