### ISSUE TITLE
Can't install extensions on remote SSH sessions. Proxy not working.

### ISSUE THREAD

**Issue by tautomer** [microsoft/vscode-remote-release#7220]
- VSCode Version: 1.71.2
- Local OS Version: mac 12.5.1
- Remote OS Version: RHEL 7.9
- Remote Extension/Connection Type: SSH
- Logs:
   ```text
  [2022-09-21 15:32:32.565] [renderer3] [error] ["Invalid: Corrupt ZIP: end of central directory record signature not found","    at U.downloadExtension (/turquoise/users/username/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/server/node/server.main.js:137:105790)","    at async U.doRun (/turquoise/users/username/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/server/node/server.main.js:137:104722)"]
  [2022-09-21 15:32:32.587] [renderer3] [error] Corrupt ZIP: end of central directory record signature not found: Invalid: Corrupt ZIP: end of central directory record signature not found
      at U.downloadExtension (/turquoise/users/username/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/server/node/server.main.js:137:105790)
      at async U.doRun (/turquoise/users/username/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/server/node/server.main.js:137:104722)
  ```

Steps to Reproduce:

1. Update an outdated extension
2. Error message pops up

The problem looks similar to #231 or microsoft/vscode/issues/71610, but I already have proxies set on the remote OS. 
```shell
echo $http_proxy
http://proxyout.*.*:8080
```

I can directly download the extension package from CLI on the remote OS

```text
 wget https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/2022.8.1002431955/vspackage
--2022-09-21 15:23:34--  https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/2022.8.1002431955/vspackage
Resolving proxyout.*.* (proxyout.*.*)... 192.12.184.19
Connecting to proxyout.*.* (proxyout.*.*)|192.12.184.19|:8080... connected.
Proxy request sent, awaiting response... 200 OK
Length: 15397577 (15M) [application/vsix]
Saving to: ‘vspackage’

100%[====================================================================================================================================================================================================================>] 15,397,577  18.8MB/s   in 0.8s

2022-09-21 15:23:36 (18.8 MB/s) - ‘vspackage’ saved [15397577/15397577]
```

and then install the *.vsix manually, but installation from CLI fails. However, I can install all kinds of themes on the remote server through GUI. Weird...

Also, the local machine itself need go through exactly the same proxy, but there is no problem with installing extensions.

**Comment by chrmarti** [comment]
Does setting the proxy in the machine settings make it work? (There is a tab in the user settings for machine settings.)

**Comment by chrmarti** [comment]
I meant to say the "Remote" tab in the user settings editor:
<img width="954" alt="image" src="https://user-images.githubusercontent.com/9205389/207313137-bae6d4b6-b27a-44a7-95ca-908d57816972.png">

**Comment by tautomer** [comment]
> I meant to say the "Remote" tab in the user settings editor: <img alt="image" width="954" src="https://user-images.githubusercontent.com/9205389/207313137-bae6d4b6-b27a-44a7-95ca-908d57816972.png">

Oh, I have set the proxy there already, but it never worked. However, `remote.downloadExtensionsLocally` seems to solve the problem. I successfully updated my extensions on the remote just now.
