### ISSUE TITLE
ERROR: Version mismatch: .devcontainer/docker-compose.yml specifies version 3.8 but extension file docker-compose.devcontainer.build-1664135184311.yml uses version 1

### ISSUE THREAD

**Issue by leviplj** [microsoft/vscode-remote-release#7244]
- VSCode Version: 1.70.2-1660629410 (1.71 has the same problem)
- Local OS Version: Ubuntu 20.04.5 LTS
- Remote Extension/Connection Type: Containers
- Logs:
 ```
[2022-09-25T19:46:19.505Z] Remote-Containers 0.247.0 in VS Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662).
[2022-09-25T19:46:19.505Z] Start: Resolving Remote
[2022-09-25T19:46:19.516Z] Setting up container for folder or workspace: /home/leviplj/workspace/testapp
[2022-09-25T19:46:19.517Z] Host: unix:///run/user/1000/docker.sock
[2022-09-25T19:46:19.538Z] Start: Check Docker is running
[2022-09-25T19:46:19.539Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2022-09-25T19:46:19.594Z] Stop (55 ms): Run: docker version --format {{.Server.APIVersion}}
[2022-09-25T19:46:19.595Z] Server API version: 1.41
[2022-09-25T19:46:19.595Z] Stop (57 ms): Check Docker is running
[2022-09-25T19:46:19.595Z] Start: Run: docker volume ls -q
[2022-09-25T19:46:19.641Z] Stop (46 ms): Run: docker volume ls -q
[2022-09-25T19:46:19.650Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/leviplj/workspace/testapp --filter label=vsch.quality=stable
[2022-09-25T19:46:19.700Z] Stop (50 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/home/leviplj/workspace/testapp --filter label=vsch.quality=stable
[2022-09-25T19:46:19.701Z] Start: Run: /usr/share/code/code /home/levi_leal/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/levi_leal/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/leviplj/workspace/testapp --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/leviplj/workspace/testapp --log-level debug --log-format json --config /home/leviplj/workspace/testapp/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-09-25T19:46:19.915Z] remote-containers 0.247.0.
[2022-09-25T19:46:19.915Z] Start: Run: docker buildx version
[2022-09-25T19:46:20.000Z] Stop (85 ms): Run: docker buildx version
[2022-09-25T19:46:20.001Z] Start: Resolving Remote
[2022-09-25T19:46:20.005Z] Start: Run: docker-compose version --short
[2022-09-25T19:46:20.518Z] Stop (513 ms): Run: docker-compose version --short
[2022-09-25T19:46:20.519Z] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=testing_devcontainer --filter label=com.docker.compose.service=app
[2022-09-25T19:46:20.562Z] Stop (43 ms): Run: docker ps -q -a --filter label=com.docker.compose.project=testing_devcontainer --filter label=com.docker.compose.service=app
[2022-09-25T19:46:20.563Z] Start: Run: docker-compose -f /home/leviplj/workspace/testapp/.devcontainer/docker-compose.yml config
[2022-09-25T19:46:21.093Z] Stop (530 ms): Run: docker-compose -f /home/leviplj/workspace/testapp/.devcontainer/docker-compose.yml config
[2022-09-25T19:46:21.093Z] services:
  app:
    build:
      args:
        NODE_VERSION: '16'
        VARIANT: '3.10'
      context: /home/leviplj/workspace/testapp
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    network_mode: service:db
    volumes:
    - /home/leviplj/workspace/testapp:/workspace:cached
  db:
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:latest
    restart: unless-stopped
    volumes:
    - postgres-data:/var/lib/postgresql/data:rw
version: '3.8'
volumes:
  postgres-data: {}

[2022-09-25T19:46:21.100Z] Start: Run: docker -v
[2022-09-25T19:46:21.139Z] Stop (39 ms): Run: docker -v
[2022-09-25T19:46:21.139Z] Start: Run: docker events --format {{json .}} --filter event=start
[2022-09-25T19:46:21.144Z] PersistedPath=/home/levi_leal/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data, ContainerHasLabels=false
[2022-09-25T19:46:21.144Z] Start: Run: docker-compose -f /home/leviplj/workspace/testapp/.devcontainer/docker-compose.yml config
[2022-09-25T19:46:21.710Z] Stop (566 ms): Run: docker-compose -f /home/leviplj/workspace/testapp/.devcontainer/docker-compose.yml config
[2022-09-25T19:46:21.710Z] services:
  app:
    build:
      args:
        NODE_VERSION: '16'
        VARIANT: '3.10'
      context: /home/leviplj/workspace/testapp
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    network_mode: service:db
    volumes:
    - /home/leviplj/workspace/testapp:/workspace:cached
  db:
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:latest
    restart: unless-stopped
    volumes:
    - postgres-data:/var/lib/postgresql/data:rw
version: '3.8'
volumes:
  postgres-data: {}

[2022-09-25T19:46:21.715Z] local container features stored at: /home/levi_leal/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/node_modules/vscode-dev-containers/container-features
[2022-09-25T19:46:21.717Z] Start: Run: tar --no-same-owner -x -f -
[2022-09-25T19:46:21.748Z] Stop (31 ms): Run: tar --no-same-owner -x -f -
[2022-09-25T19:46:21.757Z] * Processing feature: aws-cli
[2022-09-25T19:46:22.876Z] * Fetching feature: aws-cli_1_oci
[2022-09-25T19:46:23.871Z] Start: Run: docker build -t dev_container_feature_content_temp -f /tmp/vsch-levi_leal/container-features/0.247.0-1664135181714/Dockerfile.buildContent /tmp/vsch-levi_leal/container-features/0.247.0-1664135181714
[2022-09-25T19:46:23.954Z] Sending build context to Docker daemon  319.5kB

[2022-09-25T19:46:23.958Z] Step 1/2 : FROM scratch
 ---> 
[2022-09-25T19:46:23.958Z] Step 2/2 : COPY . /tmp/build-features/
[2022-09-25T19:46:24.302Z]  ---> 27734e1e97bb
[2022-09-25T19:46:24.302Z] Successfully built 27734e1e97bb
[2022-09-25T19:46:24.307Z] Successfully tagged dev_container_feature_content_temp:latest
[2022-09-25T19:46:24.310Z] Stop (439 ms): Run: docker build -t dev_container_feature_content_temp -f /tmp/vsch-levi_leal/container-features/0.247.0-1664135181714/Dockerfile.buildContent /tmp/vsch-levi_leal/container-features/0.247.0-1664135181714
[2022-09-25T19:46:24.312Z] Start: Run: docker-compose --project-name testing_devcontainer -f /home/leviplj/workspace/testapp/.devcontainer/docker-compose.yml -f /home/levi_leal/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1664135184311.yml build
[2022-09-25T19:46:24.766Z] ERROR: Version mismatch: file /home/leviplj/workspace/testapp/.devcontainer/docker-compose.yml specifies version 3.8 but extension file /home/levi_leal/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1664135184311.yml uses version 1
[2022-09-25T19:46:24.827Z] Stop (515 ms): Run: docker-compose --project-name testing_devcontainer -f /home/leviplj/workspace/testapp/.devcontainer/docker-compose.yml -f /home/levi_leal/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1664135184311.yml build
[2022-09-25T19:46:24.828Z] Error: Command failed: docker-compose --project-name testing_devcontainer -f /home/leviplj/workspace/testapp/.devcontainer/docker-compose.yml -f /home/levi_leal/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1664135184311.yml build
[2022-09-25T19:46:24.828Z]     at mu (/home/levi_leal/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/spec-node/devContainersSpecCLI.js:219:419)
[2022-09-25T19:46:24.829Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-09-25T19:46:24.829Z]     at async kS (/home/levi_leal/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/spec-node/devContainersSpecCLI.js:219:2358)
[2022-09-25T19:46:24.829Z]     at async OS (/home/levi_leal/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/spec-node/devContainersSpecCLI.js:203:2361)
[2022-09-25T19:46:24.829Z]     at async JS (/home/levi_leal/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/spec-node/devContainersSpecCLI.js:260:2177)
[2022-09-25T19:46:24.829Z]     at async co (/home/levi_leal/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/spec-node/devContainersSpecCLI.js:260:3110)
[2022-09-25T19:46:24.830Z]     at async TP (/home/levi_leal/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/spec-node/devContainersSpecCLI.js:359:9519)
[2022-09-25T19:46:24.830Z]     at async LP (/home/levi_leal/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/spec-node/devContainersSpecCLI.js:359:9275)
[2022-09-25T19:46:24.837Z] Stop (5136 ms): Run: /usr/share/code/code /home/levi_leal/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/levi_leal/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/leviplj/workspace/testapp --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/leviplj/workspace/testapp --log-level debug --log-format json --config /home/leviplj/workspace/testapp/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-09-25T19:46:24.837Z] Exit code 1
[2022-09-25T19:46:24.842Z] Command failed: /usr/share/code/code /home/levi_leal/.vscode/extensions/ms-vscode-remote.remote-containers-0.247.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/levi_leal/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/leviplj/workspace/testapp --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/leviplj/workspace/testapp --log-level debug --log-format json --config /home/leviplj/workspace/testapp/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-09-25T19:46:24.842Z] Exit code 1
```

Steps to Reproduce:

1. create any folder and `cd` into it
2. run `npm init -y`
3. Ctrl+Shift+P -> Remote-Containers: Rebuild and Reopen in Container -> Python 3 & PostgreSQL -> [Python Version:] 3-bulleye -> [Node Version:] lts -> Select at least one feature [AWS CLI] -> OK

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

Note: It doesn't happen on codespaces

**Comment by chrmarti** [comment]
`docker-compose.devcontainer.build-1664135184311.yml` is missing the version. What do you get for `docker-compose version`? (Later versions seem to have stopped complaining when the version is missing in one of the override files.)

**Comment by blieusong** [comment]
Same here.

```
> docker-compose version
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Comment by blieusong** [comment]
Hi,

Juste to mention that, as you suggested, installing a more recent docker-compose fixed the issue for me.

Thanks.

**Comment by aaronduignan** [comment]
@blieusong  What version of docker compose are you using?

I am using the latest version and I am still getting this issue
``` 
$ docker compose version
Docker Compose version v2.10.2

**Comment by aaronduignan** [comment]
thank you @blieusong. I had to manually download 2.11.2. It is working for me now.

**Comment by leviplj** [comment]
Using the latest docker-compose version fixed the problem. I also had to manually download it. Now I'm currently using v2.11.2.

**Comment by chrmarti** [comment]
Reopening to fix in code.
