### ISSUE TITLE
webviewServer error in remote server log

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#725]
- Connect to an ssh remote
- `cat ~/.vscode-server-insiders/.7f53e50cbf316dff94fbbe5406d8f352dac99a6b.log` or whatever commit
- An error always shows up, doesn't seem to be causing an issue though

```
Error occurred in webviewServer
{ Error: listen EACCES 0.0.0.0:1
    at Server.setupListenHandle [as _listen2] (net.js:1269:19)
    at listenInCluster (net.js:1334:12)
    at Server.listen (net.js:1421:7)
    at O.<anonymous> (/home/roblou/.vscode-server-insiders/bin/7f53e50cbf316dff94fbbe5406d8f352dac99a6b/out/vs/server/remoteExtensionHostAgent.js:380:863)
    at Generator.next (<anonymous>)
    at o (/home/roblou/.vscode-server-insiders/bin/7f53e50cbf316dff94fbbe5406d8f352dac99a6b/out/vs/server/remoteExtensionHostAgent.js:16:221)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 1 }
```

**Comment by mjbvz** [comment]
This should be fixed. We were not treating `0` as the random port and instead thinking that the server was literally running on port `0` (so we'd select port `1` for the webview server)
