### ISSUE TITLE
Unable to Install Python extension in VS code for WSL

### ISSUE THREAD

**Issue by codeastra2** [microsoft/vscode-remote-release#7265]
- VSCode Version:
Visual Studio Code (1.71.2, wsl, desktop)

- Local OS Version:
Windows 11 OS build 22621.601
 Ubuntu 20.04.5 LTS

- Remote OS Version:
5.4.72-microsoft-standard-WSL2

- Remote Extension/Connection Type: WSL

- Logs:

```
Visual Studio Code (1.71.2, wsl, desktop)
Jupyter Extension Version: 2022.8.1002431955.
Python Extension not installed.
Workspace folder /home/codeastra/notebooks
info 10:45:23.466: ZMQ install verified.
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 10:45:24.78: LSP Notebooks experiment is disabled -- not using Pylance
info 10:45:24.173: Preferred Remote kernel for /home/codeastra/notebooks/test.ipynb is undefined
info 10:45:24.173: Find preferred kernel for /home/codeastra/notebooks/test.ipynb with metadata {"orig_nbformat":4,"language_info":{"name":"python"}} & preferred interpreter 
info 10:45:24.188: Preferred Remote kernel for /home/codeastra/notebooks/test.ipynb is undefined
info 10:45:24.188: Find preferred kernel for /home/codeastra/notebooks/test.ipynb with metadata {"orig_nbformat":4,"language_info":{"name":"python"}} & preferred interpreter 
info 10:45:24.192: Preferred Remote kernel for /home/codeastra/notebooks/test.ipynb is undefined
info 10:45:28.991: Preferred Remote kernel for /home/codeastra/notebooks/test.ipynb is undefined
info 10:45:29.49: Preferred Remote kernel for /home/codeastra/notebooks/test.ipynb is undefined
info 10:45:29.49: Find preferred kernel for /home/codeastra/notebooks/test.ipynb with metadata {"orig_nbformat":4,"language_info":{"name":"python"}} & preferred interpreter 
info 10:45:29.67: Preferred Remote kernel for /home/codeastra/notebooks/test.ipynb is undefined
info 10:45:29.67: Find preferred kernel for /home/codeastra/notebooks/test.ipynb with metadata {"orig_nbformat":4,"language_info":{"name":"python"}} & preferred interpreter 
info 11:8:42.623: Preferred Remote kernel for /home/codeastra/notebooks/test.ipynb is undefined
info 11:8:42.679: Preferred Remote kernel for /home/codeastra/notebooks/test.ipynb is undefined
info 11:8:42.679: Find preferred kernel for /home/codeastra/notebooks/test.ipynb with metadata {"orig_nbformat":4,"language_info":{"name":"python"}} & preferred interpreter 
info 11:8:42.709: Preferred Remote kernel for /home/codeastra/notebooks/test.ipynb is undefined
info 11:8:42.709: Find preferred kernel for /home/codeastra/notebooks/test.ipynb with metadata {"orig_nbformat":4,"language_info":{"name":"python"}} & preferred interpreter 
error 11:9:50.248: Failed to install Python Extension via Kernel Picker command
warn 11:9:50.262: DataScience Error [Error: Failed to install the Python Extension.
	at _.installPythonExtensionViaKernelPicker (/home/codeastra/.vscode-server/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:2:2407793)
	at async c._executeContributedCommand (/home/codeastra/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:85:63762)]
info 11:10:43.66: Loading webview. View is notset
info 11:10:43.73: Loading web view...
info 11:10:43.76: Webview panel created.
info 11:10:43.433: Web view react rendered
error 11:11:17.370: Failed to install Python Extension via Kernel Picker command
warn 11:11:17.371: DataScience Error [Error: Failed to install the Python Extension.
	at _.installPythonExtensionViaKernelPicker (/home/codeastra/.vscode-server/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:2:2407793)
	at async c._executeContributedCommand (/home/codeastra/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:85:63762)]
info 11:16:27.335: Preferred Remote kernel for /home/codeastra/notebooks/Untitled.ipynb is undefined
info 11:16:27.413: Preferred Remote kernel for /home/codeastra/notebooks/Untitled.ipynb is undefined
info 11:16:27.413: Find preferred kernel for /home/codeastra/notebooks/Untitled.ipynb with metadata {"kernelspec":{"display_name":"Python_venv394_kernel","language":"python","name":"venv394"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.4"}} & preferred interpreter 
info 11:16:27.481: Preferred Remote kernel for /home/codeastra/notebooks/Untitled.ipynb is undefined
info 11:16:27.481: Find preferred kernel for /home/codeastra/notebooks/Untitled.ipynb with metadata {"kernelspec":{"display_name":"Python_venv394_kernel","language":"python","name":"venv394"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.4"}} & preferred interpreter 
info 11:17:14.95: Creating server with url : http://127.0.0.1:8888/
warn 11:17:14.284: Uri verification error [FetchError: request to http://127.0.0.1:8888/api/kernels?1664443034266 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
	at ClientRequest.<anonymous> (/home/codeastra/.vscode-server/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:17:520420)
	at ClientRequest.emit (node:events:526:28)
	at Socket.socketErrorListener (node:_http_client:442:9)
	at Socket.emit (node:events:526:28)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)]
error 11:17:14.295: SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (/home/codeastra/.vscode-server/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/node_modules/@jupyterlab/services.js:2:156575)
	at m.dispose (/home/codeastra/.vscode-server/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/node_modules/@jupyterlab/services.js:2:48238)
	at u.dispose (/home/codeastra/.vscode-server/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:2:2228833)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)]
info 11:17:15.532: Creating server with url : http://127.0.0.1:8888/
warn 11:17:15.540: Uri verification error [FetchError: request to http://127.0.0.1:8888/api/kernels?1664443035534 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
	at ClientRequest.<anonymous> (/home/codeastra/.vscode-server/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:17:520420)
	at ClientRequest.emit (node:events:526:28)
	at Socket.socketErrorListener (node:_http_client:442:9)
	at Socket.emit (node:events:526:28)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)]
error 11:17:15.543: SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (/home/codeastra/.vscode-server/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/node_modules/@jupyterlab/services.js:2:156575)
	at m.dispose (/home/codeastra/.vscode-server/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/node_modules/@jupyterlab/services.js:2:48238)
	at u.dispose (/home/codeastra/.vscode-server/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:2:2228833)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)]
info 11:18:2.701: Creating server with url : http://127.0.0.1:8888/
warn 11:18:2.711: Uri verification error [FetchError: request to http://127.0.0.1:8888/api/kernels?1664443082703 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
	at ClientRequest.<anonymous> (/home/codeastra/.vscode-server/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:17:520420)
	at ClientRequest.emit (node:events:526:28)
	at Socket.socketErrorListener (node:_http_client:442:9)
	at Socket.emit (node:events:526:28)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)]
error 11:18:2.712: SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (/home/codeastra/.vscode-server/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/node_modules/@jupyterlab/services.js:2:156575)
	at m.dispose (/home/codeastra/.vscode-server/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/node_modules/@jupyterlab/services.js:2:48238)
	at u.dispose (/home/codeastra/.vscode-server/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:2:2228833)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)]
error 11:22:49.770: Failed to install Python Extension via Kernel Picker command
warn 11:22:49.773: DataScience Error [Error: Failed to install the Python Extension.
	at _.installPythonExtensionViaKernelPicker (/home/codeastra/.vscode-server/extensions/ms-toolsai.jupyter-2022.8.1002431955/out/extension.node.js:2:2407793)
	at async c._executeContributedCommand (/home/codeastra/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:85:63762)]
```

Steps to Reproduce:

1.Try to install python extension for jupyter notebook in vs code  wsl. 
<img width="894" alt="image" src="https://user-images.githubusercontent.com/16428095/192996055-502ee839-7130-4b59-b395-b331c49cc6d6.png">

2. It fails with the above error trace.

**Comment by codeastra2** [comment]
I had to restart  the ubuntu distro and also vs cod in order to solve this issue.
