### ISSUE TITLE
Enabling `containerd` experimental feature in Docker Desktop causes Devcontainers to stop working

### ISSUE THREAD

**Issue by GavinRay97** [microsoft/vscode-remote-release#7283]
Reporting this so that others getting the spurious `Shell server terminated (code: 126, signal: null)` error can have something to find on Google

- VSCode Version: 1.72.0-insider
- Local OS Version: Windows 11
- Remote OS Version: N/A
- Remote Extension/Connection Type: Containers
- Logs:

```ps1
[2022-10-04T00:06:21.903Z] Stop (908 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\rayga\AppData\Local\Temp\devcontainercli\container-features\0.17.0-1664841980963\Dockerfile-with-features -t vsc-bustub-java-e47ee9a63d7d15e9c67bad02fdf00f21 --target dev_containers_target_stage --build-arg VARIANT=ubuntu-22.04 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label c:\Users\rayga\WindowsProjects\bustub-java\.devcontainer
[2022-10-04T00:06:21.905Z] Start: Run: docker events --format {{json .}} --filter event=start
[2022-10-04T00:06:21.922Z] Start: Starting container
[2022-10-04T00:06:21.922Z] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=c:\Users\rayga\WindowsProjects\bustub-java,target=/workspaces/bustub-java,consistency=cached --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=c:\Users\rayga\WindowsProjects\bustub-java --entrypoint /bin/sh vsc-bustub-java-e47ee9a63d7d15e9c67bad02fdf00f21 -c echo Container started
[2022-10-04T00:06:22.015Z] 
[2022-10-04T00:06:22.508Z] Container started
[2022-10-04T00:06:22.511Z] Stop (589 ms): Starting container
[2022-10-04T00:06:22.511Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\rayga\WindowsProjects\bustub-java
[2022-10-04T00:06:22.515Z] Stop (610 ms): Run: docker events --format {{json .}} --filter event=start
[2022-10-04T00:06:22.651Z] Stop (140 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\rayga\WindowsProjects\bustub-java
[2022-10-04T00:06:22.651Z] Start: Run: docker inspect --type container c0d37a1ff7ae
[2022-10-04T00:06:22.772Z] Stop (121 ms): Run: docker inspect --type container c0d37a1ff7ae
[2022-10-04T00:06:22.772Z] Start: Inspecting container
[2022-10-04T00:06:22.772Z] Start: Run: docker inspect --type container c0d37a1ff7aef93f6ff410f302519a77c1140bed0b1e59e7c748b476acf5a536
[2022-10-04T00:06:22.896Z] Stop (124 ms): Run: docker inspect --type container c0d37a1ff7aef93f6ff410f302519a77c1140bed0b1e59e7c748b476acf5a536
[2022-10-04T00:06:22.896Z] Stop (124 ms): Inspecting container
[2022-10-04T00:06:22.897Z] Start: Run in container: /bin/sh
[2022-10-04T00:06:22.914Z] Start: Run in container: uname -m
[2022-10-04T00:06:23.019Z] Stop (122 ms): Run in container: /bin/sh
[2022-10-04T00:06:23.019Z] Shell server terminated (code: 126, signal: null)
[2022-10-04T00:06:23.019Z] GetResourcePath: BaseFS of container c0d37a1ff7aef93f6ff410f302519a77c1140bed0b1e59e7c748b476acf5a536 is unexpectedly nil

[2022-10-04T00:06:23.020Z] Start: Run in container: cat /etc/passwd
[2022-10-04T00:06:23.020Z] Stdin closed!
[2022-10-04T00:06:23.021Z] Error: An error occurred setting up the container.
[2022-10-04T00:06:23.021Z]     at ok (c:\Users\rayga\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.255.0\dist\spec-node\devContainersSpecCLI.js:294:1323)
[2022-10-04T00:06:23.021Z]     at M0 (c:\Users\rayga\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.255.0\dist\spec-node\devContainersSpecCLI.js:294:1261)
[2022-10-04T00:06:23.021Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-10-04T00:06:23.021Z]     at async mk (c:\Users\rayga\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.255.0\dist\spec-node\devContainersSpecCLI.js:300:2014)
[2022-10-04T00:06:23.021Z]     at async ms (c:\Users\rayga\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.255.0\dist\spec-node\devContainersSpecCLI.js:300:3166)
[2022-10-04T00:06:23.021Z]     at async lD (c:\Users\rayga\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.255.0\dist\spec-node\devContainersSpecCLI.js:420:8396)
[2022-10-04T00:06:23.021Z]     at async cD (c:\Users\rayga\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.255.0\dist\spec-node\devContainersSpecCLI.js:420:8152)
[2022-10-04T00:06:23.029Z] Stop (2673 ms): Run: C:\Users\rayga\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe --ms-enable-electron-run-as-node c:\Users\rayga\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.255.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\rayga\AppData\Roaming\Code - Insiders\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder c:\Users\rayga\WindowsProjects\bustub-java --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\rayga\WindowsProjects\bustub-java --log-level debug --log-format json --config c:\Users\rayga\WindowsProjects\bustub-java\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-10-04T00:06:23.030Z] Exit code 1
[2022-10-04T00:06:23.032Z] Command failed: C:\Users\rayga\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe --ms-enable-electron-run-as-node c:\Users\rayga\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.255.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\rayga\AppData\Roaming\Code - Insiders\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder c:\Users\rayga\WindowsProjects\bustub-java --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\rayga\WindowsProjects\bustub-java --log-level debug --log-format json --config c:\Users\rayga\WindowsProjects\bustub-java\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-10-04T00:06:23.033Z] Exit code 1
```

Steps to Reproduce:

1. Create any Devcontainer definition
2. Enable the below setting in Docker Desktop

![image](https://user-images.githubusercontent.com/26604994/193707450-0c9c803a-9864-41b7-81bd-554d05d9c8cc.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Tracking as https://github.com/microsoft/vscode-remote-release/issues/7214. Thanks.
