### ISSUE TITLE
vscode tries to use `target` on docker-compose syntax versions prior to 3.4

### ISSUE THREAD

**Issue by kyrofa** [microsoft/vscode-remote-release#7301]
- VSCode Version: 1.71.2
- Local OS Version: Ubuntu 18.04 (Bionic)
- Remote OS Version: Ubuntu 20.04 (Focal)
- Remote Extension/Connection Type: docker-compose
- Logs:
- 
```
<snip...>
[2022-10-06T18:32:33.500Z] Docker Compose override file for building image:
version: '3.2'

services:
  dev:
    image: vsc-project-c7c13266ed09e325da5dc5a63e0cf8df
    build:
      dockerfile: /tmp/devcontainercli-kyrofa/container-features/0.19.0-1665081153307/Dockerfile-with-features
      target: dev_containers_target_stage
      context: /home/kyrofa/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
      args:
        - _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label
        - _DEV_CONTAINERS_IMAGE_USER=root
        - _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp

[2022-10-06T18:32:33.501Z] Start: Run: docker-compose --project-name if2engine -f /home/kyrofa/project/docker-compose.yml -f /home/kyrofa/project/docker-compose.override.yml -f /home/kyrofa/project/.devcontainer/docker-compose.yml -f /home/kyrofa/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1665081153500.yml build dev
[2022-10-06T18:32:33.765Z] ERROR: The Compose file '/home/kyrofa/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1665081153500.yml' is invalid because:
services.dev.build contains unsupported option: 'target'
[2022-10-06T18:32:33.785Z] Stop (284 ms): Run: docker-compose --project-name if2engine -f /home/kyrofa/project/docker-compose.yml -f /home/kyrofa/project/docker-compose.override.yml -f /home/kyrofa/project/.devcontainer/docker-compose.yml -f /home/kyrofa/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1665081153500.yml build dev
[2022-10-06T18:32:33.786Z] Error: Command failed: docker-compose --project-name if2engine -f /home/kyrofa/project/docker-compose.yml -f /home/kyrofa/project/docker-compose.override.yml -f /home/kyrofa/project/.devcontainer/docker-compose.yml -f /home/kyrofa/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1665081153500.yml build dev
[2022-10-06T18:32:33.786Z]     at pd (/home/kyrofa/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.2/dist/spec-node/devContainersSpecCLI.js:259:426)
[2022-10-06T18:32:33.786Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-10-06T18:32:33.786Z]     at async ZF (/home/kyrofa/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.2/dist/spec-node/devContainersSpecCLI.js:259:2424)
[2022-10-06T18:32:33.786Z]     at async XF (/home/kyrofa/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.2/dist/spec-node/devContainersSpecCLI.js:241:2391)
[2022-10-06T18:32:33.786Z]     at async bD (/home/kyrofa/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.2/dist/spec-node/devContainersSpecCLI.js:303:2193)
[2022-10-06T18:32:33.786Z]     at async ys (/home/kyrofa/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.2/dist/spec-node/devContainersSpecCLI.js:303:3182)
[2022-10-06T18:32:33.786Z]     at async UL (/home/kyrofa/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.2/dist/spec-node/devContainersSpecCLI.js:423:10319)
[2022-10-06T18:32:33.786Z]     at async ML (/home/kyrofa/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.2/dist/spec-node/devContainersSpecCLI.js:423:10075)
[2022-10-06T18:32:33.789Z] Stop (1509 ms): Run: /snap/code/108/usr/share/code/code --ms-enable-electron-run-as-node /home/kyrofa/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.2/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/kyrofa/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/kyrofa/project --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/kyrofa/project --log-level debug --log-format json --config /home/kyrofa/project/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-10-06T18:32:33.789Z] Exit code 1
[2022-10-06T18:32:33.790Z] Command failed: /snap/code/108/usr/share/code/code --ms-enable-electron-run-as-node /home/kyrofa/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.2/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/kyrofa/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/kyrofa/project --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/kyrofa/project --log-level debug --log-format json --config /home/kyrofa/project/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-10-06T18:32:33.790Z] Exit code 1
```

Steps to Reproduce:

1. Open a project uses a docker-compose syntax version prior to 3.4 (mine is v3.2)
2. Click "reopen in container"

This is #6568 all over again. Please check syntax versions before trying to do this stuff! I don't want to bump syntax versions in my projects unless it's for something I need. Not because my chosen tooling requires it of me.

**Comment by kyrofa** [comment]
@chrmarti helped resolve this last time around.

**Comment by chrmarti** [comment]
Dev Containers 0.258.0-pre-release comes with a fix. Could you give that a try and let me know if it fixes it? Thanks.

**Comment by chrmarti** [comment]
Fix is now also available in Dev Containers 0.255.3.
