### ISSUE TITLE
The VS Code GUI editor can not open certain folders on the remote SSH server 

### ISSUE THREAD

**Issue by ocimer** [microsoft/vscode-remote-release#7327]
After the latest update the VS Code client cannot open certain remote folders on the SSH server - VS Code server. Previously the __open folder__ has worked flawlessly for all folders on my remote SSH server. My remote settings are correct (SSH config, ... ) and there definitely is an internet connection. As said, **some folders can be opened and some cannot** (Both, the folder that opens and the one that does not have folder `.git`). I have tested to open a "fresh" folder without `.vscode` and with `.vscode` and both get stuck at :

`INFO [attempt 1] Invoking resolveAuthority(ssh-remote)`

- **Issue persist after killing the remote server**
- **The folder that can not be opened can be opened as in the workspace context but not individually.**

Some folders can be opened and some can not be opened. It prompts a connection error with following in the terminal:

## On VS Code terminal 
```Bash
[09:40:42.750] Log Level: 2
[09:40:42.753] remote-ssh@0.84.0
[09:40:42.753] win32 x64
[09:40:42.780] SSH Resolver called for "ssh-remote+desktop-work", attempt 1
[09:40:42.781] "remote.SSH.useLocalServer": false
[09:40:42.781] "remote.SSH.showLoginTerminal": false
[09:40:42.781] "remote.SSH.remotePlatform": {"desktop-work":"linux","raspi":"linux"}
[09:40:42.782] "remote.SSH.path": undefined
[09:40:42.782] "remote.SSH.configFile": undefined
[09:40:42.782] "remote.SSH.useFlock": true
[09:40:42.782] "remote.SSH.lockfilesInTmp": false
[09:40:42.782] "remote.SSH.localServerDownload": auto
[09:40:42.782] "remote.SSH.remoteServerListenOnSocket": false
[09:40:42.782] "remote.SSH.showLoginTerminal": false
[09:40:42.783] "remote.SSH.defaultExtensions": []
[09:40:42.783] "remote.SSH.loglevel": 2
[09:40:42.783] "remote.SSH.enableDynamicForwarding": true
[09:40:42.783] "remote.SSH.enableRemoteCommand": false
[09:40:42.783] "remote.SSH.serverPickPortsFromRange": {}
[09:40:42.783] "remote.SSH.serverInstallPath": {}
[09:40:42.808] SSH Resolver called for host: desktop-work
[09:40:42.808] Setting up SSH remote "desktop-work"
[09:40:42.845] Using commit id "64bbfbf67ada9953918d72e1df2f4d8e537d340e" and quality "stable" for server
[09:40:42.852] Install and start server if needed
[09:40:42.859] Checking ssh with "ssh -V"
[09:40:42.916] > OpenSSH_for_Windows_8
[09:40:42.917] > .1p1, LibreSSL 3.0.2

[09:40:42.924] Running script with connection command: ssh -T -D 59720 "desktop-work" bash
[09:40:42.926] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[09:40:59.936] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (c:\Users\<user>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:585348)
	at Timeout._onTimeout (c:\Users\<user>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:679743)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[09:40:59.944] ------
```

## VSCODE GUI client dev tools
```Bash
 INFO [attempt 1] Invoking resolveAuthority(ssh-remote)
  ERR [attempt 1] resolveAuthority(ssh-remote) returned an error after 17240 ms CodeExpectedError: Connecting with SSH timed out
    at I._resolveAuthority (electronExtensionService.ts:387:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async I._resolveAuthorityInitial (electronExtensionService.ts:423:28)
    at async I._scanAndHandleExtensions (electronExtensionService.ts:503:22)
    at async I._initialize (abstractExtensionService.ts:759:4)
The customer named _initialize has been holding on to the lock for 30s. This might be a problem.
```

## client exthost.json 
```Bash
[2022-10-11 09:30:56.055] [exthost] [info] Extension host with pid 10840 started
[2022-10-11 09:30:56.055] [exthost] [info] Skipping acquiring lock for c:\Users\<user>\AppData\Roaming\Code\User\workspaceStorage\2533f32aa3ed41a87d03370f3c32e993.
[2022-10-11 09:30:56.086] [exthost] [info] $getCanonicalURI invoked for authority (ssh-remote)
[2022-10-11 09:30:56.095] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-ssh, startup: false, activationEvent: 'onResolveRemoteAuthority:ssh-remote'
[2022-10-11 09:30:56.171] [exthost] [info] $resolveAuthority invoked for authority (ssh-remote)
[2022-10-11 09:31:00.880] [exthost] [info] ExtensionService#_doActivateExtension formulahendry.auto-rename-tag, startup: true, activationEvent: '*'
[2022-10-11 09:31:00.880] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
[2022-10-11 09:31:02.209] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
[2022-10-11 09:31:02.494] [exthost] [info] Eager extensions activated
[2022-10-11 09:31:02.499] [exthost] [info] ExtensionService#_doActivateExtension dsznajder.es7-react-js-snippets, startup: false, activationEvent: 'onStartupFinished'
[2022-10-11 09:31:02.499] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers, startup: false, activationEvent: 'onStartupFinished'
[2022-10-11 09:31:02.500] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl, startup: false, activationEvent: 'onStartupFinished'
[2022-10-11 09:31:23.186] [exthost] [info] Extension host terminating: renderer closed the socket
[2022-10-11 09:31:23.197] [exthost] [info] Extension host with pid 10840 exiting with code 0
[2022-10-11 09:31:25.603] [exthost] [info] Extension host with pid 11952 started
[2022-10-11 09:31:25.603] [exthost] [info] Skipping acquiring lock for c:\Users\<user>\AppData\Roaming\Code\User\workspaceStorage\026f6120ae2a51acc9e6528d26b37e75.
[2022-10-11 09:31:25.640] [exthost] [info] $getCanonicalURI invoked for authority (ssh-remote)
[2022-10-11 09:31:25.654] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-ssh, startup: false, activationEvent: 'onResolveRemoteAuthority:ssh-remote'
[2022-10-11 09:31:25.733] [exthost] [info] $resolveAuthority invoked for authority (ssh-remote)
```

## VSCode server 
```Bash
[2022-10-11 09:30:56.842] [remoteagent] [info] [127.0.0.1][af08f31e][ManagementConnection] New connection established.
[2022-10-11 09:31:02.856] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at a._throwIfNoPty (/home/<user>/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:27:7252)","    at a.updateTitle (/home/<user>/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:27:2984)","    at Object.call (/home/<user>/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at c.onPromise (/home/<user>/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)","    at c.onRawMessage (/home/<user>/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)","    at /home/<user>/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:4502","    at m.invoke (/home/<user>/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/home/<user>/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at O.fire (/home/<user>/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.X (/home/<user>/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:9:20837)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-10-11 09:31:02.857] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at a._throwIfNoPty (/home/<user>/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:27:7252)","    at a.updateIcon (/home/<user>/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:27:3046)","    at Object.call (/home/<user>/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at c.onPromise (/home/<user>/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:5833)","    at c.onRawMessage (/home/<user>/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:5216)","    at /home/<user>/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:15:4502","    at m.invoke (/home/<user>/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/home/<user>/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at O.fire (/home/<user>/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.X (/home/<user>/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/platform/terminal/node/ptyHostMain.js:9:20837)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-10-11 09:31:20.528] [remoteagent] [info] [127.0.0.1][af08f31e][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-10-11 09:31:20.621] [remoteagent] [info] [127.0.0.1][ff586f3c][ExtensionHostConnection] <209699> Extension Host Process exited with code: 0, signal: null.
```

## Extensions enabled
<html>
<body>

Extension | Author (truncated) | Version
-- | -- | --
systemd-unit-file | coo | 1.0.6
es7-react-js-snippets | dsz | 4.4.3
vscode-firefox-debug | fir | 2.9.8
auto-rename-tag | for | 0.1.10
better-cpp-syntax | jef | 1.16.1
dotenv | mik | 1.0.1
remote-containers | ms- | 0.255.2
remote-ssh | ms- | 0.84.0
remote-ssh-edit | ms- | 0.84.0
remote-wsl | ms- | 0.72.0
vscode-remote-extensionpack | ms- | 0.21.0
JavaScriptSnippets | xab | 1.8.0
vscode-tailwindcss | bra | 0.8.7
prettier-vscode | esb | 9.9.0
cmake-tools | ms- | 1.12.27
cpptools | ms- | 1.12.4
cpptools-extension-pack | ms- | 1.3.0
makefile-tools | ms- | 0.6.0
cmake | twx | 0.0.17
clang-format | xav | 1.9.0

<span style="color: rgb(204, 204, 204); font-family: &quot;Segoe WPC&quot;, &quot;Segoe UI&quot;, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(60, 60, 60); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">(2 theme extensions excluded)</span>
</body>
</html>

## Sys info

<html>
<body>

CPUs | Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: disabled_off
Load (avg) |  
Memory (System) | 15.89GB (7.97GB free)
Process Argv | --crash-reporter-id ab400741-bd8b-4d52-8cbf-a0ebbb5b2e2c
Screen Reader | no
VM | 0%

</body>
</html>

## Remote sys info

<html>
<body>

Remote | SSH: desktop-work
-- | --
OS | Linux x64 5.15.0-48-generic
CPUs | Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 1627)
Memory (System) | 15.50GB (12.58GB free)
VM | 0%

SSH: desktop-work
--
  | Connection to 'SSH: desktop-work' could not be established Connecting with SSH timed out

</body>
</html>

**Comment by roblourens** [comment]
> As said, some folders can be opened and some cannot

Could you share a log from an instance where this does work?

The log only shows that ssh was not able to connect. I doubt there is an actual difference between folders, but there may be some randomness.

**Comment by ocimer** [comment]
# Found the step to reproduce (see below)

## Some use cases and log for when it works as it should ...

- Connect to host: 
OK (with "desktop-work" ssh config)

- It can open a directory with the same but fresh project (fresh git clone).
SSH log:
[09:01:11.666] Log Level: 2
[09:01:11.667] remote-ssh@0.90.1
[09:01:11.668] win32 x64
[09:01:11.708] SSH Resolver called for "ssh-remote+desktop-work", attempt 1
[09:01:11.709] "remote.SSH.useLocalServer": false
[09:01:11.710] "remote.SSH.showLoginTerminal": false
[09:01:11.710] "remote.SSH.remotePlatform": {"desktop-work":"linux","raspi":"linux"}
[09:01:11.711] "remote.SSH.path": undefined
[09:01:11.711] "remote.SSH.configFile": undefined
[09:01:11.711] "remote.SSH.useFlock": true
[09:01:11.712] "remote.SSH.lockfilesInTmp": false
[09:01:11.712] "remote.SSH.localServerDownload": auto
[09:01:11.712] "remote.SSH.remoteServerListenOnSocket": false
[09:01:11.712] "remote.SSH.showLoginTerminal": false
[09:01:11.713] "remote.SSH.defaultExtensions": []
[09:01:11.713] "remote.SSH.loglevel": 2
[09:01:11.713] "remote.SSH.enableDynamicForwarding": true
[09:01:11.713] "remote.SSH.enableRemoteCommand": false
[09:01:11.713] "remote.SSH.serverPickPortsFromRange": {}
[09:01:11.714] "remote.SSH.serverInstallPath": {}
[09:01:11.721] SSH Resolver called for host: desktop-work
[09:01:11.721] Setting up SSH remote "desktop-work"
[09:01:11.801] Using commit id "64bbfbf67ada9953918d72e1df2f4d8e537d340e" and quality "stable" for server
[09:01:11.812] Install and start server if needed
[09:01:11.822] Checking ssh with "ssh -V"
[09:01:12.038] > OpenSSH_for_Windows_8.
[09:01:12.038] > 1p1, L
[09:01:12.039] > i
[09:01:12.040] > breSSL 3.0.2

[09:01:12.056] Running script with connection command: ssh -T -D 61086 "desktop-work" bash
[09:01:12.067] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[09:01:12.753] > ]0;C:\WINDOWS\System32\cmd.exe
[09:01:12.754] Got some output, clearing connection timeout
[09:01:13.065] > 3bc0458be7f3: running
[09:01:13.089] > Acquiring lock on /home/<user>/.vscode-server/bin/64bbfbf67ada9953918d72e1df2f4d
> 8e537d340e/vscode-remote-lock.<user>.64bbfbf67ada9953918d72e1df2f4d8e537d340e   
[09:01:13.099] > Found existing installation at /home/<user>/.vscode-server/bin/64bbfbf67ada99539
> 18d72e1df2f4d8e537d340e...
> Checking /home/<user>/.vscode-server/.64bbfbf67ada9953918d72e1df2f4d8e537d340e.l
> og and /home/<user>/.vscode-server/.64bbfbf67ada9953918d72e1df2f4d8e537d340e.pid
>  for a running server
> Looking for server with pid: 292446
[09:01:13.116] > Found running server...
[09:01:13.124] > 
> *
> * Reminder: You may only use this software with Visual Studio family products, 
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
> 
[09:01:13.134] > Checking server status on port 33341 with wget
> 3bc0458be7f3: start
> SSH_AUTH_SOCK====
> DISPLAY====
> webUiAccessToken====
> listeningOn==33341==
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> connectionToken==11a11111-1a1a-1a1a-a1a1-11aaaaa11111==
> 3bc0458be7f3: end
[09:01:13.135] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==33341==
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==11a11111-1a1a-1a1a-a1a1-11aaaaa11111==

[09:01:13.136] Remote server is listening on 33341
[09:01:13.136] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":33341},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/1000","platform":"linux","connectionToken":"11a11111-1a1a-1a1a-a1a1-11aaaaa11111"},"installUnpackCode":""}
[09:01:13.141] Starting forwarding server. localPort 61098 -> socksPort 61086 -> remotePort 33341
[09:01:13.142] Forwarding server listening on 61098
[09:01:13.143] Waiting for ssh tunnel to be ready
[09:01:13.148] Tunneled 33341 to local port 61098
[09:01:13.149] Resolved "ssh-remote+desktop-work" to "127.0.0.1:61098"
[09:01:13.151] [Forwarding server 61098] Got connection 0
[09:01:13.173] ------




[09:01:13.210] [Forwarding server 61098] Got connection 1
[09:01:13.235] [Forwarding server 61098] Got connection 2
[09:01:15.091] [Forwarding server 61098] Got connection 3
[09:01:52.369] Picking SSH host
[09:01:54.122] Selected desktop-work

- Case with the same .vscode folder (added the same .vscode folder from old dir to the fresh dir)
OK
- Case with git flow init (tool specific)
OK
- Case with the same additional folders (.tar packages , user specific ...)
OK
- Case with configured makefile tools
**!!!!! NOT OK !!!!!!!**
When I have **configured** (steps 1 - configure and 2 - build) Makefile tools with my make file in the secondary sidebar view, the VS Code does not open my directory, instead it timeouts with SSH! Maybe Makefile init takes too long?

**Comment by roblourens** [comment]
Could someone do this

- F1 > "Set Log Level" > Trace
- Reproduce the issue
- Share the logs from the "Log (Window)" output channel

Thank you

**Comment by Billy-Sheppard** [comment]
I'm getting the same issue, some folders work others just time out.

Here is the trace:

```
[14:56:01.865] Log Level: 1
[14:56:01.866] remote-ssh@0.90.1
[14:56:01.866] linux x64
[14:56:01.880] SSH Resolver called for "ssh-remote+localhost", attempt 1
[14:56:01.880] "remote.SSH.useLocalServer": false
[14:56:01.880] "remote.SSH.showLoginTerminal": false
[14:56:01.881] "remote.SSH.remotePlatform": {"localhost":"linux"}
[14:56:01.881] "remote.SSH.path": undefined
[14:56:01.881] "remote.SSH.configFile": undefined
[14:56:01.881] "remote.SSH.useFlock": true
[14:56:01.881] "remote.SSH.lockfilesInTmp": false
[14:56:01.881] "remote.SSH.localServerDownload": auto
[14:56:01.881] "remote.SSH.remoteServerListenOnSocket": false
[14:56:01.881] "remote.SSH.showLoginTerminal": false
[14:56:01.881] "remote.SSH.defaultExtensions": []
[14:56:01.881] "remote.SSH.loglevel": 1
[14:56:01.882] "remote.SSH.enableDynamicForwarding": true
[14:56:01.882] "remote.SSH.enableRemoteCommand": false
[14:56:01.882] "remote.SSH.serverPickPortsFromRange": {}
[14:56:01.882] "remote.SSH.serverInstallPath": {}
[14:56:01.886] SSH Resolver called for host: localhost
[14:56:01.886] Setting up SSH remote "localhost"
[14:56:01.889] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[14:56:01.891] Install and start server if needed
[14:56:01.891] PATH: /var/home/billy/.local/bin:/var/home/billy/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:~/azuredatastudio-linux-x64:/var/home/billy/bin:~/azuredatastudio-linux-x64:/var/home/billy/bin
[14:56:01.892] Checking ssh with "ssh -V"
[14:56:01.906] > OpenSSH_8.8p1, OpenSSL 3.0.5 5 Jul 2022

[14:56:01.908] Running script with connection command: ssh -T -D 34945 -o ConnectTimeout=15 localhost bash
[14:56:18.908] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (/var/home/billy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:585348)
	at Timeout._onTimeout (/var/home/billy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:679743)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[14:56:18.910] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Timeout","exitCodeLabel":""},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":17028,"timing.preSshTime":28,"timing.scriptTime":17000}}
[14:56:18.912] ------




[14:56:18.914] ------




[14:56:18.914] SSH Resolver called for "ssh-remote+localhost", attempt 2, (Reconnection)
[14:56:18.915] SSH Resolver called for host: localhost
[14:56:18.915] Setting up SSH remote "localhost"
[14:56:18.916] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[14:56:18.920] Install and start server if needed
[14:56:18.923] Running script with connection command: ssh -T -D 36811 -o ConnectTimeout=15 localhost bash
[14:56:35.924] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (/var/home/billy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:585348)
	at Timeout._onTimeout (/var/home/billy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:679743)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[14:56:35.925] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Timeout","exitCodeLabel":""},"measures":{"resolveAttempts":2,"retries":1,"timing.totalResolveTime":17010,"timing.preSshTime":10,"timing.scriptTime":17000}}
[14:56:35.926] ------




[14:56:35.928] ------




[14:56:35.928] SSH Resolver called for "ssh-remote+localhost", attempt 3, (Reconnection)
[14:56:35.929] SSH Resolver called for host: localhost
[14:56:35.929] Setting up SSH remote "localhost"
[14:56:35.930] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[14:56:35.932] Install and start server if needed
[14:56:35.934] Running script with connection command: ssh -T -D 32935 -o ConnectTimeout=15 localhost bash
[14:56:52.935] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (/var/home/billy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:585348)
	at Timeout._onTimeout (/var/home/billy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:679743)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[14:56:52.936] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Timeout","exitCodeLabel":""},"measures":{"resolveAttempts":3,"retries":1,"timing.totalResolveTime":17007,"timing.preSshTime":6,"timing.scriptTime":17001}}
[14:56:52.936] ------




[14:56:52.962] ------




[14:56:52.962] SSH Resolver called for "ssh-remote+localhost", attempt 4, (Reconnection)
[14:56:52.963] SSH Resolver called for host: localhost
[14:56:52.963] Setting up SSH remote "localhost"
[14:56:52.964] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[14:56:52.966] Install and start server if needed
[14:56:52.968] Running script with connection command: ssh -T -D 44863 -o ConnectTimeout=15 localhost bash
[14:57:09.968] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (/var/home/billy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:585348)
	at Timeout._onTimeout (/var/home/billy/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:679743)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[14:57:09.968] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Timeout","exitCodeLabel":""},"measures":{"resolveAttempts":4,"retries":1,"timing.totalResolveTime":17006,"timing.preSshTime":6,"timing.scriptTime":17000}}
[14:57:09.969] ------




[14:57:09.994] ------




[14:57:09.994] SSH Resolver called for "ssh-remote+localhost", attempt 5, (Reconnection)
[14:57:09.994] SSH Resolver called for host: localhost
[14:57:09.994] Setting up SSH remote "localhost"
[14:57:09.995] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[14:57:09.997] Install and start server if needed
[14:57:09.999] Running script with connection command: ssh -T -D 44283 -o ConnectTimeout=15 localhost bash
```

**Comment by eleanorjboyd** [comment]
@Billy-Sheppard could you try increasing your `Remote.SSH: Connect Timeout` setting and see if you get any additional error messaging?

**Comment by ocimer** [comment]
@roblourens Here is the TRACE log.
[vscode-app-1665994526684.log](https://github.com/microsoft/vscode-remote-release/files/9798347/vscode-app-1665994526684.log)
