### ISSUE TITLE
Fails to deploy remote ssh server on armhf

### ISSUE THREAD

**Issue by ulfwin** [microsoft/vscode-remote-release#7328]
When trying to connect to a armhf server (raspberry pi 4), the error message below appears.

I have tried to run "Kill VS Code Server", remove the .vscode-server-oss folder and try again. Same error every time.

Might be an issue specific for armhf, but I don't know.

- VSCode Version: 1.72.0
- Local OS Version: linux Manjaro (archlinux based)
- Remote OS Version: openhabian (debian based)
- Remote Extension/Connection Type: SSH
- Logs:
```
[18:53:55.921] > Found flag and server on host
[18:53:55.941] > d0868c3a8ab5%%2%%
> tar --version:
[18:53:55.947] > tar (GNU tar) 1.30
> Copyright (C) 2017 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[18:53:56.108] "Copy server to host" terminal command done
[18:54:08.923] stderr> mv: cannot move 'vscode-server-linux-armhf/bin' to './bin'
[18:54:08.924] stderr> : Directory not empty
[18:54:08.925] stderr> 
[18:54:08.925] stderr> mv: cannot move 'vscode-server-linux-armhf/extensions' to './extensions': Directory not empty
[18:54:08.976] stderr> mv: 
[18:54:08.979] stderr> cannot move 'vscode-server-linux-armhf/node_modules' to './node_modules'
[18:54:08.981] stderr> : Directory not empty
[18:54:08.981] stderr> mv: cannot move 'vscode-server-linux-armhf/out' to './out': Directory not empty
[18:54:08.983] > ERROR: /home/openhabian/.vscode-server-oss/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/node or /home/openhabian/.vscode-server-oss/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/bin/code-server-oss don't exist
```

Steps to Reproduce:

1. Add new SSH Host
2. Try to connect to it
3. Fails after a while (need to give password twice and all data seems to be downloaded)

Thanks in advance!

**Comment by eleanorjboyd** [comment]
Hello! Could you please provide the entire remote-ssh logs? The whole logs includes some settings which are helpful to the debugging process. Feel free to remove any confidential information as you see fit but the logs are most helpful when they are verbose so include as much as possible. Thanks!

**Comment by ulfwin** [comment]
Sure! Here is the full log:
```
[20:05:22.927] Log Level: 2
[20:05:22.929] remote-ssh@0.90.1
[20:05:22.930] linux x64
[20:05:22.932] SSH Resolver called for "ssh-remote+192.168.51.6", attempt 1
[20:05:22.934] "remote.SSH.useLocalServer": true
[20:05:22.936] "remote.SSH.path": undefined
[20:05:22.936] "remote.SSH.configFile": undefined
[20:05:22.937] "remote.SSH.useFlock": true
[20:05:22.937] "remote.SSH.lockfilesInTmp": false
[20:05:22.937] "remote.SSH.localServerDownload": auto
[20:05:22.938] "remote.SSH.remoteServerListenOnSocket": false
[20:05:22.938] "remote.SSH.showLoginTerminal": false
[20:05:22.938] "remote.SSH.defaultExtensions": []
[20:05:22.939] "remote.SSH.loglevel": 2
[20:05:22.939] "remote.SSH.enableDynamicForwarding": true
[20:05:22.939] "remote.SSH.enableRemoteCommand": false
[20:05:22.940] "remote.SSH.serverPickPortsFromRange": {}
[20:05:22.940] "remote.SSH.serverInstallPath": {}
[20:05:22.951] SSH Resolver called for host: 192.168.51.6
[20:05:22.951] Setting up SSH remote "192.168.51.6"
[20:05:22.968] Acquiring local install lock: /tmp/vscode-remote-ssh-cfb22688-install.lock
[20:05:22.972] Looking for existing server data file at /home/ulf/.config/Code - OSS/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-cfb22688-64bbfbf67ada9953918d72e1df2f4d8e537d340e-0.90.1/data.json
[20:05:22.973] Using commit id "64bbfbf67ada9953918d72e1df2f4d8e537d340e" and quality "stable" for server
[20:05:22.980] Install and start server if needed
[20:05:22.984] PATH: /home/ulf/.local/bin:/opt/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
[20:05:22.984] Checking ssh with "ssh -V"
[20:05:22.992] > OpenSSH_9.0p1, OpenSSL 1.1.1q  5 Jul 2022

[20:05:22.995] askpass server listening on /run/user/1000/vscode-ssh-askpass-08f74361167a2c2e16295c5ddfee42e944e8d4dc.sock
[20:05:22.995] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-fd4e368b22d6aaf7f88b9afc7f814feda157073f.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","43833","-o","ConnectTimeout=15","192.168.51.6"],"serverDataFolderName":".vscode-server-oss","dataFilePath":"/home/ulf/.config/Code - OSS/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-cfb22688-64bbfbf67ada9953918d72e1df2f4d8e537d340e-0.90.1/data.json"}
[20:05:22.995] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","SHELL":"/bin/bash","DISPLAY":":1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/ulf/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/lib/electron19/electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/ulf/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-08f74361167a2c2e16295c5ddfee42e944e8d4dc.sock"}
[20:05:22.999] Spawned 5226
[20:05:23.248] > local-server-1> Spawned ssh, pid=5235
[20:05:23.264] stderr> OpenSSH_9.0p1, OpenSSL 1.1.1q  5 Jul 2022
[20:05:23.344] stderr> debug1: Server host key: ssh-ed25519 SHA256:yu/kM8BXOjNoHKp7rgUbpv1VE6SeARIlZM3lCwmT1KU
[20:05:23.554] Got askpass request: {"request":"--ms-enable-electron-run-as-node openhabian@192.168.51.6's password:"}
[20:05:23.554] Showing password prompt
[20:05:23.555] Listening for interwindow password on /run/user/1000/vscode-ssh-askpass-27a748b447a3ac1a480ee6133a425b36d7a3f48f.sock
[20:05:23.555] Writing password prompt to globalState
[20:05:32.585] Got password response
[20:05:32.585] Interactor gave response: ***********************
[20:05:32.586] Cleaning up other-window auth server
[20:05:32.706] stderr> Authenticated to 192.168.51.6 ([192.168.51.6]:22) using "password".
[20:05:32.823] > Linux openhabian 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l
> 
> The programs included with the Debian GNU/Linux system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
> permitted by applicable law.
[20:05:32.867] > 
[20:05:32.869] > Wi-Fi is currently blocked by rfkill.
[20:05:32.873] > Use raspi-config to set the country before use.
[20:05:32.875] > 
[20:05:32.887] > 
[20:05:32.893] > [38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#
> [38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m [38;5;236m openhabian[38;5;236m [38;5;236m [38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#[38;5;236m#
> [38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#
> [38;5;238m#[38;5;238m#[38;5;238m [38;5;238m [38;5;238m [38;5;238m [38;5;238m [38;5;238m [38;5;238m [38;5;238m [38;5;245mIp [38;5;254m= [38;5;255m192.168.51.6
> [38;5;238m#[38;5;238m#[38;5;238m [38;5;238m [38;5;238m [38;5;245mRelease [38;5;254m= [38;5;250mRaspbian GNU/Linux 10 (buster)
> [38;5;238m#[38;5;238m#[38;5;238m [38;5;238m [38;5;238m [38;5;238m [38;5;245mKernel [38;5;254m= [38;5;250mLinux 5.10.103-v7l+
> [38;5;238m#[38;5;238m#[38;5;238m [38;5;238m [38;5;245mPlatform [38;5;254m= [38;5;250mRaspberry Pi 4 Model B Rev 1.1
> [38;5;238m#[38;5;238m#[38;5;238m [38;5;238m [38;5;238m [38;5;238m [38;5;245mUptime [38;5;254m= [38;5;255m79 [38;5;250mday(s). [38;5;255m23[38;5;250m:[38;5;255m8[38;5;250m:[38;5;255m37
> [38;5;238m#[38;5;238m#[38;5;238m [38;5;245mCPU Usage [38;5;254m= [38;5;255m10.03%[38;5;250m avg over [38;5;255m4 [38;5;250mcpu(s) ([38;5;255m4 [38;5;250mcore(s) x [38;5;255m1 [38;5;250msocket(s))
> [38;5;238m#[38;5;238m#[38;5;238m [38;5;238m [38;5;245mCPU Load [38;5;254m= [38;5;255m1m: 0.00, 5m: 0.00, 15m: 0.00
> [38;5;238m#[38;5;238m#[38;5;238m [38;5;238m [38;5;238m [38;5;238m [38;5;245mMemory [38;5;254m= [38;5;250mFree: [38;5;255m1.01GB[38;5;250m ([38;5;255m27%[38;5;250m), Used: [38;5;255m2.78GB[38;5;250m ([38;5;255m73%[38;5;250m), Total: [38;5;255m3.79GB[38;5;250m
> [38;5;238m#[38;5;238m#[38;5;238m [38;5;238m [38;5;238m [38;5;238m [38;5;238m [38;5;238m [38;5;245mSwap [38;5;254m= [38;5;250mFree: [38;5;255m2.58GB [38;5;250m([38;5;255m100%[38;5;250m), Used: [38;5;255m0.00GB [38;5;250m([38;5;255m0%[38;5;250m), Total: [38;5;255m2.58GB
> [38;5;238m#[38;5;238m#[38;5;238m [38;5;238m [38;5;238m [38;5;238m [38;5;238m [38;5;238m [38;5;245mRoot [38;5;254m= [38;5;250mFree: [38;5;255m18.69GB [38;5;250m([38;5;255m71%[38;5;250m), Used: [38;5;255m7.31GB [38;5;250m([38;5;255m29%[38;5;250m), Total: [38;5;255m27.13GB
> [38;5;238m#[38;5;238m#[38;5;238m [38;5;238m [38;5;238m [38;5;245mUpdates [38;5;254m= [38;5;255m103 apt [38;5;250mupdates available.
> [38;5;238m#[38;5;238m#[38;5;238m [38;5;238m [38;5;245mSessions [38;5;254m= [38;5;255m4 session(s)
> [38;5;238m#[38;5;238m#[38;5;238m [38;5;245mProcesses [38;5;254m= [38;5;255m148 [38;5;250mrunning processes of [38;5;255m32768 [38;5;250mmaximum processes
> [38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#[38;5;238m#
[20:05:32.969] > 
>                           _   _     _     ____   _               
>   ___   ___   ___   ___  | | | |   / \   | __ ) (_)  ____   ___  
>  / _ \ / _ \ / _ \ / _ \ | |_| |  / _ \  |  _ \ | | / _  \ / _ \ 
> | (_) | (_) |  __/| | | ||  _  | / ___ \ | |_) )| || (_) || | | |
>  \___/|  __/ \___/|_| |_||_| |_|/_/   \_\|____/ |_| \__|_||_| | |
>       |_|                  openHAB 3.3.0.M3 - Milestone Build          
[20:05:32.973] > Looking for a place to get started? Check out 'sudo openhabian-config' and the
> documentation at https://www.openhab.org/docs/installation/openhabian.html[36;49;00m
> The openHAB dashboard can be reached at http://openhabian:8080[39;49;00m
> To interact with openHAB on the command line, execute: 'openhab-cli --help'
> 
> ready: d4aaa56984a5
[20:05:32.985] > Linux 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022
[20:05:32.987] Platform: linux
[20:05:33.000] > /bin/bash
[20:05:33.002] Shell: bash
[20:05:33.002] Creating bash subshell inside "bash"
[20:05:33.017] > bash version:  5.0.3(1)-release
[20:05:33.094] > d4aaa56984a5: running
[20:05:33.575] > Acquiring lock on /home/openhabian/.vscode-server-oss/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/vscode-remote-lock.openhabian.64bbfbf67ada9953918d72e1df2f4d8e537d340e
> Installing to /home/openhabian/.vscode-server-oss/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e...
[20:05:33.585] > d4aaa56984a5%%1%%
[20:05:33.642] > Downloading with wget
[20:05:36.237] > Download complete
[20:05:36.239] > d4aaa56984a5%%2%%
> tar --version:
> tar (GNU tar) 1.30
> Copyright (C) 2017 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[20:05:49.959] > ERROR: /home/openhabian/.vscode-server-oss/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/node or /home/openhabian/.vscode-server-oss/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/bin/code-server-oss don't exist
[20:05:49.961] > Trigger local server download
> d4aaa56984a5:trigger_server_download
> platform==linux==
> vscodeArch==armhf==
> destFolder==/home/openhabian/.vscode-server-oss/bin/==
> destFolder2==64bbfbf67ada9953918d72e1df2f4d8e537d340e==
> d4aaa56984a5:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/openhabian/.vscode-server-oss/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/vscode-scp-done.flag and vscode-server.tar.gz to exist
>  
[20:05:49.964] Got request to download on client for {"platform":"linux","arch":"armhf","destFolder":"/home/openhabian/.vscode-server-oss/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e"}
[20:05:49.966] Downloading VS Code server locally...
[20:05:51.780] Downloaded VS Code server to /tmp/ef1226d3-5b46-480a-b3fe-0d308f3a1d40
[20:05:51.780] Renamed VS Code server to /tmp/vscode_server_1665943551780/vscode-server.tar.gz
[20:05:51.782] PATH: /home/ulf/.local/bin:/opt/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
[20:05:51.782] Checking ssh with "ssh -V"
[20:05:51.789] > OpenSSH_9.0p1, OpenSSL 1.1.1q  5 Jul 2022

[20:05:51.789] Testing scp with "scp"
[20:05:51.801] scp exited with code: 1
[20:05:51.801] Got stderr from scp: usage: scp [-346ABCOpqRrsTv] [-c cipher] [-D sftp_server_path] [-F ssh_config]
           [-i identity_file] [-J destination] [-l limit]
           [-o ssh_option] [-P port] [-S program] source ... target
[20:05:51.802] Copying file to remote with scp -o ConnectTimeout=15 'vscode-server.tar.gz' 'vscode-scp-done.flag' '192.168.51.6':'/home/openhabian/.vscode-server-oss/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e'
[20:05:51.803] Using cwd: file:///tmp/vscode_server_1665943551780
[20:05:52.174] > openhabian@192.168.51.6's password: 
[20:05:52.175] Showing password prompt
[20:05:53.851] >  
[20:05:56.820] >  
[20:05:59.795] >  
[20:06:02.520] Got password response
[20:06:02.521] "Copy server to host" wrote data to terminal: "***********************"
[20:06:02.567] > 
[20:06:02.800] >  
[20:06:02.852] > vscode-server.tar.gz                            0%    0     0.0KB/s   --:-- ETA
[20:06:03.853] > vscode-server.tar.gz                            9% 4224KB   4.1MB/s   00:10 ETA
[20:06:04.851] > vscode-server.tar.gz                           18% 8576KB   4.1MB/s   00:08 ETA
[20:06:05.807] >  
[20:06:05.851] > vscode-server.tar.gz                           28%   13MB   4.2MB/s   00:07 ETA
[20:06:06.852] > vscode-server.tar.gz                           37%   17MB   4.2MB/s   00:06 ETA
[20:06:07.855] > vscode-server.tar.gz                           47%   22MB   4.2MB/s   00:05 ETA
[20:06:08.815] >  
[20:06:08.852] > vscode-server.tar.gz                           56%   26MB   4.2MB/s   00:04 ETA
[20:06:09.851] > vscode-server.tar.gz                           66%   30MB   4.2MB/s   00:03 ETA
[20:06:10.852] > vscode-server.tar.gz                           73%   33MB   4.1MB/s   00:02 ETA
[20:06:11.827] >  
[20:06:11.852] > vscode-server.tar.gz                           83%   38MB   4.2MB/s   00:01 ETA
[20:06:12.851] > vscode-server.tar.gz                           85%   39MB   3.8MB/s   00:01 ETA
[20:06:13.852] > vscode-server.tar.gz                           89%   41MB   3.6MB/s   00:01 ETA
[20:06:14.821] >  
[20:06:14.855] > vscode-server.tar.gz                           99%   45MB   3.7MB/s   00:00 ETA
[20:06:14.912] > vscode-server.tar.gz                          100%   45MB   3.8MB/s   00:12    
[20:06:14.942] > vscode-scp-done.flag                            0%    0     0.0KB/s   --:-- ETA
[20:06:14.948] > vscode-scp-done.flag                          100%    9     1.4KB/s   00:00    
[20:06:15.372] "Copy server to host" terminal command done
[20:06:17.916] > Found flag and server on host
[20:06:18.324] > d4aaa56984a5%%2%%
> tar --version:
> tar (GNU tar) 1.30
> Copyright (C) 2017 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[20:06:30.364] stderr> mv: cannot move 'vscode-server-linux-armhf/bin' to './bin': Directory not empty
[20:06:30.364] stderr> mv: cannot move 'vscode-server-linux-armhf/extensions' to './extensions': Directory not empty
[20:06:30.365] stderr> 
[20:06:30.413] stderr> mv: cannot move 'vscode-server-linux-armhf/node_modules' to './node_modules': Directory not empty
[20:06:30.414] stderr> 
[20:06:30.415] stderr> mv: cannot move 'vscode-server-linux-armhf/out' to './out': Directory not empty
[20:06:30.415] > ERROR: /home/openhabian/.vscode-server-oss/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/node or /home/openhabian/.vscode-server-oss/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/bin/code-server-oss don't exist
> Already attempted local download, failing
> d4aaa56984a5: start
> exitCode==37==
> listeningOn====
> osReleaseId==raspbian==
> arch==armv7l==
> tmpDir==/run/user/1000==
[20:06:30.421] > platform==linux==
> unpackResult==missingFiles==
> didLocalDownload==1==
> downloadTime==2589==
> installTime==12128==
> extInstallTime====
> serverStartTime====
> d4aaa56984a5: end
[20:06:30.423] Received install output: 
exitCode==37==
listeningOn====
osReleaseId==raspbian==
arch==armv7l==
tmpDir==/run/user/1000==platform==linux==
unpackResult==missingFiles==
didLocalDownload==1==
downloadTime==2589==
installTime==12128==
extInstallTime====
serverStartTime====

[20:06:30.427] Terminating local server
[20:06:30.438] Resolver error: Error: Failed to install the VS Code Server
	at g.ServerInstallError (/home/ulf/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:585156)
	at f (/home/ulf/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:579642)
	at t.handleInstallOutput (/home/ulf/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:582429)
	at Object.e [as tryInstallWithLocalServer] (/home/ulf/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:624373)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/ulf/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:643506
	at async t.withShowDetailsEvent (/home/ulf/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:647224)
	at async /home/ulf/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:622845
	at async T (/home/ulf/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:619351)
	at async t.resolveWithLocalServer (/home/ulf/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:622460)
	at async t.resolve (/home/ulf/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:644834)
	at async /home/ulf/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:726917
[20:06:30.455] ------




[20:06:30.458] Local server exit: 15
[20:06:30.698] ------




[20:06:30.698] SSH Resolver called for "ssh-remote+192.168.51.6", attempt 2, (Reconnection)
[20:06:30.700] SSH Resolver called for host: 192.168.51.6
[20:06:30.700] Setting up SSH remote "192.168.51.6"
[20:06:30.702] Acquiring local install lock: /tmp/vscode-remote-ssh-cfb22688-install.lock
[20:06:30.703] Looking for existing server data file at /home/ulf/.config/Code - OSS/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-cfb22688-64bbfbf67ada9953918d72e1df2f4d8e537d340e-0.90.1/data.json
[20:06:30.703] Using commit id "64bbfbf67ada9953918d72e1df2f4d8e537d340e" and quality "stable" for server
[20:06:30.710] Install and start server if needed
[20:06:30.714] askpass server listening on /run/user/1000/vscode-ssh-askpass-b78782ccedb39bcc0ea24117cfefb916d3f03a31.sock
[20:06:30.715] Spawning local server with {"serverId":2,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-8be142668cf5620ee604a0484b4ee345228a29e8.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","39061","-o","ConnectTimeout=15","192.168.51.6"],"serverDataFolderName":".vscode-server-oss","dataFilePath":"/home/ulf/.config/Code - OSS/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-cfb22688-64bbfbf67ada9953918d72e1df2f4d8e537d340e-0.90.1/data.json"}
[20:06:30.715] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","SHELL":"/bin/bash","DISPLAY":":1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/ulf/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/lib/electron19/electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/ulf/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-b78782ccedb39bcc0ea24117cfefb916d3f03a31.sock"}
[20:06:30.721] Spawned 5330
[20:06:30.950] > local-server-2> Spawned ssh, pid=5340
[20:06:30.954] stderr> OpenSSH_9.0p1, OpenSSL 1.1.1q  5 Jul 2022
[20:06:31.031] stderr> debug1: Server host key: ssh-ed25519 SHA256:yu/kM8BXOjNoHKp7rgUbpv1VE6SeARIlZM3lCwmT1KU
[20:06:31.228] Got askpass request: {"request":"--ms-enable-electron-run-as-node openhabian@192.168.51.6's password:"}
[20:06:31.228] Showing password prompt
[20:06:31.229] Listening for interwindow password on /run/user/1000/vscode-ssh-askpass-bb074f4bfd8b257128c908bb82d94866fed40f0a.sock
[20:06:31.229] Writing password prompt to globalState
```

**Comment by eleanorjboyd** [comment]
Hello, are you using an official build of the remote-ssh extension? I am noticing some differences that what we would expect in terms of file structure. Thanks!

**Comment by ulfwin** [comment]
Seems I by mistake installed an open source version of VS Code rather than the proprietary. Works now! Thanks for your time!
