### ISSUE TITLE
Remote SSH Connection Fails during Server Installation on Remote

### ISSUE THREAD

**Issue by Wanger-SJTU** [microsoft/vscode-remote-release#7335]
- VSCode Version: 1.71.2
- Local OS Version: Windows 10 19043.1889
- Remote OS Version:Ubuntu 18.04.2 LTS
- Remote Extension/Connection Type: SSH/Containers/WSL/Server
- Logs:
```
[14:26:22.399] Log Level: 1
[14:26:22.400] remote-ssh@0.90.1
[14:26:22.400] win32 x64
[14:26:22.409] SSH Resolver called for "ssh-remote+191", attempt 1
[14:26:22.409] "remote.SSH.useLocalServer": false
[14:26:22.410] "remote.SSH.showLoginTerminal": false
[14:26:22.410] "remote.SSH.remotePlatform": {"142":"linux"}
[14:26:22.410] "remote.SSH.path": undefined
[14:26:22.410] "remote.SSH.configFile": undefined
[14:26:22.411] "remote.SSH.useFlock": true
[14:26:22.411] "remote.SSH.lockfilesInTmp": false
[14:26:22.411] "remote.SSH.localServerDownload": auto
[14:26:22.412] "remote.SSH.remoteServerListenOnSocket": false
[14:26:22.412] "remote.SSH.showLoginTerminal": false
[14:26:22.414] "remote.SSH.defaultExtensions": []
[14:26:22.414] "remote.SSH.loglevel": 1
[14:26:22.415] "remote.SSH.enableDynamicForwarding": true
[14:26:22.415] "remote.SSH.enableRemoteCommand": false
[14:26:22.415] "remote.SSH.serverPickPortsFromRange": {}
[14:26:22.415] "remote.SSH.serverInstallPath": {}
[14:26:22.436] SSH Resolver called for host: 191
[14:26:22.437] Setting up SSH remote "191"
[14:26:22.442] Using commit id "74b1f979648cc44d385a2286793c226e611f59e7" and quality "stable" for server
[14:26:22.446] Install and start server if needed
[14:26:22.448] Checking ssh with "ssh -V"
[14:26:22.482] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[14:26:22.486] Running script with connection command: ssh -T -D 51746 191 bash
[14:26:22.488] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[14:26:23.432] "install" terminal received data: "[2J[m[H286c897744d2: running
]0;C:\WINDOWS\System32\cmd.exe[?25h"
[14:26:23.432] Got some output, clearing connection timeout
[14:26:23.460] "install" terminal received data: "Acquiring lock on /home/ch/.vscode-server/bin/74b1f979648cc44d385a2286793c
226e611f59e7/vscode-remote-lock.ch.74b1f979648cc44d385a2286793c226e611f59e
7[K"
[14:26:23.476] "install" terminal received data: "Installing to /home/ch/.vscode-server/bin/74b1f979648cc44d385a2286793c226e
611f59e7...[K
286c897744d2%%1%%[K
Downloading with wget[K"
[14:26:30.770] "install" terminal received data: "wget download failed[9X
failed: Connection timed out.
printenv:[K
    SSH_CONNECTION=10.143.63.77 51748 7.189.53.10 22[K
    LANG=en_US.UTF-8[K
    XDG_SESSION_ID=214939[K
    USER=ch[K
    PWD=/home/ch/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59
e7[K
    HOME=/home/ch[K
    SSH_CLIENT=10.143.63.77 51748 22[K
    MAIL=/var/mail/ch[K
    SHELL=/bin/bash[K
    SHLVL=2[K
    LANGUAGE=en_US:[K
    VSCODE_AGENT_FOLDER=/home/ch/.vscode-server[K
    LOGNAME=ch[K
    DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus[K
    XDG_RUNTIME_DIR=/run/user/1000[K
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
:/usr/local/games[K
    _=/usr/bin/printenv[K
    OLDPWD=/home/ch
Trigger local server download
286c897744d2:trigger_server_download
platform==linux==
vscodeArch==x64==
destFolder==/home/ch/.vscode-server/bin/==
destFolder2==74b1f979648cc44d385a2286793c226e611f59e7==
286c897744d2:trigger_server_download_end"
[14:26:30.770] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/home/ch/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7"}
[14:26:30.770] Downloading VS Code server locally...
[14:26:30.790] "install" terminal received data: ""
[14:26:30.807] "install" terminal received data: "Waiting for client to transfer server archive...
Waiting for /home/ch/.vscode-server/bin/74b1f979648cc44d385a2286793c226e61
1f59e7/vscode-scp-done.flag and vscode-server.tar.gz to exist
[1C"
[14:26:33.772] "install" terminal received data: " "
[14:26:36.775] "install" terminal received data: " "
[14:26:39.775] "install" terminal received data: " "
[14:26:42.778] "install" terminal received data: " "
[14:26:45.779] "install" terminal received data: " "
[14:26:48.782] "install" terminal received data: " "
[14:26:51.782] "install" terminal received data: " "
[14:26:54.784] "install" terminal received data: " "
[14:26:57.786] "install" terminal received data: " "
[14:27:00.789] "install" terminal received data: " "
[14:27:03.657] Downloaded VS Code server to c:\Users\C00562~1\AppData\Local\Temp\4763a426-8aab-4ae0-8f98-e1612f72fd98
[14:27:03.658] Renamed VS Code server to c:\Users\C00562~1\AppData\Local\Temp\vscode_server_1665556023657\vscode-server.tar.gz
[14:27:03.661] Checking ssh with "ssh -V"
[14:27:03.691] > OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

[14:27:03.693] Testing scp with "scp"
[14:27:03.754] scp exited with code: 1
[14:27:03.754] Got stderr from scp: usage: scp [-346ABCpqrTv] [-c cipher] [-F ssh_config] [-i identity_file]
            [-J destination] [-l limit] [-o ssh_option] [-P port]
            [-S program] source ... target
[14:27:03.755] Copying file to remote with scp "vscode-server.tar.gz" "vscode-scp-done.flag" 191:"/home/ch/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7"
[14:27:03.755] Using cwd: file:///c%3A/Users/C00562~1/AppData/Local/Temp/vscode_server_1665556023657
[14:27:03.756] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[14:27:03.792] "install" terminal received data: " "
[14:27:03.963] "Copy server to host" terminal received data: "[2J[m[H/usr/bin/ssh]0;C:\WINDOWS\System32\cmd.exe[?25h"
[14:27:03.974] "Copy server to host" terminal received data: "[25l[H/usr/bin/ssh: No such file or directory
lost connection[24X
[?25h"
[14:27:05.239] "Copy server to host" terminal command done
[14:27:06.790] "install" terminal received data: " "
[14:27:09.794] "install" terminal received data: " "
[14:27:12.795] "install" terminal received data: " "

```

Steps to Reproduce:

1. new connect to a server.

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by eleanorjboyd** [comment]
Hello! Could you check on your server side to see if vscode-server.tar was installed? Additionally are there any other nearby files that did successfully download to your remote related to vscode?

**Comment by jimjamg** [comment]
I'm seeing the same behaviour on my RedHat 8 box.

Version: 1.72.1
Commit: 129500ee4c8ab7263461ffe327268ba56b9f210d
Date: 2022-10-10T17:23:00.760Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 4.18.0-372.26.1.el8_6.x86_64
Sandboxed: No

Remote OS Version: CentOS 7.9
[10:23:09.177] > Acquiring lock on /home/user/.vscode-server/bin/129500ee4c8ab7263461ffe327268ba56b9f210d/vscode-remote-lock.user.129500ee4c8ab7263461ffe327268ba56b9f210d
[10:23:09.178] > Installing to /home/user/.vscode-server/bin/129500ee4c8ab7263461ffe327268ba56b9f210d...
[10:23:09.182] > eba3b6cf800c%%1%%
[10:23:09.184] > Downloading with wget
[10:23:16.246] > wget download failed

[user@localhost:~/.vscode-server/bin/129500ee4c8ab7263461ffe327268ba56b9f210d]$ ll
total 0
-rw-r-----. 1  user user 0 Oct 14 09:23 vscode-server.tar.gz

**Comment by eleanorjboyd** [comment]
@jimjamg hello! Could you include the full logs, thanks!

**Comment by jimjamg** [comment]
@eleanorjboyd Please see the full logs:

`[11:07:33.664] Log Level: 2
[11:07:33.666] remote-ssh@0.90.1
[11:07:33.666] linux x64
[11:07:33.668] SSH Resolver called for "ssh-remote+remote.machine.com", attempt 1
[11:07:33.669] "remote.SSH.useLocalServer": true
[11:07:33.669] "remote.SSH.path": undefined
[11:07:33.670] "remote.SSH.configFile": undefined
[11:07:33.670] "remote.SSH.useFlock": true
[11:07:33.670] "remote.SSH.lockfilesInTmp": false
[11:07:33.670] "remote.SSH.localServerDownload": always
[11:07:33.671] "remote.SSH.remoteServerListenOnSocket": false
[11:07:33.671] "remote.SSH.showLoginTerminal": false
[11:07:33.671] "remote.SSH.defaultExtensions": []
[11:07:33.671] "remote.SSH.loglevel": 2
[11:07:33.672] "remote.SSH.enableDynamicForwarding": true
[11:07:33.672] "remote.SSH.enableRemoteCommand": false
[11:07:33.672] "remote.SSH.serverPickPortsFromRange": {}
[11:07:33.673] "remote.SSH.serverInstallPath": {}
[11:07:33.690] SSH Resolver called for host: remote.machine.com
[11:07:33.691] Setting up SSH remote "remote.machine.com"
[11:07:33.700] Acquiring local install lock: /tmp/vscode-remote-ssh-452856a9-install.lock
[11:07:33.701] Looking for existing server data file at /home/jimjamg/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-452856a9-129500ee4c8ab7263461ffe327268ba56b9f210d-0.90.1/data.json
[11:07:33.703] Using commit id "129500ee4c8ab7263461ffe327268ba56b9f210d" and quality "stable" for server
[11:07:33.707] Install and start server if needed
[11:07:33.713] PATH: /sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/home/jimjamg/.local/bin:/home/jimjamg/bin:/home/jimjamg/.local/bin:/home/jimjamg/bin:/home/jimjamg/.local/bin:/home/jimjamg/bin:/home/jimjamg/.local/bin:/home/jimjamg/bin
[11:07:33.713] Checking ssh with "ssh -V"
[11:07:33.730] > OpenSSH_8.0p1, OpenSSL 1.1.1k  FIPS 25 Mar 2021

[11:07:33.735] askpass server listening on /run/user/10398/vscode-ssh-askpass-c92f75b34f96fc08c9c6fc334ab03edde202a723.sock
[11:07:33.736] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/10398/vscode-ssh-askpass-c58ce2721b7681a916ea6fd5780b835529faf24a.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","33791","-o","ConnectTimeout=15","remote.machine.com"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/jimjamg/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-452856a9-129500ee4c8ab7263461ffe327268ba56b9f210d-0.90.1/data.json"}
[11:07:33.736] Local server env: {"SSH_AUTH_SOCK":"/run/user/10398/keyring/ssh","SHELL":"/bin/bash","DISPLAY":":10.0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/jimjamg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/jimjamg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/10398/vscode-ssh-askpass-c92f75b34f96fc08c9c6fc334ab03edde202a723.sock"}
[11:07:33.741] Spawned 170606
[11:07:33.921] > local-server-1> Spawned ssh, pid=170614
[11:07:33.925] stderr> OpenSSH_8.0p1, OpenSSL 1.1.1k  FIPS 25 Mar 2021
[11:07:34.027] stderr> Server not found in Kerberos database
[11:07:34.027] stderr> 
[11:07:34.027] stderr> 
[11:07:34.039] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:HYTIPZfV+TxvO/U+SoBd6c1kcG0kErTZ8UuaXN87gFk
[11:07:34.094] stderr> All the connections will be logged and monitored. 
[11:07:34.111] stderr> Server not found in Kerberos database
[11:07:34.112] stderr> 
[11:07:34.112] stderr> 
[11:07:34.304] Got askpass request: {"request":"user@remote.machine.com's password:"}
[11:07:34.304] Showing password prompt
[11:07:34.306] Listening for interwindow password on /run/user/10398/vscode-ssh-askpass-75b7f524936e2b00cd29fe8013fc41cbb4742ed3.sock
[11:07:34.306] Writing password prompt to globalState
[11:07:38.061] Got password response
[11:07:38.061] Interactor gave response: ********
[11:07:38.062] Cleaning up other-window auth server
[11:07:38.117] stderr> Authenticated to remote.machine.com ([192.168.1.50]:22).
[11:07:38.398] > ready: f8c01b219003
[11:07:38.401] > Linux 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022
[11:07:38.401] Platform: linux
[11:07:38.402] > /bin/bash
[11:07:38.403] Shell: bash
[11:07:38.403] Creating bash subshell inside "bash"
[11:07:38.406] > bash version:  4.2.46(2)-release
[11:07:38.422] > f8c01b219003: running
[11:07:38.451] > Acquiring lock on /home/user/.vscode-server/bin/129500ee4c8ab7263461ffe327268ba56b9f210d/vscode-remote-lock.user.129500ee4c8ab7263461ffe327268ba56b9f210d
[11:07:38.455] > Installing to /home/user/.vscode-server/bin/129500ee4c8ab7263461ffe327268ba56b9f210d...
[11:07:38.456] > Trigger local server download
> f8c01b219003:trigger_server_download
> platform==linux==
[11:07:38.456] > vscodeArch==x64==
> destFolder==/home/user/.vscode-server/bin/==
> destFolder2==129500ee4c8ab7263461ffe327268ba56b9f210d==
> f8c01b219003:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/user/.vscode-server/bin/129500ee4c8ab7263461ffe327268ba56b9f210d/vscode-scp-done.flag and vscode-server.tar.gz to exist
>  
[11:07:38.456] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/home/user/.vscode-server/bin/129500ee4c8ab7263461ffe327268ba56b9f210d"}
[11:07:38.457] Downloading VS Code server locally...
[11:07:41.458] >  
[11:07:44.459] >  
[11:07:47.461] >  
[11:07:50.463] >  
[11:07:53.464] >  
[11:07:56.466] >  
[11:07:59.467] >  
[11:08:02.468] >  
[11:08:05.470] >  
[11:08:08.471] >  
[11:08:11.473] >  
[11:08:14.474] >  
[11:08:17.476] >  
[11:08:20.478] >  
[11:08:23.480] >  
[11:08:26.481] >  
[11:08:29.483] >  
[11:08:32.484] >  
[11:08:35.485] >  
[11:08:38.487] >  
[11:08:41.491] >  
[11:08:44.491] >  
[11:08:47.492] >  
[11:08:50.493] >  
[11:08:53.494] >  
[11:08:56.496] >  
[11:08:59.498] >  
[11:09:02.499] >  
[11:09:05.501] >  
[11:09:08.503] >  
[11:09:11.505] >  
[11:09:14.505] >  
[11:09:17.507] >  
[11:09:20.508] >  
[11:09:23.509] >  
[11:09:26.510] >  
[11:09:29.512] >  
[11:09:32.514] >  
[11:09:35.516] >  
[11:09:38.518] >  
[11:09:41.520] >  
[11:09:44.521] >  
[11:09:47.523] >  
[11:09:48.173] Terminating local server
[11:09:48.175] Resolver error: Error: XHR failed
    at S.onerror (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:70:9756)
[11:09:48.181] ------




[11:09:48.183] Local server exit: 15
[11:09:48.197] ------




[11:09:48.197] SSH Resolver called for "ssh-remote+remote.machine.com", attempt 2, (Reconnection)
[11:09:48.201] SSH Resolver called for host: remote.machine.com
[11:09:48.201] Setting up SSH remote "remote.machine.com"
[11:09:48.202] Acquiring local install lock: /tmp/vscode-remote-ssh-452856a9-install.lock
[11:09:48.203] Looking for existing server data file at /home/jimjamg/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-452856a9-129500ee4c8ab7263461ffe327268ba56b9f210d-0.90.1/data.json
[11:09:48.204] Using commit id "129500ee4c8ab7263461ffe327268ba56b9f210d" and quality "stable" for server
[11:09:48.209] Install and start server if needed
[11:09:48.214] askpass server listening on /run/user/10398/vscode-ssh-askpass-9c3134671506feb75f437bdb35f5923b66e0ce4e.sock
[11:09:48.214] Spawning local server with {"serverId":2,"ipcHandlePath":"/run/user/10398/vscode-ssh-askpass-64d786cc4d59513e3f398c8a2c563a37270372a2.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","43749","-o","ConnectTimeout=15","remote.machine.com"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/jimjamg/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-452856a9-129500ee4c8ab7263461ffe327268ba56b9f210d-0.90.1/data.json"}
[11:09:48.214] Local server env: {"SSH_AUTH_SOCK":"/run/user/10398/keyring/ssh","SHELL":"/bin/bash","DISPLAY":":10.0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/jimjamg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/jimjamg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/10398/vscode-ssh-askpass-9c3134671506feb75f437bdb35f5923b66e0ce4e.sock"}
[11:09:48.219] Spawned 170728
[11:09:48.412] > local-server-2> Spawned ssh, pid=170736
[11:09:48.421] stderr> OpenSSH_8.0p1, OpenSSL 1.1.1k  FIPS 25 Mar 2021
[11:09:48.546] stderr> Server not found in Kerberos database
[11:09:48.546] stderr> 
[11:09:48.546] stderr> 
[11:09:48.567] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:HYTIPZfV+TxvO/U+SoBd6c1kcG0kErTZ8UuaXN87gFk
[11:09:48.651] stderr> All the connections will be logged and monitored. 
[11:09:48.668] stderr> Server not found in Kerberos database
[11:09:48.668] stderr> 
[11:09:48.668] stderr> 
[11:09:48.913] Got askpass request: {"request":"user@remote.machine.com's password:"}
[11:09:48.914] Showing password prompt
[11:09:48.915] Listening for interwindow password on /run/user/10398/vscode-ssh-askpass-1f99ef03deacc63ac11ed2d8747b3da3a27c5a77.sock
[11:09:48.915] Writing password prompt to globalState
[11:09:52.145] Password dialog canceled
[11:09:52.146] Interactor signaled cancel
[11:09:52.146] Cleaning up other-window auth server
[11:09:52.162] stderr> Permission denied, please try again.
[11:09:52.362] Got askpass request: {"request":"user@remote.machine.com's password:"}
[11:09:52.394] stderr> Received disconnect from 192.168.1.50 port 22:2: Too many authentication failures
[11:09:52.394] stderr> Disconnected from 192.168.1.50 port 22
[11:09:52.395] > local-server-2> ssh child died, shutting down
[11:09:52.403] Local server exit: 0
[11:09:52.403] Received install output: local-server-2> Spawned ssh, pid=170736
OpenSSH_8.0p1, OpenSSL 1.1.1k  FIPS 25 Mar 2021
Server not found in Kerberos database


debug1: Server host key: ecdsa-sha2-nistp256 SHA256:HYTIPZfV+TxvO/U+SoBd6c1kcG0kErTZ8UuaXN87gFk
All the connections will be logged and monitored. 
Server not found in Kerberos database


Permission denied, please try again.
Received disconnect from 192.168.1.50 port 22:2: Too many authentication failures
Disconnected from 192.168.1.50 port 22
local-server-2> ssh child died, shutting down

[11:09:52.408] Resolver error: Error: Too many authentication failures
	at g.Create (/home/jimjamg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:585222)
	at /home/jimjamg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:583279
	at t.handleInstallOutput (/home/jimjamg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:583796)
	at Object.e [as tryInstallWithLocalServer] (/home/jimjamg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:624373)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/jimjamg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:643506
	at async t.withShowDetailsEvent (/home/jimjamg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:647224)
	at async /home/jimjamg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:622845
	at async T (/home/jimjamg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:619351)
	at async t.resolveWithLocalServer (/home/jimjamg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:622460)
	at async t.resolve (/home/jimjamg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:644834)
	at async /home/jimjamg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:726917
[11:09:52.413] ------




[11:09:52.434] ------




[11:09:52.434] SSH Resolver called for "ssh-remote+remote.machine.com", attempt 3, (Reconnection)
[11:09:52.437] SSH Resolver called for host: remote.machine.com
[11:09:52.437] Setting up SSH remote "remote.machine.com"
[11:09:52.439] Acquiring local install lock: /tmp/vscode-remote-ssh-452856a9-install.lock
[11:09:52.442] Looking for existing server data file at /home/jimjamg/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-452856a9-129500ee4c8ab7263461ffe327268ba56b9f210d-0.90.1/data.json
[11:09:52.442] Using commit id "129500ee4c8ab7263461ffe327268ba56b9f210d" and quality "stable" for server
[11:09:52.447] Install and start server if needed
[11:09:52.502] askpass server listening on /run/user/10398/vscode-ssh-askpass-ecab860a3469e11d60c13ff1472283855a3dd10d.sock
[11:09:52.502] Spawning local server with {"serverId":3,"ipcHandlePath":"/run/user/10398/vscode-ssh-askpass-77e2d54bab5e9824669e4753e700361b94561005.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","41419","-o","ConnectTimeout=15","remote.machine.com"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/jimjamg/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-452856a9-129500ee4c8ab7263461ffe327268ba56b9f210d-0.90.1/data.json"}
[11:09:52.504] Local server env: {"SSH_AUTH_SOCK":"/run/user/10398/keyring/ssh","SHELL":"/bin/bash","DISPLAY":":10.0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/jimjamg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/jimjamg/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/10398/vscode-ssh-askpass-ecab860a3469e11d60c13ff1472283855a3dd10d.sock"}
[11:09:52.510] Spawned 170770
[11:09:52.744] > local-server-3> Spawned ssh, pid=170778
[11:09:52.748] stderr> OpenSSH_8.0p1, OpenSSL 1.1.1k  FIPS 25 Mar 2021
[11:09:52.792] stderr> Server not found in Kerberos database
[11:09:52.792] stderr> 
[11:09:52.793] stderr> 
[11:09:52.835] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:HYTIPZfV+TxvO/U+SoBd6c1kcG0kErTZ8UuaXN87gFk
[11:09:52.904] stderr> All the connections will be logged and monitored. 
[11:09:52.920] stderr> Server not found in Kerberos database
[11:09:52.920] stderr> 
[11:09:52.920] stderr> 
[11:09:53.109] Got askpass request: {"request":"user@remote.machine.com's password:"}
[11:09:53.110] Showing password prompt
[11:09:53.110] Listening for interwindow password on /run/user/10398/vscode-ssh-askpass-ef373a84c1fe98d48c4535df83cc78955411ee64.sock
[11:09:53.111] Writing password prompt to globalState
`

**Comment by eleanorjboyd** [comment]
Hello again [jimjamg](https://github.com/jimjamg), could you open a new issue on our repo? Your issue seems to be unrelated to the issue originally mentioned in this issue and therefore we should open a new line of communication to address your issue directly. Thanks!

**Comment by eleanorjboyd** [comment]
@Wanger-SJTU, hello can you try running the command `kill server on remote` and then try again? Additionally, did the logs stall at `[14:27:12.795] "install" terminal received data: " "`? It seems like it was in the process of downloading so I am trying to figure out what could have stopped it. Thanks
