### ISSUE TITLE
Error building container setting extensions in devcontainer.json

### ISSUE THREAD

**Issue by FabianoFPS** [microsoft/vscode-remote-release#7339]
- VSCode Version: 1.72.0
- Local OS Version: Ubuntu 20.04.5 LTS 
- Local chip architecture: x86_64
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue:

Steps to Reproduce:

1. include extension in "extensions" : []
2. Build Container

```json
"customizations": {
		"vscode": {
			"extensions": [
				"gruntfuggly.todo-tree"
			]
		}
	}
```
results in error:

```log
tep 16/16 : LABEL devcontainer.metadata="{\"customizations\":{\"vscode\":{\"extensions\":[\"gruntfuggly.todo-tree\"
[2022-10-09T18:20:43.783Z] ERROR: Service 'api' failed to build: failed to process "\"{\\\"customizations\\\":{\\\"vscode\\\":{\\\"extensions\\\":[\\\"gruntfuggly.todo-tree\\\"": unexpected end of statement while looking for matching double-quote
[2022-10-09T18:20:43.933Z] Stop (5520 ms): Run: docker-compose --project-name codefirst -f /home/fabiano/workspaces/rocketseat/graphql_node/codefirst/docker-compose.yml -f /home/fabiano/workspaces/rocketseat/graphql_node/codefirst/.devcontainer/docker-compose.yml -f /home/fabiano/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1665339638412.yml build
[2022-10-09T18:20:43.937Z] Error: Command failed: docker-compose --project-name codefirst -f /home/fabiano/workspaces/rocketseat/graphql_node/codefirst/docker-compose.yml -f /home/fabiano/workspaces/rocketseat/graphql_node/codefirst/.devcontainer/docker-compose.yml -f /home/fabiano/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1665339638412.yml build
[2022-10-09T18:20:43.938Z]     at pd (/home/fabiano/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.2/dist/spec-node/devContainersSpecCLI.js:259:426)
[2022-10-09T18:20:43.938Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-10-09T18:20:43.939Z]     at async ZF (/home/fabiano/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.2/dist/spec-node/devContainersSpecCLI.js:259:2424)
[2022-10-09T18:20:43.939Z]     at async XF (/home/fabiano/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.2/dist/spec-node/devContainersSpecCLI.js:241:2391)
[2022-10-09T18:20:43.939Z]     at async bD (/home/fabiano/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.2/dist/spec-node/devContainersSpecCLI.js:303:2193)
[2022-10-09T18:20:43.940Z]     at async ys (/home/fabiano/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.2/dist/spec-node/devContainersSpecCLI.js:303:3182)
[2022-10-09T18:20:43.941Z]     at async UL (/home/fabiano/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.2/dist/spec-node/devContainersSpecCLI.js:423:10319)
[2022-10-09T18:20:43.941Z]     at async ML (/home/fabiano/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.2/dist/spec-node/devContainersSpecCLI.js:423:10075)
[2022-10-09T18:20:43.952Z] Stop (9858 ms): Run: /snap/code/109/usr/share/code/code --ms-enable-electron-run-as-node /home/fabiano/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.2/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/fabiano/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/fabiano/workspaces/rocketseat/graphql_node/codefirst --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/fabiano/workspaces/rocketseat/graphql_node/codefirst --log-level debug --log-format json --config /home/fabiano/workspaces/rocketseat/graphql_node/codefirst/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-10-09T18:20:43.954Z] Exit code 1
[2022-10-09T18:20:43.970Z] Command failed: /snap/code/109/usr/share/code/code --ms-enable-electron-run-as-node /home/fabiano/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.2/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/fabiano/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/fabiano/workspaces/rocketseat/graphql_node/codefirst --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/fabiano/workspaces/rocketseat/graphql_node/codefirst --log-level debug --log-format json --config /home/fabiano/workspaces/rocketseat/graphql_node/codefirst/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-10-09T18:20:43.970Z] Exit code 1
```

**Comment by chrmarti** [comment]
What do you get for `docker version`? It looks like it doesn't accept the multi-line LABEL instruction.

**Comment by FabianoFPS** [comment]
Hey
Other settings generate the same error on the label.

```json
"settings": {
		"terminal.integrated.defaultProfile.linux": "bash"
	}
```

```log
Step 15/15 : LABEL devcontainer.metadata="{\"customizations\":{\"vscode\":{\"settings\":{\"terminal.integrated.defaultProfile.linux\":\"bash\"
[2022-10-14T22:22:02.316Z] ERROR: Service 'api-weather' failed to build: failed to process "\"{\\\"customizations\\\":{\\\"vscode\\\":{\\\"settings\\\":{\\\"terminal.integrated.defaultProfile.linux\\\":\\\"bash\\\"": unexpected end of statement while looking for matching double-quote
```
```bash
> docker version             
Client: Docker Engine - Community
 Version:           20.10.19
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        d85ef84
 Built:             Thu Oct 13 16:46:17 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.19
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       c964641
  Built:            Thu Oct 13 16:44:09 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by Denis-Guimaraes** [comment]
Hello,
If it can help, donwgrading the devcontainer extension to 0.251.0 solved the issue for me.

**Comment by FabianoFPS** [comment]
Hi @Denis-Guimaraes , thanks for the tip. This error happened after the update.

**Comment by chrmarti** [comment]
Are you using `# escape=` at the top of your Dockerfile?

**Comment by FabianoFPS** [comment]
I wasn't using # in the Dockerfile.
But in version 0.266.1 this bug does not occur.
Thank you for your attention.
