### ISSUE TITLE
Error: Missing node-pty when using specific Dockerfile command

### ISSUE THREAD

**Issue by aleksanderostrup** [microsoft/vscode-remote-release#7356]
- VSCode Version: 1.72
- Local OS Version: Win 10 Build 10.0.19043
- Remote OS Version: Ubuntu 18.04
- Remote Extension/Connection Type: Containers

Steps to Reproduce:
1. In the Dockerfile, using the command:
   `RUN usermod -l ${USERNAME} vscode --home /home/${USERNAME} --move-home`
(where the ${USERNAME} is defined) **_breaks the building of the container_**. 
It has worked previously with version 0.224.3 of **_Dev Containers_**. 

This might be related to https://github.com/microsoft/vscode-remote-release/issues/6525.

I have tried with the pre-release version of the extension, but that does not seem to fix the issue either.

For some reason I cannot upload my *.log file, so here is the crucial part:

```
=> => exporting layers                                                    0.0s
 => => writing image sha256:0f3755884b553f3689eaab4fa8052e26de742a7371bdb  0.0s
 => => naming to docker.io/library/vsc-p1linux-93c1819c338c289a0848996cea  0.0s
[2022-10-13T12:39:37.088Z] 
[2022-10-13T12:39:37.387Z] 
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[2022-10-13T12:39:37.395Z] Stop (1137 ms): Run: docker build -f /tmp/devcontainercli-ale/updateUID.Dockerfile-0.20.0 -t vsc-p1linux-93c1819c338c289a0848996cea42d1ff-uid --build-arg BASE_IMAGE=vsc-p1linux-93c1819c338c289a0848996cea42d1ff --build-arg REMOTE_USER=vscode --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=root /tmp/devcontainercli-ale/empty-folder
[2022-10-13T12:39:37.396Z] Start: Run: docker -v
[2022-10-13T12:39:37.453Z] Stop (57 ms): Run: docker -v
[2022-10-13T12:39:37.453Z] Start: Run: docker events --format {{json .}} --filter event=start
[2022-10-13T12:39:37.455Z] Start: Starting container
[2022-10-13T12:39:37.455Z] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/ale/git/p1linux,target=/workspaces/p1linux --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=\\wsl$\Ubuntu-22.04\home\ale\git\p1linux --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --entrypoint /bin/sh vsc-p1linux-93c1819c338c289a0848996cea42d1ff-uid -c echo Container started
[2022-10-13T12:39:37.972Z] Container started
[2022-10-13T12:39:37.980Z] Stop (525 ms): Starting container
[2022-10-13T12:39:37.980Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=\\wsl$\Ubuntu-22.04\home\ale\git\p1linux
[2022-10-13T12:39:38.046Z] Stop (66 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=\\wsl$\Ubuntu-22.04\home\ale\git\p1linux
[2022-10-13T12:39:38.047Z] Start: Run: docker inspect --type container 35f38423901c
[2022-10-13T12:39:38.115Z] Stop (68 ms): Run: docker inspect --type container 35f38423901c
[2022-10-13T12:39:38.116Z] Start: Inspecting container
[2022-10-13T12:39:38.116Z] Start: Run: docker inspect --type container 35f38423901cda5a53086530f7d3c4b7b931d4996d7b139a05491ea67efc9342
[2022-10-13T12:39:38.184Z] Stop (68 ms): Run: docker inspect --type container 35f38423901cda5a53086530f7d3c4b7b931d4996d7b139a05491ea67efc9342
[2022-10-13T12:39:38.185Z] Stop (69 ms): Inspecting container
[2022-10-13T12:39:38.186Z] Start: Run in container: /bin/sh
[2022-10-13T12:39:38.189Z] Start: Run in container: uname -m
[2022-10-13T12:39:38.274Z] Stop (88 ms): Run in container: /bin/sh
[2022-10-13T12:39:38.276Z] Shell server terminated (code: 126, signal: null)
[2022-10-13T12:39:38.276Z] unable to find user vscode: no matching entries in passwd file

[2022-10-13T12:39:38.275Z] Start: Run in container: cat /etc/passwd
[2022-10-13T12:39:38.275Z] Stdin closed!
[2022-10-13T12:39:38.278Z] Error: An error occurred setting up the container.
[2022-10-13T12:39:38.278Z]     at Use (/home/ale/.vscode-remote-containers/dist/dev-containers-cli-0.259.0/dist/spec-node/devContainersSpecCLI.js:1868:1339)
[2022-10-13T12:39:38.279Z]     at jO (/home/ale/.vscode-remote-containers/dist/dev-containers-cli-0.259.0/dist/spec-node/devContainersSpecCLI.js:1868:1275)
[2022-10-13T12:39:38.279Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-10-13T12:39:38.279Z]     at async Xse (/home/ale/.vscode-remote-containers/dist/dev-containers-cli-0.259.0/dist/spec-node/devContainersSpecCLI.js:1874:2030)
[2022-10-13T12:39:38.279Z]     at async Uf (/home/ale/.vscode-remote-containers/dist/dev-containers-cli-0.259.0/dist/spec-node/devContainersSpecCLI.js:1874:3193)
[2022-10-13T12:39:38.279Z]     at async Cae (/home/ale/.vscode-remote-containers/dist/dev-containers-cli-0.259.0/dist/spec-node/devContainersSpecCLI.js:1994:10350)
[2022-10-13T12:39:38.279Z]     at async yae (/home/ale/.vscode-remote-containers/dist/dev-containers-cli-0.259.0/dist/spec-node/devContainersSpecCLI.js:1994:10104)
[2022-10-13T12:39:38.282Z] Stop (27317 ms): Run in Host: /home/ale/.vscode-remote-containers/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/node /home/ale/.vscode-remote-containers/dist/dev-containers-cli-0.259.0/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /home/ale/git/p1linux --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl$\Ubuntu-22.04\home\ale\git\p1linux --log-level debug --log-format json --config /home/ale/git/p1linux/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-10-13T12:39:38.283Z] Exit code 1
[2022-10-13T12:39:38.287Z] Command failed: /home/ale/.vscode-remote-containers/bin/64bbfbf67ada9953918d72e1df2f4d8e537d340e/node /home/ale/.vscode-remote-containers/dist/dev-containers-cli-0.259.0/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /home/ale/git/p1linux --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl$\Ubuntu-22.04\home\ale\git\p1linux --log-level debug --log-format json --config /home/ale/git/p1linux/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-10-13T12:39:38.288Z] Exit code 1
[2022-10-13T12:39:41.525Z] Start: Run: wsl -d Ubuntu-22.04 -e wslpath -u \\wsl$\Ubuntu-22.04\home\ale\git\p1linux
[2022-10-13T12:39:41.748Z] Stop (223 ms): Run: wsl -d Ubuntu-22.04 -e wslpath -u \\wsl$\Ubuntu-22.04\home\ale\git\p1linux

```

**Comment by alexnfsc175** [comment]
using podman and podman-compose the same problem happens

```log
[2022-10-17 23:51:10.464] [exthost] [error] {"message":"Command failed: /home/alex/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/node /home/alex/.vscode-remote-containers/dist/dev-containers-cli-0.255.4/dist/spec-node/devContainersSpecCLI.js read-configuration --docker-path podman --docker-compose-path podman-compose --workspace-folder /home/alex/development/test-api --log-level debug --log-format json --config /home/alex/development/test-api/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true","code":1} remote-containers.openFolder {"value":"ms-vscode-remote.remote-containers","_lower":"ms-vscode-remote.remote-containers"}
```

**Comment by aleksanderostrup** [comment]
I think that it might be related to permission rights, but I'm not sure.

Are all the Dockerfile commands being executed as root? Or maybe this has changed, which is the cause of the problem.

**Comment by alexnfsc175** [comment]
@aleksanderostrup I'm running my containers without root privileges, with  [Rootless Podman](https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md), I can't tell from the error messages if it's a permissions problem, the error I can see in the console is this: `Error: Missing node-pty`
Is there any way to debug this kind of problem?

**Comment by aleksanderostrup** [comment]
Not that I know of. Hopefully one of the devs will take a look at this in due time.

**Comment by chrmarti** [comment]
The base images now pass down the `"remoteUser"` config (among other properties). Try setting it explicitly to `root` if you don't set it in your devcontainer.json to some other user by adding `"remoteUser": "root"`. Does that help?
