### ISSUE TITLE
Cannot open dev container: Invalid template on MacOS 12.6

### ISSUE THREAD

**Issue by jiayi-ren** [microsoft/vscode-remote-release#7360]
- VSCode Version: 1.72.1
- Local OS Version: macOS Monterey 12.6
- Remote OS Version:
- Remote Extension/Connection Type: Dev Containers v0.255.3
- Logs:

[60240123 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[60240246 ms] 1.41
[60240289 ms] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/abc/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.3/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /Users/abc/Desktop/project --log-level debug --log-format json --config /Users/abc/Desktop/project/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true
[60240670 ms] (node:45831) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[60240671 ms] (Use `Code Helper --trace-deprecation ...` to show where the warning was created)
[60240675 ms] @devcontainers/cli 0.20.0. Node.js v16.14.2. darwin 21.6.0 x64.
[60240675 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/abc/Desktop/project
[60240803 ms] Start: Run: docker-compose version --short
[60240838 ms] Docker Compose version: 2.11.0
[60240838 ms] Start: Run: docker-compose -f /Users/abc/Desktop/project/.devcontainer/docker-compose.devcontainer.yml --profile * config
[60240877 ms] 
[60240878 ms] Invalid template: "2&31ZrE$40nGFT57a#Zc@DeJSI1Bg19D"

[60240878 ms] Exit code 1
[60240878 ms] Error: Command failed: docker-compose -f /Users/abc/Desktop/project/.devcontainer/docker-compose.devcontainer.yml --profile * config
    at vc (/Users/abc/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.3/dist/spec-node/devContainersSpecCLI.js:1859:904)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async EO (/Users/abc/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.3/dist/spec-node/devContainersSpecCLI.js:1787:19035)
    at async _ae (/Users/abc/.vscode/extensions/ms-vscode-remote.remote-containers-0.255.3/dist/spec-node/devContainersSpecCLI.js:1994:26821)
[60240884 ms] Exit code 1

Steps to Reproduce:

1. After I upgraded to 12.6 Monterey, the dev container cannot be opened any more. I have tried clone the repo into several different directories but still wouldn't work.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Please see https://github.com/docker/compose-cli/issues/1896.
