### ISSUE TITLE
Cannot open in dev container after deleting dev_container_feature_content_temp

### ISSUE THREAD

**Issue by sqsp-rwatkins** [microsoft/vscode-remote-release#7384]
- VSCode Version: 1.72.2
- Local OS Version: macOS 12.5
- Logs:
```
[2022-10-19T13:31:27.127Z] Dev Containers 0.260.0 in VS Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075).
[2022-10-19T13:31:27.127Z] Start: Resolving Remote
[2022-10-19T13:31:27.132Z] Setting up container for folder or workspace: /Users/rwatkins/sqsp-src/backstage
[2022-10-19T13:31:27.134Z] Start: Check Docker is running
[2022-10-19T13:31:27.134Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2022-10-19T13:31:27.208Z] Stop (74 ms): Run: docker version --format {{.Server.APIVersion}}
[2022-10-19T13:31:27.209Z] Server API version: 1.41
[2022-10-19T13:31:27.209Z] Stop (75 ms): Check Docker is running
[2022-10-19T13:31:27.209Z] Start: Run: docker volume ls -q
[2022-10-19T13:31:27.268Z] Stop (59 ms): Run: docker volume ls -q
[2022-10-19T13:31:27.277Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/rwatkins/sqsp-src/backstage --filter label=vsch.quality=stable
[2022-10-19T13:31:27.346Z] Stop (69 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/Users/rwatkins/sqsp-src/backstage --filter label=vsch.quality=stable
[2022-10-19T13:31:27.346Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/rwatkins/sqsp-src/backstage
[2022-10-19T13:31:27.410Z] Stop (64 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/rwatkins/sqsp-src/backstage
[2022-10-19T13:31:27.411Z] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/rwatkins/.vscode/extensions/ms-vscode-remote.remote-containers-0.260.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/rwatkins/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/rwatkins/sqsp-src/backstage --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/rwatkins/sqsp-src/backstage --log-level debug --log-format json --config /Users/rwatkins/sqsp-src/backstage/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-10-19T13:31:27.559Z] (node:18044) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2022-10-19T13:31:27.559Z] (Use `Code Helper --trace-deprecation ...` to show where the warning was created)
[2022-10-19T13:31:27.560Z] @devcontainers/cli 0.20.0. Node.js v16.14.2. darwin 21.6.0 arm64.
[2022-10-19T13:31:27.560Z] Start: Run: docker buildx version
[2022-10-19T13:31:27.662Z] Stop (102 ms): Run: docker buildx version
[2022-10-19T13:31:27.662Z] github.com/docker/buildx v0.9.1 ed00243a0ce2a0aee75311b06e32d33b44729689
[2022-10-19T13:31:27.662Z] 
[2022-10-19T13:31:27.662Z] Start: Resolving Remote
[2022-10-19T13:31:27.664Z] Start: Run: docker-compose version --short
[2022-10-19T13:31:27.753Z] Stop (89 ms): Run: docker-compose version --short
[2022-10-19T13:31:27.753Z] Docker Compose version: 2.10.2
[2022-10-19T13:31:27.753Z] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=backstage_devcontainer --filter label=com.docker.compose.service=app
[2022-10-19T13:31:27.822Z] Stop (69 ms): Run: docker ps -q -a --filter label=com.docker.compose.project=backstage_devcontainer --filter label=com.docker.compose.service=app
[2022-10-19T13:31:27.822Z] Start: Run: docker inspect --type container c4c486058f9f
[2022-10-19T13:31:27.886Z] Stop (64 ms): Run: docker inspect --type container c4c486058f9f
[2022-10-19T13:31:27.886Z] Start: Run: docker-compose -f /Users/rwatkins/sqsp-src/backstage/.devcontainer/docker-compose.yml --profile * config
[2022-10-19T13:31:27.982Z] Stop (96 ms): Run: docker-compose -f /Users/rwatkins/sqsp-src/backstage/.devcontainer/docker-compose.yml --profile * config
[2022-10-19T13:31:27.982Z] name: devcontainer
[REDACTED]
[2022-10-19T13:31:27.984Z] Start: Run: docker events --format {{json .}} --filter event=start
[2022-10-19T13:31:27.986Z] PersistedPath=/Users/rwatkins/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data, ContainerHasLabels=true
[2022-10-19T13:31:27.986Z] Container was created with these config files: /Users/rwatkins/sqsp-src/tmp/backstage/.devcontainer/docker-compose.yml,/Users/rwatkins/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1666179762262.yml,/Users/rwatkins/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1666179763086.yml
[2022-10-19T13:31:27.986Z] Restoring /Users/rwatkins/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1666179762262.yml from persisted storage
[2022-10-19T13:31:27.986Z] Restoring /Users/rwatkins/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1666179763086.yml from persisted storage
[2022-10-19T13:31:27.986Z] Start: Run: docker-compose --project-name backstage_devcontainer -f /Users/rwatkins/sqsp-src/backstage/.devcontainer/docker-compose.yml -f /Users/rwatkins/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1666179762262.yml -f /Users/rwatkins/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1666179763086.yml up -d --no-recreate
[2022-10-19T13:31:28.226Z] [+] Building 0.0s (0/0)                                                         
could not find /var/folders/mv/k9hfvhsj2l1fb87vxssq5c8h0000gp/T/devcontainercli/container-features/0.20.0-1666179761076: stat /var/folders/mv/k9hfvhsj2l1fb87vxssq5c8h0000gp/T/devcontainercli/container-features/0.20.0-1666179761076: no such file or directory
[2022-10-19T13:31:28.230Z] Stop (244 ms): Run: docker-compose --project-name backstage_devcontainer -f /Users/rwatkins/sqsp-src/backstage/.devcontainer/docker-compose.yml -f /Users/rwatkins/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1666179762262.yml -f /Users/rwatkins/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1666179763086.yml up -d --no-recreate
[2022-10-19T13:31:28.231Z] Error: Command failed: docker-compose --project-name backstage_devcontainer -f /Users/rwatkins/sqsp-src/backstage/.devcontainer/docker-compose.yml -f /Users/rwatkins/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1666179762262.yml -f /Users/rwatkins/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1666179763086.yml up -d --no-recreate
[2022-10-19T13:31:28.231Z]     at kse (/Users/rwatkins/.vscode/extensions/ms-vscode-remote.remote-containers-0.260.0/dist/spec-node/devContainersSpecCLI.js:1830:3088)
[2022-10-19T13:31:28.231Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-10-19T13:31:28.231Z]     at async _se (/Users/rwatkins/.vscode/extensions/ms-vscode-remote.remote-containers-0.260.0/dist/spec-node/devContainersSpecCLI.js:1812:2396)
[2022-10-19T13:31:28.231Z]     at async Xse (/Users/rwatkins/.vscode/extensions/ms-vscode-remote.remote-containers-0.260.0/dist/spec-node/devContainersSpecCLI.js:1874:2203)
[2022-10-19T13:31:28.231Z]     at async Uf (/Users/rwatkins/.vscode/extensions/ms-vscode-remote.remote-containers-0.260.0/dist/spec-node/devContainersSpecCLI.js:1874:3193)
[2022-10-19T13:31:28.231Z]     at async Cae (/Users/rwatkins/.vscode/extensions/ms-vscode-remote.remote-containers-0.260.0/dist/spec-node/devContainersSpecCLI.js:1994:10350)
[2022-10-19T13:31:28.231Z]     at async yae (/Users/rwatkins/.vscode/extensions/ms-vscode-remote.remote-containers-0.260.0/dist/spec-node/devContainersSpecCLI.js:1994:10104)
[2022-10-19T13:31:28.232Z] Stop (821 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/rwatkins/.vscode/extensions/ms-vscode-remote.remote-containers-0.260.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/rwatkins/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/rwatkins/sqsp-src/backstage --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/rwatkins/sqsp-src/backstage --log-level debug --log-format json --config /Users/rwatkins/sqsp-src/backstage/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-10-19T13:31:28.233Z] Exit code 1
[2022-10-19T13:31:28.234Z] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/rwatkins/.vscode/extensions/ms-vscode-remote.remote-containers-0.260.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/rwatkins/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/rwatkins/sqsp-src/backstage --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/rwatkins/sqsp-src/backstage --log-level debug --log-format json --config /Users/rwatkins/sqsp-src/backstage/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-10-19T13:31:28.234Z] Exit code 1

```
Steps to Reproduce:

1. docker rmi dev_container_feature_content_temp
2. Open repo in Dev Container

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Haven't tried

When I run the command `docker-compose --project-name backstage_devcontainer -f /Users/rwatkins/sqsp-src/backstage/.devcontainer/docker-compose.yml -f /Users/rwatkins/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1666179762262.yml -f /Users/rwatkins/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1666179763086.yml up -d --no-recreate` locally it errors out. I believe this is because there is a space in `Application Support` so it sees `Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1666179763086.yml` as a command

**Comment by KarstenB** [comment]
I just encountered a very similar issue, but the path did not contain any spaces. Instead it was caused by docker caching an error.
```
 docker build -t dev_container_feature_content_temp -f /var/folders/fh/43zg053s47v0k5jwwywpff7c0000gn/T/devcontainercli/container-features/0.20.0-1666471972034/Dockerfile.buildContent /var/folders/fh/43zg053s47v0k5jwwywpff7c0000gn/T/devcontainercli/container-features/0.20.0-1666471972034
[+] Building 0.1s (5/5) FINISHED
 => [internal] load build definition from Dockerfile.buildContent                                                               0.0s
 => => transferring dockerfile: 49B                                                                                             0.0s
 => [internal] load .dockerignore                                                                                               0.0s
 => => transferring context: 2B                                                                                                 0.0s
 => [internal] load build context                                                                                               0.0s
 => => transferring context: 1.61kB                                                                                             0.0s
 => CACHED [1/1] COPY . /tmp/build-features/                                                                                    0.0s
 => ERROR exporting to image                                                                                                    0.0s
 => => exporting layers
 ```
Running the command with --no-cache and thus creating the dev_container_feature_content_temp helped to get my vscode  up and running again. I don't know if those 2 error descriptions are the same error, or different. But maybe it helps someone.

**Comment by chrmarti** [comment]
Not sure these two errors are from the same problem. @sqsp-rwatkins Does rebuilding the container make it work again?

**Comment by sqsp-rwatkins** [comment]
@chrmarti Can you provide some steps to rebuild it, please? I can't see any build commands in the log.
I've tried reinstalling the extension but it didn't work

**Comment by chrmarti** [comment]
`F1` > `Dev Containers: Rebuild Container` / `F1` > `Dev Containers: Rebuild and Reopen Container` should do that.

**Comment by sqsp-rwatkins** [comment]
@chrmarti Sorry for the late reply.
That's fixed it. Thanks for the help
