### ISSUE TITLE
win 11 not support?

### ISSUE THREAD

**Issue by kuohsu228** [microsoft/vscode-remote-release#7386]
🚨 The issue tracker is not for questions 🚨

If you have a question about VS Code, please ask it on https://stackoverflow.com/questions/tagged/visual-studio-code and about
VS Code Remote on https://stackoverflow.com/questions/tagged/vscode-remote.

can't connect to my college server after upgrading my pc to win11

[00:37:42.740] > bash: powershell: command not found
[00:37:44.041] "install" terminal command done
[00:37:44.042] Install terminal quit with output: bash: powershell: command not found
[00:37:44.042] Received install output: bash: powershell: command not found
[00:37:44.042] Failed to parse remote port from server output
[00:37:44.042] Resolver error: Error: 
	at g.Create (c:\Users\kk3kk\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:585222)
	at t.handleInstallOutput (c:\Users\kk3kk\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:583874)
	at t.tryInstall (c:\Users\kk3kk\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:681023)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\kk3kk\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:643908
	at async t.withShowDetailsEvent (c:\Users\kk3kk\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:647224)
	at async t.resolve (c:\Users\kk3kk\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:644958)
	at async c:\Users\kk3kk\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:726917
[00:37:44.045] ------

[00:37:44.109] ------

[00:37:44.109] SSH Resolver called for "ssh-remote+access.engr.oregonstate.edu", attempt 2, (Reconnection)
[00:37:44.110] SSH Resolver called for host: access.engr.oregonstate.edu
[00:37:44.110] Setting up SSH remote "access.engr.oregonstate.edu"
[00:37:44.111] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[00:37:44.113] Install and start server if needed
[00:37:48.982] getPlatformForHost was canceled
[00:37:48.982] Resolver error: Error: Connecting was canceled
	at g.Canceled (c:\Users\kk3kk\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:585418)
	at c:\Users\kk3kk\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:643820
	at async t.withShowDetailsEvent (c:\Users\kk3kk\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:647224)
	at async t.resolve (c:\Users\kk3kk\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:644958)
	at async c:\Users\kk3kk\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:726917
[00:37:48.983] ------

[00:37:48.984] ------

[00:37:48.984] SSH Resolver called for "ssh-remote+access.engr.oregonstate.edu", attempt 3, (Reconnection)
[00:37:48.985] SSH Resolver called for host: access.engr.oregonstate.edu
[00:37:48.985] Setting up SSH remote "access.engr.oregonstate.edu"
[00:37:48.986] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[00:37:48.988] Install and start server if needed

**Comment by eleanorjboyd** [comment]
Hello! Could you please provide the entire remote-ssh logs? The whole logs includes some settings which are helpful to the debugging process. Feel free to remove any confidential information as you see fit but the logs are most helpful when they are verbose so include as much as possible. Thanks!

**Comment by kuohsu228** [comment]
> Hello! Could you please provide the entire remote-ssh logs? The whole logs includes some settings which are helpful to the debugging process. Feel free to remove any confidential information as you see fit but the logs are most helpful when they are verbose so include as much as possible. Thanks!



> Hello! Could you please provide the entire remote-ssh logs? The whole logs includes some settings which are helpful to the debugging process. Feel free to remove any confidential information as you see fit but the logs are most helpful when they are verbose so include as much as possible. Thanks!

This is basically everything that shows on the terminal after it gets the error. Before this just I tried to enter my password to log in to the server. And it looks fine because I can see my account id and do the verification code.

**Comment by valord577** [comment]
Can you print your environment variable PTAH? 

Like: https://github.com/microsoft/vscode-remote-release/issues/7380#issuecomment-1286389327

**Comment by eleanorjboyd** [comment]
Hello! Is this issue still occuring? If so in the logs there should be a line that includes the sshArgs or ssh command we are running, if you use vscode insiders the logs will have `Running ssh connection command` followed by the full command. If you could try running this from a local terminal and make sure that works and let me know that would be great. Along with providing that ssh command it is attempting.
