### ISSUE TITLE
Remote SSH Fails during server installation on remote 

### ISSUE THREAD

**Issue by martema** [microsoft/vscode-remote-release#7389]
Type: <b>Bug</b>

VSCode version:  1.72.2
Local OS version: Windows 10
Remote OS Version: Ubuntu 20.04.3 LTS (Focal Fossa) 
Remote Extension/Connection Type: Remote - SSH
Step to reproduce : Open new connection to a server and select Linux
Terminal output:

[15:16:23.995] Log Level: 2
[15:16:23.996] remote-ssh@0.90.1
[15:16:23.996] win32 x64
[15:16:24.005] SSH Resolver called for "ssh-remote+192.168.7.218", attempt 1
[15:16:24.005] "remote.SSH.useLocalServer": false
[15:16:24.005] "remote.SSH.showLoginTerminal": false
[15:16:24.006] "remote.SSH.remotePlatform": {}
[15:16:24.006] "remote.SSH.path": undefined
[15:16:24.006] "remote.SSH.configFile": undefined
[15:16:24.006] "remote.SSH.useFlock": true
[15:16:24.006] "remote.SSH.lockfilesInTmp": false
[15:16:24.006] "remote.SSH.localServerDownload": auto
[15:16:24.006] "remote.SSH.remoteServerListenOnSocket": false
[15:16:24.006] "remote.SSH.showLoginTerminal": false
[15:16:24.006] "remote.SSH.defaultExtensions": []
[15:16:24.006] "remote.SSH.loglevel": 2
[15:16:24.006] "remote.SSH.enableDynamicForwarding": true
[15:16:24.007] "remote.SSH.enableRemoteCommand": false
[15:16:24.007] "remote.SSH.serverPickPortsFromRange": {}
[15:16:24.007] "remote.SSH.serverInstallPath": {}
[15:16:24.021] SSH Resolver called for host: 192.168.7.218
[15:16:24.021] Setting up SSH remote "192.168.7.218"
[15:16:24.028] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[15:16:24.033] Install and start server if needed
[15:16:25.938] Checking ssh with "ssh -V"
[15:16:25.970] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[15:16:25.975] Running script with connection command: ssh -T -D 60309 "192.168.7.218" bash
[15:16:25.977] Terminal shell path: C:\Windows\System32\cmd.exe
[15:16:26.191] > ]0;C:\Windows\System32\cmd.exe
[15:16:26.191] Got some output, clearing connection timeout
[15:16:27.967] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[15:16:50.452] > client_loop: send disconnect: Connection reset
[15:16:51.751] "install" terminal command done
[15:16:51.751] Install terminal quit with output: client_loop: send disconnect: Connection reset
[15:16:51.751] Received install output: client_loop: send disconnect: Connection reset
[15:16:51.752] Failed to parse remote port from server output
[15:16:51.753] Resolver error: Error: 
	at g.Create (c:\Users\Martina\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:585222)
	at t.handleInstallOutput (c:\Users\Martina\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:583874)
	at t.tryInstall (c:\Users\Martina\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:681023)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\Martina\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:643908
	at async t.withShowDetailsEvent (c:\Users\Martina\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:647224)
	at async t.resolve (c:\Users\Martina\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:644958)
	at async c:\Users\Martina\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:726917
[15:16:51.758] ------

[15:16:51.860] ------

[15:16:51.860] SSH Resolver called for "ssh-remote+192.168.7.218", attempt 2, (Reconnection)
[15:16:51.861] SSH Resolver called for host: 192.168.7.218
[15:16:51.861] Setting up SSH remote "192.168.7.218"
[15:16:51.863] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[15:16:51.866] Install and start server if needed
[15:16:53.401] getPlatformForHost was canceled
[15:16:53.401] Resolver error: Error: Connecting was canceled
	at g.Canceled (c:\Users\Martina\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:585418)
	at c:\Users\Martina\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:643820
	at async t.withShowDetailsEvent (c:\Users\Martina\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:647224)
	at async t.resolve (c:\Users\Martina\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:644958)
	at async c:\Users\Martina\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:726917
[15:16:53.403] ------

[15:16:53.410] ------

[15:16:53.410] SSH Resolver called for "ssh-remote+192.168.7.218", attempt 3, (Reconnection)
[15:16:53.411] SSH Resolver called for host: 192.168.7.218
[15:16:53.411] Setting up SSH remote "192.168.7.218"
[15:16:53.412] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[15:16:53.414] Install and start server if needed

Extension version: 0.90.1
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1690)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.74GB (19.84GB free)|
|Process Argv|--crash-reporter-id 76a1e77c-b407-4356-a6fa-158fb5aafbbe|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
nodejswelcome1:30587005
40g7c324:30573242
vscutilityc:30590830

```

</details>

**Comment by eleanorjboyd** [comment]
Hello! Does it work for you to connect to the server from the command line? Also once the connection is made are you able to do `echo hello` to the server and get a response? Thanks

**Comment by martema** [comment]
Hello. It works to connect from the command line, both from an external terminal and from VSCode terminal. I can also get a response to "echo hello". The problem happens only using Remote-SSH.

**Comment by eleanorjboyd** [comment]
Also are these the full logs or were there additional lines between [15:16:27.967] > and [15:16:50.452]>? The issue might be in those lines and they might help me debug further- thanks!

**Comment by martema** [comment]
That is the complete output on the console. When the connection fails the first time it retries, asking me again on the command palette input to insert the type of server (Linux, Microsoft..). This might be the reason for the idle time in the log.

**Comment by eleanorjboyd** [comment]
Could you see if adding this to your user settings fixes the problem? "remote.SSH.remotePlatform": { "YOUR_HOSTNAME": "windows" }
