### ISSUE TITLE
"invalid windows mount type: 'bind'" when opening a windows directory in a container

### ISSUE THREAD

**Issue by beirtipol** [microsoft/vscode-remote-release#7394]
Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No

- VSCode Version: 1.72.2
- Local OS Version: Windows 11 Pro
- Remote OS Version: Docker Engine 20.10.18 (Installed using Chocolatey. Not using Docker Desktop)
- Remote Extension/Connection Type: SSH/Containers/WSL/Server
- Logs:
```
[82 ms] Dev Containers 0.255.4 in VS Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075).
[82 ms] Start: Resolving Remote
[98 ms] Setting up container for folder or workspace: c:\dev\source\python-helloworld
[101 ms] Start: Check Docker is running
[101 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[170 ms] Server API version: 1.41
[171 ms] Start: Run: docker volume ls -q
[243 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=c:\dev\source\python-helloworld --filter label=vsch.quality=stable
[312 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\dev\source\python-helloworld
[377 ms] Start: Run: C:\Users\beirt\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\beirt\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\beirt\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder c:\dev\source\python-helloworld --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\dev\source\python-helloworld --log-level debug --log-format json --config c:\dev\source\python-helloworld\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[569 ms] (node:2496) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[569 ms] (Use `Code --trace-deprecation ...` to show where the warning was created)
[571 ms] @devcontainers/cli 0.20.0. Node.js v16.14.2. win32 10.0.22000 x64.
[571 ms] Start: Run: docker buildx version
[727 ms] github.com/docker/buildx v0.9.1 ed00243a0ce2a0aee75311b06e32d33b44729689
[727 ms] 
[727 ms] Start: Resolving Remote
[729 ms] Start: Run: git rev-parse --show-cdup
[733 ms] findLocalWindowsExecutable: Exectuable 'git' not found on PATH 'C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PowerShell\7\;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet\;C:\Users\beirt\AppData\Local\Microsoft\WindowsApps;;C:\Users\beirt\AppData\Local\Programs\Microsoft VS Code\bin'.
[735 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\dev\source\python-helloworld
[804 ms] Start: Run: docker inspect --type image mcr.microsoft.com/vscode/devcontainers/python:0-3.10-bullseye
[1179 ms] local container features stored at: c:\Users\beirt\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\node_modules\vscode-dev-containers\container-features
[1190 ms] Start: Run: tar --no-same-owner -x -f -
[1229 ms] Start: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\beirt\AppData\Local\Temp\devcontainercli\container-features\0.20.0-1666442914132\Dockerfile-with-features -t vsc-python-helloworld-bf28ea87bd4af983df95d1ad6037cb7a --target dev_containers_target_stage --build-arg VARIANT=3.10-bullseye --build-arg NODE_VERSION=lts/* --build-context dev_containers_feature_content_source=C:\Users\beirt\AppData\Local\Temp\devcontainercli\container-features\0.20.0-1666442914132 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp c:\dev\source\python-helloworld
2022/10/22 13:48:34 http2: server: error reading preface from client //./pipe/do
cker_engine: file has already been closed
[+] Building 0.1s (2/2) FINISHED
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 4.66kB                                     0.0s
 => [internal] load .dockerignore                                          0.1s
 => => transferring context: 2B                                            0.0s
ERROR: failed to solve: rpc error: code = Unknown desc = failed to solve with fr
ontend dockerfile.v0: failed to read dockerfile: failed to mount in-place: {bind
 C:\ProgramData\docker\windowsfilter\s3f8khtz6nhqt7cq6p71yqx1y [rbind ro]}: inva
lid windows mount type: 'bind'
[1593 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\beirt\AppData\Local\Temp\devcontainercli\container-features\0.20.0-1666442914132\Dockerfile-with-features -t vsc-python-helloworld-bf28ea87bd4af983df95d1ad6037cb7a --target dev_containers_target_stage --build-arg VARIANT=3.10-bullseye --build-arg NODE_VERSION=lts/* --build-context dev_containers_feature_content_source=C:\Users\beirt\AppData\Local\Temp\devcontainercli\container-features\0.20.0-1666442914132 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp c:\dev\source\python-helloworld
[1594 ms]     at Vse (c:\Users\beirt\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js:1869:1635)
[1594 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[1594 ms]     at async ZA (c:\Users\beirt\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js:1868:1973)
[1594 ms]     at async jO (c:\Users\beirt\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js:1868:901)
[1594 ms]     at async Xse (c:\Users\beirt\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js:1874:2030)
[1594 ms]     at async Uf (c:\Users\beirt\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js:1874:3193)
[1594 ms]     at async Cae (c:\Users\beirt\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js:1994:10350)
[1594 ms]     at async yae (c:\Users\beirt\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js:1994:10104)
[1604 ms] Exit code 1
[1606 ms] Command failed: C:\Users\beirt\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\beirt\.vscode\extensions\ms-vscode-remote.remote-containers-0.255.4\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\beirt\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder c:\dev\source\python-helloworld --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\dev\source\python-helloworld --log-level debug --log-format json --config c:\dev\source\python-helloworld\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[1606 ms] Exit code 1

```
devcontainer.json
```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.245.2/containers/python-3
{
	"name": "Python 3",
	"build": {
		"dockerfile": "Dockerfile",
		"context": "..",
		"args": { 
			// Update 'VARIANT' to pick a Python version: 3, 3.10, 3.9, 3.8, 3.7, 3.6
			// Append -bullseye or -buster to pin to an OS version.
			// Use -bullseye variants on local on arm64/Apple Silicon.
			"VARIANT": "3.10-bullseye",
			// Options
			"NODE_VERSION": "lts/*"
		}
	},

	// Configure tool-specific properties.
	"customizations": {
		// Configure properties specific to VS Code.
		"vscode": {
			// Set *default* container specific settings.json values on container create.
			"settings": { 
				"python.defaultInterpreterPath": "/usr/local/bin/python",
				"python.linting.enabled": true,
				"python.linting.pylintEnabled": true,
				"python.formatting.autopep8Path": "/usr/local/py-utils/bin/autopep8",
				"python.formatting.blackPath": "/usr/local/py-utils/bin/black",
				"python.formatting.yapfPath": "/usr/local/py-utils/bin/yapf",
				"python.linting.banditPath": "/usr/local/py-utils/bin/bandit",
				"python.linting.flake8Path": "/usr/local/py-utils/bin/flake8",
				"python.linting.mypyPath": "/usr/local/py-utils/bin/mypy",
				"python.linting.pycodestylePath": "/usr/local/py-utils/bin/pycodestyle",
				"python.linting.pydocstylePath": "/usr/local/py-utils/bin/pydocstyle",
				"python.linting.pylintPath": "/usr/local/py-utils/bin/pylint"
			},
			
			// Add the IDs of extensions you want installed when the container is created.
			"extensions": [
				"ms-python.python",
				"ms-python.vscode-pylance"
			]
		}
	},

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "pip3 install --user -r requirements.txt",

	// Comment out to connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
	"remoteUser": "vscode"
}

```

Command which is erroring:
```
C:\Windows\system32>docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\beirt\AppData\Local\Temp\devcontainercli\container-features\0.20.0-1666442914132\Dockerfile-with-features -t vsc-python-helloworld-bf28ea87bd4af983df95d1ad6037cb7a --target dev_containers_target_stage --build-arg VARIANT=3.10-bullseye --build-arg NODE_VERSION=lts/* --build-context dev_containers_feature_content_source=C:\Users\beirt\AppData\Local\Temp\devcontainercli\container-features\0.20.0-1666442914132 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp c:\dev\source\python-helloworld
2022/10/22 13:57:03 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
[+] Building 0.1s (2/2) FINISHED
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load build definition from Dockerfile-with-features                                                 0.1s
 => => transferring dockerfile: 46B                                                                                0.0s
ERROR: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to mount in-place: {bind C:\ProgramData\docker\windowsfilter\s3f8khtz6nhqt7cq6p71yqx1y [rbind ro]}: invalid windows mount type: 'bind'
```

Steps to Reproduce:

1. Clean Install of Windows 11 Pro, VSCode, Docker
2. Install Remote Development Extension pack
3. Open a windows directory in a container, using the default Python 3 environment (also attempted alpine, same error)

Troubleshooting steps attempted after some research:
1. Disable buildkit in the daemon.json and restart the docker engine
```
{
    "group":  "docker-users",
    "features": {
        "buildkit": false
    }
}

```
2. Run the failing command in commandline, same error present
3. Run the failing command in commandline as administrator, same error present
4. Confirmed that I can start any other docker container without issue.
5. Run VSCode as an administrator

**Comment by beirtipol** [comment]
I've also tried on a Windows 10 Pro machine. I get a very similar but slightly different error:

```
docker: Error response from daemon: invalid mount config for type "bind": invalid mount path: 'c:/dev/source/python-helloworld' mount path must be absolute.
```

**Comment by beirtipol** [comment]
Have found a workaround. I spotted on the Remote Containers homepage that only Docker Desktop is supported. I uninstalled docker completely (I had installed docker-engine and cli from chocolatey) and installed the latest docker desktop. That does seem to work ok.

I can't find any docs on the web on how to enable windows bind mounts using the standalone docker engine, so I guess I'll have to go back to using Docker Desktop for now! Would be great if someone could figure this out though

**Comment by beirtipol** [comment]
Conifrmed that Docker Desktop does work on both Windows 10 and 11 pro. I'll leave this issue open though as it would be good to get guidance on if it's possible to support the standalone docker-engine as in a work setting, I don't use Docker Desktop

**Comment by chrmarti** [comment]
Can the chocolatey-installed Docker CLI run containers that bind mount a Windows folder? (Maybe only the build context can't be bind mounted on a Windows folder?)

**Comment by chrmarti** [comment]
I think Docker Desktop is using WSL's mount points for the Windows filesystem to access these. Its CLI on the Windows side probably maps Windows paths to WSL paths.

If you don't want to use Docker Desktop, you could also install the Docker CLI into your WSL distro and enable `Execute In WSL` for Dev Containers in VS Code's user settings:
<img width="915" alt="image" src="https://user-images.githubusercontent.com/9205389/198545803-c54f7500-55bc-45ff-911b-78562ccb8046.png">
