### ISSUE TITLE
macos not compatible ?

### ISSUE THREAD

**Issue by shams-mac-m1** [microsoft/vscode-remote-release#7398]
- VSCode Version:1.73.0-insider (Universal)
- Local OS Version:mac os 12
- Remote OS Version: ubuntu 22
- Remote Extension/Connection Type: SSH
- Logs:[21:31:10.058] SSH Resolver called for "ssh-remote+141.145.195.252", attempt 4, (Reconnection)
[21:31:10.062] SSH Resolver called for host: 141.145.195.252
[21:31:10.062] Setting up SSH remote "141.145.195.252"
[21:31:10.064] Acquiring local install lock: /var/folders/x3/5tlgfvnn5_v7m37h1z08ljf00000gn/T/vscode-remote-ssh-3f3568e5-install.lock
[21:31:10.065] Looking for existing server data file at /Users/shams/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-3f3568e5-504c5a768a001b2099dd2b44e9dc39e10ccdfb56-0.90.1/data.json
[21:31:10.066] Using commit id "504c5a768a001b2099dd2b44e9dc39e10ccdfb56" and quality "insider" for server
[21:31:10.071] Install and start server if needed
[21:31:10.100] askpass server listening on /var/folders/x3/5tlgfvnn5_v7m37h1z08ljf00000gn/T/vscode-ssh-askpass-4dbe9867e955ad4e1b0f92188ad62f6dfd145e4a.sock
[21:31:10.101] Spawning local server with {"serverId":4,"ipcHandlePath":"/var/folders/x3/5tlgfvnn5_v7m37h1z08ljf00000gn/T/vscode-ssh-askpass-f3efa9bf734c8f51b98e6e2f27c239564d268db5.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","50914","-o","ConnectTimeout=15","141.145.195.252"],"serverDataFolderName":".vscode-server-insiders","dataFilePath":"/Users/shams/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-3f3568e5-504c5a768a001b2099dd2b44e9dc39e10ccdfb56-0.90.1/data.json"}
[21:31:10.101] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.JjaGe6laFU/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/x3/5tlgfvnn5_v7m37h1z08ljf00000gn/T/vscode-ssh-askpass-4dbe9867e955ad4e1b0f92188ad62f6dfd145e4a.sock"}
[21:31:10.103] Spawned 3013
[21:31:10.364] > local-server-4> Spawned ssh, pid=3016
[21:31:10.368] stderr> OpenSSH_8.6p1, LibreSSL 3.3.6
[21:31:10.368] stderr> /Users/shams/.ssh/config line 5: missing argument.
[21:31:10.368] stderr> /Users/shams/.ssh/config line 5: unsupported option "(null)".
[21:31:10.368] stderr> /Users/shams/.ssh/config: line 6: Bad configuration option: askpassgui
[21:31:10.368] stderr> /Users/shams/.ssh/config: terminating, 2 bad configuration options
[21:31:10.369] > local-server-4> ssh child died, shutting down
[21:31:10.374] Local server exit: 0
[21:31:10.374] Received install output: local-server-4> Spawned ssh, pid=3016
OpenSSH_8.6p1, LibreSSL 3.3.6
/Users/shams/.ssh/config line 5: missing argument.
/Users/shams/.ssh/config line 5: unsupported option "(null)".
/Users/shams/.ssh/config: line 6: Bad configuration option: askpassgui
/Users/shams/.ssh/config: terminating, 2 bad configuration options
local-server-4> ssh child died, shutting down

[21:31:10.375] Failed to parse remote port from server output
[21:31:10.376] Resolver error: Error: 
	at g.Create (/Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:585222)
	at t.handleInstallOutput (/Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:583874)
	at Object.e [as tryInstallWithLocalServer] (/Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:624373)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:643506
	at async t.withShowDetailsEvent (/Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:647224)
	at async /Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:622845
	at async T (/Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:619351)
	at async t.resolveWithLocalServer (/Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:622460)
	at async t.resolve (/Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:644834)
	at async /Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:726917
[21:31:10.379] ------

[21:31:10.389] ------

[21:31:10.389] SSH Resolver called for "ssh-remote+141.145.195.252", attempt 5, (Reconnection)
[21:31:10.392] SSH Resolver called for host: 141.145.195.252
[21:31:10.392] Setting up SSH remote "141.145.195.252"
[21:31:10.393] Acquiring local install lock: /var/folders/x3/5tlgfvnn5_v7m37h1z08ljf00000gn/T/vscode-remote-ssh-3f3568e5-install.lock
[21:31:10.394] Looking for existing server data file at /Users/shams/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-3f3568e5-504c5a768a001b2099dd2b44e9dc39e10ccdfb56-0.90.1/data.json
[21:31:10.394] Using commit id "504c5a768a001b2099dd2b44e9dc39e10ccdfb56" and quality "insider" for server
[21:31:10.397] Install and start server if needed
[21:31:10.403] askpass server listening on /var/folders/x3/5tlgfvnn5_v7m37h1z08ljf00000gn/T/vscode-ssh-askpass-af92b343854779ce0eb32d54e683e889f4d7cafe.sock
[21:31:10.404] Spawning local server with {"serverId":5,"ipcHandlePath":"/var/folders/x3/5tlgfvnn5_v7m37h1z08ljf00000gn/T/vscode-ssh-askpass-3cdf3a553fa57f5404ecd7173439b705f39dab85.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","50915","-o","ConnectTimeout=15","141.145.195.252"],"serverDataFolderName":".vscode-server-insiders","dataFilePath":"/Users/shams/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-3f3568e5-504c5a768a001b2099dd2b44e9dc39e10ccdfb56-0.90.1/data.json"}
[21:31:10.404] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.JjaGe6laFU/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/x3/5tlgfvnn5_v7m37h1z08ljf00000gn/T/vscode-ssh-askpass-af92b343854779ce0eb32d54e683e889f4d7cafe.sock"}
[21:31:10.406] Spawned 3017
[21:31:10.633] > local-server-5> Spawned ssh, pid=3019
[21:31:10.637] stderr> OpenSSH_8.6p1, LibreSSL 3.3.6
[21:31:10.638] stderr> /Users/shams/.ssh/config line 5: missing argument.
[21:31:10.638] stderr> /Users/shams/.ssh/config line 5: unsupported option "(null)".
[21:31:10.638] stderr> /Users/shams/.ssh/config: line 6: Bad configuration option: askpassgui
[21:31:10.638] stderr> /Users/shams/.ssh/config: terminating, 2 bad configuration options
[21:31:10.639] > local-server-5> ssh child died, shutting down
[21:31:10.644] Local server exit: 0
[21:31:10.645] Received install output: local-server-5> Spawned ssh, pid=3019
OpenSSH_8.6p1, LibreSSL 3.3.6
/Users/shams/.ssh/config line 5: missing argument.
/Users/shams/.ssh/config line 5: unsupported option "(null)".
/Users/shams/.ssh/config: line 6: Bad configuration option: askpassgui
/Users/shams/.ssh/config: terminating, 2 bad configuration options
local-server-5> ssh child died, shutting down

[21:31:10.645] Failed to parse remote port from server output
[21:31:10.646] Resolver error: Error: 
	at g.Create (/Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:585222)
	at t.handleInstallOutput (/Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:583874)
	at Object.e [as tryInstallWithLocalServer] (/Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:624373)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:643506
	at async t.withShowDetailsEvent (/Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:647224)
	at async /Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:622845
	at async T (/Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:619351)
	at async t.resolveWithLocalServer (/Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:622460)
	at async t.resolve (/Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:644834)
	at async /Users/shams/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:726917
[21:31:10.648] ------

Steps to Reproduce:

1. set ssh file
2. try and ssh

**Comment by eleanorjboyd** [comment]
Hello! It seems there might be an issue with SSH not being able to understand your config file. I would check there and attempt to connect via SSH in your terminal and if you are able to connect via the terminal but still not via VS Code then let us know. Thanks!

> [21:31:10.368] stderr> /Users/shams/.ssh/config line 5: missing argument.
> [21:31:10.368] stderr> /Users/shams/.ssh/config line 5: unsupported option "(null)".
> [21:31:10.368] stderr> /Users/shams/.ssh/config: line 6: Bad configuration option: askpassgui
> [21:31:10.368] stderr> /Users/shams/.ssh/config: terminating, 2 bad configuration options
