### ISSUE TITLE
i can't connect remote ssh

### ISSUE THREAD

**Issue by kevin4dhd** [microsoft/vscode-remote-release#7415]
- VSCode Version: 1.72.2
- Logs:
[11:46:59.511] Log Level: 2
[11:46:59.512] remote-ssh@0.90.1
[11:46:59.512] win32 x64
[11:46:59.519] SSH Resolver called for "ssh-remote+node-id-10.runtime.openingerdevphp.zerops", attempt 1
[11:46:59.519] "remote.SSH.useLocalServer": false
[11:46:59.520] "remote.SSH.showLoginTerminal": false
[11:46:59.520] "remote.SSH.remotePlatform": {"Codify_Contabo":"linux","Jhamil-4":"linux","Jhamil-5":"linux","rara.tv":"linux","Jhamil-Contabo":"linux","Jhamil-6":"linux","KevinOneCore":"linux","Wapix":"linux","Jhamil-Dedicado":"linux","chatvideo_DEDICATE_SERVER":"linux","ryzen_chatvideo":"linux","Kevin":"linux","remixrun-indiestack-sef8hkziq3r":"linux"}
[11:46:59.520] "remote.SSH.path": undefined
[11:46:59.520] "remote.SSH.configFile": C:\Users\Usuario\.ssh\config
[11:46:59.520] "remote.SSH.useFlock": true
[11:46:59.520] "remote.SSH.lockfilesInTmp": false
[11:46:59.520] "remote.SSH.localServerDownload": auto
[11:46:59.520] "remote.SSH.remoteServerListenOnSocket": false
[11:46:59.520] "remote.SSH.showLoginTerminal": false
[11:46:59.521] "remote.SSH.defaultExtensions": ["gitpod.gitpod-remote-ssh"]
[11:46:59.521] "remote.SSH.loglevel": 2
[11:46:59.521] "remote.SSH.enableDynamicForwarding": true
[11:46:59.521] "remote.SSH.enableRemoteCommand": false
[11:46:59.521] "remote.SSH.serverPickPortsFromRange": {}
[11:46:59.521] "remote.SSH.serverInstallPath": {}
[11:46:59.534] SSH Resolver called for host: node-id-10.runtime.openingerdevphp.zerops
[11:46:59.534] Setting up SSH remote "node-id-10.runtime.openingerdevphp.zerops"
[11:46:59.537] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[11:46:59.540] Install and start server if needed
[11:47:01.850] Checking ssh with "ssh -V"
[11:47:01.877] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[11:47:01.880] Using SSH config file "C:\Users\Usuario\.ssh\config"
[11:47:01.881] Running script with connection command: ssh -T -D 1087 -F "C:\Users\Usuario\.ssh\config" "node-id-10.runtime.openingerdevphp.zerops" bash
[11:47:01.882] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[11:47:02.072] > ]0;C:\WINDOWS\System32\cmd.exe
[11:47:02.072] Got some output, clearing connection timeout
[11:47:04.716] "install" terminal command done
[11:47:04.717] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exe
[11:47:04.717] Received install output: ]0;C:\WINDOWS\System32\cmd.exe
[11:47:04.717] Failed to parse remote port from server output
[11:47:04.717] Resolver error: Error: 
	at g.Create (c:\Users\Usuario\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:585222)
	at t.handleInstallOutput (c:\Users\Usuario\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:583874)
	at t.tryInstall (c:\Users\Usuario\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:681023)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\Usuario\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:643908
	at async t.withShowDetailsEvent (c:\Users\Usuario\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:647224)
	at async t.resolve (c:\Users\Usuario\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:644958)
	at async c:\Users\Usuario\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:726917
[11:47:04.721] ------

[11:47:04.815] ------

[11:47:04.815] SSH Resolver called for "ssh-remote+node-id-10.runtime.openingerdevphp.zerops", attempt 2, (Reconnection)
[11:47:04.816] SSH Resolver called for host: node-id-10.runtime.openingerdevphp.zerops
[11:47:04.816] Setting up SSH remote "node-id-10.runtime.openingerdevphp.zerops"
[11:47:04.817] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[11:47:04.818] Install and start server if needed
[11:47:07.832] getPlatformForHost was canceled
[11:47:07.833] Resolver error: Error: Conexión cancelada
	at g.Canceled (c:\Users\Usuario\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:585418)
	at c:\Users\Usuario\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:643820
	at async t.withShowDetailsEvent (c:\Users\Usuario\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:647224)
	at async t.resolve (c:\Users\Usuario\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:644958)
	at async c:\Users\Usuario\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:726917
[11:47:07.836] ------

[11:47:07.854] ------

[11:47:07.854] SSH Resolver called for "ssh-remote+node-id-10.runtime.openingerdevphp.zerops", attempt 3, (Reconnection)
[11:47:07.856] SSH Resolver called for host: node-id-10.runtime.openingerdevphp.zerops
[11:47:07.856] Setting up SSH remote "node-id-10.runtime.openingerdevphp.zerops"
[11:47:07.857] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[11:47:07.859] Install and start server if needed
[11:53:06.967] getPlatformForHost was canceled
[11:53:06.968] Resolver error: Error: Conexión cancelada
	at g.Canceled (c:\Users\Usuario\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:585418)
	at c:\Users\Usuario\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:643820
	at async t.withShowDetailsEvent (c:\Users\Usuario\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:647224)
	at async t.resolve (c:\Users\Usuario\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:644958)
	at async c:\Users\Usuario\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:726917
[11:53:06.970] ------

[11:53:06.976] ------

[11:53:06.976] SSH Resolver called for "ssh-remote+node-id-10.runtime.openingerdevphp.zerops", attempt 4, (Reconnection)
[11:53:06.977] SSH Resolver called for host: node-id-10.runtime.openingerdevphp.zerops
[11:53:06.977] Setting up SSH remote "node-id-10.runtime.openingerdevphp.zerops"
[11:53:06.978] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[11:53:06.981] Install and start server if needed

Steps to Reproduce:

1.There is a server which I can connect to by ssh, so I connect by this command:
ssh -p 65437 node-id-10.runtime.openingerdevphp.zerops
I need to be connected to a VPN for ssh to work (wireguard) the problem is that when I try to connect via remote ssh it doesn't work
2.No password or IdentityFile is needed to enter, simply with that command above I can enter, my configuration is this:
![image](https://user-images.githubusercontent.com/22886367/197836090-6f7fd02f-162b-4e88-94b2-0944081a13b9.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by Mollylulu** [comment]
same error here 😭 Out of a sudden. I was using vscode with remote-ssh on the server, suddenly vscode pop up kind of xxx mismatch window, required me to relaunch vscode. I followed its instruction. However, after relaunch, I can not connect to the server any more. It just reporting the same error as above user.
<img width="253" alt="Snipaste_2022-10-27_20-58-28" src="https://user-images.githubusercontent.com/26273127/198290915-aa1bd87a-77f7-44cb-9dbe-81858ccbd5e5.png">

**Comment by Mollylulu** [comment]
Moreover, I delete the remote server `.vscode-server` directory, which does not work it out.

**Comment by eleanorjboyd** [comment]
Hello! Could you see if adding this to your user settings fixes the problem? `"remote.SSH.remotePlatform": { "YOUR_HOSTNAME": "windows" }`

**Comment by eleanorjboyd** [comment]
@Mollylulu could you include your full logs?

**Comment by Mollylulu** [comment]
I have deleted the vscode in my Mac 😂, the logged issue was the same as the above user's.  Waht's more, I redownload vscode and this problem just is solved.

**Comment by eleanorjboyd** [comment]
@Mollylulu I'm glad you found the issue! Happy coding 😄

**Comment by semiautomatix** [comment]
```
[21:28:42.168] Log Level: 2
[21:28:42.169] remote-ssh@0.90.1
[21:28:42.170] win32 x64
[21:28:42.197] SSH Resolver called for "ssh-remote+7b2275736572223a2273656d696175746f6d61742d736f6c69646a7364656d6f2d6c3476627a756736683535222c22686f73744e616d65223a2273656d696175746f6d61742d736f6c69646a7364656d6f2d6c3476627a7567366835352e7373682e77732d757337342e676974706f642e696f227d", attempt 1
[21:28:42.198] "remote.SSH.useLocalServer": false
[21:28:42.199] "remote.SSH.showLoginTerminal": true
[21:28:42.200] "remote.SSH.remotePlatform": {}
[21:28:42.200] "remote.SSH.path": undefined
[21:28:42.200] "remote.SSH.configFile": undefined
[21:28:42.201] "remote.SSH.useFlock": true
[21:28:42.201] "remote.SSH.lockfilesInTmp": false
[21:28:42.201] "remote.SSH.localServerDownload": auto
[21:28:42.202] "remote.SSH.remoteServerListenOnSocket": false
[21:28:42.202] "remote.SSH.showLoginTerminal": true
[21:28:42.203] "remote.SSH.defaultExtensions": ["gitpod.gitpod-remote-ssh"]
[21:28:42.203] "remote.SSH.loglevel": 2
[21:28:42.204] "remote.SSH.enableDynamicForwarding": true
[21:28:42.204] "remote.SSH.enableRemoteCommand": false
[21:28:42.204] "remote.SSH.serverPickPortsFromRange": {}
[21:28:42.205] "remote.SSH.serverInstallPath": {}
[21:28:42.208] SSH Resolver called for host: semiautomat-solidjsdemo-l4vbzug6h55@semiautomat-solidjsdemo-l4vbzug6h55.ssh.ws-us74.gitpod.io
[21:28:42.209] Setting up SSH remote "semiautomat-solidjsdemo-l4vbzug6h55.ssh.ws-us74.gitpod.io"
[21:28:42.219] Using commit id "8fa188b2b301d36553cbc9ce1b0a146ccb93351f" and quality "stable" for server
[21:28:42.224] Install and start server if needed
[21:28:43.863] Checking ssh with "ssh -V"
[21:28:43.901] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0
[21:28:43.902] > .2

[21:28:43.905] Remote command length: 6252/8192 characters
[21:28:43.906] Running script with connection command: ssh -T -D 52383 "semiautomat-solidjsdemo-l4vbzug6h55@semiautomat-solidjsdemo-l4vbzug6h55.ssh.ws-us74.gitpod.io" powershell
[21:28:43.907] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[21:28:44.236] > ]0;C:\WINDOWS\System32\cmd.exe
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[21:28:44.237] Got some output, clearing connection timeout
[21:28:45.257] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[21:28:47.607] "install" terminal command done
[21:28:47.607] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exe
[21:28:47.607] Received install output: ]0;C:\WINDOWS\System32\cmd.exe
[21:28:47.608] Failed to parse remote port from server output
[21:28:47.608] Resolver error: Error: 
	at g.Create (c:\Users\timga\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:585222)
	at t.handleInstallOutput (c:\Users\timga\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:583874)
	at t.tryInstall (c:\Users\timga\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:681023)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\timga\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:643908
	at async t.withShowDetailsEvent (c:\Users\timga\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:647224)
	at async t.resolve (c:\Users\timga\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:644958)
	at async c:\Users\timga\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:726917
[21:28:47.614] ------
```

Confirming a similar issue.

**Comment by eleanorjboyd** [comment]
@semiautomatix Does this issue occur when you try this locally?

**Comment by Drfengze** [comment]
`[12:07:41.239] Log Level: 2
[12:07:41.244] remote-ssh@0.88.0
[12:07:41.244] win32 x64
[12:07:41.250] SSH Resolver called for "ssh-remote+147.46.64.79", attempt 1
[12:07:41.250] "remote.SSH.useLocalServer": false
[12:07:41.250] "remote.SSH.showLoginTerminal": false
[12:07:41.250] "remote.SSH.remotePlatform": {"147.46.64.79":"linux"}
[12:07:41.250] "remote.SSH.path": undefined
[12:07:41.250] "remote.SSH.configFile": undefined
[12:07:41.251] "remote.SSH.useFlock": true
[12:07:41.251] "remote.SSH.lockfilesInTmp": false
[12:07:41.251] "remote.SSH.localServerDownload": auto
[12:07:41.251] "remote.SSH.remoteServerListenOnSocket": true
[12:07:41.251] "remote.SSH.showLoginTerminal": false
[12:07:41.251] "remote.SSH.defaultExtensions": []
[12:07:41.251] "remote.SSH.loglevel": 2
[12:07:41.251] "remote.SSH.enableDynamicForwarding": true
[12:07:41.251] "remote.SSH.enableRemoteCommand": false
[12:07:41.252] "remote.SSH.serverPickPortsFromRange": {}
[12:07:41.252] "remote.SSH.serverInstallPath": {}
[12:07:41.254] SSH Resolver called for host: 147.46.64.79
[12:07:41.254] Setting up SSH remote "147.46.64.79"
[12:07:41.259] Using commit id "6261075646f055b99068d3688932416f2346dd3b" and quality "stable" for server
[12:07:41.263] Install and start server if needed
[12:07:41.266] Checking ssh with "ssh -V"
[12:07:41.307] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[12:07:41.312] Running script with connection command: ssh -T -D 60187 "147.46.64.79" bash
[12:07:41.316] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[12:07:41.686] > huaize@147.46.64.79's password:]0;C:\WINDOWS\System32\cmd.exe
[12:07:41.687] Got some output, clearing connection timeout
[12:07:41.687] Showing password prompt
[12:07:49.046] Got password response
[12:07:49.046] "install" wrote data to terminal: "*************"
[12:07:49.088] > 
[12:07:49.307] > 494784635f32: running

> mkdir: cannot create directory ‘/home/huaize/.vscode-server’Creating the server install dir failed...
> 494784635f32: start
> exitCode==34==
> : No space left on device
> listeningOn====
> osReleaseId====
> arch====
> tmpDir==/run/user/1007==
> platform====
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 494784635f32: end
> [12:07:49.307] Received install output: 
> exitCode==34==
> : No space left on device
> listeningOn====
> osReleaseId====
> arch====
> tmpDir==/run/user/1007==
> platform====
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====

[12:07:49.308] Failed to parse remote port from server output
[12:07:49.309] Resolver error: Error: 
	at g.Create (c:\Users\usr\.vscode\extensions\ms-vscode-remote.remote-ssh-0.88.0\out\extension.js:1:583821)
	at t.handleInstallOutput (c:\Users\usr\.vscode\extensions\ms-vscode-remote.remote-ssh-0.88.0\out\extension.js:1:582473)
	at t.tryInstall (c:\Users\usr\.vscode\extensions\ms-vscode-remote.remote-ssh-0.88.0\out\extension.js:1:679699)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\usr\.vscode\extensions\ms-vscode-remote.remote-ssh-0.88.0\out\extension.js:1:642502
	at async t.withShowDetailsEvent (c:\Users\usr\.vscode\extensions\ms-vscode-remote.remote-ssh-0.88.0\out\extension.js:1:645820)
	at async t.resolve (c:\Users\usr\.vscode\extensions\ms-vscode-remote.remote-ssh-0.88.0\out\extension.js:1:643552)
	at async c:\Users\usr\.vscode\extensions\ms-vscode-remote.remote-ssh-0.88.0\out\extension.js:1:722230
[12:07:49.314] ------



[12:07:50.571] "install" terminal command done
[12:07:50.572] Install terminal quit with output: `

same issues, please help! I used `remote kill` and many methods, none working
please help @eleanorjboyd
