### ISSUE TITLE
"Error: Got bad result from install script" after a successfull auth

### ISSUE THREAD

**Issue by fxck** [microsoft/vscode-remote-release#7416]
"Connect to Host" seems to authenticate fine but crashes right after on the error shown below. I have no idea what could be causing this, it's connected as root and `serverInstallPath` has been set to a folder it has permission to.

- VSCode Version: Version: 1.72.2 (happens using latest insiders as well)
- Local OS Version: macOS 12.6 (21G115)
- Remote OS Version: Ubuntu 18.04.6 LTS (Bionic Beaver)
- Remote Extension/Connection Type: SSH
- Logs:
```
[18:52:21.269] SSH Resolver called for "ssh-remote+zeropsdevcontainer", attempt 5, (Reconnection)
[18:52:21.270] SSH Resolver called for host: zeropsdevcontainer
[18:52:21.270] Setting up SSH remote "zeropsdevcontainer"
[18:52:21.271] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[18:52:21.272] Install and start server if needed
[18:52:21.276] Running script with connection command: ssh -T -D 63337 -o ConnectTimeout=10000 zeropsdevcontainer bash
[18:52:22.034] "install" terminal command done
[18:52:22.034] Install terminal quit with output: 
[18:52:22.034] Resolver error: Error: Got bad result from install script
	at g.Create (/Users/fxck/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:585222)
	at t.tryInstall (/Users/fxck/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:680786)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/fxck/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:643908
	at async t.withShowDetailsEvent (/Users/fxck/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:647224)
	at async t.resolve (/Users/fxck/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:644958)
	at async /Users/fxck/.vscode/extensions/ms-vscode-remote.remote-ssh-0.90.1/out/extension.js:1:726917
```

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by fxck** [comment]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/1303561/197836983-69853473-88bc-40bc-b774-da0935ecf499.png">

developer tools show this error, which doesn't seem to be any more tangible than what vscode output shows

**Comment by fxck** [comment]
It was a problem on ssh server's side

**Comment by gante** [comment]
In case someone else has an identical traceback and stumbles upon this issue: 

I did a sequence of things, and while the **_last action_** fixed it, some intermediary steps might also be required. Actions: remove `.vscode-server` folder on remote -> kill existing `vscode-server` processes on remote -> downgrade Remote-SSH extension (to 0.78.0) -> upgrade Remote-SSH back to 0.90.1 -> uninstall unused extensions (namely, Liveshare was throwing exceptions) -> reboot remote -> **_restart vscode_**

**Comment by fxck** [comment]
The problem in my case was that the SSH server that I was using wasn't properly implementing heredocs, so the install command just ran the first line of the script, which was `bash` without anything else, so it succeed, but returned nothing, which the extension evaluated as bad result and failed.
