### ISSUE TITLE
Remote SSH Connection Suddenly Stopped Working

### ISSUE THREAD

**Issue by andrewjchang1509** [microsoft/vscode-remote-release#7426]
The remote ssh connection has been working fine until this Monday when it suddenly gave me errors. I did not change any setting. BUT THERE IS A WINDOWS UPDATE ON OCTOBER 24. I tried multiple solutions online including downgrade VS Code and Remote Explorer extension, removing .vscode-server folder on the remote server. None of them worked.
I can connect to the ssh server though Terminal window in VS Code, Putty, WinSCP but the Remote Explorer.

Extension version: 0.90.1
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (22.75GB free)|
|Process Argv|--crash-reporter-id 2ab9ae40-548d-4a66-9aff-d8ba4277a575|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
2e4cg342:30596373

```

</details>

VSCode Version: 1.72.2

[13:00:00.901] Log Level: 2
[13:00:00.902] remote-ssh@0.84.0
[13:00:00.902] win32 x64
[13:00:00.914] SSH Resolver called for "ssh-remote+scobig-analytics.com", attempt 1
[13:00:00.915] "remote.SSH.useLocalServer": false
[13:00:00.915] "remote.SSH.showLoginTerminal": false
[13:00:00.915] "remote.SSH.remotePlatform": {}
[13:00:00.916] "remote.SSH.path": undefined
[13:00:00.916] "remote.SSH.configFile": C:\Users\Andrew Chang\.ssh\config
[13:00:00.916] "remote.SSH.useFlock": true
[13:00:00.916] "remote.SSH.lockfilesInTmp": false
[13:00:00.916] "remote.SSH.localServerDownload": auto
[13:00:00.916] "remote.SSH.remoteServerListenOnSocket": false
[13:00:00.916] "remote.SSH.showLoginTerminal": false
[13:00:00.916] "remote.SSH.defaultExtensions": []
[13:00:00.917] "remote.SSH.loglevel": 2
[13:00:00.917] "remote.SSH.enableDynamicForwarding": true
[13:00:00.917] "remote.SSH.enableRemoteCommand": false
[13:00:00.917] "remote.SSH.serverPickPortsFromRange": {}
[13:00:00.917] "remote.SSH.serverInstallPath": {}
[13:00:00.932] SSH Resolver called for host: scobig-analytics.com
[13:00:00.932] Setting up SSH remote "scobig-analytics.com"
[13:00:00.946] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[13:00:00.948] Install and start server if needed
[13:00:02.486] Checking ssh with "ssh -V"
[13:00:02.518] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[13:00:02.521] Using SSH config file "C:\Users\Andrew Chang\.ssh\config"
[13:00:02.521] Running script with connection command: ssh -T -D 64683 -F "C:\Users\Andrew Chang\.ssh\config" "scobig-analytics.com" bash
[13:00:02.523] Terminal shell path: C:\windows\System32\cmd.exe
[13:00:02.702] > The filename, directory name, or volume label syntax is incorrect.
> ]0;C:\windows\System32\cmd.exe
[13:00:02.703] Got some output, clearing connection timeout
[13:00:03.984] "install" terminal command done
[13:00:03.984] Install terminal quit with output: ]0;C:\windows\System32\cmd.exe
[13:00:03.984] Received install output: ]0;C:\windows\System32\cmd.exe
[13:00:03.985] Failed to parse remote port from server output
[13:00:03.985] Resolver error: Error: 
	at g.Create (c:\Users\Andrew Chang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:585222)
	at t.handleInstallOutput (c:\Users\Andrew Chang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:583874)
	at t.tryInstall (c:\Users\Andrew Chang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:681023)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\Andrew Chang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:643908
	at async t.withShowDetailsEvent (c:\Users\Andrew Chang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:647224)
	at async t.resolve (c:\Users\Andrew Chang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:644958)
	at async c:\Users\Andrew Chang\.vscode\extensions\ms-vscode-remote.remote-ssh-0.84.0\out\extension.js:1:727082
[13:00:03.989] ------

Also, when I tried to Kill SSH Server on Host, there is a similar message like when I tried to connect to the SSH server:

The terminal process "C:\windows\System32\cmd.exe /c (type "C:\Users\ANDREW~1\AppData\Local\Temp\vscode-linux-multi-line-command-scobig-analytics.com-60488159.sh" | ssh -T -o ClearAllForwardings=true -F "C:\Users\Andrew Chang\.ssh\config" "scobig-analytics.com" bash) & exit /b 0" terminated with exit code: 255.

**Comment by andrewjchang1509** [comment]
Hi thank you, but it did not work.

**Comment by eleanorjboyd** [comment]
Hello! Could your problem be related to: https://github.com/microsoft/vscode-remote-release/issues/7324? We got a fix in which is currently on insiders. Sorry for the delay and let me know if your issue has already been fixed either way. Thanks!

**Comment by eleanorjboyd** [comment]
Hello! With the new remote-ssh release, version 0.94.0, this should now be on stable and you can try it there. Thanks and let me know if it is still causing issues.
