### ISSUE TITLE
Could not establish connection to Host | exit code:255

### ISSUE THREAD

**Issue by purnasai-cyient** [microsoft/vscode-remote-release#7432]
I am getting an Error when I tried to connect to Azure VM using VSCode. I gave ssh Config, that looks like:
```
Host SampleHost
  HostName 123.123.123.123
  User Usernamehere
  IdentityFile pathto.pemfiehere
```
I got a pop-up that says, `The terminal process terminated with exit code:255`.
Another pop-up says, `Could not establish the connection to Host`

os: windows
vscode version:1.72.2
remote_ssh extension: recent

I also tried uninstalling extensions `remote-ssh` and `python`, but nothing worked. 

But the process worked on My Colleague's laptop, who tried the same procedure and connected to VM. We have the same OS&Extensions. 
Also when I tried Connecting to VM through putty, I am able to connect. I Tried all possible solutions from Net, but didn't work.

Any help is appreciated. Thanks

**Comment by eleanorjboyd** [comment]
Hello! Could you please provide the remote-ssh logs? You can find them through going to the `terminal` on your server side vscode window then selecting the tab `output` then select `remote-ssh` from the dropdown. Feel free to remove any confidential information as you see fit but the logs are most helpful when they are verbose so include as much as possible. Thanks!

**Comment by purnasai-cyient** [comment]
Hi, Thanks for the Reply. Here are the logs:

[00:45:14.438] Log Level: 2
[00:45:14.439] remote-ssh@0.90.1
[00:45:14.440] win32 x64
[00:45:14.461] SSH Resolver called for "ssh-remote+123.123.123.123", attempt 1
[00:45:14.462] "remote.SSH.useLocalServer": false
[00:45:14.462] "remote.SSH.showLoginTerminal": false
[00:45:14.463] "remote.SSH.remotePlatform": {}
[00:45:14.463] "remote.SSH.path": undefined
[00:45:14.463] "remote.SSH.configFile": undefined
[00:45:14.464] "remote.SSH.useFlock": true
[00:45:14.464] "remote.SSH.lockfilesInTmp": false
[00:45:14.464] "remote.SSH.localServerDownload": auto
[00:45:14.464] "remote.SSH.remoteServerListenOnSocket": false
[00:45:14.464] "remote.SSH.showLoginTerminal": false
[00:45:14.465] "remote.SSH.defaultExtensions": []
[00:45:14.465] "remote.SSH.loglevel": 2
[00:45:14.466] "remote.SSH.enableDynamicForwarding": true
[00:45:14.467] "remote.SSH.enableRemoteCommand": false
[00:45:14.468] "remote.SSH.serverPickPortsFromRange": {}
[00:45:14.468] "remote.SSH.serverInstallPath": {}
[00:45:14.510] SSH Resolver called for host: 123.123.123.123
[00:45:14.511] Setting up SSH remote "123.123.123.123"
[00:45:14.519] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[00:45:14.529] Install and start server if needed
[00:45:24.014] Checking ssh with "ssh -V"
[00:45:24.133] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[00:45:24.146] Running script with connection command: ssh -T -D 57749 "123.123.123.123" bash
[00:45:24.154] Terminal shell path: C:\windows\System32\cmd.exe
[00:45:24.562] > 'ssh' is not recognized as an internal or external command,
> operable program or batch file.
> ]0;C:\windows\System32\cmd.exe
[00:45:24.563] Got some output, clearing connection timeout
[00:45:26.847] "install" terminal command done
[00:45:26.848] Install terminal quit with output: ]0;C:\windows\System32\cmd.exe
[00:45:26.848] Received install output: ]0;C:\windows\System32\cmd.exe
[00:45:26.851] Failed to parse remote port from server output
[00:45:26.852] Resolver error: Error: 
	at g.Create (c:\Users\usernamehere\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:585222)
	at t.handleInstallOutput (c:\Users\usernamehere\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:583874)
	at t.tryInstall (c:\Users\usernamehere\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:681023)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\usernamehere\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:643908
	at async t.withShowDetailsEvent (c:\Users\usernamehere\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:647224)
	at async t.resolve (c:\Users\usernamehere\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:644958)
	at async c:\Users\usernamehere\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:726917
[00:45:26.871] ------




[00:45:27.305] ------




[00:45:27.305] SSH Resolver called for "ssh-remote+123.123.123.123", attempt 2, (Reconnection)
[00:45:27.309] SSH Resolver called for host: 123.123.123.123
[00:45:27.310] Setting up SSH remote "123.123.123.123"
[00:45:27.314] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[00:45:27.323] Install and start server if needed
[00:45:48.708] getPlatformForHost was canceled
[00:45:48.710] Resolver error: Error: Connecting was canceled
	at g.Canceled (c:\Users\usernamehere\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:585418)
	at c:\Users\usernamehere\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:643820
	at async t.withShowDetailsEvent (c:\Users\usernamehere\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:647224)
	at async t.resolve (c:\Users\usernamehere\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:644958)
	at async c:\Users\usernamehere\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:726917
[00:45:48.721] ------




[00:45:48.740] ------




[00:45:48.740] SSH Resolver called for "ssh-remote+123.123.123.123", attempt 3, (Reconnection)
[00:45:48.746] SSH Resolver called for host: 123.123.123.123
[00:45:48.747] Setting up SSH remote "123.123.123.123"
[00:45:48.752] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[00:45:48.761] Install and start server if needed

Thank you.

**Comment by eleanorjboyd** [comment]
Hello! Could you add "remote.SSH.remotePlatform": { "YOUR_HOSTNAME": "windows" } to your user settings and let me know if this works?

**Comment by purnasai-cyient** [comment]
Hi, I tried this earlier. I did it even now, but still the same error.

`The terminal process "C:\windows\System32\cmd.exe /c (type "C:\Users\usernamehere\AppData\Local\Temp\vscode-linux-multi-line-command-123.123.123.123-658840110.sh" | ssh -T -D 55651 "123.123.123.123" powershell) & exit /b 0" terminated with exit code: 255.`

**Comment by purnasai-cyient** [comment]
Hi, Were you able to find any solution? I am still struck by the same issue. I hope, we could find a solution to it.

**Comment by eleanorjboyd** [comment]
Hi, I am noticing one of the lines in the error message ` 'ssh' is not recognized as an internal or external command`. Do you have SSH installed on your machine? Additionally could you try running this `ssh -T -D 57749 "123.123.123.123" bash` from your command line and seeing if the connection works?

**Comment by purnasai-cyient** [comment]
Hi @eleanorjboyd , Thanks for your time. I don't know what is wrong with my current machine. I have remote-ssh and python installed same as my colleagues. they were able to connect, but I am not. Finally, I switched to a New machine, in which I am able to connect to Azure VM using VSCode through remote-ssh. Thanks again.

**Comment by eleanorjboyd** [comment]
Glad it now works! 🎉
