### ISSUE TITLE
When trying to connect to an SSH host VSCode tries and times out after a while.

### ISSUE THREAD

**Issue by Dzejkop** [microsoft/vscode-remote-release#7447]
- VSCode Version: `1.73.0`
- Local OS Version: `Windows_NT x64 10.0.19044`
- Remote OS Version: `macOS 12.6 (21G115)`
- Remote Extension/Connection Type: SSH
- Logs:

```
[00:37:11.639] Running script with connection command: ssh -T -D 55963 "MacBookM1" bash
[00:37:11.641] Terminal shell path: C:\Windows\System32\cmd.exe
[00:37:28.655] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (c:\Users\jakub\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:585348)
	at Timeout._onTimeout (c:\Users\jakub\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:679743)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[00:37:28.665] ------




[00:37:28.675] ------




[00:37:28.675] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a224d6163426f6f6b4d31227d", attempt 2, (Reconnection)
[00:37:28.677] SSH Resolver called for host: MacBookM1
[00:37:28.677] Setting up SSH remote "MacBookM1"
[00:37:28.680] Using commit id "8fa188b2b301d36553cbc9ce1b0a146ccb93351f" and quality "stable" for server
[00:37:28.685] Install and start server if needed
[00:37:28.688] Running script with connection command: ssh -T -D 55970 "MacBookM1" bash
[00:37:28.690] Terminal shell path: C:\Windows\System32\cmd.exe
```

What's interesting is that if I try to run the command `ssh MacBookM1` it connects just fine, but `ssh -T -D 55963 "MacBookM1" bash` hangs forever

**Comment by Sampas** [comment]
I'm having the same issue, and removing the related remote folder in `%appdata%/Code/User/workspaceStorage` helps temporarily as described in https://github.com/microsoft/vscode-remote-release/issues/7438#issuecomment-1297865154.

**Comment by Dzejkop** [comment]
Thanks a lot @Sampas, that worked!

**Comment by eleanorjboyd** [comment]
Hello! It looks to be related to this issue as well: https://github.com/microsoft/vscode-remote-release/issues/7324, we are working on a fix and will post updates in that thread. Thanks!
