### ISSUE TITLE
Connecting with SSH timed out with ProxyJump with Yubikey PIN Prompt

### ISSUE THREAD

**Issue by geekshen8521** [microsoft/vscode-remote-release#7448]
VSCode Version:
```
Version: 1.73.0 (user setup)
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:34:06.111Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```

- Local OS Version: 
  ```
  Microsoft Windows 11 Pro Version 10.0.22621 Build 22621
  OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.3

  ```
- Remote OS Version: 
  ProxyJump: Gentoo
```
Kernel:  5.19.16-gentoo-dist
OpenSSH_9.1p1, OpenSSL 1.1.1s  1 Nov 2022
```
   Destination: Ubuntu 20.04

```
Kernel: 5.4.0-131-generic
OpenSSH_8.2p1 Ubuntu-4ubuntu0.5, OpenSSL 1.1.1f  31 Mar 2020
```
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
Config:
```
Host seed-hk-frp
  HostName 192.168.13.10
  User szzonly
  Port 22
  IdentityFile C:\Users\szzon\.ssh\id_ed25519_sk
  ProxyJump gentoo-frp

Host gentoo-frp
  HostName xx.xx.xx.xx
  User szzonly
  Port xxxx
  # IdentityFile C:\Users\szzon\.ssh\id_ed25519_sk
```
1. Connect to seed-hk-frp
2. The flow is like `Windows -> Gentoo -> Ubuntu`

Does this issue occur when you try this locally?: N/A
Does this issue occur when you try this locally and all extensions are disabled?: N/A
- Extra information
I enable public key authentication on both Gentoo and Ubuntu. 
 - When I `ssh seed-hk-frp` in Windows Terminal (with powershell), it will first prompt for PIN for yubikey, then after the PIN is entered, a second prompt will require the same PIN. (I use the same public key on both Gentoo and Ubuntu). Enter the wrong PIN or wait for some time before entering the PIN does not cause any noticable problem.
 - For vscode, if I enter the PIN really quick (two PIN enter and two Yubikey touch within 10 seconds), the remote machine connects successfully. But If I type the first PIN at normal speed, or if I wait for a short time (around 10 seconds) without entering the PIN, then vscode will prompt the `connection timeout...` message.
 - For vscode, if I use public key with empty password( no yubikey involved, key is same on both machine) on both Gentoo and Ubuntu, the remote machine connects just fine.

- Logs:
```
[15:33:47.295] Log Level: 2
[15:33:47.295] remote-ssh@0.90.1
[15:33:47.295] win32 x64
[15:33:47.296] SSH Resolver called for "ssh-remote+seed-hk-frp", attempt 1
[15:33:47.297] "remote.SSH.useLocalServer": false
[15:33:47.297] "remote.SSH.showLoginTerminal": false
[15:33:47.297] "remote.SSH.remotePlatform": {"100.114.237.31":"linux","10.111.0.2":"linux","gentoo-111":"linux","ubuntu20":"linux","43.142.43.244":"linux","seed2":"linux","seed1":"linux","seed3":"linux","seed4":"linux","seed5":"linux","sccc2":"linux","gentoo-frp":"linux","seed-hk-frp":"linux","sc-seed-frp":"linux"}
[15:33:47.297] "remote.SSH.path": undefined
[15:33:47.297] "remote.SSH.configFile": undefined
[15:33:47.297] "remote.SSH.useFlock": true
[15:33:47.297] "remote.SSH.lockfilesInTmp": false
[15:33:47.297] "remote.SSH.localServerDownload": auto
[15:33:47.298] "remote.SSH.remoteServerListenOnSocket": false
[15:33:47.298] "remote.SSH.showLoginTerminal": false
[15:33:47.298] "remote.SSH.defaultExtensions": []
[15:33:47.298] "remote.SSH.loglevel": 2
[15:33:47.298] "remote.SSH.enableDynamicForwarding": true
[15:33:47.298] "remote.SSH.enableRemoteCommand": false
[15:33:47.298] "remote.SSH.serverPickPortsFromRange": {}
[15:33:47.298] "remote.SSH.serverInstallPath": {}
[15:33:47.302] SSH Resolver called for host: seed-hk-frp
[15:33:47.302] Setting up SSH remote "seed-hk-frp"
[15:33:47.306] Using commit id "8fa188b2b301d36553cbc9ce1b0a146ccb93351f" and quality "stable" for server
[15:33:47.309] Install and start server if needed
[15:33:47.312] Checking ssh with "ssh -V"
[15:33:47.365] > OpenSSH_for_Windows_8.9p1, 
[15:33:47.365] > LibreSSL 3.4.3

[15:33:47.372] Running script with connection command: ssh -T -D 53344 "seed-hk-frp" bash
[15:33:47.379] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:34:04.392] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (c:\Users\szzon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:585348)
	at Timeout._onTimeout (c:\Users\szzon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:679743)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[15:34:04.396] ------




[15:34:04.411] ------




[15:34:04.411] SSH Resolver called for "ssh-remote+seed-hk-frp", attempt 2, (Reconnection)
[15:34:04.414] SSH Resolver called for host: seed-hk-frp
[15:34:04.414] Setting up SSH remote "seed-hk-frp"
[15:34:04.416] Using commit id "8fa188b2b301d36553cbc9ce1b0a146ccb93351f" and quality "stable" for server
[15:34:04.419] Install and start server if needed
[15:34:04.429] Running script with connection command: ssh -T -D 53347 "seed-hk-frp" bash
[15:34:04.434] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:34:05.230] > sign_and_send_pubkey: signing failed for ED25519-SK "C:\\Users\\szzon/.ssh/id_ed25519_sk" from agent: agent refused operation
> ]0;C:\WINDOWS\System32\cmd.exe
[15:34:05.230] Got some output, clearing connection timeout
[15:34:05.335] > sign_and_send_pubkey: signing failed for ED25519-SK "szzon@HP-5950X-WINDOWS" from agent: agent refused operation
> szzonly@18.162.168.161: Permission denied (publickey).
> kex_exchange_identification: Connection closed by remote host
> The process tried to write to a nonexistent pipe.
[15:34:06.608] "install" terminal command done
[15:34:06.609] Install terminal quit with output: kex_exchange_identification: Connection closed by remote host
[15:34:06.609] Received install output: kex_exchange_identification: Connection closed by remote host
[15:34:06.609] Failed to parse remote port from server output
[15:34:06.610] Resolver error: Error: 
	at g.Create (c:\Users\szzon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:585222)
	at t.handleInstallOutput (c:\Users\szzon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:583874)
	at t.tryInstall (c:\Users\szzon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:681023)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\szzon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:643908
	at async t.withShowDetailsEvent (c:\Users\szzon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:647224)
	at async t.resolve (c:\Users\szzon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:644958)
	at async c:\Users\szzon\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:726917
[15:34:06.612] ------
```

**Comment by geekshen8521** [comment]
I have tried the `Remote - SSH Pre-Release Version` and it is the same.

**Comment by eleanorjboyd** [comment]
Hello! Does it work correctly locally if you run the command `sh -T -D 53344 "seed-hk-frp" bash`. Additionally does changing the setting in vscode around connection timeout give you more time to write in your password? Hopefully knowing these items can help me troubleshoot more. Thanks!

**Comment by geekshen8521** [comment]
Change the timeout settings from 15 seconds to 30 seconds does works. I do have enough time to enter the PINs. And it connects successfully.

But for `ssh -T -D 53344 "seed-hk-frp" bash`, after two PIN prompt, the terminal just hang there (with Windows Terminal), the terminal cursor is blinking.

**Comment by geekshen8521** [comment]
Also, I am not sure if VSCode will wait for the prompt or not. 
![Screenshot_20221106_055121](https://user-images.githubusercontent.com/65728806/200164916-b9aab4b9-a9dc-47b2-bbc4-8699aec6b612.png)

**Comment by eleanorjboyd** [comment]
@geekshen8521 VS Code should wait for the prompt- what type of authentication are you using for your server? We might not support it at this time which is why VS Code might not be waiting since it doesn't recognize the request for user input. If you run your ssh command with `-v` it should provide more logs that would tell us what ssh is returning that we need to add to our auth recognization list.

**Comment by geekshen8521** [comment]
I follow the link to setup SSH https://developers.yubico.com/SSH/Securing_SSH_with_FIDO2.html

**Comment by geekshen8521** [comment]
Here is the `ssh -v` log
```
OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.3
debug1: Reading configuration data C:\\Users\\szzon/.ssh/config
debug1: C:\\Users\\szzon/.ssh/config line 28: Applying options for seed-hk-frp
debug1: Setting implicit ProxyCommand from ProxyJump: "C:\\Program Files\\OpenSSH\\ssh.exe"  -v -W "[%h]:%p" gentoo-frp
debug1: Executing proxy command: exec "C:\\Program Files\\OpenSSH\\ssh.exe"  -v -W "[192.168.13.10]:22" gentoo-frp
debug1: identity file C:\\Users\\szzon\\.ssh\\id_ed25519_sk type 12
debug1: identity file C:\\Users\\szzon\\.ssh\\id_ed25519_sk-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.9
OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.3
debug1: Reading configuration data C:\\Users\\szzon/.ssh/config
debug1: C:\\Users\\szzon/.ssh/config line 94: Applying options for gentoo-frp
debug1: Connecting to xx.xx.xx.xx [xx.xx.xx.xx] port xxxx.
debug1: Connection established.
debug1: identity file C:\\Users\\szzon/.ssh/id_rsa type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_rsa-cert type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_ecdsa type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_ecdsa-cert type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_ecdsa_sk type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_ed25519 type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_ed25519-cert type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_ed25519_sk type 12
debug1: identity file C:\\Users\\szzon/.ssh/id_ed25519_sk-cert type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_xmss type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_xmss-cert type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_dsa type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.9
debug1: Remote protocol version 2.0, remote software version OpenSSH_9.1
debug1: compat_banner: match: OpenSSH_9.1 pat OpenSSH* compat 0x04000000
debug1: Authenticating to xx.xx.xx.xx:xxxx as 'szzonly'
debug1: load_hostkeys: fopen C:\\Users\\szzon/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
debug1: load_hostkeys: fopen C:\\Users\\szzon/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts2: No such file or directory
debug1: Host '[xx.xx.xx.xx]:xxxx' is known and matches the ED25519 host key.
debug1: Found key in C:\\Users\\szzon/.ssh/known_hosts:81
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: get_agent_identities: agent returned 2 keys
debug1: Will attempt key: C:\\Users\\szzon/.ssh/id_ed25519_sk ED25519-SK SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX authenticator agent
debug1: Will attempt key: szzon@HP-5950X-WINDOWS ED25519-SK SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX authenticator agent
debug1: Will attempt key: C:\\Users\\szzon/.ssh/id_rsa
debug1: Will attempt key: C:\\Users\\szzon/.ssh/id_ecdsa
debug1: Will attempt key: C:\\Users\\szzon/.ssh/id_ecdsa_sk
debug1: Will attempt key: C:\\Users\\szzon/.ssh/id_ed25519
debug1: Will attempt key: C:\\Users\\szzon/.ssh/id_xmss
debug1: Will attempt key: C:\\Users\\szzon/.ssh/id_dsa
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com>
debug1: kex_input_ext_info: publickey-hostbound@openssh.com=<0>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: C:\\Users\\szzon/.ssh/id_ed25519_sk ED25519-SK SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX authenticator agent
debug1: Server accepts key: C:\\Users\\szzon/.ssh/id_ed25519_sk ED25519-SK SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX authenticator agent
Authenticated to xx.xx.xx.xx ([xx.xx.xx.xx]:xxxx) using "publickey".
debug1: channel_connect_stdio_fwd: 192.168.13.10:22
debug1: channel 0: new [stdio-forward]
debug1: getpeername failed: Bad file descriptor
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: filesystem
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: client_input_hostkeys: searching C:\\Users\\szzon/.ssh/known_hosts for [xx.xx.xx.xx]:xxxx / (none)
debug1: client_input_hostkeys: searching C:\\Users\\szzon/.ssh/known_hosts2 for [xx.xx.xx.xx]:xxxx / (none)
debug1: client_input_hostkeys: hostkeys file C:\\Users\\szzon/.ssh/known_hosts2 does not exist
debug1: client_input_hostkeys: host key found matching a different name/address, skipping UserKnownHostsFile update
debug1: Remote: /home/szzonly/.ssh/authorized_keys:2: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug1: Remote: /home/szzonly/.ssh/authorized_keys:2: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.2p1 Ubuntu-4ubuntu0.5
debug1: compat_banner: match: OpenSSH_8.2p1 Ubuntu-4ubuntu0.5 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 192.168.13.10:22 as 'szzonly'
debug1: load_hostkeys: fopen C:\\Users\\szzon/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
debug1: load_hostkeys: fopen C:\\Users\\szzon/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts2: No such file or directory
debug1: Host '192.168.13.10' is known and matches the ED25519 host key.
debug1: Found key in C:\\Users\\szzon/.ssh/known_hosts:28
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: get_agent_identities: agent returned 2 keys
debug1: Will attempt key: C:\\Users\\szzon\\.ssh\\id_ed25519_sk ED25519-SK SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX explicit authenticator agent
debug1: Will attempt key: szzon@HP-5950X-WINDOWS ED25519-SK SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX authenticator agent
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: C:\\Users\\szzon\\.ssh\\id_ed25519_sk ED25519-SK SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX explicit authenticator agent
debug1: Server accepts key: C:\\Users\\szzon\\.ssh\\id_ed25519_sk ED25519-SK SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX explicit authenticator agent
sign_and_send_pubkey: signing failed for ED25519-SK "C:\\Users\\szzon\\.ssh\\id_ed25519_sk" from agent: agent refused operation
debug1: Offering public key: szzon@HP-5950X-WINDOWS ED25519-SK SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX authenticator agent
debug1: Authentications that can continue: publickey
debug1: No more authentication methods to try.
szzonly@192.168.13.10: Permission denied (publickey).
PS C:\Users\szzon> ssh -v seed-hk-frp
OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.3
debug1: Reading configuration data C:\\Users\\szzon/.ssh/config
debug1: C:\\Users\\szzon/.ssh/config line 28: Applying options for seed-hk-frp
debug1: Setting implicit ProxyCommand from ProxyJump: "C:\\Program Files\\OpenSSH\\ssh.exe"  -v -W "[%h]:%p" gentoo-frp
debug1: Executing proxy command: exec "C:\\Program Files\\OpenSSH\\ssh.exe"  -v -W "[192.168.13.10]:22" gentoo-frp
debug1: identity file C:\\Users\\szzon\\.ssh\\id_ed25519_sk type 12
debug1: identity file C:\\Users\\szzon\\.ssh\\id_ed25519_sk-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.9
OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.3
debug1: Reading configuration data C:\\Users\\szzon/.ssh/config
debug1: C:\\Users\\szzon/.ssh/config line 94: Applying options for gentoo-frp
debug1: Connecting to xx.xx.xx.xx [xx.xx.xx.xx] port xxxx.
debug1: Connection established.
debug1: identity file C:\\Users\\szzon/.ssh/id_rsa type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_rsa-cert type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_ecdsa type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_ecdsa-cert type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_ecdsa_sk type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_ed25519 type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_ed25519-cert type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_ed25519_sk type 12
debug1: identity file C:\\Users\\szzon/.ssh/id_ed25519_sk-cert type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_xmss type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_xmss-cert type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_dsa type -1
debug1: identity file C:\\Users\\szzon/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.9
debug1: Remote protocol version 2.0, remote software version OpenSSH_9.1
debug1: compat_banner: match: OpenSSH_9.1 pat OpenSSH* compat 0x04000000
debug1: Authenticating to xx.xx.xx.xx:xxxx as 'szzonly'
debug1: load_hostkeys: fopen C:\\Users\\szzon/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
debug1: load_hostkeys: fopen C:\\Users\\szzon/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts2: No such file or directory
debug1: Host '[xx.xx.xx.xx]:xxxx' is known and matches the ED25519 host key.
debug1: Found key in C:\\Users\\szzon/.ssh/known_hosts:81
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: get_agent_identities: agent returned 2 keys
debug1: Will attempt key: C:\\Users\\szzon/.ssh/id_ed25519_sk ED25519-SK SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX authenticator agent
debug1: Will attempt key: szzon@HP-5950X-WINDOWS ED25519-SK SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX authenticator agent
debug1: Will attempt key: C:\\Users\\szzon/.ssh/id_rsa
debug1: Will attempt key: C:\\Users\\szzon/.ssh/id_ecdsa
debug1: Will attempt key: C:\\Users\\szzon/.ssh/id_ecdsa_sk
debug1: Will attempt key: C:\\Users\\szzon/.ssh/id_ed25519
debug1: Will attempt key: C:\\Users\\szzon/.ssh/id_xmss
debug1: Will attempt key: C:\\Users\\szzon/.ssh/id_dsa
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com>
debug1: kex_input_ext_info: publickey-hostbound@openssh.com=<0>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: C:\\Users\\szzon/.ssh/id_ed25519_sk ED25519-SK SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX authenticator agent
debug1: Server accepts key: C:\\Users\\szzon/.ssh/id_ed25519_sk ED25519-SK SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX authenticator agent
Authenticated to xx.xx.xx.xx ([xx.xx.xx.xx]:xxxx) using "publickey".
debug1: channel_connect_stdio_fwd: 192.168.13.10:22
debug1: channel 0: new [stdio-forward]
debug1: getpeername failed: Bad file descriptor
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: filesystem
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: client_input_hostkeys: searching C:\\Users\\szzon/.ssh/known_hosts for [xx.xx.xx.xx]:xxxx / (none)
debug1: client_input_hostkeys: searching C:\\Users\\szzon/.ssh/known_hosts2 for [xx.xx.xx.xx]:xxxx / (none)
debug1: client_input_hostkeys: hostkeys file C:\\Users\\szzon/.ssh/known_hosts2 does not exist
debug1: client_input_hostkeys: host key found matching a different name/address, skipping UserKnownHostsFile update
debug1: Remote: /home/szzonly/.ssh/authorized_keys:2: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug1: Remote: /home/szzonly/.ssh/authorized_keys:2: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.2p1 Ubuntu-4ubuntu0.5
debug1: compat_banner: match: OpenSSH_8.2p1 Ubuntu-4ubuntu0.5 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 192.168.13.10:22 as 'szzonly'
debug1: load_hostkeys: fopen C:\\Users\\szzon/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
debug1: load_hostkeys: fopen C:\\Users\\szzon/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts2: No such file or directory
debug1: Host '192.168.13.10' is known and matches the ED25519 host key.
debug1: Found key in C:\\Users\\szzon/.ssh/known_hosts:28
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: get_agent_identities: agent returned 2 keys
debug1: Will attempt key: C:\\Users\\szzon\\.ssh\\id_ed25519_sk ED25519-SK SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX explicit authenticator agent
debug1: Will attempt key: szzon@HP-5950X-WINDOWS ED25519-SK SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX authenticator agent
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: C:\\Users\\szzon\\.ssh\\id_ed25519_sk ED25519-SK SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX explicit authenticator agent
debug1: Server accepts key: C:\\Users\\szzon\\.ssh\\id_ed25519_sk ED25519-SK SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX explicit authenticator agent
Authenticated to 192.168.13.10 (via proxy) using "publickey".
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: filesystem
debug1: ENABLE_VIRTUAL_TERMINAL_INPUT is supported. Reading the VTSequence from console
debug1: ENABLE_VIRTUAL_TERMINAL_PROCESSING is supported. Console supports the ansi parsing
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: client_input_hostkeys: searching C:\\Users\\szzon/.ssh/known_hosts for 192.168.13.10 / (none)
debug1: client_input_hostkeys: searching C:\\Users\\szzon/.ssh/known_hosts2 for 192.168.13.10 / (none)
debug1: client_input_hostkeys: hostkeys file C:\\Users\\szzon/.ssh/known_hosts2 does not exist
debug1: client_input_hostkeys: no new or deprecated keys from server
debug1: Remote: /home/szzonly/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug1: Remote: /home/szzonly/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
```

**Comment by eleanorjboyd** [comment]
I'm closing since changing the timeout fix works for you and nothing in these logs suggests an easy fix to why its not waiting for the auth like with other auth services.
