### ISSUE TITLE
"Rebuild and Reopen in Container" from WSL fails for docker-compose

### ISSUE THREAD

**Issue by dlawson-mt** [microsoft/vscode-remote-release#7464]
Building a docker-compose.yml devcontainer from within a WSL-opened folder fails. 

- VSCode Version: 1.73.0 / 1.74.0-insider
- Local OS Version: Windows_NT x64 10.0.22621
- Remote OS Version: WSL: Ubuntu-20.04
- Remote Extension/Connection Type: WSL/Containers
- Logs:

**Dev Containers: Show Container Log**
```
[9535 ms] Dev Containers 0.263.0 in VS Code 1.74.0-insider (e764c5b816a99eb8673b2fc4fc028827f202872f).
[9535 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/dave/devcontainer-test' && /bin/sh
[9545 ms] Start: Run in host: id -un
[9647 ms] dave
[9648 ms] 
[9648 ms] Start: Run in host: cat /etc/passwd
[9650 ms] Start: Run in host: echo ~
[9651 ms] /home/dave
[9651 ms] 
[9651 ms] Start: Run in host: test -x '/home/dave/.vscode-remote-containers/bin/e764c5b816a99eb8673b2fc4fc028827f202872f/node'
[9652 ms] 
[9652 ms] 
[9652 ms] Exit code 1
[9653 ms] Start: Run in host: test -x '/home/dave/.vscode-server-insiders/bin/e764c5b816a99eb8673b2fc4fc028827f202872f/node'
[9654 ms] 
[9654 ms] 
[9655 ms] Start: Run in host: test -f '/home/dave/.vscode-server-insiders/bin/e764c5b816a99eb8673b2fc4fc028827f202872f/node_modules/node-pty/package.json'
[9655 ms] 
[9656 ms] 
[9656 ms] Start: Run in host: test -f '/home/dave/.vscode-remote-containers/dist/vscode-remote-containers-server-0.263.0.js'
[9657 ms] 
[9657 ms] 
[9657 ms] Exit code 1
[9657 ms] Start: Run in host: mkdir -p '/home/dave/.vscode-remote-containers/dist'
[9658 ms] 
[9658 ms] 
[9659 ms] Start: Run in host: cat <<'EOF-/home/dave/.vscode-remote-containers/dist/vscode-remote-containers-server-0.263.0.js' >/home/dave/.vscode-remote-containers/dist/vscode-remote-containers-server-0.263.0.js_1667563349401
[9661 ms] 
[9661 ms] 
[9663 ms] userEnvProbe: loginInteractiveShell (default)
[9663 ms] userEnvProbe shell: /bin/bash
[9724 ms] Command failed: /bin/bash -lic echo -n 4e9cbda1b157a5d0fc322b1816ab93b6; cat /proc/self/environ; echo -n 4e9cbda1b157a5d0fc322b1816ab93b6
[9768 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/dave/devcontainer-test' && /bin/sh
[9776 ms] Start: Run in host: id -un
[9875 ms] dave
[9875 ms] 
[9875 ms] Start: Run in host: cat /etc/passwd
[9877 ms] Start: Run in host: echo ~
[9877 ms] /home/dave
[9877 ms] 
[9877 ms] Start: Run in host: test -x '/home/dave/.vscode-remote-containers/bin/e764c5b816a99eb8673b2fc4fc028827f202872f/node'
[9878 ms] 
[9878 ms] 
[9878 ms] Exit code 1
[9878 ms] Start: Run in host: test -x '/home/dave/.vscode-server-insiders/bin/e764c5b816a99eb8673b2fc4fc028827f202872f/node'
[9879 ms] 
[9879 ms] 
[9879 ms] Start: Run in host: test -f '/home/dave/.vscode-server-insiders/bin/e764c5b816a99eb8673b2fc4fc028827f202872f/node_modules/node-pty/package.json'
[9880 ms] 
[9880 ms] 
[9880 ms] Start: Run in host: test -f '/home/dave/.vscode-remote-containers/dist/vscode-remote-containers-server-0.263.0.js'
[9881 ms] 
[9881 ms] 
[9882 ms] userEnvProbe: loginInteractiveShell (default)
[9882 ms] userEnvProbe shell: /bin/bash
[9942 ms] Command failed: /bin/bash -lic echo -n ec75c4b7d5020c498e7e1835022afb0f; cat /proc/self/environ; echo -n ec75c4b7d5020c498e7e1835022afb0f
[9981 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[10004 ms] 1.41
[10039 ms] Start: Run in Host: tar --no-same-owner -x -f -
[10068 ms] Start: Run in Host: tar --no-same-owner -x -f -
[10078 ms] Start: Run in Host: /home/dave/.vscode-server-insiders/bin/e764c5b816a99eb8673b2fc4fc028827f202872f/node /home/dave/.vscode-remote-containers/dist/dev-containers-cli-0.263.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/dave/devcontainer-test --log-level debug --log-format json --config /home/dave/devcontainer-test/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true
[10227 ms] (node:1103) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[10227 ms] (Use `node --trace-deprecation ...` to show where the warning was created)
[10230 ms] @devcontainers/cli 0.23.2. Node.js v16.14.2. linux 5.15.68.1-microsoft-standard-WSL2 x64.
[10230 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/dave/devcontainer-test
[10258 ms] Start: Run: docker-compose version --short
[10261 ms] Error: Command failed: docker-compose version --short
    at xc (/home/dave/.vscode-remote-containers/dist/dev-containers-cli-0.263.0/dist/spec-node/devContainersSpecCLI.js:1878:904)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TO (/home/dave/.vscode-remote-containers/dist/dev-containers-cli-0.263.0/dist/spec-node/devContainersSpecCLI.js:1804:20191)
    at async sue (/home/dave/.vscode-remote-containers/dist/dev-containers-cli-0.263.0/dist/spec-node/devContainersSpecCLI.js:2013:31891)
[10264 ms] Exit code 1
```

**Log (Extension Host) output:**
```
2022-11-04 08:02:20.028 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2022-11-04 08:02:23.310 [info] $getCanonicalURI invoked for authority (wsl)
2022-11-04 08:02:50.101 [error] {"message":"Command failed: /home/dave/.vscode-server-insiders/bin/e764c5b816a99eb8673b2fc4fc028827f202872f/node /home/dave/.vscode-remote-containers/dist/dev-containers-cli-0.263.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/dave/devcontainer-test --log-level debug --log-format json --config /home/dave/devcontainer-test/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true","code":1} remote-containers.rebuildAndReopenInContainer {"value":"ms-vscode-remote.remote-containers","_lower":"ms-vscode-remote.remote-containers"}
```

Steps to Reproduce:

1. WSL: Open Folder in WSL... (select a folder that is not bind-mounted)
2. Dev Containers: Add Dev Container Configuration Files...
3. Add a docker-compose.yml file to project and modify devcontainer.json to use it (see below)
4. Dev Containers: Rebuild and Reopen in Container

**devcontainer.json**
```
{
	"name": "Alpine",
	"dockerComposeFile": "./docker-compose.yml",
	"service": "app",
	"remoteUser": "vscode"
}
```
**docker-compose.yml**
```
version: "3.8"
services:
  app:
    image: mcr.microsoft.com/devcontainers/base:0-alpine-3.16
```

Step 4 fails with the following dialog box:
![image](https://user-images.githubusercontent.com/11928222/199972867-83b16e04-6dc7-4cb3-a71d-bce408d3846f.png)

If I enter the failing command directly in the WSL terminal, it reports: "Error: Missing node-pty":
```
$ /home/dave/.vscode-server-insiders/bin/e764c5b816a99eb8673b2fc4fc028827f202872f/node /home/dave/.vscode-remote-containers/dist/dev-containers-cli-0.263.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/dave/devcontainer-test --log-level debug --log-format json --config /home/dave/devcontainer-test/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true
(node:1481) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: Missing node-pty
    at ID (/home/dave/.vscode-remote-containers/dist/dev-containers-cli-0.263.0/dist/spec-node/devContainersSpecCLI.js:1672:1412)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async fn (/home/dave/.vscode-remote-containers/dist/dev-containers-cli-0.263.0/dist/spec-node/devContainersSpecCLI.js:1671:13306)
    at async sue (/home/dave/.vscode-remote-containers/dist/dev-containers-cli-0.263.0/dist/spec-node/devContainersSpecCLI.js:2013:30945)
```

I believe the issue is that vscode-server's NODE_PATH is incorrect when this command is being executed (hence, the "Missing node-pty" error).

This only happens when trying to build a docker-compose.yml devcontainer, when "docker-compose version -short" is probed. This is not an issue for a Dockerfile-based devcontainer.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by nvick** [comment]
I'm seeing the same issue with VSCode on Linux. Versions 1.72 and 1.73. The Dev Container extension is version 0.262.3.

**Comment by chrmarti** [comment]
@dlawson-mt The error in the log suggests that `docker-compose version --short` is failing for some reason, could you try running that in the same WSL distro? (We set the NODE_PATH when launching the Dev Containers CLI in WSL.)

@nvick Could you append the log from when this happens (`F1` > `Dev Containers: Show Container Log`)?

**Comment by dlawson-mt** [comment]
> @dlawson-mt The error in the log suggests that `docker-compose version --short` is failing for some reason, could you try running that in the same WSL distro? (We set the NODE_PATH when launching the Dev Containers CLI in WSL.)

Executing from the WSL distro (Ubuntu-20.04) produces this:
```
dave@dave-hoffice:~/devcontainer-test$ docker-compose version --short
1.29.2
```

However, I believe the problem is in the execution of devContainersSpecCLI.js, which is throwing the error. You can see the command that executes this script in the _Log (Extension Host)_ output. When I execute that same command from the WSL terminal, it fails when trying to require _node-pty_:
```
dave@dave-hoffice:~/devcontainer-test$ /home/dave/.vscode-server-insiders/bin/e764c5b816a99eb8673b2fc4fc028827f202872f/node /home/dave/.vscode-remote-containers/dist/dev-containers-cli-0.263.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/dave/devcontainer-test --log-level debug --log-format json --config /home/dave/devcontainer-test/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true
(node:4204) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: Missing node-pty
    at ID (/home/dave/.vscode-remote-containers/dist/dev-containers-cli-0.263.0/dist/spec-node/devContainersSpecCLI.js:1672:1412)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async fn (/home/dave/.vscode-remote-containers/dist/dev-containers-cli-0.263.0/dist/spec-node/devContainersSpecCLI.js:1671:13306)
    at async sue (/home/dave/.vscode-remote-containers/dist/dev-containers-cli-0.263.0/dist/spec-node/devContainersSpecCLI.js:2013:30945)
```

If I add the correct NODE_PATH to that command, it works:
```
dave@dave-hoffice:~/devcontainer-test$ NODE_PATH="/home/dave/.vscode-server-insiders/bin/e764c5b816a99eb8673b2fc4fc028827f202872f/node_modules/" /home/dave/.vscode-server-insiders/bin/e764c5b816a99eb8673b2fc4fc028827f202872f/node /home/dave/.vscode-remote-containers/dist/dev-containers-cli-0.263.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/dave/devcontainer-test --log-level debug --log-format json --config /home/dave/devcontainer-test/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true
(node:4637) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
{"type":"text","level":3,"timestamp":1667920457274,"text":"@devcontainers/cli 0.23.2. Node.js v16.14.2. linux 5.15.68.1-microsoft-standard-WSL2 x64."}
{"type":"start","level":2,"timestamp":1667920457274,"text":"Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/dave/devcontainer-test"}
{"type":"stop","level":2,"timestamp":1667920457416,"text":"Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/dave/devcontainer-test","startTimestamp":1667920457274}
{"type":"text","level":1,"timestamp":1667920457418,"text":"workspace root: /home/dave/devcontainer-test"}
{"type":"start","level":2,"timestamp":1667920457418,"text":"Run: docker-compose version --short"}
{"type":"stop","level":2,"timestamp":1667920457769,"text":"Run: docker-compose version --short","startTimestamp":1667920457418}
{"type":"text","level":2,"timestamp":1667920457769,"text":"Docker Compose version: 1.29.2"}
{"type":"start","level":2,"timestamp":1667920457770,"text":"Run: docker-compose -f /home/dave/devcontainer-test/.devcontainer/docker-compose.yml config"}
{"type":"stop","level":2,"timestamp":1667920458110,"text":"Run: docker-compose -f /home/dave/devcontainer-test/.devcontainer/docker-compose.yml config","startTimestamp":1667920457770}
{"type":"text","level":2,"timestamp":1667920458110,"text":"services:\n  app:\n    image: mcr.microsoft.com/devcontainers/base:0-alpine-3.16\nversion: '3.8'\n\n"}
{"type":"start","level":2,"timestamp":1667920458112,"text":"Run: docker inspect --type image mcr.microsoft.com/devcontainers/base:0-alpine-3.16"}
{"type":"stop","level":2,"timestamp":1667920458233,"text":"Run: docker inspect --type image mcr.microsoft.com/devcontainers/base:0-alpine-3.16","startTimestamp":1667920458112}
{"type":"text","level":1,"timestamp":1667920458234,"text":"resource: mcr.microsoft.com/devcontainers/base"}
{"type":"text","level":1,"timestamp":1667920458234,"text":"id: base"}
{"type":"text","level":1,"timestamp":1667920458234,"text":"version: 0-alpine-3.16"}
{"type":"text","level":1,"timestamp":1667920458234,"text":"owner: devcontainers"}
{"type":"text","level":1,"timestamp":1667920458234,"text":"namespace: devcontainers"}
{"type":"text","level":1,"timestamp":1667920458234,"text":"registry: mcr.microsoft.com"}
{"type":"text","level":1,"timestamp":1667920458234,"text":"path: devcontainers/base"}
{"type":"text","level":1,"timestamp":1667920458234,"text":"manifest url: https://mcr.microsoft.com/v2/devcontainers/base/manifests/0-alpine-3.16"}
{"type":"text","level":1,"timestamp":1667920458647,"text":"blob url: https://mcr.microsoft.com/v2/devcontainers/base/blobs/sha256:4120cfd0449e055442c3ccee73e0dcca5540233dc224073167b9b465ef2487ce"}
{"configuration":{"name":"Alpine","dockerComposeFile":"./docker-compose.yml","service":"app","remoteUser":"vscode","configFilePath":{"$mid":1,"fsPath":"/home/dave/devcontainer-test/.devcontainer/devcontainer.json","path":"/home/dave/devcontainer-test/.devcontainer/devcontainer.json","scheme":"file"}},"workspace":{"workspaceFolder":"/"},"mergedConfiguration":{"name":"Alpine","dockerComposeFile":"./docker-compose.yml","service":"app","remoteUser":"vscode","configFilePath":{"$mid":1,"fsPath":"/home/dave/devcontainer-test/.devcontainer/devcontainer.json","path":"/home/dave/devcontainer-test/.devcontainer/devcontainer.json","scheme":"file"},"init":false,"privileged":false,"remoteEnv":{},"containerEnv":{},"portsAttributes":{}}}
dave@dave-hoffice:~/devcontainer-test$
```

**Comment by chrmarti** [comment]
We set `NODE_PATH` when we launch `devContainersSpecCLI.js` from the extension. The error in the original log is `Error: Command failed: docker-compose version --short`.

**Comment by dlawson-mt** [comment]
> The error in the original log is `Error: Command failed: docker-compose version --short`.

Yes, but I believe that error message is being thrown by the `devContainerSpecCLI.js` script when it tries to execute `docker-compose version --short`.

As I noted in my previous comment, if I manually execute `devContainerSpecCLI.js` script with the correct `NODE_PATH`, it appears to execute correctly. You can see the call to `docker-compose version --short` in the output, and you can see that the correct docker-compose version is returned:

```shell
...
{"type":"start","level":2,"timestamp":1667920457418,"text":"Run: docker-compose version --short"}
{"type":"stop","level":2,"timestamp":1667920457769,"text":"Run: docker-compose version --short","startTimestamp":1667920457418}
{"type":"text","level":2,"timestamp":1667920457769,"text":"Docker Compose version: 1.29.2"}
...
```

**Comment by suppayami** [comment]
I got the same problem and tried what @dlawson-mt mentioned above, can confirm that problem lied on node-pty package couldn't be found.

**Comment by chrmarti** [comment]
We run `docker-compose version --short` without using `node-pty`. When I remove `node-pty` it fails with an "Error: Missing node-pty" right after starting the devContainersSpecCLI.js.

@dlawson-mt I see in you log that the userEnvProbe in WSL failed. Could you run `/bin/bash -lic 'echo test'` in WSL and see if that shows any error?

**Comment by jackmenzie** [comment]
@dlawson-mt Not sure where you got with this issue but I ran into it too recently.

It seems like an issue with the way the extension uses the local docker-compose. To resolve the issue, we upgraded to the latest version of docker-compose locally using the standalone installation: https://docs.docker.com/compose/install/other/#on-linux (v2.14.0).

**Comment by suppayami** [comment]
I follow @jackmenzie instruction and it works for me now. You need to check if there is any existing link to `/usr/bin/docker-compose` and delete it, upgrade to docker-compose v2.14.2 and link new version to `/usr/bin/docker-compose`.

**Comment by GerwazyMiod** [comment]
Same - it turned out I didn't had docker-compose on my linux host (for which I log-on as remote machine from my Windows machine where VSCode sits). After successful instalation of docker-compose - everything is working smoothly.  So the error "Error: Missing node-pty" is quite misleading here.

**Comment by konqi** [comment]
I had the same issue, recognizable by the `devContainersSpecCLI.js` part in the stack trace.
**Possible Fix:** For me installing the latest (LTS) version of node made it work. I believe node wasn't available by default before.

**Comment by Cpcrook** [comment]
I was running into this today with an older dev container.  Fiddled with node versions in WSL, Docker updates to latest, etc, trying to figure things out.

Turns out the culprit appeared to be a _very_ old NVM installer script causing issues.

In particular, in my dev container Dockerfile I swapped out 

```
    && curl -so- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash 2>&1 \
```

for 

```
    && curl -so- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash 2>&1 \
```

Dev container now builds and runs as expected.

**Comment by pedrodaniel10** [comment]
I changed the `docker-compose` alias in the VS Code configurations (under extensions > Dev Containers). The reason is that Docker Desktop uses compose V2 and `docker-compose` is V1. 
However I had other error when doing the `docker compose up`:

```
[7668 ms] Start: Run: docker compose --project-name proj -f /home/pedrodaniel10/code.siemens/proj/docker-compose-dev.yml -f /home/pedrodaniel10/code.siemens/proj/.devcontainer/docker-compose.yml -f /tmp/devcontainercli-pedrodaniel10/docker-compose/docker-compose.devcontainer.containerFeatures-1679656652020.yml up -d
[+] Running 0/0
 ⠋ redis-cache Pulling                                                     0.0s
 ⠋ mongo Pulling                                                           0.0s
 ⠋ redis-bullmq Pulling                                                    0.0s
error getting credentials - err: docker-credential-desktop.exe resolves to executable in current directory (./docker-credential-desktop.exe), out: ``
[8027 ms] Error: Command failed: docker compose --project-name proj -f /home/pedrodaniel10/code.siemens/proj/docker-compose-dev.yml -f /home/pedrodaniel10/code.siemens/proj/.devcontainer/docker-compose.yml -f /tmp/devcontainercli-pedrodaniel10/docker-compose/docker-compose.devcontainer.containerFeatures-1679656652020.yml up -d
[8027 ms]     at sie (/home/pedrodaniel10/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:1896:3061)
[8027 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[8027 ms]     at async iie (/home/pedrodaniel10/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:1878:2396)
[8028 ms]     at async xie (/home/pedrodaniel10/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:1945:2798)
[8028 ms]     at async Wf (/home/pedrodaniel10/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:1945:3750)
[8028 ms]     at async noe (/home/pedrodaniel10/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:2069:17325)
[8028 ms]     at async roe (/home/pedrodaniel10/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js:2069:17066)
[8035 ms] Exit code 1
[8038 ms] Command failed: /home/pedrodaniel10/.vscode-server/bin/ee2b180d582a7f601fa6ecfdad8d9fd269ab1884/node /home/pedrodaniel10/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js up --docker-compose-path docker compose --container-session-data-folder /tmp/devcontainers-fff09a04-4465-4f54-80a3-6aadc2a998a01679656643105 --workspace-folder /home/pedrodaniel10/code.siemens/proj --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl$\Ubuntu-20.04\home\pedrodaniel10\code.siemens\proj --id-label devcontainer.config_file=/home/pedrodaniel10/code.siemens/proj/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/pedrodaniel10/code.siemens/proj/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[8038 ms] Exit code 1
```

Apparently, it tries to run `docker-credential-desktop.exe`. Any ideas what is this issue?

**Comment by chrmarti** [comment]
Docker uses `docker-credential-desktop.exe` to lookup credentials to authenticate with image registries. Is that in your current directory?
