### ISSUE TITLE
Failure to build dev container if builtin path has spaces

### ISSUE THREAD

**Issue by LighthouseJ** [microsoft/vscode-remote-release#7467]
- VSCode Version: 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662)
- Local OS Version: macOS Monterey 12.6.1
- Remote OS Version: Debian Bullseye 11
- Remote Extension/Connection Type: Containers
- Logs:

<pre>
[2022-11-04T16:11:37.686Z] Remote-Containers 0.245.2 in VS Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662).
[2022-11-04T16:11:37.686Z] Start: Resolving Remote
[2022-11-04T16:11:37.703Z] Setting up container for folder or workspace: /Users/widmyern/Documents/test/testproject
[2022-11-04T16:11:37.705Z] Start: Check Docker is running
[2022-11-04T16:11:37.705Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2022-11-04T16:11:37.920Z] Stop (215 ms): Run: docker version --format {{.Server.APIVersion}}
[2022-11-04T16:11:37.920Z] Server API version: 1.41
[2022-11-04T16:11:37.920Z] Stop (215 ms): Check Docker is running
[2022-11-04T16:11:37.921Z] Start: Run: docker volume ls -q
[2022-11-04T16:11:38.103Z] Stop (182 ms): Run: docker volume ls -q
[2022-11-04T16:11:38.195Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/widmyern/Documents/test/testproject --filter label=vsch.quality=stable
[2022-11-04T16:11:38.390Z] Stop (195 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/Users/widmyern/Documents/test/testproject --filter label=vsch.quality=stable
[2022-11-04T16:11:38.390Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/widmyern/Documents/test/testproject
[2022-11-04T16:11:38.593Z] Stop (203 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/widmyern/Documents/test/testproject
[2022-11-04T16:11:38.593Z] Start: Run: docker inspect --type container b39b9234b0dd
[2022-11-04T16:11:38.792Z] Stop (199 ms): Run: docker inspect --type container b39b9234b0dd
[2022-11-04T16:11:38.792Z] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/widmyern/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/widmyern/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/widmyern/Documents/test/testproject --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/widmyern/Documents/test/testproject --log-level debug --log-format json --config /Users/widmyern/Documents/test/testproject/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-11-04T16:11:38.938Z] remote-containers 0.245.2.
[2022-11-04T16:11:38.938Z] Start: Run: docker buildx version
[2022-11-04T16:11:39.325Z] Stop (387 ms): Run: docker buildx version
[2022-11-04T16:11:39.325Z] Start: Resolving Remote
[2022-11-04T16:11:39.327Z] Start: Run: docker-compose version --short
[2022-11-04T16:11:39.739Z] Stop (412 ms): Run: docker-compose version --short
[2022-11-04T16:11:39.739Z] Docker Compose version: 2.10.2
[2022-11-04T16:11:39.740Z] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=testproject_devcontainer --filter label=com.docker.compose.service=app
[2022-11-04T16:11:39.940Z] Stop (200 ms): Run: docker ps -q -a --filter label=com.docker.compose.project=testproject_devcontainer --filter label=com.docker.compose.service=app
[2022-11-04T16:11:39.940Z] Start: Run: docker inspect --type container b39b9234b0dd
[2022-11-04T16:11:40.115Z] Stop (175 ms): Run: docker inspect --type container b39b9234b0dd
[2022-11-04T16:11:40.115Z] Start: Run: docker-compose -f /Users/widmyern/Documents/test/testproject/.devcontainer/docker-compose.yaml --profile * config
[2022-11-04T16:11:40.834Z] Stop (719 ms): Run: docker-compose -f /Users/widmyern/Documents/test/testproject/.devcontainer/docker-compose.yaml --profile * config
[2022-11-04T16:11:40.835Z] name: devcontainer
services:
  app:
    build:
      context: /Users/widmyern/Documents/test/testproject/.devcontainer
      dockerfile: Dockerfile.rust
      args:
        VARIANT: buster
    command:
    - /bin/sh
    - -c
    - while sleep 1000; do :; done
    network_mode: service:db
    volumes:
    - type: bind
      source: /Users/widmyern/Documents/test/testproject
      target: /workspace
      bind:
        create_host_path: true
  db:
    image: postgres:15
    networks:
      default: null
    restart: unless-stopped
networks:
  default:
    name: devcontainer_default
[2022-11-04T16:11:40.837Z] Start: Run: docker events --format {{json .}} --filter event=start
[2022-11-04T16:11:40.839Z] PersistedPath=/Users/widmyern/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data, ContainerHasLabels=true
[2022-11-04T16:11:40.839Z] Container was created with these config files: /Users/widmyern/Documents/test/testproject/.devcontainer/docker-compose.yaml,/Users/widmyern/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1667571563561.yml
[2022-11-04T16:11:40.839Z] Expected to find a docker-compose file prefixed with docker-compose.devcontainer.build, but did not.
[2022-11-04T16:11:40.839Z] Restoring /Users/widmyern/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1667571563561.yml from persisted storage
[2022-11-04T16:11:40.839Z] Start: Run: docker-compose --project-name testproject_devcontainer -f /Users/widmyern/Documents/test/testproject/.devcontainer/docker-compose.yaml -f /Users/widmyern/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1667571563561.yml up -d --no-recreate
[2022-11-04T16:11:41.802Z] [+] Running 1/0
 ⠿ Container testproject_devcontainer-db-1   Started        0.0s
 ⠋ Container testproject_devcontainer-app-1  Starting       0.0s
[2022-11-04T16:11:41.901Z] [+] Running 1/2
[2022-11-04T16:11:41.901Z]  ⠿ Container testproject_devcontainer-db-1   Started        0.0s
 ⠙ Container testproject_devcontainer-app-1  Starting       0.1s
[2022-11-04T16:11:42.001Z] [+] Running 1/2
 ⠿ Container testproject_devcontainer-db-1   Started        0.0s
 ⠹ Container testproject_devcontainer-app-1  Starting       0.2s
[2022-11-04T16:11:42.102Z] 
[2022-11-04T16:11:42.102Z] [+] Running 1/2
 ⠿ Container testproject_devcontainer-db-1   Started        0.0s
 ⠸ Container testproject_devcontainer-app-1  Starting       0.3s
[2022-11-04T16:11:42.201Z] [+] Running 1/2
 ⠿ Container testproject_devcontainer-db-1   Started        0.0s
 ⠼ Container testproject_devcontainer-app-1  Starting       0.4s
[2022-11-04T16:11:42.301Z] [+] Running 1/2
 ⠿ Container testproject_devcontainer-db-1   Started        0.0s
 ⠴ Container testproject_devcontainer-app-1  Starting       0.5s
[2022-11-04T16:11:42.301Z] 
[2022-11-04T16:11:42.359Z] [+] Running 1/2
[2022-11-04T16:11:42.359Z]  ⠿ Container testproject_devcontainer-db-1   Started        0.0s
 ⠦ Container testproject_devcontainer-app-1  Starting       0.6s
Error response from daemon: Container b21f4f0992a24ddbe19b5a62f9658c977ffe1c80dc032ee6bb42bc65a4323d43 is restarting, wait until the container is running
[2022-11-04T16:11:42.364Z] Stop (1525 ms): Run: docker-compose --project-name testproject_devcontainer -f /Users/widmyern/Documents/test/testproject/.devcontainer/docker-compose.yaml -f /Users/widmyern/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1667571563561.yml up -d --no-recreate
[2022-11-04T16:11:42.365Z] Error: Command failed: docker-compose --project-name testproject_devcontainer -f /Users/widmyern/Documents/test/testproject/.devcontainer/docker-compose.yaml -f /Users/widmyern/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1667571563561.yml up -d --no-recreate
[2022-11-04T16:11:42.365Z]     at _S (/Users/widmyern/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:220:2970)
[2022-11-04T16:11:42.365Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-11-04T16:11:42.365Z]     at async AS (/Users/widmyern/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:204:2361)
[2022-11-04T16:11:42.365Z]     at async KS (/Users/widmyern/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:261:2177)
[2022-11-04T16:11:42.365Z]     at async co (/Users/widmyern/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:261:3110)
[2022-11-04T16:11:42.365Z]     at async LP (/Users/widmyern/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:360:9352)
[2022-11-04T16:11:42.365Z]     at async DP (/Users/widmyern/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:360:9108)
[2022-11-04T16:11:42.367Z] Stop (3575 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/widmyern/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/widmyern/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/widmyern/Documents/test/testproject --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/widmyern/Documents/test/testproject --log-level debug --log-format json --config /Users/widmyern/Documents/test/testproject/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-11-04T16:11:42.367Z] Exit code 1
[2022-11-04T16:11:42.368Z] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Users/widmyern/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/widmyern/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/widmyern/Documents/test/testproject --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/widmyern/Documents/test/testproject --log-level debug --log-format json --config /Users/widmyern/Documents/test/testproject/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-11-04T16:11:42.368Z] Exit code 1
</pre>

I think the issue is the generated command has a space in it (directory called "Application Support"), which wrecks the command executing correctly.

Steps to Reproduce:

1. Create a dev container on a Mac w/ your own docker-compose.yaml file and Dockerfile

Does this issue occur when you try this locally?: N/A (happens when dev container is built)
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Could you update to the latest version of VS Code (1.73) and the Dev Containers (0.262.3) extension (renamed from Remote-Containers) and retry?

**Comment by chrmarti** [comment]
Could you run the command locally (adding quotes for the paths with spaces, the extension spawns the command without shell, so they are not needed there):
```
docker-compose --project-name testproject_devcontainer -f /Users/widmyern/Documents/test/testproject/.devcontainer/docker-compose.yaml -f "/Users/widmyern/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1667919440175.yml" up -d --no-recreate
```

**Comment by LighthouseJ** [comment]
Sure thing, the above command was successful. :)

I ended up removing Postgres from the docker compose file temporarily because when starting, the image would get in a boot loop. I likely didn't finish setting it up, so I removed it for this test.
When I had only the one service, docker compose created the network and lone app service.

`
➜  testproject ✗ docker-compose --project-name testproject_devcontainer -f /Users/widmyern/Documents/test/testproject/.devcontainer-multi/docker-compose.yaml -f "/Users/widmyern/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1667919440175.yml" up -d --no-recreate
[+] Running 2/2
 ⠿ Network testproject_devcontainer_default  Created                                                                0.0s
 ⠿ Container testproject_devcontainer-app-1  Started                                                                0.3s
➜  testproject ✗ 
`

I also was able to attach VSCode to the running container and it successfully initialized the container.
`[16 ms] Dev Containers 0.264.0 in VS Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f).
[16 ms] Start: Resolving Remote
[17 ms] Setting up container: /testproject_devcontainer-app-1
[25 ms] Start: Run: docker inspect --type container /testproject_devcontainer-app-1
[178 ms] Start: Check Docker is running
[178 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[295 ms] Server API version: 1.41
[296 ms] Start: Inspecting container
[296 ms] Start: Run: docker inspect --type container 804be366a1a5bf6df24fea29757e8194e6599aa3b7fed9f0680ffc333737f6b7
[392 ms] Start: Run in container: /bin/sh
[394 ms] Start: Run in container: uname -m
[557 ms] x86_64
[557 ms] 
[557 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[579 ms] PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[579 ms] 
[580 ms] Start: Run in container: cat /etc/passwd
[596 ms] Start: Run in container: test -d /root/.vscode-server
[600 ms] 
[601 ms] 
[601 ms] Exit code 1
[601 ms] Start: Run in container: test -d /root/.vscode-remote
[604 ms] 
[604 ms] 
[604 ms] Exit code 1
[604 ms] Start: Run in container: test ! -f '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[632 ms] 
[632 ms] 
[632 ms] Start: Run in container: cat /root/.vscode-server/data/Machine/settings.json
[649 ms] 
[649 ms] cat: /root/.vscode-server/data/Machine/settings.json: No such file or directory
[649 ms] Exit code 1
[650 ms] Start: Run in container: test -d /root/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f
[653 ms] 
[653 ms] 
[653 ms] Exit code 1
[653 ms] Start: Run in container: test -d /vscode/vscode-server/bin/linux-x64/8fa188b2b301d36553cbc9ce1b0a146ccb93351f
[655 ms] 
[655 ms] 
[656 ms] Exit code 1
[656 ms] Installing VS Code Server for commit 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
[656 ms] Start: Downloading VS Code Server
[656 ms] 8fa188b2b301d36553cbc9ce1b0a146ccb93351f linux-x64 stable 
[13271 ms] Start: Installing VS Code Server
[13272 ms] Start: Run in container: mkdir -p /vscode/vscode-server/bin/linux-x64/8fa188b2b301d36553cbc9ce1b0a146ccb93351f_1668610359537
[13323 ms] 
[13324 ms] 
[13344 ms] Start: Run in container: (dd iflag=fullblock bs=8192 count=7958 2>/dev/null; dd iflag=fullblock bs=342 count=1 2>/dev/null) | tar --no-same-owner -xz -C /vscode/vscode-server/bin/linux-x64/8fa188b2b301d36553cbc9ce1b0a146ccb93351f_1668610359537
[16400 ms] 
[16400 ms] 
[16401 ms] Start: Run in container: mv -n /vscode/vscode-server/bin/linux-x64/8fa188b2b301d36553cbc9ce1b0a146ccb93351f_1668610359537/* /vscode/vscode-server/bin/linux-x64/8fa188b2b301d36553cbc9ce1b0a146ccb93351f && rmdir /vscode/vscode-server/bin/linux-x64/8fa188b2b301d36553cbc9ce1b0a146ccb93351f_1668610359537
[16436 ms] 
[16436 ms] 
[16436 ms] Start: Run in container: mkdir -p '/root/.vscode-server/bin' && ln -snf '/vscode/vscode-server/bin/linux-x64/8fa188b2b301d36553cbc9ce1b0a146ccb93351f' '/root/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f'
[16469 ms] 
[16469 ms] 
[16470 ms] Start: Run in container: touch '/vscode/vscode-server/bin/linux-x64/8fa188b2b301d36553cbc9ce1b0a146ccb93351f' && cd '/vscode/vscode-server/bin/linux-x64' && ls -td *[^_]????????????? | tail -n +10 | xargs rm -rf
[16470 ms] Start: Launching Dev Containers helper.
[16470 ms] ssh-agent: SSH_AUTH_SOCK in container (/tmp/vscode-ssh-auth-52bbedf697326da31d6c336e931bc47e59b7ac17.sock) forwarded to local host (/private/tmp/com.apple.launchd.G5v9fHSaCL/Listeners).
[16470 ms] Start: Run: gpgconf --list-dir agent-extra-socket
[16474 ms] Start: Run in container: /bin/sh
[16476 ms] userEnvProbe: loginInteractiveShell (default)
[16476 ms] Start: Run in container: echo ~
[16476 ms] userEnvProbe shell: /bin/bash
[16527 ms] 
[16527 ms] 
[16527 ms] Start: Run in container: # Test for /root/.ssh/known_hosts and ssh
[16549 ms] 
[16549 ms] 
[16549 ms] Start: Run in container: # Copy /Users/widmyern/.ssh/known_hosts to /root/.ssh/known_hosts
[16587 ms] 
[16587 ms] 
[16587 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --system --replace-all credential.helper '!f() { /root/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/node /tmp/vscode-remote-containers-52bbedf697326da31d6c336e931bc47e59b7ac17.js $*; }; f' || true
[16640 ms] 
[16640 ms] 
[16641 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd ; readlink /proc/$pid/ns/mnt ; cat /proc/$pid/stat | tr "
[16665 ms] /root
[16665 ms] 
[16665 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-52bbedf697326da31d6c336e931bc47e59b7ac17.js' >/tmp/vscode-remote-containers-52bbedf697326da31d6c336e931bc47e59b7ac17.js
[16683 ms] 
[16684 ms] 
[16684 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-52bbedf697326da31d6c336e931bc47e59b7ac17.js' >/tmp/vscode-remote-containers-server-52bbedf697326da31d6c336e931bc47e59b7ac17.js_1668610362950
[16720 ms] 
[16720 ms] 
[17119 ms] Start: Run in container: cat '/root/.vscode-server/data/Machine/.connection-token-8fa188b2b301d36553cbc9ce1b0a146ccb93351f' 2>/dev/null || (umask 377 && echo 'aa0c87ff-e796-4ef2-9522-4b51339e56da' >'/root/.vscode-server/data/Machine/.connection-token-8fa188b2b301d36553cbc9ce1b0a146ccb93351f-a25c345b-d55d-4171-babc-ca3065183a2c' && mv -n '/root/.vscode-server/data/Machine/.connection-token-8fa188b2b301d36553cbc9ce1b0a146ccb93351f-a25c345b-d55d-4171-babc-ca3065183a2c' '/root/.vscode-server/data/Machine/.connection-token-8fa188b2b301d36553cbc9ce1b0a146ccb93351f' && rm -f '/root/.vscode-server/data/Machine/.connection-token-8fa188b2b301d36553cbc9ce1b0a146ccb93351f-a25c345b-d55d-4171-babc-ca3065183a2c' && cat '/root/.vscode-server/data/Machine/.connection-token-8fa188b2b301d36553cbc9ce1b0a146ccb93351f')
[17181 ms] aa0c87ff-e796-4ef2-9522-4b51339e56da
[17181 ms] 
[17182 ms] Start: Starting VS Code Server
[17182 ms] Start: Preparing Extensions
[17182 ms] Start: Run in container: test ! -f '/root/.vscode-server/data/Machine/.installExtensionsMarker' && set -o noclobber && mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.installExtensionsMarker' ; } 2> /dev/null
[17203 ms] 
[17203 ms] 
[17206 ms] Extensions cache, install extensions: None
[17206 ms] Start: Run in container: test -d /root/.vscode-server/extensionsCache && ls /root/.vscode-server/extensionsCache || true
[17209 ms] 
[17209 ms] 
[17209 ms] Start: Run in container: test -d /vscode/vscode-server/extensionsCache && ls /vscode/vscode-server/extensionsCache || true
[17231 ms] mutantdino.resourcemonitor-1.0.7
rust-lang.rust-analyzer-0.3.1277-linux-arm64
rust-lang.rust-analyzer-0.3.1285-linux-arm64
serayuzgur.crates-0.5.10
tamasfe.even-better-toml-0.19.0
vadimcn.vscode-lldb-1.8.1
[17232 ms] 
[17232 ms] Extensions cache, link in container: None
[17232 ms] Start: Run in container: /root/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/bin/code-server --log debug --force-disable-user-env --server-data-dir /root/.vscode-server --use-host-proxy --telemetry-level off --accept-server-license-terms --host 127.0.0.1 --port 0 --connection-token-file /root/.vscode-server/data/Machine/.connection-token-8fa188b2b301d36553cbc9ce1b0a146ccb93351f --extensions-download-dir /root/.vscode-server/extensionsCache --start-server --disable-websocket-compression
[17512 ms] userEnvProbe PATHs:
Probe:     '/usr/local/cargo/bin:/usr/local/cargo/bin:/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/bin'
Container: '/usr/local/cargo/bin:/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
Merged:    '/usr/local/cargo/bin:/usr/local/cargo/bin:/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/bin'
[17867 ms] *
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
[17896 ms] Server bound to 127.0.0.1:37557 (IPv4)
Extension host agent listening on 37557

[17897 ms] Start: Run in container: echo 37557 >'/root/.vscode-server/data/Machine/.devport-8fa188b2b301d36553cbc9ce1b0a146ccb93351f'
[17900 ms] 
[17900 ms] 
[17900 ms] Port forwarding for container port 37557 starts listening on local port.
[17901 ms] Port forwarding local port 37557 to container port 37557
[17901 ms] Start: Run in container: mkdir -p '/root/.vscode-server/data/Machine' && CONTENT="$(cat '/root/.vscode-server/data/Machine/.onCreateCommandMarker' 2>/dev/null || echo ENOENT)" && [ "${CONTENT:-2022-11-16T14:52:04.947306007Z}" != '2022-11-16T14:52:04.947306007Z' ] && echo '2022-11-16T14:52:04.947306007Z' > '/root/.vscode-server/data/Machine/.onCreateCommandMarker'
[17938 ms] 
[17938 ms] 
[17939 ms] Start: Run in container: mkdir -p '/root/.vscode-server/data/Machine' && CONTENT="$(cat '/root/.vscode-server/data/Machine/.updateContentCommandMarker' 2>/dev/null || echo ENOENT)" && [ "${CONTENT:-2022-11-16T14:52:04.947306007Z}" != '2022-11-16T14:52:04.947306007Z' ] && echo '2022-11-16T14:52:04.947306007Z' > '/root/.vscode-server/data/Machine/.updateContentCommandMarker'
[17977 ms] 
[17977 ms] 
[17978 ms] Start: Run in container: mkdir -p '/root/.vscode-server/data/Machine' && CONTENT="$(cat '/root/.vscode-server/data/Machine/.postCreateCommandMarker' 2>/dev/null || echo ENOENT)" && [ "${CONTENT:-2022-11-16T14:52:04.947306007Z}" != '2022-11-16T14:52:04.947306007Z' ] && echo '2022-11-16T14:52:04.947306007Z' > '/root/.vscode-server/data/Machine/.postCreateCommandMarker'
[17978 ms] Start: Run in container: /bin/sh -c # Watch installed extensions
[17978 ms] Start: Run in container: /bin/sh -c # Watch machine settings
[17984 ms] Port forwarding connection from 65099 > 37557 > 37557 in the container.
[17984 ms] Start: Run in container: /root/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/node -e 
[18017 ms] 
[18017 ms] 
[18019 ms] Start: Run in container: # Test for /root/.gitconfig and git
[18037 ms] 
[18037 ms] 
[18038 ms] Start: Run in container: # Copy /Users/widmyern/.gitconfig to /root/.gitconfig
[18076 ms] 
[18076 ms] 
[18077 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --global --replace-all credential.helper '!f() { /root/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/node /tmp/vscode-remote-containers-52bbedf697326da31d6c336e931bc47e59b7ac17.js $*; }; f' || true
[18106 ms] 
[18106 ms] 
[18106 ms] Start: Run in container: mkdir -p '/root/.vscode-server/data/Machine' && CONTENT="$(cat '/root/.vscode-server/data/Machine/.postStartCommandMarker' 2>/dev/null || echo ENOENT)" && [ "${CONTENT:-2022-11-16T14:52:05.208134883Z}" != '2022-11-16T14:52:05.208134883Z' ] && echo '2022-11-16T14:52:05.208134883Z' > '/root/.vscode-server/data/Machine/.postStartCommandMarker'
[18148 ms] 
[18148 ms] 
[18695 ms] Port forwarding 65099 > 37557 > 37557 stderr: Connection established
[19171 ms] [14:52:45] Extension host agent started.
[19198 ms] Port forwarding connection from 65104 > 37557 > 37557 in the container.
[19198 ms] Start: Run in container: /root/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/node -e 
[19290 ms] [14:52:45] [127.0.0.1][eac2a803][ManagementConnection] New connection established.
[19796 ms] Port forwarding 65104 > 37557 > 37557 stderr: Connection established
[20561 ms] [14:52:46] [127.0.0.1][b79d6106][ExtensionHostConnection] New connection established.
[20612 ms] [14:52:46] [127.0.0.1][b79d6106][ExtensionHostConnection] <543> Launched Extension Host Process.
[78201 ms] Start: Run in container: /bin/sh -c # Watch installed extensions
[83380 ms] Start: Run in container: /bin/sh -c # Watch machine settings
[143394 ms] Start: Run in container: /bin/sh -c # Watch installed extensions
[148824 ms] Start: Run in container: /bin/sh -c # Watch machine settings
[208544 ms] Start: Run in container: /bin/sh -c # Watch installed extensions
[213946 ms] Start: Run in container: /bin/sh -c # Watch machine settings
`
