### ISSUE TITLE
Version 0.262.3 breaks container when reloading extension

### ISSUE THREAD

**Issue by JeremyGrieshop** [microsoft/vscode-remote-release#7472]
- VSCode Version: 1.73.0
- Local OS Version: MacOS 12.6
- Remote OS Version: Ubuntu 20
- Remote Extension/Connection Type: Containers
- Logs:  (Included at the bottom)

Steps to Reproduce:

1. New version of Dev Containers requires Restart
2. Restart to load new version fails to reconnect to container

It looks like there's a typo somewhere in the container name:

`Error: No such image: profile_devcontainer-node-composer`

On my system that image does not exist. However, the following image does:  `profile_devcontainer_node-composer`.  You will notice that it should be `_` instead of `-`. So, somewhere a process is constructing the wrong image name.

```
[26 ms] Dev Containers 0.262.3 in VS Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f).
[26 ms] Start: Resolving Remote
[32 ms] Start: Check Docker is running
[32 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[103 ms] Server API version: 1.41
[103 ms] Start: Run: docker volume ls -q
[152 ms] Start: Run: docker build -f /var/folders/wt/l8_fz7qn55d9xc9wtp7wgn480000gq/T/vsch/bootstrap-image/0.262.3/bootstrap.Dockerfile -t vsc-volume-bootstrap /var/folders/wt/l8_fz7qn55d9xc9wtp7wgn480000gq/T/vsch/bootstrap-image/0.262.3
[+] Building 0.5s (9/9) FINISHED                                                
 => [internal] load build definition from bootstrap.Dockerfile             0.0s
 => => transferring dockerfile: 47B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for mcr.microsoft.com/devcontainers/base:0-a  0.4s
 => [1/4] FROM mcr.microsoft.com/devcontainers/base:0-alpine-3.16@sha256:  0.0s
 => [internal] load build context                                          0.0s
 => => transferring context: 5.90kB                                        0.0s
 => CACHED [2/4] RUN apk add --no-cache  nodejs  python3  npm  make  g++   0.0s
 => CACHED [3/4] RUN cd && npm i node-pty                                  0.0s
 => CACHED [4/4] COPY .vscode-remote-containers /root/.vscode-remote-cont  0.0s
 => exporting to image                                                     0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:ce20705b02fdfed9c326d6c3114b6bb7616174ca35b08  0.0s
 => => naming to docker.io/library/vsc-volume-bootstrap                    0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[1030 ms] Cloning Github repository: unknown-owner/profile into /workspaces/profile

[1030 ms] Start: Run: docker run -d --mount type=volume,src=profile,dst=/workspaces -v /var/run/docker.sock:/var/run/docker.sock vsc-volume-bootstrap sleep infinity
[1263 ms] Start: Run in container: /bin/sh
[1265 ms] Start: Launching Dev Containers helper.
[1266 ms] Start: Run: gpgconf --list-dir agent-extra-socket
[1286 ms] /Users/jeremy/.gnupg/S.gpg-agent.extra
[1286 ms] 
[1287 ms] Start: Run in container: gpgconf --list-dir agent-socket
[1358 ms] /root/.gnupg/S.gpg-agent
[1358 ms] 
[1358 ms] Start: Run in container: gpgconf --list-dir homedir
[1360 ms] /root/.gnupg
[1360 ms] 
[1360 ms] Start: Run in container: ls '/root/.gnupg/private-keys-v1.d' 2>/dev/null
[1362 ms] 
[1362 ms] 
[1362 ms] Exit code 2
[1362 ms] Start: Run in container: mkdir -p -m 700 '/root/.gnupg'
[1363 ms] Start: Run in container: /bin/sh
[1364 ms] Start: Run in container: echo ~
[1364 ms] 
[1364 ms] 
[1364 ms] Start: Run: gpgconf --list-dir homedir
[1373 ms] /Users/jeremy/.gnupg
[1373 ms] 
[1373 ms] Start: Run in container: gpgconf --list-dir homedir
[1375 ms] /root/.gnupg
[1375 ms] 
[1375 ms] Start: Run in container: # Test for /root/.gnupg/pubring.kbx and gpg
[1377 ms] 
[1377 ms] 
[1378 ms] Start: Run in container: # Copy /Users/jeremy/.gnupg/pubring.kbx to /root/.gnupg/pubring.kbx
[1396 ms] 
[1397 ms] 
[1397 ms] Start: Run in container: # Test for /root/.gnupg/trustdb.gpg and gpg
[1399 ms] 
[1399 ms] 
[1399 ms] Start: Run in container: # Copy /Users/jeremy/.gnupg/trustdb.gpg to /root/.gnupg/trustdb.gpg
[1402 ms] 
[1402 ms] 
[1402 ms] Start: Run: gpg-connect-agent updatestartuptty /bye
[1468 ms] /root
[1468 ms] 
[1468 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-b412bf814aa9b5ec001be5b17ceb42bccf953037.js' >/tmp/vscode-remote-containers-b412bf814aa9b5ec001be5b17ceb42bccf953037.js
[1470 ms] 
[1470 ms] 
[1470 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-b412bf814aa9b5ec001be5b17ceb42bccf953037.js' >/tmp/vscode-remote-containers-server-b412bf814aa9b5ec001be5b17ceb42bccf953037.js_1667592214454
[1481 ms] 
[1481 ms] 
[1483 ms] Start: Run in container: # Test for /root/.gitconfig and git
[1485 ms] 
[1485 ms] 
[1485 ms] Start: Run in container: # Copy /Users/jeremy/.gitconfig to /root/.gitconfig
[1488 ms] 
[1488 ms] 
[1489 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --global --replace-all credential.helper '!f() { node /tmp/vscode-remote-containers-b412bf814aa9b5ec001be5b17ceb42bccf953037.js $*; }; f' || true
[1495 ms] 
[1496 ms] 
[1496 ms] Start: Run in container: # Test for /root/.ssh/known_hosts and ssh
[1498 ms] 
[1498 ms] 
[1498 ms] Start: Run in container: # Copy /Users/jeremy/.ssh/known_hosts to /root/.ssh/known_hosts
[1501 ms] 
[1501 ms] 
[1541 ms] Start: Run in container: cat /workspaces/profile/.devcontainer/devcontainer.json 2>/dev/null
[1544 ms] Start: Run in container: cat /workspaces/profile/.devcontainer/devcontainer.json 2>/dev/null
[1546 ms] The options 'workspaceMount' or 'workspaceFolder' are ignored when cloning a repository into a volume.
[1546 ms] Start: Run in container: cat <<'EOF-/tmp/devcontainer-ae2582af-9530-4276-85ba-927ba8cfb8dd.json' >/tmp/devcontainer-ae2582af-9530-4276-85ba-927ba8cfb8dd.json_1667592214530
[1550 ms] 
[1550 ms] 
[1550 ms] Start: Run in container: docker volume ls -q
[1868 ms] Start: Run in container: docker ps -q -a --filter label=vsch.local.repository=https://bitbucket.*****/profile.git --filter label=vsch.local.repository.volume=profile --filter label=vsch.local.repository.folder=profile --filter label=vsch.quality=stable
[1991 ms] Start: Run in container: docker ps -q -a --filter label=vsch.local.repository=https://bitbucket.******/profile.git --filter label=vsch.local.repository.volume=profile --filter label=vsch.local.repository.folder=profile
[2119 ms] Start: Run in container: docker inspect --type container 8bc6bff1cb55
[2434 ms] Start: Run in container: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.262.3/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /workspaces/profile --workspace-mount-consistency cached --id-label vsch.local.repository=https://bitbucket.******/profile.git --id-label vsch.local.repository.volume=profile --id-label vsch.local.repository.folder=profile --log-level debug --log-format json --config /workspaces/profile/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-ae2582af-9530-4276-85ba-927ba8cfb8dd.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=profile,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root true
[2690 ms] (node:144) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2690 ms] (Use `node --trace-deprecation ...` to show where the warning was created)
[2691 ms] @devcontainers/cli 0.23.2. Node.js v16.17.1. linux 5.15.49-linuxkit arm64.
[2691 ms] Start: Run: docker buildx version
[2763 ms] github.com/docker/buildx v0.8.2 6224def4dd2c3d347eee19db595348c50d7cb491
[2763 ms] 
[2763 ms] Start: Resolving Remote
[2768 ms] Start: Run: docker-compose version --short
[2771 ms] Start: Run: docker compose version --short
[2835 ms] Docker Compose version: 2.12.2
[2837 ms] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=profile_devcontainer --filter label=com.docker.compose.service=node-composer
[2869 ms] Start: Run: docker inspect --type container 8bc6bff1cb55
[2897 ms] Start: Run: docker compose -f /workspaces/profile/.devcontainer/docker-compose.yml --profile * config
[2983 ms] name: devcontainer
services:
  node-composer:
    build:
      context: /workspaces/profile/.devcontainer
      dockerfile: Dockerfile
    command:
    - sleep
    - infinity
    networks:
      default: null
    ports:
    - mode: ingress
      target: 3000
      published: "3000"
      protocol: tcp
    privileged: true
    volumes:
    - type: volume
      source: profile-workspace-vol
      target: /workspace
      volume: {}
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      bind:
        create_host_path: true
networks:
  default:
    name: devcontainer_default
volumes:
  profile-workspace-vol:
    name: devcontainer_profile-workspace-vol
[2986 ms] Start: Run: docker -v
[3012 ms] Start: Run: docker events --format {{json .}} --filter event=start
[3014 ms] PersistedPath=/tmp/devcontainercli-root, ContainerHasLabels=true
[3014 ms] Container was created with these config files: /workspaces/profile/.devcontainer/docker-compose.yml,/tmp/docker-compose/docker-compose.devcontainer.containerFeatures-1664912281805.yml
[3015 ms] Expected to find a docker-compose file prefixed with docker-compose.devcontainer.build, but did not.
[3015 ms] Expected /tmp/docker-compose/docker-compose.devcontainer.containerFeatures-1664912281805.yml to exist, but it did not
[3016 ms] Start: Run: docker compose -f /workspaces/profile/.devcontainer/docker-compose.yml --profile * config
[3091 ms] name: devcontainer
services:
  node-composer:
    build:
      context: /workspaces/profile/.devcontainer
      dockerfile: Dockerfile
    command:
    - sleep
    - infinity
    networks:
      default: null
    ports:
    - mode: ingress
      target: 3000
      published: "3000"
      protocol: tcp
    privileged: true
    volumes:
    - type: volume
      source: profile-workspace-vol
      target: /workspace
      volume: {}
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
      bind:
        create_host_path: true
networks:
  default:
    name: devcontainer_default
volumes:
  profile-workspace-vol:
    name: devcontainer_profile-workspace-vol
[3093 ms] Start: Run: docker inspect --type image node
[3119 ms] local container features stored at: /root/.vscode-remote-containers/dist/dev-containers-cli-0.262.3/dist/node_modules/vscode-dev-containers/container-features
[3120 ms] Start: Run: tar --no-same-owner -x -f -
[3144 ms] Docker Compose override file for building image:
version: '3'

services:
  node-composer:
    build:
      dockerfile: /tmp/devcontainercli-root/container-features/0.23.2-1667592216102/Dockerfile-with-features
      args:
        - BUILDKIT_INLINE_CACHE=1
        - _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label

[3145 ms] Start: Run: docker inspect --type image profile_devcontainer-node-composer
[3743 ms] Error fetching image details: No manifest found for docker.io/library/profile_devcontainer-node-composer.
[3744 ms] Start: Run: docker pull profile_devcontainer-node-composer
Using default tag: latest
Error response from daemon: pull access denied for profile_devcontainer-node-composer, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
[4717 ms] []
[4717 ms] Error: No such image: profile_devcontainer-node-composer

[4728 ms] Error: Command failed: docker inspect --type image profile_devcontainer-node-composer
[4729 ms]     at Qse (/root/.vscode-remote-containers/dist/dev-containers-cli-0.262.3/dist/spec-node/devContainersSpecCLI.js:1831:2820)
[4729 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[4729 ms]     at async voe (/root/.vscode-remote-containers/dist/dev-containers-cli-0.262.3/dist/spec-node/devContainersSpecCLI.js:1893:2222)
[4729 ms]     at async Xf (/root/.vscode-remote-containers/dist/dev-containers-cli-0.262.3/dist/spec-node/devContainersSpecCLI.js:1893:3212)
[4729 ms]     at async Jae (/root/.vscode-remote-containers/dist/dev-containers-cli-0.262.3/dist/spec-node/devContainersSpecCLI.js:2013:15058)
[4729 ms]     at async Wae (/root/.vscode-remote-containers/dist/dev-containers-cli-0.262.3/dist/spec-node/devContainersSpecCLI.js:2013:14812)
[4755 ms] Exit code 1
[4755 ms] Start: Run: docker rm -f e4dcd02d5743289a20058749b2ea7803aa45d2e6bf3e3749064d90f1ee6bb267
[4761 ms] Command failed: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.262.3/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /workspaces/profile --workspace-mount-consistency cached --id-label vsch.local.repository=https://bitbucket.*****/profile.git --id-label vsch.local.repository.volume=profile --id-label vsch.local.repository.folder=profile --log-level debug --log-format json --config /workspaces/profile/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-ae2582af-9530-4276-85ba-927ba8cfb8dd.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=profile,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root true
[4762 ms] Exit code 1
[4952 ms] Container server terminated (code: 137, signal: null).
```

**Comment by JeremyGrieshop** [comment]
I was able to work around this issue by re-tagging the image:

`docker tag profile_devcontainer_node-composer profile_devcontainer-node-composer`

**Comment by chrmarti** [comment]
Docker Compose 2.8.0 changed this separator from `_` to `-`. Did you recently update Docker Compose/Docker Desktop?

**Comment by chrmarti** [comment]
We pick the separator based on the installed version of Docker Compose. This might have been an existing container (referencing the old image) from before the Docker update.

**Comment by chrmarti** [comment]
Assuming we are past this hump. Closing, thanks.
