### ISSUE TITLE
CentOS 6: Unauthorized client refused

### ISSUE THREAD

**Issue by bmingles** [microsoft/vscode-remote-release#748]
- VSCode Version: 1.35.1
- Local OS Version: macOS Mojave 10.14.4
- Remote OS Version: CentOS 6
- Remote Extension/Connection Type: SSH

Steps to Reproduce:
1. On CentOS 6 I have glibc 2.23 installed via linuxbrew

```
ldd --version
ldd (GNU libc) 2.23
```

2. Command Palette -> Remote-SSH: Connect to Host... 

## Result

A new vscode window opens and terminal: SSH Tunnel shows
```Connected to SSH Host - Please do not close this terminal```

An error dialog pops up in bottom right:
```Failed to connect to the remote extension host server (Error: Connection error: Unauthorized client refused.)```

## Outputs

**Server log: ~/.vscode-server/.c7d83e57cd18f18026a8162d042843bda1bcf21f.log**
```
*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*

IP Address: XX.XX.XX.XX
Extension host agent listening on 45334
Unauthorized client refused.
Unauthorized client refused.
```

**Terminal: SSH Tunnel**
```Connected to SSH Host - Please do not close this terminal```

**Output: Remote SSH**
```
"install" terminal command done
Received install output: 9e8afd44-cd56-4699-bd49-cde9eef0c7ef==45334==
Server is listening on port 45334
Spawning tunnel with: ssh -t  "xxxxxx.yyyyyyyyy.com" -L localhost:49930:localhost:45334 "echo -e 'Connected to SSH Host - Please do not close this terminal' && sleep infinity"
Spawned SSH tunnel between local port 49930 and remote port 45334
Waiting for ssh tunnel to be ready
Tunneling remote port 45334 to local port 49930
Resolving "ssh-remote+xxxxxx.yyyyyyyyy.com" to "localhost:49930", attempt: 1
> Connected to SSH Host - Please do not close this terminal
```

**Output: Log (Window)**
```
[2019-06-20 13:23:47.945] [renderer23] [error] Connection error: Unauthorized client refused.: Error: Connection error: Unauthorized client refused.
    at v (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1548:662)
    at t.onControlMessage.o (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1547:601)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:983)
    at a (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:322:248)
    at e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:322:294)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:983)
    at S._receiveMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:331:324)
    at S._socketDisposables.push._socketReader.onMessage.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:328:437)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:983)
    at g.acceptChunk (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:325:17)
    at _register._socket.onData.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:324:372)
    at Socket.t (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:333:519)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:636:20)
[2019-06-20 13:23:47.946] [renderer23] [error] Cannot read property 'extensions' of null: TypeError: Cannot read property 'extensions' of null
    at P.<anonymous> (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3893:223)
    at Generator.next (<anonymous>)
    at r (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:34:454)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-06-20 13:23:47.946] [renderer23] [error] Connection error: Unauthorized client refused.: Error: Connection error: Unauthorized client refused.
    at v (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1548:662)
    at t.onControlMessage.o (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1547:601)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:983)
    at a (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:322:248)
    at e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:322:294)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:983)
    at S._receiveMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:331:324)
    at S._socketDisposables.push._socketReader.onMessage.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:328:437)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:983)
    at g.acceptChunk (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:325:17)
    at _register._socket.onData.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:324:372)
    at Socket.t (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:333:519)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:636:20)
```

**Comment by roblourens** [comment]
You probably need https://code.visualstudio.com/docs/remote/linux#_updating-glibc-and-libstdc-on-rhel-centos-6

**Comment by bmingles** [comment]
@roblourens Thank you. I have already looked into this option, but I don't have permissions to install anything on this server. Also, I believe I have an updated version of glibc already installed so not sure this is the issue.

**Comment by roblourens** [comment]
Ok. I don't know exactly what the problem is, but most likely it is something covered by https://github.com/microsoft/vscode-remote-release/issues/103

**Comment by bmingles** [comment]
I'm confused why this was closed. I have read through #103 already, but it doesn't resolve my issue, and is also closed. Are there any additional details I can provide that would be helpful?

**Comment by roblourens** [comment]
#103 covers a lot of people reporting the "Unauthorized client" error. I think there are multiple reasons why people get that, and I don't know what all of them are yet. One of them is having an old version of glibc, that doesn't seem to be the case for you and also for some other people. So I don't know what the problem is with your setup but I am trying to centralize the "Unauthorized client" issues until we figure out what else might be behind it. Most likely it's related to our native dependencies not running on your system for some reason. Sorry I don't have a better answer yet

**Comment by bmingles** [comment]
Ok thank you. So is #103 the best issue to keep an eye on for a resolution if one is found?

**Comment by roblourens** [comment]
Yes
