### ISSUE TITLE
error: could not find /tmp/devcontainercli-username/container-features

### ISSUE THREAD

**Issue by jacquespeeters** [microsoft/vscode-remote-release#7480]
- VSCode Version: 1.73.0 
- Local OS Version: Ubuntu 22.04.1 LTS - 64 bit
- Remote OS Version:
- Logs:
```
[2022-11-06T12:14:03.704Z] Dev Containers 0.262.3 in VS Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f).
[2022-11-06T12:14:03.704Z] Start: Resolving Remote
[2022-11-06T12:14:03.721Z] Setting up container for folder or workspace: /home/jacques/Documents/code/prix_immo
[2022-11-06T12:14:03.751Z] Start: Check Docker is running
[2022-11-06T12:14:03.751Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2022-11-06T12:14:03.794Z] Stop (43 ms): Run: docker version --format {{.Server.APIVersion}}
[2022-11-06T12:14:03.795Z] Server API version: 1.41
[2022-11-06T12:14:03.795Z] Stop (44 ms): Check Docker is running
[2022-11-06T12:14:03.795Z] Start: Run: docker volume ls -q
[2022-11-06T12:14:03.833Z] Stop (38 ms): Run: docker volume ls -q
[2022-11-06T12:14:03.837Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/jacques/Documents/code/prix_immo --filter label=vsch.quality=stable
[2022-11-06T12:14:03.877Z] Stop (40 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/home/jacques/Documents/code/prix_immo --filter label=vsch.quality=stable
[2022-11-06T12:14:03.878Z] Start: Run: /usr/share/code/code --ms-enable-electron-run-as-node /home/jacques/.vscode/extensions/ms-vscode-remote.remote-containers-0.262.3/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/jacques/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/jacques/Documents/code/prix_immo --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/jacques/Documents/code/prix_immo --log-level debug --log-format json --config /home/jacques/Documents/code/prix_immo/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-11-06T12:14:04.051Z] (node:43931) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2022-11-06T12:14:04.051Z] (Use `code --trace-deprecation ...` to show where the warning was created)
[2022-11-06T12:14:04.052Z] @devcontainers/cli 0.23.2. Node.js v16.14.2. linux 5.15.0-52-generic x64.
[2022-11-06T12:14:04.052Z] Start: Run: docker buildx version
[2022-11-06T12:14:04.120Z] Stop (68 ms): Run: docker buildx version
[2022-11-06T12:14:04.121Z] github.com/docker/buildx v0.8.2 6224def4dd2c3d347eee19db595348c50d7cb491
[2022-11-06T12:14:04.121Z] 
[2022-11-06T12:14:04.121Z] Start: Resolving Remote
[2022-11-06T12:14:04.122Z] Start: Run: git rev-parse --show-cdup
[2022-11-06T12:14:04.125Z] Stop (3 ms): Run: git rev-parse --show-cdup
[2022-11-06T12:14:04.126Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/jacques/Documents/code/prix_immo
[2022-11-06T12:14:04.163Z] Stop (37 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/jacques/Documents/code/prix_immo
[2022-11-06T12:14:04.165Z] Start: Run: docker inspect --type image python:3.8
[2022-11-06T12:14:04.202Z] Stop (37 ms): Run: docker inspect --type image python:3.8
[2022-11-06T12:14:04.204Z] local container features stored at: /home/jacques/.vscode/extensions/ms-vscode-remote.remote-containers-0.262.3/dist/node_modules/vscode-dev-containers/container-features
[2022-11-06T12:14:04.204Z] Start: Run: tar --no-same-owner -x -f -
[2022-11-06T12:14:04.216Z] Stop (12 ms): Run: tar --no-same-owner -x -f -
[2022-11-06T12:14:04.218Z] Start: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-jacques/container-features/0.23.2-1667736844203/Dockerfile-with-features -t vsc-prix_immo-43ddd1ec117e3afa111d8027a8636c7a --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /home/jacques/Documents/code/prix_immo
[2022-11-06T12:14:04.310Z] [+] Building 0.0s (0/0)                                                         
[2022-11-06T12:14:04.310Z] error: could not find /tmp/devcontainercli-jacques/container-features/0.23.2-1667736844203: stat /tmp/devcontainercli-jacques/container-features/0.23.2-1667736844203: no such file or directory
[2022-11-06T12:14:04.314Z] Stop (96 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-jacques/container-features/0.23.2-1667736844203/Dockerfile-with-features -t vsc-prix_immo-43ddd1ec117e3afa111d8027a8636c7a --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /home/jacques/Documents/code/prix_immo
[2022-11-06T12:14:04.315Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-jacques/container-features/0.23.2-1667736844203/Dockerfile-with-features -t vsc-prix_immo-43ddd1ec117e3afa111d8027a8636c7a --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /home/jacques/Documents/code/prix_immo
[2022-11-06T12:14:04.315Z]     at doe (/home/jacques/.vscode/extensions/ms-vscode-remote.remote-containers-0.262.3/dist/spec-node/devContainersSpecCLI.js:1888:1635)
[2022-11-06T12:14:04.315Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-11-06T12:14:04.315Z]     at async pF (/home/jacques/.vscode/extensions/ms-vscode-remote.remote-containers-0.262.3/dist/spec-node/devContainersSpecCLI.js:1887:1973)
[2022-11-06T12:14:04.315Z]     at async eT (/home/jacques/.vscode/extensions/ms-vscode-remote.remote-containers-0.262.3/dist/spec-node/devContainersSpecCLI.js:1887:901)
[2022-11-06T12:14:04.315Z]     at async voe (/home/jacques/.vscode/extensions/ms-vscode-remote.remote-containers-0.262.3/dist/spec-node/devContainersSpecCLI.js:1893:2049)
[2022-11-06T12:14:04.315Z]     at async Xf (/home/jacques/.vscode/extensions/ms-vscode-remote.remote-containers-0.262.3/dist/spec-node/devContainersSpecCLI.js:1893:3212)
[2022-11-06T12:14:04.315Z]     at async Jae (/home/jacques/.vscode/extensions/ms-vscode-remote.remote-containers-0.262.3/dist/spec-node/devContainersSpecCLI.js:2013:15058)
[2022-11-06T12:14:04.315Z]     at async Wae (/home/jacques/.vscode/extensions/ms-vscode-remote.remote-containers-0.262.3/dist/spec-node/devContainersSpecCLI.js:2013:14812)
[2022-11-06T12:14:04.318Z] Stop (440 ms): Run: /usr/share/code/code --ms-enable-electron-run-as-node /home/jacques/.vscode/extensions/ms-vscode-remote.remote-containers-0.262.3/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/jacques/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/jacques/Documents/code/prix_immo --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/jacques/Documents/code/prix_immo --log-level debug --log-format json --config /home/jacques/Documents/code/prix_immo/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-11-06T12:14:04.318Z] Exit code 1
[2022-11-06T12:14:04.322Z] Command failed: /usr/share/code/code --ms-enable-electron-run-as-node /home/jacques/.vscode/extensions/ms-vscode-remote.remote-containers-0.262.3/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/jacques/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/jacques/Documents/code/prix_immo --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/jacques/Documents/code/prix_immo --log-level debug --log-format json --config /home/jacques/Documents/code/prix_immo/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-11-06T12:14:04.322Z] Exit code 1
```

Whereas directory exists
```
ls -ltrh /tmp/devcontainercli-jacques/container-features/0.23.2-1667736844203
drwxrwxr-x 2 jacques jacques 4,0K nov.   5 17:49 local-cache
-rw-rw-r-- 1 jacques jacques  563 nov.   6 13:14 Dockerfile-with-features
```

Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: ???

Looks like a permission issue? `docker run hello-world` works correctly so it seems related to VSCode / remote-containers :(

**Comment by jacquespeeters** [comment]
Clean install solved it ...
