### ISSUE TITLE
Can't create new-style devcontainers on M1 Mac

### ISSUE THREAD

**Issue by tclasen** [microsoft/vscode-remote-release#7488]
devcontainer.json
```json
{
	"name": "Python 3",
	"image": "mcr.microsoft.com/devcontainers/python:3.10-bullseye",
	"features": {
		"ghcr.io/devcontainers/features/node:1": {
			"version": "lts"
		}
	}
}

```

remoteContainers-*.log
```log
[2022-11-08T19:40:02.850Z] Dev Containers 0.262.3 in VS Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f).
[2022-11-08T19:40:02.850Z] Start: Resolving Remote
[2022-11-08T19:40:02.860Z] Setting up container for folder or workspace: /Users/name@email.com/projects/experiment
[2022-11-08T19:40:02.862Z] Start: Check Docker is running
[2022-11-08T19:40:02.863Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2022-11-08T19:40:03.290Z] Stop (427 ms): Run: docker version --format {{.Server.APIVersion}}
[2022-11-08T19:40:03.290Z] Server API version: 1.43
[2022-11-08T19:40:03.290Z] Stop (428 ms): Check Docker is running
[2022-11-08T19:40:03.291Z] Start: Run: docker volume ls -q
[2022-11-08T19:40:03.341Z] Stop (50 ms): Run: docker volume ls -q
[2022-11-08T19:40:03.346Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/name@email.com/projects/experiment --filter label=vsch.quality=stable
[2022-11-08T19:40:03.397Z] Stop (51 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/Users/name@email.com/projects/experiment --filter label=vsch.quality=stable
[2022-11-08T19:40:03.397Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/name@email.com/projects/experiment
[2022-11-08T19:40:03.466Z] Stop (69 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/name@email.com/projects/experiment
[2022-11-08T19:40:03.466Z] Start: Run: docker inspect --type container b27ab68ff9c0
[2022-11-08T19:40:03.523Z] Stop (57 ms): Run: docker inspect --type container b27ab68ff9c0
[2022-11-08T19:40:03.524Z] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/name@email.com/.vscode/extensions/ms-vscode-remote.remote-containers-0.262.3/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/name@email.com/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/name@email.com/projects/experiment --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/name@email.com/projects/experiment --log-level debug --log-format json --config /Users/name@email.com/projects/experiment/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-11-08T19:40:03.682Z] (node:48122) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2022-11-08T19:40:03.682Z] (Use `Code Helper --trace-deprecation ...` to show where the warning was created)
[2022-11-08T19:40:03.683Z] @devcontainers/cli 0.23.2. Node.js v16.14.2. darwin 22.1.0 arm64.
[2022-11-08T19:40:03.683Z] Start: Run: docker buildx version
[2022-11-08T19:40:04.224Z] Stop (541 ms): Run: docker buildx version
[2022-11-08T19:40:04.225Z] github.com/docker/buildx v0.9.1 ed00243a0ce2a0aee75311b06e32d33b44729689
[2022-11-08T19:40:04.225Z] 
[2022-11-08T19:40:04.225Z] Start: Resolving Remote
[2022-11-08T19:40:04.226Z] Start: Run: git rev-parse --show-cdup
[2022-11-08T19:40:04.232Z] Stop (6 ms): Run: git rev-parse --show-cdup
[2022-11-08T19:40:04.233Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/name@email.com/projects/experiment
[2022-11-08T19:40:04.306Z] Stop (73 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/name@email.com/projects/experiment
[2022-11-08T19:40:04.307Z] Start: Run: docker inspect --type container b27ab68ff9c0
[2022-11-08T19:40:04.375Z] Stop (68 ms): Run: docker inspect --type container b27ab68ff9c0
[2022-11-08T19:40:04.375Z] Start: Starting container
[2022-11-08T19:40:04.375Z] Start: Run: docker start b27ab68ff9c0a9c5b1da4f796a30446c2953f15543f35d1030ba608d5f1c1dc7
[2022-11-08T19:40:04.565Z] Stop (190 ms): Run: docker start b27ab68ff9c0a9c5b1da4f796a30446c2953f15543f35d1030ba608d5f1c1dc7
[2022-11-08T19:40:04.565Z] Error: Command failed: docker start b27ab68ff9c0a9c5b1da4f796a30446c2953f15543f35d1030ba608d5f1c1dc7
[2022-11-08T19:40:04.565Z]     at loe (/Users/name@email.com/.vscode/extensions/ms-vscode-remote.remote-containers-0.262.3/dist/spec-node/devContainersSpecCLI.js:1887:1339)
[2022-11-08T19:40:04.565Z]     at eT (/Users/name@email.com/.vscode/extensions/ms-vscode-remote.remote-containers-0.262.3/dist/spec-node/devContainersSpecCLI.js:1887:1275)
[2022-11-08T19:40:04.565Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-11-08T19:40:04.566Z]     at async voe (/Users/name@email.com/.vscode/extensions/ms-vscode-remote.remote-containers-0.262.3/dist/spec-node/devContainersSpecCLI.js:1893:2049)
[2022-11-08T19:40:04.566Z]     at async Xf (/Users/name@email.com/.vscode/extensions/ms-vscode-remote.remote-containers-0.262.3/dist/spec-node/devContainersSpecCLI.js:1893:3212)
[2022-11-08T19:40:04.566Z]     at async Jae (/Users/name@email.com/.vscode/extensions/ms-vscode-remote.remote-containers-0.262.3/dist/spec-node/devContainersSpecCLI.js:2013:15058)
[2022-11-08T19:40:04.566Z]     at async Wae (/Users/name@email.com/.vscode/extensions/ms-vscode-remote.remote-containers-0.262.3/dist/spec-node/devContainersSpecCLI.js:2013:14812)
[2022-11-08T19:40:04.568Z] Stop (1044 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/name@email.com/.vscode/extensions/ms-vscode-remote.remote-containers-0.262.3/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/name@email.com/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/name@email.com/projects/experiment --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/name@email.com/projects/experiment --log-level debug --log-format json --config /Users/name@email.com/projects/experiment/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-11-08T19:40:04.568Z] Exit code 1
[2022-11-08T19:40:04.571Z] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/name@email.com/.vscode/extensions/ms-vscode-remote.remote-containers-0.262.3/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/name@email.com/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/name@email.com/projects/experiment --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/name@email.com/projects/experiment --log-level debug --log-format json --config /Users/name@email.com/projects/experiment/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-11-08T19:40:04.572Z] Exit code 1

```

- VSCode Version: 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f)
- Local OS Version: MacOS 13.0 (22A380)
- Remote OS Version: mcr.microsoft.com/devcontainers/python:3.10-bullseye
- Remote Extension/Connection Type: Containers

Steps to Reproduce:

1. Command Pallette > "Dev Containers: Add Dev Container configuration files" > Select any image
2. "Reopen in container"
3. Above error

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

Some of the containers in this list don't have Arm64 images, and I understand why those don't work. But for the ones that do, I can do a `docker pull` and `docker run` on them just fine. But when I try to use them as my base image for a new devcontainer I get the above error. Specifically I use `mcr.microsoft.com/devcontainers/python:3.10-bullseye` and it works when I use the docker CLI locally but fails when I use VSCode remote-containers extension to connect to it.

This used to work on my Mac, but has recently stopped working with the addition of "features" section that now appears in the devcontainer.json settings file. The default Python devcontainer (and many more) used to work just fine on the M1 Mac right out of the box.

**Comment by tclasen** [comment]
Note that when I say the addition of the "features" section I actually meant when it was changed to a new format.

An example of the "old-style" features from a repo that works on my box:
```json
  "features": {
    "docker-in-docker": "latest"
  }
```

And an example of the "new-style" features from a the above:
```json
"features": {
  "ghcr.io/devcontainers/features/node:1": {
    "version": "lts"
  }
}
```

It is only an assumption on my part that these are even different "versions" of the feature configuration section. And it is also an assumption that when it changed is around the time when new devcontainers stopped working for me.

**Comment by tclasen** [comment]
The devcontainer in this repo can still be used as-is: https://github.com/obscuritylabs/dramatiq-mongodb

**Comment by chrmarti** [comment]
The devcontainer.json in the description works on my M1 Mac. Maybe the existing container has an issue, can you try rebuilding that? (`F1` > `Dev Containers: Rebuild and Reopen in Container`)
