### ISSUE TITLE
SSH cannot connect when opening certain folders on remote system

### ISSUE THREAD

**Issue by n0doubt** [microsoft/vscode-remote-release#7491]
IF I connect to remote and open certain folders i.e. my project folder, I get a "Could not Establish Connection to "IP ADDRESS": Connecting with SSH timed out" message This is not a timeout-related issue (happens at a timeout value of 300) and I can connect to the remote normally if I open any other or no folders.

If I rename the folder, I can open it normally. Persists across deletion of .vscode and .vscode-server on local and remote machines, as well as a reinstallation and cache clear of VsCode on the local machine (settings sync disabled). Happens with no extensions enabled and with the insider version. 

Also happens with the 'disable local server' option disabled. 

- VSCode Version: 1.73.0 (user setup)
- Local OS Version: Windows 10.0.19044
- Remote OS Version: Debian GNU/Linux 11 (bullseye)
- Remote Extension/Connection Type: SSH
- Logs: 
```
[10:05:14.524] Log Level: 1
[10:05:14.525] remote-ssh@0.90.1
[10:05:14.525] win32 x64
[10:05:14.537] SSH Resolver called for "ssh-remote+<IP_CENSORED>", attempt 1
[10:05:14.537] "remote.SSH.useLocalServer": false
[10:05:14.538] "remote.SSH.showLoginTerminal": false
[10:05:14.538] "remote.SSH.remotePlatform": {"<IP_CENSORED>":"linux"}
[10:05:14.538] "remote.SSH.path": undefined
[10:05:14.538] "remote.SSH.configFile": undefined
[10:05:14.538] "remote.SSH.useFlock": true
[10:05:14.538] "remote.SSH.lockfilesInTmp": false
[10:05:14.538] "remote.SSH.localServerDownload": auto
[10:05:14.538] "remote.SSH.remoteServerListenOnSocket": false
[10:05:14.539] "remote.SSH.showLoginTerminal": false
[10:05:14.539] "remote.SSH.defaultExtensions": []
[10:05:14.539] "remote.SSH.loglevel": 1
[10:05:14.539] "remote.SSH.enableDynamicForwarding": true
[10:05:14.539] "remote.SSH.enableRemoteCommand": false
[10:05:14.539] "remote.SSH.serverPickPortsFromRange": {}
[10:05:14.539] "remote.SSH.serverInstallPath": {}
[10:05:14.543] SSH Resolver called for host: <IP_CENSORED>
[10:05:14.543] Setting up SSH remote "<IP_CENSORED>"
[10:05:14.548] Using commit id "8fa188b2b301d36553cbc9ce1b0a146ccb93351f" and quality "stable" for server
[10:05:14.551] Install and start server if needed
[10:05:14.553] Checking ssh with "ssh -V"
[10:05:14.584] > OpenSSH_for_Windows_8.1p1, 
[10:05:14.584] > LibreSSL 3.0.2

[10:05:14.589] Running script with connection command: ssh -T -D 5503 "<IP_CENSORED>" bash
[10:05:14.591] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:05:31.599] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (c:\Users\USERNAME\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:585348)
	at Timeout._onTimeout (c:\Users\USERNAME\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:679743)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[10:05:31.603] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Timeout","exitCodeLabel":""},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":17062,"timing.preSshTime":54,"timing.scriptTime":17007}}
[10:05:31.603] ------




[10:05:31.679] ------




[10:05:31.680] SSH Resolver called for "ssh-remote+<IP_CENSORED>", attempt 2, (Reconnection)
[10:05:31.681] SSH Resolver called for host: <IP_CENSORED>
[10:05:31.681] Setting up SSH remote "<IP_CENSORED>"
[10:05:31.684] Using commit id "8fa188b2b301d36553cbc9ce1b0a146ccb93351f" and quality "stable" for server
[10:05:31.687] Install and start server if needed
[10:05:31.690] Running script with connection command: ssh -T -D 5513 "<IP_CENSORED>" bash
[10:05:31.697] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:05:48.701] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (c:\Users\USERNAME\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:585348)
	at Timeout._onTimeout (c:\Users\USERNAME\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:679743)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[10:05:48.702] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Timeout","exitCodeLabel":""},"measures":{"resolveAttempts":2,"retries":1,"timing.totalResolveTime":17021,"timing.preSshTime":18,"timing.scriptTime":17003}}
[10:05:48.702] ------




[10:05:48.726] ------




[10:05:48.726] SSH Resolver called for "ssh-remote+<IP_CENSORED>", attempt 3, (Reconnection)
[10:05:48.727] SSH Resolver called for host: <IP_CENSORED>
[10:05:48.727] Setting up SSH remote "<IP_CENSORED>"
[10:05:48.729] Using commit id "8fa188b2b301d36553cbc9ce1b0a146ccb93351f" and quality "stable" for server
[10:05:48.731] Install and start server if needed
[10:05:48.735] Running script with connection command: ssh -T -D 5523 "<IP_CENSORED>" bash
[10:05:48.736] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:06:05.741] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (c:\Users\USERNAME\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:585348)
	at Timeout._onTimeout (c:\Users\USERNAME\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:679743)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[10:06:05.742] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Timeout","exitCodeLabel":""},"measures":{"resolveAttempts":3,"retries":1,"timing.totalResolveTime":17015,"timing.preSshTime":10,"timing.scriptTime":17005}}
[10:06:05.742] ------




[10:06:05.779] ------




[10:06:05.779] SSH Resolver called for "ssh-remote+<IP_CENSORED>", attempt 4, (Reconnection)
[10:06:05.780] SSH Resolver called for host: <IP_CENSORED>
[10:06:05.781] Setting up SSH remote "<IP_CENSORED>"
[10:06:05.783] Using commit id "8fa188b2b301d36553cbc9ce1b0a146ccb93351f" and quality "stable" for server
[10:06:05.785] Install and start server if needed
[10:06:05.789] Running script with connection command: ssh -T -D 5534 "<IP_CENSORED>" bash
[10:06:05.791] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:06:22.795] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (c:\Users\USERNAME\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:585348)
	at Timeout._onTimeout (c:\Users\USERNAME\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:679743)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[10:06:22.796] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Timeout","exitCodeLabel":""},"measures":{"resolveAttempts":4,"retries":1,"timing.totalResolveTime":17016,"timing.preSshTime":12,"timing.scriptTime":17004}}
[10:06:22.797] ------




[10:06:22.822] ------




[10:06:22.822] SSH Resolver called for "ssh-remote+<IP_CENSORED>", attempt 5, (Reconnection)
[10:06:22.824] SSH Resolver called for host: <IP_CENSORED>
[10:06:22.824] Setting up SSH remote "<IP_CENSORED>"
[10:06:22.826] Using commit id "8fa188b2b301d36553cbc9ce1b0a146ccb93351f" and quality "stable" for server
[10:06:22.828] Install and start server if needed
[10:06:22.830] Running script with connection command: ssh -T -D 5543 "<IP_CENSORED>" bash
[10:06:22.831] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:06:39.840] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (c:\Users\USERNAME\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:585348)
	at Timeout._onTimeout (c:\Users\USERNAME\.vscode\extensions\ms-vscode-remote.remote-ssh-0.90.1\out\extension.js:1:679743)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[10:06:39.841] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Timeout","exitCodeLabel":""},"measures":{"resolveAttempts":5,"retries":1,"timing.totalResolveTime":17018,"timing.preSshTime":9,"timing.scriptTime":17009}}
[10:06:39.841] ------




[10:06:41.078] "install" terminal received data: "[2J[m[H]0;C:\WINDOWS\System32\cmd.exe[?25h"
[10:06:41.079] Got some output, clearing connection timeout
[10:06:41.481] "install" terminal received data: "[2J[m[H]0;C:\WINDOWS\System32\cmd.exe[?25h"
[10:06:41.482] Got some output, clearing connection timeout
[10:06:41.678] "install" terminal received data: "c21fd79f4b97: running"
[10:06:41.686] "install" terminal received data: "[2J[m[H]0;C:\WINDOWS\System32\cmd.exe[?25h"
[10:06:41.686] Got some output, clearing connection timeout
[10:06:41.689] "install" terminal received data: "Acquiring lock on /home/admin/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146
ccb93351f/vscode-remote-lock.admin.8fa188b2b301d36553cbc9ce1b0a146ccb93351f     
Found existing installation at /home/admin/.vscode-server/bin/8fa188b2b301d36553
cbc9ce1b0a146ccb93351f...[K
Checking /home/admin/.vscode-server/.8fa188b2b301d36553cbc9ce1b0a146ccb93351f.lo
g and /home/admin/.vscode-server/.8fa188b2b301d36553cbc9ce1b0a146ccb93351f.pid f
or a running server[K
Looking for server with pid: 1577[K"
[10:06:41.714] "install" terminal received data: "Found running server...[K
[K
*[K
* Reminder: You may only use this software with Visual Studio family products, 
* as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
*[K
[K
Checking server status on port 34827 with wget
c21fd79f4b97: start[27X
SSH_AUTH_SOCK====[29X
DISPLAY====[35X
webUiAccessToken====[26X
listeningOn==34827==[26X
osReleaseId==debian==[25X
arch==x86_64==[32X
tmpDir==/run/user/1000==[22X
platform==linux==[29X
unpackResult====[30X
didLocalDownload==0==[25X
downloadTime====[30X
installTime====[31X
extInstallTime====
serverStartTime===="
[10:06:41.730] "install" terminal received data: "
connectionToken==a11111aa-1a11-1a11-a11a-1a1111111a11==
c21fd79f4b97: end"
[10:06:41.745] "install" terminal received data: ""
[10:06:41.874] "install" terminal received data: "8a958791f89c: running"
[10:06:41.895] "install" terminal received data: "Acquiring lock on /home/admin/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146
ccb93351f/vscode-remote-lock.admin.8fa188b2b301d36553cbc9ce1b0a146ccb93351f     "
[10:06:41.913] "install" terminal received data: "[2J[m[H]0;C:\WINDOWS\System32\cmd.exe[?25h"
[10:06:41.913] "install" terminal received data: "Found existing installation at /home/admin/.vscode-server/bin/8fa188b2b301d36553
cbc9ce1b0a146ccb93351f...[K"
[10:06:41.914] Got some output, clearing connection timeout
[10:06:41.972] "install" terminal received data: "Checking /home/admin/.vscode-server/.8fa188b2b301d36553cbc9ce1b0a146ccb93351f.lo
g and /home/admin/.vscode-server/.8fa188b2b301d36553cbc9ce1b0a146ccb93351f.pid f
or a running server[K
Looking for server with pid: 1577[K
Found running server...[K
[K
*[K
* Reminder: You may only use this software with Visual Studio family products, 
* as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
*[K
[K
Checking server status on port 34827 with wget[K
8a958791f89c: start[K
SSH_AUTH_SOCK====[K
DISPLAY====[K
webUiAccessToken====[K
listeningOn==34827==[K
osReleaseId==debian==[K
arch==x86_64==[K
tmpDir==/run/user/1000==[K
platform==linux==[K
unpackResult====[K
didLocalDownload==0==[K
downloadTime====[K
installTime====[K
extInstallTime====
serverStartTime====
connectionToken==a11111aa-1a11-1a11-a11a-1a1111111a11==
8a958791f89c: end"
[10:06:41.987] "install" terminal received data: ""
[10:06:42.192] "install" terminal received data: "[2J[m[H]0;C:\WINDOWS\System32\cmd.exe[?25h"
[10:06:42.192] Got some output, clearing connection timeout
[10:06:42.224] "install" terminal received data: "1b71d8de6f05: running"
[10:06:42.251] "install" terminal received data: "Acquiring lock on /home/admin/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146
ccb93351f/vscode-remote-lock.admin.8fa188b2b301d36553cbc9ce1b0a146ccb93351f     "
[10:06:42.270] "install" terminal received data: "Found existing installation at /home/admin/.vscode-server/bin/8fa188b2b301d36553
cbc9ce1b0a146ccb93351f...[K
Checking /home/admin/.vscode-server/.8fa188b2b301d36553cbc9ce1b0a146ccb93351f.lo
g and /home/admin/.vscode-server/.8fa188b2b301d36553cbc9ce1b0a146ccb93351f.pid f
or a running server[K
Looking for server with pid: 1577[K"
[10:06:42.294] "install" terminal received data: "Found running server..."
[10:06:42.309] "install" terminal received data: "[K
*[K
* Reminder: You may only use this software with Visual Studio family products, 
* as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
*[K
[K
Checking server status on port 34827 with wget[K
1b71d8de6f05: start[K
SSH_AUTH_SOCK====[K
DISPLAY====[K
webUiAccessToken====[K
listeningOn==34827==[K
osReleaseId==debian==[K
arch==x86_64==[K
tmpDir==/run/user/1000==[K
platform==linux==[K
unpackResult====[K
didLocalDownload==0==[K
downloadTime====[K
installTime====[K
extInstallTime====
serverStartTime====
connectionToken==a11111aa-1a11-1a11-a11a-1a1111111a11==
1b71d8de6f05: end"
[10:06:42.335] "install" terminal received data: ""
[10:06:42.413] "install" terminal received data: "48735167bc7a: running"
[10:06:42.440] "install" terminal received data: "Acquiring lock on /home/admin/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146
ccb93351f/vscode-remote-lock.admin.8fa188b2b301d36553cbc9ce1b0a146ccb93351f     "
[10:06:42.456] "install" terminal received data: "Found existing installation at /home/admin/.vscode-server/bin/8fa188b2b301d36553
cbc9ce1b0a146ccb93351f...[K
Checking /home/admin/.vscode-server/.8fa188b2b301d36553cbc9ce1b0a146ccb93351f.lo
g and /home/admin/.vscode-server/.8fa188b2b301d36553cbc9ce1b0a146ccb93351f.pid f
or a running server[K
Looking for server with pid: 1577[K"
[10:06:42.467] "install" terminal received data: "Found running server...[K
[K
*[K
* Reminder: You may only use this software with Visual Studio family products, 
* as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
*[K
[K"
[10:06:42.484] "install" terminal received data: "Checking server status on port 34827 with wget
48735167bc7a: start[27X
SSH_AUTH_SOCK====[29X
DISPLAY====[35X
webUiAccessToken====[26X
listeningOn==34827==[26X
osReleaseId==debian==[25X
arch==x86_64==[32X
tmpDir==/run/user/1000==[22X
platform==linux==[29X
unpackResult====[30X
didLocalDownload==0==[25X
downloadTime====[30X
installTime====[31X
extInstallTime====
serverStartTime===="
[10:06:42.544] "install" terminal received data: "connectionToken==a11111aa-1a11-1a11-a11a-1a1111111a11==
48735167bc7a: end"
[10:06:42.706] "install" terminal received data: "fe2766ab5e35: running"
[10:06:42.731] "install" terminal received data: "Acquiring lock on /home/admin/.vscode-server/bin/8fa188b2b301d36553cbc9ce1b0a146
ccb93351f/vscode-remote-lock.admin.8fa188b2b301d36553cbc9ce1b0a146ccb93351f     
Found existing installation at /home/admin/.vscode-server/bin/8fa188b2b301d36553
cbc9ce1b0a146ccb93351f...[K"
[10:06:42.747] "install" terminal received data: "Checking /home/admin/.vscode-server/.8fa188b2b301d36553cbc9ce1b0a146ccb93351f.lo
g and /home/admin/.vscode-server/.8fa188b2b301d36553cbc9ce1b0a146ccb93351f.pid f
or a running server[K
Looking for server with pid: 1577[K
Found running server...[K
[K
*[K
* Reminder: You may only use this software with Visual Studio family products,  "
[10:06:42.763] "install" terminal received data: "* as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
*[K
[K
Checking server status on port 34827 with wget[K
fe2766ab5e35: start     
SSH_AUTH_SOCK====       
DISPLAY====[13X
webUiAccessToken====    
listeningOn==34827==    
osReleaseId==debian==   
arch==x86_64==[10X
tmpDir==/run/user/1000==
platform==linux==       
unpackResult====        
didLocalDownload==0==   
downloadTime====        
installTime====[9X
extInstallTime====
serverStartTime====
connectionToken==a11111aa-1a11-1a11-a11a-1a1111111a11==
fe2766ab5e35: end"
[10:06:42.850] "install" terminal received data: ""
```

Steps to Reproduce:

1. Work on a project for awhile 
2. Need to reload the window/close VsCode to enjoy my evening
3. Reopen Vscode 
4. "Could not establish connection to "IP ADDRESS": Connecting with ssh timed out"
5. I can close the remote window, and open another one and connect to the remote without opening a folder
6. Rename the remote folder in question and I can open it again, I can never set that folder to the broken name again or else I cannot open the folder.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by n0doubt** [comment]
Only similar issue I could find and I tried this with no success: https://github.com/microsoft/vscode-remote-release/issues/7281#issuecomment-1267229776

**Comment by ervwalter** [comment]
I'm seeing the same thing for what it's worth.

**Comment by ervwalter** [comment]
Also as a data point, I deleted the `C:\Users\USERNAME\AppData\Roaming\Code` folder and that made things start working again.  So whatever the issue is, it lies with some file somewhere in that large folder tree.  Note, deleting that folder causes VS Code to act like it was freshly installed.  This was not too painful for me because I use Setting Sync and I quickly got back to my normal VS Code configuration after launching it again and letting the "fresh" vscode pull down my existing settings/extensions/etc.  The only thing I really lost was my "Recent Folders/Files" list.

**Comment by n0doubt** [comment]
I can confirm that deleting AppData\Roaming\Code fixes the behavior

**Comment by dgc** [comment]
I can also confirm that deleting `%APPDATA%\Code` worked around this issue.

Just to add that you can set up "Settings Sync" first if you haven't done already (as I just did).

**Comment by jabbera** [comment]
You can just delete this folder without your whole setting:

https://stackoverflow.com/a/74356273/556475

**Comment by n0doubt** [comment]
This is apparently related to https://github.com/microsoft/vscode-remote-release/issues/7324 and a fix should arrive soon or is already here

Thank you @jabbera for the Stackoverflow link which pointed me to the issue
