### ISSUE TITLE
Don't timeout during SSH-agent comunication

### ISSUE THREAD

**Issue by Maetveis** [microsoft/vscode-remote-release#7504]
When connecting to ssh and using an ssh agent, the connection can time out while waiting for the user to enter the password.
It is reasonable that the timeout on a failed connection would be a few seconds, but for entering a complex password that might be too short. 
Therefore I'd like if there would be no timeout, or a much larger timeout for the agent to return a key.

**Comment by eleanorjboyd** [comment]
Hi! What type of authentication are you using? Could you send the remote-ssh logs?

**Comment by Maetveis** [comment]
> Hi! What type of authentication are you using?

I'm using GPG agent with ssh-agent support (i.e. `--enable-ssh-support`), the used ssh key is part of my GPG key.

> Could you send the remote-ssh logs?

<details>

<summary>Remote ssh logs</summary>

```plaintext
[09:36:20.524] Log Level: 2
[09:36:20.525] remote-ssh@0.92.0
[09:36:20.525] linux x64
[09:36:20.542] SSH Resolver called for "ssh-remote+amd-devcloud-ixt-sjc2-124", attempt 1
[09:36:20.542] "remote.SSH.useLocalServer": true
[09:36:20.542] "remote.SSH.path": undefined
[09:36:20.542] "remote.SSH.configFile": undefined
[09:36:20.542] "remote.SSH.useFlock": true
[09:36:20.542] "remote.SSH.lockfilesInTmp": false
[09:36:20.542] "remote.SSH.localServerDownload": auto
[09:36:20.542] "remote.SSH.remoteServerListenOnSocket": false
[09:36:20.542] "remote.SSH.showLoginTerminal": false
[09:36:20.543] "remote.SSH.defaultExtensions": []
[09:36:20.543] "remote.SSH.loglevel": 2
[09:36:20.543] "remote.SSH.enableDynamicForwarding": true
[09:36:20.543] "remote.SSH.enableRemoteCommand": false
[09:36:20.543] "remote.SSH.serverPickPortsFromRange": {}
[09:36:20.543] "remote.SSH.serverInstallPath": {}
[09:36:20.545] SSH Resolver called for host: amd-devcloud-ixt-sjc2-124
[09:36:20.545] Setting up SSH remote "amd-devcloud-ixt-sjc2-124"
[09:36:20.547] Acquiring local install lock: /tmp/vscode-remote-ssh-333fe349-install.lock
[09:36:20.548] Looking for existing server data file at /home/gergely/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-333fe349-8fa188b2b301d36553cbc9ce1b0a146ccb93351f-0.92.0/data.json
[09:36:20.548] Using commit id "8fa188b2b301d36553cbc9ce1b0a146ccb93351f" and quality "stable" for server
[09:36:20.550] Install and start server if needed
[09:36:20.551] PATH: /usr/local/bin:/usr/bin
[09:36:20.551] Checking ssh with "ssh -V"
[09:36:20.556] > OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022

[09:36:20.558] askpass server listening on /run/user/1000/vscode-ssh-askpass-a1cc583bf2eb32fbdea19ae7b79d1fef59d9a482.sock
[09:36:20.559] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-864f38242cd5df8066b3fd3eae8162ace253aba3.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","38967","-o","ConnectTimeout=15","amd-devcloud-ixt-sjc2-124"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/gergely/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-333fe349-8fa188b2b301d36553cbc9ce1b0a146ccb93351f-0.92.0/data.json"}
[09:36:20.559] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/gnupg/S.gpg-agent.ssh","SHELL":"/bin/zsh","DISPLAY":":1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/opt/visual-studio-code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-a1cc583bf2eb32fbdea19ae7b79d1fef59d9a482.sock"}
[09:36:20.561] Spawned 14332
[09:36:20.634] > local-server-1> Spawned ssh, pid=14341
[09:36:20.635] stderr> OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022
[09:36:20.638] stderr> OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022
[09:36:21.697] stderr> debug1: Server host key: ssh-ed25519 SHA256:NFaRrz+xfeLb3xeIR+OaIJJ9/zPG1i1UcIYNGL+HBqI
[09:36:35.649] stderr> Connection timed out during banner exchange
[09:36:35.650] stderr> Connection to UNKNOWN port 65535 timed out
[09:36:35.650] > local-server-1> ssh child died, shutting down
[09:36:35.653] Local server exit: 0
[09:36:35.654] Received install output: local-server-1> Spawned ssh, pid=14341
OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022
OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022
debug1: Server host key: ssh-ed25519 SHA256:NFaRrz+xfeLb3xeIR+OaIJJ9/zPG1i1UcIYNGL+HBqI
Connection timed out during banner exchange
Connection to UNKNOWN port 65535 timed out
local-server-1> ssh child died, shutting down

[09:36:35.657] Resolver error: Error: The connection timed out
	at g.Offline (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:583872)
	at /home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:581447
	at t.handleInstallOutput (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:581661)
	at Object.e [as tryInstallWithLocalServer] (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:623084)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:642212
	at async t.withShowDetailsEvent (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:645932)
	at async /home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:621556
	at async T (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:618062)
	at async t.resolveWithLocalServer (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:621171)
	at async t.resolve (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:643540)
	at async /home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:722342
[09:36:35.661] ------




[09:36:35.673] ------




[09:36:35.673] SSH Resolver called for "ssh-remote+amd-devcloud-ixt-sjc2-124", attempt 2, (Reconnection)
[09:36:35.677] SSH Resolver called for host: amd-devcloud-ixt-sjc2-124
[09:36:35.677] Setting up SSH remote "amd-devcloud-ixt-sjc2-124"
[09:36:35.678] Acquiring local install lock: /tmp/vscode-remote-ssh-333fe349-install.lock
[09:36:35.678] Looking for existing server data file at /home/gergely/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-333fe349-8fa188b2b301d36553cbc9ce1b0a146ccb93351f-0.92.0/data.json
[09:36:35.679] Using commit id "8fa188b2b301d36553cbc9ce1b0a146ccb93351f" and quality "stable" for server
[09:36:35.683] Install and start server if needed
[09:36:35.688] askpass server listening on /run/user/1000/vscode-ssh-askpass-fb81880f013182c5552ac5a222c8a2aa84e58dee.sock
[09:36:35.688] Spawning local server with {"serverId":2,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-e57d7e46e44fc53137bc62eb59a7863031dd117e.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","45799","-o","ConnectTimeout=15","amd-devcloud-ixt-sjc2-124"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/gergely/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-333fe349-8fa188b2b301d36553cbc9ce1b0a146ccb93351f-0.92.0/data.json"}
[09:36:35.689] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/gnupg/S.gpg-agent.ssh","SHELL":"/bin/zsh","DISPLAY":":1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/opt/visual-studio-code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-fb81880f013182c5552ac5a222c8a2aa84e58dee.sock"}
[09:36:35.692] Spawned 14435
[09:36:35.762] > local-server-2> Spawned ssh, pid=14443
[09:36:35.763] stderr> OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022
[09:36:35.768] stderr> OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022
[09:36:38.183] stderr> debug1: Server host key: ssh-ed25519 SHA256:NFaRrz+xfeLb3xeIR+OaIJJ9/zPG1i1UcIYNGL+HBqI
[09:36:50.776] stderr> Connection timed out during banner exchange
[09:36:50.777] stderr> Connection to UNKNOWN port 65535 timed out
[09:36:50.777] > local-server-2> ssh child died, shutting down
[09:36:50.780] Local server exit: 0
[09:36:50.781] Received install output: local-server-2> Spawned ssh, pid=14443
OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022
OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022
debug1: Server host key: ssh-ed25519 SHA256:NFaRrz+xfeLb3xeIR+OaIJJ9/zPG1i1UcIYNGL+HBqI
Connection timed out during banner exchange
Connection to UNKNOWN port 65535 timed out
local-server-2> ssh child died, shutting down

[09:36:50.781] Resolver error: Error: The connection timed out
	at g.Offline (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:583872)
	at /home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:581447
	at t.handleInstallOutput (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:581661)
	at Object.e [as tryInstallWithLocalServer] (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:623084)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:642212
	at async t.withShowDetailsEvent (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:645932)
	at async /home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:621556
	at async T (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:618062)
	at async t.resolveWithLocalServer (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:621171)
	at async t.resolve (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:643540)
	at async /home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:722342
[09:36:50.782] ------




[09:36:50.816] ------




[09:36:50.817] SSH Resolver called for "ssh-remote+amd-devcloud-ixt-sjc2-124", attempt 3, (Reconnection)
[09:36:50.818] SSH Resolver called for host: amd-devcloud-ixt-sjc2-124
[09:36:50.818] Setting up SSH remote "amd-devcloud-ixt-sjc2-124"
[09:36:50.819] Acquiring local install lock: /tmp/vscode-remote-ssh-333fe349-install.lock
[09:36:50.819] Looking for existing server data file at /home/gergely/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-333fe349-8fa188b2b301d36553cbc9ce1b0a146ccb93351f-0.92.0/data.json
[09:36:50.819] Using commit id "8fa188b2b301d36553cbc9ce1b0a146ccb93351f" and quality "stable" for server
[09:36:50.820] Install and start server if needed
[09:36:50.823] askpass server listening on /run/user/1000/vscode-ssh-askpass-253a04e3b2e974db19f5f62fc83e107cc762a242.sock
[09:36:50.823] Spawning local server with {"serverId":3,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-939f7db29ab91c588dd061011e348cf20e1bf5c8.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","45869","-o","ConnectTimeout=15","amd-devcloud-ixt-sjc2-124"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/gergely/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-333fe349-8fa188b2b301d36553cbc9ce1b0a146ccb93351f-0.92.0/data.json"}
[09:36:50.823] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/gnupg/S.gpg-agent.ssh","SHELL":"/bin/zsh","DISPLAY":":1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/opt/visual-studio-code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-253a04e3b2e974db19f5f62fc83e107cc762a242.sock"}
[09:36:50.825] Spawned 14535
[09:36:50.897] > local-server-3> Spawned ssh, pid=14544
[09:36:50.899] stderr> OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022
[09:36:50.901] stderr> OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022
[09:36:51.746] stderr> debug1: Server host key: ssh-ed25519 SHA256:NFaRrz+xfeLb3xeIR+OaIJJ9/zPG1i1UcIYNGL+HBqI
[09:37:05.901] stderr> Connection timed out during banner exchange
[09:37:05.901] stderr> Connection to UNKNOWN port 65535 timed out
[09:37:05.902] > local-server-3> ssh child died, shutting down
[09:37:05.907] Local server exit: 0
[09:37:05.908] Received install output: local-server-3> Spawned ssh, pid=14544
OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022
OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022
debug1: Server host key: ssh-ed25519 SHA256:NFaRrz+xfeLb3xeIR+OaIJJ9/zPG1i1UcIYNGL+HBqI
Connection timed out during banner exchange
Connection to UNKNOWN port 65535 timed out
local-server-3> ssh child died, shutting down

[09:37:05.909] Resolver error: Error: The connection timed out
	at g.Offline (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:583872)
	at /home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:581447
	at t.handleInstallOutput (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:581661)
	at Object.e [as tryInstallWithLocalServer] (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:623084)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:642212
	at async t.withShowDetailsEvent (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:645932)
	at async /home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:621556
	at async T (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:618062)
	at async t.resolveWithLocalServer (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:621171)
	at async t.resolve (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:643540)
	at async /home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:722342
[09:37:05.910] ------




[09:37:05.961] ------




[09:37:05.961] SSH Resolver called for "ssh-remote+amd-devcloud-ixt-sjc2-124", attempt 4, (Reconnection)
[09:37:05.963] SSH Resolver called for host: amd-devcloud-ixt-sjc2-124
[09:37:05.963] Setting up SSH remote "amd-devcloud-ixt-sjc2-124"
[09:37:05.964] Acquiring local install lock: /tmp/vscode-remote-ssh-333fe349-install.lock
[09:37:05.965] Looking for existing server data file at /home/gergely/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-333fe349-8fa188b2b301d36553cbc9ce1b0a146ccb93351f-0.92.0/data.json
[09:37:05.966] Using commit id "8fa188b2b301d36553cbc9ce1b0a146ccb93351f" and quality "stable" for server
[09:37:05.969] Install and start server if needed
[09:37:05.972] askpass server listening on /run/user/1000/vscode-ssh-askpass-c742a83cba22e1314deab6766147789e1b3f1bb6.sock
[09:37:05.972] Spawning local server with {"serverId":4,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-44cc81aaee8d903237b6c921e195542ad60b9de1.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","33043","-o","ConnectTimeout=15","amd-devcloud-ixt-sjc2-124"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/gergely/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-333fe349-8fa188b2b301d36553cbc9ce1b0a146ccb93351f-0.92.0/data.json"}
[09:37:05.972] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/gnupg/S.gpg-agent.ssh","SHELL":"/bin/zsh","DISPLAY":":1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/opt/visual-studio-code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-c742a83cba22e1314deab6766147789e1b3f1bb6.sock"}
[09:37:05.975] Spawned 14626
[09:37:06.051] > local-server-4> Spawned ssh, pid=14634
[09:37:06.052] stderr> OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022
[09:37:06.057] stderr> OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022
[09:37:06.957] stderr> debug1: Server host key: ssh-ed25519 SHA256:NFaRrz+xfeLb3xeIR+OaIJJ9/zPG1i1UcIYNGL+HBqI
[09:37:21.068] stderr> Connection timed out during banner exchange
[09:37:21.068] stderr> Connection to UNKNOWN port 65535 timed out
[09:37:21.069] > local-server-4> ssh child died, shutting down
[09:37:21.073] Local server exit: 0
[09:37:21.074] Received install output: local-server-4> Spawned ssh, pid=14634
OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022
OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022
debug1: Server host key: ssh-ed25519 SHA256:NFaRrz+xfeLb3xeIR+OaIJJ9/zPG1i1UcIYNGL+HBqI
Connection timed out during banner exchange
Connection to UNKNOWN port 65535 timed out
local-server-4> ssh child died, shutting down

[09:37:21.074] Resolver error: Error: The connection timed out
	at g.Offline (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:583872)
	at /home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:581447
	at t.handleInstallOutput (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:581661)
	at Object.e [as tryInstallWithLocalServer] (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:623084)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:642212
	at async t.withShowDetailsEvent (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:645932)
	at async /home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:621556
	at async T (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:618062)
	at async t.resolveWithLocalServer (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:621171)
	at async t.resolve (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:643540)
	at async /home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:722342
[09:37:21.076] ------




[09:37:21.080] ------




[09:37:21.080] SSH Resolver called for "ssh-remote+amd-devcloud-ixt-sjc2-124", attempt 5, (Reconnection)
[09:37:21.081] SSH Resolver called for host: amd-devcloud-ixt-sjc2-124
[09:37:21.081] Setting up SSH remote "amd-devcloud-ixt-sjc2-124"
[09:37:21.082] Acquiring local install lock: /tmp/vscode-remote-ssh-333fe349-install.lock
[09:37:21.082] Looking for existing server data file at /home/gergely/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-333fe349-8fa188b2b301d36553cbc9ce1b0a146ccb93351f-0.92.0/data.json
[09:37:21.083] Using commit id "8fa188b2b301d36553cbc9ce1b0a146ccb93351f" and quality "stable" for server
[09:37:21.085] Install and start server if needed
[09:37:21.089] askpass server listening on /run/user/1000/vscode-ssh-askpass-d9ffdec7cc17693e51f03d575f010661684edd0d.sock
[09:37:21.089] Spawning local server with {"serverId":5,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-171934e6fc20aebe9a48db5fd988651250c860e7.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","44591","-o","ConnectTimeout=15","amd-devcloud-ixt-sjc2-124"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/gergely/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-333fe349-8fa188b2b301d36553cbc9ce1b0a146ccb93351f-0.92.0/data.json"}
[09:37:21.089] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/gnupg/S.gpg-agent.ssh","SHELL":"/bin/zsh","DISPLAY":":1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/opt/visual-studio-code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-d9ffdec7cc17693e51f03d575f010661684edd0d.sock"}
[09:37:21.092] Spawned 14693
[09:37:21.163] > local-server-5> Spawned ssh, pid=14701
[09:37:21.164] stderr> OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022
[09:37:21.167] stderr> OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022
[09:37:22.022] stderr> debug1: Server host key: ssh-ed25519 SHA256:NFaRrz+xfeLb3xeIR+OaIJJ9/zPG1i1UcIYNGL+HBqI
[09:37:36.176] stderr> Connection timed out during banner exchange
[09:37:36.176] stderr> Connection to UNKNOWN port 65535 timed out
[09:37:36.177] > local-server-5> ssh child died, shutting down
[09:37:36.182] Local server exit: 0
[09:37:36.182] Received install output: local-server-5> Spawned ssh, pid=14701
OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022
OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022
debug1: Server host key: ssh-ed25519 SHA256:NFaRrz+xfeLb3xeIR+OaIJJ9/zPG1i1UcIYNGL+HBqI
Connection timed out during banner exchange
Connection to UNKNOWN port 65535 timed out
local-server-5> ssh child died, shutting down

[09:37:36.183] Resolver error: Error: The connection timed out
	at g.Offline (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:583872)
	at /home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:581447
	at t.handleInstallOutput (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:581661)
	at Object.e [as tryInstallWithLocalServer] (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:623084)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:642212
	at async t.withShowDetailsEvent (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:645932)
	at async /home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:621556
	at async T (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:618062)
	at async t.resolveWithLocalServer (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:621171)
	at async t.resolve (/home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:643540)
	at async /home/gergely/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:722342
[09:37:36.185] ------
```

</details>

I don't think its relevant (I can reproduce this with all ssh targets not just this one), but here's my `~/.ssh/config` section for this host. (With details omitted)

```plaintext
Host amd-devcloud-ixt-sjc2-124
  HostName <hostname>
  User <user>
  RemoteForward /run/user/1006/gnupg/S.gpg-agent /run/user/1000/gnupg/S.gpg-agent.extra
  ProxyJump <proxy-hostname>
  ForwardAgent yes
```

**Comment by eleanorjboyd** [comment]
Hello! It seems you are receiving an error regarding "The Connection timed out during banner exchange". This error message might indicate issues with your network or some firewall rules. Are you able to connect if you run this command which we are attempting from a local terminal? `ssh -v -T -D 38967 -o ConnectTimeout=15 amd-devcloud-ixt-sjc2-124`

**Comment by Maetveis** [comment]
> Are you able to connect if you run this command which we are attempting from a local terminal? `ssh -v -T -D 38967 -o ConnectTimeout=15 amd-devcloud-ixt-sjc2-124`

I'm able to connect if I enter the password before the timeout, just as in vscode. However this command also times out during the password prompt after 15 seconds. I guess my request should be directed to OpenSSH in this case.

Is the 15 second in the supplied command configurable?

**Comment by eleanorjboyd** [comment]
Hi, yes if it is timing out if the command is in the command line then it is likely unrelated to VS Code. Yes, you can change the timeout, there is a user setting that is remoteSSH connection timeout. Thanks!
