### ISSUE TITLE
SSH timeout after successful login

### ISSUE THREAD

**Issue by citizenrich** [microsoft/vscode-remote-release#7520]
- VSCode Version:

Version: 1.74.0-insider (Universal)
Commit: 3fb8e8feb1c93a490feb2c2259713d4c8f0e0058
Date: 2022-11-14T10:15:28.815Z
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes

- Local OS Version: macOS Monterey, 12.6.1
- Remote OS Version: Debian GNU/Linux 11 (bullseye)
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Remote-SSH: Connect to Host for already configured host.
2. Attempt to connect.

Does this issue occur when you try this locally?: No. Remote SSH works with a local bare metal workstation running Ubuntu 22.04 and with a cloud instance in AWS running Ubuntu 22.04.
Does this issue occur when you try this locally and all extensions are disabled?: Yes

- Logs:
```
[14:26:20.896] Log Level: 2
[14:26:20.926] remote-ssh@0.93.2022111115
[14:26:20.927] darwin x64
[14:26:20.956] SSH Resolver called for "ssh-remote+host-hidden", attempt 1
[14:26:20.959] "remote.SSH.useLocalServer": true
[14:26:20.960] "remote.SSH.path": undefined
[14:26:20.960] "remote.SSH.configFile": undefined
[14:26:20.960] "remote.SSH.useFlock": true
[14:26:20.960] "remote.SSH.lockfilesInTmp": false
[14:26:20.960] "remote.SSH.localServerDownload": auto
[14:26:20.961] "remote.SSH.remoteServerListenOnSocket": false
[14:26:20.961] "remote.SSH.showLoginTerminal": false
[14:26:20.961] "remote.SSH.defaultExtensions": []
[14:26:20.961] "remote.SSH.loglevel": 2
[14:26:20.961] "remote.SSH.enableDynamicForwarding": true
[14:26:20.962] "remote.SSH.enableRemoteCommand": false
[14:26:20.962] "remote.SSH.serverPickPortsFromRange": {}
[14:26:20.962] "remote.SSH.serverInstallPath": {}
[14:26:20.995] SSH Resolver called for host:+host-hidden
[14:26:20.995] Setting up SSH remote +host-hidden"
[14:26:21.000] Acquiring local install lock: /var/folders/5g/qr2tyf4n7jbfcqbjh58mdwx00000gn/T/vscode-remote-ssh-9c0f0d8a-install.lock
[14:26:21.002] Looking for existing server data file at /Users/richard/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-9c0f0d8a-ef415578d1b1019db585718968a303eeca4b8979-0.93.2022111115/data.json
[14:26:21.002] Using commit id "ef415578d1b1019db585718968a303eeca4b8979" and quality "insider" for server
[14:26:21.010] Install and start server if needed
[14:26:21.014] PATH: /Library/Frameworks/iio.framework/Tools:/usr/local/opt/ruby/bin:/usr/local/sbin:/usr/local/opt/openssl/bin:/Users/richard/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/MacGPG2/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/usr/local/opt/go/libexec/bin:/Users/richard/.cargo/bin:/usr/local/opt/qt/bin:/Users/richard/.gem/ruby/3.0.0/bin
[14:26:21.014] Checking ssh with "ssh -V"
[14:26:21.039] > OpenSSH_8.6p1, LibreSSL 3.3.6

[14:26:21.044] askpass server listening on /var/folders/5g/qr2tyf4n7jbfcqbjh58mdwx00000gn/T/vscode-ssh-askpass-1ac992e13e716ee082fb90bf782e992c782e0d9f.sock
[14:26:21.045] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/5g/qr2tyf4n7jbfcqbjh58mdwx00000gn/T/vscode-ssh-askpass-ac121cf9e1bc07315961375ba43be8b167cff4fe.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","61290","-o","ConnectTimeout=15",+host-hidden"],"serverDataFolderName":".vscode-server-insiders","dataFilePath":"/Users/richard/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-9c0f0d8a-ef415578d1b1019db585718968a303eeca4b8979-0.93.2022111115/data.json"}
[14:26:21.045] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.TRLTFwX8fk/Listeners","SHELL":"/bin/bash","DISPLAY":"/private/tmp/com.apple.launchd.tAoedN1zHH/org.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/richard/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/richard/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/5g/qr2tyf4n7jbfcqbjh58mdwx00000gn/T/vscode-ssh-askpass-1ac992e13e716ee082fb90bf782e992c782e0d9f.sock"}
[14:26:21.049] Spawned 43152
[14:26:21.256] > local-server-1> Spawned ssh, pid=43159
[14:26:21.260] stderr> OpenSSH_8.6p1, LibreSSL 3.3.6
[14:26:37.083] stderr> debug1: Server host key: ssh-ed25519 SHA256:STUFF...
[14:26:37.684] stderr> Authenticated to+host-hidden ([185.19.29.190]:22).
[14:26:38.001] > Linux host-hidden 5.18.0-0.deb11.4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.16-1~bpo11+1 (2022-08-12) x86_64
> 
> The programs included with the Debian GNU/Linux system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
> permitted by applicable law.
[14:26:38.011] > 
> FIND PQ Environment -- As of: 2022-10-27 00:00:01.087730524 +0000
[14:26:38.012] > sut01: MOTD STUFF here showing successful SSH
[14:26:38.055] Terminating local server
[14:26:38.059] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (/Users/richard/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/extension.js:1:583947)
	at Timeout._onTimeout (/Users/richard/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.93.2022111115/out/extension.js:1:629238)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[14:26:38.063] Local server exit: 15
[14:26:38.071] ------
```

**Comment by eleanorjboyd** [comment]
Hi! Could you add "echo 'hello'" in your ssh connection command as this helps you ping the server and make sure you can get a response? It seems your ssh connects but then times out so this will give us more understand of where that might be happening.

**Comment by citizenrich** [comment]
Sure. You mean...
```
$ ssh XX@XX echo "hi vscode friends"
hi vscode friends
$
```

**Comment by santhoshcameo** [comment]
@citizenrich  I have the same issue and this is the thread[ https://github.com/microsoft/vscode-remote-release/issues/7441]( https://github.com/microsoft/vscode-remote-release/issues/7441)

**Comment by santhoshcameo** [comment]
The same issue with my personal mac and work machine as well.

**Comment by eleanorjboyd** [comment]
@citizenrich, what version of the remote-SSH extension and OpenSSH do you have?

**Comment by citizenrich** [comment]
I'm using Insiders, and the remote-SSH extension is pre-release v0.93.2022111815.   OpenSSH is OpenSSH_8.6p1 (which looks to be built-in /usr/bin/ssh) not homebrew. HTH

**Comment by citizenrich** [comment]
Thanks. I ran the command with the addition of the user@host at the end and minus the +host-hidden bit because it would error and what happened is that the SSH session hung after the MOTD on the remote host. It got in, ran the MOTD, then just sat there.

**Comment by citizenrich** [comment]
Hi, thanks for all of the support. Here's the command and output. When I say hung, I mean it went idle. But, here's a full log of what happened this time. I removed some user/host stuff/motd stuff.
```
❯ echo "echo hello" | ssh -v -T -D 61290 -o ConnectTimeout=15 user@host
OpenSSH_8.6p1, LibreSSL 3.3.6
debug1: Reading configuration data /Users/richard/.ssh/config
debug1: /Users/richard/.ssh/config line 9: Applying options for host
debug1: /Users/richard/.ssh/config line 18: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
debug1: /etc/ssh/ssh_config line 54: Applying options for *
debug1: /etc/ssh/ssh_config line 58: Applying options for *
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Connecting to host port 22.
debug1: connect to address host port 22: Operation timed out
debug1: Connecting to host port 22.
debug1: fd 5 clearing O_NONBLOCK
debug1: Connection established.
debug1: identity file /Users/richard/.ssh/id_rsa type 0
debug1: identity file /Users/richard/.ssh/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.6
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.4p1 Debian-5+deb11u1
debug1: compat_banner: match: OpenSSH_8.4p1 Debian-5+deb11u1 pat OpenSSH* compat 0x04000000
debug1: Authenticating to host as 'yser'
debug1: load_hostkeys: fopen /Users/richard/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:blahblah
debug1: load_hostkeys: fopen /Users/richard/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: Host 'host' is known and matches the ED25519 host key.
debug1: Found key in /Users/richard/.ssh/known_hosts:135
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /Users/richard/.ssh/id_rsa RSA SHA256:blahblah explicit agent
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering public key: /Users/richard/.ssh/id_rsa RSA SHA256:blahblah explicit agent
debug1: Server accepts key: /Users/richard/.ssh/id_rsa RSA SHA256:blahblah explicit agent
debug1: Authentication succeeded (publickey).
Authenticated to host.
debug1: Local connections to LOCALHOST:61290 forwarded to remote address socks:0
debug1: Local forwarding listening on ::1 port 61290.
debug1: channel 0: new [port listener]
debug1: Local forwarding listening on 127.0.0.1 port 61290.
debug1: channel 1: new [port listener]
debug1: channel 2: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: filesystem full
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: client_input_hostkeys: searching /Users/richard/.ssh/known_hosts for host
debug1: client_input_hostkeys: searching /Users/richard/.ssh/known_hosts2 for host
debug1: client_input_hostkeys: hostkeys file /Users/richard/.ssh/known_hosts2 does not exist
debug1: client_input_hostkeys: no new or deprecated keys from server
debug1: Remote: /home/user/.ssh/authorized_keys:8: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug1: Remote: /home/user/.ssh/authorized_keys:8: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug1: Requesting authentication agent forwarding.
debug1: Sending environment.
debug1: channel 2: setting env LC_TERMINAL_VERSION = "3.4.18"
debug1: channel 2: setting env LANG = "en_US.UTF-8"
debug1: channel 2: setting env LC_TERMINAL = "iTerm2"
Linux host 5.18.0-0.deb11.4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.16-1~bpo11+1 (2022-08-12) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
---
MOTD STUFF
---
debug1: client_input_channel_req: channel 2 rtype exit-status reply 0
hello
debug1: channel 2: free: client-session, nchannels 3
debug1: channel 0: free: port listener, nchannels 2
debug1: channel 1: free: port listener, nchannels 1
debug1: fd 0 clearing O_NONBLOCK
Transferred: sent 3092, received 4540 bytes, in 0.4 seconds
Bytes per second: sent 7263.9, received 10665.6
debug1: Exit status 0
```

**Comment by eleanorjboyd** [comment]
On looking at these logs it seems like we are able to pipe something in correctly and since it just hangs in the other cases I am thinking it might just be a valid timeout issue that is happening when you try the extension. So your SSH connection is idle for the timeout period,  ConnectTimeout=15, and then times out before the install is finished. Could you try increasing the connection timeout setting for the remote-ssh extension? The setting is: `"remote.SSH.connectTimeout"`. Try increasing that value and see if it works. Thanks!

**Comment by citizenrich** [comment]
Thanks for the helpful review. I've tried timeouts of 15, 30, and 60. Same outcome. It actually connects, shows the MOTD, the disconnects complaining of a timeout.

**Comment by santhoshcameo** [comment]
@citizenrich  I had this issue for 1 month, and just now solved it by adding the following line into ( 

`.ssh/config`  file ( **MAC OSX; Monterey**)

```
Host *
  IPQoS=throughput
```

**Comment by citizenrich** [comment]
Thanks @santhoshcameo that's a nice option. It didn't work for me but thanks for the heads up on it. I think that because the other servers I use are working fine, that this particular server simply has some option configured that on it that is causing the problem on the server-side. I'll look more into it.

**Comment by eleanorjboyd** [comment]
@citizenrich what shell are you using? The extension only works with bash so just to confirm is that installed on your remote machine?

**Comment by citizenrich** [comment]
I'm using bash but have switched to zsh and back and still see the same issue. The server-side has always been bash. I

I'll talk to the server admin of that server that has the issues and discuss the ssh settings on it.

**Comment by mladen5000** [comment]
Having this issue as well - works on insiders but not on vscode. It would occur primarily on newly created workspaces but now also on certain folders. Could it be related to some dirty editor that gets called up from the server on remote?

**Comment by eleanorjboyd** [comment]
@mladen5000 it should be because of this fix that went into insiders. It will be released in the next stable release for remote-ssh which should be this week. Thanks! https://github.com/microsoft/vscode-remote-release/issues/7324

**Comment by eleanorjboyd** [comment]
@roblourens, do you have thoughts on @citizenrich's problem?

**Comment by citizenrich** [comment]
Hi folks. The latest release of this plugin or VSCode Insiders just solved it! Thanks for all of the awesome support.

**Comment by eleanorjboyd** [comment]
So glad to hear that! Thank you for following up. Happy coding 🎉
