### ISSUE TITLE
Unable to SSH into a Specific Server but works on Other Servers : Resolver Error

### ISSUE THREAD

**Issue by aki-au** [microsoft/vscode-remote-release#7536]
- VSCode Version: 1.73.1
- Local OS Version: Windows 10 Home 22H2
- Remote OS Version: Linux 5.15.0-48-generic
- Remote Extension/Connection Type: SSH
- Logs:

Failed to parse remote port from server output
'''
[22:13:27.835] Resolver error: Error: 
    at g.Create (c:\Users\akira\\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:583821)
    at t.handleInstallOutput (c:\Users\akira\\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:582473)
    at t.tryInstall (c:\Users\akira\\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:679811)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async c:\Users\akira\\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:642614
    at async t.withShowDetailsEvent (c:\Users\akira\\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:645932)
    at async t.resolve (c:\Users\akira\\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:643664)
    at async c:\Users\akira\\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:722342
'''
Steps to Reproduce:

1. Try to SSH into Server

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

I can SSH normally using Putty.

**Comment by eleanorjboyd** [comment]
Hello! Could you please provide the entire remote-ssh logs? The whole logs includes some settings which are helpful to the debugging process. Thanks!

**Comment by aki-au** [comment]
I was able to solve it, there was a problem with the vscode server on the remote SSH. I deleted the directories, and then cleared up some memory on the remote server as well. 
Then reconnected and it worked
