### ISSUE TITLE
Unable to ssh into a vm .i am able to ssh into vm from normal cmd/Local putty .Getting below error.please help

### ISSUE THREAD

**Issue by amey2688** [microsoft/vscode-remote-release#7537]
SSH command i am using : ssh uname@unameCN%xxxx.net@vmname@psmpint.xxx.net

i am using a corporate system and hence masking internal vm and usernamename. i am conecting to vm via cyberark and hence i have to use cyberark login name and cyberark account used to login, which can be used like uname@unameCN.

this command works fine in normal cmd .

vs code version :
![image](https://user-images.githubusercontent.com/33552841/202361815-289df9c4-4d58-4f4f-93ca-a9a70e7f363a.png)

Getting error "could not establish connection to psmp.xxxx.net"

[10:23:14.338] Log Level: 2
[10:23:14.341] remote-ssh@0.92.0
[10:23:14.341] win32 x64
[10:23:14.343] SSH Resolver called for "ssh-remote+psmpint.xxxx.net", attempt 1
[10:23:14.344] "remote.SSH.useLocalServer": false
[10:23:14.345] "remote.SSH.showLoginTerminal": false
[10:23:14.345] "remote.SSH.remotePlatform": {}
[10:23:14.345] "remote.SSH.path": undefined
[10:23:14.345] "remote.SSH.configFile": undefined
[10:23:14.346] "remote.SSH.useFlock": true
[10:23:14.346] "remote.SSH.lockfilesInTmp": false
[10:23:14.346] "remote.SSH.localServerDownload": auto
[10:23:14.346] "remote.SSH.remoteServerListenOnSocket": false
[10:23:14.347] "remote.SSH.showLoginTerminal": false
[10:23:14.347] "remote.SSH.defaultExtensions": []
[10:23:14.347] "remote.SSH.loglevel": 2
[10:23:14.348] "remote.SSH.enableDynamicForwarding": true
[10:23:14.348] "remote.SSH.enableRemoteCommand": false
[10:23:14.349] "remote.SSH.serverPickPortsFromRange": {}
[10:23:14.349] "remote.SSH.serverInstallPath": {}
[10:23:14.357] SSH Resolver called for host: psmpint.xxxx.net
[10:23:14.358] Setting up SSH remote "psmpint.xxxx.net"
[10:23:14.369] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[10:23:14.375] Install and start server if needed
[10:23:16.244] Checking ssh with "ssh -V"
[10:23:16.445] > OpenSSH_for_Wind
[10:23:16.446] > ows_8.1p1, LibreSSL 3.0.2

[10:23:16.458] Running script with connection command: ssh -T -D 50444 "psmpint.xxxx.net" bash
[10:23:16.464] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:23:17.077] > ]0;C:\WINDOWS\System32\cmd.exe
[10:23:17.077] Got some output, clearing connection timeout
[10:23:18.810] > uname@uname%xxxx.net@vmname@psmpint.xxxx.net's password: 
[10:23:18.811] Showing password prompt
[10:23:36.229] Got password response
[10:23:36.229] "install" wrote data to terminal: "************"
[10:23:36.273] > 
[10:23:43.173] > 
> This session is being recorded
[10:23:43.268] > 
> This is part of xxxxx group’s computer system.
> Only Authorised persons in connection with their associated tasks are allowed  
> access to this system and the information contained herein.
> There is no privacy in this system. Any activity in any form or by any means in
> this system may be monitored, recorded, copied, etc., and may be subject to    
> detailed legal or internal security and administrative investigation.
[10:23:50.212] > 665dfa5b523b: running
[10:23:50.237] > bash: line 186: unexpected EOF while looking for matching `)'
> bash: line 187: syntax error: unexpected end of file
[10:23:51.916] "install" terminal command done
[10:23:51.917] Install terminal quit with output: bash: line 187: syntax error: unexpected end of file
[10:23:51.917] Received install output: bash: line 187: syntax error: unexpected end of file
[10:23:51.918] Failed to parse remote port from server output
[10:23:51.920] Resolver error: Error: 
	at g.Create (c:\Users\xxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:583821)
	at t.handleInstallOutput (c:\Users\xxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:582473)
	at t.tryInstall (c:\Users\xxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:679811)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\xxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:642614
	at async t.withShowDetailsEvent (c:\Users\xxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:645932)
	at async t.resolve (c:\Users\xxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:643664)
	at async c:\Users\xxxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:722342
[10:23:51.926] ------

[10:23:52.106] ------

[10:23:52.106] SSH Resolver called for "ssh-remote+psmpint.xxxx.net", attempt 2, (Reconnection)
[10:23:52.139] SSH Resolver called for host: psmpint.xxxx.net
[10:23:52.139] Setting up SSH remote "psmpint.xxxxx.net"
[10:23:52.144] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[10:23:52.152] Install and start server if needed
[10:24:06.097] getPlatformForHost was canceled
[10:24:06.098] Resolver error: Error: Connecting was canceled
	at g.Canceled (c:\Users\xxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:584017)
	at c:\Users\xxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:642526
	at async t.withShowDetailsEvent (c:\Users\xxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:645932)
	at async t.resolve (c:\Users\xxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:643664)
	at async c:\Users\xxxx\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:722342
[10:24:06.101] ------

[10:24:06.137] ------

[10:24:06.137] SSH Resolver called for "ssh-remote+psmpint.xxxx.net", attempt 3, (Reconnection)
[10:24:06.143] SSH Resolver called for host: psmpint.xxxx.net
[10:24:06.143] Setting up SSH remote "psmpint.xxxx.net"
[10:24:06.146] Using commit id "d045a5eda657f4d7b676dedbfa7aab8207f8a075" and quality "stable" for server
[10:24:06.148] Install and start server if needed

**Comment by eleanorjboyd** [comment]
Hello! Does it work to connect if you run this command from your local terminal: `ssh -T -D 50444 "psmpint.xxxx.net" bash`? Secondly, can you try adding this setting into your user settings: "remote.SSH.remotePlatform": { "YOUR_HOSTNAME": "windows" } and see it that makes it work?

**Comment by amey2688** [comment]
@eleanorjboyd  it does not work while connecting with port 50444, but if i change to another port  for exampleexample 8080 , it works fine . is there any way i can change this default port 50444

**Comment by eleanorjboyd** [comment]
Hello! We have an issue about allowing default port to be configurable here which you could upvote: https://github.com/microsoft/vscode-remote-release/issues/7369. Secondly, the port will actually be randomly chosen each time so if you try to run SSH again it should pick a new random port. Finally, it seems as if you have a corporate proxy of sorts. We have seen this being a cause when the error "Install terminal quit with output: bash: line 187: syntax error: unexpected end of file" comes up. Could you send your SSH config on your remote side as this might show what proxy setting is truncating the install script?

**Comment by amey2688** [comment]
@eleanorjboyd  please find content of ssh config file below :

Host psmpint.<companydomain>.net
  HostName psmpint.<companydomain>.net
  User <uname>@<cyberarkuname>%<companydomain>t@<vmname>

yes i am behind a corporate proxy . i am connecting to vm via cyberark

**Comment by amey2688** [comment]
@eleanorjboyd  below is content of /etc/ssh/sshd_config file . please let me know if you need information of some other file



AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE
AcceptEnv XMODIFIERS
AllowTcpForwarding no
AuthorizedKeysFile .ssh/authorized_keys
Banner /etc/issue.net
ChallengeResponseAuthentication no
Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,aes256-cbc,aes256-cbc
ClientAliveCountMax 0
ClientAliveInterval 30m
GatewayPorts no
GssapiAuthentication no
HostBasedAuthentication no
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
IgnoreRhosts yes
KerberosAuthentication no
LogLevel INFO
LoginGraceTime 60
MaxAuthTries 3
MaxStartups 10:30:60
PermitEmptyPasswords no
PermitRootLogin without-password
PermitUserEnvironment no
Protocol 2
PubkeyAuthentication no
RevokedKeys /etc/ssh/revoked_keys
StrictModes yes
SyslogFacility AUTHPRIV
TCPKeepAlive yes
TrustedUserCAKeys /etc/ssh/ca_keys
UseDns no
UsePAM yes
X11Forwarding no

Subsystem sftp internal-sftp

Match User [computer-user1]
  PubkeyAuthentication yes
Match User [computer-user2]
  PubkeyAuthentication yes
Match User root
  PubkeyAuthentication yes



P.S. :
Changing usernames to [computer-user2] and [computer-user1 ] for security

**Comment by amey2688** [comment]
content of ssh config file on local machine :


Host psmpint.companydomain.net
  HostName psmpint.companydomain.net
  User username@cyberarkuname%companydomain@vmname

yes i am behind a corporate proxy . i am connecting to vm via cyberark

ssh command which works in cmd to connect to vm is :

ssh usernamrname@cyberarkuname%companydomain.net@vmname@psmpint.companydomain.net

**Comment by eleanorjboyd** [comment]
Hello! We have seen users experiencing issues with cyberark in the past as seen in this issue: https://github.com/microsoft/vscode-remote-release/issues/5906. Please check out this issue and subscribe to notifications for updates. I am close this current issue as a dup of #5906. Thanks
