### ISSUE TITLE
The terminal process failed to launch: A native exception occurred during launch (forkpty(3) failed.).

### ISSUE THREAD

**Issue by Holmeyoung** [microsoft/vscode-remote-release#7543]
- VSCode Version: 
  ```bash
  Version: 1.73.1
  Commit: 6261075646f055b99068d3688932416f2346dd3b
  Date: 2022-11-09T02:22:48.959Z (1 wk ago)
  Electron: 19.0.17
  Chromium: 102.0.5005.167
  Node.js: 16.14.2
  V8: 10.2.154.15-electron.0
  OS: Darwin arm64 21.6.0
  Sandboxed: No
  ```
- Local OS Version: Monterey 12.6 (21G115)
- Remote OS Version: Linux n24-182-074 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
- Remote Extension/Connection Type: SSH/Server
- Logs:
    ```bash
    [13:27:03.236] Log Level: 2
    [13:27:03.238] remote-ssh@0.92.0
    [13:27:03.238] darwin arm64
    [13:27:03.243] SSH Resolver called for "ssh-remote+n24-182-074", attempt 1
    [13:27:03.243] "remote.SSH.useLocalServer": false
    [13:27:03.243] "remote.SSH.showLoginTerminal": false
    [13:27:03.243] "remote.SSH.remotePlatform": {"n24-182-074":"linux"}
    [13:27:03.243] "remote.SSH.path": undefined
    [13:27:03.243] "remote.SSH.configFile": undefined
    [13:27:03.243] "remote.SSH.useFlock": true
    [13:27:03.243] "remote.SSH.lockfilesInTmp": false
    [13:27:03.243] "remote.SSH.localServerDownload": auto
    [13:27:03.243] "remote.SSH.remoteServerListenOnSocket": true
    [13:27:03.243] "remote.SSH.showLoginTerminal": false
    [13:27:03.244] "remote.SSH.defaultExtensions": []
    [13:27:03.244] "remote.SSH.loglevel": 2
    [13:27:03.244] "remote.SSH.enableDynamicForwarding": true
    [13:27:03.244] "remote.SSH.enableRemoteCommand": false
    [13:27:03.244] "remote.SSH.serverPickPortsFromRange": {}
    [13:27:03.244] "remote.SSH.serverInstallPath": {}
    [13:27:03.245] SSH Resolver called for host: n24-182-074
    [13:27:03.245] Setting up SSH remote "n24-182-074"
    [13:27:03.248] Using commit id "6261075646f055b99068d3688932416f2346dd3b" and quality "stable" for server
    [13:27:03.251] Install and start server if needed
    [13:27:03.252] PATH: /opt/homebrew/bin:/Users/bytedance/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/puppetlabs/bin
    [13:27:03.252] Checking ssh with "ssh -V"
    [13:27:03.257] > OpenSSH_8.6p1, LibreSSL 3.3.6
    
    [13:27:03.258] Running script with connection command: ssh -T -D 52489 -o ConnectTimeout=15 'n24-182-074' bash
    [13:27:03.372] "install" terminal command done
    [13:27:03.372] Install terminal quit with output: 
    [13:27:03.373] Resolver error: Error: Got bad result from install script
	    at g.Create (/Users/bytedance/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:583821)
	    at t.tryInstall (/Users/bytedance/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:679574)
	    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	    at async /Users/bytedance/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:642614
	    at async t.withShowDetailsEvent (/Users/bytedance/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:645932)
	    at async t.resolve (/Users/bytedance/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:643664)
	    at async /Users/bytedance/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:722342
    [13:27:03.376] ------
    ```

Steps to Reproduce:

1. Everytime when i open a remote folder or reload a remote window, mac will starts two ssh processes、two bash processes.
    <img width="791" alt="image" src="https://user-images.githubusercontent.com/18281399/202629705-d733c75b-e0f7-4f5b-a49d-0ff56a1b66b6.png">
    <img width="960" alt="image" src="https://user-images.githubusercontent.com/18281399/202612802-fa4d77f2-de32-4664-af79-104d4b78c54c.png">
    <img width="960" alt="image" src="https://user-images.githubusercontent.com/18281399/202612817-2c151da6-74f6-442c-b4d2-1b3d5006e741.png">

3. When i close the vscode remote window(not vscode), the ssh、bash process still exists.
4. So, when you open a window, it starts four processes, but when you close, it still exists. And when the number of processes exceeded the maximum number of mac process limit, there will be error. 
    <img width="260" alt="image" src="https://user-images.githubusercontent.com/18281399/202629581-64aeae97-2b67-4ab2-8ba7-faf3ca843bdc.png">

    The reason I came to this conclusion is that when I open the terminal, I get an error
    ![image](https://user-images.githubusercontent.com/18281399/202628780-ac8b4db1-01e6-4be6-b7b6-bf228649c902.png)

6. When i double click the ssh process, it shows the parent process is bash. Click the bash process, it shows the parent process of bash is Code Helper(Renderer), and so on.
    <img width="1797" alt="image" src="https://user-images.githubusercontent.com/18281399/202614737-e56e1bb6-a240-421d-abd4-17a0441eea33.png">
7. For me the solution is using `Command + Q` to  close vscode when the error`The terminal process failed to launch: A native exception occurred during launch (forkpty(3) failed.).]` occurs. It's a terrible experience.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by eleanorjboyd** [comment]
Hello! Could you try running the command `Kill VS Code server on remote` then try reconnecting to see if the same issue occurs? Also can you try running `ssh -T -D 52489 -o ConnectTimeout=15 'n24-182-074' bash` but add `echo "echo hello" |` to the beginning of your SSH command to confirm that we can execute a script on your remote by piping it into ssh.

**Comment by Holmeyoung** [comment]
@eleanorjboyd Thank you for your quick reply 👍
> Could you try running the command Kill VS Code server on remote then try reconnecting to see if the same issue occurs?
1. When i open a remote window
    <img width="960" alt="image" src="https://user-images.githubusercontent.com/18281399/202902769-71327885-3b60-4f92-b1b8-f9f6a9ccc198.png">
    running the command `Kill VS Code server on host n24-182-074`(it's my remote server)
    <img width="1024" alt="image" src="https://user-images.githubusercontent.com/18281399/202902790-a8398608-c857-4109-bcc5-305664b5b251.png">
    it starts two more bash processes
    <img width="1012" alt="image" src="https://user-images.githubusercontent.com/18281399/202902996-a6fd5a37-f460-4692-ab4e-aab8ee5597ce.png">
    After clicking `Reload Window`, the number of bash processes becomes six😭
    <img width="960" alt="image" src="https://user-images.githubusercontent.com/18281399/202903024-32d5a4e6-7a8a-4559-9c31-97810b8d910d.png">

> Also can you try running ssh -T -D 52489 -o ConnectTimeout=15 'n24-182-074' bash but add echo "echo hello" | to the beginning of your SSH command to confirm that we can execute a script on your remote by piping it into ssh.
vsc

I'm sorry I don't know how to add `echo "echo hello" |` to the beginning of my SSH command. I tried to set `alias ssh=echo hello | ssh` in my `.zshrc` but the command in the log didn't change. I also tried
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/18281399/202905362-d67feb9e-ae9e-42b5-9478-2de6a9cf80f0.png">
<img width="1713" alt="image" src="https://user-images.githubusercontent.com/18281399/202905403-0de0746a-1ab5-479f-b027-97d1b21e4b4b.png">
It jumps to
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/18281399/202905442-c6aba3a6-d699-429f-9df2-2569916fbb10.png">

**Comment by eleanorjboyd** [comment]
@Tyriar and @meganrogge, do you have any ideas on why the server terminal processes might not being killed?

**Comment by meganrogge** [comment]
does disabling `terminal.integrated.enablePersistentSessions` fix this for you?

**Comment by Tyriar** [comment]
Looks like this is due to hitting the max number of ptys, see https://codybonney.com/increase-the-max-number-of-ptys-on-os-x-10-8-3/
