### ISSUE TITLE
docker buildx failing with error: unexpected end of JSON input

### ISSUE THREAD

**Issue by aamanraj** [microsoft/vscode-remote-release#7551]
- VSCode Version: 1.74.0-insider (Universal)
- Local OS Version: mac os monterey 
- Remote OS Version: (image is not built)
- Remote Extension/Connection Type: Containers
- Logs: 
   `[2022-11-19T05:33:42.096Z] Dev Containers 0.264.0 in VS Code 1.74.0-insider (1b1e2a2c5794df1f475976062c754651827634a9).
[2022-11-19T05:33:42.096Z] Start: Resolving Remote
[2022-11-19T05:33:42.102Z] Setting up container for folder or workspace: <workspace-path>
[2022-11-19T05:33:42.105Z] Start: Check Docker is running
[2022-11-19T05:33:42.105Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2022-11-19T05:33:42.171Z] Stop (66 ms): Run: docker version --format {{.Server.APIVersion}}
[2022-11-19T05:33:42.171Z] Server API version: 1.41
[2022-11-19T05:33:42.171Z] Stop (66 ms): Check Docker is running
[2022-11-19T05:33:42.172Z] Start: Run: docker volume ls -q
[2022-11-19T05:33:42.223Z] Stop (51 ms): Run: docker volume ls -q
[2022-11-19T05:33:42.235Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=<workspace-path> --filter label=vsch.quality=insider
[2022-11-19T05:33:42.291Z] Stop (56 ms): Run: docker ps -q -a --filter label=vsch.local.folder=<workspace-path> --filter label=vsch.quality=insider
[2022-11-19T05:33:42.291Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=<workspace-path>
[2022-11-19T05:33:42.345Z] Stop (54 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=<workspace-path>
[2022-11-19T05:33:42.345Z] Start: Run: /private/var/folders/j4/_7mr7xm91hlfmz1mr3mm9jc80000gn/T/AppTranslocation/B5624E75-3020-4AA2-81A2-D18319C43AAF/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin) --ms-enable-electron-run-as-node /Users/username/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.264.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/username/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder <workspace-path>--workspace-mount-consistency cached --id-label devcontainer.local_folder=<workspace-path> --log-level debug --log-format json --config <workspace-path>/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-11-19T05:33:42.496Z] (node:16090) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2022-11-19T05:33:42.496Z] (Use `Code - Insiders Helper (Plugin) --trace-deprecation ...` to show where the warning was created)
[2022-11-19T05:33:42.497Z] @devcontainers/cli 0.24.0. Node.js v16.14.2. darwin 21.6.0 arm64.
[2022-11-19T05:33:42.497Z] Start: Run: docker buildx version
[2022-11-19T05:33:42.673Z] Stop (176 ms): Run: docker buildx version
[2022-11-19T05:33:42.673Z] github.com/docker/buildx v0.9.1 ed00243a0ce2a0aee75311b06e32d33b44729689
[2022-11-19T05:33:42.673Z] 
[2022-11-19T05:33:42.673Z] Start: Resolving Remote
[2022-11-19T05:33:42.675Z] Start: Run: git rev-parse --show-cdup
[2022-11-19T05:33:42.685Z] Stop (10 ms): Run: git rev-parse --show-cdup
[2022-11-19T05:33:42.686Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=<workspace-path>
[2022-11-19T05:33:42.738Z] Stop (52 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=<workspace-path>
[2022-11-19T05:33:42.740Z] Start: Run: docker inspect --type image <image-name>
[2022-11-19T05:33:42.790Z] Stop (50 ms): Run: docker inspect --type image <image-name>
[2022-11-19T05:33:42.791Z] local container features stored at: /Users/username/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.264.0/dist/node_modules/vscode-dev-containers/container-features
[2022-11-19T05:33:42.791Z] Start: Run: tar --no-same-owner -x -f -
[2022-11-19T05:33:42.812Z] Stop (21 ms): Run: tar --no-same-owner -x -f -
[2022-11-19T05:33:42.813Z] Start: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/j4/_7mr7xm91hlfmz1mr3mm9jc80000gn/T/devcontainercli/container-features/0.24.0-1668836022790/Dockerfile-with-features -t vsc-<repo-name>-c5102d2aac73724b157247edf322039a --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label <workspace-path>
[2022-11-19T05:33:42.947Z] ERROR: unexpected end of JSON input
[2022-11-19T05:33:42.964Z] Stop (151 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/j4/_7mr7xm91hlfmz1mr3mm9jc80000gn/T/devcontainercli/container-features/0.24.0-1668836022790/Dockerfile-with-features -t vsc-<repo-name>-c5102d2aac73724b157247edf322039a --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label <workspace-path>
[2022-11-19T05:33:42.964Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/j4/_7mr7xm91hlfmz1mr3mm9jc80000gn/T/devcontainercli/container-features/0.24.0-1668836022790/Dockerfile-with-features -t vsc-<repo-name>-c5102d2aac73724b157247edf322039a --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label <workspace-path>
[2022-11-19T05:33:42.964Z]     at Foe (/Users/amanraj/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.264.0/dist/spec-node/devContainersSpecCLI.js:1894:1669)
[2022-11-19T05:33:42.964Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-11-19T05:33:42.964Z]     at async CF (/Users/username/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.264.0/dist/spec-node/devContainersSpecCLI.js:1893:1978)
[2022-11-19T05:33:42.964Z]     at async oT (/Users/username/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.264.0/dist/spec-node/devContainersSpecCLI.js:1893:901)
[2022-11-19T05:33:42.965Z]     at async koe (/Users/username/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.264.0/dist/spec-node/devContainersSpecCLI.js:1899:2128)
[2022-11-19T05:33:42.965Z]     at async Zf (/Users/username/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.264.0/dist/spec-node/devContainersSpecCLI.js:1899:3278)
[2022-11-19T05:33:42.965Z]     at async iue (/Users/username/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.264.0/dist/spec-node/devContainersSpecCLI.js:2019:15058)
[2022-11-19T05:33:42.965Z]     at async nue (/Users/username/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.264.0/dist/spec-node/devContainersSpecCLI.js:2019:14812)
[2022-11-19T05:33:42.966Z] Stop (621 ms): Run: /private/var/folders/j4/_7mr7xm91hlfmz1mr3mm9jc80000gn/T/AppTranslocation/B5624E75-3020-4AA2-81A2-D18319C43AAF/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin) --ms-enable-electron-run-as-node /Users/username/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.264.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/username/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder <workspace-path> --workspace-mount-consistency cached --id-label devcontainer.local_folder=<workspace-path> --log-level debug --log-format json --config <workspace-path>/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-11-19T05:33:42.966Z] Exit code 1
[2022-11-19T05:33:42.968Z] Command failed: /private/var/folders/j4/_7mr7xm91hlfmz1mr3mm9jc80000gn/T/AppTranslocation/B5624E75-3020-4AA2-81A2-D18319C43AAF/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin) --ms-enable-electron-run-as-node /Users/username/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.264.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/username/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder <workspace-path>--workspace-mount-consistency cached --id-label devcontainer.local_folder=<workspace-path> --log-level debug --log-format json --config <workspace-path>/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-11-19T05:33:42.968Z] Exit code 1
`

Steps to Reproduce:

1.  create devcontainer.json with following content  
     `{
	"name": "Go",
	"dockerFile": "Dockerfile",
	"context": "..",
	"runArgs": [
		"--cap-add=SYS_PTRACE",
		"--security-opt",
		"seccomp=unconfined",
		"platform=linux/amd64"
	],
	"extensions": [
		"golang.go",
		"streetsidesoftware.code-spell-checker"
	],
	"settings": {
		"go.gopath": "/go"
	}
} `

2. with dockerfile containing amd64 based linux image 

Does this issue occur when you try this locally?: Yes

This was working when using sytem with intel based architecture, only reporducible in apple sillicon

**Comment by aamanraj** [comment]
issue was with docker buildx command, probably with its installation
