### ISSUE TITLE
Remote SSH not being able to connect

### ISSUE THREAD

**Issue by moseleyi** [microsoft/vscode-remote-release#7553]
- VSCode Version: 1.73.1
- Local OS Version: Windows 10
- Remote OS Version: Linux
- Remote Extension/Connection Type: SSH
- Logs:

So far I used SSHExtension to connect to my shared hosting server that allows me to connect to it va SSH. I use the following configuration:

```json
"sshextension.serverList": [{
    "name": "My Server",
    "host": "serwer.com",
    "port": 22222,
    "username": "server183904",
    "privateKey": "C:\\Users\\<my_name>\\.ssh\\s_home",
    "path": "/"
}]
```

Then I installed the Remote SSH extension but after few hours of trying I still couldn't connect. I went through removing unnecessary permissions on my `s_home` file as it has been suggested. 

Then I get this information:

![image](https://user-images.githubusercontent.com/16131590/202925272-9a2a0cc8-cf26-4315-bc5a-96dee07f3a05.png)

And after about 30s this is what I see in the logs:

```
[21:46:07.820] Log Level: 2
[21:46:07.827] remote-ssh@0.92.0
[21:46:07.828] win32 x64
[21:46:07.838] SSH Resolver called for "ssh-remote+my_server", attempt 1
[21:46:07.838] "remote.SSH.useLocalServer": false
[21:46:07.839] "remote.SSH.showLoginTerminal": false
[21:46:07.839] "remote.SSH.remotePlatform": {}
[21:46:07.840] "remote.SSH.path": undefined
[21:46:07.840] "remote.SSH.configFile": undefined
[21:46:07.840] "remote.SSH.useFlock": false
[21:46:07.840] "remote.SSH.lockfilesInTmp": true
[21:46:07.841] "remote.SSH.localServerDownload": auto
[21:46:07.841] "remote.SSH.remoteServerListenOnSocket": false
[21:46:07.841] "remote.SSH.showLoginTerminal": false
[21:46:07.842] "remote.SSH.defaultExtensions": []
[21:46:07.842] "remote.SSH.loglevel": 2
[21:46:07.842] "remote.SSH.enableDynamicForwarding": true
[21:46:07.842] "remote.SSH.enableRemoteCommand": false
[21:46:07.843] "remote.SSH.serverPickPortsFromRange": {}
[21:46:07.843] "remote.SSH.serverInstallPath": {}
[21:46:07.848] SSH Resolver called for host: <host>
[21:46:07.848] Setting up SSH remote "<host>"
[21:46:07.857] Using commit id "6261075646f055b99068d3688932416f2346dd3b" and quality "stable" for server
[21:46:07.866] Install and start server if needed
[21:46:09.750] Checking ssh with "ssh -V"
[21:46:09.781] > OpenSSH_for_Windows_8.1p1
[21:46:09.782] > , LibreSSL 3.0.2

[21:46:09.786] Running script with connection command: ssh -T -D 55458 "<hos>" bash
[21:46:09.789] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[21:46:10.114] > ]0;C:\WINDOWS\System32\cmd.exe
[21:46:10.114] Got some output, clearing connection timeout
[21:46:11.619] > 1cf1e6894045: running
> Missing GLIBC >= 2.17!
> Found version
> 1cf1e6894045$$1$$
> Acquiring lock on /tmp/vscode-remote-lock.serwer1846576.6261075646f055b99068d368
> 8932416f2346dd3b
> \ln /tmp/vscode-remote-lock.serwer1846576.6261075646f055b99068d3688932416f2346dd
> 3b.target /tmp/vscode-remote-lock.serwer1846576.6261075646f055b99068d3688932416f
> 2346dd3b
> Installing to /home/serwer1846576/.vscode-server/bin/6261075646f055b99068d368893
> 2416f2346dd3b...
> 1cf1e6894045%%1%%
> Downloading with wget
[21:46:11.643] > bash: line 180: /usr/bin/ldd: Permission denied
[21:46:41.882] > Download complete
[21:46:42.003] > 1cf1e6894045%%2%%
> tar --version:
> tar (GNU tar) 1.34
> Copyright (C) 2021 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[21:47:12.910] "install" terminal command done
[21:47:12.911] Install terminal quit with output: 
[21:47:12.912] Resolver error: Error: Got bad result from install script
	at g.Create (c:\Users\<my_user>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:583821)
	at t.tryInstall (c:\Users\<my_user>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:679574)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\<my_user>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:642614
	at async t.withShowDetailsEvent (c:\Users\<my_user>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:645932)
	at async t.resolve (c:\Users\<my_user>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:643664)
	at async c:\Users\<my_user>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:722342
[21:47:12.919] ------
```

I'm just curious if it's even possible or the server I use, doesn't give me enough permissions to install everything that's necessary?

**Comment by eleanorjboyd** [comment]
Hello! I would review this doc about that error message you got to see if your machine's current version are compatible with the extension: https://code.visualstudio.com/docs/remote/linux. It has a section called updating glibc and libstdc++ which might be particular applicable!
