### ISSUE TITLE
bash not found

### ISSUE THREAD

**Issue by an-mediola** [microsoft/vscode-remote-release#7561]
I can connect to my special linux based gateway with normal ssh client,   
but when I used this vscode extension, I get an error which says bash not found.
I do not have bash in my gateway, I have sh. Is there any way to connect to this gateway by this extension or not?
I do not and for some reasons can not install anything on the gateway, I just want to be able to connect to it and run some commands.

- VSCode Version: 1.73.1 6261075646f055b99068d3688932416f2346dd3b x64
- Local OS Version: macOs ventura 13
- Remote OS Version: Linux  4.14.95-v7 #1 SMP Sat May 21 02:17:49 CEST 2022 armv7l GNU/Linux
- Remote Extension/Connection Type: SSH
- Logs: 
```
[10:25:17.436] Log Level: 2
[10:25:17.444] remote-ssh@0.92.0
[10:25:17.445] darwin x64
[10:25:17.460] SSH Resolver called for "ssh-remote+192.168.55.70", attempt 1
[10:25:17.462] "remote.SSH.useLocalServer": false
[10:25:17.463] "remote.SSH.showLoginTerminal": true
[10:25:17.464] "remote.SSH.remotePlatform": {"192.168.55.70":"linux"}
[10:25:17.464] "remote.SSH.path": undefined
[10:25:17.465] "remote.SSH.configFile": undefined
[10:25:17.465] "remote.SSH.useFlock": true
[10:25:17.465] "remote.SSH.lockfilesInTmp": false
[10:25:17.465] "remote.SSH.localServerDownload": auto
[10:25:17.466] "remote.SSH.remoteServerListenOnSocket": false
[10:25:17.466] "remote.SSH.showLoginTerminal": true
[10:25:17.473] "remote.SSH.defaultExtensions": []
[10:25:17.473] "remote.SSH.loglevel": 2
[10:25:17.475] "remote.SSH.enableDynamicForwarding": true
[10:25:17.475] "remote.SSH.enableRemoteCommand": false
[10:25:17.475] "remote.SSH.serverPickPortsFromRange": {}
[10:25:17.475] "remote.SSH.serverInstallPath": {}
[10:25:17.494] SSH Resolver called for host: 192.168.55.70
[10:25:17.494] Setting up SSH remote "192.168.55.70"
[10:25:17.516] Using commit id "6261075646f055b99068d3688932416f2346dd3b" and quality "stable" for server
[10:25:17.610] Install and start server if needed
[10:25:17.620] PATH: /usr/local/sbin:/Users/amir/bin:/Users/amir/.pyenv/versions/3.7.2/bin:/usr/local/opt/mysql@5.6/bin:/usr/local/opt/openjdk@8/bin:/usr/local/opt/tomcat@8/bin:/usr/local/opt/tomcat@8/bin:/usr/local/opt/openjdk/bin:/usr/local/opt/mysql@5.6/bin:/usr/local/opt/mysql@5.6/bin:/Users/amir/.nvm/versions/node/v14.17.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/amir/Applications/apache-maven-3.6.3/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/amir/.ebcli-virtual-env/executables:/Users/amir/Gitlab/flutter/bin
[10:25:17.620] Checking ssh with "ssh -V"
[10:25:17.653] > OpenSSH_9.0p1, LibreSSL 3.3.6

[10:25:17.658] Running script with connection command: ssh -T -D 52183 -o ConnectTimeout=15 '192.168.55.70' bash
[10:25:19.284] > root@192.168.55.70's password: 
[10:25:19.285] Got some output, clearing connection timeout
[10:25:21.521] > 
[10:25:21.578] > sh: bash: not found
[10:25:21.895] "install" terminal command done
[10:25:21.897] Install terminal quit with output: sh: bash: not found
[10:25:21.897] Received install output: sh: bash: not found
[10:25:21.903] Resolver error: Error: bash not found
	at g.Create (/Users/amir/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:583821)
	at /Users/amir/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:581960
	at t.handleInstallOutput (/Users/amir/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:582395)
	at t.tryInstall (/Users/amir/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:679811)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/amir/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:642614
	at async t.withShowDetailsEvent (/Users/amir/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:645932)
	at async t.resolve (/Users/amir/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:643664)
	at async /Users/amir/.vscode/extensions/ms-vscode-remote.remote-ssh-0.92.0/out/extension.js:1:722342
[10:25:21.922] ------
```

**Comment by eleanorjboyd** [comment]
Hello! To confirm if you run this SSH command in your local terminal it doesn't work right? `ssh -T -D 52183 -o ConnectTimeout=15 '192.168.55.70' bash` And does the command work if you remove `bash` from that command?

**Comment by an-mediola** [comment]
well without bash it opens the socket : 
```
root@192.168.55.70's password: 
Authenticated to 192.168.55.70 ([192.168.55.70]:22) using "password".
debug1: Local connections to LOCALHOST:52183 forwarded to remote address socks:0
debug1: Local forwarding listening on ::1 port 52183.
debug1: channel 0: new [port listener]
debug1: Local forwarding listening on 127.0.0.1 port 52183.
debug1: channel 1: new [port listener]
debug1: channel 2: new [client-session]
debug1: Entering interactive session.
debug1: pledge: filesystem
debug1: Sending environment.
debug1: channel 2: setting env LC_CTYPE = "UTF-8"
```

with bash it fails:
```
root@192.168.55.70's password: 
Authenticated to 192.168.55.70 ([192.168.55.70]:22) using "password".
debug1: Local connections to LOCALHOST:52183 forwarded to remote address socks:0
debug1: Local forwarding listening on ::1 port 52183.
debug1: channel 0: new [port listener]
debug1: Local forwarding listening on 127.0.0.1 port 52183.
debug1: channel 1: new [port listener]
debug1: channel 2: new [client-session]
debug1: Entering interactive session.
debug1: pledge: filesystem
debug1: Sending environment.
debug1: channel 2: setting env LC_CTYPE = "UTF-8"
debug1: Sending command: bash
debug1: client_input_channel_req: channel 2 rtype exit-status reply 0
sh: bash: not found
debug1: channel 2: free: client-session, nchannels 3
debug1: channel 0: free: port listener, nchannels 2
debug1: channel 1: free: port listener, nchannels 1
Transferred: sent 1960, received 984 bytes, in 0.0 seconds
Bytes per second: sent 92527.0, received 46452.3
debug1: Exit status 127
```

**Comment by an-mediola** [comment]
@eleanorjboyd any update? should I have hope or give up?

**Comment by eleanorjboyd** [comment]
Hello! Sorry for the delay with the American holiday. In your first message you said you don't have bash in your gateway, do you have it in the server you are trying to connect to? Our extension does require bash because of a few specific commands and therefore we would have to rewrite our script to have it be compatible with sh.

**Comment by an-mediola** [comment]
@eleanorjboyd no I don't have bash. Without bash it will not work?

**Comment by an-mediola** [comment]
@eleanorjboyd it would be great. well I don't know how the procedure works, please guide me.
Based on https://code.visualstudio.com/docs/remote/ssh we should be able to use it with __ANY__ remote machine. 
SSH server is important but the shell should not.  
```
The Visual Studio Code Remote - SSH extension allows you 
to open a remote folder on any remote machine, virtual machine, or container with a running SSH server 
and take full advantage of VS Code's feature set.
```
