### ISSUE TITLE
failed at docker inspect and no logging provides helpful information.

### ISSUE THREAD

**Issue by Celthi** [microsoft/vscode-remote-release#7619]
- VSCode Version: 1.73.1 
- Local OS Version: Win 10 enterprise 10.0.19044
- Remote OS Version: Red Hat Enterprise Linux Server 7.7 (Maipo)
- Remote Extension/Connection Type: Containers
- Logs:
```
[263 ms] Dev Containers 0.265.0 in VS Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b).
[262 ms] Start: Resolving Remote
[272 ms] Setting up container for folder or workspace: d:\repos\remote-iserver\iserver-dev-to-space
[272 ms] Host: ssh://root@space
[273 ms] Local Docker: true
[277 ms] Start: Check Docker is running
[277 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[6442 ms] Stop (6165 ms): Run: docker version --format {{.Server.APIVersion}}
[6442 ms] Server API version: 1.40
[6442 ms] Stop (6165 ms): Check Docker is running
[6443 ms] Start: Run: docker volume ls -q
[14409 ms] Stop (7966 ms): Run: docker volume ls -q
[14464 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=d:\repos\remote-iserver\iserver-dev-to-space --filter label=vsch.quality=stable
[22438 ms] Stop (7974 ms): Run: docker ps -q -a --filter label=vsch.local.folder=d:\repos\remote-iserver\iserver-dev-to-space --filter label=vsch.quality=stable
[22438 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=d:\repos\remote-iserver\iserver-dev-to-space
[30927 ms] Stop (8489 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=d:\repos\remote-iserver\iserver-dev-to-space
[30928 ms] Start: Run: docker inspect --type container cfdb1567b4c8
[38885 ms] Stop (7957 ms): Run: docker inspect --type container cfdb1567b4c8
[38886 ms] Start: Run: C:\Users\xialu\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\xialu\.vscode\extensions\ms-vscode-remote.remote-containers-0.265.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\xialu\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder d:\repos\remote-iserver\iserver-dev-to-space --workspace-mount-consistency cached --id-label devcontainer.local_folder=d:\repos\remote-iserver\iserver-dev-to-space --log-level trace --log-format json --config d:\repos\remote-iserver\iserver-dev-to-space\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true --terminal-columns 282 --terminal-rows 28
[39118 ms] (node:10336) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[39118 ms] (Use `Code --trace-deprecation ...` to show where the warning was created)
[39120 ms] @devcontainers/cli 0.25.0. Node.js v16.14.2. win32 10.0.19044 x64.
[39120 ms] Start: Run: docker buildx version
[49535 ms] Stop (10415 ms): Run: docker buildx version
[49536 ms] github.com/docker/buildx v0.5.1-docker 11057da37336192bfc57d81e02359ba7ba848e4a
[49536 ms] 
[49536 ms] Start: Resolving Remote
[49539 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=d:\repos\remote-iserver\iserver-dev-to-space
[53533 ms] Stop (3994 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=d:\repos\remote-iserver\iserver-dev-to-space
[53533 ms] Error: Command failed: docker ps -q -a --filter label=devcontainer.local_folder=d:\repos\remote-iserver\iserver-dev-to-space
[53533 ms]     at voe (c:\Users\xialu\.vscode\extensions\ms-vscode-remote.remote-containers-0.265.0\dist\spec-node\devContainersSpecCLI.js:1893:1355)
[53534 ms]     at oT (c:\Users\xialu\.vscode\extensions\ms-vscode-remote.remote-containers-0.265.0\dist\spec-node\devContainersSpecCLI.js:1893:1291)
[53534 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[53534 ms]     at async Ioe (c:\Users\xialu\.vscode\extensions\ms-vscode-remote.remote-containers-0.265.0\dist\spec-node\devContainersSpecCLI.js:1899:2128)
[53534 ms]     at async Zf (c:\Users\xialu\.vscode\extensions\ms-vscode-remote.remote-containers-0.265.0\dist\spec-node\devContainersSpecCLI.js:1899:3278)
[53534 ms]     at async oue (c:\Users\xialu\.vscode\extensions\ms-vscode-remote.remote-containers-0.265.0\dist\spec-node\devContainersSpecCLI.js:2020:15162)
[53534 ms]     at async sue (c:\Users\xialu\.vscode\extensions\ms-vscode-remote.remote-containers-0.265.0\dist\spec-node\devContainersSpecCLI.js:2020:14916)
[53541 ms] Stop (14655 ms): Run: C:\Users\xialu\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\xialu\.vscode\extensions\ms-vscode-remote.remote-containers-0.265.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\xialu\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder d:\repos\remote-iserver\iserver-dev-to-space --workspace-mount-consistency cached --id-label devcontainer.local_folder=d:\repos\remote-iserver\iserver-dev-to-space --log-level trace --log-format json --config d:\repos\remote-iserver\iserver-dev-to-space\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true --terminal-columns 282 --terminal-rows 28
[53542 ms] Exit code 1
[53545 ms] Command failed: C:\Users\xialu\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\xialu\.vscode\extensions\ms-vscode-remote.remote-containers-0.265.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\xialu\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder d:\repos\remote-iserver\iserver-dev-to-space --workspace-mount-consistency cached --id-label devcontainer.local_folder=d:\repos\remote-iserver\iserver-dev-to-space --log-level trace --log-format json --config d:\repos\remote-iserver\iserver-dev-to-space\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true --terminal-columns 282 --terminal-rows 28
[53545 ms] Exit code 1
```

Steps to Reproduce:

**I believe this is somehow related to my env thus reproducing steps here is not revalent. But the logs gives little information. It only says that exit code 1 and the ` Command failed: docker ps -q -a --filter label=devcontainer.local_folder=d:\repos\remote-iserver\iserver-dev-to-space`
This issue here is to see if more information could be provided in the logging to help troubleshooting. Please know that I have turned the logging level to trace. But not much information can be seen from the output.
I also try to rebuild the container but got no luck. The following is the log with the trace turned on while clicking "rebuild container"**

```
[52 ms] Dev Containers 0.265.0 in VS Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b).
[52 ms] Start: Resolving Remote
[60 ms] Setting up container for folder or workspace: d:\repos\remote-iserver\iserver-dev-to-space
[60 ms] Host: ssh://root@space
[60 ms] Local Docker: true
[64 ms] Start: Check Docker is running
[64 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[5494 ms] Stop (5430 ms): Run: docker version --format {{.Server.APIVersion}}
[5494 ms] Server API version: 1.40
[5494 ms] Stop (5430 ms): Check Docker is running
[5494 ms] Start: Run: docker volume ls -q
[13389 ms] Stop (7895 ms): Run: docker volume ls -q
[13443 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=d:\repos\remote-iserver\iserver-dev-to-space --filter label=vsch.quality=stable
[21365 ms] Stop (7922 ms): Run: docker ps -q -a --filter label=vsch.local.folder=d:\repos\remote-iserver\iserver-dev-to-space --filter label=vsch.quality=stable
[21366 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=d:\repos\remote-iserver\iserver-dev-to-space
[29312 ms] Stop (7946 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=d:\repos\remote-iserver\iserver-dev-to-space
[29313 ms] Start: Run: docker inspect --type container cfdb1567b4c8
[37278 ms] Stop (7965 ms): Run: docker inspect --type container cfdb1567b4c8
[37278 ms] Start: Run: C:\Users\xialu\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\xialu\.vscode\extensions\ms-vscode-remote.remote-containers-0.265.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\xialu\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder d:\repos\remote-iserver\iserver-dev-to-space --workspace-mount-consistency cached --id-label devcontainer.local_folder=d:\repos\remote-iserver\iserver-dev-to-space --log-level trace --log-format json --config d:\repos\remote-iserver\iserver-dev-to-space\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true --terminal-columns 282 --terminal-rows 28
[37514 ms] (node:7100) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[37514 ms] (Use `Code --trace-deprecation ...` to show where the warning was created)
[37516 ms] @devcontainers/cli 0.25.0. Node.js v16.14.2. win32 10.0.19044 x64.
[37516 ms] Start: Run: docker buildx version
[47743 ms] Stop (10227 ms): Run: docker buildx version
[47744 ms] github.com/docker/buildx v0.5.1-docker 11057da37336192bfc57d81e02359ba7ba848e4a
[47744 ms] 
[47744 ms] Start: Resolving Remote
[47747 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=d:\repos\remote-iserver\iserver-dev-to-space
[53365 ms] Stop (5618 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=d:\repos\remote-iserver\iserver-dev-to-space
[53366 ms] Error: Command failed: docker ps -q -a --filter label=devcontainer.local_folder=d:\repos\remote-iserver\iserver-dev-to-space
[53366 ms]     at voe (c:\Users\xialu\.vscode\extensions\ms-vscode-remote.remote-containers-0.265.0\dist\spec-node\devContainersSpecCLI.js:1893:1355)
[53366 ms]     at oT (c:\Users\xialu\.vscode\extensions\ms-vscode-remote.remote-containers-0.265.0\dist\spec-node\devContainersSpecCLI.js:1893:1291)
[53366 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[53366 ms]     at async Ioe (c:\Users\xialu\.vscode\extensions\ms-vscode-remote.remote-containers-0.265.0\dist\spec-node\devContainersSpecCLI.js:1899:2128)
[53367 ms]     at async Zf (c:\Users\xialu\.vscode\extensions\ms-vscode-remote.remote-containers-0.265.0\dist\spec-node\devContainersSpecCLI.js:1899:3278)
[53367 ms]     at async oue (c:\Users\xialu\.vscode\extensions\ms-vscode-remote.remote-containers-0.265.0\dist\spec-node\devContainersSpecCLI.js:2020:15162)
[53367 ms]     at async sue (c:\Users\xialu\.vscode\extensions\ms-vscode-remote.remote-containers-0.265.0\dist\spec-node\devContainersSpecCLI.js:2020:14916)
[53373 ms] Stop (16095 ms): Run: C:\Users\xialu\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\xialu\.vscode\extensions\ms-vscode-remote.remote-containers-0.265.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\xialu\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder d:\repos\remote-iserver\iserver-dev-to-space --workspace-mount-consistency cached --id-label devcontainer.local_folder=d:\repos\remote-iserver\iserver-dev-to-space --log-level trace --log-format json --config d:\repos\remote-iserver\iserver-dev-to-space\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true --terminal-columns 282 --terminal-rows 28
[53374 ms] Exit code 1
[53376 ms] Command failed: C:\Users\xialu\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\xialu\.vscode\extensions\ms-vscode-remote.remote-containers-0.265.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\xialu\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder d:\repos\remote-iserver\iserver-dev-to-space --workspace-mount-consistency cached --id-label devcontainer.local_folder=d:\repos\remote-iserver\iserver-dev-to-space --log-level trace --log-format json --config d:\repos\remote-iserver\iserver-dev-to-space\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true --terminal-columns 282 --terminal-rows 28
[53376 ms] Exit code 1
```

Does this issue occur when you try this locally?: Not applicable
Does this issue occur when you try this locally and all extensions are disabled?: Not applicable

**Comment by Celthi** [comment]
The command `docker ps -q -a --filter label=devcontainer.local_folder=d:\repos\remote-iserver\iserver-dev-to-space` can be run in the terminal if I ssh to the remote host machine.

**Comment by chrmarti** [comment]
It runs this command on your Windows machine, could you try running it there to see if that works? Add `--host ssh://root@space` to the options to make it connect to the remote Docker daemon.

**Comment by Celthi** [comment]
@chrmarti 
The command `docker ps -q -a ` should run in the remote host if my understanding is correct. My above picture shows that it successfully run in the remote host if I type them manually.
Are you suggesting running the command on a windows machine?

**Comment by Celthi** [comment]
@chrmarti
The command docker ps -q -a should run in the remote host if my understanding is correct. My above picture shows that it successfully run in the remote host if I type them manually.
Are you suggesting running the command on a windows machine?

**Comment by chrmarti** [comment]
`Local Docker: true` indicates that it is running these commands locally. It does that when you reopen a local folder in a dev container while you are connected to a remote Docker host.

We recommend using Remote-SSH to connect to an SSH server, set up your workspace folder there and then reopen that in a Dev Container. When the workspace folder is on the same machine as the Docker daemon, that folder can be mounted into the container.
