### ISSUE TITLE
Can't connect with ssh to linux server after upgrading to windows 11

### ISSUE THREAD

**Issue by ysig** [microsoft/vscode-remote-release#7659]
Hi,

from a previous post after upgrading to windows 11 I can't use remote explorer in vs code.
This has dropped my productivity significantly and wasn't solved by the latest update.

Here is the log:
```
[23:08:31.540] Log Level: 2
[23:08:31.547] remote-ssh@0.92.0
[23:08:31.548] win32 x64
[23:08:31.563] SSH Resolver called for "ssh-remote+imagine", attempt 1
[23:08:31.564] "remote.SSH.useLocalServer": false
[23:08:31.565] "remote.SSH.showLoginTerminal": false
[23:08:31.565] "remote.SSH.remotePlatform": {"172.22.11.40":"windows"}
[23:08:31.565] "remote.SSH.path": undefined
[23:08:31.565] "remote.SSH.configFile": undefined
[23:08:31.565] "remote.SSH.useFlock": true
[23:08:31.565] "remote.SSH.lockfilesInTmp": false
[23:08:31.565] "remote.SSH.localServerDownload": auto
[23:08:31.566] "remote.SSH.remoteServerListenOnSocket": false
[23:08:31.566] "remote.SSH.showLoginTerminal": false
[23:08:31.566] "remote.SSH.defaultExtensions": []
[23:08:31.566] "remote.SSH.loglevel": 2
[23:08:31.567] "remote.SSH.enableDynamicForwarding": true
[23:08:31.567] "remote.SSH.enableRemoteCommand": false
[23:08:31.567] "remote.SSH.serverPickPortsFromRange": {}
[23:08:31.567] "remote.SSH.serverInstallPath": {}
[23:08:31.575] SSH Resolver called for host: imagine
[23:08:31.575] Setting up SSH remote "imagine"
[23:08:31.582] Using commit id "5235c6bb189b60b01b1f49062f4ffa42384f8c91" and quality "stable" for server
[23:08:31.588] Install and start server if needed
[23:08:32.677] Checking ssh with "ssh -V"
[23:08:32.738] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[23:08:32.743] Running script with connection command: ssh -T -D 57224 imagine bash
[23:08:32.747] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[23:08:33.136] > kex_exchange_identification: Connection closed by remote host
> Connection closed by UNKNOWN port 65535
> The process tried to write to a nonexistent pipe.
> ]0;C:\WINDOWS\System32\cmd.exe
[23:08:33.137] Got some output, clearing connection timeout
[23:08:34.426] "install" terminal command done
[23:08:34.427] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exe
[23:08:34.428] Received install output: ]0;C:\WINDOWS\System32\cmd.exe
[23:08:34.429] Failed to parse remote port from server output
[23:08:34.432] Resolver error: Error: 
	at g.Create (c:\Users\mirag\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:583821)
	at t.handleInstallOutput (c:\Users\mirag\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:582473)
	at t.tryInstall (c:\Users\mirag\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:679811)
	at async c:\Users\mirag\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:642614
	at async t.withShowDetailsEvent (c:\Users\mirag\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:645932)
	at async t.resolve (c:\Users\mirag\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:643664)
	at async c:\Users\mirag\.vscode\extensions\ms-vscode-remote.remote-ssh-0.92.0\out\extension.js:1:722342
[23:08:34.442] ------
```

**Comment by ysig** [comment]
Not sure what step 2 means - I ssh using Ubuntu WSL.

**Comment by ysig** [comment]
The output of the remote explorer from vscode is exactly the one I have posted above.

**Comment by eleanorjboyd** [comment]
Step 2 is asking you to run this command  `ssh -T -D 57224 imagine bash` from your local terminal which can be found in the Remote-SSH logs on this line `Running script with connection command: ssh -T -D 57224 imagine bash`. This is the ssh exact ssh command the extension is trying to run so by running it locally you can check your ssh connection to collect more insight into where the issue might be. Same also goes for step 3, these are not solutions but instead steps to find additional information which helps troubleshoot. And yes, the logs above are your remote-ssh logs so those are very helpful to debug once we know the result of Steps 2 and 3.

**Comment by ysig** [comment]
So I find the bug thanks to your advice. The reason is that I connect to an old server and the ssh got updated so I had to add some algorithm key exchange additional configurations.

Thank you so much :)

**Comment by eleanorjboyd** [comment]
So glad to hear you found the issue! Thanks!
