### ISSUE TITLE
Tunnel connection fails on desktop (Windows 8.1), but works on vscode.dev

### ISSUE THREAD

**Issue by csubich** [microsoft/vscode-remote-release#7680]
I have a VSCode tunnel set up on a remote Linux system as per https://code.visualstudio.com/docs/remote/tunnels.  The tunnel works quite nicely through the web version of VSCode at the tunnel-supplied vscode.dev link.  However, the connection from my desktop machine fails with the error `ailed to connect to the remote extension host server (Error: Illegal argument: connectionToken)`

The error message suggests opening Developer Tools, which loads the full traceback:

```  
INFO [attempt 4] Invoking resolveAuthority(tunnel)
ERR [attempt 4] resolveAuthority(tunnel) returned an error after 28 ms Error: Illegal argument: connectionToken
	at P (c:\Users\Christopher\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:7:1129)
	at new Y (c:\Users\Christopher\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:17352)
	at C.resolve (c:\Users\Christopher\.vscode\extensions\ms-vscode.remote-server-1.1.2022120609\dist\node\extension.js:2:945336)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async d.$resolveAuthority (c:\Users\Christopher\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:18208)
```

and

```
ERR [remote-connection][attempt 2] An error occurred in initial connection! Will retry... Error:
ERR Error: Illegal argument: connectionToken
	at P (c:\Users\Christopher\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:7:1129)
	at new Y (c:\Users\Christopher\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:17352)
	at C.resolve (c:\Users\Christopher\.vscode\extensions\ms-vscode.remote-server-1.1.2022120609\dist\node\extension.js:2:945336)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async d.$resolveAuthority (c:\Users\Christopher\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:18208)
```

As suggested by the `[attempt 4]` and `[attempt 2]`, these errors repeat several times in the log.  I've included one illustrative example; the others are identical.

Outbound connection attempts via the `SSH` tunnel from this computer do succeed; the error appears to be restricted to the new tunnel variant.

- VSCode Version:1.74.0
- Local OS Version: Windows 8.1
- Remote OS Version: Linux (Alpine)
- Remote Extension/Connection Type: Tunnel

Steps to Reproduce:

1. Create tunnel on remote system via `./code tunnel [etc]`
2. Connect to tunnel via vscode.dev link (works)
3. Attempt to connect to tunnel via VSCode on desktop (fails)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: N/A (Remote - Tunnels is a required extension)

**Comment by eamodio** [comment]
I see the same thing -- works from the web, but not on the desktop. When I try to connect from 1 machine to another (all on the same WiFi), I just see 3 notifications that its connecting, but never does

![image](https://user-images.githubusercontent.com/641685/206929828-b4fccf98-86e2-40ce-997c-b08080115cc1.png)

**Comment by lamhm** [comment]
> I see the same thing -- works from the web, but not on the desktop. When I try to connect from 1 machine to another (all on the same WiFi), I just see 3 notifications that its connecting, but never does

Same here. Both of my host and my remote machines are running on Ubuntu 20.04 and VS Code 1.74.0.

**Comment by AbolhasanAshori** [comment]
Same here but only from remote machine (Manjaro) to host (Windows 10).
the other way works fine (win10 --> manjaro)

**Comment by mjkanji** [comment]
Answered in #7661. This is supposed to be fixed in a new build on Monday.

**Comment by eamodio** [comment]
Fixed the issue for me! Thanks
