### ISSUE TITLE
Cannot connect to container after update to 1.74

### ISSUE THREAD

**Issue by WuNein** [microsoft/vscode-remote-release#7701]
Function well on version before 1.74.0

- VSCode Version: 1.74.0
- Local OS Version: windows10
- Remote OS Version: ubuntu 22.04 host, docker  nvcr.io/nvidia/pytorch:22.09-py3
- Remote Extension/Connection Type: SSH+Containers
- Logs:

Steps to Reproduce:

1. remote ssh + docker container
2. select/connect remote and container

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

```
Shell server terminated (code: 255, signal: null)

XSL ��ʽ(��)�ļ�����Ч��

node:child_process:925
    throw err;
    ^

Error: Command failed: wmic process where (commandline like "%ssh-askpass.bat%") get processid,parentprocessid /format:"%WINDIR%\System32\wbem\en-us\csv"
XSL ��ʽ(��)�ļ�����Ч��



    at checkExecSyncError (node:child_process:848:11)
    at Object.execSync (node:child_process:922:15)
    at Object.<anonymous> (node:electron/js2c/asar_bundle:5:12704)
    at Object.<anonymous> (c:\Users\WuNein\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\common\sshAskpass.js:5:808)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  status: 44210,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(27) [Uint8Array] [
       88,  83,  76,  32, 184, 241, 202,
      189,  40, 187, 242,  41, 206, 196,
      188, 254, 195, 251, 206, 222, 208,
      167, 161, 163,  13,  13,  10
    ]
  ],
  pid: 7192,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(27) [Uint8Array] [
     88,  83,  76,  32, 184, 241, 202,
    189,  40, 187, 242,  41, 206, 196,
    188, 254, 195, 251, 206, 222, 208,
    167, 161, 163,  13,  13,  10
  ]
}
Permission denied, please try again.
XSL ��ʽ(��)�ļ�����Ч��

node:child_process:925
    throw err;
    ^

Error: Command failed: wmic process where (commandline like "%ssh-askpass.bat%") get processid,parentprocessid /format:"%WINDIR%\System32\wbem\en-us\csv"
XSL ��ʽ(��)�ļ�����Ч��



    at checkExecSyncError (node:child_process:848:11)
    at Object.execSync (node:child_process:922:15)
    at Object.<anonymous> (node:electron/js2c/asar_bundle:5:12704)
    at Object.<anonymous> (c:\Users\WuNein\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\common\sshAskpass.js:5:808)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  status: 44210,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(27) [Uint8Array] [
       88,  83,  76,  32, 184, 241, 202,
      189,  40, 187, 242,  41, 206, 196,
      188, 254, 195, 251, 206, 222, 208,
      167, 161, 163,  13,  13,  10
    ]
  ],
  pid: 15540,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(27) [Uint8Array] [
     88,  83,  76,  32, 184, 241, 202,
    189,  40, 187, 242,  41, 206, 196,
    188, 254, 195, 251, 206, 222, 208,
    167, 161, 163,  13,  13,  10
  ]
}
Permission denied, please try again.
XSL ��ʽ(��)�ļ�����Ч��

node:child_process:925
    throw err;
    ^

Error: Command failed: wmic process where (commandline like "%ssh-askpass.bat%") get processid,parentprocessid /format:"%WINDIR%\System32\wbem\en-us\csv"
XSL ��ʽ(��)�ļ�����Ч��



    at checkExecSyncError (node:child_process:848:11)
    at Object.execSync (node:child_process:922:15)
    at Object.<anonymous> (node:electron/js2c/asar_bundle:5:12704)
    at Object.<anonymous> (c:\Users\WuNein\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\common\sshAskpass.js:5:808)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  status: 44210,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(27) [Uint8Array] [
       88,  83,  76,  32, 184, 241, 202,
      189,  40, 187, 242,  41, 206, 196,
      188, 254, 195, 251, 206, 222, 208,
      167, 161, 163,  13,  13,  10
    ]
  ],
  pid: 12360,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(27) [Uint8Array] [
     88,  83,  76,  32, 184, 241, 202,
    189,  40, 187, 242,  41, 206, 196,
    188, 254, 195, 251, 206, 222, 208,
    167, 161, 163,  13,  13,  10
  ]
}
wu@xxxxxx: Permission denied (publickey,password).
```

**Comment by aondra17** [comment]
Same problem with SSH + Attach To Running Container
(with "attach Shell" I can enter and everything works as expected)

**Comment by aondra17** [comment]
Problem (temporarily) solved! 
Rollback to previous version v0.262.3 of "Dev Containers" Extension

**Comment by WuNein** [comment]
> 

Interesting, it solved! But it still need proper fix
