### ISSUE TITLE
Shell server terminated (code:255)

### ISSUE THREAD

**Issue by chaeunl** [microsoft/vscode-remote-release#7707]
- VSCode Version: 1.74.0
- Local OS Version: Windows10 21H2
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: Containers
- Logs:
When I tried to connect a container in my remote server after got connected to the server using SSH, I got the error message (denoted as **ERROR 1**):
Shell server terminated (code: 255, signal: null) XSL ���� �Ǵ� ���� �̸��� �߸��Ǿ����ϴ�. node:child_process:925 throw err; ^ Error: Command failed: wmic process where (commandline like "%ssh-askpass.bat%") get processid,parentprocessid /format:"%WINDIR%\System32\wbem\en-us\csv" XSL ���� �Ǵ� ���� �̸��� �߸��Ǿ����ϴ�. at checkExecSyncError (node:child_process:848:11) at Object.execSync (node:child_process:922:15) at Object.<anonymous> (node:electron/js2c/asar_bundle:5:12704) at Object.<anonymous> (c:\Users\chaeu\.vscode\extensions\ms-vscode-remote.remote-containers-0.267.0\dist\common\sshAskpass.js:5:808) at Module._compile (node:internal/modules/cjs/loader:1165:14) at Module._extensions..js (node:internal/modules/cjs/loader:1220:10) at Module.load (node:internal/modules/cjs/loader:1035:32) at Module._load (node:internal/modules/cjs/loader:876:12) at c._load (node:electron/js2c/asar_bundle:5:13343) at Function.executeUser...

After press the refresh button in the container explorer bar, there is another error message (denoted as **ERROR 2**):
remote-containers.explorerTargetsRefresh: Shell server terminated (code: 255, signal: null) XSL ���� �Ǵ� ���� �̸��� �߸��Ǿ����ϴ�. node:child_process:925 throw err; ^ Error: Command failed: wmic process where (commandline like "%ssh-askpass.bat%") get processid,parentprocessid /format:"%WINDIR%\System32\wbem\en-us\csv" XSL ���� �Ǵ� ���� �̸��� �߸��Ǿ����ϴ�. at checkExecSyncError (node:child_process:848:11) at Object.execSync (node:child_process:922:15) at Object.<anonymous> (node:electron/js2c/asar_bundle:5:12704) at Object.<anonymous> (c:\Users\chaeu\.vscode\extensions\ms-vscode-remote.remote-containers-0.267.0\dist\common\sshAskpass.js:5:808) at Module._compile (node:internal/modules/cjs/loader:1165:14) at Module._extensions..js (node:internal/modules/cjs/loader:1220:10) at Module.load (node:internal/modules/cjs/loader:1035:32) at Module._load (node:internal/modules/cjs/loader:876:12) at c._load (node:electron/js2...

**Related issue: https://github.com/microsoft/vscode-remote-release/issues/7035**

Steps to Reproduce:

1. open vs code 
2. enter the password in the prompt to connect the server (SSH)
3. In the explorer bar, select "Containers" tab, I got **ERROR 1** message
4. In the explorer bar, press the refresh button and I got **ERROR 2** message

I also followed the instruction in the **Related issue**, especially follow the reply, https://github.com/microsoft/vscode-remote-release/issues/7035#issuecomment-1221387113, to use ssh-agent, but it does not work for me.

I got these error messages with no reasons. When I tried in the different env.(with my MacBook), there is no error.

Can you explain the steps to resolve the issue with some details?

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by Lua12138** [comment]
I had the same situation when I upgraded to Windows 11 22H2. Everything was fine before upgrading Windows11. (Windows 11 22H1 before upgrading)

**Comment by jounghoolee** [comment]
I have the same issue too

**Comment by Lua12138** [comment]
Is there any new news? I tried to reinstall the brand-new Windows 10 and Windows 11. As long as it is the 22H2 version, both Windows 10 and Windows 11 show the same prompt as above.

**Comment by jounghoolee** [comment]
I solved the problem by upgrading dev containers extension to pre-release version.
