### ISSUE TITLE
VS remote SSH extension is not working

### ISSUE THREAD

**Issue by DanShinde** [microsoft/vscode-remote-release#7712]
I cannot connect to remote ssh using VS code **remote SSH** extension.
Following is the log.
My remote ssh host is **Raspberry Pi** with Latest Raspberry pi OS.
I have my VS code on windows 10.
Please help.

`[23:53:17.982] Log Level: 2
[23:53:17.988] remote-ssh@0.94.0
[23:53:17.989] win32 x64
[23:53:17.997] SSH Resolver called for "ssh-remote+192.168.137.92", attempt 1
[23:53:17.997] "remote.SSH.useLocalServer": false
[23:53:17.998] "remote.SSH.showLoginTerminal": false
[23:53:17.999] "remote.SSH.remotePlatform": {}
[23:53:17.999] "remote.SSH.path": undefined
[23:53:17.999] "remote.SSH.configFile": undefined
[23:53:17.999] "remote.SSH.useFlock": true
[23:53:18.000] "remote.SSH.lockfilesInTmp": false
[23:53:18.000] "remote.SSH.localServerDownload": auto
[23:53:18.000] "remote.SSH.remoteServerListenOnSocket": false
[23:53:18.001] "remote.SSH.showLoginTerminal": false
[23:53:18.004] "remote.SSH.defaultExtensions": []
[23:53:18.004] "remote.SSH.loglevel": 2
[23:53:18.005] "remote.SSH.enableDynamicForwarding": true
[23:53:18.005] "remote.SSH.enableRemoteCommand": false
[23:53:18.006] "remote.SSH.serverPickPortsFromRange": {}
[23:53:18.006] "remote.SSH.serverInstallPath": {}
[23:53:18.015] SSH Resolver called for host: 192.168.137.92
[23:53:18.015] Setting up SSH remote "192.168.137.92"
[23:53:18.022] Using commit id "6261075646f055b99068d3688932416f2346dd3b" and quality "stable" for server
[23:53:18.030] Install and start server if needed
[23:53:23.235] Checking ssh with "ssh -V"
[23:53:23.297] > OpenSSH_for_Wi
[23:53:23.298] > ndows_8.1p1, LibreSSL 3.0.2

[23:53:23.303] Running script with connection command: ssh -T -D 52410 "192.168.137.92" bash
[23:53:23.306] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[23:53:23.570] > ]0;C:\WINDOWS\System32\cmd.exe
[23:53:23.570] Got some output, clearing connection timeout
[23:53:23.588] > Bad owner or permissions on C:\\Users\\myuser/.ssh/config
> The process tried to write to a nonexistent pipe.
> 
[23:53:24.862] "install" terminal command done
[23:53:24.863] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exeBad owner or permissions on C:\\Users\\myuser/.ssh/config
[23:53:24.863] Received install output: ]0;C:\WINDOWS\System32\cmd.exeBad owner or permissions on C:\\Users\\myuser/.ssh/config
[23:53:24.864] Failed to parse remote port from server output
[23:53:24.865] Resolver error: Error: 
	at g.Create (c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:583926)
	at t.handleInstallOutput (c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:582540)
	at t.tryInstall (c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:680469)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:642848
	at async t.withShowDetailsEvent (c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:646166)
	at async t.resolve (c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:643898)
	at async c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:723024
[23:53:24.875] ------
`

**Comment by eleanorjboyd** [comment]
Hello! Can you try this doc especially item 2? I see in the logs it says "Bad owner or permissions on C:\Users\myuser/.ssh/config" and therefore wanted to see if it might be a connection error. Here is the doc: `https://github.com/microsoft/vscode-remote-release/wiki/Debugging-for-Remote-SSH`

**Comment by DanShinde** [comment]
Thanks.
Solved this by changing the security settings of  "C:\Users\myuser/.ssh/config"file.
