### ISSUE TITLE
[Remote-SSH Bug]: Failed to parse remote port from server output

### ISSUE THREAD

**Issue by fisherxue** [microsoft/vscode-remote-release#7718]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Debugging Steps

- [X] I have followed these debugging steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting
- [X] My SSH command works from a local terminal
- [ ] I can connect using the Remote-SSH extension on VS Code when all other VS Code extensions are disabled

### ->

Attempting to connect from VS Code running on Windows to WSL environment within Windows on remote machine. SSH to the remote machine works, and WSL is launched from SSH by changing the default WSL shell. 

### Versions

- VS Code Version: 1.74.1
- Remote - SSH Version: 0.94.0
- Remote OS Version: Windows 11 
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      22621  0

### Expected Behavior

VS Code SSH should connect over SSH and open up in the WSL environment on remote.

### Steps To Reproduce

1. Use VS Code to SSH to remote Windows machine when default shell on remote Windows machine is set to bash.exe from WSL

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

[16:01:31.424] Log Level: 2
[16:01:31.428] remote-ssh@0.94.0
[16:01:31.428] win32 x64
[16:01:31.435] SSH Resolver called for "ssh-remote+home", attempt 1
[16:01:31.435] "remote.SSH.useLocalServer": false
[16:01:31.436] "remote.SSH.showLoginTerminal": true
[16:01:31.436] "remote.SSH.remotePlatform": {"home":"linux"}
[16:01:31.436] "remote.SSH.path": undefined
[16:01:31.436] "remote.SSH.configFile": undefined
[16:01:31.436] "remote.SSH.useFlock": true
[16:01:31.436] "remote.SSH.lockfilesInTmp": false
[16:01:31.437] "remote.SSH.localServerDownload": auto
[16:01:31.437] "remote.SSH.remoteServerListenOnSocket": false
[16:01:31.437] "remote.SSH.showLoginTerminal": true
[16:01:31.437] "remote.SSH.defaultExtensions": []
[16:01:31.437] "remote.SSH.loglevel": 2
[16:01:31.437] "remote.SSH.enableDynamicForwarding": true
[16:01:31.437] "remote.SSH.enableRemoteCommand": false
[16:01:31.437] "remote.SSH.serverPickPortsFromRange": {}
[16:01:31.437] "remote.SSH.serverInstallPath": {}
[16:01:31.441] SSH Resolver called for host: home
[16:01:31.441] Setting up SSH remote "home"
[16:01:31.446] Using commit id "1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a" and quality "stable" for server
[16:01:31.449] Install and start server if needed
[16:01:31.452] Checking ssh with "ssh -V"
[16:01:31.496] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[16:01:31.502] Running script with connection command: ssh -T -D 50855 home bash
[16:01:31.505] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[16:01:32.056] > Enter passphrase for key 'C:\Users\fishe/.ssh/id_ed25519':]0;C:\WINDOWS\System32\cmd.exe
[16:01:32.057] Got some output, clearing connection timeout
[16:01:32.080] > [8;28;102tEnter passphrase for key 'C:\Users\fishe/.ssh/id_ed25519':
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[16:01:35.235] > 
[16:01:35.554] > I
[16:01:35.563] > s
[16:01:36.864] "install" terminal command done
[16:01:36.865] Install terminal quit with output: Is
[16:01:36.865] Received install output: Is
[16:01:36.865] Failed to parse remote port from server output
[16:01:36.867] Resolver error: Error: 
	at g.Create (c:\Users\fishe\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:583926)
	at t.handleInstallOutput (c:\Users\fishe\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:582540)
	at t.tryInstall (c:\Users\fishe\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:680469)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\fishe\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:642848
	at async t.withShowDetailsEvent (c:\Users\fishe\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:646166)
	at async t.resolve (c:\Users\fishe\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:643898)
	at async c:\Users\fishe\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:723024
[16:01:36.874] ------

</p>
</details>

### Anything else?

When default ssh shell is set to bash.exe[New-ItemProperty -Path "HKLM:\SOFTWARE\OpenSSH" -Name DefaultShell -Value "C:\WINDOWS\System32\bash.exe" -PropertyType String -Force], why is VS Code still using cmd or Powershell when the remotePlatform is set to linux?

**Comment by joshspicer** [comment]
A lot has changed since this issue was created and it appears to be related to specific user configuration

Please feel free to open a new issue with a current copy of your logs (`> Remote-SSH: Show Log` in the command palette) if you'd like me to take a closer look at any current issues.
