### ISSUE TITLE
EACCES permission denied, failed to execute Jupyter notebook cell in the devcontainer

### ISSUE THREAD

**Issue by mirzaim** [microsoft/vscode-remote-release#7733]
failed to execute Jupyter notebook cell. The notebook's output is:
> Failed to start the Kernel. 
> Failed to start the Kernel 'Python 3.8.10'. 
> View Jupyter [log](command:jupyter.viewOutput) for further details. EACCES: permission denied, open '/tmp/kernel-v2-252DKt4rp4xtDme.json'

Dockerfile:
```
#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------
ARG IMAGE_TYPE
ARG TF_VERSION="latest"
FROM tensorflow/tensorflow:$TF_VERSION$IMAGE_TYPE-jupyter

# This Dockerfile adds a non-root user with sudo access. Update the “remoteUser” property in
# devcontainer.json to use it. More info: https://aka.ms/vscode-remote/containers/non-root-user.
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Options for common setup script - SHA updated on release
ARG INSTALL_ZSH="true"
ARG UPGRADE_PACKAGES="false"
ARG COMMON_SCRIPT_SOURCE="https://raw.githubusercontent.com/microsoft/vscode-dev-containers/main/script-library/common-debian.sh"
ARG COMMON_SCRIPT_SHA="dev-mode"

# Install needed packages and setup non-root user. Use a separate RUN statement to add your own dependencies.
RUN apt-get update \
    && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends curl ca-certificates 2>&1 \
    && curl -sSL  ${COMMON_SCRIPT_SOURCE} -o /tmp/common-setup.sh \
    && ([ "${COMMON_SCRIPT_SHA}" = "dev-mode" ] || (echo "${COMMON_SCRIPT_SHA} */tmp/common-setup.sh" | sha256sum -c -)) \
    && /bin/bash /tmp/common-setup.sh "${INSTALL_ZSH}" "${USERNAME}" "${USER_UID}" "${USER_GID}" "${UPGRADE_PACKAGES}" \
    && rm /tmp/common-setup.sh \
    #
    # *********************************************************************
    # * Uncomment this section to use RUN to install other dependencies.  *
    # * See https://aka.ms/vscode-remote/containers/dockerfile-run        *
    # *********************************************************************
    && apt-get -y install --no-install-recommends protobuf-compiler \
    #
    # Clean up
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
```

devcontainer.json:
```
{
	"name": "Tensorflow Dev Container",
	"build": {
		"dockerfile": "Dockerfile",
		"context": "../..",
		"args": {
			"TF_VERSION": "2.11.0",
			"IMAGE_TYPE": "-gpu"
		}
	},

	// Configure tool-specific properties.
	"customizations": {
		// Configure properties specific to VS Code.
		"vscode": {
			// Set *default* container specific settings.json values on container create.
			"settings": { 
				"python.defaultInterpreterPath": "/usr/local/bin/python",
				"python.linting.enabled": true,
				"python.linting.pylintEnabled": true,
				"python.formatting.autopep8Path": "/usr/local/py-utils/bin/autopep8",
				"python.formatting.blackPath": "/usr/local/py-utils/bin/black",
				"python.formatting.yapfPath": "/usr/local/py-utils/bin/yapf",
				"python.linting.banditPath": "/usr/local/py-utils/bin/bandit",
				"python.linting.flake8Path": "/usr/local/py-utils/bin/flake8",
				"python.linting.mypyPath": "/usr/local/py-utils/bin/mypy",
				"python.linting.pycodestylePath": "/usr/local/py-utils/bin/pycodestyle",
				"python.linting.pydocstylePath": "/usr/local/py-utils/bin/pydocstyle",
				"python.linting.pylintPath": "/usr/local/py-utils/bin/pylint",
				"files.watcherExclude": {
					"**/bazel-*/**": true
				},
				"search.exclude": {
					"**/bazel-*/**": true
				}
			},
			
			// Add the IDs of extensions you want installed when the container is created.
			"extensions": [
				"ms-python.python",
				"ms-python.vscode-pylance",
				"ms-toolsai.jupyter"
			]
		}
	},

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "pip3 install --user -r requirements.txt",

	"runArgs": [ 
		"--cap-add=SYS_PTRACE",
		"--gpus=all",
		"--security-opt",
		"seccomp=unconfined"
	],

	// Comment out to connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
	"remoteUser": "vscode",
	"features": {
		"ghcr.io/devcontainers/features/git:1": {}
	}
}
```

When I comment `"remoteUser": "vscode",` line in the devcontainer.json or change the ownership of the /tmp/ folder (`sudo chown -R vscode /tmp/`) the problem will solve. But the first solution runs the container with root permission, and in the second solution, each user has to run the command manually.
Is there a better solution that solves the problem?

**Comment by chrmarti** [comment]
Does it fail to create that file? Normally everyone can create files in `/tmp`. What do you get when running `ls -ld /tmp` inside the container?

**Comment by mirzaim** [comment]
Seems it can't create that file. This is the content of `/tmp/`. That file isn't there.
```
vscode ➜ /workspaces $ ll /tmp/
total 20
drwxr-xr-x 1 root root 4096 Dec 18 13:24 ./
drwxr-xr-x 1 root root 4096 Dec 18 13:35 ../
drwxr-xr-x 1 root root 4096 Dec 18 13:24 build-features/
```

But the log file shows that the problem is about _open systemcall_. These are the last lines of the log file. So, maybe the file is created but it can't be read and then deleted.
```
error 10:22:14.105: Error in execution (get message for cell) [r [Error]: 
	at new r (/home/vscode/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:17:33248)
	at Function.from (/home/vscode/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:17:33326)
	at t.Kernel.createJupyterSession (/home/vscode/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2035382)

Error: EACCES: permission denied, open '/tmp/kernel-v2-221uqRY09L1nuZS.json'] {
  category: 'unknown',
  originalException: [Error: EACCES: permission denied, open '/tmp/kernel-v2-221uqRY09L1nuZS.json'] {
    errno: -13,
    code: 'EACCES',
    syscall: 'open',
    path: '/tmp/kernel-v2-221uqRY09L1nuZS.json'
  }
}
```


The output of `ls -ld /tmp` is:
```
vscode ➜ /workspaces $ ls -ld /tmp
drwxr-xr-x 1 root root 4096 Dec 18 13:24 /tmp
```

**Comment by mirzaim** [comment]
Sorry. It was my fault.
I run a script after container creation that isn't mentioned here. It deletes and recreates `/tmp` folder. So the folder permission will be changed.
