### ISSUE TITLE
remote-SSH extension connecting to host failed with gibberish in output

### ISSUE THREAD

**Issue by LinTzuYu0925** [microsoft/vscode-remote-release#7773]
I'm trying to setup a ssh server using my win10 PC. After successfully install [ssh-server](https://learn.microsoft.com/zh-tw/windows-server/administration/openssh/openssh_install_firstuse) on my PC and ssh-client on my client laptop(win11). I tried using command line to connect, which has success. This ensure that my ssh-server and ssh-client have installed successfully and my username and password are both correct.

However, if I use [remote-SSH](https://code.visualstudio.com/docs/remote/remote-overview) on my laptop vscode to connect to my PC(using username/password certification), it failed with following output log :
```
[23:49:42.494] Got password response
[23:49:42.494] "install" wrote data to terminal: "**********"
[23:49:42.521] > 
[23:49:42.815] > powershell : �L�k���� 'powershell' ���J�O�_�� Cmdlet�B��ơB���O�ɩΥi����{�����W�١C���ˬd�W�٫��r�O�_���T�A�p�G�]�t
[23:49:42.826] > ��|���ܡA�нT�{��|�O�_���T�A�M��A�դ@���C
��� �u��:1 �r��:1
+ powershell
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (powershell:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 

[23:49:44.124] "install" terminal command done
[23:49:44.125] Install terminal quit with output:  
[23:49:44.126] Received install output:  
[23:49:44.129] Resolver error: Error: 
    at g.Create (c:\Users\lspss\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:583926)
    at c:\Users\lspss\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:581767
    at t.handleInstallOutput (c:\Users\lspss\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:582462)
    at t.tryInstall (c:\Users\lspss\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:680469)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async c:\Users\lspss\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:642848
    at async t.withShowDetailsEvent (c:\Users\lspss\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:646166)
    at async t.resolve (c:\Users\lspss\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:643898)
    at async c:\Users\lspss\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:723024
[23:49:44.138] -----
```
There are some gibberish after `powershell`. If I connect it otherwise(using my PC as client and laptop as server), it success : 
```
[23:56:27.929] Got password response
[23:56:27.929] "install" wrote data to terminal: "************"
[23:56:27.951] > 
[23:56:28.645] > Windows PowerShell
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Install the latest PowerShell for new features and improvements! https://aka.ms/
> PSWindowsPS C:\Users\lspss>
> PS C:\Users\lspss> $uuid="d68ebbafd913"
> PS C:\Users\lspss> "${uuid}: running"
> d68ebbafd913: running
> PS C:\Users\lspss> "d68ebbafd913: pauseLog"
> d68ebbafd913: pauseLog
```
I have tried reinstall my ssh-server on my PC. 
Any idea?

**Comment by eleanorjboyd** [comment]
Hello! Could you start by trying these steps in our troubleshooting guide? It will help provide some additional information if it still doesn't work. Thanks! https://github.com/microsoft/vscode-remote-release/wiki/Debugging-for-Remote-SSH
