### ISSUE TITLE
Remote ssh cannot be installed on the mac m1 platform

### ISSUE THREAD

**Issue by Jesn** [microsoft/vscode-remote-release#7776]
```
2022-12-29 13:59:56.839 [error] XHR failed,XHR failed: Error: XHR failed,XHR failed
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:88554
    at Array.reduce (<anonymous>)
    at u (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:88540)
    at Z.D (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:79894)
    at async Z.z (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:77428)
    at async Z.install (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:89:154420)
```

**Comment by eleanorjboyd** [comment]
Hello! Could you provide additional information like which machine is your local and which machine is your remote machine? Also could you check your PC system proxy settings, it is likely related to your settings and so I would check there first. Let me know if you find something or if it still isn't working, thanks!

**Comment by Jesn** [comment]
After testing, it is found that the agent is turned on. After the agent service is turned off, the plug-in can be installed
