### ISSUE TITLE
Resolver error:remote ssh could not establish connection

### ISSUE THREAD

**Issue by weever560** [microsoft/vscode-remote-release#7781]
at g.Create (d:\VSCode extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:583926)
    at t.handleInstallOutput (d:\VSCode extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:582540)
    at t.tryInstall (d:\VSCode extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:680469)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async d:\VSCode extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:642848
    at async t.withShowDetailsEvent (d:\VSCode extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:646166)
    at async t.resolve (d:\VSCode extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:643898)
    at async d:\VSCode extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:723024

**Comment by eleanorjboyd** [comment]
Hello! Can you please fill out a bug report using our remote-SSH bug template here: https://github.com/microsoft/vscode-remote-release/issues/new?assignees=eleanorjboyd&labels=ssh&template=a_remote_ssh_bug_form.yml&title=%5BRemote-SSH+Bug%5D%3A+. This will help you troubleshoot your error and if it is still not working, provide us with the information we need to offer help! Thanks

**Comment by eleanorjboyd** [comment]
closing issue in favor of creating a remote-ssh bug report.
