### ISSUE TITLE
Failed to find dev container configuration when opening folder in WSL

### ISSUE THREAD

**Issue by EngineerFaunce** [microsoft/vscode-remote-release#7784]
- VSCode Version: 1.74.2
- Local OS Version: Windows 10 Pro, Version 22H2, OS build 19045.2364
- Remote OS Version: Linux x64 5.15.79.1-microsoft-standard-WSL2
- Remote Extension/Connection Type: Connected to dev container via WSL

- Logs: [dev-container.log](https://github.com/microsoft/vscode-remote-release/files/10333592/dev-container.log)

Enabled extensions:
- Dev Containers
- Remote - SSH
- WSL
![image](https://user-images.githubusercontent.com/16312436/210280878-1d9409ed-a2ce-42b5-8686-b6e45eefddf4.png)

Steps to Reproduce:

1. Reopen WSL2 folder in Node.js & TypeScript dev container (Node.js version 18)
2. Open command palette (`Ctrl + Shift + P`) and select `Dev Containers: Show Container Log`
4. Open command palette again and select `Dev Containers: Configure Container Features...`
5. Log states `Failed to find configuration. Cannot configure container features.`

If I attempt the same steps while reopening a folder in the Windows file system, no error is thrown and I am able to select additional features:
![image](https://user-images.githubusercontent.com/16312436/210281138-33d5022b-bb7f-4fc5-90e1-7fa6786dfc63.png)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by Supportic** [comment]
For me I had troubles when:
1. Trying to add config files in a opened workspace. Trying to add config files when you open up just the directory worked.
```
[error] EntryNotADirectory (FileSystemError): Error: ENOTDIR: not a directory, stat '/home/<user>/dev/test/workspace.code-workspace/.devcontainer/devcontainer.json'
	at Jt.c (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:25943)
	at Object.stat (c:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:24413)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Object.isFile (c:\Users\<user>\.vscode\extensions\ms-vscode-remote.remote-containers-0.262.3\dist\extension\extension.js:399:36278)
	at async c:\Users\<user>\.vscode\extensions\ms-vscode-remote.remote-containers-0.262.3\dist\extension\extension.js:401:10584 remote-containers.createDevContainerFile {"value":"ms-vscode-remote.remote-containers","c":"ms-vscode-remote.remote-containers"}
```
2. When using a compose.yml file like described in the new docker compose specification. Switching to docker-compose.yml helped in this case

**Comment by chrmarti** [comment]
@Supportic That is fixed with https://github.com/microsoft/vscode-remote-release/issues/7813 (not released in a new version yet).
