### ISSUE TITLE
Dev Containers doesn't properly handle git submodules

### ISSUE THREAD

**Issue by a1291762** [microsoft/vscode-remote-release#7826]
- VSCode Version: 1.74.3
- Local OS Version: Ubuntu 20.04
- Remote OS Version: n/a
- Remote Extension/Connection Type: Containers

- Logs:

```
2023-01-11 13:50:13.941 [error] EntryNotADirectory (FileSystemError): Error: ENOTDIR: not a directory, stat '/path/to/repo/.git/config'
	at Jt.c (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:25943)
	at Object.stat (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:24413)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Object.isFile (/home/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/extension/extension.js:254:33101)
	at async yd (/home/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/extension/extension.js:62:312)
	at async Fk (/home/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/extension/extension.js:62:1653)
	at async WE (/home/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/extension/extension.js:237:5384)
	at async bi (/home/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/extension/extension.js:237:5301)
	at async /home/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/extension/extension.js:254:26638
	at async Promise.all (index 0)
	at async Ux (/home/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/extension/extension.js:254:26559)
	at async Xx (/home/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/extension/extension.js:256:1038)
	at async e$ (/home/user/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/extension/extension.js:256:1533)
	at async s.h (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:107614) remote-containers.addExtensionToConfig {"value":"ms-vscode-remote.remote-containers","c":"ms-vscode-remote.remote-containers"}
```

Steps to Reproduce:

1. Open a folder in VSCode that is a git submodule.

Because the folder is a git submodule, .git is a file that points to a directory in the parent repo's .git folder.

```
gitdir: ../.git/modules/repo
```

However, Dev Containers tries and fails to access .git/config, so it's clearly not handling this correctly.

Apart from noise in the log, this prevents the prompt to open the folder in a Dev Container. I don't know what else may be impacted...

![image](https://user-images.githubusercontent.com/327162/211715658-401ca391-6f1c-4ee4-9f3e-af93e7f7c1d3.png)

**Comment by a1291762** [comment]
FWIW: git rev-parse --git-dir can be used to find the actual location of git...

```
/path/to/repo> git rev-parse --git-dir
/home/user/git/parent_repo/.git/modules/repo
```
