### ISSUE TITLE
Failed to process feature

### ISSUE THREAD

**Issue by pieterv-icloud-com** [microsoft/vscode-remote-release#7830]
- VSCode Version: 1.74.3 (Universal)
- Local OS Version: Darwin arm64 22.2.0
- Remote OS Version: debian bullseye
- Remote Extension/Connection Type: Containers

Looks like there is an auth issue with github at the moment processing features.

- Logs:
```
(node:39317) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Plugin) --trace-deprecation ...` to show where the warning was created)
[9 ms] @devcontainers/cli 0.25.2. Node.js v16.14.2. darwin 22.2.0 arm64.
[9 ms] Start: Run: docker buildx version
[163 ms] Stop (154 ms): Run: docker buildx version
[164 ms] github.com/docker/buildx v0.9.1 ed00243a0ce2a0aee75311b06e32d33b44729689
[164 ms]
[167 ms] Start: Run: docker inspect --type image mcr.microsoft.com/vscode/devcontainers/base:0-bullseye
[213 ms] Stop (46 ms): Run: docker inspect --type image mcr.microsoft.com/vscode/devcontainers/base:0-bullseye
[214 ms] local container features stored at: /Users/pieter.vandermerwe/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/node_modules/vscode-dev-containers/container-features
[215 ms] Start: Run: tar --no-same-owner -x -f -
[224 ms] Stop (9 ms): Run: tar --no-same-owner -x -f -
[224 ms] workspace root: /Users/pieter.vandermerwe/repos/roslyn-observability
[227 ms] Loaded /Users/pieter.vandermerwe/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/node_modules/vscode-dev-containers/container-features/devcontainer-features.json, which declares 25 features and does not contain explicit source info.
[227 ms] --- Processing User Features ----
[227 ms] * Processing feature: ghcr.io/devcontainers/features/aws-cli:1
[227 ms] > input: ghcr.io/devcontainers/features/aws-cli:1
[227 ms] >
[227 ms] > resource: ghcr.io/devcontainers/features/aws-cli
[227 ms] > id: aws-cli
[228 ms] > version: 1
[228 ms] > owner: devcontainers
[228 ms] > namespace: devcontainers/features
[228 ms] > registry: ghcr.io
[228 ms] > path: devcontainers/features/aws-cli
[228 ms] manifest url: https://ghcr.io/v2/devcontainers/features/aws-cli/manifests/1
[228 ms] url: https://ghcr.io/token?scope=repository:devcontainers/features/aws-cli:pull&service=ghcr.io
[853 ms] HTTP request failed with status code 403: : Forbidden
[854 ms] Failed to get registry auth token with error: Error: HTTP 403: Forbidden
[1429 ms] (!) WARNING: Falling back to deprecated GitHub Release syntax. See https://github.com/devcontainers/spec/blob/main/proposals/devcontainer-features.md#referencing-a-feature for updated specification.
[1430 ms] Github feature.
[1430 ms] Could not resolve Feature 'ghcr.io/devcontainers/features/aws-cli:1'.  Ensure the Feature is published and accessible from your current environment.
Error: Failed to process feature ghcr.io/devcontainers/features/aws-cli:1
    at Pse (/Users/pieter.vandermerwe/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1805:3150)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Sm (/Users/pieter.vandermerwe/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1805:2294)
    at async Jf (/Users/pieter.vandermerwe/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1807:1415)
    at async Doe (/Users/pieter.vandermerwe/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1893:2580)
    at async EF (/Users/pieter.vandermerwe/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1893:1978)
    at async fue (/Users/pieter.vandermerwe/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:2020:19430)
    at async lue (/Users/pieter.vandermerwe/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:2020:17550)
{"outcome":"error","message":"Failed to process feature ghcr.io/devcontainers/features/aws-cli:1","description":"An error occurred building the container."}
```

Steps to Reproduce:

1. Run `devcontainer build . --verbose` on a devcontainer with features.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Could you update to the latest Dev Containers extension (0.270.0-pre-release at the moment) and retry? /cc @samruddhikhandale @joshspicer

**Comment by pieterv-icloud-com** [comment]
This is pretty embarrassing, turns out my github token expired and I had to create a new one.

**Comment by peter-job** [comment]
> This is pretty embarrassing, turns out my github token expired and I had to create a new one.

@pieterv-icloud-com I'm having the same issue here, could you explain what you did with the github token to authenticate?

**Comment by joshspicer** [comment]
The CLI's will use a `GITHUB_TOKEN` environment variable is one is available in your environment, or the token saved in your `~/.docker/config.json` file.  If one is not found, it will attempt to exchange with the `ghcr.io` token endpoint for an anonymous registry token (assuming the Feature/Template is set as public, which is true for all of the Features published by the `devcontainers` org.

Please use this code snippet as a reference for the order of precedence: https://github.com/devcontainers/cli/blob/03e01c421c02640c027b442d87aaf77e8401c84f/src/spec-configuration/httpOCIRegistry.ts#L125-L164

@peter-job you may want to first ensure you don't have a stale `GITHUB_TOKEN` env variable set.  If that's not the case, doing a `echo $CR_GITHUB_PAT | docker login ghcr.io -u USERNAME --password-stdin` with a properly scoped GitHub PAT might do the trick! [(docs)](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-with-a-personal-access-token-classic)

**Comment by peter-job** [comment]
@joshspicer I did have an old GITHUB_TOKEN environment variable set, clearing it fixed the problem. I really appreciate the explanation you gave in your comment. I was stuck on why I couldn't pull the public features from ghcr.io even after providing docker with a fresh PAT. It makes sense now, thank you!
