### ISSUE TITLE
[Remote-SSH Bug]: Can not remove an SSH Connection

### ISSUE THREAD

**Issue by ramikilany** [microsoft/vscode-remote-release#7835]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Debugging Steps

- [X] I have followed these debugging steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting
- [ ] My SSH command works from a local terminal
- [ ] I can connect using the Remote-SSH extension on VS Code when all other VS Code extensions are disabled

### Versions

- VS Code Version: 1.74.3
- Remote OS Version: Debian 11 latest updates

### Expected Behavior

I have 3 remote ssh connections and works fine. But I suddenly found a fourth connection that it was not setup by me.
When I go to ssh config file I see also the only 3 connections without showing the fourth one.

I tried to remote it, I had the message "Could not establish connection to "final all": Could not resolve hostname."

### Remote-SSH Log

[16:39:24.586] Log Level: 2
[16:39:24.591] remote-ssh@0.94.0
[16:39:24.591] linux x64
[16:39:24.600] SSH Resolver called for "ssh-remote+final all", attempt 1
[16:39:24.601] "remote.SSH.useLocalServer": true
[16:39:24.601] "remote.SSH.path": undefined
[16:39:24.602] "remote.SSH.configFile": undefined
[16:39:24.602] "remote.SSH.useFlock": true
[16:39:24.602] "remote.SSH.lockfilesInTmp": false
[16:39:24.602] "remote.SSH.localServerDownload": auto
[16:39:24.603] "remote.SSH.remoteServerListenOnSocket": false
[16:39:24.603] "remote.SSH.showLoginTerminal": false
[16:39:24.603] "remote.SSH.defaultExtensions": []
[16:39:24.603] "remote.SSH.loglevel": 2
[16:39:24.603] "remote.SSH.enableDynamicForwarding": true
[16:39:24.604] "remote.SSH.enableRemoteCommand": false
[16:39:24.604] "remote.SSH.serverPickPortsFromRange": {}
[16:39:24.604] "remote.SSH.serverInstallPath": {}
[16:39:24.612] SSH Resolver called for host: final all
[16:39:24.612] Setting up SSH remote "final all"
[16:39:24.618] Acquiring local install lock: /tmp/vscode-remote-ssh-693ed714-install.lock
[16:39:24.619] Looking for existing server data file at /home/rami/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-693ed714-97dec172d3256f8ca4bfb2143f3f76b503ca0534-0.94.0/data.json
[16:39:24.620] Using commit id "97dec172d3256f8ca4bfb2143f3f76b503ca0534" and quality "stable" for server
[16:39:24.624] Install and start server if needed
[16:39:24.631] PATH: /home/rami/.local/bin:/home/rami/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/rami/.dotnet/tools
[16:39:24.631] Checking ssh with "ssh -V"
[16:39:24.641] > OpenSSH_8.8p1, OpenSSL 3.0.5 5 Jul 2022

[16:39:24.645] askpass server listening on /run/user/1000/vscode-ssh-askpass-53dce79f0a18d52e2fa2538b2f4350a95de9f5dd.sock
[16:39:24.646] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-19526007de582cc660e7d729e53c4d0aeac36f91.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","45645","-o","ConnectTimeout=15","final all"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/rami/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-693ed714-97dec172d3256f8ca4bfb2143f3f76b503ca0534-0.94.0/data.json"}
[16:39:24.646] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","SHELL":"/bin/bash","DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-53dce79f0a18d52e2fa2538b2f4350a95de9f5dd.sock"}
[16:39:24.652] Spawned 41536
[16:39:24.792] > local-server-1> Running ssh connection command: "-v -T -D 45645 -o ConnectTimeout=15 final all"
[16:39:24.796] > local-server-1> Spawned ssh, pid=41544
[16:39:24.800] stderr> OpenSSH_8.8p1, OpenSSL 3.0.5 5 Jul 2022
[16:39:28.583] stderr> ssh: Could not resolve hostname final all: Name or service not known
[16:39:28.584] > local-server-1> ssh child died, shutting down
[16:39:28.591] Local server exit: 0
[16:39:28.592] Received install output: local-server-1> Running ssh connection command: "-v -T -D 45645 -o ConnectTimeout=15 final all"
local-server-1> Spawned ssh, pid=41544
OpenSSH_8.8p1, OpenSSL 3.0.5 5 Jul 2022
ssh: Could not resolve hostname final all: Name or service not known
local-server-1> ssh child died, shutting down

[16:39:28.594] Resolver error: Error: Could not resolve hostname
	at g.Offline (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:583977)
	at /home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:581360
	at t.handleInstallOutput (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:581728)
	at Object.e [as tryInstallWithLocalServer] (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:623191)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:642446
	at async t.withShowDetailsEvent (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:646166)
	at async /home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:621663
	at async T (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:618169)
	at async t.resolveWithLocalServer (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:621278)
	at async t.resolve (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:643774)
	at async /home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:723024
[16:39:28.604] ------

[16:39:28.697] ------

[16:39:28.697] SSH Resolver called for "ssh-remote+final all", attempt 2, (Reconnection)
[16:39:28.699] SSH Resolver called for host: final all
[16:39:28.699] Setting up SSH remote "final all"
[16:39:28.700] Acquiring local install lock: /tmp/vscode-remote-ssh-693ed714-install.lock
[16:39:28.701] Looking for existing server data file at /home/rami/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-693ed714-97dec172d3256f8ca4bfb2143f3f76b503ca0534-0.94.0/data.json
[16:39:28.701] Using commit id "97dec172d3256f8ca4bfb2143f3f76b503ca0534" and quality "stable" for server
[16:39:28.704] Install and start server if needed
[16:39:28.714] askpass server listening on /run/user/1000/vscode-ssh-askpass-e0e7e3f58ce3ba93fda84f7dea912bbaa65d672a.sock
[16:39:28.715] Spawning local server with {"serverId":2,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-884329168dc42fdff689176f57363b806e8f2e1e.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","38057","-o","ConnectTimeout=15","final all"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/rami/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-693ed714-97dec172d3256f8ca4bfb2143f3f76b503ca0534-0.94.0/data.json"}
[16:39:28.715] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","SHELL":"/bin/bash","DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-e0e7e3f58ce3ba93fda84f7dea912bbaa65d672a.sock"}
[16:39:28.719] Spawned 41547
[16:39:28.881] > local-server-2> Running ssh connection command: "-v -T -D 38057 -o ConnectTimeout=15 final all"
[16:39:28.887] > local-server-2> Spawned ssh, pid=41555
[16:39:28.892] stderr> OpenSSH_8.8p1, OpenSSL 3.0.5 5 Jul 2022
[16:39:32.833] stderr> ssh: Could not resolve hostname final all: Name or service not known
[16:39:32.833] > local-server-2> ssh child died, shutting down
[16:39:32.840] Local server exit: 0
[16:39:32.840] Received install output: local-server-2> Running ssh connection command: "-v -T -D 38057 -o ConnectTimeout=15 final all"
local-server-2> Spawned ssh, pid=41555
OpenSSH_8.8p1, OpenSSL 3.0.5 5 Jul 2022
ssh: Could not resolve hostname final all: Name or service not known
local-server-2> ssh child died, shutting down

[16:39:32.841] Resolver error: Error: Could not resolve hostname
	at g.Offline (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:583977)
	at /home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:581360
	at t.handleInstallOutput (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:581728)
	at Object.e [as tryInstallWithLocalServer] (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:623191)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:642446
	at async t.withShowDetailsEvent (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:646166)
	at async /home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:621663
	at async T (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:618169)
	at async t.resolveWithLocalServer (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:621278)
	at async t.resolve (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:643774)
	at async /home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:723024
[16:39:32.846] ------

[16:39:32.854] ------

[16:39:32.854] SSH Resolver called for "ssh-remote+final all", attempt 3, (Reconnection)
[16:39:32.857] SSH Resolver called for host: final all
[16:39:32.857] Setting up SSH remote "final all"
[16:39:32.858] Acquiring local install lock: /tmp/vscode-remote-ssh-693ed714-install.lock
[16:39:32.858] Looking for existing server data file at /home/rami/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-693ed714-97dec172d3256f8ca4bfb2143f3f76b503ca0534-0.94.0/data.json
[16:39:32.859] Using commit id "97dec172d3256f8ca4bfb2143f3f76b503ca0534" and quality "stable" for server
[16:39:32.862] Install and start server if needed
[16:39:32.871] askpass server listening on /run/user/1000/vscode-ssh-askpass-346a23451570cba9a80b38119d9e1663302255fa.sock
[16:39:32.871] Spawning local server with {"serverId":3,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-0053c77e667c0fb21b174e57555bdf7bb37af160.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","36389","-o","ConnectTimeout=15","final all"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/rami/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-693ed714-97dec172d3256f8ca4bfb2143f3f76b503ca0534-0.94.0/data.json"}
[16:39:32.872] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","SHELL":"/bin/bash","DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-346a23451570cba9a80b38119d9e1663302255fa.sock"}
[16:39:32.879] Spawned 41557
[16:39:33.039] > local-server-3> Running ssh connection command: "-v -T -D 36389 -o ConnectTimeout=15 final all"
[16:39:33.044] > local-server-3> Spawned ssh, pid=41565
[16:39:33.048] stderr> OpenSSH_8.8p1, OpenSSL 3.0.5 5 Jul 2022
[16:39:36.833] stderr> ssh: Could not resolve hostname final all: Name or service not known
[16:39:36.833] > local-server-3> ssh child died, shutting down
[16:39:36.839] Local server exit: 0
[16:39:36.840] Received install output: local-server-3> Running ssh connection command: "-v -T -D 36389 -o ConnectTimeout=15 final all"
local-server-3> Spawned ssh, pid=41565
OpenSSH_8.8p1, OpenSSL 3.0.5 5 Jul 2022
ssh: Could not resolve hostname final all: Name or service not known
local-server-3> ssh child died, shutting down

[16:39:36.841] Resolver error: Error: Could not resolve hostname
	at g.Offline (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:583977)
	at /home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:581360
	at t.handleInstallOutput (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:581728)
	at Object.e [as tryInstallWithLocalServer] (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:623191)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:642446
	at async t.withShowDetailsEvent (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:646166)
	at async /home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:621663
	at async T (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:618169)
	at async t.resolveWithLocalServer (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:621278)
	at async t.resolve (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:643774)
	at async /home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:723024
[16:39:36.845] ------

[16:39:36.846] ------

[16:39:36.846] SSH Resolver called for "ssh-remote+final all", attempt 4, (Reconnection)
[16:39:36.848] SSH Resolver called for host: final all
[16:39:36.848] Setting up SSH remote "final all"
[16:39:36.849] Acquiring local install lock: /tmp/vscode-remote-ssh-693ed714-install.lock
[16:39:36.850] Looking for existing server data file at /home/rami/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-693ed714-97dec172d3256f8ca4bfb2143f3f76b503ca0534-0.94.0/data.json
[16:39:36.850] Using commit id "97dec172d3256f8ca4bfb2143f3f76b503ca0534" and quality "stable" for server
[16:39:36.852] Install and start server if needed
[16:39:36.858] askpass server listening on /run/user/1000/vscode-ssh-askpass-0c43e694ab3df7e19bb2499b58ca7258b2410894.sock
[16:39:36.858] Spawning local server with {"serverId":4,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-f8a62e52acaa11544dc63b2b950daa9fb6f97dec.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","41597","-o","ConnectTimeout=15","final all"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/rami/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-693ed714-97dec172d3256f8ca4bfb2143f3f76b503ca0534-0.94.0/data.json"}
[16:39:36.858] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","SHELL":"/bin/bash","DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-0c43e694ab3df7e19bb2499b58ca7258b2410894.sock"}
[16:39:36.865] Spawned 41571
[16:39:37.008] > local-server-4> Running ssh connection command: "-v -T -D 41597 -o ConnectTimeout=15 final all"
[16:39:37.013] > local-server-4> Spawned ssh, pid=41579
[16:39:37.018] stderr> OpenSSH_8.8p1, OpenSSL 3.0.5 5 Jul 2022
[16:39:40.833] stderr> ssh: Could not resolve hostname final all: Name or service not known
[16:39:40.834] > local-server-4> ssh child died, shutting down
[16:39:40.843] Local server exit: 0
[16:39:40.844] Received install output: local-server-4> Running ssh connection command: "-v -T -D 41597 -o ConnectTimeout=15 final all"
local-server-4> Spawned ssh, pid=41579
OpenSSH_8.8p1, OpenSSL 3.0.5 5 Jul 2022
ssh: Could not resolve hostname final all: Name or service not known
local-server-4> ssh child died, shutting down

[16:39:40.846] Resolver error: Error: Could not resolve hostname
	at g.Offline (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:583977)
	at /home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:581360
	at t.handleInstallOutput (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:581728)
	at Object.e [as tryInstallWithLocalServer] (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:623191)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:642446
	at async t.withShowDetailsEvent (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:646166)
	at async /home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:621663
	at async T (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:618169)
	at async t.resolveWithLocalServer (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:621278)
	at async t.resolve (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:643774)
	at async /home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:723024
[16:39:40.855] ------

[16:39:40.902] ------

[16:39:40.902] SSH Resolver called for "ssh-remote+final all", attempt 5, (Reconnection)
[16:39:40.907] SSH Resolver called for host: final all
[16:39:40.907] Setting up SSH remote "final all"
[16:39:40.909] Acquiring local install lock: /tmp/vscode-remote-ssh-693ed714-install.lock
[16:39:40.909] Looking for existing server data file at /home/rami/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-693ed714-97dec172d3256f8ca4bfb2143f3f76b503ca0534-0.94.0/data.json
[16:39:40.910] Using commit id "97dec172d3256f8ca4bfb2143f3f76b503ca0534" and quality "stable" for server
[16:39:40.915] Install and start server if needed
[16:39:40.922] askpass server listening on /run/user/1000/vscode-ssh-askpass-549c6ef4670eca5af07a69a6865546cc0f269bce.sock
[16:39:40.922] Spawning local server with {"serverId":5,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-3e7f2e2f5b3b9678388b11113c1a5097e2dd31f3.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","39095","-o","ConnectTimeout=15","final all"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/rami/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-693ed714-97dec172d3256f8ca4bfb2143f3f76b503ca0534-0.94.0/data.json"}
[16:39:40.922] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","SHELL":"/bin/bash","DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-549c6ef4670eca5af07a69a6865546cc0f269bce.sock"}
[16:39:40.928] Spawned 41582
[16:39:41.143] > local-server-5> Running ssh connection command: "-v -T -D 39095 -o ConnectTimeout=15 final all"
[16:39:41.157] > local-server-5> Spawned ssh, pid=41590
[16:39:41.165] stderr> OpenSSH_8.8p1, OpenSSL 3.0.5 5 Jul 2022
[16:39:45.083] stderr> ssh: Could not resolve hostname final all: Name or service not known
[16:39:45.084] > local-server-5> ssh child died, shutting down
[16:39:45.090] Local server exit: 0
[16:39:45.091] Received install output: local-server-5> Running ssh connection command: "-v -T -D 39095 -o ConnectTimeout=15 final all"
local-server-5> Spawned ssh, pid=41590
OpenSSH_8.8p1, OpenSSL 3.0.5 5 Jul 2022
ssh: Could not resolve hostname final all: Name or service not known
local-server-5> ssh child died, shutting down

[16:39:45.092] Resolver error: Error: Could not resolve hostname
	at g.Offline (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:583977)
	at /home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:581360
	at t.handleInstallOutput (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:581728)
	at Object.e [as tryInstallWithLocalServer] (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:623191)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:642446
	at async t.withShowDetailsEvent (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:646166)
	at async /home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:621663
	at async T (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:618169)
	at async t.resolveWithLocalServer (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:621278)
	at async t.resolve (/home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:643774)
	at async /home/rami/.vscode/extensions/ms-vscode-remote.remote-ssh-0.94.0/out/extension.js:1:723024
[16:39:45.097] ------

**Comment by eleanorjboyd** [comment]
Hello! Where did you find this 4th connection? Is it in the remote-explorer on vscode? Do you have a config file set up? If so can you check that there is no additional host which exists there that you didn't realize.

**Comment by ramikilany** [comment]
I found the 4th connection in the remote explorer. And I have a config file in /home/rami/.ssh/config and here its content:

Host 5.161.103.41
    HostName 5.161.103.41
    User brian

Host rds.mrimath.com
    HostName 5.161.45.208
    User root
  
Host www.mrimath.com
    HostName 127.0.0.1
    Port 3322
    User rami

**Comment by ekremparlak** [comment]
Same thing happened to me on Fedora 37
Looks like there is a file at /etc/ssh/ssh_config.d/50-redhat.conf
````
# The options here are in the "Match final block" to be applied as the last
# options and could be potentially overwritten by the user configuration
Match final all
	# Follow system-wide Crypto Policy, if defined:
	Include /etc/crypto-policies/back-ends/openssh.config

	GSSAPIAuthentication yes

# If this option is set to yes then remote X11 clients will have full access
# to the original X11 display. As virtually no X11 client supports the untrusted
# mode correctly we set this to yes.
	ForwardX11Trusted yes

# Uncomment this if you want to use .local domain
# Host *.local
````
I remove the file for debug and the "final all" remote was removed from the list.

**Comment by ramikilany** [comment]
> 

It works as you mention.

Thank you for your support.
