### ISSUE TITLE
[Remote-SSH Bug]: Failed to Create hard link

### ISSUE THREAD

**Issue by elibroftw** [microsoft/vscode-remote-release#7836]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Debugging Steps

- [X] I have followed these debugging steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting
- [X] My SSH command works from a local terminal
- [ ] I can connect using the Remote-SSH extension on VS Code when all other VS Code extensions are disabled

### ->

I tried connecting, vscode got hung up deleting a folder, so I renamed the folder (from an SSH terminal) and restarted vscode. Then it came erroring out and this is what I got. 

 ln: failed to create hard link '/u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534': File exists

### Versions

- VS Code Version: 1.74.3
- Remote OS Version: Ubuntu 18.04

### Expected Behavior

Should not fail because of a ln failure due to file already existing

### Steps To Reproduce

Connect again after many months.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[11:20:16.972] Log Level: 2
[11:20:16.973] remote-ssh@0.94.0
[11:20:16.973] win32 x64
[11:20:16.974] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a227557617465726c6f6f227d", attempt 1
[11:20:16.975] "remote.SSH.useLocalServer": false
[11:20:16.975] "remote.SSH.showLoginTerminal": false
[11:20:16.975] "remote.SSH.remotePlatform": {"167.99.191.206":"linux","uWaterloo":"linux","lenerva.com":"linux","xmr.node.lenerva.com":"linux"}
[11:20:16.976] "remote.SSH.path": undefined
[11:20:16.976] "remote.SSH.configFile": undefined
[11:20:16.976] "remote.SSH.useFlock": false
[11:20:16.976] "remote.SSH.lockfilesInTmp": false
[11:20:16.976] "remote.SSH.localServerDownload": auto
[11:20:16.977] "remote.SSH.remoteServerListenOnSocket": false
[11:20:16.977] "remote.SSH.showLoginTerminal": false
[11:20:16.977] "remote.SSH.defaultExtensions": []
[11:20:16.977] "remote.SSH.loglevel": 2
[11:20:16.977] "remote.SSH.enableDynamicForwarding": true
[11:20:16.977] "remote.SSH.enableRemoteCommand": false
[11:20:16.978] "remote.SSH.serverPickPortsFromRange": {}
[11:20:16.978] "remote.SSH.serverInstallPath": {}
[11:20:16.980] SSH Resolver called for host: uWaterloo
[11:20:16.980] Setting up SSH remote "uWaterloo"
[11:20:16.986] Using commit id "97dec172d3256f8ca4bfb2143f3f76b503ca0534" and quality "stable" for server
[11:20:16.991] Install and start server if needed
[11:20:16.993] Checking ssh with "ssh -V"
[11:20:17.031] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[11:20:17.034] Running script with connection command: ssh -T -D 6606 "uWaterloo" bash
[11:20:17.036] Terminal shell path: C:\Windows\System32\cmd.exe
[11:20:31.341] > 21a7bb3da199: running
> ]0;C:\Windows\System32\cmd.exe
[11:20:31.341] Got some output, clearing connection timeout
[11:20:31.471] > Acquiring lock on /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534
[11:20:31.491] > \ln /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534.target /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534
> Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> 21a7bb3da199: start
> exitCode==24==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/32480==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 21a7bb3da199: end
> ln: failed to create hard link '/u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534': File exists
[11:20:31.491] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/32480==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[11:20:31.492] Server installation process already in progress - waiting and retrying
[11:20:32.506] Running script with connection command: ssh -T -D 6606 "uWaterloo" bash
[11:20:32.508] Terminal shell path: C:\Windows\System32\cmd.exe
[11:20:32.954] "install" terminal command done
[11:20:32.955] Install terminal quit with output: 
[11:20:49.521] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (c:\Users\maste\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:584052)
	at Timeout._onTimeout (c:\Users\maste\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:679189)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[11:20:49.524] ------




[11:20:49.585] ------




[11:20:49.585] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a227557617465726c6f6f227d", attempt 2, (Reconnection)
[11:20:49.586] SSH Resolver called for host: uWaterloo
[11:20:49.586] Setting up SSH remote "uWaterloo"
[11:20:49.590] Using commit id "97dec172d3256f8ca4bfb2143f3f76b503ca0534" and quality "stable" for server
[11:20:49.598] Install and start server if needed
[11:20:49.600] Running script with connection command: ssh -T -D 6615 "uWaterloo" bash
[11:20:49.602] Terminal shell path: C:\Windows\System32\cmd.exe
[11:21:06.616] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (c:\Users\maste\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:584052)
	at Timeout._onTimeout (c:\Users\maste\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:679189)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[11:21:06.619] ------




[11:21:06.660] ------




[11:21:06.660] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a227557617465726c6f6f227d", attempt 3, (Reconnection)
[11:21:06.662] SSH Resolver called for host: uWaterloo
[11:21:06.662] Setting up SSH remote "uWaterloo"
[11:21:06.665] Using commit id "97dec172d3256f8ca4bfb2143f3f76b503ca0534" and quality "stable" for server
[11:21:06.668] Install and start server if needed
[11:21:06.672] Running script with connection command: ssh -T -D 6617 "uWaterloo" bash
[11:21:06.673] Terminal shell path: C:\Windows\System32\cmd.exe
[11:21:17.398] > 21a7bb3da199: running
> ]0;C:\Windows\System32\cmd.exe
[11:21:17.398] > 89e8e5902604: running
> ]0;C:\Windows\System32\cmd.exe
[11:21:17.399] Got some output, clearing connection timeout
[11:21:17.399] Got some output, clearing connection timeout
[11:21:17.417] > [8;13;245t21a7bb3da199: running
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[11:21:17.454] > Acquiring lock on /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534
[11:21:17.458] > Acquiring lock on /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534
> \ln /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534.target /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534
> ln: failed to create hard link '/u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534'Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> 21a7bb3da199: start
> exitCode==24==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/32480==
> : File exists
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 21a7bb3da199: end
[11:21:17.459] > \ln /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534.target /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534
> ln: failed to create hard link '/u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534': File exists
> Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> 89e8e5902604: start
> exitCode==24==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/32480==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 89e8e5902604: end
[11:21:17.459] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/32480==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[11:21:17.459] Server installation process already in progress - waiting and retrying
[11:21:18.472] Running script with connection command: ssh -T -D 6617 "uWaterloo" bash
[11:21:18.474] Terminal shell path: C:\Windows\System32\cmd.exe
[11:21:18.906] "install" terminal command done
[11:21:18.907] Install terminal quit with output: 
[11:21:19.209] "install" terminal command done
[11:21:19.209] Install terminal quit with output: 
[11:21:35.476] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (c:\Users\maste\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:584052)
	at Timeout._onTimeout (c:\Users\maste\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:679189)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[11:21:35.478] ------




[11:21:35.515] ------




[11:21:35.515] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a227557617465726c6f6f227d", attempt 4, (Reconnection)
[11:21:35.516] SSH Resolver called for host: uWaterloo
[11:21:35.516] Setting up SSH remote "uWaterloo"
[11:21:35.519] Using commit id "97dec172d3256f8ca4bfb2143f3f76b503ca0534" and quality "stable" for server
[11:21:35.521] Install and start server if needed
[11:21:35.523] Running script with connection command: ssh -T -D 6621 "uWaterloo" bash
[11:21:35.525] Terminal shell path: C:\Windows\System32\cmd.exe
[11:21:43.653] > 3cb8a00f8fcc: running
> ]0;C:\Windows\System32\cmd.exe
[11:21:43.653] Got some output, clearing connection timeout
[11:21:43.691] > Acquiring lock on /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534
[11:21:43.706] > \ln /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534.target /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534
> ln: failed to create hard link '/u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534': File exists
> Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> 3cb8a00f8fcc: start
> exitCode==24==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/32480==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 3cb8a00f8fcc: end
[11:21:43.707] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/32480==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[11:21:43.707] Server installation process already in progress - waiting and retrying
[11:21:44.717] Running script with connection command: ssh -T -D 6621 "uWaterloo" bash
[11:21:44.720] Terminal shell path: C:\Windows\System32\cmd.exe
[11:21:45.152] "install" terminal command done
[11:21:45.152] Install terminal quit with output: 
[11:21:45.474] > 3cb8a00f8fcc: running
> ]0;C:\Windows\System32\cmd.exe
[11:21:45.474] Got some output, clearing connection timeout
[11:21:45.500] > Acquiring lock on /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534
> \ln /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534.target /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534
> Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> ln: failed to create hard link '/u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534': File exists
> 3cb8a00f8fcc: start
> exitCode==24==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/32480==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 3cb8a00f8fcc: end
[11:21:45.500] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/32480==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[11:21:45.501] Server installation process already in progress - waiting and retrying
[11:21:46.510] Running script with connection command: ssh -T -D 6621 "uWaterloo" bash
[11:21:46.511] Terminal shell path: C:\Windows\System32\cmd.exe
[11:21:46.941] "install" terminal command done
[11:21:46.941] Install terminal quit with output: 
[11:21:47.034] > 3cb8a00f8fcc: running
> ]0;C:\Windows\System32\cmd.exe
[11:21:47.034] Got some output, clearing connection timeout
[11:21:47.070] > Acquiring lock on /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534
[11:21:47.091] > \ln /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534.target /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534
> ln: failed to create hard link '/u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534': File exists
> Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> 3cb8a00f8fcc: start
> exitCode==24==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/32480==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 3cb8a00f8fcc: end
[11:21:47.091] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/32480==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[11:21:47.091] Server installation process already in progress - waiting and retrying
[11:21:48.100] Running script with connection command: ssh -T -D 6621 "uWaterloo" bash
[11:21:48.102] Terminal shell path: C:\Windows\System32\cmd.exe
[11:21:48.539] "install" terminal command done
[11:21:48.539] Install terminal quit with output: 
[11:21:52.158] > 89e8e5902604: running
> ]0;C:\Windows\System32\cmd.exe
[11:21:52.159] Got some output, clearing connection timeout
[11:21:52.200] > Acquiring lock on /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534
[11:21:52.215] > \ln /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534.target /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534
> ln: failed to create hard link '/u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534'Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> 89e8e5902604: start
> exitCode==24==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/32480==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 89e8e5902604: end
> : File exists
[11:21:53.479] "install" terminal command done
[11:21:53.480] Install terminal quit with output: 
[11:22:04.898] > 40d6c6ee9821: running
> ]0;C:\Windows\System32\cmd.exe
[11:22:04.898] Got some output, clearing connection timeout
[11:22:04.933] > Acquiring lock on /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534
[11:22:04.952] > \ln /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534.target /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534
> ln: failed to create hard link '/u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534': File exists
> Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> 40d6c6ee9821: start
> exitCode==24==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/32480==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 40d6c6ee9821: end
[11:22:05.104] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (c:\Users\maste\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:584052)
	at Timeout._onTimeout (c:\Users\maste\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:679189)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[11:22:05.106] ------




[11:22:05.145] ------




[11:22:05.145] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a227557617465726c6f6f227d", attempt 5, (Reconnection)
[11:22:05.146] SSH Resolver called for host: uWaterloo
[11:22:05.146] Setting up SSH remote "uWaterloo"
[11:22:05.148] Using commit id "97dec172d3256f8ca4bfb2143f3f76b503ca0534" and quality "stable" for server
[11:22:05.152] Install and start server if needed
[11:22:05.156] Running script with connection command: ssh -T -D 6627 "uWaterloo" bash
[11:22:05.158] Terminal shell path: C:\Windows\System32\cmd.exe
[11:22:06.214] "install" terminal command done
[11:22:06.215] Install terminal quit with output: 
[11:22:22.170] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (c:\Users\maste\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:584052)
	at Timeout._onTimeout (c:\Users\maste\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:679189)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[11:22:22.172] ------




[11:22:24.877] > 3cb8a00f8fcc: running
> ]0;C:\Windows\System32\cmd.exe
[11:22:24.877] Got some output, clearing connection timeout
[11:22:24.909] > Acquiring lock on /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534
[11:22:25.042] > \ln /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534.target /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534
[11:22:25.055] > ln: failed to create hard link '/u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534': File exists
> Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> 3cb8a00f8fcc: start
> exitCode==24==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/32480==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 3cb8a00f8fcc: end
[11:22:26.321] "install" terminal command done
[11:22:26.321] Install terminal quit with output: 
[11:22:38.979] > 6c2ef27c56c5: running
> ]0;C:\Windows\System32\cmd.exe
[11:22:38.980] Got some output, clearing connection timeout
[11:22:39.009] > Acquiring lock on /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534
[11:22:39.106] > \ln /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534.target /u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534
[11:22:39.118] > Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> 6c2ef27c56c5: start
> exitCode==24==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/32480==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 6c2ef27c56c5: end
> ln: failed to create hard link '/u5/e5lopez/.vscode-server/bin/97dec172d3256f8ca4bfb2143f3f76b503ca0534/vscode-remote-lock.e5lopez.97dec172d3256f8ca4bfb2143f3f76b503ca0534': File exists
[11:22:40.390] "install" terminal command done
[11:22:40.391] Install terminal quit with output: 
```

</p>
</details>

**Comment by eleanorjboyd** [comment]
If you do a reset (by calling `kill vs code server on remote`) does this fix the problem? Or does the exact error message continue to come up?

**Comment by elibroftw** [comment]
Well I removed the linking file myself, but now I get: 
```
  channel 3: open failed: connect failed: Connection refused
```

**Comment by elibroftw** [comment]
Is there a way to kill the server without hunting for the PID manually? I don't think the server's even running.

**Comment by elibroftw** [comment]
It finally works, but just saying that there's a big issue with how the remote SSH extension update the vscode-server. I suggest using a rename + background delete methodology which does not block rather than the current blocking, buggy, random way.

**Comment by eleanorjboyd** [comment]
Understood thank you for your feedback. Currently since it is an issue with a work-around it does not result in a top priority but we may relook at this logic at some point.

**Comment by elibroftw** [comment]
Got the error again because vscode is deleting the folder instead of renaming it and deleting in the background.
```
ln: failed to create hard link '/u5/e5lopez/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/vscode-remote-lock.e5lopez.e2816fe719a4026ffa1ee0189dc89bdfdbafb164': File exists
```

**Comment by elibroftw** [comment]
I honestly don't understand if you guys think it's reasonable to make users wait over 10 minutes to delete a folder recursively as if it matters if deleting the folder needs to occur synchrnously as opposed to async.

**Comment by elibroftw** [comment]
Every single time, I have to ssh and renaming and delete the folder in the background and then remove the symlink myself so that vscode works. The program is not robust at all!

**Comment by eleanorjboyd** [comment]
Hello again! I think it would be best to separate these issues since from my understanding there seems to be two problems. From my understanding, there is an issue with the hard link and the connection then to your remote. Have you tried setting "useFlock" back to true? I see you have it as false right now. Secondly, it seems like you are having an issue with deleting a large folder. You are suggesting that instead of us doing it recursively we do it more in the background? If could write out a wholistic description of the problem and your suggested solution I can move that to a new issue for investigation or feature request. Thanks
