### ISSUE TITLE
ERROR: invalid character '\x00' looking for beginning of value

### ISSUE THREAD

**Issue by krave1986** [microsoft/vscode-remote-release#7846]
- VSCode Version: 1.74.3
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 20.04.5 LTS
- Remote Extension/Connection Type: Containers

- Logs: 
  [2023-01-12T04:01:16.387Z] Dev Containers 0.266.1 in VS Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534).
[2023-01-12T04:01:16.387Z] Start: Resolving Remote
[2023-01-12T04:01:16.435Z] Setting up container for folder or workspace: d:\devcontainers\fixed-got\fixed-got
[2023-01-12T04:01:16.481Z] Start: Check Docker is running
[2023-01-12T04:01:16.481Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2023-01-12T04:01:16.653Z] Stop (172 ms): Run: docker version --format {{.Server.APIVersion}}
[2023-01-12T04:01:16.653Z] Server API version: 1.41
[2023-01-12T04:01:16.653Z] Stop (172 ms): Check Docker is running
[2023-01-12T04:01:16.654Z] Start: Run: docker volume ls -q
[2023-01-12T04:01:16.810Z] Stop (156 ms): Run: docker volume ls -q
[2023-01-12T04:01:16.878Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=d:\devcontainers\fixed-got\fixed-got --filter label=vsch.quality=stable
[2023-01-12T04:01:17.042Z] Stop (164 ms): Run: docker ps -q -a --filter label=vsch.local.folder=d:\devcontainers\fixed-got\fixed-got --filter label=vsch.quality=stable
[2023-01-12T04:01:17.042Z] Start: Run: C:\Program Files\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\Administrator\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder d:\devcontainers\fixed-got\fixed-got --workspace-mount-consistency cached --id-label devcontainer.local_folder=d:\devcontainers\fixed-got\fixed-got --log-level debug --log-format json --config d:\devcontainers\fixed-got\fixed-got\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-01-12T04:01:17.296Z] (node:19868) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2023-01-12T04:01:17.296Z] (Use `Code --trace-deprecation ...` to show where the warning was created)
[2023-01-12T04:01:17.298Z] @devcontainers/cli 0.25.2. Node.js v16.14.2. win32 10.0.19044 x64.
[2023-01-12T04:01:17.298Z] Start: Run: docker buildx version
[2023-01-12T04:01:17.573Z] Stop (275 ms): Run: docker buildx version
[2023-01-12T04:01:17.574Z] github.com/docker/buildx v0.9.1 ed00243a0ce2a0aee75311b06e32d33b44729689
[2023-01-12T04:01:17.574Z] 
[2023-01-12T04:01:17.574Z] Start: Resolving Remote
[2023-01-12T04:01:17.577Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=d:\devcontainers\fixed-got\fixed-got
[2023-01-12T04:01:17.725Z] Stop (148 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=d:\devcontainers\fixed-got\fixed-got
[2023-01-12T04:01:17.728Z] Start: Run: docker inspect --type image ubuntu:latest
[2023-01-12T04:01:17.881Z] Stop (153 ms): Run: docker inspect --type image ubuntu:latest
[2023-01-12T04:01:17.883Z] local container features stored at: c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\node_modules\vscode-dev-containers\container-features
[2023-01-12T04:01:17.884Z] Start: Run: tar --no-same-owner -x -f -
[2023-01-12T04:01:17.943Z] Stop (59 ms): Run: tar --no-same-owner -x -f -
[2023-01-12T04:01:17.945Z] Start: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\ADMINI~1\AppData\Local\Temp\devcontainercli\container-features\0.25.2-1673496077882\Dockerfile-with-features -t vsc-fixed-got-bf927df6b08c2ce61ccd3f9d4a2a8cfa --target dev_containers_target_stage --no-cache --pull --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label d:\devcontainers\fixed-got\fixed-got\.devcontainer
[2023-01-12T04:01:18.102Z] 
[2023-01-12T04:01:18.269Z] ERROR: invalid character '\x00' looking for beginning of value
[2023-01-12T04:01:18.393Z] Stop (448 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\ADMINI~1\AppData\Local\Temp\devcontainercli\container-features\0.25.2-1673496077882\Dockerfile-with-features -t vsc-fixed-got-bf927df6b08c2ce61ccd3f9d4a2a8cfa --target dev_containers_target_stage --no-cache --pull --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label d:\devcontainers\fixed-got\fixed-got\.devcontainer
[2023-01-12T04:01:18.394Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\ADMINI~1\AppData\Local\Temp\devcontainercli\container-features\0.25.2-1673496077882\Dockerfile-with-features -t vsc-fixed-got-bf927df6b08c2ce61ccd3f9d4a2a8cfa --target dev_containers_target_stage --no-cache --pull --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label d:\devcontainers\fixed-got\fixed-got\.devcontainer
[2023-01-12T04:01:18.394Z]     at Doe (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\spec-node\devContainersSpecCLI.js:1894:1669)
[2023-01-12T04:01:18.394Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-01-12T04:01:18.394Z]     at async EF (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\spec-node\devContainersSpecCLI.js:1893:1978)
[2023-01-12T04:01:18.394Z]     at async uT (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\spec-node\devContainersSpecCLI.js:1893:901)
[2023-01-12T04:01:18.394Z]     at async Poe (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\spec-node\devContainersSpecCLI.js:1899:2128)
[2023-01-12T04:01:18.394Z]     at async Zf (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\spec-node\devContainersSpecCLI.js:1899:3278)
[2023-01-12T04:01:18.394Z]     at async aue (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\spec-node\devContainersSpecCLI.js:2020:15276)
[2023-01-12T04:01:18.395Z]     at async oue (c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\spec-node\devContainersSpecCLI.js:2020:15030)
[2023-01-12T04:01:18.405Z] Stop (1363 ms): Run: C:\Program Files\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\Administrator\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder d:\devcontainers\fixed-got\fixed-got --workspace-mount-consistency cached --id-label devcontainer.local_folder=d:\devcontainers\fixed-got\fixed-got --log-level debug --log-format json --config d:\devcontainers\fixed-got\fixed-got\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-01-12T04:01:18.406Z] Exit code 1
[2023-01-12T04:01:18.410Z] Command failed: C:\Program Files\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\Administrator\.vscode\extensions\ms-vscode-remote.remote-containers-0.266.1\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\Administrator\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder d:\devcontainers\fixed-got\fixed-got --workspace-mount-consistency cached --id-label devcontainer.local_folder=d:\devcontainers\fixed-got\fixed-got --log-level debug --log-format json --config d:\devcontainers\fixed-got\fixed-got\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-01-12T04:01:18.411Z] Exit code 1

Steps to Reproduce:

1. Clone [this repo](https://github.com/krave1986/devcontainers) into local Windows filesystem.
2. Use VS Code to open this folder.
3. Press **Reopen** button when dialog window pops out.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by krave1986** [comment]
Hi @chrmarti , I tried to clone the repo on `C:` and repeat the operation I mentioned above. Still same error. This repo is what I build on this machine months ago. I also have another project running on this machine based on this repo without any problem. So I don't see why would this happen.

**Comment by chrmarti** [comment]
What are the differences between the two repos? 🤔

**Comment by krave1986** [comment]
They are same repo.
I take the repo as a seed container environment.
Every node.js project is based on this repo as a start point.

**Comment by krave1986** [comment]
@chrmarti Other users also reported similar issue who using VS Code within containers. https://github.com/docker/for-win/issues/12561

**Comment by yilmazdurmaz** [comment]
`\x00` is the `null` we know from many programming languages. and for this error, it means at least one file's context is overwritten all by nulls.

I opened the issue @krave1986 linked, and then found out it was some of the context files being broken. here, I suggest checking them first and taking my suggested action if that is the case. otherwise, you need to compare two recent commits of the repo and try to find those files with broken content.

**Comment by krave1986** [comment]
Hi @yilmazdurmaz , thank you for the hint.
I followed your suggestion and found that `meta.json` is also broken which turned into a binary file instead of a text json file.

I open it up via hex editor and it shows all zeros as you expected.
![image](https://user-images.githubusercontent.com/16416541/215379449-26bb238b-4d84-4fed-b18d-ba09d624aa53.png)

**Comment by yilmazdurmaz** [comment]
Alright then, at least we know why you get the error you get :) a broken context file prevents docker even from starting itself. 

We still don't know why this happens yet, but at least, know how to fix it: remove broken context files. just be careful if you have custom contexts.
