### ISSUE TITLE
[Remote-SSH Bug]: Resolver error: Error: Failed to install the VS Code Server

### ISSUE THREAD

**Issue by marfeljoergsen** [microsoft/vscode-remote-release#7857]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Debugging Steps

- [X] I have followed these debugging steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting
- [X] My SSH command works from a local terminal
- [ ] I can connect using the Remote-SSH extension on VS Code when all other VS Code extensions are disabled

### Versions

- VS Code Version: 1.74.3
- Remote OS Version: v0.94.0

### Expected Behavior

I expect to be able to connect to a remote computer via SSH. And I can also see it logins perfectly fine. It then wget downloads some remote server files and complains and exits with error. I don't expect any errors, as ssh works.

### Steps To Reproduce

1. I just click "Connect to Host" - type in the server.
2. I wait for it to connect - but it doesn't ever really complete the vscode-server-stuff it needs.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[21:51:05.320] Log Level: 2
[21:51:05.322] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a226d6f785562756e7475564d227d", attempt 1
[21:51:05.322] "remote.SSH.useLocalServer": true
[21:51:05.323] "remote.SSH.path": undefined
[21:51:05.323] "remote.SSH.configFile": undefined
[21:51:05.324] "remote.SSH.useFlock": true
[21:51:05.324] "remote.SSH.lockfilesInTmp": false
[21:51:05.324] "remote.SSH.localServerDownload": auto
[21:51:05.324] "remote.SSH.remoteServerListenOnSocket": false
[21:51:05.325] "remote.SSH.showLoginTerminal": false
[21:51:05.325] "remote.SSH.defaultExtensions": []
[21:51:05.325] "remote.SSH.loglevel": 2
[21:51:05.326] "remote.SSH.enableDynamicForwarding": true
[21:51:05.326] "remote.SSH.enableRemoteCommand": false
[21:51:05.326] "remote.SSH.serverPickPortsFromRange": {}
[21:51:05.326] "remote.SSH.serverInstallPath": {}
[21:51:05.331] VS Code version: 1.74.2
[21:51:05.331] Remote-SSH version: remote-ssh@0.95.2023010915
[21:51:05.331] linux x64
[21:51:05.332] SSH Resolver called for host: someUbuntuInstallation
[21:51:05.333] Setting up SSH remote "someUbuntuInstallation"
[21:51:05.335] Acquiring local install lock: /tmp/vscode-remote-ssh-a174a889-install.lock
[21:51:05.336] Looking for existing server data file at /home/user/.config/Code - OSS/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-a174a889-e8a3071ea4344d9d48ef8a4df2c097372b0c5161-0.95.2023010915/data.json
[21:51:05.336] Using commit id "e8a3071ea4344d9d48ef8a4df2c097372b0c5161" and quality "stable" for server
[21:51:05.338] Install and start server if needed
[21:51:05.340] PATH: /usr/lib/ccache/bin/:/usr/condabin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin:/home/user/bin
[21:51:05.341] Checking ssh with "ssh -V"
[21:51:05.347] > OpenSSH_9.1p1, OpenSSL 3.0.7 1 Nov 2022

[21:51:05.350] askpass server listening on /run/user/1000/vscode-ssh-askpass-021fefcfec676c7074f83c9062f2769f83a867e2.sock
[21:51:05.350] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-60caf0b29b1345b4e9bb0dbb1596b4761c57de95.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","42669","-o","ConnectTimeout=15","someUbuntuInstallation"],"serverDataFolderName":".vscode-server-oss","dataFilePath":"/home/user/.config/Code - OSS/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-a174a889-e8a3071ea4344d9d48ef8a4df2c097372b0c5161-0.95.2023010915/data.json"}
[21:51:05.350] Local server env: {"SHELL":"/usr/bin/zsh","DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/user/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.95.2023010915/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/lib/electron19/electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/user/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.95.2023010915/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-021fefcfec676c7074f83c9062f2769f83a867e2.sock"}
[21:51:05.354] Spawned 938577
[21:51:05.464] > local-server-1> Running ssh connection command: "-v -T -D 42669 -o ConnectTimeout=15 someUbuntuInstallation"
[21:51:05.467] > local-server-1> Spawned ssh, pid=938585
[21:51:05.471] stderr> OpenSSH_9.1p1, OpenSSL 3.0.7 1 Nov 2022
[21:51:05.632] stderr> debug1: Server host key: ssh-ed25519 SHA256:Z9lIWLtdAaVoZfE/Oxy98PamfX6CUigSYN1wPeU/PSQ
[21:51:05.681] stderr> Authenticated to 192.168.78.48 ([192.168.78.48]:22) using "publickey".
[21:51:06.995] > Welcome to Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-58-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>   System information as of Sun 15 Jan 20:51:05 UTC 2023
> 
>   System load:  0.830078125        Processes:              117
>   Usage of /:   36.2% of 14.65GB   Users logged in:        1
>   Memory usage: 17%                IPv4 address for ens18: 192.168.78.48
>   Swap usage:   0%
> 
>  * Strictly confined Kubernetes makes edge and IoT secure. Learn how MicroK8s
>    just raised the bar for easy, resilient and secure K8s cluster deployment.
> 
>    https://ubuntu.com/engage/secure-kubernetes-at-the-edge
> 
> 0 updates can be applied immediately.
> 
[21:51:07.014] > ready: a4ff5548b5bc
[21:51:07.019] > Linux 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023
[21:51:07.019] Platform: linux
[21:51:07.021] > /bin/bash
[21:51:07.021] Shell: bash
[21:51:07.021] Creating bash subshell inside "bash"
[21:51:07.027] > bash version:  5.1.16(1)-release
[21:51:07.047] > a4ff5548b5bc: running
[21:51:07.117] > Acquiring lock on /home/ubuntu/.vscode-server-oss/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/vscode-remote-lock.ubuntu.e8a3071ea4344d9d48ef8a4df2c097372b0c5161
[21:51:07.125] > Installing to /home/ubuntu/.vscode-server-oss/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161...
[21:51:07.132] > a4ff5548b5bc%%1%%
[21:51:07.140] > Downloading with wget
[21:51:10.369] > Download complete
[21:51:10.399] > a4ff5548b5bc%%2%%
> tar --version:
[21:51:10.451] > tar (GNU tar) 1.34
> Copyright (C) 2021 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[21:51:15.257] stderr> mv: cannot move 'vscode-server-linux-x64/bin' to './bin': Directory not empty
[21:51:15.257] stderr> mv: cannot move 'vscode-server-linux-x64/extensions' to './extensions': Directory not empty
[21:51:15.288] > ERROR: /home/ubuntu/.vscode-server-oss/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/node or /home/ubuntu/.vscode-server-oss/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/bin/code-server-oss don't exist
> Trigger local server download
> a4ff5548b5bc:trigger_server_download
> platform==linux==
> vscodeArch==x64==
> destFolder==/home/ubuntu/.vscode-server-oss/bin/==
> destFolder2==e8a3071ea4344d9d48ef8a4df2c097372b0c5161==
> a4ff5548b5bc:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/ubuntu/.vscode-server-oss/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/vscode-scp-done.flag and vscode-server.tar.gz to exist
>  
[21:51:15.288] Got request to download on client for {"platform":"linux","arch":"x64","destFolder":"/home/ubuntu/.vscode-server-oss/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161"}
[21:51:15.289] Downloading VS Code server locally...
[21:51:15.290] stderr> mv: cannot move 'vscode-server-linux-x64/node_modules' to './node_modules': Directory not empty
[21:51:15.290] stderr> mv: cannot move 'vscode-server-linux-x64/out' to './out': Directory not empty
[21:51:17.471] Downloaded VS Code server to /tmp/91d9ff91-f66f-4844-b9af-9dce39c95468
[21:51:17.471] Renamed VS Code server to /tmp/vscode_server_1673815877471/vscode-server.tar.gz
[21:51:17.474] PATH: /usr/lib/ccache/bin/:/usr/condabin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin:/home/user/bin
[21:51:17.474] Checking ssh with "ssh -V"
[21:51:17.480] > OpenSSH_9.1p1, OpenSSL 3.0.7 1 Nov 2022

[21:51:17.481] Testing scp with "scp"
[21:51:17.484] scp exited with code: 1
[21:51:17.484] Got stderr from scp: usage: scp [-346ABCOpqRrsTv] [-c cipher] [-D sftp_server_path] [-F ssh_config]
           [-i identity_file] [-J destination] [-l limit]
           [-o ssh_option] [-P port] [-S program] source ... target
[21:51:17.485] Copying file to remote with scp -o ConnectTimeout=15 'vscode-server.tar.gz' 'vscode-scp-done.flag' 'someUbuntuInstallation':'/home/ubuntu/.vscode-server-oss/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161'
[21:51:17.485] Using cwd: file:///tmp/vscode_server_1673815877471
[21:51:18.065] > vscode-server.tar.gz                            0%    0     0.0KB/s   --:-- ETA
[21:51:18.286] >  
[21:51:19.065] > vscode-server.tar.gz                           32%   21MB  20.6MB/s   00:02 ETA
[21:51:20.065] > vscode-server.tar.gz                           95%   61MB  22.6MB/s   00:00 ETA
[21:51:20.093] > vscode-server.tar.gz                          100%   64MB  31.4MB/s   00:02    
> vscode-scp-done.flag                            0%    0     0.0KB/s   --:-- ETA
[21:51:20.099] > vscode-scp-done.flag                          100%    9     7.1KB/s   00:00    
[21:51:20.352] "Copy server to host" terminal command done
[21:51:21.290] > Found flag and server on host
[21:51:21.299] > a4ff5548b5bc%%2%%
> tar --version:
[21:51:21.303] > tar (GNU tar) 1.34
> Copyright (C) 2021 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[21:51:27.039] stderr> mv: cannot move 'vscode-server-linux-x64/bin' to './bin': Directory not empty
[21:51:27.039] stderr> mv: cannot move 'vscode-server-linux-x64/extensions' to './extensions': Directory not empty
[21:51:27.077] stderr> mv: cannot move 'vscode-server-linux-x64/node_modules' to './node_modules': Directory not empty
[21:51:27.077] stderr> mv: cannot move 'vscode-server-linux-x64/out' to './out': Directory not empty
[21:51:27.078] > ERROR: /home/ubuntu/.vscode-server-oss/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/node or /home/ubuntu/.vscode-server-oss/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/bin/code-server-oss don't exist
> Already attempted local download, failing
> a4ff5548b5bc: start
> exitCode==37==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/1000==
[21:51:27.078] > platform==linux==
> unpackResult==missingFiles==
> didLocalDownload==1==
> downloadTime==3257==
> installTime==5587==
> extInstallTime====
> serverStartTime====
[21:51:27.078] > a4ff5548b5bc: end
[21:51:27.079] Received install output: 
exitCode==37==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/1000==platform==linux==
unpackResult==missingFiles==
didLocalDownload==1==
downloadTime==3257==
installTime==5587==
extInstallTime====
serverStartTime====
[21:51:27.079] Terminating local server
[21:51:27.081] Resolver error: Error: Failed to install the VS Code Server
	at g.ServerInstallError (/home/user/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.95.2023010915/out/extension.js:1:584081)
	at f (/home/user/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.95.2023010915/out/extension.js:1:578529)
	at t.handleInstallOutput (/home/user/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.95.2023010915/out/extension.js:1:581316)
	at Object.e [as tryInstallWithLocalServer] (/home/user/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.95.2023010915/out/extension.js:1:623419)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/user/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.95.2023010915/out/extension.js:1:642712
	at async t.withShowDetailsEvent (/home/user/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.95.2023010915/out/extension.js:1:646432)
	at async /home/user/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.95.2023010915/out/extension.js:1:621891
	at async T (/home/user/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.95.2023010915/out/extension.js:1:618397)
	at async t.resolveWithLocalServer (/home/user/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.95.2023010915/out/extension.js:1:621506)
	at async t.resolve (/home/user/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.95.2023010915/out/extension.js:1:644040)
	at async /home/user/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.95.2023010915/out/extension.js:1:723355
[21:51:27.084] ------




[21:51:27.085] Local server exit: 15
```

</p>
</details>

### Anything else?

One thing is the "Resolver error: Error: Failed to install the VS Code Server"-error message. The other thing is that it also complained and gave an error here:

`ERROR: /home/ubuntu/.vscode-server-oss/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/node or /home/ubuntu/.vscode-server-oss/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/bin/code-server-oss don't exist`

But that error is actually wrong, because the ".../node"-file actually exists on the remote computer/system:

```
$ ls  /home/ubuntu/.vscode-server-oss/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/node
/home/ubuntu/.vscode-server-oss/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/node
```
I could/can also run the `.../bin/....(long hex-number).../bin/code-server`-executable on the remote side, which brings up the "Visual Studio Code Server"-headline and a reference to license terms and "Do you accept the terms in the License Agreement (Y/n)?"... So I'm surprised that when it can wget over ssh, but it cannot run this executable...?

**Comment by asbe** [comment]
I believe I faced the same issue as you. Switching to `Remote - SSH` pre-release (v0.95.2023010915) seems to resolve it.

**Comment by marfeljoergsen** [comment]
Sorry, for me switching to pre-release version: `0.95.2023010915` didn't work. I'm on Arch Linux, don't know if something is broken - but I tried 2 different Arch Linux computers and neither of them work, so... But thanks a lot for your input, I hope someone can help with ideas.

**Comment by marfeljoergsen** [comment]
More details: I'm on Arch Linux, but the server is running Ubuntu 22.04, both uptodate. I also tried downgrading to 0.84.0 (1 year old) and to 0.62.0 (2 years old). Same problem... I might see if I can figure out how to debug a VS code extension (which I've never done), could be interesting to see what's going on with that/those failing "mv"-commands, seems it's in a wrong directory or expecting files in a different directory...

**Comment by marfeljoergsen** [comment]
Ok, I figured it out: On arch linux, the `community/code`-package does not work with this extension but it does work with the official binary version (`aur/visual-studio-code-bin`). So this is a downstream-issue, Arch-related only...

**Comment by marfeljoergsen** [comment]
Hi eleanor. Thanks for looking into this. I don't understand it should be port-related, because it says`stderr> mv: cannot move ...` several times. So this was my main concern, however I don't know the code for this extension. Also, just to make sure I understand it correctly: Did you see my comment in the section "Anything else?" where it complains about missing ".../node" or missing "../code-server-oss" ? That message is also wrong, because node does exist when I use "ls" to check if the file is there. So this is where I suspect something is wrong... I'm happy to help and test anything, if this/these error messages and the extension can be improved.

You wrote I should run the "node.js"-script. I don't have the node executable installed on the remote server (at least not using the system package manager) and I assume you want me to run the "node.js"-script on the remote server, right? Since the node executable isn't installed on the remote system (but "node.js" works locally on the VS Code machine, where I do have it), I think the culprit is what's described in the "Anything else?"-section, i.e. the node-executable *IS* there, but still the extension complains and thinks it isn't there, in the log output:

`ERROR: /home/ubuntu/.vscode-server-oss/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/node or /home/ubuntu/.vscode-server-oss/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/bin/code-server-oss don't exist
`

If I misunderstood this, would you like me to run: `/home/ubuntu/.vscode-server-oss/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/node node.js` and report back if I can see the `Hello World!`-message using http://(ip-of-server):3000 ? If I use port 0, I think it takes a random port and then I think I need  `sudo netstat -tupln|grep -i node` to test http://(ip-of-server):(port-number), correct?

**Comment by eleanorjboyd** [comment]
Hello! Sorry for the delay in getting back to you. I seem to have mixed this issue up with another and the message I sent was meant for a different thread! So sorry for the confusion, I'm glad you figured your issue out and happy coding 🎉

**Comment by marfeljoergsen** [comment]
Hi eleanor. Ok, understood. If anyone is interested, I digged a bit more, just out of curiosity: Downloaded the .vsix-file for the extension, unzipped it, searched for what was going on and think that (my) issue happens in `extension/out/extension.js`. But this file is obfuscated so it's not easy to read. I think the problem I described is caused by something here (or it is part of the problem):
```
const S = await async function(e, t, r) {
    r.debug("Downloading VS Code server locally...");
    const n = await s.commands.executeCommand("_workbench.downloadResource", s.Uri.parse(e));
    if (!n) throw new Error(m(0, null));
    r.debug("Downloaded VS Code server to " + n.fsPath);
    const i = o.join(o.dirname(n.fsPath), `vscode_server_${Date.now()}`),
        a = o.join(i, t);
    return await g(i) || await _(i), await v(n.fsPath, a), r.debug("Renamed VS Code server to " + a), a
}(a, y, i.logger);
```
This code matches where I got these errors:

```
[21:51:15.289] Downloading VS Code server locally...
[21:51:15.290] stderr> mv: cannot move 'vscode-server-linux-x64/node_modules' to './node_modules': Directory not empty
[21:51:15.290] stderr> mv: cannot move 'vscode-server-linux-x64/out' to './out': Directory not empty
```
So I think while running `await s.commands.executeCommand("_workbench.downloadResource", s.Uri.parse(e));` something goes wrong and an exception is thrown. Otherwise I would have seen: "**_Downloaded VS Code server to..._**" in my log. I couldn't see the source code anywhere and my fix is not really a fix, more a work-around. Maybe this information can help the described problem to be fixed one day and if so, I would be happy to be informed/notified, I'll keep watching for updates here.
