### ISSUE TITLE
Remote WSL Extension fails to load

### ISSUE THREAD

**Issue by mjz19910** [microsoft/vscode-remote-release#7891]
Type: <b>Bug</b>
Remote WSL Extension fails to load

Getting this error in the extension host
```
2023-01-23 16:16:55.183 [error] Activating extension ms-vscode-remote.remote-wsl failed due to an error:
[error] Error: AIF keys are no longer supported. Please switch to 1DS keys for 1st party extensions
	at new m (c:\Users\user\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.75.0\dist\extension.js:2:277145)
	at t.setupTelemetry (c:\Users\user\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.75.0\dist\extension.js:2:715725)
	at t.activate (c:\Users\user\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.75.0\dist\extension.js:2:700953)
	at Ui.db (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:14814)
	at Ui.cb (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:14515)
	at c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:12517
	at async h.n (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:6818)
	at async h.m (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:6781)
	at async h.l (c:\Users\user\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:6238)
```
This causes requests with the url protocol `vscode-remote://` to fail with ENOPRO

Extension version: 0.75.0
VS Code version: Code - Insiders 1.75.0-insider (f1b09237cd400d92987cf7a9681995e8011ef54c, 2023-01-23T11:53:59.088Z)
OS version: Windows_NT x64 10.0.25281
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.79.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.76GB (45.07GB free)|
|Process Argv|--crash-reporter-id d8e6a4a1-1c4c-4468-b5c5-20e221d12d31|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.79.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|31.23GB (29.77GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30622696

```

</details>

**Comment by yostinso** [comment]
Appears to be newly broken in 0.75.0; 0.72.0 works fine.
This error may be triggered in [vscode-extension-telemetry](https://github.com/microsoft/vscode-extension-telemetry)

**Comment by aeschli** [comment]
I released 0.75.0 with a fix.
Make sure the extension is installed and close all VS Code Windows to make sure the remote server is shutting down.

**Comment by mjz19910** [comment]
Thanks it is working on the new version of `ms-vscode-remote.remote-wsl` 0.75.0

**Comment by aeschli** [comment]
@mjz19910 Thanks, I corrected the version.

**Comment by GavinRay97** [comment]
Thanks for the swift fix!
