### ISSUE TITLE
Error hit when opening workspace in container

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode-remote-release#7907]
Testing: https://github.com/microsoft/vscode-remote-release/issues/7881

I don't fully understand this error and if it is actually related to the TPI or if I just did an unsupported workflow. I hit this error when I executed these steps, I am not versed enough in containers to tell what the issue is. Thanks!

Steps:
- have the container open with a folder / some files
- click `save as workspace` from `file`
- select `open workspace in container` (this didn't work)
- select `rebuild container` pop up that showed up after I saved the workspace saying I can made changes

These logs showed up in the terminal tab
<img width="1279" alt="Screenshot 2023-01-24 at 10 29 07 AM" src="https://user-images.githubusercontent.com/26030610/214378863-6f4e2e38-83b1-40c2-a312-2b8b24e5ee03.png">

```
[280 ms] Dev Containers 0.272.0 in VS Code 1.75.0-insider (5ae522f8563fe48b89470923f77a9732f96c0472).
[279 ms] Start: Resolving Remote
[285 ms] Setting up container for folder or workspace: /Users/eleanorboyd/Documents/testing_tester_files/devContainerTester
[285 ms] Context: desktop-linux
[290 ms] Start: Check Docker is running
[290 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[384 ms] Server API version: 1.41
[385 ms] Start: Run: docker volume ls -q
[441 ms] Start: Run: docker inspect --type container b6f0646e86e44f01c2350d67b890e37657f3f8a8b9cd982205cd1701a5c973cb
[493 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/eleanorboyd/Documents/testing_tester_files/devContainerTester --filter label=vsch.quality=insider
[544 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/eleanorboyd/Documents/testing_tester_files/devContainerTester --filter label=devcontainer.config_file=/Users/eleanorboyd/Documents/testing_tester_files/devContainerTester/.devcontainer/devcontainer.json
[598 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/eleanorboyd/Documents/testing_tester_files/devContainerTester
[648 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/eleanorboyd/Documents/testing_tester_files/devContainerTester
[703 ms] Start: Run: /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin) --ms-enable-electron-run-as-node /Users/eleanorboyd/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.272.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/eleanorboyd/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder tmp/devcontainers-5cc3ddb5-249e-4903-a9d4-9d15b2420b031674584930753 --workspace-folder /Users/eleanorboyd/Documents/testing_tester_files/devContainerTester --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/eleanorboyd/Documents/testing_tester_files/devContainerTester --id-label devcontainer.config_file=/Users/eleanorboyd/Documents/testing_tester_files/devContainerTester/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/eleanorboyd/Documents/testing_tester_files/devContainerTester/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[857 ms] (node:4088) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[858 ms] (Use `Code - Insiders Helper (Plugin) --trace-deprecation ...` to show where the warning was created)
[858 ms] @devcontainers/cli 0.29.0. Node.js v16.14.2. darwin 22.2.0 arm64.
[858 ms] Start: Run: docker buildx version
[1054 ms] github.com/docker/buildx v0.9.1 ed00243a0ce2a0aee75311b06e32d33b44729689
[1054 ms] 
[1054 ms] Start: Resolving Remote
[1055 ms] Start: Run: git rev-parse --show-cdup
[1067 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/eleanorboyd/Documents/testing_tester_files/devContainerTester --filter label=devcontainer.config_file=/Users/eleanorboyd/Documents/testing_tester_files/devContainerTester/.devcontainer/devcontainer.json
[1139 ms] Start: Run: docker inspect --type image mcr.microsoft.com/devcontainers/base:alpine-3.17
[1191 ms] local container features stored at: /Users/eleanorboyd/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.272.0/dist/node_modules/vscode-dev-containers/container-features
[1192 ms] Start: Run: tar --no-same-owner -x -f -
[1236 ms] * Processing feature: ghcr.io/devcontainers/features/sshd:1
[1906 ms] * Fetching feature: sshd_1_oci
[2324 ms] Start: Run: docker buildx build --load --build-context dev_containers_feature_content_source=/var/folders/q8/17wzg0cx7p59c1qfvwxx8yhc0000gn/T/devcontainercli/container-features/0.29.0-1674584932352 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:alpine-3.17 --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-devcontainertester-03606461beff94e70fceb93eacde6b69-features -f /var/folders/q8/17wzg0cx7p59c1qfvwxx8yhc0000gn/T/devcontainercli/container-features/0.29.0-1674584932352/Dockerfile.extended /Users/eleanorboyd/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[+] Building 2.2s (15/15) FINISHED                                              
 => [internal] load build definition from Dockerfile.extended              0.0s
 => => transferring dockerfile: 1.30kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               1.0s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531b  0.0s
 => [internal] load build definition from Dockerfile.extended              0.0s
 => [internal] load .dockerignore                                          0.0s
 => [context dev_containers_feature_content_source] load .dockerignore     0.0s
 => => transferring dev_containers_feature_content_source: 2B              0.0s
 => [internal] load metadata for mcr.microsoft.com/devcontainers/base:alp  0.0s
 => [context dev_containers_feature_content_source] load from client       0.1s
 => => transferring dev_containers_feature_content_source: 310.70kB        0.1s
 => [dev_containers_feature_content_normalize 1/3] FROM mcr.microsoft.com  0.1s
 => [dev_containers_feature_content_normalize 2/3] COPY --from=dev_contai  0.0s
 => [dev_containers_feature_content_normalize 3/3] RUN chmod -R 0700 /tmp  0.2s
 => [dev_containers_target_stage 2/4] COPY --from=dev_containers_feature_  0.0s
 => [dev_containers_target_stage 3/4] RUN echo "_CONTAINER_USER_HOME=$(ge  0.2s
 => ERROR [dev_containers_target_stage 4/4] RUN cd /tmp/build-features/ss  0.2s
------
 > [dev_containers_target_stage 4/4] RUN cd /tmp/build-features/sshd_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh:
#0 0.189 ===========================================================================
#0 0.189 Feature       : SSH server
#0 0.189 Description   : Adds a SSH server into a container so that you can use an external terminal, sftp, or SSHFS to interact with it.
#0 0.189 Id            : ghcr.io/devcontainers/features/sshd
#0 0.189 Version       : 1.0.7
#0 0.189 Documentation : https://github.com/devcontainers/features/tree/main/src/sshd
#0 0.189 Options       :
#0 0.189     VERSION="latest"
#0 0.189 ===========================================================================
#0 0.201 find: /var/lib/apt/lists/*: No such file or directory
#0 0.202 Running apt-get update...
#0 0.202 ./install.sh: line 49: apt-get: command not found
#0 0.203 ERROR: Feature "SSH server" (ghcr.io/devcontainers/features/sshd) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/sshd for help troubleshooting this error.
------
ERROR: failed to solve: executor failed running [/bin/sh -c cd /tmp/build-features/sshd_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh]: exit code: 127
[5194 ms] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/var/folders/q8/17wzg0cx7p59c1qfvwxx8yhc0000gn/T/devcontainercli/container-features/0.29.0-1674584932352 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:alpine-3.17 --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-devcontainertester-03606461beff94e70fceb93eacde6b69-features -f /var/folders/q8/17wzg0cx7p59c1qfvwxx8yhc0000gn/T/devcontainercli/container-features/0.29.0-1674584932352/Dockerfile.extended /Users/eleanorboyd/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[5195 ms]     at fie (/Users/eleanorboyd/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.272.0/dist/spec-node/devContainersSpecCLI.js:1915:1355)
[5195 ms]     at P7 (/Users/eleanorboyd/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.272.0/dist/spec-node/devContainersSpecCLI.js:1915:1291)
[5195 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[5195 ms]     at async Fie (/Users/eleanorboyd/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.272.0/dist/spec-node/devContainersSpecCLI.js:1921:2093)
[5195 ms]     at async Vf (/Users/eleanorboyd/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.272.0/dist/spec-node/devContainersSpecCLI.js:1921:3241)
[5195 ms]     at async eoe (/Users/eleanorboyd/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.272.0/dist/spec-node/devContainersSpecCLI.js:2045:17324)
[5195 ms]     at async Qse (/Users/eleanorboyd/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.272.0/dist/spec-node/devContainersSpecCLI.js:2045:17065)
[5196 ms] Exit code 1
[5199 ms] Command failed: /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Plugin).app/Contents/MacOS/Code - Insiders Helper (Plugin) --ms-enable-electron-run-as-node /Users/eleanorboyd/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.272.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/eleanorboyd/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder tmp/devcontainers-5cc3ddb5-249e-4903-a9d4-9d15b2420b031674584930753 --workspace-folder /Users/eleanorboyd/Documents/testing_tester_files/devContainerTester --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/eleanorboyd/Documents/testing_tester_files/devContainerTester --id-label devcontainer.config_file=/Users/eleanorboyd/Documents/testing_tester_files/devContainerTester/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/eleanorboyd/Documents/testing_tester_files/devContainerTester/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[5199 ms] Exit code 1
```

**Comment by chrmarti** [comment]
The log shows that it tries to install a feature into an Alpine container using `apt-get`. This is due to a gap in our feature story where features can't tell which distros they support. We are tracking this in https://github.com/devcontainers/spec/issues/58. Thanks!
