### ISSUE TITLE
Unable to build basic Alpine image in Ubuntu

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-remote-release#7908]
Testing #7881

1. On Linux, set up and add the current $USER to the `docker` group
1. `snap install docker` and `snap install code-insiders`
2. Verify `docker run hello-world` works
3. Create a basic alpine devcontainer.json
4. Try to reopen the workspace in a container

Get the following log:

```
[170 ms] Dev Containers 0.272.0 in VS Code 1.75.0-insider (0a6c277e4faa44a6b6eb82ddca8bfeccf7fecef6).
[169 ms] Start: Resolving Remote
[183 ms] Setting up container for folder or workspace: /home/connor/Downloads/multi-devcontainer-test
[187 ms] Start: Check Docker is running
[187 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[280 ms] Server API version: 
[282 ms] Start: Run: docker volume ls -q
[369 ms] Start: Run: docker volume create vscode
[446 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/connor/Downloads/multi-devcontainer-test --filter label=vsch.quality=insider
[537 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/connor/Downloads/multi-devcontainer-test --filter label=devcontainer.config_file=/home/connor/Downloads/multi-devcontainer-test/.devcontainer/devcontainer.json
[614 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/connor/Downloads/multi-devcontainer-test
[691 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/connor/Downloads/multi-devcontainer-test
[783 ms] Start: Run: /snap/code-insiders/1202/usr/share/code-insiders/code-insiders --ms-enable-electron-run-as-node /home/connor/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.272.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/connor/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder tmp/devcontainers-f6467a77-aded-4951-9c13-6f7bbb2a6f9b1674585240536 --workspace-folder /home/connor/Downloads/multi-devcontainer-test --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/connor/Downloads/multi-devcontainer-test --id-label devcontainer.config_file=/home/connor/Downloads/multi-devcontainer-test/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/connor/Downloads/multi-devcontainer-test/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-ffe0ab0008035109dd942dda33382eb6078a7759.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[1143 ms] (node:955033) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1144 ms] (Use `code-insiders --trace-deprecation ...` to show where the warning was created)
[1145 ms] @devcontainers/cli 0.29.0. Node.js v16.14.2. linux 5.15.0-53-generic x64.
[1145 ms] Start: Run: docker buildx version
[1648 ms] 
[1648 ms] 
[1648 ms] Start: Resolving Remote
[1653 ms] Start: Run: git rev-parse --show-cdup
[1660 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/connor/Downloads/multi-devcontainer-test --filter label=devcontainer.config_file=/home/connor/Downloads/multi-devcontainer-test/.devcontainer/devcontainer.json
[1776 ms] Start: Run: docker inspect --type image mcr.microsoft.com/devcontainers/base:alpine-3.17
[2114 ms] local container features stored at: /home/connor/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.272.0/dist/node_modules/vscode-dev-containers/container-features
[2116 ms] Start: Run: tar --no-same-owner -x -f -
[2182 ms] Start: Run: docker build -f /tmp/devcontainercli-connor/updateUID.Dockerfile-0.29.0 -t vsc-multi-devcontainer-test-e20a532bcf577c01ab07691f81e5e813-uid --build-arg BASE_IMAGE=mcr.microsoft.com/devcontainers/base:alpine-3.17 --build-arg REMOTE_USER=vscode --build-arg NEW_UID=1000 --build-arg NEW_GID=1001 --build-arg IMAGE_USER=root /home/connor/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /tmp/devcontainercli-connor: no such file or directory
[2923 ms] Error: Command failed: docker build -f /tmp/devcontainercli-connor/updateUID.Dockerfile-0.29.0 -t vsc-multi-devcontainer-test-e20a532bcf577c01ab07691f81e5e813-uid --build-arg BASE_IMAGE=mcr.microsoft.com/devcontainers/base:alpine-3.17 --build-arg REMOTE_USER=vscode --build-arg NEW_UID=1000 --build-arg NEW_GID=1001 --build-arg IMAGE_USER=root /home/connor/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2923 ms]     at fie (/home/connor/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.272.0/dist/spec-node/devContainersSpecCLI.js:1915:1355)
[2923 ms]     at P7 (/home/connor/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.272.0/dist/spec-node/devContainersSpecCLI.js:1915:1291)
[2923 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2924 ms]     at async Fie (/home/connor/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.272.0/dist/spec-node/devContainersSpecCLI.js:1921:2093)
[2924 ms]     at async Vf (/home/connor/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.272.0/dist/spec-node/devContainersSpecCLI.js:1921:3241)
[2924 ms]     at async eoe (/home/connor/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.272.0/dist/spec-node/devContainersSpecCLI.js:2045:17324)
[2924 ms]     at async Qse (/home/connor/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.272.0/dist/spec-node/devContainersSpecCLI.js:2045:17065)
[2929 ms] Exit code 1
[2933 ms] Command failed: /snap/code-insiders/1202/usr/share/code-insiders/code-insiders --ms-enable-electron-run-as-node /home/connor/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.272.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/connor/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder tmp/devcontainers-f6467a77-aded-4951-9c13-6f7bbb2a6f9b1674585240536 --workspace-folder /home/connor/Downloads/multi-devcontainer-test --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/connor/Downloads/multi-devcontainer-test --id-label devcontainer.config_file=/home/connor/Downloads/multi-devcontainer-test/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/connor/Downloads/multi-devcontainer-test/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-ffe0ab0008035109dd942dda33382eb6078a7759.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2933 ms] Exit code 1
```

**Comment by chrmarti** [comment]
Have you installed Docker with snap? Looks like https://github.com/microsoft/vscode-remote-release/issues/5865.
