### ISSUE TITLE
[Remote-SSH Bug]: 

### ISSUE THREAD

**Issue by joehfis** [microsoft/vscode-remote-release#7937]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Debugging Steps

- [X] I have followed these debugging steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting
- [X] My SSH command works from a local terminal
- [ ] I can connect using the Remote-SSH extension on VS Code when all other VS Code extensions are disabled

### Versions

- VS Code Version: 1.74.3, remote SSH v0.94.0
- Remote OS Version: Red Hat 6.10, Red Hat 7.9

### Expected Behavior

Able to login to the remote Linux server to work on code that resides on remote servers.

### Steps To Reproduce

1. From Windows 10 laptop, I opened an Ubuntu shell.
2. Ran ssh to the redhat server with and without the -T flag.
3. From the Ubuntu shell, ssh succeeds without the -T flag.
4. From the Ubuntu shell, ssh fails with below error message.
5. Also tested from a Windows 2012 server to RH 7.9 using putty and had to remove -T and bash options.

### Remote-SSH Log

<details>
<summary>[[15:43:45.447] Log Level: 2
[15:43:45.452] [remote-ssh@0.94.0](mailto:remote-ssh@0.94.0)
[15:43:45.452] win32 x64
[15:43:45.458] SSH Resolver called for "ssh-remote+pdc1rfisnexbs01", attempt 1
[15:43:45.458] "remote.SSH.useLocalServer": false
[15:43:45.459] "remote.SSH.showLoginTerminal": true
[15:43:45.459] "remote.SSH.remotePlatform": {"10.236.254.20":"linux","10.237.117.97":"linux","pdc1rfisnexbs01":"linux","PDC1RFISDCNAP01":"linux","ltc1rfisnexbs01":"linux"}
[15:43:45.459] "remote.SSH.path": undefined
[15:43:45.459] "remote.SSH.configFile": C:\Users\e0116257\.ssh\config
[15:43:45.459] "remote.SSH.useFlock": true
[15:43:45.460] "remote.SSH.lockfilesInTmp": false
[15:43:45.460] "remote.SSH.localServerDownload": auto
[15:43:45.460] "remote.SSH.remoteServerListenOnSocket": false
[15:43:45.460] "remote.SSH.showLoginTerminal": true
[15:43:45.460] "remote.SSH.defaultExtensions": []
[15:43:45.460] "remote.SSH.loglevel": 2
[15:43:45.460] "remote.SSH.enableDynamicForwarding": true
[15:43:45.460] "remote.SSH.enableRemoteCommand": false
[15:43:45.460] "remote.SSH.serverPickPortsFromRange": {}
[15:43:45.460] "remote.SSH.serverInstallPath": {}
[15:43:45.465] SSH Resolver called for host: pdc1rfisnexbs01
[15:43:45.466] Setting up SSH remote "pdc1rfisnexbs01"
[15:43:45.473] Using commit id "97dec172d3256f8ca4bfb2143f3f76b503ca0534" and quality "stable" for server
[15:43:45.478] Install and start server if needed
[15:43:45.482] Checking ssh with "ssh -V"
[15:43:48.067] > OpenSSH_for_Windows_8.1
[15:43:48.068] > p1, LibreSSL 3.0.2
 
[15:43:48.074] Using SSH config file "C:\Users\e0116257\.ssh\config"
[15:43:48.075] Running script with connection command: ssh -T -D 61160 -F "C:\Users\e0116257\.ssh\config" pdc1rfisnexbs01 bash
[15:43:48.078] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:43:52.600] > ]0;C:\WINDOWS\System32\cmd.exe 
[15:43:52.602] Got some output, clearing connection timeout
[15:43:52.605] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[15:43:53.878] > 
[15:43:53.901] > **************************************************
[15:43:53.922] > *******************************************************************************
> **                     Fidelity Informati
[15:43:53.930] > **                     Fidelity Information Services                         **
> **             Proprietary - Us
[15:43:53.951] > **             Proprietary - Use Pursuant To Company Policy                  **
> ***********************
[15:43:53.958] > *******************************************************************************
> **
[15:43:53.976] > **                                                                           **
> **  SEC
[15:43:53.993] > **  SECURITY NOTICE:                                                         **
> **    Th
[15:43:54.010] > **    This computer system contains sensitive client information managed by  **
> **  FIS and is i
[15:43:54.027] > **  FIS and is intended for official and other authorized use only.          **
> **    Unauthorized access or u
[15:43:54.044] > **    Unauthorized access or use of this system may subject violators to     **
> **  administrative action, civil, and/or cri
[15:43:54.060] > **  administrative action, civil, and/or criminal prosecution under the      **
> **  United States Criminal Code (Title 18 U.S.C.
[15:43:54.077] > **  United States Criminal Code (Title 18 U.S.C. \247 1030).                 **
> **    All information on this computer system may be monitor
[15:43:54.086] > **    All information on this computer system may be monitored, intercepted, **
> **  recorded, read, copied, or captured and disclosed by
[15:43:54.103] > **  recorded, read, copied, or captured and disclosed by and to authorized   **
> **  personnel for official purposes, including criminal pro
[15:43:54.122] > **  personnel for official purposes, including criminal prosecution.         **
> **    You have no expectations of privacy using this system. Any authorized  **
[15:43:54.133] > 
> **  or unauthorized use of this computer system signifies consent to and     **
> **  com
[15:43:54.143] > **  compliance with FIS policies and those security/privacy compliance       **
> **  regulations require
[15:43:54.160] > **  regulations required by external governing bodies and these terms.       **
> **
[15:43:54.176] > **                                                                           **
> **    By logging into this server, you agree to accept these terms. **
[15:43:54.210] > 
> *******************************************************************************
> 
[15:43:54.419] > Enter PASSCODE: 
[15:44:11.951] > 
[15:44:16.714] > Received disconnect from 10.236.254.20 port 22:2: No terminal authorization granted
> Disconnected from 10.236.254.20 port 22
[15:44:16.741] > 
> The process tried to write to a nonexistent pipe.
[15:44:20.575] "install" terminal command done
[15:44:20.576] Install terminal quit with output: Disconnected from 10.236.254.20 port 22
[15:44:20.577] Received install output: Disconnected from 10.236.254.20 port 22
[15:44:20.578] Failed to parse remote port from server output
[15:44:20.582] Resolver error: Error: 
      at g.Create (c:\Users\e0116257\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:583926)
      at t.handleInstallOutput (c:\Users\e0116257\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:582540)
      at t.tryInstall (c:\Users\e0116257\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:680469)
      at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async c:\Users\e0116257\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:642848
      at async t.withShowDetailsEvent (c:\Users\e0116257\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:646166)
      at async t.resolve (c:\Users\e0116257\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:643898)
      at async c:\Users\e0116257\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:723024
[15:44:20.595] ------]
```</summary>
<p>

```

</p>
</details>

### Anything else?

I recommend making the entire line that the plug in passes  to the server end user configurable. I noticed that removing -T and bash options are necessary from some clients, on others, removing -T is sufficient. 
Thanks
Joe

**Comment by eleanorjboyd** [comment]
Hello! The `-T` parameter is a known issue for some people's setups, have you used the extension before and successfully connected? Therefore is this a regression or your first time attempting to use the extension?

**Comment by joehfis** [comment]
Hi Eleanor,
This is the first time I'm using the extension.
BTW, I also tested from a Windows 2012 server to RH 7.9, using putty and had to remove -T and bash.
I would recommend making the entire line customizable by the end user.
"C:\Users\e0116257\AppData\Local\Programs\Git\usr\bin\ssh.exe" -T -D 62275 -F "C:\Users\e0116257\.ssh\config" pdc1rfisnexbs01 bash

Thanks
Joe

Thanks.

FIS| Joe Hermosillo | ETS Storage Administrator | Storage Support Services | ***@***.******@***.***> | ?Mobile: 312.446.8603

**Comment by eleanorjboyd** [comment]
We are planning on adding a setting to allow for the -T parameter to be changeable, you can follow the progress here: https://github.com/microsoft/vscode-remote-release/issues/7558. Thank you and sorry you ran into this issue!
