### ISSUE TITLE
Error: Missing node-pty on dev-containers-cli-0.266.1

### ISSUE THREAD

**Issue by steve-fraser** [microsoft/vscode-remote-release#7947]
Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:05:37.721Z (4 mos ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No

- Local OS Version:  Darwin x64 21.6.0
- Remote OS Version: Ubuntu
- Remote Extension/Connection Type: Server

- Logs:

Steps to Reproduce:

```
steve@workspace0:~/.vscode-server/extensions$ /home/steve/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/node /home/steve/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/steve/code --log-level debug --log-format json --config /home/steve/code/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true
(node:177470) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: Missing node-pty
    at MD (/home/steve/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js:1673:1412)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async dn (/home/steve/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js:1672:13306)
    at async Cue (/home/steve/.vscode-remote-containers/dist/dev-containers-cli-0.266.1/dist/spec-node/devContainersSpecCLI.js:2020:31172)
```

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: Yes/No

**Comment by andy-v-h** [comment]
I am having the same issue with 
Remote OS: MacOS Ventura 
_and_
Remote OS: Arch Linux

**Comment by chrmarti** [comment]
You need to set `NODE_PATH` to the `node_modules` folder next to the `node` executable.

I curious: Why are you trying to run the CLI like that?

**Comment by kinghat** [comment]
i just got this issue as well after updating code and docker so not sure of the cause:

> docker-ce 3:23.0.0-1.fc37

> Version: 1.75.0
> Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
> Date: 2023-02-01T15:29:17.766Z
> Electron: 19.1.9
> Chromium: 102.0.5005.194
> Node.js: 16.14.2
> V8: 10.2.154.23-electron.0
> OS: Linux x64 6.1.8-200.fc37.x86_64
> Sandboxed: No

not using the cli directly but the vscode extension and devcontainer.

i tired to rebuild my devcontainer and am now getting build errors and am not sure if they are related. i can run the docker hello-world just fine:

```
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount696486693/updateUID.Dockerfile-0.29.0: no such file or directory
[2023-02-03T05:01:38.131Z] Stop (1010 ms): Run: docker build -f /tmp/devcontainercli-kinghat/updateUID.Dockerfile-0.29.0 -t vsc-tabbed-card-79216982b8fdbb64893a7e58609031ac-uid --build-arg BASE_IMAGE=thomasloven/hass-custom-devcontainer --build-arg REMOTE_USER=vscode --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=vscode /home/kinghat/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2023-02-03T05:01:38.132Z] Error: Command failed: docker build -f /tmp/devcontainercli-kinghat/updateUID.Dockerfile-0.29.0 -t vsc-tabbed-card-79216982b8fdbb64893a7e58609031ac-uid --build-arg BASE_IMAGE=thomasloven/hass-custom-devcontainer --build-arg REMOTE_USER=vscode --build-arg NEW_UID=1000 --build-arg NEW_GID=1000 --build-arg IMAGE_USER=vscode /home/kinghat/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2023-02-03T05:01:38.132Z]     at fie (/home/kinghat/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1915:1355)
[2023-02-03T05:01:38.132Z]     at P7 (/home/kinghat/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1915:1291)
[2023-02-03T05:01:38.133Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-02-03T05:01:38.133Z]     at async Fie (/home/kinghat/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1921:2093)
[2023-02-03T05:01:38.134Z]     at async Vf (/home/kinghat/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1921:3241)
[2023-02-03T05:01:38.134Z]     at async eoe (/home/kinghat/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:2045:17324)
[2023-02-03T05:01:38.134Z]     at async Qse (/home/kinghat/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:2045:17065)
[2023-02-03T05:01:38.144Z] Stop (3047 ms): Run: /usr/share/code/code --ms-enable-electron-run-as-node /home/kinghat/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/kinghat/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder tmp/devcontainers-65acb17f-5550-4289-abec-019c97488a8c1675400492229 --workspace-folder /home/kinghat/Projects/tabbed-card --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/kinghat/Projects/tabbed-card --id-label devcontainer.config_file=/home/kinghat/Projects/tabbed-card/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/kinghat/Projects/tabbed-card/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-8ec87859aa93284876715a31dc0396c7608a193f.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-02-03T05:01:38.144Z] Exit code 1
[2023-02-03T05:01:38.147Z] Command failed: /usr/share/code/code --ms-enable-electron-run-as-node /home/kinghat/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/kinghat/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder tmp/devcontainers-65acb17f-5550-4289-abec-019c97488a8c1675400492229 --workspace-folder /home/kinghat/Projects/tabbed-card --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/kinghat/Projects/tabbed-card --id-label devcontainer.config_file=/home/kinghat/Projects/tabbed-card/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/kinghat/Projects/tabbed-card/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-8ec87859aa93284876715a31dc0396c7608a193f.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-02-03T05:01:38.148Z] Exit code 1
```

**Comment by chrmarti** [comment]
@kinghat That looks different. I will copy it to a new issue.

**Comment by steve-fraser** [comment]
> You need to set `NODE_PATH` to the `node_modules` folder next to the `node` executable.
> 
> I curious: Why are you trying to run the CLI like that?

when I was running the rebuild container workflow it said "failed to run command" or something like that with no details,  but listed the command. I wanted to see the failure output, so i copied the command to run it locally to see the the output.
