### ISSUE TITLE
Cannot read properties of undefined (reading 'parsedAuthority')

### ISSUE THREAD

**Issue by GongT** [microsoft/vscode-remote-release#7954]
Type: <b>Bug</b>

```text
2023-02-02 14:34:21.967 [info] Invoking resolveAuthority(dev-container)...
2023-02-02 14:34:21.967 [info] [LocalProcess0][resolveAuthority(dev-container,1)][0ms] obtaining proxy...
2023-02-02 14:34:21.967 [info] [LocalProcess0][resolveAuthority(dev-container,1)][0ms] invoking...
2023-02-02 14:34:22.968 [info] [LocalProcess0][resolveAuthority(dev-container,1)][1000ms] waiting...
2023-02-02 14:34:23.973 [info] [LocalProcess0][resolveAuthority(dev-container,1)][2005ms] waiting...
2023-02-02 14:34:24.979 [info] [LocalProcess0][resolveAuthority(dev-container,1)][3011ms] waiting...
2023-02-02 14:34:25.968 [info] [LocalProcess0][resolveAuthority(dev-container,1)][4000ms] waiting...
2023-02-02 14:34:26.968 [info] [LocalProcess0][resolveAuthority(dev-container,1)][5000ms] waiting...
2023-02-02 14:34:27.967 [info] [LocalProcess0][resolveAuthority(dev-container,1)][6000ms] waiting...
2023-02-02 14:34:28.968 [info] [LocalProcess0][resolveAuthority(dev-container,1)][7000ms] waiting...
2023-02-02 14:34:29.972 [info] [LocalProcess0][resolveAuthority(dev-container,1)][8004ms] waiting...
2023-02-02 14:34:30.979 [info] [LocalProcess0][resolveAuthority(dev-container,1)][9011ms] waiting...
2023-02-02 14:34:31.968 [info] [LocalProcess0][resolveAuthority(dev-container,1)][10000ms] waiting...
2023-02-02 14:34:32.969 [info] [LocalProcess0][resolveAuthority(dev-container,1)][11001ms] waiting...
2023-02-02 14:34:33.970 [info] [LocalProcess0][resolveAuthority(dev-container,1)][12002ms] waiting...
2023-02-02 14:34:34.971 [info] [LocalProcess0][resolveAuthority(dev-container,1)][13003ms] waiting...
2023-02-02 14:34:35.969 [info] [LocalProcess0][resolveAuthority(dev-container,1)][14001ms] waiting...
2023-02-02 14:34:36.460 [error] RequestService#request (browser) - error https://update.code.visualstudio.com/commit:e2816fe719a4026ffa1ee0189dc89bdfdbafb164/server-linux-x64/insider {}
2023-02-02 14:34:36.466 [error] [LocalProcess0][resolveAuthority(dev-container,1)][14498ms] returned an error {"name":"TypeError","message":"Cannot read properties of undefined (reading 'parsedAuthority')"}
2023-02-02 14:34:36.467 [error] resolveAuthority(dev-container) returned an error after 14500 ms {"name":"CodeExpectedError","_message":"Cannot read properties of undefined (reading 'parsedAuthority')","_code":"Unknown","_detail":{"name":"TypeError","message":"Cannot read properties of undefined (reading 'parsedAuthority')"},"isHandled":false}
2023-02-02 14:34:36.467 [error] Error received from starting extension host (kind: Remote)
2023-02-02 14:34:36.467 [error] CodeExpectedError: Cannot read properties of undefined (reading 'parsedAuthority')
    at Jc.vc (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2631:5709)
    at async Jc.zc (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2631:6721)
    at async Jc.Yb (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2631:7874)
    at async Jc.wb (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2629:20636)
2023-02-02 14:34:36.468 [error] [remote-connection][attempt 1] An error occurred in initial connection! Will retry... Error:
2023-02-02 14:34:36.468 [error] CodeExpectedError: Cannot read properties of undefined (reading 'parsedAuthority')
    at Jc.vc (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2631:5709)
    at async Jc.zc (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2631:6721)
    at async Jc.Yb (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2631:7874)
    at async Jc.wb (vscode-file://vscode-app/c:/Users/gongt/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2629:20636)
2023-02-02 14:34:36.469 [error] [remote-connection][attempt 2] An error occurred in initial connection! Will retry... Error:
```

VS Code version: Code - Insiders 1.75.0-insider (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:16:18.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.0-58-generic
Connection to 'Dev Container: 开发容器 @ ssh://10.1.20.131' could not be established  Cannot read properties of undefined (reading 'parsedAuthority')
Connection to 'SSH: 10.1.20.131' could not be established 

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X3D 8-Core Processor            (16 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.93GB (44.33GB free)|
|Process Argv|--crash-reporter-id 96f73321-5813-467b-a648-55a25ee2317b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: 开发容器 @ ssh://10.1.20.131|
|OS|Linux x64 5.15.0-58-generic|
|CPUs|AMD EPYC 7H12 64-Core Processor (8 x 2599)|
|Memory (System)|62.81GB (59.96GB free)|
|VM|0%|

Connection to 'Dev Container: 开发容器 @ ssh://10.1.20.131' could not be established  Cannot read properties of undefined (reading 'parsedAuthority')

Connection to 'SSH: 10.1.20.131' could not be established 
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887

```

</details>

**Comment by chrmarti** [comment]
This might be fixed in Dev Containers 0.276.0-pre-release (requires VS Code 1.75 stable or insiders to install). Could you give that a try? This might surface another issue, if so, please append the log for that here. (`F1` > `Dev Containers: Show Container Log`)
