### ISSUE TITLE
Remote container start error: failed to receive status: rpc error: code = Unavailable

### ISSUE THREAD

**Issue by lukaemon** [microsoft/vscode-remote-release#7955]
- VSCode Version: 1.75
- Local OS Version: MacOS 13.2
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: Containers

- Logs:
```
[2023-02-03T06:48:26.163Z] Dev Containers 0.275.0 in VS Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164).
[2023-02-03T06:48:26.163Z] Start: Resolving Remote
[2023-02-03T06:48:26.173Z] Start: Run: ssh home /bin/sh
[2023-02-03T06:48:26.174Z] Start: Run in host: id -un
[2023-02-03T06:48:26.358Z] lucas
[2023-02-03T06:48:26.358Z] 
[2023-02-03T06:48:26.358Z] Stop (184 ms): Run in host: id -un
[2023-02-03T06:48:26.358Z] Start: Run in host: cat /etc/passwd
[2023-02-03T06:48:26.360Z] Stop (2 ms): Run in host: cat /etc/passwd
[2023-02-03T06:48:26.361Z] Start: Run in host: echo ~
[2023-02-03T06:48:26.362Z] /home/lucas
[2023-02-03T06:48:26.363Z] 
[2023-02-03T06:48:26.363Z] Stop (2 ms): Run in host: echo ~
[2023-02-03T06:48:26.363Z] Start: Run in host: test -x '/home/lucas/.vscode-remote-containers/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/node'
[2023-02-03T06:48:26.364Z] 
[2023-02-03T06:48:26.364Z] 
[2023-02-03T06:48:26.364Z] Stop (1 ms): Run in host: test -x '/home/lucas/.vscode-remote-containers/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/node'
[2023-02-03T06:48:26.365Z] Start: Run in host: test -f '/home/lucas/.vscode-remote-containers/dist/vscode-remote-containers-server-0.275.0.js'
[2023-02-03T06:48:26.366Z] 
[2023-02-03T06:48:26.366Z] 
[2023-02-03T06:48:26.366Z] Stop (1 ms): Run in host: test -f '/home/lucas/.vscode-remote-containers/dist/vscode-remote-containers-server-0.275.0.js'
[2023-02-03T06:48:26.368Z] userEnvProbe: loginInteractiveShell (default)
[2023-02-03T06:48:26.369Z] userEnvProbe: not found in cache
[2023-02-03T06:48:26.369Z] userEnvProbe shell: /bin/bash
[2023-02-03T06:48:26.694Z] userEnvProbe PATHs:
Probe:     '/home/lucas/miniconda3/bin:/home/lucas/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
Container: None
[2023-02-03T06:48:26.696Z] Setting up container for folder or workspace: /home/lucas/dev/seed
[2023-02-03T06:48:26.696Z] Host: ssh://home
[2023-02-03T06:48:26.702Z] Start: Check Docker is running
[2023-02-03T06:48:26.703Z] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[2023-02-03T06:48:26.763Z] Stop (60 ms): Run in Host: docker version --format {{.Server.APIVersion}}
[2023-02-03T06:48:26.764Z] Server API version: 1.42
[2023-02-03T06:48:26.764Z] Stop (62 ms): Check Docker is running
[2023-02-03T06:48:26.765Z] Start: Run in Host: docker volume ls -q
[2023-02-03T06:48:26.811Z] Stop (46 ms): Run in Host: docker volume ls -q
[2023-02-03T06:48:26.812Z] Start: Run in Host: docker ps -q -a --filter label=vsch.local.folder=/home/lucas/dev/seed --filter label=vsch.quality=stable
[2023-02-03T06:48:26.855Z] Stop (43 ms): Run in Host: docker ps -q -a --filter label=vsch.local.folder=/home/lucas/dev/seed --filter label=vsch.quality=stable
[2023-02-03T06:48:26.855Z] Start: Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=/home/lucas/dev/seed --filter label=devcontainer.config_file=/home/lucas/dev/seed/.devcontainer/devcontainer.json
[2023-02-03T06:48:26.894Z] Stop (39 ms): Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=/home/lucas/dev/seed --filter label=devcontainer.config_file=/home/lucas/dev/seed/.devcontainer/devcontainer.json
[2023-02-03T06:48:26.894Z] Start: Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=/home/lucas/dev/seed
[2023-02-03T06:48:26.939Z] Stop (45 ms): Run in Host: docker ps -q -a --filter label=devcontainer.local_folder=/home/lucas/dev/seed
[2023-02-03T06:48:26.943Z] Start: Run in Host: /home/lucas/.vscode-remote-containers/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/node /home/lucas/.vscode-remote-containers/dist/dev-containers-cli-0.275.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder tmp/devcontainers-2271acab-664a-4ed8-96a0-99765211ffc61675406905222 --workspace-folder /home/lucas/dev/seed --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/lucas/dev/seed --id-label devcontainer.config_file=/home/lucas/dev/seed/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/lucas/dev/seed/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-02-03T06:48:27.062Z] (node:10366) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2023-02-03T06:48:27.063Z] (Use `node --trace-deprecation ...` to show where the warning was created)
[2023-02-03T06:48:27.043Z] @devcontainers/cli 0.29.0. Node.js v16.14.2. linux 5.15.0-58-generic x64.
[2023-02-03T06:48:27.043Z] Start: Run: docker buildx version
[2023-02-03T06:48:27.111Z] Stop (68 ms): Run: docker buildx version
[2023-02-03T06:48:27.111Z] github.com/docker/buildx v0.10.2 00ed17d
[2023-02-03T06:48:27.111Z] 
[2023-02-03T06:48:27.112Z] Start: Resolving Remote
[2023-02-03T06:48:27.114Z] Start: Run: git rev-parse --show-cdup
[2023-02-03T06:48:27.116Z] Stop (2 ms): Run: git rev-parse --show-cdup
[2023-02-03T06:48:27.117Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/lucas/dev/seed --filter label=devcontainer.config_file=/home/lucas/dev/seed/.devcontainer/devcontainer.json
[2023-02-03T06:48:27.151Z] Stop (34 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/lucas/dev/seed --filter label=devcontainer.config_file=/home/lucas/dev/seed/.devcontainer/devcontainer.json
[2023-02-03T06:48:27.153Z] Start: Run: docker inspect --type image nvcr.io/nvidia/pytorch:22.11-py3
[2023-02-03T06:48:27.201Z] Stop (48 ms): Run: docker inspect --type image nvcr.io/nvidia/pytorch:22.11-py3
[2023-02-03T06:48:27.202Z] local container features stored at: /home/lucas/.vscode-remote-containers/dist/dev-containers-cli-0.275.0/dist/node_modules/vscode-dev-containers/container-features
[2023-02-03T06:48:27.203Z] Start: Run: tar --no-same-owner -x -f -
[2023-02-03T06:48:27.216Z] Stop (13 ms): Run: tar --no-same-owner -x -f -
[2023-02-03T06:48:27.217Z] Start: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-lucas/container-features/0.29.0-1675406907201/Dockerfile-with-features -t vsc-seed-83fbbf41c4c80bfc940446a3f201c3a2 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /home/lucas/dev/seed
[2023-02-03T06:48:27.389Z] 
[2023-02-03T06:48:27.389Z] [+] Building 0.0s (0/1)                                                         
[2023-02-03T06:48:27.539Z] [+] Building 0.2s (10/11)                                                       
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 1.73kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for nvcr.io/nvidia/pytorch:22.11-py3          0.0s
 => [internal] load build context                                          0.0s
 => => transferring context: 37B                                           0.0s
 => [dev_container_auto_added_stage_label 1/6] FROM nvcr.io/nvidia/pytorc  0.0s
 => CACHED [dev_container_auto_added_stage_label 2/6] COPY requirement.tx  0.0s
 => CACHED [dev_container_auto_added_stage_label 3/6] RUN apt update && a  0.0s
 => CACHED [dev_container_auto_added_stage_label 4/6] RUN pip install -U   0.0s
[2023-02-03T06:48:27.539Z]  => CACHED [dev_container_auto_added_stage_label 5/6] RUN pip install --u  0.0s
 => CACHED [dev_container_auto_added_stage_label 6/6] RUN pip install -r   0.0s
 => preparing layers for inline cache                                      0.1s
[2023-02-03T06:48:27.653Z] [+] Building 0.3s (10/11)                                                       
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 1.73kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for nvcr.io/nvidia/pytorch:22.11-py3          0.0s
[2023-02-03T06:48:27.653Z]  => [internal] load build context                                          0.0s
 => => transferring context: 37B                                           0.0s
 => [dev_container_auto_added_stage_label 1/6] FROM nvcr.io/nvidia/pytorc  0.0s
 => CACHED [dev_container_auto_added_stage_label 2/6] COPY requirement.tx  0.0s
 => CACHED [dev_container_auto_added_stage_label 3/6] RUN apt update && a  0.0s
 => CACHED [dev_container_auto_added_stage_label 4/6] RUN pip install -U   0.0s
 => CACHED [dev_container_auto_added_stage_label 5/6] RUN pip install --u  0.0s
 => CACHED [dev_container_auto_added_stage_label 6/6] RUN pip install -r   0.0s
 => preparing layers for inline cache                                      0.2s
ERROR: failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF
[2023-02-03T06:48:27.857Z] Stop (640 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-lucas/container-features/0.29.0-1675406907201/Dockerfile-with-features -t vsc-seed-83fbbf41c4c80bfc940446a3f201c3a2 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /home/lucas/dev/seed
[2023-02-03T06:48:27.878Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-lucas/container-features/0.29.0-1675406907201/Dockerfile-with-features -t vsc-seed-83fbbf41c4c80bfc940446a3f201c3a2 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /home/lucas/dev/seed
[2023-02-03T06:48:27.878Z]     at pie (/home/lucas/.vscode-remote-containers/dist/dev-containers-cli-0.275.0/dist/spec-node/devContainersSpecCLI.js:1916:1698)
[2023-02-03T06:48:27.878Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-02-03T06:48:27.878Z]     at async vF (/home/lucas/.vscode-remote-containers/dist/dev-containers-cli-0.275.0/dist/spec-node/devContainersSpecCLI.js:1915:1972)
[2023-02-03T06:48:27.878Z]     at async P7 (/home/lucas/.vscode-remote-containers/dist/dev-containers-cli-0.275.0/dist/spec-node/devContainersSpecCLI.js:1915:901)
[2023-02-03T06:48:27.878Z]     at async Fie (/home/lucas/.vscode-remote-containers/dist/dev-containers-cli-0.275.0/dist/spec-node/devContainersSpecCLI.js:1921:2093)
[2023-02-03T06:48:27.878Z]     at async Vf (/home/lucas/.vscode-remote-containers/dist/dev-containers-cli-0.275.0/dist/spec-node/devContainersSpecCLI.js:1921:3241)
[2023-02-03T06:48:27.878Z]     at async eoe (/home/lucas/.vscode-remote-containers/dist/dev-containers-cli-0.275.0/dist/spec-node/devContainersSpecCLI.js:2045:17324)
[2023-02-03T06:48:27.879Z]     at async Qse (/home/lucas/.vscode-remote-containers/dist/dev-containers-cli-0.275.0/dist/spec-node/devContainersSpecCLI.js:2045:17065)
[2023-02-03T06:48:27.882Z] Stop (939 ms): Run in Host: /home/lucas/.vscode-remote-containers/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/node /home/lucas/.vscode-remote-containers/dist/dev-containers-cli-0.275.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder tmp/devcontainers-2271acab-664a-4ed8-96a0-99765211ffc61675406905222 --workspace-folder /home/lucas/dev/seed --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/lucas/dev/seed --id-label devcontainer.config_file=/home/lucas/dev/seed/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/lucas/dev/seed/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-02-03T06:48:27.883Z] Exit code 1
[2023-02-03T06:48:27.885Z] Command failed: /home/lucas/.vscode-remote-containers/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/node /home/lucas/.vscode-remote-containers/dist/dev-containers-cli-0.275.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder tmp/devcontainers-2271acab-664a-4ed8-96a0-99765211ffc61675406905222 --workspace-folder /home/lucas/dev/seed --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/lucas/dev/seed --id-label devcontainer.config_file=/home/lucas/dev/seed/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/lucas/dev/seed/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-02-03T06:48:27.885Z] Exit code 1
```

Steps to Reproduce:

1. Was using it fine 2 hours ago. Then it stop working.

**Comment by lukaemon** [comment]
Could it be this docker update...?

```
Client: Docker Engine - Community
 Version:           23.0.0
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        e92dd87
 Built:             Wed Feb  1 17:49:08 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.0
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       d7573ab
  Built:            Wed Feb  1 17:49:08 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

I did a `sudo apt upgrade` before the failure.

**Comment by jprenaudet** [comment]
Had the same error this morning.
Downgrading docker to `20.10.23` make devcontainer works again

**Comment by lukaemon** [comment]
Try to remove and reinstall docker, got this error:
```
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Fri 2023-02-03 15:30:43 CST; 3ms ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
    Process: 34660 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
   Main PID: 34660 (code=exited, status=1/FAILURE)
dpkg: error processing package docker-ce (--configure):
 installed docker-ce package post-installation script subprocess returned error exit status 1
```

Are they related? Networking problem?

**Comment by lukaemon** [comment]
> Had the same error this morning. Downgrading docker to `20.10.23` make devcontainer works again

Right on. Let me try.

**Comment by lukaemon** [comment]
Downgrade, rebuild container, works again. 
Cost 1 hour, release 400g disk space. Ok deal... Thanks @jprenaudet 

```
Client: Docker Engine - Community
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:36:25 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:34:14 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by leandroximenes** [comment]
Thank you!!!

I tried reinstall devcontainer and didn't worked.

When I donwgraded It's worked

**Comment by wkinne** [comment]
Anyone have a link to or instructions on reverting to 20.10.23? TIA

**Comment by lukaemon** [comment]
> Anyone have a link to or instructions on reverting to 20.10.23? TIA

Check this section. Remove and reinstall. https://docs.docker.com/engine/install/ubuntu/#uninstall-docker-engine

**Comment by leandroximenes** [comment]
> Anyone have a link to or instructions on reverting to 20.10.23? TIA

sudo apt-get update
apt-cache madison docker-ce
    docker-ce | 5:23.0.0-1~ubuntu.22.04~jammy | https://download.docker.com/linux/ubuntu jammy/stable amd64 Packages
    docker-ce | 5:20.10.23~3-0~ubuntu-jammy | https://download.docker.com/linux/ubuntu jammy/stable amd64 Packages
    docker-ce | 5:20.10.22~3-0~ubuntu-jammy | https://download.docker.com/linux/ubuntu jammy/stable amd64 Packages

choose the version and run:
sudo apt-get install docker-ce=5:20.10.20~3-0~ubuntu-jammy
