### ISSUE TITLE
VS Code: Building docker fails: devContainersSpecCLI.js

### ISSUE THREAD

**Issue by VSCBSt** [microsoft/vscode-remote-release#7966]
How would you search the reason for that error : ?

VS Code 1.75.0
Dev Containers v0.275.0

```
ERROR: failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF
[3200 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-username/container-features/0.29.0-1675438293541/Dockerfile-with-features -t vsc-workspace-59d8363462602ea70fe70ed3756ea6fb --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /origin/vscode-launcher/configs/mgu22/workspace/.devcontainer
[3200 ms]     at pie (/home/username/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1916:1698)
[3201 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[3201 ms]     at async vF (/home/username/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1915:1972)
[3201 ms]     at async P7 (/home/username/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1915:901)
[3201 ms]     at async Fie (/home/username/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1921:2093)
[3201 ms]     at async Vf (/home/username/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1921:3241)
[3201 ms]     at async eoe (/home/username/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:2045:17324)
[3201 ms]     at async Qse (/home/username/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:2045:17065)
[3204 ms] Exit code 1
[3206 ms] Command failed: /usr/share/code/code --ms-enable-electron-run-as-node /home/username/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/username/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder tmp/devcontainers-bd4a15b9-54f5-4ea9-8419-061d3c146e861675438290663 --workspace-folder /origin/vscode-launcher/configs/mgu22/workspace --workspace-mount-consistency cached --id-label devcontainer.local_folder=/origin/vscode-launcher/configs/mgu22/workspace --id-label devcontainer.config_file=/origin/vscode-launcher/configs/mgu22/workspace/.devcontainer/devcontainer.json --log-level debug --log-format json --config /origin/vscode-launcher/configs/mgu22/workspace/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[3206 ms] Exit code 1
```

**Comment by chrmarti** [comment]
Tracking as https://github.com/microsoft/vscode-remote-release/issues/7958.
