### ISSUE TITLE
"Error: Illegal argument: base" when opening in container

### ISSUE THREAD

**Issue by rjra100** [microsoft/vscode-remote-release#7985]
Type: <b>Bug</b>

With Dev Containers 0.275.0, 0.275.1, or (pre-release) 0.277.
Exit any running containers, then do "Open Folder in Container..." from the green "><" remoting button, or "Dev Containers: Open Folder in Container..." from the command palette. Select a folder with a dev container setup. The container does not open, and after a moment we're getting an error in the Extension Host output, along the lines of
```
2023-02-06 17:49:52.333 [error] Error: Illegal argument: base
	at v (c:\Users\ralexander72\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:7:1267)
	at new ei (c:\Users\ralexander72\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:44917)
	at Wne (c:\Users\ralexander72\.vscode\extensions\ms-vscode-remote.remote-containers-0.275.1\dist\extension\extension.js:337:23068)
	at hE (c:\Users\ralexander72\.vscode\extensions\ms-vscode-remote.remote-containers-0.275.1\dist\extension\extension.js:337:20963)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async v2 (c:\Users\ralexander72\.vscode\extensions\ms-vscode-remote.remote-containers-0.275.1\dist\extension\extension.js:337:20365)
	at async s.h (c:\Users\ralexander72\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108008) remote-containers.openFolder {"value":"ms-vscode-remote.remote-containers","c":"ms-vscode-remote.remote-containers"}
```

This does *not* happen when opening the same container from the Recents list. That works fine. Opening the folder and then doing "Reopen in Container" produces the same failure, though.

I'm not sure whether it makes a difference, but we're running Docker under WSL, with the containers located under the WSL filesystem (paths such as \\\\wsl$\Ubuntu-20.04\home\ralexander72\my_workspace). 

Extension version: 0.275.1
VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

**Comment by rjra100** [comment]
Looks like the same issue as https://github.com/microsoft/vscode-dev-containers/issues/1711. I've repeatedly installed, uninstalled, reinstalled the Dev Containers extension, though; consistently seeing this issue with everything from 0.275.0 on.

**Comment by rjra100** [comment]
Sorry, also a dup of https://github.com/microsoft/vscode-remote-release/issues/7978. Will add additional info there.
