### ISSUE TITLE
Remote Switcher never shows up once it is hidden

### ISSUE THREAD

**Issue by nobchika** [microsoft/vscode-remote-release#7988]
Type: <b>Bug</b>

The remote switcher, which allow users to choose remote source among SSH, WSL and Docker, never shows up once it is hidden:

1. In the Remote Explorer, right-click on the remote switcher and select "Hide Switch Remote" to hide it
2. Click on the three dots next to the title of Remote Explorer and choose "Switch Remote"
3. An error message "Cannot read properties of undefined (reading 'length')" shows up in the right bottom.

This is the error message from the developer tools:

```
workbench.desktop.main.js:747 TypeError: Cannot read properties of undefined (reading 'length')
    at set targetType [as targetType] (workbench.desktop.main.js:1883:30477)
    at Object.set (workbench.desktop.main.js:611:3536)
    at a.run (workbench.desktop.main.js:2540:23460)
    at handler (workbench.desktop.main.js:642:17301)
    at o.invokeFunction (workbench.desktop.main.js:611:360)
    at v.k (workbench.desktop.main.js:1552:2710)
    at v.executeCommand (workbench.desktop.main.js:1552:2272)
    at fr.run (workbench.desktop.main.js:642:16512)
    at L.runAction (workbench.desktop.main.js:86:14925)
    at L.run (workbench.desktop.main.js:86:14836)
    at r.onClick (workbench.desktop.main.js:182:11387)
    at workbench.desktop.main.js:182:41777
c @ workbench.desktop.main.js:747
```

Extension version: 0.2.0
VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.0-58-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1260P (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|47.70GB (16.25GB free)|
|Process Argv|--crash-reporter-id 13876372-e9eb-4d0a-b840-5fd052aed7c2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: docsoup|
|OS|Linux x64 5.15.0-58-generic|
|CPUs|Intel(R) Core(TM) i7-4790T CPU @ 2.70GHz (4 x 2693)|
|Memory (System)|7.76GB (4.24GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
pyind779cf:30657577
89544117:30613380
pythonsymbol12:30657548
2i9eh265:30646982

```

</details>

**Comment by nobchika** [comment]
I'm using the latest version, and tested on three different Windows environment, and any of these shows the symptom. Also, the insiders' version has the same problem. As this is a little bit inconvenient, if anybody knows a quick work-around, please let me know.

**Comment by nobchika** [comment]
`ctrl+p` and `> View: Reset All Menus` solved the problem.
