### ISSUE TITLE
[Remote-SSH Bug]: Remote-SSH + Javascript Debugger kills all connectivity on remote server

### ISSUE THREAD

**Issue by SomervilleTom** [microsoft/vscode-remote-release#7989]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

I expect whatever SSH connectivity VSCode needs to be gracefully managed by VSCode without impact on VSCode itself and certainly without disabling all connectivity to the server for every SSH connection (including `root`).

### Steps To Reproduce

1. Open `Remote-SSH` and Javascript Debugger on `React` app
2. Open terminal window and type `yarn start`.
3. Wait for initial chrome browser to open. Close it
4. Wait for successful Javascript compilation to finish.
5. Click on "Launch Chrome" from the "Run and Debug" view
6. Interact with the resulting browser

### Remote-SSH Logs

<details>
<summary>Remote-SSH Logs</summary>
<p>

Example 1 (`remote-agent.log`, episode 1)
```
2023-02-07 00:05:49.459 [warning] No ptyHost heartbeat after 6 seconds
2023-02-07 00:06:15.455 [warning] No ptyHost heartbeat after 6 seconds
2023-02-07 00:06:30.182 [warning] No ptyHost heartbeat after 6 seconds
2023-02-07 00:06:53.325 [info] [127.0.0.1][50b95e87][ExtensionHostConnection] The client has reconnected.
2023-02-07 00:06:54.467 [error] CodeExpectedError: Could not find pty on pty host
    at S.L (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:6839)
    at S.updateIcon (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:2680)
    at Object.call (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:17:5043)
    at r.s (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:5412)
    at r.q (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4915)
    at /home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4326
    at invoke (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at E.deliver (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:2033)
    at c.fire (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:1671)
    at process.F (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:9:20881)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2023-02-07 00:06:59.023 [error] CodeExpectedError: Could not find pty on pty host
    at S.L (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:6839)
    at S.updateTitle (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:2630)
    at Object.call (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:17:5043)
    at r.s (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:5412)
    at r.q (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4915)
    at /home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4326
    at invoke (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at E.deliver (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:2033)
    at c.fire (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:1671)
    at process.F (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:9:20881)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2023-02-07 00:07:00.032 [error] CodeExpectedError: Could not find pty on pty host
    at S.L (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:6839)
    at S.updateTitle (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:2630)
    at Object.call (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:17:5043)
    at r.s (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:5412)
    at r.q (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4915)
    at /home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4326
    at invoke (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at E.deliver (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:2033)
    at c.fire (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:1671)
    at process.F (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:9:20881)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2023-02-07 00:07:04.388 [info] [127.0.0.1][8ba70ecc][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
```

Example 2:
```
2023-02-07 16:20:16.340 [warning] No ptyHost heartbeat after 6 seconds
2023-02-07 16:21:00.479 [warning] No ptyHost heartbeat after 6 seconds
2023-02-07 16:21:23.125 [warning] No ptyHost heartbeat after 6 seconds
2023-02-07 16:21:23.210 [info] [127.0.0.1][747bb2c2][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
2023-02-07 16:21:24.238 [error] CodeExpectedError: Could not find pty on pty host
    at S.L (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:6839)
    at S.updateIcon (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:2680)
    at Object.call (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:17:5043)
    at r.s (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:5412)
    at r.q (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4915)
    at /home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4326
    at invoke (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at E.deliver (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:2033)
    at c.fire (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:1671)
    at process.F (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:9:20881)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2023-02-07 16:21:24.242 [error] CodeExpectedError: Could not find pty on pty host
    at S.L (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:6839)
    at S.updateTitle (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:2630)
    at Object.call (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:17:5043)
    at r.s (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:5412)
    at r.q (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4915)
    at /home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4326
    at invoke (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at E.deliver (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:2033)
    at c.fire (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:1671)
    at process.F (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:9:20881)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2023-02-07 16:21:24.242 [error] CodeExpectedError: Could not find pty on pty host
    at S.L (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:6839)
    at S.updateTitle (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:2630)
    at Object.call (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:17:5043)
    at r.s (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:5412)
    at r.q (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4915)
    at /home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4326
    at invoke (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at E.deliver (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:2033)
    at c.fire (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:1671)
    at process.F (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:9:20881)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2023-02-07 16:21:24.624 [info] [127.0.0.1][fcd47c50][ExtensionHostConnection] <3038> Extension Host Process exited with code: 0, signal: null.
2023-02-07 16:21:24.626 [info] Last EH closed, waiting before shutting down
```

Relevant `exthost.log` (`exthost1/exthost.log`):
```
2023-02-07 16:21:24.241 [info] Extension host terminating: received terminate message from renderer
2023-02-07 16:21:24.479 [info] Lock '/home/tms/.vscode-server/data/User/workspaceStorage/e71344bf6e8903ea68569ac4346d49d2/vscode.lock
': Marking the lockfile as scheduled to be released in 6000 ms.
2023-02-07 16:21:24.489 [info] Extension host with pid 3038 exiting with code 0
```
</p>
</details>

### Anything else?

The server is a robust AWS EC2 instance with plenty of memory:
```
# grep MemTotal /proc/meminfo
MemTotal:       16016696 kB
```

I find no entries in `/var/log/messages` with a timestamp corresponding to the issue. I similarly see no complaints in `/var/log/sssd`. 

Here is the content of `journalctl` during the second hang logged above:
```
Feb 07 16:21:24 byron.zeetix.com sshd[4071]: Accepted publickey for tms from 73.16.152.225 port 63945 ssh2: ED25519 SHA256:h9SMFnZOH/T8z/R7P9PqhgceZulX9HBPSWlgKzQHrZg
Feb 07 16:21:24 byron.zeetix.com sshd[4071]: pam_unix(sshd:session): session opened for user tms by (uid=0)
Feb 07 16:21:24 byron.zeetix.com systemd[1]: Started Session 7 of user tms.
Feb 07 16:21:24 byron.zeetix.com systemd-logind[921]: New session 7 of user tms.
Feb 07 16:21:24 byron.zeetix.com systemd[1]: Created slice system-systemd\x2dcoredump.slice.
Feb 07 16:21:24 byron.zeetix.com systemd[1]: Started Process Core Dump (PID 4109/UID 0).
Feb 07 16:21:24 byron.zeetix.com systemd-coredump[4111]: Resource limits disable core dumping for process 3355 (node).
Feb 07 16:21:24 byron.zeetix.com systemd-coredump[4111]: Process 3355 (node) of user 1001 dumped core.
Feb 07 16:21:24 byron.zeetix.com systemd[1]: systemd-coredump@0-4109-0.service: Succeeded.
Feb 07 16:21:52 byron.zeetix.com sshd[2725]: pam_unix(sshd:session): session closed for user tms
Feb 07 16:21:52 byron.zeetix.com systemd-logind[921]: Session 3 logged out. Waiting for processes to exit.
```

The same code runs with no issues or complaints outside of VSCode.

This failure often happens while the app is doing several sequential invocations of `window.open`, setting `window.opener.document.location.href` , and calling `window.close`. It is also calling and handling inbound redirects from an Auth0 server. I'm developing authentication and authorization behavior for a public-facing site, and so I'm reluctant to share too much information about the information being passed to and from the authentication provider (Auth0).

I'm happy to have a private exchange with someone on the VSCode team if that's helpful.

Is anybody paying attention to this? It is a serious issue, I've provided reasonable documentation, it's been assigned, and I see no indication that anybody has even viewed it -- never mind begun investigating the issue.

**Comment by SomervilleTom** [comment]
Remote-SSH + Javascript debugger kills ALL connections on the remote server. While this is happening, no connections can be established to the remote server and all existing connections -- whether from vscode-server or from out-of-band SSH client connections -- are lost.

This only occurs after launching a Chrome browser from the Javascript Debugger on the remote system (using the "launch.json").

When this happens, `remote-agent.log` contains something like the following:
```
2023-02-07 00:05:49.459 [warning] No ptyHost heartbeat after 6 seconds
2023-02-07 00:06:15.455 [warning] No ptyHost heartbeat after 6 seconds
2023-02-07 00:06:30.182 [warning] No ptyHost heartbeat after 6 seconds
2023-02-07 00:06:53.325 [info] [127.0.0.1][50b95e87][ExtensionHostConnection] The client has reconnected.
2023-02-07 00:06:54.467 [error] CodeExpectedError: Could not find pty on pty host
    at S.L (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:6839)
    at S.updateIcon (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:2680)
    at Object.call (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:17:5043)
    at r.s (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:5412)
    at r.q (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4915)
    at /home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4326
    at invoke (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at E.deliver (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:2033)
    at c.fire (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:1671)
    at process.F (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:9:20881)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2023-02-07 00:06:59.023 [error] CodeExpectedError: Could not find pty on pty host
    at S.L (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:6839)
    at S.updateTitle (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:2630)
    at Object.call (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:17:5043)
    at r.s (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:5412)
    at r.q (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4915)
    at /home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4326
    at invoke (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at E.deliver (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:2033)
    at c.fire (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:1671)
    at process.F (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:9:20881)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2023-02-07 00:07:00.032 [error] CodeExpectedError: Could not find pty on pty host
    at S.L (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:6839)
    at S.updateTitle (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:2630)
    at Object.call (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:17:5043)
    at r.s (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:5412)
    at r.q (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4915)
    at /home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4326
    at invoke (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at E.deliver (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:2033)
    at c.fire (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:1671)
    at process.F (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:9:20881)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2023-02-07 00:07:04.388 [info] [127.0.0.1][8ba70ecc][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
```

The server is a robust AWS EC2 instance:
```
# grep MemTotal /proc/meminfo
MemTotal:       16016696 kB
```

I don't know if the above complaint ("No ptyHost heartbeat after 6 seconds") is a cause or a symptom. I do know that this only happens during the above scenario -- running VSCode, launching a Chrome browser, and using the Javascript Debugger.

The same code runs without issue after a "yarn build" and deployment. It is therefore specific to the development environment.

**Comment by SomervilleTom** [comment]
Just happened again. Connectivity was lost at 16:20 UTC, restored by 16:23 UTC.

Here is the relevant excerpt from `remoteagent.log`:
```
2023-02-07 16:20:16.340 [warning] No ptyHost heartbeat after 6 seconds
2023-02-07 16:21:00.479 [warning] No ptyHost heartbeat after 6 seconds
2023-02-07 16:21:23.125 [warning] No ptyHost heartbeat after 6 seconds
2023-02-07 16:21:23.210 [info] [127.0.0.1][747bb2c2][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
2023-02-07 16:21:24.238 [error] CodeExpectedError: Could not find pty on pty host
    at S.L (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:6839)
    at S.updateIcon (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:2680)
    at Object.call (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:17:5043)
    at r.s (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:5412)
    at r.q (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4915)
    at /home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4326
    at invoke (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at E.deliver (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:2033)
    at c.fire (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:1671)
    at process.F (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:9:20881)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2023-02-07 16:21:24.242 [error] CodeExpectedError: Could not find pty on pty host
    at S.L (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:6839)
    at S.updateTitle (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:2630)
    at Object.call (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:17:5043)
    at r.s (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:5412)
    at r.q (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4915)
    at /home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4326
    at invoke (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at E.deliver (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:2033)
    at c.fire (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:1671)
    at process.F (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:9:20881)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2023-02-07 16:21:24.242 [error] CodeExpectedError: Could not find pty on pty host
    at S.L (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:6839)
    at S.updateTitle (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:27:2630)
    at Object.call (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:17:5043)
    at r.s (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:5412)
    at r.q (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4915)
    at /home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:15:4326
    at invoke (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at E.deliver (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:2033)
    at c.fire (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:11:1671)
    at process.F (/home/tms/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/platform/terminal/node/ptyHostMain.js:9:20881)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
2023-02-07 16:21:24.624 [info] [127.0.0.1][fcd47c50][ExtensionHostConnection] <3038> Extension Host Process exited with code: 0, signal: null.
2023-02-07 16:21:24.626 [info] Last EH closed, waiting before shutting down
```

Here is `exthost1/exthost.log`:
```
2023-02-07 16:21:24.241 [info] Extension host terminating: received terminate message from renderer
2023-02-07 16:21:24.479 [info] Lock '/home/tms/.vscode-server/data/User/workspaceStorage/e71344bf6e8903ea68569ac4346d49d2/vscode.lock
': Marking the lockfile as scheduled to be released in 6000 ms.
2023-02-07 16:21:24.489 [info] Extension host with pid 3038 exiting with code 0
```

This failure happened while the app is doing several sequential invocations of `window.open`  and handling inbound redirects from an Auth0 server. I'm developing authentication and authorization behavior for a public-facing site, and so I'm reluctant to share too much information about the information being passed to and from external sites.

I'm happy to have a private exchange with someone on the VSCode team if that's helpful.

I do hope that somebody is paying attention, this is a major hassle.

**Comment by roblourens** [comment]
I'll follow up on the vscode issue
