### ISSUE TITLE
`HTTP 407: authenticationrequired` when attempting to connect to remote container across SSH

### ISSUE THREAD

**Issue by Spitfire1900** [microsoft/vscode-remote-release#7994]
When attempting to connect to use the command `Dev Containers: Reopen in Container` to [set up a remote container](https://code.visualstudio.com/remote/advancedcontainers/develop-remote-host#_connect-using-the-remote-ssh-extension-recommended) the following error appears.

- VSCode Version: 1.75.0 (user setup)
- Local OS Version: Windows 10
- Remote OS Version: Red Hat Enterprise Linux release 8.7 (Ootpa)
- Remote Extension/Connection Type: Container on remote SSH

- Logs:
```
2023-02-07 09:08:28.799 [error] Error: HTTP 407: authenticationrequired
	at On.<anonymous> (c:\Users\***\.vscode\extensions\ms-vscode-remote.remote-containers-0.275.1\dist\extension\extension.js:266:36639)
	at On.emit (node:events:526:28)
	at On.emit (node:events:526:28)
	at On._processResponse (c:\Users\***\.vscode\extensions\ms-vscode-remote.remote-containers-0.275.1\dist\extension\extension.js:9:4685)
	at On._onNativeResponse (c:\Users\***\.vscode\extensions\ms-vscode-remote.remote-containers-0.275.1\dist\extension\extension.js:9:1350)
	at Object.onceWrapper (node:events:646:26)
	at ClientRequest.emit (node:events:538:35)
	at HTTPParser.parserOnIncomingClient (node:_http_client:618:27)
	at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
	at Socket.socketOnData (node:_http_client:482:22)
	at Socket.emit (node:events:526:28)
	at Readable.read (node:internal/streams/readable:527:10)
	at Socket.read (node:net:644:39)
	at flow (node:internal/streams/readable:1011:34)
	at resume_ (node:internal/streams/readable:992:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21) remote-containers.reopenInContainer {"value":"ms-vscode-remote.remote-containers","c":"ms-vscode-remote.remote-containers"
```

Steps to Reproduce:

1. Have the Docker extension installed in addition to the Remote Development extension pack
1. Create the following setting in your local user settings.json
```json
"docker.environment": {
  "DOCKER_HOST": "ssh://username@remotevm.example.com"
}
```
2. Connect to the remote SSH server (set up pubkey auth so you don't get prompted for password)
3. In my case it is network isolated so it can only connect to a few internal resources; The `remote.SSH.localServerDownload: auto` lets the connection still occur.
4. Have podman installed (we don't allow docker) and available at `/usr/bin/podman`.
5. Symlink docker to podman ` ln -s /usr/bin/podman ./.local/bin/docker`
6. Create a folder and add the follwing `.vscode/devcontainer.json`
```json
{
    "image": "library/hello-world", // Or "dockerFile"
    "workspaceFolder": "/workspace",
    "workspaceMount": "source=remote-workspace,target=/workspace,type=volume"
}
```
7. Set up the following on ` ~/.config/containers/registries.conf` so that artifacts can be resolved by podman:
```
unqualified-search-registries=["artifactory.example.com"]
```
7. Open the folder using the `File: Open Folder` command
8. Run the `Dev Containers: Reopen in Container` command

**Comment by chrmarti** [comment]
The Dev Containers extension downloads the VS Code Server locally, it does not support downloading it remotely.
