### ISSUE TITLE
Remote SSH blocks while creating connection

### ISSUE THREAD

**Issue by Longman-Stan** [microsoft/vscode-remote-release#8051]
Hello! 
   Sorry for the delay. I see I cannot reply on the older conversation. The problem still persists.

"Click on the `Vie`w menu at the very top of your computer screen, then select `Output` from the dropdown, and then select `Remote-SSH` from the output dropdown on the top right of the `Output` window." 

_Originally posted by @eleanorjboyd in https://github.com/microsoft/vscode-remote-release/issues/7691#issuecomment-1372566447_

Here is the full log:

[17:06:20.164] Log Level: 1
[17:06:20.170] SSH Resolver called for "ssh-remote+windows", attempt 1
[17:06:20.170] "remote.SSH.useLocalServer": true
[17:06:20.170] "remote.SSH.path": undefined
[17:06:20.170] "remote.SSH.configFile": undefined
[17:06:20.170] "remote.SSH.useFlock": true
[17:06:20.170] "remote.SSH.lockfilesInTmp": false
[17:06:20.170] "remote.SSH.localServerDownload": always
[17:06:20.170] "remote.SSH.remoteServerListenOnSocket": false
[17:06:20.170] "remote.SSH.showLoginTerminal": true
[17:06:20.171] "remote.SSH.defaultExtensions": []
[17:06:20.171] "remote.SSH.loglevel": 1
[17:06:20.171] "remote.SSH.enableDynamicForwarding": true
[17:06:20.171] "remote.SSH.enableRemoteCommand": false
[17:06:20.171] "remote.SSH.serverPickPortsFromRange": {}
[17:06:20.171] "remote.SSH.serverInstallPath": {}
[17:06:20.172] VS Code version: 1.73.1
[17:06:20.172] Remote-SSH version: remote-ssh@0.97.2023020215
[17:06:20.172] darwin arm64
[17:06:20.173] SSH Resolver called for host: windows
[17:06:20.173] Setting up SSH remote "windows"
[17:06:20.174] Acquiring local install lock: /var/folders/3m/2nn45szd49l8x89mmxp7nzcm0000gq/T/vscode-remote-ssh-d59726ea-install.lock
[17:06:20.175] Looking for existing server data file at /Users/***/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-d59726ea-6261075646f055b99068d3688932416f2346dd3b-0.97.2023020215/data.json
[17:06:20.175] Using commit id "6261075646f055b99068d3688932416f2346dd3b" and quality "stable" for server
[17:06:20.177] Install and start server if needed
[17:06:20.178] PATH: /Users/***/.nvm/versions/node/v12.22.10/bin:/opt/miniconda3/bin:/opt/miniconda3/condabin:/Users/***/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[17:06:20.178] Checking ssh with "ssh -V"
[17:06:20.185] > OpenSSH_8.6p1, LibreSSL 3.3.6

[17:06:20.186] askpass server listening on /var/folders/3m/2nn45szd49l8x89mmxp7nzcm0000gq/T/vscode-ssh-askpass-14c8011dadaa6c37a7c5e2f8f6d3fb8a2c7717b0.sock
[17:06:20.187] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/3m/2nn45szd49l8x89mmxp7nzcm0000gq/T/vscode-ssh-askpass-34e2295959fa75770455f34ec2cb3e4dfbd93e23.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","53569","-o","ConnectTimeout=60","windows","powershell"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/***/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-d59726ea-6261075646f055b99068d3688932416f2346dd3b-0.97.2023020215/data.json"}
[17:06:20.187] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.wdsPEvozkf/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/***/.vscode/extensions/ms-vscode-remote.remote-ssh-0.97.2023020215/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/***/.vscode/extensions/ms-vscode-remote.remote-ssh-0.97.2023020215/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/3m/2nn45szd49l8x89mmxp7nzcm0000gq/T/vscode-ssh-askpass-14c8011dadaa6c37a7c5e2f8f6d3fb8a2c7717b0.sock"}
[17:06:20.188] Spawned 50828
[17:06:20.256] > local-server-1> Running ssh connection command: "-v -T -D 53569 -o ConnectTimeout=60 windows powershell"
[17:06:20.259] > local-server-1> Spawned ssh, pid=50836
[17:06:20.264] stderr> OpenSSH_8.6p1, LibreSSL 3.3.6
[17:06:20.264] stderr> debug1: Reading configuration data /Users/***/.ssh/config
[17:06:20.264] stderr> debug1: /Users/***/.ssh/config line 1: Applying options for windows
[17:06:20.265] stderr> debug1: Reading configuration data /etc/ssh/ssh_config
[17:06:20.265] stderr> debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
[17:06:20.265] stderr> debug1: /etc/ssh/ssh_config line 54: Applying options for *
[17:06:20.265] stderr> debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
[17:06:20.265] stderr> debug1: Connecting to *** [***] port 22.
[17:06:20.272] stderr> debug1: fd 3 clearing O_NONBLOCK
[17:06:20.272] stderr> debug1: Connection established.
[17:06:20.272] stderr> debug1: identity file /Users/***/.ssh/id_rsa type -1
[17:06:20.272] stderr> debug1: identity file /Users/***/.ssh/id_rsa-cert type -1
[17:06:20.272] stderr> debug1: identity file /Users/***/.ssh/id_dsa type -1
[17:06:20.272] stderr> debug1: identity file /Users/***/.ssh/id_dsa-cert type -1
[17:06:20.272] stderr> debug1: identity file /Users/***/.ssh/id_ecdsa type -1
[17:06:20.272] stderr> debug1: identity file /Users/***/.ssh/id_ecdsa-cert type -1
[17:06:20.272] stderr> debug1: identity file /Users/***/.ssh/id_ecdsa_sk type -1
[17:06:20.272] stderr> debug1: identity file /Users/***/.ssh/id_ecdsa_sk-cert type -1
[17:06:20.272] stderr> debug1: identity file /Users/***/.ssh/id_ed25519 type 3
[17:06:20.272] stderr> debug1: identity file /Users/***/.ssh/id_ed25519-cert type -1
[17:06:20.272] stderr> debug1: identity file /Users/***/.ssh/id_ed25519_sk type -1
[17:06:20.272] stderr> debug1: identity file /Users/***/.ssh/id_ed25519_sk-cert type -1
[17:06:20.273] stderr> debug1: identity file /Users/***/.ssh/id_xmss type -1
[17:06:20.273] stderr> debug1: identity file /Users/***/.ssh/id_xmss-cert type -1
[17:06:20.273] stderr> debug1: Local version string SSH-2.0-OpenSSH_8.6
[17:06:20.515] stderr> debug1: Remote protocol version 2.0, remote software version OpenSSH_for_Windows_7.7
[17:06:20.515] stderr> debug1: compat_banner: match: OpenSSH_for_Windows_7.7 pat OpenSSH* compat 0x04000000
[17:06:20.515] stderr> debug1: Authenticating to ***:22 as '***'
[17:06:20.527] stderr> debug1: load_hostkeys: fopen /Users/***/.ssh/known_hosts2: No such file or directory
[17:06:20.527] stderr> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
[17:06:20.527] stderr> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
[17:06:20.527] stderr> debug1: SSH2_MSG_KEXINIT sent
[17:06:20.670] stderr> debug1: SSH2_MSG_KEXINIT received
[17:06:20.671] stderr> debug1: kex: algorithm: curve25519-sha256
[17:06:20.671] stderr> debug1: kex: host key algorithm: ssh-ed25519
[17:06:20.671] stderr> debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
[17:06:20.671] stderr> debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
[17:06:20.672] stderr> debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
[17:06:20.697] stderr> debug1: SSH2_MSG_KEX_ECDH_REPLY received
[17:06:20.697] stderr> debug1: Server host key: ssh-ed25519 SHA256:XMtBd9sLedLzsDjX5yw6IwFZkVcTz38By7deHqBSNS8
[17:06:20.698] stderr> debug1: load_hostkeys: fopen /Users/***/.ssh/known_hosts2: No such file or directory
[17:06:20.698] stderr> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
[17:06:20.698] stderr> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
[17:06:20.698] stderr> debug1: Host '10.131.183.213' is known and matches the ED25519 host key.
[17:06:20.698] stderr> debug1: Found key in /Users/***/.ssh/known_hosts:12
[17:06:20.701] stderr> debug1: rekey out after 134217728 blocks
[17:06:20.701] stderr> debug1: SSH2_MSG_NEWKEYS sent
[17:06:20.701] stderr> debug1: expecting SSH2_MSG_NEWKEYS
[17:06:20.701] stderr> debug1: SSH2_MSG_NEWKEYS received
[17:06:20.701] stderr> debug1: rekey in after 134217728 blocks
[17:06:20.701] stderr> debug1: Will attempt key: /Users/***/.ssh/id_rsa 
[17:06:20.701] stderr> debug1: Will attempt key: /Users/***/.ssh/id_dsa 
[17:06:20.701] stderr> debug1: Will attempt key: /Users/***/.ssh/id_ecdsa 
[17:06:20.701] stderr> debug1: Will attempt key: /Users/***/.ssh/id_ecdsa_sk 
[17:06:20.701] stderr> debug1: Will attempt key: /Users/***/.ssh/id_ed25519 ED25519 SHA256:ahSfTjs/Gk9JWtgegFeA2I1ujFxyRmElhaAYpdf45/k
[17:06:20.701] stderr> debug1: Will attempt key: /Users/***/.ssh/id_ed25519_sk 
[17:06:20.701] stderr> debug1: Will attempt key: /Users/***/.ssh/id_xmss 
[17:06:20.702] stderr> debug1: SSH2_MSG_EXT_INFO received
[17:06:20.702] stderr> debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
[17:06:20.773] stderr> debug1: SSH2_MSG_SERVICE_ACCEPT received
[17:06:20.790] stderr> debug1: Authentications that can continue: publickey,password,keyboard-interactive
[17:06:20.790] stderr> debug1: Next authentication method: publickey
[17:06:20.790] stderr> debug1: Trying private key: /Users/***/.ssh/id_rsa
[17:06:20.790] stderr> debug1: Trying private key: /Users/***/.ssh/id_dsa
[17:06:20.790] stderr> debug1: Trying private key: /Users/***/.ssh/id_ecdsa
[17:06:20.790] stderr> debug1: Trying private key: /Users/***/.ssh/id_ecdsa_sk
[17:06:20.790] stderr> debug1: Offering public key: /Users/***/.ssh/id_ed25519 ED25519 SHA256:ahSfTjs/Gk9JWtgegFeA2I1ujFxyRmElhaAYpdf45/k
[17:06:20.800] stderr> debug1: Authentications that can continue: publickey,password,keyboard-interactive
[17:06:20.800] stderr> debug1: Trying private key: /Users/***/.ssh/id_ed25519_sk
[17:06:20.800] stderr> debug1: Trying private key: /Users/***/.ssh/id_xmss
[17:06:20.800] stderr> debug1: Next authentication method: keyboard-interactive
[17:06:20.806] stderr> debug1: Authentications that can continue: publickey,password,keyboard-interactive
[17:06:20.806] stderr> debug1: Next authentication method: password
[17:06:20.806] stderr> debug1: read_passphrase: can't open /dev/tty: Device not configured
[17:06:20.889] Got askpass request: {"request":"***@***'s password:"}
[17:06:20.890] Showing password prompt
[17:06:20.890] Listening for interwindow password on /var/folders/3m/2nn45szd49l8x89mmxp7nzcm0000gq/T/vscode-ssh-askpass-15b282f67d044013ae9d458621caffb62966a8c0.sock
[17:06:20.890] Writing password prompt to globalState
[17:06:24.488] Got password response
[17:06:24.489] Interactor gave response: **********
[17:06:24.489] Cleaning up other-window auth server
[17:06:24.561] stderr> debug1: Authentication succeeded (password).
[17:06:24.561] stderr> Authenticated to 10.131.183.213 ([10.131.183.213]:22).
[17:06:24.561] stderr> debug1: Local connections to LOCALHOST:53569 forwarded to remote address socks:0
[17:06:24.561] stderr> debug1: Local forwarding listening on 127.0.0.1 port 53569.
[17:06:24.561] stderr> debug1: channel 0: new [port listener]
[17:06:24.562] stderr> debug1: Local forwarding listening on ::1 port 53569.
[17:06:24.562] stderr> debug1: channel 1: new [port listener]
[17:06:24.562] stderr> debug1: channel 2: new [client-session]
[17:06:24.562] stderr> debug1: Requesting no-more-sessions@openssh.com
[17:06:24.562] stderr> debug1: Entering interactive session.
[17:06:24.562] stderr> debug1: pledge: filesystem full
[17:06:24.688] stderr> debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
[17:06:24.690] stderr> debug1: client_input_hostkeys: searching /Users/***/.ssh/known_hosts for 10.131.183.213 / (none)
[17:06:24.700] stderr> debug1: client_input_hostkeys: searching /Users/***/.ssh/known_hosts2 for 10.131.183.213 / (none)
[17:06:24.701] stderr> debug1: client_input_hostkeys: hostkeys file /Users/***/.ssh/known_hosts2 does not exist
[17:06:24.701] stderr> debug1: client_input_hostkeys: host key found matching a different name/address, skipping UserKnownHostsFile update
[17:06:24.701] stderr> debug1: Sending environment.
[17:06:24.701] stderr> debug1: Sending command: powershell
[17:06:24.978] > Windows PowerShell
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Try the new cross-platform PowerShell https://aka.ms/pscore6
[17:06:26.165] stderr> Loading personal and system profiles took 888ms.
[17:06:26.239] > (base) 
[17:06:26.249] > PS C:\Users\***> 
[17:06:26.363] > echo 'ready: 9c25a0f8085b'
> ready: 9c25a0f8085b
[17:06:26.372] > (base) 
[17:06:26.374] > PS C:\Users\***> 
[17:06:26.377] > uname -rsv
[17:06:26.964] > CYGWIN_NT-10.0 3.3.4(0.341/5/3) 2022-01-31 19:35
[17:06:26.978] > (base) PS C:\Users\***> 
[17:07:26.494] Terminating local server
[17:07:26.505] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (/Users/vlad-constantinlungu-stan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.97.2023020215/out/extension.js:1:584273)
	at Timeout._onTimeout (/Users/vlad-constantinlungu-stan/.vscode/extensions/ms-vscode-remote.remote-ssh-0.97.2023020215/out/extension.js:1:629573)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[17:07:26.512] Local server exit: 15
[17:07:26.514] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"1","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Timeout","exitCodeLabel":""},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":66330,"timing.preSshTime":17}}
[17:07:26.517] ------

**Comment by eleanorjboyd** [comment]
Hello! Thank you for these logs, it seems the connect initally worked and then cut off. Can you send your windows logs, these might be more helpful since the connection did succeed at one point. You can get the windows logs by doing mostly the same steps as before `view`, `output` then just select `window` from the dropdown instead of ssh. Thanks!

**Comment by Longman-Stan** [comment]
Here it is:
2023-02-15 19:39:42.356 [critical] Extension 'ms-toolsai.jupyter' wants API proposal 'notebookDebugOptions' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-02-15 19:39:45.706 [info] [perf] Render performance baseline is 22ms
2023-02-15 19:39:55.916 [info] [attempt 1] Invoking resolveAuthority(ssh-remote)
2023-02-15 19:39:56.140 [critical] Extension 'ms-toolsai.jupyter' wants API proposal 'notebookDebugOptions' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-02-15 19:40:33.290 [error] [attempt 1] resolveAuthority(ssh-remote) returned an error after 37088 ms {"name":"CodeExpectedError","_message":"Connecting with SSH timed out","_code":"TemporarilyNotAvailable","isHandled":false}

**Comment by eleanorjboyd** [comment]
Hi! So I notice you are connecting via CYGIN, do you want your remote type to be Linux or Windows? Can you try with `use local server mode = false` and see if this helps. Thanks

**Comment by Longman-Stan** [comment]
Hi, Eleanor! 
The remote type should be Windows. I'm not sure where CYGIN comes from. 
Using local server mode = false seems to work, but I'd rather use the server locally. 
The thing is it used to work with local server mode = true. I'm not sure what's changed.

**Comment by eleanorjboyd** [comment]
When was the last time it worked with local server mode?

**Comment by eleanorjboyd** [comment]
Hi! So what happens on local server mode that is different from non local server mode is we infer your platform based on output where as in non local server mode we explicitly ask for your platform type (and have the user enter it). Therefore what platform type are you selecting during non-local server mode? You should then explicitly set this value in your settings since local server mode will take this value over a detected platform if set. Secondly just let me know the type because I am also going to change it so our script recognizes CYGIN and sets a platform type based on that output. 

Thanks

**Comment by Longman-Stan** [comment]
> When was the last time it worked with local server mode?

More than half an year ago, when I've first started the previous thread. Quite hard to remember details, I'm afraid. 

I select Windows. And it works.  By "explicitly set this value in your settings" we're talking about this?

<img width="932" alt="image" src="https://user-images.githubusercontent.com/48775757/221799828-d653da38-2253-41bb-9a99-7fa0ea709352.png">

If so, even if it's set, with use_local_server = True it blocks, as described.

**Comment by eleanorjboyd** [comment]
Hi! Yes this is the setting, the item should be the remote hostname- not sure if that is also windows. so item = remote host name, value = windows. Let me know if that works

**Comment by Longman-Stan** [comment]
That setting got completed when I've connected using non-local server mode, when it successfully connected. Should I change anything in this case?
It doesn't work, though. The problem persists.

**Comment by eleanorjboyd** [comment]
What happens if you set the value = linux instead of mac? Also can you include logs from your run where you included that remote platform setting? Thanks

**Comment by Longman-Stan** [comment]
Setting it to linux did not change anything (in the settings it also says it's not currently used :-?)

The logs don't change:
"""
2023-03-15 11:32:43.542 [error] [LocalProcess0][resolveAuthority(ssh-remote,1)][37348ms] returned an error {"code":"NotAvailable","message":"Connecting with SSH timed out","detail":true}
2023-03-15 11:32:43.542 [error] resolveAuthority(ssh-remote) returned an error after 37348 ms {"name":"CodeExpectedError","_message":"Connecting with SSH timed out","_code":"NotAvailable","_detail":true,"isHandled":true}
2023-03-15 11:32:43.543 [error] Error received from starting extension host (kind: Remote)
2023-03-15 11:32:43.543 [error] CodeExpectedError: Connecting with SSH timed out
    at $c.wc (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2607:5936)
    at async $c.Ac (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2607:6948)
    at async $c.Zb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2607:8106)
    at async $c.xb (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2605:19494)
2023-03-15 11:32:43.543 [error] [remote-connection][attempt 1] An error occurred in initial connection! Will retry... Error:
2023-03-15 11:32:43.543 [error] CodeExpectedError: Connecting with SSH timed out
"""
"""
[11:32:11.447] stderr> debug1: Sending environment.
[11:32:11.447] stderr> debug1: Sending command: powershell
[11:32:11.769] > Windows PowerShell
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Try the new cross-platform PowerShell https://aka.ms/pscore6
[11:32:13.892] stderr> Loading personal and system profiles took 1794ms.
[11:32:13.948] > (base) 
[11:32:13.958] > PS C:\Users\*> 
[11:32:14.149] > e
[11:32:14.149] > cho 'ready: 7813f484102c'
[11:32:14.151] > ready: 7813f484102c
[11:32:14.183] > (base) PS C:\Users\*> uname -rsv
[11:32:14.308] > CYGWIN_NT-10.0 3.3.4(0.341/5/3) 2022-01-31 19:35
[11:32:14.319] > (base) PS C:\Users\*> 
[11:32:43.258] Terminating local server
[11:32:43.262] Resolver error: Error: Connecting with SSH timed out
	at m.Timeout (/Users/*/.vscode/extensions/ms-vscode-remote.remote-ssh-0.99.2023030315/out/extension.js:1:584648)
	at Timeout._onTimeout (/Users/*/.vscode/extensions/ms-vscode-remote.remote-ssh-0.99.2023030315/out/extension.js:1:630634)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[11:32:43.263] Local server exit: 15
[11:32:43.264] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"1","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Timeout","exitCodeLabel":""},"measures":{"resolveAttempts":1,"timing.totalResolveTime":37093,"timing.preSshTime":23}}
[11:32:43.268] ------
"""

**Comment by eleanorjboyd** [comment]
Hi! I am just going to go ahead and hardcode cygwin in as a remote OS type that then maps to windows- this should resolve your problem as it adds cygwin as a specific case in our extension. THanks!

**Comment by Longman-Stan** [comment]
Hi! Thank you! 
Please tell me if I can aid with anything.

**Comment by Longman-Stan** [comment]
@eleanorjboyd so an update of VS Code should get it to work as intended?

**Comment by eleanorjboyd** [comment]
vscode insider will have the fix which you can download [here](https://code.visualstudio.com/insiders/). Otherwise, the fix will be out in about a month to vscode stable. If you could test it out on insiders and let me know it works that would be very helpful. Thanks!
