### ISSUE TITLE
[Remote-SSH Bug]: 

### ISSUE THREAD

**Issue by soletian11** [microsoft/vscode-remote-release#8066]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

I'm trying to use WSL Ubuntu 20.04.5 LTS (GNU/Linux 5.15.0-1029-gcp x86_64) on my windows laptop and created  public key and private on ubuntu in ssh directory .
gpc and gpc.pub were created using command :ssh-keygen -t rsa -f gpc -C anand -b 2048 .
Then I created config file and use ssh <Host> to connect to gcp vm and works well. when I use code . and expected to show <hostname> with help remote ssh which is installed but it never shows in vscode.

I explicitly trying to connect by issuing  command   ssh -i ~/.ssh/gpc anand@35.202.254.15 and fails with public key permission denied.

### Expected Behavior

Need to connect gcp instances either using remote ssh config with hostname.

### Steps To Reproduce

1.Install Ubuntu 20.04.5 LTS (GNU/Linux 5.15.0-1029-gcp x86_64) on WSL2 on  Windows 11 Home
2.VS Code installed with remote ssh
3.SSH keys were generated using ssh-keygen -t rsa -f gpc -C anand -b 2048 
4.Create below config file and 
 Host gcloudvm
Hostname 35.202.254.15
User anand
IdentityFile /home/anand/.ssh/gpc
5.Opening code . from Ubuntu and I should see gcloudvm but nothing seen in settings.
6.But same connected using terminal in same vscode instance.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[0K[?25h"
[16:55:11.869] "install" terminal command done
[16:55:11.870] Install terminal quit with output:  ssh -i ~/.ssh/gpc anand@35.202.254.15: Permission denied (publickey).
[16:55:11.870] Received install output:  ssh -i ~/.ssh/gpc anand@35.202.254.15: Permission denied (publickey).
[16:55:11.870] Stopped parsing output early. Remaining text: ssh -i ~/.ssh/gpc anand@35.202.254.15: Permission denied (publickey).
[16:55:11.871] Resolver error: Error: Permission denied (publickey).
	at g.Create (c:\Users\anand\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:584147)
	at c:\Users\anand\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:582166
	at t.handleInstallOutput (c:\Users\anand\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:582683)
	at t.tryInstall (c:\Users\anand\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:680758)
	at async c:\Users\anand\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:643114
	at async t.withShowDetailsEvent (c:\Users\anand\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:646432)
	at async t.resolve (c:\Users\anand\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:644164)
	at async c:\Users\anand\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:721750
[16:55:11.874] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"0","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"PermissionDenied","exitCodeLabel":""},"measures":{"resolveAttempts":1,"retries":1,"timing.totalResolveTime":2746,"timing.preSshTime":1681,"timing.scriptTime":1065}}
[16:55:11.876] ------
```

</p>
</details>

**Comment by chrmarti** [comment]
@soletian11 Does `ssh gcloudvm` work in a terminal window in WSL?

@eleanorjboyd Would Remote-SSH show the `~/.ssh/config` entries of the current workspace folder's WSL distro?

**Comment by soletian11** [comment]
ssh gcloudvm works well in wsl -ubuntu terminal very well.

![image](https://user-images.githubusercontent.com/87721131/220383321-dba21d41-069d-4830-8ccd-c55542dfccef.png)


Remote -SSH does not show any config entries  of config file and below are entries of config file and remote-ssh.


**config file:**
![image](https://user-images.githubusercontent.com/87721131/220387738-20637070-fffc-4e36-add9-aec34d9e4ddf.png)


![image](https://user-images.githubusercontent.com/87721131/220385650-8788e4f0-7130-4151-b40e-cd8587bf81a9.png)




Also I created bat file in my windows folder with entries and below remote ssh json settings and added to "remote.SSH.path": Below are screen snippets.


**Batch File to redirect ssh :**
![image](https://user-images.githubusercontent.com/87721131/220386285-ca61c55d-a80f-4159-8825-83ed98fe34d2.png)

**JSON Settings:**

![image](https://user-images.githubusercontent.com/87721131/220386575-06eb8bfb-5dd0-4a95-aa26-529ba661b02b.png)

**Comment by eleanorjboyd** [comment]
> @eleanorjboyd Would Remote-SSH show the `~/.ssh/config` entries of the current workspace folder's WSL distro?

@roblourens could you answer this one? I am not very sure

**Comment by eleanorjboyd** [comment]
Hello! Currently we do not support this- here is an issue about it: https://github.com/microsoft/vscode-remote-release/issues/937. Follow there for information. Thanks!
