### ISSUE TITLE
[Remote-SSH Bug]: cannot find product.json

### ISSUE THREAD

**Issue by LunaJang** [microsoft/vscode-remote-release#8083]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [x] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

I was able to access the server without any problems until yesterday, but I suddenly couldn't access it today. After clearing both Extension and user setting, reinstalling the latest version of vscode does not solve the problem. All connections without using vscode were possible without any problems.

### Remote-SSH Log

[14:33:03.328] Log Level: 2
[14:33:03.412] SSH Resolver called for "ssh-remote+hulk", attempt 1
[14:33:03.417] "remote.SSH.useLocalServer": false
[14:33:03.422] "remote.SSH.showLoginTerminal": false
[14:33:03.423] "remote.SSH.remotePlatform": {}
[14:33:03.423] "remote.SSH.path": undefined
[14:33:03.424] "remote.SSH.configFile": undefined
[14:33:03.425] "remote.SSH.useFlock": true
[14:33:03.426] "remote.SSH.lockfilesInTmp": false
[14:33:03.427] "remote.SSH.localServerDownload": auto
[14:33:03.428] "remote.SSH.remoteServerListenOnSocket": false
[14:33:03.430] "remote.SSH.showLoginTerminal": false
[14:33:03.431] "remote.SSH.defaultExtensions": []
[14:33:03.434] "remote.SSH.loglevel": 2
[14:33:03.443] "remote.SSH.enableDynamicForwarding": true
[14:33:03.444] "remote.SSH.enableRemoteCommand": false
[14:33:03.445] "remote.SSH.serverPickPortsFromRange": {}
[14:33:03.445] "remote.SSH.serverInstallPath": {}
[14:33:03.481] VS Code version: 1.75.1
[14:33:03.484] Remote-SSH version: remote-ssh@0.96.0
[14:33:03.484] win32 x64
[14:33:03.496] SSH Resolver called for host: hulk
[14:33:03.496] Setting up SSH remote "hulk"
[14:33:03.519] Using commit id "441438abd1ac652551dbe4d408dfcec8a499b8bf" and quality "stable" for server
[14:33:03.573] Install and start server if needed
[14:33:05.282] Checking ssh with "ssh -V"
[14:33:05.419] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[14:33:05.434] Running script with connection command: ssh -T -D 65145 hulk bash
[14:33:05.443] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[14:33:09.317] > a543fd25abcd: running
> ]0;C:\WINDOWS\System32\cmd.exe
[14:33:09.318] Got some output, clearing connection timeout
[14:33:09.444] > Acquiring lock on /home/lunajang/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/vscode-remote-lock.lunajang.441438abd1ac652551dbe4d408dfcec8a499b8bf
[14:33:09.505] > Found old VS Code install 441438abd1ac652551dbe4d408dfcec8a499b8bf, attempting to clean up
[14:33:09.599] > Failed to acquire lock for install, not deleting: 441438abd1ac652551dbe4d408dfcec8a499b8bf
[14:33:09.646] > Found existing installation at /home/lunajang/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf...
> Checking /home/lunajang/.vscode-server/.441438abd1ac652551dbe4d408dfcec8a499b8bf.log and /home/lunajang/.vscode-server/.441438abd1ac652551dbe4d408dfcec8a499b8bf.pid for a running server
[14:33:09.661] > Looking for server with pid: 231827
[14:33:09.761] > Running ssh connection command... /home/lunajang/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all   &> "/home/lunajang/.vscode-server/.441438abd1ac652551dbe4d408dfcec8a499b8bf.log" < /dev/null
> printenv:
>     SSH_CONNECTION=■■■■■■■■
>     LANG=en_US.UTF-8
>     XDG_SESSION_ID=■■■■■■■■
>     USER=■■■■■■■■
>     PWD=■■■■■■■■
>     HOME=■■■■■■■■
>     SSH_CLIENT=■■■■■■■■
>     MAIL=■■■■■■■■
>     SHELL=/bin/bash
>     SHLVL=2
>     VSCODE_AGENT_FOLDER=/home/lunajang/.vscode-server
>     LOGNAME=lunajang
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1024/bus
>     XDG_RUNTIME_DIR=/run/user/1024
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
> s:/usr/local/games:/snap/bin
>     _=/usr/bin/printenv
[14:33:09.772] > 
[14:33:12.090] > Removing old logfile at /home/lunajang/.vscode-server/.441438abd1ac652551dbe4d40
> 08dfcec8a499b8bf.log
[14:33:12.101] > 
[14:33:13.271] > Spawned remote server: 232567
[14:33:13.290] > 
[14:33:13.437] > Waiting for server log...
[14:33:13.445] > 
[14:33:13.608] > Waiting for server log...
[14:33:13.617] > 
[14:33:14.039] > Waiting for server log...
[14:33:14.055] > 
[14:33:14.212] > Waiting for server log...
[14:33:14.226] > 
[14:33:14.333] > Waiting for server log...
[14:33:14.352] > 
[14:33:14.415] > Waiting for server log...
[14:33:14.431] > 
[14:33:14.926] > Waiting for server log...
[14:33:14.942] > 
[14:33:14.998] > Waiting for server log...
[14:33:15.020] > 
[14:33:15.137] > Waiting for server log...
[14:33:15.145] > 
[14:33:15.621] > Waiting for server log...
[14:33:15.634] > 
[14:33:15.674] > Waiting for server log...
[14:33:15.696] > 
[14:33:15.789] > Waiting for server log...
[14:33:15.806] > 
[14:33:16.286] > Waiting for server log...
[14:33:16.301] > 
[14:33:16.393] > Waiting for server log...
[14:33:16.409] > 
[14:33:16.445] > Waiting for server log...
[14:33:16.456] > 
[14:33:16.508] > Waiting for server log...
[14:33:16.519] > 
[14:33:16.968] > Waiting for server log...
[14:33:16.990] > 
[14:33:17.173] > Waiting for server log...
[14:33:17.186] > 
[14:33:17.363] > Waiting for server log...
[14:33:17.370] > 
[14:33:17.420] > Waiting for server log...
[14:33:17.432] > 
[14:33:17.534] > Waiting for server log...
[14:33:17.555] > 
[14:33:17.644] > Waiting for server log...
[14:33:17.665] > 
[14:33:17.735] > Waiting for server log...
[14:33:17.744] > 
[14:33:18.202] > Waiting for server log...
[14:33:18.214] > 
[14:33:18.328] > Waiting for server log...
[14:33:18.339] > 
[14:33:18.431] > Waiting for server log...
[14:33:18.449] > 
[14:33:18.541] > Waiting for server log...
[14:33:18.558] > 
[14:33:18.660] > Waiting for server log...
[14:33:18.668] > 
[14:33:18.746] > Waiting for server log...
[14:33:18.763] > 
[14:33:18.800] > Waiting for server log...
[14:33:18.810] > 
[14:33:18.948] > Waiting for server log...
[14:33:18.969] > 
[14:33:19.039] > Waiting for server log...
[14:33:19.049] > 
[14:33:19.179] > Waiting for server log...
[14:33:19.190] > 
[14:33:19.286] > Waiting for server log...
[14:33:19.296] > 
[14:33:19.355] > Waiting for server log...
[14:33:19.374] > 
[14:33:19.474] > Waiting for server log...
[14:33:19.490] > 
[14:33:19.600] > Waiting for server log...
[14:33:19.614] > 
[14:33:19.793] > Waiting for server log...
[14:33:19.803] > 
[14:33:19.853] > Waiting for server log...
[14:33:19.866] > 
[14:33:19.999] > Waiting for server log...
[14:33:20.009] > 
[14:33:20.121] > Waiting for server log...
[14:33:20.133] > 
[14:33:20.320] > Waiting for server log...
[14:33:20.338] > 
[14:33:20.346] > Waiting for server log...
[14:33:20.415] > Waiting for server log...
[14:33:20.431] > 
[14:33:20.539] > Waiting for server log...
[14:33:20.549] > 
[14:33:20.642] > Waiting for server log...
[14:33:20.660] > 
[14:33:20.734] > Waiting for server log...
[14:33:20.753] > 
[14:33:20.814] > Waiting for server log...
[14:33:20.831] > 
[14:33:20.946] > Waiting for server log...
[14:33:20.956] > 
[14:33:21.445] > Waiting for server log...
[14:33:21.456] > 
[14:33:21.539] > Waiting for server log...
[14:33:21.550] > 
[14:33:21.576] > Waiting for server log...
[14:33:21.595] > 
[14:33:21.696] > Waiting for server log...
[14:33:21.714] > 
[14:33:21.746] > Waiting for server log...
[14:33:21.761] > 
[14:33:21.828] > Waiting for server log...
[14:33:21.840] > 
[14:33:21.913] > Waiting for server log...
[14:33:21.932] > 
[14:33:21.999] > Waiting for server log...
[14:33:22.009] > 
[14:33:22.092] > Waiting for server log...
[14:33:22.101] > 
[14:33:22.204] > Waiting for server log...
[14:33:22.224] > 
[14:33:22.303] > Waiting for server log...
[14:33:22.320] > 
[14:33:22.404] > Waiting for server log...
[14:33:22.413] > 
[14:33:22.466] > Waiting for server log...
[14:33:22.475] > 
[14:33:22.530] > Waiting for server log...
[14:33:22.552] > 
[14:33:22.940] > Waiting for server log...
[14:33:22.952] > 
[14:33:23.048] > Waiting for server log...
[14:33:23.061] > 
[14:33:23.239] > Waiting for server log...
[14:33:23.249] > 
[14:33:23.640] > Waiting for server log...
[14:33:23.660] > 
[14:33:23.827] > Waiting for server log...
[14:33:23.849] > 
[14:33:23.964] > Waiting for server log...
[14:33:23.974] > 
[14:33:24.177] > Waiting for server log...
[14:33:24.197] > 
[14:33:24.509] > Waiting for server log...
[14:33:24.524] > 
[14:33:24.808] > Waiting for server log...
[14:33:24.818] > 
[14:33:24.927] > Waiting for server log...
[14:33:24.942] > 
[14:33:25.106] > Waiting for server log...
[14:33:25.130] > 
[14:33:25.627] > Waiting for server log...
[14:33:25.643] > 
[14:33:25.828] > Waiting for server log...
[14:33:25.841] > 
[14:33:26.017] > Waiting for server log...
[14:33:26.028] > 
[14:33:26.111] > Waiting for server log...
[14:33:26.135] > 
[14:33:26.351] > Waiting for server log...
[14:33:26.367] > 
[14:33:26.438] > Waiting for server log...
[14:33:26.460] > 
[14:33:26.513] > Waiting for server log...
[14:33:26.523] > 
[14:33:26.618] > Waiting for server log...
[14:33:26.634] > 
[14:33:26.856] > Waiting for server log...
[14:33:26.870] > 
[14:33:26.957] > Waiting for server log...
[14:33:26.979] > 
[14:33:27.455] > Waiting for server log...
[14:33:27.479] > 
[14:33:27.676] > Waiting for server log...
[14:33:27.697] > 
[14:33:28.383] > Waiting for server log...
[14:33:28.406] > 
[14:33:28.420] >  
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-lice
> ense) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacyst
> tatement).
> *
> 
[14:33:28.436] > 
[14:33:28.770] > Server did not start successfully. Full server log at /home/lunajang/.vscode-ser
> rver/.441438abd1ac652551dbe4d408dfcec8a499b8bf.log >>>
[14:33:28.780] > 
[14:33:28.826] > node:internal/modules/cjs/loader:936
>   throw err;
>   ^
> 
> Error: Cannot find module '../product.json'
> Require stack:
> - /home/lunajang/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/out
> t/server-main.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15
> 5)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (/home/lunajang/.vscode-server/bin/441438abd1ac652551d
> dbe4d408dfcec8a499b8bf/out/server-main.js:4:10329)
>     at Module._compile (node:internal/modules/cjs/loader:1103:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10) 
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_ma
> ain:77:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/lunajang/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/
> /out/server-main.js'
>   ]
> }
> <<< End of server log
> a543fd25abcd: start
> exitCode==32==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> tmpDir==/run/user/1024==
> platform==linux==
[14:33:28.834] > 
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==18653==
> a543fd25abcd: end
[14:33:28.835] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
tmpDir==/run/user/1024==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==18653==

[14:33:28.835] Cannot find module '../product.json'

[14:33:28.836] Resolver error: Error: Cannot find module '../product.json'

	at g.ServerInstallError (c:\Users\jse95\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:584081)
	at h (c:\Users\jse95\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:577310)
	at t.handleInstallOutput (c:\Users\jse95\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:581290)
	at t.tryInstall (c:\Users\jse95\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:680758)
	at async c:\Users\jse95\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:643114
	at async t.withShowDetailsEvent (c:\Users\jse95\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:646432)
	at async t.resolve (c:\Users\jse95\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:644164)
	at async c:\Users\jse95\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:721750
[14:33:28.841] ------

[14:33:30.120] "install" terminal command done
[14:33:30.120] Install terminal quit with output: 

### Anything else?

the pop-up saids "cannot find module .../product.json"

**Comment by LunaJang** [comment]
and here is a window log

**Comment by LunaJang** [comment]
I found 'product.json' exist in "Microsoft VS Code/resources/app/product.json".
Do I need to move this file to somewhere else?

**Comment by LunaJang** [comment]
Problem solved. It turns out that it's not a client, but a server problem. There was no product.json inside .vscode-server/ on server.

So, I deleted the folder completely, returned to the client, and tried to connect to ssh, and it was connected normally with the new vscode-server installed.

If someone has a similar problem, I think it's okay to use the same method as above.
