### ISSUE TITLE
[Remote-SSH Bug]: Can't connect to server: getsockname failed: Not a socket

### ISSUE THREAD

**Issue by PeerBroxtermann** [microsoft/vscode-remote-release#8095]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[13:48:29.731] Log Level: 2
[13:48:29.736] SSH Resolver called for "ssh-remote+myhost.de", attempt 1
[13:48:29.736] "remote.SSH.useLocalServer": false
[13:48:29.736] "remote.SSH.showLoginTerminal": false
[13:48:29.737] "remote.SSH.remotePlatform": {"myhost.de":"linux","myhost2.de":"linux"}
[13:48:29.737] "remote.SSH.path": undefined
[13:48:29.737] "remote.SSH.configFile": undefined
[13:48:29.737] "remote.SSH.useFlock": true
[13:48:29.737] "remote.SSH.lockfilesInTmp": false
[13:48:29.737] "remote.SSH.localServerDownload": auto
[13:48:29.737] "remote.SSH.remoteServerListenOnSocket": false
[13:48:29.737] "remote.SSH.showLoginTerminal": false
[13:48:29.737] "remote.SSH.defaultExtensions": []
[13:48:29.737] "remote.SSH.loglevel": 2
[13:48:29.737] "remote.SSH.enableDynamicForwarding": true
[13:48:29.737] "remote.SSH.enableRemoteCommand": false
[13:48:29.737] "remote.SSH.serverPickPortsFromRange": {}
[13:48:29.737] "remote.SSH.serverInstallPath": {}
[13:48:29.740] VS Code version: 1.75.1
[13:48:29.741] Remote-SSH version: remote-ssh@0.96.0
[13:48:29.741] win32 x64
[13:48:29.741] SSH Resolver called for host: myhost.de
[13:48:29.741] Setting up SSH remote "myhost.de"
[13:48:29.743] Using commit id "441438abd1ac652551dbe4d408dfcec8a499b8bf" and quality "stable" for server
[13:48:29.746] Install and start server if needed
[13:48:29.747] Checking ssh with "ssh -V"
[13:48:29.760] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[13:48:29.762] Running script with connection command: ssh -T -D 57710 "myhost.de" bash
[13:48:29.763] Terminal shell path: C:\Windows\System32\cmd.exe
[13:48:29.962] > getsockname failed: Not a socket
> Read from remote host myhost.de: Unknown error
> The process tried to write to a nonexistent pipe.
> 
[13:48:29.962] Got some output, clearing connection timeout
[13:48:30.285] "install" terminal command done
[13:48:30.285] Install terminal quit with output: Read from remote host myhost.de: Unknown error
[13:48:30.286] Received install output: Read from remote host myhost.de: Unknown error
[13:48:30.286] Failed to parse remote port from server output
[13:48:30.287] Resolver error: Error: 
	at g.Create (c:\Users\broxt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:584147)
	at t.handleInstallOutput (c:\Users\broxt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:582761)
	at t.tryInstall (c:\Users\broxt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:680758)
	at async c:\Users\broxt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:643114
	at async t.withShowDetailsEvent (c:\Users\broxt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:646432)
	at async t.resolve (c:\Users\broxt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:644164)
	at async c:\Users\broxt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.96.0\out\extension.js:1:721750
[13:48:30.290] ------
```

</p>
</details>

### Anything else?

Trying to connect to the dev-Server at work from my new PC (Windows). VSCode has the exact same version and settings as my old computer which is able to connect without any issue.

Tried all the troubleshooting steps, deleted the remote .vscode-server directory, etc, nothing changes.
I also tried reinstalling vscode, but that didn't do anything either.

The only issue I could find that looked similar to mine was this one: https://github.com/microsoft/vscode-remote-release/issues/1309
But that issue just kinda resolved itself and therefore does not help me in troubleshooting.

Thanks in advance for any help you can provide.

**Comment by eleanorjboyd** [comment]
Can you send over your ssh-config file? Thanks
