### ISSUE TITLE
Cannot build a devcontainer image with Podman

### ISSUE THREAD

**Issue by Jacques-Peeters** [microsoft/vscode-remote-release#8103]
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z (2 wks ago)
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0

Sandboxed: No

- VSCode Version: Version: 1.75.1 (Universal)
- Local OS Version: OS: Darwin arm64 22.3.0
- Remote OS Version: `FROM python:3.8`
- Remote Extension/Connection Type: Containers/
- 

- Logs:

Steps to Reproduce:

1. Try to build or rebuild a container

Main error being `Error: stat /var/tmp/libpod_builder1976726847/build/private/var/folders/01/6ynqy_zx13qgqfdg64515jd00000gn/T/devcontainercli/container-features/0.29.0-1677361186508/Dockerfile-with-features: no such file or directory`

```
[2023-02-25T21:39:45.215Z] Dev Containers 0.275.1 in VS Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf).
[2023-02-25T21:39:45.215Z] Start: Resolving Remote
[2023-02-25T21:39:45.226Z] Setting up container for folder or workspace: /Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen
[2023-02-25T21:39:45.231Z] Start: Check Docker is running
[2023-02-25T21:39:45.231Z] Start: Run: podman version --format {{.Server.APIVersion}}
[2023-02-25T21:39:45.443Z] Stop (212 ms): Run: podman version --format {{.Server.APIVersion}}
[2023-02-25T21:39:45.444Z] Server API version: 4.2.1
[2023-02-25T21:39:45.444Z] Stop (213 ms): Check Docker is running
[2023-02-25T21:39:45.444Z] Start: Run: podman volume ls -q
[2023-02-25T21:39:45.586Z] Stop (142 ms): Run: podman volume ls -q
[2023-02-25T21:39:45.586Z] Start: Run: podman ps -q -a --filter label=vsch.local.folder=/Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen --filter label=vsch.quality=stable
[2023-02-25T21:39:45.673Z] Stop (87 ms): Run: podman ps -q -a --filter label=vsch.local.folder=/Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen --filter label=vsch.quality=stable
[2023-02-25T21:39:45.674Z] Start: Run: podman ps -q -a --filter label=devcontainer.local_folder=/Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen --filter label=devcontainer.config_file=/Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen/.devcontainer/devcontainer.json
[2023-02-25T21:39:45.794Z] Stop (120 ms): Run: podman ps -q -a --filter label=devcontainer.local_folder=/Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen --filter label=devcontainer.config_file=/Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen/.devcontainer/devcontainer.json
[2023-02-25T21:39:45.794Z] Start: Run: podman ps -q -a --filter label=devcontainer.local_folder=/Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen
[2023-02-25T21:39:45.881Z] Stop (87 ms): Run: podman ps -q -a --filter label=devcontainer.local_folder=/Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen
[2023-02-25T21:39:45.881Z] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/jacquespeeters/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/jacquespeeters/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --docker-path podman --container-session-data-folder /tmp/devcontainers-5328a637-3a08-4bc6-a347-a1c1db54beb51677361184061 --workspace-folder /Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen --id-label devcontainer.config_file=/Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-02-25T21:39:46.025Z] (node:13637) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2023-02-25T21:39:46.025Z] (Use `Code Helper (Plugin) --trace-deprecation ...` to show where the warning was created)
[2023-02-25T21:39:46.026Z] @devcontainers/cli 0.29.0. Node.js v16.14.2. darwin 22.3.0 arm64.
[2023-02-25T21:39:46.026Z] Start: Run: podman buildx version
[2023-02-25T21:39:46.165Z] Stop (139 ms): Run: podman buildx version
[2023-02-25T21:39:46.165Z] buildah 1.29.0
[2023-02-25T21:39:46.165Z] 
[2023-02-25T21:39:46.165Z] Start: Resolving Remote
[2023-02-25T21:39:46.167Z] Start: Run: git rev-parse --show-cdup
[2023-02-25T21:39:46.175Z] Stop (8 ms): Run: git rev-parse --show-cdup
[2023-02-25T21:39:46.176Z] Start: Run: podman ps -q -a --filter label=devcontainer.local_folder=/Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen --filter label=devcontainer.config_file=/Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen/.devcontainer/devcontainer.json
[2023-02-25T21:39:46.326Z] Stop (150 ms): Run: podman ps -q -a --filter label=devcontainer.local_folder=/Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen --filter label=devcontainer.config_file=/Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen/.devcontainer/devcontainer.json
[2023-02-25T21:39:46.328Z] Start: Run: podman inspect --type image python:3.8
[2023-02-25T21:39:46.507Z] Stop (179 ms): Run: podman inspect --type image python:3.8
[2023-02-25T21:39:46.508Z] local container features stored at: /Users/jacquespeeters/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/node_modules/vscode-dev-containers/container-features
[2023-02-25T21:39:46.509Z] Start: Run: tar --no-same-owner -x -f -
[2023-02-25T21:39:46.543Z] Stop (34 ms): Run: tar --no-same-owner -x -f -
[2023-02-25T21:39:46.544Z] Start: Run: podman buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/01/6ynqy_zx13qgqfdg64515jd00000gn/T/devcontainercli/container-features/0.29.0-1677361186508/Dockerfile-with-features -t vsc-key-events-second-screen-1e4bceb7d422ae106a4be52e1d8a86ad --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen
[2023-02-25T21:40:34.938Z] Error: stat /var/tmp/libpod_builder1976726847/build/private/var/folders/01/6ynqy_zx13qgqfdg64515jd00000gn/T/devcontainercli/container-features/0.29.0-1677361186508/Dockerfile-with-features: no such file or directory

[2023-02-25T21:40:34.940Z] Stop (48396 ms): Run: podman buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/01/6ynqy_zx13qgqfdg64515jd00000gn/T/devcontainercli/container-features/0.29.0-1677361186508/Dockerfile-with-features -t vsc-key-events-second-screen-1e4bceb7d422ae106a4be52e1d8a86ad --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen
[2023-02-25T21:40:34.940Z] Error: Command failed: podman buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/01/6ynqy_zx13qgqfdg64515jd00000gn/T/devcontainercli/container-features/0.29.0-1677361186508/Dockerfile-with-features -t vsc-key-events-second-screen-1e4bceb7d422ae106a4be52e1d8a86ad --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen
[2023-02-25T21:40:34.940Z]     at pie (/Users/jacquespeeters/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js:1916:1698)
[2023-02-25T21:40:34.940Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-02-25T21:40:34.940Z]     at async vF (/Users/jacquespeeters/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js:1915:1972)
[2023-02-25T21:40:34.940Z]     at async P7 (/Users/jacquespeeters/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js:1915:901)
[2023-02-25T21:40:34.940Z]     at async Fie (/Users/jacquespeeters/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js:1921:2093)
[2023-02-25T21:40:34.940Z]     at async Vf (/Users/jacquespeeters/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js:1921:3241)
[2023-02-25T21:40:34.940Z]     at async eoe (/Users/jacquespeeters/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js:2045:17324)
[2023-02-25T21:40:34.940Z]     at async Qse (/Users/jacquespeeters/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js:2045:17065)
[2023-02-25T21:40:34.942Z] Stop (49061 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/jacquespeeters/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/jacquespeeters/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --docker-path podman --container-session-data-folder /tmp/devcontainers-5328a637-3a08-4bc6-a347-a1c1db54beb51677361184061 --workspace-folder /Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen --id-label devcontainer.config_file=/Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-02-25T21:40:34.942Z] Exit code 1
[2023-02-25T21:40:34.944Z] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/jacquespeeters/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/jacquespeeters/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --docker-path podman --container-session-data-folder /tmp/devcontainers-5328a637-3a08-4bc6-a347-a1c1db54beb51677361184061 --workspace-folder /Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen --id-label devcontainer.config_file=/Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/jacquespeeters/src/github.com/Shopify/key-events-second-screen/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-02-25T21:40:34.944Z] Exit code 1

```

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: ?

Already happened in the past :( Similar to https://github.com/microsoft/vscode-remote-release/issues/7408

**Comment by UKHOGreg** [comment]
Same issue for me with:

Version: 1.75.1 (user setup)
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19042
Sandboxed: No

Unfortunately I couldn't find a fix.

**Comment by chrmarti** [comment]
We pass the correct path to Podman.

**Comment by Jacques-Peeters** [comment]
"We pass the correct path to Podman" + "upstream" tag, do you consider that the problem should not fixed within `vscode-remote-release` side? 

If so, where then? https://github.com/containers/podman ?

This is extremely problematic to do not be able to be able to run Docker image with Podman on VSCode.

**Comment by chrmarti** [comment]
You seem to be using a Podman CLI on Windows (or Mac) that doesn't properly forward the Dockerfile passed with `-f`. I see https://github.com/containers/podman has downloads for that, could you file an issue there? Thanks.
