### ISSUE TITLE
[Remote-SSH Issue]: Newly created files get improper ownership

### ISSUE THREAD

**Issue by elfmimi** [microsoft/vscode-remote-release#8123]
- VSCode Version: 1.65.2
- Local OS Version: Windows 10 Pro 21H2 19044.2364
- Remote OS Version: Windows 10 Pro 21H2 19044.1889
- Remote OpenSSH server: OpenSSH_for_Windows_7.7p1, LibreSSL 3.0.2 (sshd.exe version 7.7.2.3) 
- Remote Extension/Connection Type: Remote-SSH vscode-server

I'm trying Windows as a ssh host. Overall, it looks working flawlessly. That is really awesome.

When I create a new file through Remote-SSH , that file will have proper access right settings but its ownership is slightly weird.

`icacls test.txt` shows something like this. Which looks good as far as I can tell.
```
test.txt NT AUTHORITY\SYSTEM:(I)(F)
         BUILTIN\Administrators:(I)(F)
         DESKTOP-XXXXXXX\elfmimi:(I)(F)
```

`cmd /c dir /q test.txt` shows this.
```
2023/03/02  09:47                 4 BUILTIN\Administrators test.txt
```

now do this `takeoown /f test.txt` in terminal inside or outside of vscode. after that owner will be shown as DESKTOP-XXXXXXX\elfmimi which is what I think is the expected one at the first place.

---

Probably related info.
in https://github.com/PowerShell/Win32-OpenSSH/issues/1652 from @bagajjal

> For admin users, ssh connection is an elevated session. Given you are an admin and has elevated session, you can write to c:\windows.
>
> This is by design.

**Comment by eleanorjboyd** [comment]
>  Overall, it looks working flawlessly. That is really awesome.

glad to hear it 😊

I will look into this further but just to clarify you do not switch users at all following the connection right? And if so are the files being created under the user you connected with or that you switch to and are currently active as?

**Comment by elfmimi** [comment]
I'm doing nothing special. Just connecting as myself, same username, and saving a new file under home directory.
As it is natural for a developer, my account is a member of Administrators group.

**Comment by eleanorjboyd** [comment]
@bpasero looks to be a file creation issue past the remote-ssh connection but please send it back if you think this is actually in my domain. Thanks!

**Comment by bpasero** [comment]
@eleanorjboyd the file service lives in the `Agent` of the server process, so I would assume that the ownership of whoever starts the server will apply to the files. 

The file service is not doing anything special here, just using standard node.js APIs to create and write the file. So I would assume this really depends on how the server is started.

**Comment by rmyorston** [comment]
The behaviour reported above, where a created file is seen to belong to `BUILTIN\Administrators`, can be reproduced without involving VSCode or SSH. Simply run a Command Prompt as Administrator and create a file:
```
C:\Windows\system32>echo hello >hello

C:\Windows\system32>dir /q hello
 Volume in drive C has no label.
 Volume Serial Number is 5CDD-5B1F

 Directory of C:\Windows\system32

19/03/2023  13:26                 8 BUILTIN\Administrators hello
               1 File(s)              8 bytes
               0 Dir(s)   6,219,354,112 bytes free
```
The reason we see the same thing with Remote-SSH is that when an admin user logs in over SSH they're granted elevated privileges.

This has been reported a number of times. (In [https://github.com/PowerShell/Win32-OpenSSH/issues/1652](https://github.com/PowerShell/Win32-OpenSSH/issues/1652), for example, as mentioned above.) The OpenSSH developers insist this is "by design" because there's otherwise no way to obtain elevated privileges over SSH.

>I would assume that the ownership of whoever starts the server will apply to the files.

Indeed. When I run VSCode and make a Remote-SSH connection to localhost I see processes like these:
```
PID   PPID  USER     TIME  ELAPSED COMMAND
5144  6924 rmy       0:10  0:50   Code.exe
2436  6924 rmy       0:01  0:47   Code.exe
1704   168 rmy       0:00  0:47   Code.exe
2620  3968 rmy       0:00  0:44   conhost.exe
1952  3968 rmy       0:00  0:43   cmd.exe
2672  1952 rmy       0:00  0:43   ssh.exe
3452  2284 root      0:00  3:31   sshd.exe
5980  3452 root      0:00  3:31   sshd.exe
7124  5980 root      0:00  3:31   powershell.exe
7136  7124 root      0:00  3:31   conhost.exe
3384  7124 root      0:00  3:31   powershell.exe
1628  3384 root      0:00  3:31   powershell.exe
2564  1628 root      0:00  3:31   conhost.exe
2748  1628 root      0:00  3:31   cmd.exe
6176  2748 root      0:00  3:31   node.exe
4548  6176 root      0:00  3:31   node.exe
4324  6176 root      0:00  3:31   node.exe
```
The processes belonging to **rmy** are on the client side, those belonging to **root** are on the server side. Of the latter, Process Explorer shows that the `sshd.exe` with PID 3452 belongs to **NT AUTHORITY\SYSTEM** while all the others belong to **rmy**. (busybox-w32 `ps` reports **root** but it's _actually_ '**rmy** with elevated privileges'.) The elevated privilege propagates down through all the processes to whatever it is that eventually creates the file. As a result the file ownership isn't as expected.

Over at [https://github.com/rmyorston/busybox-w32/issues/240](https://github.com/rmyorston/busybox-w32/issues/240) we've been experimenting with dropping privilege in SSH sessions.

The only process I can easily affect in the tree above is the first `powershell.exe`, the one with PID 7124. Unfortunately that one really does need elevated privileges. Login fails with:
```
> PS C:\Users\rmy> main
[12:51:55.173] > gcim : Access denied
> At line:4 char:6
[12:51:55.180] >
> + $u_=(gcim win32_process | ? processid -eq $t_).parentprocessid
> +      ~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : PermissionDenied: (root\cimv2:win32_process:String) [Get-CimInstance], CimException
>     + FullyQualifiedErrorId : HRESULT 0x80041003,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand
>
> no sshd parent proc
[12:51:55.230] >
[12:51:56.770] "install" terminal command done
[12:51:56.771] Install terminal quit with output: no sshd parent proc
[12:51:56.771] Received install output: no sshd parent proc
[12:51:56.772] Failed to parse remote port from server output
[12:51:56.775] Resolver error: Error:
    at m.Create (c:\Users\rmy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:584388)
    at t.handleInstallOutput (c:\Users\rmy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:582948)
    at t.tryInstall (c:\Users\rmy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:681793)
    at async c:\Users\rmy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:644041
    at async t.withShowDetailsEvent (c:\Users\rmy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:647359)
    at async t.resolve (c:\Users\rmy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:645091)
    at async c:\Users\rmy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:720839
[12:51:56.805] ------
```
It might be possible to drop privilege at some subsequent stage without breaking things, but sadly that's beyond my powers.

**Comment by bpasero** [comment]
@elfmimi can you confirm above?

**Comment by rmyorston** [comment]
Wait a minute.
>The only process I can easily affect in the tree above is the first powershell.exe, the one with PID 7124. Unfortunately that one really does need elevated privileges. Login fails with:

If that fails when I, as an admin user, drop privileges, how does it work for a user who _isn't_ an admin?

The answer is that it doesn't: it fails in the same way.

This means the Remote-SSH extension only works for users who are an admin. Which seems a bit unfair.

That should be a separate issue, though.

**Comment by bpasero** [comment]
If I understand the linked issue in `OpenSSH` properly, then the session you are creating on the remote will be as admin if the user account has admin rights without going through the UAC flow. Any file operation that is done on behalf of said user will be saved as admin and not as the user that is logged in. This seems unnecessary but also seems like an explicit design choice by the SSH implementation.

This would be comparable to running VS Code as admin (right click - run as admin) and then doing file operations.

I am not sure what VS Code can do here to resolve this: as I had said, file operations on the remote happen with the rights of the server process. We would have to find a way to explicitly lower privileges on write operations to solve this?

**Comment by bpasero** [comment]
Thanks for the nice comment, that is helpful. I think this is not really a file issue, but a more general decision to make then.

**Comment by rmyorston** [comment]
Just to provide some further background, the OpenSSH issue mentioned above is linked to this [PowerShell issue](https://github.com/PowerShell/PowerShell/issues/15562). Specifically:
- A discussion of the [privilege-lowering technology](https://github.com/PowerShell/PowerShell/issues/15562#issuecomment-859301523)
- A suggestion that a [privilege altering cmdlet](https://github.com/PowerShell/PowerShell/issues/15562#issuecomment-903269556) for PowerShell could be investigated, though nothing seems to have come of that.

**Comment by elfmimi** [comment]
> @elfmimi can you confirm above?

Yes. I was aware of the elevated session. Hence the link in my OP. I didn't have right words to describe it clearly. Very much appreciate @rmyorston 's explanation.

**Comment by eleanorjboyd** [comment]
Thank you for bringing this to our attention. At this time we are going to close it as an upstream issue- this could be something we explore in the future to make the access rights similar to how people might perceive the extension to work but do not have the bandwidth at this time. Thanks
