### ISSUE TITLE
Dev container ignores "insecure-registries" setting in local daemon.json file

### ISSUE THREAD

**Issue by julian-poidevin** [microsoft/vscode-remote-release#8124]
Type: <b>Bug</b>

1. Have a local docker setting file (located under `/etc/docker/daemon.json` in Linux)
2. Have an "insecure-registries" setting in this file specifying an plain HTTP registry :

```json
{
  "insecure-registries" : [ "gitlab.switchess.com:5050" ]
}
```

4. Have a `.devcontainer.json` file using a `Dockerfile` than is using an image located under this HTTP registry
5. Run the command "Rebuild without cache and Reopen Container"
6. Have an "`http: server gave HTTP response to HTTPS client`" error (log below)
    - INFO : Manually running `docker pull gitlab.switchess.com:5050/switchess-dev/batcom/batcom-bootloader:latest` in the terminal succeeds

<details>
<summary>Remonte Container Log</summary>

```
[2023-03-02T08:30:45.278Z] Dev Containers 0.281.0 in VS Code 1.76.0-insider (92da9481c0904c6adfe372c12da3b7748d74bdcb).
[2023-03-02T08:30:45.278Z] Start: Resolving Remote
[2023-03-02T08:30:45.446Z] Setting up container for folder or workspace: /home/julian/repo/EmbeddedC/batcom-bootloader
[2023-03-02T08:30:45.504Z] Start: Check Docker is running
[2023-03-02T08:30:45.505Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2023-03-02T08:30:45.667Z] Stop (162 ms): Run: docker version --format {{.Server.APIVersion}}
[2023-03-02T08:30:45.667Z] Server API version: 1.42
[2023-03-02T08:30:45.668Z] Stop (164 ms): Check Docker is running
[2023-03-02T08:30:45.668Z] Start: Run: docker volume ls -q
[2023-03-02T08:30:45.794Z] Stop (126 ms): Run: docker volume ls -q
[2023-03-02T08:30:45.797Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/julian/repo/EmbeddedC/batcom-bootloader --filter label=vsch.quality=insider
[2023-03-02T08:30:45.918Z] Stop (121 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/home/julian/repo/EmbeddedC/batcom-bootloader --filter label=vsch.quality=insider
[2023-03-02T08:30:45.921Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/julian/repo/EmbeddedC/batcom-bootloader --filter label=devcontainer.config_file=/home/julian/repo/EmbeddedC/batcom-bootloader/.devcontainer/devcontainer.json
[2023-03-02T08:30:46.044Z] Stop (123 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/julian/repo/EmbeddedC/batcom-bootloader --filter label=devcontainer.config_file=/home/julian/repo/EmbeddedC/batcom-bootloader/.devcontainer/devcontainer.json
[2023-03-02T08:30:46.046Z] Start: Run: docker inspect --type container 9a6739c6b12a
[2023-03-02T08:30:46.155Z] Stop (109 ms): Run: docker inspect --type container 9a6739c6b12a
[2023-03-02T08:30:46.158Z] Start: Run: /opt/visual-studio-code-insiders/code-insiders --ms-enable-electron-run-as-node /home/julian/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.281.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/julian/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-b1098749-f15f-400d-b90b-bf609f3e76691677745843493 --workspace-folder /home/julian/repo/EmbeddedC/batcom-bootloader --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/julian/repo/EmbeddedC/batcom-bootloader --id-label devcontainer.config_file=/home/julian/repo/EmbeddedC/batcom-bootloader/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/julian/repo/EmbeddedC/batcom-bootloader/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-03-02T08:30:46.720Z] (node:68650) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2023-03-02T08:30:46.720Z] (Use `code-insiders --trace-deprecation ...` to show where the warning was created)
[2023-03-02T08:30:46.721Z] @devcontainers/cli 0.31.0. Node.js v16.14.2. linux 6.2.1-arch1-1 x64.
[2023-03-02T08:30:46.721Z] Start: Run: docker buildx version
[2023-03-02T08:30:46.957Z] Stop (236 ms): Run: docker buildx version
[2023-03-02T08:30:46.958Z] github.com/docker/buildx 0.10.3 79e156beb11f697f06ac67fa1fb958e4762c0fab
[2023-03-02T08:30:46.959Z] 
[2023-03-02T08:30:46.960Z] Start: Resolving Remote
[2023-03-02T08:30:46.974Z] Start: Run: git rev-parse --show-cdup
[2023-03-02T08:30:46.986Z] Stop (12 ms): Run: git rev-parse --show-cdup
[2023-03-02T08:30:46.990Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/julian/repo/EmbeddedC/batcom-bootloader --filter label=devcontainer.config_file=/home/julian/repo/EmbeddedC/batcom-bootloader/.devcontainer/devcontainer.json
[2023-03-02T08:30:47.167Z] Stop (177 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/julian/repo/EmbeddedC/batcom-bootloader --filter label=devcontainer.config_file=/home/julian/repo/EmbeddedC/batcom-bootloader/.devcontainer/devcontainer.json
[2023-03-02T08:30:47.168Z] Start: Run: docker inspect --type container 9a6739c6b12a
[2023-03-02T08:30:47.334Z] Stop (166 ms): Run: docker inspect --type container 9a6739c6b12a
[2023-03-02T08:30:47.335Z] Start: Removing Existing Container
[2023-03-02T08:30:47.335Z] Start: Run: docker rm -f 9a6739c6b12ae8f8585874da0043c2342f4fb48d9d277185ef751421b47a13c6
[2023-03-02T08:30:48.772Z] Stop (1437 ms): Run: docker rm -f 9a6739c6b12ae8f8585874da0043c2342f4fb48d9d277185ef751421b47a13c6
[2023-03-02T08:30:48.772Z] Stop (1437 ms): Removing Existing Container
[2023-03-02T08:30:48.779Z] Start: Run: docker inspect --type image gitlab.switchess.com:5050/switchess-dev/batcom/batcom-bootloader:latest
[2023-03-02T08:30:48.909Z] Stop (130 ms): Run: docker inspect --type image gitlab.switchess.com:5050/switchess-dev/batcom/batcom-bootloader:latest
[2023-03-02T08:30:48.911Z] local container features stored at: /home/julian/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.281.0/dist/node_modules/vscode-dev-containers/container-features
[2023-03-02T08:30:48.913Z] Start: Run: tar --no-same-owner -x -f -
[2023-03-02T08:30:48.959Z] Stop (46 ms): Run: tar --no-same-owner -x -f -
[2023-03-02T08:30:48.973Z] * Processing feature: common
[2023-03-02T08:30:48.974Z] (!) WARNING: Using the deprecated 'common' Feature. See https://github.com/devcontainers/features/tree/main/src/common-utils#example-usage for the updated Feature.
[2023-03-02T08:30:49.969Z] * Fetching feature: common-utils_1_oci
[2023-03-02T08:30:50.484Z] Start: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-julian/container-features/0.31.0-1677745848911/Dockerfile-with-features -t vsc-batcom-bootloader-8fd25c24aa42c27a6d7aef654b2e976f --target dev_containers_target_stage --no-cache --pull --build-context dev_containers_feature_content_source=/tmp/devcontainercli-julian/container-features/0.31.0-1677745848911 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /home/julian/repo/EmbeddedC/batcom-bootloader/.devcontainer
[2023-03-02T08:30:50.772Z] [+] Building 0.0s (0/1)                                                         
[2023-03-02T08:30:50.923Z] [+] Building 0.2s (2/3)                                                         
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 3.94kB                                     0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               0.1s
[2023-03-02T08:30:51.072Z] [+] Building 0.3s (2/3)                                                         
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 3.94kB                                     0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               0.3s
[2023-03-02T08:30:51.223Z] [+] Building 0.5s (2/3)                                                         
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 3.94kB                                     0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               0.4s
[2023-03-02T08:30:51.373Z] [+] Building 0.6s (2/3)                                                         
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 3.94kB                                     0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               0.6s
[2023-03-02T08:30:51.524Z] [+] Building 0.8s (2/3)                                                         
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 3.94kB                                     0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               0.7s
[2023-03-02T08:30:51.675Z] [+] Building 0.9s (4/4)                                                         
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 3.94kB                                     0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               0.7s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531b  0.0s
[2023-03-02T08:30:51.792Z] [+] Building 1.0s (6/6) FINISHED                                                
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
[2023-03-02T08:30:51.793Z]  => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 3.94kB                                     0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               0.7s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531b  0.0s
 => ERROR [internal] load metadata for gitlab.switchess.com:5050/switches  0.1s
 => [context dev_containers_feature_content_source] load .dockerignore     0.0s
 => => transferring dev_containers_feature_content_source: 2B              0.0s
------
 > [internal] load metadata for gitlab.switchess.com:5050/switchess-dev/batcom/batcom-bootloader:latest:
------
Dockerfile-with-features:4
--------------------
   2 |     ARG _DEV_CONTAINERS_BASE_IMAGE=placeholder
   3 |     # Use GitLab CI Docker image as base image for our development container
   4 | >>> FROM gitlab.switchess.com:5050/switchess-dev/batcom/batcom-bootloader:latest AS dev_container_auto_added_stage_label
   5 |     # In case you want to avoid pulling from the remote repository, you can close the stm32cubeidecidocker project, build locally and use the following line instead
   6 |     # FROM stm32cubeidecidocker:latest
--------------------
ERROR: failed to solve: failed to do request: Head "https://gitlab.switchess.com:5050/v2/switchess-dev/batcom/batcom-bootloader/manifests/latest": http: server gave HTTP response to HTTPS client
[2023-03-02T08:30:51.999Z] Stop (1515 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-julian/container-features/0.31.0-1677745848911/Dockerfile-with-features -t vsc-batcom-bootloader-8fd25c24aa42c27a6d7aef654b2e976f --target dev_containers_target_stage --no-cache --pull --build-context dev_containers_feature_content_source=/tmp/devcontainercli-julian/container-features/0.31.0-1677745848911 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /home/julian/repo/EmbeddedC/batcom-bootloader/.devcontainer
[2023-03-02T08:30:52.001Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-julian/container-features/0.31.0-1677745848911/Dockerfile-with-features -t vsc-batcom-bootloader-8fd25c24aa42c27a6d7aef654b2e976f --target dev_containers_target_stage --no-cache --pull --build-context dev_containers_feature_content_source=/tmp/devcontainercli-julian/container-features/0.31.0-1677745848911 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /home/julian/repo/EmbeddedC/batcom-bootloader/.devcontainer
[2023-03-02T08:30:52.002Z]     at hie (/home/julian/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.281.0/dist/spec-node/devContainersSpecCLI.js:1931:1698)
[2023-03-02T08:30:52.003Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-03-02T08:30:52.004Z]     at async FF (/home/julian/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.281.0/dist/spec-node/devContainersSpecCLI.js:1930:3910)
[2023-03-02T08:30:52.005Z]     at async S7 (/home/julian/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.281.0/dist/spec-node/devContainersSpecCLI.js:1930:2839)
[2023-03-02T08:30:52.005Z]     at async xie (/home/julian/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.281.0/dist/spec-node/devContainersSpecCLI.js:1945:2625)
[2023-03-02T08:30:52.005Z]     at async Wf (/home/julian/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.281.0/dist/spec-node/devContainersSpecCLI.js:1945:3750)
[2023-03-02T08:30:52.006Z]     at async noe (/home/julian/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.281.0/dist/spec-node/devContainersSpecCLI.js:2069:17325)
[2023-03-02T08:30:52.006Z]     at async roe (/home/julian/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.281.0/dist/spec-node/devContainersSpecCLI.js:2069:17066)
[2023-03-02T08:30:52.013Z] Stop (5855 ms): Run: /opt/visual-studio-code-insiders/code-insiders --ms-enable-electron-run-as-node /home/julian/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.281.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/julian/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-b1098749-f15f-400d-b90b-bf609f3e76691677745843493 --workspace-folder /home/julian/repo/EmbeddedC/batcom-bootloader --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/julian/repo/EmbeddedC/batcom-bootloader --id-label devcontainer.config_file=/home/julian/repo/EmbeddedC/batcom-bootloader/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/julian/repo/EmbeddedC/batcom-bootloader/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-03-02T08:30:52.013Z] Exit code 1
[2023-03-02T08:30:52.017Z] Command failed: /opt/visual-studio-code-insiders/code-insiders --ms-enable-electron-run-as-node /home/julian/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.281.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/julian/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-b1098749-f15f-400d-b90b-bf609f3e76691677745843493 --workspace-folder /home/julian/repo/EmbeddedC/batcom-bootloader --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/julian/repo/EmbeddedC/batcom-bootloader --id-label devcontainer.config_file=/home/julian/repo/EmbeddedC/batcom-bootloader/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/julian/repo/EmbeddedC/batcom-bootloader/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-03-02T08:30:52.018Z] Exit code 1

```

</details>

Extension version: 0.24.0
VS Code version: Code - Insiders 1.76.0-insider (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-02-28T11:50:46.070Z)
OS version: Linux x64 6.2.1-arch1-1
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 6.2.1-arch1-1

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 3057)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 3, 2|
|Memory (System)|23.17GB (17.00GB free)|
|Process Argv|--no-sandbox --new-window --crash-reporter-id 6ac47a50-23bf-4d23-a2a5-ea853d2bf51d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Dev Container: STM32 Dev Environment|
|OS|Linux x64 6.2.1-arch1-1|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 2566)|
|Memory (System)|23.17GB (17.01GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30659908
pythonb192cf:30661257
funwalk2cf:30676044
pythonms35:30671666

```

</details>

**Comment by chrmarti** [comment]
This seems to be an issue with BuildKit. Could be https://github.com/docker/buildx/issues/1370.
