### ISSUE TITLE
code tunnel not connecting

### ISSUE THREAD

**Issue by TheItsNameless** [microsoft/vscode-remote-release#8126]
I want to code on a remote server, which i can access with different devices. Until yesterday a tunnel worked, but then I updated to code version 1.76.0 and suddenly, i can not connect anymore. VSCode is always stuck at `connecting to ...` and the server gives me the below mentioned log when running `code tunnel --verbose`.

- VSCode Version: 1.76.0
- Local OS Version: Windows 11 22H2 22621.1344
- Remote OS Version: Ubuntu 22.04 LTS
- Remote Extension/Connection Type: Server (with `code tunnel`)

- Logs:

```
[2023-03-02 17:32:38] debug [rpc.0] Starting server with command... Command { std: "/home/user/.vscode-cli/server-stable/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/bin/code-server" "--connection-token=fhvtcZPH0WFEBj6MqKkN2SyLhfwbFdM-L9X5quVKojk" "--accept-server-license-terms" "--start-server" "--enable-remote-auto-shutdown" "--socket-path=/tmp/vscode-server-061950ac-95aa-45f4-8ad4-e5e39b822982", kill_on_drop: false }
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1] *
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1] * Visual Studio Code Server
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1] *
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1] * By using the software, you agree to
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1] * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1] * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1] *
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1] Server bound to /tmp/vscode-server-061950ac-95aa-45f4-8ad4-e5e39b822982
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1] Extension host agent listening on /tmp/vscode-server-061950ac-95aa-45f4-8ad4-e5e39b822982
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1] parsed location: "/tmp/vscode-server-061950ac-95aa-45f4-8ad4-e5e39b822982"
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1]
[2023-03-02 17:32:38] info [rpc.0] Server started
[2023-03-02 17:32:38] trace [rpc.0] Attached to server
[2023-03-02 17:32:38] trace [rpc.0] Attached to server
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1] [17:32:38]
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1]
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1]
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1]
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1]
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1] /home/user/.vscode-cli/server-stable/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/server/node/server.main.js:6
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1] `}),I}}e.LoaderStats=E}),define(ve[86],Ee([1,0]),function(se,e){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.throttle=e.debounce=e.memoize=void 0;function E(I){return(P,y,v)=>{let A=null,C=null;if(typeof v.value=="function"?(A="value",C=v.value):typeof v.get=="function"&&(A="get",C=v.get),!C)throw new Error("not supported");v[A]=I(C,y)}}function k(I,P,y){let v=null,A=null;if(typeof y.value=="function"?(v="value",A=y.value,A.length!==0&&console.warn("Memoize should only be used in functions with zero parameters")):typeof y.get=="function"&&(v="get",A=y.get),!A)throw new Error("not supported");const C=`$memoize$${P}`;y[v]=function(...b){return this.hasOwnProperty(C)||Object.defineProperty(this,C,{configurable:!1,enumerable:!1,writable:!1,value:A.apply(this,b)}),this[C]}}e.memoize=k;function a(I,P,y){return E((v,A)=>{const C=`$debounce$${A}`,b=`$debounce$result$${A}`;return function(...h){this[b]||(this[b]=y?y():void 0),clearTimeout(this[C]),P&&(this[b]=P(this[b],...h),h=[this[b]]),this[C]=setTimeout(()=>{v.apply(this,h),this[b]=y?y():void 0},I)}})}e.debounce=a;function S(I,P,y){return E((v,A)=>{const C=`$throttle$timer$${A}`,b=`$throttle$result$${A}`,h=`$throttle$lastRun$${A}`,d=`$throttle$pending$${A}`;return function(...g){if(this[b]||(this[b]=y?y():void 0),(this[h]===null||this[h]===void 0)&&(this[h]=-Number.MAX_VALUE),P&&(this[b]=P(this[b],...g)),this[d])return;const c=this[h]+I;c<=Date.now()?(this[h]=Date.now(),v.apply(this,[this[b]]),this[b]=y?y():void 0):(this[d]=!0,this[C]=setTimeout(()=>{this[d]=!1,this[h]=Date.now(),v.apply(this,[this[b]]),this[b]=y?y():void 0},c-Date.now()))}})}e.throttle=S}),define(ve[9],Ee([1,0]),function(se,e){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.BugIndicatingError=e.ErrorNoTelemetry=e.ExpectedError=e.NotSupportedError=e.NotImplementedError=e.getErrorMessage=e.disposed=e.readonly=e.illegalState=e.illegalArgument=e.canceled=e.CancellationError=e.isCancellationError=e.transformErrorForSerialization=e.onUnexpectedExternalError=e.onUnexpectedError=e.isSigPipeError=e.setUnexpectedErrorHandler=e.errorHandler=e.ErrorHandler=void 0;class E{constructor(){this.b=[],this.a=function(n){setTimeout(()=>{throw n.stack?D.isErrorNoTelemetry(n)?new D(n.message+`
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1]





[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1]
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1] Error: Unable to retrieve mac address (unexpected format)
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1]
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1] Error: Unable to retrieve mac address (unexpected format)
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1]     at S (/home/user/.vscode-cli/server-stable/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/server/node/server.main.js:63:3251)
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1]     at v (/home/user/.vscode-cli/server-stable/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/server/node/server.main.js:74:8276)
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1]     at async /home/user/.vscode-cli/server-stable/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/server/node/server.main.js:74:8133
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1]     at Timeout._onTimeout (/home/user/.vscode-cli/server-stable/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/out/vs/server/node/server.main.js:8:12)
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1]     at listOnTimeout (node:internal/timers:559:17)
[2023-03-02 17:32:38] trace [rpc.0] [codeserver.1]     at processTimers (node:internal/timers:502:7)
```

Steps to Reproduce:

1. Install vscode 1.76.0 on a server
2. start the tunnel with `code tunnel --verbose`
3. after setup, connect to tunnel with web or code desktop

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by TheItsNameless** [comment]
I just tried to downgrade back to 1.75.1, but the error still occurs... Is there a file that vscode downloads and reuses once i downgrade? Because on 1.75.1, the error did not occur, but after the update it occurs in both versions.

**Comment by TheItsNameless** [comment]
I found another issue on the vscode repository, which actually found a solution to the exact problem.

https://github.com/microsoft/vscode/issues/175878
