### ISSUE TITLE
Failed to Attach to Running Container...

### ISSUE THREAD

**Issue by kevluo-nable** [microsoft/vscode-remote-release#8136]
- VSCode Version: 1.76.0 (Universal)
- Local OS Version: macOS Ventura Version 13.2.1 (22D68)
- Remote OS Version: Ubuntu 20.04.5 LTS
- Remote Extension/Connection Type: Containers

- Logs:
[17 ms] Dev Containers 0.282.0 in VS Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb).
[16 ms] Start: Resolving Remote
[18 ms] Setting up container: /api_test
[18 ms] Host: ssh://10.220.80.50
[22 ms] Start: Run: ssh 10.220.80.50 /bin/sh
[24 ms] Start: Run in host: id -un
[10400 ms] root
[10402 ms] 
[10404 ms] Start: Run in host: cat /etc/passwd
[10530 ms] Start: Run in host: echo ~
[10654 ms] /root
[10656 ms] 
[10658 ms] Start: Run in host: test -x '/root/.vscode-remote-containers/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/node'
[10780 ms] 
[10781 ms] 
[10781 ms] Exit code 1
[10782 ms] Start: Run in host: test -x '/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/node'
[10903 ms] 
[10903 ms] 
[10903 ms] Start: Run in host: test -f '/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/node_modules/node-pty/package.json'
[11025 ms] 
[11025 ms] 
[11025 ms] Start: Run in host: test -f '/root/.vscode-remote-containers/dist/vscode-remote-containers-server-0.282.0.js'
[11147 ms] 
[11147 ms] 
[11270 ms] userEnvProbe: loginInteractiveShell (default)
[11271 ms] userEnvProbe: not found in cache
[11272 ms] userEnvProbe shell: /bin/bash
[11540 ms] userEnvProbe PATHs:
Probe:     '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
Container: None
[11668 ms] Start: Run in Host: docker inspect --type container /api_test
[11927 ms] Start: Check Docker is running
[11928 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[12175 ms] Server API version: 1.41
[12428 ms] Start: Run in Host: /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/node /root/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js set-up --container-id f414fddcba1140fac394da4f36273ea9f4a5f5ddb3ff93639dbc5639af10390e --container-session-data-folder /tmp/devcontainers-48b6ddb7-f741-48b2-beb5-99ce71df04591677812777108 --log-level debug --log-format json --default-user-env-probe loginInteractiveShell --skip-post-create --terminal-columns 124 --terminal-rows 15
[12810 ms] (node:4097784) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[12811 ms] (Use `node --trace-deprecation ...` to show where the warning was created)
[12806 ms] @devcontainers/cli 0.31.0. Node.js v16.14.2. linux 5.4.0-124-generic x64.
[12806 ms] Start: Run: docker buildx version
[12897 ms] github.com/docker/buildx v0.9.1-docker ed00243a0ce2a0aee75311b06e32d33b44729689
[12898 ms] 
[12898 ms] Start: Run: docker inspect --type container f414fddcba1140fac394da4f36273ea9f4a5f5ddb3ff93639dbc5639af10390e
[12929 ms] Start: Inspecting container
[12929 ms] Start: Run: docker inspect --type container f414fddcba1140fac394da4f36273ea9f4a5f5ddb3ff93639dbc5639af10390e
[12962 ms] Start: Run in container: /bin/sh
[12967 ms] Start: Run in container: uname -m
[13060 ms] x86_64
[13060 ms] 
[13061 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[13063 ms] NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
[13063 ms] 
[13063 ms] Start: Run in container: cat /etc/passwd
[13066 ms] Start: Run in container: test -f '/var/devcontainer/.patchEtcEnvironmentMarker'
[13067 ms] 
[13067 ms] 
[13068 ms] Start: Run in container: test -f '/var/devcontainer/.patchEtcProfileMarker'
[13069 ms] 
[13069 ms] 
[13331 ms] Start: Run in Host: /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/node /root/.vscode-remote-containers/dist/dev-containers-cli-0.282.0/dist/spec-node/devContainersSpecCLI.js read-configuration --container-id f414fddcba1140fac394da4f36273ea9f4a5f5ddb3ff93639dbc5639af10390e --log-level debug --log-format json --include-merged-configuration --mount-workspace-git-root true --terminal-columns 124 --terminal-rows 15
[13724 ms] (node:4097854) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[13725 ms] (Use `node --trace-deprecation ...` to show where the warning was created)
[13723 ms] @devcontainers/cli 0.31.0. Node.js v16.14.2. linux 5.4.0-124-generic x64.
[13723 ms] Start: Run: docker inspect --type container f414fddcba1140fac394da4f36273ea9f4a5f5ddb3ff93639dbc5639af10390e
[13764 ms] Start: Inspecting container
[13764 ms] Start: Run in Host: docker inspect --type container f414fddcba1140fac394da4f36273ea9f4a5f5ddb3ff93639dbc5639af10390e
[14031 ms] Start: Run in Host: docker exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=48b6ddb7-f741-48b2-beb5-99ce71df04591677812777108 f414fddcba1140fac394da4f36273ea9f4a5f5ddb3ff93639dbc5639af10390e /bin/sh
[14160 ms] Start: Run in container: uname -m
[14284 ms] x86_64
[14286 ms] 
[14287 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[14413 ms] NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
[14414 ms] 
[14415 ms] Start: Run in container: cat /etc/passwd
[14542 ms] Start: Run in container: test -d /root/.vscode-server
[14667 ms] 
[14668 ms] 
[14669 ms] Start: Run in container: test ! -f '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[14794 ms] 
[14795 ms] 
[14796 ms] Exit code 1
[14796 ms] Start: Run in container: cat /root/.vscode-server/data/Machine/settings.json
[14925 ms] 
[14927 ms] cat: /root/.vscode-server/data/Machine/settings.json: No such file or directory
[14927 ms] Exit code 1
[14928 ms] Start: Run in container: test -d /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb
[15050 ms] 
[15050 ms] 
[15050 ms] Start: Launching Dev Containers helper.
[15051 ms] ssh-agent: SSH_AUTH_SOCK in container (/tmp/vscode-ssh-auth-713d0b02-781e-4361-a009-7a0d4cd8d33c.sock) forwarded to ssh host (/tmp/ssh-tUPaRtPOxY/agent.4097631).
[15051 ms] X11 forwarding: DISPLAY not set on host.
[15051 ms] Start: Run in Host: gpgconf --list-dir agent-extra-socket
[15299 ms] /run/user/0/gnupg/S.gpg-agent.extra
[15299 ms] 
[15300 ms] Start: Run in container: gpgconf --list-dir agent-socket
[15425 ms] /root/.gnupg/S.gpg-agent
[15425 ms] 
[15425 ms] Start: Run in container: gpgconf --list-dir homedir
[15553 ms] /root/.gnupg
[15553 ms] 
[15554 ms] Start: Run in container: ls '/root/.gnupg/private-keys-v1.d' 2>/dev/null
[15679 ms] 
[15680 ms] 
[15680 ms] Exit code 2
[15680 ms] Start: Run in container: mkdir -p -m 700 '/root/.gnupg'
[15807 ms] 
[15808 ms] 
[15808 ms] Start: Run in container: command -v docker >/dev/null 2>&1
[15809 ms] Start: Run in Host: gpgconf --list-dir homedir
[15935 ms] 
[15936 ms] 
[15936 ms] Exit code 127
[15938 ms] Start: Run in Host: docker exec -i -u root f414fddcba1140fac394da4f36273ea9f4a5f5ddb3ff93639dbc5639af10390e /bin/sh
[15939 ms] userEnvProbe: loginInteractiveShell (default)
[15940 ms] Start: Run in container: test -f '/tmp/devcontainers-48b6ddb7-f741-48b2-beb5-99ce71df04591677812777108/env-loginInteractiveShell.json'
[16059 ms] /root/.gnupg
[16059 ms] 
[16064 ms] Start: Run in container: echo ~
[16070 ms] 
[16070 ms] 
[16070 ms] Exit code 1
[16070 ms] Start: Run in container: gpgconf --list-dir homedir
[16071 ms] userEnvProbe: not found in cache
[16071 ms] userEnvProbe shell: /bin/bash
[16192 ms] /root
[16192 ms] 
[16192 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-713d0b02-781e-4361-a009-7a0d4cd8d33c.js' >/tmp/vscode-remote-containers-713d0b02-781e-4361-a009-7a0d4cd8d33c.js
[16199 ms] /root/.gnupg
[16199 ms] 
[16199 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --system --replace-all credential.helper '!f() { /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/node /tmp/vscode-remote-containers-713d0b02-781e-4361-a009-7a0d4cd8d33c.js git-credential-helper $*; }; f' || true
[16325 ms] 
[16325 ms] 
[16326 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-713d0b02-781e-4361-a009-7a0d4cd8d33c.js' >/tmp/vscode-remote-containers-server-713d0b02-781e-4361-a009-7a0d4cd8d33c.js_1677812793914
[16328 ms] 
[16328 ms] 
[16328 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd ; readlink /proc/$pid/ns/mnt ; cat /proc/$pid/stat | tr "
[16574 ms] 
[16575 ms] 
[16713 ms] Container server: /bin/sh: 32: /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/node: not found
[16715 ms] Container server terminated (code: 127, signal: null).
[16716 ms] Error: stream ended with:0 but wanted:9
        at c (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:66217)
        at /Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:66398
        at s (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:14:5371)
        at Stream.<anonymous> (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:14:5541)
        at Stream.emit (node:events:526:28)
        at g (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:14:7426)
        at e.read (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:73282)
        at Qi._onstream (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:72558)
        at Qi.write (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:71515)
        at /Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:73518
        at /Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:58999
        at /Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:61605
        at Object.cb (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:68183)
        at c (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:66066)
        at l (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:66328)
        at d.read (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:66696)
        at Object.cb (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:68083)
        at c (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:66066)
        at l (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:66328)
        at d.read (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:66696)
        at /Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:67992
        at r (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:61553)
        at u (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:58885)
        at /Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:59047
        at /Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:61605
        at Object.cb (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:68183)
        at c (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:66066)
        at l (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:66328)
        at /Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:11:66411
        at s (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:14:5371)
        at Socket.<anonymous> (/Users/kevin.luo/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/extension/extension.js:14:5472)
        at Socket.emit (node:events:526:28)
        at addChunk (node:internal/streams/readable:315:12)
        at readableAddChunk (node:internal/streams/readable:289:9)
        at Readable.push (node:internal/streams/readable:228:10)
        at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[16839 ms] Start: Run in container: mkdir -p '/tmp/devcontainers-48b6ddb7-f741-48b2-beb5-99ce71df04591677812777108' && cat > '/tmp/devcontainers-48b6ddb7-f741-48b2-beb5-99ce71df04591677812777108/env-loginInteractiveShell.json' << 'envJSON'
[16976 ms] 
[16977 ms] 
[16977 ms] Start: Run in container: cat '/root/.vscode-server/data/Machine/.connection-token-92da9481c0904c6adfe372c12da3b7748d74bdcb' 2>/dev/null || (umask 377 && echo 'cdf57e2c-e11e-4570-be06-0f9f1f0fec8d' >'/root/.vscode-server/data/Machine/.connection-token-92da9481c0904c6adfe372c12da3b7748d74bdcb-2c1eb4df-1be9-4a23-ab3f-4b2afaed064f' && mv -n '/root/.vscode-server/data/Machine/.connection-token-92da9481c0904c6adfe372c12da3b7748d74bdcb-2c1eb4df-1be9-4a23-ab3f-4b2afaed064f' '/root/.vscode-server/data/Machine/.connection-token-92da9481c0904c6adfe372c12da3b7748d74bdcb' && rm -f '/root/.vscode-server/data/Machine/.connection-token-92da9481c0904c6adfe372c12da3b7748d74bdcb-2c1eb4df-1be9-4a23-ab3f-4b2afaed064f' && cat '/root/.vscode-server/data/Machine/.connection-token-92da9481c0904c6adfe372c12da3b7748d74bdcb')
[16978 ms] Start: Run in Host: gpg-connect-agent updatestartuptty /bye
[17106 ms] e09c58e7-8277-4ebc-82c9-4b506740315a
[17106 ms] 
[17106 ms] Start: Starting VS Code Server
[17106 ms] Start: Preparing Extensions
[17107 ms] Start: Run in container: test ! -f '/root/.vscode-server/data/Machine/.installExtensionsMarker' && set -o noclobber && mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.installExtensionsMarker' ; } 2> /dev/null
[17229 ms] 
[17229 ms] 
[17229 ms] Exit code 1
[17230 ms] Extensions cache, install extensions: None
[17230 ms] Start: Run in container: test -d /root/.vscode-server/extensionsCache && ls /root/.vscode-server/extensionsCache || true
[17352 ms] 
[17352 ms] 
[17354 ms] Extensions cache, copy to remote: None
[17355 ms] Start: Run in Host: docker exec -i -u root -e SHELL=/bin/bash -e VSCODE_AGENT_FOLDER=/root/.vscode-server -w /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb f414fddcba1140fac394da4f36273ea9f4a5f5ddb3ff93639dbc5639af10390e /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/bin/code-server --log debug --force-disable-user-env --server-data-dir /root/.vscode-server --telemetry-level all --accept-server-license-terms --host 127.0.0.1 --port 0 --connection-token-file /root/.vscode-server/data/Machine/.connection-token-92da9481c0904c6adfe372c12da3b7748d74bdcb --extensions-download-dir /root/.vscode-server/extensionsCache --start-server 
[17602 ms] OCI runtime exec failed: exec failed: unable to start container process: exec: "/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/bin/code-server": stat /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/bin/code-server: no such file or directory: unknown
[17606 ms] Command failed: /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/bin/code-server --log debug --force-disable-user-env --server-data-dir /root/.vscode-server --telemetry-level all --accept-server-license-terms --host 127.0.0.1 --port 0 --connection-token-file /root/.vscode-server/data/Machine/.connection-token-92da9481c0904c6adfe372c12da3b7748d74bdcb --extensions-download-dir /root/.vscode-server/extensionsCache --start-server 
[17606 ms] OCI runtime exec failed: exec failed: unable to start container process: exec: "/root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/bin/code-server": stat /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/bin/code-server: no such file or directory: unknown
[17606 ms] Exit code 126
[27515 ms] Extensions cache, remote removals: None
[87647 ms] Extensions cache, remote removals: None
[147780 ms] Extensions cache, remote removals: None

Steps to Reproduce:

1. Use the Remote Explorer in the Activity Bar and from the Containers view, select the Attach to Container inline action on the container;
2. When attaching to an existing container, you will be asked to confirm that attaching means you trust the container. Select 'Got It".

**Comment by chrmarti** [comment]
It can't run `node` while earlier confirming that it exists and is executable. 🤔 
```
[16713 ms] Container server: /bin/sh: 32: /root/.vscode-server/bin/92da9481c0904c6adfe372c12da3b7748d74bdcb/node: not found
```
