### ISSUE TITLE
[Dev Containers] HTTP 407: Proxy Authorization Required since version `0.275.0`

### ISSUE THREAD

**Issue by cailloumajor** [microsoft/vscode-remote-release#8155]
- VSCode Version: 1.76.0
- Local OS Version: Windows 10 version 1909 (build 18363.1443)
- Remote OS Version: N/A
- Remote Extension/Connection Type: Containers/WSL

- Logs:

```
2023-03-07 09:43:11.337 [debug] ProxyResolver#resolveProxy https://education.github.com/api/user PROXY proxy.****.com:3128 
2023-03-07 09:43:11.446 [debug] ProxyResolver#resolveProxy https://api.github.com/user PROXY proxy.****.com:3128 
2023-03-07 09:43:11.787 [error] Error: HTTP 407: Proxy Authorization Required
	at pi.<anonymous> (c:\Users\62203\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:37631)
	at pi.emit (node:events:526:28)
	at pi._processResponse (c:\Users\62203\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:9:4694)
	at ClientRequest._onNativeResponse (c:\Users\62203\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:9:1356)
	at Object.onceWrapper (node:events:646:26)
	at ClientRequest.emit (node:events:538:35)
	at HTTPParser.parserOnIncomingClient (node:_http_client:618:27)
	at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
	at Socket.socketOnData (node:_http_client:482:22)
	at Socket.emit (node:events:526:28)
	at Readable.read (node:internal/streams/readable:527:10)
	at Socket.read (node:net:644:39)
	at flow (node:internal/streams/readable:1011:34)
	at resume_ (node:internal/streams/readable:992:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2023-03-07 09:43:11.787 [trace] forwarded error to extension? true {"value":"ms-vscode-remote.remote-containers","c":"ms-vscode-remote.remote-containers"}
2023-03-07 09:43:12.698 [debug] ProxyResolver#resolveProxy cached https://mobile.events.data.microsoft.com/OneCollector/1.0?cors=true&content-type=application/x-json-stream PROXY proxy.****.com:3128 
2023-03-07 09:43:20.593 [error] Error: HTTP 407: Proxy Authorization Required
	at pi.<anonymous> (c:\Users\62203\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:37631)
	at pi.emit (node:events:526:28)
	at pi._processResponse (c:\Users\62203\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:9:4694)
	at ClientRequest._onNativeResponse (c:\Users\62203\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:9:1356)
	at Object.onceWrapper (node:events:646:26)
	at ClientRequest.emit (node:events:538:35)
	at HTTPParser.parserOnIncomingClient (node:_http_client:618:27)
	at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
	at Socket.socketOnData (node:_http_client:482:22)
	at Socket.emit (node:events:526:28)
	at Readable.read (node:internal/streams/readable:527:10)
	at Socket.read (node:net:644:39)
	at flow (node:internal/streams/readable:1011:34)
	at resume_ (node:internal/streams/readable:992:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2023-03-07 09:43:20.593 [trace] forwarded error to extension? true {"value":"ms-vscode-remote.remote-containers","c":"ms-vscode-remote.remote-containers"}
2023-03-07 09:43:25.285 [error] Error: HTTP 407: Proxy Authorization Required
	at pi.<anonymous> (c:\Users\62203\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:37631)
	at pi.emit (node:events:526:28)
	at pi._processResponse (c:\Users\62203\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:9:4694)
	at ClientRequest._onNativeResponse (c:\Users\62203\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:9:1356)
	at Object.onceWrapper (node:events:646:26)
	at ClientRequest.emit (node:events:538:35)
	at HTTPParser.parserOnIncomingClient (node:_http_client:618:27)
	at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
	at Socket.socketOnData (node:_http_client:482:22)
	at Socket.emit (node:events:526:28)
	at Readable.read (node:internal/streams/readable:527:10)
	at Socket.read (node:net:644:39)
	at flow (node:internal/streams/readable:1011:34)
	at resume_ (node:internal/streams/readable:992:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Description:

I am behind a corporate proxy.
Starting with version `0.275.0` of Dev Containers extension, the error shown in the logs above is thrown at regular intervals (some seconds) in the Extension Host output panel.
I tried to delete VSCode proxy credentials from Windows Credentials Store, restarting VSCode and authenticating again to the proxy, without success.
Switching back to version `0.266.1` of the extension, no errors are logged.

Feel free to ask if you need more information or debugging on my side.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by chrmarti** [comment]
Could you append your container log? (`F1` > `Dev Containers: Show Container Log`)

**Comment by cailloumajor** [comment]
There is no container log, because this happens even before starting a dev container, right after starting VSCode in local mode.

**Comment by andreamah** [comment]
@chrmarti are there some verif steps for this?

**Comment by chrmarti** [comment]
The issue I fixed was that we fetched an index from remote automatically after activation, now it is again only fetched the first time it is needed.

Maybe @cailloumajor could you verify this no longer occurs after VS Code startup? (It would still show when you trigger downloading of the index, but that needs user interaction with the Dev Containers extension, like adding a configuration file through the UI.)
