### ISSUE TITLE
extensions in devcontainer fail to load

### ISSUE THREAD

**Issue by rectalogic** [microsoft/vscode-remote-release#8180]
Type: <b>Bug</b>

Open this branch of this project in devcontainer https://github.com/rectalogic/webvfx/tree/qt6-frameserver

The extensions in the devcontainer.json do not load.
(direct link to devcontainer.json https://github.com/rectalogic/webvfx/blob/qt6-frameserver/.devcontainer/devcontainer.json )

Extension Host log contains:
```
2023-03-11 12:01:47.780 [info] Extension host with pid 52134 started
2023-03-11 12:01:47.780 [info] Skipping acquiring lock for /Users/aw/Library/Application Support/Code/User/workspaceStorage/b4f145a24c69075623d6345fd8ce21ec.
2023-03-11 12:01:47.823 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-03-11 12:01:47.830 [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:jsonc'
2023-03-11 12:01:47.833 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2023-03-11 12:01:47.847 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2023-03-11 12:01:47.855 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers, startup: false, activationEvent: 'onLanguage:jsonc'
2023-03-11 12:01:47.902 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2023-03-11 12:01:47.947 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2023-03-11 12:01:47.962 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-03-11 12:01:48.012 [info] Eager extensions activated
2023-03-11 12:01:48.072 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-03-11 12:01:48.075 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-03-11 12:01:48.205 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-03-11 12:01:48.296 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2023-03-11 12:01:54.240 [info] Extension host terminating: renderer closed the MessagePort
2023-03-11 12:01:54.246 [error] Canceled: Canceled
	at new l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:88793)
	at a.O (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:11260)
	at V.<computed>.Q.charCodeAt.V.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:8550)
	at c.g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:108198)
	at c.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:107574)
	at N.registerCommand.description (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:106867)
	at c.h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:108784)
	at c.g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:107674)
	at c.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:107574)
	at Object.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:30781)
	at D (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1467127)
	at f.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at m.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
	at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
	at Object.m [as dispose] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1481856)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1485923
	at Array.forEach (<anonymous>)
	at g.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1485909)
	at C.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:12431)
	at C.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:12566)
	at C.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1469257)
	at C.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:12566)
	at k (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10:12074)
	at f.X (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:11284)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:9088
	at Array.map (<anonymous>)
	at f.Q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:9075)
	at f.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:9347)
	at u.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:1397)
	at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:18592)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:14731)
	at MessagePortMain.emit (node:events:526:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364) setContext undefined
2023-03-11 12:01:54.246 [error] Canceled: Canceled
	at new l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:88793)
	at a.O (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:11260)
	at V.<computed>.Q.charCodeAt.V.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:8550)
	at c.g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:108198)
	at c.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:107574)
	at N.registerCommand.description (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:106867)
	at c.h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:108784)
	at c.g (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:107674)
	at c.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:107574)
	at Object.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:30781)
	at D (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1467127)
	at f.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at m.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
	at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
	at Object.m [as dispose] (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1481856)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1485923
	at Array.forEach (<anonymous>)
	at g.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1485909)
	at C.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:12431)
	at C.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:12566)
	at C.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main.js:2:1469257)
	at C.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:12566)
	at k (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10:12074)
	at f.X (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:11284)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:9088
	at Array.map (<anonymous>)
	at f.Q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:9075)
	at f.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:9347)
	at u.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:1397)
	at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:18592)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:14731)
	at MessagePortMain.emit (node:events:526:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364) setContext undefined
2023-03-11 12:01:54.246 [info] Extension host with pid 52134 exiting with code 0
2023-03-11 12:01:54.796 [info] Extension host with pid 52259 started
2023-03-11 12:01:54.796 [info] Skipping acquiring lock for /Users/aw/Library/Application Support/Code/User/workspaceStorage/3fa592343f0654aa1a2245396e9eec57.
2023-03-11 12:01:54.796 [info] $getCanonicalURI invoked for authority (dev-container)
2023-03-11 12:01:54.801 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers, startup: false, activationEvent: 'onResolveRemoteAuthority:dev-container'
2023-03-11 12:01:54.871 [info] [resolveAuthority(dev-container,1)][0ms] activating resolver...
2023-03-11 12:01:54.871 [info] [resolveAuthority(dev-container,1)][0ms] setting tunnel factory...
2023-03-11 12:01:54.871 [info] [resolveAuthority(dev-container,1)][0ms] invoking resolve()...
2023-03-11 12:01:55.875 [info] [resolveAuthority(dev-container,1)][1004ms] waiting...
2023-03-11 12:01:56.881 [info] [resolveAuthority(dev-container,1)][2010ms] waiting...
2023-03-11 12:01:57.886 [info] [resolveAuthority(dev-container,1)][3015ms] waiting...
2023-03-11 12:01:58.493 [error] Shell server terminated (code: 1, signal: null)

Error response from daemon: Container c506dde33165ee842b72f55431d6a9c821b3e4730ed176e63710af951e887496 is not running

2023-03-11 12:01:58.887 [info] [resolveAuthority(dev-container,1)][4016ms] waiting...
2023-03-11 12:01:59.889 [info] [resolveAuthority(dev-container,1)][5018ms] waiting...
2023-03-11 12:02:00.894 [info] [resolveAuthority(dev-container,1)][6023ms] waiting...
2023-03-11 12:02:01.895 [info] [resolveAuthority(dev-container,1)][7024ms] waiting...
2023-03-11 12:02:02.892 [info] Extension host terminating: renderer closed the MessagePort
2023-03-11 12:02:02.892 [info] Extension host with pid 52259 exiting with code 0
2023-03-11 12:02:02.892 [error] [resolveAuthority(dev-container,1)][8021ms] returned an error {"name":"Canceled"}
2023-03-11 12:02:03.437 [info] Extension host with pid 52396 started
2023-03-11 12:02:03.437 [info] Skipping acquiring lock for /Users/aw/Library/Application Support/Code/User/workspaceStorage/3fa592343f0654aa1a2245396e9eec57.
2023-03-11 12:02:03.437 [info] $getCanonicalURI invoked for authority (dev-container)
2023-03-11 12:02:03.442 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers, startup: false, activationEvent: 'onResolveRemoteAuthority:dev-container'
2023-03-11 12:02:03.490 [info] [resolveAuthority(dev-container,1)][0ms] activating resolver...
2023-03-11 12:02:03.490 [info] [resolveAuthority(dev-container,1)][0ms] setting tunnel factory...
2023-03-11 12:02:03.491 [info] [resolveAuthority(dev-container,1)][1ms] invoking resolve()...
2023-03-11 12:02:04.491 [info] [resolveAuthority(dev-container,1)][1001ms] waiting...
2023-03-11 12:02:05.492 [info] [resolveAuthority(dev-container,1)][2002ms] waiting...
2023-03-11 12:02:06.497 [info] [resolveAuthority(dev-container,1)][3007ms] waiting...
2023-03-11 12:02:06.609 [info] [resolveAuthority(dev-container,1)][3119ms] returned 127.0.0.1:46529
2023-03-11 12:02:07.640 [info] Eager extensions activated
2023-03-11 12:02:07.704 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-03-11 12:02:08.895 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2023-03-11 12:05:17.614 [info] Extension host terminating: renderer closed the MessagePort
2023-03-11 12:05:17.616 [info] Extension host with pid 52396 exiting with code 0
2023-03-11 12:05:18.216 [info] Extension host with pid 52782 started
2023-03-11 12:05:18.216 [info] Skipping acquiring lock for /Users/aw/Library/Application Support/Code/User/workspaceStorage/3fa592343f0654aa1a2245396e9eec57.
2023-03-11 12:05:18.216 [info] $getCanonicalURI invoked for authority (dev-container)
2023-03-11 12:05:18.222 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers, startup: false, activationEvent: 'onResolveRemoteAuthority:dev-container'
2023-03-11 12:05:18.277 [info] [resolveAuthority(dev-container,1)][0ms] activating resolver...
2023-03-11 12:05:18.277 [info] [resolveAuthority(dev-container,1)][0ms] setting tunnel factory...
2023-03-11 12:05:18.277 [info] [resolveAuthority(dev-container,1)][0ms] invoking resolve()...
2023-03-11 12:05:19.280 [info] [resolveAuthority(dev-container,1)][1003ms] waiting...
2023-03-11 12:05:20.280 [info] [resolveAuthority(dev-container,1)][2003ms] waiting...
2023-03-11 12:05:21.286 [info] [resolveAuthority(dev-container,1)][3009ms] waiting...
2023-03-11 12:05:21.321 [info] [resolveAuthority(dev-container,1)][3044ms] returned 127.0.0.1:46529
2023-03-11 12:05:21.914 [info] Eager extensions activated
2023-03-11 12:05:21.965 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-03-11 12:05:23.220 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2023-03-11 12:05:47.116 [info] Extension host terminating: renderer closed the MessagePort
2023-03-11 12:05:47.118 [info] Extension host with pid 52782 exiting with code 0
2023-03-11 12:05:47.684 [info] Extension host with pid 52945 started
2023-03-11 12:05:47.684 [info] Skipping acquiring lock for /Users/aw/Library/Application Support/Code/User/workspaceStorage/3fa592343f0654aa1a2245396e9eec57.
2023-03-11 12:05:47.684 [info] $getCanonicalURI invoked for authority (dev-container)
2023-03-11 12:05:47.690 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers, startup: false, activationEvent: 'onResolveRemoteAuthority:dev-container'
2023-03-11 12:05:47.742 [info] [resolveAuthority(dev-container,1)][0ms] activating resolver...
2023-03-11 12:05:47.742 [info] [resolveAuthority(dev-container,1)][0ms] setting tunnel factory...
2023-03-11 12:05:47.742 [info] [resolveAuthority(dev-container,1)][0ms] invoking resolve()...
2023-03-11 12:05:48.742 [info] [resolveAuthority(dev-container,1)][1000ms] waiting...
2023-03-11 12:05:49.745 [info] [resolveAuthority(dev-container,1)][2003ms] waiting...
2023-03-11 12:05:50.746 [info] [resolveAuthority(dev-container,1)][3004ms] waiting...
2023-03-11 12:05:50.994 [info] [resolveAuthority(dev-container,1)][3252ms] returned 127.0.0.1:46529
2023-03-11 12:05:51.576 [info] Eager extensions activated
2023-03-11 12:05:51.617 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-03-11 12:05:52.844 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
```

Extension version: 0.282.0
VS Code version: Code 1.76.1 (Universal) (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:09.831Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.49-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: WebVfx @ desktop-linux|
|OS|Linux x64 5.15.49-linuxkit|
|CPUs|unknown (6 x 0)|
|Memory (System)|4.82GB (3.08GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
This seems to be https://github.com/microsoft/vscode-remote-release/issues/8169. Closing as duplicate. Thanks.
