### ISSUE TITLE
`Could not resolve Feature` error occurs in prerelease version Dev Containers extention

### ISSUE THREAD

**Issue by s-t-hg** [microsoft/vscode-remote-release#8191]
The pre-release version continuously failed to build from devcontainer.json containing the `features`.

Switching to the release version worked fine, so I am not sure what is going on.
I am wondering if there have been any changes related to corporate proxy.

- VSCode Version: 1.75.1
- Local OS Version: Windows10 (local) and Ubuntu 20.04 (ssh, Docker host)
- Remote OS Version: NA
- Remote Extension/Connection Type: Containers

- Logs:

```log
[3792 ms] local container features stored at: /home/username/.vscode-remote-containers/dist/dev-containers-cli-0.283.0/dist/node_modules/vscode-dev-containers/container-features
[3795 ms] Start: Run: tar --no-same-owner -x -f -
[3838 ms] * Processing feature: ghcr.io/devcontainers/features/rust:1
[8815 ms] [httpOci] Could not fetch bearer token for 'ghcr.io': Error: HTTP 503: Service Unavailable
[8815 ms] [httpOci] ERR: Failed to fetch Bearer token from registry.
[8815 ms] Request failed
[8815 ms] (!) WARNING: Falling back to deprecated GitHub Release syntax. See https://github.com/devcontainers/spec/blob/main/proposals/devcontainer-features.md#referencing-a-feature for updated specification.
[8815 ms] Github feature.
[8815 ms] Could not resolve Feature 'ghcr.io/devcontainers/features/rust:1'.  Ensure the Feature is published and accessible from your current environment.
[9009 ms] Error: Failed to process feature ghcr.io/devcontainers/features/rust:1
[9009 ms]     at bne (/home/username/.vscode-remote-containers/dist/dev-containers-cli-0.283.0/dist/spec-node/devContainersSpecCLI.js:1850:3109)
[9009 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[9009 ms]     at async am (/home/username/.vscode-remote-containers/dist/dev-containers-cli-0.283.0/dist/spec-node/devContainersSpecCLI.js:1850:2243)
[9010 ms]     at async Uf (/home/username/.vscode-remote-containers/dist/dev-containers-cli-0.283.0/dist/spec-node/devContainersSpecCLI.js:1853:1672)
[9010 ms]     at async fm (/home/username/.vscode-remote-containers/dist/dev-containers-cli-0.283.0/dist/spec-node/devContainersSpecCLI.js:1853:207)
[9010 ms]     at async FF (/home/username/.vscode-remote-containers/dist/dev-containers-cli-0.283.0/dist/spec-node/devContainersSpecCLI.js:1930:3948)
[9010 ms]     at async S7 (/home/username/.vscode-remote-containers/dist/dev-containers-cli-0.283.0/dist/spec-node/devContainersSpecCLI.js:1930:2839)
[9010 ms]     at async xie (/home/username/.vscode-remote-containers/dist/dev-containers-cli-0.283.0/dist/spec-node/devContainersSpecCLI.js:1945:2625)
[9010 ms]     at async Wf (/home/username/.vscode-remote-containers/dist/dev-containers-cli-0.283.0/dist/spec-node/devContainersSpecCLI.js:1945:3750)
[9011 ms]     at async noe (/home/username/.vscode-remote-containers/dist/dev-containers-cli-0.283.0/dist/spec-node/devContainersSpecCLI.js:2069:17325)
[9011 ms] Exit code 1
```

**Comment by chrmarti** [comment]
Looks like an issue on the service side: `[httpOci] Could not fetch bearer token for 'ghcr.io': Error: HTTP 503: Service Unavailable`. Does this work again?
