### ISSUE TITLE
Command Dev Container Open Folder in Container resulted in an error

### ISSUE THREAD

**Issue by MagnusNilsson11** [microsoft/vscode-remote-release#8196]
- VSCode Version: 1.76.1 (user setup)
- Local OS Version: Windows_NT x64 10.0.19044
- Remote OS Version: Ubuntu 22.04.2 LTS (Jammy Jellyfish)
- Remote Extension/Connection Type: WSL

- Logs:

> 2023-03-14 14:59:56.877 [error] TypeError: Cannot read properties of undefined (reading 'localeCompare')
> 	at c:\Users\anonymous\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:39178
> 	at Array.sort (<anonymous>)
> 	at Cw (c:\Users\anonymous\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:39158)
> 	at Tse (c:\Users\anonymous\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:50962)
> 	at Sse (c:\Users\anonymous\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:50674)
> 	at c:\Users\anonymous\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:49575
> 	at s (c:\Users\anonymous\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:50061)
> 	at s (c:\Users\anonymous\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:50243)
> 	at async ag (c:\Users\anonymous\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:49536)
> 	at async i$ (c:\Users\anonymous\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:47159)
> 	at async n$ (c:\Users\anonymous\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:293:46819)
> 	at async n0 (c:\Users\anonymous\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:364:22184)
> 	at async Cae (c:\Users\anonymous\.vscode\extensions\ms-vscode-remote.remote-containers-0.282.0\dist\extension\extension.js:364:21058)
> 	at async c.h (c:\Users\anonymous\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108776) remote-containers.openFolder {"value":"ms-vscode-remote.remote-containers","c":"ms-vscode-remote.remote-containers"}
> 

Steps to Reproduce:

1. Start vscode from a WSL2 terminal
2. Navigate to project folder and command "Dev Containers: Open Folder in Container..."
3. Choose the current folder
4. Choose any predefined container image in the list

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

This error started suddenly, not sure if there's been a version update of vscode or the plugin since it broke. Tried different images in the list, the read error alwats appears.

Tried deleting the %userprofile%/.vscode folder, also tried uninstalling and resinstalling vscode. Rebooted the computer many many times inbetween all the tests.

**Comment by PandaLord** [comment]
same issue

**Comment by edmcman** [comment]
I am getting the same error when trying to use "Dev Containers: Add Dev Container Configuration Files"
