### ISSUE TITLE
[Remote-SSH Bug]: Missing server-darwin file causing failed installation

### ISSUE THREAD

**Issue by prerakmody** [microsoft/vscode-remote-release#8214]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

I am using a Windows 11 local machine (vscode v1.76.2) and trying to install vscode-remote (v0.98.0) on a remote linux machine. Upon investigating logs, I find out that the link [https://update.code.visualstudio.com/commit:/server-darwin/stable](https://update.code.visualstudio.com/commit:/server-darwin/stable) fails. It returns
```
Cannot GET /commit:/server-darwin/stable
```
> Note, that the link where my windows install fails contain the word `darwin`, which is meant for macOS. So I'm a bit confused why it needs that link.

---

Surprisingly, using a local macOS (vscode v1.74.0) and trying to install vscode-remote (v0.98.0) works completely fine. 

### Remote-SSH Log

<details>
<summary>Excerpts from Remote-SSH Log (via windows install)</summary>
<p>

```
[15:04:09.664] Log Level: 2
[15:04:09.669] VS Code version: 1.76.2
[15:04:09.669] Remote-SSH version: remote-ssh@0.98.0
[15:04:09.669] win32 x64

> Downloading with wget
[15:04:19.667] > 
[15:04:19.669] > wget download failed
> https://update.code.visualstudio.com/commit:/server-darwin/stable: 2023-03-17 15
> 5:04:14 ERROR 404: Not Found

> b962cc29f3e9%%2%%
> tar --version:
> tar (GNU tar) 1.30
> Copyright (C) 2017 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>. 
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
> tar: This does not look like a tar archive
> 
> gzip: stdin: unexpected end of file
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> main: line 228: elapsed: command not found
> ERROR: tar exited with non-0 exit code: 0
[15:05:06.484] > 
> main: line 160: fail_with_exitcode: command not found
[15:05:08.417] "install" terminal command done
[15:05:08.418] Install terminal quit with output: main: line 160: fail_with_exitcode: command not found
[15:05:08.418] Received install output: main: line 160: fail_with_exitcode: command not found
[15:05:08.419] Failed to parse remote port from server output
[15:05:08.420] Resolver error: Error: 
    at m.Create (c:\Users\ppmody\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:584388)
    at t.handleInstallOutput (c:\Users\ppmody\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:582948)
    at t.tryInstall (c:\Users\ppmody\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:681793)
    at async c:\Users\ppmody\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:644041
    at async t.withShowDetailsEvent (c:\Users\ppmody\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:647359)
    at async t.resolve (c:\Users\ppmody\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:645091)
    at async c:\Users\ppmody\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:720839
[15:05:08.426] ------
```

</p>
</details>

**Comment by eleanorjboyd** [comment]
can you try setting the setting "remote.SSH.remotePlatform" to linux for the remote you're trying to connect to?

**Comment by prerakmody** [comment]
Hi,
Thanks for the quick response. So turns out that this setting is already configured as `linux` in my local Windows VS Code preferences. Nevertheless, I deleted that setting and then got prompted again to set this while trying to connect. But I am still unable to connect.

Looking at the logs, I seem to be getting a "bad file descriptor" error. Would you happen to know what that means?
 
```
> main: line 46: /bin/99/vscode-remote-lock.ppmody.99: No such file or directory
> Acquiring lock on /bin//vscode-remote-lock.ppmody.
> flock: 99: Bad file descriptor
> Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> bash: line 86: fail_with_exitcode: command not found
[10:50:23.600] > Found old VS Code install clhsdb, attempting to clean up
> main: line 46: /bin/clhsdb/vscode-remote-lock.ppmody.clhsdb: Not a directory
> flock: 98: Bad file descriptor
> Failed to acquire lock for install, not deleting: clhsdb
```

**Comment by eleanorjboyd** [comment]
Do you have the setting `"remote.SSH.useFlock":`set? Does turning it off make a difference?

**Comment by prerakmody** [comment]
I set `remote.SSH.useFlock` to `false ` and also `remote.SSH.lockfilesInTmp` to `true` as per comments in [#1374](https://github.com/microsoft/vscode-remote-release/issues/1374).

```
[12:34:50.143] Log Level: 2
[12:34:50.146] SSH Resolver called for "ssh-remote+res-hpc-lo02", attempt 1
[12:34:50.146] "remote.SSH.useLocalServer": false
[12:34:50.146] "remote.SSH.showLoginTerminal": false
[12:34:50.147] "remote.SSH.remotePlatform": {"res-hpc-lo01":"linux","hpc2":"linux","res-hpc-lkeb06":"linux","res-hpc-lkeb07":"linux","XOSight-EC2":"linux","XOSight-EC2-Trial2":"linux"}
[12:34:50.147] "remote.SSH.path": undefined
[12:34:50.147] "remote.SSH.configFile": undefined
[12:34:50.147] "remote.SSH.useFlock": false
[12:34:50.147] "remote.SSH.lockfilesInTmp": true
[12:34:50.147] "remote.SSH.localServerDownload": auto
[12:34:50.147] "remote.SSH.remoteServerListenOnSocket": false
[12:34:50.147] "remote.SSH.showLoginTerminal": false
[12:34:50.147] "remote.SSH.defaultExtensions": []
[12:34:50.148] "remote.SSH.loglevel": 2
[12:34:50.148] "remote.SSH.enableDynamicForwarding": true
[12:34:50.148] "remote.SSH.enableRemoteCommand": false
[12:34:50.148] "remote.SSH.serverPickPortsFromRange": {}
[12:34:50.148] "remote.SSH.serverInstallPath": {}
[12:34:50.152] VS Code version: 1.76.2
[12:34:50.152] Remote-SSH version: remote-ssh@0.98.0
[12:34:50.152] win32 x64
[12:34:50.154] SSH Resolver called for host: res-hpc-lo02
[12:34:50.154] Setting up SSH remote "res-hpc-lo02"
[12:34:50.159] Using commit id "ee2b180d582a7f601fa6ecfdad8d9fd269ab1884" and quality "stable" for server
[12:34:50.164] Install and start server if needed
[12:34:52.041] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin\ssh.exe -V"
[12:34:52.044] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin\ssh.exe ENOENT
[12:34:52.045] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\libnvvp\ssh.exe -V"
[12:34:52.046] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\libnvvp\ssh.exe ENOENT
[12:34:52.046] Checking ssh with "C:\windows\system32\ssh.exe -V"
[12:34:52.047] Got error from ssh: spawn C:\windows\system32\ssh.exe ENOENT
[12:34:52.047] Checking ssh with "C:\windows\ssh.exe -V"
[12:34:52.048] Got error from ssh: spawn C:\windows\ssh.exe ENOENT
[12:34:52.048] Checking ssh with "C:\windows\System32\Wbem\ssh.exe -V"
[12:34:52.050] Got error from ssh: spawn C:\windows\System32\Wbem\ssh.exe ENOENT
[12:34:52.050] Checking ssh with "C:\windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[12:34:52.051] Got error from ssh: spawn C:\windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[12:34:52.051] Checking ssh with "C:\windows\System32\OpenSSH\ssh.exe -V"
[12:34:52.082] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[12:34:52.086] Running script with connection command: "C:\windows\System32\OpenSSH\ssh.exe" -T -D 55139 "res-hpc-lo02" bash
[12:34:52.089] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[12:34:53.883] > This is a Tuesday 21 in March of 2023 (12:34:53 PM) return
> ]0;C:\WINDOWS\System32\cmd.exe
[12:34:53.883] Got some output, clearing connection timeout
[12:34:53.893] > /home/ppmody/.bashrc: line 36: ml: command not found
[12:34:54.030] > 444857a5dabe: running
[12:34:54.061] > zsh: bad math expression: operand expected at `*100000 + ...'
> Acquiring lock on /vscode-remote-lock.ppmody.
> touch: cannot touch '/vscode-remote-lock.ppmody..target': Permission denied
> \ln /vscode-remote-lock.ppmody..target /vscode-remote-lock.ppmody.
> Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFlock setting
> ln: failed to access '/vscode-remote-lock.ppmody..target': No such file or directory
> bash: line 86: fail_with_exitcode: command not found
[12:34:54.068] > Found old VS Code install clhsdb, attempting to clean up
> touch: cannot touch '/vscode-remote-lock.ppmody.clhsdb.target': Permission denied
> \ln /vscode-remote-lock.ppmody.clhsdb.target /vscode-remote-lock.ppmody.clhsdb
> Failed to acquire lock for install, not deleting: clhsdb
> Found old VS Code install extcheck, attempting to clean up
> ln: failed to access '/vscode-remote-lock.ppmody.clhsdb.target': No such file or directory
> touch: cannot touch '/vscode-remote-lock.ppmody.extcheck.target': Permission denied
> \ln /vscode-remote-lock.ppmody.extcheck.target /vscode-remote-lock.ppmody.extcheck
> Failed to acquire lock for install, not deleting: extcheck
> Found old VS Code install hsdb, attempting to clean up
> ln: failed to access '/vscode-remote-lock.ppmody.extcheck.target': No such file or directory
```

I also dont seem to have issues with space.
![image](https://user-images.githubusercontent.com/2803936/226597464-f35b7700-0569-4b05-aa6b-8801d6fa2f6c.png)

**Comment by prerakmody** [comment]
Yes, I too see errors on the last two lines of my ~/.bashrc file
```
ml add system/gcc/11.2.0
zsh -l
```

Upon commenting these lines, I am able to connect to the remote server via the extension on Windows. But, these two lines do not seem to be an issue for the VSCode on Mac. This is what confounds me.

For now, its not mission critical to have these lines, but maybe interesting for the extension team to look into.

**Comment by eleanorjboyd** [comment]
Hm yes that is interesting- and if you connect via your terminal it is successful right and doesn't have a problem with the bash script? Also if you try running those commands on your remote machine following the connection they work fine?
