### ISSUE TITLE
Remote SSH is not working for few servers although i can connect them via ssh in the vscode terminal

### ISSUE THREAD

**Issue by GIRISHRRAO** [microsoft/vscode-remote-release#8249]
Type: <b>Bug</b>

I could connect to remote server via the terminal but when i try to connect to the remote server from the ssh-remote extension i get the error

```

[20:00:49.122] Using SSH config file "C:\Users\GIRARAO\.ssh\config"
[20:00:49.122] Running script with connection command: ssh -T -D 49838 -F "C:\Users\GIRARAO\.ssh\config" "cegbu-lon-72.snlhrprshared1.gbucdsint02lhr.oraclevcn.com" bash
[20:00:49.124] Terminal shell path: C:\windows\System32\cmd.exe
[20:00:49.420] > ]0;C:\windows\System32\cmd.exe
[20:00:49.421] Got some output, clearing connection timeout
[20:00:50.665] > Corrupted MAC on input.
[20:00:50.681] > ssh_dispatch_run_fatal: Connection to 100.76.205.62 port 22: message authenticat
> ion code incorrect
> The process tried to write to a nonexistent pipe.
> 
[20:00:51.966] "install" terminal command done
[20:00:51.967] Install terminal quit with output: ion code incorrect
[20:00:51.967] Received install output: ion code incorrect
[20:00:51.968] Failed to parse remote port from server output
[20:00:51.970] Resolver error: Error: 
	at g.Create (c:\Users\GIRARAO\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:583926)
	at t.handleInstallOutput (c:\Users\GIRARAO\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:582540)
	at t.tryInstall (c:\Users\GIRARAO\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:680469)
	at async c:\Users\GIRARAO\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:642848
	at async t.withShowDetailsEvent (c:\Users\GIRARAO\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:646166)
	at async t.resolve (c:\Users\GIRARAO\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:643898)
	at async c:\Users\GIRARAO\.vscode\extensions\ms-vscode-remote.remote-ssh-0.94.0\out\extension.js:1:723024
[20:00:51.978] 

Extension version: 0.94.0
VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (8.40GB free)|
|Process Argv|--crash-reporter-id 510148f4-2bb0-4299-94ea-ff4255e43b46|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
vsccsb:30677849
vscodeenable:30660116
azdwalk:30687957
pythonms35:30686772

```

</details>

<!-- generated by issue reporter -->

**Comment by eleanorjboyd** [comment]
Hello! Could you try running this command from your terminal: `ssh -T -D 49838 -F "C:\Users\GIRARAO\.ssh\config" "cegbu-lon-72.snlhrprshared1.gbucdsint02lhr.oraclevcn.com" bash`. Let me know if that works or if you also get an error. Secondly can you send your remote-ssh logs? You can find the logs by going to `view` in the menu bar, then selecting `output`, and finally once the bottom window pops up select  `remote-ssh` from the dropdown on the right. Thanks!

**Comment by GIRISHRRAO** [comment]
Hi Eleanor,
`ssh -T -D 49838 -F "C:\Users\GIRARAO\.ssh\config" "cegbu-lon-72.snlhrprshared1.gbucdsint02lhr.oraclevcn.com" bash`
did not work

Remote-ssh logs -

`[17:16:10.303] Log Level: 2
[17:16:10.315] Picking SSH host
[17:16:10.317] VS Code version: 1.76.2
[17:16:10.317] Remote-SSH version: remote-ssh@0.98.0
[17:16:10.317] win32 x64
[17:16:14.327] ConfigFileWatcher: start watching file:///c%3A/Users/GIRARAO/.ssh/config
[17:16:14.327] ConfigFileWatcher: adding save listener
[17:16:14.328] ConfigFileWatcher: adding close listener
[17:16:40.211] ConfigFileWatcher: saving file:///c%3A/Users/GIRARAO/.ssh/config
[17:16:40.212] ConfigFileWatcher: firing change event for file:///c%3A/Users/GIRARAO/.ssh/config
[17:16:41.522] ConfigFileWatcher: saving file:///c%3A/Users/GIRARAO/.ssh/config
[17:16:41.522] ConfigFileWatcher: firing change event for file:///c%3A/Users/GIRARAO/.ssh/config
[17:16:42.506] ConfigFileWatcher: closing file:///c%3A/Users/GIRARAO/.ssh/config
[17:16:42.507] ConfigFileWatcher: stop watching file:///c%3A/Users/GIRARAO/.ssh/config
[17:16:42.507] ConfigFileWatcher: removing save listener
[17:16:42.507] ConfigFileWatcher: removing close listener
[17:16:45.345] Picking SSH host
[17:16:46.367] Selected cegbu-lon-72.snlhrprshared1.gbucdsint02lhr.oraclevcn.com`

**Comment by klaaspieter** [comment]
I'm seeing a similar (if not the same) issue. I tried the suggested command with different arguments and the part that breaks is `bash`. If I run the command without specifying `bash` it connects successfuly. Probably worth noting that the default shell on the remote and local machines is `zsh`.

**Comment by GIRISHRRAO** [comment]
I fixed the issue in my windows machine by deleting all the extensions related to the remote explorer from the `%USER%\\.vscode\extensions\` folder and reinstalling the extension again.

**Comment by Hallflower20** [comment]
@eleanorjboyd I am getting a very similair issue as the comment above. I think the issue may be coming from some parsing of new lines from log in prompts? Below is my error log:

```
[14:51:20.505] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 49686 lwacalim09 bash
[14:51:20.506] Terminal shell path: C:\Windows\System32\cmd.exe
[14:51:20.761] > ]0;C:\Windows\System32\cmd.exe
[14:51:20.761] Got some output, clearing connection timeout
[14:51:20.783] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[14:51:23.583] > Home directory quota: 72.8% out of 15.0 GB used.
[14:51:25.319] "install" terminal command done
[14:51:25.319] Install terminal quit with output: Home directory quota: 72.8% out of 15.0 GB used.
[14:51:25.319] Received install output: Home directory quota: 72.8% out of 15.0 GB used.
[14:51:25.319] Failed to parse remote port from server output
[14:51:25.320] Resolver error: Error: 
	at m.Create (c:\Users\20xha\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:584388)
	at t.handleInstallOutput (c:\Users\20xha\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:582948)
	at t.tryInstall (c:\Users\20xha\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:681793)
	at async c:\Users\20xha\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:644041
	at async t.withShowDetailsEvent (c:\Users\20xha\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:647359)
	at async t.resolve (c:\Users\20xha\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:645091)
	at async c:\Users\20xha\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:720839
[14:51:25.323] ------```

**Comment by roblourens** [comment]
I wouldn't say that's a similar issue, please open your own issue with the full log.
