### ISSUE TITLE
[Remote-SSH Bug]: 

### ISSUE THREAD

**Issue by SunYong0821** [microsoft/vscode-remote-release#8255]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

```
Host 192.168.71.31_user2
  HostName 192.168.71.31
  User user2
  Port 22
  IdentityFile ~/.ssh/id_rsa_2

Host 192.168.71.31_user1
  HostName 192.168.71.31
  User user1
  Port 22
  IdentityFile ~/.ssh/id_rsa
```

user1 login successfully without passwd, but user2 login with passwd
what happened?

### Expected Behavior

user1 login successfully without passwd, but user2 login with passwd

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[12:56:50.163] Log Level: 2
[12:56:50.179] SSH Resolver called for "ssh-remote+192.168.71.31_user2", attempt 1
[12:56:50.179] "remote.SSH.useLocalServer": false
[12:56:50.180] "remote.SSH.showLoginTerminal": false
[12:56:50.180] "remote.SSH.remotePlatform": {"192.168.71.31_user1":"linux","192.168.71.31_user2":"linux"}
[12:56:50.180] "remote.SSH.path": undefined
[12:56:50.180] "remote.SSH.configFile": undefined
[12:56:50.180] "remote.SSH.useFlock": true
[12:56:50.180] "remote.SSH.lockfilesInTmp": false
[12:56:50.180] "remote.SSH.localServerDownload": auto
[12:56:50.180] "remote.SSH.remoteServerListenOnSocket": false
[12:56:50.180] "remote.SSH.showLoginTerminal": false
[12:56:50.181] "remote.SSH.defaultExtensions": []
[12:56:50.181] "remote.SSH.loglevel": 2
[12:56:50.181] "remote.SSH.enableDynamicForwarding": true
[12:56:50.181] "remote.SSH.enableRemoteCommand": false
[12:56:50.181] "remote.SSH.serverPickPortsFromRange": {}
[12:56:50.181] "remote.SSH.serverInstallPath": {}
[12:56:50.186] VS Code version: 1.76.2
[12:56:50.186] Remote-SSH version: remote-ssh@0.98.0
[12:56:50.186] win32 x64
[12:56:50.187] SSH Resolver called for host: 192.168.71.31_user2
[12:56:50.187] Setting up SSH remote "192.168.71.31_user2"
[12:56:50.190] Using commit id "ee2b180d582a7f601fa6ecfdad8d9fd269ab1884" and quality "stable" for server
[12:56:50.193] Install and start server if needed
[12:56:50.195] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[12:56:50.197] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[12:56:50.198] Checking ssh with "C:\Windows\ssh.exe -V"
[12:56:50.198] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[12:56:50.199] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[12:56:50.199] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[12:56:50.199] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[12:56:50.200] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[12:56:50.200] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[12:56:50.220] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[12:56:50.223] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 55070 "192.168.71.31_user2" bash
[12:56:50.225] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[12:56:50.534] > beitai@192.168.71.31's password:]0;C:\WINDOWS\System32\cmd.exe
[12:56:50.535] Got some output, clearing connection timeout
[12:56:50.535] Showing password prompt
[12:56:51.033] Password dialog canceled
[12:56:51.033] "install" terminal command canceled
[12:56:51.034] Resolver error: Error: Connecting was canceled
	at m.Canceled (c:\Users\skenoy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:584584)
	at c:\Users\skenoy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:681107
[12:56:51.040] ------
```

</p>
</details>

**Comment by eleanorjboyd** [comment]
if you try it from the command line does it still prompt for a password for user2? The remote-ssh extension relies on ssh for all password handling / authorization, therefore we expect the same behavior in the command line as what happens in our extension. If it works from the command line and not from the remote-ssh extension please let me know and I can investigate. Thanks!

**Comment by SunYong0821** [comment]
> if you try it from the command line does it still prompt for a password for user2? The remote-ssh extension relies on ssh for all password handling / authorization, therefore we expect the same behavior in the command line as what happens in our extension. If it works from the command line and not from the remote-ssh extension please let me know and I can investigate. Thanks!

yes it does! only user2 need passwd

**Comment by eleanorjboyd** [comment]
and it doesn't prompt with this either: `ssh "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 55070 "192.168.71.31_user2" bash`? This is the exact command we run

**Comment by SunYong0821** [comment]
> and it doesn't prompt with this either: `ssh "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 55070 "192.168.71.31_user2" bash`? This is the exact command we run

I tested, it(user2) prompt with the command line.
user1 doesn`t prompt with the command line

**Comment by SunYong0821** [comment]
@roblourens 
sorry，I forgot to modify the `beitai`place with user2 in log......
i got prompt

**Comment by roblourens** [comment]
> i got prompt

So you got a password prompt when logging in with user2 in the command line, manually?

If I am understanding correctly then there is an issue with your own ssh config. vscode should do the same thing for auth as when you use ssh in the terminal.
