### ISSUE TITLE
It has log error when i try to connect to connect window

### ISSUE THREAD

**Issue by Bala-periannan** [microsoft/vscode-remote-release#8276]
[19:12:15.464] Log Level: 2
[19:12:15.491] SSH Resolver called for "ssh-remote+184.168.111.92", attempt 1
[19:12:15.492] "remote.SSH.useLocalServer": true
[19:12:15.493] "remote.SSH.path": undefined
[19:12:15.493] "remote.SSH.configFile": undefined
[19:12:15.494] "remote.SSH.useFlock": true
[19:12:15.494] "remote.SSH.lockfilesInTmp": false
[19:12:15.494] "remote.SSH.localServerDownload": auto
[19:12:15.495] "remote.SSH.remoteServerListenOnSocket": false
[19:12:15.495] "remote.SSH.showLoginTerminal": false
[19:12:15.495] "remote.SSH.defaultExtensions": []
[19:12:15.495] "remote.SSH.loglevel": 2
[19:12:15.496] "remote.SSH.enableDynamicForwarding": true
[19:12:15.496] "remote.SSH.enableRemoteCommand": false
[19:12:15.497] "remote.SSH.serverPickPortsFromRange": {}
[19:12:15.497] "remote.SSH.serverInstallPath": {}
[19:12:15.511] VS Code version: 1.76.2
[19:12:15.512] Remote-SSH version: remote-ssh@0.101.2023032415
[19:12:15.512] linux x64
[19:12:15.519] SSH Resolver called for host: 184.168.111.92
[19:12:15.526] Setting up SSH remote "184.168.111.92"
[19:12:15.535] Acquiring local install lock: /tmp/vscode-remote-ssh-fda1d05d-install.lock
[19:12:15.538] Looking for existing server data file at /home/bala/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-fda1d05d-ee2b180d582a7f601fa6ecfdad8d9fd269ab1884-0.101.2023032415/data.json
[19:12:15.539] Using commit id "ee2b180d582a7f601fa6ecfdad8d9fd269ab1884" and quality "stable" for server
[19:12:15.548] Install and start server if needed
[19:12:15.559] PATH: /home/bala/.local/bin:/home/bala/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[19:12:15.559] Checking ssh with "ssh -V"
[19:12:15.584] > OpenSSH_8.9p1 Ubuntu-3ubuntu0.1, OpenSSL 3.0.2 15 Mar 2022

[19:12:15.604] askpass server listening on /run/user/1000/vscode-ssh-askpass-47b4a80e5e96da76c628b7e9b97242799fc54c56.sock
[19:12:15.605] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-a77290a597e61d8026dea95f2076318fb657820e.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","37199","-o","ConnectTimeout=15","184.168.111.92"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/bala/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-fda1d05d-ee2b180d582a7f601fa6ecfdad8d9fd269ab1884-0.101.2023032415/data.json"}
[19:12:15.605] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","SHELL":"/bin/bash","DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/bala/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032415/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/bala/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032415/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-47b4a80e5e96da76c628b7e9b97242799fc54c56.sock"}
[19:12:15.621] Spawned 34360
[19:12:15.957] > local-server-1> Running ssh connection command: "-v -T -D 37199 -o ConnectTimeout=15 184.168.111.92"
[19:12:15.985] > local-server-1> Spawned ssh, pid=34369
[19:12:16.017] stderr> OpenSSH_8.9p1 Ubuntu-3ubuntu0.1, OpenSSL 3.0.2 15 Mar 2022
[19:12:17.032] stderr> Unable to negotiate with 184.168.111.92 port 22: no matching host key type found. Their offer: ssh-rsa,ssh-rsa-cert-v01@openssh.com,ssh-dss
[19:12:17.034] > local-server-1> ssh child died, shutting down
[19:12:17.046] Local server exit: 0
[19:12:17.047] Received install output: local-server-1> Running ssh connection command: "-v -T -D 37199 -o ConnectTimeout=15 184.168.111.92"
local-server-1> Spawned ssh, pid=34369
OpenSSH_8.9p1 Ubuntu-3ubuntu0.1, OpenSSL 3.0.2 15 Mar 2022
Unable to negotiate with 184.168.111.92 port 22: no matching host key type found. Their offer: ssh-rsa,ssh-rsa-cert-v01@openssh.com,ssh-dss
local-server-1> ssh child died, shutting down

[19:12:17.049] Failed to parse remote port from server output
[19:12:17.056] Resolver error: Error: 
	at m.Create (/home/bala/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032415/out/extension.js:1:584145)
	at t.handleInstallOutput (/home/bala/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032415/out/extension.js:1:582705)
	at Object.e [as tryInstallWithLocalServer] (/home/bala/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032415/out/extension.js:1:623427)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/bala/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032415/out/extension.js:1:643396
	at async t.withShowDetailsEvent (/home/bala/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032415/out/extension.js:1:647116)
	at async /home/bala/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032415/out/extension.js:1:621899
	at async C (/home/bala/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032415/out/extension.js:1:618405)
	at async t.resolveWithLocalServer (/home/bala/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032415/out/extension.js:1:621514)
	at async t.resolve (/home/bala/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032415/out/extension.js:1:644724)
	at async /home/bala/.vscode/extensions/ms-vscode-remote.remote-ssh-0.101.2023032415/out/extension.js:1:720599
[19:12:17.072] ------

**Comment by eleanorjboyd** [comment]
if you try `ssh -v -T -D 37199 -o ConnectTimeout=15 184.168.111.92` from your local terminal does it connect? This is replicating exactly what we run so if it doesn't work from the terminal it is an ssh issue. I am seeing the error `Unable to negotiate with 184.168.111.92 port 22: no matching host key type found. Their offer: ssh-rsa,[ssh-rsa-cert-v01@openssh.com](mailto:ssh-rsa-cert-v01@openssh.com),ssh-dss` which I think is an ssh issue.
