### ISSUE TITLE
[Remote-SSH Bug]:  can not connect using -F /dev/nul 

### ISSUE THREAD

**Issue by idhamari** [microsoft/vscode-remote-release#8282]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Anything else?

This is a copy /paste from the original closed issue  [here](https://github.com/microsoft/vscode-discussions/discussions/537):

Dear vscode community,

I am trying to connect to a remote machine via Remote extension. I can connect using the terminal  e.g. 

             ssh -v -F /dev/null user@example.come

But I could not connect using the Remote extension. 

             debug1: Server host key:  examplekey
             Load key "/dev/null": error in libcrypto
             user@example.com: Permission denied (publickey,password).
             local-server-1> ssh child died, shutting down

I tried to modify the config file based on googling but nothing works e.g. 

             IdentityFile /dev/null
  
or 

           StrictHostKeyChecking no
           UserKnownHostsFile /dev/null

or 

        UserKnownHostsFile ~/.ssh/known_hosts
        PubkeyAuthentication no
        PreferredAuthentications password

or 
 
        StrictHostKeyChecking no
        UserKnownHostsFile=/dev/null 

Any suggestions?

I am using visual code installed in Ubuntu machine and trying to connect to another Ubuntu machone

**Comment by eleanorjboyd** [comment]
Hello! Could you please send your remote-ssh logs? You can find the logs by going to `view` in the menu bar, then selecting `output`, and finally once the bottom window pops up select  `remote-ssh` from the dropdown on the right. Thanks!

**Comment by idhamari** [comment]
Thanks for your response: Here is the relevant log part:

`21:23:58.559] Log Level: 2
[21:23:58.571] SSH Resolver called for "ssh-remote+example.com", attempt 1
[21:23:58.572] "remote.SSH.useLocalServer": true
[21:23:58.572] "remote.SSH.path": undefined
[21:23:58.572] "remote.SSH.configFile": undefined
[21:23:58.572] "remote.SSH.useFlock": true
[21:23:58.573] "remote.SSH.lockfilesInTmp": false
[21:23:58.573] "remote.SSH.localServerDownload": auto
[21:23:58.573] "remote.SSH.remoteServerListenOnSocket": false
[21:23:58.573] "remote.SSH.showLoginTerminal": false
[21:23:58.573] "remote.SSH.defaultExtensions": []
[21:23:58.573] "remote.SSH.loglevel": 2
[21:23:58.573] "remote.SSH.enableDynamicForwarding": true
[21:23:58.574] "remote.SSH.enableRemoteCommand": false
[21:23:58.574] "remote.SSH.serverPickPortsFromRange": {}
[21:23:58.574] "remote.SSH.serverInstallPath": {}
[21:23:58.577] VS Code version: 1.74.3
[21:23:58.577] Remote-SSH version: remote-ssh@0.98.0
[21:23:58.577] linux x64
[21:23:58.579] SSH Resolver called for host: example.com
[21:23:58.579] Setting up SSH remote "example.com"
[21:23:58.584] Acquiring local install lock: /tmp/vscode-remote-ssh-8cd8e0e1-install.lock
[21:23:58.586] Looking for existing server data file at /home/example/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-rrrrr-0.98.0/data.json
[21:23:58.588] Using commit id "97dec172d3256f8ca4bfb2143f3f76b503ca0534" and quality "stable" for server
[21:23:58.596] Install and start server if needed
[21:23:58.602] PATH: rrrrr
[21:23:58.603] Checking ssh with "ssh -V"
[21:23:58.623] > OpenSSH_8.9p1 Ubuntu-3ubuntu0.1, OpenSSL 3.0.2 15 Mar 2022

[21:23:58.633] askpass server listening on /run/user/1000/vscode-ssh-askpass-8fbd45266e289de6960dd6a731a73f59c19ce61d.sock
[21:23:58.633] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-45d791b08900239b6b908effb75cad404d218740.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","38563","-o","ConnectTimeout=15","example.com"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/example/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-rrrrrr-0.98.0/data.json"}
[21:23:58.634] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","SHELL":"/bin/bash","DISPLAY":":1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/example/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/example/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-rrrrr.sock"}
[21:23:58.639] Spawned 8290
[21:23:58.760] > local-server-1> Running ssh connection command: "-v -T -D 38563 -o ConnectTimeout=15 example.com"
[21:23:58.764] > local-server-1> Spawned ssh, pid=8298
[21:23:58.770] stderr> OpenSSH_8.9p1 Ubuntu-3ubuntu0.1, OpenSSL 3.0.2 15 Mar 2022
[21:23:59.210] stderr> debug1: Server host key: ssh-ed25519 SHA256:rrrrr
[21:23:59.211] stderr> Warning: Permanently added 'example.com' (ED25519) to the list of known hosts.
[21:23:59.360] stderr> exampleuser@example.com: Permission denied (publickey,password).
[21:23:59.365] > local-server-1> ssh child died, shutting down
[21:23:59.388] Local server exit: 0
[21:23:59.389] Received install output: local-server-1> Running ssh connection command: "-v -T -D 38563 -o ConnectTimeout=15 example.com"
local-server-1> Spawned ssh, pid=8298
OpenSSH_8.9p1 Ubuntu-3ubuntu0.1, OpenSSL 3.0.2 15 Mar 2022
debug1: Server host key: ssh-ed25519 SHA256:bOqA39qMLsydRsJCbjxXGDvWaT7Z1waRnPXh7f4GJEE
Warning: Permanently added 'example.com' (ED25519) to the list of known hosts.
exampleuser@example.com: Permission denied (publickey,password).
local-server-1> ssh child died, shutting down

[21:23:59.396] Resolver error: Error: Permission denied (publickey,password).
	at m.Create (/home/example/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:584388)
	at /home/example/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:582254
	at t.handleInstallOutput (/home/example/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:582870)
	at Object.e [as tryInstallWithLocalServer] (/home/example/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:623670)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/example/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:643639
	at async t.withShowDetailsEvent (/home/example/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:647359)
	at async /home/example/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:622142
	at async C (/home/example/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:618648)
	at async t.resolveWithLocalServer (/home/example/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:621757)
	at async t.resolve (/home/example/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:644967)
	at async /home/example/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:720839
[21:23:59.406] ------`

**Comment by eleanorjboyd** [comment]
Hi! so what happens if you include the `IdentityFile /dev/null` in your config and then run this from the command line `ssh -v -T -D 38563 -o ConnectTimeout=15 example.com`. The exact ssh command we are running to connect is `ssh -v -T -D 38563 -o ConnectTimeout=15 example.com` and therefore if you can get this command to work from your terminal by making changes in the ssh config file then it should work in the extension as well. Let me know how that goes- thanks!

**Comment by idhamari** [comment]
Thanks for your quick reply. I got this:

```
debug1: Trying private key: /dev/null
Load key "/dev/null": error in libcrypto
debug1: No more authentication methods to try.
user@example.com: Permission denied (publickey,password).
```
However, when I add -F /dev/null it works. I should mention that I am using vpn and after connection, I have to enter password e.g.

```
debug1: Trying private key: key_n-1
debug1: Trying private key: key_n
debug1: Next authentication method: password
user@example.com's password: 
```

Finally, I tried to add this line to the config  file and it seems to work and I can connect.

               PasswordAuthentication yes

Thanks again for your support. I will close this issue.

**Comment by eleanorjboyd** [comment]
Great! I am so glad to hear you got your problem figured out. Happy coding 🎉
