### ISSUE TITLE
 Resolver error: Error: Failed to write install script to path C:\Users\saite\AppData\Local\Tempc:\ffmpeg\bin\vscode-linux-multi-line-command-neptun.cs.uni-kl.de-571522878.sh. ENOENT: no such file or directory, 

### ISSUE THREAD

**Issue by SaiTeja2919** [microsoft/vscode-remote-release#8293]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

![Capture](https://user-images.githubusercontent.com/85756704/228555812-85673a20-e1b6-4fc1-b121-b751fb32ff3a.PNG)

i am getting the following error when i am trying to connect remote Linux server 

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```Log Level: 2
[15:34:25.345] SSH Resolver called for "ssh-remote+neptun.cs.uni-kl.de", attempt 1
[15:34:25.347] "remote.SSH.useLocalServer": false
[15:34:25.348] "remote.SSH.showLoginTerminal": false
[15:34:25.349] "remote.SSH.remotePlatform": {}
[15:34:25.349] "remote.SSH.path": undefined
[15:34:25.350] "remote.SSH.configFile": undefined
[15:34:25.350] "remote.SSH.useFlock": true
[15:34:25.350] "remote.SSH.lockfilesInTmp": false
[15:34:25.351] "remote.SSH.localServerDownload": auto
[15:34:25.351] "remote.SSH.remoteServerListenOnSocket": false
[15:34:25.351] "remote.SSH.showLoginTerminal": false
[15:34:25.352] "remote.SSH.defaultExtensions": []
[15:34:25.354] "remote.SSH.loglevel": 2
[15:34:25.356] "remote.SSH.enableDynamicForwarding": true
[15:34:25.357] "remote.SSH.enableRemoteCommand": false
[15:34:25.358] "remote.SSH.serverPickPortsFromRange": {}
[15:34:25.358] "remote.SSH.serverInstallPath": {}
[15:34:25.385] VS Code version: 1.76.2
[15:34:25.385] Remote-SSH version: remote-ssh@0.98.0
[15:34:25.385] win32 x64
[15:34:25.390] SSH Resolver called for host: neptun.cs.uni-kl.de
[15:34:25.390] Setting up SSH remote "neptun.cs.uni-kl.de"
[15:34:25.403] Using commit id "ee2b180d582a7f601fa6ecfdad8d9fd269ab1884" and quality "stable" for server
[15:34:25.416] Install and start server if needed
[15:34:27.838] Checking ssh with "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe -V"
[15:34:27.843] Got error from ssh: spawn C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[15:34:27.844] Checking ssh with "C:\Program Files\Java\jdk1.8.0_281\bin\ssh.exe -V"
[15:34:27.847] Got error from ssh: spawn C:\Program Files\Java\jdk1.8.0_281\bin\ssh.exe ENOENT
[15:34:27.847] Checking ssh with "C:\Program Files (x86)\PC Connectivity Solution\ssh.exe -V"
[15:34:27.849] Got error from ssh: spawn C:\Program Files (x86)\PC Connectivity Solution\ssh.exe ENOENT
[15:34:27.849] Checking ssh with "C:\Program Files (x86)\Intel\iCLS Client\ssh.exe -V"
[15:34:27.851] Got error from ssh: spawn C:\Program Files (x86)\Intel\iCLS Client\ssh.exe ENOENT
[15:34:27.852] Checking ssh with "C:\Program Files\Intel\iCLS Client\ssh.exe -V"
[15:34:27.856] Got error from ssh: spawn C:\Program Files\Intel\iCLS Client\ssh.exe ENOENT
[15:34:27.857] Checking ssh with "C:\windows\system32\ssh.exe -V"
[15:34:27.859] Got error from ssh: spawn C:\windows\system32\ssh.exe ENOENT
[15:34:27.859] Checking ssh with "C:\windows\ssh.exe -V"
[15:34:27.861] Got error from ssh: spawn C:\windows\ssh.exe ENOENT
[15:34:27.861] Checking ssh with "C:\windows\System32\Wbem\ssh.exe -V"
[15:34:27.863] Got error from ssh: spawn C:\windows\System32\Wbem\ssh.exe ENOENT
[15:34:27.864] Checking ssh with "C:\windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[15:34:27.866] Got error from ssh: spawn C:\windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[15:34:27.866] Checking ssh with "C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\ssh.exe -V"
[15:34:27.870] Got error from ssh: spawn C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\ssh.exe ENOENT
[15:34:27.871] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[15:34:27.873] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[15:34:27.873] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[15:34:27.876] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[15:34:27.876] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[15:34:27.878] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[15:34:27.879] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[15:34:27.883] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[15:34:27.884] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[15:34:27.952] > OpenSSH_for_Windows_8.1p1, Libr
[15:34:27.953] > eSSL 3.0.2

[15:34:27.959] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 10981 "neptun.cs.uni-kl.de" bash
[15:34:27.964] Resolver error: Error: Failed to write install script to path C:\Users\saite\AppData\Local\Tempc:\ffmpeg\bin\vscode-linux-multi-line-command-neptun.cs.uni-kl.de-571522878.sh. ENOENT: no such file or directory, open 'C:\Users\saite\AppData\Local\Tempc:\ffmpeg\bin\vscode-linux-multi-line-command-neptun.cs.uni-kl.de-571522878.sh'
	at t.generateMultiLineCommand (c:\Users\saite\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:652443)
	at async t.generateSshCommand (c:\Users\saite\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:682006)
	at async c:\Users\saite\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:644090
	at async t.withShowDetailsEvent (c:\Users\saite\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:647359)
	at async t.resolve (c:\Users\saite\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:645091)
	at async c:\Users\saite\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:720839
[15:34:27.979] ------

</p>
</details>


### Anything else?

_No response_

**Comment by eleanorjboyd** [comment]
seems like the same issue as here: https://github.com/microsoft/vscode-remote-release/issues/2920. Ill investigate to see if there is an easier solution.

**Comment by roblourens** [comment]
We create a path to write this install script to based on the environment variable `TEMP`. That should be the first part of the path in the error message. It seems like on your system this variable must have the invalid value of `C:\Users\saite\AppData\Local\Tempc:\ffmpeg\bin\`, please check that.
