### ISSUE TITLE
Cannot connet to remote target (SSH server)

### ISSUE THREAD

**Issue by RiccardoLincetto** [microsoft/vscode-remote-release#8309]
Type: <b>Bug</b>

I am running VS Code on MacOS and trying to connect to a remote Windows 11 target via SSH, but it's not working. The same client can connect to the same server, via plain ssh; the same client can also connect to other remote Ubuntu targets via the extension. The failure happens after asking the server platform type. Logs are reported here:
```shell
[01:45:07.439] Log Level: 2
[01:45:07.458] SSH Resolver called for "ssh-remote+aurora.nord", attempt 1
[01:45:07.459] "remote.SSH.useLocalServer": true
[01:45:07.459] "remote.SSH.path": undefined
[01:45:07.459] "remote.SSH.configFile": undefined
[01:45:07.459] "remote.SSH.useFlock": true
[01:45:07.460] "remote.SSH.lockfilesInTmp": false
[01:45:07.460] "remote.SSH.localServerDownload": auto
[01:45:07.460] "remote.SSH.remoteServerListenOnSocket": false
[01:45:07.460] "remote.SSH.showLoginTerminal": true
[01:45:07.460] "remote.SSH.defaultExtensions": []
[01:45:07.460] "remote.SSH.loglevel": 2
[01:45:07.460] "remote.SSH.enableDynamicForwarding": true
[01:45:07.461] "remote.SSH.enableRemoteCommand": false
[01:45:07.461] "remote.SSH.serverPickPortsFromRange": {}
[01:45:07.461] "remote.SSH.serverInstallPath": {}
[01:45:07.466] VS Code version: 1.77.0
[01:45:07.466] Remote-SSH version: remote-ssh@0.98.0
[01:45:07.466] darwin x64
[01:45:07.468] SSH Resolver called for host: aurora.nord
[01:45:07.468] Setting up SSH remote "aurora.nord"
[01:45:07.471] Acquiring local install lock: /var/folders/zd/z7ntg84j5qz80zt4mdsqrxsc0000gn/T/vscode-remote-ssh-99a72aec-install.lock
[01:45:07.472] Looking for existing server data file at /Users/riccardo/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-99a72aec-7f329fe6c66b0f86ae1574c2911b681ad5a45d63-0.98.0/data.json
[01:45:07.473] Using commit id "7f329fe6c66b0f86ae1574c2911b681ad5a45d63" and quality "stable" for server
[01:45:07.478] Install and start server if needed
[01:45:07.494] PATH: /Users/riccardo/.local/bin:/usr/local/Caskroom/miniconda/base/bin:/usr/local/Caskroom/miniconda/base/condabin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
[01:45:07.494] Checking ssh with "ssh -V"
[01:45:07.534] > OpenSSH_9.0p1, LibreSSL 3.3.6

[01:45:07.558] askpass server listening on /var/folders/zd/z7ntg84j5qz80zt4mdsqrxsc0000gn/T/vscode-ssh-askpass-91f58d889a1a7cd08be3f379e454e02b55a17c2a.sock
[01:45:07.560] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/zd/z7ntg84j5qz80zt4mdsqrxsc0000gn/T/vscode-ssh-askpass-a5a10439962d00690b5fc75a78f477c3a8c0efa1.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","56174","-o","ConnectTimeout=15","aurora.nord"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/riccardo/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-99a72aec-7f329fe6c66b0f86ae1574c2911b681ad5a45d63-0.98.0/data.json"}
[01:45:07.560] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.gloDYQRziJ/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/riccardo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/riccardo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/zd/z7ntg84j5qz80zt4mdsqrxsc0000gn/T/vscode-ssh-askpass-91f58d889a1a7cd08be3f379e454e02b55a17c2a.sock"}
[01:45:07.563] Spawned 9599
[01:45:07.767] > local-server-1> Running ssh connection command: "-v -T -D 56174 -o ConnectTimeout=15 aurora.nord"
[01:45:07.770] > local-server-1> Spawned ssh, pid=9606
[01:45:07.780] stderr> OpenSSH_9.0p1, LibreSSL 3.3.6
[01:45:08.142] stderr> debug1: Server host key: ssh-ed25519 SHA256:UDJPPXwAKRpf+mROalKjEmIE01I5ZrvFvyLDIx0VaMI
[01:45:08.744] stderr> Authenticated to riccardo.lincetto-olympic.nord ([100.66.181.44]:22) using "publickey".
[01:45:13.141] stderr> client_loop: send disconnect: Broken pipe
[01:45:13.143] > local-server-1> ssh child died, shutting down
[01:45:13.151] Local server exit: 0
[01:45:13.152] Received install output: local-server-1> Running ssh connection command: "-v -T -D 56174 -o ConnectTimeout=15 aurora.nord"
local-server-1> Spawned ssh, pid=9606
OpenSSH_9.0p1, LibreSSL 3.3.6
debug1: Server host key: ssh-ed25519 SHA256:UDJPPXwAKRpf+mROalKjEmIE01I5ZrvFvyLDIx0VaMI
Authenticated to riccardo.lincetto-olympic.nord ([100.66.181.44]:22) using "publickey".
client_loop: send disconnect: Broken pipe
local-server-1> ssh child died, shutting down

[01:45:13.153] Error connecting, prompting to select platform. Issue related to remote-release issue #7272, temporary workaround due to OpenSSH regression.
[01:45:15.877] askpass server listening on /var/folders/zd/z7ntg84j5qz80zt4mdsqrxsc0000gn/T/vscode-ssh-askpass-1f873cf8d354dec1762ac88fd25c3d266fffa382.sock
[01:45:15.878] Spawning local server with {"serverId":2,"ipcHandlePath":"/var/folders/zd/z7ntg84j5qz80zt4mdsqrxsc0000gn/T/vscode-ssh-askpass-93ce92ec944ba613f50bc8c7d653b8dd0988226a.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","56174","-o","ConnectTimeout=15","aurora.nord","powershell"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/riccardo/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-99a72aec-7f329fe6c66b0f86ae1574c2911b681ad5a45d63-0.98.0/data.json"}
[01:45:15.878] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.gloDYQRziJ/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/riccardo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/riccardo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/zd/z7ntg84j5qz80zt4mdsqrxsc0000gn/T/vscode-ssh-askpass-1f873cf8d354dec1762ac88fd25c3d266fffa382.sock"}
[01:45:15.880] Spawned 9616
[01:45:16.046] > local-server-2> Running ssh connection command: "-v -T -D 56174 -o ConnectTimeout=15 aurora.nord powershell"
[01:45:16.051] > local-server-2> Spawned ssh, pid=9622
[01:45:16.063] stderr> OpenSSH_9.0p1, LibreSSL 3.3.6
[01:45:16.659] stderr> debug1: Server host key: ssh-ed25519 SHA256:UDJPPXwAKRpf+mROalKjEmIE01I5ZrvFvyLDIx0VaMI
[01:45:17.228] stderr> Authenticated to riccardo.lincetto-olympic.nord ([100.66.181.44]:22) using "publickey".
[01:45:17.541] stderr> Transferred: sent 2572, received 12604 bytes, in 0.3 seconds
[01:45:17.541] stderr> Bytes per second: sent 8273.6, received 40544.3
[01:45:17.542] > I[01:45:17.550] Local server exit: 0
[01:45:17.551] Received install output: local-server-2> Running ssh connection command: "-v -T -D 56174 -o ConnectTimeout=15 aurora.nord powershell"
local-server-2> Spawned ssh, pid=9622
OpenSSH_9.0p1, LibreSSL 3.3.6
debug1: Server host key: ssh-ed25519 SHA256:UDJPPXwAKRpf+mROalKjEmIE01I5ZrvFvyLDIx0VaMI
Authenticated to riccardo.lincetto-olympic.nord ([100.66.181.44]:22) using "publickey".
Transferred: sent 2572, received 12604 bytes, in 0.3 seconds
Bytes per second: sent 8273.6, received 40544.3
I[01:45:17.552] Failed to parse remote port from server output
[01:45:17.556] Resolver error: Error: 
	at m.Create (/Users/riccardo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:584388)
	at t.handleInstallOutput (/Users/riccardo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:582948)
	at e (/Users/riccardo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:623670)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Object.e [as tryInstallWithLocalServer] (/Users/riccardo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:624415)
	at async /Users/riccardo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:643639
	at async t.withShowDetailsEvent (/Users/riccardo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:647359)
	at async /Users/riccardo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:622142
	at async C (/Users/riccardo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:618648)
	at async t.resolveWithLocalServer (/Users/riccardo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:621757)
	at async t.resolve (/Users/riccardo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:644967)
	at async /Users/riccardo/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:720839
[01:45:17.563] ------
```

Extension version: 0.98.0
VS Code version: Code 1.77.0 (Universal) (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T09:57:11.797Z)
OS version: Darwin x64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 2a2ea4e2-519d-42e9-956a-f4b6549df978|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30672706
vsccsb:30677849
azdwalk:30687957
pythonms35:30701012

```

</details>

**Comment by RiccardoLincetto** [comment]
Solved somehow.
