### ISSUE TITLE
[Remote-SSH Bug]: VS Code Connect to Host was working until today.

### ISSUE THREAD

**Issue by solarslurpi** [microsoft/vscode-remote-release#8332]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

```
[09:15:34.825] Log Level: 2
[09:15:34.914] SSH Resolver called for "ssh-remote+gus", attempt 1
[09:15:34.915] "remote.SSH.useLocalServer": false
[09:15:34.915] "remote.SSH.showLoginTerminal": true
[09:15:34.916] "remote.SSH.remotePlatform": {"microscope":"linux","microdebug":"linux","microcambuddy":"linux","growbuddy":"linux","gus":"linux","vintageracing.social":"linux","143.42.163.55":"linux"}
[09:15:34.916] "remote.SSH.path": undefined
[09:15:34.916] "remote.SSH.configFile": undefined
[09:15:34.917] "remote.SSH.useFlock": true
[09:15:34.917] "remote.SSH.lockfilesInTmp": false
[09:15:34.917] "remote.SSH.localServerDownload": auto
[09:15:34.918] "remote.SSH.remoteServerListenOnSocket": false
[09:15:34.918] "remote.SSH.showLoginTerminal": true
[09:15:34.918] "remote.SSH.defaultExtensions": []
[09:15:34.918] "remote.SSH.loglevel": 2
[09:15:34.918] "remote.SSH.enableDynamicForwarding": true
[09:15:34.918] "remote.SSH.enableRemoteCommand": false
[09:15:34.919] "remote.SSH.serverPickPortsFromRange": {}
[09:15:34.919] "remote.SSH.serverInstallPath": {}
[09:15:34.925] VS Code version: 1.77.1
[09:15:34.925] Remote-SSH version: remote-ssh@0.98.0
[09:15:34.925] win32 x64
[09:15:34.926] SSH Resolver called for host: gus
[09:15:34.926] Setting up SSH remote "gus"
[09:15:34.930] Using commit id "b7886d7461186a5eac768481578c1d7ca80e2d21" and quality "stable" for server
[09:15:34.934] Install and start server if needed
[09:15:34.938] Checking ssh with "C:\Program Files\ImageMagick-7.1.0-Q16\ssh.exe -V"
[09:15:34.940] Got error from ssh: spawn C:\Program Files\ImageMagick-7.1.0-Q16\ssh.exe ENOENT
[09:15:34.941] Checking ssh with "C:\Program Files (x86)\Razer\ChromaBroadcast\bin\ssh.exe -V"
[09:15:34.941] Got error from ssh: spawn C:\Program Files (x86)\Razer\ChromaBroadcast\bin\ssh.exe ENOENT
[09:15:34.941] Checking ssh with "C:\Program Files\Razer\ChromaBroadcast\bin\ssh.exe -V"
[09:15:34.942] Got error from ssh: spawn C:\Program Files\Razer\ChromaBroadcast\bin\ssh.exe ENOENT
[09:15:34.942] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[09:15:34.943] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[09:15:34.943] Checking ssh with "C:\Windows\ssh.exe -V"
[09:15:34.946] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[09:15:34.946] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[09:15:34.947] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[09:15:34.947] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[09:15:34.948] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[09:15:34.948] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[09:15:34.986] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[09:15:34.990] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 50770 gus bash
[09:15:34.993] Terminal shell path: C:\Windows\System32\cmd.exe
[09:15:35.499] > ]0;C:\Windows\System32\cmd.exe
[09:15:35.500] Got some output, clearing connection timeout
[09:15:35.517] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[09:15:35.821] > pi@gus's password: 
[09:15:41.433] > 
[09:15:41.797] > da504d62d08e: running
[09:15:41.904] > Acquiring lock on /home/pi/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/vscode-remote-lock.pi.b7886d7461186a5eac768481578c1d7ca80e2d21
[09:15:41.933] > Found existing installation at /home/pi/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21...
[09:15:41.946] > Checking /home/pi/.vscode-server/.b7886d7461186a5eac768481578c1d7ca80e2d21.log and /home/pi/.vscode-server/.b7886d7461186a5eac768481578c1d7ca80e2d21.pid for a running server
> Looking for server with pid: 8985
[09:15:41.996] > Running ssh connection command... /home/pi/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all   &> "/h
> ome/pi/.vscode-server/.b7886d7461186a5eac768481578c1d7ca80e2d21.log" < /dev/null
> printenv:
[09:15:42.016] >     SHELL=/bin/bash
>     PWD=/home/pi
>     LOGNAME=pi
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/home/pi
>     LANG=en_GB.UTF-8
>     VSCODE_AGENT_FOLDER=/home/pi/.vscode-server
>     SSH_CONNECTION=192.168.86.25 50771 192.168.86.39 22
>     XDG_SESSION_CLASS=user
>     USER=pi
>     SHLVL=0
>     XDG_SESSION_ID=17
>     XDG_RUNTIME_DIR=/run/user/1000
>     SSH_CLIENT=192.168.86.25 50771 22
>     PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
>     _=/usr/bin/printenv
[09:15:42.024] > 
> Removing old logfile at /home/pi/.vscode-server/.b7886d7461186a5eac768481578c1d7ca80e2d21.log
[09:15:42.094] > Spawned remote server: 10679
[09:15:42.100] > Waiting for server log...
> Waiting for server log...
[09:15:42.155] > Waiting for server log...
[09:15:42.206] > Waiting for server log...
[09:15:42.259] > Waiting for server log...
[09:15:42.308] > Waiting for server log...
[09:15:42.361] > Waiting for server log...
[09:15:42.410] > Waiting for server log...
[09:15:42.463] > Waiting for server log...
[09:15:42.511] > Waiting for server log...
[09:15:42.565] > Waiting for server log...
[09:15:42.614] > Waiting for server log...
[09:15:42.665] > Waiting for server log...
[09:15:42.718] > Waiting for server log...
[09:15:42.769] > Waiting for server log...
[09:15:42.823] > Waiting for server log...
[09:15:42.873] > Waiting for server log...
[09:15:42.922] > Waiting for server log...
[09:15:42.976] > Waiting for server log...
[09:15:43.026] > Waiting for server log...
[09:15:43.080] > Waiting for server log...
[09:15:43.131] > Waiting for server log...
[09:15:43.183] > Waiting for server log...
[09:15:43.232] > Waiting for server log...
[09:15:43.284] > Waiting for server log...
[09:15:43.334] > Waiting for server log...
[09:15:43.383] > Waiting for server log...
[09:15:43.436] > Waiting for server log...
[09:15:43.489] > Waiting for server log...
[09:15:43.537] > Waiting for server log...
[09:15:43.588] > Waiting for server log...
[09:15:43.642] > Waiting for server log...
[09:15:43.695] > Waiting for server log...
[09:15:43.744] > Waiting for server log...
[09:15:43.797] > Waiting for server log...
[09:15:43.850] > Waiting for server log...
[09:15:43.898] > Waiting for server log...
[09:15:43.952] > Waiting for server log...
[09:15:44.001] > Waiting for server log...
[09:15:44.053] > Waiting for server log...
[09:15:44.107] > Waiting for server log...
[09:15:44.154] > Waiting for server log...
[09:15:44.206] > Waiting for server log...
[09:15:44.290] > Waiting for server log...
[09:15:44.366] > Waiting for server log...
[09:15:44.417] > Waiting for server log...
[09:15:44.473] > Waiting for server log...
[09:15:44.527] > Waiting for server log...
[09:15:44.607] > Waiting for server log...
[09:15:44.665] > Waiting for server log...
[09:15:44.722] > Waiting for server log...
[09:15:44.766] > Waiting for server log...
[09:15:44.817] > Waiting for server log...
[09:15:44.869] > Waiting for server log...
[09:15:44.919] > Waiting for server log...
[09:15:44.971] > Waiting for server log...
[09:15:45.021] > Waiting for server log...
[09:15:45.073] > Waiting for server log...
[09:15:45.118] > Waiting for server log...
[09:15:45.171] > Waiting for server log...
[09:15:45.220] > Waiting for server log...
[09:15:45.272] > Waiting for server log...
[09:15:45.323] > Waiting for server log...
[09:15:45.376] > Waiting for server log...
[09:15:45.428] > Waiting for server log...
[09:15:45.475] > Waiting for server log...
[09:15:45.527] > Waiting for server log...
[09:15:45.578] > Waiting for server log...
[09:15:45.631] > Waiting for server log...
[09:15:45.681] > Waiting for server log...
[09:15:45.731] > Waiting for server log...
[09:15:45.785] > Waiting for server log...
[09:15:45.834] > Waiting for server log...
[09:15:45.883] > Waiting for server log...
[09:15:45.935] > Waiting for server log...
[09:15:45.984] > Waiting for server log...
[09:15:46.035] > Waiting for server log...
[09:15:46.088] > Waiting for server log...
[09:15:46.137] > Waiting for server log...
[09:15:46.187] > Waiting for server log...
[09:15:46.238] > Waiting for server log...
[09:15:46.289] > Waiting for server log...
[09:15:46.338] > Waiting for server log...
[09:15:46.391] > Waiting for server log...
[09:15:46.443] > Waiting for server log...
[09:15:46.492] > Waiting for server log...
[09:15:46.542] > Waiting for server log...
[09:15:46.592] > Waiting for server log...
[09:15:46.643] > Waiting for server log...
[09:15:46.694] > Waiting for server log...
[09:15:46.746] > Waiting for server log...
[09:15:46.796] > Waiting for server log...
[09:15:46.846] > Waiting for server log...
[09:15:46.898] > Waiting for server log...
[09:15:46.950] > Waiting for server log...
[09:15:46.999] > Waiting for server log...
[09:15:47.050] > Waiting for server log...
[09:15:47.105] > Waiting for server log...
[09:15:47.168] > Waiting for server log...
[09:15:47.229] > Waiting for server log...
[09:15:47.278] > Waiting for server log...
[09:15:47.331] > Waiting for server log...
[09:15:47.382] > Waiting for server log...
[09:15:47.434] > Waiting for server log...
[09:15:47.485] > Waiting for server log...
[09:15:47.535] > Waiting for server log...
[09:15:47.587] > Waiting for server log...
[09:15:47.638] > Waiting for server log...
[09:15:47.689] > Waiting for server log...
[09:15:47.740] > Waiting for server log...
[09:15:47.791] > Waiting for server log...
[09:15:47.844] > Waiting for server log...
[09:15:47.894] > Waiting for server log...
[09:15:47.944] > Waiting for server log...
[09:15:47.995] > Waiting for server log...
[09:15:48.048] > Waiting for server log...
[09:15:48.099] > Waiting for server log...
[09:15:48.152] > Waiting for server log...
[09:15:48.201] > Waiting for server log...
[09:15:48.252] > Waiting for server log...
[09:15:48.304] > Waiting for server log...
[09:15:48.355] > Waiting for server log...
[09:15:48.401] > Waiting for server log...
[09:15:48.447] > Waiting for server log...
[09:15:48.497] > Waiting for server log...
[09:15:48.548] > Waiting for server log...
[09:15:48.597] > Waiting for server log...
[09:15:48.648] > Waiting for server log...
[09:15:48.699] > Waiting for server log...
[09:15:48.750] > Waiting for server log...
[09:15:48.802] > Waiting for server log...
[09:15:48.856] > Waiting for server log...
[09:15:48.909] > Waiting for server log...
[09:15:48.959] > Waiting for server log...
[09:15:49.011] > Waiting for server log...
[09:15:49.065] > Waiting for server log...
[09:15:49.119] > Waiting for server log...
[09:15:49.174] > Waiting for server log...
[09:15:49.224] > Waiting for server log...
[09:15:49.277] > Waiting for server log...
[09:15:49.329] > Waiting for server log...
[09:15:49.381] > Waiting for server log...
[09:15:49.432] > Waiting for server log...
[09:15:49.484] > Waiting for server log...
[09:15:49.535] > Waiting for server log...
[09:15:49.588] > Waiting for server log...
[09:15:49.640] > Waiting for server log...
[09:15:49.692] > Waiting for server log...
[09:15:49.745] > Waiting for server log...
[09:15:49.798] > Waiting for server log...
[09:15:49.850] > Waiting for server log...
[09:15:49.901] > Waiting for server log...
[09:15:49.953] > Waiting for server log...
[09:15:50.021] > Waiting for server log...
[09:15:50.089] > Waiting for server log...
[09:15:50.141] > Waiting for server log...
[09:15:50.192] > Waiting for server log...
[09:15:50.245] > Waiting for server log...
[09:15:50.298] > Waiting for server log...
[09:15:50.350] > Waiting for server log...
[09:15:50.404] > Waiting for server log...
[09:15:50.455] > Waiting for server log...
[09:15:50.509] > Waiting for server log...
[09:15:50.559] > Waiting for server log...
[09:15:50.613] > Waiting for server log...
[09:15:50.665] > Waiting for server log...
[09:15:50.716] > Waiting for server log...
[09:15:50.770] > Waiting for server log...
[09:15:50.824] > Waiting for server log...
[09:15:50.876] > Waiting for server log...
[09:15:50.929] > Waiting for server log...
[09:15:50.979] > Waiting for server log...
[09:15:51.031] > Waiting for server log...
[09:15:51.087] > Waiting for server log...
[09:15:51.140] > Waiting for server log...
[09:15:51.192] > Waiting for server log...
[09:15:51.249] > Waiting for server log...
[09:15:51.301] > Waiting for server log...
[09:15:51.350] > Waiting for server log...
[09:15:51.405] > Waiting for server log...
[09:15:51.456] > Waiting for server log...
[09:15:51.509] > Waiting for server log...
[09:15:51.559] > Waiting for server log...
[09:15:51.614] > Waiting for server log...
[09:15:51.667] > Waiting for server log...
[09:15:51.719] > Waiting for server log...
[09:15:51.773] > Waiting for server log...
[09:15:51.824] > Waiting for server log...
[09:15:51.877] > Waiting for server log...
[09:15:51.930] > Waiting for server log...
[09:15:51.981] > Waiting for server log...
[09:15:52.037] > Waiting for server log...
[09:15:52.112] > Waiting for server log...
[09:15:52.170] > Waiting for server log...
[09:15:52.225] > Waiting for server log...
[09:15:52.275] > Waiting for server log...
[09:15:52.329] > Waiting for server log...
[09:15:52.380] > Waiting for server log...
[09:15:52.434] > Waiting for server log...
[09:15:52.487] > Waiting for server log...
[09:15:52.540] > Waiting for server log...
[09:15:52.592] > Waiting for server log...
[09:15:52.651] > Waiting for server log...
[09:15:52.719] > Waiting for server log...
[09:15:52.755] > Waiting for server log...
[09:15:52.807] > Waiting for server log...
[09:15:52.861] > Waiting for server log...
[09:15:52.912] > Waiting for server log...
[09:15:52.965] > Waiting for server log...
[09:15:53.024] > Waiting for server log...
[09:15:53.074] > Waiting for server log...
[09:15:53.128] > Waiting for server log...
[09:15:53.181] > Waiting for server log...
[09:15:53.234] > Waiting for server log...
[09:15:53.288] > Waiting for server log...
[09:15:53.355] > Waiting for server log...
[09:15:53.394] > Waiting for server log...
[09:15:53.445] > Waiting for server log...
[09:15:53.498] > Waiting for server log...
[09:15:53.552] > Waiting for server log...
[09:15:53.624] > Waiting for server log...
[09:15:53.688] > Waiting for server log...
[09:15:53.740] > Waiting for server log...
[09:15:53.792] > Waiting for server log...
[09:15:53.845] > Waiting for server log...
[09:15:53.898] > Waiting for server log...
[09:15:53.951] > Waiting for server log...
[09:15:54.005] > Waiting for server log...
[09:15:54.056] > Waiting for server log...
[09:15:54.129] > Waiting for server log...
[09:15:54.196] > Waiting for server log...
[09:15:54.266] > Waiting for server log...
[09:15:54.358] > Waiting for server log...
[09:15:54.424] > Waiting for server log...
[09:15:54.490] > Waiting for server log...
[09:15:54.579] > Waiting for server log...
[09:15:54.645] > Waiting for server log...
[09:15:54.698] > Waiting for server log...
[09:15:54.751] > Waiting for server log...
[09:15:54.801] > Waiting for server log...
[09:15:54.853] > Waiting for server log...
[09:15:54.906] > Waiting for server log...
[09:15:54.959] > Waiting for server log...
[09:15:55.012] > Waiting for server log...
[09:15:55.080] > Waiting for server log...
[09:15:55.138] > Waiting for server log...
[09:15:55.190] > Waiting for server log...
[09:15:55.245] > Waiting for server log...
[09:15:55.298] > Waiting for server log...
[09:15:55.348] > Waiting for server log...
[09:15:55.402] > Waiting for server log...
[09:15:55.455] > Waiting for server log...
[09:15:55.506] > Waiting for server log...
[09:15:55.559] > Waiting for server log...
[09:15:55.611] > Waiting for server log...
[09:15:55.665] > Waiting for server log...
[09:15:55.716] > Waiting for server log...
[09:15:55.769] > Waiting for server log...
[09:15:55.826] > Waiting for server log...
[09:15:55.875] > Waiting for server log...
[09:15:55.931] > Waiting for server log...
[09:15:55.981] > Waiting for server log...
[09:15:56.032] > Waiting for server log...
[09:15:56.084] > Waiting for server log...
[09:15:56.138] > Waiting for server log...
[09:15:56.192] > Waiting for server log...
[09:15:56.243] > Waiting for server log...
[09:15:56.291] >  
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
[09:15:56.302] > 
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
> 
[09:15:56.333] > Server did not start successfully. Full server log at /home/pi/.vscode-server/.b7886d7461186a5eac768481578c1d7ca80e2d21.log >>>
> /home/pi/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/bin/code-server: 12: /home/pi/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/node: not found
[09:15:56.340] > 
> <<< End of server log
> da504d62d08e: start
> exitCode==32==
> listeningOn====
> osReleaseId==raspbian==
> arch==aarch64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==14275==
> da504d62d08e: end
[09:15:56.341] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==raspbian==
arch==aarch64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==14275==

[09:15:56.343] Resolver error: Error: The VS Code Server failed to start
	at m.ServerInstallError (c:\Users\happy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:584322)
	at f (c:\Users\happy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:578379)
	at t.handleInstallOutput (c:\Users\happy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:581404)
	at t.tryInstall (c:\Users\happy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:681793)
	at async c:\Users\happy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:644041
	at async t.withShowDetailsEvent (c:\Users\happy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:647359)
	at async t.resolve (c:\Users\happy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:645091)
	at async c:\Users\happy\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:720839
[09:15:56.350] ------




[09:15:56.377] > 
[09:15:57.624] "install" terminal command done
[09:15:57.624] Install terminal quit with output: 
[09:17:20.737] Picking SSH host
[09:17:32.254] Selected gus
[09:17:32.256] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -o ClearAllForwardings=true gus bash
[09:17:32.260] Terminal shell path: C:\Windows\System32\cmd.exe
[09:17:32.520] > ]0;C:\Windows\System32\cmd.exe
[09:17:32.529] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[09:17:32.741] > pi@gus's password: 
[09:17:37.047] > 
[09:17:37.339] > kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
[09:17:42.327] "Uninstall VS Code Server" terminal command done
```

### Steps To Reproduce

It reproduces the same error every time.  I have tried uninstalling and reinstalling things, now I am totally confused. I apologize for this.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/2947

**Comment by roblourens** [comment]
From what I understand, there was some update to the Raspberry Pi that caused a lot of people to start hitting this issue. We will try to do something to address it soon.

**Comment by solarslurpi** [comment]
I see. Thank you.  I was able to get it to work by forcing into 32 bit with the idea to modify /boot/config.txt as shown in https://github.com/microsoft/vscode-remote-release/issues/6388#issuecomment-1050923254  .  Obviously, this isn't a fix...sadly...but...

**Comment by solarslurpi** [comment]
Also, is it possible to sign up somehow for a notification when this gets fixed?  Thank you.

**Comment by eleanorjboyd** [comment]
@solarslurpi it is currently fixed in vscode insiders and the release to stable will go out in our next monthly release which is next week. Thanks
