### ISSUE TITLE
[Remote-SSH Bug]: VSCode Server failed to start

### ISSUE THREAD

**Issue by bradkeifer** [microsoft/vscode-remote-release#8341]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Steps To Reproduce

vscode version 1.77.1 on macOS Venture 13.3 attempting remote SSH connection to a Raspberry Pi 4 running Debian 10.

vscode details are:
```
Version: 1.77.1
Commit: b7886d7461186a5eac768481578c1d7ca80e2d21
Date: 2023-04-04T23:23:33.779Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.4.0
Sandboxed: Yes
```
uname -a output from raspberry pi is 
```
Linux keiferpi2 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

When trying remote SSH connection, I get an error that the `VSCode Server failed to start`. The log file states that the file `node` was not found. But the file exists, is readable, see below:
```
-rwxr-xr-x 1 brad brad 79252272 Apr  5 09:21 /home/brad/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/node
```

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[10:00:47.674] Log Level: 2
[10:00:47.690] SSH Resolver called for "ssh-remote+keiferpi2.local", attempt 1
[10:00:47.691] "remote.SSH.useLocalServer": true
[10:00:47.692] "remote.SSH.path": undefined
[10:00:47.692] "remote.SSH.configFile": undefined
[10:00:47.692] "remote.SSH.useFlock": true
[10:00:47.692] "remote.SSH.lockfilesInTmp": false
[10:00:47.692] "remote.SSH.localServerDownload": off
[10:00:47.692] "remote.SSH.remoteServerListenOnSocket": false
[10:00:47.693] "remote.SSH.showLoginTerminal": true
[10:00:47.693] "remote.SSH.defaultExtensions": []
[10:00:47.693] "remote.SSH.loglevel": 2
[10:00:47.693] "remote.SSH.enableDynamicForwarding": true
[10:00:47.693] "remote.SSH.enableRemoteCommand": false
[10:00:47.693] "remote.SSH.serverPickPortsFromRange": {}
[10:00:47.694] "remote.SSH.serverInstallPath": {}
[10:00:47.696] VS Code version: 1.77.1
[10:00:47.696] Remote-SSH version: remote-ssh@0.98.0
[10:00:47.696] darwin x64
[10:00:47.698] SSH Resolver called for host: keiferpi2.local
[10:00:47.698] Setting up SSH remote "keiferpi2.local"
[10:00:47.702] Acquiring local install lock: /var/folders/zn/hm2_qvmd6wqdkygd66j0dhx40000gp/T/vscode-remote-ssh-32219cfd-install.lock
[10:00:47.704] Looking for existing server data file at /Users/bradold2/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-32219cfd-b7886d7461186a5eac768481578c1d7ca80e2d21-0.98.0/data.json
[10:00:47.705] Using commit id "b7886d7461186a5eac768481578c1d7ca80e2d21" and quality "stable" for server
[10:00:47.710] Install and start server if needed
[10:00:47.719] PATH: /Users/bradold2/bin:/usr/local/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
[10:00:47.719] Checking ssh with "ssh -V"
[10:00:47.743] > OpenSSH_9.0p1, LibreSSL 3.3.6

[10:00:47.746] askpass server listening on /var/folders/zn/hm2_qvmd6wqdkygd66j0dhx40000gp/T/vscode-ssh-askpass-39b2963963630b92e015c67c24840ec285bd5e40.sock
[10:00:47.747] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/zn/hm2_qvmd6wqdkygd66j0dhx40000gp/T/vscode-ssh-askpass-6747829726f1aee54116a1a89379a5017da34988.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","64573","-o","ConnectTimeout=15","keiferpi2.local"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/bradold2/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-32219cfd-b7886d7461186a5eac768481578c1d7ca80e2d21-0.98.0/data.json"}
[10:00:47.747] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.kXVDzdWcvO/Listeners","SHELL":"/bin/zsh","DISPLAY":"/private/tmp/com.apple.launchd.XCDoVigO42/org.macosforge.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/bradold2/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/bradold2/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/zn/hm2_qvmd6wqdkygd66j0dhx40000gp/T/vscode-ssh-askpass-39b2963963630b92e015c67c24840ec285bd5e40.sock"}
[10:00:47.751] Spawned 8631
[10:00:48.008] > local-server-1> Running ssh connection command: "-v -T -D 64573 -o ConnectTimeout=15 keiferpi2.local"
[10:00:48.013] > local-server-1> Spawned ssh, pid=8636
[10:00:48.022] stderr> OpenSSH_9.0p1, LibreSSL 3.3.6
[10:00:48.127] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:Sp3/0t6ovCGmXf2O12JHP+ULhLWesii6mHrIAAskcZg
[10:00:48.206] stderr> Authenticated to keiferpi2.local ([fe80::21bb:6e09:3f33:dc0%en0]:22) using "publickey".
[10:00:48.365] > Linux keiferpi2 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64
> 
> The programs included with the Debian GNU/Linux system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
> permitted by applicable law.
> ready: 358fe4840d0d
[10:00:48.372] > Linux 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023
[10:00:48.372] Platform: linux
[10:00:48.380] > /bin/bash
[10:00:48.381] Shell: bash
[10:00:48.381] Creating bash subshell inside "bash"
[10:00:48.391] > bash version:  5.1.4(1)-release
[10:00:48.434] > 358fe4840d0d: running
[10:00:53.893] > Acquiring lock on /home/brad/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/vscode-remote-lock.brad.b7886d7461186a5eac768481578c1d7ca80e2d21
> Installing to /home/brad/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21...
> 358fe4840d0d%%1%%
[10:00:53.909] > Downloading with wget
[10:00:59.440] > Download complete
[10:00:59.451] > 358fe4840d0d%%2%%
> tar --version:
[10:00:59.454] > tar (GNU tar) 1.34
> Copyright (C) 2021 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[10:01:02.876] > Checking /home/brad/.vscode-server/.b7886d7461186a5eac768481578c1d7ca80e2d21.log and /home/brad/.vscode-server/.b7886d7461186a5eac768481578c1d7ca80e2d21.pid for a running server
[10:01:02.927] > Running ssh connection command... /home/brad/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all   &> "/home/brad/.vscode-server/.b7886d7461186a5eac768481578c1d7ca80e2d21.log" < /dev/null
> printenv:
[10:01:02.931] >     SHELL=/bin/bash
>     LANGUAGE=en_US.UTF-8
>     NO_AT_BRIDGE=1
>     PWD=/home/brad
>     LOGNAME=brad
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/home/brad
>     LANG=en_US.UTF-8
>     VSCODE_AGENT_FOLDER=/home/brad/.vscode-server
>     SSH_CONNECTION=fe80::1c49:d26d:ebf4:9f43%eth0 64574 fe80::21bb:6e09:3f33:dc0%eth0 22
>     XDG_SESSION_CLASS=user
>     USER=brad
>     SHLVL=1
>     XDG_SESSION_ID=51
>     XDG_RUNTIME_DIR=/run/user/1001
>     SSH_CLIENT=fe80::1c49:d26d:ebf4:9f43%eth0 64574 22
>     LC_ALL=en_US.UTF-8
>     XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
>     PATH=/home/brad/.local/bin:/home/brad/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/snap/bin
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus
>     OLDPWD=/home/brad/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21
>     TEXTDOMAIN=Linux-PAM
>     _=/usr/bin/printenv
[10:01:02.939] stderr> rm: cannot remove '/home/brad/.vscode-server/.b7886d7461186a5eac768481578c1d7ca80e2d21.token'
[10:01:02.940] stderr> : No such file or directory
[10:01:02.946] > Spawned remote server: 20535
[10:01:02.955] > Waiting for server log...
[10:01:02.996] > Waiting for server log...
[10:01:03.036] > Waiting for server log...
[10:01:03.079] > Waiting for server log...
[10:01:03.120] > Waiting for server log...
[10:01:03.161] > Waiting for server log...
[10:01:03.201] > Waiting for server log...
[10:01:03.242] > Waiting for server log...
[10:01:03.283] > Waiting for server log...
[10:01:03.324] > Waiting for server log...
[10:01:03.366] > Waiting for server log...
[10:01:03.405] > Waiting for server log...
[10:01:03.446] > Waiting for server log...
[10:01:03.486] > Waiting for server log...
[10:01:03.527] > Waiting for server log...
[10:01:03.567] > Waiting for server log...
[10:01:03.608] > Waiting for server log...
[10:01:03.649] > Waiting for server log...
[10:01:03.689] > Waiting for server log...
[10:01:03.730] > Waiting for server log...
[10:01:03.771] > Waiting for server log...
[10:01:03.812] > Waiting for server log...
[10:01:03.852] > Waiting for server log...
[10:01:03.893] > Waiting for server log...
[10:01:03.932] > Waiting for server log...
[10:01:03.974] > Waiting for server log...
[10:01:04.013] > Waiting for server log...
[10:01:04.054] > Waiting for server log...
[10:01:04.095] > Waiting for server log...
[10:01:04.141] > Waiting for server log...
[10:01:04.187] > Waiting for server log...
[10:01:04.235] > Waiting for server log...
[10:01:04.286] > Waiting for server log...
[10:01:04.330] > Waiting for server log...
[10:01:04.379] > Waiting for server log...
[10:01:04.425] > Waiting for server log...
[10:01:04.475] > Waiting for server log...
[10:01:04.520] > Waiting for server log...
[10:01:04.566] > Waiting for server log...
[10:01:04.612] > Waiting for server log...
[10:01:04.658] > Waiting for server log...
[10:01:04.704] > Waiting for server log...
[10:01:04.752] > Waiting for server log...
[10:01:04.798] > Waiting for server log...
[10:01:04.845] > Waiting for server log...
[10:01:04.894] > Waiting for server log...
[10:01:04.942] > Waiting for server log...
[10:01:04.990] > Waiting for server log...
[10:01:05.039] > Waiting for server log...
[10:01:05.087] > Waiting for server log...
[10:01:05.135] > Waiting for server log...
[10:01:05.182] > Waiting for server log...
[10:01:05.230] > Waiting for server log...
[10:01:05.277] > Waiting for server log...
[10:01:05.324] > Waiting for server log...
[10:01:05.376] > Waiting for server log...
[10:01:05.424] > Waiting for server log...
[10:01:05.471] > Waiting for server log...
[10:01:05.517] > Waiting for server log...
[10:01:05.564] > Waiting for server log...
[10:01:05.610] > Waiting for server log...
[10:01:05.657] > Waiting for server log...
[10:01:05.705] > Waiting for server log...
[10:01:05.754] > Waiting for server log...
[10:01:05.801] > Waiting for server log...
[10:01:05.849] > Waiting for server log...
[10:01:05.896] > Waiting for server log...
[10:01:05.944] > Waiting for server log...
[10:01:05.991] > Waiting for server log...
[10:01:06.039] > Waiting for server log...
[10:01:06.087] > Waiting for server log...
[10:01:06.135] > Waiting for server log...
[10:01:06.182] > Waiting for server log...
[10:01:06.229] > Waiting for server log...
[10:01:06.277] > Waiting for server log...
[10:01:06.328] > Waiting for server log...
[10:01:06.375] > Waiting for server log...
[10:01:06.422] > Waiting for server log...
[10:01:06.468] > Waiting for server log...
[10:01:06.513] > Waiting for server log...
[10:01:06.559] > Waiting for server log...
[10:01:06.607] > Waiting for server log...
[10:01:06.654] > Waiting for server log...
[10:01:06.702] > Waiting for server log...
[10:01:06.751] > Waiting for server log...
[10:01:06.798] > Waiting for server log...
[10:01:06.846] > Waiting for server log...
[10:01:06.892] > Waiting for server log...
[10:01:06.940] > Waiting for server log...
[10:01:06.991] > Waiting for server log...
[10:01:07.038] > Waiting for server log...
[10:01:07.085] > Waiting for server log...
[10:01:07.130] > Waiting for server log...
[10:01:07.177] > Waiting for server log...
[10:01:07.223] > Waiting for server log...
[10:01:07.271] > Waiting for server log...
[10:01:07.319] > Waiting for server log...
[10:01:07.365] > Waiting for server log...
[10:01:07.411] > Waiting for server log...
[10:01:07.458] > Waiting for server log...
[10:01:07.506] > Waiting for server log...
[10:01:07.553] > Waiting for server log...
[10:01:07.599] > Waiting for server log...
[10:01:07.647] > Waiting for server log...
[10:01:07.696] > Waiting for server log...
[10:01:07.743] > Waiting for server log...
[10:01:07.788] > Waiting for server log...
[10:01:07.834] > Waiting for server log...
[10:01:07.879] > Waiting for server log...
[10:01:07.933] > Waiting for server log...
[10:01:07.971] > Waiting for server log...
[10:01:08.017] > Waiting for server log...
[10:01:08.064] > Waiting for server log...
[10:01:08.111] > Waiting for server log...
[10:01:08.159] > Waiting for server log...
[10:01:08.206] > Waiting for server log...
[10:01:08.254] > Waiting for server log...
[10:01:08.301] > Waiting for server log...
[10:01:08.349] > Waiting for server log...
[10:01:08.398] > Waiting for server log...
[10:01:08.445] > Waiting for server log...
[10:01:08.492] > Waiting for server log...
[10:01:08.539] > Waiting for server log...
[10:01:08.586] > Waiting for server log...
[10:01:08.634] > Waiting for server log...
[10:01:08.680] > Waiting for server log...
[10:01:08.727] > Waiting for server log...
[10:01:08.775] > Waiting for server log...
[10:01:08.822] > Waiting for server log...
[10:01:08.869] > Waiting for server log...
[10:01:08.917] > Waiting for server log...
[10:01:08.963] > Waiting for server log...
[10:01:09.008] > Waiting for server log...
[10:01:09.055] > Waiting for server log...
[10:01:09.102] > Waiting for server log...
[10:01:09.151] > Waiting for server log...
[10:01:09.198] > Waiting for server log...
[10:01:09.245] > Waiting for server log...
[10:01:09.291] > Waiting for server log...
[10:01:09.338] > Waiting for server log...
[10:01:09.384] > Waiting for server log...
[10:01:09.432] > Waiting for server log...
[10:01:09.479] > Waiting for server log...
[10:01:09.527] > Waiting for server log...
[10:01:09.574] > Waiting for server log...
[10:01:09.621] > Waiting for server log...
[10:01:09.668] > Waiting for server log...
[10:01:09.717] > Waiting for server log...
[10:01:09.763] > Waiting for server log...
[10:01:09.810] > Waiting for server log...
[10:01:09.858] > Waiting for server log...
[10:01:09.905] > Waiting for server log...
[10:01:09.952] > Waiting for server log...
[10:01:10.000] > Waiting for server log...
[10:01:10.046] > Waiting for server log...
[10:01:10.093] > Waiting for server log...
[10:01:10.137] > Waiting for server log...
[10:01:10.185] > Waiting for server log...
[10:01:10.232] > Waiting for server log...
[10:01:10.280] > Waiting for server log...
[10:01:10.327] > Waiting for server log...
[10:01:10.375] > Waiting for server log...
[10:01:10.419] > Waiting for server log...
[10:01:10.466] > Waiting for server log...
[10:01:10.517] > Waiting for server log...
[10:01:10.561] > Waiting for server log...
[10:01:10.606] > Waiting for server log...
[10:01:10.651] > Waiting for server log...
[10:01:10.700] > Waiting for server log...
[10:01:10.748] > Waiting for server log...
[10:01:10.795] > Waiting for server log...
[10:01:10.840] > Waiting for server log...
[10:01:10.892] > Waiting for server log...
[10:01:10.938] > Waiting for server log...
[10:01:10.984] > Waiting for server log...
[10:01:11.033] > Waiting for server log...
[10:01:11.079] > Waiting for server log...
[10:01:11.127] > Waiting for server log...
[10:01:11.174] > Waiting for server log...
[10:01:11.222] > Waiting for server log...
[10:01:11.269] > Waiting for server log...
[10:01:11.324] > Waiting for server log...
[10:01:11.371] > Waiting for server log...
[10:01:11.417] > Waiting for server log...
[10:01:11.462] > Waiting for server log...
[10:01:11.508] > Waiting for server log...
[10:01:11.554] > Waiting for server log...
[10:01:11.600] > Waiting for server log...
[10:01:11.645] > Waiting for server log...
[10:01:11.693] > Waiting for server log...
[10:01:11.740] > Waiting for server log...
[10:01:11.787] > Waiting for server log...
[10:01:11.834] > Waiting for server log...
[10:01:11.881] > Waiting for server log...
[10:01:11.929] > Waiting for server log...
[10:01:11.981] > Waiting for server log...
[10:01:12.029] > Waiting for server log...
[10:01:12.075] > Waiting for server log...
[10:01:12.120] > Waiting for server log...
[10:01:12.167] > Waiting for server log...
[10:01:12.214] > Waiting for server log...
[10:01:12.262] > Waiting for server log...
[10:01:12.307] > Waiting for server log...
[10:01:12.354] > Waiting for server log...
[10:01:12.401] > Waiting for server log...
[10:01:12.448] > Waiting for server log...
[10:01:12.495] > Waiting for server log...
[10:01:12.542] > Waiting for server log...
[10:01:12.588] > Waiting for server log...
[10:01:12.634] > Waiting for server log...
[10:01:12.681] > Waiting for server log...
[10:01:12.728] > Waiting for server log...
[10:01:12.776] > Waiting for server log...
[10:01:12.823] > Waiting for server log...
[10:01:12.871] > Waiting for server log...
[10:01:12.919] > Waiting for server log...
[10:01:12.967] > Waiting for server log...
[10:01:13.013] > Waiting for server log...
[10:01:13.059] > Waiting for server log...
[10:01:13.106] > Waiting for server log...
[10:01:13.153] > Waiting for server log...
[10:01:13.201] > Waiting for server log...
[10:01:13.250] > Waiting for server log...
[10:01:13.300] > Waiting for server log...
[10:01:13.348] > Waiting for server log...
[10:01:13.396] > Waiting for server log...
[10:01:13.443] > Waiting for server log...
[10:01:13.489] > Waiting for server log...
[10:01:13.537] > Waiting for server log...
[10:01:13.585] > Waiting for server log...
[10:01:13.628] > Waiting for server log...
[10:01:13.675] > Waiting for server log...
[10:01:13.723] > Waiting for server log...
[10:01:13.770] > Waiting for server log...
[10:01:13.816] > Waiting for server log...
[10:01:13.861] > Waiting for server log...
[10:01:13.908] > Waiting for server log...
[10:01:13.953] > Waiting for server log...
[10:01:13.999] > Waiting for server log...
[10:01:14.046] > Waiting for server log...
[10:01:14.094] > Waiting for server log...
[10:01:14.140] > Waiting for server log...
[10:01:14.188] > Waiting for server log...
[10:01:14.234] > Waiting for server log...
[10:01:14.282] > Waiting for server log...
[10:01:14.327] > Waiting for server log...
[10:01:14.374] > Waiting for server log...
[10:01:14.420] > Waiting for server log...
[10:01:14.466] > Waiting for server log...
[10:01:14.513] > Waiting for server log...
[10:01:14.561] > Waiting for server log...
[10:01:14.608] > Waiting for server log...
[10:01:14.656] > Waiting for server log...
[10:01:14.702] > Waiting for server log...
[10:01:14.750] > Waiting for server log...
[10:01:14.798] > Waiting for server log...
[10:01:14.845] > Waiting for server log...
[10:01:14.893] > Waiting for server log...
[10:01:14.940] > Waiting for server log...
[10:01:14.988] > Waiting for server log...
[10:01:15.035] > Waiting for server log...
[10:01:15.084] > Waiting for server log...
[10:01:15.129] > Waiting for server log...
[10:01:15.174] > Waiting for server log...
[10:01:15.221] > Waiting for server log...
[10:01:15.268] > Waiting for server log...
[10:01:15.316] > Waiting for server log...
[10:01:15.362] > Waiting for server log...
[10:01:15.411] > Waiting for server log...
[10:01:15.457] > Waiting for server log...
[10:01:15.505] > Waiting for server log...
[10:01:15.552] > Waiting for server log...
[10:01:15.600] > Waiting for server log...
[10:01:15.647] > Waiting for server log...
[10:01:15.694] > Waiting for server log...
[10:01:15.742] > Waiting for server log...
[10:01:15.788] > Waiting for server log...
[10:01:15.836] > Waiting for server log...
[10:01:15.883] > Waiting for server log...
[10:01:15.928] > Waiting for server log...
[10:01:15.974] > Waiting for server log...
[10:01:16.021] > Waiting for server log...
[10:01:16.070] > Waiting for server log...
[10:01:16.117] > Waiting for server log...
[10:01:16.164] > Waiting for server log...
[10:01:16.212] > Waiting for server log...
[10:01:16.260] > Waiting for server log...
[10:01:16.309] > Waiting for server log...
[10:01:16.352] > Waiting for server log...
[10:01:16.399] > Waiting for server log...
[10:01:16.446] > Waiting for server log...
[10:01:16.494] > Waiting for server log...
[10:01:16.542] > Waiting for server log...
[10:01:16.592] > Waiting for server log...
[10:01:16.635] > Waiting for server log...
[10:01:16.680] > Waiting for server log...
[10:01:16.727] > Waiting for server log...
[10:01:16.775] > Waiting for server log...
[10:01:16.821] > Waiting for server log...
[10:01:16.870] > Waiting for server log...
[10:01:16.917] > Waiting for server log...
[10:01:16.965] > Waiting for server log...
[10:01:17.018] > Waiting for server log...
[10:01:17.066] > Waiting for server log...
[10:01:17.112] > Waiting for server log...
[10:01:17.158] > Waiting for server log...
[10:01:17.205] > Waiting for server log...
[10:01:17.308] > Waiting for server log...
[10:01:17.316] > Waiting for server log...
[10:01:17.365] > Waiting for server log...
[10:01:17.393] > Waiting for server log...
[10:01:17.438] > Waiting for server log...
[10:01:17.484] > Waiting for server log...
[10:01:17.532] > Waiting for server log...
[10:01:17.580] > Waiting for server log...
[10:01:17.632] > Waiting for server log...
[10:01:17.679] > Waiting for server log...
[10:01:17.725] > Waiting for server log...
[10:01:17.770] > Waiting for server log...
[10:01:17.816] >  
> *
> * Visual Studio Code Server
[10:01:17.817] > *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
>  
[10:01:17.842] > Server did not start successfully. Full server log at /home/brad/.vscode-server/.b7886d7461186a5eac768481578c1d7ca80e2d21.log >>>
[10:01:17.846] > /home/brad/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/bin/code-server: 12: /home/brad/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/node: not found
[10:01:17.847] > <<< End of server log
> 358fe4840d0d: start
> exitCode==32==
> listeningOn====
> osReleaseId==raspbian==
> arch==aarch64==
> tmpDir==/run/user/1001==
> platform==linux==
> unpackResult==success==
[10:01:17.850] > didLocalDownload==0==
> downloadTime==5552==
> installTime==3377==
> extInstallTime====
> serverStartTime==14877==
> 358fe4840d0d: end
[10:01:17.851] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==raspbian==
arch==aarch64==
tmpDir==/run/user/1001==
platform==linux==
unpackResult==success==didLocalDownload==0==
downloadTime==5552==
installTime==3377==
extInstallTime====
serverStartTime==14877==

[10:01:17.852] Terminating local server
[10:01:17.858] Resolver error: Error: The VS Code Server failed to start
	at m.ServerInstallError (/Users/bradold2/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:584322)
	at f (/Users/bradold2/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:578379)
	at t.handleInstallOutput (/Users/bradold2/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:581404)
	at Object.e [as tryInstallWithLocalServer] (/Users/bradold2/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:623670)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/bradold2/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:643639
	at async t.withShowDetailsEvent (/Users/bradold2/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:647359)
	at async /Users/bradold2/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:622142
	at async C (/Users/bradold2/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:618648)
	at async t.resolveWithLocalServer (/Users/bradold2/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:621757)
	at async t.resolve (/Users/bradold2/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:644967)
	at async /Users/bradold2/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:720839
[10:01:17.862] Local server exit: 15
[10:01:17.873] ------
```

</p>
</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/2947
