### ISSUE TITLE
Mac: "kex_exchange_identification: Connection closed by remote host" when accessing a remote server with a jump server on vs code.

### ISSUE THREAD

**Issue by JiangTao-thu** [microsoft/vscode-remote-release#8343]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

macos: 13.3.1 (22E261)
Remote-SSH: v0.98.0
Remote.SSH: Use Local Server: disable

My ssh config:
> Host jump-box
>   HostName 166.111.32.48
>   User jiangt
> 
> \# The Remote Host
> Host target-box
>   HostName hepfarm40
>   User jiang-t18
>   ProxyJump ssh -q -W %h:%p jump-box
> 
Remote.SSH: Enable Remote Command: 
Log: attached below

I tried to access a remote server , which I can access successfully on Mac's terminal step by step, using a jump server with vscode but got an error:
> ssh: Could not resolve hostname ssh: nodename nor servname provided, or not known
>\> kex_exchange_identification: Connection closed by remote host

permission appears to be fine:
> -rw-------@  1 macguffin  staff   256  4  8 18:57 config
> -rw-------@  1 macguffin  staff  3389  4  8 16:26 id_rsa
> -rw-------@  1 macguffin  staff   747  4  8 16:26 id_rsa.pub
> -rw-------@  1 macguffin  staff     0  4  8 19:18 known_hosts

I also tried the pre-release version but the error remains.
Specifically, I can access the jump server successfully via vscode, which seems strange.

### Remote-SSH Log

[20:21:08.653] Log Level: 2
[20:21:08.659] SSH Resolver called for "ssh-remote+target-box", attempt 1
[20:21:08.659] "remote.SSH.useLocalServer": false
[20:21:08.659] "remote.SSH.showLoginTerminal": false
[20:21:08.659] "remote.SSH.remotePlatform": {}
[20:21:08.659] "remote.SSH.path": undefined
[20:21:08.659] "remote.SSH.configFile": undefined
[20:21:08.659] "remote.SSH.useFlock": true
[20:21:08.659] "remote.SSH.lockfilesInTmp": false
[20:21:08.659] "remote.SSH.localServerDownload": auto
[20:21:08.659] "remote.SSH.remoteServerListenOnSocket": false
[20:21:08.660] "remote.SSH.showLoginTerminal": false
[20:21:08.660] "remote.SSH.defaultExtensions": []
[20:21:08.660] "remote.SSH.loglevel": 2
[20:21:08.660] "remote.SSH.enableDynamicForwarding": true
[20:21:08.660] "remote.SSH.enableRemoteCommand": false
[20:21:08.660] "remote.SSH.serverPickPortsFromRange": {}
[20:21:08.660] "remote.SSH.serverInstallPath": {}
[20:21:08.661] VS Code version: 1.77.1
[20:21:08.661] Remote-SSH version: remote-ssh@0.98.0
[20:21:08.661] darwin arm64
[20:21:08.662] SSH Resolver called for host: target-box
[20:21:08.662] Setting up SSH remote "target-box"
[20:21:08.664] Using commit id "b7886d7461186a5eac768481578c1d7ca80e2d21" and quality "stable" for server
[20:21:08.666] Install and start server if needed
[20:21:10.739] PATH: /usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/opt/homebrew/bin
[20:21:10.740] Checking ssh with "ssh -V"
[20:21:10.745] > OpenSSH_9.0p1, LibreSSL 3.3.6

[20:21:10.746] Running script with connection command: ssh -T -D 51978 -o ConnectTimeout=15 'target-box' bash
[20:21:10.973] > ssh: Could not resolve hostname ssh: nodename nor servname provided, or not known
\> kex_exchange_identification: Connection closed by remote host
\> Connection closed by UNKNOWN port 65535
[20:21:10.973] Got some output, clearing connection timeout
[20:21:11.219] "install" terminal command done
[20:21:11.220] Install terminal quit with output: Connection closed by UNKNOWN port 65535
[20:21:11.220] Received install output: Connection closed by UNKNOWN port 65535
[20:21:11.220] Failed to parse remote port from server output
[20:21:11.221] Resolver error: Error: 
	at m.Create (/Users/macguffin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:584388)
	at t.handleInstallOutput (/Users/macguffin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:582948)
	at t.tryInstall (/Users/macguffin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:681793)
	at async /Users/macguffin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:644041
	at async t.withShowDetailsEvent (/Users/macguffin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:647359)
	at async t.resolve (/Users/macguffin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:645091)
	at async /Users/macguffin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:720839

### Log for ssh -T -D 61480 -o ConnectTimeout=15 'target-box'

kex_exchange_identification: Connection closed by remote host
Connection closed by 127.0.0.1 port 7890
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
macguffin@TaodeMBP .ssh % ssh -vvv  -T -D 61480 -o ConnectTimeout=15 'target-box'
OpenSSH_9.0p1, LibreSSL 3.3.6
debug1: Reading configuration data /Users/macguffin/.ssh/config
debug1: /Users/macguffin/.ssh/config line 11: Applying options for target-box
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
debug1: /etc/ssh/ssh_config line 54: Applying options for *
debug1: Setting implicit ProxyCommand from ProxyJump: ssh -vvv -W '[%h]:%p' ssh
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/Users/macguffin/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/Users/macguffin/.ssh/known_hosts2'
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Executing proxy command: exec ssh -vvv -W '[hepfarm40]:22' ssh
debug3: timeout: 15000 ms remain after connect
debug1: identity file /Users/macguffin/.ssh/id_rsa type 0
debug1: identity file /Users/macguffin/.ssh/id_rsa-cert type -1
debug1: identity file /Users/macguffin/.ssh/id_ecdsa type -1
debug1: identity file /Users/macguffin/.ssh/id_ecdsa-cert type -1
debug1: identity file /Users/macguffin/.ssh/id_ecdsa_sk type -1
debug1: identity file /Users/macguffin/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /Users/macguffin/.ssh/id_ed25519 type -1
debug1: identity file /Users/macguffin/.ssh/id_ed25519-cert type -1
debug1: identity file /Users/macguffin/.ssh/id_ed25519_sk type -1
debug1: identity file /Users/macguffin/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /Users/macguffin/.ssh/id_xmss type -1
debug1: identity file /Users/macguffin/.ssh/id_xmss-cert type -1
debug1: identity file /Users/macguffin/.ssh/id_dsa type -1
debug1: identity file /Users/macguffin/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.0
OpenSSH_9.0p1, LibreSSL 3.3.6
debug1: Reading configuration data /Users/macguffin/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
debug1: /etc/ssh/ssh_config line 54: Applying options for *
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/Users/macguffin/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/Users/macguffin/.ssh/known_hosts2'
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Connecting to ssh port 22.
debug1: Connection established.
debug1: identity file /Users/macguffin/.ssh/id_rsa type 0
debug1: identity file /Users/macguffin/.ssh/id_rsa-cert type -1
debug1: identity file /Users/macguffin/.ssh/id_ecdsa type -1
debug1: identity file /Users/macguffin/.ssh/id_ecdsa-cert type -1
debug1: identity file /Users/macguffin/.ssh/id_ecdsa_sk type -1
debug1: identity file /Users/macguffin/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /Users/macguffin/.ssh/id_ed25519 type -1
debug1: identity file /Users/macguffin/.ssh/id_ed25519-cert type -1
debug1: identity file /Users/macguffin/.ssh/id_ed25519_sk type -1
debug1: identity file /Users/macguffin/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /Users/macguffin/.ssh/id_xmss type -1
debug1: identity file /Users/macguffin/.ssh/id_xmss-cert type -1
debug1: identity file /Users/macguffin/.ssh/id_dsa type -1
debug1: identity file /Users/macguffin/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.0
kex_exchange_identification: Connection closed by remote host
Connection closed by 127.0.0.1 port 7890
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535

**Comment by roblourens** [comment]
Sorry I'm a little confused, it looks like you are having this issue when connecting manually with ssh in a terminal? Is that right?

**Comment by JiangTao-thu** [comment]
> Sorry I'm a little confused, it looks like you are having this issue when connecting manually with ssh in a terminal? Is that right?

Sorry if I didn't explain it clearly enough. It's almost the same meaning, but there are some differences. I checked the error message and used ssh -vvv on the terminal to expect more detailed logs, which was the second log attached above. However, manually connecting to the jump server and then using ssh to connect to the target server on the jump server is feasible, and even using ssh remote to connect to the jump server is also feasible.

**Comment by roblourens** [comment]
> ssh: Could not resolve hostname ssh: nodename nor servname provided, or not known

This is just ssh telling us that it couldn't resolve the hostname you're trying to connect to- either because it wasn't using your ssh config or something in your ssh config is wrong.

You might try enabling `remote.SSH.useLocalServer`, it looks like you've disabled it

**Comment by JiangTao-thu** [comment]
> > ssh: Could not resolve hostname ssh: nodename nor servname provided, or not known
> 
> This is just ssh telling us that it couldn't resolve the hostname you're trying to connect to- either because it wasn't using your ssh config or something in your ssh config is wrong.
> 
> You might try enabling `remote.SSH.useLocalServer`, it looks like you've disabled it

Thanks for your reply! I tried to be disabled it but the error message remain the same. A few days ago, it could still connect successfully through the config file, so it may not be due to the wrong configuration file issues.

**Comment by roblourens** [comment]
Nothing changed in Remote-SSH over the past few days- I'm afraid this is going to be an issue on your end.
