### ISSUE TITLE
Could not establish connection to "".The VS Code Server failed to start.

### ISSUE THREAD

**Issue by aleodor5** [microsoft/vscode-remote-release#8361]
Type: <b>Bug</b>

Hello,
I want to connect via ssh to the raspberry pi 4, but it doesn't work even if I enter the data correctly. I keep getting this error.I also tried Remote SSH: kill VS Code Server on Host and Remote-SSH: Uninstall VS Code Server from Host. Neither method worked.
![image](https://user-images.githubusercontent.com/130148141/230595124-45225706-8ee9-4de3-a5ff-89d3797d794c.png)

**Comment by aleodor5** [comment]
> Please share the log from the Remote-SSH output channel

> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-lice
> nse) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacyst
[11:10:05.944] > 
> atement).
> *
> 
[11:10:05.964] > Server did not start successfully. Full server log at /home/pi/.vscode-serve
> r/.b7886d7461186a5eac768481578c1d7ca80e2d21.log >>>
> /home/pi/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca80e2d21/bin/cod
[11:10:05.969] > 
> e-server: 12: /home/pi/.vscode-server/bin/b7886d7461186a5eac768481578c1d7ca8
> 0e2d21/node: not found
> <<< End of server log
> 1b1d7bdad818: start
> exitCode==32==
> listeningOn====
> osReleaseId==raspbian==
> arch==aarch64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==14025==
> 1b1d7bdad818: end
[11:10:05.969] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==raspbian==
arch==aarch64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==14025==

[11:10:05.971] Resolver error: Error: The VS Code Server failed to start
    at m.ServerInstallError (c:\Users\x\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:584322)
    at f (c:\Users\x\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:578379)
    at t.handleInstallOutput (c:\Users\x\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:581404)
    at t.tryInstall (c:\Users\x\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:681793)
    at async c:\Users\x\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:644041
    at async t.withShowDetailsEvent (c:\Users\x\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:647359)
    at async t.resolve (c:\Users\x\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:645091)
    at async c:\Users\x\.vscode\extensions\ms-vscode-remote.remote-ssh-0.98.0\out\extension.js:1:720839
[11:10:05.977] ------




[11:10:06.331] > 
[11:10:07.263] "install" terminal command done
[11:10:07.264] Install terminal quit with output:

**Comment by roblourens** [comment]
Looks like https://github.com/microsoft/vscode-remote-release/issues/2947, we've got a fix in the pre-release build of the extension

**Comment by edorgeville** [comment]
Pre-release version `v0.101.2023050515` does fix the issue 🎆
