### ISSUE TITLE
[Remote-SSH Bug]: 

### ISSUE THREAD

**Issue by bitchenhui** [microsoft/vscode-remote-release#8368]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### ->

```
[17:43:28.521] Log Level: 2
[17:43:28.528] SSH Resolver called for "ssh-remote+jumpserver", attempt 1
[17:43:28.528] "remote.SSH.useLocalServer": true
[17:43:28.529] "remote.SSH.path": undefined
[17:43:28.529] "remote.SSH.configFile": undefined
[17:43:28.529] "remote.SSH.useFlock": true
[17:43:28.529] "remote.SSH.lockfilesInTmp": false
[17:43:28.529] "remote.SSH.localServerDownload": auto
[17:43:28.529] "remote.SSH.remoteServerListenOnSocket": false
[17:43:28.529] "remote.SSH.showLoginTerminal": false
[17:43:28.529] "remote.SSH.defaultExtensions": []
[17:43:28.529] "remote.SSH.loglevel": 2
[17:43:28.529] "remote.SSH.enableDynamicForwarding": true
[17:43:28.529] "remote.SSH.enableRemoteCommand": false
[17:43:28.529] "remote.SSH.serverPickPortsFromRange": {}
[17:43:28.529] "remote.SSH.serverInstallPath": {}
[17:43:28.531] VS Code version: 1.77.3
[17:43:28.531] Remote-SSH version: remote-ssh@0.100.0
[17:43:28.531] darwin arm64
[17:43:28.531] SSH Resolver called for host: jumpserver
[17:43:28.532] Setting up SSH remote "jumpserver"
[17:43:28.533] Acquiring local install lock: /var/folders/q3/8cb63gjx2_7f6892mp_71hnm0000gn/T/vscode-remote-ssh-6d2cc25a-install.lock
[17:43:28.534] Looking for existing server data file at /Users/ppred/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-6d2cc25a-704ed70d4fd1c6bd6342c436f1ede30d1cff4710-0.100.0/data.json
[17:43:28.534] Using commit id "704ed70d4fd1c6bd6342c436f1ede30d1cff4710" and quality "stable" for server
[17:43:28.536] Install and start server if needed
[17:43:28.538] PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/Library/Application Support/Yunshu/Yunshu.app/Contents/Public:/Applications/Yunshu.app/Contents/Public:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
[17:43:28.538] Checking ssh with "ssh -V"
[17:43:28.547] > OpenSSH_9.0p1, LibreSSL 3.3.6

[17:43:28.549] askpass server listening on /var/folders/q3/8cb63gjx2_7f6892mp_71hnm0000gn/T/vscode-ssh-askpass-721bcfd73a57d1e132bef5066ddbec434c9215ab.sock
[17:43:28.549] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/q3/8cb63gjx2_7f6892mp_71hnm0000gn/T/vscode-ssh-askpass-84a02a19dd8b2a96e915ce56cb6a0c57bcd4ecee.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","49890","-o","ConnectTimeout=15","jumpserver"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/ppred/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-6d2cc25a-704ed70d4fd1c6bd6342c436f1ede30d1cff4710-0.100.0/data.json"}
[17:43:28.549] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.JzpeSHeyV8/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/ppred/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/ppred/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/q3/8cb63gjx2_7f6892mp_71hnm0000gn/T/vscode-ssh-askpass-721bcfd73a57d1e132bef5066ddbec434c9215ab.sock"}
[17:43:28.550] Spawned 40735
[17:43:28.628] > local-server-1> Running ssh connection command: "-v -T -D 49890 -o ConnectTimeout=15 jumpserver"
[17:43:28.629] > local-server-1> Spawned ssh, pid=40741
[17:43:28.634] stderr> OpenSSH_9.0p1, LibreSSL 3.3.6
[17:43:29.279] stderr> debug1: Server host key: ssh-rsa xxxxx
[17:43:29.388] Got askpass request: {"request":"The authenticity of host '212.64.115.70 (212.64.115.70)' can't be established. RSA key fingerprint is SHA256:xxxx. This host key is known by the following other names/addresses: ~/.ssh/known_hosts:6: xxxx.com Are you sure you want to continue connecting (yes/no/[fingerprint])?"}
[17:43:29.388] Detected fingerprint confirmation message
[17:43:29.388] Showing fingerprint confirmation dialog
[17:43:29.389] Listening for interwindow password on /var/folders/q3/8cb63gjx2_7f6892mp_71hnm0000gn/T/vscode-ssh-askpass-c343515cea7d61f897352bfd19c8fde4766b2932.sock
[17:43:29.389] Writing password prompt to globalState
[17:43:32.978] Got fingerprint response: yes
[17:43:32.979] Interactor gave response: yes
[17:43:32.979] Cleaning up other-window auth server
[17:43:33.008] stderr> Warning: Permanently added 'xxxx' (RSA) to the list of known hosts.
[17:43:33.473] stderr> Authenticated to xxxx ([xxxx]:22) using "publickey".
[17:43:33.569] stderr> Transferred: sent 2684, received 1660 bytes, in 0.1 seconds
[17:43:33.569] stderr> Bytes per second: sent 31960.0, received 19766.6
[17:43:33.569] > No PTY requested.
[17:43:33.569] > local-server-1> ssh child died, shutting down
[17:43:33.573] Local server exit: 0
[17:43:33.573] Received install output: local-server-1> Running ssh connection command: "-v -T -D 49890 -o ConnectTimeout=15 jumpserver"
local-server-1> Spawned ssh, pid=40741
OpenSSH_9.0p1, LibreSSL 3.3.6
debug1: Server host key: ssh-rsa SHA256:xxxx
Warning: Permanently added 'xxxx' (RSA) to the list of known hosts.
Authenticated to xxxx ([xxxx]:22) using "publickey".
Transferred: sent 2684, received 1660 bytes, in 0.1 seconds
Bytes per second: sent 31960.0, received 19766.6
No PTY requested.
local-server-1> ssh child died, shutting down

[17:43:33.573] Failed to parse remote port from server output
[17:43:33.575] Resolver error: Error: 
	at m.Create (/Users/ppred/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:584145)
	at t.handleInstallOutput (/Users/ppred/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:582705)
	at Object.e [as tryInstallWithLocalServer] (/Users/ppred/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:623427)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/ppred/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:643396
	at async t.withShowDetailsEvent (/Users/ppred/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:647116)
	at async /Users/ppred/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:621899
	at async C (/Users/ppred/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:618405)
	at async t.resolveWithLocalServer (/Users/ppred/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:621514)
	at async t.resolve (/Users/ppred/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:644724)
	at async /Users/ppred/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:720590
[17:43:33.579] ------
```

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by roblourens** [comment]
Unfortunately the log doesn't really tell us anything other than that the ssh connection was closed before starting the server install script.

> `No PTY requested.`

It's possible that your configuration doesn't like the `-T` flag- there are open issues for that

**Comment by eleanorjboyd** [comment]
Let us know if you tried these suggestions and if they worked or not- thanks!
