### ISSUE TITLE
[Remote-SSH Bug]: Failed to install the VS Code Server when using Code OSS

### ISSUE THREAD

**Issue by sshwy** [microsoft/vscode-remote-release#8377]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [x] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

install VS Code Server successfully.

### Steps To Reproduce

Connect to the remote host using Code OSS on Manjaro (or Arch Linux, perhaps)

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[21:16:11.519] Log Level: 2
[21:16:11.521] SSH Resolver called for "ssh-remote+sshwy.cn", attempt 1
[21:16:11.521] "remote.SSH.useLocalServer": false
[21:16:11.521] "remote.SSH.showLoginTerminal": true
[21:16:11.522] "remote.SSH.remotePlatform": {"zhengruioi.com":"linux"}
[21:16:11.522] "remote.SSH.path": undefined
[21:16:11.522] "remote.SSH.configFile": undefined
[21:16:11.522] "remote.SSH.useFlock": true
[21:16:11.522] "remote.SSH.lockfilesInTmp": false
[21:16:11.522] "remote.SSH.localServerDownload": off
[21:16:11.522] "remote.SSH.remoteServerListenOnSocket": true
[21:16:11.522] "remote.SSH.showLoginTerminal": true
[21:16:11.523] "remote.SSH.defaultExtensions": []
[21:16:11.523] "remote.SSH.loglevel": 2
[21:16:11.523] "remote.SSH.enableDynamicForwarding": true
[21:16:11.523] "remote.SSH.enableRemoteCommand": false
[21:16:11.523] "remote.SSH.serverPickPortsFromRange": {}
[21:16:11.524] "remote.SSH.serverInstallPath": {"zhengruioi.com":".vscode-server"}
[21:16:11.526] VS Code version: 1.77.0
[21:16:11.526] Remote-SSH version: remote-ssh@0.101.2023041015
[21:16:11.526] linux x64
[21:16:11.527] SSH Resolver called for host: sshwy.cn
[21:16:11.527] Setting up SSH remote "sshwy.cn"
[21:16:11.529] Using commit id "7f329fe6c66b0f86ae1574c2911b681ad5a45d63" and quality "stable" for server
[21:16:11.532] Install and start server if needed
[21:16:13.455] PATH: /home/sshwy/.nvm/versions/node/v18.16.0/bin:/home/sshwy/.cargo/bin:/home/sshwy/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/home/sshwy/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/sshwy/.yarn/bin:/home/sshwy/.deno/bin:/home/sshwy/go/bin:/home/sshwy/.cabal/bin:/home/sshwy/.ghcup/bin
[21:16:13.455] Checking ssh with "ssh -V"
[21:16:13.473] > OpenSSH_9.3p1, OpenSSL 3.0.8 7 Feb 2023

[21:16:13.480] Running script with connection command: ssh -T -D 35635 -o ConnectTimeout=15 'sshwy.cn' bash
[21:16:17.813] > 113ce84d90b0: running
[21:16:17.813] Got some output, clearing connection timeout
[21:16:18.026] > Acquiring lock on /home/ubuntu/.vscode-server-oss/bin/7f329fe6c66b0f86ae1574c2911b681ad5a45d63/vscode-remote-lock.ubuntu.7f329fe6c66b0f86ae1574c2911b681ad5a45d63
[21:16:18.031] > Installing to /home/ubuntu/.vscode-server-oss/bin/7f329fe6c66b0f86ae1574c2911b681ad5a45d63...
[21:16:18.349] > 113ce84d90b0%%1%%
> Downloading with wget
[21:16:21.765] > Download complete
> 113ce84d90b0%%2%%
> tar --version:
[21:16:21.774] > tar (GNU tar) 1.30
> Copyright (C) 2017 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[21:16:29.565] > ERROR: /home/ubuntu/.vscode-server-oss/bin/7f329fe6c66b0f86ae1574c2911b681ad5a45d63/node or /home/ubuntu/.vscode-server-oss/bin/7f329fe6c66b0f86ae1574c2911b681ad5a45d63/bin/code-server-oss don't exist
> 113ce84d90b0: start
> exitCode==37==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult==missingFiles==
> didLocalDownload==0==
> downloadTime==3730==
> installTime==1455==
> extInstallTime====
> serverStartTime====
> 113ce84d90b0: end
[21:16:29.565] Received install output: 
exitCode==37==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult==missingFiles==
didLocalDownload==0==
downloadTime==3730==
installTime==1455==
extInstallTime====
serverStartTime====

[21:16:29.566] Resolver error: Error: Failed to install the VS Code Server
	at m.ServerInstallError (/home/sshwy/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.101.2023041015/out/extension.js:1:584079)
	at f (/home/sshwy/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.101.2023041015/out/extension.js:1:578374)
	at t.handleInstallOutput (/home/sshwy/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.101.2023041015/out/extension.js:1:581161)
	at t.tryInstall (/home/sshwy/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.101.2023041015/out/extension.js:1:681881)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/sshwy/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.101.2023041015/out/extension.js:1:644110
	at async t.withShowDetailsEvent (/home/sshwy/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.101.2023041015/out/extension.js:1:647428)
	at async t.resolve (/home/sshwy/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.101.2023041015/out/extension.js:1:645160)
	at async /home/sshwy/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.101.2023041015/out/extension.js:1:720925
[21:16:29.569] ------
```

</p>
</details>

### Anything else?

After this fatal, I inspect files under `/home/ubuntu/.vscode-server-oss/bin/7f329fe6c66b0f86ae1574c2911b681ad5a45d63/` manually. I find that the `node` executable does exist, but the `bin/code-server-oss` does not exist, while instead the `bin/code-server` exists. I guess it's due to a small naming mistake when distributing packages to different platforms.

I've also notices that there's a similar issue #7857 but it was closed without a solution, so I open this issue hopefully to fix it.

**Comment by roblourens** [comment]
This scenario is actually not supported, since the VS Code Remote extensions rely on non-OSS components to communicate with the server
