### ISSUE TITLE
When using MFA code verification, an error was reported: No PTY requested

### ISSUE THREAD

**Issue by tydqcjj** [microsoft/vscode-remote-release#8378]
When I login using SSH, the server requires the input of MFA code。
When I input the code, an error is reported as follows：
```
[11:16:11.899] Got some output, clearing connection timeout
[11:16:12.314] > Please Enter MFA Code.
> [OTP Code]: 
[11:16:16.429] > 8
[11:16:16.565] > 8
[11:16:17.302] > 9
[11:16:18.461] > 3
[11:16:18.742] > 2
[11:16:19.136] > 8
[11:16:20.453] > 
[11:16:20.569] > No PTY requested.
[11:16:21.949] "install" terminal command done
[11:16:21.950] Install terminal quit with output: No PTY requested.
[11:16:21.950] Received install output: No PTY requested.
[11:16:21.951] Failed to parse remote port from server output
[11:16:21.953] Resolver error: Error: 
	at m.Create (c:\Users\junjie.chen\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:584145)
	at t.handleInstallOutput (c:\Users\junjie.chen\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:582705)
	at t.tryInstall (c:\Users\junjie.chen\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:681555)
	at async c:\Users\junjie.chen\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:643798
	at async t.withShowDetailsEvent (c:\Users\junjie.chen\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:647116)
	at async t.resolve (c:\Users\junjie.chen\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:644848)
	at async c:\Users\junjie.chen\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:720590
```

**Comment by roblourens** [comment]
Please see the tips in https://github.com/microsoft/vscode-remote-release/wiki/Debugging-for-Remote-SSH and let me know whether any of that helps
