### ISSUE TITLE
Cannot drag folder out of VS Code to windows

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-remote-release#839]
From #664 

Issue Type: <b>Bug</b>

**Repo**
1. On windows, Open a remote workspace (tested over ssh)
1. Drag a folder from the remote workspace to the windows desktop

**Bug**
Nothing happens. In dev tools console see:

```
ERR Error: EISDIR: illegal operation on a directory, read: EntryIsADirectory (FileSystemError): Error: EISDIR: illegal operation on a directory, read
    at Object.t.createFileSystemProviderError (/home/mattbierner/.vscode-server-insiders/bin/a122c88b4e56318f778d9d2e3800395ee18ecba8/out/vs/server/remoteExtensionHostAgent.js:215:215)
    at b.toFileSystemProviderError (/home/mattbierner/.vscode-server-insiders/bin/a122c88b4e56318f778d9d2e3800395ee18ecba8/out/vs/server/remoteExtensionHostAgent.js:332:761)
    at b.<anonymous> (/home/mattbierner/.vscode-server-insiders/bin/a122c88b4e56318f778d9d2e3800395ee18ecba8/out/vs/server/remoteExtensionHostAgent.js:327:75)
    at Generator.throw (<anonymous>)
    at a (/home/mattbierner/.vscode-server-insiders/bin/a122c88b4e56318f778d9d2e3800395ee18ecba8/out/vs/server/remoteExtensionHostAgent.js:16:505)
```
Extension version: 0.42.2
VS Code version: Code - Insiders 1.36.0-insider (a122c88b4e56318f778d9d2e3800395ee18ecba8, 2019-06-26T21:19:01.595Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.18.0-1014-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|9.72GB (3.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|57%|

|Item|Value|
|---|---|
|Remote|SSH: az-box1|
|OS|Linux x64 4.18.0-1014-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (2 x 2394)|
|Memory (System)|7.79GB (3.88GB free)|
|VM|0%|
</details>

**Comment by isidorn** [comment]
Thanks for testing. However as mentioned in the testplan "we can not drag multiple or a folder due to a chrome limitation)". Due to that we have added a Download command which does just that.
I could leave this open as an upstream issue, though I prefer to close it.
If you disagree feel free to reopen.
