### ISSUE TITLE
[Remote-SSH Bug]: remote container connect linux docker error

### ISSUE THREAD

**Issue by maidouxiaozi** [microsoft/vscode-remote-release#8414]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### Remote-SSH Log

2023-04-27 10:58:45.396 [error] Shell server terminated (code: 255, signal: null)

Error: Exectuable 'wmic' not found on PATH 'C:\Users\xlzhou\AppData\Local\Microsoft\WindowsApps;C:\zxl\vscode\Microsoft VS Code\bin'.
    at m (c:\Users\xlzhou\.vscode\extensions\ms-vscode-remote.remote-containers-0.288.0\dist\common\sshAskpass.js:5:1240)
    at async c:\Users\xlzhou\.vscode\extensions\ms-vscode-remote.remote-containers-0.288.0\dist\common\sshAskpass.js:5:1950 {
  code: 'ENOENT'
}
Permission denied, please try again.
Error: Exectuable 'wmic' not found on PATH 'C:\Users\xlzhou\AppData\Local\Microsoft\WindowsApps;C:\zxl\vscode\Microsoft VS Code\bin'.
    at m (c:\Users\xlzhou\.vscode\extensions\ms-vscode-remote.remote-containers-0.288.0\dist\common\sshAskpass.js:5:1240)
    at async c:\Users\xlzhou\.vscode\extensions\ms-vscode-remote.remote-containers-0.288.0\dist\common\sshAskpass.js:5:1950 {
  code: 'ENOENT'
}
Permission denied, please try again.
Error: Exectuable 'wmic' not found on PATH 'C:\Users\xlzhou\AppData\Local\Microsoft\WindowsApps;C:\zxl\vscode\Microsoft VS Code\bin'.
    at m (c:\Users\xlzhou\.vscode\extensions\ms-vscode-remote.remote-containers-0.288.0\dist\common\sshAskpass.js:5:1240)
    at async c:\Users\xlzhou\.vscode\extensions\ms-vscode-remote.remote-containers-0.288.0\dist\common\sshAskpass.js:5:1950 {
  code: 'ENOENT'
}
root@192.168.29.15: Permission denied (publickey,password).
: Error: Shell server terminated (code: 255, signal: null)

Error: Exectuable 'wmic' not found on PATH 'C:\Users\xlzhou\AppData\Local\Microsoft\WindowsApps;C:\zxl\vscode\Microsoft VS Code\bin'.
    at m (c:\Users\xlzhou\.vscode\extensions\ms-vscode-remote.remote-containers-0.288.0\dist\common\sshAskpass.js:5:1240)
    at async c:\Users\xlzhou\.vscode\extensions\ms-vscode-remote.remote-containers-0.288.0\dist\common\sshAskpass.js:5:1950 {
  code: 'ENOENT'
}
Permission denied, please try again.
Error: Exectuable 'wmic' not found on PATH 'C:\Users\xlzhou\AppData\Local\Microsoft\WindowsApps;C:\zxl\vscode\Microsoft VS Code\bin'.
    at m (c:\Users\xlzhou\.vscode\extensions\ms-vscode-remote.remote-containers-0.288.0\dist\common\sshAskpass.js:5:1240)
    at async c:\Users\xlzhou\.vscode\extensions\ms-vscode-remote.remote-containers-0.288.0\dist\common\sshAskpass.js:5:1950 {
  code: 'ENOENT'
}
Permission denied, please try again.
Error: Exectuable 'wmic' not found on PATH 'C:\Users\xlzhou\AppData\Local\Microsoft\WindowsApps;C:\zxl\vscode\Microsoft VS Code\bin'.
    at m (c:\Users\xlzhou\.vscode\extensions\ms-vscode-remote.remote-containers-0.288.0\dist\common\sshAskpass.js:5:1240)
    at async c:\Users\xlzhou\.vscode\extensions\ms-vscode-remote.remote-containers-0.288.0\dist\common\sshAskpass.js:5:1950 {
  code: 'ENOENT'
}
root@192.168.29.15: Permission denied (publickey,password).

	at m.h (c:\zxl\vscode\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:126151)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by roblourens** [comment]
There is something wrong with your PATH environment variable. We need to be able to access the tool `wmic` in order to connect, but it seems that this has been removed from your PATH.
