### ISSUE TITLE
[Remote-SSH Bug]: bash syntax error when connecting

### ISSUE THREAD

**Issue by ignacioi96** [microsoft/vscode-remote-release#8417]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

Without useLocalServer:

[13:13:53.202] > bash: syntax error: unexpected "(" (expecting "then")
[13:13:53.661] "install" terminal command done
[13:13:53.662] Install terminal quit with output: bash: syntax error: unexpected "(" (expecting "then")
[13:13:53.662] Received install output: bash: syntax error: unexpected "(" (expecting "then")
[13:13:53.665] Failed to parse remote port from server output

With useLocalServer:

Linux 4.1.15-00417-g0c800cffe1f9 #102 SMP PREEMPT Mon Mar 29 09:24:11 CST 2021
/usr/local/niluje/usbnet/bin/ash
bash version: 
bash version: 
bash: 
syntax error: unexpected "(" (expecting "then")
bash version: 
-ash: syntax error: unexpected ")"
Transferred: sent 18256, received 1620 bytes, in 0.2 seconds
Bytes per second: sent 79914.8, received 7091.5
local-server-1> ssh child died, shutting down
[13:19:07.934] Failed to parse remote port from server output

### Expected Behavior

I expected VS Code to connect to ssh host succesfuly.

### Steps To Reproduce

Pop!_OS 22.04 LTS
64-bit

VS Code
Version: 1.77.3

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[13:19:06.213] Log Level: 2
[13:19:06.225] SSH Resolver called for "ssh-remote+192.168.100.243", attempt 1
[13:19:06.226] "remote.SSH.useLocalServer": true
[13:19:06.227] "remote.SSH.path": undefined
[13:19:06.227] "remote.SSH.configFile": ~/.ssh/config
[13:19:06.228] "remote.SSH.useFlock": true
[13:19:06.228] "remote.SSH.lockfilesInTmp": false
[13:19:06.229] "remote.SSH.localServerDownload": auto
[13:19:06.229] "remote.SSH.remoteServerListenOnSocket": false
[13:19:06.229] "remote.SSH.showLoginTerminal": false
[13:19:06.230] "remote.SSH.defaultExtensions": []
[13:19:06.230] "remote.SSH.loglevel": 2
[13:19:06.231] "remote.SSH.enableDynamicForwarding": true
[13:19:06.231] "remote.SSH.enableRemoteCommand": false
[13:19:06.232] "remote.SSH.serverPickPortsFromRange": {}
[13:19:06.232] "remote.SSH.serverInstallPath": {}
[13:19:06.239] VS Code version: 1.77.3
[13:19:06.239] Remote-SSH version: remote-ssh@0.100.0
[13:19:06.239] linux x64
[13:19:06.240] SSH Resolver called for host: 192.168.100.243
[13:19:06.240] Setting up SSH remote "192.168.100.243"
[13:19:06.244] Acquiring local install lock: /tmp/vscode-remote-ssh-01f53000-install.lock
[13:19:06.244] Looking for existing server data file at /home/soy_yogurt/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-01f53000-704ed70d4fd1c6bd6342c436f1ede30d1cff4710-0.100.0/data.json
[13:19:06.245] Using commit id "704ed70d4fd1c6bd6342c436f1ede30d1cff4710" and quality "stable" for server
[13:19:06.248] Install and start server if needed
[13:19:06.252] PATH: /home/soy_yogurt/.nvm/versions/node/v19.7.0/bin:/home/soy_yogurt/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
[13:19:06.252] Checking ssh with "ssh -V"
[13:19:06.258] > OpenSSH_8.9p1 Ubuntu-3ubuntu0.1, OpenSSL 3.0.2 15 Mar 2022

[13:19:06.261] Using SSH config file "/home/soy_yogurt/.ssh/config"
[13:19:06.261] askpass server listening on /run/user/1000/vscode-ssh-askpass-68196b5e04a294b93abd4970ec5cc5103f64e5e8.sock
[13:19:06.261] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-9f3914b1c073b35e2f8ae9d71f905bf6081477bf.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","43491","-o","ConnectTimeout=15","-F","/home/soy_yogurt/.ssh/config","192.168.100.243"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/soy_yogurt/.config/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-01f53000-704ed70d4fd1c6bd6342c436f1ede30d1cff4710-0.100.0/data.json"}
[13:19:06.262] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","SHELL":"/usr/bin/zsh","DISPLAY":":1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/soy_yogurt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code/code","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/soy_yogurt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-68196b5e04a294b93abd4970ec5cc5103f64e5e8.sock"}
[13:19:06.266] Spawned 69665
[13:19:06.346] > local-server-1> Running ssh connection command: "-v -T -D 43491 -o ConnectTimeout=15 -F /home/soy_yogurt/.ssh/config 192.168.100.243"
[13:19:06.349] > local-server-1> Spawned ssh, pid=69673
[13:19:06.352] stderr> OpenSSH_8.9p1 Ubuntu-3ubuntu0.1, OpenSSL 3.0.2 15 Mar 2022
[13:19:06.533] stderr> debug1: Server host key: ssh-ed25519 SHA256:L1PEfxfu1pOG8ZC+o/YrSzK3/1v1ZpAAlxIuLD2s0TA
[13:19:06.667] Got askpass request: {"request":"root@192.168.100.243's password:"}
[13:19:06.668] Showing password prompt
[13:19:06.668] Listening for interwindow password on /run/user/1000/vscode-ssh-askpass-d8560d30aea19d58bb244078712a8fa9efae9bcf.sock
[13:19:06.669] Writing password prompt to globalState
[13:19:07.644] Got password response
[13:19:07.645] Interactor gave response: 
[13:19:07.646] Cleaning up other-window auth server
[13:19:07.686] stderr> Authenticated to 192.168.100.243 ([192.168.100.243]:22) using "password".
[13:19:07.753] > ready: e07fc18773bc
[13:19:07.759] > Linux 4.1.15-00417-g0c800cffe1f9 #102 SMP PREEMPT Mon Mar 29 09:24:11 CST 2021
[13:19:07.760] Platform: linux
[13:19:07.764] > /usr/local/niluje/usbnet/bin/ash
[13:19:07.765] Shell: ash
[13:19:07.766] Creating bash subshell inside "ash"
[13:19:07.822] > bash version: 
[13:19:07.873] > bash version: 
[13:19:07.904] stderr> bash: 
[13:19:07.905] stderr> syntax error: unexpected "(" (expecting "then")
[13:19:07.906] stderr> 
[13:19:07.910] > bash version: 
[13:19:07.915] stderr> -ash: syntax error: unexpected ")"
[13:19:07.918] stderr> Transferred: sent 18256, received 1620 bytes, in 0.2 seconds
[13:19:07.918] stderr> Bytes per second: sent 79914.8, received 7091.5
[13:19:07.920] > local-server-1> ssh child died, shutting down
[13:19:07.930] Local server exit: 0
[13:19:07.931] Received install output: local-server-1> Running ssh connection command: "-v -T -D 43491 -o ConnectTimeout=15 -F /home/soy_yogurt/.ssh/config 192.168.100.243"
local-server-1> Spawned ssh, pid=69673
OpenSSH_8.9p1 Ubuntu-3ubuntu0.1, OpenSSL 3.0.2 15 Mar 2022
debug1: Server host key: ssh-ed25519 SHA256:L1PEfxfu1pOG8ZC+o/YrSzK3/1v1ZpAAlxIuLD2s0TA
Authenticated to 192.168.100.243 ([192.168.100.243]:22) using "password".
ready: e07fc18773bc
Linux 4.1.15-00417-g0c800cffe1f9 #102 SMP PREEMPT Mon Mar 29 09:24:11 CST 2021
/usr/local/niluje/usbnet/bin/ash
bash version: 
bash version: 
bash: 
syntax error: unexpected "(" (expecting "then")
bash version: 
-ash: syntax error: unexpected ")"
Transferred: sent 18256, received 1620 bytes, in 0.2 seconds
Bytes per second: sent 79914.8, received 7091.5
local-server-1> ssh child died, shutting down

[13:19:07.934] Failed to parse remote port from server output
[13:19:07.941] Resolver error: Error: 
	at m.Create (/home/soy_yogurt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:584145)
	at t.handleInstallOutput (/home/soy_yogurt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:582705)
	at Object.e [as tryInstallWithLocalServer] (/home/soy_yogurt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:623427)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/soy_yogurt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:643396
	at async t.withShowDetailsEvent (/home/soy_yogurt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:647116)
	at async /home/soy_yogurt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:621899
	at async C (/home/soy_yogurt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:618405)
	at async t.resolveWithLocalServer (/home/soy_yogurt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:621514)
	at async t.resolve (/home/soy_yogurt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:644724)
	at async /home/soy_yogurt/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:720590
[13:19:07.953] ------
```

</p>
</details>

**Comment by roblourens** [comment]
Thanks, I think this is technically the same as https://github.com/microsoft/vscode-remote-release/issues/4394, even if you are not specifically using Alpine
