### ISSUE TITLE
Got Authentication failed - even Password prompt not displayed

### ISSUE THREAD

**Issue by surapuramakhil** [microsoft/vscode-remote-release#8429]
[10:35:38.778] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 7124 "linprog.cs.fsu.edu" bash
[10:35:38.785] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:35:39.248] > Corrupted MAC on input.
> ssh_dispatch_run_fatal: Connection to 128.186.122.109 port 22: message authentication code incorrect
> The process tried to write to a nonexistent pipe.
> ]0;C:\WINDOWS\System32\cmd.exe
[10:35:39.248] Got some output, clearing connection timeout
[10:35:40.517] "install" terminal command done
[10:35:40.517] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exe
[10:35:40.517] Received install output: ]0;C:\WINDOWS\System32\cmd.exe
[10:35:40.518] Failed to parse remote port from server output
[10:35:40.520] Resolver error: Error: 
	at m.Create (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:584145)
	at t.handleInstallOutput (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:582705)
	at t.tryInstall (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:681555)
	at async c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:643798
	at async t.withShowDetailsEvent (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:647116)
	at async t.resolve (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:644848)
	at async c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:720590
[10:35:40.533] ------

**Comment by roblourens** [comment]
> `Corrupted MAC on input.`

This is an issue with your ssh configuration. If you search for the error message or look up `MACs` in the ssh_config manpage, you will see some info that may help
