### ISSUE TITLE
[Remote-SSH Bug]: Remote ssh cannot connect any ssh connection

### ISSUE THREAD

**Issue by ruban-s** [microsoft/vscode-remote-release#8435]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### Steps To Reproduce

Environment:

Version: 1.78.0-insider
Commit: e410e7c66e7ce5c6bc31f73150d66857804a0ee9
Date: 2023-04-28T12:24:36.251Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.10.0-22-amd64
Sandboxed: Yes

Trying to Connect to ssh connection but not connecting any connection at all.

### Remote-SSH Log

[12:15:57.777] Log Level: 2
[12:15:57.790] VS Code version: 1.78.0-insider
[12:15:57.790] Remote-SSH version: remote-ssh@0.100.0
[12:15:57.790] linux x64
[12:15:57.791] SSH Resolver called for "ssh-remote+15.187.547.245", attempt 1
[12:15:57.792] "remote.SSH.useLocalServer": true
[12:15:57.792] "remote.SSH.path": undefined
[12:15:57.792] "remote.SSH.configFile": undefined
[12:15:57.792] "remote.SSH.useFlock": true
[12:15:57.793] "remote.SSH.lockfilesInTmp": false
[12:15:57.793] "remote.SSH.localServerDownload": auto
[12:15:57.793] "remote.SSH.remoteServerListenOnSocket": false
[12:15:57.793] "remote.SSH.showLoginTerminal": false
[12:15:57.793] "remote.SSH.defaultExtensions": []
[12:15:57.793] "remote.SSH.loglevel": 2
[12:15:57.793] "remote.SSH.enableDynamicForwarding": true
[12:15:57.794] "remote.SSH.enableRemoteCommand": false
[12:15:57.794] "remote.SSH.serverPickPortsFromRange": {}
[12:15:57.794] "remote.SSH.serverInstallPath": {}
[12:15:57.801] SSH Resolver called for host: 15.187.547.245
[12:15:57.801] Setting up SSH remote "15.187.547.245"
[12:15:57.805] Acquiring local install lock: /tmp/vscode-remote-ssh-9aed5675-install.lock
[12:15:57.806] Looking for existing server data file at /home/user/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-9aed5675-e410e7c66e7ce5c6bc31f73150d66857804a0ee9-0.100.0/data.json
[12:15:57.808] Found local server running: {"remoteListeningOn":{"port":39515},"osReleaseId":"debian","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/1000","platform":"linux","connectionToken":"111111a1-1a11-1a11-aa11-111aaa1a11aa","pid":6426,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-2ce033fc5ef8b17c7c4ee794c6260127c6f697ac.sock","socksPort":35967,"startupTime":1682759785780}
[12:15:57.814] Server delay-shutdown request failed: connect ENOENT /run/user/1000/vscode-ssh-askpass-2ce033fc5ef8b17c7c4ee794c6260127c6f697ac.sock
[12:15:57.814] Existing server's health check failed, will start a new one
[12:15:57.814] Using commit id "e410e7c66e7ce5c6bc31f73150d66857804a0ee9" and quality "insider" for server
[12:15:57.818] Install and start server if needed
[12:15:57.823] PATH: /usr/local/go/bin:/root/.rbenv/shims:/root/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.config/composer/vendor/bin
[12:15:57.823] Checking ssh with "ssh -V"
[12:15:57.831] > OpenSSH_8.4p1 Debian-5+deb11u1, OpenSSL 1.1.1n  15 Mar 2022

[12:15:57.835] askpass server listening on /run/user/1000/vscode-ssh-askpass-9e5fabb108e1c142a0f77a1544dc8b20f6cf6bdb.sock
[12:15:57.835] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-9f4a6b277d8dd5b0be567c202e89d41cf06d15c6.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","45813","-o","ConnectTimeout=15","15.187.547.245"],"serverDataFolderName":".vscode-server-insiders","dataFilePath":"/home/user/.config/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-9aed5675-e410e7c66e7ce5c6bc31f73150d66857804a0ee9-0.100.0/data.json"}
[12:15:57.835] Local server env: {"SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","SHELL":"/bin/bash","DISPLAY":":1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/user/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/share/code-insiders/code-insiders","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/user/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-9e5fabb108e1c142a0f77a1544dc8b20f6cf6bdb.sock"}
[12:15:57.840] Spawned 10774
[12:15:57.951] > local-server-1> Running ssh connection command: "-v -T -D 45813 -o ConnectTimeout=15 15.187.547.245"
[12:15:57.956] > local-server-1> Spawned ssh, pid=10783
[12:15:57.959] stderr> OpenSSH_8.4p1 Debian-5+deb11u1, OpenSSL 1.1.1n  15 Mar 2022
[12:15:57.959] stderr> Bad owner or permissions on /home/user/.ssh/config
[12:15:57.960] > local-server-1> ssh child died, shutting down
[12:15:57.964] Local server exit: 0
[12:15:57.964] Received install output: local-server-1> Running ssh connection command: "-v -T -D 45813 -o ConnectTimeout=15 15.187.547.245"
local-server-1> Spawned ssh, pid=10783
OpenSSH_8.4p1 Debian-5+deb11u1, OpenSSL 1.1.1n  15 Mar 2022
Bad owner or permissions on /home/user/.ssh/config
local-server-1> ssh child died, shutting down

[12:15:57.965] Failed to parse remote port from server output
[12:15:57.968] Resolver error: Error: 
	at m.Create (/home/user/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:584145)
	at t.handleInstallOutput (/home/user/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:582705)
	at Object.e [as tryInstallWithLocalServer] (/home/user/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:623427)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/user/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:643396
	at async t.withShowDetailsEvent (/home/user/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:647116)
	at async /home/user/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:621899
	at async C (/home/user/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:618405)
	at async t.resolveWithLocalServer (/home/user/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:621514)
	at async t.resolve (/home/user/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:644724)
	at async /home/user/.vscode-insiders/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:720590
[12:15:57.974] ------

**Comment by ruban-s** [comment]
The Comment is used in ssh using terminal:
`ssh -i Downloads/pemkey.pem bitnami@15.187.547.245  -v -T -D 45813 -o ConnectTimeout=15 15.187.547.245`

**Output Log:**
```
OpenSSH_8.4p1 Debian-5+deb11u1, OpenSSL 1.1.1n  15 Mar 2022
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to 15.187.547.245 [15.187.547.245] port 22.
debug1: fd 3 clearing O_NONBLOCK
debug1: Connection established.
debug1: identity file Downloads/pemkey.pem type -1
debug1: identity file Downloads/pemkey.pem-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.4p1 Debian-5+deb11u1
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.4p1 Debian-5+deb11u1
debug1: match: OpenSSH_8.4p1 Debian-5+deb11u1 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 15.187.547.245:22 as 'bitnami'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:vzQFhboB8oxQyCjyVU4gkKojelmdinMeISbvIQ0OazM
debug1: Host '15.187.547.245' is known and matches the ECDSA host key.
debug1: Found key in /root/.ssh/known_hosts:15
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: Downloads/pemkey.pem  explicit
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: Downloads/pemkey.pem
debug1: Authentication succeeded (publickey).
Authenticated to 15.187.547.245 ([15.187.547.245]:22).
debug1: Local connections to LOCALHOST:45813 forwarded to remote address socks:0
debug1: Local forwarding listening on ::1 port 45813.
debug1: channel 0: new [port listener]
debug1: Local forwarding listening on 127.0.0.1 port 45813.
debug1: channel 1: new [port listener]
debug1: channel 2: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug1: Remote: /home/bitnami/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug1: Sending environment.
debug1: Sending env LANG = en_IN
debug1: Sending command: 15.187.547.245
debug1: client_input_channel_req: channel 2 rtype exit-status reply 0
debug1: client_input_channel_req: channel 2 rtype eow@openssh.com reply 0
bash: line 1: 15.187.547.245: command not found
debug1: channel 2: free: client-session, nchannels 3
debug1: channel 0: free: port listener, nchannels 2
debug1: channel 1: free: port listener, nchannels 1
Transferred: sent 2524, received 2664 bytes, in 0.6 seconds
Bytes per second: sent 4120.0, received 4348.5
debug1: Exit status 127
```
Connection established and not connecting through vscode.
Thanks
