### ISSUE TITLE
[Remote-SSH Bug]: 

### ISSUE THREAD

**Issue by jerempr** [microsoft/vscode-remote-release#8454]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

I would like to connect from my VSCode on my wondows PC to my Raspberry Pi 4B running on Bullseye. It always worked for me. I didnt use this functionnality for 6 month and now trying again, I always get stuck in "Waiting for server log...". 

### Steps To Reproduce

My computer is running windows latest version
The Raspi is running latest version of Bullseye 
I'm using version 0.100 of Remote-SSH

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[21:46:34.932] Log Level: 2
[21:46:34.946] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a225261737062657272795f706572736f5f43435456227d", attempt 1
[21:46:34.947] "remote.SSH.useLocalServer": false
[21:46:34.948] "remote.SSH.showLoginTerminal": true
[21:46:34.948] "remote.SSH.remotePlatform": {"Raspberry_perso_CCTV":"linux"}
[21:46:34.949] "remote.SSH.path": undefined
[21:46:34.949] "remote.SSH.configFile": C:/Users/jerem/.ssh/config
[21:46:34.949] "remote.SSH.useFlock": true
[21:46:34.949] "remote.SSH.lockfilesInTmp": false
[21:46:34.949] "remote.SSH.localServerDownload": auto
[21:46:34.949] "remote.SSH.remoteServerListenOnSocket": false
[21:46:34.950] "remote.SSH.showLoginTerminal": true
[21:46:34.950] "remote.SSH.defaultExtensions": []
[21:46:34.950] "remote.SSH.loglevel": 2
[21:46:34.950] "remote.SSH.enableDynamicForwarding": true
[21:46:34.951] "remote.SSH.enableRemoteCommand": false
[21:46:34.951] "remote.SSH.serverPickPortsFromRange": {}
[21:46:34.953] "remote.SSH.serverInstallPath": {}
[21:46:34.959] VS Code version: 1.78.0
[21:46:34.959] Remote-SSH version: remote-ssh@0.100.0
[21:46:34.959] win32 x64
[21:46:34.961] SSH Resolver called for host: Raspberry_perso_CCTV
[21:46:34.961] Setting up SSH remote "Raspberry_perso_CCTV"
[21:46:34.967] Using commit id "252e5463d60e63238250799aef7375787f68b4ee" and quality "stable" for server
[21:46:34.970] Install and start server if needed
[21:46:34.973] Checking ssh with "C:\Python311\Scripts\ssh.exe -V"
[21:46:34.976] Got error from ssh: spawn C:\Python311\Scripts\ssh.exe ENOENT
[21:46:34.976] Checking ssh with "C:\Python311\ssh.exe -V"
[21:46:34.978] Got error from ssh: spawn C:\Python311\ssh.exe ENOENT
[21:46:34.978] Checking ssh with "C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\ssh.exe -V"
[21:46:34.980] Got error from ssh: spawn C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\ssh.exe ENOENT
[21:46:34.980] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[21:46:34.982] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[21:46:34.983] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[21:46:34.985] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[21:46:34.985] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[21:46:34.987] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[21:46:34.987] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[21:46:34.990] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[21:46:34.990] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[21:46:35.065] > OpenSSH_for_
[21:46:35.065] > Windows_8.6p1, LibreSSL 3.4.3

[21:46:35.073] Using SSH config file "C:/Users/jerem/.ssh/config"
[21:46:35.073] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 57101 -F "C:/Users/jerem/.ssh/config" "Raspberry_perso_CCTV" bash
[21:46:35.077] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[21:46:36.125] > 5ae284d1d133: running
> ]0;C:\WINDOWS\System32\cmd.exe
[21:46:36.125] Got some output, clearing connection timeout
[21:46:36.142] > 5ae284d1d133: running
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[21:46:36.200] > Acquiring lock on /home/blackjack/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/vscode-remote-lock.blackjack.252e5463d60e63238250799aef7375787f68b4ee
[21:46:36.216] > Found existing installation at /home/blackjack/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee...
> Checking /home/blackjack/.vscode-server/.252e5463d60e63238250799aef7375787f68b4ee.log and /home/blackjack/.vscode-server/.252e5463d60e63238250799aef7375787f68b4ee.pid for a running server
> Looking for server with pid: 10559
[21:46:36.268] > Running ssh connection command... /home/blackjack/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all   &> "/home/blackjack/.vscode-server/.252e5463d60e63238250799aef7375787f68b4ee.log" < /dev/null
> printenv:
>     SHELL=/bin/bash
>     PWD=/home/blackjack
>     LOGNAME=blackjack
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/home/blackjack
>     LANG=en_GB.UTF-8
>     VSCODE_AGENT_FOLDER=/home/blackjack/.vscode-server
>     SSH_CONNECTION=192.168.1.161 57103 192.168.1.148 22
>     XDG_SESSION_CLASS=user
>     USER=blackjack
>     SHLVL=0
>     XDG_SESSION_ID=25
>     XDG_RUNTIME_DIR=/run/user/1000
>     SSH_CLIENT=192.168.1.161 57103 22
>     PATH=/usr/local/bin:/usr/bin:/bin:/usr/games
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
>     _=/usr/bin/printenv
[21:46:36.278] > 
> Removing old logfile at /home/blackjack/.vscode-server/.252e5463d60e63238250799aef7375787f68b4ee.log
[21:46:36.292] > 
> Spawned remote server: 12958
[21:46:36.301] > Waiting for server log...
[21:46:36.312] > 
[21:46:36.341] > Waiting for server log...
[21:46:36.358] > 
[21:46:36.384] > Waiting for server log...
[21:46:36.405] > 
[21:46:36.429] > Waiting for server log...
[21:46:36.455] > 
[21:46:36.466] > Waiting for server log...
[21:46:36.507] > Waiting for server log...
[21:46:36.530] > 
[21:46:36.549] > Waiting for server log...
[21:46:36.559] > 
[21:46:36.590] > Waiting for server log...
[21:46:36.605] > 
[21:46:36.636] > Waiting for server log...
[21:46:36.654] > 
[21:46:36.673] > Waiting for server log...
[21:46:36.683] > 
[21:46:36.716] > Waiting for server log...
[21:46:36.733] > 
[21:46:36.758] > Waiting for server log...
[21:46:36.776] > 
[21:46:36.799] > Waiting for server log...
[21:46:36.808] > 
[21:46:36.858] > Waiting for server log...
[21:46:36.894] > Waiting for server log...
[21:46:36.916] > 
[21:46:36.934] > Waiting for server log...
[21:46:36.995] > Waiting for server log...
[21:46:37.042] > Waiting for server log...
> Waiting for server log...
[21:46:37.058] > 
[21:46:37.090] > Waiting for server log...
[21:46:37.106] > 
[21:46:37.135] > Waiting for server log...
[21:46:37.154] > 
[21:46:37.177] > Waiting for server log...
[21:46:37.200] > 
[21:46:37.224] > Waiting for server log...
[21:46:37.244] > 
[21:46:37.267] > Waiting for server log...
[21:46:37.276] > 
[21:46:37.317] > Waiting for server log...
[21:46:37.323] > 
[21:46:37.351] > Waiting for server log...
[21:46:37.371] > 
[21:46:37.393] > Waiting for server log...
[21:46:37.401] > 
[21:46:37.436] > Waiting for server log...
[21:46:37.454] > 
[21:46:37.479] > Waiting for server log...
[21:46:37.495] > 
[21:46:37.574] > Waiting for server log...
[21:46:37.605] > Waiting for server log...
[21:46:37.621] > 
[21:46:37.746] > Waiting for server log...
> Waiting for server log...
> Waiting for server log...
> Waiting for server log...
[21:46:37.755] > 
[21:46:37.800] > Waiting for server log...
[21:46:37.824] > Waiting for server log...
[21:46:37.839] > 
[21:46:37.863] > Waiting for server log...
[21:46:37.885] > 
[21:46:37.908] > Waiting for server log...
[21:46:37.917] > 
[21:46:37.951] > Waiting for server log...
[21:46:37.962] > 
[21:46:37.997] > Waiting for server log...
[21:46:38.009] > 
[21:46:38.040] > Waiting for server log...
[21:46:38.056] > 
[21:46:38.088] > Waiting for server log...
[21:46:38.102] > 
[21:46:38.134] > Waiting for server log...
[21:46:38.151] > 
[21:46:38.184] > Waiting for server log...
[21:46:38.196] > 
[21:46:38.239] > Waiting for server log...
[21:46:38.260] > 
[21:46:38.290] > Waiting for server log...
[21:46:38.306] > 
[21:46:38.334] > Waiting for server log...
[21:46:38.353] > 
[21:46:38.381] > Waiting for server log...
[21:46:38.400] > 
[21:46:38.428] > Waiting for server log...
[21:46:38.445] > 
[21:46:38.471] > Waiting for server log...
[21:46:38.492] > 
[21:46:38.512] > Waiting for server log...
[21:46:38.524] > 
[21:46:38.559] > Waiting for server log...
[21:46:38.572] > 
[21:46:38.603] > Waiting for server log...
[21:46:38.617] > 
[21:46:38.643] > Waiting for server log...
[21:46:38.661] > 
[21:46:38.691] > Waiting for server log...
[21:46:38.709] > 
[21:46:38.735] > Waiting for server log...
[21:46:38.758] > 
[21:46:38.776] > Waiting for server log...
[21:46:38.790] > 
[21:46:38.822] > Waiting for server log...
[21:46:38.834] > 
[21:46:38.863] > Waiting for server log...
[21:46:38.879] > 
[21:46:38.906] > Waiting for server log...
[21:46:38.926] > 
[21:46:38.945] > Waiting for server log...
[21:46:38.957] > 
[21:46:38.990] > Waiting for server log...
[21:46:39.008] > 
[21:46:39.034] > Waiting for server log...
[21:46:39.051] > 
[21:46:39.078] > Waiting for server log...
[21:46:39.096] > 
[21:46:39.124] > Waiting for server log...
[21:46:39.143] > 
[21:46:39.167] > Waiting for server log...
[21:46:39.187] > 
[21:46:39.209] > Waiting for server log...
[21:46:39.220] > 
[21:46:39.297] > Waiting for server log...
> Waiting for server log...
[21:46:39.338] > Waiting for server log...
[21:46:39.357] > 
[21:46:39.380] > Waiting for server log...
[21:46:39.391] > 
[21:46:39.426] > Waiting for server log...
[21:46:39.440] > 
[21:46:39.469] > Waiting for server log...
[21:46:39.483] > 
[21:46:39.508] > Waiting for server log...
[21:46:39.529] > 
[21:46:39.550] > Waiting for server log...
[21:46:39.560] > 
[21:46:39.592] > Waiting for server log...
[21:46:39.608] > 
[21:46:39.636] > Waiting for server log...
[21:46:39.656] > 
[21:46:39.678] > Waiting for server log...
[21:46:39.691] > 
[21:46:39.725] > Waiting for server log...
[21:46:39.734] > 
[21:46:39.767] > Waiting for server log...
[21:46:39.780] > 
[21:46:39.812] > Waiting for server log...
[21:46:39.826] > 
[21:46:39.859] > Waiting for server log...
[21:46:39.873] > 
[21:46:39.900] > Waiting for server log...
[21:46:39.922] > 
[21:46:39.939] > Waiting for server log...
[21:46:39.951] > 
[21:46:39.984] > Waiting for server log...
[21:46:39.995] > 
[21:46:40.027] > Waiting for server log...
[21:46:40.043] > 
[21:46:40.067] > Waiting for server log...
[21:46:40.090] > 
[21:46:40.107] > Waiting for server log...
[21:46:40.123] > 
[21:46:40.151] > Waiting for server log...
[21:46:40.168] > 
[21:46:40.193] > Waiting for server log...
[21:46:40.213] > 
[21:46:40.234] > Waiting for server log...
[21:46:40.244] > 
[21:46:40.280] > Waiting for server log...
[21:46:40.291] > 
[21:46:40.325] > Waiting for server log...
[21:46:40.341] > 
[21:46:40.373] > Waiting for server log...
[21:46:40.386] > 
[21:46:40.413] > Waiting for server log...
[21:46:40.435] > 
[21:46:40.462] > Waiting for server log...
[21:46:40.477] > 
[21:46:40.508] > Waiting for server log...
[21:46:40.525] > 
[21:46:40.543] > Waiting for server log...
[21:46:40.557] > 
[21:46:40.591] > Waiting for server log...
[21:46:40.606] > 
[21:46:40.629] > Waiting for server log...
[21:46:40.650] > 
[21:46:40.674] > Waiting for server log...
[21:46:40.683] > 
[21:46:40.713] > Waiting for server log...
[21:46:40.728] > 
[21:46:40.756] > Waiting for server log...
[21:46:40.774] > 
[21:46:40.797] > Waiting for server log...
[21:46:40.806] > 
[21:46:40.840] > Waiting for server log...
[21:46:40.856] > 
[21:46:40.886] > Waiting for server log...
[21:46:40.901] > 
[21:46:40.930] > Waiting for server log...
[21:46:40.945] > 
[21:46:40.972] > Waiting for server log...
[21:46:40.993] > 
[21:46:41.017] > Waiting for server log...
[21:46:41.039] > 
[21:46:41.060] > Waiting for server log...
[21:46:41.073] > 
[21:46:41.103] > Waiting for server log...
[21:46:41.116] > 
[21:46:41.145] > Waiting for server log...
[21:46:41.162] > 
[21:46:41.190] > Waiting for server log...
[21:46:41.209] > 
[21:46:41.230] > Waiting for server log...
[21:46:41.240] > 
[21:46:41.274] > Waiting for server log...
[21:46:41.289] > 
[21:46:41.317] > Waiting for server log...
[21:46:41.336] > 
[21:46:41.358] > Waiting for server log...
[21:46:41.367] > 
[21:46:41.400] > Waiting for server log...
[21:46:41.413] > 
[21:46:41.441] > Waiting for server log...
[21:46:41.459] > 
[21:46:41.487] > Waiting for server log...
[21:46:41.505] > 
[21:46:41.530] > Waiting for server log...
[21:46:41.554] > 
[21:46:41.573] > Waiting for server log...
[21:46:41.583] > 
[21:46:41.622] > Waiting for server log...
[21:46:41.633] > 
[21:46:41.665] > Waiting for server log...
[21:46:41.690] > 
[21:46:41.711] > Waiting for server log...
[21:46:41.726] > 
[21:46:41.759] > Waiting for server log...
[21:46:41.777] > 
[21:46:41.809] > Waiting for server log...
[21:46:41.828] > 
[21:46:41.839] > Waiting for server log...
[21:46:41.876] > Waiting for server log...
[21:46:41.896] > 
[21:46:41.924] > Waiting for server log...
[21:46:41.941] > 
[21:46:41.964] > Waiting for server log...
[21:46:41.975] > 
[21:46:42.007] > Waiting for server log...
[21:46:42.018] > 
[21:46:42.051] > Waiting for server log...
[21:46:42.068] > 
[21:46:42.091] > Waiting for server log...
[21:46:42.113] > 
[21:46:42.135] > Waiting for server log...
[21:46:42.144] > 
[21:46:42.176] > Waiting for server log...
[21:46:42.192] > 
[21:46:42.224] > Waiting for server log...
[21:46:42.241] > 
[21:46:42.263] > Waiting for server log...
[21:46:42.286] > 
[21:46:42.308] > Waiting for server log...
[21:46:42.317] > 
[21:46:42.351] > Waiting for server log...
[21:46:42.368] > 
[21:46:42.393] > Waiting for server log...
[21:46:42.412] > 
[21:46:42.440] > Waiting for server log...
[21:46:42.460] > 
[21:46:42.485] > Waiting for server log...
[21:46:42.528] > Waiting for server log...
[21:46:42.541] > 
[21:46:42.567] > Waiting for server log...
[21:46:42.585] > 
[21:46:42.608] > Waiting for server log...
[21:46:42.617] > 
[21:46:42.652] > Waiting for server log...
[21:46:42.665] > 
[21:46:42.692] > Waiting for server log...
[21:46:42.709] > 
[21:46:42.737] > Waiting for server log...
[21:46:42.786] > Waiting for server log...
[21:46:42.805] > 
[21:46:42.827] > Waiting for server log...
[21:46:42.854] > 
[21:46:42.875] > Waiting for server log...
[21:46:42.894] > 
[21:46:42.922] > Waiting for server log...
[21:46:42.940] > 
[21:46:42.957] > Waiting for server log...
[21:46:42.973] > 
[21:46:43.001] > Waiting for server log...
[21:46:43.018] > 
[21:46:43.041] > Waiting for server log...
[21:46:43.051] > 
[21:46:43.084] > Waiting for server log...
[21:46:43.095] > 
[21:46:43.125] > Waiting for server log...
[21:46:43.143] > 
[21:46:43.178] > Waiting for server log...
[21:46:43.192] > 
[21:46:43.207] > Waiting for server log...
[21:46:43.223] > 
[21:46:43.256] > Waiting for server log...
[21:46:43.268] > 
[21:46:43.292] > Waiting for server log...
[21:46:43.314] > 
[21:46:43.336] > Waiting for server log...
[21:46:43.344] > 
[21:46:43.377] > Waiting for server log...
[21:46:43.396] > 
[21:46:43.424] > Waiting for server log...
[21:46:43.436] > 
[21:46:43.474] > Waiting for server log...
[21:46:43.497] > 
[21:46:43.527] > Waiting for server log...
[21:46:43.545] > 
[21:46:43.570] > Waiting for server log...
[21:46:43.610] > Waiting for server log...
[21:46:43.625] > 
[21:46:43.660] > Waiting for server log...
[21:46:43.684] > 
[21:46:43.701] > Waiting for server log...
[21:46:43.719] > 
[21:46:43.742] > Waiting for server log...
[21:46:43.760] > 
[21:46:43.805] > Waiting for server log...
[21:46:43.834] > Waiting for server log...
[21:46:43.856] > 
[21:46:43.875] > Waiting for server log...
[21:46:43.886] > 
[21:46:43.918] > Waiting for server log...
[21:46:43.935] > 
[21:46:43.960] > Waiting for server log...
[21:46:43.979] > 
[21:46:44.006] > Waiting for server log...
[21:46:44.023] > 
[21:46:44.043] > Waiting for server log...
[21:46:44.057] > 
[21:46:44.095] > Waiting for server log...
[21:46:44.117] > 
[21:46:44.130] > Waiting for server log...
[21:46:44.174] > Waiting for server log...
[21:46:44.194] > 
[21:46:44.221] > Waiting for server log...
[21:46:44.242] > 
[21:46:44.263] > Waiting for server log...
[21:46:44.288] > 
[21:46:44.308] > Waiting for server log...
[21:46:44.318] > 
[21:46:44.345] > Waiting for server log...
[21:46:44.362] > 
[21:46:44.391] > Waiting for server log...
[21:46:44.407] > 
[21:46:44.436] > Waiting for server log...
[21:46:44.456] > 
[21:46:44.486] > Waiting for server log...
[21:46:44.505] > 
[21:46:44.521] > Waiting for server log...
[21:46:44.539] > 
[21:46:44.560] > Waiting for server log...
[21:46:44.578] > 
[21:46:44.607] > Waiting for server log...
[21:46:44.628] > 
[21:46:44.654] > Waiting for server log...
[21:46:44.673] > 
[21:46:44.696] > Waiting for server log...
[21:46:44.722] > 
[21:46:44.742] > Waiting for server log...
[21:46:44.789] > Waiting for server log...
[21:46:44.796] > 
[21:46:44.828] > Waiting for server log...
[21:46:44.845] > 
[21:46:44.874] > Waiting for server log...
[21:46:44.897] > 
[21:46:44.913] > Waiting for server log...
[21:46:44.937] > 
[21:46:44.958] > Waiting for server log...
[21:46:44.972] > 
[21:46:44.995] > Waiting for server log...
[21:46:45.011] > 
[21:46:45.041] > Waiting for server log...
[21:46:45.061] > 
[21:46:45.088] > Waiting for server log...
[21:46:45.107] > 
[21:46:45.128] > Waiting for server log...
[21:46:45.138] > 
[21:46:45.171] > Waiting for server log...
[21:46:45.188] > 
[21:46:45.208] > Waiting for server log...
[21:46:45.230] > 
[21:46:45.255] > Waiting for server log...
[21:46:45.276] > 
[21:46:45.298] > Waiting for server log...
[21:46:45.308] > 
[21:46:45.340] > Waiting for server log...
[21:46:45.353] > 
[21:46:45.385] > Waiting for server log...
[21:46:45.404] > 
[21:46:45.426] > Waiting for server log...
[21:46:45.445] > 
[21:46:45.468] > Waiting for server log...
[21:46:45.490] > 
[21:46:45.514] > Waiting for server log...
[21:46:45.539] > 
[21:46:45.561] > Waiting for server log...
[21:46:45.568] > 
[21:46:45.608] > Waiting for server log...
[21:46:45.614] > 
[21:46:45.645] > Waiting for server log...
[21:46:45.661] > 
[21:46:45.692] > Waiting for server log...
[21:46:45.711] > 
[21:46:45.729] > Waiting for server log...
[21:46:45.755] > 
[21:46:45.775] > Waiting for server log...
[21:46:45.787] > 
[21:46:45.815] > Waiting for server log...
[21:46:45.832] > 
[21:46:45.857] > Waiting for server log...
[21:46:45.878] > 
[21:46:45.897] > Waiting for server log...
[21:46:45.910] > 
[21:46:45.944] > Waiting for server log...
[21:46:45.961] > 
[21:46:45.991] > Waiting for server log...
[21:46:46.004] > 
[21:46:46.031] > Waiting for server log...
[21:46:46.054] > 
[21:46:46.076] > Waiting for server log...
[21:46:46.095] > 
[21:46:46.122] > Waiting for server log...
[21:46:46.142] > 
[21:46:46.160] > Waiting for server log...
[21:46:46.174] > 
[21:46:46.206] > Waiting for server log...
[21:46:46.226] > 
[21:46:46.244] > Waiting for server log...
[21:46:46.270] > 
[21:46:46.289] > Waiting for server log...
[21:46:46.297] > 
[21:46:46.331] > Waiting for server log...
[21:46:46.345] > 
[21:46:46.375] > Waiting for server log...
[21:46:46.397] > 
[21:46:46.420] > Waiting for server log...
[21:46:46.439] > 
[21:46:46.461] > Waiting for server log...
[21:46:46.468] > 
[21:46:46.495] > Waiting for server log...
[21:46:46.522] > 
[21:46:46.542] > Waiting for server log...
[21:46:46.581] > Waiting for server log...
[21:46:46.595] > 
[21:46:46.625] > Waiting for server log...
[21:46:46.645] > 
[21:46:46.665] > Waiting for server log...
[21:46:46.678] > 
[21:46:46.722] > Waiting for server log...
[21:46:46.735] > 
[21:46:46.753] > Waiting for server log...
[21:46:46.770] > 
[21:46:46.790] > Waiting for server log...
[21:46:46.798] > 
[21:46:46.830] > Waiting for server log...
[21:46:46.844] > 
[21:46:46.870] > Waiting for server log...
[21:46:46.894] > 
[21:46:46.921] > Waiting for server log...
[21:46:46.938] > 
[21:46:46.954] > Waiting for server log...
[21:46:46.971] > 
[21:46:46.994] > Waiting for server log...
[21:46:47.013] > 
[21:46:47.036] > Waiting for server log...
[21:46:47.044] > 
[21:46:47.075] > Waiting for server log...
[21:46:47.093] > 
[21:46:47.119] > Waiting for server log...
[21:46:47.141] > 
[21:46:47.160] > Waiting for server log...
[21:46:47.169] > 
[21:46:47.203] > Waiting for server log...
[21:46:47.219] > 
[21:46:47.245] > Waiting for server log...
[21:46:47.264] > 
[21:46:47.290] > Waiting for server log...
[21:46:47.308] > 
[21:46:47.335] > Waiting for server log...
[21:46:47.357] > 
[21:46:47.377] > Waiting for server log...
[21:46:47.392] > 
[21:46:47.423] > Waiting for server log...
[21:46:47.447] > 
[21:46:47.467] > Waiting for server log...
[21:46:47.477] > 
[21:46:47.505] > Waiting for server log...
[21:46:47.526] > 
[21:46:47.548] > Waiting for server log...
[21:46:47.574] > 
[21:46:47.590] > Waiting for server log...
[21:46:47.601] > 
[21:46:47.636] > Waiting for server log...
[21:46:47.655] > 
[21:46:47.678] > Waiting for server log...
[21:46:47.693] > 
[21:46:47.722] > Waiting for server log...
[21:46:47.741] > 
[21:46:47.762] > Waiting for server log...
[21:46:47.775] > 
[21:46:47.806] > Waiting for server log...
[21:46:47.821] > 
[21:46:47.853] > Waiting for server log...
[21:46:47.871] > 
[21:46:47.895] > Waiting for server log...
[21:46:47.914] > 
[21:46:47.943] > Waiting for server log...
[21:46:47.961] > 
[21:46:47.991] > Waiting for server log...
[21:46:48.010] > 
[21:46:48.029] > Waiting for server log...
[21:46:48.055] > 
[21:46:48.074] > Waiting for server log...
[21:46:48.098] > 
[21:46:48.115] > Waiting for server log...
[21:46:48.127] > 
[21:46:48.160] > Waiting for server log...
[21:46:48.176] > 
[21:46:48.202] > Waiting for server log...
[21:46:48.224] > 
[21:46:48.244] > Waiting for server log...
[21:46:48.254] > 
[21:46:48.288] > Waiting for server log...
[21:46:48.305] > 
[21:46:48.327] > Waiting for server log...
[21:46:48.346] > 
[21:46:48.374] > Waiting for server log...
[21:46:48.394] > 
[21:46:48.409] > Waiting for server log...
[21:46:48.425] > 
[21:46:48.452] > Waiting for server log...
[21:46:48.470] > 
[21:46:48.496] > Waiting for server log...
[21:46:48.519] > 
[21:46:48.543] > Waiting for server log...
[21:46:48.563] > 
[21:46:48.594] > Waiting for server log...
[21:46:48.608] > 
[21:46:48.639] > Waiting for server log...
[21:46:48.660] > 
[21:46:48.681] > Waiting for server log...
[21:46:48.704] > 
[21:46:48.727] > Waiting for server log...
[21:46:48.751] > 
[21:46:48.767] > Waiting for server log...
[21:46:48.779] > 
[21:46:48.810] > Waiting for server log...
[21:46:48.828] > 
[21:46:48.851] > Waiting for server log...
[21:46:48.873] > 
[21:46:48.892] > Waiting for server log...
[21:46:48.906] > 
[21:46:48.934] > Waiting for server log...
[21:46:48.953] > 
[21:46:48.976] > Waiting for server log...
[21:46:48.995] > 
[21:46:49.019] > Waiting for server log...
[21:46:49.042] > 
[21:46:49.064] > Waiting for server log...
[21:46:49.076] > 
[21:46:49.107] > Waiting for server log...
[21:46:49.125] > 
[21:46:49.151] > Waiting for server log...
[21:46:49.168] > 
[21:46:49.192] > Waiting for server log...
[21:46:49.213] > 
[21:46:49.234] > Waiting for server log...
[21:46:49.245] > 
[21:46:49.281] > Waiting for server log...
[21:46:49.293] > 
[21:46:49.324] > Waiting for server log...
[21:46:49.342] > 
[21:46:49.368] > Waiting for server log...
[21:46:49.390] > 
[21:46:49.408] > Waiting for server log...
[21:46:49.417] > 
[21:46:49.457] > Waiting for server log...
[21:46:49.463] > 
[21:46:49.495] > Waiting for server log...
[21:46:49.510] > 
[21:46:49.534] > Waiting for server log...
[21:46:49.557] > 
[21:46:49.581] > Waiting for server log...
[21:46:49.606] > 
[21:46:49.624] > Waiting for server log...
[21:46:49.635] > 
[21:46:49.668] > Waiting for server log...
[21:46:49.684] > 
[21:46:49.707] > Waiting for server log...
[21:46:49.729] > 
[21:46:49.753] > Waiting for server log...
[21:46:49.760] > 
[21:46:49.794] > Waiting for server log...
[21:46:49.809] > 
[21:46:49.840] > Waiting for server log...
[21:46:49.859] > 
[21:46:49.885] > Waiting for server log...
[21:46:49.902] > 
[21:46:49.926] > Waiting for server log...
[21:46:49.954] > 
[21:46:49.972] > Waiting for server log...
[21:46:49.981] > 
[21:46:50.013] > Waiting for server log...
[21:46:50.027] > 
[21:46:50.057] > Waiting for server log...
[21:46:50.076] > 
[21:46:50.097] > Waiting for server log...
[21:46:50.122] > 
[21:46:50.140] > Waiting for server log...
[21:46:50.152] > 
[21:46:50.185] > Waiting for server log...
[21:46:50.201] > 
[21:46:50.225] > Waiting for server log...
[21:46:50.248] > 
[21:46:50.269] > Waiting for server log...
[21:46:50.278] > 
[21:46:50.335] > Waiting for server log...
[21:46:50.355] > 
> Waiting for server log...
[21:46:50.368] > 
[21:46:50.407] > Waiting for server log...
[21:46:50.421] > 
[21:46:50.447] > Waiting for server log...
[21:46:50.463] > 
[21:46:50.491] > Waiting for server log...
[21:46:50.511] > 
[21:46:50.537] > Waiting for server log...
[21:46:50.558] > 
[21:46:50.580] > Waiting for server log...
[21:46:50.594] > 
[21:46:50.623] > Waiting for server log...
[21:46:50.638] > 
[21:46:50.661] > Waiting for server log...
[21:46:50.681] > 
[21:46:50.707] > Waiting for server log...
[21:46:50.727] > 
[21:46:50.752] > Waiting for server log...
[21:46:50.790] > Waiting for server log...
[21:46:50.809] > 
[21:46:50.837] > Waiting for server log...
[21:46:50.853] > 
[21:46:50.877] > Waiting for server log...
[21:46:50.884] > 
[21:46:50.912] >  
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
[21:46:50.929] > 
> *
> 
> Server did not start successfully. Full server log at /home/blackjack/.vscode-server/.252e5463d60e63238250799aef7375787f68b4ee.log >>>
> /home/blackjack/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/bin/code-server: 12: /home/blackjack/.vscode-server/bin/252e5463d60e6323
> 38250799aef7375787f68b4ee/node: not found
[21:46:50.936] > 
> <<< End of server log
> 5ae284d1d133: start
[21:46:50.941] > 
> exitCode==32==
> listeningOn====
> osReleaseId==raspbian==
> arch==aarch64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==14638==
> 5ae284d1d133: end
[21:46:50.941] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==raspbian==
arch==aarch64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==14638==

[21:46:50.943] Resolver error: Error: The VS Code Server failed to start
	at m.ServerInstallError (c:\Users\jerem\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:584079)
	at f (c:\Users\jerem\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:578136)
	at t.handleInstallOutput (c:\Users\jerem\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:581161)
	at t.tryInstall (c:\Users\jerem\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:681555)
	at async c:\Users\jerem\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:643798
	at async t.withShowDetailsEvent (c:\Users\jerem\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:647116)
	at async t.resolve (c:\Users\jerem\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:644848)
	at async c:\Users\jerem\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:720590
[21:46:50.953] ------




[21:46:52.267] "install" terminal command done
[21:46:52.268] Install terminal quit with output: 
```

</p>
</details>

### Anything else?

I tried the solutions proposed in other post or solutions found online:
- deleting the .vscode-server file on my rpi
- augmenting the time of connection to the server
- trying to install the server manually or on another user
- restarting everything or using other older or prerealease versions of Remote SSH

I always get the same result

**Comment by jerempr** [comment]
Actually the problem was that vscode was probably trying to set things up for a arm64 architecture because `uname -m` was returning arm46. the solution was to add `arm_64bit=0` to the `/boot/config.txt` file and rebooting. Now `uname -m` return `armv7l` and vscode remote server is able to run
