### ISSUE TITLE
Dev containers fail to build

### ISSUE THREAD

**Issue by ekluxae** [microsoft/vscode-remote-release#8458]
- VSCode Version: 1.78.0
- Local OS Version: Windows 10
- Remote OS Version: Ubuntu 20.04
- Remote Extension/Connection Type: Dev Container

- Logs:
>[7929 ms] Dev Containers 0.292.0 in VS Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee).
[7929 ms] Start: Run: ssh t480-ubuntu /bin/sh
[7951 ms] Start: Run in host: id -un
[8531 ms] ekl
[8532 ms] 
[8532 ms] Start: Run in host: cat /etc/passwd
[8537 ms] Start: Run in host: echo ~
[8539 ms] /home/ekl
[8539 ms] 
[8541 ms] Start: Run in host: test -x '/home/ekl/.vscode-remote-containers/bin/252e5463d60e63238250799aef7375787f68b4ee/node'
[8544 ms] 
[8544 ms] 
[8544 ms] Exit code 1
[8545 ms] Start: Run in host: test -x '/home/ekl/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/node'
[8549 ms] 
[8550 ms] 
[8550 ms] Start: Run in host: test -f '/home/ekl/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/node_modules/node-pty/package.json'
[8554 ms] 
[8554 ms] 
[8555 ms] Start: Run in host: test -f '/home/ekl/.vscode-remote-containers/dist/vscode-remote-containers-server-0.292.0.js'
[8558 ms] 
[8559 ms] 
[8559 ms] Exit code 1
[8559 ms] Start: Run in host: mkdir -p '/home/ekl/.vscode-remote-containers/dist'
[8562 ms] 
[8562 ms] 
[8563 ms] Start: Run in host: cat <<'EOF-/home/ekl/.vscode-remote-containers/dist/vscode-remote-containers-server-0.292.0.js' >/home/ekl/.vscode-remote-containers/dist/vscode-remote-containers-server-0.292.0.js_1683553559205
[8575 ms] 
[8575 ms] 
[8578 ms] userEnvProbe: loginInteractiveShell (default)
[8579 ms] userEnvProbe: not found in cache
[8579 ms] userEnvProbe shell: /bin/bash
[8664 ms] userEnvProbe PATHs:
Probe:     '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
Container: None
[8680 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[8747 ms] 1.42
[9159 ms] Start: Run in Host: tar --no-same-owner -x -f -
[9183 ms] Start: Run in Host: tar --no-same-owner -x -f -
[9207 ms] Start: Run in Host: /home/ekl/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/node /home/ekl/.vscode-remote-containers/dist/dev-containers-cli-0.292.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/ekl/live/vscode-dev --log-level debug --log-format json --config /home/ekl/live/vscode-dev/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true
[7494 ms] @devcontainers/cli 0.40.0. Node.js v16.17.1. linux 5.4.0-147-generic x64.
[7494 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/ekl/live/vscode-dev --filter label=devcontainer.config_file=/home/ekl/live/vscode-dev/.devcontainer/devcontainer.json
[7588 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/ekl/live/vscode-dev
[7665 ms] Start: Run: docker-compose version --short
[7686 ms] Docker Compose version: v2.0.1
[7686 ms] Start: Run: docker-compose -f /home/ekl/live/vscode-dev/.devcontainer/docker-compose.yml --profile * config
[7706 ms] services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    command:
    - sleep
    - infinity
    networks:
      default: null
    volumes:
    - type: bind
      source: ../..
      target: /workspaces
      bind:
        create_host_path: true
networks:
  default:
    name: devcontainer_default
[7710 ms] Error: ENOENT: no such file or directory, open '/home/ekl/.vscode-remote-containers/dist/dev-containers-cli-0.292.0/Dockerfile'
[9659 ms] Exit code 1
[19319 ms] Start: Run in Host: docker version --format {{.Server.APIVersion}}
[19398 ms] 1.42
[19434 ms] Start: Run in Host: /home/ekl/.vscode-server/bin/252e5463d60e63238250799aef7375787f68b4ee/node /home/ekl/.vscode-remote-containers/dist/dev-containers-cli-0.292.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/ekl/live/vscode-dev --log-level debug --log-format json --config /home/ekl/live/vscode-dev/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true
[17677 ms] @devcontainers/cli 0.40.0. Node.js v16.17.1. linux 5.4.0-147-generic x64.
[17677 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/ekl/live/vscode-dev --filter label=devcontainer.config_file=/home/ekl/live/vscode-dev/.devcontainer/devcontainer.json
[17742 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/ekl/live/vscode-dev
[17796 ms] Start: Run: docker-compose version --short
[17812 ms] Docker Compose version: v2.0.1
[17813 ms] Start: Run: docker-compose -f /home/ekl/live/vscode-dev/.devcontainer/docker-compose.yml --profile * config
[17833 ms] services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    command:
    - sleep
    - infinity
    networks:
      default: null
    volumes:
    - type: bind
      source: ../..
      target: /workspaces
      bind:
        create_host_path: true
networks:
  default:
    name: devcontainer_default
[17837 ms] Error: ENOENT: no such file or directory, open '/home/ekl/.vscode-remote-containers/dist/dev-containers-cli-0.292.0/Dockerfile'
[19786 ms] Exit code 1

Steps to Reproduce:

1. Create .devcontainer folder with the 3 files attached and execute "Rebuild and Reopen in Container"
2. Works for Dev Container extension V0.234.0, but later versions of Dev Container including latest V0.292.0 will result in error as shown in log
3.  Looks similar to closed issue #6815

[devcontainer.zip](https://github.com/microsoft/vscode-remote-release/files/11421616/devcontainer.zip)

**Comment by chrmarti** [comment]
You have an early v2 version of Docker Compose. Could you try with a more recent one?

**Comment by davzucky** [comment]
I have have the same problem, but with a configuration little different.


- VSCode Version: 1.77.0
- Local OS Version: Windows 10
- Remote OS Version: RedHat 8
- Remote Extension/Connection Type: Dev Container
- use podman and podman-compose on remote host
- 
```
[5530 ms] Dev Containers 0.292.0 in VS Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63).
[5530 ms] Start: Run: ssh -F C:\Users\dzucker\.ssh\config zucker-large /bin/sh
[5557 ms] Start: Run in host: id -un
[9519 ms] coder
[9520 ms]
[9522 ms] Start: Run in host: cat /etc/passwd
[9756 ms] Start: Run in host: echo ~
[9989 ms] /cs/coder
[9990 ms]
[9993 ms] Start: Run in host: test -x '/cs/coder/.vscode-remote-containers/bin/7f329fe6c66b0f86ae1574c2911b681ad5a45d63/node'
[10228 ms]
[10230 ms]
[10231 ms] Start: Run in host: test -f '/cs/coder/.vscode-remote-containers/dist/vscode-remote-containers-server-0.292.0.js'
[10463 ms]
[10463 ms]
[10695 ms] userEnvProbe: loginInteractiveShell (default)
[10696 ms] userEnvProbe: not found in cache
[10696 ms] userEnvProbe shell: /bin/bash
[11172 ms] userEnvProbe PATHs:
Probe:     '/cs/coder/.local/bin:/cs/coder/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin'
Container: None
[11413 ms] Start: Run in Host: podman version --format {{.Server.APIVersion}}
[11944 ms] 4.2.0
[16502 ms] Start: Run in Host: tar --no-same-owner -x -f -
[17448 ms] Start: Run in Host: tar --no-same-owner -x -f -
[18408 ms] Start: Run in Host: /cs/coder/.vscode-remote-containers/bin/7f329fe6c66b0f86ae1574c2911b681ad5a45d63/node /cs/coder/.vscode-remote-containers/dist/dev-containers-cli-0.292.0/dist/spec-node/devContainersSpecCLI.js read-configuration --docker-path podman --docker-compose-path podman-compose --workspace-folder /cs/coder/nori --log-level debug --log-format json --config /cs/coder/nori/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true --terminal-columns 228 --terminal-rows 28
[18738 ms] @devcontainers/cli 0.40.0. Node.js v16.14.2. linux 4.18.0-372.32.1.el8_6.x86_64 x64.
[18738 ms] Start: Run: podman ps -q -a --filter label=devcontainer.local_folder=/cs/coder/nori --filter label=devcontainer.config_file=/cs/coder/nori/.devcontainer/devcontainer.json
[18887 ms] Start: Run: podman ps -q -a --filter label=devcontainer.local_folder=/cs/coder/nori
[19036 ms] Start: Run: podman-compose version --short
[19182 ms] Docker Compose version: 1.0.6
[19183 ms] Start: Run: podman-compose -f /cs/coder/nori/.devcontainer/docker-compose.yml config
[19326 ms] services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      mongo:
        condition: service_started
    links:
    - mongo
    volumes:
    - relabel: shared
      source: ..
      target: /nori
      type: bind
  mongo:
    environment:
      MONGO_INITDB_DATABASE: hotpot_test
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_USERNAME: root
    image: docker-dev.odyssey.rowini.net/mongo:4.4
    ports:
    - 27017:27017
    restart: unless-stopped
version: '3.9'
[19332 ms] Error: ENOENT: no such file or directory, open '/cs/coder/.vscode-remote-containers/dist/dev-containers-cli-0.292.0/Dockerfile'
[19497 ms] Exit code 1
```
I tried to run the last command, which error on the shell, and I got this log.

```
[coder@ip nori]$ /cs/coder/.vscode-remote-containers/bin/7f329fe6c66b0f86ae1574c2911b681ad5a45d63/node /cs/coder/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/dist/spec-node/devContainersSpecCLI.js read-configuration --docker-path podman --docker-compose-path podman-compose --workspace-folder /cs/coder/nori --log-level debug --log-format json --config /cs/coder/nori/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true --terminal-columns 155 --terminal-rows 28
Error: Missing node-pty
    at Jx (/cs/coder/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/dist/spec-node/devContainersSpecCLI.js:1670:1908)
    at async gn (/cs/coder/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/dist/spec-node/devContainersSpecCLI.js:1669:13220)
    at async Pae (/cs/coder/.vscode-remote-containers/dist/dev-containers-cli-0.293.0/dist/spec-node/devContainersSpecCLI.js:2092:33226)
```
This problem only happens when I want to use a docker compose to start. I downgrade the ```dev container``` extension to 0.234 and confirm that it works for me.

**Comment by ekluxae** [comment]
upgraded docker-compose to latest version and problem fixed

**Comment by davzucky** [comment]
In my case, I'm using podman-compose. Let me check if they are a more resent version.

**Comment by davzucky** [comment]
I think the problem is still valid. I confirmed that I'm using the latest version of podman-compose.
I change the container engine to docker/docker-compose and this is working now.

Is the setup tested with podman-compose ? looking at the output of docker-compose and podman-compose I can see some small different. Could this be the root cause ?
