### ISSUE TITLE
Dev container extension is not working

### ISSUE THREAD

**Issue by deepaerial** [microsoft/vscode-remote-release#8506]
I cannot open existing projects with `.devcontainer` configuration and cannot add new configuration.  

Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:44:45.204Z (1 wk ago)
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.3.0
Sandboxed: No

- Logs:
```
2023-05-18 23:52:53.216 [error] {"message":"Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/deepaerial/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /Users/deepaerial/Projects/weathertower --log-level debug --log-format json --config /Users/deepaerial/Projects/weathertower/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true","code":1} remote-containers.reopenInContainer {"value":"ms-vscode-remote.remote-containers","c":"ms-vscode-remote.remote-containers"}
2023-05-18 23:55:20.253 [error] {"message":"Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/deepaerial/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js templates apply --workspace-folder /var/folders/5k/yrwqz7p14b74jkz9f3yz_1000000gn/T/tmp-output-dir-1684446919385 --template-id ghcr.io/devcontainers/templates/python:latest --template-args {\"imageVariant\":\"3.10\"} --features [{\"id\":\"ghcr.io/devcontainers-contrib/features/poetry:2\",\"options\":{}}] --tmp-dir /var/folders/5k/yrwqz7p14b74jkz9f3yz_1000000gn/T/tmp-dir-1684446919385","code":1} remote-containers.createDevContainerFile {"value":"ms-vscode-remote.remote-containers","c":"ms-vscode-remote.remote-containers"}
```
Steps to Reproduce:

1. Open project with `.devcontainer` config folder and choose "Reopen in container" option.
OR
1. Choose "Add Dev Container Configuration Files..." select Python 3 template with version `3.10` and choose Poetry as additional feature.

**Comment by chrmarti** [comment]
Please append the Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)

**Comment by deepaerial** [comment]
@chrmarti Logs:
```
[2023-05-18T21:51:52.438Z] Dev Containers 0.292.0 in VS Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435).
[2023-05-18T21:51:52.438Z] Start: Run: git rev-parse --abbrev-ref --symbolic-full-name @{u}
[2023-05-18T21:51:52.447Z] Stop (9 ms): Run: git rev-parse --abbrev-ref --symbolic-full-name @{u}
[2023-05-18T21:51:54.577Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2023-05-18T21:51:54.688Z] Stop (111 ms): Run: docker version --format {{.Server.APIVersion}}
[2023-05-18T21:51:54.688Z] 1.41
[2023-05-18T21:51:54.707Z] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/deepaerial/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /Users/deepaerial/Projects/weathertower --log-level debug --log-format json --config /Users/deepaerial/Projects/weathertower/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true
[2023-05-18T21:51:54.977Z] @devcontainers/cli 0.40.0. Node.js v16.17.1. darwin 22.3.0 x64.
[2023-05-18T21:51:54.976Z] Start: Run: git rev-parse --show-cdup
[2023-05-18T21:51:54.985Z] Stop (9 ms): Run: git rev-parse --show-cdup
[2023-05-18T21:51:54.986Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/deepaerial/Projects/weathertower --filter label=devcontainer.config_file=/Users/deepaerial/Projects/weathertower/.devcontainer/devcontainer.json
[2023-05-18T21:51:55.066Z] Stop (80 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/deepaerial/Projects/weathertower --filter label=devcontainer.config_file=/Users/deepaerial/Projects/weathertower/.devcontainer/devcontainer.json
[2023-05-18T21:51:55.067Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/deepaerial/Projects/weathertower
[2023-05-18T21:51:55.147Z] Stop (80 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/deepaerial/Projects/weathertower
[2023-05-18T21:51:55.152Z] * Processing feature: docker-from-docker
[2023-05-18T21:51:55.152Z] (!) WARNING: Using the deprecated 'docker-from-docker' Feature. See https://github.com/devcontainers/features/tree/main/src/docker-from-docker#example-usage for the updated Feature.
[2023-05-18T21:51:55.375Z] Start: Run: docker-credential-desktop get
[2023-05-18T21:51:55.479Z] Stop (104 ms): Run: docker-credential-desktop get
[2023-05-18T21:51:55.760Z] [httpOci] Could not fetch bearer token for 'ghcr.io': Error: HTTP 403: Forbidden
[2023-05-18T21:51:55.760Z] [httpOci] ERR: Failed to fetch Bearer token from registry.
[2023-05-18T21:51:55.760Z] Request 'https://ghcr.io/v2/devcontainers/features/docker-from-docker/manifests/1' failed
[2023-05-18T21:51:55.760Z] Could not resolve Feature manifest for 'ghcr.io/devcontainers/features/docker-from-docker:1'.  If necessary, provide registry credentials with 'docker login <registry>'.
[2023-05-18T21:51:55.760Z] Github feature.
[2023-05-18T21:51:55.760Z] Could not resolve Feature 'ghcr.io/devcontainers/features/docker-from-docker:1'.  Ensure the Feature is published and accessible from your current environment.
[2023-05-18T21:51:55.761Z] Error: Failed to process feature ghcr.io/devcontainers/features/docker-from-docker:1
    at Wie (/Users/deepaerial/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:1874:3166)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Xm (/Users/deepaerial/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:1874:2263)
    at async Iae (/Users/deepaerial/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:2092:33794)
[2023-05-18T21:51:55.767Z] Stop (1060 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/deepaerial/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /Users/deepaerial/Projects/weathertower --log-level debug --log-format json --config /Users/deepaerial/Projects/weathertower/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true
[2023-05-18T21:51:55.767Z] Exit code 1
[2023-05-18T21:52:52.007Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2023-05-18T21:52:52.100Z] Stop (93 ms): Run: docker version --format {{.Server.APIVersion}}
[2023-05-18T21:52:52.100Z] 1.41
[2023-05-18T21:52:52.131Z] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/deepaerial/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /Users/deepaerial/Projects/weathertower --log-level debug --log-format json --config /Users/deepaerial/Projects/weathertower/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true
[2023-05-18T21:52:52.396Z] @devcontainers/cli 0.40.0. Node.js v16.17.1. darwin 22.3.0 x64.
[2023-05-18T21:52:52.396Z] Start: Run: git rev-parse --show-cdup
[2023-05-18T21:52:52.415Z] Stop (19 ms): Run: git rev-parse --show-cdup
[2023-05-18T21:52:52.415Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/deepaerial/Projects/weathertower --filter label=devcontainer.config_file=/Users/deepaerial/Projects/weathertower/.devcontainer/devcontainer.json
[2023-05-18T21:52:52.515Z] Stop (100 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/deepaerial/Projects/weathertower --filter label=devcontainer.config_file=/Users/deepaerial/Projects/weathertower/.devcontainer/devcontainer.json
[2023-05-18T21:52:52.516Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/deepaerial/Projects/weathertower
[2023-05-18T21:52:52.595Z] Stop (79 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/deepaerial/Projects/weathertower
[2023-05-18T21:52:52.601Z] * Processing feature: docker-from-docker
[2023-05-18T21:52:52.601Z] (!) WARNING: Using the deprecated 'docker-from-docker' Feature. See https://github.com/devcontainers/features/tree/main/src/docker-from-docker#example-usage for the updated Feature.
[2023-05-18T21:52:52.879Z] Start: Run: docker-credential-desktop get
[2023-05-18T21:52:52.983Z] Stop (104 ms): Run: docker-credential-desktop get
[2023-05-18T21:52:53.207Z] [httpOci] Could not fetch bearer token for 'ghcr.io': Error: HTTP 403: Forbidden
[2023-05-18T21:52:53.207Z] [httpOci] ERR: Failed to fetch Bearer token from registry.
[2023-05-18T21:52:53.207Z] Request 'https://ghcr.io/v2/devcontainers/features/docker-from-docker/manifests/1' failed
[2023-05-18T21:52:53.207Z] Could not resolve Feature manifest for 'ghcr.io/devcontainers/features/docker-from-docker:1'.  If necessary, provide registry credentials with 'docker login <registry>'.
[2023-05-18T21:52:53.207Z] Github feature.
[2023-05-18T21:52:53.207Z] Could not resolve Feature 'ghcr.io/devcontainers/features/docker-from-docker:1'.  Ensure the Feature is published and accessible from your current environment.
[2023-05-18T21:52:53.207Z] Error: Failed to process feature ghcr.io/devcontainers/features/docker-from-docker:1
    at Wie (/Users/deepaerial/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:1874:3166)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Xm (/Users/deepaerial/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:1874:2263)
    at async Iae (/Users/deepaerial/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:2092:33794)
[2023-05-18T21:52:53.215Z] Stop (1084 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/deepaerial/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /Users/deepaerial/Projects/weathertower --log-level debug --log-format json --config /Users/deepaerial/Projects/weathertower/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true
[2023-05-18T21:52:53.215Z] Exit code 1
[2023-05-18T21:54:41.903Z]  -- CREATEDEVCONTAINER v2
[2023-05-18T21:55:19.388Z] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/deepaerial/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js templates apply --workspace-folder /var/folders/5k/yrwqz7p14b74jkz9f3yz_1000000gn/T/tmp-output-dir-1684446919385 --template-id ghcr.io/devcontainers/templates/python:latest --template-args {"imageVariant":"3.10"} --features [{"id":"ghcr.io/devcontainers-contrib/features/poetry:2","options":{}}] --tmp-dir /var/folders/5k/yrwqz7p14b74jkz9f3yz_1000000gn/T/tmp-dir-1684446919385
[2023-05-18T21:55:19.653Z] [2023-05-18T21:55:19.652Z] @devcontainers/cli 0.40.0. Node.js v16.17.1. darwin 22.3.0 x64.
[2023-05-18T21:55:20.244Z] [2023-05-18T21:55:20.243Z] [httpOci] Could not fetch bearer token for 'ghcr.io': Error: HTTP 403: Forbidden
[2023-05-18T21:55:20.245Z] [2023-05-18T21:55:20.244Z] [httpOci] ERR: Failed to fetch Bearer token from registry.
[2023-05-18T21:55:20.245Z] [2023-05-18T21:55:20.244Z] Request 'https://ghcr.io/v2/devcontainers/templates/python/manifests/latest' failed
[2023-05-18T21:55:20.245Z] [2023-05-18T21:55:20.244Z] Failed to fetch template manifest for ghcr.io/devcontainers/templates/python:latest
[2023-05-18T21:55:20.246Z] [2023-05-18T21:55:20.244Z] Failed to fetch template 'ghcr.io/devcontainers/templates/python:latest'.
[2023-05-18T21:55:20.252Z] Stop (864 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/deepaerial/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js templates apply --workspace-folder /var/folders/5k/yrwqz7p14b74jkz9f3yz_1000000gn/T/tmp-output-dir-1684446919385 --template-id ghcr.io/devcontainers/templates/python:latest --template-args {"imageVariant":"3.10"} --features [{"id":"ghcr.io/devcontainers-contrib/features/poetry:2","options":{}}] --tmp-dir /var/folders/5k/yrwqz7p14b74jkz9f3yz_1000000gn/T/tmp-dir-1684446919385
[2023-05-18T21:55:20.253Z] Exit code 1
[2023-05-18T22:00:54.540Z]  -- CREATEDEVCONTAINER v2
```

**Comment by chrmarti** [comment]
Might your token for ghcr.io have expired? Could you try running `docker logout ghcr.io` and then retry? (https://github.com/microsoft/vscode-remote-release/issues/8449)

**Comment by deepaerial** [comment]
@chrmarti I've logged out using command you provided and it seems it worked. But this behaviour is very weird. I expected VSCode to show some error message in notifications that token was expired.

**Comment by chrmarti** [comment]
The server doesn't tell us the token is expired. The fix for https://github.com/microsoft/vscode-remote-release/issues/8449 will improve this by retrying without token (which would have worked in your case). Closing as duplicate. Thanks.
