### ISSUE TITLE
[Remote-SSH Bug]: VS Code Server for x86_64 used on M2 Mac instead of arm64

### ISSUE THREAD

**Issue by petermbauer** [microsoft/vscode-remote-release#8525]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

The arm64 version of the VS Code server should be downloaded and used.

### Steps To Reproduce

1. Connect to an M2 Mac (i guess this is the same for M1 Macs) per ssh
2. Wait for the error

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[08:19:24.953] Log Level: 2
[08:19:24.967] SSH Resolver called for "ssh-remote+mac-host", attempt 1
[08:19:24.968] "remote.SSH.useLocalServer": false
[08:19:24.968] "remote.SSH.showLoginTerminal": false
[08:19:24.968] "remote.SSH.remotePlatform": {}
[08:19:24.968] "remote.SSH.path": undefined
[08:19:24.968] "remote.SSH.configFile": undefined
[08:19:24.968] "remote.SSH.useFlock": true
[08:19:24.969] "remote.SSH.lockfilesInTmp": false
[08:19:24.969] "remote.SSH.localServerDownload": auto
[08:19:24.969] "remote.SSH.remoteServerListenOnSocket": false
[08:19:24.969] "remote.SSH.showLoginTerminal": false
[08:19:24.971] "remote.SSH.defaultExtensions": []
[08:19:24.971] "remote.SSH.loglevel": 2
[08:19:24.971] "remote.SSH.enableDynamicForwarding": true
[08:19:24.971] "remote.SSH.enableRemoteCommand": false
[08:19:24.972] "remote.SSH.serverPickPortsFromRange": {}
[08:19:24.972] "remote.SSH.serverInstallPath": {}
[08:19:24.979] VS Code version: 1.78.2
[08:19:24.979] Remote-SSH version: remote-ssh@0.102.0
[08:19:24.979] win32 x64
[08:19:24.980] SSH Resolver called for host: mac-host
[08:19:24.980] Setting up SSH remote "mac-host"
[08:19:25.007] Using commit id "b3e4e68a0bc097f0ae7907b217c1119af9e03435" and quality "stable" for server
[08:19:25.014] Install and start server if needed
[08:19:27.185] Checking ssh with "C:\programs\oraX86\12.1.0.2.0.x86\bin\ssh.exe -V"
[08:19:27.189] Got error from ssh: spawn C:\programs\oraX86\12.1.0.2.0.x86\bin\ssh.exe ENOENT
[08:19:27.189] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[08:19:27.192] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[08:19:27.192] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[08:19:27.194] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[08:19:27.195] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[08:19:27.197] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[08:19:27.198] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[08:19:27.201] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[08:19:27.201] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[08:19:27.254] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[08:19:27.258] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 55978 "mac-host" bash
[08:19:27.261] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[08:19:27.576] > ]0;C:\WINDOWS\System32\cmd.exe
[08:19:27.577] Got some output, clearing connection timeout
[08:19:27.874] > Password:
[08:19:27.874] Showing password prompt
[08:19:30.984] Got password response
[08:19:30.985] "install" wrote data to terminal: "*********"
[08:19:30.996] > 
[08:19:31.392] > 5d5c16cef315: running
[08:19:31.429] > Acquiring lock on /Users/remoteuser/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119
> af9e03435/vscode-remote-lock.remoteuser.b3e4e68a0bc097f0ae7907b217c1119af9e03435      
> \ln /Users/remoteuser/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/vsco
> de-remote-lock.remoteuser.b3e4e68a0bc097f0ae7907b217c1119af9e03435.target /Users/remoteuser/
> .vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/vscode-remote-lock.f
> wsw.b3e4e68a0bc097f0ae7907b217c1119af9e03435
> Installing to /Users/remoteuser/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e
> 03435...
[08:19:31.446] > 5d5c16cef315%%1%%
> Downloading with curl
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed  
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 
[08:19:32.677] >   0     0    0     0 
[08:19:32.688] >    0     0      0      0 --:--:--  0:00:01 --:--:--     0
[08:19:33.689] >   0     0    0     0  
[08:19:33.703] >   0     0      0      0 --:--:--  0:00:02 --:--:--     0
[08:19:34.698] >   0     0    0     0    0 
[08:19:34.713] >     0      0      0 --:--:--  0:00:03 --:--:--     0
[08:19:35.708] >   0     0    0     0
[08:19:35.725] >     0     0      0      0 --:--:--  0:00:04 --:--:--     0
[08:19:36.719] >   0     0    0     0    0  
[08:19:36.732] >    0      0      0 --:--:--  0:00:05 --:--:--     0
[08:19:37.729] >   0     0    0     0    0
[08:19:37.749] >      0      0      0 --:--:--  0:00:06 --:--:--     0
[08:19:38.448] >   0     0    0     0    0
[08:19:38.458] >   0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0 
> curl: (28) SSL connection timeout
> curl download failed
> 000
> printenv:
>     SHELL=/bin/zsh
>     TMPDIR=/var/folders/rg/hhfc3h9d30s215vqqxvq2z5w0000gn/T/
>     SSH_CLIENT=AA.BB.CC.DD 55979 22
>     USER=remoteuser
>     VSCODE_AGENT_FOLDER=/Users/remoteuser/.vscode-server
>     PATH=/usr/bin:/bin:/usr/sbin:/sbin
>     PWD=/Users/remoteuser/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435
>     SHLVL=1
>     HOME=/Users/remoteuser
>     LOGNAME=remoteuser
>     SSH_CONNECTION=10.187.231.166 55979 10.170.41.49 22
>     _=/usr/bin/printenv
>     OLDPWD=/Users/remoteuser
> Trigger local server download
> 5d5c16cef315:trigger_server_download
> platform==macOS==
> vscodeArch==arm64==
> destFolder==/Users/remoteuser/.vscode-server/bin/==
> destFolder2==b3e4e68a0bc097f0ae7907b217c1119af9e03435==
> 5d5c16cef315:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /Users/remoteuser/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03
> 435/vscode-scp-done.flag and vscode-server.tar.gz to exist
> 
[08:19:38.458] Got request to download on client for {"platform":"macOS","arch":"arm64","destFolder":"/Users/remoteuser/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435"}
[08:19:38.459] Downloading VS Code server locally...
[08:19:47.258] Downloaded VS Code server to c:\Users\myuser\AppData\Local\Temp\d159a7b3-2764-440f-bbc1-fab03dd006b9
[08:19:47.261] Renamed VS Code server to c:\Users\myuser\AppData\Local\Temp\vscode_server_1684909187258\vscode-server.tar.gz
[08:19:47.264] Checking ssh with "C:\programs\oraX86\12.1.0.2.0.x86\bin\ssh.exe -V"
[08:19:47.266] Got error from ssh: spawn C:\programs\oraX86\12.1.0.2.0.x86\bin\ssh.exe ENOENT
[08:19:47.267] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[08:19:47.269] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[08:19:47.270] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[08:19:47.271] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[08:19:47.272] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[08:19:47.274] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[08:19:47.274] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[08:19:47.276] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[08:19:47.276] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[08:19:47.328] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[08:19:47.331] Expecting scp to be next to ssh at C:\WINDOWS\System32\OpenSSH\scp.exe
[08:19:47.332] Testing scp with "C:\WINDOWS\System32\OpenSSH\scp.exe"
[08:19:47.444] scp exited with code: 1
[08:19:47.444] Got stderr from scp: usage: scp [-346BCpqrTv] [-c cipher] [-F ssh_config] [-i identity_file]
            [-J destination] [-l limit] [-o ssh_option] [-P port]
            [-S program] source ... target
[08:19:47.445] Copying file to remote with "C:\WINDOWS\System32\OpenSSH\scp.exe" "vscode-server.tar.gz" "vscode-scp-done.flag" "mac-host":"/Users/remoteuser/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435"
[08:19:47.445] Using cwd: file:///c%3A/Users/myuser/AppData/Local/Temp/vscode_server_1684909187258
[08:19:47.445] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[08:19:47.701] > ]0;C:\WINDOWS\System32\cmd.exe
[08:19:48.034] > Password:
[08:19:48.034] Showing password prompt
[08:19:54.061] Got password response
[08:19:54.062] "Copy server to host" wrote data to terminal: "*********"
[08:19:54.076] > 
[08:19:54.452] > vscode-server.tar.gz                            0%    0     0.0KB/s   --:-- ETA
...
[08:20:40.031] > vscode-server.tar.gz                          100%   51MB   1.1MB/s   00:45    
[08:20:40.049] > 
[08:20:40.065] > vscode-scp-done.flag                            0%    0     0.0KB/s   --:-- ETA
[08:20:40.082] > vscode-scp-done.flag                          100%    9     0.4KB/s   00:00    
[08:20:40.099] > 
[08:20:41.394] "Copy server to host" terminal command done
[08:20:41.762] > Found flag and server on host
[08:20:41.782] > 5d5c16cef315%%2%%
> tar --version:
> bsdtar 3.5.3 - libarchive 3.5.3 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8
[08:20:41.789] > 
[08:20:42.336] > Checking /Users/remoteuser/.vscode-server/.b3e4e68a0bc097f0ae7907b217c1119af9e03435.lo
> g and /Users/remoteuser/.vscode-server/.b3e4e68a0bc097f0ae7907b217c1119af9e03435.pid f
> or a running server
[08:20:42.366] > Running ssh connection command... /Users/remoteuser/.vscode-server/bin/b3e4e68a0bc097f
> 0ae7907b217c1119af9e03435/bin/code-server --start-server --host=127.0.0.1 --acce
> pt-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level
>  all   &> "/Users/remoteuser/.vscode-server/.b3e4e68a0bc097f0ae7907b217c1119af9e03435.
> log" < /dev/null
> printenv:
>     SHELL=/bin/zsh
>     TMPDIR=/var/folders/rg/hhfc3h9d30s215vqqxvq2z5w0000gn/T/
>     SSH_CLIENT=10.187.231.166 55979 22
>     USER=remoteuser
>     VSCODE_AGENT_FOLDER=/Users/remoteuser/.vscode-server
>     PATH=/usr/bin:/bin:/usr/sbin:/sbin
>     PWD=/Users/remoteuser
>     SHLVL=1
>     HOME=/Users/remoteuser
>     LOGNAME=remoteuser
>     SSH_CONNECTION=10.187.231.166 55979 10.170.41.49 22
>     _=/usr/bin/printenv
[08:20:42.371] > 
>     OLDPWD=/Users/remoteuser/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e034
> 35
> rm: /Users/remoteuser/.vscode-server/.b3e4e68a0bc097f0ae7907b217c1119af9e03435.token: 
> No such file or directory
> Spawned remote server: 24095
> Waiting for server log...
[08:20:42.387] > 
[08:20:42.416] > Waiting for server log...
...
[08:20:57.106] >  
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-lice
> nse) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacyst
> atement).
> *
> 
[08:20:57.117] > 
> Server did not start successfully. Full server log at /Users/remoteuser/.vscode-server
> /.b3e4e68a0bc097f0ae7907b217c1119af9e03435.log >>>
> /Users/remoteuser/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/bin/code
> -server: line 22: /Users/remoteuser/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119
> af9e03435/node: Bad CPU type in executable
> <<< End of server log
> 5d5c16cef315: start
> exitCode==32==
> listeningOn====
> osReleaseId==Darwin==
> arch==arm64==
> vscodeArch==arm64==
> bitness==64==
[08:20:57.122] > 
> tmpDir==/tmp==
> platform==macOS==
> unpackResult==success==
> didLocalDownload==1==
> downloadTime====
> installTime==1000==
> extInstallTime====
> serverStartTime==15000==
> 5d5c16cef315: end
[08:20:57.123] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==Darwin==
arch==arm64==
vscodeArch==arm64==
bitness==64==
tmpDir==/tmp==
platform==macOS==
unpackResult==success==
didLocalDownload==1==
downloadTime====
installTime==1000==
extInstallTime====
serverStartTime==15000==

[08:20:57.125] Resolver error: Error: The VS Code Server failed to start
	at m.ServerInstallError (c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:584079)
	at f (c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:578136)
	at t.handleInstallOutput (c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:581161)
	at t.tryInstall (c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:681881)
	at async c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:644110
	at async t.withShowDetailsEvent (c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:647428)
	at async t.resolve (c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:645160)
	at async c:\Users\myuser\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:720916
[08:20:57.133] ------




[08:20:58.419] "install" terminal command done
[08:20:58.420] Install terminal quit with output: 
```

</p>
</details>

### Anything else?

VS Code 1.78.2
Remote - SSH v0.102.0

**Comment by petermbauer** [comment]
This output shows that the node executable is actually an x86_64 executable:
```
$ file /Users/remoteuser/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/node
/Users/remoteuser/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/node: Mach-O 64-bit executable x86_64
```

**Comment by roblourens** [comment]
Looks like there was an oversight when we added the arm vscode server for mac, we won't download the proper server when  doing the "local download"

**Comment by petermbauer** [comment]
Thanks a lot for looking into this. The Mac remote does not have Internet access, so unfortunately this is not an option.

**Comment by petermbauer** [comment]
Did i miss something here or what is the solution?

**Comment by roblourens** [comment]
I pushed a fix which is out in the pre-release now, and will be out in the next stable release

**Comment by TylerLeonhardt** [comment]
@petermbauer can you give the pre-release version a try to we can verify this is fixed for you?

**Comment by roblourens** [comment]
This can also be verified by someone with mac arm, set `"remote.SSH.localServerDownload": "always"` then connect to an ssh remote

**Comment by petermbauer** [comment]
@TylerLeonhardt i can confirm that it works with the `v0.103.2023062115` pre-release version.
Thanks a lot for solving this so quickly!
