### ISSUE TITLE
Devcontainer fails to run

### ISSUE THREAD

**Issue by adam-fowler** [microsoft/vscode-remote-release#8528]
If I attempt to open a workspace in a devcontainer nothing seems to happen. This has only just recently started. It was working fine previously and it only occurs in workspaces where a devcontainer doesn't already exist.

- VSCode Version: 1.78.2
- Local OS Version: macOS 13.0.1 (M1 Mac)
- Remote OS Version: Ubuntu Jammy
- Remote Extension/Connection Type: Containers

- Logs:
This is output to the "Extension Host" log
```
[error] {"message":"Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/adamfowler/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /Users/adamfowler/Developer/server/soto-project/soto-core --log-level debug --log-format json --config /Users/adamfowler/Developer/server/soto-project/soto-core/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true","code":1} remote-containers.reopenInContainer {"value":"ms-vscode-remote.remote-containers","c":"ms-vscode-remote.remote-containers"}
```

Steps to Reproduce:

1. Run command `Reopen in container`

Here is the devcontainer.json file
```json
{
    "name": "Swift",
    "image": "swift:5.8",
    "features": {
        "ghcr.io/devcontainers/features/common-utils:2": {
            "installZsh": "false",
            "username": "vscode",
            "userUid": "1000",
            "userGid": "1000",
            "upgradePackages": "false"
        },
        "ghcr.io/devcontainers/features/git:1": {
            "version": "os-provided",
            "ppa": "false"
        }
    },
    "runArgs": [
        "--cap-add=SYS_PTRACE",
        "--security-opt",
        "seccomp=unconfined"
    ],
    // Configure tool-specific properties.
    "customizations": {
        // Configure properties specific to VS Code.
        "vscode": {
            // Set *default* container specific settings.json values on container create.
            "settings": {
                "lldb.library": "/usr/lib/liblldb.so"
            },
            // Add the IDs of extensions you want installed when the container is created.
            "extensions": [
                "sswg.swift-lang"
            ]
        }
    },
    // Use 'postCreateCommand' to run commands after the container is created.
    "postCreateCommand": "swift --version",

    // Set `remoteUser` to `root` to connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
    "remoteUser": "vscode"
}
```

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Please append the Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)

**Comment by adam-fowler** [comment]
I got slightly further. I am getting a log now. It appears to be failing because it requires authentication for ghcr.io. Which is a little more informative than it was previously
```
[12666 ms] Dev Containers 0.292.0 in VS Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435).
[12666 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[12733 ms] 1.42
[12912 ms] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/adamfowler/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /Users/adamfowler/Developer/server/hummingbird-project/hummingbird --log-level debug --log-format json --config /Users/adamfowler/Developer/server/hummingbird-project/hummingbird/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root true
[13050 ms] @devcontainers/cli 0.40.0. Node.js v16.17.1. darwin 22.1.0 arm64.
[13050 ms] Start: Run: git rev-parse --show-cdup
[13061 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/adamfowler/Developer/server/hummingbird-project/hummingbird --filter label=devcontainer.config_file=/Users/adamfowler/Developer/server/hummingbird-project/hummingbird/.devcontainer/devcontainer.json
[13112 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/adamfowler/Developer/server/hummingbird-project/hummingbird
[13163 ms] * Processing feature: ghcr.io/devcontainers/features/common-utils:2
[13378 ms] Start: Run: docker-credential-desktop get
[13813 ms] [httpOci] Could not fetch bearer token for 'ghcr.io': Error: HTTP 403: Forbidden
[13813 ms] [httpOci] ERR: Failed to fetch Bearer token from registry.
[13813 ms] Request 'https://ghcr.io/v2/devcontainers/features/common-utils/manifests/2' failed
[13813 ms] Could not resolve Feature manifest for 'ghcr.io/devcontainers/features/common-utils:2'.  If necessary, provide registry credentials with 'docker login <registry>'.
[13813 ms] Github feature.
[13813 ms] Could not resolve Feature 'ghcr.io/devcontainers/features/common-utils:2'.  Ensure the Feature is published and accessible from your current environment.
[13813 ms] Error: Failed to process feature ghcr.io/devcontainers/features/common-utils:2
    at Wie (/Users/adamfowler/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:1874:3166)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Xm (/Users/adamfowler/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:1874:2263)
    at async Iae (/Users/adamfowler/.vscode/extensions/ms-vscode-remote.remote-containers-0.292.0/dist/spec-node/devContainersSpecCLI.js:2092:33794)
[13821 ms] Exit code 1
```

**Comment by chrmarti** [comment]
Could you retry with Dev Container 0.294.0-pre-release? That has a fix for when the access token has expired.

**Comment by adam-fowler** [comment]
The pre-release fixes this
