### ISSUE TITLE
[Remote-SSH Bug]: Unable to install remote ssh - CorruptZip: end of central directory record signature not found

### ISSUE THREAD

**Issue by lennethli** [microsoft/vscode-remote-release#8553]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Steps To Reproduce

1. Download the latest visual studio code
2. Click the install (release and pre-release) in the extension Remote - SSH

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
2023-05-30 09:59:42.055 [error] CorruptZip: end of central directory record signature not found
    at pt.download (c:\Users\lenne\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:88:141)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async x.y (c:\Users\lenne\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:88:20937)
    at async x.h (c:\Users\lenne\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:88:19006)
2023-05-30 09:59:42.075 [error] end of central directory record signature not found: CorruptZip: end of central directory record signature not found
    at pt.download (c:\Users\lenne\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:88:141)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async x.y (c:\Users\lenne\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:88:20937)
    at async x.h (c:\Users\lenne\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:88:19006)
2023-05-30 09:59:45.080 [error] Failed to find installed remote extension: Error: Failed to find installed remote extension
    at vscode-file://vscode-app/c:/Users/lenne/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1353:32171
    at async U (vscode-file://vscode-app/c:/Users/lenne/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:97:19994)
    at async Ul.u (vscode-file://vscode-app/c:/Users/lenne/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1353:32095)
    at async vscode-file://vscode-app/c:/Users/lenne/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1353:31117
```

</p>
</details>

### Anything else?

My local Mobaxterm can connect successfully but I just can't install the remote ssh on visual studio.
- tried uninstall/install visual studio code
- tried manually download via vsix but same error message

**Comment by roblourens** [comment]
So this is just with installing the Remote-SSH extension, right? Are you connecting through a proxy or something that might interfere with your downloaded content?

**Comment by lennethli** [comment]
Yes, I can install other extensions with no problem. Only Remote-SSH gives me this error. I am not using proxy or anything

**Comment by sandy081** [comment]
> tried manually download via vsix but same error message

Can you please share the vsix?

**Comment by lennethli** [comment]
> > tried manually download via vsix but same error message
> 
> Can you please share the vsix?
Yes! I downloaded it directly from the visual studio prompt
[ms-vscode-remote.remote-ssh-0.102.0.zip](https://github.com/microsoft/vscode-remote-release/files/11637296/ms-vscode-remote.remote-ssh-0.102.0.zip)
note:I couldn't attach vsix directly so I compressed it

**Comment by sandy081** [comment]
> It generates the same error output as attached in the initial post.

Initial output you attached is not from shared process log. Can you please share the log from 

F1 > Open View... > Shared

Which version of VS Code are you currently on?

**Comment by cwherring** [comment]
We were seeing this issue as well with VS Code 1.80.0 and the Remote SSH extension.  We rolled VS Code back to 1.78.1 and it installed fine.

**Comment by sandy081** [comment]
Can you please share the log from

F1 > Open View... > Shared

Which version of VS Code are you currently on?

**Comment by arielgee** [comment]
I'm having the same problem.

**<ins>VSCode</ins>**
```
Version: 1.82.0 (user setup)
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:07:07.438Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19041
```

**<ins>vsix (zipped)</ins>**
[ms-vscode-remote.remote-ssh-0.107.2023091115.vsix.zip](https://github.com/microsoft/vscode-remote-release/files/12586739/ms-vscode-remote.remote-ssh-0.107.2023091115.vsix.zip)

**<ins>Shared process log</ins>**
```
2023-09-12 16:11:49.949 [info] Installing extension: ms-vscode-remote.remote-ssh
2023-09-12 16:11:51.153 [info] Getting Manifest... ms-vscode-remote.remote-ssh-edit
2023-09-12 16:11:51.156 [info] Getting Manifest... ms-vscode.remote-explorer
2023-09-12 16:11:51.240 [info] Installing extension: ms-vscode-remote.remote-ssh-edit ms-vscode-remote.remote-ssh
2023-09-12 16:11:51.399 [error] Error while installing the extension: ms-vscode-remote.remote-ssh-edit
2023-09-12 16:11:51.401 [error] [uncaught exception in sharedProcess]: end of central directory record signature not found: CorruptZip: end of central directory record signature not found
    at w.download (c:\Users\XXXXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:92:141)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async B.x (c:\Users\XXXXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:92:19757)
    at async B.h (c:\Users\XXXXXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:92:17797)
```
