### ISSUE TITLE
Trying use VSCODE in a sharing hosting of  a customer: listen EACCES: permission denied /run/user/{remote_correct_user_name}/vscode-ssh-remote

### ISSUE THREAD

**Issue by iappaPedroza** [microsoft/vscode-remote-release#8565]
[10:59:26.314] Log Level: 2
[10:59:26.527] VS Code version: 1.78.2
[10:59:26.528] Remote-SSH version: remote-ssh@0.102.0
[10:59:26.530] win32 x64
[10:59:27.117] SSH Resolver called for "ssh-remote+{remote_IP}", attempt 1
[10:59:27.123] "remote.SSH.useLocalServer": false
[10:59:27.124] "remote.SSH.showLoginTerminal": true
[10:59:27.126] "remote.SSH.remotePlatform": {"{other_VPS_VSCODE_OK_remote_IP}":"linux","{other_VPS2_VSCODE_OK_remote_IP}":"linux","{remote_IP}":"linux"}
[10:59:27.127] "remote.SSH.path": undefined
[10:59:27.128] "remote.SSH.configFile": undefined
[10:59:27.129] "remote.SSH.useFlock": true
[10:59:27.130] "remote.SSH.lockfilesInTmp": false
[10:59:27.131] "remote.SSH.localServerDownload": auto
[10:59:27.132] "remote.SSH.remoteServerListenOnSocket": true
[10:59:27.133] "remote.SSH.showLoginTerminal": true
[10:59:27.134] "remote.SSH.defaultExtensions": []
[10:59:27.134] "remote.SSH.loglevel": 2
[10:59:27.184] "remote.SSH.enableDynamicForwarding": true
[10:59:27.199] "remote.SSH.enableRemoteCommand": false
[10:59:27.200] "remote.SSH.serverPickPortsFromRange": {}
[10:59:27.200] "remote.SSH.serverInstallPath": {}
[10:59:27.227] SSH Resolver called for host: {remote_IP}
[10:59:27.227] Setting up SSH remote "{remote_IP}"
[10:59:27.329] Using commit id "b3e4e68a0bc097f0ae7907b217c1119af9e03435" and quality "stable" for server
[10:59:27.446] Install and start server if needed
[10:59:27.467] Checking ssh with "C:\Users\{USER_NAME}\bin\ssh.exe -V"
[10:59:27.561] Got error from ssh: spawn C:\Users\{USER_NAME}\bin\ssh.exe ENOENT
[10:59:27.563] Checking ssh with "C:\Program Files\Git\mingw64\bin\ssh.exe -V"
[10:59:27.577] Got error from ssh: spawn C:\Program Files\Git\mingw64\bin\ssh.exe ENOENT
[10:59:27.578] Checking ssh with "C:\Program Files\Git\usr\local\bin\ssh.exe -V"
[10:59:27.592] Got error from ssh: spawn C:\Program Files\Git\usr\local\bin\ssh.exe ENOENT
[10:59:27.593] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[10:59:30.478] > OpenSSH_9.2p1, OpenSSL 1.1.1t  7 Feb 2023

[10:59:30.642] Running script with connection command: "C:\Program Files\Git\usr\bin\ssh.exe" -T -D 51616 "{remote_IP}" bash
[10:59:30.660] Terminal shell path: C:\Windows\System32\cmd.exe
[10:59:38.934] > 10bbe8cd13d0: running
> ]0;C:\Windows\System32\cmd.exe10bbe8cd13d0: running
> Acquiring lock on /home/{remote_USER_NAME}/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9
> e03435/vscode-remote-lock.{remote_USER_NAME}.b3e4e68a0bc097f0ae7907b217c1119af9e03435
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[10:59:38.943] Got some output, clearing connection timeout
[10:59:39.379] > Found existing installation at /home/{remote_USER_NAME}/.vscode-server/bin/b3e4e68a0bc097f0ae790
> 7b217c1119af9e03435...
> Checking /home/{remote_USER_NAME}/.vscode-server/.b3e4e68a0bc097f0ae7907b217c1119af9e03435.log a
> nd /home/{remote_USER_NAME}/.vscode-server/.b3e4e68a0bc097f0ae7907b217c1119af9e03435.pid for a r
> unning server
> Looking for server with pid: 3793280
> Found running server...    
> 
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement)
> .
[10:59:39.568] > 
> *
> 
> Server did not start successfully. Full server log at /home/{remote_USER_NAME}/.vscode-server/.b
> 3e4e68a0bc097f0ae7907b217c1119af9e03435.log >>>
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement)
> .
> *
> [13:57:40]
> 
> 
> 
> 
> [13:57:40] Extension host agent started.
> [13:57:40] Error occurred in server
> [13:57:40] Error: listen EACCES: permission denied /run/user/{remote_correct_user_name}/vscode-ssh-remote
> -server-sock-1685800630
>     at Server.setupListenHandle [as _listen2] (node:net:1415:21)
>     at listenInCluster (node:net:1480:12)
>     at Server.listen (node:net:1579:5)
>     at start (/home/{remote_USER_NAME}/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e034
> 35/out/server-main.js:5:823)
>     at Object.<anonymous> (/home/{remote_USER_NAME}/.vscode-server/bin/b3e4e68a0bc097f0ae7907b21
> 7c1119af9e03435/out/server-main.js:15:28)
>     at Module._compile (node:internal/modules/cjs/loader:1126:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
>     at Module.load (node:internal/modules/cjs/loader:1004:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:839:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12
> ) {
>   code: 'EACCES',
>   errno: -13,
>   syscall: 'listen',
>   address: '/run/user/{remote_correct_user_name}/vscode-ssh-remote-server-sock-1685800630',
>   port: -1
> }
> [13:57:40] Started initializing default profile extensions in extensions installation fo
> lder. file:///home/{remote_USER_NAME}/.vscode-server/extensions
> [13:57:40] Completed initializing default profile extensions in extensions installation 
> folder. file:///home/{remote_USER_NAME}/.vscode-server/extensions
> <<< End of server log
> 10bbe8cd13d0: start
> exitCode==32==
> listeningOn====
> osReleaseId==Linux==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/{remote_correct_user_name}==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 10bbe8cd13d0: end
[10:59:39.572] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==Linux==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/{remote_correct_user_name}==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[10:59:39.575] listen EACCES: permission denied /run/user/{remote_correct_user_name}/vscode-ssh-remote

[10:59:39.581] Resolver error: Error: listen EACCES: permission denied /run/user/{remote_correct_user_name}/vscode-ssh-remote

	at m.ServerInstallError (c:\Users\{USER_NAME}\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:584079)
	at h (c:\Users\{USER_NAME}\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:577155)
	at t.handleInstallOutput (c:\Users\{USER_NAME}\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:581135)
	at t.tryInstall (c:\Users\{USER_NAME}\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:681881)
	at async c:\Users\{USER_NAME}\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:644110
	at async t.withShowDetailsEvent (c:\Users\{USER_NAME}\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:647428)
	at async t.resolve (c:\Users\{USER_NAME}\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:645160)
	at async c:\Users\{USER_NAME}\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:720916
[10:59:39.650] ------

[10:59:43.762] "install" terminal command done
[10:59:43.764] Install terminal quit with output: 

May somebody lend a hand here?

The other access in VPS servers RemoteSSH work fine.

**Comment by mamprogr** [comment]
I am facing the same issue with cPanel server

**Comment by roblourens** [comment]
It looks like your user doesn't have permission to access the referenced folder, which it should. Is that right?
