### ISSUE TITLE
[Remote-SSH Bug]: could not establish connection to XXX: The VSCode Server failed to start

### ISSUE THREAD

**Issue by Cindy0725** [microsoft/vscode-remote-release#8574]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

My PC is windows11 and the remote host is Ubuntu. I tried to Kill the remote server and reconnect to server, I also tried to uninstall SSH remote and install it again. I also tried both values of the remote.SSH.useLocalServer setting. All of these methods don't work for me. 
I also have a macbook pro, it can't connect to the remote server either. I have used VSCode to connect to this remote host for several months, it works well until this afternoon. And I didn't change any setting or config file.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```

> Server did not start successfully. Full server log at /home/zhangyicindy/.vscode
[14:02:09.438] > 
> e-server/.b3e4e68a0bc097f0ae7907b217c1119af9e03435.log >>>
> /home/zhangyicindy/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/n
> node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required b
> by /lib/x86_64-linux-gnu/libstdc++.so.6)
> /home/zhangyicindy/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/n
> node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required b
> by /lib/x86_64-linux-gnu/libstdc++.so.6)
> /home/zhangyicindy/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/n
> node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required b
> by /lib/x86_64-linux-gnu/libstdc++.so.6)
> <<< End of server log
> cb66076d8dff: start
> exitCode==32==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1003==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==14856==
> cb66076d8dff: end
[14:02:09.438] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1003==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==14856==

[14:02:09.440] Resolver error: Error: The VS Code Server failed to start
	at m.ServerInstallError (c:\Users\ZHANG YI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:584079)
	at f (c:\Users\ZHANG YI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:578136)
	at t.handleInstallOutput (c:\Users\ZHANG YI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:581161)
	at t.tryInstall (c:\Users\ZHANG YI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:681881)
	at async c:\Users\ZHANG YI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:644110
	at async t.withShowDetailsEvent (c:\Users\ZHANG YI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:647428)
	at async t.resolve (c:\Users\ZHANG YI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:645160)
	at async c:\Users\ZHANG YI\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:720916
[14:02:09.443] ------




[14:02:09.576] > 
[14:02:10.733] "install" terminal command done
[14:02:10.733] Install terminal quit with output: 
```

</p>
</details>

**Comment by Cindy0725** [comment]
Problem solved. It seems that the error comes from the incompatible version between Ubuntu and GLIBC. After the version become compatible, the problem solved.
