### ISSUE TITLE
Can't turn on remote tunnel access from VS Code

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-remote-release#8579]
- VSCode Version:

Version: 1.79.0-insider (user setup)
Commit: aee52551e25d98391f9064996196cd83a9fc8669
Date: 2023-06-06T15:00:13.166Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.25381

- Local OS Version: Windows 11 Insiders
- Remote OS Version: Remote-Tunnels v1.2.2023060609
- Remote Extension/Connection Type: Remote Tunnels

Steps to Reproduce:

1. Open latest VS Code Insiders
2. "Turn on Remote Tunnel Access..."
3. Sign in with GitHub
4. Fails with logs below. I'm wondering if it has anything to do with me deleting my previous tunnel and unregistering this machine using the `code` CLI. 

- Logs:

```
2023-06-06 15:15:41.571 [info] Running tunnel CLI
2023-06-06 15:15:41.571 [info] status Spawning: c:\Users\brmurtau\AppData\Local\Programs\Microsoft VS Code Insiders\bin\code-tunnel-insiders.exe tunnel status
2023-06-06 15:15:58.266 [info] Session updated: bamurtaugh (github)
2023-06-06 15:15:58.266 [info] Session token updated: bamurtaugh (github)
2023-06-06 15:15:58.398 [info] status terminating(19444)
2023-06-06 15:15:58.399 [info] Running tunnel CLI
2023-06-06 15:15:58.399 [info] status Spawning: c:\Users\brmurtau\AppData\Local\Programs\Microsoft VS Code Insiders\bin\code-tunnel-insiders.exe tunnel status
2023-06-06 15:15:58.400 [error] Canceled: Canceled
    at c:\Users\brmurtau\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:21:11397
    at w.invoke (c:\Users\brmurtau\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:19:145)
    at u.deliver (c:\Users\brmurtau\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:19:2121)
    at a.fire (c:\Users\brmurtau\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:19:1729)
    at N.cancel (c:\Users\brmurtau\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:19:5719)
    at T.cancel (c:\Users\brmurtau\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:19:6133)
    at Object.cancel (c:\Users\brmurtau\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:21:11551)
    at e.RemoteTunnelService.D (c:\Users\brmurtau\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:81:8011)
    at c:\Users\brmurtau\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:81:7654
    at c:\Users\brmurtau\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:21:13683
    at async e.RemoteTunnelService.startTunnel (c:\Users\brmurtau\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:81:7624)
2023-06-06 15:15:58.400 [info] status exit(19444): + null 
2023-06-06 15:16:31.725 [info] [2023-06-06 15:16:31] error could not connect to socket/pipe: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }

2023-06-06 15:16:31.730 [info] status exit(36456): + 1 
```

**Comment by connor4312** [comment]
Hm, I'm not super clear what's going on there. It looks like `status` may have been cancelled too early. Could you turn on trace logging and do that again? Maybe that will provide another hint.

**Comment by bamurtaugh** [comment]
I turned on trace logging, but now I don't see any output in the Remote Tunnel Service output:

![image](https://github.com/microsoft/vscode-remote-release/assets/25310137/7c13a781-6201-498a-95be-962d1b39b881)

**Comment by bamurtaugh** [comment]
I think I needed to sign out and sign back in. I did that, and now it seemed to work!

I'm not sure what changed, but I can close this for now since maybe it was a fleeting issue.
