### ISSUE TITLE
[Remote-SSH Bug]:  Unable to Establish SSH Connection to Remote Server

### ISSUE THREAD

**Issue by Loccret** [microsoft/vscode-remote-release#8605]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### ->

Hello there,

I encountered an issue with the SSH extension today. Previously, it was working correctly without any problems. However, last night I ran my code on a remote server using SSH and then went to bed. When I woke up this morning, I found my local machine in sleep mode. Upon trying to reconnect to the remote server, I received the following error: "Could not establish connection to 'username'." But I still could access the remote server from terminal.

To resolve this issue, I have already attempted the following steps:

- Used the `Remote-SSH: Kill Local Connection Server For Host` command.
- Tried the `Remote-SSH: Kill VS Code Server On Host` command.
- Used the `Remote-SSH: Uninstall VS Code Server from Host` command.
- Deleted the "known_hosts" file.

Unfortunately, despite these attempts, the error still persists. I would appreciate your assistance in resolving this problem.

Thank you,

### Steps To Reproduce

Environment:
VS Code Version: 1.79.1 (user setup)
OS: Windows_NT x64 10.0.19044
Remote - SSH version: 0.102.0

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[11:56:35.970] Log Level: 2
[11:56:35.983] SSH Resolver called for "ssh-remote+li", attempt 1
[11:56:35.984] "remote.SSH.useLocalServer": false
[11:56:35.984] "remote.SSH.showLoginTerminal": false
[11:56:35.984] "remote.SSH.remotePlatform": {"li":"linux"}
[11:56:35.984] "remote.SSH.path": undefined
[11:56:35.984] "remote.SSH.configFile": undefined
[11:56:35.984] "remote.SSH.useFlock": true
[11:56:35.984] "remote.SSH.lockfilesInTmp": false
[11:56:35.985] "remote.SSH.localServerDownload": auto
[11:56:35.985] "remote.SSH.remoteServerListenOnSocket": false
[11:56:35.985] "remote.SSH.showLoginTerminal": false
[11:56:35.985] "remote.SSH.defaultExtensions": []
[11:56:35.985] "remote.SSH.loglevel": 2
[11:56:35.986] "remote.SSH.enableDynamicForwarding": true
[11:56:35.986] "remote.SSH.enableRemoteCommand": false
[11:56:35.986] "remote.SSH.serverPickPortsFromRange": {}
[11:56:35.986] "remote.SSH.serverInstallPath": {}
[11:56:35.991] VS Code version: 1.79.1
[11:56:35.991] Remote-SSH version: remote-ssh@0.102.0
[11:56:35.991] win32 x64
[11:56:35.993] SSH Resolver called for host: li
[11:56:35.993] Setting up SSH remote "li"
[11:56:35.998] Using commit id "4cb974a7aed77a74c7813bdccd99ee0d04901215" and quality "stable" for server
[11:56:36.004] Install and start server if needed
[11:56:36.008] Checking ssh with "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe -V"
[11:56:36.012] Got error from ssh: spawn C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[11:56:36.012] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin\ssh.exe -V"
[11:56:36.013] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin\ssh.exe ENOENT
[11:56:36.013] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\libnvvp\ssh.exe -V"
[11:56:36.014] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\libnvvp\ssh.exe ENOENT
[11:56:36.014] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[11:56:36.015] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[11:56:36.016] Checking ssh with "C:\Windows\ssh.exe -V"
[11:56:36.017] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[11:56:36.017] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[11:56:36.018] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[11:56:36.019] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[11:56:36.019] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[11:56:36.020] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[11:56:36.053] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[11:56:36.058] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 49236 li bash
[11:56:36.061] Terminal shell path: C:\Windows\System32\cmd.exe
[11:56:36.336] > ]0;C:\Windows\System32\cmd.exe
[11:56:36.337] Got some output, clearing connection timeout
[11:56:36.384] > li@133.55.113.219's password: 
[11:56:36.384] Showing password prompt
[11:56:39.573] Got password response
[11:56:39.574] "install" wrote data to terminal: "********"
[11:56:39.585] > 
[11:56:39.704] > 896ee575b303: running
[11:56:39.725] > mkdir: cannot create directory '/home/li/.vscode-server': No space left on devic
> e
> Creating the server install dir failed...
> 896ee575b303: start
> exitCode==34==
> listeningOn====
> osReleaseId====
> arch====
> vscodeArch====
> bitness====
> tmpDir==/tmp==
> platform====
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 896ee575b303: end
[11:56:39.726] Received install output: 
exitCode==34==
listeningOn====
osReleaseId====
arch====
vscodeArch====
bitness====
tmpDir==/tmp==
platform====
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[11:56:39.727] Failed to parse remote port from server output
[11:56:39.729] Resolver error: Error: 
	at m.Create (c:\Users\ENVY\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:584145)
	at t.handleInstallOutput (c:\Users\ENVY\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:582705)
	at t.tryInstall (c:\Users\ENVY\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:681881)
	at async c:\Users\ENVY\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:644110
	at async t.withShowDetailsEvent (c:\Users\ENVY\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:647428)
	at async t.resolve (c:\Users\ENVY\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:645160)
	at async c:\Users\ENVY\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:720916
[11:56:39.738] ------




[11:56:41.005] "install" terminal command done
[11:56:41.006] Install terminal quit with output: 

```

</p>
</details>

**Comment by Loccret** [comment]
The issue has been resolved after I cleared the hard disk of the remote server.
