### ISSUE TITLE
[Remote-SSH Bug]: Connecting fails specifically on home ('~') dir

### ISSUE THREAD

**Issue by jordantgh** [microsoft/vscode-remote-release#8610]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

#7324 and #7554 closest, but supposedly solved in previous patches.

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

---

### Expected Behavior

I expected to be able to use Remote - SSH to connect to the home directory (`/home/home/`, aka `~`) on my home (WLAN networked) server, in the same way that I can connect to the same server on other folders (e.g. `/home/` or `/home/home/Desktop/`), and in the same way that I can connect to the same server on the same folder using the VScode insiders build.

I used to be able to do this without problems. I have only noticed the behaviour as of last night. I was on 1.79.1 and updated to 1.79.2, and the issue persists.

---

### Steps To Reproduce

1. Use vscode1.79.2 on windows 11* , open the remote explorer and select SSH Targets.
2. Click on the server icon for my server named "home" and select "Connect to Host in New Window".**
3. Choose the home directory (`/home/home/`) as the remote folder to open.**
4. See error: Connecting with SSH timed out.

*detailed info: [
  Version: 1.79.2 (system setup)
  Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
  Date: 2023-06-14T08:57:04.379Z
  Electron: 22.5.7
  Chromium: 108.0.5359.215
  Node.js: 16.17.1
  V8: 10.8.168.25-electron.0
  OS: Windows_NT x64 10.0.22621
 ]
 
 **The same behaviour is also observable when I (succesfully) use Remote - SSH to enter another dir, e.g., `/home/home/Desktop`, and from within the VScode bash terminal type `code ~`

---

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[10:10:40.555] Log Level: 2
[10:10:40.564] VS Code version: 1.79.2
[10:10:40.564] Remote-SSH version: remote-ssh@0.102.0
[10:10:40.564] win32 x64
[10:10:40.568] SSH Resolver called for "ssh-remote+home", attempt 1
[10:10:40.568] "remote.SSH.useLocalServer": false
[10:10:40.568] "remote.SSH.showLoginTerminal": true
[10:10:40.569] "remote.SSH.remotePlatform": {"192.168.1.81":"linux","home":"linux","192.168.1.98":"linux","vm":"linux","13.48.57.255":"linux"}
[10:10:40.569] "remote.SSH.path": undefined
[10:10:40.569] "remote.SSH.configFile": C:\Users\jtayl\.ssh\config
[10:10:40.569] "remote.SSH.useFlock": true
[10:10:40.569] "remote.SSH.lockfilesInTmp": false
[10:10:40.569] "remote.SSH.localServerDownload": auto
[10:10:40.569] "remote.SSH.remoteServerListenOnSocket": false
[10:10:40.569] "remote.SSH.showLoginTerminal": true
[10:10:40.569] "remote.SSH.defaultExtensions": []
[10:10:40.569] "remote.SSH.loglevel": 2
[10:10:40.570] "remote.SSH.enableDynamicForwarding": true
[10:10:40.570] "remote.SSH.enableRemoteCommand": false
[10:10:40.570] "remote.SSH.serverPickPortsFromRange": {}
[10:10:40.570] "remote.SSH.serverInstallPath": {}
[10:10:40.573] SSH Resolver called for host: home
[10:10:40.573] Setting up SSH remote "home"
[10:10:40.577] Using commit id "695af097c7bd098fbf017ce3ac85e09bbc5dda06" and quality "stable" for server
[10:10:40.580] Install and start server if needed
[10:10:40.582] Checking ssh with "C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\bin\ssh.exe -V"
[10:10:40.584] Got error from ssh: spawn C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\bin\ssh.exe ENOENT
[10:10:40.584] Checking ssh with "C:\Program Files\Python311\Scripts\ssh.exe -V"
[10:10:40.585] Got error from ssh: spawn C:\Program Files\Python311\Scripts\ssh.exe ENOENT
[10:10:40.585] Checking ssh with "C:\Program Files\Python311\ssh.exe -V"
[10:10:40.586] Got error from ssh: spawn C:\Program Files\Python311\ssh.exe ENOENT
[10:10:40.586] Checking ssh with "C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe -V"
[10:10:40.587] Got error from ssh: spawn C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[10:10:40.587] Checking ssh with "G:\Oculus\Support\oculus-runtime\ssh.exe -V"
[10:10:40.588] Got error from ssh: spawn G:\Oculus\Support\oculus-runtime\ssh.exe ENOENT
[10:10:40.588] Checking ssh with "C:\Program Files (x86)\VMware\VMware Player\bin\ssh.exe -V"
[10:10:40.589] Got error from ssh: spawn C:\Program Files (x86)\VMware\VMware Player\bin\ssh.exe ENOENT
[10:10:40.589] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\ssh.exe -V"
[10:10:40.590] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\ssh.exe ENOENT
[10:10:40.590] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\libnvvp\ssh.exe -V"
[10:10:40.592] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\libnvvp\ssh.exe ENOENT
[10:10:40.592] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\ssh.exe -V"
[10:10:40.593] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\ssh.exe ENOENT
[10:10:40.593] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp\ssh.exe -V"
[10:10:40.594] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp\ssh.exe ENOENT
[10:10:40.594] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[10:10:40.595] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[10:10:40.595] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[10:10:40.596] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[10:10:40.596] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[10:10:40.597] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[10:10:40.597] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[10:10:40.598] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[10:10:40.598] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[10:10:40.626] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[10:10:40.630] Using SSH config file "C:\Users\jtayl\.ssh\config"
[10:10:40.630] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 64024 -F "C:\Users\jtayl\.ssh\config" home bash
[10:10:40.632] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:10:57.641] Resolver error: Error: Connecting with SSH timed out
	at m.Timeout (c:\Users\jtayl\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:584271)
	at Timeout._onTimeout (c:\Users\jtayl\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:680601)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[10:10:57.647] ------




[10:10:58.328] > 86b357dd3aca: running
> ]0;C:\WINDOWS\System32\cmd.exe
[10:10:58.329] Got some output, clearing connection timeout
[10:10:58.329] > 86b357dd3aca: running
> Acquiring lock on /home/home/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/vscode-remote-lock.home.695af097c7bd098fbf017ce3ac85e09bbc5dda06
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[10:10:58.335] > Found existing installation at /home/home/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06...
> Checking /home/home/.vscode-server/.695af097c7bd098fbf017ce3ac85e09bbc5dda06.log and /home/home/.vscode-server/.695af097c7bd098fbf017ce3ac85e09bbc5dda06.pid for a running server
> Looking for server with pid: 423840
[10:10:58.431] > Found running server...
>  
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
>  
> Checking server status on port 39841 with wget
> 86b357dd3aca: start
> SSH_AUTH_SOCK====
> DISPLAY====
> webUiAccessToken====
> listeningOn==39841==
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
[10:10:58.437] > 
> connectionToken==11aaa1a1-1aa1-1a11-a111-11a1aaa1a111==
> 86b357dd3aca: end

```

</p>
</details>

---

### Anything else?

Below are some logs for *succesfull* remote connections; these work reproducibly for me. Note, I have already worried that perhaps the vscode insiders server was causing problems, therefore I killed both and rm -rf'd the respective .vscode-server folders and found the same issue even *de novo*. 

<details>
<summary>Remote-SSH Log - succesful connection to subfolder with same VScode build</summary>
<p>

```
[10:11:57.963] Log Level: 2
[10:11:57.972] VS Code version: 1.79.2
[10:11:57.972] Remote-SSH version: remote-ssh@0.102.0
[10:11:57.972] win32 x64
[10:11:57.975] SSH Resolver called for "ssh-remote+home", attempt 1
[10:11:57.975] "remote.SSH.useLocalServer": false
[10:11:57.976] "remote.SSH.showLoginTerminal": true
[10:11:57.976] "remote.SSH.remotePlatform": {"192.168.1.81":"linux","home":"linux","192.168.1.98":"linux","vm":"linux","13.48.57.255":"linux"}
[10:11:57.976] "remote.SSH.path": undefined
[10:11:57.976] "remote.SSH.configFile": C:\Users\jtayl\.ssh\config
[10:11:57.976] "remote.SSH.useFlock": true
[10:11:57.976] "remote.SSH.lockfilesInTmp": false
[10:11:57.976] "remote.SSH.localServerDownload": auto
[10:11:57.976] "remote.SSH.remoteServerListenOnSocket": false
[10:11:57.976] "remote.SSH.showLoginTerminal": true
[10:11:57.977] "remote.SSH.defaultExtensions": []
[10:11:57.977] "remote.SSH.loglevel": 2
[10:11:57.977] "remote.SSH.enableDynamicForwarding": true
[10:11:57.977] "remote.SSH.enableRemoteCommand": false
[10:11:57.977] "remote.SSH.serverPickPortsFromRange": {}
[10:11:57.977] "remote.SSH.serverInstallPath": {}
[10:11:57.980] SSH Resolver called for host: home
[10:11:57.980] Setting up SSH remote "home"
[10:11:57.983] Using commit id "695af097c7bd098fbf017ce3ac85e09bbc5dda06" and quality "stable" for server
[10:11:57.987] Install and start server if needed
[10:11:57.988] Checking ssh with "C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\bin\ssh.exe -V"
[10:11:57.990] Got error from ssh: spawn C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\bin\ssh.exe ENOENT
[10:11:57.990] Checking ssh with "C:\Program Files\Python311\Scripts\ssh.exe -V"
[10:11:57.991] Got error from ssh: spawn C:\Program Files\Python311\Scripts\ssh.exe ENOENT
[10:11:57.991] Checking ssh with "C:\Program Files\Python311\ssh.exe -V"
[10:11:57.992] Got error from ssh: spawn C:\Program Files\Python311\ssh.exe ENOENT
[10:11:57.992] Checking ssh with "C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe -V"
[10:11:57.993] Got error from ssh: spawn C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[10:11:57.993] Checking ssh with "G:\Oculus\Support\oculus-runtime\ssh.exe -V"
[10:11:57.993] Got error from ssh: spawn G:\Oculus\Support\oculus-runtime\ssh.exe ENOENT
[10:11:57.994] Checking ssh with "C:\Program Files (x86)\VMware\VMware Player\bin\ssh.exe -V"
[10:11:57.994] Got error from ssh: spawn C:\Program Files (x86)\VMware\VMware Player\bin\ssh.exe ENOENT
[10:11:57.994] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\ssh.exe -V"
[10:11:57.995] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\ssh.exe ENOENT
[10:11:57.995] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\libnvvp\ssh.exe -V"
[10:11:57.996] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\libnvvp\ssh.exe ENOENT
[10:11:57.996] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\ssh.exe -V"
[10:11:57.997] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\ssh.exe ENOENT
[10:11:57.997] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp\ssh.exe -V"
[10:11:57.998] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp\ssh.exe ENOENT
[10:11:57.998] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[10:11:57.998] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[10:11:57.998] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[10:11:57.999] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[10:11:57.999] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[10:11:58.000] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[10:11:58.000] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[10:11:58.001] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[10:11:58.001] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[10:11:58.027] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[10:11:58.030] Using SSH config file "C:\Users\jtayl\.ssh\config"
[10:11:58.030] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 64114 -F "C:\Users\jtayl\.ssh\config" home bash
[10:11:58.031] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:12:00.084] > 835847b252b5: running
> ]0;C:\WINDOWS\System32\cmd.exe
[10:12:00.084] Got some output, clearing connection timeout
[10:12:00.100] > 835847b252b5: running
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[10:12:00.113] > Acquiring lock on /home/home/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/vscode-remote-lock.home.695af097c7bd098fbf017ce3ac85e09bbc5dda06
> Found existing installation at /home/home/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06...
> Checking /home/home/.vscode-server/.695af097c7bd098fbf017ce3ac85e09bbc5dda06.log and /home/home/.vscode-server/.695af097c7bd098fbf017ce3ac85e09bbc5dda06.pid for a running server
> Looking for server with pid: 423840
[10:12:00.131] > Found running server...
>  
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
>  
[10:12:00.142] > Checking server status on port 39841 with wget
> 835847b252b5: start
> SSH_AUTH_SOCK====
> DISPLAY====
> webUiAccessToken====
> listeningOn==39841==
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> connectionToken==11aaa1a1-1aa1-1a11-a111-11a1aaa1a111==
> 835847b252b5: end
[10:12:00.142] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==39841==
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==11aaa1a1-1aa1-1a11-a111-11a1aaa1a111==

[10:12:00.142] Remote server is listening on 39841
[10:12:00.142] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":39841},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/1000","platform":"linux","connectionToken":"11aaa1a1-1aa1-1a11-a111-11a1aaa1a111"},"installUnpackCode":""}
[10:12:00.145] Starting forwarding server. localPort 64119 -> socksPort 64114 -> remotePort 39841
[10:12:00.145] Forwarding server listening on 64119
[10:12:00.145] Waiting for ssh tunnel to be ready
[10:12:00.146] [Forwarding server 64119] Got connection 0
[10:12:00.147] Tunneled 39841 to local port 64119
[10:12:00.147] Resolved "ssh-remote+home" to "127.0.0.1:64119"
[10:12:00.154] ------




[10:12:00.167] [Forwarding server 64119] Got connection 1
[10:12:00.184] [Forwarding server 64119] Got connection 2

```

</p>
</details>

<details>
<summary>Remote-SSH Log - succesful connection to CORRECT folder with VScode insiders build</summary>
<p>

```
[10:12:56.436] Log Level: 2
[10:12:56.451] VS Code version: 1.80.0-insider
[10:12:56.451] Remote-SSH version: remote-ssh@0.103.2023061415
[10:12:56.451] win32 x64
[10:12:56.489] SSH Resolver called for "ssh-remote+home", attempt 1
[10:12:56.489] "remote.SSH.useLocalServer": false
[10:12:56.490] "remote.SSH.showLoginTerminal": false
[10:12:56.490] "remote.SSH.remotePlatform": {"home":"linux"}
[10:12:56.490] "remote.SSH.path": undefined
[10:12:56.490] "remote.SSH.configFile": undefined
[10:12:56.490] "remote.SSH.useFlock": true
[10:12:56.490] "remote.SSH.lockfilesInTmp": false
[10:12:56.490] "remote.SSH.localServerDownload": auto
[10:12:56.490] "remote.SSH.remoteServerListenOnSocket": false
[10:12:56.490] "remote.SSH.showLoginTerminal": false
[10:12:56.490] "remote.SSH.defaultExtensions": []
[10:12:56.490] "remote.SSH.loglevel": 2
[10:12:56.490] "remote.SSH.enableDynamicForwarding": true
[10:12:56.490] "remote.SSH.enableRemoteCommand": false
[10:12:56.490] "remote.SSH.serverPickPortsFromRange": {}
[10:12:56.491] "remote.SSH.serverInstallPath": {}
[10:12:56.494] SSH Resolver called for host: home
[10:12:56.494] Setting up SSH remote "home"
[10:12:56.497] Using commit id "61ba389b0a7108af0411c73ab30c7e4350051645" and quality "insider" for server
[10:12:56.499] Install and start server if needed
[10:12:56.504] Checking ssh with "C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\bin\ssh.exe -V"
[10:12:56.505] Got error from ssh: spawn C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot\bin\ssh.exe ENOENT
[10:12:56.506] Checking ssh with "C:\Program Files\Python311\Scripts\ssh.exe -V"
[10:12:56.506] Got error from ssh: spawn C:\Program Files\Python311\Scripts\ssh.exe ENOENT
[10:12:56.507] Checking ssh with "C:\Program Files\Python311\ssh.exe -V"
[10:12:56.507] Got error from ssh: spawn C:\Program Files\Python311\ssh.exe ENOENT
[10:12:56.507] Checking ssh with "C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe -V"
[10:12:56.508] Got error from ssh: spawn C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[10:12:56.508] Checking ssh with "G:\Oculus\Support\oculus-runtime\ssh.exe -V"
[10:12:56.510] Got error from ssh: spawn G:\Oculus\Support\oculus-runtime\ssh.exe ENOENT
[10:12:56.510] Checking ssh with "C:\Program Files (x86)\VMware\VMware Player\bin\ssh.exe -V"
[10:12:56.510] Got error from ssh: spawn C:\Program Files (x86)\VMware\VMware Player\bin\ssh.exe ENOENT
[10:12:56.511] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\ssh.exe -V"
[10:12:56.511] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\ssh.exe ENOENT
[10:12:56.511] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\libnvvp\ssh.exe -V"
[10:12:56.513] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\libnvvp\ssh.exe ENOENT
[10:12:56.513] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\ssh.exe -V"
[10:12:56.514] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\ssh.exe ENOENT
[10:12:56.514] Checking ssh with "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp\ssh.exe -V"
[10:12:56.516] Got error from ssh: spawn C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp\ssh.exe ENOENT
[10:12:56.516] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[10:12:56.517] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[10:12:56.517] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[10:12:56.519] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[10:12:56.519] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[10:12:56.520] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[10:12:56.520] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[10:12:56.522] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[10:12:56.522] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[10:12:56.555] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[10:12:56.559] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 64201 home bash
[10:12:56.560] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:12:57.114] > e05816b12f6e: running
> ]0;C:\WINDOWS\System32\cmd.exe
[10:12:57.114] Got some output, clearing connection timeout
[10:12:57.138] > Acquiring lock on /home/home/.vscode-server-insiders/bin/61ba389b0a7108af0411c73ab30c7e4350051645/vscode-remote-lock.home.61ba389b0a7108af0411c73ab30c7e4350051645
> Found existing installation at /home/home/.vscode-server-insiders/bin/61ba389b0a7108af0411c73ab30c7e4350051645...
> Checking /home/home/.vscode-server-insiders/.61ba389b0a7108af0411c73ab30c7e4350051645.log and /home/home/.vscode-server-insiders/.61ba389b0a7108af0411c73ab30c7e4350051645.pid for a running server
> Looking for server with pid: 423533
> Running ssh connection command... /home/home/.vscode-server-insiders/bin/61ba389b0a7108af0411c73ab30c7e4350051645/bin/code-server-insiders --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all   &> "/home/home/.vscode-server-insiders/.61ba389b0a7108af0411c73ab30c7e4350051645.log" < /dev/null
> printenv:
>     SHELL=/bin/bash
>     LANGUAGE=en_GB:en
>     PWD=/home/home
>     LOGNAME=home
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/home/home
>     LANG=en_GB.UTF-8
>     VSCODE_AGENT_FOLDER=/home/home/.vscode-server-insiders
>     SSH_CONNECTION=192.168.1.152 64202 192.168.1.81 22
>     XDG_SESSION_CLASS=user
>     USER=home
>     SHLVL=0
>     XDG_SESSION_ID=15075
>     XDG_RUNTIME_DIR=/run/user/1000
>     SSH_CLIENT=192.168.1.152 64202 22
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
> s:/usr/local/games:/snap/bin
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
>     _=/usr/bin/printenv
[10:12:57.144] > 
> Removing old logfile at /home/home/.vscode-server-insiders/.61ba389b0a7108af0411
> 1c73ab30c7e4350051645.log
> Spawned remote server: 430854
> Waiting for server log...
[10:12:57.162] > 
[10:12:57.184] > Waiting for server log...
[10:12:57.194] > 
[10:12:57.219] >  
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-lice
> ense) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacyst
> tatement).
> *
> 
[10:12:57.228] > 
> e05816b12f6e: start
> SSH_AUTH_SOCK====
> DISPLAY====
> webUiAccessToken====
> listeningOn==45487==
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==77==
> connectionToken==1a111111-a11a-1a11-1111-a1aaaa111a11==
> e05816b12f6e: end
[10:12:57.229] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====
webUiAccessToken====
listeningOn==45487==
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==77==
connectionToken==1a111111-a11a-1a11-1111-a1aaaa111a11==

[10:12:57.229] Remote server is listening on 45487
[10:12:57.229] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":45487},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/1000","platform":"linux","connectionToken":"1a111111-a11a-1a11-1111-a1aaaa111a11"},"serverStartTime":77,"installUnpackCode":""}
[10:12:57.231] Starting forwarding server. localPort 64204 -> socksPort 64201 -> remotePort 45487
[10:12:57.232] Forwarding server listening on 64204
[10:12:57.232] Waiting for ssh tunnel to be ready
[10:12:57.233] [Forwarding server 64204] Got connection 0
[10:12:57.234] Tunneled 45487 to local port 64204
[10:12:57.234] Resolved "ssh-remote+home" to "127.0.0.1:64204"
[10:12:57.241] ------




[10:12:57.242] > 
[10:12:57.253] [Forwarding server 64204] Got connection 1
[10:12:57.377] [Forwarding server 64204] Got connection 2

```

</p>
</details>

**Comment by roblourens** [comment]
This sounds like https://github.com/microsoft/vscode-remote-release/issues/8586. Do you have the secondary sidebar open?

**Comment by jordantgh** [comment]
> This sounds like #8586. Do you have the secondary sidebar open?

Thanks for getting back to me. I think it's not really the same issue. I don't have a secondary sidebar open, and there are no vscode workspaces in the target folder AFAICT. 

```
home@home-B250-serv:~$ ls -a
.                                  .fontconfig                             R
..                                 .gitconfig                              .selected_editor
anaconda3                          .gnome                                  shiny-server-1.5.20.1002-amd64.deb
Anaconda3-2022.10-Linux-x86_64.sh  google-chrome-stable_current_amd64.deb  shiny-server-1.5.20.1002-x86_64.rpm
.bash_history                      .ipython                                snap
.bash_logout                       .lesshst                                .ssh
.bashrc                            .local                                  .sudo_as_admin_successful
.cache                             microarray-shiny                        Templates
.conda                             Music                                   upsnap
.condarc                           Pictures                                Videos
.config                            .pki                                    .vscode-server
Desktop                            plug-data                               .wget-hsts
Documents                          .profile                                wget-log
.dotnet                            Public
Downloads                          .python_history
```

This is the current contents of the folder - is there anything you see that could be causing the problem? The `.vscode-server` is new; I previously rm -rf'd it & rebooted the server, plus uninstall/re-installed the Remotes extension on my local system, and freshly connected just now. 

As for rolling back to 1.78, I'm willing to try that if you still recommend, but I have never rolled back a vscode version before and I'm worried about messing with my environment and settings if I do so. Before I do that, I just first wanted to point out that I think this is a different issue than #8586.

**Comment by roblourens** [comment]
The title and OP of that post is a bit misleading, to me your log shows the exact same thing so I think it's probably the same underlying issue. It's safe to try 1.78 if you want to do that, and another workaround would be to set `"remote.SSH.useLocalServer": true` (needs to be set directly in your settings.json file)

**Comment by jordantgh** [comment]
OK, thanks again. Adding that to my *user* settings.json seems to have done the trick (it was already present in defaultSettings.json, and checked in the GUI for user & workspace). This was on 1.79.2, so was able to avoid downgrading. I guess there's some issue with the settings GUI not propagating to the .json? Anyway, I'll close this as at least my specific issue is solved, cheers.

**Comment by roblourens** [comment]
Yeah it's a windows-specific override that was supposed to be temporary then was held up due to windows bugs
