### ISSUE TITLE
[Remote-SSH Bug] Opening a folder from a remote machine is impossible

### ISSUE THREAD

**Issue by NicolasWaw** [microsoft/vscode-remote-release#8614]
Type: <b>Bug</b>

Beforehand, less than a week ago i was able to connect to ssh with vscode to my server using the shortcut to connect and directly open a folder from the remote machine. 

But since this weekend, I can no longer connect in ssh by opening a folder on the remote machine .

A "normal" connection works, if i just want to open a ssh connection from vscode via the remote-ssh extension, it's works. But with the shortcut in the remote extension tab or after a successful ssh connection and choose to open a folder, the attempt to open a new ssh connection will fail.

For details, I use a ssh connection with **password**.

Two way to reproduce the bug:
# First way

1. Open a ssh connection with a remote machine using remote-ssh extension

2. Open folder on the remote machine via the vscode menu

3. The ssh connection will fail. A dialog box asks to choose betwen "Close Remote", "Retry" or "More Actions...".

# Second way

*This way only works if a previous connection was achieved with the remote machine and a folder was opened*

1. Click on the "Remote Explorer" tab (remote-tunnel extension shall be install)
2. Click on the shortcut which matches with the folder you want to open on the remote machine
3. The ssh connection will fail. A dialog box asks to choose betwen "Close Remote", "Retry" or "More Actions...".

No matter the way, vscode doesn't ask for the password before the failure. Only the dialog box for password appear after the connection fails.

This below is the log coming from the "Output" terminal (Ctrl+Shift+U) during the attempt of connection:
I replace the domain name of my server by "MyServerDomainName" and my ssh username by "MyServerUserName"
```
[13:34:27.696] Log Level: 2
[13:34:27.707] VS Code version: 1.79.2
[13:34:27.707] Remote-SSH version: remote-ssh@0.102.0
[13:34:27.707] win32 x64
[13:34:27.710] SSH Resolver called for "ssh-remote+MyServerDomainName", attempt 1
[13:34:27.711] "remote.SSH.useLocalServer": false
[13:34:27.711] "remote.SSH.showLoginTerminal": false
[13:34:27.711] "remote.SSH.remotePlatform": {"MyServerDomainName":"linux"}
[13:34:27.711] "remote.SSH.path": undefined
[13:34:27.711] "remote.SSH.configFile": undefined
[13:34:27.711] "remote.SSH.useFlock": true
[13:34:27.711] "remote.SSH.lockfilesInTmp": false
[13:34:27.712] "remote.SSH.localServerDownload": auto
[13:34:27.712] "remote.SSH.remoteServerListenOnSocket": false
[13:34:27.712] "remote.SSH.showLoginTerminal": false
[13:34:27.712] "remote.SSH.defaultExtensions": []
[13:34:27.712] "remote.SSH.loglevel": 2
[13:34:27.712] "remote.SSH.enableDynamicForwarding": true
[13:34:27.712] "remote.SSH.enableRemoteCommand": false
[13:34:27.712] "remote.SSH.serverPickPortsFromRange": {}
[13:34:27.713] "remote.SSH.serverInstallPath": {}
[13:34:27.717] SSH Resolver called for host: MyServerDomainName
[13:34:27.717] Setting up SSH remote "MyServerDomainName"
[13:34:27.720] Using commit id "695af097c7bd098fbf017ce3ac85e09bbc5dda06" and quality "stable" for server
[13:34:27.724] Install and start server if needed
[13:34:27.726] Checking ssh with "C:\Program Files (x86)\VMware\VMware Player\bin\ssh.exe -V"
[13:34:27.728] Got error from ssh: spawn C:\Program Files (x86)\VMware\VMware Player\bin\ssh.exe ENOENT
[13:34:27.728] Checking ssh with "C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\ssh.exe -V"
[13:34:27.729] Got error from ssh: spawn C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin\ssh.exe ENOENT
[13:34:27.729] Checking ssh with "C:\Program Files\Microsoft\jdk-11.0.16.101-hotspot\bin\ssh.exe -V"
[13:34:27.730] Got error from ssh: spawn C:\Program Files\Microsoft\jdk-11.0.16.101-hotspot\bin\ssh.exe ENOENT
[13:34:27.730] Checking ssh with "C:\Program Files\Oculus\Support\oculus-runtime\ssh.exe -V"
[13:34:27.731] Got error from ssh: spawn C:\Program Files\Oculus\Support\oculus-runtime\ssh.exe ENOENT
[13:34:27.731] Checking ssh with "C:\Python310\Scripts\ssh.exe -V"
[13:34:27.732] Got error from ssh: spawn C:\Python310\Scripts\ssh.exe ENOENT
[13:34:27.732] Checking ssh with "C:\Python310\ssh.exe -V"
[13:34:27.732] Got error from ssh: spawn C:\Python310\ssh.exe ENOENT
[13:34:27.732] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[13:34:27.733] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[13:34:27.733] Checking ssh with "C:\Windows\ssh.exe -V"
[13:34:27.734] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[13:34:27.734] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[13:34:27.735] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[13:34:27.735] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[13:34:27.736] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[13:34:27.736] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[13:34:27.756] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[13:34:27.759] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 56836 "MyServerDomainName" bash
[13:34:27.761] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[13:34:44.771] Resolver error: Error: Connecting with SSH timed out
	at m.Timeout (c:\Users\nicol\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:584271)
	at Timeout._onTimeout (c:\Users\nicol\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:680601)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[13:34:44.775] ------




[13:34:45.292] > MyServerUserName@MyServerDomainName's password:]0;C:\WINDOWS\System32\cmd.exe 
[13:34:45.292] Got some output, clearing connection timeout
[13:34:45.293] Showing password prompt
[13:35:04.670] Password dialog canceled
[13:35:04.671] "install" terminal command canceled
```

Extension version: 0.102.0
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700X 8-Core Processor              (16 x 3394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|47.91GB (37.62GB free)|
|Process Argv|--crash-reporter-id 083d0731-67c4-46c8-b7ce-6215133f3bfc|
|Screen Reader|no|
|VM|40%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30730052
showindicator:30766890
pythongtdpath:30769146
i26e3531:30769768
dh2dc718:30770000

```

</details>

**Comment by NicolasWaw** [comment]
Close secondary sidebar as ask in #8586 works.
