### ISSUE TITLE
Code Insiders cannot detect WSL. VSCode (blue one) can.

### ISSUE THREAD

**Issue by phildaniels** [microsoft/vscode-remote-release#8642]
Error: "Windows Subsystem for Linux not detected. The WSL extension requires Windows 10 with the Windows Subsystem for Linux feature installed."

It's worth noting as well, everything works correctly in normal (blue) vscode, I can connect to WSL2 repos there. So I think it's an issue just with insiders. I have also tried running code insiders as an administrator, I've tried completely uninstalling (and deleting extensions / vscode server folders on both sides, windows and WSL) and no luck.

- VSCode Version:
Version: 1.80.0-insider (user setup)
Commit: b4952d14a465572e33f0635ef58de089227b8876
Date: 2023-06-26T05:32:56.741Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
- Local OS Version:
OS: Windows_NT x64 10.0.19045
- Remote OS Version:
WSL2
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
- Remote Extension/Connection Type: Containers/WSL/Server
WSL Extension

- Logs:
2023-06-26 12:21:01.940 [info] Extension host with pid 12876 started
2023-06-26 12:21:01.940 [info] Skipping acquiring lock for c:\Users\phillip.daniels\AppData\Roaming\Code - Insiders\User\workspaceStorage\1ff61fa469e51588d606dbc62d06c428.
2023-06-26 12:21:01.940 [info] $getCanonicalURI invoked for authority (wsl)
2023-06-26 12:21:01.948 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl, startup: false, activationEvent: 'onResolveRemoteAuthority:wsl'
2023-06-26 12:21:01.988 [info] [resolveAuthority(wsl,1)][0ms] activating remote resolvers wsl+Ubuntu
2023-06-26 12:21:01.988 [info] [resolveAuthority(wsl,1)][0ms] activating resolver...
2023-06-26 12:21:01.988 [info] [resolveAuthority(wsl,1)][0ms] invoking final resolve()...
2023-06-26 12:21:02.992 [info] [resolveAuthority(wsl,1)][1004ms] waiting...
2023-06-26 12:21:04.006 [info] [resolveAuthority(wsl,1)][2018ms] waiting...
2023-06-26 12:21:05.020 [info] [resolveAuthority(wsl,1)][3032ms] waiting...
2023-06-26 12:21:06.034 [info] [resolveAuthority(wsl,1)][4046ms] waiting...
2023-06-26 12:21:07.046 [info] [resolveAuthority(wsl,1)][5058ms] waiting...
2023-06-26 12:21:08.051 [info] [resolveAuthority(wsl,1)][6063ms] waiting...
2023-06-26 12:21:09.063 [info] [resolveAuthority(wsl,1)][7075ms] waiting...
2023-06-26 12:21:10.066 [info] [resolveAuthority(wsl,1)][8078ms] waiting...
2023-06-26 12:21:11.066 [info] [resolveAuthority(wsl,1)][9078ms] waiting...
2023-06-26 12:21:12.080 [info] [resolveAuthority(wsl,1)][10092ms] waiting...
2023-06-26 12:21:13.080 [info] [resolveAuthority(wsl,1)][11092ms] waiting...
2023-06-26 12:21:14.090 [info] [resolveAuthority(wsl,1)][12102ms] waiting...
2023-06-26 12:21:15.104 [info] [resolveAuthority(wsl,1)][13116ms] waiting...
2023-06-26 12:21:16.113 [info] [resolveAuthority(wsl,1)][14125ms] waiting...
2023-06-26 12:21:17.116 [info] [resolveAuthority(wsl,1)][15127ms] waiting...
2023-06-26 12:21:18.124 [info] [resolveAuthority(wsl,1)][16136ms] waiting...
2023-06-26 12:21:19.138 [info] [resolveAuthority(wsl,1)][17150ms] waiting...
2023-06-26 12:21:20.153 [info] [resolveAuthority(wsl,1)][18165ms] waiting...
2023-06-26 12:21:21.161 [info] [resolveAuthority(wsl,1)][19173ms] waiting...
2023-06-26 12:21:22.173 [info] [resolveAuthority(wsl,1)][20185ms] waiting...
2023-06-26 12:21:23.185 [info] [resolveAuthority(wsl,1)][21197ms] waiting...
2023-06-26 12:21:24.198 [info] [resolveAuthority(wsl,1)][22210ms] waiting...
2023-06-26 12:21:25.208 [info] [resolveAuthority(wsl,1)][23220ms] waiting...
2023-06-26 12:21:26.223 [info] [resolveAuthority(wsl,1)][24235ms] waiting...
2023-06-26 12:21:27.232 [info] [resolveAuthority(wsl,1)][25244ms] waiting...
2023-06-26 12:21:28.246 [info] [resolveAuthority(wsl,1)][26258ms] waiting...
2023-06-26 12:21:29.250 [info] [resolveAuthority(wsl,1)][27262ms] waiting...
2023-06-26 12:21:30.262 [info] [resolveAuthority(wsl,1)][28274ms] waiting...
2023-06-26 12:21:31.264 [info] [resolveAuthority(wsl,1)][29276ms] waiting...
2023-06-26 12:21:32.275 [info] [resolveAuthority(wsl,1)][30287ms] waiting...
2023-06-26 12:21:33.285 [info] [resolveAuthority(wsl,1)][31297ms] waiting...
2023-06-26 12:21:34.291 [info] [resolveAuthority(wsl,1)][32303ms] waiting...
2023-06-26 12:21:35.298 [info] [resolveAuthority(wsl,1)][33310ms] waiting...
2023-06-26 12:21:36.301 [info] [resolveAuthority(wsl,1)][34313ms] waiting...
2023-06-26 12:21:37.310 [info] [resolveAuthority(wsl,1)][35321ms] waiting...
2023-06-26 12:21:38.324 [info] [resolveAuthority(wsl,1)][36336ms] waiting...
2023-06-26 12:21:39.326 [info] [resolveAuthority(wsl,1)][37338ms] waiting...
2023-06-26 12:21:40.339 [info] [resolveAuthority(wsl,1)][38351ms] waiting...
2023-06-26 12:21:41.351 [info] [resolveAuthority(wsl,1)][39363ms] waiting...
2023-06-26 12:21:42.365 [info] [resolveAuthority(wsl,1)][40377ms] waiting...
2023-06-26 12:21:43.378 [info] [resolveAuthority(wsl,1)][41390ms] waiting...
2023-06-26 12:21:44.388 [info] [resolveAuthority(wsl,1)][42400ms] waiting...
2023-06-26 12:21:45.389 [info] [resolveAuthority(wsl,1)][43401ms] waiting...
2023-06-26 12:21:46.401 [info] [resolveAuthority(wsl,1)][44413ms] waiting...
2023-06-26 12:21:47.404 [info] [resolveAuthority(wsl,1)][45416ms] waiting...
2023-06-26 12:21:48.410 [info] [resolveAuthority(wsl,1)][46421ms] waiting...
2023-06-26 12:21:49.414 [info] [resolveAuthority(wsl,1)][47426ms] waiting...
2023-06-26 12:21:50.425 [info] [resolveAuthority(wsl,1)][48437ms] waiting...
2023-06-26 12:21:51.438 [info] [resolveAuthority(wsl,1)][49450ms] waiting...
2023-06-26 12:21:52.443 [info] [resolveAuthority(wsl,1)][50455ms] waiting...
2023-06-26 12:21:53.456 [info] [resolveAuthority(wsl,1)][51468ms] waiting...
2023-06-26 12:21:54.471 [info] [resolveAuthority(wsl,1)][52483ms] waiting...
2023-06-26 12:21:55.473 [info] [resolveAuthority(wsl,1)][53485ms] waiting...
2023-06-26 12:21:56.477 [info] [resolveAuthority(wsl,1)][54489ms] waiting...
2023-06-26 12:21:57.478 [info] [resolveAuthority(wsl,1)][55490ms] waiting...
2023-06-26 12:21:58.492 [info] [resolveAuthority(wsl,1)][56504ms] waiting...
2023-06-26 12:21:59.501 [info] [resolveAuthority(wsl,1)][57513ms] waiting...
2023-06-26 12:22:00.508 [info] [resolveAuthority(wsl,1)][58520ms] waiting...
2023-06-26 12:22:01.512 [info] [resolveAuthority(wsl,1)][59524ms] waiting...
2023-06-26 12:22:02.514 [info] [resolveAuthority(wsl,1)][60526ms] waiting...
2023-06-26 12:22:03.527 [info] [resolveAuthority(wsl,1)][61539ms] waiting...
2023-06-26 12:22:04.535 [info] [resolveAuthority(wsl,1)][62547ms] waiting...
2023-06-26 12:22:05.550 [info] [resolveAuthority(wsl,1)][63561ms] waiting...
2023-06-26 12:22:06.559 [info] [resolveAuthority(wsl,1)][64571ms] waiting...
2023-06-26 12:22:07.570 [info] [resolveAuthority(wsl,1)][65582ms] waiting...
2023-06-26 12:22:08.582 [info] [resolveAuthority(wsl,1)][66594ms] waiting...
2023-06-26 12:22:09.586 [info] [resolveAuthority(wsl,1)][67598ms] waiting...
2023-06-26 12:22:10.598 [info] [resolveAuthority(wsl,1)][68610ms] waiting...
2023-06-26 12:22:11.607 [info] [resolveAuthority(wsl,1)][69618ms] waiting...
2023-06-26 12:22:12.608 [info] [resolveAuthority(wsl,1)][70620ms] waiting...
2023-06-26 12:22:13.618 [info] [resolveAuthority(wsl,1)][71629ms] waiting...
2023-06-26 12:22:14.628 [info] [resolveAuthority(wsl,1)][72640ms] waiting...
2023-06-26 12:22:15.641 [info] [resolveAuthority(wsl,1)][73653ms] waiting...
2023-06-26 12:22:16.650 [info] [resolveAuthority(wsl,1)][74662ms] waiting...
2023-06-26 12:22:17.661 [info] [resolveAuthority(wsl,1)][75673ms] waiting...
2023-06-26 12:22:18.672 [info] [resolveAuthority(wsl,1)][76684ms] waiting...
2023-06-26 12:22:19.675 [info] [resolveAuthority(wsl,1)][77687ms] waiting...
2023-06-26 12:22:20.688 [info] [resolveAuthority(wsl,1)][78699ms] waiting...
2023-06-26 12:22:21.699 [info] [resolveAuthority(wsl,1)][79711ms] waiting...
2023-06-26 12:22:22.710 [info] [resolveAuthority(wsl,1)][80721ms] waiting...
2023-06-26 12:22:23.721 [info] [resolveAuthority(wsl,1)][81733ms] waiting...
2023-06-26 12:22:24.736 [info] [resolveAuthority(wsl,1)][82747ms] waiting...
2023-06-26 12:22:25.749 [info] [resolveAuthority(wsl,1)][83761ms] waiting...
2023-06-26 12:22:26.763 [info] [resolveAuthority(wsl,1)][84775ms] waiting...
2023-06-26 12:22:27.776 [info] [resolveAuthority(wsl,1)][85788ms] waiting...
2023-06-26 12:22:28.789 [info] [resolveAuthority(wsl,1)][86801ms] waiting...
2023-06-26 12:22:29.801 [info] [resolveAuthority(wsl,1)][87813ms] waiting...
2023-06-26 12:22:30.813 [info] [resolveAuthority(wsl,1)][88825ms] waiting...
2023-06-26 12:22:31.826 [info] [resolveAuthority(wsl,1)][89838ms] waiting...
2023-06-26 12:22:32.828 [info] [resolveAuthority(wsl,1)][90840ms] waiting...
2023-06-26 12:22:33.838 [info] [resolveAuthority(wsl,1)][91850ms] waiting...
2023-06-26 12:22:34.843 [info] [resolveAuthority(wsl,1)][92855ms] waiting...
2023-06-26 12:22:35.857 [info] [resolveAuthority(wsl,1)][93869ms] waiting...
2023-06-26 12:22:36.867 [info] [resolveAuthority(wsl,1)][94879ms] waiting...
2023-06-26 12:22:37.878 [info] [resolveAuthority(wsl,1)][95890ms] waiting...
2023-06-26 12:22:38.891 [info] [resolveAuthority(wsl,1)][96903ms] waiting...
2023-06-26 12:22:39.896 [info] [resolveAuthority(wsl,1)][97907ms] waiting...
2023-06-26 12:22:40.897 [info] [resolveAuthority(wsl,1)][98909ms] waiting...
2023-06-26 12:22:41.909 [info] [resolveAuthority(wsl,1)][99920ms] waiting...
2023-06-26 12:22:42.919 [info] [resolveAuthority(wsl,1)][100931ms] waiting...
2023-06-26 12:22:43.931 [info] [resolveAuthority(wsl,1)][101943ms] waiting...
2023-06-26 12:22:44.944 [info] [resolveAuthority(wsl,1)][102955ms] waiting...
2023-06-26 12:22:45.953 [info] [resolveAuthority(wsl,1)][103965ms] waiting...
2023-06-26 12:22:46.963 [info] [resolveAuthority(wsl,1)][104975ms] waiting...
2023-06-26 12:22:47.974 [info] [resolveAuthority(wsl,1)][105986ms] waiting...
2023-06-26 12:22:48.987 [info] [resolveAuthority(wsl,1)][106998ms] waiting...
2023-06-26 12:22:49.122 [error] [resolveAuthority(wsl,1)][107134ms] returned an error WSL not installed.
2023-06-26 12:22:49.252 [error] CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://wsl%2Bubuntu/home/phil'
    at e.$op.j (vscode-file://vscode-app/c:/Users/phillip.daniels/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:627:11401)
    at async e.$op.exists (vscode-file://vscode-app/c:/Users/phillip.daniels/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:627:13607)
    at async Promise.all (index 0)
    at async vscode-file://vscode-app/c:/Users/phillip.daniels/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1835:2490
2023-06-26 12:22:49.253 [info] Eager extensions activated
2023-06-26 12:22:49.323 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers, startup: false, activationEvent: 'onStartupFinished'
2023-06-26 12:22:49.366 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-06-26 12:22:49.449 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
Steps to Reproduce:

1. Open folder in wsl via code insiders

Does this issue occur when you try this locally?: Yes/No
Does this issue occur when you try this locally and all extensions are disabled?: I got this with every extension disabled as well

**Comment by phildaniels** [comment]
Restarting WSL did it (wsl --shutdown)

**Comment by pimise** [comment]
> Restarting WSL did it (wsl --shutdown)

That didn't work for me, no matter what I do WSL is no longer detected on VSCode Insiders

**Comment by phildaniels** [comment]
> > Restarting WSL did it (wsl --shutdown)
> 
> That didn't work for me, no matter what I do WSL is no longer detected on VSCode Insiders

I was wrong here, I thought restarting it fixed it when it didn't. If you want, I actually have a solution for version 0.80.1

1) Open the extension file, mine was in:
myuserprofile\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.80.1\dist\node\extension.js

2. Ctrl+H and replace "r.write(`WSL feature installed: ${i} (dll path)`)" with "return r.write(`WSL feature installed: ${i} (dll path)`), !!1". 

3. Save and restart code insiders. FYI you'll have to do this every time you get an update for the extension until they fix it.

**Comment by pimise** [comment]
> > > Restarting WSL did it (wsl --shutdown)
> > 
> > 
> > That didn't work for me, no matter what I do WSL is no longer detected on VSCode Insiders
> 
> I was wrong here, I thought restarting it fixed it when it didn't. If you want, I actually have a solution for version 0.80.1
> 
> 1. Open the extension file, mine was in:
>    `myuserprofile\.vscode-insiders\extensions\ms-vscode-remote.remote-wsl-0.80.1\dist\node\extension.js`
> 
> 2. Ctrl+H and replace `` r.write(`WSL feature installed: ${i} (dll path)`) `` with `` return r.write(`WSL feature installed: ${i} (dll path)`), !!1 ``
> 3. Save and restart code insiders. FYI you'll have to do this every time you get an update for the extension until they fix it.

Thanks, I actually just rolled back to 2 earlier versions of the WSL extension and it worked again so I didn't bother looking more into it
