### ISSUE TITLE
[Remote-SSH Bug]: Connect with SSH time out

### ISSUE THREAD

**Issue by windzhu0514** [microsoft/vscode-remote-release#8659]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

can't connect to remote.
![image](https://github.com/microsoft/vscode-remote-release/assets/5474294/9d56dd59-b37b-4162-8a48-047cfd49c2de)

### Expected Behavior

Can reconnect to remote host

### Steps To Reproduce

1. open vscode ,remote ssh to Ubuntu 22.04.2 LTS
2. open a golang project
3. install `Go Mod Explorer` or `GitLens — Git supercharged` extension 
4. move this two extension to `Secondary Side bar` ,and move the `Secondary Side bar` to right 
5. open one of these two extensions
6. disconnect the laptop from the network
7. wait vscode for prompt to reconnect or click one file in project,then will prompt to reconnect 
8. restoring the laptop's network
9. click to reconnect
10. Then this error occurs

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[10:50:00.386] Log Level: 2
[10:50:00.398] VS Code version: 1.79.2
[10:50:00.398] Remote-SSH version: remote-ssh@0.102.0
[10:50:00.399] win32 x64
[10:50:00.401] SSH Resolver called for "ssh-remote+pc-dev", attempt 1
[10:50:00.402] "remote.SSH.useLocalServer": false
[10:50:00.402] "remote.SSH.showLoginTerminal": false
[10:50:00.402] "remote.SSH.remotePlatform": {"pc-dev":"linux"}
[10:50:00.403] "remote.SSH.path": undefined
[10:50:00.403] "remote.SSH.configFile": undefined
[10:50:00.403] "remote.SSH.useFlock": true
[10:50:00.403] "remote.SSH.lockfilesInTmp": false
[10:50:00.403] "remote.SSH.localServerDownload": auto
[10:50:00.403] "remote.SSH.remoteServerListenOnSocket": false
[10:50:00.403] "remote.SSH.showLoginTerminal": false
[10:50:00.403] "remote.SSH.defaultExtensions": []
[10:50:00.404] "remote.SSH.loglevel": 2
[10:50:00.404] "remote.SSH.enableDynamicForwarding": true
[10:50:00.404] "remote.SSH.enableRemoteCommand": false
[10:50:00.404] "remote.SSH.serverPickPortsFromRange": {}
[10:50:00.404] "remote.SSH.serverInstallPath": {}
[10:50:00.408] SSH Resolver called for host: pc-dev
[10:50:00.408] Setting up SSH remote "pc-dev"
[10:50:00.411] Using commit id "695af097c7bd098fbf017ce3ac85e09bbc5dda06" and quality "stable" for server
[10:50:00.414] Install and start server if needed
[10:50:00.415] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[10:50:00.417] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[10:50:00.417] Checking ssh with "C:\Windows\ssh.exe -V"
[10:50:00.418] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[10:50:00.418] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[10:50:00.419] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[10:50:00.419] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[10:50:00.420] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[10:50:00.420] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[10:50:00.443] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[10:50:00.446] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 54363 "pc-dev" bash
[10:50:00.447] Terminal shell path: C:\Windows\System32\cmd.exe
[10:50:17.460] Resolver error: Error: Connecting with SSH timed out
	at m.Timeout (c:\Users\ljc01\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:584271)
	at Timeout._onTimeout (c:\Users\ljc01\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:680601)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[10:50:17.478] ------




[10:50:19.437] > 26279ae59748: running
> ]0;C:\Windows\System32\cmd.exeAcquiring lock on /home/ljc/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/vscode-remote-lock.ljc.695af097c7bd098fbf017ce3ac85e09bbc5dda06
> Found existing installation at /home/ljc/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06...
> Checking /home/ljc/.vscode-server/.695af097c7bd098fbf017ce3ac85e09bbc5dda06.log and /home/ljc/.vscode-server/.695af097c7bd098fbf017ce3ac85e09bbc5dda06.pid for a running server
> Looking for server with pid: 693977
> Found running server...
>  
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
>  
> Checking server status on port 43157 with wget
> 26279ae59748: start
> SSH_AUTH_SOCK====
> DISPLAY====
> webUiAccessToken====
> listeningOn==43157==
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> connectionToken==aa111111-a111-1111-a11a-a111aaa11111==
> 26279ae59748: end
[10:50:19.439] Got some output, clearing connection timeout

```

</p>
</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/8586

Please let me know if this is still happening in the latest Insiders release

**Comment by windzhu0514** [comment]
> #8586
> 
> Please let me know if this is still happening in the latest Insiders release

also happening in the latest Insiders release

```
Version: 1.80.0-insider (user setup)
Commit: 39efe30bfc8e196f5be2119479092bd9eb83e174
Date: 2023-06-30T14:32:07.986Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

**Comment by roblourens** [comment]
Will continue in that issue
