### ISSUE TITLE
[Remote-SSH Bug]: Failed to install the VS Code Server - ".../node" or ".../code-server-oss" don't exist

### ISSUE THREAD

**Issue by edward-shen** [microsoft/vscode-remote-release#8695]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### Expected Behavior

1. Connect to a new remote host `irys` using `Remote - SSH`.
2. Successfully installs server and allows client vscode to connect to remote vscode server

### Steps To Reproduce

1. On an Arch Linux installation, install `code`, `code-features`, and `code-marketplace`.
2.  Attempt to use the remote ssh extension to connect to a debian server with an ssh cert.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[16:49:23.714] Log Level: 1
[16:49:23.716] SSH Resolver called for "ssh-remote+irys", attempt 1
[16:49:23.717] "remote.SSH.useLocalServer": true
[16:49:23.717] "remote.SSH.path": undefined
[16:49:23.717] "remote.SSH.configFile": undefined
[16:49:23.717] "remote.SSH.useFlock": true
[16:49:23.717] "remote.SSH.lockfilesInTmp": false
[16:49:23.717] "remote.SSH.localServerDownload": off
[16:49:23.718] "remote.SSH.remoteServerListenOnSocket": false
[16:49:23.718] "remote.SSH.showLoginTerminal": false
[16:49:23.718] "remote.SSH.defaultExtensions": []
[16:49:23.718] "remote.SSH.loglevel": 1
[16:49:23.718] "remote.SSH.enableDynamicForwarding": true
[16:49:23.718] "remote.SSH.enableRemoteCommand": false
[16:49:23.718] "remote.SSH.serverPickPortsFromRange": {}
[16:49:23.719] "remote.SSH.serverInstallPath": {}
[16:49:23.721] VS Code version: 1.79.2
[16:49:23.721] Remote-SSH version: remote-ssh@0.103.2023062115
[16:49:23.721] linux x64
[16:49:23.722] SSH Resolver called for host: irys
[16:49:23.722] Setting up SSH remote "irys"
[16:49:23.725] Acquiring local install lock: /tmp/vscode-remote-ssh-2ed22716-install.lock
[16:49:23.725] Looking for existing server data file at /home/edward/.config/Code - OSS/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-2ed22716-695af097c7bd098fbf017ce3ac85e09bbc5dda06-0.103.2023062115/data.json
[16:49:23.725] Using commit id "695af097c7bd098fbf017ce3ac85e09bbc5dda06" and quality "stable" for server
[16:49:23.728] Install and start server if needed
[16:49:23.731] PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/home/edward/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/rustup/bin:/bin:/home/edward/.yarn/bin:/home/edward/bin
[16:49:23.731] Checking ssh with "ssh -V"
[16:49:23.739] > OpenSSH_9.3p1, OpenSSL 3.1.1 30 May 2023

[16:49:23.741] askpass server listening on /run/user/1000/vscode-ssh-askpass-b501c1452af50e4374683025a29aa2e2caae69e3.sock
[16:49:23.742] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-2e2b0cd94f3fad51133aef5d15bc664b698504d3.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","42673","-o","ConnectTimeout=15","irys"],"serverDataFolderName":".vscode-server-oss","dataFilePath":"/home/edward/.config/Code - OSS/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-2ed22716-695af097c7bd098fbf017ce3ac85e09bbc5dda06-0.103.2023062115/data.json"}
[16:49:23.742] Local server env: {"SHELL":"/usr/bin/zsh","DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/edward/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.103.2023062115/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/usr/lib/electron22/electron","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/edward/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.103.2023062115/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-b501c1452af50e4374683025a29aa2e2caae69e3.sock"}
[16:49:23.746] Spawned 2603713
[16:49:23.858] > local-server-1> Running ssh connection command: "-v -T -D 42673 -o ConnectTimeout=15 irys"
[16:49:23.863] > local-server-1> Spawned ssh, pid=2603721
[16:49:23.865] stderr> OpenSSH_9.3p1, OpenSSL 3.1.1 30 May 2023
[16:49:23.866] stderr> debug1: Reading configuration data /home/edward/.ssh/config
[16:49:23.866] stderr> debug1: /home/edward/.ssh/config line 29: Applying options for irys
[16:49:23.866] stderr> debug1: Reading configuration data /etc/ssh/ssh_config
[16:49:23.866] stderr> debug1: Connecting to 10.0.0.99 [10.0.0.99] port 2222.
[16:49:23.866] stderr> debug1: fd 3 clearing O_NONBLOCK
[16:49:23.867] stderr> debug1: Connection established.
[16:49:23.867] stderr> debug1: identity file /home/edward/.ssh/irys.starry.network type 3
[16:49:23.867] stderr> debug1: identity file /home/edward/.ssh/irys.starry.network-cert type -1
[16:49:23.867] stderr> debug1: Local version string SSH-2.0-OpenSSH_9.3
[16:49:23.872] stderr> debug1: Remote protocol version 2.0, remote software version OpenSSH_9.2p1 Debian-2
[16:49:23.872] stderr> debug1: compat_banner: match: OpenSSH_9.2p1 Debian-2 pat OpenSSH* compat 0x04000000
[16:49:23.872] stderr> debug1: Authenticating to 10.0.0.99:2222 as 'edward'
[16:49:23.872] stderr> debug1: load_hostkeys: fopen /home/edward/.ssh/known_hosts2: No such file or directory
[16:49:23.872] stderr> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
[16:49:23.872] stderr> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
[16:49:23.872] stderr> debug1: SSH2_MSG_KEXINIT sent
[16:49:23.873] stderr> debug1: SSH2_MSG_KEXINIT received
[16:49:23.873] stderr> debug1: kex: algorithm: sntrup761x25519-sha512@openssh.com
[16:49:23.873] stderr> debug1: kex: host key algorithm: ssh-ed25519
[16:49:23.873] stderr> debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
[16:49:23.873] stderr> debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
[16:49:23.923] stderr> debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
[16:49:23.930] stderr> debug1: SSH2_MSG_KEX_ECDH_REPLY received
[16:49:23.930] stderr> debug1: Server host key: ssh-ed25519 SHA256:qLW+wrJjPZwBoWN0GGsTbmLGcr74CickcTQ7YoZmTtY
[16:49:23.930] stderr> debug1: load_hostkeys: fopen /home/edward/.ssh/known_hosts2: No such file or directory
[16:49:23.930] stderr> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
[16:49:23.931] stderr> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
[16:49:23.931] stderr> debug1: checking without port identifier
[16:49:23.931] stderr> debug1: load_hostkeys: fopen /home/edward/.ssh/known_hosts2: No such file or directory
[16:49:23.931] stderr> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
[16:49:23.931] stderr> debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
[16:49:23.931] stderr> debug1: Host '10.0.0.99' is known and matches the ED25519 host key.
[16:49:23.931] stderr> debug1: Found key in /home/edward/.ssh/known_hosts:17
[16:49:23.931] stderr> debug1: found matching key w/out port
[16:49:23.931] stderr> debug1: check_host_key: hostkey not known or explicitly trusted: disabling UpdateHostkeys
[16:49:23.950] stderr> debug1: rekey out after 134217728 blocks
[16:49:23.950] stderr> debug1: SSH2_MSG_NEWKEYS sent
[16:49:23.950] stderr> debug1: expecting SSH2_MSG_NEWKEYS
[16:49:23.950] stderr> debug1: SSH2_MSG_NEWKEYS received
[16:49:23.950] stderr> debug1: rekey in after 134217728 blocks
[16:49:23.950] stderr> debug1: Will attempt key: /home/edward/.ssh/irys.starry.network ED25519 SHA256:31kAoF0KA+tWWYAXqLliKczHu8l7KzbIsFsJRUQaXLs explicit
[16:49:23.950] stderr> debug1: SSH2_MSG_EXT_INFO received
[16:49:23.951] stderr> debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com,ssh-dss,ssh-rsa,rsa-sha2-256,rsa-sha2-512>
[16:49:23.951] stderr> debug1: kex_input_ext_info: publickey-hostbound@openssh.com=<0>
[16:49:23.991] stderr> debug1: SSH2_MSG_SERVICE_ACCEPT received
[16:49:23.998] stderr> debug1: Authentications that can continue: publickey,password,keyboard-interactive
[16:49:23.998] stderr> debug1: Next authentication method: publickey
[16:49:23.998] stderr> debug1: Offering public key: /home/edward/.ssh/irys.starry.network ED25519 SHA256:31kAoF0KA+tWWYAXqLliKczHu8l7KzbIsFsJRUQaXLs explicit
[16:49:23.999] stderr> debug1: Server accepts key: /home/edward/.ssh/irys.starry.network ED25519 SHA256:31kAoF0KA+tWWYAXqLliKczHu8l7KzbIsFsJRUQaXLs explicit
[16:49:24.012] stderr> Authenticated to 10.0.0.99 ([10.0.0.99]:2222) using "publickey".
[16:49:24.012] stderr> debug1: Local connections to LOCALHOST:42673 forwarded to remote address socks:0
[16:49:24.012] stderr> debug1: Local forwarding listening on ::1 port 42673.
[16:49:24.012] stderr> debug1: channel 0: new port-listener [port listener] (inactive timeout: 0)
[16:49:24.012] stderr> debug1: Local forwarding listening on 127.0.0.1 port 42673.
[16:49:24.012] stderr> debug1: channel 1: new port-listener [port listener] (inactive timeout: 0)
[16:49:24.012] stderr> debug1: channel 2: new session [client-session] (inactive timeout: 0)
[16:49:24.013] stderr> debug1: Requesting no-more-sessions@openssh.com
[16:49:24.013] stderr> debug1: Entering interactive session.
[16:49:24.013] stderr> debug1: pledge: network
[16:49:24.105] stderr> debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
[16:49:24.105] stderr> debug1: Remote: /home/edward/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
[16:49:24.147] stderr> debug1: Remote: /home/edward/.ssh/authorized_keys:1: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
[16:49:24.147] stderr> debug1: pledge: network
[16:49:24.148] > Linux irys 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64
> 
> The programs included with the Debian GNU/Linux system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
> permitted by applicable law.
[16:49:24.149] > ready: e916685756a5
[16:49:24.150] > Linux 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08)
[16:49:24.150] Platform: linux
[16:49:24.151] > /usr/bin/zsh
[16:49:24.151] Shell: zsh
[16:49:24.151] Creating bash subshell inside "zsh"
[16:49:24.152] > bash version:  5.2.15(1)-release
[16:49:24.156] > e916685756a5: running
[16:49:24.165] > Acquiring lock on /home/edward/.vscode-server-oss/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/vscode-remote-lock.edward.695af097c7bd098fbf017ce3ac85e09bbc5dda06
[16:49:24.166] > Installing to /home/edward/.vscode-server-oss/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06...
[16:49:24.167] > e916685756a5%%1%%
[16:49:24.169] > Downloading with wget
[16:49:25.077] > Download complete
[16:49:25.079] > e916685756a5%%2%%
> tar --version:
[16:49:25.080] > tar (GNU tar) 1.34
> Copyright (C) 2021 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[16:49:25.680] stderr> mv: cannot move 'vscode-server-linux-x64/bin' to './bin': Directory not empty
[16:49:25.680] stderr> mv: cannot move 'vscode-server-linux-x64/extensions' to './extensions': Directory not empty
[16:49:25.681] stderr> mv: cannot move 'vscode-server-linux-x64/node_modules' to './node_modules': Directory not empty
[16:49:25.681] stderr> mv: cannot move 'vscode-server-linux-x64/out' to './out': Directory not empty
[16:49:25.681] > ERROR: /home/edward/.vscode-server-oss/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node or /home/edward/.vscode-server-oss/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/bin/code-server-oss don't exist
> e916685756a5: start
> exitCode==37==
> listeningOn====
> osReleaseId==debian==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult==missingFiles==
> didLocalDownload==0==
> downloadTime==911==
> installTime==600==
> extInstallTime====
> serverStartTime====
> e916685756a5: end
[16:49:25.681] Received install output: 
exitCode==37==
listeningOn====
osReleaseId==debian==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult==missingFiles==
didLocalDownload==0==
downloadTime==911==
installTime==600==
extInstallTime====
serverStartTime====

[16:49:25.682] Terminating local server
[16:49:25.684] Resolver error: Error: Failed to install the VS Code Server
	at f.ServerInstallError (/home/edward/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.103.2023062115/out/extension.js:1:585353)
	at d (/home/edward/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.103.2023062115/out/extension.js:1:579333)
	at t.handleInstallOutput (/home/edward/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.103.2023062115/out/extension.js:1:582216)
	at Object.e [as tryInstallWithLocalServer] (/home/edward/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.103.2023062115/out/extension.js:1:624990)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /home/edward/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.103.2023062115/out/extension.js:1:645035
	at async t.withShowDetailsEvent (/home/edward/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.103.2023062115/out/extension.js:1:648795)
	at async /home/edward/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.103.2023062115/out/extension.js:1:623462
	at async T (/home/edward/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.103.2023062115/out/extension.js:1:619968)
	at async t.resolveWithLocalServer (/home/edward/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.103.2023062115/out/extension.js:1:623077)
	at async t.resolve (/home/edward/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.103.2023062115/out/extension.js:1:646403)
	at async /home/edward/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.103.2023062115/out/extension.js:1:715610
[16:49:25.688] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"1","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"ExitCode","exitCodeLabel":""},"measures":{"resolveAttempts":1,"timing.totalResolveTime":1967,"timing.preSshTime":26,"timing.establishSshTime":414}}
[16:49:25.688] ------




[16:49:25.692] Local server exit: 15

```

</p>
</details>

### Anything else?

- Attempted on current stable `v0.102.0` and pre-release version `v0.103.2023062115`.
- Despite the error message, `/home/edward/.vscode-server-oss/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node` actually exists:
```
[edward@irys ~]$ /home/edward/.vscode-server-oss/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node --version
v16.17.1
```
- `code-server-oss` does not:
```
[edward@irys ~]$ /home/edward/.vscode-server-oss/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/bin/code-server-oss
zsh: no such file or directory: /home/edward/.vscode-server-oss/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/bin/code-server-oss
```
- Despite the error message, the extraction seems to have worked:
<details>
<summary><code>ls</code> output of the folders with a failed <code>mv</code> operation</summary>
<p>

```
[edward@irys 695af097c7bd098fbf017ce3ac85e09bbc5dda06]$ ls -la bin extensions node_modules out
bin:
total 57
drwxr-xr-x 4 edward edward   5 Jun 14 02:00 .
drwxr-xr-x 7 edward edward  12 Jul  9 16:55 ..
-rwxr-xr-x 1 edward edward 249 Jun 14 01:59 code-server
drwxr-xr-x 2 edward edward   3 Jun 14 02:00 helpers
drwxr-xr-x 2 edward edward   3 Jun 14 02:00 remote-cli

extensions:
total 313
drwxr-xr-x 33 edward edward 33 Jun 14 02:00 .
drwxr-xr-x  7 edward edward 12 Jul  9 16:55 ..
drwxr-xr-x  5 edward edward  7 Jun 14 02:00 configuration-editing
drwxr-xr-x  6 edward edward  9 Jun 14 02:00 css-language-features
drwxr-xr-x  5 edward edward  7 Jun 14 02:00 debug-auto-launch
drwxr-xr-x  4 edward edward  6 Jun 14 02:00 debug-server-ready
drwxr-xr-x  4 edward edward  7 Jun 14 02:00 emmet
drwxr-xr-x  4 edward edward  6 Jun 14 02:00 extension-editing
drwxr-xr-x  4 edward edward  7 Jun 14 02:00 git
drwxr-xr-x  6 edward edward  9 Jun 14 02:00 git-base
drwxr-xr-x  5 edward edward  9 Jun 14 02:00 github
drwxr-xr-x  5 edward edward  8 Jun 14 02:00 github-authentication
drwxr-xr-x  4 edward edward  7 Jun 14 02:00 grunt
drwxr-xr-x  4 edward edward  7 Jun 14 02:00 gulp
drwxr-xr-x  6 edward edward  9 Jun 14 02:00 html-language-features
drwxr-xr-x  4 edward edward  7 Jun 14 02:00 ipynb
drwxr-xr-x  4 edward edward  7 Jun 14 02:00 jake
drwxr-xr-x  5 edward edward  8 Jun 14 02:00 json-language-features
drwxr-xr-x  8 edward edward 13 Jun 14 02:00 markdown-language-features
drwxr-xr-x  6 edward edward 10 Jun 14 02:00 markdown-math
drwxr-xr-x  4 edward edward  8 Jun 14 02:00 media-preview
drwxr-xr-x  4 edward edward  7 Jun 14 02:00 merge-conflict
drwxr-xr-x  4 edward edward  7 Jun 14 02:00 microsoft-authentication
drwxr-xr-x  4 edward edward  8 Jun 14 02:00 ms-vscode.js-debug
drwxr-xr-x  4 edward edward 10 Jun 14 02:00 ms-vscode.js-debug-companion
drwxr-xr-x  4 edward edward 12 Jun 14 02:00 ms-vscode.vscode-js-profile-table
drwxr-xr-x  3 edward edward  3 Jun 14 02:00 node_modules
drwxr-xr-x  4 edward edward  7 Jun 14 02:00 npm
drwxr-xr-x  4 edward edward  7 Jun 14 02:00 php-language-features
drwxr-xr-x  4 edward edward  7 Jun 14 02:00 references-view
drwxr-xr-x  5 edward edward  8 Jun 14 02:00 search-result
drwxr-xr-x  4 edward edward  7 Jun 14 02:00 simple-browser
drwxr-xr-x  6 edward edward  9 Jun 14 02:00 typescript-language-features

node_modules:
total 1042
drwxr-xr-x 114 edward edward 114 Jun 14 02:00 .
drwxr-xr-x   7 edward edward  12 Jul  9 16:55 ..
drwxr-xr-x   3 edward edward   4 Jun 14 02:00 agent-base
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 ansi-regex
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 aproba
drwxr-xr-x   3 edward edward  11 Jun 14 02:00 are-we-there-yet
drwxr-xr-x   2 edward edward   6 Jun 14 02:00 base64-js
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 bindings
drwxr-xr-x   2 edward edward   6 Jun 14 02:00 bl
drwxr-xr-x   3 edward edward   6 Jun 14 02:00 braces
drwxr-xr-x   2 edward edward   6 Jun 14 02:00 buffer
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 buffer-crc32
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 chownr
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 code-point-at
drwxr-xr-x   2 edward edward   6 Jun 14 02:00 console-control-strings
drwxr-xr-x   2 edward edward   6 Jun 14 02:00 cookie
drwxr-xr-x   3 edward edward   7 Jun 14 02:00 core-util-is
drwxr-xr-x   4 edward edward   6 Jun 14 02:00 debug
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 decompress-response
drwxr-xr-x   3 edward edward   6 Jun 14 02:00 deep-extend
drwxr-xr-x   2 edward edward   7 Jun 14 02:00 delegates
drwxr-xr-x   3 edward edward   5 Jun 14 02:00 detect-libc
drwxr-xr-x   3 edward edward   7 Jun 14 02:00 emoji-regex
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 end-of-stream
drwxr-xr-x   3 edward edward   6 Jun 14 02:00 es6-promise
drwxr-xr-x   3 edward edward   4 Jun 14 02:00 es6-promisify
drwxr-xr-x   2 edward edward   6 Jun 14 02:00 expand-template
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 fd-slicer
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 file-uri-to-path
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 fill-range
drwxr-xr-x   2 edward edward   6 Jun 14 02:00 fs-constants
drwxr-xr-x   2 edward edward  19 Jun 14 02:00 gauge
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 github-from-package
drwxr-xr-x   2 edward edward   8 Jun 14 02:00 graceful-fs
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 has-unicode
drwxr-xr-x   3 edward edward   5 Jun 14 02:00 http-proxy-agent
drwxr-xr-x   3 edward edward   5 Jun 14 02:00 https-proxy-agent
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 ieee754
drwxr-xr-x   2 edward edward   6 Jun 14 02:00 inherits
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 ini
drwxr-xr-x   3 edward edward   4 Jun 14 02:00 ip
drwxr-xr-x   2 edward edward   7 Jun 14 02:00 isarray
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 is-extglob
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 is-fullwidth-code-point
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 is-glob
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 is-number
drwxr-xr-x   3 edward edward   6 Jun 14 02:00 jschardet
drwxr-xr-x   4 edward edward   6 Jun 14 02:00 keytar
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 lru-cache
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 micromatch
drwxr-xr-x   7 edward edward   7 Jun 14 02:00 @microsoft
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 mimic-response
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 minimist
drwxr-xr-x   3 edward edward   6 Jun 14 02:00 mkdirp
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 mkdirp-classic
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 ms
drwxr-xr-x   2 edward edward   6 Jun 14 02:00 napi-build-utils
drwxr-xr-x   3 edward edward   7 Jun 14 02:00 native-watchdog
drwxr-xr-x   3 edward edward   7 Jun 14 02:00 node-abi
drwxr-xr-x   2 edward edward   8 Jun 14 02:00 node-gyp-build
drwxr-xr-x   4 edward edward   6 Jun 14 02:00 node-pty
drwxr-xr-x   4 edward edward   5 Jun 14 02:00 node-vsce-sign
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 npmlog
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 number-is-nan
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 object-assign
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 once
drwxr-xr-x   3 edward edward   3 Jun 14 02:00 @parcel
drwxr-xr-x   2 edward edward   6 Jun 14 02:00 pend
drwxr-xr-x   3 edward edward   6 Jun 14 02:00 picomatch
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 process-nextick-args
drwxr-xr-x   2 edward edward   6 Jun 14 02:00 proxy-from-env
drwxr-xr-x   2 edward edward   7 Jun 14 02:00 pump
drwxr-xr-x   3 edward edward  10 Jun 14 02:00 rc
drwxr-xr-x   3 edward edward  11 Jun 14 02:00 readable-stream
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 safe-buffer
drwxr-xr-x   7 edward edward  12 Jun 14 02:00 semver
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 set-blocking
drwxr-xr-x   2 edward edward   6 Jun 14 02:00 signal-exit
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 simple-concat
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 simple-get
drwxr-xr-x   3 edward edward   5 Jun 14 02:00 smart-buffer
drwxr-xr-x   3 edward edward   5 Jun 14 02:00 socks
drwxr-xr-x   3 edward edward   4 Jun 14 02:00 socks-proxy-agent
drwxr-xr-x   4 edward edward   6 Jun 14 02:00 string_decoder
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 string-width
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 strip-ansi
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 strip-json-comments
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 tar-fs
drwxr-xr-x   2 edward edward   9 Jun 14 02:00 tar-stream
drwxr-xr-x   4 edward edward   6 Jun 14 02:00 tas-client-umd
drwxr-xr-x   3 edward edward   3 Jun 14 02:00 @tootallnate
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 to-regex-range
drwxr-xr-x   3 edward edward   6 Jun 14 02:00 tunnel-agent
drwxr-xr-x   2 edward edward   6 Jun 14 02:00 util-deprecate
drwxr-xr-x   7 edward edward   7 Jun 14 02:00 @vscode
drwxr-xr-x   7 edward edward  13 Jun 14 02:00 vscode-encrypt
drwxr-xr-x   3 edward edward   7 Jun 14 02:00 vscode-oniguruma
drwxr-xr-x   3 edward edward   4 Jun 14 02:00 vscode-regexp-languagedetection
drwxr-xr-x   2 edward edward   7 Jun 14 02:00 vscode-regexpp
drwxr-xr-x   3 edward edward   6 Jun 14 02:00 vscode-textmate
drwxr-xr-x   4 edward edward   7 Jun 14 02:00 vsda
drwxr-xr-x   3 edward edward   6 Jun 14 02:00 wide-align
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 wrappy
drwxr-xr-x   4 edward edward   6 Jun 14 02:00 xterm
drwxr-xr-x   3 edward edward   5 Jun 14 02:00 xterm-addon-canvas
drwxr-xr-x   3 edward edward   5 Jun 14 02:00 xterm-addon-image
drwxr-xr-x   3 edward edward   5 Jun 14 02:00 xterm-addon-search
drwxr-xr-x   3 edward edward   4 Jun 14 02:00 xterm-addon-serialize
drwxr-xr-x   3 edward edward   5 Jun 14 02:00 xterm-addon-unicode11
drwxr-xr-x   3 edward edward   5 Jun 14 02:00 xterm-addon-webgl
drwxr-xr-x   3 edward edward   4 Jun 14 02:00 xterm-headless
drwxr-xr-x   2 edward edward   6 Jun 14 02:00 yallist
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 yauzl
drwxr-xr-x   2 edward edward   5 Jun 14 02:00 yazl

out:
total 154
drwxr-xr-x 3 edward edward     10 Jun 14 02:00 .
drwxr-xr-x 7 edward edward     12 Jul  9 16:55 ..
-rw-r--r-- 1 edward edward   1385 Jun 14 01:41 bootstrap-amd.js
-rw-r--r-- 1 edward edward   2875 Jun 14 01:41 bootstrap-fork.js
-rw-r--r-- 1 edward edward   2410 Jun 14 01:41 bootstrap.js
-rw-r--r-- 1 edward edward   1844 Jun 14 01:41 bootstrap-node.js
-rw-r--r-- 1 edward edward 111898 Jun 14 01:50 nls.metadata.json
-rw-r--r-- 1 edward edward  40164 Jun 14 01:41 server-cli.js
-rw-r--r-- 1 edward edward  44457 Jun 14 01:41 server-main.js
drwxr-xr-x 6 edward edward      7 Jun 14 02:00 vs
```

</p>
</details>

- Naively speaking, this sounds like there's accidental double-install step, where it successfully extracts the tar on the first install but fails to on the second install?
- This error occurs regardless if `~/.vscode-server-oss` exists.
- I can invoke `./bin/code-server --accept-server-license-terms --log trace --extensions-dir /home/edward/.vscode-server-oss/extensions` and it spins up a server, but `code` does not detect the instance and attempts to install it anyways.

**Comment by roblourens** [comment]
The Arch Linux vscode repo is distributing an OSS build of vscode- this doesn't support the remote extensions because they contain non-OSS components
