### ISSUE TITLE
[Remote-SSH Bug]: Cannot open remote linux server in vscode even though ssh works in terminal

### ISSUE THREAD

**Issue by namespace-Pt** [microsoft/vscode-remote-release#8705]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

I expect the vscode to successfully remote to the server, as it always does.

### Steps To Reproduce

1. added my new ssh (to a linux server) to the configuration
2. failed to remote to the server

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[13:15:58.843] Log Level: 2
[13:15:58.855] SSH Resolver called for "ssh-remote+base", attempt 1
[13:15:58.856] "remote.SSH.useLocalServer": false
[13:15:58.856] "remote.SSH.showLoginTerminal": true
[13:15:58.856] "remote.SSH.remotePlatform": {"node1":"linux","job":"linux","183.174.228.39":"linux","183.174.228.153":"linux","cc":"linux"}
[13:15:58.856] "remote.SSH.path": undefined
[13:15:58.856] "remote.SSH.configFile": undefined
[13:15:58.857] "remote.SSH.useFlock": true
[13:15:58.857] "remote.SSH.lockfilesInTmp": false
[13:15:58.857] "remote.SSH.localServerDownload": auto
[13:15:58.857] "remote.SSH.remoteServerListenOnSocket": false
[13:15:58.857] "remote.SSH.showLoginTerminal": true
[13:15:58.857] "remote.SSH.defaultExtensions": ["ms-python.python","ms-toolsai.jupyter"]
[13:15:58.857] "remote.SSH.loglevel": 2
[13:15:58.858] "remote.SSH.enableDynamicForwarding": true
[13:15:58.859] "remote.SSH.enableRemoteCommand": false
[13:15:58.859] "remote.SSH.serverPickPortsFromRange": {}
[13:15:58.859] "remote.SSH.serverInstallPath": {}
[13:15:58.864] VS Code version: 1.80.0
[13:15:58.864] Remote-SSH version: remote-ssh@0.102.0
[13:15:58.865] win32 x64
[13:15:58.866] SSH Resolver called for host: base
[13:15:58.866] Setting up SSH remote "base"
[13:15:58.870] Using commit id "660393deaaa6d1996740ff4880f1bad43768c814" and quality "stable" for server
[13:15:58.874] Install and start server if needed
[13:16:03.666] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[13:16:03.668] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[13:16:03.669] Checking ssh with "C:\Windows\ssh.exe -V"
[13:16:03.670] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[13:16:03.670] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[13:16:03.671] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[13:16:03.671] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[13:16:03.672] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[13:16:03.672] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[13:16:03.720] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[13:16:03.724] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 57801 base bash
[13:16:03.726] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[13:16:05.411] > 1de7a665182e: running
> ]0;C:\WINDOWS\System32\cmd.exe
[13:16:05.412] Got some output, clearing connection timeout
[13:16:05.427] > 1de7a665182e: running
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[13:16:05.453] > Acquiring lock on /home/ks_group/.vscode-server/bin/660393deaaa6d1996740ff4880f1bad43768c814/vscode-remote-lock.ks_group.660393deaaa6d1996740ff4880f1bad43768c814
[13:16:05.468] > Found existing installation at /home/ks_group/.vscode-server/bin/660393deaaa6d1996740ff4880f1bad43768c814...
> Checking /home/ks_group/.vscode-server/.660393deaaa6d1996740ff4880f1bad43768c814.log and /home/ks_group/.vscode-server/.660393deaaa6d1996740ff4880f1bad43768c814.pid for a running server
> Looking for server with pid: 2267638
[13:16:05.561] > Found running server...
> Installing extensions...
[13:16:05.766] > Installing extensions...
[13:16:05.826] > Extension 'ms-python.python' v2023.12.0 is already installed. Use '--force' option to update to latest version or provide '@<version>' to install a specific version, for example: 'ms-python.python@1.2.3'.
> Extension 'ms-toolsai.jupyter' v2023.6.1101941928 is already installed. Use '--force' option to update to latest version or provide '@<version>' to install a specific version, for example: 'ms-toolsai.jupyter@1.2.3'.
[13:16:05.872] >  
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
> 
> Server did not start successfully. Full server log at /home/ks_group/.vscode-server/.660393deaaa6d1996740ff4880f1bad43768
> 8c814.log >>>
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
> [05:11:15]
> 
> 
> 
> 
> [05:11:15] Installing extensions...
> [05:11:15] Extension host agent started.
> [05:11:15] Error occurred in server
> [05:11:15] Error: listen EADDRNOTAVAIL: address not available 127.0.0.1
>     at Server.setupListenHandle [as _listen2] (node:net:1415:21)
>     at listenInCluster (node:net:1480:12)
>     at doListen (node:net:1629:7)
>     at processTicksAndRejections (node:internal/process/task_queues:84:21) {
>   code: 'EADDRNOTAVAIL',
>   errno: -99,
>   syscall: 'listen',
>   address: '127.0.0.1'
> }
> [05:11:15] Extension 'ms-python.python' v2023.12.0 is already installed. Use '--force' option to update to latest version
> n or provide '@<version>' to install a specific version, for example: 'ms-python.python@1.2.3'.
> [05:11:15] Extension 'ms-toolsai.jupyter' v2023.6.1101941928 is already installed. Use '--force' option to update to late
> est version or provide '@<version>' to install a specific version, for example: 'ms-toolsai.jupyter@1.2.3'.
> <<< End of server log
> 1de7a665182e: start
> exitCode==32==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/12003==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime==288==
> serverStartTime====
> 1de7a665182e: end
[13:16:05.872] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/12003==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime==288==
serverStartTime====

[13:16:05.873] listen EADDRNOTAVAIL: address not available 127.0.0.1

[13:16:05.875] Resolver error: Error: listen EADDRNOTAVAIL: address not available 127.0.0.1

	at m.ServerInstallError (c:\Users\Pt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:584079)
	at h (c:\Users\Pt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:577155)
	at t.handleInstallOutput (c:\Users\Pt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:581135)
	at t.tryInstall (c:\Users\Pt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:681881)
	at async c:\Users\Pt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:644110
	at async t.withShowDetailsEvent (c:\Users\Pt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:647428)
	at async t.resolve (c:\Users\Pt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:645160)
	at async c:\Users\Pt\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:720916
[13:16:05.882] ------




[13:16:07.161] "install" terminal command done
[13:16:07.162] Install terminal quit with output: 

```

</p>
</details>

### Anything else?

I've searched through the internet and I found some references pointing out the error is because VPN usage. However I have disabled my VPN and nothing changed.

**Comment by kukuxiahuni** [comment]
I found that when I maximize the vscode window, it can solve the connection problem.
```
版本: 1.81.0-insider (user setup)
提交: f8782370c90ec98467dc3590bcfa2eeb1f218107
日期: 2023-07-11T14:28:05.103Z
电子: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by roblourens** [comment]
> listen EADDRNOTAVAIL: address not available 127.0.0.1

No clue why this would come up or why the window size would help. Does it help to set the setting `"remote.SSH.useLocalServer": true` (you have to set this directly in your settings.json file)

**Comment by namespace-Pt** [comment]
I have set it to both true and false but neither worked. I think maybe the error is related to the destination server.

**Comment by roblourens** [comment]
I think that something is preventing the vscode server from listening on the localhost address. I'm not sure why that would be the case, but there's probably an issue with the way your remote is configured somehow
