### ISSUE TITLE
[Remote-SSH Bug]: Connection times out on some folders but not others

### ISSUE THREAD

**Issue by aejjehint** [microsoft/vscode-remote-release#8707]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[11:49:55.507] Log Level: 2
[11:49:55.512] VS Code version: 1.80.0
[11:49:55.512] Remote-SSH version: remote-ssh@0.102.0
[11:49:55.513] win32 x64
[11:49:55.536] SSH Resolver called for "ssh-remote+shared", attempt 1
[11:49:55.537] "remote.SSH.useLocalServer": false
[11:49:55.537] "remote.SSH.showLoginTerminal": true
[11:49:55.537] "remote.SSH.remotePlatform": {"shared":"linux"}
[11:49:55.537] "remote.SSH.path": undefined
[11:49:55.537] "remote.SSH.configFile": undefined
[11:49:55.537] "remote.SSH.useFlock": true
[11:49:55.538] "remote.SSH.lockfilesInTmp": false
[11:49:55.538] "remote.SSH.localServerDownload": off
[11:49:55.538] "remote.SSH.remoteServerListenOnSocket": false
[11:49:55.538] "remote.SSH.showLoginTerminal": true
[11:49:55.538] "remote.SSH.defaultExtensions": []
[11:49:55.539] "remote.SSH.loglevel": 2
[11:49:55.541] "remote.SSH.enableDynamicForwarding": true
[11:49:55.541] "remote.SSH.enableRemoteCommand": false
[11:49:55.541] "remote.SSH.serverPickPortsFromRange": {}
[11:49:55.541] "remote.SSH.serverInstallPath": {}
[11:49:55.553] SSH Resolver called for host: shared
[11:49:55.553] Setting up SSH remote "shared"
[11:49:55.559] Using commit id "660393deaaa6d1996740ff4880f1bad43768c814" and quality "stable" for server
[11:49:55.564] Install and start server if needed
[11:49:55.568] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[11:49:55.572] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[11:49:55.572] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[11:49:55.574] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[11:49:55.574] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[11:49:55.576] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[11:49:55.576] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[11:49:55.577] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[11:49:55.578] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[11:49:55.662] > OpenSSH_for_Windows_8.6p1, 
[11:49:55.663] > LibreSSL 3.4.3

[11:49:55.672] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 63817 shared bash
[11:49:55.678] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[11:50:57.689] Resolver error: Error: Connecting with SSH timed out
	at m.Timeout (c:\Users\aejjeh\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:584271)
	at Timeout._onTimeout (c:\Users\aejjeh\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:680601)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[11:50:57.695] ------




[11:50:59.114] > *******************************************************
> Use of this device and the network are subject to
> security monitoring to protect against security
> vulnerabilities and to confirm Intel policy compliance.
> *******************************************************
> ]0;C:\WINDOWS\System32\cmd.exe*******************************************************
> Use of this device and the network are subject to
> security monitoring to protect against security
> vulnerabilities and to confirm Intel policy compliance.
> *******************************************************
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[11:50:59.114] Got some output, clearing connection timeout
[11:50:59.815] > stty: 'standard input': Inappropriate ioctl for device
[11:50:59.828] > 23822fd42f05: running
[11:50:59.850] > Acquiring lock on /nfs/site/home/aejjeh/.vscode-server/bin/660393deaaa6d1996740ff4880f1bad43768c814/vscode-remote-lock.aejjeh.660393deaaa6d1996740ff4880f1bad43768c814
> Found existing installation at /nfs/site/home/aejjeh/.vscode-server/bin/660393deaaa6d1996740ff4880f1bad43768c814...
> Checking /nfs/site/home/aejjeh/.vscode-server/.660393deaaa6d1996740ff4880f1bad43768c814.log and /nfs/site/home/aejjeh/.vscode-server/.660393deaaa6d1996740ff4880f1bad43768c814.pid for a running server
[11:50:59.860] > Looking for server with pid: 25317
> Found running server...
>  
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
>  
> Checking server status on port 33291 with wget
[11:50:59.885] > 23822fd42f05: start
> SSH_AUTH_SOCK====
> DISPLAY====
> webUiAccessToken====
> listeningOn==33291==
> osReleaseId==sles==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/11953417==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> connectionToken==1aaa1a11-11aa-1111-1111-11a11aaaa1aa==
> 23822fd42f05: end
[11:50:59.908] > 
```

</p>
</details>

### Anything else?

I am able to connect to the other folders on the same host/server without any problem. For some reason, when connecting to some folders it gives a connection timed out error. What is peculiar is that just as it is displaying the error message (could not establish connection), it dumps output that contains "Got some output, clearing connection timeout".

**Comment by ns-jzhan** [comment]
Second this. I had the same issue this morning. One workspace folder opened successfully. The other one is not working. Not sure what happened. There is no any updates in VS code or extension. 

I compared with "Remote - SSH" output logs between successful and failed ones. The failed log shows the failure happened on line: `Running script with connection command: ssh -T -D 50927 -o ConnectTimeout=30  <remote_host> bash`.

Followed debugging steps. Still doesn't work.

**Comment by ecker-deshaw** [comment]
I am seeing this as well. I started noticing this when my VS Code updated to 1.79.1 (on Windows 10) a few weeks back. There was exactly one folder that I could not open over SSH, and all others worked as expected. It happened that my directory was named `code`, like `/home/ecker/code` and I thought that _maybe_ there was something fishy with detection due to a binary also being called `code`, especially since after I renamed my directory to `code-something`, it worked. However, starting today, opening `code-something` results in `Could not establish connect to "<myservername>": Connecting with SSH timed out.` again.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-remote-release/issues/8586

**Comment by ecker-deshaw** [comment]
> #8586

Thanks for the reference - closing the secondary side bar resolved this for me.

**Comment by aejjehint** [comment]
Indeed, closing the secondary side bar resolved this for me as well!
