### ISSUE TITLE
[Remote-SSH Bug]: Downloaded server is incomplete

### ISSUE THREAD

**Issue by 50Wliu** [microsoft/vscode-remote-release#8708]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

The connection to complete.

### Steps To Reproduce

I am trying to connect to a Windows SSH workspace. This has recently started to fail with "Downloaded server is incomplete", and the local SCP upload also failing. See below for exact version details.

This is consistent across multiple Windows SSH remotes.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[10:26:40.872] Log Level: 2
[10:26:40.888] VS Code version: 1.81.0-insider
[10:26:40.888] Remote-SSH version: remote-ssh@0.102.0
[10:26:40.888] win32 x64
[10:26:40.890] SSH Resolver called for "ssh-remote+publics", attempt 1
[10:26:40.890] "remote.SSH.useLocalServer": false
[10:26:40.891] "remote.SSH.showLoginTerminal": false
[10:26:40.891] "remote.SSH.remotePlatform": {"wave_analysis":"windows","one_click":"windows","publics":"windows","prime":"windows"}
[10:26:40.891] "remote.SSH.path": undefined
[10:26:40.891] "remote.SSH.configFile": undefined
[10:26:40.891] "remote.SSH.useFlock": true
[10:26:40.891] "remote.SSH.lockfilesInTmp": false
[10:26:40.891] "remote.SSH.localServerDownload": auto
[10:26:40.892] "remote.SSH.remoteServerListenOnSocket": false
[10:26:40.892] "remote.SSH.showLoginTerminal": false
[10:26:40.892] "remote.SSH.defaultExtensions": []
[10:26:40.892] "remote.SSH.loglevel": 2
[10:26:40.892] "remote.SSH.enableDynamicForwarding": true
[10:26:40.892] "remote.SSH.enableRemoteCommand": false
[10:26:40.893] "remote.SSH.serverPickPortsFromRange": {}
[10:26:40.893] "remote.SSH.serverInstallPath": {}
[10:26:40.903] SSH Resolver called for host: publics
[10:26:40.903] Setting up SSH remote "publics"
[10:26:40.909] Using commit id "d568855b2a4ef75716cdaa9a52da5315f5100a5d" and quality "insider" for server
[10:26:40.915] Install and start server if needed
[10:26:40.920] Checking ssh with "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\ssh.exe -V"
[10:26:40.925] Got error from ssh: spawn C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\ssh.exe ENOENT
[10:26:40.925] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[10:26:40.928] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[10:26:40.928] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[10:26:40.930] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[10:26:40.931] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[10:26:40.933] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[10:26:40.934] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[10:26:40.935] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[10:26:40.935] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[10:26:40.999] > OpenSSH_for_Windows_9.2p1, LibreSSL 3.6.2

[10:26:41.006] Remote command length: 6230/8192 characters
[10:26:41.007] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 49506 publics powershell
[10:26:41.010] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:26:44.847] > Windows PowerShell
> Copyright (C) Microsoft Corporation. All rights reserved.Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows]0;C:\WINDOWS\System32\cmd.exe
[10:26:44.847] Got some output, clearing connection timeout
[10:26:45.181] > PS C:\Users\winstonliu> 
[10:26:45.204] > 
> PS C:\Users\winstonliu> $uuid="282949a5cb88"
[10:26:45.239] > PS C:\Users\winstonliu> "${uuid}: running"
> 282949a5cb88: running
> PS C:\Users\winstonliu> "282949a5cb88: pauseLog
[10:26:46.043] > 
[10:26:46.674] > Acquiring lock on C:\Users\winstonliu\.vscode-server-insiders\bin\d568855b2a4ef7
> 75716cdaa9a52da5315f5100a5d\vscode-remote-lock.d568855b2a4ef75716cdaa9a52da5315f5
> 5100a5d
[10:26:46.682] > 
> Looking for existing server in C:\Users\winstonliu\.vscode-server-insiders\bin\d
> d568855b2a4ef75716cdaa9a52da5315f5100a5d
[10:26:46.690] > 
> Downloading server x64
> 282949a5cb88%%1%%
[10:26:46.706] > 
[10:26:47.722] > Expanding server into C:\Users\winstonliu\AppData\Local\Temp\rjondc0s.qio
> 282949a5cb88%%2%%
[10:26:47.738] > 
[10:26:55.567] > Downloaded server is incomplete.
> Trigger local server download
> 282949a5cb88:trigger_server_download
> platform==windows==
> vscodeArch==x64==
> destFolder==C:\Users\winstonliu\.vscode-server-insiders\bin\==
> destFolder2==d568855b2a4ef75716cdaa9a52da5315f5100a5d==
> 282949a5cb88:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for C:\Users\winstonliu\.vscode-server-insiders\bin\d568855b2a4ef75716cd
> daa9a52da5315f5100a5d\vscode-scp-done.flag and vscode-server.zip to exist        
[10:26:55.568] Got request to download on client for {"platform":"windows","arch":"x64","destFolder":"C:\\Users\\winstonliu\\.vscode-server-insiders\\bin\\d568855b2a4ef75716cdaa9a52da5315f5100a5d"}
[10:26:55.568] Downloading VS Code server locally...
[10:26:55.588] > 
[10:26:56.672] Downloaded VS Code server to c:\Users\WINSTO~1\AppData\Local\Temp\eb7c10e3-e62b-4f42-8bb4-4c81fa49c77f
[10:26:56.674] Renamed VS Code server to c:\Users\WINSTO~1\AppData\Local\Temp\vscode_server_1689182816672\vscode-server.zip
[10:26:56.679] Checking ssh with "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\ssh.exe -V"
[10:26:56.681] Got error from ssh: spawn C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\ssh.exe ENOENT
[10:26:56.681] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[10:26:56.683] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[10:26:56.683] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[10:26:56.685] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[10:26:56.685] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[10:26:56.687] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[10:26:56.687] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[10:26:56.689] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[10:26:56.689] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[10:26:56.737] > OpenSSH_for_Windows_9.2p1, LibreSSL 3.6.2

[10:26:56.740] Expecting scp to be next to ssh at C:\WINDOWS\System32\OpenSSH\scp.exe
[10:26:56.741] Testing scp with "C:\WINDOWS\System32\OpenSSH\scp.exe"
[10:26:56.800] scp exited with code: 1
[10:26:56.800] Got stderr from scp: usage: scp [-346ABCOpqRrsTv] [-c cipher] [-D sftp_server_path] [-F ssh_config]
           [-i identity_file] [-J destination] [-l limit] [-o ssh_option]
           [-P port] [-S program] [-X sftp_option] source ... target
[10:26:56.801] Copying file to remote with "C:\WINDOWS\System32\OpenSSH\scp.exe" "vscode-server.zip" "vscode-scp-done.flag" publics:"C:\Users\winstonliu\.vscode-server-insiders\bin\d568855b2a4ef75716cdaa9a52da5315f5100a5d"
[10:26:56.802] Using cwd: file:///c%3A/Users/WINSTO~1/AppData/Local/Temp/vscode_server_1689182816672
[10:26:56.802] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:26:58.642] > vscode-server.zip                               0%    0     0.0KB/s   --:-- ETA]0;C:\WINDOWS\System32\cmd.exe
[10:26:59.257] > vscode-server.zip                             100%   48MB  78.0MB/s   00:00    
> 
[10:26:59.321] > vscode-scp-done.flag                          100%    9     1.0KB/s   00:00    
[10:27:00.611] "Copy server to host" terminal command done
[10:27:01.566] > Transfer complete
> Expanding server into C:\Users\winstonliu\AppData\Local\Temp\fidmpykp.ihq       
> 282949a5cb88%%2%%
[10:27:01.599] > 
[10:27:07.896] > Downloaded server is incomplete.
> Already attempted local download, failing
> 282949a5cb88: start
> exitCode==37==
> listeningOn====
> osReleaseId==windows==
> osVersion====
[10:27:07.902] > 
> arch==x64==
> platform==windows==
> unpackResult==missingFiles==
> didLocalDownload==True==
> downloadTime==1015==
> installTime==6322==
> extInstallTime====
> serverStartTime====
[10:27:07.922] > 
> 282949a5cb88: end
> Expanding server into C:\Users\winstonliu\AppData\Local\Temp\fqn32gzh.zzu       
> 282949a5cb88%%2%%
[10:27:07.923] Received install output: 
exitCode==37==
listeningOn====
osReleaseId==windows==
osVersion====
arch==x64==
platform==windows==
unpackResult==missingFiles==
didLocalDownload==True==
downloadTime==1015==
installTime==6322==
extInstallTime====
serverStartTime====

[10:27:07.925] Resolver error: Error: Failed to install the VS Code Server
	at m.ServerInstallError (c:\Users\winstonliu\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:584079)
	at f (c:\Users\winstonliu\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:578374)
	at t.handleInstallOutput (c:\Users\winstonliu\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:581161)
	at t.tryInstall (c:\Users\winstonliu\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:681881)
	at async c:\Users\winstonliu\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:644110
	at async t.withShowDetailsEvent (c:\Users\winstonliu\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:647428)
	at async t.resolve (c:\Users\winstonliu\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:645160)
	at async c:\Users\winstonliu\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:720916
[10:27:07.931] ------





```

</p>
</details>

### Anything else?

This started occurring with the 2023-07-11 VS Code Insiders release (I verified I was able to connect to the same workspace using an older Insiders release). I'm currently on
```
Version: 1.81.0-insider (user setup)
Commit: d568855b2a4ef75716cdaa9a52da5315f5100a5d
Date: 2023-07-12T11:44:41.446Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.25906
```

**Comment by 50Wliu** [comment]
Also, even after VS Code officially pops up the dialog saying it can't connect, I still see Remote-SSH continuously trying to download the server into TEMP and failing over and over with the same "Downloaded server is incomplete" message. Which means it'll eventually fill up the whole disk with incomplete server downloads until you kill the window.

**Comment by roblourens** [comment]
Thanks, the shape of the windows server did change in Insiders, I'm finding out whether the extension needs to adapt to this

**Comment by roblourens** [comment]
This should be fixed now, please let me know if now

**Comment by 50Wliu** [comment]
Confirmed. Thanks :)
