### ISSUE TITLE
Devcontainer failing to start on Dockerfile steps?

### ISSUE THREAD

**Issue by mindlessroman** [microsoft/vscode-remote-release#8714]
- VSCode Version: 1.80.1 (Universal)
- Local OS Version: Mac 13.4.1 
- Remote OS Version: 
- Remote Extension/Connection Type: Containers

Other VS Code version info:
```
Version: 1.80.1 (Universal)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:20:23.298Z (1 day ago)
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.5.0
```

- Logs:
```
[68 ms] Dev Containers 0.299.0 in VS Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771).
[67 ms] Start: Resolving Remote
[88 ms] Setting up container for folder or workspace: /Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT
[88 ms] Context: desktop-linux
[109 ms] Start: Check Docker is running
[109 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[182 ms] Server API version: 1.43
[183 ms] Start: Run: docker volume ls -q
[259 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT --filter label=vsch.quality=stable
[357 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT --filter label=devcontainer.config_file=/Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT/.devcontainer/devcontainer.json
[432 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT
[506 ms] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/REDACTED/.vscode/extensions/ms-vscode-remote.remote-containers-0.299.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT --id-label devcontainer.local_folder=/Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT --id-label devcontainer.config_file=/Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT/.devcontainer/devcontainer.json --mount-workspace-git-root true
[751 ms] @devcontainers/cli 0.46.0. Node.js v16.17.1. darwin 22.5.0 x64.
[751 ms] Start: Run: git rev-parse --show-cdup
[788 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT --filter label=devcontainer.config_file=/Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT/.devcontainer/devcontainer.json
[861 ms] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/REDACTED/.vscode/extensions/ms-vscode-remote.remote-containers-0.299.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/REDACTED/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-17e04051-1b6c-4a77-b3ad-fdd3ddc579fa1689274139061 --workspace-folder /Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT --id-label devcontainer.config_file=/Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[1119 ms] @devcontainers/cli 0.46.0. Node.js v16.17.1. darwin 22.5.0 x64.
[1119 ms] Start: Run: docker buildx version
[1413 ms] github.com/docker/buildx v0.11.0 687feca9e8dcd1534ac4c026bc4db5a49de0dd6e
[1413 ms] 
[1413 ms] Start: Resolving Remote
[1416 ms] Start: Run: git rev-parse --show-cdup
[1453 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT --filter label=devcontainer.config_file=/Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT/.devcontainer/devcontainer.json
[1518 ms] Start: Run: docker inspect --type image mcr.microsoft.com/vscode/devcontainers/dotnet:0-6.0-bullseye-slim
[1600 ms] local container features stored at: /Users/REDACTED/.vscode/extensions/ms-vscode-remote.remote-containers-0.299.0/dist/node_modules/vscode-dev-containers/container-features
[1601 ms] Start: Run: tar --no-same-owner -x -f -
[1615 ms] Resolving Feature dependencies for 'docker-from-docker'...
[1615 ms] * Processing feature: docker-from-docker
[1615 ms] (!) WARNING: Using the deprecated 'docker-from-docker' Feature. See https://github.com/devcontainers/features/tree/main/src/docker-from-docker#example-usage for the updated Feature.
[1698 ms] Start: Run: docker-credential-desktop get
[2340 ms] * Processing feature: ghcr.io/devcontainers/features/common-utils
[2696 ms] Resolving Feature dependencies for 'github-cli'...
[2696 ms] * Processing feature: github-cli
[2696 ms] (!) WARNING: Using the deprecated 'github-cli' Feature. See https://github.com/devcontainers/features/tree/main/src/github-cli#example-usage for the updated Feature.
[3004 ms] * Processing feature: ghcr.io/devcontainers/features/common-utils
[3335 ms] * Processing feature: ghcr.io/devcontainers/features/git
[3597 ms] Resolving Feature dependencies for 'azure-cli'...
[3597 ms] * Processing feature: azure-cli
[3597 ms] (!) WARNING: Using the deprecated 'azure-cli' Feature. See https://github.com/devcontainers/features/tree/main/src/azure-cli#example-usage for the updated Feature.
[3712 ms] * Processing feature: ghcr.io/devcontainers/features/common-utils
[4015 ms] Soft-dependency 'ghcr.io/devcontainers/features/common-utils' is not required.  Removing from installation order...
[4015 ms] Soft-dependency 'ghcr.io/devcontainers/features/git' is not required.  Removing from installation order...
[4015 ms] Soft-dependency 'ghcr.io/devcontainers/features/common-utils' is not required.  Removing from installation order...
[4015 ms] Soft-dependency 'ghcr.io/devcontainers/features/common-utils' is not required.  Removing from installation order...
[4016 ms] * Fetching feature: azure-cli_0_oci
[4200 ms] * Fetching feature: docker-outside-of-docker_1_oci
[4383 ms] * Fetching feature: github-cli_2_oci
[4589 ms] Start: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/7s/rl8w85qx345_955x0vl8y4gr0000gn/T/devcontainercli/container-features/0.46.0-1689274141516/Dockerfile-with-features -t vsc-WHATEVER-SUBPROJECT-b344d4eae81ff623705fc194e2a8f7d6e0d022b75570490f92b3a5a78fe11d6f --target dev_containers_target_stage --build-context dev_containers_feature_content_source=/var/folders/7s/rl8w85qx345_955x0vl8y4gr0000gn/T/devcontainercli/container-features/0.46.0-1689274141516 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT
[+] Building 0.7s (8/17)                                   docker:desktop-linux
[+] Building 0.8s (8/17)                                   docker:desktop-linux
 => [internal] load build definition from Dockerfile-with-features         0.0s
[+] Building 0.9s (8/17)                                   docker:desktop-linux
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 4.62kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               0.4s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531b  0.0s
[+] Building 1.1s (9/17)                                   docker:desktop-linux
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 4.62kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               0.4s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531b  0.0s
[+] Building 1.1s (9/17)                                   docker:desktop-linux
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 4.62kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               0.4s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531b  0.0s
 => [context dev_containers_feature_content_source] load .dockerignore     0.0s 
 => => transferring dev_containers_feature_content_source: 2B              0.0s 
 => [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/d  0.0s 
 => CACHED [dev_container_auto_added_stage_label 1/2] FROM mcr.microsoft.  0.0s 
 => [context dev_containers_feature_content_source] load from client       0.0s 
 => => transferring dev_containers_feature_content_source: 25.43kB         0.0s 
 => ERROR [dev_container_auto_added_stage_label 2/2] RUN apt-get update    0.5s
------
 > [dev_container_auto_added_stage_label 2/2] RUN apt-get update   && apt-get -y install --no-install-recommends apt-utils dialog iproute2 procps sudo   && apt-get -y install git wget zip unzip jq   && apt-get -y upgrade   && curl -sL https://deb.nodesource.com/setup_16.x | bash -   && apt install -y nodejs   && npm install -g jest-cli markdown-spellcheck markdownlint-cli   && apt-get autoremove -y   && apt-get clean -y   && rm -rf /var/lib/apt/lists/*:
0.255 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
0.296 Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
0.303 Get:3 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
0.313 Get:4 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
0.338 Err:1 http://deb.debian.org/debian bullseye InRelease
0.338   At least one invalid signature was encountered.
0.382 Err:2 http://deb.debian.org/debian-security bullseye-security InRelease
0.382   At least one invalid signature was encountered.
0.418 Err:3 https://dl.yarnpkg.com/debian stable InRelease
0.418   At least one invalid signature was encountered.
0.464 Err:4 http://deb.debian.org/debian bullseye-updates InRelease
0.464   At least one invalid signature was encountered.
0.470 Reading package lists...
0.481 W: GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.
0.481 E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.
0.481 W: GPG error: http://deb.debian.org/debian-security bullseye-security InRelease: At least one invalid signature was encountered.
0.481 E: The repository 'http://deb.debian.org/debian-security bullseye-security InRelease' is not signed.
0.481 W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: At least one invalid signature was encountered.
0.481 E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
0.481 W: GPG error: http://deb.debian.org/debian bullseye-updates InRelease: At least one invalid signature was encountered.
0.481 E: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed.
------
Dockerfile-with-features:8
--------------------
   7 |     
   8 | >>> RUN apt-get update \
   9 | >>>   #
  10 | >>>   # Configure apt and install common packages
  11 | >>>   && apt-get -y install --no-install-recommends apt-utils dialog iproute2 procps sudo \
  12 | >>>   #
  13 | >>>   # Verify wget, jq, unzip, git and process tools installed
  14 | >>>   && apt-get -y install git wget zip unzip jq \
  15 | >>>   #
  16 | >>>   # Upgrade existing packages
  17 | >>>   && apt-get -y upgrade \
  18 | >>>   #
  19 | >>>   # Install node
  20 | >>>   && curl -sL https://deb.nodesource.com/setup_16.x | bash - \
  21 | >>>   && apt install -y nodejs \
  22 | >>>   #
  23 | >>>   # Install jest-cli testing framework globally
  24 | >>>   && npm install -g jest-cli markdown-spellcheck markdownlint-cli \
  25 | >>>   #
  26 | >>>   # Clean up
  27 | >>>   && apt-get autoremove -y \
  28 | >>>   && apt-get clean -y \
  29 | >>>   && rm -rf /var/lib/apt/lists/*
  30 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get update   && apt-get -y install --no-install-recommends apt-utils dialog iproute2 procps sudo   && apt-get -y install git wget zip unzip jq   && apt-get -y upgrade   && curl -sL https://deb.nodesource.com/setup_16.x | bash -   && apt install -y nodejs   && npm install -g jest-cli markdown-spellcheck markdownlint-cli   && apt-get autoremove -y   && apt-get clean -y   && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
[6113 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/7s/rl8w85qx345_955x0vl8y4gr0000gn/T/devcontainercli/container-features/0.46.0-1689274141516/Dockerfile-with-features -t vsc-WHATEVER-SUBPROJECT-b344d4eae81ff623705fc194e2a8f7d6e0d022b75570490f92b3a5a78fe11d6f --target dev_containers_target_stage --build-context dev_containers_feature_content_source=/var/folders/7s/rl8w85qx345_955x0vl8y4gr0000gn/T/devcontainercli/container-features/0.46.0-1689274141516 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT
[6113 ms]     at Ute (/Users/REDACTED/.vscode/extensions/ms-vscode-remote.remote-containers-0.299.0/dist/spec-node/devContainersSpecCLI.js:2008:1698)
[6113 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[6114 ms]     at async fC (/Users/REDACTED/.vscode/extensions/ms-vscode-remote.remote-containers-0.299.0/dist/spec-node/devContainersSpecCLI.js:2007:1691)
[6114 ms]     at async n3 (/Users/REDACTED/.vscode/extensions/ms-vscode-remote.remote-containers-0.299.0/dist/spec-node/devContainersSpecCLI.js:2007:610)
[6114 ms]     at async rre (/Users/REDACTED/.vscode/extensions/ms-vscode-remote.remote-containers-0.299.0/dist/spec-node/devContainersSpecCLI.js:2024:3660)
[6114 ms]     at async Yf (/Users/REDACTED/.vscode/extensions/ms-vscode-remote.remote-containers-0.299.0/dist/spec-node/devContainersSpecCLI.js:2024:4775)
[6114 ms]     at async Dne (/Users/REDACTED/.vscode/extensions/ms-vscode-remote.remote-containers-0.299.0/dist/spec-node/devContainersSpecCLI.js:2156:12193)
[6114 ms]     at async Sne (/Users/REDACTED/.vscode/extensions/ms-vscode-remote.remote-containers-0.299.0/dist/spec-node/devContainersSpecCLI.js:2156:11934)
[6121 ms] Exit code 1
[6124 ms] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/REDACTED/.vscode/extensions/ms-vscode-remote.remote-containers-0.299.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/REDACTED/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-17e04051-1b6c-4a77-b3ad-fdd3ddc579fa1689274139061 --workspace-folder /Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT --id-label devcontainer.config_file=/Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/REDACTED/code/WHATEVER-PROJECT/WHATEVER-SUBPROJECT/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[6124 ms] Exit code 1
```

`devcontainer.json`:
```
{
  "name": "Whatever the name is",
  "build": {
    "dockerfile": "Dockerfile",
    "context": ".."
  },
  "runArgs": [
    "-v", "/var/run/docker.sock:/var/run/docker.sock"
  ],
  "settings": {
    "terminal.integrated.profiles.linux": {
      "bash": {
        "path": "/bin/bash"
      }
    },
    "workbench.iconTheme": "vscode-icons"
  },
	"remoteUser": "vscode",
	"features": {
		"docker-from-docker": "latest",
		"github-cli": "latest",
		"azure-cli": "latest",
	},
  "extensions": [
    "ms-dotnettools.csharp",
    "ms-azuretools.vscode-docker",
    "ms-vsliveshare.vsliveshare",
    "vscode-icons-team.vscode-icons",
    "editorconfig.editorconfig",
    "davidanson.vscode-markdownlint"
  ]
}
```

`.dockerfile`:
```docker
FROM mcr.microsoft.com/vscode/devcontainers/dotnet:0-6.0-bullseye-slim

# Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  #
  # Configure apt and install common packages
  && apt-get -y install --no-install-recommends apt-utils dialog iproute2 procps sudo \
  #
  # Verify wget, jq, unzip, git and process tools installed
  && apt-get -y install git wget zip unzip jq \
  #
  # Upgrade existing packages
  && apt-get -y upgrade \
  #
  # Install node
  && curl -sL https://deb.nodesource.com/setup_16.x | bash - \
  && apt install -y nodejs \
  #
  # Install jest-cli testing framework globally
  && npm install -g jest-cli markdown-spellcheck markdownlint-cli \
  #
  # Clean up
  && apt-get autoremove -y \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*

# Switch back to dialog for any ad-hoc use of apt-get
ENV DEBIAN_FRONTEND=

CMD ["bash"]
```

Steps to Reproduce / My Attempts to Troubleshoot:

1. Try `> Dev Containers: Rebuild And Reopen In Container` once I have my directory with a `devcontainer.json` detected inside.
2. Try same thing but ignore cache.
3. Try uninstalling and reinstalling VSCode, then restarting.
4. Restarting my computer in general.
5. Try rolling back Dev Containers extension version to 0.255.4 as suggested in Issue #8230.
6. It happened on an older version of docker (4.8.something) so I thought updating docker would help (4.21.1). 
7. I slimmed down the `Dockerfile` to to just run in the `apt-get update`.
8. Updated the feature syntax in the `devcontainer.json` to the new syntax.
9. Turned off the feature: buildkit in my docker engine ([suggested in this stackoverflow response](https://stackoverflow.com/questions/74903197/how-to-solve-the-problem-with-starting-devcontainer)
```
{
  "builder": {
    "gc": {
      "defaultKeepStorage": "20GB",
      "enabled": true
    }
  },
  "experimental": false,
  "features": {
    "buildkit": false
  }
}
```
and similarly, tried to adjust the `devcontainer.json` like [the referenced GH issue](https://github.com/microsoft/vscode-remote-release/issues/7958) suggested.

**Comment by bamurtaugh** [comment]
Thanks for opening. Just to clarify - did this dev container config work at one point, and it stopped working now? That's what it sounded like may have been the case based on the troubleshooting steps shared.

**Comment by mindlessroman** [comment]
Sorry! @bamurtaugh I meant to update sooner.

Context was that for a long time, I had been using an older container. I recently deleted it for some container "spring cleaning" and then was trying to rebuild the container based off my previous `.devcontainer` definition. 
 I eventually got this to work. I fixed this the other week so I'm possibly forgetting a detail or two, but I believe it was resolved with including this line:
 ```dockerfile
FROM mcr.microsoft.com/vscode/devcontainers/dotnet:0-6.0-bullseye-slim

# Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

# THIS LINE IS NEW 
RUN apt-get clean && apt-get update \
[...]
```

The `apt-get clean` seems to have saved the day!
