### ISSUE TITLE
Unable to find WSL on PATH

### ISSUE THREAD

**Issue by luketrenaman** [microsoft/vscode-remote-release#8729]
When running the "Rebuild and Reopen in Container" command, I encounter this error
![image](https://github.com/microsoft/vscode-remote-release/assets/46632227/cc4492f4-f704-4cac-b977-3dd07cca9034)

Extension Host logging shows this as the full trace
![image](https://github.com/microsoft/vscode-remote-release/assets/46632227/d2eb9503-eef4-4d11-8d49-166341457f3f)

This is what is shown by Dev Container: Show Container Log
![image](https://github.com/microsoft/vscode-remote-release/assets/46632227/4768b1c3-453f-4f1d-a56d-b82a270ca3c7)

For further context I am able to run the `wsl` command within Command Prompt, Powershell, VSCode's integrated terminal and WSL. I'm unsure why `wsl` would not be found if it is available otherwise. Particularly I am wondering if `C:\Users\ltrenaman\AppData\Local\Microsoft\WindowsApps` is not the correct way to expose this executable.

Dev Container extension version: v0.299.0
WSL extension version: v0.80.2
VS Code version: Code 1.80.1 (Universal) (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:20:23.298Z)
Windows OS version: 19045.2846
Remote OS version:  Ubuntu 22.04.2 LTS

**Comment by luketrenaman** [comment]
I was able to resolve this by adding `C:\Windows\System32` to my system path. There is a WSL executable at this location that has different behavior than the one at `C:\Users\{USERNAME}\AppData\Local\Microsoft\WindowsApps`.

**Comment by miguel-mi-silva** [comment]
Thanks for that. Unfortunately, had already tried that option but it didn't work for me. Keep having the same error even with `C:\Windows\System32` added to both user and system `Path`.

**Comment by miguel-mi-silva** [comment]
Any idea what may be causing this problem? Here's the log I get:
```
[error] Error: Exectuable 'wsl' not found on PATH 'C:\Windows\System32;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\miniforge3\Scripts;C:\Users\myusername\AppData\Local\Programs\Git\cmd;C:\Users\myusername\AppData\Roaming\Python\Scripts;C:\Windows\System32;C:\Users\myusername\AppData\Local\Programs\Microsoft VS Code\bin;'.
	at Co (c:\Users\myusername\.vscode\extensions\ms-vscode-remote.remote-containers-0.305.0\dist\extension\extension.js:106:741)
	at async c:\Users\myusername\.vscode\extensions\ms-vscode-remote.remote-containers-0.305.0\dist\extension\extension.js:126:1070
	at async he (c:\Users\myusername\.vscode\extensions\ms-vscode-remote.remote-containers-0.305.0\dist\extension\extension.js:125:1454)
	at async bd (c:\Users\myusername\.vscode\extensions\ms-vscode-remote.remote-containers-0.305.0\dist\extension\extension.js:123:4119)
	at async Jk (c:\Users\myusername\.vscode\extensions\ms-vscode-remote.remote-containers-0.305.0\dist\extension\extension.js:123:5702)
	at async oC (c:\Users\myusername\.vscode\extensions\ms-vscode-remote.remote-containers-0.305.0\dist\extension\extension.js:123:4874)
	at async nt (c:\Users\myusername\.vscode\extensions\ms-vscode-remote.remote-containers-0.305.0\dist\extension\extension.js:289:23805)
	at async c:\Users\myusername\.vscode\extensions\ms-vscode-remote.remote-containers-0.305.0\dist\extension\extension.js:360:14348
	at async a.h (c:\Users\myusername\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:77769) remote-containers.createDevContainer {"value":"ms-vscode-remote.remote-containers","_lower":"ms-vscode-remote.remote-containers"}
```

As can be seen in the error log, `C:\Windows\System32` (where the file `wsl.exe` is located) is indeed in `Path`, and calling `wsl` from the powershell works just fine.

**Comment by chrmarti** [comment]
I see it at `C:\Windows\system32\wsl.exe` too. Not sure why it would not be found when the log output show `C:\Windows\system32` is on the `PATH`.

**Comment by timofeymukha** [comment]
I have exactly the same problem.
