### ISSUE TITLE
Could not connect to remote with experimental execServer setting

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-remote-release#8758]
Testing #8750

I ran `kill server` while still connected, which tried to immediately reconnect, and I cancelled that operation
set `remote.SSH.experimental.useExecServer: true`
ran connect to host in current window
connection failed:

```
[15:16:02.352] Log Level: 2
[15:16:02.367] SSH Resolver called for "ssh-remote+20.3.232.14", attempt 1
[15:16:02.368] "remote.SSH.useLocalServer": false
[15:16:02.368] "remote.SSH.showLoginTerminal": false
[15:16:02.369] "remote.SSH.remotePlatform": {"20.64.234.143":"linux","20.3.232.14":"windows"}
[15:16:02.369] "remote.SSH.path": undefined
[15:16:02.369] "remote.SSH.configFile": undefined
[15:16:02.369] "remote.SSH.useFlock": true
[15:16:02.370] "remote.SSH.lockfilesInTmp": false
[15:16:02.370] "remote.SSH.localServerDownload": always
[15:16:02.370] "remote.SSH.remoteServerListenOnSocket": false
[15:16:02.371] "remote.SSH.showLoginTerminal": false
[15:16:02.371] "remote.SSH.defaultExtensions": []
[15:16:02.371] "remote.SSH.loglevel": 2
[15:16:02.372] "remote.SSH.enableDynamicForwarding": true
[15:16:02.372] "remote.SSH.enableRemoteCommand": false
[15:16:02.372] "remote.SSH.serverPickPortsFromRange": {}
[15:16:02.373] "remote.SSH.serverInstallPath": {}
[15:16:02.382] VS Code version: 1.81.0-insider
[15:16:02.382] Remote-SSH version: remote-ssh@0.105.2023072515
[15:16:02.382] win32 x64
[15:16:02.384] SSH Resolver called for host: 20.3.232.14
[15:16:02.385] Setting up SSH remote "20.3.232.14"
[15:16:02.391] Using commit id "fda972663af87b4d1dab87845e36c357738b44f9" and quality "insider" for server
[15:16:02.401] Install and start server if needed
[15:16:02.406] Checking ssh with "C:\Python311\Scripts\ssh.exe -V"
[15:16:02.410] Got error from ssh: spawn C:\Python311\Scripts\ssh.exe ENOENT
[15:16:02.410] Checking ssh with "C:\Python311\ssh.exe -V"
[15:16:02.412] Got error from ssh: spawn C:\Python311\ssh.exe ENOENT
[15:16:02.412] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[15:16:02.413] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[15:16:02.413] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[15:16:02.415] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[15:16:02.415] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[15:16:02.417] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[15:16:02.417] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[15:16:02.419] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[15:16:02.419] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[15:16:02.472] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[15:16:02.479] Remote command length: 4837/8192 characters
[15:16:02.479] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 55896 "20.3.232.14" powershell
[15:16:02.483] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:16:03.179] > aamunger@20.3.232.14's password:]0;C:\WINDOWS\System32\cmd.exe
[15:16:03.180] Got some output, clearing connection timeout
[15:16:03.182] Showing password prompt
[15:16:06.907] Got password response
[15:16:06.907] "install" wrote data to terminal: "***************"
[15:16:06.931] > 
[15:16:07.680] > Windows PowerShell
> Copyright (C) Microsoft Corporation. All rights reserved.Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows
[15:16:07.696] > PS C:\Users\aamunger> 
> PS C:\Users\aamunger> $uuid="589d18fb5bba"
> 
[15:16:07.728] > PS C:\Users\aamunger> 
[15:16:07.745] > "${uuid}: running"
> 589d18fb5bba: running
> PS C:\Users\aamunger> "589d18fb5bba: pauseLog"
> 589d18fb5bba: pauseLog
[15:16:08.513] > 589d18fb5bba: resumeLog
[15:16:08.522] > 
> PS C:\Users\aamunger> main
[15:16:08.538] > 
[15:16:08.912] > Looking for existing CLI in C:\Users\aamunger\.vscode-server-insiders
> Found installed CLI
[15:16:08.930] > 
> Starting cli: & 'C:\Users\aamunger\.vscode-server-insiders\code-insiders-fda9726
> 663af87b4d1dab87845e36c357738b44f9.exe' command-shell --on-port --require-token 4
> 4d5e325aa05c *> 'C:\Users\aamunger\AppData\Local\Temp\tmp6429.tmp'
[15:16:09.414] > Server failed to start. - Cannot bind argument to parameter 'Pattern' because it
> t is null.
> at main, <No file>: line 46
[15:16:09.428] > 
> at <ScriptBlock>, <No file>: line 1
[15:16:09.443] > 
[15:16:09.567] > 589d18fb5bba: start
> SSH_AUTH_SOCK====
> listeningOn====
> osReleaseId==windows==
> osVersion==10.0.22621==
> arch==x64==
> platform==windows==
> unpackResult====
> didLocalDownload==False==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==72==
[15:16:09.584] > 
> 589d18fb5bba: end
> 10784, watching 1168
[15:16:09.585] Received install output: 
SSH_AUTH_SOCK====
listeningOn====
osReleaseId==windows==
osVersion==10.0.22621==
arch==x64==
platform==windows==
unpackResult====
didLocalDownload==False==
downloadTime====
installTime====
extInstallTime====
serverStartTime==72==

[15:16:09.588] Failed to parse remote port from server output
[15:16:09.593] Resolver error: Error: 
	at m.Create (c:\Users\aamunger\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.105.2023072515\out\extension.js:2:617971)
	at t.handleInstallOutput (c:\Users\aamunger\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.105.2023072515\out\extension.js:2:616531)
	at t.tryInstall (c:\Users\aamunger\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.105.2023072515\out\extension.js:2:735903)
	at async c:\Users\aamunger\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.105.2023072515\out\extension.js:2:697001
	at async t.withShowDetailsEvent (c:\Users\aamunger\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.105.2023072515\out\extension.js:2:700067)
	at async A (c:\Users\aamunger\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.105.2023072515\out\extension.js:2:693996)
	at async t.resolve (c:\Users\aamunger\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.105.2023072515\out\extension.js:2:697623)
	at async c:\Users\aamunger\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.105.2023072515\out\extension.js:2:880114
[15:16:09.612] ------
```

**Comment by connor4312** [comment]
Can you share the output of running

```
& 'C:\Users\aamunger\.vscode-server-insiders\code-insiders-fda972663af87b4d1dab87845e36c357738b44f9.exe' command-shell --on-port --require-token 4d5e325aa05c
```

manually in powershell?

**Comment by amunger** [comment]
on the remote I assume:

PS C:\Users\aamunger> & 'C:\Users\aamunger\.vscode-server-insiders\code-insiders-fda972663af87b4d1dab87845e36c357738b44f9.exe' command-shell --on-port --require-token 4d5e325aa05c
Listening on 127.0.0.1:50922

**Comment by amunger** [comment]
happened on both Azure VMs that I created for the TPI. 100% of the time with `remote.SSH.experimental.useExecServer: true` and never when set to false.

**Comment by amunger** [comment]
steps to test on Windows Azure VM

1. Create an azure VM, pick windows and a resourceGroup that you own, everything else can be default
2. use the reset password tab in the Azure portal to create a user account to use (unless you already did this when creating)
3. using the "connect" tab in the Azure portal - configure JIT for port 3389 and request access
5. use remote desktop to log in (it might ask for an email, just use the username)
6. on the remote machine, open settings -> apps -> optional features -> Add an optional feature -> install openssh server
7. open "services" from the start menu, find openssh server, right click -> start
8. back in the "connect" tab in the Azure portal - configure JIT for port 22 and request access
10. you should now be able to connect with remote-ssh in vscode
