### ISSUE TITLE
connection stuck after taking too long to enter password for remote machine

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-remote-release#8762]
Testing #8750

it's been stuck here for 7 minutes

![image](https://github.com/microsoft/vscode-remote-release/assets/2019016/0bcefac7-60a5-4ffe-b677-084e3c2fad23)

**Comment by amunger** [comment]
retrying leads to connection cancelled error

```
10:51:46.385] Got stderr from scp: usage: scp [-346ABCpqrTv] [-c cipher] [-F ssh_config] [-i identity_file]
            [-J destination] [-l limit] [-o ssh_option] [-P port]
            [-S program] source ... target
[10:51:46.385] Copying file to remote with "C:\Windows\System32\OpenSSH\scp.exe" "vscode-server.zip" "vscode-server.zip.done" "4.246.58.61":"C:\Users\aamunger\.vscode-server-insiders\bin\/862fa13002d8018c328931ee1edccfd4ca76447d"
[10:51:46.386] Using cwd: file:///c%3A/Users/aamunger/AppData/Local/Temp/vscode_server_1690393906178
[10:51:46.386] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:51:47.169] > aamunger@4.246.58.61's password:]0;C:\WINDOWS\System32\cmd.exe
[10:51:47.169] Showing password prompt
[10:51:47.171] Password dialog canceled
[10:51:47.172] "install" terminal command canceled
[10:51:47.176] Resolver error: Error: Connecting was canceled
	at m.Canceled (c:\Users\aamunger\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.105.2023072617\out\extension.js:2:618167)
	at c:\Users\aamunger\.vscode-insiders\extensions\ms-vscode-remote.remote-ssh-0.105.2023072617\out\extension.js:2:734980
[10:51:47.186] ------
```

**Comment by connor4312** [comment]
I think this is probably an existing bug in the local download mode

**Comment by roblourens** [comment]
In the original case, I think that was just scp not waiting that long for the password. Maybe we could recover better from that but it's a pain. In the second one

> [10:51:47.169] Showing password prompt
> [10:51:47.171] Password dialog canceled
> [10:51:47.172] "install" terminal command canceled

Not clear to me what happened, did you see the password prompt popup in vscode? I assume you weren't holding down the escape key or something like that to dismiss it in 2ms

**Comment by amunger** [comment]
I thought I remember seeing a prompt, entering a password, then getting another prompt that quickly went away. Maybe I didn't capture enough of the logs.

My guess is that the cancelled error was a side effect from the original issue - as if it was still trying to connect on that other session so it couldn't properly establish a new one. It kept that way until I rebooted.

**Comment by roblourens** [comment]
Sorry for not following up. If you still see this, and with the execServer mode enabled (should be by default for you) then share the log again please
