### ISSUE TITLE
[Remote-SSH Bug]: `--file-uri` doesn't work with non ".code-workspace" files, ssh connection timed out

### ISSUE THREAD

**Issue by ge9** [microsoft/vscode-remote-release#8765]
### Is there an existing issue for this bug?

- [x] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

`--file-uri` works correctly with any type of files

### Steps To Reproduce

If I invoke Code.exe with `--file-uri vscode-remote://ssh-remote+remote_server/path/to/file`, it fails in ssh connection if the `file` is not `xxx.code-workspace`. 
No problems in `folder-uri`.  

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by roblourens** [comment]
> it fails in ssh connection

Can you be more specific?

**Comment by ge9** [comment]
The popup window says "Could not establish connection to "my_servername":Connecting with SSH timed out."
But VS Code **is** successful in ssh connection (because it writes log in remote server).
This is my local log.
```
[12:56:12.693] Log Level: 2
[12:56:12.746] VS Code version: 1.80.1
[12:56:12.746] Remote-SSH version: remote-ssh@0.102.0
[12:56:12.746] win32 x64
[12:56:12.748] SSH Resolver called for "ssh-remote+my_servername", attempt 1
[12:56:12.749] "remote.SSH.useLocalServer": false
[12:56:12.750] "remote.SSH.showLoginTerminal": false
[12:56:12.751] "remote.SSH.remotePlatform": {"my_servername":"macOS"}
[12:56:12.751] "remote.SSH.path": undefined
[12:56:12.751] "remote.SSH.configFile": undefined
[12:56:12.752] "remote.SSH.useFlock": true
[12:56:12.752] "remote.SSH.lockfilesInTmp": false
[12:56:12.753] "remote.SSH.localServerDownload": auto
[12:56:12.753] "remote.SSH.remoteServerListenOnSocket": false
[12:56:12.754] "remote.SSH.showLoginTerminal": false
[12:56:12.754] "remote.SSH.defaultExtensions": []
[12:56:12.754] "remote.SSH.loglevel": 2
[12:56:12.755] "remote.SSH.enableDynamicForwarding": true
[12:56:12.755] "remote.SSH.enableRemoteCommand": false
[12:56:12.758] "remote.SSH.serverPickPortsFromRange": {}
[12:56:12.758] "remote.SSH.serverInstallPath": {}
[12:56:12.773] SSH Resolver called for host: my_servername
[12:56:12.773] Setting up SSH remote "my_servername"
[12:56:12.779] Using commit id "74f6148eb9ea00507ec113ec51c489d6ffb4b771" and quality "stable" for server
[12:56:12.788] Install and start server if needed
[12:56:12.799] Checking ssh with "C:\Program Files\OpenSSH\ssh.exe -V"
[12:56:12.962] > OpenSSH_for_Windows_9.2p1, LibreSSL 3.7.2

[12:56:12.984] Running script with connection command: "C:\Program Files\OpenSSH\ssh.exe" -T -D 63918 my_servername bash
[12:56:12.989] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[12:56:45.007] Resolver error: Error: Connecting with SSH timed out
	at m.Timeout (c:\Users\my_username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:584271)
	at Timeout._onTimeout (c:\Users\my_username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:680601)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[12:56:45.059] ------




[12:56:47.392] > 2563753a97c9: running
> ]0;C:\WINDOWS\System32\cmd.exe
[12:56:47.393] Got some output, clearing connection timeout
[12:56:47.497] > Acquiring lock on /home/my_remote_username/.vscode-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/vscode-remote-lock.my_remote_username.74f6148eb9ea00507ec113ec51c489d6ffb4b771
> \ln /home/my_remote_username/.vscode-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/vscode-remote-lock.my_remote_username.74f6148eb9ea00507ec113ec51c489d6ffb4b771.target /home/my_remote_username/.vscode-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/vscode-remote-lock.my_remote_username.74f6148eb9ea00507ec113ec51c489d6ffb4b771
> Found existing installation at /home/my_remote_username/.vscode-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771...
> Checking /home/my_remote_username/.vscode-server/.74f6148eb9ea00507ec113ec51c489d6ffb4b771.log and /home/my_remote_username/.vscode-server/.74f6148eb9ea00507ec113ec51c489d6ffb4b771.pid for a running server
> Looking for server with pid: 73175
[12:56:47.524] > Running ssh connection command... /home/my_remote_username/.vscode-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all   &> "/home/my_remote_username/.vscode-server/.74f6148eb9ea00507ec113ec51c489d6ffb4b771.log" < /dev/null
> printenv:
>     SHELL=/bin/bash
>     SSH_CLIENT=(*hidden*) 63947 22
>     TMPDIR=/var/folders/zz/zyxvpxvq6csfxvn_n000d9kr003_cp/T/
>     USER=my_remote_username
>     SSH_AUTH_SOCK=/tmp/ssh-svoj5GQ3rB/agent.85079
>     VSCODE_AGENT_FOLDER=/home/my_remote_username/.vscode-server
>     PATH=/usr/bin:/bin:/usr/sbin:/sbin
>     PWD=(*hidden*)
>     HOME=/home/my_remote_username
>     SHLVL=2
>     LOGNAME=my_remote_username
>     SSH_CONNECTION=(*hidden*) 63947 (*hidden*) 22
>     _=/usr/bin/printenv
[12:56:47.543] > Removing old logfile at /home/my_remote_username/.vscode-server/.74f6148eb9ea00507ec113e
> ec51c489d6ffb4b771.log
> Spawned remote server: 85124
> Waiting for server log...
[12:56:47.653] > 
> Waiting for server log...
[12:56:47.699] > 
[12:56:50.195] > Waiting for server log...
[12:56:50.209] > 
[12:56:50.236] > Waiting for server log...
[12:56:50.253] > 
[12:56:50.297] >  
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-lice
> ense) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacyst
> tatement).
> *
> 
[12:56:50.323] > 
> 2563753a97c9: start
> SSH_AUTH_SOCK==/tmp/ssh-svoj5GQ3rB/agent.85079==
> DISPLAY====
> webUiAccessToken====
> listeningOn==50322==
> osReleaseId==Darwin==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/tmp==
> platform==macOS==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==3000==
> connectionToken==1111a1a1-a111-1aa1-aa11-11aa111aaa1a==
> 2563753a97c9: end
[12:56:50.334] > 
```
And this is remote log (`/home/my_remote_username/.vscode-server/.74f6148eb9ea00507ec113ec51c489d6ffb4b771.log`).
```
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Server bound to 127.0.0.1:50322 (IPv4)
Extension host agent listening on 50322

[12:56:49] 




[12:56:49] Extension host agent started.
[12:56:51] Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
Last EH closed, shutting down
[13:01:49] Last EH closed, shutting down
```

**Comment by ge9** [comment]
Judging from timestamps, the `ssh` command is called only after the timeout limit exceeded.

**Comment by ge9** [comment]
This bug happened in both Windows and Linux client, and both Mac and Linux server. (I didn't test other cases)

**Comment by ge9** [comment]
It's working right after some update (extension or VS Code itself) today, so I close this now.
