### ISSUE TITLE
[Remote-SSH Bug]: Keep asking for password

### ISSUE THREAD

**Issue by win5923** [microsoft/vscode-remote-release#8776]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

When I used VSCode SSH for connection today, it keeps asking me to re-enter the password. Below is the log:

Windows log always show waiting:
```
2023-07-31 11:15:50.477 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][171007ms] waiting...
2023-07-31 11:15:51.471 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][172001ms] waiting...
2023-07-31 11:15:52.478 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][173007ms] waiting...
2023-07-31 11:15:53.472 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][174002ms] waiting...
2023-07-31 11:15:54.479 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][175008ms] waiting...
2023-07-31 11:15:55.479 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][176008ms] waiting...
2023-07-31 11:15:56.480 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][177008ms] waiting...
2023-07-31 11:15:57.478 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][178007ms] waiting...
2023-07-31 11:15:58.479 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][179008ms] waiting...
2023-07-31 11:15:59.478 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][180008ms] waiting...
2023-07-31 11:16:00.477 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][181007ms] waiting...
2023-07-31 11:16:01.478 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][182008ms] waiting...
2023-07-31 11:16:02.478 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][183008ms] waiting...
2023-07-31 11:16:03.476 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][184006ms] waiting...
2023-07-31 11:16:04.475 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][185005ms] waiting...
2023-07-31 11:16:05.476 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][186006ms] waiting...
2023-07-31 11:16:06.480 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][187009ms] waiting...
2023-07-31 11:16:07.481 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][188010ms] waiting...
2023-07-31 11:16:08.479 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][189009ms] waiting...
2023-07-31 11:16:09.481 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][190010ms] waiting...
2023-07-31 11:16:10.475 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][191005ms] waiting...
2023-07-31 11:16:11.477 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][192007ms] waiting...
2023-07-31 11:16:12.475 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][193005ms] waiting...
2023-07-31 11:16:13.480 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][194010ms] waiting...
2023-07-31 11:16:14.478 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][195008ms] waiting...
2023-07-31 11:16:15.477 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][196007ms] waiting...
2023-07-31 11:16:16.472 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][197001ms] waiting...
2023-07-31 11:16:17.471 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][198001ms] waiting...
2023-07-31 11:16:18.473 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][199002ms] waiting...
```

I have already tried re-downloading `Remote-SSH`, `Remote-SSH: Kill VS Code Server on Host...`,both options of `Remote.SSH: Use Local Server` and `Remote.SSH: Use Flock`, but still cannot connect.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[11:23:02.726] Log Level: 2
[11:23:02.742] SSH Resolver called for "ssh-remote+ip", attempt 1
[11:23:02.742] "remote.SSH.useLocalServer": false
[11:23:02.742] "remote.SSH.showLoginTerminal": false
[11:23:02.742] "remote.SSH.remotePlatform": {}
[11:23:02.742] "remote.SSH.path": undefined
[11:23:02.742] "remote.SSH.configFile": undefined
[11:23:02.742] "remote.SSH.useFlock": true
[11:23:02.742] "remote.SSH.lockfilesInTmp": false
[11:23:02.743] "remote.SSH.localServerDownload": auto
[11:23:02.743] "remote.SSH.remoteServerListenOnSocket": true
[11:23:02.743] "remote.SSH.showLoginTerminal": false
[11:23:02.743] "remote.SSH.defaultExtensions": []
[11:23:02.743] "remote.SSH.loglevel": 2
[11:23:02.743] "remote.SSH.enableDynamicForwarding": true
[11:23:02.743] "remote.SSH.enableRemoteCommand": false
[11:23:02.744] "remote.SSH.serverPickPortsFromRange": {}
[11:23:02.744] "remote.SSH.serverInstallPath": {}
[11:23:02.746] VS Code version: 1.80.2
[11:23:02.746] Remote-SSH version: remote-ssh@0.102.0
[11:23:02.746] win32 x64
[11:23:02.748] SSH Resolver called for host: ip
[11:23:02.749] Setting up SSH remote "ip"
[11:23:02.755] Using commit id "2ccd690cbff1569e4a83d7c43d45101f817401dc" and quality "stable" for server
[11:23:02.759] Install and start server if needed
[11:23:04.217] Checking ssh with "C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe -V"
[11:23:04.224] Got error from ssh: spawn C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[11:23:04.225] Checking ssh with "C:\Program Files (x86)\VMware\VMware Player\bin\ssh.exe -V"
[11:23:04.228] Got error from ssh: spawn C:\Program Files (x86)\VMware\VMware Player\bin\ssh.exe ENOENT
[11:23:04.228] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[11:23:04.232] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[11:23:04.232] Checking ssh with "C:\Windows\ssh.exe -V"
[11:23:04.236] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[11:23:04.236] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[11:23:04.240] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[11:23:04.240] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[11:23:04.243] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[11:23:04.243] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[11:23:04.313] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[11:23:04.322] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 52415 "ip" bash
[11:23:04.325] Terminal shell path: C:\Windows\System32\cmd.exe
[11:23:04.626] > ]0;C:\Windows\System32\cmd.exe
[11:23:04.627] Got some output, clearing connection timeout
[11:23:04.671] > name@ip's password: 
[11:23:04.672] Showing password prompt
[11:23:06.700] Got password response
[11:23:06.700] "install" wrote data to terminal: "***********"
[11:23:06.721] > 
[11:23:07.252] > 04cbf592825b: running
[11:23:07.315] > Acquiring lock on /home/name/.vscode-server/bin/2ccd690cbff1569e4a83d7c43d4510
> 1f817401dc/vscode-remote-lock.name.2ccd690cbff1569e4a83d7c43d45101f817401dc   
[11:23:07.349] > Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFloc
> k setting
> 04cbf592825b: start
> exitCode==24==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 04cbf592825b: end
[11:23:07.350] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[11:23:07.351] Server installation process already in progress - waiting and retrying
[11:23:08.375] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 52415 "ip" bash
[11:23:08.380] Terminal shell path: C:\Windows\System32\cmd.exe
[11:23:08.607] > ]0;C:\Windows\System32\cmd.exe
[11:23:08.608] Got some output, clearing connection timeout
[11:23:08.687] >name@ip's password: 
[11:23:08.688] Showing password prompt
[11:23:08.829] "install" terminal command done
[11:23:08.829] Install terminal quit with output: 
[11:23:10.803] Got password response
[11:23:10.803] "install" wrote data to terminal: "***********"
[11:23:10.818] > 
[11:23:11.341] > 04cbf592825b: running
[11:23:11.414] > Acquiring lock on /home/name/.vscode-server/bin/2ccd690cbff1569e4a83d7c43d4510
> 1f817401dc/vscode-remote-lock.name.2ccd690cbff1569e4a83d7c43d45101f817401dc   
[11:23:11.426] > Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFloc
> k setting
> 04cbf592825b: start
> exitCode==24==
> listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 04cbf592825b: end
[11:23:11.427] Received install output: 
exitCode==24==
listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[11:23:11.427] Server installation process already in progress - waiting and retrying
[11:23:12.441] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 52415 "ip" bash
[11:23:12.443] Terminal shell path: C:\Windows\System32\cmd.exe
[11:23:12.693] > ]0;C:\Windows\System32\cmd.exe
[11:23:12.694] Got some output, clearing connection timeout
[11:23:12.747] > name@ip's password: 
[11:23:12.747] Showing password prompt
[11:23:12.877] "install" terminal command done
[11:23:12.878] Install terminal quit with output: 
```

</p>
</details>

**Comment by 2jiwon** [comment]
I am having this problem too. But my logs are little different.

(blocked the real IP to dummy IP in the contents)
```
[15:09:31.305] Log Level: 2
[15:09:31.312] SSH Resolver called for "ssh-remote+byappsold", attempt 1
[15:09:31.313] "remote.SSH.useLocalServer": false
[15:09:31.313] "remote.SSH.showLoginTerminal": false
[15:09:31.313] "remote.SSH.remotePlatform": {"byapps":"linux","byappsold":"linux"}
[15:09:31.313] "remote.SSH.path": undefined
[15:09:31.313] "remote.SSH.configFile": \home\jiwon\.ssh\vsc_config
[15:09:31.313] "remote.SSH.useFlock": true
[15:09:31.313] "remote.SSH.lockfilesInTmp": false
[15:09:31.313] "remote.SSH.localServerDownload": auto
[15:09:31.314] "remote.SSH.remoteServerListenOnSocket": false
[15:09:31.314] "remote.SSH.showLoginTerminal": false
[15:09:31.314] "remote.SSH.defaultExtensions": []
[15:09:31.315] "remote.SSH.loglevel": 2
[15:09:31.315] "remote.SSH.enableDynamicForwarding": true
[15:09:31.315] "remote.SSH.enableRemoteCommand": false
[15:09:31.315] "remote.SSH.serverPickPortsFromRange": {}
[15:09:31.315] "remote.SSH.serverInstallPath": {}
[15:09:31.319] VS Code version: 1.80.2
[15:09:31.319] Remote-SSH version: remote-ssh@0.105.2023072715
[15:09:31.319] win32 x64
[15:09:31.320] SSH Resolver called for host: byappsold
[15:09:31.320] Setting up SSH remote "byappsold"
[15:09:31.323] Using commit id "2ccd690cbff1569e4a83d7c43d45101f817401dc" and quality "stable" for server
[15:09:31.326] Install and start server if needed
[15:09:31.330] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[15:09:31.332] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[15:09:31.332] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[15:09:31.333] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[15:09:31.333] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[15:09:31.334] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[15:09:31.334] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[15:09:31.334] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[15:09:31.335] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[15:09:31.369] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[15:09:31.372] Using SSH config file "\home\jiwon\.ssh\vsc_config"
[15:09:31.372] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 50782 -F "\home\jiwon\.ssh\vsc_config" byappsold bash
[15:09:31.374] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:09:31.985] > ]0;C:\WINDOWS\System32\cmd.exe
[15:09:31.985] Got some output, clearing connection timeout
[15:09:32.026] > The authenticity of host '[byapps.co.kr]:2020 ([111.222.333.444]:2020)' can't be es
> tablished.
> ECDSA key fingerprint is SHA256:i1xI+FYzfn22Xe3yqshN9i3fcdd9hpQpVA3ms1/x/d0.    
> Are you sure you want to continue connecting (yes/no/[fingerprint])?
[15:09:32.026] Detected fingerprint confirmation message
[15:09:32.026] Showing fingerprint confirmation dialog
[15:09:32.828] Got fingerprint response: yes
[15:09:32.828] "install" wrote data to terminal: "yes"
[15:09:32.845] > y
[15:09:32.860] > Are you sure you want to continue connecting (yes/no/[fingerprint])? yes        
> Failed to add the host to the list of known hosts (C:\\Users\\ljw/.ssh/known_hos
> ts).
[15:09:32.876] > @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[15:09:32.890] > @         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> Permissions for '\\\\wsl.localhost\\Ubuntu-18.04\\home\\jiwon\\.ssh\\id_rsa' are
>  too open.
> It is required that your private key files are NOT accessible by others.        
> This private key will be ignored.
> Load key "\\\\wsl.localhost\\Ubuntu-18.04\\home\\jiwon\\.ssh\\id_rsa": bad permi
> ssions
> marutm1@byapps.co.kr's password:
[15:09:32.890] Showing password prompt
[15:09:41.962] Password dialog canceled
[15:09:41.963] "install" terminal command canceled
[15:09:41.965] Resolver error: Error: Connecting was canceled
	at m.Canceled (c:\Users\ljw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.105.2023072715\out\extension.js:2:618167)
	at c:\Users\ljw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.105.2023072715\out\extension.js:2:734980
[15:09:41.980] ------
```

In my WSL2 terminal, I am using this key file to connect ssh without password and it works totally fine.
I don't understand the logs said about the permission, it's not the key, it's VSCode. Because with the same key, terminal works fine. 

I already killed the vscode processes at the remote server and removed the `.vscode-server` directory, nothing worked.
Also, it worked fine before I upgrade WSL1 to WSL2. 
All I can guess is something bugs with WSL2 and VSCode environment.

**Comment by roblourens** [comment]
```
[11:23:11.414] > Acquiring lock on /home/name/.vscode-server/bin/2ccd690cbff1569e4a83d7c43d4510
> 1f817401dc/vscode-remote-lock.name.2ccd690cbff1569e4a83d7c43d45101f817401dc   
[11:23:11.426] > Installation already in progress...
> If you continue to see this message, you can try toggling the remote.SSH.useFloc
> k setting
```

does it work if you run the command F1>"Kill VS Code Server on Host" to delete the stale lock file, or if you toggle that setting?

**Comment by win5923** [comment]
I deleted the `.vscode-server` folder on the VM and reinstalled Remote SSH on the local side. Now, I can connect successfully, although I have to enter the password twice each time. However, the issue has been resolved. Thank you very much!
