### ISSUE TITLE
VScode Remote SSH error

### ISSUE THREAD

**Issue by chetansriram** [microsoft/vscode-remote-release#8784]
[19:04:11.251] Resolver error: Error: Connecting was canceled
	at m.Canceled (c:\Users\0156751\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:584341)
	at c:\Users\0156751\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:644022
	at async t.withShowDetailsEvent (c:\Users\0156751\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:647428)
	at async t.resolve (c:\Users\0156751\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:645160)
	at async c:\Users\0156751\.vscode\extensions\ms-vscode-remote.remote-ssh-0.102.0\out\extension.js:1:720916
[19:04:11.260] ------

**Comment by bamurtaugh** [comment]
Hi, please follow the guidance here / in the issue template to provide more info on your issue: https://code.visualstudio.com/docs/remote/troubleshooting#_reporting-issues. Thanks!
