### ISSUE TITLE
Fail to SSH in VScode

### ISSUE THREAD

**Issue by SU-Hongs** [microsoft/vscode-remote-release#8793]
Type: <b>Bug</b>

Hi,

I am using Macbook. I can SSH in terminal. But I cannot SSH in VScode (for the same server). I've check my firewall and it should be OK

VS Code version: Code 1.80.2 (Universal) (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T21:05:41.366Z)
OS version: Darwin x64 20.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 28a498ef-6611-481c-b1e5-82dc3235e3f0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-perl|cfg|1.19.0
doxdocgen|csc|1.4.0
opencv-intellisense|did|0.0.4
code-runner|for|0.12.0
copilot|Git|1.100.306
gc-excelviewer|Gra|4.2.57
todo-tree|Gru|0.0.226
language-cython|guy|0.0.7
vs-code-runner|Har|2.0.1
better-cpp-syntax|jef|1.17.2
vscode-csharp-snippets|jor|1.1.0
docomment|k--|1.0.0
unity-code-snippets|kle|2.1.0
rainbow-csv|mec|3.7.0
r|Mik|0.0.30
csharp|ms-|2.0.320
vscode-dotnet-runtime|ms-|1.6.0
python|ms-|2023.12.0
vscode-pylance|ms-|2023.8.10
jupyter|ms-|2023.6.1101941928
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.17
vscode-jupyter-cell-tags|ms-|0.1.8
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.299.0
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-wsl|ms-|0.80.2
cmake-tools|ms-|1.14.34
cpptools|ms-|1.16.3
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.4.1
cs-script|ole|2.2.1
sqlite-viewer|qwt|0.2.5
r|REd|2.8.1
perl|ric|2.6.1
cython|tcw|0.1.0
python|tht|0.2.3
unity-tools|Tob|1.2.12
cmake|twx|0.0.17
unity-debug|Uni|3.0.2
unity-snippets|Ycl|0.1.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
vsctsb:30748421
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by roblourens** [comment]
Please share the log from the Remote-SSH output channel

**Comment by SU-Hongs** [comment]
Here is the log. Thank you.

[10:09:17.729] Setting up SSH remote "rwcpu9.cse.ust.hk"
[10:09:17.733] Acquiring local install lock: /var/folders/f1/ptxl35314mj1csv1q3j0_9740000gn/T/vscode-remote-ssh-5a7f8ccd-install.lock
[10:09:17.735] Looking for existing server data file at /Users/suhong/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-5a7f8ccd-2ccd690cbff1569e4a83d7c43d45101f817401dc-0.102.0/data.json
[10:09:17.736] Using commit id "2ccd690cbff1569e4a83d7c43d45101f817401dc" and quality "stable" for server
[10:09:17.742] Install and start server if needed
[10:09:17.748] PATH: /Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Users/suhong/opt/anaconda3/bin:/Users/suhong/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/python3:/Library/Frameworks/Python.framework/Versions/3.9/bin/python3:/Library/TeX/texbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin
[10:09:17.748] Checking ssh with "ssh -V"
[10:09:17.764] > OpenSSH_8.1p1, LibreSSL 2.7.3

[10:09:17.772] askpass server listening on /var/folders/f1/ptxl35314mj1csv1q3j0_9740000gn/T/vscode-ssh-askpass-47f8bc2561cb04fbff62aba2a4b8b87ba2877374.sock
[10:09:17.773] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/f1/ptxl35314mj1csv1q3j0_9740000gn/T/vscode-ssh-askpass-d083183aba8ea935100860a5d8386f965832751a.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","59533","-o","ConnectTimeout=15","rwcpu9.cse.ust.hk"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/suhong/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-5a7f8ccd-2ccd690cbff1569e4a83d7c43d45101f817401dc-0.102.0/data.json"}
[10:09:17.773] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.5WQwdpIcGG/Listeners","SHELL":"/bin/bash","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/suhong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code-2.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/suhong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/f1/ptxl35314mj1csv1q3j0_9740000gn/T/vscode-ssh-askpass-47f8bc2561cb04fbff62aba2a4b8b87ba2877374.sock"}
[10:09:17.775] Spawned 11173
[10:09:17.927] > local-server-1> Running ssh connection command: "-v -T -D 59533 -o ConnectTimeout=15 rwcpu9.cse.ust.hk"
[10:09:17.928] > local-server-1> Spawned ssh, pid=11183
[10:09:17.933] stderr> OpenSSH_8.1p1, LibreSSL 2.7.3
[10:09:20.689] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:hN2vbYcGa9mois+OypoO2sR3RHO4E03TiNQ5ZJfSUWI
[10:09:21.164] Got askpass request: {"request":"Password:"}
[10:09:21.165] Showing password prompt
[10:09:21.166] Listening for interwindow password on /var/folders/f1/ptxl35314mj1csv1q3j0_9740000gn/T/vscode-ssh-askpass-91a32d6149f66be3b1a6c9e435c2b3b2d1370c4c.sock
[10:09:21.166] Writing password prompt to globalState
[10:09:24.946] Got password response
[10:09:24.946] Interactor gave response: *************
[10:09:24.947] Cleaning up other-window auth server
[10:09:25.205] stderr> Authenticated to rwcpu9.cse.ust.hk ([143.89.126.69]:22).
[10:09:25.350] > Warning: no access to tty (Bad file descriptor).
> Thus no job control in this shell.
[10:09:25.647] > ready: 4cf1c683a9be
[10:09:25.698] > Linux 3.10.0-1160.62.1.el7.x86_64 #1 SMP Tue Apr 5 16:57:59 UTC 2022
[10:09:25.699] Platform: linux
[10:09:25.747] > /bin/tcsh
[10:09:25.747] Shell: tcsh
[10:09:25.748] Creating bash subshell inside "tcsh"
[10:09:25.851] > bash version:  4.2.46(2)-release
[10:09:25.927] > 4cf1c683a9be: running
[10:09:25.936] > Creating the server install dir failed...
> 4cf1c683a9be: start
> exitCode==34==
> listeningOn====
> osReleaseId====
> arch====
> vscodeArch====
> bitness====
> tmpDir==/run/user/31885==
> platform====
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> 4cf1c683a9be: end
[10:09:25.937] Received install output: 
exitCode==34==
listeningOn====
osReleaseId====
arch====
vscodeArch====
bitness====
tmpDir==/run/user/31885==
platform====
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====

[10:09:25.939] Failed to parse remote port from server output
[10:09:25.939] Terminating local server
[10:09:25.940] stderr> mkdir: cannot create directory ‘/home/hsuag/.vscode-server/bin/2ccd690cbff1569e4a83d7c43d45101f817401dc’: Permission denied
[10:09:25.941] stderr> BASH_VERSION: Undefined variable.
[10:09:25.945] Resolver error: Error: 
	at m.Create (/Users/suhong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:584145)
	at t.handleInstallOutput (/Users/suhong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:582705)
	at Object.e [as tryInstallWithLocalServer] (/Users/suhong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:623656)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/suhong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:643708
	at async t.withShowDetailsEvent (/Users/suhong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:647428)
	at async /Users/suhong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:622128
	at async C (/Users/suhong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:618634)
	at async t.resolveWithLocalServer (/Users/suhong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:621743)
	at async t.resolve (/Users/suhong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:645036)
	at async /Users/suhong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:720916
[10:09:25.955] ------

**Comment by SU-Hongs** [comment]
This issue is resolved. It is not a problem from VScode but from the server instead. Thanks a lot.
