### ISSUE TITLE
[Remote-SSH Bug]: UNPROTECTED PRIVATE KEY FILE problem after updating WSL1 -> WSL2

### ISSUE THREAD

**Issue by 2jiwon** [microsoft/vscode-remote-release#8798]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

In teminal, it works totally fine.
I can connect to remote server using ssh without typing passwords.

### Steps To Reproduce

1. Windows10 WSL2 Ubuntu 18.04
2. Vscode - connect to host
3. the prompt for password shouln't be showed because I copied the public key files on the remote servers.

config file is like this.

```
Host myserver
HostName myserver.co.kr
User ljw
Port 2020
IdentityFile \\wsl.localhost\Ubuntu-18.04\home\jiwon\.ssh\id_rsa
```

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[15:09:31.305] Log Level: 2
[15:09:31.312] SSH Resolver called for "ssh-remote+myserver", attempt 1
[15:09:31.313] "remote.SSH.useLocalServer": false
[15:09:31.313] "remote.SSH.showLoginTerminal": false
[15:09:31.313] "remote.SSH.remotePlatform": {"myserver":"linux","myserver2":"linux"}
[15:09:31.313] "remote.SSH.path": undefined
[15:09:31.313] "remote.SSH.configFile": \home\jiwon\.ssh\vsc_config
[15:09:31.313] "remote.SSH.useFlock": true
[15:09:31.313] "remote.SSH.lockfilesInTmp": false
[15:09:31.313] "remote.SSH.localServerDownload": auto
[15:09:31.314] "remote.SSH.remoteServerListenOnSocket": false
[15:09:31.314] "remote.SSH.showLoginTerminal": false
[15:09:31.314] "remote.SSH.defaultExtensions": []
[15:09:31.315] "remote.SSH.loglevel": 2
[15:09:31.315] "remote.SSH.enableDynamicForwarding": true
[15:09:31.315] "remote.SSH.enableRemoteCommand": false
[15:09:31.315] "remote.SSH.serverPickPortsFromRange": {}
[15:09:31.315] "remote.SSH.serverInstallPath": {}
[15:09:31.319] VS Code version: 1.80.2
[15:09:31.319] Remote-SSH version: remote-ssh@0.105.2023072715
[15:09:31.319] win32 x64
[15:09:31.320] SSH Resolver called for host: myserver
[15:09:31.320] Setting up SSH remote "myserver"
[15:09:31.323] Using commit id "2ccd690cbff1569e4a83d7c43d45101f817401dc" and quality "stable" for server
[15:09:31.326] Install and start server if needed
[15:09:31.330] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[15:09:31.332] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[15:09:31.332] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[15:09:31.333] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[15:09:31.333] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[15:09:31.334] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[15:09:31.334] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[15:09:31.334] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[15:09:31.335] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[15:09:31.369] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[15:09:31.372] Using SSH config file "\home\jiwon\.ssh\vsc_config"
[15:09:31.372] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 50782 -F "\home\jiwon\.ssh\vsc_config" myserver bash
[15:09:31.374] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[15:09:31.985] > ]0;C:\WINDOWS\System32\cmd.exe
[15:09:31.985] Got some output, clearing connection timeout
[15:09:32.026] > The authenticity of host '[111.222.333.444]:2020 ([111.222.333.444]:2020)' can't be es
> tablished.
> ECDSA key fingerprint is SHA256:i1xI+FYzfn22Xe3yqshN9i3fcdd9hpQpVA3ms1/x/d0.    
> Are you sure you want to continue connecting (yes/no/[fingerprint])?
[15:09:32.026] Detected fingerprint confirmation message
[15:09:32.026] Showing fingerprint confirmation dialog
[15:09:32.828] Got fingerprint response: yes
[15:09:32.828] "install" wrote data to terminal: "yes"
[15:09:32.845] > y
[15:09:32.860] > Are you sure you want to continue connecting (yes/no/[fingerprint])? yes        
> Failed to add the host to the list of known hosts (C:\\Users\\ljw/.ssh/known_hos
> ts).
[15:09:32.876] > @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[15:09:32.890] > @         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> Permissions for '\\\\wsl.localhost\\Ubuntu-18.04\\home\\jiwon\\.ssh\\id_rsa' are
>  too open.
> It is required that your private key files are NOT accessible by others.        
> This private key will be ignored.
> Load key "\\\\wsl.localhost\\Ubuntu-18.04\\home\\jiwon\\.ssh\\id_rsa": bad permi
> ssions
> dummy@111.222.333.444's password:
[15:09:32.890] Showing password prompt
[15:09:41.962] Password dialog canceled
[15:09:41.963] "install" terminal command canceled
[15:09:41.965] Resolver error: Error: Connecting was canceled
	at m.Canceled (c:\Users\ljw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.105.2023072715\out\extension.js:2:618167)
	at c:\Users\ljw\.vscode\extensions\ms-vscode-remote.remote-ssh-0.105.2023072715\out\extension.js:2:734980
[15:09:41.980] ------
```

</p>
</details>

### Anything else?

I use this extension and public keys to connect remote servers without typing passwords.

It worked totally fine before updating WSL2

after updated WSL2, suddenly VSCode complains my public keys’ permissions are too open.

They have 0644 permission, and even if I changed it as 0600, it didn’t work either.

```bash
-rw-r--r--  1 jiwon jiwon   745 Jul 31 14:18 id_rsa.pub
```
ssh directory have 0700 permission.

```bash
drwx------  2 jiwon jiwon    4096 Aug  3 15:15 .ssh/
```
I don’t understand why it is keep saying its permission is too open.

**Comment by 2jiwon** [comment]
Okay, I finally found out what went wrong. It was all me, not an issue. Sorry. :smile:

**Comment by 2jiwon** [comment]
If anyone, by any chance, bumped into this problem in the future, just remember this. 
"VScode and the Remote SSH(OpenSSH) extensions are installed on Windows, not on WSL."    
This will resolve everything. :smile:
