### ISSUE TITLE
[Remote-SSH Bug]: The connection fails beause it appears to not recognize my PATH

### ISSUE THREAD

**Issue by jfmcdowell** [microsoft/vscode-remote-release#8844]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

N/A

### Expected Behavior

I expected that I would connect to my remote host.

I have an EC2 instance on AWS that I connect with via AWS SSM as outlined in this [blog](https://aws.amazon.com/blogs/architecture/field-notes-use-aws-cloud9-to-power-your-visual-studio-code-ide/). After updating to VSCode 1.81 and Remote-SSH v0.105.2023080715 pre-release, I am unable to connect receiving the following errors in the attached [logs.txt](https://github.com/microsoft/vscode-remote-release/files/12345868/logs.txt)

My [ssh_config](https://github.com/microsoft/vscode-remote-release/files/12345932/devbox_ssh_config.txt) is also attached as well as proof that it works locally. I have also attached the
[ssm-proxy.sh file](https://github.com/microsoft/vscode-remote-release/files/12345993/ssm-proxy.txt)

<img width="891" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/206422/16e02bc7-988f-4cf0-b46e-97f69a242f9b">

### Steps To Reproduce

1. In VSCode 1.81 commit [5c49794](https://github.com/microsoft/vscode/commit/6c3e3dba23e8fadc360aed75ce363ba185c49794) using Remote-SSH extension v0.105.2023080715 pre-release
2. With the attached config file `ssh_config` and `ssm-proxy`
3. Run Remote-SSH: Connect to Host devbox
4. See error in attached `logs.txt` file

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[10:19:25.613] Log Level: 2
[10:19:25.614] SSH Resolver called for "ssh-remote+devbox", attempt 1
[10:19:25.615] "remote.SSH.useLocalServer": false
[10:19:25.615] "remote.SSH.showLoginTerminal": true
[10:19:25.615] "remote.SSH.remotePlatform": {"devbox":"linux"}
[10:19:25.615] "remote.SSH.path": undefined
[10:19:25.615] "remote.SSH.configFile": undefined
[10:19:25.615] "remote.SSH.useFlock": true
[10:19:25.615] "remote.SSH.lockfilesInTmp": false
[10:19:25.615] "remote.SSH.localServerDownload": auto
[10:19:25.615] "remote.SSH.remoteServerListenOnSocket": true
[10:19:25.616] "remote.SSH.showLoginTerminal": true
[10:19:25.616] "remote.SSH.defaultExtensions": ["ms-python.python","ms-python.black-formatter","charliermarsh.ruff","bierner.emojisense","aaron-bond.better-comments","github.remotehub","johnpapa.vscode-peacock","kddejong.vscode-cfn-lint","github.vscode-pull-request-github","redhat.vscode-commons","visualstudioexptteam.vscodeintellicode","amazonwebservices.aws-toolkit-vscode","eamodio.gitlens","oderwat.indent-rainbow"]
[10:19:25.616] "remote.SSH.loglevel": 2
[10:19:25.616] "remote.SSH.enableDynamicForwarding": true
[10:19:25.616] "remote.SSH.enableRemoteCommand": false
[10:19:25.616] "remote.SSH.serverPickPortsFromRange": {}
[10:19:25.616] "remote.SSH.serverInstallPath": {}
[10:19:25.618] VS Code version: 1.81.1
[10:19:25.618] Remote-SSH version: remote-ssh@0.105.2023080715
[10:19:25.618] darwin arm64
[10:19:25.619] SSH Resolver called for host: devbox
[10:19:25.619] Setting up SSH remote "devbox"
[10:19:25.621] Using commit id "6c3e3dba23e8fadc360aed75ce363ba185c49794" and quality "stable" for server
[10:19:25.625] Install and start server if needed
[10:19:25.627] PATH: /usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Privileges.app/Contents/Resources:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
[10:19:25.627] Checking ssh with "ssh -V"
[10:19:25.638] > OpenSSH_9.0p1, LibreSSL 3.3.6

[10:19:25.639] Running script with connection command: ssh -T -D 63000 -o ConnectTimeout=60 devbox bash
[10:19:25.882] > /Users/engineer/.ssh/ssm-proxy.sh: line 16: aws: command not found
> /Users/engineer/.ssh/ssm-proxy.sh: line 19: [: ==: unary operator expected
> /Users/engineer/.ssh/ssm-proxy.sh: line 23: aws: command not found
[10:19:25.882] Got some output, clearing connection timeout
[10:19:30.890] > /Users/engineer/.ssh/ssm-proxy.sh: line 27: aws: command not found
> /Users/engineer/.ssh/ssm-proxy.sh: line 28: [: ==: unary operator expected
[10:19:35.908] > /Users/engineer/.ssh/ssm-proxy.sh: line 27: aws: command not found
> /Users/engineer/.ssh/ssm-proxy.sh: line 28: [: ==: unary operator expected
[10:19:40.918] > /Users/engineer/.ssh/ssm-proxy.sh: line 27: aws: command not found
> /Users/engineer/.ssh/ssm-proxy.sh: line 28: [: ==: unary operator expected
[10:19:45.921] > /Users/engineer/.ssh/ssm-proxy.sh: line 27: aws: command not found
> /Users/engineer/.ssh/ssm-proxy.sh: line 28: [: ==: unary operator expected
[10:19:50.936] > /Users/engineer/.ssh/ssm-proxy.sh: line 27: aws: command not found
> /Users/engineer/.ssh/ssm-proxy.sh: line 28: [: ==: unary operator expected
[10:19:55.958] > /Users/engineer/.ssh/ssm-proxy.sh: line 27: aws: command not found
> /Users/engineer/.ssh/ssm-proxy.sh: line 28: [: ==: unary operator expected
> kex_exchange_identification: Connection closed by remote host
> Connection closed by UNKNOWN port 65535
[10:19:56.229] "install" terminal command done
[10:19:56.230] Install terminal quit with output: Connection closed by UNKNOWN port 65535
[10:19:56.230] Received install output: Connection closed by UNKNOWN port 65535
[10:19:56.230] Failed to parse remote port from server output
[10:19:56.233] Resolver error: Error:
	at m.Create (/Users/engineer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.105.2023080715/out/extension.js:2:617971)
	at t.handleInstallOutput (/Users/engineer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.105.2023080715/out/extension.js:2:616531)
	at t.tryInstall (/Users/engineer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.105.2023080715/out/extension.js:2:735685)
	at async /Users/engineer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.105.2023080715/out/extension.js:2:696783
	at async t.withShowDetailsEvent (/Users/engineer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.105.2023080715/out/extension.js:2:699849)
	at async A (/Users/engineer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.105.2023080715/out/extension.js:2:693778)
	at async t.resolve (/Users/engineer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.105.2023080715/out/extension.js:2:697405)
	at async /Users/engineer/.vscode/extensions/ms-vscode-remote.remote-ssh-0.105.2023080715/out/extension.js:2:879896
[10:19:56.237] ------
```

</p>
</details>

### Anything else?

It seems that the extension is not picking up my local PATH

**Comment by roblourens** [comment]
How does that script get run? Something is wrong

> [10:19:25.882] > /Users/engineer/.ssh/ssm-proxy.sh: line 16: aws: command not found
> > /Users/engineer/.ssh/ssm-proxy.sh: line 19: [: ==: unary operator expected

**Comment by jfmcdowell** [comment]
I wanted to leave this breadcrumb for anyone who may be experiencing this issue. Make sure VSCode is using the AWS profile as defined in the proxy script. If there is a mismatch the proxyscript will error out.
