### ISSUE TITLE
[Remote-SSH Bug]: 

### ISSUE THREAD

**Issue by Ant0wan** [microsoft/vscode-remote-release#8845]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### Steps To Reproduce

1. Trying to connect to debian remote machine using ssh alias

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[10:01:20.868] Install and start server if needed
[10:01:25.296] PATH: /app/bin:/app/bin:/app/bin:/usr/bin:/home/antoine/.var/app/com.visualstudio.code/data/node_modules/bin
[10:01:25.297] Checking ssh with "ssh -V"
[10:01:25.311] > OpenSSH_9.3p1, OpenSSL 3.0.9 30 May 2023

[10:01:25.314] Running script with connection command: ssh -T -D 46043 -o ConnectTimeout=15 **** bash
[10:01:25.574] > [490 preload-host-spawn-strategy] Warning: waitpid override ignores groups
> free(): invalid pointer
[10:01:25.574] Got some output, clearing connection timeout
[10:01:25.656] > [490 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[10:01:25.915] "install" terminal command done
[10:01:25.916] Install terminal quit with output: [490 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[10:01:25.916] Received install output: [490 preload-host-spawn-strategy] Warning: waitpid override ignores groups
[10:01:25.916] Failed to parse remote port from server output
[10:01:25.918] Resolver error: Error: 
	at m.Create (/home/antoine/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:584145)
	at t.handleInstallOutput (/home/antoine/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:582705)
	at t.tryInstall (/home/antoine/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:681881)
	at async /home/antoine/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:644110
	at async t.withShowDetailsEvent (/home/antoine/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:647428)
	at async t.resolve (/home/antoine/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:645160)
	at async /home/antoine/.var/app/com.visualstudio.code/data/vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:720916
[10:01:25.920] ------

```

</p>
</details>

**Comment by Ant0wan** [comment]
Does someone has an idea how to fix this ?

**Comment by Ant0wan** [comment]
@roblourens

**Comment by roblourens** [comment]
`Bad owner or permissions on /home/antoine/.ssh/config`

This is from ssh, not vscode, check this
