### ISSUE TITLE
Cannot install tunnel service in WSL

### ISSUE THREAD

**Issue by selfagency** [microsoft/vscode-remote-release#8857]
I am attempting to turn on Remote Tunnel Access but, when I do, I receive the following error after about 30 seconds:

```
2023-08-18 08:51:51.771 [error] SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at o.G (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:84:7662)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async o.startTunnel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:84:6879)
```

When I try with every extension disabled except Remote Tunnels, I get:

```
2023-08-18 09:05:20.199 [info] status terminating(30452)
2023-08-18 09:05:20.200 [error] Canceled: Canceled
    at c.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:24:12553)
    at y.w (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:21:1902)
    at y.x (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:21:1972)
    at y.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:21:2188)
    at j.cancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:21:5690)
    at L.cancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:21:6100)
    at Object.cancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:24:12688)
    at o.G (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:84:7392)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:84:6909
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:24:14795
    at async o.startTunnel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:84:6879)
```

- VSCode Version: 1.81.1
- Local OS Version: Windows 10.0.19045 Build 19045
- Remote OS Version:  Ubuntu 22.04.3
- Remote Extension/Connection Type: WSL

- Logs: [vscodelogs.txt](https://github.com/microsoft/vscode-remote-release/files/12379544/vscodelogs.txt)

Steps to Reproduce:

1. CTRL-SHIFT-P
2. Remote Tunnels: Turn on remote tunnel access...
3. Install as a service

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by selfagency** [comment]
for some reason this worked after a system reboot

**Comment by bamurtaugh** [comment]
Thanks for the update. If you experience this again, please let us know!
