### ISSUE TITLE
Reconnecting more than one remote ssh connection

### ISSUE THREAD

**Issue by HappyBahman** [microsoft/vscode-remote-release#8903]
Type: <b>Bug</b>

When there is more than one ssh connection (e.g. working simultanously on two different projects on a host system), if for some reason the connections are broken, when trying to reconnect, VS will ask for ssh password on one window (which will then reconnect), but the other window will get stuck at 'reconnecting' status without asking for password so it can reconnect. 
Client system: MacOS ventura
Host system: Ubuntu 22.04

VS Code version: Code 1.81.1 (Universal) (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin arm64 22.6.0
Modes:
Remote OS version: Linux x64 6.2.0-26-generic
Remote OS version: Linux x64 6.2.0-26-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|--crash-reporter-id 1abd3a1e-97e6-4c06-9849-ab85645a5e6c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 130.63.92.250|
|OS|Linux x64 6.2.0-26-generic|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3691)|
|Memory (System)|15.49GB (8.32GB free)|
|VM|0%|

|Item|Value|
|---|---|
|OS|Linux x64 6.2.0-26-generic|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3691)|
|Memory (System)|15.49GB (8.32GB free)|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.102.0
remote-ssh-edit|ms-|0.86.0
remote-explorer|ms-|0.4.1
vscode-antlr4|mik|2.3.1
autopep8|ms-|2023.6.0
black-formatter|ms-|2023.4.1
python|ms-|2023.14.0
vscode-pylance|ms-|2023.8.40
java|red|1.21.0
intellicode-api-usage-examples|Vis|0.2.8
vscodeintellicode|Vis|1.2.30
vscode-gradle|vsc|3.12.7
vscode-java-debug|vsc|0.54.0
vscode-java-dependency|vsc|0.23.1
vscode-java-pack|vsc|0.25.13
vscode-java-test|vsc|0.39.1
vscode-maven|vsc|0.42.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
962ge761:30823813
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by HappyBahman** [comment]
Hi. Sorry it took me a while to reproduce the error, it seems like this doesn't always happen.
Here's the output from Remote SSH window (I replaced my IP with asterisks). I discarded the logs before 10:45 since it would make the log too long, please let me know if you need the full log:

``` 
[10:46:05.384] [Forwarding server 56069] Got connection 1
[10:46:05.531] [Forwarding server 56069] Got connection 2
[11:04:05.995] [Forwarding server 56069] Got connection 3
[11:04:05.996] ------




[11:04:05.996] SSH Resolver called for "ssh-remote+***.**.**.***", attempt 2, (Reconnection)
[11:04:05.999] SSH Resolver called for host: ***.**.**.***
[11:04:05.999] Setting up SSH remote "***.**.**.***"
[11:04:06.000] Acquiring local install lock: /var/folders/l0/_yf1bz515nn_08gh9dyll32m0000gn/T/vscode-remote-ssh-bc07b914-install.lock
[11:04:06.001] Looking for existing server data file at /Users/bahman/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-bc07b914-6c3e3dba23e8fadc360aed75ce363ba185c49794-0.102.0/data.json
[11:04:06.006] Found local server running: {"remoteListeningOn":{"port":36925},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/1001","platform":"linux","connectionToken":"11aa11aa-1111-11aa-aaa1-11a11aaaaa11","pid":29543,"ipcHandlePath":"/var/folders/l0/_yf1bz515nn_08gh9dyll32m0000gn/T/vscode-ssh-askpass-0e7ed3046ab712addf16af7d9f82deb8519fffff.sock","socksPort":56065,"startupTime":1693925161084}
[11:04:06.006] Running server is stale. Ignoring
[11:04:06.007] Using commit id "6c3e3dba23e8fadc360aed75ce363ba185c49794" and quality "stable" for server
[11:04:06.034] Install and start server if needed
[11:04:06.046] askpass server listening on /var/folders/l0/_yf1bz515nn_08gh9dyll32m0000gn/T/vscode-ssh-askpass-4f8cff33d3a3ebbf5286f02c6488fb08abd6d1be.sock
[11:04:06.046] Spawning local server with {"serverId":2,"ipcHandlePath":"/var/folders/l0/_yf1bz515nn_08gh9dyll32m0000gn/T/vscode-ssh-askpass-b037935a15c41c2217eba484d7bfd60d40e306a0.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","56430","-o","ConnectTimeout=15","***.**.**.***"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/bahman/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-bc07b914-6c3e3dba23e8fadc360aed75ce363ba185c49794-0.102.0/data.json"}
[11:04:06.046] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.5mXn4ERrow/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/bahman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/bahman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/l0/_yf1bz515nn_08gh9dyll32m0000gn/T/vscode-ssh-askpass-4f8cff33d3a3ebbf5286f02c6488fb08abd6d1be.sock"}
[11:04:06.048] Spawned 29649
[11:04:06.130] > local-server-2> Running ssh connection command: "-v -T -D 56430 -o ConnectTimeout=15 ***.**.**.***"
[11:04:06.131] > local-server-2> Spawned ssh, pid=29656
[11:04:06.134] stderr> OpenSSH_9.0p1, LibreSSL 3.3.6
[11:04:06.198] stderr> debug1: Server host key: ssh-ed25519 SHA256:YNfbWey8pSz0sQ8vYGPTloUpiIjvAvSTN0oP/sKToUc
[11:04:06.356] Got askpass request: {"request":"brouhani@***.**.**.***'s password:"}
[11:04:06.356] Showing password prompt
[11:04:06.356] Listening for interwindow password on /var/folders/l0/_yf1bz515nn_08gh9dyll32m0000gn/T/vscode-ssh-askpass-eb101d453ea9354734e69770d172a332027eb524.sock
[11:04:06.356] Writing password prompt to globalState
[11:04:10.720] > local-server-1> Timed out
[11:04:10.731] Local server exit: 0
[11:04:24.534] Server delay-shutdown request failed: connect ECONNREFUSED /var/folders/l0/_yf1bz515nn_08gh9dyll32m0000gn/T/vscode-ssh-askpass-b037935a15c41c2217eba484d7bfd60d40e306a0.sock
[11:04:24.534] > local-server-2> Timed out
[11:04:24.534] Local server exit: 0
[11:04:24.535] Received install output: local-server-2> Running ssh connection command: "-v -T -D 56430 -o ConnectTimeout=15 ***.**.**.***"
local-server-2> Spawned ssh, pid=29656
OpenSSH_9.0p1, LibreSSL 3.3.6
debug1: Server host key: ssh-ed25519 SHA256:YNfbWey8pSz0sQ8vYGPTloUpiIjvAvSTN0oP/sKToUc
local-server-2> Timed out

[11:04:24.535] Failed to parse remote port from server output
[11:04:24.536] Resolver error: Error: 
	at m.Create (/Users/bahman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:584145)
	at t.handleInstallOutput (/Users/bahman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:582705)
	at Object.e [as tryInstallWithLocalServer] (/Users/bahman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:623656)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/bahman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:643708
	at async t.withShowDetailsEvent (/Users/bahman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:647428)
	at async /Users/bahman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:622128
	at async C (/Users/bahman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:618634)
	at async t.resolveWithLocalServer (/Users/bahman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:621743)
	at async t.resolve (/Users/bahman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:645036)
	at async /Users/bahman/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:720916
[11:04:24.540] ------




[11:07:01.696] Got password response
[11:07:01.696] Interactor gave response: **********
[11:07:01.697] Cleaning up other-window auth server
```
