### ISSUE TITLE
[Remote-SSH Bug]: libstdc++.so.6 (cannot open shared object file: No such file or directory)

### ISSUE THREAD

**Issue by martin-flower** [microsoft/vscode-remote-release#8932]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Steps To Reproduce

Host machine mac intel *successfully* connects Visual Studio Code remote to VirtualBox running *Debian12 64bit* - remote debugging working in python.

Host machine *fails* to start remote Visual Studio Code Server on VirtualBox running *Raspberry Desktop (intel) 32 bit*.
_error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory_

I am totally new to this world, but maybe it is the case that the second scenario is not supported? I'm guessing that the 32 bit might be the problem. Is it worth me investigating and trying to get it to work by supplying the missing component(s) ?

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[14:11:18.110] Log Level: 2
[14:11:18.221] SSH Resolver called for "ssh-remote+192.168.178.84", attempt 1
[14:11:18.222] "remote.SSH.useLocalServer": true
[14:11:18.222] "remote.SSH.path": undefined
[14:11:18.237] "remote.SSH.configFile": undefined
[14:11:18.238] "remote.SSH.useFlock": true
[14:11:18.238] "remote.SSH.lockfilesInTmp": false
[14:11:18.238] "remote.SSH.localServerDownload": auto
[14:11:18.238] "remote.SSH.remoteServerListenOnSocket": false
[14:11:18.238] "remote.SSH.showLoginTerminal": true
[14:11:18.238] "remote.SSH.defaultExtensions": []
[14:11:18.239] "remote.SSH.loglevel": 2
[14:11:18.239] "remote.SSH.enableDynamicForwarding": true
[14:11:18.239] "remote.SSH.enableRemoteCommand": false
[14:11:18.239] "remote.SSH.serverPickPortsFromRange": {}
[14:11:18.239] "remote.SSH.serverInstallPath": {}
[14:11:18.250] VS Code version: 1.81.1
[14:11:18.250] Remote-SSH version: remote-ssh@0.102.0
[14:11:18.250] darwin x64
[14:11:18.274] SSH Resolver called for host: 192.168.178.84
[14:11:18.274] Setting up SSH remote "192.168.178.84"
[14:11:18.278] Acquiring local install lock: /var/folders/lv/hdbw9nk50k12tyt63y12c3mr0000gn/T/vscode-remote-ssh-d0372234-install.lock
[14:11:18.279] Looking for existing server data file at /Users/martin/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-d0372234-6c3e3dba23e8fadc360aed75ce363ba185c49794-0.102.0/data.json
[14:11:18.280] Using commit id "6c3e3dba23e8fadc360aed75ce363ba185c49794" and quality "stable" for server
[14:11:18.290] Install and start server if needed
[14:11:18.297] PATH: /Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin
[14:11:18.297] Checking ssh with "ssh -V"
[14:11:18.372] > OpenSSH_8.6p1, LibreSSL 3.3.6

[14:11:18.379] askpass server listening on /var/folders/lv/hdbw9nk50k12tyt63y12c3mr0000gn/T/vscode-ssh-askpass-5885320d3356fc17f090231f1e050d173105ec44.sock
[14:11:18.380] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/lv/hdbw9nk50k12tyt63y12c3mr0000gn/T/vscode-ssh-askpass-7de3b0f9404eee92d7e3d96530ef4eda39cee695.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","51033","-o","ConnectTimeout=15","192.168.178.84"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/martin/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-d0372234-6c3e3dba23e8fadc360aed75ce363ba185c49794-0.102.0/data.json"}
[14:11:18.381] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.q07OnG2kcy/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/lv/hdbw9nk50k12tyt63y12c3mr0000gn/T/vscode-ssh-askpass-5885320d3356fc17f090231f1e050d173105ec44.sock"}
[14:11:18.385] Spawned 8628
[14:11:18.833] > local-server-1> Running ssh connection command: "-v -T -D 51033 -o ConnectTimeout=15 192.168.178.84"
[14:11:18.843] > local-server-1> Spawned ssh, pid=8631
[14:11:18.851] stderr> OpenSSH_8.6p1, LibreSSL 3.3.6
[14:11:18.927] stderr> debug1: Server host key: ssh-ed25519 SHA256:ks81gudgJqrIUMHBJqaT4HMdaNldV2Utqj30FTVnms8
[14:11:18.994] stderr> Authenticated to 192.168.178.84 ([192.168.178.84]:22).
[14:11:19.288] > Linux raspberry 5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64
> 
> The programs included with the Debian GNU/Linux system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
> permitted by applicable law.
[14:11:19.307] > ready: 3125f91de9f5
[14:11:19.311] > Linux 5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09)
[14:11:19.311] Platform: linux
[14:11:19.316] > /bin/bash
[14:11:19.317] Shell: bash
[14:11:19.317] Creating bash subshell inside "bash"
[14:11:19.328] > bash version:  5.1.4(1)-release
[14:11:19.353] > 3125f91de9f5: running
[14:11:19.393] > Acquiring lock on /home/frukt/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/vscode-remote-lock.frukt.6c3e3dba23e8fadc360aed75ce363ba185c49794
[14:11:19.400] > Found existing installation at /home/frukt/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794...
> Checking /home/frukt/.vscode-server/.6c3e3dba23e8fadc360aed75ce363ba185c49794.log and /home/frukt/.vscode-server/.6c3e3dba23e8fadc360aed75ce363ba185c49794.pid for a running server
[14:11:19.402] > Looking for server with pid: 1916
[14:11:19.423] > Running ssh connection command... /home/frukt/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown --port=0 --telemetry-level all   &> "/home/frukt/.vscode-server/.6c3e3dba23e8fadc360aed75ce363ba185c49794.log" < /dev/null
> printenv:
[14:11:19.424] >     SHELL=/bin/bash
>     LANGUAGE=sv_SE.UTF-8
>     NO_AT_BRIDGE=1
>     PWD=/home/frukt
>     LOGNAME=frukt
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/home/frukt
>     LANG=sv_SE.UTF-8
>     VSCODE_AGENT_FOLDER=/home/frukt/.vscode-server
>     SSH_CONNECTION=192.168.178.82 51034 192.168.178.84 22
>     XDG_SESSION_CLASS=user
>     PIGPIO_ADDR=fe80::1%usb0
>     GPIOZERO_PIN_FACTORY=pigpio
>     USER=frukt
>     SHLVL=1
>     XDG_SESSION_ID=5
>     XDG_RUNTIME_DIR=/run/user/1000
>     SSH_CLIENT=192.168.178.82 51034 22
>     LC_ALL=sv_SE.UTF-8
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
>     TEXTDOMAIN=Linux-PAM
>     _=/usr/bin/printenv
[14:11:19.434] > Removing old logfile at /home/frukt/.vscode-server/.6c3e3dba23e8fadc360aed75ce363ba185c49794.log
[14:11:19.440] > Spawned remote server: 4149
[14:11:19.445] > Waiting for server log...
[14:11:19.483] > Waiting for server log...
[14:11:19.524] > Waiting for server log...
.. ..
[14:11:33.781] > Waiting for server log...
[14:11:33.823] > Waiting for server log...
[14:11:33.864] >  
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
>  
[14:11:33.881] > Server did not start successfully. Full server log at /home/frukt/.vscode-server/.6c3e3dba23e8fadc360aed75ce363ba185c49794.log >>>
[14:11:33.885] > /home/frukt/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
[14:11:33.886] > <<< End of server log
> 3125f91de9f5: start
> exitCode==32==
> listeningOn====
> osReleaseId==debian==
> arch==x86_64==
> vscodeArch==x64==
> bitness==32==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==14383==
> 3125f91de9f5: end
[14:11:33.887] Received install output: 
exitCode==32==
listeningOn====
osReleaseId==debian==
arch==x86_64==
vscodeArch==x64==
bitness==32==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==14383==

[14:11:33.888] Terminating local server
[14:11:33.894] Resolver error: Error: The VS Code Server failed to start
	at m.ServerInstallError (/Users/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:584079)
	at f (/Users/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:578136)
	at t.handleInstallOutput (/Users/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:581161)
	at Object.e [as tryInstallWithLocalServer] (/Users/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:623656)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:643708
	at async t.withShowDetailsEvent (/Users/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:647428)
	at async /Users/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:622128
	at async C (/Users/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:618634)
	at async t.resolveWithLocalServer (/Users/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:621743)
	at async t.resolve (/Users/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:645036)
	at async /Users/martin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.102.0/out/extension.js:1:720916
[14:11:33.896] Local server exit: 15
[14:11:33.901] ------
```

</p>
</details>

**Comment by roblourens** [comment]
It's not supported, sorry https://code.visualstudio.com/docs/remote/linux
