### ISSUE TITLE
[Remote-SSH Bug]: Cannot connect to the docker container on the remote server

### ISSUE THREAD

**Issue by fallingleaflun** [microsoft/vscode-remote-release#8962]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [x] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

1. I can connect to container A running on the same machine. 
2. I use `docker commit` and `docker save` to save the snapshot of container A.
3. I send the snapshot to the remote server and use `docker load` to load and run the container.
4. I cannot connect to the container running on the remote server.

### Expected Behavior

Being able to connect to the container running on the remote server.

### Remote-SSH Log

<details>
<summary>Part of the Remote-SSH Log</summary>
<p>

```
[44596 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-fb18b7a0-f030-4605-9943-6522c3734a87.js' >/tmp/vscode-remote-containers-server-fb18b7a0-f030-4605-9943-6522c3734a87.js_1694523198202
[44626 ms] 
[44626 ms] 
[44643 ms] Container server: /root/.vscode-server/bin/8b617bd08fd9e3fc94d14adb8d358b56e3f72314/node[1633]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
[44643 ms] Container server: 1: 0xb7d990 node::Abort() [/root/.vscode-server/bin/8b617bd08fd9e3fc94d14adb8d358b56e3f72314/node]
[44644 ms] Container server: 2: 0xb7da0e  [/root/.vscode-server/bin/8b617bd08fd9e3fc94d14adb8d358b56e3f72314/node]
[44645 ms] Container server: 3: 0xbeb98e  [/root/.vscode-server/bin/8b617bd08fd9e3fc94d14adb8d358b56e3f72314/node]
[44645 ms] Container server: 4: 0xbeba71 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [/root/.vscode-server/bin/8b617bd08fd9e3fc94d14adb8d358b56e3f72314/node]
[44646 ms] Container server: 5: 0xb39b5f node::InitializeOncePerProcess(std::vector<std::string, std::allocator<std::string> > const&, node::ProcessFlags::Flags) [/root/.vscode-server/bin/8b617bd08fd9e3fc94d14adb8d358b56e3f72314/node]
[44646 ms] Container server: 6: 0xb3a2b3 node::Start(int, char**) [/root/.vscode-server/bin/8b617bd08fd9e3fc94d14adb8d358b56e3f72314/node]
[44646 ms] Container server: 7: 0x7f0467fef6ca  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7f0467fef785 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
[44647 ms] Container server: 9: 0xab681c  [/root/.vscode-server/bin/8b617bd08fd9e3fc94d14adb8d358b56e3f72314/node]
[44881 ms] Container server: Aborted (core dumped)
[44923 ms] Error: stream ended with:0 but wanted:9
        at c (c:\Users\86134\.vscode\extensions\ms-vscode-remote.remote-containers-0.311.0\dist\extension\extension.js:24:102284)
        at c:\Users\86134\.vscode\extensions\ms-vscode-remote.remote-containers-0.311.0\dist\extension\extension.js:24:102465
        at s (c:\Users\86134\.vscode\extensions\ms-vscode-remote.remote-containers-0.311.0\dist\extension\extension.js:27:5371)
        at Stream.<anonymous> (c:\Users\86134\.vscode\extensions\ms-vscode-remote.remote-containers-0.311.0\dist\extension\extension.js:27:5541)
        at Stream.emit (node:events:513:28)
        at g (c:\Users\86134\.vscode\extensions\ms-vscode-remote.remote-containers-0.311.0\dist\extension\extension.js:27:7426)
        at Dk.e.read (c:\Users\86134\.vscode\extensions\ms-vscode-remote.remote-containers-0.311.0\dist\extension\extension.js:24:109349)
        at Ro._onstream (c:\Users\86134\.vscode\extensions\ms-vscode-remote.remote-containers-0.311.0\dist\extension\extension.js:24:108625)
        at Ro.write (c:\Users\86134\.vscode\extensions\ms-vscode-remote.remote-containers-0.311.0\dist\extension\extension.js:24:107582)
        at c:\Users\86134\.vscode\extensions\ms-vscode-remote.remote-containers-0.311.0\dist\extension\extension.js:24:109585
        at c:\Users\86134\.vscode\extensions\ms-vscode-remote.remote-containers-0.311.0\dist\extension\extension.js:24:95068
        at c:\Users\86134\.vscode\extensions\ms-vscode-remote.remote-containers-0.311.0\dist\extension\extension.js:24:97674
        at Object.cb (c:\Users\86134\.vscode\extensions\ms-vscode-remote.remote-containers-0.311.0\dist\extension\extension.js:24:104250)
        at c (c:\Users\86134\.vscode\extensions\ms-vscode-remote.remote-containers-0.311.0\dist\extension\extension.js:24:102133)
        at l (c:\Users\86134\.vscode\extensions\ms-vscode-remote.remote-containers-0.311.0\dist\extension\extension.js:24:102395)
        at c:\Users\86134\.vscode\extensions\ms-vscode-remote.remote-containers-0.311.0\dist\extension\extension.js:24:102478
        at s (c:\Users\86134\.vscode\extensions\ms-vscode-remote.remote-containers-0.311.0\dist\extension\extension.js:27:5371)
        at Socket.<anonymous> (c:\Users\86134\.vscode\extensions\ms-vscode-remote.remote-containers-0.311.0\dist\extension\extension.js:27:5472)
        at Socket.emit (node:events:513:28)
        at addChunk (node:internal/streams/readable:324:12)
        at readableAddChunk (node:internal/streams/readable:297:9)
        at Readable.push (node:internal/streams/readable:234:10)
        at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[44923 ms] Start: Run in container: mkdir -p '/tmp/devcontainers-567ff262-388c-4975-89ee-82a02bd773d91694523152289' && cat > '/tmp/devcontainers-567ff262-388c-4975-89ee-82a02bd773d91694523152289/env-loginInteractiveShell.json' << 'envJSON'
[44924 ms] Container server terminated (code: 134, signal: null).
[44929 ms] 
[44929 ms] 
[44977 ms] Command failed: /root/.vscode-server/bin/8b617bd08fd9e3fc94d14adb8d358b56e3f72314/bin/code-server --log debug --force-disable-user-env --server-data-dir /root/.vscode-server --telemetry-level all --accept-server-license-terms --host 127.0.0.1 --port 0 --connection-token-file /root/.vscode-server/data/Machine/.connection-token-8b617bd08fd9e3fc94d14adb8d358b56e3f72314 --extensions-download-dir /root/.vscode-server/extensionsCache --start-server 
[44977 ms] /root/.vscode-server/bin/8b617bd08fd9e3fc94d14adb8d358b56e3f72314/node[1642]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xb7d990 node::Abort() [/root/.vscode-server/bin/8b617bd08fd9e3fc94d14adb8d358b56e3f72314/node]
 2: 0xb7da0e  [/root/.vscode-server/bin/8b617bd08fd9e3fc94d14adb8d358b56e3f72314/node]
 3: 0xbeb98e  [/root/.vscode-server/bin/8b617bd08fd9e3fc94d14adb8d358b56e3f72314/node]
 4: 0xbeba71 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [/root/.vscode-server/bin/8b617bd08fd9e3fc94d14adb8d358b56e3f72314/node]
 5: 0xb39b5f node::InitializeOncePerProcess(std::vector<std::string, std::allocator<std::string> > const&, node::ProcessFlags::Flags) [/root/.vscode-server/bin/8b617bd08fd9e3fc94d14adb8d358b56e3f72314/node]
 6: 0xb3a2b3 node::Start(int, char**) [/root/.vscode-server/bin/8b617bd08fd9e3fc94d14adb8d358b56e3f72314/node]
 7: 0x7f81b89be6ca  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7f81b89be785 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0xab681c  [/root/.vscode-server/bin/8b617bd08fd9e3fc94d14adb8d358b56e3f72314/node]
Aborted (core dumped)
[44977 ms] Exit code 134
[47856 ms] userEnvProbe is taking longer than 2 seconds. Process not found.
[54499 ms] Extensions cache, remote removals: None
```

</p>
</details>

### Anything else?

I can connect to a Redis container on the remote server, but I cannot connect to the container A.
The version of devcontainers is as follows:
```
[48 ms] Dev Containers 0.309.0 in VS Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314).
```
local machine:
Windows or Ubuntu (I have tried on two machines)
remote server:
5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fallingleaflun** [comment]
Solved~. It failed because the version of docker installed in the remote server is too low. Just upgrade it.
