### ISSUE TITLE
[Remote-SSH Bug]: Unable to SSH to remote server

### ISSUE THREAD

**Issue by shashank140195** [microsoft/vscode-remote-release#8966]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[20:25:59.943] Failed to parse remote port from server output
[20:25:59.943] Terminating local server
[20:25:59.944] Resolver error: Error: 
	at g.Create (/Users/shashankgupta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:637879)
	at t.handleInstallOutput (/Users/shashankgupta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:635279)
	at e (/Users/shashankgupta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:695279)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /Users/shashankgupta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:717117
	at async t.withShowDetailsEvent (/Users/shashankgupta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:720723)
	at async /Users/shashankgupta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:693700
	at async C (/Users/shashankgupta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:690170)
	at async t.resolveWithLocalServer (/Users/shashankgupta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:693291)
	at async C (/Users/shashankgupta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:714245)
	at async t.resolve (/Users/shashankgupta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:718119)
	at async /Users/shashankgupta/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:901789
[20:25:59.945] Local server exit: 15
[20:25:59.948] ------
```

</p>
</details>

**Comment by abearxiong** [comment]
maybe you can rm server `~/.vscode*`

**Comment by aipatr** [comment]
In older versions it works in the current one it gives:

failed to parse remote port from server output

**Comment by astrowonk** [comment]
This is the same as #8958 I think. Removing the server didn't help me either, only downgrading the extension version did.

**Comment by lnwor** [comment]
I can confirm that the same issue as #8958 is present in `v0.106.4`

**Comment by roblourens** [comment]
Can someone share the full log output, instead of just the end?

**Comment by mortezaataiy** [comment]
[19:51:03.646] "install" terminal command done
[19:51:03.648] Install terminal quit with output:     
[19:51:03.648] Received install output:     
[19:51:03.652] Resolver error: Error: 
	at g.Create (c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:637879)
	at c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:634387
	at t.handleInstallOutput (c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:635201)
	at t.tryInstall (c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:756878)
	at async c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:717470
	at async t.withShowDetailsEvent (c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:720723)
	at async C (c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:714384)
	at async t.resolve (c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:718119)
	at async c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:901789

**Comment by mortezaataiy** [comment]
```
[19:51:03.646] "install" terminal command done
[19:51:03.648] Install terminal quit with output:     
[19:51:03.648] Received install output:     
[19:51:03.652] Resolver error: Error: 
	at g.Create (c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:637879)
	at c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:634387
	at t.handleInstallOutput (c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:635201)
	at t.tryInstall (c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:756878)
	at async c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:717470
	at async t.withShowDetailsEvent (c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:720723)
	at async C (c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:714384)
	at async t.resolve (c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:718119)
	at async c:\Users\username\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:901789
```
@roblourens

**Comment by thiagomarafeli** [comment]
I have just get this same problem... (I'm using Windows 11 and the extensions with the latest updates) the log looks similar to what @mortezaataiy got, but I got a way to solve it
In the log at the end of this comment, Windows is asking us to remove permissions of an account from this file. The account is an "Uknown account" and it's not trivial to remove it. So, what I did to remove it was:

# Steps that worked for me
1. Right click the file/folder and go to `Properties > Security > Advanced`
2. Click over the user that is causing problems and then on `Disable inheritance`
3. Click again over the same user and finally click on `Remove`
4. Apply all changes
5. Try to connect again

# Log with the error:
```
[04:09:04.766] Log Level: 2
[04:09:04.788] SSH Resolver called for "ssh-remote+192.168.0.3", attempt 1
[04:09:04.789] "remote.SSH.useLocalServer": false
[04:09:04.789] "remote.SSH.useExecServer": false
[04:09:04.790] "remote.SSH.showLoginTerminal": false
[04:09:04.790] "remote.SSH.remotePlatform": {}
[04:09:04.791] "remote.SSH.path": undefined
[04:09:04.791] "remote.SSH.configFile": undefined
[04:09:04.791] "remote.SSH.useFlock": true
[04:09:04.791] "remote.SSH.lockfilesInTmp": false
[04:09:04.792] "remote.SSH.localServerDownload": auto
[04:09:04.795] "remote.SSH.remoteServerListenOnSocket": false
[04:09:04.796] "remote.SSH.showLoginTerminal": false
[04:09:04.796] "remote.SSH.defaultExtensions": []
[04:09:04.797] "remote.SSH.loglevel": 2
[04:09:04.798] "remote.SSH.enableDynamicForwarding": true
[04:09:04.798] "remote.SSH.enableRemoteCommand": false
[04:09:04.799] "remote.SSH.serverPickPortsFromRange": {}
[04:09:04.799] "remote.SSH.serverInstallPath": {}
[04:09:04.808] VS Code version: 1.84.2
[04:09:04.808] Remote-SSH version: remote-ssh@0.107.0
[04:09:04.809] win32 x64
[04:09:04.815] SSH Resolver called for host: 192.168.0.3
[04:09:04.816] Setting up SSH remote "192.168.0.3"
[04:09:04.824] Using commit id "1a5daa3a0231a0fbba4f14db7ec463cf99d7768e" and quality "stable" for server
[04:09:04.831] Install and start server if needed
[04:09:06.932] Checking ssh with "C:\Program Files (x86)\GnuWin32\bin\ssh.exe -V"
[04:09:06.938] Got error from ssh: spawn C:\Program Files (x86)\GnuWin32\bin\ssh.exe ENOENT
[04:09:06.939] Checking ssh with "C:\MinGW\bin\ssh.exe -V"
[04:09:06.941] Got error from ssh: spawn C:\MinGW\bin\ssh.exe ENOENT
[04:09:06.941] Checking ssh with "C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe -V"
[04:09:06.944] Got error from ssh: spawn C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[04:09:06.944] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[04:09:06.947] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[04:09:06.947] Checking ssh with "C:\Windows\ssh.exe -V"
[04:09:06.950] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[04:09:06.950] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[04:09:06.951] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[04:09:06.952] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[04:09:06.953] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[04:09:06.954] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[04:09:07.014] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[04:09:07.020] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 49544 "192.168.0.3" bash
[04:09:07.025] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[04:09:07.836] > Bad permissions. Try removing permissions for user: UNKNOWN\\UNKNOWN (S-1-5-21-4094470673-428602975-3590580420-1002) on file C:/Users/thiago/.ssh/config.
> Bad owner or permissions on C:\\Users\\thiago/.ssh/config
> O processo tentou gravar em um pipe inexistente.
> ]0;C:\WINDOWS\System32\cmd.exe
[04:09:07.836] Got some output, clearing connection timeout
[04:09:09.091] "install" terminal command done
[04:09:09.092] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exe
[04:09:09.092] Received install output: ]0;C:\WINDOWS\System32\cmd.exe
[04:09:09.093] Failed to parse remote port from server output
[04:09:09.096] Resolver error: Error: 
	at g.Create (c:\Users\thiago\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.0\out\extension.js:2:642290)
	at t.handleInstallOutput (c:\Users\thiago\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.0\out\extension.js:2:639656)
	at t.tryInstall (c:\Users\thiago\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.0\out\extension.js:2:761636)
	at async c:\Users\thiago\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.0\out\extension.js:2:722175
	at async t.withShowDetailsEvent (c:\Users\thiago\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.0\out\extension.js:2:725481)
	at async I (c:\Users\thiago\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.0\out\extension.js:2:719146)
	at async t.resolve (c:\Users\thiago\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.0\out\extension.js:2:722852)
	at async c:\Users\thiago\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.0\out\extension.js:2:906656
[04:09:09.102] ------
```

**Comment by roblourens** [comment]
The latest logs describe `Bad owner or permissions on C:\\Users\\myuser/.ssh/config` which is a real issue that you will have to fix. This is enforced by windows ssh, nothing I can do.

Not hearing from anyone else, closing
