### ISSUE TITLE
[Remote-SSH Bug]: Fails to untar archive vscode-server.tar.gz

### ISSUE THREAD

**Issue by snps-etowie** [microsoft/vscode-remote-release#8970]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Steps To Reproduce

1. Use Windows 11 and VS-Code 1.82.1 (occurs for many previous releases too) with CentOS7 remote host.
2. Start Remote-SSH session.
3. See issue with tar on the remote vscode-server.tar.gz

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[10:35:28.026] Log Level: 2
[10:35:28.034] VS Code version: 1.82.1
[10:35:28.035] Remote-SSH version: remote-ssh@0.106.4
[10:35:28.035] win32 x64
[10:35:28.057] SSH Resolver called for "ssh-remote+ness", attempt 1
[10:35:28.057] "remote.SSH.useLocalServer": false
[10:35:28.057] "remote.SSH.useExecServer": false
[10:35:28.058] "remote.SSH.showLoginTerminal": false
[10:35:28.058] "remote.SSH.remotePlatform": {"ness":"linux"}
[10:35:28.058] "remote.SSH.path": undefined
[10:35:28.058] "remote.SSH.configFile": undefined
[10:35:28.058] "remote.SSH.useFlock": true
[10:35:28.059] "remote.SSH.lockfilesInTmp": false
[10:35:28.059] "remote.SSH.localServerDownload": auto
[10:35:28.059] "remote.SSH.remoteServerListenOnSocket": false
[10:35:28.060] "remote.SSH.showLoginTerminal": false
[10:35:28.060] "remote.SSH.defaultExtensions": []
[10:35:28.060] "remote.SSH.loglevel": 2
[10:35:28.061] "remote.SSH.enableDynamicForwarding": true
[10:35:28.061] "remote.SSH.enableRemoteCommand": false
[10:35:28.061] "remote.SSH.serverPickPortsFromRange": {"ness":{"start":4000,"end":5000}}
[10:35:28.065] "remote.SSH.serverInstallPath": {"ness":"/SCRATCH/etowie"}
[10:35:28.084] SSH Resolver called for host: ness
[10:35:28.084] Setting up SSH remote "ness"
[10:35:28.092] Using commit id "6509174151d557a81c9d0b5f8a5a1e9274db5585" and quality "stable" for server
[10:35:28.096] Install and start server if needed
[10:35:28.100] Checking ssh with "C:\Program Files\Microsoft\jdk-11.0.11.9-hotspot\bin\ssh.exe -V"
[10:35:28.106] Got error from ssh: spawn C:\Program Files\Microsoft\jdk-11.0.11.9-hotspot\bin\ssh.exe ENOENT
[10:35:28.107] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[10:35:28.109] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[10:35:28.109] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[10:35:28.113] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[10:35:28.114] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[10:35:28.117] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[10:35:28.117] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[10:35:28.120] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[10:35:28.120] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[10:35:28.299] > OpenSSH_for_Windows_8.
[10:35:28.300] > 6p1, LibreSSL 3.4.3

[10:35:28.309] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 63309 ness bash
[10:35:28.315] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:35:30.085] > 3421cef34ccd: running
> Acquiring lock on /SCRATCH/etowie/.vscode-server/bin/6509174151d557a81c9d0b5f8a5a1e9274db5585/vscode-remote-lock.etowie.6509174151d557a81c9d0b5f8a5a1e9274db5585
> Installing to /SCRATCH/etowie/.vscode-server/bin/6509174151d557a81c9d0b5f8a5a1e9274db5585...
> 3421cef34ccd%%1%%
> Downloading with wget
> ]0;C:\WINDOWS\System32\cmd.exe
[10:35:30.087] Got some output, clearing connection timeout
[10:35:33.892] > Download complete
> 3421cef34ccd%%2%%
> tar --version:
> tar (GNU tar) 1.13.25
> Copyright (C) 2001 Free Software Foundation, Inc.
> This program comes with NO WARRANTY, to the extent permitted by law.
> You may redistribute it under the terms of the GNU General Public License;
> see the file named COPYING for details.
> Written by John Gilmore and Jay Fenlason.
> tar: This does not look like a tar archive
> tar: Skipping to next header
> tar: Archive contains obsolescent base-64 headers
[10:35:33.943] > tar: Error exit delayed from previous errors
> ERROR: tar exited with non-0 exit code: 0
> Trigger local server download
> 3421cef34ccd:trigger_server_download
> artifact==server-linux-x64==
> destFolder==/SCRATCH/etowie/.vscode-server/bin/==
> destFolder2==/6509174151d557a81c9d0b5f8a5a1e9274db5585/vscode-server.tar.gz==
> 3421cef34ccd:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /SCRATCH/etowie/.vscode-server/bin/6509174151d557a81c9d0b5f8a5a1e9274db5585/vscode-server.tar.gz.done and vscode-server.tar.gz to exist
> 
[10:35:33.944] Got request to download on client for {"artifact":"server-linux-x64","destPath":"/SCRATCH/etowie/.vscode-server/bin//6509174151d557a81c9d0b5f8a5a1e9274db5585/vscode-server.tar.gz"}
[10:35:33.945] Downloading VS Code server locally...
[10:38:25.305] Downloaded VS Code server to c:\Users\etowie\AppData\Local\Temp\70360088-2f6e-470a-b18b-76ee20270aa0
[10:38:25.310] Renamed VS Code server to c:\Users\etowie\AppData\Local\Temp\vscode_server_1694597905306\vscode-server.tar.gz
[10:38:25.315] Checking ssh with "C:\Program Files\Microsoft\jdk-11.0.11.9-hotspot\bin\ssh.exe -V"
[10:38:25.318] Got error from ssh: spawn C:\Program Files\Microsoft\jdk-11.0.11.9-hotspot\bin\ssh.exe ENOENT
[10:38:25.318] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[10:38:25.320] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[10:38:25.320] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[10:38:25.322] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[10:38:25.322] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[10:38:25.326] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[10:38:25.326] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[10:38:25.328] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[10:38:25.328] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[10:38:25.480] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[10:38:25.488] Expecting scp to be next to ssh at C:\WINDOWS\System32\OpenSSH\scp.exe
[10:38:25.489] Testing scp with "C:\WINDOWS\System32\OpenSSH\scp.exe"
[10:38:25.648] scp exited with code: 1
[10:38:25.648] Got stderr from scp: usage: scp [-346ABCpqrTv] [-c cipher] [-F ssh_config] [-i identity_file]
            [-J destination] [-l limit] [-o ssh_option] [-P port]
            [-S program] source ... target
[10:38:25.649] Copying file to remote with "C:\WINDOWS\System32\OpenSSH\scp.exe" "vscode-server.tar.gz" "vscode-server.tar.gz.done" ness:"/SCRATCH/etowie/.vscode-server/bin//6509174151d557a81c9d0b5f8a5a1e9274db5585"
[10:38:25.649] Using cwd: file:///c%3A/Users/etowie/AppData/Local/Temp/vscode_server_1694597905306
[10:38:25.650] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:38:27.355] > vscode-server.tar.gz                            0%    0     0.0KB/s   --:-- ETA]0;C:\WINDOWS\System32\cmd.exe
[10:38:28.355] > vscode-server.tar.gz                           13% 6960KB   6.7MB/s   00:06 ETA
[10:38:29.358] > vscode-server.tar.gz                           32%   16MB   6.9MB/s   00:04 ETA
[10:38:30.380] > vscode-server.tar.gz                           50%   25MB   7.1MB/s   00:03 ETA
[10:38:31.379] > vscode-server.tar.gz                           67%   33MB   7.3MB/s   00:02 ETA
[10:38:32.382] > vscode-server.tar.gz                           83%   41MB   7.3MB/s   00:01 ETA
[10:38:33.398] > vscode-server.tar.gz                           98%   48MB   7.3MB/s   00:00 ETA
[10:38:33.761] > vscode-server.tar.gz                          100%   49MB   7.6MB/s   00:06    
> 
[10:38:33.823] > vscode-server.tar.gz.done                       0%    0     0.0KB/s   --:-- ETA
[10:38:33.881] > vscode-server.tar.gz.done                     100%    9     0.2KB/s   00:00    
[10:38:33.975] > Found flag and serve
> er on host
> 3421cef34ccd%%2%%
> tar --version:
> tar (GNU tar) 1.13.25
> Copyright (C) 2001 Free Software Foundation, Inc.
> This program comes with NO WARRANTY, to the extent permitted by law.
> You may redistribute it under the terms of the GNU General Public License;      
> see the file named COPYING for details.
> Written by John Gilmore and Jay Fenlason.
> tar: This does not look like a tar archive
[10:38:33.982] > 
> tar: Skipping to next header
> tar: Archive contains obsolescent base-64 headers
[10:38:33.991] > 
[10:38:34.031] > tar: Error exit delayed from previous errors
> ERROR: tar exited with non-0 exit code: 0
> Already attempted local download, failing
> 3421cef34ccd: start
> exitCode==37==
> listeningOn====
> osReleaseId==centos==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/32960==
> platform==linux==
> unpackResult==error==
> didLocalDownload==1==
> downloadTime==3940==
> installTime==49==
> extInstallTime====
> serverStartTime====
> 3421cef34ccd: end
[10:38:34.031] Received install output: 
exitCode==37==
listeningOn====
osReleaseId==centos==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/32960==
platform==linux==
unpackResult==error==
didLocalDownload==1==
downloadTime==3940==
installTime==49==
extInstallTime====
serverStartTime====

[10:38:34.038] Resolver error: Error: Failed to install the VS Code Server
	at g.ServerInstallError (c:\Users\etowie\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:637813)
	at d (c:\Users\etowie\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:631686)
	at t.handleInstallOutput (c:\Users\etowie\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:633504)
	at t.tryInstall (c:\Users\etowie\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:756878)
	at async c:\Users\etowie\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:717470
	at async t.withShowDetailsEvent (c:\Users\etowie\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:720723)
	at async C (c:\Users\etowie\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:714384)
	at async t.resolve (c:\Users\etowie\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:718119)
	at async c:\Users\etowie\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:901789
[10:38:34.049] ------




[10:38:34.546] > 
[10:38:35.251] "Copy server to host" terminal command done
[10:38:35.553] "install" terminal command done
[10:38:35.553] Install terminal quit with output: 

```

</p>
</details>

### Anything else?

If I connect via SSH on the Windows Terminal to the remote host and navigate to the location of the vscode-server.tar.gz, I'm able to untar the archive using the system tar without any issue. I'm very confused why VSCode reports the errors as I cannot repeat them.

**Comment by snps-etowie** [comment]
I probably should've added that to workaround this issue I simply manually untar the downloaded vscode-server.tar.gz. Everything else works as expected until the next update where I have to go through the same procedure.
Appreciate this version of tar is old, but why does it work for me and not for VSCode? 
What is the command line for the untar operation used by VSCode?

**Comment by roblourens** [comment]
Guessing that the old tar version is the issue. Simply `tar -xf vscode-server.tar.gz`. What command works for you?

**Comment by snps-etowie** [comment]
Exactly the same command, unsurprisingly!  I really don't understand the old version works in a terminal, but fails in VSCode..

**Comment by snps-etowie** [comment]
Ok, I updated the version of tar on my remote host from 1.13.25 to 1.28 and forced a re-install of the VSCode server. It immediately starts working, so as suspected it is somehow due to the ancient version of tar. 

I've no idea why my system has such an ancient version, it's over 20yrs old with even 1.28 being ~10yrs old.

Still it works without manual intervention so I will mark this issue as resolved.
