### ISSUE TITLE
[Remote-SSH Bug]: Connection times out when connecting to raspberry pi 4b, connects successfully from local terminal

### ISSUE THREAD

**Issue by safarzadehsbeengood** [microsoft/vscode-remote-release#8987]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

No impact from toggling useLocalServer either way, showLoginTerminal doesn't make a difference.

### Expected Behavior

Until yesterday, Remote SSH was working fine for the raspberry pi. I can still Remote SSH into other servers with no problem, so it is definitely a problem with VSCode and the pi. It would prompt me for the password once, then I would be connected.

### Steps To Reproduce

1. Open remote explorer
2. Connect to ssh host
3. VSCode server tries to install, connection times out

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[00:44:05.438] Log Level: 2
[00:44:05.448] SSH Resolver called for "ssh-remote+45.31.61.225", attempt 1
[00:44:05.448] "remote.SSH.useLocalServer": true
[00:44:05.448] "remote.SSH.useExecServer": false
[00:44:05.448] "remote.SSH.path": undefined
[00:44:05.448] "remote.SSH.configFile": undefined
[00:44:05.448] "remote.SSH.useFlock": true
[00:44:05.449] "remote.SSH.lockfilesInTmp": false
[00:44:05.449] "remote.SSH.localServerDownload": auto
[00:44:05.449] "remote.SSH.remoteServerListenOnSocket": false
[00:44:05.449] "remote.SSH.showLoginTerminal": true
[00:44:05.449] "remote.SSH.defaultExtensions": []
[00:44:05.449] "remote.SSH.loglevel": 2
[00:44:05.449] "remote.SSH.enableDynamicForwarding": true
[00:44:05.449] "remote.SSH.enableRemoteCommand": false
[00:44:05.449] "remote.SSH.serverPickPortsFromRange": {}
[00:44:05.449] "remote.SSH.serverInstallPath": {}
[00:44:05.451] VS Code version: 1.82.2
[00:44:05.452] Remote-SSH version: remote-ssh@0.106.4
[00:44:05.452] win32 x64
[00:44:05.452] SSH Resolver called for host: 45.31.61.225
[00:44:05.452] Setting up SSH remote "45.31.61.225"
[00:44:05.455] Acquiring local install lock: C:\Users\RYAN\AppData\Local\Temp\vscode-remote-ssh-a15cb036-install.lock
[00:44:05.458] Looking for existing server data file at c:\Users\RYAN\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-ssh\vscode-ssh-host-a15cb036-abd2f3db4bdb28f9e95536dfa84d8479f1eb312d-0.106.4\data.json
[00:44:05.459] Using commit id "abd2f3db4bdb28f9e95536dfa84d8479f1eb312d" and quality "stable" for server
[00:44:05.461] Install and start server if needed
[00:44:05.463] Checking ssh with "C:\Program Files\Eclipse Adoptium\jdk-19.0.1.10-hotspot\bin\ssh.exe -V"
[00:44:05.465] Got error from ssh: spawn C:\Program Files\Eclipse Adoptium\jdk-19.0.1.10-hotspot\bin\ssh.exe ENOENT
[00:44:05.466] Checking ssh with "C:\Python310\Scripts\ssh.exe -V"
[00:44:05.466] Got error from ssh: spawn C:\Python310\Scripts\ssh.exe ENOENT
[00:44:05.467] Checking ssh with "C:\Python310\ssh.exe -V"
[00:44:05.467] Got error from ssh: spawn C:\Python310\ssh.exe ENOENT
[00:44:05.468] Checking ssh with "C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler\ssh.exe -V"
[00:44:05.468] Got error from ssh: spawn C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler\ssh.exe ENOENT
[00:44:05.468] Checking ssh with "C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe -V"
[00:44:05.469] Got error from ssh: spawn C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[00:44:05.469] Checking ssh with "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe -V"
[00:44:05.470] Got error from ssh: spawn C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[00:44:05.470] Checking ssh with "C:\Program Files (x86)\Razer Chroma SDK\bin\ssh.exe -V"
[00:44:05.471] Got error from ssh: spawn C:\Program Files (x86)\Razer Chroma SDK\bin\ssh.exe ENOENT
[00:44:05.471] Checking ssh with "C:\Program Files\Razer Chroma SDK\bin\ssh.exe -V"
[00:44:05.472] Got error from ssh: spawn C:\Program Files\Razer Chroma SDK\bin\ssh.exe ENOENT
[00:44:05.472] Checking ssh with "C:\Program Files (x86)\Razer\ChromaBroadcast\bin\ssh.exe -V"
[00:44:05.473] Got error from ssh: spawn C:\Program Files (x86)\Razer\ChromaBroadcast\bin\ssh.exe ENOENT
[00:44:05.473] Checking ssh with "C:\Program Files\Razer\ChromaBroadcast\bin\ssh.exe -V"
[00:44:05.474] Got error from ssh: spawn C:\Program Files\Razer\ChromaBroadcast\bin\ssh.exe ENOENT
[00:44:05.474] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[00:44:05.475] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[00:44:05.475] Checking ssh with "C:\Windows\ssh.exe -V"
[00:44:05.476] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[00:44:05.476] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[00:44:05.477] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[00:44:05.477] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[00:44:05.478] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[00:44:05.478] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[00:44:05.499] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[00:44:05.501] Checking ssh with "C:\Program Files\Intel\WiFi\bin\ssh.exe -V"
[00:44:05.502] Got error from ssh: spawn C:\Program Files\Intel\WiFi\bin\ssh.exe ENOENT
[00:44:05.502] Checking ssh with "C:\Program Files\Common Files\Intel\WirelessCommon\ssh.exe -V"
[00:44:05.503] Got error from ssh: spawn C:\Program Files\Common Files\Intel\WirelessCommon\ssh.exe ENOENT
[00:44:05.503] Checking ssh with "C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR\ssh.exe -V"
[00:44:05.504] Got error from ssh: spawn C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR\ssh.exe ENOENT
[00:44:05.504] Checking ssh with "C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\ssh.exe -V"
[00:44:05.505] Got error from ssh: spawn C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\ssh.exe ENOENT
[00:44:05.505] Checking ssh with "C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps\ssh.exe -V"
[00:44:05.506] Got error from ssh: spawn C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps\ssh.exe ENOENT
[00:44:05.506] Checking ssh with "C:\Users\RYAN\AppData\Local\Microsoft\WindowsApps\ssh.exe -V"
[00:44:05.507] Got error from ssh: spawn C:\Users\RYAN\AppData\Local\Microsoft\WindowsApps\ssh.exe ENOENT
[00:44:05.507] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[00:44:05.508] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[00:44:05.508] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[00:44:05.509] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[00:44:05.509] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[00:44:05.510] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[00:44:05.510] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[00:44:05.511] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[00:44:05.511] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[00:44:05.531] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[00:44:05.533] Checking ssh with "C:\Program Files\Git\cmd\ssh.exe -V"
[00:44:05.534] Got error from ssh: spawn C:\Program Files\Git\cmd\ssh.exe ENOENT
[00:44:05.534] Checking ssh with "C:\Program Files\nodejs\ssh.exe -V"
[00:44:05.535] Got error from ssh: spawn C:\Program Files\nodejs\ssh.exe ENOENT
[00:44:05.535] Checking ssh with "C:\ProgramData\chocolatey\bin\ssh.exe -V"
[00:44:05.536] Got error from ssh: spawn C:\ProgramData\chocolatey\bin\ssh.exe ENOENT
[00:44:05.536] Checking ssh with "C:\Program Files (x86)\QuickTime\QTSystem\ssh.exe -V"
[00:44:05.537] Got error from ssh: spawn C:\Program Files (x86)\QuickTime\QTSystem\ssh.exe ENOENT
[00:44:05.537] Checking ssh with "C:\Users\RYAN\AppData\Local\Programs\Python\Python38\ssh.exe -V"
[00:44:05.538] Got error from ssh: spawn C:\Users\RYAN\AppData\Local\Programs\Python\Python38\ssh.exe ENOENT
[00:44:05.538] Checking ssh with "C:\Users\RYAN\AppData\Local\Programs\Python\Python38\Scripts\ssh.exe -V"
[00:44:05.539] Got error from ssh: spawn C:\Users\RYAN\AppData\Local\Programs\Python\Python38\Scripts\ssh.exe ENOENT
[00:44:05.539] Checking ssh with "C:\Users\RYAN\AppData\Local\Programs\Microsoft VS Code\bin\ssh.exe -V"
[00:44:05.540] Got error from ssh: spawn C:\Users\RYAN\AppData\Local\Programs\Microsoft VS Code\bin\ssh.exe ENOENT
[00:44:05.540] Checking ssh with "C:\Users\RYAN\Downloads\MinGW\bin\ssh.exe -V"
[00:44:05.541] Got error from ssh: spawn C:\Users\RYAN\Downloads\MinGW\bin\ssh.exe ENOENT
[00:44:05.541] Checking ssh with "C:\Users\RYAN\AppData\Roaming\npm\ssh.exe -V"
[00:44:05.542] Got error from ssh: spawn C:\Users\RYAN\AppData\Roaming\npm\ssh.exe ENOENT
[00:44:05.542] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[00:44:05.562] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[00:44:05.564] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[00:44:05.587] > OpenSSH_9.0p1, OpenSSL 1.1.1o  3 May 2022

[00:44:05.613] Using SSH config file "C:\Users\RYAN\.ssh\config"
[00:44:05.614] askpass server listening on \\.\pipe\vscode-ssh-askpass-f32b81752887368e6d8f62060a3fa132da9e55de-sock
[00:44:05.614] Spawning local server with {"serverId":1,"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-d909074e1a2e33e5873f041e121b3a5b9948ba85-sock","sshCommand":"C:\\Program Files\\Git\\usr\\bin\\ssh.exe","sshArgs":["-v","-T","-D","52250","-F","C:\\Users\\RYAN\\.ssh\\config","45.31.61.225","bash"],"serverDataFolderName":".vscode-server","dataFilePath":"c:\\Users\\RYAN\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-vscode-remote.remote-ssh\\vscode-ssh-host-a15cb036-abd2f3db4bdb28f9e95536dfa84d8479f1eb312d-0.106.4\\data.json"}
[00:44:05.614] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"c:\\Users\\RYAN\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.106.4\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"C:\\Users\\RYAN\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"c:\\Users\\RYAN\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.106.4\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-f32b81752887368e6d8f62060a3fa132da9e55de-sock"}
[00:44:05.622] Spawned 12320
[00:44:05.714] > local-server-1> Running ssh connection command: "-v -T -D 52250 -F C:\\Users\\RYAN\\.ssh\\config 45.31.61.225 bash"
[00:44:05.718] > local-server-1> Spawned ssh, pid=27376
[00:44:05.747] stderr> OpenSSH_9.0p1, OpenSSL 1.1.1o  3 May 2022
[00:44:26.785] stderr> ssh: connect to host 45.31.61.225 port 22: Connection timed out
[00:44:26.802] > local-server-1> ssh child died, shutting down
[00:44:26.809] Local server exit: 0
[00:44:26.809] Received install output: local-server-1> Running ssh connection command: "-v -T -D 52250 -F C:\\Users\\RYAN\\.ssh\\config 45.31.61.225 bash"
local-server-1> Spawned ssh, pid=27376
OpenSSH_9.0p1, OpenSSL 1.1.1o  3 May 2022
ssh: connect to host 45.31.61.225 port 22: Connection timed out
local-server-1> ssh child died, shutting down

[00:44:26.811] Resolver error: Error: The connection timed out
	at g.Offline (c:\Users\RYAN\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:637930)
	at c:\Users\RYAN\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:634033
	at t.handleInstallOutput (c:\Users\RYAN\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:634348)
	at e (c:\Users\RYAN\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:695279)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async c:\Users\RYAN\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:717117
	at async t.withShowDetailsEvent (c:\Users\RYAN\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:720723)
	at async c:\Users\RYAN\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:693700
	at async C (c:\Users\RYAN\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:690170)
	at async t.resolveWithLocalServer (c:\Users\RYAN\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:693291)
	at async C (c:\Users\RYAN\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:714245)
	at async t.resolve (c:\Users\RYAN\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:718119)
	at async c:\Users\RYAN\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.4\out\extension.js:2:901789
[00:44:26.813] ------



```

</p>
</details>

**Comment by roblourens** [comment]
We spawned ssh and got no output. Are you sure you can ssh into that device from a separate terminal? Did anything change in your settings or ssh config? Can you try downgrading the Remote-SSH extension? (Right click Remote-SSH > install another version)

**Comment by safarzadehsbeengood** [comment]
Turns out there was some weird stuff going on with the Ethernet connection,
it’s fixed now thank you!
