### ISSUE TITLE
Unable to run dev container without WSL 2 integration

### ISSUE THREAD

**Issue by jsunico** [microsoft/vscode-remote-release#9002]
I'm purposely running my Docker Desktop with Hyper-v and without using WSL 2 Integration. This is because of the memory issues I've been having with WSL 2. I would like to use dev containers to run my application but I have been getting an error so far.

When I'm trying to open the current folder in the container, it seems like VSCode is trying to use WSL 2 to build my dev container. Eventually, this results in the error:

```
[2023-09-19T10:31:18.520Z] docker: Error response from daemon: \\wsl.localhost\Ubuntu-20.04\mnt\wslg\runtim
e-dir\wayland-0%!(EXTRA string=is not a valid Windows path).
See 'docker run --help'.
```

- VSCode Version: 1.82.2
- Local OS Version: Windows 10 Enterprise 21H2 19044.3324
- Remote OS Version: Docker Desktop 4.23.0
- Remote Extension/Connection Type: Linux Container / Hyper-V

- Logs:
```
[2023-09-19T10:31:09.924Z] Start: Resolving Remote
[2023-09-19T10:31:09.924Z] Dev Containers 0.309.0 in VS Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d).
[2023-09-19T10:31:09.989Z] Setting up container for folder or workspace: c:\Users\someone\projects\app1
[2023-09-19T10:31:09.992Z] Start: Run: wsl -l -v
[2023-09-19T10:31:10.560Z] Stop (568 ms): Run: wsl -l -v
[2023-09-19T10:31:10.562Z] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c echo ~
[2023-09-19T10:31:11.159Z] Stop (597 ms): Run: wsl -d Ubuntu-20.04 -e /bin/sh -c echo ~
[2023-09-19T10:31:11.166Z] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/home/someone' && /bin/sh
[2023-09-19T10:31:11.220Z] Start: Run in host: id -un
[2023-09-19T10:31:11.531Z] someone
[2023-09-19T10:31:11.531Z] 
[2023-09-19T10:31:11.532Z] Stop (312 ms): Run in host: id -un
[2023-09-19T10:31:11.532Z] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'someone' || grep -E '^someone|^[^:]*:[^:]*:someone:' /etc/passwd || true)
[2023-09-19T10:31:11.535Z] Stop (3 ms): Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'someone' || grep -E '^someone|^[^:]*:[^:]*:someone:' /etc/passwd || true)
[2023-09-19T10:31:11.536Z] Start: Run in host: echo ~
[2023-09-19T10:31:11.537Z] /home/someone
[2023-09-19T10:31:11.538Z] 
[2023-09-19T10:31:11.538Z] Stop (2 ms): Run in host: echo ~
[2023-09-19T10:31:11.539Z] Start: Run in host: test -x '/home/someone/.vscode-remote-containers/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/node'
[2023-09-19T10:31:11.541Z] 
[2023-09-19T10:31:11.541Z] 
[2023-09-19T10:31:11.541Z] Exit code 1
[2023-09-19T10:31:11.542Z] Stop (3 ms): Run in host: test -x '/home/someone/.vscode-remote-containers/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/node'
[2023-09-19T10:31:11.543Z] Start: Run in host: test -x '/home/someone/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/node'
[2023-09-19T10:31:11.544Z] 
[2023-09-19T10:31:11.544Z] 
[2023-09-19T10:31:11.544Z] Stop (1 ms): Run in host: test -x '/home/someone/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/node'
[2023-09-19T10:31:11.544Z] Start: Run in host: test -f '/home/someone/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/node_modules/node-pty/package.json'
[2023-09-19T10:31:11.546Z] 
[2023-09-19T10:31:11.546Z] 
[2023-09-19T10:31:11.547Z] Stop (3 ms): Run in host: test -f '/home/someone/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/node_modules/node-pty/package.json'
[2023-09-19T10:31:11.547Z] Start: Run in host: test -f '/home/someone/.vscode-remote-containers/dist/vscode-remote-containers-server-0.309.0.js'
[2023-09-19T10:31:11.548Z] 
[2023-09-19T10:31:11.548Z] 
[2023-09-19T10:31:11.548Z] Stop (1 ms): Run in host: test -f '/home/someone/.vscode-remote-containers/dist/vscode-remote-containers-server-0.309.0.js'
[2023-09-19T10:31:11.556Z] userEnvProbe: loginInteractiveShell (default)
[2023-09-19T10:31:11.556Z] userEnvProbe: not found in cache
[2023-09-19T10:31:11.556Z] userEnvProbe shell: /usr/bin/zsh
[2023-09-19T10:31:13.260Z] userEnvProbe PATHs:
Probe:     '/home/someone/.nvm/versions/node/v16.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/Microsoft/jdk-11.0.18.10-hotspot/bin:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/dotnet/:/mnt/c/ffmpeg/bin:/mnt/c/Program Files/Cloudflare/Cloudflare WARP/:/mnt/c/apache-activemq-5.18.1/bin:/mnt/c/Program Files/Amazon/AWSSAMCLI/bin/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/Users/someone/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/someone/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/someone/AppData/Local/Programs/Fiddler:/mnt/c/Users/someone/AppData/Local/Microsoft/WinGet/Packages/Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe:/home/someone/.local/bin'
Container: None
[2023-09-19T10:31:13.268Z] Start: Run in Host: wslpath -w /mnt/wslg/runtime-dir/wayland-0
[2023-09-19T10:31:13.273Z] Stop (5 ms): Run in Host: wslpath -w /mnt/wslg/runtime-dir/wayland-0
[2023-09-19T10:31:13.274Z] Start: Check Docker is running
[2023-09-19T10:31:13.275Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2023-09-19T10:31:13.574Z] Stop (299 ms): Run: docker version --format {{.Server.APIVersion}}
[2023-09-19T10:31:13.575Z] Server API version: 1.43
[2023-09-19T10:31:13.575Z] Stop (301 ms): Check Docker is running
[2023-09-19T10:31:13.576Z] Start: Run: docker volume ls -q
[2023-09-19T10:31:13.872Z] Stop (296 ms): Run: docker volume ls -q
[2023-09-19T10:31:13.873Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=c:\Users\someone\projects\app1 --filter label=vsch.quality=stable
[2023-09-19T10:31:14.182Z] Stop (309 ms): Run: docker ps -q -a --filter label=vsch.local.folder=c:\Users\someone\projects\app1 --filter label=vsch.quality=stable
[2023-09-19T10:31:14.183Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\someone\projects\app1 --filter label=devcontainer.config_file=c:\Users\someone\projects\app1\.devcontainer\devcontainer.json
[2023-09-19T10:31:14.492Z] Stop (309 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\someone\projects\app1 --filter label=devcontainer.config_file=c:\Users\someone\projects\app1\.devcontainer\devcontainer.json
[2023-09-19T10:31:14.493Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\someone\projects\app1
[2023-09-19T10:31:14.791Z] Stop (298 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\someone\projects\app1
[2023-09-19T10:31:14.792Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\someone\projects\app1
[2023-09-19T10:31:15.098Z] Stop (306 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\someone\projects\app1
[2023-09-19T10:31:15.100Z] Start: Run: C:\Users\someone\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\someone\.vscode\extensions\ms-vscode-remote.remote-containers-0.309.0\dist\spec-node\devContainersSpecCLI.js read-configuration --workspace-folder c:\Users\someone\projects\app1 --id-label devcontainer.local_folder=c:\Users\someone\projects\app1 --id-label devcontainer.config_file=c:\Users\someone\projects\app1\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\someone\projects\app1\.devcontainer\devcontainer.json --mount-workspace-git-root true
[2023-09-19T10:31:15.763Z] @devcontainers/cli 0.51.1. Node.js v18.15.0. win32 10.0.19044 x64.
[2023-09-19T10:31:15.763Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\someone\projects\app1 --filter label=devcontainer.config_file=c:\Users\someone\projects\app1\.devcontainer\devcontainer.json
[2023-09-19T10:31:16.105Z] Stop (342 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\someone\projects\app1 --filter label=devcontainer.config_file=c:\Users\someone\projects\app1\.devcontainer\devcontainer.json
[2023-09-19T10:31:16.125Z] Stop (1025 ms): Run: C:\Users\someone\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\someone\.vscode\extensions\ms-vscode-remote.remote-containers-0.309.0\dist\spec-node\devContainersSpecCLI.js read-configuration --workspace-folder c:\Users\someone\projects\app1 --id-label devcontainer.local_folder=c:\Users\someone\projects\app1 --id-label devcontainer.config_file=c:\Users\someone\projects\app1\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\someone\projects\app1\.devcontainer\devcontainer.json --mount-workspace-git-root true
[2023-09-19T10:31:16.127Z] Start: Run: C:\Users\someone\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\someone\.vscode\extensions\ms-vscode-remote.remote-containers-0.309.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\someone\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-07b5c790-2533-49ff-8a65-9d12776720f61695119468050 --workspace-folder c:\Users\someone\projects\app1 --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\someone\projects\app1 --id-label devcontainer.config_file=c:\Users\someone\projects\app1\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\someone\projects\app1\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=\\wsl.localhost\Ubuntu-20.04\mnt\wslg\runtime-dir\wayland-0,target=/tmp/vscode-wayland-0e3c539d-fff8-4b07-beee-268f1d0b7d0e.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-09-19T10:31:16.653Z] @devcontainers/cli 0.51.1. Node.js v18.15.0. win32 10.0.19044 x64.
[2023-09-19T10:31:16.653Z] Start: Run: docker buildx version
[2023-09-19T10:31:17.324Z] Stop (671 ms): Run: docker buildx version
[2023-09-19T10:31:17.325Z] github.com/docker/buildx v0.11.2-desktop.4 b9955a86a20bf0112ebb4f14424bf59fc46ee179
[2023-09-19T10:31:17.325Z] 
[2023-09-19T10:31:17.326Z] Start: Resolving Remote
[2023-09-19T10:31:17.334Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\someone\projects\app1 --filter label=devcontainer.config_file=c:\Users\someone\projects\app1\.devcontainer\devcontainer.json
[2023-09-19T10:31:17.626Z] Stop (292 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\someone\projects\app1 --filter label=devcontainer.config_file=c:\Users\someone\projects\app1\.devcontainer\devcontainer.json
[2023-09-19T10:31:17.627Z] Start: Run: docker inspect --type image mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
[2023-09-19T10:31:17.906Z] Stop (279 ms): Run: docker inspect --type image mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
[2023-09-19T10:31:17.909Z] local container features stored at: c:\Users\someone\.vscode\extensions\ms-vscode-remote.remote-containers-0.309.0\dist\node_modules\vscode-dev-containers\container-features
[2023-09-19T10:31:17.911Z] Start: Run: tar --no-same-owner -x -f -
[2023-09-19T10:31:18.029Z] Stop (118 ms): Run: tar --no-same-owner -x -f -
[2023-09-19T10:31:18.033Z] Start: Run: docker events --format {{json .}} --filter event=start
[2023-09-19T10:31:18.064Z] Start: Starting container
[2023-09-19T10:31:18.065Z] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount source=c:\Users\someone\projects\app1,target=/workspace,type=bind,consistency=cached --mount type=volume,src=vscode,dst=/vscode --mount type=bind,src=\\wsl.localhost\Ubuntu-20.04\mnt\wslg\runtime-dir\wayland-0,dst=/tmp/vscode-wayland-0e3c539d-fff8-4b07-beee-268f1d0b7d0e.sock -l devcontainer.local_folder=c:\Users\someone\projects\app1 -l devcontainer.config_file=c:\Users\someone\projects\app1\.devcontainer\devcontainer.json --entrypoint /bin/sh -l devcontainer.metadata=[{"id":"ghcr.io/devcontainers/features/common-utils:2"},{"id":"ghcr.io/devcontainers/features/git:1"},{"id":"ghcr.io/devcontainers/features/node:1","customizations":{"vscode":{"extensions":["dbaeumer.vscode-eslint"]}}},{"customizations":{"vscode":{"extensions":["dbaeumer.vscode-eslint"]}},"remoteUser":"node"},{"id":"ghcr.io/devcontainers/features/git:1"},{"customizations":{"vscode":{"extensions":["dbaeumer.vscode-eslint"]}},"remoteUser":"node"},{"mounts":[]}] mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye -c echo Container started
[2023-09-19T10:31:18.387Z] 
[2023-09-19T10:31:18.520Z] docker: Error response from daemon: \\wsl.localhost\Ubuntu-20.04\mnt\wslg\runtim
e-dir\wayland-0%!(EXTRA string=is not a valid Windows path).
See 'docker run --help'.
[2023-09-19T10:31:18.611Z] Stop (546 ms): Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount source=c:\Users\someone\projects\app1,target=/workspace,type=bind,consistency=cached --mount type=volume,src=vscode,dst=/vscode --mount type=bind,src=\\wsl.localhost\Ubuntu-20.04\mnt\wslg\runtime-dir\wayland-0,dst=/tmp/vscode-wayland-0e3c539d-fff8-4b07-beee-268f1d0b7d0e.sock -l devcontainer.local_folder=c:\Users\someone\projects\app1 -l devcontainer.config_file=c:\Users\someone\projects\app1\.devcontainer\devcontainer.json --entrypoint /bin/sh -l devcontainer.metadata=[{"id":"ghcr.io/devcontainers/features/common-utils:2"},{"id":"ghcr.io/devcontainers/features/git:1"},{"id":"ghcr.io/devcontainers/features/node:1","customizations":{"vscode":{"extensions":["dbaeumer.vscode-eslint"]}}},{"customizations":{"vscode":{"extensions":["dbaeumer.vscode-eslint"]}},"remoteUser":"node"},{"id":"ghcr.io/devcontainers/features/git:1"},{"customizations":{"vscode":{"extensions":["dbaeumer.vscode-eslint"]}},"remoteUser":"node"},{"mounts":[]}] mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye -c echo Container started
[2023-09-19T10:31:18.613Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\someone\projects\app1 --filter label=devcontainer.config_file=c:\Users\someone\projects\app1\.devcontainer\devcontainer.json
[2023-09-19T10:31:18.626Z] Stop (593 ms): Run: docker events --format {{json .}} --filter event=start
[2023-09-19T10:31:18.949Z] Stop (336 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\someone\projects\app1 --filter label=devcontainer.config_file=c:\Users\someone\projects\app1\.devcontainer\devcontainer.json
[2023-09-19T10:31:18.953Z] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount source=c:\Users\someone\projects\app1,target=/workspace,type=bind,consistency=cached --mount type=volume,src=vscode,dst=/vscode --mount type=bind,src=\\wsl.localhost\Ubuntu-20.04\mnt\wslg\runtime-dir\wayland-0,dst=/tmp/vscode-wayland-0e3c539d-fff8-4b07-beee-268f1d0b7d0e.sock -l devcontainer.local_folder=c:\Users\someone\projects\app1 -l devcontainer.config_file=c:\Users\someone\projects\app1\.devcontainer\devcontainer.json --entrypoint /bin/sh -l devcontainer.metadata=[{"id":"ghcr.io/devcontainers/features/common-utils:2"},{"id":"ghcr.io/devcontainers/features/git:1"},{"id":"ghcr.io/devcontainers/features/node:1","customizations":{"vscode":{"extensions":["dbaeumer.vscode-eslint"]}}},{"customizations":{"vscode":{"extensions":["dbaeumer.vscode-eslint"]}},"remoteUser":"node"},{"id":"ghcr.io/devcontainers/features/git:1"},{"customizations":{"vscode":{"extensions":["dbaeumer.vscode-eslint"]}},"remoteUser":"node"},{"mounts":[]}] mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye -c echo Container started
[2023-09-19T10:31:18.953Z] trap "exit 0" 15
[2023-09-19T10:31:18.953Z] exec "$@"
[2023-09-19T10:31:18.953Z] while sleep 1 & wait $!; do :; done -
[2023-09-19T10:31:18.954Z]     at gAA (c:\Users\someone\.vscode\extensions\ms-vscode-remote.remote-containers-0.309.0\dist\spec-node\devContainersSpecCLI.js:462:1066)
[2023-09-19T10:31:18.954Z]     at FK (c:\Users\someone\.vscode\extensions\ms-vscode-remote.remote-containers-0.309.0\dist\spec-node\devContainersSpecCLI.js:462:1002)
[2023-09-19T10:31:18.954Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-09-19T10:31:18.954Z]     at async FAA (c:\Users\someone\.vscode\extensions\ms-vscode-remote.remote-containers-0.309.0\dist\spec-node\devContainersSpecCLI.js:479:3660)
[2023-09-19T10:31:18.954Z]     at async GC (c:\Users\someone\.vscode\extensions\ms-vscode-remote.remote-containers-0.309.0\dist\spec-node\devContainersSpecCLI.js:479:4775)
[2023-09-19T10:31:18.954Z]     at async VeA (c:\Users\someone\.vscode\extensions\ms-vscode-remote.remote-containers-0.309.0\dist\spec-node\devContainersSpecCLI.js:611:12240)
[2023-09-19T10:31:18.954Z]     at async WeA (c:\Users\someone\.vscode\extensions\ms-vscode-remote.remote-containers-0.309.0\dist\spec-node\devContainersSpecCLI.js:611:11981)
[2023-09-19T10:31:18.972Z] Stop (2845 ms): Run: C:\Users\someone\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\someone\.vscode\extensions\ms-vscode-remote.remote-containers-0.309.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\someone\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-07b5c790-2533-49ff-8a65-9d12776720f61695119468050 --workspace-folder c:\Users\someone\projects\app1 --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\someone\projects\app1 --id-label devcontainer.config_file=c:\Users\someone\projects\app1\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\someone\projects\app1\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=\\wsl.localhost\Ubuntu-20.04\mnt\wslg\runtime-dir\wayland-0,target=/tmp/vscode-wayland-0e3c539d-fff8-4b07-beee-268f1d0b7d0e.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-09-19T10:31:18.972Z] Exit code 1
[2023-09-19T10:31:18.978Z] Command failed: C:\Users\someone\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\someone\.vscode\extensions\ms-vscode-remote.remote-containers-0.309.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\someone\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-07b5c790-2533-49ff-8a65-9d12776720f61695119468050 --workspace-folder c:\Users\someone\projects\app1 --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\someone\projects\app1 --id-label devcontainer.config_file=c:\Users\someone\projects\app1\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\someone\projects\app1\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=\\wsl.localhost\Ubuntu-20.04\mnt\wslg\runtime-dir\wayland-0,target=/tmp/vscode-wayland-0e3c539d-fff8-4b07-beee-268f1d0b7d0e.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-09-19T10:31:18.978Z] Exit code 1
```

Steps to Reproduce:

1. Open Windows folder in VsCode
2. Under remote explorer > Click New Dev Container
3. Open Current Folder in Container

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by jsunico** [comment]
After some tinkering in the settings, I found that there is a setting called "Mount Wayland Socket". By default it is enabled. Disabling it fixes the issue for me.
