### ISSUE TITLE
WSL failed to manage extensions

### ISSUE THREAD

**Issue by ZDJeffrey** [microsoft/vscode-remote-release#9004]
- VSCode Version:1.82.2 with Remote-WSL Extension 0.81.4
- Local OS Version: Microsoft Windows [Version 10.0.19045.3448]
- Remote OS Version: Ubuntu18.04(WSL 2.0.0.0 Kernel Version 5.15.123.1-1)
- Remote Extension/Connection Type: WSL 0.81.4

- Logs:
Output(Windows)
```
2023-09-20 21:16:43.677 [error] Extension 'ms-vscode.remote-server' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): resolvers, tunnelFactory
product.json (WINS): resolvers, tunnels, contribViewsWelcome
2023-09-20 21:16:43.770 [info] Invoking resolveAuthority(wsl)...
2023-09-20 21:16:43.771 [info] [LocalProcess0][resolveAuthority(wsl,1)][0ms] obtaining proxy...
2023-09-20 21:16:43.771 [info] [LocalProcess0][resolveAuthority(wsl,1)][0ms] invoking...
2023-09-20 21:16:44.542 [info] [LocalProcess0][resolveAuthority(wsl,1)][772ms] returned WebSocket(127.0.0.1:52944)
2023-09-20 21:16:44.542 [info] resolveAuthority(wsl) returned 'WebSocket(127.0.0.1:52944)' after 772 ms
2023-09-20 21:16:44.543 [info] Creating a socket (renderer-Management-e174ac90-0d8d-48cd-bd97-2c2150a60e4e)...
2023-09-20 21:16:44.544 [info] Creating a socket (renderer-ExtensionHost-94189957-e270-4e61-8e92-cf9df36bdbcb)...
2023-09-20 21:16:44.667 [info] Creating a socket (renderer-Management-e174ac90-0d8d-48cd-bd97-2c2150a60e4e) was successful after 124 ms.
2023-09-20 21:16:44.910 [info] Creating a socket (renderer-ExtensionHost-94189957-e270-4e61-8e92-cf9df36bdbcb) was successful after 367 ms.
2023-09-20 21:16:45.181 [warning] No search provider registered for scheme: vscode-remote, waiting
2023-09-20 21:16:46.098 [info] [perf] Render performance baseline is 31ms
2023-09-20 21:20:51.776 [error] Can't install 'ms-vscode.cpptools' extension because it is not compatible.: Error: Can't install 'ms-vscode.cpptools' extension because it is not compatible.
    at vscode-file://vscode-app/d:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2639:20300
    at async vscode-file://vscode-app/d:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2639:22992
2023-09-20 21:23:04.690 [info] Downloading the 'ms-vscode.cpptools' extension locally and install
2023-09-20 21:23:32.433 [info] Downloaded extension: ms-vscode.cpptools /C:/Users/Jeffrey/AppData/Roaming/Code/CachedExtensionVSIXs/ms-vscode.cpptools-1.17.5-linux-x64
2023-09-20 21:23:44.037 [info] Successfully installed 'ms-vscode.cpptools' extension
```
Output(Server)
```
2023-09-20 21:16:44.459 [info] 




2023-09-20 21:16:44.471 [info] Extension host agent started.
2023-09-20 21:16:44.677 [info] [127.0.0.1][e174ac90][ManagementConnection] New connection established.
2023-09-20 21:16:45.115 [info] [127.0.0.1][94189957][ExtensionHostConnection] New connection established.
2023-09-20 21:16:45.120 [info] [127.0.0.1][94189957][ExtensionHostConnection] <815> Launched Extension Host Process.
2023-09-20 21:23:41.832 [info] Downloaded extension to file:///home/jeffrey/.vscode-server/data/CachedExtensionVSIXs/78ed94a7-d77e-40b2-b749-631838d704ff
2023-09-20 21:23:41.879 [info] Installing extension: ms-vscode.cpptools
2023-09-20 21:23:41.879 [info] Installing the extension without checking dependencies and pack ms-vscode.cpptools
2023-09-20 21:23:41.891 [info] Deleted existing extension from disk ms-vscode.cpptools /home/jeffrey/.vscode-server/extensions/ms-vscode.cpptools-1.17.5
2023-09-20 21:23:43.991 [info] Extracted extension to file:///home/jeffrey/.vscode-server/extensions/ms-vscode.cpptools-1.17.5: ms-vscode.cpptools
2023-09-20 21:23:44.002 [info] Renamed to /home/jeffrey/.vscode-server/extensions/ms-vscode.cpptools-1.17.5
2023-09-20 21:23:44.011 [info] Extracting extension completed. ms-vscode.cpptools
2023-09-20 21:23:44.020 [info] Extension installed successfully: ms-vscode.cpptools

```

Output(Shared)
```
2023-09-20 21:16:44.143 [info] Deleted uninstalled extension from disk ms-ceintl.vscode-language-pack-zh-hans c:\Users\Jeffrey\.vscode\extensions\ms-ceintl.vscode-language-pack-zh-hans-1.82.2023091309
2023-09-20 21:16:44.206 [error] [uncaught exception in sharedProcess]: Error: ENOENT: no such file or directory, stat 'c:\Users\Jeffrey\.vscode\extensions\ms-ceintl.vscode-language-pack-zh-hans-1.82.2023091309.65ee8cd9.vsctmp': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'c:\Users\Jeffrey\.vscode\extensions\ms-ceintl.vscode-language-pack-zh-hans-1.82.2023091309.65ee8cd9.vsctmp'
    at n.create (d:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:34:30248)
    at i (d:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:34:30364)
    at t.ab (d:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:39:35344)
    at t.stat (d:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:39:28004)
    at async w.stat (d:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:39:15546)
    at async X.pb (d:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:92:9372)
2023-09-20 21:23:32.432 [info] Extension signature is verified: ms-vscode.cpptools
```

Output(Extension Host)
```
2023-09-20 21:16:43.698 [info] Extension host with pid 8 started
2023-09-20 21:16:43.698 [info] Skipping acquiring lock for c:\Users\Jeffrey\AppData\Roaming\Code\User\workspaceStorage\1ddaf7c2a72a06f09142150226bc6b64.
2023-09-20 21:16:43.704 [info] $getCanonicalURI invoked for authority (wsl)
2023-09-20 21:16:43.710 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl, startup: false, activationEvent: 'onResolveRemoteAuthority:wsl'
2023-09-20 21:16:43.771 [info] [resolveAuthority(wsl,1)][0ms] activating remote resolvers wsl+ubuntu-18.04
2023-09-20 21:16:43.771 [info] [resolveAuthority(wsl,1)][0ms] activating resolver for wsl+ubuntu-18.04...
2023-09-20 21:16:43.771 [info] [resolveAuthority(wsl,1)][0ms] invoking final resolve()...
2023-09-20 21:16:44.529 [info] [resolveAuthority(wsl,1)][757ms] setting tunnel factory...
2023-09-20 21:16:44.529 [info] [resolveAuthority(wsl,1)][757ms] returned 127.0.0.1:52944
2023-09-20 21:16:44.954 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-09-20 21:16:44.970 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2023-09-20 21:16:45.698 [info] Eager extensions activated
2023-09-20 21:16:45.700 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers, startup: false, activationEvent: 'onStartupFinished'
2023-09-20 21:16:45.773 [info] ExtensionService#_doActivateExtension ms-vscode.remote-server, startup: false, activationEvent: 'onStartupFinished'
```

Output(Extension Host(Remote))
```
2023-09-20 21:16:45.476 [info] Extension host with pid 815 started
2023-09-20 21:16:45.479 [error] Error: EEXIST: file already exists, open '/home/jeffrey/.vscode-server/data/User/workspaceStorage/1ddaf7c2a72a06f09142150226bc6b64/vscode.lock'
2023-09-20 21:16:45.488 [info] Lock '/home/jeffrey/.vscode-server/data/User/workspaceStorage/1ddaf7c2a72a06f09142150226bc6b64/vscode.lock': Could not acquire lock, checking if the file is stale.
2023-09-20 21:16:45.492 [info] Lock '/home/jeffrey/.vscode-server/data/User/workspaceStorage/1ddaf7c2a72a06f09142150226bc6b64/vscode.lock': The lockfile is scheduled to have been released.
2023-09-20 21:16:45.492 [info] Lock '/home/jeffrey/.vscode-server/data/User/workspaceStorage/1ddaf7c2a72a06f09142150226bc6b64/vscode.lock': Deleting a stale lock.
2023-09-20 21:16:45.501 [info] Lock '/home/jeffrey/.vscode-server/data/User/workspaceStorage/1ddaf7c2a72a06f09142150226bc6b64/vscode.lock': Lock acquired.
2023-09-20 21:16:45.552 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-09-20 21:16:45.553 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2023-09-20 21:16:45.553 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2023-09-20 21:16:45.888 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2023-09-20 21:16:45.906 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2023-09-20 21:16:45.906 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-09-20 21:16:46.172 [info] Eager extensions activated
2023-09-20 21:16:46.172 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-09-20 21:16:46.173 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
```

Steps to Reproduce:

1. `wsl --install --distribution Ubuntu-18.04` to install Ubuntu-18.04
2. set `"remote.downloadExtensionsLocally": true`
3. `code .` in WSL to install vscode server and open vscode
4. all extensions were unavailable because an extension(ms-ceintl.vscode-language-pack-zh-hans) is being installing
5. uninstalled ms-ceintl.vscode-language-pack-zh-hans
6. open `extensions`. It seems to be loading as the progress bar is constantly moving
7. install extension C/C++ by clicking `install in WSL:Ubuntu-18.04` and get `Can't install 'ms-vscode.cpptools' extension because it is not compatible.`Click again and successfully install.But the extension doesn't appear in the list `WSL:UBUNTU-18.04-INSTALL` although the extension's functionality is normal. At the same time ,the `install in WSL:Ubuntu-18.04` doesn't disappear.

Is there any method to enable WSL to manage extensions normally?

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by Demianeen** [comment]
Same issue, my vscode: 
Version: 1.82.2 (Universal)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:59:47.790Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

**Comment by ZDJeffrey** [comment]
It fixed after I upgraded the wsl extension to v0.81.7.
