### ISSUE TITLE
Urgent: Remothe SSH forwarder port hangs

### ISSUE THREAD

**Issue by Demianeen** [microsoft/vscode-remote-release#9010]
Type: <b>Bug</b>

I've been working on our monorepo and using our Docker dev environment as usual. Everything was running smoothly until today. I've noticed that the service running on port 4000 has started to hang. Requests are initiated, but there's no response.

What I've Tried:

- Checked the service directly on the server using curl, and it returns HTML as expected.
- Ruled out the firewall as the issue by turning it off and on.

Additional Clues:

I've found some logs in the developer tools that might be related to this issue. They mention `Invoking resolveAuthority(ssh-remote)` and show a "waiting..." status. There are also some `ECONNRESET` errors.

Your insights would be invaluable to me at this point. I'd greatly appreciate any help you can offer to get this resolved as quickly as possible.

Thank you for your time and consideration.

Additional info: 
- I used gcloud dev machine as a server

The devtools logs itself: 
```console
workbench.desktop.main.js:sourcemap:630   ERR Extension 'github.copilot-chat' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): interactive, interactiveUserActions, terminalContextMenu, terminalDataWriteEvent, terminalSelection, terminalQuickFixProvider, handleIssueUri, chatSlashCommands, readonlyMessage, chatVariables, mappedEditsProvider, aiRelatedInformation
product.json (WINS): handleIssueUri, interactive, interactiveUserActions, terminalContextMenu, terminalDataWriteEvent, terminalSelection, terminalQuickFixProvider, chatSlashCommands, readonlyMessage, mappedEditsProvider, aiRelatedInformation
workbench.desktop.main.js:sourcemap:630   ERR Extension 'ms-vscode.remote-server' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): resolvers, tunnelFactory
product.json (WINS): resolvers, tunnels, contribViewsWelcome
workbench.desktop.main.js:sourcemap:630  INFO Invoking resolveAuthority(ssh-remote)...
workbench.desktop.main.js:sourcemap:630  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] obtaining proxy...
workbench.desktop.main.js:sourcemap:630  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] invoking...
workbench.desktop.main.js:sourcemap:630  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][1000ms] waiting...
workbench.desktop.main.js:sourcemap:630  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][2026ms] waiting...
workbench.desktop.main.js:sourcemap:630  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][3009ms] waiting...
workbench.desktop.main.js:sourcemap:630  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][4001ms] waiting...
workbench.desktop.main.js:sourcemap:630  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][5002ms] waiting...
workbench.desktop.main.js:sourcemap:630   ERR [Extension Host] (node:36272) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Plugin) --trace-deprecation ...` to show where the warning was created)
workbench.desktop.main.js:sourcemap:132 [Extension Host] (node:36272) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Plugin) --trace-deprecation ...` to show where the warning was created)
m @ workbench.desktop.main.js:sourcemap:132
workbench.desktop.main.js:sourcemap:630  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][5293ms] returned WebSocket(127.0.0.1:52264)
workbench.desktop.main.js:sourcemap:630  INFO resolveAuthority(ssh-remote) returned 'WebSocket(127.0.0.1:52264)' after 5293 ms
workbench.desktop.main.js:sourcemap:630  INFO Creating a socket (renderer-Management-2711e534-c7e2-40cd-860e-565fbe2a93b1)...
workbench.desktop.main.js:sourcemap:630  INFO Creating a socket (renderer-ExtensionHost-f849da6b-e61e-433b-bd04-12a14d79cdf8)...
workbench.desktop.main.js:sourcemap:630  INFO Creating a socket (renderer-Management-2711e534-c7e2-40cd-860e-565fbe2a93b1) was successful after 274 ms.
workbench.desktop.main.js:sourcemap:630  INFO Creating a socket (renderer-ExtensionHost-f849da6b-e61e-433b-bd04-12a14d79cdf8) was successful after 537 ms.
workbench.desktop.main.js:sourcemap:630   ERR Extension 'github.copilot-chat' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): interactive, interactiveUserActions, terminalContextMenu, terminalDataWriteEvent, terminalSelection, terminalQuickFixProvider, handleIssueUri, chatSlashCommands, readonlyMessage, chatVariables, mappedEditsProvider, aiRelatedInformation
product.json (WINS): handleIssueUri, interactive, interactiveUserActions, terminalContextMenu, terminalDataWriteEvent, terminalSelection, terminalQuickFixProvider, chatSlashCommands, readonlyMessage, mappedEditsProvider, aiRelatedInformation
workbench.desktop.main.js:sourcemap:630  INFO Creating lazy extension host: contains 1 extension(s): cezaraugusto.vscode-chrome-extesion-manifest-json-schema.
webWorkerExtensionHostIframe.html:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
workbench.desktop.main.js:sourcemap:132 [Extension Host] Initializing tunnel extension
workbench.desktop.main.js:sourcemap:630   ERR Error: The editor could not be opened because the file was not found.
    at M.bc (workbench.desktop.main.js:sourcemap:2318:21886)
    at async M.setInput (workbench.desktop.main.js:sourcemap:2318:20972)
    at async s.M (workbench.desktop.main.js:sourcemap:2316:20423)
    at async s.D (workbench.desktop.main.js:sourcemap:2316:19091)
    at async s.openEditor (workbench.desktop.main.js:sourcemap:2316:18079)
    at async workbench.desktop.main.js:sourcemap:2505:12564
workbench.desktop.main.js:sourcemap:630  WARN No search provider registered for scheme: vscode-remote, waiting
workbench.desktop.main.js:sourcemap:630  INFO [perf] Render performance baseline is 17ms
workbench.desktop.main.js:sourcemap:132 [Extension Host] rejected promise not handled within 1 second: TypeError: Failed to parse URL from /home/demian_kaiku_co/.vscode-server/extensions/github.copilot-labs-0.15.1019/dist/tree-sitter.wasm
m @ workbench.desktop.main.js:sourcemap:132
workbench.desktop.main.js:sourcemap:132 [Extension Host] stack trace: TypeError: Failed to parse URL from /home/demian_kaiku_co/.vscode-server/extensions/github.copilot-labs-0.15.1019/dist/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
m @ workbench.desktop.main.js:sourcemap:132
workbench.desktop.main.js:sourcemap:630   ERR Failed to parse URL from /home/demian_kaiku_co/.vscode-server/extensions/github.copilot-labs-0.15.1019/dist/tree-sitter.wasm: TypeError: Failed to parse URL from /home/demian_kaiku_co/.vscode-server/extensions/github.copilot-labs-0.15.1019/dist/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
workbench.desktop.main.js:sourcemap:1182 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
mountTo @ workbench.desktop.main.js:sourcemap:1182
workbench.desktop.main.js:sourcemap:630   ERR Error: The editor could not be opened because the file was not found.
    at M.bc (workbench.desktop.main.js:sourcemap:2318:21886)
    at async M.setInput (workbench.desktop.main.js:sourcemap:2318:20972)
    at async s.M (workbench.desktop.main.js:sourcemap:2316:20423)
    at async s.D (workbench.desktop.main.js:sourcemap:2316:19091)
    at async s.openEditor (workbench.desktop.main.js:sourcemap:2316:18079)
    at async workbench.desktop.main.js:sourcemap:2505:12564
2workbench.desktop.main.js:sourcemap:630   ERR Canceled: Canceled
    at n.value (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:73:13079)
    at m.w (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
    at m.fire (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
    at L.cancel (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:63:5965)
    at A.cancel (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:63:6375)
    at Object.Y (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:117:9639)
    at i.I (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:117:10125)
    at i.G (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:117:8970)
    at n.value (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:117:7566)
    at m.w (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
    at m.fire (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
    at v.fire (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:79:13940)
    at n.value (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:136:7901)
    at m.w (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
    at m.fire (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
    at v.fire (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:79:13940)
    at s.z (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:79:17005)
    at n.value (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:79:15457)
    at m.w (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
    at m.fire (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
    at n.acceptChunk (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:79:11714)
    at n.value (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:79:11001)
    at m.w (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
    at m.fire (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
    at m.u (/home/demian_kaiku_co/.vscode-server/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/out/vs/workbench/api/node/extensionHostProcess.js:133:19073)
workbench.desktop.main.js:sourcemap:630   ERR [Extension Host] 2023-09-21T08:52:30.523Z [ERROR] [streamChoices] Error parsing extraData: data: {"id":"chatcmpl-819i5JUxkPDq5C7ofA9kpN0tXbqNB","object":"chat.completion.chunk","created":1695286345,"model":"copilot-chat","choices":[{"index":0,"finish_reason":null,"delta":{"content"
workbench.desktop.main.js:sourcemap:132 [Extension Host] 2023-09-21T08:52:30.523Z [ERROR] [streamChoices] Error parsing extraData: data: {"id":"chatcmpl-819i5JUxkPDq5C7ofA9kpN0tXbqNB","object":"chat.completion.chunk","created":1695286345,"model":"copilot-chat","choices":[{"index":0,"finish_reason":null,"delta":{"content"
m @ workbench.desktop.main.js:sourcemap:132
2workbench.desktop.main.js:sourcemap:630   ERR read ECONNRESET: Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
workbench.desktop.main.js:sourcemap:1182 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
mountTo @ workbench.desktop.main.js:sourcemap:1182
```

Extension version: 0.106.4
VS Code version: Code 1.82.2 (Universal) (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:59:47.790Z)
OS version: Darwin arm64 22.6.0
Modes:
Connection to 'ssh-remote+kaiku-dev' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id db2d9547-9ad9-4f2e-8928-db71d9243463|
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+kaiku-dev' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by KeithMnemonic** [comment]
I am seeing the same "waiting" message on one of my remote ssh nodes as well

**Comment by Demianeen** [comment]
For me, the bug was fixed the next day for some reason without any action from my side.
