### ISSUE TITLE
Bundled Node.js version 14.16.0 is too old, missing crypto.randomUUID

### ISSUE THREAD

**Issue by sliekens** [microsoft/vscode-remote-release#9016]
Type: <b>Bug</b>

Run `devcontainer build` from the command line

```
TypeError: JK.randomUUID is not a function
    at Bo (/home/stelie/.vscode-remote-containers/dist/dev-containers-cli-0.309.0/dist/spec-node/devContainersSpecCLI.js:479:5690)
    at async itA (/home/stelie/.vscode-remote-containers/dist/dev-containers-cli-0.309.0/dist/spec-node/devContainersSpecCLI.js:611:20980)
    at async ttA (/home/stelie/.vscode-remote-containers/dist/dev-containers-cli-0.309.0/dist/spec-node/devContainersSpecCLI.js:611:20283)
{"outcome":"error","message":"JK.randomUUID is not a function","description":"An error occurred building the container."}
```

Upgrading to pre-release (or downgrading) does not help.

```
TypeError: KK.randomUUID is not a function
    at Bo (/home/stelie/.vscode-remote-containers/dist/dev-containers-cli-0.312.0/dist/spec-node/devContainersSpecCLI.js:479:5690)
    at async rtA (/home/stelie/.vscode-remote-containers/dist/dev-containers-cli-0.312.0/dist/spec-node/devContainersSpecCLI.js:611:20980)
    at async itA (/home/stelie/.vscode-remote-containers/dist/dev-containers-cli-0.312.0/dist/spec-node/devContainersSpecCLI.js:611:20283)
{"outcome":"error","message":"KK.randomUUID is not a function","description":"An error occurred building the container."}
```

Extension version: 0.312.0
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (14.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|Memory (System)|15.54GB (13.66GB free)|
|VM|0%|
</details>

**Comment by sliekens** [comment]
After a bit more digging, I found that the extension ships with Node.js **v14.16** while `crypto.randomUUID` was added in **v14.17**.

Does anyone know why this started happening? It's totally preventing me from building dev containers.

```
$ ~/.vscode-remote-containers/bin/b3318bc0524af3d74034b8bb8a64df0ccf35549a/node --version
v14.16.0
$ tree ~/.vscode-remote-containers
/home/stelie/.vscode-remote-containers
├── bin
│   └── b3318bc0524af3d74034b8bb8a64df0ccf35549a
│       ├── LICENSE
│       ├── node
│       └── node_modules
│           └── node-pty
│               ├── build
│               │   └── Release
│               │       └── pty.node
│               ├── lib
│               │   ├── conpty_console_list_agent.js
│               │   ├── eventEmitter2.js
│               │   ├── eventEmitter2.test.js
│               │   ├── index.js
│               │   ├── interfaces.js
│               │   ├── shared
│               │   │   └── conout.js
│               │   ├── terminal.js
│               │   ├── terminal.test.js
│               │   ├── testUtils.test.js
│               │   ├── types.js
│               │   ├── unixTerminal.js
│               │   ├── unixTerminal.test.js
│               │   ├── utils.js
│               │   ├── windowsConoutConnection.js
│               │   ├── windowsPtyAgent.js
│               │   ├── windowsPtyAgent.test.js
│               │   ├── windowsTerminal.js
│               │   ├── windowsTerminal.test.js
│               │   └── worker
│               │       └── conoutSocketWorker.js
│               ├── LICENSE
│               └── package.json
└── dist
    ├── dev-containers-cli-0.309.0
    │   ├── dist
    │   │   ├── node_modules
    │   │   │   └── vscode-dev-containers
    │   │   │       └── container-features
    │   │   │           ├── devcontainer-features.json
    │   │   │           ├── feature-scripts.env
    │   │   │           ├── fish-debian.sh
    │   │   │           ├── homebrew-debian.sh
    │   │   │           └── install.sh
    │   │   └── spec-node
    │   │       └── devContainersSpecCLI.js
    │   ├── package.json
    │   └── scripts
    │       ├── bootstrap.Dockerfile
    │       ├── gitAskPass.sh
    │       ├── inspect-volume
    │       │   └── volume.Dockerfile
    │       ├── ssh-askpass.bat
    │       ├── ssh-askpass.sh
    │       └── updateUID.Dockerfile
    └── vscode-remote-containers-server-0.309.0.js

18 directories, 38 files
```
