### ISSUE TITLE
[Remote-SSH Bug]: VSCode disconnects from WSL when launching Browser Debug

### ISSUE THREAD

**Issue by eladavron** [microsoft/vscode-remote-release#9029]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Steps To Reproduce

1. With WSL over Ubuntu, launch a browser debug session (either Chrome or Edge, doesn't matter) 
1. VSCode disconnects from WSL and will not reconnect without a reload.

Initially it shows the error:
```
The extension host terminated unexpectedly.
```

Then after a few seconds this message appears:
![image](https://github.com/microsoft/vscode-remote-release/assets/5508836/0fc1e68f-c963-436e-8aa5-ee2ca9b73695)

If you hit "Cancel" you can no longer interact with the remote WSL instance through VSCode.
Hitting "Reload" reloads the window, connects to WSL, but starting the debug session again causes the same issue.

`Output` -> `Window` output:
```
2023-09-26 15:16:16.120 [error] Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.
2023-09-26 15:16:16.121 [info] Automatically restarting the extension host.
2023-09-26 15:16:16.166 [info] Creating a socket (renderer-ExtensionHost-e498d2f3-bac0-439e-be2e-b75e548fc18c)...
2023-09-26 15:16:19.918 [info] [remote-connection][Management   ][b73d5…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
2023-09-26 15:16:19.918 [error] {"isTrusted":true}
2023-09-26 15:16:19.919 [info] [remote-connection][Management   ][b73d5…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
2023-09-26 15:16:19.922 [info] [remote-connection][Management   ][b73d5…][reconnect] resolving connection...
2023-09-26 15:16:19.922 [info] Invoking resolveAuthority(wsl)...
2023-09-26 15:16:19.923 [info] [LocalProcess0][resolveAuthority(wsl,2)][0ms] obtaining proxy...
2023-09-26 15:16:19.923 [info] [LocalProcess0][resolveAuthority(wsl,2)][1ms] invoking...
2023-09-26 15:16:20.952 [info] [LocalProcess0][resolveAuthority(wsl,2)][1030ms] waiting...
2023-09-26 15:16:21.937 [info] [LocalProcess0][resolveAuthority(wsl,2)][2015ms] waiting...
2023-09-26 15:16:22.935 [info] [LocalProcess0][resolveAuthority(wsl,2)][3013ms] waiting...
2023-09-26 15:16:23.169 [info] Creating a socket (renderer-ExtensionHost-e498d2f3-bac0-439e-be2e-b75e548fc18c) returned an error after 7036 ms.
2023-09-26 15:16:23.169 [error] CodeExpectedError: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:661:3986)
2023-09-26 15:16:23.170 [error] [remote-connection][ExtensionHost][e498d…][initial][WebSocket(127.0.0.1:50098)] socketFactory.connect() failed or timed out. Error:
2023-09-26 15:16:23.170 [error] CodeExpectedError: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:661:3986)
2023-09-26 15:16:23.171 [error] [remote-connection][attempt 1] An error occurred in initial connection! Will retry... Error:
2023-09-26 15:16:23.172 [error] CodeExpectedError: WebSocket close with status code 1006
    at WebSocket.<anonymous> (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:661:3986)
2023-09-26 15:16:23.936 [info] [LocalProcess0][resolveAuthority(wsl,2)][4014ms] waiting...
2023-09-26 15:16:24.935 [info] [LocalProcess0][resolveAuthority(wsl,2)][5013ms] waiting...
2023-09-26 15:16:25.935 [info] [LocalProcess0][resolveAuthority(wsl,2)][6013ms] waiting...
2023-09-26 15:16:26.306 [info] [LocalProcess0][resolveAuthority(wsl,2)][6384ms] returned WebSocket(127.0.0.1:51051)
2023-09-26 15:16:26.307 [info] resolveAuthority(wsl) returned 'WebSocket(127.0.0.1:51051)' after 6385 ms
2023-09-26 15:16:26.308 [info] [remote-connection][Management   ][b73d5…][reconnect] connecting to WebSocket(127.0.0.1:51051)...
2023-09-26 15:16:26.308 [info] Creating a socket (renderer-Management-b73d534c-029c-47ec-a41c-401968c1e799)...
2023-09-26 15:16:26.309 [info] Creating a socket (renderer-ExtensionHost-98d60009-3fde-4b5f-a9de-53a0ed772619)...
2023-09-26 15:16:26.914 [info] Creating a socket (renderer-Management-b73d534c-029c-47ec-a41c-401968c1e799) was successful after 605 ms.
2023-09-26 15:16:27.060 [error] [remote-connection][Management   ][b73d5…][reconnect][WebSocket(127.0.0.1:51051)] received error control message when negotiating connection. Error:
2023-09-26 15:16:27.060 [error] Error: Connection error: Unknown reconnection token (never seen)
    at H (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:661:23126)
    at o.value (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:661:14747)
    at f.w (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:70:1902)
    at f.fire (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:70:2119)
    at r.fire (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:599:14152)
    at b.z (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:599:17251)
    at o.value (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:599:16622)
    at f.w (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:70:1902)
    at f.fire (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:70:2119)
    at o.acceptChunk (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:599:11926)
    at vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:599:11213
    at o.value (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:661:4918)
    at f.w (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:70:1902)
    at f.fire (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:70:2119)
    at i.onload (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:661:3302)
2023-09-26 15:16:27.061 [error] [remote-connection][Management   ][b73d5…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
2023-09-26 15:16:27.061 [error] Error: Connection error: Unknown reconnection token (never seen)
    at H (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:661:23126)
    at o.value (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:661:14747)
    at f.w (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:70:1902)
    at f.fire (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:70:2119)
    at r.fire (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:599:14152)
    at b.z (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:599:17251)
    at o.value (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:599:16622)
    at f.w (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:70:1902)
    at f.fire (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:70:2119)
    at o.acceptChunk (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:599:11926)
    at vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:599:11213
    at o.value (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:661:4918)
    at f.w (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:70:1902)
    at f.fire (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:70:2119)
    at i.onload (vscode-file://vscode-app/c:/Users/eavron/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:661:3302)
2023-09-26 15:16:27.551 [info] Creating a socket (renderer-ExtensionHost-98d60009-3fde-4b5f-a9de-53a0ed772619) was successful after 1242 ms.
2023-09-26 15:17:27.628 [error] Error received from starting extension host (kind: Remote)
2023-09-26 15:17:27.629 [error] The remote extension host took longer than 60s to send its ready message.
```

### Remote-SSH Log

No such option in logs

### Anything else?

Here are the `launch.json` settings I'm using:

```json
{
    "name": "Launch Chrome",
    "request": "launch",
    "type": "chrome",
    "url": "http://127.0.0.1:8080",
    "webRoot": "${workspaceFolder}/app/static/"
},
{
    "name": "Launch Edge",
    "request": "launch",
    "type": "msedge",
    "url": "http://127.0.0.1:8080",
    "webRoot": "${workspaceFolder}/app/static/"
},
```

**Comment by joshspicer** [comment]
I cannot repro this anymore, so hopefully it has resolved over time.  

Please feel free to open a new issue with a current copy of the logs if you can still reproduce, thank you.
