### ISSUE TITLE
Latest Update: Failed to load message bundle (HTML language server)

### ISSUE THREAD

**Issue by razilevin** [microsoft/vscode-remote-release#904]
Updated to
```
Version: 1.37.0-insider
Commit: 3a87cea73dfaf923bf5baa3318f971d854785d1d
Date: 2019-07-04T10:34:40.391Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-20-generic
```

Causes the following issues logged in the console
```
nternal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:460536)
    at n (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:220)
    at Object.<anonymous> (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:452776)
    at n (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:220)
    at Object.<anonymous> (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:450430)
    at n (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:220)
[Info  - 3:40:33 PM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:460536)
    at n (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:220)
    at Object.<anonymous> (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:452776)
    at n (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:220)
    at Object.<anonymous> (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:450430)
    at n (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:220)
[Info  - 3:40:34 PM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:460536)
    at n (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:220)
    at Object.<anonymous> (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:452776)
    at n (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:220)
    at Object.<anonymous> (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:450430)
    at n (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:220)
[Info  - 3:40:34 PM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:460536)
    at n (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:220)
    at Object.<anonymous> (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:452776)
    at n (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:220)
    at Object.<anonymous> (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:450430)
    at n (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:220)
[Info  - 3:40:34 PM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:460536)
    at n (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:220)
    at Object.<anonymous> (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:452776)
    at n (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:220)
    at Object.<anonymous> (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:450430)
    at n (/root/.vscode-server-insiders/bin/3a87cea73dfaf923bf5baa3318f971d854785d1d/extensions/html-language-features/server/dist/htmlServerMain.js:1:220)
[Error - 3:40:34 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by egamma** [comment]
@razilevin the insider build had some issues can you please try to reproduce on a newer insider build.
