### ISSUE TITLE
Suddenly: No remote extension installed to resolve wsl when trying to start a Dev-Container in WSL2

### ISSUE THREAD

**Issue by Roemer** [microsoft/vscode-remote-release#9067]
Type: <b>Bug</b>

Today, without changing anything, I can suddenly not connect to any remote container running inside WSL2 anymore.
Connecting to WSL2 works fine and uppon choosing "Reopen in container", it ends in "Disconnected from Dev Container" and the log shows:
```
2023-10-05 12:38:06.985 [warning] No search provider registered for scheme: vscode-remote, waiting
2023-10-05 12:38:18.996 [error] Extension 'ms-vscode.remote-server' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): resolvers, tunnelFactory
product.json (WINS): resolvers, tunnels, contribViewsWelcome
2023-10-05 12:38:20.071 [info] Invoking resolveAuthority(dev-container)...
2023-10-05 12:38:20.071 [info] [LocalProcess0][resolveAuthority(dev-container,1)][0ms] obtaining proxy...
2023-10-05 12:38:20.072 [info] [LocalProcess0][resolveAuthority(dev-container,1)][0ms] invoking...
2023-10-05 12:38:20.142 [error] [LocalProcess0][resolveAuthority(dev-container,1)][71ms] returned an error {"code":"NoResolverFound","message":"No remote extension installed to resolve wsl."}
2023-10-05 12:38:20.143 [error] resolveAuthority(dev-container) returned an error after 71 ms No remote extension installed to resolve wsl.
2023-10-05 12:38:20.144 [error] Error received from starting extension host (kind: Remote)
2023-10-05 12:38:20.144 [error] CodeExpectedError: No remote extension installed to resolve wsl.
    at Y.rb (vscode-file://vscode-app/c:/appl/scoop/apps/vscode/1.83.0/resources/app/out/vs/workbench/workbench.desktop.main.js:2656:21247)
    at async Y.qb (vscode-file://vscode-app/c:/appl/scoop/apps/vscode/1.83.0/resources/app/out/vs/workbench/workbench.desktop.main.js:2656:20506)
    at async Y.Ob (vscode-file://vscode-app/c:/appl/scoop/apps/vscode/1.83.0/resources/app/out/vs/workbench/workbench.desktop.main.js:2657:11479)
    at async Y.jb (vscode-file://vscode-app/c:/appl/scoop/apps/vscode/1.83.0/resources/app/out/vs/workbench/workbench.desktop.main.js:2656:18089)
```
I just completely reinstalled vscode (from scoop) and deleted all extension/settings but still the same.

Extension version: 0.24.0
VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.19045
Modes: Dev-Container inside WSL2

**Comment by Roemer** [comment]
Closing this issue as this is already tracked in: https://github.com/microsoft/vscode-remote-release/issues/9060

**Comment by chrmarti** [comment]
@Roemer https://github.com/microsoft/vscode-remote-release/issues/9060 is fixed in 0.315.1 and 0.317.0-pre-release. Could you give one of these a try and let me know if you still see the `CodeExpectedError: No remote extension installed to resolve wsl.` error. Thanks!

**Comment by Roemer** [comment]
Perfect, 0.315.1 fixes it for me. Thanks!
