### ISSUE TITLE
Version 0.315.0 unable to start a container from WSL

### ISSUE THREAD

**Issue by alan-davies-se** [microsoft/vscode-remote-release#9068]
To reproduce:

- In WSL create a default cpp devcontainer and try and load it

The devcontainer fails to build/load 

I have just rolled back to v0.309.0 and the issue has gone away.

Logs from the `Window Output`:

2023-10-05 12:44:22.536 [error] [LocalProcess0][resolveAuthority(dev-container,1)][24ms] returned an error {"code":"NoResolverFound","message":"No remote extension installed to resolve wsl."}
2023-10-05 12:44:22.536 [error] resolveAuthority(dev-container) returned an error after 24 ms No remote extension installed to resolve wsl.
2023-10-05 12:44:22.536 [error] Error received from starting extension host (kind: Remote)
2023-10-05 12:44:22.536 [error] CodeExpectedError: No remote extension installed to resolve wsl.
    at Y.rb (vscode-file://vscode-app/c:/Users/sesa615812/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2656:21247)
    at async Y.qb (vscode-file://vscode-app/c:/Users/sesa615812/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2656:20506)
    at async Y.Ob (vscode-file://vscode-app/c:/Users/sesa615812/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2657:11479)
    at async Y.jb (vscode-file://vscode-app/c:/Users/sesa615812/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2656:18089)
2023-10-05 12:44:22.537 [error] [remote-connection][attempt 1] An error occurred in initial connection! Will retry...

**Comment by SaschaSchwarz** [comment]
Give v0.315.1 a try, which apparently fixed the issue for me.

**Comment by alan-davies-se** [comment]
> Give v0.315.1 a try, which apparently fixed the issue for me.

Excellent all looks good now, thanks, I will close this ticket.
