### ISSUE TITLE
[Remote-SSH Bug]: 

### ISSUE THREAD

**Issue by alsace1986** [microsoft/vscode-remote-release#9085]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Remote-SSH Log

[19:36:09.710] Log Level: 2
[19:36:09.722] SSH Resolver called for "ssh-remote+192.168.201.134", attempt 1
[19:36:09.723] "remote.SSH.useLocalServer": false
[19:36:09.723] "remote.SSH.useExecServer": false
[19:36:09.725] "remote.SSH.showLoginTerminal": false
[19:36:09.726] "remote.SSH.remotePlatform": {}
[19:36:09.726] "remote.SSH.path": undefined
[19:36:09.726] "remote.SSH.configFile": undefined
[19:36:09.726] "remote.SSH.useFlock": true
[19:36:09.726] "remote.SSH.lockfilesInTmp": false
[19:36:09.726] "remote.SSH.localServerDownload": auto
[19:36:09.726] "remote.SSH.remoteServerListenOnSocket": false
[19:36:09.727] "remote.SSH.showLoginTerminal": false
[19:36:09.727] "remote.SSH.defaultExtensions": []
[19:36:09.727] "remote.SSH.loglevel": 2
[19:36:09.727] "remote.SSH.enableDynamicForwarding": true
[19:36:09.727] "remote.SSH.enableRemoteCommand": false
[19:36:09.727] "remote.SSH.serverPickPortsFromRange": {}
[19:36:09.728] "remote.SSH.serverInstallPath": {}
[19:36:09.733] VS Code version: 1.83.0
[19:36:09.733] Remote-SSH version: remote-ssh@0.106.5
[19:36:09.733] win32 x64
[19:36:09.734] SSH Resolver called for host: 192.168.201.134
[19:36:09.734] Setting up SSH remote "192.168.201.134"
[19:36:09.739] Using commit id "e7e037083ff4455cf320e344325dacb480062c3c" and quality "stable" for server
[19:36:09.743] Install and start server if needed
[19:36:10.849] Checking ssh with "C:\Users\User\Desktop\КТИ\bin\ssh.exe -V"
[19:36:10.851] Got error from ssh: spawn C:\Users\User\Desktop\КТИ\bin\ssh.exe ENOENT
[19:36:10.851] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[19:36:10.852] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[19:36:10.852] Checking ssh with "C:\Windows\ssh.exe -V"
[19:36:10.852] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[19:36:10.852] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[19:36:10.853] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[19:36:10.853] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[19:36:10.854] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[19:36:10.854] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[19:36:10.878] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[19:36:10.881] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 51868 "192.168.201.134" bash
[19:36:10.882] Terminal shell path: C:\Windows\System32\cmd.exe
[19:36:11.085] > ]0;C:\Windows\System32\cmd.exe
[19:36:11.085] Got some output, clearing connection timeout
[19:36:22.379] > 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
[19:36:32.119] > ssh: connect to host 192.168.201.134 port 22: Connection timed out
[19:36:32.135] > Попытка записи в несуществующий канал.
[19:36:33.387] "install" terminal command done
[19:36:33.387] Install terminal quit with output: Попытка записи в несуществующий канал.
[19:36:33.388] Received install output: Попытка записи в несуществующий канал.
[19:36:33.389] Failed to parse remote port from server output
[19:36:33.392] Resolver error: Error: 
	at g.Create (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:640937)
	at t.handleInstallOutput (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:638303)
	at t.tryInstall (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:760218)
	at async c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:720757
	at async t.withShowDetailsEvent (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:724063)
	at async I (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:717728)
	at async t.resolve (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:721434)
	at async c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:905238
[19:36:33.412] ------

### Anything else?

help me please

i cant connect vm ware to vsc

**Comment by bamurtaugh** [comment]
Can you please provide more info, such as how you try to connect, local and remote OS, and any error you see in the UI? Thanks!
