### ISSUE TITLE
Can't add configuration files

### ISSUE THREAD

**Issue by suharnikov** [microsoft/vscode-remote-release#9102]
- VSCode Version: 1.83.1 f1b07bd25dfad64b0167beb15359ae573aecd2cc x64
- Local OS Version: Linux fortday 6.5.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 10 Oct 2023 21:10:21 +0000 x86_64 GNU/Linux
- Remote OS Version: None
- Remote Extension/Connection Type: Containers

- Logs:
  - Extension host:

  ```logs
  2023-10-14 16:38:09.976 [error] TypeError: Cannot read properties of undefined (reading 'files')
      at r$ (/home/kosto/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/extension/extension.js:293:39361)
      at processTicksAndRejections (node:internal/process/task_queues:95:5) remote-containers.createDevContainerFile {"value":"ms-vscode-remote.remote-containers","_lower":"ms-vscode-remote.remote-containers"}
  ```
  - extension:
  ```logs
  [2023-10-14T12:37:54.052Z] Dev Containers 0.315.1 in VS Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc).
  [2023-10-14T12:37:54.052Z]  -- CREATEDEVCONTAINER v2
  [2023-10-14T12:38:01.443Z] Start: Run: /opt/visual-studio-code/code --ms-enable-electron-run-as-node /home/kosto/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js templates apply --workspace-folder /tmp/tmp-output-dir-1697287081441 --template-id ghcr.io/devcontainers/templates/rust:latest --template-args {"imageVariant":"bookworm"} --features [] --tmp-dir /tmp/tmp-dir-1697287081441
  [2023-10-14T12:38:01.569Z] [2023-10-14T12:38:01.568Z] @devcontainers/cli 0.51.3. Node.js v18.15.0. linux 6.5.7-arch1-1 x64.
  [2023-10-14T12:38:09.969Z] [2023-10-14T12:38:09.969Z] Error getting blob: Error: connect EHOSTUNREACH 2606:50c0:8002::154:443
  [2023-10-14T12:38:09.970Z] Error: Failed to download package for ghcr.io/devcontainers/templates/rust
  [2023-10-14T12:38:09.970Z]     at s1 (/home/kosto/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:604:6751)
  [2023-10-14T12:38:09.970Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  [2023-10-14T12:38:09.970Z]     at async HeA (/home/kosto/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:604:9683)
  [2023-10-14T12:38:09.971Z]     at async /home/kosto/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:604:9118
  [2023-10-14T12:38:09.975Z] Stop (8532 ms): Run: /opt/visual-studio-code/code --ms-enable-electron-run-as-node /home/kosto/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js templates apply --workspace-folder /tmp/tmp-output-dir-1697287081441 --template-id ghcr.io/devcontainers/templates/rust:latest --template-args {"imageVariant":"bookworm"} --features [] --tmp-dir /tmp/tmp-dir-1697287081441
  ```

Steps to Reproduce:

1. In Command Palette run `Add dev configuration files`
2. Select Rust image without features.

![image](https://github.com/microsoft/vscode-remote-release/assets/1702003/f40c15d8-05b4-4ee0-930b-67811308f356)

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by suharnikov** [comment]
Is it normal that the address is ipv6? `2606:50c0:8002::154:443`

**Comment by materod-upv** [comment]
Hi, 

I believe that the extensions don't work with IPv6. You can probably disable it from the network adapter

**Comment by suharnikov** [comment]
I don't face the bug anymore. So I guess we can close the issue.
