### ISSUE TITLE
[Remote-SSH Bug]: 

### ISSUE THREAD

**Issue by andrea-begnoni** [microsoft/vscode-remote-release#9113]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

When I try to connect from VSCode from my machine to my remote host it does not work and I received the error I paste down there.

I receive the same error from two different PCs and everything worked like a charm till few hours ago. I have WSL and it connects with no issue while from Powershell I need to run `ssh -m hmac-sha2-512-etm@openssh.com <server_name>` to make it work.

This problem appears from 2 PCs and trying to connect with 2 different remotes, while ssh works from WSL and Powershell

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[20:26:19.453] Log Level: 2
[20:26:19.462] SSH Resolver called for "ssh-remote+almond_tree", attempt 1
[20:26:19.463] "remote.SSH.useLocalServer": false
[20:26:19.463] "remote.SSH.useExecServer": false
[20:26:19.463] "remote.SSH.showLoginTerminal": false
[20:26:19.464] "remote.SSH.remotePlatform": {"gate_recas":"linux","almond_tree":"linux","hpc-gpu-1-4-3.recas.ba.infn.it":"linux"}
[20:26:19.464] "remote.SSH.path": undefined
[20:26:19.464] "remote.SSH.configFile": undefined
[20:26:19.464] "remote.SSH.useFlock": true
[20:26:19.464] "remote.SSH.lockfilesInTmp": false
[20:26:19.465] "remote.SSH.localServerDownload": auto
[20:26:19.465] "remote.SSH.remoteServerListenOnSocket": false
[20:26:19.466] "remote.SSH.showLoginTerminal": false
[20:26:19.467] "remote.SSH.defaultExtensions": []
[20:26:19.467] "remote.SSH.loglevel": 2
[20:26:19.467] "remote.SSH.enableDynamicForwarding": true
[20:26:19.467] "remote.SSH.enableRemoteCommand": false
[20:26:19.467] "remote.SSH.serverPickPortsFromRange": {}
[20:26:19.467] "remote.SSH.serverInstallPath": {}
[20:26:19.471] VS Code version: 1.83.1
[20:26:19.471] Remote-SSH version: remote-ssh@0.106.5
[20:26:19.471] win32 x64
[20:26:19.475] SSH Resolver called for host: almond_tree
[20:26:19.475] Setting up SSH remote "almond_tree"
[20:26:19.478] Using commit id "f1b07bd25dfad64b0167beb15359ae573aecd2cc" and quality "stable" for server
[20:26:19.480] Install and start server if needed
[20:26:19.482] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[20:26:19.484] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[20:26:19.484] Checking ssh with "C:\Windows\ssh.exe -V"
[20:26:19.485] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[20:26:19.485] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[20:26:19.486] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[20:26:19.486] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[20:26:19.487] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[20:26:19.487] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[20:26:19.514] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[20:26:19.519] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 52701 "almond_tree" bash
[20:26:19.521] Terminal shell path: C:\Windows\System32\cmd.exe
[20:26:19.837] > Corrupted MAC on input.
> ssh_dispatch_run_fatal: Connection to 90.147.77.122 port 22: message authentication code incorrect
> kex_exchange_identification: Connection closed by remote host
> Connection closed by UNKNOWN port 65535
> The process tried to write to a nonexistent pipe.
> ]0;C:\Windows\System32\cmd.exe
[20:26:19.838] Got some output, clearing connection timeout
[20:26:21.100] "install" terminal command done
[20:26:21.100] Install terminal quit with output: ]0;C:\Windows\System32\cmd.exe
[20:26:21.100] Received install output: ]0;C:\Windows\System32\cmd.exe
[20:26:21.101] Failed to parse remote port from server output
[20:26:21.104] Resolver error: Error: 
	at g.Create (c:\Users\andre\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:640937)
	at t.handleInstallOutput (c:\Users\andre\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:638303)
	at t.tryInstall (c:\Users\andre\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:760218)
	at async c:\Users\andre\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:720757
	at async t.withShowDetailsEvent (c:\Users\andre\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:724063)
	at async I (c:\Users\andre\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:717728)
	at async t.resolve (c:\Users\andre\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:721434)
	at async c:\Users\andre\.vscode\extensions\ms-vscode-remote.remote-ssh-0.106.5\out\extension.js:2:905238
[20:26:21.110] ------

```

</p>
</details>

### Anything else?

Thank in advance for any help

**Comment by roblourens** [comment]
> `message authentication code incorrect`

This is just an error from ssh, I don't think there's anything the extension can do. If you search around for this error message, you may find some tips.

**Comment by andrea-begnoni** [comment]
Ok thank you anyway, have a nice day
