### ISSUE TITLE
[Remote-SSH Bug]:  vscode server fails to install, 404

### ISSUE THREAD

**Issue by 0xphk** [microsoft/vscode-remote-release#9133]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### Expected Behavior

The local client or the remote (depending on setting) successfully downloads the server and vscode is able to connect.

### Steps To Reproduce

Download URL for vs-code server returns a 404, see attached log. I've only found #6804 but it was solved in 2022.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[22:10:45.325] Log Level: 2
[22:10:45.326] SSH Resolver called for "ssh-remote+target", attempt 1
[22:10:45.327] "remote.SSH.useLocalServer": true
[22:10:45.327] "remote.SSH.useExecServer": false
[22:10:45.327] "remote.SSH.path": undefined
[22:10:45.327] "remote.SSH.configFile": ~/.ssh/config
[22:10:45.327] "remote.SSH.useFlock": true
[22:10:45.327] "remote.SSH.lockfilesInTmp": false
[22:10:45.327] "remote.SSH.localServerDownload": auto
[22:10:45.327] "remote.SSH.remoteServerListenOnSocket": false
[22:10:45.327] "remote.SSH.showLoginTerminal": false
[22:10:45.328] "remote.SSH.defaultExtensions": []
[22:10:45.328] "remote.SSH.loglevel": 2
[22:10:45.328] "remote.SSH.enableDynamicForwarding": true
[22:10:45.328] "remote.SSH.enableRemoteCommand": false
[22:10:45.328] "remote.SSH.serverPickPortsFromRange": {}
[22:10:45.328] "remote.SSH.serverInstallPath": {}
[22:10:45.331] VS Code version: 1.83.1
[22:10:45.331] Remote-SSH version: remote-ssh@0.106.5
[22:10:45.331] linux x64
[22:10:45.334] SSH Resolver called for host: target
[22:10:45.335] Setting up SSH remote "target"
[22:10:45.339] Acquiring local install lock: /tmp/vscode-remote-ssh-4ee90310-install.lock
[22:10:45.340] Looking for existing server data file at /home/$user/.config/VSCodium/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-4ee90310-36d13de33ac0d6c684f10f99cff352e2f58228b3-0.106.5-tr/data.json
[22:10:45.341] Using commit id "36d13de33ac0d6c684f10f99cff352e2f58228b3" and quality "stable" for server
[22:10:45.346] Install and start server if needed
[22:10:45.349] PATH: /home/$user/bin:/home/$user/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin
[22:10:45.349] Checking ssh with "ssh -V"
[22:10:45.356] > OpenSSH_9.5p1, OpenSSL 3.1.3 19 Sep 2023

[22:10:45.360] Using SSH config file "/home/phk/.ssh/config"
[22:10:45.360] askpass server listening on /run/user/1000/vscode-ssh-askpass-f6feef2a6292825b838e8a4e6dc446de863097fb.sock
[22:10:45.360] Spawning local server with {"serverId":1,"ipcHandlePath":"/run/user/1000/vscode-ssh-askpass-7650889bfcc6a24185f062a291db48b1f7d4a995.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","45329","-o","ConnectTimeout=15","-F","/home/$user/.ssh/config","target"],"serverDataFolderName":".vscode-server","dataFilePath":"/home/$user/.config/VSCodium/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-4ee90310-36d13de33ac0d6c684f10f99cff352e2f58228b3-0.106.5-tr/data.json"}
[22:10:45.360] Local server env: {"SHELL":"/bin/bash","DISPLAY":":0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/home/$user/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.106.5/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/opt/vscodium-bin/codium","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/home/$user/.vscode-oss/extensions/ms-vscode-remote.remote-ssh-0.106.5/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/run/user/1000/vscode-ssh-askpass-f6feef2a6292825b838e8a4e6dc446de863097fb.sock"}
[22:10:45.364] Spawned 837788
[22:10:45.451] > local-server-1> Running ssh connection command: "-v -T -D 45329 -o ConnectTimeout=15 -F /home/$user/.ssh/config target"
[22:10:45.454] > local-server-1> Spawned ssh, pid=837796
[22:10:45.457] stderr> OpenSSH_9.5p1, OpenSSL 3.1.3 19 Sep 2023
[22:10:45.897] stderr> debug1: Server host key: [sanitized]
[22:10:46.129] stderr> Authenticated to target ([sanitized]) using "publickey".
[22:10:47.697] > Linux target 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64
[22:10:47.744] > ready: 1cfd820e4c9e
[22:10:47.783] > Linux 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29)
[22:10:47.784] Platform: linux
[22:10:47.830] > /bin/bash
[22:10:47.830] Shell: bash
[22:10:47.831] Creating bash subshell inside "bash"
[22:10:47.876] > bash version:  5.1.4(1)-release
[22:10:47.996] > 1cfd820e4c9e: running
[22:10:48.027] > Acquiring lock on /root/.vscode-server/bin/36d13de33ac0d6c684f10f99cff352e2f58228b3/vscode-remote-lock.root.36d13de33ac0d6c684f10f99cff352e2f58228b3
[22:10:48.032] > Installing to /root/.vscode-server/bin/36d13de33ac0d6c684f10f99cff352e2f58228b3...
[22:10:48.038] > 1cfd820e4c9e%%1%%
[22:10:48.044] > Downloading with wget
[22:10:48.123] > wget download failed
> https://update.code.visualstudio.com/commit:36d13de33ac0d6c684f10f99cff352e2f58228b3/server-linux-x64/stable: 2023-10-25 22:10:29 ERROR 404: Not Found.
> printenv:
[22:10:48.128] >     SHELL=/bin/bash
>     HISTCONTROL=ignoreboth
>     HISTSIZE=1000000
>     LANGUAGE=en_US:en
>     PWD=/root/.vscode-server/bin/36d13de33ac0d6c684f10f99cff352e2f58228b3
>     LOGNAME=root
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/root
>     VSCODE_AGENT_FOLDER=/root/.vscode-server
>     SSH_CONNECTION=[sanitized]
>     XDG_SESSION_CLASS=user
>     TERM=xterm-256color
>     USER=root
>     SHLVL=1
>     XDG_SESSION_ID=46748
>     XDG_RUNTIME_DIR=/run/user/0
>     SSH_CLIENT=[sanitized]
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/influxdb:/opt/bin:/var/www/nextcloud
>     HISTIGNORE=ls:history
>     HISTFILESIZE=1000000
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/0/bus
>     OLDPWD=/root
>     _=/usr/bin/printenv
> Trigger local server download
> 1cfd820e4c9e:trigger_server_download
> artifact==server-linux-x64==
> destFolder==/root/.vscode-server/bin/==
> destFolder2==/36d13de33ac0d6c684f10f99cff352e2f58228b3/vscode-server.tar.gz==
> 1cfd820e4c9e:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /root/.vscode-server/bin/36d13de33ac0d6c684f10f99cff352e2f58228b3/vscode-server.tar.gz.done and vscode-server.tar.gz to exist
>  
[22:10:48.129] Got request to download on client for {"artifact":"server-linux-x64","destPath":"/root/.vscode-server/bin//36d13de33ac0d6c684f10f99cff352e2f58228b3/vscode-server.tar.gz"}
[22:10:48.130] Downloading VS Code server locally...
[22:10:48.390] Terminating local server
[22:10:48.392] Resolver error: Error: Server returned 404
    at h (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:676:36488)
    at T.download (vscode-file://vscode-app/opt/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:677:1873)
[22:10:48.400] ------
[22:10:48.410] Local server exit: 15
```

</p>
</details>

**Comment by roblourens** [comment]
vscodium isn't supported
