### ISSUE TITLE
Can't start container over SSH

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-remote-release#9134]
Testing #9123

Not sure what this error means. Just going through the steps with "reopen in container" over SSH. No problems opening the container locally.

```
[15375 ms] Dev Containers 0.319.0 in VS Code 1.84.0-insider (18b7f75a9fab40499744c2e9c6ba9af64d5c6744).
[15374 ms] Start: Resolving Remote
[15419 ms] Start: Run: powershell -NoProfile -Command -
[15438 ms] Start: Run in host: echo $env:userprofile
[17007 ms] C:\Users\roblou
[17008 ms] 
[17016 ms] Setting up container for folder or workspace: c:\Users\roblou\code\searchtest
[17016 ms] Host authority: ssh-remote+me
[17018 ms] Start: Run: wsl -l -v
[17112 ms] Start: Run: wsl -d openSUSE-Leap-15-1 -e /bin/sh -c echo ~
[17448 ms] Start: Run: wsl -d openSUSE-Leap-15-1 -e /bin/sh -c cd '/home/rob' && /bin/sh
[17471 ms] Start: Run in host: id -un
[17691 ms] rob
[17692 ms] 
[17694 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'rob' || grep -E '^rob|^[^:]*:[^:]*:rob:' /etc/passwd || true)
[17716 ms] Start: Run in host: echo ~
[17719 ms] /home/rob
[17719 ms] 
[17720 ms] Start: Run in host: test -x '/home/rob/.vscode-remote-containers/bin/18b7f75a9fab40499744c2e9c6ba9af64d5c6744/node'
[17722 ms] 
[17722 ms] 
[17723 ms] Start: Run in host: test -f '/home/rob/.vscode-remote-containers/dist/vscode-remote-containers-server-0.319.0.js'
[17726 ms] 
[17726 ms] 
[17755 ms] userEnvProbe: loginInteractiveShell (default)
[17765 ms] userEnvProbe: not found in cache
[17775 ms] userEnvProbe shell: /bin/bash
[19421 ms] userEnvProbe PATHs:
Probe:     '/home/rob/.nvm/versions/node/v18.12.1/bin:/home/rob/bin:/usr/local/bin:/usr/bin:/bin'
Container: None
[19426 ms] Start: Check Docker is running
[19426 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[20032 ms] Server API version: 1.41
[20033 ms] Start: Run: docker volume ls -q
[20609 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=c:\Users\roblou\code\searchtest --filter label=vsch.quality=insider
[21110 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\roblou\code\searchtest --filter label=devcontainer.config_file=c:\Users\roblou\code\searchtest\.devcontainer\devcontainer.json
[22632 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\roblou\code\searchtest
[23180 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\roblou\code\searchtest
[23697 ms] Start: Run: C:\Users\roblou\.vscode-server-insiders\cli\servers\Insiders-18b7f75a9fab40499744c2e9c6ba9af64d5c6744\server\node.exe C:\Users\roblou\.vscode-remote-containers\dist\dev-containers-cli-0.319.0\dist\spec-node\devContainersSpecCLI.js read-configuration --workspace-folder c:\Users\roblou\code\searchtest --id-label devcontainer.local_folder=c:\Users\roblou\code\searchtest --id-label devcontainer.config_file=c:\Users\roblou\code\searchtest\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\roblou\code\searchtest\.devcontainer\devcontainer.json --mount-workspace-git-root
[24055 ms] @devcontainers/cli 0.52.1. Node.js v18.15.0. win32 10.0.19043 x64.
[24055 ms] Start: Run: git rev-parse --show-cdup
[24222 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\roblou\code\searchtest --filter label=devcontainer.config_file=c:\Users\roblou\code\searchtest\.devcontainer\devcontainer.json
[24754 ms] Start: Run: C:\Users\roblou\.vscode-server-insiders\cli\servers\Insiders-18b7f75a9fab40499744c2e9c6ba9af64d5c6744\server\node.exe C:\Users\roblou\.vscode-remote-containers\dist\dev-containers-cli-0.319.0\dist\spec-node\devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-d91b5610-5486-4783-a231-ed20552d83741698272336805 --workspace-folder c:\Users\roblou\code\searchtest --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\roblou\code\searchtest --id-label devcontainer.config_file=c:\Users\roblou\code\searchtest\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\roblou\code\searchtest\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[25074 ms] @devcontainers/cli 0.52.1. Node.js v18.15.0. win32 10.0.19043 x64.
[25074 ms] Start: Run: docker buildx version
[26701 ms] github.com/docker/buildx v0.5.1-docker 11057da37336192bfc57d81e02359ba7ba848e4a
[26702 ms] 
[26702 ms] Start: Resolving Remote
[26708 ms] Start: Run: git rev-parse --show-cdup
[26894 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\roblou\code\searchtest --filter label=devcontainer.config_file=c:\Users\roblou\code\searchtest\.devcontainer\devcontainer.json
[27705 ms] Start: Run: docker inspect --type image node:18
[28748 ms] Start: Run: docker-credential-desktop get
[30105 ms] local container features stored at: C:\Users\roblou\.vscode-remote-containers\dist\dev-containers-cli-0.319.0\dist\node_modules\vscode-dev-containers\container-features
[30107 ms] Start: Run: tar --no-same-owner -x -f -
[30180 ms] Start: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\roblou\AppData\Local\Temp\devcontainercli\container-features\0.52.1-1698272370788\Dockerfile-with-features -t vsc-searchtest-d1eb35eb7f7b82066feaed3520e31512c24cc4534388e9fa122a50e181840511 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label c:\Users\roblou\code\searchtest\.devcontainer

[+] Building 0.9s (3/3) FINISHED
 => [internal] load build definition from Dockerfile-with-features         0.1s
 => => transferring dockerfile: 634B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => ERROR [internal] load metadata for docker.io/library/node:18           0.5s
------
 > [internal] load metadata for docker.io/library/node:18:
------
error: failed to solve: rpc error: code = Unknown desc = failed to solve with fr
ontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown
 desc = error getting credentials - err: exit status 1, out: `error getting cred
entials - err: exit status 1, out: `A specified logon session does not exist. It
 may already have been terminated.``
[34320 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\roblou\AppData\Local\Temp\devcontainercli\container-features\0.52.1-1698272370788\Dockerfile-with-features -t vsc-searchtest-d1eb35eb7f7b82066feaed3520e31512c24cc4534388e9fa122a50e181840511 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label c:\Users\roblou\code\searchtest\.devcontainer
[34321 ms]     at cAA (C:\Users\roblou\.vscode-remote-containers\dist\dev-containers-cli-0.319.0\dist\spec-node\devContainersSpecCLI.js:463:1860)
[34321 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[34330 ms]     at async zw (C:\Users\roblou\.vscode-remote-containers\dist\dev-containers-cli-0.319.0\dist\spec-node\devContainersSpecCLI.js:462:1841)
[34330 ms]     at async kK (C:\Users\roblou\.vscode-remote-containers\dist\dev-containers-cli-0.319.0\dist\spec-node\devContainersSpecCLI.js:462:610)
[34331 ms]     at async NAA (C:\Users\roblou\.vscode-remote-containers\dist\dev-containers-cli-0.319.0\dist\spec-node\devContainersSpecCLI.js:479:3660)
[34332 ms]     at async vC (C:\Users\roblou\.vscode-remote-containers\dist\dev-containers-cli-0.319.0\dist\spec-node\devContainersSpecCLI.js:479:4775)
[34332 ms]     at async etA (C:\Users\roblou\.vscode-remote-containers\dist\dev-containers-cli-0.319.0\dist\spec-node\devContainersSpecCLI.js:613:10941)
[34332 ms]     at async AtA (C:\Users\roblou\.vscode-remote-containers\dist\dev-containers-cli-0.319.0\dist\spec-node\devContainersSpecCLI.js:613:10682)
[34388 ms] Exit code 1
[34399 ms] Command failed: C:\Users\roblou\.vscode-server-insiders\cli\servers\Insiders-18b7f75a9fab40499744c2e9c6ba9af64d5c6744\server\node.exe C:\Users\roblou\.vscode-remote-containers\dist\dev-containers-cli-0.319.0\dist\spec-node\devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-d91b5610-5486-4783-a231-ed20552d83741698272336805 --workspace-folder c:\Users\roblou\code\searchtest --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\roblou\code\searchtest --id-label devcontainer.config_file=c:\Users\roblou\code\searchtest\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\roblou\code\searchtest\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[34399 ms] Exit code 1
```

**Comment by chrmarti** [comment]
Could this be https://stackoverflow.com/questions/74583214/docker-failed-to-solve-with-frontend-dockerfile-v0-failed-to-create-llb-defin?
