### ISSUE TITLE
Failure to launch VSCode from WSL2 

### ISSUE THREAD

**Issue by Rhahkeem** [microsoft/vscode-remote-release#914]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

 When launching `code` from WSL2 *without* the Remote-Development Extension Pack there is no problem. But, when trying to launch `code` from `WSL2`  with Remote-Development (specifically Remote-WSL) it fails to launch with the following stacktrace
```
MyUserName@Host:~ $ -> code
Updating VS Code Server to version 0f3794b38477eea13fb47fbe15a42798e6129338
Removing previous installation...
Downloading: 100%
Unpacking: 100%
The factory method of "vs/server/remoteCli" has thrown an exception
{ Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:358:11)
    at Object.spawn (child_process.js:533:9)
    at l (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/server/remoteCli.js:86:650)
    at Object.<anonymous> (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/server/remoteCli.js:88:1010)
    at Function.t._safeInvokeFunction (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:19:945)
    at Function.t._invokeFactory (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:20:175)
    at t.complete (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:20:412)
    at s._onModuleComplete (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:30:614)
    at s._onModuleComplete (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:30:858)
    at s._onModuleComplete (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:30:858)
    at s._onModuleComplete (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:30:858)
    at s._resolve (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:30:174)
    at s.defineModule (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:24:534)
    at o (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:28:673)
    at Object.l (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:36:291)
    at Function.t._safeInvokeFunction (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:19:945)
    at Function.t._invokeFactory (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:20:175)
    at t.complete (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:20:412)
    at s._onModuleComplete (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:30:614)
    at s._onModuleComplete (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:30:858)
    at s._resolve (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:30:174)
    at s.defineModule (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:24:534)
    at o (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:31:789)
    at c (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:17:118)
    at Object.<anonymous> (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/server/remoteCli.nls.js:4:1)
    at t._createAndEvalScript (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:17:162)
    at /home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:16:762
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3) errno: 'EPERM', code: 'EPERM', syscall: 'spawn' }
Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:358:11)
    at Object.spawn (child_process.js:533:9)
    at l (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/server/remoteCli.js:86:650)
    at Object.<anonymous> (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/server/remoteCli.js:88:1010)
    at Function.t._safeInvokeFunction (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:19:945)
    at Function.t._invokeFactory (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:20:175)
    at t.complete (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:20:412)
    at s._onModuleComplete (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:30:614)
    at s._onModuleComplete (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:30:858)
    at s._onModuleComplete (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:30:858)
    at s._onModuleComplete (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:30:858)
    at s._resolve (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:30:174)
    at s.defineModule (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:24:534)
    at o (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:28:673)
    at Object.l (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:36:291)
    at Function.t._safeInvokeFunction (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:19:945)
    at Function.t._invokeFactory (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:20:175)
    at t.complete (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:20:412)
    at s._onModuleComplete (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:30:614)
    at s._onModuleComplete (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:30:858)
    at s._resolve (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:30:174)
    at s.defineModule (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:24:534)
    at o (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:31:789)
    at c (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:17:118)
    at Object.<anonymous> (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/server/remoteCli.nls.js:4:1)
    at t._createAndEvalScript (/home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:17:162)
    at /home/MyUserName/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/out/vs/loader.js:16:762
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

It seems to fail after downloading and installing the vscode server to run in WSL2

Extension version: 0.38.7
VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 10.0.18932

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (5.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by xeurun** [comment]
Any solutions?

**Comment by thelovesmith** [comment]
I am also having a problem running VScode from the WSL. However it logs: 

> Failed to connect to the remote extension host server (Error: connect ETIMEDOUT 127.0.0.1:50548)


restarted the computer and everything short of reinstalling the program. Since the connection fails I can't even access my extensions to uninstall them

**Comment by hausler89** [comment]
I completely reinstalled Code and Remote, I also can't open a terminal, neither on WSL nor on a Ubuntu machine through a SSH connection. The terminal window is stuck at "starting...".

**Comment by xeurun** [comment]
Have the same problem

`
Version: 1.37.0-insider (user setup)
Commit: 7e03eb1a1fce3beb6ccea5f3b8f828e01940be61
Date: 2019-07-05T18:31:56.611Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18932
`

**Comment by aeschli** [comment]
@thelovesmith @hausler89 @xeurun Please file separate issues unless your issue is also with WSL2 and you get exactly the same error as in the description...

**Comment by aeschli** [comment]
@Rhahkeem I think the problem is that `cmd.exe` is not on your PATH inside WSL. Can you confirm?

**Comment by phonzia** [comment]
@aeschli I have the same problem, but cmd.exe is in my path inside wsl, I can launch it directly by type it in wsl2 terminal

**Comment by xeurun** [comment]
I use as temporary solution forced `WSL_BUILD=0` value in `...\Microsoft VS Code Insiders\bin\code-insiders"` file

**Comment by Rhahkeem** [comment]
Weird enough after completely uninstalling vscode insiders and the extension this weekend, and now reinstalling I'm able to get past this part. 

Now I get 

```
[2019-07-08 11:31:20.986] Starting VS Code Server inside WSL (Ubuntu-18.04)
[2019-07-08 11:31:20.986] Windows build: 18932. Multi distro support: enabled
[2019-07-08 11:31:21.174] Probing if server is already installed: C:\WINDOWS\System32\wsl.exe -d Ubuntu-18.04 bash -c "[ -d ~/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338 ] && echo found || echo missing"
[2019-07-08 11:31:21.293] Server install found in WSL
[2019-07-08 11:31:21.293] Launching C:\WINDOWS\System32\wsl.exe -d Ubuntu-18.04 bash -c "'./scripts/wslServer.sh' '0f3794b38477eea13fb47fbe15a42798e6129338' 'stable' '.vscode-server' '' 0  " in c:\Users\UserName\.vscode\extensions\ms-vscode-remote.remote-wsl-0.38.7
[2019-07-08 11:31:21.473] bash: ./scripts/wslServer.sh: No such file or directory
```

Since that script does exist in the `c:\Users\UserName\.vscode\extensions\ms-vscode-remote.remote-wsl-0.38.7` directory I'm guessing the extension is expecting something in my `env` that doesn't exist. I've set my default shell to `/usr/bin/fish` using `chsh`. When setting the default to `/bin/bash` I noticed this was added 
```
AMD_ENTRYPOINT=vs/server/remoteExtensionHostProcess`
VSCODE_IPC_HOOK_CLI=/tmp/vscode-ipc-e2a2f2a4-1a80-4080-afe2-9f22272da8be.sock
```
and 
`/home/Username/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/bin:` was prepended to my `$PATH`. 

Sound like we're on the right track?

**Comment by aeschli** [comment]
@Rhahkeem That last issue sounds like https://github.com/microsoft/WSL/issues/4270

**Comment by Rhahkeem** [comment]
Interesting. Looks like they're definitely related. I had an explicit `cd <dir>` my ` ~/.config/fish/config.fish` to always put me in a certain directory at startup. Removing it seems to have solved the problem, and I can't seem to reproduce the original reported one. 
Curious though that launching from one directory is a problem. Can it be solved by giving the full path to `wslServer.sh` instead?  I typically like to start from a specific work directory when I run a shell

**Comment by aeschli** [comment]
If you still see the first issue (Error: spawn EPERM), please run with `--verbose` (`code .`)

**Comment by aeschli** [comment]
`EPERM` sounds like there a permission error when calling `cmd.exe /c code.cmd` out of the WSL.  \I haven't seen such an error myself yet. Anything special around permissions in your setup?

**Comment by garytube** [comment]
running code . --verbose
`
Invoking: cmd.exe /C C:\Program Files\Microsoft VS Code\bin\code.cmd --verbose --folder-uri=vscode-remote://wsl+Ubuntu-18.04/home/username/project--remote=wsl+Ubuntu-18.04
....
The factory method of "vs/server/remoteCli" has thrown an exception
{ Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:358:11)`

I'm running a fresh install of Ubuntu and the latest vs code insider build.

**Comment by aeschli** [comment]
@garytube Thanks a lot.
I assume you get the same when running `cmd.exe /C C:\Program Files\Microsoft VS Code\bin\code.cmd` directly in the WSL shell?

Just to confirm, it's a WSL2 distro, right? (`wsl -l`  will show you that)

If you want to test against the latest insiders, run `code-insiders . --verbose`

**Comment by garytube** [comment]
Yep, you are right.

I also tested the Insiders build, of course the same error.

Interestingly enough. Everything works just fine if I start a new WSL window from within vs code.

**Comment by aeschli** [comment]
What about running `/mnt/c/Program Files/Microsoft VS Code/code` from the WSL shell?

**Comment by infdahai** [comment]
@aeschli  I try what you said.
```
➜  Microsoft VS Code Insiders which code-insiders
/mnt/c/Program Files/Microsoft VS Code Insiders/bin/code-insiders
➜  Microsoft VS Code Insiders pwd
/mnt/c/Program Files/Microsoft VS Code Insiders
➜  Microsoft VS Code Insiders ls
bin                                         ffmpeg.dll        osmesa.dll         unins000.dat
chrome_100_percent.pak                      icudtl.dat        resources          unins000.exe
chrome_200_percent.pak                      libEGL.dll        resources.pak      unins000.msg
Code - Insiders.exe                         libGLESv2.dll     snapshot_blob.bin  v8_context_snapshot.bin
Code - Insiders.VisualElementsManifest.xml  locales           swiftshader
d3dcompiler_47.dll                          natives_blob.bin  tools
```                                     
In this directory, I use ```  `$pwd`/bin/code-insiders and crash```  again as before. 
But if you use Code - Insiders.exe, it will run as an editor in windows.

and I change my dir and try a try. 
```
➜  tinyflow git:(master) pwd
/mnt/f/tinyflow
➜  tinyflow git:(master) /mnt/c/Program\ Files/Microsoft\ VS\ Code\ Insiders/Code\ -\ Insiders.exe  .
```
It works and open the tinyflow dir but vscode-insiders run as a windows editor on the host machine, not as remote editor in wsl.

I try another situation.
```
➜  tinyflow git:(master) /mnt/c/Program\ Files/Microsoft\ VS\ Code\ Insiders/Code\ -\ Insiders.exe  `pwd`/

 %                   
```
the windows editor will create a file named 'tinyflow' in this situation so that isn't right.

**Comment by aeschli** [comment]
@infdahai Thanks for the investigation.
Great to know that `/mnt/c/Program\ Files/Microsoft\ VS\ Code\ Insiders/Code\ -\ Insiders.exe` can be invoked from the WSL shell. (It opens a local window, but that's expected: It requires a `--folder-uri://wsl+default/mnt/f/tinyflow` as argument to do that).

**Comment by aeschli** [comment]
Can you try the following:
- Open `c:\Program Files\Microsoft VS Code Insiders\bin/code-insiders` in an editor
- On line 39, replace the assignment with `WIN_CODE_CMD="$ELECTRON"`

**Comment by infdahai** [comment]
> Can you try the following:
> 
> * Open `c:\Program Files\Microsoft VS Code Insiders\bin/code-insiders` in an editor
> * On line 39 (`WIN_CODE_CMD...`, replace the line with `WIN_CODE_CMD="$ELECTRON"`

thanks very much, my friend.
I use powershell to do what you said.
And then I find it work in my wsl 2 (debian 9)

```
➜  d which code-insiders
/mnt/c/Program Files/Microsoft VS Code Insiders/bin/code-insiders
➜  d code-insiders chromium

 [main 2019-07-10T18:33:09.681Z] update#setState idle
[main 2019-07-10T18:33:16.667Z] Received resolved authority wsl+Debian
                                                                      [main 2019-07-10T18:33:39.685Z] update#setState checking for updates
                                                                                                                                          [main 2019-07-10T18:33:39.981Z] update#setState idle

```
I try it and open the chromium dir in remote editor.
if I just exec ` code-insiders ` , the windows editor will  be invoked.

**Comment by infdahai** [comment]
@aeschli 
I update  windows 10-insider os and code-insiders today.
Then the method of editing `code-insiders` file doesn't work.

```shell
➜  ~ code-insiders ss_config.json
/usr/bin/env: ‘bash\r’: Operation not permitted
➜  ~ bash
user@DESKTOP-M11AF9V:~$ code-insiders ss_config.json
/usr/bin/env: ‘bash\r’: Operation not permitted

```

**Comment by aeschli** [comment]
@infdahai Likely the editor added a Windows end-of-line character (\r\n) to the first line of the script. Should be just `\n`

**Comment by infdahai** [comment]
@aeschli 
oh, that's my fault.

I use ` WIN_CODE_CMD="$ELECTRON" ` then can run correctly.

**Comment by aeschli** [comment]
Sorry, had to revert and find a better solution

**Comment by yunghoy** [comment]
Did you revert the VSCode insiders recently? After updated VSCode Insiders, I just met the problem. I cannot use Remote-WSL anymore.

Failed to connect to the remote extension host server (Error: connect ETIMEOUT xxx.xxx.xxx.xxx:yyyyy)

**Comment by aeschli** [comment]
No I just reverted the change now. 
I https://github.com/microsoft/vscode-remote-release/issues/1012 what you are seeing?
If not, please file a new issue describing the way you start up the WSL window and paste the full WSL terminal output.

**Comment by maxencefrenette** [comment]
Not sure if this should be closed. I'm getting the exact same error with the latest versions of Windows (Fast Ring), Ubuntu and VS Code.

**Comment by SeanTAllen** [comment]
I'm also getting this issue as of 2 days ago. I'm on Fast Ring for insider builds.

**Comment by aeschli** [comment]
New attempt to fix...

**Comment by aeschli** [comment]
Please try with tomorrows (7/30) insider build.

**Comment by SeanTAllen** [comment]
@aeschli with the vscode insiders build? or some other insiders build?

**Comment by aeschli** [comment]
Fixes by https://github.com/microsoft/vscode/commit/49b51b32b2a9c32f34c00746c2013dbde86d1ef3

**Comment by aeschli** [comment]
@SeanTAllen Yes, the VSCode insiders build

**Comment by SeanTAllen** [comment]
@aeschli I have version:

```
Version: 1.37.0-insider (user setup)
Commit: cf03ea3729dc37e439d724267ad29dc5840f903a
Date: 2019-07-30T07:15:22.972Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18945
```

And still have the issue. I'll do another insider update tomorrow and see if perhaps your change didn't make it into the version that I updated to earlier today. If tomorrow's doesn't work as well, I'll let you now.

**Comment by SeanTAllen** [comment]
I think this should still be an open issue. I am running:

```
Version: 1.37.0-insider (user setup)
Commit: d5900c642b359fe7a9eb1e3f9e2d0977f6e0905c
Date: 2019-07-31T05:24:41.973Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18945
```

and when I run `code-insiders .` inside a WSL2 setup, it hangs. Control-c is unable to exit the process. This is slightly different than the non-insiders VSCode that also hangs but you can Control-C to exit from being hung.

**Comment by denispasin** [comment]
From my understanding (and debugging) `ELECTRON_RUN_AS_NODE=1` isn't working and that line starts a "normal" VSCode (which is not what we want) and so the command hang.

**Comment by SeanTAllen** [comment]
@denispasin yes, without the `ELECTRON_RUN_AS_NODE=1` code will start. however, it opens the cli.js file and doesn't start up as a WSL environment editor.

**Comment by denispasin** [comment]
What I mean is even with `ELECTRON_RUN_AS_NODE=1` (or ELECTRON_RUN_AS_NODE=true` for that matter) it starts code and open the `cli.js` file.

**Comment by Rhahkeem** [comment]
FWIW it works for me now

**Comment by SeanTAllen** [comment]
I installed the latest VSCode insiders and have the same problem. @Rhahkeem what WSL build are your running?

**Comment by sfteague** [comment]
> I think this should still be an open issue. I am running:
> 
> ```
> Version: 1.37.0-insider (user setup)
> Commit: d5900c642b359fe7a9eb1e3f9e2d0977f6e0905c
> Date: 2019-07-31T05:24:41.973Z
> Electron: 4.2.7
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Windows_NT x64 10.0.18945
> ```
> 
> And when I run `code-insiders .` inside a WSL2 setup, it hangs. Control-c is unable to exit the process. This is slightly different than the non-insiders VSCode that also hangs but you can Control-C to exit from being hung.
> 
> Doing a bit of debugging, I never execute the line that was changed as part of the patch. It hangs before that when:
> 
> ```
> WSL_EXT_WLOC=$(ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --locate-extension $WSL_EXT_ID)   
> ```
> 
> is executed.

I'm having the exact same issue.  When I run `code-insiders .` I get a hang and am unable to exit the process with Ctrl+C.  If I run `code .` it also hangs, but I can exit.  I'm on Windows 10, Version 1903, OS build 18950.1000.  I completely uninstalled Ubuntu and WSL, got things running again, and am getting the same behavior.

**Comment by arthurgeron** [comment]
Same issue here, getting ETIMEDOUT on different ports each time.

**Comment by jflam** [comment]
I'm seeing it in 

```
Version: 1.37.0 (user setup)
Commit: 036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
Date: 2019-08-08T02:33:50.993Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18956
```

on `Windows Insider 18956.1000 and Ubuntu 18.04 LTS`

Fortunately, I can workaround by launching code from Windows and navigating to the desired directory in WSL 2.

**Comment by arthurgeron** [comment]
@jflam  what configs in vscode did you use to avoid LF CRLF conflicts?

**Comment by jflam** [comment]
I use `git config --global core.autocrlf input` from the docs here: https://code.visualstudio.com/docs/remote/wsl

**Comment by LostInBrittany** [comment]
Hi! Same problem here :(

Everything worked well until this morning, when I updated my VSCode to version 1.37.1.

Now VSCode is unable to connect to WSL, I get

```
Failed to connect to the remote extension host server (Error: connect ETIMEDOUT 192.168.109.164:38019)
```

when trying to open remote-wsl

**Comment by aeschli** [comment]
There are various issue described here:

> When I run code-insiders . I get a hang and am unable to exit the process with Ctrl+C
That's a WSL bug related to the Windows Insider Update: Bug https://github.com/microsoft/vscode/issues/77898

> Everything worked well until this morning, when I updated my VSCode to version 1.37.1.
@LostInBrittany Can you open a new issue and paste in the full WSL log (from the WSL terminal)

**Comment by LostInBrittany** [comment]
> There are various issue described here:
> 
> > When I run code-insiders . I get a hang and am unable to exit the process with Ctrl+C

I definitively have this issue too, but reading the thread I had understood it comes from issue in VSCode that comes from a WSL issue :)

> > Everything worked well until this morning, when I updated my VSCode to version 1.37.1.
>
> @LostInBrittany Can you open a new issue and paste in the full WSL log (from the WSL terminal)

I am currently back to my Linux computer because I had some work to do. I will try again on the Win machine tonight and I will post the issue. How can I get the full WSL log?

**Comment by aeschli** [comment]
The WSL log comes to the foreground if there's any startup issue and when you run the `Remote - WSL: Show Log` command.
It's a tab in the terminal

**Comment by LostInBrittany** [comment]
When I tried I got a popup with the message I detailed before, no log came
into foreground.
I will use the `Remote - WSL: Show Log` when I will test again tonight.

THANKS!
