### ISSUE TITLE
Log: Invalid URI creating

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-remote-release#9151]
Just found this in my VSCode Window log, not sure how I got it or what it causes.

2023-10-30 09:36:12.202 [error] [Extension Host] Error: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
    at m (c:\Users\martinae\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:31832)
    at new y (c:\Users\martinae\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:32740)
    at new h (c:\Users\martinae\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:34378)
    at h.with (c:\Users\martinae\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:33167)
    at uu (c:\Users\martinae\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.315.1\dist\extension\extension.js:293:5285)
    at Object.isFile (c:\Users\martinae\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.315.1\dist\extension\extension.js:293:4317)
    at Sy (c:\Users\martinae\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.315.1\dist\extension\extension.js:92:347)
    at X3 (c:\Users\martinae\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.315.1\dist\extension\extension.js:92:2018)
    at iS (c:\Users\martinae\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.315.1\dist\extension\extension.js:279:1641)
    at Hle (c:\Users\martinae\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.315.1\dist\extension\extension.js:368:8769)
    at c:\Users\martinae\.vscode-insiders\extensions\ms-vscode-remote.remote-containers-0.315.1\dist\extension\extension.js:367:20025

**Comment by chrmarti** [comment]
This should be fixed with https://github.com/microsoft/vscode-remote-release/issues/9127 in Dev Containers 0.320.0-pre-release and later. Thanks!
