### ISSUE TITLE
Permission denied error in devcontainer over tunnel

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-remote-release#9156]
Testing https://github.com/microsoft/vscode-remote-release/issues/9081

Out of the box dev containers over tunnels (Windows -> macOS) hit the following error starting the container:

```
[171421 ms] Start: Run: /Users/connor/.vscode-remote-containers/bin/7c1bff30eae1fcb2565c20a062a4fb44b7dd562b/node /Users/connor/.vscode-remote-containers/dist/dev-containers-cli-0.320.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /Users/connor/Downloads/foo/Basic --id-label devcontainer.local_folder=/Users/connor/Downloads/foo/Basic --id-label devcontainer.config_file=/Users/connor/Downloads/foo/Basic/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/connor/Downloads/foo/Basic/.devcontainer/devcontainer.json --mount-workspace-git-root
[171753 ms] Error: CodeError(ProcessSpawnFailed(Os { code: 13, kind: PermissionDenied, message: "Permission denied" }))
        at Object.resolve (c:\Users\conno\.vscode-insiders\extensions\ms-vscode.remote-server-1.5.2023102609\dist\node\extension.js:2:871541)
        at c:\Users\conno\.vscode-insiders\extensions\ms-vscode.remote-server-1.5.2023102609\dist\node\extension.js:2:870246
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[171754 ms] Exit code -1
```

Looking at that file in my terminal, it's missing `x`
```
➜  ~ ls -l /Users/connor/.vscode-remote-containers/bin/7c1bff30eae1fcb2565c20a062a4fb44b7dd562b/node
-rw-r--r--  1 connor  staff  93111376 Oct 30 16:39 /Users/connor/.vscode-remote-containers/bin/7c1bff30eae1fcb2565c20a062a4fb44b7dd562b/node
➜  ~ /Users/connor/.vscode-remote-containers/bin/7c1bff30eae1fcb2565c20a062a4fb44b7dd562b/node
zsh: permission denied: /Users/connor/.vscode-remote-containers/bin/7c1bff30eae1fcb2565c20a062a4fb44b7dd562b/node
```

A manual `chmod +x` fixed the issue

**Comment by chrmarti** [comment]
Fixed in Dev Containers 0.322.0-pre-release.
