### ISSUE TITLE
[Remote-SSH Bug]: Cannot GET /commit: ... server-win32/stable

### ISSUE THREAD

**Issue by dorianso** [microsoft/vscode-remote-release#9179]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

On mac system using : Version: 1.84.1
Commit: 2b35e1e6d88f1ce073683991d1eff5284a32690f
Date: 2023-11-06T12:37:31.808Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0

Connect to Windows system and have ssh work as expected. 

### Steps To Reproduce

On Mac, using :Version: 1.84.1
Commit: 2b35e1e6d88f1ce073683991d1eff5284a32690f
Date: 2023-11-06T12:37:31.808Z

Use SSH extension to connect to Windows machine on same network. 

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[12:24:03.288] Log Level: 2
[12:24:03.293] VS Code version: 1.84.1
[12:24:03.293] Remote-SSH version: remote-ssh@0.106.5
[12:24:03.293] darwin arm64
[12:24:03.294] SSH Resolver called for "ssh-remote+192.168.64.2", attempt 1
[12:24:03.294] "remote.SSH.useLocalServer": false
[12:24:03.294] "remote.SSH.useExecServer": false
[12:24:03.295] "remote.SSH.showLoginTerminal": true
[12:24:03.295] "remote.SSH.remotePlatform": {"192.168.64.2":"windows"}
[12:24:03.295] "remote.SSH.path": undefined
[12:24:03.295] "remote.SSH.configFile": undefined
[12:24:03.295] "remote.SSH.useFlock": true
[12:24:03.295] "remote.SSH.lockfilesInTmp": false
[12:24:03.295] "remote.SSH.localServerDownload": auto
[12:24:03.295] "remote.SSH.remoteServerListenOnSocket": true
[12:24:03.296] "remote.SSH.showLoginTerminal": true
[12:24:03.296] "remote.SSH.defaultExtensions": []
[12:24:03.296] "remote.SSH.loglevel": 2
[12:24:03.296] "remote.SSH.enableDynamicForwarding": true
[12:24:03.296] "remote.SSH.enableRemoteCommand": false
[12:24:03.298] "remote.SSH.serverPickPortsFromRange": {}
[12:24:03.299] "remote.SSH.serverInstallPath": {}
[12:24:03.301] SSH Resolver called for host: 192.168.64.2
[12:24:03.301] Setting up SSH remote "192.168.64.2"
[12:24:03.302] Using commit id "2b35e1e6d88f1ce073683991d1eff5284a32690f" and quality "stable" for server
[12:24:03.305] Install and start server if needed

[12:24:03.306] Checking ssh with "ssh -V"
[12:24:03.311] > OpenSSH_9.4p1, LibreSSL 3.3.6

[12:24:03.313] Remote command length: 6276/8192 characters
[12:24:03.313] Running script with connection command: ssh -T -D 51607 -o ConnectTimeout=15 '192.168.64.2' powershell
[12:24:04.662] > Windows PowerShell
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows
> 
> PS C:\Users\dorian> 
> PS C:\Users\dorian> $uuid="a2e7ae5e9849"
> PS C:\Users\dorian> "${uuid}: running"
> a2e7ae5e9849: running
> PS C:\Users\dorian> "a2e7ae5e9849: pauseLog"
> a2e7ae5e9849: pauseLog
[12:24:04.662] Got some output, clearing connection timeout
[12:24:04.898] > a2e7ae5e9849: resumeLog
> PS C:\Users\dorian> main
[12:24:05.124] > Acquiring lock on C:\Users\dorian\.vscode-server\bin\2b35e1e6d88f1ce073683991d1eff5284a32690f\vscode-remote-lock.2b35e1e6d88f1ce073683991d1eff5284a32690f
> Looking for existing server in C:\Users\dorian\.vscode-server\bin\2b35e1e6d88f1ce073683991d1eff5284a32690f
[12:24:05.138] > Downloading server ia32
> a2e7ae5e9849%%1%%
[12:24:05.333] > Download failed. - Not Found
> Trigger local server download
> a2e7ae5e9849:trigger_server_download
> artifact==server-win32==
> destFolder==C:\Users\dorian\.vscode-server\bin\==
> destFolder2==/2b35e1e6d88f1ce073683991d1eff5284a32690f\vscode-server.zip==
> a2e7ae5e9849:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for C:\Users\dorian\.vscode-server\bin\2b35e1e6d88f1ce073683991d1eff5284a32690f\vscode-server.zip.done and vscode-server.zip to exist
[12:24:05.333] Got request to download on client for {"artifact":"server-win32","destPath":"C:\\Users\\dorian\\.vscode-server\\bin\\/2b35e1e6d88f1ce073683991d1eff5284a32690f\\vscode-server.zip"}
[12:24:05.334] Downloading VS Code server locally...
[12:24:05.456] Resolver error: Error: Server returned 404
    at h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:676:29220)
    at E.download (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:677:1753)
[12:24:05.461] ------```

</p>
</details>


### Anything else?

In developer logs it shows the following:

update.code.visualstudio.com/commit:2b35e1e6d88f1ce073683991d1eff5284a32690f/server-win32/stable:1     Failed to load resource: the server responded with a status of 404 ()
log.ts:441   ERR [LocalProcess0][resolveAuthority(ssh-remote,1)][2175ms] returned an error Objectcode: "NotAvailable"detail: truemessage: "Server returned 404"

It seems the issue is with the following : **https://update.code.visualstudio.com/commit:2b35e1e6d88f1ce073683991d1eff5284a32690f/server-win32/stable which returns a 404.** 

I tried using chrome to access that resource but got back : 
**NOT FOUND** 


My conclusion is that the server download for the current VSCode commit of 2b35e1e6d88f1ce073683991d1eff5284a32690f is inaccesible for some reason .


Current Solution is to downgrade to commit :fdb98833154679dbaa7af67a5a29fe19e55c2b73

**Comment by roblourens** [comment]
Ah, we don't support windows 32 anymore. We will have to update the extension to enforce that as well https://code.visualstudio.com/updates/v1_84#_windows-32bit-support-ends

**Comment by dorianso** [comment]
Thank you for the quick response and clarification.

**Comment by connor4312** [comment]
This will be fixed in tomorrow's prerelease version of Remote - SSH (go to extension view, search for remote - ssh, right click and "Switch to Pre-release version")

**Comment by rzhao271** [comment]
Now it fails to connect with a 404 error, which makes sense to me, though I wonder if the logs can be a bit friendlier.

Current logs:

```
...
[14:07:04.119] > PS C:\Users\raymondzhao> "${uuid}: running"
> d76eca7ecf45: running
> PS C:\Users\raymondzhao> "d76eca7ecf45: pauseLog
[14:07:06.028] > d76eca7ecf45: resumeLog
[14:07:06.041] > PS C:\Users\raymondzhao> main
[14:07:06.058] > 
[14:07:08.927] > Looking for existing CLI in C:\Users\raymondzhao\.vscode-server-insiders
[14:07:08.937] > 
> Downloading cli ia32
> d76eca7ecf45%%1%%
[14:07:08.957] > 
[14:07:09.267] > Download failed. - Not Found
[14:07:09.274] > 
> Trigger local server download
> d76eca7ecf45:trigger_server_download
> artifact==cli-win32==
> destFolder==C:\Users\raymondzhao\.vscode-server-insiders==
> destFolder2==/vscode-cli-8762127fc97b8aaae5f3a0dd6a6d853d9a1b7574.zip==
> d76eca7ecf45:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for C:\Users\raymondzhao\.vscode-server-insiders\vscode-cli-8762127fc97b8aaae5f3a0dd6a6d853d9a1b7574.zip.done and vscode-cli-87
> 762127fc97b8aaae5f3a0dd6a6d853d9a1b7574.zip to exist
[14:07:09.276] Got request to download on client for {"artifact":"cli-win32","destPath":"C:\\Users\\raymondzhao\\.vscode-server-insiders/vscode-cli-8762127fc97b8aaae5f3a0dd6a6d853d9a1b7574.zip"}
[14:07:09.277] Downloading VS Code server locally...
[14:07:09.297] > 
[14:07:09.473] Resolver error: Error: Server returned 404
    at <stacktrace>
[14:07:09.492] ------

...

[14:07:19.534] Exec server for ssh-remote+localhost failed: Error: La connexion a été annulée
[14:07:19.534] Error opening exec server for ssh-remote+localhost: Error: La connexion a été annulée
```
