### ISSUE TITLE
Segmentation fault connecting to containers

### ISSUE THREAD

**Issue by rowanseymour** [microsoft/vscode-remote-release#9180]
- VSCode Version: 1.84.0
- Local OS Version: macOS 14 (M1)
- Remote OS Version: 
- Remote Extension/Connection Type: Containers

- Logs:

```
[1734 ms] Optimizing extensions for quality: stable
[1734 ms] Start: Run in container: cd /vscode/vscode-server/extensionsCache && touch 'dbaeumer.vscode-eslint-2.4.2' 'golang.go-0.39.1'
[1735 ms] Start: Run in container: /home/vscode/.vscode-server/bin/d037ac076cee195194f93ce6fe2bdfe2969cc82d/bin/code-server --log debug --force-disable-user-env --server-data-dir /home/vscode/.vscode-server --telemetry-level all --accept-server-license-terms --host 127.0.0.1 --port 0 --connection-token-file /home/vscode/.vscode-server/data/Machine/.connection-token-d037ac076cee195194f93ce6fe2bdfe2969cc82d --extensions-download-dir /home/vscode/.vscode-server/extensionsCache --install-extension golang.Go --install-extension dbaeumer.vscode-eslint --start-server 
[1736 ms] Error: stream ended with:0 but wanted:9
        at c (/Users/rowan/.vscode/extensions/ms-vscode-remote.remote-containers-0.321.0/dist/extension/extension.js:27:22149)
        at /Users/rowan/.vscode/extensions/ms-vscode-remote.remote-containers-0.321.0/dist/extension/extension.js:27:22330
        at s (/Users/rowan/.vscode/extensions/ms-vscode-remote.remote-containers-0.321.0/dist/extension/extension.js:30:5371)
        at Socket.<anonymous> (/Users/rowan/.vscode/extensions/ms-vscode-remote.remote-containers-0.321.0/dist/extension/extension.js:30:5541)
        at Socket.emit (node:events:525:35)
        at endReadableNT (node:internal/streams/readable:1359:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[1737 ms] Start: Run in container: mkdir -p '/tmp/devcontainers-0d9a7102-2d4c-4960-b298-cf009a4931751699300957883' && cat > '/tmp/devcontainers-0d9a7102-2d4c-4960-b298-cf009a4931751699300957883/env-loginInteractiveShell.json' << 'envJSON'
[1737 ms] 
[1737 ms] 
[1737 ms] Container server terminated (code: 139, signal: null).
[1739 ms] 
[1739 ms] 
[1794 ms] Command failed: /home/vscode/.vscode-server/bin/d037ac076cee195194f93ce6fe2bdfe2969cc82d/bin/code-server --log debug --force-disable-user-env --server-data-dir /home/vscode/.vscode-server --telemetry-level all --accept-server-license-terms --host 127.0.0.1 --port 0 --connection-token-file /home/vscode/.vscode-server/data/Machine/.connection-token-d037ac076cee195194f93ce6fe2bdfe2969cc82d --extensions-download-dir /home/vscode/.vscode-server/extensionsCache --install-extension golang.Go --install-extension dbaeumer.vscode-eslint --start-server 
[1795 ms] Segmentation fault
[1795 ms] Exit code 139
```

I think the `ms-vscode-remote.remote-containers` extension updated today to v0.321.0 and now I can't open any project in a container, or rebuild containers.

**Comment by rowanseymour** [comment]
Uninstalled then reinstalled the extension and its working now...
