### ISSUE TITLE
 findLocalWindowsExecutable: Exectuable 'tar' not found on PATH

### ISSUE THREAD

**Issue by a4z** [microsoft/vscode-remote-release#9198]
- VSCode Version: 1.84.2
- Local OS Version: Windows 10
- Remote OS Version:  python:3.11.3-alpine3.18
- Remote Extension/Connection Type: Containers

- Logs:

```
[2023-11-10T09:43:05.288Z] Start: Resolving Remote
[2023-11-10T09:43:05.293Z] Start: Run: git rev-parse --show-cdup
[2023-11-10T09:43:05.403Z] Stop (110 ms): Run: git rev-parse --show-cdup
[2023-11-10T09:43:05.450Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\dev\xperiment\weasy --filter label=devcontainer.config_file=c:\dev\xperiment\weasy\.devcontainer\devcontainer.json
[2023-11-10T09:43:05.672Z] Stop (222 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\dev\xperiment\weasy --filter label=devcontainer.config_file=c:\dev\xperiment\weasy\.devcontainer\devcontainer.json
[2023-11-10T09:43:05.677Z] Start: Run: docker inspect --type image python:3.11.3-alpine3.18
[2023-11-10T09:43:05.887Z] Stop (210 ms): Run: docker inspect --type image python:3.11.3-alpine3.18
[2023-11-10T09:43:06.255Z] Start: Run: docker-credential-desktop get
[2023-11-10T09:43:06.443Z] Stop (188 ms): Run: docker-credential-desktop get
[2023-11-10T09:43:07.691Z] local container features stored at: c:\Users\hachc05546\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\node_modules\vscode-dev-containers\container-features
[2023-11-10T09:43:07.693Z] Start: Run: tar --no-same-owner -x -f -
[2023-11-10T09:43:07.729Z] findLocalWindowsExecutable: Exectuable 'tar' not found on PATH '%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Docker\Docker\resources\bin;C:\Users\hachc05546\scoop\apps\python\current\Scripts;C:\Users\hachc05546\scoop\apps\python\current;C:\Users\hachc05546\scoop\apps\microsoft-lts-jdk\current\bin;C:\Users\hachc05546\scoop\apps\nodejs-lts\current\bin;C:\Users\hachc05546\scoop\apps\nodejs-lts\current;C:\Users\hachc05546\scoop\shims;C:\Users\hachc05546\AppData\Local\Microsoft\WindowsApps;C:\Users\hachc05546\AppData\Local\Programs\Microsoft VS Code\bin'.
[2023-11-10T09:43:07.739Z] Error: Exectuable 'tar' not found on PATH '%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Docker\Docker\resources\bin;C:\Users\hachc05546\scoop\apps\python\current\Scripts;C:\Users\hachc05546\scoop\apps\python\current;C:\Users\hachc05546\scoop\apps\microsoft-lts-jdk\current\bin;C:\Users\hachc05546\scoop\apps\nodejs-lts\current\bin;C:\Users\hachc05546\scoop\apps\nodejs-lts\current;C:\Users\hachc05546\scoop\shims;C:\Users\hachc05546\AppData\Local\Microsoft\WindowsApps;C:\Users\hachc05546\AppData\Local\Programs\Microsoft VS Code\bin'.
[2023-11-10T09:43:07.739Z]     at Fy (c:\Users\hachc05546\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\spec-node\devContainersSpecCLI.js:150:4280)
[2023-11-10T09:43:07.740Z]     at async Object.exec (c:\Users\hachc05546\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\spec-node\devContainersSpecCLI.js:150:1655)
[2023-11-10T09:43:07.740Z]     at async AAA (c:\Users\hachc05546\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\spec-node\devContainersSpecCLI.js:394:324)
[2023-11-10T09:43:07.740Z]     at async MC (c:\Users\hachc05546\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\spec-node\devContainersSpecCLI.js:392:1750)
[2023-11-10T09:43:07.740Z]     at async cAA (c:\Users\hachc05546\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\spec-node\devContainersSpecCLI.js:462:2402)
[2023-11-10T09:43:07.740Z]     at async zw (c:\Users\hachc05546\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\spec-node\devContainersSpecCLI.js:462:1841)
[2023-11-10T09:43:07.741Z]     at async kK (c:\Users\hachc05546\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\spec-node\devContainersSpecCLI.js:462:610)
[2023-11-10T09:43:07.741Z]     at async NAA (c:\Users\hachc05546\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\spec-node\devContainersSpecCLI.js:479:3660)
[2023-11-10T09:43:07.741Z]     at async vC (c:\Users\hachc05546\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\spec-node\devContainersSpecCLI.js:479:4775)
[2023-11-10T09:43:07.741Z]     at async etA (c:\Users\hachc05546\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\spec-node\devContainersSpecCLI.js:613:10941)
[2023-11-10T09:43:07.753Z] Stop (3391 ms): Run: C:\Users\hachc05546\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\hachc05546\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\hachc05546\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-19b9c4f8-d7a2-4779-86b4-d5a6cca1711e1699609381326 --workspace-folder c:\dev\xperiment\weasy --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\dev\xperiment\weasy --id-label devcontainer.config_file=c:\dev\xperiment\weasy\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\dev\xperiment\weasy\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2023-11-10T09:43:07.754Z] Exit code 1
[2023-11-10T09:43:07.757Z] Command failed: C:\Users\hachc05546\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\hachc05546\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\hachc05546\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-19b9c4f8-d7a2-4779-86b4-d5a6cca1711e1699609381326 --workspace-folder c:\dev\xperiment\weasy --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\dev\xperiment\weasy --id-label devcontainer.config_file=c:\dev\xperiment\weasy\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\dev\xperiment\weasy\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2023-11-10T09:43:07.757Z] Exit code 1
```

Steps to Reproduce:

1. Open a dev container

The situation is basically, yesterday it worked, today it does not. What happend in between? An update of VS Code

I can still open existing folders as container, but not a new one
Even if I copy the .devcontainer and the Dockerfile of the working one in a new folder, try to build and start the container, and end up with the error above

**Comment by a4z** [comment]
Today, Monday, it works again. 
Maybe some issue caused through Virus Scanner, or other temporary issues on the company Windows?
Who knows, had in any case updates over the weekend, and now the problem went away... so I close this issue
