### ISSUE TITLE
DevContainer: Failed to cache user env: Shell server failed: Error: unexpected end of parent stream

### ISSUE THREAD

**Issue by ahemwe** [microsoft/vscode-remote-release#9209]
- VSCode Version: 1.84.2 (user setup) (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e)
- Local OS Version: Windows_NT x64 10.0.19045
- Remote OS Version: Debian 12 (bookworm)"
- Remote Extension/Connection Type: Containers
- WSL 2 OS: Ubuntu 22.04

My `devcontainer.json`:
``` devcontainer
{
	"name": "Existing Dockerfile",
	"build": {
		// Sets the run context to one level up instead of the .devcontainer folder.
		"context": "..",
		// Update the 'dockerFile' property if you aren't using the standard 'Dockerfile' filename.
		"dockerfile": "../Dockerfile",
	}

	// Features to add to the dev container. More info: https://containers.dev/features.
	// "features": {},

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Uncomment the next line to run commands after the container is created.
	// "postCreateCommand": "cat /etc/os-release",

	// Configure tool-specific properties.
	// "customizations": {},

	// Uncomment to connect as an existing user other than the container default. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "devcontainer"
}

```
My `Dockerfile`:

```
FROM python:3.10-bookworm
```

Build of my devcontainer works well, but when opening the existing container in VSCode, this error shows up.
It is possible to run the container via command line or docker desktop and access it.
Problem seems to be during configuration of remote access from vs code.

- Logs:
```
[2023-11-16T14:57:04.453Z] Start: Run in Host: docker exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=ea039853-32cf-4451-959d-72d713049c591700146617283 2598043c0c80b4d9897bac5e0297cc57cd6ec5924e6e580092fe5343d376a220 /bin/sh
[2023-11-16T14:57:04.456Z] Start: Run in container: uname -m
[2023-11-16T14:57:04.519Z] x86_64
[2023-11-16T14:57:04.519Z] 
[2023-11-16T14:57:04.519Z] Stop (63 ms): Run in container: uname -m
[2023-11-16T14:57:04.519Z] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[2023-11-16T14:57:04.521Z] PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[2023-11-16T14:57:04.521Z] 
[2023-11-16T14:57:04.521Z] Stop (2 ms): Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[2023-11-16T14:57:04.521Z] Start: Run in container:  (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true)
[2023-11-16T14:57:04.523Z] Stop (2 ms): Run in container:  (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true)
[2023-11-16T14:57:04.523Z] Start: Run in container: command -v git >/dev/null 2>&1 && cd '/workspaces/test' && test -d .git && test "$(stat -c %u .)" != "$(id -u)"
[2023-11-16T14:57:04.525Z] 
[2023-11-16T14:57:04.525Z] 
[2023-11-16T14:57:04.525Z] Exit code 1
[2023-11-16T14:57:04.525Z] Stop (2 ms): Run in container: command -v git >/dev/null 2>&1 && cd '/workspaces/test' && test -d .git && test "$(stat -c %u .)" != "$(id -u)"
[2023-11-16T14:57:04.525Z] Start: Updating configuration state
[2023-11-16T14:57:04.530Z] Stop (5 ms): Updating configuration state
[2023-11-16T14:57:04.531Z] Start: Setup shutdown monitor
[2023-11-16T14:57:04.531Z] Forking shutdown monitor: c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\shutdown\shutdownMonitorProcess \\.\pipe\vscode-remote-containers-ff5c034d-d32b-4600-a37f-43fd12ead575-sock singleContainer Debug c:\Users\myself\AppData\Roaming\Code\logs\20231116T152745\window2\exthost\ms-vscode-remote.remote-containers 1700146617833
[2023-11-16T14:57:04.541Z] Stop (10 ms): Setup shutdown monitor
[2023-11-16T14:57:04.542Z] Start: Run in container: test -d /root/.vscode-server
[2023-11-16T14:57:04.544Z] 
[2023-11-16T14:57:04.544Z] 
[2023-11-16T14:57:04.544Z] Exit code 1
[2023-11-16T14:57:04.544Z] Stop (2 ms): Run in container: test -d /root/.vscode-server
[2023-11-16T14:57:04.545Z] Start: Run in container: test -d /root/.vscode-remote
[2023-11-16T14:57:04.546Z] 
[2023-11-16T14:57:04.546Z] 
[2023-11-16T14:57:04.546Z] Exit code 1
[2023-11-16T14:57:04.546Z] Stop (1 ms): Run in container: test -d /root/.vscode-remote
[2023-11-16T14:57:04.546Z] Start: Run in container: test ! -f '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[2023-11-16T14:57:04.549Z] 
[2023-11-16T14:57:04.550Z] 
[2023-11-16T14:57:04.550Z] Stop (4 ms): Run in container: test ! -f '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[2023-11-16T14:57:04.550Z] Start: Run in container: cat /root/.vscode-server/data/Machine/settings.json
[2023-11-16T14:57:04.553Z] 
[2023-11-16T14:57:04.553Z] cat: /root/.vscode-server/data/Machine/settings.json: No such file or directory
[2023-11-16T14:57:04.553Z] Exit code 1
[2023-11-16T14:57:04.553Z] Stop (3 ms): Run in container: cat /root/.vscode-server/data/Machine/settings.json
[2023-11-16T14:57:04.553Z] Start: Run in container: test -d /root/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
[2023-11-16T14:57:04.555Z] 
[2023-11-16T14:57:04.555Z] 
[2023-11-16T14:57:04.556Z] Exit code 1
[2023-11-16T14:57:04.556Z] Stop (3 ms): Run in container: test -d /root/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
[2023-11-16T14:57:04.556Z] Start: Run in container: test -d /vscode/vscode-server/bin/linux-x64/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
[2023-11-16T14:57:04.557Z] 
[2023-11-16T14:57:04.558Z] 
[2023-11-16T14:57:04.558Z] Stop (2 ms): Run in container: test -d /vscode/vscode-server/bin/linux-x64/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
[2023-11-16T14:57:04.558Z] Start: Run in container: mkdir -p '/root/.vscode-server/bin' && ln -snf '/vscode/vscode-server/bin/linux-x64/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e' '/root/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e'
[2023-11-16T14:57:04.561Z] 
[2023-11-16T14:57:04.561Z] 
[2023-11-16T14:57:04.561Z] Stop (3 ms): Run in container: mkdir -p '/root/.vscode-server/bin' && ln -snf '/vscode/vscode-server/bin/linux-x64/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e' '/root/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e'
[2023-11-16T14:57:04.561Z] Start: Run in container: touch '/vscode/vscode-server/bin/linux-x64/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e'
[2023-11-16T14:57:04.561Z] Start: Launching Dev Containers helper.
[2023-11-16T14:57:04.562Z] ssh-agent: SSH_AUTH_SOCK not set on wsl host.
[2023-11-16T14:57:04.562Z] ssh-agent: SSH_AUTH_SOCK not set on local host.
[2023-11-16T14:57:04.562Z] ssh-agent: SSH_AUTH_SOCK in container (/tmp/vscode-ssh-auth-a0bb44c4-f9e0-43cb-9fd3-51381150ce2c.sock) forwarded to local host (\\.\pipe\openssh-ssh-agent).
[2023-11-16T14:57:04.564Z] 
[2023-11-16T14:57:04.564Z] 
[2023-11-16T14:57:04.564Z] Stop (3 ms): Run in container: touch '/vscode/vscode-server/bin/linux-x64/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e'
[2023-11-16T14:57:04.564Z] Start: Run in container: test -e /tmp/.X11-unix/X0
[2023-11-16T14:57:04.566Z] 
[2023-11-16T14:57:04.566Z] 
[2023-11-16T14:57:04.566Z] Exit code 1
[2023-11-16T14:57:04.566Z] Stop (2 ms): Run in container: test -e /tmp/.X11-unix/X0
[2023-11-16T14:57:04.566Z] Start: Run in container: mkdir -p '/tmp/.X11-unix'
[2023-11-16T14:57:04.568Z] 
[2023-11-16T14:57:04.569Z] 
[2023-11-16T14:57:04.569Z] Stop (3 ms): Run in container: mkdir -p '/tmp/.X11-unix'
[2023-11-16T14:57:04.569Z] X11 forwarding: DISPLAY in container (:0) forwarded to wsl host (:0).
[2023-11-16T14:57:04.569Z] Start: Run in container: gpgconf --list-dir agent-socket
[2023-11-16T14:57:04.571Z] /root/.gnupg/S.gpg-agent
[2023-11-16T14:57:04.571Z] 
[2023-11-16T14:57:04.571Z] Stop (2 ms): Run in container: gpgconf --list-dir agent-socket
[2023-11-16T14:57:04.571Z] Start: Run in container: gpgconf --list-dir homedir
[2023-11-16T14:57:04.573Z] /root/.gnupg
[2023-11-16T14:57:04.574Z] 
[2023-11-16T14:57:04.574Z] Stop (3 ms): Run in container: gpgconf --list-dir homedir
[2023-11-16T14:57:04.574Z] Start: Run in container: ls '/root/.gnupg/private-keys-v1.d' 2>/dev/null
[2023-11-16T14:57:04.576Z] 
[2023-11-16T14:57:04.576Z] 
[2023-11-16T14:57:04.576Z] Exit code 2
[2023-11-16T14:57:04.576Z] Stop (2 ms): Run in container: ls '/root/.gnupg/private-keys-v1.d' 2>/dev/null
[2023-11-16T14:57:04.576Z] Start: Run in Host: gpgconf --list-dir agent-extra-socket
[2023-11-16T14:57:04.579Z] Stop (3 ms): Run in Host: gpgconf --list-dir agent-extra-socket
[2023-11-16T14:57:04.580Z] /run/user/1000/gnupg/S.gpg-agent.extra
[2023-11-16T14:57:04.580Z] 
[2023-11-16T14:57:04.580Z] Start: Run in container: mkdir -p -m 700 '/root/.gnupg'
[2023-11-16T14:57:04.580Z] gpg-agent: Socket in container (/root/.gnupg/S.gpg-agent) forwarded to wsl host (/run/user/1000/gnupg/S.gpg-agent.extra).
[2023-11-16T14:57:04.582Z] 
[2023-11-16T14:57:04.583Z] 
[2023-11-16T14:57:04.583Z] Stop (3 ms): Run in container: mkdir -p -m 700 '/root/.gnupg'
[2023-11-16T14:57:04.583Z] Start: Run in container: command -v docker >/dev/null 2>&1
[2023-11-16T14:57:04.583Z] Start: Run in Host: gpgconf --list-dir homedir
[2023-11-16T14:57:04.586Z] 
[2023-11-16T14:57:04.586Z] 
[2023-11-16T14:57:04.586Z] Exit code 127
[2023-11-16T14:57:04.586Z] Stop (3 ms): Run in container: command -v docker >/dev/null 2>&1
[2023-11-16T14:57:04.586Z] Start: Run in Host: docker exec -i -u root 2598043c0c80b4d9897bac5e0297cc57cd6ec5924e6e580092fe5343d376a220 /bin/sh
[2023-11-16T14:57:04.586Z] Stop (25 ms): Launching Dev Containers helper.
[2023-11-16T14:57:04.586Z] userEnvProbe: loginInteractiveShell (default)
[2023-11-16T14:57:04.587Z] Start: Run in container: test -f '/tmp/devcontainers-ea039853-32cf-4451-959d-72d713049c591700146617283/env-loginInteractiveShell.json'
[2023-11-16T14:57:04.587Z] Stop (4 ms): Run in Host: gpgconf --list-dir homedir
[2023-11-16T14:57:04.587Z] /home/myself/.gnupg
[2023-11-16T14:57:04.587Z] 
[2023-11-16T14:57:04.591Z] Start: Run in container: echo ~
[2023-11-16T14:57:04.591Z] 
[2023-11-16T14:57:04.592Z] 
[2023-11-16T14:57:04.592Z] Exit code 1
[2023-11-16T14:57:04.592Z] Stop (5 ms): Run in container: test -f '/tmp/devcontainers-ea039853-32cf-4451-959d-72d713049c591700146617283/env-loginInteractiveShell.json'
[2023-11-16T14:57:04.592Z] Start: Run in container: gpgconf --list-dir homedir
[2023-11-16T14:57:04.592Z] userEnvProbe: not found in cache
[2023-11-16T14:57:04.592Z] userEnvProbe shell: /bin/bash
[2023-11-16T14:57:04.595Z] /root/.gnupg
[2023-11-16T14:57:04.595Z] 
[2023-11-16T14:57:04.595Z] Stop (3 ms): Run in container: gpgconf --list-dir homedir
[2023-11-16T14:57:04.597Z] Start: Run in container: # Test for /root/.ssh/known_hosts and ssh
[2023-11-16T14:57:04.600Z] 
[2023-11-16T14:57:04.600Z] 
[2023-11-16T14:57:04.600Z] Stop (3 ms): Run in container: # Test for /root/.ssh/known_hosts and ssh
[2023-11-16T14:57:04.600Z] Start: Run in container: # Copy /home/myself/.ssh/known_hosts to /root/.ssh/known_hosts
[2023-11-16T14:57:04.605Z] Stop (405 ms): Run in Host: docker exec -i -u root 2598043c0c80b4d9897bac5e0297cc57cd6ec5924e6e580092fe5343d376a220 /bin/sh -c echo "New container started. Keep-alive process started." ; export VSCODE_REMOTE_CONTAINERS_SESSION=ea039853-32cf-4451-959d-72d713049c591700146617283 ; /bin/sh
[2023-11-16T14:57:04.606Z] Stop (153 ms): Run in Host: docker exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=ea039853-32cf-4451-959d-72d713049c591700146617283 2598043c0c80b4d9897bac5e0297cc57cd6ec5924e6e580092fe5343d376a220 /bin/sh
[2023-11-16T14:57:04.606Z] Stop (20 ms): Run in Host: docker exec -i -u root 2598043c0c80b4d9897bac5e0297cc57cd6ec5924e6e580092fe5343d376a220 /bin/sh
[2023-11-16T14:57:04.611Z] Keep-alive process ended.
[2023-11-16T14:57:04.612Z] Error reading shell environment.
[2023-11-16T14:57:04.612Z] Start: Run in Host: gpg-connect-agent updatestartuptty /bye
[2023-11-16T14:57:04.612Z] Start: Run in container: mkdir -p '/tmp/devcontainers-ea039853-32cf-4451-959d-72d713049c591700146617283' && cat > '/tmp/devcontainers-ea039853-32cf-4451-959d-72d713049c591700146617283/env-loginInteractiveShell.json' << 'envJSON'
[2023-11-16T14:57:04.613Z] Failed to cache user env: Shell server failed: Error: unexpected end of parent stream
	at jo.destroy (c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:26638)
	at jo.write (c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:27379)
	at c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:29482
	at c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:14866
	at c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:17539
	at c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:23891
	at r (c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:17487)
	at c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:17532
	at Object.cb (c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:24002)
	at c (c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:21998)
	at l (c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:22260)
	at c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:22343
	at s (c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:30:5371)
	at Socket.<anonymous> (c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:30:5472)
	at Socket.emit (node:events:513:28)
	at addChunk (node:internal/streams/readable:324:12)
	at readableAddChunk (node:internal/streams/readable:297:9)
	at Readable.push (node:internal/streams/readable:234:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[2023-11-16T14:57:04.613Z] Start: Run in container: umask 077 && XRD="/tmp/user/$(id -u)" && mkdir -p $XRD && echo $XRD
[2023-11-16T14:57:04.615Z] Shell server failed: Error: unexpected end of parent stream
	at jo.destroy (c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:26638)
	at jo.write (c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:27379)
	at c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:29482
	at c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:14866
	at c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:17539
	at c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:23891
	at r (c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:17487)
	at c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:17532
	at Object.cb (c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:24002)
	at c (c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:21998)
	at l (c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:22260)
	at c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:27:22343
	at s (c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:30:5371)
	at Socket.<anonymous> (c:\Users\myself\.vscode\extensions\ms-vscode-remote.remote-containers-0.321.0\dist\extension\extension.js:30:5472)
	at Socket.emit (node:events:513:28)
	at addChunk (node:internal/streams/readable:324:12)
	at readableAddChunk (node:internal/streams/readable:297:9)
	at Readable.push (node:internal/streams/readable:234:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[2023-11-16T14:57:04.618Z] Host server: packet-stream asked to read after closed { value: { code: 1, signal: null }, end: false, req: -141 }
packet-stream asked to read after closed { value: { code: 0, signal: null }, end: false, req: -16 }
[2023-11-16T14:57:04.619Z] Host server: packet-stream asked to read after closed { value: { code: 0, signal: null }, end: false, req: -77 }
[2023-11-16T14:57:04.620Z] Host server: packet-stream asked to read after closed { value: { code: 0, signal: null }, end: false, req: -96 }
[2023-11-16T14:57:04.678Z] Host server: packet-stream asked to read after closed { value: { code: 255, signal: null }, end: false, req: -117 }
[2023-11-16T14:57:04.692Z] Stop (6376 ms): Run: wsl -d Ubuntu-22.04 -e /bin/sh -c cd '/home/myself/git/test' && /bin/sh
[2023-11-16T14:57:04.692Z] Host server terminated (code: 0, signal: null).
[2023-11-16T14:57:07.441Z] Start: Run: wsl -d Ubuntu-22.04 -e wslpath -u \\wsl.localhost\Ubuntu-22.04\home\myself\git\test
[2023-11-16T14:57:07.654Z] Stop (213 ms): Run: wsl -d Ubuntu-22.04 -e wslpath -u \\wsl.localhost\Ubuntu-22.04\home\myself\git\test
```

Steps to Reproduce:
1. Open Repo in WSL
2. Start "DevContainers: Rebuild and Reopen in Container"

I already tried to reset my docker desktop to factory settings without progress.

Does this issue occur when you try this locally?: When running the same devcontainer directly on windows, it works
Does this issue occur when you try this locally and all extensions are disabled?:

**Comment by ahemwe** [comment]
Running the same from a Ubuntu 20.04 WSL works well. I've installed Ubuntu 22.04 in WSL yesterday. Can I somehow check for a corrupted distribution in WSL?

**Comment by ahemwe** [comment]
Might be related to #7505 but unfortunately there was no other solution than reinstalling windows completely.
I've reinstalled my WSL distro twice and this fixed the issue for some hours, but eventually, the error reoccurred.
Any hint?

**Comment by chrmarti** [comment]
'Error reading shell environment.' indicates something went wrong before, although it could be the same underlying issue as for the 'unexpected end of parent stream' error. Not sure what might have triggered this, was this working in earlier versions of the Dev Containers extension?

**Comment by ahemwe** [comment]
I tried to reinstall the Ubuntu 22.04 distribution in WSL2 twice. Second time I did reinstall even the whole WSL (windows feature) and Docker.

In both cases, the issue was gone for about 1 day. After a further reboot, the issue re-occured. 

I'm not aware of any update of the extension.

**Comment by ahemwe** [comment]
Can I provide any further information (logs, configs...) that might help to pinpoint the issue?
@chrmarti

**Comment by chrmarti** [comment]
Could you retry with the current version of Dev Containers (0.327.0 or 0.328.0-pre-release) and again append the log here? I have improved logging a bit, maybe we'll get some additional hints on what is going on. Thanks.

**Comment by ahemwe** [comment]
Today I got the version 1.85 update including vs code server updates and I can't reproduce the issue.
I'll test it until mid of next week and give more solid feedback.
Would be great if this issue has already been fixed.

**Comment by ahemwe** [comment]
For some reason, the issue disappeared. Most probably when updating to 1.85 and installing the latest vscode server.

Closing this issue.

Thanks a lot for taking it serious @chrmarti
