### ISSUE TITLE
[Remote-SSH Bug]: Connection Timout because there is 'bash' in script with connection command

### ISSUE THREAD

**Issue by Byongsoo** [microsoft/vscode-remote-release#9235]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully (when remove 'bash' in script with connection command')

### ->

Remote-SSH
  1. Connection Commad : "C:\Program Files\OpenSSH\ssh.exe" -T -D 51752 "bee0_romulus" bash
  2. Resut : Resolver error: Error: Connecting with SSH timed out

CMD prompt(cmd.exe)
  1. Command : C:\Users\User>"C:\Program Files\OpenSSH\ssh.exe" -T -D 51752 "bee0_romulus" bash
  2. Result : Nothging!! Just wait the response.

The result of both Remote-SSH and CMD prompt comment are same!!
But When I remove 'bash' at CMD prompt command, It works well (See Expected Behavior)

### Expected Behavior

C:\Users\User>"C:\Program Files\OpenSSH\ssh.exe" -T -D 51752 "bee0_romulus"
Welcome to Bee
          __         .' '.
        _/__)        .   .       .
       (8|)_}}- .      .        .
         \__)    '. . ' ' .  . '

system info:
OS............: Ubuntu 20.04.5 LTS (x86_64)
Hostname......: byeongsugong-romulus

worker info:
CPU...........: 16 core
Memory........: 40 GB
Disk..........: 200 GB
Worker name...: romulus
Project name..: lupa
Image name....: lupa-20-04

--- Project notice ---

--- Project notice ---
null

### Steps To Reproduce

Enviroment
  1. I installed VS Code on the windows OS 10
  2. I try to the Linux PC(SSH Server) using VS Code with Remote SSH Extention
  3. I can connec the Linux PC (SSH Server) using Putty successfully.
  4. I had already connected the server using Remote-SSH Extection. 
      So I have the server in the Remote-Explore Extextion also.

Step to Reproduce
  1. Connect to ssh (linux) server using Remote-Explore Extention (select Connect In New Winods ...)
      At that time threr is no error and I can open linux terminal and send linux commands (ex, ls, cd etc.)
  2. Open a folder of the server (VS Code File -> Open Folder)
  3. Occure  "Connection Timeout"

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[13:48:07.164] Log Level: 2
[13:48:07.173] VS Code version: 1.79.2
[13:48:07.173] Remote-SSH version: remote-ssh@0.105.2023080715
[13:48:07.173] win32 x64
[13:48:07.214] SSH Resolver called for "ssh-remote+bee0_romulus", attempt 1
[13:48:07.214] "remote.SSH.useLocalServer": false
[13:48:07.215] "remote.SSH.showLoginTerminal": false
[13:48:07.215] "remote.SSH.remotePlatform": {"bee0_romulus":"linux","bee0_linuxpc":"linux","gonghongnas.synology.me":"linux"}
[13:48:07.215] "remote.SSH.path":  C:\Program Files\OpenSSH\ssh.exe
[13:48:07.215] "remote.SSH.configFile": undefined
[13:48:07.215] "remote.SSH.useFlock": true
[13:48:07.215] "remote.SSH.lockfilesInTmp": false
[13:48:07.215] "remote.SSH.localServerDownload": auto
[13:48:07.215] "remote.SSH.remoteServerListenOnSocket": false
[13:48:07.215] "remote.SSH.showLoginTerminal": false
[13:48:07.215] "remote.SSH.defaultExtensions": []
[13:48:07.215] "remote.SSH.loglevel": 2
[13:48:07.215] "remote.SSH.enableDynamicForwarding": true
[13:48:07.216] "remote.SSH.enableRemoteCommand": false
[13:48:07.216] "remote.SSH.serverPickPortsFromRange": {}
[13:48:07.216] "remote.SSH.serverInstallPath": {}
[13:48:07.218] SSH Resolver called for host: bee0_romulus
[13:48:07.218] Setting up SSH remote "bee0_romulus"
[13:48:07.222] Using commit id "695af097c7bd098fbf017ce3ac85e09bbc5dda06" and quality "stable" for server
[13:48:07.227] Install and start server if needed
[13:48:07.232] Checking ssh with " C:\Program Files\OpenSSH\ssh.exe -V"
[13:48:07.234] Got error from ssh: spawn  C:\Program Files\OpenSSH\ssh.exe ENOENT
[13:48:07.234] The specified path  C:\Program Files\OpenSSH\ssh.exe is not a valid SSH binary
[13:48:07.234] Checking ssh with "C:\Program Files\OpenSSH\ssh.exe -V"
[13:48:07.295] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.3.3

[13:48:07.306] Running script with connection command: "C:\Program Files\OpenSSH\ssh.exe" -T -D 51752 "bee0_romulus" bash
[13:48:07.308] Terminal shell path: C:\windows\System32\cmd.exe
[13:48:24.322] Resolver error: Error: Connecting with SSH timed out
	at m.Timeout (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.105.2023080715\out\extension.js:2:618097)
	at Timeout._onTimeout (c:\Users\User\.vscode\extensions\ms-vscode-remote.remote-ssh-0.105.2023080715\out\extension.js:2:734405)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[13:48:24.330] ------
```

</p>
</details>

### Anything else?

I have found below issue.
https://github.com/microsoft/vscode-remote-release/issues/6215

In the issue, I can found below comment.
'''
@chrmarti are you adding bash or powershell at the end of your connection command? That could be causing this error:
https://github.com/microsoft/vscode-remote-ssh/commit/21d0cc043142cf48bde68433baf4300eb79f81cf

and then I completely removed the specified shell:
https://github.com/microsoft/vscode-remote-ssh/commit/533b67be58e677112024bffd4549f761d64df7b7
'''

But I can not access the URL because that the URL return 404 (NOT Found).

Could you let me share the URL contents Or know the method remove the 'bash' in the below connection command?

[13:48:07.306] Running script with connection command: "C:\Program Files\OpenSSH\ssh.exe" -T -D 51752 "bee0_romulus" **bash**

**Comment by roblourens** [comment]
This is the problem your log shows

```
[13:48:07.234] Got error from ssh: spawn  C:\Program Files\OpenSSH\ssh.exe ENOENT
[13:48:07.234] The specified path  C:\Program Files\OpenSSH\ssh.exe is not a valid SSH binary
```

that seems like the real issue to me

**Comment by Byongsoo** [comment]
@roblourens 
Hi~ roblourens.
Thank you for sharing the error log.
I search the error message in the google, I could fix my issue by following below steps.

1. Remove the remote server information at ssh config and known_host files. ( both C:\Users\User\.ssh and C:\ProgramData\ssh)
2. Close all opened VS Code windows
3. Open new VS Code
4. Connect new session in Remove-SSH with "-i" option
   The 'i' option guides at https://code.visualstudio.com/docs/remote/ssh#_remember-hosts-and-advanced-settings
