### ISSUE TITLE
Remote-SSH: Local server download fails in 1.85

### ISSUE THREAD

**Issue by drisspg** [microsoft/vscode-remote-release#9246]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

Connects succsefully

### Steps To Reproduce

I recently updated vscode-insider versions, was working prior to update

### Remote-SSH Log

``` Shell
[12:04:33.468] Terminating local server
[12:04:33.470] Resolver error: Error: XHR failed
    at k.onerror (vscode-file://vscode-app/private/var/folders/g1/cvs2rnpx60qc3b4_x72xvxlr0000gn/T/AppTranslocation/1EDA0CA8-65F0-4A71-83AE-D707E1E03A65/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:2027)
[12:04:33.474] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"1","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Unknown","exitCodeLabel":""},"measures":{"resolveAttempts":1,"isExecServer":0,"timing.totalResolveTime":7217,"timing.preSshTime":27,"timing.establishSshTime":6250}}
[12:04:33.475] ------




[12:04:33.481] Local server exit: 15
```

### Anything else?

Same error when running without local_server mode

``` Shell
[12:06:01.219] Downloading VS Code server locally...
[12:06:01.310] Resolver error: Error: XHR failed
    at k.onerror (vscode-file://vscode-app/private/var/folders/g1/cvs2rnpx60qc3b4_x72xvxlr0000gn/T/AppTranslocation/1EDA0CA8-65F0-4A71-83AE-D707E1E03A65/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:2027)
[12:06:01.311] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"0","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"Unknown","exitCodeLabel":""},"measures":{"resolveAttempts":1,"isExecServer":0,"timing.totalResolveTime":8002,"timing.preSshTime":1670,"timing.establishSshTime":6229,"timing.scriptTime":6332}}
[12:06:01.312] ------
```

**Comment by drisspg** [comment]
I am trying to manual install the server with 

```
wget https://update.code.visualstudio.com/commit:b3b84b5239037a2f0ef8499306df9a3bacda4105/server-linux-x64/stable
```

And I am getting a 404 not found

**Comment by roblourens** [comment]
That's an insiders commit, but the url says `/stable`, where did you get that from, is it in a log?

Can you check the "Extension Host" or "Window" log for network-related errors?

**Comment by drisspg** [comment]
Sorry that is an old wget command I have tried in the past, what is the correct path? 

In Extension Host I see
```Shell
2023-11-29 09:58:46.520 [error] Error: XHR failed
    at k.onerror (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:2027) _workbench.downloadResource undefined
2023-11-29 09:58:46.526 [error] [resolveAuthority(ssh-remote,1)][5055ms] returned an error XHR failed
2023-11-29 09:58:46.610 [error] CodeExpectedError: ENOPRO: No file system provider found for resource
```

**Comment by roblourens** [comment]
The correct one would be `/insider`

**Comment by justin39** [comment]
Seeing the same issue on the latest Insiders build:
```javascript
[17:27:36.505] Resolver error: Error: XHR failed
    at k.onerror (vscode-file://vscode-app/c:/Users/justinw/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:95:2027)
```

Insiders build version:

```
Version: 1.85.0-insider (user setup)
Commit: 8762127fc97b8aaae5f3a0dd6a6d853d9a1b7574
Date: 2023-11-29T17:38:23.440Z
Electron: 25.9.6
ElectronBuildId: 25427645
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19044
```

The version of the "Remote - SSH" extension doesn't seem to matter between pre-release/stable/older versions. The workaround noted above does work (i.e. `wget https://update.code.visualstudio.com/commit:8762127fc97b8aaae5f3a0dd6a6d853d9a1b7574/server-linux-x64/insider`).

**Comment by roblourens** [comment]
Do you have anything like a corporate proxy configured? Do you have the `http.proxy` setting set?

**Comment by justin39** [comment]
> Do you have anything like a corporate proxy configured? Do you have the `http.proxy` setting set?

Yes, this is behind a corporate proxy - `http.proxy` is not set

**Comment by AxisRay** [comment]
Same error
```
版本: 1.85.0-insider (Universal)
提交: c46c2f120b96f1d538333b263e42d1f133a200f0
日期: 2023-12-05T09:55:05.986Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0
Remote-SSH: v0.108.2023112915
```

```
[21:42:43.442] Got request to download on client for {"artifact":"cli-alpine-x64","destPath":"/root/.vscode-server-insiders/vscode-cli-c46c2f120b96f1d538333b263e42d1f133a200f0.tar.gz"}
[21:42:43.442] Downloading VS Code server locally...
[21:42:43.923] Terminating local server
[21:42:43.925] Resolver error: Error: XHR failed
    at k.onerror (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:2027)
[21:42:43.932] ------

```

**Comment by roblourens** [comment]
Oh, yes I forgot about this: https://code.visualstudio.com/updates/v1_85#_new-cdn

There is a new CDN that we will download from, and your sysadmin may have to allow that new hostname

**Comment by EISHKARAN** [comment]
I have even facing the same issue till last evening I was able to connect to the server and then it got disconnected after that when I tried its giving me XHR failed.  
Tried deleting the whole vscode insiders by deleting it's dot files and installing it again but didn't help. 

`[13:10:31.195] Got request to download on client for {"artifact":"cli-alpine-x64","destPath":"/shared/home/v_eishkaran_singh/.vscode-server-insiders/vscode-cli-ab0520decb7284b2b2a9bbe3ababea57ac83c86b.tar.gz"}
[13:10:31.196] Downloading VS Code server locally...
[13:10:32.165] Terminating local server
[13:10:32.166] Resolver error: Error: XHR failed
    at k.onerror (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:95:2027)
[13:10:32.181] Local server exit: 15
[13:10:32.206] ------
`
Help out how to resolve it from the user end cause the server can't be accessed in my case.

**Comment by roblourens** [comment]
@AxisRay I'm referring to the fact that some configurations only allow connections to a fixed set of allowed hosts, and I'm assuming that is part of the issue here since we have similar issues every time we connect to a new hostname. I don't think there's an issue on our end.

**Comment by AxisRay** [comment]
I roughly understand what you're saying. My server doesn't have internet access, but my local machine does (with no firewall limit). In this situation, VSCode attempts to download locally and then upload to the server. The conditions triggering this issue are as described, and you can try to replicate it. I've tested it, and the problem persists in both the insider and stable versions of VSCode.
@roblourens

**Comment by AxisRay** [comment]
> Access to XMLHttpRequest at 'https://vscode.download.prss.microsoft.com/dbazure/download/insider/c46c2f1…/vscode_cli_alpine_x64_cli.tar.gz' (redirected from 'https://update.code.visualstudio.com/commit:c46c2f1…/cli-alpine-x64/insider') from origin 'vscode-file://vscode-app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

My assessment of the cause of this issue is based on the the error message.
This error is caused by the Same-Origin Policy enforced by browsers, which restricts web pages from making requests to a domain different from the one that served the web page. In this case, the browser(vscode) is blocking a cross-origin request to 'https://vscode.download.prss.microsoft.com/' because the response does not include the necessary 'Access-Control-Allow-Origin' header.

To resolve this issue, one common approach is to configure CORS headers on the server. The server should include the 'Access-Control-Allow-Origin' header in the response, specifying the allowed domain(s) to access the resource. Alternatively, just set "Access-Control-Allow-Origin" to *.

Therefore, this requires the administrator to configure the CDN correctly.

**Comment by EISHKARAN** [comment]
@AxisRay I guess being a user I think I found a solution. At least it worked for me hoping it can work for you even. 
If you are using Mac OS or Linux 
Go to terminal 
type in 
`sudo nano /etc/resolv.conf`
It'll prompt you to give your password enter it and you will be directed to a file 
In that file you will find the keyword "nameserver" where it is in the next line add this line 
`nameserver 8.8.8.8`
Do this in terminal and then go to vscode and try to reconnect to server. 
Hope it works
@roblourens

**Comment by roblourens** [comment]
Oh, I can repro this. Sorry that it took me so long to get to that point. But if I force Remote-SSH to do a local download, it does fail with this new URL.

**Comment by camillehe1992** [comment]
I met the same issue after upgrading the vscode from 1.84.2 to the latest version 1.85.0 last week in windows 11. I didn't find a good workaround, so just revert to 1.84.2. And it works. 
Will keep using 1.84.2 till someone or VSCode team address the issue.

**Comment by drisspg** [comment]
Should the fix be available on insiders already? I am still seeing this issue so I am curious if there is any updates I need to do with vs-code?

**Comment by Edgar-Nieto-BH** [comment]
> Should the fix be available on insiders already? I am still seeing this issue so I am curious if there is any updates I need to do with vs-code?

AFAIK it is already available in 1.85.1, just updated and everything works as expected.

**Comment by ytwanghaoyu** [comment]
with 1.85.1 the issue seems still exists?
![image](https://github.com/microsoft/vscode-remote-release/assets/25526912/c29865d5-20b4-421e-8276-7300fc905619)

**Comment by alerdenisov** [comment]
I getting unnamed error after update to 1.85.1 (before the same as issue starter).

```sh
[00:11:39.010] Log Level: 2
[00:11:39.031] VS Code version: 1.85.1
[00:11:39.031] Remote-SSH version: remote-ssh@0.107.1
[00:11:39.031] darwin arm64
[00:11:39.053] SSH Resolver called for "ssh-remote+64.226.96.123", attempt 1
[00:11:39.053] "remote.SSH.useLocalServer": true
[00:11:39.053] "remote.SSH.useExecServer": false
[00:11:39.054] "remote.SSH.path": undefined
[00:11:39.054] "remote.SSH.configFile": undefined
[00:11:39.054] "remote.SSH.useFlock": true
[00:11:39.054] "remote.SSH.lockfilesInTmp": false
[00:11:39.054] "remote.SSH.localServerDownload": auto
[00:11:39.054] "remote.SSH.remoteServerListenOnSocket": false
[00:11:39.054] "remote.SSH.showLoginTerminal": false
[00:11:39.054] "remote.SSH.defaultExtensions": []
[00:11:39.054] "remote.SSH.loglevel": 2
[00:11:39.055] "remote.SSH.enableDynamicForwarding": true
[00:11:39.055] "remote.SSH.enableRemoteCommand": false
[00:11:39.055] "remote.SSH.serverPickPortsFromRange": {}
[00:11:39.055] "remote.SSH.serverInstallPath": {}
[00:11:39.081] SSH Resolver called for host: 64.226.96.123
[00:11:39.081] Setting up SSH remote "64.226.96.123"
[00:11:39.083] Acquiring local install lock: /var/folders/vl/70lkrgq51yjbtfhkjg_ntplh0000gn/T/vscode-remote-ssh-e8b1a4ee-install.lock
[00:11:39.085] Looking for existing server data file at /Users/aler/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-e8b1a4ee-0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2-0.107.1-tr/data.json
[00:11:39.085] Using commit id "0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2" and quality "stable" for server
[00:11:39.087] Install and start server if needed
[00:11:39.095] PATH: /Users/aler/.tiup/bin:/Users/aler/Library/pnpm:/usr/local/opt/python/libexec/bin:/Users/aler/.flutter/bin:/Users/aler/.n/bin:/Users/aler/.n:/Users/aler/.avm/bin:/Users/aler/.local/share/solana/install/active_release/bin:/Users/aler/.local/share/solana/install/active_release/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/aler/.cargo/bin:/Users/aler/go/bin:/Users/aler/.yarn/bin:/Users/aler/Library/Android/sdk/platform-toolscode:/Users/aler/protoc/bin:/Users/aler/.pub-cache/bin
[00:11:39.095] Checking ssh with "ssh -V"
[00:11:39.117] > OpenSSH_9.0p1, LibreSSL 3.3.6

[00:11:39.120] askpass server listening on /var/folders/vl/70lkrgq51yjbtfhkjg_ntplh0000gn/T/vscode-ssh-askpass-12044e595f252da8dc3512f8d3f8bb81b0f7018f.sock
[00:11:39.121] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/vl/70lkrgq51yjbtfhkjg_ntplh0000gn/T/vscode-ssh-askpass-f23653312fbebf16e12740e18a83d7f24fdc7ec1.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","54579","-o","ConnectTimeout=15","64.226.96.123"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/aler/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-e8b1a4ee-0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2-0.107.1-tr/data.json"}
[00:11:39.121] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.NGbFtISCyJ/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/aler/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/aler/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/vl/70lkrgq51yjbtfhkjg_ntplh0000gn/T/vscode-ssh-askpass-12044e595f252da8dc3512f8d3f8bb81b0f7018f.sock"}
[00:11:39.122] Spawned 22266
[00:11:39.254] > local-server-1> Running ssh connection command: "-v -T -D 54579 -o ConnectTimeout=15 64.226.96.123"
[00:11:39.260] > local-server-1> Spawned ssh, pid=22293
[00:11:39.267] stderr> OpenSSH_9.0p1, LibreSSL 3.3.6
[00:11:39.494] stderr> debug1: Server host key: ssh-ed25519 SHA256:CqKh8FZqPr5VBmwtCIaWfAaoO43XvsB0qRX01Xkciyc
[00:11:39.802] stderr> Authenticated to 64.226.96.123 ([64.226.96.123]:22) using "publickey".
[00:11:40.275] > Welcome to Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-91-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>  * Introducing Expanded Security Maintenance for Applications.
>    Receive updates to over 25,000 software packages with your
>    Ubuntu Pro subscription. Free for personal use.
> 
>      https://ubuntu.com/pro
> 
> Expanded Security Maintenance for Applications is not enabled.
> 
> 77 updates can be applied immediately.
> To see these additional updates run: apt list --upgradable
> 
> Enable ESM Apps to receive additional future security updates.
> See https://ubuntu.com/esm or run: sudo pro status
> 
> 
> The list of available updates is more than a week old.
> To check for new updates run: sudo apt update
[00:11:40.314] > ready: 9b1fbd4a9ba6
[00:11:40.357] > Linux 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023
[00:11:40.357] Platform: linux
[00:11:40.399] > /bin/bash
[00:11:40.400] Shell: bash
[00:11:40.400] Creating bash subshell inside "bash"
[00:11:40.443] > bash version:  5.1.16(1)-release
[00:11:40.494] > 9b1fbd4a9ba6: running
[00:11:40.496] stderr> mkdir: cannot create directory ‘/root/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2’: No space left on device
[00:11:40.498] > Creating the server install dir failed...
> 9b1fbd4a9ba6: start
> exitCode==34==
> listeningOn====
> osReleaseId====
> arch====
> vscodeArch====
> bitness====
> tmpDir==/run/user/0==
> platform====
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
[00:11:40.535] > serverStartTime====
> 9b1fbd4a9ba6: end
[00:11:40.535] Received install output: 
exitCode==34==
listeningOn====
osReleaseId====
arch====
vscodeArch====
bitness====
tmpDir==/run/user/0==
platform====
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====serverStartTime====

[00:11:40.536] Failed to parse remote port from server output
[00:11:40.536] Terminating local server
[00:11:40.540] Resolver error: Error: 
	at g.Create (/Users/aler/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:642703)
	at t.handleInstallOutput (/Users/aler/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:640069)
	at e (/Users/aler/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:700300)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /Users/aler/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:722169
	at async t.withShowDetailsEvent (/Users/aler/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:725828)
	at async /Users/aler/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:697005
	at async C (/Users/aler/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:695056)
	at async t.resolveWithLocalServer (/Users/aler/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:696545)
	at async I (/Users/aler/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:719392)
	at async t.resolve (/Users/aler/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:723199)
	at async /Users/aler/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:907003
[00:11:40.541] Local server exit: 15
[00:11:40.544] ------




[00:11:40.859] Opening exec server for ssh-remote+64.226.96.123
[00:11:40.865] Initizing new exec server for ssh-remote+64.226.96.123
[00:11:40.867] Acquiring local install lock: /var/folders/vl/70lkrgq51yjbtfhkjg_ntplh0000gn/T/vscode-remote-ssh-e8b1a4ee-install.lock
[00:11:40.869] Looking for existing server data file at /Users/aler/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-e8b1a4ee-0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2-0.107.1-es/data.json
[00:11:40.870] Using commit id "0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2" and quality "stable" for server
[00:11:40.872] Install and start server if needed
[00:11:40.878] askpass server listening on /var/folders/vl/70lkrgq51yjbtfhkjg_ntplh0000gn/T/vscode-ssh-askpass-58b6cfb910931c3c06bb931fbc4a893dbba87d85.sock
[00:11:40.879] Spawning local server with {"serverId":2,"ipcHandlePath":"/var/folders/vl/70lkrgq51yjbtfhkjg_ntplh0000gn/T/vscode-ssh-askpass-709333a9adefa087747365e96326ff32aa95b68d.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","54590","-o","ConnectTimeout=15","64.226.96.123"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/aler/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-e8b1a4ee-0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2-0.107.1-es/data.json"}
[00:11:40.879] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.NGbFtISCyJ/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/aler/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/aler/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/vl/70lkrgq51yjbtfhkjg_ntplh0000gn/T/vscode-ssh-askpass-58b6cfb910931c3c06bb931fbc4a893dbba87d85.sock"}
[00:11:40.880] Spawned 22297
[00:11:40.955] > local-server-2> Running ssh connection command: "-v -T -D 54590 -o ConnectTimeout=15 64.226.96.123"
[00:11:40.958] > local-server-2> Spawned ssh, pid=22311
[00:11:40.961] stderr> OpenSSH_9.0p1, LibreSSL 3.3.6
[00:11:41.198] stderr> debug1: Server host key: ssh-ed25519 SHA256:CqKh8FZqPr5VBmwtCIaWfAaoO43XvsB0qRX01Xkciyc
[00:11:41.580] stderr> Authenticated to 64.226.96.123 ([64.226.96.123]:22) using "publickey".
[00:11:41.718] > Welcome to Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-91-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
>  * Introducing Expanded Security Maintenance for Applications.
>    Receive updates to over 25,000 software packages with your
>    Ubuntu Pro subscription. Free for personal use.
> 
>      https://ubuntu.com/pro
> 
> Expanded Security Maintenance for Applications is not enabled.
> 
> 77 updates can be applied immediately.
> To see these additional updates run: apt list --upgradable
> 
> Enable ESM Apps to receive additional future security updates.
> See https://ubuntu.com/esm or run: sudo pro status
> 
> 
> The list of available updates is more than a week old.
> To check for new updates run: sudo apt update
[00:11:41.766] > ready: f5427af27a0f
[00:11:41.815] > Linux 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023
[00:11:41.815] Platform: linux
[00:11:41.867] > /bin/bash
[00:11:41.867] Shell: bash
[00:11:41.867] Creating bash subshell inside "bash"
[00:11:41.922] > bash version:  5.1.16(1)-release
[00:11:41.976] > bash version:  5.1.16(1)-release
[00:11:41.981] > f5427af27a0f: running
[00:11:41.990] > Installing to /root/.vscode-server...
[00:11:41.993] > f5427af27a0f%%1%%
[00:11:41.994] > Downloading with wget
[00:11:42.035] > wget download failed
> Cannot write to ‘vscode-cli-0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2.tar.gz’ (Success).
> printenv:
>     SHELL=/bin/bash
>     PWD=/root/.vscode-server
>     LOGNAME=root
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/root
>     LANG=C.UTF-8
>     VSCODE_AGENT_FOLDER=/root/.vscode-server
>     SSH_CONNECTION=83.220.185.125 54593 64.226.96.123 22
>     XDG_SESSION_CLASS=user
>     USER=root
>     SHLVL=1
>     XDG_SESSION_ID=397
>     XDG_RUNTIME_DIR=/run/user/0
>     SSH_CLIENT=83.220.185.125 54593 22
>     XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/0/bus
>     OLDPWD=/root
>     _=/usr/bin/printenv
> Trigger local server download
> f5427af27a0f:trigger_server_download
> artifact==cli-alpine-x64==
> destFolder==/root/.vscode-server==
> destFolder2==/vscode-cli-0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2.tar.gz==
> f5427af27a0f:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /root/.vscode-server/vscode-cli-0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2.tar.gz.done and vscode-server.tar.gz to exist
>  
[00:11:42.035] Got request to download on client for {"artifact":"cli-alpine-x64","destPath":"/root/.vscode-server/vscode-cli-0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2.tar.gz"}
[00:11:42.036] Downloading VS Code server locally...
[00:11:42.310] Downloaded VS Code server to /var/folders/vl/70lkrgq51yjbtfhkjg_ntplh0000gn/T/3f00a16d-e678-486d-bc5b-192e22ef5b90
[00:11:42.319] Renamed VS Code server to /var/folders/vl/70lkrgq51yjbtfhkjg_ntplh0000gn/T/vscode_server_1704143502310/vscode-cli-0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2.tar.gz
[00:11:42.332] PATH: /Users/aler/.tiup/bin:/Users/aler/Library/pnpm:/usr/local/opt/python/libexec/bin:/Users/aler/.flutter/bin:/Users/aler/.n/bin:/Users/aler/.n:/Users/aler/.avm/bin:/Users/aler/.local/share/solana/install/active_release/bin:/Users/aler/.local/share/solana/install/active_release/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/aler/.cargo/bin:/Users/aler/go/bin:/Users/aler/.yarn/bin:/Users/aler/Library/Android/sdk/platform-toolscode:/Users/aler/protoc/bin:/Users/aler/.pub-cache/bin
[00:11:42.332] Checking ssh with "ssh -V"
[00:11:42.340] > OpenSSH_9.0p1, LibreSSL 3.3.6

[00:11:42.341] Testing scp with "scp"
[00:11:42.348] scp exited with code: 1
[00:11:42.348] Got stderr from scp: usage: scp [-346ABCOpqRrsTv] [-c cipher] [-D sftp_server_path] [-F ssh_config]
           [-i identity_file] [-J destination] [-l limit]
           [-o ssh_option] [-P port] [-S program] source ... target
[00:11:42.349] Copying file to remote with scp -o ConnectTimeout=15 'vscode-cli-0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2.tar.gz' 'vscode-cli-0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2.tar.gz.done' '64.226.96.123':'/root/.vscode-server'
[00:11:42.349] Using cwd: file:///var/folders/vl/70lkrgq51yjbtfhkjg_ntplh0000gn/T/vscode_server_1704143502310
[00:11:43.427] > vscode-cli-0ee08df0cf4527e40edc9aa28f4b5bd38b   0%    0     0.0KB/s   --:-- ETA
[00:11:43.436] > vscode-cli-0ee08df0cf4527e40edc9aa28f4b5bd38b   0%   32KB 370.1KB/s   00:22 ETA
> scp: write remote "/root/.vscode-server/vscode-cli-0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2.tar.gz": Failure
[00:11:43.480] > scp: failed to upload file vscode-cli-0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2.tar.gz to /root/.vscode-server
[00:11:43.562] > vscode-cli-0ee08df0cf4527e40edc9aa28f4b5bd38b   0%    0     0.0KB/s   --:-- ETA
[00:11:43.606] > vscode-cli-0ee08df0cf4527e40edc9aa28f4b5bd38b 100%    9     0.2KB/s   00:00    
> scp: write remote "/root/.vscode-server/vscode-cli-0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2.tar.gz.done": Failure
[00:11:43.648] > scp: failed to upload file vscode-cli-0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2.tar.gz.done to /root/.vscode-server
[00:11:43.936] "Copy server to host" terminal command done
[00:11:45.036] > Found flag and server on host
[00:11:45.039] > f5427af27a0f%%2%%
> tar --version:
> tar (GNU tar) 1.34
> Copyright (C) 2021 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
[00:11:45.041] stderr> tar: This does not look like a tar archive
[00:11:45.042] stderr> 
[00:11:45.042] stderr> gzip: stdin: unexpected end of file
[00:11:45.043] stderr> tar: Child returned status 1
[00:11:45.043] stderr> tar: Error is not recoverable: exiting now
[00:11:45.044] > ERROR: tar exited with non-0 exit code: 0
> Already attempted local download, failing
> f5427af27a0f: start
> exitCode==37==
[00:11:45.077] > listeningOn====
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/0==
> platform==linux==
> unpackResult==error==
> didLocalDownload==1==
> downloadTime====
> installTime==5==
> serverStartTime====
> execServerToken==f1189891da14==
> f5427af27a0f: end
[00:11:45.077] Received install output: 
exitCode==37==listeningOn====
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/0==
platform==linux==
unpackResult==error==
didLocalDownload==1==
downloadTime====
installTime==5==
serverStartTime====
execServerToken==f1189891da14==

[00:11:45.078] Terminating local server
[00:11:45.088] Exec server for ssh-remote+64.226.96.123 failed: Error: Failed to install the VS Code Server
[00:11:45.088] Error opening exec server for ssh-remote+64.226.96.123: Error: Failed to install the VS Code Server
[00:11:45.091] Local server exit: 15

```

**Comment by levihuayuzhang** [comment]
when I try to connect to container on a remote machine through SSH:
1. set up proxy on remote host
2. add user to docker group (https://docs.docker.com/engine/install/linux-postinstall/)
3. add proxy for containers (https://docs.docker.com/network/proxy/)
4. restart remote docker daemon
5. try to connect and download vscode-server in container on remote machine automatically.

**Comment by DiegoCao** [comment]
Also encountered this problem, and tried the most common solution:

1. SSH to the remote server via terminal
2. Remove the ~/.vscode-server/
```
rm -rf ~/.vscode-server/
```
3. If remove failed, use lsof to find open files and kill the processes that access files under ~/.vscode-server/
4. Retry with Vscode

Whenever the connection failed i feel this procedure can resolve the problem in most cases.
