### ISSUE TITLE
Failed to parse remote port from server output when install  code server for windows

### ISSUE THREAD

**Issue by monotone** [microsoft/vscode-remote-release#9256]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

worker fine

### Steps To Reproduce

1. client: mac os.     server: windows 
2. flow the doc

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

when set `remote.SSH.useLocalServer: false`:
```
[21:19:15.595] Log Level: 2
[21:19:15.603] SSH Resolver called for "ssh-remote+win", attempt 1
[21:19:15.603] "remote.SSH.useLocalServer": false
[21:19:15.603] "remote.SSH.useExecServer": false
[21:19:15.603] "remote.SSH.showLoginTerminal": false
[21:19:15.604] "remote.SSH.remotePlatform": {"win":"windows"}
[21:19:15.604] "remote.SSH.path": undefined
[21:19:15.604] "remote.SSH.configFile": /Users/billow/.ssh/config
[21:19:15.604] "remote.SSH.useFlock": true
[21:19:15.604] "remote.SSH.lockfilesInTmp": false
[21:19:15.604] "remote.SSH.localServerDownload": auto
[21:19:15.605] "remote.SSH.remoteServerListenOnSocket": false
[21:19:15.605] "remote.SSH.showLoginTerminal": false
[21:19:15.605] "remote.SSH.defaultExtensions": []
[21:19:15.605] "remote.SSH.loglevel": 2
[21:19:15.605] "remote.SSH.enableDynamicForwarding": true
[21:19:15.605] "remote.SSH.enableRemoteCommand": false
[21:19:15.605] "remote.SSH.serverPickPortsFromRange": {}
[21:19:15.606] "remote.SSH.serverInstallPath": {}
[21:19:15.612] VS Code version: 1.84.2
[21:19:15.613] Remote-SSH version: remote-ssh@0.107.1
[21:19:15.613] darwin x64
[21:19:15.615] SSH Resolver called for host: win
[21:19:15.615] Setting up SSH remote "win"
[21:19:15.617] Using commit id "1a5daa3a0231a0fbba4f14db7ec463cf99d7768e" and quality "stable" for server
[21:19:15.619] Install and start server if needed
[21:19:15.622] PATH: ****
[21:19:15.622] Checking ssh with "ssh -V"
[21:19:15.628] > OpenSSH_8.6p1, LibreSSL 3.3.6

[21:19:15.630] Using SSH config file "/Users/billow/.ssh/config"
[21:19:15.631] Remote command length: 6226/8192 characters
[21:19:15.631] Running script with connection command: ssh -T -D 51789 -o ConnectTimeout=15 -F '/Users/billow/.ssh/config' win powershell
[21:19:17.469] > Windows PowerShell
> ��Ȩ���� (C) Microsoft Corporation����������Ȩ����
> 
> �����µĿ�ƽ̨ PowerShell https://aka.ms/pscore6
> 
> PS C:\Users\billow> 
[21:19:17.470] Got some output, clearing connection timeout
[21:19:17.711] "install" terminal command done
[21:19:17.712] Install terminal quit with output: PS C:\Users\billow> 
[21:19:17.712] Received install output: PS C:\Users\billow> 
[21:19:17.713] Failed to parse remote port from server output
[21:19:17.716] Resolver error: Error: 
	at g.Create (/Users/billow/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:642703)
	at t.handleInstallOutput (/Users/billow/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:640069)
	at t.tryInstall (/Users/billow/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:761983)
	at async /Users/billow/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:722522
	at async t.withShowDetailsEvent (/Users/billow/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:725828)
	at async I (/Users/billow/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:719493)
	at async t.resolve (/Users/billow/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:723199)
	at async /Users/billow/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:907003
[21:19:17.720] ------
```

And with ``remote.SSH.useLocalServer: true`, I got:

```
[21:28:48.136] Log Level: 2
[21:28:48.151] SSH Resolver called for "ssh-remote+win", attempt 1
[21:28:48.153] "remote.SSH.useLocalServer": true
[21:28:48.153] "remote.SSH.useExecServer": false
[21:28:48.153] "remote.SSH.path": undefined
[21:28:48.154] "remote.SSH.configFile": /Users/billow/.ssh/config
[21:28:48.154] "remote.SSH.useFlock": true
[21:28:48.154] "remote.SSH.lockfilesInTmp": false
[21:28:48.155] "remote.SSH.localServerDownload": auto
[21:28:48.155] "remote.SSH.remoteServerListenOnSocket": false
[21:28:48.155] "remote.SSH.showLoginTerminal": false
[21:28:48.155] "remote.SSH.defaultExtensions": []
[21:28:48.155] "remote.SSH.loglevel": 2
[21:28:48.156] "remote.SSH.enableDynamicForwarding": true
[21:28:48.156] "remote.SSH.enableRemoteCommand": false
[21:28:48.156] "remote.SSH.serverPickPortsFromRange": {}
[21:28:48.156] "remote.SSH.serverInstallPath": {}
[21:28:48.163] VS Code version: 1.84.2
[21:28:48.163] Remote-SSH version: remote-ssh@0.107.1
[21:28:48.163] darwin x64
[21:28:48.166] SSH Resolver called for host: win
[21:28:48.166] Setting up SSH remote "win"
[21:28:48.171] Acquiring local install lock: /var/folders/6w/839ldj3x2t5b1nqb8tmcs9k40000gn/T/vscode-remote-ssh-0bf7cb59-install.lock
[21:28:48.173] Looking for existing server data file at /Users/billow/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-0bf7cb59-1a5daa3a0231a0fbba4f14db7ec463cf99d7768e-0.107.1-tr/data.json
[21:28:48.173] Using commit id "1a5daa3a0231a0fbba4f14db7ec463cf99d7768e" and quality "stable" for server
[21:28:48.176] Install and start server if needed
[21:28:48.180] PATH: /Users/billow/Library/pnpm:/usr/local/sbin:/usr/local/Cellar/ruby/3.2.2_1/bin:/Users/billow/fvm/versions/stable/bin:/Users/billow/.nvmd/bin:/Users/billow/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/billow/.cargo/bin:/Users/billow/.orbstack/bin:/Users/billow/go/bin:/Users/billow/fvm/default/bin:/Users/billow/Library/Android/sdk/emulator:/Users/billow/Library/Android/sdk/platform-tools:/Users/billow/Library/Android/sdk/tools:/Users/billow/Library/Android/sdk/tools/bin
[21:28:48.180] Checking ssh with "ssh -V"
[21:28:48.189] > OpenSSH_8.6p1, LibreSSL 3.3.6

[21:28:48.194] Using SSH config file "/Users/billow/.ssh/config"
[21:28:48.196] askpass server listening on /var/folders/6w/839ldj3x2t5b1nqb8tmcs9k40000gn/T/vscode-ssh-askpass-66965c75b3868f5f20253a3509188cdb8e6e2e37.sock
[21:28:48.196] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/6w/839ldj3x2t5b1nqb8tmcs9k40000gn/T/vscode-ssh-askpass-65ec05b25940d89464cfc9d47708fece0dab1930.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","51930","-o","ConnectTimeout=15","-F","/Users/billow/.ssh/config","win","powershell"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/billow/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-0bf7cb59-1a5daa3a0231a0fbba4f14db7ec463cf99d7768e-0.107.1-tr/data.json"}
[21:28:48.196] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.gXqyp0hXEt/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/billow/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/billow/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/6w/839ldj3x2t5b1nqb8tmcs9k40000gn/T/vscode-ssh-askpass-66965c75b3868f5f20253a3509188cdb8e6e2e37.sock"}
[21:28:48.197] Spawned 5313
[21:28:48.425] > local-server-1> Running ssh connection command: "-v -T -D 51930 -o ConnectTimeout=15 -F /Users/billow/.ssh/config win powershell"
[21:28:48.429] > local-server-1> Spawned ssh, pid=5321
[21:28:48.439] stderr> OpenSSH_8.6p1, LibreSSL 3.3.6
[21:28:48.662] stderr> debug1: Server host key: ssh-ed25519 SHA256:zSNXaRivWUQ0icTeZzr8DRo57EyWbCpK7uuD7lByyzg
[21:28:48.724] stderr> Authenticated to 192.168.1.19 ([192.168.1.19]:22).
[21:28:48.910] > Windows PowerShell
> ��Ȩ���� (C) Microsoft Corporation����������Ȩ����
> 
> �����µĿ�ƽ̨ PowerShell https://aka.ms/pscore6
[21:28:49.099] > PS C:\Users\billow> 
[21:28:49.202] > echo 'ready: fab787da4841'
[21:28:50.794] stderr> Transferred: sent 3360, received 3056 bytes, in 2.1 seconds
[21:28:50.794] stderr> Bytes per second: sent 1623.9, received 1477.0
[21:28:50.795] > local-server-1> ssh child died, shutting down
[21:28:50.801] Local server exit: 0
[21:28:50.802] Received install output: local-server-1> Running ssh connection command: "-v -T -D 51930 -o ConnectTimeout=15 -F /Users/billow/.ssh/config win powershell"
local-server-1> Spawned ssh, pid=5321
OpenSSH_8.6p1, LibreSSL 3.3.6
debug1: Server host key: ssh-ed25519 SHA256:zSNXaRivWUQ0icTeZzr8DRo57EyWbCpK7uuD7lByyzg
Authenticated to 192.168.1.19 ([192.168.1.19]:22).
Windows PowerShell
��Ȩ���� (C) Microsoft Corporation����������Ȩ����

�����µĿ�ƽ̨ PowerShell https://aka.ms/pscore6

PS C:\Users\billow> 
echo 'ready: fab787da4841'
Transferred: sent 3360, received 3056 bytes, in 2.1 seconds
Bytes per second: sent 1623.9, received 1477.0
local-server-1> ssh child died, shutting down

[21:28:50.804] Failed to parse remote port from server output
[21:28:50.810] Resolver error: Error: 
	at g.Create (/Users/billow/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:642703)
	at t.handleInstallOutput (/Users/billow/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:640069)
	at e (/Users/billow/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:700300)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /Users/billow/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:722169
	at async t.withShowDetailsEvent (/Users/billow/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:725828)
	at async /Users/billow/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:697005
	at async C (/Users/billow/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:695056)
	at async t.resolveWithLocalServer (/Users/billow/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:696545)
	at async I (/Users/billow/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:719392)
	at async t.resolve (/Users/billow/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:723199)
	at async /Users/billow/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:907003
[21:28:50.813] ------
```

</p>
</details>

**Comment by monotone** [comment]
@roblourens what should i do next？

**Comment by monotone** [comment]
```bash
/usr/local/bin
$ echo "echo hello" | ssh -T -D 51789 -o ConnectTimeout=15 -F '/Users/billow/.ssh/config' win powershell                                                                 2 ↵


Windows PowerShell
��Ȩ���� (C) Microsoft Corporation����������Ȩ��

�����µĿ�ƽ̨ PowerShell https://aka.ms/pscore6

PS C:\Users\billow> echo hello
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
/usr/local/bin
$
```

I dont known which part of the command is breaking it. Only know now I can use tunnel mode to access my windows....

but can not use remote ssh .

**Comment by roblourens** [comment]
By "figure out" I mean that you can try removing parts of it to see what causes it to work. eg does it work without the `-T`?
