### ISSUE TITLE
Windows: Detect if Docker daemon does not have access to the Wayland socket

### ISSUE THREAD

**Issue by artm** [microsoft/vscode-remote-release#9293]
- VSCode Version: 1.85.0
- Local OS Version: Ubuntu 22.04
- Remote OS Version: not relevant as it never gets that far
- Remote Extension/Connection Type: Dev Containers v0.327.0 and Docker Desktop for linux as container runtime

- Logs:
```
...
[2023-12-10T11:42:11.338Z] Start: Starting container
[2023-12-10T11:42:11.338Z] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount source=/home/artm/src/clock,target=/usr/share/nginx/html,type=bind,consistency=cached --mount type=volume,src=vscode,dst=/vscode --mount type=bind,src=/run/user/1000/wayland-0,dst=/tmp/vscode-wayland-d5213ca0-a4ec-4610-99c8-8f9c10ac4854.sock -l devcontainer.local_folder=/home/artm/src/clock -l devcontainer.config_file=/home/artm/src/clock/.devcontainer/devcontainer.json --entrypoint /bin/sh vsc-clock-301948f0c9645b23e46be384c3ddd58f66365927455a28b442453ceafc652518 -c echo Container started
[2023-12-10T11:42:11.441Z] docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /run/user/1000/wayland-0.
See 'docker run --help'.
[2023-12-10T11:42:11.450Z] Stop (112 ms): Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount source=/home/artm/src/clock,target=/usr/share/nginx/html,type=bind,consistency=cached --mount type=volume,src=vscode,dst=/vscode --mount type=bind,src=/run/user/1000/wayland-0,dst=/tmp/vscode-wayland-d5213ca0-a4ec-4610-99c8-8f9c10ac4854.sock -l devcontainer.local_folder=/home/artm/src/clock -l devcontainer.config_file=/home/artm/src/clock/.devcontainer/devcontainer.json --entrypoint /bin/sh vsc-clock-301948f0c9645b23e46be384c3ddd58f66365927455a28b442453ceafc652518 -c echo Container started
[2023-12-10T11:42:11.451Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/artm/src/clock --filter label=devcontainer.config_file=/home/artm/src/clock/.devcontainer/devcontainer.json
[2023-12-10T11:42:11.537Z] Stop (86 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/artm/src/clock --filter label=devcontainer.config_file=/home/artm/src/clock/.devcontainer/devcontainer.json
[2023-12-10T11:42:11.539Z] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount source=/home/artm/src/clock,target=/usr/share/nginx/html,type=bind,consistency=cached --mount type=volume,src=vscode,dst=/vscode --mount type=bind,src=/run/user/1000/wayland-0,dst=/tmp/vscode-wayland-d5213ca0-a4ec-4610-99c8-8f9c10ac4854.sock -l devcontainer.local_folder=/home/artm/src/clock -l devcontainer.config_file=/home/artm/src/clock/.devcontainer/devcontainer.json --entrypoint /bin/sh vsc-clock-301948f0c9645b23e46be384c3ddd58f66365927455a28b442453ceafc652518 -c echo Container started
[2023-12-10T11:42:11.540Z] trap "exit 0" 15
[2023-12-10T11:42:11.540Z] exec "$@"
[2023-12-10T11:42:11.540Z] while sleep 1 & wait $!; do :; done -
[2023-12-10T11:42:11.540Z]     at J$ (/home/artm/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:462:1253)
[2023-12-10T11:42:11.540Z]     at $J (/home/artm/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:462:997)
[2023-12-10T11:42:11.541Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-12-10T11:42:11.541Z]     at async tAA (/home/artm/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:479:3660)
[2023-12-10T11:42:11.541Z]     at async CC (/home/artm/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:479:4775)
[2023-12-10T11:42:11.542Z]     at async NeA (/home/artm/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:11107)
[2023-12-10T11:42:11.542Z]     at async MeA (/home/artm/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:10848)
...
```

Steps to Reproduce:

1. clone the repo https://github.com/gastropoda/clock
2. open it in VSCode
3. issue "Dev Containers: rebuild and reopen in container"

Does this issue occur when you try this locally?: not relevant
Does this issue occur when you try this locally and all extensions are disabled?: not relevant

**Comment by artm** [comment]
I think it's because Docker Desktop for linux runs in its own VM which is isolated from my Wayland, but `WAYLAND_DISPLAY` gets leaked into some relevant environment somewhere.

**Comment by artm** [comment]
Found it, there is an extension setting "Dev › Containers: Mount Wayland Socket / Controls whether a Wayland socket, if one exists, should be mounted into the Dev Container." which prevents this from happening. But perhaps the extension could detect that itself somehow?

**Comment by shanrath** [comment]
> Found it, there is an extension setting "Dev › Containers: Mount Wayland Socket / Controls whether a Wayland socket, if one exists, should be mounted into the Dev Container." which prevents this from happening. But perhaps the extension could detect that itself somehow?

Either way, it seems like a strange thing to set to 'true' by default, if it breaks devcontainer startup.

**Comment by artm** [comment]
> > Found it, there is an extension setting "Dev › Containers: Mount Wayland Socket / Controls whether a Wayland socket, if one exists, should be mounted into the Dev Container." which prevents this from happening. But perhaps the extension could detect that itself somehow?
> 
> Either way, it seems like a strange thing to set to 'true' by default, if it breaks devcontainer startup.

It only breaks in my specific case: VSCode sees the wayland socket but docker daemon doesn't. I think native linux docker wouldn't have this problem and is traditionally used more often than Docker Desktop on linux.

**Comment by davide-prade** [comment]
I have the same issue on the following system:
- Ubuntu 22.04.3 LTS
- Docker Desktop 4.27.0 (135262)
- VScode 1.86.0
- Dev Containers v0.338.1

> docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /run/user/1000/wayland-0.

The VScode 1.85.1 with Dev Containers v0.321.0 works.

**Comment by davide-prade** [comment]
@chrmarti I confirm, even in my case disabling the `Dev › Containers: Mount Wayland Socket` option of the "Dev Containers" extension works.

**Comment by Spikhalskiy** [comment]
Got this issue on

Ubuntu 24.04 LTS
Docker Desktop 4.30.0 (149282)
VScode 1.89.1
Dev Containers v0.362.0

**Comment by clementgoclock** [comment]
Same problem here 

Fedora 40, VSC 1.89.1, DevContainer v0.362.0, Docker Desktop 4.29

Had to disable Wayland socket as well. Could it be off by default or asked before doing something ?

![image](https://github.com/microsoft/vscode-remote-release/assets/126659374/3fb712bf-8042-41b7-a0b1-cbf65237e7bd)

**Comment by chrmarti** [comment]
0.370.0-pre-release automatically disables the feature when it sees the mount fail.
