### ISSUE TITLE
Dev Container Configuration '.devcontainer/devcontainer.json'  file already exists.

### ISSUE THREAD

**Issue by alexanderilyin** [microsoft/vscode-remote-release#9303]
- VSCode Version: Version: 1.85.1 (Universal) Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
- Local OS Version: macOS 13.6.3 (22G436)
- Remote OS Version: Ubuntu 22.04.3 LTS
- Remote Extension/Connection Type: Containers

## Logs:

```
[347397 ms] Start: Run: docker compose version --short
[347418 ms] Error: Command failed: docker compose version --short
    at Wg (/home/myusername/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:460:889)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TJ (/home/myusername/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:390:23529)
    at async _eA (/home/myusername/.vscode-remote-containers/dist/dev-containers-cli-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:35354)
[347454 ms] Exit code 1
```

Steps to Reproduce:

1. Install Docker
2. Do NOT install Compose Plugin (https://docs.docker.com/compose/install/linux/#install-using-the-repository)
3. Configure Dev Container using `docker-compose.yml`

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: No

## Notes

This would not be a problem if you start project from scratch and create devcontainer.json, cause at some point you would install Compose plugin for `docker` but when someone will start using project on new machine he will get misleading error message:

```
Dev Container Configuration '.devcontainer/devcontainer.json'  file already exists.
```

Other part of the UX problem is that related log is not opened and you have to find it via:

```
> Dev Containers: Show Container Log
```

Which is confusing for new users.

```[tasklist]
### Tasks
```

**Comment by westsiderz** [comment]
I am using Ubuntu 22.04. I had VSCode installed previously, today it updated itself. I have a .devconatiner file, which I have developed in Windows. Getting the same errors. The config file do work on WIndows.

**Comment by GaTechThomas** [comment]
Same. It just stopped working. Killed all dev progress. Trying extension version rollback.

**Comment by datasalaryman** [comment]
Is this still ongoing? I'm opening a fresh github repo on a container and I'm experiencing the same issue.

**Comment by AzureWolf** [comment]
I'm experiencing the same, specifically on mac. Windows is working smoothly. Just started recently.

**Comment by ynakayama999** [comment]
Try this hack. I resolved, anyway.
https://github.com/microsoft/vscode-remote-release/issues/9302#issuecomment-1854476541

**Comment by AzureWolf** [comment]
> Try this hack. I resolved, anyway. [#9302 (comment)](https://github.com/microsoft/vscode-remote-release/issues/9302#issuecomment-1854476541)

Thank you for this, but it did not work for me. However, it made me go down a path where I found the solution that worked for me (on Mac): https://github.com/microsoft/vscode/issues/202096

Hope this helps anyone else!

**Comment by jeebb** [comment]
Not sure why but the latest pre-release version (v0.331) still does not work for me. I downgraded the version to v0.321 and it works well for now. Hope that this info could help.

**Comment by BMMevius** [comment]
> Try this hack. I resolved, anyway. [#9302 (comment)](https://github.com/microsoft/vscode-remote-release/issues/9302#issuecomment-1854476541)

For me this gave me the error that a `.env` file was missing. It is strange that adding an `initializeCommand` gives me the actual error.
```
[2024-01-18T13:56:04.767Z] Dev Containers 0.327.0 in VS Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2).
[2024-01-18T13:56:04.767Z] Start: Resolving Remote
[2024-01-18T13:56:04.804Z] Setting up container for folder or workspace: /home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard
[2024-01-18T13:56:04.872Z] Start: Check Docker is running
[2024-01-18T13:56:04.872Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2024-01-18T13:56:04.908Z] Stop (36 ms): Run: docker version --format {{.Server.APIVersion}}
[2024-01-18T13:56:04.908Z] Server API version: 1.43
[2024-01-18T13:56:04.908Z] Stop (36 ms): Check Docker is running
[2024-01-18T13:56:04.909Z] Start: Run: docker volume ls -q
[2024-01-18T13:56:04.936Z] Stop (27 ms): Run: docker volume ls -q
[2024-01-18T13:56:04.937Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard --filter label=vsch.quality=stable
[2024-01-18T13:56:04.961Z] Stop (24 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard --filter label=vsch.quality=stable
[2024-01-18T13:56:04.962Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard --filter label=devcontainer.config_file=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard/.devcontainer/devcontainer.json
[2024-01-18T13:56:04.989Z] Stop (27 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard --filter label=devcontainer.config_file=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard/.devcontainer/devcontainer.json
[2024-01-18T13:56:04.989Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard
[2024-01-18T13:56:05.024Z] Stop (35 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard
[2024-01-18T13:56:05.025Z] Start: Run: /opt/visual-studio-code/code --ms-enable-electron-run-as-node /home/thomas/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard --id-label devcontainer.local_folder=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard --id-label devcontainer.config_file=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard/.devcontainer/devcontainer.json --mount-workspace-git-root
[2024-01-18T13:56:05.329Z] @devcontainers/cli 0.54.1. Node.js v18.15.0. linux 6.7.0-arch3-1 x64.
[2024-01-18T13:56:05.329Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard --filter label=devcontainer.config_file=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard/.devcontainer/devcontainer.json
[2024-01-18T13:56:05.353Z] Stop (24 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard --filter label=devcontainer.config_file=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard/.devcontainer/devcontainer.json
[2024-01-18T13:56:05.370Z] Stop (345 ms): Run: /opt/visual-studio-code/code --ms-enable-electron-run-as-node /home/thomas/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard --id-label devcontainer.local_folder=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard --id-label devcontainer.config_file=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard/.devcontainer/devcontainer.json --mount-workspace-git-root
[2024-01-18T13:56:05.370Z] Start: Run: /opt/visual-studio-code/code --ms-enable-electron-run-as-node /home/thomas/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/thomas/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-2dd886e6-c73e-46b9-bee7-06d4cb9fb0de1705586164129 --workspace-folder /home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard --id-label devcontainer.config_file=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-01-18T13:56:05.657Z] @devcontainers/cli 0.54.1. Node.js v18.15.0. linux 6.7.0-arch3-1 x64.
[2024-01-18T13:56:05.657Z] Start: Run: docker buildx version
[2024-01-18T13:56:05.785Z] Stop (128 ms): Run: docker buildx version
[2024-01-18T13:56:05.786Z] github.com/docker/buildx 0.12.1 30feaa1a915b869ebc2eea6328624b49facd4bfb
[2024-01-18T13:56:05.786Z]
[2024-01-18T13:56:05.786Z] Start: Resolving Remote
[2024-01-18T13:56:05.794Z] Running the initializeCommand from devcontainer.json...
 
[2024-01-18T13:56:05.795Z] Start: Run: /bin/sh -c ls
[2024-01-18T13:56:05.808Z] azure-pipelines.yml   package.json           run-fangage-dashboard.sh
bunfig.toml      package-lock.json      src
bun.lockb        postcss.config.js      tailwind.config.ts
Dockerfile       public             tsconfig.json
Dockerfile.dockerignore  README.md
next.config.js       run-fangage-dashboard.ps1
[2024-01-18T13:56:05.809Z] Stop (14 ms): Run: /bin/sh -c ls
[2024-01-18T13:56:05.809Z]
[2024-01-18T13:56:05.811Z] Start: Run: docker-compose version --short
[2024-01-18T13:56:05.849Z] Stop (38 ms): Run: docker-compose version --short
[2024-01-18T13:56:05.850Z] Docker Compose version: 2.24.0
[2024-01-18T13:56:05.850Z] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=smartstadium --filter label=com.docker.compose.service=smart-stadium-fangage-dashboard
[2024-01-18T13:56:05.873Z] Stop (23 ms): Run: docker ps -q -a --filter label=com.docker.compose.project=smartstadium --filter label=com.docker.compose.service=smart-stadium-fangage-dashboard
[2024-01-18T13:56:05.874Z] Start: Run: docker inspect --type container d677fbecc5fb
[2024-01-18T13:56:05.898Z] Stop (24 ms): Run: docker inspect --type container d677fbecc5fb
[2024-01-18T13:56:05.899Z] Start: Removing existing container.
[2024-01-18T13:56:05.899Z] Start: Run: docker rm -f d677fbecc5fb2112d49f831b38e8f8c5aad1ce4b3eefa91432313720bde7cbe0
[2024-01-18T13:56:06.474Z] Stop (575 ms): Run: docker rm -f d677fbecc5fb2112d49f831b38e8f8c5aad1ce4b3eefa91432313720bde7cbe0
[2024-01-18T13:56:06.474Z] Stop (575 ms): Removing existing container.
[2024-01-18T13:56:06.476Z] Start: Run: docker-compose -f /home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/docker-compose.yml -f /home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard/.devcontainer/docker-compose.yml --profile * config
[2024-01-18T13:56:06.555Z] Stop (79 ms): Run: docker-compose -f /home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/docker-compose.yml -f /home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard/.devcontainer/docker-compose.yml --profile * config
[2024-01-18T13:56:06.555Z]
[2024-01-18T13:56:06.555Z] time="2024-01-18T14:56:06+01:00" level=warning msg="The \"AZURE_STORAGE_KEY\" variable is not set. Defaulting to a blank string."
env file /home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/.env not found: stat /home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/.env: no such file or directory
 
[2024-01-18T13:56:06.555Z] Exit code 14
[2024-01-18T13:56:06.558Z] Error: Command failed: docker-compose -f /home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/docker-compose.yml -f /home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard/.devcontainer/docker-compose.yml --profile * config
[2024-01-18T13:56:06.558Z]     at Wg (/home/thomas/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:460:889)
[2024-01-18T13:56:06.558Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-01-18T13:56:06.558Z]     at async L$ (/home/thomas/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:427:1481)
[2024-01-18T13:56:06.558Z]     at async N$ (/home/thomas/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:409:3165)
[2024-01-18T13:56:06.558Z]     at async tAA (/home/thomas/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:479:3833)
[2024-01-18T13:56:06.558Z]     at async CC (/home/thomas/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:479:4775)
[2024-01-18T13:56:06.559Z]     at async NeA (/home/thomas/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:11107)
[2024-01-18T13:56:06.559Z]     at async MeA (/home/thomas/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js:612:10848)
[2024-01-18T13:56:06.575Z] Stop (1205 ms): Run: /opt/visual-studio-code/code --ms-enable-electron-run-as-node /home/thomas/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/thomas/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-2dd886e6-c73e-46b9-bee7-06d4cb9fb0de1705586164129 --workspace-folder /home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard --id-label devcontainer.config_file=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-01-18T13:56:06.575Z] Exit code 1
[2024-01-18T13:56:06.580Z] Command failed: /opt/visual-studio-code/code --ms-enable-electron-run-as-node /home/thomas/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/thomas/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-2dd886e6-c73e-46b9-bee7-06d4cb9fb0de1705586164129 --workspace-folder /home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard --id-label devcontainer.config_file=/home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/SmartStadiumFangageDashboard/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-01-18T13:56:06.580Z] Exit code 1
```

**Comment by chrmarti** [comment]
The warning dialog (`Dev Container Configuration '.devcontainer/devcontainer.json' file already exists.`) can have various underlying reasons. I have released a fix that will instead show an error dialog explaining that the config could not be loaded (which is the real reason and wasn't handled properly). The fix should also make the `initializeCommand` workaround obsolete.

Could everyone seeing this give Dev Containers 0.334.0-pre-release a try and if it still fails post the log output here? Thanks!

@BMMevius Your log shows an issue with a missing env file:
```
env file /home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/.env not found: stat /home/thomas/Projects/sorama/src/Applications/Tools/SmartStadium/.env: no such file or directory
```

**Comment by Levi-Montgomery** [comment]
Switching to that pre-release version fixed the issue for me.

**Comment by ringe** [comment]
Addinng a .env file fixed the issue for me.

**Comment by JackCaster** [comment]
I get the same error message
![image](https://github.com/microsoft/vscode-remote-release/assets/18400141/be901815-a340-4b0f-9afd-ccd9a1ad346d)
but in reality the problem is that the corporate network is blocking the connection. I was quite confused until I realized I needed to deactivate the firewall. The error message was misleading.

```
2024-01-25 08:48:13.697 [error] CodeExpectedError: cannot open file://wsl.localhost/Ubuntu/home/xxx/dev/accumulate/.devcontainer/devcontainer.json. Detail: Unable to read file '\\wsl.localhost\Ubuntu\home\xxx\dev\accumulate\.devcontainer\devcontainer.json' (Unknown (FileSystemError): UNC host 'wsl.localhost' access is not allowed. Please update the 'security.allowedUNCHosts' setting if you want to allow this host.)
    at r.$tryOpenDocument (vscode-file://vscode-app/c:/Users/xxx/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2163:62448)
```

**Comment by chrmarti** [comment]
@JackCaster Could you open a new issue with the complete log and the steps you took to get there? Thanks!

I should have mentioned: Currently the latest Dev Containers versions need VS Code Insiders. Please make sure you are giving the latest version a try (currently Dev Containers 0.336.0-pre-release).

**Comment by jaques-sam** [comment]
Still experiencing the issue, I don't know how to solve this. Adding an .env file nor switching to pre-release helps for me.

**Comment by jaques-sam** [comment]
Linked to https://github.com/devcontainers/features/issues/221

**Comment by chrmarti** [comment]
@jaques-sam Make sure to try with VS Code Insiders (https://code.visualstudio.com/insiders/) and the latest pre-release version of Dev Containers (currently 0.338.0). (The current pre-release version only installs with VS Code Insiders, this will change when VS Code 1.86 is released and alongside it a new Dev Containers stable version later this week.)

**Comment by pantelis** [comment]
In Ubuntu 22.04, and VSCode in 1.86.0, switching the devcontainer extension only to pre-release version fixes the issue for me.

**Comment by chrmarti** [comment]
If you still see this, make sure you have the latest Dev Containers extension version installed. For any remaining problems please open new issues. Thanks!
