### ISSUE TITLE
SSH Asking for password twice

### ISSUE THREAD

**Issue by KillahB33** [microsoft/vscode-remote-release#9306]
Does this issue occur when all extensions are disabled?: I can't do the command mentioned above because I am using an extension.

- VS Code Version: 
Version: 1.85.0 (user setup)
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T20:48:09.019Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
- OS Version: 
Windows 10

Steps to Reproduce:

Use SSH to connect to another host
It connects successfully and I see the paths available there, and then it asks for password again. 
Entering the password again or cancelling doesn't seem to make a difference.

I have the following extensions related to SSH
Remote - SSH
Remote - SSH: Editing Config
Remote Explorer

Here is the stack when I cancel:
[10:05:22.966] [Forwarding server port 46499] Got connection 1
[10:05:23.603] [Forwarding server port 46499] Got connection 2
[10:05:26.066] [Forwarding server port 46499] Got connection 3
[10:05:28.481] Opening exec server for ssh-remote+192.168.0.300
[10:05:28.501] Initizing new exec server for ssh-remote+192.168.0.300
[10:05:28.519] Using commit id "af28b32d7e553898b2a91af498b1fb666fdebe0c" and quality "stable" for server
[10:05:28.522] Install and start server if needed
[10:05:28.529] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 46511 "192.168.0.300" bash
[10:05:28.530] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[10:05:28.747] > ]0;C:\WINDOWS\System32\cmd.exe
[10:05:28.747] Got some output, clearing connection timeout
[10:05:28.826] > me@192.168.0.300's password: 
[10:05:28.826] Showing password prompt
[10:05:45.998] Password dialog canceled
[10:05:45.999] "install" terminal command canceled
[10:05:45.999] Exec server for ssh-remote+192.168.0.300 failed: Error: Connecting was canceled
[10:05:46.000] Error opening exec server for ssh-remote+192.168.0.300: Error: Connecting was canceled

EDIT: I forgot one note, it wasn't doing this about a month or so ago.

**Comment by roblourens** [comment]
Please share the full Remote-SSH log. Also does this still happen if you set `"remote.SSH.useExecServer": false`?

**Comment by KillahB33** [comment]
It is already set to false.

Alright here is the full stack.
```[08:07:29.519] Log Level: 2
[08:07:29.538] VS Code version: 1.85.0
[08:07:29.538] Remote-SSH version: remote-ssh@0.107.1
[08:07:29.539] win32 x64
[08:07:29.539] SSH Resolver called for "ssh-remote+192.168.0.204", attempt 1
[08:07:29.540] "remote.SSH.useLocalServer": false
[08:07:29.540] "remote.SSH.useExecServer": false
[08:07:29.540] "remote.SSH.showLoginTerminal": false
[08:07:29.540] "remote.SSH.remotePlatform": {"192.168.0.204":"linux"}
[08:07:29.540] "remote.SSH.path": undefined
[08:07:29.540] "remote.SSH.configFile": undefined
[08:07:29.541] "remote.SSH.useFlock": true
[08:07:29.541] "remote.SSH.lockfilesInTmp": false
[08:07:29.541] "remote.SSH.localServerDownload": auto
[08:07:29.541] "remote.SSH.remoteServerListenOnSocket": false
[08:07:29.541] "remote.SSH.showLoginTerminal": false
[08:07:29.541] "remote.SSH.defaultExtensions": []
[08:07:29.541] "remote.SSH.loglevel": 2
[08:07:29.542] "remote.SSH.enableDynamicForwarding": true
[08:07:29.542] "remote.SSH.enableRemoteCommand": false
[08:07:29.542] "remote.SSH.serverPickPortsFromRange": {}
[08:07:29.542] "remote.SSH.serverInstallPath": {}
[08:07:29.546] SSH Resolver called for host: 192.168.0.204
[08:07:29.546] Setting up SSH remote "192.168.0.204"
[08:07:29.550] Using commit id "af28b32d7e553898b2a91af498b1fb666fdebe0c" and quality "stable" for server
[08:07:29.552] Install and start server if needed
[08:07:29.556] Checking ssh with "C:\Program Files (x86)\Razer Chroma SDK\bin\ssh.exe -V"
[08:07:29.559] Got error from ssh: spawn C:\Program Files (x86)\Razer Chroma SDK\bin\ssh.exe ENOENT
[08:07:29.560] Checking ssh with "C:\Program Files\Razer Chroma SDK\bin\ssh.exe -V"
[08:07:29.561] Got error from ssh: spawn C:\Program Files\Razer Chroma SDK\bin\ssh.exe ENOENT
[08:07:29.561] Checking ssh with "C:\Program Files (x86)\Razer\ChromaBroadcast\bin\ssh.exe -V"
[08:07:29.562] Got error from ssh: spawn C:\Program Files (x86)\Razer\ChromaBroadcast\bin\ssh.exe ENOENT
[08:07:29.563] Checking ssh with "C:\Program Files\Razer\ChromaBroadcast\bin\ssh.exe -V"
[08:07:29.564] Got error from ssh: spawn C:\Program Files\Razer\ChromaBroadcast\bin\ssh.exe ENOENT
[08:07:29.565] Checking ssh with "C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe -V"
[08:07:29.566] Got error from ssh: spawn C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[08:07:29.567] Checking ssh with "C:\Program Files\Oculus\Support\oculus-runtime\ssh.exe -V"
[08:07:29.568] Got error from ssh: spawn C:\Program Files\Oculus\Support\oculus-runtime\ssh.exe ENOENT
[08:07:29.568] Checking ssh with "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe -V"
[08:07:29.569] Got error from ssh: spawn C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[08:07:29.569] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[08:07:29.571] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[08:07:29.571] Checking ssh with "C:\Windows\ssh.exe -V"
[08:07:29.572] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[08:07:29.572] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[08:07:29.574] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[08:07:29.574] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[08:07:29.576] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[08:07:29.576] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[08:07:29.610] > OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

[08:07:29.614] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 42596 "192.168.0.204" bash
[08:07:29.616] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[08:07:29.844] > ]0;C:\WINDOWS\System32\cmd.exe
[08:07:29.844] Got some output, clearing connection timeout
[08:07:29.967] > me@192.168.0.204's password: 
[08:07:29.968] Showing password prompt
[08:07:37.406] Got password response
[08:07:37.406] "install" wrote data to terminal: "*********"
[08:07:37.439] > 
[08:07:38.484] > fbb80ac5a56b: running
[08:07:38.546] > Acquiring lock on /home/me/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb6
> 66fdebe0c/vscode-remote-lock.me.af28b32d7e553898b2a91af498b1fb666fdebe0c     
[08:07:38.577] > Found existing installation at /home/me/.vscode-server/bin/af28b32d7e553898b2
> a91af498b1fb666fdebe0c...
> Checking /home/me/.vscode-server/.af28b32d7e553898b2a91af498b1fb666fdebe0c.lo
> g and /home/me/.vscode-server/.af28b32d7e553898b2a91af498b1fb666fdebe0c.pid f
> or a running server
> Looking for server with pid: 584288
[08:07:38.594] > Found running server...
[08:07:38.611] > 
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-lice
> nse) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacyst
> atement).
> *
> 
[08:07:38.625] > Checking server status on port 34937 with wget
[08:07:38.642] > fbb80ac5a56b: start
> SSH_AUTH_SOCK====    
> DISPLAY====
> webUiAccessToken==== 
> listeningOn==34937== 
> osReleaseId==ubuntu==
> arch==x86_64==       
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1000==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> connectionToken==a1a1111a-a1a1-11a1-11a1-11a1a111a111==
> fbb80ac5a56b: end
[08:07:38.643] Received install output: 
SSH_AUTH_SOCK====    
DISPLAY====
webUiAccessToken==== 
listeningOn==34937== 
osReleaseId==ubuntu==
arch==x86_64==       
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1000==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==a1a1111a-a1a1-11a1-11a1-11a1a111a111==

[08:07:38.643] Remote server is listening on port 34937
[08:07:38.643] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":34937},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"","display":"","tmpDir":"/run/user/1000","platform":"linux","connectionToken":"a1a1111a-a1a1-11a1-11a1-11a1a111a111"},"installUnpackCode":""}
[08:07:38.646] Starting forwarding server. local port 42600 -> socksPort 42596 -> remotePort 34937
[08:07:38.647] Forwarding server listening on port 42600
[08:07:38.648] Waiting for ssh tunnel to be ready
[08:07:38.650] Tunneled port 34937 to local port 42600
[08:07:38.650] Resolved "ssh-remote+192.168.0.204" to "port 42600"
[08:07:38.651] [Forwarding server port 42600] Got connection 0
[08:07:38.658] ------




[08:07:38.699] [Forwarding server port 42600] Got connection 1
[08:07:38.713] > 
[08:07:38.720] [Forwarding server port 42600] Got connection 2
[08:07:39.471] [Forwarding server port 42600] Got connection 3
[08:07:40.609] Opening exec server for ssh-remote+192.168.0.204
[08:07:40.643] Initizing new exec server for ssh-remote+192.168.0.204
[08:07:40.661] Using commit id "af28b32d7e553898b2a91af498b1fb666fdebe0c" and quality "stable" for server
[08:07:40.664] Install and start server if needed
[08:07:40.674] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 42612 "192.168.0.204" bash
[08:07:40.675] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[08:07:40.906] > ]0;C:\WINDOWS\System32\cmd.exe
[08:07:40.907] Got some output, clearing connection timeout
[08:07:40.967] > me@192.168.0.204's password: 
[08:07:40.968] Showing password prompt
[08:07:43.823] Password dialog canceled
[08:07:43.824] "install" terminal command canceled
[08:07:43.824] Exec server for ssh-remote+192.168.0.204 failed: Error: Connecting was canceled
[08:07:43.825] Error opening exec server for ssh-remote+192.168.0.204: Error: Connecting was canceled```

**Comment by roblourens** [comment]
Sorry, I meant `true` :)

Can you try that and check the server log `home/me/.vscode-server/.af28b32d7e553898b2a91af498b1fb666fdebe0c.log` for suspicious output?

**Comment by KillahB33** [comment]
That seems to have gotten rid of the second prompt but yes looks like we have some errors.

```*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Server bound to 127.0.0.1:34937 (IPv4)
Extension host agent listening on 34937

[12:58:05] 




[12:58:05] Extension host agent started.
[12:58:05] [127.0.0.1][b6f32be7][ManagementConnection] New connection established.
[12:58:05] [127.0.0.1][30202f61][ExtensionHostConnection] New connection established.
[12:58:05] [127.0.0.1][30202f61][ExtensionHostConnection] <584362> Launched Extension Host Process.
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host
    at A.U (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:43:32377)
    at A.updateTitle (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:43:27509)
    at T.<computed> (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:43:22735)
    at Object.call (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:34:5041)
    at g.s (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:32:5153)
    at g.q (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:32:4662)
    at a.value (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:32:4064)
    at i.y (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at i.fire (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process.ce (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:25:10117)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[12:58:08] Error [CodeExpectedError]: Could not find pty on pty host
    at A.U (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:43:32377)
    at A.updateTitle (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:43:27509)
    at T.<computed> (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:43:22735)
    at Object.call (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:34:5041)
    at g.s (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:32:5153)
    at g.q (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:32:4662)
    at a.value (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:32:4064)
    at i.y (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at i.fire (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process.ce (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:25:10117)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
rejected promise not handled within 1 second: CodeExpectedError: Could not find pty on pty host
stack trace: CodeExpectedError: Could not find pty on pty host
    at A.U (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:43:32377)
    at A.updateTitle (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:43:27509)
    at T.<computed> (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:43:22735)
    at Object.call (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:34:5041)
    at g.s (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:32:5153)
    at g.q (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:32:4662)
    at a.value (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:32:4064)
    at i.y (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at i.fire (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process.ce (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:25:10117)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[12:58:10] Error [CodeExpectedError]: Could not find pty on pty host
    at A.U (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:43:32377)
    at A.updateTitle (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:43:27509)
    at T.<computed> (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:43:22735)
    at Object.call (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:34:5041)
    at g.s (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:32:5153)
    at g.q (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:32:4662)
    at a.value (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:32:4064)
    at i.y (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:27:1906)
    at i.fire (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:27:2123)
    at process.ce (/home/bryan/.vscode-server/bin/af28b32d7e553898b2a91af498b1fb666fdebe0c/out/vs/platform/terminal/node/ptyHostMain.js:25:10117)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
New EH opened, aborting shutdown
[13:03:05] New EH opened, aborting shutdown
[13:05:56] [127.0.0.1][b6f32be7][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[13:05:56] [127.0.0.1][30202f61][ExtensionHostConnection] <584362> Extension Host Process exited with code: 0, signal: null.
Last EH closed, waiting before shutting down
[13:05:56] Last EH closed, waiting before shutting down
Got delay-shutdown request while in shutdown timeout, delaying
[13:07:39] Got delay-shutdown request while in shutdown timeout, delaying
Cancelling previous shutdown timeout
[13:07:39] Cancelling previous shutdown timeout
[13:07:39] [127.0.0.1][64cfe2a2][ManagementConnection] New connection established.
[13:07:39] [127.0.0.1][af19619a][ExtensionHostConnection] New connection established.
[13:07:39] [127.0.0.1][af19619a][ExtensionHostConnection] <584609> Launched Extension Host Process.
New EH opened, aborting shutdown
[13:12:39] New EH opened, aborting shutdown
[13:40:51] [127.0.0.1][64cfe2a2][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[13:40:51] [127.0.0.1][af19619a][ExtensionHostConnection] <584609> Extension Host Process exited with code: 0, signal: null.
Last EH closed, waiting before shutting down
[13:40:51] Last EH closed, waiting before shutting down
Last EH closed, shutting down
[13:45:51] Last EH closed, shutting down```

**Comment by roblourens** [comment]
Did it work or were there issues in the run where you got that error? Did the terminal work? If so it's ignorable, if not I will look into it

**Comment by KillahB33** [comment]
Yeah it's working fine. What's the difference between the two?

**Comment by roblourens** [comment]
There's a little description in https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting, it will be the default in the future, and does some things better.

Re: "Could not find pty on pty host" there is some discussion going on in https://github.com/microsoft/vscode/issues/201029

**Comment by EricFuma** [comment]
> Did it work or were there issues in the run where you got that error? Did the terminal work? If so it's ignorable, if not I will look into it

Works for me too.
