### ISSUE TITLE
Devcontainer fails in open in windows but not on mac

### ISSUE THREAD

**Issue by ridhwaans** [microsoft/vscode-remote-release#9308]
crossposted to https://github.com/devcontainers/cli/issues/756

- VSCode Version: latest
- Local OS Version: windows 11 latest
- WSL version: WSL2 latest
- WSL2 Linux version: Ubuntu 22.04
- Extensions used - ms-vscode-remote.remote-containers (latest), ms-vscode-remote.remote-wsl (latest)
- environment - reopen in container from local window and within WSL2 window

- Logs:

```
See 'docker run --help'.
[6288 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=\\wsl.localhost\Ubuntu\home\ridhwaans\Source\devcontainer-features
[6368 ms] Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,source=/home/ridhwaans/Source/devcontainer-features,target=/workspaces/devcontainer-features --mount type=volume,src=dind-var-lib-docker-${devcontainerId},dst=/var/lib/docker --mount type=volume,src=vscode,dst=/vscode -l devcontainer.local_folder=\\wsl.localhost\Ubuntu\home\ridhwaans\Source\devcontainer-features --privileged --entrypoint /bin/sh vsc-devcontainer-features-371a2d39594520cab899c23907e2c2c1-features -c echo Container started
[6368 ms] trap "exit 0" 15
[6368 ms] /usr/local/share/docker-init.sh
[6369 ms] exec "$@"
[6369 ms] while sleep 1 & wait $!; do :; done -
[6369 ms]     at MS (/home/ridhwaans/.vscode-remote-containers/dist/dev-containers-cli-0.245.2/dist/spec-node/devContainersSpecCLI.js:255:2186)
[6369 ms]     at Zw (/home/ridhwaans/.vscode-remote-containers/dist/dev-containers-cli-0.245.2/dist/spec-node/devContainersSpecCLI.js:255:2124)
[6369 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[6369 ms]     at async KS (/home/ridhwaans/.vscode-remote-containers/dist/dev-containers-cli-0.245.2/dist/spec-node/devContainersSpecCLI.js:261:2006)
[6369 ms]     at async co (/home/ridhwaans/.vscode-remote-containers/dist/dev-containers-cli-0.245.2/dist/spec-node/devContainersSpecCLI.js:261:3110)
[6369 ms]     at async LP (/home/ridhwaans/.vscode-remote-containers/dist/dev-containers-cli-0.245.2/dist/spec-node/devContainersSpecCLI.js:360:9352)
[6369 ms]     at async DP (/home/ridhwaans/.vscode-remote-containers/dist/dev-containers-cli-0.245.2/dist/spec-node/devContainersSpecCLI.js:360:9108)
[6372 ms] Exit code 1
[6375 ms] Command failed: /home/ridhwaans/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/node /home/ridhwaans/.vscode-remote-containers/dist/dev-containers-cli-0.245.2/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /home/ridhwaans/Source/devcontainer-features --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\Ubuntu\home\ridhwaans\Source\devcontainer-features --log-level debug --log-format json --config /home/ridhwaans/Source/devcontainer-features/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true --terminal-columns 265 --terminal-rows 22
[6375 ms] Exit code 1
```
Steps to Reproduce:

1. Ubuntu is installed in WSL2 Windows 11
2. VSCode extensions [Remote containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) and [WSL ](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl)extensions are installed. Docker Desktop is already running on windows 11 (host machine)
3. Repository containing `devcontainer.json` is cloned into WSL drive
4. In VSCode, open repository in a local window or "WSL" window
5. Command `Remote-Containers: Reopen in container`

This error doesn't happen with the VSCode remote container extension on MacOS

![Image](https://github.com/microsoft/vscode-remote-release/assets/1103336/54349370-7858-4bf6-953e-c0bbceae6cde)

![Image](https://github.com/microsoft/vscode-remote-release/assets/1103336/12869cdd-2335-4899-9e26-66ea04eabc06)

Copy of `devcontainer.json` from error :
```
{
    "image": "mcr.microsoft.com/devcontainers/javascript-node",
    "features": {
        "ghcr.io/devcontainers/features/docker-in-docker:2": {}
    },
    "postCreateCommand": "npm install -g @devcontainers/cli",
    "hostRequirements": {
        "cpus": 4
    },
    "customizations": {
        "vscode": {
            "extensions": [
                "mads-hartmann.bash-ide-vscode"
            ]
        }
    }
  }
```

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by ridhwaans** [comment]
uninstalled vscode 1.67. Now installed vscode v1.87.2 and the issue is resolved. Closed
