### ISSUE TITLE
Cannot build DevContainer locally on Windows 10 Home edition version 22H2

### ISSUE THREAD

**Issue by HenrikBach1** [microsoft/vscode-remote-release#9314]
Hi

I'm trying to build the CPP dev container locally from "https://github.com/devcontainers/images". However I get these errors, which prevents me to get a locally build devcontainer image for development:

``` shell
[2023-12-15T18:14:09.430Z] Dev Containers 0.328.0 in VS Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2).
[2023-12-15T18:14:09.430Z] Start: Resolving Remote
[2023-12-15T18:14:09.494Z] Setting up container for folder or workspace: c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp
[2023-12-15T18:14:09.496Z] Start: Run: wsl -l -v
[2023-12-15T18:14:09.646Z] Stop (150 ms): Run: wsl -l -v
[2023-12-15T18:14:09.646Z] Start: Run: wsl -d docker-desktop -e /bin/sh -c echo ~
[2023-12-15T18:14:09.840Z] Stop (194 ms): Run: wsl -d docker-desktop -e /bin/sh -c echo ~
[2023-12-15T18:14:09.842Z] Start: Run: wsl -d docker-desktop -e /bin/sh -c cd '/root' && /bin/sh
[2023-12-15T18:14:09.847Z] Start: Run in host: id -un
[2023-12-15T18:14:09.962Z] root
[2023-12-15T18:14:09.962Z] 
[2023-12-15T18:14:09.962Z] Stop (115 ms): Run in host: id -un
[2023-12-15T18:14:09.963Z] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true)
[2023-12-15T18:14:09.964Z] Stop (1 ms): Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true)
[2023-12-15T18:14:09.965Z] Start: Run in host: echo ~
[2023-12-15T18:14:09.966Z] /root
[2023-12-15T18:14:09.966Z] 
[2023-12-15T18:14:09.966Z] Stop (1 ms): Run in host: echo ~
[2023-12-15T18:14:09.967Z] Start: Run in host: test -x '/root/.vscode-remote-containers/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node'
[2023-12-15T18:14:09.968Z] 
[2023-12-15T18:14:09.968Z] 
[2023-12-15T18:14:09.968Z] Stop (1 ms): Run in host: test -x '/root/.vscode-remote-containers/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node'
[2023-12-15T18:14:09.968Z] Start: Run in host: test -f '/root/.vscode-remote-containers/dist/vscode-remote-containers-server-0.328.0.js'
[2023-12-15T18:14:09.969Z] 
[2023-12-15T18:14:09.969Z] 
[2023-12-15T18:14:09.969Z] Stop (1 ms): Run in host: test -f '/root/.vscode-remote-containers/dist/vscode-remote-containers-server-0.328.0.js'
[2023-12-15T18:14:09.973Z] Host server: /bin/sh: /root/.vscode-remote-containers/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/node: not found
[2023-12-15T18:14:09.974Z] userEnvProbe: loginInteractiveShell (default)
[2023-12-15T18:14:09.974Z] userEnvProbe: not found in cache
[2023-12-15T18:14:09.975Z] userEnvProbe shell: /bin/ash
[2023-12-15T18:14:10.033Z] Error reading shell environment.
[2023-12-15T18:14:10.033Z] Error: stream ended with:0 but wanted:9
	at l (c:\Users\henri\.vscode\extensions\ms-vscode-remote.remote-containers-0.328.0\dist\extension\extension.js:27:22149)
	at c:\Users\henri\.vscode\extensions\ms-vscode-remote.remote-containers-0.328.0\dist\extension\extension.js:27:22330
	at s (c:\Users\henri\.vscode\extensions\ms-vscode-remote.remote-containers-0.328.0\dist\extension\extension.js:30:5371)
	at Socket.<anonymous> (c:\Users\henri\.vscode\extensions\ms-vscode-remote.remote-containers-0.328.0\dist\extension\extension.js:30:5541)
	at Socket.emit (node:events:525:35)
	at endReadableNT (node:internal/streams/readable:1359:12)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[2023-12-15T18:14:10.034Z] Could not connect to WSL.
[2023-12-15T18:14:10.034Z] stream is closed
[2023-12-15T18:14:10.035Z] Stop (193 ms): Run: wsl -d docker-desktop -e /bin/sh -c cd '/root' && /bin/sh
[2023-12-15T18:14:10.035Z] Host server terminated (code: 127, signal: null).
[2023-12-15T18:14:10.038Z] Start: Check Docker is running
[2023-12-15T18:14:10.038Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2023-12-15T18:14:10.179Z] Stop (141 ms): Run: docker version --format {{.Server.APIVersion}}
[2023-12-15T18:14:10.180Z] Server API version: 1.44
[2023-12-15T18:14:10.180Z] Stop (142 ms): Check Docker is running
[2023-12-15T18:14:10.181Z] Start: Run: docker volume ls -q
[2023-12-15T18:14:10.332Z] Stop (151 ms): Run: docker volume ls -q
[2023-12-15T18:14:10.333Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp --filter label=vsch.quality=stable
[2023-12-15T18:14:10.488Z] Stop (155 ms): Run: docker ps -q -a --filter label=vsch.local.folder=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp --filter label=vsch.quality=stable
[2023-12-15T18:14:10.488Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp --filter label=devcontainer.config_file=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp\.devcontainer\devcontainer.json
[2023-12-15T18:14:10.647Z] Stop (159 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp --filter label=devcontainer.config_file=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp\.devcontainer\devcontainer.json
[2023-12-15T18:14:10.647Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp
[2023-12-15T18:14:10.796Z] Stop (149 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp
[2023-12-15T18:14:10.797Z] Start: Run: C:\Program Files\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\henri\.vscode\extensions\ms-vscode-remote.remote-containers-0.328.0\dist\spec-node\devContainersSpecCLI.js read-configuration --workspace-folder c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp --id-label devcontainer.local_folder=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp --id-label devcontainer.config_file=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp\.devcontainer\devcontainer.json --mount-workspace-git-root
[2023-12-15T18:14:11.108Z] @devcontainers/cli 0.54.2. Node.js v18.15.0. win32 10.0.19045 x64.
[2023-12-15T18:14:11.107Z] Start: Run: git rev-parse --show-cdup
[2023-12-15T18:14:11.120Z] findLocalWindowsExecutable: Exectuable 'git' not found on PATH 'C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\Vagrant\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\henri\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Oracle\VirtualBox;'.
[2023-12-15T18:14:11.121Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp --filter label=devcontainer.config_file=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp\.devcontainer\devcontainer.json
[2023-12-15T18:14:11.305Z] Stop (184 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp --filter label=devcontainer.config_file=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp\.devcontainer\devcontainer.json
[2023-12-15T18:14:11.320Z] Stop (523 ms): Run: C:\Program Files\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\henri\.vscode\extensions\ms-vscode-remote.remote-containers-0.328.0\dist\spec-node\devContainersSpecCLI.js read-configuration --workspace-folder c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp --id-label devcontainer.local_folder=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp --id-label devcontainer.config_file=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp\.devcontainer\devcontainer.json --mount-workspace-git-root
[2023-12-15T18:14:11.321Z] Start: Run: C:\Program Files\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\henri\.vscode\extensions\ms-vscode-remote.remote-containers-0.328.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\henri\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-564882c4-7627-4996-99f3-780e55f932371702664048438 --workspace-folder c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp --id-label devcontainer.config_file=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2023-12-15T18:14:11.658Z] @devcontainers/cli 0.54.2. Node.js v18.15.0. win32 10.0.19045 x64.
[2023-12-15T18:14:11.658Z] Start: Run: docker buildx version
[2023-12-15T18:14:12.083Z] Stop (425 ms): Run: docker buildx version
[2023-12-15T18:14:12.084Z] github.com/docker/buildx v0.12.0-desktop.2 c5a13b51c1ae9358eb691e9a21c955590e26d0a0
[2023-12-15T18:14:12.084Z] 
[2023-12-15T18:14:12.084Z] Start: Resolving Remote
[2023-12-15T18:14:12.088Z] Start: Run: git rev-parse --show-cdup
[2023-12-15T18:14:12.099Z] findLocalWindowsExecutable: Exectuable 'git' not found on PATH 'C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\Vagrant\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\henri\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Oracle\VirtualBox;'.
[2023-12-15T18:14:12.103Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp --filter label=devcontainer.config_file=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp\.devcontainer\devcontainer.json
[2023-12-15T18:14:12.255Z] Stop (152 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp --filter label=devcontainer.config_file=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp\.devcontainer\devcontainer.json
[2023-12-15T18:14:12.259Z] Start: Run: docker inspect --type image mcr.microsoft.com/devcontainers/base:debian-12
[2023-12-15T18:14:12.424Z] Stop (165 ms): Run: docker inspect --type image mcr.microsoft.com/devcontainers/base:debian-12
[2023-12-15T18:14:12.427Z] Resolving Feature dependencies for 'ghcr.io/devcontainers/features/git:1'...
[2023-12-15T18:14:12.428Z] * Processing feature: ghcr.io/devcontainers/features/git:1
[2023-12-15T18:14:12.616Z] Start: Run: docker-credential-desktop get
[2023-12-15T18:14:12.702Z] Stop (86 ms): Run: docker-credential-desktop get
[2023-12-15T18:14:13.098Z] * Processing feature: ghcr.io/devcontainers/features/common-utils
[2023-12-15T18:14:13.367Z] Soft-dependency 'ghcr.io/devcontainers/features/common-utils' is not required.  Removing from installation order...
[2023-12-15T18:14:13.369Z] * Fetching feature: git_0_oci
[2023-12-15T18:14:13.611Z] * Fetched feature: git_0_oci version 1.1.6
[2023-12-15T18:14:13.618Z] Start: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\henri\AppData\Local\Temp\devcontainercli\container-features\0.54.2-1702664052425\Dockerfile-with-features -t vsc-cpp-fbdbf35867253a3a7aa8976ec90635864985d60598828db68887e7e9766b9f5b --target dev_containers_target_stage --build-context dev_containers_feature_content_source=C:\Users\henri\AppData\Local\Temp\devcontainercli\container-features\0.54.2-1702664052425 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp\.devcontainer
[2023-12-15T18:14:13.784Z] 
[2023-12-15T18:14:14.117Z] 2023/12/15 19:14:14 http2: server: error reading preface from client //./pipe/do
cker_engine: file has already been closed
[2023-12-15T18:14:14.210Z] [+] Building 0.0s (0/1)                                          docker:default
[2023-12-15T18:14:14.396Z] 
[+] Building 0.2s (1/2)                                          docker:default
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 3.73kB                                     0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               0.1s
[2023-12-15T18:14:14.535Z] 
[+] Building 0.3s (1/2)                                          docker:default
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 3.73kB                                     0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               0.3s
[2023-12-15T18:14:14.568Z] 
[2023-12-15T18:14:14.691Z] 
[+] Building 0.5s (1/2)                                          docker:default
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 3.73kB                                     0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               0.5s
[2023-12-15T18:14:14.721Z] 
[2023-12-15T18:14:14.849Z] 
[+] Building 0.6s (1/2)                                          docker:default
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 3.73kB                                     0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               0.6s
[2023-12-15T18:14:15.005Z] 
[+] Building 0.8s (1/2)                                          docker:default
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 3.73kB                                     0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               0.8s
[2023-12-15T18:14:15.132Z] 
[+] Building 0.9s (1/2)                                          docker:default
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 3.73kB                                     0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               0.9s
[2023-12-15T18:14:15.163Z] 
[2023-12-15T18:14:15.226Z] 
[+] Building 1.0s (2/2)                                          docker:default
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 3.73kB                                     0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               1.0s
[2023-12-15T18:14:15.352Z] 
[+] Building 1.1s (3/4)                                          docker:default
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 3.73kB                                     0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               1.0s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531b  0.0s
 => => resolve docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a8586  0.0s
[2023-12-15T18:14:15.505Z] 
[+] Building 1.3s (6/6)                                          docker:default
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 3.73kB                                     0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               1.0s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531b  0.0s
 => => resolve docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a8586  0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [context dev_containers_feature_content_source] load .dockerignore     0.0s
 => => transferring dev_containers_feature_content_source: 2B              0.0s
 => [internal] load metadata for mcr.microsoft.com/devcontainers/base:deb  0.1s
[2023-12-15T18:14:15.737Z] 
[+] Building 1.5s (8/18)                                         docker:default
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 3.73kB                                     0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               1.0s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531b  0.0s
 => => resolve docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a8586  0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [context dev_containers_feature_content_source] load .dockerignore     0.0s
 => => transferring dev_containers_feature_content_source: 2B              0.0s
 => [internal] load metadata for mcr.microsoft.com/devcontainers/base:deb  0.1s
 => [context dev_containers_feature_content_source] load from client       0.0s
 => => transferring dev_containers_feature_content_source: 17.61kB         0.0s
 => [dev_container_auto_added_stage_label 1/4] FROM mcr.microsoft.com/dev  0.2s
 => => resolve mcr.microsoft.com/devcontainers/base:debian-12@sha256:058f  0.2s
 => [internal] load build context                                          0.0s
[2023-12-15T18:14:15.924Z] 
[+] Building 1.7s (11/18)                                        docker:default
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 3.73kB                                     0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               1.0s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531b  0.0s
 => => resolve docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a8586  0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [context dev_containers_feature_content_source] load .dockerignore     0.0s
 => => transferring dev_containers_feature_content_source: 2B              0.0s
 => [internal] load metadata for mcr.microsoft.com/devcontainers/base:deb  0.1s
 => [context dev_containers_feature_content_source] load from client       0.0s
 => => transferring dev_containers_feature_content_source: 17.61kB         0.0s
 => [dev_container_auto_added_stage_label 1/4] FROM mcr.microsoft.com/dev  0.2s
 => => resolve mcr.microsoft.com/devcontainers/base:debian-12@sha256:058f  0.2s
 => [internal] load build context                                          0.0s
[2023-12-15T18:14:15.955Z] 
 => [dev_container_auto_added_stage_label 1/4] FROM mcr.microsoft.com/dev  0.2s
 => => resolve mcr.microsoft.com/devcontainers/base:debian-12@sha256:058f  0.2s
 => [internal] load build context                                          0.0s
 => => transferring context: 83B                                           0.0s
 => CACHED [dev_container_auto_added_stage_label 2/4] RUN apt-get update   0.0s
 => CACHED [dev_container_auto_added_stage_label 3/4] COPY base-scripts/i  0.0s
 => [dev_container_auto_added_stage_label 4/4] RUN chmod +x /tmp/install-  0.2s
[2023-12-15T18:14:16.049Z] 
[+] Building 1.8s (11/18)                                        docker:default
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 3.73kB                                     0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               1.0s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531b  0.0s
 => => resolve docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a8586  0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [context dev_containers_feature_content_source] load .dockerignore     0.0s
 => => transferring dev_containers_feature_content_source: 2B              0.0s
 => [internal] load metadata for mcr.microsoft.com/devcontainers/base:deb  0.1s
 => [context dev_containers_feature_content_source] load from client       0.0s
 => => transferring dev_containers_feature_content_source: 17.61kB         0.0s
 => [dev_container_auto_added_stage_label 1/4] FROM mcr.microsoft.com/dev  0.2s
 => => resolve mcr.microsoft.com/devcontainers/base:debian-12@sha256:058f  0.2s
 => [internal] load build context                                          0.0s
 => => transferring context: 83B                                           0.0s
 => CACHED [dev_container_auto_added_stage_label 2/4] RUN apt-get update   0.0s
 => CACHED [dev_container_auto_added_stage_label 3/4] COPY base-scripts/i  0.0s
 => [dev_container_auto_added_stage_label 4/4] RUN chmod +x /tmp/install-  0.3s
 => => # /usr/bin/env: 'bash\r': No such file or directory
 => => # /usr/bin/env: use -[v]S to pass options in shebang lines
[2023-12-15T18:14:16.128Z] 
[+] Building 1.9s (12/18)                                        docker:default
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 3.73kB                                     0.0s
 => resolve image config for docker.io/docker/dockerfile:1.4               1.0s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531b  0.0s
 => => resolve docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a8586  0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [context dev_containers_feature_content_source] load .dockerignore     0.0s
 => => transferring dev_containers_feature_content_source: 2B              0.0s
 => [internal] load metadata for mcr.microsoft.com/devcontainers/base:deb  0.1s
 => [context dev_containers_feature_content_source] load from client       0.0s
 => => transferring dev_containers_feature_content_source: 17.61kB         0.0s
 => [dev_container_auto_added_stage_label 1/4] FROM mcr.microsoft.com/dev  0.2s
 => => resolve mcr.microsoft.com/devcontainers/base:debian-12@sha256:058f  0.2s
 => [internal] load build context                                          0.0s
 => => transferring context: 83B                                           0.0s
 => CACHED [dev_container_auto_added_stage_label 2/4] RUN apt-get update   0.0s
 => CACHED [dev_container_auto_added_stage_label 3/4] COPY base-scripts/i  0.0s
 => ERROR [dev_container_auto_added_stage_label 4/4] RUN chmod +x /tmp/in  0.3s
------
 > [dev_container_auto_added_stage_label 4/4] RUN chmod +x /tmp/install-vcpkg.sh
     && ./tmp/install-vcpkg.sh vscode     && rm -f /tmp/install-vcpkg.sh:
0.251 /usr/bin/env: 'bash\r': No such file or directory
0.251 /usr/bin/env: use -[v]S to pass options in shebang lines
------
Dockerfile-with-features:22
--------------------
  21 |     COPY base-scripts/install-vcpkg.sh /tmp/
  22 | >>> RUN chmod +x /tmp/install-vcpkg.sh \
  23 | >>>     && ./tmp/install-vcpkg.sh ${USERNAME} \
  24 | >>>     && rm -f /tmp/install-vcpkg.sh
  25 |
--------------------
ERROR: failed to solve: process "/bin/sh -c chmod +x /tmp/install-vcpkg.sh     &
& ./tmp/install-vcpkg.sh ${USERNAME}     && rm -f /tmp/install-vcpkg.sh" did not
 complete successfully: exit code: 127

View build details: docker-desktop://dashboard/build/default/default/k9sojatpld7
40e9gdelxongnb
[2023-12-15T18:14:16.238Z] Stop (2620 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\henri\AppData\Local\Temp\devcontainercli\container-features\0.54.2-1702664052425\Dockerfile-with-features -t vsc-cpp-fbdbf35867253a3a7aa8976ec90635864985d60598828db68887e7e9766b9f5b --target dev_containers_target_stage --build-context dev_containers_feature_content_source=C:\Users\henri\AppData\Local\Temp\devcontainercli\container-features\0.54.2-1702664052425 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp\.devcontainer
[2023-12-15T18:14:16.240Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\henri\AppData\Local\Temp\devcontainercli\container-features\0.54.2-1702664052425\Dockerfile-with-features -t vsc-cpp-fbdbf35867253a3a7aa8976ec90635864985d60598828db68887e7e9766b9f5b --target dev_containers_target_stage --build-context dev_containers_feature_content_source=C:\Users\henri\AppData\Local\Temp\devcontainercli\container-features\0.54.2-1702664052425 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp\.devcontainer
[2023-12-15T18:14:16.241Z]     at Y$ (c:\Users\henri\.vscode\extensions\ms-vscode-remote.remote-containers-0.328.0\dist\spec-node\devContainersSpecCLI.js:463:1860)
[2023-12-15T18:14:16.241Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-12-15T18:14:16.241Z]     at async Fw (c:\Users\henri\.vscode\extensions\ms-vscode-remote.remote-containers-0.328.0\dist\spec-node\devContainersSpecCLI.js:462:1831)
[2023-12-15T18:14:16.241Z]     at async $J (c:\Users\henri\.vscode\extensions\ms-vscode-remote.remote-containers-0.328.0\dist\spec-node\devContainersSpecCLI.js:462:608)
[2023-12-15T18:14:16.242Z]     at async tAA (c:\Users\henri\.vscode\extensions\ms-vscode-remote.remote-containers-0.328.0\dist\spec-node\devContainersSpecCLI.js:479:3660)
[2023-12-15T18:14:16.242Z]     at async CC (c:\Users\henri\.vscode\extensions\ms-vscode-remote.remote-containers-0.328.0\dist\spec-node\devContainersSpecCLI.js:479:4775)
[2023-12-15T18:14:16.242Z]     at async NeA (c:\Users\henri\.vscode\extensions\ms-vscode-remote.remote-containers-0.328.0\dist\spec-node\devContainersSpecCLI.js:612:11107)
[2023-12-15T18:14:16.242Z]     at async MeA (c:\Users\henri\.vscode\extensions\ms-vscode-remote.remote-containers-0.328.0\dist\spec-node\devContainersSpecCLI.js:612:10848)
[2023-12-15T18:14:16.254Z] Stop (4933 ms): Run: C:\Program Files\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\henri\.vscode\extensions\ms-vscode-remote.remote-containers-0.328.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\henri\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-564882c4-7627-4996-99f3-780e55f932371702664048438 --workspace-folder c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp --id-label devcontainer.config_file=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2023-12-15T18:14:16.254Z] Exit code 1
[2023-12-15T18:14:16.257Z] Command failed: C:\Program Files\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\henri\.vscode\extensions\ms-vscode-remote.remote-containers-0.328.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\henri\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-564882c4-7627-4996-99f3-780e55f932371702664048438 --workspace-folder c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp --id-label devcontainer.config_file=c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp\.devcontainer\devcontainer.json --log-level debug --log-format json --config c:\Users\henri\OneDrive\Projects\DevContainers\github\henrikbach1\ms-devcontainers\src\cpp\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2023-12-15T18:14:16.258Z] Exit code 1
```

What is above error messages trying to tell?

- VSCode Version: 
Version: 1.85.1 (system setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

- Local OS Version:
Edition	Windows 10 Home
Version	22H2
Installed on	‎14/‎12/‎2023
OS build	19045.3803
Experience	Windows Feature Experience Pack 1000.19053.1000.0

- Remote OS Version: N/A

Used latest VSCode Extension, due to the released have same behavior:
Dev Containers
v0.328.0
Pre-Release

**Comment by HenrikBach1** [comment]
Hi, 

Sorry for the late reply. 

However, in the meantime, everything seems to that it has healed itself. No, error messages and a running devcontainer.

Thank you.
Henrik
