### ISSUE TITLE
SSH Hangs Inside VSCode But Not In iTerm2/Terminal.app

### ISSUE THREAD

**Issue by SynAckJack** [microsoft/vscode-remote-release#9322]
Type: <b>Bug</b>

Kind of a weird one - when I try to SSH to a Windows host from my Terminal, it works without any issue. When I try to use the Remote SSH extension or SSH from the VS Code Terminal, it hangs. 

_Using Extension_
1. Open the command pallete and enter SSH command.
2. Observe that a new VS Code window opens.
3. Select `details` in the Toast and observe that the last log was `[20:44:20.800] stderr> debug1: Connecting to <host> [<host>] port 22.`
4. Connection times out.

_Using VS Code Terminal_
1. Open VS Code Terminal
2. ssh user@ip -v
3. Observe that the SSH connection hangs at `debug1: Connecting to <host> [<host>] port 22.`, then times out.

Extension version: 0.107.1
VS Code version: Code 1.84.2 (Universal) (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:33.687Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 6, 5|
|Memory (System)|32.00GB (1.13GB free)|
|Process Argv|--crash-reporter-id e115f421-07d6-497f-86e7-946c5dc0b093|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
3biah626:30602489
f6dab269:30613381
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260
cp7184c:30925681

```

</details>

**Comment by SynAckJack** [comment]
Apologies, I forgot the Remote SSH log (d'oh): 

```
[20:52:48.696] Log Level: 1
[20:52:48.703] SSH Resolver called for "ssh-remote+192.168.0.23", attempt 1
[20:52:48.703] "remote.SSH.useLocalServer": true
[20:52:48.703] "remote.SSH.useExecServer": false
[20:52:48.704] "remote.SSH.path": undefined
[20:52:48.704] "remote.SSH.configFile": undefined
[20:52:48.704] "remote.SSH.useFlock": true
[20:52:48.704] "remote.SSH.lockfilesInTmp": false
[20:52:48.704] "remote.SSH.localServerDownload": auto
[20:52:48.704] "remote.SSH.remoteServerListenOnSocket": false
[20:52:48.704] "remote.SSH.showLoginTerminal": true
[20:52:48.704] "remote.SSH.defaultExtensions": []
[20:52:48.704] "remote.SSH.loglevel": 1
[20:52:48.705] "remote.SSH.enableDynamicForwarding": true
[20:52:48.705] "remote.SSH.enableRemoteCommand": false
[20:52:48.705] "remote.SSH.serverPickPortsFromRange": {}
[20:52:48.708] "remote.SSH.serverInstallPath": {}
[20:52:48.710] VS Code version: 1.84.2
[20:52:48.710] Remote-SSH version: remote-ssh@0.107.1
[20:52:48.710] darwin arm64
[20:52:48.711] SSH Resolver called for host: 192.168.0.23
[20:52:48.711] Setting up SSH remote "192.168.0.23"
[20:52:48.713] Acquiring local install lock: /var/folders/pk/v96vmb217f583jpcsy6z0x9w0000gp/T/vscode-remote-ssh-92c1f59f-install.lock
[20:52:48.714] Looking for existing server data file at /Users/oscar/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-92c1f59f-1a5daa3a0231a0fbba4f14db7ec463cf99d7768e-0.107.1-tr/data.json
[20:52:48.714] Using commit id "1a5daa3a0231a0fbba4f14db7ec463cf99d7768e" and quality "stable" for server
[20:52:48.717] Install and start server if needed
[20:52:48.719] PATH: /Users/oscar/.rbenv/shims:/opt/homebrew/bin:/usr/local/bin:/usr/local/sbin:/Users/oscar/.cargo/bin:/Users/oscar/dotfiles:/Users/oscar/scripts:/Users/oscar/.nimble/bin:/Users/oscar/.local/bin:/Users/oscar/.local/share/bob/nvim-bin/:/Users/oscar/.docker/bin/:/usr/local/bin/clion/bin/:/Users/oscar/.cargo/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/Applications/Little Snitch.app/Contents/Components:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools
[20:52:48.719] Checking ssh with "ssh -V"
[20:52:48.728] > OpenSSH_9.5p1, OpenSSL 3.1.3 19 Sep 2023

[20:52:48.731] askpass server listening on /var/folders/pk/v96vmb217f583jpcsy6z0x9w0000gp/T/vscode-ssh-askpass-33a05a37fe3bd5ee5b5ed03e3c30134e3abe7a60.sock
[20:52:48.731] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/pk/v96vmb217f583jpcsy6z0x9w0000gp/T/vscode-ssh-askpass-df7e5041eea3265ffc98c0dbd352adfbd6a82860.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","57838","-o","ConnectTimeout=30","192.168.0.23","powershell"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/oscar/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-92c1f59f-1a5daa3a0231a0fbba4f14db7ec463cf99d7768e-0.107.1-tr/data.json"}
[20:52:48.731] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.JwUO0ZTbah/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/oscar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/oscar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/pk/v96vmb217f583jpcsy6z0x9w0000gp/T/vscode-ssh-askpass-33a05a37fe3bd5ee5b5ed03e3c30134e3abe7a60.sock"}
[20:52:48.732] Spawned 79425
[20:52:48.823] > local-server-1> Running ssh connection command: "-v -T -D 57838 -o ConnectTimeout=30 192.168.0.23 powershell"
[20:52:48.824] > local-server-1> Spawned ssh, pid=79427
[20:52:48.831] stderr> OpenSSH_9.5p1, OpenSSL 3.1.3 19 Sep 2023
[20:52:48.831] stderr> debug1: Reading configuration data /Users/oscar/.ssh/config
[20:52:48.831] stderr> debug1: /Users/oscar/.ssh/config line 7: Applying options for 192.168.0.23
[20:52:48.831] stderr> debug1: Reading configuration data /opt/homebrew/etc/ssh/ssh_config
[20:52:48.831] stderr> debug1: Connecting to 192.168.0.23 [192.168.0.23] port 22.
[20:53:18.838] stderr> debug1: connect to address 192.168.0.23 port 22: Operation timed out
[20:53:19.838] stderr> ssh: connect to host 192.168.0.23 port 22: Operation timed out
[20:53:19.840] > local-server-1> ssh child died, shutting down
[20:53:19.846] Local server exit: 0
[20:53:19.846] Received install output: local-server-1> Running ssh connection command: "-v -T -D 57838 -o ConnectTimeout=30 192.168.0.23 powershell"
local-server-1> Spawned ssh, pid=79427
OpenSSH_9.5p1, OpenSSL 3.1.3 19 Sep 2023
ssh: connect to host 192.168.0.23 port 22: Operation timed out
local-server-1> ssh child died, shutting down

[20:53:19.847] Stopped parsing output early. Remaining text: local-server-1> Running ssh connection command: "-v -T -D 57838 -o ConnectTimeout=30 192.168.0.23 powershell"local-server-1> Spawned ssh, pid=79427OpenSSH_9.5p1, OpenSSL 3.1.3 19 Sep 2023ssh: connect to host 192.168.0.23 port 22: Operation timed outlocal-server-1> ssh child died, shutting down
[20:53:19.850] Resolver error: Error: The operation timed out
	at g.Offline (/Users/oscar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:642754)
	at /Users/oscar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:638911
	at t.handleInstallOutput (/Users/oscar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:639138)
	at e (/Users/oscar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:700300)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /Users/oscar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:722169
	at async t.withShowDetailsEvent (/Users/oscar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:725828)
	at async /Users/oscar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:697005
	at async C (/Users/oscar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:695056)
	at async t.resolveWithLocalServer (/Users/oscar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:696545)
	at async I (/Users/oscar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:719392)
	at async t.resolve (/Users/oscar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:723199)
	at async /Users/oscar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:907003
[20:53:19.853] TELEMETRY: {"eventName":"resolver","properties":{"osReleaseId":"","arch":"","askedPw":"0","askedPassphrase":"0","asked2fa":"0","askedHostKey":"0","remoteInConfigFile":"1","gotUnrecognizedPrompt":"0","dynamicForwarding":"1","localServer":"1","didLocalDownload":"0","installUnpackCode":"0","outcome":"failure","reason":"OfflineError","exitCodeLabel":""},"measures":{"resolveAttempts":1,"isExecServer":0,"timing.totalResolveTime":31145,"timing.preSshTime":28}}
[20:53:19.856] ------




[20:53:20.052] Opening exec server for ssh-remote+192.168.0.23
[20:53:20.058] Initizing new exec server for ssh-remote+192.168.0.23
[20:53:20.068] Acquiring local install lock: /var/folders/pk/v96vmb217f583jpcsy6z0x9w0000gp/T/vscode-remote-ssh-92c1f59f-install.lock
[20:53:20.096] Looking for existing server data file at /Users/oscar/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-92c1f59f-1a5daa3a0231a0fbba4f14db7ec463cf99d7768e-0.107.1-es/data.json
[20:53:20.098] Using commit id "1a5daa3a0231a0fbba4f14db7ec463cf99d7768e" and quality "stable" for server
[20:53:20.100] Install and start server if needed
[20:53:20.103] askpass server listening on /var/folders/pk/v96vmb217f583jpcsy6z0x9w0000gp/T/vscode-ssh-askpass-26b8b401477e1273df97dfb3ebdc4c87778dd969.sock
[20:53:20.103] Spawning local server with {"serverId":2,"ipcHandlePath":"/var/folders/pk/v96vmb217f583jpcsy6z0x9w0000gp/T/vscode-ssh-askpass-c39e02ff713f6edbce99c2da29a265589c049956.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","57855","-o","ConnectTimeout=30","192.168.0.23","powershell"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/oscar/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-92c1f59f-1a5daa3a0231a0fbba4f14db7ec463cf99d7768e-0.107.1-es/data.json"}
[20:53:20.103] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.JwUO0ZTbah/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/oscar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/oscar/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/pk/v96vmb217f583jpcsy6z0x9w0000gp/T/vscode-ssh-askpass-26b8b401477e1273df97dfb3ebdc4c87778dd969.sock"}
[20:53:20.104] Spawned 79440
[20:53:20.222] > local-server-2> Running ssh connection command: "-v -T -D 57855 -o ConnectTimeout=30 192.168.0.23 powershell"
> local-server-2> Spawned ssh, pid=79442
[20:53:20.234] stderr> OpenSSH_9.5p1, OpenSSL 3.1.3 19 Sep 2023
[20:53:20.234] stderr> debug1: Reading configuration data /Users/oscar/.ssh/config
[20:53:20.234] stderr> debug1: /Users/oscar/.ssh/config line 7: Applying options for 192.168.0.23
[20:53:20.234] stderr> debug1: Reading configuration data /opt/homebrew/etc/ssh/ssh_config
[20:53:20.234] stderr> debug1: Connecting to 192.168.0.23 [192.168.0.23] port 22.
```

**Comment by roblourens** [comment]
Let's start with running ssh in the integrated terminal, because that's much simpler.

Can you run it with `-vvv` to see what it does when it hangs? Are you sure it's using your ssh config file (if applicable), connecting to the right host with the right auth, etc?

**Comment by voltagex** [comment]
I believe I am getting the same kind of issue, but on Windows 11 with `OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2` (and also before I upgraded the version)


```
[20:06:38.329] Checking ssh with "C:\Program Files\OpenSSH\ssh.exe -V"
[20:06:38.363] > OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2

[20:06:38.368] Running script with connection command: "C:\Program Files\OpenSSH\ssh.exe" -T -o ClearAllForwardings=true "192.168.xxx.xxx" bash
[20:06:38.369] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[20:06:55.374] Resolver error: Error: Connecting with SSH timed out

```

If I try to open the integrated terminal (local), I get some kind of hang:

![image](https://github.com/microsoft/vscode-remote-release/assets/83080728/d572c138-a10b-44c4-ad33-ccc776dd690e)


```
Version: 1.85.1 (system setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.26016
```

**Comment by roblourens** [comment]
@voltagex maybe you can see https://github.com/microsoft/vscode-remote-release/wiki/Remote-SSH-troubleshooting and open your own issue if needed.
