### ISSUE TITLE
[Remote-SSH Bug]: extension

### ISSUE THREAD

**Issue by Kkhokho** [microsoft/vscode-remote-release#9348]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

'.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC' is not recognized as an
> internal or external command,
> operable program or batch file.
> ]0;C:\Windows\System32\cmd.exe
[08:41:14.979] Got some output, clearing connection timeout
[08:41:16.258] "install" terminal command done
[08:41:16.259] Install terminal quit with output: ]0;C:\Windows\System32\cmd.exe
[08:41:16.259] Received install output: ]0;C:\Windows\System32\cmd.exe
[08:41:16.260] Failed to parse remote port from server output
[08:41:16.264] Resolver error: Error: 
	at g.Create (c:\Users\DELL\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:642703)
	at t.handleInstallOutput (c:\Users\DELL\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:640069)
	at t.tryInstall (c:\Users\DELL\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:761983)
	at async c:\Users\DELL\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:722522
	at async t.withShowDetailsEvent (c:\Users\DELL\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:725828)
	at async I (c:\Users\DELL\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:719493)
	at async t.resolve (c:\Users\DELL\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:723199)
	at async c:\Users\DELL\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:907003

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

**Comment by roblourens** [comment]
Please include the full log and more details

**Comment by notashleel** [comment]
same issue ^ any fix?

**Comment by notashleel** [comment]
https://github.com/microsoft/vscode-remote-release/assets/85107376/c95c22db-fbbf-4acc-9cb5-2ffbbf769801

**Comment by roblourens** [comment]
Not the same issue, please open your own issue
