### ISSUE TITLE
There's a bug related to Node and ICU

### ISSUE THREAD

**Issue by wwahammy** [microsoft/vscode-remote-release#935]
I'm trying to use Remote-Containers. There's a bug related to using ICU.

I'd try to debug it but honestly, you're making proprietary software so you need to pay me to give you more feedback.

Log:

```
Setting up container for folder: /home/eric/houdini
Run: docker-compose -f /home/eric/houdini/docker/debug/docker-compose.yml -f /home/eric/houdini/.devcontainer/docker-compose.yml config --services
db
memcached
web
Run: docker-compose --project-name debug -f /home/eric/houdini/docker/debug/docker-compose.yml -f /home/eric/houdini/.devcontainer/docker-compose.yml up -d
debug_memcached_1 is up-to-date
debug_db_1 is up-to-date
Starting debug_web_1 ... done
Run: docker exec efd97e4c995d9b8176a1cb8cf24d7041447d6dfb699e092bec382cc2af4d303e /bin/sh -c (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
Run: docker cp efd97e4c995d9b8176a1cb8cf24d7041447d6dfb699e092bec382cc2af4d303e:/etc/passwd -
Run: docker exec efd97e4c995d9b8176a1cb8cf24d7041447d6dfb699e092bec382cc2af4d303e test -d /home/eric/.vscode-server
Run: docker exec efd97e4c995d9b8176a1cb8cf24d7041447d6dfb699e092bec382cc2af4d303e test -d /home/eric/.vscode-remote
Run: docker exec efd97e4c995d9b8176a1cb8cf24d7041447d6dfb699e092bec382cc2af4d303e /bin/sh -c set -o noclobber ; mkdir -p '/home/eric/.vscode-server/data/Machine' && { > '/home/eric/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
Run: docker exec efd97e4c995d9b8176a1cb8cf24d7041447d6dfb699e092bec382cc2af4d303e /bin/sh -c set -o noclobber ; mkdir -p '/home/eric/.vscode-server/data/Machine' && { > '/home/eric/.vscode-server/data/Machine/.copyGitConfigMarker' ; } 2> /dev/null
Run: docker exec efd97e4c995d9b8176a1cb8cf24d7041447d6dfb699e092bec382cc2af4d303e test -e /home/eric/.gitconfig
Run: docker cp /home/eric/.gitconfig efd97e4c995d9b8176a1cb8cf24d7041447d6dfb699e092bec382cc2af4d303e:/home/eric/.gitconfig --follow-link
Run: docker exec -w /home/eric -u root efd97e4c995d9b8176a1cb8cf24d7041447d6dfb699e092bec382cc2af4d303e chown eric:1000 /home/eric/.gitconfig
Run: docker exec efd97e4c995d9b8176a1cb8cf24d7041447d6dfb699e092bec382cc2af4d303e test -d /home/eric/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338
Installing VS Code Server for commit 0f3794b38477eea13fb47fbe15a42798e6129338
Run: docker exec efd97e4c995d9b8176a1cb8cf24d7041447d6dfb699e092bec382cc2af4d303e mkdir -p /home/eric/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338_1562620803557
Run: docker cp /tmp/vsch/0f3794b38477eea13fb47fbe15a42798e6129338/vscode-server-linux-x64.tar.gz efd97e4c995d9b8176a1cb8cf24d7041447d6dfb699e092bec382cc2af4d303e:/home/eric/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338_1562620803557
Run: docker exec -w /home/eric/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338_1562620803557 efd97e4c995d9b8176a1cb8cf24d7041447d6dfb699e092bec382cc2af4d303e tar --no-same-owner -xf vscode-server-linux-x64.tar.gz --strip-components 1
Run: docker exec -w /home/eric/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338_1562620803557 efd97e4c995d9b8176a1cb8cf24d7041447d6dfb699e092bec382cc2af4d303e rm vscode-server-linux-x64.tar.gz
Run: docker exec efd97e4c995d9b8176a1cb8cf24d7041447d6dfb699e092bec382cc2af4d303e mv -n /home/eric/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338_1562620803557 /home/eric/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338
Run: docker exec efd97e4c995d9b8176a1cb8cf24d7041447d6dfb699e092bec382cc2af4d303e test -d /home/eric/.vscode-server/extensions
Run: docker exec efd97e4c995d9b8176a1cb8cf24d7041447d6dfb699e092bec382cc2af4d303e /bin/sh -c set -o noclobber ; mkdir -p '/home/eric/.vscode-server/data/Machine' && { > '/home/eric/.vscode-server/data/Machine/.postCreateCommandMarker' ; } 2> /dev/null
Run: docker exec efd97e4c995d9b8176a1cb8cf24d7041447d6dfb699e092bec382cc2af4d303e test -f /home/eric/.vscode-server/.postCreateCommandMarker
Run: docker exec -w / -u 0 efd97e4c995d9b8176a1cb8cf24d7041447d6dfb699e092bec382cc2af4d303e /bin/sh -c command -v git >/dev/null 2>&1 && git config --system credential.helper '!f() { command -v code >/dev/null 2>&1 && code --gitCredential $*; }; f' || true
Run: docker exec -w /home/eric/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338 -e SHELL=/bin/sh -e VSCODE_AGENT_FOLDER=/home/eric/.vscode-server efd97e4c995d9b8176a1cb8cf24d7041447d6dfb699e092bec382cc2af4d303e /home/eric/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/server.sh --disable-user-env-probe --disable-telemetry --port 0
/home/eric/.vscode-server/bin/0f3794b38477eea13fb47fbe15a42798e6129338/node: could not initialize ICU (check NODE_ICU_DATA or --icu-data-dir parameters)
```

**Comment by ericschultz** [comment]
Also, I'd need some form of indemnification from Microsoft because your license says that I "can't work around technical limitations". This might be technical limitation and it's just too legally risky for me to investigate.

**Comment by chrmarti** [comment]
Does https://stackoverflow.com/questions/50296555/node-could-not-initialize-icu-check-node-icu-data-or-icu-data-dir-parameters help?

**Comment by Regaddi** [comment]
I'm getting the same message.

```
/root/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390/node: could not initialize ICU (check NODE_ICU_DATA or --icu-data-dir parameters)
```

Affected version: Remote - Containers 0.81.1

I tried installing the full-icu package within the postCreateCommand:

```
// .devcontainer.json
{
  // ...
  "postCreateCommand": "yarn add full-icu && export NODE_ICU_DATA=node_modules/full-icu"
}
```

but without any luck: the error remains. I guess I can't access `vscode-server`'s node at that time.
It seems to be related to the node binary included in vscode-server, which is copied into the container.
I can start the same container outside of VSCode without any issues.

Let me know if you need additional information.

**Comment by Regaddi** [comment]
This has become a blocking issue for me.
As long as I can't attach ICU data to vscode-server's `node` I can't attach to any container.
This might be related to something detecting that a JavaScript in the container calls `new Intl.NumberFormat`.

**Comment by chrmarti** [comment]
https://stackoverflow.com/a/58453422/7857763 suggests to add:
```Dockerfile
WORKDIR /icu
RUN npm init -y && npm install full-icu
ENV NODE_ICU_DATA=/icu/node_modules/full-icu

WORKDIR ...
```

to your Dockerfile. Does that work?

**Comment by Regaddi** [comment]
Hi @chrmarti,

unfortunately this doesn't solve the issue.
While full-icu seems to be installed:

```
> full-icu@1.3.0 postinstall /icu/node_modules/full-icu
> node postinstall.js

npm install icu4c-data@64l (Node 12.11.1 and small-icu 64.2) -> icudt64l.dat
full-icu$ /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install icu4c-data@64l
npm notice created a lockfile as package-lock.json. You should commit this file.
+ icu4c-data@0.64.2
added 1 package from 1 contributor and audited 1 package in 2.711s
found 0 vulnerabilities

 ??icudt64l.dat (link)
Node will use this ICU datafile if the environment variable NODE_ICU_DATA is set to ?node_modules/full-icu?
or with node --icu-data-dir=node_modules/full-icu YOURAPP.js
 For package.json:
{"scripts":{"start":"node --icu-data-dir=node_modules/full-icu YOURAPP.js"}}

By the way, if you have full data, running this in node:
> new Intl.DateTimeFormat('es',{month:'long'}).format(new Date(9E8));
... will show ?enero?. If it shows ?January? you don't have full data.
News: Please see https://github.com/icu-project/full-icu-npm/issues/6
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN icu@1.0.0 No description
npm WARN icu@1.0.0 No repository field.

+ full-icu@1.3.0
added 1 package from 1 contributor and audited 1 package in 3.443s
found 0 vulnerabilities
```

it still aborts opening the folder on the container:

```
/root/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390/node: could not initialize ICU (check NODE_ICU_DATA or --icu-data-dir parameters)
```

**Comment by chrmarti** [comment]
We're using Node.js version 12.4.0 at the moment. Maybe that version needs to match exactly? (Your output mentions Node.js 12.11.1.)

Also make sure the environment variable is set when you use `docker exec -it <container id> /bin/bash`. And try to launch `/root/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390/node` and run the JavaScript code suggested in the output you posted.

**Comment by Regaddi** [comment]
Hi @chrmarti,

thanks for your help!

Unfortunately I still can't seem to make it work.

I've been investigating some things on the container:

```
# /root/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390/node --version
v10.11.0

# /root/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390/node

/root/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390/node: could not initialize ICU (check NODE_ICU_DATA or --icu-data-dir parameters)

# npm i -g full-icu
/usr/bin/node-full-icu-path -> /usr/lib/node_modules/full-icu/node-icu-data.js

> full-icu@1.3.0 postinstall /usr/lib/node_modules/full-icu
> node postinstall.js

node: could not initialize ICU (check NODE_ICU_DATA or --icu-data-dir parameters)

npm ERR! code ELIFECYCLE
npm ERR! errno 9
npm ERR! full-icu@1.3.0 postinstall: `node postinstall.js`
npm ERR! Exit status 9
npm ERR! 
npm ERR! Failed at the full-icu@1.3.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-28T20_38_52_873Z-debug.log

# node --version
node: could not initialize ICU (check NODE_ICU_DATA or --icu-data-dir parameters)
```

I can't detect the system's node version (`/usr/bin/node`).
But interestingly `/root/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390/node` returns `v10.11.0` and not `v12.4.0`.

I tried setting `NODE_ICU_DATA` to the directory where `full-icu` was definitely installed to (in my case `/usr/lib/node_modules/full-icu`) with

1. `export NODE_ICU_DATA=/usr/lib/node_modules/full-icu` and running node
2. `NODE_ICU_DATA=/usr/lib/node_modules/full-icu /root/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390/node`
3. `/root/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390/node --icu-data-dir=/usr/lib/node_modules/full-icu`

But all responded with `/root/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390/node: could not initialize ICU (check NODE_ICU_DATA or --icu-data-dir parameters)`

I tried the same with `/usr/bin/node` with the same result.

I'm a bit stuck here 😕

**Comment by chrmarti** [comment]
I think you need to install `full-icu` with the `node` on `PATH` that will then use it.

What I don't understand is if you actually want this or if your container by chance has `NODE_ICU_DATA` set (maybe pointing to the install you mention under `/usr/lib/...`) and all you need to do is unset it.

**Comment by Regaddi** [comment]
Hey @chrmarti,

> I think you need to install full-icu with the node on PATH that will then use it.

This is already done and the "default" `node` within the container works perfectly fine. `full-icu` is already bundled with it.

It's the node at `/root/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390/node` which causes issues.
The only command I can run with this is `node --version` which returns `v10.11.0`

According to https://github.com/unicode-org/full-icu-npm/issues/25 there might be an incompatibility between node10 and full-icu.

**Comment by Regaddi** [comment]
If I symlink the vscode-server's node (`v10.11.0`) to the default node (`v12.11.1`) I get a runtime error:

```
Run: docker exec -w /root/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390 -e SHELL=/bin/ash -e VSCODE_AGENT_FOLDER=/root/.vscode-server 19fcd67a456958c9eedf55c35f10212ec33abeea9009454e4cbaa68e6dfe58b2 /root/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390/server.sh --disable-user-env-probe --port 0
/root/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390/out/bootstrap.js:5
"use strict";function mkdir(e){const r=require("fs");return new Promise((o,n)=>r.mkdir(e,r=>r&&"EEXIST"!==r.code?n(r):o(e)))}Error.stackTraceLimit=100,process.on("SIGPIPE",()=>{console.error(new Error("Unexpected SIGPIPE"))}),exports.injectNodeModuleLookupPath=function(e){if(!e)throw new Error("Missing injectPath");const r=require("module"),o=require("path").join(__dirname,"../node_modules"),n=r._resolveLookupPaths;r._resolveLookupPaths=function(r,t,i){const s=n(r,t,i),c=i?s:s[1];for(let r=0,n=c.length;r<n;r++)if(c[r]===o){c.splice(r,0,e);break}return s}},exports.enableASARSupport=function(e){const r=require("module"),o=require("path");let n=e;n||(n=o.join(__dirname,"../node_modules"));const t=n+".asar",i=r._resolveLookupPaths;r._resolveLookupPaths=function(e,r,o){const s=i(e,r,o),c=o?s:s[1];for(let e=0,r=c.length;e<r;e++)if(c[e]===n){c.splice(e,0,t);break}return s}},exports.uriFromPath=function(e){let r,o=require("path").r

TypeError: Cannot read property 'length' of undefined
    at Function.r._resolveLookupPaths (/root/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390/out/bootstrap.js:5:502)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:763:20)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/.vscode-server/bin/6ab598523be7a800d7f3eb4d92d7ab9a66069390/out/vs/server/main.js:5:373)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by Regaddi** [comment]
@chrmarti 
Here is a minimal reproduction using a docker image with built-in ICU: https://github.com/Regaddi/node12-icu-vscode-remote

**Comment by chrmarti** [comment]
Thanks @Regaddi, that's great!

It turns out that only VS Code's Insiders build (to become the next stable sometime next week) is using Node.js 12.4.0 and that works with the full-icu package you have installed. You can download the Insiders build here: https://code.visualstudio.com/insiders/

I don't think we gain anything from running the VS Code Server with full-icu, so if this problem comes up again, you could also clear the `NODE_ICU_DATA` environment variable and only set it when you launch Node yourself.

Closing for now, we can revisit if this comes up more often.
