### ISSUE TITLE
IPv6 support issue

### ISSUE THREAD

**Issue by edibleparts** [microsoft/vscode-remote-release#9366]
adding ssh connection to a remote host that using IPv6 address does not work.
E.g. you can specify IPv4 connection.  
ssh ubuntu@10.0.2.44 
You will see 'connect to host 10.0.2.44', and it works.
But if you try to use IPv6 address in this scenario, it does NOT work.
E.g.
ssh ubuntu@fd9a:92ce:386e:bc05:1863:23ff:fe39:a42b
You will see 'connect to host fd9a'. (first word)
If you do try to connect, it is obvious that IPv6 address which uses ':' separator, is confused with [explicit] port number, which also uses same separator. There are messages in extension output along the lines  
stderr> ~/.ssh/config line xx: Bad port 'ipv6 adds : ... : ... :...'

Note that at the same time direct connect 
ssh ubuntu@fd9a:92ce:386e:bc05:1863:23ff:fe39:a42b
from bash in terminal works just fine.
Hence it appears a bug in parsing of ssh hostname. 
In certain scenarios where ssh address is VM, there is no hostname resolution other than IP address, and host network uses IPv6 only, so ability to work with IPv6 host address is importamt.

**Comment by edibleparts** [comment]
Further, using ipv6+port notation e.g. ssh ubuntu@[fd9c:92ce:386e:bc05:1863:23ff:fe39:a42b] does not help.
extension creates invalid entries in ~/.ssh/config thus attempt to connect remote host fails immediately on invalid address/port.  Correcting correct entry manually allows connection to proceed, but it never connects, eventually timing out.
Judging from console output, now it is the same issue, but on remote.
Now it seems I am stuck, since this time this is not in some file I can fix.

[21:05:54.949] Received install output: local-server-1> Running ssh connection command: "-v -T -D 65393 -o ConnectTimeout=15 ubuntu"
local-server-1> Spawned ssh, pid=46687
OpenSSH_9.4p1, LibreSSL 3.3.6
debug1: Server host key: ssh-ed25519 SHA256:fXNkve/CIj3V....gH1yDovAjqtM
Failed to get SSH credentials: Error in request: socket hang up
["/private/var/folders/8_/j2w5q30j1793hmk5_4sdq4cr0000gn/T/AppTranslocation/5ADF77A9-5....943B-04C630976512/d/Visual Studio Code-3.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","/Users//.vscode/extensions/ms-vscode-remote.remote-ssh-0.108.2023112915/out/askpass-main.js","ubuntu@fd9c:92ce:386e:bc05:1863:23ff:fe39:a42b's","password:"]
Connection closed by fd9c:92ce:386e:bc05:1863:23ff:fe39:a42b port 22
local-server-1> ssh child died, shutting down

[21:05:54.950] Failed to parse remote port from server output
	at g.Create (/Users//.vscode/extensions/ms-vscode-remote.remote-ssh-0.108.2023112915/out/extension.js:2:642703)
	at t.handleInstallOutput (/Users//.vscode/extensions/ms-vscode-remote.remote-ssh-0.108.2023112915/out/extension.js:2:640069)
	at e (/Users//.vscode/extensions/ms-vscode-remote.remote-ssh-0.108.2023112915/out/extension.js:2:700300)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /Users//.vscode/extensions/ms-vscode-remote.remote-ssh-0.108.2023112915/out/extension.js:2:722169
	at async t.withShowDetailsEvent (/Users//.vscode/extensions/ms-vscode-remote.remote-ssh-0.108.2023112915/out/extension.js:2:725828)
	at async /Users//.vscode/extensions/ms-vscode-remote.remote-ssh-0.108.2023112915/out/extension.js:2:697005
	at async C (/Users//.vscode/extensions/ms-vscode-remote.remote-ssh-0.108.2023112915/out/extension.js:2:695056)
	at async t.resolveWithLocalServer (/Users//.vscode/extensions/ms-vscode-remote.remote-ssh-0.108.2023112915/out/extension.js:2:696545)
	at async I (/Users//.vscode/extensions/ms-vscode-remote.remote-ssh-0.108.2023112915/out/extension.js:2:719392)
	at async t.resolve (/Users//.vscode/extensions/ms-vscode-remote.remote-ssh-0.108.2023112915/out/extension.js:2:723199)
	at async /Users//.vscode/extensions/ms-vscode-remote.remote-ssh-0.108.2023112915/out/extension.js:2:907012

**Comment by edibleparts** [comment]
oh wait, it worked. 
It is simply asked for sudo password from remote server (couple of times), and UI is such that these requests are inconspicuous, I did not noticed them. UI can be better, I suppose.

Bottomline, there is a bug parsing IPv6 address on localhost when creating ~/.ssh/config

Workaround is to create host entry (address and port) manually, then it works.  With this workaround, bug is not as critical.
I suppose another workaround is to create an entry in /etc/hosts for the ipv6 VM. 
Thanks.

**Comment by jellehierck** [comment]
This issue also occurs for me when connecting to my VM (using Multipass and VirtualBox). Makes it quite annoying to add a host with an IPv6 address, especially since the error messages are quite obscure.

We use this extension in a broad software engineering course, so especially for students new to SSH, Remote VMs and software development in general this issue is very confusing.

But the workaround suggested by @edibleparts (creating a manual entry in ~/.ssh/config) does work.

**Comment by hwcopeland** [comment]
Ran into this issue today. Just want to +1 for a qol bug fix.

**Comment by BSpendlove** [comment]
This is mega annoying, there is clearly some hardcoded string split from the first colon to identify as a port? Clearly a software engineer wrote it... 😸 

I've tried escaping the colons with various techniques like url escaping, backslashes, etc... but no success.

Ideally it shouldn't just split the string at the first instance of a `:` character. Also implement a check to confirm if the port is an integer within the range of 0-65535 (technically 0 can be avoided if we want to go there, just do 1 <= {{ port }} <= 65535).
