### ISSUE TITLE
[Remote-SSH Bug]: Unable to open devcontainer on remote Linux host

### ISSUE THREAD

**Issue by TomFreeman** [microsoft/vscode-remote-release#9388]
### Is there an existing issue for this bug?

- [x] I have searched the existing issues

### Required Troubleshooting Steps

- [x] I have followed these troubleshooting steps
- [x] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

Can't reopen a remote SSH repository in a devcontainer.

Reverting to versions of the 'Remote Containers' extension of 0.309 or earlier seem to resolve the issue.

### Steps To Reproduce

Remote Host:
- 5.15.0-1051-aws #56~20.04.1-Ubuntu SMP Tue Nov 28 15:43:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Client OS:
- 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64

1. Connect to private VPN to access SSH host
2. Connect via SSH in vscode to remote host ✅ 
3. Open source folder containing a .devcontainer config ✅ 
4. Re-open source folder in a container
In versions greater than 0.309 of the remote container extension this doesn't work anymore, and we get the following log output:

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[2024-01-15T11:12:10.411Z] Dev Containers 0.321.0 in VS Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2).
[2024-01-15T11:12:10.411Z] Start: Resolving Remote
[2024-01-15T11:12:10.429Z] Setting up container for folder or workspace: <SOURCE>
[2024-01-15T11:12:10.429Z] Host authority: <SSH_CONNECTION>
[2024-01-15T11:12:10.430Z] Start: Check Docker is running
[2024-01-15T11:12:10.430Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2024-01-15T11:12:10.433Z] Stop (3 ms): Run: docker version --format {{.Server.APIVersion}}
[2024-01-15T11:12:10.434Z] spawn docker ENOENT
[2024-01-15T11:12:10.434Z] Stop (4 ms): Check Docker is running
[2024-01-15T11:12:10.436Z] Docker returned an error code ENOENT, message: spawn docker ENOENT
[2024-01-15T11:12:10.441Z] Stop (11 ms): Run: docker version --format {{.Server.APIVersion}}
```

Versions 0.315 (.0 and .1) append an extra detail to the error logs:

```
[2024-01-15T11:00:52.014Z] Error opening dev container configurations: CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://<LARGE_BLOB>@ssh-remote<SSH_CONNECTION>'
    at n.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:645:13659)
    at async n.exists (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:645:15866)
    at async Promise.all (index 0)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1869:2800
```

</p>
</details>

### Anything else?

Similar to https://github.com/microsoft/vscode-remote-release/issues/9345 except the client OS is macOS using native SSH.

**Comment by uricatauni9** [comment]
Same here, it always happens when opening multiple VSCode Remote Windows restoring connection to previous devcontainer session.

**Comment by TomFreeman** [comment]
Have tried again with the pre-release "dev containers" extension (0.330 is the latest listed for me.)

I seem to get two error files logged whenever it tries this? A few seconds apart. (This is, if I use the command pallet `Dev Containers Developer > Show all Logs`)

The first looks like this:

```
[2024-01-23T15:08:47.258Z] Dev Containers 0.330.0 over Remote - SSH 0.107.1 in VS Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2).
[2024-01-23T15:08:47.258Z] Start: Resolving Remote
[2024-01-23T15:08:47.318Z] Setting up container for folder or workspace: <REMOTE_PATH>
[2024-01-23T15:08:47.318Z] Host authority: <SSH_CONNECTION>
[2024-01-23T15:08:47.319Z] Start: Check Docker is running
[2024-01-23T15:08:47.319Z] Start: Run: docker version
[2024-01-23T15:08:47.322Z] Stop (3 ms): Run: docker version
[2024-01-23T15:08:47.323Z] Stop (4 ms): Check Docker is running
[2024-01-23T15:08:47.324Z] Docker returned an error code ENOENT, message: spawn docker ENOENT
[2024-01-23T15:08:47.343Z] Stop (24 ms): Run: docker version
```

Then a few seconds later it logs this:

```
[2024-01-23T15:09:02.808Z] Dev Containers 0.330.0 over Remote - SSH 0.107.1 in VS Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2).
[2024-01-23T15:09:02.808Z] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/tomfreeman/.vscode/extensions/ms-vscode-remote.remote-containers-0.330.0/dist/spec-node/devContainersSpecCLI.js outdated --workspace-folder / --config /var/folders/53/v_m86h794zv_n_66jxpwjt5c0000gn/T/dev-container-tmp-980562e2-9481-42b7-b60b-b8f4883ff29c/.devcontainer.json --output-format json --log-level debug --log-format json
[2024-01-23T15:09:02.954Z] @devcontainers/cli 0.55.0. Node.js v18.15.0. darwin 23.2.0 arm64.
[2024-01-23T15:09:02.954Z] Start: Run: git rev-parse --show-cdup
[2024-01-23T15:09:02.974Z] Stop (20 ms): Run: git rev-parse --show-cdup
[2024-01-23T15:09:03.355Z] Start: Run: docker-credential-desktop get
[2024-01-23T15:09:03.361Z] Start: Run: docker-credential-desktop get
[2024-01-23T15:09:03.362Z] Start: Run: docker-credential-desktop get
[2024-01-23T15:09:03.439Z] Stop (78 ms): Run: docker-credential-desktop get
[2024-01-23T15:09:03.474Z] Stop (119 ms): Run: docker-credential-desktop get
[2024-01-23T15:09:03.485Z] Stop (123 ms): Run: docker-credential-desktop get
[2024-01-23T15:09:03.495Z] Start: Run: docker-credential-desktop get
[2024-01-23T15:09:03.538Z] Stop (43 ms): Run: docker-credential-desktop get
[2024-01-23T15:09:04.206Z] Stop (1398 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/tomfreeman/.vscode/extensions/ms-vscode-remote.remote-containers-0.330.0/dist/spec-node/devContainersSpecCLI.js outdated --workspace-folder / --config /var/folders/53/v_m86h794zv_n_66jxpwjt5c0000gn/T/dev-container-tmp-980562e2-9481-42b7-b60b-b8f4883ff29c/.devcontainer.json --output-format json --log-level debug --log-format json
```

The second seems to be running on my machine, and the former on the remote host.

Docker is available and on the PATH in each case, and I can just revert to 0.309 and connect to the container without making any other changes.

**Comment by chrmarti** [comment]
My best guess is that the PATH isn't yet fully set up at that point, could you try setting the user setting to the absolute path to the Docker executable:
![Image](https://github.com/microsoft/vscode-remote-release/assets/9205389/55e66003-3c12-4f53-8051-312c593724cf)

I will add more logging to make this easier to investigate in the future.

**Comment by TomFreeman** [comment]
Setting the docker executable doesn't appear to have any impact.

**Comment by chrmarti** [comment]
Might be the same as https://github.com/microsoft/vscode-remote-release/issues/9324.

**Comment by TomFreeman** [comment]
Hmmm... The latest insiders build actually works on my machine.

Which is nice, but frustrating for diagnosing the issue.

The exact same remote host still doesn't work on the older extension.
In fact, just changing to vscode insiders was enough to make this work for me, even without any change to the extension.

So, on the same remote server:
- ✅ Dev Containers 0.337.0 over Remote - SSH 0.107.1 in VS Code 1.86.0-insider
- ✅ Dev Containers 0.327.0 over Remote - SSH 0.107.1 in VS Code 1.86.0-insider
- ❌ Dev Containers 0.327.0 over Remote - SSH 0.107.1 in VS Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681).

Successful logs, in case they're useful:

```
[2024-01-26T09:25:18.854Z] Dev Containers 0.337.0 over Remote - SSH 0.107.1 in VS Code 1.86.0-insider (feff7c8a7e1c82320380f42d898a1e03051fefb7).
[2024-01-26T09:25:18.854Z] Start: Resolving Remote
[2024-01-26T09:25:18.957Z] Host OS: linux 5.15.0-1051-aws
[2024-01-26T09:25:18.958Z] Host CWD: <CODE_PATH>
[2024-01-26T09:25:18.958Z] Start: Run: /bin/sh 
[2024-01-26T09:25:19.161Z] Start: Run in host: echo ~
[2024-01-26T09:25:19.264Z] /workspace
[2024-01-26T09:25:19.265Z] 
[2024-01-26T09:25:19.265Z] Stop (104 ms): Run in host: echo ~
[2024-01-26T09:25:19.266Z] Start: Run in host: id -un
[2024-01-26T09:25:19.363Z] build
[2024-01-26T09:25:19.364Z] 
[2024-01-26T09:25:19.364Z] Stop (98 ms): Run in host: id -un
[2024-01-26T09:25:19.366Z] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'build' || grep -E '^build|^[^:]*:[^:]*:build:' /etc/passwd || true)
[2024-01-26T09:25:19.466Z] Stop (100 ms): Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'build' || grep -E '^build|^[^:]*:[^:]*:build:' /etc/passwd || true)
[2024-01-26T09:25:19.469Z] userEnvProbe: loginInteractiveShell (default)
[2024-01-26T09:25:19.469Z] userEnvProbe: not found in cache
[2024-01-26T09:25:19.470Z] userEnvProbe shell: /bin/bash
[2024-01-26T09:25:19.735Z] userEnvProbe PATHs:
Probe:     '/usr/share/rbenv/shims:/usr/share/rbenv/shims:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
Container: None
[2024-01-26T09:25:20.034Z] Setting up container for folder or workspace: <CODE_PATH>
[2024-01-26T09:25:20.035Z] Host authority: ssh-remote+<BLOB>
[2024-01-26T09:25:20.037Z] Start: Check Docker is running
[2024-01-26T09:25:20.038Z] Start: Run: docker version
[2024-01-26T09:25:20.257Z] Client: Docker Engine - Community
[2024-01-26T09:25:20.257Z]  Version:           25.0.1
 API version:       1.44
 Go version:        go1.21.6
/// ... SNIP ... ///
```

**Comment by chrmarti** [comment]
Not sure what makes the difference. Could you also post the Remote-SSH log from when it fails here? (`F1` > `Output: Show Output Channels...` > `Remote-SSH`)

This might be an issue in 1.85 that has been fixed in 1.86 Insiders. 1.86 is expected to release some time next week.

**Comment by TomFreeman** [comment]
This is an example output from the failed attempt:

```
[16:25:28.820] Log Level: 2
[16:25:28.825] VS Code version: 1.85.2
[16:25:28.825] Remote-SSH version: remote-ssh@0.107.1
[16:25:28.825] darwin arm64
[16:25:28.827] SSH Resolver called for "ssh-remote+build@<SSH_HOST>", attempt 1
[16:25:28.828] "remote.SSH.useLocalServer": false
[16:25:28.828] "remote.SSH.useExecServer": false
[16:25:28.828] "remote.SSH.showLoginTerminal": false
[16:25:28.828] "remote.SSH.remotePlatform": {"<SSH_HOST>":"linux",
...
// Other Hosts
...
"<SSH_HOST>":"linux"}
[16:25:28.828] "remote.SSH.path": undefined
[16:25:28.828] "remote.SSH.configFile": /Users/tomfreeman/.ssh/config
[16:25:28.828] "remote.SSH.useFlock": true
[16:25:28.829] "remote.SSH.lockfilesInTmp": false
[16:25:28.829] "remote.SSH.localServerDownload": auto
[16:25:28.829] "remote.SSH.remoteServerListenOnSocket": false
[16:25:28.829] "remote.SSH.showLoginTerminal": false
[16:25:28.829] "remote.SSH.defaultExtensions": []
[16:25:28.829] "remote.SSH.loglevel": 2
[16:25:28.829] "remote.SSH.enableDynamicForwarding": true
[16:25:28.829] "remote.SSH.enableRemoteCommand": false
[16:25:28.829] "remote.SSH.serverPickPortsFromRange": {}
[16:25:28.829] "remote.SSH.serverInstallPath": {}
[16:25:28.832] SSH Resolver called for host: build@<SSH_HOST>
[16:25:28.832] Setting up SSH remote "<SSH_HOST>"
[16:25:28.834] Using commit id "8b3775030ed1a69b13e4f4c628c612102e30a681" and quality "stable" for server
[16:25:28.836] Install and start server if needed
[16:25:28.838] PATH: /Users/tomfreeman/code/tools/google-cloud-sdk/bin:/Users/tomfreeman/.nodenv/shims:/Users/tomfreeman/.nvm/versions/node/v16.14.0/bin:/Users/tomfreeman/.rbenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/usr/local/share/dotnet:~/.dotnet/tools:/Users/tomfreeman/.krew/bin:/opt/homebrew/opt/dotnet/libexec:/Users/tomfreeman/.dotnet/tools:/Users/tomfreeman/.bin
[16:25:28.838] Checking ssh with "ssh -V"
[16:25:28.844] > OpenSSH_9.4p1, LibreSSL 3.3.6

[16:25:28.846] Using SSH config file "/Users/tomfreeman/.ssh/config"
[16:25:28.846] Running script with connection command: ssh -T -D 63038 -o ConnectTimeout=15 -F '/Users/tomfreeman/.ssh/config' 'build@<SSH_HOST>' bash
[16:25:30.436] > 05c8f5aa64d2: running
[16:25:30.436] Got some output, clearing connection timeout
[16:25:30.468] > Acquiring lock on /workspace/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/vscode-remote-lock.build.8b3775030ed1a69b13e4f4c628c612102e30a681
> Found existing installation at /workspace/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681...
> Checking /workspace/.vscode-server/.8b3775030ed1a69b13e4f4c628c612102e30a681.log and /workspace/.vscode-server/.8b3775030ed1a69b13e4f4c628c612102e30a681.pid for a running server
> Looking for server with pid: 4647
[16:25:30.476] > Found running server...
>  
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
[16:25:30.536] > * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
>  
> Checking server status on port 42789 with wget
> 05c8f5aa64d2: start
> SSH_AUTH_SOCK==/tmp/ssh-eLZD4cH3lH/agent.5744==
> DISPLAY====
> webUiAccessToken====
> listeningOn==42789==
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1001==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime====
> connectionToken==*****==
> 05c8f5aa64d2: end
[16:25:30.536] Received install output: 
SSH_AUTH_SOCK==/tmp/ssh-eLZD4cH3lH/agent.5744==
DISPLAY====
webUiAccessToken====
listeningOn==42789==
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1001==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime====
connectionToken==*****==

[16:25:30.536] Remote server is listening on port 42789
[16:25:30.536] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":42789},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"/tmp/ssh-eLZD4cH3lH/agent.5744","display":"","tmpDir":"/run/user/1001","platform":"linux","connectionToken":"*****"},"installUnpackCode":""}
[16:25:30.537] Starting forwarding server. local port 63041 -> socksPort 63038 -> remotePort 42789
[16:25:30.538] Forwarding server listening on port 63041
[16:25:30.538] Waiting for ssh tunnel to be ready
[16:25:30.539] Tunneled port 42789 to local port 63041
[16:25:30.539] Resolved "ssh-remote+build@<SSH_HOST>" to "port 63041"
[16:25:30.539] Updating $SSH_AUTH_SOCK: ln -f -s "/tmp/ssh-eLZD4cH3lH/agent.5744" "/run/user/1001/vscode-ssh-auth-sock-124817114"
[16:25:30.539] Using cwd: vscode-remote://ssh-remote%2Bbuild@<SSH_HOST>/
[16:25:30.539] Remote extension host environment: {"SSH_AUTH_SOCK":"/run/user/1001/vscode-ssh-auth-sock-124817114"}
[16:25:30.540] [Forwarding server port 63041] Got connection 0
[16:25:30.545] ------




[16:25:30.565] [Forwarding server port 63041] Got connection 1
[16:25:30.776] [Forwarding server port 63041] Got connection 2

// Re-Open in dev container here

[16:25:32.327] Opening exec server for ssh-remote+build@<SSH_HOST>
[16:25:32.343] Initizing new exec server for ssh-remote+build@<SSH_HOST>
[16:25:32.352] Using commit id "8b3775030ed1a69b13e4f4c628c612102e30a681" and quality "stable" for server
[16:25:32.354] Install and start server if needed
[16:25:32.358] Using SSH config file "/Users/tomfreeman/.ssh/config"
[16:25:32.358] Running script with connection command: ssh -T -D 63055 -o ConnectTimeout=15 -F '/Users/tomfreeman/.ssh/config' 'build@<SSH_HOST>' bash
[16:25:32.512] "Update SSH_AUTH_SOCK" terminal command done
[16:25:34.131] > ec3ac41c49a4: running
> Found existing installation at /workspace/.vscode-server...
> Running ssh connection command... /workspace/.vscode-server/code-8b3775030ed1a69b13e4f4c628c612102e30a681 command-shell --cli-data-dir /workspace/.vscode-server/cli --on-port --require-token f503a5cf5eec --parent-process-id 5977 &> "/workspace/.vscode-server/.cli.8b3775030ed1a69b13e4f4c628c612102e30a681.log" < /dev/null
> printenv:
>     SHELL=/bin/bash
>     SSH_AUTH_SOCK=/tmp/ssh-Ms1PpXDoPy/agent.5953
>     PWD=/workspace
>     LOGNAME=build
>     XDG_SESSION_TYPE=tty
>     HOME=/workspace
>     LANG=C.UTF-8
>     VSCODE_AGENT_FOLDER=/workspace/.vscode-server
>     SSH_CONNECTION=10.212.0.227 63057 10.212.5.95 22
>     XDG_SESSION_CLASS=user
>     USER=build
>     SHLVL=0
>     XDG_SESSION_ID=9
>     XDG_RUNTIME_DIR=/run/user/1001
>     SSH_CLIENT=10.212.0.227 63057 22
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus
>     _=/usr/bin/printenv
> Removing old logfile at /workspace/.vscode-server/.cli.8b3775030ed1a69b13e4f4c628c612102e30a681.log
> Spawned remote CLI: 5996
[16:25:34.131] Got some output, clearing connection timeout
[16:25:34.139] > Waiting for server log...
[16:25:34.175] > ec3ac41c49a4: start
> SSH_AUTH_SOCK==/tmp/ssh-Ms1PpXDoPy/agent.5953==
[16:25:34.233] > DISPLAY====
> listeningOn==127.0.0.1:32811==
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/1001==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> serverStartTime==38==
> execServerToken==f503a5cf5eec==
> ec3ac41c49a4: end
[16:25:34.233] Received install output: 
SSH_AUTH_SOCK==/tmp/ssh-Ms1PpXDoPy/agent.5953==
DISPLAY====
listeningOn==127.0.0.1:32811==
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/1001==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
serverStartTime==38==
execServerToken==f503a5cf5eec==

[16:25:34.233] Remote server is listening on port 32811
[16:25:34.233] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":32811},"osReleaseId":"ubuntu","arch":"x86_64","sshAuthSock":"/tmp/ssh-Ms1PpXDoPy/agent.5953","display":"","tmpDir":"/run/user/1001","platform":"linux","execServerToken":"f503a5cf5eec"},"serverStartTime":38,"installUnpackCode":""}
[16:25:34.234] Starting forwarding server. local port 63065 -> socksPort 63055 -> remotePort 32811
[16:25:34.235] Forwarding server listening on port 63065
[16:25:34.235] Waiting for ssh tunnel to be ready
[16:25:34.236] Tunneled port 32811 to local port 63065
[16:25:34.236] Resolved "ssh-remote+build@<SSH_HOST>" to "port 63065"
[16:25:34.236] Resolving exec server at port 63065
[16:25:34.236] [Forwarding server port 63065] Got connection 0
[16:25:34.237] [Forwarding server port 63065] Got connection 1
[16:25:34.549] Exec server for ssh-remote+build@<SSH_HOST> created and cached
```

I've tried a few settings as my insiders settings for the extension and non-insiders differed in a couple of places. But, doesn't seem to have made any impact. 🤷

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-remote-release/issues/9324. Thanks.
