### ISSUE TITLE
Remote SSH not working when connecting to Windows Server 2019 Azure Virtual Machine

### ISSUE THREAD

**Issue by gareth-walley** [microsoft/vscode-remote-release#9413]
# Description
Last year, I was using the SSH connection to our Windows Server 2019 Virtual Machine (hosted on Azure). That server has not had its configuration updated, yet now my remote-ssh connection from VSCode appears to be broken.

Currently, all I am trying to do is connect using ssh in vscode to the server, and I get an error.
In the log below, there is a command ("C:\Windows\System32\OpenSSH\ssh.exe" -T -D 56210 "). When I run that in a powershell terminal on the client, I am able to connect with no issue.

Any ideas?

## Extension version: 
0.107.1

## VS Code version: 
Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)

## Connection Type:
SSH via Open SSH 

## Client OS version: 
| | |
| ---- | ---- |
| Edition |	Windows 11 Pro |
| Version | 22H2 | 
| OS build | 22621.3007 |
| Experience | Windows Feature Experience Pack 1000.22681.1000.0 |

## Remote OS Version:
| | |
| ---- | ---- |
| Edition |	Windows Server 2019 Datacenter |
| Version | 1809 | 
| OS build | 17763.5329 |

## Remote version of Powershell:

| Name                        | Value |
| ----                        | ----- |
| PSVersion                   | 5.1.17763.5328 |
| PSEdition                   | Desktop |
| PSCompatibleVersions        | {1.0, 2.0, 3.0, 4.0...} |
| BuildVersion                | 10.0.17763.5328 |
| CLRVersion                  | 4.0.30319.42000 |
| WSManStackVersion           | 3.0 |
| PSRemotingProtocolVersion   | 2.3 |
| SerializationVersion        | 1.1.0.1 |

## Installed Extensions:
- ms-vscode-remote.remote-containers 
- ms-vscode-remote.remote-ssh
- ms-vscode-remote.remote-ssh-edit
- ms-vscode.remote-explorer

## Steps to reproduce
1. Open VS Code
2. Connect to host
3. Select Windows when asked for OS
4. Password prompt -> enter password
5. Error!

## Similar issues?
I've seen similar issues with the same error message ("Failed to parse remote port from server output") however none of them have the same preceding lines in the logs ("Install terminal quit with output: Copyright (C) Microsoft Corporation. All rights reserved")

```
[11:38:51.801] Log Level: 2
[11:38:51.808] SSH Resolver called for "ssh-remote+<HOST_IP_REDACTED>", attempt 1
[11:38:51.809] "remote.SSH.useLocalServer": false
[11:38:51.809] "remote.SSH.useExecServer": false
[11:38:51.809] "remote.SSH.showLoginTerminal": true
[11:38:51.809] "remote.SSH.remotePlatform": {}
[11:38:51.809] "remote.SSH.path": undefined
[11:38:51.809] "remote.SSH.configFile": undefined
[11:38:51.809] "remote.SSH.useFlock": true
[11:38:51.809] "remote.SSH.lockfilesInTmp": false
[11:38:51.809] "remote.SSH.localServerDownload": auto
[11:38:51.809] "remote.SSH.remoteServerListenOnSocket": false
[11:38:51.809] "remote.SSH.showLoginTerminal": true
[11:38:51.809] "remote.SSH.defaultExtensions": []
[11:38:51.809] "remote.SSH.loglevel": 2
[11:38:51.810] "remote.SSH.maxReconnectionAttempts": 8
[11:38:51.810] "remote.SSH.enableDynamicForwarding": true
[11:38:51.810] "remote.SSH.enableRemoteCommand": false
[11:38:51.810] "remote.SSH.serverPickPortsFromRange": {}
[11:38:51.810] "remote.SSH.serverInstallPath": {}
[11:38:51.814] VS Code version: 1.85.2
[11:38:51.814] Remote-SSH version: remote-ssh@0.107.1
[11:38:51.814] win32 x64
[11:38:51.815] SSH Resolver called for host: <HOST_IP_REDACTED>
[11:38:51.815] Setting up SSH remote "<HOST_IP_REDACTED>"
[11:38:51.817] Using commit id "8b3775030ed1a69b13e4f4c628c612102e30a681" and quality "stable" for server
[11:38:51.819] Install and start server if needed
[11:38:53.567] Checking ssh with "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe -V"
[11:38:53.569] Got error from ssh: spawn C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[11:38:53.569] Checking ssh with "C:\Program Files (x86)\VMware\VMware Workstation\bin\ssh.exe -V"
[11:38:53.570] Got error from ssh: spawn C:\Program Files (x86)\VMware\VMware Workstation\bin\ssh.exe ENOENT
[11:38:53.570] Checking ssh with "C:\Windows\System32\ssh.exe -V"
[11:38:53.571] Got error from ssh: spawn C:\Windows\System32\ssh.exe ENOENT
[11:38:53.571] Checking ssh with "C:\Windows\ssh.exe -V"
[11:38:53.571] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[11:38:53.571] Checking ssh with "C:\Windows\System32\wbem\ssh.exe -V"
[11:38:53.572] Got error from ssh: spawn C:\Windows\System32\wbem\ssh.exe ENOENT
[11:38:53.572] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[11:38:53.573] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[11:38:53.573] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[11:38:53.599] > OpenSSH_for_Windows_8.6p1, LibreSS
[11:38:53.599] > L 3.4.3

[11:38:53.601] Remote command length: 6226/8192 characters
[11:38:53.601] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 56210 "<HOST_IP_REDACTED>" powershell
[11:38:53.602] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[11:38:54.003] > Access is denied.
> ]0;C:\WINDOWS\System32\cmd.exe
[11:38:54.003] Got some output, clearing connection timeout
[11:38:54.018] > Access is denied.
> 
[11:38:54.144] > <SERVER_USER>@<HOST_IP_REDACTED>'s password: 
[11:38:58.511] > 
[11:38:58.728] > Windows PowerShell 
> Copyright (C) Microsoft Corporation. All rights reserved.
[11:38:58.837] > PS C:\Users\<SERVER_USER>> 
[11:39:00.199] "install" terminal command done
[11:39:00.200] Install terminal quit with output: Copyright (C) Microsoft Corporation. All rights reserved.PS C:\Users\<SERVER_USER>> 
[11:39:00.200] Received install output: Copyright (C) Microsoft Corporation. All rights reserved.PS C:\Users\<SERVER_USER>> 
[11:39:00.200] Failed to parse remote port from server output
[11:39:00.201] Resolver error: Error: 
	at g.Create (c:\Users\<CLIENT_USER>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:642703)
	at t.handleInstallOutput (c:\Users\<CLIENT_USER>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:640069)
	at t.tryInstall (c:\Users\<CLIENT_USER>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:761983)
	at async c:\Users\<CLIENT_USER>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:722522
	at async t.withShowDetailsEvent (c:\Users\<CLIENT_USER>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:725828)
	at async I (c:\Users\<CLIENT_USER>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:719493)
	at async t.resolve (c:\Users\<CLIENT_USER>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:723199)
	at async c:\Users\<CLIENT_USER>\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:907003
[11:39:00.204] ------

[11:39:00.418] Opening exec server for ssh-remote+<HOST_IP_REDACTED>
[11:39:00.420] Initizing new exec server for ssh-remote+<HOST_IP_REDACTED>
[11:39:00.435] Using commit id "8b3775030ed1a69b13e4f4c628c612102e30a681" and quality "stable" for server
[11:39:00.438] Install and start server if needed
[11:39:17.021] getPlatformForHost was canceled
[11:39:17.021] Exec server for ssh-remote+<HOST_IP_REDACTED> failed: Error: Connecting was canceled
[11:39:17.022] Error opening exec server for ssh-remote+<HOST_IP_REDACTED>: Error: Connecting was canceled
```

**Comment by Oakington** [comment]
Experiencing the same issue as OP. 

Additional information:
Cisco is quarantining a bash script file with the following event log entry:
Quarantine of malicious file (C:\Users\<user>\AppData\Local\Temp\vscode-linux-multi-line-command-<remote-hostname>-<hash>.sh) successful
Cisco identifies as : Heur.BZC.PZQ.Boxter.949

Uploading the file from quarantine to virus total yields no detections.
Possible false positive from anti-virus?

**Comment by joshspicer** [comment]
The ` > Access is denied.` is coming from your remote host over SSH.  First, please confirm you can manually SSH to the host using the exact same command that the extension used.  I'm seeing in the original post that you tried the command, but didn't copy it exactly the same. Please make sure it is the same and you aren't using an SSH key or something in one place but not the other.

The command is: `"C:\Windows\System32\OpenSSH\ssh.exe" -T -D 56210 "<HOST_IP_REDACTED>" powershell`

You'll need to get that working first (note that you should put configuration into the SSH configuration file).


@Oakington - yes, assuming that file was unmodified, it appears to be a false positive from your antivirus.
