### ISSUE TITLE
[Remote-SSH Bug]: 

### ISSUE THREAD

**Issue by surapuramakhil** [microsoft/vscode-remote-release#9431]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

[08:40:26.212] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 5375 "linprog.cs.fsu.edu" bash
[08:40:26.219] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[08:40:29.526] > ssh: Could not resolve hostname linprog: No such host is known.
> The process tried to write to a nonexistent pipe.
> ]0;C:\WINDOWS\System32\cmd.exe
[08:40:29.527] Got some output, clearing connection timeout
[08:40:30.818] "install" terminal command done
[08:40:30.819] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exe
[08:40:30.819] Received install output: ]0;C:\WINDOWS\System32\cmd.exe
[08:40:30.821] Failed to parse remote port from server output
[08:40:30.824] Resolver error: Error: 
	at g.Create (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:642703)
	at t.handleInstallOutput (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:640069)
	at t.tryInstall (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:761983)
	at async c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:722522
	at async t.withShowDetailsEvent (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:725828)
	at async I (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:719493)
	at async t.resolve (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:723199)
	at async c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:907003
[08:40:30.836] ------

[08:40:32.263] Opening exec server for ssh-remote+linprog.cs.fsu.edu
[08:40:32.289] Initizing new exec server for ssh-remote+linprog.cs.fsu.edu
[08:40:32.316] Using commit id "8b3775030ed1a69b13e4f4c628c612102e30a681" and quality "stable" for server
[08:40:32.320] Install and start server if needed
[08:41:02.058] getPlatformForHost was canceled
[08:41:02.058] Exec server for ssh-remote+linprog.cs.fsu.edu failed: Error: Connecting was canceled
[08:41:02.059] Error opening exec server for ssh-remote+linprog.cs.fsu.edu: Error: Connecting was canceled

### Expected Behavior

Remote connection should be sucessfull

### Remote-SSH Log

[08:40:23.945] Log Level: 2
[08:40:23.964] SSH Resolver called for "ssh-remote+linprog.cs.fsu.edu", attempt 1
[08:40:23.964] "remote.SSH.useLocalServer": false
[08:40:23.965] "remote.SSH.useExecServer": false
[08:40:23.965] "remote.SSH.showLoginTerminal": false
[08:40:23.965] "remote.SSH.remotePlatform": {}
[08:40:23.965] "remote.SSH.path": undefined
[08:40:23.966] "remote.SSH.configFile": undefined
[08:40:23.966] "remote.SSH.useFlock": true
[08:40:23.966] "remote.SSH.lockfilesInTmp": false
[08:40:23.966] "remote.SSH.localServerDownload": auto
[08:40:23.966] "remote.SSH.remoteServerListenOnSocket": false
[08:40:23.967] "remote.SSH.showLoginTerminal": false
[08:40:23.967] "remote.SSH.defaultExtensions": []
[08:40:23.967] "remote.SSH.loglevel": 2
[08:40:23.968] "remote.SSH.enableDynamicForwarding": true
[08:40:23.968] "remote.SSH.enableRemoteCommand": false
[08:40:23.968] "remote.SSH.serverPickPortsFromRange": {}
[08:40:23.968] "remote.SSH.serverInstallPath": {}
[08:40:23.981] VS Code version: 1.85.2
[08:40:23.981] Remote-SSH version: remote-ssh@0.107.1
[08:40:23.981] win32 x64
[08:40:23.983] SSH Resolver called for host: linprog.cs.fsu.edu
[08:40:23.983] Setting up SSH remote "linprog.cs.fsu.edu"
[08:40:23.989] Using commit id "8b3775030ed1a69b13e4f4c628c612102e30a681" and quality "stable" for server
[08:40:23.997] Install and start server if needed
[08:40:26.075] Checking ssh with "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe -V"
[08:40:26.084] Got error from ssh: spawn C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[08:40:26.085] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[08:40:26.087] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[08:40:26.088] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[08:40:26.091] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[08:40:26.091] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[08:40:26.095] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[08:40:26.095] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[08:40:26.097] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[08:40:26.098] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[08:40:26.200] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[08:40:26.212] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 5375 "linprog.cs.fsu.edu" bash
[08:40:26.219] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[08:40:29.526] > ssh: Could not resolve hostname linprog: No such host is known.
> The process tried to write to a nonexistent pipe.
> ]0;C:\WINDOWS\System32\cmd.exe
[08:40:29.527] Got some output, clearing connection timeout
[08:40:30.818] "install" terminal command done
[08:40:30.819] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exe
[08:40:30.819] Received install output: ]0;C:\WINDOWS\System32\cmd.exe
[08:40:30.821] Failed to parse remote port from server output
[08:40:30.824] Resolver error: Error: 
	at g.Create (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:642703)
	at t.handleInstallOutput (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:640069)
	at t.tryInstall (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:761983)
	at async c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:722522
	at async t.withShowDetailsEvent (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:725828)
	at async I (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:719493)
	at async t.resolve (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:723199)
	at async c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:907003
[08:40:30.836] ------

[08:40:32.263] Opening exec server for ssh-remote+linprog.cs.fsu.edu
[08:40:32.289] Initizing new exec server for ssh-remote+linprog.cs.fsu.edu
[08:40:32.316] Using commit id "8b3775030ed1a69b13e4f4c628c612102e30a681" and quality "stable" for server
[08:40:32.320] Install and start server if needed
[08:41:02.058] getPlatformForHost was canceled
[08:41:02.058] Exec server for ssh-remote+linprog.cs.fsu.edu failed: Error: Connecting was canceled
[08:41:02.059] Error opening exec server for ssh-remote+linprog.cs.fsu.edu: Error: Connecting was canceled

**Comment by roblourens** [comment]
This is just an error directly from ssh: `ssh: Could not resolve hostname linprog: No such host is known.`

**Comment by surapuramakhil** [comment]
I think i have pasted the wrong Stack trace. there was another error unable to parse port number from server response

**Comment by surapuramakhil** [comment]
[11:25:59.949] Log Level: 2
[11:25:59.972] SSH Resolver called for "ssh-remote+linprog.cs.fsu.edu", attempt 1
[11:25:59.973] "remote.SSH.useLocalServer": false
[11:25:59.973] "remote.SSH.useExecServer": false
[11:25:59.975] "remote.SSH.showLoginTerminal": false
[11:25:59.980] "remote.SSH.remotePlatform": {}
[11:25:59.980] "remote.SSH.path": undefined
[11:25:59.980] "remote.SSH.configFile": undefined
[11:25:59.980] "remote.SSH.useFlock": true
[11:25:59.981] "remote.SSH.lockfilesInTmp": false
[11:25:59.981] "remote.SSH.localServerDownload": auto
[11:25:59.981] "remote.SSH.remoteServerListenOnSocket": false
[11:25:59.981] "remote.SSH.showLoginTerminal": false
[11:25:59.981] "remote.SSH.defaultExtensions": []
[11:25:59.981] "remote.SSH.loglevel": 2
[11:25:59.982] "remote.SSH.enableDynamicForwarding": true
[11:25:59.982] "remote.SSH.enableRemoteCommand": false
[11:25:59.982] "remote.SSH.serverPickPortsFromRange": {}
[11:25:59.983] "remote.SSH.serverInstallPath": {}
[11:25:59.994] VS Code version: 1.85.2
[11:25:59.994] Remote-SSH version: remote-ssh@0.107.1
[11:25:59.994] win32 x64
[11:26:00.023] SSH Resolver called for host: linprog.cs.fsu.edu
[11:26:00.023] Setting up SSH remote "linprog.cs.fsu.edu"
[11:26:00.031] Using commit id "8b3775030ed1a69b13e4f4c628c612102e30a681" and quality "stable" for server
[11:26:00.037] Install and start server if needed
[11:26:03.501] Checking ssh with "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe -V"
[11:26:03.506] Got error from ssh: spawn C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[11:26:03.507] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[11:26:03.509] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[11:26:03.510] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[11:26:03.513] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[11:26:03.513] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[11:26:03.514] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[11:26:03.516] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[11:26:03.518] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[11:26:03.518] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[11:26:03.582] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[11:26:03.586] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 9004 "linprog.cs.fsu.edu" bash
[11:26:03.589] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[11:26:04.287] > Corrupted MAC on input.
> ssh_dispatch_run_fatal: Connection to 128.186.122.110 port 22: message authentication code incorrect
> The process tried to write to a nonexistent pipe.
> ]0;C:\WINDOWS\System32\cmd.exe
[11:26:04.288] Got some output, clearing connection timeout
[11:26:05.582] "install" terminal command done
[11:26:05.583] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exe
[11:26:05.583] Received install output: ]0;C:\WINDOWS\System32\cmd.exe
[11:26:05.585] Failed to parse remote port from server output
[11:26:05.588] Resolver error: Error: 
	at g.Create (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:642703)
	at t.handleInstallOutput (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:640069)
	at t.tryInstall (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:761983)
	at async c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:722522
	at async t.withShowDetailsEvent (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:725828)
	at async I (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:719493)
	at async t.resolve (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:723199)
	at async c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:907003
[11:26:05.600] ------




[11:26:07.720] Opening exec server for ssh-remote+linprog.cs.fsu.edu
[11:26:07.757] Initizing new exec server for ssh-remote+linprog.cs.fsu.edu
[11:26:07.785] Using commit id "8b3775030ed1a69b13e4f4c628c612102e30a681" and quality "stable" for server
[11:26:07.791] Install and start server if needed
[11:26:11.651] getPlatformForHost was canceled
[11:26:11.652] Exec server for ssh-remote+linprog.cs.fsu.edu failed: Error: Connecting was canceled
[11:26:11.652] Error opening exec server for ssh-remote+linprog.cs.fsu.edu: Error: Connecting was canceled

**Comment by roblourens** [comment]
```
[11:26:04.287] > Corrupted MAC on input.

ssh_dispatch_run_fatal: Connection to 128.186.122.110 port 22: message authentication code incorrect
The process tried to write to a nonexistent pipe.
```

These are just errors directly from ssh itself, something is wrong with your configuration.

**Comment by surapuramakhil** [comment]
[12:43:45.977] Log Level: 2
[12:43:45.991] SSH Resolver called for "ssh-remote+154.41.253.115", attempt 1
[12:43:45.991] "remote.SSH.useLocalServer": false
[12:43:45.991] "remote.SSH.useExecServer": false
[12:43:45.992] "remote.SSH.showLoginTerminal": false
[12:43:45.995] "remote.SSH.remotePlatform": {"linprog.cs.fsu.edu":"linux"}
[12:43:45.995] "remote.SSH.path": undefined
[12:43:45.995] "remote.SSH.configFile": undefined
[12:43:45.996] "remote.SSH.useFlock": true
[12:43:45.996] "remote.SSH.lockfilesInTmp": false
[12:43:45.996] "remote.SSH.localServerDownload": auto
[12:43:45.996] "remote.SSH.remoteServerListenOnSocket": false
[12:43:45.996] "remote.SSH.showLoginTerminal": false
[12:43:45.996] "remote.SSH.defaultExtensions": []
[12:43:45.996] "remote.SSH.loglevel": 2
[12:43:45.997] "remote.SSH.enableDynamicForwarding": true
[12:43:45.997] "remote.SSH.enableRemoteCommand": false
[12:43:45.997] "remote.SSH.serverPickPortsFromRange": {}
[12:43:45.998] "remote.SSH.serverInstallPath": {}
[12:43:46.006] VS Code version: 1.85.2
[12:43:46.006] Remote-SSH version: remote-ssh@0.107.1
[12:43:46.006] win32 x64
[12:43:46.007] SSH Resolver called for host: 154.41.253.115
[12:43:46.007] Setting up SSH remote "154.41.253.115"
[12:43:46.011] Using commit id "8b3775030ed1a69b13e4f4c628c612102e30a681" and quality "stable" for server
[12:43:46.015] Install and start server if needed
[12:43:48.414] Checking ssh with "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe -V"
[12:43:48.417] Got error from ssh: spawn C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[12:43:48.417] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[12:43:48.419] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[12:43:48.419] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[12:43:48.422] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[12:43:48.422] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[12:43:48.427] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[12:43:48.427] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[12:43:48.429] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[12:43:48.430] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[12:43:48.498] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[12:43:48.505] Running script with connection command: "C:\WINDOWS\System32\OpenSSH\ssh.exe" -T -D 11823 "154.41.253.115" bash
[12:43:48.512] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[12:43:50.528] > The authenticity of host '154.41.253.115 (154.41.253.115)' can't be established.
> ED25519 key fingerprint is SHA256:mDSJzRH+LySYniDCv+5o81JolCDTtVzwlyVNVGgyVM8.
> This key is not known by any other names
> Are you sure you want to continue connecting (yes/no/[fingerprint])?]0;C:\WINDOWS\System32\cmd.exe
[12:43:50.529] Got some output, clearing connection timeout
[12:43:50.529] Detected fingerprint confirmation message
[12:43:50.529] Showing fingerprint confirmation dialog
[12:43:53.082] Got fingerprint response: yes
[12:43:53.083] "install" wrote data to terminal: "yes"
[12:43:53.134] > yes
> Warning: Permanently added '154.41.253.115' (ED25519) to the list of known hosts.
[12:43:54.135] > root@154.41.253.115's password: 
[12:43:54.135] Showing password prompt
[12:44:12.404] Got password response
[12:44:12.404] "install" wrote data to terminal: "*************"
[12:44:12.462] > 
[12:44:16.096] > Permission denied, please try again.
> root@154.41.253.115's password: 
[12:44:16.097] Showing password prompt
[12:45:10.671] Got password response
[12:45:10.672] "install" wrote data to terminal: "*************"
[12:45:10.716] > 
[12:45:10.972] > Connection reset by 154.41.253.115 port 22
[12:45:11.004] > The process tried to write to a nonexistent pipe.
[12:45:12.296] "install" terminal command done
[12:45:12.296] Install terminal quit with output: Connection reset by 154.41.253.115 port 22
[12:45:12.297] Received install output: Connection reset by 154.41.253.115 port 22
[12:45:12.298] Failed to parse remote port from server output
[12:45:12.301] Resolver error: Error: 
	at g.Create (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:642703)
	at t.handleInstallOutput (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:640069)
	at t.tryInstall (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:761983)
	at async c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:722522
	at async t.withShowDetailsEvent (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:725828)
	at async I (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:719493)
	at async t.resolve (c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:723199)
	at async c:\Users\surap\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:907003
[12:45:12.309] ------




[12:45:13.995] Opening exec server for ssh-remote+154.41.253.115
[12:45:14.027] Initizing new exec server for ssh-remote+154.41.253.115
[12:45:14.071] Using commit id "8b3775030ed1a69b13e4f4c628c612102e30a681" and quality "stable" for server
[12:45:14.076] Install and start server if needed
[12:45:21.475] getPlatformForHost was canceled
[12:45:21.475] Exec server for ssh-remote+154.41.253.115 failed: Error: Connecting was canceled
[12:45:21.476] Error opening exec server for ssh-remote+154.41.253.115: Error: Connecting was canceled
