### ISSUE TITLE
Symbol Not Found

### ISSUE THREAD

**Issue by tomohulk** [microsoft/vscode-remote-release#9449]
Having trouble trying to run a basic alpine image as a dev container.  Here is my dockerfile:

```dockerfile
# Create a Jekyll container from a Ruby Alpine image
FROM ruby:2.7.4-alpine

# Add Jekyll dependencies to Alpine
RUN apk update
RUN apk add --no-cache build-base gcc cmake git

# Update the Ruby bundler and install Jekyll
RUN gem update bundler && gem install bundler -v 2.4.22
```

I keep getting a `Symbol not found`, and it makes the container terminate right a way.  Here its he tail of the log.  Im not sure what it's trying to do exactly.  I have not edited the devcontainer.json at all.

```
[2024-01-28T15:54:54.804Z] Container server: Error relocating /root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEv: symbol not found
Error relocating /root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/node: _ZSt28__throw_bad_array_new_lengthv: symbol not found
[2024-01-28T15:54:54.810Z] Error reading shell environment.
[2024-01-28T15:54:54.810Z] Error: stream ended with:0 but wanted:9
	at l (/Users/tomohulk/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/extension/extension.js:27:22149)
	at /Users/tomohulk/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/extension/extension.js:27:22330
	at s (/Users/tomohulk/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/extension/extension.js:30:5371)
	at Socket.<anonymous> (/Users/tomohulk/.vscode/extensions/ms-vscode-remote.remote-containers-0.327.0/dist/extension/extension.js:30:5541)
	at Socket.emit (node:events:525:35)
	at endReadableNT (node:internal/streams/readable:1359:12)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[2024-01-28T15:54:54.810Z] Start: Run in container: mkdir -p '/tmp/devcontainers-a56dbf68-4d17-4de5-a85c-d088af062e111706457292957' && cat > '/tmp/devcontainers-a56dbf68-4d17-4de5-a85c-d088af062e111706457292957/env-loginInteractiveShell.json' << 'envJSON'
[2024-01-28T15:54:54.810Z] Stop (95 ms): Run in container: /bin/sh
[2024-01-28T15:54:54.810Z] Container server terminated (code: 127, signal: null).
[2024-01-28T15:54:54.811Z] 
[2024-01-28T15:54:54.811Z] 
[2024-01-28T15:54:54.811Z] Stop (1 ms): Run in container: mkdir -p '/tmp/devcontainers-a56dbf68-4d17-4de5-a85c-d088af062e111706457292957' && cat > '/tmp/devcontainers-a56dbf68-4d17-4de5-a85c-d088af062e111706457292957/env-loginInteractiveShell.json' << 'envJSON'
[2024-01-28T15:54:54.815Z] Stop (74 ms): Run in container: /root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/bin/code-server --log debug --force-disable-user-env --server-data-dir /root/.vscode-server --use-host-proxy --telemetry-level all --accept-server-license-terms --host 127.0.0.1 --port 0 --connection-token-file /root/.vscode-server/data/Machine/.connection-token-8b3775030ed1a69b13e4f4c628c612102e30a681 --extensions-download-dir /root/.vscode-server/extensionsCache --start-server --disable-websocket-compression
[2024-01-28T15:54:54.817Z] Command failed: /root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/bin/code-server --log debug --force-disable-user-env --server-data-dir /root/.vscode-server --use-host-proxy --telemetry-level all --accept-server-license-terms --host 127.0.0.1 --port 0 --connection-token-file /root/.vscode-server/data/Machine/.connection-token-8b3775030ed1a69b13e4f4c628c612102e30a681 --extensions-download-dir /root/.vscode-server/extensionsCache --start-server --disable-websocket-compression
[2024-01-28T15:54:54.817Z] Error relocating /vscode/vscode-server/bin/alpine-arm64/8b3775030ed1a69b13e4f4c628c612102e30a681/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEv: symbol not found
Error relocating /vscode/vscode-server/bin/alpine-arm64/8b3775030ed1a69b13e4f4c628c612102e30a681/node: _ZSt28__throw_bad_array_new_lengthv: symbol not found
[2024-01-28T15:54:54.817Z] Exit code 127
```

MacBook Pro M2 on Sanomo 14.2.1
VSCode v1.85.2
Dev Container Ext v0.327.0
Docker Ext v1.28.0

**Comment by tomohulk** [comment]
image `ruby:2.7.8alpine3.16` does load and run.  I guess I'll have to find a new image to use to do my testing, or learn how to make my own?

**Comment by chrmarti** [comment]
@tomohulk There is a ruby base image for Dev Containers (e.g., Debian-based: `mcr.microsoft.com/devcontainers/ruby:1-3.3-bullseye`) and it `rbenv` utility appears to be able install ruby 2.7.4.

**Comment by tomohulk** [comment]
I'll give it a try.  I read to try and keep the container as lite as possible on arm so I was trying to use the the alpine image.  thanks.

**Comment by deepak1556** [comment]
@chrmarti thanks didn't know about this page, I will update it.

**Comment by fulldecent** [comment]
At the same time, this change also broke connecting to RHEL 7 servers. This is especially rough because RHEL ends support in June 2024 (so people are upgrading now), and version 7 is particularly difficult to upgrade from.
