### ISSUE TITLE
VS Code Remote debug (Windows to Raspberry Pi) 

### ISSUE THREAD

**Issue by martinbradburn** [microsoft/vscode-remote-release#945]
I am trying to set up remote debugging for Python 
on the below Raspberry Pi from a Window 7 box 
using VS Code Insiders 1.37.0

Linux wip-chassis 4.9.35-v7+ 
BST 2017 armv7l GNU/Linux
ldd (Debian GLIBC 2.19-18+deb8u10) 2.19
libstdc++6:armhf   4.9.2-10+deb8u2
python2.7   2.7.9-2+deb8u1 

I am unable to attach to the remote file system with the following errors:
Connected to SSH Host - Please do not close this terminal
 then
Error received from starting extension host
Unauthorized client refused

/C:/Users/Martin Bradburn/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3331 Error received from starting extension host
_extensionHostProcessProxy._extensionHostProcessWorker.start.then.e @ /C:/Users/Martin Bradburn/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3331
/C:/Users/Martin Bradburn/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:3331 Error: Connection error: Unauthorized client refused.
    at f (/C:/Users/Martin Bradburn/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1559)
    at i.onControlMessage.o (/C:/Users/Martin Bradburn/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1558)
    at d.fire (/C:/Users/Martin Bradburn/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:79)
    at a (/C:/Users/Martin Bradburn/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:314)
    at e (/C:/Users/Martin Bradburn/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:314)
    at d.fire (/C:/Users/Martin Bradburn/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:79)
    at S._receiveMessage (/C:/Users/Martin Bradburn/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:323)
    at S._socketDisposables.push._socketReader.onMessage.e (/C:/Users/Martin Bradburn/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:320)
    at d.fire (/C:/Users/Martin Bradburn/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:79)
    at g.acceptChunk (/C:/Users/Martin Bradburn/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:317)
    at _register._socket.onData.e (/C:/Users/Martin Bradburn/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:316)
    at Socket.t (/C:/Users/Martin Bradburn/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:325)
    at Socket.emit (/C:/Users/Martin%20Bradburn/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/workbench/events.js:182)
    at addChunk (/C:/Users/Martin%20Bradburn/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/workbench/_stream_readable.js:283)
    at readableAddChunk (/C:/Users/Martin%20Bradburn/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/workbench/_stream_readable.js:264)
    at Socket.Readable.push (/C:/Users/Martin%20Bradburn/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/workbench/_stream_readable.js:219)
    at TCP.onStreamRead (/C:/Users/Martin%20Bradburn/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/workbench/internal/stream_base_commons.js:94)

I can ssh to the Pi with no password.

I believe I have met all the requirements for remote Linux for the PI

Ubuntu 16.04+, Debian 8+, Raspbian and downstream distributions | libc6 libstdc++6 python-minimal ca-certificates tar | openssh-server bashand curl or wget | Requires kernel >= 3.10, glibc >= 2.17, libstdc++ >= 3.4.18. Debian < 8 (Jessie) and Ubuntu < 14.04 do not meet this requirement.

Any assistance is greatly appreciated.

**Comment by martinbradburn** [comment]
C could someone help me out with this please. Thanks in advance.

**Comment by martinbradburn** [comment]
Found this log file:

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


{ errorCode: 'load',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ],
  detail:
   **Error: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/sysop/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/node_modules/spdlog/build/Release/spdlog.node)**
       at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
       at Module.load (internal/modules/cjs/loader.js:599:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
       at Function.Module._load (internal/modules/cjs/loader.js:530:3)
       at Module.require (internal/modules/cjs/loader.js:637:17)
       at Module.patchedRequire [as require] (/home/sysop/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
       at require (internal/modules/cjs/helpers.js:20:18)
       at bindings (/home/sysop/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/node_modules/bindings/bindings.js:112:48)
       at Object.<anonymous> (/home/sysop/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/node_modules/spdlog/index.js:3:35)
       at Module._compile (internal/modules/cjs/loader.js:689:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
       at Module.load (internal/modules/cjs/loader.js:599:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
       at Function.Module._load (internal/modules/cjs/loader.js:530:3)
       at Module.require (internal/modules/cjs/loader.js:637:17)
       at Module.patchedRequire [as require] (/home/sysop/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
       at require (internal/modules/cjs/helpers.js:20:18)
       at t.load (/home/sysop/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/out/vs/loader.js:16:247)
       at e.load (/home/sysop/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/out/vs/loader.js:13:587)
       at i (/home/sysop/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/out/vs/loader.js:28:371)
       at Object.errorback (/home/sysop/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/out/vs/loader.js:28:492)
       at e.triggerErrorback (/home/sysop/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/out/vs/loader.js:13:952)
       at /home/sysop/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/out/vs/loader.js:13:657
       at ReadFileContext.callback (/home/sysop/.vscode-server-insiders/bin/188180bccf1f56b3368c4eb20e877238d69925b8/out/vs/loader.js:16:617)
       at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13) }
IP Address: 192.168.10.208
webview server listening on 42047
Extension host agent listening on 41391
Unauthorized client refused.

**Comment by Chuxel** [comment]
@martinbradburn FYI - This is #1030.
