### ISSUE TITLE
[Remote-SSH Bug]: Mysterious behaviour of useLocalServer

### ISSUE THREAD

**Issue by DavidC-75** [microsoft/vscode-remote-release#9468]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Steps To Reproduce

I'm trying to connect from my local Windows machine to a remote Linux machine

The GUI pretends that by default, `useLocalServer` is true
![image](https://github.com/microsoft/vscode-remote-release/assets/98928623/2c10152e-eec6-4be9-a929-8dbf731e4f01)

I'm happy to trust that, and I can successfully connect.... but it's not the whole story

In the GUI, if I untick the box, I can see (as expected) that in my `settings.json` one line is automatically added : 

`"remote.SSH.useLocalServer": false`

I'm happy to trust that, and I can successfully connect again.... But that doesn't make any sense though. According to the [troubleshooting page](https://code.visualstudio.com/docs/remote/troubleshooting#_enabling-alternate-ssh-authentication-methods), this has the effect to 
> specifically tell VS Code if your SSH host is running Windows

(which is not the case since my host is running Linux). How is it possible for the connection to be successful then ?

Going further, I can tick the box again, and I can see (still as expected) that in my `settings.json` the said line disappears.
I'm back to the initial conditions and everything looks fine... But it isn't really : if, **instead of ticking the box again** (which **deletes the line**), I manually **change the line** to be `"remote.SSH.useLocalServer": true` then I get this:
![image](https://github.com/microsoft/vscode-remote-release/assets/98928623/d15039f9-9add-4c85-9a42-da6eeafa37f2)

What's going on ?? It doesn't work, but at least it makes sense (since my host is Linux). 

This really suggests that there are 3 different behaviours: one when `useLocalServer` is **explicitly defined as true**, one one when `useLocalServer` is **explicitly defined as false**, and one when it's **undefined** (which the GUI reports as true, but is actually something different).

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[16:36:46.635] Log Level: 2
[16:36:46.650] SSH Resolver called for "ssh-remote+myhost", attempt 1
[16:36:46.650] "remote.SSH.useLocalServer": true
[16:36:46.650] "remote.SSH.useExecServer": false
[16:36:46.650] "remote.SSH.path": undefined
[16:36:46.650] "remote.SSH.configFile": undefined
[16:36:46.651] "remote.SSH.useFlock": true
[16:36:46.651] "remote.SSH.lockfilesInTmp": false
[16:36:46.651] "remote.SSH.localServerDownload": auto
[16:36:46.651] "remote.SSH.remoteServerListenOnSocket": false
[16:36:46.651] "remote.SSH.showLoginTerminal": true
[16:36:46.651] "remote.SSH.defaultExtensions": []
[16:36:46.651] "remote.SSH.loglevel": 2
[16:36:46.651] "remote.SSH.enableDynamicForwarding": true
[16:36:46.651] "remote.SSH.enableRemoteCommand": true
[16:36:46.651] "remote.SSH.serverPickPortsFromRange": {}
[16:36:46.651] "remote.SSH.serverInstallPath": {}
[16:36:46.655] VS Code version: 1.86.0
[16:36:46.655] Remote-SSH version: remote-ssh@0.107.1
[16:36:46.655] win32 x64
[16:36:46.656] SSH Resolver called for host: myhost
[16:36:46.668] Acquiring local install lock: C:\Users\anonymous\AppData\Local\Temp\vscode-remote-ssh-06e80327-install.lock
[16:36:46.670] Looking for existing server data file at c:\Users\anonymous\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-ssh\vscode-ssh-host-06e80327-05047486b6df5eb8d44b2ecd70ea3bdf775fd937-0.107.1-tr\data.json
[16:36:46.674] Using commit id "05047486b6df5eb8d44b2ecd70ea3bdf775fd937" and quality "stable" for server
[16:36:46.676] Install and start server if needed
[16:36:46.679] Checking ssh with "C:\Program Files (x86)\Qualcomm\PHMDB\ssh.exe -V"
[16:36:46.680] Got error from ssh: spawn C:\Program Files (x86)\Qualcomm\PHMDB\ssh.exe ENOENT
[16:36:46.680] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[16:36:46.681] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[16:36:46.682] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[16:36:46.683] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[16:36:46.683] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[16:36:46.684] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[16:36:46.684] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[16:36:46.686] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[16:36:46.688] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[16:36:46.748] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[16:36:46.752] Checking ssh with "C:\Program Files (x86)\Sennheiser\SoftphoneSDK\ssh.exe -V"
[16:36:46.754] Got error from ssh: spawn C:\Program Files (x86)\Sennheiser\SoftphoneSDK\ssh.exe ENOENT
[16:36:46.754] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[16:36:46.756] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[16:36:46.756] Checking ssh with "C:\WINDOWS\System32\ssh.exe -V"
[16:36:46.757] Got error from ssh: spawn C:\WINDOWS\System32\ssh.exe ENOENT
[16:36:46.757] Checking ssh with "C:\WINDOWS\System32\wbem\ssh.exe -V"
[16:36:46.758] Got error from ssh: spawn C:\WINDOWS\System32\wbem\ssh.exe ENOENT
[16:36:46.758] Checking ssh with "C:\Program Files\MATLAB\R2020b\runtime\win64\ssh.exe -V"
[16:36:46.759] Got error from ssh: spawn C:\Program Files\MATLAB\R2020b\runtime\win64\ssh.exe ENOENT
[16:36:46.759] Checking ssh with "C:\Program Files\MATLAB\R2020b\bin\ssh.exe -V"
[16:36:46.760] Got error from ssh: spawn C:\Program Files\MATLAB\R2020b\bin\ssh.exe ENOENT
[16:36:46.760] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[16:36:46.761] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[16:36:46.761] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[16:36:46.762] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[16:36:46.762] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[16:36:46.763] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[16:36:46.763] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[16:36:46.765] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[16:36:46.765] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[16:36:46.820] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[16:36:46.824] Checking ssh with "C:\Program Files (x86)\MATLAB\R2008b\bin\ssh.exe -V"
[16:36:46.825] Got error from ssh: spawn C:\Program Files (x86)\MATLAB\R2008b\bin\ssh.exe ENOENT
[16:36:46.825] Checking ssh with "C:\Program Files (x86)\MATLAB\R2008b\bin\win32\ssh.exe -V"
[16:36:46.826] Got error from ssh: spawn C:\Program Files (x86)\MATLAB\R2008b\bin\win32\ssh.exe ENOENT
[16:36:46.827] Checking ssh with "C:\Program Files\Perforce\ssh.exe -V"
[16:36:46.828] Got error from ssh: spawn C:\Program Files\Perforce\ssh.exe ENOENT
[16:36:46.828] Checking ssh with "C:\Users\anonymous\AppData\Local\Microsoft\WindowsApps\ssh.exe -V"
[16:36:46.829] Got error from ssh: spawn C:\Users\anonymous\AppData\Local\Microsoft\WindowsApps\ssh.exe ENOENT
[16:36:46.829] Checking ssh with "C:\Users\anonymous\.local\bin\ssh.exe -V"
[16:36:46.830] Got error from ssh: spawn C:\Users\anonymous\.local\bin\ssh.exe ENOENT
[16:36:46.830] Checking ssh with "C:\Users\anonymous\AppData\Roaming\Python\Python38\Scripts\ssh.exe -V"
[16:36:46.831] Got error from ssh: spawn C:\Users\anonymous\AppData\Roaming\Python\Python38\Scripts\ssh.exe ENOENT
[16:36:46.831] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[16:36:46.887] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[16:36:46.891] Checking ssh with "C:\Program Files\Git\usr\bin\ssh.exe -V"
[16:36:46.893] Got error from ssh: spawn C:\Program Files\Git\usr\bin\ssh.exe ENOENT
[16:36:46.893] Checking ssh with "C:\Program Files (x86)\Git\usr\bin\ssh.exe -V"
[16:36:46.895] Got error from ssh: spawn C:\Program Files (x86)\Git\usr\bin\ssh.exe ENOENT
[16:36:46.895] Checking ssh with "C:\Program Files (x86)\Qualcomm\PHMDB\ssh.exe -V"
[16:36:46.897] Got error from ssh: spawn C:\Program Files (x86)\Qualcomm\PHMDB\ssh.exe ENOENT
[16:36:46.897] Checking ssh with "C:\WINDOWS\system32\ssh.exe -V"
[16:36:46.899] Got error from ssh: spawn C:\WINDOWS\system32\ssh.exe ENOENT
[16:36:46.899] Checking ssh with "C:\WINDOWS\ssh.exe -V"
[16:36:46.900] Got error from ssh: spawn C:\WINDOWS\ssh.exe ENOENT
[16:36:46.901] Checking ssh with "C:\WINDOWS\System32\Wbem\ssh.exe -V"
[16:36:46.902] Got error from ssh: spawn C:\WINDOWS\System32\Wbem\ssh.exe ENOENT
[16:36:46.902] Checking ssh with "C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[16:36:46.903] Got error from ssh: spawn C:\WINDOWS\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[16:36:46.904] Checking ssh with "C:\WINDOWS\System32\OpenSSH\ssh.exe -V"
[16:36:46.962] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[16:36:46.967] Cannot use RemoteCommand if you have this remote in your "remote.SSH.remotePlatform" setting.
[16:36:46.968] Using SSH config file "C:\Users\anonymous\.ssh\config"
[16:36:46.968] askpass server listening on \\.\pipe\vscode-ssh-askpass-9590a453b56927a19e5d2e0b2867d24a8eb3f44e-sock
[16:36:46.969] Spawning local server with {"serverId":1,"ipcHandlePath":"\\\\.\\pipe\\vscode-ssh-askpass-25700dac20362541e8902e3429b868d69832d638-sock","sshCommand":"C:\\WINDOWS\\System32\\OpenSSH\\ssh.exe","sshArgs":["-v","-T","-D","54259","-o","RemoteCommand=none","-F","C:\\Users\\anonymous\\.ssh\\config","myhost","bash"],"serverDataFolderName":".vscode-server","dataFilePath":"c:\\Users\\anonymous\\AppData\\Roaming\\Code\\User\\globalStorage\\ms-vscode-remote.remote-ssh\\vscode-ssh-host-06e80327-05047486b6df5eb8d44b2ecd70ea3bdf775fd937-0.107.1-tr\\data.json"}
[16:36:46.969] Local server env: {"DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"c:\\Users\\anonymous\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.107.1\\out\\local-server\\askpass.bat","VSCODE_SSH_ASKPASS_NODE":"C:\\Users\\anonymous\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"c:\\Users\\anonymous\\.vscode\\extensions\\ms-vscode-remote.remote-ssh-0.107.1\\out\\askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"\\\\.\\pipe\\vscode-ssh-askpass-9590a453b56927a19e5d2e0b2867d24a8eb3f44e-sock"}
[16:36:46.984] Spawned 9220
[16:36:47.183] > local-server-1> Running ssh connection command: "-v -T -D 54259 -o RemoteCommand=none -F C:\\Users\\anonymous\\.ssh\\config myhost bash"
[16:36:47.194] > local-server-1> Spawned ssh, pid=6088
[16:36:47.299] stderr> OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3
[16:36:47.495] stderr> debug1: Server host key: ssh-ed25519 SHA256:tplMdd62wJpPpeNtUe0+HdAjEoCQWsDEC887IBhFnhY
[16:37:03.987] Terminating local server
[16:37:03.993] Resolver error: Error: Connecting with SSH timed out
	at g.Timeout (c:\Users\anonymous\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:642829)
	at Timeout._onTimeout (c:\Users\anonymous\.vscode\extensions\ms-vscode-remote.remote-ssh-0.107.1\out\extension.js:2:707323)
	at listOnTimeout (node:internal/timers:569:17)
	at process.processTimers (node:internal/timers:512:7)
[16:37:04.005] ------




[16:37:04.010] Local server exit: null

```

</p>
</details>

**Comment by roblourens** [comment]
Yes, long story short, for windows you have to set this in your settings.json to enable it since we can't have os-specific setting defaults from extensions. This was supposed to be temporary, but it is still disabled by default on windows due to issues :)

Also some details here, if you didn't see it
