### ISSUE TITLE
[Remote-SSH Bug]: Error: Missing required dependencies

### ISSUE THREAD

**Issue by Fausro** [microsoft/vscode-remote-release#9485]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

Until the last update it worked perfectly and there were no dependency errors. Now, even installing the previous version it still does not work.

In the vscode-server .log file it says 
Warning: Missing GLIBCXX >= 3.4.25! from /usr/lib64/libstdc++.so.6.0.19
Warning: Missing GLIBC >= 2.28! from /usr/lib64/libc-2.17.so
Error: Missing required dependencies. Please refer to our FAQ https://aka.ms/vsc
ode-remote/faq/old-linux for additional information.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[12:34:13.849] stderr> rm: cannot remove ‘/gaueko0/users/xlarrayoz001/.vscode-server/.05047486b6df5eb8d44b2ecd70ea3bdf775fd937.token’: No such file or directory
[12:34:13.857] > Spawned remote server: 30067
[12:34:13.861] > Waiting for server log...
[12:34:13.898] > Waiting for server log...
[12:34:13.933] > Waiting for server log...
[12:34:13.969] > Waiting for server log...
[12:34:14.005] > Waiting for server log...
[12:34:14.041] > Waiting for server log...
[12:34:14.076] > Waiting for server log...
[12:34:14.115] > Waiting for server log...
[12:34:14.149] > Waiting for server log...
[12:34:14.185] > Waiting for server log...
[12:34:14.223] > Waiting for server log...
[12:34:14.255] > Waiting for server log...
[12:34:14.291] > Waiting for server log...
[12:34:14.327] > Waiting for server log...
[12:34:14.362] > Waiting for server log...
[12:34:14.399] > Waiting for server log...
[12:34:14.434] > Waiting for server log...
[12:34:14.470] > Waiting for server log...
[12:34:14.506] > Waiting for server log...
[12:34:14.542] > Waiting for server log...
[12:34:14.577] > Waiting for server log...
[12:34:14.612] > Waiting for server log...
[12:34:14.648] > Waiting for server log...
[12:34:14.683] > Waiting for server log...
[12:34:14.719] > Waiting for server log...
[12:34:14.756] > Waiting for server log...
[12:34:14.791] > Waiting for server log...
[12:34:14.829] > Waiting for server log...
[12:34:14.862] > Waiting for server log...
[12:34:14.898] > Waiting for server log...
[12:34:14.934] > Waiting for server log...
[12:34:14.969] > Waiting for server log...
[12:34:15.005] > Waiting for server log...
[12:34:15.041] > Waiting for server log...
[12:34:15.077] > Waiting for server log...
[12:34:15.112] > Waiting for server log...
[12:34:15.149] > Waiting for server log...
[12:34:15.183] > Waiting for server log...
[12:34:15.218] > Waiting for server log...
[12:34:15.254] > Waiting for server log...
[12:34:15.290] > Waiting for server log...
[12:34:15.326] > Waiting for server log...
[12:34:15.362] > Waiting for server log...
[12:34:15.398] > Waiting for server log...
[12:34:15.433] > Waiting for server log...
[12:34:15.469] > Waiting for server log...
[12:34:15.505] > Waiting for server log...
[12:34:15.541] > Waiting for server log...
[12:34:15.576] > Waiting for server log...
[12:34:15.612] > Waiting for server log...
[12:34:15.648] > Waiting for server log...
[12:34:15.684] > Waiting for server log...
[12:34:15.719] > Waiting for server log...
[12:34:15.755] > Waiting for server log...
[12:34:15.790] > Waiting for server log...
[12:34:15.826] > Waiting for server log...
[12:34:15.862] > Waiting for server log...
[12:34:15.898] > Waiting for server log...
[12:34:15.934] > Waiting for server log...
[12:34:15.969] > Waiting for server log...
[12:34:16.007] > Waiting for server log...
[12:34:16.041] > Waiting for server log...
[12:34:16.076] > Waiting for server log...
[12:34:16.112] > Waiting for server log...
[12:34:16.148] > Waiting for server log...
[12:34:16.184] > Waiting for server log...
[12:34:16.220] > Waiting for server log...
[12:34:16.255] > Waiting for server log...
[12:34:16.291] > Waiting for server log...
[12:34:16.329] > Waiting for server log...
[12:34:16.362] > Waiting for server log...
[12:34:16.399] > Waiting for server log...
[12:34:16.434] > Waiting for server log...
[12:34:16.470] > Waiting for server log...
[12:34:16.506] > Waiting for server log...
[12:34:16.541] > Waiting for server log...
[12:34:16.577] > Waiting for server log...
[12:34:16.613] > Waiting for server log...
[12:34:16.648] > Waiting for server log...
[12:34:16.685] > Waiting for server log...
[12:34:16.720] > Waiting for server log...
[12:34:16.757] > Waiting for server log...
[12:34:16.792] > Waiting for server log...
[12:34:16.829] > Waiting for server log...
[12:34:16.864] > Waiting for server log...
[12:34:16.900] > Waiting for server log...
[12:34:16.936] > Waiting for server log...
[12:34:16.971] > Waiting for server log...
[12:34:17.007] > Waiting for server log...
[12:34:17.043] > Waiting for server log...
[12:34:17.079] > Waiting for server log...
[12:34:17.115] > Waiting for server log...
[12:34:17.151] > Waiting for server log...
[12:34:17.186] > Waiting for server log...
[12:34:17.222] > Waiting for server log...
[12:34:17.257] > Waiting for server log...
[12:34:17.294] > Waiting for server log...
[12:34:17.330] > Waiting for server log...
[12:34:17.365] > Waiting for server log...
[12:34:17.401] > Waiting for server log...
[12:34:17.437] > Waiting for server log...
[12:34:17.473] > Waiting for server log...
[12:34:17.509] > Waiting for server log...
[12:34:17.544] > Waiting for server log...
[12:34:17.581] > Waiting for server log...
[12:34:17.616] > Waiting for server log...
[12:34:17.652] > Waiting for server log...
[12:34:17.688] > Waiting for server log...
[12:34:17.723] > Waiting for server log...
[12:34:17.760] > Waiting for server log...
[12:34:17.796] > Waiting for server log...
[12:34:17.831] > Waiting for server log...
[12:34:17.867] > Waiting for server log...
[12:34:17.903] > Waiting for server log...
[12:34:17.938] > Waiting for server log...
[12:34:17.974] > Waiting for server log...
[12:34:18.010] > Waiting for server log...
[12:34:18.046] > Waiting for server log...
[12:34:18.084] > Waiting for server log...
[12:34:18.117] > Waiting for server log...
[12:34:18.153] > Waiting for server log...
[12:34:18.189] > Waiting for server log...
[12:34:18.225] > Waiting for server log...
[12:34:18.261] > Waiting for server log...
[12:34:18.297] > Waiting for server log...
[12:34:18.333] > Waiting for server log...
[12:34:18.368] > Waiting for server log...
[12:34:18.405] > Waiting for server log...
[12:34:18.440] > Waiting for server log...
[12:34:18.476] > Waiting for server log...
[12:34:18.512] > Waiting for server log...
[12:34:18.548] > Waiting for server log...
[12:34:18.583] > Waiting for server log...
[12:34:18.619] > Waiting for server log...
[12:34:18.655] > Waiting for server log...
[12:34:18.691] > Waiting for server log...
[12:34:18.727] > Waiting for server log...
[12:34:18.762] > Waiting for server log...
[12:34:18.799] > Waiting for server log...
[12:34:18.834] > Waiting for server log...
[12:34:18.870] > Waiting for server log...
[12:34:18.905] > Waiting for server log...
[12:34:18.941] > Waiting for server log...
[12:34:18.978] > Waiting for server log...
[12:34:19.013] > Waiting for server log...
[12:34:19.049] > Waiting for server log...
[12:34:19.085] > Waiting for server log...
[12:34:19.121] > Waiting for server log...
[12:34:19.157] > Waiting for server log...
[12:34:19.192] > Waiting for server log...
[12:34:19.229] > Waiting for server log...
[12:34:19.264] > Waiting for server log...
[12:34:19.301] > Waiting for server log...
[12:34:19.336] > Waiting for server log...
[12:34:19.372] > Waiting for server log...
[12:34:19.408] > Waiting for server log...
[12:34:19.443] > Waiting for server log...
[12:34:19.479] > Waiting for server log...
[12:34:19.515] > Waiting for server log...
[12:34:19.550] > Waiting for server log...
[12:34:19.587] > Waiting for server log...
[12:34:19.622] > Waiting for server log...
[12:34:19.658] > Waiting for server log...
[12:34:19.694] > Waiting for server log...
[12:34:19.730] > Waiting for server log...
[12:34:19.765] > Waiting for server log...
[12:34:19.802] > Waiting for server log...
[12:34:19.837] > Waiting for server log...
[12:34:19.873] > Waiting for server log...
[12:34:19.909] > Waiting for server log...
[12:34:19.945] > Waiting for server log...
[12:34:19.981] > Waiting for server log...
[12:34:20.017] > Waiting for server log...
[12:34:20.052] > Waiting for server log...
[12:34:20.088] > Waiting for server log...
[12:34:20.124] > Waiting for server log...
[12:34:20.160] > Waiting for server log...
[12:34:20.197] > Waiting for server log...
[12:34:20.232] > Waiting for server log...
[12:34:20.267] > Waiting for server log...
[12:34:20.303] > Waiting for server log...
[12:34:20.339] > Waiting for server log...
[12:34:20.375] > Waiting for server log...
[12:34:20.414] > Waiting for server log...
[12:34:20.447] > Waiting for server log...
[12:34:20.483] > Waiting for server log...
[12:34:20.519] > Waiting for server log...
[12:34:20.554] > Waiting for server log...
[12:34:20.590] > Waiting for server log...
[12:34:20.626] > Waiting for server log...
[12:34:20.662] > Waiting for server log...
[12:34:20.698] > Waiting for server log...
[12:34:20.734] > Waiting for server log...
[12:34:20.769] > Waiting for server log...
[12:34:20.805] > Waiting for server log...
[12:34:20.841] > Waiting for server log...
[12:34:20.876] > Waiting for server log...
[12:34:20.912] > Waiting for server log...
[12:34:20.948] > Waiting for server log...
[12:34:20.984] > Waiting for server log...
[12:34:21.020] > Waiting for server log...
[12:34:21.056] > Waiting for server log...
[12:34:21.092] > Waiting for server log...
[12:34:21.128] > Waiting for server log...
[12:34:21.163] > Waiting for server log...
[12:34:21.199] > Waiting for server log...
[12:34:21.235] > Waiting for server log...
[12:34:21.270] > Waiting for server log...
[12:34:21.306] > Waiting for server log...
[12:34:21.342] > Waiting for server log...
[12:34:21.377] > Waiting for server log...
[12:34:21.413] > Waiting for server log...
[12:34:21.449] > Waiting for server log...
[12:34:21.485] > Waiting for server log...
[12:34:21.521] > Waiting for server log...
[12:34:21.556] > Waiting for server log...
[12:34:21.592] > Waiting for server log...
[12:34:21.628] > Waiting for server log...
[12:34:21.664] > Waiting for server log...
[12:34:21.701] > Waiting for server log...
[12:34:21.735] > Waiting for server log...
[12:34:21.772] > Waiting for server log...
[12:34:21.807] > Waiting for server log...
[12:34:21.843] > Waiting for server log...
[12:34:21.879] > Waiting for server log...
[12:34:21.915] > Waiting for server log...
[12:34:21.951] > Waiting for server log...
[12:34:21.986] > Waiting for server log...
[12:34:22.022] > Waiting for server log...
[12:34:22.059] > Waiting for server log...
[12:34:22.095] > Waiting for server log...
[12:34:22.131] > Waiting for server log...
[12:34:22.166] > Waiting for server log...
[12:34:22.202] > Waiting for server log...
[12:34:22.238] > Waiting for server log...
[12:34:22.273] > Waiting for server log...
[12:34:22.309] > Waiting for server log...
[12:34:22.344] > Waiting for server log...
[12:34:22.380] > Waiting for server log...
[12:34:22.416] > Waiting for server log...
[12:34:22.453] > Waiting for server log...
[12:34:22.489] > Waiting for server log...
[12:34:22.525] > Waiting for server log...
[12:34:22.561] > Waiting for server log...
[12:34:22.596] > Waiting for server log...
[12:34:22.633] > Waiting for server log...
[12:34:22.668] > Waiting for server log...
[12:34:22.704] > Waiting for server log...
[12:34:22.740] > Waiting for server log...
[12:34:22.775] > Waiting for server log...
[12:34:22.811] > Waiting for server log...
[12:34:22.847] > Waiting for server log...
[12:34:22.883] > Waiting for server log...
[12:34:22.919] > Waiting for server log...
[12:34:22.954] > Waiting for server log...
[12:34:22.990] > Waiting for server log...
[12:34:23.026] > Waiting for server log...
[12:34:23.062] > Waiting for server log...
[12:34:23.098] > Waiting for server log...
[12:34:23.134] > Waiting for server log...
[12:34:23.170] > Waiting for server log...
[12:34:23.205] > Waiting for server log...
[12:34:23.241] > Waiting for server log...
[12:34:23.277] > Waiting for server log...
[12:34:23.313] > Waiting for server log...
[12:34:23.350] > Waiting for server log...
[12:34:23.385] > Waiting for server log...
[12:34:23.421] > Waiting for server log...
[12:34:23.456] > Waiting for server log...
[12:34:23.492] > Waiting for server log...
[12:34:23.529] > Waiting for server log...
[12:34:23.564] > Waiting for server log...
[12:34:23.600] > Waiting for server log...
[12:34:23.636] > Waiting for server log...
[12:34:23.672] > Waiting for server log...
[12:34:23.707] > Waiting for server log...
[12:34:23.743] > Waiting for server log...
[12:34:23.780] > Waiting for server log...
[12:34:23.815] > Waiting for server log...
[12:34:23.851] > Waiting for server log...
[12:34:23.887] > Waiting for server log...
[12:34:23.922] > Waiting for server log...
[12:34:23.959] > Waiting for server log...
[12:34:23.994] > Waiting for server log...
[12:34:24.030] > Waiting for server log...
[12:34:24.066] > Waiting for server log...
[12:34:24.102] > Waiting for server log...
[12:34:24.138] > Waiting for server log...
[12:34:24.174] > Waiting for server log...
[12:34:24.210] > Waiting for server log...
[12:34:24.246] > Waiting for server log...
[12:34:24.282] > Waiting for server log...
[12:34:24.317] > Waiting for server log...
[12:34:24.353] > Waiting for server log...
[12:34:24.389] > Waiting for server log...
[12:34:24.425] > Waiting for server log...
[12:34:24.461] > Waiting for server log...
[12:34:24.497] > Waiting for server log...
[12:34:24.533] > Waiting for server log...
[12:34:24.569] > Waiting for server log...
[12:34:24.604] > Waiting for server log...
[12:34:24.641] > Waiting for server log...
[12:34:24.676] > Waiting for server log...
[12:34:24.712] > Waiting for server log...
[12:34:24.748] > Waiting for server log...
[12:34:24.784] > Waiting for server log...
[12:34:24.820] > Waiting for server log...
[12:34:24.855] > Waiting for server log...
[12:34:24.891] > Waiting for server log...
[12:34:24.928] > Waiting for server log...
[12:34:24.963] > Waiting for server log...
[12:34:24.999] > Waiting for server log...
[12:34:25.040] > Waiting for server log...
[12:34:25.070] > Waiting for server log...
[12:34:25.106] > Waiting for server log...
[12:34:25.142] > Waiting for server log...
[12:34:25.178] > Waiting for server log...
[12:34:25.213] > Waiting for server log...
[12:34:25.249] > Waiting for server log...
[12:34:25.284] > Waiting for server log...
[12:34:25.321] > Waiting for server log...
[12:34:25.356] > Waiting for server log...
[12:34:25.392] > Waiting for server log...
[12:34:25.428] > Waiting for server log...
[12:34:25.464] > Waiting for server log...
[12:34:25.500] > Waiting for server log...
[12:34:25.536] > Waiting for server log...
[12:34:25.571] > Waiting for server log...
[12:34:25.607] > Waiting for server log...
[12:34:25.643] > Waiting for server log...
[12:34:25.679] > Waiting for server log...
[12:34:25.714] > Waiting for server log...
[12:34:25.750] > Waiting for server log...
[12:34:25.786] > Waiting for server log...
[12:34:25.822] > Waiting for server log...
[12:34:25.857] > Waiting for server log...
[12:34:25.894] > Waiting for server log...
[12:34:25.930] > Waiting for server log...
[12:34:25.966] > Waiting for server log...
[12:34:26.002] > Waiting for server log...
[12:34:26.039] > Waiting for server log...
[12:34:26.073] > Waiting for server log...
[12:34:26.109] > Waiting for server log...
[12:34:26.145] > Waiting for server log...
[12:34:26.181] > Waiting for server log...
[12:34:26.217] > Waiting for server log...
[12:34:26.253] > Waiting for server log...
[12:34:26.288] > Waiting for server log...
[12:34:26.324] > Waiting for server log...
[12:34:26.360] > Waiting for server log...
[12:34:26.396] > Waiting for server log...
[12:34:26.432] > Waiting for server log...
[12:34:26.467] > Waiting for server log...
[12:34:26.503] > Waiting for server log...
[12:34:26.539] > Waiting for server log...
[12:34:26.575] > Waiting for server log...
[12:34:26.611] > Waiting for server log...
[12:34:26.647] > Waiting for server log...
[12:34:26.682] > Waiting for server log...
[12:34:26.718] > Waiting for server log...
[12:34:26.754] > Waiting for server log...
[12:34:26.790] > Waiting for server log...
[12:34:26.826] > Waiting for server log...
[12:34:26.862] > Waiting for server log...
[12:34:26.897] > Waiting for server log...
[12:34:26.933] > Waiting for server log...
[12:34:26.969] > Waiting for server log...
[12:34:27.005] > Waiting for server log...
[12:34:27.041] > Waiting for server log...
[12:34:27.081] > Waiting for server log...
[12:34:27.112] > Waiting for server log...
[12:34:27.148] > Waiting for server log...
[12:34:27.184] > Waiting for server log...
[12:34:27.219] > Waiting for server log...
[12:34:27.256] > Waiting for server log...
[12:34:27.291] > Waiting for server log...
[12:34:27.328] > Waiting for server log...
[12:34:27.363] > Waiting for server log...
[12:34:27.399] > Waiting for server log...
[12:34:27.435] > Waiting for server log...
[12:34:27.470] > Waiting for server log...
[12:34:27.506] > Waiting for server log...
[12:34:27.542] > Waiting for server log...
[12:34:27.578] > Waiting for server log...
[12:34:27.614] > Waiting for server log...
[12:34:27.650] > Waiting for server log...
[12:34:27.686] > Waiting for server log...
[12:34:27.722] > Waiting for server log...
[12:34:27.758] > Waiting for server log...
[12:34:27.793] > Waiting for server log...
[12:34:27.829] > Waiting for server log...
[12:34:27.865] > Waiting for server log...
[12:34:27.901] > Waiting for server log...
[12:34:27.937] > Waiting for server log...
[12:34:27.972] > Waiting for server log...
[12:34:28.008] > Waiting for server log...
[12:34:28.045] >  
> *
> * Visual Studio Code Server
> *
[12:34:28.046] > * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
>  
[12:34:28.055] > Server did not start successfully. Full server log at /gaueko0/users/xlarrayoz001/.vscode-server/.05047486b6df5eb8d44b2ecd70ea3bdf775fd937.log >>>
[12:34:28.056] > Warning: Missing GLIBCXX >= 3.4.25! from /usr/lib64/libstdc++.so.6.0.19
> Warning: Missing GLIBC >= 2.28! from /usr/lib64/libc-2.17.so
> Error: Missing required dependencies. Please refer to our FAQ https://aka.ms/vscode-remote/faq/old-linux for additional information.
> <<< End of server log
> 5a1d73dd4380: start
> exitCode==32==
> listeningOn====
[12:34:28.085] > osReleaseId==centos==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/50459==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==14198==
> 5a1d73dd4380: end
[12:34:28.086] Received install output: 
exitCode==32==
listeningOn====osReleaseId==centos==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/50459==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==14198==

[12:34:28.087] Terminating local server
[12:34:28.091] Resolver error: Error: No se pudo iniciar VS Code Server
	at g.ServerInstallError (/home/xlarrayoz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:642637)
	at d (/home/xlarrayoz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:636024)
	at t.handleInstallOutput (/home/xlarrayoz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:638294)
	at e (/home/xlarrayoz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:700300)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /home/xlarrayoz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:722169
	at async t.withShowDetailsEvent (/home/xlarrayoz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:725828)
	at async /home/xlarrayoz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:697005
	at async C (/home/xlarrayoz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:695056)
	at async t.resolveWithLocalServer (/home/xlarrayoz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:696545)
	at async I (/home/xlarrayoz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:719392)
	at async t.resolve (/home/xlarrayoz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:723199)
	at async /home/xlarrayoz/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:907003
[12:34:28.102] ------




[12:34:28.107] Local server exit: 15

```

</p>
</details>

**Comment by aumungray** [comment]
Same problem here. I checked, I am able to open to do remote ssh in an ubuntu VM of aws ac2 but not inside that of a CENTOS VM. This is because, the centos VMs in aws have GLIBC==2.26 by default. Unfortunately after a lot of search I found out that there is no way to upgrade GLIBC to 2.31 (as it would cause lot of dependency conflicts). Unless the microsoft team helps with this, the only way around is to change the OS of the VM which will be harder than shifting to PyCharm.

**Comment by sastrybitapps** [comment]
Same problem, Waiting for solution

**Comment by DavidC-75** [comment]
> I found out that there is no way to upgrade GLIBC

What you probably mean is that the system glibc cannot (easily) be upgraded. But it is possible to build anywhere you like a more recent version of glibc and to work around the problem. See https://github.com/microsoft/vscode-remote-release/issues/9467

**Comment by vbelis** [comment]
Same problem here.

**Comment by mmazeika** [comment]
I think I'm having the same problem.

I’m able to download old versions of the code CLI using `curl -Lk 'https://update.code.visualstudio.com/1.84.2/cli-alpine-x64/stable' --output vscode_cli.tar.gz`, and running `./code tunnel` works at first, but then the following error occurs while the connection is loading:

```
An unexpected error occurred that requires a reload of this page.
The workbench failed to connect to the server (Error: WrappedError(WrappedError { message: "error checking server integrity", original: "failed to run command \"/data/mantas_mazeika/.vscode/cli/servers/Stable-05047486b6df5eb8d44b2ecd70ea3bdf775fd937.staging/server/bin/code-server --version\" (code 99): Warning: Missing GLIBCXX >= 3.4.25! from /usr/lib64/libstdc++.so.6.0.19\nWarning: Missing GLIBC >= 2.28! from /usr/lib64/libc-2.17.so\nError: Missing required dependencies. Please refer to our FAQ https://aka.ms/vscode-remote/faq/old-linux for additional information.\n" }))
```

The code CLI makes using VSCode on compute clusters so easy, but the recent update broke it and with no way to downgrade this might be slowing a lot of people down.

**Comment by aumungray** [comment]
Yes shifting back to 1.85.2 (VScode) and 0.108 of remote-ssh solved the issue.

**Comment by MattiaZaghi** [comment]
> Shifting back to 1.85.2 (VScode) and 0.108 of remote-ssh worked for me.

Thank has worked also for me on mac. The issues started when I had to install version 1.86.0 of VS code

**Comment by vbelis** [comment]
Thanks! Downgrading also worked for me on mac.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/203375

**Comment by laiyf94** [comment]
A short answer from my experience, downgrading  to version 1.85.2 solves the issue.
