### ISSUE TITLE
[Remote-SSH Bug]: Linux setup script assumes redirection can overwrite existing files

### ISSUE THREAD

**Issue by eamathw** [microsoft/vscode-remote-release#9511]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### Expected Behavior

Connecting to a remote machine should not require the BASH "set -C" option to be set. If the users BASH profile contains "set -C" the setup script will not be able to overwrite existing files and fails.

### Steps To Reproduce

1. Add to your Bash profile on the remote server: set -C
2. Try to connect VSCode to remove server
3. In logs see:
[Trace  - 19:48:37.89] Server install command stderr:
bash: line 167: /staff/xxxx/.vscodium-server/.57dae766d7d9084be351c47b43b26bf64acc9312.token: cannot overwrite existing file
bash: line 170: /staff/xxxx/.vscodium-server/.57dae766d7d9084be351c47b43b26bf64acc9312.pid: cannot overwrite existing file

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[Info  - 19:48:34.239] Resolving ssh remote authority 'ssh-remote+login.x' (attemp #1)
[Trace  - 19:48:34.252] Identity keys:
/home/xxxx/.ssh/id_ed25519 ssh-ed25519 SHA256:ROA98yZ46OhFpHKyGLCsYQQYpQSLDYjSbOHtPlnE3qs=
xxxx@mathits-MacBook-Air.local ssh-rsa SHA256:PCSTb9l/6DhnmfkM+v6ONkfNqnvypHI+uzZ8IZ1kbng=
xxxx@krug ecdsa-sha2-nistp256 SHA256:fLA3GPcEfTe7vnem3iCh+OQE7uojYw3HDGuyyintjZk=
[Info  - 19:48:34.559] Trying no-auth authentication
[Info  - 19:48:34.665] Trying publickey authentication: /home/xxxx/.ssh/id_ed25519 ssh-ed25519 SHA256:ROA98yZ46OgFpHKyGLCsYQQYpQSLDYjSbOHtPlnE3qs=
[Trace  - 19:48:35.631] Server install command:

# Server installation script

TMP_DIR="${XDG_RUNTIME_DIR:-"/tmp"}"

DISTRO_VERSION="1.83.0"
DISTRO_COMMIT="57dae766d7d9084be351c47b43b26bf64acc9312"
DISTRO_QUALITY="stable"
DISTRO_VSCODIUM_RELEASE="23277"

SERVER_APP_NAME="codium-server"
SERVER_INITIAL_EXTENSIONS=""
SERVER_LISTEN_FLAG="--port=0"
SERVER_DATA_DIR="$HOME/.vscodium-server"
SERVER_DIR="$SERVER_DATA_DIR/bin/$DISTRO_COMMIT"
SERVER_SCRIPT="$SERVER_DIR/bin/$SERVER_APP_NAME"
SERVER_LOGFILE="$SERVER_DATA_DIR/.$DISTRO_COMMIT.log"
SERVER_PIDFILE="$SERVER_DATA_DIR/.$DISTRO_COMMIT.pid"
SERVER_TOKENFILE="$SERVER_DATA_DIR/.$DISTRO_COMMIT.token"
SERVER_ARCH=
SERVER_CONNECTION_TOKEN=
SERVER_DOWNLOAD_URL=

LISTENING_ON=
OS_RELEASE_ID=
ARCH=
PLATFORM=

# Mimic output from logs of remote-ssh extension
print_install_results_and_exit() {
    echo "581da0b6f09954a0558deedf: start"
    echo "exitCode==$1=="
    echo "listeningOn==$LISTENING_ON=="
    echo "connectionToken==$SERVER_CONNECTION_TOKEN=="
    echo "logFile==$SERVER_LOGFILE=="
    echo "osReleaseId==$OS_RELEASE_ID=="
    echo "arch==$ARCH=="
    echo "platform==$PLATFORM=="
    echo "tmpDir==$TMP_DIR=="
    
    echo "581da0b6f09954a0558deedf: end"
    exit 0
}

# Check if platform is supported
KERNEL="$(uname -s)"
case $KERNEL in
    Darwin)
        PLATFORM="darwin"
        ;;
    Linux)
        PLATFORM="linux"
        ;;
    FreeBSD)
        PLATFORM="freebsd"
        ;;
    DragonFly)
        PLATFORM="dragonfly"
        ;;
    *)
        echo "Error platform not supported: $KERNEL"
        print_install_results_and_exit 1
        ;;
esac

# Check machine architecture
ARCH="$(uname -m)"
case $ARCH in
    x86_64 | amd64)
        SERVER_ARCH="x64"
        ;;
    armv7l | armv8l)
        SERVER_ARCH="armhf"
        ;;
    arm64 | aarch64)
        SERVER_ARCH="arm64"
        ;;
    ppc64le)
        SERVER_ARCH="ppc64le"
        ;;
    *)
        echo "Error architecture not supported: $ARCH"
        print_install_results_and_exit 1
        ;;
esac

# https://www.freedesktop.org/software/systemd/man/os-release.html
OS_RELEASE_ID="$(grep -i '^ID=' /etc/os-release 2>/dev/null | sed 's/^ID=//gi' | sed 's/"//g')"
if [[ -z $OS_RELEASE_ID ]]; then
    OS_RELEASE_ID="$(grep -i '^ID=' /usr/lib/os-release 2>/dev/null | sed 's/^ID=//gi' | sed 's/"//g')"
    if [[ -z $OS_RELEASE_ID ]]; then
        OS_RELEASE_ID="unknown"
    fi
fi

# Create installation folder
if [[ ! -d $SERVER_DIR ]]; then
    mkdir -p $SERVER_DIR
    if (( $? > 0 )); then
        echo "Error creating server install directory"
        print_install_results_and_exit 1
    fi
fi

SERVER_DOWNLOAD_URL="$(echo "https://github.com/VSCodium/vscodium/releases/download/\${version}.\${release}/vscodium-reh-\${os}-\${arch}-\${version}.\${release}.tar.gz" | sed "s/\${quality}/$DISTRO_QUALITY/g" | sed "s/\${version}/$DISTRO_VERSION/g" | sed "s/\${commit}/$DISTRO_COMMIT/g" | sed "s/\${os}/$PLATFORM/g" | sed "s/\${arch}/$SERVER_ARCH/g" | sed "s/\${release}/$DISTRO_VSCODIUM_RELEASE/g")"

# Check if server script is already installed
if [[ ! -f $SERVER_SCRIPT ]]; then
    if [[ "$PLATFORM" != "darwin" ]] && [[ "$PLATFORM" != "linux" ]]; then
        echo "Error "$PLATFORM" needs manual installation of remote extension host"
        print_install_results_and_exit 1
    fi

    pushd $SERVER_DIR > /dev/null

    if [[ ! -z $(which wget) ]]; then
        wget --tries=3 --timeout=10 --continue --no-verbose -O vscode-server.tar.gz $SERVER_DOWNLOAD_URL
    elif [[ ! -z $(which curl) ]]; then
        curl --retry 3 --connect-timeout 10 --location --show-error --silent --output vscode-server.tar.gz $SERVER_DOWNLOAD_URL
    else
        echo "Error no tool to download server binary"
        print_install_results_and_exit 1
    fi

    if (( $? > 0 )); then
        echo "Error downloading server from $SERVER_DOWNLOAD_URL"
        print_install_results_and_exit 1
    fi

    tar -xf vscode-server.tar.gz --strip-components 1
    if (( $? > 0 )); then
        echo "Error while extracting server contents"
        print_install_results_and_exit 1
    fi

    if [[ ! -f $SERVER_SCRIPT ]]; then
        echo "Error server contents are corrupted"
        print_install_results_and_exit 1
    fi

    rm -f vscode-server.tar.gz

    popd > /dev/null
else
    echo "Server script already installed in $SERVER_SCRIPT"
fi

# Try to find if server is already running
if [[ -f $SERVER_PIDFILE ]]; then
    SERVER_PID="$(cat $SERVER_PIDFILE)"
    SERVER_RUNNING_PROCESS="$(ps -o pid,args -p $SERVER_PID | grep $SERVER_SCRIPT)"
else
    SERVER_RUNNING_PROCESS="$(ps -o pid,args -A | grep $SERVER_SCRIPT | grep -v grep)"
fi

if [[ -z $SERVER_RUNNING_PROCESS ]]; then
    if [[ -f $SERVER_LOGFILE ]]; then
        rm $SERVER_LOGFILE
    fi
    if [[ -f $SERVER_TOKENFILE ]]; then
        rm $SERVER_TOKENFILE
    fi

    touch $SERVER_TOKENFILE
    chmod 600 $SERVER_TOKENFILE
    SERVER_CONNECTION_TOKEN="84043254-4b7f-4394-9863-cf654302a8ff"
    echo $SERVER_CONNECTION_TOKEN > $SERVER_TOKENFILE

    $SERVER_SCRIPT --start-server --host=127.0.0.1 $SERVER_LISTEN_FLAG $SERVER_INITIAL_EXTENSIONS --connection-token-file $SERVER_TOKENFILE --telemetry-level off --enable-remote-auto-shutdown --accept-server-license-terms &> $SERVER_LOGFILE &
    echo $! > $SERVER_PIDFILE
else
    echo "Server script is already running $SERVER_SCRIPT"
fi

if [[ -f $SERVER_TOKENFILE ]]; then
    SERVER_CONNECTION_TOKEN="$(cat $SERVER_TOKENFILE)"
else
    echo "Error server token file not found $SERVER_TOKENFILE"
    print_install_results_and_exit 1
fi

if [[ -f $SERVER_LOGFILE ]]; then
    for i in {1..5}; do
        LISTENING_ON="$(cat $SERVER_LOGFILE | grep -E 'Extension host agent listening on .+' | sed 's/Extension host agent listening on //')"
        if [[ -n $LISTENING_ON ]]; then
            break
        fi
        sleep 0.5
    done

    if [[ -z $LISTENING_ON ]]; then
        echo "Error server did not start sucessfully"
        print_install_results_and_exit 1
    fi
else
    echo "Error server log file not found $SERVER_LOGFILE"
    print_install_results_and_exit 1
fi

# Finish server setup
print_install_results_and_exit 0

[Trace  - 19:48:37.89] Server install command stderr:
bash: line 167: /staff/xxxx/.vscodium-server/.57dae766d7d9084be351c47b43b26bf64acc9312.token: cannot overwrite existing file
bash: line 170: /staff/xxxx/.vscodium-server/.57dae766d7d9084be351c47b43b26bf64acc9312.pid: cannot overwrite existing file

[Trace  - 19:48:37.89] Server install command stdout:
Server script already installed in /staff/xxxx/.vscodium-server/bin/57dae766d7d9084be351c47b43b26bf64acc9312/bin/codium-server
581da0b6f09954a0558deedf: start
exitCode==0==
listeningOn==1131==
connectionToken====
logFile==/staff/xxxx/.vscodium-server/.57dae766d7d9084be351c47b43b26bf64acc9312.log==
osReleaseId==ubuntu==
arch==x86_64==
platform==linux==
tmpDir==/run/user/2185==
581da0b6f09954a0558deedf: end

[Trace  - 19:48:37.91] Creating forwarding server 37861(local) => 32945(socks) => 1131(remote)
[Error  - 19:48:37.92] Error resolving authority
Error: Illegal argument: connectionToken
	at v (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10:1417)
	at H (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:121:9613)
	at new j (/usr/share/codium/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:121:10011)
	at /home/xxxx/.vscode-oss/extensions/jeanp413.open-remote-ssh-0.0.45-universal/out/extension.js:1:405848
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

</p>
</details>

### Anything else?

The problem is solved by removing 'set -C' from the user's BASH profile. that allows these lines to function:
169: echo $SERVER_CONNECTION_TOKEN > $SERVER_TOKENFILE
170:  echo $! > $SERVER_PIDFILE

One solution would be to change the setup script to use ' >|' when redirecting output to a file  as per the BASH docs:

> [set] -C      If set, bash does not overwrite an existing file with the >, >&, and <> redirection operators.  This may be overridden when creating output files by using the redirection operator >| instead of >.

**Comment by roblourens** [comment]
It looks like you are using vscodium, but we only support the official vscode build and Remote-SSH extension. I believe this is already fixed with the official configuration.
