### ISSUE TITLE
Dev containers(0.338.1) wont start with latest vscode (v1.86.0) on MacOS

### ISSUE THREAD

**Issue by gannaramu** [microsoft/vscode-remote-release#9523]
- VSCode Version: v1.86.0
- Local OS Version: MacOS Sonoma 14.0 (23A344)
- Remote OS Version: 
- Remote Extension/Connection Type: Containers

- Logs:
```
40 ms] Dev Containers 0.338.1 in VS Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937).
[40 ms] Start: Resolving Remote
[43 ms] Setting up container for folder or workspace: /Users/ragannavarapu/trials/pm-charging
[43 ms] Context: desktop-linux
[44 ms] Start: Check Docker is running
[44 ms] Start: Run: docker version
[83 ms] Client: Docker Engine - Community
[83 ms]  Version:           20.10.12
 API version:       1.41
 Go version:        go1.17.5
 Git commit:        e91ed5707e
 Built:             Sun Dec 12 06:28:24 2021
 OS/Arch:           darwin/arm64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Desktop 4.27.1 (136059)
 Engine:
  Version:          25.0.2
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       fce6e0c
  Built:            Thu Feb  1 00:23:21 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
[85 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/ragannavarapu/trials/pm-charging --filter label=vsch.quality=stable
[113 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/ragannavarapu/trials/pm-charging --filter label=devcontainer.config_file=/Users/ragannavarapu/trials/pm-charging/.devcontainer/devcontainer.json
[145 ms] Start: Run: docker inspect --type container 0dac80658d35
[173 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/ragannavarapu/trials/pm-charging
[196 ms] Start: Run: docker inspect --type container 0dac80658d35
[220 ms] Start: Run: docker exec -i -u root 0dac80658d357f0a2b98642329d068afb38760ac1d80ba7d6d29762ffd9bd6b6 /bin/sh -c echo "Container already running. Keep-alive process started." ; export VSCODE_REMOTE_CONTAINERS_SESSION=ad79786e-524a-4fe3-9694-bde3b12f08d31707371816989 ; /bin/sh
[221 ms] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/ragannavarapu/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /Users/ragannavarapu/trials/pm-charging --id-label devcontainer.local_folder=/Users/ragannavarapu/trials/pm-charging --id-label devcontainer.config_file=/Users/ragannavarapu/trials/pm-charging/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/ragannavarapu/trials/pm-charging/.devcontainer/devcontainer.json --mount-workspace-git-root
[297 ms] Container already running. Keep-alive process started.
[396 ms] @devcontainers/cli 0.56.0. Node.js v18.17.1. darwin 23.0.0 arm64.
[396 ms] Start: Run: git rev-parse --show-cdup
[417 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/ragannavarapu/trials/pm-charging --filter label=devcontainer.config_file=/Users/ragannavarapu/trials/pm-charging/.devcontainer/devcontainer.json
[445 ms] Start: Run: docker inspect --type container 0dac80658d35
[956 ms] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/ragannavarapu/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/ragannavarapu/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-ad79786e-524a-4fe3-9694-bde3b12f08d31707371816989 --workspace-folder /Users/ragannavarapu/trials/pm-charging --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/ragannavarapu/trials/pm-charging --id-label devcontainer.config_file=/Users/ragannavarapu/trials/pm-charging/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/ragannavarapu/trials/pm-charging/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[1147 ms] @devcontainers/cli 0.56.0. Node.js v18.17.1. darwin 23.0.0 arm64.
[1147 ms] Start: Run: docker buildx version
[1351 ms] github.com/docker/buildx v0.12.1-desktop.4 6996841df2f61988c2794d84d33205368f96c317
[1351 ms] 
[1351 ms] Start: Resolving Remote
[1352 ms] Start: Run: git rev-parse --show-cdup
[1464 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/ragannavarapu/trials/pm-charging --filter label=devcontainer.config_file=/Users/ragannavarapu/trials/pm-charging/.devcontainer/devcontainer.json
[1501 ms] Start: Run: docker inspect --type container 0dac80658d35
[1535 ms] Start: Inspecting container
[1536 ms] Start: Run: docker inspect --type container 0dac80658d357f0a2b98642329d068afb38760ac1d80ba7d6d29762ffd9bd6b6
[1569 ms] Start: Run in container: /bin/sh
[1570 ms] Start: Run in container: uname -m
[1678 ms] x86_64
[1678 ms] 
[1678 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[1700 ms] PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[1700 ms] 
[1700 ms] Start: Run in container:  (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true)
[1732 ms] Start: Run in container: test -f '/var/devcontainer/.patchEtcEnvironmentMarker'
[1735 ms] 
[1735 ms] 
[1735 ms] Start: Run in container: test -f '/var/devcontainer/.patchEtcProfileMarker'
[1737 ms] 
[1737 ms] 
[1741 ms] Start: Run: docker inspect --type container 0dac80658d357f0a2b98642329d068afb38760ac1d80ba7d6d29762ffd9bd6b6
[1768 ms] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/ragannavarapu/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /Users/ragannavarapu/trials/pm-charging --id-label devcontainer.local_folder=/Users/ragannavarapu/trials/pm-charging --id-label devcontainer.config_file=/Users/ragannavarapu/trials/pm-charging/.devcontainer/devcontainer.json --container-id 0dac80658d357f0a2b98642329d068afb38760ac1d80ba7d6d29762ffd9bd6b6 --log-level debug --log-format json --config /Users/ragannavarapu/trials/pm-charging/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root
[1946 ms] @devcontainers/cli 0.56.0. Node.js v18.17.1. darwin 23.0.0 arm64.
[1946 ms] Start: Run: git rev-parse --show-cdup
[1956 ms] Start: Run: docker inspect --type container 0dac80658d357f0a2b98642329d068afb38760ac1d80ba7d6d29762ffd9bd6b6
[1992 ms] Start: Inspecting container
[1992 ms] Start: Run: docker inspect --type container 0dac80658d357f0a2b98642329d068afb38760ac1d80ba7d6d29762ffd9bd6b6
[2027 ms] Start: Run in container: /bin/sh
[2028 ms] Start: Run in container: uname -m
[2130 ms] x86_64
[2130 ms] 
[2130 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[2154 ms] PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[2154 ms] 
[2155 ms] Start: Run in container:  (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true)
[2183 ms] Start: Setup shutdown monitor
[2183 ms] Forking shutdown monitor: /Users/ragannavarapu/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/shutdown/shutdownMonitorProcess /var/folders/22/cymc14hx2j1g7mht1k3sn_5h0000gq/T/vscode-remote-containers-e7114a1d-e099-4e6f-ace9-82ecfd22ed79.sock singleContainer Debug /Users/ragannavarapu/Library/Application Support/Code/logs/20240207T214540/window2/exthost/ms-vscode-remote.remote-containers 1707371817400
[2189 ms] Start: Run in container: test -d '/root/.vscode-server'
[2191 ms] 
[2192 ms] 
[2192 ms] Start: Run in container: test ! -f '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[2194 ms] 
[2194 ms] 
[2195 ms] Exit code 1
[2195 ms] Start: Run in container: cat /root/.vscode-server/data/Machine/settings.json
[2214 ms] 
[2215 ms] cat: /root/.vscode-server/data/Machine/settings.json: No such file or directory
[2215 ms] Exit code 1
[2215 ms] Start: Run in container: test -d '/root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937'
[2217 ms] 
[2218 ms] 
[2218 ms] Start: Run in container: test -x '/root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/bin/helpers/check-requirements.sh'
[2220 ms] 
[2220 ms] 
[2220 ms] Start: Run in container: '/root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/bin/helpers/check-requirements.sh'
[2694 ms] 
[2694 ms] 
[2694 ms] Start: Launching Dev Containers helper.
[2694 ms] ssh-agent: SSH_AUTH_SOCK in container (/tmp/vscode-ssh-auth-5ab84195-d5ae-4f9b-8b8c-244e62a7b055.sock) forwarded to local host (/private/tmp/com.apple.launchd.ZWydVyhyGk/Listeners).
[2694 ms] Start: Run in container: test -e /tmp/.X11-unix/X0
[2697 ms] 
[2697 ms] 
[2698 ms] Start: Run in container: test -e /tmp/.X11-unix/X1
[2700 ms] 
[2700 ms] 
[2700 ms] Start: Run in container: test -e /tmp/.X11-unix/X2
[2702 ms] 
[2702 ms] 
[2703 ms] Start: Run in container: test -e /tmp/.X11-unix/X3
[2705 ms] 
[2705 ms] 
[2705 ms] Start: Run in container: test -e /tmp/.X11-unix/X4
[2707 ms] 
[2707 ms] 
[2707 ms] Start: Run in container: test -e /tmp/.X11-unix/X5
[2709 ms] 
[2709 ms] 
[2709 ms] Start: Run in container: test -e /tmp/.X11-unix/X6
[2711 ms] 
[2711 ms] 
[2711 ms] Start: Run in container: test -e /tmp/.X11-unix/X7
[2713 ms] 
[2713 ms] 
[2713 ms] Start: Run in container: test -e /tmp/.X11-unix/X8
[2715 ms] 
[2715 ms] 
[2715 ms] Start: Run in container: test -e /tmp/.X11-unix/X9
[2717 ms] 
[2717 ms] 
[2717 ms] Exit code 1
[2717 ms] Start: Run in container: mkdir -p '/tmp/.X11-unix'
[2742 ms] 
[2742 ms] 
[2742 ms] X11 forwarding: DISPLAY in container (:9) forwarded to local host (/private/tmp/com.apple.launchd.Bd78AXL0BJ/org.xquartz:0).
[2742 ms] Start: Run in container: gpgconf --list-dir agent-socket
[2745 ms] 
[2745 ms] /bin/sh: 21: gpgconf: not found
[2746 ms] Exit code 127
[2746 ms] gpg-agent: No agent-socket found in container.
[2746 ms] Start: Run in container: command -v docker >/dev/null 2>&1
[2749 ms] 
[2749 ms] 
[2749 ms] Exit code 127
[2750 ms] Start: Run in container: /bin/sh
[2750 ms] userEnvProbe: loginInteractiveShell (default)
[2751 ms] Start: Run in container: test -f '/tmp/devcontainers-ad79786e-524a-4fe3-9694-bde3b12f08d31707371816989/env-loginInteractiveShell.json'
[2751 ms] Start: Run in container: echo ~
[2754 ms] 
[2754 ms] 
[2754 ms] Exit code 1
[2754 ms] userEnvProbe: not found in cache
[2755 ms] userEnvProbe shell: /bin/bash
[2756 ms] Start: Run in container: # Test for /root/.ssh/known_hosts and ssh
[2761 ms] ssh not found
[2761 ms] 
[2761 ms] Exit code 1
[2761 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --system --replace-all credential.helper '!f() { /root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/node /tmp/vscode-remote-containers-5ab84195-d5ae-4f9b-8b8c-244e62a7b055.js git-credential-helper $*; }; f' || true
[2764 ms] 
[2764 ms] 
[2764 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd || echo ; readlink /proc/$pid/ns/mnt || echo ; cat /proc/$pid/stat | tr "
[2841 ms] /root
[2841 ms] 
[2841 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-5ab84195-d5ae-4f9b-8b8c-244e62a7b055.js' >/tmp/vscode-remote-containers-5ab84195-d5ae-4f9b-8b8c-244e62a7b055.js
[2864 ms] 
[2864 ms] 
[2864 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-5ab84195-d5ae-4f9b-8b8c-244e62a7b055.js' >/tmp/vscode-remote-containers-server-5ab84195-d5ae-4f9b-8b8c-244e62a7b055.js_1707371820264
[2908 ms] 
[2908 ms] 
[3719 ms] Start: Run in container: cat '/root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/product.json'
[3734 ms] Container server: qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[3736 ms] Container server: Segmentation fault
[3739 ms] Start: Run in container: cat '/root/.vscode-server/data/Machine/.connection-token-05047486b6df5eb8d44b2ecd70ea3bdf775fd937' 2>/dev/null || (umask 377 && echo '05a5b72e-2015-4eaa-afd2-7d386638b767' >'/root/.vscode-server/data/Machine/.connection-token-05047486b6df5eb8d44b2ecd70ea3bdf775fd937-0643bdd2-d131-49d5-8d76-b63490e14f96' && mv -n '/root/.vscode-server/data/Machine/.connection-token-05047486b6df5eb8d44b2ecd70ea3bdf775fd937-0643bdd2-d131-49d5-8d76-b63490e14f96' '/root/.vscode-server/data/Machine/.connection-token-05047486b6df5eb8d44b2ecd70ea3bdf775fd937' && rm -f '/root/.vscode-server/data/Machine/.connection-token-05047486b6df5eb8d44b2ecd70ea3bdf775fd937-0643bdd2-d131-49d5-8d76-b63490e14f96' && cat '/root/.vscode-server/data/Machine/.connection-token-05047486b6df5eb8d44b2ecd70ea3bdf775fd937')
[3742 ms] Error reading shell environment.
[3742 ms] Error: unexpected end of parent stream
        at Si.destroy (/Users/ragannavarapu/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/extension/extension.js:27:26638)
        at Si.write (/Users/ragannavarapu/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/extension/extension.js:27:27379)
        at /Users/ragannavarapu/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/extension/extension.js:27:29482
        at /Users/ragannavarapu/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/extension/extension.js:27:14866
        at /Users/ragannavarapu/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/extension/extension.js:27:17539
        at Object.cb (/Users/ragannavarapu/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/extension/extension.js:27:23957)
        at l (/Users/ragannavarapu/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/extension/extension.js:27:22183)
        at /Users/ragannavarapu/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/extension/extension.js:27:22330
        at s (/Users/ragannavarapu/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/extension/extension.js:30:5371)
        at Socket.<anonymous> (/Users/ragannavarapu/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/extension/extension.js:30:5541)
        at Socket.emit (node:events:526:35)
        at endReadableNT (node:internal/streams/readable:1359:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[3743 ms] Container server terminated (code: 139, signal: null).
[3760 ms] d14e267f-004f-4aba-9b49-48983639a77c
[3760 ms] 
[3760 ms] Start: Run in container: mkdir -p '/tmp/devcontainers-ad79786e-524a-4fe3-9694-bde3b12f08d31707371816989' && cat > '/tmp/devcontainers-ad79786e-524a-4fe3-9694-bde3b12f08d31707371816989/env-loginInteractiveShell.json' << 'envJSON'
[3761 ms] Start: Starting VS Code Server
[3761 ms] Start: Preparing Extensions
[3802 ms] 
[3802 ms] 
[3802 ms] Start: Run in container: test ! -f '/root/.vscode-server/data/Machine/.installExtensionsMarker' && set -o noclobber && mkdir -p '/root/.vscode-server/data/Machine' && { > '/root/.vscode-server/data/Machine/.installExtensionsMarker' ; } 2> /dev/null
[3804 ms] 
[3805 ms] 
[3805 ms] Exit code 1
[3805 ms] Extensions cache, install extensions: None
[3805 ms] Start: Run in container: test -d /root/.vscode-server/extensionsCache && ls /root/.vscode-server/extensionsCache || true
[3808 ms] 
[3808 ms] 
[3809 ms] Extensions cache, copy to remote: None
[3809 ms] Optimizing extensions for quality: stable
[3809 ms] Start: Run in container: /root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/bin/code-server --log debug --force-disable-user-env --server-data-dir /root/.vscode-server --use-host-proxy --telemetry-level off --accept-server-license-terms --host 127.0.0.1 --port 0 --connection-token-file /root/.vscode-server/data/Machine/.connection-token-05047486b6df5eb8d44b2ecd70ea3bdf775fd937 --extensions-download-dir /root/.vscode-server/extensionsCache --start-server --disable-websocket-compression --skip-requirements-check
[4484 ms] *
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
[4521 ms] Server bound to 127.0.0.1:43019 (IPv4)
Extension host agent listening on 43019

[4522 ms] Start: Run in container: echo 43019 >'/root/.vscode-server/data/Machine/.devport-05047486b6df5eb8d44b2ecd70ea3bdf775fd937'
[4525 ms] 
[4525 ms] 
[4525 ms] Port forwarding for container port 43019 starts listening on local port.
[4526 ms] Port forwarding local port 43019 to container port 43019
[4527 ms] Start: Run in container: # Test for /root/.gitconfig and git
[4532 ms] git not found
[4532 ms] 
[4532 ms] Exit code 1
[4532 ms] Start: Run in container: # Cleaning up git config
[4539 ms] Port forwarding connection from 63738 > 43019 > 43019 in the container.
[4539 ms] Start: Run in container: /root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/node -e 
[4546 ms] 
[4546 ms] /bin/sh: 51: git: not found
/bin/sh: 51: git: not found
/bin/sh: 51: git: not found
/bin/sh: 56: git: not found
[4546 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --global --replace-all credential.helper '!f() { /root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/node /tmp/vscode-remote-containers-5ab84195-d5ae-4f9b-8b8c-244e62a7b055.js git-credential-helper $*; }; f' || true
[4549 ms] 
[4549 ms] 
[5077 ms] Port forwarding 63738 > 43019 > 43019 stderr: Connection established
[5646 ms] [05:57:03] 




[5830 ms] [05:57:03] Extension host agent started.
[5848 ms] Port forwarding connection from 63743 > 43019 > 43019 in the container.
[5848 ms] Start: Run in container: /root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/node -e 
[6020 ms] [05:57:03] [127.0.0.1][22601948][ExtensionHostConnection] New connection established.
[6048 ms] [05:57:03] No uninstalled extensions found.
[6087 ms] [05:57:03] [127.0.0.1][22601948][ExtensionHostConnection] <6424> Launched Extension Host Process.
[6480 ms] Port forwarding 63743 > 43019 > 43019 stderr: Connection established
[6520 ms] [05:57:03] [127.0.0.1][70dc7324][ManagementConnection] New connection established.
[6580 ms] [05:57:03] Log level changed to info
[7834 ms] Port forwarding 63738 > 43019 > 43019 stderr: Remote close
[7836 ms] Port forwarding 63743 > 43019 > 43019 stderr: Remote close
[9831 ms] Port forwarding 63743 > 43019 > 43019 terminated with code 0 and signal null.
[9832 ms] Port forwarding 63738 > 43019 > 43019 terminated with code 0 and signal null.
[9832 ms] Port forwarding 63743 > 43019 > 43019: Local close
[9833 ms] Start: Reconnection attempt 1
[9833 ms] Start: Run: docker inspect --type container 0dac80658d357f0a2b98642329d068afb38760ac1d80ba7d6d29762ffd9bd6b6
[9835 ms] Port forwarding 63738 > 43019 > 43019: Local close
[9864 ms] Port forwarding connection from 63752 > 43019 > 43019 in the container.
[9865 ms] Start: Run in container: /root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/node -e 
[10426 ms] Port forwarding 63752 > 43019 > 43019 stderr: Error: connect ECONNREFUSED 127.0.0.1:43019
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
[10433 ms] Port forwarding 63752 > 43019 > 43019 stderr: Remote close with error
[10454 ms] Port forwarding 63752 > 43019 > 43019 terminated with code 1 and signal null.
[10454 ms] Port forwarding 63752 > 43019 > 43019: Local close
[10466 ms] Port forwarding connection from 63753 > 43019 > 43019 in the container.
[10466 ms] Start: Run in container: /root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/node -e 
[11002 ms] Port forwarding 63753 > 43019 > 43019 stderr: Error: connect ECONNREFUSED 127.0.0.1:43019
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
[11009 ms] Port forwarding 63753 > 43019 > 43019 stderr: Remote close with error
[11028 ms] Port forwarding 63753 > 43019 > 43019 terminated with code 1 and signal null.
[11028 ms] Port forwarding 63753 > 43019 > 43019: Local close
[13870 ms] Extensions cache, remote removals: None
[15457 ms] Start: Reconnection attempt 2
[15457 ms] Start: Run: docker inspect --type container 0dac80658d357f0a2b98642329d068afb38760ac1d80ba7d6d29762ffd9bd6b6
[15511 ms] Port forwarding connection from 63758 > 43019 > 43019 in the container.
[15511 ms] Start: Run in container: /root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/node -e 
[16068 ms] Port forwarding 63758 > 43019 > 43019 stderr: Error: connect ECONNREFUSED 127.0.0.1:43019
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
[16075 ms] Port forwarding 63758 > 43019 > 43019 stderr: Remote close with error
[16093 ms] Port forwarding 63758 > 43019 > 43019 terminated with code 1 and signal null.
[16093 ms] Port forwarding 63758 > 43019 > 43019: Local close
[16105 ms] Port forwarding connection from 63759 > 43019 > 43019 in the container.
[16105 ms] Start: Run in container: /root/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/node -e 
[16650 ms] Port forwarding 63759 > 43019 > 43019 stderr: Error: connect ECONNREFUSED 127.0.0.1:43019
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
[16657 ms] Port forwarding 63759 > 43019 > 43019 stderr: Remote close with error
[16675 ms] Port forwarding 63759 > 43019 > 43019 terminated with code 1 and signal null.
[16675 ms] Port forwarding 63759 > 43019 > 43019: Local close

```
Steps to Reproduce:

1.
2.

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by tomothy83** [comment]
This might be a different problem, but I got a error with VSCode 1.86.1 and Docker Desktop 4.27.1 on Windows 10.
When I updated Docker Desktop to 4.27.2 the error disappeared.

```
[2024-02-09T07:11:00.524Z] Client:
 Cloud integration: v1.0.35+desktop.10
 Version:           25.0.2
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Thu Feb  1 00:22:06 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop
 Engine:
  Version:          25.0.2
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       fce6e0c
  Built:            Thu Feb  1 00:23:17 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
....
[2024-02-09T07:11:07.379Z] Error: Command failed: docker-compose --project-name grit3_devcontainer -f /home/user**/repos/grit/grit3/.devcontainer/docker-compose.yml -f /tmp/devcontainercli-user**/docker-compose/docker-compose.devcontainer.build-1707462664647.yml -f /tmp/devcontainercli-user**/docker-compose/docker-compose.devcontainer.containerFeatures-1707462667290.yml up -d
[2024-02-09T07:11:07.379Z]     at L$ (/home/user**/.vscode-remote-containers/dist/dev-containers-cli-0.338.1/dist/spec-node/devContainersSpecCLI.js:429:3374)
[2024-02-09T07:11:07.379Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-02-09T07:11:07.379Z]     at async N$ (/home/user**/.vscode-remote-containers/dist/dev-containers-cli-0.338.1/dist/spec-node/devContainersSpecCLI.js:409:3165)
[2024-02-09T07:11:07.379Z]     at async tAA (/home/user**/.vscode-remote-containers/dist/dev-containers-cli-0.338.1/dist/spec-node/devContainersSpecCLI.js:481:3833)
[2024-02-09T07:11:07.379Z]     at async CC (/home/user**/.vscode-remote-containers/dist/dev-containers-cli-0.338.1/dist/spec-node/devContainersSpecCLI.js:481:4775)
[2024-02-09T07:11:07.379Z]     at async NeA (/home/user**/.vscode-remote-containers/dist/dev-containers-cli-0.338.1/dist/spec-node/devContainersSpecCLI.js:614:11107)
[2024-02-09T07:11:07.379Z]     at async MeA (/home/user**/.vscode-remote-containers/dist/dev-containers-cli-0.338.1/dist/spec-node/devContainersSpecCLI.js:614:10848)
[2024-02-09T07:11:07.382Z] Stop (6491 ms): Run in Host: /home/user**/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node /home/user**/.vscode-remote-containers/dist/dev-containers-cli-0.338.1/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-48f2c2e1-a3c2-4005-b24d-5b17ec20612e1707462659326 --workspace-folder /home/user**/repos/grit/grit3 --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\Ubuntu-20.04\home\user**\repos\grit\grit3 --id-label devcontainer.config_file=/home/user**/repos/grit/grit3/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/user**/repos/grit/grit3/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/mnt/wslg/runtime-dir/wayland-0,target=/tmp/vscode-wayland-f377d859-f6a0-4112-a6ab-46b48dce79f7.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-02-09T07:11:07.382Z] Exit code 1
[2024-02-09T07:11:07.385Z] Command failed: /home/user**/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node /home/user**/.vscode-remote-containers/dist/dev-containers-cli-0.338.1/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-48f2c2e1-a3c2-4005-b24d-5b17ec20612e1707462659326 --workspace-folder /home/user**/repos/grit/grit3 --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\Ubuntu-20.04\home\user**\repos\grit\grit3 --id-label devcontainer.config_file=/home/user**/repos/grit/grit3/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/user**/repos/grit/grit3/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/mnt/wslg/runtime-dir/wayland-0,target=/tmp/vscode-wayland-f377d859-f6a0-4112-a6ab-46b48dce79f7.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-02-09T07:11:07.385Z] Exit code 1
```

**Comment by jmls** [comment]
having the same problem with 1.86.1 on ubuntu

![image](https://github.com/microsoft/vscode-remote-release/assets/929523/1664a46a-1c8a-499b-93a7-c3c35cb8e438)
![image](https://github.com/microsoft/vscode-remote-release/assets/929523/9955f282-63e2-4067-b918-71712ced042b)
