### ISSUE TITLE
Reopen in Container fails

### ISSUE THREAD

**Issue by MKT-Paddy** [microsoft/vscode-remote-release#9531]
- Versions:
  VSCode Version: 1.86.1
  WSL version: 2.0.14.0
  Kernel version: 5.15.133.1-1
  WSLg version: 1.0.59
  MSRDC version: 1.2.4677
  Direct3D version: 1.611.1-81528511
  DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
  Windows version: 10.0.19045.3930
  Ubuntu 22.04.2 LTS
  Docker Desktop 4.27.2
  Dev-Containers v0.341.0 (same problem with v0.338.1)

- Remote Extension/Connection Type: Containers (WSL)

- Steps to Reproduce:
1. Open folder in WSL window
  containing .devcontainer directory with Dockerfile and devcontainer.json
3. Dev Containers: Reopen in Container
Popup shown:
Command 'Dev Containers: Reopen in Container' resulted in an error - stream is closed
same result for rebuild and reopen

- Logs:
```
[25 ms] Dev Containers 0.341.0 in VS Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533).
[25 ms] Start: Run: wsl -d ubuntu -e /bin/sh -c cd '/home/blr-0101' && /bin/sh
[43 ms] Start: Run in host: id -un
[743 ms] paddy
[743 ms] 
[744 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'paddy' || grep -E '^paddy|^[^:]*:[^:]*:paddy:' /etc/passwd || true)
[748 ms] Start: Run in host: echo ~
[754 ms] /home/paddy
[755 ms] 
[755 ms] Start: Run in host: test -x '/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node'
[757 ms] 
[757 ms] 
[758 ms] Start: Run in host: test -f '/home/paddy/.vscode-remote-containers/dist/vscode-remote-containers-server-0.341.0.js'
[759 ms] 
[760 ms] 
[761 ms] userEnvProbe: loginInteractiveShell (default)
[761 ms] userEnvProbe: not found in cache
[761 ms] userEnvProbe shell: /bin/bash
[763 ms] Host server: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
Segmentation fault
[895 ms] Error reading shell environment.
[895 ms] Error: stream ended with:0 but wanted:9
        at l (c:\Users\PatrickB\.vscode\extensions\ms-vscode-remote.remote-containers-0.341.0\dist\extension\extension.js:27:22149)
        at c:\Users\PatrickB\.vscode\extensions\ms-vscode-remote.remote-containers-0.341.0\dist\extension\extension.js:27:22330
        at s (c:\Users\PatrickB\.vscode\extensions\ms-vscode-remote.remote-containers-0.341.0\dist\extension\extension.js:30:5371)
        at Socket.<anonymous> (c:\Users\PatrickB\.vscode\extensions\ms-vscode-remote.remote-containers-0.341.0\dist\extension\extension.js:30:5541)
        at Socket.emit (node:events:526:35)
        at endReadableNT (node:internal/streams/readable:1359:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[898 ms] Host server terminated (code: 139, signal: null).
[34672 ms] Start: Run: wsl -d ubuntu -e /bin/sh -c cd '/home/blr-0101' && /bin/sh
[34698 ms] Start: Run in host: id -un
[35274 ms] paddy
[35275 ms] 
[35275 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'paddy' || grep -E '^paddy|^[^:]*:[^:]*:paddy:' /etc/passwd || true)
[35277 ms] Start: Run in host: echo ~
[35278 ms] /home/paddy
[35278 ms] 
[35279 ms] Start: Run in host: test -x '/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node'
[35279 ms] 
[35280 ms] 
[35280 ms] Start: Run in host: test -f '/home/paddy/.vscode-remote-containers/dist/vscode-remote-containers-server-0.341.0.js'
[35281 ms] 
[35281 ms] 
[35282 ms] userEnvProbe: loginInteractiveShell (default)
[35282 ms] userEnvProbe: not found in cache
[35283 ms] userEnvProbe shell: /bin/bash
[35283 ms] Host server: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
/home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node: no version information available (required by /home/paddy/.vscode-remote-containers/bin/31c37ee8f63491495ac49e43b8544550fbae4533/node)
Segmentation fault
[35417 ms] Error reading shell environment.
[35417 ms] Error: stream ended with:0 but wanted:9
        at l (c:\Users\PatrickB\.vscode\extensions\ms-vscode-remote.remote-containers-0.341.0\dist\extension\extension.js:27:22149)
        at c:\Users\PatrickB\.vscode\extensions\ms-vscode-remote.remote-containers-0.341.0\dist\extension\extension.js:27:22330
        at s (c:\Users\PatrickB\.vscode\extensions\ms-vscode-remote.remote-containers-0.341.0\dist\extension\extension.js:30:5371)
        at Socket.<anonymous> (c:\Users\PatrickB\.vscode\extensions\ms-vscode-remote.remote-containers-0.341.0\dist\extension\extension.js:30:5541)
        at Socket.emit (node:events:526:35)
        at endReadableNT (node:internal/streams/readable:1359:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[35420 ms] Host server terminated (code: 139, signal: null).
```

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
Which version of Ubuntu are you using? (Check `/etc/os-release` in WSL.)

**Comment by MKT-Paddy** [comment]
'''
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
'''

**Comment by chrmarti** [comment]
@deepak1556 Any idea what this could mean? A quick search on the web suggests that this might be about shared library versions.

**Comment by deepak1556** [comment]
@MKT-Paddy can you share the devcontainer configuration that demonstrates the issue.

**Comment by MKT-Paddy** [comment]
Example here:
https://github.com/MKTestSystems/devcontainer

.devcontainer/devcontainer.json:
```
{
	"name": "Existing Dockerfile",
	"build": {
		"context": "..",
		"dockerfile": "Dockerfile"
	},
	"customizations": {
		"vscode": {
			"settings": {},
			"extensions": [
				"ms-vscode.cpptools-extension-pack",
				"mcu-debug.debug-tracker-vscode",
				"marus25.cortex-debug",
				"ms-vscode.cmake-tools",
				"ms-python.pylint",
				"ms-python.python",
				"ms-python.autopep8"
			]
		}
	}
}
```

**Comment by MKT-Paddy** [comment]
Clean reinstall of VS Code and WSL has sorted it.
