### ISSUE TITLE
Remote-SSH: bind [::ffff:127.0.0.1]:58206: Can't assign requested address [ipv6]

### ISSUE THREAD

**Issue by arikon** [microsoft/vscode-remote-release#9551]
Type: <b>Bug</b>

Just open Remote-SSH connection to the server, which is Ubuntu 22.04.

---

UPD. Found that problem is related to `AddressFamily inet6` in my `~/.ssh/config`

```
Host *.yandex.net
  AddressFamily inet6
```

If I disable it, all starts to work fine. Looks like a bug somewhere in extension or VSCode.

---

Log:

```
[20:59:44.806] Log Level: 2
[20:59:44.810] SSH Resolver called for "ssh-remote+smart-home-iot.klg.yp-c.yandex.net", attempt 1
[20:59:44.811] "remote.SSH.useLocalServer": false
[20:59:44.811] "remote.SSH.useExecServer": false
[20:59:44.811] "remote.SSH.showLoginTerminal": false
[20:59:44.811] "remote.SSH.remotePlatform": {"smart-home-iot.klg.yp-c.yandex.net":"linux"}
[20:59:44.811] "remote.SSH.path": undefined
[20:59:44.811] "remote.SSH.configFile": undefined
[20:59:44.811] "remote.SSH.useFlock": true
[20:59:44.811] "remote.SSH.lockfilesInTmp": false
[20:59:44.811] "remote.SSH.localServerDownload": auto
[20:59:44.811] "remote.SSH.remoteServerListenOnSocket": true
[20:59:44.811] "remote.SSH.showLoginTerminal": false
[20:59:44.811] "remote.SSH.defaultExtensions": []
[20:59:44.811] "remote.SSH.loglevel": 2
[20:59:44.811] "remote.SSH.enableDynamicForwarding": true
[20:59:44.811] "remote.SSH.enableRemoteCommand": false
[20:59:44.812] "remote.SSH.serverPickPortsFromRange": {}
[20:59:44.812] "remote.SSH.serverInstallPath": {}
[20:59:44.814] VS Code version: 1.86.1
[20:59:44.814] Remote-SSH version: remote-ssh@0.108.0
[20:59:44.814] darwin arm64
[20:59:44.816] SSH Resolver called for host: smart-home-iot.klg.yp-c.yandex.net
[20:59:44.816] Setting up SSH remote "smart-home-iot.klg.yp-c.yandex.net"
[20:59:44.818] Using commit id "31c37ee8f63491495ac49e43b8544550fbae4533" and quality "stable" for server
[20:59:44.819] Install and start server if needed
[20:59:44.821] PATH: /Users/arikon/.nvm/versions/node/v18.18.2/bin:/Users/arikon/yandex-cloud/bin:/Users/arikon/projects/sdk/android/tools:/Users/arikon/projects/sdk/android/platform-tools:/Users/arikon/go/bin:/Users/arikon/Library/Application Support/JetBrains/Toolbox/scripts:/Users/arikon/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/munki
[20:59:44.821] Checking ssh with "ssh -V"
[20:59:44.826] > OpenSSH_9.4p1, LibreSSL 3.3.6

[20:59:44.828] Running script with connection command: ssh -T -D 62320 -o ConnectTimeout=15 'smart-home-iot.klg.yp-c.yandex.net' bash
[20:59:46.109] > b5d4294b01b0: running
[20:59:46.110] Got some output, clearing connection timeout
[20:59:46.174] > Acquiring lock on /home/arikon/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/vscode-remote-lock.arikon.31c37ee8f63491495ac49e43b8544550fbae4533
> Found existing installation at /home/arikon/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533...
> Checking /home/arikon/.vscode-server/.31c37ee8f63491495ac49e43b8544550fbae4533.log and /home/arikon/.vscode-server/.31c37ee8f63491495ac49e43b8544550fbae4533.pid for a running server
> Looking for server with pid: 437611
[20:59:46.238] > Starting VS Code Server... "/home/arikon/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/bin/code-server" --start-server --host=127.0.0.1 --accept-server-license-terms --enable-remote-auto-shutdown  --telemetry-level all --socket-path=/run/user/21783/vscode-ssh-remote-server-sock-1707854385  &> "/home/arikon/.vscode-server/.31c37ee8f63491495ac49e43b8544550fbae4533.log" < /dev/null
> The VS Code Server log file is /home/arikon/.vscode-server/.31c37ee8f63491495ac49e43b8544550fbae4533.log
> printenv:
>     SHELL=/bin/bash
>     SSH_AUTH_SOCK=/tmp/ssh-XXXXAKmHWh/agent.440815
>     PWD=/home/arikon
>     LOGNAME=arikon
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/home/arikon
>     LANG=en_US.UTF-8
>     TMPDIR=/var/tmp
>     VSCODE_AGENT_FOLDER=/home/arikon/.vscode-server
>     SSH_CONNECTION=2a02:6b8:b081:1212::1:8 62321 2a02:6b8:c42:29a9:0:4875:4667:0 22
>     XDG_SESSION_CLASS=user
>     USER=arikon
>     SHLVL=0
>     XDG_SESSION_ID=2267
>     XDG_RUNTIME_DIR=/run/user/21783
>     SSH_CLIENT=2a02:6b8:b081:1212::1:8 62321 22
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/21783/bus
>     _=/usr/bin/printenv
> Removing old logfile at /home/arikon/.vscode-server/.31c37ee8f63491495ac49e43b8544550fbae4533.log
> Spawned remote server: 440862
> Waiting for server log...
[20:59:46.290] > Waiting for server log...
[20:59:46.315] > Waiting for server log...
[20:59:46.351] >  
> *
> * Visual Studio Code Server
> *
> * By using the software, you agree to
> * the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
> * the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
> *
>  
> b5d4294b01b0: start
> SSH_AUTH_SOCK==/tmp/ssh-XXXXAKmHWh/agent.440815==
> DISPLAY====
> webUiAccessToken====
> listeningOn==/run/user/21783/vscode-ssh-remote-server-sock-1707854385==
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/21783==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> extInstallTime====
> serverStartTime==110==
> connectionToken==a1aaaaaa-a1a1-1a1a-aaa1-1a111a11a1aa==
> b5d4294b01b0: end
[20:59:46.352] Received install output: 
SSH_AUTH_SOCK==/tmp/ssh-XXXXAKmHWh/agent.440815==
DISPLAY====
webUiAccessToken====
listeningOn==/run/user/21783/vscode-ssh-remote-server-sock-1707854385==
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/21783==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
extInstallTime====
serverStartTime==110==
connectionToken==a1aaaaaa-a1a1-1a1a-aaa1-1a111a11a1aa==

[20:59:46.352] Remote server is listening on socket /run/user/21783/vscode-ssh-remote-server-sock-1707854385
[20:59:46.353] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"socketPath":"/run/user/21783/vscode-ssh-remote-server-sock-1707854385"},"osReleaseId":"ubuntu","arch":"x86_64","webUiAccessToken":"","sshAuthSock":"/tmp/ssh-XXXXAKmHWh/agent.440815","display":"","tmpDir":"/run/user/21783","platform":"linux","connectionToken":"a1aaaaaa-a1a1-1a1a-aaa1-1a111a11a1aa"},"serverStartTime":110,"installUnpackCode":""}
[20:59:46.357] Running script with connection command: ssh -T -L 127.0.0.1:62322:/run/user/21783/vscode-ssh-remote-server-sock-1707854385 -o ConnectTimeout=15 'smart-home-iot.klg.yp-c.yandex.net' bash
[20:59:46.357] Spawning tunnel with: ssh -T -L 127.0.0.1:62322:/run/user/21783/vscode-ssh-remote-server-sock-1707854385 -o ConnectTimeout=15 'smart-home-iot.klg.yp-c.yandex.net' bash << 'EOSSH'
echo $SSH_AUTH_SOCK && echo -e 'Connected to SSH Host - Please do not close this terminal' && while true; do sleep 180; echo -n ' '; done
EOSSH
[20:59:47.382] > bind [::ffff:127.0.0.1]:62322: Can't assign requested address
> channel_setup_fwd_listener_tcpip: cannot listen to port: 62322
> Could not request local forwarding.
[20:59:47.710] > /tmp/ssh-XXXX0OfE79/agent.440981
> Connected to SSH Host - Please do not close this terminal
[20:59:47.710] Spawned SSH tunnel between local port 62322 and remote target socket /run/user/21783/vscode-ssh-remote-server-sock-1707854385
[20:59:47.711] Waiting for ssh tunnel to be ready
[20:59:58.369] Error establishing tunnel (Max wait time exhausted).
[20:59:58.373] Resolver error: Error: Error establishing tunnel (Max wait time exhausted).
	at t.createTunnel (/Users/arikon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.108.0/out/extension.js:2:577317)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async k (/Users/arikon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.108.0/out/extension.js:2:537989)
	at async t.resolve (/Users/arikon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.108.0/out/extension.js:2:541635)
	at async /Users/arikon/.vscode/extensions/ms-vscode-remote.remote-ssh-0.108.0/out/extension.js:2:807794
[20:59:58.379] ------




[20:59:58.596] Opening exec server for ssh-remote+smart-home-iot.klg.yp-c.yandex.net
[20:59:58.596] Opening exec server for ssh-remote+smart-home-iot.klg.yp-c.yandex.net
[20:59:58.603] Initizing new exec server for ssh-remote+smart-home-iot.klg.yp-c.yandex.net
[20:59:58.615] Using commit id "31c37ee8f63491495ac49e43b8544550fbae4533" and quality "stable" for server
[20:59:58.616] Install and start server if needed
[20:59:58.619] Running script with connection command: ssh -T -D 62428 -o ConnectTimeout=15 'smart-home-iot.klg.yp-c.yandex.net' bash
[20:59:59.894] > 14396437a31a: running
[20:59:59.895] Got some output, clearing connection timeout
[20:59:59.913] > Found existing installation at /home/arikon/.vscode-server...
> Starting VS Code CLI... "/home/arikon/.vscode-server/code-31c37ee8f63491495ac49e43b8544550fbae4533" command-shell --cli-data-dir "/home/arikon/.vscode-server/cli" --on-port --parent-process-id 441050 &> "/home/arikon/.vscode-server/.cli.31c37ee8f63491495ac49e43b8544550fbae4533.log" < /dev/null
> printenv:
>     SHELL=/bin/bash
>     SSH_AUTH_SOCK=/tmp/ssh-XXXXzUeN68/agent.441049
>     PWD=/home/arikon
>     LOGNAME=arikon
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/home/arikon
>     LANG=en_US.UTF-8
>     TMPDIR=/var/tmp
>     VSCODE_AGENT_FOLDER=/home/arikon/.vscode-server
>     SSH_CONNECTION=2a02:6b8:b081:1212::1:8 62429 2a02:6b8:c42:29a9:0:4875:4667:0 22
>     XDG_SESSION_CLASS=user
>     USER=arikon
>     SHLVL=0
>     XDG_SESSION_ID=2269
>     XDG_RUNTIME_DIR=/run/user/21783
>     SSH_CLIENT=2a02:6b8:b081:1212::1:8 62429 22
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/21783/bus
>     _=/usr/bin/printenv
> Removing old logfile at /home/arikon/.vscode-server/.cli.31c37ee8f63491495ac49e43b8544550fbae4533.log
> Spawned remote CLI: 441070
[20:59:59.966] > Waiting for server log...
[21:00:00.004] > 14396437a31a: start
> SSH_AUTH_SOCK==/tmp/ssh-XXXXzUeN68/agent.441049==
> DISPLAY====
> listeningOn==127.0.0.1:44991==
> osReleaseId==ubuntu==
> arch==x86_64==
> vscodeArch==x64==
> bitness==64==
> tmpDir==/run/user/21783==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> serverStartTime==87==
> execServerToken==a11a1111-aa11-1111-a111-1a111aa1111a==
> 14396437a31a: end
[21:00:00.004] Received install output: 
SSH_AUTH_SOCK==/tmp/ssh-XXXXzUeN68/agent.441049==
DISPLAY====
listeningOn==127.0.0.1:44991==
osReleaseId==ubuntu==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/21783==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
serverStartTime==87==
execServerToken==a11a1111-aa11-1111-a111-1a111aa1111a==

[21:00:00.004] Remote server is listening on port 44991
[21:00:00.004] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":44991},"osReleaseId":"ubuntu","arch":"x86_64","sshAuthSock":"/tmp/ssh-XXXXzUeN68/agent.441049","display":"","tmpDir":"/run/user/21783","platform":"linux","execServerToken":"a11a1111-aa11-1111-a111-1a111aa1111a"},"serverStartTime":87,"installUnpackCode":""}
[21:00:00.007] Starting forwarding server. local port 62434 -> socksPort 62428 -> remotePort 44991
[21:00:00.007] Forwarding server listening on port 62434
[21:00:00.007] Waiting for ssh tunnel to be ready
[21:00:00.008] Tunneled port 44991 to local port 62434
[21:00:00.008] Resolved "ssh-remote+smart-home-iot.klg.yp-c.yandex.net" to "port 62434"
[21:00:00.008] Resolving exec server at port 62434
[21:00:00.009] [Forwarding server port 62434] Got connection 0
[21:00:00.009] [Forwarding server port 62434] Got connection 1
[21:00:00.011] Failed to set up socket for dynamic port forward to remote port 44991: connect ECONNREFUSED 127.0.0.1:62428. TCP port forwarding may be disabled, or the remote server may have crashed. See the VS Code Server log above for details.
[21:00:00.011] Failed to set up socket for dynamic port forward to remote port 44991: connect ECONNREFUSED 127.0.0.1:62428. TCP port forwarding may be disabled, or the remote server may have crashed. See the VS Code Server log above for details.
```

Extension version: 0.108.0
VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:57.920Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 5|
|Memory (System)|32.00GB (0.64GB free)|
|Process Argv|--crash-reporter-id 4bd92934-eec5-4aab-8cac-517552c63854|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
e3gdj431:30958358
ccp1r3:30958155

```

</details>

**Comment by joshspicer** [comment]
Perhaps our free port detection code here does not play nice with ipv6.

The error message indicates that the local port 62322 is not available for forwarding. One thing you can try is checking if the port is already in use (from this example)

```
lsof -i :62322
```
If the port is in use, you can either stop the process using it or choose a different port for forwarding.

Also, you can specify a different local port rangeAdd the following setting to your settings.json file with whatever range you see is not in use.

"remote.SSH.preferredLocalPortRange": "60000-61000"

If that helps, it's a good hint that we are not properly auto-detecting this situation as we would with an ipv4 address.

**Comment by joshspicer** [comment]
Also, does enabling the `useExecServer` setting help?

**Comment by totoCZ** [comment]
```
[22:06:28.491] > bind [::ffff:127.0.0.1]:53013: Can't assign requested address
> channel_setup_fwd_listener_tcpip: cannot listen to port: 53013
> Could not request local forwarding.
[22:06:29.424] > /tmp/ssh-XXXXWK7RpT/agent.126062
```
exec server doesn't change anything. macOS 15.2 (24C101)

I removed AddressFamily and it works.

I think you have 127.0.0.1 hardcoded there or some issue like that.
