### ISSUE TITLE
Fails to create container

### ISSUE THREAD

**Issue by parsley72** [microsoft/vscode-remote-release#9566]
- VSCode Version: 1.86.2
- Local OS Version: Ubuntu 22.04.03 LTS
- Remote OS Version: Ubuntu 20.4
- Remote Extension/Connection Type: Containers

- Logs:
```
[2024-02-18T23:39:38.571Z] Dev Containers 0.338.1 in VS Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda).
[2024-02-18T23:39:38.571Z] Start: Resolving Remote
[2024-02-18T23:39:38.582Z] Setting up container for folder or workspace: /home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux
[2024-02-18T23:39:38.584Z] Start: Check Docker is running
[2024-02-18T23:39:38.585Z] Start: Run: docker version
[2024-02-18T23:39:38.634Z] Client:
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.8
 Git commit:        ced0996
 Built:             Sat Oct  7 00:14:00 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
[2024-02-18T23:39:38.634Z]  Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.8
  Git commit:       a61e2b4
  Built:            Sat Oct  7 00:14:30 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
[2024-02-18T23:39:38.636Z] Stop (51 ms): Run: docker version
[2024-02-18T23:39:38.636Z] Stop (52 ms): Check Docker is running
[2024-02-18T23:39:38.636Z] Start: Run: docker volume ls -q
[2024-02-18T23:39:38.676Z] Stop (40 ms): Run: docker volume ls -q
[2024-02-18T23:39:38.676Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux --filter label=vsch.quality=stable
[2024-02-18T23:39:38.716Z] Stop (40 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux --filter label=vsch.quality=stable
[2024-02-18T23:39:38.716Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux --filter label=devcontainer.config_file=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux/.devcontainer/devcontainer.json
[2024-02-18T23:39:38.753Z] Stop (37 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux --filter label=devcontainer.config_file=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux/.devcontainer/devcontainer.json
[2024-02-18T23:39:38.753Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux
[2024-02-18T23:39:38.791Z] Stop (38 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux
[2024-02-18T23:39:38.791Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux
[2024-02-18T23:39:38.861Z] Stop (70 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux
[2024-02-18T23:39:38.862Z] Start: Run: /usr/share/code/code /home/tom/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux --id-label devcontainer.local_folder=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux --id-label devcontainer.config_file=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux/.devcontainer/devcontainer.json --mount-workspace-git-root
[2024-02-18T23:39:39.029Z] @devcontainers/cli 0.56.0. Node.js v18.17.1. linux 6.5.0-18-generic x64.
[2024-02-18T23:39:39.029Z] Start: Run: git rev-parse --show-cdup
[2024-02-18T23:39:39.035Z] Stop (6 ms): Run: git rev-parse --show-cdup
[2024-02-18T23:39:39.035Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux --filter label=devcontainer.config_file=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux/.devcontainer/devcontainer.json
[2024-02-18T23:39:39.113Z] Stop (78 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux --filter label=devcontainer.config_file=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux/.devcontainer/devcontainer.json
[2024-02-18T23:39:39.118Z] Stop (256 ms): Run: /usr/share/code/code /home/tom/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux --id-label devcontainer.local_folder=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux --id-label devcontainer.config_file=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux/.devcontainer/devcontainer.json --mount-workspace-git-root
[2024-02-18T23:39:39.119Z] Start: Run: /usr/share/code/code /home/tom/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/tom/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-ac876edd-b4fe-4d70-8083-c7e83d3cd2d01708299578036 --workspace-folder /home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux --id-label devcontainer.config_file=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-dd5f67ba-8246-4920-bc2a-d0e7c4efc581.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-02-18T23:39:39.288Z] @devcontainers/cli 0.56.0. Node.js v18.17.1. linux 6.5.0-18-generic x64.
[2024-02-18T23:39:39.288Z] Start: Run: docker buildx version
[2024-02-18T23:39:39.400Z] Stop (112 ms): Run: docker buildx version
[2024-02-18T23:39:39.400Z] github.com/docker/buildx v0.11.2 9872040b6626fb7d87ef7296fd5b832e8cc2ad17
[2024-02-18T23:39:39.400Z] 
[2024-02-18T23:39:39.400Z] Start: Resolving Remote
[2024-02-18T23:39:39.401Z] Start: Run: git rev-parse --show-cdup
[2024-02-18T23:39:39.405Z] Stop (4 ms): Run: git rev-parse --show-cdup
[2024-02-18T23:39:39.443Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux --filter label=devcontainer.config_file=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux/.devcontainer/devcontainer.json
[2024-02-18T23:39:39.509Z] Stop (66 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux --filter label=devcontainer.config_file=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux/.devcontainer/devcontainer.json
[2024-02-18T23:39:39.511Z] Start: Run: docker inspect --type image mcr.microsoft.com/devcontainers/cpp:1-ubuntu-20.04
[2024-02-18T23:39:39.597Z] Stop (86 ms): Run: docker inspect --type image mcr.microsoft.com/devcontainers/cpp:1-ubuntu-20.04
[2024-02-18T23:39:40.965Z] Start: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-tom/container-features/0.56.0-1708299580963/Dockerfile-with-features -t vsc-vaas-dsp-dev_camera-l6c-lprapp-linux-0e7daada5b97192d14f16d6429b5122695f3e1282fb7f39ca188f42b096e63b1 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux/.devcontainer
[2024-02-18T23:39:41.171Z] [+] Building 0.0s (0/0)                                          docker:default
[2024-02-18T23:39:41.171Z] ERROR: could not find /tmp/devcontainercli-tom/container-features/0.56.0-1708299580963: stat /tmp/devcontainercli-tom/container-features/0.56.0-1708299580963: no such file or directory
[2024-02-18T23:39:41.174Z] Stop (209 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-tom/container-features/0.56.0-1708299580963/Dockerfile-with-features -t vsc-vaas-dsp-dev_camera-l6c-lprapp-linux-0e7daada5b97192d14f16d6429b5122695f3e1282fb7f39ca188f42b096e63b1 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux/.devcontainer
[2024-02-18T23:39:41.174Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-tom/container-features/0.56.0-1708299580963/Dockerfile-with-features -t vsc-vaas-dsp-dev_camera-l6c-lprapp-linux-0e7daada5b97192d14f16d6429b5122695f3e1282fb7f39ca188f42b096e63b1 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux/.devcontainer
[2024-02-18T23:39:41.175Z]     at Y$ (/home/tom/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js:465:1933)
[2024-02-18T23:39:41.175Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-02-18T23:39:41.175Z]     at async Fw (/home/tom/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js:464:1831)
[2024-02-18T23:39:41.175Z]     at async $J (/home/tom/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js:464:608)
[2024-02-18T23:39:41.175Z]     at async tAA (/home/tom/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js:481:3660)
[2024-02-18T23:39:41.175Z]     at async CC (/home/tom/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js:481:4775)
[2024-02-18T23:39:41.175Z]     at async NeA (/home/tom/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js:614:11107)
[2024-02-18T23:39:41.175Z]     at async MeA (/home/tom/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js:614:10848)
[2024-02-18T23:39:41.179Z] Stop (2060 ms): Run: /usr/share/code/code /home/tom/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/tom/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-ac876edd-b4fe-4d70-8083-c7e83d3cd2d01708299578036 --workspace-folder /home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux --id-label devcontainer.config_file=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-dd5f67ba-8246-4920-bc2a-d0e7c4efc581.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-02-18T23:39:41.179Z] Exit code 1
[2024-02-18T23:39:41.183Z] Command failed: /usr/share/code/code /home/tom/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/tom/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-ac876edd-b4fe-4d70-8083-c7e83d3cd2d01708299578036 --workspace-folder /home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux --id-label devcontainer.config_file=/home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/tom/Documents/GitHub/VaaS-DSP-Dev_Camera-L6C-LPRApp-Linux/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-dd5f67ba-8246-4920-bc2a-d0e7c4efc581.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-02-18T23:39:41.183Z] Exit code 1

```

Steps to Reproduce:
I'm trying to add a container to a directory so I can build with Ubuntu 20.04 but it keeps failing with the above error. But the directory does exist:
```
$ stat /tmp/devcontainercli-tom/container-features/0.56.0-1708299580963
  File: /tmp/devcontainercli-tom/container-features/0.56.0-1708299580963
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 10302h/66306d	Inode: 95551576    Links: 2
Access: (0775/drwxrwxr-x)  Uid: ( 1000/     tom)   Gid: ( 1000/     tom)
Access: 2024-02-19 12:39:40.961291986 +1300
Modify: 2024-02-19 12:39:40.961291986 +1300
Change: 2024-02-19 12:39:40.961291986 +1300
 Birth: 2024-02-19 12:39:40.961291986 +1300
```

**Comment by gonzaloarro** [comment]
I am having the same issue

**Comment by chrmarti** [comment]
Is this still an issue?
