### ISSUE TITLE
Error Remote-ssh Win Serv 2012 r2

### ISSUE THREAD

**Issue by LpDuguitT** [microsoft/vscode-remote-release#9567]
Hello everyone,
I recently set up a windows server 2012 r2 on which I installed openSSH (default installation).
From another station, when I use ssh everything works perfectly from the cmd, I have access to files etc.. 
However, when I try to connect to Vscode using Remote-ssh, the connection doesn't work, it loads for a very long time but nothing happens.

    Logs : 
    [08:30:24.494] Log Level: 2
    [08:30:24.500] SSH Resolver called for "ssh-remote+192.168.100.20", attempt 1
    [08:30:24.500] "remote.SSH.useLocalServer": false
    [08:30:24.500] "remote.SSH.useExecServer": false
    [08:30:24.501] "remote.SSH.showLoginTerminal": false
    [08:30:24.501] "remote.SSH.remotePlatform": {"EVENG":"linux"}
    [08:30:24.501] "remote.SSH.path": undefined
    [08:30:24.501] "remote.SSH.configFile": undefined
    [08:30:24.501] "remote.SSH.useFlock": true
    [08:30:24.503] "remote.SSH.lockfilesInTmp": false
    [08:30:24.503] "remote.SSH.localServerDownload": auto
    [08:30:24.503] "remote.SSH.remoteServerListenOnSocket": false
    [08:30:24.503] "remote.SSH.showLoginTerminal": false
    [08:30:24.503] "remote.SSH.defaultExtensions": []
    [08:30:24.503] "remote.SSH.loglevel": 2
    [08:30:24.503] "remote.SSH.enableDynamicForwarding": true
    [08:30:24.503] "remote.SSH.enableRemoteCommand": false
    [08:30:24.503] "remote.SSH.serverPickPortsFromRange": {}
    [08:30:24.503] "remote.SSH.serverInstallPath": {}
    [08:30:24.505] VS Code version: 1.86.2
    [08:30:24.505] Remote-SSH version: remote-ssh@0.108.0
    [08:30:24.505] win32 x64
    [08:30:24.507] SSH Resolver called for host: 192.168.100.20
    [08:30:24.507] Setting up SSH remote "192.168.100.20"
    [08:30:24.509] Using commit id "627ejfkf98564212654e5efez3fefzazfdkez820edaa" and quality "stable" for server
    [08:30:24.511] Install and start server if needed
    [08:30:25.902] Checking ssh with "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe -V"
    [08:30:25.903] Got error from ssh: spawn C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
    [08:30:25.903] Checking ssh with "C:\Program Files (x86)\VMware\VMware Workstation\bin\ssh.exe -V"
    [08:30:25.904] Got error from ssh: spawn C:\Program Files (x86)\VMware\VMware Workstation\bin\ssh.exe ENOENT
    [08:30:25.904] Checking ssh with "C:\Windows\system32\ssh.exe -V"
    [08:30:25.905] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
    [08:30:25.905] Checking ssh with "C:\Windows\ssh.exe -V"
    [08:30:25.905] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
    [08:30:25.905] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
    [08:30:25.906] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
    [08:30:25.906] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
    [08:30:25.907] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
    [08:30:25.907] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
    [08:30:25.937] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3
    
    [08:30:25.941] Remote command length: 6226/8192 characters
    [08:30:25.941] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 57146 "192.168.100.20" powershell
    [08:30:25.942] Terminal shell path: C:\Windows\System32\cmd.exe
    [08:30:26.606] > test.test@192.168.100.20's password:]0;C:\Windows\System32\cmd.exe 
    [08:30:26.606] Got some output, clearing connection timeout
    [08:30:26.607] Showing password prompt
    [08:30:36.442] Got password response
    [08:30:36.442] "install" wrote data to terminal: ******
    [08:30:36.483] > 
    [08:30:42.901] > test.test@192.168.100.20's password:
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    > 
    [08:30:42.901] Showing password prompt
    [08:31:33.823] Got password response
    [08:31:33.823] "install" wrote data to terminal: ******
    [08:39:39.989] "install" terminal command done
    [08:39:39.989] Install terminal quit with output: 
    [08:39:39.990] Resolver error: Error: Got bad result from install script
	    at g.Create (c:\Users\G533\.vscode\extensions\ms-vscode-remote.remote-ssh-0.108.0\out\extension.js:2:460245)
	    at t.tryInstall (c:\Users\G533\.vscode\extensions\ms-vscode-remote.remote-ssh-0.108.0\out\extension.js:2:580836)
	    at async c:\Users\G533\.vscode\extensions\ms-vscode-remote.remote-ssh-0.108.0\out\extension.js:2:540958
	    at async t.withShowDetailsEvent (c:\Users\G533\.vscode\extensions\ms-vscode-remote.remote-ssh-0.108.0\out\extension.js:2:544264)
	    at async k (c:\Users\G533\.vscode\extensions\ms-vscode-remote.remote-ssh-0.108.0\out\extension.js:2:537923)
	    at async t.resolve (c:\Users\G533\.vscode\extensions\ms-vscode-remote.remote-ssh-0.108.0\out\extension.js:2:541635)
	    at async c:\Users\G533\.vscode\extensions\ms-vscode-remote.remote-ssh-0.108.0\out\extension.js:2:807794
    [08:39:39.996] ------
    
    
    
    
    [08:39:40.477] Opening exec server for ssh-remote+192.168.100.20
    [08:39:40.477] Opening exec server for ssh-remote+192.168.100.20
    [08:39:40.484] Initizing new exec server for ssh-remote+192.168.100.20
    [08:39:40.509] Using commit id "627ejfkf98564212654e5efez3fefzazfdkez820edaa" and quality "stable" for server
    [08:39:40.512] Install and start server if needed
    [08:39:42.138] getPlatformForHost was canceled
    [08:39:42.138] Exec server for ssh-remote+192.168.100.20 failed: Error: Connecting was canceled
    [08:39:42.138] Existing exec server for ssh-remote+192.168.100.20 errored (Error: Connecting was canceled)
    [08:39:42.139] Initizing new exec server for ssh-remote+192.168.100.20
    [08:39:42.139] Using commit id "627ejfkf98564212654e5efez3fefzazfdkez820edaa" and quality "stable" for server
    [08:39:42.140] Error opening exec server for ssh-remote+192.168.100.20: Error: Connecting was canceled
    [08:39:42.140] Install and start server if needed
    

-Vscode 1.86.2
- Windows server 2012 r2

Steps to Reproduce:

1.Use remote-ssh on vscode
2. entrer les informations d'identification

**Comment by lizeyujack** [comment]
I have the same problem.

**Comment by joshspicer** [comment]
Are you seeing the password prompt?

Does running `"C:\Windows\System32\OpenSSH\ssh.exe" -T -D 57146 "192.168.100.20" powershell` from your terminal on your local machine (the same station as where this log is from), does it connect?  If so, could you show me the output of executing this:

```
ssh -T -o ConnectTimeout=15 '192.168.100.20' powershell << 'EOSSH'
$uuid="test-script"
"${uuid}: running"
$PSVersion = $PSVersionTable.PSVersion
Write-Output "PowerShell Version: $($PSVersion.Major).$($PSVersion.Minor).$($PSVersion.Build)"
"${uuid}: done"
EOSSH
```
(script borrowed from troubleshooting in [this issue](https://github.com/microsoft/vscode-remote-release/issues/10510))

Please note that Windows server 2012 is no longer supported by Microsoft
