### ISSUE TITLE
Dev Containers Remote-Explorer: UNC host 'wsl.localhost' access is not allowed

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#9608]
```
notificationsAlerts.ts:40 Error: UNC host 'wsl.localhost' access is not allowed
    at stat (node:fs:1597:10)
    at Object.<anonymous> (node:electron/js2c/node_init:2:4911)
    at c:\Users\raymondzhao\.vscode\extensions\ms-vscode-remote.remote-containers-0.347.0\dist\extension\extension.js:56:11049
    at new Promise (<anonymous>)
    at Object.gr [as isFile] (c:\Users\raymondzhao\.vscode\extensions\ms-vscode-remote.remote-containers-0.347.0\dist\extension\extension.js:56:11031)
    at Xd (c:\Users\raymondzhao\.vscode\extensions\ms-vscode-remote.remote-containers-0.347.0\dist\extension\extension.js:270:1474)
    at a3 (c:\Users\raymondzhao\.vscode\extensions\ms-vscode-remote.remote-containers-0.347.0\dist\extension\extension.js:279:1769)
    at s3 (c:\Users\raymondzhao\.vscode\extensions\ms-vscode-remote.remote-containers-0.347.0\dist\extension\extension.js:279:1554)
    at SU.getWorkspaceFolderFromHostWorkspace (c:\Users\raymondzhao\.vscode\extensions\ms-vscode-remote.remote-containers-0.347.0\dist\extension\extension.js:354:16003)
    at SU.getChildDevContainer (c:\Users\raymondzhao\.vscode\extensions\ms-vscode-remote.remote-containers-0.347.0\dist\extension\extension.js:354:12649)
    at async Promise.all (index 1)
    at SU.getChildContainers (c:\Users\raymondzhao\.vscode\extensions\ms-vscode-remote.remote-containers-0.347.0\dist\extension\extension.js:354:13870)
    at n.Y (c:\Users\raymondzhao\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:40693)
    at n.getChildren (c:\Users\raymondzhao\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:37063)
```

**Comment by rzhao271** [comment]
I believe I got these errors while verifying Linux servers on VS Code Insiders on Windows.
I'll verify another Linux server right now.
