### ISSUE TITLE
uv_os_get_passwd returned ENOENT if user uses AD (ldap or similar)

### ISSUE THREAD

**Issue by Roman2dot0** [microsoft/vscode-remote-release#9649]
Does this issue occur when all extensions are disabled?: Yes/No
N/A

    VS Code Version: 1.87.1
    OS Version: Ubuntu 23.10, snap

Steps to Reproduce:

    Open VSCode
    Attempt to connect to an existing or new ssh config using Remote Development Extension
    Pop up below happens:
    'A system error occurred (A system error ocurred: uv_os_get_passwd returned ENOENT (no such file or directory))

TEMP SOLUTION:
Add username into /etc/passwd (which doesn't exist due to ldap)

**Comment by roblourens** [comment]
Can you share the log from the Remote-SSH output channel? I don't think we're reading `/etc/passwd`. Are you trying to open a container?

**Comment by Roman2dot0** [comment]
Log, when I connect to a remote host by ssh.

test.user@e.mail - from LDAP
/home/test.user@e.mail  - actual home dir
test.user - actual username from 'whoami' of  'id' commands.

`2024-03-20 17:31:33.602 [info] Extension host with pid 40803 started
2024-03-20 17:31:33.602 [info] Skipping acquiring lock for /home/test.user@e.mail/.config/Code/User/workspaceStorage/56a792434c29d4f414321a02132b891c.
2024-03-20 17:31:33.756 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-03-20 17:31:33.760 [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'onLanguage:yaml', root cause: redhat.ansible
2024-03-20 17:31:33.814 [info] ExtensionService#_doActivateExtension redhat.vscode-yaml, startup: false, activationEvent: 'onLanguage:yaml', root cause: redhat.ansible
2024-03-20 17:31:33.855 [info] ExtensionService#_doActivateExtension ms-azuretools.vscode-docker, startup: false, activationEvent: 'onLanguage:dockerfile'
2024-03-20 17:31:33.922 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:javascript'
2024-03-20 17:31:34.157 [debug] ProxyResolver#resolveProxy https://default.exp-tas.com/vscode/ab DIRECT 
2024-03-20 17:31:34.171 [debug] ProxyResolver#resolveProxy https://default.exp-tas.com/vscode/ab DIRECT 
2024-03-20 17:31:34.255 [info] ExtensionService#_doActivateExtension redhat.ansible, startup: false, activationEvent: 'onLanguage:yaml'
2024-03-20 17:31:34.398 [info] ExtensionService#_doActivateExtension ms-python.vscode-pylance, startup: false, activationEvent: 'api', root cause: ms-python.python
2024-03-20 17:31:35.760 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-03-20 17:31:35.935 [warning] [redhat.vscode-yaml] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[yaml]', provide the URI of a resource or 'null' for any resource.
2024-03-20 17:31:35.936 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-03-20 17:31:35.956 [warning] [redhat.vscode-yaml] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[yaml]', provide the URI of a resource or 'null' for any resource.
2024-03-20 17:31:35.957 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-03-20 17:31:35.997 [info] Eager extensions activated
2024-03-20 17:31:36.041 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-03-20 17:31:36.043 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-03-20 17:31:36.048 [info] ExtensionService#_doActivateExtension eamodio.gitlens, startup: false, activationEvent: 'onStartupFinished'
2024-03-20 17:31:36.766 [debug] ProxyResolver#resolveProxy https://mobile.events.data.microsoft.com/OneCollector/1.0?cors=true&content-type=application/x-json-stream DIRECT 
2024-03-20 17:31:36.777 [debug] ProxyResolver#resolveProxy https://mobile.events.data.microsoft.com/OneCollector/1.0?cors=true&content-type=application/x-json-stream DIRECT 
2024-03-20 17:31:36.786 [debug] ProxyResolver#resolveProxy https://mobile.events.data.microsoft.com/OneCollector/1.0?cors=true&content-type=application/x-json-stream DIRECT 
2024-03-20 17:31:38.699 [debug] ProxyResolver#resolveProxy cached https://mobile.events.data.microsoft.com/OneCollector/1.0?cors=true&content-type=application/x-json-stream DIRECT 
2024-03-20 17:31:38.915 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-ssh, startup: false, activationEvent: 'onCommand:opensshremotes.openEmptyWindow'
2024-03-20 17:31:38.939 [info] ExtensionService#_doActivateExtension ms-vscode.remote-explorer, startup: false, activationEvent: 'onCommand:remote-internal.setActiveFolders'
2024-03-20 17:31:38.946 [error] SystemError: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
	at new SystemError (node:internal/errors:256:5)
	at new NodeError (node:internal/errors:367:7)
	at Object.userInfo (node:os:365:11)
	at y.compute (/home/test.user@e.mail/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:450860)
	at /home/test.user@e.mail/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:603411
	at Array.forEach (<anonymous>)
	at O (/home/test.user@e.mail/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:603388)
	at P (/home/test.user@e.mail/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:602819)
	at async t.getConfiguredSshHosts (/home/test.user@e.mail/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:604945)
	at async t.interactivelyPickSshHost (/home/test.user@e.mail/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:489633)
	at async g.openEmptyWindow (/home/test.user@e.mail/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:468930)
	at async l.h (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:184831) opensshremotes.openEmptyWindow {"value":"ms-vscode-remote.remote-ssh","_lower":"ms-vscode-remote.remote-ssh"}
2024-03-20 17:31:38.948 [error] SystemError: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
	at new SystemError (node:internal/errors:256:5)
	at new NodeError (node:internal/errors:367:7)
	at Object.userInfo (node:os:365:11)
	at y.compute (/home/test.user@e.mail/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:450860)
	at /home/test.user@e.mail/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:603411
	at Array.forEach (<anonymous>)
	at O (/home/test.user@e.mail/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:603388)
	at P (/home/test.user@e.mail/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:602819)
	at async g.getConfiguredHostnames (/home/test.user@e.mail/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:470189)
	at async l.h (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:184831)
	at async Promise.all (index 1)
	at async t.RemoteTreeDataProvider.refeshSshHosts (/home/test.user@e.mail/.vscode/extensions/ms-vscode.remote-explorer-0.4.3/dist/node/extension.js:1:8182) remote-internal.getConfiguredHostnames {"value":"ms-vscode-remote.remote-ssh","_lower":"ms-vscode-remote.remote-ssh"}
2024-03-20 17:31:39.438 [debug] ProxyResolver#resolveProxy cached https://mobile.events.data.microsoft.com/OneCollector/1.0?cors=true&content-type=application/x-json-stream DIRECT 
2024-03-20 17:31:40.948 [debug] ProxyResolver#resolveProxy cached https://mobile.events.data.microsoft.com/OneCollector/1.0?cors=true&content-type=application/x-json-stream DIRECT 
2024-03-20 17:31:41.482 [info] Extension host terminating: renderer closed the MessagePort
2024-03-20 17:31:41.517 [error] Canceled: Canceled
	at new $ (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:45885)
	at s.U (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:5556)
	at z.<computed>.T.charCodeAt.z.<computed> (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:3007)
	at l.g (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:184300)
	at l.executeCommand (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183738)
	at f.registerCommand.description (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183062)
	at l.h (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:184839)
	at l.g (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183831)
	at l.executeCommand (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183738)
	at Object.executeCommand (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:21654)
	at w (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:1081:41198)
	at h (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:1081:46237)
	at ActionRunners._updateContextKeys (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:663:18411)
	at s (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:663:16855)
	at RegisteredActionRunner.unregister (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:663:16998)
	at RegisteredActionRunner.dispose (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:663:15651)
	at ActionRunners.dispose (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:663:16438)
	at /home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:1041:19519
	at Array.forEach (<anonymous>)
	at Object.dispose (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:1041:19501)
	at o (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:754)
	at w.cb (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:9882)
	at /snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:7816
	at Array.map (<anonymous>)
	at w.Y (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:7803)
	at w.terminate (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:8076)
	at o.terminate (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:1513)
	at t (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:9949)
	at MessagePortMain.<anonymous> (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:6374)
	at MessagePortMain.emit (node:events:514:28)
	at Object.emit (node:electron/js2c/utility_init:2:2285) setContext undefined
2024-03-20 17:31:41.518 [error] Canceled: Canceled
	at new $ (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:45885)
	at s.U (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:5556)
	at z.<computed>.T.charCodeAt.z.<computed> (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:3007)
	at l.g (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:184300)
	at l.executeCommand (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183738)
	at f.registerCommand.description (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183062)
	at l.h (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:184839)
	at l.g (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183831)
	at l.executeCommand (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183738)
	at Object.executeCommand (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:21654)
	at w (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:1081:41198)
	at h (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:1081:46237)
	at ActionRunners._updateContextKeys (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:663:18411)
	at s (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:663:16855)
	at RegisteredActionRunner.unregister (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:663:16998)
	at RegisteredActionRunner.dispose (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:663:15651)
	at ActionRunners.dispose (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:663:16438)
	at /home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:1041:19519
	at Array.forEach (<anonymous>)
	at Object.dispose (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:1041:19501)
	at o (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:754)
	at w.cb (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:9882)
	at /snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:7816
	at Array.map (<anonymous>)
	at w.Y (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:7803)
	at w.terminate (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:8076)
	at o.terminate (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:1513)
	at t (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:9949)
	at MessagePortMain.<anonymous> (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:6374)
	at MessagePortMain.emit (node:events:514:28)
	at Object.emit (node:electron/js2c/utility_init:2:2285) setContext undefined
2024-03-20 17:31:41.518 [error] Canceled: Canceled
	at new $ (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:45885)
	at s.U (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:5556)
	at z.<computed>.T.charCodeAt.z.<computed> (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:3007)
	at l.g (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:184300)
	at l.executeCommand (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183738)
	at f.registerCommand.description (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183062)
	at l.h (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:184839)
	at l.g (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183831)
	at l.executeCommand (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183738)
	at Object.executeCommand (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:21654)
	at w (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:1081:41198)
	at h (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:1081:46237)
	at ActionRunners._updateContextKeys (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:663:18411)
	at s (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:663:16855)
	at RegisteredActionRunner.unregister (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:663:16998)
	at RegisteredActionRunner.dispose (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:663:15651)
	at ActionRunners.dispose (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:663:16438)
	at /home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:1041:19519
	at Array.forEach (<anonymous>)
	at Object.dispose (/home/test.user@e.mail/.vscode/extensions/eamodio.gitlens-14.9.0/dist/gitlens.js:1041:19501)
	at o (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:30:754)
	at w.cb (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:9882)
	at /snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:7816
	at Array.map (<anonymous>)
	at w.Y (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:7803)
	at w.terminate (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:8076)
	at o.terminate (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:1513)
	at t (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:9949)
	at MessagePortMain.<anonymous> (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:6374)
	at MessagePortMain.emit (node:events:514:28)
	at Object.emit (node:electron/js2c/utility_init:2:2285) setContext undefined
2024-03-20 17:31:41.518 [error] Canceled: Canceled
	at new $ (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:45885)
	at s.U (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:5556)
	at z.<computed>.T.charCodeAt.z.<computed> (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:3007)
	at l.g (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:184300)
	at l.executeCommand (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183738)
	at f.registerCommand.description (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183062)
	at l.h (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:184839)
	at l.g (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183831)
	at l.executeCommand (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:183738)
	at Object.executeCommand (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:21654)
	at t.shutdown (/home/test.user@e.mail/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:583254)
	at e.deactivate (/home/test.user@e.mail/.vscode/extensions/ms-vscode-remote.remote-ssh-0.109.0/out/extension.js:2:850474)
	at w.cb (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:9687)
	at /snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:7816
	at Array.map (<anonymous>)
	at w.Y (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:7803)
	at w.terminate (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:8076)
	at o.terminate (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:1513)
	at t (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:9949)
	at MessagePortMain.<anonymous> (/snap/code/155/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:6374)
	at MessagePortMain.emit (node:events:514:28)
	at Object.emit (node:electron/js2c/utility_init:2:2285) setContext undefined
2024-03-20 17:31:41.564 [info] Extension host with pid 40803 exiting with code 0
`

**Comment by roblourens** [comment]
Thanks, this is the library we use for parsing the ssh config file, filed upstream: https://github.com/cyjake/ssh-config/issues/77

**Comment by mcallaghan-geotab** [comment]
https://github.com/cyjake/ssh-config/releases/tag/v4.4.3 was released which contains the fix FYI

**Comment by eleanorjboyd** [comment]
Hi @Roman2dot0! Are you able to verify this fix is resolved? You can do so by using vscode insiders and making sure you are on the newest version of insiders and the ssh extension. Please let me know if you are able to see that the bug is resolved. Thank you!

**Comment by TylerLeonhardt** [comment]
@roblourens could you give us some verification steps just in case?

**Comment by roblourens** [comment]
I can't repro it but the change in the upstream library should be good

**Comment by Roman2dot0** [comment]
Sorry for delay. I cheched and remote works as expected. Thanks!
