### ISSUE TITLE
Relative file path for dockerComposeFile does not work

### ISSUE THREAD

**Issue by burgealex** [microsoft/vscode-remote-release#9658]
- VSCode Version: 1.87.2
- Local OS Version: 22.04
- Remote OS Version: 22.04
- Remote Extension/Connection Type: Containers

- Logs:

`73 ms] Start: Run in container:  (command -v getent >/dev/null 2>&1 && getent passwd 'vscode' || grep -E '^vscode|^[^:]*:[^:]*:vscode:' /etc/passwd || true)
[1673 ms] Stdin closed!
[1673 ms] Error: An error occurred setting up the container.
[1673 ms]     at ttA (/home/aburge/.vscode/extensions/ms-vscode-remote.remote-containers-0.348.0/dist/spec-node/devContainersSpecCLI.js:409:3572)
[1673 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1673 ms]     at async StA (/home/aburge/.vscode/extensions/ms-vscode-remote.remote-containers-0.348.0/dist/spec-node/devContainersSpecCLI.js:481:3833)
[1673 ms]     at async ZC (/home/aburge/.vscode/extensions/ms-vscode-remote.remote-containers-0.348.0/dist/spec-node/devContainersSpecCLI.js:481:4775)
[1674 ms]     at async trA (/home/aburge/.vscode/extensions/ms-vscode-remote.remote-containers-0.348.0/dist/spec-node/devContainersSpecCLI.js:614:11269)
[1674 ms]     at async erA (/home/aburge/.vscode/extensions/ms-vscode-remote.remote-containers-0.348.0/dist/spec-node/devContainersSpecCLI.js:614:11010)
[1677 ms] Exit code 1
[1679 ms] Command failed: /snap/code/155/usr/share/code/code /home/aburge/.vscode/extensions/ms-vscode-remote.remote-containers-0.348.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/aburge/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-a3cf2289-c8f0-4321-b9d7-ccb05b7d30c01710437899290 --workspace-folder /home/aburge/git/example-linux-app --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/aburge/git/example-linux-app --id-label devcontainer.config_file=/home/aburge/git/example-linux-app/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/aburge/git/example-linux-app/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[1679 ms] Exit code 1`

Steps to Reproduce:

1. Make a devcontainer.json file that references ../docker-compose.yml as dockerComposeFile and it fails with the above error.  Move the file to the .devcontainers folder and remove the ../ and it works just fine.

**Comment by chrmarti** [comment]
Please append the devcontainer.json, docker-compose.yml and the full Dev Containers log from when this happens. (`F1` > `Dev Containers: Show Container Log`)
