### ISSUE TITLE
[Remote-SSH Bug]: Failed to parse remote port from server output

### ISSUE THREAD

**Issue by the4amfriend** [microsoft/vscode-remote-release#9661]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [x] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### -> Error message

Failed to parse remote port from server output with exit code 35, unsure what that means. 

### Steps To Reproduce

Version: 1.87.2 (user setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

Connect to NonStop using SSH

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[12:46:37.485] Log Level: 2
[12:46:37.524] SSH Resolver called for "ssh-remote+ztc0.tcmuk.local", attempt 1
[12:46:37.525] "remote.SSH.useLocalServer": false
[12:46:37.526] "remote.SSH.useExecServer": true
[12:46:37.528] "remote.SSH.showLoginTerminal": false
[12:46:37.529] "remote.SSH.remotePlatform": {"10.0.0.6":"linux"}
[12:46:37.530] "remote.SSH.path": undefined
[12:46:37.531] "remote.SSH.configFile": undefined
[12:46:37.532] "remote.SSH.useFlock": true
[12:46:37.532] "remote.SSH.lockfilesInTmp": false
[12:46:37.533] "remote.SSH.localServerDownload": auto
[12:46:37.534] "remote.SSH.remoteServerListenOnSocket": false
[12:46:37.534] "remote.SSH.showLoginTerminal": false
[12:46:37.535] "remote.SSH.defaultExtensions": []
[12:46:37.536] "remote.SSH.loglevel": 2
[12:46:37.537] "remote.SSH.enableDynamicForwarding": true
[12:46:37.537] "remote.SSH.enableRemoteCommand": false
[12:46:37.538] "remote.SSH.serverPickPortsFromRange": {}
[12:46:37.538] "remote.SSH.serverInstallPath": {}
[12:46:37.550] VS Code version: 1.87.2
[12:46:37.550] Remote-SSH version: remote-ssh@0.109.0
[12:46:37.550] win32 x64
[12:46:37.555] SSH Resolver called for host: ztc0.tcmuk.local
[12:46:37.555] Setting up SSH remote "ztc0.tcmuk.local"
[12:46:37.569] Using commit id "863d2581ecda6849923a2118d93a088b0745d9d6" and quality "stable" for server
[12:46:37.590] Install and start server if needed
[12:46:38.949] Checking ssh with "C:\Program Files (x86)\RSA SecurID Token Common\ssh.exe -V"
[12:46:38.952] Got error from ssh: spawn C:\Program Files (x86)\RSA SecurID Token Common\ssh.exe ENOENT
[12:46:38.953] Checking ssh with "C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe -V"
[12:46:38.956] Got error from ssh: spawn C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[12:46:38.957] Checking ssh with "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe -V"
[12:46:38.962] Got error from ssh: spawn C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[12:46:38.963] Checking ssh with "C:\windows\system32\ssh.exe -V"
[12:46:38.968] Got error from ssh: spawn C:\windows\system32\ssh.exe ENOENT
[12:46:38.969] Checking ssh with "C:\windows\ssh.exe -V"
[12:46:38.974] Got error from ssh: spawn C:\windows\ssh.exe ENOENT
[12:46:38.975] Checking ssh with "C:\windows\System32\Wbem\ssh.exe -V"
[12:46:38.984] Got error from ssh: spawn C:\windows\System32\Wbem\ssh.exe ENOENT
[12:46:38.984] Checking ssh with "C:\windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[12:46:38.988] Got error from ssh: spawn C:\windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[12:46:38.989] Checking ssh with "C:\windows\System32\OpenSSH\ssh.exe -V"
[12:46:39.097] > OpenSSH_for_Wind
[12:46:39.098] > ows_8.1p1, LibreSSL 3.0.2

[12:46:39.107] Running script with connection command: "C:\windows\System32\OpenSSH\ssh.exe" -T -D 56679 "ztc0.tcmuk.local" bash
[12:46:39.114] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[12:46:40.443] > ]0;C:\WINDOWS\System32\cmd.exe
[12:46:40.443] Got some output, clearing connection timeout
[12:46:43.795] > Password: 
[12:46:43.796] Showing password prompt
[12:46:46.930] Got password response
[12:46:46.931] "install" wrote data to terminal: "********"
[12:46:46.970] > 
[12:46:47.032] > Last Logon:  15 MAR 2024, 12:46    
> Last Unsuccessful Attempt: * NONE *
> Last Logon Failures: 0
[12:46:47.284] > 3f9302bd9b8e: running
[12:46:47.314] > grep: illegal option -- a
> usage: grep [-E | -F] [-c|-l|-q] [-insvxbhwy] [-p parasep] -e pattern_list...  
>         [-f pattern_file...] [file...]
> usage: grep [-E | -F] [-c|-l|-q] [-insvxbhwy] [-p parasep] [-e pattern_list...]
>         -f pattern_file... [file...]
> usage: grep [-E | -F] [-c|-l|-q] [-insvxbhwy] [-p parasep] pattern [file...]   
[12:46:47.329] > grep: illegal option -- a
> usage: grep [-E | -F] [-c|-l|-q] [-insvxbhwy] [-p parasep] -e pattern_list...  
>         [-f pattern_file...] [file...]
> usage: grep [-E | -F] [-c|-l|-q] [-insvxbhwy] [-p parasep] [-e pattern_list...]
>         -f pattern_file... [file...]
> usage: grep [-E | -F] [-c|-l|-q] [-insvxbhwy] [-p parasep] pattern [file...]   
[12:46:47.346] > Unsupported platform: NONSTOP_KERNEL
> 3f9302bd9b8e: start
> exitCode==35==
[12:46:47.375] > listeningOn====
> osReleaseId==NONSTOP_KERNEL==
> arch====
> vscodeArch====
> bitness====
> tmpDir==/tmp==
> platform====
> unpackResult====
> didLocalDownload==0==        
> downloadTime====
> installTime====
> serverStartTime====
> execServerToken==a1a11111-a11a-1111-111a-1a1111aa1a1a==
> 3f9302bd9b8e: end
[12:46:47.376] Received install output: 
exitCode==35==
listeningOn====
osReleaseId==NONSTOP_KERNEL==
arch====
vscodeArch====
bitness====
tmpDir==/tmp==
platform====
unpackResult====
didLocalDownload==0==        
downloadTime====
installTime====
serverStartTime====
execServerToken==a1a11111-a11a-1111-111a-1a1111aa1a1a==

[12:46:47.379] Failed to parse remote port from server output
[12:46:47.383] Resolver error: Error: 
	at g.Create (c:\Users\Shiva.Subramanian\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.0\out\extension.js:2:499734)
	at t.handleInstallOutput (c:\Users\Shiva.Subramanian\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.0\out\extension.js:2:497056)
	at t.tryInstall (c:\Users\Shiva.Subramanian\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.0\out\extension.js:2:620589)
	at async c:\Users\Shiva.Subramanian\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.0\out\extension.js:2:580447
	at async t.withShowDetailsEvent (c:\Users\Shiva.Subramanian\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.0\out\extension.js:2:583753)
	at async k (c:\Users\Shiva.Subramanian\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.0\out\extension.js:2:577412)
	at async t.resolve (c:\Users\Shiva.Subramanian\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.0\out\extension.js:2:581124)
	at async c:\Users\Shiva.Subramanian\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.0\out\extension.js:2:847283
[12:46:47.396] ------




[12:46:48.694] Opening exec server for ssh-remote+ztc0.tcmuk.local
[12:46:48.783] "install" terminal command done
[12:46:48.785] Install terminal quit with output: 
[12:46:48.822] Initizing new exec server for ssh-remote+ztc0.tcmuk.local
[12:46:48.939] Using commit id "863d2581ecda6849923a2118d93a088b0745d9d6" and quality "stable" for server
[12:46:48.947] Install and start server if needed
[12:46:51.822] getPlatformForHost was canceled
[12:46:51.823] Exec server for ssh-remote+ztc0.tcmuk.local failed: Error: Connecting was canceled
[12:46:51.824] Error opening exec server for ssh-remote+ztc0.tcmuk.local: Error: Connecting was canceled
```

</p>
</details>

### Anything else?

Unsure if the message 'unsupported platform' means that I won't be able to use VSCode Remote Release when working with a NonStop system? For clarification, don't think this has ever worked so I'm happy to contribute to add support to this platform if need and help maintain and test new releases.

**Comment by roblourens** [comment]
What is Nonstop? We don't support this platform, and we aren't able to take contributions to Remote-SSH since it's not open source, sorry.

**Comment by the4amfriend** [comment]
@roblourens [NonStop](https://www.hpe.com/us/en/compute/nonstop-servers.html) is a POSIX compliant fault tolerant line of proprietary servers sold by HPE. In another comment, you'd asked about what it would take to support this new platform - I'm happy to help in that regard. 

Currently, the error message and the exit code indicate that you're expecting a known value for uname as referenced below - 

```
UNAME=$(uname -s)
case $UNAME in
	Linux) PLATFORM=linux;;
	Darwin) PLATFORM=macOS;;
	*)
		echo "Unsupported platform: $UNAME"
		fail_with_exitcode 35
		;;
esac
```
Updating the script to take NONSTOP_KERNEL as the result would help and I'd assume we could equate it to `PLATFORM=linux` and see if it would pass the test? I have access to NonStops and will be able to run the tests necessary and continue to help validate test cases.

**Comment by the4amfriend** [comment]
@roblourens Is there any additional information you need from me to reopen this and see if you can support NonStop as a platform?
