### ISSUE TITLE
Support SSH to HPE NonStop 

### ISSUE THREAD

**Issue by the4amfriend** [microsoft/vscode-remote-release#9667]
Based on further analysis from #9661, it looks like there is some incompatibility with VSCode's remote SSH implementation and that of HPE NonStop's. It would be appreciated if you could add support to our platform, happy to help in anyway we can. 

```
[12:46:46.931] "install" wrote data to terminal: "********"
[12:46:46.970] > 
[12:46:47.032] > Last Logon:  15 MAR 2024, 12:46    
> Last Unsuccessful Attempt: * NONE *
> Last Logon Failures: 0
[12:46:47.284] > 3f9302bd9b8e: running
[12:46:47.314] > grep: illegal option -- a
> usage: grep [-E | -F] [-c|-l|-q] [-insvxbhwy] [-p parasep] -e pattern_list...  
>         [-f pattern_file...] [file...]
> usage: grep [-E | -F] [-c|-l|-q] [-insvxbhwy] [-p parasep] [-e pattern_list...]
>         -f pattern_file... [file...]
> usage: grep [-E | -F] [-c|-l|-q] [-insvxbhwy] [-p parasep] pattern [file...]   
[12:46:47.329] > grep: illegal option -- a
> usage: grep [-E | -F] [-c|-l|-q] [-insvxbhwy] [-p parasep] -e pattern_list...  
>         [-f pattern_file...] [file...]
> usage: grep [-E | -F] [-c|-l|-q] [-insvxbhwy] [-p parasep] [-e pattern_list...]
>         -f pattern_file... [file...]
> usage: grep [-E | -F] [-c|-l|-q] [-insvxbhwy] [-p parasep] pattern [file...]   
[12:46:47.346] > Unsupported platform: NONSTOP_KERNEL
> 3f9302bd9b8e: start
> exitCode==35==
[12:46:47.375] > listeningOn====
> osReleaseId==NONSTOP_KERNEL==
> arch====
> vscodeArch====
> bitness====
> tmpDir==/tmp==
> platform====
> unpackResult====
> didLocalDownload==0==        
> downloadTime====
> installTime====
> serverStartTime====
> execServerToken==a1a11111-a11a-1111-111a-1a1111aa1a1a==
> 3f9302bd9b8e: end
[12:46:47.376] Received install output: 
exitCode==35==
listeningOn====
osReleaseId==NONSTOP_KERNEL==
arch====
vscodeArch====
bitness====
tmpDir==/tmp==
platform====
unpackResult====
didLocalDownload==0==        
downloadTime====
installTime====
serverStartTime====
execServerToken==a1a11111-a11a-1111-111a-1a1111aa1a1a==

[12:46:47.379] Failed to parse remote port from server output
[12:46:47.383] Resolver error: Error: 
	at g.Create (c:\Users\Shiva.Subramanian\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.0\out\extension.js:2:499734)
	at t.handleInstallOutput (c:\Users\Shiva.Subramanian\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.0\out\extension.js:2:497056)
	at t.tryInstall (c:\Users\Shiva.Subramanian\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.0\out\extension.js:2:620589)
	at async c:\Users\Shiva.Subramanian\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.0\out\extension.js:2:580447
	at async t.withShowDetailsEvent (c:\Users\Shiva.Subramanian\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.0\out\extension.js:2:583753)
	at async k (c:\Users\Shiva.Subramanian\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.0\out\extension.js:2:577412)
	at async t.resolve (c:\Users\Shiva.Subramanian\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.0\out\extension.js:2:581124)
	at async c:\Users\Shiva.Subramanian\.vscode\extensions\ms-vscode-remote.remote-ssh-0.109.0\out\extension.js:2:847283
[12:46:47.396] ------
```
Unable to track down where exactly the exit code 35 is set, is that from SSH itself?

**Comment by roblourens** [comment]
Please don't just open new duplicate issues. We can reopen the previous one if needed.
