### ISSUE TITLE
Failed to connect to the remote extension host server (Error: Connection error: Version mismatch, client refused.)

### ISSUE THREAD

**Issue by tlrdstd** [microsoft/vscode-remote-release#967]
Issue Type: <b>Bug</b>

Running VSCodium `Version 1.36.1 (1.36.1)` (installed today on my Mac via `brew cask install vscodium`), and `Remote-SSH 0.44.1`, I am unable to connect to my remote Amazon EC2 Linux host. Logs indicate that the connection is successfully established and the remote server installed into `~/.vscode-server-oss`. But all attempts to connect fail with `Failed to connect to the remote extension host server (Error: Connection error: Version mismatch, client refused.)`

I postulate this is because the remotely-installed server version appears to be `1.36.0-insider` while my locally running app is `1.36.1`. I tried munging `./bin/c3fe2d8acde04e579880413ae4622a1f551efdcc/bin/code-insiders` to use a different version, but it didn't help.

**Output/Remote-SSH**:

```
remote-ssh@0.44.1
darwin x64
SSH Resolver called for "ssh-remote+dev", attempt 1
SSH Resolver called for host: dev
Setting up SSH remote "dev"
Using commit id "c3fe2d8acde04e579880413ae4622a1f551efdcc" and quality "insider" for server
Testing ssh with ssh -V
ssh exited with code: 0
Got stderr from ssh: OpenSSH_7.4p1, LibreSSL 2.5.0
Install and start server if needed
> Running remote connection script
> Found existing installation at /home/distyler/.vscode-server-oss/bin/c3fe2d8acde04e579880413ae4622a1f551efdcc...
> Found running server...
>  
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
>  
> Checking server status with wget
> b8a84562-f8b1-4c64-9121-5e862df42f15==34189==38281==
"install" terminal command done
Received install output: b8a84562-f8b1-4c64-9121-5e862df42f15==34189==38281==
Server is listening on port 34189
Spawning tunnel with: "ssh" -L 127.0.0.1:34189:127.0.0.1:34189  -o ConnectTimeout=15   "dev" bash << 'EOSSH'
echo -e 'Connected to SSH Host - Please do not close this terminal' && sleep infinity
EOSSH
> Connected to SSH Host - Please do not close this terminal
Spawned SSH tunnel between local port 34189 and remote port 34189
Waiting for ssh tunnel to be ready
Tunneling remote port 34189 to local port 34189
Resolved "ssh-remote+dev" to "127.0.0.1:34189"
------
```

**Output/Log (Window)**:
```
[2019-07-12 12:40:11.648] [renderer5] [error] Connection error: Version mismatch, client refused.: Error: Connection error: Version mismatch, client refused.
    at f (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1556:180)
    at t.onControlMessage.o (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1555:147)
    at d.fire (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:760)
    at a (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:322:769)
    at e (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:322:815)
    at d.fire (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:760)
    at S._receiveMessage (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:331:718)
    at S._socketDisposables.push._socketReader.onMessage.e (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:328:981)
    at d.fire (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:760)
    at g.acceptChunk (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:325:532)
    at _register._socket.onData.e (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:324:869)
    at Socket.t (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:333:886)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
[2019-07-12 12:40:11.649] [renderer5] [error] Cannot read property 'extensions' of null: TypeError: Cannot read property 'extensions' of null
    at P.<anonymous> (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3912:841)
    at Generator.next (<anonymous>)
    at r (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:293)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-07-12 12:40:11.650] [renderer5] [error] Connection error: Version mismatch, client refused.: Error: Connection error: Version mismatch, client refused.
    at f (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1556:180)
    at t.onControlMessage.o (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1555:147)
    at d.fire (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:760)
    at a (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:322:769)
    at e (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:322:815)
    at d.fire (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:760)
    at S._receiveMessage (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:331:718)
    at S._socketDisposables.push._socketReader.onMessage.e (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:328:981)
    at d.fire (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:760)
    at g.acceptChunk (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:325:532)
    at _register._socket.onData.e (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:324:869)
    at Socket.t (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:333:886)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
```

**Developer Tools output**:
```
[Extension Host] debugger listening on port 61792
abstractExtensionService.ts:485 Extension 'ms-vscode-remote.remote-containers cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
updateEnableProposedApi @ abstractExtensionService.ts:485
abstractExtensionService.ts:485 Extension 'ms-vscode-remote.remote-ssh-explorer cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
updateEnableProposedApi @ abstractExtensionService.ts:485
abstractExtensionService.ts:485 Extension 'ms-vscode-remote.remote-wsl cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
updateEnableProposedApi @ abstractExtensionService.ts:485
2signService.ts:27 signer.sign: [object Object]
(anonymous) @ signService.ts:27
notificationsAlerts.ts:40 Failed to connect to the remote extension host server (Error: Connection error: Version mismatch, client refused.)
onDidNotificationChange @ notificationsAlerts.ts:40
extensionHostProcessManager.ts:76 Error received from starting extension host
_extensionHostProcessProxy._extensionHostProcessWorker.start.then.e @ extensionHostProcessManager.ts:76
extensionHostProcessManager.ts:77 Error: Connection error: Version mismatch, client refused.
    at f (remoteAgentConnection.ts:447)
    at i.onControlMessage.o (remoteAgentConnection.ts:179)
    at d.fire (event.ts:558)
    at a (ipc.net.ts:421)
    at e (ipc.net.ts:428)
    at d.fire (event.ts:558)
    at S._receiveMessage (ipc.net.ts:718)
    at S._socketDisposables.push._socketReader.onMessage.e (ipc.net.ts:578)
    at d.fire (event.ts:558)
    at g.acceptChunk (ipc.net.ts:236)
    at _register._socket.onData.e (ipc.net.ts:197)
    at Socket.t (ipc.net.ts:28)
    at Socket.emit (events.js:182)
    at addChunk (_stream_readable.js:283)
    at readableAddChunk (_stream_readable.js:264)
    at Socket.Readable.push (_stream_readable.js:219)
    at TCP.onStreamRead (internal/stream_base_commons.js:94)
_extensionHostProcessProxy._extensionHostProcessWorker.start.then.e @ extensionHostProcessManager.ts:77
log.ts:173   ERR Connection error: Version mismatch, client refused.: Error: Connection error: Version mismatch, client refused.
    at f (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1556:180)
    at t.onControlMessage.o (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1555:147)
    at d.fire (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:760)
    at a (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:322:769)
    at e (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:322:815)
    at d.fire (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:760)
    at S._receiveMessage (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:331:718)
    at S._socketDisposables.push._socketReader.onMessage.e (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:328:981)
    at d.fire (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:760)
    at g.acceptChunk (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:325:532)
    at _register._socket.onData.e (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:324:869)
    at Socket.t (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:333:886)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
log.ts:173   ERR Cannot read property 'extensions' of null: TypeError: Cannot read property 'extensions' of null
    at P.<anonymous> (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3912:841)
    at Generator.next (<anonymous>)
    at r (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:35:293)
    at process._tickCallback (internal/process/next_tick.js:68:7)
log.ts:173   ERR Connection error: Version mismatch, client refused.: Error: Connection error: Version mismatch, client refused.
    at f (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1556:180)
    at t.onControlMessage.o (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1555:147)
    at d.fire (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:760)
    at a (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:322:769)
    at e (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:322:815)
    at d.fire (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:760)
    at S._receiveMessage (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:331:718)
    at S._socketDisposables.push._socketReader.onMessage.e (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:328:981)
    at d.fire (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:79:760)
    at g.acceptChunk (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:325:532)
    at _register._socket.onData.e (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:324:869)
    at Socket.t (file:///Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:333:886)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
```

Extension version: 0.44.1
VS Code version: VSCodium 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-09T18:58:39.957Z)
OS version: Darwin x64 16.7.0
Fetching remote diagnostics for 'SSH: dev' failed: Connection error: Version mismatch, client refused.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--enable-proposed-api|
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'SSH: dev' failed: Connection error: Version mismatch, client refused.
</details>

**Comment by kieferrm** [comment]
@tlrdstd it seems you are running VSCodium. The VS Code server only supports official VS Code clients. See the license message of the server below. 

```
> *
> * Reminder: You may only use this software with Visual Studio family products,
> * as described in the license (https://go.microsoft.com/fwlink/?linkid=2077057)
> *
```

This is the license link: https://go.microsoft.com/fwlink/?linkid=2077057
