### ISSUE TITLE
[Remote-SSH Bug]: 404 Error // Unable to download VS code server update

### ISSUE THREAD

**Issue by abhisen7** [microsoft/vscode-remote-release#9702]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

```> Installing to /home/abhishek/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6...
> c7cee471fe97%%1%%
> Downloading with wget
[13:14:04.939] > wget download failed
> https://update.code.visualstudio.com/commit:863d2581ecda6849923a2118d93a088b0745d9d6/server-linux-legacy-x64/stable: 2024-03-26 15:14:05 ERROR 404: Not Found.
```

When I try to check for the [package](https://update.code.visualstudio.com/commit:863d2581ecda6849923a2118d93a088b0745d9d6/server-linux-legacy-x64/stable) via browser,  Chrome cannot find it either

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[13:19:16.233] stderr> debug1: Server host key: ssh-ed25519 SHA256:OiV+nF1gUQIUOxpG0HA22kO20h3mhF/qcSxcNQRlVsU
[13:19:16.759] stderr> Authenticated to 192.168.2.8 ([192.168.2.8]:22) using "publickey".
[13:19:17.086] > Welcome to Ubuntu 22.04.3 LTS (GNU/Linux 6.5.0-25-generic x86_64)
> 
>  * Documentation:  https://help.ubuntu.com
>  * Management:     https://landscape.canonical.com
>  * Support:        https://ubuntu.com/advantage
> 
> 1 device has a firmware upgrade available.
> Run `fwupdmgr get-upgrades` for more information.
> 
> 
> Expanded Security Maintenance for Applications is not enabled.
> 
> 109 updates can be applied immediately.
> To see these additional updates run: apt list --upgradable
> 
> 13 additional security updates can be applied with ESM Apps.
> Learn more about enabling ESM Apps service at https://ubuntu.com/esm
> 
> *** System restart required ***
> 
> 1 device has a firmware upgrade available.
> Run `fwupdmgr get-upgrades` for more information.
[13:19:17.172] > ready: 6f2072733918
[13:19:17.261] > Linux 6.5.0-25-generic #25~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Feb 20 16:09:15 UTC 2
[13:19:17.262] Platform: linux
[13:19:17.345] > /bin/bash
[13:19:17.346] Shell: bash
[13:19:17.346] Creating bash subshell inside "bash"
[13:19:17.438] > bash version:  5.1.16(1)-release
[13:19:17.485] > bash version:  5.1.16(1)-release
[13:19:17.612] > 6f2072733918: running
> Acquiring lock on /home/abhishek/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/vscode-remote-lock.abhishek.863d2581ecda6849923a2118d93a088b0745d9d6
> Installing to /home/abhishek/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6...
> 6f2072733918%%1%%
> Downloading with wget
[13:19:17.651] > wget download failed
> https://update.code.visualstudio.com/commit:863d2581ecda6849923a2118d93a088b0745d9d6/server-linux-legacy-x64/stable: 2024-03-26 15:19:17 ERROR 404: Not Found.
> printenv:
[13:19:17.653] >     SHELL=/bin/bash
>     LC_ADDRESS=en_US.UTF-8
>     LC_NAME=en_US.UTF-8
>     LC_MONETARY=en_US.UTF-8
>     PWD=/home/abhishek/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6
>     LOGNAME=abhishek
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/home/abhishek
>     LANG=en_US.UTF-8
>     LC_PAPER=en_US.UTF-8
>     VSCODE_AGENT_FOLDER=/home/abhishek/.vscode-server
>     SSH_CONNECTION=192.168.6.176 49960 192.168.2.8 22
>     XDG_SESSION_CLASS=user
>     LC_IDENTIFICATION=en_US.UTF-8
>     USER=abhishek
>     SHLVL=1
>     LC_TELEPHONE=en_US.UTF-8
>     LC_MEASUREMENT=en_US.UTF-8
>     XDG_SESSION_ID=2411
>     PAPERSIZE=letter
>     XDG_RUNTIME_DIR=/run/user/1000
>     SSH_CLIENT=192.168.6.176 49960 22
>     LC_TIME=en_US.UTF-8
>     XDG_DATA_DIRS=/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop
>     PATH=/home/abhishek/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
>     LC_NUMERIC=en_US.UTF-8
>     OLDPWD=/home/abhishek
>     _=/usr/bin/printenv
> Trigger local server download
> 6f2072733918:trigger_server_download
> artifact==server-linux-legacy-x64==
> destFolder==/home/abhishek/.vscode-server/bin/==
[13:19:17.655] > destFolder2==/863d2581ecda6849923a2118d93a088b0745d9d6/vscode-server.tar.gz==
> 6f2072733918:trigger_server_download_end
> Waiting for client to transfer server archive...
> Waiting for /home/abhishek/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/vscode-server.tar.gz.done and vscode-server.tar.gz to exist
[13:19:17.655] Got request to download on client for {"artifact":"server-linux-legacy-x64","destPath":"/home/abhishek/.vscode-server/bin//863d2581ecda6849923a2118d93a088b0745d9d6/vscode-server.tar.gz"}
[13:19:17.655] Downloading VS Code server locally...
[13:19:17.699] >  
[13:19:17.939] Terminating local server
[13:19:17.941] Resolver error: Error: Failed to download VS Code Server (Server returned 404)
	at g.Create (/Users/absen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.2024032215/out/extension.js:2:499734)
	at /Users/absen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.2024032215/out/extension.js:2:550341
	at async t.downloadAndCopyToHost (/Users/absen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.2024032215/out/extension.js:2:549841)
	at async /Users/absen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.2024032215/out/extension.js:2:557740
	at async e (/Users/absen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.2024032215/out/extension.js:2:557855)
	at async /Users/absen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.2024032215/out/extension.js:2:580101
	at async t.withShowDetailsEvent (/Users/absen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.2024032215/out/extension.js:2:583760)
	at async /Users/absen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.2024032215/out/extension.js:2:554897
	at async T (/Users/absen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.2024032215/out/extension.js:2:552948)
	at async t.resolveWithLocalServer (/Users/absen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.2024032215/out/extension.js:2:554437)
	at async k (/Users/absen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.2024032215/out/extension.js:2:577318)
	at async t.resolve (/Users/absen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.2024032215/out/extension.js:2:581131)
	at async /Users/absen/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.2024032215/out/extension.js:2:847299
[13:19:17.942] Local server exit: 15
[13:19:17.944] ------
```

</p>
</details>

**Comment by connor4312** [comment]
How did you install Remote - SSH? You appear to have somehow gotten a version on VS Code Stable (1.87) that is constrained to only work on 1.88 and above.

**Comment by abhisen7** [comment]
Hi, I resolved the issue after explicitly setting `Remote.SSH.Local Server Download` to `Always` from `Auto`, and previously deleting the `863d2581ecda6849923a2118d93a088b0745d9d6` folder on the remote server.

**Comment by bariscankurtkaya** [comment]
Hi @connor4312! 

I am also facing this issue currently. Unfortunately, the solution mentioned earlier did not work for me.

I deleted the `863d2581ecda6849923a2118d93a088b0745d9d6` folder on my server and verified that the `Remote.SSH.Local Server Download` setting in VSCode is set to `auto`.

Here are my VSCode and Remote SSH versions:

```
Version: 1.87.2 (Universal)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:21:31.043Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.4.0
```

```
Name: Remote - SSH
Id: ms-vscode-remote.remote-ssh
Description: Open any folder on a remote machine using SSH and take advantage of VS Code's full feature set.
Version: 0.110.2024032215
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh
```

**Comment by bariscankurtkaya** [comment]
> Hi @connor4312!
> 
> I am also facing this issue currently. Unfortunately, the solution mentioned earlier did not work for me.
> 
> I deleted the `863d2581ecda6849923a2118d93a088b0745d9d6` folder on my server and verified that the `Remote.SSH.Local Server Download` setting in VSCode is set to `auto`.
> 
> Here are my VSCode and Remote SSH versions:
> 
> ```
> Version: 1.87.2 (Universal)
> Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
> Date: 2024-03-08T15:21:31.043Z
> Electron: 27.3.2
> ElectronBuildId: 26836302
> Chromium: 118.0.5993.159
> Node.js: 18.17.1
> V8: 11.8.172.18-electron.0
> OS: Darwin arm64 23.4.0
> ```
> 
> ```
> Name: Remote - SSH
> Id: ms-vscode-remote.remote-ssh
> Description: Open any folder on a remote machine using SSH and take advantage of VS Code's full feature set.
> Version: 0.110.2024032215
> Publisher: Microsoft
> VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh
> ```

Quick update: While I was writing about the Remote SSH version inside the message, I realized that I was using a pre-release version. I downgraded to another release version, and it is working now.

SSH Version now:
```
Name: Remote - SSH
Id: ms-vscode-remote.remote-ssh
Description: Open any folder on a remote machine using SSH and take advantage of VS Code's full feature set.
Version: 0.108.0
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh
```

**Comment by DuffyScottC** [comment]
I was experiencing the same issue, for the same reason as @bariscankurtkaya, and their solution worked for me (downgrade to release version). Not sure how VSCode was configured to be using the pre-release version, I didn't tell it to do that.

**Comment by dawin2015** [comment]
same problem
` Failed to download VS Code Server (Server returned 404).`

**Comment by mjunker** [comment]
Same issue here

Resolver error: Error: Failed to download VS Code Server (Server returned 404)

**Comment by MoJo2600** [comment]
here as well 

```
2024-04-10 14:33:59 ERROR 404: Not Found.

ERROR: Failed to download https://update.code.visualstudio.com/commit:863d2581ecda6849923a2118d93a088b0745d9d6/server-linux-legacy-x64/stable```

**Comment by arun-airtory** [comment]
I was able to get it working by changing the **Remote SSH** extension from `pre-release` to `release`.
