### ISSUE TITLE
Failed to parse remote port from server output when ssh into CentOS Linux 7

### ISSUE THREAD

**Issue by robotmir** [microsoft/vscode-remote-release#9762]
I am trying to ssh into CentOS Linux 7 from MacOS Sonoma. Everything worked fine up until around 2 weeks ago. Suddenly, the following log is printed out along with error message, "Could not establish connection to "mg"."

So far, I have tried
- changing login shell from /bin/zsh to /bin/bash
- disabling firewall
- downgrading VSCode to 1.76.2 along with Remote - SSH
- changing remote.SSH.useLocalServer
- reinstalled VSCode
- deleted .vscode-server from server side
- "Remote-SSH: Kill VS Code Server on Host..."
  - which results in "Failed to kill VS Code Server on mg."
- "Remote-SSH: Uninstall VS Code Server from Host..."
  - which results in "Command 'Remote-SSH: Uninstall VS Code Server from Host...' resulted in an error", "Failed to run command"

Also, I was able to ssh into the same server from Windows 11 VSCode through Parallels using the same network.

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[12:50:45.778] Log Level: 2
[12:50:45.783] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a226d673231312845434534333729227d", attempt 1
[12:50:45.783] "remote.SSH.useLocalServer": true
[12:50:45.783] "remote.SSH.useExecServer": true
[12:50:45.783] "remote.SSH.path": undefined
[12:50:45.783] "remote.SSH.configFile": undefined
[12:50:45.783] "remote.SSH.useFlock": true
[12:50:45.783] "remote.SSH.lockfilesInTmp": false
[12:50:45.783] "remote.SSH.localServerDownload": auto
[12:50:45.783] "remote.SSH.remoteServerListenOnSocket": false
[12:50:45.784] "remote.SSH.showLoginTerminal": false
[12:50:45.784] "remote.SSH.defaultExtensions": []
[12:50:45.784] "remote.SSH.loglevel": 2
[12:50:45.784] "remote.SSH.enableDynamicForwarding": true
[12:50:45.784] "remote.SSH.enableRemoteCommand": false
[12:50:45.785] "remote.SSH.serverPickPortsFromRange": {}
[12:50:45.785] "remote.SSH.serverInstallPath": {}
[12:50:45.787] VS Code version: 1.88.0
[12:50:45.787] Remote-SSH version: remote-ssh@0.110.1
[12:50:45.787] darwin arm64
[12:50:45.788] SSH Resolver called for host: mg
[12:50:45.788] Setting up SSH remote "mg"
[12:50:45.789] Acquiring local install lock: /var/folders/5r/g63bjx35121b0nrbk9by4fjm0000gn/T/vscode-remote-ssh-b443a579-install.lock
[12:50:45.790] Looking for existing server data file at /Users/username/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-b443a579-5c3e652f63e798a5ac2f31ffd0d863669328dc4c-0.110.1-es/data.json
[12:50:45.791] Using commit id "5c3e652f63e798a5ac2f31ffd0d863669328dc4c" and quality "stable" for server
[12:50:45.793] Install and start server if needed
[12:50:45.795] PATH: /Users/username/anaconda3/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin
[12:50:45.795] Checking ssh with "ssh -V"
[12:50:45.802] > OpenSSH_9.6p1, LibreSSL 3.3.6

[12:50:45.804] askpass server listening on /var/folders/5r/g63bjx35121b0nrbk9by4fjm0000gn/T/vscode-ssh-askpass-b253072f9471ef056a7c779224d1826c98e719c2.sock
[12:50:45.804] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/5r/g63bjx35121b0nrbk9by4fjm0000gn/T/vscode-ssh-askpass-09326f4d01ae73d8bd94c6ac852eb45b3f90ea55.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","52423","-o","ConnectTimeout=15","mg"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/username/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-b443a579-5c3e652f63e798a5ac2f31ffd0d863669328dc4c-0.110.1-es/data.json"}
[12:50:45.804] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.rjpbmb6HJ2/Listeners","SHELL":"/bin/bash","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"","VSCODE_SSH_ASKPASS_MAIN":"/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/5r/g63bjx35121b0nrbk9by4fjm0000gn/T/vscode-ssh-askpass-b253072f9471ef056a7c779224d1826c98e719c2.sock"}
[12:50:45.804] Spawned 18493
[12:50:45.896] > local-server-1> Running ssh connection command: ssh -v -T -D 52423 -o ConnectTimeout=15 mg
[12:50:45.897] > local-server-1> Spawned ssh, pid=18497
[12:50:45.900] stderr> hostname contains invalid characters
[12:50:45.901] > local-server-1> ssh child died, shutting down
[12:50:45.903] Local server exit: 0
[12:50:45.903] Received install output: local-server-1> Running ssh connection command: ssh -v -T -D 52423 -o ConnectTimeout=15 mg
local-server-1> Spawned ssh, pid=18497
hostname contains invalid characters
local-server-1> ssh child died, shutting down

[12:50:45.904] Failed to parse remote port from server output
[12:50:45.905] Resolver error: Error: 
	at g.Create (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:499181)
	at t.handleInstallOutput (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:496503)
	at e (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:557639)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:579548
	at async t.withShowDetailsEvent (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:583207)
	at async /Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:554344
	at async T (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:552395)
	at async t.resolveWithLocalServer (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:553884)
	at async k (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:576765)
	at async t.resolve (/Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:580578)
	at async /Users/username/.vscode/extensions/ms-vscode-remote.remote-ssh-0.110.1/out/extension.js:2:846687
[12:50:45.908] ------




```

</p>
</details>

**Comment by robotmir** [comment]
I found out the issue. We can not have parenthesis in the name of the Host.
