### ISSUE TITLE
Dockerfile with image from scratch fails to build from devcontainer.json

### ISSUE THREAD

**Issue by gerwinjansen** [microsoft/vscode-remote-release#9799]
VSCode Version: 1.88.1
Local OS Version: Windows 10 Pro 22H2
Remote OS Version: docker container
Remote Extension/Connection Type: Containers

## Steps to Reproduce:
Given this `Dockerfile`
```dockerfile
FROM wordpress:php8.1-apache as wordpress-stripped

RUN set -eux; \
    rm -Rf \
    /usr/local/bin/docker-entrypoint.sh \
    /usr/src \
    /var/www/*


FROM scratch as wordpress-devcontainer
COPY --from=wordpress-stripped / /
ENV PHP_INI_DIR /usr/local/etc/php
ENV APACHE_CONFDIR /etc/apache2
ENV APACHE_ENVVARS $APACHE_CONFDIR/envvars
EXPOSE 80
WORKDIR /var/www
CMD ["apache2-foreground"]
```
And this `.devcontainer.json` file
```json
{
    "build": { "dockerfile": "Dockerfile" }
}
```
I get this error:
![image](https://github.com/microsoft/vscode-remote-release/assets/13243946/e05adbb0-bcf0-44ed-887c-cd7c8925ae67)

## Workaround
Change the `.devcontainer.json` file to this:
```json
{
    "initializeCommand": "docker build --tag wordpress-devcontainer:latest .",
    "image": "wordpress-devcontainer:latest"
}
```

## Logs
full logfile: [remoteContainers-2024-04-19T19-16-59.736Z.log](https://github.com/microsoft/vscode-remote-release/files/15045177/remoteContainers-2024-04-19T19-16-59.736Z.log)

```
[2024-04-19T19:17:05.067Z] Start: Run: docker inspect --type image scratch
[2024-04-19T19:17:05.371Z] Stop (304 ms): Run: docker inspect --type image scratch
[2024-04-19T19:17:05.375Z] Loading 53 extra certificates from C:\Users\Gerwin\AppData\Local\Temp\vsch\certificates-80a0b5eac2ebcc7d1b062f7bbb7841837a07131ceefa857109ba5977eec4fae9.pem.
[2024-04-19T19:17:05.783Z] Start: Run: docker-credential-desktop get
[2024-04-19T19:17:05.972Z] Stop (189 ms): Run: docker-credential-desktop get
[2024-04-19T19:17:07.241Z] Error fetching image details: No manifest found for docker.io/library/scratch.
[2024-04-19T19:17:07.242Z] Start: Run: docker pull scratch
[2024-04-19T19:17:07.675Z] 
[2024-04-19T19:17:07.740Z] Using default tag: latest
[2024-04-19T19:17:07.908Z] Error response from daemon: 'scratch' is a reserved name
[2024-04-19T19:17:08.001Z] Stop (759 ms): Run: docker pull scratch
[2024-04-19T19:17:08.004Z] []
[2024-04-19T19:17:08.004Z] Error response from daemon: No such image: scratch:latest

[2024-04-19T19:17:08.006Z] Error: Command failed: docker inspect --type image scratch
[2024-04-19T19:17:08.006Z]     at htA (c:\Users\Gerwin\.vscode\extensions\ms-vscode-remote.remote-containers-0.354.0\dist\spec-node\devContainersSpecCLI.js:464:1260)
[2024-04-19T19:17:08.006Z]     at kH (c:\Users\Gerwin\.vscode\extensions\ms-vscode-remote.remote-containers-0.354.0\dist\spec-node\devContainersSpecCLI.js:464:1002)
[2024-04-19T19:17:08.006Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-04-19T19:17:08.006Z]     at async UtA (c:\Users\Gerwin\.vscode\extensions\ms-vscode-remote.remote-containers-0.354.0\dist\spec-node\devContainersSpecCLI.js:481:3692)
[2024-04-19T19:17:08.007Z]     at async $C (c:\Users\Gerwin\.vscode\extensions\ms-vscode-remote.remote-containers-0.354.0\dist\spec-node\devContainersSpecCLI.js:481:4807)
[2024-04-19T19:17:08.007Z]     at async QrA (c:\Users\Gerwin\.vscode\extensions\ms-vscode-remote.remote-containers-0.354.0\dist\spec-node\devContainersSpecCLI.js:661:13255)
[2024-04-19T19:17:08.007Z]     at async urA (c:\Users\Gerwin\.vscode\extensions\ms-vscode-remote.remote-containers-0.354.0\dist\spec-node\devContainersSpecCLI.js:661:12996)
```

**Comment by Fydon** [comment]
This is related to https://github.com/devcontainers/cli/issues/239

**Comment by okwilkins** [comment]
Ran into this too. The workaround is to use a local alias (which is just `scratch` underneath) and force VS Code to use it via a devcontainer specific override, while keeping production defaults pure.

1. Create the alias in `devcontainer.json`. Use `initializeCommand` to create a local tag before the container starts and add a secondary compose file to handle the override:

```json
"initializeCommand": "echo 'FROM scratch' | docker build -t scratch-alias -",
"dockerComposeFile": [
    "../docker-compose.yaml",
    "./docker-compose.devcontainer.yaml"
]
```


2. Override the arg in `.devcontainer/docker-compose.devcontainer.yaml`. This injects the local alias into the build process specifically for VS Code:

```yaml
services:
  your-service-name:
    build:
      args:
        BASE_IMAGE: scratch-alias
```

3. Default to scratch in Dockerfile. This ensures standard docker build commands for production still use scratch by default, but VS Code picks up the alias:


```dockerfile
ARG BASE_IMAGE=scratch
FROM ${BASE_IMAGE}
```
