### ISSUE TITLE
[Remote-SSH Bug]: Command 'Python: Restart Language Server' resulted in an error (command 'python.analysis.restartLanguageServer' not found) 

### ISSUE THREAD

**Issue by 731315163** [microsoft/vscode-remote-release#9832]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [x] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

All remote plugins of vscode can't work properly sometimes, and sometimes they can.

### Expected Behavior

The Python plugin can correctly select the virtual environment interpreter.

### Steps To Reproduce

1. open vscode
2. waiting
3. The Python remote plugins are working properly, or the plugins are not working.

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[11:30:47.688] Log Level: 2
[11:30:47.709] SSH Resolver called for "ssh-remote+123.58.198.95", attempt 1
[11:30:47.709] "remote.SSH.useLocalServer": false
[11:30:47.709] "remote.SSH.useExecServer": true
[11:30:47.710] "remote.SSH.showLoginTerminal": false
[11:30:47.710] "remote.SSH.remotePlatform": {"123.58.198.95":"linux"}
[11:30:47.710] "remote.SSH.path": undefined
[11:30:47.710] "remote.SSH.configFile": undefined
[11:30:47.710] "remote.SSH.useFlock": true
[11:30:47.710] "remote.SSH.lockfilesInTmp": true
[11:30:47.710] "remote.SSH.localServerDownload": always
[11:30:47.711] "remote.SSH.remoteServerListenOnSocket": true
[11:30:47.712] "remote.SSH.showLoginTerminal": false
[11:30:47.712] "remote.SSH.defaultExtensions": []
[11:30:47.712] "remote.SSH.loglevel": 2
[11:30:47.712] "remote.SSH.enableDynamicForwarding": true
[11:30:47.712] "remote.SSH.enableRemoteCommand": false
[11:30:47.712] "remote.SSH.serverPickPortsFromRange": {}
[11:30:47.712] "remote.SSH.serverInstallPath": {}
[11:30:47.715] VS Code version: 1.88.1
[11:30:47.715] Remote-SSH version: remote-ssh@0.110.1
[11:30:47.716] win32 x64
[11:30:47.722] SSH Resolver called for host: 123.58.198.95
[11:30:47.722] Setting up SSH remote "123.58.198.95"
[11:30:47.726] Using commit id "e170252f762678dec6ca2cc69aba1570769a5d39" and quality "stable" for server
[11:30:47.729] Install and start server if needed
[11:30:47.733] Checking ssh with "C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe -V"
[11:30:47.739] Got error from ssh: spawn C:\Program Files\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[11:30:47.739] Checking ssh with "C:\Program Files\PerkinElmerInformatics\ChemOffice\ChemScript\Lib\ssh.exe -V"
[11:30:47.741] Got error from ssh: spawn C:\Program Files\PerkinElmerInformatics\ChemOffice\ChemScript\Lib\ssh.exe ENOENT
[11:30:47.741] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[11:30:47.743] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[11:30:47.743] Checking ssh with "C:\Windows\ssh.exe -V"
[11:30:47.745] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[11:30:47.745] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[11:30:47.747] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[11:30:47.747] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[11:30:47.749] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[11:30:47.755] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[11:30:47.861] > OpenSSH_for_Windows_8.1p1, 
[11:30:47.862] > LibreSSL 3.0.2

[11:30:47.867] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 60131 "123.58.198.95" bash
[11:30:47.871] Terminal shell path: C:\Windows\System32\cmd.exe
[11:30:48.634] > ]0;C:\Windows\System32\cmd.exe
[11:30:48.636] Got some output, clearing connection timeout
[11:30:54.229] > d665522f9dde: running
[11:30:54.244] > Found existing installation at /root/.vscode-server...
> Starting VS Code CLI... "/root/.vscode-server/code-e170252f762678dec6ca2cc69aba1
> 570769a5d39" command-shell --cli-data-dir "/root/.vscode-server/cli" --on-port -
> -parent-process-id 495957 &> "/root/.vscode-server/.cli.e170252f762678dec6ca2cc6
> 9aba1570769a5d39.log" < /dev/null
> printenv:
>     SHELL=/bin/bash
>     PYENV_SHELL=bash
>     PWD=/root
>     LOGNAME=root
>     XDG_SESSION_TYPE=tty
>     MOTD_SHOWN=pam
>     HOME=/root
>     LANG=en_US.UTF-8
>     VSCODE_AGENT_FOLDER=/root/.vscode-server
>     SSH_CONNECTION=124.118.130.8 60135 10.53.61.243 22
>     XDG_SESSION_CLASS=user
>     LESSOPEN=||/usr/bin/lesspipe.sh %s
>     USER=root
>     SHLVL=0
>     XDG_SESSION_ID=202
>     XDG_RUNTIME_DIR=/run/user/0
>     SSH_CLIENT=124.118.130.8 60135 22
>     PYENV_ROOT=/root/.pyenv
>     DEBUGINFOD_URLS=https://debuginfod.centos.org/
>     which_declare=declare -f
>     XDG_DATA_DIRS=/root/.local/share/flatpak/exports/share:/var/lib/flatpak/expo
> rts/share:/usr/local/share:/usr/share
>     PATH=/root/.pyenv/shims:/root/.pyenv/bin:/root/.local/bin:/root/bin:/usr/loc
> al/sbin:/usr/local/bin:/usr/sbin:/usr/bin
>     DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/0/bus
>     BASH_FUNC_which%%=() {  ( alias;
>      eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-fun
> ctions --show-tilde --show-dot $@
>     }
>     _=/usr/bin/printenv
> Removing old logfile at /root/.vscode-server/.cli.e170252f762678dec6ca2cc69aba15
> 70769a5d39.log
> Spawned remote CLI: 496076
[11:30:54.250] > 
[11:30:54.261] > Waiting for server log...
[11:30:54.277] > 
[11:30:54.307] > d665522f9dde: start
> SSH_AUTH_SOCK====
> DISPLAY====
> listeningOn==127.0.0.1:38893==
> osReleaseId==rocky==
> arch==x86_64==
> vscodeArch==x64==
[11:30:54.324] > 
[11:30:54.698] > bitness==64==
> tmpDir==/run/user/0==
> platform==linux==
> unpackResult====
> didLocalDownload==0==
> downloadTime====
> installTime====
> serverStartTime==48==
> execServerToken==1aa1aa11-a11a-1aa1-a1a1-1111a1aaa111==
> d665522f9dde: end
[11:30:54.698] Received install output: 
SSH_AUTH_SOCK====
DISPLAY====
listeningOn==127.0.0.1:38893==
osReleaseId==rocky==
arch==x86_64==
vscodeArch==x64==
bitness==64==
tmpDir==/run/user/0==
platform==linux==
unpackResult====
didLocalDownload==0==
downloadTime====
installTime====
serverStartTime==48==
execServerToken==1aa1aa11-a11a-1aa1-a1a1-1111a1aaa111==

[11:30:54.698] Remote server is listening on port 38893
[11:30:54.698] Parsed server configuration: {"serverConfiguration":{"remoteListeningOn":{"port":38893},"osReleaseId":"rocky","arch":"x86_64","sshAuthSock":"","display":"","tmpDir":"/run/user/0","platform":"linux","execServerToken":"1aa1aa11-a11a-1aa1-a1a1-1111a1aaa111"},"serverStartTime":48,"installUnpackCode":""}
[11:30:54.704] Starting forwarding server. local port 60166 -> socksPort 60131 -> remotePort 38893
[11:30:54.706] Forwarding server listening on port 60166
[11:30:54.707] Waiting for ssh tunnel to be ready
[11:30:54.710] Tunneled port 38893 to local port 60166
[11:30:54.710] Resolved "ssh-remote+123.58.198.95" to "port 60166"
[11:30:54.713] Initizing new exec server for ssh-remote+123.58.198.95
[11:30:54.713] Resolving exec server at port 60166
[11:30:54.748] [Forwarding server port 60166] Got connection 0
[11:30:54.758] [Forwarding server port 60166] Got connection 1
[11:30:56.129] Exec server for ssh-remote+123.58.198.95 created and cached
[11:30:56.141] ------




[11:30:56.639] [server] Checking /root/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/log.txt and /root/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/pid.txt for a running server...
[11:30:56.640] [server] Found running server (pid=493561)
```

</p>
</details>

### Anything else?

![Snipaste_2024-04-29_12-03-00](https://github.com/microsoft/vscode-remote-release/assets/15324820/07e96007-01b1-4e75-a680-98b0ebc2fa4e)

**Comment by 731315163** [comment]
**Extension Host log**
`
2024-04-29 16:32:21.942 [error] Error: command 'remote-internal.setActiveFolders' not found
    at S.n (vscode-file://vscode-app/c:/Users/q7313/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1602:23049)
    at S.executeCommand (vscode-file://vscode-app/c:/Users/q7313/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1602:22978)
2024-04-29 16:33:18.021 [info] Extension host terminating: renderer closed the MessagePort
2024-04-29 16:33:18.032 [error] Canceled: Canceled
	at new O (c:\Users\q7313\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:142:46998)
	at u.U (c:\Users\q7313\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:149:5539)
	at F.<computed>.T.charCodeAt.F.<computed> (c:\Users\q7313\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:149:2993)
	at d.g (c:\Users\q7313\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:186335)
	at d.executeCommand (c:\Users\q7313\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:185773)
	at E.registerCommand.description (c:\Users\q7313\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:185097)
	at d.h (c:\Users\q7313\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:186874)
	at d.g (c:\Users\q7313\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:185866)
	at d.executeCommand (c:\Users\q7313\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:152:185773)
	at Object.executeCommand (c:\Users\q7313\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:162:22785)
	at t.shutdown (c:\Users\q7313\.vscode\extensions\ms-vscode-remote.remote-ssh-0.110.1\out\extension.js:2:582708)
	at e.deactivate (c:\Users\q7313\.vscode\extensions\ms-vscode-remote.remote-ssh-0.110.1\out\extension.js:2:849844)
	at m.eb (c:\Users\q7313\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:9772)
	at c:\Users\q7313\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:7816
	at Array.map (<anonymous>)
	at m.$ (c:\Users\q7313\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:7803)
	at m.terminate (c:\Users\q7313\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:8077)
	at o.terminate (c:\Users\q7313\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:162:1513)
	at t (c:\Users\q7313\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:175:9917)
	at MessagePortMain.<anonymous> (c:\Users\q7313\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:175:6342)
	at MessagePortMain.emit (node:events:517:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285) setContext undefined`

**Comment by 731315163** [comment]
Pty Host (Remote) log
`2024-04-29 15:35:02.776 [warning] Shell integration cannot be enabled for executable "/bin/sh" and args ["-c","wget --version > /dev/null\nif [ $? -eq 0 ]\nthen\n\twget --connect-timeout=7 --tries=1 --dns-timeout=7 -q --header='Metadata-Flavor:Google' -O - http://metadata.google.internal/computeMetadata/v1/instance/id\nelse\n\tcurl --version > /dev/null\n\tif [ $? -eq 0 ]\n\tthen\n\t\tcurl --connect-timeout 7 -s --header='Metadata-Flavor:Google' http://metadata.google.internal/computeMetadata/v1/instance/id\n\tfi\nfi\nexit 0"]
2024-04-29 15:35:23.311 [error] [RPC Response] PtyService#updateTitle Could not find pty on pty host`

**Comment by 731315163** [comment]
Server log
`2024-04-29 15:32:50.119 **[error] CodeExpectedError**: Could not find pty on pty host
    at D.U (/root/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:32471)
    at D.updateIcon (/root/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:27683)
    at j.<computed> (/root/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:47:22875)
    at Object.call (/root/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:36:5137)
    at l.s (/root/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:34:5145)
    at l.q (/root/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:34:4647)
    at n.value (/root/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:34:4045)
    at t.y (/root/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:29:665)
    at t.fire (/root/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:29:882)
    at process.ue (/root/.vscode-server/cli/servers/Stable-e170252f762678dec6ca2cc69aba1570769a5d39/server/out/vs/platform/terminal/node/ptyHostMain.js:25:10030)
    at process.emit (node:events:517:28)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
2024-04-29 15:33:05.300 **[info] [<unknown>][1c600120][ExtensionHostConnection]** The client has reconnected.
2024-04-29 15:33:31.837 **[info] [<unknown>][1251248c][ExtensionHostConnection]** New connection established.
2024-04-29 15:33:31.838 **[info] [<unknown>][b19d37e3][ManagementConnection]** New connection established.
2024-04-29 15:33:31.847 **[info] [<unknown>][1251248c][ExtensionHostConnection]** <505770> Launched Extension Host Process.
2024-04-29 15:35:24.313 **[error] CodeExpectedError:** Could not find pty on pty host`

**Comment by roblourens** [comment]
Please file on the Python extension repo
