### ISSUE TITLE
Default Extensions If Installed Locally: Install pre-release if local extension is pre-release

### ISSUE THREAD

**Issue by epicwhale** [microsoft/vscode-remote-release#9840]
- VS Code Version:
Version: 1.89.0-insider
Commit: 063d715c4504380317f9ca8eefc602d71e56adb5
Date: 2024-04-19T06:04:15.360Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

Steps to Reproduce:

1. Ask a question in Copilot chat inside dev container
2. Error response: r.report is not a function

<img width="548" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/670655/9ca98f55-fa1d-43e1-b15e-d07c08355fbb">

```
2024-04-19 13:28:37.183 [info] [streamChoices] request done: requestId: [c1905c88-bb37-44ee-acbf-094e6793ae71] responseId: [c1905c88-bb37-44ee-acbf-094e6793ae71] model deployment ID: [wc154981b18df]
2024-04-19 13:28:37.186 [info] [extension] TypeError: r.report is not a function
    at Object.report (/root/.vscode-server-insiders/extensions/github.copilot-chat-0.14.1/dist/extension.js:855:1767)
    at iE.applyDeltaToProgress (/root/.vscode-server-insiders/extensions/github.copilot-chat-0.14.1/dist/extension.js:854:1498)
    at /root/.vscode-server-insiders/extensions/github.copilot-chat-0.14.1/dist/extension.js:854:2590
    at /root/.vscode-server-insiders/extensions/github.copilot-chat-0.14.1/dist/extension.js:854:2343
    at Array.forEach (<anonymous>)
    at iE.checkForKeyWords (/root/.vscode-server-insiders/extensions/github.copilot-chat-0.14.1/dist/extension.js:854:2331)
    at iE.applyDelta (/root/.vscode-server-insiders/extensions/github.copilot-chat-0.14.1/dist/extension.js:854:2525)
    at iE.doProcessResponse (/root/.vscode-server-insiders/extensions/github.copilot-chat-0.14.1/dist/extension.js:854:1312)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-04-19 13:30:14.149 [info] [asyncCompute] Computing async parser based result took longer than 600ms
2024-04-19 13:30:14.186 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-04-19 13:30:14.186 [info] [chat fetch] modelMaxPromptTokens 3072
2024-04-19 13:30:14.186 [info] [chat fetch] modelMaxResponseTokens 4096
2024-04-19 13:30:14.186 [info] [chat fetch] chat model gpt-4
2024-04-19 13:30:15.494 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1306 ms
2024-04-19 13:30:27.580 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-04-19 13:30:27.584 [info] [streamChoices] request done: requestId: [77902308-49d0-4956-b650-efed7aa68a79] responseId: [77902308-49d0-4956-b650-efed7aa68a79] model deployment ID: [wc154981b18df]
2024-04-19 13:30:27.616 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-04-19 13:30:27.616 [info] [chat fetch] modelMaxPromptTokens 7168
2024-04-19 13:30:27.616 [info] [chat fetch] modelMaxResponseTokens 4096
2024-04-19 13:30:27.616 [info] [chat fetch] chat model gpt-3.5-turbo
2024-04-19 13:30:28.105 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 487 ms
2024-04-19 13:30:28.189 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-04-19 13:30:28.190 [info] [streamChoices] request done: requestId: [95b79e11-2f5b-4ce3-8e7d-febf9e717077] responseId: [95b79e11-2f5b-4ce3-8e7d-febf9e717077] model deployment ID: [x4dff5e5d11fc]
2024-04-19 13:30:37.144 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-04-19 13:30:37.144 [info] [chat fetch] modelMaxPromptTokens 3072
2024-04-19 13:30:37.144 [info] [chat fetch] modelMaxResponseTokens 4096
2024-04-19 13:30:37.144 [info] [chat fetch] chat model gpt-4
2024-04-19 13:30:38.262 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1114 ms
2024-04-19 13:30:44.955 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-04-19 13:30:44.957 [info] [streamChoices] request done: requestId: [1c51c203-2ba0-4083-bdd9-ff20a73395ba] responseId: [1c51c203-2ba0-4083-bdd9-ff20a73395ba] model deployment ID: [wc154981b18df]
2024-04-19 13:30:44.966 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-04-19 13:30:44.966 [info] [chat fetch] modelMaxPromptTokens 7168
2024-04-19 13:30:44.966 [info] [chat fetch] modelMaxResponseTokens 4096
2024-04-19 13:30:44.966 [info] [chat fetch] chat model gpt-3.5-turbo
2024-04-19 13:30:45.844 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 875 ms
2024-04-19 13:30:45.862 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-04-19 13:30:45.864 [info] [streamChoices] request done: requestId: [66159c1f-b531-41f6-b1e2-2410cc9822f9] responseId: [66159c1f-b531-41f6-b1e2-2410cc9822f9] model deployment ID: [x4dff5e5d11fc]
2024-04-19 13:31:01.366 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-04-19 13:31:01.366 [info] [chat fetch] modelMaxPromptTokens 3072
2024-04-19 13:31:01.366 [info] [chat fetch] modelMaxResponseTokens 4096
2024-04-19 13:31:01.366 [info] [chat fetch] chat model gpt-4
2024-04-19 13:31:02.436 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1064 ms
2024-04-19 13:31:17.060 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-04-19 13:31:17.065 [info] [streamChoices] request done: requestId: [b1414293-c7fc-477b-9722-20259fecfbe9] responseId: [b1414293-c7fc-477b-9722-20259fecfbe9] model deployment ID: [wc154981b18df]
2024-04-19 13:31:17.066 [info] [extension] TypeError: r.report is not a function
    at Object.report (/root/.vscode-server-insiders/extensions/github.copilot-chat-0.14.1/dist/extension.js:855:1767)
    at iE.applyDeltaToProgress (/root/.vscode-server-insiders/extensions/github.copilot-chat-0.14.1/dist/extension.js:854:1498)
    at /root/.vscode-server-insiders/extensions/github.copilot-chat-0.14.1/dist/extension.js:854:2590
    at /root/.vscode-server-insiders/extensions/github.copilot-chat-0.14.1/dist/extension.js:854:2343
    at Array.forEach (<anonymous>)
    at iE.checkForKeyWords (/root/.vscode-server-insiders/extensions/github.copilot-chat-0.14.1/dist/extension.js:854:2331)
    at iE.applyDelta (/root/.vscode-server-insiders/extensions/github.copilot-chat-0.14.1/dist/extension.js:854:2525)
    at iE.doProcessResponse (/root/.vscode-server-insiders/extensions/github.copilot-chat-0.14.1/dist/extension.js:854:1312)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by chrmarti** [comment]
@bamurtaugh Thanks for the ping, I'll continue here.

The `Default Extensions If Installed Locally` setting brings in the chat extension without remembering if it is installed as pre-release locally and that overrides any version (including `prerelease`) from the devcontainer.json.

I will fix this by remembering if the extension is installed as pre-release locally. This will also benefit the more general case where users are working with a pre-release version locally and expect pre-release to be used in the container too even if the devcontainer.json lists the stable release. (Assuming the user's local choice takes precedence over the devcontainer.json potentially shared with a team.)

**Comment by chrmarti** [comment]
Verification:
- Install GitHub Copilot Chat pre-release locally.
- Run `New Dev Container` command and verify that pre-release of GitHub Copilot Chat is automatically installed.
