### ISSUE TITLE
Failing to rebuild dev container

### ISSUE THREAD

**Issue by memben** [microsoft/vscode-remote-release#9870]
- VSCode Version: 1.89.0
- Local OS Version: MacOS 14.4.1
- Remote OS Version: 5.15.0-1042-nvidia
- Remote Extension/Connection Type: Containers

- Logs:

```text
[2024-05-10T08:23:41.805Z] Dev Containers 0.362.0 over Remote - SSH 0.110.1 in VS Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd).
[2024-05-10T08:23:41.805Z] Host OS: linux 5.15.0-1042-nvidia
[2024-05-10T08:23:41.806Z] Host CWD: /home/gorilla/memben
[2024-05-10T08:23:41.807Z] Start: Run: /bin/sh 
[2024-05-10T08:23:42.481Z] Start: Run in host: echo ~
[2024-05-10T08:23:42.934Z] /home/gorilla
[2024-05-10T08:23:42.934Z] 
[2024-05-10T08:23:42.934Z] Stop (453 ms): Run in host: echo ~
[2024-05-10T08:23:42.935Z] Start: Run in host: id -un
[2024-05-10T08:23:43.062Z] gorilla
[2024-05-10T08:23:43.062Z] 
[2024-05-10T08:23:43.062Z] Stop (127 ms): Run in host: id -un
[2024-05-10T08:23:43.062Z] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'gorilla' || grep -E '^gorilla|^[^:]*:[^:]*:gorilla:' /etc/passwd || true)
[2024-05-10T08:23:43.136Z] Stop (74 ms): Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'gorilla' || grep -E '^gorilla|^[^:]*:[^:]*:gorilla:' /etc/passwd || true)
[2024-05-10T08:23:43.137Z] userEnvProbe: loginInteractiveShell (default)
[2024-05-10T08:23:43.137Z] userEnvProbe: not found in cache
[2024-05-10T08:23:43.137Z] userEnvProbe shell: /bin/bash
[2024-05-10T08:23:43.623Z] userEnvProbe PATHs:
Probe:     '/home/gorilla/.local/bin:/usr/local/cuda/bin:/opt/bin/:/home/gorilla/.local/bin:/usr/local/cuda/bin:/opt/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
Container: None
[2024-05-10T08:23:44.573Z] Initializing configuration support...
[2024-05-10T08:23:44.574Z] Internal initialization of dev container support package...
[2024-05-10T08:24:22.843Z] Start: Run: docker version --format {{json .}}
[2024-05-10T08:24:23.455Z] {"Client":{"Platform":{"Name":"Docker Engine - Community"},"Version":"23.0.4","ApiVersion":"1.42","DefaultAPIVersion":"1.42","GitCommit":"f480fb1","GoVersion":"go1.19.8","Os":"linux","Arch":"amd64","BuildTime":"Fri Apr 14 10:32:03 2023","Context":"rootless"},"Server":{"Platform":{"Name":"Docker Engine - Community"},"Components":[{"Name":"Engine","Version":"23.0.4","Details":{"ApiVersion":"1.42","Arch":"amd64","BuildTime":"Fri Apr 14 10:32:03 2023","Experimental":"false","GitCommit":"cbce331","GoVersion":"go1.19.8","KernelVersion":"5.15.0-1042-nvidia","MinAPIVersion":"1.12","Os":"linux"}},{"Name":"containerd","Version":"1.6.8","Details":{"GitCommit":"9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6"}},{"Name":"runc","Version":"1.1.4","Details":{"GitCommit":"v1.1.4-0-g5fd4c4d"}},{"Name":"docker-init","Version":"0.19.0","Details":{"GitCommit":"de40ad0"}},{"Name":"rootlesskit","Version":"1.1.0","Details":{"ApiVersion":"1.1.1","NetworkDriver":"slirp4netns","PortDriver":"builtin","StateDir":"/tmp/rootlesskit1999516284"}},{"Name":"slirp4netns","Version":"1.0.1","Details":{"GitCommit":"6a7b16babc95b6a3056b33fb45b74a6f62262dd4"}}],"Version":"23.0.4","ApiVersion":"1.42","MinAPIVersion":"1.12","GitCommit":"cbce331","GoVersion":"go1.19.8","Os":"linux","Arch":"amd64","KernelVersion":"5.15.0-1042-nvidia","BuildTime":"2023-04-14T10:32:03.000000000+00:00"}}
[2024-05-10T08:24:23.455Z] Stop (612 ms): Run: docker version --format {{json .}}
[2024-05-10T08:24:25.716Z] TypeError: Cannot read properties of undefined (reading 'toString')
	at sU (/Users/ben/.vscode/extensions/ms-vscode-remote.remote-containers-0.362.0/dist/extension/extension.js:296:46348)
```

Steps to Reproduce:

1. The server where this issue occurs has a unique setup where multiple people share the same user account.
2. The issue happens only when initially building the dev container. However, I can open dev containers built by others under the same user account, and others can build my dev container, which I can then access.
3. Based on the logs, the problem seems to be local to my setup. Reinstalling VSCode (trying to do it cleanly) did not resolve the issue.
4. Other than my SSH key being password-protected, there's seems to be no difference regarding my setup to the others.

Does this issue occur when you try this locally?: No

**Comment by chrmarti** [comment]
The error location suggests that you are adding a devcontainer.json. Did the UI picker show up at the top of the window?

**Comment by memben** [comment]
Hey, thanks for getting back. Is this the UI picker you mean?

<img width="610" alt="image" src="https://github.com/microsoft/vscode-remote-release/assets/59774249/fbdb43e3-fda3-49c6-87e5-2ebb0b0ac03b">

It seems I wasn't in the right folder in VSCode where the .devcontainer/devcontainer.json was located. I can't remember if this was the case the first time I had the problem, but it seems to be solved for now.

**Comment by kohtala** [comment]
I think I ran into this same problem. Got past it by using Dev containers: Add Dev container configurations Files... in another windows to create the .devcontainers/devcontainer.json in the folder. Thanks for that hint.

Version: 1.92.1 (user setup)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Remote OS Ubuntu 22.04 x64 with

- Docker-ce 27.1.1 from https://download.docker.com/linux/ubuntu
- node v20.16.0 from https://deb.nodesource.com/node_20.x
- go version go1.16.8 linux/amd64 from http://ppa.launchpad.net/longsleep/golang-backports/ubuntu.

Steps

1. SSH remote Connect to host...
2. Dev Containers: Open Folder in Container...
3. The folder was not at the root of .git repository, but a project in monorepo subdirectory
4. Account on remote was my personal. I had many windows open to same remote for different projects, but closed all but this one. Restarted, upgraded VSCode, extensions. Made no difference.
5. VSCode displayed the options to create with some template or docker-compose files found at the root of the folder.
6. Selecting any option, even template, gave the error OP has. Different version

```
Container: None
[124835 ms] TypeError: Cannot read properties of undefined (reading 'toString')
        at cU (c:\Users\marko\.vscode\extensions\ms-vscode-remote.remote-containers-0.380.0\dist\extension\extension.js:328:44013)
```

It is filling an object and that location has `rootUri:vi.Uri.parse((await t.toCommonURI(n.rootFolderPath)).toString())`. Apparently the roCommonURI returns undefined.

I downloaded the ms-vscode-remote.remote-containers-0.362.0 and compared it looks like the same location defining value for `rootUri`.

<details>
<summary>Full log</summary>
```
[102 ms] Dev Containers 0.380.0 over Remote - SSH 0.113.1 in VS Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4).
[102 ms] Start: Loading environment from ExecServer
[109 ms] Host OS: linux 5.15.0-117-generic
[109 ms] Host CWD: /
[109 ms] Start: Run: /bin/sh 
[134 ms] Start: Run in host: echo ~
[145 ms] /home/kohtala
[146 ms] 
[147 ms] Start: Run in host: id -un
[186 ms] kohtala
[186 ms] 
[187 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'kohtala' || grep -E '^kohtala|^[^:]*:[^:]*:kohtala:' /etc/passwd || true)
[223 ms] userEnvProbe: loginInteractiveShell (default)
[223 ms] userEnvProbe: not found in cache
[224 ms] userEnvProbe shell: /bin/bash
[362 ms] userEnvProbe PATHs:
Probe:     '/home/kohtala/.yarn/bin:/home/kohtala/bin:/home/kohtala/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/kohtala/.porter'
Container: None
[798 ms] Initializing configuration support...
[799 ms] Internal initialization of dev container support package...
[91908 ms] Start: Run: docker version --format {{json .}}
[91955 ms] {"Client":{"Platform":{"Name":"Docker Engine - Community"},"Version":"27.1.1","ApiVersion":"1.46","DefaultAPIVersion":"1.46","GitCommit":"6312585","GoVersion":"go1.21.12","Os":"linux","Arch":"amd64","BuildTime":"Tue Jul 23 19:57:01 2024","Context":"default"},"Server":{"Platform":{"Name":"Docker Engine - Community"},"Components":[{"Name":"Engine","Version":"27.1.1","Details":{"ApiVersion":"1.46","Arch":"amd64","BuildTime":"Tue Jul 23 19:57:01 2024","Experimental":"false","GitCommit":"cc13f95","GoVersion":"go1.21.12","KernelVersion":"5.15.0-117-generic","MinAPIVersion":"1.24","Os":"linux"}},{"Name":"containerd","Version":"1.7.19","Details":{"GitCommit":"2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41"}},{"Name":"runc","Version":"1.7.19","Details":{"GitCommit":"v1.1.13-0-g58aa920"}},{"Name":"docker-init","Version":"0.19.0","Details":{"GitCommit":"de40ad0"}}],"Version":"27.1.1","ApiVersion":"1.46","MinAPIVersion":"1.24","GitCommit":"cc13f95","GoVersion":"go1.21.12","Os":"linux","Arch":"amd64","KernelVersion":"5.15.0-117-generic","BuildTime":"2024-07-23T19:57:01.000000000+00:00"}}
[99026 ms] Start: Loading environment from ExecServer
[99028 ms] Host OS: linux 5.15.0-117-generic
[99028 ms] Host CWD: /
[99029 ms] Start: Run: /bin/sh 
[99032 ms] Start: Run in host: echo ~
[99075 ms] /home/kohtala
[99075 ms] 
[99076 ms] Start: Run in host: id -un
[99119 ms] kohtala
[99119 ms] 
[99120 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'kohtala' || grep -E '^kohtala|^[^:]*:[^:]*:kohtala:' /etc/passwd || true)
[99164 ms] userEnvProbe: loginInteractiveShell (default)
[99164 ms] userEnvProbe: not found in cache
[99164 ms] userEnvProbe shell: /bin/bash
[99248 ms] userEnvProbe PATHs:
Probe:     '/home/kohtala/.yarn/bin:/home/kohtala/bin:/home/kohtala/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/kohtala/.porter'
Container: None
[99413 ms] Running Dev Containers CLI:   read-configuration --workspace-folder /home/kohtala/[redacted]/[redacted] --log-level debug --log-format json --config /home/kohtala/[redacted]/[redacted]/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root
[99413 ms] Start: Checking for Dev Containers CLI
[99416 ms] Start: Run: /home/kohtala/.vscode-server/cli/servers/Stable-eaa41d57266683296de7d118f574d0c2652e1fc4/server/node /home/kohtala/.vscode-remote-containers/dist/dev-containers-cli-0.380.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/kohtala/[redacted]/[redacted] --log-level debug --log-format json --config /home/kohtala/[redacted]/[redacted]/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root
[100183 ms] @devcontainers/cli 0.65.0. Node.js v20.14.0. linux 5.15.0-117-generic x64.
[100183 ms] Start: Run: git rev-parse --show-cdup
[100193 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/kohtala/[redacted]/[redacted] --filter label=devcontainer.config_file=/home/kohtala/[redacted]/[redacted]/.devcontainer/devcontainer.json
[100213 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/kohtala/[redacted]/[redacted]
[100238 ms] Resolving Feature dependencies for 'ghcr.io/devcontainers-contrib/features/apt-packages:1'...
[100238 ms] * Processing feature: ghcr.io/devcontainers-contrib/features/apt-packages:1
[101547 ms] * Fetching feature: apt-packages_0_oci
[102223 ms] * Fetched feature: apt-packages_0_oci version 1.0.4
[102436 ms] Start: Run: docker inspect --type image mcr.microsoft.com/devcontainers/base:bookworm
[118253 ms] Start: Run: docker version --format {{json .}}
[118299 ms] {"Client":{"Platform":{"Name":"Docker Engine - Community"},"Version":"27.1.1","ApiVersion":"1.46","DefaultAPIVersion":"1.46","GitCommit":"6312585","GoVersion":"go1.21.12","Os":"linux","Arch":"amd64","BuildTime":"Tue Jul 23 19:57:01 2024","Context":"default"},"Server":{"Platform":{"Name":"Docker Engine - Community"},"Components":[{"Name":"Engine","Version":"27.1.1","Details":{"ApiVersion":"1.46","Arch":"amd64","BuildTime":"Tue Jul 23 19:57:01 2024","Experimental":"false","GitCommit":"cc13f95","GoVersion":"go1.21.12","KernelVersion":"5.15.0-117-generic","MinAPIVersion":"1.24","Os":"linux"}},{"Name":"containerd","Version":"1.7.19","Details":{"GitCommit":"2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41"}},{"Name":"runc","Version":"1.7.19","Details":{"GitCommit":"v1.1.13-0-g58aa920"}},{"Name":"docker-init","Version":"0.19.0","Details":{"GitCommit":"de40ad0"}}],"Version":"27.1.1","ApiVersion":"1.46","MinAPIVersion":"1.24","GitCommit":"cc13f95","GoVersion":"go1.21.12","Os":"linux","Arch":"amd64","KernelVersion":"5.15.0-117-generic","BuildTime":"2024-07-23T19:57:01.000000000+00:00"}}
[121985 ms] Start: Loading environment from ExecServer
[121987 ms] Host OS: linux 5.15.0-117-generic
[121987 ms] Host CWD: /
[121987 ms] Start: Run: /bin/sh 
[121992 ms] Start: Run in host: echo ~
[122035 ms] /home/kohtala
[122035 ms] 
[122036 ms] Start: Run in host: id -un
[122079 ms] kohtala
[122079 ms] 
[122079 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'kohtala' || grep -E '^kohtala|^[^:]*:[^:]*:kohtala:' /etc/passwd || true)
[122123 ms] userEnvProbe: loginInteractiveShell (default)
[122123 ms] userEnvProbe: not found in cache
[122123 ms] userEnvProbe shell: /bin/bash
[122184 ms] userEnvProbe PATHs:
Probe:     '/home/kohtala/.yarn/bin:/home/kohtala/bin:/home/kohtala/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/kohtala/.porter'
Container: None
[124835 ms] TypeError: Cannot read properties of undefined (reading 'toString')
        at cU (c:\Users\marko\.vscode\extensions\ms-vscode-remote.remote-containers-0.380.0\dist\extension\extension.js:328:44013)
```
</details>

**Comment by chrmarti** [comment]
Reproduced with an empty window connected to an SSH server and then using `Dev Containers: Open Folder in Container...` to open a folder that does not yet have a devcontainer.json. Also needs Copilot Chat installed on the SSH server to trigger.

**Comment by DingXuefeng** [comment]
same problem here. 

- VSCode Version: 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f) x64
- Local OS Version: 15.2 (24C101) macOS Sequoia
- Remote OS Version: Ubuntu 24.04.1 LTS
- Remote Extension/Connection Type: Dev Containers
- Logs:
<details><summary>logs</summary>

```
[642 ms] Dev Containers 0.395.0 over Remote - SSH 0.117.2025011020 in VS Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f).
[642 ms] Start: Loading environment from ExecServer
[756 ms] Host OS: linux 6.8.0-51-generic
[756 ms] Host CWD: /datafs/users/dingxf/tmp/20250109_tutorial/cxx
[756 ms] Start: Run: /bin/sh 
[1141 ms] Start: Run in host: echo ~
[1212 ms] /home/dingxf
[1212 ms] 
[1212 ms] Start: Run in host: id -un
[1713 ms] dingxf
[1714 ms] 
[1714 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'dingxf' || grep -E '^dingxf|^[^:]*:[^:]*:dingxf:' /etc/passwd || true)
[1806 ms] userEnvProbe: loginInteractiveShell (default)
[1806 ms] userEnvProbe: not found in cache
[1806 ms] userEnvProbe shell: /bin/bash
[3811 ms] Start: Run: /bin/sh 
[3953 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd || echo ; readlink /proc/$pid/ns/mnt || echo ; cat /proc/$pid/stat | tr "
[11811 ms] userEnvProbe is taking longer than 10 seconds. Avoid waiting for user input in your shell's startup scripts. Continuing.
[15567 ms] Initializing configuration support...
[15567 ms] Internal initialization of dev container support package...
[16113 ms] userEnvProbe is taking longer than 2 seconds. Process tree:
  2921038: /bin/bash -lic echo -n bfc0c87d-7a95-4cfb-8ee9-6d57892ff625; cat /proc/self/environ; echo -n bfc0c87d-7a95-4cfb-8ee9-6d57892ff625 
[35531 ms] Start: Run: podman version --format {{json .}}
[35734 ms] {"Client":{"APIVersion":"4.9.3","Version":"4.9.3","GoVersion":"go1.22.2","GitCommit":"","BuiltTime":"Thu Jan  1 08:00:00 1970","Built":0,"OsArch":"linux/amd64","Os":"linux"}}
[37628 ms] TypeError: Cannot read properties of undefined (reading 'toString')
        at mU (/Users/dingxf/.vscode/extensions/ms-vscode-remote.remote-containers-0.395.0/dist/extension/extension.js:333:44512)
```
</details>
Steps to Reproduce:

1. connect to remote host
2. open the project folder
3. command+shift+P, then rebuild+reopen in devcontainer

I'm using podman underhood. It seems to be a new problem. I can open an old project with the same procedure without any problem:
<details><summary>succesful logs</summary>

```
[350 ms] Dev Containers 0.395.0 over Remote - SSH 0.117.2025011020 in VS Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f).
[349 ms] Start: Resolving Remote
[353 ms] Start: Loading environment from ExecServer
[417 ms] Host OS: linux 6.8.0-51-generic
[417 ms] Host CWD: /datafs/users/dingxf/neutrino-physics-tutorial/scikit-build-cpp-python
[417 ms] Start: Run: /bin/sh 
[544 ms] Start: Run in host: echo ~
[615 ms] /home/dingxf
[615 ms] 
[616 ms] Start: Run in host: id -un
[687 ms] dingxf
[688 ms] 
[689 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'dingxf' || grep -E '^dingxf|^[^:]*:[^:]*:dingxf:' /etc/passwd || true)
[759 ms] userEnvProbe: loginInteractiveShell (default)
[760 ms] userEnvProbe: not found in cache
[760 ms] userEnvProbe shell: /bin/bash
[2764 ms] Start: Run: /bin/sh 
[2949 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd || echo ; readlink /proc/$pid/ns/mnt || echo ; cat /proc/$pid/stat | tr "
[10374 ms] userEnvProbe PATHs:
Probe:     '***'
Container: None
[10559 ms] Setting up container for folder or workspace: /datafs/users/dingxf/neutrino-physics-tutorial/scikit-build-cpp-python
[10560 ms] Host authority: ssh-remote+serveripv6
[10560 ms] Host: unix:///run/user/1001/podman/podman.sock
[10796 ms] Start: Check Docker is running
[10796 ms] Start: Run: podman version
[11568 ms] Client:       Podman Engine
Version:      4.9.3
API Version:  4.9.3
Go Version:   go1.22.2
Built:        Thu Jan  1 08:00:00 1970
OS/Arch:      linux/amd64
[11571 ms] Start: Run: podman volume ls -q
[12040 ms] Start: Run: podman inspect --type container a315403b75c1251cca8252c27cba6b4e7078ba25aaf7cdb06d45159d42758a0a
[12580 ms] Start: Run: podman rm -f a315403b75c1251cca8252c27cba6b4e7078ba25aaf7cdb06d45159d42758a0a
[14508 ms] Start: Run: podman ps -q -a --filter label=vsch.local.folder=/datafs/users/dingxf/neutrino-physics-tutorial/scikit-build-cpp-python --filter label=vsch.quality=stable
[14907 ms] Start: Run: podman ps -q -a --filter label=devcontainer.local_folder=/datafs/users/dingxf/neutrino-physics-tutorial/scikit-build-cpp-python --filter label=devcontainer.conf
```
</details>

**Comment by DingXuefeng** [comment]
> Reproduced with an empty window connected to an SSH server and then using `Dev Containers: Open Folder in Container...` to open a folder that does not yet have a devcontainer.json. Also needs Copilot Chat installed on the SSH server to trigger.

Hi, thanks. This solves the problem. 

- I put the wrong file name: `.devcontainer/.devcontainer.json`. 
- The correct one should be `.devcontainer/devcontainer.json`.

Maybe we can improve the log message.

**Comment by blorticus** [comment]
I am using Remote - SSH to a Linux host from VS Code on a Mac.  If Github Copilot is installed in the remote, then I cannot reopen in a dev container (i.e., I have a remote session open, click the >< selector at the bottom left, select "Reopen in container").  It fails with the error noted previously.  If I remove Copilot from remote (i.e., right-click and select "Uninstall") and subsequently restart VS Code, I can then "Reopen in container" from the remote session.  I can then switch back to ssh (i.e., "Reopen folder in SSH"), install Copilot to SSH, and still reopen in a container.  I suspect that's because the previous "Reopen in container" created `.devcontainer/devcontainer.json`.  I believe this because, if I reopen in SSH, remove that directory, then try to "Reopen in container", the error occurs again.  I suspect there is a bug in the Github Copilot extension.

**Comment by noperator** [comment]
> Reproduced with an empty window connected to an SSH server and then using `Dev Containers: Open Folder in Container...` to open a folder that does not yet have a devcontainer.json. Also needs Copilot Chat installed on the SSH server to trigger.

Uninstalling Copilot on remote server (and restarting VS code) fixed this error for me.

**Comment by juliusganns** [comment]
Okay, that briefly seemed to have fixed it, but it didn't really - isn't the real issue that the JSON format in Docker "docker version" is inconsistent, or where does the "toString" call break? And why should it work when Copilot Chat is uninstalled? Maybe the root cause should be fixed...

**Comment by tewalden** [comment]
I found this issue after searching for the same error. For me, opening the project folder on it's own (not as part of a workspace with other folders or files open) seemed to fix it.

**Comment by shallowcosmicjumper** [comment]
Manually setting up the [devcontainer.json](https://code.visualstudio.com/docs/devcontainers/containers#_create-a-devcontainerjson-file) mitigates the issue for me.
