### ISSUE TITLE
[Remote-SSH Bug]: could not establish connection to

### ISSUE THREAD

**Issue by ZhiyiHu1999** [microsoft/vscode-remote-release#9953]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Expected Behavior

Successful connection to ault.

### Steps To Reproduce

I connect successfully to ault using local terminal but cannot successfully connect to ault using remote-ssh extension. I tried kill vscode remote server on ault and nothing changed. No explicit error explaination in the remote-ssh logs below. Thanks for your help

### Remote-SSH Log

[23:55:09.506] Log Level: 2
[23:55:09.514] VS Code version: 1.90.0
[23:55:09.514] Remote-SSH version: remote-ssh@0.112.2024053015
[23:55:09.514] win32 x64
[23:55:09.515] SSH Resolver called for "ssh-remote+ault", attempt 1
[23:55:09.516] "remote.SSH.useLocalServer": false
[23:55:09.516] "remote.SSH.useExecServer": true
[23:55:09.516] "remote.SSH.showLoginTerminal": true
[23:55:09.516] "remote.SSH.remotePlatform": {"duvel.ethz.ch":"linux","commnet":"linux","ault":"linux","daint":"linux"}
[23:55:09.516] "remote.SSH.path": undefined
[23:55:09.516] "remote.SSH.configFile": undefined
[23:55:09.516] "remote.SSH.useFlock": true
[23:55:09.516] "remote.SSH.lockfilesInTmp": false
[23:55:09.516] "remote.SSH.localServerDownload": auto
[23:55:09.516] "remote.SSH.remoteServerListenOnSocket": false
[23:55:09.516] "remote.SSH.showLoginTerminal": true
[23:55:09.516] "remote.SSH.defaultExtensions": []
[23:55:09.516] "remote.SSH.loglevel": 2
[23:55:09.518] "remote.SSH.enableDynamicForwarding": true
[23:55:09.518] "remote.SSH.enableRemoteCommand": false
[23:55:09.518] "remote.SSH.serverPickPortsFromRange": {}
[23:55:09.518] "remote.SSH.serverInstallPath": {}
[23:55:09.526] SSH Resolver called for host: ault
[23:55:09.526] Setting up SSH remote "ault"
[23:55:09.530] Using commit id "89de5a8d4d6205e5b11647eb6a74844ca23d2573" and quality "stable" for server
[23:55:09.532] Install and start server if needed
[23:55:09.536] Checking ssh with "E:\Program Files\Eclipse Adoptium\jdk-17.0.8.7-hotspot\bin\ssh.exe -V"
[23:55:09.539] Got error from ssh: spawn E:\Program Files\Eclipse Adoptium\jdk-17.0.8.7-hotspot\bin\ssh.exe ENOENT
[23:55:09.540] Checking ssh with "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe -V"
[23:55:09.541] Got error from ssh: spawn C:\Program Files (x86)\Common Files\Oracle\Java\javapath\ssh.exe ENOENT
[23:55:09.541] Checking ssh with "C:\Windows\system32\ssh.exe -V"
[23:55:09.542] Got error from ssh: spawn C:\Windows\system32\ssh.exe ENOENT
[23:55:09.542] Checking ssh with "C:\Windows\ssh.exe -V"
[23:55:09.543] Got error from ssh: spawn C:\Windows\ssh.exe ENOENT
[23:55:09.543] Checking ssh with "C:\Windows\System32\Wbem\ssh.exe -V"
[23:55:09.543] Got error from ssh: spawn C:\Windows\System32\Wbem\ssh.exe ENOENT
[23:55:09.544] Checking ssh with "C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe -V"
[23:55:09.544] Got error from ssh: spawn C:\Windows\System32\WindowsPowerShell\v1.0\ssh.exe ENOENT
[23:55:09.544] Checking ssh with "C:\Windows\System32\OpenSSH\ssh.exe -V"
[23:55:09.574] > OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

[23:55:09.584] Running script with connection command: "C:\Windows\System32\OpenSSH\ssh.exe" -T -D 63504 ault bash
[23:55:09.587] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[23:55:11.351] > Received disconnect from UNKNOWN port 65535:2: Too many authentication failures
> Disconnected from UNKNOWN port 65535
> 过程试图写入的管道不存在。
> ]0;C:\WINDOWS\System32\cmd.exe
[23:55:11.351] Got some output, clearing connection timeout
[23:55:12.593] "install" terminal command done
[23:55:12.593] Install terminal quit with output: ]0;C:\WINDOWS\System32\cmd.exe
[23:55:12.593] Received install output: ]0;C:\WINDOWS\System32\cmd.exe
[23:55:12.594] Failed to parse remote port from server output
[23:55:12.595] Resolver error: Error: 
	at g.Create (c:\Users\11455\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.2024053015\out\extension.js:2:499918)
	at t.handleInstallOutput (c:\Users\11455\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.2024053015\out\extension.js:2:497240)
	at t.tryInstall (c:\Users\11455\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.2024053015\out\extension.js:2:620913)
	at async c:\Users\11455\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.2024053015\out\extension.js:2:580730
	at async t.withShowDetailsEvent (c:\Users\11455\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.2024053015\out\extension.js:2:584036)
	at async k (c:\Users\11455\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.2024053015\out\extension.js:2:577649)
	at async t.resolve (c:\Users\11455\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.2024053015\out\extension.js:2:581407)
	at async c:\Users\11455\.vscode\extensions\ms-vscode-remote.remote-ssh-0.112.2024053015\out\extension.js:2:847860
[23:55:12.598] ------

**Comment by roblourens** [comment]
`Too many authentication failures`

This is just an error that we get from ssh. There must be something wrong with your configuration, but it's hard to tell what it is from here, sorry. You can try setting `"remote.SSH.useLocalServer": true` (must be in settings.json) to see if you get something different

**Comment by fochive00** [comment]
I had the same problem, restarting my Windows system solved it  (°ー°〃)
