### ISSUE TITLE
[Remote-SSH Bug]: Cannot add any remote ssh! (marketplace API issue?)

### ISSUE THREAD

**Issue by markg85** [microsoft/vscode-remote-release#9960]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It doesn’t connect successfully (same error message)

### ->

Irrelevant.

### Expected Behavior

Connect to remote SSH!

### Steps To Reproduce

Irrelevant, see log (just have the remote ssh extension and follow this guide https://code.visualstudio.com/docs/remote/ssh).

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[64207:0608/025626.084918:INFO:CONSOLE(1803)] "Activating extension 'ms-vscode-remote.remote-ssh' failed: Extension 'ms-vscode-remote.remote-ssh' CANNOT use API proposal: resolvers.
Its package.json#enabledApiProposals-property declares:  but NOT resolvers.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-vscode-remote.remote-ssh.", source: vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js (1803)
[64207:0608/025626.086482:INFO:CONSOLE(656)] "%cTRACE color: #888 DialogService#prompt Command 'Remote-SSH: Add New SSH Host...' resulted in an error", source: vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js (656)
[64207:0608/025626.111392:INFO:CONSOLE(1803)] "Activating extension 'ms-vscode.remote-explorer' failed: Extension 'ms-vscode.remote-explorer' CANNOT use API proposal: extensionsAny.
Its package.json#enabledApiProposals-property declares:  but NOT extensionsAny.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-vscode.remote-explorer.", source: vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js (1803)
[64207:0608/025626.112194:INFO:CONSOLE(656)] "%cTRACE color: #888 CommandService#executeCommand remote-internal.setActiveFolders", source: vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js (656)
[64207:0608/025626.112899:INFO:CONSOLE(656)] "%cTRACE color: #888 onWillActivateByEvent:  onCommand:remote-internal.setActiveFolders", source: vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js (656)
[64207:0608/025626.231239:INFO:CONSOLE(656)] "%cDEBUG background: #eee; color: #888 Comments: URIs of continue on comments to add to storage .", source: vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js (656)
[64207:0608/025626.294552:INFO:CONSOLE(656)] "%cTRACE color: #888 CommandService#executeCommand _setContext", source: vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js (656)
[64207:0608/025627.102136:INFO:CONSOLE(152)] "%c[Extension Host] %crejected promise not handled within 1 second: Error: command 'remote-internal.setActiveFolders' not found %c(at console.<anonymous> (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:143:59509)) color: blue color:  color: grey", source: vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js (152)
[64207:0608/025627.102265:INFO:CONSOLE(152)] "%c[Extension Host] %cstack trace: Error: command 'remote-internal.setActiveFolders' not found
    at y.n (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:1609:23057)
    at y.executeCommand (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:1609:22986) %c(at console.<anonymous> (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:143:59509)) color: blue color:  color: grey", source: vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js (152)
[64207:0608/025627.103787:INFO:CONSOLE(656)] "%c  ERR color: #f33 command 'remote-internal.setActiveFolders' not found: Error: command 'remote-internal.setActiveFolders' not found
    at y.n (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:1609:23057)

```

</p>
</details>

### Anything else?

What could be of importance here is that i'm using the open source vscode (on Arch Linux) with this [Marketplace](https://aur.archlinux.org/packages/code-marketplace) package to get vscode to behave and for packages to install.

Given the errors in the logging i'm **assuming** there is some permission thingy with the marketplace.
With that i'm also **assuming** that the vanilla vscode version probably works.

Which begs the question, if my assumptions are correct, why isn't the ssh plugin working properly on the oss vscode version? I could be wrong, just the logs make me think that.

**Comment by roblourens** [comment]
Only official VS Code builds support the remote extensions, sorry.

**Comment by markg85** [comment]
As expected, sadly.

Is there a specific reason why this extension is tied to the official vs code?
Or if that's documented somewhere, feel free to point me to that instead.

**Comment by markg85** [comment]
Thank you for your link @roblourens
Upon clicking a little further to [this page](https://github.com/microsoft/vscode/wiki/Differences-between-the-repository-and-Visual-Studio-Code) it gives me an actual explanation of why this extension is not working on the OSS version.

> Parts of the code to negotiate a connection to the Visual Studio Code server are proprietary.

Which, to me, begs the question: Why does VSCode need to negotiate **any** connection with a "Visual Studio Code server"? That makes no sense to me.

When i SSH (just ssh, forget VS Code for a moment) into a machine i don't need anyone to "negotiate" that connection. The negotiation is done by SSH itself in the connection handshake. Back to VS Code, why does it need something else that SSH doesn't already do?

**Comment by roblourens** [comment]
https://code.visualstudio.com/docs/remote/remote-overview
