### ISSUE TITLE
devcontainers 0.372.0  - the expected container does not exist

### ISSUE THREAD

**Issue by croth1-liveeo** [microsoft/vscode-remote-release#9972]
- VSCode Version: 1.89.1
- Local OS Version: Ubuntu 22.04.2 LTS
- Remote OS Version:  Ubuntu 20.04.6 LTS
- Remote Extension/Connection Type: Containers

It seems the current pre-release of the devcontainers extension (v0.372.0) will break our docker-compose setup. Switching back to `v0.369.0` fixes it.

- Logs:

```
[2024-06-12T08:09:47.570Z] Dev Containers 0.372.0 over Remote - SSH 0.110.1 in VS Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685).
[2024-06-12T08:09:47.570Z] Start: Resolving Remote
[2024-06-12T08:09:47.572Z] Start: Loading environment from ExecServer
[2024-06-12T08:09:47.586Z] Stop (14 ms): Loading environment from ExecServer
[2024-06-12T08:09:47.587Z] Host OS: linux 5.15.0-1026-aws
[2024-06-12T08:09:47.587Z] Host CWD: /home/ubuntu/repos/ta-training-dataset-builder
[2024-06-12T08:09:47.587Z] Start: Run: /bin/sh 
[2024-06-12T08:09:47.616Z] Start: Run in host: echo ~
[2024-06-12T08:09:47.673Z] /home/ubuntu
[2024-06-12T08:09:47.673Z] 
[2024-06-12T08:09:47.673Z] Stop (57 ms): Run in host: echo ~
[2024-06-12T08:09:47.673Z] Start: Run in host: id -un
[2024-06-12T08:09:47.732Z] ubuntu
[2024-06-12T08:09:47.732Z] 
[2024-06-12T08:09:47.732Z] Stop (59 ms): Run in host: id -un
[2024-06-12T08:09:47.732Z] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'ubuntu' || grep -E '^ubuntu|^[^:]*:[^:]*:ubuntu:' /etc/passwd || true)
[2024-06-12T08:09:47.790Z] Stop (58 ms): Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'ubuntu' || grep -E '^ubuntu|^[^:]*:[^:]*:ubuntu:' /etc/passwd || true)
[2024-06-12T08:09:47.790Z] userEnvProbe: loginInteractiveShell (default)
[2024-06-12T08:09:47.790Z] userEnvProbe: not found in cache
[2024-06-12T08:09:47.790Z] userEnvProbe shell: /usr/bin/zsh
[2024-06-12T08:09:48.124Z] userEnvProbe PATHs:
Probe:     '/home/ubuntu/.pyenv/shims:/home/ubuntu/.pyenv/bin:/opt/conda/condabin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/ubuntu/bin'
Container: None
[2024-06-12T08:09:48.154Z] Setting up container for folder or workspace: /home/ubuntu/repos/ta-training-dataset-builder
[2024-06-12T08:09:48.154Z] Host authority: ssh-remote+christian-mlops
[2024-06-12T08:09:48.214Z] Start: Check Docker is running
[2024-06-12T08:09:48.214Z] Start: Run: docker version
[2024-06-12T08:09:48.288Z] Client: Docker Engine - Community
[2024-06-12T08:09:48.288Z]  Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:01 2023
 OS/Arch:           
[2024-06-12T08:09:48.288Z] linux/amd64
 Context:           default

[2024-06-12T08:09:48.289Z] Server: Docker Engine - Community
[2024-06-12T08:09:48.289Z]  Engine:
[2024-06-12T08:09:48.289Z]   Version:          24.0.7
  API version:
[2024-06-12T08:09:48.289Z]       1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
[2024-06-12T08:09:48.289Z] 
  Built:        
[2024-06-12T08:09:48.289Z]     Thu Oct 26 09:08:01 2023
  OS/Arch:          linux/amd64
  Experimental:     
[2024-06-12T08:09:48.289Z] false
 containerd:
[2024-06-12T08:09:48.289Z]   Version:          1.6.25
  GitCommit:        
[2024-06-12T08:09:48.289Z] d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
[2024-06-12T08:09:48.289Z]   Version:          1.1.10
  GitCommit:        
[2024-06-12T08:09:48.289Z] v1.1.10-0-g18a0cb0
 docker-init:
[2024-06-12T08:09:48.289Z]   Version:          0.19.0
  GitCommit:        
[2024-06-12T08:09:48.289Z] de40ad0
[2024-06-12T08:09:48.289Z] Stop (75 ms): Run: docker version
[2024-06-12T08:09:48.289Z] Stop (75 ms): Check Docker is running
[2024-06-12T08:09:48.290Z] Start: Run: docker volume ls -q
[2024-06-12T08:09:48.366Z] Stop (76 ms): Run: docker volume ls -q
[2024-06-12T08:09:48.367Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/ubuntu/repos/ta-training-dataset-builder --filter label=vsch.quality=stable
[2024-06-12T08:09:48.440Z] Stop (73 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/home/ubuntu/repos/ta-training-dataset-builder --filter label=vsch.quality=stable
[2024-06-12T08:09:48.440Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/ubuntu/repos/ta-training-dataset-builder --filter label=devcontainer.config_file=/home/ubuntu/repos/ta-training-dataset-builder/.devcontainer/devcontainer.json
[2024-06-12T08:09:48.513Z] Stop (73 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/ubuntu/repos/ta-training-dataset-builder --filter label=devcontainer.config_file=/home/ubuntu/repos/ta-training-dataset-builder/.devcontainer/devcontainer.json
[2024-06-12T08:09:48.513Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/ubuntu/repos/ta-training-dataset-builder
[2024-06-12T08:09:48.585Z] Stop (72 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/ubuntu/repos/ta-training-dataset-builder
[2024-06-12T08:09:48.585Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/ubuntu/repos/ta-training-dataset-builder
[2024-06-12T08:09:48.657Z] Stop (72 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/ubuntu/repos/ta-training-dataset-builder
[2024-06-12T08:09:48.658Z] Running Dev Containers CLI:   up --container-session-data-folder /tmp/devcontainers-6eccb268-5abb-4765-a414-f4b46a8b180c1718179786222 --workspace-folder /home/ubuntu/repos/ta-training-dataset-builder --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/ubuntu/repos/ta-training-dataset-builder --id-label devcontainer.config_file=/home/ubuntu/repos/ta-training-dataset-builder/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/ubuntu/repos/ta-training-dataset-builder/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --expect-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[2024-06-12T08:09:48.658Z] Start: Checking for Dev Containers CLI
[2024-06-12T08:09:48.674Z] Stop (16 ms): Checking for Dev Containers CLI
[2024-06-12T08:09:48.688Z] Start: Run: /home/ubuntu/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/node /home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.372.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-6eccb268-5abb-4765-a414-f4b46a8b180c1718179786222 --workspace-folder /home/ubuntu/repos/ta-training-dataset-builder --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/ubuntu/repos/ta-training-dataset-builder --id-label devcontainer.config_file=/home/ubuntu/repos/ta-training-dataset-builder/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/ubuntu/repos/ta-training-dataset-builder/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --expect-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[2024-06-12T08:09:48.887Z] @devcontainers/cli 0.64.0. Node.js v18.18.2. linux 5.15.0-1026-aws x64.
[2024-06-12T08:09:48.887Z] Start: Run: docker buildx version
[2024-06-12T08:09:48.958Z] Stop (71 ms): Run: docker buildx version
[2024-06-12T08:09:48.959Z] github.com/docker/buildx v0.11.2 9872040
[2024-06-12T08:09:48.959Z] 
[2024-06-12T08:09:48.959Z] Start: Run: docker -v
[2024-06-12T08:09:48.976Z] Stop (17 ms): Run: docker -v
[2024-06-12T08:09:48.976Z] Start: Resolving Remote
[2024-06-12T08:09:48.982Z] Running the initializeCommand from devcontainer.json...

[2024-06-12T08:09:48.983Z] Start: Run: /bin/sh -c bash .devcontainer/setup_host.sh
[2024-06-12T08:09:49.755Z] WARNING! Your password will be stored unencrypted in /home/ubuntu/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

[2024-06-12T08:09:49.755Z] Login Succeeded
[2024-06-12T08:09:49.758Z] Stop (775 ms): Run: /bin/sh -c bash .devcontainer/setup_host.sh
[2024-06-12T08:09:49.758Z] 
[2024-06-12T08:09:49.759Z] Start: Run: docker-compose version --short
[2024-06-12T08:09:49.763Z] Stop (4 ms): Run: docker-compose version --short
[2024-06-12T08:09:49.763Z] Start: Run: docker compose version --short
[2024-06-12T08:09:49.766Z] Stop (7 ms): Run: docker-compose version --short
[2024-06-12T08:09:49.828Z] Stop (65 ms): Run: docker compose version --short
[2024-06-12T08:09:49.829Z] Docker Compose version: 2.21.0
[2024-06-12T08:09:49.829Z] Start: Run: docker compose -f /home/ubuntu/repos/ta-training-dataset-builder/.devcontainer/docker-compose.yml --profile * config
[2024-06-12T08:09:49.901Z] Stop (72 ms): Run: docker compose -f /home/ubuntu/repos/ta-training-dataset-builder/.devcontainer/docker-compose.yml --profile * config
[2024-06-12T08:09:49.901Z] name: ta-training-dataset-builder
services:
  flow:
    build:
      context: /home/ubuntu/repos/ta-training-dataset-builder
      dockerfile: ./anyscale_node_image/Dockerfile
      args:
        DEVCONTAINER_POSTFIX: _dev
      secrets:
      - source: ci_job_token
    command:
    - /bin/sh
    - -c
    - while sleep 1000; do :; done
    depends_on:
      imagery_api:
        condition: service_started
        required: true
    networks:
      default: null
    volumes:
    - type: bind
      source: /home/ubuntu/repos/ta-training-dataset-builder
      target: /workspace
      bind:
        create_host_path: true
    - type: bind
      source: /tmp
      target: /tmp
      bind:
        create_host_path: true
    - type: bind
      source: /home/ubuntu/.config/pypoetry
      target: /home/ray/.config/pypoetry
      bind:
        create_host_path: true
    - type: bind
      source: /home/ubuntu/.config/pip
      target: /home/ray/.config/pip
      bind:
        create_host_path: true
    - type: bind
      source: /home/ubuntu/.aws
      target: /home/ray/.aws
      bind:
        create_host_path: true
    - type: bind
      source: /home/ubuntu/.prefect
      target: /home/ray/.prefect
      bind:
        create_host_path: true
    - type: bind
      source: /home/ubuntu/.netrc
      target: /home/ray/.netrc
      bind:
        create_host_path: true
    - type: bind
      source: /efs
      target: /efs
      bind:
        create_host_path: true
  imagery_api:
    depends_on:
      postgres:
        condition: service_started
        required: true
    entrypoint:
    - bash
    - -c
    - /app/docker/wait-for-it.sh postgres:5432 && liveeo-orm-db --initialize --no-interactive
      && python liveeo/imagery_api/utils/data_import.py -f /data/initial_stac_items.json
      && uvicorn --host 0.0.0.0 --log-level debug liveeo.imagery_api.main:app
    environment:
      DEBUG: "true"
      MOCK_AUTH: "true"
      POSTGRES_DB: imagery_stac
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_TEST_DB: test_imagery_stac
      POSTGRES_USER: postgres
    image: xxx:dev-1131921307
    networks:
      default: null
    volumes:
    - type: bind
      source: /home/ubuntu/repos/ta-training-dataset-builder/data/patched_items.json
      target: /data/initial_stac_items.json
      read_only: true
      bind:
        create_host_path: true
  postgres:
    environment:
      POSTGRES_DB: imagery_stac
      POSTGRES_PASSWORD: password
      POSTGRES_TEST_DB: test_imagery_stac
      POSTGRES_USER: postgres
    image: postgis/postgis:15-3.3
    networks:
      default: null
    volumes:
    - type: volume
      target: /var/lib/postgresql/data
      volume: {}
networks:
  default:
    name: ta-training-dataset-builder_default
secrets:
  ci_job_token:
    name: ta-training-dataset-builder_ci_job_token
    file: /home/ubuntu/.secret/ci_job_token
[2024-06-12T08:09:49.907Z] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=ta-training-dataset-builder --filter label=com.docker.compose.service=flow
[2024-06-12T08:09:49.924Z] Stop (17 ms): Run: docker ps -q -a --filter label=com.docker.compose.project=ta-training-dataset-builder --filter label=com.docker.compose.service=flow
[2024-06-12T08:09:50.022Z] Error: The expected container does not exist.
[2024-06-12T08:09:50.023Z]     at utA (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.372.0/dist/spec-node/devContainersSpecCLI.js:409:3207)
[2024-06-12T08:09:50.023Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-06-12T08:09:50.023Z]     at async KtA (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.372.0/dist/spec-node/devContainersSpecCLI.js:481:3944)
[2024-06-12T08:09:50.023Z]     at async eB (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.372.0/dist/spec-node/devContainersSpecCLI.js:481:4886)
[2024-06-12T08:09:50.023Z]     at async hrA (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.372.0/dist/spec-node/devContainersSpecCLI.js:661:13684)
[2024-06-12T08:09:50.023Z]     at async lrA (/home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.372.0/dist/spec-node/devContainersSpecCLI.js:661:13432)
[2024-06-12T08:09:50.028Z] Stop (1340 ms): Run: /home/ubuntu/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/node /home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.372.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-6eccb268-5abb-4765-a414-f4b46a8b180c1718179786222 --workspace-folder /home/ubuntu/repos/ta-training-dataset-builder --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/ubuntu/repos/ta-training-dataset-builder --id-label devcontainer.config_file=/home/ubuntu/repos/ta-training-dataset-builder/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/ubuntu/repos/ta-training-dataset-builder/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --expect-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[2024-06-12T08:09:50.028Z] Exit code 1
[2024-06-12T08:09:50.031Z] Command failed: /home/ubuntu/.vscode-server/cli/servers/Stable-dc96b837cf6bb4af9cd736aa3af08cf8279f7685/server/node /home/ubuntu/.vscode-remote-containers/dist/dev-containers-cli-0.372.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-6eccb268-5abb-4765-a414-f4b46a8b180c1718179786222 --workspace-folder /home/ubuntu/repos/ta-training-dataset-builder --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/ubuntu/repos/ta-training-dataset-builder --id-label devcontainer.config_file=/home/ubuntu/repos/ta-training-dataset-builder/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/ubuntu/repos/ta-training-dataset-builder/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --expect-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[2024-06-12T08:09:50.031Z] Exit code 1
``` 
Steps to Reproduce:

Shows up immediately after switching from devcontainers v0.369.0 to -> v0.372.0 on attempting to enter the devcontainer. I can try to simplify to a minimal reproducer later this week if necessary.

devcontainers.json
```
{
    "name": "ta-training-dataset-builder",
    "dockerComposeFile": "docker-compose.yml",
    "service": "flow",
    "workspaceFolder": "/workspace",
    "customizations": {
        "vscode": {
            "settings": {
                "extensions.verifySignature": false,
                "[python]": {
                    "editor.defaultFormatter": "charliermarsh.ruff",
                    "editor.formatOnSave": true,
                    "editor.codeActionsOnSave": {
                        "source.organizeImports": "explicit",
                        "source.fixAll": "explicit"
                    }
                }

            },
            "extensions": [
                "ms-python.python",
                "ms-python.vscode-pylance",
                "ms-python.pylint",
                "ms-python.mypy-type-checker",
                "charliermarsh.ruff",
                "github.copilot",
                "ms-toolsai.jupyter",
                "tamasfe.even-better-toml",
                "ms-azuretools.vscode-docker"
            ]
        }
    },
    "containerEnv": {
        "PREFECT_SEQUENTIAL_TASKRUNNER": "1",
        "RUNNING_IN_DEV_ENV": "1"
    },
    "initializeCommand": "bash .devcontainer/setup_host.sh",
    "postCreateCommand": "bash .devcontainer/setup_container.sh",
    "shutdownAction": "stopCompose"
}

```

Does this issue occur when you try this locally?: -
Does this issue occur when you try this locally and all extensions are disabled?: -

**Comment by whexy** [comment]
same here

**Comment by densalzmann** [comment]
I had the same error when I was trying to rebuild my devcontainer. If you also couldn't find the old container with `docker ps -a` and remove it, then I have a **workaround**:
Run the failed devcontainer command without the `--expect-existing-container` flag.  This rebuilds the devcontainer, and you would be able to reopen vscode in it using the plugin.

**Comment by chrmarti** [comment]
Could you give Dev Containers 0.373.0-pre-release a try and let me know if that fixes it? Thanks.

**Comment by croth1-liveeo** [comment]
0.373 seems to work again! Thanks so much for the quick fix!
