### ISSUE TITLE
macos15

### ISSUE THREAD

**Issue by wpweishenmeyaoshemima** [microsoft/vscode-remote-release#9974]
Type: <b>Bug</b>

can't use remote-ssh on macos 15.0

Extension version: 0.112.2024053015
VS Code version: Code 1.90.0 (Universal) (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:34:44.157Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id c4272f41-a111-4677-8241-2d0ed2c24e25|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by roblourens** [comment]
Please give some more details and share the log from the Remote-SSH output channel

**Comment by roblabs** [comment]
Symptoms:

* Error from VScode is *No route to Host*
  * `Install terminal quit with output: ssh: connect to host 192.168.1.31 port 22: No route to host`

* SSH works outside of VScode
* `ssh 192.168.1.31`  # works fine in Terminal.app, but fails from terminal in Visual Studio Code.app

---

<details><summary>Log:  OpenSSH & macOS 15.0 <code>sw_vers</code></summary>
<pre>
ProductName:		macOS
ProductVersion:		15.0
BuildVersion:		24A5264n

// OpenSSH
OpenSSH_9.6p1, LibreSSL 3.3.6
</pre>
</details>

---

<details open=1><summary>Log from Remote - SSH </summary>
<pre>
[15:16:21.424] Log Level: 2
[15:16:21.432] SSH Resolver called for "ssh-remote+m1remote", attempt 1
[15:16:21.432] "remote.SSH.useLocalServer": false
[15:16:21.432] "remote.SSH.useExecServer": false
[15:16:21.432] "remote.SSH.showLoginTerminal": true
[15:16:21.433] "remote.SSH.remotePlatform": {"192.168.1.31":"macOS","m1remote":"macOS"}
[15:16:21.433] "remote.SSH.path": undefined
[15:16:21.433] "remote.SSH.configFile": /Users/roblabs/.ssh/config
[15:16:21.433] "remote.SSH.useFlock": false
[15:16:21.433] "remote.SSH.lockfilesInTmp": false
[15:16:21.433] "remote.SSH.localServerDownload": auto
[15:16:21.433] "remote.SSH.remoteServerListenOnSocket": false
[15:16:21.433] "remote.SSH.showLoginTerminal": true
[15:16:21.433] "remote.SSH.defaultExtensions": []
[15:16:21.433] "remote.SSH.loglevel": 2
[15:16:21.433] "remote.SSH.enableDynamicForwarding": true
[15:16:21.433] "remote.SSH.enableRemoteCommand": false
[15:16:21.433] "remote.SSH.serverPickPortsFromRange": {}
[15:16:21.433] "remote.SSH.serverInstallPath": {}
[15:16:21.439] VS Code version: 1.90.1
[15:16:21.439] Remote-SSH version: remote-ssh@0.112.0
[15:16:21.439] darwin x64
[15:16:21.440] SSH Resolver called for host: m1remote
[15:16:21.440] Setting up SSH remote "m1remote"
[15:16:21.443] Using commit id "611f9bfce64f25108829dd295f54a6894e87339d" and quality "stable" for server
[15:16:21.446] Install and start server if needed
[15:16:21.449] PATH: /Users/roblabs/Library/pnpm:/usr/local/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin
[15:16:21.449] Checking ssh with "ssh -V"
[15:16:21.460] > OpenSSH_9.6p1, LibreSSL 3.3.6

[15:16:21.462] Using SSH config file "/Users/roblabs/.ssh/config"
[15:16:21.463] Running script with connection command: ssh -T -D 50219 -o ConnectTimeout=15 -F '/Users/roblabs/.ssh/config' m1remote bash
[15:16:21.793] > ssh: connect to host 192.168.1.31 port 22: No route to host
[15:16:21.793] Got some output, clearing connection timeout
[15:16:22.015] "install" terminal command done
[15:16:22.015] Install terminal quit with output: ssh: connect to host 192.168.1.31 port 22: No route to host
[15:16:22.015] Received install output: ssh: connect to host 192.168.1.31 port 22: No route to host
[15:16:22.017] Resolver error: Error: No route to host
	at g.Offline (/Users/roblabs/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:499969)
	at /Users/roblabs/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:496032
	at t.handleInstallOutput (/Users/roblabs/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:496175)
	at t.tryInstall (/Users/roblabs/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:621085)
	at async /Users/roblabs/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:580730
	at async t.withShowDetailsEvent (/Users/roblabs/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:584036)
	at async k (/Users/roblabs/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:577649)
	at async t.resolve (/Users/roblabs/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:581407)
	at async /Users/roblabs/.vscode/extensions/ms-vscode-remote.remote-ssh-0.112.0/out/extension.js:2:848023
[15:16:22.019] ------




[15:16:22.237] Opening exec server for ssh-remote+m1remote
[15:16:22.246] Initizing new exec server for ssh-remote+m1remote
[15:16:22.248] Using commit id "611f9bfce64f25108829dd295f54a6894e87339d" and quality "stable" for server
[15:16:22.250] Install and start server if needed
[15:16:22.256] Using SSH config file "/Users/roblabs/.ssh/config"
[15:16:22.257] Running script with connection command: ssh -T -D 50221 -o ConnectTimeout=15 -F '/Users/roblabs/.ssh/config' m1remote bash
[15:16:22.365] > ssh: connect to host 192.168.1.31 port 22: No route to host
[15:16:22.365] Got some output, clearing connection timeout
[15:16:22.589] "install" terminal command done
[15:16:22.589] Install terminal quit with output: ssh: connect to host 192.168.1.31 port 22: No route to host
[15:16:22.589] Received install output: ssh: connect to host 192.168.1.31 port 22: No route to host
[15:16:22.589] Exec server for ssh-remote+m1remote failed: Error: No route to host
[15:16:22.589] Error opening exec server for ssh-remote+m1remote: Error: No route to host

</pre>
</details>

**Comment by roblourens** [comment]
It's weird that this would work outside of vscode because we just run that command in a terminal, and that is the error that ssh reported.

Does the exact command `ssh -T -D 50219 -o ConnectTimeout=15 -F '/Users/roblabs/.ssh/config' m1remote bash` work in an external terminal?

**Comment by roblabs** [comment]
* This is the script I used before that worked
  * `code --folder-uri=vscode-remote://ssh-remote+m1remote/Users/roblabs/somefolder_on_m1remote`

---

> *is there something else different in the external terminal environment?*
* both are using the same Zsh

---

> *Does the exact command ... work?*
* The command `ssh -T -D 50219 -o ConnectTimeout=15 -F '/Users/roblabs/.ssh/config' m1remote bash` hangs, as in *no response*.
* `ssh m1.local` works fine
* Using VScode-remote works from a Windows machine + VScode.exe running + connecting to `m1remote`
* just not on macOS Sequoia Beta

**Comment by roblabs** [comment]
I sorted out my issue with the Remote SSH.  When I upgraded to macOS Sequoia Beta, it reset (or I didn't notice) that I had to allow the proper access.  System Settings -> Privacy & Security -> Allow VSC access to the *Local Network*.

![image](https://github.com/microsoft/vscode-remote-release/assets/118112/0abfd324-2ae5-40ff-8742-4be63d2e85cd)
