### ISSUE TITLE
[Remote-SSH Bug]: Failed to parse remote port from server output (Solved)

### ISSUE THREAD

**Issue by yusijin02** [microsoft/vscode-remote-release#9982]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Steps To Reproduce

1. System: macOS Sonoma 14.5 (23F79)
2. VSCode Version:
```
Version: 1.85.2 (Universal)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:32.531Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.5.0
```
3. Config:
```
Host 4xRTX3090(185)
  HostName 116.57.73.185
  IdentityFile ~/.ssh/id_rsa
  PreferredAuthentications publickey
  User yusijin
```
4. Remote-SSH Version:
```
名称: Remote - SSH
ID: ms-vscode-remote.remote-ssh
说明: Open any folder on a remote machine using SSH and take advantage of VS Code's full feature set.
版本: 0.107.1
发布者: Microsoft
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh
```

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[17:38:41.508] Log Level: 2
[17:38:41.517] SSH Resolver called for "ssh-remote+7b22686f73744e616d65223a223478525458333039302831383529227d", attempt 1
[17:38:41.518] "remote.SSH.useLocalServer": true
[17:38:41.518] "remote.SSH.useExecServer": false
[17:38:41.518] "remote.SSH.path": undefined
[17:38:41.518] "remote.SSH.configFile": undefined
[17:38:41.519] "remote.SSH.useFlock": true
[17:38:41.519] "remote.SSH.lockfilesInTmp": false
[17:38:41.519] "remote.SSH.localServerDownload": auto
[17:38:41.519] "remote.SSH.remoteServerListenOnSocket": false
[17:38:41.519] "remote.SSH.showLoginTerminal": false
[17:38:41.519] "remote.SSH.defaultExtensions": []
[17:38:41.519] "remote.SSH.loglevel": 2
[17:38:41.520] "remote.SSH.enableDynamicForwarding": true
[17:38:41.520] "remote.SSH.enableRemoteCommand": false
[17:38:41.520] "remote.SSH.serverPickPortsFromRange": {}
[17:38:41.520] "remote.SSH.serverInstallPath": {}
[17:38:41.530] VS Code version: 1.85.2
[17:38:41.530] Remote-SSH version: remote-ssh@0.107.1
[17:38:41.530] darwin arm64
[17:38:41.533] SSH Resolver called for host: 4xRTX3090(185)
[17:38:41.533] Setting up SSH remote "4xRTX3090(185)"
[17:38:41.536] Acquiring local install lock: /var/folders/vh/t0g0clqn79j2csnf2bh09g6w0000gn/T/vscode-remote-ssh-e1706a96-install.lock
[17:38:41.537] Looking for existing server data file at /Users/yusijin/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-e1706a96-8b3775030ed1a69b13e4f4c628c612102e30a681-0.107.1-tr/data.json
[17:38:41.538] Using commit id "8b3775030ed1a69b13e4f4c628c612102e30a681" and quality "stable" for server
[17:38:41.544] Install and start server if needed
[17:38:41.547] PATH: /Users/yusijin/anaconda3/bin:/Users/yusijin/anaconda3/bin:/Users/yusijin/anaconda3/condabin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
[17:38:41.547] Checking ssh with "ssh -V"
[17:38:41.555] > OpenSSH_9.6p1, LibreSSL 3.3.6

[17:38:41.559] askpass server listening on /var/folders/vh/t0g0clqn79j2csnf2bh09g6w0000gn/T/vscode-ssh-askpass-7647357c869067ded1863812944f527044dfc69c.sock
[17:38:41.559] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/vh/t0g0clqn79j2csnf2bh09g6w0000gn/T/vscode-ssh-askpass-6ac5ec17d64ea1ca98860acbe94f4cf803b40b51.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","50738","-o","ConnectTimeout=15","4xRTX3090(185)"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/yusijin/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-e1706a96-8b3775030ed1a69b13e4f4c628c612102e30a681-0.107.1-tr/data.json"}
[17:38:41.559] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.9g6j78d7gm/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/yusijin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/yusijin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/vh/t0g0clqn79j2csnf2bh09g6w0000gn/T/vscode-ssh-askpass-7647357c869067ded1863812944f527044dfc69c.sock"}
[17:38:41.560] Spawned 1678
[17:38:41.708] > local-server-1> Running ssh connection command: "-v -T -D 50738 -o ConnectTimeout=15 4xRTX3090(185)"
[17:38:41.726] > local-server-1> Spawned ssh, pid=1685
[17:38:41.733] stderr> hostname contains invalid characters
[17:38:41.733] > local-server-1> ssh child died, shutting down
[17:38:41.737] Local server exit: 0
[17:38:41.737] Received install output: local-server-1> Running ssh connection command: "-v -T -D 50738 -o ConnectTimeout=15 4xRTX3090(185)"
local-server-1> Spawned ssh, pid=1685
hostname contains invalid characters
local-server-1> ssh child died, shutting down

[17:38:41.738] Failed to parse remote port from server output
[17:38:41.741] Resolver error: Error: 
	at g.Create (/Users/yusijin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:642703)
	at t.handleInstallOutput (/Users/yusijin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:640069)
	at e (/Users/yusijin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:700300)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /Users/yusijin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:722169
	at async t.withShowDetailsEvent (/Users/yusijin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:725828)
	at async /Users/yusijin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:697005
	at async C (/Users/yusijin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:695056)
	at async t.resolveWithLocalServer (/Users/yusijin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:696545)
	at async I (/Users/yusijin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:719392)
	at async t.resolve (/Users/yusijin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:723199)
	at async /Users/yusijin/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:907003
[17:38:41.746] ------
```

</p>
</details>

### Anything else?

1. I recently updated my macOS system, so I suspect that this might be the cause of the bug.
2. I can connect to the server normally using VSCode on Windows.
3. I have tried the following methods, but none have solved the problem:
    - restart my macOS system,
    - reinstall the Remote-SSH extension,
    - delete `~/.ssh/known_host` in macOS system,
    - delete `~/.vscode-server` in remote Linux system
4. This issue might be similar to #8292.
5. I'm willing to test out any suggested solution or to provide more info.

**Comment by roblourens** [comment]
This is an error from ssh itself `hostname contains invalid characters`

There are new requirements for ssh hostnames. Try removing the `()`

**Comment by yusijin02** [comment]
> This is an error from ssh itself `hostname contains invalid characters`
> 
> There are new requirements for ssh hostnames, coming from OpenSSH, not us. Try removing the `()`

Thanks a lot, your answer solved the bug
