### ISSUE TITLE
Node command not found

### ISSUE THREAD

**Issue by robertoneto-senior** [microsoft/vscode-remote-release#9985]
- VSCode Version: 1.90.1
- Local OS Version: 5.10.0-28-amd64 #1 SMP Debian 5.10.209-2 (2024-01-31) x86_64 GNU/Linux
- Remote OS Version: mcr.microsoft.com/devcontainers/dotnet:1-8.0-bookworm
- Remote Extension/Connection Type: Containers/WSL/Server

- Logs:
```
[34 ms] Dev Containers 0.369.0 in VS Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d).
[34 ms] Start: Resolving Remote
[56 ms] Setting up container for folder or workspace: /home/roberto.neto/sources/dotnet-oidc
[58 ms] Start: Check Docker is running
[58 ms] Start: Run: docker version
[80 ms] Client: Docker Engine - Community
 Version:           26.1.4
 API version:       1.45
 Go version:        go1.21.11
 Git commit:        5650f9b
 Built:             Wed Jun  5 11:29:31 2024
 OS/Arch:           linux/amd64
 Context:           default

[81 ms] Server: Docker Engine - Community
 Engine:
  Version:          26.1.4
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       de5c9cf
  Built:            Wed Jun  5 11:29:31 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
[83 ms] Start: Run: docker volume ls -q
[99 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/roberto.neto/sources/dotnet-oidc --filter label=vsch.quality=stable
[112 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/roberto.neto/sources/dotnet-oidc --filter label=devcontainer.config_file=/home/roberto.neto/sources/dotnet-oidc/.devcontainer/devcontainer.json
[132 ms] Start: Run: docker inspect --type container b7b5eb8c7b94
[147 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/roberto.neto/sources/dotnet-oidc
[162 ms] Start: Run: docker inspect --type container b7b5eb8c7b94
[177 ms] Running Dev Containers CLI:   read-configuration --workspace-folder /home/roberto.neto/sources/dotnet-oidc --id-label devcontainer.local_folder=/home/roberto.neto/sources/dotnet-oidc --id-label devcontainer.config_file=/home/roberto.neto/sources/dotnet-oidc/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/roberto.neto/sources/dotnet-oidc/.devcontainer/devcontainer.json --mount-workspace-git-root
[177 ms] Start: Run: /usr/share/code/code /home/roberto.neto/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/roberto.neto/sources/dotnet-oidc --id-label devcontainer.local_folder=/home/roberto.neto/sources/dotnet-oidc --id-label devcontainer.config_file=/home/roberto.neto/sources/dotnet-oidc/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/roberto.neto/sources/dotnet-oidc/.devcontainer/devcontainer.json --mount-workspace-git-root
[371 ms] @devcontainers/cli 0.62.0. Node.js v20.9.0. linux 5.10.0-28-amd64 x64.
[371 ms] Start: Run: git rev-parse --show-cdup
[377 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/roberto.neto/sources/dotnet-oidc --filter label=devcontainer.config_file=/home/roberto.neto/sources/dotnet-oidc/.devcontainer/devcontainer.json
[391 ms] Start: Run: docker inspect --type container b7b5eb8c7b94
[410 ms] Running Dev Containers CLI:   up --user-data-folder /home/roberto.neto/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-26e8f838-500b-4faf-bc65-df0168ca39de1718734011931 --workspace-folder /home/roberto.neto/sources/dotnet-oidc --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/roberto.neto/sources/dotnet-oidc --id-label devcontainer.config_file=/home/roberto.neto/sources/dotnet-oidc/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/roberto.neto/sources/dotnet-oidc/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[410 ms] Start: Run: /usr/share/code/code /home/roberto.neto/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/roberto.neto/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-26e8f838-500b-4faf-bc65-df0168ca39de1718734011931 --workspace-folder /home/roberto.neto/sources/dotnet-oidc --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/roberto.neto/sources/dotnet-oidc --id-label devcontainer.config_file=/home/roberto.neto/sources/dotnet-oidc/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/roberto.neto/sources/dotnet-oidc/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[596 ms] @devcontainers/cli 0.62.0. Node.js v20.9.0. linux 5.10.0-28-amd64 x64.
[596 ms] Start: Run: docker buildx version
[642 ms] github.com/docker/buildx v0.14.1 59582a8
[642 ms] 
[643 ms] Start: Run: docker -v
[655 ms] Start: Resolving Remote
[657 ms] Start: Run: git rev-parse --show-cdup
[663 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/roberto.neto/sources/dotnet-oidc --filter label=devcontainer.config_file=/home/roberto.neto/sources/dotnet-oidc/.devcontainer/devcontainer.json
[677 ms] Start: Run: docker inspect --type container b7b5eb8c7b94
[691 ms] Start: Starting container
[691 ms] Start: Run: docker start b7b5eb8c7b9475da11e16316c162f74b64277dedf831a889f5b7c4ac5d96c4ba
[869 ms] b7b5eb8c7b9475da11e16316c162f74b64277dedf831a889f5b7c4ac5d96c4ba
[871 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/roberto.neto/sources/dotnet-oidc --filter label=devcontainer.config_file=/home/roberto.neto/sources/dotnet-oidc/.devcontainer/devcontainer.json
[885 ms] Start: Run: docker inspect --type container b7b5eb8c7b94
[900 ms] Start: Inspecting container
[900 ms] Start: Run: docker inspect --type container b7b5eb8c7b9475da11e16316c162f74b64277dedf831a889f5b7c4ac5d96c4ba
[913 ms] Start: Run in container: /bin/sh
[917 ms] Start: Run in container: uname -m
[955 ms] x86_64
[955 ms] 
[955 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[956 ms] PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[956 ms] 
[956 ms] Start: Run in container:  (command -v getent >/dev/null 2>&1 && getent passwd 'vscode' || grep -E '^vscode|^[^:]*:[^:]*:vscode:' /etc/passwd || true)
[957 ms] Start: Run in container: test -f '/var/devcontainer/.patchEtcEnvironmentMarker'
[958 ms] 
[958 ms] 
[958 ms] Start: Run in container: test -f '/var/devcontainer/.patchEtcProfileMarker'
[958 ms] 
[958 ms] 
[965 ms] Start: Run: docker inspect --type container b7b5eb8c7b9475da11e16316c162f74b64277dedf831a889f5b7c4ac5d96c4ba
[980 ms] Start: Run: docker exec -i -u root b7b5eb8c7b9475da11e16316c162f74b64277dedf831a889f5b7c4ac5d96c4ba /bin/sh -c echo "New container started. Keep-alive process started." ; export VSCODE_REMOTE_CONTAINERS_SESSION=26e8f838-500b-4faf-bc65-df0168ca39de1718734011931 ; /bin/sh
[981 ms] Running Dev Containers CLI:   read-configuration --workspace-folder /home/roberto.neto/sources/dotnet-oidc --id-label devcontainer.local_folder=/home/roberto.neto/sources/dotnet-oidc --id-label devcontainer.config_file=/home/roberto.neto/sources/dotnet-oidc/.devcontainer/devcontainer.json --container-id b7b5eb8c7b9475da11e16316c162f74b64277dedf831a889f5b7c4ac5d96c4ba --log-level debug --log-format json --config /home/roberto.neto/sources/dotnet-oidc/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root
[985 ms] Start: Run: /usr/share/code/code /home/roberto.neto/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/roberto.neto/sources/dotnet-oidc --id-label devcontainer.local_folder=/home/roberto.neto/sources/dotnet-oidc --id-label devcontainer.config_file=/home/roberto.neto/sources/dotnet-oidc/.devcontainer/devcontainer.json --container-id b7b5eb8c7b9475da11e16316c162f74b64277dedf831a889f5b7c4ac5d96c4ba --log-level debug --log-format json --config /home/roberto.neto/sources/dotnet-oidc/.devcontainer/devcontainer.json --include-merged-configuration --mount-workspace-git-root
[1033 ms] New container started. Keep-alive process started.
[1191 ms] @devcontainers/cli 0.62.0. Node.js v20.9.0. linux 5.10.0-28-amd64 x64.
[1191 ms] Start: Run: git rev-parse --show-cdup
[1198 ms] Start: Run: docker inspect --type container b7b5eb8c7b9475da11e16316c162f74b64277dedf831a889f5b7c4ac5d96c4ba
[1219 ms] Start: Inspecting container
[1219 ms] Start: Run: docker inspect --type container b7b5eb8c7b9475da11e16316c162f74b64277dedf831a889f5b7c4ac5d96c4ba
[1234 ms] Start: Run in container: /bin/sh
[1237 ms] Start: Run in container: uname -m
[1276 ms] x86_64
[1276 ms] 
[1276 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[1277 ms] PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[1277 ms] 
[1277 ms] Start: Run in container:  (command -v getent >/dev/null 2>&1 && getent passwd 'vscode' || grep -E '^vscode|^[^:]*:[^:]*:vscode:' /etc/passwd || true)
[1279 ms] Start: Setup shutdown monitor
[1279 ms] Forking shutdown monitor: /home/roberto.neto/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/shutdown/shutdownMonitorProcess /run/user/1001/vscode-remote-containers-0048a97f-fae1-4758-82d6-16c1db78942a.sock singleContainer Debug /home/roberto.neto/.config/Code/logs/20240618T145917/window1/exthost/ms-vscode-remote.remote-containers 1718734012502
[1286 ms] Start: Run in container: test -d '/home/vscode/.vscode-server'
[1286 ms] 
[1287 ms] 
[1287 ms] Start: Run in container: test ! -f '/home/vscode/.vscode-server/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/home/vscode/.vscode-server/data/Machine' && { > '/home/vscode/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[1287 ms] 
[1288 ms] 
[1288 ms] Exit code 1
[1288 ms] Start: Run in container: cat /home/vscode/.vscode-server/data/Machine/settings.json
[1289 ms] 
[1289 ms] cat: /home/vscode/.vscode-server/data/Machine/settings.json: No such file or directory
[1289 ms] Exit code 1
[1289 ms] Start: Run in container: test -d '/home/vscode/.vscode-server/bin/611f9bfce64f25108829dd295f54a6894e87339d'
[1289 ms] 
[1290 ms] 
[1290 ms] Start: Run in container: test -d '/vscode/vscode-server/bin/linux-x64/611f9bfce64f25108829dd295f54a6894e87339d'
[1290 ms] 
[1290 ms] 
[1290 ms] Start: Run in container: /bin/sh
[1293 ms] Start: Run in container: test -x '/home/vscode/.vscode-server/bin/611f9bfce64f25108829dd295f54a6894e87339d/bin/helpers/check-requirements.sh'
[1294 ms] Start: Run in container: touch '/vscode/vscode-server/bin/linux-x64/611f9bfce64f25108829dd295f54a6894e87339d'
[1294 ms] 
[1294 ms] 
[1294 ms] Start: Run in container: '/home/vscode/.vscode-server/bin/611f9bfce64f25108829dd295f54a6894e87339d/bin/helpers/check-requirements.sh'
[1320 ms] 
[1321 ms] 
[1321 ms] Start: Launching Dev Containers helper.
[1321 ms] ssh-agent: SSH_AUTH_SOCK in container (/tmp/vscode-ssh-auth-7e2a5d8b-c5f0-429f-88c0-9b800cd9ca64.sock) forwarded to local host (/run/user/1001/keyring/ssh).
[1321 ms] Start: Run in container: test -e /tmp/.X11-unix/X0
[1327 ms] 
[1327 ms] 
[1327 ms] Exit code 1
[1327 ms] Start: Run in container: mkdir -p '/tmp/.X11-unix'
[1328 ms] 
[1328 ms] 
[1329 ms] X11 forwarding: DISPLAY in container (:0) forwarded to local host (:1).
[1329 ms] Start: Run in container: gpgconf --list-dir agent-socket
[1330 ms] /home/vscode/.gnupg/S.gpg-agent
[1330 ms] 
[1330 ms] Start: Run in container: gpgconf --list-dir homedir
[1333 ms] /home/vscode/.gnupg
[1333 ms] 
[1334 ms] Start: Run in container: ls '/home/vscode/.gnupg/private-keys-v1.d' 2>/dev/null
[1335 ms] 
[1335 ms] 
[1335 ms] Exit code 2
[1335 ms] Start: Run: gpgconf --list-dir agent-extra-socket
[1341 ms] /run/user/1001/gnupg/S.gpg-agent.extra
[1341 ms] 
[1341 ms] Start: Run in container: mkdir -p -m 700 '/home/vscode/.gnupg'
[1341 ms] gpg-agent: Socket in container (/home/vscode/.gnupg/S.gpg-agent) forwarded to local host (/run/user/1001/gnupg/S.gpg-agent.extra).
[1342 ms] 
[1342 ms] 
[1342 ms] Start: Run in container: command -v docker >/dev/null 2>&1
[1342 ms] Start: Run: gpgconf --list-dir homedir
[1345 ms] 
[1345 ms] 
[1346 ms] Exit code 127
[1346 ms] Start: Run in container: /bin/sh
[1351 ms] userEnvProbe: loginInteractiveShell (default)
[1351 ms] Start: Run in container: test -f '/tmp/devcontainers-26e8f838-500b-4faf-bc65-df0168ca39de1718734011931/env-loginInteractiveShell.json'
[1351 ms] Start: Run in container: echo ~
[1353 ms] 
[1353 ms] 
[1353 ms] Exit code 1
[1354 ms] userEnvProbe: not found in cache
[1354 ms] userEnvProbe shell: /bin/bash
[1355 ms] /home/roberto.neto/.gnupg
[1355 ms] 
[1355 ms] Start: Run in container: gpgconf --list-dir homedir
[1356 ms] 
[1356 ms] 
[1356 ms] /home/vscode/.gnupg
[1357 ms] 
[1357 ms] Start: Run in container: # Test for /home/vscode/.ssh/known_hosts and ssh
[1357 ms] /home/vscode/.ssh/known_hosts exists
[1358 ms] 
[1358 ms] Exit code 1
[1358 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --system --replace-all credential.helper '!f() { /home/vscode/.vscode-server/bin/611f9bfce64f25108829dd295f54a6894e87339d/node /tmp/vscode-remote-containers-7e2a5d8b-c5f0-429f-88c0-9b800cd9ca64.js git-credential-helper $*; }; f' || true
[1358 ms] Start: Run in container: # Test for /home/vscode/.gnupg/pubring.kbx and gpg
[1360 ms] /home/vscode/.gnupg/pubring.kbx exists
[1360 ms] 
[1360 ms] Exit code 1
[1361 ms] 
[1361 ms] 
[1361 ms] Start: Run in container: for pid in `cd /proc && ls -d [0-9]*`; do { echo $pid ; readlink /proc/$pid/cwd || echo ; readlink /proc/$pid/ns/mnt || echo ; cat /proc/$pid/stat | tr "
[1400 ms] Start: Run in container: # Test for /home/vscode/.gnupg/trustdb.gpg and gpg
[1401 ms] /home/vscode/.gnupg/trustdb.gpg exists
[1401 ms] 
[1401 ms] Exit code 1
[1401 ms] Start: Run in container: cat '/home/vscode/.vscode-server/bin/611f9bfce64f25108829dd295f54a6894e87339d/product.json'
[1401 ms] Start: Run: gpg-connect-agent updatestartuptty /bye
[1407 ms] Start: Run in container: cat '/home/vscode/.vscode-server/data/Machine/.connection-token-611f9bfce64f25108829dd295f54a6894e87339d' 2>/dev/null || (umask 377 && echo '1fc8bcc2-2042-49f1-a360-9c7de5ab9fa8' >'/home/vscode/.vscode-server/data/Machine/.connection-token-611f9bfce64f25108829dd295f54a6894e87339d-ccbd8808-bf43-4dff-93b3-0843c2225be0' && mv -n '/home/vscode/.vscode-server/data/Machine/.connection-token-611f9bfce64f25108829dd295f54a6894e87339d-ccbd8808-bf43-4dff-93b3-0843c2225be0' '/home/vscode/.vscode-server/data/Machine/.connection-token-611f9bfce64f25108829dd295f54a6894e87339d' && rm -f '/home/vscode/.vscode-server/data/Machine/.connection-token-611f9bfce64f25108829dd295f54a6894e87339d-ccbd8808-bf43-4dff-93b3-0843c2225be0' && cat '/home/vscode/.vscode-server/data/Machine/.connection-token-611f9bfce64f25108829dd295f54a6894e87339d')
[1407 ms] /home/vscode
[1408 ms] 
[1408 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-7e2a5d8b-c5f0-429f-88c0-9b800cd9ca64.js' >/tmp/vscode-remote-containers-7e2a5d8b-c5f0-429f-88c0-9b800cd9ca64.js
[1409 ms] 73757d37-1d25-479e-8246-9709db43ea26
[1409 ms] 
[1410 ms] Start: Starting VS Code Server
[1410 ms] Start: Preparing Extensions
[1410 ms] Start: Run in container: test ! -f '/home/vscode/.vscode-server/data/Machine/.installExtensionsMarker' && set -o noclobber && mkdir -p '/home/vscode/.vscode-server/data/Machine' && { > '/home/vscode/.vscode-server/data/Machine/.installExtensionsMarker' ; } 2> /dev/null
[1412 ms] 
[1412 ms] 
[1412 ms] Exit code 1
[1413 ms] Extensions cache, install extensions: None
[1413 ms] Start: Run in container: test -d /home/vscode/.vscode-server/extensionsCache && ls /home/vscode/.vscode-server/extensionsCache || true
[1413 ms] 
[1413 ms] 
[1413 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-7e2a5d8b-c5f0-429f-88c0-9b800cd9ca64.js' >/tmp/vscode-remote-containers-server-7e2a5d8b-c5f0-429f-88c0-9b800cd9ca64.js_1718734013915
[1414 ms] dbaeumer.vscode-eslint-2.4.4
dbaeumer.vscode-eslint-3.0.10
ms-dotnettools.csharp-2.33.17-linux-x64
ms-dotnettools.vscode-dotnet-runtime-2.0.6
ms-python.debugpy-2024.4.0-linux-x64
ms-python.python-2024.4.1
ms-python.vscode-pylance-2024.4.1
streetsidesoftware.code-spell-checker-3.0.1
[1415 ms] 
[1415 ms] Start: Run in container: test -d /vscode/vscode-server/extensionsCache && ls /vscode/vscode-server/extensionsCache || true
[1416 ms] dbaeumer.vscode-eslint-2.4.4
dbaeumer.vscode-eslint-3.0.10
ms-dotnettools.csharp-2.33.17-linux-x64
ms-dotnettools.vscode-dotnet-runtime-2.0.6
ms-python.debugpy-2024.4.0-linux-x64
ms-python.python-2024.4.1
ms-python.vscode-pylance-2024.4.1
streetsidesoftware.code-spell-checker-3.0.1
[1416 ms] 
[1417 ms] Extensions cache, link in container: None
[1417 ms] Optimizing extensions for quality: stable
[1417 ms] Start: Run in container: /home/vscode/.vscode-server/bin/611f9bfce64f25108829dd295f54a6894e87339d/bin/code-server --log debug --force-disable-user-env --server-data-dir /home/vscode/.vscode-server --use-host-proxy --telemetry-level all --accept-server-license-terms --host 127.0.0.1 --port 0 --connection-token-file /home/vscode/.vscode-server/data/Machine/.connection-token-611f9bfce64f25108829dd295f54a6894e87339d --extensions-download-dir /home/vscode/.vscode-server/extensionsCache --start-server --disable-websocket-compression --skip-requirements-check
[1421 ms] 
[1421 ms] 
[1423 ms] Container server: /bin/sh: 32: /home/vscode/.vscode-server/bin/611f9bfce64f25108829dd295f54a6894e87339d/node: not found
[1427 ms] Error reading shell environment.
[1427 ms] Error: stream ended with:0 but wanted:9
        at l (/home/roberto.neto/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/extension/extension.js:27:22149)
        at /home/roberto.neto/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/extension/extension.js:27:22330
        at s (/home/roberto.neto/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/extension/extension.js:30:5371)
        at Socket.<anonymous> (/home/roberto.neto/.vscode/extensions/ms-vscode-remote.remote-containers-0.369.0/dist/extension/extension.js:30:5541)
        at Socket.emit (node:events:526:35)
        at endReadableNT (node:internal/streams/readable:1408:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[1427 ms] Start: Run in container: mkdir -p '/tmp/devcontainers-26e8f838-500b-4faf-bc65-df0168ca39de1718734011931' && cat > '/tmp/devcontainers-26e8f838-500b-4faf-bc65-df0168ca39de1718734011931/env-loginInteractiveShell.json' << 'envJSON'
[1428 ms] Container server terminated (code: 127, signal: null).
[1430 ms] 
[1430 ms] 
[1469 ms] /home/vscode/.vscode-server/bin/611f9bfce64f25108829dd295f54a6894e87339d/bin/code-server: 12: /vscode/vscode-server/bin/linux-x64/611f9bfce64f25108829dd295f54a6894e87339d/node: not found
[1474 ms] Command failed: /home/vscode/.vscode-server/bin/611f9bfce64f25108829dd295f54a6894e87339d/bin/code-server --log debug --force-disable-user-env --server-data-dir /home/vscode/.vscode-server --use-host-proxy --telemetry-level all --accept-server-license-terms --host 127.0.0.1 --port 0 --connection-token-file /home/vscode/.vscode-server/data/Machine/.connection-token-611f9bfce64f25108829dd295f54a6894e87339d --extensions-download-dir /home/vscode/.vscode-server/extensionsCache --start-server --disable-websocket-compression --skip-requirements-check
[1475 ms] /home/vscode/.vscode-server/bin/611f9bfce64f25108829dd295f54a6894e87339d/bin/code-server: 12: /vscode/vscode-server/bin/linux-x64/611f9bfce64f25108829dd295f54a6894e87339d/node: not found
[1475 ms] Exit code 127
```

Steps to Reproduce:

1. Create a new devcontainer configuration for dotnet
2. Try to reopen it on remote folder

Does this issue occur when you try this locally?: Yes
Does this issue occur when you try this locally and all extensions are disabled?: Yes

I tried to clean all my docker images, networks, volumes, etc... and start a new vscode profile with only the devcontainer extension, but the problems continues.

**Comment by robertoneto-senior** [comment]
[Complete logs](https://github.com/user-attachments/files/15890924/erro-devcontainer.txt).

**Comment by robertoneto-senior** [comment]
@chrmarti  Excuse my ignorance, but how do I do this? 

I was cleanning up my docker with:

```bash
docker kill `docker ps -q` && docker rm `docker ps -aq` && docker rmi `docker images -q` -f || true && docker network prune -f || true && docker system prune -af || docker volume ls --format json | jq -r '.Name' | xargs docker volume rm
```
But how do I do this " remove the vscode volume"?

**Comment by robertoneto-senior** [comment]
@chrmarti

I was cleaning up my docker with:

```bash
docker kill `docker ps -q` && docker rm `docker ps -aq` && docker rmi `docker images -q` -f \
  || true && docker network prune -f \
  || true && docker system prune -af \
  || docker volume ls --format json | jq -r '.Name' | xargs docker volume rm
```

I noted that this `docker volume ls --format json` wasn't printing the correct output. Here is an example of this command output:

```
$ docker volume ls --format json
json
```
I changed this command `docker volume ls --format json | jq -r '.Name' | xargs docker volume rm` to this:
```bash
docker volume ls --format '{{json .Name}}' | jq -rM | xargs docker volume rm
```
Now all my volumes are also been removed.

And my devcontainers started to work again!!!

**Comment by robertoneto-senior** [comment]
@chrmarti I was able to resolve the `node: not found` error by removing the volume correctly. I algo updated my docker engine from 20.x to 26.1.4.

But now I'm facing a new bug.

The container is starting but devcontainer extension isn't able to connect to the remote container due to this error:

```
[2024-06-19T12:24:33.024Z] Port forwarding 47436 > 44517 > 44517 terminated by extension (closed) with code 126 and signal null.
[2024-06-19T12:24:33.032Z] Port forwarding connection from 47452 > 44517 > 44517 in the container.
[2024-06-19T12:24:33.033Z] Start: Run in container: /home/vscode/.vscode-server/bin/611f9bfce64f25108829dd295f54a6894e87339d/node -e 
[2024-06-19T12:24:33.157Z] Port forwarding 47452 > 44517 > 44517: Local close
[2024-06-19T12:24:33.162Z] Stop (129 ms): Run in container: /home/vscode/.vscode-server/bin/611f9bfce64f25108829dd295f54a6894e87339d/node -e 
[2024-06-19T12:24:33.163Z] Port forwarding 47452 > 44517 > 44517 terminated by extension (closed) with code 126 and signal null.
```

Full log: [devcontainer-error.log](https://github.com/user-attachments/files/15901477/devcontainer-error.log)

**Comment by robertoneto-senior** [comment]
@chrmarti 

Another strange think is, every time I first run the devcontainer, the vscode server starts with the "node" executable... But, if I close it and rerun it, that error `node: not found` starts to happen again.

So, I cleanup my docker again, reopen the devcontainer to force complete rebuild, and this time (after the container was running) I connected to it to verify the node is running and to verify that the executable was realy there.... and here is the result:

```bash
root ➜ / $ ps -ef
UID          PID    PPID  C STIME TTY          TIME CMD
root           1       0  0 13:39 ?        00:00:00 /bin/sh -c echo Container started trap "exit 0" 15  exec "$@" while sleep 1 & wait $!; do :; done -
root          34       0  0 13:39 ?        00:00:00 /bin/sh -c echo "New container started. Keep-alive process started." ; export VSCODE_REMOTE_CONTAINERS_SESSION=ba740e01-f868-48ea-aaa6-d2664c202e451718804311593 ; /bin/sh
root          40      34  0 13:39 ?        00:00:00 /bin/sh
vscode        41       0  0 13:39 ?        00:00:00 /bin/sh
root          60       0  0 13:39 ?        00:00:00 /bin/sh
vscode       189       0  0 13:39 ?        00:00:00 /bin/sh
vscode       248     189  0 13:39 ?        00:00:00 /home/vscode/.vscode-server/bin/611f9bfce64f25108829dd295f54a6894e87339d/node /tmp/vscode-remote-containers-server-7d758ceb-5491-468a-8535-cad53eed9d6a.js
vscode       255       0  0 13:39 ?        00:00:00 sh /home/vscode/.vscode-server/bin/611f9bfce64f25108829dd295f54a6894e87339d/bin/code-server --log debug --force-disable-user-env --server-data-dir /home/vscode/.vscode-server --use-host-
vscode       268     255 42 13:39 ?        00:00:13 /vscode/vscode-server/bin/linux-x64/611f9bfce64f25108829dd295f54a6894e87339d/node /vscode/vscode-server/bin/linux-x64/611f9bfce64f25108829dd295f54a6894e87339d/out/server-main.js --log de
vscode       360     268  0 13:39 ?        00:00:00 /vscode/vscode-server/bin/linux-x64/611f9bfce64f25108829dd295f54a6894e87339d/node /vscode/vscode-server/bin/linux-x64/611f9bfce64f25108829dd295f54a6894e87339d/out/bootstrap-fork --type=p
root         504       0  0 13:40 pts/0    00:00:00 /bin/bash
root         539       1  0 13:40 ?        00:00:00 sleep 1
root         540     504  0 13:40 pts/0    00:00:00 ps -ef
root ➜ / $ /home/vscode/.vscode-server/bin/611f9bfce64f25108829dd295f54a6894e87339d/node
bash: /home/vscode/.vscode-server/bin/611f9bfce64f25108829dd295f54a6894e87339d/node: No such file or directory
```
Note that, the "vscode server node process" is running, but if I try to run the node command alone it fails with `No such file or directory`.
